### ISSUE TITLE
Ubuntu Rendering Issue When There is a Long View or Trigger

### ISSUE THREAD

**Issue by christopherthompson81** [sqlitebrowser/sqlitebrowser#1001]
### Ubuntu Rendering Issue When There is a Long View or Trigger

There is a rendering issue on the 'Database Structure' tab when using DB Browser for SQLite under Ubuntu when there is a long view or trigger. I suspect there is some problem with limitless horizontal scrolling.

See attached screen-shot:

![dbfs_rendering_bug](https://cloud.githubusercontent.com/assets/2651473/25585812/9dd0472a-2e59-11e7-851a-322627cf196d.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:Ubuntu 16.04 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: 3.9.99

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oh, that's interesting.  Is the data set which you're using to trigger that, a public one?

Just thinking that might be helpful for debugging. :smile:

**Comment by christopherthompson81** [comment]
It happens before I've loaded any data. The trigger is something I'm
writing and related to Canadian taxes. You could probably reproduce it with
multiple kilobytes of random 'ipsum lorem' comments above a simple select
type view. I can probably make a demonstration database that would exhibit
the error if you're interested.

**Comment by justinclift** [comment]
Yep, definitely interested, that would really help. :smile:

**Comment by MKleusberg** [comment]
I've just prepared a test database containing two long lorem ipsum views. ```xx``` is one long line, ```yy``` are many lines. Not sure if they are long enough though. For both views it's struggling (```xx``` prints one long empty line as a tooltip, ```yy``` fills the entire screen with its tooltip) but I never get the weird output from your screenshot.

@justinclift Do you still have an Ubuntu VM somewhere to test this? I've only tryed this on KDE. My test db is [here](https://dev1.dbhub.io/mkleusberg/issue1001.db).

**Comment by justinclift** [comment]
@Yep, I can test this.  My Ubuntu VM is really Kubuntu, but it's pretty easy to download standard Ubuntu 16.04 and whip up a new one.  I'll add this to my task list for this week.

**Comment by justinclift** [comment]
Aha, I ***knew*** this sounded familiar.  Pretty sure this bug is another occurance of #920, and the solution is to compile it against a newer Qt library.

**Comment by justinclift** [comment]
@MKleusberg As a data point, just tried your test database on an Ubuntu 16.04.2 VM here, compiling using Qt 5.6 (from [a 3rd party PPA](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/stable-phone-overlay)).

No rendering issue like the above showed up, ***but*** the "Database Structure" tab took ages (~9.5 seconds) to show up.  Switching from "Database Structure" to any of the other tabs was instant.  From them back to "Database Structure"... wait 9.5 seconds again.  Every time.

So, something not quite right there.  Possibly just something weird with the VM, VMware Fusion, or whatever else too.  I'll muck around with a few settings next and see if that fixes the problem.

**Comment by justinclift** [comment]
Well, it's not caused by VMware Fusion's implementation of "Graphics Acceleration" for Linux.  Same problem both ways.

**Comment by justinclift** [comment]
Tried it with a fresh build using Qt 5.5 (with the initial compatiblity patch) instead.  Same behaviour with that database.

Using a different database (eg [this](https://dev1.dbhub.io/justinclift/Belfast%20Bikes%20Docking%20Stations.sqlite)), DB4S has no delay.  The "Database Structure" tab shows immediately when switching at all times.

**Comment by justinclift** [comment]
Ahh, this is interesting.  I just installed Qt 5.8 from the official Qt download site (qt.io).  When DB4S is compiled using that, the slowness issue isn't present.

Looks like whatever the problem is, it's been fixed sometime after Qt 5.6.1.

**Comment by justinclift** [comment]
Qt 5.7 doesn't have the problem either.

It really look like both Qt 5.5 and 5.6 on Ubuntu aren't fantastic for DB4S.  For anyone having weird slowness or screen corruption issues, it'll need to be compiling using Qt 5.7 or above instead.

**Comment by justinclift** [comment]
Yep.  If you want to do it, then go for it.  Otherwise I'll get it done later on today. :smile:

**Comment by MKleusberg** [comment]
@justinclift Done :smiley:

**Comment by justinclift** [comment]
@christopherthompson81 Did you ever get around to trying a build created with a newer version of Qt?  eg something that shouldn't have this rendering problem

**Comment by karim** [comment]
Closing this due to lack of response.
