### ISSUE TITLE
Problems with setting up dev environment for Win x64

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [sqlitebrowser/sqlitebrowser#1009]
### Details for the issue

Couple of problems encountered with [the instructions:](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S)
- the `C:\dev\SQLite` folder should apparently be named `C:\dev\SQLite-Win64`
- `vcredist_x64` should apparently be put in `C:\dev\dependencies`, not `C:\git_repos\sqlitebrowser\deps`

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:7 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: roll-your-own

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Cool.  Everyone has write access to the wiki, so it's updatable if you've the time and inclination yourself.

If not, leave this here and we'll get around to it... er... sometime. 😁

**Comment by h4yn0nnym0u5e** [comment]
Happy to edit the wiki myself ... er ... sometime. Not sure if the above is indicative of other things that have changed but didn't happen to bite me - is that likely? I may have made myself difficulties by installing VS 2013 last, as it's a 5Gb download so I did other installs first while it was downloading, then looped back to do the stuff I couldn't do because it wasn't installed.

**Comment by justinclift** [comment]
Nah, I knew the directories needed changing... I just hadn't gotten around to it.  Personal prioritisation + laziness at times. 😉

**Comment by chrisjlocke** [comment]
> the C:\dev\SQLite folder should apparently be named C:\dev\SQLite-Win64

Are you sure?  Does that depend whether you're building an x32 or x64 flavour of DB4S?  Can't remember what I did last time, but all seemed to work OK.  I'll go through the building steps again and have a play.

**Comment by justinclift** [comment]
@chrisjlocke Yeah, some paths needing updating in the CMakeLists.txt file after I wrote the initial guide:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/0c8cb4ec1dc37f2d971d23cc68376de13a24e54c/CMakeLists.txt#L20-L30

... and I kind of didn't update the screenshots afterwards... 👼

**Comment by chrisjlocke** [comment]
Excellent.  OK, leave it with me.  🐮

**Comment by chrisjlocke** [comment]
Corrected. 🥀

**Comment by justinclift** [comment]
Awesome, thanks @chrisjlocke. :smile:

**Comment by chrisjlocke** [comment]
![image](https://cloud.githubusercontent.com/assets/7872218/26059282/1ffcb16e-3979-11e7-9104-55903a91cdc9.png)
