### ISSUE TITLE
Double clicking an expression column row in new Edit Index dialog removes the row

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1012]
While trying things out in the new Edit Index dialog, something strange happened.

Double clicking on an "expression column" row in the right hand side (eg expecting to be able to edit the text) instead removed the row.

I've created a screencast, which I'll attach in a few minutes.

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/issue_uploads/DB4S%20Issue%201012.mp4

**Comment by justinclift** [comment]
At a guess, without looking at the code, it's probably related to the double click action normally swapping the row between the left and right window panes.

Expression column rows seem to get deleted instead of being transferred to the left hand side.  eg clicking the left arrow button on an expression column also nukes the row.

**Comment by MKleusberg** [comment]
Yeah, this isn't optimal. You can edit the expression column by clicking it (to select it) and then clicking again (to start editing) but if you do it to fast it counts as a double click and the column is removed entirely. That's probably a little too frustrating even if you know about the two separate clicks :wink: I'll probably disable the double click action for expression columns, so that you'll have to use the button for that. Also I could add an 'Are you sure?' message box when trying to remove an expression column. Then it wouldn't be necessary to move it to the left table view which I would find confusing as well because it doesn't really make sense for an expression column to the in the 'Table columns' list and, if you've decided to remove an expression column (and didn't do so by mistake), you'll probably not want to restore it only seconds later. Sound reasonable? :smiley:

**Comment by justinclift** [comment]
Hmmm, would it be feasible to have the double click action for expression columns trigger the "edit text" mode?  Same as the two slow clicks you describe above.

**Comment by MKleusberg** [comment]
Yep, should be doable :smiley:

**Comment by MKleusberg** [comment]
This should be fixed now. What do you think? Does it work this way? Double clicking doesn't seem to trigger the editing every time, probably because of some Qt thing I didn't investigate yet (and that we have in our Edit Table dialog too). But to me it seems good enough for now :wink:

**Comment by MKleusberg** [comment]
@justinclift Can we close this? :smile:

**Comment by justinclift** [comment]
Oh, I'd forgotten all about this.  I'm on an OSX desktop atm (good timing!) so I can check things right  now. :smile:

1 min...

**Comment by justinclift** [comment]
Just tried this out in the latest nightly build on OSX.

* Double clicking a column on the left side moves it to the right, as expected.
* Double clicking a column on the right side moves it to the left (consistently).  This seems completely fine behaviour, once I realised what it was doing.  No worries there.
* With an expression column though, things were a bit weird.
  * If the expression column **isn't** selected (eg a different one is), then double clicking on it allows it to be edited. eg it changes to a text field edit thing.
  * If the expression column **is** selected, then double clicking on it doesn't do anything.
  * If the expression column **is** selected, then single clicking on it allows it to be edited. eg it changes to a text field edit thing.

It kind of seems like the double click action for when the expression column **is** selected should also enable editing, to keep consistency.  Is that workable? :smile:

**Comment by MKleusberg** [comment]
You're right. That's still an issue. I'm not sure why though. We actually try to open the editor in both cases but the call sometimes fails and prints "edit: editing failed" to the console. There is plenty of questions and some answers regarding this message to find but none really helps. What helped most was this naive workaround:
```diff
diff --git a/src/EditIndexDialog.cpp b/src/EditIndexDialog.cpp
index 8c8ed76..9be6f0a 100644
--- a/src/EditIndexDialog.cpp
+++ b/src/EditIndexDialog.cpp
@@ -221,6 +221,7 @@ void EditIndexDialog::removeFromIndex(const QModelIndex& idx)
     // Instead just open the expression column for editing.
     if(index.column(row)->expression() && sender() != ui->buttonFromIndex)
     {
+        ui->tableIndexColumns->setItemSelected(ui->tableIndexColumns->item(row, 0), false);
         ui->tableIndexColumns->editItem(ui->tableIndexColumns->item(row, 0));
         return;
     }
```
Feel free to try it. It seems to reduce the likelihood that the editor isn't opened as expected but still fails when trying again and again, and if it fails with the patch it's even more irritating than before :wink: So not sure what to do here honestly :frowning: Maybe it's obvious to someone else?

**Comment by justinclift** [comment]
Just tried that change here on OSX.  After that I **can't** get the expression editor to be editable, no matter how many double clicks, of what type, etc I tried.  That change isn't a go-er.

I guess we can probably leave the current behaviour for now then.  It'll have to be "good enough". :smile:

**Comment by MKleusberg** [comment]
Interesting. This indicates to me that this could be a Qt-thing where the behaviour of the ```edit()``` call depends on the Qt version and/or the platform. So yeah, let's just leave it for now :wink:
