### ISSUE TITLE
Export indexes should respect tables selection

### ISSUE THREAD

**Issue by lvbeck** [sqlitebrowser/sqlitebrowser#1013]
### Details for the issue
currently if I export some database tables, the output sql file always contain indexes of all tables in the database, which means my selection of tables is ignored.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [x] Other: SQLite-2017-05-15-win64.exe

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, yeah... I can see how that'd be un-wanted. :smile:

@MKleusberg This sounds like exactly your kind of thing to look at. 😬

**Comment by justinclift** [comment]
So, something like this, and always with the most current entry (for each OS/architecture) in it?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/LATEST/

**Comment by MKleusberg** [comment]
Thanks for reporting this :smile: The issue should be fixed in the next nightly build. Are you ok to test if it's working for you, @lvbeck? But be warned that the latest nightlies (probably including the next one) are going to crash if you browse the same table twice. We're currently trying to find out why that is happening.

**Comment by lvbeck** [comment]
@MKleusberg sure, I can test the next nightly build, thank you for notice me the crash issue, I will use the nightly build with precaution.

**Comment by MKleusberg** [comment]
@lvbeck Any luck yet? :smile: With the latest few nightly builds the crash issue should be gone, too, by the way. So you'd be relatively safe to use them :wink:

**Comment by justinclift** [comment]
@lvbeck ping?

**Comment by lvbeck** [comment]
It's working in the latest release, thank you very much for all your efforts!

**Comment by justinclift** [comment]
Awesome. :smile:
