### ISSUE TITLE
Edge case crashing bug in nightlies

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1015]
Just found a simple, completely repeatable crashing bug in our latest OSX nightly build.

1. Execute a query in the Execute SQL tab (eg `SELECT count(*) FROM download_counts`), using [this DB](https://dev1.dbhub.io/justinclift/DB4S%20download%20stats.sqlite), though it'll probably happen for every DB.
2. In the result pane below, click on the result with the mouse, then press backspace (as if wanting to delete the cell contents)

Immediate DB4S crash.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000028
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x28:
--> 
    __TEXT                 000000010969c000-0000000109aa0000 [ 4112K] r-x/rwx SM=COW  /Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   net.sourceforge.sqlitebrowser 	0x00000001096ae3d4 DBBrowserDB::updateRecord(QString const&, QString const&, QString const&, QByteArray const&, bool, QString const&) + 340
1   net.sourceforge.sqlitebrowser 	0x00000001097994e0 SqliteTableModel::setTypedData(QModelIndex const&, bool, QVariant const&, int) + 944
2   net.sourceforge.sqlitebrowser 	0x00000001097546eb ExtendedTableWidget::keyPressEvent(QKeyEvent*) + 1419
3   org.qt-project.QtWidgets      	0x0000000109cf679a QWidget::event(QEvent*) + 4666
4   org.qt-project.QtWidgets      	0x0000000109df06dd QFrame::event(QEvent*) + 45
5   org.qt-project.QtWidgets      	0x0000000109e7f169 QAbstractScrollArea::event(QEvent*) + 1769
[snipped]
```

Without looking at the code, it seems like a pointer problem in DBBrowserDB::updateRecord().

Guessing either updateRecord() shouldn't be getting fired... or if it should be, then we'll need to add some extra checking. :smile:

**Comment by MKleusberg** [comment]
I wonder how that wasn't noticed before :+1: But it should be fixed with the latest commit :smile:

**Comment by justinclift** [comment]
Excellent, that fixed it.  Thanks @MKleusberg. :smile:
