### ISSUE TITLE
Refreshing 'Browse Data' data, lies about the sorting

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1016]
### Details for the issue

If you browse a table using the 'Browse Data' tab, then sort via clicking a column heading, and then click the 'Refresh Data' button, the data is pulled from the database again (as expected) but the column you clicked on is still 'selected' with the sorted up/down arrow.  If you then click this column AGAIN (to resort it, as its currently unsorted) the sort order is reversed, so you have to click the column AGAIN to resort in the order you originally wanted it.  This can get annoying... ;)

Requested feature: When the 'Refresh Data' button is pressed, the columns should lose their 'oh I was sorted' toggle.
I would have suggested 'the data is resorted', but there is currently no way to lose a sort - if you accidentially click a column heading so the data is sorted, you can't 'unclick' a column, so 'Refresh Data' with no sort is useful.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.99
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
- [x] Eaten too much today

**Comment by justinclift** [comment]
Ahhh.  Would it be more optimal to have the refresh button apply the sorting (as you mention), but we also include some way to forget any sort selection?

**Comment by chrisjlocke** [comment]
Best of both worlds! I can see you've done this before! ;)

**Comment by MKleusberg** [comment]
With the next nightly build it should keep the current sorting when pressing the refresh button. So it shouldn't be that annoying anymore :wink:

I haven't (yet) added a button for removing the sort order. But there already is a (somewhat hidden) way to do so: right click on the column headers, click "Show rowid column", then left click on the rowid column header, and then (optionally) right click, and click "Show rowid column" again to hide the rowid column.

**Comment by chrisjlocke** [comment]
Excellent, thanks!  Will check over the weekend/Monday.  Appreciate that.

**Comment by chrisjlocke** [comment]
Works perfectly... so long as it wasn't this that caused #1019 😨

**Comment by MKleusberg** [comment]
Cool, thanks for testing :smiley: I'll have a look at #1019 soon.
