### ISSUE TITLE
Browsing Recently Viewed Table Causes Crash

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1019]
### Details for the issue

Have been using an older nightly fine (7 May or so) but downloaded a recent nightly (24 May) and now if I browse a recently browsed table, DB4S crashes.
http://screencast-o-matic.com/watch/cbhZ2HXkz2

Windows doesn't really provide useful info *where* its crashing, so not sure what helpful info I can provide.

I haven't tried the obvious yet of rebooting and retrying.  The problem is fairly reproducable.  Haven't tried another database either.  
Worthy of note that the database is on a server (with plenty of disk space) but haven't had issues before.

Ignore the 'semi crash' when the program is restarted - it only does that when Avast 'sandboxes' it, so its something to do with DB4S checking for a version update and getting 'nothing' back, or something...

Edit: Just tried a different database on a different machine (so still via a network, but not the same above server) and the same issue - browse a table fine, but browse a previous table and 'BANG'.

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.99
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Does the nightly from before 19th May work?  eg the 18th or similar.

I'm wondering if it's a side effect from b7cd1c7dbd0606d12f6b2ab31451760b39cac82f somehow. :smile:

**Comment by chrisjlocke** [comment]
I'll have a go tomorrow... certainly ones from early May were OK.

**Comment by chrisjlocke** [comment]
Yes, nightlies from 18 May and 19 May worked fine.  The nightly from 20 May exhibits the above crash.

**Comment by justinclift** [comment]
Awesome @chrisjlocke. :smile:

**Comment by MKleusberg** [comment]
Thanks for tracking this down, @chrisjlocke! In this case I believe that this is indeed caused by 7ad80352616df1b185ab87f989cb7c2fd6c784c5. I'm just not sure why yet and it will be tricky to debug because it doesn't crash for me. But I'll try :smile:

**Comment by justinclift** [comment]
@MKleusberg If it's useful, I can kick off the windows build script and point it at a branch of your repo or something, to make some one off build(s) for Chris to test with.

**Comment by justinclift** [comment]
Oh... one other thing springs to mind.  I recently updated the Windows build box to use SQLite 3.19.0.  I wonder if that's the cause?

**Comment by justinclift** [comment]
Ahhh.  sqlite.org now lists 3.19.2 as the latest.  I'll update the build box with that and remake todays nightlies.  Gimme a few minutes.

**Comment by MKleusberg** [comment]
Yeah, makes sense to use the latest SQLite version. But it's probably not the source of the problem here (I guess).
Can you make a build from [this branch](https://github.com/sqlitebrowser/sqlitebrowser/tree/issue1019)? This prints some rudimentary debug output to the console.

**Comment by justinclift** [comment]
Yep, will do.  Gimme a bit. :smile:

**Comment by justinclift** [comment]
k, it's building now.  In theory it they should pop up in the *-onceoffs dirs in ~1/2 hour:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/
* https://nightlies.sqlitebrowser.org/win32-onceoffs/

... and have "issue1019v1" in their name.

**Comment by MKleusberg** [comment]
Cool, thanks :smile:

@chrisjlocke Can you test again using those build? It should still crash but - when you start the new build from cmd.exe - print some debug information that hopefully provides at least some clue on where to start looking for the bug :wink:

**Comment by karim** [comment]
I have the same exact problem as @chrisjlocke.

Also, it crashes when I move away from "Browse Data" tab and re-select it again. I can only select "Browse Data" tab *once* right after opening any database, and as soon as I select another tab and try to go back to it, DB4S crashes. Nightly versions up to 19 May work fine.

I downloaded the debug version [issue1019v1](https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1019v1-win64.exe) but it is not printing anything.

    C:\Users\Karim\Desktop\DB Browser for SQLite>"DB Browser for SQLite.exe"
    C:\Users\Karim\Desktop\DB Browser for SQLite>

**Comment by chrisjlocke** [comment]
Confirmed.  No output is created from running it from the command-line.  It might have to explicitly log it to a file?  I don't think Windows has a 'console' that applications can write to.

I tried to run it with an output option ('dbrowser for sqlite.exe >log.txt') but that didn't work either.

**Comment by karim** [comment]
Windows apps are either console apps or GUI apps. But you can *attach* a console to a GUI app. Using WinAPI you can do

```cpp
#include <stdio.h>

// attach a console to a GUI app
AllocConsole();
freopen("CON", "w", stdout);

// output to console using functions like printf

// when finished with the console, detach it
FreeConsole();
```

**Comment by chrisjlocke** [comment]
More things I didn't know.  🍸

**Comment by justinclift** [comment]
Yeah, at least some parts of DB4S definitely seem happy to throw an error message out to the console when things go wrong.  Case in point + screenshots: #583 :smile:

**Comment by chrisjlocke** [comment]
"Out to the console".  So is that console window always visible?  (ie, when the program is launched) as its not appearing in the version I ran.
And you just ran that from the command prompt?

**Comment by justinclift** [comment]
Yeah, from memory that was from when I started DB4S from a cmd.exe command prompt.

**Comment by chrisjlocke** [comment]
OK.  Well, I can't get any output from the 'supplied version', and no console window appears when that version is run (from the command line or from Windows).
Are you sure you built it properly @justinclift? 😜

**Comment by justinclift** [comment]
Hmmm, I just ran our nightlies batch file, but pointed towards the branch @MKleusberg.

It is possible I forgot something, but I'm not sure what it might be. 😖

**Comment by chrisjlocke** [comment]
It might be linked (so this is a reminder for me to check when this gets fixed) but DB4S also crashes when you open a project file (as soon as its opened - before anything is displayed).

**Comment by justinclift** [comment]
Yeah, that crash happens on Linux too with our current source.  Tried it yesterday and noticed the same thing. :wink:

**Comment by allender** [comment]
FWIW, I am having the same problem.  I load up my db, go to the browse tab, look at data, switch to the execute SQL tab and when browsing back to the browse tab, it crashes.  it looks like I have the nightly from around May 31.  If it would be helpful, I can try and supply you a db file that causes this issue.

**Comment by chrisjlocke** [comment]
It looks like _any_ file causes the issue, so don't think an example would be required .... but many grateful thanks anyway! I think we've nailed it down to _what_ the problem is, just haven't got the fix in place yet.... 🍳

**Comment by karim** [comment]
@allender In the meantime you can downgrade to any version *before* May 20 as it does not have this issue.

**Comment by allender** [comment]
Assuming it has json support, then yes :)

**Comment by chrisjlocke** [comment]
Reading issue #677, the JSON1 extension has been part of the nightlies since Jan 2017.  The nightly from 19 May should therefore be good to go. 🚗

**Comment by MKleusberg** [comment]
Makes sense that it is crashing for the project files, too, because while loading the project file, we're first opening the database as usual and then set the currently browsed table. If this is the first table in the list it's causing the same line of events as in the original issue.

But I'm still not sure how this might happen :frowning_face: If you don't see any output from the debug build this can have two reasons, I guess: 1) The issue is happening even before the code that I suspect, or 2) the console output doesn't work as expected.

To rule out option 2) I've updated the branch with the debug commit. It should now output the information in the SQL log panel, more specifically in the 'User' SQL log. Also it is going to open an empty message box after outputting to the log in order to allow you reading the log before crashing :wink: No worries, it's only 6 clicks per table selection. I hope @justinclift can make a new build from that branch.

**Comment by justinclift** [comment]
@MKleusberg As a note, this isn't a windows only crash.  I compiled on Fedora Linux a few days ago, and it immediately crashed when opening a project file.

As a side note, when compiling on OSX an hour or two ago I noticed a huge amount of warnings of compiling weirdness.  I kind of wonder if there's something funky going on with some of the recent library updates (QScintilla or and QCustomPlot) that might turn out to be related. I'll create a separate issue with the warnings in a bit, so we can look through them when we have time.

**Comment by MKleusberg** [comment]
Yeah, it doesn't sound Windows-specific either. But still, on my Linux system it doesn't crash... I'll investigate further :wink:

**Comment by MKleusberg** [comment]
Ok, I feel like I'm on a scent now. If my current assumptions prove to be right, that would explain this crash as well as he problem in #1007. On the other hand I have no idea why this wouldn't have crashed in earlier versions, too.

Anyway, can you try tomorrow's nightly build, @chrisjlocke? Does it change anything? Or does it maybe even work correctly with this? :smiley:

**Comment by chrisjlocke** [comment]
No problem.  🔎

**Comment by MKleusberg** [comment]
Awesome :smiley: If it still crashes, I have written [this Wiki page](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Debugging-a-crash-on-Windows) on how to debug a crash in a slightly more efficient way. It's still not perfect (neither the Wiki page nor the debug process) but better than nothing I guess :wink:

**Comment by justinclift** [comment]
@MKleusberg Just did a manual bisect on Fedora, to find out where the "crash when opening project files" bug started.  It's definitely this commit which introduces it: 21ee1f2703967b6caa6c07d6e0cfdca0b5c5d25f

Recompiling and running with the commit prior seems fine.  When moved by one to the above commit, the crash happens.

**Comment by justinclift** [comment]
As a note, also tried with the latest commit (6984d451d6b249a11215472b5abeb5cba5c69ff3), which also crashes.

**Comment by justinclift** [comment]
Hmmm, I might be able to attach a debugger to it and see what the crash point it.

Might be time to install Qt Creator here...

**Comment by justinclift** [comment]
Yep.  Caught the crash, and make a series of screenshots walking back the call stack.  I need to get back into the Golang thing now, but I reckon the screenshots below should be helpful. :smile:

![screenshot_2017-06-18_11-41-34](https://user-images.githubusercontent.com/406299/27260114-ade76232-541b-11e7-9da0-66e94ddff5af.png)
![screenshot_2017-06-18_11-42-08](https://user-images.githubusercontent.com/406299/27260115-b3bc6914-541b-11e7-90b1-2984f858b1da.png)
![screenshot_2017-06-18_11-42-20](https://user-images.githubusercontent.com/406299/27260116-b3d0899e-541b-11e7-832d-bc270e67d81c.png)
![screenshot_2017-06-18_11-42-33](https://user-images.githubusercontent.com/406299/27260118-b3e3fc5e-541b-11e7-859a-44ef96a09cb1.png)
![screenshot_2017-06-18_11-42-42](https://user-images.githubusercontent.com/406299/27260117-b3e3796e-541b-11e7-8856-be71718784fb.png)
![screenshot_2017-06-18_11-42-51](https://user-images.githubusercontent.com/406299/27260120-b3e50c70-541b-11e7-9a1f-a96f24d983bf.png)
![screenshot_2017-06-18_11-43-01](https://user-images.githubusercontent.com/406299/27260119-b3e49948-541b-11e7-9d8b-2d99615c4e76.png)
![screenshot_2017-06-18_11-43-14](https://user-images.githubusercontent.com/406299/27260121-b3ea58c4-541b-11e7-994a-a6af1c23351e.png)

**Comment by MKleusberg** [comment]
This looks like it might indeed be the same problem as in the original issue (i.e. the project file crash and the browsing recently viewed table crash are the same). I still don't see the error though :frowning_face:

**Comment by justinclift** [comment]
k, I'll have another go at it tomorrow, and see if I can collect more useful info for what's going on. :smile:

**Comment by MKleusberg** [comment]
Cool, thanks :smile: But no worries if you don't have the time for it tomorrow. I think I'll borrow an Windows laptop one of the next days and see if I can spot something.

**Comment by justinclift** [comment]
Hmmm, maybe run up Fedora 25 x64 (the XFCE download ISO) in a VM, and see if it crashes for you? Might be easier. :smile:

**Comment by chrisjlocke** [comment]
> I think I'll borrow an Windows laptop one of the next days and see if I can spot something.

If you want a Windows VM, let me know.

**Comment by MKleusberg** [comment]
Thanks to both of you 😄 The Fedora VM is a really good idea, and I'll probably come back to the Windows VM, too, at some point.

But I've just tried the latest nightly on a Windows system without development environment and it just worked. Then I've installed an older one and it crashed. So to me it looks like it's been fixed by one of the last commits 🎆 Not sure though, so maybe you can double check :wink:

**Comment by justinclift** [comment]
@MKleusberg Just compiled and tried it... immediate crash upon opening a project file still.  Doh! :wink:

**Comment by MKleusberg** [comment]
Huh. Nevermind then :wink:

**Comment by chrisjlocke** [comment]
> But I've just tried the latest nightly on a Windows system without development environment and it just worked.

Opening a project file works if you browse the tables first from the database (ie, open the database first).  Did you do that?  Opening a 'new' project file (ie, not opening the database first) seems to cause the project crash.

Viewing a table in the latest nightly doesn't appear to crash anymore.  Should I therefore close this issue, and raise the 'opening a project file crashes' issue instead?

**Comment by MKleusberg** [comment]
Thanks, Chris! This was it - it seems to depend on the saved active tab in the project file. If it is the Browse Data tab it works, if it isn't it crashes. And of course I always did it the wrong way :wink: But _finally_ I've managed to reproduce this (even on my system) and I think it should be fixed now.

So we had two separate issues. One for browsing the same table again which I guess was fixed by 6984d451d6b249a11215472b5abeb5cba5c69ff3, and another for loading certain project files which should be fixed by f4fad4afcf19577796be8890e1c84770de70cf63. Can you again double check it's working for you, too? :smile: Also, as pointed out earlier I think #1007 might have been fixed by the first commit, too. So that's worth testing as well.

**Comment by justinclift** [comment]
Awesome! Just tried on OSX... no crash when opening a project file.

I'll jump on the Linux dev box in a bit and try that too, just to make sure as that one was definitely crashing prior. :smile:

**Comment by justinclift** [comment]
Yep, the crash-on-opening-project-files is fixed here on Fedora 25 now.

Thanks @MKleusberg.  Well done. 😁

**Comment by chrisjlocke** [comment]
Works perfectly.  Many thanks @MKleusberg .

**Comment by MKleusberg** [comment]
Thank you for all the testing 👍 I'm glad we finally got there :wink:
