### ISSUE TITLE
Active filters are not updated on table modification

### ISSUE THREAD

**Issue by eevleevs** [sqlitebrowser/sqlitebrowser#1020]
### Details for the issue

- set a filter on one column on "browse data"
- modify the table adding another column before the one with the filter
- the filter is in the same position, but not anymore on the same field

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting bug, thanks for reporting it. :smile:

**Comment by prutz1311** [comment]
There is no way for DB4S to keep track of columns when modifying a table, that is, it cannot relate the columns before modification to the ones after modification, so it seems to be impossible to move values in filter lines into right positions. Should we instead just clear all filters on table modification?

**Comment by justinclift** [comment]
@prutz1311 Thinking about it, that's probably a reasonable approach.  But it also sounds like the kind of thing which would need to be tried out to make sure it "feels ok" when used.

For something like this I'd probably implement it as fast as possible (no error checking) just to try out the workflow.  eg to have something to try in the GUI.  Then if the user experience seems ok, I'd then add the proper error checking to make the code quality reasonable.

But, it's completely up to you if you're considering doing it. :smile:

**Comment by MKleusberg** [comment]
Oops, accidentally closed this via that commit :smile:

@eevleevs Thanks to @prutz1311 it's now at least clearing the filter row. That's still not as good as remembering the filter results and reapplying them to the new schema but it's probably all we can do for now. Are you ok to download the latest nightly build and see how it works out this way?

**Comment by eevleevs** [comment]
Good for me, thanks.

**Comment by justinclift** [comment]
Awesome.  Thanks @eevleevs. :smile:
