### ISSUE TITLE
Unable to change page size in latest version

### ISSUE THREAD

**Issue by jjxtra** [sqlitebrowser/sqlitebrowser#1021]
Changing the page size has no effect when done either in the GUI or in SQL query window. Database is brand new, no tables yet. Have tried with all different journal modes too, no change.

PRAGMA main.page_size = 8192;
PRAGMA main.page_size; // shows 1024

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 10 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oh that's different.  We'll definitely need to look into that.

Thanks for pointing it out @jjxtra. :smile:

**Comment by MKleusberg** [comment]
@jjxtra Thanks for pointing this out! :smile: I believe this issue is fixed now. Can you download tomorrow's nightly build (or any later version) and double check that it's working for you?

**Comment by jjxtra** [comment]
Absolutely, thanks for doing this. I had briefly taken a gander in the code but didn't see an obvious spot for the fix.

**Comment by jjxtra** [comment]
Unfortunately the latest nightly build as of this morning is limiting the page size to 4096. So now when I run the two lines from the top of this issue, it gives 4096 as the page size.

**Comment by justinclift** [comment]
Gaaah.  Ok so we're in the right area of things, but still aren't quite over the finish line. :wink:

**Comment by MKleusberg** [comment]
Hmm, the limit should be 65536. I have no idea where the 4096 value might come from.

That said, my fix only changes the GUI pragma editor, not the SQL execution bit. Have you tried the GUI editor yet?

I'll also put a reference to issue #966 here. That issue is about not being able to edit pragmas from the SQL editor.

**Comment by jjxtra** [comment]
This does work using the GUI.

**Comment by MKleusberg** [comment]
@jjxtra Thanks for testing this so far. I've just made an extra change that should allow you to also change the page size from the SQL editor. Are you ok to double check that too using the next nightly build? 😄

**Comment by jjxtra** [comment]
Will try it tomorrow

**Comment by jjxtra** [comment]
Unfortunately the pragma has no effect, page size remains previous value.

**Comment by justinclift** [comment]
Damn, still needs more effort then to get it working. ☹️ 

Thanks for testing @jjxtra. :smile:

**Comment by MKleusberg** [comment]
Thanks for testing, @jjxtra, and sorry for the long delay!

I've just added an additional patch which you can test by downloading tomorrow's nightly build. With this it should work just fine using the SQL editor. However, you need to set the page size and, directly after that, vacuum the database, like this:
```sql
PRAGMA page_size = 4096;
VACUUM;
```
Also see here: https://www.sqlite.org/pragma.html#pragma_page_size
The GUI editor for pragmas does this automatically, with the SQL editor you'll need to do it yourself :wink:

**Comment by justinclift** [comment]
@jjxtra Do you have time/interest to try the latest nightly build and the PRAGMA+VACUUM thing (as per @MKleusberg's comment above)? :smile:

**Comment by jjxtra** [comment]
We can close this, it's all working great!

**Comment by justinclift** [comment]
Awesome @jjxtra, thanks for checking. :smile:
