### ISSUE TITLE
Modify multiple cells' values at the same time

### ISSUE THREAD

**Issue by EvoWizz** [sqlitebrowser/sqlitebrowser#1022]
### Details for the issue
Hi! It would be great to be able to modify multiple cells' values when selecting multiple cells.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 10 x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting thought.  When reading that, the concept I'm getting is that if someone selects multiple cells then types (say) the number 5, all of the selected cells would get that value.

Is that the kind of thing you're meaning? :smile:

**Comment by EvoWizz** [comment]
@justinclift Exactly! :)

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by chrisjlocke** [comment]
Haha!  I was thinking something similar the other day as I had to update a number of cells in a database. Would be a nice feature.  ☕️

**Comment by iKlsR** [comment]
I don't like the selection model available for tables, it doesn't respect `Ctrl` and `Shift` as one would expect and instead treats everything as a `Shift` selection.

**Comment by justinclift** [comment]
@iKlsR From memory, the current behaviour (done in #709) is an improvement over what it was before.

The advantage of having skill with C++ and Qt, is that you can shape it to be better. 😁 

Would improving it further be of interest to you? 😉

**Comment by chrisjlocke** [comment]
> The advantage of having skill with C++ and Qt, is that you can shape it to be better.

The underlying control (or widget...?) should have this 'basic' functionality, then its down to the program to acknowledge/respect that, rather than the other way around?  Maybe the control does though - haven't played with Qt in any real depth.

**Comment by justinclift** [comment]
From memory of the issue, as it turned out to be fairly complex, we made it into a "single selection only" because that was the most practical approach for the time we had available.

The widget itself definitely can be told to allow multiple selections.  It does need corresponding code for handling that though.  Pasting a multiple-cell selection from one table to another has weird edge cases, and we also need it to work ok for cut-n-pasting onto the OS's clipboard so people can paste into (say) Google Docs.

... and we went with single selection for now because it was getting too hairy. :wink:

**Comment by iKlsR** [comment]
@justinclift Sure, when I get the time if someone hasn't done it yet. To clarify, I'm talking about the edit multiple cells feature, the underlying column selection is an issue to itself and would require some non-trivial structural changes.

**Comment by justinclift** [comment]
No worries at all, it all helps. 😁

**Comment by MKleusberg** [comment]
Here's an alternative idea (I wouldn't claim it's better). Leave the editing behaviour as it is but change the paste behaviour. Currently, when you're copying a single cell, then select multiple other cells, press Ctrl+V, and click Yes in the message box that will pop up, then the clipboard content is only pasted into the first of the selected cells. We could change that to paste the clipboard content into each of the selected cells. Hmm, I hope it's understandable the way I've described it :wink:

Anyway, this approach would require more button presses to achieve the same result. But on the other hand it would then be the same behaviour as in most (all?) spreadsheet applications which is probably what most users would expect.

What do you think?

**Comment by MKleusberg** [comment]
Just added the feature which I have suggested in my last comment because somebody requested it on the mailing list 😄

@EvoWizz If you're still interested in this, can you download tomorrow's nightly build and see if the approach works for you, too?

**Comment by EvoWizz** [comment]
Hello @MKleusberg 

I tried the version `24-Nov-2017 05:03            16372386`, and I'm not able to edit multiple cells' values at the same time 🤔  I've selected multiple cells, and then I've changed the value inside the "Edit Database Cell" window but that only changes the last selected value. Am I doing it wrong? Or do I just need to wait a bit for the next build 😄 ?

**Comment by mgrojo** [comment]
Hi @EvoWizz, MKleusberg has implemented a copy/paste method for this. You have to write the value in one cell and then copy it, select the remaining cells and pasting the copied cell to all the selected cells.

The way you have tried makes also sense, but nobody has implemented it yet :smile:

**Comment by EvoWizz** [comment]
Oh! Sorry I completely forgot to answer :|

So I tried doing what you said @mgrojo but I guess I'm doing it wrong again (or it doesn't work on Windows) because when I copy a value from a cell and paste it on multiple selected cells, well only the first selected cell changes. (Exactly like before)

**Comment by justinclift** [comment]
@EvoWizz Hmmm, is that using the build from a few days ago?  If so, maybe try last night's one quickly, just on the off chance it's changed? :smile:

**Comment by EvoWizz** [comment]
@justinclift Just downloaded and tried again, but I still have the same behavior.

**Comment by MKleusberg** [comment]
@EvoWizz Do you get a message box saying the number of selected cells doesn't match? Or is it just pasting the content into the first cell without asking?

**Comment by EvoWizz** [comment]
@MKleusberg Yes I do have that box

**Comment by MKleusberg** [comment]
Hmm... that message box should have gone away.
Just to make absolutely sure, can you check the version in Help -> About again? If it's from 24/11/2017 or later it should work. Here's how it works for me:
1) Browse a table.
2) Single click a cell, so it is selected, then hit Ctrl+C
3) Select multiple cells, so they are all selected
4) Hit Ctrl+V
But I suppose that's exactly what you were doing...

Can you maybe post the clipboard contents you have after step 2 here?

**Comment by EvoWizz** [comment]
Hello! Sorry I just saw the notification.

So in fact it's working! The problem was that the `v3.9.0` was still installed on my PC for some reasons. So I've uninstalled it, now it's working flawlessly with the version `3.10.99 (Nov 29 2017)`. 

So it's exactly what I expected! Thanks a lot :) @MKleusberg

**Comment by MKleusberg** [comment]
Awesome :smiley: I'm glad it's working for you now, @EvoWizz! 😄 I think we can close this issue then.

**Comment by EvoWizz** [comment]
Sure! Thanks a lot 😊

**Comment by shaun-ba** [comment]
I'm on 3.10.99 but this paste isn't working ?

**Comment by chrisjlocke** [comment]
What's the date of the 3.10.99 version? When did you download it?

**Comment by shaun-ba** [comment]
I believe I installed using the PPA

```sudo apt-cache policy sqlitebrowser
sqlitebrowser:
  Installed: 3.10.100ubuntu1-0~1709~201709212204~ubuntu16.04.1
  Candidate: 3.10.100ubuntu1-0~1709~201709212204~ubuntu16.04.1
  Version table:
 *** 3.10.100ubuntu1-0~1709~201709212204~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     3.7.0-1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages```

**Comment by justinclift** [comment]
Ahh, that looks like the 3.10.1 release for Ubuntu.  It was accidentally created from our development code at the time, but the only change was the incorrect version number (3.10.99 vs 3.10.1) that would show up in the About dialog.

@shaun-ba If you're ok with using a recent nightly build instead (should be pretty safe), then the [sqlitebrowser-testing PPA](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1) should in theory "just work".  You'll probably want to uninstall the `3.10.100ubuntu1-0~1709~201709212204~ubuntu16.04.1` version first though, just to make sure there's no conflict(s). :smile:

**Comment by MKleusberg** [comment]
Closing this again because we haven't heard about any more issues regarding this. If you're still having problems after installing the PPA version, you can always reopen this issue, @shaun-ba :smile:
