### ISSUE TITLE
Adjust column width to name for all columns

### ISSUE THREAD

**Issue by c01313** [sqlitebrowser/sqlitebrowser#1023]
### Details for the issue
I have a table with lots and lots of columns and when browsing data it's very difficult to see column names that are on the longer side, so I've been double clicking the spacer between columns, which adjusts the column width to the name.  Is there any way to do this across all columns without having to manually double click each spacer?

If not, is that something you'd consider adding in a future update?

Thanks.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 Pro ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
It's definitely a reasonable idea.  I suspect this is something people have asked about before, but we've just not gotten around to implementing yet.

Um... don't suppose you're any good with C++ and Qt programming? :smile:

**Comment by c01313** [comment]
Unfortunately not at all. 🤷‍♂️

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by chrisjlocke** [comment]
if you select multiple columns (they have to be adjacent - you can't select just specific columns) and double click the spacer, then all those columns will have the same width.  So if you select all columns (by clicking the top left square) and double clicking the column spacer to the right of the largest column, all columns will be super long.  So not perfect, but quicker than clicking each column...

**Comment by justinclift** [comment]
A sounds like that'd make for a useful FAQ item or similar kind of thing on the wiki.

@karim @chrisjlocke Would either of you have the time/interest to make something suitable? :smile:

**Comment by chrisjlocke** [comment]
"Its wacky and its weird and unlike any other feature you've used."  😉

**Comment by chrisjlocke** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Resizing-Columns

**Comment by chrisjlocke** [comment]
Oh yeah, forgot about that.... doh.  🦀

**Comment by c01313** [comment]
That works for me for the time being.  Thanks Justin and Chris.  Should I close this or is a "better" solution something you'd still plan on implementing?

**Comment by justinclift** [comment]
Probably close it for now.  We're swamped with issues as is, so cutting down on the non-major ones for a while is probably not a bad idea. :smile:

**Comment by c01313** [comment]
Haha, no worries.  Closed.  Cheers.

**Comment by elig0n** [comment]
More than two years passed so is there any chance for this to be reconsidered ? 
The above suggested method generally requires one to gauge the column with the longest cell and use that; this can be daunting in big tables.
