### ISSUE TITLE
Tabsheet "Execute SQL" - not possible write char with diakritic how id Š,š,ďť,ň,ľ...

### ISSUE THREAD

**Issue by matuszuborupc** [sqlitebrowser/sqlitebrowser#1024]
### Details for the issue

Not possible in the editor write special chars from char over 128 - 255 or unicode ....
example 
select * from "Košice"

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Which version is this happening with, and on which operating system? :smile:

**Comment by matuszuborupc** [comment]
Version 3.6.0
Qt Version 5.4.1
Sqlite 3.8.9

Windows 7

**Comment by justinclift** [comment]
Thanks @matuszuborupc.  That's a very old version.  Would you be ok to try our latest release?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.1

I'm pretty sure diacritics work in that. :smile:

**Comment by matuszuborupc** [comment]
Sorry my fault, after update to 3.9.1 sw worked fine.

Thx.

**Comment by justinclift** [comment]
Awesome. :smile:
