### ISSUE TITLE
Update SQLCipher version for Windows nightlies to 3.4.1

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1025]
SQLCipher 3.4.1 was released a while ago.  Our Windows nightlies use an older version though, as it's based on a modified version (changed to compile easier on Windows).

It would be useful to update my SQLCipher repo to version 3.4.1, so that our Windows nightlies use that.

**Comment by chrisjlocke** [comment]
Will be happy to test if you need a 'tester'. 😸 
Can't remember if you have a Win VM to test.

**Comment by justinclift** [comment]
Thanks @chrisjlocke. 😄 

I do have one, but it's stored on machine I rarely turn on and is a bit of a pain to get happening.

Probably won't get to this any time real soon though.  It's more of a reminder/placeholder issue for myself so I don't forget. :wink:

**Comment by chrisjlocke** [comment]
Closing this, as its now out of date.  SQLCipher is now on v4...
