### ISSUE TITLE
Hide columns

### ISSUE THREAD

**Issue by eevleevs** [sqlitebrowser/sqlitebrowser#1026]
### Details for the issue

I often use a db instead of a spreadsheet, and I would use the possibility to hide columns in order to focus only on certain fields. Views don't seem a solution to this because they cannot edit data.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting thought.  Yep, it does sound like it would be useful. :smile:

**Comment by chrisjlocke** [comment]
A possible 'temporary workaround' is that columns can be resized down to quite a small size.  
![image](https://cloud.githubusercontent.com/assets/7872218/26530240/29b23e36-43c9-11e7-8b9c-ae522a1904f3.png)

These can also be saved if the database is saved as a 'project', which is handy...
So not perfect, but 'workable'.... ;)

**Comment by justinclift** [comment]
Yep, that'd probably work too. :smile:

**Comment by iKlsR** [comment]
How would one go about showing back the hidden column, do we want to selectively hide columns and then have a mass show all hidden?

**Comment by eevleevs** [comment]
Mass show works for me, if you want to make it simple.
For hiding, would be good if one could select several columns, and hide all at once.

**Comment by lpirl** [comment]
for references, resolving #141 (edit views) would resolve this issue as well

**Comment by peteristhegreat** [comment]
I implemented this feature recently on 3.9.0.  I'll see if I can put together a git pull request soon.  The corner case for if all columns gets hidden, it unhides the first column (not the zeroth).

    // Add two actions in MainWindow.ui called "actionHideColumns" and "actionShowAllColumns"
    
    // add two lines to MainWindow::init()

    popupBrowseDataHeaderMenu->addAction(ui->actionHideColumns);
    popupBrowseDataHeaderMenu->addAction(ui->actionShowAllColumns);

    // add two slots to MainWindow.cpp
    void MainWindow::on_actionHideColumns_triggered()
    {
         int myCol = -1;
         if(ui->dataTable->selectedCols().size() == 0)
         {
              myCol = ui->actionBrowseTableEditDisplayFormat->property("clicked_column").toInt();
         }

         foreach(int col, ui->dataTable->selectedCols())
         {
              ui->dataTable->hideColumn(col);
         }
         if(myCol != -1)
              ui->dataTable->hideColumn(myCol);

         // check to see if all the columns are hidden

         bool allHidden = true;
         for(int col = 1; col < ui->dataTable->model()->columnCount(); col++)
         {
              if(!ui->dataTable->isColumnHidden(col))
              {
                    allHidden = false;
                    break;
              }
         }

         if(allHidden  && ui->dataTable->model()->columnCount() > 1)
         {
              ui->dataTable->showColumn(1);
              ui->dataTable->resizeColumnToContents(1);
         }
    }

    void MainWindow::on_actionShowAllColumns_triggered()
    {
         for(int col = 1; col < ui->dataTable->model()->columnCount(); col++)
         {
              if(ui->dataTable->isColumnHidden(col))
              {
                    ui->dataTable->showColumn(col);
                    ui->dataTable->resizeColumnToContents(col);
              }
         }
    }

**Comment by peteristhegreat** [comment]
Built and tested on Qt 5.6.1, MingW 4.9.2 32bit.

See #1135

![demo_hide_cols_before](https://user-images.githubusercontent.com/2342284/30349169-fd163b0a-97df-11e7-980d-09d961e7d0ae.jpg)

![demo_hide_cols_after](https://user-images.githubusercontent.com/2342284/30349174-0026cf12-97e0-11e7-8326-28c05e75ab0d.jpg)

**Comment by justinclift** [comment]
Thanks @peteristhegreat, just saw the PR.  The placement of the options looks good to me.  Right-click context menu being where people generally expect this kind of thing. :smile:

**Comment by MKleusberg** [comment]
@eevleevs We've just added this feature to our code. Are you interested in downloading tomorrow's nightly build and testing if it works for you? :smile: Thanks again to @peteristhegreat for implementing this!

**Comment by eevleevs** [comment]
Works perfectly, thank you :+1:

**Comment by justinclift** [comment]
Awesome, thanks for verifying @eevleevs. :smile:

**Comment by KimlongSeng** [comment]
Is there a way to hide it until I turn it back on ? So far, when I click refresh, it will reappear.

**Comment by MKleusberg** [comment]
@KimlongSeng Which version are you using? And can you try again with the latest nightly build from [here](https://nightlies.sqlitebrowser.org/latest/)? In theory it should stay hidden in that version.

**Comment by SpicyCatGames** [comment]
Seems like it freezes if you select too many columns at once and try to hide them.
