### ISSUE TITLE
feature request: add "set selected field to NULL" option

### ISSUE THREAD

**Issue by WiliTest** [sqlitebrowser/sqlitebrowser#1027]
### Details for the issue

If there is a way to set all selected field to null (in brownse data), I did not find it. I have seen that I could delete all the entry in once, but I'm not shure it's the same as setting these field as NULL. So I did it one by one manually using the buttons "set as null" and "apply", which was quite a job.

It would be intuitive to have a right click option : "set as null"

thanks for your awesome job!

PS: " fill out the correct check boxes": I don't see any checkbox , just raw text.

#### I'm opening this issue because:

- [x] DB4S needs a feature

#### I'm using DB4S on:

- [x] Windows: ( _version:7 ) 

#### I'm using DB4S version:

- [x] 3.9.1

#### I have also:

- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20 ✔

**Comment by justinclift** [comment]
Good thinking.  That's a very good reason to have a "Set as NULL" button or something similar in the main Browse Data window, not just inside the cell editing window.

**Comment by justinclift** [comment]
As a thought, for a workaround approach for now it'd be possible to set all values to NULL using SQL.  eg something like `UPDATE sometable SET column = NULL`.  Doing it like that without a WHERE clause will apply it to all rows. :smile:

**Comment by chrisjlocke** [comment]
This is sort of linked to the other issue raised recently of changing multiple cell values at once. The is a keyboard shortcut to null a cell contents, so it could be carried across all selected columns/rows... assuming the Qt control plays nicely...

**Comment by WiliTest** [comment]
I'm impressed you already looked at it. Thanks a lot for all you have done (even if you don't implement that!)

**Comment by WiliTest** [comment]
By the way it would even better to implement a "replace all fields by", so you could set to NULL or whatever.

ps: I'm impressed you already looked at it. Thanks a lot for all you have done (even if you don't implement that!)

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by MKleusberg** [comment]
There's a keyboard shortcut for this (but no button) :smile: You can press Alt + Delete or Alt + Backspace to set the current field to NULL. Here's a list of all non-obvious keyboard shortcuts: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts#browse-data-tab

But yeah, for now it works only for single fields. I'll try to fix that over the next couple of days, if time permits :wink:

**Comment by MKleusberg** [comment]
Oh. Sorry. It actually already *does* work. Just select multiple fields and press Alt + Delete and there you go, all set to NULL. @WiliTest can you try that? If it doesn't work for you, you can download the latest nightly build and try with that.

**Comment by MKleusberg** [comment]
Did you have a chance to test this yet, @WiliTest :smiley:

**Comment by WiliTest** [comment]
@MKleusberg Alt + Delete does work! (but it's everthing but intuitive). (I apologize for the delay)

**Comment by justinclift** [comment]
Cool. :smile:

Maybe we should add a menu option for it or something, so more people discover it?

**Comment by WiliTest** [comment]
I would go for a right click, it's where I first look for it. But you guys made a super work. Thanks a lot!

**Comment by MKleusberg** [comment]
@WiliTest Thanks for the suggestion! That's the sort of thing that I as a developer don't come up with so quickly but that makes a lot of sense :wink: Anyway, I've just added a context menu to the table browser. With the next nightly build you should be able to right click your selected items and click 'Set to NULL'. Do you have the time to double check if it's working for you this way, too? :smile:

**Comment by WiliTest** [comment]
Thanks so much, though I did not manage to test it. I tried though. I installed the latest win 64 version on https://nightlies.sqlitebrowser.org/latest/  (which uninstalled the previous one). But the .db or .sqlite arent recognize anymore (white icons).  The "Open with" option doesnt work either.

**Comment by justinclift** [comment]
Oh, that sounds like it's installed to a different path than the previous version.

As a work around, if you start DB4S manually you should be able to open files from the main GUI.  **File** → **Open**.  Well, in theory anyway. :wink:

**Comment by WiliTest** [comment]
sorry, I should have thought about it. Yes the right click does work wonderfully! (I wish I could download your brain!).

**Comment by MKleusberg** [comment]
Awesome :smile: Thank you for opening this issue and testing :wink: I'll close this issue then.
