### ISSUE TITLE
Incorrect total row count browsing data 

### ISSUE THREAD

**Issue by fatscally** [sqlitebrowser/sqlitebrowser#1028]
On the Browse Data tab.  I have a table with 80 rows.  When I scroll to the bottom it reports "65-0 of 0"

2 pictures are the same table but the top is not scrolled to the end.
![image](https://cloud.githubusercontent.com/assets/5503999/26583919/f44fa95a-453e-11e7-816e-720359f3104b.png)

![image](https://cloud.githubusercontent.com/assets/5503999/26583895/e20b1388-453e-11e7-8abc-eca4703e0662.png)

Further comment;  the button "Jump 100 rows", I would have it expected to jump only a page, so 16 rows.  If not for the tool tip I would have called it a bug on this 80 row database because it jumped to the end.

**Comment by justinclift** [comment]
As a thought, does it happen with our recently nightly builds too?  We changed the pagination code for the Browse Data tab on May 8th to jump by however many rows are currently being displayed.

**Comment by fatscally** [comment]
Hi.

Version 3.9.1


Qt Version 5.7.1


SQLCipher Version 3.11.0

**Comment by chrisjlocke** [comment]
v3.9.1 is quite old now*.  Try one of the latest nightlies from here:
https://nightlies.sqlitebrowser.org/latest

*By that I mean we've put a lot of time and effort in fixing issues, but haven't yet made a full release, so our nightlies are more up to date than the version available for main download.

**Comment by fatscally** [comment]
Oh right, I forgot.  At work I'm on the last release.  At home I have a
night release.  I'll take a look later when I get home.  :)

**Comment by MKleusberg** [comment]
@fatscally In the last few nightly builds the paging arrows should actually jump one page instead of 100 rows. As for the wrong row count, unfortunately I don't have an idea yet. What happens when you resize the window? Does it change anything? And is this a 'normal' table or a ```WITHOUT ROWID``` table?

**Comment by fatscally** [comment]
I'd luv to do some testing to help you guys along but the links to the
nightly build are blocked at work.  Can you try uploading to another
address that might work for me.  The version I have at work is an older
release, and at home I have no time to play with it.

On Wed, Jun 21, 2017 at 10:58 PM, Martin Kleusberg <notifications@github.com

**Comment by justinclift** [comment]
@fatscally Interesting.  Is it feasible for you to find out why the links are blocked?  We had weird stuff like that happen with our initial nightly download server (a semi-dodgy repurposed thing :wink:).  Our new nightlies server though is dedicated to just DB4S and hosted at Rackspace.  It's about as legit as a (VM) server can get. :smile:

That being said, some work places get a bit funny when you ask them "why are you blocking site foo?".  If your workplace is one of those, better to leave it alone. 😁 

@chrisjlocke @MKleusberg (or any else) Don't suppose you have a spare server or VM around which we could set up as a mirror, to help with situations like this?

If not, I can probably reach out to Digital Ocean or something.  They might be willing to assist. :smile:

**Comment by fatscally** [comment]
It's just a security thing here.  Everything is black listed until it's
needed by someone for a legitimate reason.
You could probably share on Google Drive?  That might work.

**Comment by justinclift** [comment]
Ahhh that might be an option.  Not personally a fan of Google, but we do already use Google Analytics for the main 1 pager website.  There's probably not much evil they could do with mirroring our nightlies files too...

**Comment by chrisjlocke** [comment]
I've uploaded the latest nightlies to my Google Drive.
https://drive.google.com/drive/folders/0B7SL71QkC9gAU2xCWEhtYy1ZWUE?usp=sharing

Hopefully you can access these @fatscally ?

**Comment by chrisjlocke** [comment]
Hi @fatscally 
We've updated DB4S quite a fair bit recently.  Is this issue still occurring for you?  Do you need an up to date link to download the latest version?

**Comment by justinclift** [comment]
Closing this due to lack of response.  @fatscally The total row count problem should be fixed ages ago.  If it does still happen for you using any recent nightly build though, you're definitely welcome to reopen this so we can investigate. :smile:

**Comment by fatscally** [comment]
Sorry guys. Luv the app. Haven't had any chance to follow up on this bug.

**Comment by MKleusberg** [comment]
By the way, I have fixed some other problem with the row count just today. If you changed the current table from a table which contains some data to a table with no rows in it, the label wasn't updated. So it should definitely be working fine now :smile:

**Comment by justinclift** [comment]
Awesome. :smile:
