### ISSUE TITLE
Export Database or Table to SQL or CSV - allow export schema only

### ISSUE THREAD

**Issue by MarkyMar** [sqlitebrowser/sqlitebrowser#103]
Export Database or Table to SQL or CSV - allow a user to export the schema only
Suggest adding a check box to the existing Export dialog.
Check box label:  "Export schema only"
Default check box condition: Unchecked

**Comment by justinclift** [comment]
@MarkyMar We've added code for this today (written by @schdub).  Would you be ok to try our latest nightly build (tomorrow), to check that it's working the way you meant it? :smile:

**Comment by MKleusberg** [comment]
Closing this as it has been fixed quite a while ago and nobody reported issues since. If there any problems left with this let's just open a new issue :smiley:
