### ISSUE TITLE
DB4S save fails silently on read-only .sql files

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#1036]
### Details for the issue

1. Save sql tab to .sql file.
2. In Explorer set file as read-only.
3. In DB4S tab change content a click Save.
4. Reopen .sql in DB4S

At step 4 you get the same content you had in step 2.
At step 3 DB4S should warn if the file cannot be saved.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x ] Windows: ( _version: 8.1 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ x ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yep, that does sound like a missing warning.  At least some kind of alert box should pop up letting the user know about the problem.

**Comment by MKleusberg** [comment]
Thanks for reporting this issue, @palmiche! And sorry for taking so long :wink: But I believe this issue should be fixed in the next nightly build. Do you have the chance to try tomorrow's (or any later) nightly build and check if it's working for you? You can find the links to the nightlies on the main page of our repository 😄

**Comment by palmiche** [comment]
Happy to! 😄

**Comment by palmiche** [comment]
This one and #1035 are fixed in the lastest nightly (well, afternoonly 😄).
