### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by xangels** [sqlitebrowser/sqlitebrowser#1038]
### Details for the issue
Open a database
go to browse
now click on the drop down and choose the first item on the list.
Crashes - Yes nightly build

**Comment by xangels** [comment]
Sorry this is for DB Browser for SQLite

**Comment by justinclift** [comment]
Yeah, there are definitely problems in our recent nightly builds.  Just no time for investigating the problem yet. ☹️ 

The ones **before** 19th May seem ok.  eg 18th of May and earlier

Depending on which Operating System you are using, grab an appropriate one here:

* https://nightlies.sqlitebrowser.org/win64/
* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/osx/

Does that help? :smile:

**Comment by xangels** [comment]
Confirmed. May 18th is fine.

**Comment by justinclift** [comment]
Cool.  Hopefully we'll get the crash problem fixed in the next week or so.

**Comment by chrisjlocke** [comment]
A duplicate of #1019.
