### ISSUE TITLE
Shortcut Key for Edit Database Cell

### ISSUE THREAD

**Issue by lovebdsobuj** [sqlitebrowser/sqlitebrowser#1039]
Is there available an keyboard shortcut key that will **Apply** **`Edit Database Cell`** value.

**Comment by chrisjlocke** [comment]
Ctrl+Enter (on Windows, at least...)

**Comment by lovebdsobuj** [comment]
I'm using DB Browser for Sqlite on Linux. And your mentioned shortcut key work.

Is there any way that we can customize Keyboard shortcut?

**Comment by chrisjlocke** [comment]
Unfortunately not.  Due to the way Qt works, they have been hardwired in.  There is probably a better way of doing it, but its low on the list of things to fix.  Once we get bored and have nothing to do, it'll probably get looked at, as it would be nifty.  👨‍🍳
