### ISSUE TITLE
Is SqlCipher supported/

### ISSUE THREAD

**Issue by zhouhao27** [sqlitebrowser/sqlitebrowser#1040]
I need to encrypt my database. I'd like to know if SQLCipher is supported? How am I going to use it? Thanks.

**Comment by zhouhao27** [comment]
I found it. Thanks.

**Comment by chrisjlocke** [comment]
Just for completeness (in case anyone else finds this query but no solution), SQLCipher is now part of DB Browser and is integrated.  Simply open a database (or create a new one) and from the **File** menu, select **Set Encryption**.

![image](https://user-images.githubusercontent.com/7872218/27175158-36190b14-51b6-11e7-9d1f-f2e7339017b1.png)

The nightlies are built using a different process, and you can actually pick whether you need SQLCipher support or not.

**Comment by ankostis** [comment]
For Debian (at least) the browser has been compiled without SQLCipher upport - you have to compile it from the sources.
