### ISSUE TITLE
Cannot open file Debug.obj when Compile DB4S using MSVC

### ISSUE THREAD

**Issue by mukhtaramin** [sqlitebrowser/sqlitebrowser#1044]
### Details for the issue
I tried to compile DB4S using MSVC by following the procedures on this page https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S
on the step 12, I got an error LNK1104: cannot open file 'C:\git_repos\sqlitebrowser\libs\qscintilla\Qt4Qt5\Debug.obj' on Project DB Browser for SQLite.

I have tried to add the path in linker input, but nothing change. Does anyone have a clue?

Thank you for the help :)

#### I'm using DB4S on:

- [ x] Windows: ( _version:10)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Haven't looked at the paths, but 'Qt4Qt5' doesn't look right ... shouldn't it be one or the other?

**Comment by mkhtrmn** [comment]
In fact, the path 'Qt4Qt5' does exist https://github.com/sqlitebrowser/sqlitebrowser/tree/master/libs/qscintilla/Qt4Qt5

**Comment by justinclift** [comment]
@chrisjlocke Yeah, that's one of the paths of the QScintilla library.

@mkhtrmn Would you be ok to cut-n-paste the few lines before that error message?  That might help us figure out what's going on.

Oh... it might be useful to take a look at the file size of `C:\git_repos\sqlitebrowser\libs\qscintilla\Qt4Qt5\Debug.obj` too, just in case it's missing or 0 bytes in length or something. :smile:

**Comment by mkhtrmn** [comment]
Hello, I have solved the problem after uninstall and reinstall all the software. Don't know what was the problem 😅 

However, on step 13, I found the following error when building the INSTALL 

> Error	101	error MSB3073: The command "setlocal
"C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	132	5	INSTALL

**Comment by MKleusberg** [comment]
Looks like this is solved then :smile: I'm going to close this issue then.
