### ISSUE TITLE
case insensitive autocomplete

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1046]
### Details for the issue
I'd love to have autocomplete on table names case insenstive. as My tables usually begin with uppercase char, I'd like if they would come up in autocomplete even if I start writing their name with lowercase.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Wow, never knew that before.  Most of my tables are normally always lowercase, so haven't come across this before.

**Comment by justinclift** [comment]
@mglatz This sounds like a reasonable idea.  Not sure how easy or difficult it would be to add, but it wouldn't surprise me if we just needed to enable some option when we initialise our QScintilla bits (which we use for this).

This sounds like it might be the right kind of thing:

*  http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html#a8348c07fe8cff0bf6141a94ca3014ed2

Hmmm, it seems like we already set that to `false`:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/6c9c56a2a9b0a09690e9598b7f6b43be06305176/src/sqltextedit.cpp#L107

So maybe that's not the option we need for this... :wink:

Someone else will probably know more about this stuff. :smile:

**Comment by chrisjlocke** [comment]
It does say though, "Note that setting a lexer may change the case sensitivity." which is then what happens in line 118.  

https://github.com/sqlitebrowser/sqlitebrowser/blob/6c9c56a2a9b0a09690e9598b7f6b43be06305176/src/sqltextedit.cpp#L118

Maybe the `setAutoCompletionCaseSensitivity(false);` could be put after that line, or debug what the case sensitivity is, to see if its been changed.

**Comment by justinclift** [comment]
Ahhh.  We could move the whole [`if {}` clause](https://github.com/sqlitebrowser/sqlitebrowser/blob/6c9c56a2a9b0a09690e9598b7f6b43be06305176/src/sqltextedit.cpp#L103-L112) to after line [129](https://github.com/sqlitebrowser/sqlitebrowser/blob/6c9c56a2a9b0a09690e9598b7f6b43be06305176/src/sqltextedit.cpp#L129).

As in, I can do that right now in our master branch, if someone wants to check the nightly build tomorrow. (?) :smile:

**Comment by justinclift** [comment]
... or I could just test it myself right away.  Hmmm, gimme a few mins... :smile:

**Comment by justinclift** [comment]
Just tried it.  Nope, that didn't work.  Looks like it'd need a bit careful attention to figure out. :wink:

**Comment by MKleusberg** [comment]
This should be fixed in the next nightly build. @mglatz Can you download and try the nightly build tomorrow or some later day to confirm it's working for you? There's currently a bug in our nightlies which causes them to crash more frequently though - we'll try to fix that as soon as possible, too :wink:

**Comment by chrisjlocke** [comment]
I can confirm this now works.  

![image](https://user-images.githubusercontent.com/7872218/27577449-9b5ea27a-5b18-11e7-81c1-f2e1ea671b05.png)

Prodding @mglatz ... ;)  🎋

**Comment by mglatz** [comment]
wow thanks! :)

**Comment by chrisjlocke** [comment]
If you can confirm it works OK for you, @mglatz, I'll close this issue. 🍾

**Comment by mglatz** [comment]
I downloaded recent nightly (3.9.99 x64) and now I get no autocomplete on table names at all. I see autocomplete only on sql keywords (select, begin...)

**Comment by mglatz** [comment]
it works on latest nightly (3.9.99 x64)

**Comment by chrisjlocke** [comment]
Thanks for reporting back! 👍

**Comment by mglatz** [comment]
I think this no longer works on 3.9.99 beta. can anyone confirm? thanks

**Comment by justinclift** [comment]
Oh, interesting.  Does it work with the 3.10.0-beta1 release from a few days ago?

**Comment by chrisjlocke** [comment]
Works for me on Win 10 x64 for the beta...

![image](https://user-images.githubusercontent.com/7872218/28776303-f9a81eb6-75ed-11e7-8ac3-7255aed774b0.png)

**Comment by mglatz** [comment]
Turns out I did not have the proper version installed (beta), but one of earlier builds. In Beta (3.9.100) it works. Sorry for confusion.

**Comment by justinclift** [comment]
No worries at all. :smile:
