### ISSUE TITLE
Support command line usage?

### ISSUE THREAD

**Issue by CoXier** [sqlitebrowser/sqlitebrowser#1047]
Recently I want to view a db file with help of a tool.After google,I find  sqlitebrowser may be useful for me.Yes I succeed in opening db file with it.

My way is :

* extract file from android 

 > adb exec-out run-as package.name cat databases/file > file
* open the file manually with `sqlitebrowser`

However it's very troublesome.So I want to write a script to wrap above two steps.But I have not any idea.

Much thx for any help.

**Comment by justinclift** [comment]
Yep, you should be able to get this working.  If you have (for example) a database called "foo.sqlite", you can open it from the command line with:

```
sqlitebrowser foo.sqlite
```

I'm not sure how adb works, but it seems like you can extract a file from android with it.  So, whatever the filename is... that's what you'd pass to sqlitebrowser.

Does that help? :smile:

**Comment by CoXier** [comment]
Can you tell me where is the `sqlitebrowser` bin file so that I can set path ?

**Comment by justinclift** [comment]
This seems to work:

```
brew tap caskroom/cask
brew cask install sqlitebrowser
/Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite myfile.sqlite
```

On OSX, the command line program name is "DB Browser for SQLite".  Don't be too bothered by it, it still works fine. :smile:

**Comment by CoXier** [comment]
Thanks.

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by CoXier** [comment]
After I invoke above command, it always works foreground so can I let it work background.

**Comment by justinclift** [comment]
Hmmm... I'm not sure.  On OSX there's a command line program called "open", which lets you launch applications.  For example:

    open /Applications/DB\ Browser\ for\ SQLite.app foo.sqlite

It might be possible to pass some kind of command line switch to that, so it opens DB4S (our name for sqlitebrowser) in the background.  I'm not sure, and I'm not on my OSX desktop at the moment.  You'll need to investigate and experiment. :smile:

**Comment by CoXier** [comment]
Cool , thanks

**Comment by mroswell** [comment]
justinclift's solution really needs to be added to the Mac documentation. (If it's there I missed it.) It worked, but I never would've figured that out on my own. The one thing I needed to change was the last argument: the name of the database, (which in my case ends in "db").
