### ISSUE TITLE
SQL vs. HTML

### ISSUE THREAD

**Issue by tauch** [sqlitebrowser/sqlitebrowser#1052]
### Details for the issue

When using the built-in SQL editor/execute and writing something like 
**WHERE a.size > 1000 and .........**
Then that requests becomes HTML-mangled and the SQL-log shows:
**WHERE a.size &amp;gt; 1000 and ...........** 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
Thanks for reporting this. This issue has been already fixed in the nightly builds but we didn't get around releasing an official version yet.

You can wait till we release v3.10 or you can try the latest nightly builds which fixed this. The latest nightly builds can be found here

https://nightlies.sqlitebrowser.org/latest/

**Comment by karim** [comment]
@tauch Did you get the chance to try our nightly build to see if it fixed your problem?

**Comment by tauch** [comment]
thank you very much for the fast response and the great softwar - it's solved in nightly :)

**Comment by karim** [comment]
The nightly version has a lot of bug fixes and new features that will soon become the next v3.10 version. If you have any more questions or if you encounter any problems please report it here again.

And thanks for reporting back and we are glad your problem is solved. 😄
