### ISSUE TITLE
Can one change the column affinity in an existing SQLite table using the SQLite Browser?

### ISSUE THREAD

**Issue by lhunsicker** [sqlitebrowser/sqlitebrowser#1054]
### Details for the issue

Everything that I have read about SQLite tells me that one cannot change the definition of a column (in particular, its affinity) in an existing populated SQLite database.  One is supposed to create a new table with the schema from the original table edited with a changed column affinity, then insert the data from the first table into the new table.  But as I have been trying out your SQLite Browser, I find that there is an option to modify an existing table, and, indeed, I have been able to change a column affinity in an existing "toy" (but large) database.  The change happens quickly enough that I am led to doubt that you are going through the above steps behind the scene.  What is your magic?  Are you able to edit the SQLite-master table?  I'd appreciate any help that would explain this situation to me.  Thanks in advance.
Larry Hunsicker

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X ] DB4S needs a feature  -- or maybe has an unexpected feature.
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:10.0.15063 N/A Build 15063 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.9.1
- [ ] 3.9.0
- [ ] Other: 

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
SQLite itself does not support editing columns.  
http://sqlite.org/lang_altertable.html

The way around it (as described in the above link too) is to create a new table and copy the data over.  That doesn't take too long, as its all done in one transaction.  Thats the method used by DB4S.
So yes, you can happily change a columns affinity whenever you want, regardless of whether there is data in the table or not.  SQLite doesn't care about the data contents when setting column data types.

**Comment by lhunsicker** [comment]
Neat!  Many  thanks.

But now a problem/question.  I have a pretty large production database that I initially loaded into SQLite directly from a *.csv table using the RSQLite dbWriteTable() function.  There is one column that the importing software identified as being of INTEGER affinity, but actually is filled with text data -- except for seven pathological entries that are, actually, integers and were entered into the SQLite table with the INTEGER type.  

This is not a big problem.  When the column is imported back into R, again using RSQLite, I get a warning that the column was of mixed type, and that the integer values were coerced into text for importation.  This is appropriate, and not an analytic issue.  But I manage this database for a small group of folks that may be alarmed by the warning.  So I'd like to switch the column affinity from INTEGER to TEXT.  It may be important to note that this column has no keys or indices defined on it.

This worked in my toy database table.  But it isn't working for the real, pretty big, production table.  I used the following sequence to try to do this.  a)  loaded the containing database, b)selected the table in the Database Structure tab, c) selected the "Modify Table" icon, which brought up the Edit Table Definition window, d)  selected the column and changed the data type from INTEGER to TEXT in the associated drop down box, e) waited quite a while as my computer thought about this, but eventually the twirling "wait a moment" gizmo went away.  So I clicked OK and the Edit Table Definition window closed, f) rechecked the table definitions.  The definition of the column wasn't changed to TEXT!  g) So I clicked the Write Changes tab to be sure that the change had been written to the database.  Still the definition of the column wasn't changed to TEXT, h) so I vacuumed the whole database to be sure that the change wasn't dangling somewhere else not yet completed.  Still no change in the column type.

I have had no problem changing the affinity of a column in my "toy" database.  So I know that your system works in general.  But there is something blocking the change in my production database.  Any suggestions?

Many thanks for your help.  I really like SQLite Browser, and I am gradually learning how to use all of its features.  Great app and great job.

Larry Hunsicker


----- Original Message -----

**Comment by chrisjlocke** [comment]
My first thought is to remove all the data (creating a test database...) and try again. This would rule out a schema issue or a data issue. 
Is there any chance you could forward me the database so I could test, or does it contain personal / confidential data?

**Comment by lhunsicker** [comment]
Thanks, Chris:

I'm going to recreate and repopulate the table using the SQLite3 bash shell system.  If it works, that will tell me that the problem is with the SQLite Browser rather than with SQLite itself (and will also solve the problem for me).  If that doesn't work, it will tell me at what step in SQLite itself the problem lies.  There are three of these pathological columns in two tables, one in each of two databases.  So if it works or if I can find where the problem lies, I can see whether I can get by the problem in the SQLite Browser. 

Unfortunately the data in the databases are all confidential, so I can't share the database with you.  But if I can figure out at which step the failure occurs, I may be able to construct a different "toy" database that has the problem, and I can share that with you so that you can fix stuff in the Browser if there is a problem there. 

Larry Hunsicker


----- Original Message -----

**Comment by lhunsicker** [comment]
OK.  I have an answer.  And as it always true for these sorts of things, the answer is obvious once you know what it is.  So I downloaded the schema for the table, edited it to change the name of the table and change the column affinity to text, and copied the amended schema back into the SQLite3 bash shell.  The table was created, but the action aborted when it came to creating the three indices on the table.  While none of these indices referred to the column variable that I wanted to change, the indices DID have the same names as the indices for the original table, and of course one can't have two indices with the same name.  So I delayed creating the indices, copied the table contents from table 1 to table 2, dropped the original table (and of course, its associated indices), and then recreated the indices at the end of all of the above.  Then all was as I had intended.  This all worked, and my immediate problem is solved.
You mentioned, however, that the SQLite Browser does this entire sequence of operations in a single transaction.  My guess is that your code, also, copies the definition of the indices from table1 to table2, and of course the creation of the indices fails because of the name conflict, causing the entire transaction to be rolled back.  The simplest solution for this bug would be to create the new table in a different schema -- probably the "temporary" schema.  I am assuming that the names of the indices in the second schema won't conflict with the names of the indices in the original schema.  Does this make sense?
Larry Hunsicker

**Comment by lhunsicker** [comment]
I think that I got the problem sorted out.  See my update on sqlite issue 1054.  
In any case, I solved my own problem!  Thanks for the help and interest.

Larry Hunsicker


----- Original Message -----

**Comment by justinclift** [comment]
Cool.  Are we ok to close this issue? :smile:

**Comment by lhunsicker** [comment]
Yes.  Thanks for your help, and thanks for the SQLite Browser!

Larry Hunsicker

**Comment by justinclift** [comment]
Cool, no worries. :smile:
