### ISSUE TITLE
Data Browser displays wrong row number

### ISSUE THREAD

**Issue by cyz199611** [sqlitebrowser/sqlitebrowser#1055]
### Details for the issue

I use the DB Browser on Mac OS, and when I click the Data Browser, I found that it always displays 
"1 - 0 of 0" at the buttom left and I cannot go to the row number that I want to go. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ *** ] Mac OS: ( _version: 10.10.5 )
- [ ] Other: ___

#### I'm using DB4S version:

- [ *** ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ *** ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ *** ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

![bug](https://user-images.githubusercontent.com/30024330/27995462-fdf9cc10-64ce-11e7-9ecc-a0a5d77d9b10.png)

**Comment by justinclift** [comment]
Oh, interesting bug.  We updated the bits for calculating row numbers a few weeks ago, and it looks like we didn't get it quite right for the case where there are only a few rows in a table.

**Comment by chrisjlocke** [comment]
This might be linked/is similar to #1028.

**Comment by chrisjlocke** [comment]
Hi @cyz199611 - DB4S has been updated a fair bit recently.  Can you confirm you're still getting this issue?

**Comment by cyz199611** [comment]
Hi @chrisjlocke Thanks for reminding, the issue has been solved. Thanks for the continuous support for this amazing application.
