### ISSUE TITLE
"Edit Database Cell" output refreshes when selection changes on the "Browse Data" Tab; refreshes on double-click on the "Execute SQL" Tab

### ISSUE THREAD

**Issue by Wikkie** [sqlitebrowser/sqlitebrowser#1056]
### Details for the issue

When the _Edit Database Cell_ window is visible, it very nicely reflects the contents of each cell that the cursor visits on the _Browse Data_ tab (without having to double click/hitting the enter key).

However, when browsing a SQL Query result on the _Execute SQL_ tab, then the contents of the _Edit Database Cell_ window only refreshes on double click or enter key.

It would be nice if the _Edit Database Cell_ window behaved the same way on the _Browse Data_ and the _Execute SQL_ tabs.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 7 _ ___ )
- [x] Linux: ( _distro:_ubuntu 17.4)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x ] Other: 3.9.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
@MKleusberg Didn't we get this solved a while back?

**Comment by Wikkie** [comment]
Hi, Sorry for the late answer. I just installed the latest nightly (Version 3.10.99) where the feature works like requested. Thanks

**Comment by justinclift** [comment]
Awesome. :smile:
