### ISSUE TITLE
text formatting in SQL query

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1057]
### Details for the issue

sometimes when I edit SQL query the text gets messed up, see picture.
https://snag.gy/Hp6Cs0.jpg
the SQL is correct and will run, I't just not displayed properly

### Useful extra information

I'm using nightlies, currently 2017-07-19 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:10 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: 3.9.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting, thanks for reporting it.  Any idea what might trigger it?

**Comment by chrisjlocke** [comment]
Never seen that on my Windows 10 box(es).  However, I notice the font used isn't a fixed width font.  I haven't changed mine from the default 'Consolas'.  Just switched to 'Arial' and that seemed OK.
Which font are you using @mglatz ?  Have you tried Consolas or Arial?

**Comment by mglatz** [comment]
I seen the error with font Courier New. Now I switched to consolas and have not seen the issue since.
I don't see it always, I can't really determine what might have triggered it.  It only occurs when I make multiple edits to query, I don't remember it would occur on sql I wrote from scratch.

**Comment by chrisjlocke** [comment]
Aah, that would be why I've not encountered this error before then - 99.999% of my table names are derived from the 'standard' character set, not the extended characters.  I'll assume the editor can't cope with so many extended characters together.
I'll add 'extended character set' into the title, to make the issue more specific.  For completeness, could you confirm the error doesn't occur if you use table names derived from the standard character set?

**Comment by chrisjlocke** [comment]
Arial correctly shows the accented characters for me?

![image](https://user-images.githubusercontent.com/7872218/28417565-7be3809c-6d50-11e7-80b0-1b0150a8619c.png)

**Comment by mglatz** [comment]
the original reported bug is not related to special characters.  The original screenshot is messed up although no special character are used. 
My editor has funny behavior :) in the below screenshot (arial) you can see that now I see chars with accent (OK) and the cursor is displayed at wrong position, in reality, it is at the end (not OK).
I suspect I'll have to reinstall windows : )
Also as mentioned earlier, I'm using latest nightly. Might that be to blame?

![image](https://user-images.githubusercontent.com/8293281/28419438-34e876c0-6d5f-11e7-9115-90e6f2f59f60.png)

**Comment by justinclift** [comment]
In theory :wink:, the nightly builds at the moment should be in reasonably decent condition.  We'll be making a first "3.10.0" beta release out of them today or tomorrow.

Personally, I have no idea why the weird characters are happening.  Am kind of wondering if it might be related to the update we did of QScintilla2, which we use for the SQL Editing part of things.  That was done on 4th May, so if you have time/interest to try a nightly build from before that (eg 2nd May or earlier) that could help figure out the cause. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/win64/2017-05/

**Comment by mglatz** [comment]
I think I found reliable method to invoke display issue. if I press and hold accented character, the cursor will move slower, eventually having this (cursor is in fact at the end of the string). This is on latest nightly and the error does not occur with normal character. 
![image](https://user-images.githubusercontent.com/8293281/28422955-dfec4cf4-6d69-11e7-934e-49de5a6d1dcd.png)

I installed version 2017-05-01 and advised above and this error does not occur. I will test it some more and let you know.

![image](https://user-images.githubusercontent.com/8293281/28423030-2aa455fc-6d6a-11e7-88d8-bf4dff117dee.png)

**Comment by justinclift** [comment]
@mglatz Would you have time to try out one of these?

* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-07-21-win64-Qt_5.9.1.exe
* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-sqlcipher-2017-07-21-win64-Qt_5.9.1.exe

They're the same nightly build as last night, but made with the latest release of Qt just to see if it makes a difference.  It's purely an experiment, to see if it changes the behaviour. :smile:

**Comment by mglatz** [comment]
tried the first one, not ok
![image](https://user-images.githubusercontent.com/8293281/28464466-b2ba7bea-6e25-11e7-860a-75d8f9f0fc7d.png)

**Comment by justinclift** [comment]
@mglatz Cool, thanks for checking.  That tells us it's probably not a Qt bug problem.

I'm kind of tempted to make a build with the slightly older version of QScintilla2 we were using until 4th May, and see if the problem goes away.  I'll take a look at doing so later on today, I'm just focused on other areas at the moment. :wink:

**Comment by mglatz** [comment]
I also figured out that the text gets scrambled when the query finishes.
If I have a multiline query and let it run, sometimes after result is shown the query text changes to scrambled version (such as in original screenshot), even with no special characters. To fix it I have to copy the SQL, open new query tab and paste it there, if I cut and paste to same query tab, the text remains scambled.


(still using build from justinclift)

**Comment by mglatz** [comment]
I did a clean install of windows and with the latest beta (I installed DB Browser for SQLite-2017-05-01-win64.exe, in about I see version 3.9.99), and I dont see the error anymore. I therefore suspect It really might have been an issue with my windows, rather than app bug. Thank you for all the support!

**Comment by justinclift** [comment]
Thanks @mglatz, hopefully it does turn out to be that simple. :smile:

**Comment by mglatz** [comment]
Turns out I did not have the proper version installed (beta), but one of earlier builds. the beta still has this issue.

**Comment by justinclift** [comment]
Interesting.  Ok, we'll need to look into this. :smile:

**Comment by mglatz** [comment]
this issue seems resolved on 3.10.0
long pres and hold of accented character no longer  messes up the layout. 
will update here if i see that bug again.

**Comment by justinclift** [comment]
Thanks @mglatz.  Personally, I have no idea what the cause of the problem was, but I'm glad it's working now. :smile:
