### ISSUE TITLE
Access version number from terminal

### ISSUE THREAD

**Issue by FriedrichFroebel** [sqlitebrowser/sqlitebrowser#1064]
### Details for the issue

It may be helpful to have a command line option (or default info text when using the `--help` argument) to print the version number.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ X ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ X ] Linux: ( _distro:_ Ubuntu 16.04 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good thinking @FriedrichFroebel.  :smile:

At a quick look, it'll probably need to be added here and doesn't look too difficult:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/7baea3bef1f843a522d357f610c38c66ef58d285/src/Application.cpp#L60-L101

**Comment by FriedrichFroebel** [comment]
Seems like this issue can be closed after commit https://github.com/sqlitebrowser/sqlitebrowser/commit/441a08a44d8367f965132cc552c918ce2db09e71.

**Comment by justinclift** [comment]
Ooops, yep.  I forgot to close this the other day, thanks. :smile:
