### ISSUE TITLE
Tooltip text for the Browse Data arrows is no longer correct

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1067]
### Details for the issue

Now that the paging arrows in the "Browse Data" tab no longer moves by 100 records, we'll need to update the tooltips to match.

Weirdly, good updated description text isn't springing to mind.  Hopefully @chrisjlocke or @MKleusberg have an idea for text to use. :smile:

![screen shot 2017-07-28 at 14 27 14](https://user-images.githubusercontent.com/406299/28719315-6203b5c8-73a1-11e7-9e45-4f46e67096c1.png)

![screen shot 2017-07-28 at 14 27 21](https://user-images.githubusercontent.com/406299/28719322-67066a84-73a1-11e7-8dc5-6e6382736f48.png)

**Comment by chrisjlocke** [comment]
Are the tooltips dynamic, or are they static?  If dynamic, then they can change depending on what the button is going to do - "Page up {x} records", etc.  If static, "Page up"  ?  😆 (or down....)
Interesting you yourself call them 'paging arrows' rather than 'scrolling arrows'.  People are familiar with the page up/down button on their keyboards, so maybe they should reflect that? (especially as they work in the same way...)  But thats just a thought.

**Comment by justinclift** [comment]
Hmmm, from memory they're static.  It's probably possibly to make them dynamic (eg change them when the paging quantity changes), but that's probably not worth the effort.

My terminology for them... meh... that's just the wording that sprang to mind.  Not necessarily the correct terms. :wink:

**Comment by chrisjlocke** [comment]
Aah, I didn't know if it was like the shortcut keys, where they're hard coded.

**Comment by MKleusberg** [comment]
Yeah, they can be changed dynamically but it would require some extra effort and might even be confusing to users (e.g. when it says it scrolls 15 rows down and then you assume it'll be doing the same thing even after you've resized the window).

Anyway, I've just changed the tooltips and the What's this?-text to... well something more appropriate. Not sure either if it's perfect, but we can always change it if somebody has a good idea :smile:

**Comment by justinclift** [comment]
Heh Heh Heh.  "One page upwards" (& downwards), yep that's good.  Simple and easily understandable. :smile:
