### ISSUE TITLE
Update to newest vcredist 2013

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [sqlitebrowser/sqlitebrowser#1068]
I think sqlitebrowser should update to the newest vcredist 2013 (Microsoft Visual C++ 2013 Update 5 Redistributable Package) version 12.0.40649.5.

The download-link is:
https://support.microsoft.com/en-us/help/3138367/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by justinclift** [comment]
Ahhh cool.  Thanks for pointing it out, we'll make sure the next beta's and release are updated with it. :smile:

**Comment by justinclift** [comment]
It's probably not a bad idea to get it into our nightlies as well, which I'll look at over the next few days too.

**Comment by justinclift** [comment]
@Tobias-B-Besemer I've just updated the redistributables in on out nightly build server, so our nightlies should now include them instead.  Our next releases (also done on the build server), should automatically pick them up too.

That being said, it wouldn't hurt for someone to take a look in a few days time to make sure things haven't unexpectedly gone weird for some reason. :smile:

**Comment by justinclift** [comment]
Just updated the URL in our [Win build environment setup doc](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S) too.

**Comment by justinclift** [comment]
@Tobias-B-Besemer I think this can be considered completed now, as the build server is using them for nightlies and our new releases.

If you're up for double checking from your point of view, would you be ok to grab either of the 32 or 64 bit binaries from this mornings' [3.10.0-beta2](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.0-beta2) release and verify it includes the correct ones?

**Comment by chrisjlocke** [comment]
I ran DB4S on a win 10 x64 (just from an extraction, not an install) and it
moaned about 4 DLLs not found. I manually ran the redist and it worked fine
after that. So it's good from my point of view... I've done win 8 boxes too
also test it on. No x86 win 10 boxes though, I don't think.


Thanks,
Chris

**Comment by justinclift** [comment]
Cool, that's good enough for me.  Thanks @chrisjlocke. :smile:

**Comment by Tobias-B-Besemer** [comment]
Did a test with Win7 & 64-bit. Works for me!

**Comment by justinclift** [comment]
Awesome, thanks @Tobias-B-Besemer. :smile:
