### ISSUE TITLE
Small typo in EditTableDialog

### ISSUE THREAD

**Issue by mafagafogigante** [sqlitebrowser/sqlitebrowser#1073]
### Details for the issue

In

```
<html><head/><body><p><span style=" font-weight:600; color:#ff0000;">Warning: </span>There is something with this table definition that our parser doesn't fully understand. Modifying and saving this table might result it in problems.</p></body></html>
```

one can find "Modifying and saving this table might result **it** in problems."

Maybe the intended wording was "Modifying and saving this table might result in problems."

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0-beta1
- [ ] 3.9.1
- [X] Other: 52f23a03a0f125029ee9e2d87ac4c0be5212d451

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mafagafogigante** [comment]
While we are at this topic, there is also an unbalanced parentheses issue in the foreign key tip.

![screenshot from 2017-07-31 13-51-39](https://user-images.githubusercontent.com/8271090/28788951-6f0994b8-75f9-11e7-847d-b7891bb0a3e9.png)

**Comment by justinclift** [comment]
Thanks @mafagafogigante.  Yep we can probably fix those today once GitHub stops being flaky. :smile:

**Comment by mafagafogigante** [comment]
@justinclift I am about 90% done with the PT-BR update, I will translate them as if they were already fixed, is that OK? This way I don't have to perform another update an hour later.

**Comment by justinclift** [comment]
Yep, that should work fine. :smile:

**Comment by mafagafogigante** [comment]
I will also fix the last translations I wrote for the plotting tool. Some of the descriptions of the dot symbols could be further humanized.

**Comment by MKleusberg** [comment]
Well spotted! :smile: Both should be fixed now.

**Comment by mafagafogigante** [comment]
That's great.

**Comment by MKleusberg** [comment]
Closing this issue then 😄 If it turns out to be still wrong in some way we can always reopen the issue 😉
