### ISSUE TITLE
dbhub: "Save to remote" dialog should pre-fill most info

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1076]
The current dialog for the "Save to Remote" option very basic:

![screenshot_2017-08-01_12-52-26](https://user-images.githubusercontent.com/406299/28824062-571149cc-76b8-11e7-8abc-1cb02194908b.png)

It should instead probably show a drop down of the server list (as per the Remote panel) with the current server preselected, and field for the database name, pre-filled with the name of the current database.

While we're at it, it should probably also display a drop down for the licence (from the list provided by the server), with "Not specified" as the default option, and have a private/public option (default to "private").

The ideal I have in mind is the user clicking the "Save to Remote" option, and then not needing to fill in any other details because they're already automatically filled in.  Unless they want to change something from the defaults that is. :smile:

So, they could just click OK or press Enter and it'd upload the database to dbhub.io, set to private.  Private is likely the correct default option, to prevent accidental sharing of data. :smile:

**Comment by MKleusberg** [comment]
What do you think? Can we close the issue now that the new Push database dialog is there? 😄

**Comment by justinclift** [comment]
Ahhh, yep.  Definitely. :smile:
