### ISSUE TITLE
dbhub: Remote database list not refreshed after upload

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1082]
@MKleusberg Just remembered this one... after uploading a database using the remote tab, it doesn't automatically appear in the list of databases.

Seems like it just needs to have an automatic refresh call added after uploading.

Guessing this'll be pretty trivial to add. :smile:

**Comment by MKleusberg** [comment]
Can you check again with the latest version? 😄 It should refresh automatically now.

**Comment by justinclift** [comment]
Cool, compiling now. :smile:

**Comment by justinclift** [comment]
Excellent.  Perfect!  Thanks @MKleusberg. :smile:
