### ISSUE TITLE
Wrong filename pattern on OSX for "Import SQL" dialog

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1084]
Using OSX atm, and just noticed that (with our very latest git master), the default filename pattern for the "Import SQL" dialog is showing up as "*.csv *.txt".

Not sure if it's another OSX-only thing, or if the problem also happens on other platforms.  I'll try it out later to check.

**Comment by justinclift** [comment]
Ahh... no... it might be a translation problem.  When I switch back to English, the correct filename pattern "*.sql *.txt" is there.

We should probably ask @progh2. :smile:

**Comment by MKleusberg** [comment]
Yep, the original filename pattern can be [found here](https://github.com/sqlitebrowser/sqlitebrowser/blob/bbbadba732d7eb3f45d1e6b91daa3df4273bf012/src/MainWindow.cpp#L1240) and looks correct to me 😄

**Comment by progh2** [comment]
I checked it in korean transition. 
I will fix it.

**Comment by justinclift** [comment]
Thanks @progh2. :smile:

**Comment by justinclift** [comment]
Closing this as it was just a typo in the Korean translation, fixed a few weeks ago. :smile:
