### ISSUE TITLE
Table headings gets bolded when clicked on

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1087]
### Details for the issue

This issue is so minor, its not even an issue.  Maybe just an 'iss'.

On the 'remote' tab, if you click in a table...
![image](https://user-images.githubusercontent.com/7872218/29277890-f5c092ec-810a-11e7-923e-9b7c8f31dfd5.png)

the headings get bolded.

![image](https://user-images.githubusercontent.com/7872218/29277904-03e1a21c-810b-11e7-82d8-138780c6eba7.png)

It causes 0 problems, but its just a 'quirk'.  Hardly worth mentioning.  Just makes my eyes twitch when it happens.... ;)  🐧 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0-beta1
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Should be fixed with the latest commit 😄 Thanks for the thorough testing, @chrisjlocke!

**Comment by chrisjlocke** [comment]
Thanks for spending time fixing it!  I'm learning how these 'tweaks' get done to aid in my coding journey.

**Comment by justinclift** [comment]
Confirmed as fixed here, testing on Linux. :smile:
