### ISSUE TITLE
Attach database not working in 3.9.x beta

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1088]
### Details for the issue

The attach databse feature does not work, after specifying attached db name, it throws [near "KEY": syntax error]. 
tested on version 3.9.100 and 3.9.200

### Useful extra information

Probably works on stable realease (not tested) 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 10 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0-beta1
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oh, that doesn't sound good.  Thanks for reporting it @mglatz. :smile:

@MKleusberg Sounds like one for you. :smile:

**Comment by chrisjlocke** [comment]
See #617 - This has been open a while.  I've never managed to get 'attach' working in DB4S (although I never got the above error - it just did nothing)

**Comment by mglatz** [comment]
I seen the referenced issue. I used attach database feature several months ago with no problem and now noticed it does not work on beta. Thought it has been fixed and broken again.

**Comment by justinclift** [comment]
Yeah, I'm pretty sure the attach statement should at least work, even if it doesn't show the database in the GUI.  @MKleusberg will probably go something like "Oh, I know what's probably causing that..." then proceed to get it fixed to work again. :smile:

**Comment by MKleusberg** [comment]
Oh, I know what's probably causing that... 😜 It's that in the SQLCipher build we're always trying to add a passphrase (for attaching encrypted databases), even if the database isn't in fact encrypted and a passphrase therefore doesn't exist. That results in an invalid SQL statement which in turn shows the error message.

With the latest commit the issue should be fixed. Are you ok to test tomorrow's (SQLCipher!) nightly build and check if it's working, @mglatz? And thanks for reporting this issue! I haven't tested the SQLCipher build recently. So this is really helpful 😄

**Comment by justinclift** [comment]
@mglatz If you'll be around your computer in about 1/2 hour from now, I can tell our windows nightly building server to rebuild the latest nightly downloads.

That takes about 1/2 hour, and would mean you don't have to wait until tomorrow.

Would that be useful?

**Comment by justinclift** [comment]
Meh... I just kicked it off anyway.  So, if someone needs a build with the attach bit likely working, it'll be ready for testing in 1/2 hour. :smile:

**Comment by mglatz** [comment]
thanks @justinclift  👍

**Comment by justinclift** [comment]
No worries. :smile:

The updated build is on the nightlies server now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
@mglatz Would you have time to try our new v3.10.0 release, and let us know if the attach database piece is working properly for you?

**Comment by chrisjlocke** [comment]
Just to confirm (as I've never used it in anger) but are attached database tables meant to show in the database structure tab?

**Comment by mglatz** [comment]
it works :)

**Comment by justinclift** [comment]
Awesome.  Thanks @mglatz. :smile:

@chrisjlocke Nope, it's a known thing that they don't show up there.  At some point it'd be good to have them do so, but AFAIK no-one's looked into it.
