### ISSUE TITLE
'Duplicate Record' doesn't duplicate selection

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1090]
### Details for the issue

Guess its not a bug per-se, as the menu option is 'Duplicate Record' and not 'Duplicate Records', but when you select a number of records, right click, and select 'Duplicate Record', only the record you right clicked on (so not necessarily the first / last record in the selection) is duplicated.

It would be nice if the selected records were duplicated and not just the record you right clicked on.

Linked to this, is that the right click doesn't cancel (or set) the selection under the mouse, so you could highlight rows 8 to 11, then right click row 3 and select 'Duplicate Record'.  Under 'normal' circumstances (in Windows, anyway), right clicking on row 3 (if not currently selected) would cancel the current selection and highlight row 3.  The selection does not get cancelled if right clicking a row is already selected.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0-beta2
- [ ] 3.10.0-beta1
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yep, makes sense. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Should this be closed now? :smile:

**Comment by chrisjlocke** [comment]
Forgot about this! Ooh. Yes, thanks to @mgrojo, another issue is squished.
