### ISSUE TITLE
Clicking 'Cog' icon sometimes crashes DB4S

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1093]
### Details for the issue

This seems to be a 'time' limited thing.  So start DB4S, and all is good.  However, after a period of time (hour?  two?) if you click the Cog icon, sometimes (not always) DB4S keels over.

![image](https://user-images.githubusercontent.com/7872218/29516127-1594e5d0-8667-11e7-8def-d8df3202e50f.png)

When testing, clicking the cog icon has worked, but clicking it again or on the third time, has crashed.
Prior to the crash, (on Windows) the cursor whirls round for approx 10 seconds, as if its trying to process something?  Normally, clicking the icon is relatively instant.

Haven't got much more detail than this, but thought I'd mention it...

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 x64 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [x] 3.9.200-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Wonder if that crash is fixed by 0c20582edbe0a4bbc9551d39680a7040f1bf402a too.

Do you have time to see if v3.10.0 seems ok?  v3.10.0 has the above fix in it. :smile:

**Comment by chrisjlocke** [comment]
Aah, will try it this afternoon.  I've had 3.9.200 open all weekend on my machine, and as soon as I clicked Mr Coggy, DB4S crashed, which led me to testing.  It was semi-repeatable.
Will try with the latest version.  👍

**Comment by justinclift** [comment]
@chrisjlocke Reminder ping for when you have a chance. :smile:

**Comment by chrisjlocke** [comment]
Can't reproduce today, so this might have been fixed.
