### ISSUE TITLE
[Suggestion] Progress for downloading/uploading

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1095]
### Details for the issue

I'm not sure whats possible, so just throwing this out as a suggestion.
Would it be possible to show how many KB/MB have been down/uploaded so far, to give some sort of progress on where the download/upload is?

Currently, the dialog gives no indication.

![image](https://user-images.githubusercontent.com/7872218/29522576-96109e92-8681-11e7-806b-c1866e2b5ea5.png)

I know with my own tinkerings with network traffic, its not always possible to get that info.

Edit: Oh, I see the upload already does that...

![image](https://user-images.githubusercontent.com/7872218/29522544-71ecf132-8681-11e7-8c75-bf8dea3b010d.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yep, it definitely should be possible.  Interestingly, the code for displaying the progress dialog is the same for both upload and download.

I *think* the problem is that the server isn't sending the filesize to DB4S when the download kicks off, so DB4S doesn't know where the end is until it hits it.

Kind of thinking I should be able to get that fixed today, in which case the download progress bar (hopefully) should just start working. :smile:

**Comment by justinclift** [comment]
Yep, it was a simple fix.  https://github.com/sqlitebrowser/dbhub.io/commit/6abd350f3576eb781197f21bed6bf2c21ab714f3

The download just needed a `Content-Length` header sent at the start.  Download progress bars are working (both Firefox and DB4S) now.  Well, at least when testing just now anyway. :wink:

**Comment by justinclift** [comment]
@chrisjlocke Reminder ping.  Hoping you have a chance to verify this. :smile:

**Comment by chrisjlocke** [comment]
I'll try again.  👍

**Comment by justinclift** [comment]
@chrisjlocke Reminder ping. :smile:

**Comment by chrisjlocke** [comment]
Aah yes, I was looking at this the other day when I came across the 'multiple download' issue, so forgot to update this one.  

Both are working well, so I can close this.

![image](https://user-images.githubusercontent.com/7872218/29963532-1bab350a-8eff-11e7-86a4-250379b0879f.png)

The pedant in me wants to remove the closing "." from the end of the filename though... 😉

**Comment by MKleusberg** [comment]
Just removed the closing "." from the upload and download dialog :wink:

**Comment by justinclift** [comment]
Oh, related to this, the upload progress bar doesn't show correctly with larger size files.  Instead the whole dialog just flickers.  The upload itself works though.

@MKleusberg If you're wanting to take a look, you don't need to upload the whole file.  It does the flickering thing right from the start.  Oh, I'll need to update the server so it doesn't apply the limits to you.  Will get that done in a sec anyway. :smile:

**Comment by justinclift** [comment]
k, upload limits via DB4S shouldn't affect yourselves now.  It's done via dodgy hot patch though, instead of anything proper... so might need to be reapplied again later until something better is put in place.  eg "Admin accounts" or similar as @chrisjlocke suggested the other day

**Comment by justinclift** [comment]
@MKleusberg Ahhh... "mtest3".  I whitelisted the wrong username.  1 min. :smile:

**Comment by MKleusberg** [comment]
No problem 😄

**Comment by justinclift** [comment]
k, should be good now. :smile:

**Comment by MKleusberg** [comment]
Hmm, I don't see any flickering... Is 223MB enough?

**Comment by justinclift** [comment]
Nope, the larger sized file problem doesn't seem to happen with the ~700MB one here, but does happen with the ~2.9GB one: :smile:

&nbsp; &nbsp; https://db4s-beta.dbhub.io/releases/justinclift/backblaze-drive_stats.db

**Comment by justinclift** [comment]
I haven't looked further to figure out where the threshold for mucking up is.

**Comment by MKleusberg** [comment]
Ok, give me some time for this. I'm downloading the 2.9GB file now :wink:

**Comment by justinclift** [comment]
Maybe generate your own? :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitedatagen

You'd need Go installed, but the generation itself is reasonably quick.  ~5 seconds per 80MB on this old Linux desktop.

**Comment by MKleusberg** [comment]
Yeah thought about that too but figured that it's faster to just download your file because it's just one click and I can do other stuff while it's loading :wink:

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/29965464-869e3dca-8f05-11e7-85d7-d90e07474684.png)

"Its OK - just Martin downloading those large test files again..."

**Comment by justinclift** [comment]
Heh Heh Heh :smile:

Yeah, on that note I haven't yet done measurements of the server while larger sized files are sent to DB4S.  Uploads were pretty relaxed (3% of one cpu) during the 2.9GB upload, mostly due to buffer management I'm guessing.  Seems ok for now, so not a priority to look at optimising (yet). :wink:

**Comment by MKleusberg** [comment]
I don't get any flickering even with the 2.9GB file. But the progress bar isn't working properly either. I assume it's because the progress dialog takes ```int``` values and if those are 32bit wide it will overflow for file sizes greater than 2^32/2 Byte, i.e. 2GB. I'll push a fix for that in a second 😄

**Comment by MKleusberg** [comment]
Ok can you test again with the latest commit applied? _In theory_ the progress dialog should work fine now 😉

**Comment by justinclift** [comment]
Sure, gimme 5. :smile:

**Comment by justinclift** [comment]
Yep, this is working smoothly now too.  Nicely shown, no flickering, smooth updates.  Awesome @MKleusberg!

**Comment by MKleusberg** [comment]
Awesome 😄 Thanks for testing!
