### ISSUE TITLE
dbhub: Push dialog fields should enforce their limits

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1097]
In the DB4S 3.10.0 release the Push dialog doesn't check if the length of the database name field nor commit message.

We should get that fixed. :smile:

* Database name: 256 chars
* Commit message: 1024 chars

**Comment by MKleusberg** [comment]
Should be fixed now :smile:

**Comment by justinclift** [comment]
Excellent @MKleusberg. Verified here. :smile:
