### ISSUE TITLE
Problem Event Name:	APPCRASH

### ISSUE THREAD

**Issue by BenitoPaul** [sqlitebrowser/sqlitebrowser#1098]
Application Name:	AVSDocumentEditor.exe
  Application Version:	4.2.3.302
  Application Timestamp:	58626461
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f83ff
  Exception Code:	c000001d
  Exception Offset:	0000000000095c01
  OS Version:	6.1.7600.2.0.0.256.1

please help me to open AVS doc editor

**Comment by chrisjlocke** [comment]
Hi @BenitoPaul 
Are you sure you've got the right support group?

**Comment by justinclift** [comment]
Yeah, doing a quick search online shows this is probably the correct people to contact: http://support.avs4you.com

@BenitoPaul Are you ok to ping them instead?  We can't really help you, as that's not our software so we don't really know much about it. :smile:

**Comment by justinclift** [comment]
@BenitoPaul You'll probably have a better result by downloading and using [LibreOffice](http://www.libreoffice.org) instead of that AVS program.

Looking at their website, they seem kind of dodgy. 😦
