### ISSUE TITLE
Problems with using entity framework in C#.

### ISSUE THREAD

**Issue by PavelCherniavskyi** [sqlitebrowser/sqlitebrowser#1103]
### Details for the issue

In DB I have a table (let it be Names), in project have DbSet<Name> Names field for that table. When adding row in browser it loads into project fine. But when in project I do:
Names.Add(someName);
DbContext.SaveChanges();
It doesn't show in browser but loads next time in project.
If I add in browser another row it erase everything of what I have added from project and returns those rows what shows in browser only.
Is it bug a bug?

P.S. In a giagnostic tool there are also some errors. Mybe that is connected somehow ![inked _li](https://user-images.githubusercontent.com/29663442/29720277-127bdc10-89c2-11e7-84fe-369076671c47.jpg)

#### I'm opening this issue because:
- [x] DB4S has a bug or another problem
#### I'm using DB4S on:
- [x ] Windows: ( _version: 10 x64 )
#### I'm using DB4S version:
- [x ] 3.10.0
#### I have also:
- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmm, this one I have no clue about personally.  Hopefully one of the other teams members has an idea. :smile:

**Comment by chrisjlocke** [comment]
> When adding row in browser it loads into project fine

And this is after clicking, "Write Changes" in DB Browser for SQLite?

Using the entity framework is obviously a layer of complexity which DB4S (DB Browser for SQLite) doesn't know about - so if you're adding in a row using DB4S, is that jhow the entity framework would do it?  Was the database made in DB4S or using Entity Framework?  The __MigrationHistory table is Entity Framework dependant, so its part of that.

DB4S lets yuou look at a 'raw' database, but you have to work within the limits of the entity framework.

**Comment by PavelCherniavskyi** [comment]
> And this is after clicking, "Write Changes" in DB Browser for SQLite?

No. I mead when I add a row in DB4S then write changes and after pulling data from project. It works fine and all tables with data are loaded correct. 
The thing is yes, I made a DB from DB4S and added all items manualy from there. It is very handy. Only after that added it to a project. But problems arise when I tried to write to DB something from a code via entity framework. And the most interesting thing is that SQLite sees that changes so I can read/write everything from a code. But DB4S sees only what was added by itself.
So it seems to me like a bug.

**Comment by justinclift** [comment]
Ahhhh.  If you're in the "Browse Data" tab and you write to the database using the entity framework... I think you need to click the "refresh" button for DB4S to read it again.  Otherwise DB4S is probably using data from cache.

Er... does that help? :smile:

**Comment by chrisjlocke** [comment]
OK.  Can you create a small database (name and age fields?) Create the code to add the record to your database.  Your project can see it.  DB Browser can't see it.  Can you send me that database?  (issue1103 [at] chrisjlocke [dot] co.uk

**Comment by justinclift** [comment]
If it's database data that's ok to be shared, maybe upload it to dbhub.io instead? :smile:

And yeah, I'm definitely trying to get people doing stuff with that so we can work out and fix the bugs there. :)

**Comment by PavelCherniavskyi** [comment]
> Can you create a small database

Ok. Do that tomorrow. Thanks.

**Comment by PavelCherniavskyi** [comment]
You all are welcome:
https://github.com/PavelCherniavskyi/DB-Browser-for-SQLite-issue
As you can see here I added 3 students. Application can read this table well, but in DB Browser students table is empty.
Once you add one more sudent via DB Browser it will erase all previous and will read that student only.

**Comment by PavelCherniavskyi** [comment]
Any news?

**Comment by chrisjlocke** [comment]
I uncommented your 'addStudent' line, ran the code a couple of times, added my own record via DB4S, and ran the program again.  4 records were displayed as it should.

![image](https://user-images.githubusercontent.com/7872218/29819246-bbc157b2-8cb7-11e7-8e59-12730a7bdff5.png)

Can you confirm when you're running rhe program, you're opening the db in the 'debug/bin' directory, and not the 'root' directory.

![image](https://user-images.githubusercontent.com/7872218/29819280-e782abe4-8cb7-11e7-8726-4f41875ddb35.png)

The 'test.sqlite' file (dated 25 Aug) is the 'baseline' database.

In the 'debug/bin' directory is a plethora of extra files (that the raw .exe uses) and one of these is the database.

![image](https://user-images.githubusercontent.com/7872218/29819320-1be46422-8cb8-11e7-8dcf-48f9152f5558.png)

Opening this in DB4S shows all the records, as above.

![image](https://user-images.githubusercontent.com/7872218/29819340-36cd84f8-8cb8-11e7-9f2d-225fc662841d.png)

**Comment by chrisjlocke** [comment]
PS: Useful frameowrk.  I wrote my own 'framework' which uses millions of lines of code to talk to the database.... urgh!  Might look into this one day...

**Comment by PavelCherniavskyi** [comment]
Gosh... I think I'm dumb )))
But why is it dublicate in bin folder?! 
Yes, in that DB everything is correct...

**Comment by chrisjlocke** [comment]
The bin folder (specifically debug in that) is the 'finished' application which you distribute to others.  Thats the application as a 'whole'.  

When you come to release your program, you switch to 'release', and it creates a bin/release directory.

![image](https://user-images.githubusercontent.com/7872218/29823309-2e809890-8cc6-11e7-8d82-aebbffb60013.png)

This version of the .exe doesn't have the debugger hooks in it, so it runs marginally quicker.

The database in the 'root' directory (not the bin/debug directory) is the 'skeleton' database, which gets created if the database in the bin/debug doesn't exist.

Until the bin/debug database is deleted, the 'skeleton' database is never touched again.

Hope that makes sense, but yell back if you need further clarification.

I'll close this issue, but feel free to continue commenting if required - it can do that while closed.

**Comment by PavelCherniavskyi** [comment]
It seems to me wired that visual studio copy database(!!!) to another location to work with that copy...
What if it will be much bigger size? It is just totaly waste of resources. 
But anyway thank you for your time and your patience.
Good luck.
You are doing a great job and usefull product!

**Comment by chrisjlocke** [comment]
> It seems to me wired that visual studio copy database(!!!) to another location to work with that copy...

The 'bin/debug' is the 'root directory' of your finished product.  Thats the directory your application 'sees'.  It cannot 'see' the directory above it, where your source is. It kind of makes sense from a 'production' point of view.  The source directory is your ingredients.  Bake in oven (compile) and the end result is your cake.  Bad cake?  Tweak the ingredients, bake, and eat another cake.  If it touched the 'source', you wouldn't be able to bake another cake.
I'm poor with giving examples, but trust me - it makes sense really!!
