### ISSUE TITLE
Holding CTRL and clicking a row should select/deselect just that row, not select all in between

### ISSUE THREAD

**Issue by Kangaroux** [sqlitebrowser/sqlitebrowser#1104]
### Details for the issue
Holding CTRL should select/deselect one row at a time. Currently it does the exact same thing as holding shift, where it selects everything in between.

CTRL only acting on one thing at a time is a standard found in any spreadsheet program or OS when dealing with folders and files.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [X] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @Kangaroux, yeah, this is a known thing.  No disagreement with you at all.  We just had to pick the best approach we could when writing our cut-n-paste code, and it's still got a ways to go. 😇 

As a though, it might be useful to update to our new release (3.10.0) just from the point of view that there's lots of bug fixes in it.  The selection behaviour of the new release is (from memory) pretty much the same as 3.9.1 though. :wink:

**Comment by mgrojo** [comment]
We have improved the copy/paste code but there are still glitches when you paste non-contiguous selections. I wonder whether it is better to enable it and letting the user assume the glitches or to continue forbidding it to avoid incorrect behaviour.

**Comment by Kangaroux** [comment]
@mgrojo What if when the user performs a copy/paste on a selection of non-contiguous rows a message box appears with a warning? If deleting and modifying columns are not affected by this bug then I think it should be allowed. I imagine those two operations are much more common than copy and pasting

**Comment by mgrojo** [comment]
@Kangaroux, @WiliTest, this has finally received some attention after so long. Now Control+Click will select only the clicked cell, and that selection can be used, except for internal copy-paste, where it these selections are still not understood. Deleting these selected records will work as expected though. Could you give it a try using tomorrow's [nightly build](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds)?
