### ISSUE TITLE
Single quote not escaped when entering password for SQLCipher encrypted db

### ISSUE THREAD

**Issue by R4N** [sqlitebrowser/sqlitebrowser#1105]
### Details for the issue

I was just testing out the new version of DB Browser for SQLite (3.10.0) with SQLCipher 3.4.1 databases and noticed it doesn’t appear to escape single quotes when entering a password.

Here’s an example of a db generated using the SQLCipher cli:
```
sqlite> .open test.db
sqlite> PRAGMA KEY = "test'123";
sqlite> PRAGMA cipher_page_size=1024;
sqlite> CREATE TABLE t1(a,b);
sqlite> INSERT INTO t1(a,b) VALUES('one for the money', 'two for the show');
sqlite> SELECT * FROM t1;
one for the money|two for the show
sqlite> .q
```
When you attempt to open it in DB Browser for SQLite (3.10.0) using the passphrase `test'123` it fails.

### Useful extra information

* This may be a regression as the previous version was able to open SQLCipher dbs with single quotes.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ Windows 10 Enterprise)
- [ ] Linux: ( _distro:_ ___ )
- [ x] Mac OS: ( _version:_ macOS Sierra 10.12.6)
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @R4N.  Yep, that definitely looks like a bug.  @MKleusberg is the right person to look at that, though he's on holidays through to the 30th August.

Pretty sure he'll get this fixed soon after returning. :smile:

**Comment by MKleusberg** [comment]
... and I'm back 😄 

@R4N Thanks for pointing this out! That is indeed a regression that was introduced by some other change. I've just pushed some code to fix it, so with tomorrow's nightly builds (see the main page of our repository on Github for download links) it should work again. Can you give them a test and see if it's working for you?

**Comment by R4N** [comment]
@MKleusberg

Awesome will do 😄 Although it may not be until Tuesday since Monday is the Labor Day Holiday here in the states.  Will post back once i've gotten a chance to test it out and confirm.  Thanks!

**Comment by MKleusberg** [comment]
Cool, thanks 😄 And no worries, just let me know if it's working whenever you have a chance to test it.

**Comment by R4N** [comment]
@MKleusberg @justinclift 

Just tried the latest nightly build (3.10.99) and can confirm it's working as expected for me wrt escaping single quotes in the SQLCipher passphrase.  Nice!

**Comment by MKleusberg** [comment]
Awesome, thanks for testing, @R4N! 😄 We plan to release DB4S 3.10.1 in a week or two with this and some other bug fixes. So hopefully the new version is out before anybody else runs into the same problem :wink:
