### ISSUE TITLE
Removing Downloaded Remote Database Doesn't Redownload If Try To Open

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1111]
### Details for the issue

This is with the latest nightly, so I presume some functionality has changed?
If a remote database is downloaded, but subsequently deleted from the temp folder, double clicking the remote database no longer redownloads the database, but instead opens the 'please open a database' dialog.

Clicking the cog (refresh?) doesn't 'repopulate' the list or make any improvement.

https://screencast-o-matic.com/watch/cbjwQAInyC

On a side issue (oops, naughty... I should get banned for this) the cog has no tooltip.  Its not entirely obvious what it does.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh cool.  Thanks @chrisjlocke, both will need investigating. :smile:

**Comment by MKleusberg** [comment]
Oops! Yeah, before downloading a database I check the list of downloaded databases to find a match. If it has already been downloaded I'll open the local copy. But that didn't check if the file still exists. If it doesn't the open process will fail and show the file open dialog. That should be fixed now 😄 Before trying to open the local copy, we're now checking if it still exists. If not it's redownloaded. Also, I've added a tooltip for the cog button :wink:

**Comment by chrisjlocke** [comment]
Thanks!  (and welcome back!)
Would this be linked in any way to #1096 (database is downloaded remotely, regardless of existance of local version)

**Comment by MKleusberg** [comment]
Hmm, that seems to be a different issue. I'll look at that later 😄

**Comment by chrisjlocke** [comment]
No problem ... just thought I'd mention it whil eI was thinking of it... it looked semi related ... vaguely ... roughly .. etc.

**Comment by justinclift** [comment]
Should this be closed?

**Comment by MKleusberg** [comment]
@chrisjlocke Did you have a chance to test this yet? :smile:

**Comment by MKleusberg** [comment]
I'll just assume this is fixed :innocent:
