### ISSUE TITLE
Size field overflows in the remote panel

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1113]
In DB4S 3.10.0, the size field for database entries in the remote panel overflows for larger sized databases.

For example, with a ~3GB upload:

![db4s_3 10 0_remote_panel_size_overflow](https://user-images.githubusercontent.com/406299/29928123-103b6e5a-8e60-11e7-8be6-311d58e1a8c3.png)

Checking the JSON returned from the server, it seems ok:

```
  {
    "commit_id": "54f336cab6b6e1ec5ccddee2fef0bee2b59c6fb88bca56439f212a915633dc85",
    "last_modified": "31 Aug 17 13:51 BST",
    "licence": "Not specified",
    "name": "backblaze-drive_stats.db",
    "public": false,
    "sha256": "9d80b69260d80dee90c04fb221588eb1e1c4ea63e51fd1e2b5b32d4da0e41104",
    "size": 3065372672,
    "type": "database",
    "url": "https://db4s-beta.dbhub.io:5550/test1/backblaze-drive_stats.db?commit=54f336cab6b6e1ec5ccddee2fef0bee2b59c6fb88bca56439f212a915633dc85"
  },
```

Guessing this will be pretty easy to fix. :smile:

**Comment by MKleusberg** [comment]
Should be fixed 😄

**Comment by justinclift** [comment]
Thanks, yep it's looking good now. :smile:
