### ISSUE TITLE
Deleting a Field Occurs Despite Clicking Cancel

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1116]
### Details for the issue

Wasn't sure if this was a bug (seems a bit dangerous if so!) or 'by design'.

Removing a field via 'Modify Database' and clicking Cancel performs the deletion anyway, with no 'Write Changes' or 'Revert Changes' being available.  
Found this while testing for #1115 .

https://screencast-o-matic.com/watch/cbQVq3Iflu

The screencast deletes an index first, as I thought it was related, but its a red herring.  I created a new table, saved changes, then deleted a field with no 'Write Changes' button.
Skip to 20 seconds in to ignore the index deleting bit.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch.  Yep, that's a bug.  Definitely the kind of thing which could catch people out. 😨

**Comment by MKleusberg** [comment]
It should be fixed now. But maybe you can double check, especially to see if there are any other corner cases left? 😄 By the way, the index deleting bit was actually important. With an unmodified database it works as expected. But still, we might want to include this in a 3.10.1 release or so :wink: (together with #1115 etc).

**Comment by justinclift** [comment]
Yeah, a 3.10.1 in a week or two would probably make sense. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Do you have time to verify this issue is fixed for you? :smile:

**Comment by chrisjlocke** [comment]
Sorry - yes, this now appears fixed.  Can't seem to break it! 🍭

**Comment by justinclift** [comment]
Thanks @chrisjlocke. :smile:
