### ISSUE TITLE
libstdc++.so.6 inside the AppImage is "too new", crashes

### ISSUE THREAD

**Issue by probonopd** [sqlitebrowser/sqlitebrowser#1118]
### Details for the issue

When trying to run the 70046f1 continuous build AppImage on Ubuntu 14.04, getting

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-7009/AppRun)
```

### Useful extra information

This can probably be avoided by not using `ubuntu-toolchain-r-test` and/or other PPAs that pull in "too new" `libstdc++.so.6`.

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 14.04 LTS )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [x] Other: 70046f1 continuous build AppImage

#### I have also:

- [x ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

#### Reference

https://travis-ci.org/AppImage/appimage.github.io/builds/271243066#L708-L710

**Comment by justinclift** [comment]
Any chance of a PR with the needed fix? :smile:

**Comment by probonopd** [comment]
Sorry, don't have the time at the moment. Also I don't know the libstdc++ version requirement for sqlitebrowser. But check out my examples here:

https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt

**Comment by probonopd** [comment]
Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/294507995#L702

**Comment by probonopd** [comment]
@justinclift 

> Any chance of a PR with the needed fix? 😄

What happened to this code?
https://github.com/sqlitebrowser/sqlitebrowser/pull/1061/files

I cannot find it in this repository anymore.

**Comment by justinclift** [comment]
Ahhh, we (I) removed that from our Travis config a while back as it was causing near 100% build failure.

From memory (!), I think it looked suspiciously like the transfer.sh server was either not consistently online or maybe was experiencing some kind of load issues.  eg it was being flaky and I personally just got sick of having builds be reported as failing. :wink:

**Comment by MKleusberg** [comment]
Going to close this issue because it's really old and the issue should be fixed. The AppImage supports Ubuntu 16.04 and newer as support for 14.04 has ended but we're not using any PPAs any more. If you think there's something else I'm missing here, please just reopen the issue :smile:

**Comment by probonopd** [comment]
Thanks. It passes the test now.

**Comment by MKleusberg** [comment]
Awesome!
