### ISSUE TITLE
Force reboot - visual C++ redistributable suspected

### ISSUE THREAD

**Issue by mt025** [sqlitebrowser/sqlitebrowser#1119]
### Details for the issue
I just installed the latest version and got a force reboot. I suspect it was the Visual C++ redistributable  
that caused it, maybe it needs another parameter when the install is called called to ignore reboot?

Thanks

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( 10 Pro version: 1703)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @mt025. Yep, that was exactly the problem, reported already in #1099.  It's fixed in the last few nightly builds, and will be in the upcoming 3.10.1 release (in about a week and a half from now). :smile:

**Comment by justinclift** [comment]
@mt025 Version 3.10.1 was released yesterday, with the fix for this included. :smile:
