### ISSUE TITLE
No Windows Latest Builds (5 Sep)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1120]
### Details for the issue

Did the nightly build process fall over last night?
https://nightlies.sqlitebrowser.org/latest/

There appears to be no Windows builds.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [Argh] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds but then cried when I saw the directory was empty.  Void.  Nothing there.
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, interesting.  I've just been looking at an OSX nightly build problem (hopefully now fixed).

I'll look at the Windows build shortly. Thanks @chrisjlocke. :smile:

**Comment by justinclift** [comment]
Yep, they didn't build.  Not sure why, as the build process on Windows doesn't generate a log file.

After the OSX building finishes, I'll run through the Windows build process manually to see if it was just something temporary (eg network connectivity failure), or something else.

**Comment by justinclift** [comment]
Found it.  The build is failing on Windows with this:

```
C:\git_repos\sqlitebrowser\src\sqlitetypes.cpp(27): error C2027: use of undefined type 'QDataStream'
          C:\dev\Qt\5.7\msvc2013\include\QtCore/qglobal.h(608) : see declaration of 'QDataStream'
```

Seems like it doesn't like this: https://github.com/sqlitebrowser/sqlitebrowser/blob/7db96cdf13ff9131b87a71ebb48517080869b061/src/sqlitetypes.cpp#L25-L29

The timeline of the commit which added it (ea1659e1d09c6d1e3452d3dd76986ac901d637dd) matches up, so that does look like the problem.

For a solution though... lets wait for @MKleusberg. :smile:

@MKleusberg As a data point, both the Windows and OSX build boxes are using Qt 5.7, so it doesn't seem to be something related to that older version.  Maybe an MSVC 2013 related thing instead?

**Comment by chrisjlocke** [comment]
Line 25 has `QDataStream&` while line 31 has `QDataStream &` ... its not that is it?

**Comment by MKleusberg** [comment]
@chrisjlocke No, that's just different formatting of the code which doesn't have any effects. I've still changed it but just to make it more consistent.

My guess is that it's just a missing include which I have just added. No idea why that would be necessary on one platform but not on the other. If the Qt versions are exactly the same that would mean that Qt (or that particular version of Qt) don't behave the same on different platforms - which in turn would be a Qt bug in my opinion, although such a minor one that it's not worth reporting :wink:

@justinclift Can you try compiling again with the last commit applied?

**Comment by justinclift** [comment]
Thanks @MKleusberg. Jumping on the other PC to fire off the build script now.  We should know in a few minutes (hmmm, maybe 10).

**Comment by justinclift** [comment]
@MKleusberg Excellent, that worked.  The build process didn't error out this time, and looks like it'll complete ok.

The overdue nightly builds should be online in ~20 mins. :smile:

**Comment by justinclift** [comment]
Closing this now, as the Windows builds are working again. :smile:
