### ISSUE TITLE
Blocks gnome screen

### ISSUE THREAD

**Issue by darvark** [sqlitebrowser/sqlitebrowser#1125]
### Details for the issue

When I open DB Browser for SQLite on my Fedora, it forbids me to switch to other desktop. No matter how I want to switch desktop to see work on other application that is opened, untill DB Browser for SQLite is open, I can't switch to any other desktop

### Useful extra information

Fedora 26 x86_64, with latest versions of packages,
Gnome 3.24.2
DB Browser fo SQLite installed from Fedora repository in version 3.9.1, qt version 5.7.1, 
sqlite version 3.16.2

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Fedora Workstation)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [x] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
This might be related to #1063 and #934.  Disabling the 'edit database cell' window might help.

**Comment by darvark** [comment]
Hi, Thanks, it's solve problem. So we can close this bug as duplicated.

**Comment by justinclift** [comment]
Ahhh, this is interesting.  My development desktop is running Fedora 25 x64.

This problem doesn't seem to happen on that.  Wonder if it's due to it running the XFCE release instead of Gnome, or if instead it's something to do with the DB4S in the Fedora repository being weird?

I'll try out the Fedora repo version when I switch to that desktop in a bit, and see if the problem shows up.

**Comment by justinclift** [comment]
With Fedora 25 x64's XFCE release, the problem isn't showing up.

It'd be interesting to know which part of Gnome, or the windowing system, is interacting badly with the Edit dialog.  That being said, since it's only in that one dialog it's probably something that wouldn't be too hard to fix.

**Comment by chrisjlocke** [comment]
I guess it's related to the flashing taskbar icon in Windows issue... Same DB4S window. I should get time early this week to investigate this.
