### ISSUE TITLE
Multiple Unique/Primary Key columns issue

### ISSUE THREAD

**Issue by fusionstream** [sqlitebrowser/sqlitebrowser#1126]
On DB4S 3.10.0

There is no provision to add a unique constraint for multiple columns as one (like a multi column primary key), but there is a provision to add the unique constraint to each column.

Additionally, using DB4S, I am still able to save a duplicate row where one or more of the primary key columns is set to null. After adding the UNIQUE constraint from another sqlite db reader, to the database, I am still able to save these duplicate rows.

Additionally, I am unsure why I am still able to save null values to columns that have the NOT NULL set (via primary key)

e.g.

CREATE TABLE `table` (
	`date`	INTEGER,
	`shift`	INTEGER,
	`till`	INTEGER,
	`key`	text,
	`value`	text,
	PRIMARY KEY(`date`,`shift`,`till`,`key`),
	UNIQUE(`date`,`shift`,`till`,`key`)
);

// The UNIQUE constraint was added from a different sqlite reader

**Comment by justinclift** [comment]
Hmmm, sounds like some bug in there. 😦

**Comment by justinclift** [comment]
Ahhh, this sounds relevant:

https://www.sqlite.org/lang_createtable.html#primkeyconst
>  According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. SQLite could be fixed to conform to the standard, but doing so might break legacy applications. Hence, it has been decided to merely document the fact that SQLite allowing NULLs in most PRIMARY KEY columns.

**Comment by justinclift** [comment]
Changed this from "bug" to "enhancement", as having some way to set multi-column unique constraints would be useful. :smile:

**Comment by justinclift** [comment]
> Additionally, using DB4S, I am still able to save a duplicate row where one or more of the primary key columns is set to null.

With that, it's slightly confusing (for me).  Using your example table above, what's an example of data that DB4S allows, but shouldn't? :smile:

**Comment by fusionstream** [comment]
> With that, it's slightly confusing (for me). Using your example table above, what's an example of data that DB4S allows, but shouldn't? 😄

WRT to that table I showed earlier:
INSERT INTO `table` VALUES(20170910, 2, null, 'akey', 'a value');
INSERT INTO `table` VALUES(20170910, 2, null, 'akey', 'a value');

You can run the query twice

**Comment by fusionstream** [comment]
INSERT INTO `table` VALUES(20170910, 2, 1, 'akey', 'a value');
INSERT INTO `table` VALUES(20170910, 2, 1, 'akey', 'a value');

will successfully fail though.

**Comment by fusionstream** [comment]
> Ahhh, this sounds relevant:

>https://www.sqlite.org/lang_createtable.html#primkeyconst

>>According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. SQLite could be fixed to conform to the standard, but doing so might break legacy applications. Hence, it has been decided to merely document the fact that SQLite allowing NULLs in most PRIMARY KEY columns.

Oh no! Thanks for sharing. :D

**Comment by justinclift** [comment]
Ahhh.  With this:

> WRT to that table I showed earlier:
> INSERT INTO table VALUES(20170910, 2, null, 'akey', 'a value');
> INSERT INTO table VALUES(20170910, 2, null, 'akey', 'a value');

That's because `null` values are distinct from each other.  So, a `null` value in one field doesn't conflict with a `null` value in another field.

`null` values in SQL are generally considered to mean "the value here is unknown".  Does that make sense?

Hmmm, I can give a practical example if it'd help?

**Comment by fusionstream** [comment]
It helps a lot. I've always thought that null is just another way of saying a literal '\0'. Thanks for taking the time to explain this.

Should I close this issue and recreate the enhancement part?

**Comment by justinclift** [comment]
No worries.  With recreating the enhancement part, yeah probably a good idea.  It'll help to keep the issue concise. :smile:

Possibly weirdly, I was pretty sure we already have an open request for multi-column constraints, but looking now I'm not finding it.  Meh, hopefully I'm just misremembering. :wink:

**Comment by MKleusberg** [comment]
👍 for opening a new issue for multi-column constraints. If time permits I will try to implement this in time for the 3.11.0 release and the issue would be a good reminder :wink: Also it would be awesome if somebody had an idea for the UI part of this. Our current checkbox approach can't really distinguish between multiple single-column constraints, a single multi-column constraint, and some mixture of both. I was thinking about adding a tab bar: one tab for the table fields which shows exactly what you get now in the dialog and one tab exclusively for editing complex constraints. But maybe somebody else has a better idea :smile:

**Comment by justinclift** [comment]
Heh Heh Heh, well so much for discussing it in a new issue. :wink:

The initial thought that popped into my head was "lets add a button to the create/edit table dialog for `Create Constraint`".  That's about as far as I got though. :smile:

**Comment by chrisjlocke** [comment]
UI suggestion for multiple column indexes.

![image](https://user-images.githubusercontent.com/7872218/30329275-bd9189f0-97c9-11e7-838b-0aa237280a86.png)

eg:

![image](https://user-images.githubusercontent.com/7872218/30329321-dc240fbe-97c9-11e7-8de9-0803255e49fc.png)

Not sure why I've pasted two images when one would have done, but hey.
This is from DbMouse, a SQL Server database manager I use.

**Comment by fusionstream** [comment]
Created new issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/1139

Thanks all

**Comment by fusionstream** [comment]
Dev/Mod/Contributor please do close whichever thread is less relevant. Late to the party.

**Comment by justinclift** [comment]
Thanks @fusionstream. :smile:

@chrisjlocke, are you ok to cut-n-paste your above suggestion there?
