### ISSUE TITLE
auto/manual refresh schema on "database structure" tab

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1128]
sometimes I add tables outside DB4S (while the db is open in DB4S) and consider it rather complicated to see these changes in "database structure" tab. As there is no refresh schema button, I need to go to "browse data" refresh there and return to "database structure" tab. 
I suggest that the schema either gets refreshed on "database structure" tab activation and/or there is button o refresh schema.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:10 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Pressing F5 in the 'Database Structure' tab forces a refresh of the schema view.

**Comment by mglatz** [comment]
thanks :)
