### ISSUE TITLE
Installer reboots computer without warning

### ISSUE THREAD

**Issue by ryanohs** [sqlitebrowser/sqlitebrowser#1129]
I ran the 64 bit installer for version 3.10.0 on Windows 10. At the final screen, it rebooted my computer without any prompt or warning, closing all my active applications.

**Comment by justinclift** [comment]
Thanks @ryanohs, yeah this is a known problem (#1099). 😦 

We'll be releasing a 3.10.1 update in a few days which fixes the issue.  Thanks for taking the time to report this though. :smile:

**Comment by justinclift** [comment]
As a thought, if you need a version right now which doesn't reboot the computer, our nightly builds have the fix for it in them:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
@ryanohs Version 3.10.1 was released yesterday, with the fix for this included. :smile:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1
