### ISSUE TITLE
Database Structure - lines too long

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#113]
Bug reported via private email:

```
I have a small issue. On the screen “Database Structure” it’s great to see the
Schema but I cannot see the whole line as it is too long. Unfortunately, it’s not
possible to scroll or copy. It would be great if you could add one or both
functionalities to be able to see the whole line.
```

![noscrollingindatabasestructureview](https://cloud.githubusercontent.com/assets/406299/4398404/476bf8ac-4455-11e4-91c5-8650775545c4.png)

**Comment by MKleusberg** [comment]
Closing this issue as it is quite old and we have a fix applied some time ago.

**Comment by glawrence** [comment]
I just tried a recently nightly and I get a horizontal scroll bar and a hint, so looks good to me and correctly closed.

**Comment by justinclift** [comment]
Thanks for testing this @glawrence. :smile:
