### ISSUE TITLE
Typing in 'Table' textbox Generates 'PRAGMA foreign_keys' SQL

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1130]
### Details for the issue

More of a query than an issue, but mentinoing it in case it is an issue .... ;)
Every time a key is pressed in the 'Table' textbox of the 'Edit Table Definition' window, a log entry of 'PRAGMA foreign_keys' is logged.  Just checking this is 'by design'.... 

![image](https://user-images.githubusercontent.com/7872218/30326886-f1c83712-97c1-11e7-822f-eaa46024b1ae.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Sounds more like a bug. :smile:

**Comment by chrisjlocke** [comment]
I can never tell these days! ;)

**Comment by MKleusberg** [comment]
Heh heh, it's definitely more on the bug side of the the bug-feature continuum :wink: It should be fixed by the commit which I have just pushed. Are you ok to double check, @chrisjlocke?

**Comment by chrisjlocke** [comment]
Confirmed working.  \o/

**Comment by MKleusberg** [comment]
Yay 👍
