### ISSUE TITLE
Moving Table To Different Schema and Back Again Causes Crash

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1131]
### Details for the issue

If a table from an attached database is moved to a different schema, it cannot be moved back to its original schema again otherwise DB4S crashes.
Guess it makes sense (maybe...) as I'm moving it back to where it came from, but there isn't anything there for it to slot into?  No idea... just waffling.... 

https://screencast-o-matic.com/watch/cbQlIVIIsF

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [x] Other: _Nightly from 12 Sept__

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Definitely a bug.  At a guess, something which should have been pointed to the new location hasn't been, and gets confused.  Good catch @chrisjlocke. :smile:

**Comment by MKleusberg** [comment]
Awesome, thanks for the screen recording. That actually helped a lot :smile: I think the issue is fixed now. Can you check the next nightly, @chrisjlocke? :smile:

**Comment by chrisjlocke** [comment]
Thanks ... will try tomorrow, or it might be Monday. Got a vet appointment tomorrow, so depends on how things go at work. :)

**Comment by chrisjlocke** [comment]
Excellent, thanks @MKleusberg !  Another issue squished.

**Comment by MKleusberg** [comment]
Awesome 😄 Thanks for testing - and for finding this issue :wink:
