### ISSUE TITLE
Attached Database Doesn't Attach If It Doesn't Contain Tables

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1132]
### Details for the issue

Addmittedly an odd case, but I thought I'd report it.
I'd attached two databases, and moved one table from one database to the other database.  Worked fine.  Saved both.  This meant database 1 was now empty, as its tables had been moved.
Closing the databases and trying to attach the now empty database didn't work.  DB4S asked what I'd want to call the attached database*, but it didn't appear in the 'Database Schema' tree.  Additionally, if I clicked on 'Create Table', it only listed 'main' and 'temp' for a schema - the attached database didn't attach.
If it has to fail (no tables, indices, etc) then a message informing the user would be handy, with maybe (now I'm going too far....) an option to open that database instead (maybe in a different copy of DB4S?) so the attach could then be retried?

\* As an additional issue/suggestion, would DB4S be able to pre-populate the 'Enter a name for the database' textbox with the filename of the database you just attached (sans extension).  

If a name isn't given for an attached database, DB4S assumes Cancel has been clicked, rather than inform the user that they can't enter nothing.  Again, some warning might be handy. (or disable the OK box if the textbox is empty)

Sorry for multiple issues per issue (if that makes sense...) but I didn't want to stuff up the issues screen with related issues...

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99 (nightly from 12 Sep)
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Another good catch @chrisjlocke. :smile:

The prepopulation thing is a good idea too.  Should be super simple to get that done.

**Comment by MKleusberg** [comment]
Thanks, @chrisjlocke! These are all good ideas :smiley:

I've just pushed a number of commits which should fix all problems mentioned in this issue: attaching empty databases should work fine now, the attach name dialog is now prepopulated, and an empty database name is not longer the same as clicking the cancel button.

SQLite is weird enough to allow empty names for attached database, so for now we allow it too even though it just doesn't look like a good idea to do that (but I'm sure, like it's always the case, there's somebody somewhere out there who actually uses this 'feature').

**Comment by chrisjlocke** [comment]
✔Attaching blank databases
✔Suggest schema name
✔Attaching database with no name

♫ Another one bites the dust.... ♫

**Comment by chrisjlocke** [comment]
❗ If you attach a database with a blank name, you cannot use it in SQL queries.  Well, you can but I don't know how.

So attaching a database with no name gives the 'users' table a '.' prefix.

![image](https://user-images.githubusercontent.com/7872218/31272436-dc203850-aa82-11e7-99e8-9d5b7a31a07a.png)

How is this used in the SQL window?

![image](https://user-images.githubusercontent.com/7872218/31272453-e8cd46ba-aa82-11e7-9d94-85c9622071df.png)
![image](https://user-images.githubusercontent.com/7872218/31272508-1e3f2dae-aa83-11e7-89ec-550c43f487b5.png)


I've tried ".users", \`.users\` and '.users'.

**Comment by MKleusberg** [comment]
Try ```""."users"``` :smile:

**Comment by MKleusberg** [comment]
And yeah this is just stupid but as far as I remember SQLite allows empty table names and empty field names too. So this could execute just fine:
```sql
SELECT "" FROM ""."" WHERE ""="";
```

**Comment by chrisjlocke** [comment]
> Try ""."users"

But thats nuts!  😕 Wow.  Thanks for pointing it out though!

**Comment by MKleusberg** [comment]
It makes sense insofar as your schema name is empty-string and "" represents an empty string but yeah... I agree.

**Comment by chrisjlocke** [comment]
Aah, that actually makes sense now you've explained it like that.  I was assuming the . was 'part' of the name.  So "{schema}"."{table name}" - *penny drops*.

**Comment by MKleusberg** [comment]
Ahh, I see what you were trying 😄 And yes, the dot it just a separator between schema and table name 😄

**Comment by chrisjlocke** [comment]
Me for the rest of the day:

![image](https://user-images.githubusercontent.com/7872218/31274325-5c644ea0-aa8a-11e7-8430-1196dfd1a8f6.png)
