### ISSUE TITLE
Modifying Attached Table Twice Returns Error

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1133]
### Details for the issue

OK, another "but this is never going to happen in real life!!" case, but thought I'd mention it....
If you attach a database twice using different names* (who would do that?) and try to amend one of the tables in one of the attached databases, DB4S can't save the changes.

![image](https://user-images.githubusercontent.com/7872218/30329715-02457394-97cb-11e7-945e-16baf9f4feb9.png)

I guess you can't prevent it, but didn't know if the error could be 'sugared' somewhat for the user, so they had an inkling that they couldn't do what they're trying to do.
 

\* For the avoidance of doubt, this was my schema.

![image](https://user-images.githubusercontent.com/7872218/30329893-9457d01a-97cb-11e7-8062-676a80e91f24.png)

a, b, and c are all the same attached database - just different names.  The 'main' database is a different database (so I'm not attaching itself, if that makes sense...)
 
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99 (nightly from 12 Sep)
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
It's probably preventable by keeping track of the path names to attached databases, and having some kind of special handling (generate an error?) when a subsequent attach attempts to use the same one.

**Comment by chrisjlocke** [comment]
I can kind of see where you'd want to attach a database twice (rare occassion) but the chances of you then wanting to amend that database are even rarer! ;)

**Comment by MKleusberg** [comment]
Yeah, I can't come up with any reasonable way to make this work either. So I have just added some code now which forbids attaching the same database twice. It's definitely better to just prevent the entire issue this way. Are you ok to double check, @chrisjlocke? Sorry for all the testing I ask for today :wink:

**Comment by chrisjlocke** [comment]
Using the latest nightly allowed me to attach the same database twice?
The date of the build was 06-Oct-2017 03:46.  Am I too early?

**Comment by MKleusberg** [comment]
Hmm... It should work with that build. I hope it's not a Windows/Linux thing 😦 Can you attach the database twice, then go to the Execute SQL tab and run
```
PRAGMA database_list;
```
and copy the results in here?

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/31273673-96832622-aa87-11e7-9890-f7ab6d312e1d.png)

**Comment by MKleusberg** [comment]
Hmm, that doesn't help as much as I would have wanted 😆 I do have an idea though...

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/31274182-c6bc5230-aa89-11e7-99ba-02e236bb727c.png)

**Comment by MKleusberg** [comment]
Where did you find this picture of me?!

I've just pushed a commit which (hopefully) makes the path and file name comparison case-independent on Windows. Maybe this already fixes your issue, so it's worth testing it again tomorrow. And if it doesn't fix your issue the commit is still fixing some bug at least :smile:

**Comment by MKleusberg** [comment]
Any update here, @chrisjlocke ? :smile:

**Comment by chrisjlocke** [comment]
Sorry - missed this one.

Yes, this has now been 'locked down' so the original error can't occur.

![image](https://user-images.githubusercontent.com/7872218/32145323-6cab902a-bcbe-11e7-9d64-d5897dd82fb0.png)

Thanks!

**Comment by MKleusberg** [comment]
Awesome, thanks for confirming :smile:
