### ISSUE TITLE
When Pushing a Database, If Pre-entered Database Name Is Changed, Click When OK Clicked Is Ignored

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1136]
### Details for the issue

When you enter an invalid database name to push to dbhub.io, DB4S tries to identify the branch, but fails due to the invalid URL.  

![image](https://user-images.githubusercontent.com/7872218/30368834-5301c5ae-986a-11e7-9e1d-6a05f10bcc77.png)

The OK button isn't cancelled, so the user can continue.  Obviously this doesn't work, but still throws up 'a weird error' (from the users perspective)

![image](https://user-images.githubusercontent.com/7872218/30369022-f9421d74-986a-11e7-8b55-4567934f1107.png)

The same is with the branch name - this currently allows non-URL friendly characters, resulting in the above 'Ow - what are you DOING?!!!' error.

![image](https://user-images.githubusercontent.com/7872218/30369131-57f284a8-986b-11e7-844d-c2deab27e2a8.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a tweak and a cuddle
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.Nightly
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, from the server side that "Internal Server Error" should probably be looked at.  That *generally* means the request is getting further along in the system than it should.  Though it's also fairly likely it's just returning a generic error instead of something more appropriate to whatever's happening.  I'll check on the server side in a bit, just to make sure it's all ok there.

**Comment by justinclift** [comment]
> DB4S needs a tweak and a cuddle

Like this? https://www.youtube.com/watch?v=9oiEzmgA5Ek :smile:

**Comment by justinclift** [comment]
Looked into this on the server side.  The invalid values were being caught in the correct place (initial validation checks) server side, but the returned error code was 500 ("Internal server error") instead of 400 ("Bad request").  That part's now fixed in the server side code, and is running on the db4s-beta server.

We'll still need to figure out some way to check the fields in DB4S before sending them to the server.

Maybe have DB4S run the same regular expression checks that the server side does?

* https://github.com/sqlitebrowser/dbhub.io/blob/7bbfa760221e21ed6f66d82d7e602bdbfb5fe4f9/common/validate.go#L12-L21

**Comment by MKleusberg** [comment]
Thanks, @chrisjlocke, good point :smile: I've just added the regular expressions to the code. Can you maybe do a quick check if I missed anything?

**Comment by chrisjlocke** [comment]
If you enter ## in the 'database name' and click to 'Commit message', an error is thrown up (first image in the orignal post).  
From a newbie users point of view, this isn't indicative that the name they've given is invalid.  Its obviously obvious, and trial and error would confirm that, but it would be nice to remove that bad attempt.
Also, if I type/change the pre-entered database name and click OK, the click is 'eaten' so it doesn't register.  I can try and screencast that if you require?

**Comment by chrisjlocke** [comment]
Submitted a database and got this 'error'

![image](https://user-images.githubusercontent.com/7872218/31271487-9cdadc16-aa7f-11e7-86c4-9c03e3178bc6.png)

This was using the latest nightly.  Upgrade what?  The application, or remove the remotedbs.db again?

**Comment by MKleusberg** [comment]
I think I found out what's causing the upgrade required bug. I'll open a new issue for it now, then investigate the other issues you've mentioned 😄

**Comment by MKleusberg** [comment]
Thanks, I believe the annoying error message is fixed now as well. I've changed it so you just can't enter invalid characters any longer.

The other issue with the 'eaten' click doesn't seem to happen for me. So yeah, maybe the screen recording would help here :smile:

**Comment by chrisjlocke** [comment]
https://screencast-o-matic.com/watch/cb616VIgZi

Its not entirely obvious, but at 0:06 when the OK button is clicked, the Cancel button gets 'highlighted', and then the OK button is clicked again.
If the database exists (ie, the same name is entered) this does not occur.
If the 'commit message' box gets the focus after entering a name, again this 'click eaten' doesn't occur.

The OK button is again clicked at 0:23 which doesn't register (but the Cancel button gets highlighted)

**Comment by justinclift** [comment]
As a data point, that "OK button not clickable at first" problem happens for me using Fedora 25 too.  I generally get around it by clicking in the branch name field, after which the OK is clickable.

Haven't looked into it more yet, nor tried on OSX.  I'll probably look at it some time this week if it annoys me enough. :smile:

**Comment by chrisjlocke** [comment]
I'll change the issue title, as the original issue has been fixed, but the 'click doesn't work on first click' is quite annoying, so its best this issue is left open.

**Comment by MKleusberg** [comment]
I think this last error could be the one fixed by a0b87688ab86c1e2bd26a6b01d8ec8a4e007e347. Want to give it another try, @chrisjlocke? :smile:

**Comment by justinclift** [comment]
Ahhh, that thing where the OK button in the upload dialog needed a 2nd click.  Haven't seen that happen in ages (mostly on Linux and Win), so forgot about it.  Pretty sure it's fixed. :smile:

**Comment by chrisjlocke** [comment]
Closing due to lack of response.  Nah, not really.
Thanks guys - fixed perfectly.
