### ISSUE TITLE
Error using the cell editor

### ISSUE THREAD

**Issue by Aermec** [sqlitebrowser/sqlitebrowser#1138]
### Details for the issue

If a text field starts with BMS word then the cell editor says 'Image data can't be viewed with the text editor'.
This bug comes out in the latest 3.10 and with 3.9.1 (I didn't try older versions).
I solved, for the moment, with another sqlite editor.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.0
- [ ] 3.10.0-beta*
- [X ] 3.9.1
- [ ] Other: ___

![screenshot](https://user-images.githubusercontent.com/14887677/30380337-a55c0df8-9899-11e7-8cdc-c2b1a80c594a.jpg)

**Comment by justinclift** [comment]
Oh wow, nice catch @Aermec.  Looks like the "data type detector" for the cell is getting caught out by that string. :smile:

This could be a Qt bug in https://doc.qt.io/qt-5/qimagereader.html#canRead.

**Comment by justinclift** [comment]
Beem trying to think of how we could detect this, without it getting too weird.

Instead, I'm thinking the best approach will be for us to file a bug on the Qt project against `QImageReader::canRead()`.  That's returning "true" when it shouldn't be.

I'll file a bug report later on today, after I've switched to the computer with my Qt login info on it. :smile:

**Comment by justinclift** [comment]
Bug report created on the Qt issue tracker: https://bugreports.qt.io/browse/QTBUG-63515

**Comment by justinclift** [comment]
As an update, the Qt developers have a proposed initial patch:

&nbsp; &nbsp; https://codereview.qt-project.org/#/c/207418/1/src/gui/image/qbmphandler.cpp

That might be adjusted before it's accepted into Qt, but this is showing it's at least getting worked on there. :smile:

**Comment by MKleusberg** [comment]
In the meantime I've added some easy code for mitigating this issue from our side.

Can you grab our next nightly build and check if it's working for you as expected using the new version, @Aermec? 😄

**Comment by Aermec** [comment]
Hi,
I just tested the nightly build and it works! Thank you

**Comment by MKleusberg** [comment]
Cool 😄 Thanks for testing, @Aermec!
