### ISSUE TITLE
DB file size limit

### ISSUE THREAD

**Issue by serden84** [sqlitebrowser/sqlitebrowser#114]
Software works very fine with <1GB files, but I have one sqlite, which is 8.6GB and can't open. The question is: is there any limit of sqlite file size? Do you have experience with large files?

**Comment by justinclift** [comment]
@serden84 @renkun-ken Our new release from a few days ago has a 64-bit Windows build.  Would you have a few minutes to try it out with your larger data set files?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.6.0

We're hoping the 64-bit builds work better for large data sets now... :smile:

**Comment by ogloo** [comment]
I run SQLite Version 3.8.10.2 (Qt Version 5.4.1) on windows

I confirm that the software is very slow for files above 200 Mo and crashes when the file exceeds 1 GB.

It would be great if files that do more than 1GB where supported, but at least sqlite should warn the user at start that opening files of more than 1 GB can crash the software.

**Comment by justinclift** [comment]
@ogloo Would you be ok to try our recent (3.7.0) release? The 64-bit version that is.  In theory, it should open larger database files without a problem: :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.7.0

**Comment by ogloo** [comment]
I use the 32 bit version actually but it is the latest one 3.7.0.

**Comment by ogloo** [comment]
And by the way in the SQL shell it would be great to have the number of affeted row when you do an update request, Some thing like:

Query executed successfully: UPDATE table SET field = 's' WHERE field2 = 1 
(took 81ms, 5 rows affected)

**Comment by justinclift** [comment]
The 32 bit version is unlikely to ever load large database files.  To load large ones, you must use the 64 bit version.  And yeah, I understand that might not be easy. :frowning:

**Comment by ogloo** [comment]
So i'll deal with it but thank you for the answers.

**Comment by justinclift** [comment]
Closing thisas we introduced large database support on Windows with version 3.6.0 64-bit.

**Comment by MKleusberg** [comment]
Yes, the 64 bit version sounds like the right approach here.

But let's not forget the 'x rows affected' thing @ogloo mentioned above as this makes a lot of sense (even though it's a bit off topic in this issue :smiley: ). With the latest commit I've just added this feature. Now, it's a bit awkward to say but it'll be available in the next nightly build which - unfortunately - is only available as a 32bit executable...

**Comment by justinclift** [comment]
@MKleusberg Good catch. :smile:

@ogloo Would you be ok to try tomorrow's nightly build, and let us know if the new UPDATE output is working well for you? (download locations are on the front page of this repo if that helps)
