### ISSUE TITLE
Change v3.10.0 installation force reboot?

### ISSUE THREAD

**Issue by tmplinshi** [sqlitebrowser/sqlitebrowser#1141]
### Details for the issue

I just installed v3.10.0 win64, it seems the installation forces to reboot the Windows. My suggestion is to prompt a confirm dialog first.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:10 x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20reboot

**Comment by tmplinshi** [comment]
Sorry, I'm not sure which reason causes the rebooting.. Maybe it was the old version uninstallation.

**Comment by chrisjlocke** [comment]
Just for completeness, yes, v3.10.0 install used a new Visual Studio runtime distribution, which needed an extra command line switch to prevent automatic reboot after installation.  This switch has now been put on the nightlies and future builds, so only the release version of 3.10.0 will do this - hopefully future versions will behave nicer.

Thanks for reporting it though.

**Comment by justinclift** [comment]
@tmplinshi Version 3.10.1 was released yesterday, with the fix for this included. :smile:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1
