### ISSUE TITLE
Extra space added between parentheses when using types such as VARCHAR(10)

### ISSUE THREAD

**Issue by techee** [sqlitebrowser/sqlitebrowser#1142]
### Details for the issue

Steps to reproduce:

1. For instance, create a new table Foo with a single field Bar and manually enter the type VARCHAR(10). The IDE correctly executes the following:

```
CREATE TABLE `Foo` (
	`Bar`	VARCHAR(10)
);
```

2. Now select "Modify table". Notice that now the type is displayed as VARCHAR ( 10 ) - notice the spaces around the number - also the SQL command below contains the spaces.

3. Make some change, e.g. make Bar the primary key and confirm the change. The following SQL is executed:

```
CREATE TABLE `sqlitebrowser_rename_column_new_table` (
	`Bar`	VARCHAR ( 10 ),
	PRIMARY KEY(`Bar`)
);
```

4. Unfortunately the type name is stored together with the spaces and e.g. Delphi then complains that ' 10 ' is not a valid integer.

---

Just a note why using VARCHAR(N) instead of TEXT - the DbGrid component of Delphi needs the N value to correctly set the widths of columns inside the grid. Simple TEXT makes Delphi show "WideMemo" string instead of the actual value. You can check the type mapping of Delphi here:

http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Using_SQLite_with_FireDAC

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @techee, guessing that'll be pretty easy to fix. :smile:

**Comment by techee** [comment]
@justinclift Good to hear!

By the way I've just tried the 3.9.1 release and it works fine so the bug must have been introduced somewhere during the 3.10 release cycle.

**Comment by justinclift** [comment]
Thanks @techee, that's useful info. :smile:

**Comment by techee** [comment]
I've bisected it to this commit:

64fdd78105574838f03fb99c6df6934bd9cd9703

I'm a bit lazy to study the grammar so I'll leave the patch to someone who understands it better.

**Comment by techee** [comment]
... which is probably @MKleusberg ;-)

**Comment by justinclift** [comment]
Ahhh, interesting.  Reading through that commit, this seems to be the line in question:
https://github.com/sqlitebrowser/sqlitebrowser/blob/659f38ebefc8f1d245b30fe279d318c26c2b84a2/src/sqlitetypes.cpp#L938

Do you have time to change the `true` on that line to `false` and see if that fixes the problem for you?

**Comment by justinclift** [comment]
Cool. :smile:

I'll leave this for @MKleusberg to get done, as he'll probably be aware of other potential side effects from changing that to `false`.  Just in case. :wink:

**Comment by MKleusberg** [comment]
That does fix this particular issue but causes new issues for types like ```big int``` or ```varying character```. For these the words would be glued together which isn't right either. I'll have a closer look at this in the next couple of days and think a bit more about it. There should be an easy way to handle both cases correctly :smile:

**Comment by justinclift** [comment]
Hmmm, wonder if we could just do something in `concatTextAST()` like add a post `stext..join` search for `(` in the string, nuking any space character after it, then a search for `)` after that, nuking any space character before that one.

Thinking that'd probably work ok as there shouldn't more than one of `(` and `)` for any field.  Does feel a bit hacky though. :wink:

**Comment by techee** [comment]
Yeah, I think something like that will be necessary. It would just be nicer to go through the tokens inside the AST and insert/not-insert the space based on the token type. Also the space before the '(' should be removed (Delphi didn't complain about this but maybe once the spaces inside the braces are removed, it will check the type before and complain). The concatTextAST() function could be declared as

```
QString concatTextAST(antlr::RefAST t, bool withspace = false, bool type = false)
```

where the `type` parameter would be false for all non-type concatenations. That doesn't seem too hard - despite promising not to do any more work, I'll try to prepare a patch ;-).

**Comment by justinclift** [comment]
Hmmm, maybe a regex could do it all in one go, without needing another parameter for the function?

**Comment by MKleusberg** [comment]
Yep, doing it based on the AST was definitely the right approach :smile:

I assume you've already tested the patch with your database, @techee :wink: So we can just keep this issue closed then :smile:
