### ISSUE TITLE
Confusing error message when libsqlite is missing during "cmake ."

### ISSUE THREAD

**Issue by techee** [sqlitebrowser/sqlitebrowser#1143]
### Details for the issue

When trying to bisect #1142 I didn't quite read what dependencies I need and just tried following the errors that "cmake ." gives me. This eventually lead me to this message:

```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Antlr2: /usr/lib/libantlr.a  
-- Could NOT find QScintilla (missing:  QSCINTILLA_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSQLITE
    linked by target "sqlitebrowser" in directory /home/techet/sqlitebrowser

-- Configuring incomplete, errors occurred!
See also "/home/techet/sqlitebrowser/CMakeFiles/CMakeOutput.log".
```

From this message it seems that what is missing is the QScintilla dependency (which actually isn't true as it's part of the sources) but in fact, the missing dependency was libsqlite in my case. It would save quite a lot of time to the project newcomers if the message was a bit clearer.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [x] Other: current master

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yeah, the first error line `-- Could NOT find QScintilla (missing:  QSCINTILLA_INCLUDE_DIR)` definitely muddies the water to the following lines:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSQLITE
    linked by target "sqlitebrowser" in directory /home/techet/sqlitebrowser
```

I've personally had the exact same thought process re "QScintilla is missing..." when coming back to compiling DB4S after a few weeks doing something else.  Not sure how to fix it though.

There are a couple of different checks for QScintilla being done, and that warning comes from the failr of one of them.  Maybe we need to suppress that message entirely, and have a later conditional warning about missing QScintilla if it's really still missing after they all run...

**Comment by MKleusberg** [comment]
I've just fixed the cmake script to not print a warning if the QScintilla library wasn't found since the warning really isn't useful at all :smile: Should be less confusing now. Are you ok to give the latest version from the master branch a try and see if the confusing warning disappears? :smile:

**Comment by techee** [comment]
@MKleusberg Perfect, it's gone :-)

**Comment by justinclift** [comment]
Excellent.  Thanks @techee. :smile:
