### ISSUE TITLE
Nested Before Delete Trigger

### ISSUE THREAD

**Issue by justindd2017** [sqlitebrowser/sqlitebrowser#1145]
### Details for the issue
Nested  "Before Delete" Triggers do not function properly in the latest release.

### Useful extra information
Trying to implement closure tables, and when I call a delete from a table within a trigger for the same table, I end up getting a foreign key error as though the nested delete did not occur.

The trigger works just fine against the same .db file when using the sqlite3 shell version 3.20.1

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @justindd2017. :smile:

Hadn't personally come across closure tables before, so this looks especially interesting.

Do you have an example database with this problem that we could take a look at?  Doesn't need any data, just pretty much anything that causes this reported problem so we can dig into it. :smile:

If you do, could you upload it to https://dbhub.io? :smile:

**Comment by chrisjlocke** [comment]
No, never used them before either.  Interesting.
https://coderwall.com/p/lixing/closure-tables-for-browsing-trees-in-sql

This gives a rudimentary example, so I'll try uploading something later, if @justindd2017 doesn't beat me to it.... ;)

**Comment by justindd2017** [comment]
I dont have access to dbhub from my location due to a firewall but here is
the sql for the schema.

**Comment by chrisjlocke** [comment]
Unfortunately file attachments aren't saved on gitHub (its a bit of a git....)
Can you post the text?

**Comment by justindd2017** [comment]
Sure thing:

BEGIN TRANSACTION;
DROP TABLE IF EXISTS `objects_closure`;
CREATE TABLE IF NOT EXISTS `objects_closure` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Parent` INTEGER NOT NULL,
`Child` INTEGER NOT NULL,
`Depth` INTEGER NOT NULL,
FOREIGN KEY(`Parent`) REFERENCES `objects`(`ID`),
FOREIGN KEY(`Child`) REFERENCES `objects`(`ID`)
);
DROP TABLE IF EXISTS `objects`;
CREATE TABLE IF NOT EXISTS `objects` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
`Name` TEXT NOT NULL,
`Parent` INTEGER NOT NULL
);
DROP INDEX IF EXISTS `Unique_Parent_Child_Depth_Closure`;
CREATE UNIQUE INDEX IF NOT EXISTS `Unique_Parent_Child_Depth_Closure` ON
`objects_closure` (
`Parent`,
`Child`,
`Depth`
);
DROP INDEX IF EXISTS `Unique_Parent_Child_Closure`;
CREATE UNIQUE INDEX IF NOT EXISTS `Unique_Parent_Child_Closure` ON
`objects_closure` (
`Parent`,
`Child`
);
DROP TRIGGER IF EXISTS `objects_before_delete`;
CREATE TRIGGER objects_before_delete BEFORE DELETE ON objects
begin

DELETE FROM objects
WHERE ID IN
(SELECT child FROM objects_closure
 WHERE parent = OLD.ID and
 child <> OLD.ID ORDER BY depth DESC);
DELETE FROM objects_closure WHERE child = OLD.ID;
DELETE FROM objects_closure WHERE parent = OLD.ID;

end;
DROP TRIGGER IF EXISTS `objects_after_update_parent_null`;
CREATE TRIGGER objects_after_update_parent_null AFTER UPDATE ON objects
WHEN OLD.parent <> New.parent AND New.parent = New.ID
begin
DELETE FROM objects_closure WHERE ID IN
 (SELECT b.ID
 FROM objects_closure AS a
 CROSS JOIN objects_closure AS b
 CROSS JOIN objects_closure AS c
 WHERE a.parent = b.parent
 AND c.child = b.child
 AND a.child = OLD.parent
 AND c.parent = OLD.ID);
end;
DROP TRIGGER IF EXISTS `objects_after_update_parent`;
CREATE TRIGGER objects_after_update_parent AFTER UPDATE ON objects
WHEN OLD.parent <> New.parent AND New.parent <> New.ID
begin
DELETE FROM objects_closure WHERE ID IN
 (SELECT b.ID
 FROM objects_closure AS a
 CROSS JOIN objects_closure AS b
 CROSS JOIN objects_closure AS c
 WHERE a.parent = b.parent
 AND c.child = b.child
 AND a.child = OLD.parent
 AND c.parent = OLD.ID
 AND a.child <> c.parent);

 INSERT INTO objects_closure (parent,child,depth)
   SELECT a.parent, b.child, a.depth+b.depth+1
   FROM objects_closure AS a CROSS JOIN objects_closure AS b
   WHERE a.child = NEW.Parent AND b.parent = NEW.ID;
end;
DROP TRIGGER IF EXISTS `objects_after_insert_zero_parent`;
CREATE TRIGGER objects_after_insert_zero_parent
AFTER INSERT ON objects WHEN NEW.parent = 0
BEGIN
UPDATE objects SET parent = NEW.ID
WHERE ID = NEW.ID;
END;
DROP TRIGGER IF EXISTS `objects_after_insert_parent`;
CREATE TRIGGER objects_after_insert_parent AFTER INSERT ON objects
WHEN NEW.parent <> NEW.ID
BEGIN
INSERT INTO objects_closure (parent, child, depth) values (NEW.ID, NEW.ID,
0);
INSERT INTO objects_closure (parent, child, depth)
   SELECT a.parent, b.child, a.depth+b.depth+1
   FROM objects_closure AS a CROSS JOIN objects_closure AS b
   WHERE a.child = NEW.Parent AND b.parent = NEW.ID;
END;
DROP TRIGGER IF EXISTS `objects_after_insert_noparent`;
CREATE TRIGGER objects_after_insert_noparent AFTER INSERT ON objects
WHEN NEW.parent = NEW.ID
BEGIN
INSERT INTO objects_closure (parent, child, depth) values (NEW.ID, NEW.ID,
0);
END;
COMMIT;

**Comment by chrisjlocke** [comment]
Excellent, thanks!

**Comment by justindd2017** [comment]
What I did was make Objects A, B, C with their parent = their id.

Then change C's parent to be B's ID.

Then Delete B, and it deletes C as well (when it works)

**Comment by mgrojo** [comment]
@justindd2017 
> The trigger works just fine against the same .db file when using the sqlite3 shell version 3.20.1

And what's the SQLite version in **Help > About**? This seems a problem in SQLite, not DB Browser.

I don't know which version is linking our new alpha version but maybe is newer than the one of your test and it's solved.

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is not directly related to our code and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time, @justindd2017  :smile:
