### ISSUE TITLE
Windows restart without prompting after uninstall followed by intall

### ISSUE THREAD

**Issue by 2000me** [sqlitebrowser/sqlitebrowser#1146]
### Details for the issue

Uninstalled sqlitebrowser version 3.9.1.
Directly after that installed sqlitebrowser version 3.10.0.
Without prompting Windows 7 restarted immediately.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [x] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues. Used as filter: restart in:title,body is:issue is:open label:bug

**Comment by justinclift** [comment]
Thanks @2000me, yep this is a known problem.  We'll be releasing 3.10.1 later on today, which fixes this and a few other bugs too. :smile:

**Comment by 2000me** [comment]
Thanks @justinclift. I should have used filter "restart in:title,body is:issue label:bug" instead. :joy:

**Comment by justinclift** [comment]
@2000me @BillyGeat Version 3.10.1 was released yesterday, with the fix for this included. :smile:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1
