### ISSUE TITLE
Error while executing .build.sh

### ISSUE THREAD

**Issue by lulzimgashi95** [sqlitebrowser/sqlitebrowser#1151]
Hi there I'm getting this error while trying to execute ./build.sh on mac.
Please anyone can help what to do ?

`jni/../../lib/SRC/VideoAndroid/sqlite3.c:24124:40: error: use of undeclared identifier 'mmap' { "mmap", (sqlite3_syscall_ptr)mmap, 0 }, ^ jni/../../lib/SRC/VideoAndroid/sqlite3.c:24160:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []' for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){ ^~~~~~~~~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:24169:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []' for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){ ^~~~~~~~~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:24196:20: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []' for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){ ^~~~~~~~~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:24213:16: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []' for(i=0; i<ArraySize(aSyscall)-1; i++){ ^~~~~~~~~~~~~~~~~~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:8590:38: note: expanded from macro 'ArraySize' #define ArraySize(X) ((int)(sizeof(X)/sizeof(X[0]))) ^~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:24217:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []' for(i++; i<ArraySize(aSyscall); i++){ ^~~~~~~~~~~~~~~~~~~ jni/../../lib/SRC/VideoAndroid/sqlite3.c:8590:38: note: expanded from macro 'ArraySize' #define ArraySize(X) ((int)(sizeof(X)/sizeof(X[0]))) ^~~ [armeabi-v7a] Compile arm : argsub_es <= gsub_mtx.c [armeabi-v7a] Compile arm : argsub_es2 <= gsub_es2.c [armeabi-v7a] Compile arm : argsub_es2 <= glStateCache2.c [armeabi-v7a] Compile arm : argsub_es2 <= gsub_mtx.c [armeabi-v7a] Compile arm : armulti <= arMultiFreeConfig.c [armeabi-v7a] Compile arm : armulti <= arMultiGetTransMat.c [armeabi-v7a] Compile arm : armulti <= arMultiGetTransMatStereo.c [armeabi-v7a] Compile arm : armulti <= arMultiReadConfigFile.c [armeabi-v7a] Compile arm : eden <= EdenError.c [armeabi-v7a] Compile arm : eden <= EdenGLFont.c [armeabi-v7a] Compile arm : eden <= EdenMath.c [armeabi-v7a] Compile arm : eden <= EdenMessage.c 6 errors generated. make: *** [obj/local/armeabi/objs/arvideo/__/__/lib/SRC/VideoAndroid/sqlite3.o] Error 1 make: *** Waiting for unfinished jobs.... Exiting ndk-build script abnormally terminated.`

**Comment by justinclift** [comment]
@lulzimgashi95 Looking at the error message, it looks like it's something to do with the main SQLite project source code, rather than us (we're a GUI for SQLite).

Probably the best place to ask is the main SQLite users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

The people there are pretty friendly, and would likely have good suggestions. :smile:

**Comment by justinclift** [comment]
Ahhh, I see you're asking the same question in other potentially related projects too.  The old shotgun approach. :smile:

The android-ndk one (where you've asked already) seems like it might be the right project too.  If you don't get a response from that, definitely try the SQLite users mailing list (as above).

**Comment by MKleusberg** [comment]
Hmm, no update here. Should we close this issue?

**Comment by justinclift** [comment]
Good point. :smile:
