### ISSUE TITLE
Double-clicking a database in Visual Studio opens DB Browser for SQLite twice

### ISSUE THREAD

**Issue by UweKeim** [sqlitebrowser/sqlitebrowser#1152]
Since the beginning of using your awesome tool (about a year ago), I experience the following behaviour:

> When double-clicking a .DB file in Visual Studio 2017 Community Edition, DB Browser for SQLite is opened twice, with both instances having the double-clicked database loaded.

E.g.:

![image](https://user-images.githubusercontent.com/415439/30899001-52bf1a8e-a35e-11e7-9461-c4b33c931954.png)

In the above image, the behaviour occurs when e.g. double-clicking the "shop-local.db".

My environment is a 64-bit Windows 10 German.

I'm totally confused whether this is an issue on Visual Studio's side or DB Browser for SQLite or if this is even intended to behave like this.

**My question:**

How to open only one instance of DB Browser for SQLite when double-clicking a .DB file in Visual Studio?

**Comment by chrisjlocke** [comment]
When double clicking the file directly in Windows Explorer, how many copies of DB4S open?

**Comment by UweKeim** [comment]
Thanks, @chrisjlocke. Only one is opened when I double-click the .DB file in Windows File Explorer.

I'm likely to blame this on Visual Studio; I just do not have a clue how to solve.

**Comment by chrisjlocke** [comment]
If you add a.txt file to your project, which I presume opens in Notepad, does that only open once?

**Comment by UweKeim** [comment]
A .txt file is opened inside Visual Studio.

I've tried it with an Excel file (.xlsx). 

When double-clicking .xlsx inside Visual Studio, it is correctly opened only once.

**Comment by justinclift** [comment]
Hmmm, what happens when clicking on some other file extension that should also open DB4S?

For example, say ".sqlite3"?  Kind of guessing in the dark here :smile:, but thinking it might be useful to try that out even if it means creating some kind of file association.  Just from the point of view of seeing what happens, and if there's any difference in behaviour.  eg one or two copies being opened.

**Comment by UweKeim** [comment]
Funny thing: .sqlite3 files open correctly.

Maybe Visual Studio treats .db files differently for whatever kind of reason.

**Comment by justinclift** [comment]
Yeah, there's definitely something unexpected happening with the VS side of things then.

Depending on how much effort you want to put into investigating this, two possibilities spring to mind. :smile:

1. While doing a search for some VS docs related to this, this showed up:
  * https://msdn.microsoft.com/en-us/library/4k7w5e5s.aspx

It's for a previous version of VS (I couldn't find the 2017 equivalent easily), but it does mention VS can be told to handle specific file extensions in various ways.

It might be useful to look at that section in your VS install, and see if it has anything defined for `.db`.  If it does... try different settings and see what happens. :smile:

2. The second possibility is to investigate what `.db` is set to in the Windows registry.  A good way seems to be using **NirSoft File Types Manager**, as @chrisjlocke wrote about in our file extensions wiki page:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

If none of that works... hmm.. I'd be looking to find out if there's a VS user group or similar to ask next.  Someone there would likely have gained the knowledge over time to muck with it's internals... :smile:

**Comment by UweKeim** [comment]
Thanks, to you all guys. Just for completeness, here is what the File Type Manager entry looks like:

![image](https://user-images.githubusercontent.com/415439/30950207-aad95e88-a41b-11e7-9605-dad66bde2e7e.png)

![image](https://user-images.githubusercontent.com/415439/30950208-aef39858-a41b-11e7-94a1-6325139520c4.png)

Nothing suspicious looking.

**Comment by justinclift** [comment]
Yep, nothing seems weird there.

Ok, next step is probably to look for some VS group on the interwebs, seeing if they have ideas.  Well, unless anyone else here comes up with something.  Maybe @karim? :smile:

**Comment by chrisjlocke** [comment]
Microsoft's [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) might be able to help.  Its a bit like looking for a cotton bud in a field of mushrooms, but if you monitor just the registry access (I'm sure its a wacky registry setting?) it might point to something.

**Comment by chrisjlocke** [comment]
I know this isn't resolved, but as its not something we can address directly in DB4S, I'll close this, but will continue to look into.  Thankfully while an annoyance that two copies opens, at least its a trivial 'workaround' to close one instance.

**Comment by UweKeim** [comment]
Thank you, Chris!

**Comment by chrisjlocke** [comment]
Sorry its not a fantastic answer.  Visual Studio is a bloaty pile of poop, so I'd look at better IDE's 😉 
Have you looked at Blumentals PHP editor?
https://www.rapidphpeditor.com/  Thats highly developed and maintained, with a big community.  Obviously not sure if it'll suit your requirements though....
