### ISSUE TITLE
compile show error: “sqlite3.h”: No such file or directory?

### ISSUE THREAD

**Issue by yeechongyeung** [sqlitebrowser/sqlitebrowser#1153]
### Details for the issue

compile show error: “sqlite3.h”: No such file or directory?
Qt version: Qt 5.7 vs2015 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  It's probably the directory here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/425bfa1e75a2720f53a5ffab2d382d6b8aab861a/CMakeLists.txt#L29

It needs to point to where you have SQLite3 compiled. :smile:

If your path is different, that line should be changed. :smile:

**Comment by justinclift** [comment]
Just to check... are you following the steps here?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Step-8-%E2%80%94-Install-SQLite

**Comment by justinclift** [comment]
Oh... one further thought.  My above answers are only correct if you are trying to compile DB4S itself.  If you are trying to compile something else, those answers aren't going to work. :smile:

Are you trying to compile DB4S?

**Comment by justinclift** [comment]
@yeechongyeung ping?

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by nurp** [comment]
I can't find an OpenSSL installer like in that wiki. All I find is either source or a zip file containing 3 binary files in it. Could you put a link to where you downloaded it maybe? https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Step-4-%E2%80%94-Install-OpenSSL

**Comment by karim** [comment]
@nurp OpenSSL [page](https://wiki.openssl.org/index.php/Binaries) links to pre-compiled binaries. The first [link](https://slproweb.com/products/Win32OpenSSL.html) should get you the installer used in the wiki.
