### ISSUE TITLE
Export to SQL problem : LONGVARCHAR / LONG VARCHAR

### ISSUE THREAD

**Issue by Neustradamus** [sqlitebrowser/sqlitebrowser#1158]
When we export a base to sql, we have in the file:
LONGVARCHAR, it must be LONG VARCHAR

**Comment by justinclift** [comment]
Which version is this happening with? :smile:

It might be related to a changes we did for #1142, which was removing some extra spaces that confused things.  At a guess, we didn't notice the problem with `LONG VARCHAR`.

@MKleusberg @techee Thoughts? :smile:

**Comment by techee** [comment]
Hmm, I can't imagine how it could happen because of #1142 - the patch affected only spaces before/after left and right brace and spaces should still be used for the rest of the type.

**Comment by Neustradamus** [comment]
The last : 3.10.1

**Comment by justinclift** [comment]
Thanks @Neustradamus. :smile:

@techee Eyeballing that code, yeah it sounded kind of similar but doesn't look like it's the culprit. :smile:

**Comment by techee** [comment]
@justinclift Especially when the commit was made after the 3.10.1 release 😉

**Comment by justinclift** [comment]
Doh!  Good point. 😀

**Comment by MKleusberg** [comment]
@Neustradamus Can you provide the schema of the affected table? It doesn't seem to happen with just any table with a ```LONG VARCHAR``` type, so I assume it's some problem in our SQL parser which is triggered by something else in the create table statement.

**Comment by Neustradamus** [comment]
Firefox profiles / places.sqlite exported to SQL

**Comment by MKleusberg** [comment]
Ah ok. I've just checked the file and it seems like that's just how it was created by Firefox. You can get the original CREATE statement by executing this:
```sql
select sql from sqlite_master where name='moz_places';
```
And it returns
```sql
CREATE TABLE moz_places (   id INTEGER PRIMARY KEY, url LONGVARCHAR, title LONGVARCHAR, rev_host LONGVARCHAR, visit_count INTEGER DEFAULT 0, hidden INTEGER DEFAULT 0 NOT NULL, typed INTEGER DEFAULT 0 NOT NULL, favicon_id INTEGER, frecency INTEGER DEFAULT -1 NOT NULL, last_visit_date INTEGER , guid TEXT, foreign_count INTEGER DEFAULT 0 NOT NULL, url_hash INTEGER DEFAULT 0 NOT NULL)
```
I've also tried using the official sqlite3 command line utility and it gives the same results.

So I'm afraid there's not much we can do about it because it's just how the table was originally created by Firefox. Maybe you can search and replace the LONGVARCHAR using a text editor? Or make a copy of your database and edit the field types using DB4S and export afterwards?

**Comment by Neustradamus** [comment]
For you it is not a bug of DB4S? :/

**Comment by chrisjlocke** [comment]
If it's how the table was originally created by Firefox, then the issue isn't with DB4S ... DB4S is just reading the SQL it's been given.
