### ISSUE TITLE
Updated query optimisations

### ISSUE THREAD

**Issue by steronydh** [sqlitebrowser/sqlitebrowser#1161]
When I run an "ANALYZE" query only the sqlite_stat1 table is generated in my database. Please can SQLiteBrowser be compiled with SQLITE_ENABLE_STAT4 so that it can use the latest query optimisations in SQLite?

#### I'm opening this issue because:

- [x] DB4S needs a feature

#### I'm using DB4S on:

- [x] Windows: (10 64-bit)

#### I'm using DB4S version:

- [x] 3.10.1

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @steronydh.  Hadn't really thought about that before, but it makes sense.

Looking at the docs for [SQLITE_ENABLE_STAT4](https://sqlite.org/compile.html#enable_stat4), it seems like it might be pretty easy to get working.  I'll experiment with it a bit, and see if it really is as easy as it sounds to enable. :smile:

**Comment by steronydh** [comment]
Great, thanks.

**Comment by justinclift** [comment]
@steronydh Are you around and still interested in this? :smile:

Asking because this has been added to our Windows nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Looking for some people to test it and verify it's working from their point of view. :smile:

**Comment by justinclift** [comment]
Our nightly (and all future) macOS builds now include it too. :smile:

**Comment by justinclift** [comment]
Just tested this and confirmed it's working in our Win32, Win64, and macOS nightly builds.  It'll be in our 3.11.1 release (should be later today, or tomorrow) too.
