### ISSUE TITLE
Encryption and Unencryption database in android app

### ISSUE THREAD

**Issue by Sirvanalie** [sqlitebrowser/sqlitebrowser#1166]
When click on File> Set Encryption , one window is opening , and we can set password for our database.

Now my question is, How use and open database(unencryption) in android project ? But Encryption  enable when someone want open on Pc or anything.

**Comment by justinclift** [comment]
@Sirvanalie To read info out of the database on Android, you will probably need to use something on Android which can open (encrypted) SQLCipher databases.

The place with information you should investigate is here:

&nbsp; &nbsp; https://discuss.zetetic.net/c/sqlcipher

They're the makers of SQLCipher, which is the encryption we use.  They have stuff available for Android, which **I guess** is probably what you want.

Does that help? :smile:

**Comment by Sirvanalie** [comment]
Thanks @justinclift . Few days ago, I downloaded one project who have a SQLite database .But when click for open it , one message appear say enter **Password**. But app use this database for fetching data and display for quiz game. Because of this , I want ask this question . Thanks a lot. I search about SQLCipher .

**Comment by chrisjlocke** [comment]
It might be worth opening the database in a text or hex editor?  DB4S will ask for a password if it finds a file it can't read - it might not necessarily be a SQLite database.
Just beacuse a file has .db or .database, it might not be a SQLite database.  If you want to upload the file or email it to me heres-a-file@chrisjlocke.co.uk.

**Comment by justinclift** [comment]
@Sirvanalie Ahhh.  In that case the suggestion by @chrisjlocke is worth looking into as well.  When our application is told to open a database, it first tries to read it using SQLite.  If that fails (eg it's not a SQLite database) then we automatically assume it's an encrypted one + ask for a password.

It could definitely be the case that the quiz game is storing the info in some other way, instead of SQLite (and not SQLCipher either).  That would also lead to the behaviour of our application asking for a password when it fails to read the database file as SQLite.

Not sure if that helps you much, but at least understanding the process should get you closer to solving it. :smile:

**Comment by juservi** [comment]
Hello
I have installed DB Browser for SQLite and I closed my project. When I opened it again the program asked me a keyword, but I didn´t creat anything. How can I use again my program? Please help me!

**Comment by chrisjlocke** [comment]
@juservi - DB4S is asking for a password (not a keyword) as it can't properly identify the file as being an SQLite database.  It therefore assumes its an encrypted database file.
If you're opening a (what you believe is a) non-encrypted file and DB4S is asking for a password, then you need to try opening the database in a text or hex editor to confirm the file is in fact a database, and not a database backup (for example, a sequence of SQL instructions)

If the database isn't sensitive information, you can try emailing it to me at whats-this-file [at] chrisjlocke.co.uk and I can have a look.

**Comment by Sirvanalie** [comment]
@chrisjlocke  Thanks dear for response me. After @justinclift reply, I search a lot about Encryption and Unencryption, AND result is : with use SQLCipher , developers can Encryption and Unencryption their databases, of course use SQLCipher  have bad effect on app like decrease performance app and increase apk size. Also with use NDK or native code. Now I am worrying about my database , because I spend more time to add data on database , and when anyone decompile my app, anyone can reach to this database , AND I don't want this :(.

**Comment by justinclift** [comment]
Yeah.  There isn't a perfect solution.  It's more about choose the best solution for a situation.  And they all have good & bad pieces.

**Comment by justinclift** [comment]
@juservi Did Chris' response help? :smile:

**Comment by chrisjlocke** [comment]
@juservi - Are you still having problems?

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦

**Comment by Sirvanalie** [comment]
H repliey in past, I still want to prevent access to database, but no way for this goal. Please closing this issue.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by chrisjlocke** [comment]
> but no way for this goal

Well, there is.  You mention slow app response, but is it really that much slower?  A slight decrease in performance is 'acceptable' if the database cannot be accessed.

**Comment by Sirvanalie** [comment]
But increase app amount and decrease performance app. If you can set password for database and when user lunch app, database is opened with some process behind loading app. This is so great , but If this is a dream !!! , must be say " **Never mind bro** " .  👍

**Comment by chrisjlocke** [comment]
I must admit, I'm not fully understanding your comment.  The database is encrypted, so no-one can open it without a password.  Your app provides this password, so the database is opened.  
Are you grouping your database write operations in transactions?  Opening an encrypted database is slower than opening a normal database, so performing separate queries using multiple connections is a bad idea.

**Comment by Sirvanalie** [comment]
Thanks.
