### ISSUE TITLE
Nightly Build Fails To Start (Windows)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1169]
### Details for the issue

The latest nightly isn't starting on my Win 10 x64 machine.  Its not failing with an error, but the DB4S window isn't showing.  The nightly from 6 Oct is fine.  Will download other ones to nail it down further, but thought I'd mention it.
Haven't tried it on another machine yet either, so will do these things ... but just wanted to potentially highlight an issue first.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S needs to start up
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _10_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99 (Nightly from 12 Oct)
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
https://screencast-o-matic.com/watch/cb6lXGIGyc

**Comment by chrisjlocke** [comment]
Its only the 12th that fails.  All before that work successfully.

**Comment by chrisjlocke** [comment]
```Faulting application name: DB Browser for SQLite.exe, version: 0.0.0.0, time stamp: 0x59dee31f
Faulting module name: Qt5Core.dll, version: 5.7.1.0, time stamp: 0x583ffd95
Exception code: 0xc0000005
Fault offset: 0x00025fdf
Faulting process ID: 0x2be0
Faulting application start time: 0x01d3435c4ad1a943
Faulting application path: D:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win32\DB Browser for SQLite.exe
Faulting module path: D:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win32\Qt5Core.dll
Report ID: c3e2aa69-5a96-4fde-92f5-12c2fac931a9
Faulting package full name: 
Faulting package-relative application ID: 
```


I have windbg but I'm a bit like a monkey with a hammer ... I have no idea what I'm doing.  It gave this info:
```
ModLoad: 00007fff`0d3d0000 00007fff`0d3fa000   C:\WINDOWS\system32\dwmapi.dll
(2d30.2a54): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for d:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win64\Qt5Core.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for d:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win64\Qt5Core.dll - 
*** WARNING: Unable to verify checksum for d:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win64\DB Browser for SQLite.exe
*** ERROR: Module load completed but symbols could not be loaded for d:\downloads\applications\DB Browser for SQLite\2017 Q4\DB Browser for SQLite-2017-10-12-win64\DB Browser for SQLite.exe
Qt5Core!QBasicMutex::unlockInternal+0x12:
00000000`61f28eb2 f00fc1430c      lock xadd dword ptr [rbx+0Ch],eax ds:00000000`0000000c=????????
```

**Comment by justinclift** [comment]
Ahhh.  Wonder if its the new multi-threading code causing it?

**Comment by justinclift** [comment]
Looking at the git blame for the [unlockInternal call in Qt](https://github.com/qt/qtbase/blame/5.9/src/corelib/thread/qmutex.cpp), it's been around since Qt 5.0 was released.

Was thinking maybe we're calling a function which isn't in Qt 5.7, but nope.  It's definitely there.

**Comment by MKleusberg** [comment]
@justinclift Can you maybe apply this patch to the current code in master and make a new Windows build? That's just a first guess from looking at this though :smile:

```diff
diff --git a/src/sqlitetablemodel.cpp b/src/sqlitetablemodel.cpp
index 54c8143..189395f 100644
--- a/src/sqlitetablemodel.cpp
+++ b/src/sqlitetablemodel.cpp
@@ -25,7 +25,6 @@ SqliteTableModel::SqliteTableModel(DBBrowserDB& db, QObject* parent, size_t chun
 
 void SqliteTableModel::reset()
 {
-    m_mutexDataCache.unlock();
     m_futureFetch.cancel();
     m_futureFetch.waitForFinished();
 ```

If that doesn't work I'll investigate further.

**Comment by justinclift** [comment]
Thanks @MKleusberg, I'll kick off a build with that in a sec. :smile:

**Comment by chrisjlocke** [comment]
*dances a little dance while he waits...*

;)

**Comment by justinclift** [comment]
Ok, it's running now.  It's just building the SQLite versions (not SQLCipher) to save time.  They should appear in the `-onceoffs` directories in ~15 minutes or so from now:

* https://nightlies.sqlitebrowser.org/win32-onceoffs/
* https://nightlies.sqlitebrowser.org/win64-onceoffs/

**Comment by justinclift** [comment]
They're uploading now.  Just tried out the 64-bit one on the Win VM while it's uploading, and no crash occurred.  If they work for @chrisjlocke too, then this is probably solved. :smile:

**Comment by chrisjlocke** [comment]
Thanks @MKleusberg and @justinclift - that version works fine. 👍

**Comment by MKleusberg** [comment]
Awesome 😄 I'm glad it was that easy to solve :wink:

**Comment by justinclift** [comment]
Excellent.  Good first guess there @MKleusberg. 😁
