### ISSUE TITLE
Unable to view hindi texts

### ISSUE THREAD

**Issue by badarshadab** [sqlitebrowser/sqlitebrowser#1183]
### Details for the issue
I have a database file created on my colleague's system.when I am trying to open that file in my DB browser for sqlite database, hindi texts in it are not visible

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [x] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Is the database file public?  If so, would you be ok to upload it to [dbhub.io](https://dbhub.io) and include the link here?

That will let us take a look at the problem better. :smile:

**Comment by mgrojo** [comment]
@badarshadab ? Please, check justindlift's comment.

**Comment by justinclift** [comment]
Closing due to lack of response. 😦
