### ISSUE TITLE
Executing select "with recursion" marks database dirty

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#1185]
### Details for the issue

When a select `with recursion` is executed, the database is marked as dirty.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Good point! I've prepared a patch for this which should fix this. It's replacing a wrong assumption by an untested one. If you want to have a look at this, you can check out this comment: https://github.com/sqlitebrowser/sqlitebrowser/pull/1181#issuecomment-338492649

If there are no major concerns with this, we can merge the code in the next couple of days. I'll let you know as soon as this is done :smile:

**Comment by MKleusberg** [comment]
And it's merged :smile: Can you test again using tomorrow's nightly build (hopefully the build works this time :wink:)? It's also worth checking for any other oddities related to this, like what happens when running other statements.

**Comment by pamtbaau** [comment]
I would love to test, but no nightlies again today....

**Comment by justinclift** [comment]
@pamtbaau Just kicked off the nightlies build script manually ~5 mins ago, after @MKleusberg fixed the problem that was breaking it.

The now-very-overdue nighlies should be online in ~40 minutes if you're still wanting to test.  Or just wait for tomorrows ones which should work ok too. :smile:

**Comment by pamtbaau** [comment]
Tested build 3.10.99 (version doesn't get bumped anymore) from 29-Oct-2017 18:09 and a recursive query does not mark the database as dirty. Seems to be fixed.

**Comment by justinclift** [comment]
Fantastic.  Thanks for verifying @pamtbaau. :smile:
