### ISSUE TITLE
Ability to rename tabs in sql panel and preserve names in project file

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#1186]
### Details for the issue

It would be nice to be able to give tabs in the sql panel a descriptive name and preserve these names in the project file.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
This should be included in the next nightly build, too. You can now double click the title of an SQL tab and get a small dialog where you can change the name. The names are included in the project files as well and should be restored when loading a project file. Can you check that as well? :smile:

**Comment by pamtbaau** [comment]
@MKleusberg I have been wanting to test this out the last few days, but I cannot find any nightlies since September 20th... Only nightly builds for OSX are refreshed every night.

**Comment by justinclift** [comment]
Thanks @pamtbaau.  We haven't set up proactively monitoring for build failures yet, so yeah... that generally gets fixed when someone mentions it. 👼 

Just added a potential fix, but haven't tested it yet as I don't have easy access to the Windows build VM right at the moment.  If I don't get around to testing it before tomorrow, then we'll get to find out by checking if there's new Windows nightlies instead. :smile:

**Comment by pamtbaau** [comment]
Still no nightlies for Windows 10/64 ....

**Comment by chrisjlocke** [comment]
> We haven't set up proactively monitoring for build failures yet, so yeah... that generally gets fixed when someone mentions it.

Just slapped together a quick VB program that'll notify me if a nightly is missing.
I'll add into it a size check, as an issue ages ago meant one of the builds suddenly increased in size.

![image](https://user-images.githubusercontent.com/7872218/32090542-d2e67d10-bae7-11e7-8b6e-4497bcf18270.png)

**Comment by pamtbaau** [comment]
Downloaded and tested... It works! Thank you so much for this feature.

**Comment by chrisjlocke** [comment]
Reopening it, as the & character isn't showing in Windows. (put a comment on the line in question)

![image](https://user-images.githubusercontent.com/7872218/32092409-4367221c-baf0-11e7-86b3-a940b6ef2ab7.png)

**Comment by MKleusberg** [comment]
@pamtbaau Thanks again for testing :wink: Glad we could help!

@chrisjlocke Just pushed a fix for that. Can you check on tomorrow's nightly build if it's now working on Windows as expected?

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/32147159-476d5e12-bcda-11e7-953a-5f26e0f7d28d.png)

Working great now.  👍

**Comment by pamtbaau** [comment]
Sorry to be a party pooper... It's not working on Windows 10. I can enter the ampersand in the popup, but it doesn't show on the tab. When showing the popup again, the ampersand shows...

Tested on the latest build 64 bit Windows 10 from 29-Oct-2017 18:09

**Comment by justinclift** [comment]
No worries at all.  This is exactly why we verify stuff manually before believing things are fixed. :smile:

**Comment by chrisjlocke** [comment]
And is that with the latest nightly?  The one with the corrected "&" in the dialog?

Works for me on Win 10.

![image](https://user-images.githubusercontent.com/7872218/32149467-e6290854-bcfc-11e7-959a-7014285d1887.png)

![image](https://user-images.githubusercontent.com/7872218/32149469-f883f7ca-bcfc-11e7-8f77-c52aea30e049.png)

**Comment by pamtbaau** [comment]
A little mindbug on my part... It didn't occur to me that the '&' issue was about keyboard shortcuts and took it for "the & is not showing in the new name" (which it doesn't).

So, new findings:
- The underscores do not appear before hitting Alt-key, but do after (as with Notepad)
- The keyboard shortcut does work with Alt-key
- To use '&' in the name, use  '&&'

**Comment by chrisjlocke** [comment]
> To use '&' in the name, use '&&'

Yes, I'll add this to the Wiki.  As the '&' is used for an accelerator key (not technically a shortcut in the true sense... but who uses proper technical jargon anyway?) then && should be used to 'cancel' it out and display a '&' instead. 

So are you OK closing this now?

**Comment by pamtbaau** [comment]
I'm OK with it. I can name the tabs and as a bonus an accelerator key can be attached to it and '&' can be used in the name... What else could I ask for? :-)

**Comment by chrisjlocke** [comment]
Excellent, thanks.
