### ISSUE TITLE
Browse Data tab: Query re-executed when filter cell receives focus

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#1187]
### Details for the issue

When focus changes in filter cells in the browse tab, the query gets rerun. Not really harmful, but unnecessary and causing screen flicker. Also, when scrolled, scrolling get undone.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Thanks for opening all these issues! As much as I would like to an issue number <200, these are all good observations :wink:

That said, I believe this issue is fixed now. Can you download tomorrow's nightly build and check if it's stopping the re-execution of queries for you? :smile:

**Comment by pamtbaau** [comment]
Tested on 3.10.99 and issue is fixed. Well done and thanks.

**Comment by MKleusberg** [comment]
Thanks for testing :smile:
