### ISSUE TITLE
Feature request: Add an option to filter empty records through the filter GUI (Browse data)

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1189]
Hello everyone,

Please, add an option to Filter empty records through the "Browse data" GUI.

Currently, on Windows 10 - Windows 7 (64bit .exe installer) I can easily filter all empty cells in my tables by writing some simple SQL code.
E.g. 
SELECT *  FROM mytable WHERE columnA = ' '

On the contrary, it looks like this option is not implemented yet as filter through the GUI.
On the "browse data" grid GUI I am able to select NULL and NOT NULL values whereas I am unable to filter empty records in my Sqlite database.
I have read the Wiki short "manual" but this option is not listed in the filter section.

I am testing the 3.10.99 version (on Windows 7 - 10)
QT 5.7.1
Sqltie 3.20.0

Thanks a lot !

**Comment by karim** [comment]
Sounds like a useful addition to DB4S filter. 😄 

Do you have any suggestion about which operator we should use? Something like `=''` maybe?

In the meantime, you can try sorting the column (by clicking on its name) and it should show you all the empty fields together. Not ideal I know but it works. :)

**Comment by SilvioGrosso** [comment]
Hello !
> Do you have any suggestion about which operator we should use? Something like ='' maybe?
Perhaps:=' ' 
--to select *empty* records
together with the option:
<>' '--the other way around (select all records which are *not empty*)
> In the meantime, you can try sorting the column (by clicking on its name) and it should show you all the empty fields together. Not ideal I know but it works. :)
Yep. It works fine :-)


 

    Il Martedì 24 Ottobre 2017 12:09, Karim ElDeeb <notifications@github.com> ha scritto:
 

 Sounds like a useful addition to DB4S filter. 😄 Do you have any suggestion about which operator we should use? Something like ='' maybe?In the meantime, you can try sorting the column (by clicking on its name) and it should show you all the empty fields together. Not ideal I know but it works. :)—

**Comment by SilvioGrosso** [comment]
Hello everyone !
You made my day :-)

Just tested on Windows 10 (64 bit) with today's daily build.
Everything is filtered as expected.

I have uploaded a video on YouTube to show this new feature (I hope you don't mind):
https://www.youtube.com/watch?v=UtP0Qg0wNpw

Many thanks indeed !

**Comment by MKleusberg** [comment]
Awesome, I'm glad I could help :smile: Thanks a lot for testing!
