### ISSUE TITLE
Execute SQL might support allowing users to drag and drop from DBSchema so they don't have to type the names of variables.

### ISSUE THREAD

**Issue by rajivnarayana** [sqlitebrowser/sqlitebrowser#119]

**Comment by mgrojo** [comment]
In fact you can click on the Name column press Ctrl+C and then paste in the SQL editor, but drag and drop should also work. I haven't found in a quick review where it can be implemented :smile:

**Comment by mgrojo** [comment]
@rajivnarayana We have implemented this feature. If you'd like to try it, you can install one of our nightly builds: https://nightlies.sqlitebrowser.org/latest

**Comment by justinclift** [comment]
@rajivnarayana If you're still interested in this, please do.  It'd really help. :smile:

**Comment by mgrojo** [comment]
@rajivnarayana I'll close this, but you can still comment on the report if you'd like to.
