### ISSUE TITLE
No Windows Latest Builds (24 Oct)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1193]
### Details for the issue

There doesn't seem to be any nightly builds since 20 Oct.

![image](https://user-images.githubusercontent.com/7872218/31930121-7e7fc3ba-b896-11e7-8055-7ff1653eff8c.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @chrisjlocke.  Heh Heh Heh.  One day we'll get around to writing up that monitoring/alerting script to proactively let us know. :smile:

As a wild-arse-guess, it's probably the same compile failure as reported in #1192.  Experimenting with the suggested fix for that now...

**Comment by justinclift** [comment]
Just added the suggested fix from #1192.  Haven't tested it on Windows (build VM not easily available atm), but it doesn't negatively affect compiling on Linux so shouldn't hurt anything. :smile:

**Comment by chrisjlocke** [comment]
Unfortunately that didn't work - still no Windows builds today.

**Comment by justinclift** [comment]
Damn.  I'll have to log into the VM remotely and manually run through it to see what's up.

**Comment by MKleusberg** [comment]
Yeah, it's unlikely the problem is in the CSV parser because the code hasn't changed around 20 Oct. But with a build log I think the problem should be very easy to fix. It's probably just another missing include for Windows.

**Comment by justinclift** [comment]
No worries.  I'm logging into the build VM now to figure out the problem. :smile:

**Comment by justinclift** [comment]
k, the error message in the build log:

```
  ...
  PlotDock.cpp
c:\git_repos\sqlitebrowser\src\MainWindow.h(143): error C2059: syntax error : '('
c:\git_repos\sqlitebrowser\src\MainWindow.h(143): error C3805: '(': unexpected token, expected either '}' or a ','
c:\git_repos\sqlitebrowser\src\MainWindow.h(146): error C2143: syntax error : missing ')' before ';'
c:\git_repos\sqlitebrowser\src\MainWindow.h(146): error C2238: unexpected token(s) preceding ';'
```

**Comment by MKleusberg** [comment]
Hmm, might be the case. That would mean that some Windows header files which define the macros are automatically included in the file. But that's definitely possible... I've just changed the names, so let's find out if that was it :smile:

**Comment by chrisjlocke** [comment]
Yay! We have nightlies again!
Thanks both.
