### ISSUE TITLE
SQLCipher encryption dialog prevents access to non-encrypted database, asks for password

### ISSUE THREAD

**Issue by dannguyen** [sqlitebrowser/sqlitebrowser#1195]
### Details for the issue

I've had this issue pop-up randomly for students on a variety of systems and data files. I'm sorry that I haven't yet been systemic in figuring out what causes the error but it pops up so sporadically and randomly...

Infrequently, and unpredictably, students who open my SQLite files using DB Browser get the following dialogue -- I have no idea where this message pops up, or how anything about my SQLite file could be encrypted:

![image](https://user-images.githubusercontent.com/121520/31981087-ac1a526c-b905-11e7-83f8-e3347457fbdf.png)

Even more confusingly, this happens with a random but few number of students, all who are on Macs, with the same recent version of DB Browser. 

### Useful extra information

For my class in the past few years, I provide SQLite datafiles that I create myself -- i.e. writing the raw SQ  importing the data from plaintext CSVs using commands in the SQLite CLI. I don't use DB Browser's importing or DB admin features in the creating or administration of the database.

I do open the SQLite db to explore with DB Browser. But I don't perform any database-altering actions (i.e. anything but `SELECT` statements) to my knowledge. I upload the file to my static file server and -- as far as I assume, the db file should be as accessible as it was when I created it.

Here's an example SQLite database that I provide for my students. It's about 45MB zipped up:

http://stash.padjo.org/data/sfpd-incidents-2012-2016.sqlite.zip

Unzipped, about 200MB. Sorry I couldn't provide a smaller sample but I can't reproduce the error, and I have had students run into it on a variety of platforms/versions/data examples. Just looking for some broad insight about whether I or the students have accidentally triggered some feature, and how to avoid doing it :)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_  10.11.6)
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [X ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/155

**Comment by chrisjlocke** [comment]
DB4S usually only pops up that dialog if the file isn't a fully readable file. If it's not a proper sqlite database, it can only assume it's encrypted.
Running queries on a database still tags the database as dirty (creates a journal file) depending on the journal rules specified. It's possible one of these is locking the database, but DB4S can usually detect this scenario.
Just to confirm, the sample you provided (thanks for that!) Exhibits this behaviour?

**Comment by chrisjlocke** [comment]
As a side note, again, depending on the OS (usually Windows) the sqlite developers don't recommend the databases stored and accessed on a network server, as the file locking can't be guaranteed. This has been known to corrupt databases. Sqlite has rudimentary repair facilities of this occurs... It's usually safer to go back to a non corrupt backup. Ouch.

**Comment by dannguyen** [comment]
Hey Chris, thanks for the reply. Yes, the file that's at that URL is what students have been downloading. Your explanation makes pretty good sense though, in terms of being a possible explanation to the randomness. I'll take a look at the file and see what's corrupt, thanks!

**Comment by chrisjlocke** [comment]
I just downloaded and opened that file with no problems (albeit on .Windows)

![image](https://user-images.githubusercontent.com/7872218/32007761-61261618-b9a2-11e7-8c6b-4d54cd49d0b5.png)

If you continue to experience this though, please comment back, so that further testing can be looked at.  If it does occur, for example, put the .sqlite file in a folder on its own and try opening again.

**Comment by justinclift** [comment]
As an additional thought, any idea of the version number of the SQLite CLI used to create the database?  Kind of wondering if it's something old and maybe slightly buggy in some way.

**Comment by dannguyen** [comment]
Oooh, yuck, you're right, I do need to upgrade:

     3.8.10.2 2015-05-20 18:17:19

**Comment by mannocheck** [comment]
Hello, I know this is an old thread but I just ran into the same issue on Mac. Reading the above, does not fix the issue, nor does a restart. Is there a solution to this problem?

**Comment by justinclift** [comment]
@mannocheck That dialog pops up with DB4S (our abbreviation for "DB Browser for SQLite") initially tries to read the database (as a SQLite file) and fails.  It currently assumes the failure means it's an encrypted database, thus the "what's the password for it?" bit.

Since your database isn't encrypted... that points to something else being wrong.  If you try opening the database file using the sqlite command line utility, does that open it ok? :smile:

**Comment by mannocheck** [comment]
It does not, unfortunately. I was simply adding a column to the db when it crashed, and upon reopening has been throwing this error.

**Comment by justinclift** [comment]
Ouch.  That means the SQLite file itself is almost definitely corrupt in some fashion. :frowning: 

If you have a backup, reverting to that will be your best bet.  If you don't... ugh.  You'll probably either need to recover the data somehow (DB4S doesn't really do that), or (worst case scenario) recreate it.  :frowning:

**Comment by mannocheck** [comment]
Eeesh, ok. 

I appreciate your help, thank you!

**Comment by chrisjlocke** [comment]
When you say the sqlite command utility can't open it, does it return an error?
How big is the database? Is it 0 bytes?
What other files (with the same filename but different extension) are with the database?
Have you tried opening the database in a text editor to see if the file is readable? Does it contain a valid header?

**Comment by mannocheck** [comment]
@chrisjlocke The error being returned from the command utility is: Error: file is encrypted or is not a database

I have placed the file in a folder of its own, as well as in it's original folder which contains .py files.
The file does open in a text editor, and is readable. I am not sure if the header details I am seeing are correct, as a lot of the file contains unusual characters.

The only file that I am trying to open is an 11mb journal file.

**Comment by mannocheck** [comment]
Yes, human readable with words that I recognize. 

The file I am trying to open is called 'mortgage_data.sqlite-journal'. The original file 'mortgage_data.sqlite' size is zero bytes.

**Comment by chrisjlocke** [comment]
Aah, makes sense.  The journal won't be able to be read in DB4S - its purely an SQLite internal file, with temporary data that you can't restore a database from.  It literally holds data (probably not even full records) of records that were changed but not written to the database.
If the original database is 0 bytes, then you'll have to either 'undelete' it (but I assume too much time/disk access has occurred now for that to be feasible) or restore from a backup.
