### ISSUE TITLE
Does DB Browser for SQLite have an IDEA plugin?

### ISSUE THREAD

**Issue by CoXier** [sqlitebrowser/sqlitebrowser#1197]
Does DB Browser for SQLite have an IDEA plugin?

**Comment by chrisjlocke** [comment]
Not 'natively' but it supports the extensions that SQLite supports.

**Comment by justinclift** [comment]
@CoXier With an IDEA plugin, are you meaning for the JetBrains IDEs?

If so, maybe one of the standard SQLite ones would work:

* https://plugins.jetbrains.com/plugin/8322-sqlscout-sqlite-support-  ← Found by search engine, I've never used it though. :smile:

Doing a search on the website there doesn't show up anything for SQLCipher.  So if you're looking for a way to open encrypted databases in a JetBrains IDE... I'm not sure if there's something to do that yet.

Does that help? :smile:

**Comment by CoXier** [comment]
@justinclift Thanks for searching for me.
I am an Android developer and recently I upgrade my Android Studio(based on JetBrains IDEs) to 3.0. Android Studio has a feature https://developer.android.com/studio/debug/device-file-explorer.html.

I have installed sqlitebrowser on my MAC but I can not use it to directly open the db file from Android device so I want to know is there a sqlitebrowser plugin ?

**Comment by justinclift** [comment]
@CoXier Oops, sorry for not getting back to you already.  There isn't yet a plugin for us that will do that.

It sounds like that new file explorer is the modern version of ADB.  ADB has a history of being unreliable though.  eg:

* https://github.com/sqlitebrowser/sqlitebrowser/issues/476#issuecomment-168403277
* https://github.com/sqlitebrowser/sqlitebrowser/issues/489#issuecomment-296430481

Hopefully the new device file explorer is reliable.

Not sure if that helps you though. 😦
