### ISSUE TITLE
Changing case in table name

### ISSUE THREAD

**Issue by zentaz** [sqlitebrowser/sqlitebrowser#1200]
### Details for the issue

Hi,

When trying to change case in table name I get an error message saying that table already exists.
I assume this is a bug?

![dbb_rename_bug](https://user-images.githubusercontent.com/33149818/32099293-05907806-bb10-11e7-827f-7d74ad8352d0.jpg)

Thanks!
Richard

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x ] Windows: ( _version:_10___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Not 'strictly' a bug, but a quirk! ;)  Table names in SQLite are case insensitive, so if you want to change the case, change the name also (eg, DazData to dazdataa, then dazdataa back to dazdata)

Guess DB4S could do similar - when changing a name, change it to something random, then back again to what the user wanted.

**Comment by justinclift** [comment]
Hmmm, wonder how well foreign keys referencing the table-being-renamed would go with that approach.  Might need to do something with pragma's to disable foreign key checking until the renaming is completed.

**Comment by zentaz** [comment]
OK, will try that workaround.  Thanks! :)

**Comment by MKleusberg** [comment]
I've just added this workaround to our code :smile: So with tomorrow's nightly build onwards, you don't have to this yourself anymore and changing the case in table names will "just work". Are you ok to give that a try and see if it's working for you, @zentaz?

**Comment by zentaz** [comment]
Just tried the latest build, changing case works fine now. Thanks very much! :)

**Comment by MKleusberg** [comment]
Cool, thanks for confirming :smile:
