### ISSUE TITLE
I could not download  DB.Browser.for.SQLite-3.9.0-win64.exe

### ISSUE THREAD

**Issue by ShakeebHashem** [sqlitebrowser/sqlitebrowser#1205]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
What happens when you try the download?  Does it give an error message or something we can investigate? :smile:

**Comment by SilvioGrosso** [comment]
Hello everyone,

Just tried to download myself the stable version and everything works fine (3.10.1 - win64.exe installer).
Even the nigthly builds are available as expected (3.10.99 - win64.exe installer).
In short, no problem at all to get them :-)

**Comment by karim** [comment]
Version 3.9.0 can be downloaded from [https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0) and here's a [direct link](https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.0/DB.Browser.for.SQLite-3.9.0-win64.exe) for Windows 64-bit version.

Please note that this version is more than one year old. To get the latest version please visit [https://github.com/sqlitebrowser/sqlitebrowser/releases](https://github.com/sqlitebrowser/sqlitebrowser/releases).

**Comment by justinclift** [comment]
@ShakeebHashem ping?

**Comment by chrisjlocke** [comment]
I'll close this, as the downloads seem to be working.  @ShakeebHashem - please comment or re-open this issue if you want us to look into this further.
