### ISSUE TITLE
Incorrect encoding tooltips (ko_KR)

### ISSUE THREAD

**Issue by to302** [sqlitebrowser/sqlitebrowser#1206]
### Details for the issue
same as  https://github.com/sqlitebrowser/sqlitebrowser/issues/1107
but I use in korean.
![sqlite3](https://user-images.githubusercontent.com/23519977/32213424-842ee98a-be5e-11e7-9539-257918e5b710.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ win 7 pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Thanks to @mgrojo this should be fixed by the way. Can you test the latest nightly build and check if it's working on your system as well, @to302? 😄

**Comment by justinclift** [comment]
Closing this due to lack of response.

@to302 This should be fixed now in our latest nightly builds.  If you get a chance to test it, and it doesn't work for you, please reopen this issue so we can investigate. :smile:

**Comment by to302** [comment]
@MKleusberg It works well., thanks you.
