### ISSUE TITLE
restorepoint

### ISSUE THREAD

**Issue by 6akko** [sqlitebrowser/sqlitebrowser#1207]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Hi @6akko 

Can you detail what the error is - you haven't detailed it at all.

**Comment by 6akko** [comment]
Hello I found the problem, it was empty lines with sign ";" and solved probleb by delete this sign ";"If it possible allow this lines, there are not errors )-- С уважением, Василий В. Терёшкин31.10.2017, 21:11, "Chris Locke" <notifications@github.com>:Hi @6akko
Can you detail what the error is - you haven't detailed it at all.
