### ISSUE TITLE
Error Adding Record

### ISSUE THREAD

**Issue by SUKMAWAN** [sqlitebrowser/sqlitebrowser#1208]
### Details for the issue

why i can't adding record ?
![image](https://user-images.githubusercontent.com/33270724/32255578-83957124-bedb-11e7-8281-636498b8d868.png)
![image](https://user-images.githubusercontent.com/33270724/32255683-9256598e-bedc-11e7-994c-e4632e664f9a.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
And Id_jenis of '1' exists in the jenis table?

**Comment by chrisjlocke** [comment]
This sounds spooookily 👻 🎃 like #463 ... Can you check the latest nightly?

**Comment by mgrojo** [comment]
This might the same as #531 and id_jenis is not a PRIMARY KEY or have a UNIQUE constraint in the jenis table.

@SUKMAWAN Could you still confirm it so we can close or clarify this issue? Sorry for taking so long to answer.

**Comment by mgrojo** [comment]
Closing this due to lack of response.
