### ISSUE TITLE
Error downloading due to invalid/corrupt/missing signature.  

### ISSUE THREAD

**Issue by sbrady373** [sqlitebrowser/sqlitebrowser#1210]
### Details for the issue
On download with browser, download is stopped due to signature of the file not being valid or was corrupt.  Needs a valid signature in order to be able to download an exe.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version:_10 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Which browser are you using?  What link are you using to download?

**Comment by sbrady373** [comment]
Hey Chris,  

I was using IE.  Now probably not an OOTB issue bit if its locked down and requires a valid code signature, that is where it seems to potentially be an issue.  

I know it requires a code signing cert, I just wasn’t sure if that was something possible or if github provided that means to do so.

Steve

**Comment by sbrady373** [comment]
Sorry missed the second question.  It was for 64 bit 3.10.1 for Windows.

**Comment by justinclift** [comment]
Hmmm, in theory the code signing thing should be working.  GitHub uses HTTPS, so the download connection should be secure and the file itself was signed with a MS Authenticode compatible cert when I made the 3.10.1 installer packages.

Is the download still not working for you?  (just in case it was something weird/transient)

**Comment by justinclift** [comment]
@sbrady373 Are you still hitting this problem when trying to download?

**Comment by justinclift** [comment]
Closing this due to lack of response. :wink:
