### ISSUE TITLE
Feature request: Add Number of rows selected with Select statement

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1211]
Hello everyone,

Please, add the information regarding the number of rows selected.

With SqliteStudio or PgAdmin (PostgreSQL) when I write some Sql statement I get as output the information about the total rows selected with my query.
This is particulary useful with hundreds of row selected as ouput.

At present, with Db Browser for Sqlite I only get the time elapsed for my query.
To get the number of rows I am forced to write another query : SELECT COUNT(*) FROM table1 WHERE etc etc

Tested on Windows 7 (64 bit) - version 3.10.99 (yesterday's daily build)

Thanks a lot !

**Comment by MKleusberg** [comment]
Oops, this was working until recently. Seems like I broke it with commit 955848f957b77b77dd3cb73480fb36a14cab501b. With the next nightly build it should be working again 😄 Thanks for reporting this!

**Comment by SilvioGrosso** [comment]
HELLO MKleusberg,

I confirm this issue is fixed !

Now everything works fine both with the 32bit.exe build,  on Windows Xp professional and, on Windows 7, through today's 64bit.exe build.

Thanks a lot indeed for this quick fix :-)

**Comment by justinclift** [comment]
Awesome.  Great work guys. :smile:
