### ISSUE TITLE
Can't to remove encryption from a database, how to open the database in python using sqlite3?

### ISSUE THREAD

**Issue by yashvone** [sqlitebrowser/sqlitebrowser#1215]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
That topic is a bit unclear.  But to make sure I'm understanding ok, are you wanting to open a database (still encrypted) using Python?

If that's the case, you'll need to use a Python library which open "SQLCipher" databases.  SQLCipher is what we use for the encryption layer.

This seems like the right kind of thing, though I've not personally used it:

&nbsp; &nbsp; https://pypi.python.org/pypi/pysqlcipher

Does that help? :smile:

**Comment by yashvone** [comment]
I'll try sqlcipher python library.
But I also wanted to remove the encryption from the database which I encrypted using your software. I can't find option to decrypt

**Comment by justinclift** [comment]
Ahhhh.  To decrypt the database, you just need to use **File** → **Set Encryption** and give it a blank password (eg no characters).

**Comment by MKleusberg** [comment]
Closing this because the original question was answered and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time, @yashvone  :smile:
