### ISSUE TITLE
Misleading import CSV message: "Import Completed"

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1217]
Hello everyone,

On Windows 10 (64 bit) I am testing yesterday's daily build (3.10.99 - 64.exe).

In all truth, I don't know whether this issue is a Db Browser feature or a bug :-)

In short, whenever I import a CSV file the message I get is "Import completed" even though sometim is quite the opposite since the CSV is not imported at all into my table !

With PostgreSQL whenever I import the same CSV file I get a more self-explanatory message.
In essence, the message is "An error has occurred, there are extra data after the last column, line 2. Copy has failed ! "

To reproduce the problem:
CREATE TABLE workers (
id integer not null ,
name text,
age integer) ;

Save with LibreOffice Calc (or whatever software you like) a CSV file with an extra column.
E.g.
id|name|age
1|marco|silvio|44 #extra column here
Saved with UTF-8 encoding  and | as separator

When you import this CSV into DB Browser (into the table workers) the message I always get is: 
"Import Completed".
IMHO, this message is misleading because no data has been imported into my table ultimately.
By reading the reports of PostgreSQL I am able to fix the CSV file whereas with Db Browser is not so straightforward (at least in my view...)

I have recorded a video with all my steps on Windows 10 where I import my CSV file both on DB Browser and PgAdmin (PostgreSQL) .

If you have some spare time you can take a look:
https://www.dropbox.com/s/729k8ou78rx8tut/DB-BROWSER_IMPORT_CSV_COMPLETED.mp4?dl=0

**Comment by justinclift** [comment]
Yeah, similar thought here.  The "Import Complete" text seems to be shown at the end of the import process, regardless of what happens.  eg even when cancelling out of it

We could probably turn it into some kind of useful status info thing instead.  Cancelling the import probably means it doesn't need to be shown at all. :smile:

**Comment by chrisjlocke** [comment]
If you read the first line (which would either be a header or the first row of data) and remembered that number of fields, you could 'abort' the import if any line read didn't have the same number of fields.  Guess you could ignore if the fields exceeded the first number (ie, you read too many columns?) but if you had less, then that would be bad.
Under normal operation, I would assume a CSV file to have a consistent number of fields for each line.  If the user isn't doing that, then it should be amended to the above 'rules'.  This would make it easy to identify 'corrupt' CSV files.

**Comment by MKleusberg** [comment]
We got rid of the "Import completed" message entirely in commit 8f82f26d4f115619afa687ef40f2c422ad4ad2ee. So let's close this issue :wink: If I'm missing anything, feel free to reopen it :smile:
