### ISSUE TITLE
Why is sqlitebrowser trying to spy on me

### ISSUE THREAD

**Issue by crash1013** [sqlitebrowser/sqlitebrowser#1219]
### Details for the issue
Every time I use sqlitebrowser, quietly and in the background it is trying to send information to the following address with this message.

"Error when connecting to https://raw.githubusercontent.com/sqlitebrowser/sqlitebrowser/master/currentrelease
Connection timed out"

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
> it is trying to send information to the following address

Its not 'sending' but 'receiving'.
If you click the link (which GitHub has automatically linked, so its a valid link) you'll see it returns the following information:

    3.10.1
    https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1

This is the current version, and a link to the current version.

This is DB4S's way of working out whether you're running the latest version or not.  I presume your firewall is blocking DB4S from talking to the outside world, so yes, the connection is timing out.

If DB4S detects its running an old version, then this dialog pops up:

![image](https://user-images.githubusercontent.com/7872218/32461617-5b84dbf0-c32e-11e7-8bd2-fac2e8c3aa5f.png)

(using the above collected information)

If you click 'View' and 'Preferences', you'll see a 'check for updates' option.

![image](https://user-images.githubusercontent.com/7872218/32461659-7f32f776-c32e-11e7-8fa3-f7a24f7a047a.png)

If you untick this (so there isn't a tick in it .. like this)

![image](https://user-images.githubusercontent.com/7872218/32461682-92bf399e-c32e-11e7-9595-de9a6f267533.png)

then DB4S won't check for updates, won't attempt to download the above file, and won't trip your firewall, and won't display a 'timed out' warning.

**Comment by chrisjlocke** [comment]
@crash1013 - Does that make sense?  Are you happier with that explanation?

**Comment by chrisjlocke** [comment]
Closing due to no response.  @crash1013 - Feel free to comment back when you return.  You can still comment on closed issues.

**Comment by shaoyongyang** [comment]
i working on not have internet envirment. when i open it. show tip message. close it  then application don't use.
