### ISSUE TITLE
Allow accessing DBs over SSH

### ISSUE THREAD

**Issue by nabeelomer** [sqlitebrowser/sqlitebrowser#1221]
Many databases are stored on servers with SSH access. Being able to browse a DB over SSH seems like a great feature.

**Comment by justinclift** [comment]
This should be possible at the moment if you use something that provides a filesystem layer via ssh.

One such filesystem is SSHFS:

&nbsp; &nbsp; https://github.com/libfuse/sshfs

Haven't tried that personally though.

For directly adding SSH support to DB4S itself (without need an ssh capable filesystem layer)... that seems unlikely.  We'd need to add some kind of server selection/setup gui piece, filesystem browsing thing, and other supporting pieces (`fsync()` equivalent, etc).  Doesn't really seem like something in-scope for this project.  At least, not in the foreseeable futture. :wink:

Does the SSHFS approach work for you? :smile:

**Comment by nabeelomer** [comment]
I use macOS and I'm not really comfortable using FUSE filesystems, so it doesn't, but I understand your point.

**Comment by justinclift** [comment]
No worries @nabeelomer, it doesn't hurt to ask. :smile:
