### ISSUE TITLE
Plot and filter values are saved with the project but not displayed when loading project

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1222]
### Details for the issue

The plot data and current filter is correctly saved in the project. But when the project is reopened and the information restored, the filter values in the header are not displayed. The appearance is that of an unfiltered table, but it is actually filtered internally. The plot is neither recovered, but the data internally is present. 

Pressing the refreshed button solves both issues. The plot is drawn, and the filter values are visible again in the header.

It's a minor issue, but something that we should take a look at some moment. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 16.04.3 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: git commit a03a90105117ba7996fffc26028ee1292b1ed450 and previous ones

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good discovery. :smile:

**Comment by mgrojo** [comment]
Moreover, if in this situation (table filtered and restored though project file, but filter is not visible in the header) I click on "Duplicate record" or press tab at the last cell, the application crashes.

Clicking Refresh after opening the project always fixes everything, the filter is visible and there are no subsequent crashes.

**Comment by mgrojo** [comment]
Now I only reproduce the filter issue. I cannot reproduce the crash nor the problem with the plot. But trying to crash it I stumbled upon  #1289 :smile:

**Comment by mgrojo** [comment]
I'll close this issue, since it covered some problems, some already fixed, and the remaining one is better described in #1573.
