### ISSUE TITLE
Symbol change error

### ISSUE THREAD

**Issue by princeteekoy** [sqlitebrowser/sqlitebrowser#1223]
This is a wonderful application. Congratulations to the developers.
My Issue : When I upload data in CSV format, the symbols in the data like Degree Symbol (º), Apostrophe (" ") and all such symbols does not display accurately in the table. What i see is (�) in the places of these symbols. How can I solve the issue. 
Expecting your prompt Replay as i have to upload data with One lakh+ rows into the table. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
![screen](https://user-images.githubusercontent.com/22438614/32674636-0b5697aa-c67a-11e7-9549-97f482065fac.jpg)

- [ X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
That sounds like an issue with the selected encoding. What value have you selected for the "Encoding" field in the CSV Import settings? If it is UTF-8, you could try setting it to ISO-8859-1 and vice versa.

If none of them work, you can install Notepad++ and open the CSV file using that. Notepad++ should auto-detect the encoding of the file and tell you somewhere. You can then go back to DB4S, set the "Encoding" field to "Other" and type in the encoding reported by Notepad++.

**Comment by justinclift** [comment]
@princeteekoy Did you have time to look into the encoding setting, as mentioned by @MKleusberg above?

**Comment by justinclift** [comment]
Closing this due to lack of response.  Hopefully @princeteekoy got this working in time. :smile:
