### ISSUE TITLE
Feature request: add shortcut to increase-decrease text size font (SQL execute window)

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1225]
Hello everyone,

I have tested Sqlite browser on Windows 10 (daily builds).

Please, add a shortcut to increase-decrease the size of the text in the SQL execute window (zooming in and zooming out into the window, actually).
At present, you can already change the size of your text through the Preferences options but it is a fixed option.
I would like to propose to add a shortcut to increase-decrease the size through a shorcut whenever you write your code in the Sql execute window.

More precisely : 
- "CTR +" in order to increase the size (when you  press this shortcut you are zooming in the window);
- "CTR - " in order to decrease the size (when you press this shortcut you are zooming out in the window) .

I have tested these two shortcuts with:
- Sublime text editor ;
- Kate editor (KDE desktop) ;
- Shell on Linux (tested on Ubuntu) ;
- Firefox Browser and Chrome Browser.

Thanks a lot for considering this proposal :-)

**Comment by mgrojo** [comment]
Surprisingly, it works for me for the latest nightly build in Windows 7 and in Ubuntu 16.04. Cannot test in Windows 10.

As far as I know, we don't set any option for this, it is enabled by default by QScintilla.

**Comment by SilvioGrosso** [comment]
Hello mgrojo,

Thanks a lot indeed for your reply and for your latest work on Sqlite Browser ! :-)
It is indeed appreciated.

Just tested again both on Windows 10 (64 bit) and Windows 7 (64 bit).
I have downloaded today's build (64.exe installer)

Whenever I press CTR + (that is, CTR together with +) nothing occurs.
With Sublime text editor or Kate (KDE) this shortcut works (the same as its opposite, "CTR -")

I have just recorded a short video on Windows 10 (64 bit) to show my failed attempt:
https://www.dropbox.com/s/itzbzj13ybm4o9g/BROWSER_SQLITE_ZOOMING-IN-OUT.mp4?dl=0

Even now, on my Firefox browser, this shorcut works fine on this Github window while I am writing this bug report :-)

**Comment by mgrojo** [comment]
Thanks for your appreciation :smiley: 

Well in fact, in Windows it is not working for me with the regular + key in the keyboard, but it does with the + key in the numeric pad. In Linux, both work. Could be a glitch with keyboard layouts in QScintilla. Have you tested with the numeric pad?

According to the Scintilla History, the mouse wheel should be supported as well (with Ctrl?) but that is not working for me:
| Release 1.01
| Wheel mouse support for scrolling and zooming on Windows. Zooming with Ctrl+KeypadPlus and Ctrl+KeypadMinus. 

By the way, Ctrl+0 is also standard for restoring the default zoom level, but that seems to not be implemented.

**Comment by SilvioGrosso** [comment]
Hello mgrojo !

Just tested today's build on a true keyboard since all my personal computers are notebooks and do not have the numeric pad :-)

In short, on Windows, zooming in-out does work when you press CTR + - on your numeric pad :-)
On my notebooks it did not work since I have only the 2 buttons + -  but not the numeric pad with them.
On Windows, I have also tested the mouse with its wheel (CTR+wheel)  but it is not working when you try to zoom in-out.

As regards the WIKI:
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-Keyboard-Shortcuts
this shortcut (CTR + - to zoom in-out) is not listed yet.

Today, I have even tested the new cool option to search available on the Execute Sql window.
I suppose your next step will be adding a replace option as well :-)

THANKS a lot indeed for your support !

As far as I am concerned, you can close this ticket.

**Comment by mgrojo** [comment]
Ok. I've updated that wiki page with the zooming and the new find shortcuts. In fact, we have two wiki pages for shortcuts:
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-Keyboard-Shortcuts
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts
Maybe we should merge both, because they don't have a clear different scope.

**Comment by mgrojo** [comment]
Closing. Although it could be improved (Ctrl+0, working always with both numeric pad and regular keys...), it should be resolved at the (Q)Scintilla layer.
