### ISSUE TITLE
Retain SQL queries in a user Table to recall later.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1227]
### Details for the issue
I have SQL cheat sheets in text files that I paste from for various db's.
It would help to have DB Browser for SQLite store the Execute SQL stuff I entered in a user table for later.

### Useful extra information
Selecting previous SQL text from a drop down list would save users the time of cutting and pasting SQL text from external files or worse, retyping from scratch.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:
- [x] Windows: ( _version:_ 3.10.99 )

#### I'm using DB4S version:
- [x] 3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Have you tried with project files? Besides, take a look at #1140. Is your proposal equivalent to that?

**Comment by sky5walk** [comment]
Whoa, I didn't know projects were a thing? I will review them and modify my post soon.
Thanks for the link. My searches missed that.

**Comment by sky5walk** [comment]
Ok, 'Save Project'  satisfies my request.
And I see renaming the "SQL 1, SQL 2, SQL 3" tabs is by DoubleClicking them. Nice.
