### ISSUE TITLE
You need a trick for macOS on 4k/5k

### ISSUE THREAD

**Issue by SourceTrigger** [sqlitebrowser/sqlitebrowser#1232]
Hello,

On macOS in 4k and 5k resolutions the program runs very slowly. It jerks extremely. The reason for this is that no OpenGL Context is used. On Windows and Linux it's no problem, but under mac it's a disaster :) 

You can increase the rendering of tables in particular by 400% by adding a layer when initializing the program. 

Add in MainWindow Constructor after setupUI:

```c++
#ifdef Q_OS_MACX
    QOpenGLWidget *ogl = new QOpenGLWidget(this);
    ui->horizontalLayout->addWidget(ogl);
    ogl->setHidden(true);
#endif
```

and add QOpenGLWidget to includes. After this Qt use OpenGL rendering ;)

It does not matter where the widget is located, the main thing is that it exists and Qt use the OpenGL rendering on mac.

I've made a short video for you to see both versions
[Video on Youtube](https://www.youtube.com/watch?v=83aKIWCQVYA)

**Comment by justinclift** [comment]
Ahhh, that should be pretty easy to do.

Do you want to make a Pull Request, which we can just merge? :smile:

**Comment by SourceTrigger** [comment]
Hello,

I'm new to GitHub, I did it.
#1233

**Comment by justinclift** [comment]
Oops, thanks.  I completely forgot to close this. :smile:
