### ISSUE TITLE
Translation/Spelling Error

### ISSUE THREAD

**Issue by weldwatcher** [sqlitebrowser/sqlitebrowser#1234]
### Details for the issue

In the tab register "SQL ausführen" ("presumed: "run SQL"?) the "Hover-Over"-Help for the "Shift+F5" function "Aktuelle Zeile ausführen", the word "Zeile" is spelled wrongly "Zeiel".

Appart from that, splendid program!!
Thanks a lot.

WeldWatcher

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X
![db3sqlite](https://user-images.githubusercontent.com/33838114/33026292-6a6cc8fc-ce10-11e7-9116-bfb3faa46d93.PNG)
] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Aha, thanks @weldwatcher.

Just updated the translation file with that fix: 09e170f75dff94761918767c644d2a16c7b4f0e5.

Would you be ok to try tomorrow's nightly build, to verify the fix from your point of view?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Closing this, as it's probably correct.  Well... no-one has mentioned otherwise. :smile:
