### ISSUE TITLE
Dragging and dropping a file while on the "Browse Data Tab" doesn't load the file

### ISSUE THREAD

**Issue by AstronautG117** [sqlitebrowser/sqlitebrowser#1237]
### Details for the issue

When I hover over with the file, the text reads +Copy 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: (10 version: 10.0.16299)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @AstronautG117.  Co-incidentally this looks like a bug fixed today with #1236.

Would you be ok to download our automatic nightly build tomorrow, and verify whether it's now working for you? :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by AstronautG117** [comment]
Yeah, I'll give it a look. My issue didn't crash the program, is it probably still the same issue?

**Comment by justinclift** [comment]
Hmmm, maybe not then. It sounded similar, but the other one was definitely a crash issue. 😦

**Comment by justinclift** [comment]
Ok actually... reading the code for the fix, it'll probably fix your problem too.  Well... hopefully. :smile:

**Comment by AstronautG117** [comment]
@justinclift It's fixed on the nightly! Thanks!

**Comment by justinclift** [comment]
Excellent!

Thanks to @SourceTrigger for the fix. :smile:
