### ISSUE TITLE
Feature request: format SQL code-completetion commands as UPPER CASE

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1238]
Hello everyone,

Just tested today's build on Windows 10 - 64 bit (downloaded the x64.exe version).

Currently, whenever you write your code into the Execute SQL tab there is no way (or shortcut) to automatically format it (UPPER CASE, new line,  indentations and so on).
Most of all, whenever you write your code in the Execute SQL window and you press enter all commands are always proposed (forced) as lower case (create, select, from, where, like instead of CREATE, SELECT, FROM, WHERE, LIKE etc).
This style formatting improvement is possible in many GUIs applications such as the freeware SqliteStudio [1] or by dint of web applications [2].

What about adding an option, in the "Preferences..." window, as regards the code-completion feature, in Sqlite Browser, to have them proposed as UPPER CASE instead ?  :-)

For instance , you write your SQL code to create a new table. 
Whenever you press enter on your keyboard to apply the create command this is formatted as CREATE instead of create as it is now (same things for the other commands: from, where, like etc).

Thanks a lot in advance for reading this very long message :-)

[1] https://www.dropbox.com/s/doxq0yfquwa2xwl/SQLITESTUDIO_FORMAT_SQL_CODE.mp4?dl=0
[2] https://sqlformat.org/

**Comment by justinclift** [comment]
Sounds like a good suggestion to me. :smile:

**Comment by mgrojo** [comment]
I wonder what should be the default value for the new preference setting ("Keywords in UPPER CASE"). Should it be false to honour the current behaviour? Or should it be true because the preferred style for SQL is usually keywords in upper case?

**Comment by chrisjlocke** [comment]
As it has no effect on anything but output for the user, I suggest it should be on by default ... by turning it on, it's not going to break anything.
The more DB4S adheres to the standard, is a good thing.

**Comment by justinclift** [comment]
If it's easy, jJust turn it on.  If someone complains (not expecting so, but could be wrong), we can then think about changing it. :wink:

**Comment by mgrojo** [comment]
@SilvioGrosso @fulldecent @lausek I've just implemented the completion of SQL keywords as upper case. If you want to give it a try, it will be available in our next nightly build: https://nightlies.sqlitebrowser.org/latest/

**Comment by fulldecent** [comment]
Looks great, thank you!

**Comment by chrisjlocke** [comment]
Works well - thanks @mgrojo.

Semi linked to this, but can the auto complete have more than one word, or is it limited to just words?  If you type LEFT, it would be handy if it auto completed to LEFT JOIN rather than just LEFT (same for right)... maybe even suggest SELECT * FROM in addition to just SELECT too.... but I'm scampering into a different issue now....... ;)

**Comment by SilvioGrosso** [comment]
Just tested on Windows 10 (64 bit) and everything is fine.
Now SQL code is easier to read...

Thanks a lot indeed ! :-)

**Comment by justinclift** [comment]
@chrisjlocke Make another issue for the suggestion, as I'm closing this now since it's done. :smile:
