### ISSUE TITLE
How do i open database in .mozilla directory?

### ISSUE THREAD

**Issue by petermoo** [sqlitebrowser/sqlitebrowser#1239]
Latest DB Browser 3.10.99 from PPA. Open Database. The directory list does not show the .mozilla directory. I thaught it might be like one of those funny applications where you have to switch on the display of . files. I looked for a setting but did not find anything.

How do I open a database in the .mozilla directory?

#### I'm using DB4S on:
- [ *] Linux: ( _distro:_ Linux Mint 18.2 )
#### I'm using DB4S version:
- [ *] 3.10.99

**Comment by FriedrichFroebel** [comment]
A right click on the folder area of the "Open" dialog and selecting "Show hidden files" should do the trick.

**Comment by justinclift** [comment]
@petermoo In theory, the suggestion from @FriedrichFroebel should work.  If that doesn't though, let us know. :smile:

**Comment by petermoo** [comment]
Right click in the file list area worked.

**Comment by justinclift** [comment]
Awesome.  Thanks for helping our @FriedrichFroebel. :smile:
