### ISSUE TITLE
Refactor SqliteTableModel interface

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#1247]
I was planning to do this for quite some time now because the current interface has repeatedly caused problems (like four queries per table instead of two, or the problem mentioned by @mgrojo in #1245). Instead of fixing these bugs by adding more special cases I would like to change the interface of the SqliteTableModel class completely so it is easier to maintain and easier to use too. Currently it is not clear which function fetches data and which doesn't.

I'm opening this issue for it because I probably won't have the time to do it right away.

**Comment by mgrojo** [comment]
@MKleusberg, you already did that refactoring, don't you?

**Comment by MKleusberg** [comment]
Yes, let's close this issue. I've left out parts of what I intended to achieve because they turned out to not work great in practice. But I'm done with what is easily possible.
