### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by isrep** [sqlitebrowser/sqlitebrowser#1248]
### Details for the issue

1. open DB Browser for SQLite
2. make sure you are in Execute SQL tab
3. click "Find text in SQL editor [Ctrl-F]" or press Ctrl-F
4. app crashes

Thank you for DB Browser for SQLite, it is quite good tool.

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Ubuntu v 16.04.3 LTS )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: 882fc8d3d35

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Thanks @isrep. That should be solved in the next nightly build.

I have to remember testing without any database open :wink:

**Comment by isrep** [comment]
While we are at it, there seems to be another crash in 5a8d6bbf62c

1. open DB Browser for SQLite
2. make sure you are in Execute SQL tab
3. click on Save icon and choose "Save SQL file as"
4. type in some file name into "Select file name" dialog
5. click Save
6. app crashes

Thanks again

**Comment by mgrojo** [comment]
I've applied the same check as in "Save SQL file" for preventing the crash.

A better solution would be to always have an SQL tab open, even when there is no DB open. We let the user open one, so I assume that is not a problem. 

Another better solution is to enable the save button (and probably others) only when there is at least one SQL tab.

**Comment by isrep** [comment]
Thank you, it does not crash any more.
