### ISSUE TITLE
XML mode for the cell editor

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1253]
Based on the work I've done for the issue #1173, I plan to develop an XML mode for the cell editor. I open this enhancement request so anyone interested in this mode, can share his expectations or ideas about it.

**Comment by justinclift** [comment]
Sounds useful. :smile:

For XML schema support, do you reckon validation will be complicated?

**Comment by justinclift** [comment]
😀 

I kind of wonder how SVG will turn out.  The existing image viewing bits will be able to view it, so an XML mode might make for a safer way to do minor adjustments.

**Comment by justinclift** [comment]
Just had a thought.  If we take some screenshots of the XML and JSON editors, we can send a tweet about them and probably get a few extra people testing them out.

Might be useful for figuring out that button placement thing. :smile:

**Comment by mgrojo** [comment]
Yeah, why not.

**Comment by mgrojo** [comment]
I'm going to close this, since nobody has reported problems and it's ready for release. The only improvement that I'm aware of is detecting XML in an efficient way, so the mode can be switched automatically to XML when appropriate, but it's better to make the cut here for the 3.11.0 release.

Regarding the button placement thing, maybe it's not so important when nobody more has paid attention to it :smile:
