### ISSUE TITLE
[Feature Request] - Plot zooming

### ISSUE THREAD

**Issue by FabianInostroza** [sqlitebrowser/sqlitebrowser#1258]
### Details for the issue
It would be useful to be able to zoom in the plot pane. That feature could help reduce iterations
in reducing the the range for the X axis.

### Useful extra information
QCustomPlot already support zooming, it's a matter of enabling it and defining or adding controls for
the used to control the interaction (zoom on X axis only, Y axis only, etc).

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
I'm glad to say that zooming is implemented in our latest nightly builds. That was my solution to issue #838. You can drag the plot for zoom in and out with the mouse wheel.

If you'd like to try: https://nightlies.sqlitebrowser.org/latest

**Comment by FabianInostroza** [comment]
mmm, I compiled from sources yesterday, didn't found the feature. Will check again.

**Comment by mgrojo** [comment]
You can also click on a point to get the row selected in the associated table.

**Comment by FabianInostroza** [comment]
Thanks, the table and graph synchronization is a nice feature. Could a checkbox (or some other way) be added to limit zooming to the X axis only?.

I accidentally hit the ESC key with the focus on the plot pane and it was hidden. I was unable to bring it back.

**Comment by mgrojo** [comment]
Ok, let's leave this issue open for the enhancement about zooming to only one axis.

The problem with the ESC is an ugly bug :smile: The same happens to the Remote dock. Not sure why when all are QDialog. A different issue would be ideal.

**Comment by mgrojo** [comment]
@FabianInostroza I've implemented your suggestion of zooming (and dragging) only in one orientation. You have to select first the axis (or associated labels) and then the wheel and drag operations will affect only to that axis.

I've also documented the possible interactions in the What's This information,  so users can discover them. Well, if they ever use this feature :smile:

If you'd like to test it, it will be available in the next nightly build: https://nightlies.sqlitebrowser.org/latest

**Comment by FabianInostroza** [comment]
Wonderful, many thanks.
I use sqlitebrowser mainly for data exploration and this is really useful to me, thanks.
