### ISSUE TITLE
Cannot change workspace on Debian 

### ISSUE THREAD

**Issue by thread9000** [sqlitebrowser/sqlitebrowser#1261]
### Details for the issue

Just installed on Debian Stretch gnome with grid workspace plugin. I cannot change to a different workspace. I move to a different workspace and right away im pulled back to the workspace with DB Browser on it. Pretty frustrating. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ x] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
3.9.1 had this issue, which was resolved in a later version. The latest version is 3.10.1.
If you install the latest version, you shouldn't experience this issue.

**Comment by justinclift** [comment]
As a data point, the issue @chrisjlocke mentions was #934.  The matching fix was c0b67ab4a82e1f20891e523f308800c26c6412aa.

@chrisjlocke It doesn't look like this is in a release yet.  3.10.1 was released in September, but this fix was only created in late October.

@thread9000 If our nightly builds for Ubuntu also work on Debian (I'm not sure), then try the latest nightly that way.  It shouldn't have the problem.  If the Ubuntu nightlies don't work... you'll probably need to compile it yourself.

We have build instructions for (again) Ubuntu:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

Not sure how well they translate to Debian though.  If you do go down this avenue, please let us know if the instructions (etc) need any changes for Debian. :smile:

**Comment by justinclift** [comment]
@thread9000 Did any of the above help? :smile:

**Comment by justinclift** [comment]
@thread9000 ping?

**Comment by justinclift** [comment]
Closing this due to lack of response.

@thread9000 Hopefully one of the above options worked for you. :smile:
