### ISSUE TITLE
Allow user to set the BLOB text. Preview for the displayed colors and text in Preferences.

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1263]
### Details for the issue

Other browsers for SQLite allow configuring the text to be displayed in BLOB fields. This would the same we do for NULL fields, but applied now to BLOB fields.

### Useful extra information

If we want this feature, I've thought in performing this improvement in the Data Browser tab in Preferences dialog, so we get a nice preview of the colors in the fields used for setting the NULL and BLOB texts (text field for Regular would function only as a preview, of course).

![imagen](https://user-images.githubusercontent.com/13812910/33808696-1ae8de0c-ddeb-11e7-9eb3-d7560e4349d1.png)

If this is welcome, I can contribute the implementation.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

**Comment by justinclift** [comment]
For anyone looking over this and wondering what the change is, this is a screenshot of the current tab layout:

![preferences-before](https://user-images.githubusercontent.com/406299/33808836-b7cf160c-dde4-11e7-8424-6565481f7c9a.png)

@mgrojo's concept is to add an additional column to the "Field display" section, showing what the rendered text would look like if applied.

Personally, I reckon it's a good idea. That should make selecting a new text font and colour faster & easier for people before committing to it. :smile:

**Comment by mgrojo** [comment]
This is already implemented. We can close it now, but anyone is still free to add any comments or feedback.

**Comment by justinclift** [comment]
Cool. :smile:
