### ISSUE TITLE
Open Read Only

### ISSUE THREAD

**Issue by angkastiel** [sqlitebrowser/sqlitebrowser#1265]
### Details for the issue

DB4S has option File\Open Database Read Only, but this option absent in command line options. Please, add option like --read-only to command line.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 7 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good idea. :smile:

**Comment by MKleusberg** [comment]
Yep, good idea! I have just added that option. You can now open a database in read-only mode by adding the ```--read-only``` command line option or ```-R``` for short.

@angkastiel Can you download tomorrow's nightly build and check if it works as expected for you?

**Comment by chrisjlocke** [comment]
Just checking ... all the other command line options are lowercase.  Is -R meant to be uppercase only?

**Comment by MKleusberg** [comment]
Yes, that was intentional. Vim is using ```-R``` for read-only mode, so I was thinking that probably more programs are using it, and we might as well :wink: I haven't checked though.

**Comment by justinclift** [comment]
@angkastiel Ping?  Are you around? :smile:

**Comment by angkastiel** [comment]
@justinclift, i'm here. How to download the build, which spoke about @MKleusberg.

**Comment by justinclift** [comment]
@angkastiel Excellent.  From here, they're automatically built every night from our latest source code. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by angkastiel** [comment]
@justinclift, @MKleusberg, i checked build at 12 jan 2018. Command line options -R and --read-only work as i expected. Thank you very much :smile:

**Comment by justinclift** [comment]
Excellent.  Good stuff @MKleusberg. :smile:

**Comment by MKleusberg** [comment]
Cool, thanks for testing, @angkastiel 😄
