### ISSUE TITLE
Remember previous directory in which a database was opened from

### ISSUE THREAD

**Issue by Bilge** [sqlitebrowser/sqlitebrowser#1267]
The MRU list is useful for opening exactly the same database as previously, but if new databases are often added to the same directory - or a directory in close proximity to that directory - it is often more useful to present the open file dialog at the same location as it was previously at when successfully selecting another database. 

That is, I opine it's more useful to remember the last directory a database was opened at than to always show the home directory as the default starting location.

**Comment by sky5walk** [comment]
View - Preferences - Default location = Remember last location

**Comment by Bilge** [comment]
Might I propose it be made the default?

**Comment by justinclift** [comment]
@Bilge That default is probably not going to be changed.  The current approach **seems** (our best guess) to suit most people. :smile:

**Comment by Bilge** [comment]
OK
