### ISSUE TITLE
Browse data on large databse hangs until crash instead of gracefully 

### ISSUE THREAD

**Issue by zapper59** [sqlitebrowser/sqlitebrowser#1269]
### Details for the issue

Hi guys, this is my first time using your software so bare with me.  I am trying to view a 3.2gb sqlLite database backup image.  It has a a single table with almost 4 million rows so performance issues are expected. Running queries is slow as expected (running off a mechanical drive ATM), but when I accidentally clicked on the browse data tab it took just as long and crashed the app the first time I tried this.  In other database viewers I've used the browse view would only load the first 1000 rows unless explicitly told otherwise.  So I guess this is a feature request to better handle viewing large databases. 

#### I'm opening this issue because:

- [ ] DB4S is crashing

#### I'm using DB4S on:

- [ ] Windows: 8

#### I'm using DB4S version:

- [ ] 3.10.1

**Comment by justinclift** [comment]
Hi @zapper59.  Co-incidentally, this is something we've been discussing on and off in another issue (#584) too.

The problem mainly stems from our calling `SELECT count(*) FROM table_name` (to populate the table row info in the bottom left) when we switch to the Browse Data tab.

With SQLite, that query reads through the entire table, ignoring indexes.  For small tables, this isn't a problem... but as you've discovered, for large tables it can be a problem.

Do you have time to scan/look through #584 and chime in with your thoughts and/or potentially useful data points? :smile:

**Comment by justinclift** [comment]
Closing this, as it's a duplicate and we'll get it done in #584.
