### ISSUE TITLE
[feature request] using standard shortcuts ctrl to select/unselect cells and shift to select from here to there

### ISSUE THREAD

**Issue by WiliTest** [sqlitebrowser/sqlitebrowser#1277]
### Details for the issue

I would be great to be able to use the standard way to select, unselect cells in the browse data tab.
For instance, when I click on the cell 1 and the cell 4 while pressing ctrl it select all the cell in between (1 to 4). Using the standard shortcut it should do that when pressing shift. But when pressing ctrl it should only select the cell 1 and 4. 

In brief: pressing shift should select the 2 cell selected plus all in between. Pressing ctrl should only select the one we click.

Your app is more than perfect already, it's just a suggestion (which is much easier to suggest than to do!)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
I knew we already have this open, but wasn't easy to find it: #1104. I'll mark this as duplicate to avoid two discussions in parallel.
