### ISSUE TITLE
Edit Database Cell does not show some data

### ISSUE THREAD

**Issue by isrep** [sqlitebrowser/sqlitebrowser#1282]
### Details for the issue
Data shown in Edit Database Cell(text mode) does not reflect data visible in browse data tab.
Prominently, short srings are not displayed, longer string are trimmed, reported char length is in some cases wrong.
Double clicking on some cells with binary data could clear data. ( e.g. in example below, double clicking on 4th row in browse data tab of test table (so the cell goes to edit mode with visible cursor) and then clicking on some other row will delete data from 4th row.)
Might relate to "Improve handling of BOMs in table cells" changes and/or #1279.
Still there should not be misleading display of simple data and silent discharge of data.
Please check with test table and provided data in Browse Data and Edit Database Cell.

    DROP TABLE if exists test;
    CREATE TABLE test (dt TEXT);
    INSERT INTO test VALUES('1234'); 	--Edit Database Cell in Text Mode shows nothing, reports length of 4
    INSERT INTO test VALUES('abcd');        --shows nothing, reports length of 4
    INSERT INTO test VALUES('2018-01-02');  --shows "-01-02" reports length of 10
    INSERT INTO test VALUES(char(0)||char(1)||char(2)||char(3)||char(61)); --shows "=" reports length of 0
    INSERT INTO test VALUES(char(1)||char(2)||char(3)||char(4)||char(61)); --shows "=" reports length of 5

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ Ubuntu 16.4 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: 117af5ae

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @isrep, that does sound like our recent changes have broken something important. 🤕

**Comment by sky5walk** [comment]
Yes, I see an error also. I'll report on the other issue since it is probably the source.

**Comment by MKleusberg** [comment]
Thanks, @isrep! It's good to see that people are testing the nightlies and pointing out issues 😃 

I think the issue is fixed in the next nightly build. Can you check if it's working in all the cases you pointed out?

**Comment by isrep** [comment]
Thank you for quick fix. With checkin feda40816 all "test rows" seem to be behaving OK.

4th row now reports "BLOB" label, Edit Database Cell returns correct string length and row field seem to be protected aganst data loosing edits. Thanks.

**Comment by MKleusberg** [comment]
Cool, thanks for testing 😃
