### ISSUE TITLE
feature request: right click to delete a row or a column

### ISSUE THREAD

**Issue by WiliTest** [sqlitebrowser/sqlitebrowser#1283]
### Details for the issue

I struggle to find how to delete a row*. It would be intuitive to be able to right click on the row number (in the tab "browse data"), or on the field headings and have an option "delete the column" or "delete the row".

Thanks (in all case!)

* for those who don't know how to delete the column: database structure tab, click on the table, the "modify table" button will be active. Click on it, select the column you need to delete, click on remove field.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Seems reasonable. :smile:

**Comment by mgrojo** [comment]
I've just implemented the "Delete records" in the context menu for the row number (the vertical header).

I have doubts about deleting columns from the "Browse data" tab. In my opinion, all the database structure operations should be on the "Database Structure" tab.

**Comment by justinclift** [comment]
Awesome stuff @mgrojo!

@WiliTest @quole Would you have time to try the nightly build tomorrow, and make sure this works well from your points of view? :smile:

**Comment by chrisjlocke** [comment]
Just a note that the 'delete record' works on the currently selected record, and NOT the record you right click on.  This is different behaviour to the 'Duplicate record' in the same menu.

https://screencast-o-matic.com/watch/cFVhluofSQ

So here, I select the record containing 'Amazon' (row 2) but right click row 7 and select 'Duplicate record'.  Row 7 is duplicated.

However, if I select a cell in row 7, right click row 9 and select 'Delete record', then row 7 disappears.  Makes sense, as that would be what would happen if 'Delete record' is clicked, but its not 'right' from a clicky mousey point of view.

Also (linked to this), if there is no selection, right clicking a row and selecting 'delete record' throws up an error that a record must be selected first.  Again, the 'duplicate record' option doesn't exhibit this behaviour.

**Comment by WiliTest** [comment]
That's perfect for the "delete record"!

I understand that deleting the column in the Browse Data tab isn't a good idea. But that would be great to have the possibility to delete/edit a column by right clicking it in the Database Structure tab.

**Comment by justinclift** [comment]
@chrisjlocke Good catch.  That inconsistency sounds like it'll catch people out.

@mgrojo How easy would it be to adjust, so the record that's right clicked on is the one which gets deleted?

**Comment by mgrojo** [comment]
It is easy if the right click on a row selects that row. I think it makes sense and I've checked that LibreOffice does so.

**Comment by justinclift** [comment]
Cool.  That's probably the right way to go then, as it'll keep consistency with the duplicate record behaviour like @chrisjlocke points out. :smile:

**Comment by mgrojo** [comment]
Done.

**Comment by chrisjlocke** [comment]
> It is easy if the right click on a row selects that row.

Currently right clicking does NOT highlight the row, or move the selection.  
The 'duplicate record' either works on a selection if the mouse is right clicked on a selection, otherwise it uses the row under the mouse.

**Comment by mgrojo** [comment]
@chrisjlocke I know, but it makes sense to highlight the row to which the operations in the context menu will be applied. This is what I've just implemented. Don't you find it better now?

**Comment by chrisjlocke** [comment]
Thanks for making the change.  I'll test the nightlies when they're built tomorrow.

**Comment by mgrojo** [comment]
@chrisjlocke Now you'll have to test also #1090 :smile:

**Comment by chrisjlocke** [comment]
Thanks @mgrojo - the changes work well.

**Comment by justinclift** [comment]
Been thinking over this... I kind of think that being able to right click on a column header and choose "delete column" would be dangerous.  As in potential data loss.

I can easily image new-ish users trying it out, thinking that perhaps it just removes the column from the Browse Data **display** instead of actually nuking it from the table.  On the other hand, we do have the "Revert Changes" thing and require people to commit things before their saved.

Still... I'm kind of inclined to think we should play it safe.  Thoughts? :smile:

**Comment by mgrojo** [comment]
@justinclift I'd go for a context menu with a "Delete field" option when right clicking on the field in the "Database structure" tab. There should be a warning like the one we raise when deleting the field inside the Edit Database dialog.

I don't know that part of the code yet, and haven't found the way at the first sight, but I suppose it shouldn't be too difficult.

**Comment by chrisjlocke** [comment]
>  I'm kind of inclined to think we should play it safe. Thoughts? 

From my point of view, I tend to think that the 'Browse Data' should be just about viewing data, and not manipulating the schema of the database.  Deleting rows is one thing (deleting data) but deleting columns (fields) is twinkling with the data, which should be separate  In my opinion, of course..

**Comment by justinclift** [comment]
> I'd go for a context menu with a "Delete field" option when right clicking on the field in the "Database structure" tab.

If you think it's worth it, then sure.  We already have a right click context menu on the main table entries (eg "Browse Data", "Modify Table", etc), so it'd probably be similar to that.

Thinking about it... it probably wouldn't hurt, and might be useful.  Not sure where the existing code is for deleting fields.  If it's all nicely self contained already and it's just a matter of calling it with the right options, that'd be excellent.  If it's buried inside the modify table code though... not sure.  I can imagine that handling errors (eg violation of foreign key constraints) could be tricky.  But, I have no idea. :smile:

For the request in this issue though - right click column delete in Browse Data tab - it sounds like we're all in agreement that we shouldn't implement that. :smile:

**Comment by MKleusberg** [comment]
I completely agree with @chrisjlocke's argument here and with @justinclift's conclusion. Let's not edit the database schema from a tab which is called "Browsed Data". In a spreadsheet application it makes sense to have both because columns and rows are essentially the same - you could in theory even rotate the table by 90 degrees. In a database I feel like they are too different to be handled in the same way.

As for deleting records by right clicking, that has been implemented by @mgrojo as while ago (right click on the row number, then click "Delete record" in the context menu). Did you had a chance to test that already, @WiliTest? :smile: 

And should we close this issue then?

**Comment by MKleusberg** [comment]
Closing this issue because we haven't heard about any problems with the current solution. If you feel like I have closed this too early, you can always reopen this issue, @WiliTest :smile:
