### ISSUE TITLE
Language keywords should autocomplete to upper case

### ISSUE THREAD

**Issue by fulldecent** [sqlitebrowser/sqlitebrowser#1287]
Test case:

1. Open query editor
2. Type `sel`
3. Wait

Expected result:

Autocomplete suggests `SELECT`.

Actual result:

Autocomplete suggests `select`.

Discussion:

[The SQLite documentation for interpreting SQL](http://www.sqlite.org/lang_expr.html) uses uppercase keywords. So we can assume that is the preferred style.

**Comment by justinclift** [comment]
Thanks @fulldecent.  This seems like a duplicate of #1238. :smile:

**Comment by fulldecent** [comment]
Definitely a dupe, closing.

And also thanks for the fix!
