### ISSUE TITLE
Crashes when try create index for database without tables

### ISSUE THREAD

**Issue by angkastiel** [sqlitebrowser/sqlitebrowser#1293]
### Details for the issue

1) Create new database (File->New Database), type name in save dialog, press 'Save' button.
2) 'Edit table definition' dialog appears. Click on 'Cancel' button.
3) Create index (Edit->Create Index)
4) Application crashes

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 10 x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99 (nightly build at 13 jan 2018)

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @angkastiel.  Well spotted. :smile:

**Comment by MKleusberg** [comment]
Thanks, @angkastiel. The crash should be fixed in the next nightly build. Can you check if it's working for you? :smiley:

**Comment by angkastiel** [comment]
@MKleusberg, i checked nightly build at 16 jan 2018. The application no longer crashes. Thanks! 😄

**Comment by justinclift** [comment]
Excellent.  Thanks for verifying @angkastiel. smile:
