### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by dnit11** [sqlitebrowser/sqlitebrowser#1294]
sqlitebrowser-master\src\sqlite.h:13:25: fatal error: sqlite3.h: No such file or directory

**Comment by glawrence** [comment]
Could you provide a little more detail please? Like which operating system are you using, which build process etc. However as a first step, take a look at https://github.com/sqlitebrowser/sqlitebrowser/wiki and follow the steps carefully. If you still have a problem then add some details and the team will try to help.

**Comment by justinclift** [comment]
Looking at the directory slashes (`\`), it seems like Windows.

So... it's probably a case of [SQLite not being in the expected directory](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-—-Step-8-—-Install-SQLite).

If that's the case, the directory path can be changed here:

* [32-bit](https://github.com/sqlitebrowser/sqlitebrowser/blob/efb32857d6336116867d1214ba756ae2f744742e/CMakeLists.txt#L42)
* [64-bit](https://github.com/sqlitebrowser/sqlitebrowser/blob/efb32857d6336116867d1214ba756ae2f744742e/CMakeLists.txt#L29)

Hopefully that helps. :smile:

**Comment by karim** [comment]
Closed due to lack of response.
