### ISSUE TITLE
FK error in 3.10.1

### ISSUE THREAD

**Issue by shlst** [sqlitebrowser/sqlitebrowser#1295]
### Details for the issue

1) Create DB table (TABLE1) having FK to table, where corresponding parent records has only non-zero (integer) values
2) Try to add new record to TABLE1. DB Browser tries to add record with FK value == 0. It does not show record for edit, but shows error like 'missing FK'. This issue is missing in 3.9.1.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version: Win 10 x64  Pro)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by shlst** [comment]
Hm, I have reinstalled it to 3.9.1 and back to 3.10.1. and now this issue is missing in 3.10.1.

**Comment by justinclift** [comment]
No worries @shlst.  If the behaviour starts up again, you're welcome to reopen this issue or create a new one.

But, try it with our latest nightly builds (in that case), as we're getting close-ish to our next release. :smile:
