### ISSUE TITLE
Open DB-Close DB-Open DB creates multiple SQL 1 tabs.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1296]
### Details for the issue
Small bug. 
Doing "Open DB-Close DB-Open DB" creates multiple "SQL 1" tabs in the Execute SQL panel.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Duplicate of #1163?

**Comment by sky5walk** [comment]
Sorry.

**Comment by justinclift** [comment]
No worries at all @sky5walk.  We've all missed previous bug reports on occasion.  There's more then a few there. :wink:
