### ISSUE TITLE
Preserve format in Copy Create Statement

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#1300]
### Details for the issue

When using `Copy Create Statement` and copying the statement in the SQL tab, the statement results in one long single line without multiple spaces, tabs and newlines.
```
CREATE VIEW equityExclAccounts as WITH recursive assets AS ( SELECT * FROM category ca WHERE type IN ('ASSETS', 'LIABILITIES') UNION SELECT ca.* FROM category ca JOIN assets a on a.id = ca.parentId WHERE ca.type != 'ACCOUNT' ) SELECT * FROM assets
```
When exporting the schema of a table/view, the schema preserves the newlines.

```
DROP VIEW IF EXISTS `equityExclAccounts`;
CREATE VIEW equityExclAccounts as 
WITH recursive assets AS 
( 
SELECT * 
FROM category ca 
WHERE type IN ('ASSETS', 'LIABILITIES')

UNION 

SELECT ca.* 
FROM category ca 
JOIN assets a on a.id = ca.parentId 
WHERE ca.type != 'ACCOUNT' 
) 
SELECT * FROM assets;
COMMIT;
```

**Enhancement request**:
Could newlines be preserved in `Copy Create Statement` too? And maybe tabs and spaces also?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: 
#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
@pamtbaau This was easy to improve :smiley: Could you check it the next nightly build?

**Comment by pamtbaau** [comment]
Why oh why haven't I requested this before... 🤦‍♂️  Thanks a lot, this save me a lot of formatting!

**Comment by justinclift** [comment]
@pamtbaau Cool.  All good, and ok to close this now? :smile:

**Comment by pamtbaau** [comment]
Sure, this issue can be closed.

**Comment by justinclift** [comment]
Awesome. :smile:
