### ISSUE TITLE
Re-ordering Rows after insert

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1301]
### Details for the issue

I know this isn't an issue when working with an SQLite database, however in the UI it's really annoying that I can't re-order rows. Say i insert a new row but it belongs in a certain point in the ordering, is it not possible to move it (the insert) ?

#### I'm opening this issue because:

DB4S needs a feature

#### I'm using DB4S on:
Linux: ( Ubuntu )

#### I'm using DB4S version:

3.10.1

**Comment by sky5walk** [comment]
DB4S is a relational database browser/editor.
Depending on your table schema, you could "reorder rows" by editing their _rowid_ and/or primary key after insertion. You can also execute SQL that returns the order you want.
Are you asking for this to happen via "drag and drop"?

**Comment by chrisjlocke** [comment]
This question occurs frequently on the SQLite discussion group.  I can only imagine people are so used to working with data/tables in Excel that they want to 'replicate' that in a database.

Your records should (if needed) have a sort order, eg, date, or 'orderBy' column, so when adding a row, you set this data accordingly.  Yes, it'll now appear at the bottom, but refresh the data and DB Browser will display the data in the required sort order.

I've probably explained this badly, but can add a screencast if thats easier.

**Comment by justinclift** [comment]
@shaun-ba Interestingly, your question about how to insert rows is similar to another issue (#830) a while back.

With SQL databases (like us) the order which rows are displayed in isn't guaranteed **unless** you tell it a column to sort by.  eg sort by "price" or "date" (if you had columns called that).

In the Browse Data tab of our GUI, you can click on a column heading to get the order sorted by that column.  If you don't click on any column, then the GUI just shows you the order as it receives them from the database (unsorted).  That can change any time, so using a column to define the order is really how to want to go.

As background info, this might be useful:

&nbsp; &nbsp; https://www.w3schools.com/sql/sql_orderby.asp

Reading through the more in-depth explanation in #830 might help too, so you get a better idea of what's going on and how to make it work well for you. :smile:

**Comment by mgrojo** [comment]
Apart from the already said, when you insert add a new record, it is first added after the last row in the table with default values (NULL if default value not defined in the table definition). In the case that you have defined a sort column (using the column header) and you fill the value for that new row and column, the row is not automatically reordered. The same happens when you edit a value in this sort column. The solution is requesting manually again the ordering by this column, then the new/modified row is moved to its proper location. Is that what you actually meant, @shaun-ba ? That it should be automatically moved to its ordered position? I'm not sure, though, that the automatic ordering would be always welcome since it could be a bit distracting.

By the way, I take this opportunity to mention that once you have set a sort column, you cannot restore the original unsorted state of the table. Maybe there should be a way through the context menu of the header or through a third click on the column header.

**Comment by justinclift** [comment]
Hmmm, the "third click to unset the sort order" approach seems like it'd be fairly natural.

**Comment by shaun-ba** [comment]
Hi sorry for the long reply and thanks for all the comments.

Yes, I was simply looking for a way to insert a row at a certain place, because as you all say a newly inserted row hits the bottom.

I have used the sort column to do this, I am databasing some coins and they have dates, but also have a numbering system that unfortunately isn't numerical. This results in the inability to add a new row (for a new coin), and sort it so that the date and reference are in the correct place.

I understand that this may just be the way things are, but thought i'd ask :)

**Comment by justinclift** [comment]
No worries.  Could you add a new column (numbering system) to make them appear in the order you want?

If you do it something like this, with spaces between the numbers ...

pos | name
--- | ---
100 | foo
200 | bar
300 | baz

...it gives you room to insert things later:

pos | name
--- | ---
100 | foo
150 | Some new row here
200 | bar
300 | baz

**Comment by shaun-ba** [comment]
Would i then be able to sort by two rows in the UI?

My numbering system is quite simple, 100, 101, 102, 102A, 102B, 103, 104, 104A, 104B, 104C  ....

**Comment by justinclift** [comment]
Not easily at the moment.  Our "click on a column header to sort using it" only works for single columns for now. :smile:

**Comment by sky5walk** [comment]
> @mgrojo - "By the way, I take this opportunity to mention that once you have set a sort column, you cannot restore the original unsorted state of the table. Maybe there should be a way through the context menu of the header or through a third click on the column header."

Yes, to get back to original sort, RM Click the column headers and show \_rowid_.
Then sort \_rowid_ ascending.

**Comment by justinclift** [comment]
@shaun-ba How'd you go with this?  Kind of wondering if we're ok to close this issue, as there's not really much we can do on our end. :smile:

**Comment by shaun-ba** [comment]
Hey, it seems unrelated, or at least it's not a bug :)

However, you could add support to sort by multiple columns in future ;)

**Comment by chrisjlocke** [comment]
Obviously you can sort by multiple columns on the 'execute sql' tab, which also supports data editing...

**Comment by justinclift** [comment]
Thanks @shaun-ba. :smile:

**Comment by wlwl2** [comment]
> This question occurs frequently on the SQLite discussion group. I can only imagine people are so used to working with data/tables in Excel that they want to 'replicate' that in a database.
> 
> Your records should (if needed) have a sort order, eg, date, or 'orderBy' column, so when adding a row, you set this data accordingly. Yes, it'll now appear at the bottom, but refresh the data and DB Browser will display the data in the required sort order.
> 
> I've probably explained this badly, but can add a screencast if thats easier.

This reply solved it for me. Thanks @chrisjlocke!
