### ISSUE TITLE
Window refuses to be minmized

### ISSUE THREAD

**Issue by thejeswi** [sqlitebrowser/sqlitebrowser#1308]
### Details for the issue
When SQLitebrowser is open, no other window (of another application) can float on top. Moving to another workspace causes a jump back to the workspace with the SQLitebrowser. I have tried using apt purge and reinstalling, that doesn't help.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:Ubuntu 17.10 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [* ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh yeah.  This was a problem in the way we were doing some window operations.  It was fixed after our last release, so if you're ok to use the nightly builds (instructions are on our front page) that **should** solve the problem.  If it doesn't though, we'll need to investigate further.

Does that help? :smile:

**Comment by justinclift** [comment]
Aha, found the previous report for this: #934, in case that's useful. :smile:

**Comment by thejeswi** [comment]
This fixes the issue! Thank you for the quick response! 
Please add this fix to the next stable version.

**Comment by justinclift** [comment]
You're welcome @thejeswi.  And yep, it'll definitely be in our next stable release. :smile:
