### ISSUE TITLE
Font size too small in log part of "Execute SQL" tab [minor annoyance]

### ISSUE THREAD

**Issue by elton12345** [sqlitebrowser/sqlitebrowser#131]
It's simply too small to read - but I can copy the text and view it in the Mac clipboard.
![bildschirmfoto 2014-10-15 um 17 02 16](https://cloud.githubusercontent.com/assets/9253552/4647579/53044ab6-547c-11e4-963f-a8d30b1c88b8.png)

**Comment by kenenbek** [comment]
![image](https://user-images.githubusercontent.com/15985969/52870840-ce081f80-3159-11e9-989f-f4c8173e96d4.png)

How to increase a font in the selected area?

**Comment by MKleusberg** [comment]
@kenenbek It should be the 'Font size' field in the Data Browser tab. I just tried it here and it worked. Which version are you using? Maybe we changed that a while ago?

**Comment by kenenbek** [comment]
@MKleusberg I tried it again, but nothing happened.
My version is:
Version 3.10.1
Qt Version 5.7.1
SQLCipher Version 3.15.2

**Comment by chrisjlocke** [comment]
v3.10.1 is over a year old.  Have you tried the v3.11 beta at all?  
https://sqlitebrowser.org/blog/third-beta-release-of-3-11-0y/

I don't know what operating system you're using though.

**Comment by MKleusberg** [comment]
@kenenbek I've looked this up. In version 3.10.1 there is no way to change the font size in the query result view. We added this for version 3.11.0. [Here](8687bfa3c36ec55889b41c67d6ccce94239df55a)'s the commit, #1240 is the corresponding issue. On the screenshot it looks like you're using Linux. What distribution are you using? We can then check how to update DB4S to version 3.11.0.

**Comment by kenenbek** [comment]
the screenshot was from ubuntu 18.04. 
but on mac os (10.14.3) SQLite browser (which version I sent) have the same issue.

But I updated to 3.11 and it works!!!

**Comment by MKleusberg** [comment]
Awesome :smile: Glad it works now!
