### ISSUE TITLE
Table filter enhancement

### ISSUE THREAD

**Issue by kwoodham** [sqlitebrowser/sqlitebrowser#1312]
### Details for the issue

This may go under "enhancement", but I think it's important to have...  I have a table of members of an organization that includes a gender column - I want to filter this on "Male" - but no records are filtered out because the same string is found in "Female" - so perhaps a case sensitive filter option would be helpful.  Of course a great capability would be to use regex in the filter, but this might be overkill.

I understand that I can revise my SQL statement to include gender, so this isn't a huge issue.

Thanks for a great product!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
If you put the filter as '=Male', that would filter out specifically just the males.

![image](https://user-images.githubusercontent.com/7872218/35687738-6938b780-0767-11e8-9bcb-eb1ac1c392d8.png)

![image](https://user-images.githubusercontent.com/7872218/35687762-77d3287a-0767-11e8-8a99-389321c73b1f.png)

Note however, that in this mode, the filter is case sensitive, so '=male' will not work.

![image](https://user-images.githubusercontent.com/7872218/35687803-93379e70-0767-11e8-8b78-d5deb3466c2a.png)

Specific matches are mentioned in the [wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters), but if you think it needs to be more obvious, let me know, and it can be changed.  :)

**Comment by chrisjlocke** [comment]
To search for males, you could also filter for 'm%'.  The '%' is a wildcard (for 'anything') so 'm%' means 'starts with m, then has anything'.  Note that using wildcards doesn't affect the case-sensitivity switch, so its not case sensitive.

**Comment by chrisjlocke** [comment]
I'll close this, but keep the 'the filters needs regex support!' under your hat, as thats a good suggestion...

**Comment by kwoodham** [comment]
Thanks @chrisjlocke  - didn't realize the wiki was there for documentation, and the "=" exact match works great.  Appreciate you taking the time to help me out.

**Comment by mgrojo** [comment]
@kwoodham In the next version you will be able of selecting a cell and using its value as exact match filter with the right-click context menu ("Use as filter"). That is a way to do quick filtering. If you'd like to try: https://nightlies.sqlitebrowser.org/latest/

This issue shows that the full possibilities of the filter are not obvious. I've thought sometimes to implement a filter dialog, that when applied, would appropriately fill the filter header. That would also be a way of discovering the possibilities of the filter header.

**Comment by justinclift** [comment]
> I've thought sometimes to implement a filter dialog, that when applied, would appropriately fill the filter header. That would also be a way of discovering the possibilities of the filter header.

Good thinking. :smile:
