### ISSUE TITLE
Update sqlite3 to latest build

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#1313]
Very similar to #1304...

sqlite3 was released on the 22nd of January:
https://www.sqlite.org/releaselog/3_22_0.html

Latest build of the browser is using build 3.21.0.

By the way, thanks for adding the date to the version in the about section.

**Comment by justinclift** [comment]
Thanks for the pointer!  Just updated the Windows build server with 3.22.0, and manually launched the nightly build script.   It'll replace today's nightlies in ~30-40 minutes.

> By the way, thanks for adding the date to the version in the about section.

You're welcome.  Very much agree btw, it's turned out to be really useful. :smile:

**Comment by justinclift** [comment]
The OSX build is using 3.22.0 already, as we use the OSX Homebrew version and pull it down freshly each night: :smile:

&nbsp; &nbsp; https://github.com/Homebrew/homebrew-core/blob/master/Formula/sqlite.rb

![screen shot 2018-02-01 at 21 25 45](https://user-images.githubusercontent.com/406299/35704195-91e6a406-0796-11e8-9f5a-270eb6fbf3c7.png)

**Comment by justinclift** [comment]
The updated windows nightlies are now online, using 3.22.0.

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Seems to be working ok here in very cursory testing. :smile:

**Comment by jungle-boogie** [comment]
Thanks for updating it!
