### ISSUE TITLE
How to open in-memory database using Browser?

### ISSUE THREAD

**Issue by viveknuna** [sqlitebrowser/sqlitebrowser#1319]
Hi, 
I'm running some test cases using XUnit in Asp.Net Core project. Its creating/updating/deleting records using in memory database. How can I open in-memory database to view tables and records using Browser. Please find the below code for your reference.

```
public static void Register(IIocManager iocManager)
{
	RegisterIdentity(iocManager);

	var builder = new DbContextOptionsBuilder<MyCompanyDbContext>();

	var inMemorySqlite = new SqliteConnection("Data Source=:memory:");
	builder.UseSqlite(inMemorySqlite);

	inMemorySqlite.Open();

	iocManager.IocContainer.Register(
		Component
			.For<DbContextOptions<MyCompanyDbContext>>()
			.Instance(builder.Options)
			.LifestyleSingleton()
	);

	new MyCompanyDbContext(builder.Options).Database.EnsureCreated();
}
```

I have tried to run these test cases on local DB, It creates a file  **MyLocalDb** and I can open this local database using browser.

**Code for local DB:**

```
public static void Register(IIocManager iocManager)
{
	RegisterIdentity(iocManager);

	var builder = new DbContextOptionsBuilder<MyProjectDbContext>();

	//var inMemorySqlite = new SqliteConnection("Data Source=:memory:");
	//builder.UseSqlite(inMemorySqlite);

	var connectionString = "Data Source=MyLocalDb.db"; //use actual path
	builder.UseSqlite(connectionString);

	//inMemorySqlite.Open();

	iocManager.IocContainer.Register(
		Component
			.For<DbContextOptions<MyProjectDbContext>>()
			.Instance(builder.Options)
			.LifestyleSingleton()
	);

	new MyProjectDbContext(builder.Options).Database.EnsureCreated();
}
```

**Version** 3.10.1

**Qt Version** 5.7.1

**SQLCipher Version** 3.15.2

**Comment by justinclift** [comment]
Reading through this a few times, it's not 100% clear to me if you're trying to create a brand new in-memory SQLite database with our GUI, or if you're trying to access the in-memory database(s) created by the test cases. :wink:

If it's the second one, and you're trying to access the in-memory databases created by the test cases... that's not going to work.  In-memory databases are created per running process, and can't be shared between running applications.  More info [here](https://www.sqlite.org/inmemorydb.html) if that helps. :smile:

**Comment by justinclift** [comment]
Closing this, as it's ancient and there's nothing we can really do for it. :smile:
