### ISSUE TITLE
JSON table export converts integer and null values to string

### ISSUE THREAD

**Issue by geoffblack** [sqlitebrowser/sqlitebrowser#1323]
### Details for the issue
JSON table export does not take into account the column data type when exporting, and you end up with all strings in the exported data, which is incorrect.

Given the following table structure:
```
CREATE TABLE "JsonTest" (
	id INTEGER NOT NULL, 
	size BIGINT, 
	flag VARCHAR, 
	PRIMARY KEY (id)
)
```
and the following row data:
```
(1, NULL, "Yes")
```
The expected output of `File`->`Export`->`Table(s) to JSON...` should contain a JSON record such as this:
```
    {
        "id": 1,
        "size": null,
        "flag": "Yes"
    }
```
but instead, it produces this:
```
    {
        "id": "1",
        "size": "",
        "flag": "Yes"
    }
```

#### I'm opening this issue because:

- [X] DB4S has a bug

#### I'm using DB4S on:

- [X] Windows: ( _version:_ 64-bit )

#### I'm using DB4S version:

- [X] 3.10.1

#### I have also:

- [X] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
I'd regard it as a limitation, not as a bug :smile: Nevertheless, I think it could be improved.

**Comment by mgrojo** [comment]
From:

Id | Name | Age | Height
-- | -- | -- | --
11111111111 | Ray | 40 | 1.79
22222222222 | Bob | 20 | 1.71
33333333333 | Pierce | 30 |  

to:

```json
[
    {
        "Age": 40,
        "Height": 1.79,
        "Id": 11111111111,
        "Name": "Ray"
    },
    {
        "Age": 20,
        "Height": 1.71,
        "Id": 22222222222,
        "Name": "Bob"
    },
    {
        "Age": 30,
        "Height": null,
        "Id": 33333333333,
        "Name": "Pierce"
    }
]
```

@geoffblack Would you have some time to try our next nightly build and report if everything works as expected? The new version will be available from 5 AM (UTC).

**Comment by geoffblack** [comment]
Just tested. Looks great, thank you!

**Comment by mgrojo** [comment]
Cool! Let's close this now but don't doubt about reopening it if there is any pending related issue.
