### ISSUE TITLE
An option to switch into a Dark theme would be very useful

### ISSUE THREAD

**Issue by m4heshd** [sqlitebrowser/sqlitebrowser#1324]
### Details for the issue
In my experience most of the developers are night owls and keep looking at screens for about 16 hours a day. In my case i have a 2nd monitor where i have **sqlitebrowser** open pretty much all the time. Since i have to look at the light colored window all the the time it makes my eyes hurt in a little while. I use this tool a lot. So it would be amazing if it's possible to switch to a Dark theme. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
As a thought, it seems like windows can set any application to a dark theme:

&nbsp; &nbsp; http://troubleshooter.xyz/wiki/enable-dark-theme-for-every-application-in-windows-10/

The "Enable a Dark Theme for Windows Desktop Applications" section on that page shows how.  I just did similar for a Windows 7 desktop here to try it, and it seems to work. :smile:

**Comment by m4heshd** [comment]
Hi Justin. The problem is only method that works with DB4S is if you change the default Windows colors which ruins the experience of windows.  I'm already using windows Dark mode and tried all of these before. I've even tried better ones like this. 

- https://eversins.deviantart.com/art/GreyEveTheme-FINAL-Windows-10-High-Contrast-Theme-643504863

DB4S looks like this when i use the above theme which is OK but not perfect. Lots of missing texts and random white backgrounds. 

![image](https://user-images.githubusercontent.com/6711514/36507327-5347e0b8-177f-11e8-91b3-1e7f02daf665.png)

Also this messes up all other applications. It'll be really good if there's a native option for the theme in the app.

**Comment by justinclift** [comment]
No worries, that definitely makes sense.  To me anyway. :smile:

**Comment by m4heshd** [comment]
Thank you for understanding.

**Comment by mgrojo** [comment]
@m4heshd  I've implemented a series of changes for a better support of operating system dark themes. If there aren't any saved settings the default colours adjust automatically to the light or dark system theme.

Would you have some time to test it in our next nightly build? https://nightlies.sqlitebrowser.org/latest/
Be sure to restore the default preferences using the new button for that purpose before taking into 
account the changes or after having changed the system theme.

Your test would be specially needed since I use Ubuntu Linux and this might be very system dependent. This is an example using the Arc-dark theme in Ubuntu:
![imagen](https://user-images.githubusercontent.com/13812910/36644912-59921080-1a61-11e8-8ea2-74ef388cdf4f.png)

**Comment by justinclift** [comment]
Oooooooo Aaaaaaaaaa.... just tried it out with KDE (4.x) on my CentOS 7 desktop:

![db4s-kde-dark_theme1](https://user-images.githubusercontent.com/406299/36645407-045d68d6-1a60-11e8-997b-a44d6b9527de.png)

This looks pretty good @mgrojo. :grin:

Haven't actually played around with KDE themes before... might stick with this dark one for a while, as I was getting kind of sick of the previous KDE look. :wink:

@m4heshd The button mentioned by @mgrojo is the new "Restore Defaults" button in the Preferences dialog.  It's in the bottom left, on the same level as the Save and Cancel buttons. :smile:

**Comment by m4heshd** [comment]
Thank you for the update. Tested it out and gotta say it looks really good. The Table component still has a white bg and i understand why that's happening. Overall it looks like this.

![image](https://user-images.githubusercontent.com/6711514/36646020-d81d166c-1a97-11e8-82b1-1efea47505c5.png)

**Comment by justinclift** [comment]
@m4heshd Just to check, did you compile it yourself or did you download from our nightly builds server?

If it's the download from the nightly build server, then that only gets updated once per day (~5am UTC), so it won't have @mgrojo's changes in it yet. :wink:

**Comment by m4heshd** [comment]
Oops.. My bad. 😁

**Comment by justinclift** [comment]
Hmmm, once the nightly builds are ready + known to work on Windows, it's probably worth mentioning this Dark Theme support on Twitter.  I'll get it that done tomorrow sometime. :smile:

**Comment by m4heshd** [comment]
Haha i was waiting to go scream on Twitter because at first i request this feature on Twitter.  Then i was advised to open the issue. Too lazy to compile. Waiting for the package 😸

**Comment by justinclift** [comment]
Heh Heh Heh

k, I've just manually started the Windows nightly build script.  In roughly 30-40 minutes, updates builds will be on the nightly server.   You'll want to check the date stamp first before downloading, just to make sure. :wink:

**Comment by m4heshd** [comment]
Yes i was checking that and also cleared the cache to make sure.

**Comment by justinclift** [comment]
Sorry for the delay with this.  The nightly build script compiled things fine, but the automatic upload failed.  I've just manually uploaded the nightly builds now.

**Comment by m4heshd** [comment]
Yup i saw just got updated. Thank you for going for a lot of trouble.

**Comment by m4heshd** [comment]
Everything seems to be looking good. Colored texts are bright and all the backgrounds are dark. Thanks. ☺

![image](https://user-images.githubusercontent.com/6711514/36651348-85b369c6-1ace-11e8-9730-6ac1ab0fc29b.png)

**Comment by justinclift** [comment]
Awesome.  I'll make a Twitter post about it now.  Is it ok to use your screenshot in the Twitter post? (me being lazy here)

**Comment by justinclift** [comment]
Meh, I used all three of our screenshots.  So, Ubuntu, CentOS, and Windows. :smile:

**Comment by m4heshd** [comment]
Everything's perfect. I wish i could get into to Qt right now. I'm a huge GUI nerd even though i'm not any kind of a UI specialist. But i got my hands full with trying to migrate all of my Java Swing GUI apps to ElectronJS. Definitely going to get my hands on with Qt when this framework war is done. 😥

**Comment by mgrojo** [comment]
You're welcome @m4heshd. Now I'm using a dark theme for my desktop too :smile:

**Comment by epistemex** [comment]
wait.. this means it won't work on Windows 8.1? :-o Looks great btw :)

**Comment by justinclift** [comment]
Errr... it worked on Win7 when I tested it.  Kind of thinking it should work on Win 8.1 too.

You do need to click the "Restore Defaults" button (bottom left) in the Preferences dialog though, to get it to use the new theme.

**Comment by epistemex** [comment]
Sorry, I did (+restart) but still no change. :( But I'll look closer into it tomorrow as I'm probably not in a state to dig closer into it right now.

**Comment by m4heshd** [comment]
Worked for me on Win 10. Remember it needs a system wide theme for this to work. Not sure if the functionality will remain after Redstone 5.

**Comment by Atralb** [comment]
So, this feature can only adapt to a system theme ? There isn't any choice inside SQLiteBrowser to set which theme you want to use on the fly ?

**Comment by mgrojo** [comment]
Both modes are present: "Follow the desktop mode" and "Dark style". Look at Preferences > General > Application Style.
