### ISSUE TITLE
Is there any extension?

### ISSUE THREAD

**Issue by hubuga** [sqlitebrowser/sqlitebrowser#1325]
I tried to find an extension to download and I couldn't find anywhere.

**Comment by justinclift** [comment]
@hubuga Are you looking for any specific extension, or just "anything" in order to try stuff out?

The SpatiaLite extension is known to work.  There are two approaches for installing it written up:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows

The 2nd one (linked at the bottom) has screenshots showing how to do it, if that helps. :smile:

**Comment by hubuga** [comment]
I'm just trying stuff out, in order to understand better how the software works and so on. That is the good side about open source softwares, maybe I could help after I understand I few things.

**Comment by justinclift** [comment]
Well, that seems to be the main one people talk about. :smile:

SQLite itself has some extensions (JSON1, FTS, and more) but we include them already so they don't need separate installing.  Um... it's possible to write your own too, but it's not something I personally have tried.  There's some more info about SQLite extensions in general here if it's useful: :wink:

&nbsp; &nbsp; https://sqlite.org/loadext.html

**Comment by jungle-boogie** [comment]
@hubuga, to know which extension to load, you need to know what you want to accomplish. Loading extensions just to load extensions doesn't make sense to me.

**Comment by justinclift** [comment]
Well, if someone's just mucking around with DB4S to learn how it does things... we don't really have a list of extensions readily at hand for people to try out.  The SpatiaLite one is probably the main one. :smile:

**Comment by MKleusberg** [comment]
Just to make sure there is no confusion - but you probably all know already :wink: The extensions are all extensions for SQLite in general and not for DB4S specifically. So if you want to search for extensions, the search phrase should be "sqlite extension". This also means the extensions are just going to extend the functionality of SQLite by adding new SQL functions, new virtual tables, etc. They are all only accessible through the Execute SQL tab. No extension will add new menu options or similar.

**Comment by MKleusberg** [comment]
[Here](https://sqlite.org/contrib/download/extension-functions.c?get=25) is one fairly popular extension which you need to compile yourself though. It adds many maths and string functions to the query language. Whether you compile it or now, the comments at the top of the file should give you an idea what extensions can do.

**Comment by hubuga** [comment]
Sorry for the delay and the extensions I meant wans't for SQLite but for DB Browser itself, in the configuration settings has an extension tab where you can select dlls.
I'm coding with Qt for a while and I'm currently trying to understand how to plugin system works and I saw that DB Browser implements it somehow and I wanted to understand how so I could help here maybe with something but I couldn't find any extension to import there.

**Comment by justinclift** [comment]
Ahhh yeah.   We don't have extensions for DB4S yet ourselves either.  The extensions there are for SQLite ones. :smile:

**Comment by justinclift** [comment]
Going to close this issue, as there doesn't seem to be anything we need to actively do. :smile:
