### ISSUE TITLE
Refresh database without clicking the button.

### ISSUE THREAD

**Issue by sidjoshi9** [sqlitebrowser/sqlitebrowser#1327]
I'm inserting some values into database using python. I want database to be refreshed automatically without clicking Refresh Button.
Is it possible ??

Thanks in advance. :100:

**Comment by chrisjlocke** [comment]
Theres no automatic timer event which presses 'Refresh' for you, unfortunately.  If you happen to know how to program, you're more than welcome to submit a PR with the necessary code! ;)

Depending on your operating system, there are applications which 'push buttons' for you though, such as https://www.jitbit.com/macro-recorder/ (note thats not a free option - just the first one I found - but there are free alternatives).  Depends on your operating system though, which I don't know...

**Comment by chrisjlocke** [comment]
I'll close this as its not an issue which can be immediately resolved, but will add the 'enhancement' label, so when we're bored, we can come back to it.  👍

**Comment by MKleusberg** [comment]
This is actually more difficult than it looks like. When pressing the refresh button the tables is scrolled back to the first row. Ff that happens periodically it would be pretty annoying, so we would need to change that scrolling first...

**Comment by justinclift** [comment]
Hmmm, I wonder if we could use something like the SQLite3 [sqlite3_total_changes()](https://sqlite.org/c3ref/total_changes.html) functions to detect when the database has been altered?

If we keep a running count of the figure returned from that in memory, and poll the database every n seconds, we should be able to determine when data has been changed.

Of course, we'd also want to hold the same position any table being viewed by the Browse Data tab too as @MKleusberg mentions.  That bit doesn't sound too hard at first thought.  We'd need to read the current table row the Browse Data tab is up to, refresh the data, then reposition back to the "same row" if it still exists.  "Same row" might be a bit of a loose definition though.  eg exact row number? Same % of the way through the table?

**Comment by MKleusberg** [comment]
I think it's still more difficult than that :wink:
```sqlite3_total_changes()``` will only work for the current database connection. That means if the database is changed from another program, we can't notice that. It also doesn't report schema changes.
The ```data_version``` pragma however indeed seems like a pretty good way to detect changes. But we would still need to figure out what the current row is that we need to return to, what to do if the user is in another tab (like the Execute SQL tab) or if the user is editing some row, when/how often to check for changed data versions etc.
