### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by JGriffin34432** [sqlitebrowser/sqlitebrowser#1328]
### Details for the issue

Adding an updater in the program so when updates are released they don't have to go onto the web to check for updates. Then can just do it from the program itself.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: Windows 10 Home Insider Preview Build 17074.rs_prerelease_flr.180116-1539 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yeah, it's a decent idea and a few people have asked for this already.

It needs to be done for each OS specifically, as the OSX update mechanism would be different from the Windows one (etc).  I'll probably happen at some point, we just need someone feeling enthusiastic about implementing it... to get it done. :smile:

**Comment by glawrence** [comment]
Justin, what is your thinking on this? Do we need one "solution" that works cross platform, or three different solutions that work on each platform. Just asking as in theory http://wingup.org/ by Don Ho and as used by Notepad++ should cover Windows. I guess the interesting approach or product to examine would be Firefox, as my Windows machines and Mac update in a similar way.

**Comment by justinclift** [comment]
Yeah, I'm not 100% sure on the way to go.  For Linux, the OS packaging itself takes care of updating OS supplied packages.  For Windows and OSX though, most people download our provided packages.

There is the PortableApp version on Windows too, which also auto-updates (after prompting the user).

Whatever approach(es) we do go with, we'll just need to make sure they don't muck with any OS provided or PortableApp versioning thing.  Not expecting that side of things to be a challenge.

For the packaging approaches themselves... I'm kind of thinking this is just a manpower problem.  It's just something that needs someone with an interest in it to pick the task up and starting trying things out + see what works.  If we figure out a solution that works just for (say) only Windows or only OSX first, that's still a win that moves us forward. We don't have to achieve a perfect solution on the first try. :smile:

**Comment by MKleusberg** [comment]
If we want to have an updater (for Windows, that is), an external one is probably the right approach. So @glawrence's suggestion about WinGUp sounds like a good idea.

The problem with writing one by ourselves is that it is actually quite complicated to do right and especially difficult to test. The real issue is making sure the updater cannot be turned into a malware deployer by some man-in-the-middle etc. because that would be bad publicity :wink:
