### ISSUE TITLE
"Modify View" always dimmed

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#1329]
### Details for the issue
Using 3.10.1 on macOS 10.12.6...

I click on one of the views in the Database Structure tab. The view is:
`CREATE VIEW "YTD" AS SELECT * FROM reservations where resdate < "2018-02-01" and staydate >= "2018-01-01" and staydate <= "2018-12-31"`

I would like to be able to alter one of the parameters, say one of the dates. I see a "Modify view" button (next to Create Table, Create Index, etc.) but it is dimmed. 

How can I modify that view to use a different value (date)?  Thanks!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, it kind of sounds like there's a bug, and that the "Modify View" option shouldn't be dimmed.

That being said... we've only really started adding support for views in the last release or two (from rough memory).   It's possible we've just not yet implemented modifying views yet.

Hmmm, would you be up for trying our latest nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

(either of the .dmg there, just pick one with or without encryption support as needed)

Suggesting that because we're getting reasonably close to making a new release, so all of the improvments and changes since the v3.10.1 that you're using will be in it.  There's a decent chance
that our view handling code has been tweaked and adjusted since, so you might be in luck. :smile:

**Comment by richb-hanover** [comment]
Thanks for the speedy response. I did try the latest (Version 3.10.99 (Feb 25 2018)), and here's what I saw:

I opened my database, and could see the the tables & views. (see screen shot below).

Click/select a table and all four buttons are enabled: Create Table, Create Index, Modify Table, Delete Table.

Click/Select a view, and three of the four buttons are enabled - the one that's dimmed is "Modify View" Note, too, that the dropdown has that menu item dimmed as well.

Please let me know if I can provide further info. Thanks.
![db browser-modify view dimmed](https://user-images.githubusercontent.com/1094930/36646013-af21781e-1a3f-11e8-8287-e0339304c7cd.png)

**Comment by justinclift** [comment]
Thanks @richb-hanover.  Sounds like we haven't yet gotten the view modifying code in place then.

You'll probably need to recreate the view(s) manually then for now.  i.e. Copy the `CREATE VIEW ...` statements to the Execute SQL tab + modify them as needed before running.

Not a fantastic approach, but it should work.  In theory. :smile:

**Comment by richb-hanover** [comment]
Great, thanks! I wanted to be sure I wasn't doing anything stupid/wrong.

**Comment by richb-hanover** [comment]
One more thought - here's an (empty) database that you can use for testing the Modify View. 

Thanks!
[Empty DB with View for DB Browser.sqlite.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/1758569/Empty.DB.with.View.for.DB.Browser.sqlite.zip)

**Comment by chrisjlocke** [comment]
Closing this as the original query has been answered (sort of).
Views is something still in development, so the editing of them should hopefully get implemented at some point.

**Comment by mbronstein** [comment]
Recreating view didnt work for me until  I added "DROP VIEW x;" at beginning of query.

**Comment by contributorpw** [comment]
OK. I had version 3.11.2. For my Ubuntu the ppa solves the problem to update to 3.12

```sh
$> sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser
```

**Comment by richb-hanover** [comment]
Yes, the Modify View command is now enabled, and it allows me to drop the view and replace it as desired (Tested with the Empty DB with View for DB Browser.sqlite.zip above.)

Thanks!

**Comment by justinclift** [comment]
Awesome. :smile:
