### ISSUE TITLE
Open file Error

### ISSUE THREAD

**Issue by gswcodeshow** [sqlitebrowser/sqlitebrowser#1330]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by gswcodeshow** [comment]
![f25e2 yr q 3qyvd3q472g](https://user-images.githubusercontent.com/25546052/36661536-7550f934-1b16-11e8-9807-41eab066a349.png)

**Comment by gswcodeshow** [comment]
[targetfile.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/1757803/targetfile.zip)

**Comment by justinclift** [comment]
Hmm, is anyone around who can translate that error message to English? :smile:

**Comment by chrisjlocke** [comment]
The posted database fails to open (disk image malformed) so might be that?

**Comment by chrisjlocke** [comment]
I've Project Naptha (cool Google Chrome extension that allows you to highlight text in images) but even that said "No" on the error message.

@gswcodeshow - Can you provide an English translation at all?

**Comment by gswcodeshow** [comment]
error message was  could not open database file.Reason: database disk image is malformed

**Comment by gswcodeshow** [comment]
![izuvjpll d tm1cawy i0ex](https://user-images.githubusercontent.com/25546052/36706763-599f2590-1ba6-11e8-8338-6eb95facd830.png)

**Comment by gswcodeshow** [comment]
the targetfile header 
![a1cf_ ntv3 wj59e vf 8 a](https://user-images.githubusercontent.com/25546052/36706857-c5a41b38-1ba6-11e8-83bd-a084f78fca38.png)

**Comment by gswcodeshow** [comment]
I open the file with other software.
![is8 oos 0y1l o 9jgim](https://user-images.githubusercontent.com/25546052/36706961-393dba5e-1ba7-11e8-8760-8ac8c251af10.png)

**Comment by chrisjlocke** [comment]
I've tried to open the database using sqlite3.exe - its the command line tool for SQLite itself.

![image](https://user-images.githubusercontent.com/7872218/36714802-86e902de-1b8b-11e8-96df-cadecd64cf83.png)

Even that can't open it?  Can you open it fine using sqlite3?
http://sqlite.org/2018/sqlite-tools-win32-x86-3220000.zip

**Comment by gswcodeshow** [comment]
I use the tools can't open it.I guess it is sqlite format error in the bytes.

**Comment by chrisjlocke** [comment]
Somewhere along the line, the database has become corrupted.  
Ironically, one of the first hits in Google on how to recover a corrupted database suggests using DB4S! (https://sysinfotools.com/blog/fix-error-sqlite-database-disk-image-malformed/)

The command line tool can export the database to SQL commands, which can be imported into a new database via DB4S, but some data along the line has been lost.  Your best option is to return to a backup copy of your database?

**Comment by chrisjlocke** [comment]
As we don't know the original state of the database, I'll close this.  @gswcodeshow - feel free to reopen it or comment further if we can be of any more help.

**Comment by gswcodeshow** [comment]
Thank you for all your answers.
