### ISSUE TITLE
Version check on startup crashes sqlitebrowser

### ISSUE THREAD

**Issue by RolandLoewe** [sqlitebrowser/sqlitebrowser#1335]
### Details for the issue

I wonder if it is necessary for sqlitebrowser to check for new versions upon startup? Our university has recently blocked access to raw.githubusercontent.com, crashing sqlitebrowser immediately upon startup :(
Thanks for a great tool otherwise!

![clipboard01](https://user-images.githubusercontent.com/10918367/37040521-5a2ab402-215a-11e8-8264-2ba31a9197aa.jpg)

#### I'm opening this issue because:

- [X] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Issue #1311 covered this, but unfortunately it couldn't be replicated, then it got derailed.... 

Thankfully you're on Windows, so turning off automatic updates should (??) be easy.
If you open the registry to this key:
HKEY_CURRENT_USER\Software\sqlitebrowser\sqlitebrowser\checkversion

and set/create a key called 'enabled' and set it to 'false'

![image](https://user-images.githubusercontent.com/7872218/37043058-a80c62d6-2157-11e8-8300-3b289c7bdfb4.png)

Hopefully it shouldn't check then.

**Comment by chrisjlocke** [comment]
I don't know if DB4S put in the 'disable' key, so ignore that, and don't ask me why there are two 'sqlitebrowser' legs, one under the other.  Historical reasons.  Magnets.  Because it was Monday.  Who knows.

**Comment by chrisjlocke** [comment]
OK, just tested this, and disabling the 'enabled' flag solves this.  @RolandLoewe - this should work OK once the registry is tweaked.  If you could kindly confirm when convenient.

**Comment by RolandLoewe** [comment]
Confirmed. Setting the registry flag is equivalent to turning off the "Automatic Updates" checkbox, so the problem basically only occurs right after installation or when somebody suddenly blocks access to github :)
Thanks!

**Comment by chrisjlocke** [comment]
Thanks.  I'll close this, but the original issue (hopefully if it gets back on track) should get addressed. 👍

**Comment by robmarkcole** [comment]
Could `checkversion` be set to `False` by default? IT admin installed this on my machine and I cannot find `Software\sqlitebrowser\sqlitebrowser\checkversion` so assume it is hidden in an admin folder someplace

**Comment by chrisjlocke** [comment]
The problem by setting it to default is that most people won't check manually, and their version will get older until it rots.
`Software\sqlitebrowser\sqlitebrowser\checkversion` is a registry key.  Its not a folder.  As per the screenshot, you edit it via Registry Editor.

**Comment by robmarkcole** [comment]
@chrisjlocke understood, resolved now after I read up on the registry editor.
Cheers

**Comment by sjlouis** [comment]
For those who can have the same problem, I haven't found the key under :
HKEY_CURRENT_USER\Software\sqlitebrowser\sqlitebrowser\checkversion

But under :
HKEY_USERS\S-1-5-21-4154618278-3164314411-2958915130-2264\Software\sqlitebrowser\sqlitebrowser\checkversion

It seems I have a lot of programs in this branch. I have Windows 7.

**Comment by sjlouis** [comment]
It works well  :-)  . Previously, it hanged a lot of time, it was very annoying.

Thank you.

**Comment by chrisjlocke** [comment]
@sjlouis - the key you posted is an alias for HKEY_CURRENT_USER.
So its the same branch.  It might depend on whether you're running 32bit or 64bit Windows though.  Its a bit more complex than that though.

**Comment by sjlouis** [comment]
You're right. I forgot the installer user is a specified user in my company. It's "administrateur" and each user have his name, "Jean-Louis" for me for example.

At home, I have several users but I'm the administrator. Nevertheless I installed some products only for me. I looked up at this case but don't see anything.

Thank you Chris  :-)  .
