### ISSUE TITLE
Ability to import NULL values from CSV

### ISSUE THREAD

**Issue by mkweskin** [sqlitebrowser/sqlitebrowser#1339]
### Details for the issue

As far as I can tell, there is not a way to import NULL values from a CSV. I suggest an additional checkbox in the "Import CSV file" window of "Treat missing values as NULL". Or I'm curious if you all have another idea to handle this.
Thanks!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.12.6 )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yep, that would be useful.  The generally referenced CSV spec (an RFC) doesn't take into consideration database things.  eg default values, NULL values, and similar

On that note, we should probably also have the choice of treating missing (eg empty) values as "use the default value for the field, if defined". :wink:

**Comment by mkweskin** [comment]
Agree about the use default option. I tried defining default as NULL and doing an import and saw that the default wasn't used.

**Comment by chrisjlocke** [comment]
A crappy hacky workaround which I've used in the past is to use a value thats either 'nonsense' or known.  So if a date field was to have NULL values, use a date thats otherwise invalid (eg, 99/99/9999) or is outside the usual range (eg, 01/01/2000) then simply do a 'update tablename set fieldname = null where fieldname='99/99/9999' etc.
Yup, told you it was hacky.  🔢

**Comment by justinclift** [comment]
Still, that's a useful workaround for now. :smile:

**Comment by remram44** [comment]
Interestingly the behavior matches sqlite3's `.import` command. But I agree that it's a terrible default.

**Comment by remram44** [comment]
The current code looks at the column type to decide what to do, but only has special behavior for `INTEGER` columns:

https://github.com/sqlitebrowser/sqlitebrowser/blob/a242a581c5802ca0bcf9acf8dd82878ffe063b44/src/ImportCsvDialog.cpp#L560-L565

**Comment by justinclift** [comment]
Oops.  We really should get a review done of #1349.

As a thought for now, while we wait for the code review to get done... would it help if I make a one-off build of DB4S (our abbreviation for DB Browser) including the code in that Pull Request?

**Comment by mkweskin** [comment]
Looks great! Thanks team.
This is my first look at the nightly build versions. I like the other changes I noticed: all caps for the suggested SQL commands, in the "Execute SQL" tab moving "Save as CSV/View" to the tool bar. Do you have a new official release planned?

**Comment by justinclift** [comment]
We're hoping for some time in the next few weeks.  As a rough guide :wink:, we're generally wanting to get all of the Pull Requests completed, and fix any other bug type things that seem important enough to get included as well.

**Comment by MKleusberg** [comment]
Thanks for testing, @mkweskin! I'll close this issue then :smile: 

By the way, if you're interested in helping with the next release, maybe @justinclift can build a once-off build for #1394 for you to play around with. The changes in this pull request are large enough that some real-world test results could be helpful :wink:

**Comment by justinclift** [comment]
Yep, that's pretty easy to do, especially for OSX builds.  It's 99.5% scripted, so I just need to point the script at the right bits and launch it.

@mkweskin I'm happy to create an OSX build with the multi-threading code for #1394 included, if you'd be ok to try things out with it and report back weirdness/bugs/etc? :smile:

**Comment by mkweskin** [comment]
Sure thing, happy to do more testing. Let me know where to download this one-off build when it's ready. It sounds like you're saying it's different than the nightly builds.

**Comment by justinclift** [comment]
Yeah.  The nightly builds (done automatically) use whatever code is in our `master` branch.

I made a copy of the nightly build script a while ago, and adjusted it so it can be told to build from a different source.  It also uploads to a different place on our nightlies server.

I'll get the build we're discussing here launched in a few minutes.  It takes a while to complete though (~1/2 from memory). :smile:

**Comment by justinclift** [comment]
k, just started the script.  In theory - if I didn't forgot something :wink: - then the builds should appear here in about 30-40 mins:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/osx-onceoffs/

There will be 2 versions.  One with standard SQLite support, and one with SQLCipher support.  Use whichever appeals. :smile:

**Comment by justinclift** [comment]
Playing around with the one including SQLCipher support. Seems to "work ok" in very light initial testing now.

I'd better get the DBHub.io migration stuff completed today, so we have some large example data sets we can try with too. :smile:
