### ISSUE TITLE
Generation of Android classes 

### ISSUE THREAD

**Issue by abelardolg** [sqlitebrowser/sqlitebrowser#1345]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

I have wondered if a valuable feature to this application is to generate automatically Android classes in order to save time by coding them.

Best regards.

**Comment by justinclift** [comment]
When you say "Android classes", what are you meaning?

Also, are you meaning for SQLite itself, or for DB Browser for SQLite (this GUI)? :smile:

**Comment by chrisjlocke** [comment]
> what are you meaning?

The answer to your first question lies in the last paragraph, "I have wondered if..." which also answers your second question... 😉

**Comment by abelardolg** [comment]
Hi @justinclift ,
In order to store internal data in any Android application, we need to use a SQLite db. Apart of using this db, we need to generate classes such as contract (you can know more about this topic here: [https://developer.android.com/training/data-storage/sqlite.html](url)).

It would interesting that this tool automatically generates the additional classes to be used in any Android application by adding plugins.

Best regards.

**Comment by justinclift** [comment]
Ok, so classes for SQLite itself, not for extending DB4S or something.

Hmmm, not sure how useful that would be.  It sounds like the kind of thing that would be better as a separate project or utility.  That's just my opinion though.  Others may feel differently. :smile:

**Comment by chrisjlocke** [comment]
Closing this, as this is not something DB4S can support in the short term.
Depending on further feedback, it could be something we revisit later.
