### ISSUE TITLE
fatal error: Qsci/qscilexerjson.h: No such file or directory

### ISSUE THREAD

**Issue by mlewisv1** [sqlitebrowser/sqlitebrowser#1348]
### Details for the issue

Hello, when compiling sqlite browser after running the make command I received the follow error. I followed the directions to the T in the BUILDING.md file pertaining to my CentOS distro. Any insight on what I could do to resolve the issue would be much appreciated.

Scanning dependencies of target sqlitebrowser
[ 50%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/AboutDialog.cpp.o
[ 51%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/EditIndexDialog.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/EditDialog.cpp.o
In file included from /home/a1d3n/sqlitebrowser/src/EditDialog.cpp:6:0:
/home/a1d3n/sqlitebrowser/src/docktextedit.h:5:32: fatal error: Qsci/qscilexerjson.h: No such file or directory
 #include <Qsci/qscilexerjson.h>
                                ^
compilation terminated.
make[2]: *** [CMakeFiles/sqlitebrowser.dir/src/EditDialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
make: *** [all] Error 2

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( CentOS 7 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Obviously, that shouldn't happen. :smile:

I've just run through the compiling instructions myself again now, using my CentOS 7 x86_64 desktop.  That worked, so it looks like whatever's wrong isn't as simple as I was hoping for. :wink:

With the source code you're compiling, is it the latest version from git, or are you using a downloaded source tarball, or something else?

**Comment by mlewisv1** [comment]
I cloned it from terminal, so should be the latest version from git. I'll try it again real quick to see if I get the error again.

**Comment by mlewisv1** [comment]
Yup. Same error after using "make" command. When I search for the file from the root folder I can find it and it says the parent folder is /home/a1d3n/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci. Just let me know if there's something else you'd like me to try.

**Comment by justinclift** [comment]
Hmmm... I wonder... on CentOS and Fedora when there's a file that's *known* to exist, but for some weird reason something isn't able to see or access it... generally it turns out to be SELinux blocking access.

I have *no idea* why SELinux would be blocking access in this case though.  Is the git clone on a remote filesystem or mounted strangely or something?  Note - just trying to imagine potential causes.  Purely guessing at the moment. :smile:

**Comment by mlewisv1** [comment]
Nope it's on my hard drive. Not cloning to anything special.

**Comment by justinclift** [comment]
Ok.  I guess I'll need to install CentOS 7 from scratch in a VM then to see if I can replicate it.  It sounds like I've probably changed something on my desktop that's letting it work.  If a default CentOS 7 install doesn't compile, it shouldn't be too hard to track down.

... it won't be right now though.  I need to get some sleep. :wink:

**Comment by mlewisv1** [comment]
No worries, whenever you get the chance. If i could be more of assistance just let me know.

**Comment by mgrojo** [comment]
Migth it be selecting an old internal version of the QScintilla library? One before the JSON cell editor was added? You may try using the FORCE_INTERNAL_QSCINTILLA cmake option:

```shell
cmake -DFORCE_INTERNAL_QSCINTILLA=ON . 
```

**Comment by mlewisv1** [comment]
That did the trick! I appreciate the assistance.

**Comment by mgrojo** [comment]
We can then close this, although it is not clear for me how it comes to select an old QScintilla version on a non standard location. At least we know now how to solve it.
