### ISSUE TITLE
new rows viewed, after reopen db

### ISSUE THREAD

**Issue by janmakarek** [sqlitebrowser/sqlitebrowser#1351]
im add data in table 
http://ipic.su/img/img7/fs/kiss_17kb.1521309757.png

1. create table
1. move to Data tabItem
2. add data
3. move to datastructure tabItem
4. move to Data tabItem
5. im show only first row!

im reopen db
move to datat tabitem
im show all rows
http://ipic.su/img/img7/fs/kiss_10kb.1521310188.png

-------------

im download sqlite dlls, and put in program dir
now so work, you can close

**Comment by justinclift** [comment]
Cool.  Glad you got it working. :smile:
