### ISSUE TITLE
sqlitebrowser fails when browsing big sets of data

### ISSUE THREAD

**Issue by drudd75077** [sqlitebrowser/sqlitebrowser#1352]
I am trying to open a database table and want to review the data in browser. The database table is 6 GB and several millions of rows. The browser data tab understandably crashes when it tries to load the whole table. In other sqlite tools it generally allows me to limit the rows in the browse data to 100 - 1000 rows. 

Is there a way to do that by default in sqlite browser?

#### I'm opening this issue because:

- [X ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( 7_version:_ SP1 Enterprise___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

https://github.com/sqlitebrowser/sqlitebrowser/issues/817 I searched this thread and tried to change some setting which did not solve my problem.

**Comment by justinclift** [comment]
Yeah, at the moment we're not yet doing really well with databases that are pretty large.  As you're seeing, we don't yet have a way to limit the amount of memory used.

As pointed out in #817, there are ways to adjust the amount of data that gets fetched at a time.  However when scrolling through a table, the whole table's data gets loaded into memory.  So if the data set for a table is bigger than memory, things go pear shaped. :frowning: 

There has been some work to help with the "scrolling through the data set" part of things:

&nbsp; &nbsp; https://lists.sqlitebrowser.org/pipermail/db4s-dev/2018-March/000308.html

But that's waiting (final?) review before being merged into our code base.  It doesn't help with overall memory usage either. :frowning:

**Comment by sky5walk** [comment]
Did you try opening a blank or smaller db and then Execute SQL = "ATTACH 'mybigdb.db' AS bdb"?
I noticed DB4S does not attempt to populate a grid in this case.
Then you could execute filtered, manageable queries on 'bdb'.

**Comment by justinclift** [comment]
@sky5walk That's a really clever approach.  Good thinking. :smile:

**Comment by mgrojo** [comment]
> There has been some work to help with the "scrolling through the data set" part of things:
Maybe we can make a branch with that solution and provide a build for users that are interested in improved support for big databases. What do you reckon?

**Comment by drudd75077** [comment]
Thanks for the advice @sky5walk

**Comment by drudd75077** [comment]
I'm new to github, should I close this issue since sky5walk's suggestion addresses my issue or keep it open since it's kind of an unelegant solution?

**Comment by justinclift** [comment]
Hmm, it's kind of an "in between" situation, as skywalk's suggestion does work but's not where we need to eventually be.

In this particular case, lets close it.  We have 250+ open issues at the moment, so we should probably err on the side of "lets try to not let that blow out too much". :wink:
