### ISSUE TITLE
Window Minimize Bug

### ISSUE THREAD

**Issue by mfathirirhas** [sqlitebrowser/sqlitebrowser#1354]
### Details for the issue
I downloaded and installed from the source. After installing, I run it and when I tried to minimize the window, it minimized but won't stay minimized and immediately get maximized. When I switched the workspace window, it keeps displaying the windows no matter in what workspace you're. I also happen before I upgrade to 3.10.1 from 3.9.1. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_Ubuntu 17.10 ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Additional Info:
- Qt version: 5.9.1
- SQLite Version: 3.19.3

**Comment by chrisjlocke** [comment]
This was quite an old bug.  I thought this was fixed a while ago.  Have you tried a nightly build?
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

See also:
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

**Comment by justinclift** [comment]
@mfathirirhas Have you had a chance to try a build created from newer source code (eg our latest git master branch)?  As @chrisjlocke mentioned, this problem should be fixed in that. :smile:

**Comment by chrisjlocke** [comment]
@mfathirirhas .... *cough*

**Comment by mfathirirhas** [comment]
@justinclift  @chrisjlocke  Sorry for late reply. My newest sqlitebrowser was built based on newest source code I downloaded on 20 March version 3.10.1. The built was succeed and same bug happen just like previous built(3.9.x). I didn't try the nightly build yet. I'll try later.

**Comment by chrisjlocke** [comment]
3.10.1 was from Sep 2017, but the minimise bug was fixed in Oct 2017.  Compiling from any nightly after 12 Oct 2017 should have this bug removed.  I'd recommend the latest nightly, but of course, that may also contain minor bugs (its a nightly build, after all) so tread carefully.
We're looking at a newer release soon, which should more stable, but the nightly would be the best bet.

**Comment by mfathirirhas** [comment]
@chrisjlocke I'll try the nightly build later.

**Comment by chrisjlocke** [comment]
I'll close this as this bug should have been fixed in Oct 2017.
Feel free to re-open it, add to it or open a new query if you feel it hasn't been answered.
