### ISSUE TITLE
Problem to open encrypted db 

### ISSUE THREAD

**Issue by bagusflyer** [sqlitebrowser/sqlitebrowser#1357]
### Details for the issue

I can't open an encrypted db with DB4S. This is the code I encrypted my db:

NSString* dbPass = FORMAT(@"PRAGMA key = 'b27c0972b1437959c8ef5c9b3c69daf7')
NSString* dbLic = FORMAT(@"PRAGMA lic = 'abcdxxxxxxxxxx');

.......

Then I tried to use b27c0972b1437959c8ef5c9b3c69daf7 as my passphrase to open the db. But can't open the db. Any idea? Thanks.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( 7 version:service pack 1)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
What program code did you use to encrypt the database?  What library did you use?
DB4S uses a library called 'SQLCipher' so the method you used to encrypt it has to be compatible with that.
https://www.zetetic.net/sqlcipher/

If you've encrypted it using one method (encryption type) you need the same format to unencrypt it.  SQLCipher is fussy with what it reads, and it can't detect the method you used - all it can tell is that when it tries to unencrypt it, its still a garbled mess, so didn't work.

**Comment by bagusflyer** [comment]
I'm not using SQLCipher, I'm just using sqlite3 library. Here is the code:

```
NSString* dbPass = FORMAT(@"PRAGMA key = 'b27c0972b1437959c8ef5c9b3c69daf7')
NSString* dbLic = FORMAT(@"PRAGMA lic = 'abcdxxxxxxxxxx');

sqlite3_stmt* stm;
const char *pzTail;
int res = sqlite3_open16(file, &db);
res = sqlite3_prepare(db, [dbLic UTF8String], -1, &stm, &pzTail);
res = sqlite3_step(stm);
res = sqlite3_finalize(stm);

res = sqlite3_prepare(db,[dbPass UTF8String], -1, &stm, &pzTail);
res = sqlite3_step(stm);
```

**Comment by bagusflyer** [comment]
When I tried to open the database in sqlite command line like this:

```
sqlite>  PRAGMA key='b27c0972b1437959c8ef5c9b3c69daf7';
sqlite> .open mydb.db3
sqlite> .database
Error: file is not a database
```

**Comment by chrisjlocke** [comment]
I'll close this as DB4S doesn't support SEE, and has limited encryption through the SQLCipher extension.
Feel free to re-open this, add to this, or open another query if you feel this is unanswered.
