### ISSUE TITLE
Sorting with Numeric Type, 90 and 9 next to each other?

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1358]
So as title says when sorting numerical data, 1,2,3,4 should be before 11,12,13, however this is not the case. How can this be fixed?

**Comment by chrisjlocke** [comment]
It does for me.

![image](https://user-images.githubusercontent.com/7872218/38136003-5f1b8150-3413-11e8-8859-a6a3e23708d4.png)

Is the database confidential?  Could you email it to me?

**Comment by shaun-ba** [comment]
Weirdly I made another View and it works, the SQL is the same between the new and old one so not sure what's up there but it now works!
