### ISSUE TITLE
Can't Modify View

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1359]
I've created a few "Views" to help when trying to find data, however there is an option to "Modify View", but it is always greyed out?

#### I'm opening this issue because:

DB4S has a bug

#### I'm using DB4S on:

Linux: (Ubuntu)

#### I'm using DB4S version:

3.10.1

**Comment by chrisjlocke** [comment]
View structures can't be edited through the GUI.  You can amend it via SQL, or simply delete the view and recreate it.

**Comment by shaun-ba** [comment]
So why have the option at all, and greyed out. Less confusing to remove it if it's not possible?

**Comment by chrisjlocke** [comment]
Its hoped one day the feature will be available.  So maybe it denotes, "coming soon.... soon to be ungreyed out.  Yay."

**Comment by shaun-ba** [comment]
Confusing for the user to put it in the UI, just comment in code instead!

I'm trying to be constructive, the app is brilliant :)

**Comment by mgrojo** [comment]
The reason is that the same button is reused for modifying any DB object, but views are not (currently?) modifiable through a dialog so the button is always greyed out for views.

It could be made invisible so the user is not confused. This is not the first time that the same issue has been raised.

**Comment by chrisjlocke** [comment]
I'll close this as the original query  has been answered.  Feel free to re-open it, add to it or open another query if you feel it hasn't been answered.
