### ISSUE TITLE
FEATURE: Enable editing of "View" cell data.

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1360]
The "View" feature is very nice, giving the ability to sort multiple columns at the same time etc. However, (for me) this is rendered completely useless when you can't edit the cells.

Any plans to add this ability?

#### I'm opening this issue because:

DB4S needs a feature

#### I'm using DB4S on:

Linux: ( Ubuntu )

#### I'm using DB4S version:

3.10.1

**Comment by chrisjlocke** [comment]
If you use one of the nightly versions of DB4S, then editing via views is possible.
https://github.com/sqlitebrowser/sqlitebrowser/issues/141#issuecomment-301131415

`
This means you have to enable editing for a view by browsing it, right clicking on the column headers, and clicking "Unlock view editing". You'll then be asked for the name of a unique column in that view. That's because we somehow have to decide how to address rows in the view and there doesn't seem to be any good way to find out a suitable column automatically.
`

**Comment by shaun-ba** [comment]
@chrisjlocke I'm now using "Version 3.10.99 (Mar 28 2018)"

I still don't see the ability to edit the view?

**Comment by chrisjlocke** [comment]
So no 'unlock' menu option?

![image](https://user-images.githubusercontent.com/7872218/38135939-db0043d8-3412-11e8-94cf-c4f8df91d0c4.png)

What options do you get when you right click the column headings in the 'browse data' tab?

**Comment by shaun-ba** [comment]
Hi, I see this option yes, but would never guess to right click the column heading in view! Not sure why there is even a need for this option to be honest.

**Comment by chrisjlocke** [comment]
As per the comment posted above (which gave instructions to click the header).
Its work in progress.  We're working on it.  Its test code.  Testing.  Editing views isn't easy due to the natuire of how views work.  So yes, it needs an option for the time being.

**Comment by shaun-ba** [comment]
Perfect, it works so thanks!

**Comment by shaun-ba** [comment]
Just to add to this feature, I can't add a new record so still can't use it for intended purpose.

If you remember from an old issue you helped me on, I want to be able to view and edit the DB whilst sorting via 2 columns, this is the overall aim here.

**Comment by chrisjlocke** [comment]
Yes, a view (by it's name) is read only as it pulls it's data from multiple tables, so you can't add a row to it, as the data would exist in more than one table.

Add a record to the tables, and the view is updated automatically.

**Comment by chrisjlocke** [comment]
I'll close this as the original query has been answered.  Feel free to re-open it, add to it or open another query if you feel it hasn't been answered.

**Comment by shaun-ba** [comment]
@chrisjlocke @mgrojo Then please re-open my feature request, clearly it is a valid request to expand on the sorting features of data when editing.

**Comment by chrisjlocke** [comment]
An existing issue relating to editing views is already open.  #141.  See the second comment above.

**Comment by shaun-ba** [comment]
@chrisjlocke Yes but it doesn't sort, so ok i'll reply there instead but best to be clear what you want users to do when closing threads left right and center!

**Comment by shaun-ba** [comment]
But it's not editable, so what is the point? I'll reply to the other thread because its an apparent fix that doesn't work

**Comment by chrisjlocke** [comment]
Aah, apologies.  It *should* be editable.  A fix to fix something has broken this bit... so its broke.  Hopefully the fix to fix the bit that has broke won't broke something else.

**Comment by endlisnis** [comment]
I hate to comment on an ancient issue, but this no longer seems to work.  I can enable cell editing, but actually trying to change the data results in "cannot modify <table> because it is a view"

**Comment by chrisjlocke** [comment]
And have you created the necessary triggers?

**Comment by endlisnis** [comment]
> And have you created the necessary triggers?

I didn't realize I needed triggers.  I have a lot of software development experience, but only a small amount of SQL experience.  I was hoping that Sqlite Browser would be able to edit the underlying source data when used on a view.

Are you saying that it should work, but I'd have to write triggers that changed any attempt to update the view into changes to the original source tables?

**Comment by justinclift** [comment]
@endlisnis Just to check, have you read through this wiki page yet? :smile:

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views#editing-data-in-a-view

**Comment by endlisnis** [comment]
> @endlisnis Just to check, have you read through this wiki page yet? 😄

No, I had not read that.  But I just read it and I was able to get it all working with triggers.  Thanks!

**Comment by justinclift** [comment]
You're welcome. :smile:
