### ISSUE TITLE
How to increase performance?

### ISSUE THREAD

**Issue by l-g** [sqlitebrowser/sqlitebrowser#1364]
### Details for the issue

I have a DB (basically an Excel sheet that is too big for Excel) consisting of one table with ten columns, all containing simple datatypes such as text, integers and dates. All in all this table has between 3 and 4 millions of rows.

Working in the GUI (scrolling, sorting a column, changing tabs and similar operations) with this DB on laptop with an eight core i7 and 16 GB memory is pretty slow. One CPU core is at 100 % but sqlitebrowser does not seem to utilise more than one core. On the other hand, I don't think CPU is the bottleneck here, rather it is memory: sqlitebrowser only uses about 1.5 GB of RAM when working with this database. The actual file is 450 MB. "Only" consuming 1.5 GB makes me think sqlitebrowser is not loading the whole dataset into memory.

Is it possible to change some settings that will make the program faster under these circumstances?

I think there should be an article about improving performance in the Wiki!

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [X] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
@l-g Are you still interested in faster performance with this?

Asking because we've being working on the performance side of things recently (in #1394), and have an initial build ready for people to test:

* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_issue1394v2.dmg

In my testing so far with a ~600MB database, the lag is now only about 1 second.  That's heaps better than any of our releases so far. :smile:

**Comment by mgrojo** [comment]
@l-g Did you had some time to try the new version? The improvements are already in the [nightly builds](https://nightlies.sqlitebrowser.org/latest/). We'd like to close this issue as clean up before the release of our next stable version.

**Comment by l-g** [comment]
Yes, but the need is no longer there. Thanks anyway.

**Comment by justinclift** [comment]
No worries @l-g. :smile:
