### ISSUE TITLE
Please Help Building SQLCipher for Windows

### ISSUE THREAD

**Issue by WizardsEnterprise** [sqlitebrowser/sqlitebrowser#1365]
I have been trying to build SQLCipher for Windows for longer than I can remember, unsuccessfully. Your walkthru has been the easiest to follow here: [Win64-setup-—-Compiling-SQLCipher](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-—-Compiling-SQLCipher) but it still doesn't work for me. I'm running on  a fresh install of Windows 10 x64 with Visual Studio 2017 community. I installed ActiveState TCL 8.5.18.0 x64.  Also GitHub Desktop for Windows, as well as OpenSSL from Shining Light Productions. I cannot get SQLCipher to build for Windows. I'm sure you're probably extremely busy with your projects, but if you could please help me it would be greatly appreciated.

My end goal, the only reason for needing to compile SQLCipher for Windows, is because I have a SQLite CEROD database that I have to be able to migrate in place and then decrypt using:
`.open 'CerodDB.db';`
`PRAGMA key='keyhere';`
`PRAGMA cipher_migrate;`
`.databases`
`ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';`
`SELECT sqlcipher_export('plaintext');`
`DETACH DATABASE plaintext;`
`.exit`

Please help with either walking me thru successfully building SQLCipher for Windows or by giving me an easier solution for the need that I have. Thanks so much!

**Comment by chrisjlocke** [comment]
Have you tried running DB4S with SQLCipher packaged?
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher-win64.exe
(or https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher-win32.exe)

Do you know how the CerodDB database was encrypted?  SQLCipher has a limited decryption library.

**Comment by justinclift** [comment]
From rough memory (it's been a while), I found some of the pieces to only work with specific versions of things.  For example, when I was compiling stuff I used Visual Studio 2015 with update 5 + TCL 8.5.x.  That combination worked.

When I instead tried it with TCL 8.6... compiling failed.

Since you're using newer Visual Studio, my first suggestion would be to try the newer TCL.  Just to see if it makes a difference.  If it doesn't... then maybe fall back to using the same versions of things I did?  eg Visual Studio 2013 update 5 (etc).  Just because it's a "known good" working combination.

... and yeah, I really should update things to use newer versions, I just haven't gotten around to it. :smile:

**Comment by WizardsEnterprise** [comment]
@chrisjlocke would that allow me to run the explicit commands that I listed, or is there a different way to do it in that db browser exe? I have a friend that uses SQLCipher to migrate and decrypt the database I'm talking about but he does it on linux, so I know for certain that SQLCipher can decrypt it, I just don't know how to successfully build it for Windows. I do not know how the Cerod db was encrypted, I only know that the commands I listed are how to get it into a readable state.

**Comment by WizardsEnterprise** [comment]
@justinclift I will try what you said and see if that works out for me. I was somewhat confused on the last step of the walk-thru though because it goes from the nmake commands to compile SQLCipher and jumps into what seems like a totally different subject about DB4S

**Comment by justinclift** [comment]
Ahhh yeah.  The first 6 steps get SQLCipher compiled ok... the last step there (7) though was supposed to follow on from that so that people could then integrate that with DB4S using Qt Creator.

Step 7 hasn't really been finished and you can probably ignore it.  Pretty sure you've already figured that out though. :smile:

**Comment by WizardsEnterprise** [comment]
@justinclift Hi again. So I took your advice and used all of the exact versions that you did and I managed to make it to step 6 (Compile SQL Cipher). I changed the values in MakeFile.msc etc etc etc... The problem I am runnining into is
`LINK : fatal error LNK1104: cannot open file 'tcl86.lib`
`NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.exe"' : return code '0x450'`
`Stop.`

I tried some googling but that error is way over my head. Is there any way you can assist? I really appreciate your assistance, I would probably never be able to do this without your help.

**Comment by justinclift** [comment]
Hmmm... ok as a different approach that might work, this is the windows batch file we use to generate our nightly builds:

&nbsp; &nbsp; https://gist.github.com/justinclift/11cc926f214e882c8162f97c53929c07

That uses the same version of things which you've now got installed.  eg Visual Studio 2013 update 5, TCL 8.5, (etc) 

It also uses a version of SQLCipher that I've pre-prepared with the changes mentioned in those instructions, just to make it easy to compile each night:

&nbsp; &nbsp; https://github.com/justinclift/sqlcipher

Assuming you installed things in the same place that the batch file and my sqlcipher repo use (details will be in the batch file I guess)... then in theory you **should** be able to run the first part of the batch file successfully, which does the SQLCipher compiling.

Hopefully that works. :smile:

**Comment by justinclift** [comment]
@WizardsEnterprise Did you get it working? :smile:

**Comment by WizardsEnterprise** [comment]
I just did this morning, I was going to give up and I thought, wait let me just copy Libeay32.dll from another location into the folder with the compiled SQLCipher and see if it works and sure enough it does. As long as you follow your initial walk thru using the exact versions that you used and afterwards manually copy in the libeay32.dll then everything works perfectly and I am able to perform an in place upgrade and decrypt the database... now I just have to figure out how to use SQLCipher in my windows service to perform these actions on that database I the fly 🤔.

This is an awesome project you have going here, thank you so much!

**Comment by justinclift** [comment]
Excellent.  Glad it finally worked out. :smile:
