### ISSUE TITLE
[True Beginner] How convert exported db to sqlite3 format?

### ISSUE THREAD

**Issue by danjde** [sqlitebrowser/sqlitebrowser#1367]
Hi Friends, and excuse me for the very beginner question.
From a sqlite3 db corrupted, I've exported it (using native sqlite3 tool) a dump file and then imported it successfully into sqlitebrowser. And this is very well!!
Then,
exporting this DB from sqlitebrowser, using the option "Export as SQL file" obtain an SQL file (not sqlite3. From Linux command "file" it appear as "ASCII text, with very long lines, with CR, LF line terminators" not anymore "SQLite 3.x database" ). And this is good but not what I would like to obtain.

Now once that the dump file is imported into sqlitebrowser, is it possible to export again it on sqlite3 format?

I've seen [this page](http://www.sqlite.org/cvstrac/wiki?p=ConverterTools), but I don't understand very well if useful.

Many many thanks!

davide

**Comment by chrisjlocke** [comment]
Technically, you've already done it.
You exported it, and that process has created SQL commands.  You then say you imported this into SQLite Browser (we call it DB4S - DB Browser for SQLite, but I prefer George,...) 
At that stage, it is in 'sqlite3' format.  You've created a database to import into.  DB4S has opened (for example) 'myDatabase.db' or 'myDatabase.db3'.  This file is in sqlite3 format.

Continuing on, you say, "Exported this DB as SQL File" - thats doing another 'dump', if you like, so you're just converting sqlite3 file back to SQL commands again.

So just to confirm.  The dump file is imported, so you don't need to export it again, as that would only recreate the file you imported...... 


.... make sense?

**Comment by danjde** [comment]
Hi chrisjlocke and thanks for your reply!
I'm very newbie to sqlite3, so I do a little hard to understand, so excuse me if it seems that I have repeated the question .. 


I would like to realize:


1) dumping from a sqlite3 db file obtain an sqlite3 file? My answer is no. Infact if I run:

`file dump_all.sql`

obtain
` dump_all.sql: ASCII text, with very long lines, with CR, LF line terminators`


I've run this procedure to dump:

```
1 sqlite3 database_ko.db
2 .mode insert
3 .output dump_all.sql
4 .dump
5 .exit
```



2) Then I can import this dump into 'George' and then if I export it using "Export as SQL file" and then test it with "file" obtain:

`file dump_all_exported_from_George.sql`

obtain:
`dump_all_exported_from_George.sql: ASCII text, with very long lines, with CR, LF line terminators`

 This file seems no longer an sqlite3 file format.


3) If I open with an editor (vi) my corrupted db, before the dumping I can see this structure:

```
SQLite format 3^@^P^@^A^A^@@  ^@^@^@^C^@^@^D.^@^@^@^@^@^@^@^@^@^@^@:^@^@^@^D^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^C^@.^AZ^E^@^@^@^C^Oñ^@^@^@^C¤^Oû^Oö^Oñ^K^B
^Z      {^Hí^HD^GÌ^Fï^Fo^E<97>^Dú^D^^^Bê^B^Z^Ai^@à^@Ø^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^F^U^F^@^@^@^@^@<81>^F^T^G^W^]^]^B<81>]tableprovinceprovince^A^\CREATE TABLE province (IDProvince INTEGER PRIMARY KEY AUTOINCREMENT,Nome TEXT,Sigla TEXT,Codice INTEGER)<81>.^S^G^W))^B<82>^Utableschedine_istatschedine_istat^A^QCREATE TABLE "schedine_istat" (ID integer PRIMARY KEY AUTOINCREMENT,numero varchar,"id_preno" integer DEFAULT 0, "data_ins" integer)<81>M^R^G^WAA^B<82>#tableschedine_istat_assoc_roomsschedine_istat_assoc_rooms^@ûCREATE TABLE "schedine_istat_assoc_rooms" (ID integer PRIMARY KEY AUTOINCREMENT,"ID_Cliente" integer,"ID_Room" integer,"ID_Scheda" integer)<82>1^Q^G^W77^B<83>^?tableschedine_istat_recordschedine_istat_record^@ÑCREATE TABLE "schedine_istat_record" (ID integer PRIMARY KEY AUTOINCREMENT,"tipo_alloggiato" integer,"ID_Cliente" integer,"ID_Room" integer,"ID_Scheda" integer,"tassa_soggiorno" integer,"data_arrivo" integer,"data_partenza" integer,modalita integer)<81>Y^P^G^W##^B<82>wtableschedine_psschedine_ps^@¾CREATE TABLE "schedine_ps" (ID integer PRIMARY KEY AUTOINCREMENT,"id_camera" integer,"data_arrivo" integer,numero varchar, "giorni_permanenza" integer, `id_preno` integer DEFAULT 0)<81>^Z^O^G^WAA^B<81>=tableschedine_ps_TipoAlloggiatoschedine_ps_TipoAlloggiato^@½CREATE TABLE schedine_ps_TipoAlloggiato (Codice integer PRIMARY KEY,Descrizione varchar)<81>U^N^G^W11^A<82>Utableschedine_ps_comunischedine_ps_comunifCREATE TABLE "schedine_ps_comuni" ("Codice" INTEGER,"Descrizione" TEXT(255,0),"Provincia" TEXT(255,0),"DataFineVal" integer,"Cap" text(255,0),primary key("Codice"))~^M^G^W77^A<81>^[tableschedine_ps_documentischedine_ps_documentieCREATE TABLE schedine_ps_documenti (Codice varchar,Descrizione varchar)<81>Z^L^G^W77^A<82>Stableschedine_ps_occupantischedine_ps_occupantiBCREATE TABLE schedine_ps_occupanti (ID integer PRIMARY KEY AUTOINCREMENT,id_schedina integer,id_cliente integer,capofamiglia integer, tipologia_alloggiato integer)v^K^G^W''^A<81>+tablesegmentazionesegmentazioneACREATE TABLE segmentazione (ID integer PRIMARY KEY AUTOINCREMENT,segmento text)<81>&
@                                                                                                                                                                                                                               @                                                                                                                                                                                                                               @                                                                                                                                                                                                                               @                                                                                                                                                                                                                               @                                                                                                                                                                                                                               @      
```

instead, if I open the 'George' sql exported file (dump_all_exported_from_George.sql) obtain a very different structure:


```
BEGIN TRANSACTION;
CREATE TABLE tipo_clienti (ID Integer PRIMARY KEY AUTOINCREMENT,nome VarChar);
INSERT INTO `tipo_clienti` VALUES (1,'Abituale');
CREATE TABLE "tipo_camera" (ID Integer PRIMARY KEY AUTOINCREMENT,nome VarChar,config integer,"conteggio_1" integer,"conteggio_2" integer,"conteggio_3" integer,"conteggio_4" integer,"conteggio_5" integer,"conteggio_6" integer,"conteggio_7" integer,"conteggio_8" integer,"conteggio_9" integer,"conteggio_10" integer,"conteggio_11" integer,"cambio_1" text,"cambio_2" text,"cambio_3" text,"cambio_4" text,"cambio_5" text,"cambio_6" text,"cambio_7" text,"cambio_8" text,"cambio_9" text,"cambio_10" text,"cambio_11" text);
INSERT INTO `tipo_camera` VALUES (11,'Doppia',2,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
INSERT INTO `tipo_camera` VALUES (12,'Doppia Eco',2,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
INSERT INTO `tipo_camera` VALUES (14,'Tripla',5,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
INSERT INTO `tipo_camera` VALUES (15,'Tripla Eco',5,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
INSERT INTO `tipo_camera` VALUES (16,'Quadrupla',7,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
INSERT INTO `tipo_camera` VALUES (17,'Quadrupla Eco',7,0,0,0,0,0,0,0,0,0,0,0,'0','0','0','0','0','0','0','0','0','0','0');
CREATE TABLE "template_email" (ID integer PRIMARY KEY AUTOINCREMENT,oggetto text,messaggio text);
INSERT INTO `template_email` VALUES (2,'benvenuto','Gentile [nome_cliente][cognome_cliente],^Mgrazie per averci scelto');
INSERT INTO `template_email` VALUES (3,'arrivederci!','Gentile [nome_cliente] [cognome_cliente],^Mgrazie per aver soggiornato da noi, spero di sarai trovato bene!');
CREATE TABLE "tariffe_giornaliere_preno" (ID integer PRIMARY KEY AUTOINCREMENT,"id_cam" integer,giorno integer,prezzo double, "id_preno" integer);
INSERT INTO `tariffe_giornaliere_preno` VALUES (1,72,1464850800,84.0,1696);
INSERT INTO `tariffe_giornaliere_preno` VALUES (2,72,1464937200,84.0,1696);
INSERT INTO `tariffe_giornaliere_preno` VALUES (3,72,1465023600,84.0,1696);
INSERT INTO `tariffe_giornaliere_preno` VALUES (4,65,1459580400,310.0,1697);
```

Only to understand, if possible, but why?

Many many thanks!

davide

**Comment by danjde** [comment]
Hi chrisjlocke and thanks again for your very very deep and descriptive explanation!

> A 'database.db' file is in sqlite3 format, and is not human readable [...]
> A 'commands.sql' file is human readable, [..]

I didn't know about "human readable" format and not (GASP!) :-)
Now (thanks to you) I begin to understand...

> [..]
> So we now have this:
> corrupted.db -> corrupted_export.dmp -> not_corrupted.db

Perfect!

> So exporting from DB4S is the same as a 'dump' - it converts a .sqlite3 database to a .sql set of instructions.
> [..]

Well, very well!

> (sorry this is a Windows screenshot and you are on Linux)
Don't worry, rather watch out for viruses! :-D :-D :-D

> [..]
> This filename will be in sqlite3 format. It will be empty, but when you import a .sql file (human readable set of instructions) it will be converted (or actioned) to populate the filename you specified. You can confirm this, as the file size will increase. (When you click 'Save Changes')
> 
> So if all you need is 'not_corrupted.db', you don't need to export it or do anything else - you already have the file you need.

This is the part that is less clear to me..

Are you talking to me that I can obtain a non human readable file, through the following procedure?

1) create new DB
2) importing into new DB my "not_corrupted.sql"
3) click 'Save Changes
4) end

Because you must to know that all these my questions arise from this need of mine:

I've an ERP software sqlite3 based. 
Some days ago this DB was corrupted due to a power failure, I managed to recover it, and successfully, but in human readable format, and this ERP does not digest this format :-)
Hence my need to understand if there are different formats 
and thanks to you to understand that there is also a "non human-readable" format.

So my new question is, this ERP could read the DB (non human readable) saved with the procedure just described above?

> 1) create new DB
> 2) importing into new DB my "not_corrupted.sql"
> 3) click 'Save Changes
> 4) end

Or can there be many many others non human human readable formats?

Very very thanks for your kindness and patience! :-)

davide

**Comment by justinclift** [comment]
> So my new question is, this ERP could read the DB (non human readable) saved with the procedure just described above?

In theory... yes. :smile:

A "normal" SQLite3 database is the non-human readible format.  Often the file has the extension .db, or .sqlite.

When a person wants to transfer the data to a different type of database system (something other than SQLite... for example PostgreSQL maybe), it's common to convert it into a human readible (.sql) file.  The human readable version can "imported" into different database system (eg PostgreSQL) and then used by programs that understand that one.

Note that this is a simplification, just to give the concept.  Like lots of things in life... there can be fine details that don't quite fit that pattern in some situations.  But, the above concept is correct. :smile:

**Comment by chrisjlocke** [comment]
OK.  When you say, "i managed to recover it", you've created an .SQL file which are all the instructions necessary to build that database.

However, there is a very important thing to understand.  Imagine a database is like a human.  It has a head, legs, arms, fingers, toes.  If you cut an arm off, you also lose the hand and fingers.  If a database becomes corrupted, imagine you 'forget' you have an arm.  However, you know you had fingers and a hand.  But where does that hand belong?  The rest of the body is also not aware you're missing an arm.  "Hey, scratch your ear!  You had an arm yesterday - why can't you do it now?" etc.

Parts of the database might need parts that are now missing.  In relational databases, an order might belong to customer number 45.  The order doesn't store all the customer information - as another order also points to customer 45, so that would be duplicate data.  However, customer 45 is now missing.  Some applications can't handle this and will crash.  I write computer programs (badly) and if the database said "yes - customer 45" but then said "i can't find customer 45" it would get confused.

The point of all this is that ultimately, you cannot trust this database.  The best you can do is revert to a full working backup, and using data from the corrupted database, put data back.  Its more complex than that - many tables talk to other tables.  

Actually I just thought of a better example.  
Imagine you have a recipe for a nice meal.  A list of ingredients and a method to make the meal.  If you 'lose' a line from the ingredients, the method won't make sense.  "Now add the onions".  Hey - what onions?  If you lose a line from the method, you'll end up with ingredients you didn't use.

I like that example.  I'm going to nick it.....

**Comment by danjde** [comment]
Waw! You are really brought for teaching, I would see you well with children at school as a teacher;-)
How many teacher I have encountered in my life unable to express their knowledge...sigh!

In any way I understood well the concept.
Unfortunately in certain situations you can not do anything but try everything for everything, sometimes hoping that one of the ingredients is not essential (as happened in my case) especially when you do not have (not for my responsibility) any backup copy ...

in any case, everything went well thanks to the dump.
I had opened this "issues" because I did not understand the difference between one "garment" of the db and another and in particular I did not understand why the ERP did not "digest" the human readable file.
Now you have explained it to me and I have understood it and I am very grateful to you! ;-)

Thank you again I wish you a good life!

I do not know if you like blues, I leave you [this song](https://www.cosmogonia.org/cosmogoniA/tmp/Blues.ogg) of one of my favorite singer-songwriter "Fausto Rossi" (very interesting [lyrics](https://wikitesti.com/blues_-_fausto_rossi/) but it's in Italian...)


davide

**Comment by justinclift** [comment]
Thanks @danjde. :smile:

I've just nuked the link to that song, as (without my knowing any better) it seems like copyrighted material.  We can get in trouble for that kind of thing, and I'd rather us avoid that.

If I'm wrong, and it's not copyrighted then just let me know.  I can put the link and text back again. :smile:

**Comment by justinclift** [comment]
Oh, I'll close this issue now too as it seems to be pretty much solved. :smile:

**Comment by danjde** [comment]
> it seems like copyrighted material
..probably yes. Well to nuke the link ;-)

> [..]pretty much solved.
Sure, and thanks again for your very great help!

Ciao!

davide
