### ISSUE TITLE
Add support for collation NOCASE

### ISSUE THREAD

**Issue by charlieph** [sqlitebrowser/sqlitebrowser#1368]
### Details for the issue

It happens when open a existing database and press the tab Browser Data.

### Useful extra information

The app send this message: A table in this database requires a special collation function 'NOCASE' that this application can't provide without further knowledge. If you choose to proceed, be aware bad things can happend to your database. Create a backup!

#### I'm opening this issue because: 

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( Windows 10 Pro version: 1709 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

Pleace help me or i am a developer, maybe could help for implement this requirement...

**Comment by justinclift** [comment]
In theory, this should already be working in our nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Try and out, and if it works you're welcome to just close this issue. :smile:

**Comment by charlieph** [comment]
Thanks justinclift,

With 3.10.99 nightly version, the problem is solved. But windows 10 alert me on SmartScreen that the binary file could be insecure. 

I am waiting that this version may be stable sooner...

Thanks for all, great job...

**Comment by chrisjlocke** [comment]
> that the binary file could be insecure

You'll always see this with the nightly builds.  They're not seen 'in the wild' that often, and are obviously fairly new.  You'll just have to trust us! ;)  As you keep using it, Windows will learn and trust it too.

**Comment by charlieph** [comment]
Thanks chrisjlocke... I got it!!!
