### ISSUE TITLE
Last nightly build = 180428-4AM, 4 days ago?

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1371]
### Details for the issue
Are the nightly builds interrupted and is the latest safe to install?
### Useful extra information
Normally, the nightlies show midnight o'clock?
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
https://nightlies.sqlitebrowser.org/win64/ goes up to 28 Apr.
My laptop usually monitors the nightlies, but unfortunately I recently moved, so waiting on t'internet to be turned back on....

https://nightlies.sqlitebrowser.org/win32/ goes up to 28 Apr, but only 27 Apr for sqlCipher.  Guess it fell over at that point...

**Comment by sky5walk** [comment]
Ok. Trying to determine if server is fishy. Is it safe to install the 180428?
I want to verify an issue with the latest before posting.

**Comment by chrisjlocke** [comment]
I'd use the 28 Apr version.  Its 10 days newer.  Unless you need x86 SqlCipher version, then you'll have to use the 27 Apr version.

The server isn't 'fishy' (just smells of salmon and mussels) - just the process fell over.

**Comment by sky5walk** [comment]
ok, thanks.

**Comment by justinclift** [comment]
Ahhh yeah, it's just the nightly build processes (they run on an older Mac Mini) not being able to connect to the internet and "do stuff".  OSX showing it's level of reliability (ie flaky) yet again. :frowning_face:

**Comment by justinclift** [comment]
Just checked, and both the OSX and Windows nightly build scripts ran fine manually today.  If they automatically update tomorrow (they should) then we can probably close this issue. :smile:

**Comment by jungle-boogie** [comment]
There haven't been any new updates to the project since 28th of March, so all builds post that date have been redundant, right?

**Comment by justinclift** [comment]
April, not March, but yeah.

For the Windows and OSX nightlies, nothing new was built in between (eg ~1 week worth).  The Linux ones (eg Ubuntu) though are built by external volunteers so didn't have the same hiccup. :smile:

**Comment by jungle-boogie** [comment]
This is the latest commit I see on master:
https://github.com/sqlitebrowser/sqlitebrowser/commit/85dbe7b01686f31a22cf3ce141e258801da986e8

That's where I got the 28 March date.

**Comment by justinclift** [comment]
The Windows and OSX nightlies fine overnight, so I'll close this now.

Thanks for reporting it @sky5walk. :smile:
