### ISSUE TITLE
EXPLAIN query enables "write changes" and "revert changes" buttons 

### ISSUE THREAD

**Issue by tcp-ip80** [sqlitebrowser/sqlitebrowser#1372]
### Details for the issue
If I execute any SQL query that starts with "EXPLAIN" (including "EXPLAIN QUERY PLAN"), the buttons "write changes" and "revert changes" in the toolbar switch to enabled, as if the query had made some changes to the database.
This should not happen, because EXPLAIN command, like SELECT,  returns a result leaving the database unchanged (see: https://www.sqlite.org/lang_explain.html ).

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Ubuntu 18.04 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, this sounds familiar.  From memory, this was fixed after our 3.10.1 release.

Um, since you're using Ubuntu, the nightly builds there should have the fix in the them.  Would you be ok to give that a go and confirm back? :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1

**Comment by tcp-ip80** [comment]
OK, I have tested the nightly-build and it seems to work fine.

**Comment by justinclift** [comment]
Thanks @tcp-ip80. :smile:
