### ISSUE TITLE
Prefetch block size creates unsafe grid selection!

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1373]
### Details for the issue
"View - Preferences - Database - Prefetch block size" creates unsafe grid selection.
And the ? tool does not work within the preferences dialog to describe the ramifications of this setting?

At a minimum, the Results window should state:
XXX rows of YYY available returned in Nms from: select * from myDB;

Better is to return all rows when user clicks Select All [Ctrl+A] or clicks the upper left of the grid box.
This is tricky behavior.
I understand the desire to limit rows for performance, but "Select All" must = "All". 
Not "Select All loaded rows".

### Useful extra information
Set the Prefetch to a smallish number like 500.

Execute a SQL statement that returns more than 500.
The Results window tells the user XXX rows returned in Xms from: select * from myDB;

- Select all resulting rows & cols - Copy to clipboard.
Result = Only the prefetch amount of rows were selected and copied.

Scrolling beyond the prefetch amount appends additional prefetch rows.
But this is an intensive and unexpected operation to get "all" the returned rows.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
> I understand the desire to limit rows for performance, but "Select All" must = "All".

Yeah, thinking about it a bit more, that does make sense. :smile:

**Comment by sky5walk** [comment]
Sorry to bump topic, but I wanted to request this as BUG and not Enhancement?
This can really cause errors down the line if users select all and get only 500 records.
There should be a popup message saying "NOT all" records selected.

**Comment by justinclift** [comment]
No worries @sky5walk. :smile:

**Comment by mgrojo** [comment]
@sky5walk I've polished this change, which I have left for a time in a repository copy, and have pushed it to the master branch. It will in tomorrow's nightly build.

Whenever "Select All" is requested through keyboard shortcut or the upper-left corner, if there is data still to be loaded, it asks the user whether to continue or cancel the selection. If accepted, all the data is loaded before performing the actual selection. Then copy and paste work as expected. Plea.se, confirm it's working OK for you.

**Comment by sky5walk** [comment]
Thanks, that sounds clear and no chance for user surprise! :) 
I'll check tomorrow.
