### ISSUE TITLE
Sql insert command script execution issues

### ISSUE THREAD

**Issue by jimmyp2** [sqlitebrowser/sqlitebrowser#1378]
Hello,

Using the portable version of DB Browser for SQLite Version 3.10.1 (latest) to import a few thousands
records (not exceeding of course the SQLITE_MAX_SQL_LENGTH or SQLITE_MAX_LENGTH limitations) in a
version 3.x Sqlite database i noticed the following issues :

When loading an .sql file containing "INSERT INTO tab1 (?,?,?) VALUES(?,?,?);" commands from the "Execute SQL" tab of application's interface and clicking the "Execute SQL" to run the script there is no visual indication somewhere in the application's window e.g. a progress indicator in the status bar or at least an hour glass icon change for the mouse cursor to show that a script is currently running. Furthermore, the "Write Changes" button is enabled right after clicking the "Execute SQL" button whether or not the script ends successfully and no matter the commands contained in the script are included within a "BEGIN TRANSACTION; COMMIT;" block or not. Also, if the script runs successfully the execution status message reports affected records count wrongly and always says "1 rows affected" even if script contains more than one records and finally the execution status message takes some time(a few seconds) to appear after script completes its execution something very bad because if someone accidentaly clicks the "Write Changes" button before execution status message appears then only part of the inserted records is commited to the database opening data integrity issues.

Thank you very much.

System used for running DB Browser for SQLite :

Windows 7 Professional 64bit  ( fully updated )
CPU: Intel Core i3 Quad Core 3.1GHz
Ram : 4GB
DB Browser for SQLite version : SQLiteDatabaseBrowserPortable_3.10.1_English.paf.exe

**Comment by chrisjlocke** [comment]
Hi,

Thanks for your detailed response.

v3.10.1 was released in Sep 2017 - nearly 8 months ago.  
I'd try the nightly versions, available here:
https://nightlies.sqlitebrowser.org/latest/

While they're not portable, the files can be taken from the 'latest' and replaced in the 'portable', creating a new portable version.  

A lot of changes have occurred from the 3.10.1 to the nightlies.  Yes, really there should be a 3.10.2 or 3.11, but the wheels of change are large and covered in ivy, so in the meantime, use v3.10.99 ..... !

**Comment by mgrojo** [comment]
@jimmyp2 If you try a nightly version (https://nightlies.sqlitebrowser.org/latest/) you'll see that most of the reported concerns are already addressed. Could you take a look?

**Comment by mgrojo** [comment]
@jimmyp2 We have just released [version 3.12.0](https://sqlitebrowser.org/blog/version-3-12-0-released/) which includes an hourglass icon in the tab and a message and button in status bar for cancelling the query. I think your issue is already addressed, but feel free to reopen this if you consider there is still something that should be improved.
