### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by DorisHarry** [sqlitebrowser/sqlitebrowser#1379]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Hi @DorisHarry 

You've provided no details on why you've opened a ticket.
Could you kindly provide some details so someone can assist you? Unless you just want me to pop round and bake you some rock cakes?

**Comment by chrisjlocke** [comment]
I'll close this, as it must have been created in error.
@DorisHarry - feel free to reopen it with more details.
