### ISSUE TITLE
Ensure silent mode installation upon re-installation.

### ISSUE THREAD

**Issue by publicst** [sqlitebrowser/sqlitebrowser#1389]
Details for the issue
--------------------

#### What did you do?
Attempting to re-install the DB.Browser.for.SQLite-3.10.1-win64.exe /S using command line

#### What did you expect to see?
Overwrite happens without anything displayed just like initial installation and uninstall with /S flag

#### What did you see instead?
Messagebox with "DB Browser for SQLite is already installed...."
Work around is to uninstall silently and re-install silently but would be nice if we did not have to do this.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10.0.16299 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
@justinclift What is CMake version in your build system? I'm asking because I used `/S` switch with the stable version 3.10.1 and the latest nightly build and got the same issue as @publicst. But when I used it  with an installer I built on my system, the `/S` switch worked as expected.

I'm guessing you are using version older than 3.7.0 cause I kept installing all versions, one by one, till I found out that this problem is gone with CMake v3.7.0 and higher.

Updating CMake and changing this line should fix it.
https://github.com/sqlitebrowser/sqlitebrowser/blob/1865272aa85c6cb0ef557a6b4be436fc0f3e27a3/CMakeLists.txt#L2

**Comment by justinclift** [comment]
Ahh, thanks.  I can check the machine tomorrow.  I suspect it'll be version 3.6.something, but not sure. :smile:

**Comment by karim** [comment]
@justinclift Did you mange to upgrade CMake to fix this issue?

@publicst Our latest nightly (https://nightlies.sqlitebrowser.org/latest/) now includes .msi installer. Maybe you can give it a try and see if it helps with your use case? Type `msiexec.exe /?` to get the list of command-line switch.

**Comment by justinclift** [comment]
> Did you mange to upgrade CMake to fix this issue?

Nope.  Saw the note about CMake 3.11.x on the wiki, so carefully installed CMake 3.10.<something> when setting up the new build VM.  Didn't hit the issue. :wink:

**Comment by justinclift** [comment]
Ahhh.  It sounds like I'd better up the CMake version on the build server itself too.

I'll get that done now.

**Comment by justinclift** [comment]
k, our build VM has been upgraded to CMake 3.10.3.

**Comment by publicst** [comment]
@karim I confirmed that the nightly build from https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.exe was able to reinstall silently with "/S" flag!
Thank you very much!

One question would be when and how does the official version get updated?

**Comment by karim** [comment]
I'm glad it's working now. :smiley: 

> One question would be when and how does the official version get updated?

Hopefully soon. :smiley: We have made a lot of changes and we are just waiting to finalize a few things and for our devs to be free.

Feel free to close this issue if your problem was solved, and sorry for the delay to get this done and not fixing it sooner.
