### ISSUE TITLE
Hitting "Delete" key doesn't do what you expect, kills app, and probably your DB

### ISSUE THREAD

**Issue by broofa** [sqlitebrowser/sqlitebrowser#1391]
1. Have a table with a unique primary key constraint on at least one column.  Have 1,500 rows in that table.
1. Go browse that table
2. Select All
3. Hit the "Delete" key

**Expected result**:  All rows get deleted from the DB in a single transaction (preceded by a "Are you sure you want to do this?" dialogue, of course).  Note: This is the behavior for the Sequel Pro app.

**Actual result**: App tries to null out every single field of every row, using a separate query for each [field,row] tuple, which seems horribly inefficient but hey, it works.

... except it doesn't.  Instead, the primary key constraint gets violated and you start getting alerts about `Unique Constraint Failed`.  Click "okay"... another alert... click "okay" again... another alert ... repeat 1,500 times for every row in your table.  Or, in practice, resign yourself to the app being toast and `kill -9` it from the command line.

And for bonus points, notice that your DB has been corrupted because only some of the fields in some of the rows have been set to null and... ah, screw it, I'll just restore from backup.

(But, thank you for an awesome app!  Seriously. It's been really helpful!)

**Comment by broofa** [comment]
MAcOS 10.13.2
DB Browser for SQLite 3.10.1
Qt Version 5.7.1
SQLCipher Version 3.15.2

**Comment by broofa** [comment]
Note:  The reason I'm getting the unique constraint error is that the primary key column doesn't have `NOT NULL` on it (my bad).  So once the first row's key is NULL'ed out, attempts to null out the key in subsequent rows fail.

**Comment by justinclift** [comment]
Thanks.  If you have a minute to try with our latest nightly version then it's possible this might be fixed already.  We're getting kinda close to the next release, so there's lots of bug fixes / tweaks / similar in our current nightly builds. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If that helps. :wink:

**Comment by broofa** [comment]
Still an issue

![image](https://user-images.githubusercontent.com/164050/40271692-a8f657dc-5b55-11e8-8045-c4911239bd2d.png)

![image](https://user-images.githubusercontent.com/164050/40271701-c3ee7e34-5b55-11e8-9eac-d600274ece2f.png)

**Comment by justinclift** [comment]
Doh! Oh well.  So much for hoping.

Thanks for checking @broofa. :grin:

**Comment by MKleusberg** [comment]
Can you try again with tomorrow's nightly build, @broofa? I have just changed it so that selecting an entire row (or multiple rows, or all rows as in your case) and hitting the delete key actually deletes the record(s) and doesn't just clear the cell contents. That should solve the immediate issue you're facing here :smile:

**Comment by broofa** [comment]
Appears to be fixed in nightly. Feel free to close.  Thanks!

**Comment by justinclift** [comment]
Excellent.  Thanks for checking @broofa. :smile:

Well done @MKleusberg. :grin:
