### ISSUE TITLE
Application Crashes when Using Filters

### ISSUE THREAD

**Issue by resech** [sqlitebrowser/sqlitebrowser#1392]
Details for the issue
--------------------

#### What did you do?
In the browse data screen, entered a value in the filter box for a column. Since it may be relevant, the database has 4300 rows.

#### What did you expect to see?
All rows matching the filter.

#### What did you see instead?
The application crashed.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 10.13.4)
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: Nightly 20/5/18 (I first noticed this issue in the 17/5/18 build, that's the first time I attempted to use the filter).

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oh wow.  That's definitely not supposed to happen!

When it crashes, is some kind of error information or crash report displayed?  That would be helpful. :smile:

As a quick test here, I've just tried the same thing on OSX 10.11.6 with last night's build of DB4S.  Wasn't able to get a crash happening using a toy database here.

Would you be ok to share the crashing database with us, and an example filter phrase that's crashing, so we can investigate in depth? :smile:

**Comment by MKleusberg** [comment]
It's definitely worth trying again with today's nightly build. I had some issues with the filters too (though no crash) and tried to fix them in the 17/05/2018 build. While fixing the original problem the patch had it's own problems (but again no crash for me) which are now finally solved in today's build :wink: So it was probably my fault and will just work with the newest version, at least the dates seem to indicate that.

**Comment by resech** [comment]
@MKleusberg it appears resolved in the 21/05/2018 build. Saves me from trying to come up with a sanitised database to share :)

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by MKleusberg** [comment]
Cool, thanks for testing, @resech :smile:
