### ISSUE TITLE
SQLite is creating a disk file for In-memory DB

### ISSUE THREAD

**Issue by abhishekginani-tm** [sqlitebrowser/sqlitebrowser#1397]
I tried to create a shareable in-memory database as per the documentation provided on SQLite  Site. But I end up finding the solution to the problem. 

**Here is my code in C#:**
```
 var connectionString = "Data Source=sharedmemdb;Mode=Memory;Cache=Shared";

            using (var connection1 = new SQLiteConnection(connectionString))
            {
                connection1.Open();

                var command1 = connection1.CreateCommand();
                command1.CommandText =
                    "CREATE TABLE Message ( Text TEXT );" +
                    "INSERT INTO Message ( Text ) VALUES ( 'Is there anybody out there?' );";
                command1.ExecuteNonQuery();

                using (var connection2 = new SQLiteConnection(connectionString))
                {
                    connection2.Open();

                    var command2 = connection2.CreateCommand();
                    command2.CommandText = "SELECT Text FROM Message;";
            
   
                    var message = command2.ExecuteScalar() as string;
                }
            }
```
If I execute this code, it will create in-memory DB named as **sharedmemdb**  and shared cache is enabled while making the connection, so this connection accessible to other connections also. If I run this first time this works pretty fine but if I close the application and run again it throws error "Table Message already exists" and this looks very strange as I created the table in-memory and this should not be available if application restarts. 

After getting this error, I looked into the application directory and found the file "sharedmemdb" which means SQLite is not creating the shareable in-memory DB.

Any clue why this is happening?

**Comment by justinclift** [comment]
Yeah, we've just never added support for in-memory databases (#335). It probably wouldn't be hard to do.

A few people have already requested this, thinking it would enable shared-access to an in-memory database among applications.  That's not something that would work though, as the in-memory database itself can only be inside a single application.

In practical terms, having the database be written to disk (and needing manual cleanup after) is a minor thing.  So... hasn't been a high priority. :wink:

**Comment by MKleusberg** [comment]
@abhishekginani-tm I think you're in the wrong place here :wink: Your question is about SQLite in general or about the .Net bindings for it, but this is the site of a GUI for SQLite databases. So there's nothing we can do here.

That said, I would change it to ```"Data Source=:memory:;Mode=Memory;Cache=Shared"``` and try again :smile:

**Comment by abhishekginani-tm** [comment]
@MKleusberg : Thanks, I will post it in right place. This `"Data Source=:memory:;Mode=Memory;Cache=Shared" ` connection string is not working.

**Comment by abhishekginani-tm** [comment]
@MKleusberg : Please suggest the link where I can post this question.

**Comment by justinclift** [comment]
Ahhh, you're after the SQLite-users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

There are heaps of helpful, knowledgeable people on there.  You'll be in good hands. :smile:

**Comment by abhishekginani-tm** [comment]
Thanks for the support.

I was using `System.Data.SQlite` namespace which doesn't supports that. Changing it to a namespace `using Microsoft.Data.Sqlite;`  allows me to access memory DB.

**Comment by justinclift** [comment]
Cool.  I'll close this then, as it sounds like it's solved. :smile:
