### ISSUE TITLE
Windows installer can hang

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1399]
Came across a report of the DB4S installer hanging, or taking an extremely long time, on Windows:

&nbsp; &nbsp; https://github.com/LibraryCarpentry/lc-sql/issues/13

It's **probably** something to do with the Visual C+ redistributable, but that's just a first guess.

The workaround is to use the PortableApp version, as that doesn't bundle the Visual C++ redistributable.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows

#### What is your DB4S version?

- [x] 3.10.1

**Comment by justinclift** [comment]
As a data point, several people that experience this hanging behaviour are sharing useful info in the original GitHub repo issue this was reported in.

**Comment by justinclift** [comment]
Good point.  We could make a debugging build for people to try, and see if anything useful shows up.

**Comment by justinclift** [comment]
This is line that launches the command: https://github.com/sqlitebrowser/sqlitebrowser/blob/39302f5b6061cf687a81984406e20070d60b4563/CMakeLists.txt#L519

I'll start a build without the `/quiet` option in a minute, and point people at it. :smile:

**Comment by justinclift** [comment]
Ahhh, [looks like](http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html) we should turn off `/passive` too for this exercise.

**Comment by justinclift** [comment]
Ahhh, it can also take a `/log log.txt` option.

Probably best to include that as well.

**Comment by karim** [comment]
Actually, I think we should move from NSIS and create a MSI installer instead. It is being requested a lot.

I started doing that a few days ago and I'm almost finished. I'm not doing it with CPack WIX, but using WiX Toolset. I should be making a PR in a couple of hours (after doing some tests) or tomorrow.

Good thing about MSI is that VCRedist is bundled with it (as a merge module) and we no longer need to include vcredist.exe anymore. Also we no longer need to include/run `winlaunch.bat` after setup to launch the application in the context of the current user (not admin), since MSI can do that automatically.

@justinclift You should download [WiX Toolset](http://wixtoolset.org/releases/) and install it on the build machine so we can start building `.msi` installers.

**Comment by justinclift** [comment]
Cool.  CPack is a major pain. :smile:

**Comment by justinclift** [comment]
WiX Toolset v3.11.1 is now installed on the Windows build box.

**Comment by karim** [comment]
Very good. I should make a PR soon.

**Comment by justinclift** [comment]
Looking into some log files which @JReally has kindly emailed me for an installation run which hangs.

The log file itself is pretty short.  These two lines in it seem to confirm the hang and indicate a potential source of the problem:

```
[154C:1470][2018-05-31T10:29:00]i300: Apply begin
[0F60:1050][2018-05-31T10:35:06]w308: Automatic updates could not be paused due to error: 0x80080005. Continuing...
```

Note the timestamp in the 2nd column, showing a delay of 6 minutes and 5 seconds between those two entries.  It looks like a timeout failure of some variety happened, which generates that error.

Doing some searching online for that error code, it seems like an issue with Windows update.  I've asked @JReally if the Windows Update service is disabled or otherwise customised.

Kind of hoping that's the case as that'd mean we've figured out the right area to look into.

Oh... I wonder if the problem might also be a network layer thing.  Maybe caused by Windows Update trying to talk to the MS update servers (or similar), and being blocked + timing out by the network in use.  eg something like a firewall rule blocking updates

**Comment by justinclift** [comment]
Relevant StackOverflow error, from someone else having the same problem:

* https://stackoverflow.com/questions/44197835/wix-toolset-installs-vc-redistributable-x86-2015-too-slowly

It does seem to be Windows Update related.

**Comment by justinclift** [comment]
Further useful link: https://stackoverflow.com/questions/49526820/wix-behaving-badly-on-xp-machine-with-windows-update-issues/49534494#49534494

There's also mention from someone that when they built their installer with a newer version of WiX (3.11), they received a proper error message instead of this weird hang.  I'm not sure what WiX version is used by the Visual C++ redistributable in this case, however it's likely to be fairly old.

The new MSI approach we're testing out now might lead to us getting a better error message in this situation.

**Comment by justinclift** [comment]
The nightly build process to create .msi installers ran for the first time tonight.

It runs as part of our standard nightly Windows build process, and for each .exe build it also creates an equivalent .msi.

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

In theory, the .msi ones shouldn't hang for people, and they're also a bit smaller in filesize.

I'm not sure if the .msi's are a complete replacement though... as in, if we could potentially drop creating the .exe's and just provide the .msi's instead.  @karim, hoping you know. :smile:

**Comment by karim** [comment]
Yes, they are. We can stop creating .exe build. But I'd wait till we close some of the open issues regarding the old NSIS installer and see if the new one fixed them. Most complaints about it were about vcredist, its silent switch, and some features request which we can do with the new one.

**Comment by chrisjlocke** [comment]
I installed a nightly from a couple of days ago (via MSI) and the latest from this morning.
When I installed from this morning, it gave no impression it found the previous install - I was asked to accept the licence agreement, which directory did I want to install into, etc.  However, after installation, it had removed the older version.
Doing this silently is a bit naughty - if I'd wanted that particular nightly for a specific reason, then its now gone.  If I run the latest .msi again, I now get the 'change repair uninstall' option - I didn't get this this morning.
![image](https://user-images.githubusercontent.com/7872218/40883890-509cb1ac-66ff-11e8-9ce1-da9e424e33e0.png)

I'll try again with tomorrows nightly to confirm/deny this part of the issue...

Also, is there a switch to make the install directory auto complete?  Normally when you start entering a directory name, the box autocompletes and fills in the name from the filesystem.

![image](https://user-images.githubusercontent.com/7872218/40883904-c0780350-66ff-11e8-9e0d-6daa67f66b6b.png)

**Comment by karim** [comment]
> When I installed from this morning, it gave no impression it found the previous install

I think this is how Windows Installer works.

For example, If you installed .msi file and tried to re-run **the same** .msi file, it will show you the options to modify/repair it, since you already installed it. But since we rebuild the .msi every night (for nightly) it gets a different product code, but it has the same upgrade code, so it can upgrade older versions of itself. Still, it is considered a different installer.

> Also, is there a switch to make the install directory auto complete?

Not that I know of. If you want to automate installation to a specific directory, maybe you can do something like.. `msiexec.exe /i db4s.msi TARGETDIR=d:\downloads\`

**Comment by justinclift** [comment]
Hmmm.  With the silent auto-uninstall of the previous version, that's a change in behaviour from the existing .exe installers.

We should probably put some info about that in an obvious place during the installer run, prior to it "doing anything".  Just so there's less chance of negatively surprising whoever is doing the install. :smile:

**Comment by karim** [comment]
> We should probably put some info about that in an obvious place during the installer run, prior to it "doing anything".

We can do it in the welcome dialog. The first thing that shows up when you start the installer. I can do it now. Just tell me the exact message to put there. :smiley:

**Comment by justinclift** [comment]
Excellent, how about something like:

    If you have a previous version of DB Browser for SQLite already installed, this installation
    process will update it.

I think that's pretty clear, and probably ticks all the right boxes. :smile:

**Comment by JReally** [comment]
I can't test this until tomorrow's build but 

"If you want to keep the current version install this version in a different folder"

**Comment by chrisjlocke** [comment]
@jreally- That doesn't work. The new installer will uninstall before it installs, regardless of where you install it. And it does it silently, which is even nicer...

**Comment by karim** [comment]
From my perspective, as a user, asking me to uninstall first then install every time I'm *updating* an application seems redundant. I already know that I have the application installed, and I'm installing a newer version, hence I'm updating it. This [comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/500#issuecomment-173692991) talks about the same thing. (@justinclift #500 should be closed? :smiley:)

However, I do understand that there are other use cases for the current NSIS behavior. Mainly the multi install trick, by clicking cancel (do not uninstall) then proceed to install in a different folder.

I see the reasons behind multi install:

1. Installing the same version but in different folders, to have some kind of different settings/configs. I don't know how this works, but in Windows the settings are saved in the registry, so all these different installations will have the same config.
2. Installing different versions in different folders. For testing or trying out new feature/bug fix without messing up with your current install, while still having the same settings shared between all versions, which is a pretty good thing.

I see # 1 can be addressed by a Portable version, where your settings are saved in the application folder. # 2 shows a very nice use case and I don't know how we could address this in a better way using the MSI installer.

My suggestion is to make it easy for most of the users, that only want to download, install, use, and when a new version is out there, they update their current installation, without extra dialogs. Then we find a way to address the use cases for the power users.

**Comment by justinclift** [comment]
Thanks, just closed #500. :smile:

And yeah.  I\m tending to also think we should keep things streamlined for non-power-users, and figure out some way of giving flexibility to the people that need it.

The currently situation with nightly builds is sort of like that anyway.  We're providing the encryption enabled option on our releases page + website, as that gives people a few options to easily choose from.

However our more in-depth users know they can get other things (eg latest SQLite build instead) from the nightlies server.  That seems to provide both audiences with what they need, in a way that seems to work decently. :smile:

**Comment by JReally** [comment]
June 4th builds didn't appear

**Comment by justinclift** [comment]
Oh.  Yep, something seems to have gone wrong with the Windows build process.

I'll look into it shortly.

Thanks @JReally. :smile:

**Comment by justinclift** [comment]
Found the problem.  I'd forgotten to remove a few `pause` statements in the `winbuild.bat` script, when I was debugging.  So, the build script didn't get very far into it's run.

The script has now been fixed, and I've just launched the process again.

**Comment by justinclift** [comment]
The nightly builds are there now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by JReally** [comment]
June 4 build still shows June 3 in the "About"

**Comment by justinclift** [comment]
Gah.  Checking now.

**Comment by justinclift** [comment]
Hmm, I just downloaded and installed this one:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher-win64.msi

For me, it's saying 4th June in the About dialog:

![screenshot1](https://user-images.githubusercontent.com/406299/40928258-c8289cf8-6818-11e8-957e-37c10fa0c784.png)

Which one did you grab?  I'll try that next. :smile:

**Comment by JReally** [comment]
DB.Browser.for.SQLite-sqlcipher-win32.msi

**Comment by justinclift** [comment]
Thanks, giving it a go now. :smile:

**Comment by justinclift** [comment]
Hmm, that one's saying 4th June for me as well:

![screenshot2](https://user-images.githubusercontent.com/406299/40929899-fefc2128-681d-11e8-920d-a1cd69e3f03b.png)

Is there any chance there's an install from yesterday still hanging around on your system somehow, and that's the one that got launched?

I *think* that's the likely thing here.  There's also the possibilty that nginx (web server software on the nightlies download box) was caching things wrong.  I've not seen that before, but who knows... :confused:

**Comment by JReally** [comment]
did you try the 32 bit cipher?

The screenshot is not the cipher version.

**Comment by justinclift** [comment]
Doh.  I misread yours as SQLite.  **sigh** long day. :wink:

**Comment by justinclift** [comment]
Just tried the right one this time :grin:.  It's saying 4th June as well:

![screenshot3](https://user-images.githubusercontent.com/406299/40930515-cd116b26-681f-11e8-9e55-c269578d634a.png)

**Comment by justinclift** [comment]
Hmmm, I'll try from a different PC too, just in case...

**Comment by JReally** [comment]
OK... I'll start over. I had already previously uninstalled (manually) and removed all related folders. Here I go again! I'll report back.

**Comment by justinclift** [comment]
No worries. :smile:

@karim added a commit earlier today (captured in these builds) which automatically adds a desktop shortcut too.

Might be useful to try launching it from that too, just to see if a different version of it somehow launches using your normal launch approach. :smile:

**Comment by justinclift** [comment]
Ok, it's definitely 4th June when downloaded and installed on a different PC as well.  It's definitely looking like the one on the server itself is ok. **\*whew\***

**Comment by JReally** [comment]
All good... sorry about this.  Not sure that I can identify exactly what happened. Before I reported it, I was fairly sure I had deleted all previous references and retested... obviously I missed something. I did jump on the downloads (originally) literally moments after Justin had set the June 4 version on-line.  I downloaded a fresh copy for the latest test... so was there some cache issue?  who knows.

**Comment by justinclift** [comment]
No worries at all @JReally.  It's good when problems turn out to be simple to fix. :smile:

**Comment by justinclift** [comment]
Hmmm, the nightly build script make the .exe's fine last night, but the .msi's aren't there.

Investigating again...

**Comment by justinclift** [comment]
On a related note, SQLite 3.24.0 was released a few days ago and looks like it has useful things included:

&nbsp; &nbsp; http://sqlite.org/releaselog/3_24_0.html

Items 1, 9, 13, 16 stand out to me.  After I get today's .msi weirdness solved, I'll update the SQLite version on the build server so tomorrow's SQLite specific builds include that.

**Comment by justinclift** [comment]
Interestingly, when I manually launch `winbuild.bat`, the .msi files are built fine.  However, when its' launched from Task Scheduler the .msi files don't build.

Managed to capture an error message from the Wix bits, which should help track down the problem:

```
light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0217 : Error executing ICE action 'ICE02'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0217 : Error executing ICE action 'ICE04'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0217 : Error executing ICE action 'ICE05'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0217 : Error executing ICE action 'ICE06'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0217 : Error executing ICE action 'ICE07'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0216 : An unexpected Win32 exception with error code 0x643 occurred: Action - 'ICE09' Fatal error during installation
```

**Comment by justinclift** [comment]
Well, the info in the [URL in the error message](http://wixtoolset.org/documentation/error217/) isn't at all helpful (to me).

@karim Any idea how to solve this?

**Comment by justinclift** [comment]
Ahhh, this might do the trick:

https://stackoverflow.com/questions/1064580/wix-3-0-throws-error-217-while-being-executed-by-continuous-integration

I'll turn on that SuppressValidation thing, and see if the .msi's build.

**Comment by karim** [comment]
I think it might be related to the user account on the system. Are you running the build script on a non-admin user account?

**Comment by justinclift** [comment]
Yeah, it's a local user account.

But, the `-sval` fix works well enough, so I'm calling this "done". :smile:

**Comment by justinclift** [comment]
Closing this, as the new MSI based installers shouldn't be able to hang, and we're also providing .zip based ones now too.  eg unzip it and people are ready to go.

If **that** hangs, then there's something really, really wrong. :wink:
