### ISSUE TITLE
Export button in Browse Data tab

### ISSUE THREAD

**Issue by ch728** [sqlitebrowser/sqlitebrowser#1402]
Describe the new feature
--------------------------
Export button under Browse Data tab that would allow the user to export after filtering

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Do you have a screenshot? Please add screenshots to help explain your idea.

Under Execute SQL there is a button that let's you export the table after running a SQL query (circled in red below)
![image](https://user-images.githubusercontent.com/36375878/40858676-1f79fd6c-65ad-11e8-8ffa-7c4044d74443.png)

It would be nice to have the same button under the Browse Data tab that would allow the user to export after filtering.

**Comment by mgrojo** [comment]
Good idea, @ch728. If you try our nightly build, you will find a new button in the Browse Data for saving the current filtering as a new SQL view. That is only a step away from a CSV export.

But this new feature makes a lot of sense and it is feasible.

**Comment by mgrojo** [comment]
@ch728, the feature is now implemented. If you install a nightly build or compile yourself from the repository, you will find a similar popup menu in the 'Browse Data' tab as in the 'Execute SQL' tab.

![imagen](https://user-images.githubusercontent.com/13812910/40873634-63c1806e-6664-11e8-91f2-add3e0a3b0c0.png)

I copy here the What's This info for the button:

> This popup menu provides the following options applying to the currently browsed and filtered table:
> 
> - Export to CSV: this option exports the data of the browsed table as currently displayed (after filters, display formats and order column) to a CSV file.
> - Save as view: this option saves the current setting of the browsed table (filters, display formats and order column) as an SQL view that you can later browse or use in SQL statements.
> 

If it works for you, please close this issue.

**Comment by justinclift** [comment]
Well done @mgrojo. :smile:
