### ISSUE TITLE
[Discussion] Create a Slack team

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#1406]
Hey guys, I was thinking of moving the discussion from Gitter to Slack and I was wondering if it's something everybody feels good about this or not.

Knowing this, I'll post some questions to which you can react with :+1: or :-1:.

**Comment by justinclift** [comment]
Does this need to be a Gitter **or** Slack thing?  As in, can't we just start a Slack channel as well and see if it gets used? :smile:

**Comment by revolter** [comment]
That would be ok too, though I think that the target would be for, at least the contributors, to use the same platform.

**Comment by karim** [comment]
Didn't know we have Gitter. :scream: I think I went there once and forgot maybe. :smile: 

But I think live chat is a good idea. We usually fill the issues/PRs with a lot of comments and better some of it move out of issues.

Do I have to downloaded an app (electron-based?) or the web app is enough? Can I use an IRC client to connect?

**Comment by revolter** [comment]
@karim, They both have web and desktop clients, so you can use whatever you see fit, but I don't know anything about IRC.

**Comment by karim** [comment]
@revolter IRC as in [Internet Relay Chat](https://en.wikipedia.org/wiki/Internet_Relay_Chat). I think Gitter has an IRC [gateway](https://irc.gitter.im/). I will probably use the web client for now. Thanks Iulian. :smiley:

**Comment by chrisjlocke** [comment]
Not used Slack before, but then I don't use Gitter much either...

**Comment by iKlsR** [comment]
Both are easily accessible via web so no need to install anything. My biggest gripe with both are that gitter is a ghost town, it's not very attractive and traffic is always low based on the several channels I use (for popular software), slack on the other hand is more widely used (in most cases people will just add another channel to their existing stack) but Slack has a max cap of ~10k messages so we might lose crucial or important discussions if it gets popular or in due time and we also can't share stuff publicly without people joining.

My suggestion - reserve an IRC channel on freenode.net for the power users and developers and keep other issues here on github. If not I prefer gitter over slack in terms of openness and as an irc user I can use the gatway if needed. I believe slack also had one and recently closed it as well.

**Comment by justinclift** [comment]
Yeah, Gitter (the software/project) seemed to start out well.

But it looks like something went wrong internally with their team at some point, so the end user software didn't get past "basic working functionality".

All of the weird behaviours/bugs + user-unfriendly bits are still in place and make it not very pleasant to use.  Doesn't seem like that'll ever change either. :frowning:

That's just my impression though.  No inside knowledge or anything. :smile:

**Comment by justinclift** [comment]
For reserving an IRC channel, if that's something we can do easily then sure, why not.

We'd have to have some people (not me) look in on the channel at least daily, and do their best to answer questions (etc).

Same for a Slack channel too though I guess. :smile:

**Comment by revolter** [comment]
I most likely won't use IRC because I'm not used to it at all and I think it's a bit harder to set up for any user that Gitter or Slack. I would use Slack because I'm already using it for work and for other open source projects, so I have it opened all the time. Gitter on the other hand, I was opening it only in the beginning, then when I needed something, and lately almost never. Also, IRC feels old-ish and I'd argue that Slack, with all the hype around it and being new, would attract more people.

Disclaimer, I am very very subjective, I know, so feel free to disregard my comments.

**Comment by iKlsR** [comment]
IRC is also easily available at https://webchat.freenode.net/. Anyone can create a channel, just type `/join channelname`, then register it after with a similar command. I also wouldn't mind slack at all but we would probably have to get a paid plan eventually to preserve history easily https://jahshaka.slack.com/plans.

I'd say to just create the slack channel and see what happens. As the proposer you would have to manage it and keep an eye out initially however ;)

**Comment by revolter** [comment]
I created https://db4s.slack.com which you can join by following this link: https://join.slack.com/t/db4s/shared_invite/enQtMzc3MzQ0MDAyNDgzLWYwOTA1MDZlYjdhN2JiNWVjMTViYjA2YjliZjA5ODFkMjljMTJiYjZlY2IwNDVlMmYwYzZhY2VmZTRhMjRmNDQ
