### ISSUE TITLE
Is it possible to sort on multiple columns?

### ISSUE THREAD

**Issue by Llaves** [sqlitebrowser/sqlitebrowser#1407]
In the browse data view, clicking on a column heading sorts the data by that column, as expected.
What I'm trying to do is sort on two columns as primary/secondary key.
In some GUIs this is achieved by using a stable sort with respect to the current view. As best as I can tell, DB Browser is using a stable sort, _with respect to the database_, not the current view.

**Comment by sky5walk** [comment]
View the SQL Log panel for the query performed with your single column sort.
Use the Execute SQL panel for complex sorting.

**Comment by justinclift** [comment]
Yeah, we don't yet support sorting on more than one column.  It'd be a useful feature, but it's not something we've gotten around to yet. :wink:

**Comment by Llaves** [comment]
Thanks for the super-prompt replies.
The Execute SQL tab approach is doubly not friendly. Adding the additional sort field is not hard, but unlike the browser view, there is no "delete row" button, so the sorted result is read-only.
Can't have everything (and I guess if I wanted it bad enough, I'd learn the source and modify it).

**Comment by justinclift** [comment]
Heh Heh Heh

If you do get motivated to learn the source and modify things, we welcome Pull Requests.

That's actually how several of us got started. :grinning:

**Comment by jondo** [comment]
I suggest to reopen this as a valid feature request (even if not currently a priority). I nearly filed a duplicate since I did not find this among the open issues.

**Comment by mgrojo** [comment]
This is implemented in the nightly builds (#1761) and it will be released in the future 3.12 version. The  multi-column sorting is triggered using Ctrl+Click over the columns in the wanted order.

**Comment by jondo** [comment]
Thank you, I can confirm this as fixed in "Version 3.11.99 (Jul 24 2019)" from the PPA.
