### ISSUE TITLE
Allow Insert/Update/Delete for Views on Browse Data tab

### ISSUE THREAD

**Issue by asperax** [sqlitebrowser/sqlitebrowser#141]
This is a feature request to allow Insert/Update/Delete user interface capability for Views on Browse Data tab.

Views are normally read-only in SQLite, however, SQLite supports using triggers on Views, which handle the write operations attempted against the View. When this is the case, the absence of a user interface for editing the view means you have to write SQL code to do so.

To avoid confusion, you might consider interrogating existing triggers for an "...INSTEAD OF [INSERT/UPDATE/DELETE] on <Viewname>..." trigger to determine what user interface options to expose. But if this is too complex, it might just be better to expose the options and return the result from the database engine, whether that's an error (because the view is read-only and doesn't have a trigger for the action) or otherwise. Of course this may conflict with your easy-to-use design philosophy (some users might dislike having the user interface indicate that edits are possible when they are not), in which case I guess the enhancement should be rejected.

**Comment by nowox** [comment]
It is been two Years, can we reopen this issue? 

Consider this database: 

```
BEGIN TRANSACTION;
CREATE TABLE Foo (a, b, c);
INSERT INTO `Foo` (a,b,c) VALUES (1,2,3);
CREATE TRIGGER update_bar
INSTEAD OF UPDATE OF a ON Bar
BEGIN
  UPDATE Foo SET a = NEW.a
  WHERE b=NEW.b;
END;
CREATE VIEW Bar AS SELECT a, b FROM Foo ORDER BY b;
COMMIT;
```

With `sqlite3` It is legit to write: 

```
UPDATE Bar SET a = 23 WHERE b = 2;
```

However, it is not possible to do it so on a View on `DB Browser for SQLite`. 

It would be a huge plus for me.

**Comment by justinclift** [comment]
It's pretty likely we'll support them at some point.  But it's not likely for the upcoming release (3.10.0), and we still a fair amount we need to get done for that. 😕

**Comment by nowox** [comment]
What amount of work this feature would represent? What are the concerned files? If I wanna build DB Browser for SQLite on Windows is there a VS project?

**Comment by justinclift** [comment]
This takes you through the complete developer environment setup process for Windows, along with getting DB4S built and running:

* https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

Does that help? :smile:

**Comment by nowox** [comment]
It's tough, but well documented ^^

**Comment by justinclift** [comment]
If you're up for getting it done (takes a few hours, though that's mostly downloading), be aware that some of the paths in the setup guide no longer match the ones hard coded in the source.  They're not far off, and it's easy to fix if you know to watch out for it. :wink:

The paths used in the source at the moment are: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt#L18-L30

(that's for 64 bit windows compiling)

Notice the "5.7" in the Qt path?  That'd likely need updating to "5.8".  Similar for the OpenSSL and SQLite paths in that highlighted section too, just make sure they match the directory structure you create when you go through the guide. :smile:

**Comment by nowox** [comment]
Great!

**Comment by MKleusberg** [comment]
@nowox Working on this now. Turns out to be trickier than expected but I might be able to push a first version this evening.

**Comment by MKleusberg** [comment]
Progress:
- [X] Update
- [ ] Insert
- [ ] Delete

Delete seems easy enough, insert however more tricky.

By default, views are still locked from editing because most databases don't have triggers in place for editing views. This means you have to enable editing for a view by browsing it, right clicking on the column headers, and clicking "Unlock view editing". You'll then be asked for the name of a unique column in that view. That's because we somehow have to decide how to address rows in the view and there doesn't seem to be any good way to find out a suitable column automatically.

**Comment by nowox** [comment]
Wooh that's nice. I should give a try

**Comment by MKleusberg** [comment]
It's been a long time but I have just added support for deleting from a view :smile:

**Comment by nowox** [comment]
Wonderful :) Thanks for your work

**Comment by MKleusberg** [comment]
I'll just leave a link to PR #1477 here because I think we can finally tackle inserting records into views when that PR is merged. Haven't thought this through though, so maybe there are still more preparations needed after that :wink:

**Comment by mgrojo** [comment]
There are problems with view editing in the alpha:
- [ ] The pseudo PK seems to not be applied again when switching back to the view (you cannot edit and the Delete Record button is not reenabled) or after refreshing.
- [ ] The 'Unlock view editing' check state persists when switching between views.

At first sight I don't get where is the problem in the code.

**Comment by shaun-ba** [comment]
@justinclift @MKleusberg When i assign a unique column, then try to edit a cell i get the error:

"Error changing data: cannot modify Shields-die_number because it is a view"

My intention is to edit cells within a view, and add entries. This is my intention because I was told a view is the only way to sort the database using multiple columns.

**Comment by chrisjlocke** [comment]
@MKleusberg - changing data in a view still displays an error.

![image](https://user-images.githubusercontent.com/7872218/49387627-38dcb980-f71a-11e8-8767-dc217fd15534.png)

**Comment by mgrojo** [comment]
@chrisjlocke How is the view defined? Have you set the "INSTEAD OF" triggers?

**Comment by chrisjlocke** [comment]
Just a straight view from a select.  No triggers defined.  Triggers are required if wanting to amend a view outside of Db4S, but not if via DB4S, correct?

**Comment by mgrojo** [comment]
No, we actually need the triggers. The update is performed by SQLite and it is requested by DB4S in the same way as if it were a table. That's why we need to define a key for the view, in order to do our usual update query:

```sql
UPDATE "main"."myView" SET "field1"=? WHERE "key"='value';
```

And SQLite requires the triggers to make the actual insertion in the appropriate table(s). Maybe it should be stated explicitly (or even checked) in the application. For the moment, I've updated the [Wiki page](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views) to mention it.

**Comment by MKleusberg** [comment]
Manuel is right about the triggers. You need to define them yourself because we can't keep track of what row comes from where and which cell is connected to which. That's actually difficult enough that I'm not even sure we can even check for the existence of such a trigger in a reliable way :wink: However, the empty ```IN(...)``` list you're mentioning is indeed a problem. I'll look into that in a second.

**Comment by MKleusberg** [comment]
Should be fixed now :smile:

**Comment by justinclift** [comment]
Just started the Windows nightly builders, so new builds for today should be available in an hour or so. :smile:

**Comment by cristilupascu** [comment]
Are there any updates for the Insert functionality for views? I would really love this feature and I am thinking of trying to implement it, if no one is working on it at the moment.

**Comment by mgrojo** [comment]
@cristilupascu Not sure which is the current state (specially after this @MKleusberg's [comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/141#issuecomment-413615197)) and haven't tested myself. I assume by your comment, that this isn't still working. I'm not working on it. Don't know about @MKleusberg, but I'd say that he isn't either.

**Comment by cristilupascu** [comment]
@mgrojo I see. Then I'll start looking through the code and see if I can figure it out. At the moment, the insert button is always disabled for views.

**Comment by justinclift** [comment]
Thanks @cristilupascu, that'd be awesome. :smile:

**Comment by cristilupascu** [comment]
Uff, sorry for all those references. I am pretty sure I added the Insert functionality without breaking anything for tables. Right now, for views, the AddRecordDialog is always used when inserting. The other method seems too complex to modify, so I won't be working on it.

**Comment by justinclift** [comment]
@cristilupascu Sounds like it'll be a good start. :smile:

**Comment by MKleusberg** [comment]
I have just merged @cristilupascu's pull request :smile: So starting with tomorrow's nightly build there should be inserting into views too now. Somebody still around to test this? We could finally close this issue then :wink: 

@cristilupascu Using the AddRecordDialog was also the way which I thought makes most sense. Inserting a row directly into the table probably won't ever work 100% correctly for views. Also I imagine some people might have an ```ON INSERT``` but no ```ON UPDATE``` trigger and the approach to insert a row directly requires both. So if no problems pop up in the tests, I think we can consider this finished :smile:

**Comment by MKleusberg** [comment]
Because I haven't heard of any problems with this, I'll finally close this issue :smile: I'd suggest considering this as done. So if there is any (remaining or new) problem with editing views, let's open a dedicated issue for that problem.

**Comment by bam80** [comment]
Please check if it's still an issue here: https://github.com/sqlitebrowser/sqlitebrowser/issues/1653#issuecomment-577445545
