### ISSUE TITLE
Windows binary detected as possible virus

### ISSUE THREAD

**Issue by davidedg** [sqlitebrowser/sqlitebrowser#1412]
Details for the issue
--------------------

downloaded latest stable and lastest nightly - both detected by VIRUSTOTAL as malware by 2 different engines

please see: 
[virustotal DB.Browser.for.SQLite-3.10.1-win64.exe](https://www.virustotal.com/it/file/2a04eceaf32d5a96a8a7d8a91f78fdd0bc8c44a5ae7f86cde568fee27d422d12/analysis/1528156433/)
[virustotal DB.Browser.for.SQLite-win64.exe](https://www.virustotal.com/it/file/6beedc0ee9bdf713e5c8a10068a88b31f63a551a22e98dd8ed08ddf3009a1f3a/analysis/1528173133/)

Useful extra information
-------------------------
#### Did you also

- [x ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @davidedg. :smile:

Looking at the result ([english version](https://www.virustotal.com/en/file/2a04eceaf32d5a96a8a7d8a91f78fdd0bc8c44a5ae7f86cde568fee27d422d12/analysis/1528156433/)) for our 3.10.1 release, it very much appears to be a false positive by the "Zillya" engine:

![virustotal1](https://user-images.githubusercontent.com/406299/40970787-8a7b3d34-68b3-11e8-9d83-e61b408161cd.png)

That page has a "comments" tab.  Clicking on it shows the false positive to be a heuristics match:

![virustotal2](https://user-images.githubusercontent.com/406299/40970867-c0096818-68b3-11e8-9aea-2b0212af9bba.png)

As best I can tell, the Zillya engine is matching common strings in our package.  Strings such as those belonging to [NSIS](https://sourceforge.net/projects/nsis/) (our .exe package creator), [StartCom](https://store.wotrus.com) (our signing certificate - will be changing soonish anyway), and various Microsoft domains.

Looking at the result for the nightly release ([english version](https://www.virustotal.com/en/file/6beedc0ee9bdf713e5c8a10068a88b31f63a551a22e98dd8ed08ddf3009a1f3a/analysis/1528173133/)), it's a different engine -" BKAV" - having an issue.

The information on the page says the detection is for `HW32.Packed.8587`:

![virustotal3](https://user-images.githubusercontent.com/406299/40971429-7baebf04-68b5-11e8-954d-1e38cde39ef2.png)

I'm not able to find much information about that error message.  This reddit comment seems to fit though, and also says it's a common false positive by BKAV:

https://www.reddit.com/r/qBittorrent/comments/89n5bx/virus_total_detected_this_engine/

> False alarm, if you google HW32.Packed you'll find it's a common false positive with programs that are compressed, it seems like the AV is saying "Hey, this program is packed, so I can't see everything it contains at the moment, could have a virus in there."
>
> Also, you may have noticed that only 1 out of 65 AVs detected it as being a virus, which is usually a very good sign that it's a false positive. I'd recommend reporting the false positive to BKAV, as there's been several people reporting this false positive and asking if it's safe to use qBittorrent recently.

To me, they both look like false positives.

What are your thoughts? :smile:

**Comment by davidedg** [comment]
I second this (FP) - it might be worth a note on the website / download links about this.
Bye!

**Comment by justinclift** [comment]
Thanks @davidedg.

If we get a bunch more people saying they're seeing issues like this on VirusTotal (or similar), then yeah it'd definitely be worth putting some kind of notice up.  Probably best to leave it off for now though, as we're friendly-to-newbies and don't really want to get them in the habit of ignoring potential malware warnings. :smile:
