### ISSUE TITLE
unable to modify table

### ISSUE THREAD

**Issue by amnakmahmood** [sqlitebrowser/sqlitebrowser#1415]
### Details for the issue

unable to modify table

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ __10_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
We need more info so we can solve this issue.

Without such info I'm just guessing here.. but are you sure the database file you are opening is not Read-only?

**Comment by amnakmahmood** [comment]
Yes, the file is not read-only. I tried to modify the table but am unable
to do so. I have already tried double-clicking and using Edit->Modify Table.

**Comment by justinclift** [comment]
Is there an error message or similar appearing when it happens? :smile:

**Comment by amnakmahmood** [comment]
No error messages, just unable to modify any highlighted cell.

*Amina Mahmood*
Computer Science Major
Cyber Scholar; CWIT Affiliate
UMBC Cyber Defense Club, Treasurer
University of Maryland, Baltimore County

**Comment by karim** [comment]
Can you try our latest nightly version here https://nightlies.sqlitebrowser.org/latest/ ? Maybe this was fixed in it.

**Comment by karim** [comment]
@amnakmahmood Are you still having issues?

**Comment by amnakmahmood** [comment]
No, downloading the nightly version worked!

Thanks!
