### ISSUE TITLE
CMake error due to unknown "qt5_use_modules" command

### ISSUE THREAD

**Issue by FriedrichFroebel** [sqlitebrowser/sqlitebrowser#1421]
Details for the issue
--------------------

#### What did you do?

Tried to build the latest master inside a clean clone using:

```
mkdir build
cd build
cmake -Wno-dev ..
```

#### What did you expect to see?

CMake runs without errors and I can build the application using `make` afterwards.

#### What did you see instead?

CMake throws an error:

```
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at libs/qscintilla/Qt4Qt5/CMakeLists.txt:172 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".


-- Configuring incomplete, errors occurred!
See also "/home/friedrichfroebel/tests/sqlitebrowser/build/CMakeFiles/CMakeOutput.log".
```

I am using `cmake version 3.11.3` with `Qt version 5.11.0`.

I additionally tried the version from #1419, but this gave me the same error.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ Manjaro Linux )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [X] Other: master branch

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  Is there any way you can drop back to an older CMake version?  We've previously had reports of problems with CMake 3.11, whereas the older versions work.

To be clear, the problem seems to be something in our source code that needs changing, rather than a problem in CMake itself. :smile:

**Comment by FriedrichFroebel** [comment]
No worries about downgrading - I just build the latest master from time to time, but use the DB4S version from the [repositories](https://www.archlinux.org/packages/community/x86_64/sqlitebrowser/) in my daily workflow (which seems to be prebuilt) as I expect the master to broken sometimes.

I decided to open this issue nevertheless as there has not been an existing one for this specific error.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by iKlsR** [comment]
Since we aren't using a `.gitmodules`, our libs/depsshould be updated as well. I was just playing around with #1419 but the changes in the CMakeLists there should be propogated to the deps as well as well as some policy macros to suppress some warnings.

**Comment by FriedrichFroebel** [comment]
With the latest update to `cmake version 3.11.4` and `Qt version 5.11.1` this aspect is resolved (see https://github.com/owncloud/client/issues/6517#issuecomment-398021244 for an explanation). Now #1361 appears during the build, so I am going to close this issue.

**Comment by justinclift** [comment]
Awesome.  Thanks for keeping an eye on it @FriedrichFroebel. :smile:

**Comment by GortiZ6** [comment]
Ok also for `Ubuntu 18.04` -> cmake `3.10.2-1ubuntu2` Qt `5.9.5+dfsg-0ubuntu1` gcc `7.3.0-16ubuntu3`
