### ISSUE TITLE
Patreon links in DB4S

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1425]
Note - This is just a reminder to myself (or anyone that gets to it first) so it's not forgotten. :smile:

We should add links to our new Patreon account in DB4S.

Two locations spring to mind:

* Something suitable in the About dialog
* Probably add some kind of link to our Help menu drop down list

**Comment by remram44** [comment]
Would you consider [Liberapay](https://liberapay.com/on/github/sqlitebrowser)?

**Comment by justinclift** [comment]
Sure, it shouldn't hurt to try it out.

That being said, Patreon seems more effective for people to sponsor OSS projects effectively. Liberapay seems to be achieving "[beer money](https://liberapay.com/explore/organizations)" levels.  

My first through here is to create a wiki page with the available options, but leave Patreon be the primay/direct link from the main in-GUI places.

**Comment by justinclift** [comment]
Just created an account with Liberapay, then went to associate it with that URL you gave.

Can't complete it though.  It wants access to completely unrelated repo's, that have nothing to do with DB4S. :frowning:

![liberapay-201807090648 1](https://user-images.githubusercontent.com/406299/42432799-60ea2038-8344-11e8-9346-794ec58690ca.png)

**Comment by remram44** [comment]
I don't think GitHub has finer-grained permissions than this, it will be able to read all your public data.

**Comment by justinclift** [comment]
Yeah.  It's a problem with the GitHub UI not allowing the user to actually choose the info shared.

Pretty much the same problem that Android users face when apps request blanket permissions, and Android doesn't give the user any option other than yes/no.

I contacted GitHub Support about it just after writing the above message, asking for the above dialog to have those tick marks (eg next to "Synthetos") be toggle-able to off (eg a cross mark, with no data for that org shared).  They've said it's been passed on to the relevant developers, so maybe it'll get done and be better for everyone. :smile:

**Comment by MKleusberg** [comment]
I've just registered with Liberapay too and connected to our Github account because I don't have any other organisations which they requested data access to. If anyone from the team wants to have a look at it, just email me :smile: For receiving money we'll need a PayPal or a Stripe account however and I don't have either of those (and I definitely don't want a PayPal account a don't know about Stripe :wink:). As soon as we have sorted this out, we could promote Liberapay :smile:

**Comment by justinclift** [comment]
Ahhh, good thinking. :smile:

With the Patreon thing, they're able to pay out either to a PayPal account or directly to a bank account (for a higher fee) using some other system (I don't remember the name, seemed ok though).  At the moment I have it going into my PayPal account, but agreed... PayPal has a bad rep due to their dodgy practises. :frowning:

**Comment by justinclift** [comment]
On that note, would you have time to add Patreon & LiberaPay links to the DB4S Help menu and About page?  My head is not even slightly in C++ mode atm. :smile:

**Comment by MKleusberg** [comment]
Sure :smile: Just added the menu item for Patreon. I'd wait with LiberaPay until we set up a way to actually receive donated money.

**Comment by justinclift** [comment]
Closing this, as the Patreon links are in place and seem to work ok.  We can get the LiberaPay approach done at a later point. :smile:

**Comment by justinclift** [comment]
As a potentially useful datapoint, this place seems reasonably well regarded too:

&nbsp; &nbsp; https://flattr.com

If Patreon goes down too dark a road, it's a decent alternative. :smile:
