### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by StatosphereSports** [sqlitebrowser/sqlitebrowser#1426]
#### I'm opening this issue because:

- [x ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ x] Mac OS: ( High Sierra version:10.13.4)
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
We need more details to be able to solve this. Is it crashing when it starts, or while doing something?

Also it is better if you try the latest nightly build (https://nightlies.sqlitebrowser.org/latest/), maybe it is fixed there already.

**Comment by justinclift** [comment]
As an additional thought, is some kind of error message being displayed when it crashes too?  If so, would you be ok to include a screenshot (or anything similar) to show the error message? :smile:

**Comment by justinclift** [comment]
Closing due to lack of response. :frowning_face:
