### ISSUE TITLE
incomplete Import from csv/flat file

### ISSUE THREAD

**Issue by MaRychly** [sqlitebrowser/sqlitebrowser#1427]
### Details for the issue
Hi All,

I have weird behaviour of browser. I'm not 100% sure, if this is a real bug.
I have flat file with nearly 2,000,000 records. Import-csv/load to DB table bypass every record # 8192. So the DB does not contains it. In this case I'm working with file having every CR/LF duplicated (0d0a0d0a). It is file provided by service provider.
The whole file is imported, anyhow there is missing 227 records which conforms to flat-file record count divided by 8192.
Is there something I could miss in the Preferences?

I'm using portable version with following ID'S. I'm running it on Win7 with 8GB RAM and Core i5
Version 3.9.1
Qt Version 5.7.0
SQLCipher Version 3.11.0

Thanks for help 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:7 Ent SP1 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [x] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
CSV import has changed drastically since version 3.9.1. We even [tweeted](https://twitter.com/sqlitebrowser/status/958826626845958144) about it. :smiley: 

Can you try the latest nightly build (https://nightlies.sqlitebrowser.org/latest/)? Or at least the latest version in https://github.com/sqlitebrowser/sqlitebrowser/releases (it is almost 1 year old).

**Comment by MaRychly** [comment]
OK, OK, :)
Thanks for response Karim.
I downloaded the latest version and all works as expected. 
Thanks for heads up
