### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by hasufell** [sqlitebrowser/sqlitebrowser#1439]
default cmake configuration, compiler is `gcc-7.3.0`.

```
[ 20%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscintilla2_autogen/mocs_compilation.cpp.o
cd /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5 && /usr/host/bin/c++  -DBUILD_VERSION=20180620 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DSCINTILLA_QT -DSCI_LEXER -I/home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5 -I/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5 -I/home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/include -I/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/. -I/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include -I/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../lexlib -I/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../src -isystem /usr/host/include/qt5 -isystem /usr/host/include/qt5/QtWidgets -isystem /usr/host/include/qt5/QtGui -isystem /usr/host/include/qt5/QtCore -isystem /usr/host/lib/qt5/mkspecs/linux-g++ -isystem /usr/host/include/qt5/QtPrintSupport  -O3 -DNDEBUG   -std=c++11 -fPIC -std=gnu++11 -o CMakeFiles/qscintilla2.dir/qscintilla2_autogen/mocs_compilation.cpp.o -c /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/mocs_compilation.cpp
In file included from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/EWIEGA46WW/../../../../../../libs/qscintilla/Qt4Qt5/ScintillaQt.h:44:0,
                 from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/EWIEGA46WW/moc_ScintillaQt.cpp:9,
                 from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/mocs_compilation.cpp:3:
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:48:19: error: expected identifier before numeric constant
 #define SCI_START 2000
                   ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:70:9: note: in expansion of macro 'SCI_START'
         SCI_START = 2000,
         ^~~~~~~~~
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:48:19: error: expected '}' before numeric constant
 #define SCI_START 2000
                   ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:70:9: note: in expansion of macro 'SCI_START'
         SCI_START = 2000,
         ^~~~~~~~~
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:48:19: error: expected unqualified-id before numeric constant
 #define SCI_START 2000
                   ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:70:9: note: in expansion of macro 'SCI_START'
         SCI_START = 2000,
         ^~~~~~~~~
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:1062:22: error: expected identifier before numeric constant
 #define SC_AC_FILLUP 1
                      ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:2329:3: note: in expansion of macro 'SC_AC_FILLUP'
   SC_AC_FILLUP = 1,
   ^~~~~~~~~~~~
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:1062:22: error: expected '}' before numeric constant
 #define SC_AC_FILLUP 1
                      ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:2329:3: note: in expansion of macro 'SC_AC_FILLUP'
   SC_AC_FILLUP = 1,
   ^~~~~~~~~~~~
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/../include/Scintilla.h:1062:22: error: expected unqualified-id before numeric constant
 #define SC_AC_FILLUP 1
                      ^
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:2329:3: note: in expansion of macro 'SC_AC_FILLUP'
   SC_AC_FILLUP = 1,
   ^~~~~~~~~~~~
In file included from /home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qscicommand.h:27:0,
                 from /home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintilla.h:32,
                 from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/SARX73RSAP/../../../../../../libs/qscintilla/Qt4Qt5/Qsci/qsciabstractapis.h:29,
                 from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/SARX73RSAP/moc_qsciabstractapis.cpp:9,
                 from /home/jule/git/sqlitebrowser/build/libs/qscintilla/Qt4Qt5/qscintilla2_autogen/mocs_compilation.cpp:4:
/home/jule/git/sqlitebrowser/libs/qscintilla/Qt4Qt5/Qsci/qsciscintillabase.h:2334:2: error: expected declaration before '}' token
  };
  ^
make[2]: *** [libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/build.make:934: libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscintilla2_autogen/mocs_compilation.cpp.o] Error 1
make[2]: Leaving directory '/home/jule/git/sqlitebrowser/build'
make[1]: *** [CMakeFiles/Makefile2:218: libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/all] Error 2
make[1]: Leaving directory '/home/jule/git/sqlitebrowser/build'
make: *** [Makefile:152: all] Error 2
```

**Comment by justinclift** [comment]
Hi @hasufell.  Is with a source tarball, or our latest git master, or something else?

Also, which platform are you running on? :smile:

**Comment by hasufell** [comment]
> or our latest git master

48d3cc6c7e25de4e5f7616e98b70e50408175231



> Also, which platform are you running on?

`Linux localhost 4.16.13+ #16 SMP Mon Jun 4 01:11:31 CEST 2018 x86_64 GNU/Linux`

**Comment by justinclift** [comment]
Thanks.  Testing super quickly now on CentOS 7 using the same git commit, and it compiled without error.  Looks like it might be specific to the gcc version or something.

The word `EWIEGA46WW` in your error output jumps out at me too.  Not sure what that means, and the few times it's showing up in search engine results all appear to be Qt related failures.  Might be not be anything important. :smile:

**Comment by justinclift** [comment]
With your Linux OS, is that a specific distro (eg something we can download and try to replicate the failure on), or is it a custom build? :smile:

**Comment by hasufell** [comment]
> is that a specific distro

https://exherbo.org/

Installation is carried out in a chroot, there is no "CD install", so you could as well just follow the installation instructions and leave it in a chroot on your host. There is also a [base docker image](https://hub.docker.com/r/exherbo/exherbo-x86_64-pc-linux-gnu-base/) if you find that easier.

**Comment by MKleusberg** [comment]
This is the same issue as #1361. Unfortunately we haven't found a solution for that yet :frowning: 

@hasufell What you can do in the meantime is just using qmake instead of cmake:
```bash
cd path/to/sqlitebrowser
qmake
make
```

**Comment by hasufell** [comment]
> @hasufell What you can do in the meantime is just using qmake instead of cmake:

Also fails (parallel) build: https://gist.github.com/hasufell/118cbd03098893ff9a9c0fb6689c5f46

**Comment by justinclift** [comment]
Heh Heh Heh

Well, this is getting complicated. :smile:

**Comment by hasufell** [comment]
It seems related to how translations are generated

**Comment by gmabey** [comment]
same build failure on CentOS 7.5 ...

**Comment by juszak** [comment]
I had similar issues building on RHEL 7 with cmake3. This worked for me (using the suggestion to use qmake)...

git clone https://github.com/sqlitebrowser/sqlitebrowser
cd sqlitebrowser
qmake-qt5
make
sudo make install

I'm not sure what packages were required, but I added ant-antlr, qt-devel, qt5-linguist, and qwt-qt5-devel to my system (using yum) when I tried to build with cmake3 before coming across the suggestion to use qmake in this issue (thanks!). 

Here are all the Qt packages I have installed (output of rpm -qa | grep qt)...

qt5-rpm-macros-5.9.2-3.el7.noarch
qt-devel-4.8.7-2.el7.x86_64
qtlockedfile-qt5-2.4-20.20150629git5a07df5.el7.x86_64
qt5-qttools-common-5.9.2-1.el7.noarch
dbusmenu-qt-0.9.2-7.el7.x86_64
qt-4.8.7-2.el7.x86_64
qt5-qtbase-devel-5.9.2-3.el7.x86_64
qt-x11-4.8.7-2.el7.x86_64
qtsingleapplication-qt5-2.6.1-28.el7.x86_64
qt5-qtsensors-5.9.2-1.el7.x86_64
qt5-qtbase-gui-5.9.2-3.el7.x86_64
qtkeychain-0.7.0-1.el7.x86_64
qt5-qtwebkit-5.9.1-1.el7.x86_64
highcontrast-qt5-0.1-2.el7.x86_64
qt5-qtxmlpatterns-5.9.2-1.el7.x86_64
adwaita-qt5-1.0-1.el7.x86_64
polkit-qt-0.103.0-10.el7_0.x86_64
qt5-qtbase-5.9.2-3.el7.x86_64
qt-settings-19-23.8.el7.noarch
qt5-qtlocation-5.9.2-1.el7.x86_64
qt5-qtbase-common-5.9.2-3.el7.noarch
qtkeychain-qt5-0.7.0-1.el7.x86_64
qt5-linguist-5.9.2-1.el7.x86_64
qt5-qtdeclarative-5.9.2-1.el7.x86_64
qt5-qtwebchannel-5.9.2-1.el7.x86_64

I'm using a version of sqlite built from source (sqlite-amalgamation-3250300). I'm also using GCC 7.2 built from source.

**Comment by tiendq** [comment]
@mgrojo Great news, I'll try it in next couple of days and let you know if it works. Thanks.

**Comment by tiendq** [comment]
@mgrojo FYI, I can build with CMake on macOS now.

**Comment by mgrojo** [comment]
@tiendq Awesome! We can close this.
