### ISSUE TITLE
Deprecated quotes used in generated SQL

### ISSUE THREAD

**Issue by tlhackque** [sqlitebrowser/sqlitebrowser#1440]
Details for the issue
--------------------

#### What did you do?
I added an index to a database using the "Database Structure" tab, "Create Index".

I watched the SQL Application log.

#### What did you expect to see?
````
CREATE UNIQUE INDEX "pathindex" ON "FILEs" (
	"cdid",
	"directory",
	"filename"
````

#### What did you see instead?
````
CREATE UNIQUE INDEX `pathindex` ON `FILEs` (
	`cdid`,
	`directory`,
	`filename`
````
Note that the identifiers are in grave accents.  This is deprecated syntax according to https://sqlite.org/lang_keywords.html.

Single quotes indicate a string.  Double quotes and identifier.  SQLite "sometimes bends the rules" by interpreting keywords in single quotes as identifiers in contexts where an identifier is allowed but a string literal is not.

> A keyword enclosed in grave accents (ASCII code 96) is an identifier. **This is not standard SQL.** This quoting mechanism is used by MySQL and _is included in SQLite for compatibility_.

The page goes on to say:

> Programmers are cautioned not to use the two exceptions described in the previous bullets. We emphasize that they exist only so that old and ill-formed SQL statements will run correctly. Future versions of SQLite might raise errors instead of accepting the malformed statements covered by the exceptions above.

Looking back in the log, it seems that all your SQL is using this non-standard syntax.

I checked the MySQL documentation, and apparently it has ANSI and Traditional modes.
The former uses double quotes; the latter the grave.  https://dev.mysql.com/doc/refman/8.0/en/string-literals.html and https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html

It is not obvious to me why the browser is generating this non-standard, "MySQL-compatibility only" syntax.  It seems like a bad idea - to the extent that brower users use the log to see how it implements commands, they will tend to treat the log as authoritative - and propagate the deprecated syntax.

With the caveat that I'm not an SQL Language Lawyer, my reading is that when generating SQL, the browser needs to use ANSI quotes.

If there's some good reason for using the MySQL quotes - e.g. talking to a MySQL database server, then they should only be used in those cases.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( _version:_ _10 pro__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ x] Other: ___3.10.99 15-Jun

#### Did you also

- [ ?] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds  Close enough, 5 daze old

- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
No.

**Comment by justinclift** [comment]
Ahhh, this seems to be what @mgrojo's PR the other day #1436 is about too.  Good timing? :smile:

**Comment by tlhackque** [comment]
Sorry, I didn't notice the discussion - trying to make forward progress on my "real" project & noting things here as they come up.  "You're only a new user once.... "

I'm on the side of "standard by default".  The notion that one can "get away" with only quoting when tripped up is, as I noted in another issue, dangerous.  So is using non-standard/deprecated syntax.  

if there is a real use case for the MySQL quotes - or the lazy quotes, the preference option(s) should be "advanced"/hard to find.  Don't forget that your test system will have to work with and validate behavior with all (2? 3?) options, not just change it to work with the default.  I'm not convinced.

**Comment by justinclift** [comment]
> "You're only a new user once.... "

Yep, very much agreed with this.  I do this for new projects (to me) too, as - to my mind - it's a good way to reduce the barrier to entry for future users.  eg notice the sharp bits I had trouble with and fix them

**Comment by mgrojo** [comment]
@tlhackque Thanks for the well-argued report.

This feature is already merged and present in the nightly builds. Have you taken a look? If it's ok for you, please close this issue, or comment here otherwise.

**Comment by tlhackque** [comment]
Thanks for letting me know.  I just installed a new nightly build.  Looks good, though I personally think that the non-standard MySQL grave and Microsoft Square-Bracket options shouldn't be given equal weight.  There's lots of room in the dropdown box.  How about something like?

- "Double Quotes"   - Standard conforming SQL
- \`Grave accents\`             - Old MySQL syntax
- [Square Brackets] - Old Microsoft SQL server syntax

I'm not stuck on the exact wording, but I think it should be clear that the bottom two options are deprecated and strongly discouraged. 

**Note that both MySQL and SQL server accept the standard-conforming syntax** And the SQLite project also cautions against using the non-standard versions and states that support may disappear. So there is no reason to suggest that they are anything but deprecated.

In any case, you did make standard syntax work - many thanks for all the effort you put in.

**Comment by mgrojo** [comment]
I made a commit inspired by your proposal and it should be already in the nightly.

**Comment by mgrojo** [comment]
@tlhackque Are you OK with closing this issue? :smile:

**Comment by tlhackque** [comment]
Sorry I missed your update.  "Traditional" seems a bit soft.  I might have chosen "deprecated", "obsolete", "non-standard".  Or "Pending removal by SQLite".  As I said previously, the message should be "deprecated and strongly discouraged".

But what you did is a definite improvement and there are other priorities.

I'm closing this issue - if someone else cares to drive strengthening the message, I'd support him (or her).
