### ISSUE TITLE
wrong number of returned rows

### ISSUE THREAD

**Issue by isrep** [sqlitebrowser/sqlitebrowser#1442]
Details for the issue
--------------------

#### What did you do?
CTE SELECTs with random() often returns wrong number of rows(some rows are empty).
For example select below often returns more that expected number of rows.

WITH RECURSIVE tossTH(seqv) AS (
            SELECT '>' --start mark
                        UNION ALL
            SELECT seqv||case when random()>=0 then 'H' else 'T' end FROM tossTH WHERE INSTR( seqv, 'TH' )=0  LIMIT 100
)
SELECT * FROM tossTH order by 1;

#### What did you expect to see?
always corrent number of rows

#### What did you see instead?
some empty rows, more than query truly returned (e.g. from 10 executios 8 times erourneous empty rows)
As seen in "Show SQL submited by Application", it seems that results of generated "count" query and real query are not aligned.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ X] Linux: ( _distro:_ ubuntu )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ X] Other: Version 3.10.99 (May 10 2018);SQLite Version 3.22.0
quick check with few years old version of browser shows the same error
#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @isrep, this definitely sounds like a bug. :innocent:

**Comment by tlhackque** [comment]
FWIW: It may also be related to the underlying issue in my #1431 - CTEs need to be recognized to be handled correctly.

**Comment by isrep** [comment]
Latest nightly version (96ca5994796) build on Ubuntu behave somewhat better (seems to show more often correct  number of rows). While wrong number of output rows is displayed, it now shows "loading..." text in those unused rows. Thank you for constantly improving sqlitebrowser.

**Comment by mgrojo** [comment]
@isrep thanks to the fix to #2165 this issue is also laterally fixed, since the problem was in doing an extra COUNT query. Can you confirm it with the latest nightly?

**Comment by MKleusberg** [comment]
Closing this issue as it looks like it has been fixed a while ago and we didn't hear anything since then. Feel free to reopen this issue if the problem still occurs.
