### ISSUE TITLE
Cert error against dbhub.io + crash

### ISSUE THREAD

**Issue by epistemex** [sqlitebrowser/sqlitebrowser#1445]
Details for the issue
--------------------

#### What did you do?

Registered at dbhub.io, generated and downloaded a PEM cert, added to DB browser and tried to connect to dbhub.io clicking the cog icon in the remote section listing my cert.

#### What did you expect to see?

Not sure yet.. .) but I assume a list of dbs in my account.

#### What did you see instead?

An error dialog:

![image](https://user-images.githubusercontent.com/26116778/41806164-58fb3902-767e-11e8-90e3-c0df301714b5.png)

and then:

![image](https://user-images.githubusercontent.com/26116778/41806302-d70ff9de-7680-11e8-95b7-cd65849a9d82.png)

which contained these details:
```text
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	DB Browser for SQLite.exe
  Application Version:	0.0.0.0
  Application Timestamp:	59c27929
  Fault Module Name:	Qt5Widgets.dll
  Fault Module Version:	5.7.1.0
  Fault Module Timestamp:	583ffd60
  Exception Code:	c0000005
  Exception Offset:	000000000021272a
  OS Version:	6.xxxxxxxx
  Locale ID:	1033
  Additional Information 1:	9af6
  Additional Information 2:	9af6ec55470e996fdd276cdb04095e9e
  Additional Information 3:	6981
  Additional Information 4:	69811c962194d5fc6a302953ca2752c8
```

Useful extra information
-------------------------

- Trying the URL directly in Firefox indicates a possible cert error on server (?)
- Allowed through firewall
- No proxy
- I'm able to connect via telnet
- (Doesn't matter if a database is loaded into the app or not)
- It's way past midnight..
- I might overlook something:

![image](https://user-images.githubusercontent.com/26116778/41806325-79ff343e-7681-11e8-9050-3e84839db976.png)

#### What operating system are you using?

- [x] Windows: ( _version: 8.1 x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Heh Heh Heh.  Nifty cat picture.  Maybe it's looking for it's twin? :grin: 

Thanks for this error report.  The dbhub.io server was recently renamed from db4s-beta.dbhub.io to just plain dbhub.io, and made available um... 2 days ago.  (still heaps to be done before it's really "ready" for production use).

My first guess is that we have something not handling that name change all that well.  Will investigate and find out. :smile:

**Comment by mgrojo** [comment]
And the crash seems the same as #1311

I get this instead of the certificate error:
![imagen](https://user-images.githubusercontent.com/13812910/41809521-621d7a2e-76ef-11e8-978f-745c46e57b26.png)

**Comment by mgrojo** [comment]
The picture is a fractal cat. If you zoom enough over the missing cat picture you find another cat in a window, and another, and another...

**Comment by justinclift** [comment]
> And the crash seems the same as #1311

Ahh yep.  Reading over that again, that does seem likely.

With the certificate error, I've just tried things out and received a different error:

![db4s-remote-panel-error1](https://user-images.githubusercontent.com/406299/41809837-363454bc-76ec-11e8-8b7d-6f65e21be9ff.png)

That seems like a config problem.  Investigating now.

**Comment by justinclift** [comment]
Hmmm, the reverse IPv4 address for the dbhub.io server was still set to `db4s3.dbhub.io` (now fixed).  I'd set it to that for the Rackspace migration a few weeks ago, and it looks like I missed updating it.

Not sure if that's the actual problem here, but it should help get things right.  I'll be able to try again in ~20 minutes when the reverse DNS setting cache expires.

And yeah, I could go and figure out how to clear that cache... but I need food anyway. :smile:

**Comment by justinclift** [comment]
@mgrojo For your error, would you be ok to go into the Remote tab of the Preferences dialog, and delete your user certificate from there (the bottom panel in that tab)?

From memory, it extracts the server name from the user (client) certifcate there.

If you then generate a new one using the dbhub.io webui, it should have the correct server name in it.  Install that one... and things **should** be in a better state.

That's assuming there's not some config problem on the server that needs fixing still. (quite possible) :smile:

**Comment by justinclift** [comment]
@epistemex With this:

> Trying the URL directly in Firefox indicates a possible cert error on server

Yeah, there definitely would be.  For the dbhub.io web server interface we use Lets Encrypt certificates, which browsers understand.  For the DB4S communication to dbhub.io though, we use certificates signed by our own Certificate Authority.

If CA stuff happens to be interesting for you, there's more info on the process here: :smile:

&nbsp; &nbsp; https://jamielinux.com/docs/openssl-certificate-authority/

**Comment by justinclift** [comment]
Ahhhh, there definitely still is a config problem on the server.  The server certificate there still has the old name.

Fixing now...

**Comment by justinclift** [comment]
Yep, that was due to the old server certificate being present on the server.  I've just now (a few seconds ago) finished fixing that, and for me it's now working. :smile:

**Comment by justinclift** [comment]
Note that when I say "it's now working"... I haven't yet tested it in depth.  So far it's able to list the remote public databases and whichever ones (both public and private) that I own.

It's also downloading them ok too.

From rough memory, we still have some outstanding work needing to be done for the uploading.  Something along the lines of first uploads working ok, but I'm not sure if subsequent ones do.  It'll need testing then fixing of any weirdness that shows up. :smile:

**Comment by justinclift** [comment]
@epistemex Oh, just realised you're using DB4S version 3.10.1 (our current main release).

That's probably not going to work with the dbhub.io server well anyway, as we went through the period of adjusting how the communication works between them... after the release.  It's still kind of ongoing too, but hasn't been that active recently (other priorities).

If you're up for using our latest nightly build, that should work "ok" now. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Is that something you're ok to try out? :smile:

**Comment by mgrojo** [comment]
It works now for me.

**Comment by justinclift** [comment]
Excellent.  Thanks for verifying @mgrojo. :smile:

**Comment by epistemex** [comment]
@justinclift that did the trick for me as well! Nice :) And thanks (great support)!
