### ISSUE TITLE
No STOP button, need one

### ISSUE THREAD

**Issue by tlhackque** [sqlitebrowser/sqlitebrowser#1447]
In my never-ending quest to demonstrate that I can make every possible mistake ...

Details for the issue
--------------------

#### What did you do?
In the execute query window I generated a recursive select that failed to terminate.

#### What did you expect to see?
A "stop" button.

#### What did you see instead?
A busy-wait loop, spinning disk, unresponsive GUI.

The only thing I could do was take a screenshot of my SQL & kill the browser.

Two issues (and I think both constitute bugs)...

- There really needs to be a "STOP" button so that a query (or other operation) can be cancelled.
- The Execute SQL tabs should have a checkpointing facility (as editors and now webbrowsers do), so that when the browser, computer, or user crashes, work can be recovered.

Restarting the browser should offer to recover the session/execute SQL tabs.
(I had 8 open where I was trying to figure out how to make a tree-walking select work - the screenshot captured only one...)

I suppose that the browser could use a, er, _database_ to journal user sessions with full roll-back and roll-forward ;-)  But a simple text file (e.g. emacs session files) would do.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
> There really needs to be a "STOP" button so that a query (or other operation) can be cancelled.

Yeah.  This is a reasonably commonly requested feature.  We've been putting effort into getting the underlying bits ready and from rough memory I think we're fairly close to having this.

> The Execute SQL tabs should have a checkpointing facility (as editors and now webbrowsers do), so that when the browser, computer, or user crashes, work can be recovered.

Very good idea.  I don't think this anyone has suggested it yet either.  We should definitely do this. :smile:

**Comment by MKleusberg** [comment]
@tlhackque We are finally preparing some changes which add, besides making some other changes, a cancel button to the Execute SQL area and keep the UI more responsive. Because it's changing a lot of our code we want to test this as good as we can. Are you interested in giving it a try? You can find the Windows and OSX build here:

* https://nightlies.sqlitebrowser.org/win32-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win32.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win64.msi
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite_issue-1575v1.dmg
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_issue-1575v1.dmg

A checkpoint feature sounds like a good idea too. It might be a separate issue though. By the way, a special thank you for opening all these issues, @tlhackque! :+1: Even though it will take us some time to work through all of them they are very much appreciated :smile:

**Comment by beRto-** [comment]
Did this new feature go anywhere? Do you still need someone to test? (Just ran a never-ending query and was wishing for a stop button! Had to kill the program, but then I had issues with locked DB because I had uncommitted writes before the crash)

**Comment by chrisjlocke** [comment]
Which version are you running?  I thought queries now utilised a cancel
button...

>

**Comment by mgrojo** [comment]
This was added to the master branch in 1f9101ae2a564121ba2843b68c1d7d3f8cff93ad but it hasn't been released yet. It will be in the next one and meanwhile, in the nightlies.

**Comment by beRto-** [comment]
@mgrojo - ah, that explains it! I could have sworn I saw a cancel button in a version I had tested. So I was kind of confused / surprised when I couldn't find it today. Must be because after 3.11.2 was released, I switched over to it from the nightly version I was testing before then.

**Comment by MKleusberg** [comment]
Did you have a chance to test this in the nightlies, @tlhackque and @beRto-? :smile:

**Comment by beRto-** [comment]
@MKleusberg  - I recall having tested at the time, and it worked. But I went to test again now, since it's been awhile. Am I looking in the wrong place (https://nightlies.sqlitebrowser.org/latest/). I didn't see any msi versions, and the zips are empty (22byte files)?

**Comment by justinclift** [comment]
> ... the zips are empty (22byte files)?

Ouch.  That generally means one of the changes since the last build (yesterday) is breaking the build on windows.

I'll take a lot at it later on today, but need to get some sleep now first.

**Comment by justinclift** [comment]
In theory (!) the build problem is now fixed, and new nightly builds will be online in about 40 minutes.

**Comment by justinclift** [comment]
Yep, new builds are online now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by beRto-** [comment]
@justinclift @MKleusberg I tried the nightly, and the ability to stop a long-running query worked for me! I used [this method](https://dba.stackexchange.com/questions/203545/write-a-slow-sqlite-query-to-test-timeout) to create a long-running test query.
It looks like the nightly also prompts to save my SQL?! Is that addressing issue #938?

**Comment by mgrojo** [comment]
Thanks, @beRto-. Yes, #938 has been addressed too, although it remained hidden under our pile of issues. I'll close both, but feel free to reopen any of them, if you think there is still some rough corner.
