### ISSUE TITLE
Windows installer :: App not registered properly

### ISSUE THREAD

**Issue by timrae** [sqlitebrowser/sqlitebrowser#145]
If I try to right-click on a custom file type, and open with, sqlite browser doesn't appear. Even after going browse -> and manually selecting the sqlitebrowser executable from program files doesn't fix the issue.

Also sqlitebrowser doesn't appear in the list of programs to uninstall

**Comment by justinclift** [comment]
@timrae In theory (!), this should be fixed a while ago.  Do you have a few moments to download our recent 3.8.0 release, and test this out just to be sure? :smile:

**Comment by timrae** [comment]
Yeah it was fixed ages ago, thanks

**Comment by justinclift** [comment]
Cool, it's all good. :smile:
