### ISSUE TITLE
freezes when try ro open db 

### ISSUE THREAD

**Issue by BorgesGabo** [sqlitebrowser/sqlitebrowser#1452]
#### I'm opening this issue because:

- [ X] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ __7_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Can you provide more information?  "freezes" doesn't really explain the problem.
Is it a large database?  Is it stored on a network?  Is it just this database or all databases?

**Comment by BorgesGabo** [comment]
thank you!

**Comment by justinclift** [comment]
Did that fix the problem for you? :smile:

**Comment by BorgesGabo** [comment]
Honestly I was under pressure to complete something so I decided to use
another tool

**Comment by justinclift** [comment]
No worries at all @BorgesGabo. "Get it working" pretty much always wins. :smile:
