### ISSUE TITLE
Issue during sqlite browser compilation in windows with visual studio 2013

### ISSUE THREAD

**Issue by nilesharv** [sqlitebrowser/sqlitebrowser#1459]
Details for the issue
--------------------
I downloaded the source code of sqlitebrowser and trying to compile using visual studio 2013. during compilation build was not successful. as some macros replace the name of variable with integer value.

#### What did you do?
For building sqlitebrowser in windows i followed steps mentioned in build file.

#### What did you expect to see?
successful build.

#### What did you see instead?
I saw there are two header file qsciscintillabase.h and Scintilla.h .
Scintilla.h  contains macro replace the enum names in qsciscintillabase.h .
due to this i am getting error during project compilation.

Useful extra information
-------------------------
once i tried with individual project compilation. that worked and i got .exe of sqlitebrowser, but not able to do complete compilation.
The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [  ] Windows: ( _version:10 )

#### What is your DB4S version?
- [  ] 3.10.1

utf8=%E2%9C%93&q=is%3Aissue%20
![image](https://user-images.githubusercontent.com/13981229/42275041-8a095902-7fac-11e8-893f-f699f16710e4.png)
![image](https://user-images.githubusercontent.com/13981229/42275061-979a3fdc-7fac-11e8-8a4e-e65c0f214278.png)

**Comment by justinclift** [comment]
Interesting.  Is this showing up with our latest git source code, or are you using a source code archive (eg .zip or .tar.gz)?

**Comment by justinclift** [comment]
Asking because while it's definitely possible something isn't right in our source code for Windows (that doesn't happen sometimes), our automatic nightly build process worked on for the Windows builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Without looking closer yet, it **seems** like our git repository source code should still be compiling ok on Windows.

**Comment by nilesharv** [comment]
I cloned the source code from git repo

**Comment by FriedrichFroebel** [comment]
Which CMake and Qt version are you using? It seems like this is related to https://github.com/sqlitebrowser/sqlitebrowser/issues/1361. Furthermore, this does not seem to be Windows-specific, as this is the same error which I get on Manjaro Linux with `cmake version 3.11.4` and `Qt version 5.11.1` using the latest master.

**Comment by justinclift** [comment]
Ahhh, good point @FriedrichFroebel.

@nilesharv Would you be ok to try a slightly older version of CMake?  Perhaps version [3.10.3](https://cmake.org/download/)?

**Comment by justinclift** [comment]
No worries.  Please let us know if it does work too, so we can close this issue. :smile:

**Comment by nilesharv** [comment]
@justinclift  @FriedrichFroebel  Thanks guys, i used cmake vesion 3.10.3 and it worked. i am able to compile without any error. thank you for help

**Comment by justinclift** [comment]
You're welcome @nilesharv. :smile:
