### ISSUE TITLE
DB Browser crashes when opened

### ISSUE THREAD

**Issue by jrosenthal** [sqlitebrowser/sqlitebrowser#1460]
When I open DB Browser, if I don't open or create a DB within ~1 sec, the program crashes.

Details for the issue
--------------------

#### What did you do?
Open DB Browser for SQLite.  

#### What did you expect to see?
Be able to use application.

#### What did you see instead?
After a second, if I have not created a new db, or opened and existing db, the software crashes.  If I open an existing db quickly enough (or create a new one), then it doesn't crash.

Looking in windows event viewer, I see an Application Error of:

> Faulting application name: DB Browser for SQLite.exe, version: 0.0.0.0, time stamp: 0x59c27929
> Faulting module name: ntdll.dll, version: 10.0.16299.492, time stamp: 0x1ef3a73c
> Exception code: 0xc0000374

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 Pro)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Is that with the 32 or 64 bit version of DB4S?

**Comment by jrosenthal** [comment]
I've been "using" the 64 bit version.  Uninstalling now to try the 32

**Comment by jrosenthal** [comment]
Well, this is confusing.  Previously I'd tried the 64 bit and the portable and had the crashes.  After trying the 32 bit, everything seems stable... even when I uninstall 32 and reinstall 64.  I think this can be closed as weird, resolved, and unreproducible.

**Comment by justinclift** [comment]
No worries at all.  It does sound windows was getting something wrong there, but seems to have resolved itself with the uninstall/reinstall dance. :smile:
