### ISSUE TITLE
Why is the wiki shy?

### ISSUE THREAD

**Issue by tlhackque** [sqlitebrowser/sqlitebrowser#1464]
What is your question
-----------------------
Is there a reason that there is no reference to the project wiki on https://sqlitebrowser.org/?  Or in the README on https://github.com/sqlitebrowser/sqlitebrowser?

Documentation (and wiki) links were the first things I looked for when I stumbled across this project...  Somehow, the GitHub "Wiki" tab doesn't jump out -- perhaps because few projects actually use it.

While the features and history are nice, a prominent link to "more information", "documentation", and/or "wiki" seem in order...

**Comment by justinclift** [comment]
Ahhh.  We've probably just been assuming that people "know" to use the wiki section (if familiar with GitHub), or they find their way to it via the Help->Wiki menu in DB4S.

It's pretty easy to add appropriate doc links to the README and website index.html.  Want to create a Pull Request with something suitable? :smile:

**Comment by MKleusberg** [comment]
I've just added a link to the Website and the README file. I've also added a badge or whatever they are called to both places. And finally there's already a menu item for the Wiki in the Help menu of the application. So I think this is prominent enough now :smile: Do you reckon we can close this issue, @tlhackque? :smile:

**Comment by tlhackque** [comment]
Thanks for addressing this.  Nit: "for users as well as developer" - should be "developers" in both places.

I'm OK with closing the issue.

**Comment by MKleusberg** [comment]
I just fixed the typo in both places. Thanks for pointing out! I'll close this issue then :smile:
