### ISSUE TITLE
add 'sqlite' and 'datastore' to app.plist

### ISSUE THREAD

**Issue by marc-medley** [sqlitebrowser/sqlitebrowser#1472]
Describe the new feature
--------------------------

Add 'sqlite' and 'datastore' to app.plist so that SQLite files with `.sqlite` and `.datastore` will show on the "Open With" file context menu without having been set as the default application.

It's a simple two line change in [/sqlitebrowser/src/app.plist](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/app.plist)

``` xml
<key>CFBundleTypeExtensions</key>
<array>
    <string>db</string>
    <string>sqlite</string>     <!-- added line -->
    <string>datastore</string>  <!-- added line -->
</array>
```

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

No.

#### Does this feature exist in another product or project? Please provide a link.

Yes. Just download [Valentia Studio (free version)](https://www.valentina-db.com/en/studio/download) and view `info.plist` in the Valentia Studio bundle.

#### Do you have a screenshot? Please add screenshots to help explain your idea.

![sqlitecontextmenu](https://user-images.githubusercontent.com/15098151/42654652-2cec0936-85ce-11e8-8e6f-55c22cfb761d.png)

**Comment by justinclift** [comment]
Thanks @marc-medley, sounds like a good idea and seems pretty simple to do.

Do you want to create a Pull Request with the change?  If not, I can get it done. :smile:

**Comment by marc-medley** [comment]
@justinclift, It would be great if you could put the change in!

Also, since `app.plist` is macOS specific, I was wondering if a similar extension pairing change was applicable for other supported platforms as well.

**Comment by justinclift** [comment]
Just added `.sqlite` to the file extension association, but thinking about it more... I'm not sure about `datastore`.

I've seen `.sqlite` be used before, so that's no worries, but haven't ever seen `.datastore` be associated with SQLite files.

Doing some quick searching online, it doesn't seem a common extension for it?

**Comment by justinclift** [comment]
For other OS's, it's a case-by-case thing too.  For Windows, we're moving to a .msi packaging system (currently in progress).  In theory that should let us set up file associations, but we haven't gotten around to doing that bit yet.

With the various *nix OS's, I'm not sure.  It might be something that can be set in the [.desktop](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/distri/sqlitebrowser.desktop) file, but it's not something I personally know about nor have much interest in.  (Pull Requests to improve things are welcome of course) :wink:

**Comment by marc-medley** [comment]
Good point regarding `.datastore`.

`.db`, `.sqlite`, `.sqlite3` would be more comment extensions than `.datastore`. With `.sqlite` and `.sqlite3` being more specific than `.db`

I had found `.datastore` in Valentina Studio's info.plist. However, it's not any extension that I use myself.

``` bash
sudo find / -name "*.datastore" -print # items found are not SQLite files.
sudo find / -name "*.db" -print        # long list found
sudo find / -name "*.sqlite" -print    # long list found
sudo find / -name "*.sqlite3" -print   # long list found
```

The instances *.datastore on my system (e.g. com.apple.Notes.datastore) are either a non-SQLite object files or a directory.

`.sqlite` and `.sqlite3` would to be common extensions in regular use on macOS. And I would agree to not add `.datastore`

**Comment by marc-medley** [comment]
The current nightly build works OK for `.sqlite` on my system.  Thanks.

I will check again when `.sqlite3` is in a nightly build. 

I have not find any "naturally occurring" `.db3` files on my system.  Still, I will rename a file and check `.db3` when the nightly build is available.

In my individual case, `.db`, `.sqlite`, `.sqlite3` are the ones i'm finding that ship with macOS or are common from  App Store installs, etc. And, the ones I current find/use in development.

Historically, its seems that a more comprehensive sqlite file extension list would be something like "db|sdb|sqlite|db3|s3db|sqlite3|sl3|db2|s2db|sqlite2|sl2".  That said, the longer list is not a request|recommendation. And, SQLite 2 versions are arguably of little current relevance. So, I would defer to you and other SQLiteBrowser team members as to whether any additional extensions should be included.

**Comment by justinclift** [comment]
Heh Heh Heh.  I think we're ok now. :wink:

We don't support SQLite version 2 (it's pretty ancient), so none of the extension with `2` in their name are likely useful for us anyway.

**Comment by marc-medley** [comment]
Verified: nightly build 14-Jul-2018 09:59 works OK for `.db3` (and `.db`, `.sqlite`, `.sqlite3`) on my system.
