### ISSUE TITLE
Browse data columns size is reset when sorting

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1475]
Just noticed something weird when testing things out with our current code (dbd2d648d8e40ce45d6754f12523b3c77de8e660).

In the Browse Data tab, if I've manually adjusted the size of some columns.. that size is lost/reset when I click on any column heading to sort by that column.

This is actually pretty annoying, as the size it reset back to (in the db I'm using atm) has fairly wide data in one field that I'm trying to read.  So having to resize it to become fully visible after every sort operation is ugh. :wink:

**Comment by mgrojo** [comment]
I don't reproduce that behaviour. It is probably a bug in Qt or a difference in behaviour between platforms.

**Comment by justinclift** [comment]
Thanks @mgrojo.  :smile:

I don't remember which platform that was on at the time.  Probably my Linux box.  At some point I'll see if happens with the Windows nightlies, just to see if there's a difference. :smile:

**Comment by MKleusberg** [comment]
I have the same issue. I think it came up with Qt 5.10 or similar. We've already worked around a similar issue which would show the rowid column each time the view is sorted.

**Comment by MKleusberg** [comment]
This was a bit tricky to fix because it is in a place which is rather complicated and needs to be rewritten at some point. But I hope it is working now. Can you double check, @justinclift? Also worth checking how hidden columns work and if it reacts to filter changes in any unexpected way. The reason is that there are plenty of possible actions in the Browse Data tab which trigger all sorts of view changes to be reset and I hope to sort them all out in my commit :smile: It'd also be interesting to see if this has any side effects when using Qt <5.10.

**Comment by mgrojo** [comment]
Still working fine with Qt Version 5.5.1

**Comment by justinclift** [comment]
I don't have time to look at this again right now.  Maybe tonight though. :smile:

**Comment by justinclift** [comment]
Got around to making a screencast of the problem:

* https://nightlies.sqlitebrowser.org/issue_uploads/DB4S_Issue_1475-hidden_columns_become_visible.mkv

It's definitely not my imagination. :smile:

**Comment by MKleusberg** [comment]
Turns out it's all more broken than I dared to imagine. I hope it's working now with the latest commit. Can you give it a try? :smile:

**Comment by MKleusberg** [comment]
Did you have a chance to test this yet, @justinclift? :smile:

**Comment by justinclift** [comment]
Whoops.  Completely forgot.  Will test it now. :smile:

**Comment by justinclift** [comment]
Yep, the sorting no longer resets column widths and the hidden columns no longer appear afterwards either.  They can be made to appear using the correct option in the right click context menu though, so this looks to be fully solved now.

Thanks for getting it done @MKleusberg, and for the reminder prompt. :wink:

**Comment by MKleusberg** [comment]
Cool :smile: I feel like that would have been a release blocker too. Thanks for testing!
