### ISSUE TITLE
Better portability with relative file path handling in Project Files 

### ISSUE THREAD

**Issue by tilusnet** [sqlitebrowser/sqlitebrowser#1478]
Describe the new feature
--------------------------
I often synchronise over SQB project files between locations: desktop / laptop / usb stick.
I notice inside the `.sqbpro` files that:
* `<db path/>` is absolute, making it difficult to load database files easily "in relative" proximity;
* `<sql/>` entries for embedded sql snippets only have reference to a `name` ─ and no reference to paths which would make it easier to update snippets on disk once they had been saved previously

My suggestions:
* make `<db path/>` use relative path resolution where applicable
* add a `path=` reference to `<sql />` pointing to the last location the snippet has been saved; again, with relative path resolution where applicable

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
No / Not aware of

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Look inside an `.sqbpro` file

I hope you'll find my suggestion useful and easy enough to implement it soon. Thanks!

**Comment by justinclift** [comment]
Seems like a decent idea. :smile:

**Comment by mgrojo** [comment]
Since  #36, the database file is searched in the directory where the project file is stored if not found in the absolute path which is saved in the file, so in practice, this is working unless a copy of the database still exist in the original location.

I'm not sure if that is enough for most use patterns. Another possible behaviour is to automatically remove the path from the DB when saving the project, if the DB and the project file share the same absolute path. Any opinions on this matter?

**Comment by justinclift** [comment]
> Another possible behaviour is to automatically remove the path from the DB when saving the project, if the DB and the project file share the same absolute path.

That sounds like a good approach. :smile:

**Comment by mgrojo** [comment]
@tilusnet, the [next nightly build](https://nightlies.sqlitebrowser.org/latest/) will save the database file without path when the project file is located in the same directory, allowing portability of the files to other locations. Could you confirm that it works for you so this issue can be closed?

**Comment by tilusnet** [comment]
@mgrojo thanks. I run Linux, I notice there's no Linux build there.
If you can confirm where and when the Linux build will be available, I'll test.

**Comment by chrisjlocke** [comment]
What flavour of Linux?  You could compile it yourself from the source?

**Comment by mgrojo** [comment]
For Linux, besides compiling yourself, you can download the [continuous build AppImage](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous), when it is done, because currently is [queued](746302432).

**Comment by mgrojo** [comment]
@tilusnet, most users are in Windows and I forgot to check in your case. I've made now this [wiki page](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) from the contents of "* README.txt" in that server and will start linking there so it's more clear and more Operating-System agnostic :wink:

**Comment by tilusnet** [comment]
I can't see the queue - https://github.com/sqlitebrowser/sqlitebrowser/issues/746302432
Is the "next nightly" UTC / GMT or what timezone is it in?

**Comment by chrisjlocke** [comment]
I think the link got mangled.  It should be this: https://travis-ci.org/sqlitebrowser/sqlitebrowser/builds/746302432

**Comment by tilusnet** [comment]
I confirm, it works with last night's build.
Thanks for following this up!

Tested with:
```
DB Browser for SQLite Version 3.12.99 (Nov 27 2020)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.5.1
SQLCipher Version 4.3.0 community (based on SQLite 3.30.1).
```

**Comment by mgrojo** [comment]
Thanks for confirming!
