### ISSUE TITLE
Problem Installing DB Browser for SQLite

### ISSUE THREAD

**Issue by fungibility42** [sqlitebrowser/sqlitebrowser#1479]
### Details for the issue

I downloaded the Windows 32-bit downloader, but the installation won't complete and has stalled at the step:
Execute: "C:\Program Files\DB Browser for SQLite\redist\vcredist_x86.exe" /install /passive /norestart /quiet"

Any help would be appreciated, thanks

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( 7 version: 32-bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
@justinclift - How many downloads of 3.10.x are we getting a week/month these days?  Wondering if its worth redirecting to a page which says, "Feel free to download 3.10.x, but its quite old and we're still developing DB4S, so it might be worth downloading one of our nightly dongles.  It may be a bit ropey, and contain a few bugs, but it won't blow up your house or eat your dog."   Or something...
Just aware that 3.10.x is quite old and has 'issues', and at first glance, people would think development has stalled on it...  If they get installation issues, most people would just bin it and find an alternative tool...

**Comment by justinclift** [comment]
Still seems to be around ~180k downloads a month.  I'm just hoping we can get the outstanding PR's all merged soon-ish, so we can cut a new release. :smile:
