### ISSUE TITLE
DB4S no longer compiles on CentOS 7

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1488]
Just tried compiling DB4S on my CentOS 7 desktop... and it fails due to the recent CMake [minimum version change](https://github.com/sqlitebrowser/sqlitebrowser/commit/961141ec36a88c6c53a3262ae77da14f46c8f4c0) for #1419:

```
$ cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.1.0 or higher is required.  You are running version 2.8.12.2
```

I think we're going to need to drop that minimum version number in down to 2.8.12.2 (or even earlier), as CentOS 7 is a very widely deployed platform.

After manually dropping the version number down to 2.8.12.2 here in testing (for the `src/` and `lib/` directory `CMakeLists.txt` files), the `add_definitions(-std=c++11)` line needed adding back into `CMakeLists.txt` too.  Without it the compile fails with errors about missing C++ features.

With those two changes, the build on CentOS 7 works again.

Will we miss anything important by dropping the minimum CMake version back down?

**Comment by MKleusberg** [comment]
If it builds with these changes (also on other platforms with newer cmake versions) it should be fine :smile: The alternative would be to tell people to use qmake on systems with older cmake versions. Especially on Linux systems the results should be pretty much the same.

**Comment by justinclift** [comment]
Cool.  I'll get the version dropped back to 2.8.12.2 sometime in the near-ish future. :smile:

**Comment by justinclift** [comment]
Just pushed the commit to move the minimum version back, and restore the removed `add_definitions(-std=c++11)` line.  This lets compiling work on CentOS 7 x64 again.

Guess we'll find out over the next few days if it breaks anything else. :wink:
