### ISSUE TITLE
Filtering is unexpectedly case insensitive

### ISSUE THREAD

**Issue by cooperdk** [sqlitebrowser/sqlitebrowser#1489]
On Windows 10, I experience what I call a bug filtering a table output.

When I search for fx "g:%" the output is both results with "g:" and "G:".

I don't know if you use a function that removes case sensitivity. But the database and all tables don't touch with the NOCASE parameter at all, so my guess is that you do a case-insensitive search in your code, which isn't good. I suggest a checkbox for the user to select if the filtering should be or not be case sensitive.

**Comment by mgrojo** [comment]
This is the default behaviour of SQLite. Take a look at the pragma case_sensitive_like
https://www.sqlite.org/pragma.html#pragma_case_sensitive_like

If I don't miss something, we should probably add it to the list of editable pragmas in the "Edit Pragmas" tab.

**Comment by justinclift** [comment]
> we should probably add it to the list of editable pragmas in the "Edit Pragmas" tab.

Good idea. :smile:

**Comment by MKleusberg** [comment]
Another (or maybe the same?) problem here seems to be that ```case_sensitive_like``` can't be read. The [documentation page](https://www.sqlite.org/pragma.html#pragma_case_sensitive_like) doesn't mention it explicitly but you can tell from the bold print example line that there is no way to read the current value - even in vanilla SQLite. So yeah, probably not possible to integrate the pragma in our GUI editor :frowning:

**Comment by justinclift** [comment]
@chrisjlocke Would you have a few minutes to ask on the SQLite users mailing list if there's a way to check the current value?  Just in case there is a way, and it just needs to be documented better. :smile:

**Comment by mgrojo** [comment]
> Another (or maybe the same?) problem here seems to be that case_sensitive_like can't be read.

Yes, it's the same. Setting the pragma value changes the behaviour also for SQLCipher. I got confused by not being able to get the value.

What strange exception. I wonder which is the reason.

There's a trick we could make :smile: This give exactly the same value as `pragma case_sensitive_like` should return:
```
SELECT 'x' NOT LIKE 'X'
```

By the way, I just noticed that in a translated version, the pragma values can be translated and consequently, setting some pragmas results may result in, for example:
`PRAGMA journal_mode = 'TRUNCAR';`
And that is ignored.

**Comment by justinclift** [comment]
> PRAGMA journal_mode = 'TRUNCAR';

Ouch.  Sounds like we'll need to figure out some way to avoid that.

**Comment by MKleusberg** [comment]
I've fixed that by disabling translation for PRAGMA values (and names, even though that's not really needed for this issue). In most languages they weren't translated anyway.

**Comment by MKleusberg** [comment]
We've also merged @mgrojo's PR. So in the [next nightly build](https://nightlies.sqlitebrowser.org/latest/) you can change the ```case sensitive like``` pragma. Can you give it a try and see if the filters work as expected with it, @cooperdk? :smile:

**Comment by MKleusberg** [comment]
Please also note that the value of the case_sensitive_like pragma isn't stored in the database. So you'll have to set it again after closing and reopening the database. Alternatively you can change it, then save your environment as a project file and open that instead of the database.

**Comment by justinclift** [comment]
@cooperdk Ping?

**Comment by mgrojo** [comment]
@cooperdk we think this is solved through the new case_sensitive_like pragma and we'd like to make some issue clean-up before the next release. If you find that we've closed this too early, you can still reopen it or add comments.
