### ISSUE TITLE
Shift+F5 shortcut does not work in Execute SQL tab

### ISSUE THREAD

**Issue by Bluezy** [sqlitebrowser/sqlitebrowser#1491]
Details for the issue
--------------------
As the title says, pressing <Shift>F5 in the 'Execute SQL' tab has no effect. 
Clicking on the icon to execute the current line works as expected, however. 
#### What did you do?
I haven't checked other key combinations.

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 X64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?
- [x] 3.10.1
#### Did you also

- [x ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Do you mean Shift+F5 (as you say in the title) or just F5 (as you say in the text)? :smile: Shift+F5 is sensitive to the current line. So if the cursor is for example in an empty line nothing will happen.

**Comment by mgrojo** [comment]
I've just reproduced this, but not sure how. It's working in the English version, but in the Spanish translation it doesn't work currently. The same is happening to "Shift+F1" which should enter in "What's this" mode. In the Help menu the shortcut is not displayed, but I'm sure to have seen it while I was updating the translation, as May+F1 (Spanish for Shift+F1).

@Bluezy Are you using a translated version? Could you change provisionally to English just to see if it works again?

**Comment by mgrojo** [comment]
I fixed the Spanish translation and now both Shift+F1 and Shift+F5 worked again. They weren't working since I updated the translation. If it weren't by this (possibly unrelated) issue, I wouldn't have notice in a while :smile:

@Bluezy If you were using a translation it might be related. Then we could fix that translation so it works Ok.

**Comment by justinclift** [comment]
Heh Heh Heh.  Learn something interesting almost every day. :grin:

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by SilvioGrosso** [comment]
I encountered this same bug.
Windows 10 (64 bit) - Nightly builds (12 November)
I have downloaded: DB.Browser.for.SQLite-win64.exe

Whenever you select the line with your SQL code an error always pops up.
At present, it only works when you select the last group of lines of code

Here is screenshot (the third SQL code works when I select it but not the previous two):
<img width="960" alt="sql_editor" src="https://user-images.githubusercontent.com/33007383/48574659-048e8e00-e910-11e8-86f7-c3dc87c02054.png">

**Comment by mgrojo** [comment]
Could it be https://github.com/sqlitebrowser/sqlitebrowser/pull/1575#issuecomment-430964392 (last Martin's answer). You don't use semicolons, so I guess it is related. What happens if you add semicolons?

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

> What happens if you add semicolons?

Yep. You nailed it!
As soon as I add the final semicolons ; my shortcuts (e.g. F5) work again.
All in all, I am not sure whether this behaviour is a bug or a feature but thanks a lot for your suggestions though.
In the long past I am pretty sure I was not forced to add any  semicolon in the Editor SQL but again, from now on, I will keep this in mind... :-)
