### ISSUE TITLE
Support :memory: or temporary databases

### ISSUE THREAD

**Issue by voltagex** [sqlitebrowser/sqlitebrowser#1492]
Describe the new feature
--------------------------
Supporting a temporary database or the :memory: connection would be helpful when I just need to check something and don't actually need to persist changes.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Does this feature exist in another product or project? Please provide a link.
https://www.sqlite.org/inmemorydb.html 

DataGrip - but it's got its own issues with this

**Comment by justinclift** [comment]
Yeah.  People have mentioned this a few times, and I personally tend to agree with you.

As long as it's easy to implement that is, and I reckon it probably would be. :smile:

**Comment by MKleusberg** [comment]
I've just added a new menu option for this. Can you give tomorrow's nightly build a try (if you're on Windows or MacOS), @voltagex? :smile: I tried to tweak the code to handle the side effects this might have but maybe I have missed something :wink:

**Comment by voltagex** [comment]
After a very brief check this seems to work as expected.

**Comment by MKleusberg** [comment]
Thanks for checking, @voltagex! :smile: I'll close this issue then - if you should notice any problems with this in the future you can always open a new issue or reopen this one.

**Comment by Jossnaz** [comment]
@MKleusberg what about linux?

**Comment by justinclift** [comment]
@Jossnaz For Linux, depending on your distribution you have a few options. :smile:

* Ubuntu and its derivatives have nightly builds available
  * https://github.com/sqlitebrowser/sqlitebrowser/#nightly-builds-1
* If you're into Snap packages, there are nightly Snap packages too:
  * https://github.com/sqlitebrowser/sqlitebrowser/#snap-packages
* If neither of those work for you, then you can build DB4S yourself:
  * https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

Building it yourself is **generally** not too hard, but there is an occasional gotcha so YMMV.

Does that help? :smile:

**Comment by Jossnaz** [comment]
@justinclift the nightly build will contain as well the in :memory: access? i'm not sure how this project is built or if there are different versions for linux and windows.

**Comment by justinclift** [comment]
All of our nightly builds (regardless of OS), are done from our `master` branch.  That's our development branch, which has the `:memory:` access stuff in it.

Sometimes the development branch is a bit flaky (eg just after we've added new features), but most of the time it's pretty good.  It should be **reasonable** about now. :smile:

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by justinclift** [comment]
Good thinking @mgrojo. :smile:

Just cut-n-pasted the above text into a new "Linux" piece on the bottom of that.  Should be good enough to start with.
