### ISSUE TITLE
Testing out new download server - please report any issues here

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1498]
Just a heads up, in a few minutes I'll update (just) the DB4S 3.10.1 release binary for Win32 to point at the new in-development download cluster:

&nbsp; &nbsp; https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.10.1-win32.exe

This is an experiment / test, just to start getting an idea of what it would take for us to serve downloads and the currentrelease file from our own infrastructure.

Please report and all weirdness with the downloads here, so it can be investigated / rolled-back / etc as needed. :smile:

**Comment by chrisjlocke** [comment]
Downloaded it fine here - no problems.  Didn't install it, so haven't tested the 'currentrelease' version file... yell back if you want me to...

**Comment by justinclift** [comment]
Thanks @chrisjlocke. I've been looking at other things, and haven't yet set up proper monitoring... but in general when logging into the 2 (very small) servers they're barely feeling any load at all.  Almost no disk nor memory io, cpu is around 5% too.

I need to find better tooling for measuring bandwidth though, as although the bandwidth isn't charged for (real "unlimited" style) each server can only do 200Mbit/s.  We need to know how much bandwidth we use at peak download time during release periods, but at least this is a start to working things out. :smile:

**Comment by jungle-boogie** [comment]
In the past, I've used vnstat:
https://humdi.net/vnstat

**Comment by justinclift** [comment]
Thanks @jungle-boogie, haven't tried that one before.  It's in the CentOS 7 repo's, so I'll give it a go now.

I'll probably set up a Zabbix or Prometheus box for "real monitoring" in near-ish future too. :smile:

**Comment by justinclift** [comment]
That vmstat is turning out to be useful already, as it seems like a good light weight solution to tracking historical bandwidth usage without needing a full on solution.

For the past few hours we've been transmitting about 1/2 a GB per hour for the Win32 download.

I'll add the Win64 one to it in a minute, which should triple that.  Let's see... :smile:

**Comment by justinclift** [comment]
Hmmm, this new approach seems to have defaulted to IPv4 only.  I'll revert it for now, and take this up again tomorrow when I'm more awake. :smile:

**Comment by justinclift** [comment]
Well, I've managed to fix the problem with client IP addresses being masked.  So that's a win.

On the other hand, the level of IPv6 support in Docker does not seem fit for purpose:

&nbsp; &nbsp; https://docs.docker.com/compose/compose-file/#enable_ipv6

"Swarm" mode being the orchestration approach that's integrated with Docker.  I can really see why people say Docker is useful for development, but just makes things harder for production.

Containerising any kind of "Business Critical" application seems like it would be fraught with danger (and very unwise).  The Docker networking code seems super unstable.  *Lots* and *lots* of bug reports about regressions, general breakage, etc.

Maybe I just need to sleep on this and look again tomorrow. :smile:

**Comment by justinclift** [comment]
Tomorrow, I'll probably just un-dockerise this, as it's adding a layer of crappiness and it's lack of native IPv6 support just leads me to consider Docker "not fit for purpose" for production workloads of small teams.  At least, not those **requiring** IPv6 support.

If we were a large business with dedicated IT support, then maybe it'd suit.  In that scenario we'd have people on staff that could likely implement and maintain a full k8s+Calico stack to put this stuff in. eg [working IPv6 in containers](https://www.projectcalico.org/enable-ipv6-on-kubernetes-with-project-calico/).

That's not where we're at though. :wink:

**Comment by justinclift** [comment]
Looks like Kubernetes is [getting around to adding IPv6 support](https://github.com/leblancd/kube-v6) too, without the need to use a 3rd party network component like Calico.

Likely too much admin overhead for our simple use case though.

**Comment by justinclift** [comment]
k, the new download bits are running directly on the hosts now (no longer in Docker), so are listening on both IPv4 and IPv6.  I've just updated the main DB4S website to point all four v3.10.1 downloads at them, so lets see how it goes this time. :smile:

**Comment by MKleusberg** [comment]
Heh heh, "Docker does not seem fit for purpose" and "it's adding a layer of crappiness". I never really understood the hype :wink:

**Comment by justinclift** [comment]
Well, it does seem to work pretty well for "internal" machines, including when they need to scale from a single server to small cluster size.  It's very much a set it up, and it just seems to run.

Troubleshooting on the other hand, seem like it can be a real PITA.

For untrusted environments though (eg internet facing), and things needing IPv6... it's definitely not there yet.  As in "very much avoid" unless there are dedicated people handy with the specific (non-default) technologies needed.

If the IPv6 stack and other issues I hit on the way through do get smoothed out over the next (say) 18-24 months, then I reckon it'll have really uptake from there.  The CLI is also pretty rough.  It reminds me of the Libvirt CLI before I got involved with that and started knocking off the rough edges. :smile:

**Comment by justinclift** [comment]
Today's our first weekday using the new download servers for all 4 of the 3.10.1 downloads (as linked from the main website).  There's only 2 servers online atm, and they're set up in round robin fashion... so super low effort approach for spreading load.

It looks like each download server will have generated about 30-40GB of traffic (mostly sending of course) for the full day.  It's not a full day yet, so that's an estimate (from vnstat).

If that's consistent (eg "steady" state), these two servers should comfortably handle the load we're seeing.  From memory of our GitHub page view stats, our traffic there generally doubles for a week or two after new releases.

So, for our next release we might want to bring an extra server or two online to handle the peak period, then drop it back to just these two after things settle down.  Guessing (!) that would continue to present a fairly ok download experience for people without notice-able slowness of downloads.

Of course, with this being round-robin (no load balancer in the front), things could definitely go pear shaped if any particular server happens to cop a large non-shared load.  That's not a problem for today though (hopefully). :grin:

**Comment by justinclift** [comment]
The new download servers seem to be working fine, and there hasn't been any complaints about moving the "currentrelease" file to the new servers.  The new servers are definitely listening on both IPv4 and IPv6 too (seeing source addresses for both come in), so this looks to be a win already. :smile:

**Comment by jungle-boogie** [comment]
To be more clear....
https://nightlies.sqlitebrowser.org/latest/

DB.Browser.for.SQLite-win64.msi doesn't have the cipher thing built with it, but has the latest sqlite build (at the time of the last modify day, anyway)

DB.Browser.for.SQLite-sqlcipher-win64.msi has sqlcipher thing

The new download path has only the sqlcipher thing:
https://download.sqlitebrowser.org/

**Comment by justinclift** [comment]
Yeah, that's deliberate.  The new download servers only have the last release (for now), which only has a SQLCipher enabled version. :smile:

**Comment by jungle-boogie** [comment]
Oh, okay. What's the sqlite version used?

**Comment by justinclift** [comment]
Not sure atm.  Pretty likely it'll be something kind of old now.
