### ISSUE TITLE
Deleting a tuple that has a Foreign Key constraint correctly fails, but it is removed from the filter

### ISSUE THREAD

**Issue by dmgerman** [sqlitebrowser/sqlitebrowser#1511]
Details for the issue
--------------------

#### What did you do?

Assume the following schema:

create table parent (a int, primary key a);
create table child(a int, b int, primary key (a,b), foreign key (a) references parent);

add values:

insert into parent values (1), (2), (3);
insert into child values (1,10), (2,20), (3,30);

make sure that the foreign key pragma is on.

now, try to delete a tuple in parent (any). it will get an error. This is ok.

the bug:

1. browsing parent, set the filter of attribute a with value equal 1, you will see only one tuple.
2. delete that tuple

you will get an error, this is ok

3. (after the error) the tuple is no longer in the filter. it has disappeared.
4. reset the filter
5. filter again with attribute equal 1, the tuple is still there.

#### What did you expect to see?

The tuple I am trying to delete should always be displayed.

#### What did you see instead?

The tuple disappears from the view (but it has not been deleted)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ X] Linux: ( _distro: ubuntu 18.04_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
As a general kind of thought, it's probably worth either grabbing a [recent nightly build](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1) or [building from source](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux) yourself.  We've fixes a lot of foreign key bits since the last major release, so there's a decent chance this will already have been taken care of. :smile:

**Comment by dmgerman** [comment]
ok, i'll give it a try and report back.

**Comment by dmgerman** [comment]
The problem persists in the daily build: Version 3.10.99 (Aug 20 2018)

**Comment by justinclift** [comment]
Damn.  Oh well, it's good you checked.  At least we now know it's a current problem that needs looking at still. :smile:

**Comment by MKleusberg** [comment]
Thanks to @mgrojo this should be fixed now :smile: Can you try again with the latest code and check if it's working now, @dmgerman?

**Comment by MKleusberg** [comment]
Did you have a chance to test this already, @dmgerman?

**Comment by dmgerman** [comment]
Sorry, for taking time to reply. I just did. Version 3.10.99 (Sep 30 2018). The bug seems to be gone.

thank you very much,

**Comment by justinclift** [comment]
Excellent. Thanks for getting back to us @dmgerman. :smile:
