### ISSUE TITLE
Connecting more than one .db file

### ISSUE THREAD

**Issue by soyoungtot** [sqlitebrowser/sqlitebrowser#1512]
I have two .db files (A.db and B.db) in the same folder. A.db file is already opened using DB Browser for SQLite, and I would like to connect to B.db file to join the tables in databases. I used: 

attach database 'A.db' as 'db1';
attach database 'B.db' as db2;

and ultimately to join tables, I have: 
SELECT * FROM A.table1 AS t1
JOIN B.table2 AS t2 
ON t1.firm = t2.firm;

but I got an error that says 'cannot ATTACH database within transaction'

Is there no way for me to join the tables in different database using DB Browser for SQLite?

Thank you,
Sophie

**Comment by justinclift** [comment]
@soyoungtot Which version of DB4S (our name for "DB Browser for SQLite") are you using? :smile:

I know that `ATTACH` works in our nightly release builds, but I'm not sure if it's in any of our major releases yet.

**Comment by soyoungtot** [comment]
@justinclift It's Version 3.10.1, Qt Version 5.7.1, and SQLCipher Version 3.15.2.

**Comment by justinclift** [comment]
Ahh ok.  If you're on Windows or macOS, try our latest nightly build from here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If you're using Ubuntu there are nightlies for that as well:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1

Does that help? :smile:

**Comment by soyoungtot** [comment]
@justinclift Thanks! It worked.

**Comment by justinclift** [comment]
Awesome. :smile:
