### ISSUE TITLE
Display zero counts

### ISSUE THREAD

**Issue by soyoungtot** [sqlitebrowser/sqlitebrowser#1517]
Hello, 

I am trying to count the number of companies by country that meet certain conditions. I tried:

select count(distinct company) from [A] where flag ==1  group by country order by country;

Unfortunately, this code leaves out countries whose counts of companies (that meet the condition where flag is 1) are zero. I tried using both nullif and left join but I couldn't figure out how to include zeros in my outcome. 

Does anyone have suggestions?

Thanks,
Sophie

**Comment by MKleusberg** [comment]
This isn't exactly an issue with DB4S, but I'll try to help you nonetheless :wink: I'm sure there is an elegant solution for this but if in doubt I will usually try to solve problems like this with sub-queries:
```sql
SELECT DISTINCT country, (SELECT COUNT(company) FROM [A] bla WHERE bla.country=a.country AND bla.flag = 1) AS number_of_companies FROM [A] ORDER BY number_of_companies DESC
```
For huge tables this is probably relatively slow though.

**Comment by soyoungtot** [comment]
@MKleusberg I didn't know that I wasn't able to ask questions about codes here. Thank you for your help!

**Comment by justinclift** [comment]
No worries Sophie, we're pretty relaxed about stuff. :smile:

As a general thought, for general questions/tips/pointers/hints/etc about SQLite queries and similar, probably the very best place on the entire internet is the SQLite users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

There are **lots** of helpful people on that mailing list, many of them very much experts.  If they can't the more curly questions... it would be (very) surprising. :grinning:

**Comment by MKleusberg** [comment]
No worries at all, @soyoungtot :smile: Did you get it to work? Another hack-ish way to get this done would be a ```UNION SELECT``` like this:
```sql
SELECT col1, col2, col3 FROM "table" WHERE something        -- This could be your original statement
UNION
SELECT col1, col2, col3 FROM "table" WHERE something else   -- This could be a statement which only return countries with zero companies
```

**Comment by mgrojo** [comment]
Hope this helped you. I'm going to close this issue but you can still post in it if you'd like to.
