### ISSUE TITLE
numRows

### ISSUE THREAD

**Issue by miguevirtual** [sqlitebrowser/sqlitebrowser#1520]
$registros = $result->numRows();

Error:
Fatal error: Uncaught Error: Call to undefined method SQLite3Result::numRows() in C:\Program Files (x86)\My Desktop App\www\ejemplos\index.php:13 Stack trace: #0 {main} thrown in C:\Program Files (x86)\My Desktop App\www\ejemplos\index.php on line 13

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Are you sure you should have posted this to the SQLite Browser group?  *scratches head*
