### ISSUE TITLE
Regexp filters

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1522]
I had an idea, that should be easy to implement. We just need to think a bit about the UI design.

Describe the new feature
--------------------------
Given that [SQLite provides a REGEXP operator](https://www.sqlite.org/lang_expr.html) similar to LIKE and all that it needs is a regexp extension (which we are providing within DB4S), it would be easy to interpret the filter as a regexp. That would allow very powerful filters.

This should not replace the current simple containing or general LIKE (with user wildcards) filters, but be an alternative that we should activate when user requests it and the extension is enabled. Here come the options:

1. A check box in an accessible place, like the contextual menu of the filter line editor. We  could then replace the placeholder text from "Filter" to "Regexp filter" for visual recognition.
2. A special syntax for activating the regexp in the filter expression, for example, surrounded by slashes: /^This is a regexp$/
3. A general setting in Preferences, so the filter is always interpreted as a regexp when it is enabled (I don't really like this option, but maybe someone likes it).

My personal preference is 1, because the expression syntax is already too overloaded. But 2 would be easier to enter.

Additional info
---------------

#### Is your feature request related to an issue? Please include the issue number.
Somewhat complementary to #1463.

#### Does this feature exist in another product or project? Please provide a link.
Some office applications, e.g. LibreOffice,  allow to search text using regexps.  DB4S itself allows this in the text search dialog. More specifically Calc allows to set a Standard filter where we can enable the regular expression as an option.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Quick demo implementation.

![imagen](https://user-images.githubusercontent.com/13812910/45002309-b4bd4d80-afd5-11e8-873e-2be0c168f30e.png)

**Comment by SilvioGrosso** [comment]
Hello everyone: @mgrojo,  @justinclift ,

As usual great improvement indeed !

With SqliteStudio 3.2.1, an open source software hosted on GitHub to handle Sqlite databases [1], it is possible to filter the data of your table through a drop-down filter where you choose:
- your TEXT  (you type the word you want to look for in the *entire* table. E.g. you type > 'Grosso') ;
- your REGEX;
- your SQL CODE (e.g:  surname like 'Grosso').
OR another *alternative* option to:
-  SHOW FILTER CODE PER COLUMN: it opens a row (header) in the table and you can type the word you want to search in the below column of our table. In short, this last option is similar to sqlite browser.

See this screenshot just to give you an idea:
![sqlitestudio_filters png](https://user-images.githubusercontent.com/33007383/45014987-992b6480-b020-11e8-8bc9-035d4bcf651c.jpg)

IMHO, just the current implementation where you write your regex code in the filter is fine!
Needless to say, it should be well documented in the WIKI :-)



[1] https://sqlitestudio.pl/index.rvt?act=download

**Comment by mgrojo** [comment]
I've finally implemented this feature using the syntax /regexp/ in the filter line. This is the simplest approach and the one that will be more useful for users, because it is immediate to change between one filter option and other. The only drawback is incorrectly using the slashes when the user expects a containing filter. In such case, escaping the first slash is enough for returning to the containing behaviour. This is automatically done if the user selects the "Use in Filter Expression > Containing" menu option.

I've opened the PR #1601 so it can be reviewed for errors or possible improvements, although the implementation itself is simple.

**Comment by mgrojo** [comment]
@SilvioGrosso @chrisjlocke The PR #1601 is already merged in the master branch, but I don't know when we will have a new nightly build with it. Stay tuned if you'd like to try it.

**Comment by justinclift** [comment]
New windows (nightly) builds have just been uploaded, and the OSX ones have just started compiling.  They seem to take about 2 hours to complete these days, so will (in theory) be online about then.

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Just tested this new feature on Windows 10 and it works like a charm
Even tested the conditional format which is the icing on the cake :-)

BWT, while I was testing the regex commit I was wandering whether there is a way into the BROWSE DATA panel to search in ALL columns in one shot?

In short, this is naturally possible with Microsoft Excel or LibreOffice Calc in that you are able to find a word in all columns. 
With Mozilla Firefox you click CTR+F and a new underneath panel appears and you can start looking for anything in the current page.
At present, with DB Browser it looks like you are forced to apply your filter "only " per colum (in essence you type your word in many columns,  at random, until you find what you are looking for).

![db-browser_regex png](https://user-images.githubusercontent.com/33007383/48282271-8a669100-e459-11e8-9a15-e628d505e5a6.jpg)

**Comment by mgrojo** [comment]
@SilvioGrosso 
> BWT, while I was testing the regex commit I was wandering whether there is a way into the BROWSE DATA panel to search in ALL columns in one shot?

No, it isn't currently possible, but it would be useful too. It could be done through a dialog or panel, as you say, or perhaps, through a way to switch to an OR operator (match all -> match any) for the filter lines and a helper menu option for copying the same word to all the columns. Maybe we should open a new issue for this, so that it is not lost. 

There is also  #147 (global search, it could be done with the find panel/dialog if it does not stop at the current table) and #1338 (it seems basically also a request for a global search).

**Comment by chrisjlocke** [comment]
Well done @mgrojo for implimenting this so quickly and easily.  I'll close this, as this seems to be sorted now.  The 'global search' request tagged on the end of this issue is a duplicate, so best kept to the other issues.  I'll close this, as this is now resolved.
