### ISSUE TITLE
Foreign keys: drop-down menu to select correct values (feature request)

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1523]
Hello eveyone,

I have searched the issues and, to my surprise, *unless* I am wrong, which is quite possible indeed, I didn't find this feature request.
I have tested the daily builds on Windows and It is not implemented yet.

In short, it would be extremely handy to have an option to have a drop-down menu where you can select your values to insert in your table, from a drop-down list, when you have a foreign key activated on a column.

At present this option is implemented in SqliteStudio 3.2.1, an open source software [1] and DBeaver 5.1.6, another open source software (at least as regards the community version...).
Needless to say, this option is available with Microsoft Excel and LibreOffice Calc as well.

See this screenshot for SqliteStudio 3.2.1, where in the column 'frutto' there is drop-down menu to select my values:
![sqlitestudio_foreign-keys png](https://user-images.githubusercontent.com/33007383/45049828-19cd7d80-b080-11e8-9a96-c25936fb4c3b.jpg)

See this screenshot for Dbeaver 5.1.6. The column 'frutto' has the option to select the correct values from the table on the right side:
![dbeaver_5 16_foreign_keys](https://user-images.githubusercontent.com/33007383/45049948-5ac59200-b080-11e8-927d-d63a6f52fb95.jpg)

**Comment by justinclift** [comment]
This definitely makes sense from my PoV. :smile:

**Comment by mgrojo** [comment]
Yes, this is highly needed. Thanks for the well documented report. We already had #614. The keyword for finding it was combobox :smile:

It is in my wish/to-do list, but there are so many possible enhancements!

**Comment by mgrojo** [comment]
Closing this, as Silvio already reported in PR #1550.
