### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1525]
Describe the new feature
--------------------------
Paper is dead, long live PDF!

Printing support in:
- [x] SQL/XML/JSON editor widgets
- [x] Plot
- [x] Table data in Data Browser and Execute SQL results
- [x] DB Structure
- [x] Other Edit Database Cell widgets

Information for SQL/XML/JSON:
http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciPrinter.html

Plot:
https://www.qcustomplot.com/index.php/support/forum/976

Table browser:
https://stackoverflow.com/questions/3147030/qtableview-printing
Maybe we can reuse the HTML clipboard.

**Comment by justinclift** [comment]
Interesting idea.  Seems like it'd be useful. :smile:

**Comment by mgrojo** [comment]
I have an implementation for the SQL editor. There is a problem, though. The keyboard shortcut for Ctrl+P is assigned to show/hide the plot dock and it's conflicting with the new print shortcut. I'd remove the Ctrl+P shortcut for the plot dock, and leave there only the other shortcut that it already has: Ctrl+D (it's the only dock having two of them). Any opinions? I never use these shortcuts for hiding/showing the docks.

**Comment by justinclift** [comment]
Just created a new "item for release note" label, which might help us not miss this bit for the next release's info. :smile:

**Comment by mgrojo** [comment]
I consider the printing support finished and ready for the release. Is anyone interested on testing it in different OS and confirm that it's working OK?

**Comment by justinclift** [comment]
Good idea. :smile:

I don't presently have a printer though, so this bit isn't something I can help with.

**Comment by chrisjlocke** [comment]
You can install a PDF printer ... you can't get out of it so easily! 😆

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Just tested this new feature on Windows Xp - professional through this installer (Version 3.10.99 - Oct  1 2018):
DB.Browser.for.SQLite-win32 (nightly builds)

I have also tested on Windows 10 - 64 bit this installer (Version 3.10.99 - Oct  1 2018):
DB.Browser.for.SQLite-win64 (nightly builds)

Both work fine in that I can successfully print my PDF :-)

Just two very *minor* personal remarks:
1)
On the Browse Data window there is no visual way, for a casual user, to guess the presence of this option. No print icon is available in the GUI, in short.
Needless to say, this feature works fine when you press CTR+P

2)
On the Execut SQL window you can now print your SQL code as PDF.
However, it looks like you can not print the result of your query as PDF. It looks like you can only export this result as CSV (or copy-paste your data into Excel, for instance).

Aside from that, GREAT feature indeed!
THANKS a lot for your hard work: Sqlite Browser has improved dramatically compared to the stable release :-)

**Comment by mgrojo** [comment]
> You can install a PDF printer ... you can't get out of it so easily!

I think you don't even need that. I'm not sure, but I think that the PDF printer is actually implemented by Qt.

> Both work fine in that I can successfully print my PDF :-)

@SilvioGrosso, thanks for reporting. Did the physical printer appear too as an option? Provided that you had one, of course.

> 1. On the Browse Data window there is no visual way, for a casual user, to guess the presence of this option. No print icon is available in the GUI, in short.
Needless to say, this feature works fine when you press CTR+P

There is a print icon in the contextual menu. Would users miss that? I hope that sooner or later they discover the icon. Nevertheless, do you all think it should be an icon in the Browse Data "toolbar"? It should be easy to add one there.

> 2. On the Execut SQL window you can now print your SQL code as PDF.
However, it looks like you can not print the result of your query as PDF. It looks like you can only export this result as CSV (or copy-paste your data into Excel, for instance).

It's possible. Again, that can be done with the contextual menu of the results table. This time I don't know how this could be made more visible. There isn't a clear location for that action.

The Edit Database Cell has also a print action in the contextual menu. Should it be added to the dock "toolbar" too?

> Aside from that, GREAT feature indeed!
THANKS a lot for your hard work: Sqlite Browser has improved dramatically compared to the stable release :-)

My pleasure :smile:

**Comment by SilvioGrosso** [comment]
Hello @mgrojo,

> Nevertheless, do you all think it should be an icon in the Browse Data "toolbar"? It should be easy to add one there.

Yep!
This way this icon would be present in this window as well (Browse Data).
At present, it is "only" available in the Database structure and in the Execute SQL.
IMHO, It is "strange" (that is, not consistent) not having the icon (print) in the Browse Data when it is available in the other 2 windows :-)

> The Edit Database Cell has also a print action in the contextual menu. Should it be added to the dock "toolbar" too?

Yep. My bad!
I didn't notice this additional option.
I think it is fine like this as regards this feature.

Again: I really appreciate your efforts.
In the past, I have always worked with SqliteStudio.
It has lot on common with Sqlite Browser (QT Gui; C++; Github - Open source code).
At present, in my view, Sqlite Browser is better (even though SqliteStudio has some features not currently available with Sqlite Browser)

**Comment by justinclift** [comment]
Would it make sense to add some main menu option for the Print ability too? :smile:

Not sure which section it'd go under though. :wink:

**Comment by chrisjlocke** [comment]
Printing the schema is fantastic.  A nice layout.  The ability to 'lose' the 'create' statement would be handy - especially for views - as it can take up a lot of paper.  Or lose the bold.  

![image](https://user-images.githubusercontent.com/7872218/46338282-a17abd80-c627-11e8-9d70-35d0c653d833.png)

Having the primary key in bold would be handy - it would highlight if a table is missing a primary key (something I do a lot! lol!)

But overall, the feature is great - really love it.  Well done!  💋

**Comment by mgrojo** [comment]
> Printing the schema is fantastic. A nice layout. The ability to 'lose' the 'create' statement would be handy - especially for views - as it can take up a lot of paper. Or lose the bold.

I've removed the bold (actually header) style from the Schema column and now it appears with preformatted so it has the same appearance as the application column. That is, if the "Remove line breaks in schema view" option is disabled, the line breaks appear also in the printed output.

![imagen](https://user-images.githubusercontent.com/13812910/46434743-c882dd80-c754-11e8-9b22-3f553bcf525e.png)

> Having the primary key in bold would be handy - it would highlight if a table is missing a primary key (something I do a lot! lol!)

I tried adding the icon but had problems. To-do for the next release.

> I'm not 100% sure the margins are correct though? I've gone into the print setup, and it says 20mm margins all round, but .... DB4S millimetres are bigger than Chris millimetres! ;)

Seems a Qt issue. I don't set any margin, but it seems that Qt adds a margin around the tables and then the printer margin.

**Comment by chrisjlocke** [comment]
Excellent tweaks - thanks @mgrojo  ❤️

**Comment by mgrojo** [comment]
Closing this as done for the v3.11.0 release. Any further improvements should be done through new issues.
