### ISSUE TITLE
Can not open SQLCipher database

### ISSUE THREAD

**Issue by Rogister** [sqlitebrowser/sqlitebrowser#1527]
When I want to open my database SQLCipher, when opening, the program detects that it is a database SQLCipher but when I type the word secret, each time, the box comes back and ask me again the secret word or I'm sure of the secret word.

Do you know this problem?

Alain

Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
How was the database created?  The sqlCipher version of DB4S can only open databases encrypted with sqlCipher (or more specifically, 256-bit AES encryption)

**Comment by Rogister** [comment]
It is a DB3 database.

To encrypt it, I use this:

sqlite3 /Users/RogisterMAC/Medinect.db
attach database '/Users/MacROGISTER/encrypted.db' as encrypted KEY 'bidon';
select sqlcipher_export ('encrypted');
detach database encrypted

**Comment by chrisjlocke** [comment]
So to encrypt it you use the SEE extension for SQLite? (https://www.sqlite.org/see/doc/trunk/www/index.wiki)  DB4S sqlCipher isn't compatible with SEE, as it uses a different encryption.

**Comment by Rogister** [comment]
I don't see where I specify SEE extension as you tell me.

Is it not possible to open this database with your tool ?

**Comment by chrisjlocke** [comment]
SQLite on its own doesn't come with encryption - you have to use a library.  SQLCipher can only open databases encrypted with SQLCipher.
If SQLCipher cannot open the database, then it must have been encrypted with a library that wasn't SQLCipher, or of course, the key entered is incorrect.  

>Is it not possible to open this database with your tool ?

Depends on how the database was originally encrypted.

**Comment by Rogister** [comment]
No, I use SQLCipher for encryption.

In my application, I use the SQLCipher library to access the database since 4 years and I have no problem.

Do you want me to send you the database?

**Comment by justinclift** [comment]
@chrisjlocke In the commands given, it has this:

    select sqlcipher_export ('encrypted');

Sounds like SQLCipher to me.  Maybe a mismatching page size?

**Comment by Rogister** [comment]
I tried all sizes and it does not work.

I took the unencrypted base. I open it with DB Browser without problem.

I re-encrypt the database with a simple 'alain' key and try to open it. Same problem.

**Comment by mgrojo** [comment]
@Rogister do you mean encrypting and then opening with DB Browser in both cases? Have you tried with a recent nightly build or with our alpha version? You can find the alpha in the releases section of github.

**Comment by justinclift** [comment]
@Rogister Had a thought about this, while looking into something else.

Not sure if you still this fixed though, as it's been a while. :wink:

If you do... what version of the SQLCipher library is being used to do the encryption?

Asking because one possibility is there's a mismatch in the version we're using vs the version of the existing SQLCipher library you were using.  Didn't personally know until recently that they needed to be of the same major version, unless specific backwards compatibility options are used.

**Comment by chrisjlocke** [comment]
I'll close this as its been a month with no response.
@Rogister - feel free to comment further if you're still having problems.
