### ISSUE TITLE
truncate table It doesn't work

### ISSUE THREAD

**Issue by miguevirtual** [sqlitebrowser/sqlitebrowser#1528]
Warning: SQLite3::query(): Unable to prepare statement: 1, near "TRUNCATE": syntax error in C:\Program Files (x86)\My Desktop App\www\json.php on line 44

// VACIAR TABLA MYSQL
		$sql = "TRUNCATE TABLE Usuarios";
		$result = $db->query($sql);

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by miguevirtual** [comment]
please

**Comment by justinclift** [comment]
Hi @miguevirtual, it sounds like you are having SQLite troubles with a PHP program you're creating?

If that's the case, you're probably better to ask here:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

There are lots of SQLite people there, many of them using PHP too. :smile:
