### ISSUE TITLE
Not Prompted To Save Changes After Amending Table

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1530]
Details for the issue
--------------------

#### What did you do?
Amended a database table.

#### What did you expect to see?
The 'Write changes' button lit up like a Christmas tree.

#### What did you see instead?
A disabled 'Write changes' button, not lit up like a Christmas tree.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.99 (7 Sep 2018)
- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Heres a screencast.
https://screencast-o-matic.com/watch/cFQ226qKwM

So I created a new database on my desktop.  Added a table.  Saved it all.  Amended it by adding a field.  As soon as the 'Edit table definition' window is opened, the 'Write Changes' button is enabled.  However, clicking 'OK' returns me to the main screen, where the 'Write changes' button is disabled.

Admittedly I'm using an old nightly (7 Sep) so this issue may have been resolved - there aren't any newer ones yet (apart from 8 Sep... haven't tried that one yet...)

The database is on my local C drive, not a network share.  I can confirm the database changes *are* getting saved - DB4S isn't simply ignoring the changes.  So its technically 'auto saving'.
Just to confirm, renaming a table has the same effect - DB4S auto saves.

**Comment by justinclift** [comment]
>  there aren't any newer ones yet (apart from 8 Sep...

Ahhh yeah, sorry about that.  My moving between countries has temporarily broken the nightlies build process a bit. Both the build box itself and the nightlies download server are fine... it's just the download server's firewall isn't allowing connections through to it (was setup for my old address only), so I need to figure out some solution to that in the near future.  Shouldn't be too hard, it's just not the highest priority atm. :smile:

**Comment by chrisjlocke** [comment]
👍 No problem - was just pre-empting the 'have you tried the latest nightly' suggestion! ;)

**Comment by mgrojo** [comment]
What you observe is expected. The behaviour has changed because it seems the only viable solution for  #1481. The table editing is now done in a single transaction, and the OK button commits the transaction. Opening the dialog also requires you to save any pending changes for starting a new fresh transaction. The Cancel button reverts the transaction.

The only improvement that I come to is changing the OK button to a Save button. That should convey to the user the idea that the change will be written to the database and a choice between saving or cancelling must be done in that very moment.

I hope that this behaviour is only surprising for current users and not for new ones, but not sure.

**Comment by chrisjlocke** [comment]
Guess it makes sense ... you've OK'd the dialog, so don't need to write those changes too ... just a change of habit for me.  Excellent, I'll close this non-issue then!  Thanks for the explanation.
