### ISSUE TITLE
Adding Primary Key To Existing Table Hangs DB4S

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1531]
Details for the issue
--------------------

#### What did you do?
Added a primary key to an existing table with existing data

#### What did you expect to see?
The primary key added to the table.

#### What did you see instead?
DB4S went into 'not responding' mode.  It was a sad time.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.99 (7 Sep 2018)
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Please see screencast
https://screencast-o-matic.com/watch/cFQ22gqK4F

Removing a primary key (if you needed to do that) works fine, so its not just amending a table.  Putting the primary key back again kicks DB4S in the nuts, and it keels over, albeit not immediately - it sits there spinning until you close the window and Windows detects the application is upset.

Tried on a couple of databases with the same result, so it wasn't database specific.
*Creating* a table with a primary key works fine - seems its just **amending** that causes the 'glitch'.

**Comment by mgrojo** [comment]
I don't reproduce it with my toy testing databases. That means almost nothing :smile:

Can you perform these check pragmas in your DB for analysis:
```
pragma foreign_key_check;
pragma integrity_key_check;
```

How many rows has the table? It would also help knowing whether you can reproduce it with a build before 282e6739d907a509d373d6dfb950dcf50666db92 (before 7 Aug).

**Comment by chrisjlocke** [comment]
I'll try this suggestions, but to be honest, it won't be until Monday.  Thanks for the tips!
The table doesn't have many rows at all - approx. 40 ?

**Comment by mgrojo** [comment]
>  The table doesn't have many rows at all - approx. 40 ?

Just guessing that it might be busy copying a very big table. We make that in some table modifications for altering the schema, when SQLite does not allow it directly. Not the case, of course.

**Comment by chrisjlocke** [comment]
>Can you perform these check pragmas in your DB for analysis

>1. pragma foreign_key_check;

This returned 0 rows, as I assume I have no foreign key constraints set.

>-- Result: 0 rows returned in 5ms

|

>2. pragma integrity_key_check

This returned 0 rows, but doing a Google search didn't come back with anything on this pragma - did you just mean integrity check?  If so, that came back clean.

>-- Result: 1 rows returned in 7ms
>integrity_check : ok

|

> and what happens if you add a field?

Adding a new field causes the same lock up, as soon as I click in the 'primary key' column.  

Just to confirm, DB4S is just eating CPU cycles - there doesn't appear to be any disk access, so its not hammering the database, or copying data, etc.

![image](https://user-images.githubusercontent.com/7872218/45743176-6756f800-bbf3-11e8-9a31-ca50da3066c5.png)

**Comment by mgrojo** [comment]
> This returned 0 rows, but doing a Google search didn't come back with anything on this pragma - did you just mean integrity check? If so, that came back clean.

Yes, I meant integrity_check. This was a copy-paste-bad-replacement error :smile:

> Just to confirm, DB4S is just eating CPU cycles - there doesn't appear to be any disk access, so its not hammering the database, or copying data, etc.

Then it would be useful to see a stack trace of the process. In Linux you can do that with gdb or pstack, but I don't know in Windows.

Is the DB schema confidential? It would be useful to test with it.

**Comment by chrisjlocke** [comment]
> Is the DB schema confidential?

I can reproduce this with a new database.  Create database, save changes, amend table, POOF.

See screencast:
https://screencast-o-matic.com/watch/cFQYQ2qPJd

**Comment by mgrojo** [comment]
Wow, I'm still unable to reproduce it. I'm restored defaults, just in case it matters, but not. This is my version information.

> Version 3.10.99 (Sep 12 2018) -> the same for Sep 21.
> 
> Qt Version 5.5.1
> 
> SQLite Version 3.8.6

I've checked the changes from the Sept 9, but nothing seems suspect of fixing that, not even without wanting :smile:

**Comment by chrisjlocke** [comment]
To be fair, I've only tried on my work PC, not my home laptop.  We've not had other reports, so it might be isolated to my PC.  Will try another machine...

**Comment by chrisjlocke** [comment]
Does it on my home laptop too.  
![image](https://user-images.githubusercontent.com/7872218/45938762-e027cc80-bfc4-11e8-914f-efebd5a3b12e.png)

Interesting that its not gone full retard - its not using 100% CPU, but looks like a dog playfully chasing its tail until it throws up.

**Comment by justinclift** [comment]
Quad core cpu?

**Comment by chrisjlocke** [comment]
So I ran it with the debugger, but it doesn't look like its showing anything interesting?

![image](https://user-images.githubusercontent.com/7872218/46081669-fdab9080-c194-11e8-821b-0306189cd0c8.png)

**Comment by MKleusberg** [comment]
Not sure but it looks like there are no debug symbols for DB4S. So the interesting bit would be the hexadecimal numbers but they're hard to decipher without symbols.

One extra question to hopefully further narrow this down without debug symbols: Does the same happen if you click the auto increment checkbox? I'm asking because the primary key checkbox automatically toggles the auto increment checkbox after doing its own stuff. So it's a two part process and by checking it the same problem happens for the auto increment flag we can tell which part of the process is broken.

**Comment by MKleusberg** [comment]
Oh one thing you can tell from the debugger output is that it's something in the multithreading code. And when I look at where we use multithreading, my bet is going to be that the same problem happens for the auto increment field :wink: Still worth checking though :smile:

**Comment by chrisjlocke** [comment]
Thanks for continuing to look into this!
Clicked on 'AI', and the tick appears, some dialog flashes up briefly, /then/ it hangs again - so yes it hangs, but the UI is updated, which doesn't happen when you click 'PK'.

**Comment by justinclift** [comment]
> That doesn't mean much to me - is that something I can 'add' ? Do I need to point WinDbg at another file?

Yep.  It needs a version of DB4S that's compiled in MSVC for "Debugging" instead of for "Release".

The Debugging ones have a bunch of extra info added (eg) to the generated binaries, with things like functions names and similar to aid debugging tools.  We ship the Release ones to cut down on the size of downloads for people, though it does have a negative effect on being able to debug stuff.

Do you still have a development setup for DB4S?  If so, it just needs to be compiled again (Debugging mode) and have WinDBG catch the problem in that.

**Comment by MKleusberg** [comment]
Because Not Null and Unique are working fine and because AI is not as broken as PK, I think the problem lies somewhere else than where I expected. I have looked at the remaining bits of code over and over again and have found one spot which might be the issue here. Can you check in tomorrow's nightly build if the fix changed anything, @chrisjlocke?

**Comment by chrisjlocke** [comment]
> Do you still have a development setup for DB4S?

Not any more.  :-(  Recently changed jobs, and one of the things I left behind was the virtual development setup.  Will have to have a go recreating it.

> Can you check in tomorrow's nightly build 

Gladly! 👍

**Comment by chrisjlocke** [comment]
Sorry for the delay in getting back to this.  The hanging no longer occurs.  Have checked 'AI' too and that's fine now as well.
Thanks @MKleusberg  and @mgrojo for helping.
