### ISSUE TITLE
add schema name when "Drag and Drop Qualified Names" for fields of atacched tables

### ISSUE THREAD

**Issue by n-arakawa** [sqlitebrowser/sqlitebrowser#1534]
Describe the new feature
--------------------------
I recently notice the "Drag and Drop Qualified Names" from DB schema is implemented.
Thanks!

It is more convenient to  add a schema name for attached database! 

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
I considered including also the schema in field names (except for main). Finally I felt that it was too verbose and left only the table name when the qualified option is enabled. But no strong opinion with that, it can be changed. I wonder now if we need an additional option for this or people will be satisfied with selecting between fully qualified and not qualified at all.

By the way, with the current version, you can control-select the schema and the field to get the fully qualified name.

**Comment by n-arakawa** [comment]
> By the way, with the current version, you can control-select the schema and the field to get the fully qualified name.

To have a good result, it is important to disable  qualified option and click items in right order.
 (schema -> table -> field)

> I wonder now if we need an additional option for this or people will be satisfied with selecting between fully qualified and not qualified at all.

It is not so tedious to delete unnecessary qualifier. So I  prefer just  two options:
 -  just simple, or 
 -  fully  qualified

**Comment by mgrojo** [comment]
Ok, qualified means qualified after all. I've added the domain as you suggested.

**Comment by n-arakawa** [comment]
Thanks!
I can get  <schema>.<table>.<fileld>  when drag and drop a field with  'fully qualified' option on.

commit 9daf2657fc15bc8dfad44de71b2fb3381c350d07
Version 3.10.99 (Sep 15 2018)
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

**Comment by mgrojo** [comment]
Thanks for testing, @n-arakawa. Let's close this, then.

By the way I had to edit your comment to understand. At first, the text between `<>` did not show up, and I thought it was failing for you :smile:
