### ISSUE TITLE
Automatic switching of the edit database cell mode according to data type

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1537]
Describe the new feature
--------------------------
This was already mentioned in other issues, but it deserves its own entry.

The editor mode of the Edit Database Cell should take advantage of the data type detection and switch automatically each time a cell is selected or a new data is imported. The user must still be able to switch the mode manually.

Subjects to discussion:
- Should we provide a way to disable the automatic switch so the user can easily navigate through the cells using a mode which is not the preferred? For example, sticking to the XML mode while viewing an SVG column or to binary mode in a text column for inspecting special characters.
- If so, how should be disabled? A checkable button besides the mode combo box? Using a wand  
![imagen](https://user-images.githubusercontent.com/13812910/45846895-6e802200-bd29-11e8-8b9a-8d6e2632ff3a.png) (representing the automagical switch) or a lock ![imagen](https://user-images.githubusercontent.com/13812910/45846911-793ab700-bd29-11e8-9241-bfdde8a844c2.png) ![imagen](https://user-images.githubusercontent.com/13812910/45846927-85267900-bd29-11e8-80b6-848f8da26de4.png)  (representing that the mode is locked to the last user selection, or not)?

Additional info
---------------
#### Is your feature request related to an issue? Please include the issue number.

This was already mentioned in #1438

> As you DO detect what's in a cell, why not change the edit mode to match when a cell is selected?
If I click on a JPEG cell (i have one), why not make the edit mode switch to image automagically?

And in #1173
> It would be great if text values are automatically checked for being parseable as JSON (if they are less than e.g. 100KB), and then the editor automatically switches to JSON.

#### Does this feature exist in another product or project? Please provide a link.
Probably. It isn't something revolutionary.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No screenshot. Use your imagination :smile:

**Comment by justinclift** [comment]
Yeah, if we implement this well it would probably improve usability. :smile:

We'd still need the drop down thing so people can manually override the selection too (eg change to binary view).  At a guess this shouldn't be too hard to get working at least initially.

**Comment by mgrojo** [comment]
I have the changes for automatically switching the mode after selecting a cell and after importing new data from a file. The user can still switch the mode manually after that.

I want to implement now the checkable button for disabling/enabling the automatic switch. I think I'm going to use the wand icon for it. I'm thinking on using the cog (off) ![imagen](https://user-images.githubusercontent.com/13812910/45897134-95e0f880-bdd6-11e8-8616-32f7f951272e.png) and cog_go (on) ![imagen](https://user-images.githubusercontent.com/13812910/45897146-9e393380-bdd6-11e8-9111-2f11d8395012.png) icons that we are already using in other contexts.

**Comment by mgrojo** [comment]
It's now committed in the master branch.

![imagen](https://user-images.githubusercontent.com/13812910/45901130-2bce5080-bde2-11e8-9c61-df1820c18008.png)

**Comment by justinclift** [comment]
Awesome @mgrojo, looks good.  Well placed & appropriate icon (etc). :smile:

I'll probably have time to get the nightlies server working again in a few days, which should help get this out to people too. :smile:

**Comment by mgrojo** [comment]
@tlhackque and @wmertens, you might like to try this new feature that both of you proposed in the referred issues. It is now available in the latest [nightly build](https://nightlies.sqlitebrowser.org/latest/).

**Comment by chrisjlocke** [comment]
@tlhackque and @wmertens ... *cough*

**Comment by tlhackque** [comment]
Have not forgotten, but have been away.

Expect to catch up later this week.

I appreciate the effort - sorry about the bad timing.

**Comment by chrisjlocke** [comment]
No problem - whenever is convenient.  😸

**Comment by justinclift** [comment]
Closing this, as it seems to be complete. :smile:
