### ISSUE TITLE
don't show images

### ISSUE THREAD

**Issue by mahas44** [sqlitebrowser/sqlitebrowser#1538]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version: win10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Can you provide more informartion, like screenshots, video recording or a textual description of what do you expect and what is the unwanted result? I guess the image viewer isn't working, but please provide more information.

**Comment by mahas44** [comment]
I can try the this db on the https://sqliteonline.com this link and i can
see the images but in this program i can't see

Manuel <notifications@github.com>, 23 Eyl 2018 Paz, 14:52 tarihinde şunu
yazdı:

**Comment by mgrojo** [comment]
@mahas44 Maybe you are affected by issue #579. If you try with a nightly build: https://nightlies.sqlitebrowser.org/latest I think you'll be able to see several types of images. Could you try and report back if it's solved for you? The nightly includes also several bug fixes and improvements that will be in the next official release and it's pretty stable.

**Comment by justinclift** [comment]
@mahas44 Did that help? :smile:

**Comment by mahas44** [comment]
yes it's help. I can see the images now. Thanks for helping.

Justin Clift <notifications@github.com>, 25 Eyl 2018 Sal, 06:55 tarihinde
şunu yazdı:

**Comment by justinclift** [comment]
Awesome. :smile:
