### ISSUE TITLE
Ability to link tables with dropdowns for auto-input

### ISSUE THREAD

**Issue by tonnyavery** [sqlitebrowser/sqlitebrowser#154]
I have a big database in mind that will be in sqlite.
And the most common data fill scenario would be the following:
There are 2-3 dictionary-tables that store dictionary entires, lots of them.
And there will be 1 table that will tie these entries together.
Obviously, this combination-table will have only id's from dictionary-tables, but it's so difficult to first input dictionaries, and they jump between tabs trying to memorize id's while pasting them to combination table.

I understand this probably isn't any close to a possible priority, but if there was only a way to say 'this cell of tableA can have only id's of tableB rows', but when I try to type something into tableA cell - show a dropdown of not-yet-added rows from tableB so I would be able to pick a row by the name, and UI would just add a correct id. This will simplify managing data a lot.

**Comment by axd1967** [comment]
> Can be done easily with SQLite and perhaps it is done yet. To re-invent the wheel is a waste of time, isn't it. Post it to SQLiteUserList and you'll get quite a few answers, I suspect.

@Z4us  If it can be done **easily**, can you **pls** give some hints?
