### ISSUE TITLE
import csv if foreign key is pre-defined or delete imported rows if foreign key not existed

### ISSUE THREAD

**Issue by antonybits** [sqlitebrowser/sqlitebrowser#1540]
in db browser
1. how is it possible to import those rows of a csv file into a table that contains foreign key in specific column?
2. further more, is it even possible to import rows if a foreign key is present in any one of the columns? (if not i have to repeat the first question's answer for importing as many as the column )
3. is it possible for an existing table to delete rows that dose not contain a foreign key in one specific column?

**Comment by antonybits** [comment]
> Is this helpful?

Thanks, It was helpful

**Comment by justinclift** [comment]
Excellent. :smile:

@antonybits Should the issue be closed now?
