### ISSUE TITLE
App asking for Calendar access and Accessibility Features on Mac

### ISSUE THREAD

**Issue by andrewackerman** [sqlitebrowser/sqlitebrowser#1542]
What is your question
-----------------------

I'm running DB Browser for SQLite v3.10.1 on my Mac with Mojave (10.14), and I've been using it for a while now. Yesterday out of nowhere, I got a notification that the app was requesting access to my Calendar, and today I got one that the app was requesting access to control my computer using Accessibility Features. The second one I can sort of speculate on, but I haven't the faintest idea why this app would ever need access to my Calendar. There isn't some secret nested spyware or adware in this app, is there?

**Comment by justinclift** [comment]
Ugh, that's bizarre.  No there's definitely nothing of the sort in this.

Weirdly, it sounds like something has either compromised your installation (and infected DB4S), or there's something else weird/untoward going on.  From memory - it's been ages since I actively used OSX - Sophos makes some kind of virus/malware scanner for it.  There are probably others too.

Personally I'd probably make a clone of the hdd, then scan it with every kind of malware/virus finder I could locate. :frowning:

**Comment by justinclift** [comment]
Just remembered something else potentially useful.  OSX/macOS comes with a command line tool `codesign` for verifying the signatures of applications.

If you're ok with using the command line for stuff, you should be able to see if the application has been changed with something like:

```
$ codesign --verify --deep --verbose "/Applications/DB Browser for SQLite.app"
```

Note that command is from memory, there's a decent chance some of those arguments might need tweaking to work (eg there might not be a `--verbose` option).
The man page will have the exact right bits though. :smile:

**Comment by justinclift** [comment]
Also just to check... you haven't recently re-downloaded DB4S from somewhere have you?  If so, we might need to look into where.  If some of our download infra has been compromised... that would really suck.

**Comment by andrewackerman** [comment]
Running the codesign gives me the following output:

    /Applications/DB Browser for SQLite.app: valid on disk
    /Applications/DB Browser for SQLite.app: satisfies its Designated Requirement

I haven't redownloaded the app since I downloaded it from the official homepage at the beginning of August (from a `https://github-production-release-asset-2e65be.s3.amazonaws.com` download URL to be exact).

**Comment by MKleusberg** [comment]
@justinclift Do you know how Qt versions work for DB4S on OS X? Do we use a system-wide version of Qt or do we bundle our own? I don't have any particular idea in mind here, just asking to rule out the possibility that the problem might be in an updated version of Qt and not in DB4S itself.

**Comment by justinclift** [comment]
@MKleusberg @andrewackerman Sorry, I somehow missed the status change of this issue so haven't seen your replies until now.

@andrewackerman The response from the code sign utility is useful, and it's saying things look ok.  On one hand, that's good news. eg no dodgy malware thing there.  On the other hand... no smoking gun. :wink:

It sounds like it might turn out to be some kind of Qt accessibility thing then.  It's just no-one else has reported similar (so far), so whatever the cause it... doesn't appear to be widespread yet.

As a general thought... does the same thing happen if you launch DB4S directly from the command line?  eg `/Applications/DB Browser for SQLite/Contents/Resources/ ...`  <-- I don't remember the full path to the binary from memory, so you'll need to take a look.

**Comment by revolter** [comment]
Interestingly enough, [this answer](https://apple.stackexchange.com/a/332686/93280) regarding Mojave's permissions actually features screenshots from DB4S 😃

**Comment by revolter** [comment]
Related to https://github.com/atom/atom/issues/17687.

**Comment by justinclift** [comment]
Good stuff @revolter. :smile:

Yep, we should probably point people to something that explains what it means, and show people how to do the `Full Disk Access` thing if it's appropriate to their situation. :smile:

**Comment by justinclift** [comment]
Ugh.  We can't point people at that discuss.atom.io website info.  I just attempted to save it via [wayback machine](https://archive.org), and the discuss.atom.io website just gave a 404 to the wayback machine's archival program.  So, that's what got saved for posterity (the 404) instead of real content.

We'll probably need to write our own info article on the wiki then.  Would you be up for that @revolter? :smile:

**Comment by andrewackerman** [comment]
@revolter That makes sense why I haven't seen the prompt, as I haven't tried to open any database files in "protected" folders since I installed the alpha version. Of course, it's also possible that since I responded to the prompts in the first place, installing the alpha on top if the existing version inherited those responses.

**Comment by revolter** [comment]
Indeed you are asked only once. In the related issue that I linked to you can also see some screenshots and more details about this.

**Comment by jacoscaz** [comment]
Just stumbled into these worrying requests to access calendar, contacts and accessibility features. Indeed, It happened as I was browsing `~/Library/Application Support`. Nice to know nothing dodgy is happening!

**Comment by justinclift** [comment]
Closing this, as it's not come up since last year and isn't really a DB4S thing. :smile:
