### ISSUE TITLE
Installer needs to be elevated ..

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1545]
Already have an msi version installed. Just tried to run the latest nightly build and it failed requiring admin right to C:\Program Files ...

Installer needs to run elevated?

**Comment by karim** [comment]
Installer is already running elevated to be able to install in "Program Files". However, "Program Files" cannot be updated by limited users. MSI cannot violate that by allowing limited users to install files there.

**Comment by mtissington** [comment]
To be clear I have a good few year experience with WIX ... I'm logged in and running as admin user. Installer did not give me the usual security prompt when running elevated. It really is not running elevated when I do the upgrade.

**Comment by karim** [comment]
I checked the documentations for WiX again and the required attribute `InstallScope="perMachine"` seems to be set correctly. `InstallPrivileges="elevated"` is not added to the `Package` element since it is the default.

https://github.com/sqlitebrowser/sqlitebrowser/blob/2dd1dce09f376833fa0283649d942261321b0bec/installer/windows/product.wxs#L8

I don't know what is missing here. I will have to check again.

To be clear, the app is installed correctly (a nightly build) but when you tried to update it with another nightly build it fails?

**Comment by mtissington** [comment]
Yes, clean install works. Update does not. When I run a clean install, the Install button shows the shield and prompts me to elevate. When I attempted an upgrade it did not show the shield.

**Comment by karim** [comment]
I just added `InstallPrivileges="elevated"`. Hopefully this can fix this issue. You should try tomorrow's nightly to check it.

 If not then an installation log will be needed to see why it is not elevating and why it fails. Simply run `msiexec /i MyApplication.msi /l*v MyLogFile.txt` to generate it and maybe send it to my email?

**Comment by justinclift** [comment]
Cool.  This sounds like a good thing to get sorted out before the next release, as it's almost guaranteed other people will hit it too. :smile:

**Comment by mtissington** [comment]
You might want to add the following to always produce a full log in the users %temp% folder which you can then ask for if it's needed.
 

<Property Id="MsiLogging" Value="voicewarmupx" />

**Comment by mtissington** [comment]
There maybe a way of specifying the file name - not sure ...
I think you can set the property regardless of version, it just won't do anything on XP.
I thought 4.5 was part of XP SP3?

**Comment by karim** [comment]
Fair enough. I just added a commit with your suggestion. Thanks again. :smiley: 

> There maybe a way of specifying the file name - not sure ...

There is a [MsiLogFileLocation](https://docs.microsoft.com/en-us/windows/desktop/Msi/msilogfilelocation) property, but it is a read-only value that is set to the full path of the log file.

>  I think you can set the property regardless of version, it just won't do anything on XP.

I didn't change the version, so I hope you are right. :smile:

> I thought 4.5 was part of XP SP3?

Windows XP SP3 comes with version 3.1, but you can download 4.5 for it. If we changed the version to 4.0 the installer will not even run if the user machine isn't updated.

**Comment by mtissington** [comment]
Hmm, well you could add a condition to the installer that it requires at least XP SP3 ... there has to be a limit of what you can support ?

**Comment by karim** [comment]
Setting the `InstallerVersion` to 3.1 doesn't do that automatically, since it is not available on earlier versions?

**Comment by karim** [comment]
While I think setting the `InstallerVersion` is enough to exclude OS older than Windows XP, I don't see anything wrong with adding a condition like you just described.

If you are familiar with GitHub you can make a PR (Pull Request) and I will merge it.

**Comment by karim** [comment]
Is it working now as expected? Can you update without uninstalling and then installing the new version?

**Comment by justinclift** [comment]
Just manually started the Win64 nightly builder again, so in ~30 mins or so there'll be a redone (new) one online for today.  Will get the Win32 one done some time after that. :smile:

**Comment by justinclift** [comment]
@mtissington Reminder ping. :smile:

**Comment by mtissington** [comment]
It's winter, long dark nights ... 
I can confirm the nightly now installs correctly over an existing nightly.

**Comment by justinclift** [comment]
> It's winter, long dark nights ...

Yeah, I only recently moved from the UK (summer at the time) back to Australia, which is now coming into summer too.

So, it'll be a continuous year of reasonable weather for me, instead of being stuck in the UK.  So very much **not** missing the UK weather. :grin:

> I can confirm the nightly now installs correctly over an existing nightly.

Excellent, thanks heaps @mtissington. :smile:
