### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by henrykironde** [sqlitebrowser/sqlitebrowser#1548]
Describe the new feature
--------------------------
Due to several patches merged, could we have a new release of the software.

**Comment by justinclift** [comment]
Yep, it's a good idea.  @MKleusberg raised this too um... yesterday I think in the private team discussion area.

We'll probably need to figure out which outstanding issues are blockers (there shouldn't be many), get those fixed, then start through the branching and stabilisation process.

**Comment by justinclift** [comment]
As a heads up, we're working on this now.  An initial alpha or beta (unsure which yet) will probably get made & released this weekend (eg late Sunday).

There will probably be a few (hopefully mostly minor) issues reported against that, so we'll get them taken care of then release the next beta or final. (as appropriate)

**Comment by justinclift** [comment]
The new DB4S 3.11.0-alpha1 release has been published:

* https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-alpha1

It's the same code from our nightly builds as of this morning, just it's now a point in time that we'll work to stabilise and tweak so it's ready for "production" use.

That being said, we're not expecting (!) anything terrible to show up in it.  Fingers crossed (for luck). :grin:

**Comment by justinclift** [comment]
@henrykironde We (finally) released the new version:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-11-0-released/

And yeah... that took an extended amount of time eh? :wink:
