### ISSUE TITLE
Completion doesn't work until refresh is pressed in DB 

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1549]
Details for the issue
--------------------

#### What did you do?
Run DB4S, open a database, click on Execute SQL, type "sel".

#### What did you expect to see?
The SQL editor proposes "SELECT" as completion.

#### What did you see instead?
No completion.

If I press F5 in DB Structure, it starts working. 

It happens several nightlies ago. It doesn't happen with 3.10.1

Useful extra information
-------------------------
> DB4S v3.10.99 (Sep 29 2018) on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.25.1
> and Qt 5.8.0

**Comment by mgrojo** [comment]
This seems solved. If someone wants to confirm it, I will wait some time before actually closing this.

**Comment by MKleusberg** [comment]
I can confirm it's working. There is however another somewhat related bug: when you open DB4S, then load a database via the menu it's working fine, but if you open a database via a command line argument or by file association the auto completion doesn't show you table names and so on from the database until you hit F5. This was mentioned somewhere in an issue but I can't find it now.

**Comment by MKleusberg** [comment]
Yeah, I'll reopen this issue so the point isn't lost. If the other issue I was thinking of if still open and we find it we can close one of them of course.

**Comment by mgrojo** [comment]
> if you open a database via a command line argument or by file association the auto completion doesn't show you table names and so on from the database until you hit F5.

I don't reproduce that. Isn't it also fixed with this change?

**Comment by mgrojo** [comment]
Does someone still reproduce this in some way?

**Comment by chrisjlocke** [comment]
Works OK for me - just tested the latest nightly.

**Comment by MKleusberg** [comment]
Seems like it's working :smile: I'm just going to close this issue then.
