### ISSUE TITLE
How to open a database that is protected by a password?

### ISSUE THREAD

**Issue by chucklu** [sqlitebrowser/sqlitebrowser#155]
I create a sqlite database with the password 'abcd'.When I try to open the database ,this software just told me "Invalid file format"
I wonder why there is no choice to inuput the password to access the database

**Comment by justinclift** [comment]
Hmmmm, thinking this specific issue through, it seems like it's not really a problem with DB4S, nor something we can really do anything with.

Going to close it as "invalid" for now, as it's most likely a file created using an encryption method we don't support yet (nor plan to, unless someone wants to take up the task :wink:). 

If that doesn't seem right, feel free to reopen this. :smile:
