### ISSUE TITLE
Several "All Files (*)" entries in open database dialog

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1556]
Details for the issue
--------------------

#### What did you do?
File -> Open Database...

#### What did you expect to see?
My configured file extensions filters and _All Files (*)_

#### What did you see instead?

![imagen](https://user-images.githubusercontent.com/13812910/46505940-ecb4ec00-c832-11e8-9858-bdc38f15b3d3.png)

Multiple "_All Files (*)_" filters. Each time Preferences are saved, a new "_All Files (*)_" entry is added (using your configured language).

Useful extra information
-------------------------
> DB4S v3.10.99 (Sep 29 2018) on Ubuntu 16.04.5 LTS (linux/4.4.0-137-generic) [x86_64]
> using SQLCipher Version 3.2.0 (based on SQLite 3.8.6)
> and Qt 5.5.1

**Comment by justinclift** [comment]
Heh Heh Heh.  Well, that's definitely a blocker to the final 3.11.0 release. :wink:

Well spotted @mgrojo. :grinning:

**Comment by MKleusberg** [comment]
Are you sure this is still happening, @mgrojo? I noticed the same a while ago but after deleting all(!) "All files" entries in the File Extension Manager dialog, they never appeared again, no matter how many settings I changed elsewhere. So I thought they were just the remnants from when the dialog was still in development.

**Comment by karim** [comment]
I get the same also.

File -> New Database...

![db4s-1](https://user-images.githubusercontent.com/8761081/46530537-5caa8d00-c89a-11e8-85e4-6dc43f7d19e2.jpg)

File -> Open Database...

![db4s-2](https://user-images.githubusercontent.com/8761081/46530565-7350e400-c89a-11e8-98cb-5361bc9d4bc3.jpg)

Useful extra information
-------------------------
> DB4S v3.10.99 (Oct  4 2018) on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.25.1
> and Qt 5.8.0

**Comment by chrisjlocke** [comment]
Ditto (latest nightly)

![image](https://user-images.githubusercontent.com/7872218/46530794-cf176f00-c892-11e8-877c-e6791184afbe.png)

Its persistent too.  So start DB4S, go through the preferences, click OK.  Another 'All files' is shown on the 'Open Database' filter.  Close DB4S.  Open DB4S.  Still has all the 'All files' entries...

**Comment by MKleusberg** [comment]
Yeah, you're right :smile: I misinterpreted this somehow back then.

**Comment by MKleusberg** [comment]
This should be fixed now. The extra "All files" entries won't go away automatically though. However, they should be visible in the File Extension Manager dialog now, so you can delete them there. You'll need to delete all of them.

Interestingly, even before my commit they were deleted every time you would open the file extension dialog and click OK, even though you didn't see them. I think that's what lead me to believe that there's no more problem to fix here :wink:

**Comment by mgrojo** [comment]
Thanks, @MKleusberg. It's working well now.
