### ISSUE TITLE
To be able to edit entries from "views"

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1564]
Describe the new feature
--------------------------

To be able to edit entries from "views".

I had a brief discussion on another issue in the past about this, but now it is really frustrating me! I need to be able to sort my table by multiple columns and the only way to do this is using a View.

Views are not editable currently, so this kind of renders them useless for the purposes of editing, and it would be super useful to be able to edit cells WITH sorting!

Thanks

**Comment by mgrojo** [comment]
Yes, this was mentioned before and there are ways to edit some views, you need to define pseudo primary key and a trigger for editing it. I'll redirect you to the previous issue and close this as redudant. We need to keep the issue count to a sane account :smile: It's  #1320.

**Comment by chrisjlocke** [comment]
#1360 too.
