### ISSUE TITLE
UNIQUE Constraint Failed - Import/Export CSV file

### ISSUE THREAD

**Issue by greygizmo** [sqlitebrowser/sqlitebrowser#1566]
I am new to SQLite and trying to use DB Browser to modify an existing database. I'd like to export a table, modify it, and the reimport it.

However, when I try this workflow (without even editing the exported CSV) I get an error message when importing stating that the "UNIQUE Constraint Failed" while trying to import record 1.

Can someone point me in the right direction? Happy to submit more information if needed!

**Comment by mgrojo** [comment]
It might be that the data in the table is already out of integrity. Could you try running ### Tools > Integrity Check and **Tools > Foreign-key Check** on that database? If your version doesn't have these tools, use directly these pragmas in an Execute SQL tab:

`PRAGMA integrity_check;`

`PRAGMA foreign_key_check;`

If the warn about any data not accomplishing the constraints. Manually edit them. In your case there seem to be duplicated values in a UNIQUE column.

**Comment by chrisjlocke** [comment]
Its a sort of known issue that the importing of data isn't 'sensible', in that it doesn't know in which order to import the data.  ie, you might input a record into a table with 'country_id=3' but the country table doesn't exist / been populated yet, so obviously the constraint fails.  

My memory of pragmas is foggy, but there is a foreign key / constraint pragma which disables this checking, so you can input the data, then turn on the checking again.

Alternatively, you can amend the CSV so that the tables are in the right order - depends on how big/complex the CSV is, and how bored you are...

To confirm my ramblings, can you post line 1 of the CSV file?

**Comment by greygizmo** [comment]
The PRAGMA checks seem to execute ok - no errors.

I've uploaded an example of the CSV file generated by the export. It's a very simple example - the tables I am hoping to edit will contain about 2 dozen columns and potentially hundreds of rows.

I changed the file type to .txt to allow the upload. If I import this file in CSV form, exactly as generated by DB Browser, I get the error. I tried without column names in first line and other types of field separators with no success.

[TurnLeadInType.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/2473989/TurnLeadInType.txt)

**Comment by greygizmo** [comment]
![image](https://user-images.githubusercontent.com/44095624/46884356-fd0c2e80-ce11-11e8-829e-8f0739b3e821.png)

That file corresponds to this table

**Comment by greygizmo** [comment]
For some context, this is a table that is installed with a manufacturing software. That software includes a GUI but the interface only allows me to populate one new row at a time, manually. 

I'd like to bypass the GUI by editing the database tables in DB Browser using spreadsheets.

**Comment by mgrojo** [comment]
I guess you are importing the data to tables that already contain the values, triggering the UNIQUE constraint of some column to fail.

The best approach would be to export the DB schema: **File > Export > Database to SQL File** and then select **Export schema only**. Then create a new database, import the SQL file and you have an empty database with your schema. Then load the data in the tables.

**Comment by greygizmo** [comment]
Yes I am trying to overwrite the existing table (export, edit, import and overwrite existing).

The database contains several hundred tables, of which I only desire to edit a small number. If I am following, if I export the schema only I would need to reimport all the tables individually.

**Comment by mgrojo** [comment]
You can delete all the rows of the table before importing. You can do that in the Data Browse tab (select all <kbd>Ctrl</kbd>+<kbd>A</kbd> and delete <kbd>del</kbd>) or simply run this in the Execute SQL tab for each of the tables you want to clear:
```sql
DELETE FROM "table_name";
```
An option for overwriting the table contents on import would make sense in the application though.

**Comment by chrisjlocke** [comment]
> of which I only desire to edit a small number.

One issue is that a table can have what is called an auto-increment field.  This is a field which is (putting it basically) a record number for that table.  It can either be a simple auto-increment field, or an advanced one.  With a simple auto increment field, lets say you add a record number 100.  Then delete it.  If you add another new record, that will now be record 100.  With an advanced auto-increment field, that new record will actually be 101.  SQLite knows it used 100 previously, so it won't use it again.

The reason I'm wobbling on about this, is that if you deleted 100 records from your 'orders' table and re-imported, they'll either start again at 1, or they could continue from 101.  This could potentially break the rest of your database - another record could be looking at record 45, but that record no longer exists - its now 145.  This all depends on your schema.

Obviously, take backups of your databases before deleting / changing anything!

> Yes I am trying to overwrite the existing table

In DB4S you can export just one table to SQL, do what you need to do, delete that table in DB4S and re-import just that table again from the SQL file.

If you delete just the records from the table, you could be there a while - thats a very slow process.  Its much quicker to delete the table and reimport it from the SQL file.

**Comment by greygizmo** [comment]
Really appreciate the suggestions guys! Still not there yet... deleting the table and importing a new version (with the same name) got the information in but seems to have broken a connection to somewhere else in the db (I lost access to my list when coming in through the GUI after importing).

When deleting the table there was a warning that "All data associated with the table would be lost." I was hoping that would have no impact but that doesn't seem to be the case.

Ctrl-A and deleting the cells eliminated the data but when importing it back in I ran into the same "UNIQUE Constraint Failed" message.

It does seems like overwriting existing data when importing is the way to go... is there any way to simply copy/paste new cells into an existing table?

**Comment by chrisjlocke** [comment]
> is there any way to simply copy/paste new cells into an existing table?

You'd have to delete existing data first.  An import imports a whole row - it doesn't just change existing data amending the fields that have changed.

> When deleting the table there was a warning that ....

Thats fine.  Thats what you want.  You're importing a fresh copy of that table.

> but seems to have broken a connection to somewhere else in the db

Not sure what you mean.  Do you mean the program was unable to see the new data you'd input?

**Comment by greygizmo** [comment]
Correct - the new data was not visible. If I manually add a record to a table, one at a time, then the data is available through the front-end GUI. However when I deleted a table completely and imported a new version of it, that data was no longer accessible.

I am trying to add to a tool list. My software lists tools by type - each type having it's own table as seen in DB Browser. After deleting/importing a table for one type (in this case, tapered tools) the GUI listed the wrong tools when I tried to access them in the GUI (accessing the Tapered Tool section displayed the list for another type of tool, Corner Round).

**Comment by chrisjlocke** [comment]
Willing to help as much as I can, but it might take a few posts here! ;)  
Would be interested in viewing the table before and after editing to see whats changed, to try and determine why your program is seeing the wrong tool type.

What operating system are you using?

**Comment by justinclift** [comment]
@greygizmo As a data point, because I'm not seeing it mentioned yet anywhere... which version of DB4S (our abbreviation for DB Browser for SQLite) is this happening with? :smile:

**Comment by chrisjlocke** [comment]
@greygizmo *cough*

You still experiencing issues?

**Comment by mgrojo** [comment]
@greygizmo  I hope we have helped you. I'll close this now, but you can still comment on it if you'd like.

**Comment by jemshit** [comment]
I am in similar situation, i want to **merge** to databases. They have overlapping records, when i import one into another, i get the same error. How could i order to ignore/overwrite the same records (that has same unique constraint)?

**Comment by jemshit** [comment]
Nvm, i think i found a way
1- Open DB-A
2- Attach DB-B
3- Execute this command

```sql
INSERT or IGNORE into MyTable SELECT * FROM "DB-B".MyTable
```
