### ISSUE TITLE
Translations for the next release wanted

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1567]
We are in the process of releasing a [new stable version](https://github.com/sqlitebrowser/sqlitebrowser/releases) of 'DB Browser for SQLite' with many new features and additions.

This is a kind request to our users to help us in making DB4S better by translating it to their languages or updating the translation of the last release (when available).

The *.ts files are already updated on the release branch: https://github.com/sqlitebrowser/sqlitebrowser/tree/v3.11.0-alpha1

You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/issues/182#issuecomment-70413095) about how to do it. I'll be happy to assist you in the process, in case you had any doubt.

**Comment by mgrojo** [comment]
@FriedrichFroebel @bssthu Any interest in helping again?

I've also notified other previous contributors by e-mail. Let's hope that many translations are updated or added for the release.

**Comment by mgrojo** [comment]
@efreeking Any interest in contributing again to the simplified Chinese translation?

**Comment by bssthu** [comment]
I'll translate simplified Chinese.

**Comment by mgrojo** [comment]
There has been an update to strings since we created the v3.11.x branch due to security-related PR  (#1558).

There are two new strings in Preferences (an option and its tooltip) and
two functions call-tips that are updated with this appendix:
> "Use of this function must be authorized from Preferences."

Nevertheless, not all translations are including function call-tips.
    
I've discarded line changes after lupdate so the amount of changes for merging of translation pull requests are minimised.

Example of the changes:

```diff
------------------------ src/translations/sqlb_es_ES.ts ------------------------
index 1aa323c..af65f39 100644
@@ -6052,14 +6052,24 @@ p, li { white-space: pre-wrap; }
         <translation>(X,Y,Z) La función like() se usa para implementar la expresión &quot;Y LIKE X ESCAPE Z&quot;.</translation>
     </message>
     <message>
-        <location filename="../SqlUiLexer.cpp" line="79"/>
         <source>(X) The load_extension(X) function loads SQLite extensions out of the shared library file named X.</source>
-        <translation>(X) La función load_extension(X) carga extensiones SQLite del archivo de la biblioteca compartida llamada X.</translation>
+        <translation type="vanished">(X) La función load_extension(X) carga extensiones SQLite del archivo de la biblioteca compartida llamada X.</translation>
     </message>
     <message>
-        <location filename="../SqlUiLexer.cpp" line="80"/>
         <source>(X,Y) The load_extension(X) function loads SQLite extensions out of the shared library file named X using the entry point Y.</source>
-        <translation>(X) La función load_extension(X) carga extensiones SQLite del archivo de la biblioteca compartida llamada X usando el punto de entrada Y.</translation>
+        <translation type="vanished">(X) La función load_extension(X) carga extensiones SQLite del archivo de la biblioteca compartida llamada X usando el punto de entrada Y.</translation>
+    </message>
+    <message>
+        <location filename="../SqlUiLexer.cpp" line="79"/>
+        <source>(X) The load_extension(X) function loads SQLite extensions out of the shared library file named X.
+Use of this function must be authorized from Preferences.</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../SqlUiLexer.cpp" line="80"/>
+        <source>(X,Y) The load_extension(X) function loads SQLite extensions out of the shared library file named X using the entry point Y.
+Use of this function must be authorized from Preferences.</source>
+        <translation type="unfinished"></translation>
     </message>
     <message>
         <location filename="../SqlUiLexer.cpp" line="81"/>
```

**Comment by bartlomiej-przymus** [comment]
Hi guys im new to github and i could possibly contribute by translating it to Polish language dont know  how to go about it but would like to contribute :) Earn my hacktoberfest t-shirt proper way :)
I have experience with MySql PHP Javascript HTML CSS. Let me know if you would be intrested.

**Comment by SafaAlfulaij** [comment]
I am wondering where to keep the qm file in order to test the translation in Windows... :)
btw, I know this is late, but I think that it's almost a standard to keep a colon in forms (like Password: <lineedit>)

**Comment by FriedrichFroebel** [comment]
@bartlomiej-przymus Should be easy using the following steps:

1. Fork the repo.
2. Clone your fork.
3. Get [Qt Linguist](https://doc.qt.io/qt-5/linguist-translators.html). It depends on your OS what is the best way to get this.
3. Open the file `sqlitebrowser/src/translations/sqlb_pl.ts` of your clone with Qt Linguist.
4. Translate all the strings with Qt Linguist until you have translations which are marked either as correct or obsolte (see [here](https://doc.qt.io/qt-5/linguist-translators.html#selecting-context-to-translate) for the symbols).
5. Save you changes to the file from within Qt Linguist.
6. Commit your changes and push to a new branch of your fork.
7. Create the corresponding Pull Request.

**Comment by bartlomiej-przymus** [comment]
@FriedrichFroebel Thanks I will do as suggested. It will be great practice for me :)

**Comment by Feyn-Man** [comment]
Working on the italian

**Comment by mgrojo** [comment]
@bartlomiej-przymus 
>Let me know if you would be intrested.

Of course we are interested. If you need more help, you only have to ask for it. Thanks for contributing!

@Feyn-Man 
> Working on the italian translation

Great to know. That was an undeserved absence. Thanks!

**Comment by Feyn-Man** [comment]
How can i generate an empty ts file for the italian? I tried to open the file `src.pro` with Qt creator in order to generate it via lupdate but I'm not able to open the file (I've never used Qt before) correctly.
Anyway actually I copied the german translation and I'm editing it but this is not the best solution I think.

**Comment by mgrojo** [comment]
> How can i generate an empty ts file for the italian? I tried to open the file src.pro with Qt creator in order to generate it via lupdate but I'm not able to open the file (I've never used Qt before) correctly.
Anyway actually I copied the german translation and I'm editing it but this is not the best solution I think. 

You can change the src/src.pro file with a simple text editor. You have to add the new file to the TRANSLATIONS variable. Then run "lupdate src/src.pro" and the new file will be generated. Then you can add the file to the repository. If you have already edited the copy from German, overwriting the generated file is an option. A better one will be a manual merge with some merge tool, so the translations don't appear as finished, while still being in German.

**Comment by Feyn-Man** [comment]
@mgrojo finally I generated a new file form src.pro

**Comment by bartlomiej-przymus** [comment]
Sorry for bothering you guys i just configured my git bash and after translating some i saved changes done local commit and entered git push and i got following: remote: Permission to sqlitebrowser/sqlitebrowser.git denied to bartlomiej-przymus.
Im trying to learn git commands so maybe i've done something wrong?

**Comment by FriedrichFroebel** [comment]
@bartlomiej-przymus You are working on a clone of this repo. You have to clone your fork of this repo instead - in this fork you will have write permissions for pushing your changes. You might can change this be editing the `.git/config` file or by moving the edited language file to the directory where you cloned your fork to.

**Comment by mgrojo** [comment]
We don't have a rigid schedule for releasing the 3.11.0  version, but we aren't receiving any bug report for the current alpha version, so we only plan to upgrade the Qt version #1580, decide if we include any of the current pull requests and wait for the pending translations. When do you think they will be ready? Is a rough deadline of one or two weeks from now possible?

**Comment by justinclift** [comment]
@bartlomiej-przymus As mentioned by @FriedrichFroebel above, the git command you're using was trying to store your changes directly in our central GitHub repo here.  Which you don't (yet) have permission for. :wink:

You need to send the changes to your own fork, which I can see you're already created (yay!): https://github.com/bartlomiej-przymus/sqlitebrowser

Running these commands should get your fork set up, so you can send your changes to it later:

```
$ git remote add myfork https://github.com/bartlomiej-przymus/sqlitebrowser
$ git remote update myfork
```

When that's done, the command you use for sending changes to it is:

```
$ git push myfork master:change1
```

That should create a new "change1" branch in your fork, that we'll be able to grab them from.

Alternatively, if you're not too overloaded with new stuff we can guide you through creating a "Pull Request", which is the standard way to do things.

Does that help? :smile:

**Comment by Feyn-Man** [comment]
@mgrojo I don't think that my translation will be ready for the end of this week, a deadline of 2 weeks is more suitable for me.

**Comment by bartlomiej-przymus** [comment]
> @bartlomiej-przymus As mentioned by @FriedrichFroebel above, the git command you're using was trying to store your changes directly in our central GitHub repo here. Which you don't (yet) have permission for. 
> 
> You need to send the changes to your own fork, which I can see you're already created (yay!): https://github.com/bartlomiej-przymus/sqlitebrowser
> 
> Running these commands should get your fork set up, so you can send your changes to it later:
> 
> ```
> $ git remote add myfork https://github.com/bartlomiej-przymus/sqlitebrowser
> $ git remote update myfork
> ```
> When that's done, the command you use for sending changes to it is:
> 
> ```
> $ git push myfork master:change1
> ```
> That should create a new "change1" branch in your fork, that we'll be able to grab them from.
> 
> Alternatively, if you're not too overloaded with new stuff we can guide you through creating a "Pull Request", which is the standard way to do things.
> 
> Does that help?

Yes it helps! thank you all is good now :)
I wlii work as much as I can to get this done as soon as possible. I'm bad with approximations but i would say 2 weeks is achievable I will try.

**Comment by mgrojo** [comment]
@bartlomiej-przymus @Feyn-Man Ok, we intend to release around 4th November then. Let's hope all the pending activities, including the in-progress translations are ready by then.

**Comment by bartlomiej-przymus** [comment]
Just letting you guys know that i have some matters that i need to attend to i will continue pushing commits to my translation but I wont make it for the 4th of November

**Comment by SafaAlfulaij** [comment]
Hello.
Sorry but I'm currently unable to set-up a git clone. Can you commit the file instead?
Thanks!

[sqlb_ar_SA.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/2543162/sqlb_ar_SA.zip)

**Comment by mgrojo** [comment]
Hi, @SafaAlfulaij 
Of course, no problem.

But the translation is incomplete. Do you plan to continue it before the final release or do you want me to commit it as is?

![imagen](https://user-images.githubusercontent.com/13812910/47929720-33494500-deca-11e8-88f9-1020523693ad.png)

**Comment by mgrojo** [comment]
@bartlomiej-przymus 
> Just letting you guys know that i have some matters that i need to attend to i will continue pushing commits to my translation but I wont make it for the 4th of November

Thanks for reporting. Don't worry, if you cannot complete it, we will merge whatever you have and the complete translation could go to the first fix release.

**Comment by SafaAlfulaij** [comment]
> 
> 
> Hi, @SafaAlfulaij
> Of course, no problem.
> 
> But the translation is incomplete. Do you plan to continue it before the final release or do you want me to commit it as is?
> 
> ![imagen](https://user-images.githubusercontent.com/13812910/47929720-33494500-deca-11e8-88f9-1020523693ad.png)

mmm, the file has nothing more. I ran the needed Qt tool to update the strings to latest, but didn't get those :\
If you can update it I'll be thankful, and sorry as well :)

**Comment by bartlomiej-przymus** [comment]
@mgrojo I plan to complete it. It will take me a little bit more time. As i am changing my career to webdevelopment there is a lot of things to sort out.

**Comment by mgrojo** [comment]
@bartlomiej-przymus 
> I plan to complete it. It will take me a little bit more time. As i am changing my career to webdevelopment there is a lot of things to sort out.

No problem. When you've finished, just let us know. Luck with your career change.

**Comment by Feyn-Man** [comment]
Hi guys, I'll not be ready too for the 4th. I'll continue to push anyway :bowtie:

**Comment by mgrojo** [comment]
@Feyn-Man Don't worry. Continue working on it, since we aren't yet ready for the release. There are some pending problems that we'd like to solve before releasing.

**Comment by justinclift** [comment]
> There are some pending problems that we'd like to solve before releasing.

Yeah, we're trying to update the Qt + SQLCipher versions we're using as well.  The updated Qt version mostly works, but the update for SQLCipher is taking a bit longer to figure out than we'd like. :frowning:

**Comment by SafaAlfulaij** [comment]
@mgrojo Thanks a lot!
I've completed most of the strings. The SQL command help is not done, because I felt I was really lost :D

[sqlb_ar_SA.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/2550214/sqlb_ar_SA.zip)

**Comment by mgrojo** [comment]
@SafaAlfulaij It looks pretty nice now. This is from the compilation log:

```
  Updating '/home/mgr/src/sqlitebrowser/src/translations/sqlb_ar_SA.qm'...
    Generated 990 translation(s) (990 finished and 0 unfinished)
    Ignored 7 untranslated source text(s)

```
Well, I reproduce the parenthesis problem from #667, but I hope it looks correct for newer Qt versions:

![imagen](https://user-images.githubusercontent.com/13812910/48022760-4b27ff80-e13c-11e8-8192-049587c7656e.png)

It's already in the master and v3.11.x branches. Thanks!

**Comment by mgrojo** [comment]
There are two new messages in the release branch due to issue #1588 as a workaround for the crash in #1311, which we haven't been able to fix. The translation files are already updated in the v3.11.x branch. 

Example of the change:
```diff
------------------------ src/translations/sqlb_ar_SA.ts ------------------------
index 087aa55..6333ccf 100644
@@ -173,7 +173,12 @@
         <translation>  -t, --table [جدول]‎	تصفّح الجدول المذكور بعد فتح قاعدة البيانات</translation>
     </message>
     <message>
-        <location filename="../Application.cpp" line="97"/>
+        <location filename="../Application.cpp" line="93"/>
+        <source>  -o, --option [group/setting=value]	Run application with this setting temporarily set to value</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../Application.cpp" line="98"/>
         <source>This is DB Browser for SQLite version %1.</source>
         <translation>هذا «متصفّح قواعد بيانات» للإصدارة %L1 من SQLite.</translation>
     </message>
@@ -217,7 +222,12 @@
         <translation>يتطلّب الخيار ‎-t/--table معطًى</translation>
     </message>
     <message>
-        <location filename="../Application.cpp" line="121"/>
+        <location filename="../Application.cpp" line="118"/>
+        <source>The -o/--option option requires an argument in the form group/setting=value</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../Application.cpp" line="138"/>
         <source>Invalid option/non-existant file: %1</source>
         <translation>خيار غير صالح/ملف غير موجود: %L1</translation>
     </message>
```

**Comment by FriedrichFroebel** [comment]
@mgrojo As it is easier for me with only two translations to be done, here are the German strings for it:

```xml
<message>
    <location filename="../Application.cpp" line="93"/>
    <source>  -o, --option [group/setting=value]	Run application with this setting temporarily set to value</source>
    <translation>  -o, --option [Gruppe/Einstellung=Wert]	Anwendung mit einem temporär gesetzten Wert für eine Einstellung ausführen</translation>
</message>

<message>
    <location filename="../Application.cpp" line="118"/>
    <source>The -o/--option option requires an argument in the form group/setting=value</source>
    <translation>The Option -o/--option benötigt ein Argument in der Form Gruppe/Einstellung=Wert</translation>
</message>
```

**Comment by SafaAlfulaij** [comment]
Arabic:

```xml
<message>
    <location filename="../Application.cpp" line="93"/>
    <source>  -o, --option [group/setting=value]	Run application with this setting temporarily set to value</source>
    <translation>  -o, --option [group/setting=value]	‫شغّل التطبيقات بهذا الإعداد المضبوط مبدئيا على القيمة value</translation>
</message>

<message>
    <location filename="../Application.cpp" line="118"/>
    <source>The -o/--option option requires an argument in the form group/setting=value</source>
    <translation>‫يتطلّب الخيار ‎-o/--option معطًى بصيغة group/setting=value</translation>
</message>
```

Nevermind the change of xml tags location, they are correct logically.

**Comment by MKleusberg** [comment]
@chrisjlocke I guess this doesn't just happen in the Preferences dialog but in all dialogs, right? There are in fact two translation files for each language: one provided by Qt for some standard strings and one provided by us for our strings. Looks like the Qt translation file isn't included in the binary or isn't loaded properly.

**Comment by MKleusberg** [comment]
The untranslated ```INTEGER``` is correct. That's a value which goes into the database and which is interpreted by SQLite, so it's more like a keyword than an UI-only string.

**Comment by mvt91** [comment]
Hi Chris,

Thanks,

I'll have a look but Préférence Dialog is not a new feature...

Best regards

----- Mail d'origine -----
De: Chris Locke <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Thu, 15 Nov 2018 14:27:23 +0100 (CET)
Objet: Re: [sqlitebrowser/sqlitebrowser] Translations for the next release wanted (#1567)

This is going to get lost in here, but noticed a possible 'quirk' in the nightly .exe when I changed language to try something.

![image](https://user-images.githubusercontent.com/7872218/48555769-0f2e3080-e8da-11e8-90d7-c63fe45c0e8e.png)

'Restore Defaults', 'Save' and 'Cancel' in the 'Preferences' dialog don't seem to have translations.

**Comment by mgrojo** [comment]
There are some minor changes or additions in UI strings in the v3.11.x branch due to including support for new version of SQLCipher and other issues. The translation files are already updated in the release branch and the changes can be seen in 66172ace8e7e19a1f3209c96bb67e7ac99c67f31 (together with simple source code lines changes). Spanish translation is already updated.

Please provide an update if you want the next release to be completely translated and sorry for the inconvenience.

**Comment by mgrojo** [comment]
@ngosang has [recommended](https://github.com/sqlitebrowser/sqlitebrowser/issues/1696#issuecomment-455856298) us using https://www.transifex.com/ for the translation process. Has anyone of the translators following this thread used it? Do you think it would be helpful for future translations?

**Comment by justinclift** [comment]
Hmmm, if we're wanting to use a web based platform we could use Canonical's Launchpad based one.

From memory, Transifex started out as an OSS project... then went commercial only, burning their Community to the ground?

Hmmm, I maybe mis-remembering that.  Looking at their pricing page, there doesn't seem to be any mention of OSS stuff, nor discounts for OSS projects.

Actually, doing some digging found this:

&nbsp; &nbsp; https://github.com/transifex/transifex

With it's one-liner description as:

> Older, open-source codebase of Transifex.com

So yeah, they seem to have started out at OSS then abandoned their roots.  Personally, not really wanting to use any kind of solution that pulls that crap. :wink:

**Comment by justinclift** [comment]
The 3.11.0 release is out, so closing this. :smile:
