### ISSUE TITLE
Upgrade SQLite engine / use sqlite3.dll

### ISSUE THREAD

**Issue by fdcastel** [sqlitebrowser/sqlitebrowser#1570]
Describe the new feature
--------------------------

Even using the latest alpha version, the SQLite engine used by DB4S is somewhat outdated. Running

```
select sqlite_version();
```

returns

```
3.15.2
```

which, according [SQLite changelog](https://www.sqlite.org/changes.html), is almost **2 years** old.

Latest SQLite versions have several improvements both in performance and features (e.g. [window functions](https://www.sqlite.org/windowfunctions.html)).

So, **could you please release a version with a updated engine version**?

Better yet: **Could you just use `sqlite3.dll` instead of embedding SQLite in the .exe?**

To the best of my understanding, to upgrade SQLite engine currently requires a full rebuild from sources (which is not an option for most users). Using `sqlite3.dll` would allow to anyone simple replace the .dll to the version needed. 

*(I tried to copy a newer `sqlite.dll` version into the same folder containing `DB Browser for SQLite.exe` but it wasn't used.)*

**Comment by justinclift** [comment]
Yeah, the actual 3.11 release will have a newer SQLite included.  That one you're seeing is the version from SQLCipher, which is another component we need updating for the release.

If you need a version of DB4S with newer SQLite, use the DB4S nightly builds **without** encryption.  Those use standard SQLite, and it's generally the latest released version:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by fdcastel** [comment]
Perfect! Thank you very much @justinclift !!

**Comment by mpr0st** [comment]
+1 to using sqlite3.dll instead of embedding SQLite in the .exe, I've had to stop using the portableapps version of DB4S for a project just because I'm unable to use the new unixepoch() function with it.

BTW, the nightly builds for Windows appear to be corrupted (22 bytes):

> [* README.txt](https://nightlies.sqlitebrowser.org/latest/%2A%20README.txt)                                       16-Jan-2019 19:58                1635
> [DB.Browser.for.SQLite-sqlcipher.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg)                29-Jul-2022 03:56            18184803
> [DB.Browser.for.SQLite-win32.zip](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip)                    25-Jul-2022 04:03                  22
> [DB.Browser.for.SQLite-win64.zip](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip)                    29-Jul-2022 15:58                  22
> [DB.Browser.for.SQLite.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite.dmg)                          29-Jul-2022 03:56             1867911

Thank you.

**Comment by justinclift** [comment]
> BTW, the nightly builds for Windows appear to be corrupted (22 bytes)

Yeah, we're working on it.  Turns out it's not a simple fix, so it's taking some time. :wink:
