### ISSUE TITLE
No Nightlies for 15 Oct

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1572]
There appears to be no nightlies for this morning.  Last nightlies were for 14 Oct at 04:30.

Details for the issue
--------------------

#### What did you do?
Sat at my desk.  Started to drink some coffee.

#### What did you expect to see?
A fairy.

#### What did you see instead?
Two frogs and a giraffe.  I must stop drinking coffee.

Useful extra information
-------------------------
Badgers don't see in the dark.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha*
- [ ] 3.10.1
- [x] Other: _3.11.1.1.1.1.1.1.1.1111.11.1111__

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
- [x] Bash the keyboard furiously until something happened.

**Comment by justinclift** [comment]
Heh Heh Heh

Oops, yeah.  I needed the international travel adaptor that the build server is using for some other stuff, so grabbed that "temporarily"... then completely forgot to plug in the build server again when I was done.

I've just plugged in the build server again and booted it.  The nightlies should be in place on time tomorrow. :wink:

**Comment by chrisjlocke** [comment]
This is why I don't let you look after my nan who's on kidney dialysis .... you'd just unplug her machine to recharge your mobile! ;)

**Comment by justinclift** [comment]
Hmmm.... kidney vs mobile... yeah, tough call. :wink:

**Comment by chrisjlocke** [comment]
Closing as the nightlies are back.  They're back!!!
