### ISSUE TITLE
Loading Project Uses Filter Setting But Does Not Show It

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1573]
When you load a project file, the filters (if any) you defined are used, but are not displayed.

Details for the issue
--------------------

#### What did you do?
Open a project file

#### What did you expect to see?
The filters preserved

#### What did you see instead?
An empty set of filter boxes

Useful extra information
-------------------------

Screenshot of the filter before saving:
![image](https://user-images.githubusercontent.com/7872218/46948677-cd119500-d076-11e8-8322-9f68a33949d4.png)

And this is after loading the project
![image](https://user-images.githubusercontent.com/7872218/46948721-edd9ea80-d076-11e8-8bc4-62725554cfbf.png)

So the filter is still being preserved (ie, showing just the records that match ELE041) but the user is not aware of why...

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.99 (14 Oct 2018)
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Yes, I noticed this too and opened #1222, but there were other problems too, that are now solved.

I prefer your issue, since mine is partly solved and too broad. And yours includes pictures :smile: So I'll close #1222.

**Comment by justinclift** [comment]
Pictures are good. :grin:

**Comment by chrisjlocke** [comment]
Aah, didn't spot your previous issue.  At least you found a workaround! ;)  The plot information is useful too, as I can add that to the project wiki page I added yesterday.

**Comment by mgrojo** [comment]
Hi @chrisjlocke, this should be solved in tomorrow's nightly. Could you confirm it also works for you?

**Comment by MKleusberg** [comment]
Let's just assume it's working :innocent: If this is still happening after all, please just re-open the issue, @chrisjlocke :smile:
