### ISSUE TITLE
How do I let DB4S use my icu sqlite version ?

### ISSUE THREAD

**Issue by qiulang** [sqlitebrowser/sqlitebrowser#1576]
What is your question
-----------------------
I built an icu sqlite version, how do I let DB4S use my sqlite version instead?  I only find one related article https://github.com/sqlitebrowser/sqlitebrowser/wiki/Compiling-DB4S-on-Ubuntu-To-Use-A-Pre-Installed-Version-of-SQLite 

But is rebuild DB4S the only way to do it ?

Thanks
Qiulang

**Comment by chrisjlocke** [comment]
I'll close this as it 'seems' resolved.
@qiulang - feel free to reopen or comment further if you have further issues regarding this.
