### ISSUE TITLE
How can I stop Capitalization of letters?

### ISSUE THREAD

**Issue by angelosg333** [sqlitebrowser/sqlitebrowser#1578]
I want to edit the texts in this sqlite file but it keeps capitalize some texts. 
[https://drive.google.com/open?id=1unyB0wpDmhgjHkdA1W5xK3RBiB6WPIR4](url)
How can I stop this?
Thanks in advance!

**Comment by chrisjlocke** [comment]
I'm not aware that DB4S (DB Browser for SQLite) capitalizes any text.  Is this through the 'Edit Database Cell'  pane?

**Comment by angelosg333** [comment]
I'm sorry! This was misunderstanding of mine. It seems that it's the
Android app (which uses this sqlite file) that capitalizes the texts. So I
guess you can't help me with this.
Thanks for your respond anyway!

Στις Πέμ, 18 Οκτ 2018, 10:06 μ.μ. ο χρήστης Chris Locke <
notifications@github.com> έγραψε:

**Comment by justinclift** [comment]
No worries at all @angelosg333, good luck with your project. :smile:
