### ISSUE TITLE
Filtering does not work for me

### ISSUE THREAD

**Issue by carbonmetrics** [sqlitebrowser/sqlitebrowser#1583]
I am trying out sqlitebrowser, and attempting to filter as set out in here: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters.
It does not work for me.

Details for the issue
--------------------

#### What did you do?
Imported a database from a tab delimited file successfully, including header names. Clicked on the filter, typed keyword at the cursor.

#### What did you expect to see?

A filtered database.

#### What did you see instead?

The database is not filtered.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ x] Linux: ( _distro:_Xubuntu ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
Hello and thanks for reporting this.

We need some more information to able to help you resolve this issue. What is your application version? What filter did you use? Please note that some filters maybe not be available if you are not using a recent version of the application.

**Comment by mgrojo** [comment]
@carbonmetrics Additionally, a copy of the executed statements by the application taken from the SQL Log  would be also useful. The SQL Log is one of the the right panes. Press Ctrl+L if it is not currently visible. You have to select Application in the combobox.

**Comment by MKleusberg** [comment]
I will close this issue then as it seems like it was solved by restarting the computer. If you should stumble upon the same issue again, you are always welcome to reopen this issue, @carbonmetrics :smile:
