### ISSUE TITLE
a checkbox option in "Import CSV file" menu to Import unique entries only

### ISSUE THREAD

**Issue by antonybits** [sqlitebrowser/sqlitebrowser#1585]
Hi, i import many new csv files into my database every few days, and after importing entries i have to remove repeated rows (using DISTINCT or GROUP BY on multiple columns).
Fortunately "Import CSV file" menu can repeat the import process for all new csv files, i hope if it could import non-repeated rows based on multiple columns.
refer to the picture which illustrate my goal: left side shows the current menu and the right side represents what i wish.
![picture2](https://user-images.githubusercontent.com/42927785/47263859-06cf1980-d517-11e8-8cea-46094088a67f.png)

**Comment by chrisjlocke** [comment]
Can't you create an index on a column that you don't want duplicated with a UNIQUE constraint?

**Comment by antonybits** [comment]
there is not a column that i don't want duplicated , its a row i don't want to, just like DISTINCT or GROUP BY on multiple columns
the combination of lac,cell.lat,lon should be uniqe but each "lat" can be duplicated (same for lac,cell.lat,lon)
each cell may be repeated but the combination should not, in other word this is unique `lac||cell||lat||lon` not each one of them
(keeping in mind that importing a csv table with N  columns (e.g, N=5) into a database's table with M  columns (e.g, M=6) is not permitted and returns error)

**Comment by chrisjlocke** [comment]
You can create an index on multiple columns.

> importing a csv table with N columns (e.g, N=5) into a database's table with M columns (e.g, M=6) is not permitted

Not *entirely* true.  Import into a new table, then do an 'insert ... select ....'* query.  Bit messy, and long winded, but seems to work.

    *insert into old_table (field1,field3,field5) select * from table_imported

**Comment by antonybits** [comment]
> 
> 
> You can create an index on multiple columns.
> 
> > importing a csv table with N columns (e.g, N=5) into a database's table with M columns (e.g, M=6) is not permitted
> 
> Not _entirely_ true. Import into a new table, then do an 'insert ... select ....'* query. Bit messy, and long winded, but seems to work.
> 
> ```
> *insert into old_table (field1,field3,field5) select * from table_imported
> ```

yes that's right but your answer is more about executing SQLs, than creating easy access through GUI into database, so isn't That off the scope of the enhancement feature requests  ?

**Comment by chrisjlocke** [comment]
This does actually raise an interesting error (and not the one you have screenshotted).
We're currently looking at this part of the program, so have raised this as a separate issue.

**Comment by antonybits** [comment]
this procedure create different errors (I don't know why) for different databases , testing the same procedure  in my laptop resulted into the error mentioned in #1590  
![capture3](https://user-images.githubusercontent.com/42927785/47414571-22882900-d77e-11e8-9927-c3eb55dd262e.JPG)

**Comment by chrisjlocke** [comment]
Hopefully (in the latest nightly build) that particular error has been squished.  Your previous issue may remain however - will test later today...

**Comment by antonybits** [comment]
just tested the latest nightly build! #1591 
Now I get this error which is probably a rational massage, at least 
![capture5](https://user-images.githubusercontent.com/42927785/47422735-38064e80-d790-11e8-9b10-21ee9f9e9202.JPG)

**Comment by chrisjlocke** [comment]
Yes, have just tested, and the right error is now displayed.  However, the import still terminates when an error occurs, which isn't ideal (but expected).  It would be nice if DB4S could continue, but that would depend on the error occurred, and would also throw up a lot of dialog boxes.  

In the short term, as you're on Windows, I could build a .Net application which could look in a table and move across records which are unique.  So import into a new table, then my program would look in this new table.  Yell if that could help.

**Comment by MKleusberg** [comment]
@antonybits That's a really good idea! :+1: I have just added a new option for that. It is hidden behind the 'Advanced' button in the Import CSV dialog and is called 'Conflict strategy'. That's of course still not equivalent to a simple 'Unique entries only' checkbox as you suggested but should make it easy enough to simulate that behaviour by adding a unique constraint for all columns as you mentioned. So in the next nightly build you should be able to:

1. Create your table like this
```sql
CREATE TABLE name(a INT, b INT, c INT, UNIQUE(a,b,c));   -- List all columns in the UNIQUE constraint here
```
2. Then open the Import CSV dialog like before
3. Click the Advanced button
4. Select your ON CONFLICT strategy there

Do you want to give that a try tomorrow or so? :smile:

**Comment by antonybits** [comment]
hi, sorry  for the delay,  It took a while to finish my tests, the results were completely fine,
i had to rebuild my database from scratches. (that's because just could not add the highlighted line to the older table)
![untitled](https://user-images.githubusercontent.com/42927785/47952400-f17cd500-df83-11e8-8c7e-15f3f776be9f.png)
the "ON CONFLICT strategy" was great, i can say there is no need for the users to have #1585 "a checkbox option in "Import CSV file" menu to Import unique entries only" but i hope we had a "partial clause" illustrated in the example artificial pic below so we could set the unique constraint on multiple columns. ( or any other way to make that possible for the users other than executing SQLs)
![untitled2](https://user-images.githubusercontent.com/42927785/47952522-09edef00-df86-11e8-8d8a-6c0a12bacf27.png)

**Comment by chrisjlocke** [comment]
Thanks @antonybits .  Will close this issue as its semi resolved, but if you have any further issues, feel free to comment further or re-open it.
