### ISSUE TITLE
Command Line Switch To Disable Version Check

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1588]
Describe the new feature
--------------------------
In relation to #1560 
If a command line switch could be provided, then the version update check could be ignored.
Depending on the OS, the application has to start to get into the options to disable the option ... this isn't possible if the application crashes when the application starts.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
Yes. #1560 

#### Does this feature exist in another product or project? Please provide a link.
Other applications have a 'safe mode' switch.  Various plugins/checks are turned off.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
n/a

**Comment by justinclift** [comment]
Good idea.  We should do this.  Preferably in 3.11.0, if someone has a chance to add suitable code. :smile:

**Comment by mgrojo** [comment]
What about generalising this to any setting?:
                
`-o, --option [group/setting=value]    Run application with this setting temporarily set to value`

**Comment by mgrojo** [comment]
I'm working on that.

**Comment by mgrojo** [comment]
I've committed to master the new option as I described in my previous comment. The setting is not saved unless user enters Preferences and presses Save. This is useful also for testing with some value and then through it away. I've tested with integer, string, boolean, font, colour values and it's working for me in every case, except for the language, which is initialised before reading the command line and consequently, the setting is correctly set, but not applied in the session. I think this glitch can be tolerated.

For #1311 and (hypothetically) #1560 users can run with this option and then use Preferences > Save:

`sqlitebrowser -o checkversion/enabled=false`

Several options can be concatenated for getting a profile completely different to your saved preferences.

`./sqlitebrowser -o databrowser/null_bg_colour=pink -o editor/font=Utopia -o editor/wrap_lines=0 -o remote/active=false `

That opens the door to having several desktop shortcuts with different profiles.

If this works well in tomorrow's nightly, I think it can be cherry-picked to the v3.11.x branch. It would need new translations for two strings related to the command line usage, though.

**Comment by justinclift** [comment]
Sounds like a smart approach @mgrojo. :smile:

**Comment by MKleusberg** [comment]
Should we close this issue then? :smile:

**Comment by chrisjlocke** [comment]
Closing due to the masterful @mgrojo doing his coding skillzzzzzzzz.

**Comment by mgrojo** [comment]
There is a pending decision about whether this should be added to the v3.11.x branch for working around #1311. I think it's safe enough; the code is very simple indeed (so totally undeserved compliments, by the way :wink: but thanks). The only drawback is that there will be two new strings to translate (only in the command-line interface which at least is not very visible if some translator is not able to update them for the release).

**Comment by justinclift** [comment]
Might as well add it to the 3.11 branch.  I should have time to get an alpha2 release created either friday or this weekend.  If I don't have the SQLCipher bits worked out by then, then alpha2 can be with standard SQLite until until I do have SQLCipher working.  That'll still give people something newer to test. :smile:

**Comment by MKleusberg** [comment]
I agree - no reason to not add this to 3.11 :smile:

**Comment by mgrojo** [comment]
Ok. Added to v3.11.x and translation files updated with the new messages.
