### ISSUE TITLE
No Nightlies for 24 Oct

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1591]
Details for the issue
--------------------
It appears there are no Windows nightlies for 24 Oct.  Mac nightlies seem OK.
I bet @justinclift [nicked the travel adaptor](https://github.com/sqlitebrowser/sqlitebrowser/issues/1572#issuecomment-429774629) again.... 😉 

![image](https://user-images.githubusercontent.com/7872218/47416982-d2ee3100-d76e-11e8-97a8-9aca1909e92e.png)

#### What did you do?
Browsed to the nightlies page

#### What did you expect to see?
Nightlies

#### What did you see instead?
Nighties.  It was a scary sight.

Useful extra information
-------------------------
Croatia, officially the Republic of Croatia is a country at the crossroads of Central and Southeast Europe, on the Adriatic Sea. Its capital Zagreb forms one of the country's primary subdivisions, along with twenty counties.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Actually, yes. :wink:

Plugged it back in this time, but too late for the job to get started automatically.

I'll kick off the Windows nightly build script again now. :smile:

**Comment by karim** [comment]
> ## Useful extra information
> 
> Croatia, officially the Republic of Croatia is a country at the crossroads of Central and Southeast Europe, on the Adriatic Sea. Its capital Zagreb forms one of the country's primary subdivisions, along with twenty counties.

Too bad we don't have `wikipedia` label. :smile:

**Comment by chrisjlocke** [comment]
I'll buy you a new adaptor!!

**Comment by justinclift** [comment]
> I'll buy you a new adaptor!!

Meh, it probably wouldn't get here for ages. :wink:

**Comment by antonybits** [comment]
was testing the latest nightly build for the error in #1590, but not working!
i didn't know how to explain the issue again! (English is my second language)
now I know how!!  I may ask whether the adapter was plugged in or borrowed "temporarily" 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f609.png)

**Comment by justinclift** [comment]
It was borrowed "temporarily". :wink:

**Comment by chrisjlocke** [comment]
Installed perfectly.  Thanks matey.  🔌

**Comment by justinclift** [comment]
Heh Heh Heh.  There's a power plug emoji even.  Awesome. :wink:
