### ISSUE TITLE
Do you have any plan to support SQLite4?

### ISSUE THREAD

**Issue by xxiongb** [sqlitebrowser/sqlitebrowser#1596]
Describe the new feature
--------------------------
The description of the SQLite4, please open the web URL. 
https://sqlite.org/src4/doc/trunk/www/index.wiki

**Comment by justinclift** [comment]
SQLite4 doesn't really seem like it's in active development.  Check the dates for the commits:

&nbsp; &nbsp; https://sqlite.org/src4/timeline

From what I remember, SQLite4 is an experimental thing to try stuff out on.  It may receive further development in future + become a viable project.  If that happens, then we'd look at supporting it.

For now though, it's not likely to be a useful thing to put time into. :smile:

**Comment by justinclift** [comment]
It's README has further useful info too:

> This directory contains source code to an experimental "version 4" of SQLite that was being developed between 2012 and 2014.
> 
> 
>  **All development work on SQLite4 has ended.  The experiment has concluded.**
> 
> Lessons learned from SQLite4 have been folded into SQLite3 which continues to be actively 
>  maintained and developed.  This repository exists as an historical record.
> 
>  **There are no plans at this time to resume development of SQLite4.**
