### ISSUE TITLE
readonly mode in project

### ISSUE THREAD

**Issue by hiropfffff** [sqlitebrowser/sqlitebrowser#1598]
Can I save the state opened in readonly mode in a project file?

I tried it, but it seems I can not do it

**Comment by justinclift** [comment]
Good question.  We've recently been adjusting the project file format on disk, so if it's not something we already keep track of then it's probably good timing to consider it. :smile:

**Comment by MKleusberg** [comment]
Welcome, @hiropfffff, and thank you for the suggestion! :smile: I have just added a read-only flag to the project files. I'm not sure when the next nightly build with the new code will be available but I hope it's going to be soon.

**Comment by justinclift** [comment]
New nightly builds for windows are online now.  OSX ones should be there in ~2 hours too:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by hiropfffff** [comment]
Thank you!
I used nightly build.
No problem.
I hope that ver3.12.0 will be released as soon as possible

**Comment by MKleusberg** [comment]
Awesome, thanks for testing @hiropfffff :+1:
