### ISSUE TITLE
Importing CSV with numeric data

### ISSUE THREAD

**Issue by rallyRays** [sqlitebrowser/sqlitebrowser#160]
Hi there,

When I import data from a CVS file (exported from excel), one of the columns in the database is a numeric hexColor. some of those hexColors are "000000"(or black), and they are imported as "0" into SQL.Another issue is the hexColor "314659" is imported as "5.57e+92".

ATTACHED IMAGE EXPLANATION:

original data from excel:
srays_Excel_screenshot.PNG

exported CVS data:
srays_CVS_screenshot.PNG

imported values in SQLite:
srays_SQLite_screenshot.PNG

Thanks!
Scott

![srays_excel_screenshot](https://cloud.githubusercontent.com/assets/9259050/5159915/378ec0c4-733d-11e4-8dd8-daedcaa57938.PNG)
![srays_sqlite_screenshot](https://cloud.githubusercontent.com/assets/9259050/5159914/37898604-733d-11e4-8182-41447050087c.PNG)
![srays_cvs_screenshot](https://cloud.githubusercontent.com/assets/9259050/5159916/378fa020-733d-11e4-95c3-b7981baa8fd4.PNG)

**Comment by justinclift** [comment]
@rallyRays Looking back through our older issues atm.  Did putting quotation marks around the hex numbers get it to work? (wondering if it did, and if this issue can be closed :wink:)

**Comment by rallyRays** [comment]
Hey Justin,

 

This issue was discovered when I tried to remove the hexColors alpha values from, so “FF01273C” to “01273C”. I ended up going back to the hexColor with the alpha “FF” values.

 

Cheers,

Scott

**Comment by justinclift** [comment]
Yeah, that sounds like a workable approach.  Closing this issue for now.  If you reckon it's worth opening again for further investigation, feel free to. :smile:

**Comment by silviulaurentiu** [comment]
I have tried to import a CSV file and one field have 0805 number inside. The preview looks ok:
![image](https://user-images.githubusercontent.com/14875058/50004707-b45b2800-ffb0-11e8-8ace-48137d9a633b.png)
but in Browse Data table, the zero "0" was removed from the front of the number and the result is this:
![image](https://user-images.githubusercontent.com/14875058/50004788-ea001100-ffb0-11e8-9c7c-8c3b756cf296.png)

**Comment by silviulaurentiu** [comment]
Good news, it works if this check button is checked:
![image](https://user-images.githubusercontent.com/14875058/50005441-fedda400-ffb2-11e8-9060-d8d42608b1c7.png)

**Comment by justinclift** [comment]
Ahhh yeah.  We added that button exactly to solve this kind of problem. :smile:
