### ISSUE TITLE
string " " -> QString("")

### ISSUE THREAD

**Issue by LETARTARE** [sqlitebrowser/sqlitebrowser#1603]
some complaints from the compiler
Edit

Details for the issue
--------------------

#### What did you do?
editDialog.cpp:L794 : bool modified = false;
mainwindow.cpp:L3117 : "=" -> QString("=")
sqlitetypes.cpp:L1162 : "" -> QString("") 

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( _version:_VISTA Businness ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha*
- [ ] 3.10.1
- [ x] Other: rev3755

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by LETARTARE** [comment]
La première ligne n'a pas été envoyée !!
svn3755
I used 'mingw530_32' and 'qt-5.9.6', IDE 'Code::Blocks-svn11508  with 'qtPregenForCB' plugin
Compilation is good.

**Comment by LETARTARE** [comment]
The first line was not sent !!

I used 'mingw530_32' and 'qt-5.9.6', IDE Code::Blocks-svn11508 with 'qtPregenForCB' plugin.
The compilation is qood

**Comment by justinclift** [comment]
Thanks @LETARTARE.

Not sure (yet) if this is useful, but it might turn out to be.  That's because you're mentioning "svn3755", which seems like a subversion thing, but we don't store our source code in subversion.

Where did the source code you're using come from?  Guessing it was our (very outdated) SourceForge project page? :smile:

As a possibly useful data point, the place to grab our source code is from here, using Git:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser

If you're not familiar with git, you can instead download our latest source code as a standard tarball from:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/archive/master.tar.gz

Does that help? :smile:

**Comment by LETARTARE** [comment]
@MKleusberg 
with rev3765 the changes you have made are satisfactory.
It remains an error in 'remoteModel.cpp:L256 
```
// return QString().setNum(size, 'f', 2).remove(".00") + " " + unit;
return QString().setNum(size, 'f', 2).remove(".00").append(" ").append(unit); 
```

> Note:
>  I can not use 'Seamonkey-2.49.4' anymore under 'VISTA' ('Github' does not accept it any more), I use the same version but under 'OpenSuse-42.3'.
> This explains my first message because I could not edit it anymore.

**Comment by justinclift** [comment]
@LETARTARE Where are you grabbing our source code from?

**Comment by LETARTARE** [comment]
@justinclift
here : ' https://github.com/sqlitebrowser/sqlitebrowser.git' with 'TortoiseSvn.exe'  under 'VISTA Business'.

**Comment by justinclift** [comment]
@LETARTARE Thanks.  That's the correct place.

It seems like TortoiseSVN is using some strange way to access things, which gives the weird "rev3765" numbers.  That doesn't seem to be hurting anything though. :smile:

**Comment by MKleusberg** [comment]
Thanks, @LETARTARE! That other warning should be fixed as well now. Do you get any other warnings or was this the last one? :smile:

**Comment by justinclift** [comment]
@LETARTARE Have you had a chance to check this? :smile:

**Comment by justinclift** [comment]
Hmmm, reading that line, I'm not personally understanding what the incorrect piece is.  I can see the difference between the two lines... I'm just not sure why the current one is "wrong". :smile:

What is the error message being given for it?

**Comment by LETARTARE** [comment]
Vista Business sp2,
compiler : 
> g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
> Copyright (C) 2015 Free Software Foundation, Inc.

error :

> U:\Donnees\TRAVAIL_NT\CodeBlock\Gcc\Qt\Autres\BaseDeDonnees\BrowserSqlite\4304\src\RemoteModel.cpp: In member function 'virtual QVariant RemoteModel::data(const QModelIndex&, int) const':
> U:\Donnees\TRAVAIL_NT\CodeBlock\Gcc\Qt\Autres\BaseDeDonnees\BrowserSqlite\4304\src\RemoteModel.cpp:246:84: error: could not convert 'operator+<QStringBuilder<QString, QString>, QString>(operator+(const A&, const B&) [with A = QString; B = QString; typename QConcatenable<B>::type = QString; typename QConcatenable<T>::type = QString](QString(((const char*)" "))), unit)' from 'QStringBuilder<QStringBuilder<QString, QString>, QString>' to 'QVariant'
>                  return QString().setNum(size, 'f', 2).remove(".00") + QString(" ") + unit;
>                                                                                     ^

**Comment by MKleusberg** [comment]
I think we have fixed the lines in question here and we definitely haven't heard of any compilation errors regarding them in a long time. So I'll go ahead and assume this is fixed. But always feel free to reopen this issue if you still see any remaining problems here!
