### ISSUE TITLE
Where are '*.qm' translation files.

### ISSUE THREAD

**Issue by LETARTARE** [sqlitebrowser/sqlitebrowser#1605]
What is your question
-----------------------
When installing the "win32" binary I can not find the '* .qm' translation files.
Where are they installed ?

**Comment by justinclift** [comment]
Hmmm, in theory they should be installed in the same folder structure as the rest of the application.  If that's not working though, then it's probably a bug in the installer.  We'll need to fix that.

Just to check things first, which win32 download binary is this happening with?  One of our nightly builds, or a release, or something else?

**Comment by MKleusberg** [comment]
I guess this is a fair question. I don't know about the Windows installer but looking at the CMakeLists.txt file it explicitly includes, besides the DB4S binary and some DLLs, the license file and the batch file for starting the application. No mention of the translations though. But again, I don't know anything about the Windows installer creation. @karim maybe? :smile:

**Comment by chrisjlocke** [comment]
What do you require the *.qm files for?  They're not needed for normal application use, so I wouldn't have expected them to be part of the binary.  Source files, maybe, but not the binary...

**Comment by MKleusberg** [comment]
They contain the translations, so you need them for using DB4S in other languages than English. However, it's also possible to compile them into the binary file as a resource. In this case we indeed don't need the files - but I have no idea if we do that :wink:

**Comment by chrisjlocke** [comment]
I can change languages fine...
![image](https://user-images.githubusercontent.com/7872218/48556193-2e798d80-e8db-11e8-90f9-7fd40579face.png)

(this is using the Windows nightly, so no *.qm files anywhere...)

**Comment by MKleusberg** [comment]
Ok, then they aren't needed indeed :wink: And the answer to the original question raised in this issue would be that they are inside the resource section of the binary.

**Comment by chrisjlocke** [comment]
I'll close this issue then, to make way for new ones.... ;)
@LETARTARE - Hope this is satisfactory, but feel free to reopen or comment further if you have more concerns on this.

**Comment by karim** [comment]
> However, it's also possible to compile them into the binary file as a resource. In this case we indeed don't need the files - but I have no idea if we do that :wink: 

Yes, we do that. :smiley: 

https://github.com/sqlitebrowser/sqlitebrowser/blob/f262bf6b18803cd6cdaf93dd89deaf3a2c8d9b6c/CMakeLists.txt#L284-L291

**Comment by karim** [comment]
I think the order is like this..

1. Add translation files

https://github.com/sqlitebrowser/sqlitebrowser/blob/37a5645bf5757fe296c1c5510c6db314e215d3b9/CMakeLists.txt#L235-L251

2. Send the files to the resource compiler (RCC)

https://github.com/sqlitebrowser/sqlitebrowser/blob/f262bf6b18803cd6cdaf93dd89deaf3a2c8d9b6c/CMakeLists.txt#L284-L291

3. Add them to the final executable

https://github.com/sqlitebrowser/sqlitebrowser/blob/f262bf6b18803cd6cdaf93dd89deaf3a2c8d9b6c/CMakeLists.txt#L362-L368
