### ISSUE TITLE
Browse Data filter

### ISSUE THREAD

**Issue by selster** [sqlitebrowser/sqlitebrowser#1607]
What is your question
-----------------------

**Comment by selster** [comment]
In Browse Data, the filters work fine for columns that have data; but if I am looking for rows that have blank data, it does not seem to work, the equilavent of: select * from <table. where field_name = ''.  I tried putting in "space" in the filter but that didn't work.  Thanks, Steve

**Comment by karim** [comment]
Hello Steve,

Did you try using `=''` (2x single quotes) as a filter?

You can also right-click on a column with a value you want to use as a filter and select *Use as Exact Filter*.

![1607](https://user-images.githubusercontent.com/8761081/48315753-e4469280-e5e2-11e8-9662-3851fab0dc2e.jpg)

**Comment by selster** [comment]
Neither work and my right-click menu does not have all of the options that yours does?  I am using the newest windows binary, is there a more recent version that would have the above options?

**Comment by karim** [comment]
Sorry, I forgot to ask you which version are you using. :smiley: 

We are getting ready to release 3.11 soon. You can test the alpha version from here https://github.com/sqlitebrowser/sqlitebrowser/releases. Also you can always get the latest nightly version from here https://nightlies.sqlitebrowser.org/latest/.

**Comment by selster** [comment]
Neither work and my right-click menu does not have all of the options that yours does?  I am using the newest windows binary, is there a more recent version that would have the above options?

**Comment by selster** [comment]
will test both now, thanks

**Comment by selster** [comment]
I downloaded and have run the one from https://github.com/sqlitebrowser/sqlitebrowser/releases.  A right click brings up the menu you describe and it inserts a ='' which I tried as =' ', neither bring up rows that are blank for the column.  Also, now, when I begin to type some letters in the filter for a column, there is a flash-screen-refresh after each  each letter and this flash is a little disconcerting, even though the filter works just fine.  Thank you, Steve

**Comment by selster** [comment]
tried the nightly version https://nightlies.sqlitebrowser.org/latest/ and it does filter for blank rows =''

Great.  The flashy stuff is still there after typing each letter

**Comment by selster** [comment]
note, when the above starts it says that there is a network error, the network is not accessible.

**Comment by chrisjlocke** [comment]
Thanks @selster - thats a known issue with the nightly as we're upgrading the Qt version in it (see #1595)
Simply click OK and turn off the nightly check, and all will be well again.

**Comment by mgrojo** [comment]
> Also, now, when I begin to type some letters in the filter for a column, there is a flash-screen-refresh after each each letter and this flash is a little disconcerting, even though the filter works just fine. 

Do you mean that the table cells get a pale red background and the text changes to "loading..."? Or only that the first column with the row numbers disappears and reappears? If it was just the later, it didn't happen with the previous version? The "loading..." cells are because of a prefetch mechanism when the table is big enough and it's a new feature for improving performance on big databases. You can avoid both effects if you set the "Filters - Delay time"  from "Edit > Preferences > Data Browser" to a greater value. You can also use the Return key for activating the filter if you have finished editing it,  so you don't have to wait.

**Comment by selster** [comment]
I am entering text in a filter for a column. I am typing one letter, after I type each letter, the entire table flashes, as the filter is applied for that letter. If I am trying to type flower, there will be six flashes. This is a little disconcerting. Am I explaining myself clear now? Thank you Steve




Get Outlook for Android







On Mon, Nov 12, 2018 at 1:07 PM -0800, "Manuel" <notifications@github.com> wrote:













Also, now, when I begin to type some letters in the filter for a column, there is a flash-screen-refresh after each each letter and this flash is a little disconcerting, even though the filter works just fine.



Do you mean that the table cells get a pale red background and the text changes to "loading..."? Or only that the first column with the row numbers disappears and reappears? If it was just the later, it didn't happen with the previous version? The "loading..." cells are because of a prefetch mechanism when the table is big enough and it's a new feature for improving performance on big databases. You can avoid both effects if you set the "Filters - Delay time"  from "Edit > Preferences > Data Browser" to a greater value. You can also use the Return key for activating the filter if you have finished editing it,  so you don't have to wait.

**Comment by chrisjlocke** [comment]
Just for info, how many rows in the table?  How many fields in the table?
Theoretically, there should be a 200 ms delay (or thereabouts) between each lookup.  You can increase this in Edit | Preferences.

![image](https://user-images.githubusercontent.com/7872218/48396693-38509480-e713-11e8-94a1-8c06f71c01cd.png)

I'd set it to 1000 (1 second) or even 750 (3/4 of a second).  See if that improves your experience.
I'll add a note of this option to the filters page on the Wiki...

**Comment by chrisjlocke** [comment]
@selster - *cough*
