### ISSUE TITLE
No nightlies (13 Nov)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1610]
Just a nod that there were no nightlies for last night (13 Nov).  I saw something somewhere that @justinclift  was doing something to the nightlies server, but as it worked OK for the 12 Nov, then .... well, thought I'd mention it.

**Comment by justinclift** [comment]
Yeah, I'm having to manually log into the server each day and kick them off.  Somewhere along the line Apple decided to outright never automatically connect to WiFi Hotspots from OSX, unlike every other OS manufacturer.  So, it's not possible for the Mac mini to maintain a network connection in it's new location without my logging into it each day and manually clicking a button.  Grrrr Apple. :frowning:

**Comment by justinclift** [comment]
Forgot to mention that since the only change to the source repo yesterday was the README tweak, I didn't bother getting them done today. :wink:

**Comment by chrisjlocke** [comment]
Aah, I see.  Sounds a pain.  You need a macro recorder thingy to do the keypresses for you.... ;)
