### ISSUE TITLE
Replace button in SQL Editor inserts text at cursor

### ISSUE THREAD

**Issue by mdro** [sqlitebrowser/sqlitebrowser#1612]
Details for the issue
--------------------

#### What did you do?
I tried to use find and replace in the SQL editor. I filled out the "Find text" and "Replace with" fields and pressed "Replace". 

#### What did you expect to see?
One of the following:

1. The button doesn't do anything or is disabled until I press "Find Next".
2. The first occurrance of the search term after the cursor gets selected, so it will be replaced on the next press of that button.
3. The first occurrance of the search term after the cursor gets replaced. Maybe the next occurrence after that gets selected.

#### What did you see instead?
The replacement text gets *inserted at the cursor position*, then the first occurrance is selected.
After that pressing the button works normaly (replace selected, select next). 

#### Related Feature Request
It would be nice if "Replace All" would be limited to the current selection in the file if there is a selection (like in e.g. Visual Studio).

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ Win 10 1804 )

#### What is your DB4S version?

- [x] 3.11.0-alpha*

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mdro** [comment]
This happened consistently on my work PC since I noticed it today. It didn't depend on the file, happened on a severeal hundred lines file as well as with a test string "abc".
I just tried it at home (Win 10 1804 as well) and it doesn't reproduce here directly. But I can move the cursor while the replace menu is open by clicking. If I do this and click Replace, the relacement text gets pasted at the cursor position (Visual Studio selects the next occurrence after the new cursor position in this case).
This second variant is of cause a smaller problem users won't normally hit. I will test on my Work PC again tomorrow.

**Comment by mdro** [comment]
I found out what happened at my work PC. The wrong insertion only happens if you had the replace or search dialogs for the same tab open before and an occurrance was selected when you closed it. This even happens if the search string changed or neither of the strings can be found in the text.

**Comment by justinclift** [comment]
@mdro Thanks, that's good info.  We should be able to investigate with that. :smile:

**Comment by mgrojo** [comment]
Thanks @mdro. Those steps helped a lot. What it's happening is that QScintilla (our editor widget library) is not resetting the search when the dialog is closed. The selection is cleared and this should reset it, in my opinion, but it doesn't. When a subsequent call to replace is done without a selection, the text is simply inserted. I'm going to work around that by checking whether there is a selection before calling to the replace method of the library. This seems to work well, except if you find something, close the dialog, select some text, open the replace dialog, write the new find and replace text fields and click Replace button. The user selected text is then replaced, although it might not match the find field. I think we can live with that glitch, but I've written to the QScintilla mailing list, just in case they consider it a bug or give a better solution.

Meanwhile I think I'll commit the workaround to the master branch.

**Comment by mgrojo** [comment]
> It would be nice if "Replace All" would be limited to the current selection in the file if there is a selection (like in e.g. Visual Studio).

Is that an option (a check box or something) or is it unconditionally done when there is a selection? I'm wondering if all users would expect that when there is a selection or it would be better with the check box.

**Comment by mgrojo** [comment]
Thanks for the information @mdro. We should open a new feature request for that.

Regarding the bug with the replace button. I received answer in the QScintilla mailing list and I hope that there aren't now any problems with the Replace button. It is now committed to the master branch. If you can test it and it works well also for you, we can include it in the v3.11.x branch.

@justinclift Will be there tonight a new nightly for testing this?

**Comment by justinclift** [comment]
@mgrojo Yep, there can be.  I'm getting in the habit of checking if there are changes to the master branch source, and if there are then I manually generate the builds when I have time through the day.

I'll start them now. :smile:

**Comment by mgrojo** [comment]
Great! I just committed a new feature (#1614). Maybe it hasn't passed the line. Next time then.

**Comment by justinclift** [comment]
The nightly build process hung anyway (my fault, oops), so am restarting it now.  The new feature should be picked up this time. :smile:

**Comment by mdro** [comment]
The fix works for me (2018-11-18 7:51, no cipher 64bit).

**Comment by justinclift** [comment]
Excellent!  Good stuff @mgrojo and thanks for the bug report + testing @mdro. :grinning:
