### ISSUE TITLE
Crashes if tablename (accidentally) starts with a space and using Browse Data

### ISSUE THREAD

**Issue by HDLcincDragon** [sqlitebrowser/sqlitebrowser#1616]
### Details for the issue

If a datatable's name starts with a space (An error when auto-generating table names) and viewing the database via DB4S' "Browse Data" tab, it crashes. Using the "Execute SQL" tab does not crash when querying the offending table (e.g. "SELECT * FROM [ oops]")

#### I'm opening this issue because:

- [X] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_Windows 7 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.0-alpha*
- [X] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Thanks for reporting this.
v3.10.1 is quite old now, and while I haven't tested it yet to confirm (I'll try later today), I'm confident the newer versions should work better.
https://github.com/sqlitebrowser/sqlitebrowser/releases

Try the 3.11 alpha, or one of the nightly builds, and see if that improves the situation.

**Comment by HDLcincDragon** [comment]
Hey Chris, I gave it a try and DB4S version 3.10.100 (Oct 10 2018) doesn't appear to have this issue.

- Rob
