### ISSUE TITLE
Question about Regex syntax in the Execute SQL find-replace panel

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1625]
What is your question
-----------------------
Hello  everyone,

I am currently testing the regular expressions pertaining to the Find and replace panel in the Execute SQL tab.
Most of them work fine but I am having troubles with the concatenation regex syntax.
I have just dowloaded today's build on Windows 10 (64 bit).

In short:
Whenever I concatenate two or more words together into the Browse Data filter everything works fine.
For instance:
/apple|pear/ --gives, as output in the filter column, both apple and pear.

On the contrary the same syntax does not yield any result in the Execute SQL tab.
IMHO, It looks fishy that the same syntax is different from the 2 tabs (Browse filter vs Execute SQL).
At first, I have suspected it was something related to the QT regex implementation but according to its documentation (http://doc.qt.io/archives/qt-4.8/qregexp.html) this | concatenation should work fine.

With Notepad++, Atom text editor and Sublime 3 everything is fine (apple|pear works OK).

Can someone shed some light on the correct syntax  and possibly point to the right documentation to delve into?

Thanks a lot in advance for any hint! 

See this screenshot:

![regex_concatenate png](https://user-images.githubusercontent.com/33007383/48978820-f7ad2f80-f0b1-11e8-80fa-42b28a327aa9.jpg)

**Comment by mgrojo** [comment]
We depend on two different implementations of regexp support for each case. The filter uses  the Qt implementation that you've linked. The find bar and the search/replace dialog uses the Scintilla implementation, which is simpler: https://www.scintilla.org/ScintillaDoc.html (look for SCFIND_REGEXP).

There is a flag in Scintilla which we still don't have with QScintilla (the Qt adaptation of the Scintilla API): SCFIND_CXX11REGEX. That would provide more features:

> When using SCFIND_CXX11REGEX more features are available, generally similar to regular expression support in JavaScript. See the documentation of your C++ runtime for details on what is supported. 

Support for SCFIND_CXX11REGEX has been requested in the QScintilla mailing list, but it is not currently available: https://www.riverbankcomputing.com/pipermail/qscintilla/2018-November/001346.html

We can leave this issue open and update to the CXX11 implementation when it is available in a new version of QScintilla.

**Comment by mgrojo** [comment]
Regarding the POSIX flag, which is only affecting to the syntax of the sub-expressions: currently `\( \)`, with POSIX would be simply `( )`. I think it's good idea to set this flag, since when CXX11 is available, syntax for sub-expression will be `( )`. 

References:
https://en.cppreference.com/w/cpp/regex/syntax_option_type
> If no grammar is chosen, ECMAScript is assumed to be selected.

https://en.cppreference.com/w/cpp/regex/ecmascript
> The Atom ( Disjunction ) is marked subexpression

Qt also uses subexpressions in the POSIX style.
http://doc.qt.io/qt-5/qregexp.html#capturing-parentheses

**Comment by mgrojo** [comment]
The POSIX flag is already committed, so the syntax for sub-expressions has changed from `\( \)` to `( )`. This is used in replacements for using a sub-expression (\n, where n is a number indicating the position of the sub-expression).

**Comment by mgrojo** [comment]
Hi @SilvioGrosso!

The next nightly build enables support of [extended regular expressions](https://en.cppreference.com/w/cpp/regex/ecmascript) as described above. This should be the same in all platforms, but it might depend on support of C++11 regex support in the compiler. Could you test in the Windows version and confirm it is working as expected?

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Thanks a lot for this last improvement.
I have just downloaed the 64 zip version (nightly) on Window 10 and everything looks fine

**Comment by mgrojo** [comment]
Great. Let's close this, then.
