### ISSUE TITLE
Cannot modify existing table (Specifically adding new field)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1627]
Details for the issue
--------------------
Added a new field, and DB4S moaned about "cannot find field8", and wouldn't allow the modifications to be saved.

#### What did you do?
Added a new field.

#### What did you expect to see?
The field added.

#### What did you see instead?
An error.

![image](https://user-images.githubusercontent.com/7872218/49016368-c8fc8b00-f17d-11e8-8d4a-0650cbc97262.png)

Useful extra information
-------------------------
Here is a screencast.
https://screencast-o-matic.com/watch/cFXOI2rF09

Adding a field and clicking OK (so not renaming the new field) seems to work.  Renaming the field then works.  
I'll try and find the nightly where this broke - I think it was fairly recently.  

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] Nightly from 26 Nov
- [ ] 3.11.0-alpha*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Added the 'release blocker' as it seems quite major.  Haven't checked to see if the Alpha is OK and this has just crept into the nightly... (doing that now)

**Comment by chrisjlocke** [comment]
15 Nov is fine, 16 Nov is bad.

**Comment by chrisjlocke** [comment]
I'm sure its linked, but you cannot delete multiple fields either.  Can't reproduce it though, as just tried again, and it worked.  Grr!

**Comment by mglatz** [comment]
@chrisjlocke can't it be related to foreign keys/triggers? Had the same issue before, solved (I think) by disabling FKs before modification.

**Comment by chrisjlocke** [comment]
The table has no foreign keys set or triggers.  Bit suspicious too the update I linked to was to do with the edit structure code ...

**Comment by justinclift** [comment]
@chrisjlocke That does seem like the right kind of commit. :smile:

**Comment by MKleusberg** [comment]
Yep, @chrisjlocke is right about the commit (and lighting the bat signal to me) :wink: 

It should be fixed now but it's worth playing around a bit more with the next version. The same problem was fixed in the delete field code, so that problem should be fixed as well, but again it's worth double checking. I'll also remove the release blocker label since this commit was never cherry-picked over to the v3.11.x branch and therefore doesn't interfere with our next release :smile:

**Comment by chrisjlocke** [comment]
Resolved.  Deleting multiple fields works OK too.  Thanks!

**Comment by MKleusberg** [comment]
Awesome, thanks for reporting! :smile:
