### ISSUE TITLE
Missing Q_OBJECT macro

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1628]
Noticed a minor error when running `lupdate` just now to refresh the strings for translation:

```
$ lupdate src/src.pro
Info: creating stash file /home/jc/git_repos/sqlitebrowser/.qmake.stash
/home/jc/git_repos/sqlitebrowser/src/AddRecordDialog.cpp:39: Class 'NullLineEdit' lacks Q_OBJECT macro
Updating 'src/translations/sqlb_ar_SA.ts'...
    Found 1019 source text(s) (32 new and 987 already existing)
    Kept 12 obsolete entries
Updating 'src/translations/sqlb_cs.ts'...
    Found 1019 source text(s) (32 new and 987 already existing)
    Kept 12 obsolete entries
Updating 'src/translations/sqlb_zh.ts'...
    Found 1019 source text(s) (32 new and 987 already existing)
...
```

That missing Q_OBJECT warning looks like something we should fix (it's [in the master branch](https://github.com/sqlitebrowser/sqlitebrowser/blob/5ae582355be8518c3321f931ff1530a799d9a35f/src/AddRecordDialog.cpp#L39)), though probably not urgent. :wink:

**Comment by MKleusberg** [comment]
Closing this since we have a new issue for this in #1740.
