### ISSUE TITLE
problem inserting row in table

### ISSUE THREAD

**Issue by moosemachineDK** [sqlitebrowser/sqlitebrowser#1633]
using python to collect data and insert into sqlite database.

insert fails on existing database but not if a new database is created (same python script).

Number of rows on existing database is below 3000. Columns below 10. 

was wondering if this could be a size issue but my understanding is that the defined limits in SQLite are reached at much higher levels. 

I'm a bit puzzled about this and don't really know where to start (assuming that this is a database issue as the script is running well on a new database).

**Comment by justinclift** [comment]
Ahhh.  It sounds like the import into an existing database might be hitting a "unique" or "not null" clause or similar.  eg perhaps one of the columns in the database has been defined in a way that some of the newly inserted rows are giving the error

Do you have the error message it's failing with at hand?  That'd help figure out what's wrong. :smile:

Also, which version of our application is this for?  If it's our new "3.11.0-beta1" release, then it might be some new bug we haven't seen yet too. (!) :wink:

**Comment by moosemachineDK** [comment]
Hi Justin, 

Thx for your response.  I'm using version 3.10.1 // Qt Version 5.7.1 // SQLCipher Version 3.15.2

I don't seem to be getting an error message (have looked under "SQL log"). I did note, however, that the script hadn't finished the last run it did before it crashed. 

The python script executes as it should. When I open the database the timestamp of the file itself has been updated ('Modified'). When I open the database the new data just isn't there / isn't visible. 

If I run the exact same script and feed the data into another database it works fine and the data is there. 

Is there maybe a more detailed log that I can go into? Or some way to verify that the database is working as it should?

**Comment by chrisjlocke** [comment]
> I don't seem to be getting an error message (have looked under "SQL log")

Is your Python script inserting the record into the database, or are you using DB Browser to insert the record?  If the former, then DB Browser won't log any database activity, as its 'outside' its connection.  It only logs SQL statements entered into the 'Execute SQL' tab.  Its up to your Python program to detect any SQL failings.

What is the actual SQL statement you're inputting?  HAve you tried pasting this into the 'Execute SQL' tab and seeing if it works there?

**Comment by moosemachineDK** [comment]
Problem solved. 

Turned out there was a bug in the python script which didn't translate well into the preexisting database (with its preexisting naming conventions)  whereas it made no difference in the new database as it was build using the 'wrong' naming conventions. Rookie mistake, I know. 

So, not a SQLite issue but a python script issue (matching predefined dataspecs).
 
Thanks for your time on this.

**Comment by justinclift** [comment]
No worries @moosemachineDK, glad you got it solved. :smile:
