### ISSUE TITLE
Getting a FOREIGN KEY constraint failed issue

### ISSUE THREAD

**Issue by CGrijalva90** [sqlitebrowser/sqlitebrowser#1637]
I have created the following tables:
    db.serialize(function() {
      db.run('CREATE TABLE IF NOT EXISTS `Artist` ( ' +
            '`id` INTEGER NOT NULL, ' +
            '`name` TEXT NOT NULL, ' +
            '`date_of_birth` TEXT NOT NULL, ' +
            '`biography` TEXT NOT NULL, ' +
            '`is_currently_employed` INTEGER NOT NULL DEFAULT 1, ' +
            'PRIMARY KEY(`id`) )');
    
      db.run('CREATE TABLE IF NOT EXISTS `Series` ( ' +
            '`id` INTEGER NOT NULL, ' +
            '`name` TEXT NOT NULL, ' +
            '`description` TEXT NOT NULL, ' +
            'PRIMARY KEY(`id`) )');
    
      db.run('CREATE TABLE IF NOT EXISTS `Issue` ( ' +
            '`id` INTEGER NOT NULL, ' +
            '`name` TEXT NOT NULL, ' +
            '`issue_number` INTEGER NOT NULL, ' +
            '`publication_date` TEXT NOT NULL, ' +
            '`artist_id` INTEGER NOT NULL, ' +
            '`series_id` INTEGER NOT NULL, ' +
            'PRIMARY KEY(`id`), ' +
            'FOREIGN KEY(`artist_id`) REFERENCES `Artist`(`id`), ' +
            'FOREIGN KEY(`series_id`) REFERENCES `Series`(`id`) )');
    });

`Artist` and `Series` table work fine and I'm able to update them and insert rows into them, but I can't seem to enter any data into the cells for the `Issues`. I'm not sure if there are some settings in it that I need to modify, because I can't even edit the cells to insert rows into them. I get the following error:

> Error adding record:
FOREIGN KEY constraint failed (INSERT INTO `Issue`(`id`,`name`,`issue_number`,`publication_date`,`artist_id`,`series_id`) VALUES (1,'',0,'',0,0);)

Which basically says that no information was stored in the table cells when I tried to create a new record.

I noticed that another user had a similar error but this was back in 2016 and he seemed to have fixed it himself.

**Comment by justinclift** [comment]
This and #1638 seem the same.  I'll close this one, as the other one seems to have slightly better formatting. :smile:
