### ISSUE TITLE
Default sqlitebrowser version for current Ubuntu (14.04LTS) is VERY old

### ISSUE THREAD

**Issue by rob-hills** [sqlitebrowser/sqlitebrowser#164]
I am trying to convert an existing MySQL DB to sqlite.  Being an optimist, I first tried an "ansi-compatible" export from the MySQL DB for one table, created (and saved) a new DB in sqlitebrowser and then tried running some of the Export file.  The result is that sqlitebrowser just hangs.

I was hoping to see it report a syntax error or something like that so I could go about massaging the sql exported from MySQL so I could do my conversion.

The SQL I tried to run in sqlitebrowser was the following:
```sql
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `acom_mforum`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE IF NOT EXISTS "posts" (
  "post_id" mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  "topic_id" mediumint(8) unsigned NOT NULL DEFAULT '0',
  "forum_id" mediumint(8) unsigned NOT NULL DEFAULT '0',
  "poster_id" mediumint(8) unsigned NOT NULL DEFAULT '0',
  "icon_id" mediumint(8) unsigned NOT NULL DEFAULT '0',
  "poster_ip" varchar(40) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_time" int(11) unsigned NOT NULL DEFAULT '0',
  "post_reported" tinyint(1) unsigned NOT NULL DEFAULT '0',
  "enable_bbcode" tinyint(1) unsigned NOT NULL DEFAULT '1',
  "enable_smilies" tinyint(1) unsigned NOT NULL DEFAULT '1',
  "enable_magic_url" tinyint(1) unsigned NOT NULL DEFAULT '1',
  "enable_sig" tinyint(1) unsigned NOT NULL DEFAULT '1',
  "post_username" varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_subject" varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  "post_text" mediumtext CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  "post_checksum" varchar(32) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_attachment" tinyint(1) unsigned NOT NULL DEFAULT '0',
  "bbcode_bitfield" varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  "bbcode_uid" varchar(8) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_postcount" tinyint(1) unsigned NOT NULL DEFAULT '1',
  "post_edit_time" int(11) unsigned NOT NULL DEFAULT '0',
  "post_edit_reason" varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_edit_user" mediumint(8) unsigned NOT NULL DEFAULT '0',
  "post_edit_count" smallint(4) unsigned NOT NULL DEFAULT '0',
  "post_edit_locked" tinyint(1) unsigned NOT NULL DEFAULT '0',
  "post_visibility" tinyint(3) NOT NULL DEFAULT '0',
  "post_delete_time" int(11) unsigned NOT NULL DEFAULT '0',
  "post_delete_reason" varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  "post_delete_user" mediumint(8) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY ("post_id"),
  KEY "forum_id" ("forum_id"),
  KEY "topic_id" ("topic_id"),
  KEY "poster_ip" ("poster_ip"),
  KEY "poster_id" ("poster_id"),
  KEY "post_username" ("post_username"),
  KEY "tid_post_time" ("topic_id","post_time"),
  KEY "post_visibility" ("post_visibility")
) AUTO_INCREMENT=51587 ;
```

Ideally sqlitebrowser should report what the error(s) is/are rather than just hanging.

**Comment by justinclift** [comment]
Hmmmm, we could probably put a call out through Twitter, to see if someone wants to create a PPA for our releases on an ongoing basis.  Pretty sure @rp- is busy with other stuff atm.

Guessing no objections? :smile:

**Comment by Jerome67000** [comment]
Hi,

I just have the same very old version 2.0b1 with my new elementary os 0.3 install (ubuntu 14.04 based) with the app manager. I have build my own 3.5.1 version and its works fine but I think that an updated version to the ubuntu app manager could be a good contribution for the community !

**Comment by justinclift** [comment]
Yep, we're looking forward to having this too.

@deepsidhu1313 volunteered in https://github.com/sqlitebrowser/sqlitebrowser/issues/238 to do the Ubuntu packaging for the next release, which should flow into at least Mint + (I'm guessing) Elementary too. :smile:

**Comment by justinclift** [comment]
@rob-hills @Jerome67000 Would you have time to try out an initial test build?

If so, @deepsidhu1313 created one here a few hours ago:

&nbsp; &nbsp; https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

**Comment by Jerome67000** [comment]
So, I just have tried the ppa from @deepsidhu1313 and the install works but I have an UI issue, maybe because im in Elementary OS. My own build hasn't this issue. The weird problem is now i cant build anymore my own build, the sudo make install say : 
```
[ 24%] Built target antlr
[ 25%] Generating src/moc_qhexedit_p.cxx
moc: Cannot open options file specified with @"
```

So I cant show you the good UI in Elementary OS, but this is the weird UI with the PPA :

![screen_ppa](https://cloud.githubusercontent.com/assets/7358899/7315275/4c32fa12-ea6c-11e4-998a-262c784c1624.jpg)

**Comment by deepsidhu1313** [comment]
I have almost same UI with both windows version (via wine or on windows) and linux version (debianized), so i can't tell the difference.

![img](/home/nika/Pictures/Screenshot from 2015-04-24 14:09:33.png)
Format: ![Alt Text](url)

**Comment by Jerome67000** [comment]
When i have a little more time i will try to fix the build problem to show you the interface on Elementary OS

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by justinclift** [comment]
@deepsidhu1313 3.6.0 is released.  You ok to update your ppa?

We should add it to the front page when that's done too. :smile:

**Comment by deepsidhu1313** [comment]
@justinclift publihed untested 3.6.0 packages to ppa https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing , 

Please test these packages so that i can publish them to stable ppa 
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser

:smiley: :+1:

**Comment by justinclift** [comment]
@rob-hills @AndroidGecko @Jerome67000 Would you have a few minutes to try out the new PPA above (if it suits your Ubuntu version)? :wink:

**Comment by Jerome67000** [comment]
Hi, the update work ! i have now the Version 3.6.99. It is not the 3.6.0 ??

**Comment by justinclift** [comment]
Ahhhh, @deepsidhu1313... it sounds like you packaged master branch and not the v3.6.x branch?

I should probably have [pointed you to this](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Release-process) before, but I didn't think of it until now. :anguished:  Sorry about that.

We can update that info in the wiki, if there's anything special that's needed for the Ubuntu builds btw.  That page is a work in progress. :wink:

@Jerome67000 Thank you, it's good you checked. :smile:

**Comment by deepsidhu1313** [comment]
@justinclift i downloaded latest tar.gz file from the link given at http://sqlitebrowser.org/ via https://github.com/sqlitebrowser/sqlitebrowser/tarball/master.

Can you please provide me the link to release 3.6.0 ? (save me the trouble, i am busy with wedding of my brother, i hope you understand) :smiley: 

And package need following dependencies installed 

 libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libqt5core5a (>= 5.2.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libsqlite3-0 (>= 3.5.9), libstdc++6 (>= 4.4.0)

if you have upgraded any package (dependency) in your build, please let me know. I am using earlier scripts from previous ppa for packaging. 

thanks !!

@Jerome67000  Thanks to you too !!

**Comment by justinclift** [comment]
No worries. The "master" bit on the end of "https://github.com/sqlitebrowser/sqlitebrowser/tarball/master" is the branch name.  "master" in this case is our active development branch, not the 3.6.x stuff.

Here's the link you want: :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.6.0.tar.gz

**Comment by deepsidhu1313** [comment]
@justinclift @Jerome67000  I downgraded version to 3.6.0 from 3.6.99 for all packages. Please retest the packages.

**Comment by Jerome67000** [comment]
:+1: its fine, after update and upgrade, its the 3.6.0 :)

**Comment by justinclift** [comment]
Excellent.  Just added pointers about it to the front page.  Please let me know when the PPA location changes (eg moves out of the -testing one), so it can be updated.  Or submit a Pull Request with the updated info, whatever works. :smile:

**Comment by deepsidhu1313** [comment]
@justinclift  Packages rebuilt on stable ppa 

https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser

**Comment by justinclift** [comment]
Excellent.  URL on the front page now updated.

Oh, I need to update the website "Linux" bit too.  I'll do it after work tonight (if I forget, pls remind me!). :wink:

**Comment by rob-hills** [comment]
Hi Justin,

On 28/04/15 20:40, Justin Clift wrote:
>
> @rob-hills <https://github.com/rob-hills> @AndroidGecko
> <https://github.com/AndroidGecko> @Jerome67000
> <https://github.com/Jerome67000> Would you have a few minutes to try
> out the new PPA above (if it suits your Ubuntu version)? :wink:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/164#issuecomment-97048283>.
>

I'd normally be happy to help but we're away cruising at present and
internet connectivity is extremely limited so I'd not be much help
anyway.  I'll be back in early June and can give it a go then if it's
not too late.

Cheers,

-- 
Rob Hills
Waikiki, Western Australia
Mobile: +61 (412) 904-357

**Comment by justinclift** [comment]
@rob-hills Already taken care of.  Thanks for responding.  Maybe try stuff out when back from your cruise (I'm jealous :wink:), and see if everything works as you expect then? :smile:

**Comment by ntwalibas** [comment]
Ubuntu 14.04 successful install. :-)

**Comment by justinclift** [comment]
Awesome. :grinning:
