### ISSUE TITLE
Update OpenSSL to v1.1 & SQLCipher to v4

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1640]
Now that SQLCipher v4 has been released, we should investigate what we need to do for supporting it:

&nbsp; &nbsp; https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md#400---2018-11-30

Although it compiles "as it" without any real changes in our source code, apparently the new defaults in SQLCipher are such that it won't open existing databases.

So, we'll need to figure out how to work around that, so our users can continue to open their existing databases + so newly created databases use the new, stronger settings.

We'll probably need to figure out what to do when saving an older database.  Should we update the database to use the new, stronger settings?  (guessing we'll need some kind of toggle/switch in our preferences)

**Comment by justinclift** [comment]
Started experimenting with changes for OpenSSL 1.1 support in a new set of `openssl11_vx` branches:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/tree/openssl11_v1

Need to get some sleep atm, but a Win64 compile using the above branch is running now.  Hopefully it completes ok. :smile:

**Comment by karim** [comment]
What I understood from https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/

SQLCipher 4 will not open SQLCipher 3 database by default. In order to open them we have two options:

1. Adjust settings at runtime.
2. Migrate older databases.

Both options depend on being able to know which SQLCipher version is used in a database file? Are we able to detect that when opening an encrypted database file?

If yes, then I would say use option 1 (adjust setting at runtime) to be able to open it using v3, then show a notification telling the user that the file is using old v3 and it is recommended to upgrade it to v4 using option 2 (migrate). With a toggle/switch to auto upgrade older databases after opening them.

If no, then we do it blindly. :smiley: Open using v4 settings, if failed, fallback to opening it using v3 settings, if failed, then say Opsss. :smiley: 

For newly created database, I would say create them always as v4. The downside would be if this database is shared with others and they are using older version of DB4S. But it's okay cause they can always update their version.

**Comment by justinclift** [comment]
Makes sense to me.  The "[Compatibility](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/#compatibility)" section on that blog post should help us figure it out too. :smile:

**Comment by justinclift** [comment]
The Win64 build seems to be working now with OpenSSL 1.1.0j & SQLCipher 4.0.0.

@karim At the end of the msi install, it has the option to "Run DB Browser for SQLite".  Is it feasible to have that be some kind of selector so the user can choose either the SQLite or SQLCipher one to run instead?  Maybe a radio button version or drop down list?  Would probably need to add an option for "Don't run either just yet" too, since it'd be replacing a yes/no checkbox. :smile:

**Comment by justinclift** [comment]
Heh Heh Heh.  Looks like Qt itself might not be liking OpenSSL 1.1.0j at the moment, or I've forgotten to include some .dll:

![ssl error v1](https://user-images.githubusercontent.com/406299/49335424-470ad700-f641-11e8-8ff6-2ddcfb4ccb63.png)

Both libcrypto.dll and libssl.dll are definitely in the DB4S install dir though, so it's not those ones.  Experimenting now...

**Comment by justinclift** [comment]
Coping the OpenSSL 1.0.2q .dll's into the DB4S directory didn't help either. :wink:

For now, I think I'll avoid spending further time with OpenSSL 1.1 stuff, and just stick with OpenSSL 1.0.  There are better things to put time into atm. :smile:

**Comment by justinclift** [comment]
As a data point, Qt should be able to work with OpenSSL 1.1:

&nbsp; &nbsp; https://bugreports.qt.io/browse/QTBUG-52905

There's probably some compile option we need to change, or something that we need to adjust in our code to get it working.  I'm not to experiment further with it just yet though. :smile:

**Comment by karim** [comment]
> @karim At the end of the msi install, it has the option to "Run DB Browser for SQLite". Is it feasible to have that be some kind of selector so the user can choose either the SQLite or SQLCipher one to run instead? Maybe a radio button version or drop down list? Would probably need to add an option for "Don't run either just yet" too, since it'd be replacing a yes/no checkbox. smile

I will look into it once I finish uninstalling the old installer.

> For now, I think I'll avoid spending further time with OpenSSL 1.1 stuff, and just stick with OpenSSL 1.0.

I agree. Let's not waste more time with it for now. Qt 5.12 should be [released soon](https://wiki.qt.io/Qt_5.12_Release) anyway.

> As a data point, Qt should be able to work with OpenSSL 1.1

Yes it should, **if** we built Qt from source. :smiley: 

Right now we are using the binary release of Qt which loads the .dll it was compiled with, and that is 1.0.

**Comment by justinclift** [comment]
No worries, sounds good.  I'm doing a practise run of building the beta2 release.  I've copied over the bits and pieces to do the combined SQLite and SQLCipher installer for Windows.  The Win64 one builds ok, the Win32 one is running through now.  Hopefully that's ok too.

I'll need to investigate doing a combined installer for macOS.  Suspecting it won't be feasible though, so we'll probably just use the single SQLCipher version there, at least for now.  Should be fairly easy to add in the math extension too, now that it's in our source tree and all. :smile:

**Comment by mtissington** [comment]
I have built a version of sqlcipher 4.0 with openssl 1.1.1a (x64)
(https://slproweb.com/products/Win32OpenSSL.html)
Using a corresponding version of sqlcipher.exe I can create/open/encrypt a database.

I confirm DB Browser can not open it.

I tried to replace the db browser sqlcipher with the one I built (also copied over the needed libcrypto-1_1-x64 and DB Browser just failed to start. No idea why.

I confused why you need to include libea32.dll?

**Comment by justinclift** [comment]
> I'm confused why you need to include libea32.dll?

Was just experimenting. :smile:

After building DB4S with SQLCipher 4.0 + OpenSSL 1.1.0j (from the same download location you mention), DB4S itself isn't able to communicate over networks using TLS.  It seems like a Qt problem, so I figured I'd see what happens when putting the old OpenSSL 1.0.2 libraries in the same dir as the DB4S installation.  eg seeing if DB4S would use the OpenSSL 1.1.0 bits, and Qt might use the OpenSSL 1.0.2 bits.  But, no luck.

As @karim mentioned, Qt will probably work fine with OpenSSL 1.1.0 if we compile (Qt) ourselves.  Haven't gone down that path yet, and **probably** won't.  Wanting to avoid that for now, as practically speaking OpenSSL 1.0.2 is "good enough" for the moment. :smile:

**Comment by mtissington** [comment]
Am I missing a hidden feature? When the need to communicate over the network using TLS?

**Comment by justinclift** [comment]
Two main things:

1. Doing the update checks (and TLS is a requirement for all network traffic these days) to see if the version being run is "the latest" one or not.  It's a check that's automatically done when DB4S starts (can be disabled in Preferences too for those that want).
2. Any/all communication with the (still in development) DBHub.io "Cloud".  eg anyone wanting to save their data in our online infrastructure (publishing data, using it as a backup, etc), or wanting to grab some data set that's already on there. :smile:
  * The whole sign-up/setup process for that is kind of a PITA atm.  We need to smooth that out / polish it somewhat so it's easier for people to try out. :wink:

**Comment by MKleusberg** [comment]
With commit 88ce4acf974b8b8607d656f84abd51b5c7aa6eaa you now get to choose all the encryption settings you need. There are also two presets, one for SQLCipher3 and one for SQLCipher4. The default one is determined by the currently used SQLCipher version:
![screenshot_20181212_135049](https://user-images.githubusercontent.com/3153504/49870940-25fe6f00-fe15-11e8-869b-44a48233114c.png)

With this it should be possible to open v3 databases using v4 and (I guess) vice versa.

**Comment by mtissington** [comment]
I was dreaming about a dialog like this - turns out not to be a dream - can't wait to test ....

**Comment by justinclift** [comment]
Win64 nightly builds are happening now including this dialog.  In theory (!) the builds for today should refresh on the nightly server in about 1/2 hour and be ready to test. :smile:

**Comment by mtissington** [comment]
You guys are good - confirmed able to open sqlcipher 4 database with great dialog 👍

**Comment by justinclift** [comment]
The windows builds on the nightly server have just been rebuilt using SQLCipher v4.0.0 + this new dialog:

* https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2018-12-12-win32.msi
* https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2018-12-12-win64.msi

**Comment by justinclift** [comment]
@MKleusberg With the KDF iterations field, should that be an enforced "powers of two" thing, or is any integer value ok?

**Comment by justinclift** [comment]
Rebuilt today's macOS nightlies to use SQLCipher v4.0.0 + this new dialog as well:

* https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20181212.dmg

**Comment by justinclift** [comment]
Closing this, as we're shipping with SQLCipher 4.x now.  No need for OpenSSL 1.1 yet, as it's still (for now) a supported thing.

**Comment by MKleusberg** [comment]
@justinclift Regarding your question from November last year: I haven't tried it but for KDF iterations any integer value should be ok. The default, 64000, isn't exactly a power of two either :smile:

**Comment by justinclift** [comment]
Good point. :smile:
