### ISSUE TITLE
New changes for the Windows Installer

### ISSUE THREAD

**Issue by karim** [sqlitebrowser/sqlitebrowser#1642]
I started updating the Windows Installer so I will need some feedback before committing the changes.

After merging SQLite and SQLCipher together in a single installer, we need to provide some helpful information to the user about the change.

The way it is done now is not good as mentioned by @chrisjlocke in https://github.com/sqlitebrowser/sqlitebrowser/issues/1224#issuecomment-442792184.

Moreover, the installer silently installs the Math extension without informing the user about it and it might be missed and/or ignored completely.

![db4s-1](https://user-images.githubusercontent.com/8761081/49398379-d0580180-f746-11e8-8602-d9493c3aa96e.jpg)

In the above picture, the shortcuts have been removed from the features list (left, old installer) and the math extension has been added (right, new proposed installer).

![db4s-2](https://user-images.githubusercontent.com/8761081/49398649-b0750d80-f747-11e8-8824-5eda8e4d8f50.jpg)

In the second picture, a new dialog was added with, hopefully :smiley:, some better information about both versions, and a way to set their shortcuts in a better way. This dialog is shown right after the one in the first picture and before installing anything.

Is this a good design? Too much text? Not enough information? Is it confusing? What about the wording? Did I get it right? Please answer any or all of the above. :smile: 

If everything went well, then I will commit these changes, and start working on other things. On my list now is detecting the old installer, enable/disable update check during installation, better way to launch the application (either SQLite or SQLCipher) after installation since we have two .exe now.

**Comment by justinclift** [comment]
I definitely like the new dialog!

It explains things well, and should be a good approach. :smile:

One slight text adjustment with it:

> ... that provides transparent ...

is probably better as:

> ... providing transparent ...

It just "sounds" a bit er... smoother?  Completely subjective of course. :wink:

With the ordering of the dialog, is it feasible to have that appear before the drop down component/extentions/etc selector dialog?  It's probably more optimal to have that drop down thing come afterwards.

Your ToDo list items sound good to me too. :smile:

**Comment by chrisjlocke** [comment]
"It also has SQL Cipher..." this doesn't convey that there are two separate applications.  It also doesn't convey the version of SQLite is behind the other one.  Its hinted at with the "[DB4S] has the latest version of SQLite...."

To explain this properly, we need to link to the WIki! 😆 

"DB Browser for SQLite uses the latest version of SQLite, but does not have encryption support.  DB Browser for SQLCipher is a separate application with SQLCipher extension built in, providing transparent blah blah encryption marmalade toast and slippers, but uses a slightly older version of SQLite.  Both applications are installed and can run concurrently.  This page allows you to **choose** the shortcuts blah blah...."

Note that your version has **chose** and not **choose**.

**Comment by chrisjlocke** [comment]
How about 'DB Browser for SQLite - Professional' 😆

**Comment by karim** [comment]
If we used "DB Browser for SQLCipher", without changing the application name, it will be confusing to users when they open it and it says in the title "DB Browser for SQLite". They will think they opened the wrong one.

**Comment by chrisjlocke** [comment]
Good point.  😞

**Comment by karim** [comment]
How about now..

![db4s-3](https://user-images.githubusercontent.com/8761081/49437640-be1ca880-f7c4-11e8-8b0c-dfc726ce433a.jpg)

The labels on top of the checkboxes match the shortcuts on Desktop also.

**Comment by karim** [comment]
I committed these changes for now so I don't lose track of them while working on other things.

These are all the strings in the shortcuts dialog. Feel free to change them or tell me what needs to be changed so I can correct it.

https://github.com/sqlitebrowser/sqlitebrowser/blob/d8b1ac2c3915934a9397e4ddee009dd2b9e3d536/installer/windows/strings.wxl#L5-L13

**Comment by justinclift** [comment]
Sounds good.  I'll start the windows nightly builders now, so we have installers for people to test. :smile:

**Comment by justinclift** [comment]
New Win nightlies are up now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
Can the extension size be added?  Specifying 37 KB would put a lot of minds at rest, that its not a 4 GB install! ;)

![image](https://user-images.githubusercontent.com/7872218/49453470-19f22c00-f7db-11e8-9fe1-0dcdab2ec902.png)

**Comment by karim** [comment]
Nice. :smiley: 

Do you think the text in the dialog is too much/complicated for new users? Or maybe missing some important information?

@chrisjlocke That's probably because you have it already installed. Nothing *new* is being installed. Try removing it and adding it again.

**Comment by chrisjlocke** [comment]
I guess the only thing that's slightly jarring (but understandable) is that we install the SQLCipher version, whether they want it or not (they've already downloaded it, so why not...) but then ask, "Hey, want to install the math extension?"

Not saying what we're doing is wrong, and I don't think 'the other' way is better, but ... well, just throwing my useless opinion out there! 😆

**Comment by chrisjlocke** [comment]
> That's probably because you have it already installed.

Doh!  Thanks!

![image](https://user-images.githubusercontent.com/7872218/49454377-f0d29b00-f7dc-11e8-9cbb-dbe79eb3f4af.png)

**Comment by mtissington** [comment]
Why are two versions required?
sqlcipher will still open a non encrypted database just fine.

**Comment by karim** [comment]
> Why are two versions required?

The only difference is SQLite version. The [version of SQLite](https://www.sqlite.org/releaselog/3_20_1.html) that comes with SQLCipher is over one year old. Some users want the latest version of SQLite. Like [UPSERT](https://www.sqlite.org/releaselog/3_24_0.html) that was introduced six months ago. The latest SQLite version is 3.26.0 (released 4 days ago) is already in the latest nightly.

That's why there were always two different versions. We just merged them together into a single installer.

**Comment by mtissington** [comment]
SQLCipher is 3.25 so they are almost on the ball...

**Comment by karim** [comment]
> SQLCipher is 3.25 so they are almost on the ball...

True. But after reading their release notes, it looks like the new version (SQLCipher v4) it is not compatible with the old version (SQLCipher v3) databases. New version will not open databases created with older version without changing how we open older databases or migrate them. We haven't got around doing that yet.

While SQLCipher is using a recent version of SQLite *now*, both versions will drift apart over time.

> I'm guessing the only difference is which dll is used (sqlite3.dll or sqlcipher) ... if so maybe there is a way to configure it instead of shipping two different versions?

Each .exe is linked to a specific .dll (either sqlite3.dll or sqlcipher.dll). A single .exe cannot link to both .dll since they use the same API/function names, and we will get linker error if we tried that. That's why we always needed two different .exe.

> So instead of the dialog with various options

The new dialog just asks you where, and if you want, to place the shortcuts. If you want to use SQLCipher only, then simply uncheck the boxes under SQLite. The installer will remember your choices and keep these boxes unchecked when updating to a newer version, so you just click Next in this dialog.

**Comment by karim** [comment]
> I guess the only thing that's slightly jarring (but understandable) is that we install the SQLCipher version, whether they want it or not (they've already downloaded it, so why not...) but then ask, "Hey, want to install the math extension?"

@chrisjlocke I get your point. Installing another application that can run next to the normal one with its own shortcut, but then ask .. "hey, want to install a 37kb extension?" :smile:  

Actually, everything is installed. :smiley: SQLite, SQLCipher, extensions, etc. The shortcuts selection/dialog will only add/remove shortcuts, but both versions are installed.

Extensions however are different. They are optional. That's why extensions are in the feature selection list. Also, they affect your SQL queries, the loading time of the app, etc. Or maybe you just don't want them. Math extension is just an example, and we might add more in the future.

> ![image](https://user-images.githubusercontent.com/7872218/49454377-f0d29b00-f7dc-11e8-9cbb-dbe79eb3f4af.png)

While the file is only 37kb it is showing 40kb. I guess MSI is using the size on disk and not the real size of the file.

**Comment by justinclift** [comment]
> Math extension is just an example, and we might add more in the future.

The [SpatiaLite extension](https://www.gaia-gis.it/fossil/libspatialite/index) would probably be a good next candidate to investigate. :smile:

**Comment by justinclift** [comment]
Been noticing something a bit weird for the last few days (from before this latest change to the installer, so that's not the problem.).

Ever since I re-created the automatic nightly build jobs for the Win32/64 installers, the .zip files keep on being created as 1kb empty things.  Running the exact same nightly builder batch files manually works though.

Generally this kind of thing is some form of permission or access error. Last night I added some basic redirection of stdout/stderr to a log file (for just the zipping), and this is what showed up:

```
The Windows Installer Service could not be accessed.  This can occur if the Windows Installer is not correctly installed.  Contact your support personnel for assistance.

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive:
0 files, 0 bytes

Creating archive: DB.Browser.for.SQLite-2018-12-05-win32.zip

Items to compress: 0


Files read from disk: 0
Archive size: 22 bytes (1 KiB)

Scan WARNINGS for files and folders:

C:\builds\zip\DB Browser for SQLite : The system cannot find the path specified.
----------------
Scan WARNINGS: 1
```

Weirdly, it looks like the `msiexec` line is the one being blocked.  I'll try and get time to investigate today.  If anyone has ideas in the meantime of what things to look at, I'm open to suggestions. :smile:

Hopefully it just some setting needing changing in the Task Scheduler task.

**Comment by karim** [comment]
I updated the installer to detect NSIS and uninstall it before installing using the MSI. There are no dialogs or any new UI. The uninstall will run silently before installing/updating the new version.

I tested it by installing v3.10.1 (first 32-bit then 64-bit) and then running the MSI. It detected NSIS and removed it then installed the MSI without a problem. But I will need others to test it just to be sure. :smiley: 

> The [SpatiaLite extension](https://www.gaia-gis.it/fossil/libspatialite/index) would probably be a good next candidate to investigate. smile

Yes, I want to add it, but the problem is its size. It is almost as big as the whole DB4S.

> Ever since I re-created the automatic nightly build jobs for the Win32/64 installers, the .zip files keep on being created as 1kb empty things. Running the exact same nightly builder batch files manually works though.

Could be user/permission thingy if you are running it from the Task Scheduler.

Try running `msiexec` with logging enabled. Add `/l*vx file.log` at the end of the command.

**Comment by justinclift** [comment]
> Yes, I want to add it, but the problem is its size. It is almost as big as the whole DB4S.

Gah.  Ok that's out then.  Definitely a separate install of some sort. :smile:

Thinking about things a bit more, should we just add the math extension to the install and not bother asking?  It's minimal file size and doesn't seem to have any negative consequences (that we know of).

The benefit would be a slightly simpler installation process.  No real downside is coming to mind.

What do you reckon? :smile:

**Comment by justinclift** [comment]
Oh, I've just manually started the Win build scripts again.  New installers should be online in an hour or so. :smile:

**Comment by karim** [comment]
> Thinking about things a bit more, should we just add the math extension to the install and not bother asking? It's minimal file size and doesn't seem to have any negative consequences (that we know of).

The file is already bundled and automatically installed by default anyway. We are not asking to install it but simply showing it to the user that it's being installed.

It is not the size, it is more about the **visibility**, Without showing it the user might not be aware it exist.

Another thing is being optional, and affects your SQL queries. What if the user complied his/her own, or using a slightly different version than ours? If the user decided to delete ours from extensions folder it will not work, since the next time he/she installs an update it will be dropped again in extensions folder.

I know it is tempting to *just do it* :smiley: and install it anyway, since it is just 37kb, but this was merely a test. We will add more extensions for sure. I'm planning to add more from here https://www.sqlite.org/src/file/ext/misc, and possibly any single file (*.c) extensions.

> The [SpatiaLite extension](https://www.gaia-gis.it/fossil/libspatialite/index) would probably be a good next candidate to investigate. :smile:

I know I spoke about its size before, but how about we make an *extensions pack*? A new installer that collects all possible extensions so we don't have to worry about DB4S installer size.

If you want to use DB4S only use its installer, and if you want this or that extension, then download the extension pack and pick from it the ones you need. This way, users will no longer hunt for these extensions or try to compile them on their own, and we will keep DB4S size low.

At the moment, making a new installer for math extension only sounds like a very bad idea. :smiley:

**Comment by justinclift** [comment]
>  ... how about we make an extensions pack? A new installer that collects all possible extensions so we don't have to worry about DB4S installer size.

Sounds good to me.  If we have the "DB4S automatically loads extensions in the `extensions` folder" thing in place, it would probably be super simple.

Timing wise... lets do the extension pack for 3.12.0 (eg the release after this one), and keep with just the math one for this (3.11.0) release?

**Comment by justinclift** [comment]
The nightly build script kicked off and mucked up the manual builds, so I've just started the Win64 one manually again.  I'll do the Win32 one sometime after that finishes.

**Comment by karim** [comment]
> Timing wise... lets do the extension pack for 3.12.0 (eg the release after this one), and keep with just the math one for this (3.11.0) release?

I suppose so. I don't have much time to do it now anyway.

The more important thing I need to take care of now is the last dialog in the installer, that starts the application after setup.

**Comment by justinclift** [comment]
Good point.  With that done, I think we're nearly ready for the release. :smile:

**Comment by chrisjlocke** [comment]
If I download the MSI and extract it, I get a concise set of files.  

![image](https://user-images.githubusercontent.com/7872218/49576488-39a16580-f93d-11e8-858a-1caab54e75fd.png)

If I download the .ZIP and extract it, I get api* files which are not in the extracted MSI folders.

![image](https://user-images.githubusercontent.com/7872218/49576573-6ce3f480-f93d-11e8-98d9-0a271b37faf3.png)

Is it the VC runtime stuff?  There are a couple of DLLs on the end (vccorlib140.dll and vcruntime140.dll) also not in the MSI set.

**Comment by justinclift** [comment]
Yep, it's the contents of the VC redistributable, extracted and placed in the main application folder so it's automatically found at startup.

**Comment by karim** [comment]
> I get api* files which are not in the extracted MSI folders.

They should be included in the MSI, but in a different folder. MSI *installs* them in the system folder, **if** they were not found on your system. With .ZIP version we can't guess if they are installed or not, so we put them in DB4S folder.

> Is it the VC runtime stuff? There are a couple of DLLs on the end (vccorlib140.dll and vcruntime140.dll) also not in the MSI set.

This might be an interesting read https://blogs.msdn.microsoft.com/vcblog/2014/06/10/the-great-c-runtime-crt-refactoring/ :smiley:

**Comment by justinclift** [comment]
> Could be user/permission thingy if you are running it from the Task Scheduler.
>
> Try running msiexec with logging enabled. Add /l*vx file.log at the end of the command.

Yep.  Turned out to be a simple fix too, thankfully.  Ticked the "Run with highest privileges" box, and the .zips are now building successfully. :smile:

![db4s-win_builders_highest_privs](https://user-images.githubusercontent.com/406299/49694777-b144ee00-fbe4-11e8-8cb3-cc134295c2f2.png)

**Comment by justinclift** [comment]
With that fixed, the "automatic" windows nightly builds should really be automatic again.  The build box is back to using a wired (ethernet) connection, so there's none of this connection stability issue from a spotty wireless connection. :smile:

**Comment by justinclift** [comment]
@karim Is it ok to close this issue, or is there still stuff for it needing to be done? :smile:

**Comment by karim** [comment]
Sorry, I forgot to close it. Yes, it is done for now, and if there is something new, we should open a new issue. Closing it now.
