### ISSUE TITLE
Project files showing the wrong table and it is showing it empty

### ISSUE THREAD

**Issue by karim** [sqlitebrowser/sqlitebrowser#1649]
Details for the issue
--------------------

If you open a project file, you expect to see the last table you saved displayed in Browse Data tab.

What I saw instead is the first table, and it is not showing anything. Just "determining row count..." is displayed instead of the number of rows. The table has only one row. It stays like this till I switch to another table and back to it, then it shows it correctly.

Switching to other tables showed one table correctly, but showed another as empty with 0 rows in it. Opening the database file itself, not the project file, is fine and I can see the table rows correctly, so I assume this is only related to project files.

I thought maybe my project file was somehow corrupted so I deleted it and created a new one, but it is the same.

This happened only with Dec 5 & 6 nightlies. Dec 4 and earlier are fine.

#### What did you do?

Opened a (*.sqbpro) project file.

#### What did you expect to see?

To see Browse Data tab opened on my table.

#### What did you see instead?

Browse Data tab is opened but on the *wrong* table (the first table), and it is empty, and it is saying "determining row count...". This table has *one* row only.

![db4s](https://user-images.githubusercontent.com/8761081/49604412-79486b80-f996-11e8-9c01-2f78a1a1514d.jpg)

Useful extra information
-------------------------
> DB4S v3.11.99 (Dec  5 2018) on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.26.0
> and Qt 5.11.2

**Comment by mgrojo** [comment]
I've also noticed this, but simply opening a DB. It used to open the first table in the dropdown and show the data, but now it only shows the name but does not load the data. It should be one of the latest changes, because it doesn't happen with v3.11.x.

**Comment by justinclift** [comment]
> It should be one of the latest changes, because it doesn't happen with v3.11.x.

**\*Whew\***  At least it's not a blocker for 3.11.0.  On that note, I need to go through the blocker list and see what's what.  Pretty sure there are some outstanding questions for me in the related issues. :innocent:

**Comment by MKleusberg** [comment]
@karim I think I have fixed a bug in the vicinity of this one. Can you maybe double check if it's also fixing your issue :smile:

**Comment by karim** [comment]
@MKleusberg Yes, I can confirm that this issue is fixed in the nightlies (Aug 19) release.

Thanks a lot, Martin. :smiley:
