### ISSUE TITLE
Renaming field in a table overwrites data in that field with previous field name

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1650]
Details for the issue
--------------------
Guess this is linked to the recent fix to the modify table code.

#### What did you do?
Renamed a field

#### What did you expect to see?
The field renamed

#### What did you see instead?
Sheer horror and panic as database data was obliterated with the previous field name.

Useful extra information
-------------------------
Here is a screencast.
https://screencast-o-matic.com/watch/cFliDAr4lt

Shows the 'contractStandardId5' field has '48' in it.  Lets remove that 5 from the end of the field name.
Did that, and flip back to the 'Browse Data' tab.  Eek.  The field doesn't have '48' in it anymore, but the old field name.
Just in case it was rogue screen update, I click on 'Refresh' and yes, it stays there.

This is due to the insert statement keeping the old field name
`INSERT INTO "main"."sqlb_temp_table_3" ("annualValueToCA","clientId","contractStandardId","createdByUserId","dateCreated","dateModified","id","modifiedByUserId","notesPlain","notesRTF","statusId","typeId") SELECT "annualValueToCA","clientId","contractStandardId5","createdByUserId","dateCreated","dateModified","id","modifiedByUserId","notesPlain","notesRTF","statusId","typeId" FROM "main"."contracts";`

Note the third field - it has **"contractStandardId5"** in that insert, and not "contractStandardId"

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] Version 3.11.99 (Dec  6 2018)
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just a nod that I'm away tomorrow for a week, but *should* have t'internet access.  Just in case though, if you don't hear from me, no need to send out a search party...

**Comment by MKleusberg** [comment]
Thanks, Chris! That's a good catch and a very good analysis of what's happening :smile: I have just pushed a fix, so it should be fine in tomorrow's build.

**Comment by chrisjlocke** [comment]
Also a reminder not to use nightly builds in a production environment! 😉

**Comment by chrisjlocke** [comment]
Thanks.  Appears fixed in the latest nightly.
