### ISSUE TITLE
RSS feed for our Releases

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1652]
Learned something interesting today (from [here](https://github.com/SwiftOldDriver/iOS-Weekly/pull/944)).  GitHub provides an RSS (atom) feed for repo Releases:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases.atom

We should probably add that feed info to our website + README.md, so people into RSS feeds can make use of it. :smile:

**Comment by mgrojo** [comment]
Good idea!

**Comment by justinclift** [comment]
The RSS feed automatically created by our website is probably good enough:

https://sqlitebrowser.org/index.xml

It's not specific to releases though.
