### ISSUE TITLE
"New Record" button is disabled. (always in grey) 

### ISSUE THREAD

**Issue by pvakar** [sqlitebrowser/sqlitebrowser#1653]
Details for the issue
--------------------

#### What did you do?

Add new record manually at Browse Data tab

#### What did you expect to see?

New Record button as active . The same way as "Delete record"

#### What did you see instead?

"New Record" button is disabled.

Useful extra information
-------------------------
> DB4S v3.11.99 (Dec  6 2018) on Windows 10 (10.0) (winnt/10.0.15063) [x86_64]
> using SQLite Version 3.26.0
> and Qt 5.11.2

**Comment by justinclift** [comment]
Thanks @pvakar, that definitely sounds like a bug.  Probably something we've added in the last few days. :wink:

As a workaround for now, would you be ok to try either the 3.11.0-beta1 release, or a nightly build from a few days ago?

* https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta1
* https://nightlies.sqlitebrowser.org/win64/

**Comment by pvakar** [comment]
thanks Justin ! Last nightly build works fine !!!

**Comment by justinclift** [comment]
Just tried out the 2018-12-06 build, and yep... that definitely has the problem:

![db4s-issue_1653-2018 12 06_nightly_build](https://user-images.githubusercontent.com/406299/49695114-d720c180-fbe9-11e8-88fa-2abf7f3b6504.png)

The 2018-12-09 build though (our latest at the time) doesn't:

![db4s-issue_1653-2018 12 09_nightly_build](https://user-images.githubusercontent.com/406299/49695117-f7508080-fbe9-11e8-95c4-9978cbdba596.png)

So, not sure what it was, but it seems fixed already. :smile:

**Comment by MKleusberg** [comment]
That was my fault, sorry :wink: Here's the commit which fixed it: b42097c704cf08527e9e1155245268da852bfc29

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by justinclift** [comment]
@karim [Inkscape](https://inkscape.org).

I'm not particularly skilled with it these days.  Instead I just use it for this exact single purpose.  To put text boxes, lines, and callouts on screenshots. :wink:

**Comment by karim** [comment]
Thanks. :smiley:

**Comment by bam80** [comment]
Maybe related:
the button is grayed out on View even when INSTEAD OF INSERT trigger was crated on it (I also unlocked the view for editing as it's pointed here https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views#editing-data-in-a-view).
For confidence, I can successfully run INSERT statement on View manually and it runs the trigger.

So please check, if it's not related maybe we should file another issue.
