### ISSUE TITLE
"determining row count" displays forever in Browse Data tab

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1654]
Noticed a weird edge case just now, while trying out the latest nightly build (2018-12-09) on macOS.

After opening a database that has no tables in it yet (eg very empty database), the Browse Data tab permanently shows the string "determining row count" for the # of rows:

![db4s-edge_case_bug1](https://user-images.githubusercontent.com/406299/49693914-e4cb4c80-fbd3-11e8-8beb-1da4292b9d03.png)

We'll probably need need to write some kind of catch that recognises when there's no table for display in the Browse Data tab. :smile:

**Comment by MKleusberg** [comment]
Yeah, I agree. That's definitely misleading. Should be fixed with the latest commit :smile:

**Comment by justinclift** [comment]
Thanks.  I'm upgrading the version of macOS on our build mac at the moment (mostly waiting for downloads to finish).  Will generate the various nightly builds after that's done. :smile:

Can't really put it off either (doh!) , as it turns out the version of macOS (El Capitan) we're running is too old now.  Homebrew, which we rely on for our development bits, no longer works on it (as of today).  So, upgrade day. :man_shrugging:

**Comment by justinclift** [comment]
Just had a chance to try this out, but immediately found a (very minor) bug.

Now (running latest master code), if I'm on the Browse Data tab with the empty tab, the row count is correctly shown as "0 - 0 of 0":

![1](https://user-images.githubusercontent.com/406299/49917628-08540700-fef4-11e8-8270-905102b43b2c.png)

While still in the Browse Data tab, if I then open a different database (with data in it), the drop down showing the table name is correctly updated.  But the widget showing the table contents doesn't get populated:

![2](https://user-images.githubusercontent.com/406299/49917649-1ace4080-fef4-11e8-8fc0-59bcd2a0fe44.png)

Pressing the Refresh button gets the data to display though:

![3](https://user-images.githubusercontent.com/406299/49917665-2de11080-fef4-11e8-9ca1-87ca0fc5b451.png)

It's probably just some event either not firing, or not being listened to.

---

Looks like the "determining row count" bug can still be triggered by this too. :wink:

If I'm viewing a table with data in it:

![3](https://user-images.githubusercontent.com/406299/49917665-2de11080-fef4-11e8-9ca1-87ca0fc5b451.png)

... but then load the empty database while I'm still in the Browse Data tab, the "determining row count" line is shown (forever) again. :wink:

![4](https://user-images.githubusercontent.com/406299/49917763-9def9680-fef4-11e8-8877-df35e0eff33e.png)

**Comment by justinclift** [comment]
Closing this as the original issue has been fixed, and the follow up one has it's own issue report now. :smile:
