### ISSUE TITLE
How to change multiple cells at the same time?

### ISSUE THREAD

**Issue by proximityblue** [sqlitebrowser/sqlitebrowser#1655]
Hello! I have a problem with SQLite Browser.
I am trying to edit a .yls file and I am trying to change multiple cells at the same time, so I don't need to change all values individually. 
I am using SQLite Browser on Windows 10 (Version  3.10.1)
If anyone can help me with this, I will be most appreciated :)

![image](https://user-images.githubusercontent.com/38113084/49733155-b3f12300-fc78-11e8-854f-d5c0755f209e.png)

(Screenshot of database file)

**Comment by justinclift** [comment]
In theory, if you grab either a nightly build or the 3.11.0-beta1 release, either of those should let you select multiple cells and change them all at the same time. :smile:

* https://nightlies.sqlitebrowser.org/latest/
* https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta1

Does that help? :smile:

**Comment by SilvioGrosso** [comment]
Hello everyone,

I have just downloaded on Window 10 (64 bit) the latest nightlies installer:
Version 3.11.99 (Dec 11 2018)
Qt Version 5.11.2
SQLite Version 3.26.0

On the Browse Data tab I have tried to change more records simultaneously but I have failed.
Whenever I select more records on the same column (e.g. text type) and I modify them only the last one is changed. The other ones remain unchanged.

See this screenshot where I have selected 3 records with the name silvio (text type) and I want to change them into antonio:

![records](https://user-images.githubusercontent.com/33007383/49758798-2a654380-fcc0-11e8-92a7-c4c814e7aeb7.jpg)


I have also noticed that it is not possible to select, on the *same* column any records which are not contiguous (I have tried with CTR + left click of mouse, to select them).
For instance:
- apple;
- orange;
- pear
In this column I am unable to select apple on first row and pear on third row. 
However, I can easily select all three of them even though only the last one (pear) is changed.

**Comment by mgrojo** [comment]
Martin implemented an alternative way. You can edit a cell, select all the cells you want to have the same value (yes, they must be contiguous) and paste the value. It asks whether you want to paste, despite the copied data having a different layout than the selected cells, answer Yes and you'll have what you needed.

**Comment by justinclift** [comment]
Ahhh, that's not something I'd remembered either. :wink:

**Comment by sky5walk** [comment]
Ha, didn't know this feature existed. But, I am a huge fan of the Execute SQL tab.
Keep a bunch of generic update queries in notepad, then paste into Execute SQL and edit as needed. That solves any non-contiguous selection edits. ;)

**Comment by chrisjlocke** [comment]
> But, I am a huge fan of the Execute SQL tab.

That works, and I'd argue for that solution too, but DB4S is meant to be a GUI app, not a command-line app, otherwise, you might as well use sqlite3.exe! ;)

It would be nice if typing the data in one cell copied that to all selected cells - thats what the user would have expected.  This copy pasting nonsense, no-one here knew how it worked! 😆

**Comment by justinclift** [comment]
@proximityblue Have you had a chance to try this out? :smile:

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
