### ISSUE TITLE
"tooltip" text when you hover over schema displays poorly for tables with tons of fields

### ISSUE THREAD

**Issue by mkweskin** [sqlitebrowser/sqlitebrowser#1659]
I'm working on a table with tons of columns (~500). When I hover over the Schema for the table in the "Database Structure" tab, a huge pop up (tooltip?) covers every thing on the screen.

Details for the issue
--------------------

#### What did you do?
Hover over the schema of a table with logs of columns.

#### What did you expect to see?
A truncated pop-up of the schema (or no pop-up_

#### What did you see instead?
A huge window that covers everything on the screen.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( 10.13.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch, that doesn't sound good.

Any chance you could screenshot it? :smile:

**Comment by mkweskin** [comment]
Here you go. (The white boxes are where I cut out some background I don't want public.)
![untitled](https://user-images.githubusercontent.com/1470877/49967735-bad69a80-fef1-11e8-835e-1af66198c82e.jpg)

**Comment by mgrojo** [comment]
Definitely! I'll take a look.

**Comment by mgrojo** [comment]
@mkweskin It will display now a maximum of 512 characters. It will show "..." at the end when truncated. 

The change will be in the next [nightly build](https://nightlies.sqlitebrowser.org/latest/).  Could you confirm whether it's working well for you?

**Comment by justinclift** [comment]
Just checked the latest nightly build for macOS.  The build itself went ok, but it looks like the upload of the .dmg's broke.  I'll re-upload them now.

Gimme a few minutes and the macOS builds should be ready for testing with. :smile:

**Comment by justinclift** [comment]
Re-upload went faster than expected.  They new macOS nightly builds are online now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by mkweskin** [comment]
👍 I checked the nightly build and the truncated text in the schema popup looks good now with that DB. Thanks!

**Comment by justinclift** [comment]
Excellent.  Good stuff again @mgrojo. :smile:
