### ISSUE TITLE
Functiones como DEFAULT de campos

### ISSUE THREAD

**Issue by aMarCruz** [sqlitebrowser/sqlitebrowser#166]
Hola,
¿hay alguna forma de introducir funciones como valor DEFAULT para un campo?
Lo que necesito es el valor de hora UTC como entero con este esquema:

     `timestamp` INTEGER NOT NULL DEFAULT (strftime('%s','now'))

veo el código y parece que no es posible.

Sería útil una ampliación que aceptara esta funcionalidad.
Por ejemplo, Visual FoxPro usa el "=()" para reconocer funciones:

    =(expresion)

en mi caso en particular podría entrar

    =(strftime('%s','now'))

Un cambio en EditTableDialog.cpp (lineas 347 y 348) podría ser este:

    QChar ch = new_value.trimmed().at(0);
    if(!( (ch == '\'' || ch == '"') && new_value.trimmed().endsWith(ch)  ))
    {
        if ( ch == '=' && new_value.trimmed().endsWith(')') && new_value.trimmed().at(1) == '(' )
              new_value = new_value.trimmed().substring_function_I_dont_know(1);  // get rid of '='
        else
        //...

No conozco QT ni C++, pero es algo así.

He modificado el formato para darle claridad al código, también emparejo comillas simples con simples y dobles con dobles (la implementación actual acepta entradas como 'mydefault").

Bueno, la idea está allí.
Gracias.

**Comment by MKleusberg** [comment]
@aMarCruz 
Casi olvidí este problema... :frowning: Pero ahora, si se abra una tabla para modificarla ponemos el signo '=' en el campo default. Si todavía tienes tiempo y ganas a probarlo puedes descargar el próximo nightly build (pero espera hasta mañana): https://github.com/sqlitebrowser/sqlitebrowser#windows

@justinclift Finally, fixed the '=' sign to be included. So this should be fixed now, so we might be able to close this issue soon :)

**Comment by aMarCruz** [comment]
ok, I test it tomorrow

**Comment by justinclift** [comment]
@MKleusberg Awesome. :grin:

**Comment by aMarCruz** [comment]
@justinclift , it is working like a charm :+1:

**Comment by justinclift** [comment]
Excellent!  Thanks for checking and letting us know @aMarCruz. :smile:

Great work again @MKleusberg. :grinning:
