### ISSUE TITLE
Global filter for all fields in Browse Data

### ISSUE THREAD

**Issue by silviulaurentiu** [sqlitebrowser/sqlitebrowser#1662]
For me will be a good point to have a global filter (placed for example somewhere in the right corner) where to insert a text, and this text will be searched in all cells (fields) of table. Space between words will mean the logic and.

For example:

 RowNo | Column 1    | Column 2
 Row  1.   | Text 1111        |  A3
 Row  2.   | Text 2221        |  B1
 Row  3.  | Text 4443        |  C2

If in the global filter input will be inserted: "xt 3"
the result of filtering will show two rows:
Row 1. because it contains "xt" on Column 1 and it also contains "3" in Column 2 
Row 3. because it contains "xt" on Column 1 and it also contains "3" in Column 1

Many thanks!

**Comment by justinclift** [comment]
Interesting concept.  It's a different perspective than I originally suspected you were meaning, and yeah I can see that it would be useful for people. :smile:

For a "more standard" way to find strings in a every field of a table, @mgrojo recently added a Find&Replace dialog: https://github.com/sqlitebrowser/sqlitebrowser/issues/1618#issuecomment-441329413

That *might* be good enough for what you're wanting now, but I'm not sure.

**Comment by silviulaurentiu** [comment]
Many thanks for your response!
Regarding the _Find&Replace dialog_ can be this used also in _Browse Data_ tab? I didn't have success to use this on Browse Data, only in _Execute SQL_ tab
You make a very good job!

**Comment by justinclift** [comment]
Heh Heh Heh, I think you're correct.  I've not used that feature yet, so I didn't realise it was only for the Execute SQL tab.  Oops. :confounded:

**Comment by silviulaurentiu** [comment]
:+1:  No problem :) 
It will be a good idea to have this also implemented in the Browse Data place!
Many thanks!

**Comment by mgrojo** [comment]
How would the SQL query look like for that? I guess that pretty convoluted. 

This might be the job for the [full-text search extension](http://www.sqlitetutorial.net/sqlite-full-text-search/).

**Comment by mgrojo** [comment]
> Regarding the Find&Replace dialog can be this used also in Browse Data tab?

Not currently, but you might want to subscribe to #1608

**Comment by justinclift** [comment]
> How would the SQL query look like for that? I guess that pretty convoluted.

At a rough guess, we'd probably be adding an `OR` clause, duplicated for all the columns in the table.  Something like `WHERE field1 LIKE '%cats%' OR field2 LIKE '%cats%' OR field3 LIKE '%cats%' OR field4 LIKE '%cats%' OR field5 LIKE '%cats%'`.

That's without any thought for regular expressions though.  Not sure if they'd change things. :smile:

**Comment by mgrojo** [comment]
That's the query for one word, but the example contained two.

I think this is what @silviulaurentiu expects:

`WHERE (field1 LIKE '%cats%' OR field2 LIKE '%cats%' OR field3 LIKE '%cats%' OR field4 LIKE '%cats%' OR field5 LIKE '%cats%') AND (field1 LIKE '%dogs%' OR field2 LIKE '%dogs%' OR field3 LIKE '%dogs%' OR field4 LIKE '%dogs%' OR field5 LIKE '%dogs%')`

**Comment by justinclift** [comment]
Yeah, that sounds about right. :smile:

**Comment by MKleusberg** [comment]
@silviulaurentiu I have just added a global filter field, pretty much exactly like you described it. Here's an example screenshot:
![Screenshot_20190916_224111](https://user-images.githubusercontent.com/3153504/64992345-016b8200-d8d4-11e9-97d3-eacb71408a77.png)

Are you still interested in this and want to give it a try? If you are using Windows or Linux, you can download a build with the new feature [here](https://nightlies.sqlitebrowser.org/latest/) by tomorrow.

**Comment by silviulaurentiu** [comment]
Hello,

             I tried and it seems to work well :-)

             Many thanks!

   ______________________________________________________

   Calde salutări / Best regards / Mit freundlichen Grüßen

*   Silviu Doaga*

   Sibiu,  România

   Phone: +40 757 141 932

   E-mail: l <Silviu.Doaga@continental-corporation.com>
aurentiusilviu@gmail.com

**Comment by MKleusberg** [comment]
Thanks for testing :smile: I'm going to close this issue then.
