### ISSUE TITLE
Import CSV numbers started with 0

### ISSUE THREAD

**Issue by silviulaurentiu** [sqlitebrowser/sqlitebrowser#1664]
I have tried to import a CSV file and one field have 0805 number inside. The preview looks ok:
![image](https://user-images.githubusercontent.com/14875058/50004707-b45b2800-ffb0-11e8-8ace-48137d9a633b.png)
but in Browse Data table, the zero "0" was removed from the front of the number and the result is this:
![image](https://user-images.githubusercontent.com/14875058/50004872-26cc0800-ffb1-11e8-85c7-af71f559a4d6.png)

It is interesting that even if the number will be edited manually, so I will place there "0805" value, the 0 is removed when I sort again the table

Inside of CSV file, the data look like these:
![image](https://user-images.githubusercontent.com/14875058/50005254-5fb8ac80-ffb2-11e8-8608-3703fbe5b191.png)

The good news, are that it works if this check button is checked:
![image](https://user-images.githubusercontent.com/14875058/50005441-fedda400-ffb2-11e8-9060-d8d42608b1c7.png)

#### What operating system are you using?

- [.] Windows: ( 7/64bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?
- [.] 3.11.0-beta3*
#### Did you also
- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
:wink:

We added that "Disable data type detection" option exactly because it's sometimes hard to correctly guess the type.  So, kind of thinking there's not really anything more to do for this issue?

**Comment by silviulaurentiu** [comment]
The solution could be simple: when the CSV file is imported, read the data from each column as you already do, and you take the decision to set it INTEGER only if each cell doesn't start with "0" value. If the value starts with "0" but the is followed by the point (e.g: 0.123) that means that the value is NUMERIC. Otherwise, the column will be set as TEXT. 
In this way the check button "Disable data type detection" can be removed.

**Comment by silviulaurentiu** [comment]
Or for each column check if TEXT(cell) == NUMERIC(cell) and if for all cells from the column the values are equal, then the column is NUMERIC. For sure, after this you can check to see if the column is NUMERIC, INTEGER or REAL.

**Comment by sky5walk** [comment]
You did not show the schema for each column?
If Package = INT, then 0805 -> 805.
If Package = TEXT, then 0805 -> "0805"
Why does "Disable data type detection" button exist, when we know the schema?
Meaning, how can you store 0805 into an integer or double column?

**Comment by chrisjlocke** [comment]
The other solution is to have 'correct' CSV file.  The CSV should include "0805" and not 0805. "0805" would be interpreted as a string then, which is what you want.  The same is for UK telephone numbers, as these all start with 0 as well, and cannot be stored in a numeric field.

**Comment by silviulaurentiu** [comment]
Many thanks guys!

**Comment by chrisjlocke** [comment]
Closing, as not implicitly a DB4S issue....

**Comment by justinclift** [comment]
> Why does "Disable data type detection" button exist, when we know the schema?

Well, until (somewhat) recently, when we import from CVS we'd just set every field to `TEXT` type.  For non-TEXT types, people would then manually update the type info after the import.

We added automatic type detection as a way to reduce the manual effort needed.  For larger sized databases with many columns, that "change the data type fields manually afterwards" step takes a long time.  eg [this data set](https://dbhub.io/justinclift/National%20Statistics%20Postcode%20Lookup%20UK.sqlite) is a decent example

That being said, it makes sense for us to continue refining the auto-detect code. :smile:

> Or for each column check if TEXT(cell) == NUMERIC(cell) ...

Interesting thought.  That might be doable.  I **think** it would be more a case of checking if TEXT(cell) == DETECTED_TYPE(cell).  If they're equal, then we might as well use the detected type.  If they're not equal though, that gets interesting:

* Do we change the field type for the entire column, or
* Do we change the field type just for this one cell (row) of data?

Hmmm... maybe some kind of threshold's would be needed?  For example, if a field mostly has integers in it, but someone has thrown a few text strings in it as well as some images, I'm not (yet) sure of the right way to handle it. :wink:

We'd probably need to think it through more, and I'm personally I'm not real awake atm. :grin:

**Comment by silviulaurentiu** [comment]
A lot of thanks Justin for your time! 
It seems that you get the idea; I made reference to auto-detect code that is implement in the backside of application; for sure there are many ideas to implement this. You decide if this could be useful or not.
