### ISSUE TITLE
Magellan vulnerbility affecting FTS3 module in SQLCipher (SQLite >3.26 unaffected)

### ISSUE THREAD

**Issue by vbjay** [sqlitebrowser/sqlitebrowser#1667]
Be aware of https://www.zdnet.com/article/sqlite-bug-impacts-thousands-of-apps-including-all-chromium-based-browsers/

**Comment by justinclift** [comment]
Thanks @vbjay.  Personally, I'm keeping an eye on the SQLCipher forum post about it:

&nbsp; &nbsp; https://discuss.zetetic.net/t/magellan-vulnerbility/3290

We'll need to see what happens there, as we include the FTS3 module in DB4S so it affects us. :smile:

**Comment by justinclift** [comment]
SQLCipher 4.0.1 should be released next week, which we'll update all of our pieces to use. :smile:

**Comment by vbjay** [comment]
Awesome. Thanks for such an awesome tool.

**Comment by karim** [comment]
The latest nightly is now built with SQLCipher 4.0.1, so this can be closed.

@vbjay Thanks for bringing this to our attention. :smiley:

**Comment by justinclift** [comment]
As a data point, the patch to fix the vulnerability was also in SQLite 3.25.3.
