### ISSUE TITLE
Resizing column width temporarily corrupts view

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1668]
Details for the issue
--------------------
I think this is related to #1658 recently raised, with text in multiple lines in a cell.  Or the updated Qt version.

On a newly selected table (so once you've corrected the quirk, it doesn't occur again) if a column is resized (even slightly) the 'alignment' gets slightly corrupted so the row numbers don't line up with the rows.

![image](https://user-images.githubusercontent.com/7872218/50086655-9fbba180-01f5-11e9-9a04-6ed9b760d2cb.png)

#### What did you do?
Resize a column

#### What did you expect to see?
No corruption.

#### What did you see instead?
Corruption.

Useful extra information
-------------------------
Here is a screencast.
https://screencast-o-matic.com/watch/cFlbl1rG8D

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10x64___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] Version 3.11.99 (Dec 17 2018)
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Hmm.  This might be a Windows thing.  Just pressed <kbd>Alt</kbd>+<kbd>Tab</kbd> which refreshed the screen, and everything seems OK again.  When 'corrupted', if you click 'Help' (to display the 'Help' and 'About' dialog) suddenly all appeared well again.
So easily sorted, but someone somewhere will moan about it....

**Comment by mgrojo** [comment]
Did this also occurred with Qt 3.12.0 and has disappeared switching to 3.11.3?

If it has, it seems to be the same underlying issue than #1658.

**Comment by chrisjlocke** [comment]
Yes, can confirm this doesn't occur with the latest nightllies, so with Qt 5.11.3

**Comment by justinclift** [comment]
Hopefully Qt 5.12.1 fixes the issues we've hit.

On the other hand, we should probably fill out some bug reports on the Qt bug tracker, just in case.

I'm trying to motivate myself to do so, but failing.  Anyone else interested in getting it done? :smile:

**Comment by chrisjlocke** [comment]
> we should probably fill out some bug reports on the Qt bug tracker

Reading the threads of doom you posted, I may as well post pictures of my dog there.... ;)
I can post the bug reports accordingly.

**Comment by mgrojo** [comment]
This seems to be fixed, probably at the same time as #1658.
