### ISSUE TITLE
[Feature Request-Execute SQL] Allow bottom editor of Execute SQL tab to grow taller.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1670]
While debugging my SQL queries, I seem to make a lot of mistakes.
Thankfully, the errors are described in the bottom editor gadget. 
But, the height of this editor is limited to only a few lines and I'm forced to constantly click and scroll to the bottom on each iteration of my edit. :((
Please allow this editor to grow to the full height of the window.

--------------------------

**Comment by mgrojo** [comment]
Yes, I think we can let that grow to the maximum height allowed by the minimum height of the other two panesl. Maybe we wrote less information there previously and it was considered senseless, but I think it can be changed without paying any price.

Note that you can also use the SQL Log pane to get the history of all the SQL executions done by the user (erroneous or not).

**Comment by sky5walk** [comment]
Cool, yes, the Execute SQL results editor always has more information forcing a scroll to bottom with each execution.
I rarely use the SQL log since that accumulates all SQL actions. It is important, but only when something is really really wrong!

**Comment by mgrojo** [comment]
@sky5walk It's now as suggested and you'll have it in tomorrow's nightly. I haven't seen any problem.

**Comment by sky5walk** [comment]
Awesome! I will send the scrollbar on vacation. :)

**Comment by justinclift** [comment]
Heh Heh Heh.

Kind of suspecting we'll be following up the 3.11.x series with a 3.12.0 release not too long after. :wink:

**Comment by sky5walk** [comment]
Just tried the extended Execute SQL feedback editor and it works great.
I can probably avoid scrolling for 80% of my queries.
This is a good compromise as I prefer more time spent on a future query builder... 😈

**Comment by sky5walk** [comment]
Sorry, to ask after closing this topic...
I thought of another way to avoid scrolling so often.
Is it easy to place the last result line at the top of the results window?

Example query: (Imagine it is much longer than this 😈 )
```
FROM
Execution finished without errors.

-- At line 11:
INSERT INTO T (a, b, c, d)
VALUES
  (3, 1, 42, -7),
  (3, 2, 43, -8),
  (3, 3, 44, -9);
-- Result: query executed successfully. Took 0ms, 3 rows affected
```
```
TO
-- Result: query executed successfully. Took 0ms, 3 rows affected

-- At line 11:
INSERT INTO T (a, b, c, d)
VALUES
  (3, 1, 42, -7),
  (3, 2, 43, -8),
  (3, 3, 44, -9);
Execution finished without errors.
```

**Comment by justinclift** [comment]
> Is it easy to place the last result line at the top of the results window?

@mgrojo What do you reckon? :smile:

**Comment by beRto-** [comment]
I like this suggestion, but would only suggest that "Execution finished without errors." also should come before the SQL. Knowing there were no errors is also new (and very useful) information when a query completes.

**Comment by sky5walk** [comment]
My assumption was "Execution finished without errors." is redundant when the top states:
"-- Result: query executed successfully. Took 0ms, 3 rows affected"

**Comment by mgrojo** [comment]
> My assumption was "Execution finished without errors." is redundant when the top states:
"-- Result: query executed successfully. Took 0ms, 3 rows affected"

Yes, I agree. In fact I don't know why @MKleusberg added the phrases  "Execution finished with(out) errors." in #1575. Maybe because some result messages aren't so clear as "query executed successfully" although the background colour was also added for helping on that regard.

My only concern about changing the order to:
```
-- Result: query executed successfully. Took 0ms, 3 rows affected
-- At line 11:
INSERT INTO T (a, b, c, d)
VALUES
  (3, 1, 42, -7),
  (3, 2, 43, -8),
  (3, 3, 44, -9);
```
is that the same message goes to the SQL Log with all the executed statements. I understand the log more easily if the query precedes the result. I'm unsure also, about whether both messages (log and results panel) should differ or be the same.

**Comment by sky5walk** [comment]
Wow, thanks for the history...
I would strongly suggest dropping the whole results log since we already have the results window to view.
As you mention, the SQL log is redundantly populated!!
Reduce the clutter and continue to report to the SQL log, 
but ONLY report to the results grid/editor.
SUCCESS = populate results grid.
FAIL/ERROR = populate results grid.  <-- since the results grid will be empty in this case.

**Comment by justinclift** [comment]
@sky5walk That's confusing for me, as it seems to be contradicting itself?  Is there a typo in it somewhere?

> I would strongly suggest dropping the whole results log since we already have the results window to view.
> Reduce the clutter and continue to report to the SQL log ...

**Comment by sky5walk** [comment]
Yeah, I don't code with qt lib, so I don't know the gadget class names?
Summary: 
  mgrojo stated the "sql log" captures the "execute sql" activity already.
I'm suggesting to drop the 3rd bottom editor in the execute sql panel entirely.
Just output successful queries to the 2nd grid
And ..
Output failed queries to the same grid.
This removes the whole scrolling and partitioning of 3 elements that by themselves are never tall enough.

**Comment by justinclift** [comment]
Thanks.  Understanding has occurred. :smile:

**Comment by beRto-** [comment]
@justinclift looks like this didn't make it into 3.11? :( Is there an ETA?

**Comment by justinclift** [comment]
Some pieces are already in our nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Those will be in 3.12.0 - our next major release - which is probably only a few months away.  We had a bunch of technical debt we needed to get through for the 3.11.0 release, which is why it took so long for that one.  In theory (!) our next releases shouldn't be so far apart. :smile:

**Comment by beRto-** [comment]
:(

Oh, I was hoping this was a minor 3.11.1 regression fix! 

Previous db4s put the important query result info (number of rows and execution time) front and centre. So I thought it would be simpler.

Anyways, thanks for considering. And congrats on the new release!

**Comment by justinclift** [comment]
@mgrojo Is this patch suitable for adding to the `v3.11.x` branch?

**Comment by mgrojo** [comment]
Added to the `v3.11.x` branch.

**Comment by justinclift** [comment]
This still has stuff needing to be done, yeah?  eg Don't close it yet?

**Comment by sky5walk** [comment]
Ok, I propose dropping the redundant SQL log in the Execute SQL tab altogether.
The display is noisy and compresses available workspace. I am forced to minimize the view on multiple locations. Using the built-in SQL log with User selected is far superior. 🙌 
It has syntax highlighting and auto scrolls to bottom of gadget.

**Comment by chrisjlocke** [comment]
Can 'o worms, but this is slightly related the recent 'can we knobble the import successful dialog' request.
It would be handy if running the SQL generated errors, that a little notification bar would pop up, otherwise, it was nice 'n quiet.  Or even keep the panel, but hide it if its not needed.  Kind of 'when the user runs a query, hide the log panel ... then .... if there was an error, show the log panel'.

**Comment by sky5walk** [comment]
Yes, it would be helpful to promote the existing SQL log more prominently.
I make it full height and a standalone tab on the right side.
Though unpinned is less constricted if you have multiple monitors.

**Comment by scottfurry** [comment]
That's the catch... The existing SQL log contains *everything against the currently opened database*. Every action taken by the user, whether it is performing a Foreign Key Check or compacting the database, is recorded there, just not necessarily the results. It is an accumulation of SQL actions against the database, as a whole.

The Log below the SQL tab is for *that statement* the user executed and is contained in the SQL text widget above. The statement could be some set of insert or select queries. This is analagous to the output from the command line if the user attempted to execute the same statement.

Granted, the SQL tabs can be a bit noisy. I can see @sky5walk what you're trying to achieve in cleaning up or refining the display to the user, but I'm not convinced of utility of the proposed solution.

**Comment by sky5walk** [comment]
If you keep the main SQL log visible, it auto-scrolls. If your last action was Execute SQL, it is in effect identical and superior to the small, isolated Execute SQL log. Look to the syntax highlighting and the number of rows returned. All there without rearranging triplet windows scrollbars.

**Comment by scottfurry** [comment]
@sky5walk: Just so that I can fully appreciate the situation, could you provide a screen shot of what you see, please?

**Comment by sky5walk** [comment]
Here is an example of repeated queries and intentional errors. Notice the SQL log to the right is auto-scrolled to the bottom with each new query. 🤔 
![image](https://user-images.githubusercontent.com/13093122/57488140-37428f00-7280-11e9-9095-0871d01ef3fb.png)

**Comment by scottfurry** [comment]
One thing that seems to be missing from the log on the right is the result. I expected to see messages saying "[some number] rows affected" for insert queries or "Result: 36255 rows returned in 240ms
At line 1:" for select queries.

I can see your issue the logging (accumulating and overall) on an open database that is given in the right log window. However, the complete results(and/or errors) gets displayed in the tab (shown in the attached image as minimized). I find that result display quite useful, especially when debugging queries or table manipulations.

I don't have an easy answer to your issue. I can see a couple of things that could be done to clean up logging(which window and log window settings) but I can't advocate the radical overhaul being advocated.

**Comment by sky5walk** [comment]
Yeah, my image was showing the scrolling and syntax highlighting and use of space. It was intended for you to duplicate and "see for yourself". If you had, you would notice the same information is present in both logs. 💡 
There is nothing radical in reducing noise and redundancies especially in space constrained gui's.
Dropping the Execute SQL log would reduce DB4S code burden and allow the user to see more of their data with less scrolling!

**Comment by scottfurry** [comment]
![DB4S_Ebuildology](https://user-images.githubusercontent.com/6686571/57558818-7c2bfb80-733c-11e9-8f81-23046f59f4f2.png)
This is what I see executing DB4S. I actually prefer, overall, the layout. I collapsed the Cell Editor letting the DB log grow upwards. While I agree that there is some "noise" in the right SQL Log that could be reduced, I find this rather utilitarian. I see the results and logging of the last executed SQL Statement. This, to me is important. As a bonus, by closing the cell editor (selected in the View Menu), the remaining log window assumes full height to the right and this is "remembered" across open/close   of DB4S(does this address #1889?).

Again, I'm not convinced. This seems like a discussion about what is the "best" work flow. Short answer is... it depends on the user.

**Comment by sky5walk** [comment]
No, you did not select 'USER' for the right side SQL log. You have APPLICATION selected, which is not the focus of this discussion.

**Comment by scottfurry** [comment]
Okay. There's several cumulative logging views available.

**Comment by sky5walk** [comment]
Ok to close with current collapsing SQL log windows.
