### ISSUE TITLE
segfault on TIMESTAMP typed tables

### ISSUE THREAD

**Issue by RafTim** [sqlitebrowser/sqlitebrowser#1671]
Details for the issue
--------------------

#### What did you do?
1. Create new Database
2. exec SQL:
```
CREATE TABLE `Foo` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`date`	TIMESTAMP DEFAULT current_timestamp
);
```
3. Switch to database structure, click "modify" table Foo.
4. If no immediate crash, click on TIMESTAMP type

#### What did you expect to see?
Selection of Timestamp type

#### What did you see instead?
segfault

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: (  distro: Arch Linux )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [X] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
v3.10.1 is quite old now.  Have you tried the latest alpha version?
https://github.com/sqlitebrowser/sqlitebrowser/releases

**Comment by RafTim** [comment]
Obviously, I didn't as I didn't check the mark for it.
But I managed to build it and it seems to be fixed

**Comment by justinclift** [comment]
Excellent.  The new release should be out in a few days - we're in the final preparation parts now. :smile:
