### ISSUE TITLE
Default App?

### ISSUE THREAD

**Issue by aaronnm2016** [sqlitebrowser/sqlitebrowser#1674]
I installed your app today, and I was persistently trying to figure out how to get it installed as a 'Default App' and I just cannot get Windows to accept this file.  Does Windows not like this file? Is it infected or something?

I'll admit that I"m the one that couldn't figure out how to get the app set as Default.  I just can't find some stuff in Windows any more, and when I go to run it, it just doesn't work entirely.

I am using a non-standard operating system.  It is Windows Server 2019.  As I am a database guy, I almost always do Windows Server on desktops, laptops... that sort of thing.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Windows Server 2019 eh?  Hopefully won't be a problem, though we'll probably likely need some of our Windows experienced people to assist.

Most of them are in EU(-ish) timezones, so there could be a bit of a wait. :wink:

**Comment by karim** [comment]
> I was persistently trying to figure out how to get it installed as a 'Default App' and I just cannot get Windows to accept this file.

"Default App" for what? For opening a specific (database) file? Windows should show you a dialog to select a default app to open unknown files.

You can also go to `Control Panel > Default Programs > Set Associations` to change your selection.

Select a file type then click `Change program...` and it will show you the same dialog that should appear whenever you open an unknown file.

![1674-3](https://user-images.githubusercontent.com/8761081/50262487-42ed0080-041a-11e9-9ba0-6b3a4a0f6387.jpg)

Click *More options* to select a different application.

![1674-4](https://user-images.githubusercontent.com/8761081/50262405-dffb6980-0419-11e9-8c03-65bdbf646fe3.jpg)

The screenshots are from Windows Server 2012 (a VPS) but it should be the same on different versions of Windows.

**Comment by chrisjlocke** [comment]
>  and when I go to run it, it just doesn't work entirely.

Can you give a bit more detail on what doesn't work?  Do you get an error displayed?  What does the error say?  If not, what result were you expecting?  What happened instead?  Can the error be repeated?  Does it always happen?
To investigate issues, its helpful if we can recreate them.  To that end, 'it doesn't work' just isn't helpful.

**Comment by justinclift** [comment]
Closing this due to lack of response.
