### ISSUE TITLE
[Suggestion] Don't rebuild table if field added

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1677]
Details for the issue
--------------------
Testing on another issue confirmed the process when a table is modified.  The existing table is modified, a new table is created, data is copied across, the old table deleted and finally the new table renamed.  However, if a field is simply added to the end of the table, this process is unnecessary, and if the table is large, wastes a lot of time.  If DB4S knew that in the 'Edit Table' dialog that 'remove field', 'move up' and 'move down' buttons weren't pressed (so the schema was only minorly modified) it could skip the superfluous fluff.

#### What did you do?
add a field

#### What did you expect to see?
the table edited

#### What did you see instead?
extraness which maybe didn't have to happen

Useful extra information
-------------------------
Heres a full log.
```ALTER TABLE "main"."audit" ADD COLUMN 	"Field8"	INTEGER
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("view_contactsData2");
PRAGMA "main".TABLE_INFO("view_contactsData");
PRAGMA "main".TABLE_INFO("view1");
PRAGMA "main".TABLE_INFO("v_meetings");
CREATE TABLE "sqlb_temp_table_1" (
	"au_id"	INTEGER,
	"au_section"	TEXT,
	"au_sectionReference"	INTEGER,
	"au_userId"	INTEGER,
	"au_date"	TEXT,
	"au_details"	TEXT,
	"au_notes"	TEXT,
	"Field8"	INTEGER,
	PRIMARY KEY("au_id")
);
INSERT INTO "main"."sqlb_temp_table_1" ("au_date","au_details","au_id","au_notes","au_section","au_sectionReference","au_userId") SELECT "au_date","au_details","au_id","au_notes","au_section","au_sectionReference","au_userId" FROM "main"."audit";
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = '1';
DROP TABLE "main"."audit";
ALTER TABLE "main"."sqlb_temp_table_1" RENAME TO "audit"
PRAGMA defer_foreign_keys = '0';
PRAGMA database_list;
[etc]
```

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
Who cares?

#### What is your DB4S version?
Nightly.

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

No.

**Comment by justinclift** [comment]
Sounds like a decent idea to me. :smile:

**Comment by MKleusberg** [comment]
Hmm, as in #1686 this works fine for me. If we're using the same SQLite version, this might be a more general issue in our code then.

**Comment by MKleusberg** [comment]
This might be a part of the issue in #1725. So it's worth trying this one again too with tomorrow's nightly build :smile:

**Comment by chrisjlocke** [comment]
It is indeed.  Can confirm only 1 `ALTER TABLE` statement is performed.
Thanks! 🌹

**Comment by MKleusberg** [comment]
Awesome :smile:
