### ISSUE TITLE
Windows 10 Security issue: Unknown Publisher

### ISSUE THREAD

**Issue by cherie0202** [sqlitebrowser/sqlitebrowser#1681]
Details for the issue
--------------------

#### What did you do?
Trying to install DB.Browser.for.SQLite-3.11.0-beta3-win64.msi

#### What did you expect to see?
Normal installation & pop-up to uninstall old version

#### What did you see instead?
Error from Microsoft in-build anti-virus : Windows Defender

Windows Defender SmartScreen prevented an unrecognized app from starting. 
Running this app might put your PC at risk.

App: DB.Browser.for.SQLite-3.11.0-beta3-win64.msi 
Publisher:  Unknown publisher 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ Win 10 Single Lang (OS Build - 17134.472)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
![db browser for sqlite-3 11 0-beta3-win64](https://user-images.githubusercontent.com/23432462/50360255-79935a00-0585-11e9-9ebe-44b5f7face7f.PNG)

**Comment by karim** [comment]
This could be related to the fact that the installer isn't signed ... yet.

Right-click on the MSI file and select Properties, then click Unblock. More info in this issue #1029 and the solution in this comment https://github.com/sqlitebrowser/sqlitebrowser/issues/1029#issuecomment-305321967

**Comment by justinclift** [comment]
> This could be related to the fact that the installer isn't signed ... yet.

Good point.  That still needs to be done.  I need to provide info to @MKleusberg so the cert can be purchased.  Will get that done today sometime. :smile:

**Comment by chrisjlocke** [comment]
@justinclift - did you need a \**cough*\* reminder about this?

**Comment by justinclift** [comment]
Nope, that's been done, and @MKleusberg [ordered the certificate yesterday](https://github.com/sqlitebrowser/sqlitebrowser/issues/1656#issuecomment-453831556).

In theory we should get the thing (it has a hardware element) some time in the next few days, and we'll be able to figure it out from there. :smile:

**Comment by chrisjlocke** [comment]
Cool.  Was just sifting through some older issues, so seeing what had been dealt with.

**Comment by MKleusberg** [comment]
Shall we close this issue then? For the 3.11.0 release we are now using a signed binary :smile:

**Comment by MKleusberg** [comment]
Let's just close this as there was no update for a long time and it seems to be solved :smile:

**Comment by gaw89** [comment]
I ran into this issue today with the ZIP version of release 3.12.2 64 bit.
![image](https://user-images.githubusercontent.com/20972961/119666203-292e1f80-be03-11eb-8521-e95331593a01.png)

Any ideas?

**Comment by chrisjlocke** [comment]
Interesting.  I thought the zip files were signed.  I thought I extracted the signed files from there to put them in the MSI version.
When you click on 'More info' does it just moan that it's new?  3.12.2 was only recently released, so it might be a 'false alarm'.  I can't get that dialog on my laptop, but it might be because I run the nightly a lot, so it 'recognises' I've run that .exe frequently.

**Comment by chrisjlocke** [comment]
I've just downloaded 3.12.2 64-bit version, and the .exe looks signed OK.
![image](https://user-images.githubusercontent.com/7872218/119670658-fac73900-be30-11eb-8b3c-3905173085f0.png)

**Comment by gaw89** [comment]
I clicked more info and was able to continue.  Now when I open it, the warning no longer comes up.  I am trying to get the exact message that appeared when I clicked more info - it was something about an unrecognized publisher and had the name of signer like in your screenshot.

**Comment by gaw89** [comment]
I got it.  Here's what I see when I click more info:
![image](https://user-images.githubusercontent.com/20972961/119672157-5e893c00-be08-11eb-82a7-601eeb6b8744.png)

**Comment by gaw89** [comment]
No problem.  Just wanted to make sure your team was aware.  I'd hate to see people not use this package because of some overzealous virus filter.

Fantastic work on the DB Browser!
