### ISSUE TITLE
Little Window for searching similar queries

### ISSUE THREAD

**Issue by khashayarxy** [sqlitebrowser/sqlitebrowser#1682]
Hey, umm... I noticed that in the latest versions there is a feature that if DB has queries less than 1000 it shows a little window like this image. It's very helpful and I like it. but here's the thing... it stops showing that after 1000 queries. is there any chance you could add this feature for any amount of queries?
![screenshot 3](https://user-images.githubusercontent.com/42047526/50380798-91073b80-0688-11e9-8ddc-211f51e33479.png)

**Comment by justinclift** [comment]
When you say "has queries less than 1000", are you meaning "has rows less than 1000"? :smile:

**Comment by khashayarxy** [comment]
> When you say "has queries less than 1000", are you meaning "has rows less than 1000"? 😄
I wanted to say it more professional 😂😂😂

**Comment by justinclift** [comment]
No worries. :smile:

"Queries" are things like `SELECT stuff FROM sometable`.  So, it was the right idea, just the wrong word. :smile:

**Comment by mgrojo** [comment]
@khashayarxy You can change that limit in **Preferences > Data Browser > Row count threshold for completion**. With big tables the completion can become a bit laggish and hence the limit.
