### ISSUE TITLE
Program Files Path

### ISSUE THREAD

**Issue by JanPichl** [sqlitebrowser/sqlitebrowser#1683]
Hi,
portable version of DB Browser foe SQLite do not support my standard patch for portable aplication.

This path is: "C:\Program Files (Portable)".

Thank you for the solution.

**Comment by justinclift** [comment]
Hi @JanPichl, that's a bit unclear.

As a idea, since it seems like your primary language is something other than english... what is your preferred language?

Asking because our Community has people from many different parts of the world.  There might be someone who has the same primary language, so would be easier to communicate with. :smile:

**Comment by justinclift** [comment]
Ahhh, your location says "České Budějovice".  So guessing Czech.

I'm not sure if anyone in our team knows České Budějovice.  Hmmm, maybe @MrJiggers has time to assist? :smile:

**Comment by justinclift** [comment]
Ahhh.  Maybe the nightly builds .zip file will work instead?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by JanPichl** [comment]
Thank you for your answers and sorry for my English. I am begginer :)

If the Portable version is running on the path "C:\Program Files (Portable)". Application throwed exception Dialog with text  "DB Browser for SQLite Portable cannot be run from inside C:\Program Files. This location is for standard local software only. Please use this application from another location.

Standard system pathes is "C:\Program Files" and "C:\Program Files (x86) . My Idea "C:\Program Files (Portable)" is not a standard system path.

**Comment by karim** [comment]
Where did you download this portable version? From https://portableapps.com/ ?

**Comment by JanPichl** [comment]
> 
> 
> Where did you download this portable version? From https://portableapps.com/ ?

My version is download from  [https://sqlitebrowser.org/](url)

**Comment by karim** [comment]
Can you try downloading the new .zip file?

32-bit: https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip
64-bit: https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

Select either 32-bit or 64-bit based on your Windows version.

**Comment by justinclift** [comment]
Ahhh. It also sounds like the Portable version has some changes added to it by the PortableApps volunteers. :smile:

If you ask on their forums, they should have more knowledge why the error is happening, and how to fix it:

&nbsp; &nbsp; https://portableapps.com/forums

**Comment by JanPichl** [comment]
> 
> 
> Can you try downloading the new .zip file?
> 
> 32-bit: https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip
> 64-bit: https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip
> 
> Select either 32-bit or 64-bit based on your Windows version.

It works for me. 

Thanks.

**Comment by chrisjlocke** [comment]
> Can you try downloading the new .zip file?

Just a note that the .ZIP file is 'portable' in that it doesn't require installing, but its not portable in the sense that it writes to the registry / hard drive for settings and configurations.
