### ISSUE TITLE
Main window minimum window size reduced

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1685]
Details for the issue
--------------------
With the latest nightlies (19 Dec onwards?) the main window can be made smaller than usual.  This results in the table combobox becoming quite small and unusable.

![image](https://user-images.githubusercontent.com/7872218/50396062-502e2600-075f-11e9-9400-34f03cfdadeb.png)

We've obviously been playing with different Qt builds, but don't know if this has a bearing on it.

#### What did you do?
Resized the window

#### What did you expect to see?
The window wouldn't normally resize beyond a set size

![image](https://user-images.githubusercontent.com/7872218/50396093-7ce23d80-075f-11e9-901d-4a1b590994f3.png)

#### What did you see instead?
The window went smaller than normal.  An 'ooh' was expressed.

![image](https://user-images.githubusercontent.com/7872218/50396102-91263a80-075f-11e9-922a-e5319bb6c524.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

Nightly (24 Dec)

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
The combobox also now 'fills the space'.  So before:

![image](https://user-images.githubusercontent.com/7872218/50396485-52de4a80-0762-11e9-9c32-a7656130582a.png)

and now:

![image](https://user-images.githubusercontent.com/7872218/50396511-71dcdc80-0762-11e9-887e-42cf75a070b8.png)

not a major problem, but its a bit big if you go full screen!

![image](https://user-images.githubusercontent.com/7872218/50396560-a3ee3e80-0762-11e9-967b-a81ce1568f6f.png)

**Comment by justinclift** [comment]
Guessing here, but kind of thinking it's probably a side effect of the in-progress changes being done for #1675.

It's good to mention them, so @mgrojo is aware of the changes as the experimentation progresses. :smile:

**Comment by chrisjlocke** [comment]
Indeed.  Presumed it was related to the Qt kerfuffles.... just seems a weird side effect.

**Comment by mgrojo** [comment]
This is a consequence of #1678 (better size policy for translations with long texts and not so high resolutions). In order to have wider range for growing and shrinking the docks, the PR set a minimumExpanding policy with a minimum of 50 pixels. I think we can set a maximum, because using so much is useless (I presume nobody has so long table names). But is there really a problem with the minimum? The user can freely make it bigger, so setting a bigger minimum brings no advantage in my opinion. We can ask also @zvova7890 for his opinions on both issues (minimum and maximum).

See also my related PR:  #1684, that tries to improve the situation by changing buttons with texts to buttons with icons (among other minor changes). I'd also like to hear your opinions on that.

**Comment by zvova7890** [comment]
About minimal size of combobox - before that, you can't make window as small as you do now. So, if it unusable - make window size is a little bigger. About maximum, as for me, it's not a problem... and as i known sqlite table names has no limitation for length.

**Comment by mgrojo** [comment]
@chrisjlocke PR #1684 is merged and now the table combo-box does not shrink beyond a certain width, while the window size can still be adjusted with enough freedom.

**Comment by chrisjlocke** [comment]
Will check that tomorrow - thanks!

**Comment by MKleusberg** [comment]
@chrisjlocke Did you check it 'tomorrow'? :stuck_out_tongue:

**Comment by mgrojo** [comment]
@chrisjlocke ping :smile:

**Comment by chrisjlocke** [comment]
Hey, come on ... a six month response time is pretty good! ;)
Yes, the minimised combobox has been corrected, and I /was/ going to say the combobox is still small as before...

![image](https://user-images.githubusercontent.com/7872218/90099567-b56acc80-dd32-11ea-8faa-eb111fe6ae6a.png)

Makes identifying tables difficult ... BUT that's due to my screen layout.  Texts in the icons, and edit database cell window on the right.  Sort that out, and the combobox does indeed stretch out.  

![image](https://user-images.githubusercontent.com/7872218/90099754-185c6380-dd33-11ea-8ee7-3183954faadd.png)

After six months (why does a change take this long to implement???!!!!  😉 😉 ) I can close this.  ❤️   Thanks guys!
