### ISSUE TITLE
Database file not released after modifying structure

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1691]
Details for the issue
--------------------
This might be a Windows thing, so ideally, if someone can confirm on another OS?  I presume as MacOS is based on Linux, it won't affect that or the specific Linux builds - @justinclift recently taught me about file locks on Linux ... or the lack thereof... 😉 

If a database structure is modified (and even if it is then cancelled) and the database closed in DB4S, the file cannot be renamed/moved, as DB4S still has a lock open on it.  Even if another database is opened (and subsequently closed) the original database is still held open.

![image](https://user-images.githubusercontent.com/7872218/50475594-3be76480-09bd-11e9-8aa7-70a087b152d1.png)

Mainly logging in case its an indication of a file handling issue which could grow over time as DB4S is being used.

#### What did you do?
Open database.  Go to 'Database Structure' tab.  Modify a table.  Add a new field.  Cancel out of all dialogs.  Close database.  Try and rename file.

#### What did you expect to see?
The file renamed.

#### What did you see instead?
An error that DB4S still had the file open.

Useful extra information
-------------------------
Here is a screencast.
https://screencast-o-matic.com/watch/cFltQprNT6

0:10 - The file is open in DB4S, and the renaming fails as expected.
0:17 - The file is closed in DB4S and the renaming succeeds as expected.
0:30 - The file is opened in DB4S and the table modified.
0:37 - A field is added, but cancelled.  The database is then closed
0:50 - The file cannot be renamed
0:55 - Another database is opened in DB4S and closed.  This can be renamed, but the original file is still locked and cannot be renamed.
1:16 - DB4S is closed, and the original file can now be renamed.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] Nightly from 24 Dec 2018
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Does the same happen for you with a very small database? I'm asking because the only explanation I can come up with right now is that some background thread is still running and accessing the file.

**Comment by chrisjlocke** [comment]
Looking at what files are open and by who, could it be a Qt thing?

![image](https://user-images.githubusercontent.com/7872218/50476569-81f1f780-09c0-11e9-9537-c6994ef55ec7.png)

**Comment by MKleusberg** [comment]
Turns out it was a plain and simple error in our code :wink: In [this function](https://github.com/sqlitebrowser/sqlitebrowser/blob/730b494ce7e17e5618c9bd8774683c0353c73138/src/sqlitedb.cpp#L1042) (which is called when editing an existing table, besides some other places) you can see that the ```stmt``` variable is allocated by the ```sqlite3_prepare_v2``` call. But we only call ```sqlite3_finalize``` on it if we got any results from ```sqlite3_step``` which we didn't in this case  (which is probably a separate issue we should look into). And when there is even a single unfinalized statement, SQLite doesn't actually close the database - DB4S just pretends it did :wink:

**Comment by chrisjlocke** [comment]
Can confirm this is now resolved.  Thanks @MKleusberg for the prompt fix.

**Comment by justinclift** [comment]
If the bug is in 3.11.x, then we should definitely fix it there too. :smile:
