### ISSUE TITLE
Nightly Builds bug: main tabs not shown

### ISSUE THREAD

**Issue by khashayarxy** [sqlitebrowser/sqlitebrowser#1692]
So today I installed the latest version of nightly builds. I was expecting bugs but not this. It shows nothing.

![test](https://user-images.githubusercontent.com/42047526/50516077-e9da3800-0abd-11e9-9ce0-c5e259f32012.png)

**Comment by khashayarxy** [comment]
@mgrojo Thanks man, I like the new version. especially that dragging and closing tabs feature.

**Comment by mgrojo** [comment]
@khashayarxy It should be solved in tomorrow's nightly build. I hope everything is now ok by then. Please, close this issue as soon as you have confirmed it.
