### ISSUE TITLE
Some parts of the app are hard to read with dark theme

### ISSUE THREAD

**Issue by ngosang** [sqlitebrowser/sqlitebrowser#1695]
### Details for the issue
Some parts of the app are hard to read with dark theme. I'm using last version of KDE Plasma.

![image](https://user-images.githubusercontent.com/10577978/50540012-5de21200-0b8a-11e9-8efc-caad8a8e7a4d.png)
![image](https://user-images.githubusercontent.com/10577978/50540018-6c302e00-0b8a-11e9-8fcb-059d7def0c4b.png)

### Useful extra information
Versión 3.10.1
Versión de Qt 5.10.0
Versión de SQLite 3.21.0

**Comment by mgrojo** [comment]
@ngosang Our latest release (still in beta phase) has improved the support of dark themes. You can install it from https://github.com/sqlitebrowser/sqlitebrowser/releases or https://github.com/deepsidhu1313/sqlitebrowser/releases/download/continuous/DB_Browser_for_SQLite-3.10.1-219-4bfcf8b-x86_64.AppImage (AppImage for Linux).

The beta has the following improvements:

*   Avoid any hard coded colours and query system colours wherever possible. In practice this adds support for dark themes (#1324)
*   Fix style of web links in UI (#1286)

But take into account that there are still room for improvement: see #1493. I'll close this so the number of open issues doesn't go out of control.

**Comment by justinclift** [comment]
As a data point, the .AppImage URL seems to change for every rebuild.  It's probably better to use:

&nbsp; &nbsp; https://github.com/deepsidhu1313/sqlitebrowser/releases/tag/continuous

**Comment by ngosang** [comment]
@mgrojo @justinclift I tried the .AppImage and ...
```
[xxx@xxArch Downloads]$ ./DB_Browser_for_SQLite-3.10.1-210-322fe3c-x86_64.AppImage 
static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)
```

**Comment by ngosang** [comment]
@mgrojo @justinclift It's me again. I built from source code and it looks way better. The only issue is the white bar, but it's minor.

![image](https://user-images.githubusercontent.com/10577978/50543634-09688200-0bde-11e9-9c35-e8ff0cd42ecb.png)
