### ISSUE TITLE
Cannot remove Primary Key field when editing table

### ISSUE THREAD

**Issue by jadeade** [sqlitebrowser/sqlitebrowser#1699]
### Details for the issue

When a field that's marked as PK is removed, a dialog error appears on screen claiming that the operation cannot be performed because the deleted field doesn't exist. If you check the attached screenshot, the new creation sentence still tries to set the older field as PK

![image](https://user-images.githubusercontent.com/5297845/50546466-448fa300-0c28-11e9-82a2-578418b09e8e.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: (8.1)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.11.0-alpha1 or 3.11.0-beta*
- [X] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by jadeade** [comment]
I just tried with last beta and still happens. I just added a PK and AI field to a table that has not and then I tried to remove it with the previously said error

Help reports:
Version 3.10.202 (Dec 13 2018)
Qt Version 5.12.0
SQLite Version 3.26.0

**Comment by jadeade** [comment]
I did not say, but even if it looks obvious: if you remove the pk flag from the field before removing it, it works as expected

**Comment by mgrojo** [comment]
Ok, thanks. I tested with the nightly and it worked well. There are changes in the table edition after the beta, so some of them have solved the issue.

In my case the error message for 3.11 is a bit different:

> expressions prohibited in PRIMARY KEY and UNIQUE constraints (CREATE TABLE "sqlb_temp_table_1" (
> 	"StockId"	NUMERIC NOT NULL,
> 	"AttachedTo"	NUMERIC NOT NULL DEFAULT -1,
> 	"Firmware"	TEXT,
> 	PRIMARY KEY("DecodeId")
> );)

**Comment by chrisjlocke** [comment]
I'll close this, as this is resolved in the latest nightly.  @jadeade, feel free to comment further or reopen the issue if you feel its still unresolved.
