### ISSUE TITLE
the IFNULL() function not working 

### ISSUE THREAD

**Issue by V-Sher** [sqlitebrowser/sqlitebrowser#1700]
Details for the issue
--------------------

#### What did you do?
SELECT species_id, sex, IFNULL(sex, 'U')
FROM surveys;

#### What did you expect to see?
the null rows replaced by 'U'

#### What did you see instead?
the nulls were still blank

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:10.13.1)
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?  This works [with the latest nightly](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds).  Can you try that?

**Comment by chrisjlocke** [comment]
@V-Sher *cough*
