### ISSUE TITLE
[Browse Data] On 1st open, Browse Data requires Refresh to populate grid.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1701]
As title states, On 1st open, Browse Data is empty and requires Refresh to populate grid.
I am using the new feature to move my Browse Data tab leftmost.
#### What did you expect to see?
The grid should populate normally.
#### What did you see instead?
Empty grid.
#### What operating system are you using?
- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### What is your DB4S version?
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [x] Other: ___Nightly 3.11.99 v181229
#### Did you also
- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
This is the same than #1649. Although the other refers to project files, it happens always a DB is opened.

You've marked the 3.11 box, but this should happen only in the nightlies. One of the changes after 3.11 has originated it.

**Comment by sky5walk** [comment]
Sorry, I will edit the post. I am on 3.11.99 nightly.

**Comment by chrisjlocke** [comment]
>  I am on 3.11.99 nightly.

The 3.11.99 refers to *any* nightly.  Can you please indicate the date of the nightly you have downloaded.

**Comment by MKleusberg** [comment]
@sky5walk I think I have finally managed to fix this issue. Can you check this one as well in tomorrow's nightly build? :smile:

**Comment by MKleusberg** [comment]
@sky5walk  Ping... :innocent:

**Comment by sky5walk** [comment]
Sorry for late reply.
This is working for me as of nightly v191121.

**Comment by MKleusberg** [comment]
No worries :smile: Thanks for testing!
