### ISSUE TITLE
how can i show encrypted data?

### ISSUE THREAD

**Issue by ksg3492** [sqlitebrowser/sqlitebrowser#1704]
I use 'DB Browser for SQLite' Tool.
When enter the db's password, all data shown decrypted.
I want to see encrypted datas. please reply.

**Comment by chrisjlocke** [comment]
When you enter password, the database is decrypted.  The data itself is not encrypted.  Everything written to the database is encrypted, so everything read from the database is decrypted.  You cannot view the encrypted data as it is decrypted before DB4S sees it.  Think of it as a layer between the data and the file on the disk.  Everything under this layer is decrypted.

**Comment by chrisjlocke** [comment]
I'll close this, as this isn't an issue in DB4S, per se.  @ksg3492, feel free to comment further or reopen the issue if you feel its not resolved.
