### ISSUE TITLE
DBHub.io docker image - for local development only

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1712]
People have been (repeatedly) asking for a way to deploy the DBHub.io daemons (eg webUI, DB4S end point) locally, so they can do related development.  eg improve the DB4S communications pieces, work on the daemons themselves, etc.

This is a first working version, **very** specifically for use in a local desktop/laptop docker environment:

&nbsp; &nbsp; https://hub.docker.com/r/sqlitebrowser/dbhub.io-dev

The "very specifically for local development" bit is because it embeds all of it's required dependencies (PostgreSQL, Memcached, Minio, etc) in the image, + includes a whole new (just for this purpose) self-signed certificate authority, signing certs, etc.

For now, it comes with a hard coded default user "logged in", so there's no need for an external Auth0 account (etc).  It should (in theory) be self contained.

Anyone interested in giving it a spin, and letting me know if it does/doesn't work for them, etc? :smile:

**Comment by MKleusberg** [comment]
Just tried it and gave it a very quick test: seems all to be working fine :+1: But I haven't tried building the image myself yet nor tested the DB4S end point.

The only minor annoyance I noticed so far is that there is no ```latest``` tag, so you'll always have to specify ```:0.04``` when pulling or running the image.

**Comment by justinclift** [comment]
Good thinking.  I'll add the `latest` tag shortly. :smile:
