### ISSUE TITLE
Shortcut Items in the MSI installer not visible

### ISSUE THREAD

**Issue by Kpax7** [sqlitebrowser/sqlitebrowser#1713]
Details for the issue
--------------------

#### What did you do?
Downloaded and installed the MSI installer (3.11 beta3)

#### What did you see instead?
shortcut items to select are not completely visible (screenshot attached)
![scshot](https://user-images.githubusercontent.com/38801146/51433438-1b7a9500-1c5f-11e9-9dc3-3de1c0cd6c8a.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( _version:7 ultimate)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ x] 3.11.0-alpha1 or 3.11.0-beta3
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @Kpax7 that's useful info.

@karim Any ideas?

**Comment by justinclift** [comment]
@Kpax7 Out of curiosity, are you using the Win32 or Win64 installer?

Not sure if it makes a difference, but it might be useful to know. :smile:

**Comment by karim** [comment]
> @karim Guessing we just need to increase the width of the ShortcutsDialog & BannerBitmap lines?

It is the checkbox control itself, I made it a bit bigger now. I don't know why it is smaller when not using themes in Windows. Sorry, my mistake. :smiley:

**Comment by justinclift** [comment]
Thanks @karim. :smile:

@Kpax7 Would you be ok to try the new nightly build here?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

The windows one's should have @karim's fix in them.  If it works for you, I'll apply the fix to our release series source code too, so the actual release (soon!) gets it too. :smile:

**Comment by Kpax7** [comment]
> @Kpax7 Out of curiosity, are you using the Win32 or Win64 installer?
> 
> Not sure if it makes a difference, but it might be useful to know.

I think it was the win64

**Comment by Kpax7** [comment]
> > @karim Guessing we just need to increase the width of the ShortcutsDialog & BannerBitmap lines?
> 
> It is the checkbox control itself, I made it a bit bigger now. I don't know why it is smaller when not using themes in Windows. Sorry, my mistake.

Thanks, I hate themes lol
I like everything the classic way

**Comment by Kpax7** [comment]
> Thanks @karim. 
> 
> @Kpax7 Would you be ok to try the new nightly build here?
> 
>     https://nightlies.sqlitebrowser.org/latest/
> 
> The windows one's should have @karim's fix in them. If it works for you, I'll apply the fix to our release series source code too, so the actual release (soon!) gets it too.

Yeah, Downloaded the latest Win64 MSI and it was all OK. Thank you
