### ISSUE TITLE
warning: 'selectAll' overrides a member function but is not marked 'override'

### ISSUE THREAD

**Issue by tiendq** [sqlitebrowser/sqlitebrowser#1718]
### Details for the issue
Compile warning.

```
/sqlitebrowser/src/ExtendedTableWidget.h:59:10: warning: 'selectAll' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void selectAll();
         ^
/usr/local/opt/qt/lib/QtWidgets.framework/Headers/qabstractitemview.h:236:18: note: overridden virtual function is here
    virtual void selectAll();
```

#### I'm using DB4S on:

- [x] Mac OS: (10.12.6) + Clang

**Comment by mgrojo** [comment]
Thanks @tiendq. It should be gone now.

**Comment by tiendq** [comment]
@mgrojo Just a bit curious, why do you turn on this warning? I rarely see `override` is required for virtual functions, I only use it in certain cases.

**Comment by mgrojo** [comment]
@tiendq I don't know much of the compilation scripts. We should ask @MKleusberg. In fact I don't get these warnings. I have to maintain two separate compilation systems: cmake and qmake. I have to use cmake in Ubuntu 18.04, so I guess you're using qmake. I don't see these flag in the pro file, but I guess that it is derived from these:

```
src/src.pro:233:    QMAKE_CXXFLAGS += -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion
src/src.pro:234:    QMAKE_CXXFLAGS += -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast
```

Maybe we should synchronise the flags used in both systems. I'll take a look.

**Comment by mgrojo** [comment]
I made the changes to the cmake files to activate the same warnings than in qmake, but I still don't get this warning. It seems that Clang activates  -Winconsistent-missing-override when -Wall is passed. But that flag isn't recognised by GCC, so it cannot be added explicitly. In conclusion, we never intended to have this warning, but adding the override doesn't harm.

On the other hand, when I add the warning flags to CMakeLists.txt, all the libraries that we compile are affected by these warnings and they produce a lot of warnings. There should be a way to apply the flags only to our flags. Some expert in the room?

These are my changes:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 14b8c06f..e1d6f412 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -26,6 +26,12 @@ add_definitions(-std=c++11)
 set(CMAKE_CXX_STANDARD 11)
 set(CMAKE_CXX_STANDARD_REQUIRED True)
 
+# Warnings
+if (CMAKE_COMPILER_IS_GNUCC)
+    set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion")
+    set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast")
+endif()
+
 # Fix behavior of CMAKE_CXX_STANDARD when targeting macOS.
 if (POLICY CMP0025)
     cmake_policy(SET CMP0025 NEW)

```

**Comment by tiendq** [comment]
@mgrojo try `target_compile_options` for a specific target.

**Comment by mgrojo** [comment]
Thanks @tiendq, I've used that and works ok. I've made a PR so it is reviewed before merging.
