### ISSUE TITLE
Failure to delete some SQLite entries (.s3db)

### ISSUE THREAD

**Issue by Blackkatt** [sqlitebrowser/sqlitebrowser#172]
This is what happens when I try to delete this entry, 

SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Instances`  ORDER BY `name` DESC);
SELECT `_rowid_`,* FROM `Instances`  ORDER BY `name` DESC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Instances`  ORDER BY `name` ASC);
SELECT `_rowid_`,* FROM `Instances`  ORDER BY `name` ASC LIMIT 0, 50000;
DELETE FROM `Instances` WHERE `_rowid_`=0;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Instances`  ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Instances`  ORDER BY `_rowid_` ASC LIMIT 0, 50000;

nothing is deleted...even in edit mode clearing the cell does nada. The row in question is empty yes, but still has an id (type of data currently in cell: text /numeric 10 char(s)) so I want it gone, seem impossible =/ actually nothing can be saved to these entries it seems???

Sorting is also reset after "delete record" is pressed, very annoying =)

**Comment by MKleusberg** [comment]
So, I could track down the issue to the very large primary key values used in the database which wouldn't fit in the int datatype we were using at some places. This should be fixed in the next nightly build.
Thanks for your bug report, @Blackkatt :smiley:

**Comment by Blackkatt** [comment]
@MKleusberg  Haha good work! I'll have to give it another try just because you spent all that time locating the issue WTG!

**Comment by justinclift** [comment]
@Blackkatt Would you be ok to try the next nightly build (after tonight), and confirm back whether it's now working properly or not?  (download locations for the nightly builds are on the front page of this repo) :smile:

**Comment by Blackkatt** [comment]
sure why not

**Comment by Blackkatt** [comment]
@justinclift could you link me perhaps, I see nothing called Nightly Builds only the master updated 2h ago =)

**Comment by Z4us** [comment]
SQLite by default uses 64-bit: https://www.sqlite.org/lang_createtable.html

<quote>
ROWIDs and the INTEGER PRIMARY KEY

Except for WITHOUT ROWID tables, all rows within SQLite tables have a 64-bit signed integer key that uniquely identifies the row within its table. This integer is usually called the "rowid". 
</quote>

**Comment by MKleusberg** [comment]
@Blackkatt For Windows you can find them [here](http://rp.oldsch00l.com/sqlitebrowser/). Just download the sqlitebrowser.exe.xz file and uncompress it with 7-Zip or some similar program.

**Comment by Blackkatt** [comment]
@MKleusberg ok, spanx, I'll test this out later today then =)

**Comment by Blackkatt** [comment]
Seem to work fine, GJ.

**Comment by justinclift** [comment]
Excellent, thanks for confirming back. :smile:
