### ISSUE TITLE
Release candidate 3.11.0-beta3 has wrong version info

### ISSUE THREAD

**Issue by hannesa2** [sqlitebrowser/sqlitebrowser#1722]
Installing the release candidate 

https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.11.0-beta3/DB.Browser.for.SQLite-3.11.0-beta3.dmg

shows wrong version number

![image](https://user-images.githubusercontent.com/3314607/51919300-6c1e8a80-23e3-11e9-951e-1d87a463d4e8.png)

**Comment by justinclift** [comment]
Just double checked here, by freshly downloading + installing it.

The version reported for that is:

![screenshot1](https://user-images.githubusercontent.com/406299/51945344-94a19580-2472-11e9-8a2a-b63927188ddf.png)

Guessing here, but it *seems* like the version you've grabbed is our 3.10.1 release.  Maybe an accidental mouse click or something when you were saving it, and it picked up the wrong file name?

As a thought, if you're familiar with creating SHA256 checksums then it should be pretty easy to check if your file is just accidentally misnamed named.

We include the SHA256 checksums for the files on the release pages:

* 3.10.1: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1
* 3.11.0-beta3: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta3

Your downloaded file will probably be:

* 9456e8ff081004bd16711959dcf3b5ecf9d304ebb0284c51b520d6ad1e0283ed

(that's the 3.10.1 OSX file)

**Comment by hannesa2** [comment]
Ok, no I did it on command line
```
wget https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.11.0-beta3/DB.Browser.for.SQLite-3.11.0-beta3.dmg
open DB.Browser.for.SQLite-3.11.0-beta3.dmg
```
Now it works, it was somewhere my fault. 
Thanks anyway
