### ISSUE TITLE
Install icons and application resources unconditionally

### ISSUE THREAD

**Issue by brook-milligan** [sqlitebrowser/sqlitebrowser#1723]
Details for the issue
--------------------

CMakeLists.txt (lines 435-444) omits installing three files (an icon file and two application resource files) depending on the conditional "if(UNIX AND NOT APPLE)".

Why are these files not included unconditionally?

I have successfully built and run sqlitebrowser on a Mac with a modified version of CMakeLists.txt that removes the conditional (and therefore installs all three files); see the attached patch.

Please either remove the conditional or provide a rationale for why the conditional makes sense.

Thank you very much.

#### What did you do?

I installed sqlitebrowser with and without the attached patch applied.

#### What did you expect to see?

I initially expected the installation on a Mac to be the same as the installation elsewhere.  When it was not, I discovered the conditional and removed it.  The installation still succeeded, and the result was now the same as on other systems.

#### What did you see instead?

By default, the Mac installation is (unexpectedly) different from other unix installations.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x ] Mac OS: ( _version:_ 10.11.16 )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [x ] Other: 3.8.0 but the conditional is still present in the most recent version of CMakeLists.txt

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

[patch-CMakeLists.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/2815417/patch-CMakeLists.txt)

**Comment by justinclift** [comment]
Thanks @brook-milligan. :smile:

Looking at the patch, this selection seems to be the code fragment you're meaning:

https://github.com/sqlitebrowser/sqlitebrowser/blob/4f939285fcf30411c9a95a1f61ec6b6770200c5c/CMakeLists.txt#L435-L444

The .png file would probably make more sense being included in macOS too.  Not sure about the .desktop and .xml files though.  From memory they provide [configuration metadata](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#sect-AppStream-XML) for some *nix desktop environments (eg menu structure placement ).

Does macOS use them too?

**Comment by brook-milligan** [comment]
> On Jan 31, 2019, at 8:29 AM, Justin Clift <notifications@github.com> wrote:
> 
> Looking at the patch, this selection seems to be the code fragment you're meaning:
> 
> https://github.com/sqlitebrowser/sqlitebrowser/blob/4f939285fcf30411c9a95a1f61ec6b6770200c5c/CMakeLists.txt#L435-L444

Yes, that is the section.  Just remove the "AND NOT APPLE" bits.

> The .png file would probably make more sense being included in macOS too. Not sure about the .desktop and .xml files though. From memory they provide configuration metadata for some *nix desktop environments (eg menu structure placement ).
> 
> Does macOS use them too?

I'm not sure.  However, I have other software that installs similar files, so it seems that sqlitebrowser should do the standard thing and install all the resource files expected on a normal unix system.  From what I can tell, there is no harm in installing these and that is what is typically expected to happen.  Why make a needless exception?

Cheers,
Brook

**Comment by justinclift** [comment]
Like many projects, our CMakeLists.txt file is kind of a hairball that has accreted stuff over time.

It's no issue adjusting the scope so the .png would be included with macOS.  Still not seeing a reason to include the .desktop and .xml files though.  I'd expect the other software which you have that does install them... is just doing so from a lack of precision, not because they're particularly care. :wink:

If macOS does use those two files, then sure we can include them too.

**Comment by justinclift** [comment]
I'll update CMakeLists.txt so the .png gets deployed on macOS as well.

**Comment by justinclift** [comment]
Just took a minute to look through our [macOS build script](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/installer/macos/build_sqlitebrowser_nightly.sh), to refresh my memory on how this stuff is done.

Our .app bundle is built with Qmake instead of CMake.  The line where the icons file is defined is here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/src.pro#L224

Not seeing another mention of `RC_FILE`, so it's probably something that Qt knows to automatically copy to the resulting .app.

Does any of the above help?  I'm thinking your patch might be unnecessary, depending on what you're trying to do. :smile:

**Comment by brook-milligan** [comment]
> On Jan 31, 2019, at 10:20 AM, Justin Clift <notifications@github.com> wrote:
> 
> Just took a minute to look through our macOS build script, to refresh my memory on how this stuff is done.
> 
> Our .app bundle is built with Qmake instead of CMake. The line where the icons file is defined is here:
> 
> https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/src.pro#L224
> 
> Not seeing another mention of RC_FILE, so it's probably something that Qt knows to automatically copy to the resulting .app.
> 
> Does any of the above help? I'm thinking your patch might be unnecessary, depending on what you're trying to do. 😄

To answer an earlier question, I am building a typical X app to be executed from the command line (not a .app bundle).  Specifically, this is to make the pkgsrc package work consistently across platforms.  These are the correct locations for installing those files in that environment, and it would be appropriate for sqlitebrowser to do the same thing as other applications under similar conditions.

Presumably Qmake and Cmake are (appropriately) doing something completely differently during their respective build processes.  Does the stanza in question in CMakeLists.txt interact with Qmake?  If not, then it seems that my patch is correct.

By the way, the icon file that ultimately gets installed into .../icons is in fact an icon, i.e., an image of the three-tiered set of platters.  I have not looked into how it got there, but Cmake is doing the right thing.  The other two files look appropriate as well.

Cheers,
Brook

**Comment by justinclift** [comment]
> Presumably Qmake and Cmake are (appropriately) doing something completely differently during their respective build processes.

Yeah.  We mainly use Cmake for Windows, and (from memory) Linux too.  Whereas - as you're experiencing - it's not super well refined for macOS.

It probably won't hurt anything to make the change you're suggesting, so I'll get it done in a minute.  If it does break something for people, I guess we'll be finding out in subsequent issues. :wink:

**Comment by justinclift** [comment]
k, just made the change (in 21d8800ce613775c995212f61d7e95c2189f6da6).

Didn't test it though, as it's so simple.  Would you be ok to try the build out and confirm it's now doing things as expected? :smile:

**Comment by brook-milligan** [comment]
> On Jan 31, 2019, at 11:51 AM, Justin Clift <notifications@github.com> wrote:
> 
> Presumably Qmake and Cmake are (appropriately) doing something completely differently during their respective build processes.
> 
> Yeah. We mainly use Cmake for Windows, and (from memory) Linux too. Whereas - as you're experiencing - it's not super well refined for macOS.
> 
> It probably won't hurt anything to make the change you're suggesting, so I'll get it done in a minute. If it does break something for people, I guess we'll be finding out in subsequent issues. 😉

Generally, I (and I'm sure you too) dislike changing things and waiting for the fallout.  However, in this case, unless Qmake and Cmake interact in some way, I don't really expect a problem, especially because this only affects the behavior on the "IF APPLE" case, for which I have seen no issues.  The Windows case is not affected nor is the Linux (or other unix) case.

Thanks for jumping on this so quickly.

Cheers,
Brook

**Comment by brook-milligan** [comment]
> On Jan 31, 2019, at 11:55 AM, Justin Clift <notifications@github.com> wrote:
> 
> k, just made the change (in 21d8800).
> 
> Didn't test it though, as it's so simple. Would you be ok to try the build out and confirm it's now doing things as expected? 😄

Normally, I would say yes.  However, the machine I am testing this on seems to have problems with the qt5 prerequisites so I can't.  That is why I was originally working with the 3.8.0 code base.  It is hard to see how there would be any difference in this area, though.  As soon as I get qt5 fixed up, I'll give it a try though.

Cheers,
Brook

**Comment by justinclift** [comment]
No worries.  Please do. :smile:

**Comment by justinclift** [comment]
Going to close this as it should (in theory) be fixed now.  If it turns out not to be, people are welcome to re-open this so we can investigate. :smile:
