### ISSUE TITLE
New DB4S website

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1724]
Been experimenting with [Hugo](https://gohugo.io) (a static website generator) & [blogdown](https://github.com/rstudio/blogdown) yesterday and today, with the idea of remaking our website so it can also include blog posts.

~An initial draft is online here (temp location):~

&nbsp; &nbsp; ~https://justinclift.org~

It's using the default blogdown theme ("hugo-lithium") without any customisations yet, as we'll probably want to choose something a bit less plain looking.  Plenty to choose from:

&nbsp; &nbsp; https://themes.gohugo.io

Some things it still needs:

* Obvious download buttons on the home page
  - It'd probably mean customising the theme, which I'm avoiding for now as that will make changing to a new theme difficult.
* [x] - Maybe a Gitter link in the top menu?
* [x] - More blog post content
  - Just created historical entries for all of our news items.  Turns out there was quite a few. :wink:

Thoughts? :smile:

**Comment by justinclift** [comment]
Oops, forgot the repo: https://github.com/justinclift/db4s_website

That's a temp repo too.  If we do go with this new website approach, I'll move the repo to the sqlitebrowser org here on github.  Probably rename the repo to "website" at the same time too. :smile:

**Comment by justinclift** [comment]
Just added blog post entries for all of our historical news items, and also added a link to our Gitter in the top menu bar.

In theory, this is probably a reasonable start for our new website.  I'll get this deployed to our main sqlitebrowser.org domain name shortly.  We'd better keep an eye on things too, just to make sure there's no indication of problems (eg massive drop in download numbers, etc). :wink:

**Comment by justinclift** [comment]
Ahhh, we should probably decide on a license for the website repo too.  I'm thinking [CC0](https://creativecommons.org/choose/zero/) is probably suitable.

Any objections? :smile:

**Comment by justinclift** [comment]
Just transferred the repo to the sqlitebrowser org:

&nbsp; &nbsp; https://github.com/sqlitebrowser/website

Having some trouble getting the current GitHub Pages (gh-pages branch) approach turned off, in order to switch to the new repo.  I've contacted GitHub support about the problem, so hopefully they'll get back to us soon.

**Comment by justinclift** [comment]
... and I've just realised we have no stats available for the website, since we no longer use Google Analytics nor are we hosting it.

Will need to think over how to solve this.  It'd be fairly trivial to move the hosting to our own server(s), letting us generate stats from the https log files.  But, that become yet another server + software to be managed.

**Comment by chrisjlocke** [comment]
Does GitHub not have any stats at all?  On each page couldn't you host a different 1 pixel image which you could track via the HTTPS logs.  Guess if you're doing that, you might as well host the whole lot.
Looks good though.

**Comment by justinclift** [comment]
> Does GitHub not have any stats at all?

Unfortunately, no.  :frowning: 

> Just a note that the image on the main page isn't responsive, so on phones and tablets, it'll be cut orf.

Oh, hadn't thought of that.  Is it just the image being a problem (which might be fixable), or other elements too?

If it's other elements as well, that should be fixable by us picking a theme which does things better.

Was very careful to not do anything which would make us have to stick with the current theme, so we should be fine to experiment with other ones. :smile:

**Comment by FriedrichFroebel** [comment]
The logo in the menu bar looks a bit strange due to it being cut off (his may work for regular blogs which have a user avatar instead). This behaviour is introduced by the `border-radius` property of the `.nav-logo img` selector (line 65 of `main.css`).

And just out of curiosity: Is there a reason for choosing `blogdown` while using only regular Markdown files instead of "plain Hugo"?

**Comment by justinclift** [comment]
Yeah, same thought about the weird round edges for the logo.  Didn't want to muck with any theme specific stuff though, as I figured we'd probably be changing the theme once we figure out what content to put up.

Since the content itself seems ok, we can probably experiment with either changing complete themes, or go down the road of customising the default one we're using. :smile:

With the themes, there's a fairly wide list of one's we can choose from:

&nbsp; &nbsp; https://themes.gohugo.io

I'll try some out later on today (probably), and see what it **really** takes to change them around.  In theory :wink:, for most of them it should be just a simple 1 line command to pull down the source (using git), then changing the [theme name in our config.toml](https://github.com/sqlitebrowser/website/blob/ab1cddc0d98e1a4d8bcba42c83b48c8e3c754fe6/config.toml#L4), then regenerating the site (another 1 line command).

> And just out of curiosity: Is there a reason for choosing blogdown while using only regular Markdown files instead of "plain Hugo"?

Yep, they have a much better newbie/intro guide than the main Hugo website.  Hugo's defaults seem very narrowly focused on blogs rather than websites with undated/non-post content pages (about, download, history, etc).  So, following through the Hugo guide is simple to do, but only results in getting a blog up and running.  To go anywhere past that seems to be a matter of reading either their reference documentation - which as a newbie having no idea of what-is-what doesn't really work - or tracing through the source code to figure stuff out - also possible, but can be a large time sink too.

While looking for online Hugo guides, the blogdown one pops up near the top of search results:

&nbsp; &nbsp; https://bookdown.org/yihui/blogdown/

It's well written, aimed at newbies, and includes both proper websites (with things like index/about/etc pages), and blogs.

Also... blogdown lets people embed R code in their posts, so is useful for displaying graphs and figures.  I've been (personally) wanting to do more with R as it's interesting to me, and other members of the team have mentioned similar.  So... a good excuse to do stuff for that goal too. :grin:

**Comment by justinclift** [comment]
As half expected, changing themes can be fairly involved.  It seems to depend on how different a given theme is from the default Hugo settings.

So far (still going) there's a theme called "mainroad" which also looks like it has potential:

![db4s_website_option-mainroad](https://user-images.githubusercontent.com/406299/52176414-a6829000-2806-11e9-9f80-8bc29c9c10b9.png)

**Comment by justinclift** [comment]
Hmmm, I'm kind of getting sick of trying new themes.  For now I've just directly modified that `main.css` file as @FriedrichFroebel mentioned.  More investigation of themes can come at a later point, whenever someone feels like doing it. :smile:

**Comment by chrisjlocke** [comment]
'mainroad' looks kinda professional, especially if it used the DB4S colours, but that might make it quite grey and drab looking.  Blue has always been 'professional'.  I'm open to try some out - got some spare hosting space to experiment with.

**Comment by justinclift** [comment]
Excellent. :smile:

It's (mostly) pretty simple to try stuff out, at least for the themes which don't require customisation to get working (at all):

1. Install Hugo.  It's a single binary executable (cli utility), so just throw it somewhere in your PATH and that bit's done. :smile:
    * https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Windows-64bit.zip
2. Clone our website source:
    * https://github.com/sqlitebrowser/website
3. Generate the website content:
    `> hugo server`

That'll spin up a local web server (http://localhost:1313) with the newly generated website.  It also has the generated content under `docs/` in the filesystem, if you want to chuck it online for others to look at.

To try a new theme, download it to the "themes" directory, then put the new theme name in config.toml:

https://github.com/sqlitebrowser/website/blob/fd4cdb2ae9dfde06873aa1b63951c2e3e246d379/config.toml#L4

Run the `hugo server` command again, it'll start up the local webserver to try things out.

Note - If you don't want to install the themes individually, you can bulk grab the entire lot with one command (takes a few minutes):

https://gohugo.io/themes/installing-and-using-themes/#install-all-themes

If running `hugo server` gives an error about not being able to generate content, it generally means the theme requires custom config to make work at all.  I just skipped over those ones.  Many others to choose from. :smile:

**Comment by justinclift** [comment]
Am setting up a new web server box (fairly low end spec) online now.  Will throw on Nginx and our new website, as there's no need for a backend database.  Should be easily sufficient. :smile:

For log processing, "Fathom" (@dannyvankooten) looks good:

* https://usefathom.com
* https://github.com/usefathom/fathom

Seems pretty simple, no GDPR issues, and it uses SQLite on the backend out of the box. :grinning:

**Comment by justinclift** [comment]
Just updated the DNS records to point at the new server.  There's a 5 minute propagation time, so (in theory) in a few minutes time we'll be serving our own website again.

If any weirdness shows up, let me know. :smile:

**Comment by justinclift** [comment]
Just added that "Fathom" stats processor to things, and put it in a publicly accessible spot:

&nbsp; &nbsp; https://stats.sqlitebrowser.org

Not sure if it'll be a reasonable long term solution though, as it requires javascript in visitors browsers + doesn't do any kind of server log processing.  So, likely to exclude a bunch of valid visitors.  Lets see how it goes. :smile:

**Comment by chrisjlocke** [comment]
Was looking at fathom, but don't think its compatible with my shared hosting - runs its own webserver which I can't do.  
For the 'general users' with javascript, etc (so many sites use it, do people really turn it off these days?) I think its quite useful stats - see which blog posts are getting hit, who reads the latest news, etc.  Handy.

**Comment by justinclift** [comment]
Yeah.  Any kind of stats processing will give that info.  It's just server side log processing is more accurate. :smile:

But, it was simple to set up.  Seems to not like being started as a background service by systemd, which I'll need to look into at some point.  For now, I'll just leave it manually running a detached terminal session or similar.

**Comment by justinclift** [comment]
Closing this, as the new website is up and running.

We're seeing a minor drop (~5%) in download numbers for the new website compared to the old 1-page approach though.  I'll have a go at converting the old 1-page website - with it's useful immediate download buttons - to a Hugo theme, but with sections <somehow>, and see if that fixes the problem. :smile:

**Comment by justinclift** [comment]
Been pointed at a modern, server side log processing solution:

&nbsp; &nbsp; https://github.com/allinurl/goaccess/

They have a real-time demo online too, which looks nice:

&nbsp; &nbsp; https://rt.goaccess.io/?20181123091935

That one might be a better fit.  Will probably try it out sometime soon-ish, just to see which ones gives us better into.
