### ISSUE TITLE
[Nightly] Renaming table fails with error copying data

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1725]
Details for the issue
--------------------

#### What did you do?
Modified a table by renaming it

#### What did you expect to see?
No error

#### What did you see instead?
![image](https://user-images.githubusercontent.com/7872218/52068495-ad926f80-2574-11e9-829d-66538ac59889.png)

The table 'currentUsage' is the original name.  Originally I tried renaming it to something else, but for the purpose of this issue, I appended a 'u' to the end, as shown in the screenshot.
So simply, the copying code is looking at the old name, not the new name,

Useful extra information
-------------------------
@MKleusberg attacked this code recently following a couple of other issues, and I thought I'd tested this, but the 'error copying data' is a new issue...

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10___ )

#### What is your DB4S version?

- [x] Version 3.11.99 (Jan 24 2019)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Works fine for me :confused: Can you paste the full table schema here? And did you change anything besides the table name?

**Comment by chrisjlocke** [comment]
When you're testing, does your table have a primary key?  Tables with no primary keys set seem to rename OK.  Tables with the first field as a primary key (specifically an INTEGER) seem to fail.

(had to experiment a lot to work that out...!)

https://screencast-o-matic.com/watch/cqn66c3KZ6

**Comment by MKleusberg** [comment]
You are right - I didn't check with a primary key. But I believe I know what was causing the problem and I already committed a fix. This one will need some good testing though :smile:

**Comment by justinclift** [comment]
The other test builds are finished, so I'll rerun todays standard nightly build script for Win64.  That'll give something for testing sooner, in case it's useful. :smile:

**Comment by MKleusberg** [comment]
Awesome :+1: Lots of building and lots of cherry-picking for today then :wink:

**Comment by justinclift** [comment]
Yep. :wink:

**Comment by chrisjlocke** [comment]
🍒🍒🍒 🌸              💥

**Comment by justinclift** [comment]
Just watched the screencast (above).  That was done well, really clear, etc.

Music wasn't tooooooooooo cheesy either. :smile:

**Comment by chrisjlocke** [comment]
I got quite used to the music and liked it after a while! 😆 🙉

**Comment by justinclift** [comment]
Updated Win64 build for today is online:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

**Comment by chrisjlocke** [comment]
Thanks @justinclift for creating the builds.

Renaming a table now works, but a few 'issues' if that table belongs to a view.  Have reported that in that thread.
Added a field, and removed a field, and that all worked too.  

Thanks @MKleusberg.
