### ISSUE TITLE
Error creating a seemingly correct trigger

### ISSUE THREAD

**Issue by Random-nii-chan** [sqlitebrowser/sqlitebrowser#1726]
Details for the issue
--------------------

#### What did you do?
I tried to create a trigger on an existing table, the table and trigger structures are the following:

```sql
--My table
CREATE TABLE "LoadoutUserLinked" (
	"userId"	INTEGER NOT NULL,
	"loadoutId"	INTEGER NOT NULL,
	PRIMARY KEY("userId","loadoutId")
);
--My trigger (it is supposed to prevent inserting another row in the table if there is already five rows in with the same userId)
CREATE TRIGGER maxLoadouts BEFORE INSERT ON LoadoutUserLinked
DECLARE
	numberOfLoadouts integer;
BEGIN
	SELECT COUNT(*) INTO numberOfLoadouts
	FROM LoadoutUserLinked
	WHERE userId = new.userId;
	
	IF(numberOfLoadouts = 5) then
		RAISE(ABORT,'Too many loadouts !');
	END;
END;
```
#### What did you expect to see?

My intention was to create a working trigger (I followed several PL/SQL online courses and inspired me from their examples).

#### What did you see instead?

The console in the application tells me the following:

```
Execution finished with errors.

-- At line 1:
CREATE TRIGGER maxLoadouts BEFORE INSERT ON LoadoutUserLinked
DECLARE
-- Result: near "DECLARE": syntax error
```

If I made an error writing my trigger, I deeply apologize, it wasn't my intention. If this is the case, I can't see it 😟 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [x] Other: 3.26.0

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Looking at the SQLite website "Triggers" page, it doesn't have a mention of `DECLARE` as a keyword:

&nbsp; &nbsp; https://sqlite.org/lang_createtrigger.html

Guessing you'll need to adjust your syntax a bit.  That page should help. :smile:

**Comment by Random-nii-chan** [comment]
Thank you ! So it was my horrible syntax all along ! Could you please let me know how can I create a trigger like I wanted using sqlite ? I can't find a way to do what I want without variables...

**Comment by justinclift** [comment]
> I followed several PL/SQL online courses and inspired me from their examples

As a general thought, `PL/SQL` is (from memory) an Oracle database specific procedural language.  Different databases have their own procedural languages, or way of achieving the same thing.  eg `PL/pgSQL` in PostgreSQL (slightly different syntax), etc.

Personally speaking, I've not really touched SQLite triggers so I'm kind of clueless with that part of things. :innocent: 

Someone else here might be able to help... though most people are in the EU/US timezone, so aren't around for at least a few hours.

You might get a better/faster result by asking on the SQLite users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

That has **lots** of people subscribed to it (generally pretty friendly and helpful), across lots of timezones.  Very recommended. :grinning:

**Comment by Random-nii-chan** [comment]
Thank you ! I'll take a look as soon as possible. In the meanwhile, I'll do a quick and dirty turnaround using my js code. I'm closing this issue.

**Comment by justinclift** [comment]
No worries at all @Random-nii-chan. :smile:
