### ISSUE TITLE
3.11.0 beta3 Win 7 install fails

### ISSUE THREAD

**Issue by gravatom** [sqlitebrowser/sqlitebrowser#1728]
Details for the issue
--------------------

#### What did you do?
Trying to install DB.Browser.for.SQLite-3.11.0-beta3-win64.msi

#### What did you expect to see?
Normal installation & pop-up to uninstall old version

#### What did you see instead?
When doubling click to install I saw
![db browser1](https://user-images.githubusercontent.com/47325376/52214943-e1c6a280-288a-11e9-936b-b68886443e55.png)

With Run as Administrator I saw
![ddb browser2](https://user-images.githubusercontent.com/47325376/52215010-0753ac00-288b-11e9-9a27-9a98f879dc8b.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( _version:_7 Home Premium___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @gravatom.

The first screenshot does look like it's missing permissions in some way, and the second one (as Administrator to fix that)... looks like it's being blocked by something.

As a complete guess, if you right click on the downloaded msi and choose Properties, is there an option near the bottom to "Unblock" or similar?

Kind of thinking that it sounds like some security/virus-checker/something might be marking the file as "unknown or potentially unsafe", so out of an abundance of caution it could be blocking things.

That's really just a guess though. :wink:

**Comment by chrisjlocke** [comment]
Oooh.  The beta has been out for a while, and we haven't had other issues.
Have you had a prior version installed?
As a 'nasty fix', you could try installing in c;\db4s - this at least gets you up and running (if you haven't already)
WHat anti-virus software do you have installed / running?

**Comment by gravatom** [comment]
For anti-virus I run Microsoft Security Essentials. Switching off real-time protection mode i get the same results.

On the permissions side I've not had problems with msi installs previously and just this minute I've run the msi installer for Calibre https://calibre-ebook.com/download_windows64 successfully.

At the moment I have 3.8.0 installed.

For the moment I've installed to D:\subdirectory

**Comment by chrisjlocke** [comment]
Thanks @gravatom .  I assume 3.8.0 is installed in the same directory? (c:\program files)
Just as a test, can you uninstall 3.8.0, then run the 3.11 installer again?  You might have to uninstall 3.11 as well - sorry.  The idea here is to start with a 'clean slate'.  We've recently switched installers, so the 3.11 isn't picking up the 3.8 installation (that's my thinking, anyway...)

**Comment by gravatom** [comment]
I uninstalled both and the install was successful. Thanks chrisjlocke.

**Comment by chrisjlocke** [comment]
Excellent, thanks.  Will make a note of this though to test.
