### ISSUE TITLE
The GUI does not handle HDPI displays correctly under Ubuntu/Linux

### ISSUE THREAD

**Issue by johann-petrak** [sqlitebrowser/sqlitebrowser#1729]
Running this on Ubuntu 18.04 with the default version and the most recent development version of sqlitebrowser (Version 3.11.99 (Feb  7 2019))

The main screen of the system is set to 1920x1080 but has a maximum resolution of 3200x1800, the secondary monitor is also 1920x1080. The sqlitebrowser GUI appears to be huge on both screens and does not even fit into the desktop. 

There appears to be no option to configure anything to change this behaviour either.

**Comment by justinclift** [comment]
Ahhh.  Yeah, we do get the occasional report of weirdness with HiDPI displays, but aren't really sure what to do about it.

From (fuzzy) memory, it might be something we need to tweak via Qt, which is the cross-platform GUI toolkit we use.

Out of curiosity, do you have other Qt using applications on the system?  If so, do they work ok?

Just kind of thinking if we can cheat and look at how some other Qt application handles HiDPI displays, maybe we can just copy their approach. :smile:

**Comment by johann-petrak** [comment]
Good idea, I will try to find some other app, but it is not immediately apparent which programs do use Qt under the hood.

**Comment by chrisjlocke** [comment]
https://en.wikipedia.org/wiki/Category:Software_that_uses_Qt
Might be out of date though!

**Comment by chrisjlocke** [comment]
Apparently VLC too.
https://www.quora.com/What-are-some-examples-of-applications-created-with-QT

**Comment by johann-petrak** [comment]
Thanks! I tried digikam, qwenview, cantor and octave.

Turns out this is really weird: 
* Originally I tried this under the MATE window manager
* As with sqlitebrowser, all other programs also showed huge dialogs
* I then thought I can try the other window managers on my system
* tried with Ubuntu and after configuring the displays in the same way, sqlitebrowser was displayed properly
* tried Xfce, again worked after configuring
* Installed plasma but was unable to even understand the desktop I was shown and aborted
* Tried GNOME, that window manager did not work properly, only showed one screen, if setting up the same resolution on the HDPI primary screen as with the other wondow managers, showed everything huge
* Tried GNOME Classic, after configuring everything worked fine and sqlitebrowser showed properly
* Tried GNUME on Xorg, also worked fine
* Went back to try MATE once again and NOW IT ALSO WORKED FINE

OK, Ubunt/Linux is weird. I have no idea why it works now, but I guess this bug can be closed :smiley:

**Comment by justinclift** [comment]
Heh Heh Heh.  Yeah, weirdness in action. :wink:

If it happens again and you figure out what the root cause is, please let us know.  That way we'll either be able to do something about it, or at least have a reference thing to future people at if they hit it too. :smile:
