### ISSUE TITLE
Phones home

### ISSUE THREAD

**Issue by bonerfart** [sqlitebrowser/sqlitebrowser#173]
Program (3.4.0 as downloaded 2014-12-11 from sourceforge) immediately phones home to an IP hosting suspicious sites such as 5monkeys.se (see http://reverseip.domaintools.com/search/?q=23.235.43.133). It shows no opt-out or autoaupdate options.

**Comment by justinclift** [comment]
k, for the next release (3.5), we'll only put the binaries on GitHub.  I'll also remove all of the existing binaries from SourceForge, and point people at the GitHub download location.

**Comment by justinclift** [comment]
@bonerfart Btw, which OS did you find this behaviour on?

**Comment by MKleusberg** [comment]
A 'whois' on the IP you reported says, it's owned by Fastly. That's a company which hosts all sort of websites and web applications, including Github. So I'm not that sure this connection is opened by some code added by Sourceforge - it might just be our update code connecting to Github. But without any information on the transferred data we can't really be sure.

Either way, maybe we should add an option for disabling the auto update feature on Windows. Or at least not query Github after each start if the user has clicked the Don't-show-again-option.

**Comment by justinclift** [comment]
@MKleusberg Yeah, that's probably a decent preference thing to add.

**Comment by MKleusberg** [comment]
Just added that option: In the preferences dialog you can now disable the automatic update check and I'm pretty confident that this will lead to no network connections being opened. If this should still be the case with any version from now on, we know the source code has been changed before compilation.

**Comment by justinclift** [comment]
@bonerfart Sound working to you?

**Comment by MKleusberg** [comment]
Closing this issue as it is quite old and we have a fix applied some time ago.

**Comment by justinclift** [comment]
Hmmm, I think I need to test this on OSX too, just to verify it's good all round.  I'll try to get it done tomorrow.
