### ISSUE TITLE
error encrypting in 3.11.0

### ISSUE THREAD

**Issue by StevenMagdy** [sqlitebrowser/sqlitebrowser#1732]
Details for the issue
--------------------

#### What did you do?
tried to encrypt using SQLCipher 4 defaults

#### What did you expect to see?

encrypt

#### What did you see instead?

SQL logic error (SELECT sqlcipher_export('sqlitebrowser_edit_encryption');)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 10.14.3 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just an obvious check, but you're running 'DB Browser for SQLCipher' and not 'DB Browser for SQLite' ?  Have to ask, as its not clear whether you are.

**Comment by StevenMagdy** [comment]
I'm running DB Browser for SQLite 3.11.0

**Comment by chrisjlocke** [comment]
Aah, I  might be talking nonsense.  Hopefully someone else can advise, as I don't run MacOS.  I know on the Windows version, there are two executables - with and without encryption.  I was thinking this was similar on the MacOS...

**Comment by justinclift** [comment]
On macOS there's just the SQLCipher one.  It only occurred to me well after we did the packaging on Windows... that for this release both the SQLite and SQLCipher executables bundle the exact same version of SQLite.  We might as well have shipped just the SQLCipher one there too. :wink:

**Comment by MKleusberg** [comment]
This seems to be the same issue as in #1690. In [my comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/1690#issuecomment-450489429) there I mention the only explanation I have found so far for this: According to the SQLCipher guys a mismatch in the OpenSSL versions can cause this problem - so it would be a build thing.

**Comment by justinclift** [comment]
k, I'll double check later on today.  I manually tested our macOS binary being able to open/save SQLCipher 3 created databases.  Don't think I checked for SQLCipher 4 ones though, rather assuming that would work.

And yeah, in hindsight that could be better. :scream_cat:

**Comment by justinclift** [comment]
Uh oh.  Just tested the SQLCipher 4 encryption here on macOS... and yep, same problem. :scream: 

![db4s-issue_1732-screenshot1](https://user-images.githubusercontent.com/406299/52532061-03d09100-2d73-11e9-83de-5a848e84e942.png)

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArrrggggggggggggh. :man_facepalming:

**Comment by justinclift** [comment]
Hmm, I can't get the SQLCipher encryption (using any settings of 3/4/customer) to encrypt a previously not-encrypted database.  eg completely borked encryption functionality.

**Comment by justinclift** [comment]
It will open a previously encrypted (SQLCipher 3) database though, without any issue.

Damn. :frowning:

**Comment by justinclift** [comment]
Same problem exists with a newly setup Win7 x64 VM too, so it's probably not a packaging error.

At a guess, we'll probably just need to change the SQL statements we send to SQLCipher, and voila... it then works.  That's my hoping anyway. :wink:

**Comment by JReally** [comment]
Although it may have nothing to do with this situation... when I drop the SQLcipher from the 2019-02-11 build into my Lazarus application (replacing the SQLCipher version from December 2018), it fails to open encrypted databases.

**Comment by MKleusberg** [comment]
@justinclift Maybe you're right. But I'm not so optimistic yet :wink: Take example number 4 from [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) which is closest to what we do in the dialog:
```sql
PRAGMA key = 'testkey';
ATTACH DATABASE 'newdb.db' AS newdb KEY 'newkey';
PRAGMA newdb.cipher_page_size = 4096;
PRAGMA newdb.cipher = 'aes-256-cfb';
PRAGMA newdb.kdf_iter = 10000;
SELECT sqlcipher_export('newdb');
DETACH DATABASE newdb;
```

Here's what we do:
```sql
PRAGMA key = 'testkey'; -- While opening the database

ATTACH DATABASE 'filename.db.enctemp' AS sqlitebrowser_edit_encryption KEY 'newkey'; -- When changing the encryption
PRAGMA sqlitebrowser_edit_encryption.cipher_page_size = 4096;
PRAGMA sqlitebrowser_edit_encryption.kdf_iter = 10000;
PRAGMA sqlitebrowser_edit_encryption.cipher_hmac_algorithm =  SHA512;
PRAGMA sqlitebrowser_edit_encryption.cipher_kdf_algorithm = SHA512;
SELECT sqlcipher_export('sqlitebrowser_edit_encryption');

-- Extra PRAGMA here - but we don't even get this far according to the error message
PRAGMA sqlitebrowser_edit_encryption.user_version = 1;

-- DETACH DATABASE sqlitebrowser_edit_encryption;
-- No detaching for us. We just close the entire connection.
```

So three things seem to be different here (in a way which might matter):
1) ```kdf_iter``` comes last in the example but second in our case. I don't think that's important.
2) We use ```cipher_hmac_algorithm``` and ```cipher_kdf_algorithm``` instead of the ```cipher``` pragma. I'm not sure what to think about this. The ```cipher``` pragma isn't even documented.
3) We say ```SHA512``` instead of ```HMAC_SHA512```.

So let's try them out :smile: Can you maybe test again with this patch applied:
```diff
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index b234caf4..a85ac1cd 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -3178,11 +3178,11 @@ void MainWindow::editEncryption()
         if(ok)
             ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_page_size = %1").arg(cipherSettings.getPageSize()), false, false);
         if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.kdf_iter = %1").arg(cipherSettings.getKdfIterations()), false, false);
+            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_hmac_algorithm = HMAC_%1").arg(cipherSettings.getHmacAlgorithm()), false, false);
         if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_hmac_algorithm = %1").arg(cipherSettings.getHmacAlgorithm()), false, false);
+            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_kdf_algorithm = PBKDF2_HMAC_%1").arg(cipherSettings.getKdfAlgorithm()), false, false);
         if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_kdf_algorithm = %1").arg(cipherSettings.getKdfAlgorithm()), false, false);
+            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.kdf_iter = %1").arg(cipherSettings.getKdfIterations()), false, false);
 
         // Export the current database to the new one
         qApp->processEvents();
```

This one is addressing points 1) and 3).

**Comment by justinclift** [comment]
With that patch applied... encryption seems to fully work!

Tested it here just now in my new local Win 7 build VM.  With this patch, I'm able to encrypt using:

* SQLCipher 4 default settings
* SQLCipher 3 default settings
* SQLCipher 4 default settings, but with 4k page size

The SQLCipher build is then able to correctly open the given encrypted database - but only if matching settings are given (good).

Our previous release - 3.10.1 - is also able to open the two databases done with SQLCipher 3 settings, and is unable to open the SQLCipher 4 one.

Looks like a win.  I'll create proper macOS and Win32/64 one-off test builds in a bit, and put them online for people to test as well. :smile:

**Comment by justinclift** [comment]
For reference, they encrypted databases are here:

* https://nightlies.sqlitebrowser.org/example_datasets/2.5mb/2.5mb-SQLCipher.4.defaults-abc123.sqlite
* https://nightlies.sqlitebrowser.org/example_datasets/2.5mb/2.5mb-SQLCipher.3.defaults-abc123.sqlite
* https://nightlies.sqlitebrowser.org/example_datasets/2.5mb/2.5mb-SQLCipher.3.default.and.4k.page.size-abc123.sqlite

They're all just an encrypted version of this one, and using the password of `abc123`:

&nbsp; &nbsp; https://dbhub.io/justinclift/2.5mb.sqlite

**Comment by justinclift** [comment]
Win64 builds with the test patch are online:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v1-win64.zip

**Comment by StevenMagdy** [comment]
I've Tested it and it's working perfectly.

**Comment by MKleusberg** [comment]
Awesome! Thanks for testing, everyone :smile: 

@justinclift I have just pushed a modified version of that patch. In theory it should do exactly the same but in a more proper way which is less error prone in case of future changes :wink: 

@StevenMagdy The weird UI might be because of PR #1684. Not sure though. @mgrojo, what do you think?

**Comment by justinclift** [comment]
> The UI is weird in this build though.

Yeah, I made the build using our development branch (`master`) code base, instead of doing it with our `3.11.x` code base.  So, you're seeing the current state of the development branch... can be a bit buggy at times. :wink:

**Comment by justinclift** [comment]
@MKleusberg So, best to make another build with the new code (eg directly from `master`), just to make sure it's 100% ok yeah? :smile:

**Comment by justinclift** [comment]
@StevenMagdy Looking at that screenshot... it kind of looks nifty.  "Zebra theme" maybe. :wink:

Not sure how it'd go on the eyes though, trying to use it for an extended amount of time. :grin:

**Comment by justinclift** [comment]
New builds, these ones are built from the 3.11.x series, with the updated patch applied:

Win32:

* *in progress*

Win64:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v2-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-issue1732v2-win64.zip

macOS:

* TBD

**Comment by chrisjlocke** [comment]
Using v2, I'm able to open an encrypted database created with v1.  Also able to create/open a database created with v2.
Seems to work OK for me.

**Comment by justinclift** [comment]
Excellent, thanks @chrisjlocke. :smile:

**Comment by StevenMagdy** [comment]
Tested V2, the encryption is working perfectly however, I'm still seeing the zebra theme on macOS. 😜

**Comment by justinclift** [comment]
Ok, that's weird. :frowning:

Oh... I bet the previous v1 build saved it's colour scheme when it exited.  Oops.

You may need to hit the "Reset Preferences" (or similar wording) button, in the Preferences dialog.

Sorry about that, didn't even think of it. :roll_eyes:

**Comment by StevenMagdy** [comment]
Nope, still there after I tried to remove the app with all its data from macOS.

**Comment by justinclift** [comment]
Okaaaaaaaaayyyyyy.  Some weird voodoo level thing is happening now. :imp:

k, "phone a friend time".  @mgrojo Please help. :smile:

**Comment by MKleusberg** [comment]
@justinclift Definitely makes sense to test the actual patch I committed again with the v3.11.x branch :smile: Unfortunately I don't have an idea either regarding the zebra look...

**Comment by mgrojo** [comment]
The pretty zebra look :wink: was already seen in this screenshot by @wmertens in [this comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-449860143). The dark mode is broken in Qt 3.11 and macOS Mojave. see [QTBUG-68891](https://bugreports.qt.io/browse/QTBUG-68891). I suppose the workaround is to disable the dark mode in macOS.

Given that it is said to be solved in 5.12.0 Alpha, we should try to apply the workaround described in [this comment in QTBUG-73721](https://bugreports.qt.io/browse/QTBUG-73721?focusedCommentId=446827&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-446827). I tried that, but don't know how to apply it to all the cells. Another option is disabling word wrapping altogether until the bug is solved (hopefully, because there is a bit of debate about it being a bug or not). The situation for mac users with dark mode is worst than loosing word wrapping, in my opinion.

**Comment by justinclift** [comment]
Thinking it over, if disabling dark mode support isn't too hard, we should do that for our 3.11.1 release, along with using Qt 5.11.3 for it.  That's probably the safest bet, which is the right kind of thing for our release code.

We can experiment with the word wrapping, dark mode (etc) + Qt 5.12 in the nightlies, as we're not under pressure to get an immediate, stable result there.

Is disabling dark mode support on macOS fairly simple to do?

**Comment by mgrojo** [comment]
I don't know if we can disable dark mode from our code. Indeed I was refering it as a possible workaround for the users to do. I suppose they have the dark mode enabled at the OS level. (I know, it's a shame they'd had to disable only because of DB4S).

**Comment by justinclift** [comment]
Ok.  I'm just not yet sure how we're supposed to proceed.

Our mac mini is too old to run macOS Mojave, and it seems like we need to be running that macOS release to get non-broken dark mode support for any macOS version user.

Hmm... maybe Mojave will work in a VM on the mac mini?  It wouldn't be efficient, but the thing is slow anyway, so no major difference there... :wink:

**Comment by justinclift** [comment]
> Our mac mini is too old to run macOS Mojave

macOS Mojave does seem to load and run in a VM, even though the host machine itself is too old.  Will see if the rest of the needed bits for doing builds also work.  If so, I'll make a test build for people to try the Dark Mode support with.

**Comment by MKleusberg** [comment]
I have just cherry-picked the encryption fix over to the 3.11.x branch. So at least the original issue here should be resolved now :smile:

**Comment by justinclift** [comment]
Excellent.  Thanks @MKleusberg. :smile:

**Comment by justinclift** [comment]
Well, this is a bit weird.  I'm able to compile DB4S on macOS Mojave... but the node based program we use for creating the pretty looking .dmg is crashing.

Attempting to build node on Mojave, specifically so it can be customised for our purposes, is failing on what seems like a bug in Homebrew.  Filed an issue for it just now: https://github.com/Homebrew/brew/issues/5741

Might be able to get around that with a manual install of node.  Not sure, will experiment.

**Comment by justinclift** [comment]
Fixed the node crashing problem, by using a manual install of Nodejs rather than the Homebrew provided one.

Created an initial "Dark Mode support" build of DB4S (from our `master` branch), and put it online for testing: https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-464075616

Going to close this (encryption) issue for now as it's been solved.  The Dark mode problem is being worked on in #1493. :smile:

**Comment by justinclift** [comment]
@StevenMagdy If you have a minute to try that new test build (for the Dark Mode problem), that'd be super useful: https://github.com/sqlitebrowser/sqlitebrowser/issues/1493#issuecomment-464075616 :smile:
