### ISSUE TITLE
When modifying a column in a table the whole table gets cloned before the final selection is made

### ISSUE THREAD

**Issue by gozzoo** [sqlitebrowser/sqlitebrowser#1734]
Details for the issue
--------------------
![image](https://user-images.githubusercontent.com/296970/52499712-b0c8d380-2be4-11e9-9149-0900d19b00bf.png)

#### What did you do?

I opened a table for editing and clicked the combobox for type selection. When I did that I saw in the SQL Log panel that the following comands get executed:

```
CREATE TABLE "sqlb_temp_table_24" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"person"	TEXT,
	"id_code"	TEXT,
	"active"	INTEGER NOT NULL DEFAULT 1,
	"in_dds"	NUMERIC,
	"address"	INTEGER,
	"phone"	INTEGER,
	PRIMARY KEY("id")
);
INSERT INTO "main"."sqlb_temp_table_24" SELECT "id","name","person","id_code","active","in_dds","address","phone" FROM "main"."company";
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = '1';
DROP TABLE "main"."company";
ALTER TABLE "main"."sqlb_temp_table_24" RENAME TO "company"
PRAGMA defer_foreign_keys = '0';
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
CREATE TABLE "sqlb_temp_table_25" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"person"	TEXT,
	"id_code"	TEXT,
	"active"	INTEGER NOT NULL DEFAULT 1,
	"in_dds"	NUMERIC,
	"address"	INTEGER,
	"phone"	INTEGER,
	PRIMARY KEY("id")
);
INSERT INTO "main"."sqlb_temp_table_25" SELECT "id","name","person","id_code","active","in_dds","address","phone" FROM "main"."company";
PRAGMA defer_foreign_keys
PRAGMA defer_foreign_keys = '1';
DROP TABLE "main"."company";
ALTER TABLE "main"."sqlb_temp_table_25" RENAME TO "company"
PRAGMA defer_foreign_keys = '0';
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
```
 

This means that the table gets re-created with the same definition, which doesn't make any sense. When I click on some type, the same thing happens again immediately. If I click something by mistake the whole table cloning happens again.

#### What did you expect to see?

I would expect the actual update of the table structure to happen when I click the OK button. If there are multiple changes they should happen then and not while selecting them.

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: (Win 7 32 bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Work on this is currently 'ongoing'.  If you are adventurous, you can download our nightly version (see link in your original post) which does do this.  I don't believe this has yet made its way into the last version.  HOWEVER, there is an issue with the nightly, where it doesn't copy data into the new table (which is why its a nightly....) but this issue has been reported.  Just waiting for development time for it to be resolved.

Thanks for reporting it though!

**Comment by gozzoo** [comment]
OK, great, Thanks for the effort. I see that it's included in 3.12. I hope that it will get released soon. 3.11 took quite a while.

**Comment by chrisjlocke** [comment]
3.11 has only just plopped out from the bowels of production.  I'd just keep an eye on the nightlies though, as once the current 'showstoppers' get 'unstopped', it could be worth a dabble.

**Comment by chrisjlocke** [comment]
I'll close this as we're aware of this particular issue, so best keep it simple and dupe-free.
Again, thanks for posting it though.  👍
