### ISSUE TITLE
Use YYYY-MM-DD instead of YYYY/MM/DD on the blog

### ISSUE THREAD

**Issue by ad-si** [sqlitebrowser/sqlitebrowser#1735]
Hi, it's great that you use a year-month-day order for your dates in your blogs.
However, you should use a `-` instead of the `/` for separating the fields. This would be in accordance with the international ISO8601 format and would make it easier to read as the `/` is normally associated with a MM/DD/YYYY order.
Sorry for the minor request, but this is a true pet peeve of mine 😅.

**Comment by justinclift** [comment]
Ahhhh, no worries.  We've only just recently started that blog, so still getting some of the kinks worked out.

I'll see if I can get it done now.  In theory, it should just need the characters changed in the `.Date.Format` lines:

* https://github.com/sqlitebrowser/website/blob/773c6cad387fe49cac03f201d3ec5d7e06970b06/themes/hugo-lithium/layouts/_default/list.html#L19
* https://github.com/sqlitebrowser/website/blob/773c6cad387fe49cac03f201d3ec5d7e06970b06/themes/hugo-lithium/layouts/_default/single.html#L13

**Comment by justinclift** [comment]
Yep, that worked. :smile:

**Comment by justinclift** [comment]
As a thought, you might want to make the same request of the upstream theme authors too:

&nbsp; &nbsp; https://github.com/jrutheiser/hugo-lithium-theme

"fix it at the source" kind of thing. :smile:

**Comment by ad-si** [comment]
Awesome, thanks! That was an impressive issue-to-solution time frame :grin:.

> As a thought, you might want to make the same request of the upstream theme authors too:
Good idea! Will open an issue ASAP

**Comment by ad-si** [comment]
But the template is using `{{ .Date.Format "January 2, 2006" }}` so I don't think this is applicable

**Comment by justinclift** [comment]
Oh, interesting.  That repo is the original upstream for the theme.  We actually got it from an R specific fork (https://github.com/yihui/hugo-lithium), which has it with the `/` symbols:

* https://github.com/yihui/hugo-lithium/blob/master/layouts/_default/list.html#L19
* https://github.com/yihui/hugo-lithium/blob/master/layouts/_default/single.html#L13

That fork is the default theme used for blogdown, which seems to be popular in the R Community.

Maybe just do a PR directly with the changes?  The author seems fairly busy/overloaded, but seems happy to hit the merge button for sensible PR's. :smile:

**Comment by ad-si** [comment]
There we go: https://github.com/yihui/hugo-lithium/pull/5

**Comment by justinclift** [comment]
No worries.  Turn around time for the PR's I've made on that repo is (so far) roughly about 1/2 day.  So, you shouldn't have to wait too long. :smile:
