### ISSUE TITLE
gpg signing key 79EAD0AB3BD7DD2C missing on keyservers

### ISSUE THREAD

**Issue by anthraxx** [sqlitebrowser/sqlitebrowser#1736]
Hi, it would be awesome if the git tags signed with the key 79EAD0AB3BD7DD2C could be verified. However, that key does not seem to be available on the regular keyservers (i tried 4 different keyservers).

Can you please upload that release key?

**Comment by justinclift** [comment]
Ahhh, that's mine.  I use gpg very rarely, so will need to look up exactly how to do that.

Adding it to my task list for tomorrow, as I'm sleepy atm and don't want to do gpg stuff while not 100% awake. :smile:

**Comment by justinclift** [comment]
In theory (!) it should now be available online.

Weirdly, the first two public key servers tried both seem to be having issues:

**keys.gnupg.net**
```
$ gpg2 --send-key 3BD7DD2C
gpg: sending key 3BD7DD2C to hkp server keys.gnupg.net
gpgkeys: HTTP post error 22: The requested URL returned error: 502 Bad Gateway
gpg: keyserver internal error
gpg: keyserver send failed: Keyserver error
```

**pgp.mit.edu**
```
$ gpg2 --keyserver pgp.mit.edu --send-key 3BD7DD2C
gpg: sending key 3BD7DD2C to hkp server pgp.mit.edu
gpgkeys: HTTP post error 22: The requested URL returned error: 408 Request Timeout
gpg: keyserver internal error
gpg: keyserver send failed: Keyserver error
```

"keyserver.ubuntu.com" worked though:

&nbsp; &nbsp; http://keyserver.ubuntu.com/pks/lookup?search=0x3BD7DD2C&op=vindex

Are you ok to verify it's ok from your point of view?

**Comment by anthraxx** [comment]
It worked, i have added it to some more keyservers, but the MIT one seems quite flaky nowadays.
Thanks a lot, will now release a source verified version :tada:

**Comment by justinclift** [comment]
Awesome! Thanks heaps @anthraxx. :smile:
