### ISSUE TITLE
"No known features for CXX compiler" with custom Clang on MacOS

### ISSUE THREAD

**Issue by cesss** [sqlitebrowser/sqlitebrowser#1737]
Details for the issue
--------------------

#### What did you do?
Try to build sqlitebrowser with cmake in Terminal, on MacOS 10.12.6 and a custom build of LLVM 7.0.0

#### What did you expect to see?
Successful build

#### What did you see instead?
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 7.0.0.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version: 10.12.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [ X] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
> Try to build sqlitebrowser with cmake in Terminal, on MacOS 10.12.6 and a custom build of LLVM 7.0.0

Co-incidentally, I was recently playing around with custom LLVM7 builds on macOS a few nights ago.

Didn't think to try compiling this with it though (was more for testing out [TinyGo](https://tinygo.org) on macOS).

Would you be ok to cut-n-paste in the CMake line used, and the rest of the CMake output?  Just in case there's useful info in it, for replicating the problem. :smile:

**Comment by tiendq** [comment]
@cesss It'd be helpful if you provide exact CMake commands you used and copy/paste CMake output here.

**Comment by justinclift** [comment]
Hmmm, it's been 10 days without any kind of response.  So, going to close this.

@cesss You're welcome to re-open this if we've closed this too early + you're still needing assistance. :smile:

**Comment by cesss** [comment]
Hi! I'm very sorry for my delay in replying, but got stuck with lots of work to do and couldn't reply sooner. Anyway, it seems that the build process really assumes you'll be using Homebrew and the Xcode compilers rather than your own (for example, I had to tune "src.pro" so that it uses my own sqlite build rather than the Homebrew build).

Anyway, can you provide me the command line procedure for building the DMG that you ship in the downloads section? The closest I got is with "qmake", but it lacks many of the stuff that the DMG has, like the math extension, the sqlcypher, and more things. I couldn't find the procedure you use for building the DMG. Maybe by knowing it I could make some progress... Thanks!!

**Comment by cesss** [comment]
Nevermind, found a script within the installer/macos directory, that seems to do the thing. Anyway, I see it really assumes to be built with Homebrew, and with your build tree conditions. Let me suggest to enhance this build procedure to make it more friendly with custom scenarios. For the time being, I'll be using the precompiled binary, because I'd need to modify the source and/or the project files, and I don't want to change the original contents of any package I build.

**Comment by justinclift** [comment]
> Let me suggest to enhance this build procedure to make it more friendly with custom scenarios.

It's not a bad idea.  So far it's just a script that fits our needs, but if you want to make sure work in a more generic fashion we're definitely open to PRs.

As a thought with the existing script, I tried to make much of it controllable through variables.  eg the path/location to things, values which need filling out, etc.  No idea how effective that really was though. :wink:
