### ISSUE TITLE
Attach database when main is encrypted

### ISSUE THREAD

**Issue by Z4us** [sqlitebrowser/sqlitebrowser#174]
If main is encrypted the version with SQLcipher seems to think all databases to attach are encrypted even when they are not.

**Comment by MKleusberg** [comment]
Thanks for noticing this! This issue should be fixed by commit f63b11925df2f7b538ef0f9f7da975e875aa5289 which, however, probably needs a bit more testing.

**Comment by justinclift** [comment]
@Z4us Do you have a few minutes to try out the fix in the next nightly build (from tomorrow onwards)? :smile:

**Comment by Z4us** [comment]
I took like 10 minutes tit test the build of MMXV-II-V and it works of course. I expected no less of MKleusberg. You guys rule! Keep up the great work on DB Browser4SQLite. Can we expect a 3.5.1 soon?

**Comment by MKleusberg** [comment]
Thanks for the kind words, @Z4us :smiley: Not sure if we're going to release a 3.5.1 but I hope 3.6 won't take that long :)

**Comment by justinclift** [comment]
Thanks guys, that's awesome. :grin:
