### ISSUE TITLE
Class 'NullLineEdit' lacks Q_OBJECT macro

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1740]
Setting up a Win 7 development environment with Qt Creator, in an attempt to figure out what's going wrong with the SQLCipher 4 encryption for new databases.

Interestingly, Qt Creator is throwing an error, even though MSVC 2017 compiles things ok:

```
Class `NullLineEdit` lacks Q_OBJECT macro
C:\git_repos\sqlitebrowser\src\AddRecordDialog.cpp    39
```

Which looks like this line:

https://github.com/sqlitebrowser/sqlitebrowser/blob/37361d8196566704499c50882b65556a975b155b/src/AddRecordDialog.cpp#L39

Anyone know if this is a legit error?  MSVC 2017 doesn't seem to complain about it.

**Comment by mgrojo** [comment]
I don't know if it's actually needed, but might be safer adding it.

**Comment by MKleusberg** [comment]
Pretty sure it's not needed - everything's working after all :wink: However, if I remember correctly the Qt moc gets confused if we add the Q_OBJECT macro without pulling out the class into a separate file. Pretty sure that's the only reason why we didn't add this before :smile:

**Comment by MKleusberg** [comment]
By the way, looks like this is a duplicate of #1628 :wink:

**Comment by mgrojo** [comment]
This change removes the warning:

```diff
diff --git a/src/AddRecordDialog.cpp b/src/AddRecordDialog.cpp
index 3b63afd5..f3428dda 100644
--- a/src/AddRecordDialog.cpp
+++ b/src/AddRecordDialog.cpp
@@ -12,6 +12,7 @@
 #include <QMenu>
 
 class NullLineEdit: public QLineEdit {
+    Q_OBJECT
 private:
     bool m_isNull;
 
@@ -338,3 +339,5 @@ void AddRecordDialog::on_buttonBox_clicked(QAbstractButton* button)
             populateFields();
     }
 }
+
+#include "AddRecordDialog.moc"
```

Should this be disregarded then?

**Comment by MKleusberg** [comment]
You're right! With the extra include it should be working fine :+1: Feel free to commit this then :smile:

**Comment by mgrojo** [comment]
Ok, commited.

**Comment by justinclift** [comment]
Tested this again on the same Win7 dev VM, and yep the build now succeeds without that warning.  Thanks @mgrojo. :smile:
