### ISSUE TITLE
Change SQL tab text via right click context menu

### ISSUE THREAD

**Issue by fossildoc** [sqlitebrowser/sqlitebrowser#1745]
Describe the new feature
--------------------------
Name SQL tabs.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
no

#### Does this feature exist in another product or project? Please provide a link.
no

#### Do you have a screenshot? Please add screenshots to help explain your idea.
no

**Comment by justinclift** [comment]
Which version are you using? :smile:

Asking because with the 3.11.0 betas, or the (mostly withdrawn) 3.11.0 release, if you double click on the tab name then a dialog should appear, asking for the new name.

**Comment by fossildoc** [comment]
3.11.99 You're right! I never thought of double-clicking. Most options like
this are usually accessed with a right click.

**Comment by justinclift** [comment]
Right click is an interesting idea too.  Probably wouldn't be too hard to implement.

@mgrojo @MKleusberg Does that sound feasible?  eg being able to change tab name via right click context menu, not just double clicking

**Comment by MKleusberg** [comment]
Definitely makes sense. However, it turns out that this is more complicated than it needs to be with Qt. So probably not going to happen soon - sorry.

**Comment by justinclift** [comment]
No worries.  Lets just leave it as double click then. :smile:

@fossildoc As above. :wink:

Going to close this issue, as technically the tabs can be renamed.  Has to be done via double clicking instead of right clicking though.
