### ISSUE TITLE
Enable Geopoly feature of SQLite

### ISSUE THREAD

**Issue by stefanofraccaro** [sqlitebrowser/sqlitebrowser#1752]
Describe the new feature
--------------------------
Can you enable the geopoly feature of sqlite?

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
SQLite
https://www.sqlite.org/geopoly.html

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No

**Comment by justinclift** [comment]
@stefanofraccaro Sounds like a good idea.  Should be fairly simple to get done too, for at least our macOS and Windows builds.

Which operating system are you using?

If it's either macOS or Windows, I can have a go at enabling it + make a build for that OS.  We'll need someone familiar with the feature to do basic sanity testing of it to make sure it's ok, before it goes into the main builds.

Is that something you'd be ok to help test with? :smile:

**Comment by stefanofraccaro** [comment]
I use Windows and Linux. Sure, I can help with tests  :-)
Thank you very much!

**Comment by justinclift** [comment]
Looking the Geopoly page, it also mention an [R*Tree option](https://www.sqlite.org/rtree.html) which looks like it might add further/better capabilities.

Should that be turned on as well? :smile:

**Comment by justinclift** [comment]
Hmmm, just added them both to the nightly Win64 build script, and re-ran it.  The build seems to have worked. :smile:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

Both of those are the same thing, just one has an installer (msi) and one doesn't (zip).  Pick whichever to try. :smile:

**Comment by stefanofraccaro** [comment]
Thank you very much for the very fast reply  :-)
I will try in the next days

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by stefanofraccaro** [comment]
SQLite has 7 compile options but there is not a "-DSQLITE_ENABLE_GEOPOLY" option. I checked it with the internal functions :
SELECT sqlite_compileoption_get(0..N);
SELECT sqlite_compileoption_used('DSQLITE_ENABLE_GEOPOLY');

If I create a table with "Execute SQL" an error appear : "no such module: geopoly". However on Database Structure I can see the table under Tables node.

**Comment by stefanofraccaro** [comment]
sorry, version 3.11.99 (Feb 21 2019)

**Comment by justinclift** [comment]
Ahhh. `-DSQLITE_ENABLE_GEOPOLY ` is the name of the option that needed to be given on the command line, when compiling the SQLite library itself.  Similarly, there's an option for the R-Tree one too.

So, the rebuilt Win64 nightly build has those enabled in it... which in theory :wink: should mean the appropriate function names are then available in the running program.  Personally, I've never (so far) used or touched either of these extensions before, so I don't have any knowledge about how to test things are working. :man_shrugging: 

In the [Geopoly](https://www.sqlite.org/geopoly.html) documentation page though, it does mention creating a new geopoly table:

```
CREATE VIRTUAL TABLE newtab USING geopoly(a,b,c);
```

... then storing polygons in it:

```
INSERT INTO newtab(_shape) VALUES('[[0,0],[1,0],[0.5,1],[0,0]]');
```

Those sound like the right pieces to get started with.  If you need to ping someone that has real world experience using them already, there would almost have to be appropriate people on the SQLite users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

Note, that's not be just fobbing you off.  There really should be the right people there for discussing this stuff. :smile:

**Comment by justinclift** [comment]
Actually... let me manually install and check the files in a VM here.  Just in case I mucked something up in the compile process, etc.  Gimme a few minutes... :smile:

**Comment by justinclift** [comment]
Ahhh, yep you're right.  Looks like those two options didn't actually get into the build for some reason. :frowning: 

As a data point, the pragma seems to be a better way to show what options the library was compiled with:

```
PRAGMA compile_options;
```

Returns a list of the options used, and they were both missing.  Ugh. :frowning: 

Ok, attempt 2 coming up shortly.  This time I'll watch the actual console as it compiles SQLite and SQLCipher.

**Comment by karim** [comment]
> As a data point, the pragma seems to be a better way to show what options the library was compiled with

The return list of `PRAGMA compile_options;` seems like a good thing to add to the About dialog. :smiley:

**Comment by justinclift** [comment]
Not sure.  Maybe we should add a "diagnostics" dialog under Help instead, that has all this info?

**Comment by stefanofraccaro** [comment]
IMHO a diagnostic dialog is a better choice :-)
I forget "PRAGMA compile_options"... +1

**Comment by karim** [comment]
Yeah, much better idea.

**Comment by justinclift** [comment]
Ok, the (re-rebuilt) Win64 nightly er... build definitely has both options this time.  Installed and checked manually (using the PRAGMA) this time, just to be sure. :smile:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

**Comment by stefanofraccaro** [comment]
Sorry for the late reply but I was sick. I will check in few days    ;-)

**Comment by justinclift** [comment]
Thanks @stefanofraccaro, that'd be really helpful. :smile:

**Comment by stefanofraccaro** [comment]
I'm trying with a long sql script but it is imported very slowly (2-3 seconds per row). If I stop the running script with the "stop" button, the program throw an unhandled exception and exits. 
Before running the script, create the table as
CREATE VIRTUAL TABLE poligoni USING geopoly(tipo, nome);

The sql script is available at:
https://fraccaro.org/dl/geopoly.sql

**Comment by justinclift** [comment]
Interesting.  Some of the lines in that file are very long.  My text editor (kwrite in this instance) also didn't like it. :wink:

Guessing this kind of thing (very long lines) is probably standard for geopoly lines.  If that's the case, we'll probably need to optimise stuff a bit.

Still... 2-3 seconds per row sounds excessive, even when non-optimised.

As a thought, if you get rid of the BEGIN TRANSACTION clause on the first line (and the corresponding one on the end, though I didn't check if that's there)... does it import any faster?

**Comment by stefanofraccaro** [comment]
'Begin transaction' on the first line does not change the import speed. SQLite result tell me 140-300 ms/row but the program runs 1 row every 2-3 seconds (i3 with virtualbox vm). I think there is something on the user interface that is slow with long lines.

**Comment by justinclift** [comment]
Thanks @stefanofraccaro.  Looks like an opportunity for performance tuning, if someone wants to get into that side of things. :smile:

**Comment by stefanofraccaro** [comment]
All geopoly functions seems working as expected  :-)

**Comment by MKleusberg** [comment]
@stefanofraccaro Do you still have these weird performance problems with the latest nightly build? If so, can you open a new issue for that because it sounds severe enough that we should definitely look into that :frowning: 

I'm going to close this issue however because the geopoly functions are working :smile:
