### ISSUE TITLE
After using the 64bit windows msi installer I can't associate .db3 files.

### ISSUE THREAD

**Issue by kharaktur** [sqlitebrowser/sqlitebrowser#1753]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.1 [built for i386-little_endian-ilp32] on Windows 7 SP 1 (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.27.1
> and Qt 5.7.1

**Comment by kharaktur** [comment]
I had to remove the 64bit install and use the 32 bit one. After the 64bit install I was unable to associate sqlite files (.db3) with DB Browser.

**Comment by chrisjlocke** [comment]
Windows is a bit funny with its associations.
It has to be hugged and coaxed to get it to do what you want.
When you say, "I was unable to..." what actually happened - did you get an error?  Did it just not show DB4S as an application to associate with?

**Comment by kharaktur** [comment]
Would not show DB4S as an application and when selected by searching it would not use it (ok button disabled.) 32bit version works as expected.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 02/20/2019, 2:37 PM Chris Locke <notifications@github.com> wrote:
Windows is a bit funny with its associations.
It has to be hugged and coaxed to get it to do what you want.
When you say, "I was unable to..." what actually happened - did you get an error?  Did it just not show DB4S as an application to associate with?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sqlitebrowser/sqlitebrowser","title":"sqlitebrowser/sqlitebrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sqlitebrowser/sqlitebrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chrisjlocke in #1753: Windows is a bit funny with its associations.\r\nIt has to be hugged and coaxed to get it to do what you want.\r\nWhen you say, \"I was unable to...\" what actually happened - did you get an error?  Did it just not show DB4S as an application to associate with?"}],"action":{"name":"View Issue","url":"https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465723603"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465723603",
"url": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465723603",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by karim** [comment]
@kharaktur Did you try clicking *Browse...* and locating the installation folder and then select the application .exe?

File association is controlled by Windows itself. Also, the installer does not mess with it and does not try to set itself with any file extension.

**Comment by justinclift** [comment]
@karim We should probably check to see if there's some way to automatically do the associations.  It was something people were requesting a while back, and would be useful. :smile:

**Comment by karim** [comment]
@justinclift Yes, it is possible and easy. Just add a few registry entries during installation. But which file extensions (.db3? .sqlite3?) and which .exe (SQLite or SQLCipher) will get it?

**Comment by justinclift** [comment]
Hmmm, the extensions should probably be the same as the default ones we list in our dialogs.  eg:

* db
* db3
* sqlite
* sqlite3

References:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/8ddfa7592945873281b9a1f2a79a0c8934bd0009/src/app.plist#L12-L15
* https://github.com/sqlitebrowser/sqlitebrowser/blob/8ddfa7592945873281b9a1f2a79a0c8934bd0009/src/Settings.cpp#L178

For which exe... hmm... that's a really good question.  Let's just pick the SQLCipher one, as that's the superset which provides more capabilities.  I **think** it's fairly unusual for people to need the absolutely latest and greatest SQLite ones (eg 3.27.1 vs 3.26.0), so that should be a fairly safe choice. :smile:

**Comment by karim** [comment]
Looks like a good plan, yes. I will get it done.

**Comment by kharaktur** [comment]
Yes, using browse fails, I can target the executable but the ok button to associate is disabled.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 02/21/2019, 4:04 AM Karim ElDeeb <notifications@github.com> wrote:
@kharaktur Did you try clicking Browse... and locating the installation folder and then select the application .exe?
File association is controlled by Windows itself. Also, the installer does not mess with it and does not try to set itself with any file extension.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sqlitebrowser/sqlitebrowser","title":"sqlitebrowser/sqlitebrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sqlitebrowser/sqlitebrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@karim in #1753: @kharaktur Did you try clicking *Browse...* and locating the installation folder and then select the application .exe?\r\n\r\nFile association is controlled by Windows itself. Also, the installer does not mess with it and does not try to set itself with any file extension."}],"action":{"name":"View Issue","url":"https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465918211"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465918211",
"url": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-465918211",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by karim** [comment]
Try `Control Panel > Default Programs` and select *Associate a file type or protocol with a program*, and check if the file type is already registered with an application and try changing it from there.

This comment (https://github.com/sqlitebrowser/sqlitebrowser/issues/1674#issuecomment-448854105) has more details with some screenshots on how to do it.

Also please note that file associations are saved in Windows Registry and a 32-bit applications can't set/modify a 64-bit settings for example. Maybe try uninstalling DB Browser for SQLite first and then re-install the 64-bit version. Do not upgrade/update over it.

**Comment by chrisjlocke** [comment]
Apparently with Windows 10, using scripts and fiddling with the registry directly is a 'no no'.
https://blogs.technet.microsoft.com/windowsinternals/2017/10/25/windows-10-how-to-configure-file-associations-for-it-pros/

Using @karim method of via the control panel is the only way.
I've had it before with Windows refusing to acknowledge a program - select the .exe and Windows just ignores it (doesn't add it to the list so it can be selected).  I can't replicate it on my current Windows 10 build though (64bit Pro)

**Comment by kharaktur** [comment]
I'm using Windows 7 pro, I'll just use the 32 bit version for now, works as expected. As an aside I added the ppa to Ubuntu and updated, works perfectly. (Wish I didn't need Windows for work, <sigh>) Thanks for your help, you guys ROCK.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 02/21/2019, 11:54 AM Chris Locke <notifications@github.com> wrote:
Apparently with Windows 10, using scripts and fiddling with the registry directly is a 'no no'.
https://blogs.technet.microsoft.com/windowsinternals/2017/10/25/windows-10-how-to-configure-file-associations-for-it-pros/
Using @karim method of via the control panel is the only way.
I've had it before with Windows refusing to acknowledge a program - select the .exe and Windows just ignores it (doesn't add it to the list so it can be selected).  I can't replicate it on my current Windows 10 build though (64bit Pro)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sqlitebrowser/sqlitebrowser","title":"sqlitebrowser/sqlitebrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sqlitebrowser/sqlitebrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chrisjlocke in #1753: Apparently with Windows 10, using scripts and fiddling with the registry directly is a 'no no'.\r\nhttps://blogs.technet.microsoft.com/windowsinternals/2017/10/25/windows-10-how-to-configure-file-associations-for-it-pros/\r\n\r\nUsing @karim method of via the control panel is the only way.\r\nI've had it before with Windows refusing to acknowledge a program - select the .exe and Windows just ignores it (doesn't add it to the list so it can be selected).  I can't replicate it on my current Windows 10 build though (64bit Pro)"}],"action":{"name":"View Issue","url":"https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466077116"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466077116",
"url": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466077116",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by justinclift** [comment]
> I'll just use the 32 bit version for now, works as expected.

Good thinking. :smile:

**Comment by kharaktur** [comment]
This may be a little off topic, but in this version execute current line Shift+F5 doesn't stop after the current line. I have to comment other lines or they run. Version 3.11.1 (32bit Windows)
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 02/21/2019, 12:19 PM Justin Clift <notifications@github.com> wrote:


I'll just use the 32 bit version for now, works as expected.



Good thinking. 😄



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sqlitebrowser/sqlitebrowser","title":"sqlitebrowser/sqlitebrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sqlitebrowser/sqlitebrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@justinclift in #1753: \u003e I'll just use the 32 bit version for now, works as expected.\r\n\r\nGood thinking. :smile:"}],"action":{"name":"View Issue","url":"https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466086396"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466086396",

"url": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1753#issuecomment-466086396",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by chrisjlocke** [comment]
@kharaktur - you can't put 'off topic' issues in completely random issues.  If you have an issue with the 'Execute SQL' tab, please open a new issue for it.  This is so it can be properly tracked and acted upon.

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
