### ISSUE TITLE
Add support for displaying the SQLite errorlog

### ISSUE THREAD

**Issue by Drachenkaetzchen** [sqlitebrowser/sqlitebrowser#1754]
Display the SQLite error log
--------------------------
SQLite starting from 3.8.0 emits a warning to the [error and warning log](https://www.sqlite.org/errlog.html) if an [autoindex](https://www.sqlite.org/optoverview.html#automatic_indexes) is created. It would be useful to display the errors (or: warnings) in order to analyze queries and optimize indexes.

**Comment by justinclift** [comment]
Sounds like a good idea @Drachenkaetzchen. :smile:

**Comment by MKleusberg** [comment]
You're right, this definitely make sense :smile: I have just added a new section to the SQL log panel. Besides 'User' and 'Application', you can now choose 'Error Log' and get all the log messages we get from SQLite. The only thing is that the font isn't right yet - QScintilla doesn't seem to respect our choice here unless we install a lexer. Can you check tomorrow's nightliy build (assuming you're using Windows or macOS) and see if it's working for you? :smile:

**Comment by justinclift** [comment]
@Drachenkaetzchen Have you had a chance to check the nightly builds, to see if the change is working ok from your point of view? :smile:

**Comment by Drachenkaetzchen** [comment]
> @Drachenkaetzchen Have you had a chance to check the nightly builds, to see if the change is working ok from your point of view? 😄

Unfortunately no, but I'll check it out when I next encounter the autoindex stuff (which could be quite some time). You are way too quick implementing stuff ;)

**Comment by MKleusberg** [comment]
Since I'm pretty sure it's going to work fine, I'll just close this issue proactively :smile: If it turns out it's not working as expected after all, please just re-open this issue, @Drachenkaetzchen :smile:
