### ISSUE TITLE
[View Cell Editing] Enabling editing in "Edit Database Cell" Widget when a view is editable

### ISSUE THREAD

**Issue by cristilupascu** [sqlitebrowser/sqlitebrowser#1756]
Details for the issue
--------------------

#### What did you do?
Created a view, wrote triggers for update and made the view editable. The cells can now be modified from the "Browse Data" tab by clicking on a cell and inputting text but I can't do the same from "Edit Database Cell".

#### What did you expect to see?
To be able to enter text using "Edit Database Cell", and making the "Apply" button active.

#### What did you see instead?
"Edit Database Cell" doesn't let me modify the text at all.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 7)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.1
- [ ] 3.11.0
- [ ] 3.10.1
- [x] Other: 3.11.99

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @cristilupascu.  Sounds like a fairly simple bug to fix. :smile:
