### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by malitech** [sqlitebrowser/sqlitebrowser#176]
Hello,

I want to re-create an index for a database file and it has to be similar to the previous formatting. To have that, I want an option "None" for sorting of an index. Now there are "ASC" and "DESC" only. I don't want any sorting. Please add this. It's very important. Thanks! :)

Before:
(
    key_remote_jid,
    key_from_me,
    key_id
)

After:
(
    key_remote_jid, ASC,
    key_from_me, ASC,
    key_id, ASC
)

**Comment by justinclift** [comment]
@malitech Out of curiosity, have you had a chance to try out the latest nightly build?

Wondering if this is working well for you now or not. :wink:

**Comment by malitech** [comment]
Hello, I checked it out right now. Works great. Thanks. :)

**Comment by justinclift** [comment]
Excellent.  Thanks for verifying. :grinning:
