### ISSUE TITLE
DB icon crossed out on Mac OS 10.13.6

### ISSUE THREAD

**Issue by MooersLab** [sqlitebrowser/sqlitebrowser#1760]
Details for the issue
--------------------

#### What did you do?

When I open the dmg file, the DB icon has a circle and slash on it.
I had several older versions in my Applications folder.
They too switched to having the crossed sign on them as soon as I opened the dmg file.
I then tried to install with home brew and got the same result. 

#### What did you expect to see?
The regular icon only. 

#### What did you see instead?
When I click on the icon, a message says that the application is damaged or incomplete.

I tried downloading and installing it several times. 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_10.13.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.1
- [ ] 3.11.0
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Haven't heard of this behaviour before, so will probably need to set up a 10.13.6 VM or similar to test it in.

Have you seen this happen with other applications too, and/or is there any kind of warning/error/etc about what the problem is? :smile:

**Comment by MooersLab** [comment]
Thank you Justin for the suggestions. 

I reset my PRAM memory, and this clear up the problem.

**Comment by justinclift** [comment]
Excellent.  Glad you figured it out @MooersLab. :smile:

**Comment by baltakatei** [comment]
I also ran into this problem but I believe the cause was a failure in the building process; instead of the usual 18 megabyte `.dmg` file, it was [about 3 megabytes](https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20210116.dmg) in size. Using [an earlier](https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20210111.dmg) nightly build fixed the problem. No PRAM reset was necessary.

![Screenshot from 2021-01-16 22-50-52](https://user-images.githubusercontent.com/40225041/104824837-5f540500-584d-11eb-9827-c859b2ad5544.png)

**Comment by chrisjlocke** [comment]
Excellent - thanks for the report.  I'm sure @justinclift would just luuuurve to look into this... ;)
Both .dmg images are poopy.

![image](https://user-images.githubusercontent.com/7872218/104827077-f02cdf80-5851-11eb-8820-31c99f349593.png)

**Comment by justinclift** [comment]
@baltakatei In theory, we've fixed the building process for those .dmg files.

Would you be ok to test one of these (either is fine) and let us know how it goes?

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite.dmg
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

**Comment by baltakatei** [comment]
I installed `https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg` and was able to decrypt a database.

The "About DB Browser for SQLite" dialogue contained this version information:

> DB Browser for SQLite Version 3.12.99 (Jan 20 2021)
> Built for x86_64-little_endian-lp64,running on x86_64
> Qt Version 5.15.2
> SQLCipher Version 4.4.0 community (based on SQLite 3.31.0).

The DB icon does not appear crossed out when I mount either dmg you linked in my macOS Big Sur Version 11.1 machine.

Thank you for your work. :smiley:

**Comment by justinclift** [comment]
Awesome.  Thanks heaps for verifying it @baltakatei. :smile:
