### ISSUE TITLE
Better sorting in Browse Data tab

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#1761]
Describe the new feature
--------------------------
You can click on a column header to sort by that column and you can click again to change the sort order. But that's about it.

We should add a possibility to "remove" any sorting, i.e. go back to sorting by rowid but without having to show the rowid column.

We should also add a possibility to sort by multiple columns. Maybe this requires a new dialog.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
Removing a sort order is mentioned in #1758. I'm sure sorting by multiple columns was mentioned several times but I can't find an issue at the moment.

#### Do you have a screenshot? Please add screenshots to help explain your idea.

>

**Comment by justinclift** [comment]
One approach I've been exposed to recently (via JetBrains Datagrip) is where clicking on one column selects it for sorting (as per now), but when clicking on a 2nd column that then adds the 2nd column as a secondary sort.  eg rows are sorted by the first column, and where rows match they're then sorted according by the 2nd.

For individual column selection, it's a case of 1st click selects the column, a 2nd click on it reverses the sort, and a third click removes the sorting for that column.  eg 1 = on, 2 = reverse, 3 = turn it off

**Comment by mgrojo** [comment]
For sorting on multiple columns, we have  #1409.

> One approach I've been exposed to recently (via JetBrains Datagrip) is where clicking on one column selects it for sorting (as per now), but when clicking on a 2nd column that then adds the 2nd column as a secondary sort. eg rows are sorted by the first column, and where rows match they're then sorted according by the 2nd.

This is an option, but the drawback is that single column sorting requires more clicks than now. Which action would be more frequent? I'd say that single column sorting.

Another option without resorting to the dialog is to use a new option in the context menu of the column (e.g. "Add column to sorting"?). We should add in any case visual feedback in the column header about the order of columns in the sorting. This might be more trickier than the rest of the implementation. With a dialog, it would be less necessary, because you could open again the dialog to check.

**Comment by justinclift** [comment]
Hmmm, I guess I explained it badly.  To sort by a single column with the way the JetBrains program does it... you just click on a column (once), same as with us. :smile:

It's just that if you then click on a different column, that becomes a secondary sort column.

**Comment by mgrojo** [comment]
> It's just that if you then click on a different column, that becomes a secondary sort column.

You've explained it well :smile: I mean, how do you change from a sort on single column A to a sort on a single column B? With us is just clicking B. With JetBrains I understand that you have to click A until the sorting disappears and then you click B. Maybe there is a reset sort button, but it is still more work than with the current approach.

**Comment by justinclift** [comment]
Ahhh yeah.  You're right, that would be more work. :smile:

But it does give us the ability to sort on more than one column, which is useful for lots of situations.  There might be a better approach anyway, I was just sharing an approach which I've seen in use recently and works ok.

**Comment by mgrojo** [comment]
Of course, and I'm not discarding it, just assessing the different options.

**Comment by karim** [comment]
Clicking once on a column header sort it, clicking again sort it in the opposite direction. Clicking on a different column change the sorting to the new column. This is the current behavior, and I agree with Manuel, there's no need to change that, as it is the most common action.

Remove sorting is the one we are discussing here. The current behavior is..

1. Right-click and select "Show rowid column"
2. Click on its header to sort by rowid
3. Right-click and unselect "Show rowid column"

which is not ideal. Maybe...

- Right-click and "remove sorting", "reset sort", "sort by rowid", etc
- Press and hold the header for a few seconds to reset
- Middle-click (middle mouse button)
- Something else? :smiley: 

There is also *group sorting* by multiple columns. I don't know if it is also discussed here or not. But if yes, then how about using an extra key, like Ctrl?

If a column is clicked while a key is pressed (Ctrl) then the old column is added to a list, with the new column, and sorting is done on both (`ORDER BY old_column, new_column`). Clicking on more columns, while Ctrl is pressed, keeps adding the columns to this list. Clicking on a column without Ctrl is pressed reset the list and goes back to one-column sort.

**Comment by MKleusberg** [comment]
I actually like @karim's idea about holding the Ctrl key to add more columns to the sorting. This way we wouldn't change the current behaviour too much. However, we would need to decide a) how and when it is possible to change the sort direction of a column, b) what would happen if you try to add a column twice to the list, and c) how to show the current sort order in the UI.

Finally there is the question of whether we want to support sorting by expressions (as in ```ORDER BY column1+column2```). This would definitely be awkward to do in the Browse Data tab and we probably should not try to base our choices on this use case. But I thought I'd mention it anyway :wink:

**Comment by MKleusberg** [comment]
I just fixed a minor problem in the sorting code. From the commit message:
When changing the sort column in the Browse Data tab we always toggled
the sort direction too. So when Field1 was sorted in ascending order,
clicking on Field2 would sort it in descending order. If Field1 was
sorted in descending order, clicking on Field2 would sort it in
ascending order. Now in both cases Field2 is sorted in ascending order
first.

**Comment by MKleusberg** [comment]
I have just pushed a first version of the sorting by multiple columns feature. As @karim suggested it works by holding the Ctrl key. Note that while working, this is still more like a demo. I was mainly trying to get the backend bits working correctly. So the UI is still far from perfect. Here are a few problems:
1) No sort indicators. The indicator is currently always placed on the first sort column.
2) Still no way to unset the sort order.
3) The Ctrl key might be a bit unfortunate because it's normally used for multi column selection.
4) You can add a column multiple times to the list.

**Comment by karim** [comment]
> a) how and when it is possible to change the sort direction of a column

I'm thinking holding Ctrl merely add a column to the sorting group, nothing more. There's no need to change that as it might confuse users.

Also, the order of clicking columns while holding Ctrl is important. It defines the sorting order. It is like First-in First-sort kinda of thing. :smiley: 

If I have a table with 4 columns (A, B, C, D) and I clicked column B then column D, it will always be `ORDER BY B, D`. Clicking on column A will add it to the list and make it `ORDER BY B, D, A`. Clicking on B again will just change its direction (`ORDER BY B DSEC, D, A`) while keeping the same order.

If you want to change the order of columns (to be A, B, C for example) you can do so by simply clicking on any column without holding Ctrl, to clear the sort group list (and switch to single sort), and start over.

> b) what would happen if you try to add a column twice to the list

As the above point mentioned, you can't. You can click as many times as you want on a column without a problem, or any change in behavior while sorting by a single or multiple columns.

I guess the group sort should be something like a data structure, holding the number of columns, their order, and their direction only. Clicking on a column that isn't in this list add it to it (and re-run the SQL query to sort). Click on a column that is already in the list just change its direction, like how it is done in single sort (also and re-run the SQL query).

> c) how to show the current sort order in the UI.

I don't know if it is possible to add any GUI element to the column header, just like the small arrow you see when you sort a column. If possible maybe add a little number like [1] on first column, etc. Something like an application icon badge when you get a new mail or notification from an app on your phone.

If not then maybe show some text on top, next to the New/Delete Record buttons, or on bottom next to the number of records in the table. I'm not sure what should be the sorting message though. Something like "Sorted by: columnA ascending, columnB descending"?

> Finally there is the question of whether we want to support sorting by expressions (as in `ORDER BY column1+column2`).

I think Browse Data should handle basic/simple sorting only. Just a single and group sort. Any more complicated sort should be done using Execute SQL tab.

**Comment by justinclift** [comment]
When clicking on a column to sort direction, could we have it so a third click on the column removes it from the sort.  eg 1st click = up, 2nd click = down, 3rd click = "removed from the sort column list" ?

**Comment by mgrojo** [comment]
For the UI, we could use all the power of Unicode for the sort indicators. I mean, we have these characters:

¹²³⁴⁵⁶⁷⁸⁹
▴ ▾

We could try something like this:

| columnA  ▴²  | columnB   ▾¹ | columnC | columnD  ▾⁴ | columnE ▴³
| ------------- | ------------- |------------- |------------- |------------- |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |

Another option that I suppose is possible, it's adding icons, but how many icons would we add to indicate the position inside the sorting group?

Quick test for the characters. (This is a trick. I created a table with those names :smile:)
![imagen](https://user-images.githubusercontent.com/13812910/53659521-0e889280-3c5c-11e9-97ff-5148e977e3c6.png)

Source:
```sql
CREATE TABLE "SortIndicators" (
	"columnA	▴²"	INTEGER,
	"columnB	▾¹"	INTEGER,
	"columnC"	INTEGER,
	"columnD	▾⁴"	INTEGER,
	"columnE	▴³"	INTEGER
)
```

**Comment by justinclift** [comment]
> We could try something like this:
>
> | columnA  ▴²  | columnB   ▾¹ | columnC | columnD  ▾⁴ | columnE ▴³
> | ------------- | ------------- |------------- |------------- |------------- |
> | Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |
> | Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |

That looks really, really good to me. :smile:

**Comment by karim** [comment]
> For the UI, we could use all the power of Unicode for the sort indicators. I mean, we have these characters:
> 
> ¹²³⁴⁵⁶⁷⁸⁹
> ▴ ▾

Yesssss. :smiley: 

This is very good.

**Comment by mgrojo** [comment]
These are even more similar to the typical triangles used to indicate sorting:
⏶⏷

Let's compare them to the former:

| columnA  ⏶²  | columnB   ⏷¹ | columnC | columnD  ⏷⁴ | columnE ⏶³
| ------------- | ------------- |------------- |------------- |------------- |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  | Content Cell  |

**Comment by justinclift** [comment]
To me, I think the first ones look better.  They're a bit bigger in size, and the direction number is closer.

That being said... the size of either could be manually changed with some creative font handling anyway. :smile:

**Comment by mgrojo** [comment]
@MKleusberg, unless you are already working on it or planning to do it, I'd like to implement the column sort indicators as described in https://github.com/sqlitebrowser/sqlitebrowser/issues/1761#issuecomment-468772667

**Comment by mgrojo** [comment]
I couldn't wait and I'm working on it.

This is how it's looking:
![imagen](https://user-images.githubusercontent.com/13812910/54561034-00f53b80-49c4-11e9-91b3-64e2aef86b15.png)

I'd like the sort indicator to be right aligned like the Qt default, but there doesn't seem to be an easy way. Otherwise, it's working fine.

**Comment by justinclift** [comment]
> I'd like the sort indicator to be right aligned like the Qt default

Maybe split each field into three pieces horizontally, with the left being the field info, the middle being an expanding spacer, and the right being the sort indicators?

    [field]<-- automatic spacer -->[sort indicators]

**Comment by MKleusberg** [comment]
We would probably need to subclass the table view to add our own header implementation to support that because with Qt's implementation we are limited to a single Unicode text field with apparently no support for HTML/CSS styles. In that case, it's probably not worth the effort for now :smile: What do you reckon? Should we close this issue then?

**Comment by justinclift** [comment]
Yep, it seems to be working ok.  We can do refinements in further issues/PRs. :smile:
