### ISSUE TITLE
Decrease padding in UI

### ISSUE THREAD

**Issue by maratumba** [sqlitebrowser/sqlitebrowser#1762]
Describe the new feature
--------------------------
It would be great if you could decrease or remove padding around elements (Especially in Execute SQL view) that take so much screen space. An option to hide the toolbar in Execute SQL would also be great. In an equivalent view in SQLPro for SQLite, you get to see 31 lines of code instead of 24 lines and with even a larger font. This makes a big difference especially in smaller screens.

Also the padding around the db schema tree view is not necessary and would be great if it can be removed.

Showing main tab buttons can also be optional and maybe added to the menus.

Additional info
---------------
#### Is your feature request related to an issue? Please include the issue number.
Not as far as I can tell.

#### Does this feature exist in another product or project? Please provide a link.
[SQLPro for SQLite](https://www.sqlitepro.com/)

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![image](https://user-images.githubusercontent.com/2898911/53287266-c1ec1580-378a-11e9-88f0-61c6040d8118.png)

Equivalent in SQLPro for SQLite:
![image](https://user-images.githubusercontent.com/2898911/53287533-98cd8400-378e-11e9-963a-a87cdce14b17.png)

**Comment by mgrojo** [comment]
We can reduce those margins by changing some attributes, but don't know why they seem bigger in macOS. Toggling the toolbar requires more effort, so it might not happen soon.

**Comment by mgrojo** [comment]
@maratumba I've reduced some of the margins and it should provide more space for the content now, at least, it does in Linux. But it requires testing in other platforms. Could you take a look with [tomorrow's nightly](https://nightlies.sqlitebrowser.org/latest/)?

Someone should take a look also to the Windows build.

**Comment by maratumba** [comment]
Of course, thank you for quick response!

**Comment by maratumba** [comment]
Checked the nightly, looks much better @mgrojo.

**Comment by chrisjlocke** [comment]
Thanks @mgrojo for the amendment.

**Comment by maratumba** [comment]
Should I create another issue for my request of making the toolbar toggle-able?

**Comment by justinclift** [comment]
Yep. :smile:
