### ISSUE TITLE
Sorting and filtering causes flickering

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#1763]
Details for the issue
--------------------

#### What did you do?
Click on column header for sorting or set a new filter.

#### What did you expect to see?
A smooth update of the browsed table.

#### What did you see instead?
A flickering is produced in the table header, due to the filter tables displayed first at the rightmost side while the table is reset and then it repaints itself when the rows appear, leaving space to the vertical header with the row numbers. See this [video](https://github.com/sqlitebrowser/sqlitebrowser/files/2893316/blinking.table.mp4.zip) provided by @HGZwebdesign in https://github.com/sqlitebrowser/sqlitebrowser/issues/1758#issuecomment-466339213

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
- All

#### What is your DB4S version?
- 3.11.1
- 3.11.0
- Latest nightly

**Comment by MKleusberg** [comment]
Thanks for looking into this, @mgrojo! :smile: Should we close this issue too?

**Comment by mgrojo** [comment]
@MKleusberg, yes, I'll close it now, since it's confirmed in  #1941.

@HGZdev, for your information, this is fixed in our nightly builds and will be included in our next release.
