### ISSUE TITLE
CASE-SENSITIVITY: Error importing data from SQL file: cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by jsejcksn** [sqlitebrowser/sqlitebrowser#1764]
Details for the issue
--------------------

#### What did you do?

1. File  > New In-Memory Database
2. Modal: _Edit table definition_ > Cancel
3. File > Import... > Database from SQL file...
4. Modal: _Create new database_ > No

`export.sql`:

``` sql
begin transaction;
create table names(
  id integer primary key,
  name text unique
);
commit;
```

#### What did you expect to see?

My SQL file imported into the in-memory database

#### What did you see instead?

Alert:  
> Error importing data: Error in statement #<span></span>1: cannot start a transaction within a transaction. Aborting execution and rolling back

#### Other notes

Using this file instead produces no error:

`export-case-sensitive.sql`:

``` sql
BEGIN TRANSACTION;
CREATE TABLE names(
  id integer PRIMARY KEY,
  name text UNIQUE
);
COMMIT;
```

Useful extra information
-------------------------

macOS: _10.14.3_  
DB4S: _3.11.1 r2_

#### Did you also

- [ ] [Try out the latest nightly version](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds)
- [x] [Search for an existing similar issue](https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20)

Possibly related to #568, #675

**Comment by jsejcksn** [comment]
Not sure why there is a case-sensitivity rule in place. Is this a trivial fix or big refactor?

**Comment by justinclift** [comment]
> Not sure why there is a case-sensitivity rule in place.

From rough memory, we use a regex to detect & remove existing transaction statements inside .sql files (so we can do the start/end of transaction in-application).  It's **probably** just a matter of making the regex case insensitive. :smile:

**Comment by mgrojo** [comment]
This might have been easy if this issue had been opened before #1045 :smile:. Then the replacement was used with a regexp, and it'd have been easy to add the case-insensitivity flag. But after the optimizations done in d783d36dbde97e04827009b6a84d18a984266117 it is no longer possible, because a `QByteArray` is used instead of a `QString`, and the former lacks regexp versions for `contains` and `replace`. @MKleusberg was aware of the shortcommings, according to his TODO comments :smile: So we have to decide now between performance and reliability. As a minimal solution, we could replace "begin transaction" as well as "BEGIN TRANSACTION".

**Comment by justinclift** [comment]
> As a minimal solution, we could replace "begin transaction" as well as "BEGIN TRANSACTION".

That's probably good enough for now.  It's unlikely people will (in the real world :wink:) use stuff like 'BeGiN traNsACtion`.  Hopefully. :grin:

**Comment by MKleusberg** [comment]
I have seen ```Begin transaction;``` or even ```Begin Transaction;``` too :wink:

**Comment by MKleusberg** [comment]
By the way, some more problems are:
```sql
BEGIN     TRANSACTION ; -- Multiple spaces here. Not detected.
END TRANSACTION; -- We're not even looking for this.
BEGIN DEFERRED TRANSACTION; -- We're not expecting any qualifiers between the two words.
INSERT INTO sql_log VALUES('BEGIN TRANSACTION;'); -- Statement gets modified
```

**Comment by MKleusberg** [comment]
I think the issue should be fixed now. The other problems I mentioned in my last comment should be fixed too :wink: 

@jsejcksn Can you check if it is working for you with one of the next nightly builds?

**Comment by jsejcksn** [comment]
``` shell
rm -r /Applications/DB\ Browser\ for\ SQLite.app
rm ~/Library/Preferences/net.sourceforge.sqlitebrowser.plist
rm -r ~/Library/Saved\ Application\ State/net.sourceforge.sqlitebrowser.savedState
```

``` shell
shasum -a 256 DB.Browser.for.SQLite.dmg
16ed0353ed67d233a5614b86ab1474fbd0fd73de00b77eb3b82e5e4b4fe7e460  DB.Browser.for.SQLite.dmg
```

``` shell
cat example-upper.sql
BEGIN TRANSACTION;
CREATE TABLE names(
  id integer PRIMARY KEY,
  name text UNIQUE
);
COMMIT;
```

``` shell
cat example-lower.sql
begin transaction;
create table names(
  id integer primary key,
  name text unique
);
commit;
```

@MKleusberg Same results as before when following the same testing procedure with the nightly.

However, I found it interesting that even after deleting my preferences `plist` and `savedState`, some (or perhaps all?) of my preferences were preserved upon launching the nightly. I don't recall all of the changes I made from the defaults, but I know that I set a custom font and font size, and those variables were persisted. Is the app storing information in a nonstandard location for macOS? Should I be looking in other locations?

**Comment by justinclift** [comment]
Preferences are split over two files (legacy thing).  Running this should show them both:

```
$ ls -1 ~/Library/Preferences/*sqliteb*
/Users/jc/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
/Users/jc/Library/Preferences/net.sourceforge.sqlitebrowser.plist
```

Looking at their names, it's fairly ironic neither of those are `.org`.

If we change them now, then everyones saved preferences will stop working.  Thus leaving them alone. :wink:

**Comment by jsejcksn** [comment]
@justinclift You could update it to reflect the current namespace `org.sqlitebrowser.sqlitebrowser.plist` and direct all writes to that location, but still read from all three locations (in a cascade, I imagine). Then, on a future _major_ [semver](https://semver.org/), you can stop reading from the legacy locations.

**Comment by justinclift** [comment]
Yeah, that's a decent idea.  Probably super low priority though, compared to other stuff. :smile:

**Comment by MKleusberg** [comment]
@jsejcksn Sorry about that! There was a minor error in there - I somehow thought 'COMMIT' was five characters long instead of six. So the fix didn't work for that statement. Should be fixed now :wink: Are you ok to check again with the next nightly build?

**Comment by jsejcksn** [comment]
@MKleusberg Sure—just send me a link when it's ready.

**Comment by justinclift** [comment]
The nightly builds ran successfully (yay) and are online now: :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by jsejcksn** [comment]
env:

``` shell
rm -r /Applications/DB\ Browser\ for\ SQLite.app
rm ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
rm ~/Library/Preferences/net.sourceforge.sqlitebrowser.plist
# rm: ~/Library/Preferences/net.sourceforge.sqlitebrowser.plist: No such file or directory
rm -r ~/Library/Saved\ Application\ State/net.sourceforge.sqlitebrowser.savedState

shasum -a 256 DB.Browser.for.SQLite.dmg
# ae5fbfcfc7d4a10201ed23d90b62ba236386c46d5c6924215b4d55f4a6f0d541  DB.Browser.for.SQLite.dmg
```

@MKleusberg Repeated last test. Success.

🐛 -> 🦋

**Comment by MKleusberg** [comment]
Awesome! Thanks for reporting and testing this, @jsejcksn :+1:
