### ISSUE TITLE
Nuke the really old nightlies?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1766]
The nightlies server is getting a bit low on disk space (~10% left), so sometime over the next few weeks we should either add more storage to it, or remove some of the stuff on there.

Am kind of thinking that we probably don't need to keep the nightlies from before our 3.10.1 release.

The ones from then on are still useful, as they can be used to figure out when some new behaviour started.  But stuff from before that... not really seeing the point.

What does everyone else reckon?  If we just kill the older (pre 3.10.1) release stuff, that'll likely free up a lot of space and we don't have to think about this again for quite some time. :smile:

**Comment by karim** [comment]
> Am kind of thinking that we probably don't need to keep the nightlies from before our 3.10.1 release.

I agree. :+1:

**Comment by chrisjlocke** [comment]
Gets my vote.  Unfortunately my laptop with login details to get onto the nightlies server had to get wiped when I handed it back to work, so will have to set it up again at some point so I can help out with the 'tidying up' (used to put the files into monthly folders, etc).  

Agree that the nightlies before 3.10.1 can be wiped.

**Comment by Z4us** [comment]
Perhaps keep some versions supporting old OS's like OS X Snow Leopard only
1 per OS for people who never upgraded; we did finally a week or two ago -
to Mojave 😆

Kind regards | Vriendelijke groeten | Cordiali saluti,
Klaas `Z4us` van B V, EFIG
<https://nl.linkedin.com/in/klaas-van-buiten-0325b2102>

**Comment by mgrojo** [comment]
I agree too that they can be wiped. If we want to save some of them, as @Z4us proposes, maybe it's enough to look to the releases dates and when there are gaps, let's say of more than 6 months, save one batch of builds from the middle date.

**Comment by justinclift** [comment]
Thanks all, good ideas. :smile:

@Z4us Any idea which build definitely works with Snow Leopard, so it can be kept?

Haven't personally run that in years, so not sure. :smile:

> maybe it's enough to look to the releases dates and when there are gaps, let's say of more than 6 months, save one batch of builds from the middle date.

That's do-able too.  I'll get it done over the next few days, and we can see how much space it really frees up.  In theory... should be plenty. :smile:

**Comment by MKleusberg** [comment]
No objections from my side either :smile: I'd probably delete even more recent ones but any date after the 3.10.1 release seems to be just random. So sounds good :wink:

**Comment by justinclift** [comment]
Getting this done now.  The concept of "which old versions to keep, so people on old macOS versions have something to run?" was bothering me for a bit...

... then remembered our proper releases are still available regardless of what gets done on the nightly server, so people running older versions of macOS can just download an older release from there.

So, nuking everything up to the 3.10.1 release date after all. :smile:

**Comment by justinclift** [comment]
k, this is done.  It pretty much freed up 1/2 the used space, so we're probably good for a very long time. :smile:
