### ISSUE TITLE
'Execute Current Line' does not work as expected in Windows - executes current and next statements

### ISSUE THREAD

**Issue by kharaktur** [sqlitebrowser/sqlitebrowser#1768]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.1 [built for i386-little_endian-ilp32] on Windows 7 SP 1 (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.27.1
> and Qt 5.7.1

**Comment by kharaktur** [comment]
Execute SQL tab. When multiple statements are present executing the current line (with Ctrl+F5 or the icon) results in all statements running sequentially. All statements are on separate lines and terminated with ; Seems to only be a problem with this version built for windows.

**Comment by chrisjlocke** [comment]
I believe this has been reported before in the nightlies, but is still a bit broken.
As a workaround, you can **highlight** the SQL statement you want to run, and click the <kbd>F5</kbd> button.  Pressing <kbd>F5</kbd> only runs the **highlighted** SQL statements.  Its more effort, but should be easier than commenting out chunks of SQL statements.

Here is a screencast of my experiment.
https://screencast-o-matic.com/watch/cqnTbd06kM

So three statements.  Seems that clicking in a line executes the next one.  My first attempt was to just click play, and as expected, the last statement is the only one visible, so it ran all three statements.
Not sure why at 0:15, the result column for 'c' is smaller than the one at 0:12.  Running just one statement gives a smaller column.  Never mind..... *scratches head*
0:20 onwards just shows highlighting works as desired.

**Comment by kharaktur** [comment]
Selecting works for me, thanks.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 02/25/2019, 12:55 PM Chris Locke <notifications@github.com> wrote:
I believe this has been reported before in the nightlies, but is still a bit broken.
As a workaround, you can highlight the SQL statement you want to run, and click the F5 button.  Pressing F5 only runs the highlighted SQL statements.  Its more effort, but should be easier than commenting out chunks of SQL statements.
Here is a screencast of my experiment.
https://screencast-o-matic.com/watch/cqnTbd06kM
So three statements.  Seems that clicking in a line executes the next one.  My first attempt was to just click play, and as expected, the last statement is the only one visible, so it ran all three statements.
Not sure why at 0:15, the result column for 'c' is smaller than the one at 0:12.  Running just one statement gives a smaller column.  Never mind..... scratches head
0:20 onwards just shows highlighting works as desired.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sqlitebrowser/sqlitebrowser","title":"sqlitebrowser/sqlitebrowser","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sqlitebrowser/sqlitebrowser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chrisjlocke in #1768: I believe this has been reported before in the nightlies, but is still a bit broken.\r\nAs a workaround, you can **highlight** the SQL statement you want to run, and click the \u003ckbd\u003eF5\u003c/kbd\u003e button.  Pressing \u003ckbd\u003eF5\u003c/kbd\u003e only runs the **highlighted** SQL statements.  Its more effort, but should be easier than commenting out chunks of SQL statements.\r\n\r\nHere is a screencast of my experiment.\r\nhttps://screencast-o-matic.com/watch/cqnTbd06kM\r\n\r\nSo three statements.  Seems that clicking in a line executes the next one.  My first attempt was to just click play, and as expected, the last statement is the only one visible, so it ran all three statements.\r\nNot sure why at 0:15, the result column for 'c' is smaller than the one at 0:12.  Running just one statement gives a smaller column.  Never mind..... *scratches head*\r\n0:20 onwards just shows highlighting works as desired.  \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sqlitebrowser/sqlitebrowser/issues/1768#issuecomment-467111169"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1768#issuecomment-467111169",
"url": "https://github.com/sqlitebrowser/sqlitebrowser/issues/1768#issuecomment-467111169",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mgrojo** [comment]
@kharaktur I think I have fixed this issue. It took a lot of time because we weren't aware of it, since it only happens under Windows. Can you confirm it works well for you using [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/)?

**Comment by kharaktur** [comment]
Works correctly now, thanks.
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 01/04/2020, 1:49 PM Manuel <notifications@github.com> wrote:

  @kharaktur I think I have fixed this issue. It took a lot of time because we weren't aware of it, since it only happens under Windows. Can you confirm it works well for you using tomorrow's nightly build?

**Comment by mgrojo** [comment]
Great! Thanks for confirming.
