### ISSUE TITLE
How to edit record?

### ISSUE THREAD

**Issue by Ghost-Recon131** [sqlitebrowser/sqlitebrowser#1769]
I used to use the SQlite manager on Firefox (pre-quantum) and I can just double click on a cell to edit record. Something that looks like the image below. Anyone know how to do this? 
![image](https://user-images.githubusercontent.com/40227626/53405300-a7749f00-3a0b-11e9-9b12-68571f0ada9b.png)

**Comment by justinclift** [comment]
You should be able to click in any cell then edit it directly.

If that doesn't work, then double clicking on a cell should open up a window thing for you to view the data (there are various modes, including text, hexedit, etc), and let you change them.

Guessing you have already tried that, and it's not working?

If that's the case... which version are you using, and on which OS?  It'll probably need looking into. :smile:

**Comment by Ghost-Recon131** [comment]
Thanks for that, was used to the old design lol :)

**Comment by justinclift** [comment]
No worries at all. :smile:
