### ISSUE TITLE
Export CSV problem

### ISSUE THREAD

**Issue by myersjj** [sqlitebrowser/sqlitebrowser#177]
When I try to export as CSV the output from a query with delimiter set to ',' (comma), it does not quote fields that contain commas.

**Comment by justinclift** [comment]
Yeah, it's a known bug in the current release.  It's fixed in the latest nightly builds (and our source code too), if that helps.

If you're on OSX or Windows, would you be ok to try the latest nightly build and try that out? (download locations are on the front page of this repo)

**Comment by myersjj** [comment]
Yes, the latest nightly build fixed this issue.
