### ISSUE TITLE
Distribution with Chocolatey

### ISSUE THREAD

**Issue by KuraiAndras** [sqlitebrowser/sqlitebrowser#1776]
Describe the new feature
Distribute sqlitebrowser through chocolatey.

Additional info
Sqlitebrowser already is on chocolatey, but the maintainers don't seem to keep it updated. (Current version there is 3.10.1 [https://chocolatey.org/packages/sqlitebrowser])

**Comment by justinclift** [comment]
Thanks @KuraiAndras, it's a good idea. :smile:

So far with the 3.11.x series we're going through a few point releases (3.11.0, 3.11.1, 3.11.2 soon) to shake out bugs.  When 3.11.2 is released (probably in a few days), it'll probably be fairly stable + suitable for things like Chocolatey, PortableApps (which we're already in too), and so on.

It's probably best to wait for the few days until 3.11.2 is released, then ping the maintainers of the package there to let them know:

* https://chocolatey.org/profiles/pallitax
* https://chocolatey.org/profiles/dtgm

If they've both lost interest in doing Chocolately packaging stuff, would you be up for getting it updated there? :smile:

**Comment by karim** [comment]
Hello Kurai, and thanks for bringing this to our attention. :smiley: 

By visiting the page you linked it seems there is some kind of an approval process before a package is added. This process gets repeated again for each version.

3.11.1 was recently released and maybe that explains the delay in updating it on Chocolatey. Maybe it is waiting for approval. @dtgm seems to be the one maintaining it, so I think he can give us more details about the process.

I'm not sure but maybe you opened this issue so that we can takeover, and do an *official* release instead.

I'm not familiar with Chocolatey so I don't know where to start, but we are always open for PRs. :smiley:

**Comment by karim** [comment]
+1 to Justin for speed. You beat me to it. :smile:

**Comment by KuraiAndras** [comment]
Wow, thanks for the fast response!

I have not yet published any package on chocolatey, but from what I have seen it does not seem too complicated. Me personally would not like to maintain it, mostly because I only occasionally use sqlbrowser.

However, I think it would be beneficial to have the official creators maintain the chocolatey package, to keep it as up to date as possible. If you think so you could close this issue, and thanks again for the heads up and the fast answers!

**Comment by justinclift** [comment]
No worries.  Just added a note to the end of our [Release Process checklist](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Release-process#notify-people), so it (mostly likely) gets done as part of the 3.11.2 release in a few days. :smile:

**Comment by chrisjlocke** [comment]
Just looked at the release process checklist, and there wasn't a mention of updating the release version on the website - the location where DB4S looks to check for an updated version?  That usually gets updated a few days after the release when 'the dust has settled'...

**Comment by justinclift** [comment]
Thanks @chrisjlocke, that's a good point.  There was an outdated mention of it in the "Notify people" section, so just [updated that](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Release-process#notify-people) to include it's new home on our download cluster as well. :smile:

**Comment by justinclift** [comment]
I've just used the contact form for our package on the Chocolatey website, letting them know there's a new release.  Hopefully that leads to a good result. :smile:
