### ISSUE TITLE
Trying to save after successful import fails

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1777]
OS - Windows 10 x64
DB build latest nightly 2nd March

I have a reasonably sized sql file with a bunch of delete tables, create tables and insert data etc.

I  successfully import the file (could be a new database or an existing database).

When I click on Write Changes (to save the database) I get the attached dialog.

![multi png](https://user-images.githubusercontent.com/6769116/53677420-67f4bf80-3c64-11e9-8cae-4ee12511696d.jpg)

The release build does not have this issue.

**Comment by justinclift** [comment]
Thanks @mtissington.  Guessing here, but it's probably a bug introduced with 0f6946c19dacb4900336bc3d043f70a3608501f7.

Any interesting in trying a build from the day prior?

If so, I *think* this should be the right one. :smile:

* https://nightlies.sqlitebrowser.org/win64/2019-02/DB.Browser.for.SQLite-2019-02-25-win64.msi
* https://nightlies.sqlitebrowser.org/win64/2019-02/DB.Browser.for.SQLite-2019-02-25-win64.zip

**Comment by mtissington** [comment]
confirmed 02-25 works correctly

**Comment by justinclift** [comment]
Cool. :smile:

The bug should be present in this one too then, if you're ok to check and confirm:

* https://nightlies.sqlitebrowser.org/win64/2019-02/DB.Browser.for.SQLite-2019-02-27-win64.msi
* https://nightlies.sqlitebrowser.org/win64/2019-02/DB.Browser.for.SQLite-2019-02-27-win64.zip

If it is, that pretty much guarantees 0f6946c19dacb4900336bc3d043f70a3608501f7 is the problem. :smile:

**Comment by mtissington** [comment]
Confirmed - that was the build I had installed prior to needing to install the release build.

**Comment by mtissington** [comment]
FYI - the import file I'm using has both a BEGIN TRANS and a COMMIT.

**Comment by justinclift** [comment]
`TRANS` or `TRANSACTION`?

**Comment by mtissington** [comment]
My mistake - BEGIN TRANSACTION;

**Comment by justinclift** [comment]
Cool. :smile:

That commit is @MKleusberg's, so he'll probably get the fixing started (etc) sometime over the next few days. :smile:

**Comment by MKleusberg** [comment]
Thanks, @mtissington, for the as always helpful report! :smile: The fix for this was trickier than expected because there were multiple problems involved which all yield the same problem. But I hope I could catch them all. Can you check again with tomorrow's nightly build if it works for your file as well?

**Comment by justinclift** [comment]
Not sure if it'll help, but I've just kicked off the Win64 nightly build script manually.  A rebuilt nightly for today (with the new commit included) should be online in ~40 mins. :smile:

**Comment by justinclift** [comment]
On that note, we'd probably find decent use in having automatic builds for Windows and macOS too, like we now have for Linux.

* With the mass firings of Travis CI staff by their new owner, it's sounding unlikely they have a strong future.
* People say good things about CircleCI, but it doesn't yet support [Windows](https://circleci.com/docs/2.0/faq/#what-operating-systems-does-circleci-20-support). So we might need to look for other options too.
  *  https://support.circleci.com/hc/en-us/articles/115015871087-Windows-and-NET-Support

**Comment by mtissington** [comment]
Sorry guys, I've just downloaded the latest nightly 3rd March, installed it and I get the same error dialog..
(check the file version/date to confirm I was running the correct version)

**Comment by mtissington** [comment]
@MKleusberg happy to send you the sql file privately if needed.

**Comment by MKleusberg** [comment]
@mtissington Yes, that would definitely help :smile: It works for my test cases and I'm not sure what's different in your file. You can send the file to mkleusberg@gmail.com.

**Comment by mtissington** [comment]
@MKleusberg  email sent

**Comment by MKleusberg** [comment]
Sorry for the late reply! I actually tried using your file and it just worked fine for me but then I didn't have enough time to investigate further.

But now seeing that issue #1814 isn't working either I start to believe that this issue here might have the same build problem. So if there is a build problem in #1814, it's worth checking this issue again after the build problem is solved.

**Comment by justinclift** [comment]
@mtissington Would you have time to check if this is fixed?

**Comment by mtissington** [comment]
I tested it the other day and it’s working Michael

**Comment by justinclift** [comment]
Fantastic.  Thanks heaps @mtissington. :smile:
