### ISSUE TITLE
Shortcuts screen problem when installing 

### ISSUE THREAD

**Issue by icecoldbier** [sqlitebrowser/sqlitebrowser#1778]
Details for the issue
--------------------

#### What did you see instead? You can only read the word "Desktop" in the list of choices.
![shortcuts](https://user-images.githubusercontent.com/48147815/53678784-bec4be00-3c91-11e9-8448-5d4f625c92d6.jpg)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: (10_version:1809 build 17763.316_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ x] 3.11.1
- [ ] 3.11.0
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
Hello @icecoldbier, and thanks for reporting this.

This was reported before in #1713 and I believe we fixed it in our nightly version.

Would you be able to try the nightly to check if it was fixed for you?

- https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Thanks @icecoldbier, that's good info. :smile:

Now to figure out where the problem starts from, so we can fix it.  As first thought, is the display you're using a HiDPI one?

Next thought - just in case - have you seen this kind of problem with other applications before too?  If so, and they've already fixed it (and they're Open Source), we might be able to just copy whatever fix they did. :smile:

**Comment by karim** [comment]
Looking again at the screenshot, it seems like the fix was for the shortcut items only.

The text in the dialog are also truncated, and I'm not sure how to fix this without actually removing some text from the dialog. The problem seems to be "too much text in a very little space".

**Comment by justinclift** [comment]
Maybe something like a wrong font is being loaded, or the font is being passed an incorrect size to render?

@icecoldbier Are any of the displays on your computer HiDPI ones?

**Comment by icecoldbier** [comment]
I used the latest nightly build and it worked fine.  Thank you.  

The resolution on my laptop is 3840 x 2160.

**Comment by justinclift** [comment]
Excellent, thanks for checking and letting us know @icecoldbier. :smile:
