### ISSUE TITLE
Please create an AppData file for sqlitebrowser

### ISSUE THREAD

**Issue by hughsie** [sqlitebrowser/sqlitebrowser#178]
Please consider writing and installing an AppData file with the application description and some screenshots, else sqlitebrowser looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by glawrence** [comment]
I believe you can do this yourself via a pull request, so why not do it yourself, you seem to know what is required?

Rather than use developer time on this, I reckon someone else could help with this, if you. I would be happy to give it a go if there are no other volunteers and it is agreed this is a good thing.

**Comment by hughsie** [comment]
Right, I could indeed do a pull request. There are three main reason I've asked upstream maintainers to do this rather than just submit something myself:

* You probably know the application inside out, e.g. how to take screenshots to fully show off all the features that would take many weeks of me using to find out.
* You can update the description and screenshots yourself when you add new features or port the UI to a new toolkit.
* Time; so far 473 upstream projects[1] have written AppData files, and I simple can't scale myself to do all that.

Also, according to https://alt.fedoraproject.org/pub/alt/screenshots/f22/matrix.html sqlitebrowser doesn't have any keywords in the .desktop file, which means that searching for it in the software center is going to be harder.

[1] https://alt.fedoraproject.org/pub/alt/screenshots/f22/status.html -- warning, BIG HTML page

**Comment by justinclift** [comment]
This isn't something I'm personally interested in doing (not a fan of Gnome, and I don't use KDE).  However if someone does a pull request with the right bits, we'll happily merge it. :grinning:

**Comment by justinclift** [comment]
@glawrence Any interest in picking this up?  If you're willing to, we might as well get it done... :wink:

**Comment by glawrence** [comment]
Yes, ok, I will give this a go. Do you have a target for the next release?

**Comment by justinclift** [comment]
Yep, April 18th. :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/milestones

**Comment by glawrence** [comment]
I have created a pull request, please see my comments in the request as I believe it needs to be checked.

@hughsie could you take a quick look too please?

**Comment by justinclift** [comment]
Awesome stuff @glawrence. :smile:
