### ISSUE TITLE
Some expressions syntax (two contiguous parentheses) "breaks" parser

### ISSUE THREAD

**Issue by iglesiasp** [sqlitebrowser/sqlitebrowser#1781]
### Details for the issue

Hi. When creating a table via a script, if any expression comes between two parentheses (i.e a constraint condition), the parser does not recognize the script and thus you won't see the table definition on the Db Structure tab

### Useful extra information

Create a table with the following constraint:

CONSTRAINT  TABLE_NAME_CK01 CHECK  ((boolean_expression))

It *will* create the table with no syntax errors BUT you won't be able to see the table definition on the Database Structure tab (plus, the 'Modify Table' context option will show a parser warning and the CREATE sentence will be EMPTY).

Create the same table again but enclose the CONSTRAINT expression with just one parentheses, it will all work normal.

This IS a problem with Constraints that MUST be written this way

CONSTRAINT  TABLE_NAME_CK01 CHECK  ((COND1 AND COND2) OR (COND3 AND COND4))

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.11.1
- [ ] 3.11.0
- [x] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @iglesiasp, sounds like a good bug catch. :smile:

**Comment by MKleusberg** [comment]
@iglesiasp We have just finished rewriting our parser to make it work much better with expressions like yours. The old one had a lot of problems with expressions with many parentheses. Are you interested in giving the next nightly build (available [here](https://nightlies.sqlitebrowser.org/latest/) in about 24 hours) a try and see if it fixes your problem? :smile:

**Comment by iglesiasp** [comment]
OMG... I completely forgot this one... Sorry for the delay! :(
Installed latest nightly (2019-10-10) and tried to reply the issue. All went OK. Great job, thanks!
