### ISSUE TITLE
sqlitebrowser doesn't start on Centos 7 with Kernel 4.9.75-204.el7.centos.i686

### ISSUE THREAD

**Issue by alexpowderpuff** [sqlitebrowser/sqlitebrowser#1787]
Details for the issue
--------------------
Hello,

yum install ant-antlr antlr-C++ cmake gcc-c++ git qt-devel qt5-linguist sqlite-devel
sudo yum install qt5-qtbase
sudo yum install qt5-qtbase-devel
git clone https://github.com/sqlitebrowser/sqlitebrowser
cd sqlitebrowser
cmake -Wno-dev .
make
sudo make install

without errors

Error:
when clicking DB Browser for SQLite nothing happens
when starting in terminal I get Segmentation fault core dumped

#### What did you expect to see?
I expected sqlitebrowser to open

#### What did you see instead?
The application doesn't start

Useful extra information
-------------------------

Please find enclosed a strace log:

[strace.log](https://github.com/sqlitebrowser/sqlitebrowser/files/2932768/strace.log)

[ ~]$ which sqlitebrowser
/usr/local/bin/sqlitebrowser

[ ~]$ ldd `which sqlitebrowser`
	linux-gate.so.1 =>  (0xb7745000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xb7701000)
	libQt5Gui.so.5 => /lib/libQt5Gui.so.5 (0xb723c000)
	libQt5Test.so.5 => /lib/libQt5Test.so.5 (0xb7200000)
	libQt5PrintSupport.so.5 => /lib/libQt5PrintSupport.so.5 (0xb7196000)
	libQt5Widgets.so.5 => /lib/libQt5Widgets.so.5 (0xb6b46000)
	libQt5Network.so.5 => /lib/libQt5Network.so.5 (0xb69bd000)
	libQt5Concurrent.so.5 => /lib/libQt5Concurrent.so.5 (0xb69b6000)
	libQt5Xml.so.5 => /lib/libQt5Xml.so.5 (0xb697a000)
	libsqlite3.so.0 => /lib/libsqlite3.so.0 (0xb68c2000)
	libQt5Core.so.5 => /lib/libQt5Core.so.5 (0xb642c000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0xb633f000)
	libm.so.6 => /lib/libm.so.6 (0xb62fd000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb62e2000)
	libc.so.6 => /lib/libc.so.6 (0xb6117000)
	/lib/ld-linux.so.2 (0xb7747000)
	libGL.so.1 => /lib/libGL.so.1 (0xb60b7000)
	libpng15.so.15 => /lib/libpng15.so.15 (0xb608a000)
	libharfbuzz.so.0 => /lib/libharfbuzz.so.0 (0xb5fe8000)
	libz.so.1 => /lib/libz.so.1 (0xb5fd1000)
	libssl.so.10 => /lib/libssl.so.10 (0xb5f68000)
	libcrypto.so.10 => /lib/libcrypto.so.10 (0xb5d7e000)
	libdl.so.2 => /lib/libdl.so.2 (0xb5d79000)
	libsystemd.so.0 => /lib/libsystemd.so.0 (0xb5d41000)
	libicui18n.so.50 => /lib/libicui18n.so.50 (0xb5b3b000)
	libicuuc.so.50 => /lib/libicuuc.so.50 (0xb59ca000)
	libicudata.so.50 => /lib/libicudata.so.50 (0xb45f7000)
	libpcre2-16.so.0 => /lib/libpcre2-16.so.0 (0xb4587000)
	libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xb4583000)
	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xb4469000)
	libGLX.so.0 => /lib/libGLX.so.0 (0xb4447000)
	libX11.so.6 => /lib/libX11.so.6 (0xb430b000)
	libXext.so.6 => /lib/libXext.so.6 (0xb42f8000)
	libGLdispatch.so.0 => /lib/libGLdispatch.so.0 (0xb429a000)
	libfreetype.so.6 => /lib/libfreetype.so.6 (0xb41e1000)
	libgraphite2.so.3 => /lib/libgraphite2.so.3 (0xb41b3000)
	libgssapi_krb5.so.2 => /lib/libgssapi_krb5.so.2 (0xb4168000)
	libkrb5.so.3 => /lib/libkrb5.so.3 (0xb4091000)
	libcom_err.so.2 => /lib/libcom_err.so.2 (0xb408c000)
	libk5crypto.so.3 => /lib/libk5crypto.so.3 (0xb4056000)
	libresolv.so.2 => /lib/libresolv.so.2 (0xb403d000)
	libcap.so.2 => /lib/libcap.so.2 (0xb4037000)
	librt.so.1 => /lib/librt.so.1 (0xb402e000)
	libselinux.so.1 => /lib/libselinux.so.1 (0xb4007000)
	liblzma.so.5 => /lib/liblzma.so.5 (0xb3fdc000)
	liblz4.so.1 => /lib/liblz4.so.1 (0xb3fc6000)
	libgcrypt.so.11 => /lib/libgcrypt.so.11 (0xb3f3e000)
	libgpg-error.so.0 => /lib/libgpg-error.so.0 (0xb3f39000)
	libdw.so.1 => /lib/libdw.so.1 (0xb3ee0000)
	libpcre.so.1 => /lib/libpcre.so.1 (0xb3e7a000)
	libxcb.so.1 => /lib/libxcb.so.1 (0xb3e4f000)
	libbz2.so.1 => /lib/libbz2.so.1 (0xb3e3c000)
	libkrb5support.so.0 => /lib/libkrb5support.so.0 (0xb3e2c000)
	libkeyutils.so.1 => /lib/libkeyutils.so.1 (0xb3e27000)
	libattr.so.1 => /lib/libattr.so.1 (0xb3e20000)
	libelf.so.1 => /lib/libelf.so.1 (0xb3e05000)
	libXau.so.6 => /lib/libXau.so.6 (0xb3e01000)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X ] Linux: ( _distro: Centos 7:; )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.1
- [ ] 3.11.0
- [ ] 3.10.1
- [ X] Other: 3.11.99

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Could you recompile without the `-Wno-dev` option for cmake and run the application inside the debugger? When it receives the segmentation fault, the `where` command will output a  backtrace that will probably help a lot.

**Comment by justinclift** [comment]
@alexpowderpuff Interesting.  Where's the 4.9.x kernel from?

Asking because I use CentOS 7 x64 on my desktop, and the newest kernel from the standard sources (that I know of :wink:) is 3.10.0-957.5.1. :smile:

Guessing the newer kernel is a way to get newer device drivers?

**Comment by justinclift** [comment]
Sorry, wrong button press. :roll_eyes:

**Comment by justinclift** [comment]
Thinking about it:

> when starting in terminal I get Segmentation fault core dumped

That'll probably be useful.  It's fairly easy to tell CentOS to create core files (done recently myself too :wink:), which gdb can then run a backtract on.  That'll show fairly exactly there the crash happened in the code. :smile:

**Comment by alexpowderpuff** [comment]
> @alexpowderpuff Interesting. Where's the 4.9.x kernel from?
> 
> Asking because I use CentOS 7 x64 on my desktop, and the newest kernel from the standard sources (that I know of 😉) is 3.10.0-957.5.1. 😄
> 
> Guessing the newer kernel is a way to get newer device drivers?

Hello,

http://buildlogs-seed.centos.org/c7.1708.exp.i386/kernel/20180105174048/4.9.75-204.el7.centos.i386/

I have to develop for production hosts that use this kernel

**Comment by alexpowderpuff** [comment]
> Could you recompile without the `-Wno-dev` option for cmake and run the application inside the debugger? When it receives the segmentation fault, the `where` command will output a backtrace that will probably help a lot.

I recompiled without -Wno-dev but 

`gdb sqlitebrowser`

shows

```
This GDB was configured as "i686-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/sqlitebrowser...(no debugging symbols found)...done.
```

**Comment by alexpowderpuff** [comment]
After google search might this help?
`cmake -DCMAKE_BUILD_TYPE=Debug`

**Comment by alexpowderpuff** [comment]
> Could you recompile without the `-Wno-dev` option for cmake and run the application inside the debugger? When it receives the segmentation fault, the `where` command will output a backtrace that will probably help a lot.

Hello I recompiled with 

`cmake -DCMAKE_BUILD_TYPE=Debug .`

gdb shows:

```
(gdb) run
Starting program: /usr/local/bin/sqlitebrowser 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xb4152b40 (LWP 30604)]
[New Thread 0xb27d6b40 (LWP 30605)]
[New Thread 0xb1dffb40 (LWP 30606)]
[New Thread 0xb15feb40 (LWP 30607)]
[New Thread 0xb0c34b40 (LWP 30608)]
[New Thread 0xb03bbb40 (LWP 30609)]
[New Thread 0xafbbab40 (LWP 30610)]
[New Thread 0xaf1bdb40 (LWP 30611)]
[Thread 0xaf1bdb40 (LWP 30611) exited]

Program received signal SIGSEGV, Segmentation fault.
0xb46eed1d in xcb_send_request_with_fds64 () from /lib/libxcb.so.1
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-8.el7.i686 PackageKit-gtk3-module-1.1.10-1.el7.centos.i686 adwaita-qt5-1.0-1.el7.i686 at-spi2-atk-2.26.2-1.el7.i686 at-spi2-core-2.28.0-1.el7.i686 atk-2.28.1-1.el7.i686 bzip2-libs-1.0.6-13.el7.i686 cairo-1.15.12-3.el7.i686 cairo-gobject-1.15.12-3.el7.i686 dbus-glib-0.100-7.el7.i686 dbus-libs-1.10.24-12.el7.i686 dconf-0.28.0-4.el7.i686 elfutils-libelf-0.172-2.el7.i686 elfutils-libs-0.172-2.el7.i686 expat-2.1.0-10.el7_3.i686 fontconfig-2.13.0-4.3.el7.i686 freetype-2.8-12.el7_6.1.i686 fribidi-1.0.2-1.el7.i686 gdk-pixbuf2-2.36.12-3.el7.i686 glib2-2.56.1-2.el7.i686 glibc-2.17-260.el7_6.3.i686 graphite2-1.3.10-1.el7_3.i686 gtk3-3.22.30-3.el7.i686 gvfs-client-1.36.2-1.el7.i686 harfbuzz-1.7.5-2.el7.i686 keyutils-libs-1.5.8-3.el7.i686 krb5-libs-1.15.1-37.el7_6.i686 libICE-1.0.9-9.el7.i686 libSM-1.2.2-2.el7.i686 libX11-1.6.5-2.el7.i686 libXau-1.0.8-2.1.el7.i686 libXcomposite-0.4.4-4.1.el7.i686 libXcursor-1.1.15-1.el7.i686 libXdamage-1.1.4-4.1.el7.i686 libXext-1.3.3-3.el7.i686 libXfixes-5.0.3-1.el7.i686 libXi-1.7.9-1.el7.i686 libXinerama-1.1.3-2.1.el7.i686 libXrandr-1.5.1-2.el7.i686 libXrender-0.9.10-1.el7.i686 libXxf86vm-1.1.4-1.el7.i686 libattr-2.4.46-13.el7.i686 libblkid-2.23.2-59.el7.i686 libcanberra-0.30-5.el7.i686 libcanberra-gtk3-0.30-5.el7.i686 libcap-2.22-9.el7.i686 libcom_err-1.42.9-13.el7.i686 libdrm-2.4.91-3.el7.i686 libepoxy-1.5.2-1.el7.i686 libffi-3.0.13-18.el7.i686 libgcc-4.8.5-36.el7.i686 libgcrypt-1.5.3-14.el7.i686 libglvnd-1.0.1-0.8.git5baa1e5.el7.i686 libglvnd-egl-1.0.1-0.8.git5baa1e5.el7.i686 libglvnd-glx-1.0.1-0.8.git5baa1e5.el7.i686 libgpg-error-1.12-3.el7.i686 libicu-50.1.2-17.el7.i686 libjpeg-turbo-1.2.90-6.el7.i686 libmount-2.23.2-59.el7.i686 libogg-1.3.0-7.el7.i686 libpng-1.5.13-7.el7_2.i686 libselinux-2.5-14.1.el7.i686 libstdc++-4.8.5-36.el7.i686 libtdb-1.3.15-1.el7.i686 libthai-0.1.14-9.el7.i686 libtool-ltdl-2.4.2-22.el7_3.i686 libuuid-2.23.2-59.el7.i686 libvorbis-1.3.3-8.el7.1.i686 libwayland-client-1.15.0-1.el7.i686 libwayland-cursor-1.15.0-1.el7.i686 libwayland-egl-1.15.0-1.el7.i686 libxcb-1.13-1.el7.i686 libxkbcommon-0.7.1-1.el7.i686 libxshmfence-1.2-1.el7.i686 llvm-private-6.0.1-2.el7.i686 lz4-1.7.5-2.el7.i686 mesa-dri-drivers-18.0.5-4.el7_6.i686 mesa-libGL-18.0.5-4.el7_6.i686 mesa-libglapi-18.0.5-4.el7_6.i686 nss-softokn-freebl-3.36.0-5.el7_5.i686 openssl-libs-1.0.2k-16.el7.i686 pango-1.42.4-1.el7.i686 pcre-8.32-17.el7.i686 pcre2-utf16-10.23-2.el7.i686 pixman-0.34.0-1.el7.i686 qgnomeplatform-0.3-3.el7.i686 qt5-qtbase-5.9.2-3.el7.i686 qt5-qtbase-gui-5.9.2-3.el7.i686 sqlite-3.7.17-8.el7.i686 systemd-libs-219-62.el7_6.5.i686 xcb-util-0.4.0-2.el7.i686 xcb-util-image-0.4.0-2.el7.i686 xcb-util-keysyms-0.4.0-1.el7.i686 xcb-util-renderutil-0.3.9-3.el7.i686 xcb-util-wm-0.4.1-5.el7.i686 xz-libs-5.2.2-1.el7.i686 zlib-1.2.7-18.el7.i686
(gdb) 
```

**Comment by justinclift** [comment]
Yep, that's the right thing. :smile:

In the 2nd last line of the gdb output there, it gives a (very long) command to run `debuginfo-install GConf2-3.2.6-8.el7.i686 ...` (as root or through sudo) for installing a bunch of debugging info.  Please run that command to install the debug symbols, then run gdb again.

Note - When I ran the `debuginfo-install ...` command a few weeks ago locally for installing the debug symbols here, it was a fairly lengthy operation.  From (rough) memory... maybe downloading 1/2GB of stuff.  It needed to grab debug symbols for X windows, gcc, zlib, sqlite, and a metric tonne of random other things.  So... don't be put off by it.  It's all needed. :wink:

When gdb then runs, at the `(gdb)` prompt type `bt`, which should spit out a fairly long listing of info, pointing out exactly where the crash happened.  Cut-n-paste that here. :smile:

**Comment by alexpowderpuff** [comment]
Hello,
This is all the information I can provide you with. I can either install mesa-debuginfo or wayland-debuginfo. Apparently I cannot install both. Do you know why?

Below the output:

Reading symbols from /usr/local/bin/sqlitebrowser...done.
(gdb) run
Starting program: /usr/local/bin/sqlitebrowser 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xb4157b40 (LWP 8515)]
[New Thread 0xb27e3b40 (LWP 8516)]
[New Thread 0xb1dffb40 (LWP 8517)]
[New Thread 0xb15feb40 (LWP 8518)]
[New Thread 0xb0c6eb40 (LWP 8519)]
[New Thread 0xb03f5b40 (LWP 8520)]
[New Thread 0xafbf4b40 (LWP 8521)]
[New Thread 0xaf1feb40 (LWP 8522)]
[Thread 0xaf1feb40 (LWP 8522) exited]

Program received signal SIGSEGV, Segmentation fault.
xcb_send_request_with_fds64 (c=c@entry=0x0, flags=flags@entry=0, vector=vector@entry=0xbfffe76c, req=req@entry=0xb470925c <xcb_req.10065>, 
    num_fds=num_fds@entry=0, fds=fds@entry=0x0) at xcb_out.c:229
229	    if(c->has_error) {
Missing separate debuginfos, use: debuginfo-install mesa-dri-drivers-18.0.5-4.el7_6.i686 mesa-libGL-18.0.5-4.el7_6.i686 mesa-libglapi-18.0.5-4.el7_6.i686

**Comment by justinclift** [comment]
> I can either install mesa-debuginfo or wayland-debuginfo. Apparently I cannot install both. Do you know why?

No idea at all. :wink:

Hadn't come across those c7-exp kernels before, so asked the CentOS team (via IRC).

Seems like they're (very) experimental kernels, not really for production use.  Mostly for IoT hardware development, so people can develop against some new-ish IoT hardware (with CentOS).

If that's the case... I'm kind of suspecting you'd be better off to use DB4S (our abbreviation for sqlitebrowser) on your local desktop, and have the SQLite database be mounted from the IoT device you're using via NFS, sshfs, etc.

Not sure how feasible that is for you?

Next thought... since the crash info mentions `xcb_send_request_with_fds64`, it's seeming like some XWindow bug behaviour.  Maybe try compiling with a different version of Qt?

**Comment by justinclift** [comment]
Oh, as a next thought... when it crashes for you under gdb, does it give you a prompt you can type command into?  If so, then `bt` (for "backtrace") should help.  In theory, that should show exactly which function it crashed in, including the line it crashed on, and useful related information. :smile:

**Comment by alexpowderpuff** [comment]
Hello,

I just wanted to let you know that I successfully installed sqlitebrowser, changing nothing on my side  expect making a fresh clone today, follwing the tutorial for CENTOS7:
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md

**Comment by justinclift** [comment]
Thanks @alexpowderpuff That's good news. :smile:

Hopefully it works decently well, without further crashing or similar.
