### ISSUE TITLE
JSON export not exporting all rows

### ISSUE THREAD

**Issue by greggman** [sqlitebrowser/sqlitebrowser#1789]
Details for the issue
--------------------

#### What did you do?

* downloaded 3.11.1 for MacOS
* loaded up [this database](https://gadm.org/download_world.html) (link to [file](https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip)).
* Selected table "level1"
* picked "File->Export->Table to JSON"

#### What did you expect to see?

All 3610 rows exported

#### What did you see instead?

Only 343 rows exported

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:10.14.3)
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.1
- [ ] 3.11.0
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Uh oh.  That sounds like a pretty serious bug. :frowning: 

Thanks for letting us know @greggman. :smile:

**Comment by MKleusberg** [comment]
@greggman There is no table ``level1``` in the file you have linked to. Is it the correct file?

I have just tried this with a random table from this file and the number of exported records was correct. So this seems to be something which depends on the table layout or data.

**Comment by greggman** [comment]
Doh! Here's the correct link

https://data.biogeo.ucdavis.edu/data/gadm3.6/gadm36_levels_gpkg.zip

**Comment by greggman** [comment]
Ok, well I used python to convert to json. That table ended up being 808meg where as when I export from DB4S it's only ~58meg.  Maybe  it's just running out of memory? Though would be nice to get an error and the json file was still valid, just missing rows, so I guess that means the issue must be something else.

**Comment by MKleusberg** [comment]
Thanks, @greggman! The problem seems to be with Qt's JSON code. Too large JSON objects are not added to JSON arrays and the rather large ```geom``` values in the ```level1``` table create large enough JSON objects. I haven't dug through the Qt source code but [this](https://git.merproject.org/mer-core/qtbase/commit/03f1a69e9cffe919597373471f7609521a465470) might be the commit, and [this](https://github.com/RSATom/Qt/blob/master/qtbase/src/corelib/json/qjson_p.h#L755) could be the current code which causes this.

I think I will replace the Qt JSON parts with another library later in order to fix this. Glad to hear you could convert the files with Python in the meantime :smile:

**Comment by justinclift** [comment]
Wonder if there are streamling libraries available for it?  eg reasonable fixed memory size requirements, so larger sized inputs don't mean larger sized memory needed.  As a rough concept anyway. :smile:

**Comment by MKleusberg** [comment]
I have decided to use @nlohmann's JSON library for now. It doesn't stream the data as @justinclift suggested but has a fairly good API, excellent documentation, and is MIT licensed :smile: In my tests I could export the ```level1``` table without any problems and there is no difference between before and after this commit for smaller files.

@greggman Do you have the time to check tomorrow's nightly build and see if it is working for you as well? :smile:

**Comment by justinclift** [comment]
The slideshow gif on the front page of the repo mentions support for visual studio 2015.  Hopefully it also works with visual studio 2013, otherwise our 32-bit builds are going to fail.

Guess we might need to investigate the 2015 version of MSVC after all.

Or look for non-MSVC ways to build stuff. :smile:

**Comment by greggman** [comment]
downloaded the MacOS nightly. It worked great!

**Comment by justinclift** [comment]
Looks like the Win32 build failed though, as semi-expected.  I'm re-running the build script for that manually now, just in case it was something else.

If the problem does turn out to be MSVC 2013, I'll have a go at getting MSVC 2015 into a dev VM to see what our options are. :smile:

**Comment by justinclift** [comment]
Yep, it fails with:

```
6>  ExportDataDialog.cpp
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(290): error C2143: syntax error : missing ';' before 'size_t'
6>          C:\git_repos\sqlitebrowser\libs\json\json.hpp(294) : see reference to class template instantiation 'nlohmann::detail::index_sequence<Ints...>' being compiled
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(290): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(291): error C3646: 'noexcept' : unknown override specifier
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(322): error C2146: syntax error : missing ';' before identifier 'T'
6>          C:\git_repos\sqlitebrowser\libs\json\json.hpp(323) : see reference to class template instantiation 'nlohmann::detail::static_const<T>' being compiled
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(322): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(326): error C2146: syntax error : missing ';' before identifier 'T'
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(326): error C2065: 'T' : undeclared identifier
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(326): error C2923: 'nlohmann::detail::static_const' : 'T' is not a valid  template type argument for parameter 'T'
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(326): error C2143: syntax error : missing ';' before 'nlohmann::detail::static_const<T>::value'
6>C:\git_repos\sqlitebrowser\libs\json\json.hpp(326): fatal error C1903: unable to recover from previous error(s); stopping compilation
```

I'll see if I can get MSVC 2015 working.

**Comment by justinclift** [comment]
Qt 5.7 seems to have MSVC 2015 support, which looks positive:

![DB4S-issue_1789-screenshot1](https://user-images.githubusercontent.com/406299/54070192-23df6b80-42b1-11e9-903a-0d3bb0825be5.png)

Downloading MSVC 2015 now.  It's going to take a few hours.

**Comment by justinclift** [comment]
Building our 32-bit binaries with MSVC 2015 instead of MSVC 2013 seems to work without issues, at least on my development workstation.

I'll update our nightly build server (after taking a snapshot of the disk) with MSVC 2015 over the next few hours, so tomorrows nightly builds use it. :smile:

**Comment by justinclift** [comment]
Our Win32 nightly builds now use MSVC2015 instead of MSVC2013, so this new JSON library should work fine. :smile:

**Comment by nlohmann** [comment]
Cool to hear that the JSON library works for you. Please let me know if you need any support!

**Comment by MKleusberg** [comment]
Thanks and good work with the library, @nlohmann :+1: We will let you know if we need any advice :smile:
