### ISSUE TITLE
Database Structure view: wrong parsing of CHECK constraints

### ISSUE THREAD

**Issue by thesoftwarebin** [sqlitebrowser/sqlitebrowser#179]
Hi! 

I'm running DB Browser for Sqlite 3.4.0 on Windows 7.

* run test1:
<pre>
CREATE TABLE "a" (
	`b`	TEXT CHECK(`b`='A')
);
</pre>
and visit the Database Structure view: 1 table "a" with 1 column "b", that's OK.

* delete table "a" and run test2:
<pre>
CREATE TABLE "a" (
	`b`	TEXT CHECK(`b`='A' or `b`='B')
);
</pre>
and visit again the Database Structure view: 1 table "a" but column "b" is not shown.

Can you please confirm if bug is reproducible for you as well.

I guess the problem is in the Database Structure parser, even if sqlite3.g seemed correct to me at first sight (i.e. "CHECK LPAREN expr RPAREN"). Thanks for your work, your time and your product, kindest regards.

Andrea

**Comment by justinclift** [comment]
Would you be ok to try the latest nightly build?  There's been a lot of bug fixing since the 3.4.0 release, including with constraints. (download locations are listed on the front page of the repo)

Hopefully it's already fixed :smile:, though if it's not we'll need to look into it. :wink:

**Comment by thesoftwarebin** [comment]
Hello Justin,

  I downloaded latest build (http://rp.oldsch00l.com/sqlitebrowser/sqlitebrowser.exe.xz) a few minutes ago and repeated test2. It still shows the same defect as in ver.3.4.0. 

May I please ask if you (and/or who reads this) to execute test2? Just to exclude that my setup is wrong. Thanks and kindest regards,

Andrea

**Comment by MKleusberg** [comment]
Hello Andrea!
I can confirm this issue and could track its source down to the combination of a complex check constraint expression (containing an 'or') and using string literals inside it (comparing the column against a number would work). Anyways, the problem is fixed now, so tomorrow's nightly build will hopefully work better for you! :)

**Comment by thesoftwarebin** [comment]
I downloaded the latest build and re-ran test2, now it works correctly. Thank you guys!
