### ISSUE TITLE
word wrap in database cell -window at the right

### ISSUE THREAD

**Issue by theraven1982** [sqlitebrowser/sqlitebrowser#1796]
Details for the issue
--------------------

#### What did you do?
Open a database, view cell contents in the window at the right (Edit Database cell -window). 

#### What did you expect to see?
I hoped to see the contents (text, viewed in text mode) word-wrapped. 

#### What did you see instead?
One long line of text; I have to scroll to the right to see the full contents. 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
Mac OS 10.14.3

#### What is your DB4S version?
Nightly build, 11 March 2019

#### Did you also
EDIT : ISSUE DOES NOT OCCUR IN 3.11.1 (RELEASE)

Didn't find a similar issue (only issue is wrt to word-wrap in the browser view). 
- [ X ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
We recently changed the Qt widget control thingy dongle to a different type of Qt widget control thingy dongle, so a tweak to it might be required - it has numerous properties.
@mgrojo has worked on this, so might have a better idea of what tweak needs to be tweaked...

Thanks for reporting it!

**Comment by mgrojo** [comment]
@theraven1982 You can configure this in "Preferences > SQL > Wrap lines". Despite the section name, it affects all our editors: plain text, XML, JSON and SQL. I'm wondering whether we need different settings, at least for the plain text and the rest of them.

**Comment by theraven1982** [comment]
That fixed the issue! I did look at the settings, but looked over it / wasn't triggered to change it there. So definitely a user error. Only suggestion would be: maybe turn word wrap on by default, as it was like that in the release version (3.11.1 for example)? Thanks for the reply!

**Comment by mgrojo** [comment]
> Only suggestion would be: maybe turn word wrap on by default, as it was like that in the release version (3.11.1 for example)? Thanks for the reply!

Yes, I think I'm going to restore the word wrapping for the text mode in the cell editor. It should apply to all text modes (XML, JSON and plain text) so I'll make it configurable, just in case someone needs to restore the the off-mode for word wrapping for XML and JSON, since that is the default now there. SQL will be still default to off, as it was always in that way and everybody seems to be happing with that, and will preserve its own setting.

**Comment by sky5walk** [comment]
To clarify, if Word Wrap remains a user setting for all editors, how can you set it ON for some editors?
Are you adding Word Wrap options for individual editors?

My vote is no for a fixed Word Wrap ON for text editor. That is confusing to users browsing stored code procedures within a text cell or BLOB cell containing text.

**Comment by mgrojo** [comment]
Before 45c1e2abfd9dd95c8a744c24406b09dff5502e71 we had the following situation:
- SQL tabs, JSON and XML modes in Edit Database Cell: was configurable through Preferences > SQL > Wrap lines, defaulting to Never.
- Text mode in Edit Database Cell was fixed as word wrapping (default for Qt).

After the change, all the editors are controlled through Preferences > SQL > Wrap lines, still defaulting to Never.

What I am thinking is separating the preference for SQL, in one setting (default Never), and Edit Database Cell (for all modes), on another (default Wrap on word boundaries).

But "Preferences > Data Browser" is a bit crowed for a new setting. Maybe it makes sense to add it to the Edit DB Cell toolbar, so it is more accessible.

**Comment by mgrojo** [comment]
@theraven1982 @sky5walk The new option in the Edit Database Cell toolbar for word wrapping will be in the next nightly build.

**Comment by theraven1982** [comment]
Yes, works perfectly! Thanks for fixing, and for the continued awesome work on DB4S!

**Comment by sky5walk** [comment]
Works for me 👍

**Comment by mgrojo** [comment]
Perfect. Thanks to all. I assume we can close this now.
