### ISSUE TITLE
Attach encrypted database results in Out of Memory Error

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1799]
Using the latest nightly build on Windows 10 (also happening with the release build!)

I have two encrypted databases (same key).

I open the first database, then attach the second database.

If I try to execute any SQL that includes any tables in the attached database I'm getting an Out Of Memory Error.

If I try to browse any of the attached tables - at the bottom of the screen where row count should appear it says "determining count of rows..."

If I try the following "PRAGMA integrity_check;" I get an Out Of Memory Error.

If I execute "DETACH DATABASE database_name" then everything returns to normal.

**Comment by chrisjlocke** [comment]
...and I assume opening the second database and performing an integrity check also comes back clean?
...and I assume running any SQL statements on the second database (alone) works fine?
Out of interest, what happens if you open the second database and attach the first database (if that makes sense...) and perform actions on the now attached database.

**Comment by mtissington** [comment]
Integrity check on stand alone second database is clean and SQL statements work fine.
Same error if I swap the databases (open second, attach first).

**Comment by justinclift** [comment]
Ouch.  Probably better to not generate the 3.11.2 builds today after all.  This sounds like a bug of some sort that's likely present in both our release and master branches. :wink:

**Comment by mtissington** [comment]
The latest build now allows me to Attach a database however I'm getting an new error when trying to detach the database using `detach database name` ..

The error is (database name is import)

Execution finished with errors.
Result: database import is locked
At line 1:
DETACH DATABASE import;

**Comment by chrisjlocke** [comment]
Is that after running successful SQL statements?
Are the statements wrapped in a transaction?  (wondering if some transaction is keeping it open?)

**Comment by mtissington** [comment]
Hmm, there is something really messed up around Attach and the issuing 'detach database name'
Now I'm no longer able to get the error `database is locked` when trying to detach.

However if I do the following

1) Click attach button and attach encrypted database (not tried plain db) as 'test'
2) Execute sql 'select * from test.sqlite_master'
3) This works and I can then select other tables without getting the original Out of Memory error.

If I don't do (2) first then any other sql seems to generate the Out Of Memory error...

Very strange.

**Comment by mtissington** [comment]
This is really critical for us - needing to Attach and execute sql statements.

Is there a version that does NOT cause the Out of Memory error?

Thanks.

**Comment by mtissington** [comment]
This seems to be related to the database being encrypted.

If I decrypted both databases and then tried the above (same version of DB Browser) everything works correctly.

Hope this helps...

**Comment by chrisjlocke** [comment]
(See also #1814)

**Comment by justinclift** [comment]
@MKleusberg This sounds like it's related to #1758.  Maybe the fix for that needs a bit of adjusting? :wink:

Note - Am now going through the outstanding GitHub Notifications I've been mostly ignoring for the past 2 weeks, prior to building the 3.11.2 release binaries.  I have a feeling this issue might be a release blocker. :frowning:

**Comment by MKleusberg** [comment]
This should be fixed too in @justinclift's build :smile: Can you try this as well, @mtissington?

**Comment by mtissington** [comment]
@MKleusberg waiting in anticipation ... 😄

**Comment by mtissington** [comment]
Still getting both errors ...

**Comment by justinclift** [comment]
@mtissington This **is** fixed now isn't it?

**Comment by mtissington** [comment]
Yes

Michael

**Comment by justinclift** [comment]
Thanks @mtissington :smile:

Looks like all we're waiting for now, is updated translations for strings.  Then we can do the 3.11.2 release. :smile:

**Comment by laratutoteam** [comment]
**get this easy error solving** https://laratuto.com/solved-out-of-memory-error-in-query-sybase_connect/

**Comment by chrisjlocke** [comment]
Purposely broke the (spam?) link.  Looks like spam but wasn't sure whether to delete or not.  Thinking 'yeah' but also 'meh'.  Seemed to go to a legit page, but couldn't see the point of it here.
