### ISSUE TITLE
Closing database doesn't clear suggestion list or raise error in Execute SQL tab

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1800]
Details for the issue
--------------------

#### What did you do?
Closed the database and executed some SQL statements

#### What did you expect to see?
No suggestions and an error about no open database

#### What did you see instead?
Suggestions and no error about no open database

Useful extra information
-------------------------
So I came back to DB4S after a couple of hours, and forgot I'd closed the database.  Opened the Execute SQL tab,, and the suggestions from the previous database were still working.

![](https://snag.gy/AkNrnI.jpg)

When I executed the SQL, nothing happened.  Well, obviously I was expecting *something*, but nothing - not even an error saying, "what are you doing?  You don't have a database open, idiot!".

Obviously not the end of the world, but thought I'd mention it....

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )

#### What is your DB4S version?

- [x] 3.11.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Makes sense.  Pretty sure I've seen similar happen recently myself too, and just didn't think about it. :smile:

**Comment by mgrojo** [comment]
Should be fixed now. Now the buttons are not reenabled when a new tab is opened and no DB is open. Suggestions for identifiers are removed when the DB is closed.

**Comment by chrisjlocke** [comment]
Thanks @mgrojo .  Will try with the next nightly.  👍

**Comment by chrisjlocke** [comment]
Thanks @mgrojo.  While no suggestions appear, the context sensitive help is still active.  So if you type a table name, it starts off purple, then turns cyan when its a recognised (ex) table name.  A minor point, but thought I'd just mention it... its not life threatening or anything, but might just be a simple one line code change...

**Comment by chrisjlocke** [comment]
Sorry - don't mean 'context sensitive help' - I mean the syntax highlighting.

**Comment by justinclift** [comment]
Ahhh yeah.  Sounds like some cached info still needs clearing. :smile:

**Comment by mgrojo** [comment]
@chrisjlocke Yes, it was an easy fix. It should clear the syntax highlighting now for tables.

**Comment by justinclift** [comment]
Awesome stuff @mgrojo! :smile:

**Comment by chrisjlocke** [comment]
@mgrojo - you deserve a pay rise.  🤣

**Comment by justinclift** [comment]
@chrisjlocke Should this be closed now?

**Comment by chrisjlocke** [comment]
Closing as @mgrojo is just awesome.

**Comment by chrisjlocke** [comment]
Closing as @mgrojo is just awesome.

**Comment by chrisjlocke** [comment]
Closing as @mgrojo is just awesome.

**Comment by chrisjlocke** [comment]
Closing as @mgrojo is just awesome.
