### ISSUE TITLE
Virtual Table data is not being displayed (compared to 3.10.1)

### ISSUE THREAD

**Issue by orbegam** [sqlitebrowser/sqlitebrowser#1801]
Details for the issue
--------------------

#### What did you do?
I opened this DB from the public sqlite-forensic-corpus:
https://faui1-files.cs.fau.de/public/sqlite-forensic-corpus/sqlite_forensic_corpus_v2.0/06/06-01.db

#### What did you expect to see?
I expected to see 10 rows with data in the 'coordinates' virtual table (which are displayed correctly in 3.10.1):
![image](https://user-images.githubusercontent.com/12697808/54283161-1de5d500-45a6-11e9-8ca5-69f44a2fc64a.png)

#### What did you see instead?
No data was displayed in the 'coordinates' virtual table (other, non-virtual tables were displayed correctly)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows 10

#### What is your DB4S version?

- [x] 3.11.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
The schema parser has been slightly tweaked in the nightly, so this issue should be solved there.
There is still a minor 'glitch' in that while the combobox dropdown is populated, the grid itself isn't, so DB4S might show 'coordinates' in the combobox and the grid is blank, but clicking 'Refresh' should happily display the data.

**Comment by chrisjlocke** [comment]
Interestingly you've ticked 'tried out the latest nightly'.  I'm just wondering if the above 'grid-is-blank-but-a-force-refresh-solves-it' helps...

**Comment by mgrojo** [comment]
I can't reproduce this issue. Might it be  #1748? This is what @chrisjlocke is refering about. However, I cannot reproduce that any longer with the master branch, and in theory, v3.11.[0-1] was never affected according to #1748, #1649 and #1701.

**Comment by chrisjlocke** [comment]
I couldn't reproduce it in the nightly, but in 3.11.1 I could.  I think it was 3.11.1.

**Comment by orbegam** [comment]
> Interestingly you've ticked 'tried out the latest nightly'. I'm just wondering if the above 'grid-is-blank-but-a-force-refresh-solves-it' helps...

Tried to check the refresh using tonight's (March 14th) nightly build, but the table was displayed correctly from the start.
Hurray! :)

**Comment by mgrojo** [comment]
Sadly, I'm reproducing it again. It doesn't happen in all circunstances. If you select the Browse Data tab before opening any DB and then you open it, the issue is reproduced.

**Comment by chrisjlocke** [comment]
"the issue" being the main issue of there being no records showing whatsoever, or the sub-issue of the table not being correctly refreshed (the data is there after a refresh).

I'm getting the latter...

![image](https://user-images.githubusercontent.com/7872218/54392765-58339d00-46a0-11e9-8ee3-47f520389a7a.png)

but this has been an issue (and has been noted) for a while.

**Comment by mgrojo** [comment]
For clarifying, what I've reproduced is the already known problem that is solved after a refresh.

**Comment by justinclift** [comment]
It sounds like some event that is supposed to be fired when a subsequent database is loaded... isn't happening?

**Comment by MKleusberg** [comment]
@orbegam Not sure what the problem was here. But if it was indeed the problem which is solved after a refresh (as @mgrojo) said, then it should be finally working in tomorrow's nightly build. Can you give that a try and see if the problem is fixed? :smile:

**Comment by MKleusberg** [comment]
Closing this because I *think* this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time, @orbegam :smile:
