### ISSUE TITLE
Unable to open Chromium SQLITE3 files

### ISSUE THREAD

**Issue by crcarson** [sqlitebrowser/sqlitebrowser#1802]
Details for the issue
--------------------

#### What did you see instead?Get error popup bod with the following:
Could not open database file.
Reason: Invalid file format
Running version 3.11.99 of sqlitebrowser 

Useful extra information
-------------------------
Can open the database file using non-snap version of sqlite browser 3.10.1-2, same level of Ubuntu 19.02 and Chrome.
> DB4S v3.11.99 (Mar 11 2019) [built for x86_64-little_endian-lp64] on Ubuntu Core 16 (linux/5.0.0-7-generic) [x86_64]
> using SQLCipher Version 3.2.0 (based on SQLite 3.8.6)
> and Qt 5.5.1

**Comment by justinclift** [comment]
Thanks @crcarson, that's an interesting bug.  Wonder if it's something to do with the version of SQLite being included with the snap version, compared to the one being included in the non-snap version.

@deepsidhu1313 will probably be interested in this. :smile:

**Comment by crcarson** [comment]
Attempted to open a Crome sqlite DB with all three revisions (907, 874, and 859) of sqlitebrowser available on my system (version 3.11.1).  All failed the same with "invalid file format".  Removed the snap version of sqlitebrowser and install the apt version (3.10.1) and the same DB opened correctly.

**Comment by deepsidhu1313** [comment]
I will look into this issue this weekend. Thanks

**Comment by deepsidhu1313** [comment]
Oh boy ! This is very old issue. @crcarson is it still happening ?

**Comment by crcarson** [comment]
All the available levels of sqlitebrowser work for me now.

3.11.2 non-snap works OK

3.11.99 --beta snap works OK

3.12.99 --edge snap works OK

You can close this if you wish, thanks

**Comment by justinclift** [comment]
Awesome, thanks for following up on this! :smile:
