### ISSUE TITLE
Export results to CSV

### ISSUE THREAD

**Issue by mrgou** [sqlitebrowser/sqlitebrowser#1806]
Hi,

In version 3.11, I can't find the export to csv button for query results. I'm pretty sure there used to be one.

Was this removed or moved to some other place?

Thanks!

R.

**Comment by sky5walk** [comment]
Look at the toolbar for a dropdown button = 'Save The Results View'.

**Comment by chrisjlocke** [comment]
[img]https://snag.gy/xBHTAk.jpg[/img]

**Comment by chrisjlocke** [comment]
![](https://snag.gy/xBHTAk.jpg)

**Comment by mrgou** [comment]
Thought I was missing something obvious! Thanks!
