### ISSUE TITLE
Compilling error 

### ISSUE THREAD

**Issue by sinhaash** [sqlitebrowser/sqlitebrowser#1807]
When compiling our master branch on Windows (MSVC), some warnings are displayed which we might want to clean up:
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(263): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(273): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(425): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(448): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(641): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(643): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
6>C:\git_repos\sqlitebrowser\src\ImportCsvDialog.cpp(649): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

**Comment by chrisjlocke** [comment]
Thanks for reporting.  Already mentioned here though in issue #1423, where its slowly rotting away.... maybe one day when someone is bored, they'll look into it..... haha!!
