### ISSUE TITLE
Only one of the main tabs shown

### ISSUE THREAD

**Issue by CameronBeeler** [sqlitebrowser/sqlitebrowser#1809]
Details for the issue
--------------------

#### What did you do?
attempted to access a sqlite3 database with the browser.  I've successfully accessed the database via command line and a remote web browser.  I've attempted several versions of the SQLITE3 browser and none seem to work.  They were all fine last week.

#### What did you expect to see?
Upon opening the database (no errors or attempt), I normally see the database structure, but now only a blank screen.  I also am not seeing the options for displaying any of the Schema, View Data, etc.

#### What did you see instead?
<img width="1043" alt="Screen Shot 2019-03-18 at 3 20 31 PM" src="https://user-images.githubusercontent.com/32376697/54567542-6da31280-4991-11e9-91eb-d3ab17afe7ec.png">

Useful extra information
-------------------------
> DB4S v3.11.99 (Mar 18 2019) [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.5.0) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by mgrojo** [comment]
How did you reach that state? Did you close all the other tabs and panels?

Using _"View > Reset Window layout (Alt+0)"_ will probably fix the issue.

**Comment by mgrojo** [comment]
See #1675 for further information. This should be documented in the wiki before the final v3.12 release.

**Comment by CameronBeeler** [comment]
OK, I’m fairly certain it was the mac beta version I was using.  Prior to updating last week, sqlite was working just fine.  the day after i logged this issue, another beta version came out, and after updating to that beta v, it now works perfectly fine.  First time I’ve had a beta macosx cause issues…

thanks!
cam

On Mar 18, 2019, at 3:46 PM, Manuel <notifications@github.com> wrote:

How did you reach that state? Did you close all the other tabs and panels?

Using "View > Reset Window layout (Alt+0)" will probably fix the issue.

**Comment by justinclift** [comment]
Sounds like it's working ok now, so going to close this.  If I have that wrong, you're welcome to re-open this so it can be investigated. :smile:

**Comment by CameronBeeler** [comment]
Yes & Perfect.  Thank you Justin!
Cam

On Mar 23, 2019, at 4:29 AM, Justin Clift <notifications@github.com> wrote:

Sounds like it's working ok now, so going to close this. If I have that wrong, you're welcome to re-open this so it can be investigated. 😄
