### ISSUE TITLE
combo-box instead of drop-down list when choosing table

### ISSUE THREAD

**Issue by thomasuser** [sqlitebrowser/sqlitebrowser#1811]
Describe the new feature
--------------------------
How about  having combo-box instead of drop-down list when choosing table at the top, acting in the same manner as cell (suggestions) ?

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
Why is the current control bad, and what improvements would changing it bring?

**Comment by chrisjlocke** [comment]
Note also that you can 'type' in the combobox.  So if you have a load of tables beginning with 'doc' but you want 'documents', if you start typing 'docu' then the focus will jump to the tables beginning with 'docu'.  Just click in the combobox first so it has focus.*

*At least on Windows.  Unsure about other operating systems.  As you deleted the template which asked for that information, I don't know what operating system you're using.

**Comment by thomasuser** [comment]
sorry for  skipping template , did not notice, I use debian(Version 3.11.0;Qt Version 5.11.3;SQLite Version 3.26.0) and there is drop-down (not editable) present not combo-box

**Comment by thomasuser** [comment]
Ok so you say that it is on windows already. Does it mean that for some reason it is not available on linux  or just it needs to be compiled in some different way other than described in https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md

**Comment by chrisjlocke** [comment]
A combobox is just another name for the control.  Different manufacturers call it different things.  Microsoft call those controls comboboxes.  

They're not directly editable, but typing in it shifts the selected item to the closest matching item.  Again, this is a Windows thing, so unsure about Linux.  Try it?  Click in the control, then try typing.  If you have a bunch of tables, and the ones beginning with 's' are way down the bottom, what happens if you press <kbd>s</kbd> in the control?  I appreciate its not editable, but does anything happen?

**Comment by thomasuser** [comment]
It does as you said,  I did not know. It is not as good as you implemented in cells (all available choices are seen at once there - perception)  but is very helpful . Thank you very much sorry for taking you time

**Comment by chrisjlocke** [comment]
This wasn't 'implemented' by us - its a general feature in all comboboxes in the operating system, so should work across all applications.  Its always been there.  Good to know it works in Linux too though.
How many tables are in your schema?  Do you have many tables spelt the same?  I am trying to understand why the dropdown isn't working good for you.

**Comment by thomasuser** [comment]
As time is passing I adding some tables and after lets say a year  it is difficult  to  scroll the list to see what is in there.  You see your browser is getting much better over time and it is all about perception, to quickly find out what is inside and what are the choices. This cell behavior  you introduced it was a bingo. 
Thank you
Yes I do have tables spelt similar and is going be more, sqlite is perfect for many reasons and your browser allows to use it easier and faster.

**Comment by chrisjlocke** [comment]
I find the database structure tab is useful - it lists all tables in one view.  Depending on the height of your screen, you can view many tables.  When you find the one you want, you can right click and select 'Modify table' so it goes straight to the modification of that table - you don't have to find it again in the list.
Ultimately, you don't use the drop down at all - just use the 'database structure' tab and right click.
I find it easier as it also shows the schema - reminds me what fields I am looking for.

**Comment by thomasuser** [comment]
I guess I was too lazy , but on the other side filters on the top and cell input suggestion introduced completely new level of high standard  from user point view  :) 
Thank you have a nice day
