### ISSUE TITLE
Error: The network is not accessible

### ISSUE THREAD

**Issue by TileRunner** [sqlitebrowser/sqlitebrowser#1812]
Details for the issue
--------------------

#### What did you see instead? Error pop-up saying "Error: The network is not accessible" every time I launch the App.

Useful extra information
-------------------------
> DB4S v3.11.0 on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLite Version 3.26.0
> and Qt 5.11.3

**Comment by chrisjlocke** [comment]
I think this is fixed in 3.11.1, which is our current release.
See here. #1595

3.11.1 can be downloaded from here:
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.1

Alternatively, you can turn off the 'Check for updates', as its that which is causing the issue.  The downside to that is that you don't know when new versions have been released (like now....)

**Comment by chrisjlocke** [comment]
Has DB4S been displaying the message of, "a newer version is available" ?

**Comment by chrisjlocke** [comment]
> Installed DB Browser for SQLite (windows 10). 

From our website, or another location?  That location might need a kick in the melons to distribute the correct version.

(Sorry for the multiple messages - editing no longer works for me...)

**Comment by justinclift** [comment]
>Sorry for the multiple messages - editing no longer works for me...

Just in this repo?  You should (in theory) have admin level access.

**Comment by chrisjlocke** [comment]
Nah, its an 'Edge' thing.  There is a dirty great banner at the top saying, "GitHub no longer supports your version of Edge" (ironic, as they're both Microsoft...) but this is a work PC, to which I can't update it (as Edge is baked into the OS, not a separate install).  Ho hum...

**Comment by justinclift** [comment]
Maybe a .zip install of some other browser would work?

**Comment by chrisjlocke** [comment]
Unfortunately, I'm not in a position to do that.  :-(  Quite restrictive with what you run and why...

**Comment by justinclift** [comment]
No worries, was just a thought. :smile:

**Comment by TileRunner** [comment]
Thanks chrisjlocke, the latest release did fix this issue.
