### ISSUE TITLE
How to import Microsoft Office Excel into your database

### ISSUE THREAD

**Issue by JacinthPan** [sqlitebrowser/sqlitebrowser#1813]
What is your question
-----------------------

**Comment by JacinthPan** [comment]
How to import Microsoft Office Excel into your database

**Comment by JacinthPan** [comment]
How to import Microsoft Office Excel into your‘s database

**Comment by JacinthPan** [comment]
How to import Microsoft Office Excel into your database(sqlitebrowser)

**Comment by chrisjlocke** [comment]
The easiest method is via CSV.  Export your spreadsheet to CSV, and import into an SQL database via that same CSV file.
Its a shame you deleted the template for queries.  What version of DB4S are you using?  What operating system are you using?

**Comment by JacinthPan** [comment]
> 最简单的方法是通过CSV。将电子表格导出为CSV，然后通过同一CSV文件导入SQL数据库。
> 很遗憾你删除了查询模板。您使用的是哪个版本的DB4S？您使用什么操作系统？
Thank you. I learned it.

**Comment by JacinthPan** [comment]
> The easiest method is via CSV. Export your spreadsheet to CSV, and import into an SQL database via that same CSV file.
> Its a shame you deleted the template for queries. What version of DB4S are you using? What operating system are you using?

Thank you. I learned it.

**Comment by JacinthPan** [comment]
> The easiest method is via CSV. Export your spreadsheet to CSV, and import into an SQL database via that same CSV file.
> Its a shame you deleted the template for queries. What version of DB4S are you using? What operating system are you using?

Are you the developer of this project? I hope you can join the Chinese language. It will good for me and you.

**Comment by chrisjlocke** [comment]
Thats great.

**Comment by justinclift** [comment]
> I hope you can join the Chinese language.

Some of our previous versions have been translated to translated to Chinese:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/translations/sqlb_zh.ts

It's a volunteer thing though, so depends on people with the right language knowledge having some free time.  Is it something you would be willing to help with? :smile:
