### ISSUE TITLE
Newer version for PortableApp (version 3.11.x or so)

### ISSUE THREAD

**Issue by indrakaw** [sqlitebrowser/sqlitebrowser#1819]
What is your ~~question~~ demand
-----------------------
Newer version for PortableApp (version 3.11.x or so). The latest portable was 3.10.1 and [haven't been updated since 2017](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1).

Please update!

PS: I installed portable version [via scoop](https://github.com/lukesampson/scoop).

**Comment by justinclift** [comment]
Yeah, that's on purpose. :smile:

We normally ping the PortableApp people after a new release has stabilised, which this time around hasn't happened yet.  In theory (!), the last of the outstanding serious bugs was fixed last night (and people can test via our nightly builds).

We'll wait a few days (eg to Friday) just to make sure it's all good after all, then create the next release (3.11.2) + and notify the PortableApps teams of the new release. :smile:

**Comment by justinclift** [comment]
As a thought, when we make this next release (likely Friday some time), would you be interested in creating a PR [in the scoop-extras repo](https://github.com/lukesampson/scoop-extras/blob/master/bucket/sqlitebrowser.json), with the update?

**Comment by justinclift** [comment]
Oh, my bad wording. :wink:

I meant once the PortableApps version of our next release is ready.  It's normally done within a day of us notifying the PortableApps people.

**Comment by justinclift** [comment]
@indrakaw We've just release DB4S 3.11.2:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-11-2-released/

Wanna get that PR on the scoop-extras repo done? :smile:

**Comment by justinclift** [comment]
... and I just remembered this needs to wait for the PortableApp version.  Oops.

Just about to email the PortableApp team.  I'll let you know when it's ready. :smile:

**Comment by indrakaw** [comment]
Bump.

It's about two weeks ago and I think the portableapp version is dead long time ago. 🕵

**Comment by justinclift** [comment]
@indrakaw Yeah.  Emailed John a few days ago, but haven't heard back yet. :smile:

**Comment by chrisjlocke** [comment]
I'm happy to have a look if required.  Its relatively easy to package up...

**Comment by chrisjlocke** [comment]
Can download from here:
http://www.chrisjlocke.co.uk/downloads/2019/Apr/SQLiteDatabaseBrowserPortable_3.11.2_English.paf.exe

**Comment by justinclift** [comment]
Awesome, thanks @chrisjlocke!

I'll email John to let him know.  He may want to sign it before we put it online, or if not then Martin probably should. :smile:

**Comment by justinclift** [comment]
Trying it out in a VM just now, it should probably launch the SQLCipher executable rather than the SQLite one.  They're both equivalent now, so technically the SQLite exe could probably be dropped... I just didn't think of it in time. :innocent:

**Comment by chrisjlocke** [comment]
No worries - I can amend.  Gimmmmmme a sec.....

**Comment by chrisjlocke** [comment]
OK, program updated.  Link is the same.

**Comment by justinclift** [comment]
Thx, trying it out now... :smile:

**Comment by justinclift** [comment]
Yep, looks good.  I'll email John about it now.

Thanks heaps @chrisjlocke. :smile:

**Comment by chrisjlocke** [comment]
No problem.  Good to know I can still do something... ;) haha!

**Comment by justinclift** [comment]
Oh... just realised it should probably be the win32 version, not the win64.

The win32 one should run on anything - including WinXP, though I'm not sure anyone's tested it - whereas the win64 build won't run on 32-bit PCs. :wink:

**Comment by chrisjlocke** [comment]
There are both in the installer.  It picks depending on the OS.  So if
you've a 64bitty PC, it'll run the 64bit version.
If you've a 64bittty OS, you can still run the 32bit version if you want -
just find the 32bit folder in the 'app' directory...

The previous portable app version had a min version of 'Vista', so I
lowered that to 'XP'.  I don't have an XP box to test that though.

**Comment by justinclift** [comment]
No worries, sounds like you're ahead of the curve. :smile:

**Comment by chrisjlocke** [comment]
So far ahead, I've come back round 360 degrees.  I'm back where I started.
:(

**Comment by justinclift** [comment]
Made a post on the PortableApps forum: https://portableapps.com/node/60202

It's been added to their list: https://portableapps.com/development/outdated

Seems like a bunch of backlog.  Maybe we should sign the package @chrisjlocke created, put it on our website, and update our Download page link to use it?

**Comment by indrakaw** [comment]
The manifest app on scoop.sh is already updated: https://github.com/lukesampson/scoop-extras/issues/1926
They had switched to zip version. With this I can easily work around with SQLite GUI without required Administrator permission to install.

Even thought the latest portable version isn't publicly released yet, but I'm already obtained my goal. Should we close this issue?

**Comment by justinclift** [comment]
Yeah, we might as well close it.  The PortableApp one will be available at some point, but it's more dependent on their team than us. :wink:

**Comment by justinclift** [comment]
Just for completeness, thanks to @chrisjlocke and [JohnTHaller](https://twitter.com/JohnTHaller), the official PortableApp version is ready now:

&nbsp; &nbsp; https://download.sqlitebrowser.org/SQLiteDatabaseBrowserPortable_3.11.2_English.paf.exe

No idea if the scoop.sh people will use that or keep with the .zip version. :wink:
