### ISSUE TITLE
Ability to change language

### ISSUE THREAD

**Issue by samir-aguiar** [sqlitebrowser/sqlitebrowser#182]
I believe it would be quite useful to be able to change the application language in the preferences dialog.
For example, my system language is German because I'm trying to learn it, but I like to use some applications in English because otherwise I have no clue of what they are saying.

I could work on this if you like.
From what I saw, DB Browser would probably need to be restarted to apply the change (as does Qt Creator when changing the language).

One problem would be where to put this option in the preference dialog. I thought about creating another tab (e.g. "Interface"), but I'm not sure if a tab with only a single drop down menu would look nice.

**Comment by justinclift** [comment]
Interesting idea.  On Linux and OSX it's not too difficult to change the language for a program prior to launch (change the LANG environment variable, then launch).  But that's not the case for every OS (eg windows), so this is probably a useful enhancement.

**Comment by Z4us** [comment]
Perhaps all text to be translated in a seperate dynamic file


Kind regards / Vriendelijke groeten / Cordiali saluti,
Klaas V <http://www.innocentisart.eu/klaasv/indexw.html> Innocentisart
<http://www.innocentisart.eu>
klaasv@innocentisart.eu

**Comment by samir-aguiar** [comment]
@Z4us sorry, but I didn't understand. What do you mean by separate file? I meant an option in the Preferences pane to select between the .qm translation files.

@justinclift Can you please test if you can change the language on the Mac (by changing the environment variables) with the lastest version? While working on this I found out that I cannot change it and I think it might be a bug.

**Comment by MKleusberg** [comment]
@samir-aguiar 
If you wanted to work on this that'd be awesome :smile: As for the question of where to put the new option in the preferences dialog I think it might be best to create a new tab (called 'Application' or 'Interface' or similar) for this. If you move the 'Default Location' option to that tab as well, the language option wouldn't even be the only field in there.

**Comment by Z4us** [comment]
@https://github.com/samir-aguiar I mean it may be possible that developers make a kind of template for translators to easily translate the relevant data in the source to be translated to their language.

**Comment by MKleusberg** [comment]
@Z4us There's a tool included in the Qt framework for this: Qt Linguist (http://doc.qt.io/qt-5/qtlinguist-index.html). The basic translation process is to add a new entry to the TRANSLATIONS part in the src/src.pro file (currently around line 90), then re-build the project. Now, the build system will collect all the strings to translate in the entire application and put them in the file you just added. This newly created ts file can than be opened in Qt Linguist and using Qt Linguist you can translate all the strings. After saving and rebuilding the translation should be in the application.
By the way, if somebody, probably someone who already made a translation, wanted to write a more detailed Wiki page about this process, that would be fantastic :)

**Comment by samir-aguiar** [comment]
@MKleusberg great, I'm working on this :grinning:

**Comment by justinclift** [comment]
Hmmmm, thinking about where to put a "change language" user interface element... shouldn't that go on the main window somewhere (unobtrusive)?

Just thinking of this from the point of view of.... "what happens if it starts up in a language I can't read?"  (eg mandarin, japanese, etc).  It would be very tricky to navigate to the preferences dialog in that situation, let alone finding the correct tab/options/'OK'-button.  A language choosing element on the main UI though would let me solve the problem without getting stuck.

Does this make sense?

**Comment by samir-aguiar** [comment]
I've just opened a pull request, but let's leave there while we decide on this then. :)

But I don't know, although this can happen most users will probably use that option once (if ever) and leave it alone for good. In such cases I think it would be strange to have it on the main screen.

**Comment by glawrence** [comment]
I think if any app opens in a language you can't understand there is something very wrong, so I would kill it and then check my OS settings and search for known issues. If that is still not fixable I would try it on another machine or read someone's advice, probably from a ticket here, to navigate in the language I don't know to select one I do. So, my personal view is not on the main screen but in the preferences, somewhere.

Note: just giving a point of view, in a friendly way, to help

**Comment by justinclift** [comment]
@samir-aguiar @glawrence No worries at all, I was just kinda idly thinking out loud. :wink:

eg whatever you guys come up with is all good.  If it turns out to be non-optimal in practise, someone will probably create an issue about it then. :grinning:

**Comment by glawrence** [comment]
Much better to think out loud @justinclift and have the discussion in public, especially for an open source project. @samir-aguiar I think the key is getting it working, then we can all see it, test it and you or someone can always comment, suggest or tweek it later. I always prefer to get functionality in and then tidy up afterwards.

**Comment by samir-aguiar** [comment]
Keep thinking out loud @justinclift, ideas are always welcome. :smile: 
I couldn't agree more, @glawrence. The current pull request is for a working version if you want to give it a go.

**Comment by justinclift** [comment]
Are we ok to close this one now, as #187 is merged?

**Comment by samir-aguiar** [comment]
Please if possible wait until I make the changes suggested by @MKleusberg because I might ask for suggestions. :smile:

**Comment by justinclift** [comment]
Sure, no worries at all. :smile:

**Comment by samir-aguiar** [comment]
So I've implemented the changes proposed by @MKleusberg and the behavior is the following: it adds the suffix "[System language]" when the language has a corresponding translation and, if that's not English, it adds "[Default language]" to English. It also moves the selected language to the top.

However, for English the resulting text is "English (United States) [System language]", which seems kinda ugly to me. It's also a little long, so the combo box width would need to be increased. Any suggestions here?

**Comment by justinclift** [comment]
Heh, nah that length is fine.  Feel free to widen out the combo box as needed for it. :smile:

**Comment by samir-aguiar** [comment]
Okay then!
What about some flags? :smile: 
![image](https://cloud.githubusercontent.com/assets/3753623/6118080/2783eb5e-b0ba-11e4-8d2a-e3a19fd8c18d.png)

**Comment by justinclift** [comment]
Flags aren't a bad idea, but some people can have a problem with them. eg where there are conflicts over national boundaries

That being said, if it's easy to include them, maybe lets do that anyway... we can adjust later if people have a serious issue with them. :grinning:

**Comment by justinclift** [comment]
... they do add some nice colour... :innocent:

**Comment by samir-aguiar** [comment]
It's actually quite easy to add them; QComboBox supports passing a QIcon() along with the data, so it would be a matter of including the images in the resource file. Of course, a image file would need to be added for every new translation.
I've found [this pack](http://www.iconarchive.com/show/world-flags-icons-by-osiris.html) that contains a lot of flags and is free to use according to the license. There's also [some repos](https://github.com/search?utf8=%E2%9C%93&q=flags) here.

**Comment by justinclift** [comment]
Hmmm, yeah, lets add them.  Does this look useful?

&nbsp; &nbsp; https://github.com/sqlitebrowser/iso-country-flags-svg-collection

Forked that to our own org repo, so it doesn't go away or disappear mysteriously. We can delete it if it turns out not to be useful.

**Comment by samir-aguiar** [comment]
Yeah, that's good. I'll be doing some tests and commit later this week.

**Comment by samir-aguiar** [comment]
Well, I guess it's done.
The system and default language (when the former is not American English) now have a suffix appended to them and the chosen language stays on top.

I've done a lot of testing with those flags and couldn't get them to look nice when building with small resolutions, so I've just built 320x240 images and manually rescaled them with Gimp.

If someone could test the width of the combo box under Windows that would be great. I've tested under OSX and Linux, but I couldn't find a setting that would make it look aligned with the QLineEdit above it, so I increased the minimum size of the QLineEdit. Not sure if that won't look weird on Windows as they don't look the same under different OS.

**Comment by justinclift** [comment]
Just tried the latest nightly on Win7, and the combo box width looks really good.  Good stuff! :grinning:

Interestingly, only "English (United States) [System Language]" is available in the drop down box.  I'll create a new issue for that in a minute (guessing its a packaging problem on Windows).
