### ISSUE TITLE
Migrating servers from Scaleway

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1823]
Yesterday Scaleway decided to lock our Scaleway account (which all of our infrastructure is hosted in), with no warning, notice, etc.

Although our servers are still online, it became impossible to manage them.  eg shut down unneeded ones, start new ones, reboot existing ones, etc.

They're claiming I have an unpaid balance on another account with them.  This may be true, as I initially set up a personal account some months ago to check out their services, prior to setting up this proper one.

However, they're refusing to provide any details of the other account, so I can't login to it to find out if it's legit (etc).

Needless to say, using Scaleway for our hosting into the future isn't an option. :frowning:

**Comment by justinclift** [comment]
In phone conversation with "Eddy Azzaro" from their "Team Trust and Safety" team just now... the unpaid balance they did all this over was 3 euro.

**Comment by chrisjlocke** [comment]
Good service, but poor customer service.  Sounds very common.  For general hosting (shitty websites) I used a UK company called Vidahost.  They were cheap, but support were awesome.  Really friendly and dedicated.  Then they were taken over, but continued with the same name.  Then prices went up.  Then support suffered.  Then everyone left.  Gah.

**Comment by justinclift** [comment]
Yeah, some bits about Scaleway are really good.  But it's just not feasible to host critical infrastructure with a place that will lock/freeze accounts with no warning, and then not respond for 24 hours.

We might be able to use them for non-critical stuff, but meh... why bother.

**Comment by glawrence** [comment]
What are our requirements?

**Comment by justinclift** [comment]
Stable (Linux) servers, preferably running CentOS (7), and being able to transmit 4+ TB a month without killing us financially.  "Without killing us financially" meaning it must be something we can cover through our Patreon account. :smile:

Was investigating Digital Ocean earlier today, and they seem to sponsor some OSS projects, so that might be a good option.

**Comment by justinclift** [comment]
Progress update: We've worked out a sponsorship agreement with Digital Ocean.  So, will be migrating servers there.

Other stuff (some WebAssembly foundation pieces) is higher priority at the moment, so migration will come after that. :smile:

**Comment by MKleusberg** [comment]
Seems like we can close this issue :smile:

**Comment by justinclift** [comment]
Re-opening this, as Scaleway have decided to stop supporting ARM and ARM64 servers at the end of the year.  So, we'll need to migrate those servers to either a different architecture, or to Digital Ocean.  Either way will work. :smile:

**Comment by justinclift** [comment]
Over the past few days I've migrated several of our servers from Scaleway to Digital Ocean.  Thus far it's not really anything people would notice.

Over today and tomorrow though, I'm migrating stuff that people *might* notice if/when there's a changeover of DNS or rebooting something.  So, things *could* be a bit spotty over the next few days, though I'll make reasonable attempts to avoid that. :smile:

**Comment by Z4us** [comment]
Justin case I notice I promise not to tell anybody else 😜

Klaas ‘Z4us’ van B. V, #linguovator

**Comment by justinclift** [comment]
Migrated the main database server across yesterday, only the stats and monitoring servers to go.

Weirdly, our download numbers and daily usage stats are remarkably lower after migrating the  the download server to Digital Ocean:

&nbsp; &nbsp; https://sqlitebrowser.org/stats/

No idea what's causing it.

* It doesn't seem like a DNS problem, as the new IPv4 and IPv6 entries seem ok and have had 24+ hours to propagate.
* The server load is barely registering on cpu, io, bandwidth, so not a resource problem.
* There are no firewall restrictions on port 80 (http) nor 443 (https).

Anyone have ideas?

**Comment by justinclift** [comment]
Hmmm.  We should probably turn off support for TLS 1.0 and 1.1 for the download server now too, as those are officially deprecates as of ages ago.

**Comment by justinclift** [comment]
Done.  The download servers now require TLS 1.2 or better.  Not sure how badly that'll affect our download numbers too. :man_shrugging:

**Comment by chrisjlocke** [comment]
>  Weirdly, our download numbers and daily usage stats are remarkably lower
after migrating the the download server to Digital Ocean:

Are they?  They seem on par or a tad higher compared with October...

[image: image.png]

**Comment by justinclift** [comment]
The download server migration was about 2 days ago, so the recent bump in activity is likely a result of the COVID-19 lockdown. :man_shrugging:

Looking at the traffic flow on the download server over the past ~1/2 hour or so, a tremendous number of the incoming connections were reporting TLS failures.  That was with the server binary compiled using Go 1.13.10, which is a slightly older release series.

Recompiled it with Go 1.14.2, and the TLS failures have mostly gone away.  Guessing there was some kind of significant TLS protocol handling improvement with the Go 1.14 release.

Hopefully that translates into our download and daily user numbers recovering. :smile:

**Comment by justinclift** [comment]
Heh Heh Heh.  Major cause of the "stats slump" was my not enabling a cronjob (like a scheduled task in windows) that runs the stats updating program.  Turned that on, and told it to process all of the historical logs as well for good measure.  Stats seem ok again now, with the expected slump during the migration period.

**Comment by justinclift** [comment]
All of our infrastructure has now been migrated off of Scaleway, and onto Digital Ocean.  Monitoring, backups, etc are all in place and are functional.

Things still left to be done:

* Turn off the remaining VM's in Scaleway, which I'll do in a few days.  Leaving them there for the moment "just in case" there's something on any of them which I've forgotten about and still needs copying/backing-up/etc.
* Add Digital Ocean logo to the footer of our pages.
* Let the Digital Ocean marketing team know. :wink:

**Comment by chrisjlocke** [comment]
Can this now be closed (again) ? 😄

**Comment by justinclift** [comment]
Good point, yep.  We have nothing in Scaleway any more, thankfully.  That was a bad experience I don't want to repeat. :wink:
