### ISSUE TITLE
Crash under Fedora 29

### ISSUE THREAD

**Issue by aaronsaunders** [sqlitebrowser/sqlitebrowser#1824]
Details for the issue
--------------------

#### What did you do?
> $ sqlitebrowser
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

"New Database"
Import -> File from CSV -> chose file and imported

Get following error in terminal:

> QFSFileEngine::open: No file name specified

Modify Table. Click on "TYPE" dropdown to change data type.

![Screenshot from 2019-03-27 16-04-45](https://user-images.githubusercontent.com/681815/55087461-70e18100-50aa-11e9-8de6-c3c2efa4aa10.png)

Crashes with following in cli:
> Segmentation fault (core dumped)

Tried with Wayland but I get the same error  and the windows look really buggy...

> $ export QT_QPA_PLATFORM=wayland
> $ sqlitebrowser
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> QSocketNotifier: Can only be used with threads started with QThread
#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
Linux: ( distro: Fedora 29 64-bit)

#### What is your DB4S version?
 3.10.1
Qt 5.11.1
SQLite 3.24.0

#### Did you also

- [ N ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ y] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Would you be up for building from source code, in order to test with something newer than our 3.10.1 release? :smile:

If so, the instructions for building on CentOS/Fedora are tested reasonably frequently, so should work without problem.  In theory. :wink:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#centos--fedora-linux

**Comment by justinclift** [comment]
No worries at all @aaronsaunders. :smile:
