### ISSUE TITLE
disable autofill suggestions

### ISSUE THREAD

**Issue by JackArcher2** [sqlitebrowser/sqlitebrowser#1825]
Describe the new feature
--------------------------
Ability to disable that pop up autofill suggestions inside the browse data tab for the table cells AND to be able to enter the data in such a way that you can still control the direction of the next cell by press the arrow keys.
The current issue is that as long as each value of the cell is unique it appears to be working as intended, but as soon as a value repeats or starts to repeat, the auto suggest pops up and interrupts the flow of entering data.

The issue is you need to press extra keys or mouse clicks to confirm what you are entering or get rid of the popup. This can equate to entering the data twice (by keystroke count) for every cell if your data is simply the value 1 for 200 cells you will need to press - 1, enter, arrow down, 1 enter arrow down, etc
Instead of press 1, arrow down , 1, arrow down etc

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
#537

#### Does this feature exist in another product or project? Please provide a link.
no

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Yes
![autofill](https://user-images.githubusercontent.com/48897538/55123594-9c2f9480-50d9-11e9-957e-71b16cbe13ff.png)

**Comment by JackArcher2** [comment]
I just realized in this particular situation where the values are the same, you can copy a value to the clipboard and highlight all the consecutive 200 column cells and paste, done. However the suggested feature would still be useful for a full manual data input when the values are not the same.

**Comment by justinclift** [comment]
Yep, makes sense to me too.  I kind of wonder if some keyboard shortcut to toggle it on/off would be suitable? This **seems** like an optimisation request mostly suited to people with good keyboard skills (not a bad thing). :smile:

**Comment by mgrojo** [comment]
You can disable this through "Preferences > Data Browser > Content > Row count threshold for completion". Set the value to 0 to disable completion. Maybe that should easier to find.

Some kind of temporary disabling would also make sense. Or make enter to move to the cell bellow, as suggested in #1669. But I tried to implement that and gave up. It wasn't so easy.

**Comment by JackArcher2** [comment]
Initially, I had looked over the preferences and didn't see that option or rather I saw it and didn't know what it did. (Yes I see the mouseover toolip now that explains it.)
"Row count threshold for completion" sounded like some databasy stuff so I just blocked it out of my mind.
Maybe add in the word "**auto** completion"? or do a combo thing where it just says "Auto Complete = ON/OFF" if it is checked off (this would set to 0 in the background). If checked on then show that whole "row count threshold..." thing.

Thanks for your support, the answer solved the issue since the option already existed.

**Comment by justinclift** [comment]
As a data point, when entering a bunch of data into an example database just now this problem showed up for me too.

In my case, I'm used to being able to type or paste data in, then hit tab to go to the next field to do the same there.  When the automatic suggestion pops up, the tab key is no longer recognised.  Or at least, it no longer triggers moving to the next field.

Disabling the pop-up in preferences did resolve it.  But I sort of wonder if it would be better to have the tab key be recognised while the pop-up suggestions are enabled... :thinking:
