### ISSUE TITLE
Warnings when compiling with MSVC 2015

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1828]
Watching the nightly build with MSVC 2015 on Win32, noticing a few unusual warnings being displayed:

```
6>  sqlitetablemodel.cpp
6>C:\git_repos\sqlitebrowser\src\sqlitetablemodel.cpp(247): warning C4018: '<': signed/unsigned mismatch
6>  RowLoader.cpp
6>  sqlitetypes.cpp
6>C:\git_repos\sqlitebrowser\libs\antlr-2.7.7\antlr/CharScanner.hpp(566): warning C4996: 'stricmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _stricmp. See online help for details.
6>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\string.h(568): note: see declaration of 'stricmp'
6>  Query.cpp
6>C:\git_repos\sqlitebrowser\src\sql\Query.cpp(71): warning C4018: '<': signed/unsigned mismatch
6>  sqltextedit.cpp
```

Seems to be these rows:

https://github.com/sqlitebrowser/sqlitebrowser/blob/8ce0b0071f32e81d1f2840efaba8728513a53282/src/sqlitetablemodel.cpp#L247

https://github.com/sqlitebrowser/sqlitebrowser/blob/8ce0b0071f32e81d1f2840efaba8728513a53282/src/sqlitetablemodel.cpp#L247

Potential problem?

**Comment by MKleusberg** [comment]
Both warnings should be harmless. But since we don't want any warnings at all, I have fixed them in the last commit. Can you check if MSVC is happy now? :smile:

**Comment by justinclift** [comment]
Thanks @MKleusberg, that fixed those warnings. :smile:
