### ISSUE TITLE
Can't remove password from an encrypted database any more

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1829]
Just discovered an important bug when testing out an initial build of 3.11.2 release binaries.

Previously (eg in 3.10.1), to remove the encryption from a database it just needed to be saved ("Set encyption") with an empty password.  eg nothing in the password and password confirmation fields

With our current `v3.11.x` branch, if nothing is put in the password and password confirmation fields then something seems to internally automatically reuse the current password.

So, removing the password from an encrypted database doesn't seem to work any more.

Completely guessing here... maybe some internal variable just needs the new "empty" setting applied?

@MKleusberg I think this is one for you. :smile:

**Comment by MKleusberg** [comment]
I'm still using SQLCipher 3.4.1 here and can't seem to reproduce it with that. So this is going to be a blind one :wink: As a first guess, can you try with this patch applied?
```diff
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index 06ea7a0b..b1c44a52 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -3225,14 +3225,18 @@ void MainWindow::editEncryption()
             ok = db.executeSQL(QString("ATTACH DATABASE '%1' AS sqlitebrowser_edit_encryption KEY %2;").arg(db.currentFile() + ".enctemp").arg(cipherSettings.getPassword()),
                                false, false);
         qApp->processEvents();
-        if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_page_size = %1").arg(cipherSettings.getPageSize()), false, false);
-        if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_hmac_algorithm = %1").arg(cipherSettings.getHmacAlgorithm()), false, false);
-        if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_kdf_algorithm = %1").arg(cipherSettings.getKdfAlgorithm()), false, false);
-        if(ok)
-            ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.kdf_iter = %1").arg(cipherSettings.getKdfIterations()), false, false);
+
+        if(cipherSettings.getPassword() != "''")
+        {
+            if(ok)
+                ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_page_size = %1").arg(cipherSettings.getPageSize()), false, false);
+            if(ok)
+                ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_hmac_algorithm = %1").arg(cipherSettings.getHmacAlgorithm()), false, false);
+            if(ok)
+                ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.cipher_kdf_algorithm = %1").arg(cipherSettings.getKdfAlgorithm()), false, false);
+            if(ok)
+                ok = db.executeSQL(QString("PRAGMA sqlitebrowser_edit_encryption.kdf_iter = %1").arg(cipherSettings.getKdfIterations()), false, false);
+        }
 
         // Export the current database to the new one
         qApp->processEvents();
```

Also, did you check whether you can change the password instead of removing it?

**Comment by justinclift** [comment]
Sure, gimme a few minutes. :smile:

**Comment by justinclift** [comment]
As a thought, for experimental patches like this... just chuck them in another branch and point at it.  I have to put them in another branch + update the build script to use that alternative branch anyway. :smile:

**Comment by MKleusberg** [comment]
Sure, I'll do that next time :smile:

**Comment by justinclift** [comment]
k, it's not working for removing the password.

**Comment by justinclift** [comment]
Interestingly... using a different password doesn't use the new password either.  It's still encrypted using the old one.

**Comment by justinclift** [comment]
Just in case it makes a difference, I've only been trying this with the "SQLCipher 4 defaults" option selected.

**Comment by MKleusberg** [comment]
That's weird. But encrypting from plain database works? I have pushed a new commit to the same branch with my next attempt to fix this. I've also just tried the SQLCipher 4 defaults option and it made no difference for me. So if that last commit doesn't help I'll probably need some time to come up with a new idea :wink:

**Comment by justinclift** [comment]
> But encrypting from plain database works?

Yep.  Or at least it did before we started adding these patches.  I'll rebuild and try again. :smile:

**Comment by justinclift** [comment]
Yep, that last patch fixed the problem.  Now the new password takes effect, and passwords can be removed by leaving the new password fields blank.

Well done @MKleusberg. :smile:

**Comment by MKleusberg** [comment]
Awesome! I'll make a proper commit out of it and apply it to master and v3.11.x in a second :smile:

**Comment by justinclift** [comment]
Tested with both SQLCipher 3 and SQLCipher 4 defaults.  All good. :smile:

Thanks. :smile:

We forgot to notify the translators, which @mgrojo has just done.  So, we'd better leave the actual binary building for a bit after all.  Oops, :face_with_head_bandage:

**Comment by MKleusberg** [comment]
Heh heh, no worries :smile: 

The fix is applied to both branches now. Good catch by the way :+1:

**Comment by justinclift** [comment]
Awesome.  Thanks heaps. :smile:

**Comment by DKMR** [comment]
I'm also unable to remove or change the database password in the latest release. Regardless of what I try, the original password is still required to decrypt the database. This matches the behavior described in this issue 1:1. Possibly a regression?

**Environment**
- DB Browser for SQLite 3.13.1
- Last commit hash when built: ce16bd0
- Windows 11 ARM64
- Built for arm64-little_endian-llp64, running on arm64
