### ISSUE TITLE
Build error on CentOS 7, ‘SQLITE_DETERMINISTIC’ was not declared in this scope

### ISSUE THREAD

**Issue by GRArmstrong** [sqlitebrowser/sqlitebrowser#1837]
Details for the issue
--------------------

#### What did you do?
Followed the instructions in [BUILDING.md](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#centos--fedora-linux) to build sqlitebrowser.

```
$ sudo yum install ant-antlr antlr-C++ cmake gcc-c++ git qt-devel qt5-linguist qt5-qtbase-devel sqlite-devel
$ git clone https://github.com/sqlitebrowser/sqlitebrowser
$ cd sqlitebrowser
$ cmake -Wno-dev .
$ make
```

#### What did you expect to see?
Succesful building

#### What did you see instead?
During the make stage, this error occurs.

```
[ 81%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sqlitedb.cpp.o
/home/grarmstr/Downloads/Git-Repos/sqlitebrowser/src/sqlitedb.cpp: In member function ‘bool DBBrowserDB::open(const QString&, bool)’:
/home/grarmstr/Downloads/Git-Repos/sqlitebrowser/src/sqlitedb.cpp:195:27: error: ‘SQLITE_DETERMINISTIC’ was not declared in this scope
             SQLITE_UTF8 | SQLITE_DETERMINISTIC,
                           ^
make[2]: *** [CMakeFiles/sqlitebrowser.dir/src/sqlitedb.cpp.o] Error 1
make[1]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
make: *** [all] Error 2
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ CentOS 7 with kernel 3.10.0-957.10.1.el7.x86_64 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: Current master (commit d4401f9705cef1e04d0a165684b0906677ec498c)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Note** that I was able to build, install, and run sqlitebrowser from **tag v3.11.2**.

I was also able to build, install, and run sqlitebrowser from master having added the line `#define SQLITE_DETERMINISTIC    0x800` to the top of src/sqlitedb.cpp.

**Comment by justinclift** [comment]
Thanks @GRArmstrong checking this now on my local CentOS 7 x64 workstation. :smile:

**Comment by justinclift** [comment]
Yep, it's happening for me too.

**Comment by justinclift** [comment]
Hmmm, may not be a missing include.  `SQLITE_DETERMINISTIC` is documented [on the SQLite website](https://www.sqlite.org/c3ref/c_deterministic.html).

Guessing it's probably a case of us using a new SQLite `#define` than what's shipped with CentOS 7 (sqlite-devel-3.7.17-8.el7).

Maybe we should just include it in `sqlitedb.cpp`, as @GRArmstrong mentions works? :smile:

**Comment by MKleusberg** [comment]
Looks like the SQLite version in CentOS 7 is too old :wink: The ```SQLITE_DETERMINISTIC``` flag was [added on 2013-12-14](https://www.sqlite.org/src/info/5716fc2341ddd8cf) and CentOS's SQLite library was [released on 2013-05-20](https://sqlite.org/releaselog/3_7_17.html). I didn't expect that :smile: 

That said, with the last commit it should be working again :smile:

**Comment by GRArmstrong** [comment]
Can confirm that cc8401fb27282aa7a7e8fc550366b8257047a2c7 has resolved this issue. Thanks for the speedy fix!
