### ISSUE TITLE
Allow reload of SQL files (Execute SQL tab)

### ISSUE THREAD

**Issue by AlexAurand** [sqlitebrowser/sqlitebrowser#1839]
I would like the Execute SQL tab to reload SQL files that have been changed by another process. This reload process would only happen if no changes have been made to the SQL file in DB Browser since initial load or since the last save.

Setup:
* Open a SQL file in DB Browser Execute SQL tab
* Open same SQL file in another editor 
* Make and save changes in other editor

Current behavior:
* SQL file in DB Browser still shows old contents
* To update SQL file contents in DB Browser, I must close the tab for that file, then reopen in a new tab ("Open SQL file" button)

Desired behavior:
* (Preferred) SQL file in DB Browser shows updated contents immediately
* (Alternative) DB Browser indicates that underlying file has been modified and gives option to refresh from disk

**Comment by justinclift** [comment]
In theory, you should be able to "Refresh" the contents of the Browse Data tab and it should show changes, even those made externally.

Have you tried the Refresh approach? :smile:

**Comment by amaurand** [comment]
> In theory, you should be able to "Refresh" the contents of the Browse Data tab and it should show changes, even those made externally.
> 
> Have you tried the Refresh approach? 😄

"Refresh" in the Browse Data tab works just fine. What I'm asking for is "Refresh" for the SQL files in the Execute SQL tab.

**Comment by MKleusberg** [comment]
I have just added the most basic of all possible implementations. There is still no reload button but a message box pops up whenever the file is changed. It also still needs an ```Always Ignore``` button or similar to silence it.

**Comment by SilvioGrosso** [comment]
Hello @MKleusberg 

Just tested today's build (DB.Browser.for.SQLite-win64.ZIP) on Windows 10
Everything works as expected: whenever I save my file.sql a new box appears and I am asked whether I wisht to reload my sql code into db browser.

THANKS a lot indeed since this option is extremely useful!

**Comment by amaurand** [comment]
Thanks, @MKleusberg !

I have been testing it on my Windows 10 machine as well and it's working just as described.

Currently, if the dialog is open, and the file is modified again, we get another dialog. I think that no additional dialog should appear if one already exists.

In addition to `Always Ignore`, I would love for there to be a way to configure it to update silently if the file has not been modified in DB Browser for Sqlite since the last reload (there are no unsaved changes to be lost by a reload).

**Comment by mgrojo** [comment]
@AlexAurand, all your last suggestions are implemented. Please, check the next nightly build and report any inconsistency.

**Comment by justinclift** [comment]
@AlexAurand Any interest in testing this, to make sure it's working the way you had in mind? :smile:

**Comment by AlexAurand** [comment]
Thanks @mgrojo ! This works almost exactly as expected.

I have a couple of notes:

1. I'm not sure answering "Yes to All" and "No to All" in response to the question "Do you want to reload it?" conveys the meaning that the application will remember the selection and apply it to future updates. Perhaps "Always reload" and "Never reload" would be clearer.
2. Sometimes (~10% of the time), when I save a file that is open in DB Browser via another application (VSCode), its tab goes blank, as though the file is empty. ![image](https://user-images.githubusercontent.com/49281806/101818710-4049b100-3af2-11eb-93ff-8ab85081ae7f.png)
3. If I select "No to All",  save the file from DB Browser, and then save the file again from another application, I get the prompt again. Is this expected behavior?

**Comment by mgrojo** [comment]
> Thanks @mgrojo ! This works almost exactly as expected.
> 
> I have a couple of notes:
> 
>     1. I'm not sure answering "Yes to All" and "No to All" in response to the question "Do you want to reload it?" conveys the meaning that the application will remember the selection and apply it to future updates. Perhaps "Always reload" and "Never reload" would be clearer? I'm open to suggestions.

Those are standard buttons that make source code cleaner and easier to program and maintain, so in principle, I'd like to keep them. Instead, we could add inline clarifications of what each button means, or a Help button linking to an explanatory page in our Wiki.

The help text could be:
> - Answer "Yes to All" to reload the file on any external update without further prompting.
> - Answer "No to All" to ignore any external update without further prompting.
> Modifying and saving the file will restore prompting.

> 
>     2. Sometimes (~10% of the time), when I save a file that is open in DB Browser via another application (VSCode), the tab goes blank, as though the file is empty. ![image](https://user-images.githubusercontent.com/49281806/101818710-4049b100-3af2-11eb-93ff-8ab85081ae7f.png)

Is that on Windows? In Linux, I only noticed that some applications, namely `emacs`, can save the file in a way that is not detected by the Qt file watcher.

> 
>     3. If I select "No to All",  save the file from DB Browser, and then save the file again from another application, I get the prompt again. Is this expected behavior?

Yes, I considered that saving the file should reset to the original behaviour. I suppose that adding that to the help text should be enough to understand the behaviour.

**Comment by AlexAurand** [comment]
@mgrojo , I think that solves 1 and 3. As for 2, yes, I was seeing the blank reload on Windows, when saving the file using VSCode.
