### ISSUE TITLE
Add field does not support datetime

### ISSUE THREAD

**Issue by jvonmitchell** [sqlitebrowser/sqlitebrowser#184]
I've noticed that the types available when creating a new field in a table are limited.  Is there any goal to support datetime?

**Comment by ircer** [comment]
SQLite does not have a storage class set aside for storing dates and/or times.

**Comment by MKleusberg** [comment]
You can just type your own datatypes into the data type field. The INTEGER/TEXT/BLOB/REAL/NUMERIC drop down box is just a list of suggestions and the text field next to the button opening it is a free-type input field.

**Comment by justinclift** [comment]
@jvonmitchell Thoughts? (wondering if we can close this :wink:)

**Comment by justinclift** [comment]
Closing this, as it's not really anything we can do something with.

**Comment by Robert-Ernst** [comment]
I had the same issue here as OP and found this zombie issue
I'm trying to revive it with the suggestion to add the supported fields of SQLite
Is there a reason not to add the suggestions to what is regularly supported by SQLite?

**Comment by justinclift** [comment]
That's a bit confusing @Robert-Ernst, as *in theory* we already support the data type SQLite supports + we also let people enter their own names.

What are you trying, that's going wrong? :smile:

**Comment by scottfurry** [comment]
@justinclift - I just had a look. Datetime type isn't listed. Odd.

**Comment by chrisjlocke** [comment]
It's not a zombie issue. Sqlite does not support the datetime data type. You can enter it, but it doesn't affect anything. 
It wouldn't be in the list as it's not a supported type.

The four supported (as mentioned above) are also listed here.
https://www.sqlite.org/datatype3.html

You're free to enter your own like 'cabbages'. It'll remember it for that database, and be populated in that list.

**Comment by scottfurry** [comment]
TIL... It's all about the functions. https://www.sqlite.org/datatype3.html#datetime
