### ISSUE TITLE
Adding sqlite3_analyzer features (also in Cipher)

### ISSUE THREAD

**Issue by Incuboazaz** [sqlitebrowser/sqlitebrowser#1840]
Describe the new feature
--------------------------
Adding a way to analyze tables, size etc.

Thanks for a great product.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Not that I'm aware of.

**Comment by justinclift** [comment]
Hmmm, are you meaning something like the [`SQLITE_ENABLE_STAT4`](https://sqlite.org/compile.html#enable_stat4) compile time option?

If so... it should (in theory) already be in the most recent release (3.11.2) builds.  At least for the windows ones (just checked).

I *think* that's also be enabled in the macOS one, but I can't easily check at the moment.

If you're meaning something else entirely though, please provide detail so we can think it through. :smile:

**Comment by justinclift** [comment]
@Incuboazaz ping?

**Comment by justinclift** [comment]
Just checked our automatic nightly macOS builds.  They include the [`SQLITE_ENABLE_STAT4`](https://sqlite.org/compile.html#enable_stat4) compile time option as well. :smile:

**Comment by Incuboazaz** [comment]
Hi, thanks for the quick response and sorry for my late one.
I think this is what I meant, I'll check it out.
Thanks again

**Comment by justinclift** [comment]
No worries.  If that extension isn't providing what you're after, let us know. :smile:

**Comment by Incuboazaz** [comment]
Hi @justinclift,
Thanks for being patient with me. I'm also quite new to this, I might be totally off point, so forgive me.
What I'm looking for is a way to analyze an existing db (as in https://www.sqlite.org/sqlanalyze.html).
Problem is, this sqlite3_analyzer doesn't work with encrypted db's, and I think it would be great to have it in app (I haven't found a way to run the analyzer with an encrypted db).

Thanks!

**Comment by justinclift** [comment]
Interesting idea.  I'm brain fried atm (staring at computer too long today :wink:), but one reasonable idea comes to mind: the SQLCipher people would probably know how to get it done.

Definitely recommend asking on their forums:

&nbsp; &nbsp; https://discuss.zetetic.net/c/sqlcipher

They're fairly responsive too, depending on what else is happening in their day. :smile:

**Comment by Incuboazaz** [comment]
Thanks!

**Comment by evbo** [comment]
@justinclift I'm not quite following sorry, is there a way to run sqlite_analyzer from sqlitebrowser? I thought sqlite_analyzer was a perl script you are supposed to run separately from the command line?

It would be awesome if sqlitebrowser run it from inside the GUI and with cool visualization and what not :)
