### ISSUE TITLE
Browser crashing on opening network DB file

### ISSUE THREAD

**Issue by msd-rjoachim** [sqlitebrowser/sqlitebrowser#1844]
Details for the issue
--------------------

#### What did you do?
File -> Open Database (browse to database file via UNC path)
File -> (choose recent database file - previously loaded via UNC path)
Toolbar -> Open Database (browse to UNC path)

#### What did you expect to see?
Database file open.

#### What did you see instead?
Selected database file, then application closes without error or warning. Initial time from choosing file to application closing is approximately 2-3 seconds.
Re-opening the application and trying again often resolves the issue for that instance, but the problem is intermittent (though frequent).

Possibly related - bottom-right (between previous/next buttons) is currently showing a "determining row count..." message, even though there is no database currently open.

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Error information from Event logs:**

Faulting application name: DB Browser for SQLite.exe, version: 3.11.2.0, time stamp: 0x5ca4b173
Faulting module name: sqlite3.dll, version: 0.0.0.0, time stamp: 0x5ca4aee3
Exception code: 0xc0000006
Fault offset: 0x000000000012b9de
Faulting process id: 0x2658
Faulting application start time: 0x01d4ee59046a7e79
Faulting application path: C:\Program Files\DB Browser for SQLite\DB Browser for SQLite.exe
Faulting module path: C:\Program Files\DB Browser for SQLite\sqlite3.dll
Report Id: cc0a0b5d-24cd-4d8a-80fa-162c3b76283a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by justinclift** [comment]
Thanks @msd-rjoachim.

It's interesting it's saying the faulting module name is sqlite3.dll.  That sounds like SQLite itself (which we embed) is hitting some problem and outright aborting without nicely handling it.

Are you ok to try the SQLite command line shell (probably from [here](https://www.sqlite.org/2019/sqlite-tools-win32-x86-3270200.zip)), and see if that opens the database over UNC path reliably?

If it does, it could be something simple like us not proving a UNC path information to the SQLite database correctly (somehow).

If it doesn't though, this is probably something the SQLite developers will need to figure out.  Maybe. (unsure) :wink:

**Comment by chrisjlocke** [comment]
Just a couple of other questions.  Does it happen to all databases?  So if you create a new database with one table and one field and store it in the same location as the other database, does that also fail, or does that open OK?

Any chance of copying the database locally?  Does it open from your desktop OK?

I open a database across UNC and don't encounter any problems, but databases can be so complex, it could be specific to that one file...

It should have no bearing, but its a good test - if you're using the 64bit version, can you try the 32bit version, and vice versa.  

Have you used a previous version of DB4S with no issues?  It might be worth trying a couple of nightly versions, which have different versions of SQLite in them.  I can point you to various downloads if you have the time to experiment.

One last thing.  Is it a top secret database?  Could you keep the schema but delete the data from it (from a copy, obviously!) and again, see if the error occurs.  If it does, then you could send us that data-less database so we could test further.

**Comment by msd-rjoachim** [comment]
Hello there,

Sorry for the delayed response. Work schedule + a sick day does not help productivity.
I just got back today and I've only had time to test a couple different scenarios - 

- I verified that the program still crashed when trying to access the DB from the UNC path, then copied that DB locally and tried opening it (then closing/opening several times), which didn't crash at all.

- I then recreated the DB with schema only (great suggestion) and moved it to the network share. The Browser does not appear to have any issues with opening it. 
It would seem the problem is specifically related to the data itself, but only when access from a network share.

While most of the data in the DB is not really secret, there is a lot of identifiable information from my users, so I wouldn't be able to share it.
This is my first time using DB Browser (loving it, by the way), so I don't have any indication whether previous versions had similar issues.

**Comment by chrisjlocke** [comment]
OK, so the next thing to try is to work out 'is it the quantity of the data' or 'is it the quality of the data'.
How many records in your crashing database?  How big is the file?  Can you recreate that using garbage data (so 'AAAAAAAA' for a name, '2000-01-01' for a date of birth, etc)
So you now have a 'sanitised' database - does that work ok?
If so, it must be some data in your database that is poor, which is bizarre - DB4S doesn't normally care, unless its really long field contents in some fields (DB4S used to cough at 30,000+ characters in numerous fields, but this has since been fixed).  This would take more experimentation.  Essentially, delete (preferably move) blocks of data from one database to another, until one database doesn't open and then the other one does.  But that could take ages.....   no-one got time for that ....
Guess you could delete wodges of data from tables until it works, then slowly pinpoint more granually which table/block of data helps.  Again, could take a while, until you found it was one record holding some wacky control codes or something.......

**Comment by mtissington** [comment]
Just a thought - what permissions do you have to the UNC?
How much space is available?

**Comment by msd-rjoachim** [comment]
Sorry for the delay, again. 

I have full read/write on the UNC path (Domain Admin in an AD environment). 
Available disk space is not an issue.
Field contents can be lengthy, but certainly not in excess of 10's of thousands of characters.
Field contents can be a mixture of all sorts of data types (it is data pulled from Windows devices via WMI mostly) for use in an inventory system. 
I realized recently that the database is being written to actively while I was attempting to work with it - it may be this was part of the problem.

This is likely just a one-off scenario specific to this database + the environment I'm working in, so I'm willing to consider this a non-issue overall. The program itself works very well, regardless of the occasional crashes discussed here.

Thanks to you all for your responses.

**Comment by justinclift** [comment]
No worries.  It's definitely a weird one. :smile:
