### ISSUE TITLE
on refreshing the page it does not show updated data

### ISSUE THREAD

**Issue by Nityanand2020** [sqlitebrowser/sqlitebrowser#1847]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
Hi @Nityanand2020, which part of the program is this happening in?  eg the "Browse Data" tab, or the "Execute SQL" tab, or something else? :smile:

**Comment by chrisjlocke** [comment]
...and why didn't you fill out the details of the issue?  Simply leaving a title isn't overly helpful.
How are you 'updating' the 'data' - in DB4S, or in another program?
If in another program, are you using transactions?  
Is the database local or on a network?

**Comment by mgrojo** [comment]
Closing due to lack of response.
