### ISSUE TITLE
Arch Linux: Unable to install via official repo.

### ISSUE THREAD

**Issue by Davetheraveuk** [sqlitebrowser/sqlitebrowser#1850]
Hi,
I have tried installing this via the official RebornOS (Arch-based linux distro) and I receive the following error:

```
Preparing...
Warning: gksu: local (2.0.2-7) is newer than Reborn-OS (0.0.r99.c2c828f-1)
Resolving dependencies...
Checking inter-conflicts...
Checking integrity...
Downloading sqlitebrowser (3.11.1-1-x86_64)...
Checking keyring...
Checking integrity...
Error: sqlitebrowser: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is invalid
Failed to commit transaction:
invalid or corrupted package (PGP signature):

```
Help!
Thanks.
Dave.

**Comment by justinclift** [comment]
Guessing here, but it kind of sounds like the downloaded file itself isn't good.

eg either the download broke during the file transfer (rare, but can happen), or the signature Levente Polyak created is something mismatching things.

Probably best to try downloading it again (eg maybe run the arch command again?), and see if that fixes things.  I'm not sure how Arch does metadata, so it *might* be a case of needing to clear out a broken download from cache first before it'll work.

If the problem isn't a broken download, but is instead the signature... then emailing Levente Polyak (via the address on the same line) is probably the best approach. :smile:

**Comment by Davetheraveuk** [comment]
@justinclift 
Hey - I did what you said: clearing the /tmp directory and installing via the Terminal instead of the "Add/Remove" GUI.

It worked.
Thanks.
Dave

**Comment by justinclift** [comment]
Excellent, good stuff @Davetheraveuk. :smile:
