### ISSUE TITLE
Export to csv and import from csv

### ISSUE THREAD

**Issue by Edimarpcosta** [sqlitebrowser/sqlitebrowser#1851]
Feature to export results to csv and import csv to a new table.
--------------------------
This feature exists in "SQLite Expert Professional 5".
![Features Screenshoot ](https://user-images.githubusercontent.com/20747256/56396662-481a5a80-6216-11e9-8911-d2397a7becb5.png)

**Comment by justinclift** [comment]
We already have import and export (to/from CSV), available from the File menu.

Guessing you just missed it? :smile:

**Comment by chrisjlocke** [comment]
@Edimarpcosta - what version of DB Browser for SQLite are you using?
If you click 'Help' and 'About', it'll pop up a little window showing the version information.

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
@Edimarpcosta - feel free to comment back if you need further assistance.
