### ISSUE TITLE
Database Is locked

### ISSUE THREAD

**Issue by IoTFier** [sqlitebrowser/sqlitebrowser#1854]
Details for the issue
--------------------

#### What did you do?
Create a set a database in DB4S v3.11.2
I have been working on my database design from last 24 hours.

Connected to the generated database in VS 2019 using an extension SQLite /SqlServer Compact Toolbox. Browsed table structure. Closed the connection to the database.

Then in DB4S tried to edit a table and have been unsuccessful in committing my changes.

#### What did you expect to see?
Expecting the DB changes to be updating as it was in last few hours since I started using DB4S

#### What did you see instead?
![image](https://user-images.githubusercontent.com/26844611/56471898-656d4580-641d-11e9-9425-ea8d84c9b4f6.png)

When tried to execute the release statement … get following not found response
![image](https://user-images.githubusercontent.com/26844611/56471980-79fe0d80-641e-11e9-8967-60080492ab77.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_10 64 bit ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds ===> Didn't feel it was required as it was working fine for last many hours...
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by IoTFier** [comment]
Restarting my PC resolved the lock. But, I don't prefer this as the work around.
Your guidance to handle is in a much better way will be appreciated.

**Comment by chrisjlocke** [comment]
The database was open in another connection.  While DB4S could handle it better, there isn't much it can do.  I use VS 2019, but not directly to open the database.  I use it to write VB .NET applications.  If one of these applications crashes, sometimes VS can leave some files open.  Closing VS completely usually resolves it - there shouldn't be a need to reboot the whole PC.

You can usually tell if the database is still 'locked' by the presence of a journal file.  Its not easy to determine what application 'owns' that journal file, as its SQLite technically.

**Comment by p-nicolaou** [comment]
I will leave my comment here for others who are facing the same issue. @chrisjlocke helped me figure out what was causing this error. I had Android Studio (and Android emulator) running while modifying Table's columns. I had to simply quit Android Studio and emulator, close/open db in DB Browser and tada! After that, back to AS, I increased db's version number and all good. Thank you.

**Comment by justinclift** [comment]
Awesome, glad it worked out @p-nicolaou. :smile:

Good stuff @chrisjlocke!
