### ISSUE TITLE
there was no full support for window function statements such as GROUPS and RANGE?

### ISSUE THREAD

**Issue by mlldev** [sqlitebrowser/sqlitebrowser#1856]
When testing a window function statement with GROUPS and RANGE ,I got a hint of syntax error.

Example from https://www.sqlite.org/windowfunctions.html#biwinfunc:
SELECT c, a, b,
  group_concat(b, '.') OVER (
    ORDER BY c GROUPS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE NO OTHERS
  ) AS no_others,
  group_concat(b, '.') OVER (
    ORDER BY c GROUPS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE CURRENT ROW
  ) AS current_row,
  group_concat(b, '.') OVER (
    ORDER BY c GROUPS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE GROUP
  ) AS grp,
  group_concat(b, '.') OVER (
    ORDER BY c GROUPS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE TIES
  ) AS ties
FROM t1 ORDER BY c, a;
===============>
Result: near "GROUPS": syntax error
At line 1:
SELECT c, a, b,
  group_concat(b, '.') OVER (
    ORDER BY c GROUPS

-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 8.1 (6.3) (winnt/6.3.9600) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
Thanks @mlldev, that sounds like a parser bug of some sort. :smile:

**Comment by MKleusberg** [comment]
I think this is more likely to be a problem with the version of SQLite we bundle. Window functions were significantly enhanced in SQLite 3.28.0, including [support for GROUPS frames](https://sqlite.org/releaselog/3_28_0.html). However, in the issue message it mentions SQLite 3.27.2 for which all of this must look like a syntax error :smile: Also we only parse ```CREATE``` statements. ```SELECT``` statements are just handed over to SQLite without further looking at them.

@justinclift Do you know if we need to publish a new release which includes 3.28.0 or if it is possible to just drop-in replace the SQLite DLL?

**Comment by justinclift** [comment]
> @justinclift Do you know if we need to publish a new release which includes 3.28.0 or if it is possible to just drop-in replace the SQLite DLL?

Not sure.  Our nightly Windows builds for the last few days have all included 3.28.0, which is probably the thing to try instead then. :smile:

**Comment by SilvioGrosso** [comment]
Hello guys!

Just downloaded todays' windows build (DB.Browser.for.SQLite-win32.ZIP) and unzipped it on Windows 10.
SQLite version is 3.28.0
Everything works fine!

I have followed this tutorial regarding PostgreSQL:
http://www.postgresqltutorial.com/postgresql-window-function/

With Db Browser for Sqlite, every example of this tutorial, as regards the window functions,  works fine: more precisely, all results concerning the query are similar!

Here is some SQL code as regards this tutorial.
The first window function is tested at the very end of the code below (all the others window functions work fine as well):

CREATE TABLE product_groups (
group_id INTEGER PRIMARY KEY,
GROUP_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE products (
product_id integer primary key,
product_name varchar(255) not null,
price real,
group_id integer not null,
foreign key (group_id) REFERENCES product_groups (group_id)
);

INSERT INTO product_groups VALUES
(1, 'Smartphone'),
(2, 'Laptop'),
(3, 'Tablet');

INSERT INTO products (product_id, product_name, group_id,price) VALUES
(1, 'Microsoft Lumia', 1, 200), 
(2, 'HTC One', 1, 400), 
(3, 'Nexus', 1, 500), 
(4, 'iPhone', 1, 900), 
(5, 'HP Elite', 2, 1200), 
(6, 'Lenovo Thinkpad', 2, 700), 
(7, 'Sony VAIO', 2, 700), 
(8, 'Dell Vostro', 2, 800), 
(9, 'iPad', 3, 700), 
(10, 'Kindle Fire', 3, 150), 
(11, 'Samsung Galaxy Tab', 3, 200); 

SELECT 
product_name, 
price, 
group_name, 
AVG (price) OVER (PARTITION BY group_name) 
FROM 
products 
INNER JOIN product_groups USING (group_id);

**Comment by mlldev** [comment]
@justinclift  I downloaded the  win64 version build and tried examples before,it's ok now!

**Comment by justinclift** [comment]
Awesome!

Good advice @MKleusberg, and thanks for checking @SilvioGrosso, @mlldev. :smile:
