### ISSUE TITLE
shared cache 

### ISSUE THREAD

**Issue by marienuac** [sqlitebrowser/sqlitebrowser#1858]
Describe the new feature
--------------------------
SQLITE_OPEN_SHAREDCACHE

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
SQLITE_OPEN_SHAREDCACHE

#### Does this feature exist in another product or project? Please provide a link.
SQLITE_OPEN_SHAREDCACHE

#### Do you have a screenshot? Please add screenshots to help explain your idea.
SQLITE_OPEN_SHAREDCACHE

**Comment by justinclift** [comment]
Looking here for more information: https://www.sqlite.org/sharedcache.html

I'm not understanding how this would be useful.

@marienuac What is a good example, where this will be useful for you? :smile:

**Comment by chrisjlocke** [comment]
Splatting 'SQLITE_OPEN_SHAREDCACHE' into every field of the support ticket doesn't help your case, as well as the suspicious "marienuac has no previous activity."
Can't see this being a fruitful conversation.

**Comment by justinclift** [comment]
Yeah, it's been a week without any response.  Closing this ticket. :man_shrugging:
