### ISSUE TITLE
Documentation - to explain "Write changes" and "Revert changes" buttons

### ISSUE THREAD

**Issue by tenbob** [sqlitebrowser/sqlitebrowser#1859]
I searched the documentation, but I can't find any explanation of the "Write changes" and "Revert changes" buttons. 

It's confusing for a new user that changes are not fully saved until you click "Write changes". The documentation should point this out and give a description of the underlying mechanism.

I still can't understand what is going on. Does the program issue a BEGIN or a SAVEPOINT command? I can't see anything like this in the 'SQL log' window. If it does, how will this interact with any similar commands that I might issue in the 'Execute SQL' window? What type of transaction is it - DEFERRED, IMMEDIATE, EXCLUSIVE? All changes seem to be visible immediately in DB4S even if they have not been written to the database. How does that work?

I'd be grateful if someone could explain it here first. Later it could go in the user documentation. Thanks.

**Comment by justinclift** [comment]
> It's confusing for a new user that changes are not fully saved until you click "Write changes".

Hmmm, where are you seeing that not commit everything? :smile:

Pretty sure that should work, and if it doesn't it'll be a bug. :scream:

**Comment by tenbob** [comment]
@justinclift. Hi. I was seeking clarification, not reporting a bug. Can you please help me by describing how it works.

**Comment by sky5walk** [comment]
Look to the SQL log to see what your changes are doing.
When DB4S detects changes to the database it flips a 'dirty' bit that triggers the gui of the 'Write changes' button.
There are several bugs reported where DB4S misinterprets changes to the database and sets the 'dirty' bit.
An example was recursive queries.

**Comment by tenbob** [comment]
It seems nobody has yet answered my original question. I can't understand what happens with "Write changes" and "Revert changes". Can someone please explain HOW IT WORKS. 

Does DB4S create a temporary copy of the user's sqlite file and carry out all the work on that? If so, where is it located? And what are the storage implications. 

Or does DB4S use some fancy SQL journalling or rollback system?

The suggestion from @sky5walk doesn't really help. There is nothing in the SQL log that relates to this. 

All I can see is that the date on my sqlite file doesn't change until I hit "Write changes". So where is the data actually being stored?

**Comment by scottfurry** [comment]
@tenbob - if I have things understood properly, database is worked on in memory but this is dependent on settings. SQLite opens the file name passed to it (with the open database command). When given the command(write change command or confirm save on exit) those changes are written from memory to file. There is not a file association for that in-memory location. You may also see another file at the same location as the database file but with a different extension. That would be the transaction settings are saved before commits. Again, dependent on `#pragma` settings for the database, I believe. I have to dig into some searches to be sure of all of the above, but I believe this is the outline of what you're trying to understand.

**Comment by tenbob** [comment]
@scottfurry Thanks. This is exactly what I'm interested in. I'd be grateful for any further info you find after digging.

As you say, it's likely that all the work is done on an in-memory copy of the database. There are no  temporary sqlite files that I can find. But what are the implications on performance? And how will it work with huge databases that won't fit into memory? 

This is a fundamental feature DB4S that needs to be explained properly in the documentation. Most other DB management programs write immediately to the sqlite file.

**Comment by mgrojo** [comment]
@tenbob DB4S is using savepoints to allow the "Write Changes" (RELEASE) and "Revert  Changes" (ROLLBACK). The implementation details about use of memory and/or disk are abstracted by SQLite.

See https://www.sqlite.org/lang_savepoint.html

Transactions entered through the Execute SQL editor are discarded.

The savepoints statements run by the application are being explicitly hidden for the SQL Log. I don't see a reason why, and I think they should be logged, since they are relevant. Only internal get-like statements issued by the application should be hidden in order to not clutter the log. I might make a pull-request to change that.

**Comment by mgrojo** [comment]
@tenbob With PR #1902 (issue #1901) the Application SQL log will show the statements associated with the "Write changes" and "Revert changes" buttons. You can give it a try in the next nightly build. Do you feel that this issue is already addressed and can be closed?

**Comment by tenbob** [comment]
Thanks @mgrojo. I tried the nightly build V3.11.99 and it seems to be working. I can now see the SAVEPOINT, RELEASE and ROLLBACK commands in the Application log. But I'm not sure if they are in the correct sequence. When I update a row I see the UPDATE first and the SAVEPOINT afterwards.

My original post was mainly about documentation. So I have added an extra page to the wiki [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Transactions ) to explain how DB4S uses transactions. Could someone please check it and make any necessary improvements, since I am no expert.

**Comment by mgrojo** [comment]
@tenbob Thanks for the wiki entry. Sorry about the delay, but the problem of the inversion in UPDATE and SAVEPOINT statements should be fixed now. Could you confirm everything is now fine in  tomorrow's nightly build?

**Comment by justinclift** [comment]
@tenbob Any interest in trying this out, to see if it's fully fixed?

**Comment by tenbob** [comment]
Hi @justinclift. Thanks for making this change. I tested it with V3.12.99 from 6 July 2020 and it's working fine. Bob

**Comment by justinclift** [comment]
Awesome, thanks for testing it @tenbob. :smile:

@mgrojo Looks like that did the trick, well done. :smile:
