### ISSUE TITLE
save SQL query bug report

### ISSUE THREAD

**Issue by vassileiosdermentzis** [sqlitebrowser/sqlitebrowser#186]
I use SQLiteBrowser in Windows Vista

1. I clicked in saveSQL file in execute SQL tab
2. In select file name window I press Save button and browses all folders (browse/hide folders option) instead of saving.
3. When it browses, I press again Save and nothing happens

**Comment by Z4us** [comment]
You have a SQL-statement correctly executed in the screen?
If so then click save-SQL-icon, type a filename
then save

**Comment by justinclift** [comment]
@vassileiosdermentzis Did you get this figured out?

**Comment by vassileiosdermentzis** [comment]
No i didn't I am still getting this bug
Στις 15 Φεβ 2015 9:46 μ.μ., ο χρήστης "Justin Clift" <
notifications@github.com> έγραψε:

**Comment by justinclift** [comment]
Ok, I will try to help. :smile:

For me, using our 3.5.1 release, I can go to the 'Execute SQL' tab and type in a query.  Like this:
![screenshot1](https://cloud.githubusercontent.com/assets/406299/6206041/4dc9c956-b578-11e4-9850-93a3b069c244.png)
It opens up a file dialog, so I can choose a location to save the file.  I give it a filename ('myquery.sql'), then click 'Save'.  Like this:
![screenshot2](https://cloud.githubusercontent.com/assets/406299/6206069/1d7f1b74-b579-11e4-9ccf-721a50c478e9.png)
That creates a text file - myquery.sql - with the SQL query in it.  Opening that in a text editor shows this:
![screenshot3](https://cloud.githubusercontent.com/assets/406299/6206096/0414dc54-b57a-11e4-80d2-26ce925865b5.png)
Is this what you are doing, and it isn't working?

**Comment by justinclift** [comment]
@vassileiosdermentzis ping... :smile:

**Comment by justinclift** [comment]
@vassileiosdermentzis How did you go with this?

**Comment by vassileiosdermentzis** [comment]
Hello,

I don't think I solved it. Actually I quit being à programmer And I don't
think I am dealing with this anymore. But thank you for your interset
anyway

**Comment by justinclift** [comment]
Sure, not a problem @vassileiosdermentzis. :smile:
