### ISSUE TITLE
ToDo: Test gzip/deflate compression support in DB4S DBHub.io connector :)

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1862]
[This is more a reminder to myself so I don't forget, as I'm focused on a very different area - visualisations support - atm]

It would be useful to see if the DBHub.io connection code (https) in DB4S transparently supports gzip and/or deflate compression already.

[Enabled it](https://github.com/sqlitebrowser/dbhub.io/commit/a2690e7ec9f1092c3c4e3b29894f9129c660ec7b) for the main DBHub.io website a few days ago, and it significantly increases throughput with some databases.

eg this ~3GB one downloads at ~18MB/s now, instead of ~5MB/s (max through of the land line here)

&nbsp; &nbsp; https://dbhub.io/justinclift/backblaze-drive_stats.db

Obviously that'll vary with the content of any given database, but it was a welcome surprise. :smile:

**Comment by MKleusberg** [comment]
Just gave this a quick try using DB4S and this:
```
cd /path/to/db4s/repo/src/certs
curl -vv --cert public.cert.pem --cacert ca-chain-development.crt -H "Accept-Encoding: gzip" 'https://db4s.dbhub.io:5550/justinclift/530mb.sqlite' --output download.db
```

And it doesn't seem to work:
```
...
> GET /justinclift/530mb.sqlite HTTP/1.1
> Host: db4s.dbhub.io:5550
> User-Agent: curl/7.65.1
> Accept: */*
> Accept-Encoding: gzip
> 
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Branch: master
< Commit-Id: 4ad28555a3a237de69f2c50df0b335a3ec952b0f93d9deb8b5a003c65a27b11a
< Content-Disposition: attachment; filename="530mb.sqlite"; modification-date="2017-08-17T22:50:09Z";
< Content-Length: 540102656
< Content-Type: application/x-sqlite3
< Date: Sat, 10 Aug 2019 13:51:27 GMT
< 
```

Does this need to be separately enabled for the DB4S backend?

**Comment by justinclift** [comment]
> Does this need to be separately enabled for the DB4S backend?

Yep.  It shouldn't be very hard to do. :smile:

**Comment by MKleusberg** [comment]
@justinclift Ping :smile:

**Comment by MKleusberg** [comment]
Looks like this is working from the DB4S side of things. See https://github.com/sqlitebrowser/dbhub.io/issues/92 for further discussion.
