### ISSUE TITLE
Incorrect character displayed compared to those typed

### ISSUE THREAD

**Issue by nbl1268** [sqlitebrowser/sqlitebrowser#1863]
What is your question
-----------------------
Hi, my question is is there a means to change the character set/language that the SQLite Browser application is using? And my apology upfront if this becomes an issue rather than a question; i'm hoping that there is a simply answer (something i haven't seen in the wiki so far)

The issue i am having is that when i type characters form my keyboard into the SQLite browser fields (filters as well as execute SQL) are mostly wring. eg if i try to type '**SELECT**' i get '**1B1G1~1G1D1N**' in the field; same type of issues with numerals; eg if i try to type date '**2019 APR 28**' the result i get is '**089e71A1X1V70w**'.

![20190428 SQLite Browser keyboard character issue](https://user-images.githubusercontent.com/1731666/56862169-6852d200-69eb-11e9-8cb1-db6b23fe3c94.png)

So, some background to help.
I am running version 3.20 of this program on my raspberry pi 2.
The PI itself is running Jessi
I access the PI using RDP/XRDP.

![20190428 SQLite Browser keyboard character issue - RPi OS info](https://user-images.githubusercontent.com/1731666/56862167-5ec96a00-69eb-11e9-90c3-a12e40f5fd8f.png)

The other programs (console, text, nano, python and perl etc) all accept and show the correct characters (per those that i have typed), just SQLite Browser doesn't.  Note it didn't always do this behaviour; I have been using this version on my PI2 since mid 2016 and I would think (vague recollection) that i've had this 'wrong character' issue since maybe mid 2018.

So have tried to update but APT-GET indicates that v3.20 is the latest; thinking this might be due to OS being Jessi. Havent updated OS as i havent checked that my own code runs on later versions (something on my to do list).

Have also uninstalled (purged) the SQLite browser using apt-get and reinstalled; issue remains.

So, any thoughts? Am i missing an obvious configuration item (or like) some where that would fix this? in SQL browser or in Raspbian/Linux itself?

Regards
Neil

**Comment by justinclift** [comment]
Hey @nbl1268.

Yeah, that version of the program (3.2) is seriously ancient, as we're in the 3.11 series now.

That being said, since you mention the program itself used to work it does sound like something else is causing the problem.

Normally I'd recommend seeing if you can compile a newer version of the program yourself, as it's pretty easy to do if you have Linux experience.  I'm not sure if that would work though, as the version of Qt listed in the screenshot is also very, very old.

Hmmm... looking at the Jessie release page, it mentions the last Jessie point release was in the middle of last year:

&nbsp; &nbsp; https://www.debian.org/releases/jessie/

Wonder if something in that caused the problem?  Timeline seems to match up.

It's **probably** worth asking on the [Raspbian Forums](https://www.raspberrypi.org/forums/viewforum.php?f=66) if anyone else has seen language issues with their installation since then.

It's completely possible it's a known thing (by the Raspbian crowd), with an easy fix.  If that doesn't work out though, feel free to come back here and we can start getting creative. :smile:

**Comment by scottfurry** [comment]
Piling on from @justinclift 
One item I would add, besides old versions of software, is to check the PI's localization settings.
A quick Google search gave me [this](https://wiki.debian.org/Locale).

I've run across instances where I had missed configured locale and got weird results when typing. Locale's have to be set to "reasonable values" as other things depend on it. Some UTF8/UTF16 languages also set keyboard mappings as part of locale.

It is also possible you may be using the wrong country code. You think you have set locale for your region but that abbreviation doesn't mean what you think it means. The country/language codes are defined in an ISO standard. See [this wiki page](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) to check if you have mis-used a language code.

**Comment by nbl1268** [comment]
Hi guys,
Many thanks for the quick replies on this.
True v3.20 is ancient :) but its been a great tool.

okay thanks @scottfurry, your pointers re locale but be on to something; have only scraped the surface but there do appear to be some know issues with Debain/Raspian Jessie and locale settings, including issues with the GUI version not correctly setting/saving the configuration.

Also in related threads is dialogue re issues where the local keyboard type is not correctly set for remote RDP services. So will follow that a bit more and see where i end up. 

Thanks again for the quick replies and pointers. 
Regards
Neil

**Comment by scottfurry** [comment]
@nbl1268 - Google gets me [this](https://www.raspberrypi.org/documentation/configuration/raspi-config.md). I had played with raspi-config before. Been awhile for me...
Good Luck.

**Comment by justinclift** [comment]
No worries @nbl1268, let us know how it goes.

As a note, if we don't hear back from you in ~week or so, we'll probably close this issue.  You're welcome to come back to it and re-open it if needed though.  Am just trying to stop our open issue count from growing unbounded too much. :wink:

**Comment by nbl1268** [comment]
Hi @scottfurry and @justinclift, thanks for the help. Much appreciated. Happy for you to close this issue; from what you helped with so far, and what i've found since found re Jessie and RDP keyboard mappings issues, i am more than certain the issue is not with this application. 
[https://www.raspberrypi.org/forums/viewtopic.php?t=122490](url)
[https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=175662](url)

BUT i will post something once i've got to the bottom of this :). 
Regards 
Neil

**Comment by justinclift** [comment]
Excellent. :smile:
