### ISSUE TITLE
Apparent Error Message on Command Line when Opening Database File

### ISSUE THREAD

**Issue by scottfurry** [sqlitebrowser/sqlitebrowser#1867]
#### What did you do?
Program called from command line.
Selected "Open Database" either via menu command or clicking toolbar button.
Unexpected Message printed :

"Empty filename passed to function"

Unexpected message produced again if user cancels out of database open dialog.

#### What did you expect to see?
No warning message

Useful extra information
-------------------------
Documenting found behaviour.
Intent is to track down function producing this call.
An error message of this type should not appear during normal usage.

#### What operating system are you using?
- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro: Funtoo LTS )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: git HEAD a1b43bca

#### Did you also
- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Looking at 'mainWindow.cpp' (around line 551) is the routine for file opening.  I can't program in C++, but looking at it, there are a number of "if(QFile::exists(wFile) )" lines - before and after the dialog is called.  If the user clicks cancel, then I assume wFile is nothing, so the exists routine doesn't like it ... but obviously 'fails' it, which the routine 'expects' (if that makes sense).

So, its a kludgy way of doing it, which while it works, is 'noisy' on the error front.

**Comment by scottfurry** [comment]
I'm hopeful that "walking the call stack" should sort out the offending behaviour. ;-)

**Comment by MKleusberg** [comment]
I'll close this issue now that we have #1875 merged. Thanks again, @scottfurry :smile:
