### ISSUE TITLE
Inserted rows are blank before refreshing

### ISSUE THREAD

**Issue by cristilupascu** [sqlitebrowser/sqlitebrowser#1870]
Details for the issue
--------------------

#### What did you do?
In the "Browse Data" tab, clicked "Insert record" button.

#### What did you expect to see?
The fields that have default values should display their default values.

#### What did you see instead?
All fields in the inserted row are completely empty.

I am pretty sure it used to work like I expect it to. Now, the fields display their value only after refreshing. Below is an image of how it looks when inserting. I expect a newly inserted row to look like the first one, with id filled in, q and date_added filled in since they are default values and all the NULLs showing.

![alt text](https://i.ibb.co/fdzdkFr/Cap00105.png "Bug example")

Useful extra information
-------------------------
> DB4S v3.11.99 (May  2 2019) [built for x86_64-little_endian-llp64] on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.28.0
> and Qt 5.11.3

**Comment by justinclift** [comment]
Hmmm, not sure about this one.  For some default values, figuring it out without doing an actual insert wouldn't be hard.  eg a default value of "3".  Fixed values like those could probably be done.

Default values though can be made very complex, with functions needing to be run which depend on other data. (etc)  Those sort of default values probably shouldn't be automatically done, as they're best to be calculated when the row is inserted into the table.

Thoughts? :smile:

**Comment by cristilupascu** [comment]
Here is how it looks like on the release version 3.11.2.
![alt text](https://i.ibb.co/ygLkHSY/Cap00106.png )

The last two rows have their values filled in even though I didn't hit refresh after inserting.
I thought for sure this is a bug, unless it was changed on purpose...

**Comment by justinclift** [comment]
Interesting.  That does sound like things have changed then, so I guess I'm wrong. :smile:

**Comment by tenbob** [comment]
The same problem occurs with columns that are primary keys. When you insert a new row the UPDATE statement tries to write a NULL into every column. SQLite ignores the NULL and writes the appropriate primary key value instead. But you don't see that in the browser. You just see a blank in every column until you refresh the whole thing.

This should be easy to fix. Continue to use NULL values in the UPDATE statement. Then read back the row you just added before you display it. It should then have the correct values.

**Comment by MKleusberg** [comment]
Thanks for reporting this, @cristilupascu. I just stumbled upon the same issue by accident. Sorry I didn't see your issue earlier! The problem should be fixed now, however. Are you ok to check again using tomorrow's nightly build and see if it's working again for you as well now? :smile:

**Comment by cristilupascu** [comment]
Thank you for addressing this issue. I've been using the release version since I found this issue. I'm hoping to finally switch back to a nightly version with this solved.

I will gladly check once the latest nightly build for Windows gets uploaded. But at the moment the latest version seems to be from 17-Sep-2019 00:23.

**Comment by cristilupascu** [comment]
I've checked it and it appears to work. Thanks, @MKleusberg, for solving this. I can finally go back to using the nightly version now.

**Comment by MKleusberg** [comment]
Awesome :smile: Thanks for testing!
