### ISSUE TITLE
Suggestions for default content for the "Remote" panel?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1877]
In the last few days we've added a "public" certificate to DB4S nightly builds, so people can view (read only) public databases on DBHub.io without needing to go through the hassle of creating an account.

At the moment, the "Remote" tab just shows a raw list of public databases.  Although ok as a first step content placeholder, it's not really all that useful. :wink:

Instead, we should probably display something useful in that Remote panel.  But what? :smile:

Something like this seems like it might be right kind of direction:

![Remote Panel - Default content](https://user-images.githubusercontent.com/406299/57197073-3bcc2680-6fa6-11e9-88c8-74384920ba78.png)
Balsamiq Mockups source [here](https://github.com/sqlitebrowser/dbhub-mockups/blob/b6995bc711dfb8067f97aa6449caa3539f3a47d1/Remote%20Panel.bmpr).

The first entry there might be hard to figure out initially, until seeing what people seem to grab.  So maybe just the ones with the drop down options?

Different ideas are welcome too.  Really just spit balling here to figure out useful avenues to explore. :smile:

**Comment by justinclift** [comment]
@remram44 Do you reckon having the SW Carpentry related databases directly fetch-able in the GUI would be useful for people?

@bmcbride @zhm Same thing, but for GeoPackages. :smile:

The lists of which ones exactly to grab would likely be dynamic, with the listing created server side and updated "somehow".

Haven't really thought through the "somehow" bit yet.  Probably starting out with some curated/whitelisted approach, to get a feel for things?

**Comment by MKleusberg** [comment]
Closing this as issue #2297 is about the same question.
