### ISSUE TITLE
DB Browser (SQLite) crashes when creating new database

### ISSUE THREAD

**Issue by chameleon07** [sqlitebrowser/sqlitebrowser#1878]
#### What did you do?
I opened DB Browser (SQLite) and clicked 'New Database'.
The issue is similar to #1460 so I uninstalled the version for 64 and installed the version for 32 instead. It works but I tried reinstalling 64 again and that won't work.

#### What did you expect to see?
For it not to exit immediately for no reason. 

#### What did you see instead?
When I clicked 'New Database' it showed window where to create a database but then within a second the who program just exited on its own without any warning or error message.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( version: 64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @chameleon07.  Yeah, it's rare, but some people do seem to have Windows computers which load an incorrect .dll for some unknown reason.

If the 32-bit version of the program is working for you well enough, just keep on using that. :smile:

It **should** be possible to figure out what is going wrong with the 64-bit version, but it's likely to take a lot of time.  Possibly several hours - spread across several days - of downloading things, trying things out, taking screenshots, etc.

Which one sounds better for you? :smile:

**Comment by chrisjlocke** [comment]
@chameleon07 - Any joy with the other version of DB4S?

**Comment by MKleusberg** [comment]
Closing this because we haven't heard back anything for a long time. If the problem still exists, please just re-open this issue any time :smile:
