### ISSUE TITLE
Maximum Number Of Columns

### ISSUE THREAD

**Issue by asanchez75** [sqlitebrowser/sqlitebrowser#188]
How can I increase the Maximum Number Of Columns?
As far I understand the limit is 2000 but I need 8000.
Thanks

**Comment by MKleusberg** [comment]
The 2000 columns limit is set by SQLite itself, so unfortunately we have no influence on that. There is a way of increasing the limit, however. You'd need to compile SQLite by yourself with the SQLITE_MAX_COLUMN setting changed to 8000 (see https://www.sqlite.org/limits.html#max_column). After that you need to compile SQLiteBrowser, too, using the modified SQLite library you just compiled. If you need any help with this feel free to post any questions here. We'd only need to know which operating system you're using. Either way, a good starting point should be these links:
https://www.sqlite.org/limits.html#max_column
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md
This would need to be done for each application using the database file.

That said, if you're only about to design a database file and not trying to open an existing one you really should consider some alternative layouts. I just can't imagine a table that should have as many as 8000 columns. Maybe an EAV model (https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model) is a better approach in your case? The only drawback is that it's not very efficient with SQL databases; but 8000-column-tables are neither :smile:

**Comment by asanchez75** [comment]
Thanks for your prompt answer. I just tried to compile and it works very well if I use Homebrew.

However, in my case I can not use Homebrew because I have to change the value SQLITE_MAX_COLUMN in the source code of sqlite before to compile and after to compile sqlitebrowser. The first compiling (sqlite was fine) but the last one (sqlitebrowser) was unsuccessful.
Then, I think the problem is because I miss some parameter when I compile the source code of sqlite. Which parameters I have to pass to compile sqlite? I am using 

./configure --prefix=/usr/local/src/sqlite3 --enable-dynamic-extensions

The last lines of error message when I compile sqlitebrowser is

ld: warning: bad symbol action: $ld$install_name$os10.7$/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices in dylib /System/Library/Frameworks//CFNetwork.framework/CFNetwork
Undefined symbols for architecture x86_64:
  "_sqlite3_enable_load_extension", referenced from:
      DBBrowserDB::open(QString const&) in sqlitedb.o
      DBBrowserDB::create(QString const&) in sqlitedb.o
  "_sqlite3_load_extension", referenced from:
      DBBrowserDB::loadExtension(QString const&) in sqlitedb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sqlitebrowser.app/Contents/MacOS/sqlitebrowser] Error 1
make[1]: *** [release] Error 2
make: *** [sub-src-make_default] Error 2

May you give a hint?

BTW, I have noticed that Homebrew uses a set parameters automatically but I do not how to use manually. Here are

==> Downloading https://sqlite.org/2015/sqlite-autoconf-3080801.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/sqlite/3.8.8.1 --enable-dynamic-extensions
==> make install
==> Downloading https://www.sqlite.org/contrib/download/extension-functions.c?get=25
######################################################################## 100.0%
==> llvm-gcc -fno-common -dynamiclib extension-functions.c -o libsqlitefunctions.dylib
==> Caveats

Thanks in advance

**Comment by justinclift** [comment]
Hmmmm, you might want to cheat.  When Homebrew downloads source code, it caches the tarball on the filesystem (for me on an OSX 10.9.5 system, it's under /Library/Caches/Homebrew).

So, you can change the parameter in that tarball + update the md5sum of the sqlite Homebrew formula to match it.  That way, if you tell Homebrew to recompile the formula it will get your updated code.

Note though... this is a very dodgy hack.  I'm not sure of a better approach though. :frowning:

**Comment by justinclift** [comment]
@asanchez75 How did this go? :smile:

**Comment by justinclift** [comment]
@asanchez75 ping?

(note - I'll close this in a day or two if no response...)

**Comment by justinclift** [comment]
Closing this as there's not really anything we can do for it.
