### ISSUE TITLE
[Feature Request-Execute SQL] Remember collapse settings of redundant Execute SQL log.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1889]
Describe the new feature
--------------------------
Remember user collapse settings of the redundant Execute SQL log.
All its information is already present in the User SQL log.
This frees up more room in the Execute SQL viewshed.

Currently, each new SQL tab recreates 3 evenly spaced gadgets.
User is forced to collapse the Execute SQL log for each new tab. 😞 

Additional info
---------------
I strongly suggest dropping the Execute SQL log altogether.
Reduce code burden as the information is already piped to the User SQL log.

#### Is your feature request related to an issue? Please include the issue number.
Issue #1670 brought me to this conclusion.

#### Does this feature exist in another product or project? Please provide a link.
NA

#### Do you have a screenshot? Please add screenshots to help explain your idea.
[within issue 1670](https://github.com/sqlitebrowser/sqlitebrowser/issues/1670#issuecomment-491076464)

**Comment by mgrojo** [comment]
@sky5walk in the next nightly build, the splitter sizes in the Execute SQL are are saved in the settings. Each time the sppliter are moved, that size is saved for the next tab to be opened. This includes the zero size (collapsed state). Please, give it a try and close this issue if everything works as expected.

**Comment by sky5walk** [comment]
Nice! Will all splitter settings be retained, or just the 1 between Execute SQL log and results?
It would be helpful to remember both.

**Comment by mgrojo** [comment]
Both will be remember: the upper one separating the editor and the table, and the lower one separating the table and the last execution results.

**Comment by sky5walk** [comment]
Close! But the code does not remember Execute SQL log completely minimized. :(
It replaces full minimize with a consistent skinny height across all open and new tabs.
Again, I would prefer dropping the entire redundant log to avoid this type of nag code support.

**Comment by mgrojo** [comment]
By "skinny height" do you mean only the handler? I supose you don't, so I cannot reproduce it in the general case. There is a way to get a default height in the lower splitter: open new tab, move splitter, close, open new one; it gets the default height. It should restore the size of the last moved splitter, but something seems to fails and the default is restored. Is it the same in you case? Maybe Qt is behaving differently due to platform or version difference.

**Comment by sky5walk** [comment]
I installed the x64 nightly on Windows 10 Pro.
The "skinny height" means the log has viewable content. No height or fully collapsed is my desire.
Side note: I cannot fully collapse the results window either.

**Comment by mgrojo** [comment]
I've fixed the stange behaviour that I was observing. I suppose it is the same issue than yours, @sky5walk  and @scottfurry. Could you confirm, please?

**Comment by sky5walk** [comment]
Is this compiled in the latest nightly?

**Comment by scottfurry** [comment]
@mgrojo - make one tweak and you might have this one cleaned up
src/SQLExecutionArea.cpp:310
```diff
- Settings::setValue("editor", "splitter2_sizes", Settings::getValue("editor", "splitter1_sizes"));
+ Settings::setValue("editor", "splitter2_sizes", Settings::getValue("editor", "splitter2_sizes"));
```
After making that change locally, the 2nd splitter area (log window) was being restored on a restart.

**Comment by mgrojo** [comment]
Oh, I see. Thanks for pointing this out, @scottfurry. It worked for a moment even after a restart. Maybe I was fooled by the value saved in the previous change, don't know. But now I see that it behaves erroneously after restart as expected by the actual bad code. In any case, it's better to save to disk only once when closing, so the last commit makes sense.

After mending that, it is working as expected as you already noted. I'll commit the fix.

**Comment by mgrojo** [comment]
@sky5walk The fix will be included in tomorrow's nightly. I think they are compiled past midnight (UTC).

**Comment by scottfurry** [comment]
@mgrojo  - that looks like it did it. Last fix works for me.

**Comment by sky5walk** [comment]
Thanks, works great 👍

**Comment by justinclift** [comment]
> The fix will be included in tomorrow's nightly. I think they are compiled past midnight (UTC).

Yep.  The mac one happens just after midnight, the Win64 one about an hour after, and the Win32 one about an hour after that.
