### ISSUE TITLE
Support for SQL Windowing

### ISSUE THREAD

**Issue by Bruno-Hanzen** [sqlitebrowser/sqlitebrowser#1893]
### Details for the issue

It seems that sqlitebrowser does not support SQL Windowing.

The following SQL statement:
"select symbol, exchange, row_number() over(partition by symbol) from downloads;"
generates the following error: "near "(": syntax error: select symbol, exchange, row_number() over("
in sqlitebrowser, while it works fine in the command line tootl (sqlite3)

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: (Ubuntu 18.04)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.2
- [ ] 3.11.1
- [x ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
From rough memory, some of the SQLite window pieces were fairly recently introduced.

Which version of the SQLite cli are you using using where it worked? :smile:

**Comment by Z4us** [comment]
In this version window functions were not yet supported. 
https://sqlite.org/syntax/window-function-invocation.html
Try the nightly build.

**Comment by justinclift** [comment]
@Z4us Yeah, similar thought but @Bruno-Hanzen is running Ubuntu 18.04.  I have a feeling the nightlies there will be using the same SQLite version as the standard release build on that platform.

That being said, I don't use Ubuntu personally so I'm not really sure. :confused:

**Comment by Bruno-Hanzen** [comment]
My version of sqlite3:
```
sqlite> select sqlite_version();
3.26.0

```

**Comment by SilvioGrosso** [comment]
Hello everyone,

On Windows 10, with the nightly builds, you get SQLite 3.28. 
With this version (3.28) the window functions are working fine. At least those implemented by the SQLite team so far.
Recently, there has been another similar bug report, which is now closed,  about this topic.
Needless to say, it was also due to not testing a Db browser version with Sqlite 3.28 shipped by default.

**Comment by Bruno-Hanzen** [comment]
How hard would it be to build the Linux version with a recent SQLite?

**Comment by chrisjlocke** [comment]
What flavour of Linux?  We have build instructions on our website.

**Comment by scottfurry** [comment]
@Bruno-Hanzen - I see your problem. The Ubuntu [downloads section on the project page](https://sqlitebrowser.org/dl/) shows a listing for a PPA but that only has version 3.11.1.

Check if you can pull in SQLite 3.28 in Unbuntu. IIRC, they're pretty good w/ keeping things up to latest revision.

**Comment by scottfurry** [comment]
Thinking through this one a little, a bunch of questions jump out at me. They boil down to one idea: Do we give the option of embedded sqlite/sqlCipher et al and the revision used to build against.

I just ran into this on my end on a Gentoo-based system where the Sqlite was not "latest-greatest". I can and have the means to fix that - for me. Other users may not have that ability/resources. This appears to be a weakness that this reporting highlights. What is the system revision of SQLite available and that, at a minimum, supported by DB4S?

Would having an embedded SQLite/SQLCipher in the `[proj root]/lib` folder with a tweaked CMakeLists.txt giving flexibility of external or system Sqlite been considered? I believe it can be done employing git submodules for dependencies.

Thoughts from group-at-large?

**Comment by justinclift** [comment]
There are nightly builds for Ubuntu a bit further down too:

&nbsp; &nbsp; https://sqlitebrowser.org/dl/#nightly-builds-1

Again, not sure what version of SQLite is in them.

Probably ironically :wink:, I don't think we've yet really thought about bundling our own SQLite version with the source, as "some version" is available just about everywhere.

That being said, it might simplify things for people building from the source for themselves.

On the other hand, does that introduce extra build time dependencies?  From memory of building SQLite from scratch on windows, there's a TCL dependency of some sort.

"Not sure".. :smile:

**Comment by Bruno-Hanzen** [comment]
Trying to add the "testing" repository:
`~$ sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser-testing`
After a long series of packages, I get:
`Lecture des listes de paquets... Fait`
`N: Le fichier configuré « main/binary-i386/Packages » ne sera pas pris en compte car le dépôt « http://dl.google.com/linux/earth/deb stable InRelease » ne prend pas en charge l'architecture « i386 »`
Which tells me something about the "main/binary-i386/Packages" and not supported i386 architecture.

**Comment by FriedrichFroebel** [comment]
@Bruno-Hanzen This does not seem to be related to `sqlitebrowser`, but to the Google Earth package. This probably occurs in your case while searching for updates. Their PPA appears to not provide i386 packages (anymore). Try to temporarily disable the Google Earth PPA and run the command(s) again.

**Comment by Bruno-Hanzen** [comment]
Looks like there has been an upgrade somewhere. I have received a new version:
- DB-Browser 3.11.99
- with sqlite 3.15.2

I'll test.

**Comment by justinclift** [comment]
> with sqlite 3.15.2

Probably won't work.  The new WINDOW stuff in SQLite came with version 3.28.0.

Looks like you'll need to build your own SQLite and DB4S after all. :confounded:

**Comment by mc51** [comment]
Installing the nightly build on Ubuntu 18.04.03 gives me this:

Version 3.11.99 (Dec 23 2019)
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

The first release of sqlite with support for window functions was 2018-09-15 (3.25.0) (see: https://www.sqlite.org/changes.html)

So sadly, no easy way to get this working :(

**Comment by mgrojo** [comment]
@mc51 Our Ubuntu nightly seems to have been using the SQLCipher version, which is based on an earlier version of SQLite. The Windows version provides both compilations. I've run the Windows nightly without problems using the zip archive version  under Ubuntu 18.04.3.

**Comment by mc51** [comment]
@mgrojo thanks for your answer.
1. How would you run the Windows version under Ubuntu? Are you refering to using wine or anything similar?
2. I've tried compiling by myself and got a working version. However, I couldn't figure out how to influence which sqlite version is being used. Any hints for that?

**Comment by mgrojo** [comment]
>  1. How would you run the Windows version under Ubuntu? Are you refering to using wine or anything similar?

Yes, using wine. Download https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip, uncompress it, and run `wine DB\ Browser\ for\ SQLite/DB\ Browser\ for\ SQLite.exe`
 
>  2. I've tried compiling by myself and got a working version. However, I couldn't figure out how to influence which sqlite version is being used. Any hints for that?

We have these instructions, but take into account that they might be outdated. https://github.com/sqlitebrowser/sqlitebrowser/wiki/Compiling-DB4S-on-Ubuntu-To-Use-A-Pre-Installed-Version-of-SQLite

**Comment by mc51** [comment]
@mgrojo: Thanks, that helped a lot. I finally managed to compile my own version using the latest sqlite3 version.

For anybody who wants to do the same:
You can compile the latest sqlite3 from the source code by following this:
https://www.sqlite.org/cgi/src/doc/trunk/README.md

Then, you will find the libsqlite3.a in the ./build/.libs folder and sqlite3.h in the root folder. Those, can be used as per the [instructions](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Compiling-DB4S-on-Ubuntu-To-Use-A-Pre-Installed-Version-of-SQLite) linked.

**Comment by MKleusberg** [comment]
Looks like this issue is solved then :smile: Please just re-open this issue if I'm wrong :wink:
