### ISSUE TITLE
Problem in database attachment

### ISSUE THREAD

**Issue by ashishkumartiwari** [sqlitebrowser/sqlitebrowser#190]
I tried to attach a database with another database, but nothing happened after attachment. I want to attach a database with another to copy the data from one's database to another database table.

**Comment by MKleusberg** [comment]
What do you mean with 'nothing happened'? It should ask you for a name to attach the database under and - if the attach operation performed successfully - won't show any message, the new database is just there and can be accessed by SQL, eg:
```sql
INSERT INTO main.destinationtable SELECT * FROM attacheddb.sourcetable;
```

Of course, the attached DB should be shown somewhere in the UI but either way, it should be attached. But maybe even that's not working for you - that's why I'm asking :)

**Comment by Z4us** [comment]
https://www.sqlite.org/lang_attach.html

**Comment by Z4us** [comment]
and https://www.sqlite.org/c3ref/open.html#urifilenamesinsqlite3open

**Comment by justinclift** [comment]
@ashishkumartiwari Ping?

**Comment by justinclift** [comment]
Hmmm, going to close this for now.

@ashishkumartiwari If this is still not working for you and you still need assistance, you're welcome to reopen it. :smile:

**Comment by DAOWAce** [comment]
I'm also not understanding this.

I've tried to google about merging two databases together, and pretty much all of them talk about using the attach function of SQLite.

However, I am too stupid to know what the code is to do this.

I attempted to use this program to just attach the database for me, but when I select the one I want to merge it asks me what to call the database.

This is where I hit a wall and don't understand.

I don't want a new name for the database, so I attempted to name it the same as the old.  Nothing happened.  It showed a log saying it was attached, but nothing changed within the database.

I tried to name it something different.. same thing, no changes.

Needless to say, I don't understand what's going on.

**Comment by glawrence** [comment]
Hi @DAOWAce I have had a look at this and did the following:

* Create a new database file with TableOne in
* Create another new database file with TableTwo in
* Create a third database file with nothing in
* Attach (File -> Attach Database) first database file, naming it "One"
* Attach (File -> Attach Database) second database file, naming it "Two"
* You will note that the "Database Structure" and "Browse Data" tables are empty
* In "Execute SQL" you can use "select * from One.TableOne" and see the table

So, I believe this works. @MKleusberg I assume there is a reason why the Structure and Browse tabs don't show attached database

**Comment by justinclift** [comment]
Opening this for now, as there is still activity here after all.  @DAOWAce / @glawrence Feel free to close this again when it's taken care of. :smile:

**Comment by glawrence** [comment]
I am happy this is all working as it should, up to @DAOWAce really unless @MKleusberg thinks something is wrong

**Comment by MKleusberg** [comment]
Quick update here: the attached databases (using the approach described by @glawrence) now show up in the UI and can be browsed and edited just like the main database. If you're still interested in this, @ashishkumartiwari and @DAOWAce, you can download the latest nightly build, and check if it's working for you :smile:

**Comment by DAOWAce** [comment]
Thanks for the update.

Admittedly I don't even remember what I was trying to do 1.5 years ago, but still, it's nice to see updates for things anyway!

**Comment by justinclift** [comment]
Thanks @DAOWAce. :smile:

Closing this now, as it sounds like the problem has kind of er... expired over time and we've also likely fixed it with the recent ATTACH changes anyway.

**Comment by MKleusberg** [comment]
No problem, @DAOWAce :smile:
