### ISSUE TITLE
cannot open files

### ISSUE THREAD

**Issue by keithtmc123** [sqlitebrowser/sqlitebrowser#1900]
Details for the issue
--------------------

#### What did you do?
open a db file

#### What did you expect to see?
at least can open it

#### What did you see instead?
cannot open

[Suggestions.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3197733/Suggestions.zip)

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.6.0) [x86_64]
> using SQLCipher Version 4.1.0 community (based on SQLite 3.27.2)
> and Qt 5.11.3

**Comment by justinclift** [comment]
When it "doesn't open", is an error message displayed or something that could be useful for figuring out what's wrong?

Also, which database file(s)?  When downloading the Suggestions.zip attachment and extracting the contents in a virtual machine, there are several database files inside.  Opening them worked ok for me, though it was with a slightly older version of our application (just because it was an older virtual machine I haven't updated things in yet).

**Comment by chrisjlocke** [comment]
What are you trying to open - the suggestions.zip itself, or the .db files
within it?  The ZIP contains numerous .db files, which all open fine.

>

**Comment by keithtmc123** [comment]
ahhh, but i can't open them in my mac and i am suspecting there is hacker who making changes to my original files and also the certificates.

________________________________
寄件者: Chris Locke <notifications@github.com>
寄件日期: 2019年5月20日 22:00
收件者: sqlitebrowser/sqlitebrowser
副本: Kyle; Author
主旨: Re: [sqlitebrowser/sqlitebrowser] cannot open files (#1900)

What are you trying to open - the suggestions.zip itself, or the .db files
within it? The ZIP contains numerous .db files, which all open fine.

**Comment by justinclift** [comment]
Well, that raises a few questions. :wink:

What kind of warning message is it showing when it doesn't open?  Are you ok to make a screenshot, as that would really help. :smile:

Which certificates?  There are a few places we do stuff with certificates (our website, some internal stuff, etc).  Just wanting to make sure we're thinking of the same things.

**Comment by chrisjlocke** [comment]
Closing this due to lack of response.  As noted, you can't open a ZIP directly, and the .db files in the zip all opened OK.
@keithtmc123 - If you can provide screenshots of what errors you're experiencing, then we can investigate further.
