### ISSUE TITLE
[SQL Log] Application does not show 'Write Changes' action.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1901]
Details for the issue
--------------------
I made a simple edit in a cell and the "Write Changes" button correctly became highlighted.
MyDB.db-journal file appeared within the folder of MyDB.db and vanished upon completion of the write cycle. My journal mode Pragma = delete.

#### What did you expect to see?
I want to see the SQL transaction within the SQL Log - Application or User. At least somewhere?
If the transaction is too long, then a truncated version would suffice.

#### What did you see instead?
No changes to either Log.

Useful extra information
-------------------------
[I was under the false impression that the SQL Log would capture such actions.](https://github.com/sqlitebrowser/sqlitebrowser/issues/1859#issuecomment-487062471)

#### What operating system are you using?

- [x] Windows: ( _version:_10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: ___3.11.99 nightly v190520

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by scottfurry** [comment]
There are three types of logs that can appear in the log window. Are the actions you expect to be logged appearing in the log window after changing the type of log presented?

![SQLLog_Dropdown_Selector](https://user-images.githubusercontent.com/6686571/58040392-a62aae00-7af2-11e9-8bc0-3c480b25c1d7.png)

**Comment by sky5walk** [comment]
I don't care which log gets appended. But, I thought the User log was only Execute SQL actions?

**Comment by mgrojo** [comment]
Hi @sky5walk. The next nightly build will show the savepoint related statements in the Application log. Could you take a look and close this issue if everything is ok?

**Comment by sky5walk** [comment]
Ok, a few issues?
Clear SQL log clears all logs(User,App,Error). Is that intended?
Clicking 'Write Changes' only shows RELEASE "RESTOREPOINT";
There is no log entry(User or App) for user edits of individual cells?
There should be an option to log all entries somewhere. 
I prefer to clutter the App log and limit the User log to Execute SQL actions.
There is too much redundancy implied in the User log name that it should be called "Execute".
Users trigger actions in both logs, so how are we to know when and where to look?

**Comment by sky5walk** [comment]
Works ok.
