### ISSUE TITLE
Add Hotkey for Open Read Only or Option to set Open as Read Only as Default

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#1904]
Describe the new feature
--------------------------
Currently my muscle memory is clicking the big Open Database button on the Toolbar. However I am developing game mod and opening that way prevent the game from dumping new data into database (because it is in use). With read-only mode, this would be great. However there is currently no quick way to do that. So I suggest:

* Add Hotkey for Open as Read Only, for example Ctrl Shift O.

and/or

* Add a Preference option for open as Read Only as default.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
No.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No.

**Comment by chrisjlocke** [comment]
If you open a database, DB4S shouldn't normally 'lock' it, unless the
'Write Changes' button is enabled - at that point, its locked until you
click 'Write Changes', then the button is disabled again (and the database
is writeable by others)

>

**Comment by datvm** [comment]
@chrisjlocke Yes have just tested, this is correct, so sometimes I was changing the database without noticing it. Thank you for the tip.

**Comment by mgrojo** [comment]
@datvm Ctrl+Shift+O will open database read-only in tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest).  Could you confirm and close this issue? Note that the nightly will also include 335999e4bdeffca10913cb832fce2498cf9f5d68 which might also be of interest to you.

**Comment by datvm** [comment]
> @datvm Ctrl+Shift+O will open database read-only in tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest). Could you confirm and close this issue? Note that the nightly will also include [335999e](https://github.com/sqlitebrowser/sqlitebrowser/commit/335999e4bdeffca10913cb832fce2498cf9f5d68) which might also be of interest to you.

Hi, I think it's not built yet right?

![image](https://user-images.githubusercontent.com/6388546/62444094-c7f91000-b786-11e9-85ba-24bfca6394a7.png)

Latest build is at July 29th, and the option is not there yet.

I no longer work on the project with SQLite anymore but I am really thankful for this. Thank you very much.

**Comment by mgrojo** [comment]
Yes, there seems to be a problem with the nightly builds. I hope @justinclift can take a look.

**Comment by MKleusberg** [comment]
@datvm The new nightlies are available now :smile:

**Comment by datvm** [comment]
Thank you so much! Can confirm it works, both the hotkey and the Recent List!

**Comment by mgrojo** [comment]
Thanks for reporting, @datvm.
