### ISSUE TITLE
Split Browse Data Screen

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#1905]
Describe the new feature
--------------------------
It would be useful to be able to split the Browse Data window into 2 or more sub-screens so we can work on multiple tables at the same time.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
Yes, Word, Excel and Visual Studio has something like this:

![image](https://user-images.githubusercontent.com/6388546/58074746-312da600-7bd0-11e9-9ea0-a067916d93cb.png)

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Pardon the quick demo, I made it myself so not very good looking but should explain the idea. The split can either be horizontal or vertical:

![image](https://user-images.githubusercontent.com/6388546/58074800-4d314780-7bd0-11e9-9aa7-4fa1db2f4fde.png)

**Comment by chrisjlocke** [comment]
Not a full solution, but you can open multiple copies of DB4S at the same
time, and line up the windows to maximise screen area.

>

**Comment by datvm** [comment]
@chrisjlocke Yes, that's what I am doing right now :P

**Comment by indrakaw** [comment]
Instead of splitting, why not tabbing like as seen on FTP Zilla client? It's cool, so you don't have to run multiple windows.

**Comment by datvm** [comment]
@indrakaw while tabbing is also nice to have, the pros of Splitting is you can see both data at the same time (assume your screen is big enough). @chrisjlocke suggestion actually works as "tabbing", and works for my case splitting because I have two screens.

**Comment by datvm** [comment]
@justinclift I used the Windows MSI to switch to the nightly version for good, I have this error on startup:

![image](https://user-images.githubusercontent.com/6388546/90994704-cee9ff00-e5e3-11ea-8003-e425de924400.png)

Everything else seems okay so far, just want to notice you about this.

**Comment by justinclift** [comment]
Thanks for mentioning the problem @datvm, that sounds like a bug we'll need to fix. :smile:

**Comment by chrisjlocke** [comment]
This might be related to the change Manuel did to display the version / help in a messagebox.... (#1982, etc)

I think its a 'false positive' error ... its because the browse data tab is empty at startup.  Once you load a database, all is good...

**Comment by MKleusberg** [comment]
Oops, I accidentally introduced that in 8a455106f980f5893f60efae1e705d13ac2105a1 and, as Chris said, only another change by Manuel made this warning visible. It's fixed now. Can you check again with tomorrow's nightly build and see if that is working as expected? :smile:

**Comment by datvm** [comment]
Can confirm today nightly build solves the problem 👍

**Comment by MKleusberg** [comment]
Awesome! Thanks for checking :+1:

**Comment by datvm** [comment]
Hi sorry it's been a long time I haven't been using SQLite again. I downloaded the latest 3.12.2 and it seems this feature isn't released yet? The nighty build at https://nightlies.sqlitebrowser.org/latest/ doesn't have Windows build, each of them is only 32KB 😅 Please advice, thank you so much and hope everything is still good.

**Comment by chrisjlocke** [comment]
Yes, this hasn't been put into the main release yet. I think there may be plans to make all windows dockable and it was tested for the browse data windows first. It might make it as is to the next version though as development has slowed lately.

The nightlies are currently broken but if you go up a directory then go into the 32-bit directory, you can see the last nightly for about 22 Aug. Yell if you need an exact link.

**Comment by datvm** [comment]
Thanks a lot I got the build on Aug 22nd and it works well so far!
