### ISSUE TITLE
Execute SQL tab: Add search bar for SQL code

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#191]
It'd be nice to have the option to search for texts or patterns in the SQL code in the Execute SQL tab. Some people keep all their SQL queries as some sort of history (I don't), but this would also be useful when opening a database dump or some similarly large SQL file. A find & replace function makes it even more useful.
I would suggest implementing this as one of these search bars modern application like to have, instead of adding a new dialog for it. The search bar is a bit more difficult to implement but easier to use and, when added to the SqlTextEdit class, would also work for all the other places where this class is used (like the SQL log).

**Comment by justinclift** [comment]
This is a bit unclear to me.   Can you whip up a dodgy pic or something to illustrate?  (doesn't have to be pretty, just needs to get the concept across) :wink:

**Comment by MKleusberg** [comment]
Here's a mockup of what I mean - "something you'd expect to open when you press Ctrl+F" might've been a better description :)
![find_mockup](https://cloud.githubusercontent.com/assets/3153504/5962376/c61a3ef6-a7e3-11e4-95c8-c7c4c0394f36.png)

**Comment by justinclift** [comment]
Ahhh, ok.  In the example above, would it then reduce the output to show only rows with 'example' in them?

**Comment by MKleusberg** [comment]
Thanks for adding this, @mgrojo! I think we can finally close this issue then :smile:

**Comment by jungle-boogie** [comment]
Thanks for implementing this, @mgrojo! It is a qt thing for the escape key to clear a field? If so, I think that would be a worthwhile improvement for this.

**Comment by mgrojo** [comment]
@jungle-boogie, do you mean that the Escape key should clear the search field? I'd prefer it to hide the search bar, like Firefox and other applications do. For clearing the field in Qt, we have Ctrl+U, at least in Linux, where it is a default for many applications. It may be different in Windows.

By the way, currently Ctrl+F toggles the search bar visibility.

**Comment by jungle-boogie** [comment]
hi @mgrojo,

> do you mean that the Escape key should clear the search field?

Yes, that's it.

> I'd prefer it to hide the search bar, like Firefox and other applications do. 

I don't have any objections to that, especially now that you make the reference to firefox.

> we have Ctrl+U, at least in Linux, where it is a default for many applications.

Ah, that's nice to know!
