### ISSUE TITLE
Missing PACKAGE.vcxproj

### ISSUE THREAD

**Issue by BenKolarik** [sqlitebrowser/sqlitebrowser#1914]
### Details for the issue

I'm trying to build SQLite from source and package it, but I'm running into a problem.  At the end of the guide it says that one is supposed to build the PACKAGE.vcxproj, but CMake seems to have failed to create one.  No relevant errors or messages have appeared, so I'm kind of stuck.  Has a new procedure for creating a package from source been created since the release of the guide?  This [issue](https://github.com/sqlitebrowser/sqlitebrowser/issues/1401)  seems to imply some changes were made to this process, but not what they were.  Any help?

#### I'm opening this issue because:

- [X] DB4S has another problem

#### I'm using DB4S on:

Windows 10

#### I'm using DB4S version:

- [X ] 3.11.2

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds(need to be building a stable version)
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
> I'm trying to build SQLite from source and package it, but I'm running into a problem.

Package it as `.msi` installer, `.exe` installer, or `.zip` file?

> At the end of the guide it says that one is supposed to build the PACKAGE.vcxproj, but CMake seems to have failed to create one.

We used to create NSIS-based `.exe` installer using CMake, then switched to MSI installer. The relevant parts that created the NSIS were removed from `CMakeLists.txt` file.

> Has a new procedure for creating a package from source been created since the release of the guide?

I'm sorry if that wasn't mentioned anywhere, and the fact that we forgot to update the wiki. Please forgive us. :smiley: 

To build the `.msi` package, take a look inside `installer\windows` folder, and you will find everything you need. You need to install [WiX Toolset](https://wixtoolset.org/) first.

After installing WiX, simply run `build.cmd win32` or `build.cmd win64` to build for your target architecture. You will find the batch files we use to generate the nightly builds inside `nightly_build_scripts` folder also.

**Comment by BenKolarik** [comment]
Thank you so much for the help!  I've created a working .msi installer, and everything works.  Thank you for the prompt response.  You can close this issue if it would be appropriate.

**Comment by justinclift** [comment]
Excellent!

Great stuff @BenKolarik  and @karim. :smile:
