### ISSUE TITLE
Error creating SSL context()

### ISSUE THREAD

**Issue by tgely** [sqlitebrowser/sqlitebrowser#1915]
Details for the issue
--------------------

#### What did you do?
Fresh install

#### What did you expect to see?

> Error when connecting to https://download.sqlitebrowser.org/currentrelease.
> error creating SS context()

#### What did you see instead?

No error message or update informations :)

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
Hmmm, guessing the "expected to see" and "what did you see instead" sections are reversed, or are you reporting a previous problem has now gone away? :smile:

**Comment by justinclift** [comment]
@tgely ?

**Comment by tgely** [comment]
I see the error message as reported in "expect" section on every program start. If I remember well 32bit version has no trouble.

**Comment by justinclift** [comment]
Interesting.  With your network connection, is it WiFi or cabled?

We've seen some weird behaviour before with WiFi connections, but we fixed "most" (!) of the problems.  Most being "we thought we'd got it sorted, but turns out to be not 100%".

If this isn't a WiFi connection though, it'll be something else. :frowning:

**Comment by tgely** [comment]
Its cabled. Probably should I install 32bit version instead? There was not error.

**Comment by justinclift** [comment]
Yeah, definitely try that. :smile:

**Comment by chrisjlocke** [comment]
Any joy with the 32bitties version?

**Comment by tgely** [comment]
64bit versions has trouble for me. DB Browser for SQLCipher.exe wants msvcr120.dll and not run. DB Browser for SQLite.exe open with error connection message.

32 bit versions work perfectly.

**Comment by Eschato** [comment]
I have the same issue on WiFi with the 64 bit version.

**Comment by justinclift** [comment]
Ahhh yeah.  The current release doesn't yet support being used through a proxy.  We added initial proxy support in the nightly builds a while back, if you're up for testing it? :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Oh... unless you're meaning that you're not behind a proxy at all?

**Comment by Eschato** [comment]
Oh sorry, I meant I'm not behind a proxy at all.

However, I have a home gateway from the ISP and an additional router connected to it. I'm using my own router for the WiFi, I don't know if it matters.

**Comment by justinclift** [comment]
No worries.  Probably the best move, though not fantastic, is to just turn off our automatic update check at startup.  That should at least stop the error message from appearing.

At some point we'll probably need to write a simple utility specifically for testing why this is happening, or perhaps add some pretty extensive logging to the application.

It'll probably take a bunch of effort though, so unlikely to be in the near future. :frowning:

**Comment by Eschato** [comment]
Yeah, it's not a big issue, I just wanted to let you know.
Feel free to msg me if I can help in any way with the testing.

DB browser is awesome, also helps a lot for newbies like me so thanks guys!

**Comment by chrisjlocke** [comment]
@Eschato - This issue has been floating around for a while, and we initially thought we solved it.  However, a very small number of users have this issue.  Its interesting you have the same error on the 32bit version - you're unique!

As another 'test', do you also get the issue with DB4S for SQLite with SQLCipher?  (its a separate .exe)

**Comment by Eschato** [comment]
@chrisjlocke 

I can not start SQLCipher, it says MSVCR120.dll is missing. I tried both 32 and 64 bit. Same error msg for both.

**Comment by karim** [comment]
> I can not start SQLCipher, it says MSVCR120.dll is missing. I tried both 32 and 64 bit. Same error msg for both.

That shouldn't happen. The missing DLL means you don't have Visual C++ 2013 Redistributable Package installed. This is not required to install/run DB Browser for SQLite. See #1912 and #1884.

 Can you provide a link to the version you are using?

**Comment by Eschato** [comment]
@karim 
https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.11.2-win32.msi
https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.11.2-win64.msi

**Comment by justinclift** [comment]
Interesting.  Is there any chance an older version of DB4S might still be partially installed somewhere?

eg a new version was installed, but didn't correctly remove an existing one.

That could explain the weird `MSVCR120.dll` error.

**Comment by karim** [comment]
None of these versions depend on Visual C++ 2013, so I don't know why it's asking for `MSVCR120.dll`.

```
> dumpbin /dependents "DB Browser for SQLCipher.exe"

Microsoft (R) COFF/PE Dumper Version 14.21.27702.2
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file DB Browser for SQLCipher.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    Qt5PrintSupport.dll
    Qt5Widgets.dll
    Qt5Network.dll
    Qt5Xml.dll
    sqlcipher.dll
    Qt5Gui.dll
    Qt5Core.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    KERNEL32.dll
```

Did you upgrade over an older version maybe like Justin said? Can you do a uninstall DB4S and do a clean install?

In *Programs and Features* do you see any of `Microsoft Visual C++ <year> Redistributable` package installed?

**Comment by Eschato** [comment]
@justinclift @karim 
This was the first time I installed DB Browser. No older version was installed before.
First I started with the 64 bit version, there came the "Error when connecting to https://download.sqlitebrowser.org/currentrelease.
error creating SS context()" error.

Then I unsinstalled the 64 bit version via Windows built in uninstaller and after a restart (just in case) I installed the 32 bit version to check SQLCipher. There came the missing dll error.

Uninstall again, back to 64 bit version and same missing ddl on SQLClipher.

I really can't think of any user error I might have done. I'll check the Microsoft Visual C++ <year> Redistributable package when I get home.

**Comment by chrisjlocke** [comment]
> First I started with the 64 bit version, there came the "Error when
connecting to https://download.sqlitebrowser.org/currentrelease.
error creating SS context()" error.

>
Install the original 64bit version and get the 'creating ss context'
error.  Once you get that, click OK, go to Edit, click Preferences, and
take off 'Check for automatic updates'.  Its this check thats causing the
error.
That at least makes the application usable.  By turning that option back
on, when convenient, we can work out whats going on and see if we can get
around that issue AND the DLL issue...

**Comment by justinclift** [comment]
Yeah, it sounds like you've done everything 100% correctly.  This behaviour is really weird. :frowning:

**Comment by glawrence** [comment]
I have done some digging on this in a Windows Sandbox using the nightly build from 29 July 2019 and see the above problems. @karim I dug a little further and used PEStudio to find that msvcr120.dll is used by both libeay32.dll ssleay32.dll, so there is an indirect use. I hope this helps

**Comment by karim** [comment]
@glawrence Thank you so much, you are right! :smiley: 

I don't know how we missed that. I checked our build script now and I saw that OpenSSL library is not being rebuilt every time we build DB4S. It seems like it was built once, using Visual Studio 2013, and we were using it since then. This is affecting our latest stable and nightlies as well.

@justinclift Can you confirm that?

Strange that we didn't get this error reported a lot. Maybe users already have Visual C++ 2013  Redistributable installed, or they tried to fix it themselves by installing it.

**Comment by justinclift** [comment]
Ahhhh, so that's where the dependency is coming from.

@glawrence You are brilliant!  Thank you so much for figuring it out. :smile:

@karim It's definitely possible this is the case.  We use the OpenSSL 1.0.2 release builds from here:

&nbsp; &nbsp; https://slproweb.com/products/Win32OpenSSL.html

Should we rebuild the Win installers to include the Visual C++ 2013 redist merge modules?

**Comment by karim** [comment]
> Should we rebuild the Win installers to include the Visual C++ 2013 redist merge modules?

I'm not sure if including two Visual C++ Redist will be a good idea. Never tried it but should work. It will add dependency on Visual Studio 2013 though since each version comes with its own merge modules, and we must have it installed to be able to build DB4S.

Another option is to build OpenSSL ourselves instead of using the binaries.

**Comment by justinclift** [comment]
There are other sources of OpenSSL for Windows.  The above one is just what I first went with, as it was the 1st option in the list on the OpenSSL website:

&nbsp; &nbsp; https://wiki.openssl.org/index.php/Binaries

The download option just below that [one](https://indy.fulgan.com/SSL/) describes itself as:

"Pre-compiled Win32/64 libraries without external dependencies to the Microsoft Visual Studio Runtime DLLs, except for the system provided msvcrt.dll."

That being said, it might be better to just build OpenSSL ourselves after all.  Haven't tried it, so not sure if it's easy/hard/etc. :wink:

**Comment by glawrence** [comment]
Another option might be to build [LibreSSL](https://www.libressl.org/) instead, just a thought as it might be easier

**Comment by karim** [comment]
Qt does not support LibreSSL (https://bugreports.qt.io/browse/QTBUG-68374), as it seems to work only with OpenSSL (https://doc.qt.io/qt-5/ssl.html).

**Comment by glawrence** [comment]
> 
> 
> Qt does not support LibreSSL (https://bugreports.qt.io/browse/QTBUG-68374), as it seems to work only with OpenSSL (https://doc.qt.io/qt-5/ssl.html).

Ah, fair enough then

**Comment by mgrojo** [comment]
By the way, is this a release blocker for Windows?

**Comment by chrisjlocke** [comment]
It only happens in a very finite scenario...
In the number of downloads we have, a very small number of people are
affected.  And by turning off the auto check, the error is averted.  Not an
ideal workaround, but if they keep an eye on the website, they'll see the
next release... which doesn't come round THAT often.
I wouldn't personally call it a release blocker...

>

**Comment by justinclift** [comment]
Yeah, it's probably something we'll fix for the next release.  eg experiment with different potential OpenSSL implementations - if not build our own - to get rid of that additional dependency

**Comment by AxnoratanxA** [comment]
I'm having the same problem and exactly the same error message. on the 32-bit version on Windows.

Things I have already tried:
- Resetting the network
- Using a wired connection
- moving these libraries into the directory: libeay32.dll, libssl32.dll, and ssleay32.dll
- checked the network security

I don't really know what else to do now, I am locked out of my database which I really need to access as soon as possible.

The website works fine when  I put it into the browser.

Please help someone.

**Comment by chrisjlocke** [comment]
> I don't really know what else to do now
>  I am locked out of my database

The error is simply DB4S checking for a newer version and failing to talk properly with the website.  It should have no effect on the rest of the working.  Simply click on [OK] and the error will disappear, and DB4S will continue.  If you're experiencing other 'symptoms' (eg, DB4S closing), please let me know.

You can clear this error by going to preferences, then turning off the automatic check.  However, it's recommended you then visit the DB4S website to check manually for updates! ;)

> moving these libraries

The error is actually already in these libraries, which DB4S can find, so moving files around doesn't solve anything, unfortunately.  In fact, it'll just cause more problems, so I'd recommend 'undoing' whatever file manipulation you've carried out.

**Comment by AxnoratanxA** [comment]
Thank you so much for your help, I really appreciate it. I finally got it working now. You saved my life :)

**Comment by chrisjlocke** [comment]
I'd still be interested to know what made you feel DB4S was locking you out of the database though.
Its a serious question.  Yes, the error could have been handled a bit better, but what could have we changed to make it obvious it was only a warning, and not a complete failure?

**Comment by ZealJared** [comment]
Had this issue today. I initially assumed the same as @AxnoratanxA. The error is general, so I assumed it applied to the general function of the application (doesn't mention checking for updates, though maybe someone brighter would draw more meaning from the URL than I did). It's also immediate. I'm used to an error message occurring in response to an action I knowingly initiated (launching the application), so I assumed this was an error inhibiting normal application launch. Now that the error is known, perhaps a more user-friendly message: "Failed to connect to **_URL_** while looking for update. Continue to use this version as usual, or install Visual C++ 2013 Redistributable from **_DOWNLOAD URL_**."

**Comment by AxnoratanxA** [comment]
I'm not sure what it was exactly but when I removed this: JS:ScriptSH-inf[trj]daily.ldb it seemed to work. My AV kept it quarantined but I managed to find out where it was a deleted it. There was no error with creating the SSL context after this

**Comment by chrisjlocke** [comment]
> Now that the error is known, perhaps a more user-friendly message

The error is actually thrown by the library, so we're probably unable to reword it, but (maybe?) we can trap it and then either ignore it, or display a more meaningful message.
Ultimately we'd like to stop the error completely, rather than just patch around it, but while we've tried that, it hasn't been 100% successful.

**Comment by Bibbu7** [comment]
I am facing the same problem. I tried both 32 and 64-bit versions but same error.

**Comment by chrisjlocke** [comment]
Once you get the error, click OK, go to Edit, click Preferences, and take off 'Check for automatic updates'.  It's this check that's causing the error.
Just check on the website manually...

**Comment by AxnoratanxA** [comment]
Yea, doing this helped for me, it'll probably (hopefully) work for you

**Comment by MKleusberg** [comment]
Is anybody still getting this error? If so, please don't fix it and write a comment here :smile: I don't think there is any way to fix this except by installing msvcr - but with some help by somebody with this error, we might be able to figure out how to show a better error message in the meantime.

**Comment by SoftwareTailor** [comment]
Yes. I'm using version 3.11.2. Qt version 5.7.1.

**Comment by SoftwareTailor** [comment]
I found the Automatic updates option on the Preferences option of the Edit menu. I just unchecked it and the error message doesn't appear any more.

**Comment by ronalddevos** [comment]
Same issue here, 3.11.2 with 5.7.1 - both on 32 and 64 bit version

**Comment by mviens** [comment]
Happening for me too.  I have never used this app before today.  Win10 x64, v3.11.2. I am using WiFi. All browsers show the URL just fine. I am not using a proxy.

**Comment by SoftwareTailor** [comment]
Hi Mike. Do I know you?

Bob

**Comment by mviens** [comment]
No Bob, I don't believe we know each other.  I am simply using GitHub to reply to a thread about an open issue that is still occurring.  You also replied to this thread (for the first time on Oct. 4, 2019).  You can unsubscribe from the thread if you no longer want to receive emails about it.

**Comment by SoftwareTailor** [comment]
Oh. Okay. I see it now. Thanks. Have a good day.

Bob

________________________________

**Comment by justinclift** [comment]
@mviens Does it still happen with our latest nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

We're getting ready for a new release, and there have been a huge amount of code changes since 3.11.2, including some that *may* have fixed this. :wink:

**Comment by justinclift** [comment]
As a general follow up with this, our recent [3.12.0-alpha1](https://sqlitebrowser.org/blog/first-alpha-release-for-3-12-0/) release and the nightly builds from the last month or so onwards should much better with this issue.  They use a newer internal component (OpenSSL v1.1.1), which seems to be more reliable when making connections to our download server.

**Comment by SoftwareTailor** [comment]
Thanks.

Bob

________________________________

**Comment by MKleusberg** [comment]
@justinclift Do you reckon we can close this issue then? Or is there anything left we can do in our code to word around this issue?

**Comment by justinclift** [comment]
Awesome.  Done. :smile:
