### ISSUE TITLE
TRUNCATE Table

### ISSUE THREAD

**Issue by miguevirtual** [sqlitebrowser/sqlitebrowser#1916]
Details for the issue
--------------------
Resultado: near "TRUNCATE": syntax error
En la línea 1:
TRUNCATE

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLCipher Version 4.1.0 community (based on SQLite 3.27.2)
> and Qt 5.11.3

**Comment by justinclift** [comment]
Yeah, this is expected.  SQLite itself has no "TRUNCATE" command, unlike some other databases (eg PostgreSQL).

You can use `DELETE FROM` instead though:

```
DELETE FROM sometable;
```

Does that help? :smile:

**Comment by scottfurry** [comment]
There is also the `vacuum` command available for SQLite databases.
https://www.sqlite.org/lang_vacuum.html

**Comment by justinclift** [comment]
Good point.  `VACUUM` can be used to free up disk space after the `DELETE` command. :smile:

**Comment by MKleusberg** [comment]
Closing this since there's nothing we can do here. But please feel free to ask to post any further comments or questions in this issue, @miguevirtual :smile:
