### ISSUE TITLE
Export from Browse Data tab

### ISSUE THREAD

**Issue by ch728** [sqlitebrowser/sqlitebrowser#1919]
Describe the new feature
--------------------------
Hi,

Is there a way to export the table obtained from filtering in the Browse Data tab?  I know that it is possible to export results from filtering in the execute SQL tab, but I think it would also be nice to be able to export them after using the filter options in the Browse Data tab.

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
Yes, in the [last release](https://sqlitebrowser.org/dl/) you can use this icon ![imagen](https://user-images.githubusercontent.com/13812910/59709102-4ebd5200-9206-11e9-88d8-9e87979b428e.png) in the Browse Data tab to export the current browsed table as filtered.

**Comment by mgrojo** [comment]
@ch728  I hope we have helped you. I'll close this now, but you can still comment on it if you'd like.

**Comment by ch728** [comment]
Yes, thank you!
