### ISSUE TITLE
Proper foreign key support in the UI

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#192]
We could parse the foreign key constraints in a table definition to understand which column links to which column of a different table and then use that information in the Browse Data tab: When hovering over a cell with a foreign key constraint and some data in it, we could show a tooltip telling the user to what table is linked here. And when holding Ctrl and then clicking the cell (or some similar combination) we could jump there directly.

**Comment by justinclift** [comment]
Sounds like a really good idea.  Please make it so. :grin:

**Comment by karai17** [comment]
Is there any update on this issue? The ability to add foreign keys would be really helpful.

**Comment by MKleusberg** [comment]
@karai17 Adding foreign keys already is possible :smiley: You have to scroll to the right side end of the grid view in the Edit/Create Table dialog but then you'll find the field you need:
![foreignkey](https://cloud.githubusercontent.com/assets/3153504/8273293/70984122-1867-11e5-93f7-a671dd7eefff.png)

**Comment by karai17** [comment]
....... I am an idiot. Thank you. .____.;

**Comment by MKleusberg** [comment]
@karai17 No worries, you're probably not :smiley: And I have to admit, too, that the field for foreign keys isn't placed very well...

As for the original issue described here: With commit 39a49e33c2e48f0b389ad9681998d7ac1588e2ef I try to add exactly that feature. There's a tooltip now appearing for cells with a foreign key set which tells you the name of the referenced table and when you hold Ctrl+Shift and click on the cell it jumps to the referenced row. Anyone willing to test this? :smile:

**Comment by SacredSkull** [comment]
It would be great if the UI itself also had a dropdown of some of the rows when entering foreign key data. As far as I can tell none of the other SQLite GUI tools support this. phpMyAdmin and MS Access are two examples of tools that do that.

Otherwise, excellent tool!

**Comment by justinclift** [comment]
@MKleusberg With the latest commits, is this now fixed?

**Comment by MKleusberg** [comment]
No, not yet. The last commits only fixed some bug I've introduced during my code refactoring. This means we're in a much better position now to start working on this but it's not yet implemented.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by justinclift** [comment]
#614 seems related to this too.

**Comment by minaamirrizk** [comment]
> @karai17 Adding foreign keys already is possible  You have to scroll to the right side end of the grid view in the Edit/Create Table dialog but then you'll find the field you need:
> ![foreignkey](https://cloud.githubusercontent.com/assets/3153504/8273293/70984122-1867-11e5-93f7-a671dd7eefff.png)

omg .. thanks man ..

**Comment by minaamirrizk** [comment]
> @karai17 Adding foreign keys already is possible  You have to scroll to the right side

OMG .. how did u get it !! .. thanks man ..

**Comment by xpidelaserra** [comment]
@MKleusberg 

Should it be any icon that shows that an attribute is a foreign key, like the one shown for primary key?
I don't see it now and it would be really helpful to have a proper picture of the schema.

Thank you.

**Comment by MKleusberg** [comment]
Closing this issue because
- We have added the tooltip + follow foreign key shortcut a long time ago
- We are showing a combobox of possible values when editing a foreign key value
- Manuel has added the foreign key icon
- We need to reduce the issue count :wink:

**Comment by csanyipal** [comment]
Here on my Xubuntu system this does not work, as expected.
When I click on a field which has reference to another table (because it is a foreign key) the combo box is showed for a moment then immediately disappeared so I can't browse the possible values for this field, but sometimes it succeeds so I can browse the possible values for this field.

**Comment by scottfurry** [comment]
@csanyipal - this is a closed bug. Not best practice to "bump" in this manner.
Can you start a new bug and provide as much detail as possible, please.
Crucially, we need versions for Xubuntu and DB4S where this problem was encountered.
