### ISSUE TITLE
CREATE VIEW works, but needs reopening of DB

### ISSUE THREAD

**Issue by c-boeckler** [sqlitebrowser/sqlitebrowser#1922]
Details for the issue
--------------------

#### What did you do?
I developped a SQL query and then prepended it with CREATE VIEW name AS and executed it successfully (according to the results window). 

#### What did you expect to see?
I hoped that the newly created view would show up immediately in the browse tab or in the schema tab.

#### What did you see instead?
Unfortunately the view did not show up in either of these tabs. Only after I closed the database and reopened it again, the view showed up as expected.

Useful extra information
-------------------------

#### What operating system are you using?

- [X] Windows: ( _version:_ 7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
As a general thought, it kind of sounds like you needed to hit the "Refresh" key.  F5 I think.

Do you remember if you tried that before reopening the DB?

**Comment by chrisjlocke** [comment]
I'm on Windows 10 and don't need to click refresh...

[image: image.png]

So create new view...

[image: image.png]

then simply return to the 'Database Structure' tab

[image: image.png]

Thanks,
Chris

**Comment by c-boeckler** [comment]
@justinclift  Thanks for the hint! I did not press F5 before reopening the DB, but doing it makes the new view appear in all expected places. 

It would have been nice if this key binding was part of the View menu as an appropriate entry (e.g. Refresh View F5?).

**Comment by justinclift** [comment]
From memory, there's a button for it.  But yeah, it probably wouldn't hurt to put in a menu item.  Probably the "Edit" menu though. :smile:

**Comment by MKleusberg** [comment]
I think the reason why we don't have a menu item for it is that the F5 key works differently depending on the tab you are in. But it's certainly possible to add it somehow.

The main point however seems to be that the view doesn't automatically show up in the other tabs. This should definitely work automatically as @chrisjlocke said. Can you maybe double check if that problem still occurs for you, @c-boeckler? :smile: If so, I'll probably need your help because it is working for me :wink:

**Comment by c-boeckler** [comment]
I cannot reproduce the problem with a newly created database and table, neither on Windows 7 nor on 10. Sorry for the hassle!
