### ISSUE TITLE
Do not append BIN extension if exporing a BLOB with All Files selected and providing one in the file name

### ISSUE THREAD

**Issue by TomasHubelbauer** [sqlitebrowser/sqlitebrowser#1923]
#### What did you do?

Export a BLOB cell value using the Export button in the Edit Database Cell pane, selecting All Files  in the save file dialog filter (as opposed to the default one, BIN) and providing a name which contained its own extension (`tile.pbf`).

#### What did you expect to see?

`tile.pbf` where I saved it.

#### What did you see instead?

`tile.pbf.bin`

This is with the latest release from GitHub Pages, on Windows.

**Comment by scottfurry** [comment]
@TomasHubelbauer - IIRC, if you put the name in quotes, the file dialog in Windows will use the chosen  filename explicitly 'AS IS' and not append file extension. This is a 'quirk' on windows platform.

**Comment by TomasHubelbauer** [comment]
Oh yeah, it didn't occur to me to do that, thanks! Would be nice for SQLite to try and determine this itself, a lot of Windows software does so, but your tip is a solution for me meanwhile.

**Comment by scottfurry** [comment]
DB4S uses Qt gui elements and is dependent on what is provided. This has been a quirk of the Windows file selection dialog _for ages_. (As I stroke the long grey hairs of my beard). Sure, it could be 'a touch' more intuitive but again, we're using Qt and what it provides.

**Comment by TomasHubelbauer** [comment]
Right, well in that case I'm going to close this. This is super minor, so not big deal.
