### ISSUE TITLE
select

### ISSUE THREAD

**Issue by kh1108** [sqlitebrowser/sqlitebrowser#1924]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
@kh1108 This is missing a lot of detail.  Was it created by accident? :smile:

**Comment by chrisjlocke** [comment]
Closing due to emptyness.  So sad.  Poor issue.  Loved him so much.  So much.  My only true friend who really understood me.  #1924.  We will remember you.
