### ISSUE TITLE
[Feature Request] Increase sqlite3.dll SQLITE_MAX_ATTACHED = 125

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1926]
Describe the new feature
--------------------------
I have to attach 11 databases in a complex query.
But, the current DB4S sqlite3.dll is hard compiled to SQLITE_MAX_ATTACHED = 10.
It is more flexible to compile with SQLITE_MAX_ATTACHED = 125 and allow a configuration option to lower SQLITE_MAX_ATTACHED with 
sqlite3_limit(db, SQLITE_LIMIT_ATTACHED, someLowerAttachLimit)
#### Additional info:
Currently, I get an error on the 11th ATTACH.
-- Result: too many attached databases - max 10
I will recompile and replace the current sqlite3.dll within the DB4S installation folder.
#### Is your feature request related to an issue?
I went straight for Feature Request instead of opening an ISSUE.
Most topics mention attaching a handful of db's.
#### Does this feature exist in another product or project?
Yes, as SQLite allows for a max of 125.

**Comment by justinclift** [comment]
Sounds reasonable. :smile:

Looking at that page, it might be a case of just needing to update the compile time options.  eg:

```
-DSQLITE_MAX_ATTACHED=125
```

**Comment by justinclift** [comment]
Just manually added that to our Win64 nightly build script (just for SQLite, not SQLCipher yet), then started the script.

If it gets through the compile ok, then there will be a new nightly Win64 build in ~30-40 mins which should have the updated setting.

If that works, we can try it with SQLCiper and the Win32 pieces as well, then update the reference script in our source repo. :smile:

**Comment by chrisjlocke** [comment]
But I need 126 attached databases.  Can you recompile with
max_attached=126? ;)

>

**Comment by MKleusberg** [comment]
> But I need 126 attached databases. Can you recompile with max_attached=126? ;)
> […](#)

> The maximum number of attached databases cannot be increased above 125.

(https://sqlite.org/limits.html#max_attached)

:smile:

**Comment by scottfurry** [comment]
I had to read the full thread to realize the sarcasm...
I was going to say if you need 120+ separate open db (and threads), there's a serious design problem. Some heavy use of normalization would be in order.

**Comment by justinclift** [comment]
> But I need 126 attached databases. Can you recompile with max_attached=126?

Yep, a special version with raised limits is available here: https://www.postgresql.org/download/

:grin:

**Comment by sky5walk** [comment]
Nice, I will give it a go within the hour. 😄 
Executing the nightlies.exe on repo changes is paying off!
I see 190628 there already. 😮

**Comment by justinclift** [comment]
Cool.  Applying the same change to the Win32 build now, but also added the setting for the SQLCipher build too.

Lets see if that works as well... :wink:

**Comment by justinclift** [comment]
Just applied the same setting for SQLCipher to the Win32 and Win64 builds, then rebuilt both nightlies again.

@sky5walk Would you be ok to try the newly (again) rebuilt nightly, but using the SQLCipher executable this time?  Just to 100% make sure the change took effect. :smile:

**Comment by sky5walk** [comment]
Ok,
Might be tomorrow. I have never run the SQLCipher version before?

**Comment by justinclift** [comment]
It's just an alternative executable to run, instead of the SQLite one.  The installer gives the choice of which ones to install.  You'll figure it out. :smile:

**Comment by chrisjlocke** [comment]
> You'll figure it out

You need to stand on your left leg when running it, otherwise your kettle
will fail to turn off.  Also, ensure you have a newspaper on the floor (or
nearby) when running, otherwise the beetroot in your fridge will turn
blue.  We've also had reports that the tap in your bathroom needs to be
ever so slightly loosened.  Not sure why though - Justtin is looking into
that.
Good luck!!

>

**Comment by justinclift** [comment]
Haven't booked the flight to get there for checking said loosening.  Sometime next week maybe. :wink:

**Comment by sky5walk** [comment]
Ok, my query with 11 attached db's ran on both DB4S and DB4SQLcipher 190629 nightlies. 👍

**Comment by justinclift** [comment]
Fantastic!  Thanks heaps for taking the time to check it @sky5walk. :smile:

**Comment by sky5walk** [comment]
Yay, you saved me recompiling sqlite3.dll with the option. :))
