### ISSUE TITLE
Open/Create New dialog does not remember most recent folder on Windows

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#1928]
Details for the issue
--------------------

#### What did you do?
Open a file (`D:\Temp\Foo\test.db`). Close the app. Open the app again and click Open Database.

#### What did you expect to see?
The Open File Dialog should open show most recent folder:

![image](https://user-images.githubusercontent.com/6388546/60395598-1996f500-9b60-11e9-930d-aba6d3c881cc.png)

#### What did you see instead?

The user folder is shown instead:

![image](https://user-images.githubusercontent.com/6388546/60395604-274c7a80-9b60-11e9-952f-d6582beacfe1.png)

Useful extra information
-------------------------

From my experience, Windows API (and .NET Framework) should automatically cache the latest folder for each app separately without any extra work, so unless you are setting default/starting folder for the dialogs, it should be already showing most recent folder.

I also notice that for Nightly Build (I downloaded the .zip version and extracted at the download location), the path is reset to the exe's location every time I restart the app.

![image](https://user-images.githubusercontent.com/6388546/60395652-e6a13100-9b60-11e9-9d25-c8ecce341481.png)

One thing I notice is the "remember most recent folder" work as long as I have the app open, but once I close the app, the folder comes back to my User folder. Not sure if this is also happening for other OS or just Windows.

This is just a minor issue but would be a great QoL if fixed.

#### What operating system are you using?

- [x] Windows: ( _version: 10 Pro 1809 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [x] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Try setting "Preferences > General > Default location" to "Remember last location". I think it should behave then as you expect.

**Comment by datvm** [comment]
> Try setting "Preferences > General > Default location" to "Remember last location". I think it should behave then as you expect.

Yes, this works. Thanks a lot :)
