### ISSUE TITLE
network db files always opened as read only

### ISSUE THREAD

**Issue by lewtwo** [sqlitebrowser/sqlitebrowser#1933]
It seems anytime DB Browser for SQLite detects that a database file is on a network drive it opens it in 'readonly' mode. I see the option to force DB Browser for SQLite to open a file in readonly mode but I do not see and option for the opposite action (i.e. only in read/write mode). I know it might not be "recommended" but the question is is there a way to do it anyway?

**Comment by chrisjlocke** [comment]
I open sqlite files on a network all the time with no issues.
You haven't specified what version of DB4S you're using.  If you can
provide that, that'll be useful.
What OS are you using?  What 'server' is the database on?

**Comment by lewtwo** [comment]
My desktop is running: 
  Linux Mint 19.1 with the MATE 1.20.1 user interface, Kernel  4.15.0-52 Generic x86_64
The network machine is running:
  Linux Mint 18.3 with the MATE 1.18.0 user interface, Kernel  4.4.0-141 Generic x86_64

The network drive where the DB file stored is on mounted samba share:
 sudo mount -o username=<myname>,password=<mypass> -t cifs //<ip-address>/xxxx /mnt/xxxx

SQLite Version 3.21.0
Qt Version 5.9.3
DB Browser for SQLite Version 3.10.1 

I can open the database but I can not edit or change anything.
Executing an sql 'update' query gets the following error message: "attempt to write a readonly database"

**Comment by chrisjlocke** [comment]
And I assume if you open some console or other application, you can write
files there just fine?
DB4S isn't running as a different user or some such?  I'm not a Linux user,
so not familiar with any 'gotchas' that you might need to be aware of...

>

**Comment by lewtwo** [comment]
> And I assume if you open some console or other application, you can write files there just fine?
That would be an affirmative. I also checked the file attributes and user rights to make sure the database file was not marked readonly.

>  I'm not a Linux user, ...
So perhaps this is platform specific. OMG I hate that. 
That means I have to dig out a Windows OS and run the same scenarios.

**Comment by chrisjlocke** [comment]
> So perhaps this is platform specific

This is 'case' specific.  We have many users running DB4S on Linux, but the
number running on mounted Samba drives is a lot lower.  I'm sure others
have come across this though...

>

**Comment by lewtwo** [comment]
For my purposes SQLite turns out to be far more trouble than it is worth.
I have not got that much data and I can get round the problem using a XLS or flat file.

It is disappointing though: 
DB Browser for SQLite works really well locally. 
My own application works well locally.
... but as soon as the DB goes on a network share it becomes a nightmare.
Now I have to start over from scratch :-)

**Comment by chrisjlocke** [comment]
> For my purposes SQLite turns out to be far more trouble than it is worth.

Its just a setup issue.  In the long run, getting it working is worth it
... honest!
Doing some random Googles, some have suggested the directory ABOVE where
the SQLite file is is also writeable.  Is that the case?

**Comment by lewtwo** [comment]
Well I finally got round to testing on a Windows 10 OS (_how to wait several hours for Windows to do a 1903 Update_). No problems what so ever even though the Sqlite DB file was hosted on a Linux platform.

**Comment by AndrewMcSwain** [comment]
I'm having this problem as well. No solution? What does this error mean and how can I fix it?
