### ISSUE TITLE
CSV Import Behavior changed from previous version

### ISSUE THREAD

**Issue by AlfredoBB** [sqlitebrowser/sqlitebrowser#1934]
The behaviour of "import as CSV" has changed since the previous versions.
Strings with zero length used to be imported as ""; this was the standard behaviour for years. However they are now imported as NULL.

I have played with several options, I disabled "truncating fields" and "field detection"; it stays the same. I routinely import csvs. I think disabling "truncating fields" doesn't actually work.

Details for the issue
--------------------

#### What did you do?

Import csv with fields like:

28/07/2019;;"sometext";55

#### What did you expect to see?
field1: 28/07/2019
field2: 
(that means: field2 ="")
field3: sometext
field4: 55

#### What did you see instead?
field1: 28/07/2019
field2: NULL
field3: sometext
field4: 55

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( 3.11.2)
#### What is your DB4S version?

- [x ] 3.11.2
#### Did you also

- [no ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ yes] Search for an existing similar issue:

**Comment by AlfredoBB** [comment]
I've also noticed that .import (commandline) doesn't create those NULL values.
Maybe this is not a bug but rather a behaviour improvement.

**Comment by sky5walk** [comment]
Did you try importing: 
28/07/2019;"";"sometext";55

What did you expect to see?
field1: 28/07/2019
field2:""
field3: sometext
field4: 55
In my mind, "" <> empty.

**Comment by AlfredoBB** [comment]
Understood. The behaviour changed but this change is for better.
Thank you.
