### ISSUE TITLE
High energy consumption on Mac

### ISSUE THREAD

**Issue by cisoun** [sqlitebrowser/sqlitebrowser#1935]
Hi,

I was using SqliteBrowser on my Mac in the train and I've noticed that something was using a high quantity of energy. I took a look at the Activity Monitor and it seems the responsible was SqliteBrowser using the GPU. Is that normal ? I guess it's related to Qt but it still seems weird to me.

Here are some screenshots (excuse the french language but I think you can see my point):

<img width="944" alt="Capture d’écran 2019-07-09 à 08 57 19" src="https://user-images.githubusercontent.com/930282/60866489-c9d3c000-a228-11e9-8cfe-c6d475b6440f.png">
<img width="392" alt="Capture d’écran 2019-07-09 à 08 57 34" src="https://user-images.githubusercontent.com/930282/60866490-c9d3c000-a228-11e9-97a4-0fe1a9d1342d.png">

I'm using a Macbook Pro 2018 with Mac OSX Mojave 10.14.5.
Using SqliteBrowser 3.11.2, also concerns 3.11.99 (nightly).

Thanks.

**Comment by chrisjlocke** [comment]
Is this high consumption all the time (right from opening) or after opening
a specific tab, a database, etc.  If you run a query does it settle or get
worse?  If you view a large amount of data in the 'browse data' tab, does
it settle or get worse?
If you click 'Close Database' does it settle or get worse?  Just trying to
(hopefully) pinpoint an area to diagnose further.

>

**Comment by scottfurry** [comment]
And fellow classmates said High School French wouldn't become relevant in later life... :stuck_out_tongue_winking_eye:

@cisoun 
Nothing jumps out looking at the System Activity window.. Only thing that is an "annoyance" for me is the whether the system can be put in `sleep` mode ('App Nap` is Non for DB4S from your screen capture). I ran into that painfully realization dealing with 'Civilization' on wife's Mac. Couldn't figure out why the computer would not go into sleep mode until I tripped over an obscure blog post in Civ Forums. See [here](https://www.lifewire.com/control-how-mac-applications-use-app-nap-2260788) for more info.

A google search of "MacBook Mojave Qt high CPU usage" brought up no recent postings. Qt's [MacOS Issues](https://doc.qt.io/qt-5/macos-issues.html) page makes no mention of CPU/GPU problems.

Let's fix the "sleep' setting and continue to monitor with more information about how you're using DB4S. Work for you?

**Comment by cisoun** [comment]
Hi,

@chrisjlocke 
Yes it triggers the discrete GPU (ATI) right away after the opening. No need to open a database.
I was working a small database (11 tables) and it doesn't seem to use more ressources than having no database open.

@scottfurry
You're right. I'm just wondering why the discrete GPU is trigged, which is often a high consumer of energy. I can also feel it heating but not that much.
Letting SqliteBrowser on background makes the "App Nap" switch to "Yes" after a while though. I can't tell if it is good or not so far.

I will make more tests this afternoon but I the case of yesterday, I saw my battery draining and I noticed OS X pointing SqliteBrowser as a high consumer. I'll post my results later.

**Comment by chrisjlocke** [comment]
I remember a Qt issue of it polling like furry relating to the network.
That was ages ago though.
Could you (but it doesn't explain why its GPU related) disable the network
or stop the Wi-Fi to see if that helps in any way?  You mention you were on
a train, so I assume not connected, but the Wi-Fi might have been on trying
to connect to something...

Thanks,
Chris

>

**Comment by cisoun** [comment]
In fact, I'm using my phone for mobile connection so I did have network but the battery was still draining a little bit faster than usual in this situation. I will do some tests without network anyway to see if it helps.

**Comment by cisoun** [comment]
Hello again,

Here are my results:
- Laps 1 (green): Firefox
- Laps 2,3 (yellow): NPM + PHP Artisan + Atom + Firefox + SqliteBrowser
- Laps 4 (red): NPM + PHP Artisan + Atom + Firefox

<img width="282" alt="Capture d’écran 2019-07-09 à 19 57 30" src="https://user-images.githubusercontent.com/930282/60911781-434ccc00-a284-11e9-8e20-b1503d71242e.png">

As you can see, the battery usage per hour is slightly higher at laps 2 and 3. I wasn't really using SqliteBrowser that much but I still suspect its GPU usage to be responsible of this.

However, I don't think it should be critical and that is just something that I've noticed so feel free to ignore my issue.

What are you thoughts about this ?

**Comment by mgrojo** [comment]
Could be related to  #1233? Just a wild guess, but it could be confirmed if the [last nightly before the change](https://nightlies.sqlitebrowser.org/osx/2017-11/DB%20Browser%20for%20SQLite_20171119.dmg)  works, while the [first nightly with the change](https://nightlies.sqlitebrowser.org/osx/2017-11/DB%20Browser%20for%20SQLite-sqlcipher_20171120.dmg) doesn't.

**Comment by justinclift** [comment]
@cisoun If you're still interested in a solution to this, it should be fixed in our nightly builds from tomorrow onwards. :smile:

**Comment by cisoun** [comment]
@justinclift Great news! I'll take a look. Thanks for the fix! :)

**Comment by justinclift** [comment]
You're welcome. :smile:
