### ISSUE TITLE
Is there a way to merge 2 .sqlite files?

### ISSUE THREAD

**Issue by MrGoatsy** [sqlitebrowser/sqlitebrowser#1936]
What is your question
-----------------------
I have 2 .sqlite files, is there a way to merge them and delete all duplicates?

**Comment by scottfurry** [comment]
Googlefu - "sqlite merge databases"
one of the first results returned:
https://stackoverflow.com/questions/80801/how-can-i-merge-many-sqlite-databases

**Comment by MrGoatsy** [comment]
Does this work with the program?

**Comment by sky5walk** [comment]
The process of merging 2 identical schema databases is not trivial.
You must ensure you do not step on duplicate primary keys.
And more complexity if the schema has multiple tables and foreign keys.
You can attempt all this in the Execute SQL tabs with ATTACH. But, 1st create a series of SQL statements that achieve a stable merge. Then cut and paste the external database paths into the working SQL statements.
Do not delete duplicates in the initial merge. Instead, limit duplicates with DISTINCT queries on the final merged database.
