### ISSUE TITLE
Can't click to follow foreign key that references `rowid`

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [sqlitebrowser/sqlitebrowser#1938]
Details for the issue
--------------------

#### What did you do?

Ctrl + Shift + clicked on a cell in a foreign key column. 

#### What did you expect to see?

The row in the other table that was referenced.

#### What did you see instead?

Nothing happened. Tooltip says:

> References md_runs(KEYWORDASCOLUMNNAME)
> Hold Ctrl + Shift and click to jump there

Useful extra information
-------------------------

The foreign key column is defined as  `FOREIGN KEY(analyzed_run) REFERENCES md_runs(rowid)`.

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ X] Linux: ( _distro:_ Kubuntu)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

**Comment by mgrojo** [comment]
It seems that you've defined a foreign key that is invalid for SQLite according to [documentation](https://www.sqlite.org/foreignkeys.html):

> The parent key is the column or set of columns in the parent table that the foreign key constraint refers to. This is normally, but not always, the primary key of the parent table. The parent key must be a named column or columns in the parent table, not the rowid. 

SQLite shouldn't let you define the table in such way. I tried creating this kind of foreign key and I could do it, but later on any insertion in the table is impossible, unless disabling foreign key checks.

You should define a proper primary for the parent table and use it as foreign key for the child table.

**Comment by Linux-cpp-lisp** [comment]
That was definitely the issue; I defined an explicit primary key and can now follow the foreign key to the other table in DB Explorer. 

Sorry to waste your time with problems actually unrelated to DB Explorer, and thanks for your help!

**Comment by mgrojo** [comment]
Don't worry. I'm pleased to have help you.
