### ISSUE TITLE
Export column to text?

### ISSUE THREAD

**Issue by HydroHydro** [sqlitebrowser/sqlitebrowser#1939]
I'm trying to do something seemingly simple but I can't figure it out. I want to take an entire column in a database and export it as plain text. Is that possible?

**Comment by karim** [comment]
Go to Execute SQL tab. Type `SELECT column_name FROM table_name;` and run this query. It will only show you this column data. Click on the button *Save the results view*. A small menu will appear, select *Export to CSV*. You can change some of the options or leave it with the default settings. Click *Save* button and you are done. :smiley:

**Comment by HydroHydro** [comment]
Thank you! @karim

**Comment by karim** [comment]
You are welcome. :smile: 

I will close this issue now. Feel free to open new issues if you have other questions or need help with anything.
