### ISSUE TITLE
Crash when a table name is empty

### ISSUE THREAD

**Issue by da3moon** [sqlitebrowser/sqlitebrowser#194]
Hi,

My usecase is probably not supposed to happen, but it happened: I unfortunatly added a table with no name. Having this leads to a software crash at startup.

But anyway, thanks for this amazing sowtare!
da3

**Comment by MKleusberg** [comment]
This is an interesting catch ;) I wasn't aware at all that SQLite would allow you to do this. Anyway, the problem should be fixed in the next nightly build, so you can use the database and the table just like any other - that's if I didn't miss anything while testing the patch, of course :smiley:

**Comment by justinclift** [comment]
@da3moon Would you be ok to try the next nightly build (tomorrow), and confirm back to us if it's all working properly now or not?  (download locations for the nightlies are listed on the front page of this repo)

**Comment by da3moon** [comment]
Hi @justinclift , I just tested it, it works. Thanks @MKleusberg for the fast fix !!! (And I corrected my own software as well, so this should no longer happen :+1: )
