### ISSUE TITLE
Sorting by a column should start with upwards sort order

### ISSUE THREAD

**Issue by jondo** [sqlitebrowser/sqlitebrowser#1942]
Details for the issue
--------------------

#### What did you do?
In the Browse Data tab, I clicked the header of a previously unsorted column to sort it.

#### What did you expect to see?
The resulting sort order should show the smallest elements on top, as in 1,2,3 or A,B,C.

#### What did you see instead?
The resulting sort order is backwards (the largest elements get on top), so a second click is needed.

Useful extra information
-------------------------
> DB4S v3.11.99 (Feb 19 2019) [built for x86_64-little_endian-lp64] on Linux Mint 19.1 (linux/4.15.0-54-generic) [x86_64]

(According to the package manager, this is 3.11.1.)

**Comment by mgrojo** [comment]
This is solved in the nightly builds. It was probably fixed by  #1761. That will give you multi-column sorting with Ctrl+Click for free :smile:

**Comment by jondo** [comment]
Thank you, I can confirm this as fixed in "Version 3.11.99 (Jul 24 2019)" from the PPA.
I'm a little unsure about the stability of this "testing" repo, though.

**Comment by chrisjlocke** [comment]
> I'm a little unsure about the stability of this "testing" repo, though

The testing repo is (or should be) solely for testing features and
confirming fixes.  Its not a 'unstable stable' version.  At any point, test
code could wreak havoc or render databases unusable.  We've had 'fixes'
which have caused data loss.
Nightlies should NOT be used in any production or live environment, or on
databases that you don't have a recent backup of.
Maybe the nightlies should stress this more, but I've 'lost' (thankfully
recovered) data through using nightly versions of the software.  Think of
it like a blowtorch where the connecting hose gets changed or tweaked every
now and then.  Don't start peering down the hose wondering what the whistle
noise is.......

**Comment by jondo** [comment]
Thank you for your explanation!
After looking at the status [3.12.0 milestone](https://github.com/sqlitebrowser/sqlitebrowser/milestone/15), I have decided not to wait for the 3.12.0 release to get the improved sorting. So I have locked the package to the current PPA version [with dpkg](https://askubuntu.com/a/18656/447870), checked that my backups are working, and hope for the best ;-)

**Comment by jondo** [comment]
I just noticed that there's another PPA, also by "Gajj GNDU", called [SqliteBrowser Stable PPA](https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser). Should I use this one instead? It has got the sqlitebrowser version `3.11.200-0~2292~201907201457~ubuntu18.04.1`. I guess this also contains the fix?

**Comment by chrisjlocke** [comment]
Interesting that its labelled a stable release - 20 Jul 2019 was obviously
a nightlie version.  Here be dragons...
Anything thats not the 'official' 3.11.2 release should be considered a
nightly.

**Comment by karim** [comment]
> I just noticed that there's another PPA, also by "Gajj GNDU", called [SqliteBrowser Stable PPA](https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser). Should I use this one instead?

This is one of our releases https://github.com/sqlitebrowser/sqlitebrowser#ubuntu-and-derivatives. I don't know why it is called *Stable* though. We should ping @deepsidhu1313 to answer that.

**Comment by deepsidhu1313** [comment]
Stable ppa only contains builds from official release/branch( lets say 3.11.x). 

Testing ppa contains builds from master branch. That means testing ppa builds a new package everytime someone commits code to master.

This is not very detailed answer, but i hope it provides some clarification. 

:)

**Comment by karim** [comment]
Thanks Navdeep for the explanation. :smiley: 

@jondo [Stable PPA](https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser) should have our latest stable version 3.11.2 and [Testing PPA](https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing) we call it nightly. If you are looking for the latest bug fixes/features then you should use the nightly.
