### ISSUE TITLE
Android Cookies File Error Open

### ISSUE THREAD

**Issue by Trixarn** [sqlitebrowser/sqlitebrowser#1944]
Trying to open "Cookies" file exported from android in /data/data folder. I got error "database disk image is malformed, but with another "Cookies" file which is from one year ago works without problems to open. Have android changed something? Tested on android 8.1 and 9.0 and I'm using version 3.11.2.

**Comment by chrisjlocke** [comment]
'Data disk image is malformed' means its a valid database file (SQLite can
open it) but it is damaged - something not quite right is with it.  This
could be something minor like a single index page is wrong, or it could be
more catastrophic.
There is a SQLite command line tool (SQLite itself) where you can dump the
database to a SQL file (a list of SQL commands to rebuild the database).
You can run a PRAGMA integrity_check command, but this only checks for
errors, it doesn't repair anything.  There is no formal repair tool - the
best you can do is export.  Depending on the 'damage', this may or may not
export everything.

**Comment by scottfurry** [comment]
Caveat Emptor - YMMV
https://stackoverflow.com/a/18260642

**Comment by mgrojo** [comment]
@Trixarn I hope we have helped you. I'll close this now, but you can still comment on it if you'd like.
