### ISSUE TITLE
Certificate has expired error

### ISSUE THREAD

**Issue by sultanfarooq1** [sqlitebrowser/sqlitebrowser#1945]
Details for the issue
--------------------

#### What did you do?
Upon opening certificate error occurs

#### What did you expect to see?
No certificate expired error as it is effecting the work i am doing and the integration for some reason is not working

#### What did you see instead
![Untitled](https://user-images.githubusercontent.com/22563540/61984118-7630e700-b01c-11e9-97d2-426fd5a95fdb.png)
?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.16299) [x86_64]
> using SQLite Version 3.27.2
![Untitled](https://user-images.githubusercontent.com/22563540/61984168-a9737600-b01c-11e9-82c5-bdb7c9580b58.png)

> and Qt 5.11.3

**Comment by justinclift** [comment]
Sorry about that.  We haven't yet automated our Lets Encrypt HTTPS cert updating, and I just got busy with other stuff then completely forgot.

New certs have been generated, so we're good for another few months. :wink:

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:

**Comment by justinclift** [comment]
Good point.  It's still a manual process, but I'm a bit more timely with generating the certificates now. :wink:
