### ISSUE TITLE
DB BLACK MODE? 

### ISSUE THREAD

**Issue by Felipeache** [sqlitebrowser/sqlitebrowser#1946]
Describe the new feature
--------------------------
Good day guys!

I just start using DB Browser, do you know where can i find a Dark Mode for it?

Thank you

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by karim** [comment]
Hello.

I believe it is done automatically for you if you are using a dark/night theme on your operating system. More information on this issue #1324.

You forgot to mention your operating system and the version you are using, but you can try our latest nightly version (https://nightlies.sqlitebrowser.org/latest/).

**Comment by mgrojo** [comment]
Release 3.11 follows the style of the operating system, as @karim says.

In the nightlies, there is an option to select our own dark style independent of the desktop style. It can be selected in the Preferences (see #1493). Please, close this if there isn't anything more to consider.

**Comment by Felipeache** [comment]
Thank you Guys!
