### ISSUE TITLE
Generate c# class from table

### ISSUE THREAD

**Issue by OazSoft** [sqlitebrowser/sqlitebrowser#1947]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
is not related to an issue

#### Does this feature exist in another product or project? Please provide a link.
not found in any SQLite browser, but as separate tool

#### Do you have a screenshot? Please add screenshots to help explain your idea.
https://archive.codeplex.com/projects/sqlitetocsharp/fc808136-69c0-4635-91bf-5654f194284c
![fc808136-69c0-4635-91bf-5654f194284c](https://user-images.githubusercontent.com/41877142/62001776-07ec3300-b0b5-11e9-9ea8-5d70f25d38e6.png)

**Comment by scottfurry** [comment]
This subject was broached before in another issue. Generating code from SQLite Table is, IMO, a specialization that is a bit beyond state scope of DB4S. See the commentary to #1853.

**Comment by chrisjlocke** [comment]
I'd have thought This is what plugins and addins are for...

**Comment by datvm** [comment]
Just curious, why don't you just use EF Core? The `Scaffold-Context` works perfectly for that purpose.

**Comment by chrisjlocke** [comment]
Closing this issue, as its a duplicate (of sorts) of #1853.
