### ISSUE TITLE
Can't open NFS mounted directory?

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#1949]
Details for the issue
--------------------

#### What did you do?

Tried to open a database located on remote but locally mounted NFS share.

#### What did you expect to see?

The file

#### What did you see instead?

Nothing

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

Ubuntu 18.04

#### What is your DB4S version?

Version 3.11.99

-----------------------------------------------------

This has always worked in the past, but I've wiped my system and reinstalled. I can't see anything special about what I've done to stop this working.

**Comment by scottfurry** [comment]
Quick Google Search got this -> https://help.ubuntu.com/community/SettingUpNFSHowTo
One thing that jumps out with NFS is the problem with file locking. There are settings that needs to be made on the NFS server configuration to allow remote file locking and creation of temporary files. Other programs have the same problem when trying to open NFS network files.

This is a network issue you should resolve and/or use local copy of database.

**Comment by MKleusberg** [comment]
@shaun-ba Did Scott's link help you? :smile:

**Comment by shaun-ba** [comment]
@MKleusberg No unfortunately a generic documentation for NFS didn't help me

**Comment by MKleusberg** [comment]
No worries :smile: I'd guess it is a locking related issue. These are very common for network file systems and the SQLite developers explicitly warn about using them for SQLite databases: https://www.sqlite.org/atomiccommit.html#_broken_locking_implementations

That said, there seem to be other locking mechanism which we could try using:
https://www.sqlite.org/howtocorrupt.html#_two_processes_using_different_locking_protocols

Can you try using the SQLite command line utility (it should be in the ```sqlite3``` package) to see if that makes a difference? If it does, we can implement it in DB4S :smile: First try to open the file like this:
```sh
sqlite3 /path/to/database.db
```
Then in the tool try this and check if it's printing any error message:
```sql
SELECT * FROM sqlite_master;
.quit
```

If it does show an error, try again but this time using these commands:
```
sqlite3 -vfs unix-dotfile /path/to/database.db

SELECT * FROM sqlite_master;
.quit
```

**Comment by justinclift** [comment]
@shaun-ba Ping? :smile:

**Comment by MKleusberg** [comment]
Closing this because it looks like this we can't do much about this (probably a locking issue on NFS) and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
