### ISSUE TITLE
Parser crashes with complex default values

### ISSUE THREAD

**Issue by qlands** [sqlitebrowser/sqlitebrowser#1950]
The parser crashed with a table with a definition like this:

```
CREATE TABLE IF NOT EXISTS lkpcrop_yield_units(
crop_yield_units_cod varchar(2) NOT NULL, 
crop_yield_units_des varchar(16) , 
rowuuid varchar(80) DEFAULT (hex( randomblob(4)) || '-' || hex( randomblob(2)) || '-' || '4' || substr( hex( randomblob(2)), 2) || '-' || substr('AB89', 1 + (abs(random()) % 4) , 1)  || substr(hex(randomblob(2)), 2) || '-' || hex(randomblob(6))) , 
PRIMARY KEY (crop_yield_units_cod) , UNIQUE(rowuuid));
```
The message is:
Warning: There is something with this table definition that our parser doesn't fully understand. Modifying and saving the table might result in problems.

Version 3.11.99 (Jul 23 2019)
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.9.5
SQLite Version 3.22.0

**Comment by scottfurry** [comment]
@qlands - try the query in this online tool for lint SQL syntax.
https://www.eversql.com/sql-syntax-check-validator/
It complained about the rowuuid DEFAULT text.

There's something about UUID generation I'll dig into, but something doesn't sit right with me on this.

**Comment by scottfurry** [comment]
@justinclift - FYI - if there is demand for UUID, we could consider an SQLite UUID extension.
This came up in a google search - https://github.com/benwebber/sqlite3-uuid
README was rather detailed on different types it can handle.

**Comment by qlands** [comment]
I don't know about https://www.eversql.com/sql-syntax-check-validator/  however the SQLite terminal application, the legacy SQLite DB Manager for Firefox and QT QSQLDriver work fine.

I know that there is a UUID plugin for sqlite. I would love to use it. But if I use it the clients that connect to the SQLite file (ODBC on Windows) have problems with plugins... So the basic concatenation for a like UUID is what I need.

**Comment by scottfurry** [comment]
@qlands - The comment for a UUID plugin was directed at project group. For example, DB4S can be built with SQLCipher for secure SQL databases. There is also a JSON data browsing ability(i.e. in the DB view, you can browser column values - great with blobs that can be interpreted as JPEGs or PNGs). The suggestion is raising  to the group was if we should consider incorporating further functionality. No something for you to do at this moment, other than trying to resolve query syntax.

**Comment by justinclift** [comment]
@scottfurry Awesome.  That UUID plugin does look to have potential. :smile:

**Comment by MKleusberg** [comment]
Thanks, @qlands! This default value is an excellent test case for our parser :smile: I have just fixed two parsing issues (one problem was the fact that there is a calculation with more than one operator in the second parameter here ```substr('AB89', 1 + (abs(random()) % 4) , 1)``` and one was the modulo operator which we for some reason didn't detect yet) and in theory it should be working now. Can you download tomorrow's nightly build (from [here](https://nightlies.sqlitebrowser.org/latest/)) and double check if it is working for you as well? It's also worth checking whether the fix breaks parsing of any other table definition :wink:

**Comment by justinclift** [comment]
@qlands ping?

**Comment by qlands** [comment]
Hi. 

Since I use Linux I did not used any of the nightly builds but I downloaded master from commit [aae2d4](https://github.com/sqlitebrowser/sqlitebrowser/commit/aae2d4dea596072459f3e341689a9d65abc3c557) and the parser works fine.

**Comment by MKleusberg** [comment]
Cool! Thanks for checking, @qlands. I'm going to close this issue then :smile:
