### ISSUE TITLE
question related to issues/1956

### ISSUE THREAD

**Issue by annoying258** [sqlitebrowser/sqlitebrowser#1957]
Questions:
-----------------------

does nightly version have any improvements or work-in-progress related to this?
its weird that the app does change the boxes, but is nowhere near good at it.
another Qt related bug?

### please see sqlitebrowser/sqlitebrowser#1956

---

github shows: `C++ 95.4%`; files in `src` folder are C++.
I wish you best of luck. Since C would have been better.
But there's no good libraries for C for making desktop apps.

Also; there's too many issues compared to PRs
and not enough active contributors.

**Comment by mgrojo** [comment]
It can be said that we are a bit overwhelmed by the success of DB4S. You could help with issue management, if working with C++ is not your kind of thing.

I've answered issue #1956. Please, note that a simple new comment in the same issue would be enough to raise attention to the issue and does not increase the already big number of open issues :smile: I'll close this now to remedy that.
