### ISSUE TITLE
Importing table from CSV is not ordered properly

### ISSUE THREAD

**Issue by Tzontonel** [sqlitebrowser/sqlitebrowser#1958]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by Tzontonel** [comment]
Meh,

The problem was the first letter. The rows with the Lowercase differs from that with Uppercase. My bad :)

**Comment by chrisjlocke** [comment]
> is not ordered correctly

>
Just a nod but a database is just a collection of unordered rows.
Importing has no effect on how records are (or more technically, not)
ordered.

Happy to explain this further if needed, but I'm assuming this is known,
and was more related to the displaying of these records (again, having no
bearing on importing)
