### ISSUE TITLE
Nightly builds not working

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#1959]
Just opening an issue on this, so people hopefully see that there is a problem and we know about it :smile: 

The nightlies don't build correctly since a couple of days. The Windows 64bit nightlies did appear this day but the others still don't seem to work.

To be honest, I didn't follow the only build on updates discussion (#1917). But the commit.txt file for the 32bit build isn't updated either:
https://nightlies.sqlitebrowser.org/win32/commit.txt vs https://nightlies.sqlitebrowser.org/win64/commit.txt

So I don't know what the problem could be :wink: We'll need to ping @justinclift for that :innocent:

**Comment by justinclift** [comment]
Looks like it's working ok again.  Updated macOS on the build server a few days ago, but forget to start the build VMs afterwards.  Noticed it last night, started the VM's, and manually launched the Win64 builder.  But then went and got sleep.

Checking the nightlies dir now, things seems ok. :smile:

**Comment by MKleusberg** [comment]
Awesome, thank you! :smile: I'm closing this issue then. And yeah, same for me with the GitHub notifications :wink:

**Comment by sky5walk** [comment]
Sorry, no nightly as of 191108?

**Comment by justinclift** [comment]
Yeah, the ethernet cable (+ port) that plugs into the build server is being used for something else temporarily. :wink:

I'll buy an 8 port switch sometime in the next few days to replace the 4-port one it's currently plugged into.
