### ISSUE TITLE
Foreign-key check works on sqlitebrowser, but the same query when executed from python inserts a record into child table by violating the foreign key 

### ISSUE THREAD

**Issue by ramesh247ntt** [sqlitebrowser/sqlitebrowser#1960]
Details for the issue
--------------------

#### What did you do?
Foreign-key check works on sqlitebrowser, but when the same query is executed from python insert statement using sqlite3 module a record is  added to child table by violating the foreign key constraint.

#### What did you expect to see?
Python code should fail, because user is trying to insert into child table where there is no corresponding entry in parent table. 

#### What did you see instead?
When python code is executed, a record is inserted into the table without checking foreign key.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ ) 10

#### What is your DB4S version?

- [ ] 3.11.2

#### Did you also
No

**Comment by ramesh247ntt** [comment]
---supplier_groups Parent table
CREATE TABLE IF NOT EXISTS supplier_groups (
	group_id integer PRIMARY KEY,
	group_name text NOT NULL
);

--- Suppliers table Child table
CREATE TABLE IF NOT EXISTS suppliers (
	supplier_id integer PRIMARY KEY,
	supplier_name text NOT NULL,
	group_id integer NOT NULL
);
----------------------------------------------------------------
Data insertion
------------------
---insert data to parent table
INSERT INTO supplier_groups (group_name)
VALUES
	('Domestic'),('Global'),('One-Time');

---insert data into child table (This Works as id = 2 is present in parent table)
INSERT INTO suppliers (supplier_name, group_id)
VALUES
	('HP', 2);

------insert data into child table (This should not work as id = 4 is not present in parent table)
INSERT INTO suppliers (supplier_name, group_id)
VALUES
	('ABC Inc.', 4);

if i execute above insert query in sqlite browser it returns a valid error, but if i try to execute the same query though python method sqlite simply accepts the data entry and breaks the relationship.

**Comment by MKleusberg** [comment]
By default foreign key checks are disabled in SQLite. So you have to activate them if you want SQLite to check them. Unlike some other settings the foreign key flag isn't stored in the database file either, so you have to enable them every single time you open your database file (usually that is once at the start of the script). DB4S/SQLiteBrowser is doing exactly the same thing. After opening a new database file, one of the first things we do is enable the foreign key checks.

You can do so by using the [```foreign_keys``` pragma](https://sqlite.org/pragma.html#pragma_foreign_keys):
```sql
PRAGMA foreign_keys = 1;
```
Just execute that SQL statement before your first ```INSERT``` statement and it should work :smile:

**Comment by MKleusberg** [comment]
Closing this because I assume the original question is answered. If you're still having any problems with this, you can still comment on this issue or re-open it :smile:
