### ISSUE TITLE
[FeatureRequest] Enable 'duplicate current Execute SQL tab'

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1964]
Describe the new feature
--------------------------
I could really use a speed up menu item to duplicate the current Execute SQL tab I am working on. Now I have many many clicks and navigating for a simple copy operation.

Additional info
---------------
I must add new SQL tab. Copy the SQL text contents from another. Paste into new tab. Copy name of prior SQL tab. Paste into new tab and edit it the name. Then edit the SQL contents.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
Yes. Chrome supports duplicating tabs.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No.

**Comment by scottfurry** [comment]
Sort of like the browser action of right click tab -> "duplicate tab" functionality?

**Comment by sky5walk** [comment]
Yes 👍

**Comment by MKleusberg** [comment]
Thanks for the suggestion, @sky5walk! I have just added a menu option for this. As usual, can you check tomorrow's nightly build and see if it's working as expected? :smile: With the new version you should be able to right click on a tab and click "Duplicate Tab" in the context menu.

**Comment by sky5walk** [comment]
Thanks, the context menu works. 👍 Big time saver!
Now that we have localized context menu items: close,duplicate,rename;
I'll make a request to remove the SQL1(x) close button on every tab.
It is soooo easy to hit that by mistake with high res screens. And when I have more than 10 tabs, the left-right scroll buttons become obscured and overlay with the close (x).

**Comment by sky5walk** [comment]
Side request: Can you modify the naming of duplicated tabs?
I am hitting backspace a lot now 😢 
Why not: 
SQLtab SQLtab(2) SQLtab(3) etc.?
Instead of:
SQLtab SQLtab(duplicate) SQLtab(duplicate)(duplicate) SQLtab(duplicate)(duplicate)(duplicate) etc.?

**Comment by MKleusberg** [comment]
Makes sense! The next nightly build changes it to "tab (n)" :smile:

**Comment by sky5walk** [comment]
Works great! 👍

**Comment by MKleusberg** [comment]
Awesome :smile:
