### ISSUE TITLE
[Bug] Exported header affected by user column sorts.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1967]
Details for the issue
--------------------
If a user clicks a column to sort it, an up-down arrow is placed beside the column label.

#### What did you do?
I select some rows in my table and then execute [Ctrl]+[Shift]+[c] to copy those rows + header into the clipboard.

#### What did you expect to see?
"nid	id	fname	sha3	file"
"blah blah blah blah blah"

#### What did you see instead?
"nid	id ▾¹	fname	sha3	file" --< The down arrow shows up in my data 😢 
"blah blah blah blah blah"

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_10 Pro latest___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: ___3.11.99

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
I had already noticed this and fixed it in 9327d512a9548eaf9a40899cdfdf2d4d18dac83c so it should be in the latest nightly.

**Comment by sky5walk** [comment]
Thanks, it works. 👍
