### ISSUE TITLE
[Feature Request] Drop close buttons on every Execute SQL tab(x).

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1968]
Describe the new feature
--------------------------
Now that we have localized context menu items: close,duplicate,rename; 😋 
It really makes sense to remove(or make optional) the SQL1(x) close button on every tab.
It is soooo easy to hit that by mistake with high res screens. And when I have more than 10 tabs, the left-right scroll buttons become obscured and overlay with the close (x).

Additional info
---------------
This is also a bug report given the scrunched scrollbar buttons with many SQL tabs.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
Yes, Notepad++ and other multi-tab environments allow disabling close buttons.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![SQL-tab-scrollbar-scrunch](https://user-images.githubusercontent.com/13093122/63188577-b689f080-c02f-11e9-8bba-1a4fca1f2818.PNG)

**Comment by justinclift** [comment]
Sounds reasonable. :smile:

**Comment by MKleusberg** [comment]
Quick poll: Should we add a checkbox to the Settings dialog for this, and if so, what should be the default? Or should we remove the close buttons and add a single button for closing the current tab (that's what I'm leaning towards)? Or should we just remove the close buttons altogether?

**Comment by mgrojo** [comment]
I like close buttons in the tabs. It's better when you have to close a lot of open tabs. So I'd prefer a setting and default to current behaviour. A single button for closing the current tab is a good idea for the other option of the setting. The main tabs should probably follow this setting too.

**Comment by mgrojo** [comment]
> And when I have more than 10 tabs, the left-right scroll buttons become obscured and overlay with the close (x).
> 
> This is also a bug report given the scrunched scrollbar buttons with many SQL tabs.

> ![SQL-tab-scrollbar-scrunch](https://user-images.githubusercontent.com/13093122/63188577-b689f080-c02f-11e9-8bba-1a4fca1f2818.PNG)

That seems a problem with the style https://github.com/ColinDuquesnoy/QDarkStyleSheet I'll try updating it and if it still happens, we should report it there.

**Comment by sky5walk** [comment]
Thanks!
My preference and philosophy is always more editable real estate.
Meaning, less manual scrolling and less distracting images for the 90% work mode.
(Maybe 10% or less of the time is spent browsing menus after a user becomes proficient in any app.)
Eliminating crowded close buttons reduces mouse accuracy required while navigating the gui.
As the number of SQL tabs increase, the potential to mis-click a close button increases and forces the user to stop and think about minutiae. The context menu is a big improvement as it is near impossible to enter by mistake.

**Comment by sky5walk** [comment]
> > And when I have more than 10 tabs, the left-right scroll buttons become obscured and overlay with the close (x).
> > This is also a bug report given the scrunched scrollbar buttons with many SQL tabs.
> 
> > ![SQL-tab-scrollbar-scrunch](https://user-images.githubusercontent.com/13093122/63188577-b689f080-c02f-11e9-8bba-1a4fca1f2818.PNG)
> 
> That seems a problem with the style https://github.com/ColinDuquesnoy/QDarkStyleSheet I'll try updating it and if it still happens, we should report it there.

Ok, latest nightly appears better but there are still overlapping buttons. Except now there is a visible highlight box around the left or right horizontal scrollbar. Much easier to tell what to click. 
Possible fixes:
-Shrink the tab width for any tab right of the scrollbar.
-Move the scrollbar permanently to the leftmost position of the list. It will never overlap.
-Do not show any tabs >= scrollbar position.

**Comment by mglatz** [comment]
I also vote for setting. I too have accidentally closed tab I really wished to keep

**Comment by sky5walk** [comment]
Wow, I forgot to mention, due to tab crowding, I cannot reliably scroll left and right. 😨 
Can we please drop the Close buttons for a trial run? It is a mess.
This is what the nightlies prove out.

**Comment by MKleusberg** [comment]
Yep, let's try it :smile: Can you try the next nightly build? It drops the close buttons for the main tabs and the Execute SQL tabs, and adds a close tab button to the Execute SQL tab bar.

**Comment by sky5walk** [comment]
Whoa 🌜  Almost there.
The clutter is gone, but the added close tab on the end [<][>][X] causes the same inadvertent loss of a SQL tab. Please drop the close button altogether. We have [right mouse click] menu and [Ctrl+W]. I can barely see the navigate left arrow due to the close button dominating the real estate.

**Comment by justinclift** [comment]
As long as it's an option.  Personally, I use those close buttons. :smile:

**Comment by sky5walk** [comment]
Yes, an option is fine. Projects with < 5 or so SQL tabs will not see this problem. With more SQL tabs and long names, the scrunch is scary.

**Comment by karim** [comment]
I think removing the close button is fine and could be the default option. Tabs can be closed using the mouse middle button.

We should also add a toggle to show it since some users (who don't open a lot of tabs) might prefer it. I see this pattern in a lot of apps.

**Comment by sky5walk** [comment]
Issue #2155 prompted me to load the latest nightly to see if this was fixed.
The scrunched view of the left and right arrows <| |>[x] still exists.
Make the tab bar full or reduce the window width to see the scrunch.

**Comment by beRto-** [comment]
Sorry for the noise in opening #2155 and thanks to @sky5walk for redirecting me here.

If I understand correctly, there should be an option to "re-enable" the X-on-each-tab setup? I don't see this anywhere - can someone please direct me to it?

It's also not clear to me why the default behavior would be to remove the X-on-each-tab? This seems like a regression / deviation compared to other major examples I have seen (e.g. Chrome, Firefox, MS SMS) all have the x on each tab.

**Comment by sky5walk** [comment]
Sorry, but why are you asking to increase the visual noise?
You want users to accidentally close tabs by guessing where to click?
Your compromise being more prompts, "Are you sure?" EVERY TIME?
Please study the problem in more depth before claiming regression. 🤔 
I am disappointed in any argument that starts, "But the other guys do it this way.".

**Comment by beRto-** [comment]
To be clear, I'm not trying to be argumentative. I really enjoy using DB4S and am grateful this useful tool exists. Provided I could turn the old functionality back on (and I don't see an option for this?), I'd be happy either way.

DB4S is a clean, simple tool. That's what makes it a pleasure to use! In my view, the new setup using a shared X is not intuitive for most people and therefore a step in the wrong direction. I feel this new setup optimizes the default view for the wrong use case (power users who happen to have dozens of tabs open at the same time).

The "other guys doing it this way" are the biggest names around, so it's prudent to tread carefully when going a different direction. The new DB4S setup deviates from well-established convention and I personally do not find another example of a multi-tab program that does not have the x on each tab by default. In my opinion, the details provided in this thread do not provide sufficient rationale for violating such a strong convention.

For example, it's stated that Notepad++ allows a user to turn off (I agree, there is a checkbox in Preferences to "show close button on each tab"). But the Notepad++ default is to have the X on each tab enabled. (And turning it off does not replace it with a shared X.)

I guess I agree that DB4S should be optimized for the 90% use case, but I disagree on what that most common scenario looks like. I would argue the case of having dozens of tabs open at the same time is the rare case. That's the setup that should require customization and preference tweaking. I suspect the more typical use case is having <10 tabs open (especially for newer users), and under that scenario the x-on-each-tab is useful and added clutter is trivial.

The x-on-each-tab is much more clear on what that x does. A single shared x is ambiguous - does it close just the current tab? does it close all the tabs? A power user will know, and that's why I think turning off the x should require the extra step of selecting this new GUI setup. Everyone else should get the well-established convention that is used in most places, and that DB4S users are already familiar with.

**Comment by sky5walk** [comment]
Sometimes argumentative is all that works.
I don't mind if there is an option similar to Notepad++, (I also drop the busy [x]'s from every tab).
I do not remember why the devs opted out of that approach?
However, you continue to "whine" about defaults without actually observing the error that occurs with 2 or 3 open tabs and window resizing. Where is it defined 5 or 10 open tabs is power use? That is normal use in DB4S projects. Else, why do projects exist?
If I must continue to argue in your vein, look to Excel's open worksheets tab.
Do you see [x] buttons on each?
Please study the problem as every user instead of your perceived preference.

**Comment by beRto-** [comment]
I see the error, I just think it's a separate issue.

I agree that if I have many tabs open, each saved with a long name, and then resize my window down from full screen, the scroll buttons overlay the tab [x]. I agree that's not good. I don't agree that getting rid of the [x] is the right fix for that problem - in fact, I think getting rid of the [x] is a completely unrelated UI decision.

If the goal is to fix the scroll button overlap error, then the right approach is to prevent the scroll buttons from overlapping the tabs in the first place. Getting rid of the [x] only solves it in a roundabout way. So now we've fixed this relatively rare overlap problem (sort of - the scroll buttons _still_ partially obscure the last tab), but introduced confusion and broken established conventions. I don't see that as a good trade.

In the end, I defer to the DB4S team on this and will be fine either way. I am just trying to offer what I hope is helpful and constructive criticism from a long-time fan and daily user of the software.

**Comment by sky5walk** [comment]
The devs are using a QT gadget lib with this behavior. It is not an owner drawn gadget/panel.
To minimize time to a solution, they dropped the many [x]'s and added a context menu and a singular trailing [x]. They also submitted bug reports to the QT team.
You are requesting to resurrect the (user dependent) scrunch effect via a preference setting.
That is an acceptable approach. Arguing the merits of this or that UI is incredibly subjective and therefore not productive.

**Comment by mgrojo** [comment]
A middle solution could be to hide the close button in all the tabs except the current one. It's easy to implement, but the width of the tab is not reduced, so there is no gain in the available space.

![imagen](https://user-images.githubusercontent.com/13812910/76170309-00c7f000-6181-11ea-96ba-a9dd892db994.png)

Unless there is a consensus around this option, I would favour having a new setting to switch between the two or three options (button in all tabs, button only in corner and, maybe, button only in current tab). This was also suggested by @MKleusberg.

For the related issue about the scroll buttons when the space is not enough, I tried updating the QDarkStyleSheet, but we'd have a worse problem with comboboxes with icons (like the Table in "Browse Data"). I think it's https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/169, although it means that it happens also in other platforms (at least in Linux).

**Comment by sky5walk** [comment]
Yes, I like it! 
And it clearly shows which tab is current.
Please drop the ugly trailing [x] as that would be superfluous.

**Comment by mgrojo** [comment]
I've finally updated to QDarkStyleSheet 2.8 and the problem with the scroll buttons in tab bar is fixed (although the tabs are still visible in the margins of these buttons):
![imagen](https://user-images.githubusercontent.com/13812910/76172582-e3525080-6197-11ea-9aa9-e587900c6bcf.png)


I've applied the workaround recommended in https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/169 for combo-boxes with icons.

@sky5walk could you confirm with tomorrow's nightly that it's the same for you?

> Yes, I like it!
And it clearly shows which tab is current.
Please drop the ugly trailing [x] as that would be superfluous.

Ok. That change is not yet committed. I'd like to wait for @MKleusberg's opinion, since he implemented the corner button and there is still an advantage in that solution and it is that the necessary space for the tabs is reduced. Martin, maybe you have some idea to get the best of both options. These are the necessary changes to hide the buttons in non-current tabs:

```diff
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index f1b833a9..7a7918a2 100644
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -343,6 +343,20 @@ void MainWindow::init()
     });
     ui->tabSqlAreas->setCornerWidget(buttonCloseSqlTab);
 
+    connect(ui->tabSqlAreas, &QTabWidget::currentChanged, [this](int currentIndex) {
+        QTabBar *tabBar = ui->tabSqlAreas->tabBar();
+        QWidget *button;
+        if (tabBar) {
+            for (int i = 0; i < ui->tabSqlAreas->count(); ++i) {
+                button = tabBar->tabButton(i, QTabBar::RightSide);
+                if (button) {
+                    const bool visible = i == currentIndex;
+                    button->setVisible(visible);
+                }
+            }
+        }
+    });
+
     // If we're not compiling in SQLCipher, hide its FAQ link in the help menu
 #ifndef ENABLE_SQLCIPHER
     ui->actionSqlCipherFaq->setVisible(false);
diff --git a/src/MainWindow.ui b/src/MainWindow.ui
index 03b31430..2ebf4418 100644
--- a/src/MainWindow.ui
+++ b/src/MainWindow.ui
@@ -39,6 +39,9 @@
       <property name="currentIndex">
        <number>0</number>
       </property>
+      <property name="tabsClosable">
+       <bool>true</bool>
+      </property>
       <property name="movable">
        <bool>true</bool>
       </property>
@@ -721,14 +724,17 @@ You can drag SQL statements from an object row and drop them into other applicat
         </item>
         <item>
          <widget class="QTabWidget" name="tabSqlAreas">
+          <property name="contextMenuPolicy">
+           <enum>Qt::CustomContextMenu</enum>
+          </property>
           <property name="currentIndex">
            <number>-1</number>
           </property>
-          <property name="movable">
+          <property name="tabsClosable">
            <bool>true</bool>
           </property>
-          <property name="contextMenuPolicy">
-           <enum>Qt::CustomContextMenu</enum>
+          <property name="movable">
+           <bool>true</bool>
           </property>
          </widget>
         </item>
```

**Comment by sky5walk** [comment]
Ok, I am thinking the [left] [right] arrows can grow if the trailing [x] is dropped.
And you now have a singular close [x] button for the current tab.
Having both just wastes real estate.
Glad the dark theme is better now.

**Comment by sky5walk** [comment]
Did your commit go through or are you still waiting for reply from @MKleusberg?
Also, I see the nightlies now populate almost daily.
I thought it would only generate new binaries for git changes or commits?

**Comment by justinclift** [comment]
> Also, I see the nightlies now populate almost daily.

The MacOS ones are still every night.  The Windows ones are still building only when something has changed.

That being said, when I'm debugging a build issue on the Windows VM I generally comment out the code that checks if the nightly should be skipped.  Sometimes I've forgotten to re-enable it again, thus building extra nightlies until I remember.  Just checked, to be safe, and nah, the code is still running as it should  It just means there have been changes to the source most days this month. :smile:

**Comment by sky5walk** [comment]
Ok, it would be nice to have that git report appended/replace to a readme.md or somesuch in the download folder. It is hard to imagine but welcome to have so many features implemented. It helps to know the reason for any new nightly binaries. 😃

**Comment by karim** [comment]
I don't think hiding the close button on a single tab, or even a few tabs a good user experience. Also it will now require two actions to close a tab...

- Right-click then select close (if X button is hidden on all tabs)
- Click on the tab to switch to it to make the X button appear then click it (if X button is only shown on active tabs)

As we can see in this issue and others that some users prefer having the X button and some don't, I think having a toggle in preference is the best option.

**Comment by sky5walk** [comment]
Yes! If we do eventually get a preference setting, then I prefer no [x]'s or [left][right] arrows mucking up the tabbed display. I can easily navigate with the keyboard and never accidentally close my SQL tabs. 😠

**Comment by sky5walk** [comment]
Ok, the scrunch is gone but so is the elegance! 
Look how tiny the [left][right][x] targets are in a High DPI and Dark theme mode. 😢 
![image](https://user-images.githubusercontent.com/13093122/76684170-0b9ade80-65e0-11ea-935c-ba41d48e8ed4.png)
The same image in standard 100% DPI is slightly better:
![image](https://user-images.githubusercontent.com/13093122/76684301-2a4da500-65e1-11ea-91dd-4a09b2b7c1e5.png)
I say again, how can I know which tab the [x] applies to? Yes, the tab is supposedly highlighted, but the subtle difference requires too many brain clock cycles to differentiate.
Please expand the width of the [left][right] arrows and drop or move the [x] button to the currently focused tab.

**Comment by justinclift** [comment]
As a data point, I was using DB4S built from the latest code a few days ago, and **really** missed having the [x] buttons on the tabs. :frowning:

**Comment by mgrojo** [comment]
Yes, this is controversial. Would hiding of the button in non-current tabs fit all users' preferences, or should we make it an option with the following values?:
- Close button in all tabs
- Close button only in current tab
- Single close button in right corner

**Comment by sky5walk** [comment]
The single close button is useless.
Please just enable preferences to mimic other apps like Notepad++
All close buttons or none.
The interest to me is more real estate and no false clicks.

**Comment by justinclift** [comment]
Personally, I'm not bothered which way, as long as there's an obvious way to close lots of tabs fairly quickly.  I'd totally forgotten about this stuff, so when I compiled from the new code... not having the close buttons there was confusing for a bit. :wink:

**Comment by MKleusberg** [comment]
To me this sounds like we should have a switch in the preferences and only allow 1) close buttons on all tabs or 2) single close button in the corner. Personally, I'd rule out these options: 3) Single close button on the active tab because of the additional maintenance for us and 4) no close buttons at all because it might confuse most users.
Or should we have a vote first?

**Comment by chrisjlocke** [comment]
> Or should we have a vote first?

And get 16 viable solutions! ;)

Personally, Chrome and Firefox are the 'main' browsers (on Windows, at least) so emulating how they do their tabs (a close button on each tab) at least is familiar.  If we go down the option route, we're going to have an option for everything... 
Right clicking a tab brings up the option to close just that tab or a bunch of them

![image](https://user-images.githubusercontent.com/7872218/81175178-f8cad780-8f9a-11ea-96df-9dd0fe24fe91.png)

**Comment by MKleusberg** [comment]
That's a valid point. So if it is the option route, it would more be between close buttons on all tabs or on no tabs then.
I was thinking about Chrome and Firefox too but think the tab bar is probably one of the UI elements with more plugins to change the look and feel for every user :wink:

**Comment by sky5walk** [comment]
To reiterate, DB Browser for SQLite should not be compared to Chrome or a web browser.
It is more like Excel and Notepad++.
Please use these as comparisons for GUI elements.
Optional(all or none) is fine by me, but please no stray scrunched close buttons.

**Comment by beRto-** [comment]
For what it's worth, I agree the single button waaay over there is hidden and confusing. I would also vote for the simple Notepad++ style on/off option (show on all tabs, or show on none).

**Comment by justinclift** [comment]
Yeah, at least at the moment, I personally prefer having the close buttons on all the tabs.  So as long as that's one of the options, I'm happy. :smile:

**Comment by mgrojo** [comment]
> 
> 
> To me this sounds like we should have a switch in the preferences and only allow 1) close buttons on all tabs or 2) single close button in the corner. Personally, I'd rule out these options: 3) Single close button on the active tab because of the additional maintenance for us and 4) no close buttons at all because it might confuse most users.
> Or should we have a vote first?

Marting has you missed my comment https://github.com/sqlitebrowser/sqlitebrowser/issues/1968#issuecomment-596262575 ? To me It passes my threshold of maintenance level, but that's very subjective. Besides, I prefer it to the corner close button, which is unusual GUI style.

The only drawback with that solution is that we don't take back the space used by the close button, since it is only hidden. I'd go for the three options mentioned in https://github.com/sqlitebrowser/sqlitebrowser/issues/1968#issuecomment-623126681

**Comment by mgrojo** [comment]
The next nightly build will have a preference setting for having close buttons on tabs as in 3.11 and before, or not. The corner button has been removed, since we have the contextual menu and the shortcut (Ctrl+W). Please confirm it works as expected, since we have to include this in the final 3.12 version.

**Comment by sky5walk** [comment]
Nightly v200603 works great! No more unsightly scrunched [x] buttons. 💯
