### ISSUE TITLE
Database Structure not displayed

### ISSUE THREAD

**Issue by cimperia** [sqlitebrowser/sqlitebrowser#1969]
I ran this DDL statement

```
CREATE TABLE [my_table] (
  [id] INTEGER NOT NULL  
, [r_type] NVARCHAR(1) NOT NULL CHECK (r_type IN ('A','P','S')) DEFAULT ('S') -- RESOURCE TYPE Array, Plural, Single
, [symbol] NVARCHAR(50) NOT NULL
, [default_text] NVARCHAR(4000)
, CHECK ((r_type = 'S' AND default_text IS NOT NULL) OR (r_type IN ('A', 'P')))
, CONSTRAINT [PK_Keys] PRIMARY KEY ([id])
, CONSTRAINT [UK1_Keys] UNIQUE ([symbol])
);
```

The my_table is listed under the "Database Structure" tab, but the table columns are not listed, ie there's no chevron and the structure cannot be expanded and it's not possible to generate a CREATE statement for it.

#### What operating system are you using?

- [x] Windows: ( _version:_ 10___ )

#### What is your DB4S version?

- [x] 3.11.2

**Comment by justinclift** [comment]
Interesting.  Some of those aren't native SQLite data types, but SQLite will mostly figure things out ok anyway.  It sounds like the `CREATE TABLE` statement worked, so (in theory) we should display whatever's there.

As a thought, would you be ok to try the latest nightly build and see what happens?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If the bug is still present with that, we'll want to fix it. :smile:

If it works

**Comment by cimperia** [comment]
Hi Justin,

 

I tried the latest night version you suggested and it did not work.

 

Thank you for that excellent piece of software!

 

Best 

Claudio

**Comment by justinclift** [comment]
You're welcome Claudio, thanks for trying that out. :smile:

Sounds like this bug is still present, and we'll need to look into it. :wink:

**Comment by MKleusberg** [comment]
This is caused by a bug in our grammar parser. It stumbles upon this part of the statement:
```sql
CHECK ((r_type = 'S' AND default_text IS NOT NULL) OR (r_type IN ('A', 'P')))
```

I'll need to see how I can fix this. But some day I think we will need to rewrite the parsing of expressions entirely...

**Comment by cimperia** [comment]
OK. Thanks. It explains why the following DDL triggers the same issue:

CREATE TABLE [Translations_Children] (
  [id]           INTEGER NOT NULL  
, [trans_id]     INTEGER NOT NULL -- FK
, [key_child_id] INTEGER NOT NULL -- FK
, [text]         NVARCHAR(255) NOT NULL
, [quantity] NVARCHAR(20) NULL CHECK (quantity IS NULL OR (quantity IN ('zero', 'one', 'two', 'few', 'many', 'other')))
, CONSTRAINT [PK_Translations_Children]  PRIMARY KEY ([id])
, CONSTRAINT [FK_Translations_Children]  FOREIGN KEY ([trans_id]) REFERENCES [Translations]([id]) ON DELETE CASCADE
, CONSTRAINT [FK_Translations_Children2] FOREIGN KEY ([key_child_id]) REFERENCES [Keys_Children]([id]) ON DELETE CASCADE
);

**Comment by justinclift** [comment]
> I think we will need to rewrite the parsing of expressions entirely...

Yeah.

**Comment by MKleusberg** [comment]
Yes, it's the same issue in your second table, again in the CHECK constraint. I think I finally came up with a fairly good solution for this though which hopefully avoids similar problems in the future too :wink: Can you download tomorrow's nightly build ([download link](https://nightlies.sqlitebrowser.org/latest/)) and double check if it's working for you as expected, @cimperia? :smile:

**Comment by cimperia** [comment]
I downloaded the 64 zip version (Version 3.11.99 (Aug 19 2019)).  The results are encouraging but it looks like there's still a problem with this check constraint:

`CHECK ((r_type = 'S' AND default_text IS NOT NULL) OR (r_type IN ('A', 'P')))`

This DDL, with a Table Check Constraint, will trigger the same issue:

```
CREATE TABLE [mytable] (
  [id] INTEGER NOT NULL  
, [r_type] NVARCHAR(1) NOT NULL 
, [symbol] NVARCHAR(50) NOT NULL
, [default_text] NVARCHAR(4000)
, CHECK ((r_type = 'S' AND default_text IS NOT NULL) OR (r_type IN ('A', 'P')))
, CONSTRAINT [PK_Keys] PRIMARY KEY ([id])
, CONSTRAINT [UK1_Keys] UNIQUE ([symbol])
);
```

**Comment by MKleusberg** [comment]
The new nightlies weren't built yet :smile: It always takes up to 24 hours until there are new binaries with the last changes. The new version which hopefully parses your CHECK constraint correctly will be there in ~4-5 hours from now. The download link is the same.

**Comment by cimperia** [comment]
Perfect ! Thank you!

**Comment by MKleusberg** [comment]
Well, thank you for reporting this :smile: If you happen to have any other tables with parsing issues feel free to open more issues :wink:
