### ISSUE TITLE
Default Location field can't be changed in v3.5.0 on OSX

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#197]
As reported here (and confirmed by myself just now), the "Default Location" preference value can't be changed.  The text field can't be typed into, and the "clickable" button doesn't open a dialog.

&nbsp; &nbsp; https://twitter.com/umeya_mann/status/562772757021491201

![b9hkk02ccaigrwg](https://cloud.githubusercontent.com/assets/406299/6084142/76fa04ac-ae26-11e4-9ca3-ab8f16ac32e6.png)

We may want to do a 3.5.1 or 3.6.0 shortly after fixing this. :wink:

**Comment by samir-aguiar** [comment]
Ohh, that's on me, that's probably caused by ae03113. Sorry about that, I'm taking a look.

**Comment by justinclift** [comment]
Thanks. :smile:

**Comment by samir-aguiar** [comment]
@justinclift I think this should fix it! Sorry about that!

**Comment by justinclift** [comment]
Awesome Samir, yep, that fixed it. :smile:

@MKleusberg @rp- I'd like to get this fix into a main release very quickly.  @rp- Do you have time to build a new windows release in the next few days?  I can do the OSX bits, release notes, etc. :smile:

**Comment by rp-** [comment]
We might want to merge a few more bug fixes into 3.5.1 (csv import, ...)
But yeah I can build a windows version tomorrow.

**Comment by Z4us** [comment]
t seems I had a vision a few days ago. Thank you, rp et al ;-D

**Comment by justinclift** [comment]
@rp- Yeah, I reckon we should include all of the bug fixes since release. eg the CSV import off-by-one bug, the support for empty table names, both of @samir-aguiar's PR's, etc

**Comment by rp-** [comment]
draft is up.

**Comment by justinclift** [comment]
@rp- Thanks, that's Awesome. :grinning:

**Comment by justinclift** [comment]
3.5.1 is released: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.5.1
