### ISSUE TITLE
Immediate crash when attempting to view HTML

### ISSUE THREAD

**Issue by aswxxx** [sqlitebrowser/sqlitebrowser#1970]
Details for the issue
--------------------

#### What did you do?

Attempted to preview [this HTML (NSFW?)](https://pastebin.com/52iuqJfD) in a field by left clicking it in the table view.

#### What did you expect to see?

HTML or text preview in the rightmost preview area.

#### What did you see instead?

Upon selecting the field, DB4S immediately crashes.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ Windows 10 1903/18362.295 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: 

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds (tried 8/19/19)
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
I could not reproduce this in Ubuntu Linux 18.04, neither using:

> Version 3.11.2
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

nor using:

> Version 3.11.99 (Aug 18 2019)
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.9.5
SQLite Version 3.15.2

It seems something Windows-specific or dependent on the Qt version. Could you paste the version information from the About window?

**Comment by aswxxx** [comment]
Main version:

> Version 3.11.2
> Built for x86_64-little_endian-llp64, running on x86_64
> Qt Version 5.11.3
> SQLite Version 3.27.2

Nightly version:

> Version 3.11.99 (Aug 19 2019)
> Built for x86_64-little_endian-llp64, running on x86_64
> Qt Version 5.11.3
> SQLite Version 3.28.0

**Comment by SilvioGrosso** [comment]
Hello everyone,

Just tried to reproduce this crash on Windows 10 (Home edition)
Nightly builds (32 zip portable):
Version 3.11.99 (Aug 19 2019)
Built for i386-little_endian-ilp32, running on x86_64
Qt Version 5.7.1
SQLite Version 3.28.0

NO crash whatsoever. 
I have also tried different modes to visualize the HTML content: text, xml, json, binary etc.

Here is the screenshot:
<img width="960" alt="db-browser" src="https://user-images.githubusercontent.com/33007383/63321234-6311ee00-c320-11e9-9304-f9bc62bc2f7c.png">

**Comment by aswxxx** [comment]
Are there PDBs available anywhere so I can debug this? In the meantime I'm attempting to build it from source.

**Comment by scottfurry** [comment]
For @aswxxx, idle thought occurs to me. HTML(and xml) can be quite picky when it comes to formatting (CR's, LF's, tags, etc). Has target file been 'linted'?
For XML, see here: http://xmlsoft.org/xmllint.html 
For HTML, see here: https://github.com/htmllint/htmllint

For @mgrojo, does DB4S "lint" (or otherwise check validity) of an xml file?

Regardless of the cause of the crash, this situation, from my viewpoint, would seem to suggest some kind of pre-import check could be accomplished prior to paring for data. (Assuming xml/html validity is not done). "Let an external library do some heavy lifting so we don't have to code" seems like a prudent philosophy.

**Comment by aswxxx** [comment]
@scottfurry no, the file has not been linted. It is HTML straight from the web.

As for the crash, I just attached VS to DB4S (without setting up PDBs), and here's something interesting that perhaps suggests some sort of misconfiguration on my system:

Output window:
```
Cannot mix incompatible Qt library (version 0x50a01) with this library (version 0x50b03)
Unhandled exception at 0x00007FF83A6BD33E (ucrtbase.dll) in DB Browser for SQLite.exe: Fatal program exit requested.
```

Call stack:
```
>	ucrtbase.dll!abort()	Unknown
 	Qt5Core.dll!QCoreApplicationPrivate::qmljsDebugArgumentsString() + 170 bytes	Unknown
 	Qt5Core.dll!QMessageLogger::fatal() + 145 bytes	Unknown
 	Qt5Core.dll!QObjectPrivate::QObjectPrivate() + 124 bytes	Unknown
 	Qt5Svg.dll!QSvgRenderer::QSvgRenderer() + 48 bytes	Unknown
 	qsvg.dll!qt_plugin_query_metadata() + 73 bytes	Unknown
 	qsvg.dll!00007fffea401117()	Unknown
 	Qt5Gui.dll!QImageReader::canRead() + 2260 bytes	Unknown
 	Qt5Gui.dll!QImageReader::imageFormat() + 1152 bytes	Unknown
 	Qt5Gui.dll!QImageReader::format() + 49 bytes	Unknown
 	DB Browser for SQLite.exe!00007ff61aa9f2ff()	Unknown
 	DB Browser for SQLite.exe!00007ff61aaa4ba1()	Unknown
 	DB Browser for SQLite.exe!00007ff61aaa92b9()	Unknown
 	DB Browser for SQLite.exe!00007ff61aaf9184()	Unknown
 	Qt5Core.dll!QMetaObject::activate() + 1439 bytes	Unknown
 	Qt5Core.dll!QItemSelectionModel::setCurrentIndex() + 304 bytes	Unknown
 	Qt5Widgets.dll!QAbstractItemView::mousePressEvent() + 728 bytes	Unknown
 	Qt5Widgets.dll!QAbstractSlider::event() + 198 bytes	Unknown
 	Qt5Widgets.dll!QFrame::event() + 55 bytes	Unknown
 	Qt5Widgets.dll!QAbstractItemView::viewportEvent() + 784 bytes	Unknown
 	Qt5Core.dll!QCoreApplicationPrivate::sendThroughObjectEventFilters() + 226 bytes	Unknown
 	Qt5Widgets.dll!QApplicationPrivate::notify_helper() + 300 bytes	Unknown
 	Qt5Widgets.dll!QApplication::notify() + 2243 bytes	Unknown
 	Qt5Core.dll!QCoreApplication::notifyInternal2() + 185 bytes	Unknown
 	Qt5Widgets.dll!QApplicationPrivate::sendMouseEvent() + 1011 bytes	Unknown
 	Qt5Widgets.dll!QSizePolicy::QSizePolicy() + 10917 bytes	Unknown
 	Qt5Widgets.dll!QSizePolicy::QSizePolicy() + 2843 bytes	Unknown
 	Qt5Widgets.dll!QApplicationPrivate::notify_helper() + 320 bytes	Unknown
 	Qt5Widgets.dll!QApplication::notify() + 7021 bytes	Unknown
 	Qt5Core.dll!QCoreApplication::notifyInternal2() + 185 bytes	Unknown
 	Qt5Gui.dll!QGuiApplicationPrivate::processMouseEvent() + 2475 bytes	Unknown
 	Qt5Gui.dll!QWindowSystemInterface::sendWindowSystemEvents() + 146 bytes	Unknown
 	Qt5Core.dll!QEventDispatcherWin32::processEvents() + 3558 bytes	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	Qt5Core.dll!QEventDispatcherWin32::processEvents() + 1456 bytes	Unknown
 	qwindows.dll!qt_plugin_query_metadata() + 7609 bytes	Unknown
 	Qt5Core.dll!QEventLoop::exec() + 459 bytes	Unknown
 	Qt5Core.dll!QCoreApplication::exec() + 321 bytes	Unknown
 	DB Browser for SQLite.exe!00007ff61abad116()	Unknown
 	DB Browser for SQLite.exe!00007ff61acde300()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
```

As I said, I'm quite unfamiliar with Qt. Is there some reason Qt would be attempting to load a dll from my path or other environment variable instead of the application directory?

**Comment by aswxxx** [comment]
"Fixed". It was loading Qt5Svg.dll from my perforce install, which apparently was also on my path. Uninstalled perforce and the crash went away. I'm ok with closing this issue now, but unsure if someone wants to do something about the fact that DB4S tries to load Qt5Svg.dll (maybe others too?) when it apparently doesn't even need it to function (it's not shipped with DB4S, which is why it loaded from the path).

**Comment by justinclift** [comment]
As a first guess, it's **probably** something Perforce does during install, to manipulate the search path for dlls.  That being the case... not really something we'd put time into investigating (eg detect the problem and workaround it).  It could probably be done something, but not a good use of time. :smile:
