### ISSUE TITLE
HAVING clause cannot be used in filtering 

### ISSUE THREAD

**Issue by okeks** [sqlitebrowser/sqlitebrowser#1971]
Details for the issue
--------------------

#### What did you do?
I used the Having clause after the Group By clause in my project and it didn't query any results back.

#### What did you expect to see?
Expected the result to be filtered into groups.

#### What did you see instead?

No response , 0 rows returned
Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
If you try the same query with the SQLite command line client, does that return any results?

If it does, it's probably something we'll need to investigate.  If it doesn't though, it likely means they problem is with the SQL statement itself.  If that's the case, the SQLite users mailing list would be the optimal place to get help. :smile:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

**Comment by SilvioGrosso** [comment]
Hello everyone,

Just tried myself with the nightlies builds on Windows 10 (home edition).
Everything works as expected.

For instance this SQL code produces two rows, that is the same result as the sqlite.exe standalone version downloaded from the sqlite web-page (https://www.sqlite.org/download.html):

create table products
(id integer,
item text,
price integer);

insert into products values
(1, 'apple', 3500),
(2, 'apple', 4500),
(3, 'pear', 3500),
(4, 'pear', 3000),
(5, 'pear', 2500),
(6, 'pear', 2000),
(7, 'banana', 3010);

select item,  avg(price) as average_price, count(item) count_item
from products
group by item
having max(price) >= 3020
order by item;

**Comment by MKleusberg** [comment]
Closing this because it doesn't look like there's much more we can do about it and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
