### ISSUE TITLE
Refactoring the Browse Data tab

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#1972]
I really hope you're not yet annoyed by me refactoring (and thus breaking) everything once a year or so :wink: But it's going to happen again. I'm currently moving all the code for the Browse Data tab into a separate class. The idea is to make the code easier to maintain but also to prepare for having multiple Browse Data tabs in one instance. Having one class for the Browse Data-related stuff which then can be instantiated multiple times is the first step towards having this.

Anyway, I'm almost done refactoring the code and will push a first version to master later today. If you have the time it would be really helpful to hear your test results :smile: 

Related issues: #756, #1465, #1905.

**Comment by SilvioGrosso** [comment]
Hello @MKleusberg 

> The idea is to make the code easier to maintain but also to prepare for having multiple Browse Data tabs in one instance.

Interesting improvement indeed!
Please, go on :-)

**Comment by mgrojo** [comment]
This is highly needed, not only for the useful enhancement, but also because MainWindow was already too big.

**Comment by MKleusberg** [comment]
Before progressing with this, I'd like to hear your opinions on whether to share or not share the view settings between multiple instances of the new TableBrowser class. Let's assume we have a way to open multiple Browse Data tabs and you are currently browsing two different tables in two tabs, changing some settings (filter, sort order, encoding, display formats, ...) for both of them. Now you change tab 1 to view the table from tab 2. Should it show the table with default settings or should it apply the settings from tab 2? In the latter case, should the changes made to the view settings in tab 1 be transferred back to tab 2? So from a more technical POV the question is if we should store the view settings once and use them for all Browse Data tabs or if each Browse Data tab should work with its own copy. And if it is the latter, the extra question is if and how synchronisation between the instances should happen.

Here's a small overview:

Option                  | Pro                                                          | Con
---------------------- | -------------------------------------------------- | --------------
Shared settings    | Easy to implement, easy to understand | Less flexible
Separate settings | More flexibility                                        | Harder to implement, lots of questions regarding synchronisation to be answered, project file format needs to be changed

What do you think? Any opinions on what to do? Any pros or cons I have missed?

Personally I'm leaning to using shared settings but with a flag to disable saving of any settings in a particular instance. This would mean that while standard Browse Data tabs share their settings, we can still show table views (e.g. for previews, tooltips, ...) which don't affect the standard views.

**Comment by mgrojo** [comment]
I'd go for shared settings with the flag to disable saving of any settings. 

A third option could be to have "saved view settings", which can be selected from a combo box. We start with a default one, which all the data browser tabs use. But the user can create a new named "saved view settings" and select it for another set of tabs. All the created "saved view settings"  are saved to the project file. When only Default exists, it could be saved with the current project format; and additional ones can be saved using similar browse_table_settings nodes in the xml file.

But not sure if this last option would be worth of the effort. I think the shared settings with the detached view flag would more simple and might be enough, at least for the moment.

**Comment by chrisjlocke** [comment]
Saving is still allowed isn't it?  It just gets slapped into the registry, or whatever is applicable for that OS.

**Comment by mgrojo** [comment]
The browse table settings are only saved when saving to a project file, so it shouldn't be a problem. One could, for example, run DB4S from a DVD-ROM and then save the project file in the local disk.

**Comment by MKleusberg** [comment]
Yep, @mgrojo is right. This only affects saving to project files.

I have already changed the code to share the settings between all views. Only the flag to disable saving the settings isn't implemented yet. It turned out to be way more complicated than initially thought because of how our ```applyBrowseTableSettings()``` function works. I think I will deal with this when we actually need the flag and leave it until then.

Should we close this issue then and open new ones for possible UI changes to make use of the separate class? Or should we use this issue for that purpose? :smile:

**Comment by MKleusberg** [comment]
Closing this because the refactoring is done and has been tested. We also settled for shared settings.
