### ISSUE TITLE
modify column's COLLATE value

### ISSUE THREAD

**Issue by kevin-haynie** [sqlitebrowser/sqlitebrowser#1973]
Would it be possible to add the ability to change the COLLATE setting on a column using your 'Edit Table Definition' form?  I'm using your application on OSX Mojave.  

You can change a lot of attributes on an existing column but you don't have the ability to change the COLLATE setting.  I have an existing table that I need to set COLLATE NOCASE on certain columns but I can't.

This would be a very helpful feature.
Thanks

**Comment by MKleusberg** [comment]
Thank you for the suggestion :smile:  I have just added a new column to the table of all fields in the Edit Table dialog. You will probably have to scroll to the right to see it though:
![Screenshot_20190821_234211](https://user-images.githubusercontent.com/3153504/63470637-649cfc80-c46d-11e9-9c69-5a093f8aaaee.png)

Can you try out the next nightly build and let me know if it is working as expected for you? You can download it [here](https://nightlies.sqlitebrowser.org/latest/) in about ~5 hours or so.

**Comment by chrisjlocke** [comment]
The Mac nightlies are busted at the moment.
See issue #1979 
The man is on the case though, so keep your eyes peeled.

**Comment by justinclift** [comment]
Just manually ran the nightly builders, and the macOS one build correctly. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by MKleusberg** [comment]
@kevin-haynie Did you have a chance to give this another try with the (now working!) nightly builds? :smile:

**Comment by MKleusberg** [comment]
Ping :innocent:

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
