### ISSUE TITLE
full outer join is not supported

### ISSUE THREAD

**Issue by ashank19** [sqlitebrowser/sqlitebrowser#1978]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by MKleusberg** [comment]
This is expected. The underlying SQLite library just doesn't support full outer joins. You can [see here](https://sqlite.org/omitted.html) what features they don't implement. If you want to, you can ask on the SQLite mailing list how likely it is that they add support for it one day or if there are any preferred workarounds. But I think chances are pretty slim. Does this help you already? :smile:

**Comment by MKleusberg** [comment]
I'm closing this issue since there is not much we can do about it.

[Here](https://www.sqlitetutorial.net/sqlite-full-outer-join/) is a small tutorial however on how to emulate full outer joins by using a UNION construct.
