### ISSUE TITLE
MacOS nightlies busted atm

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1979]
It's been pointed out via private email, that our macOS nightly builds have been broken for the last week or so.  File size is far too small to be legit:

```
DB Browser for SQLite-sqlcipher_20190821.dmg       20-Aug-2019 23:35            17133094
DB Browser for SQLite-sqlcipher_20190822.dmg       21-Aug-2019 23:27             2787313
DB Browser for SQLite-sqlcipher_20190823.dmg       22-Aug-2019 23:26             2787375
DB Browser for SQLite-sqlcipher_20190824.dmg       23-Aug-2019 23:27             2787882
DB Browser for SQLite-sqlcipher_20190825.dmg       24-Aug-2019 23:26             2787340
DB Browser for SQLite-sqlcipher_20190826.dmg       25-Aug-2019 23:26             2787956
```

This looks like the kind of thing that happens when something goes wrong with the compile, but the packaging part of the script doesn't notice and keeps going. :wink:

I'll take a look at what's wrong, likely tonight.

**Comment by chrisjlocke** [comment]
If only we had a nightlies file checker.... ;)
It was on the laptop I had to give back to my ex-work.  I start now at 7.30am (UK time ... obviously!) so will write v2... ;)

**Comment by MKleusberg** [comment]
The log files for the macOS nightlies are online which is super handy in this case: https://nightlies.sqlitebrowser.org/osx/nightly-20190827.log

The error seems to be this one:
```
MainWindow.cpp:127:9: error: no member named 'horizontalLayout' in 'Ui::MainWindow'; did you mean 'horizontalLayout_3'?
    ui->horizontalLayout->addWidget(ogl);
        ^~~~~~~~~~~~~~~~
        horizontalLayout_3
.ui/ui_MainWindow.h:183:18: note: 'horizontalLayout_3' declared here
    QHBoxLayout *horizontalLayout_3;
                 ^
```

I'll have a look now :smile:

**Comment by MKleusberg** [comment]
It should be fixed now :smile: The problem was here - which also explains why it didn't fail on Windows or Linux:
```c++
#ifdef Q_OS_MACX
    // Add OpenGL Context for macOS
    QOpenGLWidget *ogl = new QOpenGLWidget(this);
    ui->horizontalLayout->addWidget(ogl); // <--- this horizontalLayout doesn't exist anymore since I moved the Browse Data stuff into a separate widget
    ogl->setHidden(true);
#endif
```

**Comment by justinclift** [comment]
@MKleusberg That's really awesome!

Really glad we decided to include the log files with the uploads. :smile:

@chrisjlocke Excellent, it all helps. :smile:

**Comment by justinclift** [comment]
@MKleusberg Yep, it worked! :smile:
