### ISSUE TITLE
Error when connecting to download.sqlite

### ISSUE THREAD

**Issue by matixdadix** [sqlitebrowser/sqlitebrowser#1980]
Details for the issue
--------------------
error when connecting to https://download.sqlitebrowser.org/currentrelease. error creating SSL conttext()
#### What did you do?

uninstalled the browser completely. Reinstalled it. 

#### What did you expect to see?

The error message to go away
#### What did you see instead?

The error didn't go away

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by chrisjlocke** [comment]
Thanks for reporting this, but it's a known error.
The quick workaround is to turn off the automatic check for updates in the
preferences section of the options.
You'll have to check for updates manually, but as the're so infrequent, it
shouldn't be a problem.

**Comment by matixdadix** [comment]
Thanks Chris!! I will turn off the automatic updates!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hamza1244** [comment]
@chrisjlocke How does it turn off @matixdadix

**Comment by chrisjlocke** [comment]
I've put screenshots in the other issue you raised.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3124
