### ISSUE TITLE
Command Line options like --help or --version not resulting in output to stdout on macOS

### ISSUE THREAD

**Issue by ctsrc** [sqlitebrowser/sqlitebrowser#1982]
Details for the issue
--------------------

When attempting to run the `DB Browser for SQLite` Mach-O 64-bit executable from the command line on macOS with command line options such as `--help` or `--version`, no corresponding output is written to stdout.

Additionally, the following message is written to stderr a bunch of times when trying to run the executable with command line options.

```text
qt_safe_poll: Invalid argument
```

#### What did you do?

Ran the following command in the terminal on macOS:

```bash
/Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite --version
```

#### What did you expect to see?

Version information output to stdout in the terminal.

#### What did you see instead?

No output to stdout. A bunch of repeated messages on stderr saying:

```text
qt_safe_poll: Invalid argument
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ macOS Mojave Version 10.14.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

Version 3.11.2 installed from Homebrew with `brew cask install db-browser-for-sqlite`.

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
See #1069.  They don't work in Windows either.

**Comment by djedi** [comment]
I solved this by creating an alias in by .zshrc / .bashrc file:
`alias sqlitebrowser="/Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite"`

**Comment by ctsrc** [comment]
Yes, I’m fine with the issue being closed. Thank you @revolter and @mgrojo for taking the time to look at this.
