### ISSUE TITLE
Generate SQL queries required to upgrade database

### ISSUE THREAD

**Issue by elmurzaev** [sqlitebrowser/sqlitebrowser#1983]
Describe the new feature
--------------------------
Generate SQL queries required to upgrade database, which can also be exported as .sql files.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
NO

#### Does this feature exist in another product or project? Please provide a link.
I don't know

#### Do you have a screenshot? Please add screenshots to help explain your idea.
I don't

**Comment by chrisjlocke** [comment]
There is a command line tool cal sqldiff which does this, which is part of
the official sqlite tools.
What is your operating system?

**Comment by mgrojo** [comment]
This is very similar to #158 and there is probably valuable information in that issue.
