### ISSUE TITLE
Compiling on Ubuntu To Use A Pre Installed Version of SQLite

### ISSUE THREAD

**Issue by PetrJakes** [sqlitebrowser/sqlitebrowser#1985]
Compiling on Ubuntu To Use A Pre Installed Version of SQLite
-----------------------
**My working environment:**
- Linux Mint 19 Tara
- SQLite version 3.29.0 ([compiled](http://www.linuxfromscratch.org/blfs/view/svn/server/sqlite.html) )
-----------------------
**[sqlitebrowser compilation:](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux)**

`git clone https://github.com/sqlitebrowser/sqlitebrowser`

I have changed  `CMakeLists.txt` according to my environment:
```
find_library(LIBSQLITE ${LIBSQLITE_NAME} HINTS /usr/lib/x86_64-linux-gnu)
set(ADDITIONAL_INCLUDE_PATHS /usr/include)
```
Then:

```
cmake -DFORCE_INTERNAL_QSCINTILLA=ON -Wno-dev ..
make
sudo make install
......
[100%] Built target sqlitebrowser
```

No errors!

sqlitebrowser is built properly and running.
The problem is two version of SQLite (see attached screenshot)
![Screenshot from 2019-09-02 22-26-51](https://user-images.githubusercontent.com/12581771/64132965-98fcab00-cdd3-11e9-99ba-d625a09f7b80.png)

1. In the "About" info you can see SQLite version 3.29.0 as expected
2. `SELECT sqlite_version();` returns version 3.22.0  

SQLite "Windows functions" are not working.
![Screenshot from 2019-09-02 23-15-33](https://user-images.githubusercontent.com/12581771/64133610-a320a880-cdd7-11e9-9d45-42468383af17.png)

How to solve this issue?

**Comment by MKleusberg** [comment]
Do you happen to have both versions of SQLite in /usr/lib/x86_64-linux-gnu? If so, the build process probably just picks the first one it sees. You could also try setting the ```LIBSQLITE``` variable yourself. So instead of this
```
find_library(LIBSQLITE ${LIBSQLITE_NAME} HINTS /usr/lib/x86_64-linux-gnu)
set(ADDITIONAL_INCLUDE_PATHS /usr/include)
```
try this
```
set(LIBSQLITE /path/to/your/sqlite/lib)
set(ADDITIONAL_INCLUDE_PATHS /usr/include)
```

**Comment by PetrJakes** [comment]
compiling on fresh install solved the problem. Thanks

**Comment by MKleusberg** [comment]
Awesome :smile: I'm glad it's working now. I'll close this issue then.
