### ISSUE TITLE
Error when importing simple CSV file (possible type convertion error)

### ISSUE THREAD

**Issue by turicas** [sqlitebrowser/sqlitebrowser#1986]
Hi! Before everything, thanks for creating and maintaining this project. I use it a lot in my classes to teach SQL to journalists. =)

Details for the issue
--------------------

#### What did you do?

I've tried to import a simple CSV file ([santos-csv.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3572998/santos-csv.zip)) into my database and it was not imported at all, an unknown error happened.

#### What did you expect to see?

A new table with CSV contents as data.

#### What did you see instead?
The error was:
```text
Error importing data from record number 81.
Inserting row failed: not an error
```
![2019-09-04_03-29-40](https://user-images.githubusercontent.com/186126/64231156-3257ba00-cec5-11e9-8ae3-7f062986e642.png)

It won't work even if I check "Disable data type detection":
![2019-09-04_03-30-01](https://user-images.githubusercontent.com/186126/64231152-2d930600-cec5-11e9-8a7f-6daf69809bfa.png)

The only way I've found to import this file is to replace the value `"1.240.294,00"` on line 81 with `"1240294,00"` (remove Brazilian thousand separators).

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Debian GNU/Linux (sid) )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
You've put the field separator as a comma, but you're also using thousand
separators?
How will Db4S know that 1,234,5  means 1,234 is field 1, and 5 is field 2,
and not 1 is field 1, and 234,5 is field 2?
The thousand separator and field separator should be different characters.

>

**Comment by MKleusberg** [comment]
@chrisjlocke The last field is quoted and inside quotes DB4S will ignore any field separator. So no problem here :smile: 
```
Alemoa,1029,"2.507.027,00"
                      ^
                      DB4S doesn't even look for field separators as long as it is in quote mode
```

@turicas The problem seems to be the missing line break at the end of the file. If you add that it should work. I have also just committed a fix for this issue. but you will have to compile DB4S yourself to test it. Are you ok with that? :smile:

**Comment by Z4us** [comment]
The cli works flawlessly and it appears indeed the last row of the table.

**Comment by turicas** [comment]
@MKleusberg thanks! I didn't have the opportunity to test it but if you did (after your commit) we may close this issue, right?

**Comment by MKleusberg** [comment]
@turicas Sure. I'm going to close this issue. Thanks again for reporting this :smile:
