### ISSUE TITLE
Edit Table, Move Field Top Feature

### ISSUE THREAD

**Issue by sonerb** [sqlitebrowser/sqlitebrowser#1988]
Describe the new feature
--------------------------
When editting table moving to selected field to top, For example, i want to move "Identity" or "ID" field to top.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
None.

#### Does this feature exist in another product or project? Please provide a link.
No.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![screenshot](https://user-images.githubusercontent.com/2131188/64247909-82ac3780-cf18-11e9-8509-257abcb69d27.png)

**Comment by MKleusberg** [comment]
Thanks for the suggestion, @sonerb! I have just added a move to top button (and for consistency/symmetry a move to bottom button). Can you give tomorrow's nightly build a try and see if it's working for you? :smile:  You can download it [here](https://nightlies.sqlitebrowser.org/latest/) next day.

**Comment by MKleusberg** [comment]
@sonerb Did you have a chance to give the new version a try? :smile:

**Comment by sonerb** [comment]
> @sonerb Did you have a chance to give the new version a try? 😄

hello, I downloaded nightly build but it's just 22 bayt and there is nothing inside the zip file.

**Comment by justinclift** [comment]
@sonerb Yeah, one of the commits yesterday broke the automatic overnight build.

I **think** I've just fixed it, but am not 100% sure.  The build is running again, so if it worked then there the nightly build should be there in ~40 minutes or so.  If it's not, then I still have more fixing to do. :wink:

**Comment by justinclift** [comment]
Yep, new builds are online now:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by sonerb** [comment]
> Yep, new builds are online now:
> 
>     https://nightlies.sqlitebrowser.org/latest/

I checked it's working, thank you. :)

**Comment by justinclift** [comment]
Awesome.  Good work again @MKleusberg. :smile:
