### ISSUE TITLE
Export option cannot select every table

### ISSUE THREAD

**Issue by ericsia** [sqlitebrowser/sqlitebrowser#1989]
Describe the new feature
--------------------------
There's a lot table in the list I'd like to export into csv
The tool **can't** select all. If u ctrl + A it will only export 1 that's initially selected
Suggestion is to add a "select all" button let user select folder location. then export all into csv format

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
no

#### Does this feature exist in another product or project? Please provide a link.
Not seen as I like this project very much, i'd like to continue use this. This feature can be added easily

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![Image 3](https://user-images.githubusercontent.com/24624808/64480233-51708780-d1f6-11e9-80e5-3e5632227e4b.png)

**Comment by mgrojo** [comment]
Try pressing Ctrl+A inside the list. That worked for me in Linux and I guess it would also work in Windows. Nevertheless, the suggestion is welcome, since it would be more clear how to perform the action.

**Comment by ericsia** [comment]
I'm on windows. I know ctrl+A I tried it that's why I know it's not working

**Comment by scottfurry** [comment]
@ericsia  - doing a google search, there are plethora of stories of short-cut keys not working in different scenarios. General consensus is to reset and clean out offending programs blocking function. (see [here](https://nutsandboltsspeedtraining.com/powerpoint-tutorials/keyboard-shortcuts-not-working/) although it seems geared towards laptop users - but you get the idea I hope)

Short cut keys not working in windows leans towards a configuration problem more that a problem with the program. Not saying it can't happen. But in this particular case, this may be something in windows configuration of your machine causing you grief.

**Comment by mgrojo** [comment]
@scottfurry, does it work for you? I don't know if you use Windows though. I'd say it's a different behaviour due to the platform.

@ericsia, try pressing on the first table and dragging until the last one. It shouldn't be too difficult to select all in that way.

**Comment by scottfurry** [comment]
@mgrojo - on linux and don't have user's data test if problem is widespread or just local.

**Comment by mgrojo** [comment]
Ctrl+A worked for me using wine for Version 3.11.99 (Aug 11 2019).

In any case, a combox for selecting these sets of objects would be useful:
- None: initial, resets the selection.
- All tables: selects all tables.
- All views: selects all views.
- All objects: selects all tables and all views.
- Custom: automatically set when the user changes the selection. Changes nothing if manually set.

**Comment by ericsia** [comment]
my bad, today when I try it again, it's working. Last 2 time when I try it only export 1 of the table that's initially selected. I'm not sure what's the condition last time causing it to happen
