### ISSUE TITLE
Suggestions for funky 3.6.0 project name?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#199]
We don't have a funky project name for our 3.6.0 release yet.

Anyone have suggetions?

They started out with sunlight/light based names, then I ran out of ideas and just picked interesting word sets.  So, pretty much anything that sounds interesting is a valid suggestion. :grinning:

**Comment by Z4us** [comment]
Primavera 

(i.e. Italian for spring - eventually you may write it not exactly correct, but as a pun like 'Prima Vera')

**Comment by glawrence** [comment]
I would suggest coming up with a pattern rather than a name. For example, I worked for a company once where projects were named after letters of the alphabet, starting with A of course and their theme was alcohol, so the first project might have been Ale for example, however I worked on Guinness.

It might be better to use something that won't have copyright or trademark issues! Just in case. There is no need to get too clever, so we could use towns and start with Aberdeen, then Birmingham, Cleveland......

Anyway, that's just food for thought

**Comment by justinclift** [comment]
Heh, that's two decent thoughts... keep them coming. :grinning:

**Comment by Z4us** [comment]
Following glawrence's suggestion we would start with F being the sixth letter of the alphabet.  Combination with mine 'Frühling' (German for spring) or his own 'Frankfurt'

**Comment by justinclift** [comment]
Personally, I'm kinda against using letters of the alphabet.  (Due to Canonical doing that, and I'm no fan of theirs. :wink:)... and place names is kinda boring.

eg "Space Pizza Express" does sound more interesting... and could lead to nifty release-logos :grinning:

For 3.6.0, how about "Dragon Emperor Chu"?

**Comment by Z4us** [comment]
Referring to China to avoid political correctness ;-?

**Comment by justinclift** [comment]
??? Not really.  China didn't really spring to mind at all.  Just been watching anime today tho, while doing other stuff. :grinning:

**Comment by Z4us** [comment]
What about famous people provided:
1 they are dead
2 equally use artists, champions in sports, politicians, (fe)males etc.
3 perhaps they have something to do with the date e.g. day of birth, death, victory, dissertation, speech etc.

example: if a release is planned April 4 one may think of Martin Luther King

**Comment by justinclift** [comment]
Ahhhh, that's an interesting idea.

March 1st is our next tentative release date, so lets look for some March 1st people for that. :smile:

**Comment by samir-aguiar** [comment]
I also find interesting the name of stars/galaxies, famous historical
battles or Greek/Roman mythology characters.

**Comment by justinclift** [comment]
Maybe name it after "Gioachino Rossini"?

&nbsp; &nbsp; http://www.thefamouspeople.com/march-1st.php

**Comment by justinclift** [comment]
@samir-aguiar Famous historical battles &larr; Meh.. naming a release after the death of lots of people... doesn't sound optimal. :anguished:

**Comment by MKleusberg** [comment]
Naming it after some event that happened on this particular date kind of forces us to stick exactly to the planned release date. Don't know if that's a good or a bad thing... - but it definitely might make releases more stressful ;)
Anyway, I'm looking at https://en.wikipedia.org/wiki/March_1 at the moment... How about Beer Day? Or Justin Bieber? :wink: Or, more seriously, Naomi Anderson.

**Comment by justinclift** [comment]
Naomi Anderson seems like a decent figure.  Now, how to turn that into an interesting project name... :grin:

**Comment by Z4us** [comment]
Malak Karsh's birth was exactly a century ago

**Comment by Z4us** [comment]
What about Naomi Anderson's dream?

**Comment by rp-** [comment]
Not that I care too much about release names, actually I hate the debian/ubuntu naming, because I never really know which name belongs to which release.

I don't think using names of real characters is a good idea, I would rather use fictional characters or something completely different.
But again release names don't really add anything useful, until they are funny. (e.g. grml release names if you know german)

**Comment by Z4us** [comment]
Fictional characters and/or anagrams is a good idea as well

**Comment by justinclift** [comment]
Hmmmm....

k, on that note how about "Zoidberg has landed".  That's a fictional character (Futurama), and sounds somewhat interesting.  Now, we just need someone with illustration skillz... :grinning:

(Though I could go with "Naomi Anderson's Dream" as well tbh) :wink:

**Comment by Z4us** [comment]
Animals - fictional like Snoopy, Snowy (we call him Bobby) etc

**Comment by Z4us** [comment]
Since it's the centennial of her birth: 

https://en.wikipedia.org/wiki/Regina_Ghazaryan

**Comment by justinclift** [comment]
Cool.  There have been a few suggestions, so lets put them together in a list and vote here for them +1/-1 style.

I'll get the list assembled later on today (after work), unless someone has time to do it sooner. :smile:

**Comment by justinclift** [comment]
"Naomi Andersons Dream" it is. (ran over time, forgot to set up a vote, so just picked the one that appealed most to me :wink:)
