### ISSUE TITLE
Rewriting the Antlr parser

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#1990]
Since refactoring the Browse Data tab (see #1972) turned out to be way less disruptive than I initially thought, it is now time for the next refactoring project. This time I aim to replace our SQLite parser which is generated by Antlr v2. After experimenting with traditional Boost Spirit, Spirit X3, Lemon, and Antlr v4, I have now prepared a working parser generated with one of the more traditional parser generators, flex and bison, which turned out to work really well.

This first version fully replaces our parser for ```CREATE INDEX``` statements. ```CREATE TABLE``` statements still run through the old parser. If anybody is interested, you can test the new parser by opening a database and check if all indices are parsed correctly. If any problems appear, just let me know here and I'll try to tweak the new parser.

The code is in the [flex_bison_parser branch](https://github.com/sqlitebrowser/sqlitebrowser/tree/flex_bison_parser) and can be reviewed. But I don't expect anybody to review the whole thing (which is also why I'm opening an issue and not a PR). Binaries were kindly built by Justin and can be downloaded here:
* [macOS, SQLite](https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite_flex_bison_parser_v1.dmg)
* [macOS, SQLCipher](https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_flex_bison_parser_v1.dmg)
* [Win64, msi](https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-flex_bison_parser_v1-win64.msi)
* [Win64, zip](https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-flex_bison_parser_v1-win64.zip)
* [Win32, msi](https://nightlies.sqlitebrowser.org/win32-onceoffs/DB.Browser.for.SQLite-flex_bison_parser_v1-win32.msi)
* [Win32, zip](https://nightlies.sqlitebrowser.org/win32-onceoffs/DB.Browser.for.SQLite-flex_bison_parser_v1-win32.zip)

You can find some of the reasons for this step in the commit message in a6dfb518f8b8cd8d305f291cf80995febd69bd2c but I'll probably add some more explanation in a follow-up comment here later :smile:

**Comment by mgrojo** [comment]
Positively surprised that those old two horses still beat a young proud one :smile: I'll test the branch with some of my test databases.

**Comment by MKleusberg** [comment]
Thank you, Manuel :smile: 

Here is some more background information for everybody:
We currently define a SQLite grammar in a Antlr-specific format in src/grammar/sqlite3.g. Whenever I change this file, I need to rerun Antlr (a Java application) which then generates the actual lexer and parser from this file. Those are the other files in the same directory. Normally you wouldn't include these generated files in your repository but since we don't want to add a Java runtime environment and Antlr to the build dependencies, we just included them anyway.

When we want to parse a ```CREATE``` statement, we basically call the function generated by Antlr (ignoring some required preparations here). Antlr then builds an abstract syntax tree which represents the SQL statement. This tree isn't built using any of our classes but purely relies on Antlr-specific classes. So the results from the Antlr-generated parser aren't very useful alone. Instead we have to run through the tree in a second step and create objects using our classes. The tree and all the functions to access it are in a Antlr runtime library and that's why we still have to add this Antlr library as a dependency.

The new approach starts similar. There are two files now, one for the lexer and one for the parser, and they serve as input to flex and bison respectively to create code for a lexer and a parser. So it's two files and two programs now instead of one. Same thing as before: I have checked in the generated code to avoid adding flex and bison to our build dependencies. Luckily it turned out that the generated files compile on macOS and Windows without any apparent problems. Also just as before, we call the generated function with a string and it parses it. But here is the major difference. The bison-generated parser doesn't build an AST and returns it to us. Instead it uses semantic actions which means that whenever it has parsed a part of the statement, it executes a bit of code specific for this part. I have inserted code to directly build a representation using our classes. This eliminates the need for a runtime library and makes the whole process a bit simpler as there is no need for a second step to interpret the AST. That's one of the major benefits in my opinion.

**Comment by MKleusberg** [comment]
Here are some opinions on the other parser generators I tried. Don't take them too seriously because I'm definitely no expert on this topic :smile: 

* Lemon: Looks fine and is similar to bison. Is used by SQLite itself but the grammar is so specific to SQLite's needs that there is no way we can just copy and adjust it to our needs. So no benefit here. Doesn't seem to be used in too many projects, so there is less information on the Internet. Most of its strengths were implemented in bison in the meantime, too.
* Antlr v4: Looks fine too. But: Still requires Java to build the parser. Still requires a runtime library. Too different to migrate our old grammar file, so we would have to rewrite the whole thing. Still relies on LL(k) grammars which made our expression parser so awkward in the previous approach.
* Boost Spirit: Awesome, as it integrates really well with your C++ code. Ridiculous compile times even for my modest first parsers. Requires a huuuuuge C++ library to build.
* Boost Spirit X3: Even more awesome than traditional spirit. Faster compile times but still very, very long. Also requires a huge library even though it is somewhat smaller. I would have used X3 anyway but decided against it for one more reason: when it backtracks it doesn't clear the attributes (see [here](https://github.com/boostorg/spirit/issues/378)). This turned out to be so annoying, that I just didn't want to use it anymore.

**Comment by justinclift** [comment]
> I have checked in the generated code to avoid adding flex and bison to our build dependencies ...

If flex and bison are very cross platform (likely?), we could probably add them without breaking things.

**Comment by MKleusberg** [comment]
@justinclift They don't seem to be very common on Windows. But it seems like you could download them [here](http://gnuwin32.sourceforge.net/packages/flex.htm) and [here](http://gnuwin32.sourceforge.net/packages/bison.htm) and I see no reason why they shouldn't work. So the question is whether we prefer simpler compile instructions but uglier commit history or pretty commit history but more involved compile instructions (for all platforms that is). Personally I prefer the pretty commit history but I'm probably one of the few persons for whom the compile process wouldn't change a bit :wink:


Just a quick note: I have rewritten part of the history and added some new commits. I'm still not done and will likely need another couple of days but I think we're close to a parser for ```CREATE TABLE``` statements too :smile:

**Comment by MKleusberg** [comment]
Another really quick update: no need to test anything for the next 24 hours or so. I just went through the process of testing every database I could find on my system and fixed quite a few problems in the process. I'll rewrite the commit history and push the changes tomorrow. There are only two known issues remaining now - both of them need a bit of extra thinking :wink:

**Comment by MKleusberg** [comment]
By the way, the latest version of the new parser successfully parses the table definition from issue #60. So when this is merged into the master branch we can finally close our oldest open issue :tada:

**Comment by mgrojo** [comment]
My tests didn't raise any error, but my databases turned to have only a few simple index definitions, so not really useful.

**Comment by scottfurry** [comment]
This is probably TOO Late to mention, but I have to throw it out.
Is our SQL grammar customized? Has someone looked at pulling in a standard BNF SQL grammar (and only pull in uniqueness for SQLite)? Such as https://github.com/ronsavage/SQL

**Comment by data-man** [comment]
[sqlite-bnf](https://github.com/AlecStrong/sqlite-bnf)
___
Some ideas:
* use PEGs. For example [cpp-peglib](https://github.com/yhirose/cpp-peglib) (C++11) or [PEGTL](https://github.com/taocpp/PEGTL) (C++17) . PEGTL has [abnf2pegtl example](https://github.com/taocpp/PEGTL/blob/master/src/example/pegtl/abnf2pegtl.cpp) (Sadly, isn't BNF)
* use [tree-sitter](https://github.com/tree-sitter) with [atom/language-sql](atom/language-sql)
___
I take this opportunity to thank you for the great app! :rocket:

**Comment by MKleusberg** [comment]
Thanks, everybody. I'll reply to that later when I have more time :smile: 

I have just finished rewriting the history, fixed some more issues, and added more tests. One problem remains (see the failing test) but other than that I think we're fine.

**Comment by MKleusberg** [comment]
Thanks, Manuel! I have just fixed the issue - it was just a minor oversight be me :smile: What do you reckon? Can we merge the branch into master already?

**Comment by mgrojo** [comment]
Yes, Martin. It seems ready.

**Comment by MKleusberg** [comment]
Just merged it :smile:

**Comment by data-man** [comment]
Just for record. :)
Thanks to the Wikipedia article [Comparison of parser generators](https://en.wikipedia.org/wiki/Comparison_of_parser_generators).
I didn't know about [lug](https://github.com/jwtowner/lug) and [BNFLite](https://github.com/r35382/bnflite). Very interesting.

**Comment by MKleusberg** [comment]
Thanks for the links! That's indeed interesting :smile:
