### ISSUE TITLE
permission for open removable devises trougth ssh

### ISSUE THREAD

**Issue by NNoyanova** [sqlitebrowser/sqlitebrowser#1993]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem:
There is no permission to open databases on removable server, which I was connected by ssh. I switched "on" permissions in Ubuntu Software for read/write files on removable storage devises, but when I open it by DB Browser for sqlite after file manager opening (there is no access to other locations, only home/media/documents/desktop and etc on my PC), it tell me that "database is locked". I am owner of this database. I permit read and write this database for everyone. What's wrong?

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-58-generic x86_64))
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.2
- [ ] 3.11.1
- [ *] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by NNoyanova** [comment]
There is no permission to open databases on removable server, which I was connected by ssh. I switched "on" permissions in Ubuntu Software for read/write files on removable storage devises, but when I open it by DB Browser for sqlite after file manager opening (there is no access to other locations, only home/media/documents/desktop and etc on my PC), it tell me that "database is locked". I am owner of this database. I permit read and write this database for everyone. What's wrong?

**Comment by scottfurry** [comment]
@NNoyanova 
Opening an SQLite file creates the lockfile. This is more an application thing than permission. Something else has that database open. Unlike other database software (i.e. postgreSQL, oracle, et al). SQLite does not have a multi-user ability to act on data. One user, one db file.

Look in the folder where DB file resides, you should see another file like "[db filename]-journal". SQLite creates this file for tracking changes to data. Delete that file and you should be able to carry on.

**Comment by NNoyanova** [comment]
It was opened only with file search
. No another processes or users was reading that file. I added permissions for any users because of fear of collisions with logins.

**Comment by scottfurry** [comment]
Removable storage is different the SSH server. In this case, the removable storage isn't allowing a temporary file to be created.

What are we trying to solve here?

**Comment by chrisjlocke** [comment]
This has been mentioned here before, but I'm struggling to find the right words to search properly.  This is a problem with the way you're accessing the file, not with DB4S.

**Comment by justinclift** [comment]
@NNoyanova It sounds like you're still getting the hang of file and directory permissions on Ubuntu.  Not to worry, with some practice and persistence you'll figure it out. :smile:

As a first step, what is the full path to the removable storage, when it's mounted?

Please do an `ls -la` on that path, then paste the output here. :smile:

**Comment by NNoyanova** [comment]
I checked by <fuser  %filename%> and it said that there is no process using the file

**Comment by NNoyanova** [comment]
The problem was in version of sqlite browser. I launched later versions and one of them works correctly.

**Comment by MKleusberg** [comment]
Looks like we can close this issue then. Please just re-open it if I'm missing anything :smile:
