### ISSUE TITLE
Interface font is different from my system default font, how can I change the interface font?

### ISSUE THREAD

**Issue by lcchennn** [sqlitebrowser/sqlitebrowser#1995]
Part of the browser is using a font different than my system font. I was wondering if it is possible for me to change the font in the browser? I looked into the preferences dialog but did not find the place where I can change the fonts on the tab.
<img width="467" alt="font issue" src="https://user-images.githubusercontent.com/52438350/64922119-14ac1e00-d7fe-11e9-8822-0d8a2d684dd4.PNG">

#### What did you do?
Downloaded and installed the latest version

#### What did you expect to see?
font to be the same within the browser

#### What did you see instead?
The File, Edit, View and Tools on the top follows my system font. The tabs(New Database, Open Database, Write Changes..., etc. and the Database Structure, Browse Data..., etc.) however uses another font.

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by sky5walk** [comment]
You can change the Data Browser and Execute SQL fonts in the Edit-Preferences-Data Browser & SQL dialog. Your "mileage may vary" according to nightly version and Dark theme selection. 😉

**Comment by lcchennn** [comment]
Thanks for the reply! The fonts in data browser and execute sql worked fine for me and the fonts on the tab label is what I wanted to change. I think it may have something to do with my os though :/

**Comment by MKleusberg** [comment]
The screenshot looks like it is a OS or a Qt thing. We don't change the font for tab texts, labels, buttons, or anything like that anywhere in our code. But I have to admit I have no idea where the default style or font is stored and why it should be different on your system :frowning:

**Comment by sky5walk** [comment]
I did not realize the limits on the font preferences?
Can you comment on my bug post #1994?
I can remove the Tab name mention, but I expected the results window(column headers and row content) to use my font selection.

**Comment by lcchennn** [comment]
@MKleusberg Thanks. I tried on another PC which does not have this same issue. I think it could be that my OS is not installed in English. Closing this issue for now.

**Comment by MKleusberg** [comment]
Maybe. Especially if it's a language which doesn't use Latin script, Qt could choose some weird font for the UI. If you find out anything, let us know here :smile:
