### ISSUE TITLE
Some translations have the Preferences menu in the wrong place on OSX

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#200]
When testing #189, it turns out some of the translations have their Preferences dialog turn up in the wrong menu under OSX.

For OSX, it should always be under the Application menu.  For at least Russian and French it's turning up in a different menu ("Vue" for the French).

**Comment by MKleusberg** [comment]
Hi Justin, can you test this with the commit I've just made? If I understood the Qt documentation correctly it might work this way but I've no chance to actually test it...

**Comment by justinclift** [comment]
Sure, I'll give it a shot tomorrow.  Need sleep atm. :wink:

**Comment by justinclift** [comment]
Tested this just now instead, and yep, it works:

* Compiling the v3.5.1 version &rarr; Preferences entry is in the wrong menu
* Compiling with this patch applied &rarr; Preferences entry is in the Application menu (checked all of Chinese, French, German, and Russian).

Awesome stuff Martin. :grinning:

**Comment by samir-aguiar** [comment]
Nice one, working here as well. Those Qt roles are tricky :smile:

**Comment by MKleusberg** [comment]
Thank you both :smiley:
