### ISSUE TITLE
Thumbnails for images displayed directly on the table cells

### ISSUE THREAD

**Issue by silviulaurentiu** [sqlitebrowser/sqlitebrowser#2000]
This is not an issue it is a feature request.

I think will be very useful to see the image inserted into a cell as a small picture (thumbnails of the image) directly on the table cell.

Many thanks!

**Comment by MKleusberg** [comment]
Thanks for the suggestion! I have just added a very basic preview of BLOB images. For performance reasons the new feature is disabled by default for now though. I'll try to speed up the relevant code in the future and maybe we can then turn it on by default. There's a second caveat too: The images aren't scaled (yet), so for very large images you'll only see the upper left corner.

Do you want to give this a try anyway? You'll have to download tomorrow's nightly build for that. Here's the option to enable the preview feature in the Preferences dialog:
![Screenshot_20190922_222059](https://user-images.githubusercontent.com/3153504/65393894-60734000-dd87-11e9-8d36-75a85598bdb4.png)

**Comment by silviulaurentiu** [comment]
Many thanks,

            Yes, I want to try it.

                         Many thanks!

   ______________________________________________________

   Calde salutări / Best regards / Mit freundlichen Grüßen

*   Silviu Doaga*

   Sibiu,  România

   Phone: +40 757 141 932

   E-mail: l <Silviu.Doaga@continental-corporation.com>
aurentiusilviu@gmail.com

**Comment by silviulaurentiu** [comment]
It works supper!
The only thing that is missing is to auto-height all selected rows by double click on left mouse button. Now, the auto-height works only for each row, not for all of them into one single click.

**Comment by MKleusberg** [comment]
Thanks for testing!

Are you sure the auto height changed? And which version were you using before? I have just tried it with and without the changes I made and with the 3.11.2 release - and at least on my system it looks like it doesn't work in any of these version.

**Comment by silviulaurentiu** [comment]
You are right!
  The height changing is not working also in the old versions. So, your change not affected the height changing of the rows. I only want to say that this is another topic which can be improved in the tool.

  Many thanks!

**Comment by MKleusberg** [comment]
Closing this issue then because the original enhancement has been implemented and doesn't seem to break anything :smile:
