### ISSUE TITLE
Attach Database doesn't escape filepath of selected file

### ISSUE THREAD

**Issue by BitwiseX** [sqlitebrowser/sqlitebrowser#2002]
The Attach Database menu option doesn't escape the filepath of the selected file. If a filepath has a ' in it then it fails with a messagebox showing an SQL syntax error like so:

![aaa](https://user-images.githubusercontent.com/45967660/65379713-710eb200-dcc4-11e9-8757-b0ba6715646f.jpg)

Unlike double quotes, single quotes are perfectly valid characters on Windows file paths (and IIRC both single and double quotes are both valid in Unix OSes), so I'd imagine this effects all OSes.

**Comment by justinclift** [comment]
Oh, interesting bug, thanks for reporting it.

Sounds like it'll be an easy fix too. :smile:

**Comment by mgrojo** [comment]
It has to be fixed now. Could you confirm it with tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest) and close this issue?

**Comment by BitwiseX** [comment]
Sorry for the delay; had some family stuff and this issue completely slipped my mind.

Closing the issue. Thanks!

**Comment by mgrojo** [comment]
Great! Thank you for reporting.
