### ISSUE TITLE
[BUG] database table is locked after exporting data as sql script

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2008]
Details for the issue
--------------------

#### What did you do?

1. Create new in-memory db
2. Create a table `create table a(name text);`
3. Export it as sql (File -> Export -> as SQL file -> Export schema only)
4. Drop table `drop table a;`

#### What did you expect to see?

The table is dropped.

#### What did you see instead?

An error `database table is locked`

Useful extra information
-------------------------
`Write Changes` command does not make any difference.

#### What operating system are you using?

WIndows 8.1

#### What is your DB4S version?

3.11.2

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Confirmed.  Thanks for this.
Its the export thats doing it.  If you don't export it, then yes, the table can be deleted.
So yes, if you export, close, import, then you can delete the necessary tables.  Not a nice workaround, but at least it do-able if you need to delete tables.

**Comment by T1mL3arn** [comment]
Just tried latest (Version 3.11.99 (Oct  3 2019)), cant reproduce the bug. Looks like it fixed.
