### ISSUE TITLE
[Feature Request] Change collation in `Modify Table` dialog

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2009]
Describe the new feature
--------------------------

Ability to set/unset collation from `Modify Table` dialog

Additional info
---------------

#### Do you have a screenshot? Please add screenshots to help explain your idea.

![collation example](https://user-images.githubusercontent.com/9349164/65662108-b8a38e00-e076-11e9-9bef-2fa638e6e184.jpg)

where

- `SQLite Default` removes collation from column definition
- Other options set explicitly specific collation for a column

**Comment by chrisjlocke** [comment]
And have you tried the nightly?

![image](https://user-images.githubusercontent.com/7872218/65666149-fb447680-e034-11e9-834d-04cac4d9ccd0.png)

https://nightlies.sqlitebrowser.org/latest

**Comment by T1mL3arn** [comment]
Obviously, I haven't. Thanks!

Found a little bug, though. I will create a separate issue for it.
