### ISSUE TITLE
Can't paste(edit) text manually in Edit Table wizard (sql query control)

### ISSUE THREAD

**Issue by DerkachAlex** [sqlitebrowser/sqlitebrowser#201]
With last update I can't manually edit sql query in Edit Table wizard.
I think this option is required! 
What do you think about it?

**Comment by DerkachAlex** [comment]
sorry. editable sql text is in Execute SQL tab.
wrong issue :)

**Comment by justinclift** [comment]
No worries at all. :grinning:
