### ISSUE TITLE
No Windows nightlies

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2010]
Details for the issue
--------------------
Just a note that there have been no Windows nightlies for a couple of days.  The .dmg's seem fine.

![image](https://user-images.githubusercontent.com/7872218/65665744-2a0e1d00-e034-11e9-9a57-8573b12fc781.png)

#### What did you do?
Went to the nightlies page on the website

#### What did you expect to see?
My gran baking cakes.

#### What did you see instead?
My uncle in his underpants.

Useful extra information
-------------------------
The founder of match.com, Gary Kremen, lost his girlfriend to a man she met on match.com

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
The last commit to our master branch was on 23rd September, so that seems correct?

**Comment by sky5walk** [comment]
Yes, this is the desired effect. 😉 
[Nightly builds only on repo changes. #1917](url)
Recompiling for no reason is superfluous and a security risk.
There was a hint of updating a readme.md with the commit verbage to briefly explain the reason for any new nightlies.

**Comment by justinclift** [comment]
Good point.  Do you have suggested wording I can cut-n-paste into the readme on the nightlies server?

Asking because I'm brain dead tired atm.  Not up for any kind of coherent writing. :innocent:

**Comment by sky5walk** [comment]
Yes, we discussed an automated approach to updating the readme.md with git log: --> https://github.com/sqlitebrowser/sqlitebrowser/issues/1917#issuecomment-513566359

**Comment by chrisjlocke** [comment]
Oopsie.  Sorry guys!  I'll go back to hiding! ;)

**Comment by mgrojo** [comment]
> Oopsie. Sorry guys! I'll go back to hiding! ;)

Not so fast @chrisjlocke :wink: You're right about this as @SilvioGrosso has pointed out. There is no Windows nightly and there have been several commits since 23-Sep, including yesterday. Some Windows compilation log to check @justinclift? Either it is failing or isn't being triggered.

**Comment by sky5walk** [comment]
Hope we can close this issue, since it delays closing others. 💡

**Comment by sky5walk** [comment]
Is the server on Holiday? 🎈

**Comment by justinclift** [comment]
Ahhh, I thought it was working ok.  Looking now...

(been focused on other things, sorry)

**Comment by justinclift** [comment]
Hmmm, server is off.  No idea why.  Guess I knocked the power cord while moving stuff around a few days ago and didn't notice. :frowning:

**Comment by justinclift** [comment]
macOS build is running now.  When that finishes I'll run the Win64 one.

When that finishes, I'll take a look into the Win32 build problem.  Pretty sure it's something to do my [commit last month](https://github.com/sqlitebrowser/sqlitebrowser/commit/bf62a6e441155f91545a5ee197ddd1c9a3610b1d) to make the Win64 build work ok with updated Qt.

**Comment by justinclift** [comment]
Hmmm, Qt 5.12.6 is available too.  Might as well update the Win64 platform to that before I build the new binaries there.

**Comment by justinclift** [comment]
New Win32 and Win64 binaries have been built, and are on the server now.

* Before building the Win64 ones, the box was updated to Qt 5.12.6 (from 5.12.5).  Hopefully that works out ok.
* The Win32 builds turned out to be an easy fix (I'd used a mistaken comparison test in that previous commit) if a bit time consuming to investigate.

**Comment by MKleusberg** [comment]
Let's close this issue :smile:
