### ISSUE TITLE
[BUG] Collation does not change for 1-char-name table

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2011]
Details for the issue
--------------------

#### What did you do?

1. Create a table with dialog
2. Enter exactly 1 char for name, e.g `a`
3. Click `Add Field`
4. Enter some name (don't let its default name)
5. Try to change collation

#### What did you expect to see?

Collation changes.

#### What did you see instead?

Collation doesn't change.

Useful extra information
-------------------------

Just tried [latest build](https://nightlies.sqlitebrowser.org/latest/) with the collation changing feature and found this little bug.

#### What operating system are you using?

Win 8.1

#### What is your DB4S version?

Version 3.11.99 (Sep 23 2019) portable

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Thanks! This is an interesting bug :smile: It looks like this doesn't depend on the number of characters in the table name but on the fact that you just edited the field name before setting the collation. Changing anything else in between the name and the collation makes it work. I think I have fixed this issue now. Can you try tomorrow's nightly build and see if it's working for you as well? :smile:

**Comment by T1mL3arn** [comment]
Nightly builds for windows are fixed, so I tested it and looks like bug is fixed with b4c8ec9. Thanks!
