### ISSUE TITLE
Inserting row failed: not an error

### ISSUE THREAD

**Issue by mischlrebl** [sqlitebrowser/sqlitebrowser#2015]
hi all

I am receiving the message attached when trying to import a specific csv file. 
How will I be able to track down the problem? 
On line 17816 -as there is also a header line - I am not able to see a specific point.

Thx in advance for any help. As the file includes some customer data I am not able to share it here directly.

Cheers
![2019-10-02 17_08_11-Window](https://user-images.githubusercontent.com/28529799/66056895-1aad3900-e538-11e9-8082-7da053c9c057.png)

**Comment by chrisjlocke** [comment]
WHich version of DB4S?  I'd recommend trying the nightly.
It is more likely a delimiter type error - either more or less columns than
there should be?

You can't share the data, as it contains names and addresses?  Can you try
editing the data to trial and error the import?  So if its an address,
replace it with the letter A, etc.  Get it down to the basics (even
pinpointing it to the row, then the field)

Are there any fields that don't match fields previously?

**Comment by mischlrebl** [comment]
thank you for the feedback @chrisjlocke 

The nightliy brought no success.
I was able to track three times a ; inside a "..." but that didn't help.

The file is 63000 lines long and I cannot find a particular part by random search of about 1000 lines that fail.

Is it somehow possible to find the line(s) causing the the message by the record number? 
That would be just for future use or better user information.
At the end I solved it: they were " inside a "..."

**Comment by chrisjlocke** [comment]
Thanks for the feedback.
Delimiters within delimiters would cause confusion.  Was the line number reported any good?  I usually use Notepad++ to show line numbers, but not many people know that good ol' Notepad can also show line numbers.  Click 'View' and 'Status bar' to show the .... well, the status bar.  That shows the line and column number of the cursor.

![image](https://user-images.githubusercontent.com/7872218/66116914-75dc3b80-e5cb-11e9-9657-a3a063423c11.png)
