### ISSUE TITLE
display the sqlite version being used by sqlite browser

### ISSUE THREAD

**Issue by MindMapMaker** [sqlitebrowser/sqlitebrowser#2017]
Describe the new feature
--------------------------
Display the sqlite version being used by sqlite browser

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by scottfurry** [comment]
This is not difficult to implement and is actually useful in some way.
Let me take this one.

**Comment by scottfurry** [comment]
![AboutDlg](https://user-images.githubusercontent.com/6686571/66095115-9bc5f980-e553-11e9-80e9-54d8f414c34b.png)
I forgot about this... It already exists.
@MindMapMaker, is the version not being reported correctly in your version?
See output from select Help Menu->About

**Comment by mgrojo** [comment]
@MindMapMaker I'm going to close this issue, since it is provided in the last release version 3.11.2 which you can download from https://sqlitebrowser.org/dl/
