### ISSUE TITLE
64-bit windows build?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#202]
A user on Twitter mentioned that 3.5.0 is crashing on Windows when trying to open an 11GB SQLite database file.

The thought occurred to me that maybe if we can provide a 64-bit windows version (instead of Win32), maybe that would work.

Though, I have absolutely no idea where to even start.  Maybe we need to look into the "free" version of Visual Studio that (from dodgy memory) Microsoft started making available a while back?

Anyone have ideas/thoughts/etc? :smile:

**Comment by Z4us** [comment]
Depends on the file system. If they still use FAT32 nothing helps

http://en.wikipedia.org/wiki/Large_file_support

**Comment by justinclift** [comment]
For reference, the problem report on Twitter is here:

  &nbsp; &nbsp; https://twitter.com/MikeSchwert/status/564645625547870208

I'm pretty sure he's not using FAT32.  He wouldn't have an 11GB file to open if he was. :wink:

**Comment by glawrence** [comment]
Just to help dodgy memory @justinclift as I suffer the same, I believe you mean Visual Studio Community Edition, which is better than the old Express Editions and more information is at http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

**Comment by justinclift** [comment]
@glawrence Thanks yeah, that's probably it. :smile:

**Comment by justinclift** [comment]
We now have a 64-bit windows build (thanks @rp-), so closing this. :smile:
