### ISSUE TITLE
Modal alert hell when attempting to set multiple rows to NULL on NOT NULL column

### ISSUE THREAD

**Issue by broofa** [sqlitebrowser/sqlitebrowser#2021]
Details for the issue
--------------------

#### What did you do?

Attempted to set a NOT NULL column value to NULL with multiple rows selected.  As shown in the screenshot below( `name` column does not allow NULL values):
![image](https://user-images.githubusercontent.com/164050/66669962-78631480-ec0d-11e9-80c9-771be443364b.png)

#### What did you expect to see?

Either "Set to NULL" should be disabled when the selection includes a column defined as NOT NULL, or the command should fail with a single alert stating, "NOT NULL constraint failed"

#### What did you see instead?

Was forced to click through one alert per field in the selection (11 alerts in this case), with no way of suppressing further alerts or aborting the command.

Useful extra information
-------------------------
> DB4S v3.11.1 [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.0.1 community (based on SQLite 3.26.0)
> and Qt 5.11.3

**Comment by SilvioGrosso** [comment]
Hello @broofa 

> Was forced to click through one alert per field in the selection (11 alerts in this case), with no way of suppressing further alerts or aborting the command.

Yep. This occurs also on Windows 10 - 64 bit.
Tested the last nightly build, the one with QT 5.12. 5

**Comment by mgrojo** [comment]
@broofa I've committed an improvement that will check the existence of a NOT NULL constraint in one of the columns in the selection and in that case will reject the modification with this message:
 
"Cannot set selection to NULL. Column %1 has a NOT NULL constraint.", being %1 the column name.

Could you install tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/) and report back any possible misbehaviour?

**Comment by broofa** [comment]
Checked nightly.  Looks good, thanks!
![image](https://user-images.githubusercontent.com/164050/71023357-6d1de080-20b7-11ea-99fb-1e39609947eb.png)

**Comment by MKleusberg** [comment]
Awesome :smile: Closing this issue then.
