### ISSUE TITLE
isnull

### ISSUE THREAD

**Issue by Fabre77** [sqlitebrowser/sqlitebrowser#2022]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by SilvioGrosso** [comment]
Hello @Fabre77 

Your bug report IS NULL in that you don't provide enough information to help us to help you 😄

Having said that, I have tried the Browse Data tab, with a Table where some records are set as NULL. 
Both filters work as expected:
-  =NULL (to filter NULL records);
- <>NULL (to not filter NULL records).

If you also test the some SQL code, in the  Execute SQL tab, everything works as expected:
- (WHERE 'xxyy' IS NULL - NOT NULL).
- CREATE TABLE t1 (id INTEGER NOT NULL etc etc).

Please, try to provide more information about your problem...

**Comment by mgrojo** [comment]
@Fabre77 I'm going to close this issue due to lack of details and response about the problem. Feel free to reopen it if you can add more information to the report.
