### ISSUE TITLE
sqlitebrowser.org certificate expired

### ISSUE THREAD

**Issue by Paul-E** [sqlitebrowser/sqlitebrowser#2023]
The certificate for https://sqlitebrowser.org/ has expired. Right now visitors see a certificate error when they try to visit the website. This may be a repeat of #1945

![Screenshot from 2019-10-13 17-49-31](https://user-images.githubusercontent.com/4206484/66722981-0bed3e80-ede2-11e9-8e15-241f1c19bd76.png)

**Comment by justinclift** [comment]
Oops, yeah it is.  Thanks. :smile:

**Comment by justinclift** [comment]
Cert updated.  It's probably a good reminder to look into automating this. :smile:

**Comment by scottfurry** [comment]
On 2019-10-13 5:50 p.m., Justin Clift wrote:
>
> Cert updated. It's probably a good reminder to look into automating 
> this. 😄
>
Or at least a calendar entry reminder a couple of days before hand.

**Comment by justinclift** [comment]
Oh, they send out reminders via email.  Which I get and then mentally file as "must get around to this... ". :innocent:

**Comment by justinclift** [comment]
As a data point, I've started mucking around with stuff in our sponsored Digital Ocean account.

Just playing around / trying things out at the moment.  One of the useful looking points I'll get around to investigating is Certbot's (the cli tool for Lets Encrypt certs) support for Digital Ocean.  It apparently works, and the docs make it seem fairly simple:

&nbsp; &nbsp; https://certbot-dns-digitalocean.readthedocs.io/en/stable/
