### ISSUE TITLE
Feature to plot with secondary Y-axis (Y2)

### ISSUE THREAD

**Issue by sg0wtham** [sqlitebrowser/sqlitebrowser#2026]
Describe the new feature
--------------------------
Most of the times the analysis requires you to compare 2 different sets of data. Unfortunately, they have got different scales. It can be a nice feature to add a secondary y-axis (Y2).

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No this is not related to any issue

#### Does this feature exist in another product or project? Please provide a link.
This feature is a very common one. It can be found in Matplotlib, LibreOffice, etc.

#### Do you have a screenshot? Please add screenshots to help explain your idea.

<img width="443" alt="Screenshot 2019-10-22 at 5 56 47 PM" src="https://user-images.githubusercontent.com/11979051/67285556-6890dd80-f4f5-11e9-8801-6b282949ddd9.png">
( Image Credits: https://www.graphpad.com )

**Comment by mgrojo** [comment]
@sg0wtham Thanks to @anandsanto's contribution this will be in our next release. If you want to give it a try, it will be available in tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/).

**Comment by sg0wtham** [comment]
Neat and perfectly suits my needs. Thanks a lot, @anandsanto for this great addition!

**Comment by mgrojo** [comment]
I assume we can close this issue, then. Thanks!
