### ISSUE TITLE
[FeatureRequest] Add project file name to window title

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2027]
Describe the new feature
--------------------------
Projects are excellent tools to house our query prototypes, but we only see the latest opened database in the window title? How does the user know if they are in a working project or an unsaved mode of the current database?
Please add to the window title:
FROM: 
DB Browser for SQLite - C:\my-currently-opened-database.db
TO:      
DB Browser for SQLite - C:\my-currently-opened-project.sqbpro [C:\my-currently-opened-database.db]

Additional info
---------------

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
N/A

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Self-explanatory.

**Comment by mgrojo** [comment]
That makes sense, but wouldn't it be too long? Maybe one of the file names, or both, should be displayed without path.

**Comment by sky5walk** [comment]
Tough call. I prefer both files show their full paths since network or local is a common concern.
If I have to choose, I prefer the project show just its filename, and the loaded database its full path+filename.

**Comment by mgrojo** [comment]
Maybe we can put the path in the DB file only when it is different to the one of the project file. What do you think?

**Comment by sky5walk** [comment]
That sounds good. However, that will always be the case for my use model.
I create many databases at random intervals and store them in a certain path.
I prefer to keep project files in a parallel folder for tinkering, plotting, filtering, attaching.
```
PROJECT1-PATH
--DB-HERE
-----db1
-----db2
-----dbn
--PRJ-HERE <-- Each project may reference and/or attach multiple db's from any location on disk.
-----1.sqbpro
-----2.sqbpro
-----n.sqbpro
PROJECT2-PATH
```

**Comment by mgrojo** [comment]
@sky5walk It will be implemented in the next nightly build as was commented here. In your case, both filenames will have full paths, but when stored in the same location, the DB filename will directly hint it. Could you report any unexpected behaviour, as usual?

**Comment by sky5walk** [comment]
Sorry, today's Windows nightly did not have this feature?
Please clarify:
> @sky5walk It will be implemented in the next nightly build as was commented here. In your case, both filenames will have full paths, but when stored in the same location, the DB filename will directly hint it.

My requirement is to know if I am within an sqbpro file or within a database?
If I store an sqbpro file to the same path as the opened db, will the window title show?
`DB Browser for SQLite - C:\mypath\my-currently-opened-project.sqbpro [my-currently-opened-database.db]`

If I store an sqbpro file to a different path as the opened db, will the window title show?
`DB Browser for SQLite - C:\mypath\my-currently-opened-project.sqbpro [C:\mydbpath\my-currently-opened-database.db]`

**Comment by mgrojo** [comment]
@sky5walk Yes, that is what you can expect.

Sorry, there is a problem with the Windows nightly build. The last built one is in commit 3577c71193979fec2aaa26d6802dd0055873cc54 (https://nightlies.sqlitebrowser.org/win64/commit.txt)  which is 4 days old. @justinclift, could the Windows build script upload the log the server, so we can check where is the error?

**Comment by sky5walk** [comment]
No change today.

**Comment by sky5walk** [comment]
Ok, ran the v191107 nightly and this feature request is almost there.
The window title updates its initial state of "sqbpro+[loaded database]".
But, the title does not update on subsequent 'close database' and 'open database' iterations.
And, the sqbpro is forgotten when changes are detected.
Meaning, when I attempt to save my current sqbpro file, I must navigate and accept an overwrite prompt on my current project. 😞 
It gets frustrating after browsing 3 or 4 databases. I may make changes to my underlying SQL tabs and want to save them to my common sqbpro.

**Comment by mgrojo** [comment]
Sorry, @sky5walk, but I could not reproduce that problem. Could you give details about the specific steps to reproduce it?

**Comment by sky5walk** [comment]
Open an sqbpro file with a database. The title reflects this. Close the database but not the sqbpro. The title drops both. Load another database and the title only shows the database.

**Comment by mgrojo** [comment]
Ok. I understand now. So you were taking advantage of something I considered a bug: when the database was closed, the project file was remembered. How were you using this? Did you use the same project file with several database files with the same schema? Did it work well? In fact, that was completely unintended, at least on my part. 

The new model is: when you open a project file, that opens a project and an associated database. When you use the close database while working with a project, in fact you are closing the project, because a project without a database does not make sense.

**Comment by sky5walk** [comment]
Ouch, your new model is not flexible.
Yes, I do have many databases of similar schema's. But, that is not a requirement for projects.
The project is superior to a single database file.
The project can perform house cleaning and attaches and detaches and common or complex queries on dissimilar databases.
Please do not break my use model which I have shown other users for more than a year.

**Comment by mgrojo** [comment]
Don't worry, if the previous model was working correctly, I'll undo the changes related to closing the project at the same time as the database and apply that concept to the title, which has to reflect the fact that a project file can be open without a database. That fact still surprises me, and I think it was unintended, but maybe I'm wrong, because that implementation is previous to my involvement to the development. But at least, it isn't orthogonal, that a project cannot be born without an open database, but can then evolve to that state. In any case, I can see the use model that you can win from that.

**Comment by sky5walk** [comment]
Thanks! 
I think this will reduce the prompt to overwrite my existing sqbpro file on each open and close of a db?!!
> a project file can be open without a database. That fact still surprises me, and I think it was unintended, but maybe I'm wrong

Imagine a project where I only execute SQL commands.
That way I can ATTACH db1, db2, dbn. 😎 
And I do not suffer delays with very large db's.

**Comment by mgrojo** [comment]
@sky5walk The next nightly should allow the model that you are using. Please confirm that it's working correctly and as expected.

**Comment by sky5walk** [comment]
Thanks! I never thought projects were closed on database close. That explains a lot. 🤔

**Comment by sky5walk** [comment]
Works great!
This is approaching nirvana! 💯 
I will open another issue for some nitpicks. 😁
