### ISSUE TITLE
Add Zoom In / Zoom Out /"Zoom to fit window" Feature to Image viewer

### ISSUE THREAD

**Issue by lavaman13** [sqlitebrowser/sqlitebrowser#2029]
Describe the new feature
--------------------------
I love how an image in a blob column con be viewed live in the "Edit Content" window.  However my images are often big and by default the window only shows a small part of it.  I need to scroll horizontally and/or vertically to see different things in the image.  It would be great to have a "zoom in", "zoom out", "zoom to fit window size" feature in this  "Edit Content" window.

Maxime

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Good idea. :smile:

**Comment by qci-amos** [comment]
Just to add a bit more on this... hopefully to explain how useful this would be:

I love the Image mode for database cells. It's a very convenient way to summarize the result of an entire row, so I end up using these cells to browse my data from a high level. Furthermore, I often even use DB Browser for SQLite as a presentation tool over video chat screen share. That way, if someone says they want to know if I tried x, y, or z, I can find that result and pull it up in this image cell.

When using video chat however, the images are often too small to see for other people on the chat and I need a way to make it bigger. Currently, the best solution I've found is to:

1. right click on the image
2. do `Print ...`
3. resize the Print Preview window to fill my screen
4. the Print Preview window has zoom and scrolling features

**Comment by MKleusberg** [comment]
@lavaman13 and @qci-amos Can you check out tomorrow's nightly build (you will find it [here](https://nightlies.sqlitebrowser.org/latest/)) and see if the new buttons I added are working for you? :smile:

**Comment by justinclift** [comment]
@lavaman13 Do you have time to try out those new buttons, and let us know if they work well for you? :smile:

**Comment by lavaman13** [comment]
Hi Justin,

Yes, I was planning on testing it this weekend...

Maxime

**Comment by lavaman13** [comment]
Hi again Justin,

I just checked out the 6th of June build (win64.msi) and the new buttons
for the image "zoom in / zoom out / fit to window" work great!  Thanks for
the update!!!
FYI:
- multiple clicks on the "Reset the scaling to match original image" button
have no effect on the image (the first click does its job and subsequent
clicks do nothing)
- multiple clicks on the "Set the scaling to math the size of the viewport"
alternate between scaling to the viewport and scaling to the original image
size
I don't care about this behavior, it's fine as far as I'm concerned,
I just thought you should know.

Thanks again for the update!

Maxime

Le sam. 6 juin 2020, à 01 h 28, Justin Clift <notifications@github.com> a
écrit :

**Comment by justinclift** [comment]
Out of curiosity, would it make sense to have one of those be the default for viewing images?

eg: when the image viewer is showing, if you change to a different cell then the image there automatically has the "fit to window" approach or something applied?

Mind you, I've not tried out this new code, so I might not be making sense. :wink:

**Comment by lavaman13** [comment]
Hi Justin,

For sure I prefer a default behavior of "image fits in viewport". Possibly
other people would want it the other way around. 3 alternatives:
1) add an option in the "Edit --> Preferences" menu;
2) add a checkbox somewhere in the "Edit database cell" window to select
what default behavior to use;
3) "remember" the setting of the previous image shown and use that.  I
don't know how you could program this (to me it sounds complicated), but it
would have an added value:  you could also "remember" the zoom level and
the cursor position of the current image (ex:  you are zoomed in on the
bottom left hand corner) and apply those same parameters to the next
image.  If someone wants to compare the same feature in multiple rows, it
would be a breeze to just setup the image viewing parameters (zoom level
and cursor positions) for the first image and then scroll down the list of
blobs... this feature would be useful if all images are roughly the same
size and show the same kind of thing.  Otherwise reverting back to the
default behavior would probably be better!

Maxime

**Comment by MKleusberg** [comment]
Maybe we should change the default to "scale image to fit the viewport if it is larger than the viewport, or scale image to original size if it is smaller than the viewport". I'm saying this because very small images look bad when not zoomed. What do you think?

**Comment by lavaman13** [comment]
Yes, great idea! (And sounds a lot simpler to implement!)

Maxime

**Comment by justinclift** [comment]
> What do you think?

Sounds good to me too. :smile:

**Comment by MKleusberg** [comment]
@lavaman13 The next nightly build has the automatic scaling for large images while leaving smaller images in their original size by default. Can you give that a final try? :smile:

**Comment by lavaman13** [comment]
Yes, no problem!

Maxime

**Comment by lavaman13** [comment]
Hi Martin, Justin,

I tested last night's build (DB.Browser.for.SQLite-win64.msi
<https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi>,
11 June 00:31).  Works fine (both with very small and very large
pictures).

Thanks!

Maxime


Le lun. 8 juin 2020, à 14 h 52, Maxime Cadotte <maxime.cadotte@gmail.com> a
écrit :

**Comment by justinclift** [comment]
Awesome.  Good stuff guys. :smile:
