### ISSUE TITLE
Running a query and % is dropped?

### ISSUE THREAD

**Issue by StormTrooper** [sqlitebrowser/sqlitebrowser#203]
Table:

BEGIN TRANSACTION;
CREATE TABLE `table1` (
	`Field1`	TEXT
);
INSERT INTO `table1` VALUES ('testing');
INSERT INTO `table1` VALUES ('123');
INSERT INTO `table1` VALUES ('87654');
COMMIT;

Query:
select * from table1 where CAST(Field1 AS Text) LIKE '%2%'

1 Rows returned from: select * from table1 where CAST(Field1 AS Text) LIKE '2%' (took %3ms)

The % in front of '2%' is dropped and no results are returned.

Ver 3.5.1
SQlLite version: 3.8.8.2

**Comment by justinclift** [comment]
Ouch, that doesn't sound good.  Um, hopefully one of the guys has time to look into it in the next couple of days.

**Comment by StormTrooper** [comment]
Did another test and ran from the sqlite3 cli - working fine.

sqlite> select * from table1 where CAST(Field1 AS Text) LIKE '%2%';
123

**Comment by justinclift** [comment]
Yep, sounds like a definite bug then.

**Comment by StormTrooper** [comment]
Some more info which hopefully points to where the problem could be:

like '%6% - working.
like '%3% - is changed to like '6%';
like '%2%'; - is changed to like '2%';
like '%1%'; - is changed to like '7%';

Very odd. :)

**Comment by samir-aguiar** [comment]
I think I've got it. :smile: 
The "%2" was being seen as a placeholder by QString::arg() when doing replacements.

**Comment by StormTrooper** [comment]
Great stuff. That was quick - thanks. Will check in the nightly tomorrow.

**Comment by justinclift** [comment]
@samir-aguiar Awesome. :grinning:

**Comment by StormTrooper** [comment]
Tested on the latest nightly. Now working. Thanks a lot guys!

**Comment by justinclift** [comment]
@StormTrooper Excellent, thanks for testing and confirming back. :smile:
