### ISSUE TITLE
[BUG] Cannot set field name: There already is a field with that name

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2030]
Details for the issue
--------------------

#### What did you do?

1. Create inmemory db
2. Create table
3. Name the table `tbl`
4. Add field and name it `photo_url`
5. Add field and try to name it `photo`

#### What did you expect to see?

The field gets name `photo`

#### What did you see instead?

Error: `There already is a field with that name`

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: 8.1

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: Version 3.11.99 (Oct  3 2019) (a nightly build I guess)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by T1mL3arn** [comment]
Adding a field `photo` with query below works

```sql
alter table tbl add column 'photo' BLOB;
```

**Comment by SilvioGrosso** [comment]
Hello @T1mL3arn 

I confrim your issue with the latest nightly build on Windows 10 - 64 bit:
Version 3.11.99 (Oct 10 2019)
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.5
SQLite Version 3.30.0

Strangely enough, if you add a field as "photo" and later a new field as photo_url everything works as expected...
To reproduce this issue you have to add "photo_url"and later "photo" as already reported.

**Comment by mgrojo** [comment]
@T1mL3arn I'm not able to reproduce this. It is either fixed in a current nightly, or I am missing something. Could you check again with a recent nightly build?

**Comment by T1mL3arn** [comment]
@mgrojo I am not able to reproduce the issue in `Version 3.11.99 (Nov 23 2019)`. Looks like it is fixed now.
