### ISSUE TITLE
date

### ISSUE THREAD

**Issue by ALexAl123** [sqlitebrowser/sqlitebrowser#2031]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by SilvioGrosso** [comment]
I suppose this "bug-report" can be discounted as an error - troll...

**Comment by justinclift** [comment]
@ALexAl123 Was this bug repo on purpose, or just by accident?  Are we ok to close this? :smile:

**Comment by ALexAl123** [comment]
Sorry,  just by accident.

пн, 28 жовт. 2019 о 05:53 Justin Clift <notifications@github.com> пише:

**Comment by justinclift** [comment]
No worries @ALexAl123, thanks for letting us know. :smile:
