### ISSUE TITLE
No Autocomplete in Database after Import CSV Data

### ISSUE THREAD

**Issue by marcelkusch** [sqlitebrowser/sqlitebrowser#2033]
Details for the issue
--------------------

#### What did you do?
I made an Database and importet the data from a CSV file. 
The problem is that there is no autocomplete by filling data.
When i make a database without importing CSV data it works.

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.99 (Oct 30 2019) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.30.0
> and Qt 5.12.5

**Comment by justinclift** [comment]
Interesting problem.  Sounds like a bug of some sort. :wink:

**Comment by mgrojo** [comment]
This is controlled by a preference. You can set a greater number in "Preferences > Data Browser > Threshold for completion and calculation on selection" to get the automatic completion for bigger tables.

**Comment by marcelkusch** [comment]
Thank you. It works.

**Comment by justinclift** [comment]
Awesome! :smile:
