### ISSUE TITLE
Failed to browse data under windows7, cannot seek string itereator after end

### ISSUE THREAD

**Issue by skys215** [sqlitebrowser/sqlitebrowser#2036]
Details for the issue
--------------------

#### What did you do?
I compiled sqlitebrowser under Windows7 with Visual Studio 2019, compiled successfully but failed to browse data.

#### What did you expect to see?
Expect to see the data of the table.

#### What did you see instead?
It poped up an error.

Useful extra information
-------------------------
Steps:
1. Clone the repo
2. Run `cmake -G "Visual Studio 16 2019" -Wno-dev`
3. Modified the qt installation path, which is set in `cmake_install.cmake`, `variables.wxi`, `CMakeLists.txt`, `CMakeCache.txt` (not sure where to change it, so I edited all the file which includes default qt path, but thats not related to this issue)
4. Build `ALL_BUILD` as the [documentation ](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Step-12-%E2%80%94-Compile-DB4S-using-MSVC)says
5. After that, build `INSTALL` like the [doc](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Step-13-%E2%80%94-Install-DB4S-locally)
6. Run the sqlitebrowser from `C:\Program Files(x86)\sqlitebrowser.exe`
7. Open a database, select browse data and the error appears:
![image](https://user-images.githubusercontent.com/4977935/68098824-e4c5f080-fef9-11e9-94ed-25243b232d80.png)

Backtrace:
```
>	DB Browser for SQLite.exe!std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>::_Verify_offset(const __int64 _Off) Line 1885	C++
 	DB Browser for SQLite.exe!std::_Get_unwrapped_n<std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,__int64,0>(const std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> & _It, const __int64 _Off) Line 361	C++
 	DB Browser for SQLite.exe!std::equal<std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,bool <lambda>(unsigned char, unsigned char)>(const std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> _First1, const std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> _Last1, const std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> _First2, compare_ci::__l2::bool <lambda>(unsigned char, unsigned char) _Pred) Line 2409	C++
 	DB Browser for SQLite.exe!compare_ci<std::string>(const std::string & a, const std::string & b) Line 25	C++ (src\sql\sqlitetypes.h)
 	DB Browser for SQLite.exe!compare_ci<std::string>(const std::string & a, const char * b) Line 30	C++ (src\sql\sqlitetypes.h)
 	DB Browser for SQLite.exe!sqlb::Field::isInteger() Line 288	C++ (src\sql\sqlitetypes.cpp)
 	DB Browser for SQLite.exe!sqlb::Field::affinity() Line 328	C++ (src\sql\sqlitetypes.cpp)
 	DB Browser for SQLite.exe!SqliteTableModel::setQuery(const sqlb::Query & query) Line 143	C++ (src\sqlitetablemodel.cpp)
 	DB Browser for SQLite.exe!TableBrowser::updateTable() Line 439	C++ (src\TableBrowser.cpp)
 	DB Browser for SQLite.exe!MainWindow::populateTable() Line 624	C++ (src\MainWindow.cpp)
 	DB Browser for SQLite.exe!MainWindow::mainTabSelected(int __formal) Line 1195	C++ (src\MainWindow.cpp)
 	DB Browser for SQLite.exe!MainWindow::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) 行 439	C++ (sqlitebrowser_autogen\include_Debug\UVLADIE3JM\moc_MainWindow.cpp)
 	[External code]	
 	DB Browser for SQLite.exe!main(int argc, char * * argv) Line 13	C++ (src\main.cpp)
 	[External code]	
```
I tried to debug by myself to check if there's some invalid character in the field of the table I opened.
According to the backtrace, I assumed that the bug starts here where passed `LONG` as parameter of function `compare_ci` which is a data type of the first field on my table which I'm trying to browse:
![image](https://user-images.githubusercontent.com/4977935/68099205-15a72500-fefc-11e9-9b9b-daa11ac7d13e.png)
v3.11.2 has no problem on browsing data.
#### What operating system are you using?

- [X] Windows: ( 7 version: 7601 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: ebb5e3b1114772879fe71cb13d7b56332a27fe3a

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  It seems like you set everything up correctly, so this is probably something with the current DB4S code not being 100% compatible with VS2019 yet.

**Comment by mgrojo** [comment]
@skys215 Could you try with this change? I think this will solve your problem, and I think it does what was expected, but @MKleusberg should confirm that before we can commit the change.

```diff
diff --git a/src/sql/sqlitetypes.h b/src/sql/sqlitetypes.h
index 4efab688..7551d107 100644
--- a/src/sql/sqlitetypes.h
+++ b/src/sql/sqlitetypes.h
@@ -18,6 +18,8 @@ bool contains(const C& container, E element)
 template<typename T>
 bool compare_ci(const T& a, const T& b)
 {
+    if(a.length() != b.length())
+        return false;
     return std::equal(a.begin(), a.end(), b.begin(), [](unsigned char c1, unsigned char c2) {
         // TODO: Do we need to make this UTF-8-aware?
         return std::tolower(c1) == std::tolower(c2);
```

**Comment by justinclift** [comment]
@skys215 Ping? :smile:

**Comment by skys215** [comment]
Sorry for the late reply
It works well now, thanks!
