### ISSUE TITLE
DB4S crashes on Ctrl+Spacebar in SQL tab

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2038]
Details for the issue
--------------------

#### What did you do?

1. Open SQL tab
2. Press `Ctrl + Spacebar`

#### What did you expect to see?

List of autocomplete items (or at least nothing)

#### What did you see instead?

Program crashes

Useful extra information
-------------------------

Win 8.1
DB4S Version 3.11.99 (Nov  7 2019)

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Thanks for reporting this! The crash should be fixed in tomorrow's nightly build. No list is going to pop up though. I'm not sure, maybe there is another keyboard shortcut for that - maybe somebody else knows that? :smile:

**Comment by T1mL3arn** [comment]
Tested on Version 3.11.99 (Nov  8 2019), no crash on Ctrl+Spacebar.

**Comment by justinclift** [comment]
Good stuff @MKleusberg!

Thanks for testing and confirming @T1mL3arn. :smile:
