### ISSUE TITLE
Manage COLLATE NOCASE in the Modify Index command

### ISSUE THREAD

**Issue by stenci** [sqlitebrowser/sqlitebrowser#2039]
Please add the management of COLLATE NOCASE to the Edit Index Schema dialog.

Using the Modify Index as is today one risks to *damage* a database.
Here is an example of the risky workflow: create an index with a command similar to:

    CREATE INDEX index_name ON table_name (column_name COLLATE NOCASE)

Then go to the Database Structure page, right click on the index just created and click on Modify Index: the Edit Index Schema dialog doesn't show the COLLATE NOCASE and clicking OK modifies the index removing the collation.

**Comment by MKleusberg** [comment]
Can you give the nightly build a try (assuming you're using Windows or macOS)? You can download it [here](https://nightlies.sqlitebrowser.org/latest/). In theory it should work with that :smile:

**Comment by stenci** [comment]
I just installed it on Windows and it works, thanks!

As a side note now I get this error every time I start the application:
![image](https://user-images.githubusercontent.com/5955495/68484324-ab93c600-0202-11ea-9794-0ec4c374d0ab.png)

**Comment by MKleusberg** [comment]
Awesome! Glad it's working for you now :smile:
