### ISSUE TITLE
Windows builds don't seem to include translations

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#204]
Installed DB4S 3.5.1 on Windows 7, then looked at the languages available in the Preferences dialog.  It only has "English (United States)" available in the drop down.  Also tried the latest nightly, which has @samir-aguiar's latest code in it, and that has the same limitation.

Wondering if this could be a packaging problem on Windows or something?

**Comment by mafagafogigante** [comment]
So they should be there... Was trying to find the languages in the dropdown menu and thought that it was a bug in my installation. Hope someone figures this one out.

**Comment by schdub** [comment]
@mafagafogigante, wich version do you use?
Should be fixed after #310.

**Comment by mafagafogigante** [comment]
3.6.0 (release)

**Comment by schdub** [comment]
@mafagafogigante, it's already fixed
![screenshot from 2015-05-20 02 10 32](https://cloud.githubusercontent.com/assets/1304776/7715979/15cdcebe-fe96-11e4-8c3e-c5471c7c7ef9.png)
You must wait for 3.7.0 version or use our Nightly build:
http://rp.oldsch00l.com/sqlitebrowser/

**Comment by mafagafogigante** [comment]
Oh, thank you for pointing this out. Should this issue be closed then?

**Comment by schdub** [comment]
@justinclift, we can close this? On screenshot is .exe from Nightly build.

**Comment by justinclift** [comment]
Yep, lets close it. :smile:
