### ISSUE TITLE
/usr/lib64/libQt5Xml.so.5.9.4: undefined reference to `QXmlUtils::isPublicID(QString const&)@Qt_5_PRIVATE_API'

### ISSUE THREAD

**Issue by zdavatz** [sqlitebrowser/sqlitebrowser#2045]
I am building from source on Gentoo Linux and `make -j9` fails with the following error, right after completing 100%:
```
/usr/lib64/libQt5Xml.so.5.9.4: undefined reference to `QXmlUtils::isPublicID(QString const&)@Qt_5_PRIVATE_API'
```
I am following this guide:
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

**Comment by MKleusberg** [comment]
This looks like something is wrong with your Qt5 build. ```QXmlUtils``` seems to be some internal class used by Qt's XML library and is not used by us directly. Unfortunately this means that I don't really know how I can help with this. Maybe you could try rebuilding the Qt (XML) library but I'm not sure if that would help.

**Comment by zdavatz** [comment]
Ok, thank you! I am closing this.

**Comment by MKleusberg** [comment]
Ok, no worries. If you should find some solution to it or need any more information from us regarding this, just let us know here.

**Comment by zdavatz** [comment]
I ended up with this command for Gentoo: 
```
emerge -1pa `qlist -CI dev-qt/*`
```
it worked really well. ;) so I stopped building from source.

**Comment by scottfurry** [comment]
@zdavatz - see my ebuild for source building DB4S [here](https://github.com/scottfurry/FurCaT_Funtoo/tree/master/dev-db/sqlitebrowser) (contains 9999.ebuild).

I've built against qt 5.12.5 without issues. I think that's the latest available qt version in gentoo tree at the moment.

**Comment by MKleusberg** [comment]
Cool :smile: Glad you could find a way to get it running!
