### ISSUE TITLE
How to pass regular expression flags (like ignore case, multiline etc)

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2046]
is it possible to use flags in `REGEXP` ?
This doesnt work as expected
```sql
select * from (
	select 'HELLO' as word
)
where word REGEXP '/el/i'
;
-- returns nothing
-- expected 'HELLO'
```

**Comment by MKleusberg** [comment]
Yes, it's a bit unfortunate that the ```/pattern/modifier``` syntax doesn't work. You can however use the ```(?flags)pattern``` syntax like this:
```sql
select * from (
	select 'HELLO' as word
)
where word REGEXP '(?i)el'
;
-- returns 'HELLO' as expected
```

Flags which should work are:
* ```i``` case insensitive
* ```m``` multi-line mode
* ```s``` . matches \n
* ```U``` swap meaning of greediness modifiers

Does this work for you? :smile:

**Comment by T1mL3arn** [comment]
> Does this work for you?

No, it doesn't. I get an error:

```sql
Execution finished with errors.
Result: invalid operand
At line 1:
select * from (
	select 'HELLO' as word
)
where word REGEXP '(?i)el'
;
```

I use `Version 3.11.99 (Nov  8 2019)` nightly build on Win 8.1. I will try the latest build if there is one.

**Comment by MKleusberg** [comment]
You're right. I have just recently exchanged the regular expression library because of issue #2040. So you will need a nightly build from Nov 12 or later :smile:

**Comment by T1mL3arn** [comment]
Just tried new nightly and it works.

**Comment by MKleusberg** [comment]
Awesome :smile: I have added some information on this to our Wiki page too because I think it might be useful for other users as well: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Regular-Expressions
