### ISSUE TITLE
Problem installing on MacOS with .dmg

### ISSUE THREAD

**Issue by VitaliiIsaenko** [sqlitebrowser/sqlitebrowser#2048]
I wanted to install the DB Browser for SQLite with .dmg install file. I was not able to do it, all I saw is an empty window with "Rider" (for some reason) title. I assume it should be an install window where I'd need to drag DB Browser icon to applications icon. 

- [x] Mac OS: ( _version:10.14.6)

DB Browser version:
- [x] 3.11.2

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Haven't heard mention of this specific problem before, so not really sure what to make of it. :frowning:

**Comment by VitaliiIsaenko** [comment]
Installation with homebrew works fine though :) 
```
$ brew cask install db-browser-for-sqlite
```

**Comment by justinclift** [comment]
Heh Heh Heh.

At least that's a workaround.  It's kind or ironic though, as I'm pretty sure Homebrew cask just downloads the same .dmg file and installs it.  At least it works. :smile:

**Comment by justinclift** [comment]
Been thinking this over.  Going to close this issue as you have a solution, and no-one else has reported the problem.

If it crops up for anyone else though, we'd better re-open this and see if we can figure out what's going wrong. :smile:
