### ISSUE TITLE
Export to XML or JSON

### ISSUE THREAD

**Issue by jsamosfbmoll** [sqlitebrowser/sqlitebrowser#2051]
# Feature request
I'd like to export my databases sqlite in a _XML_ or _JSON_.
This way is more easy to export data to other terminals in case that we need it.
Thanks for reading.

**Comment by T1mL3arn** [comment]
File -> Export -> Export to JSON

**Comment by MKleusberg** [comment]
@jsamosfbmoll Did the JSON export (File -> Export -> Table(s) to JSON) work for you? If you're having trouble with exporting to JSON, you can also install the [latest nightly build](https://nightlies.sqlitebrowser.org/latest/) which contains some improvements for the JSON export.

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
