### ISSUE TITLE
Significant performance degradation with new REGEXP

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2052]
```sql
select DISTINCT names, names_only from t
where ctg_id in (4,5) and (names REGEXP '@p' or names_only REGEXP '@p')
order by urls != '' desc, names asc, names_only asc
;
```

**Version 3.11.99 (Nov 20 2019) / Qt Version 5.12.6**: Result: 90 rows returned in **7567ms**
**Version 3.11.99 (Nov  8 2019) / Qt Version 5.12.5**: Result: 90 rows returned in **476ms**

Both DB4S use the same SQLite version 3.30.0

Table schema

```sql
CREATE TABLE "t" (
	"ctg_id"	INTEGER NOT NULL,
	"names"	TEXT DEFAULT '',
	"urls"	TEXT DEFAULT '',
	"names_only"	TEXT DEFAULT ''
)
```

Data was generated on http://convertcsv.com/generate-test-data.htm .
To recreate data grab settings from https://pastebin.com/5qyhQDSn and use it with `Load Saved Form (Settings)`. Dataset will be  ~57000 rows.

Win 8.1 x64

**Comment by MKleusberg** [comment]
Fair point. I only tried the new regex implementation with ~10 rows or so :grinning: 

Can you check again with tomorrow's nightly build? In theory it should reduce the time to roughly the old value.

**Comment by T1mL3arn** [comment]
Tested. Now it works even faster! Thanks.

**Comment by MKleusberg** [comment]
Awesome! Out of curiosity: how long does it take to execute your query with the new version?

**Comment by T1mL3arn** [comment]
@MKleusberg

old (fast): ~ 480ms
new (with cache): ~ 380ms
