### ISSUE TITLE
[REGRESSION] REGEXP does not match unicode chars

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2054]
#### What did you do?

Run query
```sql
with tbl as (
	select 'hello 1' as name
	union
	select 'привет 1'
)
select name from tbl
where name REGEXP '\w+ \d'
;
```

#### What did you expect to see?

hello 1
привет 1

#### What did you see instead?

hello 1

Useful extra information
-------------------------

The problem discovered after migration to new regexp. The expected result received from 3.11.2 version and actual result from nightly.

According to [qt docs](https://doc.qt.io/qt-5/qregularexpression.html#unicode-properties-support) 
>character classes only match ASCII characters by default when using QRegularExpression. It is possible to change this behaviour by using the UseUnicodePropertiesOption pattern option.

As a temp workaround it is possible to rewrite `\w` as a range like `[a-zа-я bla-bla-bla]`

Win 8.1 x64, DB4S Version 3.11.99 (Nov 23 2019)

**Comment by MKleusberg** [comment]
Oh you're right. I missed that when changing the regexp implementation. Sorry about that! It should be fixed in tomorrow's nightly build. Can you give that another try? :smile:

**Comment by T1mL3arn** [comment]
Tested. Now it works as expected. Thank you for the fix.
