### ISSUE TITLE
Result: near "SELECT": syntax error

### ISSUE THREAD

**Issue by orangiee** [sqlitebrowser/sqlitebrowser#2055]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-lp64] on macOS 10.14 (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.1.0 community (based on SQLite 3.27.2)
> and Qt 5.11.3

**Comment by justinclift** [comment]
@skys215 Any interest in trying to help out with this issue?  eg first step, find out what's wrong. :smile:

**Comment by chrisjlocke** [comment]
@orangiee - can you provide a screenshot of the SQL you entered, and the error returned?

**Comment by skys215** [comment]
> @skys215 Any interest in trying to help out with this issue? eg first step, find out what's wrong. 😄

I could try it, but not sure for the result.
Does it fail for all database with SELECT?

**Comment by mgrojo** [comment]
I'm going to close this due to lack of response or details. @orangiee feel free to reopen it if you can provide more details of the error, but in any case it was probably a problem with the SQL syntax.
