### ISSUE TITLE
Pycharm, Python 3.8, Django and DB SqLite Worst combo ever!

### ISSUE THREAD

**Issue by c5corvette04** [sqlitebrowser/sqlitebrowser#2056]
Created model in Python via Pycharm 

Getting error : no such table: main.auth_user__old

Python 3.8
Pycharm 2019.2.5
Django 2.2.7
DB SQlite 3.27.2

This has been a known bug for some time, why is it still an issue and does anyone have a solution?

Details of the error:

OperationalError at /admin/products/product/add/
no such table: main.auth_user__old
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/products/product/add/
Django Version:	2.2.7
Exception Type:	OperationalError
Exception Value:	
no such table: main.auth_user__old
Exception Location:	C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 383
Python Executable:	C:\Users\chris\AppData\Local\Programs\Python\Python38-32\python.exe
Python Version:	3.8.0
Python Path:	
['C:\\Users\\chris\\PycharmProjects\\PyShop',
 'C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\python38.zip',
 'C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\DLLs',
 'C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\lib',
 'C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32',
 'C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages']
Server time:	Fri, 29 Nov 2019 01:15:50 +0000
Traceback Switch to copy-and-paste view
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in _execute
                return self.cursor.execute(sql, params) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py in execute
        return Database.Cursor.execute(self, query, params) …
▶ Local vars
The above exception (no such table: main.auth_user__old) was the direct cause of the following exception:
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py in inner
            response = get_response(request) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py in _get_response
                response = self.process_exception_by_middleware(e, request) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\options.py in wrapper
                return self.admin_site.admin_view(view)(*args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\decorators\cache.py in _wrapped_view_func
        response = view_func(request, *args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\sites.py in inner
            return view(request, *args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\options.py in add_view
        return self.changeform_view(request, None, form_url, extra_context) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py in _wrapper
        return bound_method(*args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\decorators.py in _wrapped_view
                    response = view_func(request, *args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\options.py in changeform_view
            return self._changeform_view(request, object_id, form_url, extra_context) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\options.py in _changeform_view
                    self.log_addition(request, new_object, change_message) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\options.py in log_addition
        return LogEntry.objects.log_action( …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\admin\models.py in log_action
        return self.model.objects.create( …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py in create
        obj.save(force_insert=True, using=self.db) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py in save
        self.save_base(using=using, force_insert=force_insert, …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py in save_base
            updated = self._save_table( …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py in _save_table
            result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py in _do_insert
        return manager._insert([self], fields=fields, return_id=update_pk, …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py in _insert
        return query.get_compiler(using=using).execute_sql(return_id) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py in execute_sql
                cursor.execute(sql, params) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in execute
            return super().execute(sql, params) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in _execute_with_wrappers
        return executor(sql, params, many, context) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in _execute
                return self.cursor.execute(sql, params) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py in __exit__
                raise dj_exc_value.with_traceback(traceback) from exc_value …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py in _execute
                return self.cursor.execute(sql, params) …
▶ Local vars
C:\Users\chris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py in execute
        return Database.Cursor.execute(self, query, params) …
▶ Local vars
Request information
USER
admin

GET
No GET data

POST
Variable	Value
csrfmiddlewaretoken	
'ZWcR4Q4NjmK5UInZxZNwF8MNQkw24TCFFb1Zngld4pjfumSRZMcRJc1I9fBqz9UF'
name	
'Orange'
price	
'1.99'
stock	
'50'
image_url	
'https://upload.wikimedia.org/wikipedia/commons/7/7b/Orange-Whole-%26-Split.jpg'
_save	
'Save'
FILES
No FILES data

COOKIES
Variable	Value
csrftoken	
'VyrQYG5TwmhbqBfrDVb0gq8BsySHBksoBNgYh6mjhpQl0fKj5IAlkunwLtX56AKo'
sessionid	
'x7udhq5joqtz1b46xsjl281keggmijgu'
META
Variable	Value
ALLUSERSPROFILE	
'C:\\ProgramData'
APPDATA	
'C:\\Users\\chris\\AppData\\Roaming'
COMMONPROGRAMFILES	
'C:\\Program Files (x86)\\Common Files'
COMMONPROGRAMFILES(X86)	
'C:\\Program Files (x86)\\Common Files'
COMMONPROGRAMW6432	
'C:\\Program Files\\Common Files'
COMPUTERNAME	
'DESKTOP-66S6HDL'
COMSPEC	
'C:\\WINDOWS\\system32\\cmd.exe'
CONTENT_LENGTH	
'234'
CONTENT_TYPE	
'application/x-www-form-urlencoded'
CSRF_COOKIE	
'VyrQYG5TwmhbqBfrDVb0gq8BsySHBksoBNgYh6mjhpQl0fKj5IAlkunwLtX56AKo'
DJANGO_SETTINGS_MODULE	
'pyshop.settings'
DRIVERDATA	
'C:\\Windows\\System32\\Drivers\\DriverData'
GATEWAY_INTERFACE	
'CGI/1.1'
HOMEDRIVE	
'C:'
HOMEPATH	
'\\Users\\chris'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.9'
HTTP_CACHE_CONTROL	
'max-age=0'
HTTP_CONNECTION	
'keep-alive'
HTTP_COOKIE	
('csrftoken=VyrQYG5TwmhbqBfrDVb0gq8BsySHBksoBNgYh6mjhpQl0fKj5IAlkunwLtX56AKo; '
 'sessionid=x7udhq5joqtz1b46xsjl281keggmijgu')
HTTP_DNT	
'1'
HTTP_HOST	
'127.0.0.1:8000'
HTTP_ORIGIN	
'http://127.0.0.1:8000'
HTTP_REFERER	
'http://127.0.0.1:8000/admin/products/product/add/'
HTTP_SEC_FETCH_MODE	
'navigate'
HTTP_SEC_FETCH_SITE	
'same-origin'
HTTP_SEC_FETCH_USER	
'?1'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like '
 'Gecko) Chrome/78.0.3904.108 Safari/537.36')
IDEA_INITIAL_DIRECTORY	
'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.2.3\\bin'
LOCALAPPDATA	
'C:\\Users\\chris\\AppData\\Local'
LOGONSERVER	
'\\\\DESKTOP-66S6HDL'
NUMBER_OF_PROCESSORS	
'4'
ONEDRIVE	
'C:\\Users\\chris\\OneDrive'
ONEDRIVECONSUMER	
'C:\\Users\\chris\\OneDrive'
OS	
'Windows_NT'
PATH	
('C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS '
 'Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program '
 'Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program '
 'Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files '
 '(x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program '
 'Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program '
 'Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common '
 'Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program '
 'Files\\PuTTY\\;C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\Scripts\\;C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python38-32\\;C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\;C:\\Users\\chris\\AppData\\Local\\Programs\\Python\\Python37-32\\;C:\\Users\\chris\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\chris\\AppData\\Local\\Programs\\Microsoft '
 'VS Code\\bin')
PATHEXT	
'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'
PATH_INFO	
'/admin/products/product/add/'
PROCESSOR_ARCHITECTURE	
'x86'
PROCESSOR_ARCHITEW6432	
'AMD64'
PROCESSOR_IDENTIFIER	
'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel'
PROCESSOR_LEVEL	
'6'
PROCESSOR_REVISION	
'8e09'
PROGRAMDATA	
'C:\\ProgramData'
PROGRAMFILES	
'C:\\Program Files (x86)'
PROGRAMFILES(X86)	
'C:\\Program Files (x86)'
PROGRAMW6432	
'C:\\Program Files'
PROMPT	
'$P$G'
PSMODULEPATH	
('C:\\Program '
 'Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules')
PUBLIC	
'C:\\Users\\Public'
QUERY_STRING	
''
REMOTE_ADDR	
'127.0.0.1'
REMOTE_HOST	
''
REQUEST_METHOD	
'POST'
RUN_MAIN	
'true'
SCRIPT_NAME	
''
SERVER_NAME	
'DESKTOP-66S6HDL'
SERVER_PORT	
'8000'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SOFTWARE	
'WSGIServer/0.2'
SESSIONNAME	
'Console'
SYSTEMDRIVE	
'C:'
SYSTEMROOT	
'C:\\WINDOWS'
TEMP	
'C:\\Users\\chris\\AppData\\Local\\Temp'
TERMINAL_EMULATOR	
'JetBrains-JediTerm'
TMP	
'C:\\Users\\chris\\AppData\\Local\\Temp'
USERDOMAIN	
'DESKTOP-66S6HDL'
USERDOMAIN_ROAMINGPROFILE	
'DESKTOP-66S6HDL'
USERNAME	
'chris'
USERPROFILE	
'C:\\Users\\chris'
WINDIR	
'C:\\WINDOWS'
__INTELLIJ_COMMAND_HISTFILE__	
'C:\\Users\\chris\\.PyCharmCE2019.2\\config\\terminal\\history\\history-83'
wsgi.errors	
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
wsgi.file_wrapper	
''
wsgi.input	
<django.core.handlers.wsgi.LimitedStream object at 0x0424F1D8>
wsgi.multiprocess	
False
wsgi.multithread	
True
wsgi.run_once	
False
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
Settings
Using settings module pyshop.settings
Setting	Value
ABSOLUTE_URL_OVERRIDES	
{}
ADMINS	
[]
ALLOWED_HOSTS	
[]
APPEND_SLASH	
True
AUTHENTICATION_BACKENDS	
['django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS	
'********************'
AUTH_USER_MODEL	
'auth.User'
BASE_DIR	
'C:\\Users\\chris\\PycharmProjects\\PyShop'
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS	
'default'
CACHE_MIDDLEWARE_KEY_PREFIX	
'********************'
CACHE_MIDDLEWARE_SECONDS	
600
CSRF_COOKIE_AGE	
31449600
CSRF_COOKIE_DOMAIN	
None
CSRF_COOKIE_HTTPONLY	
False
CSRF_COOKIE_NAME	
'csrftoken'
CSRF_COOKIE_PATH	
'/'
CSRF_COOKIE_SAMESITE	
'Lax'
CSRF_COOKIE_SECURE	
False
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME	
'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS	
[]
CSRF_USE_SESSIONS	
False
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': 'C:\\Users\\chris\\PycharmProjects\\PyShop\\db.sqlite3',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': ''}}
DATABASE_ROUTERS	
[]
DATA_UPLOAD_MAX_MEMORY_SIZE	
2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS	
1000
DATETIME_FORMAT	
'N j, Y, P'
DATETIME_INPUT_FORMATS	
['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']
DATE_FORMAT	
'N j, Y'
DATE_INPUT_FORMATS	
['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
DECIMAL_SEPARATOR	
'.'
DEFAULT_CHARSET	
'utf-8'
DEFAULT_CONTENT_TYPE	
'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE	
''
DEFAULT_TABLESPACE	
''
DISALLOWED_USER_AGENTS	
[]
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST	
'localhost'
EMAIL_HOST_PASSWORD	
'********************'
EMAIL_HOST_USER	
''
EMAIL_PORT	
25
EMAIL_SSL_CERTFILE	
None
EMAIL_SSL_KEYFILE	
'********************'
EMAIL_SUBJECT_PREFIX	
'[Django] '
EMAIL_TIMEOUT	
None
EMAIL_USE_LOCALTIME	
False
EMAIL_USE_SSL	
False
EMAIL_USE_TLS	
False
FILE_CHARSET	
'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_TEMP_DIR	
None
FIRST_DAY_OF_WEEK	
0
FIXTURE_DIRS	
[]
FORCE_SCRIPT_NAME	
None
FORMAT_MODULE_PATH	
None
FORM_RENDERER	
'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS	
[]
INSTALLED_APPS	
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'products.apps.ProductsConfig']
INTERNAL_IPS	
[]
LANGUAGES	
[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('hy', 'Armenian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI	
['he', 'ar', 'fa', 'ur']
LANGUAGE_CODE	
'en-us'
LANGUAGE_COOKIE_AGE	
None
LANGUAGE_COOKIE_DOMAIN	
None
LANGUAGE_COOKIE_NAME	
'django_language'
LANGUAGE_COOKIE_PATH	
'/'
LOCALE_PATHS	
[]
LOGGING	
{}
LOGGING_CONFIG	
'logging.config.dictConfig'
LOGIN_REDIRECT_URL	
'/accounts/profile/'
LOGIN_URL	
'/accounts/login/'
LOGOUT_REDIRECT_URL	
None
MANAGERS	
[]
MEDIA_ROOT	
''
MEDIA_URL	
''
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE	
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
MIGRATION_MODULES	
{}
MONTH_DAY_FORMAT	
'F j'
NUMBER_GROUPING	
0
PASSWORD_HASHERS	
'********************'
PASSWORD_RESET_TIMEOUT_DAYS	
'********************'
PREPEND_WWW	
False
ROOT_URLCONF	
'pyshop.urls'
SECRET_KEY	
'********************'
SECURE_BROWSER_XSS_FILTER	
False
SECURE_CONTENT_TYPE_NOSNIFF	
False
SECURE_HSTS_INCLUDE_SUBDOMAINS	
False
SECURE_HSTS_PRELOAD	
False
SECURE_HSTS_SECONDS	
0
SECURE_PROXY_SSL_HEADER	
None
SECURE_REDIRECT_EXEMPT	
[]
SECURE_SSL_HOST	
None
SECURE_SSL_REDIRECT	
False
SERVER_EMAIL	
'root@localhost'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_AGE	
1209600
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_HTTPONLY	
True
SESSION_COOKIE_NAME	
'sessionid'
SESSION_COOKIE_PATH	
'/'
SESSION_COOKIE_SAMESITE	
'Lax'
SESSION_COOKIE_SECURE	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
SESSION_FILE_PATH	
None
SESSION_SAVE_EVERY_REQUEST	
False
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE	
'pyshop.settings'
SHORT_DATETIME_FORMAT	
'm/d/Y P'
SHORT_DATE_FORMAT	
'm/d/Y'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS	
[]
STATICFILES_DIRS	
[]
STATICFILES_FINDERS	
['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT	
None
STATIC_URL	
'/static/'
TEMPLATES	
[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS	
[]
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR	
','
TIME_FORMAT	
'P'
TIME_INPUT_FORMATS	
['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE	
'UTC'
USE_I18N	
True
USE_L10N	
True
USE_THOUSAND_SEPARATOR	
False
USE_TZ	
True
USE_X_FORWARDED_HOST	
False
USE_X_FORWARDED_PORT	
False
WSGI_APPLICATION	
'pyshop.wsgi.application'
X_FRAME_OPTIONS	
'SAMEORIGIN'
YEAR_MONTH_FORMAT	
'F Y'

**Comment by justinclift** [comment]
If you open the database directly in our gui, does the "main.auth_user__old" table exist?

**Comment by c5corvette04** [comment]
No.  It does not.  For some reason the makemigrations and migrate do not create that table.

**Comment by justinclift** [comment]
Personally, I haven't used Django in many years so I'm not able to assist. :angel: 

If no-one else here is able to help then probably the best place to ask is the [Django Community](https://www.djangoproject.com/community/).  They should be able to help you figure out what's going wrong. :smile:

**Comment by sky5walk** [comment]
Create the database and tables manually within DB Browser for SQLite.
Then attempt to read/write to them within your code.

**Comment by justinclift** [comment]
Closing this as it's an old issue, and is really more suited to asking the Django Community (eg "why isn't this Django thing working?") rather than us.

@c5corvette04 Hopefully you got it all working some time ago. :smile:
