### ISSUE TITLE
Programm crash on "Edit display format" in a View

### ISSUE THREAD

**Issue by lnksz** [sqlitebrowser/sqlitebrowser#2058]
Details for the issue
--------------------

#### What did you do?
- I created a View from a Table.
- I selected the View via "Browse Data"
- Clicked on an a column header and selected "Edit display format" (to display unix timestamps as date-time strings)
- Crash

#### What did you expect to see?
- Converted data (e.g. date-time strings instead of integers)

#### What did you see instead?
- Process crashed

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: (lUbuntu 18.04.3 LTS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [x] 3.10.1 (sqlitebrowser 3.10.1-1.1) The described problem
- [x] Other: 3.11.99 from snapd (3.11.2-3097-914292f   1728  edge   gajjgndu), here the problem doesn't exist

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
    - I tried out the edge version from snapd (sqlitebrowser      3.11.2-3097-914292f         1728  edge      gajjgndu), where the "About" pane claims: Version 3.11.99 (Nov 16 2019)
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
This was already fixed in 9fd4ebe0e0ba6bc48509d4d8b9a27205c60d81a1 and entered the latest release, 3.11.2. You can stay in the nightly, if you want (it's pretty stable), or you can install the latest official release following instructions in https://sqlitebrowser.org/dl/ under section "Ubuntu and Derivatives".

**Comment by lnksz** [comment]
Thanks for the quick reply! If https://sqlitebrowser.org/dl/ could mention LTS 18, that would be great.
