### ISSUE TITLE
Ability to open cell with text editor and edit/apply value from there

### ISSUE THREAD

**Issue by yuis-ice** [sqlitebrowser/sqlitebrowser#2059]
Describe the new feature
--------------------------
If the value of cell in SQL query result is big sized, we might want to edit the value with your favorite text editor not in this software. As you know in each text editors have lots of cool features which is not included in this software. 

In my case I'm using Atom. Atom and sublime text are occupying lots of user share for now so implementing with them is good idea I guess. 

Something like that right click a cell then in the list, "Open with __" then click it to open with the editor to edit the value. 

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No. 

#### Does this feature exist in another product or project? Please provide a link.
I'm not sure. 

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No.

**Comment by mgrojo** [comment]
Thanks for the enhancement request. It was already considered in https://github.com/sqlitebrowser/sqlitebrowser/issues/1746#issuecomment-463799523 but it deserves its own issue report.

**Comment by mgrojo** [comment]
This is implemented in v3.12.0, so I'm closing this now, but you are free to comment on it or reopen it, if you think something is not working well. Look for the "Open in external application" button in the Edit Database Cell panel.
