### ISSUE TITLE
Undocking Database Cell Editor clears input 

### ISSUE THREAD

**Issue by gnbl** [sqlitebrowser/sqlitebrowser#2062]
Detaching the "Edit Database Cell" window from the sidebar (dock?) clears the input.

> DB4S v3.11.99 (Nov 23 2019) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.30.1
> and Qt 5.12.6

**Comment by mgrojo** [comment]
Thanks for reporting this, @gnbl. It should be fixed in the next nightly build. Please, close this issue if it is working right for you.

**Comment by justinclift** [comment]
Good fix @mgrojo. :smile:
