### ISSUE TITLE
Missing database structure for one of the tables 

### ISSUE THREAD

**Issue by broofa** [sqlitebrowser/sqlitebrowser#2066]
Details for the issue
--------------------

#### What did you do?
Ran into this while testing #2021 .  I went to look at the schema for my "programs" table under the "Database Structure" tab, but found there's no schema information shown for it. (See screenshot below).

If I run the SELECT command being used to get the table schemas (shown in the SQL log) on the `sqlite3` command line I get the following (notice "programs" table definition looks normal here):
```
sqlite> SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
table|SequelizeMeta|CREATE TABLE `SequelizeMeta` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY)|SequelizeMeta
index|sqlite_autoindex_SequelizeMeta_1||SequelizeMeta
table|histograms|CREATE TABLE `histograms` (`histogramUuid` UUID NOT NULL PRIMARY KEY, `robotUuid` UUID NOT NULL, `sampleStart` DATETIME NOT NULL, `sampleStop` DATETIME NOT NULL, `data` JSON)|histograms
index|sqlite_autoindex_histograms_1||histograms
table|events|CREATE TABLE `events` (`time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `robotUuid` UUID NOT NULL, `type` VARCHAR(255), `data` JSON)|events
table|programs|CREATE TABLE "programs" (`programUuid` UUID NOT NULL PRIMARY KEY, `name` VARCHAR(255) NOT NULL DEFAULT '', `sourceGzip` BLOB NOT NULL DEFAULT X'', `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)|programs
index|sqlite_autoindex_programs_1||programs
index|histograms_sample_start|CREATE INDEX `histograms_sample_start` ON `histograms` (`sampleStart`)|histograms
index|histograms_sample_stop|CREATE INDEX `histograms_sample_stop` ON `histograms` (`sampleStop`)|histograms
index|events_robot_uuid|CREATE INDEX `events_robot_uuid` ON `events` (`robotUuid`)|events
index|events_type|CREATE INDEX `events_type` ON `events` (`type`)|events
```

#### What did you expect to see?
"programs" table should show SQL for creating it, and have an arrow for expanding the row to show SQL definition for each column

#### What did you see instead?
The "programs" row is empty, no arrow for expanding it, as shown here:
![image](https://user-images.githubusercontent.com/164050/71024940-e4a13f00-20ba-11ea-9cd4-0de791c36e57.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ 10.14.6 )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [X] Other: `sqlite3 --version` --> 3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
This is one of the ones, that @MKleusberg knows how to solve. Or I hope so.

**Comment by mgrojo** [comment]
Well, it is easy to fix. This change should fix the parser:
```diff
diff --git a/src/sql/parser/sqlite3_lexer.ll b/src/sql/parser/sqlite3_lexer.ll
index d945a013..974ab35f 100644
--- a/src/sql/parser/sqlite3_lexer.ll
+++ b/src/sql/parser/sqlite3_lexer.ll
@@ -47,7 +47,7 @@ SQUAREBRACKETID               \[([^\n\]])*\]
 
 QUOTEDLITERAL          \"([^\n\"]|(\"\"))*\"
 STRINGLITERAL          \'([^\n\']|(\'\'))*\'
-BLOBLITERAL            X\'[0-9a-f]+\'
+BLOBLITERAL            X\'[0-9a-f]*\'
 
 BINDPARAMETER_NUM      \?([1-9]{DIGIT}*)?
 BINDPARAMETER_STR      [:@][a-z]+
```

But I cannot currently update the parser:
```
bison sqlite3_parser.yy
sqlite3_parser.yy:2.10-16: error: require bison 3.4.1, but have 3.0.4
 %require "3.4.1"
          ^^^^^^^
```

**Comment by MKleusberg** [comment]
@broofa The problem should be fixed in the next nightly build. Can you give it a try? :smile: 

@mgrojo Thank you for the fix :smile: By the way, since you only changed the lexer file (sqlite3_lexer.ll), you only need to run flex. Bison doesn't change its output anyway when only the lexer file changed.

**Comment by broofa** [comment]
Fixed in nightly.  Thanks!

**Comment by MKleusberg** [comment]
Awesome! I'm closing this issue then :smile:
