### ISSUE TITLE
Associate .mbtiles file type to allow easy open

### ISSUE THREAD

**Issue by IllusionVK** [sqlitebrowser/sqlitebrowser#2069]
Describe the new feature
--------------------------
.mbtiles file is a sqlite database file.  In MacOS mbtiles files are not associated with the the application, but it would be great if they could be to allow for easy double click to open in the application/operating system to recognise that the application is a legitimate handler for these files.

I tried to look through the code, but couldn't find where to add (and i likely dont have the skills i realised !)

Additional info
---------------
#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
n/a

#### Do you have a screenshot? Please add screenshots to help explain your idea.
n/a

**Comment by mgrojo** [comment]
According to[ this article](https://fileinfo.com/help/mac_change_program) MacOS allows the user to add their own associations.

I don't even know if our installer is making the association for our .sqbpro extension for project files. For Linux, we have recently provided support for distributors in #2024. But I guess that in MacOS doesn't use the [Shared MIME database (shared-mime-info)](https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/)

**Comment by mgrojo** [comment]
Closing this as it seems answered. It can be reopened, if there is still something to attend.
