### ISSUE TITLE
Reopen database feature

### ISSUE THREAD

**Issue by dkovalkov** [sqlitebrowser/sqlitebrowser#207]
Thank you for developing sqlitebrowser. I use it several years. I get databases from mobile device and often I need to reopen them to see changes. Can you make menu item which:
1. close current database,
2. open it again

**Comment by justinclift** [comment]
Shouldn't be too hard. :smile:

**Comment by justinclift** [comment]
By the way, are you using "Close File" then the recent files list at the moment?

eg:

* File &rarr; Close 
* File &rarr; 1

?

**Comment by dkovalkov** [comment]
Oh, thank you. I did not see database history. Much time I used old version without history.

**Comment by justinclift** [comment]
All good. :smile:

**Comment by MKleusberg** [comment]
You don't even have to close the database when reopening it using the history. DB4S does that automatically for you :smile:
