### ISSUE TITLE
How to achieve 50% width of the app size in mainTab

### ISSUE THREAD

**Issue by JacksiroKe** [sqlitebrowser/sqlitebrowser#2072]
I really need to change the ui in MainWindow.ui to fit what I have in mind with regards with this project. I would like to see the mainTab maintain 50% width of the app size whether it is maximized or not. This is what I have tried so far and have not been successful

```
 <widget class="QWidget" name="centralwidget">
   <property name="sizePolicy">
    <sizepolicy hsizetype="Minimum" vsizetype="Preferred">
     <horstretch>0</horstretch>
     <verstretch>0</verstretch>
    </sizepolicy>
   </property>
   <property name="minimumSize">
    <size>
     <width>400</width>
     <height>0</height>
    </size>
   </property>
```

and on mainTab
```
<widget class="QTabWidget" name="mainTab">
      <property name="enabled">
       <bool>true</bool>
      </property>
      <property name="sizePolicy">
       <sizepolicy hsizetype="Minimum" vsizetype="Expanding">
        <horstretch>0</horstretch>
        <verstretch>0</verstretch>
       </sizepolicy>
      </property>
      <property name="minimumSize">
       <size>
        <width>496</width>
        <height>0</height>
```

I would appreciate some enlightment on how to achieve this

**Comment by mgrojo** [comment]
I don't know how that could be done. Do you use Windows or any other desktop environment that allows maximizing one window to the left half of the desktop and another to the right half? That could be a workaround, provided also that you only need one of the docks. You could then detach that dock and close all the others and maximize the main window to the left and the dock to the right.

**Comment by JacksiroKe** [comment]
that is okay for me as a dev but for the intended users they dont have time for that. They expect things to work out anyhow without them having to do all that you have described to me there. To them it is too much work
