### ISSUE TITLE
Open as Read-Only still locks file and do not clean up journal files

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#2074]
Details for the issue
--------------------

#### What did you do?
Open a database as Read-only then:

1. Attempt to delete the db file to create a new one.

or

2. Close DB Browser for SQLite.

#### What did you expect to see?

1. I should be able to delete the db file when I am not doing anything with the database.

2. The app should clean up the locking files when I close it.

#### What did you see instead?

1. I cannot delete the file in Windows Explorer. My .NET script throws exception attempting to delete the file because it's used by another process.

2. The journal/locking files are still there. This does **NOT** happen if I open it normally (without Read-only option).

![image](https://user-images.githubusercontent.com/6388546/71546541-833a7380-29ca-11ea-88f2-7d77b5b8f862.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

P.s: the nightly build today seems messed up lol, but I was still able to test the Read-only feature, the files are not being cleaned up.

**Comment by justinclift** [comment]
For the "delete a file while you have it open" piece, to me that sounds correct.  On Windows, when you open a file (even in reading mode), windows has a "lock" on the file until it's finished.  It's a "read only" lock, so you (in theory) shouldn't be able to write to it, but it's still there.

Not sure about the journal files piece though.

**Comment by datvm** [comment]
Is there a way to disconnect the connection if I am not doing anything? I.e, after DB Browser finishes the SELECT statement, just severe the DB connection, and connect it again once I interact with the app? I know it will degrade the performance, but I am okay with that if I can have my file not locked. I know it is a bit specific for my case so I am totally okay if it's not possible :)

**Comment by justinclift** [comment]
I'm not personally aware of a way to do it, but someone else might be.

That being said, if you just need the output of the SQL command and don't need the GUI open then maybe the better approach is to call the SQLite command line interface (`sqlite.exe`) directly?

**Comment by datvm** [comment]
Sorry let me clarify a bit, I do need the UI to see what the values are, just that I don't need to interact often after that in this case. My work flow currently is:

Run script → Open DB Browser → Open database file → Check values → Modify script → **Close DB Browser** → Run script → repeat

It's just a bit inconvenient when I forget to close the DB Browser and the file is locked. That's why I ask for a way so DB Browser would create a connection, execute all needed queries, and then close it and don't do anything until I click Refresh again (something like Notepad++).

That's just my case so if you consider it too narrow use case, please just ignore it, no problem. But I think the 2nd point is still a valid problem.

**Comment by mgrojo** [comment]
The journal file is not created when the DB is open in read-only mode (at least that is I can observe in my platform). It is neither deleted when the DB is closed, because it has not been created in that connection. You have to open it read-write, save some changes, and then it is automatically deleted.

Regarding deleting a file while it is opened by an application, that is standard Windows behaviour. The file is locked against deletion.

Wouldn't the following procedure work for you? Close the DB (Ctrl+F4 in nightly, Ctrl+W in previous versions), operate with the file externally, and then open it again (Ctrl+1, provided that no DB files was opened in between).

**Comment by datvm** [comment]
Hi, I believe the described behavior was what happened before (or at least what I noticed). However it is not correct in my case: https://youtu.be/Ht42IpfFVtk. In the video, I tried opening the file in Read-only and non-Read-only mode.

I am attaching the database file as well, in case it's because of the file:

[data.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/4008769/data.zip)

> Regarding deleting a file while it is opened by an application, that is standard Windows behaviour. The file is locked against deletion.

This is correct and I have no objection about it. However, what I suggested was, if possible, DB Browser does not keep it open (I used the word "severe connection" in previous post). This behavior is similar to Notepad++, when you open a file, you can still delete/modify it elsewhere because after finishing reading the file, Notepad++ does not keep hold of it.

**Comment by mgrojo** [comment]
> Hi, I believe the described behavior was what happened before (or at least what I noticed). However it is not correct in my case: https://youtu.be/Ht42IpfFVtk. In the video, I tried opening the file in Read-only and non-Read-only mode.
> 
> I am attaching the database file as well, in case it's because of the file:
> 
> [data.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/4008769/data.zip)

Thanks for the video and the attachment. It is now clear why I didn't reproduce it. I had the database in the default journal mode (DELETE). In that case there isn't any journal file before the database is modified.

In your case it is set to WAL mode, which according to [documentation](https://www.sqlite.org/pragma.html#pragma_journal_mode):

>  WAL journaling mode uses a write-ahead log instead of a rollback journal to implement transactions. The WAL journaling mode is persistent; after being set it stays in effect across multiple database connections and after closing and reopening the database.

And from [Write Ahead Logging](https://www.sqlite.org/wal.html):

> There is an additional quasi-persistent "-wal" file and "-shm" shared memory file associated with each database, which can make SQLite less appealing for use as an application file-format. 

So even in read-only mode SQLite is creating and persisting these wal and shm files and there seems  not to be anything that we can do about it. You have the option to turn the Journal Mode to DELETE if you don't depend on the WAL mode and opening the DB in read-only mode will never create the journal file and in any case this file will not persist when the DB connection is closed.

> 
> > Regarding deleting a file while it is opened by an application, that is standard Windows behaviour. The file is locked against deletion.
> 
> This is correct and I have no objection about it. However, what I suggested was, if possible, DB Browser does not keep it open (I used the word "severe connection" in previous post). This behavior is similar to Notepad++, when you open a file, you can still delete/modify it elsewhere because after finishing reading the file, Notepad++ does not keep hold of it.

It is not the same to open a file in an editor, where the entire file is read to a memory buffer and maintained and updated there until the file is saved, when it will be completely replaced in disk; than opening a connection to a DB file, where the file is not expected to be completely read in memory and will never be entirely replaced. DB Browser could close the connection and reopen it again before implementing any query, but it would be slow and cumbersome. I cannot speak for other developers, but I don't see that happening.

I hope this helps and clarifies the issue.

**Comment by datvm** [comment]
Thanks a lot. Yes as I said before, I totally understand why the file is locked and why the app choose this approach (and it totally should). I respect your choice and totally agree with that.

As for the journal mode, the file was created by EF Core with everything in default settings. I didn't know anything about the journal mode. Checked some articles online and it seems there is an option to set it either by connection string or a query. I will try it. It's not a DB Browser's issue I suppose. 

Thank you very much for your kind support.

**Comment by mgrojo** [comment]
Thanks for reporting the nuisances using DB Browser and SQLite. It helps to know how the application is used and we all can learn something new.
