### ISSUE TITLE
export to csv

### ISSUE THREAD

**Issue by mrphysh** [sqlitebrowser/sqlitebrowser#2076]
Describe the new feature
--------------------------
I see a little icon in this video that moves the SELECT to a .cvs document.
https://youtu.be/6CaAd8plTiU
My Windows 10 does not have this.  Any thoughts.
Does this require an upgrade to DBBRowser?   Do I need to reinstall it?
Do  I need a different hobby?
John 
(https://github.com/mrphysh?tab=repositories)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
You haven't specified your version, but the video is showing an old release. The latest release (3.11.2)
has the button in the "Execute SQL" toolbar:
![imagen](https://user-images.githubusercontent.com/13812910/71647614-d0378600-2cf9-11ea-8858-de1973f1b9ab.png)

> Do I need a different hobby?
John
(https://github.com/mrphysh?tab=repositories)

Not because of DB Browser for SQLite. It will help a lot with your databases. We plan to make a new release soon. You can download a nightly build if you'd like to try the latest features: https://nightlies.sqlitebrowser.org/latest/

As showcase, this is a plot made quickly from some of your data:
![imagen](https://user-images.githubusercontent.com/13812910/71647818-2c030e80-2cfc-11ea-990f-42ee85ab1234.png)

**Comment by mrphysh** [comment]
Thanks.  Regarding the GitHub project;  The idea  is look for patterns in one pendulum.  Then, if they are found, look for a match in the other two pendulums.  As effective and certainly easier is to just average all three together.  And then look for patterns.I am actively pursuing this and making progress. I will upgrade my DbBrowser.John   

---------- Original Message ----------

**Comment by mrphysh** [comment]
Sir:  I like your graph.  thanks.   I am moving forward with interface to EXCEL.
 When I bring the database from Dbbrowser through a SELECT the datetime stamp (column_one) gets the first and last digits chopped off.    I see only minutes and seconds.
Any ideas?

**Comment by mgrojo** [comment]
Excel may be interpreting it correctly as a timestamp but displaying it with a format of mm:ss. Try setting a different cell format. If the data is not actually there, try changing the format in the import dialog to string instead of date/time.

**Comment by mrphysh** [comment]
okay thanks  (good communication)john

---------- Original Message ----------

**Comment by mrphysh** [comment]
I am looking for generic sqlite3 help and directed to GitHub.  But then nothing. I want to read date from one database, sort it and stuff and then put it in another, different database.  pretty ordinaryBut the first rows have mostly empty row and these first rows are messing up my python.  I want to delete these rows. db browser;  I delete the rows and write changes.  But I get an error [release restore point]  I have no manual, no nothing. (I like sqlite3)Any ideas.john

---------- Original Message ----------

**Comment by MKleusberg** [comment]
Sorry for the late reply, @mrphysh. Are you still getting this release restore point error? If so, can you give us some more details on what exactly you are doing so we can try to reproduce this?

**Comment by mrphysh** [comment]
Martin,  

I am a bit confused by your email.  But I do have an sqlite3 issue that is not resolved:  
In Sqlite3 I can write the sql queries and have no problems.  But when I export this table to a .csv  ,,   The excel csv file is not correctly separated into columns, destroying this functionality of the software package.  I have 'work-arounds' but this continues to be a problem.  
I have made major improvements with this project and have not gotten around to updating the GitHub repository.
 
john

Please note: message attached

**Comment by chrisjlocke** [comment]
Any attachments in the email don't get posted to GitHub via email.  You can link to them if they're hosted externally though.

**Comment by chrisjlocke** [comment]
> The excel csv file is not correctly separated into columns

What delimiter are you using?  Does this happen all the time?  Is this via the 'Execute SQL' tab?

**Comment by MKleusberg** [comment]
I was referring to this part of your message:
> I want to delete these rows. db browser; I delete the rows and write changes. But I get an error [release restore point]

As @chrisjlocke said, you should be able to change the field separators in the Export CSV dialog. I think Excel might prefer semicolons instead of commas.

**Comment by mrphysh** [comment]
I tried a semicolon and it still does not separate the columns.  Everything for a row is in column A in Excel.
And ...  No   .. This has not always been a problem.  The results of the "SQL execute" used to go nicely into Excel.

I work with this a lot and have 'work=arounds' but it would be nice to have this functionality again.
john

Please note: message attached

**Comment by chrisjlocke** [comment]
For the avoidance of doubt what version of DB4S are you using and on what operating system?
Ideally, a comma should be used to separate fields (comma-separated values, and all that) with a double quote as the identifier, so the file would be something like:
test1,test2,"test 3, test 3",test 4, test 5, "test 6, test 6"
test7,test8,"test 9, test 9",test 10, test 11, "test 12, test 12"

Feel free to email me either the database and/or the CSV file (db4s [at] chrisjlocke [dot] co [dot] uk) and I can have a cursory look at it to see if its anything obvious.  If its sensitive data, then feel free to use dummy data, etc.
I'll have an experiment as there may be a slim chance the code used in the export to CSV of that particular code in the 'execute SQL' tab is different to the exporting to CSV in the file menu (which did get a hug and tickle in the last release or so) so the code could just be a bit dusty.

**Comment by mgrojo** [comment]
Closing this as the required further information was not provided. It can be reopened, if there is still something to attend.

**Comment by chrisjlocke** [comment]
Aah, John did email me separately (and he was indeed on an older version).
It wasn't a CSV that was being exported, but a SSV (semi-colon separated file) so of course natively, Excel didn't have a clue about this, and thus shoved everything in one cell.  The fault was not with DB4S.

**Comment by mrphysh** [comment]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Aah, John did email me separately (and he was indeed on an older version).
It wasn't a CSV that was being exported, but a SSV (semi-colon separated file) so of course natively, Excel didn't have a clue about this, and thus shoved everything in one cell. The fault was not with DB4S.
XXXXXXXXXXXXXXXXXXXX

Hi Chris,
My sqlite3 application generates databases with even hundreds of thousands of rows.  I use sql within Dbrowser for initial sorts. And the use and 'export to CSV' to put them in EXCEL.  But the excel file has the whole row in one cell.

I have messed with the delimiter.  Any specific thoughts
thanks in advance

John 

Please note: message attached

**Comment by mgrojo** [comment]
When that happens, Excel has a button to process the selected column to separate the original columns using a dialog. I think it's called Text to Columns.

**Comment by mrphysh** [comment]
That was easy. In Excel   :::    [data]  then [text to columns]

I had to go around a few times but it was easy.  sometimes that happens

thanks!
john


Please note: message attached

**Comment by chrisjlocke** [comment]
In DB4S when you export, you can specify commas as a field separator.

![image](https://user-images.githubusercontent.com/7872218/108674542-5b1aa780-74dd-11eb-8cff-a63063f3e865.png)

This creates a 'typical' CSV (comma separated) file.

**Comment by mgrojo** [comment]
@chrisjlocke, you might be surprise to know that the Spanish edition of Excel generates and expects "CSV" files using ';' instead of ',' probably because it uses ',' as decimal separator (it's wouldn't be a problem, if it quoted numbers, but it doesn't) :smile: It is one of those case where Microsoft changes the behaviour depending on the localized version (like with shortcuts). Usually, people get hit about that.

**Comment by chrisjlocke** [comment]
Then it's not a CSV file! 😉  😄 
Fair enough!  Makes sense.  Thanks!

**Comment by justinclift** [comment]
@mgrojo Oh, that's a novel approach.  Hadn't heard of it before.  No wonder Excel has such a lousy reputation for it's CSV handling. :wink:

**Comment by JannetGen** [comment]
If this is still reproducible, I’d try opening a copy of the database first, just to rule out any file-locking or corruption issues. It may also be worth checking whether the same operation works from the SQLite CLI. That can help tell whether the problem is DB Browser-specific or related to the database itself.
