### ISSUE TITLE
Change "Insert New Record" button icon

### ISSUE THREAD

**Issue by kodmanyagha** [sqlitebrowser/sqlitebrowser#2083]
Describe the new feature
--------------------------
I want to add a new record to a table but I didn't find the button or shortcut. I clicked all buttons and I found a button. Its icon similar to a document export icon. Please change it PLUS icon for example:
https://fontawesome.com/icons/plus
https://fontawesome.com/icons/plus-circle?style=solid

Thanks.

**Comment by mgrojo** [comment]
Hi!

This is very subjective... In my opinion, a single plus sign is too overloaded, it could mean too many things, more than the current icon.

What comes to my head is replacing the arrow heads by  the plus and minus bullets that we have for other icons.
![table_row_insert](https://user-images.githubusercontent.com/13812910/71923649-c72d3580-318d-11ea-9e0f-27a4e1afee3b.png)
![table_row_delete](https://user-images.githubusercontent.com/13812910/71923696-e4fa9a80-318d-11ea-8886-9c543c55e14c.png)
What do you (and any other reader) think?

If you have a high resolution, you can also configure the application to show the "text beside the icon" in the "Browse Data" toolbar ("Preferences > General > Toolbar style") and all buttons will be more recognizable and more easily clickable.

**Comment by mgrojo** [comment]
Another two options based on the table_row icon in the [Silk Companion icon set](https://damieng.com/creative/icons/silk-companion-1-icons).

![table_row_add](https://user-images.githubusercontent.com/13812910/71926064-c5b23c00-3192-11ea-9261-7f69f2163a6f.png)
![table_row_delete](https://user-images.githubusercontent.com/13812910/71926065-c5b23c00-3192-11ea-8b14-6fd98e5bdfe9.png)

**Comment by MKleusberg** [comment]
I have to admit I was confused by the current icon too a couple of times :wink: For better consistency I would go with the icons suggested by @mgrojo - probably the ones with just the plus and minus icons because I think they are easier to parse visually since the plus and minus are in the same location.

**Comment by mgrojo** [comment]
Thanks for giving feedback, @MKleusberg. @kodmanyagha, the next nightly build will include the new icons, if you'd like to try.

![table_row_add](https://user-images.githubusercontent.com/13812910/71926064-c5b23c00-3192-11ea-9261-7f69f2163a6f.png) Insert Record
![table_row_delete](https://user-images.githubusercontent.com/13812910/71926065-c5b23c00-3192-11ea-8b14-6fd98e5bdfe9.png) Delete Record

**Comment by MKleusberg** [comment]
Thanks, @mgrojo. This looks good! I'll take the thumbs-up reactions as a sign that we can close this issue then :smile:
