### ISSUE TITLE
UI blacking out when I move my mouse

### ISSUE THREAD

**Issue by Ryan-Kirkwood** [sqlitebrowser/sqlitebrowser#2086]
Details for the issue
--------------------

#### What did you do?
Installed the Debian package for Chrome OS, opened the application.

#### What did you expect to see?
The DB Browser for Sqlite application without issue.

#### What did you see instead?
The application opens but when I move the mouse parts of the screen black out or has some ghosting from other applications that are open i.e. can see the terminal.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: (9.11 distro: (stretch))
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x ] Other: 3.9.1-2

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
It kind of looks like a bug we saw reported a few years ago, which (from memory) was caused by Qt.  Qt being the GUI toolkit we use.

I think the only solution was to upgrade the version of Qt (maybe even a manual install), then recompile our application using that. :frowning:

**Comment by chrisjlocke** [comment]
@Ryan-Kirkwood - IS this still an issue?  Did you investigate this any more?

**Comment by Ryan-Kirkwood** [comment]
Hey @chrisjlocke, the issue persisted but this was happening on my Chromebook which I no longer use, it may still be an issue or it could have been a ChromeOS issue that has been updated. Closing this issue as it seems pretty niche.
