### ISSUE TITLE
Can't make a foreign key to a table that starts with the same name of new table

### ISSUE THREAD

**Issue by JonathanGzzBen** [sqlitebrowser/sqlitebrowser#2088]
Details for the issue
--------------------

#### What did you do?
I had a table called 'attendance', then I tried making a junction table called 'attendance_student' which has a column named 'attendance_id', which is a foreign key to the column 'id' of the table 'attendance'.
The editor didn't let me choose the table 'attendance' to make a foreign key.

#### What did you expect to see?
Having the option to make a reference to the 'attendance' table.

#### What did you see instead?
It didn't appear in the dropdown list of tables.

Useful extra information
-------------------------
After trying with more names, I concluded that the problem is that it is not possible to make a foreign key to a table which name starts the same way as the new table.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
This seems the same as #1991. Could you confirm that it is solved using a [recent nightly](https://nightlies.sqlitebrowser.org/latest/)?

**Comment by JonathanGzzBen** [comment]
Yes, it is solved using the nightly build.
