### ISSUE TITLE
Pressing tab on last field of "Browse Data" should auto-create new record

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#209]
When inputting a bunch of data today, it became a real pain having to click on "New Record" to create each new line.  It would be a bunch more user-friendly for this scenario, if pressing "TAB" when on the very last field of the last record in a table, automatically started a new record and placed the cursor in the first
field of it.

In theory, this should be pretty easy to implement too. :wink:

**Comment by Z4us** [comment]
As a non-native English speaker I don't understand "a real to have" as if 'rea;' is a noun as well?

On a more serious and on-topic note: increasing user-friendliness is always a good plan for any software OS, commercial or something in between.

**Comment by justinclift** [comment]
Oops, missing word.  "became a real pain having to click...".  Fixed.

Thanks for pointing it out. :smile:

**Comment by MKleusberg** [comment]
Done :smile: Good idea, by the way!

**Comment by justinclift** [comment]
Thanks Martin, trying this out now. :smile:

**Comment by justinclift** [comment]
Yep, well done.  This is a lot nicer to use now, and a lot faster for inputing multiple rows of data. :grinning:
