### ISSUE TITLE
Expression Based Indices are broken when Modify Index or Modify Table is used.

### ISSUE THREAD

**Issue by tonurics** [sqlitebrowser/sqlitebrowser#2090]
Assume you have an expression based index for: JSON_EXTRACT(JSON,'$.Key')

*) If you use the Modify Index dialog it will return: JSON_EXTRACT(JSON,

*) On the Database Structure tab, under the Indices section, if you expand the tree element of the index it will show the incomplete index.

*) If you use the Modify Table dialog it will report the indices are broken, show the incomplete index and delete it from the schema.

I would guess that the problem is due to DB4S incorrectly handling quotes in indices.

#### I'm opening this issue because:
- [X] DB4S has a bug
- [X] DB4S has another problem

#### I'm using DB4S on:
- [X] Linux: ( Arch Linux: 2020-01-15 )

#### I'm using DB4S version:
- [X] 3.11.2

#### I have also:
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
I think this happens because of our (old) SQL parser. We have rewritten the parser some time ago however and improved it a lot. So I have just tried your example with the new parser and it seemed to work fine. :smile: Since you are using Linux, can you compile the latest code from our repository and see if it's fixing the issue for you? If you need any help with compiling the project, just let us know :smile:

**Comment by tonurics** [comment]
Hello Martin,

Thanks for the reply, I can confirm the issue is already gone in version 3.11.19. There were also some Modify Table issues I saw [I wanted to research further before reporting], that appear to also be gone in the new version. :)

I also note, that subjectively: the new version feels more responsive somehow. In any case, I'm looking forward to seeing it make it's way into my distro's packages once it's flagged for release.

Thanks again, and for your work on this project as a whole. I wasn't really one for GUI database interfaces, but DB4S really won me over. ;)

**Comment by MKleusberg** [comment]
Thank you for the quick feedback and for the kind words, @tonurics :smile: It's interesting you say that the new version feels more responsive. I tried to make a bunch of micro-optimisations in the code and wasn't quite sure if they are noticeable at all. But then they do seem to pay off :smile:
