### ISSUE TITLE
Could not open database file. Reason: file is not a database error after setting encryption

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#2092]
Details for the issue
--------------------

#### What did you do?

- Check out a657d2bf
- Open it in Qt Creator
- Ran qmake and then the project
- Created a new database
- Tried to encrypt it

#### What did you expect to see?

A success alert.

#### What did you see instead?

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5748627/72650476-52c27580-3989-11ea-8040-5638a0c6e1d2.png">

And that a `*.enctempold` file was created near the original database.

[test.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/4079374/test.zip)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ _10.15.2 (19C57)_ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: _a657d2bf_

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
And there was no dialog asking you for the passphrase again before you got the error message? That's pretty weird because this error message is usually what you get when you try to open an encrypted database with a build of DB4S with no encryption support. Also the fact that there is a ```.enctempold``` file means that the encryption itself threw no errors. So, honestly, I don't know :wink: Maybe it's some sort of build problem. Or maybe somebody else has a good idea :smile:

**Comment by revolter** [comment]
> And there was no dialog asking you for the passphrase again before you got the error message?

Nope.

> That's pretty weird because this error message is usually what you get when you try to open an encrypted database with a build of DB4S with no encryption support.

Exactly. But if that was the case, the encrypt menu wouldn't be visible.

**Comment by MKleusberg** [comment]
> > That's pretty weird because this error message is usually what you get when you try to open an encrypted database with a build of DB4S with no encryption support.
> 
> Exactly. But if that was the case, the encrypt menu wouldn't be visible.

Well actually, the visibility of the encrypt menu is determined at compile time. But if the SQLCipher shared library is loaded can be a runtime decision. The encryption process itself is happening more or less entirely by executing a series of ```PRAGMA```s which don't throw any error when they are not supported. You can try that by running this and see that it only says that it didn't return any rows but it reports no error:

```sql
PRAGMA blablablub
```

Can you try this one too in your build and see if it prints anything?
```sql
PRAGMA cipher_version
```

**Comment by revolter** [comment]
Well, I `git clean -dfx`, pulled the latest commit and tried again, and now it works. I don't know what happened, but thank you for your time!

**Comment by MKleusberg** [comment]
Cool :smile: I'm glad it's working now!
