### ISSUE TITLE
Ranges for data types

### ISSUE THREAD

**Issue by jon80** [sqlitebrowser/sqlitebrowser#210]
I need to know the ranges of data that can be used for numeric data, if it is possible to update the article at https://www.sqlite.org/datatype3.html,

**Comment by Z4us** [comment]
Floating see http://steve.hollasch.net/cgindex/coding/ieeefloat.html

Integer from -(2 ^ 64) to (2ˆ64) -1

**Comment by justinclift** [comment]
@jon80 It's probably best to ask on the SQLite Users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

:smile:

**Comment by samir-aguiar** [comment]
Well, @Z4us already said the ranges and we can't edit their documentation, so I'm closing this. :)
