### ISSUE TITLE
no way to reset ordering for Views

### ISSUE THREAD

**Issue by bam80** [sqlitebrowser/sqlitebrowser#2101]
Details for the issue
--------------------

Choose any View in "Browse Data" tab.
Set the View ordering(sorting) by clicking on it's any field.
If there was ordering implied by view's query - it's overridden now and there is no possibility to restore "native" view's ordering.

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
This has already been implemented with #1761, but we have not released it yet. You can try it out in the nightly builds or building the master branch by yourself. There are instructions in the wiki.

We plan to release soon, so you can decide to wait if you like.

**Comment by bam80** [comment]
Thanks. So there should be milestone set maybe?

**Comment by mgrojo** [comment]
Done.

**Comment by justinclift** [comment]
Closing this, as it was implemented a while back and is in our latest release.

If it's not working properly though, feel free to re-open this or create another issue to let us know. :smile:
