### ISSUE TITLE
CREATE TABLE syntax error not clear

### ISSUE THREAD

**Issue by jon80** [sqlitebrowser/sqlitebrowser#211]
I don't quite understand why this statement is an error, should you review the documentation or is it my mistake?
![untitled7](https://cloud.githubusercontent.com/assets/719110/6351517/84d51caa-bc3c-11e4-90e7-83e70606f2f1.png)

See https://www.sqlite.org/lang_savepoint.html, and, https://www.sqlite.org/lang_createtable.html. 

SQLite v 3.5.1
QT Version 4.8.5
SQLite Version 3.8.8.2
![untitled7](https://cloud.githubusercontent.com/assets/719110/6351540/a00bc4ce-bc3c-11e4-9154-e7f956ef87b6.png)

**Comment by rp-** [comment]
there is no statement separator after the SAVEPOINT pre.
you need a ';' or sqlite will see this as ONE statement

**Comment by jon80** [comment]
thanks

**Comment by jon80** [comment]
I think I tried this, but thanks.

**Comment by jon80** [comment]
The only statement not supported is the 'IF NOT EXISTS', at least so I deduce.

**Comment by justinclift** [comment]
Not sure if this is a bug in our program?  Does the statement (including the IF NOT EXISTS) work with the standard sqlite3 command line too?  If it doesn't there either, then it sounds like a limitation of SQLite itself (for now anyway).

**Comment by Z4us** [comment]
The syntax should be 

create table if not exists customer (customer_id...

Indeed if you suspect a bug RTFM

https://www.sqlite.org/lang_createtable.html

**Comment by justinclift** [comment]
Thanks @Z4us.  Closing this now. :smile:
