### ISSUE TITLE
can't open files with '~'

### ISSUE THREAD

**Issue by bam80** [sqlitebrowser/sqlitebrowser#2111]
Details for the issue
--------------------

In the Open Database dialog, the files with `~` in the end are not seen and also can't be entered in File name: field, so no way to open them. 

That file suffixes are frequently used for backups.

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
What desktop environment are you using? Wondering because I can neither reproduce this issue nor #2112 here and they both seem to be somewhat dependent on the desktop environment and similar. I get this popup when I start typing the file name and can select the '~' file without problems:
![Screenshot_20200213_103836](https://user-images.githubusercontent.com/3153504/74421299-16c9e580-4e4d-11ea-8e59-26db83e68950.png)

**Comment by scottfurry** [comment]
My understanding is that files ending with tilde ('~') are _usually_ backup files. These files may be hidden by a configuration setting of the window/file manager. Can you "right click" the directory window and check for "show hidden" is enabled? This may also be a distribution defined setting (sounds like something RedHat or Ubuntu would do).

**Comment by bam80** [comment]
"show hidden" doesn't help here, only if I change the Filter: to All files that .db~ file appeared.
If it intended behavior we can close the issue.

**Comment by justinclift** [comment]
This seems more like a KDE settings thing, than something we have control over. :wink:

**Comment by MKleusberg** [comment]
I'm using Plasma too so it shouldn't be a KDE thing. But it definitely looks like something we don't have control over :frowning:

**Comment by mgrojo** [comment]
I think this is working as expected. ".db~" is regarded as a different extension as ".db". When using the "All Files" filter, they are shown. What you can do is adding ".db~" to the list of recognized extensions in "Preferences > Global".
