### ISSUE TITLE
Timestamp Conversion

### ISSUE THREAD

**Issue by mac4n6** [sqlitebrowser/sqlitebrowser#2115]
Describe the new feature
--------------------------

Detect an epoch timestamp in a cell and be able to mass convert them. Need conversion by column as sometimes there are multiple versions of timestamps in a single table.

Common timestamps (w/sub-second resolution):
- Unix Epoch (1/1/1970 00:00:00 UTC)
- Mac Epoch (1/1/2000 00:00:00 UTC)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
Take a look at [Display Formats](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats). You can either use it directly or take a look at the used functions to make your own conversion code in SQL.

**Comment by scottfurry** [comment]
There is also the sqlite functions for DateTime conversion here:
https://www.sqlite.org/lang_datefunc.html

**Comment by justinclift** [comment]
@mac4n6 How'd you go with this? :smile:

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
