### ISSUE TITLE
no error

### ISSUE THREAD

**Issue by doro-92** [sqlitebrowser/sqlitebrowser#2116]
Details for the issue
--------------------

#### What did you do?
replace type at line in table, but programm do not it.
I find, that view, when using, occupied and did not allow to perform this operation. I drop view and done replacing type in table 

#### What did you expect to see?
error, so do I need todo

#### What did you see instead?
nothing

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by MKleusberg** [comment]
Can you try again with the latest nightly build? You can download it [here](https://nightlies.sqlitebrowser.org/latest/). I have just tried this with the latest version and get this error message:
```
Error renaming table 'sqlb_temp_table_2' to 'test'.
Message from database engine:
error in view view_test: no such table: main.test (ALTER TABLE "main"."sqlb_temp_table_2" RENAME TO "test")
```

**Comment by justinclift** [comment]
@doro-92 Ping... :smile:

**Comment by doro-92** [comment]
Yeah, latest version ok

**Comment by justinclift** [comment]
Cool. :smile:

Are you ok to close this issue?

**Comment by doro-92** [comment]
ok. yes)
