### ISSUE TITLE
Modifying a table by adding new column is instant causing errors

### ISSUE THREAD

**Issue by allusernamestakenexceptthis** [sqlitebrowser/sqlitebrowser#2117]
When modifying a table from UI by adding new column to a table. then trying to tick NN to mark as not null, it display error that there is at least on record that has null so impossible to change

#### What did you do?
Load an sqlite database, right click table choose modify table
click add field. enter name, change type, then click NN
error occurs

#### What did you expect to see?
The adding of the fields should only happen after clicking OK or a new button that says Apply. because clearly I'm not done adding column.

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by Tikiti** [comment]
I got the same error. It's due a new change on how sqlite works the alter table command after version 3.26. In short you have to issue this command: PRAGMA legacy_alter_table=ON before you try to alter the table. This is more of a work around till the program change the way to alter the table in a more safe way.
For more in-depth information you can see the answer here:
https://stackoverflow.com/a/57275538

**Comment by chrisjlocke** [comment]
Thanks @Tikiti for the explanation and link.

**Comment by chrisjlocke** [comment]
@allusernamestakenexceptthis - Can you check the latest nightly and confirm if this error still occurs?  I couldn't replicate it, but it might depend on your particular database schema....
https://nightlies.sqlitebrowser.org/latest/

**Comment by Tikiti** [comment]
@chrisjlocke I just tested it and it works fine now. There's a split second popup window when you click not null, can't see what it says.

However every time I open the app it throws a error (unrelated to this bug).

Version 3.12.99 (Aug 24 2020)
SQLite version 3.33.0

![2020-08-24](https://user-images.githubusercontent.com/18273203/91077645-6c0e5d00-e60f-11ea-98f4-3ff4bce55df7.png)

**Comment by chrisjlocke** [comment]
Thanks for replying back,
Yes, that error with the dialog at startup has been identified and will be blown into bits by tomorrows nightly build.  Thanks for letting us know! 👍

**Comment by chrisjlocke** [comment]
Closing as resolved by the magical code-updating fairies.
