### ISSUE TITLE
DB4S failing to show data columns for plot

### ISSUE THREAD

**Issue by bobha43** [sqlitebrowser/sqlitebrowser#2118]
### Details for the issue
Installed DBS4 on RPi 4 Raspbian Buster
sudo apt-get install sqlitebrowser
Inverter data recovered using SBFSpot. Appears correctly in tables.
Data column selected
Plot appears, with x 0:5, Y 0:5, but **without list of data columns to select for plotting.**

Worked perfectly with earlier installation on RPi 3
**Possibly not an actual bug, but I haven't been able to find anything with my searches**

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ x] Linux: ( Raspbian Buster Rp1 4 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.2
- [ ] 3.11.1
- [x ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by scottfurry** [comment]
Confirm RPi setup.
Is this a physical device? Size of monitor? HDMI?

Or are you using PIXIE? (see here: 
https://www.raspberrypi.org/downloads/raspberry-pi-desktop/)

**Comment by Myoldpasswordbobharris1943** [comment]
Hi Scott,
Thanks for getting back to me.
I am running a RPi 4 with 4 GB and a 64 GB SD Card.
The OS is Raspbian Buster with RPi Desktop, installed on the SD card.
It is located remotely and I am accessing it headless over VNC from my
Windows 10 PC.
The (virtual) screen resolution is set to 1920 x 1080 pixels.
It is displayed on a 24 in monitor using HDMI.

I am using SBFSpot (v. 3.10.1) to read from my SMA Inverter and this loads
data correctly into the expected tables.
SQLite is version 3.24.0.

So far so good and everything else seems to work correctly. The data are
also imported correctly into Domoticz.

When I  browse the desired table and select the plot screen in DB4S this
appears with a set of empty axes, both ranging from 0 to 5, *but without a
table of columns from which to select the items to be plotted *(see
attached image).

An essentially identical setup on a Raspberry Pi 3B works without problem -
also over VNC.

Any help you can give would be much appreciated.

Bob Harris

[image: DB4S_plot.png]

**Comment by scottfurry** [comment]
Please confirm the build configuration?
If you use the CMake build, executing "$ cmake -H. -B[folder] ..." will 
put data in [folder]. In that folder will be the file CMakeCache.txt 
file. That will detail how and if some dependent components are built 
into DB4S. Specifically, I'm concerned about QCustomPlot. That is what 
produces the graph plot.

I helped push into the tree the ability to build against an external( or 
system installed) version of the QCustomPlot library 
(https://www.qcustomplot.com/index.php).
The revisions haven't changed much in the last couple of years (last 
update to QCustomPlot in DB4S - 
https://github.com/sqlitebrowser/sqlitebrowser/tree/master/libs). V2.0.0 
was 2017 and looks to be compatible w/ Qt5.9. V2.0.1 takes us to 5.11. 
CMakeCache.txt will have a flag (FORCE_INTERNAL_QCUSTOMPLOT:BOOL=ON) 
saying if the version in our source tree is being used or the system 
version.

IIRC, (and a web search of Debain packages 
here[https://packages.debian.org/buster/libqt5core5a] confirms, Raspbian 
Buster is using 5.11.3. (command "$ apt-cache search qt5-core" to verify).

My concern( @justincliff, @MKleusberg - FYI) is that with 5.11 more 
prolific, using older QCustomPlot (2017 version that only goes to 5.9) 
may be causing you problems.
(Note to devs: maybe we should think about bumping the revision in git?)

So...
- check version of Qt. (5.11.3?)
- building against system version or DB4S version of QCustomPlot (CMake 
cache)
- what version of QCustomPlot is being used?
(if DB4S - we know the version; external debian shows 2.0.1 - 
https://packages.debian.org/buster/libqcustomplot-dev)

**Comment by scottfurry** [comment]
@Myoldpasswordbobharris1943 -- I've made a "pull request" for the latest QCustomPlot. This will take some time to go through review. In the interim and if your comfortable "rolling your own", I can walk you through CMake and building against external (we would use the Debian/Raspbian provided QCustomPlot v2.0.1). This would be a "workaround", and if successful, confirmation of my theory of the problem.
Do you have gitter? We can use the DB4S gitter channel to make happen. (Note - N.America MST)

**Comment by Myoldpasswordbobharris1943** [comment]
Thanks, but that all sounds rather beyond my "relatively noob" background.
I shall wait and in the meantime use my RPi 3B for this task. I appreciate
your efforts and hope you will be able to inform me once things are
resolved.
Thanks for the good work. If you need any more information please let me
know.
Bob
