### ISSUE TITLE
Please add support for CR line endings

### ISSUE THREAD

**Issue by atoregozh** [sqlitebrowser/sqlitebrowser#212]
I had a small table in csv format that had 3 columns and I wanted to import that into sqlitebrowser (create new database then file -> import -> import from CSV file). The import doesn't look right as instead of having multiple rows, it just imports everything into 1 single row. I was teaching a workshop using sqlitebrowser today and everyone who had a Mac had the same issue. We downloaded the most recent version of sqlitebrowser that is available on your website. Windows users didn't have this issue.

**Comment by rp-** [comment]
This sounds as your used Mac editor wrote Mac line endings CR.

The CSV RFC (http://www.ietf.org/rfc/rfc4180.txt) specifies CRLF (windows line endings) as line separators.

**Comment by Z4us** [comment]
@rp standard line ending of Mac is LF since the beginning of 21st century :-)

http://en.wikipedia.org/wiki/Newline#Representations

Perhaps for next milestone you may create an option in the menu where users may choose the EOL symbol of their system?

**Comment by justinclift** [comment]
Interesting.  Guess I've only ever exported CSV files instead of importing them. :wink:

Wonder if it's possible to reliably detect all of the common line endings (*nix, OSX, Windows) and not have to make it an option?

**Comment by atoregozh** [comment]
I forgot to add that this bug wasn't just for csv files but also for text files as well. When I tried importing a text file, I had the same 1 row with many fields instead of several rows and several columns.

**Comment by samir-aguiar** [comment]
@atoregozh could you provide a sample file?
The code works with LF and CRLF line endings, even if the file uses both. However, as @rp- mentioned it doesn't work with the old CR line endings, so perhaps your editor has that as default. TextWrangler, for instance, offers the ability to save with the three.

**Comment by atoregozh** [comment]
@samir-aguiar I'm not sure how to upload the file in this discussion but you can download "handle.csv" from here: http://web.mit.edu/aizhan/www/twitter_api_workshop/docs/

**Comment by samir-aguiar** [comment]
Yes, that's using only CR.
The easiest ways to check is to use a editor that shows that information (Sublime Text does and IIRC so does TextWrangler) or open Terminal and run:
`$ file <filename>`

The output for your file is:
`handle.csv: ASCII text, with CR line terminators`

However, apparently this is a bug (or a feature?) of Office for Mac when exporting to CSV. I don't know if there is a setting to change that, but you can convert the line endings to a more common format by using a text editor that supports it (like the ones I've mentioned) or checking [here](http://en.wikipedia.org/wiki/Newline#Conversion_utilities) for some command line tricks.

**Comment by samir-aguiar** [comment]
Hmm I did some searches and apparently there's no setting in Excel to change that. Don't know why would they choose this behavior though...

Anyway, from what I've seen it would be easy to also accept only CR as the line-ending character. What do you guys think?

**Comment by atoregozh** [comment]
@samir-aguiar thanks! that did fix it, but why would the sqlitebrowser code not work with CR endings? because they are "old" and no one uses them? I guess there would be some people who would view their csv files using excel, and if they save it, the file will be saved with CR endings.

**Comment by atoregozh** [comment]
@samir-aguiar this might be off-topic re sqlitebrowser issue: I used both options of checking the line endings you suggested and terminal does say that I have CR endings, but when I opened the file in Sublime Text2, and viewed the file's line endings, the tick was on Mac OS9 and not on Windows. Would that imply that sublime text is not recognizing the correct line endings?

**Comment by samir-aguiar** [comment]
@atoregozh It doesn't work probably because they are not common and are not accepted by the RFC, but I don't know for sure, I've only recently joined the project :smile: 

As for Sublime, it's showing correctly: Windows uses CRLF. CR was used by Mac OS until version 9 and starting with OS X it switched to Unix line endings (LF).

**Comment by justinclift** [comment]
@samir-aguiar Yeah, if it's easy to also add support for just CR as line endings - and not muck up anything else - then lets do it. :smile:

**Comment by MKleusberg** [comment]
I agree that we should add 'silent' support for CR line endings, so just treat them as LFs and not having a checkbox in the dialog for it. In my opinion we should support as many broken CSV variations as possible (as most CSV files are broken in one way or another according to the RFC).

@samir-aguiar Feel free to change the csvparser code. Maybe adding some more tests before changing it just to make sure it doesn't break anything else.

**Comment by samir-aguiar** [comment]
I think it should be working now.
By mistake I referenced and commented in the other CSV issue... it's right next to this one :smile: 

@justinclift we already cover cases where there's a non-empty string between the separators :wink:

**Comment by atoregozh** [comment]
@samir-aguiar great you already added support for CR? Does that mean that I should reinstall sqlitebrowser? Again off-topic: I actually have Mac OS X, why would sublime show that I have Mac OS 9 and thus I have CR endings?

**Comment by samir-aguiar** [comment]
@atoregozh Yeah, you can test tomorrow with the nightly build. It won't be in the stable version though -- if everything works out it should be in the next release.
The line endings are actually part of the file contents, so Sublime is telling you that this file uses the character '\r' to indicate a line break. OS 9 text editors added that character to the files when saving them to represent a newline. OS X editors now add '\n' instead, which is the same character used by Unix system. So Sublime just shows what character(s) the file contains that represent a newline, along with the most common OS to first set that character as the default for files read/written by that OS tools.

**Comment by justinclift** [comment]
@atoregozh We have a script which runs every night, compiling the very latest code on MacOSX and leaving it's results here:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/nightly/

It's a way for people to test the very latest changes, without needing to wait for an official release.

Please try out the latest build (in a few hours), to verify things are working for you now.  If they're not, it's important to let us know so we can investigate + figure out what else we need to do.

Workable? :smile:

**Comment by atoregozh** [comment]
@justinclift sure I'll install it later tonight. Per link you gave, what's the difference between sqlitebrowser vs sqlitebrowser-cipher? And which one should I install (sorry maybe that's not a relevant question)

**Comment by justinclift** [comment]
@atoregozh They're both very similar (same GUI), but the -sqlcipher one supports full database encryption as well.  So, pick whichever one best meets your needs. :smile:

**Comment by atoregozh** [comment]
@justinclift Thank you! I downloaded the last built (from March 8) and it works! I appreciate your fast assistance with this. And I learned a lot myself )

**Comment by justinclift** [comment]
@atoregozh - @samir-aguiar deserves your thanks, as he did the work, not me. :wink:

**Comment by atoregozh** [comment]
@samir-aguiar Thank you so much for helping!

**Comment by samir-aguiar** [comment]
No worries :smile:
