### ISSUE TITLE
Support for spaces for auto-completion of table, field names in query editor

### ISSUE THREAD

**Issue by mkweskin** [sqlitebrowser/sqlitebrowser#2120]
Describe the new feature
--------------------------
If you have a table or field name that includes spaces, the name appears correctly (with spaces) in the auto-complete suggestion pop-up, but if you then choose to insert the text, only the first word is inserted.
I suggested that quotes are automatically inserted around the multi-word name. 

I understand that spaces in names are not best-practice.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
<img width="242" alt="example" src="https://user-images.githubusercontent.com/1470877/74474126-d8472180-4e72-11ea-8345-54dd0c4a2d31.png">

**Comment by mgrojo** [comment]
That makes a lot and might be implemented at some point.

The enhancement has already been asked for, so I will close this issue as redundant. Please, subscribe to #2061 for the follow-up.
