### ISSUE TITLE
Trying to modify field type deleted all table data

### ISSUE THREAD

**Issue by pwr33** [sqlitebrowser/sqlitebrowser#2121]
Details for the issue
--------------------

#### What did you do?

click on field type button to change from integer to string

#### What did you expect to see?

a drop down list of field types

#### What did you see instead?

lock up, then when click again dbbrowser crashed/exited

it was a quite big table, lots of records and gave some warning message about a key referencing this field.  I then deleted the journal after the crash as dbbrowser refusing to load the table and then discovered all records in the table had been deleted.

fortunately had a recent backup and the means to recreate the table.

so seems a bit of checking for potential error conditions before modifying the data seems what should be done... so in this case want to delete the index first probably and the method I would use would be to tell the user to do this so they understand what is going on.  (index on an integer field which needs to be reindexed, or deleted and recreated) Or at least give the option to proceed with any table modification or not

Also a bit more positive feedback in the program while it is waiting for a process to complete, like on a large table can take 10's of seconds just to scroll to end of table when viewing the data, so a status bar area or a pop up dialog informing user to wait while it scans to end of table or does any long internal process would be good.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: ( mx linux 18 )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [x] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by pwr33** [comment]
OK, followed the build instructions and compiled latest, for mx linux had to used ubuntu instructions plus 
cmake -Dsqlcipher=1 -Wno-dev   -DFORCE_INTERNAL_QSCINTILLA=ON ..

can confirm viewing table data much much faster going to end of table, (and seem to get feedback where table goes red for short time) and the change of field type worked OK though I deleted the key and applied the changes first before changing field type this time.
Nice Work, Thanks!

**Comment by MKleusberg** [comment]
Awesome :smile: I'm glad the new version fixed the problem.

**Comment by pwr33** [comment]
I decided I wanted integer after all, more space efficient I think for a timestamp, so can now confirm DB4S handles not manually deleting the index first when changing field type as well.
I noticed the status bar notifications as well, Cool!
Though missing that notification when you do the modify table as that is through a dialog popup, but table access is now so fast it does not matter so much... only when about 10+ seconds have elapsed do you start thinking something locked up LOL

**Comment by pwr33** [comment]
done several field mods with an index on the field modified in several tables and all work OK

running the executable from a terminal can see some errors, no noticeable effect in operation

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3272, resource id: 23324540, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4139, resource id: 23324890, major code: 40 (TranslateCoords), minor code: 0
Empty filename passed to function
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 29269, resource id: 23360527, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 31188, resource id: 23366829, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 31612, resource id: 23367229, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 33178, resource id: 23368079, major code: 40 (TranslateCoords), minor code: 0

**Comment by justinclift** [comment]
Yeah, that stuff seems like standard (somewhat random) Qt output.  Nothing to really be done about it as far as I know.

**Comment by MKleusberg** [comment]
Yeah, that error is harmless. We might want to look into why we're getting this at some point but it's definitely safe to ignore this error :smile: I'm glad the nightly is working so well for you too. That probably means we can publish a new release really soon.
