### ISSUE TITLE
Importing CSV - how to find error?

### ISSUE THREAD

**Issue by ghost** [sqlitebrowser/sqlitebrowser#213]
Hi

I'm importing 3 CSV's. The first 2 worked ok but the 3rd shows:

![capture](https://cloud.githubusercontent.com/assets/8420596/6459769/8f9d4dcc-c189-11e4-9880-47a04e20a29a.PNG)

How can I find the error, to fix it?

**Comment by MKleusberg** [comment]
Hard to tell without the CSV file... - are you, by any chance, able to provide us the file which is causing you trouble? You can also send it by email. Maybe the first 3 lines or so will already suffice for reproducing the problem, so you could check that beforehand if you want to reduce the amount of data.

I've also improved the error messages. They won't be much more detailed in your case but if you're unable to provide the CSV file you can retry the import with tomorrow's nightly build (http://rp.oldsch00l.com/sqlitebrowser/) and we might be able to narrow down the error source.

**Comment by samir-aguiar** [comment]
@MKleusberg I've added two tests, one for CR endings and another for empty strings between separators. Any ideas for other tests?

**Comment by justinclift** [comment]
Non-empty strings between separators? (just saying... I really have no clue if that's appropriate) :grin:

**Comment by justinclift** [comment]
@ircer Is this problem still happening for you?

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by chrisjlocke** [comment]
Just a nod that if you have a blank CR on the end of a SQL statement, DB4S throws up this 'error'.
Appreciate this is now closed, but if it ever gets reopened and this is referred to, this note'll be found! ;)
