### ISSUE TITLE
This tool will take forever to improve... unless...

### ISSUE THREAD

**Issue by DingBEN** [sqlitebrowser/sqlitebrowser#2139]
**Simple...**
- _please take this as constructive criticism_
- **This is just one example, there are many more...**
   VS Code app, load it, play with it, Hint: **Ctrl+SHIFT+P** or VIEW, Command Palette (>, ?)
   you need to look at everything not just the hint above, colors, configuration, layout, etc...

**As to DBBrowser for SQLite**,
- **the dark scheme is a joke**, the background of the app is horrendous. (and no way to customize it)
   ...had to revert to the desktop style to get rid of this eye-boggling background
   luckily that is not a stupid white screens layout on my setup... or I would not even have looked at this app at all

- the **horribly THICK** frames around the various panels are a complete waste of vertical and horizontal real-estate
   they almost eat as much space as the data-work space... and in some places, more! RIDICULOUS!

- **the legacy Microsoft style pigeonhole dialogs** are shameful instead of today's modern UI styles
  HTML layouts that use full panels and fast scrolling (see VS Code hint above)

- **The tool otherwise seems to have a proper approach/work flow**, but not going to waste my time trying to study that part given the horrible layouts, and lack of configuration options.
sad, sad, sad... leaving to evaluate another tool.

**Comment by justinclift** [comment]
> the background of the app is horrendous. (and no way to customize it)

Would you be ok to provide a screenshot?  We've seen the theme turn out strangely on some platforms, and it's possible this is another case of it.

> The tool otherwise seems to have a proper approach/work flow, but not going to waste my time trying to study that part given the horrible layouts, and lack of configuration options.
sad, sad, sad... leaving to evaluate another tool.

No worries.  You seem happy with Electron based apps, and that's your choice. :wink:

**Comment by scottfurry** [comment]
> **Simple...**
>     * _please take this as constructive criticism_
With or without the flawed logic?
 
>     * **This is just one example, there are many more...**
>       VS Code app, load it, play with it, Hint: **Ctrl+SHIFT+P** or VIEW, Command Palette (>, ?)
>       you need to look at everything not just the hint above, colors, configuration, layout, etc...
Apple != Orange
C++ != HTML
Electron based apps use an underlying java script.
This is a Qt-based app written in C++

> **As to DBBrowser for SQLite**,
>     * **the dark scheme is a joke**, the background of the app is horrendous. (and no way to customize it)
This is the bane of Qt-based apps. Qt has this weird quasi-css style sheet usage. In some cases that's the only way to make certain functionality happen is via a style sheet. Problem exists in both the Qt C++ and Python libraries. tl;dr - circumstances beyond our control. Can only do best effort.

>       ...had to revert to the desktop style to get rid of this eye-boggling background
>       luckily that is not a stupid white screens layout on my setup... or I would not even have looked at this app at all
Wait till you try integrating Qt apps with a dark screen layout. If you're on a Linux box (can't tell as you didn't provide platform details), the 'qt5ct' (or configuration tool) helps so Qt apps play nicely in a GTK environment. Sadly, that tool hasn't been updated in almost three years.

>     * the **horribly THICK** frames around the various panels are a complete waste of vertical and horizontal real-estate
>       they almost eat as much space as the data-work space... and in some places, more! RIDICULOUS!
If it is extremely painful, and you think that improvements can be made, you are most welcome to submit a patch to fix so as to minimize the anguish and agony that others might encounter.  

>     * **the legacy Microsoft style pigeonhole dialogs** are shameful instead of today's mod
ern UI styles
>       HTML layouts that use full panels and fast scrolling (see VS Code hint above)
The Qt library has defined dialogs and controls. Although their are CSS-like elements for styling, these are not CSS/HTML controls. Again. Apple != Orange and C++ != HTML

>     * **The tool otherwise seems to have a proper approach/work flow**, but not going to waste my time trying to study that part given the horrible layouts, and lack of configuration options.
>       sad, sad, sad... leaving to evaluate another tool.
Good luck. Prepare to be disappointed.

**Comment by DingBEN** [comment]
- **I like the responses...** candid, reflecting of the conundrum programmers bathe in.
LOL -> [... Good luck. Prepare to be disappointed. ...]

- **Sure C++ is HTML...** != equals false!
  Qt/QML!? javascript support builtin !?
  Umpteen HTML libraries
  ...and those of you who still stagnate in C++ need to check out RUST

- **...NO**, _**I am not happy with electron based apps.**_ That would make me a rather short-sighted individual.  It is not a matter of Chevy vs Ford, or blue against red, ... it is a matter of ergonomics/design/anatomy beyond the suggested underlying capability of the base engine.
All but the worst of engines can be made to look identical at the UI level.

- **At least you admit it is painful. lol**  ...40+ years coding, believe me, I too know.
I am in no position to be of help as it concerns producing relief for anyone who will suffer this anguish and agony as you put it.  If I was I would simply write my own or I would have jumped in and ruffled feathers of everyone on the project, and started to revamp the app. ...and I am disenchanted with having to battle the egos and the people set in their way.

- **no need for screen-snapshots...** this is infantile. The corporate sector made sure to force programmers to develop everything on snow-white screens... the dark themes scared them as to be porno-like... so all the idiots working on screens ate brightARSE snow flash all day long, and still do.
Those who snow ski know better and wear eye protecting shades.

**A dark scheme can be fouled** just as much as a snow one.  If you need snapshots to possibly save your current horrendous color layout, you have no clue as to what ergonomic colors are... you need to hand the job to someone else who does.
I do not need snapshots to see it's shite.  As soon as it came up, I knew it's crap.  Again if you will get off your `electron` bashing statement and pay attention to the colors and how they work together, VS Code is a darned good example to emulate. ...and I am no MS fan... my preferred world is Unix/Xenix/Linux/nodejs/javascript/RUST [ I started on TRASHDOS, then Unix, was .NET/C#/VB.NET/... at some time ] but that again is a Ford vs Chevy thing... If Linux starts to invade my privacy as WIN10 does... Linux becomes SHITE also! If Chrome pushes a 3rd party manager without warning, and turns it ON by default, and offers no way to kill it... buhbye Chrome... now on Opera[GX](yes Chromium based) ...and searching for a different browser yet again.

**It took PHCKNG 4 decades for people like me to keep pushing for more ergonomic colors.**  ...and when it comes to eye fatigue, there is no choice except to go dark.
Now-a-days, the dark schemes are finally taking over.

- **Everything I/you listed can be circumvented, cleaned up.**
SQLiteStudio(for example) already shows how to create tighter better layouts but its anatomy takes a convoluted approach, and some of the UI is not so good.  After using it for a while I was able to make adequate use of it, but with many 'go-arounds'.
If you people merged with the SQLiteStudio one man show, you may be able to combine the 2 tools and get a much better tool fast.

**It just takes to visualize the beast up-front** and to build a base on top of the existing lacking engine that is open for mods.
When using a pre-cooked engine object, it usually quickly sucks and causes the code to be written to accommodate the lacks of same, don't rely on that. Either extend the object/class immediately or simply write a new one **that will save time overall**.  Everything that sucks in a class/object can be overridden. ha! you say... you say that takes time... read the bold again just above.

- **One can feel butt-hurt** because of being attached to a toy, but that is juvenile.  The approach in VS Code is the new wave... that should have happened long ago.  ...and it is only a beginning, wait till you see the advanced and more polished versions to come.

- **Why hide this issue by closing it, quasi guaranteeing hardly anyone will see it!?**
  _butt_hurt syndrome and egos are-a-flyin'_

**Comment by justinclift** [comment]
I'm locking this conversation, as @DingBEN is being outright abusive (eg name calling), and refusing to even assist with resolving the reported problems (eg provide screenshots, a basic and effective tool for demonstrating what other people are seeing).
