### ISSUE TITLE
Background color for NULL values goes white when changed

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#214]
Trying out the new NULL background colour thing, and discovered a minor bug.

1) In the Browse Data tab, with a table open that has NULL values shown correctly (using the colour from preferences)
2) I then go into the Preferences dialog and change the colour.  When I exit the dialog, the fields with NULL values change to (blank) white, instead of the new colour chosen.

Clicking the "New record" button helps, with the new line being the correct colour, and the previously blank fields now also changing to the right colour.

Can provide screenshots if that's needed. :smile:

**Comment by samir-aguiar** [comment]
That's weird, I've done some tests but couldn't reproduce. Here it immediately changes.
More info please? :smile:

**Comment by justinclift** [comment]
Sure. :smile:

So, starting with this table:
![start](https://cloud.githubusercontent.com/assets/406299/6472491/d522f0fc-c1ea-11e4-936b-fc39b9fa2037.png)
I then click the "New Record" button to create a new row:
![new row created](https://cloud.githubusercontent.com/assets/406299/6472493/da109646-c1ea-11e4-87be-0a0653f25c39.png)
(yeah, it's green - that's just the NULL colour value setting at the time of doing these screenshots)

Not liking the green as NULL, I go into the preferences.  Here you can see the preferences (unchanged):
![pref dialog opened - colour unchanged](https://cloud.githubusercontent.com/assets/406299/6472505/f9c610ce-c1ea-11e4-8455-758c6657683a.png)
I change the NULL colour to a light-ish red:
![pref dialog opened - colour changed](https://cloud.githubusercontent.com/assets/406299/6472528/143b333a-c1eb-11e4-8e24-06af5cc46f0a.png)
And now exit the Preferences dialog.  The Browse Data rows has slightly moved up 1/2 a row (23 is only 1/2 visible now - wasn't me doing that), and the cell colour that was green has now gone blank:
![pref dialog closed - last row has gone blank](https://cloud.githubusercontent.com/assets/406299/6472550/35fbe884-c1eb-11e4-95e2-b822a38b8e5d.png)
When creating new rows though, the displayed NULL colour is using the updated value correctly:
![new rows have the updated colour though](https://cloud.githubusercontent.com/assets/406299/6472559/4fa529bc-c1eb-11e4-9d6a-0cf67b145739.png)
Kind of suspecting there's something in the "exit the preferences dialog" code that refreshes the view, and it doesn't know about null values having a background colour yet.

I can email you the database if you want.  It's only a couple of kB. :smile:

**Comment by samir-aguiar** [comment]
That's really strange, I followed the steps and it just works. 
Can you try closing the app, removing or renaming the settings file and trying again?
It's this one:
`~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist`
Maybe that's it, somehow it doesn't get the new values. Perhaps the stored settings are corrupted.

If that doesn't work, send me the database, I'll do some more tests. :grinning:

**Comment by justinclift** [comment]
Tried it, and no change.  I'll email the database to you. :wink:

**Comment by samir-aguiar** [comment]
Thanks Justin!
The fields are actually empty as they can't be NULL (because of the constraint), but right after adding a new record the table was getting it wrong.
It should be fixed now. :smile:

**Comment by justinclift** [comment]
Just tried it... not sure if it's fixed or not... :wink:

With that database, I removed the "NOT NULL" constraint for the table ("Database Structure" tab → modify "Modify Table..."), then went to the Browse Data tab.  Clicked the "New Record" button to add a row, then clicked off of it to un-highlight it.  And got this:
![screen shot 2015-03-06 at 00 26 37](https://cloud.githubusercontent.com/assets/406299/6517886/88facfde-c397-11e4-9211-14153d1405d4.png)

Doesn't seem right?  Tried it all over again, and it happened both times, so it's consistent...

Ideas? :smile:

**Comment by samir-aguiar** [comment]
Yeah, that's because of the PK constraint, it doesn't insert NULL values as PK.

**Comment by justinclift** [comment]
Thanks @samir-aguiar, all good then. :grin:

We're going to have to do something about the default NULL colour too (need to make a new CR).  It's a super strong red by default, and made me think there was something wrong... :wink:

**Comment by samir-aguiar** [comment]
That's true, @justinclift, I'll commit some changes related to that later. :smiley:

**Comment by samir-aguiar** [comment]
BTW, apparently it should be possible to add NULL fields as PK, so that's also a bug. Not related to the color stuff though.
