### ISSUE TITLE
It would be very useful if the Import CSV File utility could use an existing table

### ISSUE THREAD

**Issue by cooperld** [sqlitebrowser/sqlitebrowser#2140]
Describe the new feature
--------------------------

It would be very useful if the Import CSV File utility could use an existing table. Often it gets the types wrong e.g. drops leading 0 and assumes text as number . The column 1 values are not always data base compliant

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Oh, this seems to have been overlooked. :frowning:

Do you remember which version of our program you were using with the CSV import when it got the types wrong?  We've added a type-override thing in our development code, so it might be useful to try our nightly builds which should include it.

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
I've just moved the bulk of the request text from the issue title into the main issue text field, to be more in line with other issues. :smile:

**Comment by Pharizna** [comment]
Hi, 

I have some problems with the type of a real column importing a table from CSV file. This variable has a lot of REAL number but few INTEGERS ... and choose INTEGER as type,

Now , I'm trying to use your last nightly build and now it's not possible to use this interesting option to create a new table, why?

**Comment by justinclift** [comment]
@Pharizna The option is called "Disable data type detection", under the "Advanced" drop down widget in the CSV import dialog.

In theory, it should be there for you as I just checked the nightly build now.  If you're not seeing it though, let us know so we can investigate. :smile:

**Comment by Pharizna** [comment]
@justinclift 

Thanks... but now is the our first variable (ID) that is an INTEGER appears as ... default type as the other variables?

**Comment by justinclift** [comment]
With the data type detection turned off, everything is just imported as "STRING".  Once the import is complete, you should be able to modify the table to change the column type.  eg Database schema view -> Edit table

Hopefully I'm understanding what you're aiming for. :smile:

**Comment by Pharizna** [comment]
Another suggestion: In Spain, we use "," in decimal data instead ".". Could you include this "character decimal separator" as you did with ";" instead ","? 

THANK YOU!

**Comment by Pharizna** [comment]
Perfecte @justinclift 

I thought that was impossible to alter the schema :-(

Anyway, why the default "importation" type is not the default chosen in DB preferences instead STRING?

**Comment by justinclift** [comment]
> I thought that was impossible to alter the schema

SQLite's way of doing "[ALTER TABLE](https://www.sqlite.org/lang_altertable.html)" has some limitations, so we do some behind the scenes magic to make it work. :smile:

> Anyway, why the default "importation" type is not the default chosen in DB preferences instead STRING?

Are you meaning the Preferences -> Database -> Default field type?  Um... that's a good question.  I think the original (super simple) code just used STRING for everything, as that's the safest.  eg no potential to lose data by guessing types.

That being said, unless there are lots of columns, it's fairly easy to change the column type afterwards through the GUI.  (Lots of columns becomes time consuming)

**Comment by justinclift** [comment]
> In Spain, we use "," in decimal data instead ".".

Ahhh.  I'd be surprised if we don't already have a way of making that work, though it's possible we've somehow missed it.

@mgrojo Have you run into that before for CSV imports?

**Comment by cooperld** [comment]
As a workaround I import to a staging table,  all as string.
I then do a "insert into ..select from " to move the data to the target
table"

**Comment by mgrojo** [comment]
> > In Spain, we use "," in decimal data instead ".".
> 
> Ahhh. I'd be surprised if we don't already have a way of making that work, though it's possible we've somehow missed it.
> 
> @mgrojo Have you run into that before for CSV imports?

I mostly use data formatted with dot as decimal separator and when I've run into the comma as separator, the data was simple enough to perform a preprocessing using Unix text tools, like sed or awk.

But of course, we should support different decimal separators. Even data using thousands separators, which we are not supporting in any case.

**Comment by Pharizna** [comment]
Thank but I'd prefer to import data directly without any preprocessing... mainly working in Windows.

Why is there the possibility to choose from "," or ";" as field separator? It would be simple enough to preprocessing too  ;-)

**Comment by scottfurry** [comment]
> Another suggestion: In Spain, we use "," in decimal data instead ".". Could you include this "character decimal separator" as you did with ";" instead ","?

Spanish is not the only language that does this ( IIRC this is an expectation in parts of Europe ).
The joys of regional, multi-language settings... </sarcasm>

IIRC, there is a setting for CSV import to select the field separator (i.e. what goes between each data field). I don't think we touch/look at the regional settings of the running system to check the decimal separator.

**Comment by justinclift** [comment]
Yeah, it sounds like we should add another field to the dialog, so people can choose which decimal separator to use.

Probably needs a safety check too, such that "`,`" can't be chosen for both the field separator and decimal point at the same time.

**Comment by bgol** [comment]
> Probably needs a safety check too, such that "`,`" can't be chosen for both the field separator and decimal point at the same time.

This should be possible, you just need the field to be quoted:
```
one half,"0,5"
two half,1
three half,"1,5"
```

**Comment by justinclift** [comment]
Aren't quoted fields supposed to always be "string" type though?

**Comment by bgol** [comment]
CSV is typeless, so whatever the application decides goes. CSV doesn't have an escape char per se, so to escape the use of the seperator you have to put it under quotes. See [RFC 4180](https://tools.ietf.org/html/rfc4180) section 2 point 6.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by Pharizna** [comment]
In the Spanish Excel usually we use “,” for field separator and decimal point for numbers. Why not use same convention?

Pedro

>

**Comment by bgol** [comment]
Because I'm from Austria and we use the comma as decimal separator (and the point as group separator). We even call the parts _Vor**komma**stellen_ and _Nach**komma**stellen_. It's also not always bad to give options.

**Comment by mgrojo** [comment]
@Pharizna , @bgol  There is a new option in the `Import CSV as table` dialog, under `Advanced`: `Use local number conventions`. If your locale is Spanish (Spain) or German (Austria), for example, it will use `,` as decimal separator and `.` as group separator. Could you confirm that is working well for you using the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)?

**Comment by MKleusberg** [comment]
Closing this issue as it looks like it has been fixed a while ago and we didn't hear anything since then. Feel free to reopen this issue if the problem still occurs.
