### ISSUE TITLE
Keyword formating

### ISSUE THREAD

**Issue by gsoTH** [sqlitebrowser/sqlitebrowser#2148]
Details for the issue
--------------------

#### What did you do?
Wrote SQL-Statement in SQL-Editor: DROP TABLE IF EXISTS album

#### What did you expect to see?
DROP TABLE IF EXISTS --> formated blue, as they are keywords
album --> formated purple as it is a name

#### What did you see instead?
DROP TABLE IF --> formated blue
EXISTS album --> formated purple 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [x] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by karim** [comment]
This has been fixed in our latest version (v3.11.2). Can you download it and confirm that it works. You can download it from here https://sqlitebrowser.org/dl/.

**Comment by gsoTH** [comment]
Sadly it doesn't work as exptected. There are now 3 colors.

DROP TABLE IF  --> formated blue, as they are keywords
EXISTS --> formated purple (like a name instead of a keyword)
album --> formated green(ish), as it is a table

**Comment by mgrojo** [comment]
@gsoTH The solution is not released yet (fa66937827586a80a1037c519eddeab0cf2fdbc0). It will be available in our next release, which should be soon. You can wait for it or install our [nightly build](https://nightlies.sqlitebrowser.org/latest/) if you want to give it a try.

**Comment by gsoTH** [comment]
Is fixed in nightly build. 

Thx!
