### ISSUE TITLE
Add (Qt) REGEXP support for the Execute SQL tab

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#215]
Query via Twitter:

&nbsp; &nbsp; https://twitter.com/BryanMcConkey/status/573115725595844608

```
Any plans to support REGEXP in the Execute SQL tab? I would find this very useful
in testing queries.
```

Thoughts? :smile:

**Comment by justinclift** [comment]
Thinking about this more... we pretty much rely on SQLite to provide the SQL processing part of things.  @BryanMcConkey (hoping that's is the correct GitHub user account :wink:), what's a good example of what you're looking for?

Depending on what/where it may or may not be possible, and we may need to suggest it to upstream SQLite developers first...

**Comment by MKleusberg** [comment]
Just a bit of background:
SQLite syntax includes the REGEXP keyword but SQLite lacks an implementation of an regular expression algorithm. Instead it tries to call a user-defined function and just errors out if it can't find one: https://www.sqlite.org/lang_expr.html#regexp
I have no idea why they do it this way - maybe fore more flexibility or simply to avoid adding dependencies to any other libraries. Either way, they're probably not going to change this :)

Anyway, Qt implements a regex algorithm which is easy enough for us to connect to SQLite. This is done in 6d1a874f8077b859bee2dd9d4031f242cfa1e807. I've also added an option to disable this feature just in case somebody prefers to load their own extension implementing a different algorithm.

@BryanMcConkey You can download the next nightly build (though you'll have to wait till tomorrow) or build the latest code yourself and test this feature. Any feedback is welcome and if you have any further questions feel free to ask us :)

**Comment by justinclift** [comment]
Wow.  That's unexpected and pretty darn awesome. :grinning:

**Comment by bryanmcconkey** [comment]
Wow, quick turn around on that inquery. I will look into tesing it out soon (probably tomorrow).

As for why SQLite does not implement the function I suspect is just to keep the lib as small as possible for embedded purposes where REGEXP is rarely needed. Hooking to qt implementation is what I would expect for sqlitebrowser.

Thanks again,  I will let you know how it works for me.

**Comment by bryanmcconkey** [comment]
Took a few minutes to download the nightly and give it a whirl. Its working as expected. Thanks again for the feature support!

**Comment by justinclift** [comment]
Fantastic news.  Thanks for testing and confirming it @bryanmcconkey. :grinning:

**Comment by samir-aguiar** [comment]
Nice! :+1:

**Comment by Bacham** [comment]
Hi! 
Is't possible to capture substrings by backreferences in your REGEX implementation? for example:
`UPDATE field_data_body
SET body_value = '\1'
WHERE body_value REGEXP '.*([0-9]*).*'`

**Comment by MKleusberg** [comment]
@Bacham Unfortunately it's not possible. It's also not a limitation by our REGEX implementation either but a limitation of SQLite. So I don't think there's anything we can do about it, sorry :frowning:
