### ISSUE TITLE
New to DB Browser, and a little confused.

### ISSUE THREAD

**Issue by Sarusagi** [sqlitebrowser/sqlitebrowser#2151]
What is your question
-----------------------
Hi! So I'm a student that's currently learning basic/introductory programming so I apologise beforehand for my noob-ness but upon a friend's recommendation, I installed DB Browser to use to make creating and hopefully linking a database to my basic GUI for my assignment easier. 

The problem I'm facing is, is that after setting up what I wanted the database to record and look like, I went to save the database so then I could look at adding it to my coding except the DB Browser refuses to save the database in any extension other than .sqbpro. Visual Studios (which I'm required to use) doesn't recognise it, and once I've saved it as .sqbpro the DB Browser doesn't even detect/display it when I go to "Open Database" so I'm left under the impression that I can't go back and alter the file, either.

Honestly, I just want to be able to save a file simply as .sql and work with it but I have started several fresh database files to test if I could alter the extension whether by manually entering it at the end of the file name or just clicking about looking for clues or things I could do differently but I'm basically stumped as every file ends up getting force saved under the extension .sqbpro and my last resort is to seek out a different IDE.

If I'm just being silly and I CAN use the .sqbpro file that'd be great but I still have an issue with the fact I can't boot the file back up again on DB Browser because the file doesn't pop up when I go to "Open Database" and there's still the issue that VS doesn't recognise it so... I hope someone can clear this up for me. ^^;

**Comment by justinclift** [comment]
> DB Browser refuses to save the database in any extension other than .sqbpro

Ahhh.  Sounds like you're hitting the "Save project" button, instead of the "Write Changes" button.

The "Write Changes" one saves just the .sqlite file (using whatever extension you gave it).  The "Save project" one saves a metadata file (with .sqbpro extension) that keeps track of other stuff.  eg contents of open tabs and similar.

Does that help? :smile:

**Comment by Sarusagi** [comment]
Oh, thanks! That's very embarrassing for me considering how simple the solution was, but in my defense I'm still getting the hang of things, haha. ^^;;

Thanks a lot! Hopefully this'll be my only obstacle, welp. :x

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by mgrojo** [comment]
@Sarusagi This might be of further help: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Project-Files
