### ISSUE TITLE
COMMENTS

### ISSUE THREAD

**Issue by Niranjani29** [sqlitebrowser/sqlitebrowser#2152]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Hi @Niranjani29, this issue is missing pretty much all the details we'd need to work out what's wrong.

Was it an accidental one you've opened, and is ok to be closed? :smile:

**Comment by Niranjani29** [comment]
Yes it was accidental, sorry about that.

**Comment by justinclift** [comment]
No worries @Niranjani29. :smile:
