### ISSUE TITLE
Running SQL select statements in Execute SQL tab locks up database

### ISSUE THREAD

**Issue by rupendrab** [sqlitebrowser/sqlitebrowser#2154]
Details for the issue
--------------------
When I run a select statement in the "execute sql" tab, the database gets locked.

#### What did you do?
Ran a select statement in the execute sql window.

#### What did you expect to see?
I did not expect the "Write Changes" and "Revert Changes" buttons to get activated. If I try to close the database, I am  prompted with the dialog "do you want to save/revert your changes?

#### What did you see instead?
As reported above.

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by mgrojo** [comment]
This seems the same as #2147, which has been confirmed as fixed in our latest [nightly build](https://nightlies.sqlitebrowser.org/latest/). Could you try with it and confirm that we can close this issue?

**Comment by rupendrab** [comment]
This issue is fixed with the nightly build pointed above. Thanks for looking into it.
