### ISSUE TITLE
New location of the "x" to close a tab is awkward?

### ISSUE THREAD

**Issue by beRto-** [sqlitebrowser/sqlitebrowser#2155]
I searched for the ticket where this change would have been made, but couldn't find it. Please redirect if I'm positing in the wrong place.

I was running a nightly build recently and noticed the "x" to close a query tab has been moved from being on the tab to being alone on the right hand side. I am curious why this was done? In my opinion, the new location is not intuitive (makes it look like I am closing *all* tabs) and is not consistent with other programs that use tabs (web browsers, etc).

**Current DB4S (Version 3.11.2):**
![image](https://user-images.githubusercontent.com/10589057/75835680-8f0d3200-5d8d-11ea-925c-e7a6d7a411e7.png)

**Nightly DB4S:**
![image](https://user-images.githubusercontent.com/10589057/75835750-ba901c80-5d8d-11ea-8891-03960936f58a.png)
...
![image](https://user-images.githubusercontent.com/10589057/75835765-c4b21b00-5d8d-11ea-977b-ec355cbffa6d.png)

**Comment by sky5walk** [comment]
Read Issue #1968 
You can delete individual tabs with right mouse menu click.
A gui problem still appears for users of many Execute SQL tabs.

**Comment by mgrojo** [comment]
@beRto- The next nightly build will have a preference setting for having close buttons on tabs as in 3.11 and before, or not. The corner button has been removed, since we have the contextual menu and the shortcut (Ctrl+W). Please confirm it works as expected, since we have to include this in the final 3.12 version.

**Comment by sky5walk** [comment]
Nightly v200603 works great! No more unsightly scrunched [x] buttons. 💯

**Comment by beRto-** [comment]
@mgrojo - nice! I just had a chance to test this using Version 3.12.99 (Jun  3 2020). I confirm each tab now has the "x" restored, as expected. Unfortunately, I was not able to test the preference setting to remove the close buttons. I expected to see some kinds of "Show close button on each tab" checkbox on under Preferences >> General, but did not find it there (or anywhere else). Could you please point me to it?

**Comment by mgrojo** [comment]
Yes, in the SQL tab. Infact, it should be called SQL Editor. It's the last
check button in the tab.

**Comment by beRto-** [comment]
@mgrojo OK, I see it now, thanks!

I would naively have expected it under General because it's not really an SQL preference, but just a display/interface preference?

That said, I can see a valid argument that these "x" only show up in tabs under Execute SQL. And so I would also agree the setting makes sense where it is right now.

In short, I like this change and thank you for looking into it! :)

**Comment by mgrojo** [comment]
Thanks for the feedback!
