### ISSUE TITLE
can't insert into table with check constraints 

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#2156]
Details for the issue
--------------------

#### What did you do?
I see two issues with such table
```
create table EnforceTypes (
	id integer primary key AUTOINCREMENT
	,someText TEXT CHECK(TYPEOF(someText) = 'text' OR someText is NULL) DEFAULT null
	,someInt INTEGER CHECK(TYPEOF(someInt) = 'integer' or someInt IS NULL) DEFAULT null
	,someReal real CHECK(TYPEOF(someReal) = 'real' or someReal is null)
	,someDate DATETIME CHECK((JULIANDAY(someDate) between 2415020.5 and 2488069.5)  or someDate is NULL)
);
```

1. the table is not visible whatsoever in the browse data tab, not even when new row button is clicked (although the row is added). Only after I insert some data with SQL the table shows itself. This is caused by the BETWEEN constraint on someDate. If I remove the between clause, Db Browser behaves as expected - table is visible. 

2. Its impossible to edit numerical values (someInt, someReal) in the browse data tab, says "Check constraint failed: EnforceTypes". It is possible to insert update numerical data with SQL, queires below work just fine. his is not related to someDate column, behaves the same even without this column. someText is not affected, editing this column works as expected.
```
insert into EnforceTypes values (null,'a',5,3.0,'2020-01-01');
update EnforceTypes set someInt = 4 where id = 1;
```

#### What did you expect to see?
see above

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Thanks for reporting this, @mglatz. I've reproduced it in 3.11.2 but not it in the latest development version. @MKleusberg has made a lot of improvements in the parsing of SQL statements, so I guess that has solved this issue. There were indeed errors in 3.11.2 related to this table and it could not be edited from the GUI, apart from the problems that you have already described.

You can use the [latest nightly build](https://nightlies.sqlitebrowser.org/latest/) or wait to the next release, which should be close to delivery.
