### ISSUE TITLE
Table Definition Template for csv import

### ISSUE THREAD

**Issue by kutoman** [sqlitebrowser/sqlitebrowser#216]
Hi,
it would be very relieving if there was the possiblity to store/load table definitions which then can be applied to tables which are imported from csv files. 
It suits to my use case where a bunch of people are managing data in a csv file on google drive (since concurrent access is possible) which then needs to be imported in a certain sqlite databse. The data belongs to a certain table of that databse but everytime I import the csv file I also need to modify the table definition fitting to the original definition (and of course rename that table and remove the older table, to perform the replacement). This is a tedious progress :(
One alternative solution would be to somehow enable importing of csv data directly in a already existing table (column name matches needs to be checked and eventually duplicates omitted of course).

**Comment by Z4us** [comment]
You can use the first line of a CSV-file as table definition with column names. No need to worry about types since SQLite does it "autodramaticcaly"

https://www.sqlite.org/cli.html#csv

**Comment by kutoman** [comment]
thanks for the advice!

**Comment by kutoman** [comment]
hmm unfortunately that does not really work:
"questionPool.csv:1: INSERT failed: datatype mismatch"

**Comment by justinclift** [comment]
Awesome stuff @Z4us . :smile:
