### ISSUE TITLE
error message when launching DB Browser v 3.11.2 under Win10

### ISSUE THREAD

**Issue by dbyy** [sqlitebrowser/sqlitebrowser#2160]
Details for the issue
--------------------

#### What did you expect to see?
I didn't expect any error message

#### What did you see instead?
![image](https://user-images.githubusercontent.com/8461068/76538564-e4b0a100-6455-11ea-8aef-2184ab8a1f96.png)

Useful extra information
-------------------------
![image](https://user-images.githubusercontent.com/8461068/76538744-28a3a600-6456-11ea-8d6b-5825f530b59d.png)

**Comment by justinclift** [comment]
Interesting.  We've seen this happen before, and (in theory) it should be fixed in our nightly builds:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Are you to try that and let us know how it goes?

**Comment by dbyy** [comment]
hm, according to your message it seems to me that the bug hasn't been identified yet. ;-)

**Comment by justinclift** [comment]
Nah, it's not that.  That particular error message shows up when "something" goes wrong with the network (controlled by Qt) when it tries to check if there's an update available.

It turns out Qt's network layer is fairly hairy, with strange + unexpected bugs that change per (Qt) version.  So, we've already "fixed" several things that can cause that error message, but there's no guarantee it's all completely done.

And yeah, that's unlike most other bugs.  It's just Qt's network layer is... lousy (not really fit for purpose, frankly) :frowning:

**Comment by dbyy** [comment]
Ok I get it :-) 

I will try a nightly build
Cheers

**Comment by dbyy** [comment]
I tested the nightly build from March 9th, 2020 (from a zip file).
The following message now appears (slightly different text):
![image](https://user-images.githubusercontent.com/8461068/76968326-19fa3a80-68ff-11ea-9ef8-0e172e72d0bd.png)

HTH

**Comment by justinclift** [comment]
Well damn. :wink:

Probably the most effective way to stop that error message is to turn off the automatic "check if there's a new version available" thing.

There **used** to be an option for that in the preferences, but I've just checked now and can't see it.  @mgrojo @MKleusberg @scottfurry Has it been renamed or something, or am I forgetting something obvious? :smile:

**Comment by scottfurry** [comment]
I just had a quick look at the program preferences and I don't see any 
setting to control "auto update check".

@MKleusberg, @justincliff - this sounds like a "feature" request. Not a 
deal breaker for next major release.
For Linux distributions, having such would be ideal from the build 
command line so as to disable updating except through package management.

**Comment by justinclift** [comment]
Nah, we **definitely** had an option to turn off the automatic update check. :smile:

**Comment by scottfurry** [comment]
> Nah, we definitely **had** an option to turn off the automatic update check. smile
FTFY

**Comment by justinclift** [comment]
Just realised... that option probably only shows up for Windows and macOS, as (generally) on Linux people get the software from their distribution package management software.

Looking at the latest nightly build for windows, the "Automatic updates" option does show up. @dbyy Try turning off the automatic update check:

![DB4S-preferences](https://user-images.githubusercontent.com/406299/77027551-ab92a680-69ea-11ea-8f1a-30bbfb51ff68.png)

**Comment by scottfurry** [comment]
@justinclift - which means it's platform specific?
That's not good.

**Comment by justinclift** [comment]
@scottfurry Yeah, it's platform specific because it's a decent approach for the situation.  Windows and macOS users tend to download directly from us, thus the update check.  But other platforms tend to have their own software package distribution mechanisms, where the update check would get in the way.

**Comment by scottfurry** [comment]
Then there's app-store users et al. A little surprised that feature is not configurable from command line. (i.e. homebrew MacOSX users would be one use case). I need to revisit this later.

**Comment by dbyy** [comment]
I turned the automatic update off (check mark off) and it appears to resolve the problem (for now).
Even though this is not resolving that problem itself - just by-passing it.
Anyway -- thanks

**Comment by justinclift** [comment]
@scottfurry Good point.  From memory, there is some way to change preference info from the command line.  There should be examples here in the GitHub issues (somewhere :wink:).

@dbyy You're welcome. :smile:

**Comment by scottfurry** [comment]
@justinclift  - oddly enough, I just had that conversation tonight with someone else...
https://xkcd.com/1313/
I'll dig it out(somehow) if only to make things more obvious and/or update wiki.

**Comment by mgrojo** [comment]
Yes, it is as you have already mentioned. That setting in Preferences is only enabled with the` -DCHECKNEWVERSION` flag, which is enabled for Windows under:
https://github.com/sqlitebrowser/sqlitebrowser/blob/763a4a0b9240b90bcc4eb8cc9ee06b88aef83631/CMakeLists.txt#L333
and for MacOSX under:
https://github.com/sqlitebrowser/sqlitebrowser/blob/763a4a0b9240b90bcc4eb8cc9ee06b88aef83631/CMakeLists.txt#L353

**Comment by mgrojo** [comment]
> @scottfurry Good point. From memory, there is some way to change preference info from the command line. There should be examples here in the GitHub issues (somewhere wink).

Yes, there is a way in the nightlies, the` --save-option` or `-O` command-line options. It would be: 
`sqlitebrowser --save-option checkversion/enabled=false`

`sqlitebrowser` would be `DB Browser for SQLite.exe` under Windows.
