### ISSUE TITLE
Can't open database from SqlCipher 4.3.0 on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by eygraber** [sqlitebrowser/sqlitebrowser#2162]
Details for the issue
--------------------

#### What did you do?

Downloaded a sqlite database file from my Android app. It is encrypted using SqlCipher 4.3.0 with the default settings. I tried opening it and was asked for the password. I entered it correctly, selected SqlCipher4 defaults, and pressed OK.

#### What did you expect to see?

The database opened

#### What did you see instead?

The encryption dialog again

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Linux: Ubuntu 18.04.4

#### What is your DB4S version?

I tried 3.11.2 and 3.11.299-0~2709~202003090047~ubuntu18.04.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  It sounds like the versions you've tried on Ubuntu were compiled with a different (maybe older?) version of SQLCipher.

If you go into About -> Help, in theory it should show the version of SQLCipher in use.

Would you be ok to check that, and let us know? :smile:

**Comment by eygraber** [comment]
Version 3.11.99 (Mar  9 2020)

Built for x86_64-little_endian-lp64, running on x86_64

Qt Version 5.9.5

SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

**Comment by justinclift** [comment]
Cool, that helps.  The version of SQLCipher there (3.4.1) isn't compatible with SQLCipher 4.x as far as I know. :frowning:

That being said, lets ask @deepsidhu1313 if it would be feasible for the Ubuntu nightly builds to use SQLCipher 4.x instead.

@deepsidhu1313 Any idea? :smile:

**Comment by justinclift** [comment]
As a thought for a workaround, if you have a windows computer handy then our nightly builds for that are done with the SQLCipher 4.x.

Using that would let you open the database, and then decrypt it for use on your Ubuntu computer.  That being said, only go down this track if having it unencrypted somewhere is an ok thing for your use case. :smile:

**Comment by deepsidhu1313** [comment]
> Cool, that helps. The version of SQLCipher there (3.4.1) isn't compatible with SQLCipher 4.x as far as I know. 
> 
> That being said, lets ask @deepsidhu1313 if it would be feasible for the Ubuntu nightly builds to use SQLCipher 4.x instead.
> 
> @deepsidhu1313 Any idea?

i don't think that is possible at the moment, as our packages use official repos and official repos have 3.4.1_build1 of sqlcipher at the moment. Which might change with the next release of Ubuntu(due this month).

**Comment by justinclift** [comment]
Thanks @deepsidhu1313, that's useful to know. :smile:

@eygraber Not really sure what to recommend here.  You need to figure out some way of using a SQLite GUI that has SQLCipher 4.x support.  We do in our Windows and Mac builds, but the Linux ones pretty much depend on whatever SQLCipher version is available for the given platform. :frowning:

**Comment by deepsidhu1313** [comment]
@justinclift  i will see if we can build SQlCipher in our repo and use it to build new packages.

**Comment by eygraber** [comment]
I updated Ubuntu to 20.04 and they still package SqlCipher v3. It would be very much appreciated if you could build against the latest SqlCipher :smile:

**Comment by scottfurry** [comment]
Quick look at this one. It appears that upstream provides a precompiled binary for Android usage. Currently available revision of precompiled Android binaries is [v4.3.0](https://www.zetetic.net/sqlcipher/open-source/).

Upstream also makes available sources to be compiled. I suspect that that observation being reported is attributable to differences in compiling options and versions being used.

Current available in [Ubuntu](https://packages.ubuntu.com/search?keywords=sqlcipher&searchon=names&suite=eoan&section=all) is 3.4.1. Same for [Debian](https://packages.debian.org/search?keywords=sqlcipher&searchon=names&suite=buster&section=all). Full spread of availability is [here](https://repology.org/project/sqlcipher/versions).

I would recommend we implement [latest SQLCipher sources](https://github.com/sqlcipher/sqlcipher/releases) into tree while distributions get up to speed.

**Comment by justinclift** [comment]
> I would recommend we implement latest SQLCipher sources into tree while distributions get up to speed.

Interesting idea.  Might be the right approach. :smile:

**Comment by scottfurry** [comment]
I'm thinking we can treat this in a manner as we already do WRT QHexEdit and QCustomPlot (flags in CMakeLists.txt and qmake *.pro files as to whether to build against internal/external library).

It's not an impossible situation. The "best practices" type action I've seen in another project is to have an "external" folder (name can be something else but "3rd Party" should be discouraged) that has the git/versioned source dependencies. "git submodules" should be discouraged (messy, ugly, PITA, other expletives as desired).

I would also fold into this one other issue that hasn't been identified but appears to be potential failure point. The source tree has other libraries(e.g. Nholmann's JSON C++ library) but these may/may not be verbatim copies of upstream. The header/source files have been modified for our purposes an it isn't exactly clear how we got from Point A (upstream version) to Point B(what's in the tree). Scripts, README's, et al should be in this folder that defines how external libraries are modified for the project - IMHO with copious $0.02.

**Comment by scottfurry** [comment]
This is doable. No errors/warnings encountered during build but I don't have anything to test against.
![AboutDlg_2020Apr29](https://user-images.githubusercontent.com/6686571/80653675-ef3fed80-8a37-11ea-8a61-e7c385aee3e3.png)

**Comment by justinclift** [comment]
Interesting.  @MKleusberg @mgrojo What do you reckon about adding SQLCipher to our source tree?

It would potentially let @deepsidhu1313 build with that across all versions of Ubuntu, as even the new Ubuntu release is still stuck on SQLCipher 3.x. :frowning:

**Comment by justinclift** [comment]
> Scripts, README's, et al should be in this folder that defines how external libraries are modified for the project - IMHO with copious $0.02.

Good point @scottfurry. :smile:

**Comment by deepsidhu1313** [comment]
If sqlcipher is openly available i will look into creating a new ppa(s) to
build upstream packages. But that is not possible until weekend.

**Comment by scottfurry** [comment]
> If sqlcipher is openly available i will look into creating a new ppa(s) to build upstream packages. But that is not possible until weekend.

@deepsidhu1313 - download site for community edition is [here](https://www.zetetic.net/sqlcipher/open-source/)

**Comment by deepsidhu1313** [comment]
Thanks, i will look into it.

**Comment by deepsidhu1313** [comment]
@scottfurry please use our nightly ppa to test sqlcipher 4.3.0. Once you verify the sqlcipher is working as intented , i will update db4s packages to use sqlcipher 4.3.0 from our ppa and we can do another test.

**Comment by eygraber** [comment]
Will do shortly. Really appreciate this!

**Comment by eygraber** [comment]
Tested 3.12.99 and it accepts the passphrase that I supply without an error, but it doesn't show any of the data that is in the db once it is open.

**Comment by justinclift** [comment]
@eygraber Once the encrypted database is opened, is it showing any kind of structure (tables, etc) correctly?

Just wondering if it's a complete blank, or partially working, or ? :wink:

**Comment by eygraber** [comment]
Completely blank. Querying sqlite_master returns 0 rows.

**Comment by deepsidhu1313** [comment]
Moved sqlcipher to its own dedicated ppa
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlcipher-nightly

And triggered rebuild for sqlitebrowser package.
@eygraber May i request you to download latest build from our ppa and give it one more try, and please check on About page which sqlcipher version it says it is using ?

**Comment by deepsidhu1313** [comment]
@justinclift does DB4S shows the libsqlite version used to compile it or is it Harcoded ?

**Comment by justinclift** [comment]
@deepsidhu1313 It shows the version it was compiled with in Help -> About.

It's not hard coded.  So, if you're still seeing an older version in there, then somehow the older version is what was being picked up and compiled with.

**Comment by eygraber** [comment]
It was user error :sweat_smile: 

I wasn't copying the .wal and .db-shm files from my Android device with the .db file. Everything seems to be working great, thank you!

**Comment by justinclift** [comment]
Awesome! :smile:
