### ISSUE TITLE
Duplicate record creates a new empty record

### ISSUE THREAD

**Issue by dhdeangelis** [sqlitebrowser/sqlitebrowser#2163]
When duplicating a record in a table a new but empty record is created. This behavior wasn't present in previous versions (unfortunately did not register the number of the last used, but it was the version available for openSUSE Leap 15.1).

I am using version 3.11.2-1.3 that comes with openSUSE Tumbleweed (20200311-0).

Information for package sqlitebrowser:
--------------------------------------
Repository     : Main Repository (OSS)                         
Name           : sqlitebrowser                                 
Version        : 3.11.2-1.3                                    
Arch           : x86_64                                        
Vendor         : openSUSE                                      
Installed Size : 4.5 MiB                                       
Installed      : Yes                                           
Status         : up-to-date                                    
Source package : sqlitebrowser-3.11.2-1.3.src   

The database is SQLITE3:

Information for package sqlite3:
--------------------------------
Repository     : Main Repository (OSS)         
Name           : sqlite3                       
Version        : 3.31.1-2.2                    
Arch           : x86_64                        
Vendor         : openSUSE                      
Installed Size : 1.3 MiB                       
Installed      : Yes                           
Status         : up-to-date                    
Source package : sqlite3-3.31.1-2.2.src

**Comment by justinclift** [comment]
Interesting.  We're getting ready for our next release presently, which shouldn't (in theory) have this bug any more.

Not sure how long it'll be until Tumbleweed picks up the next release though.

Um... any interest in compiling our latest code from source, and checking if that works better for you?

If so, we have generic instructions for OpenSUSE, though I'm unsure which release stream (SLES, Leap, Tumbleweed, etc) they're for:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#opensuse

**Comment by dhdeangelis** [comment]
Thank you for your reply. It is effectively as you mention. I just downloaded the latest code and built without problems (just a lot of warnings from gcc 9). Sqlitebrowser works just fine. The bug is not present. So this issue can be closed.

**Comment by justinclift** [comment]
Awesome.  Thanks for checking and letting us know @dhdeangelis. :smile:
