### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Sayan-Ghosh** [sqlitebrowser/sqlitebrowser#2164]
Getting the following error when trying to install in ubuntu 18.04 

`Err:1 http://in.archive.ubuntu.com/ubuntu bionic/universe amd64 libsqlcipher0 amd64 3.4.1-1build1                                                                                                                 
  Cannot initiate the connection to in.archive.ubuntu.com:80 (2403:8940:ffff::f). - connect (101: Network is unreachable) Could not connect to in.archive.ubuntu.com:80 (103.97.84.254), connection timed out [IP: 103.97.84.254 80]
E: Failed to fetch http://in.archive.ubuntu.com/ubuntu/pool/universe/s/sqlcipher/libsqlcipher0_3.4.1-1build1_amd64.deb  Cannot initiate the connection to in.archive.ubuntu.com:80 (2403:8940:ffff::f). - connect (101: Network is unreachable) Could not connect to in.archive.ubuntu.com:80 (103.97.84.254), connection timed out [IP: 103.97.84.254 80]
`

**Comment by Sayan-Ghosh** [comment]
Network is absolutely OK but still getting network issues. Also I tried to install it from the Ubuntu Software store and there also it's getting the same error.

**Comment by justinclift** [comment]
Weird.  That **seems** like some network connection error happening for the official Ubuntu servers.

Hopefully it's just some kind of temporary issue on their end, and clears up fairly quickly. :smile:

**Comment by scottfurry** [comment]
> Weird. That **seems** like some network connection error happening for the official Ubuntu servers.
> 
> Hopefully it's just some kind of temporary issue on their end, and clears up fairly quickly. smile

Due to world events, networks all over are being hammered. Some by legitimate use just overwhelming servers. Others,.... not so legitimate. If we've uploaded "latest and greatest" and people can't download, I would think that it's an Ubuntu network issue. The "cannot initiate connection" and 'timed out" messages supports this theory.

A quick check of [site testing](https://check-host.net/check-ping?host=103.97.84.254) indicates problems server problems.

**Comment by justinclift** [comment]
@Sayan-Ghosh Have you had a chance to try it again in the last few hours?

Looking at the site testing link @scottfurry provided, it **seems** like the server should be working for people again. :smile:

**Comment by chrisjlocke** [comment]
@Sayan-Ghosh **cough**

**Comment by justinclift** [comment]
Meh, just going to close this.  It was a problem with the Ubuntu servers, and isn't really something under our control. :smile:
