### ISSUE TITLE
Program crashes when trying to alter column type

### ISSUE THREAD

**Issue by boris-so** [sqlitebrowser/sqlitebrowser#2168]
[Sqlite does not implement](https://www.sqlite.org/omitted.html) alter of column type. But comboboxes with column types in "alter table" dialog are active and program crashes when trying to modify value in them.
--------------------

#### What did you do?
I'm trying to change type of column for existing database (knowing it's not supported by database).

#### What did you expect to see?
Since [sqlite does not implement](https://www.sqlite.org/omitted.html) ablity to alter column types, so i expect comboboxes be, for example, disabled in alter table dialog (for existing columns only)

#### What did you see instead?
Program crashes when i try to open any combobox with mouse or by typing new type into text field of combobox.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: debian buster)
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [x] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
In theory, this should work.  Obviously it's not though. :frowning:

Is there any chance you're up for compiling our latest code for yourself?  That'd very likely get you a working solution.

If that's ok interest, our instructions for Ubuntu are likely pretty close:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

That being said, I don't run Ubuntu nor Debian personally so aren't 100% sure. :wink:

**Comment by boris-so** [comment]
So much time ago, but anyway...
I followed that steps to compile, but have some errors with `make`:
```
[ 80%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/FindReplaceDialog.cpp.o
/home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp: In member function ‘bool FindReplaceDialog::findFirst(bool, bool)’:
/home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:59:30: error: no matching function for call to ‘ExtendedScintilla::findFirstInSelection(QString, bool, bool, bool, bool&, bool, bool, bool)’
              /* cxx11 */ true);
                              ^
In file included from /home/boris/projects/sqlitebrowser/src/ExtendedScintilla.h:4,
                 from /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:813:18: note: candidate: ‘virtual bool QsciScintilla::findFirstInSelection(const QString&, bool, bool, bool, bool, bool, bool)’
     virtual bool findFirstInSelection(const QString &expr, bool re, bool cs,
                  ^~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:813:18: note:   candidate expects 7 arguments, 8 provided
/home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:72:30: error: no matching function for call to ‘ExtendedScintilla::findFirst(QString, bool, bool, bool, bool&, bool&, int, int, bool, bool, bool)’
              /* cxx11 */ true);
                              ^
In file included from /home/boris/projects/sqlitebrowser/src/ExtendedScintilla.h:4,
                 from /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:3:
/usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:783:18: note: candidate: ‘virtual bool QsciScintilla::findFirst(const QString&, bool, bool, bool, bool, bool, int, int, bool, bool)’
     virtual bool findFirst(const QString &expr, bool re, bool cs, bool wo,
                  ^~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:783:18: note:   candidate expects 10 arguments, 11 provided
make[2]: *** [CMakeFiles/sqlitebrowser.dir/build.make:1080: CMakeFiles/sqlitebrowser.dir/src/FindReplaceDialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/sqlitebrowser.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
My versions of dependencies packages:
```
ii  build-essential                               12.6                                 amd64        Informational list of build-essential packages
ii  cmake                                         3.13.4-1                             amd64        cross-platform, open-source make system
ii  libqcustomplot-dev                            2.0.1+dfsg1-1                        amd64        Qt C++ widget for plotting - header
ii  libsqlcipher-dev                              3.4.1-1+b12                          amd64        SQLCipher development files
ii  libsqlite3-dev:amd64                          3.27.2-3                             amd64        SQLite 3 development files
ii  qt5-default:amd64                             5.11.3+dfsg1-1+deb10u3               amd64        Qt 5 development defaults package
ii  qtbase5-dev:amd64                             5.11.3+dfsg1-1+deb10u3               amd64        Qt 5 base development files
ii  qttools5-dev:amd64                            5.11.3-4                             amd64        Qt 5 tools development files
ii  qttools5-dev-tools                            5.11.3-4                             amd64        Qt 5 development tools
```
Maybe some of them are too old?

**Comment by justinclift** [comment]
Most of those look ok.  Which compiler (and version) are you using? :smile:

**Comment by justinclift** [comment]
As a general thought after reading this bug report, you should be able to alter column type with our program.  Although SQLite itself doesn't support it, we do a couple of behind the scenes tricks to make it work.  eg be user friendly.

That being said, the crashing behaviour is definitely not supposed to be happening. :smile:

**Comment by boris-so** [comment]
> Most of those look ok. Which compiler (and version) are you using?

```
$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ make --version
GNU Make 4.2.1
```

**Comment by boris-so** [comment]
Have just tried night build (3.12.99 - May 7 2020) [from here](https://nightlies.sqlitebrowser.org/latest/) in my win10 vm --  changing column type works without any issues. So I bielive it is a linux-related issue or an old version issue.

But I cannot suggest any ways to get compilation work yet, it seems like coding errors to me... I will try to google smth to get compiled version.

**Comment by scottfurry** [comment]
@boris-so - The make cools about right. Can please post the output of `g++ --version`.
Since you are building from source, can you clarify if you are using `--std="c++{11, 14, 17}"` (or in CMake `-DCMAKE_CXX_VERSION={11,14,17}`)

**Comment by boris-so** [comment]
> Can please post the output of `g++ --version`
```
$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

> Since you are building from source, can you clarify if you are using --std="c++{11, 14, 17}" (or in CMake -DCMAKE_CXX_VERSION={11,14,17})
I am not very familiar with compilation process in c. But following the guide above I had not used any special keys or variables for `make` and `cmake`. At least in an explicit way...

**Comment by scottfurry** [comment]
@boris-so - ping me on our gitter channel. There's a couple of interactive things we can do to sort this out for you (with the added bonus of not filling up everyone's email inbox with notifications).
https://gitter.im/sqlitebrowser/sqlitebrowser

**Comment by boris-so** [comment]
Thanks a lot to @scottfurry i made the compilation process work and got a latest binary.
The behaviour described was not reproduced in version 3.12.99 (May  8 2020).

**Comment by scottfurry** [comment]
Addendum: @boris-so mentioned he followed our Ubuntu instructions [from here](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux). We may need to verify these other instructions at a later date.

**Comment by justinclift** [comment]
Yep, sounds like we should check if they need adjusting for recent Ubuntu releases.

**Comment by xxsl** [comment]
> So much time ago, but, anyway...
> I followed that steps to compile, but have some errors with `make`:
> 
> ```
> [ 80%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/FindReplaceDialog.cpp.o
> /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp: In member function ‘bool FindReplaceDialog::findFirst(bool, bool)’:
> /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:59:30: error: no matching function for call to ‘ExtendedScintilla::findFirstInSelection(QString, bool, bool, bool, bool&, bool, bool, bool)’
>               /* cxx11 */ true);
>                               ^
> In file included from /home/boris/projects/sqlitebrowser/src/ExtendedScintilla.h:4,
>                  from /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:3:
> /usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:813:18: note: candidate: ‘virtual bool QsciScintilla::findFirstInSelection(const QString&, bool, bool, bool, bool, bool, bool)’
>      virtual bool findFirstInSelection(const QString &expr, bool re, bool cs,
>                   ^~~~~~~~~~~~~~~~~~~~
> /usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:813:18: note:   candidate expects 7 arguments, 8 provided
> /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:72:30: error: no matching function for call to ‘ExtendedScintilla::findFirst(QString, bool, bool, bool, bool&, bool&, int, int, bool, bool, bool)’
>               /* cxx11 */ true);
>                               ^
> In file included from /home/boris/projects/sqlitebrowser/src/ExtendedScintilla.h:4,
>                  from /home/boris/projects/sqlitebrowser/src/FindReplaceDialog.cpp:3:
> /usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:783:18: note: candidate: ‘virtual bool QsciScintilla::findFirst(const QString&, bool, bool, bool, bool, bool, int, int, bool, bool)’
>      virtual bool findFirst(const QString &expr, bool re, bool cs, bool wo,
>                   ^~~~~~~~~
> /usr/include/x86_64-linux-gnu/qt5/Qsci/qsciscintilla.h:783:18: note:   candidate expects 10 arguments, 11 provided
> make[2]: *** [CMakeFiles/sqlitebrowser.dir/build.make:1080: CMakeFiles/sqlitebrowser.dir/src/FindReplaceDialog.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/sqlitebrowser.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```
> 
> My versions of dependencies packages:
> 
> ```
> ii  build-essential                               12.6                                 amd64        Informational list of build-essential packages
> ii  cmake                                         3.13.4-1                             amd64        cross-platform, open-source make system
> ii  libsqlite3-dev:amd64                          3.27.2-3                             amd64        SQLite 3 development files
> ii  qt5-default:amd64                             5.11.3+dfsg1-1+deb10u3               amd64        Qt 5 development defaults package
> ii  qttools5-dev-tools                            5.11.3-4                             amd64        Qt 5 development tools
> ii  libsqlcipher-dev                              3.4.1-1+b12                          amd64        SQLCipher development files
> ii  qtbase5-dev:amd64                             5.11.3+dfsg1-1+deb10u3               amd64        Qt 5 base development files
> ii  libqscintilla2-qt5-dev                        2.10.4+dfsg-2.1                      amd64        Scintilla source code editing widget for Qt5, development files
> ii  libqcustomplot-dev                            2.0.1+dfsg1-1                        amd64        Qt C++ widget for plotting - header
> ii  qttools5-dev:amd64                            5.11.3-4                             amd64        Qt 5 tools development files
> ```
> 
> Maybe some of them are too old?

If you're using Debian Buster, just add -DFORCE_INTERNAL_QSCINTILLA=ON to your cmake parameters, It will be ok to go. 
Things here seem to be slightly different from Ubuntu. I think the document should be updated and add new section for Debian.

**Comment by justinclift** [comment]
> I think the document should be updated and add new section for Debian.

Want to make a Pull Request with that info?

Hmmm, might be be good enough to just add something like "If you're using Debian Buster...", plus rename the Ubuntu section to be "Debian or Ubuntu"?

**Comment by xxsl** [comment]
Done ;-) #2414

**Comment by justinclift** [comment]
Thanks, merged it .:smile:

**Comment by xxsl** [comment]
😋
