### ISSUE TITLE
Regex searches in filters

### ISSUE THREAD

**Issue by B-bit-maker** [sqlitebrowser/sqlitebrowser#2171]
Describe the new feature
--------------------------
Is it possible to implement the possibility to perform regex searches directly from the filters?
Thanks

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
Yes, take a look at  #1522. Summarizing, you have to enclose the regexp between '/' characters. But it is not released yet, you'll have to wait for our next stable release or install a [nightly build](https://nightlies.sqlitebrowser.org/latest/) to try it out.

**Comment by B-bit-maker** [comment]
Ok, thanks.
