### ISSUE TITLE
Cannot open encrypted database（打不开加密的数据库）

### ISSUE THREAD

**Issue by Archer353** [sqlitebrowser/sqlitebrowser#2172]
What is your question
-----------------------
打开加密的数据库时，总是提示让我输入密码。但是我输入之后还让我输入。数据库是wcdb用SQLCipher方式加密的。我该怎么做才能打开。
（When opening an encrypted database, I am always prompted for my password.
But after I typed it, it asked again.
The database is encrypted by wcdb using SQLCipher.
What can I do to open it.）

**Comment by justinclift** [comment]
Guessing "wcdb" is this one:

&nbsp; &nbsp; https://github.com/Tencent/wcdb

Is there some way of finding out what version of SQLCipher they're using?

As a first guess, it sounds like (maybe) they're using a different version of SQLCipher than we are, that isn't compatible?

If that's the case, and they're using SQLCipher version 3.<something>, then you might be able to open it with our older versions.  eg maybe our version 3.10.x or even 3.9.x.

Does that help? :smile:

**Comment by justinclift** [comment]
Closing this, due to lack of response.
