### ISSUE TITLE
Unable to open a DB file Browser for SQLite "Motif : File is not a database"

### ISSUE THREAD

**Issue by GeorgeSears15** [sqlitebrowser/sqlitebrowser#2173]
Details for the issue

I installed 3.11.2 x64 for W7 version, when I want to open a databse, I have this message "Motif: File is not a database"

Click oo File > Open Database > Locate to the file you want to read
Click on Open et the error message is dpslayed "Motif: File is not a database"

The file is in .db (cisco jabber history chat)

#### What did you do?

I want to open the DB history of cisco jabber 

#### What operating system are you using?

- [ x] Windows: ( _version:_7 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ x] 3.11.2

![db](https://user-images.githubusercontent.com/63109547/78379699-12ab8000-75d3-11ea-9ad5-9db57d1cbd58.PNG)

**Comment by justinclift** [comment]
Interesting.  As a way to test the file, are you ok to try opening the file with the SQLite command line interface?

&nbsp; &nbsp; https://sqlite.org/download.html#a10

It's not a GUI, but it's the gold standard for checking if a file is "really" a SQLite database.  eg meets the spec and isn't damaged in some strange way

**Comment by GeorgeSears15** [comment]
Hi Justinclift,

First of all, thanks you for your help, really appreciate it.
As I said in my profim, i'm just a beginner who want to recover some chat history, 

What do you mean by " **As a way to test the file, are you ok to try opening the file with the SQLite command line interface?"**

Which Download should I take please ?

**Comment by justinclift** [comment]
Yep, that's the right download. :smile:

Sorry, I didn't see your profile so didn't pick up on you being a beginner!

With the SQLite command line tool, it's useful for checking if a given file is really a SQLite database file.  There are lots of different types of database files, and sometimes people pick us when it's the wrong choice. :smile:

That SQLite command line tool though is more of an "advanced computer user" type of thing though, as it doesn't have a graphical interface and needs people to type in text commands.

Um... as a potential easier workaround, how confidential is that database file of yours?  Asking because you could just email it to me (justin@postgresql.org) and I can check what sort of database it is.  I won't forward it on to anyone else, share the contents (etc).  This is just from the "probably easier option" point of view though. :smile:

**Comment by GeorgeSears15** [comment]
Hi Justin Clift.

First of all I will try to make it. And If I don't get it. I will send you a private message with th dB files, no problem. Nothing very confidence or sensible.

So which Commands Do I do please in the command tool ?

Thx a lot.

**Comment by justinclift** [comment]
No worries. :smile:

First things first, make sure the sqlite3.exe file, and your database file, are in the same directory.

As an example, this is a screenshot taken just now showing what I mean.  It has the 3 files from that SQLite .zip file extracted to a directory, and I've put a small example database ([2.5mb.sqlite](https://dbhub.io/justinclift/2.5mb.sqlite)) in the same directory.

![db4s-issue-2173-screenshot1](https://user-images.githubusercontent.com/406299/78534279-80eb7f00-782d-11ea-875e-e99f4e43ddd5.png)

When I then double click on the `sqlite3.exe` file to run it, the same black window thing will show up that you saw.

What you need to do is click on the window so commands you type will go into it, and then type the word `.open` followed by the name of your database file, then press Enter.

eg:

![db4s-issue-2173-screenshot2](https://user-images.githubusercontent.com/406299/78534381-aed0c380-782d-11ea-93a8-98cc461ac91c.png)

In theory (!) if that database file of yours really is a SQLite one, it should open up fine and no error message will be returned.  Then you can type `.tables` (and Enter), to show the top level structure inside the file.

If that works, without any errors, then it means your file is ok, and we next need to figure out why the heck our program isn't opening it. :wink:

On the other hand, if it gives an error, please screenshot it or somehow tell us the error message so we can figure out potential next steps. :smile:

Oh, to quite that black command line window the "proper" way is to type in `.quit` (and Enter).  Though just clicking the Close button might work too. :wink:

**Comment by justinclift** [comment]
> Where can I donate for the sqlite project and github? It would be a pleasure to make a little donation.

Not sure about GitHub (they're a commercial-only organisation), but our project has a Patreon account, and it would be **really, really** appreciated:

&nbsp; &nbsp; https://www.patreon.com/db4s

**Comment by GeorgeSears15** [comment]
> 
> 
> No worries. smile
> 
> First things first, make sure the sqlite3.exe file, and your database file, are in the same directory.
> 
> As an example, this is a screenshot taken just now showing what I mean. It has the 3 files from that SQLite .zip file extracted to a directory, and I've put a small example database ([2.5mb.sqlite](https://dbhub.io/justinclift/2.5mb.sqlite)) in the same directory.
> 
> ![db4s-issue-2173-screenshot1](https://user-images.githubusercontent.com/406299/78534279-80eb7f00-782d-11ea-875e-e99f4e43ddd5.png)
> 
> When I then double click on the `sqlite3.exe` file to run it, the same black window thing will show up that you saw.
> 
> What you need to do is click on the window so commands you type will go into it, and then type the word `.open` followed by the name of your database file, then press Enter.
> 
> eg:
> 
> ![db4s-issue-2173-screenshot2](https://user-images.githubusercontent.com/406299/78534381-aed0c380-782d-11ea-93a8-98cc461ac91c.png)
> 
> In theory (!) if that database file of yours really is a SQLite one, it should open up fine and no error message will be returned. Then you can type `.tables` (and Enter), to show the top level structure inside the file.
> 
> If that works, without any errors, then it means your file is ok, and we next need to figure out why the heck our program isn't opening it. wink
> 
> On the other hand, if it gives an error, please screenshot it or somehow tell us the error message so we can figure out potential next steps. smile
> 
> Oh, to quite that black command line window the "proper" way is to type in `.quit` (and Enter). Though just clicking the Close button might work too. wink

Hi Justin,

Here a screenshot

![sql](https://user-images.githubusercontent.com/63109547/78558048-3a3c5b80-7812-11ea-8c99-16660376bb52.PNG)

It Seems the size of db file generated by sql3 is 0 KO, Is it normal ? As you can see, When I Tap .open and .tables, it works....

Here the file when I open it

![sql2](https://user-images.githubusercontent.com/63109547/78558216-838cab00-7812-11ea-97b2-d021c15da8d1.PNG)

**Comment by GeorgeSears15** [comment]
If you want, I can send you the db files (2 files)

Thx a lot

**Comment by justinclift** [comment]
Ahhh.  When you type in the file name, it needs the full thing.  Both the file name and it's extension.  eg "dbfile.db"

Note the ".db" bit in my example here is just a guess.  You'll need to check what the extension of your file really is.  It's probably viewable in the file properties (right click on it -> properties).

If the file extension doesn't show up there, then it should show up if you turn on the "Show file extensions" setting in Windows.  On Windows 7 that was in Control Panel -> Folder Options.  No idea what it is in Windows 10 though, as I've never run it. :wink:

Btw, when you type in a filename to the SQLite command line window, if the filename doesn't exist then SQLite will create a new database using that name.

So, `.open dbfile` (with no extension on the end) is just creating a blank new empty file.  Thus the new one appearing when you do that. :wink:

**Comment by GeorgeSears15** [comment]
Hi Justin. Thx again for your helps. Could I send you the dB files in private message please?

The extension is. DB and the hidden folder has been set on windows 7 folder. 

Thx a lot very appreciate it. Especially with covid 19

**Comment by GeorgeSears15** [comment]
I will try to use the command 
.Open dbfile.db indeed

I forgot the extension sorry

**Comment by justinclift** [comment]
> Could I send you the dB files in private message please?

Yep, just email them to me (justin@postgresql.org).  I'll see if I can figure out what's wrong. :smile:

**Comment by justinclift** [comment]
Did some looking around online, and it turns out the Cisco's Jabber software **used** to store things in standard SQLite databases.  But from version 11.9 of their software, they switched across to encrypting the data:

&nbsp; &nbsp; https://www.pilotmikekc.com/2016/02/12/viewing-cisco-jabber-local-history-file/

Unless you can get hold of the encryption key - which Cisco doesn't seem to give out :frowning: - there's no reasonable way to open the database.

**Comment by GeorgeSears15** [comment]
Can I send you the db files in private message please as you said before ? Thx a lot

> 
> 
> Did some looking around online, and it turns out the Cisco's Jabber software **used** to store things in a standard SQLite database. But from version 11.9 of their software, they switched to encrypting the data:
> 
>     https://www.pilotmikekc.com/2016/02/12/viewing-cisco-jabber-local-history-file/
> 
> Unless you can get hold of the encryption key - which Cisco doesn't seem to give out frowning - there's no reasonable way to open the database.


Yes It seems that cisco jabber upper than 11.9 version encrypted data.
Maybe it's impossible to recover that.

I just sent yu 2 db files in your email, thax a lot, If you're don't be able to do that, thx again !

**Comment by justinclift** [comment]
Took a look at those files, and yep... as expected it's a no go.  Without the encryption key, there's no way to unlock them. :frowning:

**Comment by GeorgeSears15** [comment]
Hi Justin, Yes indeed it seems it's impossible.....don't worry, thx again
my friend.
Do you have a paypal or something, as i said, i will make a little donation
as promised.

Thx again

Le lun. 6 avr. 2020 à 18:18, Justin Clift <notifications@github.com> a
écrit :

**Comment by justinclift** [comment]
Thanks.  Just responded via private email. :smile:
