### ISSUE TITLE
Larger sized numbers exported via JSON are incorrect

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2175]
This is from a new report on Twitter (with accompanying video) shows the the JSON export in 3.11.2 is incorrectly rounding or truncating larger sized values:

&nbsp; &nbsp; https://twitter.com/ItzFaded1/status/1245803820875218944

Details for the issue
--------------------

Exported a simple 1 row table with 2 fields to JSON.

The values in the JSON export are slightly **different** to the numbers in the source table. :frowning:

https://www.youtube.com/watch?v=DLMwESmUd6E

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows (10)

#### What is your DB4S version?

- [x] 3.11.2

**Comment by scottfurry** [comment]
Maybe we can lump this with idea of testing and have a json test suite to ensure correctness.

**Comment by justinclift** [comment]
Good thinking. :smile:

**Comment by justinclift** [comment]
Adding this to the Release Blocker category, as if it's still happening it needs fixing for 3.12.0. :smile:

**Comment by scottfurry** [comment]
Unfortunate that person reporting disappeared. I'm experimenting with large numbers here. One thing that jumps out from reporting is that underlying field types being used is missing. SQLite has a rather esoteric "type affinity" system(see Section 3 https://www.sqlite.org/datatype3.html ).

If I insert a large numbers into NUMERIC type fields of a table, SQLite will convert those to scientific notation immediately if the values are large enough. Experimenting on Linux system w/ SQLite 3.31.1 found that to be ~18 digit integer. The same scientific values are then exported to JSON verbatim. No truncation appears.

Without more information from the user, I'm inclined to close this and monitor. My suspicion is that some field manipulation is happening in the value export either in Qt or SQLite.

For Future reference: src/ExportDataDialog:233 -> exportQueryJson()

**Comment by horst-p-w-neubauer** [comment]
here is a snapshot of the video, showing the datatypes of the admin table:
![grafik](https://user-images.githubusercontent.com/28151942/80926890-44faf980-8d9a-11ea-9490-e0c97ebc55db.png)

**Comment by scottfurry** [comment]
@horst-p-w-neubauer - those are 'other' SQL datatypes - not SQLite datatypes.
It doesn't change the observations above.

**Comment by justinclift** [comment]
> Unfortunate that person reporting disappeared.

They reported via Twitter.  They're probably still around if we engage there. :smile:

**Comment by scottfurry** [comment]
@justinclift - I'll disagree with you on closing. We should remove that this bug stops the next release. Here's why...

When doing digging, I was throwing very large integer numbers at DB4S and exporting to JSON. I did not see the truncation errors originally posted. Again, up to about 17 digit integer and no errors. At 18, sqlite decides to kick in scientific notation. That was exported verbatim also.

Same is true for TEXT/REAL/BLOB values. JSON just moved them over. I think the truncation problem is with how the number was retrieved and/or a problem with the underlying database integrity. Without more info from user and/or a copy of their data, there's nothing else we can do here. This "feels" like an issue on the user's end.

**Comment by horst-p-w-neubauer** [comment]
I did also try to retrace the behavior with the nightly build and with an older 3.10.1 version and could not find the shown effect. I've once had a problem with sqlite and big numbers in Delphi. But that derived from the connection components I was using. So maybe it could be a problem with any library - but I don't think, that the user was building his version out of the sources by himself (we windows user don't do this ;-) ).

I agree with @scottfurry , that this should not block 3.12.
Is there a label that we wait need more information? 
I'd suggest to set a deadline when to close the issue, if we don't get more information.

**Comment by horst-p-w-neubauer** [comment]
Let me guess: None of you tested with Version 3.11.2?
I just did - and I even got the same behavior than our friend on twitter!
What ever it was - it's gone for 3.12.
I suggest to put it into 'Known problems versoin 3.11.2' and close the issue.

**Comment by justinclift** [comment]
Thanks. :smile:

That means the problem was likely with the older JSON export approach we were using, and has been fixed by moving to the different JSON export library.

I'll ping the user on Twitter to let them know, and see if they're ok to verify for themselves with 3.12.0-alpha1. :smile:

**Comment by justinclift** [comment]
Just let them know: https://twitter.com/sqlitebrowser/status/1247070723153133568

Hopefully they're ok to test it, etc. :smile:

**Comment by scottfurry** [comment]
> Let me guess: None of you tested with Version 3.11.2?

No. _Normally_, developers test against the development release if only to head of the piles of noise from users. 3.11.2 made it this far before someone spoke up. Moving on...

**Comment by horst-p-w-neubauer** [comment]
@scottfurry , sorry, my question wasn't ment to be offensive. I should have written "None of us..". I just wanted to reasure, that this was the reason, why non off us - me too - couldn't achive the same behavior in our first tests.

**Comment by scottfurry** [comment]
@horst-p-w-neubauer - no worries. I had "next release" focus and glossed over "last release". One of us thought to try it and was able to reproduce observations.

**Comment by MKleusberg** [comment]
Just a quick explanation of what is happening here: The difference between the last releases and 3.12 stems from the fact that we changed the JSON library we used. It used to be Qt's JSON library which had multiple issues (so I'm not surprised about this one) and are now using Niels Lohmann's JSON library which works a lot better.

Should we close this issue then?

**Comment by justinclift** [comment]
Yep, lets close this. :smile:
