### ISSUE TITLE
Filter clause not working in sql statement

### ISSUE THREAD

**Issue by donvnielsen** [sqlitebrowser/sqlitebrowser#2177]
Details for the issue
--------------------

#### What did you do?
```
select
    WI.Id              WorkItemId
  , WI.name            Description
  , WI.notes           Notes
  , max(vlp.ListValue) filter(where vlp.PropertyName = 'Support Source') as Source
  , max(vlp.ListValue) filter(where vlp.PropertyName = 'Task') as Task
from Grindstone.WorkItems WI
     left join Grindstone.ListValuePropertyValues tasks on tasks.WorkItemId = WI.Id
     left join vwListProperties vLP on vLP.ListValueId = tasks.ListValueId
group by WI.Id, WI.name, WI.notes;

```

A time tracking application named Grindstone communicates the date/time of time slices as "ticks" (why, I don't know.) But I have to convert ticks to unixepoch times so I can display the proper date/times. I then round those times to 15min for time reporting purposes.

#### What did you expect to see?
I expected to see the max propertyname value from all entries having 'Support Source' and 'Task' within the given group.

#### What did you see instead?
An error "Result: near "as": syntax error". The application doesn't appear to support that syntax, even though it runs on the command line.

```
sqlite> select
   ...>     WI.Id              WorkItemId
   ...>   , WI.name            Description
   ...>   , WI.notes           Notes
   ...>   , max(vlp.ListValue) filter(where vlp.PropertyName = 'Support Source' collate nocase) as Source
   ...>   , max(vlp.ListValue) filter(where vlp.PropertyName = 'Task' collate nocase) as Task
   ...> from Grindstone.WorkItems WI
   ...>      left join Grindstone.ListValuePropertyValues tasks on tasks.WorkItemId = WI.Id
   ...>      left join vwListProperties vLP on vLP.ListValueId = tasks.ListValueId
   ...> group by WI.Id, WI.name, WI.notes;
047512c3-a967-42e1-831a-879fb7d8e291|Training|General training||Training
07cf8b53-8c2c-4873-91d0-bfe3b299c880|Reoffer to RLI |Offer to logistics button||Support
3bd2060a-c8a3-4884-9594-90fe9cfe9ef9|Support|||Support
6e1a774d-f02b-452d-8f9c-f349f3263110|Time Tracking|||Time Tracking
9b620f5c-7ee3-4e6b-a26d-f709f38bbe8c|Meetings|General meetings, standups, support, etc.||Meetings
b3b9b08d-8a83-47ee-bca2-77e9622dafdd|Miscellaneous|Just miscellaneous stuff I do||
b8a9da97-76c4-45fb-ba06-9f2630478216|Breaks|Lunch, etc..||Breaks
c85cd025-67f2-4e8f-9c67-2f7d8e9ec690|Code Review|||Code Review
sqlite>

[support_summary.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/4438906/support_summary.txt)

The entirety of the script will run from the command line.

```

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by donvnielsen** [comment]
Just an observation. JetBrains DataGrip also fails to parse the filter structure correctly in this scenario. However, it still shuttles the sql to sqlite for execution, which does return the correct results. I'm guessing DB4S does not attempt execution when it is unable to parse a statement.

**Comment by justinclift** [comment]
Interesting.  Would you be ok to try it with our latest nightly build?  eg:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi

There's been a substantial amount of work on things since the 3.11.2 release, and we're getting ready to make a new release.  So knowing if this bug is present in our development code would be super useful. :smile:

**Comment by donvnielsen** [comment]
WORKED LIKE A CHARM!
![image](https://user-images.githubusercontent.com/16655285/78672870-dadc5b00-78a6-11ea-8574-5b3bfb056f54.png)

I did get the following window on startup, which I ignored:

![image](https://user-images.githubusercontent.com/16655285/78671481-f8102a00-78a4-11ea-9b5e-836c9625fe15.png)

**Comment by justinclift** [comment]
Awesome! :smile:

Not sure what the TLS connection error is caused by.  It's been an occasional, ongoing thing.  If it keeps on happening, there's an option in Preferences to turn off the "Automatic update check" (or similar wording).  Turning that off will stop the error message. :smile:
