### ISSUE TITLE
shortcut Strg + Enter doesn't work in 64-bit version

### ISSUE THREAD

**Issue by horst-p-w-neubauer** [sqlitebrowser/sqlitebrowser#2178]
### Details for the issue
I've downloaded and installed first 64-bit then 32-bit Version today.
Version 3.11.2

Typing Strg+Enter in SQL-Editor starts execution in 32-bit Version but is ignored in 64-bit Version whereas Strg+R works fine in both. Why is that?

running on Win 7, but I've encountered this on other win-systems as well.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows: ( _version:_ 7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
That's a bit unclear.  Which key is "Strg"? :smile:

**Comment by chrisjlocke** [comment]
Strg is German for Ctrl.

**Comment by justinclift** [comment]
Interesting.  Haven't tested this to confirm, but first potential guesses (without checking) are:

* Something to do with the Qt versions for our 32 and 64 bit builds being different?
* Possibly some key combination thing messed up in the German translation (?).  Not sure why it would only be on the 64-bit version though. :frowning:

**Comment by mgrojo** [comment]
> Interesting. Haven't tested this to confirm, but first potential guesses (without checking) are:
> 
>   * Something to do with the Qt versions for our 32 and 64 bit builds being different?
> 

Probably. Or maybe missing translation files. @horst-p-w-neubauer are the general button labels in dialogue translated? How is the Control key translated in standard entries like in standard contextual menus.

>  * Possibly some key combination thing messed up in the German translation (?).  Not sure why it would only be on the 64-bit version though. 😦

What we have seen at other issues is: if you translate the key names, you have to match the translation used by Qt. And Spanish, at least once they've changed the abbreviated translation for the Shift key.

**Comment by horst-p-w-neubauer** [comment]
It's all translated zu German.

**Comment by horst-p-w-neubauer** [comment]
Funny, If I Change the setting to English Ctrl+Enter works fine. Thx for this idea!

**Comment by justinclift** [comment]
No worries @horst-p-w-neubauer.  It probably means there's something with our german translation strings that needs looking at. :smile:

It might be something @FriedrichFroebel has time to investigate at some point. :pray:

**Comment by horst-p-w-neubauer** [comment]
@justinclift, is there a way I can contribute to this project. It seems not to be open for everybody - but maybe I just have some troubles with the security stuff.

**Comment by scottfurry** [comment]
@horst-p-w-neubauer - hop on [gitter](https://gitter.im/sqlitebrowser/sqlitebrowser) and we can find someone to walk you through details/roadblocks. Sounds like your multilingual skills could be most useful.

**Comment by horst-p-w-neubauer** [comment]
thanks I seem to have found a way to fork and create a pull request

**Comment by horst-p-w-neubauer** [comment]
I found the same behavior in 6 other languages 
in these 7 languages Ctrl+Return doesn't work in the sql-tab:
Arabic, Chinese(China), Frensh, German, Italian, Korean, Portuguese

in these 10 languages Ctrl+Return works proper in the sql-tab
Chinese(Taiwan), Czech, 2xEnglish, Japanese, Polish, Russian, Spanish, Turkish, Ukrainian

**Comment by horst-p-w-neubauer** [comment]
this may help locate the issue:
Chinese(China) translates in sqlb-zh.ts to 
    <message>
        <location filename="../MainWindow.ui" line="1497"/>
        <source>Ctrl+Return</source>
        <translation>Ctrl+å›žè½¦</translation>
    </message>
as Chinese(Taiwan) doesn't
    <message>
        <location filename="../MainWindow.ui" line="1497"/>
        <source>Ctrl+Return</source>
        <translation>Ctrl+Return</translation>
    </message>
If checked the complete list. All those who don't work translate the shortcut. the working ones don't transalte.

**Comment by horst-p-w-neubauer** [comment]
the same with other translated shortcuts. 
e.g. Ctrl+P in TableBrowser.ui 
translated in German to Strp+P - doesn't work
There is no difference in Shortcuts comming from .ui files to those, comming fom .cpp file 
if the shortcut gets translated - it doesn't work
e.g. Ctrl+W in MainWindow.cpp
translated in German to Ctrl+P - doesn't work

**Comment by horst-p-w-neubauer** [comment]
Shortcuts working without explicit translation but show translated on UI:
![grafik](https://user-images.githubusercontent.com/28151942/80113081-1f901380-8582-11ea-8779-de2e5ffbfcaf.png)

**Comment by justinclift** [comment]
> I found the same behavior in 6 other languages

Good work! :smile:

We'll need to get this fixed (as much as practical) for the 3.12.0 release.

**Comment by mgrojo** [comment]
I think Qt provides shortcuts for translators, not so they can translate
the keys, which can be done automatically, but to provide different
mnemonics local to the language. This is something that Microsoft usually
do in their products, for example. In practice, it does more harm than
good, because the mnemonic sometimes it is very subtle, even in English,
and that approach forces users to learn different shortcuts for translated
and untranslated programs.

There shouldn't be any problem in translating our keyboard shorcut,
provided that we use the official translations used by Qt, but in practice,
I've seen they've changed their standard for Spanish, and thus broken our
translation, and I guess many others. Moreover, we seem to have some
problem with some Qt or platform versions. My conclusion is: we should
recommend against translating key combinations unless the translator wants
to use a different key combination, which generally, or never?, they don't.
And maybe we should remove those translations. I don't know if there is a
way to avoid adding keyboard shortcuts to translation files. It'd be the
best way forward.

**Comment by horst-p-w-neubauer** [comment]
I was testing the nightly-build: Version 3.12.99 (May  3 2020); Erstellt für x86_64-little_endian-llp64, laufend unter x86_64

In the german version Ctrl+Return works fine now. 
How should we handle the other languages? 
Should I just reset all short-key translations in the other languages?
Are there active translators on every language that could be envolved shortly?

**Comment by mgrojo** [comment]
I wonder, why Qt recommends doing this:
`QKeySequence(tr("Ctrl+P"))`
when it is so easy to break it.

1. Is someone translating the key sequences to other key combination?
1. When not, should we remove `tr()` in all these constructors? Or only remove all the translations?

**Comment by scottfurry** [comment]
If it wasn't for Qt-Creator and such, my vote would be to just put all the key sequences in a header file and just call a namespace global:
```
namespace DB4S {
....
    const SEQ_CTRL_P = QString("Ctrl+P");
    const DISPLAY_CTRL_P = QString(Qt::tr("Ctrl+P"));
...
};
```
... but that's just me musing here.

**Comment by horst-p-w-neubauer** [comment]
I vote for removing the translations. That gives us time to find a solid solution without breaking any timelines or any code.

**Comment by horst-p-w-neubauer** [comment]
Do we know if any of the translations realy take advantage of changing shortcuts instead of translating them what makes them useless?

**Comment by mgrojo** [comment]
> Do we know if any of the translations really take advantage of changing shortcuts instead of translating them what makes them useless?

No, I think nobody is doing that. They are either leaving the text as is or translating key names. Apparently, but I don't know Chinese, Japanese, Polish, etc :wink:

I made a command to get differing source and translation strings. They are these, if I haven't missed anything:
```grep -E '>Ctrl\+|>Alt\+|>Shift\+|>F[1-9]' *.ts | grep --before 1 '<translation>' |grep -o '>.*<' | uniq -c | grep '^  *1 '
      1 >Ctrl+Return<
      1 >Ctrl+Enter<
      1 >Alt+Del<
      1 >Alt+Entf<
      1 >Alt+Del<
      1 >Alt+Entf<
      1 >Ctrl+Space<
      1 >Ctrl+Espacio<
      1 >Ctrl+Shift+C<
      1 >Ctrl+Maj+C<
      1 >Alt+Del<
      1 >Alt+Supp<
      1 >Ctrl+Shift+C<
      1 >Ctrl+Maj+C<
      1 >Ctrl+Shift+O<
      1 >Ctrl+Maj+O<
      1 >Ctrl+Shift+S<
      1 >Ctrl+Maj+S<
      1 >Ctrl+Return<
      1 >Ctrl+Entrée<
      1 >Alt+Del<
      1 >Alt+Supp<
      1 >Ctrl+Space<
      1 >Ctrl+Espace<
      1 >Alt+Del<
      1 >Alt+Canc<
      1 >Ctrl+O<
      1 >Ctrl+A<
      1 >Ctrl+W<
      1 >Ctrl+C<
      1 >Ctrl+Q<
      1 >Ctrl+E<
      1 >Ctrl+Return<
      1 >Ctrl+Invio<
      1 >Alt+Del<
      1 >Alt+Canc<
      1 >Ctrl+Space<
      1 >Ctrl+スペース<
      1 >Ctrl+Return<
      1 >Ctrl+리턴<
      1 >Ctrl+Space<
      1 >Ctrl+Spacja<
      1 >Ctrl+Return<
      1 >Ctrl+ENTER<
      1 >Alt+Del<
      1 >Alt+De<
      1 >Ctrl+Return<
      1 >Ctrl+回车<
```
Assuming that the non-letter cases are just translations, clear cases of remapping seem all from Italian:
```
sqlb_it.ts:        <source>Ctrl+O</source>
sqlb_it.ts:        <translation>Ctrl+A</translation>
sqlb_it.ts:        <source>Ctrl+W</source>
sqlb_it.ts:        <translation>Ctrl+S</translation>
sqlb_it.ts:        <source>Ctrl+S</source>
sqlb_it.ts:        <translation>Ctrl+C</translation>
sqlb_it.ts:        <source>Ctrl+Q</source>
sqlb_it.ts:        <translation>Ctrl+E</translation>
```

**Comment by horst-p-w-neubauer** [comment]
thx for analyzing, @mgrojo 
As there are remappings - I'd vote for clearing .ts files from all non regular key-expressions and resetting them. And explainig it on [wiki/Translations](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations).

**Comment by mgrojo** [comment]
> thx for analyzing, @mgrojo
> As there are remappings - I'd vote for clearing .ts files from all non regular key-expressions and resetting them. And explainig it on [wiki/Translations](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations).

Agreed and made into a pull request #2235.

**Comment by mgrojo** [comment]
@horst-p-w-neubauer, can we close this? The only remaining step is merging it to the 3.12.x branch, but this can be than at the same time including all what we want to release, if they haven't resulted in any issue.

**Comment by justinclift** [comment]
Closing this as I'm pretty sure it's complete. :smile:
