### ISSUE TITLE
[BUG w/SQLite v3.31.1] Bad query bug with Join and On clauses.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2179]
Details for the issue
--------------------
Please update compiled sqlite3.dll to latest on trunk(v3.32.0+) to avoid Join bug with an On clause.
#### What did you do?
[Bug mention on SQLite forum](https://sqlite.org/forum/forumpost/85738a0268)
#### What did you see instead?

Useful extra information
-------------------------
#### What operating system are you using?
- [ ] Windows: ( _version:_10 v1909___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: ___latest nightly as of 200309

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
No worries @sky5walk, this looks do-able.  Should be just a matter of getting that pre-release snapshot, recompressing it with .zip, and dropping it in place of the existing one on the build server.

I'll have a go at that shortly. :smile:

**Comment by justinclift** [comment]
There's a new Win64 build on the nightlies server (same spot as normal), that uses the snapshot from today.  Also has a slightly updated SQLCipher too (v4.3.0, vs the older v4.1.0) as I'd been meaning to update that for a while now too.

@sky5walk Want to give it a go?

**Comment by sky5walk** [comment]
Whew, that worked!
Thanks for the quick fix. 💯

**Comment by justinclift** [comment]
Excellent. :smile:
