### ISSUE TITLE
Open .db file with sql 2.0 1b and nothing loads

### ISSUE THREAD

**Issue by Oldimac10yrsold** [sqlitebrowser/sqlitebrowser#218]
Some background info here, skip over to get to the problem.

-------Before yelling at me, please understand the new 3.x versions of sql arent compatible with my mac version 10.6.8 for some reason. I have no programming experience, but i have used this program before to edit some integers for an iphone app a few years ago, however it isnt working now, even with the same app, the same software, and the same .db file.

Here is why i am confused as to why i cant use the updated 3.0
https://github.com/sqlitebrowser/sqlitebrowser
"OSX 10.6 (Snow Leopard) - 10.10 (Yosemite) are tested and known to work"
yet it doesnt.--------

end BG info

So, i have a file "Cashe.db" that has integers in it that i want to modify, that should be in a table. So i >file>openDatabase>Cashe.db and nothing shows up. it's blank. on the top bar it says as follows "SQLite Database Browser  - /Users/me/Desktop/Cashe/db". I assume this means that the file is open, but not loaded, perhaps due to an encryption? I tried using other .db editors but they dont get me to the table due to one reason or another, again, because of the possible encryption.

**Comment by Z4us** [comment]
You're sure it's a made with a version after 3.6.12 (the standard of 10.6.8) I can imagine 2.* databases can't be handled by sqlitebrowser, not even with sqlite3. I suggest to dump the old db and load it with a version after 3.7.* 

Normally DB4S can handle practically all sqlite3 databases.

I have 10.6.8 and normally use (or convert to) the newest version (now 3.8.8.3) 
If you need help you may send your db to me, though I can't handle version 2.*

**Comment by Oldimac10yrsold** [comment]
Version 3.6.18, as it says from the about dropdown, not sure if that is what you meant by 2.*. I do remember though, i was able to load the database document with no problems and edit in the past.

**Comment by Z4us** [comment]
This issue has 2.0 in the title.

More about release 2 here: http://slackbuilds.org/repository/13.37/system/sqlite2/

It's about 2.8.17_6

Probably I misunderstood the title. When you open your database in Terminal* do you get an error message?

*
Finder > Applications > Utility > Terminal.app

cd  /Users/me/Desktop/Cashe/db 
sqlite3 Cashe.db

**Comment by Z4us** [comment]
Perhaps you used to use SQLitebrowser 
Version 2.0b1 released - 2009-12-10 
If it's really based on SQLite 3.6.18 you may miss some OSX specific features

http://www.sqlite.org/changes.html

**Comment by Z4us** [comment]
You mean SQLitebrowser 2.01b 
with http://www.sqlite.org/changes.html#version_3_6_18 ?

**Comment by Oldimac10yrsold** [comment]
yes, i did mean 2.01b, sorry for the confusion.

I went into terminal and here is what i have

My-iMac:~ Games$ cd /Users/me/Desktop/Cashe/db 
-bash: cd: /Users/me/Desktop/Cashe/db: No such file or directory
Mt-IMac:~ Games$ sqlite3 Cashe.db
SQLite version 3.6.12
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite>

**Comment by justinclift** [comment]
Interesting, that seems to have loaded it ok.  I wonder why our latest code isn't working with it. :frowning: 

Um, how big is that database file?  If it's not too big, are you ok to email it to me or something (justin@postgresql.org)?  I'll see if I can figure out what's wrong with it, and if not, I'll forward it to our main developers for having a look.

**Comment by Oldimac10yrsold** [comment]
I sent the file justin. i have no idea if it is encrypted or not, but i have heard it shows that there is an error instead of showing up blank.

**Comment by rp-** [comment]
the file didn't load, check the output, the directory doesn't even exists:
```-bash: cd: /Users/me/Desktop/Cashe/db: No such file or directory```

if sqlite3 is called with a non existent file, it will just create a new database.

**Comment by justinclift** [comment]
@rp- Yeah, saw that.  Am figuring the only way to be sure is to take a look at it and see what's what. :wink:

@Oldimac10yrsold Weirdly, I didn't receive the email.  It's definitely possible my anti-spam stuff automatically deleted it, so I've turned them off completely for now.  Would you be ok to try sending it again?

In theory, there shouldn't be anything that can stop it from getting through this time. :smile:

**Comment by Oldimac10yrsold** [comment]
@justinclift re-emailed to you.

**Comment by justinclift** [comment]
Yep, got it this time.  It's definitely a SQLite3 database file, and DB4S opened it ok on my system.

Now, we just need to figure out why recent versions of DB4S isn't working on yours.

As a first thought, which version of DB4S have you downloaded to try?  If you're not sure, would you be ok to grab the latest version **without encryption** and try that?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.5.1/sqlitebrowser-3.5.1.dmg

Your Cache.db file isn't encrypted, so you don't need the encryption version. :smile:

If it doesn't work, can you screenshot it, and add the screenshot(s) here?

**Comment by Oldimac10yrsold** [comment]
Good to hear that it isnt encrypted :) 

i believe i downloaded every version and tried to use them, however they "arent supported on this mac"

screenshots are here: 
http://imgur.com/LVc4LFA
http://imgur.com/ZQSqf1O
http://imgur.com/NQYA4sA
http://imgur.com/ESfPiqF

**Comment by Z4us** [comment]
Did you ever changed the database with a version after 3.6.18? In this case you absolutely need to upgrade. Let's hope it's not corrupted.

https://www.sqlite.org/howtocorrupt.html

**Comment by samir-aguiar** [comment]
@Oldimac10yrsold try the following: right-click on sqlitebrowser.app, click "Show package contents". Now go to Contents > MacOS and double click on the sqlitebrowser file (I'm not sure if the path is correct, can't check now). See if the app opens or if not, what message appears.

**Comment by Z4us** [comment]
@samir: On Apple we don't right-click, but ctrl-click

the rest of the info is correct:


--[[z4us|binz--]]
cd sqlitebrowser.app/Contents/MacOS
--[[z4us|MacOS--]]
ls
sqlitebrowser translations
--[[z4us|MacOS--]]

**Comment by samir-aguiar** [comment]
You're right @Z4us, thanks. I have mine customized for so long that I forgot the original behaviour.
The first thing I did after buying a magic mouse was enable right clicking. The same with maximizing windows, couldn't stand they only expanding and not taking all the space. :stuck_out_tongue_winking_eye:

**Comment by justinclift** [comment]
@Oldimac10yrsold Ahhh, I just thought of something.  I kind of suspect your iMac might not be using an Intel processor, which is what our OSX downloads have been made with (so far).

Would you be ok to screenshot your "About this Mac" dialog?  The one that shows the overall system info, from the Apple menu?  For example, this is what mine looks like:

![screen shot 2015-03-09 at 13 07 54](https://cloud.githubusercontent.com/assets/406299/6555383/5947d80e-c65d-11e4-8f96-796508018fa1.png)

**Comment by Oldimac10yrsold** [comment]
@samir-aguiar I went to the MacOS folder and clicked and it opened with this dialogue
MY-iMac:~ me$ /Users/me/Desktop/Storage/SQLite\ Database\ Browser\ 2.0\ b1.app/Contents/MacOS/sqlitebrowser ; exit;

and SQL opened normally.
@justinclift 
im gonna hit 2 birds with 1 stone, and shoe what folder i was in and my mac info

http://imgur.com/Pc4fZVb

**Comment by samir-aguiar** [comment]
@Oldimac10yrsold Sorry, I forgot to mention that this should be done with the lastest version, the one that you say it's not working on your Mac.

**Comment by Oldimac10yrsold** [comment]
@samir-aguiar Here is what it says in terminal

my-iMac:~ me$ /Volumes/src:sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
-bash: /Volumes/src:sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser: Bad CPU type in executable
logout

[Process completed]

**Comment by rp-** [comment]
32 bit OS/CPU?

**Comment by Oldimac10yrsold** [comment]
@rp- i believe so

**Comment by justinclift** [comment]
@Oldimac10yrsold In theory, you should be able to compile this on your Mac and it would work.

I'm just trying to think of an easy way for you to do that, as it's normally done from the command line.  There's probably a GUI way to compile it, but it's not coming to mind. (it's very late here, and I'm very tired, so might be able to remember it tomorrow) :wink:

As a side thought, how often do you need to modify the integers?  There's only a few rows, so I can probably just modify them for you and email back the file (this time).  Not right now though. :smile:

**Comment by Oldimac10yrsold** [comment]
@justinclift I can wait, i dont modify these files often, maybe once a year if i use them to begin with.

**Comment by justinclift** [comment]
@Oldimac10yrsold Is this the model of Mac you're using? :smile:

&nbsp; &nbsp; http://www.everymac.com/systems/apple/imac/specs/imac_cd_2.0_20.html

**Comment by Oldimac10yrsold** [comment]
@justinclift to my knowledge, yes.

**Comment by justinclift** [comment]
@samir-aguiar Any idea how we could compile a 32-bit version of DB4S as a once off?

I don't have access to any 32-bit OSX systems, and the virtualisation stuff I have either won't run OSX or won't present a 32-bit Intel cpu to it. :frowning:

**Comment by samir-aguiar** [comment]
@justinclift I'm not sure, I don't have any 32-bit system either...
I'll do some tests tonight :wink:

**Comment by justinclift** [comment]
@Oldimac10yrsold If we can't get this figured out, you may need to use something like [Navicat for SQLite](http://www.navicat.com/products/navicat-for-sqlite).  Their product page says it supports OSX 10.6, and is a 32-bit/64-bit version.  It's a commercial product though. :frowning: 

Note - we have no association to the Navicat people.  I was just looking at it earlier today for another bug. :wink:

**Comment by Oldimac10yrsold** [comment]
Navicat doesnt work either.

**Comment by justinclift** [comment]
Heh Heh Heh.  This is proving to be a challenge eh? :wink:

**Comment by Oldimac10yrsold** [comment]
Yes sir 
:)

**Comment by justinclift** [comment]
Out of curiosity, do you have Xcode installed on your iMac?

We might be able to write some clear instructions for you to compile things yourself... but I suspect you might not have the software needed to compile it.

**Comment by justinclift** [comment]
@Oldimac10yrsold Try this, and let us know if it works?

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/onceoffs/sqlitebrowser_32bits.dmg

That's from @samir-aguiar, who left an initial 32-bit compile run overnight.  We're hoping it works, but not 100% sure. :wink:

**Comment by Oldimac10yrsold** [comment]
403 forbidden when i clicked the link. Interesting.

**Comment by justinclift** [comment]
Oops, that'll be a problem on my end.  I must have gotten the permissions wrong on the server directory...  gimme a minute. :anguished:

**Comment by justinclift** [comment]
Should be good now.  Sorry about that.  I rarely make that kind of dumb mistake, but it does still happen. :smiling_imp:

**Comment by Oldimac10yrsold** [comment]
Last login: Thu Mar 12 15:43:54 on console
/Volumes/sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
Jim-Collinsworths-iMac:~ Games$ /Volumes/sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
dyld: Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/sqlitebrowser/sqlitebrowser.app/Contents/MacOS/../Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
  Reason: image not found
Trace/BPT trap
logout

[Process completed]

in terminal,thats what it says when i open it.


when opening normally, it gives this error message:

"check with the developer to make sure sqlitebrowser works with this version of macosx. You may need to reinstall the application. Be sure to install any available updates for the application and mac osx".

**Comment by justinclift** [comment]
k.  Next version to try:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/onceoffs/sqlitebrowser_32bit_20150313.dmg

**Comment by Oldimac10yrsold** [comment]
doesnt even open :(

**Comment by samir-aguiar** [comment]
Any output from the console?
Try the following, put sqlitebrowser.app in your downloads folder.
Supposing that the downloads folder is in `/Users/< your username >/Downloads`, open Terminal and run:
`cd ~/Downloads`
Then:
`otool -L sqlitebrowser.app/Contents/MacOS/sqlitebrowser`
And paste the output here, starting from the line that says `sqlitebrowser.app/Contents/MacOS/sqlitebrowser`.

**Comment by Oldimac10yrsold** [comment]
"otool doesnt exist"

so i just right clicked and opened its contents, macos folder, right click >open with terminal:

Last login: Sat Mar 14 22:19:00 on ttys000
/Volumes/src:sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
my-iMac:~ me$ /Volumes/src:sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
Bus error
logout

[Process completed]

**Comment by Z4us** [comment]
If you're sure using the 32-bit version there might be a bug in it.

When I do the same I see a similar message (without 'Bus error')  B4S is launched


Last login: Fri Mar  6 19:53:10 on ttys001
/Users/Shared/ZeaGuiL/binz/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;
localhost:~ <myHome>$ /Users/Shared/ZeaGuiL/binz/sqlitebrowser.app/Contents/MacOS/sqlitebrowser ; exit;

FWIW it's this 64-bit version I believe the buikd of yesterday

Version master_git

Qt Version 4.8.6

SQLCipher Version 3.8.6

BTW: is there a way within the GUI to see which build you're in?

**Comment by justinclift** [comment]
@Z4us Hmmm, not yet.  It's a good idea though.  We should add something to the About dialog to show the git commit id it was compiled with, if it's on master_git.

Just asked [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/222#issuecomment-81000342), as there's already an open issue being worked on for stuff in the Dialog box.

I think I'll ask my work colleagues at Red Hat if someone has a 32-bit OSX box hanging around, preferably with OSX 10.6.  There's a decent chance... :smile:

**Comment by samir-aguiar** [comment]
That error is related to memory issues, as to accessing invalid addresses. That's probably some library incompatibility, but I don't know what. I've compiled Qt with libstdc++, the target as OS 10.6 and the arch as i386. I've also linked a universal build of libsqlite, that contains both 32 and 64-bit instructions.
@Oldimac10yrsold can you try the following?
With the .dmg file mounted, open Terminal and run:
`ulimit -c unlimited`
`/Volumes/src:sqlitebrowser/sqlitebrowser.app/Contents/MacOS/sqlitebrowser`

Then check the folder `/cores/` to see if a core dump file was generated for the process. If there is a file there with the creation date just after you ran DB4S with the command above, can you send it to me?

@justinclift That would be great!

**Comment by Oldimac10yrsold** [comment]
"Bus error (core dumped)"

cant find the core folder. Also, what is DB4S? i just want to check my knowledge.

**Comment by samir-aguiar** [comment]
Hmm I think that folder it's hidden by default.
Run this on Terminal:
`mkdir ~/Downloads/cores`
then
`cp -R /cores/* ~/Downloads/cores`
Then check your Downloads folder, a new `cores` folder should be there with the interesting files. If you could upload them somewhere and send the link it would be great :smiley: 

DB4S is our acronym for DB Browser for SQLite :)

**Comment by Oldimac10yrsold** [comment]
Okay, i have one file in it, how shall i send it to you?

**Comment by Z4us** [comment]
Like Samir said: Upload it somewhere e.g >> https://gist.github.com/
 and post the link here.

**Comment by justinclift** [comment]
Potential way forward.  @CBredesen (colleague at Red Hat) has a suitable OSX box, and we're working on getting the right development bits installed on it. :grin:

Hopefully this works out. :wink:

**Comment by cbredesen** [comment]
OK I got through most of this stuff but I'm now met with this, when trying to `brew install qt`, on the `make` step:

```
make[2]: *** [.obj/release-shared/qtestcase.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [release] Error 2
make: *** [sub-testlib-make_default-ordered] Error 2

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by justinclift** [comment]
@cbredesen No worries.  As a first step, run this to get Homebrew to check it's environment for gotchas:

    $ brew doctor

Ideally, it should come back like this:

    $ brew doctor
    Your system is ready to brew.
    $

Guessing it won't, so we'll need to see what's wrong and address that first.

**Comment by Oldimac10yrsold** [comment]
@Z4us gist caused me a lo of frustration trying to upload the file. any other method?

**Comment by justinclift** [comment]
@Oldimac10yrsold How big is the file?  If it's only a few MB, then maybe email it to me?  I can get it to @samir-aguiar from there. :smile:

**Comment by Oldimac10yrsold** [comment]
the original file is 600 megabytes, the .zip is 101 megabytes.

**Comment by justinclift** [comment]
Hmmm.  That's a bit big for an email.

Do you have an FTP or SFTP program you're comfortable with?  If you do, I can create an account for you to upload the file somewhere. :smile:

Btw - Sorry this is dragging out so long.  It turns out this is more complicated than it seemed... :frowning:

**Comment by samir-aguiar** [comment]
Perhaps upload it to Dropbox, Drive or something of the kind and send us the link? I think it also works :smile:

**Comment by Oldimac10yrsold** [comment]
i can do google drive. just give me an address to send to and ill get it done asap.

**Comment by samir-aguiar** [comment]
Nice, you can send it to saguiar@gmx.de
Thanks :)

**Comment by Oldimac10yrsold** [comment]
sent the share samir :)

**Comment by samir-aguiar** [comment]
Thanks, I was checking and it seems to be a problem with the Qt libraries. I'll build Qt again overnight with some other flags set and we send you another binary tomorrow... Let's see if it works this time :grimacing:

**Comment by justinclift** [comment]
@cbredesen btw ping... just in case. :smile:

**Comment by Oldimac10yrsold** [comment]
Thanks guys :)

**Comment by cbredesen** [comment]
Hey all, sorry about the delay. Built fine once I got XCode installed. I have a .app but not the .dmg ... what would you like me to do?

**Comment by samir-aguiar** [comment]
That's great, @cbredesen!

I was going to send another version but I dug further and I didn't think that would work either. I'm running some tests with Valgrind and Xcode Inspector to see if they can find leaks, but they are not helping much.
It would be great if you could upload it somewhere or send it to @justinclift so he could upload to his server. To build .dmg, Qt comes with a deploy tool. You can run:

`macdeployqt sqlitebrowser.app -dmg -verbose=2`

It will generate the .dmg with the libraries added to the bundle.

Thanks a lot for helping :smile:

**Comment by cbredesen** [comment]
Here you go:

https://dl.dropboxusercontent.com/u/12092928/sqlitebrowser.dmg

**Comment by samir-aguiar** [comment]
Thanks @cbredesen!

@Oldimac10yrsold can you try this version?

**Comment by justinclift** [comment]
That's Fantastic @cbredesen. :grinning: 

Just tried it here on 64-bit OSX 10.9.5 out of curiosity, and it works here too.  Don't really need it myself, but it's interesting to note. :wink:

**Comment by Oldimac10yrsold** [comment]
the good news, it works! the file loads and everything is cool.

the bad news is that i cant seem to find the data fields i need to edit :)

**Comment by justinclift** [comment]
@Oldimac10yrsold FINALLY! :dancers: Awesome that it works. :grinning:  Hopefully you figure out the data fields you need at some point... :wink:

@cbredesen Thank you, you're a legend. :smile:

Team - we should probably add this specific .dmg file to our Releases page, so anyone else using a 32-bit Mac can also benefit.  It'd be interesting to see the download #'s for it over time too, in case it's not just a very small #.

Not sure how to make it not appear right at the top of our releases list though which probably isn't the right place for it (could confuse people?)... :confused:  Ideas welcome. :smile:
