### ISSUE TITLE
Crash when -t option specifies missing table

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2180]
Details for the issue
--------------------

#### What did you do?
Start the app with the -t option followed by the name of a table that does not exist (e.g., due to typo).

#### What did you expect to see?
Simple error and abort, or start but without going to the specified table.

#### What did you see instead?
Crash!!!

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ 7___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?
Downloaded on 2020-04-07 from https://nightlies.sqlitebrowser.org/latest
DB.Browser.for.SQLite-win32.zip (MD5: 7f4b3a42424815d40f5c72154f81a616)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good catch @tonypdmtr, sounds like a simple bug that should be fairly easy to fix. :smile:

**Comment by MKleusberg** [comment]
Thanks, @tonypdmtr! Can you check tomorrow's nightly build and see if it's fixing the crash?

**Comment by tonypdmtr** [comment]
I tried this one `DB.Browser.for.SQLite-win32.zip                    07-May-2020 01:25            17365666` and it works with a crash.

**Comment by justinclift** [comment]
Awesome, good work @MKleusberg. :smile:
