### ISSUE TITLE
The latest nightly crashes on open on macOS

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#2181]
Details for the issue
--------------------

#### What did you do?

I downloaded the [latest nightly](https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20200408.dmg).

#### What did you see instead?

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5748627/78771209-7a2d4b00-7998-11ea-9610-3a6331c7b4d7.png">

<details>

```
Process:               DB Browser for SQLite [64817]
Path:                  /Applications/DB Browser for SQLite 2020.04.08.app/Contents/MacOS/DB Browser for SQLite
Identifier:            net.sourceforge.sqlitebrowser
Version:               3.11.99 (3.11.99)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DB Browser for SQLite [64817]
User ID:               501

Date/Time:             2020-04-08 12:50:20.560 +0300
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        9A5D9F3E-FC62-8A38-5590-3CB6F10C0433

Sleep/Wake UUID:       22D98FA3-3078-46E5-B2DF-816144C1D3CB

Time Awake Since Boot: 47000 seconds
Time Since Wake:       7700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/libsqlcipher.0.dylib
  Reason: image not found

Binary Images:
       0x10dddd000 -        0x10e31cfff +net.sourceforge.sqlitebrowser (3.11.99 - 3.11.99) <1D04F808-D331-3F15-BE46-02DB915B8620> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/MacOS/DB Browser for SQLite
       0x10e44b000 -        0x10e521ff3 +libsqlcipher.0.dylib (0) <829B035D-4795-32F4-BEEB-50DFA4922082> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/libsqlcipher.0.dylib
       0x10e53b000 -        0x10e565ff7 +org.qt-project.QtPrintSupport (5.11 - 5.11.3) <559ABC7F-F890-393C-B37E-E47FF49291D9> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10e590000 -        0x10e9c3ff3 +org.qt-project.QtWidgets (5.11 - 5.11.3) <A7AEAE0D-EF52-3183-9BCA-8A9556B0634A> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10eb3c000 -        0x10ef55fff +org.qt-project.QtGui (5.11 - 5.11.3) <09BF520B-88B0-3401-8C6A-08D9510C6351> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10f065000 -        0x10f099ffb +org.qt-project.QtOpenGL (5.11 - 5.11.3) <6E28F9C0-33A1-32FD-AAB2-9CB065303623> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL
       0x10f0bf000 -        0x10f0c7ffb +org.qt-project.QtMacExtras (5.11 - 5.11.3) <3AAB6309-2D96-3C06-8F55-1109F932DA3A> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
       0x10f0d3000 -        0x10f0d7ffb +org.qt-project.QtConcurrent (5.11 - 5.11.3) <783A5203-2025-32E9-867B-F3B2695E7C7B> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x10f0e0000 -        0x10f109fff +org.qt-project.QtXml (5.11 - 5.11.3) <575D6197-EC9E-3025-B0DC-0F43D756EF22> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtXml.framework/Versions/5/QtXml
       0x10f18c000 -        0x10f21ccb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld
       0x10f290000 -        0x10f77bff3 +org.qt-project.QtCore (5.11 - 5.11.3) <02CECF89-9D8B-3CAD-A3D9-0618E34152BF> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10f847000 -        0x10f94fff3 +org.qt-project.QtNetwork (5.11 - 5.11.3) <C0EEC468-C3F3-35FE-B6D2-FF6F097B1C50> /Applications/DB Browser for SQLite 2020.04.08.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
    0x7fff2f05e000 -     0x7fff2f062ffb  com.apple.agl (3.3.3 - AGL-3.3.3) <93797B81-445E-3D1B-9C0D-004A4E398F99> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff32246000 -     0x7fff32246fff  com.apple.Carbon (160 - 162) <916D6D9E-3FE9-355C-913B-B44CAF35146D> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff35a2f000 -     0x7fff35a35fff  com.apple.DiskArbitration (2.7 - 2.7) <5BE0B036-DEAB-3191-8D44-B489F4D39EE1> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff364a7000 -     0x7fff3654affb  com.apple.framework.IOKit (2.0.2 - 1726.80.1) <B63FE840-8E32-3429-A95D-AB466FE62104> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3df60000 -     0x7fff3df6fff7  com.apple.opengl (17.10.22 - 17.10.22) <9530427D-0AE4-3F7D-B036-73FD32DDAD77> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff67bf5000 -     0x7fff67bf6ff3  libSystem.B.dylib (1281) <A2C26908-8802-3CA7-8B74-ED4A74AA152C> /usr/lib/libSystem.B.dylib
    0x7fff67edb000 -     0x7fff67f2eff7  libc++.1.dylib (800.7) <1D0CB627-8A78-329F-A679-1B5248FF4C59> /usr/lib/libc++.1.dylib
    0x7fff6a126000 -     0x7fff6a138ffb  libz.1.dylib (76) <52250917-039C-3B46-8011-497FEACF3550> /usr/lib/libz.1.dylib

Model: MacBookPro15,3, BootROM 1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0), 8 processors, 8-Core Intel Core i9, 2.3 GHz, 32 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonProVega20Item, Radeon Pro Vega 20, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2400 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2400 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Dec  6 2019 11:17:27 version 9.112.4.0.32.5.41 FWID 01-ac611e8a
Bluetooth: Version 7.0.3f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: USB3.0 Card Reader
USB Device: 4-Port USB 3.0 Hub
USB Device: Elements 25A2
USB Device: USB 10/100/1000 LAN
USB Device: USB 3.1 Bus
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: HyperX Cloud Flight Wireless Headset
USB Device: USB2.0 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: Logitech Speaker Lapdesk N700
USB Device: USB 2.0 BILLBOARD
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.3
```

</details>

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ _Catalina 10.15.3 (19D76)_ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: _2020.04.08_

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch. :frowning:

Thanks for pointing it out @revolter, I'll take a look shortly.

**Comment by revolter** [comment]
The build from [`22-Nov-2019 00:34`](https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20191122.dmg) is the first one that introduced it.

**Comment by revolter** [comment]
Maybe that's when openssl 1.1 was released? Anyways, it should not link to a specific version of it:

```sh
> ls -al /usr/local/opt/openssl/lib/
total 14496
drwxr-xr-x  10 revolt  staff      320 Mar 31 15:17 .
drwxr-xr-x  15 revolt  staff      480 Apr  8 13:00 ..
drwxr-xr-x   4 revolt  staff      128 Mar 31 15:17 engines-1.1
-r--r--r--   1 revolt  staff  2262368 Apr  5 14:23 libcrypto.1.1.dylib
-r--r--r--   1 revolt  staff  3936872 Mar 31 15:17 libcrypto.a
lrwxr-xr-x   1 revolt  staff       19 Mar 31 15:17 libcrypto.dylib -> libcrypto.1.1.dylib
-r--r--r--   1 revolt  staff   490564 Apr  5 14:23 libssl.1.1.dylib
-r--r--r--   1 revolt  staff   724096 Mar 31 15:17 libssl.a
lrwxr-xr-x   1 revolt  staff       16 Mar 31 15:17 libssl.dylib -> libssl.1.1.dylib
drwxr-xr-x   5 revolt  staff      160 Apr  5 14:23 pkgconfig
```

Context:
> Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib

It should link to the `/usr/local/opt/openssl/lib/libcrypto.dylib` symlink.

**Comment by justinclift** [comment]
Interesting.  Wonder if this is a Qt problem, as previous attempts of trying to use OpenSSL 1.1 failed due to Qt (at the time) being built with OpenSSL 1.1.

It might be as simple as just needing to update our Qt installation.  Will check. :smile:

**Comment by justinclift** [comment]
Aha:

https://www.qt.io/blog/2019/06/17/qt-5-12-4-released-support-openssl-1-1-1

Our macOS build box currently has Qt 5.11.3, and 5.12.1 on it.  Will experiment a bit...

**Comment by revolter** [comment]
Well, regardless the version that we use, as I said, I don't think that we should link to an explicit version, because it will break for people having a different version installed. Better yet, we could bundle openssl into the app?

**Comment by justinclift** [comment]
From memory, the macdeployqt tool provided by Qt takes care of bundling/linking dependencies.

At least, I'm not seeing anything in our build script that explicitly does any linking:

https://github.com/sqlitebrowser/sqlitebrowser/blob/3d15ba46d1f4b7b3e85d9a0390f7af42f868c016/installer/macos/build_sqlitebrowser_nightly.sh

**Comment by justinclift** [comment]
I'm completely re-installing Qt on the mac build VM now.  (Bizarrely, the maintenance app refused to proceed without being provided an account user/pw combo.  No friggin way I'm giving account info just for a version check.)

**Comment by justinclift** [comment]
WTF.  The Qt installer is now **requiring** a Qt account, just to download the OSS version.

Sorry, but that's not happening.  We will no longer be providing macOS nightly builds until a workaround for this Qt bullshit is found.

**Comment by chrisjlocke** [comment]
Is it just an email address they need?  Can you sign up for a Qt account with a GMail disposable address?

**Comment by revolter** [comment]
Even if you install it with `brew`?

**Comment by revolter** [comment]
http://bugmenot.com/view/qt.io

**Comment by justinclift** [comment]
Oh, I have a Qt account.  I'm just **not** going to use it for a simple download of **Open Source** software.  Which has never, ever been needed before.

The Qt company have been heading on a trajectory of becoming more and more anti-OSS over the years.  This has crossed the line and is taking the piss now.

**Comment by justinclift** [comment]
It looks like they still have "offline installers" available.  eg:

http://ftp.yz.yamagata-u.ac.jp/pub/qtproject/archive/qt/5.14/5.14.2/qt-opensource-mac-x64-5.14.2.dmg <-- random mirror

Going to try that.  If that requires a login too, that's the end of macOS builds of DB4S from me.

**Comment by justinclift** [comment]
Wow, downloads from pretty much any of the Qt mirrors is only going at about 60-70kB/s.  It's going to take 9 hours (!) to download that offline installer. :frowning:

**Comment by justinclift** [comment]
Looks like they've pulled this shit before too:

https://www.qt.io/blog/2015/05/06/changing-qt-account-to-be-optional-in-the-online-installer

**Comment by revolter** [comment]
> Which has never, ever been needed before.

I've always logged into Qt Creator when installing it.

**Comment by justinclift** [comment]
Interesting.  I haven't, and I'm not about to start. :wink:

**Comment by revolter** [comment]
> https://www.qt.io/blog/2015/05/06/changing-qt-account-to-be-optional-in-the-online-installer

So, isn't it optional now?

**Comment by justinclift** [comment]
Nope.  It now refuses to proceed without being provided ~user tracking information~ account user/pw combo.

If I was in the EU still, I'd literally be filling out a GDPR violation form on the Info Commission people about this. Except well, the UK left the EU and I left the UK. :wink:

**Comment by revolter** [comment]
Then move here 😃

**Comment by justinclift** [comment]
Yeah, at some point I may do so.  Today isn't that day though. :wink:

**Comment by justinclift** [comment]
From IRC conversation just now:

```
13:39 < JustinClift> Quick question - it seems like the Qt Online Installer for the OSS version now *requires* account information in order 
                     to download even just OSS Qt.  Is that on purpose, or an accidental mistake?
13:44 < JustinClift> Asking because this is blocking some OSS projects from using Qt, and because this move has previously been performed 
                     then recognised as extremely OSS-unfriendly so rolled back. eg: 
                     https://www.qt.io/blog/2015/05/06/changing-qt-account-to-be-optional-in-the-online-installer
14:02 < JustinClift> Not sure if this is what the "accept Open Source obligations" piece here is meaning: 
                     https://www.qt.io/blog/qt-online-installer-3.2.1-released
14:02 < JustinClift> Guessing "yes", as all of the previous installers (that didn't require an account, just for OSS downloads) have been 
                     removed.
14:08 < anp_> it's intentional
14:08 < JustinClift> Ugh.
14:08 < JustinClift> Why the change of heart?
14:10 < JustinClift> Saying that because it ends my use of Qt.
14:13 < JustinClift> It also seems to be directly in violation of the GDPR.
14:13 < anp_> https://lists.qt-project.org/pipermail/development/2020-January/038316.html
14:14 -!- pekkari [~pekkari@uk.sesame.canonical.com] has quit [Quit: Konversation terminated!]
14:14 < JustinClift> Oh wow.
14:14 < JustinClift> "In addition, we want open source users to contribute to Qt or the Qt ecosystem."
14:15 < JustinClift> Well, I just unsubscribed from the Qt mailing list for localisation, and there's zero chance I'm going to be helping out 
                     the Qt project from this point forwards.
14:15 < JustinClift> I *was* a contributor to Qt.  That's now ended.
14:17 < JustinClift> Hopefully you'll reverse this, as it's effectively stopped us (DB Browser for SQLite) project from releasing any new 
                     builds.
14:17 < anp_> it's not my call. in fact, I don't think any of the decision makers reads here,
14:18 < JustinClift> No worries.  Guessing the decision makers won't care anyway. ;)
14:19 < JustinClift> Hopefully you'll all have alternatives for accessing SQLite, if you use it. :)
```

Looks like I'm done.  Someone else can provide builds going forward.

**Comment by sky5walk** [comment]
I never understood the choice of QT?
I realize it is a rich environment, but it is also profit driven at its core.
Why not choose GTK?

**Comment by justinclift** [comment]
Heh Heh Heh

GTK is a complete and utter shit show for anything that's not expected to only run directly on Linux. :frowning: 

Unfortunately, that's not understating things either.  On a technical level, Qt could be considered (say) 8/10 for cross platform completeness, documentation for at least 95% of stuff (not just trivial examples), and fairly good localisation.  GTK would probably be about 2.5/10 (absolute max) for cross platform completeness, documentation (nothing at all for complex examples), etc.

They're not in the same ballpark. :frowning:

Going to hit the sack now, but the offline installer has finished downloading.  Will experiment tomorrow.

If that doesn't work, it might be feasible to build Qt from source instead.  We've had that on our ToDo list for a while for investigation anyway, so perhaps this will cause that to get done. :man_shrugging:

**Comment by revolter** [comment]
I think that building from source is the best way to go.

**Comment by scottfurry** [comment]
This doesn't surprise me. Tech Companies have been pushing more and more to "who is using our stuff". Slurping up user details. Developers become a "commodity". How to tick people off quickly...

I agree about GTK. Gong Show. Their agile method has done nothing but reek havoc on the Linux ecosystem. I do not have numbers but I've seen more and more useful programs become abandoned-ware because developers didn't/couldn't/wouldn't keep up with the rapid, capricious, arbitrary breakage of api changes.

The QT sources can be grabbed from a download URL (PM me for details). This is how other distributions grab their implementations. The "installer" was a convenience for people who didn't want to deal with the vulgarities of packaging. FWIW - Homebrew offers a qt5 cask (https://formulae.brew.sh/formula/qt#default).

**Comment by justinclift** [comment]
Yeah, we used to use the Qt5 version that came with brew.  But moved away from it a few years ago, for some reason I don't remember now.

Can check it out again, though I suspect we'll just be rediscovering why we moved from the brew version in the first place. :smile:

**Comment by justinclift** [comment]
Co-incidentally, from today: https://www.phoronix.com/scan.php?page=news_item&px=Qt-Might-Restrict-New-Releases

**Comment by justinclift** [comment]
Even KDAB (a well known KDE/Qt dev company) seems to think the move by the official Qt company is crap, and are willing to support an alternative development ecosystem:

https://mail.kde.org/pipermail/kde-community/2020q2/006101.html

**Comment by justinclift** [comment]
Been upgrading the macOS VM today (eg new macOS point release).

The OpenSSL thing might not just be Qt, it could also be the fixed-point-in-time SQLite and SQLCipher builds we've been using.  eg not the standard brew ones, but instead ones with our own specific compile-time options.

I'll update those probably tomorrow, and likely experiment with the offline Qt installers too.  We should be able to figure out some workable approach from there. :smile:

**Comment by justinclift** [comment]
@MKleusberg @mgrojo @scottfurry Have you guys seen [CopperSpice](https://www.copperspice.com) before?

If it all goes south with standard Qt, that might be a way forward.

**Comment by sky5walk** [comment]
GUI list
https://www.reddit.com/r/cpp/comments/babfl5/a_pretty_big_list_of_c_gui_libraries/

**Comment by justinclift** [comment]
@revolter In theory, these should work ok now:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite.dmg
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

They're using OpenSSL 1.1 (from Homebrew), Qt 5.12.8 (LTS release), and latest releases of both SQLite (3.31.1) and SQLCipher (4.3.0).

Tested both super quickly on the Mojave build VM itself, where they both opened the GUI correctly.  It'd be useful to see if they work on a different system, where the needed dependency libraries likely aren't also installed.  eg "Did the library bundling work properly?" :smile:

**Comment by revolter** [comment]
It works, but I do have OpenSSL 1.1 installed, so I can't know if bundling worked properly or not. So I'll close this, at least for now, thanks a lot!

**Comment by justinclift** [comment]
You're welcome @revolter.  Thanks for reporting it.  We needed to get this stuff updated about now for the next release anyway. :smile:

**Comment by mgrojo** [comment]
> @MKleusberg @mgrojo @scottfurry Have you guys seen [CopperSpice](https://www.copperspice.com) before?
> 
> If it all goes south with standard Qt, that might be a way forward.

This is the first time I've heard about it. It is interesting, but it would be a risky movement for us: probably difficult to port and less user base.

**Comment by scottfurry** [comment]
> > @MKleusberg @mgrojo @scottfurry Have you guys seen [CopperSpice](https://www.copperspice.com) before?
> > If it all goes south with standard Qt, that might be a way forward.
> 
> This is the first time I've heard about it. It is interesting, but it would be a risky movement for us: probably difficult to port and less user base.

I played with it. Basic premise of the project is to compile Qt w/o the moc compilation process that goes on under the hood in all Qt code. (Analogous to what wxWidgets does although I'm not sure if they go the same design route w/ macros the way wxW does).

I've tried to get their "kitchen sink" (example project of all controls) compiled without success. Development seems laggy and improvements come in fits and bursts. However, it's been a few months since I last looked in on the project.

**Comment by scottfurry** [comment]
> The OpenSSL thing might not just be Qt, it could also be the fixed-point-in-time SQLite and SQLCipher builds we've been using. eg not the standard brew ones, but instead ones with our own specific compile-time options.

There's another candidate for automation - updating the internal libraries. We may want to "untangle" that confusion and to always build internal libraries( i.e. production app) against the latest available.

**Comment by justinclift** [comment]
Yeah.  There's a tonne of opportunities for automating stuff around. :smile:
