### ISSUE TITLE
where are the Hotkeys gone ? 

### ISSUE THREAD

**Issue by Sirais** [sqlitebrowser/sqlitebrowser#2186]
til today i uses an older version of SQlitebrowser wich had hotkeys for menu stuff
like Ctrl-w for close DB.
where are those Hotkeys gone ?

**Comment by justinclift** [comment]
Those should still be working.

We have seen some hotkeys go wrong though in the past, when a translation string doesn't use the "correct" hotkey name.

Wondering if that's the problem here.  Do you have the application set for using a non-English language?

**Comment by Sirais** [comment]
Yes, im using a german version.

**Comment by justinclift** [comment]
Which operating system are you using?

If it's Windows or macOS, it's probably worth try the very latest development build (created yesterday) from here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

The translations were updated a few weeks ago, in preparation for our next major release.  The nightly builds use those translations too, and if it's going to work anywhere, it'll be in those. :smile:

**Comment by Sirais** [comment]
Using Windows 10. 
checking yesterdays release from the site you provided

**Comment by Sirais** [comment]
Thanks. that versione has Hotkeys again !

**Comment by justinclift** [comment]
Awesome! :smile:
