### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by pshem** [sqlitebrowser/sqlitebrowser#2187]
Details for the issue
--------------------

#### What did you do?
I opened a database. I'm including a dataless version of the database as it also triggers the warning messages and should hopefully aid in debugging.
[backup.db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/4487021/backup.db.zip)

#### What did you expect to see?
I didn't expect to see errors in the terminal

#### What did you see instead?
```bash
$ sqlitebrowser --read-only ~/z/source/backup.db 
Sqlite parse error: line 1:47: unexpected token: thread_id(CREATE VIRTUAL TABLE sms_fts USING fts5(body, thread_id UNINDEXED, content=sms, content_rowid=_id))
Sqlite parse error: line 1:47: unexpected token: thread_id(CREATE VIRTUAL TABLE mms_fts USING fts5(body, thread_id UNINDEXED, content=mms, content_rowid=_id))
```

I'm not sure whether the problematic token is `fts5` or not. The 47th character is the `t` in `fts5`. Do you think loading the fts5 extension would help? I've tried to find out whether Ubuntu builds `sqlitebrowser` with fts5, but with no luck. Searching the ![build log](https://launchpadlibrarian.net/434964113/buildlog_ubuntu-eoan-amd64.sqlitebrowser_3.11.2-1_BUILDING.txt.gz) for fts5 found nothing.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( distro: Kubuntu 19.10 )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

My issue looks similar to #80 and #917, except the problematic token appears to be a space, or the entire expression.

**Comment by MKleusberg** [comment]
This is a problem in our SQL parser. We have rewritten the entire parser in the meantime but it still has the same issue :innocent: So I'm going to look at the new parser only. The problem there seems to be the ```UNINDEXED``` keyword:
```
1.57-65: syntax error, unexpected identifier, expecting ) or ","
Sqlite parse error: CREATE VIRTUAL TABLE sms_fts USING fts5(body, thread_id UNINDEXED, content=sms, content_rowid=_id)
```

I have just added a workaround for this. So the parser still fails and the error messages still appear (which is good as it reminds us to fix this in the parser at some point) but a workaround is now applied which should solve the problem for you. Are you able to compile DB4S or use our PPA for testing the fix?

**Comment by MKleusberg** [comment]
Did you have a chance to test this yet? :smile:

**Comment by pshem** [comment]
Sorry, I unfortunately don't have access to that dataset anymore

**Comment by MKleusberg** [comment]
No worries :smile:
