### ISSUE TITLE
Filter should be deactivated when a table is empty

### ISSUE THREAD

**Issue by skarmoutsosv** [sqlitebrowser/sqlitebrowser#2188]
Describe the new feature
--------------------------
At Browse Data tab, filter should be deactivated when a table is empty (no records).
There is frustration for a user trying to add the first record of a table.
The first action will often be to click on one of the filter textboxes instead of the 'New Record' button.

Additional info
---------------
#### Is your feature request related to an issue? Please include the issue number.
No

#### Do you have a screenshot? Please add screenshots to help explain your idea.
I don't have any screenshot to support my idea but there is a video where you can see clearly the problem.
Please watch 7:40-9:00 @ http://www.youtube.com/watch?v=plpLzZKID6s&t=7m40s
where a java professor tries to create a record in an empty table but he ends up with two records; with the first one to be an empty record. The voice is in Greek but the image speaks by it self.

**Comment by justinclift** [comment]
Yep, agree.  Good idea, we should do that. :smile:

**Comment by justinclift** [comment]
@MKleusberg @mgrojo @scottfurry This sounds like a simple tweak.  Something we could get into the 3.12.x series?

**Comment by scottfurry** [comment]
I can sort of see this. The filter controls are already disabled without an open db.
If switching to the "Browse Data" tab, enabling the controls/actions may be done depending on the value of the table name drop-down list. Psuedo code/sqlite stmt:
```
// filters -> ref to filter controls
//      setEnabled is a _std_(IIRC) public function to control QWidget
// sql -> ref to current open'd sqlite db
//      exec - place holder for exec statement function
// 'SELECT...' - sqlite3 statement to query 'table' for its current record count
filters.setEnabled( sql.exec('SELECT COUNT() from table;') );
```
In theory this should work.

**Comment by scottfurry** [comment]
Even with a 'dummy ' table that has no records, the sql statement above returns a '0' value (not a null value as I feared).

**Comment by justinclift** [comment]
From memory, we already have the # of records in the table, as that's displayed in the counter on the bottom left.  We can probably just do a conditional thing based on the number there. :smile:

**Comment by scottfurry** [comment]
count != 0 -> enable filter
That works.
Personally, I'm leery of diving into this as there is quite a bit of "stuff" in the qt creator files.

**Comment by justinclift** [comment]
> Personally, I'm leery of diving into this as there is quite a bit of "stuff" in the qt creator files.

Yeah, probably a safer approach. :grinning:

**Comment by justinclift** [comment]
@skarmoutsosv This should be fixed in the next nightly build, thanks to @mgrojo. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Would you be ok to try it (tomorrow), and let us know if the change works well?

**Comment by chrisjlocke** [comment]
@mgrojo - I assume as they are 'invisible' they are still there - unsure if this is a biggie, but if you move the mouse where they would be, the column headers still get selected.

https://youtu.be/nYqkbr3CALE

Don't know if the heights can be reduced to remove the mouse region, or if its only a Windows thing?  I'm sure 99.99% of people won't know/care about this, but ... well, .... thought I'd let you know.  Kind of looks better without the filter row (I've been guilty of entering values in that row thinking its a new record!) but also naked without it!

**Comment by mgrojo** [comment]
In theory, invisible means for Qt that the GUI has to behave as if the widget weren't there. I don't know if that highlighting is a bug in Qt or the undesired consequence of some of the adjustments we do in the table header, but I'll take a look.

**Comment by mgrojo** [comment]
@chrisjlocke I've removed the filters instead of hiding them. Now the visual glitch should disappear. At least, a similar issue with the mouse pointer for resizing columns, which I noticed under Linux, is solved now.

**Comment by mgrojo** [comment]
ping @chrisjlocke :smiley:

**Comment by chrisjlocke** [comment]
Apologies - yes, can confirm this is now good!  Thanks for the quick fix! 👍
