### ISSUE TITLE
Export of table to CSV from database table doesn't align columns and rows correctly

### ISSUE THREAD

**Issue by atoregozh** [sqlitebrowser/sqlitebrowser#219]
Dear contributors, I'm reporting an issue with sqlitebrowser related to exporting table from database. When I view the table from sqlitebrowser, all the alignments are in place, but when I try to export the table to as a csv, the rows and columns are get misaligned. I'm using sqlitebrowser for mac. I updated the install to the latest "night" install from March 8. Input file: the database is "example.db" within http://web.mit.edu/aizhan/www/twitter_api_workshop/docs/ the table name within the database is called "result"

**Comment by justinclift** [comment]
When you say "misaligned", would you be ok to screenshot it and add it here?  (dragging and dropping images into these comment fields works)

It's kind of hard to visualise the problem without a screenshot.  Not impossible... but a screenshot would really help. :smile:

**Comment by Z4us** [comment]
In the same directory there is a file 'example.sqlite'.

**Comment by justinclift** [comment]
@Z4us Thanks.  Looking now... incredibly slow web server though (27KB/s). :frowning:

**Comment by justinclift** [comment]
@Z4us They're both SQLite database files.

@atoregozh I've downloaded example.db and exported the result table to a .csv file.  The file is hugely wide though, so can't be sensibly viewed in my OSX Terminal window.  How are you viewing it? (a screenshot really would be helpful btw :smile:)

**Comment by atoregozh** [comment]
@justinclift  it is just my Uni uses a bit slow servers, hence is a lag :(

I put 2 files: csv_screenshot.png and sqlitebrowser_screenshot.png. You can see misalignment there. I used excel to view the csv file.

**Comment by samir-aguiar** [comment]
@atoregozh can you try the nightly build tomorrow to see if the issue is fixed? The problem was that some of the values end with the CR character ('\r'), which was not escaped when exporting. Because we now accept it as a line ending character, I've changed the code to also escape them.

**Comment by atoregozh** [comment]
@samir-aguiar sure will do. Thanks for your help in many ways

**Comment by justinclift** [comment]
Awesome @samir-aguiar. :smile:

**Comment by atoregozh** [comment]
Hi @samir-aguiar! I tested the last build and it works perfectly! Thank you so much for a quick fix :+1:

**Comment by justinclift** [comment]
Excellent.  Thanks for letting us know @atoregozh. :smile:
