### ISSUE TITLE
SQLite does not work on my Laptop

### ISSUE THREAD

**Issue by Hilary-Prog** [sqlitebrowser/sqlitebrowser#2194]
Details for the issue
--------------------

#### What did you do?
I tried to run SQLite on my computer.

#### What did you expect to see?
SQLite Browser

#### What did you see instead?
System Error"
"The program can't start because api-ms-crt-runtime-|1-1-0.dll is missing from your computer. Try reintstalling the program to fix this problem."

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ x] Windows: ( 7_version:_64-bit 6.1, Build 7601)
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ x] Other: __3.12._

#### Did you also

- [ x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hi @Hilary-Prog, which one of the downloads did you grab?  eg which exact file? :smile:

Asking because I can kind of imagine a scenario where the .zip download might not work, but if you grabbed the .msi installer that's more puzzling.  Regardless, we'll try and figure it out. :smile:

**Comment by Hilary-Prog** [comment]
Thanks.
I tried both (in fact most of the versions available). I have not even seen
this error before.

**Comment by justinclift** [comment]
That same **exact** error message happened with all of them?

**Comment by Hilary-Prog** [comment]
Yes, the same exact error message.

**Comment by justinclift** [comment]
Interesting.  With the .zip file version, are you fully extracting the contents of the .zip file first before running it?  (eg with [7zip](https://www.7-zip.org) or similar)

If you are, then I'm not really sure where to start for investigating this.  Um... maybe @chrisjlocke or @karim have ideas? :smile:

**Comment by scottfurry** [comment]
@justinclift - my $0.02 is to double check extraction is being done properly and what is extracted matches what _should_ be present (i.e. make sure the created archive is being packaged properly with all needed).

With `zip`, IIRC, the `-v` switch will cause verbose output.
With `7zip` - need the `-bb` switch (see [here](https://sevenzip.osdn.jp/chm/cmdline/switches/bb.htm) )

**Comment by justinclift** [comment]
Ahhh yeah.  Good thinking. :smile:

**Comment by scottfurry** [comment]
Also... what gets lost in GUI applications... start it from the cmd line. Then error messages will get spat out to the console. Missing libraries, unmet conditions, missing files, etc (aka _usual suspects_). ;)

**Comment by chrisjlocke** [comment]
Is that the *exact* error?
There is a api-ms-win-crt-runtime-|1-1-0.dll - not api-ms-crt-runtime-|1-1-0.dll.

**Comment by chrisjlocke** [comment]
Another thing to try is the 'portable' copy of DB4S alpha.  
https://we.tl/t-0GCSsE1qm1

This link dies in two days.  
I've tried this on XP and it ran, so 'assume' its OK on Win 7.  Can't see why it shouldn't.

**Comment by Hilary-Prog** [comment]
Yes, that is the exact error.

**Comment by chrisjlocke** [comment]
Is this a real Windows 7 or a virtual? As we've not had any reports of this prior, I'd hazard a guess this is machine specific - a dodgy .NET install?
What version(s) of .NET are installed? Is the machine generally OK? If you replied back, "No, Word always crashes too, and it blue screens every half hour" then the machine itself needs a cuddle.
Also, the file could be corrupt. Have you run a chkdsk* on the drive? I've had it before where the operating system has been coughing and spluttering, to only find the disk is goo.

**Comment by Hilary-Prog** [comment]
Thank you. DB4S worked.The portable one does not even need shortcuts or
installation.


Thanks a lot, Chris.
Thank you, Justin and Scott.

**Comment by chrisjlocke** [comment]
So the portable is just the .zip version extracted and wrapped up again.  I'm guessing on a corrupted install, which would be fixed by a chkdsk.
Just a 'heads up', depending on whether its a real disk or an SSD, that your disk could be failing.
Glad you got it working though.

**Comment by Hilary-Prog** [comment]
It is an old machine but no blue screen and hard drive seems fine. (for
now). I have not checked anything on .NET. Do I have to re-install .NET?

**Comment by scottfurry** [comment]
@Hilary-Prog - Just throwing this out... You probably do have .NET installed. It may need an update (or updates are not completed). I'll also echo and emphasize @chrisjlocke observation - check your hard drive.

**Comment by chrisjlocke** [comment]
> Do I have to re-install .NET?

It wouldn't do any harm.  I'd suggest going into Control Panel and removing any installations of .NET first, then installing v4.8 (the latest) https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by Hilary-Prog** [comment]
Thanks alot, Scott.
I will try both.

**Comment by Hilary-Prog** [comment]
I will re-install .NET and try again.
Thanks, Chris.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by scottfurry** [comment]
@Hilary-Prog - google-fu: https://support.microsoft.com/en-ca/help/2641432/check-your-hard-disk-for-errors-in-windows-7

**Comment by justinclift** [comment]
Should this issue be closed, or is there more we need to do? :smile:

**Comment by Hilary-Prog** [comment]
I think it should be closed.
The solution is to use portable SQLite.
So I 'm not sure there is more to do except write a whole new version of
SQLite.
The portable version solves the issue.

**Comment by chrisjlocke** [comment]
> So I 'm not sure there is more to do except write a whole new version of
> SQLite

I'm not too sure how that would solve this issue.  But we'll close this for the time being as it's an isolated incident.  I'm glad the portable version works for you.  👍
