### ISSUE TITLE
primary

### ISSUE THREAD

**Issue by TanyaGnedina** [sqlitebrowser/sqlitebrowser#2196]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
@TanyaGnedina Guessing this was accidentally opened, and we're ok to close it? :smile:

**Comment by chrisjlocke** [comment]
@TanyaGnedina - feel free to submit another request if you've still got issues.

**Comment by justinclift** [comment]
@chrisjlocke We seem to be having a run of these (slowly) crop up over the last few months.  GitHub itself seems to have automatically-nuked one of them a week ago or so too. eg received email notification for it, but it wasn't here when I checked.

Wonder if it's from some UI change in GitHub, and other projects are having this happen too?

**Comment by chrisjlocke** [comment]
I can understand leaving spam (buy your tablets here, etc) but what's the benefit of leaving just a one word subject?  They must know they're doing it as they get notifications from us...
Aah well.  Close and move on...

**Comment by mgrojo** [comment]
Maybe we should leave some precooked polite comment and close them
directly. I doubt whether labelling them invalid would be useful in some
way. Probably not.

**Comment by justinclift** [comment]
Yeah, you're probably right. :smile:

**Comment by justinclift** [comment]
A variation on @chrisjlocke's comment would probably be suitable:

```
@name - This looks like it was created accidentally, so we'll close it. If it
wasn't an accident, feel free to reopen it or submit another request (with
more details) if you still need help.
```

**Comment by chrisjlocke** [comment]
Leaving a comment of #boilerplate here so I can find this again! 😄😄
Poor @TanyaGnedina being notified of every comment here.  *sigh* ;)
