### ISSUE TITLE
Default background colour for NULL fields needs adjusting

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#220]
At the moment, the default background colour for NULL fields is a very strong red.  It makes things seem like there's an error, when there's not:

![screen shot 2015-03-09 at 13 37 50](https://cloud.githubusercontent.com/assets/406299/6555908/8287b6ae-c661-11e4-96d3-94a9feda660a.png)
Maybe #ffd0cd instead?

![screen shot 2015-03-09 at 13 39 22](https://cloud.githubusercontent.com/assets/406299/6555934/b89d986c-c661-11e4-9bbf-8578e6a26da2.png)
Even lighter might be better too (unsure).  It depends on how the colour displays across a wide selection of monitors...

[side question - how does a person reset an existing field with a value to NULL?  I just tried and didn't find a reliable method. :frowning: In the edit dialog for a field, changing to "binary" then clicking "clear" and exiting works initially, but then the table goes white/non-NULL again after changing to the Database Structure tab and back again (sounds like a bug really) :wink:]

**Comment by samir-aguiar** [comment]
I've changed this and added options (not commited yet) for a custom text and custom foreground and background color, as suggested by @glawrence in #163.
However, I can't find a nice layout for the fields. I've added them to a new "Data Browser" tab, because I though that putting them somewhere else would be misleading.
Thoughts? :smile: 

![null_fields](https://cloud.githubusercontent.com/assets/3753623/6561287/4ed57470-c690-11e4-8ec8-fbf6786fcdd6.png)

**Comment by samir-aguiar** [comment]
P.S. those colours won't be the default, of course :smile:

**Comment by glawrence** [comment]
Thanks for remembering! I quite like #ffd0cd by the way and the new tab looks good to me.

**Comment by justinclift** [comment]
Yep, looks workable to me too.  Clean look, clear info.  Pretty good. :smile:

**Comment by justinclift** [comment]
Actually, is it easy to have the "NULL fields" title at the top of the containing box be a bit more um... stand out?  Bolder or underlined or errr... something?

Not at all critical, but I'm just thinking "it's the heading for the stuff below" and it's not really standing out as a heading that much.  Yet. :wink:

**Comment by samir-aguiar** [comment]
Indeed it was too small, @justinclift. Here's how it looks in the end:

![browser_settings](https://cloud.githubusercontent.com/assets/3753623/6605025/0bdc8462-c82d-11e4-80eb-d6c4cd336e76.png)

The default colors and text are the same as in the first implementation by @MKleusberg. I think this way is better because it's more neutral and won't change much for those accustomed to the old appearance, but no problems to set it otherwise :smile:

**Comment by justinclift** [comment]
Looking good.  Is there a way to horizontally centre the "NULL" string in the field?

**Comment by samir-aguiar** [comment]
Done :smile:

**Comment by justinclift** [comment]
Hmmmm, just tried it.  It's showing centres in the Preferences dialog, but not for the fields themselves in the Browse Data tab?

**Comment by justinclift** [comment]
Then again... I'm kind of wondering if "centred" in the Browse Data fields will actually look right... :wink:

**Comment by samir-aguiar** [comment]
Ahh I thought you meant the field in the settings pane. :grin: 
Yeah, that's doable, but won't that look out of place when the others are left-aligned horizontally?
Have a look:

![screen](https://cloud.githubusercontent.com/assets/3753623/6607961/66f674e6-c843-11e4-8f20-a281b2cceea8.png)

**Comment by justinclift** [comment]
Hmmm yeah.  I think you're right.  It looks good centred in the Preferences dialog bit, but in the Browse Data tab... not so much.  Leave it left aligned. :smile:

**Comment by samir-aguiar** [comment]
So @justinclift I've commited some changes for this bug of not being able to set the value to NULL. Now the clear button should set it permanently :smiley: Also, when it's NULL the type in the edit dialog will be shown as "Null", so it's possible to tell empty from NULL.
If you could test it would be great :smile:

**Comment by justinclift** [comment]
Awesome.  Just tried it out, and NULL values are now kept correctly.  No more reverting back to blank spaces at every opportunity.

They're written out to disk correctly now too, so things set to NULL **keep** as NULL.  Until changed on purpose of course.

Thanks @samir-aguiar I think this is a important fix.  Kinda feels like we'd been missing foundational data handling with this busted. :wink:
