### ISSUE TITLE
bracket highlighting doesn’t work proper on Windows light style

### ISSUE THREAD

**Issue by horst-p-w-neubauer** [sqlitebrowser/sqlitebrowser#2203]
Details for the issue
--------------------
bracket highlighting doesn’t work proper on Windows light style
cursor sits on line 4 behind the bracket in both windows

light (desktop) style: you can’t see the highlighting in line 2
 
![grafik](https://user-images.githubusercontent.com/28151942/80020906-121f4e80-84da-11ea-9197-dbaa600d346f.png)

dark style: you can see the highlighting in line 2 very fine
 
![grafik](https://user-images.githubusercontent.com/28151942/80020926-177c9900-84da-11ea-9673-025d35b3847c.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_7 ___ )

#### What is your DB4S version?

- [ x] 3.12.0-(alpha or betas)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by sky5walk** [comment]
I think you mean "Dark" style?
The cursor disappears in Dark style whenever on a bracket. 😢

**Comment by horst-p-w-neubauer** [comment]
@sky5walk , no, sorry. I mean "follow the desktop" style. On my Win 7 mashine, you can't see the bracket hightlighting if you're on different lines. It has been once that the corresponding bracket changed its color from black to blue. This isn't anymore. It's just the background changing to white what ist difficult to be seen in one line (because the acual line is in light gray) - but absolutely worthless on different lines as they are allready showing with white background.

**Comment by mgrojo** [comment]
@horst-p-w-neubauer  I've added the possibility of changing the brace highlighting colour and the new default has been improved and adapted to the dark or light style. It also includes new settings for the selection colours. Could you confirm it works for you using tomorrow's nightly build or latest code in master?

**Comment by chrisjlocke** [comment]
@horst-p-w-neubauer - *cough*
