### ISSUE TITLE
open a set of SQL-Files

### ISSUE THREAD

**Issue by horst-p-w-neubauer** [sqlitebrowser/sqlitebrowser#2207]
Describe the new feature
--------------------------
enhance Open SQL File, 
![grafik](https://user-images.githubusercontent.com/28151942/80126431-5f132b80-8593-11ea-8169-b9ea7aab9fea.png)
so You can select more than one file in the Dialog
![grafik](https://user-images.githubusercontent.com/28151942/80126678-ae595c00-8593-11ea-8111-72704fb429b5.png)

and open each in a different tab, if not allready loaded (this is the part, that holds the most work to be done)
![grafik](https://user-images.githubusercontent.com/28151942/80126908-e3fe4500-8593-11ea-931e-55ba22cf2219.png)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by horst-p-w-neubauer** [comment]
I just realised, that there is actually no test on allready loaded same files. So I'll not miss it on loading a set of files too.

**Comment by horst-p-w-neubauer** [comment]
trying to implement this #2211

**Comment by horst-p-w-neubauer** [comment]
Seen in "Version 3.12.99 (May  3 2020)".
Happy!

**Comment by justinclift** [comment]
Awesome. :smile:

Does anyone know if this change is simple enough that it would apply cleanly to the master branch too? (obviously haven't tested it)

**Comment by mgrojo** [comment]
I think it's a clear candidate for the 3.12.x branch.

**Comment by justinclift** [comment]
Cool.  Just created a new `needs merging with upcoming release branch` label, which can apply to stuff then get around to figuring out the merging later. :smile:
