### ISSUE TITLE
.Net access DB Browser for sql?

### ISSUE THREAD

**Issue by caoanqi** [sqlitebrowser/sqlitebrowser#2214]
Is there an interface for .Net access?
thanks

**Comment by chrisjlocke** [comment]
SQLite has .Net libraries.
https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki

The downloads are lengthy, but I'd recommend the precompiled binaries (non bundle)
https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netFx46-binary-Win32-2015-1.0.112.0.zip
If you're application is 64-bit, then download also the 64-bit version.
https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netFx46-binary-x64-2015-1.0.112.0.zip

I use Visual Studio and program in VB, and its dead easy to get this running.  Happy to walk you through that process if its any good.

**Comment by chrisjlocke** [comment]
*cough*

Do you need any further assistance, or can this be closed?

**Comment by chrisjlocke** [comment]
Closing as no response.  Feel free to comment further if you want to continue with this though.

**Comment by caoanqi** [comment]
Sorry, I just logged into github.
my db file is encrypt. So dot net is accessible.

**Comment by chrisjlocke** [comment]
Encrypted using what method?  You can use the system.data.sql library mentioned above with a password property
http://web.archive.org/web/20130325100811/http://sqlite.phxsoftware.com/forums/t/130.aspx

BUT - be aware that the encryption isn't compatible with SqlCipher, so you won't be able to open the database in that, NOR DB4S (unless you decrypt it first, obviously...)
