### ISSUE TITLE
Enhancement Request, Allow Copy to info in About DB Browser OSX Version

### ISSUE THREAD

**Issue by jmagyari** [sqlitebrowser/sqlitebrowser#222]
Allow copying of info in About DB Browser, so it can be copied and pasted when sending bug and enhancement requests 351, 486, SQLCipher386 version and 351, 486, SQLite 3.8.8.2.

Also should in SQLCipher Version mention OPENSSL version?

**Comment by justinclift** [comment]
Sounds useful. :smile:

**Comment by justinclift** [comment]
Thanks Martin.  Seems to work well here for the standard SQLite build:
![screen shot 2015-03-11 at 20 32 31](https://cloud.githubusercontent.com/assets/406299/6606220/d9a8c414-c82d-11e4-8a2f-9eb9606b08ab.png)

I haven't tried with the SQLCipher build yet.  Having some issues on my local system after a recent Xcode software update. :innocent:

**Comment by MKleusberg** [comment]
It's exactly the same in the SQLCipher version. However, I haven't added the OpenSSL version (though that would be nice to have) because SQLCipher doesn't seem to report it anywhere and I can't think of a sane way of getting it from somewhere else.

**Comment by justinclift** [comment]
k, lets ask the SQLCipher people if there's already a way, or if they think it's a good idea to add in their future releases. :smile:

**Comment by justinclift** [comment]
Cool, looks like it'll be available in future SQLCipher versions.  We might want to keep this issue open until then, when we can add the relevant bits.

**Comment by justinclift** [comment]
@MKleusberg Would it be feasible to add the git commit id in the About dialog, when DB4S is compiled from git manually?  eg same thing that detects master_git, but puts something like "git master commit c3c8f8ce568114d7aae1ae263e03390617c7c878" instead?

**Comment by mgrojo** [comment]
> @MKleusberg Would it be feasible to add the git Commit ID in the About dialog, when DB4S is compiled from git manually?
> 
>   eg same thing that detects master_git, but puts something like "git master commit [c3c8f8c](https://github.com/sqlitebrowser/sqlitebrowser/commit/c3c8f8ce568114d7aae1ae263e03390617c7c878)" instead

This will be in our next release. One old issue less.

> DB Browser for SQLite Version 3.13.0
> Last commit hash when built: 5f656a1
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.12.8
> SQLite Version 3.44.0.
