### ISSUE TITLE
Builds Failing on launchpad due to missing "images/sqlitebrowser.svg"

### ISSUE THREAD

**Issue by deepsidhu1313** [sqlitebrowser/sqlitebrowser#2225]
Details for the issue
--------------------

#### What did you do?
Launchpad pulled latest code from repo and tried building packages from it

#### What did you expect to see?
Successful buillds of deb packages

#### What did you see instead?
Errors and Failures
```
dh_install: warning: Cannot find (any matches for) "images/sqlitebrowser.svg" (tried in ., debian/tmp)

dh_install: warning: sqlitebrowser missing files: images/sqlitebrowser.svg
dh_install: error: missing files, aborting
make: *** [debian/rules:7: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: (Ubuntu 16.04 and above)
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0-(alpha or betas)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  Looks like we missed a spot when renaming things in: https://github.com/sqlitebrowser/sqlitebrowser/commit/e985a012d40fb66c18c60e3893f06fdd15ac3d4e

**Comment by justinclift** [comment]
If it helps, the file is probably called "images/logo.svg" now.  Hopefully it's just a text or config file that just needs updating?

**Comment by deepsidhu1313** [comment]
Added [Commit](https://github.com/deepsidhu1313/sqlitebrowser-deb-packaging/commit/819f0eaa87610f3c27fff1e5e8e060287cf10e4f)

**Comment by deepsidhu1313** [comment]
Worked . https://code.launchpad.net/~linuxgndu/+recipe/sqlitebrowser-recipe-daily

**Comment by justinclift** [comment]
Awesome, well done. :smile:
