### ISSUE TITLE
losing Main Tabs on editing registry

### ISSUE THREAD

**Issue by horst-p-w-neubauer** [sqlitebrowser/sqlitebrowser#2228]
Details for the issue
--------------------

When you edit „HKCU\Software\sqlitebrowser\sqlitebrowser\MainWindow\openTabs“ in the registry and get anything wrong – you will lose this main tab for ever. I thougt, this key is ment to save the order oft the tabs – so it should open the main tabs, that are not included in the registry key in default order after the included ones. 

![grafik](https://user-images.githubusercontent.com/28151942/80864319-302b4280-8c82-11ea-9d63-88c3845ffadf.png)
![grafik](https://user-images.githubusercontent.com/28151942/80864325-38837d80-8c82-11ea-8ecf-ec30eb387087.png)

Useful extra information
-------------------------
> DB4S v3.11.100 [built for x86_64-little_endian-llp64] on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.32.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
So what happens if you bring the tabs back via the options in the view menu?

![image](https://user-images.githubusercontent.com/7872218/80866505-f6a90600-8c86-11ea-95e6-bcfce73188fb.png)

I'm basing this on 3.11.99 though... unsure if its the same...

**Comment by horst-p-w-neubauer** [comment]
Shame on me! I've never realised this option! Sorry.

**Comment by chrisjlocke** [comment]
👍

**Comment by mgrojo** [comment]
You can move around the tabs and close and reopen them using the View menu. "Alt+0" will always restore the tabs and any other rearrangement. The first implementation included close buttons in the tabs, but we thought it would be easy to close one erroneously and maybe hard to find how to recover them.

Different tab layouts can be saved in different project files.
