### ISSUE TITLE
Foreign Characters incorrectly displayed on OSX for v3.5.1, Qt 4.8.6, SQLite 3.8.8.2 and SQLCipher 3.8.6

### ISSUE THREAD

**Issue by jmagyari** [sqlitebrowser/sqlitebrowser#223]
FROM http://www2.sqlite.org/cvstrac/wiki?p=ConverterTools
Download Northwind.SL3 
from http://download.vive.net/Northwind.zip
NAVICAT FOR SQLITE 11.1.9 CONNECT TO NORTHWIND.SL3,
VIEW CUSTOMER TABLE, VIEW COMPANY NAMES USING FOREIGN CHARACTERS
They appear correct in NAVICAT

Connect via sqlitebrowser and foreign characters appear as question mark in BLACK rotated
Browse Data Table Customers->Company Names
Berglunds snabbk�p  should be Berglunds snabbköp
SQUAREOSX SQLite 3.5.1., 4.8.6, 3.8.8.2 and SQLCipher 3.8.6 versions

**Comment by justinclift** [comment]
Interesting.  I'll take a look after work today. :smile:

**Comment by justinclift** [comment]
Just took a look now instead, and yep, you're right.  This is what's showing for me on OSX 10.9.5:
![screen shot 2015-03-11 at 14 15 26](https://cloud.githubusercontent.com/assets/406299/6598089/297766ba-c7f9-11e4-8dcb-1e4017d599dc.png)

**Comment by Z4us** [comment]
I have a version of the same database that works correctly. I'll send it to you if you want and PM me your email-address.

México D.F.

Perhaps a good idea to use this as our standard TestBase?

**Comment by rp-** [comment]
The same thing is on Linux and even on the commandline client.
So my guess is that the database didn't get correctly converted to a UTF16 sqlite3 db or the strings are not correctly converted to UTF8 strings

**Comment by Z4us** [comment]
--[[z4us|bb--]]
sqlite3 nw.sqb
SQLite version 3.8.8.3 2015-02-25 13:29:11
Enter ".help" for usage hints.
sqlite> select * from Customers where CustomerID like 'AN%';
ANATR|Ana Trujillo Emparedados y helados|Ana Trujillo|Owner|Avda. de la Constitución 2222|México D.F.||05021|Mexico|(5) 555-4729|(5) 555-3745
ANTON|Antonio Moreno Taquería|Antonio Moreno|Owner|Mataderos  2312|México D.F.||05023|Mexico|(5) 555-3932|

**Comment by Z4us** [comment]
I agree with https://github.com/rp- 

Perhaps the uploader used some pre-UTF8 codePage 

To check go to http://mysharepoint.org/Accounting/Lists/Client%20List/AllItems.aspx

**Comment by justinclift** [comment]
@jmagyari Looks like a problem with the data itself then, so I'm marking this as invalid and closing it.

You're completely welcome to re-open this though, if you find out the original data really is ok somehow. :smile:

**Comment by justinclift** [comment]
Hmmm... thinking it through more... it doesn't appear to be something wrong with the data.  Here's what it looks like in Navicat for SQLite (just grabbed their trial):
![screen shot 2015-03-11 at 16 16 07](https://cloud.githubusercontent.com/assets/406299/6600864/fcd02fa0-c809-11e4-8e74-22a3a665bce4.png)

**Comment by samir-aguiar** [comment]
This is really a problem with the data. In the header of the file it says UTF-8, but the characters are encoded in Windows-1252 or ISO 8859-1. Navicat probably uses one of them as fallback or something. But the specification states that only 3 encodings are valid, namely UTF-8, UTF-16le and UTF-16be.

**Comment by justinclift** [comment]
Awesome, thanks for looking into it @samir-aguiar.

Is this something we should try to recognise and work around (similar to Navicat), or are we good as-is?

Kind of wondering if there's a way to detect bad data, so we could at least warn the user.  No idea how feasible that really is though. :wink:  If it's a major undertaking, then lets not bother. :smile:

**Comment by samir-aguiar** [comment]
Hmm I don't know much about encoding, but it's possible to detect invalid UTF-8 characters, yes. It could then default to some other encoding instead of invalidating them (which is what I think is currently happening). So I think it's doable, however it will probably require a lot of changes.

**Comment by Z4us** [comment]
It's indeed rather tricky to make an educated guess. There are so many ways to encode/encrypt data. Navicat was lucky since 8859-1 (Latin-1?) is (almost was) one of the most common. If the developers are able to detect let's say four of five of those, they deserve a prize. I don't think it's worth all the effort though besides an increase in size...

**Comment by justinclift** [comment]
k.  Sounds like we should mark this off as "won't fix", because although technically possible to deal with... it's an edge case for dealing with bad data and is likely a lot of effort.

Although, if someone does come along and contribute a fix/patch to address the problem, we'll happily merge it. :smile:
