### ISSUE TITLE
Attach Database error

### ISSUE THREAD

**Issue by Jymms** [sqlitebrowser/sqlitebrowser#2230]
Can't attach a data due to what I think is the file directory
--------------------
It seem like you haven't taken into consideration an apostophy in a directory.  

Error Message:  near "s": syntax error (ATTACH 'C:/Users/Jym's Laptop/Documents/db2008.dat' AS "db2008") 

-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
Oh, that sounds like an escaping problem.

Um, would you be ok to try the 3.12.0-alpha1 release, and see if it still happens there?

* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.0-alpha1/DB.Browser.for.SQLite-3.12.0-alpha1-win64.msi

I'm kind of thinking it should be fixed, but am not 100% sure. :smile:

**Comment by Jymms** [comment]
100% sure it's an escaping problem otherwise the apostrophe in the error would show as Jym''s laptop :)   I just added it in the sql tab and all was good.  Is there a non-install version of of 3.12.0-alpha1, it's a work laptop so I can't install software.  Otherwise anyone can test it by creating a folder with an apostrophe.

**Comment by justinclift** [comment]
Ahhh, just grab the .zip version instead:

* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.0-alpha1/DB.Browser.for.SQLite-3.12.0-alpha1-win64.zip

Just unzip the to a folder, and run in-place.  No need to install stuff. :smile:

**Comment by Jymms** [comment]
Yes that worked, and the opening of SQLite browser has gone from waiting, waiting, waiting to a regular app open speed.  Impressive. 

I'm sure this isn't the appropriate spot to put a suggestion, but … Why don't you include the encoding with the New Database?  I'm guessing as more people use UTF16 that would be handy as you're 'screwed' if you do anything at all prior to setting the pragma encoding which includes the first table that comes up in the popup.

**Comment by justinclift** [comment]
Hmmm.  I'm not really aware of the uses of UTF16 vs other stuff, as it's not something I've personally had to think about.

How about making a new issue with this (+ details?) as the suggestion? :smile:

**Comment by Jymms** [comment]
(I babble so let me know if 2232 makes sense)

**Comment by justinclift** [comment]
Guessing you mean #2234? :smile:

**Comment by MKleusberg** [comment]
Looks like the original problem is solved by the latest version :smile: So I'm going to close this issue.
