### ISSUE TITLE
Minor: Change "Filter in all columns" => "Filter in any column"

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2233]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0-(alpha or betas)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
You are suggesting just a rewording, don't you? At first, I thought it was a feature change.

**Comment by tonypdmtr** [comment]
Yes, just rewording to match behavior

**Comment by mgrojo** [comment]
@MKleusberg, what do you reckon? It was your wording. I think the change would make sense.

**Comment by MKleusberg** [comment]
I agree. Thanks for pointing this out, @tonypdmtr. I have just changed the wording.

Should we ask the translators to update this or just fix it in the next release?

**Comment by justinclift** [comment]
Might as well get it done for 3.12.0 release, as there are other strings that need updating anyway too. :smile:

**Comment by tonypdmtr** [comment]
Thank you
