### ISSUE TITLE
Colored emoji in the grid and edit cell.

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2236]
Describe the new feature
--------------------------
🍒 (as many other UTF-8 characters) is colored.  The grid and edit cell box show the correct character but in black-and-white.

Allow colors to display.

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
Emojis are very recent and still not well-supported in all platforms/toolkits. For this we need support in operating system, font and Qt. Have you tried with the 3.12 alpha version? And changing the font?

Look for related bug report in Qt and test some of the proposed solutions:
https://bugreports.qt.io/browse/QTBUG-55096?jql=text%20~%20%22color%20emoji%22

**Comment by justinclift** [comment]
Qt released version 5.15.0 a few weeks ago.  We could try that, and see if it makes a useful difference.

**Comment by mgrojo** [comment]
This is working for me in the development version.

![imagen](https://user-images.githubusercontent.com/13812910/209716338-788ed0bc-d6ee-417c-8902-e2a69f8eb398.png)

@tonypdmtr, I'll close this issue, but if you want to try the nightly build and have different results in your environment, you are encouraged to reopen it again and report it.

> DB Browser for SQLite Version 3.12.99 (Dec 22 2022)
>
> Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.3
SQLCipher Version 3.4.1 (based on SQLite 3.15.2).
