### ISSUE TITLE
How do I include rowid column in browser grid?

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2237]
What is your question
-----------------------

I'd like to include rowid column in browser.  Is there some option to do so?

The numbers displayed in the browser grid (apparently) are sequence numbers of the selected rows but I also need to know the associated rowid, and also be able to sort by it.

(I know I can get it with SQL but then I cannot edit the result.)

**Comment by chrisjlocke** [comment]
Right-click on a column header.
Select 'Show RowId'

![image](https://user-images.githubusercontent.com/7872218/81497419-5a01ec00-92b6-11ea-9ff5-52cb1af64f14.png)

**Comment by tonypdmtr** [comment]
Thanks
