### ISSUE TITLE
Detach Database

### ISSUE THREAD

**Issue by CARRIVIN** [sqlitebrowser/sqlitebrowser#2239]
Describe the new feature
--------------------------
It will possible to get Detach database?

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Yes, https://github.com/lazierthanthou/sqlite-manager

#### Do you have a screenshot? Please add screenshots to help explain your idea.

![Image2](https://user-images.githubusercontent.com/65180266/81580855-4174fd00-93ae-11ea-866e-5bfe8f1dc0f5.jpg)

**Comment by justinclift** [comment]
Sounds like a reasonable idea. :smile:

**Comment by horst-p-w-neubauer** [comment]
One easy attempt might be adding a `detach` command to the popup on the schemaTree where the attached databases show up:
![grafik](https://user-images.githubusercontent.com/28151942/81606175-e30e4580-93d2-11ea-95f9-6b61c911264a.png)

**Comment by justinclift** [comment]
Sounds like a decent idea too. :smile:

**Comment by horst-p-w-neubauer** [comment]
Who could create an icon for that action?

**Comment by mgrojo** [comment]
I can do it. Do you have a branch? If you push it, I can add the icon to it.

**Comment by horst-p-w-neubauer** [comment]
detach-database

**Comment by mgrojo** [comment]
Done. You can reference it using alias db_detach.

**Comment by CARRIVIN** [comment]
Hi Martin, great It works. Thanks a lot. ;)

**Comment by CARRIVIN** [comment]
Thanks a lot all.

**Comment by justinclift** [comment]
Awesome.  Thanks for testing it and letting us know @CARRIVIN. :smile:

**Comment by MKleusberg** [comment]
> Hi Martin, great It works. Thanks a lot. ;)

Well, it's all been @horst-p-w-neubauer's work :wink:
