### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Deanomac** [sqlitebrowser/sqlitebrowser#2245]
Via, paypal or Crypto?
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
I've a feeling this isn't a real request, but just in case, we use Patreon.
There is also this topic.
https://github.com/sqlitebrowser/sqlitebrowser/issues/1992

I'll close this, but if this is legitimate, feel free to comment further and it can be reopened.
