### ISSUE TITLE
rename internally ColumnObjectType values „database“ to „schema“

### ISSUE THREAD

**Issue by horst-p-w-neubauer** [sqlitebrowser/sqlitebrowser#2247]
For every item of `m_db.schemata[]`  `DbStructureModel::reloadData()` creates an item with a `ColumnObjectType` named `„database“`. That is inconsistent. All other elements are named identically in `sqlitedb` and in `DbStructureModel`: `„table“, „index“, „view“`  – but not `"schema"/"database"`. I don’t see any reason why. It reduces code readability. 

You probably have to be a newbie to the code-base to get disturbed - so I bring it up as long as I'm not driven in too deep to recognize it anymore.

**Comment by scottfurry** [comment]
Sqlite is NOT an RDBMS (Relational DB Management System). That singular idea has to be grasped before any comparisons are made WRT Oracle, MS, MySQL, MariaDB, PostgreSQL, et al.

See this [design note](https://www.sqlite.org/lang_naming.html) for Sqlite.

**Comment by justinclift** [comment]
> Sqlite is NOT an RDBMS (Relational DB Management System).

That sounds a bit strange.  Looking through the SQLite page there, I'm not really seeing anything which would indicate "not a relational database".  ???

**Comment by horst-p-w-neubauer** [comment]
Thank You @scottfurry for reminding me. but that is not the point.

I don't consider any other DB-Systems. I just investigate our code base. 
I find `class DBBrowserDB in sqlitedb.cpp` has a member `schemaMap schemata`. This map holds all schemata of the actual databasemodel with its alias names (or schema) and an `sqlitedb::objectMap` that hold all database structure objects of the respective schema. For each of this schemata[] entities `DbStructureModel::reloadData()` produces an `QTreeWidgetItem` and it sets the string "database" as  its ColumnObjectType value. Where as tables are named as table in both files.

**Comment by horst-p-w-neubauer** [comment]
I just plead for consistent naming through over the whole project. IMHO opinion we should decide how to name this entity and don't mix different namings. While I found most often 'schema' I suggest to got for 'schema' and rename '"database"' as internal objectType to "schema".

**Comment by horst-p-w-neubauer** [comment]
@scottfurry , could You please give me another hint, what it is, that you can't agree to?

**Comment by scottfurry** [comment]
> > Sqlite is NOT an RDBMS (Relational DB Management System).
> 
> That sounds a bit strange. Looking through the SQLite page there, I'm not really seeing anything which would indicate "not a relational database". ???

Read the full Acronym expansion again.... _Relational DB Management **SYSTEM**_.

**Comment by horst-p-w-neubauer** [comment]
Alright - so - naming consistency is not Your problem - did I get this right?
Would You agree to me, that it would be find to have **one** consistent name to the same object inside our code?

**Comment by scottfurry** [comment]
There are _vast_ number of things I would very much like to do to the code base. However, DB4S code is working well for others and is in heavy usage. Situation is further complicated by historical needs and my own personal bandwidth. Justify *exactly* what needs to change, why the effort to change is necessary, and be prepared to do the _heavy lifting_ to make happen. If this isn't done then the conversation risks be described as an [XKCD comic](https://xkcd.com/927/).
My €/$0.02 and IHMO.

**Comment by horst-p-w-neubauer** [comment]
> and be prepared to do the heavy lifting to make happen
I've allready done this while I was waiting for your response. 

I'm working on #2242 and came over the need to add the databases/schema filepath information and was stepping over this inconsistency and so I suggest to get rid of it. Next reason is, that I think we should have a Object for schema like we have one for table, index, view and triggers as well. That is because we hide schema attriubtes (main/temp/attached) behind magic strings "main", "temp" and (not ("main") and not("temp")) as we have only one attribute for a schema beside its structure - and that is its name. I'd be happy to assign the file name to an schema object - but that doesn't exist. Before introducing this Object I wanted to get the thing itself be addressed consistent over our code base. 

Please, consider.

**Comment by scottfurry** [comment]
Not up to me to consider. This would have been easier with just a pull request and then focus on the code and its impact. A dozen or so messages later.... :(

**Comment by horst-p-w-neubauer** [comment]
done - I'm off for an hour or too

**Comment by mgrojo** [comment]
I'm not sure if I follow all the conversation, but if I've understood well, I don't see we are in discordance to the nomenclature used by SQLite itself, looking at the ATTACH documentation page, the argument to the statement is called database. Besides, if calling it database is convenient for the user, why is it inconvenient to us? But in any case, I think the concepts of database file and schema overlaps in some points. There will be ones where schema is the most appropriate (when you are referring to entities inside an attached database, it is better to use schema) and others where database is more appropriate, when you are talking about attaching, detaching or in general referring to the attached database, or the main database file. There will be other points where there is a grey area. Problem with schema: it is polysemic too. It sometimes refers to the objects structure and the SQL statements to define them, others to a namespace with which these objects can be referenced.

**Comment by horst-p-w-neubauer** [comment]
I agree to this - database and schema is ambiguous inside our code. So if there is a need for us to distinguish between schema an database - I'm absolutely fine with. But then I would like to know what is our common understanding of the one and of the other - and what are the different needs that we have?

Our actual code isn't sure about what is what. Look at this and the different use of ColumnName:
```
  // This is the main database
    itemAll->setIcon(ColumnName, IconCache::get("database")); 
    itemAll->setText(ColumnName, tr("All")); // hn? why does schema name and name differ - shouldn't this be solved on DisplayRole?
    itemAll->setText(ColumnObjectType, "database");
    buildTree(itemAll, "main"); // hn? "main" is the schema 

  // this is the temporary database
        itemTemp->setIcon(ColumnName, IconCache::get("database")); 
        itemTemp->setText(ColumnName, tr("Temporary")); // hn? why does schema name and name differ - shouldn't this be solved on DisplayRole?
        itemTemp->setText(ColumnObjectType, "database");
        buildTree(itemTemp, "temp"); // hn? "temp" is the schema 

  // this is for all attached databases
            itemSchema->setIcon(ColumnName, IconCache::get("database"));
            itemSchema->setText(ColumnName, QString::fromStdString(it.first)); // schema - and you need it to detach because it's the only way to get the schema name out of this item so far
            itemSchema->setText(ColumnObjectType, "database");
            buildTree(itemSchema, it.first);  // ?hn ColumnName and schema are the same here
```

The first two items are Database items with a difference between Name and the schema of its children. The attached items seams to be schema Items as theire name is the same as the schema name of their children. In both cases i'd suggest to add and setText(ColumnSchema) to the toplevel Item.

So is it that: a schema is the alias for a database? If so I'd suggest to change schemata to databases, have it be an object with an schema attribute and name should be the name of the databasefile. I've absolutely no problem with that. But that would change the structure tree as it shows the name - or we decide to show the schema instead of the database on the structure tree - like we do now - but then - isn't it then a schema? 

Or is it a schema that have an database (file?) as an attribute - so let us go for this.

Clearing it out and changing it to a common understanding is fine for me.
Leaving it ambiguous is not the best to do I'd say.

**Comment by horst-p-w-neubauer** [comment]
Back from the greenhouse I've had some time to think about it. Isn't it like that:
1. schema is the logical structure of the database
2. database is the complete information - schema and the data itself

If we agree to see it so, I'd think it's the schema what we actually see in the "Database Structure" tab when we show the schema name of an attached database, as we show only the structure of the database. We don't show any dabase-specific information: how big is the file, how many rows are in which table, what pragmas are set etc. So the type of the node should change to "schema".

If we once would add database related information we would need to add a node of type "database" where "schema" is one of the childrens.

But this is just an invitation to an open discussion.

**Comment by justinclift** [comment]
> Read the full Acronym expansion again.... Relational DB Management SYSTEM.

Are you meaning "Relational DB Management **server**" rather than system?

"SQLite isn't a database server" is obviously true, but "SQLite isn't a relation database system"... still makes no sense to me.  :smile:

**Comment by scottfurry** [comment]
https://en.wikipedia.org/wiki/Relational_database

**Comment by justinclift** [comment]
@scottfurry The approach of just blindly linking to stuff, with literally no explanation at all of what you're meaning is ridiculous.  Please do better. :smile:

**Comment by horst-p-w-neubauer** [comment]
@scottfurry I agree with You. Sqlite is not a DBMS. But that doesn't free us from clearing out what is the difference between our understanding of "database" and "schema". Maybe it helps to have a look on sqlites view of this matter, I off some refferences to the sqlite doku: 
[In-Memory Databases](https://www.sqlite.org/inmemorydb.html)
> An SQLite database is normally stored in a single ordinary disk file. However, in certain circumstances, the database might be stored in memory.
> 
> The most common way to force an SQLite database to exist purely in memory is to open the database using the special filename ":memory:". In other words, instead of passing the name of a real disk file into one of the sqlite3_open(), sqlite3_open16(), or sqlite3_open_v2() functions, pass in the string ":memory:"
> 

[Single-file Cross-platform Database](https://www.sqlite.org/onefile.html)
> A database in SQLite is a single disk file

[2.6. Storage Of The SQL Database Schema](https://www.sqlite.org/fileformat2.html#intschema)
>Page 1 of a database file is the root page of a table b-tree that holds a special table named "sqlite_master" (or "sqlite_temp_master" in the case of a TEMP database) which stores the complete database schema.

[PRAGMA writable_schema = boolean;](https://www.sqlite.org/pragma.html#pragma_writable_schema)
>When this pragma is on, and the SQLITE_DBCONFIG_DEFENSIVE flag is off, then the sqlite_master table can be changed using ordinary UPDATE, INSERT, and DELETE statements. 

I would state: Sqlite distinguishes between "database" and "schema" and schema is a part of the database but not the database itself.

Next is on us to decide if we need this different view on our code model.

**Comment by horst-p-w-neubauer** [comment]
This Issue took a strange direction. I close it now. But sooner or later we should discuss design issues. And I hope, we all get prepared to do it in professional way.
