### ISSUE TITLE
FAILURE TO MODIFY TABLES

### ISSUE THREAD

**Issue by estevan6** [sqlitebrowser/sqlitebrowser#2248]
#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro: DEBIAN 10(buster) 64 bit, kernell 4.19.0-8-AMD64 x86_64, desktop MATE 1.20.4), 2GB RAM
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.2
- [ ] 3.11.1
- [X] 3.10.1
- [ ] Other: ___

**Comment by estevan6** [comment]
La modificación de esta columna falló. Error devuelto por la base de datos:
renameColumn: creación de la nueva tabla fallida. La base de datos dice: table `sqlitebrowser_rename_column_new_table` already exists (CREATE TABLE `sqlitebrowser_rename_column_new_table` (
	`id_hab`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`edo`	TEXT NOT NULL,
	`mun`	TEXT NOT NULL,
	`prq`	TEXT NOT NULL,
	`direc_habit`	TEXT NOT NULL,
	`telef_habit`	TEXT,
	`cel_1`	TEXT NOT NULL,
	`cel_2`	TEXT,
	`email`	TEXT NOT NULL,
	`url`	TEXT
);)

**Comment by mgrojo** [comment]
Sorry, @estevan6 , but we no longer maintain the 3.10 release. Can't you use an AppImage, snap package or build from source the latest release or the development version?

Besides this was already reporting in #2202, so I'm closing it now and mark it as duplicate.
