### ISSUE TITLE
Invalid file format

### ISSUE THREAD

**Issue by trbsi** [sqlitebrowser/sqlitebrowser#225]
I'm trying to open sqlite database. It is working with some databases, with others there is error:"Invalid file format"
Not sure if it is because of database or sqlitebrowser

**Comment by justinclift** [comment]
Couple of questions.. :smile:

* Which version of DB4S (new acronym for SQLite Browser) are you trying with?
* Which Operating system are you using?

If the file is not too big (eg couple of MB's), and the info in it isn't confidential, you can email it to me directly (justin@postgresql.org) and I'll see if I can figure it out.

**Comment by trbsi** [comment]
DB4S 3.5.1.
Win 8.1

 I will email it to you now :)

**Comment by justinclift** [comment]
Just took a look through them, and they don't appear to be with SQLite version 3, nor SQLite version 2 database files.

There's definitely data of some sort in them, as using "vi -b" or even "strings" on them shows bits of text in them.

Sorry to say, but I have no idea what you can open them with. :frowning:

**Comment by trbsi** [comment]
It's fine, thank you :)

**Comment by justinclift** [comment]
Good luck. :smile:

**Comment by justinclift** [comment]
Btw - Don't get stressed about the "Invalid".  It's just so I can scan down the closed bug list quickly when preparing our next release. :smile:
