### ISSUE TITLE
Issue with Arabic writing in query

### ISSUE THREAD

**Issue by SafeerDeveloper** [sqlitebrowser/sqlitebrowser#2254]
Details for the issue
--------------------
Hi, greetings for those who spent their times to give us  useful tools like sqlbrowser.
there is an issue when you need to type arabic in query statements like: INSERT INTO the direction layout of typeing revers arabic words inside quotations mark.
thank you,
-------------------------
> DB4S v3.12.99 (May  7 2020) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.32.0
> and Qt 5.12.8

**Comment by justinclift** [comment]
@SafaAlfulaij Any idea how to fix the problem? :smile:

**Comment by SafeerDeveloper** [comment]
for now ,i think setting some properties of textarea control which using for submitting  query it will be help.
![sqlite browser arabic issue](https://user-images.githubusercontent.com/13442266/82229566-4cdaa200-9933-11ea-95b9-e7516e8006f6.PNG)

**Comment by chrisjlocke** [comment]
Not a fantastic workaround, but can you put the Arabic part on its own line?
So 

     insert into employees(user_id,user_job_tilte,user_name,user_phone)
     values(20294,
'',
'name',
'000')

I assume that would still fail - the text would crash over the opening apostrophe?

**Comment by mgrojo** [comment]
This is an known problem: #884. So I'm going to close this issue as duplicate. Please, subscribe to the other and add any useful information there, so the information is not scattered and our number of issues is kept in manageable levels.
