### ISSUE TITLE
bulk update from file (TXT or CSV)

### ISSUE THREAD

**Issue by EngDarkRoseAlchemist** [sqlitebrowser/sqlitebrowser#2256]
Describe the new feature
--------------------------
Bulk update table from TXT and CSV files (demi-column, tab and comma separated)

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
I'm suspecting this is spam as per the other closed issues, and this is @EngDarkRoseAlchemist first issue.
Come on @EngDarkRoseAlchemist ... prove me wrong...

**Comment by justinclift** [comment]
GitHub is kind of going the way of fake forum spammers. :frowning:
