### ISSUE TITLE
SSL error..........again

### ISSUE THREAD

**Issue by bh4754** [sqlitebrowser/sqlitebrowser#2259]
I have read blogs where this has been a problem before.  I was able to download part of a db from Udacity and complete a project.  However, when I reopen DB SQLite now, I am getting a SSL DB Browser error

**Comment by scottfurry** [comment]
@bh4754 Paste the output from the console of the command  `openssl version`, please.
This may be as simple as OpenSSL in need of an update.

**Comment by justinclift** [comment]
@bh4754 If you're on Windows or macOS, our recent 3.12.0-alpha1 release fixes the problem for most people: :smile:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/first-alpha-release-for-3-12-0/

**Comment by chrisjlocke** [comment]
@bh4754 - Can you test the latest release candidate?
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.12.0-rc1

**Comment by chrisjlocke** [comment]
Closing this due to lack of information.  Now the release candidate is out there, either this will solve the issue, or we'll get more reports.
@bh4754 - feel free to comment once you've tried the release candidate, and if a program issue, we can look at it further.
