### ISSUE TITLE
Dark Mode!

### ISSUE THREAD

**Issue by djcornutt** [sqlitebrowser/sqlitebrowser#2261]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by scottfurry** [comment]
A little sparse on details...
See DB4S preferences for setting a Dark style.

Note to @justinclift - need a WIKI/FAQ entry for this.

**Comment by djcornutt** [comment]
Sorry, I hit enter to soon. If it possible to have this run in Dark Mode like browers and Office apps do that would be cool just a wish.

**Comment by scottfurry** [comment]
You're not the first to hit the enter button too quickly. It happens.
Open the preferences, on the first page about half way down is a dark style check box setting. Click and restart the app. It works by using a custom style sheet to restyle all the application GUI elements consistently. This will cause us grief when Qt6 rolls around as I've seen blurbs about qss style sheets going away.

**Comment by jerocis** [comment]
scottfurry, Thank you!

**Comment by JoshLambda** [comment]
Dark mode can now be set with: `Edit -> Preferences -> General -> Application style -> Dark style`
