### ISSUE TITLE
not showing result

### ISSUE THREAD

**Issue by Sworup-Raj** [sqlitebrowser/sqlitebrowser#2264]
Details for the issue
--------------------

#### What did you do?

SELECT Track.title, Artist.name, Album.title, Genre.name 
    FROM Track JOIN Genre JOIN Album JOIN Artist 
    ON Track.genre_id = Genre.id and Track.album_id = Album.id 
        AND Album.artist_id = Artist.id
    ORDER BY Artist.name LIMIT 3

#### What did you expect to see?
table containing different columns selected above.

#### What did you see instead?

Execution finished without errors.
Result: 0 rows returned in 19ms  #here result is 0?
At line 1:
SELECT Track.title, Artist.name, Album.title, Genre.name 
    FROM Track JOIN Genre JOIN Album JOIN Artist 
    ON Track.genre_id = Genre.id and Track.album_id = Album.id 
        AND Album.artist_id = Artist.id
    ORDER BY Artist.name LIMIT 3

Useful extra information
-------------------------
> DB4S v3.11.100 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.32.0
> and Qt 5.12.8

**Comment by scottfurry** [comment]
Joins....bane of many an SQL user. IIRC, there are the odd issues with full joins in sqlite3 (left joins? - been awhile).
Have you tried the same query on the sql db on the command line?
Open a console (or find run in menu and select CMD.exe)
If you enter ( `>` for command prompt)
```
> sqlite3  # this should open sqlite3 command line program
sqlite3> .open [path to db file]
sqlite3> SELECT... [ rest of query ] ;
```
!!! uber important -> end your query with a semi-colon.
Do you get the same empty results from this as you join-query?

**Comment by chrisjlocke** [comment]
I'm paddlin' slightly out of my depth (ie, have no idea what I'm talking about) but shouldn't each JOIN have its own ON statement, so the join knows how to connect?

**Comment by justinclift** [comment]
@Sworup-Raj If you want to try stuff out online to discuss, something like this where you can execute SQLite code live + show the results might be useful: :smile:

&nbsp; &nbsp; https://dbhub.io/vis/justinclift/Join%20Testing.sqlite

**Comment by MKleusberg** [comment]
The SQL query looks correct and does return results in my test database. So I think the reason you're not seeing any results is because the data in your tables is not matching. But it's hard to say without seeing the original database :smile:

**Comment by chrisjlocke** [comment]
@Sworup-Raj - Any more information you can provide us?

**Comment by chrisjlocke** [comment]
I'll close this as this looks like a data issue.
@Sworup-Raj - feel free to comment once you know more and if it is a program issue, we can look at it further.

**Comment by Sworup-Raj** [comment]
I find solution for this. Thank you who ever help me.
