### ISSUE TITLE
context menu option to copy images into clipboard

### ISSUE THREAD

**Issue by qci-amos** [sqlitebrowser/sqlitebrowser#2265]
Describe the new feature
--------------------------
I really like the image database cell option. I have a table where every row is some high level result summarized with this image. However, I often want to show the image to other users, e.g., post it in an instant messenger. Right now, the most convenient way to do it is to do a screencap of the cell, and copy/pasting that (which is easier than clicking export, picking a file location, saving, finding that directory in a file browser, nope wrong file it was that other one, copy/dragging, then deleting the file)

What would be nice would be a way to copy it directly into the clipboard ready to be pasted into an instant messenger.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
Couldn't find one.

#### Does this feature exist in another product or project? Please provide a link.

It seems like a common feature, but I use Snipping Tool on Windows to copy the screencap into my clipboard and paste into my employer's instant messenger.

#### Do you have a screenshot? Please add screenshots to help explain your idea.

n/a

**Comment by scottfurry** [comment]
The idea of how to manage/export a binary blob is a level of detail deeper than intended. Not impossible. I know in Gimp (www.gimp.org) you can create an image from clipboard data and save. Not sure of other tools on windows short of expensive photoshop and the like.

**Comment by qci-amos** [comment]
ah, this feature is already supported from the Browse Data cell. I was just looking for it in the wrong place (the Edit Database Cell context menu)

![image](https://user-images.githubusercontent.com/45039789/83432239-97195400-a406-11ea-8658-ea7bd94e9b0d.png)

**Comment by justinclift** [comment]
Seems like the kind of thing that the standard Copy keyboard shortcut (Control-c) should work too, when the cursor is on the cell with the image.

That being said, I haven't actually tried it. :wink:
