### ISSUE TITLE
export image/data to vscode (or other target app)

### ISSUE THREAD

**Issue by qci-amos** [sqlitebrowser/sqlitebrowser#2266]
Describe the new feature
--------------------------
One idea that I'd love for how to implement #2016 and #2265 could be to add a button to export/open an image in VSCode (i.e., in a single click). That would have the additional benefit (that I didn't make a dedicated issue for here) of allowing me to have multiple images on my screen at the same time.

Mostly I'm interested in images for this feature because there's already good support for copy pasting data in DB Browser for SQLite, but this approach could make sense for other data types too.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

#2016 #2265

**Comment by scottfurry** [comment]
VSC currently has the ability to import or open a file node (i.e. context menu option to "open with..."). However, that's where the ability for two programs "to share" data ends. VSC works on the Electron Framework (www.electronjs.org - otherwise a hyped up google chrome browser with features). Having a C++ program export raw data into a Node.js, browser-based program doesn't seem practical or possible at this time.

However, DB4S does have the ability to export data in json format that can then be imported as a file in VSC. The sql queries can be saved as *.sql files and then opened by any other text editor.

**Comment by qci-amos** [comment]
I'm sure I'm not following... I know I can get the image into vscode if I export to file from DB Browser. What I'm looking for is to streamline that and "push" the data from DB Browser to VSC. 

For example, a sketch of an implementation could be a button in DB Browser which:
1. saves the image to `/tmp`
2. runs `code tmp.png`

**Comment by qci-amos** [comment]
I just noticed that this could be the approach (i.e., note the temp dir) Windows Terminal takes for editing its `settings.json` file

![image](https://user-images.githubusercontent.com/45039789/83431111-d050c480-a404-11ea-9769-3e74fe9c7725.png)

**Comment by scottfurry** [comment]
^ - which is what I suggested above.

And why would anyone want to edit an image file in a text/code editor?
I still shudder at thinking about all the times I worked in binary/octal/hexidecimal arrays...flashbacks.

In another bug you filed, I pointed out that the raw binary blob in the cell editor could be copied to the clipboard then pasted into an _image editor_ (such as gimp or similar).

Any other "test-based files" can be processed easily in just about any text editor (MS notepad, notepad++ [https://notepad-plus-plus.org/], geany[https://www.geany.org/], VSC, ad nauseum).

What exactly are you trying to do here? What is the end-goal/effort to the streamlined workflow being suggested?

**Comment by qci-amos** [comment]
Ah, I figured out what I was missing from the other issue and closed it. To be clear, I'm not looking to edit the image (although I suppose some people may be interested in that) even though I'm referring to the the Edit Database Cell panel.

I'm looking for are more convenient ways to **view** the images than what's currently available in DB Browser's Edit Database Cell panel. VSCode has a decent way to view images (e.g., reconfigurable tabs, zoom, ) so those are the dots I'm connecting here.

**Comment by scottfurry** [comment]
There are a couple of fundamental tenets of software design.
- do one thing and do it well
- separation of concerns 

DB4S does this. It manages a GUI interface to easy access to an SQLite data store. What DB4S _does not do_ is impose what can/cannot be done with the data. That's a user concern.

Sure...there is a binary blob in a cell. What it represents is not a concern, but a user has access to it.

There are not enough resources to fashion DB4S into a "swiss-army-knife" like program for every conceivable use case. Cover the basics; allow people to use SQL statements on an SQLite database; move on.

If you absolutely intent on some kind of extra functionality, you're welcome to dig into the [VSC API's](https://code.visualstudio.com/api) and make a pull request here.

**Comment by qci-amos** [comment]
I understand!

I'd just humbly suggest rounding off your tenet of software design with another:
* to easily integrate with other tools that go beyond the "one thing" you do well.

The problem with GUIs is that users are always looking for ways to minimize the click-count in their workflows (with a CLI I could just write my own script). Maybe saying VSC in the issue title was too specific: more generically what I'm asking for is an "Open With..." export option in DB4S for the different kinds of data.

In any case, when I opened this issue, as I wrote in the other issue, I didn't know that I could copy the blob out of the cell. That accomplishes like 95% of what I was trying to do. Unfortunately, VSC does not accept a pasted image, but Powerpoint does and is probably a better choice now that I think about it, so I'll work with that for now.

**Comment by scottfurry** [comment]
> I'd just humbly suggest rounding off your tenet of software design with another:

Not my tenet's of software design. They are conventions accepted by distributions, developers.
They do not say "work with other tools". Not appropriate and leads to bike shedding.

I'm closing this before the philosophical debate ramps up. There are other tools/methods available but you want a one-stop-shop convenience that is out of scope for program.

**Comment by chrisjlocke** [comment]
Just derailing this slightly, but @qci-amos - what are you trying to achieve?
You've a SQLite database with images in BLOBS, which you're trying to view?  
I'm just wondering if a third-party application/CLI could be useful?  You mention VSCode, so assume you can program anyway - can't a quick 'n dirty application be built?

**Comment by qci-amos** [comment]
@scottfurry Thanks for considering it.

@chrisjlocke Think of me as a data scientist and this project is the first time I've used SQLite. I'm using SQLite for my own use to collect results from scientific calculations I run because I got tired of saving tons of json files everywhere and browsing them with VSC. When I want to analyze my data or do post processing, I load it into Jupyter (or write python) so I'm well covered there (and maybe Jupyter apps is the direction I need to take my project). But I also need a good table widget GUI (browse data, filter, sort, etc) and DB4S works very well out of the box.

I know from personal experience that making a good table widget is a lot of effort. I don't have a license for a commercial data analysis tools. Recommendations are welcome if I'm missing something.

**Comment by mgrojo** [comment]
@qci-amos Have you taken a look at the [3.12 alpha release](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.12.0-alpha1)? It includes this enhancement #1597, which allows you to open the data content of a cell in the default application for that data type (we only detect certain image types, json, xml, text and binary, in which case we add the ".dat" extension). That would serve your needs if your default application used for that data type is VSC. You should be able to change the default application using Windows or whatever OS you use.

**Comment by qci-amos** [comment]
@mgrojo No, I haven't tried the alpha release. That sounds like exactly what I was looking for. Thank you!
