### ISSUE TITLE
español

### ISSUE THREAD

**Issue by Lekkito** [sqlitebrowser/sqlitebrowser#2268]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by Lekkito** [comment]
Yes, sorry, I had a problem translating the program but I was able to solve
it. Sorry for posting it there, if you can delete it. Greetings and thanks
for asking

**Comment by justinclift** [comment]
No worries, glad you got it solved. :smile:
