### ISSUE TITLE
Grammar parser doesn't read foreign key column constraints

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#227]
```sql
CREATE TABLE test(
  id int,
  parent_id int REFERENCES test(id)
);
```
is equivalent to
```sql
CREATE TABLE test(
  id	int,
  parent_id	int,
  FOREIGN KEY(parent_id) REFERENCES test (id)
);
```
However, only the latter is fully read by our grammar parser. If you use the first version, DB4S will work but silently drop the foreign key clause when you edit the table definition.

**Comment by MKleusberg** [comment]
Should be fixed but any extra tests are welcome :)

**Comment by justinclift** [comment]
Awesome. :grin:

Should we set the milestone for this to 3.6, or leave it alone for now, in case more stuff comes up? :smile:

**Comment by MKleusberg** [comment]
Closing this as it's really old and nobody complained ;)
