### ISSUE TITLE
3.12.0-release candidate 1

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2273]
Am now merging the outstanding commits from `master` branch to `v3.12.x`, for then building the release candidate 1 binaries from.

So far, these ones are merged and seem ok (some needed minor editing to merge cleanly):

* #1968 - [Feature Request] Drop close buttons on every Execute SQL tab(x).
* #2153 - Show a useful icon in SQL tabs
* #2174 - Open SQL tabs for modifying views and triggers
* #2180 - Crash when -t option specifies missing table
* #2207 - Open a set of SQL-Files
* #2233 - Minor: Change "Filter in all columns" => "Filter in any column"
* #2235 - Avoid unchanged translation of keyboard shortcuts to work around problems
* #2240 - Rearrange preferences database
* #2270 - Application icon cleanup
* #2275 - Update to Windows Icon Generation script

~I'm not sure what needs to be done for this one.  Is there a commit in `master` I can merge, or set of them?~ :smile:

* ~#2178 - shortcut Strg + Enter doesn't work in 64-bit version~

~It seems related to #2235, which is already merged~.

**Comment by mgrojo** [comment]
@justinclift awesome!

#2178 is fixed by #2235, so it should be fine now.

**Comment by justinclift** [comment]
Thanks, I wasn't sure.

Is that the only stuff we need to merge before generating the new builds for Win and macOS?

I'm thinking we do that, and get people testing those.  Meanwhile we generate updated strings for translation and apply the new translation updates that come in.

That should mean we have a fairly well tested code base (v3.12.x branch) to generate the final release binaries from in a week or so.

**Comment by justinclift** [comment]
Hmmm, it's just about to hit 1am here.  I'll get some sleep now, and build the binaries in the morning.

If there are more changes that need cherry-picking to our `v3.12.x` branch, feel free to do them directly or leave a note here, and I'll get to them after I wake up.  Will build the rc1 binaries from there. :smile:

**Comment by MKleusberg** [comment]
Awesome :smile: Let me know when there are binaries for signing.

**Comment by justinclift** [comment]
@MKleusberg Any idea about #2200?  It's marked as a release blocker, but maybe it's not?

Similar thought for #2113, there seems to be an outstanding piece for that, but I'm not sure if that is something for another day (etc).

**Comment by justinclift** [comment]
@MKleusberg The binaries are ready to sign.  They're in the winXX-prerelease directories on the nightlies server. :smile:

**Comment by justinclift** [comment]
k, the release candidate build has been published. :smile:

**Comment by csanyipal** [comment]
> @MKleusberg Any idea about #2200? It's marked as a release blocker, but maybe it's not?
I just update my Sqlitebrowser here on Ubuntu. Now I am running this version of sqlitebrowser:
Version 3.12.99 (Jun 11 2020)
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.9.5
SQLCipher Version 4.3.0 community (based on SQLite 3.30.1)

The issue #2200 still exists. So in fact I can not use sqlitebrowser here, on Ubuntu 18.04.4 LTS

**Comment by justinclift** [comment]
@csanyipal Ouch, that's not good.  Looks like it still needs fixing after all. :frowning:

Ahh, just noticed your screencast in the original issue report.  That should help. :smile:

With the version numbering, `3.12.99 (Jun 11 2020)` means you're running our latest development code (`master` branch in git) rather than 3.12.0-release candidate 1.

**Comment by justinclift** [comment]
Oops.  As a data point, I typo'd the git tag name for the 3.12.0 release. `3.12.0`  vs `v3.12.0`.

Just fixed it - needed to force push tags and recreate the release here on GitHub.  Hopefully there's no residual weirdness. :scream:
