### ISSUE TITLE
Execute SQL button is disabled in Execute SQL tab despite database being open

### ISSUE THREAD

**Issue by CodingMaster06** [sqlitebrowser/sqlitebrowser#2274]
Details for the issue
--------------------

#### What did you do?
trying to create a table in SQL EXecute window. Let's me save and open saved SQL statements but the run/f5 option is not available or working

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by CodingMaster06** [comment]
Got it to finally work. Had to creates table using formbased method on Database Structure tab and then delete it before it would let me execute SQL code.

**Comment by justinclift** [comment]
Hmmm, that doesn't sound good.  It's not supposed to check if the tables already exist before running them. :frowning:

That being said, we've made a **lot** of changes since the 3.11.2 release, and are in the process of getting a new release out the door (likely next week).

Any interest in testing out the new pre-release binaries, and seeing if they have the same problem?  They should be pretty stable. :smile:

**Comment by chrisjlocke** [comment]
Just as a test, can you create a new database, cancel the 'create table' dialog, and see if the 'Run' button is enabled?
https://screencast-o-matic.com/watch/cY1ijmCnaJ

If you close the database and simply select it from the recent list, the buttons should appear again.

I tried this on 3.11.2 with no issues, but the above screencast was with a recent-ish nightly.

**Comment by chrisjlocke** [comment]
Also, I assume a database was actually open when you tried to enter/run SQL statements?  Just making sure... ;)

**Comment by chrisjlocke** [comment]
@CodingMaster06 - Have you had a chance to test the latest release candidate?
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.12.0-rc1

Either that, or one of the nightlies.
https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@CodingMaster06 - Feel free to comment back if needed.
