### ISSUE TITLE
Is my code wrong or is there some other reason I dont get the full result when using "Execute SQL"

### ISSUE THREAD

**Issue by Storesund445** [sqlitebrowser/sqlitebrowser#2285]
Hi,

Im tryind to search imdb database for names of actors and movies (for a project). 

My query is: SELECT * from people WHERE name = "John"; 

When doing this I get 9 results on John's, but if I check manually i'll find alot more John's than just nine. 

Am I doing something wrong (obviously)? Or is there some other reason my results are so limited. I'm new, so there's a big chance i'm doing some kind of newbeginner mistake. 

Thanks in advance. 

![104169055_304651420694141_7720627912092845353_n](https://user-images.githubusercontent.com/63971291/84626759-fe92d180-aee5-11ea-8bd8-4273df3ea593.jpg)
![104095654_2621995944739139_8052900738264171573_n](https://user-images.githubusercontent.com/63971291/84626774-03578580-aee6-11ea-8fcb-cfb34a9a77ba.jpg)
![104476007_262129185009602_6157829509652689547_n](https://user-images.githubusercontent.com/63971291/84626780-06eb0c80-aee6-11ea-8f40-1dcba2a93f92.jpg)

**Comment by justinclift** [comment]
Try this: :smile:

```
SELECT * from people WHERE name = "John%";
```

**Comment by scottfurry** [comment]
This is a common SQL type problem with SELECT queries based on strings.
When using wild card searches of strings, you need to change the conditional from `=` to `LIKE`.
See [this tutorial](https://www.sqlitetutorial.net/sqlite-like/) for more details.

**Comment by justinclift** [comment]
This might be helpful extra reference info too:

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters

**Comment by Storesund445** [comment]
Thank you, justinclift and scottfurry. Now it's working. This made my day! Slowly learning! :)

**Comment by justinclift** [comment]
You're welcome @Storesund445.  Keep at it. :smile:

**Comment by chrisjlocke** [comment]
> Adding `%` on the end should do the trick

Just a slight expansion on this.  Depending on what your original question is ... note your results contains 'Olivia Newton-John'.
Do you want people who's firstname is 'John' ?  Do you want 'John' as a surname, but not 'Johnson', etc?

So there are two 'comparison' operators - `=` and `like`.  If you search for `name = 'John'` then you will get an exact match.  If you search for `name like '%John%'` then you'll get any name where John appears in the name (which is how the filters work)

Note that `name = 'John'` is case sensitive (normally) while `name like '%John%'` isn't.

Also note that in SQL, quotation marks are used for column names, while single quotes are used for strings.
So `name="John"` actually means 'name equals the value in the 'John' column' 
SQLite is a bit helpful though, and in this instance, says, "aah, I didn't find a John column, so I guess you meant the text 'John' instead'.  But beware of this, as it could bite you on the bum ... so instead, use single quotes... `name='John'`
