### ISSUE TITLE
intellisense not appearing while writing query in Ver: 3.12.0

### ISSUE THREAD

**Issue by tojiamathewwork** [sqlitebrowser/sqlitebrowser#2290]
Details for the issue
--------------------

#### What did you do?
Usually when typing queries in the "Execute SQL" tab, you could see intellisense appearing with the table names, but after upgrading the SQLite DB Browser to ver 3.12.0 yesterday, i don't see the intellisense appearing.

#### What did you expect to see?
intellisense box while typing queries, especially while typing table name.

#### What did you see instead?
Didn't see an intellisense box while typing table name.

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by tojiamathewwork** [comment]
I see intellisense box is appearing, after few tries. Thank you

**Comment by chrisjlocke** [comment]
It should start appearing after typing the third character.
It should work on tables and views.
If you find it not working, please re-open this issue.
