### ISSUE TITLE
Allignment of last column in empty tables is wrong

### ISSUE THREAD

**Issue by Landcross** [sqlitebrowser/sqlitebrowser#2292]
Details for the issue
--------------------
In version 3.12, alignment of the last column in the data browser when viewing empty tables is a bit wrong. A picture says more than a 1000 words.
![image](https://user-images.githubusercontent.com/12005521/85207499-871bd280-b329-11ea-84c4-53a166895d0b.png)

This only happens on empty tables, and this only happens when viewing the table for the first time (since opening the database). If I go to another table and then back to the one from the picture, it looks fine, thus like this:

![image](https://user-images.githubusercontent.com/12005521/85207526-a4e93780-b329-11ea-9e6f-d48b45bf5742.png)

It's a *very* minor issue, but figured I'd report it nevertheless.

Useful extra information
-------------------------
#### What operating system are you using?
- Windows 10 Pro 64bit

#### What is your DB4S version?
- 3.12.0

**Comment by justinclift** [comment]
Interesting.  It kind of sounds like an off-by-one error when setting those headers. :wink:

Hopefully simple to fix. :smile:

**Comment by mgrojo** [comment]
@Landcross No idea why this is happening, but it doesn't matter now because #2188 has been implemented and the filters will be hidden in that situation. Could you give it a try using tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/)? It is important that the filter is only hidden when the table is empty, and not in any other case.

By the way,  #2353 and this are duplicates.

**Comment by Landcross** [comment]
@mgrojo I used the latest nightly build and the issue is indeed 'gone' because, as you said, the filters don't show anymore for empty tables so there's not a whole lot to misallign.

However, I do feel like a horizontal line at the bottom of the table headers would be nice to have. Now it kinda feels like something is broken or missing.

![image](https://user-images.githubusercontent.com/12005521/89624574-be711f00-d896-11ea-8aac-e3be56ec00cf.png)

**Comment by chrisjlocke** [comment]
> Now it kinda feels like something is broken or missing

Thats because the bottom border is on the filter row, which isn't visible.  Unsure if there's an easy fix... possibly remove the filter row and not 'hide' it...

**Comment by mgrojo** [comment]
Yes, it depends on the style. I switched between a dark style, which lacked a bottom line and  light one, which had. Removing the widgets instead of hiding them hasn't changed anything in this regard.

**Comment by mgrojo** [comment]
I think we can close this.
