### ISSUE TITLE
File type selector for blob import isn't working correctly on OSX

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#230]
Just tried importing an image file into a database field, but the file selector isn't working correctly.
![screen shot 2015-03-18 at 19 54 10](https://cloud.githubusercontent.com/assets/406299/6718086/0178777a-cda9-11e4-8cca-bf670016667e.png)
The "image" and "all" selectors aren't letting me select the .jpg files in the folder, as shown.

Something incorrect in the way the filters are constructed?

**Comment by samir-aguiar** [comment]
I think it's a Qt but on OS X, because it works on Fedora:

![save_as](https://cloud.githubusercontent.com/assets/3753623/6735536/1e5d94a4-ce5f-11e4-9fdf-c447a9f9bc13.png)

Will do some research when I get home :)

**Comment by samir-aguiar** [comment]
So this is really a (bug in Qt)[https://bugreports.qt.io/browse/QTBUG-38427]. It also affects version 4.8.5.

**Comment by justinclift** [comment]
Hmmm, looks like it's been sitting there unfixed for about a year. :frowning: 

As a workaround for us for now, maybe we should make the "All files (*)" filter the default?  That way people can at least select stuff.

I had to rename the file I wanted to use (an image) to .txt, just so I could recognise it.  Doesn't seem fantastic. :wink:

**Comment by samir-aguiar** [comment]
The files become clickable if you leave and enter the directory again after changing the filter.
Another workaround is not use the native file dialog. That works, but it will look a little bit weird.
Or perhaps subclass QFileDialog and force a refresh when changing filter, but might be too much for something not so critical.

**Comment by justinclift** [comment]
Hmmm, if subclassing works... how much effort would it be?  Wouldn't it inherit pretty much everything (hopefully)?

Just thinking that from a user perspective, that's the only fix that would completely work atm. :frowning:

**Comment by samir-aguiar** [comment]
Done :smiley:

**Comment by justinclift** [comment]
Thanks, that's working perfectly. :smile:
