### ISSUE TITLE
Missing 'Add Record'  'Delete Record'

### ISSUE THREAD

**Issue by RutagerD** [sqlitebrowser/sqlitebrowser#2301]
Details for the issue
--------------------

Downloaded and installed v 3.12.0 x86_64
Qt Version 5.12.8
SQLite Version 3.32.2

Browse Data Tab.  Usually has the Add Record, Delete Record buttons

Did not see the buttons.  Needed to reinstall older version. Am I just missing something?

Win 10 Desktop V 1903
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
It should be the first and second icon in the third group of icons.

![image](https://user-images.githubusercontent.com/7872218/85762617-cf613900-b70b-11ea-8cd6-93d00985e644.png)

If you hover your mouse over them, they should also say, "Insert a new record......." etc.

![image](https://user-images.githubusercontent.com/7872218/85762698-e6079000-b70b-11ea-8a85-a96a215c443c.png)

If you don't see these buttons, can you provide a screenshot?

**Comment by RutagerD** [comment]
Great.  Thanks for the retraining 🙂

________________________________
