### ISSUE TITLE
Brew install returning a 404 not found

### ISSUE THREAD

**Issue by moosecanswim** [sqlitebrowser/sqlitebrowser#2302]
Details for the issue
--------------------

#### What did you do?

`brew cask install db-browser-for-sqlite`

#### What did you expect to see?

brew to install db-browser-for-sqlite

#### What did you see instead?

```
==> Downloading https://github.com/sqlitebrowser/sqlitebrowser/releases/download/3.12.0/DB.Browser.for.SQLite-3.12.0.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'db-browser-for-sqlite' with message: Download failed: https://github.com/sqlitebrowser/sqlitebrowser/releases/download/3.12.0/DB.Browser.for.SQLite-3.12.0.dmg
```

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ x] macOS: ( _version:_ 10.14.6___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oops.  That's my fault.  I typo'd the git tag name when creating the release, and fixed it a few hours ago. :frowning:

The updated download url - if downloading from GitHub - is now: https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.0/DB.Browser.for.SQLite-3.12.0.dmg

That being said, the GitHub url is mostly just a mirror for convenience.  The official download url is: https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.12.0.dmg

Um... do you want to let the Homebrew people know about the change?  If not, I can do it. :smile:

**Comment by justinclift** [comment]
Looks like this was fixed in https://github.com/Homebrew/homebrew-cask/pull/85039. :smile:
