### ISSUE TITLE
Retain Executed SQL Queries

### ISSUE THREAD

**Issue by joshuambg** [sqlitebrowser/sqlitebrowser#2303]
Describe the new feature
--------------------------
We have the ability to save Execute SQL to a file. 

Asking for feature to retain the executed queries even after application close. When a database is loaded, the program remembers the previous SQL "tabs" that were open and loads them with the database.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Unknown

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No

**Comment by chrisjlocke** [comment]
There is this feature already.  You can save a 'project' which saves the database location and the 'Execute SQL' tabs.

From the File menu, select 'Save Project'.  You'll be prompted to save a file with a .sqbpro extension.  This can live anywhere - not necessarily with the database.

![image](https://user-images.githubusercontent.com/7872218/85829433-839da680-b782-11ea-996f-d24f1aeb8d3f.png)

**Comment by chrisjlocke** [comment]
Yell if this doesn't work for you, or wasn't exactly what you intended...
