### ISSUE TITLE
Sort arrows are wrong direction

### ISSUE THREAD

**Issue by harrisrap** [sqlitebrowser/sqlitebrowser#231]
The arrows in the column headings to indicate sort direction are incorrect.  They are the opposite of what they should be.  An upward facing arrow means the sort is from smaller to bigger (or alphabetic).  A downward facing arrow means the sort is from bigger to smaller (or reverse alphabetic).  
Take a look at the arrows in the column headers of folders on a PC or a Mac, or in Outlook, or any other common software that allows sorting by columns, and you will see they are using them the way I am describing, which is the opposite of how you are.

**Comment by justinclift** [comment]
I'll check this out tonight too. :smile:

**Comment by justinclift** [comment]
Hmmmm, on OSX 10.9 here, and it doesn't seem to be wrong for me.  For example, the sort column here is the "hour" column.  The little arrow is pointing downward which should mean biggest to smallest, and the sort order is doing that:
![screen shot 2015-03-19 at 23 53 55](https://cloud.githubusercontent.com/assets/406299/6743547/3c5c720c-ce93-11e4-850d-cd15d9c57855.png)
It seems to be correct in the other direction too:
![screen shot 2015-03-19 at 23 55 18](https://cloud.githubusercontent.com/assets/406299/6743565/6bd9c21e-ce93-11e4-8026-cf22326e145c.png)
If it's not doing this for you, are you ok to screenshot the problem?

**Comment by harrisrap** [comment]
![screen shot 2015-03-19 at 10 03 04 pm](https://cloud.githubusercontent.com/assets/5605944/6746358/11ddd606-ce84-11e4-948f-348d0863c272.png)
![screen shot 2015-03-19 at 10 03 30 pm](https://cloud.githubusercontent.com/assets/5605944/6746359/11f58364-ce84-11e4-8e35-23688efddb50.png)

**Comment by justinclift** [comment]
Interesting.  What data type is the parent_list_id field defined with there?

**Comment by harrisrap** [comment]
![screen shot 2015-03-20 at 5 36 46 am](https://cloud.githubusercontent.com/assets/5605944/6751612/2c247f4e-cec3-11e4-8719-f4b73205fc4f.png)

**Comment by Z4us** [comment]
INT = short for INTEGER it's written full in 'list_id' to make it (synonym) of ROWID

ref. https://www.sqlite.org/lang_createtable.html#rowid

**Comment by harrisrap** [comment]
It is sorting incorrectly for list_id too

![screen shot 2015-03-20 at 6 59 39 am](https://cloud.githubusercontent.com/assets/5605944/6752832/b94f72f6-cece-11e4-842a-3b5dad50dabb.png)

**Comment by Z4us** [comment]
The arrow shows the order you can change the current one to so the opposite of what is the "status quo"

**Comment by samir-aguiar** [comment]
Ok, I think I got this fixed.
Apparently the problem happened when opening a table for the first time (either by opening a database file or switching tables) and clicking on a header. Then the data were sorted correctly (based on the order from the SQL query), but the arrow was upside-down.
Would be great if you could do some tests :smile:

**Comment by justinclift** [comment]
Awesome @samir-aguiar. :grin: 

Just tried out the behaviour for this before-vs-after, and yeah, you guys are right.  Here's a sort showing the wrong order (from the commit right before this one):
![screen shot 2015-03-22 at 20 49 40](https://cloud.githubusercontent.com/assets/406299/6771413/0ebb98e8-d0d5-11e4-850a-b852a90b2d5c.png)
and the opposite direction:
![screen shot 2015-03-22 at 20 51 30](https://cloud.githubusercontent.com/assets/406299/6771421/3d943508-d0d5-11e4-9d77-ad008665e938.png)
Here's the same thing, but compiled with the fix:
![screen shot 2015-03-22 at 20 54 26](https://cloud.githubusercontent.com/assets/406299/6771439/ab0639d8-d0d5-11e4-8eb2-1e6e664bfa96.png)
![screen shot 2015-03-22 at 20 55 00](https://cloud.githubusercontent.com/assets/406299/6771443/b719604c-d0d5-11e4-8f77-574c53f1cb88.png)
Seems good now. :grinning:

@harrisrap Would you have a few minutes to try out the nightly build (tomorrow), and let us know if that works properly for you? :smile:

**Comment by justinclift** [comment]
@harrisrap ping? :smile:

**Comment by harrisrap** [comment]
Sorry, I don’t see how to install the nightly build.  Instructions please?

From:  Justin Clift <notifications@github.com>
Reply-To:  sqlitebrowser/sqlitebrowser
<reply+00558a38a1be9e9cea4eaae9d10d9f7d4a8ec1551e9469ac92cf00000001112970e69
2a169ce03c0d70d@reply.github.com>
Date:  Tuesday, March 24, 2015 at 11:37 AM
To:  sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc:  Harris Rappaport <harris@harrisrappaport.com>
Subject:  Re: [sqlitebrowser] Sort arrows are wrong direction (#231)


@harrisrap <https://github.com/harrisrap>  ping?

—
Reply to this email directly or view it on GitHub
<https://github.com/sqlitebrowser/sqlitebrowser/issues/231#issuecomment-8563
6056> .

**Comment by justinclift** [comment]
No worries. :smile:

1. Remove the existing DB4S / SQLite Browser application from your /Applications list.

2. Grab the .dmg here:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/nightly/sqlitebrowser_20150325.dmg

3. Open that dmg file (double click on it in Finder), then drag-n-drop the sqlitebrowser.app file to your /Applications folder.

In theory, that should install the latest nightly build.  If it doesn't for some reason, let us know. :smile:

**Comment by harrisrap** [comment]
Eureka!  You did it.  Sort arrows are working perfectly now.  Nice work
gentlemen.

From:  Justin Clift <notifications@github.com>
Reply-To:  sqlitebrowser/sqlitebrowser
<reply+00558a389fdf40b4d4348be19551238009be3ecf26363cb192cf00000001112a41c49
2a169ce03c0d70d@reply.github.com>
Date:  Wednesday, March 25, 2015 at 2:28 AM
To:  sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc:  Harris Rappaport <harris@harrisrappaport.com>
Subject:  Re: [sqlitebrowser] Sort arrows are wrong direction (#231)


No worries. 
1. 
2. Remove the existing DB4S / SQLite Browser application from your
/Applications list.
3. 
4. Grab the .dmg here:

    
http://mirror.salasaga.org/sqlitebrowser/nightly/sqlitebrowser_20150325.dmg
1. Open that dmg file (double click on it in Finder), then drag-n-drop the
sqlitebrowser.app file to your /Applications folder.
In theory, that should install the latest nightly build.  If it doesn't for
some reason, let us know.

—
Reply to this email directly or view it on GitHub
<https://github.com/sqlitebrowser/sqlitebrowser/issues/231#issuecomment-8595
2160> .

**Comment by justinclift** [comment]
Awesome. You've nailed another one perfectly @samir-aguiar. :grin:

@harrisrap Thank you very much for reporting the problem, and verifying the fix.  It really helps. :smile:
