### ISSUE TITLE
Text in column is outlined on the right instead of the left

### ISSUE THREAD

**Issue by Landcross** [sqlitebrowser/sqlitebrowser#2315]
So, I just noticed in a database that I'm using that in the new release 3.12 I have a column with text that for some mysterious reason aligns to the right instead of to the left.

I don't really wanna post a screenshot here in public because of the data in there, but it shouldn't be that hard to imagine what a right-aligned column of text looks like ;)

I have no idea why this specific column aligns on the right. Sorting it doesn't change it either. And it's reproducible, if I close and reopen the db, the same column aligns to the right. However, I also have a view that joins two tables and selects a few columns, including the right-aligned column. And in that view, the same column with the same data is aligned to the left (as it should be).

I'm using the latest version 3.12 on Windows 10 64 bit.

**Comment by chrisjlocke** [comment]
Can you post the schema of that column?  Is it text, but has numeric data?  Or vice-versa?  Whats the name of the column?  I'm 99.9999999999999% certain that DB4S makes no assumptions based on the name, but it might have a freaky name which is confusing the SQL parser.  Do any other fields have any wacky characters in them?  No weird encoding or characters in anything?
If you right-click the column and select 'Display format', what is currently set?

![image](https://user-images.githubusercontent.com/7872218/86226291-5aff1d80-bb83-11ea-8c63-1c0772dbaf40.png)

**Comment by Landcross** [comment]
*facepalm*, I'm terribly sorry. Apparently the column was set to INTEGER instead of TEXT. I'm sure it was was TEXT before, cause I dug up an older backup. I must've accidentally changed it to integer when I was changing the schema a little while ago. I changed it back to text and it looks fine now. Kinda weird how the table and view displayed it differently though. Nevertheless, my fault. Sorry for the unnecessary report.


As a side-note: I find it personally pretty annoying that one can scroll through the datatypes without selecting the dropdown when creating/editing a schema. I've oftentimes accidentally changed datatypes like that; I want to scroll down in the list of columns, but my mouse happens to over over the dropdown and I change datatypes instead of scrolling down. Maybe that was the cause of this too. But nevertheless, that's besides the point ;)

**Comment by chrisjlocke** [comment]
Glad you got it resolved.
The datatypes is pretty much a 'suggestion' as far as SQLite is concerned.  if you set something as numeric but put 'Banana' in it, SQLite will put in 'Banana' and not the numeric equivalent (eg, 0).  

What would be cool, if there was a schema checker.  Or DB4S highlighted on the schema tab that 'You set this column to Integer, but it has text values in it' or vice versa.  On a database with a million rows though, that could slow things down.  Ignore me.  Silly idea.  😉

**Comment by mgrojo** [comment]
If we can figure out some SQL code for checking that, we could add it to
the tools menu, in a similar way than the other checks.

**Comment by chrisjlocke** [comment]
Would you be able to do it in SQL?  You'd have to find the column name, the column type, then rattle through all values in that field, blah blah .... could be quite a task.,..,

**Comment by justinclift** [comment]
The code for doing the check is likely the same stuff @MKleusberg wrote for autodetecting data types in the CSV import a while back.
