### ISSUE TITLE
Hello, that database when i open it opens empty without data.

### ISSUE THREAD

**Issue by NasserAnasser** [sqlitebrowser/sqlitebrowser#2319]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
What database are you trying to open?  Where did you get the database from?  Is this one online, or one that you made?
Are you sure it is meant to contain data, and isn't just the schema (the structure of the database) and its just a template?
Have you opened this database OK before?
Do you have a backup of it?
What operating system are you using?
What version of DB4S are you using?

**Comment by chrisjlocke** [comment]
I'll close this, as I suspect its not a genuine question, but please provide more information, and we can reopen it.
