### ISSUE TITLE
[Dark Theme] Preferences - SQL <-- missing critical elements.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2320]
Details for the issue
--------------------
Please add more editor elements to render Dark Themes more visible.
  The cursor is invisible in Dark Mode when landing on either side of a () or [] or {}.
  I have to guess where I am. :(
Ex.
  Selection Text Foreground/Background [#f0f0f0]
  Cursor Foreground/Background             [#ff00ff]
#### What did you do?
Preferences - General - Application style - Dark style
#### What did you expect to see?
Cursor blinks brighter or darker than background/foreground combination.
#### What did you see instead?

Useful extra information
-------------------------
#### What operating system are you using?
- [x] Windows: ( _version:_10 Pro latest___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___
#### What is your DB4S version?
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: ___3.12.99 v200603
#### Did you also
- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
> The cursor is invisible in Dark Mode when landing on either side of a () or [] or {}.
> I have to guess where I am. :(

Ouch. :frowning:

**Comment by mgrojo** [comment]
This is related to #2203 and should be addressed at the same time.

**Comment by justinclift** [comment]
Interesting.

**Comment by mgrojo** [comment]
Yes, the brace matching colours are set to black on white. In light mode, it cannot be seen when outside the highlighted (grey) current line. In dark mode, it is always visible, but makes the cursor invisible, because it uses the same colour as the background.

So I'm planning to add a new setting for the brace matching background (and mayb foreground). But for selection it seems too much, since the default provided by the OS should be sensible. @sky5walk, why do you think it's needed?

**Comment by mgrojo** [comment]
@sky5walk I've added the possibility of changing the brace highlighting colour and the selection foreground and background colours. Default for highlighting has been improved and adapted to the dark or light style. Defaults for selection are got from the desktop style as before. Could you confirm it works for you using tomorrow's nightly build?

**Comment by sky5walk** [comment]
Nice!
No more guessing where my cursor is. I am lousy gambler.

**Comment by justinclift** [comment]
Wondering if the colour is something we could automatically calculate correctly every time?

Maybe something like the steps mentioned in the answer (not question) here?

&nbsp; &nbsp; https://stackoverflow.com/questions/1165107/how-do-i-invert-a-colour#1165145

eg convert the colour from RGB to HSV, invert the Hue value, then convert it back to RGB?

**Comment by sky5walk** [comment]
Ok, this is an improvement. I can tell where I am if I squint hard.
I still cannot change the color of the blinking cursor? 
It follows the foreground color.
It would be more direct to set the cursor color bright red on the dark style.

**Comment by sky5walk** [comment]
Works well enough. Please close ticket.
