### ISSUE TITLE
laravel artisan migrate:fresh --seed, not show new rows in sqlitebrowser

### ISSUE THREAD

**Issue by dotus-ru** [sqlitebrowser/sqlitebrowser#2322]
Details for the issue
--------------------

#### What did you do?
When i  perform artisan command "php artisan migrate:fresh --seed" in laravel i expect see in sqlitebrowser **new** 5 rows from laravel seeder with command factory(\App\User::class, 5)->create(); , but i see rows from old seeding, same name, same emails and time created_at, button refresh and f5 not help see new seeded lines.  New lines appear only when sqlitebrowser restart or artisan command perform separately php artisan migrate fresh, php artisan db:seed. 

When i settings up seeder to random count of rows factory(\App\User::class, **rand(1, 10)**)->create(), new seeded rows are shown after f5 is expected to. I try latest ant prelatest version of sqlitebrowser, laravel 7 and 5.8, same problem. 

When i check database after seeding using eloquent query, new lines always present in database, but sqlitebrowser not show updated lines until database was reopened or program restarted. 

_sorry for my English_

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X ] Windows: ( _version:7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0
- [Х] 3.11.x
- [Х ] Other: 3.9

#### Did you also

- [X ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  That **should** work.  Obviously it's not though. :frowning:

As a thought, are you able to try our recent 3.12.0 release?

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-12-0-released/

We improved a **lot** of stuff in that.  There's a decent chance it'll work. :smile:

**Comment by dotus-ru** [comment]
Yes, i try 3.12 , same behaviour. But, try built-in phpstorm sqlite viewer... same problem - when seeding same count of rows, new rows not appear after f5 but dump of database User::all() view new lines. sqlite viewer show new lines after f5 only if count of seeded lines not same count of previous seeding. maybe problem not in sqlitebrowser. Sorry

**Comment by justinclift** [comment]
No worries.  Hopefully you find a good solution. :smile:
