### ISSUE TITLE
“DB Browser for SQLite.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by rubencanlas** [sqlitebrowser/sqlitebrowser#2324]
Details for the issue
--------------------

#### What did you do?
Updated to the latest version from the old version of DB Browser. My old version was installed using Mojave MacOS. Then I upgraded to Catalina and this happened.

#### What did you expect to see?
To run DB Browser (it was working a few seconds ago, then i decided to update).

#### What did you see instead?
This error: "“DB Browser for SQLite.app” can’t be opened because Apple cannot check it for malicious software."

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version: Catalina )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yeah, we need to update our release process on macOS to include a new "Notarize" step next time around. :wink:

In the meantime, this Apple support doc shows how to launch the application anyway:

&nbsp; &nbsp; https://support.apple.com/en-us/HT202491

It's pretty much just going into macOS System Preferences and confirming it's ok to launch. :smile:

**Comment by rubencanlas** [comment]
Thanks for the quick response! It looks like Catalina reset my Preferences
back to stricter permissions. Will re-open it.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by rubencanlas** [comment]
It worked! So there's an extra step in Catalina now and it's a bit
confusing, plus the support article wasn't showing up in my search. Thanks
again.


..............................................................
RUBEN CANLAS JR.
Agile Coach
..............................................................
“Computers are useless. They can only give you answers.” -- Pablo Picasso
