### ISSUE TITLE
Data updated through external source does not refresh

### ISSUE THREAD

**Issue by john2014** [sqlitebrowser/sqlitebrowser#2325]
Here are the steps:

1. Open your database using sqlite browser version 3.12
2. Now using your favorite programming language (c#, php etc) make changes to the table (eg adding a new column) and optionally run the vacuum command
3. Once the program have finished updating the table, click refresh on sqlite browser

Expected: The sqlite browser should show table with new column added by external program.
Actual: There are no changes to the table.

It was working fine in version 3.11 where refreshing sqlitebrowser would reload the table and show new column. This bug seems to be introduced in this version.

**Comment by MKleusberg** [comment]
Thanks for reporting this! Can you try again with tomorrow's nightly build? Hopefully it's fixed in that version :smile: You will find it [here](https://nightlies.sqlitebrowser.org/latest/). In the meantime you can try pressing <kbd>F5</kbd> instead of clicking the refresh button.

**Comment by justinclift** [comment]
@MKleusberg From (#2331), it sounds like that commit should be added to 3.12.1 as well. :smile:

**Comment by chrisjlocke** [comment]
Just a nod that this now works OK.
https://screencast-o-matic.com/watch/cYiTFvEyc0
