### ISSUE TITLE
Adding in a new tab called Dashboard

### ISSUE THREAD

**Issue by yindrew** [sqlitebrowser/sqlitebrowser#2326]
So I'm attempting to add a new tab into the mainTab in MainWindow. I added it in but when I run the program nothing shows up. I'm a graduating high school senior, so I don't really know a lot of the technical language. If anyone could help me, it would be greatly appreciated.

![IssueForProject](https://user-images.githubusercontent.com/61204939/87189003-d799a680-c2bd-11ea-8b63-71b04519a344.png)

![WhyDoesntItwork](https://user-images.githubusercontent.com/61204939/87189011-de281e00-c2bd-11ea-8e25-49ce8449fb52.png)

**Comment by mgrojo** [comment]
Maybe the new tab it's hidden. You have to add some code and attributes to add a new tab, so it can be shown, hidden and its visibility status saved to a project file. These commits might help you:
- 4f9c21f83f14dda3478bf952b90f453f38f6f5ab Closable main tabs and saving automatically open tabs and order 
- 544ed812e28d4b07867180792143497a1f6b2b3e Reset Window Layout, positional shortcuts for tabs and avoid statusTip 
- 3d4601c8ef21895ee98900c59dd9cf4d7a1eb8aa This is part of a pull request to add a new Diagram tab. Check changes in MainWindow.cpp and MainWindow.ui

**Comment by mgrojo** [comment]
Are you trying to implement something like  #2216?

**Comment by MKleusberg** [comment]
Another idea is to implement it as a dock (just like the Plot dock for example). The code for a dock usually is a bit more independent from the rest of the code which can make it easier to add a new one.

**Comment by yindrew** [comment]
@MKleusberg @mgrojo 

My end goal is to implement a new tab called dashboard that's able to display multiple graphs all at once. So in this process, creating a new tab is the first step. I looked over 4f9c21f 544ed81 3d4601c, but it doesn't seem to work. I think I might try implementing it as a dock. Thank you for the help.

**Comment by justinclift** [comment]
@yindrew Is the code you're trying with online somewhere, so we could potentially look and see if there's anything obviously wrong? :smile:

**Comment by mgrojo** [comment]
@yindrew Is it appearing in the View menu? Maybe it is just hidden.

**Comment by yindrew** [comment]
@justinclift I have a repo for it here https://github.com/yindrew/sqlitebrowser  
@mgrojo I don't even know what the view menu is...

**Comment by mgrojo** [comment]
I checked your repository and the problem is about accessibleName. You need to set it to the tab title. With these changes your tab will appear:

```diff
diff --git a/src/MainWindow.ui b/src/MainWindow.ui
index fc5977d7..e780cc45 100644
--- a/src/MainWindow.ui
+++ b/src/MainWindow.ui
@@ -37,7 +37,7 @@
     <item alignment="Qt::AlignHCenter">
      <widget class="QTabWidget" name="mainTab">
       <property name="currentIndex">
-       <number>3</number>
+       <number>0</number>
       </property>
       <property name="movable">
        <bool>true</bool>
@@ -735,6 +735,9 @@ You can drag SQL statements from an object row and drop them into other applicat
        </layout>
       </widget>
       <widget class="QWidget" name="dashboard">
+       <property name="accessibleName">
+        <string>Dashboard</string>
+       </property>
        <attribute name="title">
         <string>Dashboard</string>
        </attribute>
```

**Comment by yindrew** [comment]
@mgrojo ur the best

**Comment by yindrew** [comment]
@mgrojo I tried changing the code like you told me too, but it still doesn't display. Do you have any idea why it still wont work?

**Comment by mgrojo** [comment]
No, it worked for me. Have you changed anything else? I only changed those lines from your repository and rebuilt.

**Comment by yindrew** [comment]
I rebuilt the program, but the issue persists. I'm running Ubuntu 16.04 and QT 5.5. Could that possibly be the issue? Did you change anything else as well? 

Did you build your executable in QT or in CMD line? Feeling awfully confused about why its not getting built. @mgrojo

**Comment by yindrew** [comment]
![accessibleName](https://user-images.githubusercontent.com/61204939/88424862-54e41180-cdbc-11ea-9dec-5b11abb5b191.png)

**Comment by mgrojo** [comment]
Yes, that should be enough to make it work. Why don't you push your changes to your repository and I check it whether it works for me or what is wrong?

**Comment by yindrew** [comment]
@mgrojo got it. I just pushed my repository. thanks.

**Comment by mgrojo** [comment]
The change is correct. Since you have window settings from the previous version, you have to press Alt+0 to restore window layout or choose the Dashboard option in the View menu of the application menu-bar.

**Comment by yindrew** [comment]
@mgrojo what would I do without you in my life

**Comment by justinclift** [comment]
@yindrew I'm guessing you'll be doing a lot more development work getting your Dashboard idea working.

When you're happy with it, would you be ok with having it added to the main program here as well?  Depending on what it ends up like, if the code quality seems ok, if it seems useful for lots of people, etc. :smile:
