### ISSUE TITLE
'Unable to open database file' error when selected 'Public' from the Remote dock

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2327]
Opened the 'Remote' pane, selected 'Public' and got an error - 'Unable to open database file'.

![image](https://user-images.githubusercontent.com/7872218/87217969-9bf6ef00-c346-11ea-8ba6-143362b11a17.png)

The list of public databases did display though.
The nightly from 6 Feb doesn't exhibit this behaviour.

Started another copy of DB4S and it did it again, so wasn't like it had to download something and was now OK...

This was on the 11 Jul nightly...

**Comment by chrisjlocke** [comment]
Oops.

**Comment by justinclift** [comment]
Oops?

**Comment by MKleusberg** [comment]
Hmm, in theory (!) I didn't change anything related to that. Can you check the ```remotedbs.db``` file and see if it is somehow broken? You should find it in ```C:\Users\<USER>\AppData\Roaming\DB Browser for SQLite\remotedbs.db``` or some similar path (the ```AppData``` directory might be hidden too). It should just open in DB4S. If it doesn't I'd assume it's corrupt due to a crash or something.

**Comment by chrisjlocke** [comment]
We need a button to open this database in DB4S 😉

**Comment by chrisjlocke** [comment]
I don't have that path...

![image](https://user-images.githubusercontent.com/7872218/87243293-cf13ae00-c42c-11ea-8f8c-6dabbb293b45.png)

Searched for 'remote*.db' too...

![image](https://user-images.githubusercontent.com/7872218/87243330-169a3a00-c42d-11ea-8287-e982bb559943.png)

**Comment by MKleusberg** [comment]
Not sure about the button as it's supposed to be an internal database. Changing its values would confuse DB4S so better hide the database :wink:

But better error handling, yes definitely. Let's try to figure out what happens in your case and handle this more gracefully.

**Comment by MKleusberg** [comment]
Ok, I got it. The problem is that the directory doesn't exist. So we have to create it first, then create the database file. Not sure why it worked before though but at least it's easy to fix :smile:

**Comment by chrisjlocke** [comment]
Is this linked to this error?  Trying to open a public database (any random one) and while it downloads OK (or appears to) DB4S then says, "Er, what database do you want to open?"
I thought it might be asking "Where do you want to save it?" but its asking to open one.
http://somup.com/cYil6fQLkk

**Comment by MKleusberg** [comment]
Yes, this should be linked to this issue. By default databases are downloaded into the same directory and this probably fails for the same reasons. So when trying to open the downloaded database DB4S can't find it and when it doesn't find a database it's asking you where it is.

**Comment by chrisjlocke** [comment]
Makes sense.  Wonder how that got deleted.  I can understand if I'd just run the .ZIP install or portable, but I have got it installed.  Thats a point.  Portable version.  Guess we need an option of where to save temporary stuff... eurk.

**Comment by karim** [comment]
I'm having the same problem as Chris.

Also..

![2327](https://user-images.githubusercontent.com/8761081/87244211-f02fcb00-c43b-11ea-972e-56b630e07edf.png)

Is `sqlitebrowser` in the path necessary?

**Comment by chrisjlocke** [comment]
Changed my location, double-clicked on a database, and the same 'open dialog' appeared.

![image](https://user-images.githubusercontent.com/7872218/87276631-a812b600-c4d8-11ea-88a3-c44e7e153118.png)

**Comment by MKleusberg** [comment]
Ok, the directory should be created automatically on the first use now. Can you try again? :smile: 

@karim The ```sqlitebrowser``` part isn't strictly necessary. But it's generated this way by Qt and changing it manually would make things way more complicated :smile:

**Comment by MKleusberg** [comment]
@chrisjlocke Is it working for you now?

**Comment by chrisjlocke** [comment]
Yes for both - directory is created, and double-clicking a database now opens it (sans error).
The only /minor/ point is the directory shown uses the wrong slashes.  

![image](https://user-images.githubusercontent.com/7872218/87854263-a4cc5f80-c908-11ea-8b2e-20b926eef754.png)

But that's like moaning that the teaspoon provided with a cup of coffee that someone has made you is the wrong colour ;)

**Comment by MKleusberg** [comment]
Thanks for pointing this out. It should be fixed in the next nightly build. Want to give it a try? :smile:

**Comment by chrisjlocke** [comment]
Looks good in Windows.  👍
