### ISSUE TITLE
read only mode buggy

### ISSUE THREAD

**Issue by jadeiX** [sqlitebrowser/sqlitebrowser#2331]
Details for the issue
--------------------

#### What did you see instead? DBBrowser the column names are not assigned to the correct data. Sometimes the table is not updating at all 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
This is similar to #2325 and a fix has been put in the nightly code.  If you try the nightlies (https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds) this might work better.

**Comment by chrisjlocke** [comment]
I see you've closed it, but if the pressing-of-F5 or the nightlies doesn't help, please yell back.

**Comment by jadeiX** [comment]
from what I see currently it is working well. I will let you know if I see another issue. 
thank you for the prompt follow up
