### ISSUE TITLE
Remote pane causing application crash in dev code (bisected)

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2333]
Stumbled into an interesting crash of DB4S today, while adjusting the DBHub.io code to display the user home directory first in the list-of-all-directories.

"Something" is going wrong with DB4S in this commit onwards: 5cdda28608c4e70090d1d3b7e69ded1c822c52dd

It'll happy load the current JSON "list of users with public databases", but the list returned from my local development DBHub.io instance causes it to immediately crash. :frowning:

At first, I thought it was a problem with the JSON being generated by my local dev setup.  But no, that's fine:

[docker-rootdir.json.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/4940927/docker-rootdir.json.txt)

* Then tried the 3.12.0 release.  No crash. :sweat_smile:
* Then tried the v3.12.x branch.  No crash.

So, manually bisected things to figure out where the crash in our development code starts.  5cdda28608c4e70090d1d3b7e69ded1c822c52dd introduced the crash.

Note that the bisecting was a little complicated, as the updated certificate and port number adjustment code (3 commits) needing to be applied each time so DB4S would talk to the local development server. :wink:

Two branches of interest:

* [db4s-bisect-v1-working](https://github.com/sqlitebrowser/sqlitebrowser/tree/db4s-bisect-v1-working)
* [db4s-bisect-v3-busted](https://github.com/sqlitebrowser/sqlitebrowser/tree/db4s-bisect-v3-busted)

Ignoring the first three commits in each, they are 1 commit different.  That commit is the crasher.

For triggering the crash:

* Most of the time It just needs the appropriate local development cert to be selected.
* Sometimes however it only happens after clicking the drop down arrow widget next to the username, to show the available databases for that user.

One interesting observation, is that if the proper production server is selected first (eg the remote list is pulled from that), then switching to the local development server cert won't then cause a crash.  The crash only happens when freshly starting DB4S, then selecting the local development cert.

**Comment by justinclift** [comment]
@MKleusberg Pretty sure you'll be interested in this. :smile:

**Comment by justinclift** [comment]
Just triggered the crash while running DB4S (compiled from that `db4s-bisect-v3-busted` branch) under Qt Creator in Debug mode.

It crashes here:

![2020-07-18-Qt_Creator-DB4S_crash_when_loading_remote_database_list_json](https://user-images.githubusercontent.com/406299/87842325-1bf4fa00-c8ef-11ea-8750-28150c0a1bc8.png)

**Comment by justinclift** [comment]
As a data point, it seems to be related to only having a single entry returned in the JSON list.

After adding a 2nd user (with public database) to the local development environment, the crash also goes away.

**Comment by MKleusberg** [comment]
I only got it to crash once every ten runs or so. But I think I found the problem and could fix it. Can you try again and see if it's working for you as well? Thanks for bisecting by the way! Initially I couldn't believe this is the right commit and it turned out to be correct and definitely helped a lot :smile:

**Comment by justinclift** [comment]
Awesome, yep the crash is now gone.  It used to happen every time, now it doesn't crash.  Tested ~15 times.

Thanks heaps @MKleusberg. :smile:

**Comment by MKleusberg** [comment]
Awesome. This should definitely go into the 3.12.1 release then (or maybe all the DBHub.io related commits should go in there because that code isn't used that often anyway and probably wouldn't break anybody's routine).

**Comment by justinclift** [comment]
Yeah, if we can get all the DBHub.io stuff in 3.12.1 it'd be really good.  Lots of useful changes there. :smile:

Would you be ok to cherry-pick the commits across?

If so, you might need to wind the head of `v3.12.x` back a few first, as I added the port number changing + updated docker CA cert commits earlier on today.

**Comment by MKleusberg** [comment]
Yes, I can do that :smile: I'll wait until before the release though so I don't have to remember where I finished cherry-picking before :wink:
