### ISSUE TITLE
Windows nightlies unavailable

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2335]
The windows nightlies seem unavailable.  Out of disk space again? 😉 

![image](https://user-images.githubusercontent.com/7872218/87851361-eb619000-c8ef-11ea-82c9-78b9ddc181d0.png)

**Comment by MKleusberg** [comment]
The 22 bytes size probably means there's a build error. Usually that's a missing include or something similar. @justinclift Can you paste the build log in here? I should be able to figure it out then :smile:

**Comment by justinclift** [comment]
Thanks @chrisjlocke, looking now.

It shouldn't be a disk space problem.  There was heaps of space free when I last looked (a week or so ago).

**Comment by justinclift** [comment]
> Can you paste the build log in here?

The macOS ones have a build log, but not the Windows ones.

When I previously tried adding a redirect (eg `>> /some/log/file.txt`) to the batch file lines, it just broke the build.

If someone else can figure out how to get it working though, it'd be welcome. :smile:

**Comment by justinclift** [comment]
Looks like a compile error.  Kicked off a manual build, then interrupted it when noticing part of the build failed.

@MKleusberg This is a cut-n-paste of the build log window, which shows the compile error:

[compile_error.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/4941653/compile_error.txt)

**Comment by chrisjlocke** [comment]
`>>` redirects stdout, while `2>>` redirects stderr.  Also, /some/log/file is Unix slashes, while Windows uses \some\log\file.txt 😉 
But the first \ also assumes the root directory, so ensure the path you enter is right.

**Comment by justinclift** [comment]
@chrisjlocke Yeah, I tried several variations.  From memory, the part that it broke was the `devenv` line which does the main DB4S compiling piece.  It **really** didn't like the redirects or something.

It was a while back though, so memory of specifics is pretty faint. :wink:

**Comment by chrisjlocke** [comment]
> C:\git_repos\SQLCipher-Win64>git pull

Not related to this compile error, but this returns an error ... or can that error be ignored?

**Comment by MKleusberg** [comment]
Thanks. This should be fixed now :smile:

**Comment by justinclift** [comment]
> Not related to this compile error, but this returns an error ... or can that error be ignored?

It does a bunch of git things near the start, to try and automatically get itself out of any weird inconsistent state from bad compiles (etc).  Looking at it now, it seems ok. :smile:

**Comment by justinclift** [comment]
> This should be fixed now

Cool.  Just kicked off the build scripts...

**Comment by justinclift** [comment]
Yep, looks good.  The Win64 build completed successfully, and the Win32 one is running now. :smile:

**Comment by chrisjlocke** [comment]
Thanks you two ... much appreciated.  😃

**Comment by chrisjlocke** [comment]
Closing as your both so bloody awesome.

**Comment by chrisjlocke** [comment]
Opening again.  No nightlies.  😭 😭

**Comment by MKleusberg** [comment]
Oh. That's disappointing. It's likely the automatic update check again which I really tried to keep in mind this time :wink: 

@justinclift Can you start a new build with the latest commit included? :smile:

**Comment by MKleusberg** [comment]
Thank you for trying to test this by the way, @chrisjlocke! The new DBHub.io code in DB4S definitely needs some testing.

**Comment by justinclift** [comment]
No worries, new build starting now.  Will cut-n-paste the output again, once the compile breaks. :smile:

**Comment by justinclift** [comment]
Win64 compile actually succeeded.  Looks like whatever went wrong with the builds earlier today, it wasn't a source code problem.

Kicking off the Win32 build now.

**Comment by MKleusberg** [comment]
caa9e4d77f334722f08a17dbe54d34e8b989d3ea should have fixed it :smile:

**Comment by justinclift** [comment]
Heh Heh Heh.  Cool, looks like we're good then. :smile:
