### ISSUE TITLE
'Clone' textboxes displays multiple carets

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2336]
This is a weird one, but might be simply an option on the control or something.  The UI might be redesigned anyway, but thought I'd mention it.

![image](https://user-images.githubusercontent.com/7872218/87854368-62575280-c909-11ea-97fe-8e5612674f6c.png)

If I click in each textarea in the 'clone' area of the 'Remote' tab, a text caret is correctly placed there, but isn't cleared if I click elsewhere.  So now there are three carets....
A user won't click like this, and this doesn't seem to occur in other places of DB4S (not that textboxes like this are used...)

Totally minor point, and might be an OS thing, but thought I'd mention it and clog up the issues a bit more.... 😉

**Comment by MKleusberg** [comment]
Can you check the last nightly build again? :smile: I've simply replaced those labels by line edit widgets.

**Comment by chrisjlocke** [comment]
Yes, no carets at all now.  Like a vegetable stall burgled by a gang of rabbits.
