### ISSUE TITLE
'Failed to open database' error

### ISSUE THREAD

**Issue by aditibindal27** [sqlitebrowser/sqlitebrowser#2337]
Details for the issue
--------------------
![Screenshot (6)](https://user-images.githubusercontent.com/68473349/87855804-55058c80-c938-11ea-8f76-aba6455b6e03.png)

#### What did you do?
OPen a database

#### What did you expect to see?
Database

#### What did you see instead?
Error

I tried to even run it as administrator. The database doesnt open. 

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by justinclift** [comment]
With the error message about the database being read only, is there any chance that's really the case?

From memory, one way to check is to right click on the database file in Windows explorer, then choose "Properties" from the context menu.

In the dialog that's displayed, it should show if the file is read only or now.  And also let you change that, if you have sufficient permission.  eg from the Administrator account, as you mentioned

**Comment by chrisjlocke** [comment]
From DB4S, you can also open a read-only database.  Its unusual for a database to be read-only though - are you opening it from somewhere in c:\program files as a normal user? Normally, Windows 'shuts this off' from normal users.  Right-click the DB4S .exe and select 'Run as Administrator'. 

![image](https://user-images.githubusercontent.com/7872218/87859530-b07e4d00-c92d-11ea-8cad-e5e87ea270a0.png)

**Comment by aditibindal27** [comment]
Nothing works. I opened the Browser as well as the file by run as administrator. It shows the same error. And only on some files. Some files are opening, some are not. And at times, the file gets opened  but when i try to reopen it, it gives the same error. I also tinstalled the software again on my laptop. Please help!
![Screenshot (15)](https://user-images.githubusercontent.com/68473349/87860146-b0477700-c958-11ea-9955-56051025f871.png)

**Comment by chrisjlocke** [comment]
> Some files are opening, some are not.

Do you know what files are opening and what ones aren't ?  Can you email a couple to me?  (db4s [at] chrisjlocke [dot] co [dot] uk)
Are they all in the same location?  Or do files from location X work, but not at location Y ?
It appears you're trying to open from the desktop, which should be fine.
Can you create a directory off the C drive called 'databases', move the file there, and try opening it / them?
But again, the desktop should be fine.  I assume if you try and rename the file (that won't open) that works fine without error?

**Comment by chrisjlocke** [comment]
> Nothing works. I opened the Browser as well as the file by run as administrator. It shows the same error. And only on some files. Some files are opening, some are not. And at times, the file gets opened but when i try to reopen it, it gives the same error. I also installed the software again on my laptop., nothing works again :( Please help!
> ![Screenshot (16)](https://user-images.githubusercontent.com/68473349/87860249-85115780-c959-11ea-9b28-444e8037145a.png)

Can you click on the 'Security' tab from the properties dialog in your screenshot, and scroll down to find your username and click on it once [1], then in the permissions section, ensure you have modify [2] and write [3] permissions.

![image](https://user-images.githubusercontent.com/7872218/87870319-8749d500-c99e-11ea-8f77-da687553e28b.png)

**Comment by FriedrichFroebel** [comment]
There is a database journal file in your (now deleted) screenshot of the directory content. Where does this stem from? Is this being distributed with the database, do you have an active session on the database, does DB4S create this when trying to open the database or ...?

**Comment by chrisjlocke** [comment]
The .journal doesn't get created until a change is made to the database (by the user) - shouldn't get created during the initial opening of a database.  I've just created a read-only folder in Windows, and DB4S allows me to open a database in there, but (expectedly) doesn't allow me to create a new table.

**Comment by chrisjlocke** [comment]
@aditibindal27 - Have you looked any more into this?

**Comment by aditibindal27** [comment]
Yes! After changing the file name, it worked automatically

**Comment by justinclift** [comment]
No worries, sounds like a working solution then. :smile:
