### ISSUE TITLE
--with-functions option not work on macOS Homebrew

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#2338]
What is your question
-----------------------
**To build the project on macOS, I ran the following command with reference to [BUILDING.md](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md).**
`$ brew install sqlite --with-functions --with-json1 --without-readline`

**As a result of executing the above command, Homebrew returned the following error.**
`Error: invalid option: --with-functions`

I searched for something related to google but I couldn't find a workaround.
I think that option is missing from [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sqlite.rb). So I tried to review the history of the SQLite homebrew formula,
but my computer was so slow that the 'git log' command did not work smoothly.

Can I ask your advice?

Environment
-------------
- macOS Catalina 10.15.6
- Homebrew 2.4.8

Screenshot
------------
![스크린샷 2020-07-20 03 18 54](https://user-images.githubusercontent.com/64626662/87881993-00493b00-ca38-11ea-82fa-766b671312e3.png)

**Comment by scottfurry** [comment]
@lucydodo - looks like there is something 'out-of-date' in our documentation. A quick scan of the `sqlite` [compile options](https://www.sqlite.org/compile.html) doesn't show a `functions` setting. If you edit the homebrew formula and remove the `--with-functions`, does sqlite3 build?

**Comment by justinclift** [comment]
Oops, that line in the building.md is very out of date.  We use our own Homebrew formula for SQLite now instead:

https://github.com/sqlitebrowser/sqlitebrowser/blob/a3360cc2aa95edd9e5736c369f52c7b733c8b011/installer/macos/build_sqlitebrowser_nightly.sh#L68

Try this instead:

```
$ brew  tap sqlitebrowser/sqlite3
$ brew install sqlitefts5
```

In theory, that should retrieve our Homebrew formula (with the correct options) and things should work ok. :smile:

**Comment by lucydodo** [comment]
@scottfurry Thank you for your advice. before I tried your advice, I got a solution from @justinclift and just solved it.
@justinclift It works! Thank you for your advice.
