### ISSUE TITLE
VACUUM

### ISSUE THREAD

**Issue by yura371** [sqlitebrowser/sqlitebrowser#234]
Why sqlitebrowser write "cannot VACUUM from within a transaction: VACUUM;"? When I select "VACUUM" query.

**Comment by justinclift** [comment]
Yeah, that doesn't sound good.

Which version are you using, and on which OS?

**Comment by justinclift** [comment]
Hmmm, it happens here on OSX 10.9.5, using our latest code:
![screen shot 2015-03-20 at 18 53 36](https://cloud.githubusercontent.com/assets/406299/6758762/951c77ee-cf32-11e4-9e2b-9726e2607ab5.png)
@yura371 File → Compact Database works for me though.  Is that good enough for you for now?

![screen shot 2015-03-20 at 19 07 10](https://cloud.githubusercontent.com/assets/406299/6758990/62322494-cf34-11e4-883e-baf80c10fc96.png)

**Comment by rp-** [comment]
this doesn't work, because internally we create a transaction around all statements in the execute sql editor. And VACUUM can't be run within an transaction.

As a workaround use the "compact Database", from the menu as suggested.

**Comment by justinclift** [comment]
@rp- Interesting.  This seems to work if someone **really** needs a way to run vacuum instead of doing the Compact Database option for some reason:
![screen shot 2015-03-23 at 11 17 56](https://cloud.githubusercontent.com/assets/406299/6778882/8bddb972-d14e-11e4-95d8-c9aff2323ad1.png)
Dodgy workaround though. :wink:

**Comment by justinclift** [comment]
Closing this for now, as it seems like something we're not going to change.

"Compact database" is hopefully a workable alternative instead. :smile:

**Comment by MKleusberg** [comment]
The 'Compact database' is just a GUI element for calling the vacuum function, so it's not even really a workaround in a technical sense but just exactly the required function here :)

**Comment by justinclift** [comment]
Excellent. :smile:

**Comment by Xtigyro** [comment]
And how to do this within a Python script? - I mean, If I want to "compact" the DB? You cannot execute more than one query at a time.

```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/IBM/InformationServer/Server/DSEngine/bin/ISMD-emeaprd.py/__main__.py", line 3518, in <module>
  File "/opt/IBM/InformationServer/Server/DSEngine/bin/ISMD-emeaprd.py/__main__.py", line 2151, in f_deleteOlderT31d
pysqlite2.dbapi2.Warning: You can only execute one statement at a time.
```

**Comment by FriedrichFroebel** [comment]
@Xtigyro This is not really related to the "DB Browser for SQLite" (DB4S). You may have a look at https://github.com/ghaering/pysqlite/issues/109, but as this seems like a bug in some IBM product, you probably should contact the corresponding developers.
