### ISSUE TITLE
Format BLOBs as UniqueIdentifier

### ISSUE THREAD

**Issue by maseal** [sqlitebrowser/sqlitebrowser#2342]
Describe the new feature
--------------------------
When you create table column with "UNIQUEIDENTIFIER" type, SQLite always stores its values as BLOB. It would be great to add human-readable formatting for such columns.

Additional info
---------------
Now SQLiteBrowser doesn't display BLOB data by default and I use the following custom display format:
`substr(hex("column"), 7, 2) || substr(hex("column"), 5, 2) || substr(hex("column"), 3, 2) || substr(hex("column"), 1, 2) || '-' || substr(hex("column"), 11, 2) || substr(hex("column"), 9, 2) || '-' || substr(hex("column"), 15, 2) || substr(hex("column"), 13, 2) || '-' || substr(hex("column"), 17, 4) || '-' || substr(hex("column"), 21, 12)`
(this solution came from here: https://neosmart.net/blog/2018/converting-a-binary-blob-guid-to-text-in-sql)
But it's very uncomfortable to rewrite this code for each column name.
I believe I am not the only person who need this feature.
E.g. it can be easily added to `ColumnDisplayFormatDialog.cpp` with the following lines (I am not a C++ developer):
```
ui->comboDisplayFormat->addItem(tr("UniqueIdentifier blob"), "uuidblob");
...
formatFunctions["uuidblob"] = "substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 7, 2) || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 5, 2) || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 3, 2) || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 1, 2) || '-' || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 11, 2) || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 9, 2) || '-' || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 15, 2) || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 13, 2) || '-' || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 17, 4) || '-' || substr(hex(" + sqlb::escapeIdentifiercolumn_name + "), 21, 12)";
```
#### Default displaying of UniqueIdentifier column:
![image](https://user-images.githubusercontent.com/575760/88259178-39eda080-ccdb-11ea-8a9a-5a4ceb15ce1c.png)
#### Formatted displaying of UniqueIdentifier column:
![image](https://user-images.githubusercontent.com/575760/88263855-285cc680-cce4-11ea-9a56-c6c94f8db954.png)

**Comment by justinclift** [comment]
Just to make sure I'm understanding, you're wanting us to add a `uuidblob` display format to the in build list, using the code snippet above (or similar)?

If so, no worries.  That's probably do-able. :smile:

**Comment by maseal** [comment]
Yes, exactly

**Comment by MKleusberg** [comment]
Thanks for the suggestion and excellent preparation, @maseal! I have just added a new display format like that. Can you check tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/) and see if it's working for you? :smile:

**Comment by justinclift** [comment]
@maseal Have you had a chance to see if the new format option works ok?

**Comment by maseal** [comment]
Yes I've already tested it. It works as expected

**Comment by justinclift** [comment]
Awesome!  Thanks for making the suggestion @maseal. :smile:

@MKleusberg Good stuff.  I've added this to the 3.12.1 milestone, as the code change looks pretty simple. :smile:

**Comment by straypointer** [comment]
This is a great feature, but I am not seeing it in my display format dropdown list... does 'uniqueidentifier' need to be capitalized for it to work?

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?

**Comment by straypointer** [comment]
I just installed 3.12.1 - win64.

If it helps, here is the version from the about box:
"DB Browser for SQLite Version 3.12.1


Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.12.8

SQLite Version 3.33.0."


Thanks!

**Comment by chrisjlocke** [comment]
Interesting - this got missed from the 3.12.1 release.  Just checked the 3.12.1 and yes, the list stops at 'upper case', while it's there in the nightlies.

![image](https://user-images.githubusercontent.com/7872218/102904854-374dcd80-446a-11eb-89a1-e71d1e1cff29.png)

I'd suggest download the nightly and trying that.
https://nightlies.sqlitebrowser.org/latest/

If you download the .zip flavour (https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip), extract it, you can run it without 'installing' and alongside your existing version.

**Comment by straypointer** [comment]
Yep, that worked. Thanks!

**Comment by thigg** [comment]
is this released already?

**Comment by chrisjlocke** [comment]
Don't think its in the 3.12.2 release .. it's in the nightlies though.
https://nightlies.sqlitebrowser.org/latest/

**Comment by thigg** [comment]
Any indication when this will be released? Will this be in the next release?

**Comment by justinclift** [comment]
> Will this be in the next release?

Yep.  We're still figuring out when to do the next release though. :wink:

**Comment by justinclift** [comment]
Should be.  Everything that's been in the nightlies before we branched the 3.13.x series should be in 3.13.0.

**Comment by jogibear9988** [comment]
I don't see this....

<img width="615" alt="Image" src="https://github.com/user-attachments/assets/39ce049a-7d1c-4f30-8842-c236bf738ddd" />

**Comment by jogibear9988** [comment]
Sorry, list is scrollable, itt works
