### ISSUE TITLE
Pressing [F5] in Execute SQL tab doesn't execute SQL

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2344]
In the latest nightly (18 Jul is OK) pressing [F5] in the Execute SQL tab does nothing.  No errors, nothing.  This works fine (for the same database / steps) in the nightly from 18 Jul, so has broken between these points.

Pressing [Shift] + [F5] works, as does pressing the toolbar button - just not the [F5] itself.

**Comment by sky5walk** [comment]
I thought there was a change to execute only 1 line of SQL with [F5] and all lines with [shift]+[F5]?
Or vice versa?

**Comment by chrisjlocke** [comment]
The tooltip would indicate [F5] is the key of choice.

![image](https://user-images.githubusercontent.com/7872218/88324183-3aa62700-cd1b-11ea-92f2-2716a9342911.png)

Pressing [Ctrl] + [R] works, as does [Ctrl] + [Return].  Its just [F5] that doesn't.

**Comment by mgrojo** [comment]
I cannot reproduce this with my own build of the master branch, @chrisjlocke. Does it happen using other language setting?

**Comment by chrisjlocke** [comment]
Interesting.  Changed to Saudi Arabia and tried again, and F5 did work.  Er....how....why....er.....what..... 😕

**Comment by chrisjlocke** [comment]
Ok.  Resetting back to English and it works again.  
I guess something got messed up in the translations or something?  
Thanks @mgrojo !!

I'll have to try a 'clean' install to confirm, but must just have been me then.
