### ISSUE TITLE
Unable to look at temporary table in Browse Data Tab

### ISSUE THREAD

**Issue by gchan1234** [sqlitebrowser/sqlitebrowser#2348]
Hi 

I am unable to look at temporary tables in the Browse data table. It works in previous versions. When I click on the temporary table - it reverts to the first available table on the list

**Comment by justinclift** [comment]
Ouch.  That sounds like a bug. :frowning:

**Comment by MKleusberg** [comment]
Yes, just noticed that too with attached databases. I'll look into it now. It's definitely something we need to fix for 3.12.1, so thanks for reporting this, @gchan1234! :smile:

**Comment by MKleusberg** [comment]
This should be fixed now. Can you check again using [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/), @gchan1234?

**Comment by justinclift** [comment]
@MKleusberg Any idea when this bug was introduced?

**Comment by gchan1234** [comment]
@MKleusberg Thanks it's fixed :)

**Comment by MKleusberg** [comment]
@justinclift Looks like the bug was introduced by this commit a09df5bc0a8bc5247edf2c789898e94d59a94410. So it's only present in the nightlies.

@gchan1234 Awesome. Thanks for testing! :smile:

**Comment by justinclift** [comment]
> Looks like the bug was introduced by this commit a09df5b. So it's only present in the nightlies.

Cool. :smile:
