### ISSUE TITLE
Upload button disabled in remote dock

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2349]
Trying out the latest DB4S dev code at the moment (commit 8b5f34c4062094d1da5154f6ed37326c8b0d82e7), and noticed a bug with the Remote dock.

I've downloaded a database from my account, modified it (adding a view), then closed the database (after writing changes).

In the "Local" tab of the Remote dock, the "upload" button remains greyed out when I select the entry for the database:

![2020-07-30-Remote_tab-8b5f34c4062094d1da5154f6ed37326c8b0d82e7-upload_button_disabled](https://user-images.githubusercontent.com/406299/88921639-3301f780-d2b2-11ea-9522-821bbd415abe.png)

That seems like that should probably work?

As an aside, right clicking on the entry gives a context menu of "Open database" and "Close database".  If it's simple to add an "Upload database" entry there too, that's probably a decent spot for it as well. :smile:

**Comment by justinclift** [comment]
Some extra data points, after playing around with this a bit:

* Restarting DB4S and selecting the database in the Local tab makes no difference.  The Upload button is still greyed out.
* Double clicking on the database in the Local tab, to open it in DB4S then enables the Upload button.
* Closing the database greys out the Upload button again. :frowning:

**Comment by MKleusberg** [comment]
The Upload button is intentionnaly only enabled when a database is opened because it's meant to be a 'global' button which doesn't depend on anything you do in the different tabs of the Remote dock. The button could become rather confusing when you have one database opened but selected another one in the Local tab for example.

An extra action in the context menu is a very good suggestion though :smile:

**Comment by justinclift** [comment]
> The button could become rather confusing when you have one database opened but selected another one in the Local tab for example.

Ahhh, hadn't thought of that.  Yeah, a context action would probably do the job then. :smile:

**Comment by justinclift** [comment]
Just noticed another small thing.  When uploading a new database version, the commit list in the "Current Database" tab doesn't automatically refresh to show the new commit.  Easy fix? :smile:

**Comment by justinclift** [comment]
In a similar level of "not real important, more a UI tweak":

* When the last database for the user is deleted from the "Local" list, an empty folder entry for that user is left behind.  It's gone when DB4S is restarted, but it would be "smoother" experience to have it removed from the visible folder list right away.

**Comment by justinclift** [comment]
In the "Current Database" tab of the Remote dock, right clicking on a commit revision shows a context menu with two options:

* Check out Commit
* Save Revision to File

The "Save Revision to File" one is useful, but it doesn't work for the latest commit though it probably should.

It'd be useful to have a "Copy commit details to clipboard" context menu option as well, and maybe one just for the commit ID too.  Working on our API today, I had a need for a previous database revision and it's commit ID.  Grabbed the commit ID via the website, but it seems like that'd fit well here too.

**Comment by MKleusberg** [comment]
Let me try listing the different suggestions and their status here:
1. Upload Database context menu action -> Done
2. Commit list not updated after uploading database -> Fixed in #2359
3. Removing the last database of a user should remove the user directory too -> Done
4. Copy commit details -> Pending

@justinclift Can you check 1 and 3? I'm not sure about 4. You can just click on the cell you're interested in and press Ctrl+C to copy the cell contents. We have the same behaviour in other parts of the application like the Database Structure view and it seems to work fine there.

**Comment by justinclift** [comment]
Just tested:

1. Upload Database context menu action -> Confirmed working.
2. Commit list not updated after uploading database -> Confirmed working.
3. Removing the last database of a user should remove the user directory too -> Confirmed working.

The fourth one, "Copy commit details", isn't quite working properly.  I didn't actually realise it was possible to click in a cell to have it be the "selected" one for copying. :wink:

For me, clicking on any row in the commit list highlights the whole row.  Subsequent clicking on any individual cell doesn't visible change anything, the whole row is still highlighted.  If there's some way to indicate "this cell is now selected", that'd probably be worth trying. :smile:

For the copying aspect, when a new row is selected in the commit list, the Ctrl+C copy keypress does nothing.  But after subsequently clicking on a cell in the same row (without any indication of change), the Ctrl+C copy **does** work, putting the contents into the clipboard.

From a user point of view, it'd probably be better for any single click on a new row to do nothing but highlight that specific cell, in order to (hopefully) make it more obvious it's contents can be copied?  The "select the whole row visibly" thing doesn't really do anything functional does it? eg it could be dropped without negative effect (?)

Oh, there was one other suggestion:

5. Context menu option "Save Revision to File" isn't working for the latest commit.  It'd be useful if it did, so people can make a copy of the pristine (unchanged) latest revision, without needing to overwrite any of their local changes. :smile:

**Comment by MKleusberg** [comment]
Ah, I didn't see 5. It should be fixed too now :smile: 

The fourth one seems peculiar. I can copy the information after the first click. Out of curiosity, can you see if it works as expected in the Database Structure tree view?

**Comment by justinclift** [comment]
Trying out 5. ("Save Revision to File" for most recent commit), now works.

Just noticed something a bit strange that **might** be related to it.  If I've modified the local database, and double click a previous revision in the commit history it pops up a warning about "You have modified the local clone ...".  But double clicking the latest commit (which I've since modified the DB from) doesn't.  It seems to just re-open the existing (modified) database, rather than refreshing it.

**Comment by justinclift** [comment]
Weirdly, **now** when I directly click on any given cell in the commit list the Ctrl+C is working.  It definitely wasn't before.  Oh well. :wink:

**Comment by MKleusberg** [comment]
> But double clicking the latest commit (which I've since modified the DB from) doesn't. It seems to just re-open the existing (modified) database, rather than refreshing it from that commit. Problem?

Yeah, that's intended but not necessarily well-founded. The reasoning is that checking out the currently checked out commit should be a no-op because users could misunderstand the warning and lose their changes. What do you think? Should I change it or leave it as it is? In the latter case a 'Revert to commit on server' button might be needed.

**Comment by MKleusberg** [comment]
> Weirdly, **now** when I directly click on any given cell in the commit list the Ctrl+C is working to copy that cells contents. It definitely wasn't before. Oh well. :wink:

I believe you :smile: Maybe another Qt oddity.

**Comment by justinclift** [comment]
With double clicking a commit, the right approach there is probably to have the same "You have modified the local clone ..." warning if the user double clicks the latest revision too.  Well, if they *have* modified the database anyway.

That way the behaviour is consistent regardless of which commit they click on, and gives fair warning before any potential data loss.

**Comment by MKleusberg** [comment]
Ok makes sense :smile:

**Comment by MKleusberg** [comment]
Done :smiley: Can you test it again?

**Comment by justinclift** [comment]
Yep, it's working well now.  It's consistent, allows people to reset their changes back to any of the given versions as desired, and has an appropriate warning before any potential data loss could occur.

Well done! :smile:

**Comment by MKleusberg** [comment]
Awesome :smile: What do you think? Are we finished with the DBHub.io integration for the next release or is there anything important missing?

**Comment by justinclift** [comment]
I **think** it's complete now.  At least, it seems to be working well, and I'm not seeing any missing functionality.

Hmmm, we could potentially add a "Delete database" option.  So people can nuke their stuff from the server without needing to use the webUI.

It'd need the corresponding deletion call added to the server, but that should be pretty easy.  I wrote initial [deletion code](https://github.com/sqlitebrowser/dbhub.io/commit/1b9307e95c3e1c8521370f587a4ca5261c79963a) for the API today (note - work in progress, very untested).  A DB4S variant of that would be straight forward.

That being said, I'm about to hit the sack here (5am!), so can't do it right away.  If you reckon it'd be a useful addition to DB4S (?), you're welcome to get both sides done and I'll deploy it live when I'm up and about again. :smile:

**Comment by justinclift** [comment]
@MKleusberg The "Delete" functionality is available for people through the API now (https://github.com/sqlitebrowser/dbhub.io/commit/28ee508c5266a0da74b98cf5ef6132994cf2c7b8).  Do you want me to create a DB4S end point for it as well (prob tomorrow), or should we skip that for now and call it "good enough"?

**Comment by MKleusberg** [comment]
I'm not really sure. I mean it's potentially very destructive and rarely used. So the workflow of clicking the Website icon in DB4S and deleting the database there might be enough or even better in my opinion :smile:

**Comment by justinclift** [comment]
No worries.  Let's call it "good enough" for now then.  If people request the ability to delete their databases via DB4S, it should be pretty straight forward to add then. :smile:
