### ISSUE TITLE
Last column in Data Browser should not be right-aligned

### ISSUE THREAD

**Issue by NSExceptional** [sqlitebrowser/sqlitebrowser#2350]
When browsing table data, the last column appears to be automatically right-aligned. This is not desired behavior.

#### What operating system are you using?

- [x] Windows 10

**Comment by justinclift** [comment]
Interesting.  With that right alignment, does it happen regardless of the data type of the column, or is it only happening for specific types?

Also, which version of the application is this happening with? :smile:

**Comment by chrisjlocke** [comment]
For me, the last column (if text) is left aligned.  Seems OK... 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/7872218/89259751-df313e80-d622-11ea-82cf-9d91a2ed8982.png)

A screenshot (and application version info ... see Help then About ... the four text lines at the top can be selected, copied and pasted here).

**Comment by mgrojo** [comment]
The behaviour in v3.12 is that columns whose datatype is numeric are right-aligned, remaining columns are datatype. That depends on how the table is defined, and not on the actual data stored in the cell (given that SQLite allows storing text in a column whose type is integer, for example).

Nevertheless, you can change the alignment using the format toolbar, which is expanded pressing this button: ![image](https://user-images.githubusercontent.com/13812910/89307009-e121ee80-d670-11ea-8c9b-4ed776915f2b.png)

**Comment by mgrojo** [comment]
Without further information to consider this a bug, closing this as answered question.
