### ISSUE TITLE
How do I word wrap the table viewer?

### ISSUE THREAD

**Issue by botist** [sqlitebrowser/sqlitebrowser#2352]
So instead of this:
![Capture](https://user-images.githubusercontent.com/66886150/89360000-235d2700-d695-11ea-8ea2-e201fcef4778.PNG)
I get something more like this:
![Capture1](https://user-images.githubusercontent.com/66886150/89360026-31ab4300-d695-11ea-8a2c-d4d421189a7f.PNG)

**Comment by chrisjlocke** [comment]
If you increase the row height, the text should be displayed.
https://youtu.be/TdABaZN_1Vs

You can also double-click the cell border to make the cell as high as needed.
https://youtu.be/8Pk4COJUOQI

**Comment by mgrojo** [comment]
Additionally, you can press the secondary mouse button to get the context menu over the vertical header (where the row numbers are shown) and select 'Adjust rows to contents'. That wil automatically adjust the row heights to the current contents. Each time the table is refreshed, the heights are readjusted. This setting is not currently stored in project files, but should be in the future.

**Comment by botist** [comment]
Thank you, much better now!
