### ISSUE TITLE
Modifying new table has misaligned filter cells

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2353]
When you create a new table and immediately go to the 'Browse Data' tab, the filter cells under each column heading aren't sized to the cells.  If you've a large table, this can look .... odd.

https://youtu.be/v211U39Yybk

So I created a table, browsed a couple of other tables fine, but as soon as I clicked the newly created one, you can see the long filter cells.  Clicking 'Refresh' (and indeed visiting another table and returning) solved the issue, but ... well, it can look a bit ... odd.

This was with the latest nightly, after checking the temporary table amendment.

**Comment by mgrojo** [comment]
@chrisjlocke No idea why this is happening, but it doesn't matter now because #2188 has been implemented and it filters will be hidden in that situation.

**Comment by chrisjlocke** [comment]
Excellent, many thanks!

**Comment by chrisjlocke** [comment]
@justinclift - I've downloaded last nights nightly, and these latest fixes don't seem to be in it.
Does the build need to be 'kicked' again, like it did when the last changes didn't take?

**Comment by justinclift** [comment]
@chrisjlocke I'll take a look. :smile:

**Comment by justinclift** [comment]
Ahhh.  The builds went fine, but the uploading to the nightlies server failed.  The build server doesn't have a static IP address (from the nightlies server perspective), and was blocked by firewall rules.  Updated those rules, and the nightlies are uploading now.

Give it a minute or two, and they should be available. :smile:

**Comment by chrisjlocke** [comment]
Cheeeers bud!

**Comment by chrisjlocke** [comment]
Closing as this is now resolved.  Thanks all!
