### ISSUE TITLE
Unable to cut cell content

### ISSUE THREAD

**Issue by siera-papa** [sqlitebrowser/sqlitebrowser#2355]
CTRL + X does not do anything and the last copied item is pasted.
I tried reinstalling v3.12.0, latest nightly version and restarting my PC.
I guess this is a known bug although nothing came up in my searches.

Version 3.12.0
Windows 10 Pro x64

**Comment by justinclift** [comment]
Errr, no, it's not a known bug.  Cut is supposed to work.  But, it's obviously not in this case. :frowning:

Is there any chance you can record it going wrong, so we can see in context what's happening? eg screencast or similar

**Comment by siera-papa** [comment]
Sure, here it is.

**Comment by siera-papa** [comment]
Sure, here is the recording:
https://streamable.com/p771g6

**Comment by justinclift** [comment]
Thanks, yeah that should work.

@mgrojo This looks like your kind of thing?

**Comment by justinclift** [comment]
@siera-papa Just to double check, there's nothing else running on the system which might be stealing the clipboard contents somehow?

**Comment by mgrojo** [comment]
I was surprised too, but we don't have a Cut operation, so when you press Ctrl+X is like doing nothing :smile: Apparently, @siera-papa, you're the first one to notice this omission.

Luckily, it will be easy to implement. I suppose Cut should delete the cell to NULL and copy to clipboard. Ideally, it should take into account a possible NOT NULL constraint in the field to leave the cell empty, instead of setting it to NULL.

**Comment by siera-papa** [comment]
Thanks for your interest. 
I hope this will be implemented soon.

**Comment by mgrojo** [comment]
@siera-papa [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) will have a Cut option in the context menu, and Ctrl-X or Shift-Del will also trigger the operation. It copies current data to clipboard and then deletes cell contents to NULL or to empty strings (depending on the NOT NULL constraint of the field). Could you give it a try and confirm it's working for you?

**Comment by siera-papa** [comment]
@mgrojo Works perfectly now, thanks a lot!
