### ISSUE TITLE
Add a way to disable "Collation needed! Proceed?" dialogue for DBs that have custom COLLATE columns

### ISSUE THREAD

**Issue by armahnii2000** [sqlitebrowser/sqlitebrowser#2356]
Describe the new feature
--------------------------
If you have a column with a custom COLLATE string, a Collation needed! pop-up window shows up almost every time. It makes browsing DB's with custom collations cumbersome. It would be nice if there was a way to override this via some setting where you just fallback to some default collation if SQLite can't find one.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
There's lots of issues on this - https://github.com/sqlitebrowser/sqlitebrowser/issues?q=is%3Aissue+collate+is%3Aclosed
Original issue for which pop-up dialog was introduced is found here - https://github.com/sqlitebrowser/sqlitebrowser/issues/54
Commit - https://github.com/sqlitebrowser/sqlitebrowser/commit/cf33f3054e613f0a7ac20c5edf4c35ffe994e2bf

#### Does this feature exist in another product or project? Please provide a link.
Not sure. Only used sqlitebrowser

**Comment by justinclift** [comment]
Good idea. :smile:

**Comment by MKleusberg** [comment]
Can you try tomorrow's nightly build, @armahnii2000? I have added a 'Don't ask again' button to that message box :smile:

**Comment by armahnii2000** [comment]
Will do!

Thanks!
George

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by armahnii2000** [comment]
Just tried it out and its working great!

**Comment by justinclift** [comment]
Awesome!  Well done @MKleusberg. :smile:

Thanks for verifying it @armahnii2000. :smile:
