### ISSUE TITLE
Unable to write changes: "FOREIGN KEY constraint failed"

### ISSUE THREAD

**Issue by senthilmuruga** [sqlitebrowser/sqlitebrowser#2357]
Details for the issue
--------------------

#### What did you do?
I tried to do some ETL stuff by our sqlite3, I am able to alter the table data and not able to save the changes in my DB

#### What did you expect to see?
I wanted to save the DB as my edited version which I play around through sqlite3

#### What did you see instead?
Its is not saving changes, just throwing error like "FOREIGN KEY constraint failed (RELEASE "RESTORE POINT;")

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by chrisjlocke** [comment]
v3.11.2 is 'relatively' old now ... well, one version out.  Try v3.12.0
https://sqlitebrowser.org/dl/

Also, what data are you changing?  If you're adding or deleting specific data, just make sure you're following the 'rules' - you can't add an ID of 7 if that doesn't exist in the other table.  If none of that makes sense, yell, as you may already know about foreign keys...  ie, the error may not be an error as such, more of a 'data integrity' warning.

**Comment by mgrojo** [comment]
Probably your database has foreign-key errors which are not caught by sqlite3 because the "`PRAGMA foreign_key`" is disabled. You can do the same in DB4S (using "Preferences > Database > Foreign keys") or find and fix all the errors using "Tools > Foreign-Key Check".

**Comment by mgrojo** [comment]
Closing this as it seems answered. It can be reopened, if there is still something to attend.
