### ISSUE TITLE
Unable to create table from sql export

### ISSUE THREAD

**Issue by adriandinu** [sqlitebrowser/sqlitebrowser#2358]
When I export an sql file, if the column name has a dash ("-") inside, the INSERT statement give me an SQL Logic error when I use the generated sql file:
This is what I get when I export:

CREATE TABLE IF NOT EXISTS `MyTable` (
	`Name`	TEXT,
	`Value-1`	TEXT,
	`Value-2`	TEXT
);
INSERT INTO `MyTable` (Name,Value-1,Value-2) VALUES ('a name','a value','another value'),

The error appears because the column names in (Name,Value-1,Value-2) don't have back quote like this: (`Name`,`Value-1`,`Value-2`)

**Comment by chrisjlocke** [comment]
To be Mr Pedantic, double-quotes is the proper method - grave accents (or back quotes, as you call them) are for compatibility with MySQL users.  But I digress.

What version of DB4S are you using?  This is one of the questions asked when you raise a new issue.
In our latest version (3.12.0) an SQL export includes double-quotes.

```
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "table-1" (
	"field-1"	INTEGER,
	"field-2"	INTEGER
);
INSERT INTO "table-1" VALUES (1,1);
INSERT INTO "table-1" VALUES (2,2);
INSERT INTO "table-1" VALUES (3,3);
COMMIT;
```

**Comment by chrisjlocke** [comment]
Closing this as no further information given.  Issue can be re-opened once more information is provided.
