### ISSUE TITLE
Remote dock push failure in nightly builds

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2359]
Stumbled onto an important bug in the RemotePushDialog code of our nightly builds. :wink:

When uploading a new version of an existing database, the branch list isn't refreshed + (important) DB4S's understanding of the "current commit" isn't updated to be the new one.

This means subsequent uploads from DB4S then all fail silently, as DB4S isn't sending the DBHub.io cloud the correct (updated) commit ID.

As a step towards resolving the problem, this message is shown on the application output console when pushing:

```
QObject::connect: No such slot RemotePushDialog::reloadBranchList() in .ui/ui_RemotePushDialog.h:152
QObject::connect:  (sender name:   'editName')
QObject::connect:  (receiver name: 'RemotePushDialog')
```

Looking into the current `master` code base, the `reloadBranchList()` function is indeed missing.  It is present some commits back (I checked the `v3.12.0` tag), though cutting-and-pasting the old function+header to our newer code doesn't work due to us now using a different approach.

Taking a brute force method, I've created an [initial "somewhat functional" equivalent](https://github.com/sqlitebrowser/sqlitebrowser/commit/79b5fd4f968329c855570e5ff8f2eb5b531dcd81) that does at least get rid of the warning message, but doesn't fully work.  eg it runs, but doesn't actually update the displayed list in the "Current Database" tab, nor does it move DB4S's understanding of the "current commit" forwards like needs to happen.

Hopefully this is easy to fix properly. :smile:

**Comment by justinclift** [comment]
Ahhh, it looks like `RemoteDock::pushFinished()` should be getting called instead, but for some reason that's not happening.

**Comment by justinclift** [comment]
Not sure why, but `RemoteNetwork::gotReply()` seems to not be called when the database push is finished, so the `case RequestTypePush` condition doesn't trigger.

Just in cast the problem was the recently-added gzip compression, I turned that off on my local dev server, but the same thing happens in DB4S.

Anyone know what might be causing this problem, or have ideas on how to debug it?

**Comment by justinclift** [comment]
Found the root cause.  There's a missing `connect()` in the new `RemoteNetwork.cpp`.

With the fixed pushing databases remotely works correctly.  I'll commit the fix to `master` shortly.

**Comment by justinclift** [comment]
Oh, that left over `RemotePushDialog::reloadBranchList()` signal in RemotePushDialog.ui should probably get fixed too.  Guessing it'll just need to be deleted, but I'll leave that to @MKleusberg as I'm not familiar enough with the code. :smile:

**Comment by justinclift** [comment]
Hmmm, there seems to be something wrong with downloading specific database revisions with the `master` branch too, though it's working in the `v3.12.x` branch.

**Comment by justinclift** [comment]
It looks like `RemoteDock::fetchFinished()` is being called multiple times when a remote database is downloaded.  The first time correctly puts it in place and calls (via a signal) `MainWindow::fileOpen()` on the file.

However that in turn calls `remoteDock->fileOpened()` on the file, which seems to trigger further runs of `RemoteDock::fetchFinished()`.  But with no file content, thus overwriting the correctly downloaded SQLite database with a 0 byte file.

**Comment by MKleusberg** [comment]
Should be fixed now. Can you double check it's working? :smile: 

The error message in the Push dialog and the missing update after pushing were unrelated issues but both should be fixed now. Your commit for the error message in the Push dialog was pretty close :+1: The missing update after pushing was caused by a missing handler for that event. Your first commit added that but was causing the download handler to be called twice. The new commit makes sure to only connect that needed handler for push actions.

**Comment by justinclift** [comment]
Yep, it's working fine now.  Thanks heaps for getting these fixed @MKleusberg. :smile:

**Comment by MKleusberg** [comment]
Cool :smile: Thanks for testing!
