### ISSUE TITLE
Bad Query Parse using %3

### ISSUE THREAD

**Issue by jaymmartin** [sqlitebrowser/sqlitebrowser#236]
Running the query:

`SELECT * FROM address WHERE house_number LIKE '%3';`
runs a query like
`SELECT * FROM address WHERE house_number LIKE '20';`

The number that %3 gets turned into seems somewhat random, but usually less than 20.

Note that %1 and %2 are also broken, but %4 and up work.

**Comment by justinclift** [comment]
Thanks for the report Jay.  This is fixed in the nightly builds already.  Well, in theory it is. :smile:

Are you ok to grab the latest nightly build and try that, just to make sure? (locations are listed on the front page of our this)

**Comment by justinclift** [comment]
I think this is the bug where it's identified and fixed, if that helps: https://github.com/sqlitebrowser/sqlitebrowser/issues/203

If it turns out this is not the same bug, and it's in our latest code, then yeah, it's a real bug that needs fixing. :smile:

**Comment by jaymmartin** [comment]
Nightly build works! Sorry for the trouble. I swear I searched first. :frowning:

**Comment by justinclift** [comment]
It's no worries at all. :smile:

If something else weird/not-great turns up, please report that too. (really) :grin: :
