### ISSUE TITLE
**the Import from CSV** option is disabled...

### ISSUE THREAD

**Issue by Zorono** [sqlitebrowser/sqlitebrowser#2360]
***Details for the issue***
![ScreenShot_20200809214839](https://user-images.githubusercontent.com/19735243/89740647-d3ae9f00-da8a-11ea-9794-b0fbf2d0fac8.png)
**the Import from CSV** option is disabled...
--------------------

#### What did you expect to see?
clickable **the Import from CSV** option...

#### What did you see instead?
disabled **the Import from CSV** option.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: 10 Pro N x64
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
In theory (!), if you create a database first (for importing into), then the option should be enabled.

Try that, and let us know how you go? :smile:

**Comment by Zorono** [comment]
Thanks dude, shame on my stupidness...

**Comment by justinclift** [comment]
It's no worries at all.  I've hit the same thing myself before too. :smile:
