### ISSUE TITLE
When creating a new/opening a SQLite database some parts of the UI still contain old data

### ISSUE THREAD

**Issue by mbraeutigam** [sqlitebrowser/sqlitebrowser#2362]
Details for the issue
--------------------

#### What did you do?
* Opened a database, queried some stuff.
* Clicked on Create new database | Open database and selected a file

#### What did you expect to see?
A fresh clean GUI. No old views / data.
It seems that the "Execute SQL" tab and the "Edit Database Cell" panel still contain old value.

#### What did you see instead?
![image](https://user-images.githubusercontent.com/4228180/89888852-efbc5880-dbd0-11ea-84f4-7a4ae87bdfbf.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0
- [ ] 3.11.x
- [X] Other: 3.12.99 (Aug 9 2020)

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for the bug report. :smile:

This is actually on purpose though, as we used to clear out everything... but it turns out some people want that info kept open between sessions.  This way people can run the same SQL queries on a bunch of databases, without having to manually open a SQL files (with statements to run) after opening a database. :smile:

**Comment by mbraeutigam** [comment]
Ahh, it's not a 🐞 - it's a feature 🤣

**Comment by mgrojo** [comment]
In the development version you can use the new menu entry "File > Close Project" to clean up everything.
