### ISSUE TITLE
Missing alias in "Execute SQL" tab's data view (table header)

### ISSUE THREAD

**Issue by mbraeutigam** [sqlitebrowser/sqlitebrowser#2364]
Details for the issue
--------------------

#### What did you do?
Executed
```SQL
CREATE TABLE IF NOT EXISTS "table_one" (
	"ID"	INTEGER NOT NULL,
	"TEXT"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "table_two" (
	"ID"	INTEGER NOT NULL,
	"ID_ONE"	INTEGER NOT NULL,
	"TEXT"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

INSERT INTO "table_one" ("ID", "TEXT") VALUES (1, "one");
INSERT INTO "table_one" ("ID", "TEXT") VALUES (2, "two");

INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (1,1, "one1");
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (2,1, "two1");
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (3,2, "three2");
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (4,2, "four2");

SELECT O.*, T.* FROM "table_one" O INNER JOIN "table_two" T ON O.ID = T.ID_ONE;
```

#### What did you expect to see?
| O.ID | O.TEXT | T.ID | T.ID_ONE | T.TEXT |
|---|---|---|---|---|
| 1 | one | 1 | 1 | one1 |
| 1 | one | 2 | 1 | two1 |
| 2 | two | 3 | 2 | three2 |
| 2 | two | 4 | 2 | four2 |

edit: it is not about the values in the cells but the alias abbreviations in the header

#### What did you see instead?
![image](https://user-images.githubusercontent.com/4228180/89890486-c0f3b180-dbd3-11ea-88b3-59f6a1909552.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0
- [ ] 3.11.x
- [X] Other: 3.12 Aug 9 2020

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, that result seems correct.

```
SELECT O.*, T.* FROM "table_one" O INNER JOIN "table_two" T ON O.ID = T.ID_ONE;
```

That's pretty much selecting everything where `ID` in the first table equals `ID_ONE` in the second table.

Looking at the first row of the first table, it's ID column contains `1`.

Looking at the second table, there are two rows which have an `ID_ONE` column equalling 1:

```
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (1,1, "one1");
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (2,1, "two1");
```

Ditto when looking at the first table, with ID containing `2`.  There are two rows in the second table with `ID_ONE` equalling 2:

```
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (3,2, "three2");
INSERT INTO "table_two" ("ID", "ID_ONE", "TEXT") VALUES (4,2, "four2");
```

So, it's giving the four resulting rows.

Off hand, I can't see a way to reduce that down to the single line you're after without either using an extra column, or maybe adding a "DISTINCT" clause to it.  The DISTINCT approach probably isn't what you really want though, in this specific instance.

Hmmm, I'm about to step away from the computer, but someone else might have some useful thoughts if you haven't figured out the solution already. :smile:

**Comment by mbraeutigam** [comment]
It is not about the values in the cells but about the naming of the header columns.

I get column names of ID, TEXT, ID, ID_ONE, TEXT instead of O.ID, O.TEXT, T.ID, T.ID_ONE, T.TEXT.
So I can not distinguish which column TEXT originates from which table at first sight.

**Comment by justinclift** [comment]
Ahhh.  I think you'll need to specify alias names for each column then, which unfortunately isn't as convenient. :frowning:

```
SELECT O.ID AS O.ID, O.TEXT AS O.TEXT, T.ID AS T.ID (etc) ...
```

**Comment by mgrojo** [comment]
These are the names returned by sqlite3 and I think we cannot do anything about it. The sqlite3 command line tool returns the same names, by the way.

Moreover, according to the [API documentation](http://sqlite.org/c3ref/column_name.html):

> The name of a result column is the value of the "AS" clause for that column, if there is an AS clause. If there is no AS clause then the name of the column is unspecified and may change from one release of SQLite to the next. 

So Justin is right, but you have to quote the dots, so the working query would be:
```sql
SELECT O.ID AS "O.ID", O.TEXT AS "O.TEXT", T.ID AS "T.ID", T.ID_ONE AS "T.ID_ONE", T.TEXT AS "T.TEXT" FROM "table_one" as O INNER JOIN "table_two" as T ON O.ID = T.ID_ONE;
```

**Comment by mbraeutigam** [comment]
Ughhh, good to know 👍 

Fun fact even ordering by column TEXT with no specification to the table does work - it seems SQLite grabs the first "TEXT" column and uses that for ordering (BTW: I changed O.*, T.* to T.*, O.*):
```SQL
SELECT T.*, O.* FROM "table_one" O INNER JOIN "table_two" T ON O.ID = T.ID_ONE ORDER BY TEXT;
```
result
![image](https://user-images.githubusercontent.com/4228180/89897494-62343500-dbdf-11ea-9738-d23d6b63c957.png)

For my taste the SQLite engine handles some "usual" stuff way too loose 🙄
SQL-Server or any other DBMS would fire up the alarm if trying those things 🔊 

Well, anyway, thanks for your responses.

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by justinclift** [comment]
Oh, as a thought since you're coming from a different database, it might be useful to cast your eye over the list of SQLite PRAGMA's:

&nbsp; &nbsp; https://sqlite.org/pragma.html#toc

The `PRAGMA` is a SQLite specific keyword used for setting (or querying) various configuration option in the SQLite engine.  Most stuff is probably not relevant most of the time, but things like enabling or disabling [foreign key checks](https://sqlite.org/pragma.html#pragma_foreign_keys) can be done through them. :smile:
