### ISSUE TITLE
Adjust rows to contents crashes program

### ISSUE THREAD

**Issue by rik1301** [sqlitebrowser/sqlitebrowser#2365]
Hi, I have a table of 440,000 records.  Several of the cells contain writing which is longer than the column width, so gets truncated in normal view unless you expand the column width to view it, or select the cell to open the full editor.

I read on a previous ticket that clicking on the row margin and selecting 'adjust rows to contents' solves the problem.  But when I do this it crashes the program as it freezes and never completes so have to force close and reopen.  I have tried it with a smaller dataset of just 25,000 records and eventually after approx 30 seconds it completes and resizes the row heights to accommodate, but then all functions on the table work at the same glacial pace, such as trying to sort the columns when clicking on the header, filtering etc.  Once I deselect the 'adjust rows to contents' and let it truncate again, the table functions perform as normal without any delay.

My PC is an i7 4770k with 16 GB RAM so not a toaster.

OS is Windows 8.1 .

**Comment by justinclift** [comment]
Interesting.  That's definitely a bug of some variety.  @mgrojo will probably want to investigate. :smile:

@rik1301 Would you be ok to try our [latest nightly build](https://nightlies.sqlitebrowser.org/latest/) and see if that crash still happens for you?

**Comment by rik1301** [comment]
Justin, I'm afraid to say there is no noticeable difference using the new version :( : 

Version 3.12.99 (Aug 12 2020)

Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.12.8

SQLite Version 3.32.3.

A subset of 25,000 records still takes approx 30 seconds to process after 'adjust rows to contents' to word-wrap the longer cells (not a huge amount of them in my table, maybe about 20% of the total rows).  I've not tried it with my other 440k record database for obvious reasons.

**Comment by rik1301** [comment]
Btw, there's a bug in that nightly build.  Select a table, click 'modify table'.  Double click any of the fields in the list and the input box resizes to being much smaller in height than the blue background one.

**Comment by rik1301** [comment]
Just comparing it with 3.12.0, the whole panel seems to be bunched up in 3.12.99 with smaller text.  Looks much better and works fine in 3.12.0.  :)

**Comment by justinclift** [comment]
Oh well, was worth a shot just in case.  Thanks for trying it out @rik1301. :smile:

We'll need to wait for our more in depth developers to take a look at this.  Someone generally checks in each day or so, so it shouldn't be **tooooo** long to wait.  Hopefully. :wink:

**Comment by rik1301** [comment]
No probs Justin.  Happy to help. :)

**Comment by justinclift** [comment]
> ... the whole panel seems to be bunched up in 3.12.99 with smaller text.

Oh, I just remembered that we added extra customisation options for the font sizes of things in our development code.  What you saw is probably a follow on effect from that.  In theory (!) it should be fixable by playing around with the font settings in Preferences.  But, reverting back to 3.12.0 works too. :wink:

**Comment by chrisjlocke** [comment]
> Just comparing it with 3.12.0, the whole panel seems to be bunched up in 3.12.99 with smaller text. Looks much better and works fine in 3.12.0. :)

Can you attach a screenshot?  In the nightlies, the modify panel was ... well, modified ... cosmetically.  
Do you have a high dpi monitor?  Its not that throwing it out is it?

In Preferences, what value do you have for the application font size?

![image](https://user-images.githubusercontent.com/7872218/89992330-08824800-dc7d-11ea-9d97-fb91f711f352.png)

For me, 10 gives me this:

![image](https://user-images.githubusercontent.com/7872218/89992376-16d06400-dc7d-11ea-9eb9-3b9732327793.png)

So works OK...

**Comment by rik1301** [comment]
I don't have the nightly installed anymore.  I switched back to the stable version.

**Comment by chrisjlocke** [comment]
Just a nod that you don't need to 'install' the nightlies or stable version.  If you download the ZIP, you can just extract and run the .exe from there.  Useful to run the nightlies.  The nightlies are generally more preferable than the stable version - especially the longer between the two versions, as tweaks, fixes and amendments are added.

**Comment by mgrojo** [comment]
> So works OK. Try changing it to something mad like 15 (DB4S doesn't need to be restarted) then confirm the text is wacky

The columns in this table have hardcoded widths, so it is not strange that increasing the font size gives problems. I'll check if better results can be got from a fit-to-contents approach.

Regarding this issue, I've made a change to resize only the visible rows and it seems to work fine. They are resized on the fly, so we could expect the scrolling to be affected, but apparently, not too much. My bigger table with more than 1.75 million rows seems to work acceptably. @rik1301 could you report with the next nightly build how is your case?

**Comment by chrisjlocke** [comment]
> The columns in this table have hardcoded widths, so it is not strange that increasing the font size gives problems.

Aah no - I was just trying to confirm that if you set the font-size larger, the size change was actually taking effect.  Make it a nice large number so the change was noticeable - just checking first DB4S was changing the font-size as needed.

**Comment by rik1301** [comment]
Hi guys, just to come back to this I've fired up the latest nightly to check the changes to the 'expand all rows' or whatever it's called.  I can report that it now 'wraps' all truncated cells within a second or two, which is great news, however this causes a new problem in that the data grid view scrolling is extremely laggy/jerky on my 448k records and a notable increase in my CPU fan speed...  Sorting the columns works, as does filtering data, but with around 2-4 seconds delay typically, rather than it being near-instant on the 'fixed' row height version.

As for my settings, in the 'general' tab the font size is 8 and in the data grid tab I am using Verdana 10pt, content 5000/1000, field display regular - preview only n/a, filters 200, \ .

I note in other comments some say you only have 1000 records loaded at a time.  For reasons I don't know, all my records load and can be scrolled through, although if I scroll down a bit too fast I get the red background with 'loading...' for half a second before they appear.

I don't know if it makes any difference but this is an .sqb file I'm editing.

**Comment by chrisjlocke** [comment]
> I note in other comments some say you only have 1000 records loaded at a time. 

Yes, DB4S loads in 'batches', so that rather than spend 30 seconds filling the grid unnecessarily, it only fills it as you scroll through.

> however this causes a new problem in that the data grid view scrolling is extremely laggy/jerky on my 448k records

Is this on every scroll up and down, or only on the initial scroll, as the rows are rejiggled?

**Comment by rik1301** [comment]
Hi Chris, regrettably it happens all the time when attempting to scroll up and down.  I could email you the sqb if you would like to experiment with it yourself.

**Comment by mgrojo** [comment]
@rik1301, is there a noticeable difference while scrolling when you have the option to adjust row sizes or not? If not, the performance is related to the background reading of data as Chris described. There is a preference setting  ("Database > Prefetch block size")  for adjusting the number of records which are loaded each time. You can play with that value and left it to whatever value it gives better response in your platform.

**Comment by rik1301** [comment]
" is there a noticeable difference while scrolling when you have the option to adjust row sizes or not?"

Not sure what you mean here.  The option is there all the time over the row numbers.  You can either toggle it or or off.  In its 'off' default state, the scrolling is smooth and instant, for the entire 448k records.  No problems at all - works exactly as one would expect.  Of course, in this mode the cells with contents greater than the column width are truncated with ... until one double clicks on the cell to open the editor or expands the column.

In the 'expand all rows' setting, it word wraps all the longer cell contents onto 2+ lines, retaining the column width, and does this for all records within a few seconds, but then when you try to scroll up and down the table it's extremely laggy and jerky, clearly struggling to process the data in this format, and filter searches, column sorts take several seconds to perform.

If I deselect 'expand all rows' back to the default setting, everything becomes smooth and fast again.

**Comment by rik1301** [comment]
"There is a preference setting ("Database > Prefetch block size") for adjusting the number of records which are loaded each time. You can play with that value and left it to whatever value it gives better response in your platform."

This doesn't seem to do anything.  It was 50k by default.  I have tried it at 2000, saved, nothing changes.  The data in the grid is still the full 448k records and laggy scrolling.  Also tried just 500 records, saved and that doesn't change anything either.  Maybe I'm doing something wrong?

**Comment by chrisjlocke** [comment]
> In the 'expand all rows' setting, it word wraps all the longer cell contents onto 2+ lines, retaining the column width, and does this for all records within a few seconds, but then when you try to scroll up and down the table it's extremely laggy and jerky,

I wonder if DB4S is calculating that the cell contents are greater than the width, so adjusting the height, regardless of the current height.  I haven't looked at the code, so don't know.  Might be that its resetting the heights unnecessarily as each row is scrolled into view.  Only a guess...

**Comment by rik1301** [comment]
I've uploaded to .sqb to my google drive.  If I've set the sharing permissions right you should be able to download it and see the problem first hand : https://drive.google.com/file/d/1j6K6V6L7YyhhfvK8YHYVX8D-87KBGsjj/view?usp=sharing

**Comment by rik1301** [comment]
Any further work on this, gentlemen, or still on the 'to look at' list?

**Comment by chrisjlocke** [comment]
Its currently 'on the list' ... but its a long list.... ;)
