### ISSUE TITLE
I cann't type ( give commands) in SQLlite, what should i do?

### ISSUE THREAD

**Issue by afygit** [sqlitebrowser/sqlitebrowser#2370]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by justinclift** [comment]
When you try typing commands, what's happening instead?

**Comment by chrisjlocke** [comment]
@afygit - Any chance of a screenshot?  Are you actually opening a database?  You have to open a database first, then the options within DB4S open.  
What operating system are you using?

**Comment by chrisjlocke** [comment]
*cough*

**Comment by justinclift** [comment]
Meh, lets just close this.  It's probably bot spam or similar.

**Comment by chrisjlocke** [comment]
Interesting that it seemed to come from DB4S (has the about info from the application).

**Comment by justinclift** [comment]
Oh, good point.

**Comment by mgrojo** [comment]
I think we've just made so easy to open a bug from the program, that people follow the link from the menu because they have a minor problem, sign up in github as required, enter the problem and forget about it. They've probably solved it afterwards. I think we shouldn't bother about it, so it's good idea to close them after the first request for details is not answered.

**Comment by afygit** [comment]
I opened the database, I am typing through keyboard but nothing is coming
on the screen. As if it's not taking bin the input.

**Comment by chrisjlocke** [comment]
Thanks for replying back, but we really need more information.  This is like taking your car to a garage and saying, "I heard a noise.  Please fix."

Any chance of a screenshot? Where are you trying to type information?  What version of DB4S are you using?  What operating system are you using?  What are you trying to do - add a new table, change some data in a table?

**Comment by justinclift** [comment]
@afygit As Chris mentions, some screenshots or perhaps even a screencast (?) would be really useful here.

We **do** try to help, but we need to know what we're dealing with. :smile:

**Comment by afygit** [comment]
I have attached the clip to this email.

**Comment by chrisjlocke** [comment]
Attachments don't attach here, unfortunately.  Can you email the attachment to me, db4s.issue.2370@chrisjlocke.co.uk
Thanks!

**Comment by scottfurry** [comment]
(ClamAV)[https://www.clamav.net/] is your friend

**Comment by chrisjlocke** [comment]
An antivirus engine? 😕 Have you posted that in the right thread?

**Comment by scottfurry** [comment]
yup. Earlier comment about emailing attachments. Trying to look out for you. :)

**Comment by chrisjlocke** [comment]
Aaw, thanks.  Have a picture of an elephant in return. 😃 

![image](https://user-images.githubusercontent.com/7872218/90861741-268a2f80-e384-11ea-82c2-1edff17f0d6f.png)

**Comment by chrisjlocke** [comment]
Closing this as no further information given.  Issue can be re-opened once we have more information.
