### ISSUE TITLE
Edit database cell shortcut to exit the pop-up window

### ISSUE THREAD

**Issue by rik1301** [sqlitebrowser/sqlitebrowser#2374]
Hi.  Is there a shortcut to exit the 'edit database cell' pop-up when editing a large cell?  I have found purely through some experimentation that CTRL + RETURN saves the new cell contents, but annoyingly this doesn't close the editor at the same time, all it does is make the 'apply' button flash.  The ESC key would be the most likely candidate for doing it manually but this doesn't do anything.  Pressing RETURN in the cell editor creates a new line rather than saving the contents.

**Comment by rik1301** [comment]
I note that ALT F4 works, but only when the full window is selected.  Can this be reconfigured somewhere?

**Comment by chrisjlocke** [comment]
The 'edit database cell' window is a docked window, and is open all the time - its not a modal window only open when needed, so technically, can't be 'closed'.  After editing, you simply click 'Apply' then click into the next cell you need.

**Comment by rik1301** [comment]
Hi Chris, The problem is that it gets in the way of editing the data.  ie. it's impossible to edit the data without having to use the mouse to click on various buttons to do stuff.  Hence the question how to bypass this requirement by using the keyboard only.  I personally have no need for the docked window being permanently active and am able to edit all cells with just the keyboard, except I can't because there's seemingly no way to avoid this pop-up without having to waste time reaching for the mouse to click on the button.  Is this intentional behaviour or a bug ?

I've noticed reading through the other tickets there are a lot of questions about shortcuts for the grid view, or lack thereof.  There is an abundance of shortcuts for the SQL editor panels but basically everything on the grid view involves having to use mouse at some point.  I think that most of us using the grid are probably current or former Excel users so we're expecting Excel-esque front-end functionality for moving around and editing the cells, which often isn't there or requires a convulted way of doing it.  I realise that the program isn't an Excel clone and is never intended to be one, but it may go some way to explaining why there are so many questions and feature requests for grid editor shortcuts and other 'WYSIWYG' functionality. :)

**Comment by chrisjlocke** [comment]
You can 'close' the edit database cell via the [x]

![image](https://user-images.githubusercontent.com/7872218/90334638-02ff6780-dfc7-11ea-8f6b-d1d210205374.png)

Or clicking 'View' and de-selecting 'View Edit Database Cell'.

![image](https://user-images.githubusercontent.com/7872218/90334651-1a3e5500-dfc7-11ea-9de5-04fa4c9fc97c.png)

Apologies  - I thought you meant close it as in 'Click OK to save changes and make it close like a dialog' kind-of way.

**Comment by chrisjlocke** [comment]
> so we're expecting Excel-esque front-end functionality for moving around and editing the cells, which often isn't there

Unfortunately, we're limited with the grid control that's part of the Qt framework, and how that works.  I think the worst one is the dropdown 'suggestion' that appears that can't be tabbed out of or arrowed out of - you have to press Enter first.

**Comment by rik1301** [comment]
Hi Chrs, understood - yes, I did think it could be to do with restrictions with the design at your end otherwise you'd have probably already implemented it.  But all is not lost as your reply above with the CTRL E option to close it is a workable solution for me.  Thanks.

**Comment by justinclift** [comment]
Personally, I reckon the "automatically open the Edit Database Cell" thing still seems to get in the way sometimes.  I'm almost tempted to add some way to toggle it's behaviour (eg disable it unless explicitly opened), but we'll see... :wink:

**Comment by chrisjlocke** [comment]
It doesn't appear if you stop double-clicking in a cell 😉

**Comment by rik1301** [comment]
Hi Chris.  Is there another way to QUICKLY edit a long cell then, that I'm not aware of?  I realise I can SLOWLY click the cell once, then 2 seconds later click it again to highlight it, then another second later to place the cursor where I want, but I don't know of a way to do that quickly as attempting to do so just brings up the editor pop-up instead.  If I cell the once just once then when I start typing it deletes the entire cell contents.

**Comment by chrisjlocke** [comment]
You can click once in a cell and press [F2].

**Comment by rik1301** [comment]
Hi Chris, well it's still an annoyance, but as you said above, it's a limitation of your Qt framework design so kinda stuck with it!

**Comment by chrisjlocke** [comment]
Its no different (theoretically) to Excel.  I guess the only thing that could be helpful is an 'always-in-edit-mode' - so if you click a cell, it simulates pressing [F2] so always goes into Edit straight away.  That would have to be a toggle though, as you wouldn't be able to select a range of cells, or select a cell to delete it, etc...

**Comment by justinclift** [comment]
It might be helpful for us to add some kind of Preferences option, so double clicking does the same thing as F2 (inline editing), rather than using the Edit Database Cell dock.

When I'm doing lots of text data entry, the Edit Database Cell is more harmful than helpful.  Conversely, when doing other stuff (working with image files), it's really useful.

**Comment by chrisjlocke** [comment]
> so double clicking does the same thing as F2

Single-clicking  😉 .  You'd want single-clicking to go into edit-mode, then press [Esc] to return to 'select-mode'.  Click in another cell, and back into edit-mode again.  The only annoyance would be text would be selected, so you'd still need to click AGAIN or press [Home]/[End], etc... but hey, it can't work exactly how everyone wants...

**Comment by justinclift** [comment]
Errr no?  Single clicking selects/highlights a cell without going into edit mode.  Double clicking should go into edit mode.

Hmmm, that's how it seems "in my head" anyway.  That could turn out to be wrong. :wink:

**Comment by chrisjlocke** [comment]
Yes, that's what currently happens, but to speed up editing, it would be
handy if you could single-click into cells.  If you wanted to select a
cell, simply press [Esc] to return to select-mode.  Just a suggestion that
single-clicking to edit is quicker and sometimes more 'intuitive' than
having to double-click.  Maybe.  I'm OK as I tend to write my own
applications anyway - when you write a data-entry form, each textbox is
immediately editable - you don't double-click in one first.

**Comment by chrisjlocke** [comment]
I'll close this as the issue has been answered.
