### ISSUE TITLE
Scaling is wrong at HDPI monitor

### ISSUE THREAD

**Issue by ChristophAxthelm** [sqlitebrowser/sqlitebrowser#2375]
Details for the issue
--------------------

#### What did you do?
* Open DB Browser for SQLite

#### What did you expect to see?
* Correct font size for all UI elements

#### What did you see instead?
* The font sizes of the buttons and tab headers are too small
* The font size of the Menu ("File", "Edit", "View", etc.) have the correct font size.

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

* Display settings of main screen:
  * Resolution 3840x2160
  * Scaling 150%
* Display settings of second screen:
  * Resolution 1920x1080
  * Scaling 125%

**Comment by justinclift** [comment]
Not sure if it'll help with the HiDPI problem, but we've recently added a bunch of extra Preferences settings for changing the size of UI elements.

The changes are in our nightly builds, if you're up for trying that out?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
As a thought, the workaround [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/2305#issuecomment-652221799) might help with this. :smile:

**Comment by scwithrow** [comment]
I just tried the latest nightly build (23 Sept, 64bit MSI) and I still have the similar problem with the font sizes being way too large. Nomatter what screen (of 3) I use the fonts look like the below.  The workaround above doesn't change things.

If in doubt, "name", "type", "schema", and app title are the right size, everything else is wonky.

![Screenshot 2020-09-30 154221](https://user-images.githubusercontent.com/71782609/94747366-90a6d480-0333-11eb-89a5-03a59e994e79.png)

The screen resolutions are:

- laptop screen: 3840x2160 (250% recommended)
- Other two screens: 1920x1200 (100% recommended)

**Comment by chrisjlocke** [comment]
if you click 'Edit' and 'Preferences', what value have you got for 'font size' ?

![image](https://user-images.githubusercontent.com/7872218/94774667-49155c80-03b6-11eb-93c5-a6b00e5411c3.png)

I set this to 80, and got a UI similar to yours.

![image](https://user-images.githubusercontent.com/7872218/94774708-5a5e6900-03b6-11eb-9f23-0838add9df4b.png)

Try setting it to 9, then back to 8.  Or another value.  Or both.  Or all three.  Or something else... 😉

**Comment by scwithrow** [comment]
Well boogers! That was easy. It was set to 20 (why I know not) and setting it to 9 fixes all. I'm putting you in my will.  Thanks!

**Comment by chrisjlocke** [comment]
Glad you got it sorted!  I'll close the issue, but will monitor the will situation. 😉

**Comment by justinclift** [comment]
@ChristophAxthelm Out of curiosity, is your main screen an external monitor or a laptop screen?

**Comment by ChristophAxthelm** [comment]
> @ChristophAxthelm Out of curiosity, is your main screen an external monitor or a laptop screen?
> 
> Asking because we're [looking for suggestions](https://github.com/sqlitebrowser/sqlitebrowser/issues/2570) for a "HiDPI" screen to get one of our developers, specifically for testing HiDPI stuff.

@justinclift I updated the description (see above).

**Comment by justinclift** [comment]
@ChristophAxthelm Don't suppose you know the exact model # of the screen? (am wanting to look it up, just for comparing to other purchase possibilities)
