### ISSUE TITLE
Feature request: Please add a PPA for Linux Mint

### ISSUE THREAD

**Issue by deepsidhu1313** [sqlitebrowser/sqlitebrowser#238]
It will be better if we get a version for Linux, However windows version can be executed using wine.

**Comment by justinclift** [comment]
We support Linux already.  Some distributions already package us, though maybe not the very latest version.

Which Linux distribution are you using?  If a package for us doesn't exist, would you be interested in creating/maintaining one? :smile:

Btw - Instructions to compile on Linux are in [BUILDING.md](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md).  It's pretty easy. :wink:

**Comment by deepsidhu1313** [comment]
My apologies for not knowing that and my laziness :sweat_smile: . I am using Linux Mint 17.1. Can you please maintain a ppa for that.?

If you say i can maintain the ppa. :smiley:

**Comment by justinclift** [comment]
Sure.  If you can put together an initial PPA for Mint, we can add it to the download locations on the front page.  We can also include you in the release process (eg emails :smile:), so that Mint has packages ready for people at release time.

How does that sound? :smile:

**Comment by deepsidhu1313** [comment]
Good :+1: 

I will be free in next few weeks, i will be right to it.

**Comment by justinclift** [comment]
Awesome. We're planning on releasing v3.6.0 in a few weeks, on 18th April (roughly):

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/milestones

So, you have some time. :smile:

**Comment by deepsidhu1313** [comment]
Yeah sure , i will be free by then. :smiley:

**Comment by rp-** [comment]
for reference there is an PPAR for an older version. As I don't have really the time and motivation to keep the PPA up to date:

https://launchpad.net/~peinthor/+archive/ubuntu/sqlitebrowser

**Comment by deepsidhu1313** [comment]
@rp-  Thanks for the refrence that helped a lot. I will be using same code for packaging from previous ppa :smile:  And here is link to testing ppa

https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

Feel free to tag me with packaging issues. I will be happy to help and contribute to project as much as possible :smiley:  And as i don't use Sqlitebrowser in depth, it will be great if somebody can test ppa builds (or alternatively tell me how can i test (stress testing or other)  my build :P ).  Thanks .

**Comment by justinclift** [comment]
Cool. :smile:
