### ISSUE TITLE
Application freezes shortly after startup

### ISSUE THREAD

**Issue by lostless13** [sqlitebrowser/sqlitebrowser#2382]
#### What did you do?
Open program, approximately 15 seconds afterwards the program becomes unresponsive and freezes. It must be closed from the Task Manager. The crashpad_handler.exe is running. Programs has become unusable and does not recover.

I have tried 
- re-installing.
- nightly build.
- Portable app

All had the same result.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: 10 Pro

#### What is your DB4S version?

- [x] 3.12.0

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Thanks for reporting this.  Not seen this issue before.

You mention crashpad_handler but that's to do with Google Drive.  Does DB4S start but you're trying to open a database via Google Drive?  
There isn't a 'safe mode' of DB4S, and it doesn't normally open the last database by default - it usually just sits there bored waiting for you to open a database.
When you say its responsive, what is showing in Task manager - high CPU usage?

![image](https://user-images.githubusercontent.com/7872218/91234544-6148ea80-e72b-11ea-892a-0a7722aaf6ce.png)

Are you running the 32-bit version or the 64-bit version?  Have you tried both versions?
Might have to get you to run 'whatIsHang' by NirSoft, as this shows the stacktrace of the stuck program.
https://www.nirsoft.net/utils/what_is_hang.html

**Comment by lostless13** [comment]
I'm not trying to open a file on google drive. I can open a file before the program crashes but it also crashes if I don't open a file.

The application isn't showing up in whatIsHung. I am still able to resize/maximize/minimize the window but none of the other program UI elements work or react. The close button highlights on mouseover but doesn't work.

I've tried both portable, 32 and 64 bit releases plus the 64 bit nightly. All the same behaviour.

CPU usage is 0%. Memory 
![image](https://user-images.githubusercontent.com/24193723/91236076-3abb8d00-e6f4-11ea-8988-d1effba2d23d.png)

**Comment by chrisjlocke** [comment]
Thanks for the screenshot and extra info.  
The only other thing that DB4S does at program startup is check for updates/the latest version.  We've not had reports of this hanging, but it has displayed an error box.  I assume DB4S has the focus when you've tried to click UI elements - mind you, Windows 10 doesn't highlight the current application anymore ... only in the taskbar.
If you turn off the update check in the registry (as that setting would be used for the nightly/portable, etc) we could check that.  If you open regedit and go to Computer\HKEY_CURRENT_USER\Software\sqlitebrowser\sqlitebrowser\checkversion  then add a string value called 'enabled' and set it to 'false'

![image](https://user-images.githubusercontent.com/7872218/91238764-b558cc80-e735-11ea-9e23-867f77f44d08.png)

**Comment by justinclift** [comment]
This error is definitely in the "unusual" category.  Like Chris mentions, the first potential thing that **might** be causing it is the automatic update check.  Instead of having to muck around with the Windows registry, it's probably easier to go into Preferences and turn it off from there.  You'll need to make that change and save it before the application hangs, but 15 seconds is (generally) enough time to do that.  Though it might take a few attempts to get it done before it hangs. :wink:

With that setting off, hopefully future launches of the application don't hang.  If the hanging still happens though, then that wasn't it. :frowning:

**Comment by lostless13** [comment]
Sorry, for the delay. I tried disabling updates from the registry. That registry entry didn't exist so I created it with a false value. I also checked the preference and the updates were disabled.

It didn't change anything. The behavior persists.

**Comment by justinclift** [comment]
Thanks, that's good information.  Sounds like we'll need to figure out a different approach to solving this problem then, as that didn't work.  @karim @chrisjlocke Any ideas?

**Comment by lucydodo** [comment]
@justinclift I'm sorry to interrupt, How about requesting a process dump file?
(Just right-click on the DB4S in the unresponsive state in Task Manager and click the 'Create process dump' button.)

**Comment by chrisjlocke** [comment]
I've had it a couple of times where the toolbar isn't responsive, but other UI elements have been OK.  Restarting usually solves it.

@lostless13 - I presume you've got no developer versions of Qt installed?  Can only assume its a Qt issue with something thats installed...

**Comment by justinclift** [comment]
@lucydodo 

> I'm sorry to interrupt

No need to be sorry.  Helpful idea's are welcome. :smile:

> How about requesting a process dump file?

That sounds like a good idea too.

**Comment by lucydodo** [comment]
@chrisjlocke How about on the Details tab? Probably possible there.

**Comment by justinclift** [comment]
This seems like it could be useful: https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

**Comment by lostless13** [comment]
I don't have a dev version of QT installed.

Here's the procdump. 
[DB Browser for SQLite.exe_200831_144913.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/5152586/DB.Browser.for.SQLite.exe_200831_144913.zip)

**Comment by chrisjlocke** [comment]
Just as final piece of the jigsaw, can we have a full-screen screenshot?  Just showing DB4S open with a database loaded.  Or even if you click 'File' and 'New database'.  At that point, it should 'crash' where you can't click on anything.  A screenshot of that would be grand.

**Comment by lucydodo** [comment]
@lostless13 Can you check if running DB4S from the command line with the following command reproduces the same problem?
`"DB Browser for SQLCipher.exe" -o checkversion/enabled=false`

P.S. I know that you edited it through the registry above,
but according to the dump file, the setting does not seem to have been applied.

**Comment by lostless13** [comment]
@lucydodo That made no difference. The application still locked up shortly after startup.

The freezing happens when I open the app regardless if a DB is open. Here's a screenshot with no db loaded and the app locked up.
![image](https://user-images.githubusercontent.com/24193723/91855390-58bc4c80-ec22-11ea-8c90-b067ff5242f2.png)

Here is an example where it locked up as I was creating a new DB.
![image](https://user-images.githubusercontent.com/24193723/91855671-b6509900-ec22-11ea-80b1-119605072277.png)

**Comment by lucydodo** [comment]
@lostless13 Do you have the Google Drive File Stream program installed?

**Comment by lostless13** [comment]
I do.

**Comment by lucydodo** [comment]
@lostless13 I asked two more questions through the edit function.
I guess you couldn't see it because you answered by email.

Could you also answer the questions below?
>Does DB4S continue to work when crashpad_handler.exe is force quit?
>Who signed the digital signature of crashpad_handler.exe? Google LCC?

**Comment by lostless13** [comment]
@lucydodo Sorry yes.

Signed by Google LLC.

Force quitting crash_handler does nothing.

Another thing I just noticed is if I go to open a file the crashpad_handler.exe shows up as a sub process when it freezes.
If I don't open a file, crashpad_handler does not show up as a subprocess. The application still freezes.

**Comment by lucydodo** [comment]
No need to sorry, because it's my mistake.

In order to reproduce the issue, I installed Google Drive File Stream, and it was confirmed that 'crash_handler.exe' is running as a DB4S subprocess. (When a file created or opened in DB4S) However, it does NOT freeze on my PC.

I asked you to confirm the 'Google LCC' digital signature because there were reports of some viruses pretending to be the process name 'crash_handler.exe'. but it was not.

If possible, can you please check if deleting the Google Drive File Stream will cause DB4S to work properly and if the same problem occurs after reinstallation? This is to identify if there is a conflict between the two programs or a DB4S's problem.

Sorry for not giving you a clear solution. 😢

**Comment by lucydodo** [comment]
cough

**Comment by lucydodo** [comment]
Close this issue because no response has been received for one week.
You can re-open this issue at any time by responding again.
