### ISSUE TITLE
Loading dialog takes over mouse position on Windows with Auto Move option on

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#2383]
Details for the issue
--------------------

#### What did you do?

On Windows, we have this useful option that move the mouse to a dialog button:

![image](https://user-images.githubusercontent.com/6388546/91234832-5d828b80-e75e-11ea-801b-627018348ebf.png)

However, with (not too) recent update, whenever I browse a column with a foreign key, DB would try to load the data of that table to make it into a select combo-box. That's fine by me although I am not using that feature but during the loading, a dialog box is shown and so my mouse is moved there, which is quite disruptive.

![image](https://user-images.githubusercontent.com/6388546/91234942-9d497300-e75e-11ea-8369-9851737cb4e4.png)

#### What did you expect to see?

The dialog should not show up, or should not have any button. I think there should be an option to either disable the loading dialog, or at least disable the feature completely if I do not need it.

#### What did you see instead?

My mouse is moved to an invisible button (maybe because I can never see it, it's too quickly).

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: 3.12.99 (Aug 25 2020 nightly build) but can confirm it happens since the latest stable build.

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I believe the dialog is a 'please wait while data is being loaded' alert.  I believe it may have a cancel button, which may be throwing off your mouse 'ping to a button' feature...
If you do load a large table, that dialog would need to pop up, so it would be hard to disable it completely.  We could wrap some 'if we've only taken a second, don't show the dialog, but its been three seconds now, so lets pop up a dialog' but that could be a fair bit of code, compared to the 'quick-n-dirty' way we're using at the moment....

**Comment by datvm** [comment]
Thanks for the response!

In WinForm/WPF, we could set the button as non-primary (i.e not default button). The mouse cursor wouldn't be moved if it is so. Is it possible for Qt? Or can I disable the whole feature?

**Comment by mgrojo** [comment]
We are using [QProgressDialog](https://doc.qt.io/qt-5/qprogressdialog.html). I've tried to set a cancel button without the [default](https://doc.qt.io/qt-5/qpushbutton.html#default-prop) and autoDefault properties but I've seen no difference in Linux. It still looks as a default button and pressing Space bar cancels the progress, so maybe the dialog is forcing the property. Should I commit it nevertheless to try it in Windows?

**Comment by justinclift** [comment]
> Should I commit it nevertheless to try it in Windows?

Might as well try it. :smile:

**Comment by mgrojo** [comment]
Confirmed as working in PR #2386.
