### ISSUE TITLE
Try to delete value NULL in the browse.

### ISSUE THREAD

**Issue by diegocampillo** [sqlitebrowser/sqlitebrowser#2384]
Details for the issue
--------------------

#### What did you do?
Open Browse data. Select value in a field. Edit cell and "Delete to NULL", but this button was enabled to false. I can't click it.

#### What did you expect to see?
Click on the button "Delete to NULL", and the value in the field had changed to NULL.

#### What did you see instead?
I can't do nothing.

Useful extra information
![Hardcopy](https://user-images.githubusercontent.com/29041029/91283852-70f81b80-e78b-11ea-8ca8-809d0ab53fd3.jpg)

-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Is it just a 'one-off' - if you click in another cell and back again, I presume the 'Editar Celda' dock has the focus.  Does the button become enabled again?

**Comment by MKleusberg** [comment]
The little icon next to "V_VOCABULARIO" indicates that this is a view. Data in views can't be edited, you'll have to change the data of the underlying table (or add some triggers and activate view editing).

**Comment by diegocampillo** [comment]
It's true. I was editing datas in a view, instead in a table. I'm sorry. Thank you for supporting me.

**Comment by MKleusberg** [comment]
No worries. Glad we could help :smile:
