### ISSUE TITLE
Clicking the result grid on Execute SQL tab crashes the app

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#2391]
Details for the issue
--------------------

#### What did you do?

Run a SELECT statement, click on the result table/grid

![image](https://user-images.githubusercontent.com/6388546/92310403-11460f80-efd8-11ea-8b52-61e3fa32f9ee.png)

#### What did you expect to see?

Select the data.

#### What did you see instead?

App crashes.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: 3.12.99 (Sep  3 2020)

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Ow.  Can confirm.  Application just dies - doesn't display any error or warning - just bombs out.

**Comment by MKleusberg** [comment]
Thanks for reporting this, @datvm! In theory the crash should be fixed now. Can you check tomorrow's nightly build and see if it's working for you? :smile:

**Comment by chrisjlocke** [comment]
I'll wait for @datvm to confirm before closing, but works OK for me.  Thanks for the quick fix @MKleusberg !

**Comment by datvm** [comment]
Can confirm it's fixed, thanks :D

**Comment by justinclift** [comment]
Awesome.  Good stuff all! :smile:
