### ISSUE TITLE
[Suggestion] Load or export user configuration file in a GUI environment

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#2393]
Describe the new feature
--------------------------
I recently made a change to user can use a user configuration file with code I committed. 0644bc094fa874012f47172a4175625aea282e8c

However, it still only works on the command line. Working from the command line would be inconvenient for most users compared to GUI environments. In fact, there were some people who used this program for education in [related issues](https://github.com/sqlitebrowser/sqlitebrowser/issues/2317).

So I propose to provide two menus as follows in GUI environment.
- Import Configuration
- Export Configuration
![Screen Shot 2020-09-08 at 2 08 56](https://user-images.githubusercontent.com/64626662/92409392-69694700-f17b-11ea-8770-314acbe210fe.png)
and I will also provide the option to permanently save the configuration(Windows registry or specified path by QSettings class) so that the user doesn't load the configuration file every time they run the DB4S. What do you think? 😄 
![Screen Shot 2020-09-08 at 2 09 03](https://user-images.githubusercontent.com/64626662/92409394-6c643780-f17b-11ea-9ec6-ce5b39093e70.png)
*It's not included in the screenshot, but it would be nice to warn that if click 'Yes', existing settings may be deleted.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
#2317 

#### Does this feature exist in another product or project? Please provide a link.
Many

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Already attached above.

**Comment by chrisjlocke** [comment]
Having it off the File menu is slightly confusing, considering to get to the configuration, you go to the Edit menu, and select 'Preferences'.  Preferences ... configuration ... is this the same thing?  
In the Preferences dialog, we have 'Restore Defaults'.  How about adding 'Export Preferences' and 'Import Preferences' there, then moving the 'Restore defaults' button.
This might mean the command-line switch needs to be reworded to 'preferences file' and not 'config file'.  Or maybe a config file holds preference information, so thats OK.  Heck, I hate this, and swear in my applications when I've added a 'New...' button in one form then an 'Add...' in another.
I think as we have 'Import', then 'Export' then 'Import Configuration', it looks a little muddled ... duplication.  There is already a lot of 'Opens' going on (and 'Open Project' at the bottom) muddying it even further.

Just a thought though ... so please don't take any notice of my ramblings! 😆

**Comment by lucydodo** [comment]
@chrisjlocke I think your idea is nice. 😄  I think it would be nice to create a new tab in the preferences dialog and implement the function I was talking and move the existing 'Restore Defaults' button.

Preferences? Configuration? I'm also wondering which word will be more natural. Personally, I think it would be good to express it as an 'Preferences' than 'Configuration' (Because it is already express as an Preferences and PreferencesDialog)

**Comment by chrisjlocke** [comment]
Another thought (from my thought...) is to reduce the size of the 'manage' button (does it have to be the screen width) and add a 'configuration' section with 'export' and 'import' buttons.

![image](https://user-images.githubusercontent.com/7872218/92411079-5a17d880-f13e-11ea-9e24-1bf9d16f5aab.png)

Dooodled that while you were doing yours! 😆

**Comment by justinclift** [comment]
Personally, I kind of like the concept of those two buttons in Chris' first screenshot:

![image](https://user-images.githubusercontent.com/7872218/92410615-99452a00-f13c-11ea-914e-c576d3071bc3.png)

But probably named "Export Preferences" and "Import Preferences", as they're already in the "Preferences" dialog?

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/92411252-f8a43980-f13e-11ea-872b-caadf3d5a88c.png)

**Comment by lucydodo** [comment]
Cool, then we better add two buttons at the bottom.
One more thing, it is currently expressed as configuration on the command line. Wouldn't it be nice change this to a 'preferences'? (Including changing the option from `-c and --config` to `-p and --preferences` at the same time)

**Comment by justinclift** [comment]
Yeah, probably best to try and keep things consistent. :smile:

**Comment by lucydodo** [comment]
Cool. Then it's time to tap on the keyboard!

**Comment by lucydodo** [comment]
@justinclift I'm sorry to keep bothering you. Shall I change the name of the environment variable 'DB4S_CONFIG_FILE' too?

**Comment by chrisjlocke** [comment]
I'm not a DB4S programmer, but it would help reading the code, especially for others.

**Comment by lucydodo** [comment]
I agree. For the consistent, I changed the name of the environment variable and committed it. d9fd0e17955d37622b6f6e84f856530c84408332
If @justinclift has any other disagreement, I will correct it immediately. Thank you.

**Comment by mgrojo** [comment]
Sorry to introduce more doubt but in fact, the settings include more
information than only the preferences like many settings that are adjusted
directly by the user in the application, like window layout, state of some
toggle buttons and the like. Might be irrelevant, but I wonder if user will
be surprised by that if we call it preferences.

On the other hand, what is this suppose to do? Import the configuration in
the file into the native "registry" or set the file as the settings store
for the rest of the session? "Import" suggests the former, but then, it is
something different to what one gets from the command line. Saying that
because it should not be called import if it's the same as the "-c" switch.
But what users would like from the GUI is something permanent, so a real
import is what we need.

**Comment by lucydodo** [comment]
@mgrojo Thanks for the comments. I'd like to give my thoughts on which expression would be more appropriate, 'Configuration' and 'Preferences', but it's difficult to comment because English is not my native language.
(I would appreciate this if other people discuss this 👀 )

and about on the second agenda I think it is because I simply came up with the word 'Import' without thinking of the word 'Load'. (similar reaons as above) I think it's good to give multiple options to user, but on the one hand, I think it might be better to just store permanently ('real import' in your expression) as you say.

What do other people think? 😄

**Comment by justinclift** [comment]
> Sorry to introduce more doubt but in fact, the settings include more
information than only the preferences like many settings that are adjusted
directly by the user in the application, like window layout, state of some
toggle buttons and the like. Might be irrelevant, but I wonder if user will
be surprised by that if we call it preferences.

Yeah, that's a good point.  If it does more than just preferences, we probably do need to use a different word. :thinking:

**Comment by scottfurry** [comment]
@justinclift - word your reaching for is _settings_

There are a few schools of thought about where to put menu entry. _By convention_, and assume you have a choice unlike MacOS, choices are *File*, *Help*, and *Edit*. Since we're dealing with an application level construct, my choice would be for the *File* menu. Also, Menu Item separators coupled with ellipses at end of action name (i.e. "Edit Settings...") can be employed to ensure this stands out or otherwise causes confusion.

My €/$0.02

**Comment by justinclift** [comment]
*Settings* sound reasonable.  Am kind of thinking "Export Settings" and "Import Settings" buttons (as per above button screenshots), unless that'd be too confusing to have in Preferences dialog?

**Comment by scottfurry** [comment]
On 2020-09-07 2:31 p.m., Justin Clift wrote:
>
> /Settings/ sound reasonable. Am kind of thinking "Export Settings" and 
> "Import Settings" buttons (as per above button screenshots), unless 
> that'd be too confusing to have in Preferences dialog?
>
This works. Analogous to Firefox where Export/Import bookmarks are apart 
of Bookmarks manager dialog.
Extra buttons on the bottom maybe?

**Comment by lucydodo** [comment]
I also searched the English-English dictionary, but 'Settings' seems to be a more appropriate expression.
'Configuration' seems to be an expression used in hardware. eg) `Here's the system configuration: CPU, RAM, SSD, VGA`

In summary, is it correct to express it as 'Settings', and to make the buttons at the bottom of the `PreferencesDialog`?
and, should we need to change the name to 'Settings' in `PreferencesDialog`? eg) `PreferencesDialog` -> `SettingsDialog`

**Comment by chrisjlocke** [comment]
Preferences would be something more user-centric.  Eg, the toolbar style you want, the font size, etc.  Settings would be more application-centric - window size, date last updated, etc.  The configuration would be what the application needs to work, eg, variables that can be tweaked/set, URLs it points to, etc.  There is a lot of grey area though - one configuration option could be a preference, etc, etc.  Its all up to different developers and the OS they use.  Eg, in Windows, everthing was Options.  'Tools' -> 'Options' has been a standard in Microsoft stuff for years.  Linux has been 'Preferences' or 'Settings', etc.

I don't think changing the name of the dialog would be necessary...

**Comment by lucydodo** [comment]
@chrisjlocke I understand. I just mentioned it for consistent. :wink:
