### ISSUE TITLE
HTML code without content passed to translation

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2395]
The html field of this QTextEdit passes a default value to translation that does not contain any visible text. This HTML code is the default of the field and cannot be removed from my version of QtCreator, but it seems to not have any purpose, since the widget does not accept rich text format.
https://github.com/sqlitebrowser/sqlitebrowser/blob/dfc7645079486193a81b545ee1e741dcda94e8d4/src/RemotePushDialog.ui#L49

@MKleusberg do you think we can remove this value safely using a text editor (since QtCreator refuses to leave it empty)?

**Comment by MKleusberg** [comment]
Yes, we can remove that safely. Unfortunately though Qt Creator seems to add it again every time you modify something in the form.  I have just changed the field to not get translated. Do you reckon this is good enough? Or should we investigate this further?

**Comment by mgrojo** [comment]
Thanks, that seems enough. It isn't overwritten by Qt Creator and removes the message from translation files. I've cherry-picked it into `v3.12.x`.
