### ISSUE TITLE
Cannot run 3.12.0 Mac version

### ISSUE THREAD

**Issue by amandapouget** [sqlitebrowser/sqlitebrowser#2398]
Details for the issue
--------------------

#### What did you do?
Downloaded 3.12.0. Tried to run app.

#### What did you expect to see?
The app

#### What did you see instead?
![image](https://user-images.githubusercontent.com/12855692/93356699-8225cc80-f80d-11ea-96ba-97b0da3eb9b3.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yeah, this is just because I didn't know Apple had changed their signing requirements, so the application isn't signed ("notarized") in the new way.

That'll be fixed for the next release, but in the meantime there's a workaround.  I'll dig up the info, give me a few minutes... :smile:

**Comment by lucydodo** [comment]
Duplicated issue, please refer #2346 issue.

**Comment by chrisjlocke** [comment]
and #2324 😄 
Someone is going to yell at me to add this to the Wiki in .... 5......4......3......2...........20......19......18........ 😸

**Comment by justinclift** [comment]
> to add this to the Wiki ...

That's a good idea @chrisjlocke.  Consider this a **\*yell\*** then? :wink:

**Comment by lucydodo** [comment]
I forgot to say it in advance. I'm working on a draft. After writing(and after eating all the snacks :smile: ), I will add on the wiki :)

**Comment by justinclift** [comment]
@chrisjlocke It probably belongs in the #1688 too. :smile:

@amandapouget Have you gotten it working?

If it helps, there's a Apple support doc on how to run applications which haven't (yet) been notarized:

&nbsp; &nbsp; https://support.apple.com/en-us/HT202491

**Comment by lucydodo** [comment]
I just added it to the [wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/macOS-warn-%27DB4S%27-is-malicious-software%3F), wiki table of contents and [Known Issue](https://github.com/sqlitebrowser/sqlitebrowser/issues/1688).
@chrisjlocke Thanks for the great idea! 😄

**Comment by justinclift** [comment]
@amandapouget We've just released version 3.12.1, which is Notarised on macOS, so should (in theory) launch properly now without any warnings:

&nbsp; &nbsp; https://sqlitebrowser.org/dl/#macos
