### ISSUE TITLE
When are nightly builds created and released?

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#2400]
What is your question
-----------------------
I'm just curious when the nightly build is created and released.

**Comment by justinclift** [comment]
The build for macOS starts at just after midnight (GMT), the win64 build starts just after 1am (GMT), and the win32 build starts around 2:30am (GMT).

Hmmm, those win64 and win32 times might be the other way around.  I'd have to log in and check, and can't be bothered at the moment. :wink:

**Comment by lucydodo** [comment]
Thanks for answering!
Seeing that builds for Win64 uploaded an hour and a half earlier than builds for Win32, I think you're right. 😉
