### ISSUE TITLE
Cannot save text opened in external application (Windows)

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2402]
Haven't used this feature before, but it appears when in the 'Edit Database Cell' dock, there is a button to edit the text in an external application (eg, Notepad, if on Windows).
However, it wasn't possible to save this text within Notepad - the file was locked (I assume by DB4S...)

Screencast: https://streamable.com/5bbtoj

So I clicked the button, edited the file, but when you save it, Notepad can't.  I saved the file elsewhere, but obviously, DB4S couldn't use this file.
I assume this will work on other OS's, that don't lock the files so strongly as Windows.
This was with the latest nightly.

**Comment by mgrojo** [comment]
Oh, you were the first to complain... it seems this new feature is not very used, or nobody cared in Windows.

Yes, in Linux it works without problem, but I've checked the code and it isn't obvious. In theory, the file is closed before calling the external application. I guess not everything is done synchronously.

Aha, so this is the problem:
> Reopening a [QTemporaryFile ](https://doc.qt.io/qt-5/qtemporaryfile.html)after calling close() is safe. For as long as the QTemporaryFile object itself is not destroyed, the unique temporary file will exist and be **kept open internally by QTemporaryFile**.

So Qt tried to outsmart me... (when I say _close_, it's _close_). Ok, I'll have to find an alternate way.

**Comment by mgrojo** [comment]
@chrisjlocke I'd figured out how to close the file before the external application is launched. I haven't tested in Windows. You know the proceedings :wink:

**Comment by chrisjlocke** [comment]
Works perfectly!  
Using it though, I'm wondering if the workflow could do with a tweak.
At the moment, you edit the file, save it, close the third-party application, return to DB4S, click 'Apply', and then have to click 'Apply' again (albeit a different 'Apply' button).  There is no need for the 'Cancel' and 'Apply' - it can simply be an 'OK'.  If you didn't want the changes, simply don't click 'Apply' when you return to DB4S - move cell.
At the moment, having to click 'Apply' implies you've applied it, when you haven't - you have to click 'Apply' a further time.

**Comment by mgrojo** [comment]
After having removed the Cancel and Apply buttons and replaced them by an OK button, I wonder if it make sense to have to click OK and then Apply in the Cell editor. Why not leaving the Cancel and Apply buttons in the dialog, and when clicking Apply saving the data directly in the cell. Clicking Cancel will, of course, throw the data away and not touch anything. The wording could be mostly the same as in the current revision:

```
"The data has been saved to a temporary file and has been opened with the default application. "
"You can now edit the file and, when you are ready, apply the saved new data to the cell or cancel any changes."
```
 The implementation is equally simple in both case. @chrisjlocke, what do you reckon?

**Comment by chrisjlocke** [comment]
Thanks for implementing this so quickly.  I haven't followed your last message - got a bit lost with the OK's and Apply's, so will download the nightly and have a look.... 👍

**Comment by mgrojo** [comment]
Oh, I might be expressing myself very badly :wink: I did not push anything I was just asking for your opinion. Nevertheless, I think that this last proposal is the best one, so I'll push it and wait for your impression

**Comment by mgrojo** [comment]
I've added d8ca11f57aead731fa185d2572e69932d1b5d6e8 to `v3.12.x` since it solved the problem and did not change any text. The improved version with the changed text goes to v3.13.

**Comment by chrisjlocke** [comment]
Thanks for the changes.  Yes, this works well.  Clicking 'apply' applies the changes straight into the cell. ❤️
