### ISSUE TITLE
Print preview window cannot be closed

### ISSUE THREAD

**Issue by Crystoppher** [sqlitebrowser/sqlitebrowser#2404]
Details for the issue
--------------------

#### What did you do?
I clicked on the "print" tab. A new tab with the print settings has been detailed.

#### What did you expect to see?
There is no button with "exit" or "close" status in the print settings window.

#### What did you see instead?
I found out through trial and error that using the ALT + F4 commands or the right mouse button you can see the close button.

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-lp64] on Linux Mint 20 (linux/5.4.0-47-generic) [x86_64]
> using SQLite Version 3.31.1
> and Qt 5.12.5

**Comment by chrisjlocke** [comment]
When you say 'print tab', do you mean the print button? [1]
If a print window (not a print tab) appears, do you see an [x] to close it? [2]

![image](https://user-images.githubusercontent.com/7872218/93504652-aff43980-f911-11ea-85b4-afcf7d8d9918.png)

Maybe you could post a screenshot, as I'm unaware of a 'print tab'.

**Comment by Crystoppher** [comment]
print button @chrisjlocke 

![Captura de tela de 2020-09-17 14-37-55](https://user-images.githubusercontent.com/44615834/93507765-8a0c6c00-f8f4-11ea-9fff-f111b38a323b.png)
The button close in not visible in window "Print Preview". Only with command alt+f4 or button right the mouse.

![Captura de tela de 2020-09-17 14-38-20](https://user-images.githubusercontent.com/44615834/93507784-91cc1080-f8f4-11ea-984a-a5a835303176.png)

**Comment by Crystoppher** [comment]
@chrisjlocke 
Sorry!!
This is the version available in the Linux application manager.
I have an outdated version of the software.

![Captura de tela de 2020-09-17 15-10-36](https://user-images.githubusercontent.com/44615834/93510680-fd63ad00-f8f7-11ea-8120-4142aefa77b3.png)

**Comment by lucydodo** [comment]
@Crystoppher What desktop environment are you using?
In my Ubuntu VM(with Gnome 3.x), the close button appears fine.

**Comment by justinclift** [comment]
Interesting.  Wonder if that's the "system provided" print dialog, rather than one we've created?

Kind of suspecting it is, though I could be wrong. :man_shrugging:

**Comment by lucydodo** [comment]
@justinclift It seems to provided by `QPrintViewDialog`. I've found some ways to resolve this problem, but I'm not sure.
If @Crystoppher tell us what the desktop environment is, I'll install it and test. 😄

**Comment by mgrojo** [comment]
That seems a problem in either Qt or the desktop environment. Probably, we cannot do or should not do anything about it.

**Comment by Crystoppher** [comment]
> What desktop environment are you using?
> In my Ubuntu VM(with Gnome 3.x), the close button appears fine

Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana

**Comment by lucydodo** [comment]
There seems to be a misunderstanding.
What I'm talking about is a desktop environment like GNOME, KDE and XFCE, not a distribution.

**Comment by mgrojo** [comment]
@Crystoppher Take a look at this. It's similar to your problem: https://github.com/olivierkes/manuskript/issues/464

At the end, how this user solved it:
> The problem was located in System Settings / Themes. There are a bunch of settings for the style of OS ("Window borders", "Icons", "Controls", etc). Since I have been having my system from 2014, and always upgrading to a newer version (never a clean install), there were apparently some residues (I think it was the theme with increased contrast in the "Window borders" sub-setting) that caused this issue. Changing it to a new one completely solved the issue.

**Comment by Crystoppher** [comment]
> There seems to be a misunderstanding.
> What I'm talking about is a desktop environment like GNOME, KDE and XFCE, not a distribution.

**linux-mint@linuxmint-H14BT58:~$** echo $XDG_CURRENT_DESKTOP
X-Cinnamon

**Comment by Crystoppher** [comment]
> @Crystoppher Take a look at this. It's similar to your problem: [olivierkes/manuskript#464](https://github.com/olivierkes/manuskript/issues/464)
> 
> At the end, how this user solved it:
> 
> > The problem was located in System Settings / Themes. There are a bunch of settings for the style of OS ("Window borders", "Icons", "Controls", etc). Since I have been having my system from 2014, and always upgrading to a newer version (never a clean install), there were apparently some residues (I think it was the theme with increased contrast in the "Window borders" sub-setting) that caused this issue. Changing it to a new one completely solved the issue.

I will research this tutorial. 
Thank you @mgrojo  :+1:

**Comment by lucydodo** [comment]
Thanks for response. I just installed and set up the VM based on the following environment:
- Linux Mint 20 with Cinnamon
- DB Browser for SQLite v3.11.2

And I created a sample database file and opened the print preview dialog, but the close button is appear.
<img width="1552" alt="Screen Shot 2020-09-19 at 2 07 38" src="https://user-images.githubusercontent.com/64626662/93626026-c7204d80-fa1d-11ea-8433-cddff1041895.png">
Probably this is due to the theme you are using(it looks different from the default installed theme).

Maybe I have to find another way. For now, the comments from @mgrojo might be helpful, so would you like to give it a try?
Sorry for not giving you a clear solution. 😢

**Comment by Crystoppher** [comment]
> Thanks for response. I just installed and set up the VM based on the following environment:
> 
>     * Linux Mint 20 with Cinnamon
> 
>     * DB Browser for SQLite v3.11.2
> 
> 
> And I created a sample database file and opened the print preview dialog, but the close button is appear.
> <img alt="Screen Shot 2020-09-19 at 2 07 38" width="1552" src="https://user-images.githubusercontent.com/64626662/93626026-c7204d80-fa1d-11ea-8433-cddff1041895.png">
> Probably this is due to the theme you are using(it looks different from the default installed theme).
> 
> Maybe I have to find another way. For now, the comments from @mgrojo might be helpful, so would you like to give it a try?
> Sorry for not giving you a clear solution. cry

@lucydodo 
Following the tutorial indicated by  olivierkes/manuskript#464  I ended up changing the current theme (Adapta-Nokto) to the standard linux mint theme and solved the problem.
Just by changing the settings in THEMES (window borders) the problem already solves. There must be some incompatibility.

![thema-default](https://user-images.githubusercontent.com/44615834/93627200-f2be1c00-f9ba-11ea-89cb-8aa3e86d0840.png)

**Comment by lucydodo** [comment]
Glad the problem was solved. If so, is it okay to close this issue?

**Comment by Crystoppher** [comment]
> Glad the problem was solved. If so, is it okay to close this issue?

Of course!
Thank you
