### ISSUE TITLE
feature request: resize multiple cols and rows in 1 go in the main QTableView

### ISSUE THREAD

**Issue by finjulhich** [sqlitebrowser/sqlitebrowser#241]
It would be nice to select multiple cols and get them all resized in 1 go as has been implemented here:
https://forum.qt.io/topic/16047/solved-qtableview-resize-of-several-columns/6

**Comment by justinclift** [comment]
@schdub This sounds like the kind of thing you would know how to do... any interest in doing this? :smile:

**Comment by schdub** [comment]
@justinclift, ок. Waiting when my previous pull-request will be merged.

**Comment by justinclift** [comment]
@schdub Done. :smile:

**Comment by MKleusberg** [comment]
Can we close this issue? The feature should be in the code since v 3.6.0 :smile:

**Comment by justinclift** [comment]
Sure. :smile:
