### ISSUE TITLE
Update Null value to empty string without query

### ISSUE THREAD

**Issue by emrecpp** [sqlitebrowser/sqlitebrowser#2410]
Details for the issue
--------------------

#### What did you do?
Trying to update null value to empty string ("") without query

#### What did you expect to see?
empty string ("")

#### What did you see instead?
Not executed, i need to run query for update. As I know, this was works in v3.11.2.

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
If you go to the 'Browse Data' tab and select the cells you want to clear, then press [Backspace], the cells will be empty.

https://streamable.com/yhwl1d

You can also right-click and select 'Set to NULL' if you want to return them to NULL values.

**Comment by emrecpp** [comment]
> If you go to the 'Browse Data' tab and select the cells you want to clear, then press [Backspace], the cells will be empty.
> 
> https://streamable.com/yhwl1d
> 
> You can also right-click and select 'Set to NULL' if you want to return them to NULL values.

Ahaha :) Thank you

**Comment by justinclift** [comment]
Awesome.  Good stuff @chrisjlocke. :smile:
