### ISSUE TITLE
No UI elements visible upon startup

### ISSUE THREAD

**Issue by toonvandeputte** [sqlitebrowser/sqlitebrowser#2412]
Details for the issue
--------------------

#### What did you do?
Open the application

#### What did you expect to see?
Default (empty) UI view

#### What did you see instead?
A fully grey window without any interface widgets:
<img width="1070" alt="Screenshot 2020-09-23 at 13 26 06" src="https://user-images.githubusercontent.com/6859906/94006758-9be08a00-fda0-11ea-9944-a67ce34ca10f.png">

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-lp64] on macOS 10.15 (darwin/19.6.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.12.8

**Comment by toonvandeputte** [comment]
Reboot magically resolved it. Still unsure what the root cause was.
Maybe it's useful to know that Trend Micro Security is running on my system.

**Comment by chrisjlocke** [comment]
Thanks for reporting back what solved it.  Not seen this glitch before!
