### ISSUE TITLE
Is there a way to disable the "save project" dialog?

### ISSUE THREAD

**Issue by franksands** [sqlitebrowser/sqlitebrowser#2417]
What is your question
-----------------------
I use DB browser 99% of the time as a viewer and almost never change any information in the db. So I would like to disable that dialog that always asks if I want create a project when closing the application

**Comment by chrisjlocke** [comment]
> I really hate retyping SQL queries

Thats why I create applications - sledgehammer to crack an apricot... ;)

**Comment by franksands** [comment]
> I really hate retyping SQL queries.
Me too, that's why 99% of the time, I use the "browse data" view, instead of typing an sql query. And when I do have to create a query, they're rarely the same.
So, is there an option to disable the be prompt to save the project?

**Comment by justinclift** [comment]
Oh, the read-only approach might be easiest.

**Comment by franksands** [comment]
> Not to be argumentative, but when you open Notepad or any other editor or spreadsheet and type stuff, how/why would you disable the prompt to save?

Actually, if Notepad had the same behavior, it would always ask if I want to create a "Notepad project" besides the file I was currently editing. Also, still in the text editors field, Sublime does not nag me about creating a Sublime project for each file I edit there. I have no problems DB browser asking me if I want to save the changes I might have made to the db file, but I do not have any need to create a "Sqlite project" or anything of the sort.

**Comment by justinclift** [comment]
Ahhhh, that makes sense.  If you're not already using a project file, then it makes sense it shouldn't always ask about them.

That should be ~reasonably easy for us to adjust in some way. :smile:

**Comment by franksands** [comment]
Thank you. Should I open a feature request? Since this was open as a question.

**Comment by justinclift** [comment]
Nah, no need to.  The question and conversation here have the needed details. :smile:

**Comment by lucydodo** [comment]
@franksands I modified the code by as I understood and create a [PR](https://github.com/sqlitebrowser/sqlitebrowser/pull/2420).
If there is no problem after code review, this will be reflected. Thanks for enhancement idea.

**Comment by franksands** [comment]
Thanks, I'll close this issue

**Comment by lucydodo** [comment]
@franksands Oh, there is no need to close the issue. We generally ask the initial suggester to confirm that the DB4S has been made to the what suggester want after a code change. 

However, it has already been closed and I will only ask for a simple confirm, so I will keep it closed.
(Also a bonus of not sending unnecessary re-open notification to others :wink: )

**Comment by justinclift** [comment]
Oops.  I just reopened this before reading the last part of your comment @lucydodo. :wink:

**Comment by chrisjlocke** [comment]
Oh and now I've just had an unnecessary re-open notification 🤣 🤣 🤣

**Comment by lucydodo** [comment]
Good news! The code just passed the review and merge in the master branch. You can try it the next nightly build. 😄 
Disable the 'Save Project' dialog by disabling the 'Prompt to save SQL tabs in new project file' option in the preferences.

Please give us feedback so we can close the issue after you testing :)
>NOTE: The next nightly build is scheduled to start on Oct 5, 2020 at 00:00.

**Comment by franksands** [comment]
I tested today an it works perfectly. I was able to run SQL queries and close the app without the prompt to save the project.

**Comment by justinclift** [comment]
Fantastic!  Thanks heaps for testing it, and letting us know @franksands. :smile:

Well done team. :smile:
