### ISSUE TITLE
Export sql doesn't name insert columns

### ISSUE THREAD

**Issue by galmok** [sqlitebrowser/sqlitebrowser#242]
When exporting the database to SQL with the purpose of importing the data from one of the tables via SQL to another database, it would be extremely helpful if the columns were named in the INSERT statement. This would make the insert work even if the columns were in a different order in the target database (my situation),

I can solve it by replacing the INSERT word like this:

INSERT INTO `SomeData` VALUES (1,34,37,463);
to:
INSERT INTO `SomeData` (col1,col2,col3,col4) VALUES (1,34,37,463);

I would be nice if this tool could do this automatically.

**Comment by justinclift** [comment]
Yeah, that makes sense.  We'll probably need some kind of dialog so people can choose their preferred options too. :smile:

**Comment by justinclift** [comment]
@galmok Our very latest code has a new export dialog for changing options with the output CSV file.  One of those options is to explicitly state the column name in the output.

Do you want to take a look and make sure it would work for your situation?  The nightly build (tomorrow) would have the changes included, if that helps. :smile:

**Comment by justinclift** [comment]
Closing this as it was fixed ages ago. :smile:
