### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by ultranet1** [sqlitebrowser/sqlitebrowser#2423]
import sqlite3
conn=sqlite3.connect('gbongan.db')
cur=conn.cursor()
#cur.execute("create table street2 (id integer PRIMARY KEY, building text,color text, number integer, FOREIGN KEY (id) REFERENCES number (id))" )
#id1=('mosque', 'brown', '1')
print('MY STREET DATABASE')

print('BUILDING | COLOR | NUMBER')
sql1=("INSERT INTO street2 VALUES(1,  'mosque', null,  1)\n")
cur.execute (sql1)
sql2=("INSERT INTO street2 VALUES(2,'my house', 'red', 2)")
cur.execute(sql2) 
sql3=("INSERT INTO street2 VALUES(3,'laquinta', 'yellow', 3)")
cur.execute(sql3)
sql4=("INSERT INTO street2 VALUES(4, 'palace', 'white', 4)")
cur.execute(sql4)
view=('SELECT building, color, number FROM street2')
cur.execute(view)
row =cur.fetchall()
for i in row:
	print(i)
print('.....')
print('.....')
print('.....')
print('MY NEIGHBORS DETAILS')

sql5=("CREATE TABLE neighbors1 (id int primary key, name text, date date, number int)")
cur.execute(sql5)
sql6=("INSERT INTO neighbors1(name, date, number) VALUES(?,?,? )")
cur.execute(sql6,('baba_ariet', '01/03/1999', 1))
cur.execute(sql6, ('aditi', '01/05/2005', 2)) 
cur.execute(sql6,('iya_bidemi', '06/07/2015', 3))
view1= ("SELECT * FROM neighbors1") 
cur.execute(view1)
row1=cur.execute(view1)
for i1 in row1:
	print(i1)

print('\nLIST OF TABLES')
view2=("SELECT name FROM sqlite_master ")
cur.execute(view2)
row5=cur.execute(view2)
for i3 in row5:
	print(i3)
	
#print(cur.fetchmany(6)

sql7=("SELECT id, building, color, number FROM street2 ")
cur.execute(sql7)
row2=cur.execute(sql7)
for i2 in row2:
	print(i2)
print('..')

sql8=("INSERT INTO street2 VALUES(5,'Cocoa', 'white', 5)")
cur.execute(sql8)
street2_id=cur.lastrowid
print(street2_id)

#TO GET LAST ROW
sql9=("SELECT id from street2")
cur.execute(sql9)
lastrow=cur.lastrowid
print(lastrow)

#TO GET MIDDLEROW
sql10=("SELECT id from street2")
middlerow=cur.lastrowid
cur.execute(sql10)
print(middlerow)

dbs=("insert into street2 values(6,'hall','gold', 6)")
cur.execute(dbs)
dbs1=cur.execute(sql7)
for i6 in dbs1:
	print('The result is', i6)

print('....... ')
#dbs2=("delete from street2 where ")
#cur.execute(dbs2)
#dbs3=cur.execute(dbs2)
#for i7 in dbs3:
#	print(i7)
#dbs3=cur.execute()

#dbs4=("CREATE DATABASE osogbo")
#cur.execute(dbs4)
#dbs5=cur.execute(dbs4)
#for i8 in dbs5:
#	print(i8)

#dbs01=("backup database gbongan.gb to disk ='data/file/0'") 
#cur. execute(dbs01)  

print(sqlite3.version)

**Comment by justinclift** [comment]
Hi, this looks like you're trying to run some Python code that does SQLite?

If that's the case, then it's not really the kind of thing that "Issues" here are for. :wink:

**Comment by chrisjlocke** [comment]
Also, you have a /n where you shouldn't.

![image](https://user-images.githubusercontent.com/7872218/95241521-c94c1f80-0805-11eb-8ba3-d243641593fd.png)

**Comment by lucydodo** [comment]
I think, this person is not familiar with GitHub yet, so I think it was written by mistake.
Actually, looking at activity overview in his profile, the same or similar issues were created in other repositories.

Therefore, I judge this issue as spam or mistake and close it.
