### ISSUE TITLE
Can't see number of rows of my queries

### ISSUE THREAD

**Issue by Ignacio-Ibarra** [sqlitebrowser/sqlitebrowser#2429]
Details for the issue
--------------------

Suddenly, I cannot see the results view as I did before. When I run a query I can see the what is in each rows and columns, but I can't see how many rows are involved. When the number of rows involved in my query is 0 or when i get an error the result screen remains blank

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?
What operating system are you using?
Can you provide a screenshot of the result screen.

**Comment by mgrojo** [comment]
Maybe the results pane is collapsed? Please, provide more info or we'll have to close this issue.

**Comment by chrisjlocke** [comment]
Closing due to lack of response.  @Ignacio-Ibarra - feel free to comment further so we can assist.
