### ISSUE TITLE
print each table data structure on a separate page

### ISSUE THREAD

**Issue by rtwRichard** [sqlitebrowser/sqlitebrowser#2433]
Describe the new feature
--------------------------
It would be useful have the database structure print the details for each table on a separate page for documentation purposes.   

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by lucydodo** [comment]
Thanks for your interest in our project.
I understand your enhancement idea roughly, but it would be better if there was little more detailed explanation. :smile:

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@rtwRichard - Feel free to comment back if needed.
