### ISSUE TITLE
install Sortierfunktion iso8601

### ISSUE THREAD

**Issue by brunodepuerto** [sqlitebrowser/sqlitebrowser#2438]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by scottfurry** [comment]
FWIW, sqlite doesn't store date/times in a dedicated type.
See [this](https://www.sqlite.org/lang_datefunc.html) background on date/time functions.
Sorting functions based on iso8601 may be extra functionality for DB4S.

**Comment by mgrojo** [comment]
Note that sorting ISO dates is the same as sorting strings, so it should not be a problem for SQLite.

Closing this, as it did not provide enough information.
