### ISSUE TITLE
+Infinite and -Infinite Expression on Export Database to SQL file

### ISSUE THREAD

**Issue by DongilKim** [sqlitebrowser/sqlitebrowser#244]
Create Sample Table using "Import/Database from SQL file" function

> CREATE TABLE foo (x DOUBLE);
> INSERT INTO foo VALUES (9e999); -- +Inf
> INSERT INTO foo VALUES (-9e999); -- -Inf
> INSERT INTO foo VALUES (9e999 / 9e999); -- NaN: gets converted to NULL

This foo table has these values

> 'Inf'
> '-Inf'
> 'NULL'

Export foo table to SQL using "Export/Database to SQL file" function. This SQL Statement generates error on "Inf".

> CREATE TABLE foo (x DOUBLE);
> INSERT INTO `foo` VALUES (Inf);
> INSERT INTO `foo` VALUES (-Inf);
> INSERT INTO `foo` VALUES (NULL);

I think that this is right. What do you think about this?

> CREATE TABLE foo (x DOUBLE);
> INSERT INTO `foo` VALUES ('Inf');
> INSERT INTO `foo` VALUES ('-Inf');
> INSERT INTO `foo` VALUES (NULL);

**Comment by justinclift** [comment]
Hmmm yeah, that doesn't sound good. :frowning:

**Comment by justinclift** [comment]
@DongilKim Do you have time to try out the next nightly build, and see if it's working properly for you now? :smile:

**Comment by DongilKim** [comment]
I have tested using 11-Apr-2015 02:15 nightly build. Everything's OK. Thank you. @justinclift @schdub

**Comment by justinclift** [comment]
Awesome!  Thank you @schdub for this, and thank you @DongilKim for checking and letting us know. :grinning:
