### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [sqlitebrowser/sqlitebrowser#2446]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/db-browser-for-sqlite-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80-%D0%B1%D0%B0%D0%B7-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B4%D0%BB%D1%8F-sqlite.html).

The project is interesting, so please don't abandon it!

**Comment by chrisjlocke** [comment]
Thanks for the link on that website.  I'll close this issue as its not technically an issue, but we thank you kindly anyway. 👍
