### ISSUE TITLE
Error with NN checkbox

### ISSUE THREAD

**Issue by fvlasie** [sqlitebrowser/sqlitebrowser#2447]
Details for the issue
--------------------

#### What did you do?
Modify Table > Add Field and click the NN checkbox 

#### What did you expect to see?
The NN checkbox becomes selected

#### What did you see instead?
An error stating "There is at least one row with this field set to NULL. This makes it impossible to set this flag. Please change the table data first."

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

MacOS: (10.15.7 )

#### What is your DB4S version?

- [x] 3.11.2

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just confirming - why is this an error?
Do you have any data in this table?  Are any rows (in the row you've clicked 'NN' on) have any NULL values?

**Comment by fvlasie** [comment]
Thank you for the reply.
The table already has data and I am adding a new column (field). The datatype is BIT and I would like the field to be either 0 or 1. If I set the default value to 0 and then check the NN box I still get the same message. 

As it works now, it seems impossible to use the NN checkbox when creating a new field. I would have thought that checking NN would either set the field to 0 or fill it with a default value.

**Comment by chrisjlocke** [comment]
This is more of a limitation with SQLite than DB4S.  Imagine building a house.  You've built three rooms.  All done.  Carpeted, wallpapered, decorated.  Now the owner has said, "Great job!  Now build a fourth room!  I want it wallpapered like the others."  As soon as you build the walls, the owner comes back and moans, "Why haven't you wallpapered yet?  Aargh!" and runs away screaming.
As soon as you add an empty column, the data in it has to be null.  

> If I set the default value to 0 and then check the NN box I still get the same message.

I don't tend to use the NN checkbox, so not 100% sure on the steps to do.  It might be that setting a default option sets ... well, a default option for new records, and doesn't populate existing records.

Before checking the NN box, can you run a check on the data ... `select * from table where newField is null`.
Does that return anything?
![image](https://user-images.githubusercontent.com/7872218/96546839-e7545e00-12a2-11eb-86d6-1ed5dcc15926.png)

If it does, just issue a `update table set newfield=0 where newfield is null`.

![image](https://user-images.githubusercontent.com/7872218/96546907-14a10c00-12a3-11eb-9591-b1f92accec06.png)

Then the 'NN' checkbox should work.  You're right - its 9,000 steps when one would do, but again, I believe its an SQLite limitation. 

Just checked, and setting 'default' on a new field does populate the records, so technically, those steps above shouldn't be needed.

![image](https://user-images.githubusercontent.com/7872218/96547125-72cdef00-12a3-11eb-8ab4-dafef516d0c2.png)

Also, adding a new field seems to work OK...

https://streamable.com/rnqjt4

v3.12 has been out a while, with 3.12.1 being released soon ... just hiding in the wings.  Can you try that and see if that works any better?

**Comment by fvlasie** [comment]
That makes sense. It creates the column with NULL values immediately when you click "Add field". What I do for a workaround is run a command to set the new column's values: ```update table set newColumn = 0;``` Then I can go back and set NN.

Thanks for a very useful project!

**Comment by chrisjlocke** [comment]
> What I do for a workaround is run a command to set the new column's values

You don't need to do that if you set a 'default' option when you create the field.

**Comment by fvlasie** [comment]
Well, I should have tested this before posting anything but the issue is resolved with the latest stable release (3.12.0). My apologies for wasting your time!

**Comment by chrisjlocke** [comment]
Yay!  Glad its resolved!  Thanks for reporting back.  👍
