### ISSUE TITLE
'Could not open database file - attempt to write a read-only database' error

### ISSUE THREAD

**Issue by Aonyiah** [sqlitebrowser/sqlitebrowser#2449]
I was trying to open a database I was already working on when I got the following error message:
![image](https://user-images.githubusercontent.com/13909761/96854812-d434c000-1453-11eb-81b4-f5bd6eae134f.png)

I did this by going to the File > Open database > Select database > Click open

I thought it might be a permissions restriction so I went to the file to check my permissions and it seemed okay. I looked around online for some answers but found nothing that made sense within the context of my situation. 

Can anyone explain why this happened and what I can do to prevent a reoccurrence in the future or at least to be able to resolve. 

I've had to reupload the database from scratch to do my assignment.

**Comment by justinclift** [comment]
That error generally happens when the file isn't able to be changed for some reason.

Seems like that's not the situation you were in though, which is confusing. :frowning: 

Without it still happening, it's kind of impossible to try and figure out what's wrong.

Um... probably the best we can do for now is →If it happens again, leave the file there and ask us, so we can suggest things to investigate.

**Comment by chrisjlocke** [comment]
This usually happens if DB4S can't create a journal file.
Where was the file located - on your computer or on a network location?
The file might have been locked in another application - could you have the file open elsewhere and/or another copy of DB4S opening the file?

**Comment by Aonyiah** [comment]
@justinclift 
_That error generally happens when the file isn't able to be changed for some reason._

What you are saying is that the file is not being transformed from one version to another. If that is correct then it's not a process I am familiar with. It would be helpful if you could elaborate on some examples, please. 

@chrisjlocke 
The file was located on my PC and I did see a journal file actually. It is possible that It was locked another file in which case, I would presume, discontinuing the program run would be the solution. However, all files were closed at the time. I'd only just booted up SQLite Browser to open the database before looking to open it. 
I don't have the files open elsewhere for it to be affected since I am working from home on my own personal computer with no shared networks. 

Thank you again for responding to my request.

**Comment by chrisjlocke** [comment]
> It would be helpful if you could elaborate on some examples, please.

I believe Justin means the file needs to be written to - the permission to change a file (write to it) is additional to the permission to read it.

> and I did see a journal file actually.

And how big was this journal file?  Was it more than 0 bytes?  If it was 0 bytes, then Windows has created it, but can't write to it.
If you close DB4S, then this journal file should also disappear.

**Comment by Aonyiah** [comment]
> > It would be helpful if you could elaborate on some examples, please.
> 
> I believe Justin means the file needs to be written to - the permission to change a file (write to it) is additional to the permission to read it.
> 
> > and I did see a journal file actually.
> 
> And how big was this journal file? Was it more than 0 bytes? If it was 0 bytes, then Windows has created it, but can't write to it.
> If you close DB4S, then this journal file should also disappear.
> 
> Where are you opening the database - on the desktop? My Documents?

the journal file is saved on a desktop folder and its 10kb in size

**Comment by chrisjlocke** [comment]
Is this with DB4S closed and nothing accessing the file?  Then 'technically' that journal file can be deleted.  Its unusual the journal file is there and is younger than the database itself - would imply there has been two applications accessing the database at the same time.  Usually when you save any changes, the journal is written to the database.
I'm sure its not, but just to rule it out (I'll have to try), try creating a 'SQL Projects' directory off the C drive (so c:\sql projects\database\Home value trends.db) and see how that goes.
I'm sure the apostrophe in your username has no bearing, but it would be interesting to try and rule that out.

**Comment by justinclift** [comment]
@chrisjlocke When I look at that screenshot, I notice the database file is newer than the journal file.  To me - not having really looked at journal files in ages - that seems like something is wrong?

**Comment by Aonyiah** [comment]
> Is this with DB4S closed and nothing accessing the file? Then 'technically' that journal file can be deleted. Its unusual the journal file is there and is younger than the database itself - would imply there has been two applications accessing the database at the same time. Usually when you save any changes, the journal is written to the database.
> I'm sure its not, but just to rule it out (I'll have to try), try creating a 'SQL Projects' directory off the C drive (so c:\sql projects\database\Home value trends.db) and see how that goes.
> I'm sure the apostrophe in your username has no bearing, but it would be interesting to try and rule that out.

Thanks for the reply, 
I think it was the journal file affecting it like you said initiating a lock when trying to access the file

**Comment by chrisjlocke** [comment]
I'll close this now, as this seems to be resolved.  @Aonyiah - has this occurred anymore?  Feel free to comment further where it can be reopened if necessary.

**Comment by Daiio** [comment]
Hi! This is also happening to me. DB Browser crashed while I was trying to run a join and when I went to reopen the database I was working on, it gave me the same error as Aonyiah. I now cannot open my database.

**Comment by chrisjlocke** [comment]
> DB Browser crashed while I was trying to run a join

In the directory where the .db lives, there should be a journal file.  Usually the same name as the database, but prefixed with '-journal'.
You can remove this journal file and DB4S should open the database, but beware that the database is possibly broken.  You should at the least run an integrity check on it, and at worst, revert to an earlier backup.
