### ISSUE TITLE
licensing information clarification

### ISSUE THREAD

**Issue by plusky** [sqlitebrowser/sqlitebrowser#245]
According to README.md, "DB Browser for SQLite is bi-licensed under the Mozilla Public License Version 2, as well as the GNU General Public License Version 3 or later." - it is not clear if this means that conditions of both licenses must be met at same time or that one or other license must be followed.

Thanks for clarification

**Comment by justinclift** [comment]
Well, it pretty much means when you're creating something from this project, you can choose whichever of the two licenses best suits you, OR you can use both of them.

  eg, if you're creating something to put in (say) the Apple Store - which forbids GPL usage I think - you'd want to use the Mozilla license for that.  You're obliged to only follow the Mozilla license terms then.

Conversely, you can do the same thing, but using the GPL license version instead.

Or, you could do what we do, and just do both. :smile:

It's really up to you. :grin:

Does that help?

**Comment by plusky** [comment]
Yes, thanks a lot for quick reply.

**Comment by glawrence** [comment]
Hope you don't mind @justinclift but I have added this to a wiki page now at https://github.com/sqlitebrowser/sqlitebrowser/wiki/Licensing as I thought this was worth documenting
