### ISSUE TITLE
Cannot edit data cells in new created tables

### ISSUE THREAD

**Issue by pbiotech** [sqlitebrowser/sqlitebrowser#2452]
Details for the issue
--------------------

#### What did you do?
I created a new db with a new table.

#### What did you expect to see?
Data entered into new table are saved

#### What did you see instead?
When I try to edit data cells in the new created table the black circle with the white cross inside of it is shown in the right side and the new entered data are not saved.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X ] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Any chance of a screenshot?
So here I create a table, add some fields, then browse the data.
https://streamable.com/3qhc7a

Its very much like Excel then - enter some figures, press Enter to 'save' or click in another cell.  Every now and then click the 'Write changes' to slap all changes in the database.

Can you confirm what steps you're doing, and where it differs from this?

**Comment by pbiotech** [comment]
Here is the screenshot of what happens - [https://drive.google.com/file/d/1eErToK--cFwROGgCh7MIZKLbgi_Nn62p/view?usp=sharing](url). The program worked perfectly until I created in the existing database a table named Version and a column in it with the same name. After that I am not able to populate any new created table, but am still able to add new records in the already populated tables. I tried SQLiteStudio and it worked good, see here - [https://drive.google.com/file/d/1KA_QqzYHw6v6ytMjsbOydxQW0zfeeM1a/view?usp=sharing](url). I then opened this db in the DB Browser and now it is able to add new records - [https://drive.google.com/file/d/1M_sEOYn5IxUl9rDjBHttqLDAdFYkY-7K/view?usp=sharing](url). Any ideas why DB Browser has such behavior? I like this program and would like to continue using it. Thanks

**Comment by chrisjlocke** [comment]
Aah yes, a common mistake.  You've 'added' a record into the filter row.  
Click the 'add record' button 

![image](https://user-images.githubusercontent.com/7872218/97094202-98178000-164a-11eb-9748-e39240479fd3.png)

See my screencast above, at about 16 seconds in.

**Comment by pbiotech** [comment]
Thanks. That filter row generates headache.

**Comment by chrisjlocke** [comment]
No problem.  Try the latest nightly, and the filter row has disappeared.  3.12.1 should be released shortly, which (I believe) also has this fix.  :)
