### ISSUE TITLE
attempt to write on read only database ?? 

### ISSUE THREAD

**Issue by amirorfi** [sqlitebrowser/sqlitebrowser#2456]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by amirorfi** [comment]
after django delete the sqlitebrowser can't open the data base ("attempt to write on read only data base")

**Comment by chrisjlocke** [comment]
"after django delete the sqlitebrowser "
I'm guessing this is spam.  
Feel free to prove me wrong, and this can be reopened.
