### ISSUE TITLE
to_date

### ISSUE THREAD

**Issue by popovanika** [sqlitebrowser/sqlitebrowser#2459]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Hi, is this a request for assistance with something? :smile:

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/97464752-35b7cb80-1939-11eb-8690-ce012c6fffbf.png)
