### ISSUE TITLE
Feature request: Data browsing using Database Structure table selection

### ISSUE THREAD

**Issue by stef145g** [sqlitebrowser/sqlitebrowser#246]
A really cool feature would be to allow the user to select "Browse Data" on a popup selection when the table has been selected on the Database Structure tab.

Alternatively, when the selection of a table is made on the Database Structure tab, the table selection is automatically updated on the Browse Data tab. This would allow the user to switch to the Browse Data View and have the data for the selected table ready for viewing without having to reselect the table using the dropdown box.

**Comment by Z4us** [comment]
Not a bad plan, very user friendly, except the automatic update of tables you may design a databases with special tables reserved for future, special use e.g. only developers, bits, the system etc. You should make them invisible to avoid users to manipulate them.
 I'm afraid adding this feature is more complicated and certainly more risky than you think at first thought, but to put it in a more positive light: "Nothing is impossible."

**Comment by stef145g** [comment]
@MKleusberg , This now makes examining a database much easier in version 3.6.0.
Thanks for providing this feature.
