### ISSUE TITLE
struggled by 'group by" data type

### ISSUE THREAD

**Issue by chris3392** [sqlitebrowser/sqlitebrowser#2463]
Details for the issue
--------------------

#### What did you do?
Table oppty with 145k entries, column Stagename is a set of 9 different values (all text)
(1) Select stagename from oppty;  -> "plot" window shows StageName as Axis type = Label (correct)
(2) Select stagename from oppty group by stagename ;  -> "plot" window shows StageName as Axis type = Numeric (incorrect).
(3) Supress the "group by" and execute again: 
Select stagename from oppty;  -> "plot" window shows StageName as Axis type =Numeric (incorrect).

I have to issue an entirely different request (as on another table) then the ""Select stagename from oppty;  -> "plot" window shows StageName as Axis type = Label (correct)"", (as if there would be some kind of "reset" of the plot window outputs

It seems the code is out of control once I add a group or order clause.

#### What did you expect to see?
for (2) and (3), should see Axis type = Label

#### What did you see instead?
See above

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

Ubuntu 18.04

#### What is your DB4S version?

3.12.0

#### Did you also
No I did not.
Will be happy to try once you confirm it should solve above issue.

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
There is a slight chance that this is the same issue as #2286 which was solved a couple of weeks ago. Are you ok with giving the latest version from the master branch a try by compiling it yourself? We can assist you of course if you have any problems while compiling DB4S.

**Comment by chris3392** [comment]
Hi Martin,

As mentionned, would be willing to compile and test.
Please provide relevant instructions to download / compile

Brgds

Le 08/11/2020 à 18:25, Martin Kleusberg a écrit :

**Comment by mgrojo** [comment]
@chris3392, please, take a look at https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu--debian-linux and confirm if we can close this issue.

**Comment by chris3392** [comment]
Hi, will do later if possible otherwise by end of week.
Thanks for returning to me on this.

Le 07/12/2020 à 22:07, Manuel a écrit :

**Comment by mgrojo** [comment]
Let's suppose this was the same problem and close this, since it's growing old. @chris3392 don't hesitate to reopen it if that weren't the case.
