### ISSUE TITLE
Display the row count of every tables in one view

### ISSUE THREAD

**Issue by MuleaneEve** [sqlitebrowser/sqlitebrowser#2464]
Describe the new feature
--------------------------

I would like to be able to see the number of rows in all the tables of a database in one view.

When I want to explore a database with a lot of tables, I want to skip the ones that are empty or to prioritize the ones that have a lot of rows. Currently, I am forced to go through all of them one by one in "Browse Data".

My suggestion is to add a new column in "Data Structure" and "DB Schema" to display that number for each table.
If there are performance concerns, maybe that column can be empty by default, and the user has to click a button to load it...

An alternative would be to add a menu item (similar to Tools -> Optimize) that computes all these counts and display them in a new "Execute SQL" tab.

**Comment by justinclift** [comment]
> An alternative would be to add a menu item (similar to Tools -> Optimize) that computes all these counts and display them in a new "Execute SQL" tab.

That might be the better approach, at least initially.  For most databases (pretty small in size), automatically counting the number of rows in each table and displaying them would be pretty trivial.

But for large databases (say 500MB+) with no indexes, it could be a right pain.  Having a way to make it optional, or a make it a specific action, would probably avoid that pain. :smile:

**Comment by MuleaneEve** [comment]
I would be happy with the menu item.

By the way, I am talking about `COUNT(*)` and I think that it is an O(1) function (that doesn't use indexes). Still, with a lot of tables, it could take a second or two (and we do not to re-compute it every time a table changes).

**Comment by MKleusberg** [comment]
> By the way, I am talking about `COUNT(*)` and I think that it is an O(1) function (that doesn't use indexes). Still, with a lot of tables, it could take a second (and we do need to re-compute it every time a table changes).

I thought so too but I just tried with a ~2.9GiB database of one table with 17,673,915 rows and it took ~25 seconds on my system. But even if it was a faster operation, databases with many tables would be a performance problem.

But adding a menu item should be no problem at all :smile:

**Comment by MKleusberg** [comment]
@MuleaneEve I have added a new menu item called "Show Row Counts" to the Tools menu which should do just what you want. Can you try tomorrow's nightly build and see if it's working for you? You can download it [here](https://nightlies.sqlitebrowser.org/latest/) tomorrow.

**Comment by MuleaneEve** [comment]
Awesome.
I just read the code in the commit, and everything looks good. I will confirm tomorrow after testing the nightly build.

**Comment by MuleaneEve** [comment]
I've tested this feature and it is working as expected.

Thank you!

**Comment by MKleusberg** [comment]
Awesome, thank you for testing :smile:
