### ISSUE TITLE
release restorpoint

### ISSUE THREAD

**Issue by jmhel** [sqlitebrowser/sqlitebrowser#2465]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by MKleusberg** [comment]
Can you provide some more details, @jmhel? :smile:

**Comment by chrisjlocke** [comment]
I'm 92.7% this is just spam.  Didn't see this come in earlier, otherwise I'd have closed it...
