### ISSUE TITLE
HiDPI on Windows

### ISSUE THREAD

**Issue by sandman7920** [sqlitebrowser/sqlitebrowser#2468]
Describe the new feature
--------------------------
It will be nice HiDPI to be enabled by default.

```cpp
int main( int argc, char ** argv )
{
#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
    QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling, true);
#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
    QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
#endif
#endif
    QGuiApplication::setAttribute(Qt::AA_UseHighDpiPixmaps, true);
```

Additional info
---------------
Currently one could use QT_AUTO_SCREEN_SCALE_FACTOR and QT_SCALE_FACTOR_ROUNDING_POLICY environment variables, but I'm not sure how many people know about them..

Screenshots
---------------

**Enabled**
![image](https://user-images.githubusercontent.com/3589417/98028609-06acc880-1e17-11eb-89fb-54a1b7e6fcd9.png)

**Disabled**
![image](https://user-images.githubusercontent.com/3589417/98028650-13c9b780-1e17-11eb-95fd-9c22e01aa9c4.png)

**Comment by chrisjlocke** [comment]
You're more than welcome to submit a PR as it looks like you've half the code already! ;)

**Comment by sandman7920** [comment]
Tomorrow I will submit PR.
