### ISSUE TITLE
Add header license on each file

### ISSUE THREAD

**Issue by dridk** [sqlitebrowser/sqlitebrowser#247]
Create a file "header" containing licence header .
Then : 
for file in *.cpp *.h
do
cat header $file > $file.new
mv $file.new $file
done
~

**Comment by justinclift** [comment]
When you say a licence header file, what are you meaning?  Something to do with our licensing?

**Comment by richardfontana** [comment]
Not needed, except (perhaps) in cases where the header is already present in a file you take in whole or in part from some other project. There are arguments for and against per-source-file notices; practice around this issue varies quite widely.

**Comment by justinclift** [comment]
Thanks Richard. :grinning: :

@dridk Closing this, as it looks like it's unnecessary.  Thanks for taking the time to open the issue, and get us to look into it though.  Hopefully cuterest goes really well. :smile:
