### ISSUE TITLE
Error when connecting TLS initialization failed

### ISSUE THREAD

**Issue by ineuw** [sqlitebrowser/sqlitebrowser#2473]
Details for the issue
--------------------

#### What did you do?
Opened  DB Browser for SQLite 
Version 3.11.99 (Jan  7 2020)
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.6
SQLite Version 3.30.1

#### What did you expect to see?
No connection error

#### What did you see instead?
Received connection error 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?
Windows 10 Pro 2004 OS build    19401.610

#### What is your DB4S version?
- [x ] 3.11.99 (Jan  7 2020)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
![connection issue with sqlitebrowser](https://user-images.githubusercontent.com/10367016/98482096-e8efb280-21cc-11eb-87c2-3a45dfa805cb.png)

**Comment by chrisjlocke** [comment]
> Version 3.11.99

Version 3.11 has been superseded by v3.12 now, and this issue should be fixed.  You can download the latest version from here:
https://sqlitebrowser.org/dl/#windows
