### ISSUE TITLE
Sorting data in table browser on datetime column

### ISSUE THREAD

**Issue by swidz** [sqlitebrowser/sqlitebrowser#2474]
Details for the issue
--------------------

#### What did you do?

Brows table data and sort suing datetime column 

#### What did you expect to see?
sort descending or ascending by datetime

#### What did you see instead?
sort in alphabetical order

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by swidz** [comment]
Sorry, works as expected. I have not notice that it was a TEXT typed column

**Comment by justinclift** [comment]
No worries at all @swidz. :smile:
