### ISSUE TITLE
DB Browser for SQLite cannot be opened because of a problem. (3.12.1 on MacOS Catalina)

### ISSUE THREAD

**Issue by lpn25** [sqlitebrowser/sqlitebrowser#2476]
Details for the issue
--------------------

#### What did you do?
Installed version 3.12.1 on the current MacOS Catalina 10.15.7. It went through the malware check just fine: 

> “DB Browser for SQLite.app” is an app downloaded from the internet. Are you sure you want to open it? 
> Safari downloaded this file today at 01:38. Apple checked it for malicious software and none was detected.

#### What did you expect to see?
When opening expected to see the main DB Browser for SQLite window

#### What did you see instead?
For some reason can't upload a screenshot, but got the following:
> DB Browser for SQLite cannot be opened because of a problem.
> Check with the developer to make sure DB Browser for SQLite works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
> Click Report to see more detailed information and send a report to Apple

The previous version 3.12.0 works just fine after reinstalling it.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ 10.15.7)
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: 3.12.**1**

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Uh oh, that's not good. :frowning:

Is there some way to get further information about what "the problem" is?

**Comment by chrisjlocke** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/issues/2472#issuecomment-723823653 maybe?

**Comment by justinclift** [comment]
Looks like a problem with the SQLCipher library that we compiled.

I'll investigate shortly.  In the meantime, I'll update our download pages to point at the older 3.12.0 release for macOS.

**Comment by lpn25** [comment]
> [#2472 (comment)](https://github.com/sqlitebrowser/sqlitebrowser/issues/2472#issuecomment-723823653) maybe?
> @lpn25 - Is the error you received?

Yes, I got the same error

**Comment by justinclift** [comment]
Thanks @lpn25, that's helpful.

I'm rebuilding the macOS version of the release now, to try and figure out why that library is missing from it.

**Comment by andy60** [comment]
@justinclift the for help, let me know when i can download the mc release rebuilded

**Comment by justinclift** [comment]
Well, it looks like today is going to be "macOS build process fixing day". :wink:

**Comment by andy60** [comment]
great, thx @justinclift

**Comment by andy60** [comment]
> Well, it looks like today is going to be "macOS build process fixing day". 😉

hi @justinclift plz let me know when new version is compiled

**Comment by justinclift** [comment]
@andy60 I'm still working on it.  It turns out we need to use the `macdeployqt` tool from Qt 5.15.x (rather than Qt 5.12.8, which we were using).

And Qt 5.15 can only be installed using the Qt Company's "Online" installers.  Which don't allow for choosing the download server, so installation takes about 13 hours instead of 20 minutes (not exaggerating).  So, I left it running overnight.  The good news it that Qt 5.15.1 installed properly overnight, so I'm continuing on... :smile:

**Comment by andy60** [comment]
I work on my db, if a decide to change a table I create another one and go on. For the moment. I like this software, others are not at the same leve. Thx for your work.

**Comment by justinclift** [comment]
@andy60 Would you be ok to try this?

https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-v2.dmg

It's a new build of version 3.12.1, using the latest Qt release (5.15.1), and is "Notarised" by Apple.  In theory it should work ok... but I'd like some more people to test it before I put it on our main download page. :smile:

**Comment by lpn25** [comment]
> @lpn25 @andy60 Would you be ok to try this?
> 
> https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-v2.dmg
> 
> It's a new build of version 3.12.1, using the latest Qt release (5.15.1), and is "Notarised" by Apple. In theory it should work ok... but I'd like some more people to test it before I put it on our main download page. 😄

It opens fine for me, the previous error didn't occur. I didn't have time to test whether it has any issues when using it, though.

**Comment by justinclift** [comment]
Thanks @lpn25, that helps. :smile:

**Comment by justinclift** [comment]
Closing this, as the problem has been solved.  Thanks heaps for letting us know and helping out @lpn25. :smile:
