### ISSUE TITLE
Windows (.msi) Installer Evaluation Warning (ignorable), but also crashes later

### ISSUE THREAD

**Issue by p-schneider** [sqlitebrowser/sqlitebrowser#2477]
Details for the issue
--------------------

#### What did you do?
I downloaded `DB.Browser.for.SQLite-3.12.1-win64.msi` (and verified the sha-256 hash)
Then I launched the msi Installation. (Version 3.12.0 is currently installed - had been installed using .msi as well)
Got **warning** message on "Welcome" screen of Installer:
![warning](https://user-images.githubusercontent.com/2636101/98538617-5235fb00-228b-11eb-9360-56adbb71c8fb.png)
After ignoring the message with `[OK]` I was able to click through the setup assistant Next->Next->Next etc.
Within the Installation process (after UAC Confirmation) an **error** message pops up:
![error](https://user-images.githubusercontent.com/2636101/98539069-02a3ff00-228c-11eb-87a2-5f613b22c6f2.png)

_Just a sidenote: 
The DPI/Zoom setting in the 3.12.1 msi seems to be off. (I don't really mind having different/strange DPI behaviour during setup, but it's odd.)_
![3.12.1 dpi](https://user-images.githubusercontent.com/2636101/98539234-46970400-228c-11eb-966b-c0569e1e0664.png)
_For comparison on the same Computer running the 3.12.0 msi (after uninstalling 3.12.0 - otherwise I wouldn't see that screen):_
![3.12.0 dpi](https://user-images.githubusercontent.com/2636101/98539407-907fea00-228c-11eb-8e8f-e3b75881aeb6.png)

#### What did you expect to see?
No Warning or Error messages.

#### What did you see instead?
1. **Warning** message about Evaluation Version of "Advanced Installer" (can be ignored)
2. **Error** message during setup (after giving Admin priviledges via UAC prompt)
3. _Strange DPI/Zoom behaviour - 3.12.0 msi works fine, 3.12.1 msi looks strange (that's not important, just a sidenote)_

Useful extra information
-------------------------

Testing Nightly .msi (SHA-256 D83A76E29135E8A317BBD5A2A930492C3217A0C40C3B06F6A04CE08B2AF89920)
Today's **nightly .msi installer works fine** (in all 3 points mentioned above) - but I'm not sure if the 3.12.1 release is currently newer or older than the latest nightly.

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 20H2 )

#### What is your DB4S version?

- [x] 3.12.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaargh!

This was licenced software.  (Advanced Installer).  Grr.
I'll contact them now.

**Comment by chrisjlocke** [comment]
Thanks for reporting this.  This should be corrected now, and replacement .msi files should be in place shortly.
If you require one sooner, drop me an email and I can wing you a copy. :)

**Comment by justinclift** [comment]
Heh Heh Heh.  This is turning out to be an interesting release.  We probably should have made it a "Release Candidate 2" instead, from trying out new packaging for both Windows and macOS. :wink:

**Comment by MKleusberg** [comment]
We have just uploaded a new version of the MSI installers (and removed the original ones from the release page). Can you try again with the new version, @p-schneider? :smile:

**Comment by wrldwzrd89** [comment]
> We have just uploaded a new version of the MSI installers (and removed the original ones from the release page). Can you try again with the new version, @p-schneider? 😄

I just tried the new Windows 64-bit MSI installer and it works! No crash, no funky scaling issues and no warning about a trial version.

**Comment by p-schneider** [comment]
@MKleusberg Thank you, it's all fixed now. Works as expected.
You can now update the links in https://sqlitebrowser.org/blog/version-3-12-1-released/ (incl. SHA256SUMS).

**Comment by justinclift** [comment]
Awesome.  Updated the website with the new -v2 links. :smile:
