### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by donno2048** [sqlitebrowser/sqlitebrowser#2479]
# The new feature
Just use `ctrl` +`F` to search in the database

Additional info
---------------

#### Is the feature request related to an issue?
I don't think so
#### Does the feature exist in another product or project?
I guess *every* editor for text-based data has this feature

**Comment by justinclift** [comment]
In theory, with our 3.12.0 release onwards this should work. As per:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts#edit-dialog-and-edit-pane

If it's not working for you though, that's probably something to be investigated. :wink:

On the other hand, if you're using and older version then upgrading is probably the right thing to try. :smile:

**Comment by donno2048** [comment]
This is working in the 3.12 release, thanks.

**Comment by justinclift** [comment]
You're welcome @donno2048. :smile:
