### ISSUE TITLE
Error message when launching DB4S

### ISSUE THREAD

**Issue by JannesMeyer** [sqlitebrowser/sqlitebrowser#2480]
Details for the issue
--------------------

#### What did you do?

I opened the application

#### What did you expect to see?

No errors

#### What did you see instead?

The error message `Unable to open default EUDC font: "C:\\Windows\\FONTS\\EUDC.TTE"`

![image](https://user-images.githubusercontent.com/704336/99157936-b9114500-26cd-11eb-8e13-7b93b207fd8d.png)

Useful extra information
-------------------------

The error dialog can be dismissed without any issues. Nevertheless it is a bit annoying to have to do that every time I open the application.

I noticed that no font file exists at the referenced path. However, if I launch `eudcedit.exe`, draw a custom symbol and save, it creates the file in question and the DB4S error goes away.

#### What operating system are you using?

Windows 10.0.18363.1198

#### What is your DB4S version?

3.12.1 (tested 32bit and 64bit)

#### Did you also

- [x] Try out the latest nightly version
- [x] Search for an existing similar issue

**Comment by JannesMeyer** [comment]
I found a Qt commit that contains the error message: https://github.com/qt/qtbase/commit/9e99dba4a22bbf212b3e6d1e2607a16dbbd04d90

Does this project use Qt by any chance?

**Comment by justinclift** [comment]
Yep, we use Qt. :smile:

**Comment by justinclift** [comment]
I don't think anyone's reported this particular error message before.  At a complete guess, maybe go into the DB4S Preference menu, and see if any of the font settings are pointing towards that "EUDC" font?

It kind of sounds like that font is being used by "something".  And if that "something" can be switched to a font that's actually around then maybe the problem would be solved in a more useful way.

**Comment by JannesMeyer** [comment]
Hmm, it's strange because I have used other Qt apps before, but it's the first time I am seeing this message.

I think VLC also uses Qt, right?

The font file doesn't exist on my Windows 10 installation, but it looks like Qt assumes the registry key `SystemDefaultEUDCFont` points to a file which exists on every system.

The Qt commit message contains the following sentence:

> This has been tested on a couple of systems, and appears to always be present.

I guess they were wrong about that... Maybe I need to create a bug report for Qt then?

**Comment by JannesMeyer** [comment]
> At a complete guess, maybe go into the DB4S Preference menu, and see if any of the font settings are pointing towards that "EUDC" font?

The DB4S preferences are all set to default. The data browser font is set to "MS Shell Dlg 2" and the SQL fonts are all set to "Courier New"

**Comment by JannesMeyer** [comment]
I managed to "solve" this by launching `eudcedit.exe`, drawing some custom character and clicking `File -> Save`. This created the missing EUDC font file for me.

![image](https://user-images.githubusercontent.com/704336/99158909-3641b780-26d8-11eb-8c13-fb79c7d05c7b.png)

**Comment by justinclift** [comment]
Cool, at least there's a workaround. :smile:

> I guess they were wrong about that... Maybe I need to create a bug report for Qt then?

If you've the time for it, then that would be helpful. :smile:

**Comment by chrisjlocke** [comment]
I'll close this as the initial issue has been resolved.  Thanks for at least reporting back what the solution was, @JannesMeyer

**Comment by KirkH420** [comment]
I got this error too, but I sort of think it only started after I was goofing around, looking at the different places that the GodMode directory can take me to. So I went back there where the eudcedit.exe is referenced as "Private Character Editor", as was suggested above and created 1 character and it did go away.

Is it possible that the other people who've experienced this issue, also have visited the in-built "PCE" when they were maybe checking out where those godmode shortcuts take them?.....and then exited without creating anything? This editor probably adds something to the registry when it's opened for the first time, or something.

**Comment by justinclift** [comment]
Er... what's the "God Mode" thing you're meaning? :smile:

**Comment by chrisjlocke** [comment]
> what's the "God Mode" 

Its a GUID you enter into Windows and it takes  you to an admin control panel of a lot of options you can change in Windows, many of which don't normally have a GUI to get to them, only by amending the registry direct.
"Here be dragons".

**Comment by JannesMeyer** [comment]
Hmm. At least in my case I don't remember ever having used a "god mode" GUID.

I may have caused the issue in a different way, but it's long ago and hard to say what exactly caused it for me.

**Comment by KirkH420** [comment]
Are you serious?
I thought everybody knew what was.
Well... a web search will pull up several pages of references to this topic.
All you do is create a New Folder and then you name the folder  GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}

The string "GodMode" is really arbitrary but that's just what everybody on the internet calls it.

Once you enter the name, your folder will transform into a nameless Control Panel Icon which.
Inside it are Dozens of shortcuts for navigating your system. 
How many really depends on Home/Pro/Enterprise

**Comment by KirkH420** [comment]
How I or anyone else gets to the "Private Character Editor" probably doesn't matter.
What I was saying was... SOMEHOW i navigated to the Private Character Editor.

**Comment by chrisjlocke** [comment]
> Are you serious?

Incredible as it may seem, not everyone uses Windows.  if you're not a Windows user, you're not going to know or even want to know, about 'God mode'.
