### ISSUE TITLE
Typo in French translation

### ISSUE THREAD

**Issue by alessandroCharbonnier** [sqlitebrowser/sqlitebrowser#2486]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
It's written "Bzse de DOnnées en cours" which should be "Base de Données en cours".
![Screenshot_3](https://user-images.githubusercontent.com/35409610/99903032-fc694600-2cc1-11eb-9d7f-f3149fa6439b.png)

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by alessandroCharbonnier** [comment]
not urgent :)

**Comment by lucydodo** [comment]
Thanks for reporting. You can edit translation file yourself and send us a PR, or we can take care of it. Which method is better? 😄

**Comment by alessandroCharbonnier** [comment]
Seems like I cannot fount the typo in the src/translations/sqlb_fr.ts file...

**Comment by mgrojo** [comment]
> Seems like I cannot fount the typo in the src/translations/sqlb_fr.ts file...

That's because we hadn't yet brought some of the translations from the v3.12.x branch to the master branch. They are now included in the main development branch and the type fixed. Thanks for reporting! It will be fixed in the next [nightly build](https://nightlies.sqlitebrowser.org/latest/).

**Comment by MKleusberg** [comment]
I just double checked if this is fixed and it looks good :+1: Thanks, @mgrojo, for the fix and thanks, @alessandroCharbonnier, for pointing this out! :smile:
