### ISSUE TITLE
Edit Database Cell - potential for data loss

### ISSUE THREAD

**Issue by tenbob** [sqlitebrowser/sqlitebrowser#2488]
#### What did you do?
Enter data using the 'Edit Database Cell' box at the top right. Then click the mouse to move focus to a different cell in the data table. 

#### What did you see?
Everything you typed into the 'Edit Database Cell' box is lost without warning.

#### What did you expect to see?
A message telling me there was unsaved data and inviting me to click the Apply button. 

#### Comment
People use the 'Edit Database Cell' box when they have a lot of text to enter. So it's particularly annoying if it is all lost without warning. You may not even notice that the data has not been saved. 

#### What operating system are you using?
Windows: 7
#### What is your DB4S version?
3.12.99
#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
No.

- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?
Yes.

**Comment by justinclift** [comment]
Thanks, that's a good point. :smile:

Thinking about it more, it's kind of surprising we don't have a warning already. (!)

**Comment by mgrojo** [comment]
Yes, this omission was a bit embarrassing. But it's now solved and will be available in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds). Could you confirm that everything is working fine?

**Comment by tenbob** [comment]
Thanks for the very speedy response @mgrojo. I will test it tomorrow.

I just thought of a small enhancement that you might consider at the same time. Could the Edit Database Cell box display the name of the column somewhere? eg in the title. It's dificult to know what column you are editing if the column width in the grid is all squashed up. 

Don't worry if I am too late with this request.

**Comment by tenbob** [comment]
Hi @mgrojo. I tested the nightly Version 3.12.99 (Dec  8 2020). It is working as expected in most cases.  I get the pop up asking me to Apply or Discard. 

Unfortunately there are a few special cases where it is not working reliably. Below are two cases where I found it doesn't work. I haven't found any more so far. Start by entering data in the "Edit Database Cell" box. Then with unsaved data do one of the following.

(1) Change to a different tab, eg Database Structure instead of Browse Data. The pop up does not appear and data is lost.

(2) Click the filter row above the data grid and type one character. The pop up appears. Click Apply. The pop up appears again. Click Apply again. Apply is ignored and the data is not saved. Also the grid display gets slightly messed up.

Also I think it may be better if the default button is Apply rather than Discard. This seems the most likely choice after you have entered data. 

Thanks for your work on this.

**Comment by tenbob** [comment]
Hi @mgrojo. I had some more thoughts about this. There is no explicit way to cancel after you have started to enter data in the "Edit Database Cell" box. The box really needs to have its own two buttons - "Apply" and "Discard". At present cancelling is handled almost by accident when the user starts to do something different and then gets the popup warning. Adding a Discard button to the Edit Database Cell box would make the UI a lot easier to understand.

Also, as I mentioned above, it would be nice if the Edit Database Cell box showed the column name somewhere.

**Comment by mgrojo** [comment]
Hi @tenbob. I'm fixed the two remaining cases that you reported, plus some minor adjustments to improve feedback. I haven't added the "Discard" button, though. I'm hesitant to change this long tradition of the single "Apply" button. What others think about it?
