### ISSUE TITLE
Crash on Opening a database containing a large blob

### ISSUE THREAD

**Issue by celloman** [sqlitebrowser/sqlitebrowser#249]
sqlitebrowser consistently crashes upon opening a database with a large blob in it (close to 1GB blob, but not over due to the SQLite max size)... the database(s) work fine in the program that utilizes them, but the browser can't handle it. I get a visual c++ error stating that "This application has requested the Runtime to terminate it in an unusual way."
I have tried this on several databases with similarly sized data and have encountered the problem on each. If I create the same database layout with a smaller blob then it is loaded fine.

Running Windows 7 Professional SP1 64-bit
2.7GHz i7
12 GB ram

**Comment by schdub** [comment]
celloman, please provide your table schema to reproduce this issue.

**Comment by celloman** [comment]
It is very simple, just a TEXT column with the "filename" and a BLOB column containing the data. This is for an octree structure, one blob stores a tree's structure, and the other stores data accessed by the nodes.

**Comment by justinclift** [comment]
I kind of suspect it's because we're compiling using 32 bit on Windows (win32), and not 64 bit.

@schdub Would you happen to have any skill with Windows compilers?  eg Visual Studio or anything :smile:

**Comment by justinclift** [comment]
@celloman Would you be ok to try this again with our new release from a few hours ago?  We have a 64-bit windows version, which (in theory) should open larger database files now like yours.

**Comment by celloman** [comment]
I'll try it out, thanks!

**Comment by celloman** [comment]
Thanks, I am now able to open these databases without this crash... Though it is a bit sluggish on opening.

I'll go ahead and close this, as I feel the problem is adequately fixed. I don't know if anything can really be done about speed. This is dealing with large blobs after all =P

**Comment by justinclift** [comment]
Awesome!

@rp- Looks like it was the 32-vs-64 bit builds.  Thanks for working on that. :smile:
