### ISSUE TITLE
Allow selecting vfs and opening by URL

### ISSUE THREAD

**Issue by mwisnicki** [sqlitebrowser/sqlitebrowser#2493]
See topic

**Comment by chrisjlocke** [comment]
Care to give a bit more information?

**Comment by mwisnicki** [comment]
Sure, I'm assuming you know what VFS is. I wanted to test out in SQLiteBrowser some of the experimental VFS I'm working on and was unable to do so.

You can specify them on command line with `-vfs` parameter or via parameter to open: https://www.sqlite.org/c3ref/open.html
Sqlite also allows to open file or attach database by URI: https://sqlite.org/uri.html and passing ?vfs query parameter.


I was unable to find a way select VFS or open by url in the UI. Additionally it looks like ATTACH doesn't have URI support enabled.

**Comment by mwisnicki** [comment]
I just discovered I can make my VFS a default one through `sqlite3_vfs_register(..., 1)` so I have a workaround but it would still be nice to expose VFS selection and URI support in UI.

**Comment by mgrojo** [comment]
Please, could you give examples of what you are trying to achieve, so we can get an idea of the usefulness and general interest of the feature?.

**Comment by MKleusberg** [comment]
@mwisnicki Can you check if specifying a ```?vfs=...``` parameter when attaching a database works in tomorrow's nightly build? In theory it should be enabled now but it might depend on the platform. This would be a first step towards exposing the VFS feature of SQLite.

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@mwisnicki - Feel free to comment back if needed.
