### ISSUE TITLE
Issue with importing csv file when the table has a foreign key

### ISSUE THREAD

**Issue by jimbasquiat** [sqlitebrowser/sqlitebrowser#2494]
I am trying to import data (with the import from csv) in an existing table that has a foreign key, but i receive an error message :
![image](https://user-images.githubusercontent.com/19773990/100528985-98231680-31da-11eb-935b-5d27928535e1.png)

Here the code that creates the table:

```
CREATE TABLE `titles` (
  `titleID` INTEGER PRIMARY KEY,
  `symbolID` TEXT,
  `keywordsID` INTEGER,
  `date` TEXT,
  `title` TEXt,
  `url` TEXT,
  `source` TEXT,
  `rank` INTEGER,
  `relevant` INTEGER DEFAULT 0,
  `topicID` TEXT DEFAULT na,
  CONSTRAINT fk_symbolID
    FOREIGN KEY (symbolID)
    REFERENCES symbols(symbolID)
  CONSTRAINT fk_topicID
    FOREIGN KEY (topicID)
    REFERENCES topic(topicID)
  CONSTRAINT fk_keywordsID
    FOREIGN KEY (keywordsID)
    REFERENCES keywords(keywordsID)
);
```

The referenced column correctly has the value in the other table:

![image](https://user-images.githubusercontent.com/19773990/100528901-b8060a80-31d9-11eb-8e67-45ca47ab0869.png)

I think the issue is that when i try to import, the `topic` table is called `main.topic`... But I am not sure.

Anyone has idea how to solve this ?

**Comment by chrisjlocke** [comment]
Its 'topic**s**' in your screenshot....
