### ISSUE TITLE
Display formatting of the numeric X-Axis Plot

### ISSUE THREAD

**Issue by regisphilbin** [sqlitebrowser/sqlitebrowser#2498]
Is there an easy way to change how a numeric field is displayed on the  plots axis?  

I have a field with a SN# (numeric) i'd like to plot in its entirety without being truncated as an exponential Number.
the format is eight digits long (ie. 2047000) but when graphed on the Plot X-Axis,  it shows up as "2.047*10^7" .
![plot](https://user-images.githubusercontent.com/75390715/100922410-b1ee8300-3492-11eb-96db-739a8cc9a5f5.JPG)

**Comment by mgrojo** [comment]
I've implemented an option for setting the fixed format for the axes but the graph does not remove in that case the trailing zeros, so I had to set the precision to 0. The option can be selected using the contextual menu (right mouse button) of the plot. Could you confirm it works well for you in [tomorrow's nightly](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)?

**Comment by regisphilbin** [comment]
Thank you.  I will try it out and report back in this thread....

**Comment by regisphilbin** [comment]
I've had a chance to use it and wanted to first say thanks for the quick response.  

A couple of notes...

1)  it seems as there is no way to decouple the "fixed format" for each axis individually.  It is for the entire plot.  Is it possible to decouple the X, Y1 and Y2 axes to have the option to set this option independently?

2)  When our dataset spans ranges that aren't numerically consecutive,   we get huge gaps as shown below.  Is there any way to eliminate any unnecessary SN's that rren't being used?  for example  we have ranges of SN# 20470001 through 20470038,  but then would also like to look at data in the range of 20490001 through 20490008 on the same plot.  see example of results below.



![image](https://user-images.githubusercontent.com/75390715/102938675-9d822280-4461-11eb-877d-38258ff76a3d.png)

**Comment by chrisjlocke** [comment]
> When our dataset spans ranges that aren't numerically consecutive, we get huge gaps as shown below.

Isn't that how a graph works?  Do you want the X-axis to just show explicit values? Each X value would have to be labelled, otherwise you wouldn't know what the value would be - it could be anything (rather than extrapolating the value from neighbouring values).

**Comment by mgrojo** [comment]
I've made an adjustment, so in the fix format mode, big numbers (center greater than 999 and number of values greater than 10) get no decimal digits and smaller numbers get two digits.

Ideally, all the axis and graphics configuration (line type, point shape) should be individually selectable, but I don't have currently the motivation to make such a big and complex change.
