### ISSUE TITLE
Difficult to select multiple columns in data grid

### ISSUE THREAD

**Issue by tenbob** [sqlitebrowser/sqlitebrowser#2499]
I want to select multiple columns in the data grid so I can resize or hide them. I found this very tricky, as none of the obvious methods seemed to work. After a lot of experimentation I found a couple of ways to do it, but they are certainly not intuitive. 

It would be good if this could be improved. However, it may be a feature of Qt that is not fixable. In which case these notes may help other people trying to do the same thing.

#### Drag across the column headings
This looks like it is going to work. As you drag the columns are highlighted. But when you let go the highlight disappears. Moreover, there are some other odd effects. The highlight doesn't start at the column you expect, but at some other column that has been selected previously. And when you release the mouse you get an unwanted sorting of the column it is on.

#### Double click the column heading
Double clicking selects the column. But also performs an unwanted sort at the same time. To extend the selection to more columns, hold down Shift and double click another column heading. This will extend the selection as required, but will also do an unwanted sort on that column. 

#### Use the context menu to select the columns
With the cursor on the column heading, right-click to get a context menu. This has an item "Select column". This does what it says and selects the column (without also sorting it). Hold down Shift and do the same on another column heading to extend the selection.

#### Use the magic shortcut Ctrl+Space
This turns out to be the best way to do it, but is hard to discover. Select any block of cells in the data grid that spans the columns you want to select. Then just hit Ctrl+Space and the selection is changed to a selection of whole columns. 

#### What operating system are you using?
Windows 7 Pro

#### What is your DB4S version?
3.12.99

**Comment by chrisjlocke** [comment]
If you're just viewing the data, you can use SQL to select specific columns and order by specific columns.  Not great, and goes against the GUI aspect, but at least that's another workaround.

**Comment by tenbob** [comment]
Thanks @chrisjlocke. I definitely need to edit the data, so SQL won't work for me. I thought of setting up different views, but I couldn't get it to work with editing. I think it requires a lot of SQL code to allow you to edit every column in the table.

**Comment by chrisjlocke** [comment]
> I think it requires a lot of SQL code to allow you to edit every column in the table.

You need a unique ID for each table and a trigger, so depends on how many tables you have - you have to replicate this for every table, which can be a pain.
However, if you just reduce the width of the columns (not just hide them) you can save this 'layout' as a project file for the database, so technically, you only need to do it once.  It can be a pain to then unhide the columns, but depends on how frequently you have to do it.

**Comment by mgrojo** [comment]
This can be considered the continuation of #1717. For that, I added the menu entry and the shortcut, because I couldn't make the selection through some kind of mouse gesture to work better. But of course, it would be nice to have better ways.

By the way, you can contribute the "Things that work" to the Wiki page [Browse Data](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Browse-Data), if you like.

**Comment by tenbob** [comment]
Thanks to @mgrojo for your previous work on this. Maybe it is now as good as it can be.

I would like to discuss with @chrisjlocke about how to make editable views. But here is not the correct place. I have a a simple table with a unique index and no foreign keys. There isn't much detail in the [Wiki ](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views) page under "Editing Data In A View". Is there a tutorial available?

**Comment by chrisjlocke** [comment]
See this issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/141

This is where the initial concept was discussed, and I blundered along, couldn't get it working, and was told, 'duuur - haven't you created any triggers?' which I didn't even know was required.  Thought this was added to the wiki, but we can create a 'tutorial' to go through.  I'll have a tinker today.

**Comment by tenbob** [comment]
Hi @chrisjlocke.  I have read the [Wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views) about editing data in a view. Also the [SQLite documentation](https://sqlite.org/lang_createtrigger.html). It seems just too complicated to be practical. I want the ability to edit any column in a view. 

It looks like you need to write a separate `INSTEAD OF` trigger for every column in the database. They all take the form 
~~~
INSTEAD OF UPDATE OF <the column in the view>
BEGIN <SQL to update the associated column of the original table>; END;
~~~
Each trigger needs to be carefully coded and tested. Any small slip will screw up the data, probably without your knowledge. In a view with 20 columns you need to write 20 of these triggers. Then you probably need to do it all over again for INSERT and DELETE. If you ever modify the columns in the view you need to make exactly corresponding changes to the triggers or, again, you will screw up the data. 

So editing in the table rather than the view seems the only sensible way to proceed.

**Comment by chrisjlocke** [comment]
Urgh - that's crap.  @mgrojo - can you just confirm this is the only way - triggers for each column on update, insert and delete?

**Comment by mgrojo** [comment]
No, you only need to code a trigger per each table and operation. Example for `UPDATE`:

```sql
CREATE TABLE Foo (a, b, c);

CREATE VIEW Bar AS SELECT a, b, c FROM Foo ORDER BY b;

CREATE TRIGGER UpdateBar
INSTEAD OF UPDATE ON Bar
BEGIN
  UPDATE Foo SET a = NEW.a, c = NEW.c
  WHERE b=NEW.b;
END
```

**Comment by tenbob** [comment]
Thanks for your help @mgrojo. I have now got this working and it was easier than I expected. I was misled by the example in Section 4 of the the [SQLite documentation](https://sqlite.org/lang_createtrigger.html) which only deals with the update of a single column. 

This information should go in the [Wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views). I will try to add it unless someone else does it first.

Next I will attempt something similar with related tables !

**Comment by chrisjlocke** [comment]
I'll close this as it's not going to get better any time soon, and there are suitable workarounds.
