### ISSUE TITLE
I would love to see a dark mode option for sqlitebrowser. The blazing white background plays havoc with my cataracts.

### ISSUE THREAD

**Issue by jerocis** [sqlitebrowser/sqlitebrowser#2500]
Describe the new feature
--------------------------
A change to the appearance of sqlitebrowser to allow for the optional use of a dark mode as an alternative to the blazing white background that is very difficult to look at for more than a moment or two.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
no

#### Does this feature exist in another product or project? Please provide a link.
everywhere
![VS Dark Mode](https://user-images.githubusercontent.com/7890613/101081111-3dd5dd00-356f-11eb-9f35-842e06d97840.png)

**Comment by drescherjm** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/issues/2261#issuecomment-634934930

**Comment by chrisjlocke** [comment]
What version of DB4S are you using - there is a dark mode already.

**Comment by JoshLambda** [comment]
Dark mode can now be set with: `Edit -> Preferences -> General -> Application style -> Dark style`
