### ISSUE TITLE
Is there a way to use the filters to exclude certain terms ?

### ISSUE THREAD

**Issue by jimbasquiat** [sqlitebrowser/sqlitebrowser#2501]
I would like to be able to use the filter (of the browse data table view) in order to exclude certain terms.

Right now for instance if I type "vincent" in the filter of column1, the table will only show rows where column1 contains "vincent".

I would like to be able to find a way for the browser to return all rows except those where "vincent" is present in the column.

By browsing the doc, it says that the filter is done usign the `LIKE` operator, so as a request it is actually possible to use `NOT LIKE` to get the intended result (by using the execute sql tab for instance).

However it would be much more convenient to have the same behavior available in the browse data tab. I looked into doing it [with regex](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters) as well but to available.

Any help appreciated!

**Comment by chrisjlocke** [comment]
You can use `<>` to mean 'anything less than or anything greater than' which normally means 'anything other than'.
So typing `vincent` would bring up matches of `vincent` but if you typed `<>vincent` then that would bring up everything other than vincent.

Original data:
![image](https://user-images.githubusercontent.com/7872218/101094890-0722b580-35b5-11eb-8c8c-339a55bb8637.png)

Just vincent:
![image](https://user-images.githubusercontent.com/7872218/101094931-1275e100-35b5-11eb-977c-82c574c28887.png)

Everything other than vincent:
![image](https://user-images.githubusercontent.com/7872218/101094977-24f01a80-35b5-11eb-96f4-784256dedead.png)

Note that using `<>` no longer uses the `like` operator, so text is now case sensitive.
![image](https://user-images.githubusercontent.com/7872218/101095070-44874300-35b5-11eb-8469-a226fb36d38c.png)

If you just use `vincent` then that doesn't match `Vincent`.
![image](https://user-images.githubusercontent.com/7872218/101095245-9203b000-35b5-11eb-8e63-6b1dba6c4018.png)

Note also DB4S sometimes gets confused and doesn't display the header row.  Shhh.  You didn't spot that.

**Comment by mgrojo** [comment]
Additionally, if the "<>" is not what you need, there is a "Not containing" filter using regexp expressions. It's complex, but don't worry because there is a helper menu entry which allows to enter it easily. Press the right mouse button over the filter box and select  "Set expression filter > Not containing". It fills the regexp expression for you and you only have to fill the patter (which is a selected `?`, so you only have to type your pattern).

**Comment by jimbasquiat** [comment]
Great! thx a lot

**Comment by MKleusberg** [comment]
Awesome :smile: I'm closing this issue then as we're a bit flooded with open issues and this seems to be solved. If there's anything else we can do, feel free to reopen this issue any time though, @jimbasquiat!

**Comment by chrisjlocke** [comment]
> Additionally, if the `<>` filter is not what you need, there is a "Not containing" filter using regexp expressions. 

Thanks @mgrojo - I wasn't aware of that, so will add a tutorial thingy to the Wiki. :)
