### ISSUE TITLE
Control + Enter/return near numpad not working in 'Execute SQL' editor

### ISSUE THREAD

**Issue by MuhammedZakir** [sqlitebrowser/sqlitebrowser#2502]
Details for the issue
--------------------

#### What did you do?

In 'Execute SQL' editor, press `Ctrl + Enter` (numpad `enter/return` key).

#### What did you expect to see?

Execute SQL query.

#### What did you see instead?

Nothing happens.

Useful extra information
-------------------------

Other `enter` key works.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Manjaro)
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Technically, the key is [Ctrl] + [Return].

![image](https://user-images.githubusercontent.com/7872218/101283174-c1dacf80-37d0-11eb-9896-50b4714166bd.png)

Normally, the main [Return] key on a keyboard is [Return], while the key on the numeric keypad is [Enter].  This varies greatly with region and keyboard, but the general consensus is this.
Each key has its own keycode, so [Return] isn't the same as [Enter], and so [Ctrl] + [Enter] won't behave like [Ctrl] + [Return].
It's hoped at some point in the future that these shortcuts can be remapped by the user, but due to limitations in Qt (the development framework we use) and in programming time, this hasn't been implimented.

**Comment by chrisjlocke** [comment]
Closing this as this isn't an issue that we can resolve ... technically we could add [Ctrl] + [Enter] as a shortcut, but as we've also got [Ctrl] + [R] and [F5], I think we're pretty well covered ... but feel free to comment further if you need to.

**Comment by MuhammedZakir** [comment]
> Technically, the key is [Ctrl] + [Return].
> 
> ![image](https:// user-images.githubusercontent.com/7872218/101283174-c1dacf80-37d0-11eb-9896-50b4714166bd.png)
> 
> Normally, the main [Return] key on a keyboard is [Return], while the key on the numeric keypad is [Enter]. This varies greatly with region and keyboard, but the general consensus is this.

Thanks for the info! 

> Each key has its own keycode, so [Return] isn't the same as [Enter], and so [Ctrl] + [Enter] won't behave like [Ctrl] + [Return].
> It's hoped at some point in the future that these shortcuts can be remapped by the user, but due to limitations in Qt (the development framework we use) and in programming time, this hasn't been implimented.
> As a workaround, pressing [Ctrl] + [R] or simply [F5] will work.

I see!

> Closing this as this isn't an issue that we can resolve ... technically we could add [Ctrl] + [Enter] as a shortcut, but as we've also got [Ctrl] + [R] and [F5], I think we're pretty well covered ... but feel free to comment further if you need to.

Personally, I hope you can add `Ctrl + enter`. Generally, when you see some shortcuts with `enter/return`, I expect it to work with `return/enter` too. I think others also expect the same.  Also, if it's added, there isn't any need to add this to hover text because of the same reason.

Why I want this: I use numpad when working with number-heavy data. This is not important, as I could just move my hand. But it's annoying and cumbersome. If possible, please do add it. :-)

**Comment by chrisjlocke** [comment]
What are you entering that requires you to press [Ctrl] + [Return] so much?
Are you entering values via SQL, amending them then pressing [Ctrl] + [return] again?  Just trying to understand what you're doing so I can see if there is a workaround.  I usually find [F5] easier to press.

**Comment by MuhammedZakir** [comment]
> Are you entering values via SQL, amending them then pressing [Ctrl] + [return] again?

Yes, happens when amending.

> I usually find [F5] easier to press.

On my keyboard, there is an empty row between numbers and function keys. So I have to move my hands quit a bit to reach `F5` and so, `Ctrl + enter` is easier for me.

> > Also, if it's added, there isn't any need to add this to hover text because of the same reason.
> 
> Not sure I follow this - you'd still need the tooltip regardless of whether [Ctrl]+[Enter] was added.

What I meant was, you won't need to add `Ctrl + enter` to tooltip. `Ctrl + return` is sufficient.

**Comment by mgrojo** [comment]
Ok, since a lot of people don't know this difference and it makes sense to perform the same action for both, we can add Ctrl+Enter too, although the tooltip will be left untouched so it is not cluttered.
