### ISSUE TITLE
improve Arabic language

### ISSUE THREAD

**Issue by WassemSy** [sqlitebrowser/sqlitebrowser#2505]
#### Text me whatsapp 00963943396901

**Comment by justinclift** [comment]
Thanks, but we're probably not going to use Whatsapp for this.  We do all of our development here on GitHub. :wink:

You're definitely welcome to help us improve the Arabic language, here on GitHub though. :smile:

**Comment by WassemSy** [comment]
Ok, not problem
How I can help you ?! الثلاثاء, ٠٨ كانون الأول ٢٠٢٠, ٠٢:٠٣ص +02:00 from Justin Clift  notifications@github.com :

**Comment by justinclift** [comment]
@karim You're our resident Arabic expert, any ideas? :smile:

**Comment by WassemSy** [comment]
You can send strings file to me & I will translate the file between 24-48 hours.
Just send 10$ to this email via PayPal & I will give you a perfect translate 珞 الثلاثاء, ٠٨ كانون الأول ٢٠٢٠, ٠٤:٠٧ص +02:00 from Justin Clift  notifications@github.com :

**Comment by lucydodo** [comment]
Well, I think the open source culture is worth more than $10.

**Comment by WassemSy** [comment]
Look .. I'm support the open source culture, in fact .. I'm Arabian Developer from Syria.
But This money it's not for me .. I will paid this money for internet service & electricity .. 10 years of war if you know what I mean 
الثلاثاء, ٠٨ كانون الأول ٢٠٢٠, ٠٦:١٥ص +02:00 from SeongTae Jeong  notifications@github.com :

**Comment by justinclift** [comment]
@WassemSy Thanks, but no.  We're all volunteers here, doing this stuff without cost. :smile:

**Comment by WassemSy** [comment]
As you like my bro, let me know if you want any help in future 
Thank you for your time ❤ الثلاثاء, ٠٨ كانون الأول ٢٠٢٠, ٠٨:١٣ص +02:00 from Justin Clift  notifications@github.com :

**Comment by lucydodo** [comment]
Thank you for your interest in our project. I close this issue for now.
