### ISSUE TITLE
Numbers not displaying properly in SQL results section

### ISSUE THREAD

**Issue by zakhikhan** [sqlitebrowser/sqlitebrowser#2511]
Details for the iss
<img width="541" alt="Screen Shot 2020-12-16 at 3 57 15 PM" src="https://user-images.githubusercontent.com/76130723/102405585-64583700-3fb7-11eb-94dc-3fde2fa0ce71.png">
ue
--------------------

#### What did you do?

The SQL output section under "Execute SQL" displays numbers as being cut off, not showing the full number. I am running the program on MacOS 11.1 on an M1 MacBook Pro.

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.2.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.15.1

**Comment by mgrojo** [comment]
What happens if you select a different font under `Preferences > Data Browser`?

**Comment by zackdareshori** [comment]
> What happens if you select a different font under `Preferences > Data Browser`?

I selected Arial and it displays properly. Thanks for the suggestion--I didn't think to try that.

**Comment by mgrojo** [comment]
I suppose that the original font has some too new or too old feature and is not well-supported by Qt. At least, there is a workaround.
