### ISSUE TITLE
Add row count to Table dropdown

### ISSUE THREAD

**Issue by stark4n6** [sqlitebrowser/sqlitebrowser#2512]
Describe the new feature
--------------------------
Add row count next to the Table of choice from the dropdown when you "Browse Data". It would help with identifying from a GUI perspective what tables have data and what don't easily.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Magnet AXIOM does this:
![image](https://user-images.githubusercontent.com/48143894/102499993-d5e0c580-4049-11eb-88f6-e1eaa7765ada.png)

Would be great to add alongside:
![image](https://user-images.githubusercontent.com/48143894/102500121-f577ee00-4049-11eb-9a32-b64d36015c07.png)

**Comment by mgrojo** [comment]
Thanks for the suggestion. This is not easy to do well, because we don't want to penalize performance with big databases.

In the nightly build though, you have a tool which can help you to discover that, although not in such integrated way, but with a query: Tools > Show Row Counts

**Comment by stark4n6** [comment]
Ok great, will check it out!
