### ISSUE TITLE
Main window cannot be as small (in height) as expected

### ISSUE THREAD

**Issue by cpina** [sqlitebrowser/sqlitebrowser#2513]
Describe the new feature
--------------------------
I'm an occasional long term sqlitebrowser user (since 2009). The minimum height that I can resize the main window is too big. I would like it to be possible to resize it smaller.

I think that the current size might cause problems in small resolutions (as it wouldn't fit all in one screen).

Additional info
---------------

#### Does this feature exist in another product or project? Please provide a link.

In older versions of sqlitebrowser (e.g. the packaged in Debian Buster: 3.10.1.). I remember that years ago it was possible as well.

**Comment by cpina** [comment]
PR: https://github.com/sqlitebrowser/sqlitebrowser/pull/2514

**Comment by cpina** [comment]
Besides PR #2514: the Main Window cannot be resized as small as I wanted.

I've seen a ticket with Main Window UI bigger changes. I might have a look if I can make widgets resizeable in height smaller unless this is already in your pipeline or bigger changes might happen in this area.

**Comment by cpina** [comment]
One more thing: using View -> Window Layout -> Simplify Window Layout makes it possible to resize as much as I want. I can't see how to make sqlitebrowser start with the simplified window layout: this would work well enough for me as well.

Is there any way to change the default window layout?

Thank you very much - and I forgot to say earlier thanks for this fantastic software!

**Comment by chrisjlocke** [comment]
No, it would appear the window layout isn't saved in the project file either.  I thought DB4S remembered the window layout, but upon setting it and starting another copy, it doesn't appear to.  😖😕

**Comment by mgrojo** [comment]
We looked at this issue in a previous version in #1684, but it seems that the latest changes to the Remote dock have increased again the minimum size. I haven't tested the PR #2514, but if the scrollbar is added to a group of widgets instead of to a table list or similar, I think  there should be a better solution in those terms (#1684) than adding a scrollbar. Note also that the layout can be adjusted in many ways, and it should be saved, like removing the Remote tab or rearranging it to overlap the other docked tabs. In that case the minimal height of both docks (top and bottom) do not add up:

![image](https://user-images.githubusercontent.com/13812910/102778495-f767e700-4392-11eb-9627-564280f98da4.png)

**Comment by cpina** [comment]
> We looked at this issue in a previous version in #1684, but it seems that the latest changes to the Remote dock have increased again the minimum size. I haven't tested the PR #2514, but if the scrollbar is added to a group of widgets instead of to a table list or similar, I think there should be a better solution in those terms (#1684) than adding a scrollbar. Note also that the layout can be adjusted in many ways, and it should be saved, like removing the Remote tab or rearranging it to overlap the other docked tabs. In that case the minimal height of both docks (top and bottom) do not add up:

I've added two screenshots:

![sqlitebrowser-01](https://user-images.githubusercontent.com/489071/102802585-c85f6e80-43ae-11eb-9f43-afcbeefdebeb.png)
![sqlitebrowser-02](https://user-images.githubusercontent.com/489071/102802589-c8f80500-43ae-11eb-9604-5b018bc7eb2e.png)

The Current Database has many widgets that are not resizeable (and I don't think that they should) smaller than this (QToolBar, QTextEdit, etc.):

![sqlitebrowser-03](https://user-images.githubusercontent.com/489071/102802753-0a88b000-43af-11eb-8309-e1e26a2f44fe.png)

So the QScrollArea seems an "easy" solution. Another one would be maybe to have User, Database and Branch all in one line? but I didn't want to change the layout that much.

**Comment by cpina** [comment]
BTW, if the Simplified Layout would be saved I wouldn't (personally) worry too much about the minimum size of the "Current Database". I would have it almost all the time in Simplified Layout for the operations that I do. Thanks!

**Comment by chrisjlocke** [comment]
> Which version are you using? I can try a quick "git bisect" if the saving layout used to work at some point.

One of the nightlies from 9 Nov.

**Comment by cpina** [comment]
> > Which version are you using? I can try a quick "git bisect" if the saving layout used to work at some point.
> 
> One of the nightlies from 9 Nov.

And one more question: which operating system? (I'm testing it on Linux)

**Comment by chrisjlocke** [comment]
Windows.

**Comment by cpina** [comment]
The main window size is smaller (PR #2514)

I'll make another now another PR to solve the problem that the "Simplify Window Layout" was not saved: after this I think that people who prefer a simplified window layout with a smaller application height can do it and leave it. I'll close this issue.

Thanks for all the information here.
