### ISSUE TITLE
DB4S Doesn't support Window functions

### ISSUE THREAD

**Issue by AlwaysBeCalm** [sqlitebrowser/sqlitebrowser#2516]
Details for the issue
--------------------

#### What did you do?
written a query that has an over clause

#### What did you expect to see?
the result set as queried 

#### What did you see instead?
Execution finished with errors.
Result: near "(": syntax error
At line 1:
select sum(salary) OVER(

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ _Mint 20.04_ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
SQLite is 'baked in' to DB4S, so it can't be upgraded without recompiling DB4S.
If you click 'help' and 'about', what version of SQLite is 3.12.0 using?  Does that version support Window functions?
The latest version of DB4S is 3.12.1, and that will use a newer version of SQLite.

**Comment by chrisjlocke** [comment]
Closing this as this is primarily due to the version of SQLite in the older version of DB4S.
