### ISSUE TITLE
It imports an empty database while trying to import a sql file

### ISSUE THREAD

**Issue by extremesecurity** [sqlitebrowser/sqlitebrowser#2519]
Details for the issue
--------------------

#### What did you do?
Opened up sqlite browser and tried to import a postgresql dump (.sql file)

#### What did you expect to see?
The database was supposed to be on there

#### What did you see instead?
It said "import completed" but the database hadn't been imported

Useful extra information
-------------------------
The .sql file uses copy command instead of insert command

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
A postgresql dump (.sql file) isn't 100% sqlite compatible.
If you want to email me the .SQL file (zip it first?) to db4s [at] chrisjlocke [dot] co [dot] uk I can walk you through making it DB4S happy. 👍

**Comment by extremesecurity** [comment]
> 
> 
> A postgresql dump (.sql file) isn't 100% sqlite compatible.
> If you want to email me the .SQL file (zip it first?) to db4s [at] chrisjlocke [dot] co [dot] uk I can walk you through making it DB4S happy. 👍

i can't since it's a big file (3 gb) but you can help me with walking me through by telling me the process

**Comment by chrisjlocke** [comment]
OK.  Use Notepad++ or some other editor to open that text file.  It's just plain text.  A .SQL file is just a bunch of instructions.
The first bunch of statements (usually) is to drop a table or 'if not exist' statements.  SQLite doesn't support 'if not exists'.  However, that's OK, because if the table exists the statement isn't going to run anyway, so its a bit superfluous.

How much about SQL do you know?  The 'create' statement for tables is pretty easy.
However, there is a difference between Postgres and SQLite - mainly in that SQLite supports a narrow set of data types - a column can either be text, numeric (integer), real (decimals) or binary.  That's pretty much it.  Having said that, technically, that's all you need.  Dates will be the biggest bitch, depending on how they're stored in Postgres - you can either store the seconds from 1970, textual as 'yyyy-MM-dd', etc.  SQLite prefers the latter, but does support numbers, but has no dedicated 'date' column type.  So depending on how the table is built, you have to squidge the columns into the right data types.
Paste your 'create table' statement here and I can advise.

Finally, how complex is this schema?  Will it have constraints, foreign keys and all that jazz?  Is this a requirement?  If you're just throwing a copy of a database into SQLite to have a nose or amend, then you may not need all the constraints.

This did come up a while ago, and someone linked to an online conversion tool, so there is also that, but I think it's good to learn what you're doing.  Depends on how much time you have and if you want to learn anything new.

Finally (another finally...) there is a minor 'bug' if you do have any constraints or foreign keys.  What tends to happen is that you have table A and table B.  You set up that table B links to table A, and a constraint that 'if a user enters a record into table B, there must be a corresponding record in table A' - very common with order databases - you can't have an order for customer 123 if that customer doesn't exist, or for item 123 if that item doesn't exist.  However, when importing, the SQL is usually in the wrong order - you may be inserting records in the orders table before the SQL for creating/inserting the customer table has occurred - so everything fails.
I say 'bug', but its more of a design thing with exporting and importing data - it can be difficult to know easily what table links to what then that table links to that and then that, etc, when its easier to just dump it.  There are commands to ignore constraints, etc, when importing.

**Comment by extremesecurity** [comment]
firstly, i haven't done anything about sql before and as i got to know from your latest message i tried to make my sql file's code as minimal as possible. i have deleted everything insted of create table and copy statement but that hadn't done the trick. the problem is as i think the copy statement and i don't know how to convert that to an insert statement quickly.

**Comment by chrisjlocke** [comment]
OK, if you zip up the file, you can use www.wetransfer.com to transfer the file. 
Its usually the 'create table' part that fails - the rest should be 'insert' commands which is importing the actual data.

> as i think the copy statement and i don't know how to convert that to an insert statement quickly.

I don't quite follow this fully, but if I saw the .SQL file, I might - can you paste a screenshot here?  If you press [Print Scrn] on your keyboard, you can press [Ctrl] + [V] to paste the image in here.

**Comment by justinclift** [comment]
To keep things simple, maybe @extremesecurity could just copy the `CREATE TABLE` statements from the start of the file to here?

They're generally within the first few lines of PostgreSQL SQL dumps, and that's probably pretty much all that needs changing.  Hopefully. :smile:

**Comment by extremesecurity** [comment]
> 
> 
> OK, if you zip up the file, you can use [www.wetransfer.com](http://www.wetransfer.com) to transfer the file.
> Its usually the 'create table' part that fails - the rest should be 'insert' commands which is importing the actual data.
> 
> > as i think the copy statement and i don't know how to convert that to an insert statement quickly.
> 
> I don't quite follow this fully, but if I saw the .SQL file, I might - can you paste a screenshot here? If you press [Print Scrn] on your keyboard, you can press [Ctrl] + [V] to paste the image in here.

Sorry, i can't since it's a private database



> 
> 
> To keep things simple, maybe @extremesecurity could just copy the `CREATE TABLE` statements from the start of the file to here?
> 
> They're generally within the first few lines of PostgreSQL SQL dumps, and that's probably pretty much all that needs changing. Hopefully. 😄

```CREATE TABLE table1 (
    a bigint NOT NULL,
    b text NOT NULL,
    c text NOT NULL,
    d text NOT NULL,
    e text NOT NULL,
    f text NOT NULL,
    g character varying(1) NOT NULL,
    h text NOT NULL,
    i text NOT NULL,
    j text NOT NULL,
    k text NOT NULL,
    l text NOT NULL,
    m text NOT NULL,
    n text NOT NULL,
    o text NOT NULL,
    p text NOT NULL,
    q text NOT NULL
);

COPY table1 (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) FROM stdin;
//data
//data2
//data3```

**Comment by chrisjlocke** [comment]
OK, bigint is just 'integer' and 'character' is just text.  

    create table table1 (
    a integer not null,
    b text not null,
    ...
    g text not null,
    ...
    q text not null
    );

As for the 'copy', that might take more work.
Not seen that before, but I've not used postgres before.

To insert data into sqlite, you use `insert into table (columns) values (data)`
So `insert into table1 (a,b,c,d,e,f) values ('abc','abc','abc','abc','abc','abc')`
You can do multiple inserts too:
`insert into table1 (a,b,c,d,e,f) values ('abc','abc','abc','abc','abc','abc'), ('abc','abc','abc','abc','abc','abc'), ('abc','abc','abc','abc','abc','abc')`

If you're inputting numbers, then you don't need to enclose in single quotes.
If you're inputting text, then enclose in single quotes.
Don't use double quotes. So don't do this:
`insert into table1 (a,b,c,d,e,f) values ("abc","abc","abc","abc","abc","abc")`
If you're inputting dates, then yyyy-MM-dd HH:mm:ss format is recommended.  Slap it in a 'text' field, and enclose in single quotes.

I write VB applications, so theoretically, it might be do-able to create an importer, but as above, there are online tools, but 3 GB is a huuuuuuge file.
I don't know how the //data //data2 is laid out, but might be easy to convert to an INSERT easily enough.

Yell back if I can help in any way - happy to assist where I can. 😁

**Comment by extremesecurity** [comment]
> 
> 
> OK, bigint is just 'integer' and 'character' is just text.
> 
> ```
> create table table1 (
> a integer not null,
> b text not null,
> ...
> g text not null,
> ...
> q text not null
> );
> ```
> 
> As for the 'copy', that might take more work.
> Not seen that before, but I've not used postgres before.
> 
> To insert data into sqlite, you use `insert into table (columns) values (data)`
> So `insert into table1 (a,b,c,d,e,f) values ('abc','abc','abc','abc','abc','abc')`
> You can do multiple inserts too:
> `insert into table1 (a,b,c,d,e,f) values ('abc','abc','abc','abc','abc','abc'), ('abc','abc','abc','abc','abc','abc'), ('abc','abc','abc','abc','abc','abc')`
> 
> If you're inputting numbers, then you don't need to enclose in single quotes.
> If you're inputting text, then enclose in single quotes.
> Don't use double quotes. So don't do this:
> `insert into table1 (a,b,c,d,e,f) values ("abc","abc","abc","abc","abc","abc")`
> If you're inputting dates, then yyyy-MM-dd HH:mm:ss format is recommended. Slap it in a 'text' field, and enclose in single quotes.
> 
> I write VB applications, so theoretically, it might be do-able to create an importer, but as above, there are online tools, but 3 GB is a huuuuuuge file.
> I don't know how the //data //data2 is laid out, but might be easy to convert to an INSERT easily enough.
> 
> Yell back if I can help in any way - happy to assist where I can. 😁

well, i changed the create part as you've said but it seems i have to convert copy part either. the problem is i don't want to change copy to insert on every line of a 3 gb file so isn't there an automated way to do it (non-web application ofc)? i have been searching the internet for a day or so but i couldn't find anyting. and for example the copy statement looks like
```
COPY table1 (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) FROM stdin;
111111	111111	AAA	BBB	CCC	DDD	E	FFF	12/12/1999	GGG	HHH	III	JJJ	KKK	LLL	11	<NULL>
222222	222222	AAA	BBB	CCC	DDD	E	FFF	12/12/1999	GGG	HHH	III	JJJ	KKK	LLL	11	<NULL>
\.

**Comment by chrisjlocke** [comment]
Is there a table with non-sensitive data you could email over?  Are the values tab-separated?  
Shouldn't be too hard to create a quick converter... theoretically.

**Comment by chrisjlocke** [comment]
I've not used it, but others have recommended this tool.
http://opendbcopy.sourceforge.net/

This can read in database A (.sql file) and export to database B.

**Comment by extremesecurity** [comment]
> 
> 
> I've not used it, but others have recommended this tool.
> http://opendbcopy.sourceforge.net/
> 
> This can read in database A (.sql file) and export to database B.

i have installed this software and the thing i understand from it's plugins is it doesn't take a sql file (a database dump), instead it takes the database as input. 


> 
> 
> Is there a table with non-sensitive data you could email over? Are the values tab-separated?
> Shouldn't be too hard to create a quick converter... theoretically.

table looks like

> ```
> COPY table1 (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) FROM stdin;
> 111111	111111	AAA	BBB	CCC	DDD	E	FFF	12/12/1999	GGG	HHH	III	JJJ	KKK	LLL	11	<NULL>
> 222222	222222	AAA	BBB	CCC	DDD	E	FFF	12/12/1999	GGG	HHH	III	JJJ	KKK	LLL	11	<NULL>
> \.
> ```

as i've said before with more data of course

**Comment by extremesecurity** [comment]
right now i am taking a look at what character they are seperated with

**Comment by justinclift** [comment]
For the copy, that's just the default output format that PostgreSQL's dump command (`pg_dump`) uses.  Importing (back into PostgreSQL) using that is faster than insert statements.

That being said, `pg_dump` can output `INSERT` statements too.  It just needs to be passed the `--inserts` option on the command line. :smile:

**Comment by justinclift** [comment]
@extremesecurity Naturally, that'll only be useful if you're able to run the `pg_dump` command again to recreate the .sql file.  Not so useful if you don't still have access to the database it came from. :innocent:

**Comment by chrisjlocke** [comment]
> ```
> CREATE TABLE table1 (
>     a bigint NOT NULL,
>     b text NOT NULL,
>     c text NOT NULL,
>     d text NOT NULL,
>     e text NOT NULL,
>     f text NOT NULL,
>     g character varying(1) NOT NULL,
>     h text NOT NULL,
>     i text NOT NULL,
>     j text NOT NULL,
>     k text NOT NULL,
>     l text NOT NULL,
>     m text NOT NULL,
>     n text NOT NULL,
>     o text NOT NULL,
>     p text NOT NULL,
>     q text NOT NULL
> );
> 
> COPY table1 (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) FROM stdin;
> //data
> //data2
> //data3```
> ```

So the 'create table' is on multiple lines, as you've put here?
What ends the //data in the 'copy table' segment?  What separates one copy statement from another?

**Comment by extremesecurity** [comment]
i-

> 
> 
> @extremesecurity Naturally, that'll only be useful if you're able to run the `pg_dump` command again to recreate the .sql file. Not so useful if you don't still have access to the database it came from. 😇

that has done the trick (converting copy statements to insert statements) but the problem (the unability to import the file) does still persist. when i try to import the file i made through [this](https://manuelvanrijn.nl/blog/2012/01/18/convert-postgresql-to-sqlite/) blog post sqlite3 says the file is not a database and sqlite browser nightly build fails at importing it too

**Comment by chrisjlocke** [comment]
> sqlite3 says the file is not a database

Its still an .SQL file though - just instructions - you have to import it into a database, not open it as a database.

> and sqlite browser nightly build imports a blank table

I assume its still 3 GB.  Open it, and do it in pieces.
Highlight the 'create table' parts, copy it, and run that in DB4S (execute SQL tab)
That'll create the database.

Highlight the 'insert' statements.  Unsure if it'll be one huge statement, or a series of individual statements.  You can either repeat the copy/paste you did above, or paste into a new file and get DB4S to import that.  Do it in small pieces.

**Comment by chrisjlocke** [comment]
> Replace true for ‘t’

Postgres has a 'bit' or 'boolean' data type, which is either 'true' or 'false'.  SQLite doesn't have that, so we need to convert any fields with alternatives.  Just a bit of background info... 😁

**Comment by mgrojo** [comment]
Wouldn't work for you to import the SQL dump in a Postgresql database and
then to export it again using pg_dump options for a more portable SQL
output, like using INSERT statements and so on?

**Comment by chrisjlocke** [comment]
Think that's been done ("that has done the trick (converting copy statements to insert statements)") but being a 3 GB file, there is one error that is stopping the whole import.

**Comment by extremesecurity** [comment]
> 
> 
> Think that's been done ("that has done the trick (converting copy statements to insert statements)") but being a 3 GB file, there is one error that is stopping the whole import.

thanks for the suggestion, it worked bu there is only one flaw, it is very very slow i tried adding begin and end statements but that gave an error; cant begin a transaction in a transaction.

**Comment by extremesecurity** [comment]
nevermind
