### ISSUE TITLE
exporting blob binary to .csv file leads to line feed

### ISSUE THREAD

**Issue by InitialDuan** [sqlitebrowser/sqlitebrowser#2521]
I'm using the Version 3.12.0 on Ubuntu20.04. I want to export sqlite table to csv.file. However, when importing .csv file to LibreOffice, the **binary column "data" always jumps to a new line**, no matter how I set the delimiter in export options. 

Futhermore, there are a few lines behaves expected without line feed (`id 8-15 in the picture`). The only difference between these and other lines is their field "data" values has one more digit(`10 digits`) thus one byte occupied(`18 bytes out of 20`). 

What's the reason behind it? How can I solve it if it's not a bug?
Here you can find the link of this [db3.file.](https://drive.google.com/file/d/1kvznjikSWayWdnkE13MNEytPZLnGPsrI/view?usp=sharing)

![sqlite bug](https://user-images.githubusercontent.com/51959238/103319161-1882a480-4a31-11eb-9805-88ce1bcdcbb3.png)

**Comment by chrisjlocke** [comment]
Have you tried with 3.12.1 ?  That's the latest version.

**Comment by InitialDuan** [comment]
> Have you tried with 3.12.1 ? That's the latest version.
> https://sqlitebrowser.org/dl/

Yes, I did, got the same result.

**Comment by chrisjlocke** [comment]
Aah, OK.  I know a lot of work has gone into the export since the 3.11.2 version (which you originally said you were using).

**Comment by chrisjlocke** [comment]
I'm guessing DB4S is trying to put the bytes into ASCII and failing.  That is just not going to work.  The blob contains 0A which is 10, so DB4S is displaying a line feed.  The other record you mention (with no line feed) is 0B, which is a tab.  You can see the rest of the 'data' is numeric, which is just nonsense.  You're not viewing the correct data - just the data you can 'see'.  It's like trying to read a letter written in a biro and an infra-red pen - you can only make out the biro bits by the naked eye.  OK, its nothing like that.  I'm bad with analogies.  But you can't import/export like that.

I would assume to support exporting this type of data, you'd need to base64 encode it?

SQLite supports 'quote'
select quote(data) from messages

So you can create an SQL statement to view the table, then export that to CSV.  I haven't investigated how to import that back into anything.
But don't forget as its binary data, you won't be able to 'view' that in Excel, etc - its just 'noise' - not printable information.

**Comment by mgrojo** [comment]
I don't get that extra lines using the Unix option as new line character, because the data is correctly quoted when it finds the LF character. But in any case, I suppose we should be converting binary BLOBs to base64 or hexadecimal format, because CSV is a text-file format. Has anyone an argument against that change?

**Comment by mgrojo** [comment]
I've added the conversion to base64 for binary BLOBs when exporting to CSV.  If someone needs hexadecimal format, they can use the `hex` display format and save as a view.

@InitialDuan You can use the AppImage of the continuous build to try it.

**Comment by chrisjlocke** [comment]
@InitialDuan - Have you tried the latest version to see if this fix done by mgrojo works for you?

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@InitialDuan - Feel free to comment back if needed.
