### ISSUE TITLE
readfile error no such function

### ISSUE THREAD

**Issue by beaucoder** [sqlitebrowser/sqlitebrowser#2522]
Using Version 3.12.0 on Ubuntu 20.04
--------------------

#### What did you do?
Created SQL: insert into images (image, name) values (readfile('/media/ken/Backups-Images/.SGGG-No-Dupes/23.jpg'),'Sunny');

#### What did you expect to see?
A newly inserted record.

#### What did you see instead?
Execution finished with errors.
Result: no such function: readfile
At line 1:
insert into images (image, name) values (readfile('/media/ken/Backups-Images/.SGGG-No-Dupes/23.jpg'),'Sunny');

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-lp64] on Ubuntu 20.04.1 LTS (linux/5.4.0-58-generic) [x86_64]
> using SQLCipher Version 3.4.1 (based on SQLite 3.30.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Quoting from the SQLite manual: https://sqlite.org/cli.html
"Note that the readfile(X) and writefile(X,Y) functions are extension functions and are not built into the core SQLite library. These routines are available as a loadable extension in the ext/misc/fileio.c source file in the SQLite source code repositories."

On Windows, there is an 'extensions' folder with 'fileio.dll' in it.  I assume this would be similar on Linux.
Within DB4S, click 'Tools', 'Load extension' and select 'fileio.dll'.

**Comment by beaucoder** [comment]
The readfile() function works flawlessly in the CLI for Sqlite3 version 3.31.1, the current stable version.
No errors occur.
In SqliteBrowser readfile generates a "no such function" error which occurred in older versions of Sqlite3. 
How to update SqliteBrowser to Sqlite3 v 3.31.1.
Can this be done?
Thanks, beaucoder.

**Comment by chrisjlocke** [comment]
DB4S itself (v3.12.1) used SQLite v3.33.0.  The version of SQLite used in DB4S SqlCipher was slightly behind.
DB4S v3.12.0 used SQLite v3.32.2.

Do you need the SqlCipher flavour?
