### ISSUE TITLE
[Suggestion] Do not map keyboard shortcuts to F keys

### ISSUE THREAD

**Issue by ediril** [sqlitebrowser/sqlitebrowser#2523]
I just upgraded to the latest version and noticed that "Close Database" shortcut got updated to COMMAND-F4. While it's fine to change keyboard shortcuts, please refrain from mapping them to F keys as new macbook pros made it a pain to use them.

**Comment by chrisjlocke** [comment]
You can still press [Alt] + [F], then press [C].
There is also a large button in the toolbar.

![image](https://user-images.githubusercontent.com/7872218/103408643-43691780-4b5b-11eb-8a7c-a6a5f4a68fb5.png)

**Comment by chrisjlocke** [comment]
Hopefully in the future (as it's been requested before) we can have configurable shortcuts, so they can be mapped to whatever you need them to be.

**Comment by ediril** [comment]
@chrisjlocke, thank you for replying. Yes, there are certainly workarounds available. 

`[Alt] + [F], then press [C]` does not work on OSX. I would caution against using multiple-key-stroke style keyboard shortcuts. They are not as productive in my opinion.

The possibility to remap shortcuts is great but I imagine it's a good bit of dev effort. Plus, it doesn't take away from the need for the app to set sensible defaults.

I would love it if we could go back to COMMAND-W to close the database, or anything other than the F keys. I also understand if you are not willing to do it, I'll use the button.

**Comment by mgrojo** [comment]
OSX does not support [accelerators](https://doc.qt.io/qt-5/accelerators.html)? 

Close Database was changed to Ctrl+F4 due to #2025. There are too many actions with shortcuts, unfortunately, we cannot do without the F keys.

**Comment by ediril** [comment]
> OSX does not support accelerators?

I'm not sure, it doesn't seem to work or maybe I'm doing it wrong. I'm not a big fan of them. Multiple keystrokes are not as productive as two-key combos.

> Close Database was changed to Ctrl+F4 due to #2025.

Ah I see. I don't close windows/tabs very often, so I missed that.

I use "Close Database" quite often though and I imagine I'm not alone. I'd love to have a different key combo for it. How about Ctrl+U? It doesn't seem to be assigned. If you don't want to change it again, maybe assign both shortcuts?

**Comment by mgrojo** [comment]
> > OSX does not support accelerators?
> 
> I'm not sure, it doesn't seem to work or maybe I'm doing it wrong. I'm not a big fan of them. Multiple keystrokes are not as productive as two-key combos.

In principle, they are not supported, according to [this](https://superuser.com/questions/24159/osx-keyboard-shortcuts-in-dialogs), but take a look, because there is an alternative for dialogs, which might also work for menus.

> I use "Close Database" quite often though and I imagine I'm not alone. I'd love to have a different key combo for it. How about Ctrl+U? It doesn't seem to be assigned. If you don't want to change it again, maybe assign both shortcuts?

I don't like Ctrl+U, it cleans text entries, at least in Linux. We can add Ctrl+Shift+W as a secondary shortcut for closing the project, since in some applications it means "[Close all files](https://defkey.com/search?irq=close+file)"

**Comment by ediril** [comment]
How about Ctrl+Alt+W to close the database then? Or Ctrl+Alt+D.. anything but F keys which are very unfriendly to use on macbooks these days.

**Comment by mgrojo** [comment]
Ok, this is usual for laptops, you usually have to press an additional Fn key. I wonder why they give more importance to the laptop control keys (volume, brightness, etc.). It should be the opposite.

I've finally set them in this way:
* Close Database: Ctrl+F4 and Ctrl+Alt+W
* Close Project: Ctrl+Shift+W and Ctrl+Shift+F4
* Close SQL Tab: Ctrl+W

The primary shortcut will appear in the menu. In the case of `Close Database`, both shortcuts will appear in the tooltip at the toolbar.

Could you confirm using [tomorrow's nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) that it works fine for you?

**Comment by ediril** [comment]
@mgrojo Thank you, yes I will confirm and let you know

**Comment by ediril** [comment]
I confirmed that the new keyboard shortcut for "Close Database" is working as well as Ctrl+F4, so closing this ticket. 

Thank you very much for taking my suggestion, you just improved the workflow of all MBP users out there! 😄
