### ISSUE TITLE
Cell Editor misinterprets text with newline as binary

### ISSUE THREAD

**Issue by ediril** [sqlitebrowser/sqlitebrowser#2527]
I have multiline text (i.e. has newlines) inserted into a string column. Database Cell Editor is misinterpretting these values as BINARY even though they are just TEXT.

Note that version 3.11.2 works correctly.

Useful extra information
-------------------------
#### What operating system are you using?
- [x] macOS: ( _version: 10.14.6 )

#### What is your DB4S version?
Latest

**Comment by mgrojo** [comment]
Could you paste a minimal example here? Choose a short case, press Ctrl+A and Ctrl+Shift+C inside the binary editor and paste it here.

**Comment by ediril** [comment]
Btw this works correctly on v3.12.1 as well. It does not work on the `nightly` build.

Here i what I do: just edit a text column (null or empty) and enter a character, say `a`, then hit ENTER to go to the next line and enter another character like `b`. When I click apply, the cell editor goes into BINARY mode.

If i enter just `ab` without any ENTER and click Apply, then it remains as TEXT.

**Comment by mgrojo** [comment]
Ok, I can reproduce it now. Surprisingly, it did not happen with a text in Spanish which I used. But new texts in Spanish are affected, so I don't know yet where the problem lies.

**Comment by ediril** [comment]
Perhaps it's due to this change? https://github.com/sqlitebrowser/sqlitebrowser/commit/5e0c56a47faa3f2982dcf12b37bb4ec2edec87f6

Is `LF`, `CR` etc considered printable characters? I'm guessing not.

**Comment by ediril** [comment]
I think that's it. The following code says `\r` and `\n` are not printable:

```
    QString testStr = "cd\n\r";

    for (int i = 0; i < test.size(); i++) {
        bool printable = testStr.at(i).isPrint();
    }
```

I guess Qt doesn't consider these as "whitespace"..

**Comment by mgrojo** [comment]
Yes, the problem entered with that commit. Thanks for reporting.

It should be fixed in tomorrow's nightly. Please, report any corner case that you could encounter.

**Comment by ediril** [comment]
I confirmed that this is fixed in the latest nightly build. Thank you very much!
