### ISSUE TITLE
File/Export/SQL to delete a field

### ISSUE THREAD

**Issue by ch2021** [sqlitebrowser/sqlitebrowser#2529]
Since SQLite does not allow direct delete of a field, it would be great if the browser could export the SQL to delete a field.  Potentially this could build on the existing export SQL, schema only.

For example, please see https://stackoverflow.com/questions/5938048/delete-column-from-sqlite-table/5987838#5987838

So the user would click File/Export/SQL to delete a field, and then a popup would appear.  The popup would have a selector for a single table, and then a multi-selector to identify the fields to delete.  Then a Save button very similar to File/Export/SQL.  No need to ask about preserving data, etc., because the generated SQL will create a new table without the newly deleted fields, then update the new table with data from the existing table.

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
No.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
Don't have a screenshot.  But do please let me know if it's not clear.

**Comment by ch2021** [comment]
For example, here is the code I wrote to remove a few fields from a table.  I used File/Export/SQL, schema to help:

/* Now remove dead fields from HallEffectConfig */

ALTER TABLE "main"."HallEffectConfig" RENAME TO "temp_HallEffectConfig";
DROP TABLE IF EXISTS "HallEffectConfig";
CREATE TABLE IF NOT EXISTS "HallEffectConfig" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"WellId"	INT NOT NULL,
	"HallEffectCodePath"	INT NOT NULL,
	"StrokeSensorStartLocation"	INT NOT NULL,
	"HallEffectSensorsEnabled"	BIT NOT NULL,
	"Nrevs"	DOUBLE NOT NULL DEFAULT 144.0,
	"StartAngleOffset"	DOUBLE NOT NULL DEFAULT 0.0,
	"SPM"	DOUBLE,
	"UseMeasuredStrokeLength"	BOOLEAN NOT NULL DEFAULT 0,
	"UseCustomPumpingDimensions"	BOOLEAN NOT NULL DEFAULT 0,
	"DeadCenterOffset"	FLOAT NOT NULL DEFAULT 0.0,
	"Rdimension"	FLOAT NOT NULL DEFAULT 0.0,
	"Kdimension"	FLOAT NOT NULL DEFAULT 0.0,
	"Cdimension"	FLOAT NOT NULL DEFAULT 0.0,
	"Pdimension"	FLOAT NOT NULL DEFAULT 0.0,
	"Adimension"	FLOAT NOT NULL DEFAULT 0.0,
	"Idimension"	FLOAT NOT NULL DEFAULT 0.0,
	"ChainSprocketRatio"	FLOAT NOT NULL DEFAULT 0.0,
	"MeasuredAngleOffset"	DOUBLE NOT NULL DEFAULT 0.0,
	"CrankAngleOffsetMethod"	DOUBLE NOT NULL DEFAULT 0.0,
	"OneDigitalPosition"	BOOL NOT NULL DEFAULT 0
);

INSERT INTO "main"."HallEffectConfig" 
	SELECT 
		"Id",
		"WellId",
		"HallEffectCodePath",
		"StrokeSensorStartLocation",
		"HallEffectSensorsEnabled",
		"Nrevs",
		"StartAngleOffset",
		"SPM",
		"UseMeasuredStrokeLength",
		"UseCustomPumpingDimensions",
		"DeadCenterOffset",
		"Rdimension",
		"Kdimension",
		"Cdimension",
		"Pdimension",
		"Adimension",
		"Idimension",
		"ChainSprocketRatio",
		"MeasuredAngleOffset",
		"CrankAngleOffsetMethod",
		"OneDigitalPosition"
	FROM "main"."temp_HallEffectConfig";
DROP TABLE "main"."temp_HallEffectConfig";

**Comment by chrisjlocke** [comment]
DB4S currently supports the deleting of fields.

https://user-images.githubusercontent.com/7872218/103571346-a0016500-4ec2-11eb-87f8-ea74a148af9b.mp4

It also supports moving fields around, and adding new fields (not necessarily at the end of the table) which SQLite doesn't normally support.

Behind the scenes. a new table is created and the data is copied across, so on big tables it can take a while, but generally, it's fast and works well.

**Comment by ch2021** [comment]
Hi Chris, thanks for the quick reply.  Understood that DB Browser for SQLite does support the deleting of fields.  But that does not help us, because we need to implement changes to our production SQLite database in SQL patch files.  So we have to implement delete field in SQL.

**Comment by mgrojo** [comment]
Maybe the SQL log, submitted by the application, can be of help. Do it in
the GUI and then get your patch from the Log.

**Comment by ch2021** [comment]
Thank you, mgrojo!  I did not know about the SQL log.  Great solution.
