### ISSUE TITLE
Suggestion: Use "delete" (or "backspace") to clear a value to null directly in browser

### ISSUE THREAD

**Issue by JC3** [sqlitebrowser/sqlitebrowser#253]
I think it would be handy if a value could be set to null by highlighting it (single click, not edit mode) in the data browser then pressing "delete" or "backspace" (equivalent of double clicking value to open the editor then pressing "clear").

Currently values can be edited without actually opening the editor window, but they still require the edit window to be opened to set them to null. If this were added it'd nicely round off the editing actions that can be done without having to open the editor.

**Comment by justinclift** [comment]
Yeah, this makes sense. :smile"

**Comment by rp-** [comment]
well, there is a difference between NULL and empty string, that's why there is a clear button.
maybe a key like shift-(delete, backspace) make it faster to edit such columns

**Comment by justinclift** [comment]
For me, on OSX, the delete and backspace keys don't do anything at present.  Are they supposed to already be the equivalent of making a null string? (just checking)

It does sound reasonable to have something like delete / backspace be the "make an empty string" keystroke, with shift-delete / shift-backspace being the "make a NULL" key combination.

**Comment by MKleusberg** [comment]
Can we close this now that for issue #443 we've implemented the Delete and Alt+Delete shortcuts?

**Comment by justinclift** [comment]
Good point, lets do that. :smile:
