### ISSUE TITLE
DB Browser crashed when try to use Filter

### ISSUE THREAD

**Issue by csanyipal** [sqlitebrowser/sqlitebrowser#2533]
Details for the issue
--------------------

#### What did you expect to see?
I expect to see the filtered rows of the database.

#### What did you see instead?
I started the DB Browser in a terminal emulator window by running the 'sqlitebrowser' command. After it crashed I get this error:
$ sqlitebrowser 
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 14) >= this->size() (which is 14)
Aborted (core dumped)

https://user-images.githubusercontent.com/1310341/104008165-560dcd00-51a9-11eb-924c-b731b4127d29.mov

Useful extra information
-------------------------
> DB4S v3.12.99 (Jan  3 2021) [built for x86_64-little_endian-lp64] on Ubuntu 20.04.1 LTS (linux/5.4.0-59-generic) [x86_64]
> using SQLCipher Version 4.3.0 community (based on SQLite 3.30.1)
> and Qt 5.12.8

**Comment by justinclift** [comment]
Thanks @csanyipal, that definitely sounds like a bug that shouldn't be toooooo hard to fix.  Hopefully. :wink:

@mgrojo Sounds like your kind of thing?

**Comment by tonypdmtr** [comment]
I noticed the same.  It started with this version: DB.Browser.for.SQLite-2020-12-21-win32.zip

**Comment by mgrojo** [comment]
It was fixed in b41046e6b6955f9222fa8073cf0bae7f151863b5. Please update and confirm.

**Comment by csanyipal** [comment]
I just updated DB Browser to the 
DB Browser for SQLite Version 3.12.99 (Jan 10 2021)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.8
SQLCipher Version 4.3.0 community (based on SQLite 3.30.1).

I can use Filter's now. Fixed. Thanks!

**Comment by mgrojo** [comment]
Great. Thanks!
