### ISSUE TITLE
No search refresh after insertion

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2537]
Details for the issue
--------------------

#### What did you do?
Type some search term in the "find anywhere" box.
Matching items appear.
Insert a new item.
#### What did you expect to see?
It should show the previous found item plus the new one if it happens to match the search.
#### What did you see instead?
Screen becomes blank.   Even the refresh button doesn't correct it.  You need to retype the search term.
Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ 7___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
What DB4S version are you using?

**Comment by tonypdmtr** [comment]
![image](https://user-images.githubusercontent.com/11968823/104580509-0c6c2900-5666-11eb-9de4-e9a6fa8de72e.png)

Must also note that the column search also has a similar problem.  Upon insertion the search is ignored and ALL records are shown.

**Comment by MKleusberg** [comment]
Thanks, @tonypdmtr! It's really helpful to have you around testing the nightlies so regularly :smile: The issue should be fixed in tomorrow's nightly build. Can you give that another try?

**Comment by tonypdmtr** [comment]
I tried this one DB.Browser.for.SQLite-win32.zip                    20-Jan-2021 05:36            17818586
and it seems to work OK with respect to this issue.

**Comment by MKleusberg** [comment]
Cool, I'll close this issue then. Thanks again for pointing this out, @tonypdmtr! If you should notice anything else in the new build please let us know :smile:
