### ISSUE TITLE
Import table from CSV file : Option to change column names

### ISSUE THREAD

**Issue by cherie-O2** [sqlitebrowser/sqlitebrowser#2540]
Describe the new feature
--------------------------
Option to change column name while Importing "Table from CSV file". This is helpful where names are not as per database metadata or very long names or contains special chars like /"$# etc.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
NO

#### Does this feature exist in another product or project? Please provide a link.
I have seen this option, but do not remember exact product

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![Screenshot 2021-01-15 at 19 36 02](https://user-images.githubusercontent.com/23432462/104737260-07909d80-576a-11eb-8fb7-3d11106fa1db.png)

**Comment by chrisjlocke** [comment]
Can't you amend the CSV file prior to importing?
I've seen CSV mapping, so that you can put fields from the CSV file in specific fields in a table, or not import a particular column, etc, but as you can import into a new table, its easier to import then do any data mangling once the data is in a table.

**Comment by mgrojo** [comment]
I agree with @chrisjlocke. You can edit the table schema after importing. I don't see any benefit in adding column name edition in the import phase.

**Comment by chrisjlocke** [comment]
I'll close this, as its not something we'll probably code against in the short term.
Once things settle down to a manageable level, it could be something we revisit.
Thanks for suggesting it though.
