### ISSUE TITLE
timestamp columns which display has been changed should maintain this state

### ISSUE THREAD

**Issue by ipinky77** [sqlitebrowser/sqlitebrowser#2541]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
not an issue

#### Does this feature exist in another product or project? Please provide a link.
don't know

#### Do you have a screenshot? Please add screenshots to help explain your idea.
I can change the display of a timestamp column to display say Unix epoch time. But I have to do this "change" (changing the display format) EVERY time I reopen and browse the table

**Comment by chrisjlocke** [comment]
If you save a project (Click 'File' then 'Save Project') you'll be prompted to save a .sqbpro file.  Open this file instead of the database, and your column settings (as well as a bunch of other preferences) will be saved.
😊😊

**Comment by ipinky77** [comment]
Great! Thanks a lot

Didn’t know about that

Works fine

Michael

**Comment by chrisjlocke** [comment]
We'll add something more to the wiki, or make a 'did you know?' thingy... it's not a super-obvious feature.
