### ISSUE TITLE
Nightly .dmg images are incomplete

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2542]
Originally alerted by @baltakatei.

![image](https://user-images.githubusercontent.com/7872218/104827104-54e83a00-5852-11eb-8825-f10cf9fb3db4.png)

Both .dmg images are poopy.
Hopefully something @justinclift can investigate...... as he luuurves looking into incomplete .dmg image issues.......

**Comment by justinclift** [comment]
No worries.  This was pointed out in private email a few days ago too, I just haven't yet had the spare time to investigate. :frowning:

**Comment by justinclift** [comment]
Looking into it now, the [log file for the macOS nightly build](https://nightlies.sqlitebrowser.org/osx/nightly-20210112.log) seems to show the problem:

```
In file included from TableBrowserDock.cpp:8:
In file included from ./MainWindow.h:5:
In file included from ./sqlitedb.h:5:
./sql/sqlitetypes.h:30:12: error: no matching function for call to 'equal'
    return std::equal(a.begin(), a.end(), b.begin(), b.end(), [](unsigned char c1, unsigned char c2) {
           ^~~~~~~~~~
./sql/sqlitetypes.h:46:16: note: in instantiation of function template specialization 'compare_ci<std::__1::basic_string<char> >' requested here
        return compare_ci(str.substr(0, with.size()), with);
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1216:1: note: candidate function template not viable: requires 4 arguments, but 5 were provided
equal(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __pred)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1227:1: note: candidate function template not viable: requires 3 arguments, but 5 were provided
equal(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__bit_reference:1264:60: note: candidate function template not viable: requires 3 arguments, but 5 were provided
    template <class _Dp, bool _IC1, bool _IC2> friend bool equal(__bit_iterator<_Dp, _IC1>,
                                                           ^
1 error generated.
make[2]: *** [release/TableBrowserDock.o] Error 1
```

Seems to be something to do with the `equal()` call, added a few days ago in the recent C++14 commit (740c88b7022805f29b6ee402ba53b3e81d209049).

@MKleusberg Thoughts? :smile:

**Comment by scottfurry** [comment]
The path `/../include/c++/v1/algorithm` suggest to me that the compiler is not a final version (Pre-release, interim, or not LTS release version).

The details of std::algorithm::equal (see [here](https://en.cppreference.com/w/cpp/algorithm/equal) ) seem most messy. My "off-the-cuff" thought is to have pre-processing statements to guard different levels of C++. See [here](https://www.tutorialspoint.com/how-to-determine-the-version-of-the-cplusplus-standard-used-by-the-compiler) for ideas about C++ version testing.

**Comment by justinclift** [comment]
> The path /../include/c++/v1/algorithm suggest to me that the compiler is not a final version (Pre-release, interim, or not LTS release version).

Interesting.  It's using the installed Xcode, so personally I just throw my hands up, say "Apple" and roll my eyes. :wink:

**Comment by MKleusberg** [comment]
The problem seems to be that the ```-std``` parameter is passed twice to clang, one time setting it to C++11 and one time setting it to C++14:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -std=c++14 -DENABLE_SQLCIPHER -DCHECKNEWVERSION -O2 -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_MACEXTRAS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I/usr/local/opt/sqlcipher/include -I/usr/local/include -I../libs/qhexedit/src -I../libs/qcustomplot-source -I../libs/qscintilla/Qt4Qt5 -I../libs/json -I../../sqlitebrowser -I../../../Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtMacExtras.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtConcurrent.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I../../../Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -Irelease -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I.ui -I../../../Qt/5.15.2/clang_64/mkspecs/macx-clang -F/Users/jc/Qt/5.15.2/clang_64/lib -o release/MainWindow.o MainWindow.cpp
```

@justinclift Are we doing anything special to build the macOS nightlies or is it just running ```qmake && make``` to build? Also is this doing a clean build each time or could there be traces of an old Makefile somewhere?

**Comment by scottfurry** [comment]
A quick grep of sources was insightful.

IIRC, the last `-std` takes precedence, overriding any previous directives. It looks like we already have it in place in CMake but not correctly (CMakeLists.txt line 27). This would be better served, IMHO, by utilizing CMake directives rather than `add_definitions` (see [CXX_STANDARD](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html) directive).

Also, libs/DB4S_PATCHOS (line 27) adds in the `-std=c++11`. I suspect the patch is pulled in first, then the `-std=c++14` is then added to the command by qmake or similar.

**Comment by MKleusberg** [comment]
@scottfurry As far as I can tell the macOS build only uses qmake. So the CMakeLists.txt file is completely ignored. But I might be wrong about that. The patch for the libs adds C++11 but that should be fine. The libraries are a subproject which is built more or less independently. At least the settings for the libraries don't propagate to the top-level project. And since the libraries don't need C++14 we can leave it at C++11.

**Comment by justinclift** [comment]
@MKleusberg Looking at the nightly build script for macOS, we're using (Qt 5.15.2) [qmake](https://github.com/sqlitebrowser/sqlitebrowser/blob/89587a7d67928388d57a092817816b4971cf6e4b/installer/macos/build_sqlitebrowser_nightly.sh#L91) for it:

```
qmake sqlitebrowser.pro -r -spec macx-clang CONFIG+=x86_64
```

@scottfurry That [patch file](https://github.com/sqlitebrowser/sqlitebrowser/blob/89587a7d67928388d57a092817816b4971cf6e4b/libs/DB4S_PATCH_05#L27) seems like it's only for QScintilla?

**Comment by scottfurry** [comment]
Just chiming in with what I could find with a grep search for "-std". The files mentioned, plus changelog, were the output. Throw it out there.

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by justinclift** [comment]
Hmmm, if the last invocation of `-std` takes priority, then maybe we should just add `-std=c++14` to the end of our qmake line and see if that works?

**Comment by scottfurry** [comment]
Correct me if I'm wrong, but qmake is being used to build on MacOS. That explains why a `.xcodeproject` file doesn't exist in the tree. However, the Qt `.pro` file contains the line:
```
QMAKE_CXXFLAGS += -std=c++14
```

Meaning to take the defaults for qmake and append to c++ flags some contents( in our case, another standard directive). A quick google search found that this may be the wrong directive to use. I found numerous pages stating to use:
```
CONFIG += c++14
```
Some URLS were [older](https://wiki.qt.io/How_to_use_C%2B%2B11_in_your_Qt_Projects) but they all mentioned the same idea - use `CONFIG += {stuff}` as opposed to `QMAKE_CXXFLAGS += {stuff}`.

**Comment by justinclift** [comment]
Ahhh.  So for a quick test, `CONFIG+="-std=c++14" added to the Qmake line might be workable?

**Comment by justinclift** [comment]
As a data point, just adding a plain `-std=c++14` (not as `CONFIG`) to the qmake line doesn't work.

I'll try the `CONFIG` version now.

**Comment by scottfurry** [comment]
@justinclift - the URL in my post above should help out here. My impression( after reading [this](https://amirkoblog.wordpress.com/2018/08/14/creating-c17-enabled-qt-projects/) ) is that `QMAKE_CXXFLAGS` _could be_ used...assuming qmake didn't support that c++ version(i.e. c++20 et al going forward). However, for _supported versions_ (i.e. 11, 14, 17), `CONFIG` is _preferred_. I may be wrong but that's my impression reading through pages.

**Comment by justinclift** [comment]
No worries, a test build with the `CONFIG+=` approach is running at the moment.  So far, no error but it's still near the beginning.  Lots of deprecation warnings around Qt Network pieces though. :shrug:

**Comment by justinclift** [comment]
Hmmm, it looks like the `CONFIG+="-std=c++14"` approach might have worked.  Let's see if the full .dmg generation completes ok... :smile:

**Comment by scottfurry** [comment]
I suspect it will succeed - sort of. I recall there were HUGE issues with mixing of earlier revisions of c++ (pre 0x days). I can't speak to whether a build of the supporting libraries(json, et al) with c++11 will play nicely w/ application built using c++14. Throwing it out there...

**Comment by justinclift** [comment]
Oh, I just noticed I made a slight typo, but it still worked:

`CONFIG+="c++14"`

**Comment by scottfurry** [comment]
Question becomes how many `-std=...` was seen on the command line?

**Comment by justinclift** [comment]
Well, that's ironic.  With the `-std=` piece in there, the compilation fails with the `equals()` error reported above.  eg:

```
CONFIG+="-std=c++14"
```

However, with my typo version the compile works:

```
CONFIG+="c++14"
```

Fortunate typo? :smile:

**Comment by justinclift** [comment]
I've captured the output log file for the new broken build (using `CONFIG+="-std=c++14"`).  I'm rerunning a build now with the typo version (`CONFIG+="c++14"`), and I'll capture the log file for that too, then upload them both so everyone can take a look. :smile:

**Comment by scottfurry** [comment]
Ah...
If there is breakage, I would look at the log output for what standard qmake is applying. Did you look at the pages linked earlier? I believe the line is supposed to read
```
CONFIG += c++14
```
(note spacing and absence of quotes).

**Comment by justinclift** [comment]
Ahhh.  I used `CONFIG+="c++14"` on the command line, which worked ok.  That's the same as the example you just gave, and (in theory due to command line) the spacing and quoting work out the same.  Looks like I accidentally got it right. :wink:

**Comment by justinclift** [comment]
Just committed the [working change](https://github.com/sqlitebrowser/sqlitebrowser/commit/cdf6db2fc0de3996989fa63c161abd6d7afffbf8) to the macOS nightly build script in our repo, and also added the same info to our [BUILDING.md](https://github.com/sqlitebrowser/sqlitebrowser/commit/3e06b2e4f9db40deff5b7dd6441d1a550b2558e2) for good measure. :smile:

**Comment by MKleusberg** [comment]
Awesome! Looks like the nightlies were built correctly again. Thanks, @justinclift and @scottfurry  for figuring this out! :smile:

**Comment by justinclift** [comment]
The newly-working-again dmg files have been verified as good by @baltakatei in https://github.com/sqlitebrowser/sqlitebrowser/issues/1760#issuecomment-763869819 too. :smile:
