### ISSUE TITLE
SUM 

### ISSUE THREAD

**Issue by Biz7662** [sqlitebrowser/sqlitebrowser#2543]
![Schermata 2021-01-17 alle 13 56 06](https://user-images.githubusercontent.com/73756170/104844112-87377d00-58ce-11eb-997a-7b83771a25e0.png)
![Schermata 2021-01-17 alle 14 15 23](https://user-images.githubusercontent.com/73756170/104844113-8868aa00-58ce-11eb-9b5a-4692404f6638.png)

Hi all, 
I'm trying to SUM just 2 attributes of 2 different records on my table. The code I wrote doesn't work ..
Some one has any idea and can help me ? 

Thank you

-----------------------

**Comment by chrisjlocke** [comment]
The last two fields - I assume this is a text field, and you have two values in the same field? 3 and 1 in one cell, and 1 5 in the other cell?
So you're trying to add up 1 and 5?

**Comment by Biz7662** [comment]
Thank you for answering, I'm training my self for an exam at university so this is table is just an example but I think could be useful to understand how to do I it! 
Maybe I express incorrectly my question. The last two records: 'Chemioluminescence' and 'Betarayattenuation' had each one a value on the 'Fanta' column and I'm looking for a code for having a SUM of that two values ( 31 and 15).

**Comment by chrisjlocke** [comment]
Aah, OK, it might just be the font, but it looks like '3 1' and not '31'.

Your query was 97% correct. I assume the bottom select statement hasn't been run, as the 'sum' isn't in the top screenshot.

My table isn't called the same as yours, but the process is the same.

![image](https://user-images.githubusercontent.com/7872218/104916338-d2629600-5989-11eb-9e6a-52388b6b6c60.png)

So in your 'where' statement, you're doing the right thing (I want this AND that) but you have to do it as if you're pulling out a record out of a hat ... is the record I want this one .... or is it that one?  a record (singular) can't be two values (1 AND 2) it can only be 1 OR 2.  Yell if that doesn't make sense and I can find another example.

Note you only get one row returned, even though you are summing two - when you ask for a sum, you only get one record back, so also selecting the other field, you only get that for the last record.  Again, yell if this doesn't make sense.

**Comment by Biz7662** [comment]
![Schermata 2021-01-18 alle 16 44 36](https://user-images.githubusercontent.com/73756170/104936283-98ef5200-59ac-11eb-93da-ae8c29e9be93.png)

I solve in this way , with the operator IN ... It's ok but I don't know why in the result ('46') the '6' seems to be cut on the left side. Anyway thank you for answering!

**Comment by chrisjlocke** [comment]
Yes, the 'IN' is a good substitute too.  Useful if you have a number of entries - saves using all those 'OR' statements.
Well done.

The 6 is being cut off due to the font being used.  Go into preferences and select another font.
I'll close this as the main issue has been resolved, but feel free to comment further or reopen the issue.
