### ISSUE TITLE
Read only

### ISSUE THREAD

**Issue by Rach5242** [sqlitebrowser/sqlitebrowser#2547]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for i386-little_endian-ilp32] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

my file isnt a read only file and I dont open it as read only however when I click and to modify table then make a change and then try to click ok it tells me I cannot do this as the file is read only.

**Comment by chrisjlocke** [comment]
Where is the database stored?  DB4S can't edit a database if you're running DB4S as a normal user and the database is in the same folder as the application.
Try storing the database on the desktop or in your documents folder.  It will want to create a journal file, which is the only additional file.
Lastly, ensure the file is not 'locked'.  If the database has been downloaded, then Windows sometimes locks it.  Right click the file, select Properties, and see if it has an 'Unlock' option at the bottom.

![image](https://user-images.githubusercontent.com/7872218/105065279-986ebe00-5a75-11eb-8fd6-c2be71b5a717.png)

**Comment by Rach5242** [comment]
I tried the top one but still having the same issues and I have checked they are not read only in properties etc

**Comment by Rach5242** [comment]
![image](https://user-images.githubusercontent.com/73558209/105066841-18495800-5a77-11eb-89d3-cae9779a5417.png)
![image](https://user-images.githubusercontent.com/73558209/105066918-26977400-5a77-11eb-8dea-81e57731db81.png)
![image](https://user-images.githubusercontent.com/73558209/105067215-64949800-5a77-11eb-8ed0-a95b9924eda1.png)

**Comment by chrisjlocke** [comment]
Weird.  You've selected 'administrators' in the file properties though - I assume you run DB4S as a normal user.  Did you create the bots and .vscode directories?
directories starting with dots are usually created by applications, and could be hidden, etc.
As a test, create a 'test' directory on your desktop, and slap in there the 'main.sqlite' file, just to check that works.  That should be fine.
If that works, try just the 'bots' directory.  If that works, try the .vscode directory.
A long shot, but maybe the full path (including filename) is greater than 255 characters?  I haven't tested that, but it might be close.  Or miles off.  
Lastly, you can run DB4S as administrator.  Hold down shift while right-clicking the shortcut, and you should see a 'run as administrator' option.  But I'd rule out the other options first... just to be sure...

**Comment by chrisjlocke** [comment]
As an aside, the font-size in DB4S looks quite large.  Is this OK, or do you want this reduced?  If you click 'Edit' and 'Preferences', there should be a 'font size' option in the middle.  8 or 9 is a good size, but it's obviously personal preference.  Just checking... ;)

**Comment by Rach5242** [comment]
I run it as a normal user yes. It is weird because one day it was working didnt change any setting then thenext day when i tried it started to fail and hadnt moved the file or anything. 


Yeah I changed the text because often I am not sat like right in front of the screen so I can still read it at a distance XD

**Comment by Rach5242** [comment]
should I just try and create and exact replica of the database then as nothing else seems to be working?

**Comment by chrisjlocke** [comment]
Out of what I posted before, what have you tried?

    As a test, create a 'test' directory on your desktop, and slap in there the 'main.sqlite' file, just to check that works. That should be fine.
    If that works, try just the 'bots' directory. If that works, try the .vscode directory.
    Lastly, you can run DB4S as administrator. Hold down shift while right-clicking the shortcut, and you should see a 'run as 
    administrator' option. But I'd rule out the other options first... just to be sure...

**Comment by Rach5242** [comment]
i tried all of it

**Comment by chrisjlocke** [comment]
OK.  There should be no issue opening the file on your desktop, or running DB4S as administrator.
When you open the file, can you click on 'Tools' and 'Integrity check'

![image](https://user-images.githubusercontent.com/7872218/105152686-69049380-5aff-11eb-806a-82702969d46e.png)

The error is caused by DB4S not being about to create a journal file.
By putting the database (main.sqlite) in its own directory, you're eliminating an existing file being present, and of course, any permission errors (Windows can usually create a file in the directory you create).

As another test, I assume you can start DB4S, create a database and store it in the directories you've created.  Click 'New database', get the 'Save as' dialog, save the database as '1.db' or something, then create a table, etc.  How far do you get?

Also, if you click 'New database', can you right-click and create a folder and new documents OK?  Again, this tests the permissions - you're creating files as DB4S would.

Eg: 

https://user-images.githubusercontent.com/7872218/105156529-e16d5380-5b03-11eb-8622-277a6d8b9fe7.mp4

How do you launch DB4S?  Shortcut, or by double-clicking a database file?

**Comment by MKleusberg** [comment]
Just pointing out one weird thing I noticed: we try to detect a read-only file and a read-only directory when opening a database. If it is read-only altering a table should be disabled and a small 'Read only' text should appear on the right side of the status bar. The fact that this isn't the case here shows that something weird and unexpected is happening but unfortunately I have no clue what it is either.

**Comment by chrisjlocke** [comment]
Creating a folder on the desktop should get around any weird permission issues.  Unsure what the problem is... very weird.

**Comment by justinclift** [comment]
When weird stuff like this happens, generally the next thing to check is whether the standard [SQLite command line utility](https://sqlite.org/cli.html) is able to work with the file ok.

Doing that is a way of figuring out if there's something strange going on with Windows (maybe some security software?), or if it's a problem with our application.

@Rach5242 The SQLite command line utility can be downloaded from the main SQLite website [here](https://sqlite.org/2021/sqlite-tools-win32-x86-3340100.zip).

It's not super user friendly, but as long as you back up your database first it shouldn't hurt to try. :smile:

**Comment by chrisjlocke** [comment]
Hi @Rach5242 - Is this still an issue?  Have you spent any more time on this to resolve it?

**Comment by Rach5242** [comment]
Sorry for the late reply. The only way to fix it was to create a totally brand new database.

**Comment by chrisjlocke** [comment]
No problem - thanks for coming back to us.  Sorry we couldn't easily resolve this.
