### ISSUE TITLE
"Result: no such function: iif" in new version

### ISSUE THREAD

**Issue by kreolsky** [sqlitebrowser/sqlitebrowser#2549]
Details for the issue
--------------------

#### What did you do?
`select word, iif(freq < round(avg(freq)), 'rare', 'frequent') as category from words`

#### What did you expect to see?
correct responce

#### What did you see instead?
```
Execution finished with errors.
Result: no such function: iif
At line 1:
select word, iif(freq < round(avg(freq)), 'rare', 'frequent') as category from words
```

Useful extra information
-------------------------
> DB4S v3.12.99 (Jan 20 2021) [built for x86_64-little_endian-lp64] on Linux Mint 20.1 (linux/5.8.0-38-generic) [x86_64]
> using SQLCipher Version 4.3.0 community (based on SQLite 3.30.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
There are two versions of DB4S (DB Browser for SQLite).  The 'normal' version and the build with SQLCipher.  The SQLCipher uses an older (baked in) version of SQLite - v3.30.  The iif function arrived in v3.32 of SQLite.  Until the SQLCipher library is updated with a newer version of SQLite, we're stuck with the older version.
The 'non-SQLCipher' version of DB4S uses the latest version of SQLite.

**Comment by kreolsky** [comment]
Thanx! But haw can I install 'non-SQLCipher' version? :)

**Comment by justinclift** [comment]
@kreolsky That kind of depends... we provide macOS and Windows builds where it's pretty easy to pick, but on Linux things are (for now) a bit more complicated.

The version of DB4S you're using at the moment.  Is that from the standard Linux Mint installation repositories?

If so, then it **might** work to try out our Ubuntu builds:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/#ubuntu-and-derivatives

There are two potential builds there, a stable build, and a nightly build.  I'd try the stable one first, and if that doesn't have `iif()` then I'd try the nightly build.

If none of those works, then it's not hard to [compile and install DB4S](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu--debian-linux) yourself.  But you'd need to make sure it's done with SQLite v3.32 or newer, which I personally don't remember how to do.  Shouldn't be toooo hard though. :smile:

**Comment by chrisjlocke** [comment]
I'll close this as the main issue has been addressed, but feel free to comment back if you have any further issues and we can look more into it. 😃

**Comment by kreolsky** [comment]
Thank you guys! I do it! :)
