### ISSUE TITLE
Suggestion: 'Tab' indents multiline selection in SQL editor

### ISSUE THREAD

**Issue by JC3** [sqlitebrowser/sqlitebrowser#255]
It would be convenient of pressing 'tab' in the SQL editor when multiple lines of text were selected indented all of the lines. The current behavior replaces the selection with a tab.

This could be useful when incrementally building complex queries and subqueries.

**Comment by justinclift** [comment]
Yep, this sounds useful. :smile:

**Comment by justinclift** [comment]
@schdub wrote code to make this happen, and it's merged into our main code base a few minutes ago. :smile:

In my quick testing here, it seems to work well. :grin: 

@JC3 Would you be ok to try it out and confirm it's working the way you want?

I'm not sure which OS you're using, but if it's Windows or MacOS then tomorrow's "nightly build" will include it.  (download locations for our nightly builds are on the front page of our repo)

**Comment by justinclift** [comment]
@JC3 Do you have time to try our latest nightly build? We've [updated the code](https://github.com/sqlitebrowser/sqlitebrowser/pull/260) we use for the Execute SQL tab, and it now supports Tab for multi-line indent (plus more).

**Comment by justinclift** [comment]
This is definitely fixed now in the new 3.6.0 release. :smile:
