### ISSUE TITLE
Filter results

### ISSUE THREAD

**Issue by Biz7662** [sqlitebrowser/sqlitebrowser#2551]
I'm trying to ask DB browser to calculate average weight and print me just the results with the avg bigger ( smaller is the same 'cause is just a training) than a number, 42.67 for example. 
![Schermata 2021-01-23 alle 00 50 22](https://user-images.githubusercontent.com/73756170/105561075-16e98b00-5d16-11eb-9ee8-2e316eb9d6be.png)
![Schermata 2021-01-23 alle 00 59 19](https://user-images.githubusercontent.com/73756170/105561137-3c769480-5d16-11eb-94af-9633e206b91f.png)

As u can see when I try with HAVING and a WHERE functions but both gives me problem. With HAVING it doesn't print nothing and with WHERE gives me an error.

Any idea ?

Thank you

Antonio

-----------------------

**Comment by chrisjlocke** [comment]
The average is a final result - you can't have an average for every record.  The where is a criteria for every record.  You can't (in a similar vein) add up all the records to get a total of 90, and ask DB4S to only pull out the records that add up to 90.  
Remove the AVG criteria from the WHERE statement.
If you remove the HAVING criteria from your first result, whats the answer?
Again, the average is a result - you can't ask for an average higher than a number.

If I have rows 1, 2, and 3:

![image](https://user-images.githubusercontent.com/7872218/105563893-b2c7c680-5d17-11eb-8c01-32790bd06734.png)

The average is 2.  I can ask DB4S for an average of the rows where field1 <3 or field1 is >1 or field1 is 2 or field1 isn't 2 ... but I can't ask DB4S for an average of 1.

**Comment by Biz7662** [comment]
Absolutely clear, thank you !
I've done in this two ways:
![Schermata 2021-01-23 alle 10 21 06](https://user-images.githubusercontent.com/73756170/105574419-b6ce0580-5d64-11eb-857f-886ca357381a.png)

I asked to calculate AVG weight **for each Species of Rodents** and also I asked the values (of each Specie ) bigger than a number (21 for example) or  another value. That value in the second request is the Subquery for the AVG **of all the Rodent**.
It's my explanation true ?

**Comment by chrisjlocke** [comment]
I understand the first one, although the 'from' statement is a little different to what I'm used to - would have expected a left join there, rather than putting it in the where.  The where would be your taxa='Rodent', which you're sub-querying - creating the from as you've done mashes all the records together, which isn't wholly accurate - if you have table1 as three rows - 1,2 and 3, it creates six rows - 1,1, 1,2, 1,3, 2,1, etc.

![image](https://user-images.githubusercontent.com/7872218/105574986-11b12e00-5d60-11eb-8d6f-043536a4ddf8.png)

Create a left join, joining on the species_id in both tables.  This creates just the records you need.
Is it a public database?  If you can send it to me, I can have the same data as you and work with you.

**Comment by Biz7662** [comment]
Thank you Chris I understand but I've also to meditate about this.. anyway the database I'm working it's not public, I received it from my professor

**Comment by chrisjlocke** [comment]
OK, no problem.
If you've tableA, and tableB, and field1 in tableA links to field2 in tableB (which I assume you're familiar with), then you use

select *
from tableA
left join tableB on tableA.field1=tableB.field2
where tableA.field6='something'

See also: https://www.w3schools.com/sql/sql_join_left.asp

If you need a more specific example, please yell.
This creates a join on only whats needed - what you're doing is creating a link between the tables whether there is a link there or not.  😃

**Comment by chrisjlocke** [comment]
All the rest of your query is sound - you're doing the right thing and you should get the results you need.
Again, while your data is not public, I can replicate some of the schema and put in a couple of test records to show you examples.

**Comment by Biz7662** [comment]
Ok I can share another one that is public,  where I can send you ?

**Comment by chrisjlocke** [comment]
https://dbhub.io - the home of sharing databases!!  😄 (written by the guys who maintain DB4S....)

**Comment by Biz7662** [comment]
Super ! 
(:

**Comment by Biz7662** [comment]
https://db4s.dbhub.io:5550/Biz7662/Big_air.db?commit=0102844c43b3d269e97a3014e42822307079af82fea0834eddec643f427d9b59&branch=master

Maybe from this link u can open it ..

**Comment by chrisjlocke** [comment]
Did you get that link directly from dbhub.io?  Intestesting.  I'll tag @justinclift (but I know he's away and uncooking his brain at the moment) but for me, that link doesn't work.  The link that does is https://dbhub.io/Biz7662/Big_air.db?commit=0102844c43b3d269e97a3014e42822307079af82fea0834eddec643f427d9b59&branch=master (so no db4s prefix, and no port...)
But yes - can see that database. 👍

**Comment by justinclift** [comment]
At a rough guess, without looking closely, that'll be a link from inside DB4S somewhere?  "db4s.dbhub.io:5550" links are used internally by DB4S itself. :smile:

**Comment by chrisjlocke** [comment]
Yes, think its from the 'clone database' button.

![image](https://user-images.githubusercontent.com/7872218/105613530-05a68a00-5dbb-11eb-8687-13ca759b6ac9.png)

However, trying to open that link just makes my browser fart.

![image](https://user-images.githubusercontent.com/7872218/105613555-2373ef00-5dbb-11eb-88d2-a9706086d68f.png)

With a big red, 'not secure' in the address bar.  Removing the guff (which must be important guff...) makes it work. 😁😊

**Comment by justinclift** [comment]
Good question.  Not remembering the answer off hand... @MKleusberg added the button though, so hand balling... :smile:

**Comment by MKleusberg** [comment]
Ah yes, I added that button a while ago. The intention was to offer a way to skip the part where you scroll through the list of all remote databases in DB4S and instead just clone the database you discovered on the website. You can click this button in DB4S and paste the link in there:
![image](https://user-images.githubusercontent.com/3153504/105626134-4db2c480-5e2e-11eb-8383-ffdbe6481646.png)

**Comment by Biz7662** [comment]
Yes @chrisjlocke I've done exactly in this way.. and moreover @justinclift in "db4s.dbhub.io:5550" the 5550 maybe is the port on my computer that is used  or something similar ?

**Comment by chrisjlocke** [comment]
> Ah yes, I added that button a while ago. 

Excellent, ta.  I'm going to do some dbhub.io tutorials this week, so will remember this bit! 😆 😄 

> maybe is the port on my computer that is used or something similar ?

No, its the port used for the dbhub.io server, and while my browser is more strict and secure, DB4S is a bit more lax, so that link should work fine.  I've not got the remote part set up on this current PC so wasn't sure how that worked, but will check it out later.  Either way, I've got your database up and running. 😺

**Comment by Biz7662** [comment]
![Schermata 2021-01-24 alle 17 56 11](https://user-images.githubusercontent.com/73756170/105637381-90e05800-5e6d-11eb-8011-214b9158c51b.png)

Hi all, on another table (x_segnalazioni) I've 3 column: id_compilator, datacsort and id_segnalazione.
All It's ok but even if I used 'DESC' results aren't on decrescent order 

/:

**Comment by chrisjlocke** [comment]
I think 'num_segn_ might be zero when it encounters that in that part, so use 'count(x_segnalazioni.id_segnalazione)' instead...

**Comment by chrisjlocke** [comment]
So using your big_air database...

![image](https://user-images.githubusercontent.com/7872218/105638090-c767a400-5e68-11eb-9631-04491241a3ba.png)

But instead...

![image](https://user-images.githubusercontent.com/7872218/105638103-d8181a00-5e68-11eb-96ae-e2fe6fbf43f8.png)

**Comment by Biz7662** [comment]
Wow ! I hadn't thought before but the meaning of this is that if I use the quotes ( '     ' ) he understand It as a value and not a column, that's right ?

**Comment by chrisjlocke** [comment]
That's correct. Slightly more advanced than that as there are two types of quotes - single quotes ' and double quotes "
If you use single quotes, it's treated as text.
If you use double quotes, it's treated as a column name.

So if you'd have used **order by "cc"** then it would have ordered by column cc (same as using no quotes).  
Some people (if they're used to programming) get confused and think double quotes is treated as text, as that's what most programming languages use.

**Comment by Biz7662** [comment]
Hi all, I've a table with a list of object related with a data (YYYY-MM-DD), I want to extract a number of object in function of the season..
I thought the best way is to calculate the cumulative number on a fixed interval of time and maybe could be useful add another table and foreign/primary key related to the date.. but actually I'm still thinking about..
Any idea of code or data structure for solve this ?

**Comment by chrisjlocke** [comment]
I assume (don't know how accurate you're wanting) but the seasons are via fixed dates?  I'd add another column (you could do it calculated, but would be better nailing it into the database) and work out the season based on the date.  So Spring would be 20 Mar to 21 Jun, Summer would be 21 Jun to 22 Sep, etc.  Ideally, the season would be an integer - 1,2,3,4, rather than textual ("Summer", etc) so you may need another table to hold these sorts of 'variables' or 'lookups'.

**Comment by chrisjlocke** [comment]
I'll close this issue as the original issue has been resolved, but feel free to continue to comment if you need further SQL help. 😃
