### ISSUE TITLE
error checking foreign keys

### ISSUE THREAD

**Issue by lopi157** [sqlitebrowser/sqlitebrowser#2553]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Closing as no information given.
Feel free to comment on the actual issue and we can look into it further.
