### ISSUE TITLE
icons are twice too small on 4K monitor

### ISSUE THREAD

**Issue by mateusz-lacki** [sqlitebrowser/sqlitebrowser#2555]
Details for the issue
--------------------

#### What did you do?
I have just run the application. Ubuntu 20.04.  4K monitor with 175% fractional scaling set.

#### What did you expect to see?
I expected to show window with icons matching the size of the text captions, both consistent with sizes of other UI elements

#### What did you see instead?
I saw text portion of window being sized correctly, but icons are tiny and seem to be fixed pixel size.
Also text is larger in "About" window. Its size seems fixed as well and now larger text in terms of pixel is longer than the size of the window would allow.

![zzz](https://user-images.githubusercontent.com/17043732/105827768-af0b9c80-5fc2-11eb-8f44-9ad73a2298f2.png)
![zzz2](https://user-images.githubusercontent.com/17043732/105827893-d06c8880-5fc2-11eb-9efa-399793171bb3.png)

Version 3.11.2
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.5

**Comment by chrisjlocke** [comment]
Aah, 3.11.2 is at least two main revisions behind - we're on 3.12.1 now.
Appreciate you're on Linux - think there is a newer version for you to download, or you can build it yourself?
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser
(see here: https://sqlitebrowser.org/dl/)

**Comment by chrisjlocke** [comment]
The newer version (and the nightlies) have better high resolution support, and more granular settings for font sizes.

**Comment by mateusz-lacki** [comment]
Ok, thanks for letting me know. I think that 3.11.2 is the version packaged in ubuntu 20.04 repos. 
I will update. Thanks.

**Comment by chrisjlocke** [comment]
@mateusz-lacki - did you try the latest version?  Wondered if this issue was resolved...

**Comment by chrisjlocke** [comment]
Closing due to lack of response.  @mateusz-lacki - feel free to comment further and we can re-open if necessary.

**Comment by mateusz-lacki** [comment]
Hi,
I apologize for lack of reply. Somehow the email went into junk.  I have tried version 3.12.0 from snap store. The issue is still there.

I have actually solved my issues with icons by adding QT_AUTO_SCREEN_SCALE_FACTOR=2 to /etc/environment.

Best,
Mateusz

**Comment by chrisjlocke** [comment]
Interesting.  3.12.0 is still one revision behind.
Glad you resolved this via other means.

**Comment by mateusz-lacki** [comment]
Yes, but still the window looks bad (everything is twice larger, but icons are still too small and blurry, and the about window is still not showing properly, but it is more readable). If that is fixed in the newest version, then great. I have no easy way of testing that.
Between my original message and the latest replies, I had problems with other software as well, it seems fixes to other software have contributed to the way how sqlitebrowser works. Now my system has a few non-standard settings in it, and frankly I am unable to cooperate with providing useful feedback.

Best,
Mateusz
