### ISSUE TITLE
Missing font message

### ISSUE THREAD

**Issue by Stewag25** [sqlitebrowser/sqlitebrowser#2556]
When I open DB browser for SQLite I get the attached error message.
The font does indeed not exist on my Win10 Pro PC and it sounds rather unusal.
?

Best regards
Steffen

**Comment by justinclift** [comment]
Hmmm, when you say "attached error message" there's nothing being shown. :wink:

Did you forget to attach it? :grin:

**Comment by chrisjlocke** [comment]
Also, what version of DB4S did you install?  Where did you get it from?  Was it installed, or run from an unzipped ZIP file?  Have you had DB4S installed on your machine previously?  Does DB4S continue after the 'missing font' error, albeit everything on screen looks wonky?  Does this error keep appearing, or did you only get it once?

**Comment by Stewag25** [comment]
Hi Chris,

I installed the 32Bit Win versions freshly from your website 
(https://sqlitebrowser.org/) today.
Yes, there has been a previous version, which I deinstalled.

The error does not appear on my notebook.

By the way: It's a great tool!

Best regards,
Steffen




------ Originalnachricht ------
Von: "Chris Locke" <notifications@github.com>
An: "sqlitebrowser/sqlitebrowser" <sqlitebrowser@noreply.github.com>
Cc: "Stewag25" <stewagner@freenet.de>; "Author" 
<author@noreply.github.com>
Gesendet: 26.01.2021 14:57:36
Betreff: Re: [sqlitebrowser/sqlitebrowser] Missing font message (#2556)

**Comment by chrisjlocke** [comment]
OK, so out of interest, what font is it moaning about?
If you click 'Edit' and 'Preferences', then select the 'Data Browser' tab, what do you have in the font box?

![image](https://user-images.githubusercontent.com/7872218/105867102-97e1a480-5fec-11eb-8b93-6cea1c41d0e7.png)

If you click the 'SQL' tab, again, what font do you have selected?

![image](https://user-images.githubusercontent.com/7872218/105867287-d2e3d800-5fec-11eb-906e-2c25c3cfc76a.png)

If you set them both to 'Segoe UI' (which is a nicer font than Arial) and click 'Save', and restart DB4S, does the error go away?

**Comment by Stewag25** [comment]
... sorry, this is the error message:


I set data Browser to Segoe UI but it seems on coming

BR
Steffen

------ Originalnachricht ------
Von: "Chris Locke" <notifications@github.com>
An: "sqlitebrowser/sqlitebrowser" <sqlitebrowser@noreply.github.com>
Cc: "Stewag25" <stewagner@freenet.de>; "Author" 
<author@noreply.github.com>
Gesendet: 26.01.2021 16:43:01
Betreff: Re: [sqlitebrowser/sqlitebrowser] Missing font message (#2556)

**Comment by Stewag25** [comment]
I just replaced the 32Bit version against the 64Bit one.
Same error!



------ Originalnachricht ------
Von: "Steffen Wagner" <stewagner@freenet.de>
An: "sqlitebrowser/sqlitebrowser" 
<reply@reply.github.com>
Gesendet: 26.01.2021 17:58:09
Betreff: Re[2]: [sqlitebrowser/sqlitebrowser] Missing font message 
(#2556)

**Comment by chrisjlocke** [comment]
> sorry, this is the error message

Unfortunately, as you're replying by email, any attachments don't get included in your message.
Can you paste the image into https://imgur.com and post the link here?  You don't need an account - just click 'New Post' at the top, press Ctrl+V, then right-click the image and 'copy image link', etc...

> but it seems on coming

Then that's very weird.  Not seen this type of error before.  Wonder what font it's moaning about and where from?
Could you try a nightly at all?
https://nightlies.sqlitebrowser.org/latest/

**Comment by Stewag25** [comment]
Hi Chris,

here is the error:
https://imgur.com/a/2D1ItQr



------ Originalnachricht ------
Von: "Chris Locke" <notifications@github.com>
An: "sqlitebrowser/sqlitebrowser" <sqlitebrowser@noreply.github.com>
Cc: "Stewag25" <stewagner@freenet.de>; "Author" 
<author@noreply.github.com>
Gesendet: 26.01.2021 18:43:03
Betreff: Re: [sqlitebrowser/sqlitebrowser] Missing font message (#2556)

**Comment by justinclift** [comment]
Ahhh, `EUDC.TTE`.  That's the second report of that missing font then.  The other report is #2480.

The workaround for the problem - as we're not yet sure of the actual cause - seems to be having a font file there where it asks.  In the original report, the person doing the report created an [initial font glyph](https://github.com/sqlitebrowser/sqlitebrowser/issues/2480#issuecomment-727279569) manually at the path in the error message.

Just copying an existing file file to the same path instead might be an easier way to work around it though (just guessing). :smile:

**Comment by Stewag25** [comment]
... thanks Justin, that helped!

Best regards,
Steffen

------ Originalnachricht ------
Von: "Justin Clift" <notifications@github.com>
An: "sqlitebrowser/sqlitebrowser" <sqlitebrowser@noreply.github.com>
Cc: "Stewag25" <stewagner@freenet.de>; "Author" 
<author@noreply.github.com>
Gesendet: 27.01.2021 01:16:25
Betreff: Re: [sqlitebrowser/sqlitebrowser] Missing font message (#2556)

**Comment by justinclift** [comment]
You're welcome, glad you got it working. :smile:

**Comment by abtxu** [comment]
Folks, I have found THE solution:

>editing  \HKEY_CURRENT_USER\EUDC\1252 (1252 is the code of the latin alphabet) "SystemDefaultEUDCFont" key value to "C:\Windows\Fonts\seguibli.TTF" 

[[PYSIDE-1620] qt.qpa.fonts: Unable to open default EUDC font: "C:\\WINDOWS\\FONTS\\EUDC.TTE" - Qt Bug Tracker](https://bugreports.qt.io/browse/PYSIDE-1620)

In fact, you can change "C:\Windows\Fonts\seguibli.TTF"  to "C:\Windows\Fonts\WhateverFontThatEndsWith.TTF". For me, it is calibri.ttf.

**Comment by chrisjlocke** [comment]
Well done @abtxu - handy to know!
