### ISSUE TITLE
tp1

### ISSUE THREAD

**Issue by f5599** [sqlitebrowser/sqlitebrowser#2557]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
tp1?  Wassis?
I'll close this as it seems to be opened in error, but feel free to comment further if you still need assistance...
