### ISSUE TITLE
can't get sqlcipher_version

### ISSUE THREAD

**Issue by yzhgu** [sqlitebrowser/sqlitebrowser#2562]
What is your question
-----------------------
I have a db encrypted by wxsqlite3 using SQLCipher4 method. It can be opened successfully with the [official nightly builds](https://nightlies.sqlitebrowser.org/latest/). However, I can not open it with the exe file build by myself (win10 + vs2019, and of cource, set ENABLE_SQLCIPHER). If I debug into the source code, in function getSqliteVersion(), sqlite3_step(stmt) returns 101 and therefor, sqlcipher is not set.
Did I miss something compraed to official nightly builds?

**Comment by chrisjlocke** [comment]
Which version of SQLite did you use?  Did you include the SQLCipher library?
"returns 101" - why 101?  Where is it getting 101 from?

**Comment by yzhgu** [comment]
You are right, SQLCipher lib is missing. Thx a lot
