### ISSUE TITLE
Error- Could not open database file. Database disk image is malformed

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [sqlitebrowser/sqlitebrowser#2564]
Hi everyone,  I was going to open  SQLite  (size > 200MB) file in the SQLite browser but could not open it, and here is the screenshot of the error message. How can  I open huge files in  SQLite browser?
Thanks

![error](https://user-images.githubusercontent.com/46449085/106378014-7fa2c880-63e4-11eb-95c9-36521f6bf3de.jpg)

**Comment by chrisjlocke** [comment]
That's basically saying that while DB4S can recognise its a database file, it's not a *valid* database - it's internally broken.  Usually occurs if it was damaged while it was being written to.

If you click on 'File' and 'Export' then 'Export database to SQL file' it'll save what it can.

![image](https://user-images.githubusercontent.com/7872218/106378148-21e98e80-639a-11eb-9f99-6c7922d1b520.png)

However, the database should not be relied upon - parts will be missing.  It may be just an index or part of, in which case it can recreate this, or it could be a huge chunk of data.  Do not use this database again, as it cannot be relied upon - you'll need to revert to a backup.

If DB4S can't actually open the file (sometimes DB4S can open it, but running some queries produces the above error) then you'll need the SQLite command tool.
Run it and enter:
`    .mode insert`
`    .output dump_all.sql`
`    .dump`
`    .exit`

That'll get you the same export as above - the 'non-damaged' parts.  You can import that into a new database using 'File', 'Import' and 'Import database from SQL file'

![image](https://user-images.githubusercontent.com/7872218/106378266-45610900-639b-11eb-8442-16b9a1498dd2.png)

**Comment by chrisjlocke** [comment]
For the avoidance of doubt, this is nothing to do with DB4S, and that it can't open a 'huge' database - SQLite databases can happily be GB's in size with tables containing millions of rows - it's what it's designed for.

**Comment by justinclift** [comment]
@ilyosbekibrohimov Out of curiosity, did you get the database file from an Android tablet or something?  Asking because that's known to sometimes corrupt database files when copying them off.

If that's the case, you might have better luck just trying to copy the file from the tablet again first.  It does sound like the one you have at the moment is corrupted. :frowning:

**Comment by ilyosbekibrohimov** [comment]
I got  SQLite files from an Android device. Thank you, everyone, I have solved that problem. Initially,  I was thinking that the SQLite browser can't open SQLite files because of their huge size,  but as you guys said  I was wrong: Those  SQLite files were corrupted. 
I just run  'sqlite3 corrupted_file.db ".recover" | sqlite3 new_file.db' command to recover corrupted SQLite  file  and  fortunately  it worked.
Thank you for everyone who helped me to solve that issue:)

**Comment by chrisjlocke** [comment]
Glad you got it sorted.  Again, be aware that the 'recover' only recovers what it can - and to be fair, its usually only the indexes that are out of bonk, so no great loss - they're easily recreated.  However, sometimes you can lose data, and if that data was a lookup table, potentially it could render the whole database unusable.  
Unless you know that database is good, don't rely on it - don't treat it as a 'production' database.

I'll add this to the wiki as its a useful point of knowledge.
