### ISSUE TITLE
Extension names not saved in Preferences::saveSettings

### ISSUE THREAD

**Issue by rjmoses** [sqlitebrowser/sqlitebrowser#2565]
Problem: When editing the user preferences to have one or more user defined extensions loaded for all databases, the extension name is not written to the [extensions] section of the sqlitebrowser.conf file when trying to save permanently.  

Instead of writing "list=extensionnames", saveSettings writes "list=@Invalid()"

The following original statements fail to build "extList" because findItems does not return any items.

    QStringList extList;
    for(const QListWidgetItem* item : ui->listExtensions->findItems(QString("*"), Qt::MatchWrap | Qt::MatchWildcard))
        extList.append(item->text());

Corrected code that works:

    for(int i = 0; i < ui->listExtensions->count(); i++) {
        QListWidgetItem* item = ui->listExtensions->item(i);
        extList.append(item->text());
    }

To recreate problem:

1) Edit-->Preferences-->Extensions-->Add Extension
2) Select new extensions to be loaded for all databases
3) Save

Problem found in:

sqlitebrowser version 3.11.99
sqlite version 3.34.0
Qt version 5.15.2
OS: Linux Mint 20.1

**Comment by Yuhsak** [comment]
I'm facing same issue. It would be so nice if it'll be fixed.

macos 10.15.7
sqlitebrowser version 3.12.1
Qt version 5.15.1

**Comment by chrisjlocke** [comment]
Anyone is welcome to raise a PR with the corrected code...

**Comment by mgrojo** [comment]
This should be fixed by  #2467, so I'll close it as redundant. It will be released in 3.12.2, but if you can install the [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) to have a testing version where it is fixed.
