### ISSUE TITLE
'Continuous build' is marked as 'Latest Release' and not as 'Pre-release' in GitHub

### ISSUE THREAD

**Issue by core-code** [sqlitebrowser/sqlitebrowser#2566]
'Continuous build' is marked as 'Latest Release' and not as 'Pre-release' in GitHub

**Comment by justinclift** [comment]
Yeah, it's created automatically as part of a part of a script.  There doesn't seem to be a way to fix it, so it's marked as "Pre-release" either. :frowning:

**Comment by core-code** [comment]
sorry don't know how to do it, but pretty sure there is some way as the automated builds of other projects are usually tagged right.

**Comment by chrisjlocke** [comment]
Looks like it just needs a `prerelease: true` tag.

**Comment by mgrojo** [comment]
This is fixed now. It was caused by a change in the upload.sh script that we use. It requires now an environment variable to declare the build as a pre-release.

**Comment by justinclift** [comment]
Well done @mgrojo, that's awesome!

Thanks for reporting the problem @core-code.  It wouldn't have been fixed otherwise. :smile:

**Comment by core-code** [comment]
thanks for solving this :)
