### ISSUE TITLE
Message "The database is currently busy" displayed when opening file from project

### ISSUE THREAD

**Issue by rjmoses** [sqlitebrowser/sqlitebrowser#2567]
When opening a database from a project and the Browse Data tab is the active tab, the message box:

 "The database is currently busy: reading rows
   Do you want to continue"

is displayed.

1) The loadProject function calls the fileOpen function to open the database, then continues processing.  
2) fileOpen opens the database then tests if the current widget is the browser tab.  If so, it calls populateTable, continues processing and returns to loadProject.
3) loadProject continues processing, then calls populateTable just before returning.  
4) The call to populateTable from loadProject conflicts with the call from fileOpen causing waitForDbRelease to display the message that the db is busy.

The correction for this problem is to change fileOpen from
 
                if(ui->mainTab->currentWidget() == ui->browser) 
                    populateTable();

to include a check if it had been called from loadProject before calling populateTable

                if( (ui->mainTab->currentWidget() == ui->browser)  && !openFromProject )
                    populateTable();

Problem found in:

sqlitebrowser version 3.11.99, 3.12.1
sqlite version 3.34.0
Qt version 5.15.2
OS: Linux Mint 20.1

Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by sky5walk** [comment]
Yes, I see similar messages when opening a sqbpro and a network attached db.
In most cases, just hit ok and continue.

**Comment by chrisjlocke** [comment]
> to include a check if it had been called from loadProject before calling populateTable

What implications does this bring?  If you open a project file with the 'browse data' tab open, does it display old data (even from an old database?) or just doesn't refresh with new data?

**Comment by rjmoses** [comment]
I have tip-toed through the code just enough to understand what was causing the message to be displayed.  

Under differing circumstances, I have seen that the table is sometimes displayed with each cell "loading" depending on timing of my response and the response I selected.  This often depended on the table size.

Looking at the code, I'm guessing that there might be a conflict with the project pragmas which are set upon return from fileOpen but possible after the table is loaded.  I can imagine that it might be a hit or miss depending on timing.

From what I see, the table should only be populated in either fileOpen or loadProject--not both.

**Comment by justinclift** [comment]
Hmmm, wonder if the recent changes by @MKleusberg to fix the "Stop button still being shown after query has finished" problem might have fixed this too?

@rjmoses As you're on Linux and look comfortable with compiling code, is there any chance you could see if our latest development stuff (`master` branch) still does this for you?

**Comment by chrisjlocke** [comment]
Just a little nod that @MKleusberg's fixes for that 'stop button still being shown' are still being fixed, and the latest nightly is fubar in that regard.

**Comment by justinclift** [comment]
@chrisjlocke Ahhh, I didn't realise.

**Comment by chrisjlocke** [comment]
Hmm.  Can't find my comment now ... grr!  Maybe that's why it hasn't been fixed yet! 😁😂

**Comment by rjmoses** [comment]
I'll give the nightly build a shot over the next few days.

**Comment by rjmoses** [comment]
Checked nightly build (3.12.99) for this problem.  Problem exists.  Changed line 564 from:

                refreshTableBrowsers(true);

to:
                if(!openFromProject) {
                    refreshTableBrowsers(true);  
                }

Problem corrected.   I am not sure about other ramifications, but it seems that refreshTableBrowsers() should only be called once after the project is loaded.

**Comment by justinclift** [comment]
@MKleusberg ^^^ :smile:

**Comment by chrisjlocke** [comment]
Downgrading from what version?  On what OS?
Upgrading to the latest version would be preferable...

**Comment by ReMiOS** [comment]
> 

I start the DB Browser with command line option "-t" to open a table 
After starting this message appears:
```
The database is currently busy: reading rows
Do you want to abort that other operation ?

```

I'm having this issue on Windows 10 and Windows 11 
The issue appears when DB file is on local drive or on a network share

I agree it would be preferable to use the latest version, however on both v3.12.1 and v3.12.2 i encounter this issue, 
while on version v3.12.0 i do not get this warning.

**Comment by chrisjlocke** [comment]
Can understand that's annoying.  Introduced around that time was multi-threading, so there is an issue where DB4S starts, grabs something like the number of rows in the table, and is hitting this issue.
If you just say 'No' it should just continue on its way.  I can assure you the benefits (and fewerbugs) in the nightly or 3.12.2 faaaar outweigh the benefit of using 3.12.0.  Just look through the release notes.
I would argue (feebly...) that it may be easier not to use the -f option.... ;)

**Comment by sandman7920** [comment]
@mgrojo it should be done.
I am not sure it works on all platforms.

**Comment by mgrojo** [comment]
Great! It is no longer reproduce with the project where I had this problem in previous versions.
