### ISSUE TITLE
Zip or 7Z portable release

### ISSUE THREAD

**Issue by jonorozcoc** [sqlitebrowser/sqlitebrowser#257]
The PortableApps Format is ugly portable specification, need much settings, A single zip with all contents are more useful. Note: I'm colombian, my english is bad.

**Comment by justinclift** [comment]
Interesting idea.  It should not be too hard. :smile:

**Comment by justinclift** [comment]
@rp- Any idea if creating a zip from the contents of an installed version will work ok? (I can prob try it tomorrow, I just need sleep atm)

**Comment by rp-** [comment]
yes should work

**Comment by justinclift** [comment]
Cool, I'll make .zip files tonight for the windows binaries.

**Comment by jonorozcoc** [comment]
I recomend see the PortableApps Config File for details of settings.

**Comment by justinclift** [comment]
@jonorozcoc Would you be willing to create the .zip files instead?

**Comment by jonorozcoc** [comment]
Yes, i try

**Comment by jonorozcoc** [comment]
I will use the latest release.

**Comment by jonorozcoc** [comment]
I made the file with all the requirements (VC2013), as it can send?

**Comment by justinclift** [comment]
Is it small enough to email?  If so, try emailing it to me at justin@postgresql.org.  I'll try it out. :smile:

Oh, we should not include VC2013 yet.  We need to understand the license terms for that bit first. :wink:

**Comment by justinclift** [comment]
@jonorozcoc It's taken us a few years to get this done, but we're now providing .zip versions of both our releases and nightly builds (starting from yesterday). :smile:

* https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.0-beta1
* https://nightlies.sqlitebrowser.org/latest/

If you're still interested in these, please give them a go and let us know if there's any strangeness with them.  In theory there shouldn't be, but providing .zips is brand new for us. :grinning:
