### ISSUE TITLE
HiDPI monitor suggestions for testing?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2570]
After letting our Patreon funds build up for a while, we now have a shade over US$500 available for putting towards a HiDPI monitor for @MKleusberg.  That should allow for investigating and fixing HiDPI related problems (eg scaling issues) that crop up. :smile:

So, the next question is... does anyone have suggestions on a reasonable HiDPI monitor to choose?

@MKleusberg Any preference(s) size wise, and what sort of graphics card do you have that would be driving it?

**Comment by scottfurry** [comment]
https://www.lg.com/us/4k-monitors

**Comment by justinclift** [comment]
@scottfurry Thanks!  Am also not 100% sure what an appropriate screen size is, as a 4K display that's "too big" will just be a large standard DPI thing.

Looking at the [Wikipedia](https://en.wikipedia.org/wiki/Pixel_density#Named_pixel_densities) page about this, it seems like "HiDPI" means about "213–240 dots per inch".  However, that doesn't seem achievable with even 27" screens (on the smaller 4K side) when running at 4K:

* 27 inch screen with a 2560×1440 resolution → 108.8 PPI
* 27 inch screen with a 3840×2160 resolution → 163 PPI
* 32 inch screen with a 3840×2160 resolution → 138 PPI

So, it looks like "HiDPI" for monitors is likely somewhat of a smaller DPI than that for phones and tablets.

* From that LG page, they seem to have a few that are probably "HiDPI" for our purposes (maybe ~27" or so?).
* Looking around at reviews online, the [ASUS VG289Q](https://www.displayninja.com/best-gaming-monitor/#ASUS_VG289Q) one seems ok too and is in the [right price range](https://www.scan.co.uk/products/28-asus-tuf-vg289q-4k-monitor-ips-3440x2160-60hz-5ms-freesync-hdr10-10001-350cd-m-hdmi-dp).

More research and reading needed... :smile:

**Comment by sandman7920** [comment]
@justinclift in the Office we are using Dell P2415Q, not the best monitor but has a high pixel density (185 PPI, 3840×2160, 23.8")

Connectivity
DisplayPort in
Mini DisplayPort
DisplayPort out
HDMI (MHL)
Speaker-line out
4 x USB 3.0 downstream
1 x USB upstream

Works great on Windows, Linux, and Mac OS

**Comment by justinclift** [comment]
Thanks @sandman7920, that's good info.  Looking around for places to buy those, Ebay seems like they have a few, though it's an older model now.  Still, it's a decent possibility. :smile:

**Comment by justinclift** [comment]
Looking at the LG monitors @scottfurry linked to above, there's only a single ~23" 4K one (eg high pixel density).  That's the [LG 24UD58-B](https://www.lg.com/us/monitors/lg-24UD58-B-4k-uhd-led-monitor).

Reviews of it are generally pretty positive, and price wise, it's also well within budget (useful).

Seems like it'd be a good choice.  That Dell P2415Q seems to be very hard to find these days, except 2nd hand on Ebay which might not be the best choice for this. :wink:

**Comment by sandman7920** [comment]
@justinclift LG 24UD58-B look great for the price, but LG sale those only from the US site, Isn't MKleusberg live in Germany.

Dell P2415Q can be ordered from emag .ro .bg .hu, but don't know if they ship internationally, here in Bulgaria Emag is maybe the number one e-shop place (great job Romania).

**Comment by justinclift** [comment]
Gah.  It turns out the LG link above actually excludes some 4K monitors.  No idea why.

A better link is this one: https://www.lg.com/us/monitors

That shows two potential ~23" 4K monitors:

* [24UD58-B](https://www.lg.com/us/monitors/lg-24UD58-B-4k-uhd-led-monitor) ← looks decent
* [24MD4KL-B](https://www.lg.com/us/monitors/lg-24MD4KL-B-4k-uhd-led-monitor) ← a better monitor, but more expensive.  We could just wait a bit and save up further though...

@sandman7920 Yeah.  My initial though for buying the thing is to ask [Scan](https://www.scan.co.uk) if they can stock it.  I have an account with them from when I lived in the UK.  Hopefully they can, and it wouldn't be too hard to ship to Germany.

**Comment by MKleusberg** [comment]
Thank you all for your suggestions! :smile: That 24UD58-B looks good to me size-wise (I'm currently using a 22" monitor, so it'd be a bit larger but as I have a large desk that's a benefit) and price-wise (not looking forward to using all of those US$500 :wink:). And it's using HDMI which my current graphics card support. That said, I'm planning on buying a new one anyway. So a monitor which only supports DP should be ok too.

I couldn't find any information in international shipping on scan.co.uk. In Germany people just tend to use Amazon these days. For computer related stuff mindfactory.de is popular too here but they have no English website. So that would be more difficult to use for Justin.

**Comment by justinclift** [comment]
K, sounds like the LG 24UD58-B is the first choice.  I'll ping the Scan people, and see if they can order it in + ship it to Germany.  Hopefully it's that easy... :smile:

**Comment by justinclift** [comment]
Chatting with Scan customer service staff today, they're not doing any international deliveries at all for now due to the general mess that Brexit has left things in.  They used to, and intend to again, it's just... "not right now". :wink:

Things might be clearer in a few weeks for them.

In the meantime, we'll probably need to look at alternative ways to get this done.  I **could** order one from the US via Ebay, and try to get it delivered to Germany.  That's likely to mean some amount of dumb customs fees though, over and above double posting 1/2 way around the world.

Hmmm, there has to be a better way...

**Comment by chrisjlocke** [comment]
How would you (Justin) pay for it?  Could you not buy an Amazon voucher for Martin to use, if Amazon has stock of the item... or Martin buys on mindfactory.de and receives an Amazon voucher (or PayPal or reimbursed some other means) ...

**Comment by justinclift** [comment]
Amazon voucher(s) might be a decent way to do it.  We just have to find some place that stocks it.  It might be better if Martin emails the Mindfactory place to ask if they can stock it...?

> Dell P2415Q can be ordered from emag .ro .bg .hu

@sandman7920 Interestingly, it only seems to show up on the emag .bg and .hu sites, not the .ro one.  Guess they're not sharing the same backend catalog, or they have regional info about availability.  That being said, if you're ok with doing the ordering and getting it shipped to Martin, then I'm ok with reimbursing you for the entire cost (and a reasonable handling fee :wink:).  If that sounds potentially do-able, maybe email me (justin@postgresql.org) so we can figure out how to get money from us to you? :smile:

**Comment by sandman7920** [comment]
@justinclift One of the Bulgarian PC components sellers has a big discount on Dell P2415Q, around 270 Euro and I ordered it.
If everything is OK it should be here next week.

**Comment by justinclift** [comment]
@sandman7920 Heh Heh Heh.  We'd better figure out how to get money to you then.  Can do PayPal, direct bank transfer, etc, if that helps.

As it's "financial stuff" it's probably safer to communicate about it not-in-public though (eg via email?).

**Comment by justinclift** [comment]
Status update.  With @sandman7920's extensive efforts, @MKleusberg now has a proper HiDPI monitor (Dell P2415Q) for testing stuff. :grin: 

We should probably write up a blog post about it, and probably also post something on our Patreon so people know their money is being put to useful ends. :smile:

**Comment by chrisjlocke** [comment]
"Now we need to just get enough money for a power cord for it."

**Comment by justinclift** [comment]
It's not an Apple monitor. :wink:

On that note, when in an Australian Apple store a few years ago I asked if they had cords for the Mac Mini.  The answer was No, but they'd happily sell me a new Mac Mini if I really, really needed the cord.

And yes, the sales person was being a smartarse, not super serious.  Though of course if I'd said "yeah" he'd have sold us a new Mac Mini. :grin:

**Comment by justinclift** [comment]
A [blog entry on our website](https://sqlitebrowser.org/blog/hidpi-monitor-purchased-thanks-to-patreon-supporters/) and a [post on our Patreon](https://www.patreon.com/posts/48394255) have been created for this. :smile:

**Comment by MKleusberg** [comment]
Another big thank you from my side to everybody involved in this! :smiley: I'll do my best to make some good use of the monitor and tackle the HiDPI issues we have.
