### ISSUE TITLE
Very slow insert query when large number of queries approximately 100000 are add in the Execute SQL window

### ISSUE THREAD

**Issue by ganeshkamath89** [sqlitebrowser/sqlitebrowser#2572]
I added 100000 insert statements in the "Execute SQL" window and hit the run button. It displayed in the result for each query that it took about 65 ms - 85 ms. But output for each query was shown after little more than 1 second fore each query. So after running the query for 8 hours I have exited the query.

I had entered the first 100 insert statements separately and tested. The queries ran ver quickly, so i had decided to run all my insert statements together. But I think there is some problem in the logic used to execute large number insert queries form the "Execute SQL" window.

I see that there is no problem even if I add 4200 insert queries. The speed is still good enough. But I was expecting the same speed of query execution and output even when query count increased.

Another observation. Sometimes I have observed that as more an more queries complete, it becomes somewhat fast, but I have not measured the timings

I ran it on Windows: 10, Version 1909. Build 18363
DBS version 3.12.1

**Comment by chrisjlocke** [comment]
At least you didn't press the (X) button to cancel the insert process - DB4S doesn't like that.
https://streamable.com/yfvvbd

Sort of replicated your issue.  Did you have multiple 'insert' statements, or an insert statement with multiple 'value' parameters?
I think the delay (seen in my video every 100 iterations) was due to it processing one long line each time - further in I recreated it with one insert on each line.  Yes, as you add more lines, the insert takes longer, as I assume DB4S is processing (or re-reading?) the text to work out which line we've just processed. Or something.
Again, at the end of the video, it shows where pressing the 'abort' button knees DB4S in the goolies.  Oops.  Also weird is the 'error near ble1' that appears.  Guess that's as it's not reading enough text to throw to SQLite.

Thanks for reporting this.

**Comment by justinclift** [comment]
Out of curiosity, did you put the insert statements inside a transaction block?

eg:

```
BEGIN TRANSACTION;

INSERT ...
INSERT ...
INSERT ... (etc)

COMMIT;
```

In theory, doing that should be **much** faster. :smile:

**Comment by chrisjlocke** [comment]
There is already a transaction created for the 'execute sql' tab, so if you add another manually, you get told off:

![image](https://user-images.githubusercontent.com/7872218/106780467-f091ec80-663f-11eb-8a66-1006d0689f75.png)

**Comment by chrisjlocke** [comment]
Aah, but it does like 'begin transaction' (which has no effect) - guess that's stripped out the prevent error?

![image](https://user-images.githubusercontent.com/7872218/106780891-5a11fb00-6640-11eb-8d23-9892184d72ac.png)

**Comment by justinclift** [comment]
Ahhhh, completely forgot about that.  Oops. :wink:

**Comment by chrisjlocke** [comment]
Speed difference of inserting 400,000 lines.

https://user-images.githubusercontent.com/7872218/106781149-a5c4a480-6640-11eb-822c-8d4b39c48d48.mp4

**Comment by MKleusberg** [comment]
Thank you very much for reporting this, @ganeshkamath89! That's exactly the sort of issue I would like to get rid of :smile:  I hope I could fix this issue. Can you give tomorrow's nightly build (available [here](https://nightlies.sqlitebrowser.org/latest/) another try? It'd be interesting to see how fast that is in your use case.

**Comment by ganeshkamath89** [comment]
Hi @MKleusberg, with the nightly build, i am getting:
![image](https://user-images.githubusercontent.com/2648522/106840479-44471900-66c6-11eb-86ca-ec20cc8236a5.png)

**Comment by justinclift** [comment]
@ganeshkamath89 Oh, it looks like only our Win32 nightly build was created ok.  The Win64 one there is older, from the day before.  If you tested with the Win64 build that was there, it's probably not using that new piece @MKleusberg added

Btw, not sure why the Win64 build is having issues, investigating now...

**Comment by justinclift** [comment]
@ganeshkamath89 There's a new Win64 build for testing, that includes the potential fix, if you're ok to try again: :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by ganeshkamath89** [comment]
I am still getting the same error in this build also:     https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Oh well.  Thanks for trying it @ganeshkamath89. :smile:

**Comment by chrisjlocke** [comment]
> I am still getting the same error

The same error originally reported, or the 'attempt to write a readonly database' error?
If the latter, then did DB4S crash when you last used it?  I had this and it was due to a left over journal file.  Deleting it solved my problem, but obviously it does mean the database is in an inconsistent and unknown state.  Thankfully it was only a test database.
Check if you have any other files with the same filename as the database file (but with -journal appended).

Eg:
![image](https://user-images.githubusercontent.com/7872218/106864679-1fe93d80-66c2-11eb-8f66-74b3e3ca36b7.png)

**Comment by ganeshkamath89** [comment]
Hi @chrisjlocke , Yes i am getting the 'attempt to write to readonly database' error itself.

I am able to open the Database as I did before with the 3.12.1 released version, before as well as after trying the two nightly builds. I don't have any journal files.

**Comment by chrisjlocke** [comment]
OK, so v3.12.1 can open the database OK, and you don't get an error, but with the nightly, you can open the database, but can't modify it or run an insert, etc? I assume when you're opening this database you don't have another copy of DB4S open?
Just as a test, with the nightly version, can you create a new database (eg, store it on your desktop), create a new table with just one field, and all is good?

**Comment by ganeshkamath89** [comment]
Can you check if you can install this tool from: https://developer.amd.com/tools-for-dmtf-dash/
Application name: AMC-setup-6.0.0.861-AMD.exe

It is a Manageability tool. 
It writes to the db: C:\Program Files (x86)\AMD Management Console\config\db.dat

It might help you to reproduce the issue I am facing. That's why I am sharing.

**Comment by chrisjlocke** [comment]
That setup doesn't complete for me.

![image](https://user-images.githubusercontent.com/7872218/106908646-6311d380-66f7-11eb-82e5-ab715972f440.png)

You're trying to open db.dat using DB4S?  It might be read-only if the AMD service is using it?  Have you made a copy of that .dat file and tried to open that?

**Comment by ganeshkamath89** [comment]
Yes I have tried with a copy of the db.
I have also tried by stopping the service that accesses the db.

**Comment by ganeshkamath89** [comment]
the application writes installation logs to the location: C:\Users\Administrator\
Can you share the file named AMC_Install.log ?

**Comment by chrisjlocke** [comment]
During install there is no amc_install.log file created.  I checked using 'search everywhere' from Void tools, and there is no amc_install.log on my PC.
Unsure why it's not working with a copy of the db file - that's weird.  However, where is that .db created?  DB4S usually has issues accessing any file in the c:\program files (or the x86 version)* - can you put a copy of the .db on your desktop?

*normal users can't write to files in these directories.

**Comment by ganeshkamath89** [comment]
I also created a new DB. Then I exported tables from my DB as SQL and imported into new db as SQL.
I am able to now run insert queries.
It is still very slow like I had seen before.

**Comment by justinclift** [comment]
Just to ask a possibly dumb question... does that AMD tool check whether there is AMD hardware (cpu, gpu) before it'll install?  Just in case @chrisjlocke is not using AMD hardware. :smile:

**Comment by ganeshkamath89** [comment]
No. It shuld be able run on any Windows system. This tool is used to manage other systems. It does not check the current system's hardware type while installing.

**Comment by ganeshkamath89** [comment]
I am interested in testing further if you have any other builds. Because I need to run large number of queries manually for my test application

**Comment by justinclift** [comment]
@ganeshkamath89 I think we'll need to wait for @MKleusberg to think of other things to try.

Another possibility worth testing for your specific case, is whether passing the commands to SQLite via the command line shell goes faster:

&nbsp; &nbsp; https://sqlite.org/cli.html

In theory, that shouldn't have the slowness of the GUI.  On the other hand, it's less easy to use.  But probably worth trying out. :wink:

**Comment by ganeshkamath89** [comment]
Thank you for sharing this trick. I will be checking back if there is a fix from DB4S. But meanwhile this is a fantastic solution.

**Comment by justinclift** [comment]
No worries.  With the SQLite CLI, definitely wrap things in a transaction block, as it probably won't do it automatically:

```
BEGIN TRANSACTION;

INSERT ...
INSERT ...
INSERT ... (etc)

COMMIT;
```

That'll help it go even faster. :smile:

**Comment by little-brother** [comment]
Use `pragma syncrohous` and `transaction`.
Also if you have triggers or indexes on the target table then you can drop them to make insert faster.
```
pragma synchronous = off;
begin;
// inserts here
commit;
pragma synchronous = on;
```

**Comment by ganeshkamath89** [comment]
I am able to run 127500000 insert queries also via sqlite3.exe, which was just another stress test. Thank you. I have incorporated all the optimizations in pragmas and transactions given in this thread.

**Comment by justinclift** [comment]
How long did it take via the SQLite cli? :smile:

**Comment by MKleusberg** [comment]
@ganeshkamath89 Can you give the latest nightly build another try? I have fixed another problem which slowed down the application when you were executing many queries at the same time.

**Comment by ganeshkamath89** [comment]
Hi @MKleusberg, Can you please share the x86 nightly build windows installer link?

**Comment by MKleusberg** [comment]
Sure! It's going to be available here tomorrow: https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.msi

**Comment by chrisjlocke** [comment]
Just a nod that I'd recommend the .zip file - this needs no installation - simply download, extract and run the .exe file directly.
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

Just a suggestion, but whatever works best for you.  😁

**Comment by chrisjlocke** [comment]
@ganeshkamath89 - did you try this again?
Just wondering if this can be closed now.

**Comment by ganeshkamath89** [comment]
Hi @chrisjlocke,
     I was unable to copy 100000 insert queries for running with the build you shared. I recently changed my laptop. When I copy large number of queries, it is getting hung. I tried copying 50000 but still it became un responsive for some time. So I didn't continue further.

**Comment by chrisjlocke** [comment]
Aah, OK.  Sorry it didn't help.

**Comment by Zhuinden** [comment]
This problem still exists in 3.12.2.

**Comment by chrisjlocke** [comment]
The fix should also be in the nightly.

The commit was https://github.com/sqlitebrowser/sqlitebrowser/commit/73efa116807aa7171379a0c3f5bc479dda0810f8
I'm not clever enough to know if that commit found its way into 3.12.2.  I know commits are cherry-picked and squidged in rather than built from a branch.
