### ISSUE TITLE
between filter does not work for float fields

### ISSUE THREAD

**Issue by pablonana** [sqlitebrowser/sqlitebrowser#2574]
Details for the issue
--------------------

#### What did you do?
I used the 1.0~3.0 between filter for a column that contains float fields

#### What did you expect to see?
I expect to filter by range

#### What did you see instead?
it filtered all the rows

Useful extra information
-------------------------
The range operator filter ('\~') works for integers but not for floats. 
Additionally, It would be nice if you can select a range of values from a column and then right-click, select "use in filter expression", select "between this and this" and it will select the min and max value from the selected list and autocomplete the filter doing: "min~max". This should work for integers, too.
This is related to the issue:
https://github.com/sqlitebrowser/sqlitebrowser/issues/935

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ x ] Linux: ( _distro:_ Ubuntu 20.04_ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ x ] 3.11.x (3.11.2)
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
HAve you tried the later version?  3.11.2 is quite old now.  I've tried this with the later version, and this seems to work OK.
With a table of three values, 1.1, 2.2 and 3.3, it works OK for floats (which I didn't think it would do)

![image](https://user-images.githubusercontent.com/7872218/106802140-702cb500-665a-11eb-8c19-86f8680486c9.png)

![image](https://user-images.githubusercontent.com/7872218/106802163-7884f000-665a-11eb-999d-9299877de359.png)

**Comment by mgrojo** [comment]
Check the type of the data. Add a custom display format as `typeof("field")` and check if the data is TEXT instead of REAL.

**Comment by chrisjlocke** [comment]
Good point - this caught me out before when I reported the ~ operator not working - was due to the field being text.

**Comment by mgrojo** [comment]
Closing this as the required further information was not provided. It can be reopened, if there is still something to attend.
