### ISSUE TITLE
Unable to Create Foreign Key Constraint

### ISSUE THREAD

**Issue by mafischer** [sqlitebrowser/sqlitebrowser#2581]
Details for the issue
--------------------

#### What did you do?
I attempted to add a foreign key constraint

#### What did you expect to see?
I expected the foreign key constraint window to allow me to add a foreign key constraint.

#### What did you see instead?
The form did not allow me to select another table and foreign key to reference.
<img width="803" alt="Screen Shot 2021-02-07 at 11 04 39 AM" src="https://user-images.githubusercontent.com/1082176/107153651-48786e00-6934-11eb-9e99-1a45525096d3.png">

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.3.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.15.1

**Comment by mgrojo** [comment]
Thanks for reporting. This is duplicated with #2444. Please, subscribe to that.
