### ISSUE TITLE
[BUG-3.12.99-210209]Sort columns broken :(

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2583]
Details for the issue
--------------------

#### What did you do?
Clicked a column header within the data browser.

#### What did you expect to see?
Sorted data below the column headers.

#### What did you see instead?
No columns are visible.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ latest 10 Pro___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: ___DB Browser for SQLite Version 3.12.99 (Feb  9 2021)

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by sky5walk** [comment]
Ok, installed in reverse order till the bug is gone. :(
DB.Browser.for.SQLite-2021-01-27-win64 <-- Works.

**Comment by chrisjlocke** [comment]
Any chance of a screenshot?  I can't reproduce this (on Windows 10) and my version is from 6 Feb.

**Comment by sky5walk** [comment]
I have dark theme enabled. There is nothing to screenshot. I only see the headers. The rest is blank screen.

**Comment by MKleusberg** [comment]
Sounds like we generate a broken SQL query. Can you paste the last one or two lines from the "SQL Log" window's "Application" section in here, @sky5walk? Also a copy of the ```CREATE TABLE``` statement of your table could be helpful.

**Comment by sky5walk** [comment]
I can try this with the next nightly that would make the fix.
Right now I'm frozen at 210127.

Side note:  My real reason for upgrading and stumbling onto this bug, was a floating point error with my queries using nightly, 3.12.99 200603.
Ex. Inequalities failed with simple 2 <= 2.05. !!
This is fixed with 210127.

**Comment by justinclift** [comment]
@sky5walk Ahhh.  Sounds more like @MKleusberg was asking if you'd be ok to try running one of the broken builds (eg last night's?) in order to cut-n-paste the SQL log from that.

Maybe just grab the .zip version to keep things easy?  That one doesn't need any installation. :smile:

**Comment by sky5walk** [comment]
Ok, this is latest nightly run from zip, not installed.
Easy fix 😌 
You can see below, there is an error when I click on the TTp(s) column.
The SQL must put double quotes or backticks around a complex column name:  `TTp(s)`

SQL Log - APP
```
PRAGMA foreign_keys = '1';
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA encoding;
SELECT "_rowid_",* FROM "main"."DOC" LIMIT 0, 49999;
SELECT "_rowid_",* FROM "main"."DOC" LIMIT 0, 49999;
SELECT "_rowid_",* FROM "main"."TD" LIMIT 0, 49999;
SELECT COUNT(*) FROM "main"."TD"
SELECT "_rowid_",* FROM "main"."TD"  ORDER BY TTp(s) ASC LIMIT 0, 49999;
```
SQL Log - ERROR
`(1) no such column: s in "SELECT "_rowid_",* FROM "main"."TD"  ORDER BY TTp(s) ASC LIMIT 0, 49999;"
`

**Comment by justinclift** [comment]
Perfect, thanks. :smile:

**Comment by sky5walk** [comment]
Can someone mark this as BUG?

**Comment by justinclift** [comment]
Oops, good point.  Done. :smile:

**Comment by justinclift** [comment]
That being said, we could just add you to the developers group @sky5walk, so you'd have the ability to do stuff like that yourself, if you want?

**Comment by sky5walk** [comment]
Ok, yes. Please add me. 😄

**Comment by justinclift** [comment]
@sky5walk Team invite sent. :smile:

**Comment by oldlaptop** [comment]
This issue bisects down to commit 94023a55e836b279f070ada862432480b962c511 for me. This database (sqlite(1) .dump) should be an easy test case:

    PRAGMA foreign_keys=OFF;
    BEGIN TRANSACTION;
    CREATE TABLE test("Foonly Bar", "Egg bacon and spam");
    INSERT INTO test VALUES('1','z');
    INSERT INTO test VALUES('2','y');
    INSERT INTO test VALUES('3','x');
    INSERT INTO test VALUES('4','w');
    COMMIT;

I should have a patch shortly.
