### ISSUE TITLE
Accept input file parameters - Feature Request? Existing Feature?

### ISSUE THREAD

**Issue by joshglenn** [sqlitebrowser/sqlitebrowser#259]
Okay so I'm not sure if this is the appropriate place to do this, but I didn't see any other place. There may be a way to do this already, But if there's not just want to put my two cents in that it might be a good idea. I'm on Mac OSx. I have set up an Automator service that lets me right-click an SQLite database and then open SQLiteBrowser. However, when I do so it doesn't actually open the file in question. Is there a way for me, perhaps using a shell command or some other way, to open SQLiteBrowser and pass in the filename of the database I wish to open?

**Comment by joshglenn** [comment]
I was able to do this using finders normal file handling capability. Although, I kind of want something that won't make opening a database as simple as a double-click. Right Click > Open in ... would be nice.

**Comment by justinclift** [comment]
Hmmmm, in theory (!) if the first command line argument you pass is a database file name... it should open it.  Isn't that what Automator should be doing?

**Comment by joshglenn** [comment]
Yeah. It should be. I made a similar Automator workflow to do that with sublimetext. It opens the file or folder that I have highlighted. With sqlitebrowser, it seems no argument gets passed in, because it opens only the App not any database file along with it.

**Comment by justinclift** [comment]
Yeah, I'm not sure how to change that.  Sounds like we need someone with good Automator understanding to look into it (might be possible).  If it means we need to change something in our OSX builds, we can definitely consider it. :smile:

**Comment by joshglenn** [comment]
Okay. I figured out how to do this. Create an Automator service that runs a shell script. I even included a notification center to prompt with the filename as it opens. But that's not necessary.

```
for f in "$@"
do
	osascript -e "display notification \"$f\" with title \"Opening file:\""
	open -a "sqlitebrowser" "$1"
done
```

![screen shot 2015-04-16 at 10 42 42 am](https://cloud.githubusercontent.com/assets/6953274/7184905/5d941edc-e425-11e4-8fec-9f246c4e3f71.png)

**Comment by justinclift** [comment]
Good stuff. Although I wonder why it's needed for you (on my OSX 10.9 system it "just works") it's good that your workaround does the job. :smile:
