### ISSUE TITLE
can someone take a look and give me some thoughts how to to view this blob?

### ISSUE THREAD

**Issue by ghost** [sqlitebrowser/sqlitebrowser#2590]
![2](https://user-images.githubusercontent.com/79114925/107992593-a5ac9900-6f9e-11eb-8ad4-42ea6a4400ce.JPG)
![1](https://user-images.githubusercontent.com/79114925/107992594-a6452f80-6f9e-11eb-835b-2fd1194d5406.JPG)

I started this question over here at 

[https://discuss.zetetic.net/t/how-do-i-see-contents-of-blob/4827/2](url)

and they recommended I come here. 

Thoughts on how I can see this blob, and export it to a .csv? When I go to export I get a bunch of funny characters in the spreadsheet.

**Comment by sky5walk** [comment]
You have edit database cell set to Binary.
Change that to Text and report back.
What is the source format of the blob? UTF8 or ANSI or something else?

**Comment by j86schroeder** [comment]
![Capture](https://user-images.githubusercontent.com/79114925/107997684-f75a2100-6fa8-11eb-9055-5c9efda731ea.JPG)

**Comment by j86schroeder** [comment]
How do I find the source format of the blob?

**Comment by chrisjlocke** [comment]
If you change the mode to binary, what does it look like?

![image](https://user-images.githubusercontent.com/7872218/108000472-f5f91a80-6fe1-11eb-8627-2350ba15c6a1.png)

It might be RTF text, or even compressed - could be anything.

**Comment by j86schroeder** [comment]
Yes when I change the mode to anything else other than binary I get the error message try switching to binary mode, and when I go to binary mode, it looks like this...
![Capture](https://user-images.githubusercontent.com/79114925/108000721-3c358600-6fb0-11eb-8665-9ca43361cfb0.JPG)

**Comment by chrisjlocke** [comment]
It could be compressed - or even encrypted.  Or maybe both.

**Comment by j86schroeder** [comment]
It is likely both I guess? I guess there is no way around it?

**Comment by justinclift** [comment]
It's hard to tell at first glance.  What is the application that created the database?  There might be info online about it's file format. :smile:

**Comment by j86schroeder** [comment]
eSword

**Comment by sky5walk** [comment]
Ok, quick look into e-Sword and it is a proprietary Bible study app.
While the author may have chosen SQLite as one of its data sources, it does not mean all fields are discernible. [The following quote is from the e-Sword website: ](https://www.e-sword.net/faq.html)

> Copy the e-Sword modules from the "Resource Location" directory, such as BBLX, CMTX, DCTX, DEVX, LEXX, MAPX, and REFX files.

**Comment by justinclift** [comment]
@j86schroeder Interesting.  Not seeing any file format docs on their website, but if you politely ask them how to view the data they **might** already have a way to do it. :smile:

**Comment by mgrojo** [comment]
I hope we have helped you in some way.
