### ISSUE TITLE
Open DB Files in console? 

### ISSUE THREAD

**Issue by yaeuc100** [sqlitebrowser/sqlitebrowser#2593]
Hey guys sorry i am all new to this. I have created a database with db browser. Added triggers and also checks, i also added some data. It seems to work perfectly. The thing is i need to .db file from the whole database from sqlite3 console. Which file should i save from the db browser and how do i open my database directly in the console programm? Can't seem to figure this out. 

PS: I tried yesterday to rewrite in the console,  i get : UNIQUE CONSTRAINT FAILED when adding in the console but not in db browser. i would appreciate really any help. Thank you!

**Comment by chrisjlocke** [comment]
There should only be one file - a .db file (or whatever you called it - some people name is .sqlite, or .dbs - its pretty much whatever you want).  There might be an additional journal file, but depends on the settings you used.  I think these get cleared down and flushed once everything is saved, so all you need is the .db file.

>  I tried yesterday to rewrite in the console

Unsure what you typed, so if you know, post it here.
Theoretically, any SQL typed in the console should work in DB4S and vice-versa.  
By 'console' I assume you mean command-line program, sqlite3.exe?  (if on Windows).

**Comment by chrisjlocke** [comment]
Hi @yaeuc100 - do you have any more details for us to try and assist you?

**Comment by chrisjlocke** [comment]
Closing due to lack of response.  @yaeuc100 - feel free to comment further and we can try and assist.
