### ISSUE TITLE
Activate 3.12.1 as current release

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2594]
This is a reminder that we haven't changed yet the `currentrelease` file to 3.12.1. What is still missing?

**Comment by justinclift** [comment]
Ahhh, good point.  The only main thing missing from the 3.12.1 release is the fileio SQLite extension.

That's not **super** important anyway, so we can probably just update the `currentrelease` file now and push out 3.12.2 whenever it's convenient. :smile:

**Comment by justinclift** [comment]
On that note, I've just pushed out the updated `currentrelease` for `3.12.1`.

Thanks for the reminder @mgrojo :grin:

**Comment by mgrojo** [comment]
Thanks, Justin.
