### ISSUE TITLE
[BUG-3.12.99-210127] SQL Log - User: Row Count <> actual count. Prefetch limits answer.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2595]
Details for the issue
--------------------
#### What did you do?
Execute SQL within a sqbpro file on a single loaded database.

My Preferences - Database - Prefetch Block Size = 5000

#### What did you expect to see?
Rows returned = SQL Log - User count of rows returned.

#### What did you see instead?
SQL Log = 4999 rows and Results = 7406.
```
SELECT `TI(n)`,`A(n)`,`B(n)`,`C(n)`*1000 AS `C(mn)` FROM TD WHERE
	`TI(n)` = 1 AND
	`X(z)` = 2000;
-- Result: 4999 rows returned in 127ms
```
Useful extra information
-------------------------
If I change My Preferences - Database - Prefetch Block Size = 7500,
then the User Log returns the correct result.
But only because 7406 < 7500.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ 10 Pro Latest___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: ___3.12.99 - 210127

#### Did you also
Did not go higher in nightlies due to another bug regarding complex column names requiring backticks within queries.

- [] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
For clarity, what you're reporting is that the 'rows returned' is different to the actual number of rows in the grid - when you do 'select * from table', the number of rows returned could be > the prefetch block size, but the '(prefetch block size-1) rows returned' is displayed instead.

**Comment by justinclift** [comment]
@sky5walk Looks like @sandman7920 has committed a potential fix for this, so (in theory) it should make it's way into tomorrow's nightly builds.  Want to try it out and let us know if it works better?

**Comment by sky5walk** [comment]
Will do.

**Comment by sky5walk** [comment]
Ok to close.

**Comment by justinclift** [comment]
Thanks @sky5walk, I somehow missed seeing your follow up message about it working. :wink:

@sandman7920 Good work! :smile:
