### ISSUE TITLE
Modify Table list selection can be 'fooled' by dragging

### ISSUE THREAD

**Issue by EArmour** [sqlitebrowser/sqlitebrowser#261]
This is occurring in the latest nightly Windows build.

When modifying the order of fields, the 'move up/down' buttons are disabled when at the top/bottom of the list. But if you click on another row, then hold down the mouse button and drag to one of the end rows, the movement buttons are not properly disabled. So you can click to move the top row up and the bottom row down, both of which crash the application.

The inverse also works, so if you click the bottom row, then drag up one row, the "move down" button will be disabled even though you should be able to move the field. So basically it seems like the listener for disabling those buttons triggers on the mouse click, not the actual final selection after dragging around.

![2015-04-15 15_23_01-db browser for sqlite - d__dev__pycharm projects_smallthings_static_mwd db](https://cloud.githubusercontent.com/assets/1524567/7167488/620c3fe6-e383-11e4-89eb-e28564803796.png)

**Comment by justinclift** [comment]
Thanks, that definitely sounds like a bug. :wink:

**Comment by MKleusberg** [comment]
Haha nice find :+1: Thanks for reporting!
This should be fixed in the next nightly build.

**Comment by justinclift** [comment]
@EArmour Would you be ok to try out the next nightly build (tomorrow), and let us know if it's working like it should now? :smile:

**Comment by EArmour** [comment]
Alright, looks good now! Thanks for the quick response :+1:

**Comment by justinclift** [comment]
Awesome!  Thanks for letting us know @EArmour. :grin:
