### ISSUE TITLE
On Linux, the version of SQLite is old

### ISSUE THREAD

**Issue by tatsu38** [sqlitebrowser/sqlitebrowser#2610]
I'm using the latest version of the nightly build on Ubuntu 20.04. However, the version of SQLite is old. I want to use SQLite 3.31, what should I do?

https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing
sqlitebrowser_3.12.1-0\~3033\~202103060233\~ubuntu20.04.1

select sqlite_version();
3.30.1

Details for the issue
--------------------

#### What did you do?
I checked the version of SQLite

#### What did you expect to see?
version 3.31 or 3.33

#### What did you see instead?
version 3.30.1

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ Ubuntu 20.04 )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Not sure why the latest version of SQLite isn't being used - guess the building environment which builds that package hasn't been updated in a while.
Have you tried building DB4S yourself?  There are good instructions on how to do it.

**Comment by tatsu38** [comment]
Sure, the problem may be that the build process is out of date. Specifically, I think the version of SQLCipher is old.

On the display, it's SQLCipher version 4.3.0, but it's actually older.

> DB Browser for SQLite Version 3.12.99 (Mar  6 2021)
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.12.8
> SQLCipher Version 4.3.0 community (based on SQLite 3.34.1).

It was the same even if I built it myself.
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu--debian-linux

> DB Browser for SQLite Version 3.12.99 (Mar  6 2021)
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.12.8
> SQLCipher Version 4.3.0 community (based on SQLite 3.30.1).

> select sqlite_version();
> 3.30.1

**Comment by chrisjlocke** [comment]
Aah yes, if you build it using SQLCipher, then that is based on an older version of SQLite.  Do you need SQLCipher?  If you need a newer SQLite, you can build it without SQLCipher support.

**Comment by tatsu38** [comment]
Thank you. When I built it without SQLCipher, it became SQLite 3.31.1. You're probably using Ubuntu 20.04 SQLite directly.

> DB Browser for SQLite Version 3.12.99 (Mar  7 2021)
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.12.8
> SQLite Version 3.31.1.

> select sqlite_version();
> 3.31.1

The imminent problem has been resolved. However, can I modify the new SQLite so that it can be used without having to build it myself?

**Comment by chrisjlocke** [comment]
Do you mean slot the newer SQLite into DB4S without rebuilding DB4S?  Unfortunately not - it's all 'baked in' rather than access the file as an external library which can be swapped out.

**Comment by tatsu38** [comment]
I want to use SQLite 3.31 or 3.33 with nightly build (PPA). Can't update the build process?

**Comment by MKleusberg** [comment]
In theory DB4S can be built with any version of SQLite included or with some more or less random version SQLite loaded from a shared library. But unfortunately we're not in control of the build process of this PPA. You'd have to contact its author directly via this page https://launchpad.net/~linuxgndu.

I'll close this issue for now but feel free to reopen it if you need any further assistance from our side :smile:

**Comment by justinclift** [comment]
Well, @deepsidhu1313 **is** a member of the team too.  It's just a matter of people having enough time to try improving things, and the access to do so.

@deepsidhu1313 Does the PPA build process there allow other people to get involved and help out or improve things?  eg add more users or whatever with the right access permissions to help with updating build scripts and stuff

**Comment by deepsidhu1313** [comment]
Hi Justin, i will document the process and will share it with you so that in any case i will not be able to contribute to this project anymore, someone from community can take over and maintain it. Please feel free to browse the repos maintained under my profile, i will be happy to accept MRs. For the question related to using updated sqlite version with DB4S ppa builds, we mostly rely on Ubuntu’s default archive for ppa build. I have recently added sqlcipher to the same nightly ppa so that we can use latest version of sqlcipher to build DB4S, i will take a look over upcoming weekend if we can add updated sqlite as well, or if there is a reason it is not using it. Thanks.

**Comment by justinclift** [comment]
@deepsidhu1313 Thanks heaps.  Yeah, spreading write access permissions around - at least with people who show a constructive attitude :wink: - seems to be a good approach.  At least, that's what we've been doing for this main organisations repositories, as real life does take priority time wise sometimes. :smile:
