### ISSUE TITLE
Cannot save view with 'filter in any column' active

### ISSUE THREAD

**Issue by bob-u** [sqlitebrowser/sqlitebrowser#2615]
Details for the issue
--------------------

#### What did you do?

('filter in any column' == global search)

1)typed a search keyword in global search bar
2)tried to save view and was presented with error: 
"There is no filter set for this table.  View will not be created."

Global view does work if at least one column filter is used:
1)typed a search keyword in global search bar
2)typed a keyword within column filter
3)saved view (this time it worked) that included global search bar keyword and column filter

Resulting view is as I would expect global search view to work, except of the additional column filter applied

#### What did you expect to see?
for global searches: saved view with select WHERE <column> LIKE %keyword% applied to all columns

#### What did you see instead?
error in popup window:
"There is no filter set for this table.  View will not be created."

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_ 10___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?
DB Browser for SQLite Version 3.12.1

Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8
SQLite Version 3.33.0.
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Have labelled it as a bug, but just to confirm, you can edit the view (if you add an unnecessary filter) which can then be removed - have you tried that?

**Comment by bob-u** [comment]
Yes, I can edit the view...about that:  when editing the view I expected to have a way to save it after modification and the only way I found was by clicking "write changes" button, which I think applies all changes not just the view, I think?

**Comment by chrisjlocke** [comment]
The only way to edit a view is to drop it and recreate it using SQL statements, and as each one of these is committed once you press the 'Write changes' button, that's the only way to 'save it', per se.

**Comment by mgrojo** [comment]
This check was supposed to help the user understand what this operation was for, but it was actually preventing to save as view table states that had global filter, display formats or custom order and not column filters. It's better to give the user the freedom, even to create maybe useless views as:

`CREATE VIEW "example_view" AS SELECT * FROM "main"."example"`

The check has been removed. @bob-u, could you try with [tomorrow nightly build]( https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds) which will include this fix and close this issue if everything works as expected?

There is also a new "Export to JSON" action in the same menu, which surprisingly was also missing and nobody has complained.

**Comment by bob-u** [comment]
Save view with global filter works in build from 13-Mar-2021 01:33.

**Comment by justinclift** [comment]
Awesome!  Good stuff @mgrojo, and thanks for verifying it @bob-u  :smile:
