### ISSUE TITLE
Clear all filters to clear 'filter in any column' filed also

### ISSUE THREAD

**Issue by bob-u** [sqlitebrowser/sqlitebrowser#2616]
Describe the new feature
--------------------------
Hello

In my opinion it would be nice if:
1)'clear all filters' would clear 'filter in any column' field
2)if there was some hint in the icon bar that any (filter in any column or column filter) filter is active.  Perhaps keep the 'clear all filters' grayed out when filters are not in effect?

First request I think is self explanatory.  Second would be useful when there are columns with filters that are not visible in current view.  Another improvement would be to invert text in filter field (or make it to stand-out in some way) with filter active so it's easier to spot.  Thank you.

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by mgrojo** [comment]
@bob-u, both requests make sense to me and I have implemented them. Could you try them using [tomorrow's nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) and report any glitch?

**Comment by bob-u** [comment]
Hi @mgrojo.  I tested DB.Browser.for.SQLite-win64.zip 20-Mar-2021 01:33, and clear filters button does clear 'global filter' now and becomes inactive when there are no filters.  Great usability improvement.  Thanks!
