### ISSUE TITLE
Slow Execution of SQL satements in Execute SQL window

### ISSUE THREAD

**Issue by addled1** [sqlitebrowser/sqlitebrowser#2619]
Details for the issue
--------------------

#### What did you do?
I created a new database, dismissed the create table dialogue and pasted my table, index and view creation statements into the Execute SQL window and clicked the run button. The SQL I use runs to ~7,767 lines and includes some 'setup data' insert statements for a few of the tables.. There are 101 table, 101 triggers, 58 views and 559 indexes created. 1 table has ~450 seed data inserts and ~4 or 5 tables have between ~10-20 seed data inserts each

#### What did you expect to see?
A database with 101 table, 101 triggers, 58 views and 559 indexes created. 

#### What did you see instead?
I saw what I expected... eventually!

 I have been using this as a way of testing my SQLite database creation scripts to identify any SQL typos or incompatible statements for a number of years now and it has always worked well, until recently, with my scripts completing fairly rapidly in < ~20-30 seconds. But since one or two sqlitebrowser releases ago, it has all started running very slowly showing each semi-colon statement executing in   0 ms but taking about 1 sec to display the result and move to the next statement. It seems particularly slow on the insert statements and by the time it got down to index and view creation it just rattled through those statements like it always had. The total execution time

Note, the content of the executed script is run from within a WPF desktop application that I develop when a new SQLite database is required and completes in ~10-15 sec (possibly less) in that case but I always test changes/updates manually against SQLite, MSSQL and PostgreSQL so I can pick up any mistakes before I release changes.

There was some error log data:
(21) API call with invalid database connection pointer
(21) misuse at line 162200 of [fca8dc8b57]
(1) "Database didn't close correctly, probably still busy" (, :0)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( version: Windows 10 Pro 20H2  OS Build 19042.867)
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Thanks for reporting this.
This is probably linked to #2592 where the number of lines just trips the parser.  My recall on versions is a bit hazy now, but I don't think there has been any improvement in this area since the 3.12.1 release, but have you tried the nightlies?  You can download a nightly, extract and run the .exe - you don't need to install it.  

I know this area of code has undergone a fair bit of love and attention, which is why its changed in recent versions.  Sorry it seems to have had a negative effect.  Attempts have been made to make it multi-threaded, etc.  

While this is a duplicate (of sorts) I'll keep it open as it might not be 100% related to the above issue... it'll need @MKleusberg to cast his eyes over this.

Is there any way you can post the schema you created, or even upload the database to dbhub.io?  This'll help us run what you have to ensure we get the same error you do, then we can identify it easier.  Thanks!

**Comment by addled1** [comment]
[BRAHMS_DB.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/6119455/BRAHMS_DB.zip)

Thanks for your reply. I did see #2592 but thought maybe more related to https://github.com/sqlitebrowser/sqlitebrowser/issues/2572 perhaps.

I have attached a zip containing the created SQLite database and an SQL file containing the script that was pasted into the SQL Execute window and run to create the tables and views etc.

**Comment by chrisjlocke** [comment]
Excellent, thanks for the upload.  That'll help reproduce the issue.
Weird there is a large delay considering its only ~7700 lines - expected it to be quicker than that.
Created a new in-memory database, and saw the same issue (using a relatively new nightly).  https://streamable.com/y23xsp

**Comment by MKleusberg** [comment]
Thanks for pointing this out, @addled1! Tomorrow's nightly build should improve the performance a lot. Can you give that a try? It will be available tomorrow [here](https://nightlies.sqlitebrowser.org/latest/). There is still room for further improvements but considering how many open issues we have I' suggest closing this one if the new version is already fast enough for you :wink:

**Comment by addled1** [comment]
I have just tried the above suggested nightly build:
DB Browser for SQLite Version 3.12.99 (Mar 16 2021)
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8, SQLite Version 3.35.0.

I can confirm that it is indeed greatly improved in Execute SQL speed (and feedback) when executing my database creation script.

A huge thank you for looking at this and fixing my issue so promptly.

So, well done and congratulations on having produced such a useful tool for working with SQLite databases. It is of enormous help to me in my development efforts so thank you, and all contributors, for your fantastic efforts.

**Comment by chrisjlocke** [comment]
Thanks for reporting back, raising the issue to make DB4S better, and of course your kind comments.  👍

**Comment by MKleusberg** [comment]
Thank you for your kind words :smile: I'm glad I could help!
