### ISSUE TITLE
Proxy Denied Connection dialog is popping up when offline.

### ISSUE THREAD

**Issue by sspates-starbucks** [sqlitebrowser/sqlitebrowser#2625]
We are using the tool with a machine that is offline and cannot reach the internet.  For some reason, the tool is prompting about failing to connect to a proxy when none is specified:

![image](https://user-images.githubusercontent.com/70030176/110976173-6fe89f00-8315-11eb-9de9-ab68884d0f21.png)

**Comment by chrisjlocke** [comment]
Theoretically, this'll be the 'check for latest version' option, which you can turn off.
Click 'Edit' and 'Preferences', then remove the tick from the 'Automatic updates' option.

![image](https://user-images.githubusercontent.com/7872218/111030535-b2d07280-83fa-11eb-9b09-949230cfc016.png)

Yell back if that works or not.

**Comment by justinclift** [comment]
@sspates-starbucks Did that help? :smile:

**Comment by chrisjlocke** [comment]
I'll close this, assuming the answer is yes.  @sspates-starbucks - please comment back if you still have issues.
