### ISSUE TITLE
How to import data from CSV file into SQLite with CLI and handle unique constraint?

### ISSUE THREAD

**Issue by mostaszewski** [sqlitebrowser/sqlitebrowser#2630]
Hello,
is it possible to import data from CSV file into SQLite database with CLI and handle unique constraint?

Right now I am doing it this way:

```
.open [path to my database]
.separator ,
.import [path to a CSV file] [table name]
```
Everything is fine until it raises

`INSERT failed: UNIQUE constraint failed: [table name].[field name]`

I would like to use the **ON CONFLICT REPLACE** in such cases.

I know it is possible in the sqlitebrowser GUI by using "Conflict strategy" feature available in the "Import CSV file" window - is there any CLI equivalent?

![sqlite](https://user-images.githubusercontent.com/26186093/111066263-5040aa80-84be-11eb-90d0-521fd3bfc8e6.PNG)

Thank you

**Comment by chrisjlocke** [comment]
DB4S has a command-line switch to import a CSV file via the command-line - I'm unsure what conflict strategy settings it uses - default ones, or the previous ones entered.  You could try on a new database or in-memory database to test...

For the avoidance of doubt, you have quoted sqlite3.exe commands (.open, .seperator, etc) and this program is totally separate from DB4S.  This might be known, but just wanted to make sure.
We have no control over the sqlite3 program and how it operates - we can only amend and develop DB4S.

**Comment by mostaszewski** [comment]
> DB4S has a command-line switch to import a CSV file via the command-line - I'm unsure what conflict strategy settings it uses - default ones, or the previous ones entered. You could try on a new database or in-memory database to test...
> 
> For the avoidance of doubt, you have quoted sqlite3.exe commands (.open, .seperator, etc) and this program is totally separate from DB4S. This might be known, but just wanted to make sure.
> We have no control over the sqlite3 program and how it operates - we can only amend and develop DB4S.

Yes, you are correct, I mentioned list of sqlite3.exe's commands - I just wanted to show what I tried to do before.

So is it possible to set conflict strategy before the `.import` command execution? Could you please explain me how to do it?
Thank you

**Comment by chrisjlocke** [comment]
Looks like its a command extension, so you use it in your INSERT statement.
https://sqlite.org/lang_conflict.html

**Comment by mostaszewski** [comment]
> Looks like its a command extension, so you use it in your INSERT statement.
> https://sqlite.org/lang_conflict.html
> So in an INSERT, you don't actually use ON CONFLICT, but instead use OR. INSERT OR REPLACE for example.

Just to be sure - it is not possible to run the same command via sqlitebrowser's CLI as the one's I showed on the attached screenshot?

**Comment by chrisjlocke** [comment]
No - DB4S and sqlite3 are completely different programs - they're not written by the same people or even do the same job.  DB4S is a GUI to SQLite, and not a GUI to sqlite3 (slight but important difference).
The import via command-line is a recent addition (and still technically in development) and as yet doesn't support the ON CONFLICT to be set via command-line.  As I said though, it might remember the last setting used, so it might still be a viable option for you.

**Comment by mostaszewski** [comment]
> No - DB4S and sqlite3 are completely different programs - they're not written by the same people or even do the same job. DB4S is a GUI to SQLite, and not a GUI to sqlite3 (slight but important difference).

Sure thing, I know about that, probably I have mentioned sqlite3.exe unnecessarily.

> The import via command-line is a recent addition (and still technically in development) and as yet doesn't support the ON CONFLICT to be set via command-line. As I said though, it might remember the last setting used, so it might still be a viable option for you.

It sounds promising, but for now I managed to do what I want by setting **ON CONFLICT REPLACE** on column.

Thank you!

**Comment by chrisjlocke** [comment]
No problem.  Glad you got there in the end.  👍
