### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by RiccardoBarbieri** [sqlitebrowser/sqlitebrowser#2635]
I'm trying to open a database with sqlite browser but it says that the database is locked. I tried to find if there are any processes that are using the database file but I couldn't find none. What else could it be?

**Comment by scottfurry** [comment]
It could be the folder permission settings. When `sqlite` opens a database, it creates a lock file in the same directory(look for a file that starts with a tilde, `~` character). If the permissions inhibit file creation, `sqlite` could report file is locked.

This is a guess on my part. There could be other things going on, but permissions would be my first check.

FYI - more information would help. Version of sqlitebrowser? Operating System?

**Comment by RiccardoBarbieri** [comment]
> It could be the folder permission settings. When `sqlite` opens a database, it creates a lock file in the same directory(look for a file that starts with a tilde, `~` character). If the permissions inhibit file creation, `sqlite` could report file is locked.
> 
> This is a guess on my part. There could be other things going on, but permissions would be my first check.
> 
> FYI - more information would help. Version of sqlitebrowser? Operating System?

Thank you very much. I totally forgot that the database I was trying to open was in a WSL path.

**Comment by AbidKhairyAK** [comment]
@RiccardoBarbieri  actually you can use sqlite browser on wsl, you just need to install the app as an wsl / linux app like you normally do on linux operating system. if installed correctly, the app will show on the Start Menu with a penguin on the front of its icon. here's the install script:

```bash
sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser
sudo apt-get update
sudo apt-get install sqlitebrowser
```

<img width="998" height="808" alt="Image" src="https://github.com/user-attachments/assets/93bb2519-0c63-4bdd-9c67-731aef4fb186" />
