### ISSUE TITLE
Cannot open zero byte file as empty database - opens as CSV file instead

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2636]
Details for the issue
--------------------

#### What did you do?
Opened a zero byte file as a new database with the intention of creating tables, etc.

#### What did you expect to see?
An empty (blank) database

#### What did you see instead?
Import CSV dialog.  Cancelling then 'opens' in-memory database.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.99 - 13 Mar 2021
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

So I normally create a new file in Windows, give it a .db extension, then drag that into DB4S.  This usually 'opens' it (sans tables, etc) allowing me to create the schema as needed.

In the newer nightly, when I drag the file into DB4S, a dialog appears, asking if I want to open this file, attach or import.  

![image](https://user-images.githubusercontent.com/7872218/111850150-65c33380-8907-11eb-9d0a-2101191ef4a4.png)

I choose 'Open'.
This dialog disappears, only for the 'Import CSV' dialog to appear.  

![image](https://user-images.githubusercontent.com/7872218/111850179-7b385d80-8907-11eb-95a8-2249dd60cea9.png)

The table name is the name of the file.
Clicking Cancel closes this dialog, but DB4S is now telling me it has an 'in memory' database open.

![image](https://user-images.githubusercontent.com/7872218/111850258-bb97db80-8907-11eb-84a6-af64ff545108.png)

I assume this 'in memory' database was created and opened to import the CSV file into...

In a previous nightly I used (9 Feb) dragging a zero byte file into DB4S displayed the 'open/attach/import' dialog, but clicking on 'open' did in fact open the database.

Opening the database the 'normal' way (File, then Open) creates the same issue - the 'Import CSV' dialog is displayed.

Clicking 'File' and 'New database' works properly, but sometimes I'm in the folder where I want to be, so creating a zero byte file is easier than going back to DB4S, clicking 'File', 'New Database', then navigating to where I want the database...

**Comment by chrisjlocke** [comment]
Screencast just to prove I'm not going loooooopy.

https://user-images.githubusercontent.com/7872218/111850812-2a296900-8909-11eb-8fed-b341244c4b87.mp4

**Comment by justinclift** [comment]
Sounds to me like the "open the zero byte file" piece is failing, because it's **not** actually a database.

So, then the fallback behaviour of "lets try it as a CSV file" happens instead.

Not really sure of the "correct" behaviour here though, as opening a zero byte file and pretending it's a valid (but empty) database isn't really correct either.  That being said, if that's definitely the previous behaviour then it's probably something some of our users have become accustomed to.

We *could* probably do a file-size check after a failed database opening, then invoke the previous behaviour for zero byte files. :smile:

**Comment by chrisjlocke** [comment]
> Not really sure of the "correct" behaviour here though, as opening a zero byte file and pretending it's a valid (but empty) database isn't really correct either. 

Well, indeed, but it's the only possible 'solution' - it can't think its something to import, as it's empty.  It could attach it I guess.

Actually, just checked, and you can drag it, attach it, and amend it that way, so that's a workaround at the moment.  Fifty steps instead of one, but it's a fix! 😁😂😂

**Comment by chrisjlocke** [comment]
Interestingly, the 'open/attach/import?' dialog is a bit stroppy - just tried it again (testing the attach thing) and it's not appearing - dragging a file (zero bytes) straight into DB4S gives me the 'import CSV' dialog,  I have to have an open database before it appears.

**Comment by mgrojo** [comment]
I didn't think about this case and nevertheless, I'd have said that SQLite was going to reject the empty file as a database. But it was easy to return to the previous behaviour: in the tests to determine whether the file is a project file, a text file or a database file, the text file check will now say it's not, and it will fall in the database case again.

**Comment by chrisjlocke** [comment]
Thanks @mgrojo - appreciate the quick fix.  😍🤩🥰🥰
