### ISSUE TITLE
Ugly font 

### ISSUE THREAD

**Issue by alex9153** [sqlitebrowser/sqlitebrowser#2640]
<img width="2105" alt="Снимок экрана 2021-03-23 в 13 11 11" src="https://user-images.githubusercontent.com/353832/112131145-4a437b80-8bda-11eb-99bf-88c08adfbb4b.png">

MAC OS 11.1

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?
If you click 'Edit' and 'Preferences', you can change the font to another one.

Click the 'Data browser' tab and see the font option.
![image](https://user-images.githubusercontent.com/7872218/112134917-2295e880-8bc5-11eb-85dc-70833a82aae1.png)

There is also a font option on the 'SQL' tab.
![image](https://user-images.githubusercontent.com/7872218/112135023-3c373000-8bc5-11eb-833c-ebd96df8f358.png)

**Comment by chrisjlocke** [comment]
@alex9153 - Has changing the font helped?

**Comment by alex9153** [comment]
fixed thanks

**Comment by chrisjlocke** [comment]
Excellent - thanks for confirming!
