### ISSUE TITLE
Warning: QT_DEVICE_PIXEL_RATIO is deprecated.

### ISSUE THREAD

**Issue by yu6315** [sqlitebrowser/sqlitebrowser#2643]
What is your question
-----------------------
![image](https://user-images.githubusercontent.com/48148334/112400907-59463d00-8d44-11eb-852f-d3de5b2043e6.png)
When I run the software, this prompt pops up.

**Comment by justinclift** [comment]
Thanks, that's helpful. :smile:

Oh, which version of DB Browser for SQLite is that happening for, and on which Operating System? (that information is important, as it helps us investigate) :grin:

**Comment by yu6315** [comment]
> Thanks, that's helpful. 😄
> 
> Oh, which version of DB Browser for SQLite is that happening with, and on which Operating System? (that information is important, as it helps us investigate) 😁

DB Browser for SQLite version is 3.12.1, Operating System is Windows 10 Home 20H2 (10.0.19042).

**Comment by yu6315** [comment]
> Thanks, that's helpful. 😄
> 
> Oh, which version of DB Browser for SQLite is that happening with, and on which Operating System? (that information is important, as it helps us investigate) 😁

Thank you very much😄, I solved this problem by deleting the environment variable:`QT_DEVICE_PIXEL_RATIO=auto`, [details](https://stackoverflow.com/questions/58194247/warning-qt-device-pixel-ratio-is-deprecated)

**Comment by justinclift** [comment]
Oh, that's good info.  Thanks for putting that there.  Any future people having the same problem will find that solution when searching. :smile:

**Comment by Hamza1244** [comment]
Hi @yu6315 Sir, please tell me how to fix that

**Comment by chrisjlocke** [comment]
There is a link here:
https://stackoverflow.com/questions/58194247/warning-qt-device-pixel-ratio-is-deprecated

Simply remove the environment variable.  What OS are you using?

**Comment by jalalsaberi** [comment]
OS = Windows 11 Pro 22H2
Permanent method (for all future sessions):
1. Right-click on "This PC" or "My Computer"
2. Click on "Advanced system settings"
3. Click the "Environment Variables" button
4. Under "System variables" delete QT_AUTO_SCREEN_SCALE_FACTOR
5. Click OK on all open windows to save the changes

**Comment by jalalsaberi** [comment]
OS = Windows 11 Pro 22H2
Permanent method (for all future sessions):
1. Right-click on "This PC" or "My Computer"
2. Click on "Advanced system settings"
3. Click the "Environment Variables" button
4. Under "System variables" delete QT_****
5. Click OK on all open windows to save the changes

**Comment by jalalsaberi** [comment]
OS = Windows 11 Pro 22H2
Permanent method (for all future sessions):
1. Right-click on "This PC" or "My Computer"
2. Click on "Advanced system settings"
3. Click the "Environment Variables" button
4. Under "System variables" delete QT_DEVICE_PIXEL_RATIO
5. Click OK on all open windows to save the changes
