### ISSUE TITLE
"Refresh" button doesn not re-load from disk?

### ISSUE THREAD

**Issue by davecotter** [sqlitebrowser/sqlitebrowser#2646]
Details for the issue
--------------------

#### What did you do?
press the refresh button

#### What did you expect to see?
the current DB is completely reloaded from disk (replacing the in-memory one)

#### What did you see instead?
it just refreshed the view based on the in-memory db

#### request:
perhaps a "reload" button, or an "auto-reload" function where if you're viewing a read-only DB, that if the DB changes on disk due to another process, the view will reload the DB from disk and display the updated data

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on macOS Mojave (10.14) (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.15.1

**Comment by chrisjlocke** [comment]
This is also being discussed in the discussion area.
https://github.com/sqlitebrowser/sqlitebrowser/discussions/2648

I'll leave this open for the time being, but this is not a known issue - the refresh button does work as you expect it to - it reloads from the disk.

**Comment by chrisjlocke** [comment]
Aah, actually, this is slightly different from the discussion - this is mentioning an in-memory database.
Your other discussion was related to accessing a database in read-only mode.

Can you explain (in reproducible steps) what you're doing.  You're creating an in-memory database, then opening another database?

**Comment by chrisjlocke** [comment]
@davecotter - *cough*

**Comment by davecotter** [comment]
no it's an on-disk database. my app changes it, i want this app to notice it changed and update accordingly.

**Comment by chrisjlocke** [comment]
Thats freaky, as obviously it should.

Any chance you can fire up two copies of DB4S and just confirm it works on a new database?
https://user-images.githubusercontent.com/7872218/113322723-f6890e80-930c-11eb-9561-cb79a3149f52.mp4

So opening the same database in two instances.
I ballsed up in the screencast and the initial refresh didn't work until I clicked 'Write changes'.  
If that doesn't work, then we know if the issue is with DB4S or not...

**Comment by davecotter** [comment]
well it's working now, maybe i was previously looking at the wrong thing, thanks for looking into it.

**Comment by chrisjlocke** [comment]
Glad its now working.
