### ISSUE TITLE
always not responding

### ISSUE THREAD

**Issue by argstorm** [sqlitebrowser/sqlitebrowser#2653]
Details for the issue
--------------------

#### What did you do?
Launch the program, open a database

#### What did you expect to see?
To manipulate the database.

#### What did you see instead?
Just clicking the 'create table' button causes 'not responding', CPU occupation 30+%, memory occupation 1.5G+, power usage very high. Long waiting brings more occupation.

Useful extra information
-------------------------
> DB4S v3.12.1 [built for i386-little_endian-ilp32] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Eurk.  Does it happen on all databases or just this one?
If you click 'New database', set a location (eg, desktop), it'll come up with a new table.  Just type 'TableA' and click 'Add' in the 'Fields' tab a couple of times, then click OK.  Click 'Write changes'.  If you close the database and reopen it, does it open OK?

How big is the database you're trying to open (file size).  How many rows in the first table? (alphabetically).  I assume its a local database, and not on a network?

**Comment by argstorm** [comment]
Hi Chris, thanks for your reply. It's a small local database. I just started to learn SQLite, with a 5-row, 3-column table. I followed your guidance and it crashed when I clicked 'Add' in the 'Fields' tab. Just like what I encountered before.

**Comment by justinclift** [comment]
Ahhh, that sounds like something about the table structure was giving it grief.  Do you happen to remember the settings you used?  That'd be helpful for us trying it out here and/or there might be some super obvious "gotcha" thing we can point out. :smile:

**Comment by chrisjlocke** [comment]
Grr.  That's annoying.  Think we've had something similar, but many moons ago on an old version.  Not had any recent reports of this, and 3.12.1 has been out a while now.
Can you try the nightly?
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

Just download the ZIP, extract it, go into the 'DB Browser for SQLite' folder, and run the .exe.  You'll see two .exe's - you can ignore the SqlCipher version.

You don't need to uninstall the previous version - this can run 'as is'.

**Comment by chrisjlocke** [comment]
One thing to try if you're bored, is to try the 'execute sql' tab.
Create a new database, and you'll get the table dialog.  Cancel that, then go to the 'Execute sql' tab.
Type `create table tableA (field1 integer primary key,field2 integer, field3 integer)` then press [F5] to run it.
If that works, then we know it's something to do with Qt - displaying a grid or something?
If that does work, then we could try using a slightly older version of DB4S that uses a different version of Qt - there a loads of nightlies to try...

**Comment by argstorm** [comment]
Same happened to nightly... But creating new table by 'Execute sql' works!  Many many thanks!

Should I forget 'cerate table' tab from now on?

**Comment by argstorm** [comment]
Hi Justin, I don't remember 'the settings' when installing it. It seems a very simple operation without settings...

**Comment by chrisjlocke** [comment]
OK.  Well, glad you got at least some way there, but it doesn't explain the issue...
Can you click 'Modify Table' (which should display the same dialog as before) and again, click 'Add'?

![image](https://user-images.githubusercontent.com/7872218/113417097-a5375880-93ba-11eb-8786-a13e15df0727.png)

All it does it add an entry into the grid, so it should spin this time....

If that fails, and depending on your patience, we could try older versions of DB4S...
As an aside, how are you learning sqlite - from a course, or just from online videos?

**Comment by argstorm** [comment]
Things are getting worse. After trying 'Execute sql' a couple of times, I can't even open a database. It crashes as soon as I launch it. 

I learned sqlite from Coursera's Python for Everybody.

**Comment by chrisjlocke** [comment]
Well, thats a bit more interesting.  When you say 'crashes', I assume you mean DB4S just closes, with no errors - just vanishes.  Is that as soon as opening DB4S and not opening a database?  Or as soon as the database is opened?
If the latter, can you try creating a new database again - different filename.  Cancel the 'create table' dialog, then just close the database - that'll be a blank database.  Try opening it again - does it then crash again?
Apologies for all this, and again, thanks for your help in troubleshooting.  I appreciate it's a pain and laborious process.  

If all that is still failing, can we try last years nightly?  Just ruling out something wacky in the code and/or Qt version, etc.
https://nightlies.sqlitebrowser.org/win32/2020-01/DB.Browser.for.SQLite-2020-01-05-win32.zip

Again, that's just a ZIP, so extract, find the .exe and run it.  It should look identical to the latest version, give or take...

Thanks! 👍

**Comment by argstorm** [comment]
Sorry for my late reply! My 'crashes' means program not responding, CPU and memory keep increasing, with terribly loud noise. Sometimes I can open a database, sometime can't. But can never do anything more.

Fortunately, this nightly works perfectly! I tried each tabs, then saving, quitting, reopening. No problem any more. Many many thanks!!!

**Comment by chrisjlocke** [comment]
Don't apologise for late replies - any reply is better than nothing. 😉
Well, I'm glad we've got at least something working for you.  INteresting that the recent builds aren't.  This could mean one of two things.  Our latest builds are garbage and aren't working on anyones PCs, but you're the only one to point it out, or there is something wacky about your setup (some other program installed) which is causing some conflict.  Nothing personal, but I'm edging more towards scenario #2, than #1.  
It would be nice to identify what, but as it's just spinning, it would need some logging in the application (and not just to the existing application log) and a lot of trial and error.  
I suspect it's something to do with the multi-threading code, but that's only a guess between the version of DB4S that does work and the version that doesn't.  We can try other nightlies to find the point where they no longer work - that would help identify the bit of code that is causing the problems.  If you're up for that (downloading, extracting and a bit of testing) then let me know.  You might just want to celebrate knowing you've got something working!

**Comment by argstorm** [comment]
What nightlies can I try?

**Comment by chrisjlocke** [comment]
If it is the multi-threading code, then those would be recent (which might tie in with 3.12.1 being an issue) - that was in Nov 2020.  Lets try the binary split approach.  Try mid-way - May 2020?
https://nightlies.sqlitebrowser.org/win32/2020-05/DB.Browser.for.SQLite-2020-05-16-win32.zip

All the nightlies are here:
https://nightlies.sqlitebrowser.org/win32/

Theoretically, the code-base between the nightlies and releases are different - just various parts are cherry-picked from the nightlies into the releases.
If the May 2020 worked, try halfway again, so Aug 2020?
https://nightlies.sqlitebrowser.org/win32/2020-08/DB.Browser.for.SQLite-2020-08-18-win32.zip

So last one (ish) of 2020 was in Dec.
https://nightlies.sqlitebrowser.org/win32/2020-12/DB.Browser.for.SQLite-2020-12-20-win32.zip

See how many of those fail! ;)

**Comment by argstorm** [comment]
2020-05-16 failed,
2020-08-18 failed,
2020-12-20 failed.

**Comment by chrisjlocke** [comment]
Thanks for trying.
We don't have many nightlies in March, so wanna try the 9th?
https://nightlies.sqlitebrowser.org/win32/2020-03/DB.Browser.for.SQLite-2020-03-09-win32.zip

We know Jan works, and May doesn't, so just trying to find the last one that fails so we could work out what code was added which is causing you problems.  So far, you're the only person who's reported a problem - either other people have experienced it and just decided DB4S is pants and haven't gone any further, or no-one has had a problem - hard to know ... or it could be something installed on your machine interfering but hard to know that too.  There are ways of working out from crash dumps exactly why its crashing, but that's a little bit out of my comfort zone to guide you on what to do - it's not something I know much about.

**Comment by chrisjlocke** [comment]
I'll close this as there hasn't been any further input.
Annoyingly this seems an isolated case, but identifying which nightly starts causing the issue could identify the possible code problem.  
We're hoping to release version v3.12.2 soon, so would be interesting to know if that one works.  This seems system-related unfortunately, as there hasn't been a flood of similar issues.
Yell back when convenient and this can be re-opened if necessary.

**Comment by argstorm** [comment]
Hi Chris, sorry for the delay. I registered the email account for Coursera courses only and haven't checked it since I finished the last course. So I didn't receive your reply until this morning.
I tried the nightly of 9th March. It's a good one. Thanks for your patience and kindness! If you don't mind, you can release the further versions here. I won't let you wait so long again.
Cheers!
