### ISSUE TITLE
Impossible to 'Set Encryption' for the current database

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2654]
I've not used the SQLCipher version before, but using it to test a .net 'plugin'.
I've created a database, then clicked 'tools' and 'set encryption'.  The dialog appears, when I enter a key.  It's only a small test database, so quick to 'encrypt'.  An open dialog then appears.

![image](https://user-images.githubusercontent.com/7872218/107068321-616c0c80-67d8-11eb-8c77-3dcad20a8e6e.png)

It's not immediately obvious what to do - open '1.db' ?  Tried that, and that is unencrypted.
However, there is a hidden .enctemp file.

![image](https://user-images.githubusercontent.com/7872218/107068426-82346200-67d8-11eb-870e-d5f8bec4ced3.png)

This *does* seem encrypted.  Is this how it works - I now use the '.enctemp' file and rename the '1.db' as no longer being used?
Just seems that there should be some dialog explaining this, or even a 'do you want the original file backed up and the '.enctemp' renamed?' helpful last step...
Initially I just thought the encryption wasn't working...

Also, in the encryption dialog, you can set v3 or v4 defaults.

![image](https://user-images.githubusercontent.com/7872218/107068869-0c7cc600-67d9-11eb-81ae-490777793438.png)

Does this also set whether a v3 or v4 type file is created?  I seem to remember something hazy about the file types are completely different, and I wasn't sure what version my .net code can open - can I set which version DB4S creates?  Or does it still create a v4 file, just with v3 'headers' / settings?

_Originally posted by @chrisjlocke in https://github.com/sqlitebrowser/sqlitebrowser/discussions/2579_

**Comment by chrisjlocke** [comment]
Thanks @mgrojo 👍

**Comment by mgrojo** [comment]
It seems exactly what you saw, but I could not test with SQLCipher, but in the source code seemed obvious, `fileClose()` is resetting `currentFile()`. I've changed it, so it no longer matters.

This is apparently only in the master branch.

**Comment by chrisjlocke** [comment]
Yay!  Thanks @mgrojo 😍
Now get this after setting a password.

![image](https://user-images.githubusercontent.com/7872218/113723544-5d317200-96e9-11eb-977f-d24c3e8c6077.png)

Entering the password brings up the encrypted database.  All works again!  👍
