### ISSUE TITLE
Missing shortcut description on how to follow foreign keys (i.e. CTRL+SHIFT+Click) in the "Keyboard Shortcuts" docs section

### ISSUE THREAD

**Issue by agpaleoc** [sqlitebrowser/sqlitebrowser#2656]
Details for the issue
--------------------

#### What did you do?
Looked for a shortcut on how to follow foreign keys in the "Keyboard Shortcuts" section of the docs

#### What did you expect to see?
The keyboard shortcut CTRL+SHIFT+Click and a description of what it does

#### What did you see instead?
It wasn't listed.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: 10
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Interesting.  Thanks for letting us know.  We'll get that added.  👍

**Comment by agpaleoc** [comment]
Thank you very much!


Alex

**Comment by MKleusberg** [comment]
Just added it: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts/_compare/b8420521b7fbf3439252acae250d42079cfb7bf4...a42e5bd4688eed401aec6d98b69eb50716507590

I'll close this issue but if you feel like we should add further explanations or similar feel free to reopen it any time!

**Comment by agpaleoc** [comment]
Thank you very much, I appreciate it!
