### ISSUE TITLE
data base locked while windows application run

### ISSUE THREAD

**Issue by rifakmr1** [sqlitebrowser/sqlitebrowser#2657]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I'll close this as it doesn't contain any information to assist.
@rifakmr1 - Please comment back so we can troubleshoot this.
