### ISSUE TITLE
Cannot Open a Project From the Command Line

### ISSUE THREAD

**Issue by CecilWesterhof** [sqlitebrowser/sqlitebrowser#2658]
What is your question
-----------------------

When I run:
    sqlitebrowser Databases/project.sqbpro

sqlitebrowser is started as if no parameter was given.
When I then open the same project file from within sqlitebrowser it opens the project without a problem.
(So it is not a problem with the project file.)

When I run:
    sqlitebrowser Databases/project.sqlite (the database of the project)

The database is opened without problems. So I can open a database from the command line, but not a project.

This is with 3.10.1 on Debian 10.

**Comment by chrisjlocke** [comment]
I don't think 3.10.1 supported opening project files via the command-line - it was only introduced in a newer version.  Not 100% sure, but it may only be in the nightlies - unsure if it was put into the 3.12.1 release.

Can you build a newer version from the source?

**Comment by CecilWesterhof** [comment]
Should be possible. I will look into it.

**Comment by chrisjlocke** [comment]
Our downloads page gives download instructions for Debian, but it doesn't say what version is available.
https://sqlitebrowser.org/dl/#debian

Unsure if following that would give you a better version than 3.10.1.

**Comment by scottfurry** [comment]
Debian packaging seems a touch out of step. Buster (current stable) shows 3.10.1 while Sid (experimental) is at 3.12. See [here](https://packages.debian.org/search?keywords=sqlitebrowser&searchon=names&suite=all&section=all) for details.

**Comment by CecilWesterhof** [comment]
That is standard for Debian. They find stability very important.
Instead of fetching it from experimental, it is better to take it from testing. That is also 3.12.1-2.

**Comment by CecilWesterhof** [comment]
With 3.12.1-2 opening a project from the command line works. But it also breaks some things. (I installed from testing on a less important computer.) Looking into how easy it is to repair before I decide for the upgrade on my main system.

**Comment by chrisjlocke** [comment]
Are the 'But it also breaks some things' known issues?  Admittedly there are 400+ 'known issues', but if they're significant, feel free to raise them and increase their awareness.

**Comment by chrisjlocke** [comment]
Technically, this issue can be closed, but feel free to comment further or raise other issues if the 3.12.x version is causing problems.

**Comment by CecilWesterhof** [comment]
The problem is that mixing stable and testing gives problems. But that is a debian and not a sqlitebrowser problem.
It seems that completely going to bullseye (testing) works. And because bullseye will become stable in about half a year I do not see it as a problem.
(Get also newer versions of python, tcl and ffmpeg. And the kernel goes from 4 to 5.))
