### ISSUE TITLE
How to change font size for SQL log

### ISSUE THREAD

**Issue by IGRACH** [sqlitebrowser/sqlitebrowser#2659]
I'm unable to find option to change font for "SQL log":

![image](https://user-images.githubusercontent.com/7463331/113868046-4177ab80-977d-11eb-8fe9-a68096a101ed.png)

Winows 10-1909
DB Browser for SQLite 3.12.0 Portable

**Comment by chrisjlocke** [comment]
I don't think you can, to be honest.  That setting isn't available.

**Comment by chrisjlocke** [comment]
Oops, I didn't try hard enough.
Click 'Edit' and 'Preferences'.  On the 'SQL' tab, change the 'Sql editor font size'.

![image](https://user-images.githubusercontent.com/7872218/114672763-67f99180-9cfd-11eb-917c-b8bccbc6849d.png)
