### ISSUE TITLE
File Filter In The FileOpenDialog

### ISSUE THREAD

**Issue by jonorozcoc** [sqlitebrowser/sqlitebrowser#266]
The FileOpenDialog show all files in all formats. The SQLite formats are: *.db, *.sqlite, *.sqlite3, *.db3. Is it possible to add the filter? 

Note: I'm Colombian, My English Is Bad.

**Comment by justinclift** [comment]
Which operating system are you using? :smile:

If you are using MacOS X, this is a known problem. :anguished:

We did have filters, but they don't work with Qt on OSX (a Qt bug).  So we made it do *.* instead. :frowning:

If you're not using OSX though.. this is a new bug and we should investigate it. :smile:

**Comment by jonorozcoc** [comment]
I'm using Windows 7 Ultimate Edition.

**Comment by glawrence** [comment]
I have just downloaded a Windows nightly build (23-Apr-2015 02:15) and I only see one file filter, "All Files (*.*)". So on Windows 7 I get the same. From looking at the code it would seem the filters were removed for all platforms but I might be wrong.

**Comment by justinclift** [comment]
That'll need fixing then. :smile:

**Comment by samir-aguiar** [comment]
Just to make sure, you are talking about the dialog from "File > Open Database...",  right?

**Comment by glawrence** [comment]
I was and I assume @jonorozcoc was as well. However don't forget, it needs to be Windows and Linux only @samir-aguiar as per the comments from @justinclift

**Comment by samir-aguiar** [comment]
Alright, could you guys test it please? :smile:

**Comment by samir-aguiar** [comment]
Oh, tomorrow btw, after the next nightly build.

**Comment by jonorozcoc** [comment]
What version of Qt are using?? This issue is solved on MacOSX in the latest version.

**Comment by samir-aguiar** [comment]
Yeah, but I think it's only fixed on Yosemite. Could you confirm that, @justinclift? I don't run Mavericks anymore. :smile:

**Comment by justinclift** [comment]
k, what do you want/need me to test? (kind of hard to tell atm) :wink:

**Comment by glawrence** [comment]
I have tested the latest nightly build (24-Apr-2015 02:19) on Windows and I get a filter in the open dialog when I do "File -> Open Database...". I guess @justinclift someone needs to test on Linux and Mac.

**Comment by samir-aguiar** [comment]
@justinclift you're right, that was confusing. :smile: 
So, apparently the bug we had on #230 is gone on Yosemite, but I'm not sure if that's due to some Qt update and if it's also fixed on Mavericks as well. I'll send you a release of DB4S through e-mail, then can you please test if the bug from #230 is still there?

**Comment by justinclift** [comment]
@samir-aguiar Thanks Samir.  Just tried it here on OSX 10.9.5... and no change.  Still busted here for older OSX releases. :frowning:

Maybe change the conditional to allow filters on OSX 10.10 and above?

**Comment by MKleusberg** [comment]
Closing this as the original issue has been solved a long time ago :smile:
