### ISSUE TITLE
group_concat with distinct and seperator results in an error

### ISSUE THREAD

**Issue by ookami125** [sqlitebrowser/sqlitebrowser#2662]
I've searched for solutions to this issue a few times. All solutions that I found no longer work, don't work when column1 already contains commas, or are just rewrite the command to something else. My only guess is support the SEPERATOR keyword or allow `DISTINCT column1` to be wrapped in parenthesis.

#### What did you do?
Ran a command similar to
```sql
select group_concat(DISTINCT column1, '|') from example_table
group by column2;
```

#### What did you expect to see?
I expected to get a concatenated list of distinct value seperated by a pipe

#### What did you see instead?
```
Execution finished with errors.
Result: DISTINCT aggregates must have exactly one argument
At line 1:
select group_concat(DISTINCT column1, '|') from example_table
group by column2;
```

#### What operating system are you using?

- [x] Windows: ( _version: Windows 10 Home v10.0.19041 Build 19041 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [x] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?q=is%3Aissue+DISTINCT

**Comment by chrisjlocke** [comment]
Are you sure **group_concat** is a SQLite function?  Doing a search on it only brings up mySql examples.

**Comment by ookami125** [comment]
I mean this on its own works, so I have to assume it's supported function.
```sql
select group_concat(column1, '|') from example_table
group by column2;
```

**Comment by chrisjlocke** [comment]
This 'answer' would suggest it's either a subquery or replace - they're you're only options.
https://stackoverflow.com/questions/18285713/how-to-avoid-duplication-in-group-concat

This isn't an issue with DB4S, but with SQLite, as it doesn't support a delimiter when using GROUP_CONCAT(DISTINCT.

**Comment by ookami125** [comment]
Okay I can attempt those, I wanted to avoid expanding the query as it has already grown quite complex. Oh well, thanks for the help and suggestion.

**Comment by chrisjlocke** [comment]
Another answer would be to use a temporary table, or just another table.  Create a table, shove your distinct values in it, then you can run your group_concat on it using whatever delimiter you want.

**Comment by i-s-o** [comment]
As an alternative to a temporary table you can also use a common table expression (CTE). So, your example can be turned into this:
```
with cte as (
  select distinct column1
  from example_table
)
select group_concat(column1, "|")
from cte
```

**Comment by chrisjlocke** [comment]
Cool tip!  Thanks @i-s-o .  Never really used CTEs before.

**Comment by i-s-o** [comment]
> avoid expanding the query as it has already grown quite complex

I kept my previous answer short to introduce CTEs as an alternative. However, in practice, I use a two step process to deal with *complex queries*, e.g.:
```sql
with recursive pretend_complex_query (seq, rnd) as (
  select 1, abs(random() % 10) + 1
  union all
  select seq + 1, abs(random() % 10) + 1 from pretend_complex_query where seq < 50000
)
, cte_distinct as (
  select distinct rnd
  from pretend_complex_query
  order by rnd
)
select group_concat(rnd, "|") as rnd_list
from cte_distinct
;
```
This way, I keep the *complex query* untouched by turning it into a CTE, then add a second CTE to get the distinct values, and finally I run the `group_concat()` with a separator of my choice.

**Comment by chrisjlocke** [comment]
I'll close this, as this isn't a problem with DB4S, and has been resolved via workarounds.
