### ISSUE TITLE
Close Fold SQL

### ISSUE THREAD

**Issue by rafaelbarata** [sqlitebrowser/sqlitebrowser#2664]
Need close tab SQL without ask to save or save always.

**Comment by chrisjlocke** [comment]
This option?

![image](https://user-images.githubusercontent.com/7872218/114735532-2b4d8a80-9d3d-11eb-8fb7-6696ef126a7c.png)

Edit - Preferences - General tab.

**Comment by rafaelbarata** [comment]
My version 3.12.1 x64.
Don't have that option.

Thanks.



[image: image.png]







Em qua., 14 de abr. de 2021 às 12:20, Chris Locke ***@***.***>
escreveu:

**Comment by chrisjlocke** [comment]
Aah.  That might be a new option then.  I don't keep up that well with features that are in the live version compared to the development version.

Can you download the development version?
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

If you download the ZIP, extract it, then simply run the .exe in the directory, you don't need to install it.  It won't interfere with the live version you have.

**Comment by rafaelbarata** [comment]
It worked 100%. Thanks.

Em qua., 14 de abr. de 2021 às 13:27, Chris Locke ***@***.***>
escreveu:

**Comment by chrisjlocke** [comment]
Glad you got it working.  👍
