### ISSUE TITLE
Error importing data

### ISSUE THREAD

**Issue by myangelaku** [sqlitebrowser/sqlitebrowser#2665]
#### What did you do?
Try to import an SQL dump from https://data.ppy.sh

#### What did you see instead?
![](https://myangel.aku.lu/2zgrbiwrsr8k.png)

#### What operating system are you using?
Windows 10.0.19042

#### What is your DB4S version?
3.12.1
3.12.1.99 (Nightly)

#### Did you also
Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
Yes.
Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20
Yes.

**Comment by chrisjlocke** [comment]
Unfortunately, DB4S can only import SQLite compatible files.  These dumps appear to be MySQL dumps.  While there is a standard (of sorts) within SQL engines, there are still little quirks and differences.  

All this garbage at the start of the SQL file can be removed.

```
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
```

Between the drop table and create table, there is also noise.

```
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
```

You then have various data issues.
Eg:
```
`name` varchar(200) NOT NULL,`
```

SQLite doesn't support 'varchar' - it only supports text, numeric, integer, real and blobs.

How many tables are you importing, and what for?  If you're editing them to export again, then that's not going to work out so well.  Ideally, you need a MySQL editor, not an SQLite editor.
There are some tools to tweak the MySQL to get it working to import, but it depends on what your goals are.

**Comment by chrisjlocke** [comment]
In an ideal world, DB4S would read this as a MySQL dump and display a better error, or at least point you to a Wiki page.  I'm tempted to add an 'enhancement' tag, but with >400 open issues, it would be low priority and there are better things at the moment to resolve and correct.  Maybe one day... ;)

**Comment by myangelaku** [comment]
>  These dumps appear to be MySQL dumps
Oh gosh, sorry I didn't know ^^'

>  How many tables are you importing, and what for? 
Just to play around with the data, not sure how many tables they were

**Comment by chrisjlocke** [comment]
No problem! 😁
There are numerous tools to convert from mySql to SQLite, eg, https://pypi.org/project/mysql-to-sqlite3/
Depending on what you're importing, it can be easier to build the tables yourself, copy the import commands (which should normally work OK - they're normally standard) and you're away.

The benefit of SQLite is that you don't need a server to run the database.
I assume these aren't your dumps - if you've access to the original MySQL database, you can export cleaner SQL.

**Comment by chrisjlocke** [comment]
I'll close this as there hasn't been any further input and the error is more in the dump files than DB4S itself.
@myangelaku - yell back if you have any further input and need this to be re-opened.
