### ISSUE TITLE
password

### ISSUE THREAD

**Issue by gracetung** [sqlitebrowser/sqlitebrowser#2668]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Hi @grace841129 was this created accidentally, or do you need assistance with DB Browser for SQLite? :smile:

**Comment by grace841129** [comment]
Sorry, I created it accidentally. Please just delete it, thank you.

**Comment by chrisjlocke** [comment]
No problem.  🙂
