### ISSUE TITLE
"Right click --> browse table" doesn't work for attached database

### ISSUE THREAD

**Issue by kobylevin14** [sqlitebrowser/sqlitebrowser#2669]
Details for the issue
--------------------

#### After delay, Browse opened, but with a different table. (It was from the main database, not the attached database)

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.3.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Could you try 3.12.1, or the nightlies?  (there are mac flavours of those).
This seems to work in the nightlies, so might have been fixed from the 3.12.0 version you're using (which is technically one version out).

**Comment by chrisjlocke** [comment]
I'll close this, as this issue seems fixed, and there has been no response.
@kobylevin14 - this can be re-opened if you respond back saying it's still broken in the latest version.
