### ISSUE TITLE
Load spatialite extension?

### ISSUE THREAD

**Issue by giumas** [sqlitebrowser/sqlitebrowser#267]
Can I load the spatialite extension module? I have attempted using "Load extension" but I got "Error loading extension: The specified module could not be found".

**Comment by justinclift** [comment]
As a thought, which OS are you using, and which version of DB4S and the SpatiaLite extension?  (not sure if it makes a difference, but it's helpful to know)

**Comment by giumas** [comment]
I am on Win7 x64. For the DB4S (x86) version, I attach a screenshot with the about:
![dbbrowser_version](https://cloud.githubusercontent.com/assets/2849257/7254833/67d23f2c-e813-11e4-94a8-93419a8bc757.PNG)

For the spatialite extension, I am using the last stable (4.2.0): http://www.gaia-gis.it/gaia-sins/windows-bin-x86/

I am not sure that I am properly using the application .. I was not able to find documentation on the "load extension". However, to reproduce my error, I open DB4S, then I create a dummy table and I try to "load extension" selecting the dll in a folder where I unzipped the 7z archive:

![dbbrowser_error](https://cloud.githubusercontent.com/assets/2849257/7254834/69d50e76-e813-11e4-988c-62fd14a1ca49.PNG)

**Comment by justinclift** [comment]
Hmmm yeah, I'm not sure either.  @MKleusberg or @rp- may know more... :smile:

**Comment by roemhildtg** [comment]
I'm having this problem also. I am trying to load the ST_Geomtry extension for ArcGIS:

http://desktop.arcgis.com/en/arcmap/latest/manage-data/databases/spatially-enable-sqlilte.htm

I've added all the PATH's and the command works via command line sqlite3, but not in the browser.

**Comment by justinclift** [comment]
Hmmm, as a thought, is the extension a .dll file?  If so, copying it into the same directory as the sqlitebrowser.exe file might let it be found.

No guarantees, but it's worth a shot. :smile:

**Comment by jimothyr** [comment]
I am having the same problem. I have tried the same directory approach , and no dice..

Win7 x64    db version  3.8.0

**Comment by justinclift** [comment]
It sounds like we'll need to investigate this properly after the 3.9.0 release.

**Comment by zhm** [comment]
I ran into this same issue and I finally got it to work. It has to do with the library search paths on Windows because `mod_spatialite` in turn loads its own dependent DLLs that reside in the same directory as `mod_spatialite.dll`.

I got it working 2 different ways:

1.) Add the directory containing the spatialite `.dll` files to your %PATH%. Windows searches `%PATH%` for dll files so it will be able to locate it.
2.) Copy the `.dll` files to the same directory containing `DB Browser for SQLite.exe`. e.g. `C:\Program Files\DB Browser for SQLite` or `C:\Program Files (x86)\DB Browser for SQLite` whichever version you have installed (32bit or 64bit). You will also want to make sure you use the correct x86 or x64 dll files that correspond to the version of sqlitebrowser you have.

This works because Windows searches for .dll files in `%PATH% and the current application directory. So putting them in either place works.

If `mod_spatialite` were shipped as fat binary containing _everything_ in a single dll file I don't believe this would be necessary and it would just work pointing it at the dll, but until then we have to make sure all of the .dll's are located somewhere Windows will search when loading shared libs.

**Comment by justinclift** [comment]
@zhm That's pretty awesome. :smile:

Any interest in cutting-n-pasting that into a wiki page, for better visibility of the info?  It's seems like pretty arcane knowledge that others would definitely benefit from.

**Comment by zhm** [comment]
I added a new page.

https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows

**Comment by zhm** [comment]
I think this issue can be closed because it's definitely not an issue with DB4S. I don't believe there's anything to be done other than making a more location-independent build of `mod_spatialite`.

**Comment by justinclift** [comment]
Fantastic!  Added a link on the front page of the wiki pointing at it, so it should be much easier for people to find now.  Thank you heaps Zac. :smile:

**Comment by ranaalisaeed** [comment]
I have tried both options proposed by @zhm   but still get the same error!

**Comment by zmarty** [comment]
@ranaalisaeed I also just tried and I cannot get it to work. I made sure to use the 64 bit plugin for the 64 bit version of DB Browser. I copied the files under "C:\Program Files\DB Browser for SQLite" and I am also getting the "Error loading extension" error.

**Comment by justinclift** [comment]
@zhm Would you have time to help these guys out?  Sounds like it's more than just a once-off problem that's happening.  eg probably useful to figure out the cause + solution, and update things (docs, whatever) as needed so future people don't hit it.  Or least have a workaround for it. :smile:

**Comment by allspatial** [comment]
Same here with the latest version of DB4S and mod_spatialite on Windows 10 (x64). Neither of the options provided by @zhm helps. Many thanks for looking into this!

**Comment by karim** [comment]
@ranaalisaeed @zmarty @allspatial I'm not familiar with spatialite extension, but I followed @zhm instructions and it worked.

I tested on Windows 7 SP1 (64-bit) using the latest stable version (v3.10.1) and latest nightly version. It should be something like this..

1. Download http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-4.3.0a-win-amd64.7z

2. Extract **all** DLL files to DB4S folder

![spatialite2](https://user-images.githubusercontent.com/8761081/41065710-cf4b2b86-69df-11e8-93fb-4de25646cb34.jpg)

3. Open any database and select `File > Load extension` from the menu

4. Locate `mod_spatialite.dll` inside DB4S folder and select it

![spatialite](https://user-images.githubusercontent.com/8761081/41065950-8bfc832e-69e0-11e8-9bff-4c65e9b33a70.jpg)

**Comment by karim** [comment]
Hello Michael, I'm guessing it could be a dependency problem. Some DLLs might be missing. To find out which, you can download Dependency Walker.

1. Download the app from http://www.dependencywalker.com/depends22_x64.zip
2. Open it and select `File > Open...` from the menu.
3. Locate `mod_spatialite.dll` and select it.

Now the application will show you all DLLs that `mod_spatialite.dll` depends on. If you see something like this..
![dw2](https://user-images.githubusercontent.com/8761081/41082127-897d818c-6a2d-11e8-86c6-96b2e568b047.jpg)
... it means these files are missing.

**Comment by justinclift** [comment]
@allspatial Just to double check, which version(s) of DB4S have you been trying with? :smile:

**Comment by justinclift** [comment]
Oh... I wonder if it might be something Windows 10 is doing to the .dll?

I remember seeing cases of other applications where Windows does weird things, as part of it's attempt to keep people safe.

If you right click on the dll (eg mod_spalialite.dll) in Windows Explorer, and choose Properties, is there an "Unblock" button near the bottom?  If there is, it'll be near the "Read only" checkbox. :smile:

**Comment by allspatial** [comment]
Hi @justinclift, there is no Unblock button shown so I assume the dll is not blocked. I attached a screenshot regarding the DB4S version. Many thanks!

![shot](https://user-images.githubusercontent.com/12534211/41157531-1647bf10-6b37-11e8-9b52-d142c9bac44e.jpg)

**Comment by justinclift** [comment]
No worries, it was worth checking just in case.

Hmmm, would you be ok to try a nightly build and see if there's any difference?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

Btw, are you running 32 or 64-bit Windows?

With the nightly builds, we're in the process to switching over the providing .msi files instead of .exe.  The installed result (in theory) should be identical, but the .msi's are somewhat more preferable technically. :smile:

**Comment by karim** [comment]
@allspatial Searching around about this extension and Windows 10 keeps pointing to `libstdc++-6.dll`. Spatialite seems to include an older version of it, which works fine in Windows 7 but not Windows 10. This file comes from MinGW, the compiler they use to build the extension with.

Now we will try to replace the old one with a newer version..

1. Delete `libstdc++_64-6.dll` from DB4S folder
2. Go to https://sourceforge.net/projects/mingw-w64/files/ and download one of **x86_64-win32-seh** files
    - Or use this direct link [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-win32/seh/x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z)
3. Extra it somewhere and look into the `bin` folder
4. Copy both `libstdc++-6.dll` and `libgcc_s_seh-1.dll` to DB4S folder
5. Rename `libstdc++-6.dll` to `libstdc++_64-6.dll`
6. Try to load the module again

Credit goes to http://blog.jrg.com.br/2016/04/25/Fixing-spatialite-loading-problem/

**Comment by stephan-br** [comment]
Thanks all, had the same issue can confirm the fix

**Comment by justinclift** [comment]
Excellent!

Good stuff @karim, those steps are now cut-n-pasted into the SpatiaLite page on the wiki for future Win10 users:

* https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows#workaround-for-windows-10-failure

**Comment by karim** [comment]
@allspatial @stephan-br I'm glad it's working fine for both of you. :smiley: 

@justinclift Thanks for the wiki update. :+1:

It is not an optimal solution though. Having users download the extension then download unrelated ~50mb package, install another unrelated program (7-zip) to extract it (to a ~450mb folder), just to get 2 files doesn't look like a good solution.

Is it better if we (also reads as you :smile:) contact the author of the extension to update these DLLs? Or maybe we offer this extension (and maybe later others too) as .zip download in the releases section? Or bundle it with DB4S if it is not going to affect other users, since extensions are usually optional.

**Comment by justinclift** [comment]
@karim It looks like the author of the blog post you linked to already did that.  The conclusion of the blog post mentions bringing it up on the [spatialite users](https://groups.google.com/forum/#!topic/spatialite-users/u2QZpQL_6ek) mailing list.

Co-incidentally, I was wondering the other day (re: MSI installer) if we should maybe bundle useful .dll's for people, and give them a checkbox in the installation as to whether to install them.

I'm not sure how big (file size) just the needed SpatiaLite .dll's are.  If they're small (less than 1MB total?) it wouldn't do bad things to our file size.  Our downloads are smaller by 5MB now anyway with the new MSI approach. :smile:

**Comment by karim** [comment]
Yes, I'm also thinking it might be useful to include some SQLite extensions with DB4S.

SpatiaLite contains 12 DLLs with a total size of 15MB. When added to the MSI it increased its size by 4MB. So it is now close to its original size.

I'm thinking maybe we can build it ourselves, to get rid of some of its dependencies. It includes its own copy of SQLite. Or statically link all these DLLS to it to minimize its size.

But for now, we can do one of these..

1. Bundle it (and other extensions we find useful) with DB4S installer (Full version)
2. Same as 1 but also create another MSI without extensions like current one (Lite version)
3. Create a new MSI installer for each extension, that will be installed only if DB4S is installed first
4. Just .zip it and include it in the releases page (along with other popular extensions)

**Comment by justinclift** [comment]
Been thinking this over.  Personally, I reckon it's kind of nifty that our .msi sizes are now noticably smaller than the .exe's.  Seems like a shame to immediately pad them back out. :smile:

From that list, option 3 sounds optimal to me.  We could include some links at the bottom of the Release Notes page, something like this:

---

## Downloads

* DB Browser for SQLite [win/osx] [...]

### SpatiaLite extension

* Windows 64-bit <-- direct link to the new 64-bit msi
* Windows 32-bit <-- direct link to the new 32-bit msi
* OSX <-- we can think about this one later

Hmmm, I wonder if we could have both the 32 and 64 bit .dlls in just one msi, and it figures out which ones to install?

With the above approach, after a release or two we'd have some idea of how many people are downloading + installing it as well.  That might be useful for future planning purposes too. :smile:

eg If (say) 80% of people are downloading it, then we might as well bundle it after all. :smile:

**Comment by karim** [comment]
Okay, I will try to create a MSI for SpatiaLite and will make a PR when it is ready.

**Comment by barbalex** [comment]
I am a JavaScript/Flutter dev. Know nothing about c. I have spent two days trying to get a working sqlite database with spatialite built/compiled. On Windows or macOS. To no avail. I would LOVE to be able to download an msi for sqlitebrowser with spatialite.

**Comment by chrisjlocke** [comment]
Have you followed the instructions here?
https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows#workaround-for-windows-10-failure

Simply download the binaries, plop them in the DB4S folder, and you should be good to go.
I can't provide an MSI, but can provide a .ZIP file if you're really stuck.

**Comment by barbalex** [comment]
@chrisjlocke Thanks so much! A few minutes ago I actually finally managed. It seems that I downloaded the wrong binaries. In the end I used these: http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/mod_spatialite-5.0.1-win-amd64.7z 

I guess being a complete noob and with the binaries seemingly hard to find that is rather likely to happen.

**Comment by chrisjlocke** [comment]
OK, just make sure you're happy with the 64-bit version - see the links I posted.  It mentioned about having to download alternative DLLs...
Glad you got it working.  👍

**Comment by barbalex** [comment]
This may be a very dumb question: Isn't the loaded extension supposed to persist? I naturally assumed that. But I now realized that I have to load it every time I open the database or it's functions will not be usable.

How can I make the extension persist?

**Comment by chrisjlocke** [comment]
If you click 'Edit' and 'Preferences', then go to the 'Extensions' tab (1), then click the icon on the right (2) that has a little plus sign, you can load extensions that'll load for every database.  👍

**Comment by barbalex** [comment]
@chrisjlocke Thanks a lot, that works.

After reading up on extensions I have the impression that the extension will now be loaded by DB4S every time I open the database file. As opposed to: The extension is present, whatever software opens the db file. As if it were baked into the file.

So if I use for example [sqflite](https://pub.dev/packages/sqflite) in flutter to open the same database file the extension will not be present unless I find a way to load it every time sqflite opens the database file, using dart. Maybe using [dart::ffi](https://flutter.dev/docs/development/platform-integration/c-interop).

I realize you may not know dart/flutter enough but does the principle seem correct?

**Comment by justinclift** [comment]
> I thought project files might be the answer too, but apparently not.

If there's a sensible use case for it, and we can think of a way to add it in a non-confusing fashion, the code itself probably wouldn't be too hard to add.

**Comment by chrisjlocke** [comment]
> If there's a sensible use case for it

If opening a database relies on extension A, B and C, then it *kinda* makes sense...
Guess you could just attach every extension as persistent anyway - I don'r know how much overhead that gives DB4S - ie, it won't load the function/module until you use that function, etc.

**Comment by chrisjlocke** [comment]
> but does the principle seem correct?

@barbalex - extensions are purely for DB4S.  If you want them for other projects, then that project will need to use that extension too.  I believe you can bake it into sqlite3.exe itself, but I just tried the sqlite3.exe that came with mod_spatialite and that didn't work out - I might have to enable the extension first ... not sure.  But for my VB applications for example, that uses its own SQLite library which is totally outside everything DB4S uses.  Enaabling and adding extensions has no effect on the actual physical database file which other applications can access.
Hope that makes sense.
How does sqflite access an SQLite file - via its own library, its own copy of sqlite3.exe, etc?

**Comment by barbalex** [comment]
@chrisjlocke Yeah, makes sense.

Sqflite uses whatever the platform (Android, iOS) provides (https://github.com/tekartik/sqflite/issues/70#issuecomment-399878769). I am not sure if it will be possible to load spatialite under these circumstances, even if dart:ffi seems to let me run c code. Will have to try, I guess.

**Comment by chrisjlocke** [comment]
You're loading it in the preferences section, as per this comment?
https://github.com/sqlitebrowser/sqlitebrowser/issues/267#issuecomment-815549428

**Comment by stuartong** [comment]
@chrisjlocke yes i followed those steps but was unable to load the extension

**Comment by chrisjlocke** [comment]
> but was unable to load the extension

Can you send a screenshot of the error you get?  What operating system are you using?  What DB4S version are you using?

**Comment by ThoKau** [comment]
Doesn't work her.
Testing with nighly DB4S-version and Spatialite 5.0.1.
Copied all dll files from MinGW-DL in all 3 possible folders, tried 32, 64, 32 in 64. Nothing works.
Crap.

**Comment by justinclift** [comment]
Ok, it sounds like we'll need some assistance from a specialist that knows GIS stuff.

@sandman7920 Are you able to help out here, and get things working? :smile:

**Comment by sandman7920** [comment]
@ThoKau is you are ok with spatialite-4.3.0a please look at #2538

You need to copy all dependencies into DB4S root folder or somewhere in the system path
dependencies:
```freexl.dll
geos_c.dll
geos.dll
iconv.dll
libxml2.dll
lwgeom.dll
proj_6_3.dll
```

Then **mod_spatialite.dll** should be loaded without problem.

**Comment by chrisjlocke** [comment]
I'll fire up a Win 8.1 virtual machine and have a look.

**Comment by chrisjlocke** [comment]
@ThoKau - Does it need to be Spatialite 5.0.1 - seems the osgeo files only go to 4.3.0a

**Comment by ThoKau** [comment]
@sandman7920:  Thanks!! freexl.dll from #2538 was missing, and libfreexl-1.dll too, at least for me.
After adding those 8 files to DB4S-folder and copying  all mod_spatialite-files too, it seems to run with latest versions.

SELECT 'SQLite version:' AS Lib, sqlite_version() AS Version
UNION SELECT 'Spatialite:', spatialite_version()
UNION SELECT 'GEOS', geos_version()
UNION SELECT 'spatialite_target_cpu', spatialite_target_cpu()
UNION SELECT 'FreeXL', freexl_version()
UNION SELECT 'Proj', proj_version()
UNION SELECT 'Proj4', proj_version()
UNION SELECT 'RTTopo', rttopo_version()
UNION SELECT 'LibXML2', libxml2_version()

returns a couple of versions in DB4S:

FreeXL	1.0.6
GEOS	3.9.0-CAPI-1.16.2
LibXML2	2.9.10
Proj	Rel. 7.2.1, January 1st, 2021
Proj4	Rel. 7.2.1, January 1st, 2021
RTTopo	1.1.0
SQLite version:	3.36.0
Spatialite:	5.0.1
spatialite_target_cpu	x86_64-w64-mingw32

**Comment by chrisjlocke** [comment]
@ThoKau - Where did you get the 5.0.1 files from?  I could only (albeit from the link above) see the older 4.3 version.

**Comment by ThoKau** [comment]
Oh, I'm too lazy to compile myself...  :-) 
http://www.gaia-gis.it/gaia-sins/   or  http://www.gaia-gis.it/gaia-sins/windows-bin-amd64/

**Comment by sandman7920** [comment]
@ThoKau now you have a mixture between MinGW/MSVC C/C++ runtime and sqlite3.dll/libsqlite3-0.dll DB4S/gaia-sins

osgeo4w provides [v2](https://download.osgeo.org/osgeo4w/v2/) repo which contains version 5.0.1 of the mod_spatialite.

**Comment by sandman7920** [comment]
OSGeo4W mod_spatialite-5.0.1 dependencies:
```
mod_spatialite.dll

charset-1.dll
freexl.dll
geos_c.dll
geos.dll
iconv-2.dll
jpeg12.dll
jpeg.dll
libcurl.dll
liblzma.dll
librttopo.dll
libxml2.dll
proj_8_0.dll
proj.db
tiff.dll
zlib.dll
zstd.dll
```

Optionally if don't have  [msvcrt2019](https://download.osgeo.org/osgeo4w/v2/x86_64/release/msvcrt2019/) and [OpenSSL](https://download.osgeo.org/osgeo4w/v2/x86_64/release/openssl/) installed system-wide you can get them from **v2 repo**

If you don't want to pollute the DB4S folder with external libraries (easy update for both DB4S and mod_spatialite),
create a new folder for example `D:\mod_spatilite`, copy all libraries there, and add the folder to the **user** or **system** path.

![DB4S_env](https://user-images.githubusercontent.com/3589417/128335595-bc29c032-4138-4bd6-992a-d9f539988273.png)

Then load mod_spatialite.dll from the newly created folder.
