### ISSUE TITLE
Display verbose error descriptions in the output window of the "Execute SQL" panel

### ISSUE THREAD

**Issue by agyates** [sqlitebrowser/sqlitebrowser#2674]
Display english language error descriptions in the output window of the "Execute SQL" panel.
For example: INSERT INTO table1 SELECT * FROM table2; should work if both tables have the same number and type of fields.
However, if table1.field1 is text and table2.field1 is integer and table1.field1 contains some non-numeric character then the display should read something like "Cannot convert non-numeric character into numeric type".

Example: Oracle Sql+ returns descriptive error messages.

**Comment by chrisjlocke** [comment]
I think we display whatever is returned back from SQLite.
In your example, because SQLite doesn't care about field types, you can happily store 'squishy lemons' in an integer field.

**Comment by MKleusberg** [comment]
@chrisjlocke is right. We just display whatever error message SQLite gives us. Unfortunately those aren't very descriptive all the time but there isn't much we can do about that. I'll close this issue then but feel free to reopen it if you think I've been to eager with this :smile:
