### ISSUE TITLE
csv import

### ISSUE THREAD

**Issue by priscillakonadu123** [sqlitebrowser/sqlitebrowser#2677]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
Hi,
I can see you've raised three issues regarding this (have closed the other two), but there are no details for the actual issue you're facing.
Can you explain what problem you're experiencing?
Can you also give the operating system you're using, and the version of DB4S you're using.

**Comment by chrisjlocke** [comment]
OK, I'll close this then.  Feel free to comment further and it can be re-opened if necessary.
