### ISSUE TITLE
Can not trigger double-click on data points in the plot view [sqlitebrowser-latest]

### ISSUE THREAD

**Issue by GarfieldCatMao** [sqlitebrowser/sqlitebrowser#2678]
#### What did you do?
Double click on data points in  plotDock/plotview can't trigger link to tabBrowser with DB browser built locally.
Building is based on the latest codes from the branch, sqlitebrowser-master. No matter how we click the data, it doesn't work.

#### What did you expect to see?
If we use 'no installer' version, everything is ok, by double-clicking the point in the view, the corresponding data will be emerged in the first row in that table, and we can instantly have a link between the data we are plotting and the position of the data in the table. So convenient 
DB Browser for SQLite - .zip (no installer) for 64-bit Windows

#### What did you see instead?
We expect to see that it can work with the version built by ourselves.

#### What operating system are you using?
QT 5.15.2
MinGW 8.1.0 64 bit

- [x] Windows: ( _version:_ _Win10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

Looking forward to your reply, thanks!

**Comment by chrisjlocke** [comment]
What file is 'DB Browser for SQLite - .zip (no installer) for 64-bit Windows' - if this is 3.12.1 then something has broken in the nightlies.  Where did you download it from?

**Comment by GarfieldCatMao** [comment]
> What file is 'DB Browser for SQLite - .zip (no installer) for 64-bit Windows' - if this is 3.12.1 then something has broken in the nightlies. Where did you download it from?

Yes, it's 3.12.1, and it's downloaded from the home page(homepage --> download page).
It's supposed that something is broken in the codes (latest codes of sqlitebrowser-master)

BR,
Garfield

**Comment by GarfieldCatMao** [comment]
Looks that this function is never called.

void QCustomPlot::mouseDoubleClickEvent(QMouseEvent *event)

**Comment by GarfieldCatMao** [comment]
Compared with 3.12.1, looks lots of things are being added to master branch. It's normal to have an issue like this.

It's good that I can use 3.12.1 before new version is released.

Thanks

**Comment by mgrojo** [comment]
This is fixed with Pull Request #2644. I think we can merge it, because it seems that many people are missing the feature. Whether it affects performance and how it can be prevented, can be analyzed later. I hope @MKleusberg has some time in the future to take a look into it.

**Comment by mgrojo** [comment]
@GarfieldCatMao could you try again, building from master or downloading the next nightly build, to confirm it works for you and that this issue can be closed?

**Comment by GarfieldCatMao** [comment]
> @GarfieldCatMao could you try again, building from master or downloading the next nightly build, to confirm it works for you and that this issue can be closed?

Thanks, building from master is ok now(double-click works).

For this feature itself, it's very recommended to be kept in latest version. It's very convenient for people who want to locate the data position in the table when he finds something interesting or abnormal in the plot view.

Last, still would like to say, plot view is the best among all that I've seen. 

Thanks again.

**Comment by chrisjlocke** [comment]
Excellent, thanks for confiming.  👍
