### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by NLRicker** [sqlitebrowser/sqlitebrowser#268]
Perhaps a feature rather than a bug.

I used an open-source conversion program to go from an SQL file to a SQLlite file.  That program left the data types in the table schema in their original SQL form.  One was a "bit" type.  Your browser seems to interpret that reasonably.  It displays as either 0 or 1.  When I run an sql command in your browser to select for 0 or 1, it works as expected.

But when I run the same command in SQLlite3, it never selects regardless of the bit value.

It appears that the browser is interpreting data types in a different way than SQLlite3.  So while the browser's liberal behavior is a nice convenience, it is misleading.  Perhaps the browser should display the type being used?  Or warn?

Otherwise, I'm very happy with it in my rather limited experience to date.

**Comment by justinclift** [comment]
Interesting.  This does kind of sound bug-ish, as we're trying to keep pretty close to the behaviour of SQLite3.

**Comment by NLRicker** [comment]
Hi Justin,

 

A few hours after sending that message I found that my test of SQLlite behavior was flawed.  I’m not sure the bit data type really behaves differently in the two contexts.  Now I’ve eliminated that data type from my DB so I can no longer test for it.

 

It seems to me that the most useful feature would be to display somehow the data type that will actually be used in SQLlite.  For example, my database also includes DateTime data types.  I’m wondering whether those are considered strings or blobs (or …?).

 

Anyway, it’s not an urgent concern.  I can work around as long as the behavior is consistent.

 

Thanks for responding,

Larry Ricker

**Comment by justinclift** [comment]
Well... displaying the data type that's going to be used for any particular column probably isn't going to work.  SQLite 3 doesn't really seem to enforce data types the same way that other databases do.

So, even if someone has (say) a column marked as REAL, if someone decides to try and insert "FOOBAR! WAS! HERE!" (a string) into a field in it... SQLite3 will accept that string and store it fine (as a string).  It will "just work".  In some ways this could be considered a good thing, in some ways it could be considered a bad thing.  Very much "depends how you look at it". :wink:

Further info, in case it's helpful: https://www.sqlite.org/datatype3.html
