### ISSUE TITLE
Different behaviour in evaluating checked constraints in "Browse Data" and "Execute SQL"

### ISSUE THREAD

**Issue by mbraeutigam** [sqlitebrowser/sqlitebrowser#2680]
Details for the issue
--------------------

#### What did you do?
The following was done using the SQLite JDBC driver and some dynamically generated SQL statements
- [x] created a table (fields VNK,NNK,VST,BST,...) with checked constraints
- [x] inserted data (with null)
Now the DB Browser comes into play
- failed to manually update one of the fields (VST,BST) to set NULL value using the Browse Data editor

#### Here are two test cases

1. Failing in Browse Data (setting NULL in editor) and working as expected in Execute SQL (setting NULL via SQL) - with OR'ed check constraint for fields VST,BST
```SQL
CREATE TABLE DB001005 (VNK TEXT CONSTRAINT DB001005_VNK CHECK(typeof(VNK)='text' and length(VNK)<=10 or typeof(VNK)='null'),NNK TEXT CONSTRAINT DB001005_NNK CHECK(typeof(NNK)='text' and length(NNK)<=10 or typeof(NNK)='null'),VST INTEGER CONSTRAINT DB001005_VST CHECK(typeof(VST)='integer' and VST>=0 or typeof(VST)='null'),BST INTEGER CONSTRAINT DB001005_BST CHECK(typeof(BST)='integer' and BST>=0 or typeof(BST)='null'));

INSERT INTO DB001005 (VNK,NNK,VST,BST) VALUES ('12345678','12345678',10,null);

-- running this in Execute SQL works, leave it out and try manually setting the field VST to a NULL value in Browse Data
UPDATE DB001005 SET VST=null;
```

2. Working as expected in both Browse Data and Execute SQL: setting NULL fails - without OR'ed check constraint for fields VST,BST
```SQL
CREATE TABLE DB001005_nonull (VNK TEXT CONSTRAINT DB001005_VNK CHECK(typeof(VNK)='text' and length(VNK)<=10 or typeof(VNK)='null'),NNK TEXT CONSTRAINT DB001005_NNK CHECK(typeof(NNK)='text' and length(NNK)<=10 or typeof(NNK)='null'),VST INTEGER CONSTRAINT DB001005_VST CHECK(typeof(VST)='integer' and VST>=0),BST INTEGER CONSTRAINT DB001005_BST CHECK(typeof(BST)='integer' and BST>=0));

INSERT INTO DB001005_nonull (VNK,NNK,VST,BST) VALUES ('12345678','12345678',10,10);

UPDATE DB001005_nonull SET VST=null;
```

#### What did you expect to see?
For test case 1: allowing me to set null value by pressing DEL key

#### What did you see instead?
![image](https://user-images.githubusercontent.com/4228180/116370746-fcd6b180-a80a-11eb-98eb-62e4cab448ea.png)

#### Some thoughts
To me it seems that parsing/evaluating the checked constraint which uses a combination of and & or expressions fails and thus the update is not executed in the GUI. As mentioned above: sending to the plain SQL to SQLite/the SQLite driver succeeds.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ 10 64bit)
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: nightly

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

EDIT 1: fixed top description (after "SQLite browser comes into play")
EDIT 2: added comment "-- running this in Execute SQL works, leave it out and try manually setting the field VST to a NULL value in Browse Data" to first test case
EDIT 3: added edit history

**Comment by chrisjlocke** [comment]
DB001005_VST is failing as you don't have a null check on that - you do on the others.
When you add a new record, DB4S adds in a record with all NULLS, then you add the values as required.  If you add a check, then it should work.
You can't set the cell to null, as the constraint is not set for that - only numeric values.

**Comment by chrisjlocke** [comment]
> failed to manually update one of the fields (VST,BST) to set a numeric value (eg. 10) using the Browse Data editor

Using your CREATE statement as provided (no amendment), this worked fine for me.

![image](https://user-images.githubusercontent.com/7872218/116393141-2e567980-a819-11eb-8998-e34c41fa7abe.png)

**Comment by chrisjlocke** [comment]
Wasn't sure how the constraints were being interpreted, so added more brackets to ensure it was how you actually wanted it.

**Comment by mbraeutigam** [comment]
@chrisjlocke Thank you for your fast response!
First comment: DB001005_VST has a null check on it, so I should be able to edit the cell after running my statements... 
Funny thing: Pressing DEL key on the cell of column VST drops error, even if I ran the third statement (SET NULL) of test case 1 and set the field already to NULL.

Your second comment is correct, that was an error at the top of my description - I meant setting it to null, the description of the test cases was correct "(setting NULL in editor)". Sorry for that, I updated the top post and added some edit notes at the bottom.

My point is, that there seems to be a slightly different behaviour in parsing/evaluating the constraint by the sqlite driver itself versus the gui of the sqlite browser editor.
To be a bit more concise: IMHO the boolean AND operator has a higher order than the OR operator, so it should usually not be neccessary to put brackets around the two operands of the AND statement. That different evaluation causes the statement to run in Execute SQL but drops an error message before executing the update (which would be executed correctly).

BTW: [SQLite Studio](https://sqlitestudio.pl/) seems to interprete my CHECK CONSTRAINT correctly. After changing the cell and commiting the changes, data is written as expected. 
The SQLite driver for Java (JDBC) does the same and allows me to update to NULL in DB001005.
Even SQLite Browser allows this in Execute SQL tab, but not in the Browse Data.

I hope, I could clarify things now 😄

**Comment by chrisjlocke** [comment]
I'm guessing it's how the browse table uses parameters.  DB4S doesn't log the full SQL, but it gives half - 
```
[UPDATE "main"."DB001005" SET "VST"=? WHERE "_rowid_"='1']:
```
It does it to both integer fields, not text, so guessing it's failing on that.

Again, adding brackets made it work, so unsure if it's a problem or not.   Unfortunately the error just states it failed and on which constraint, and doesn't specify exactly why and on what part.  If brackets work, then .... well, at least it works! 😁😊

**Comment by mbraeutigam** [comment]
Unfortunately editing/clearing (= pressing DEL on VST cell in Browse Data) doesn't work either after adding brackets to SQL... 😢 

```SQL
CREATE TABLE DB001005 (VNK TEXT CONSTRAINT DB001005_VNK CHECK(typeof(VNK)='text' and length(VNK)<=10 or typeof(VNK)='null'),NNK TEXT CONSTRAINT DB001005_NNK CHECK(typeof(NNK)='text' and length(NNK)<=10 or typeof(NNK)='null'),VST INTEGER CONSTRAINT DB001005_VST CHECK((typeof(VST)='integer' and VST>=0) or typeof(VST)='null'),BST INTEGER CONSTRAINT DB001005_BST CHECK((typeof(BST)='integer' and BST>=0) or typeof(BST)='null'));

INSERT INTO DB001005 (VNK,NNK,VST,BST) VALUES ('12345678','12345678',10,null);
```

**Comment by chrisjlocke** [comment]
Doh.  It does work, but we've been knobbled by something obvious.
Pressing Delete doesn't set the cell the NULL - it sets it to a blank value (text).  
To enter a NULL value, right-click and select 'Set to Null'

![image](https://user-images.githubusercontent.com/7872218/116431027-47722100-a83f-11eb-8305-4c3a5cc3eca4.png)

Or press Alt+Del.

That works.  
And yes, without that bracket nonsense - you were probably right about that.

Sorry I led you down the wrong path!

**Comment by mbraeutigam** [comment]
Interesting fact, that DEL sets a blank string value. So I guess, we're done here 👍
I'm closing the ticket. Thanks heaps for your response!
