### ISSUE TITLE
Adicionar Coluna com porcentagem

### ISSUE THREAD

**Issue by jornalistaCarlosOsorio** [sqlitebrowser/sqlitebrowser#2682]
What is your question
-----------------------

Como faço para criar código para calcular porcentagem simples com duas colunas?

SELECT
Coluna 01,
Coluna 02,
Porcentagem
FROM NOME_DO_ARQUIVO

Realizei algumas tentativas, mas não obtive sucesso. Alguém pode me ajudar?

**Comment by justinclift** [comment]
Does something like this help? :smile:

https://stackoverflow.com/questions/7863724/simple-math-calculation-with-sqlite-android

(Sorry for the English-only answer :innocent:)

**Comment by chrisjlocke** [comment]
This was answered in the discussion area...
https://github.com/sqlitebrowser/sqlitebrowser/discussions/2685

Didn't spot this was opened here too...
