### ISSUE TITLE
not sure if this is already included but a way to merge databases would be really awesome if you con already do it can someone please explain

### ISSUE THREAD

**Issue by BigFatDecker** [sqlitebrowser/sqlitebrowser#2688]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
How many tables?
The same data (columns) from both tables?  You can attach another database and just do a couple of 'insert into X select * from Y' statements.
With more information I can give an example.

**Comment by chrisjlocke** [comment]
I'll close this as it hasn't had any response, and issues with 99.8% of the issue in the subject with no other details looks a tad suspicious.
@BigFatDecker - Feel free to comment and this can be reopened if necessary.
