### ISSUE TITLE
3.6.0 install problem on Windows

### ISSUE THREAD

**Issue by cnromaine** [sqlitebrowser/sqlitebrowser#269]
When trying to update to 3.6.0 in Windows 8.1, I get the following message "This application failed to start because it could not find or load the Qt platform plugin 'windows'. Reinstalling the application may fix this problem ".) 
![image](https://cloud.githubusercontent.com/assets/207884/7359648/aecd31fc-ed0e-11e4-9387-a474f0f0c8ca.png)
Tried to install both the 32 bit and 64 bit versions for Windows. Version 3.5.1 installs fine and runs.

**Comment by justinclift** [comment]
Gah, that's not good.

@cnromaine Thanks for pointing this out.  We could be releasing 3.6.1 tomorrow or so. :wink:

@rp- Any ideas?

**Comment by justinclift** [comment]
Some Google turns up these:

* http://falsinsoft.blogspot.ch/2013/09/qt-5-and-failed-to-load-platform-plugin.html
* https://forum.qt.io/topic/40656/solved-qt-this-application-failed-to-start-because-it-could-not-find-or-load-the-qt-platform-plugin-windows/18

**Comment by justinclift** [comment]
Also received email about this same issue, so it's not limited to @cnromaine. :frowning:

**Comment by justinclift** [comment]
I've just pulled the windows binaries, updated the website about it, and reverted currentrelease (which the update checker relies on) to 3.5.1.

Hopefully we get this solved in a day or two, so we can put up good v3.6.0 binaries for Windows. :wink:

**Comment by cnromaine** [comment]
Maybe its is in the build?
I don't know if this will help, but 3.6.0 produces a bin with multiple .dlls. 
![image](https://cloud.githubusercontent.com/assets/207884/7361114/5dab822a-ed21-11e4-9ad5-17978dd63f10.png)
3.5.1 only has the .exe.
![image](https://cloud.githubusercontent.com/assets/207884/7361122/7b474648-ed21-11e4-9d89-b2eff4f1ed48.png)
That's about all that I can add for now.

**Comment by rp-** [comment]
There seems to be dll's missing in the installer.
I didn't have this problem, I guess because I hade the qt development libs installed on my system.
Will fix it today.

**Comment by justinclift** [comment]
@cnromaine Yeah, this is our first Windows release using a new build process (to enable 64 bit Windows builds).  Looks like there are a few kinks to still be worked out. :wink:

**Comment by cnromaine** [comment]
Oops. I forgot to include a pic of the 64 bit deployment.

![image](https://cloud.githubusercontent.com/assets/207884/7370517/9f8180ac-ed88-11e4-882d-68133656f158.png)

Note that these are files in the /SqliteBrowser/bin folder. The /SqliteBrowser looks the same for all version:
![image](https://cloud.githubusercontent.com/assets/207884/7370570/07972778-ed89-11e4-8f87-1e56fbbcf837.png)

Thanks for all that you do. Wonderful product.

**Comment by rp-** [comment]
I added new windows installers with the missing .dll, please someone else also test them.

Also keep in mind that your system needs to have the MSVC2013 .dll installed.
You get a MSVC120.dll missing error on start if thats the case, the installer for them can be downloaded here:
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by justinclift** [comment]
I have a Win8.1 VM I can test.  I'll try it out now.

**Comment by cnromaine** [comment]
Installed both

32 bit, v2
![image](https://cloud.githubusercontent.com/assets/207884/7376122/9c61456a-edab-11e4-986a-3c3d4da643c5.png)
and
![image](https://cloud.githubusercontent.com/assets/207884/7376321/fd96bb20-edac-11e4-9542-132b72b147ab.png)

64 bit, v2
![image](https://cloud.githubusercontent.com/assets/207884/7376105/712d0bea-edab-11e4-8b81-42c10d010623.png)
and
![image](https://cloud.githubusercontent.com/assets/207884/7376310/e6bb280a-edac-11e4-842c-52461fa4293b.png)


Only thing that might need addressing are their icons. They seem to switched around. Perhaps one is left over from the previous version?
![image](https://cloud.githubusercontent.com/assets/207884/7376086/3dd89af2-edab-11e4-8285-79a86aa17cf8.png)

Also note that 3.5.1 was a single .exe rather than all of the .dlls.

Both versions start up without any errors. Haven't time to check integrity but I'm sure that you wouldn't have released it if you weren't ready to go. ;-)

Thanks for the extra effort. If the icons are an issue, let me know and I'll start another issue.

Great job!

**Comment by justinclift** [comment]
@rp- Cool, the new ones work. :smile:

The MSVCP120.dll error message did happen too, and the download at the link you gave fixed that.

I'll update the release page with the new dependency info, new shasums, and update currentrelease.

**Comment by justinclift** [comment]
Oh... should I hold off until new icons?

**Comment by cnromaine** [comment]
I can start a new issue. Push it out the door!
(Thanks again)

**Comment by cnromaine** [comment]
BTW, I have VS2013 Community installed on this machine. Did not get the MSVCP120.dll error message. No problems were encountered with the "v2" installs.

**Comment by justinclift** [comment]
Yeah, my VM is close to a fresh install of Win 8.1.

**Comment by justinclift** [comment]
k, updated things so now 3.6.0v2 is live. :wink:

Thanks for your assistance with this @cnromaine, it's helping a lot. :grinning:

**Comment by jgus** [comment]
Has the portable app been updated with this fix? I'm seeing this error with the portable app at https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.6.0/SQLiteDatabaseBrowserPortable_3.6.0_English.paf.exe

**Comment by cnromaine** [comment]
Was able to open @jgus' portable app on Windows 8.1 machine without any error messages. Did not check it any further. No error message as I first reported in April (see first post).

What version of Windows are you running @jgus? Perhaps you should log it as a new issue with documentation of its problem and your machine's specs.

Ping me if you need me to run some quick tests.

**Comment by jgus** [comment]
Windows 8.1. Though, the exact same set of files _does_ work on another Win8.1 machine. Not sure what the difference is. And using the installer rather than the portable seems to work around whatever the issue is on the problematic machine. <shrug>

**Comment by justinclift** [comment]
Yeah, that's really weird. :frowning:
