### ISSUE TITLE
NULL String is copy as empty String

### ISSUE THREAD

**Issue by yccheok** [sqlitebrowser/sqlitebrowser#2691]
Details for the issue
--------------------

#### What did you do?
Under "Browse Data", I use "Copy as SQL"

#### What did you expect to see?

`"INSERT INTO "main"."tab_info" ("id", "type", "name", "color_index", "custom_color", "icon_index", "order", "synced_timestamp", "uuid") VALUES ('5', '3', NULL, '0', '0', '0', '4', '1620358885863', 'c37d62c1-865a-4b16-acaa-35dbf5986b16');
`

Please refer to the screenshot

![null-as-empty-string](https://user-images.githubusercontent.com/308276/117398732-85530180-af31-11eb-8cce-250e5d29e245.png)

#### What did you see instead?

`"INSERT INTO "main"."tab_info" ("id", "type", "name", "color_index", "custom_color", "icon_index", "order", "synced_timestamp", "uuid") VALUES ('5', '3', '', '0', '0', '0', '4', '1620358885863', 'c37d62c1-865a-4b16-acaa-35dbf5986b16');
`

Useful extra information
-------------------------
Version 3.12.0

Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.12.8

SQLite Version 3.32.2

**Comment by mgrojo** [comment]
This should be fixed in the development branch with c5199f559d2e734075af85faed2a00ed334cdcd0. Could you confirm using the latest [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)?

**Comment by yccheok** [comment]
@mgrojo 

Sorry for late respond.

Yes. I did a test on nightly build. The problem is no longer seen.

Hope to have such fix into production soon. Thank you very much for your support!

**Comment by chrisjlocke** [comment]
Excellent, thanks for confirming!
