### ISSUE TITLE
DBHub syncing using DB Browser process

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#2693]
What is your question
-----------------------

Hello,

If I have a database that I'm uploading via `dio` on one machine (machineA), I can use `sqlitebrowser` to download that database on a different machine (machineB) using my same identity. 

What do I do if I want to edit the schema or add in more views in the GUI machine (machineB) and merge it with the cloud version, and my other local copy on the other machine (machineB)?

```
machineA uploads to dbhub ----> cloud ---->machineB locally
edit on machineB ----> cloud ----> machineA
```

Is that kind of syncing possible without losing all my commits?

**Comment by justinclift** [comment]
Yeah, that's supposed to work well.  In theory.  I'd tend to keep a backup of things handy, just because I'm the paranoid sort and well... I've seen too many edge cases happen with important data over the years. :wink:
