### ISSUE TITLE
F5 doesn't refresh query after changing remote identity

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#2695]
Details for the issue
--------------------

#### What did you do?

1.  Opened gui portable app version 3.12.99 from May 3, 2021
2.  Opened local database with the above mentioned app
3.  Typed in a bogus query (`select * from justin`)
4.  Pressed F5 key
5.  Executed with errors message appears below the query (as expected)
6.  Changed to "Remote" tab on the pane on the right
7.  Set identity to my `@dbhub` address
8.  Went back to SQL editor tab
9.  Pressed F5 key
10. Query not executed

#### What did you expect to see?

I expected to see my query refreshed and for me to get the same error message below the query.

#### What did you see instead?

It looks like the DBHUB.io tab is refreshed with each press of F5.
ctrl+ Enter/Return still works in the editor tab, along with ctrl + r, just not the F5 key

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( version:10)

#### What is your DB4S version?

- [x] Other: Nightly

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by jungle-boogie** [comment]
Ah, you're right. However, if you keep remote > DBHub.io set, then go to something like SQL Log and hit F5, it won't refresh.

At least there's a workaround until this gets fixed. :-D

And thanks for correcting my spelling mistake. ;)

**Comment by MKleusberg** [comment]
Thanks, @jungle-boogie! That's a very good observation. The issue should be fixed in tomorrow's nightly build. Can you give that a try and see if it's working as expected now?

**Comment by jungle-boogie** [comment]
Yes, will do!

**Comment by jungle-boogie** [comment]
The latest Windows 64 bit build is `DB Browser for SQLite Version 3.12.99 (May 22 2021)`, which doesn't have this fix.

Not sure why Windows 64 wasn't made
https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Hmmm, you're right.  Looks like the 64-bit build didn't work.

Chris noticed that the other day, but they turned up a few hours later.  Hmmm, might need to look into it. :frowning:

Actually, for now I'll just kick off the 64-bit build, and spread out their initial kick off times during the day.  That way they shouldn't potentially conflict with each other, just in case that's the problem. :smile:

**Comment by jungle-boogie** [comment]
Thanks! I’ll look for the 64bit build in a few hours.

Good idea on spacing out the build times.

**Comment by jungle-boogie** [comment]
Verified the F5 fix is good. Thanks @MKleusberg for checking into this.

Verified 64bit Windows builds work. Thanks @justinclift 

Validated fix on `DB Browser for SQLite Version 3.12.99 (May 23 2021)`
