### ISSUE TITLE
missing release tag signature on v3.12.1

### ISSUE THREAD

**Issue by anthraxx** [sqlitebrowser/sqlitebrowser#2698]
Hi, so far the release tags have been signed by the key `05E463FDB5802C3D00257F9C79EAD0AB3BD7DD2C` from Justin Clift. Now this doesn't seem to be the case anymore, which broke the chain of trust hence we did not yet proceed with releasing distro updates for v3.12.1 but are stuck with v3.12.0.

Would it be possible to create an annotated tag for v3.12.1 with the known good signing key? Thanks!

**Comment by justinclift** [comment]
Oops.  Yeah, I *think* I can do that from the cli.  Let me try some stuff out... :smile:

**Comment by justinclift** [comment]
k, in ***theory**, the `v3.12.1` tag should now be signed.  There's a `v3.12.2` tag (also signed) there too, which the next stable release should be created from sometime in the next few days or so. :smile:

**Comment by anthraxx** [comment]
Thank you very much for your quick handling and response :smile_cat: 

Is the `v3.12.2` already meant for distro production consumption?

**Comment by justinclift** [comment]
Hmmmm, probably not (yet)e.  We've generated initial Windows and macOS binaries using that tag, and **assuming** nothing goes wrong with their signing process then our official release should happen in a few days.

That being said, if something weird does turn out to need fixing, then that tag will be moved to whichever new commit has the bits we fix.  So, probably best to wait until we officially launch the 3.12.2 release.  Hopefully pretty soon. :smile:

**Comment by anthraxx** [comment]
makes sense, just making sure :cat: thanks a lot

**Comment by justinclift** [comment]
@anthraxx We've just published the 3.12.2 release here on GitHub.  No blog post on the website yet, that'll probably get done tomorrow. :smile:

**Comment by justinclift** [comment]
Ahhh, it looks like the ordering of releases is by the timestamp of their tags.  So the recently recreated `v3.12.1` tag being only a few days ago seems more recent.

I'll just create the `v3.12.2` tag, which should fix the problem... :smile:

**Comment by justinclift** [comment]
Yep, that worked. :smile:
