### ISSUE TITLE
Drop-down menu tables order

### ISSUE THREAD

**Issue by PautassoEGiacomina** [sqlitebrowser/sqlitebrowser#2700]
While I am here I would like to ask another question.
I state that I searched if there was already an answer here by trying all the keywords that came to my mind, but I did not find anything.
I made this my first database and I am therefore a very newbie.
When I click on "Foreign Key" the drop-down menu opens with all the available tables from which I can choose the one that contains the primary key that interests me. But the tables in this drop-down menu are not shown in alphabetical order, so each time it takes me a long time to find the desired table among the more than 80 currently created. Is there any way to show the tables in alphabetical order in the drop down menu, perhaps from the DB Browser configuration files?
Thank you in advance!

**Comment by chrisjlocke** [comment]
I'll label this as a bug, as I guess it should be easy to sort the tables quite easily - they're in the database itself anyhow.  80 tables sounds a lot.  Are they all related in different objects, rather than split into categories - eg, you don't have 30 different 'log' tables for different months, do you?  Just making sure...  Just bear in mind that database tables are designed to hold milllllllllllllions of records.

**Comment by PautassoEGiacomina** [comment]
> I'll label this as a bug, as I guess it should be easy to sort the tables quite easily - they're in the database itself anyhow. 80 tables sounds a lot. Are they all related in different objects, rather than split into categories - eg, you don't have 30 different 'log' tables for different months, do you? Just making sure... Just bear in mind that database tables are designed to hold milllllllllllllions of records.
> I remember a colleague learning databases, and making a recipe system. He created tables for mains, tables for desserts, tables for starters, etc, etc. In his mind it made sense, but from a system point of view, it was a mess.

Thank you so much for your kind reply!
My database is structured as follows: about 80 tables contain only a few records each listing various aspects. The remaining 3 or 4, which are the main ones, contain only references (foreign keys) to all the others; none of my main tables actually contain a typed field, only foreign keys. All this because I am veeeery picky and I have tried to separate almost every existing column in a table, to avoid data repetition, inconsistencies, records containing empty fields, etc.
For example, to register a customer's address I only have foreign keys that connect to dozens of different tables: one table contains only the streets, another only the ZIP codes, another only the cities, another only the provinces, another only the states, and so on for all the aspects that I want to analyze.
Having said that, I have seen that when I open the drop-down menu in question I can type on the keyboard the letter with which the name of the table that interests me begins: in this way I save a considerable amount of time, even if I would still prefer that they were shown in alphabetical order.
But then I did not understand: is it a bug that only me or was it thought so?

**Comment by chrisjlocke** [comment]
> is it a bug that only me or was it thought so?

I assume the code to retrieve the tables has no sorting on it - in initial testing, databases have probably been small!

At least keeping data in specific tables helps keep the database small - very limited repetitive data.  It can make getting the information out complex though - lots of joins!

**Comment by PautassoEGiacomina** [comment]
> I assume the code to retrieve the tables has no sorting on it - in initial testing, databases have probably been small!
> 
> At least keeping data in specific tables helps keep the database small - very limited repetitive data. It can make getting the information out complex though - lots of joins!

Exactly, you said right! In hindsight I should have found the right balance between keeping the database small and clean and the non-complexity of its connections.

**Comment by MKleusberg** [comment]
Good catch, @PautassoEGiacomina! I've been looking at this dropdown for hundreds of times but never noticed this issue :wink: It should be fixed in tomorrow's nightly build. Can you give that a try? The download will be available [here](https://nightlies.sqlitebrowser.org/latest/).

**Comment by PautassoEGiacomina** [comment]
> Good catch, @PautassoEGiacomina! I've been looking at this dropdown for hundreds of times but never noticed this issue wink It should be fixed in tomorrow's nightly build. Can you give that a try? The download will be available [here](https://nightlies.sqlitebrowser.org/latest/).

Thank you so much for the fantastic support you provide!!
My DB Browser for SQLite package is from the official Arch repo, can I still try it as you say?

**Comment by MKleusberg** [comment]
Hmm, I'm not sure about Arch Linux. I think they package the latest official version but don't have a build with the latest changes and no AUR either at the moment. You could try the AppImage file from [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous). If that doesn't work you'd have to compile it yourself which actually isn't that difficult and we could assist you doing that.

**Comment by scottfurry** [comment]
Seems Arch needs a package maintainer to help keep up to date.
[Current Packaging](https://archlinux.org/packages/?q=sqlitebrowser) is a version behind.
[Arch AUR](https://aur.archlinux.org/packages.php?K=sqlitebrowser) doesn't appear to be updated.
