### ISSUE TITLE
Select "%text"

### ISSUE THREAD

**Issue by Dream-Apps-pl** [sqlitebrowser/sqlitebrowser#2706]
Details for the issue
--------------------

When I serach like: SELECT * FROM Verses WHERE VERSE_TEXT like "text%"
everything work good, but when I try to search like:
SELECT * FROM Verses WHERE VERSE_TEXT like "%text"
I have no results

#### What did you do?
SELECT * FROM Verses WHERE VERSE_TEXT like "%text"

#### What did you expect to see?
Any results with: %text

#### What did you see instead?
nothing

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.4.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.15.1

**Comment by chrisjlocke** [comment]
Have you got an actual example?  Maybe a screenshot?
If a field contained 'Hello' and you entered a filter of `%el`, it wouldn't display anything, as % means 'any character', so `%el` means any field that ends with `el`.  To search for a field containing `el`, you'd have to enter `%el%` - so has any characters, then `el`, then any characters.

**Comment by Dream-Apps-pl** [comment]
Yes, should work but doesn't. See screens with examples
<img width="2032" alt="Zrzut ekranu 2021-05-18 o 17 04 12" src="https://user-images.githubusercontent.com/80961875/118676056-625f0200-b7fb-11eb-9cd1-ee11e8c824a0.png">
<img width="2032" alt="Zrzut ekranu 2021-05-18 o 17 04 27" src="https://user-images.githubusercontent.com/80961875/118676080-668b1f80-b7fb-11eb-80b2-75eabf27fa2d.png">
<img width="2032" alt="Zrzut ekranu 2021-05-18 o 17 04 00" src="https://user-images.githubusercontent.com/80961875/118676087-67bc4c80-b7fb-11eb-803f-3a27b9d2f6c6.png">

**Comment by Dream-Apps-pl** [comment]
There should be many results like: Rodom, zawiadom, sądom, Sodomy...

**Comment by chrisjlocke** [comment]
So the first one, `select * from verses where verse_text like '%dom'` will only find texts that end with those three characters - it won't find 'here is the kingdom.' as that ends in 'dom.' which isn't the same thing.  
As a test, make it `select * from verses where verse_text like '%dom%'` and see how many rows you get back.

Aah, sorry - typed that before I saw screenshot #2.
Well, that shows its working - all the rows begin with 'Dom' which is what you asked for.

As an aside, I notice the font is slightly broken in the results pane.  You can change the font in Edit and then Preferences.

I'm still not seeing the issue - are you saying it's not displaying rows with 'Rodom' in it?

**Comment by Dream-Apps-pl** [comment]
I have a result for "Rodom" but I don't see results from "%Dom". I should have results like: Rodom, zawiadom, sądom, Sodomy... How to get that result?

<img width="1988" alt="Zrzut ekranu 2021-05-18 o 21 29 14" src="https://user-images.githubusercontent.com/80961875/118712166-bf20e380-b820-11eb-9014-3b9fe5f8c4f3.png">
<img width="2032" alt="Zrzut ekranu 2021-05-18 o 21 32 01" src="https://user-images.githubusercontent.com/80961875/118712181-c3e59780-b820-11eb-8fbc-812ea6e7a60e.png">

**Comment by chrisjlocke** [comment]
> I have a result for "Rodom" but I don't see results from "%Dom"

Maybe you don't have any text entries that end with 'Rodom'.  If you have a line that ends with a full stop (I can't see how a line is going to end with just Rodom?) then %Dom isn't going to work.
Again, if you have a line that is `the cat sat on the mat.` then `%mat` isn't going to pick that up - that line doesn't end with `mat`.

The `%` means 'any character', and it's looking at the whole field, not individual words, so if your search string doesn't end with %, then it's only going to find records that matches that - not if it has text after it.
Again, `%don` will match `London` but it won't match `Londonat`.

If you want to search for words that end in 'dom' anywhere in the field, then you're going to have to use regular expressions.  SQLite does not contain regular expression functionality by default, but there are extensions you can load to give you this functionality.

**Comment by Dream-Apps-pl** [comment]
I'm talking about 'dom' :) I search for 'dom' and any word that end with 'dom'.
I show you that I have a words in 'VERSE_TEXT' like: Rodom, zawiadom, sądom
So why when I search: WHERE VERSE_TEXT like "%dom" I'm not receive worlds like:
Rodom, zawiadom, sądom
??
Did I thing wrong or app not working correctly?  

Piotr

**Comment by Dream-Apps-pl** [comment]
You wrote:  %don will match London
So In my DB: %dom should find: Rodom, zawiadom, sądom
But I have a 0 results

**Comment by Dream-Apps-pl** [comment]
maybe you just try:
[sample.sqlite.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/6504644/sample.sqlite.zip)

Try:
SELECT * FROM Verses WHERE VERSE_TEXT like "%dom"

Piotr

**Comment by chrisjlocke** [comment]
> Did I thing wrong or app not working correctly?

The whole field is being searched - not each word.  So look at the field.  This is why I said imagine the text 'The cat sat on the mat'.
You are searching for %dom so it will only find fields that end in dom.
So if I search for %mat it will show the above field.
If I search for %cat it will NOT find the above field.  That field does not end with cat.

If I want to find fields that contain cat I have to use %cat%
However, this does not find just the word cat but any word or phrase that contains cat, so scat, scats, etc.
You could try `% cat %` but that wouldn't bring up 'the cat, which was blue' or 'the blue cat.'

Check out this tutorial.
https://www.sqlitetutorial.net/sqlite-like/

It may be that I'm not explaining it properly.

**Comment by Dream-Apps-pl** [comment]
ok, thx

**Comment by chrisjlocke** [comment]
Feel free to comment further if you need more help on this.

**Comment by MKleusberg** [comment]
I'll close this issue for now because it looks like the questions raised here have been answered. But you can always comment further on this issue or reopen it if there's more to discuss, @Dream-Apps-pl :smile:
