### ISSUE TITLE
User-defined edit/view forms.

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2707]
Describe the new feature
--------------------------

(For start, to keep it very simple)
Allow the user to drag fields from a table/view combination into a 'form', and then move/stretch the field box sizes  anywhere on the form screen (using as default label the column name -- but it should be allowed edits by user).

The form layout details should be saved preferably inside the DB (so that shipping the db also keeps the forms together), or else the configuration file.

Now, browsing / inserting / updating / deleting can be done one record (screenful)  at a time.

(This idea -- with more bells and whistles such as field validation [reg exp etc] --  I implemented about 30 years ago on a Pick database system for a large HMO company.  It worked unbelievably well, and end users could even re-arrange the form to their liking while using it.  Fully dynamic.)

This functionality will make DB4S able to run low complexity db applications without any additional software.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

No.

#### Does this feature exist in another product or project? Please provide a link.

Not sure.

**Comment by chrisjlocke** [comment]
This seems a popular topic - this only came up yesterday (#2702).
I'll close this though (no offence!) as we already have an open issue regarding forms (#127)
