### ISSUE TITLE
Filtering fails when column name contains a space 

### ISSUE THREAD

**Issue by jeffbronks** [sqlitebrowser/sqlitebrowser#2708]
One of my tables contains a column called "Word Mark". Whatever I type in the filter box for that column, I get zero results. The reason is apparent in the SQL Log:

SELECT "_rowid_","ID","Word Mark","Status","Owner","Register","App No","Reg No",strftime('%Y-%m-%d', "App Date") AS "App Date",strftime('%Y-%m-%d', "Reg Date") AS "Reg Date","Image" FROM "main"."Trademarks" WHERE Word Mark LIKE '%p%' ESCAPE '\' LIMIT 0, 49999;

After the WHERE keyword the column name "Word Mark" is not enclosed in quotes so it causes a syntax error. IMHO (I'm not an expert) DB Browser should enclose column names in quotes.

**Comment by chrisjlocke** [comment]
Thanks for reporting this.  This should be easy to fix.  Interesting the fields are quoted in the initial select statement, whether they need them or not! 😁  You'd think in the bowels of the DB4S coding, the function to retrieve a field name would decide whether or not to supply quotes.  It can be a bit messy to just quote everything 'just in case'.

As a workaround, you can create a view so the column doesn't have a space (in an ideal world, field names shouldn't).  The only downside is that by default, browsing on views is read-only, which is a bit of a pain.

**Comment by MKleusberg** [comment]
Which version of DB4S are you using, @jeffbronks? A quick test showed that at least the latest nightly build doesn't seem to have this issue.

**Comment by chrisjlocke** [comment]
Aah, the 32/64 bit versions are usually built together - something must have broken during it's build.  I'll raise an issue...

**Comment by mgrojo** [comment]
The important part to reproduce this was having a display format for any of the columns, as the query was showing. It should be fixed now in the next nightly build. Could you try it and confirm it's working for you?

**Comment by jeffbronks** [comment]
It's working. I installed today's nightly win64 and now the query is:

SELECT "_rowid_","ID","Word Mark","Status","Owner","Register","App No","Reg No",strftime('%d/%m/%Y', "App Date") AS "App Date","Reg Date","Image" FROM "main"."Trademarks" WHERE "Word Mark" LIKE '%p%' ESCAPE '\' LIMIT 49999 OFFSET 0;

**Comment by chrisjlocke** [comment]
Thanks for the fix @mgrojo , and thanks for confirming @jeffbronks .
