### ISSUE TITLE
Problem with Qt Platform plugin "Windows"

### ISSUE THREAD

**Issue by ticktock12** [sqlitebrowser/sqlitebrowser#271]
I am running windows 7 64 bit and when i install the 64 bit version i keep getting "This application failed to start because it could not find of load the Qt platform plugin "Windows".

Reinstalling might fix it.

Reinstalled multiple time nothing worked and

**Comment by justinclift** [comment]
Thanks @ticktock12.  This one's already reported [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/269).

Sounds like we're better pull the windows binaries for now, until we figure out what's wrong. :frowning:

**Comment by justinclift** [comment]
Done it, pulled them.  Hope we get this fixed soon. :wink:

**Comment by justinclift** [comment]
@ticktock12 New downloads for windows are available now:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.6.0

Sorry for the initial hassle. :frowning:

**Comment by ticktock12** [comment]
Thanks for quick fix :3
