### ISSUE TITLE
64-bit version of nightlies are unavailable

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2710]
Just a nod that the 64-bit version of the nightlies are unavailable - the 32-bit ones have been built successfully.

![image](https://user-images.githubusercontent.com/7872218/118851194-74a77180-b8c9-11eb-9552-8e731c0d8586.png)

**Comment by justinclift** [comment]
Weird.  I just looked now, and they seem to have built and uploaded ok.  Hopefully it was just a timing thing. :smile:
