### ISSUE TITLE
Change the read only satus

### ISSUE THREAD

**Issue by JANA-tmarill** [sqlitebrowser/sqlitebrowser#2711]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Hey @JANA-tmarill, that's a bit light on details. :wink:

Are you needing help with something?  If so, um... maybe screenshot the problem or something?

We're happy to help, but need to know the situation, etc. :smile:

**Comment by justinclift** [comment]
Closing this, as it seems to have been created in error.
