### ISSUE TITLE
Hidden columns should stay hidden after sorting another one

### ISSUE THREAD

**Issue by DCourtel** [sqlitebrowser/sqlitebrowser#2718]
Details for the issue
--------------------

#### What did you do?
I right-click on a column header and choose "Hide a/some column(s)", the column is hidden. I click on another column header to sort (Ascending or Descending) the data. The hidden column is displayed again.

#### What did you expect to see?
The hidden column should stay hidden.

#### What did you see instead?
The hidden column appears again.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version:_ Server 2019 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [ ] 3.12.1
- [X] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Can you try with v3.12.2 (just recently released) or the nightly - I'm trying with a nightly version, and it doesn't do that.  In fact, I don't see a 'Hide a/some column(s)' option at all - just a 'Hide column(s)'

![image](https://user-images.githubusercontent.com/7872218/119318525-58148c00-bc71-11eb-82d2-1f76a898125e.png)

**Comment by DCourtel** [comment]
I tried with release 3.12.2 with no luck. (I use the French translation of the UI, so I tried to translate the context menu item as it "could" appear in the original language :-) ).
The nightly build seems to solve the issue, though.

Thank you!

**Comment by chrisjlocke** [comment]
Oops - apologies for the translation error - that makes sense then! 👍
I'll tag this as 'broken' then as the nightlies shouldn't have 'fixes' in them which isn't in the main release.  Thanks for making us aware of it!

**Comment by justinclift** [comment]
Um... the nightlies *often* have fixes in them that aren't in a stable release.

It's just that generally when we do a stable release, we try to get all of the useful fixes into it.  Sounds like this *might* have been one we missed. :wink:
