### ISSUE TITLE
Unable to open default EUDC font in Windows 10

### ISSUE THREAD

**Issue by yanoolo** [sqlitebrowser/sqlitebrowser#2719]
Details for the issue
--------------------
I had the same issue as mentioned in Bug Report #2556 with the error: Unable to open default EUDC font: "C:\Windows\FONTS\EUDC.TTE"
The solution in #2556 works:
1. Open eudcedit.exe
2. Save the file (no edits needed)

#### What operating system are you using?
Windows: (version: 10, 21H1)

#### What is your DB4S version? 
3.12.2

**Comment by chrisjlocke** [comment]
Thanks.  I'll close this then, as there is a solution available.

**Comment by abtxu** [comment]
>Save the file (no edits needed)
how did you do that? I can not find the option of save under file, nor can I save it after close the editing window of eudcedit.exe.

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/182022990-5111a33b-ca0f-4471-8506-13940762e392.png)

Click 'Edit' and 'Save character'

**Comment by AlbertWang2018** [comment]
I have fixed it editing \HKEY_CURRENT_USER\EUDC\1252 (1252 is the code of the latin alphabet) "SystemDefaultEUDCFont" key value to "C:\Windows\Fonts\seguibli.TTF" (for Segoe UI font) which it seems like it is the default windows font.
