### ISSUE TITLE
3.6.0 v2 icons for Windows 32 bit and 64 bit are different.

### ISSUE THREAD

**Issue by cnromaine** [sqlitebrowser/sqlitebrowser#272]
During testing the 3.6.0 v2 release, I noticed that the icons for the Windows 32 bit and 64 bit were different. Should they be the same? Maybe one was left over from a prior release.

![image](https://cloud.githubusercontent.com/assets/207884/7377837/e9a95316-edb6-11e4-9008-c42022f20b04.png)

Thanks.

**Comment by rp-** [comment]
I have the NSIS icon on both installers

**Comment by justinclift** [comment]
Cool.  This sounds like it would work:

&nbsp; &nbsp; https://stackoverflow.com/questions/7431039/how-to-replace-the-default-logo-in-nsis-installer

**Comment by justinclift** [comment]
@cnromaine Would you have time to check the icons on the [3.9.0-beta1 release](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1), from your point of view?

In theory they should be ok, but verifying doesn't hurt. :smile:

**Comment by cnromaine** [comment]
Out of town for a few days. Will check them out when I get back this weekend. Currently running Windows 10 Pro 64 bit and Win 7 64 bit on box and laptop.

**Comment by justinclift** [comment]
Thanks @cnromaine. :smile:

**Comment by justinclift** [comment]
For me, when I checked here they're both using the same icon.  That was on Win 7 x64.

@cnromaine We're just about to release 3.9.0, so I'll close this.  If it turns out that the icons for 3.9.0 are different for you, feel free to reopen this and we can look back into it for the next release. :smile:
