### ISSUE TITLE
RETURNING keyword not implemented?

### ISSUE THREAD

**Issue by tinxx** [sqlitebrowser/sqlitebrowser#2720]
Details for the issue
--------------------

#### What did you do?

Inserting data into a table using the `RETURNING` keyword in the tab 'Execute SQL'.

```sql
CREATE TABLE t0(
  a INTEGER PRIMARY KEY,
  b DATE DEFAULT CURRENT_TIMESTAMP,
  c INTEGER
);
INSERT INTO t0(c) VALUES(random()) RETURNING *;
```

See [here](https://www.sqlite.org/lang_returning.html) for more information and above example query.

#### What did you expect to see?

The returned data in the output window element.

_Note: The data is correctly returned as expected when manually executed via command line._

#### What did you see instead?

Empty table with correct header, in this case:

|  a  |  b  |  c  |
| --- | --- | --- |

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: Arch Linux
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
DB4S v3.12.1 only has SQLite 3.33 in it.  The RETURNING keyword was only introduced in 3.35.
You need to use DB4S v3.12.2 (which does have 3.35 in it) or a recent nightly.

v3.12.2 can be downloaded from here: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.11.2

**Comment by chrisjlocke** [comment]
So I was wrong on everything! 😁😃  I guess I should be happy I at least responded in the right topic! 😉

**Comment by tinxx** [comment]
Hi @justinclift, I am actually using a current version of SQLite. I probably should have mentioned that. I did however mention that the keyword does not pose a problem to the SQLite version installed on my system.

![Screenshot from 2021-05-25 23-15-26](https://user-images.githubusercontent.com/13608545/119570041-db3bfc00-bdaf-11eb-8730-fe1de01bf175.png)

I am not going to install 3.12.2 until it will show up on Arch, because that should usually happen within a few days/weeks.
If I fail to report back after the update happened feel free to nudge me here later.

**Comment by ambaca** [comment]
Hi.
I'm trying Windows version
```
DB Browser for SQLite Version 3.12.2

Built for i386-little_endian-ilp32, running on x86_64
Qt Version 5.12.8
SQLite Version 3.35.5.
```
I have exactly same problem like in[ first post ](https://github.com/sqlitebrowser/sqlitebrowser/issues/2720#issue-900569252)

Is this user error or it just not work in this program, yet ?

**Comment by mgrojo** [comment]
@tinxx, this was fixed thanks to @bmalrat. It will be available in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) and in the next release.

**Comment by tinxx** [comment]
Hey @mgrojo, thanks for letting me know! Thanks, @bmalrat, for implementing it!

I am currently not using SQLite regularly. Do you need me to verify, or can I wait until the next release is out?

**Comment by mgrojo** [comment]
Not strictly necessary. Usually we like that another person, often the original reporter, verifies it is working, but since this was implemented by third person, and I could verify it is working, it has already seen two green lights.
