### ISSUE TITLE
currentreleases version is 3.12.0

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2722]
I know the 'currentreleases' doesn't get updated for a while, just in case something wacky is spotted in the binaries, but just a nod that it's been eight days, and it doesn't look like it got updated last time - it's still on 3.12.0, pointing to that version.
So this is a 'reminder' or placeholder so it can get updated in the next couple of days or so...
Also, unsure if it was by design or not, but the blog post (https://sqlitebrowser.org/blog/version-3-12-2-released/) doesn't mention the portable version.

**Comment by justinclift** [comment]
Which `currentreleases` file are you looking at?

Asking because I updated it a few days ago, to point at 3.12.2:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/currentrelease

Maybe you're looking at an older revision or something?

**Comment by justinclift** [comment]
With the blog post not mentioning the portable version... oops.  Totally forgot.

Want to update the blog post, and I'll regenerate it for the website after work tonight?

(Or you can just run `[hugo](https://github.com/gohugoio/hugo/releases)` in the same directory from the command line - without any options needed - and it'll regenerate it)

**Comment by chrisjlocke** [comment]
Aah, I thought `https://download.sqlitebrowser.org/currentrelease` was the main location.  I was running up older copies of DB4S, and it was looking there.

**Comment by justinclift** [comment]
Oh crap.  I totally forgot about the existence of that file.  Yeah, it's probably important too, so we should update it.  Updating now... :smile:

**Comment by justinclift** [comment]
k, that's updated.  While I was at it, I moved the primary download location for all the downloads back to our own infrastructure.  That'll mean our [download stats][https://sqlitebrowser.org/stats/] start working again (though I need to update the 3.12.x entries to not be "null"). :wink:

@chrisjlocke Would you be ok to let John Haller know there's a new primary download location for the PortableApp?
* New location: https://download.sqlitebrowser.org/SQLiteDatabaseBrowserPortable_3.12.2_English.paf.exe

Downloads from the GitHub link will still work, it's just stuff that's not done from our download infrastructure isn't counted in our download counter stats. :angel:

**Comment by chrisjlocke** [comment]
Many thanks!
