### ISSUE TITLE
 DB_Browser_for_SQLite--x86_64.AppImage  cannot run in LinuxMint

### ISSUE THREAD

**Issue by edu-live** [sqlitebrowser/sqlitebrowser#2724]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
@edu-live As Chris is pointing out, it's very hard for us to diagnose what could be going wrong, and suggest how to fix it.

When you start our application, is an error dialog shown?  If not, please open a terminal window and try and run it from the command line.  In theory :wink:, doing that should let the errors be shown when it goes wrong.

So, cutting and pasting the complete error text here would be super useful.  We'll be able to read it, and have an idea of why our application isn't working properly on your system. :smile:
