### ISSUE TITLE
incomplete display

### ISSUE THREAD

**Issue by bobatwhidbey** [sqlitebrowser/sqlitebrowser#2726]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I'll close this as there is no detail - incomplete what on where?
Please reply with more information and this can be reopened if necessary.
