### ISSUE TITLE
Bundle MS "Visual C++ Redistributable Packages for Visual Studio 2013" dependency for 3.7.0?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#273]
Wondering if we can bundle the MS redistributable package dependency for 3.7.0, or (if not), then perhaps check during installation that it's required and let the user know to download it.

**Comment by rp-** [comment]
d99d83f269e4f942e9e3dddba5b417005e4191b7

**Comment by justinclift** [comment]
Awesome Rene.  This should help a lot for the upgrade process. :smile:
