### ISSUE TITLE
My database is not changed when I run my python

### ISSUE THREAD

**Issue by crizzomy1010** [sqlitebrowser/sqlitebrowser#2730]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by scottfurry** [comment]
Details are a bit sparse. However, based on what is provided, my first impression is to suggest that you may need to commit changes. See [here](https://arctype.com/blog/hitchhikers-guide-sqlite-python/#sqlite-integration) for some more information.

**Comment by crizzomy1010** [comment]
Dear Scott,
     Thanks for the advice. I got it to work.

**Comment by scottfurry** [comment]
Awesome! \o/
I'll close this off then.
Good Luck.
