### ISSUE TITLE
display of table content weird

### ISSUE THREAD

**Issue by ba38** [sqlitebrowser/sqlitebrowser#2732]
Details for the issue
--------------------

#### What did you do? 
Use DB Browser for SQlite 3.12.2 on Windows 7 SP1 (with a db created using with sqlite.dll 3.31.1.0) to check the content of the db : table data display

#### What did you expect to see? 
I expect to see the right content of columns which are texts (and they appear as texts either in the application I debug (using Delphi) and in another tool "SQLite2009 Pro").

#### What did you see instead? 
Instead I see shortcuts whiche are the beginning of the text 'D:...' or gray text 'BLOB'.  
When looking at the right panel "Edit the content of a cell", with "Text mode" the content is not displayed with the message "binary data, not displayable", and with binary mode the content is displayed as text.
It seems a problem of displaying old ASCII characters (ASCII from codes 0 to 255) I am using.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8
![image](https://user-images.githubusercontent.com/3527377/120815804-753e3a00-c550-11eb-96f8-690d71ea2d4e.png)

**Comment by chrisjlocke** [comment]
It appears 'nom' and 'nom_exe' are blob fields?
What are you storing in these fields - just text?  Why have you used BLOBs?  
BLOBs allow the storing of binary data, eg, pictures, sounds, etc - things that cannot be displayed.  If you're just storing names or text values, you can use TEXT as a field type.

**Comment by ba38** [comment]
Hi These fields are text fields and the gray text "blob" is written by the software and is very strange indeed.
That's this behavior which is not awaited !
About blobs (which are used elsewhere) they are a kind of text fields with a content of hexadecimals such as "X'0..9-A..F'  with only
numbers and A to F letters.

**Comment by ba38** [comment]
![image](https://user-images.githubusercontent.com/3527377/120833130-ba1e9c80-c561-11eb-80a2-290c9453bfd8.png)
Here the structure of the table.

**Comment by chrisjlocke** [comment]
Aah, that makes a bit more sense.  Thanks for the extra information.
It would appear that DB4S is reading the cell contents and 'deciding' its binary data, when it's not.  In the 'Edit data cell' pane, you can select 'text' and it should display correctly.

**Comment by ba38** [comment]
Another view of this weirdness :
![image](https://user-images.githubusercontent.com/3527377/120840282-4fbe2a00-c56a-11eb-8332-8f9606576464.png)
and in binary :
![image](https://user-images.githubusercontent.com/3527377/120840356-6e242580-c56a-11eb-9c94-8e2d921235c3.png)

**Comment by chrisjlocke** [comment]
Yes, there is a very basic test done on the first few characters to determine whether the contents is text or binary, and unfortunately, your text is 'breaking the logic'.  I've tried changing the display format, adding some 'noise' to the start and casting to text, and no trick seems to work.  Someone cleverer than me might be able to assist in unblobbing this field.

**Comment by chrisjlocke** [comment]
Well, it's the full-stop that's doing it - binary code e9 (233 in decimal) in your example.  For me, a full-stop is binary 2e (ASCII 46).  
Replacing that character works for me.
```
select field2,replace(field2,x'e9',x'2e')
from a
```
So instead of this

![image](https://user-images.githubusercontent.com/7872218/120845458-c65a2800-c568-11eb-872d-435d7ccb7c6d.png)

I get

![image](https://user-images.githubusercontent.com/7872218/120845500-d540da80-c568-11eb-91d7-3c8e03e313a8.png)

That'll work until you hit another 'out of range' character... so not a workaround in the slightest ... or even at all ...

**Comment by mgrojo** [comment]
I guess it's text encoded in ISO-8859-1. Follow these steps and choose ISO-8859-1 as encoding, and then, voilà, you'll get: Mécanique :smile:

**Comment by ba38** [comment]
Hi mgrojo and thanks a lot
It's a encoding in ISO-8859-1 and changing the encoding for all tables as you indicate gives the expected display !
That's good now.
Have a good weekend.
Best regards.
Bernard

**Comment by mgrojo** [comment]
Great. Have a nice weekend too.

**Comment by chrisjlocke** [comment]
Thanks @mgrojo - knew there was a proper solution!  Doh!  😁
