### ISSUE TITLE
Comments within CREATE statement are missing when exported DB to SQL file.

### ISSUE THREAD

**Issue by voncwisch** [sqlitebrowser/sqlitebrowser#2735]
Comments within CREATE statement are missing when exported DB to SQL file.
--------------------
Export Database to SQL file does not include any comments within CREATE statement.

Created the TABLE using this SQL.
```
CREATE TABLE "BOB" (
 "FIELDID_0001"  TEXT UNIQUE, /* My Comments on the purpose of this column */
 "FIELDID_0002"  TEXT UNIQUE  /* My Comments on the purpose of this column */
)

```
Export contains:
```
CREATE TABLE IF NOT EXISTS "BOB" (
 "FIELDID_0001"  TEXT UNIQUE,
 "FIELDID_0002"  TEXT UNIQUE
);
```

When Copy Create statement is used, all comments are present.

#### What did you do?
Export Database to SQL file. - > File.

#### What did you expect to see?
Expected to see comments in create statement.

#### What did you see instead?
No comments.

Useful extra information
-------------------------
DB Browser for SQLite Version 3.12.1 Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8
SQLite Version 3.33.0.

**Comment by voncwisch** [comment]
> s

e

**Comment by chrisjlocke** [comment]
Note also that if you modify the table, this may also remove comments, so using comments in this way isn't recommended.
Creating a specific 'schema' table would be better.  Well, actually not removing comments would be better, yes, obviously.... 😁

**Comment by mgrojo** [comment]
For the export, we could query SQLite for the create statement of the table, instead of dumping our own internal represen

**Comment by justinclift** [comment]
@mgrojo Oh, that's an interesting idea. :smile:

**Comment by mgrojo** [comment]
I've investigated this a bit. The change is easy, but we would revert to a previous behaviour, see https://github.com/sqlitebrowser/sqlitebrowser/commit/2981351cc6302910851fed55e31568bee2bf92d7

Maybe this should be an Export option. Another option would be to add the comments to our parsing, and that would cover this issue and  #2709, but I'm not familiarized with the parser and doesn't seem straightforward.

**Comment by mgrojo** [comment]
@voncwisch, I've implemented a new option in the Export to SQL dialog to "Keep original CREATE statements". Could you give it a try with the next [nightly build](https://nightlies.sqlitebrowser.org/latest/) and report any malfunction?
