### ISSUE TITLE
MySQL Browser

### ISSUE THREAD

**Issue by Romvnly-Gaming** [sqlitebrowser/sqlitebrowser#2742]
Describe the new feature
--------------------------
MySQL Browser would be sqlite browser's amazing UI but on MySQL!

Additional info
---------------

#### Is your feature request related to an issue? Please include the issue number.
No.

#### Does this feature exist in another product or project? Please provide a link.
Yes, but their UI is ugly. I've come to really like SQLite Browser.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![DB_Browser_for_SQLite_nBI2n1Vlw7](https://user-images.githubusercontent.com/62443489/122138279-6a1ec000-ce14-11eb-8c9e-88896481af90.png)
But on MySQL! ❤️ 

## One thing
Am I missing a fork that does this already? I couldn't find one on the internet. I understand if this issue is closed aswell with no feedback. 😔

**Comment by justinclift** [comment]
Thanks for the compliment @Romvnly-Gaming. :smile:

I doubt this will happen, at least in the short to medium term, but you never know.

Personally, I've toyed with the idea of adding PostgreSQL support, but it would be a **lot** of work.  We do a lot of stuff that is SQLite specific, and we'd need to abstract that to work across multiple databases.  Then likely add the database-specific things as well.

It *might* happen at some point, but ... :shrug:  :grin:

**Comment by jungle-boogie** [comment]
I would rather DB4S stay specific to SQLite.

**Comment by chrisjlocke** [comment]
I'll close this as it's not going to get 'resolved' in the short, medium or even probably the long term.  The 'enhancement' tag should ping it back if ever we're bored scratching for something to do.
