### ISSUE TITLE
No SQL messages shown in GUI

### ISSUE THREAD

**Issue by Orialchon** [sqlitebrowser/sqlitebrowser#2746]
Details for the issue
--------------------

#### What did you do?
Launched any sql instruction (query or DML), either with correct syntax either purposely wrong

#### What did you expect to see?
In the lowest window widget, any SQL message feedback

#### What did you see instead?
![noSQLMessagesFeedback](https://user-images.githubusercontent.com/78219455/122560176-93239880-d040-11eb-8732-75426b5cf1db.png)

Only a blank window, no feedback at all.

Useful extra information
-------------------------
> DB4S v3.12.99 (Jun 12 2021) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I assume the SQL window has been 'minimised' - its height is so small that's it been hidden.  You can 'drag it up' to make it visible.  This textual explanation isn't that helpful, so here's a video which I hope explains it.  Yell back if it does/doesn't.

https://user-images.githubusercontent.com/7872218/122562903-7c2e7780-d03b-11eb-8cdf-8281763b7fb3.mp4

**Comment by mgrojo** [comment]
Should "Reset Window Layout" restore that panel height? Might be a panic button for all these case where people do not know what happened to their widgets.

**Comment by Orialchon** [comment]
Hi guys, thanks for your time! Yes, indeed my widget got minimized, retaining it's size event with full uninstall/install cycle, both standard and zip versions!.
Thank you again, and yes, a restore windows layout that counts minimized widgets should do the trick!
