### ISSUE TITLE
dark

### ISSUE THREAD

**Issue by LokeshKumarkumawat** [sqlitebrowser/sqlitebrowser#2747]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
@LokeshKumarkumawat Was this opened by accident?  eg should it be closed?

**Comment by mgrojo** [comment]
See https://github.com/sqlitebrowser/sqlitebrowser/issues/2753#issuecomment-867391406 if you're interested in a dark mode. I'll close this, since it seems just a search trial, and not an issue.
