### ISSUE TITLE
File - Import - Table from CSV data in clipboard doesn't work

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2749]
It appears the 'import table from clipboard data' is broken in the nightlies.
My copy from 9 Feb works fine.

https://user-images.githubusercontent.com/7872218/122680159-cd7a6a80-d1e5-11eb-8495-edd0eb7523c2.mp4

A recent download doesn't (skip the first 28 seconds... and from 0:40 onwards where I was oblivious it hadn't gotten any data)

https://user-images.githubusercontent.com/7872218/122680171-dc611d00-d1e5-11eb-8b95-79dd6866639b.mp4

I haven't tried other nightlies to determine exactly where it broke.

Saving the file as CSV and importing that works, so it's not an issue with the CSV/clipboard data (I don't think...)

**Comment by mgrojo** [comment]
I'm the one to blame :) Temporary files in Qt are treacherous, if the object is destroyed they are removed (OK, they are temporary), but it's easy to forget that. This is the second time that this behaviour bites us.

**Comment by mgrojo** [comment]
Ok, that should be fixed now. Tested in Ubuntu 20.04.

**Comment by chrisjlocke** [comment]
Confirmed.  Thanks for the quick fix @mgrojo. Appreciated as always.  👍

**Comment by remysucre** [comment]
Hitting exactly the same behavior on macOS 15.4 now, both for release 3.13.1 and the nightly. There's another open issue #2492 for mac, but for me importing from a file worked fine, just not from the clipboard.
