### ISSUE TITLE
Creating Foreign Key Not Working

### ISSUE THREAD

**Issue by AnthonyUccello** [sqlitebrowser/sqlitebrowser#275]
Howdy

I have two tables:
characters
weapons

My characters table has a column: weaponId
This I need to reference to the id in Weapons table.

In my weapons table I have made sure there is an id column, and its the primary key.

I have foreign keys allowed in my schema.

When I go to edit table, on the Characters table, and I click the 'weaponID' column, and I type in for the foreign key weapons (id) my SQL log looks as follows:

```
CREATE TABLE `characters` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`weaponId`	INTEGER,
	FOREIGN KEY(`lweaponId`) REFERENCES weapons (id)
);
```

However when I click OK, the foreign key is not there at all. Its never saved (and I've tried weapons(id) as well to check if it was a formatting issue).

Can you advise what the issue may be? :)

PS I tried doing a manual SQL query too:

```
ALTER TABLE `characters` 
(
	ADD FOREIGN KEY (`weaponId`) REFERENCES `weapons`(id)
);

Error Log: near "(": syntax error: 
```

**Comment by rp-** [comment]
1. what version are you talking about?
2. what "edit table" do you exactly mean?

**Comment by Z4us** [comment]
@AnthonyUccello - How does the structure of your table `weapons` look like?

**Comment by AnthonyUccello** [comment]
@rp- By edit table I mean modify table. When I want to add a foreign key here:

![sql](https://cloud.githubusercontent.com/assets/3809669/7395387/92dd86e0-ee67-11e4-9256-b88e48574741.png)

My version is: 3.5.1

@Z4us Its just got a row with an id column which is the primary key

![sql](https://cloud.githubusercontent.com/assets/3809669/7395420/c0ade204-ee67-11e4-9c9b-d5d4c3c23d22.png)

**Comment by AnthonyUccello** [comment]
(Sorry for the typo weappons in the image, but the issue is the same regardless, I've tried weapons(id) and weapons (id), and manual SQL attempts).

**Comment by justinclift** [comment]
@AnthonyUccello Have you tried our newest release? It has a lot of updates in it, including some foreign key stuff.

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.6.0

If you've already tried that though, no worries. :smile:

**Comment by AnthonyUccello** [comment]
Updating to 3.6 fixed the issue. Closing this.

You guys work fast ^_^
