### ISSUE TITLE
"Trophy_Collator" Crash

### ISSUE THREAD

**Issue by InochiPM** [sqlitebrowser/sqlitebrowser#2752]
#### What did you do?
Tried to edit Trophy name & Trophy description from Madoka Magica The Battle Pentagram

#### What did you expect to see?
The changes in the file to apply.

#### What did you see instead?
![2021-06-22 20_34_08-](https://user-images.githubusercontent.com/13459080/123016914-9f3d8c00-d399-11eb-8bbf-d7e6699f6920.png)

#### What operating system are you using?

- [x] Windows: (10)

#### What is your DB4S version?

- [x] 3.12.2

**Comment by justinclift** [comment]
Um, that's a warning message.  Did you make a backup of your database (important!), then proceed with editing your database to see if it works?

**Comment by mgrojo** [comment]
Ideally, all these dialogs should have a Help button linking to a clarifying wiki article, or to a [corresponding SQLite3 page](https://sqlite.org/datatype3.html#collation) (in this case might be too technical though).

**Comment by InochiPM** [comment]
> Um, that's a warning message. Did you make a backup of your database (important!), then proceed with editing your database to see if it works?

It actively crashes the whole program the second i hit apply, this pops up and before you can even hit the button its in the middle of crashing.

**Comment by i-s-o** [comment]
A shot in the dark:
*Madoka Magica The Battle Pentagram* sounds like a game: is the db you are trying to edit part of a larger app? If that is the case, maybe the app provides some loadable modules/libraries that provide a special collating sequence to sort certain fields.  And, if you open the db outside the app, maybe DB4S can't find those modules, and complain about missing collating sequence.

**Comment by oldlaptop** [comment]
For reference, I can't reproduce this with a [simple test database](https://github.com/sqlitebrowser/sqlitebrowser/files/6721035/collation-sample.zip) using a custom collation sequence (https://gist.github.com/oldlaptop/cd16145c76939334d927b55f0c3c8b8e - may also be helpful for understanding what a custom collation sequence does). @InochiPM, it would probably be helpful if you could provide a copy of the database that fails for you.

**Comment by justinclift** [comment]
> @InochiPM, it would probably be helpful if you could provide a copy of the database that fails for you.

Actually, yeah.  If that's at all possible, then one of our developers would probably be able to at least figure out why it's crashing there, and if that can be worked around. :smile:

**Comment by InochiPM** [comment]
I actually got it to work once i exported it as the one format with the S and then reimported it and they work fine now!
