### ISSUE TITLE
Trigger Not Recognising NULL Records

### ISSUE THREAD

**Issue by mhunter808** [sqlitebrowser/sqlitebrowser#2756]
I've written a trigger to update NULL records after insert, but the trigger doesn't fire/seem to recognise NULL records.

CREATE TRIGGER "DATE"
after insert on "TEST"
for each row
when "DATE" IS NULL
begin
update "TEST"
set "DATE" = date(current_timestamp,'localtime');
end;

![image](https://user-images.githubusercontent.com/86662010/123793965-ad555480-d925-11eb-9531-0342ab2350c5.png)

When inserting a new record, and the value is NULL, I expect the trigger to update the record accordingly, however it doesn't.

![image](https://user-images.githubusercontent.com/86662010/123799098-3458fb80-d92b-11eb-8eb7-fea4c5db78ce.png)

If I change the "when" criteria in the trigger to something else, like, != '2020-06-29' or something:

CREATE TRIGGER "DATE"
after insert on "TEST"
for each row
when "DATE" != '2021-06-29'
begin
update "TEST"
set "DATE" = date(current_timestamp,'localtime');
end;

![image](https://user-images.githubusercontent.com/86662010/123799597-ba754200-d92b-11eb-8663-c9eb03331c1d.png)

and then try to insert a record (where the value != '2020-06-29'), the trigger fires & updates accordingly. For some reason, it just doesn't recognise/fire on NULL records, and I can't for the life of me figure out why.

![image](https://user-images.githubusercontent.com/86662010/123799645-c5c86d80-d92b-11eb-836d-00fb96117f23.png)

Useful extra information
-------------------------
#### What operating system are you using?
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] macOS: (version: macOS Big Sur 11.14)
- [ ] Other: ___

#### What is your DB4S version?
- [X] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also
- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I had a play with this and coulnd't get it working either, then couldn't get triggers working, then ..... argh!  It's not fun...

**Comment by MKleusberg** [comment]
You'll want to make two changes to your trigger:

```sql
CREATE TRIGGER "DATE"
after insert on "TEST"
for each row
when new."DATE" is null  -- first change here: This solves your original problem "DATE" alone doesn't point anywhere at this point. Instead you need to add a reference, either "new" or "old". Because we're inserting here only "new" is a valid option.
begin
update "TEST"
set "DATE" = date(current_timestamp,'localtime')
where rowid=new.rowid; -- second change here: This make sure you're only setting the DATE column of the record that was just inserted. Without this you're updating all records in the table.
end;
```

Does this help, @mhunter808?

**Comment by mhunter808** [comment]
> You'll want to make two changes to your trigger:
> 
> ```sql
> CREATE TRIGGER "DATE"
> after insert on "TEST"
> for each row
> when new."DATE" is null  -- first change here: This solves your original problem "DATE" alone doesn't point anywhere at this point. Instead you need to add a reference, either "new" or "old". Because we're inserting here only "new" is a valid option.
> begin
> update "TEST"
> set "DATE" = date(current_timestamp,'localtime')
> where rowid=new.rowid; -- second change here: This make sure you're only setting the DATE column of the record that was just inserted. Without this you're updating all records in the table.
> end;
> ```
> 
> Does this help, @mhunter808?

Yes, that did it. Thanks for your help!
