### ISSUE TITLE
Problem starting db browser for sqlite on windows 10

### ISSUE THREAD

**Issue by Sanballat** [sqlitebrowser/sqlitebrowser#2757]
Hi,
I'm new to sqlite and want to use it on windows forms application. After downloading and installing the db browser for sqlite, every attempt to start the browser results in this system error: "The code execution cannot proceed because VCRUnTIME140_1.dll was not found. Reinstalling the program may fix this problem." I have reinstalled the db browser for sqlite  program several times without any change in my situation. Any way out for me? What else should I do?
![System Error](https://user-images.githubusercontent.com/86726652/123970236-dc64d800-d9b0-11eb-9eeb-ae57b3325247.jpg)

**Comment by sandman7920** [comment]
This DLL is part of **Microsoft Visual C Runtime** which should be shipped with the application.
What version did you install?

**Comment by chrisjlocke** [comment]
I don't think we ship the runtimes anymore, as most PCs have them already.
@Sanballat - Can you download/run/install this and see if it works?
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by chrisjlocke** [comment]
> and want to use it on windows forms application

You're building your own databases?  Using .Net?  VB or C#?

**Comment by Sanballat** [comment]
@sandman7920 
I installed version 3.12

**Comment by Sanballat** [comment]
@chrisjlocke 
I am trying to build my own database in C#.

**Comment by justinclift** [comment]
Oh, I do remember another reported problem along these lines from a while back.  

@Sanballat As Chris mentions, there's an official download for what sounds like the right missing piece here:

&nbsp; &nbsp; https://www.microsoft.com/en-us/download/details.aspx?id=48145

Ignore the big banner ad at the top of the page there. :roll_eyes:  You're after the "Visual C++ Redistributable for Visual Studio 2015".

Grab and install both the 32-bit (`vc_redist.x86.exe`) and 64-bit (`vc_redist.x64.exe`) versions from that page.

In theory (!), that should fix the problem. :smile:

**Comment by chrisjlocke** [comment]
> I am trying to build my own database in C#

Cool.  DB Browser for SQLite (once you install the runtimes) should get you up and running to build the database itself.
You then need the SQLite library for Visual Studio.
Download the 32-bit
https://system.data.sqlite.org/downloads/1.0.114.0/sqlite-netFx46-binary-Win32-2015-1.0.114.0.zip
and the 64-bit
https://system.data.sqlite.org/downloads/1.0.114.0/sqlite-netFx46-binary-x64-2015-1.0.114.0.zip

You only need System.Data.SQLite.dll in the 'debug' (or 'release') directory, then the 'SQLite.Interop.dll' from the 32-bit ZIP in a 'x86' directory (in the debug directory) and the 'SQLite.Interop.dll' from the 64-bit ZIP in a 'x64' directory (in the debug directory)

```
Application directory
   |--- debug
   |       System.Data.SQLite.dll
   |       |
   |       +--- x86
   |       |      SQLite.Interop.dll
   |       |        
   |       +--- x64
   |             SQLite.Interop.dll
```
Then in your project you just need to reference system.data.sqlite.dll

**Comment by Sanballat** [comment]
Thank you for your help @justinclift. I just downloaded and attempted to install both the x64 and x86 without success. This is the message displayed.
![Failed_Untitled](https://user-images.githubusercontent.com/86726652/124004882-5d7f9780-d9d0-11eb-8baa-d0a0639027cf.png)

**Comment by justinclift** [comment]
Hmmm.  Ok.  Sounds like it might be needing a version of the "Visual C++ Redistributable for Visual Studio" that's not from 2015 then.

---

Ahhh.  Yeah.  From doing some searching online, it looks like it's really after the 2019 version.  Oops, sorry. :facepalm: 

This page seems to be the right one:

&nbsp; &nbsp; https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

The direct download links look to be:

* https://aka.ms/vs/16/release/vc_redist.x86.exe
* https://aka.ms/vs/16/release/vc_redist.x64.exe

Hopefully *that* works. :smile:

**Comment by Sanballat** [comment]
@justinclift
Thank you so much. Your last suggestion worked smoothly; I successfully installed the Microsoft Visual C++ redistributable and the db browser runs smoothly. I can now continue my project development. Once again thank you @justinclift, @chrisjlocke , @sandman7920.

**Comment by justinclift** [comment]
You're welcome, hopefully it all ends up going pretty well. :smile:

**Comment by JannetGen** [comment]
I’d try reproducing it with a copy of the database first, just to rule out file locking or another process modifying it. If it still happens, checking the DB Browser version and the SQLite library it’s using would be a good next step.
