### ISSUE TITLE
Intermittent error: 'Connection closed'

### ISSUE THREAD

**Issue by lemelinm** [sqlitebrowser/sqlitebrowser#2759]
So, I don't know what and why I have this problem.  If I get the error, I cannot work with it.  I restart the computer and the issue will still be there.  Then, during the day, I was doing something else and then I decided to try starting DB again and BANG success!!!
Can someone tell me how DB is working? I am not a beginner nor a pro, but a clean explanation would be very appreciated.
I need DB to continue a course in python ([https://www.py4e.com]). And the part on the databases really interests me.

I installed DB with the windows installer.  I even installed it with the zip file and the result is the same.
I am working under Windows 10 Pro x64 20H2 as you can see at the bottom.

![DB bug](https://user-images.githubusercontent.com/61095867/124360169-5b971d80-dbf6-11eb-9cab-fd258f945e13.png)

Thank you in advance for your help.
Mario

--------------------

#### What did you do?
I open DB

#### What did you expect to see?
DB ready to work.

#### What did you see instead?
See the attach file.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I haven't seen this before.  This is usually related to sqlite itself where it has a connection to the database, but it's closed.  I sometimes see this in my own database development, but I work over a VPN, so if that connection goes, then I get this error.
We've not had other reports of this, so we need to get more details.

When you open/create/use the database, is this on your local machine?  Is it on a normal folder, or using something wacky like WSL, or network share, etc.

**Comment by chrisjlocke** [comment]
I can't see 'Connection closed' in the source files, so assume it's coming from SQLite itself.  Bit weird we're just throwing the text 'naked' and not reporting 'an error has occurred blah blah blah - '%error%', etc...

@lemelinm - Does the box pop up randomly whenever you use DB4S, or always if you do X, Y and Z?  I appreciate what you said about 'I decided to try starting DB again and BANG success', but was that doing the same steps you did that caused the problem previously?

**Comment by lemelinm** [comment]
Thank you for that fast response. Now, I have just restart DB4S and it continues to pop up randomly when I open it.  
Thank you for helping me.
Mario

**Comment by justinclift** [comment]
@lemelinm Is the database you're working on, local to your computer?  (eg on your hard drive, or usb stick, or similar)  Or it is on a remote computer? (eg over a network or similar)

**Comment by lemelinm** [comment]
It is on my computer.  I am wondering about this piece of information.  Four years ago, I follow a course in Coursera that was title Data-Driven Astronomy. IN this course, I was using PostgreSQL and the server was on a remote computer. But I am not sure if I installed it on my computer.  Dam, it is installed on my computer!  Could it be that?  Now, I am really confused.  I am thinking about my **path** in Windows.

**Comment by chrisjlocke** [comment]
DB4S uses one file for its database - eg, 'squishy_lemons.db'.  The file is either on your desktop, 'my documents' folder, or on a network share somewhere.  Some people say 'its on my desktop' but their desktop is actually on a network, for example, or they're using WSL (Linux subsystem).  

Postgresql shouldn't have any bearing on this ... well, I can't see that it could, anyway.
All I can suggest initially is the usual Windows things - run a chkdsk, run a sfc scan (that can take a while) and make sure your event log is clean.  Yell back if you need further help on any of that stuff.

**Comment by lemelinm** [comment]
It is on my computer.  I am wondering about this piece of information.  Four years ago, I follow a course in Coursera that was title Data-Driven Astronomy. IN this course, I was using PostgreSQL and the server was on a remote computer. But I am not sure if I installed it on my computer.  Dam, it is installed on my computer!  Could it be that?  Now, I am really confused.  I am thinking about my **path** in Windows.

**Comment by justinclift** [comment]
> Dam, it is installed on my computer! Could it be that?

Very unlikely.  Our application itself only uses SQLite, so any installed PostgreSQL pieces aren't really relevant even if they're in the path. :smile:

**Comment by chrisjlocke** [comment]
@lemelinm - Did you copy and paste the same comment again?

**Comment by lemelinm** [comment]
First, when I start DB4S, I haven't open anything yet.  I have it installed by Windows and it is here:
C:\Program Files\DB Browser for SQLite
Then I click on the OK button on the little window that you can find at the beginning of this thread. Then I open this one database that I created in python name trackdb.sqlite located here:
D:\Cours\Cours PY4E Python\Codes\tracks

So it seems that I can work with DB4S without any problem. I will check if this message is connected with SQLite.
Again, thank you for your help.
Mario

**Comment by lemelinm** [comment]
> 
> 
> @lemelinm - Did you copy and paste the same comment again?

No!

**Comment by chrisjlocke** [comment]
OK, so you start DB4S, and before opening any database, the error appears?  That's interesting, as it would appear the error is coming from the update check, and not from SQLite - this is helpful.
If you click 'Edit' and 'Preferences', you can turn off the 'Automatic updates' option.

![image](https://user-images.githubusercontent.com/7872218/124395969-f549f200-dcfe-11eb-96f1-d77dffc34ebd.png)

If you close and open DB4S again, does the error pop up again?
Theoretically, this check only occurs when you start DB4S, but you mention it occurs randomly when using DB4S, so it may not be this after all, but useful to rule it out, just in case...

**Comment by lemelinm** [comment]
@chrisjlocke  Congratulations!  This error window does not appear anymore.  I hope you will be able to find out why this happens. 
So fantastic support and I must say that I love this software.  Easy to use and fast too.  Again, THANK YOU VERY MUCH!
Mario

**Comment by chrisjlocke** [comment]
Can you explain your network setup?  Do you use a VPN?  Are you behind some proxy or something?  Or I'm guessing its something SSL related, but as you're on Windows, I have no idea if/why/how that would have occurred.
Guessing @justinclift might be able to spot something in some server logs somewhere, but I'm guessing that'd be like looking for a needle in a rather large haystack.  I'm just thinking rather than displaying an error, it would be useful if DB4S would display the routine the error occurred in - would help pinpoint this sort of thing...  Had something similar when someone at work got a random 'file not found' error in an in-house application.  What file - what routine was moaning - where was it looking - and why - etc. 

I won't close this, as ideally this issue still needs properly addressing - either a better error or identifying what's going on.  But thanks for your patience, for reporting this and glad it got 'resolved' (sort of...)

**Comment by lemelinm** [comment]
@chrisjlocke chrisjlocke
Ok! For that, I have produce a Word [document](https://www.dropbox.com/s/do50xke9st7d5rq/Network%20Setting.docx?dl=0) that list all the parameters about my network. Since I am not a specialist in Networking, if you need other informations, just ask and I will give it to tyou.
As always,
Thank you!
Mario

**Comment by chrisjlocke** [comment]
Aah, so you're using NordVPN.  That might have something to do with it?  I'm guessing our servers don't like that ... although I can't think why ... just the obvious 'elephant in the room' that stands out.
Everything else seems 'normal'... 

Thanks for the document.  👍

**Comment by MKleusberg** [comment]
Hmm, I don't know either. So I have just pushed a change which hides this error message. It still won't work but at least there's no annoying error message which we probably can't do anything about anyway :wink: I'll just close this issue now. But everybody is more than welcome to reopen it if they have any idea what else we can do here.
