### ISSUE TITLE
Open Database

### ISSUE THREAD

**Issue by xjpmauricio** [sqlitebrowser/sqlitebrowser#276]
the Open Database button does not restore the last folder opended. It's allways opening on the same folder: my user folder.

OS: windows 7

**Comment by justinclift** [comment]
Yeah, there seem to be two main ways of thinking about this.  One is that the "last opened folder" should be opened... and the other is that the folder defined in Preferences should always be used.

At the moment, it always opens the folder defined in Preferences.  We get asked often enough though, that we should probably make this behaviour changeable.

**Comment by xjpmauricio** [comment]
In my opinion, the last version's behaviour is more correct: allways open in the last folder selected but, someone else might not like it that way. It might be a matter of personal taste, I don't know.

**Comment by justinclift** [comment]
Aha, found one of the previous Issues about this: https://github.com/sqlitebrowser/sqlitebrowser/issues/224

**Comment by glawrence** [comment]
I reckon we might need a preference checkbox to keep everyone happy. Personally I expect "default location" the first time I ever use an app. Then on each subsequent start of the app I expect either default or last used. However once I have open a file I then expect the next open to start from there.

Anyway, how about a preference which is a combo box with some options:

"Open Database" directory
- default location as specified
- same as last file used
- same as last but default for new session

Ok, so not great UI design but just some thoughts.

**Comment by justinclift** [comment]
Decent thoughts.  I kind of remember we've had some discussion about it in our early issues as well, which is probably worth digging through to make a proper proposal with (which covers all bases).

I'm kinda busy on some other stuff (not related to DB4S) for the next 2-3 weeks, so I have no idea if I'll get to look at it before then. You're definitely welcome to if you want. :smile:

**Comment by MKleusberg** [comment]
I think the approach suggested by @glawrence should make everybody happy. So I've just pushed an implementation of this which should work for all file dialogs. The default settings is now set to the 'same as last but default for new session' option which seems to be the best compromise for new users and those upgrading to a new version.

**Comment by glawrence** [comment]
Thanks @MKleusberg I shall look forward to testing that in the nightly build.

**Comment by justinclift** [comment]
@xjpmauricio Would you be ok to test the latest nightly build too, and let us know if it's "working better" with the new approach? :smile:

**Comment by MKleusberg** [comment]
This should be fixed in the 3.7.0 release where we've introduced a new option to the Preferences dialog to change this behaviour. This way everybody should be happy :smiley:
![lastlocation](https://cloud.githubusercontent.com/assets/3153504/8273318/9c697f04-1868-11e5-9791-7dce9ff25cfe.png)
If there are no objections I think we can close these issue soon.

**Comment by justinclift** [comment]
@xjpmauricio Any interest in try our latest release, and letting us know if the new behaviour is better for you? :smile:

**Comment by xjpmauricio** [comment]
Hi justin, I installed version 3.7 and it works great! Everybody's happy!

**Comment by glawrence** [comment]
Great, thanks @xjpmauricio for testing and letting us know
