### ISSUE TITLE
ORDER of columns of the tables in the treeview

### ISSUE THREAD

**Issue by Raphael-MOUQUIN** [sqlitebrowser/sqlitebrowser#2762]
### Details
**ORDER of columns** of the tables:
In the treeview we have alphabetical ASCENDING order , 
In the Structure tab, DIFFERENT order than the one in the treeview

<img width="308" alt="scrshot_SQLiteStudio3 3 3_COLUMNS_ORDER" src="https://user-images.githubusercontent.com/86474028/124497691-854d7180-ddbb-11eb-8703-7698b6de46ce.PNG">

### Steps to reproduce
Issue apply to all tables/columns. Functionnality always active.

### Operating system
Win7

#### What is your DB4S version?
3.12.2

**Comment by chrisjlocke** [comment]
Is this your own build of DB4S?  The (small) screenshot you've provided doesn't seem like DB4S...

**Comment by i-s-o** [comment]
This looks like SQLite Studio question (oh, I see that you already posted this issue there: https://github.com/pawelsalawa/sqlitestudio/issues/4151).

The order of columns in the tree is selectable in the configuration dialog. If you are asking about changing the order in the *Structure* tab, that is most likely based on the `CREATE ...` statement used at the table creation time (i.e. the GUI probably doesn't touch it): see https://github.com/sqlitebrowser/sqlitebrowser/issues/2735 for a discussion on how DB4S handles the original `CREATE ...` statement.
 
![image](https://user-images.githubusercontent.com/1661549/124962905-2a02c580-dfed-11eb-93d7-a6b0f05da82f.png)

**Comment by chrisjlocke** [comment]
Aah, well spotted @i-s-o .  I'll close this then as its not DB4S related.
