### ISSUE TITLE
I cannot store data in my databse when i enter it on a form. 

### ISSUE THREAD

**Issue by HoodLegend** [sqlitebrowser/sqlitebrowser#2766]
Details for the issue
--------------------

#### What did you do?
whenever i enter data in a form it is not saved in the mysqlite database

#### What did you expect to see?
the data saved in the database so that i can see it on table.

#### What did you see instead?
Nothing no update whatsoever,

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Data in a form?  Can you please provide a screenshot of what form you're referring to?

**Comment by HoodLegend** [comment]
NO! I am developing an application using spring boot but whenever i enter data into the form in my html file it goes to the page redirected to but the data does not save to the sqlite database. My question is what could be the root cause of this? 
![Screenshot (27)](https://user-images.githubusercontent.com/61332272/124987365-154e1e00-e03d-11eb-9b0d-a43702c5f724.png)
the screenshot is one of the forms in my app. However, when the form is submitted the data does not appear in the db. 
![Screenshot (27)](https://user-images.githubusercontent.com/61332272/124987552-49c1da00-e03d-11eb-8f37-fb6bde9f201f.png)

**Comment by scottfurry** [comment]
In your web application, do you `commit` the data?
Not committing the transaction, which triggers a write of data to the database, is a common problem with sqlite-based applications.

**Comment by HoodLegend** [comment]
I dont know what that is i  m new at spring boot for web development. Kindly share how that is done. Thanks

**Comment by HoodLegend** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/61332272/124992835-c8ba1100-e043-11eb-97f9-3e1cfb3d45fe.png)
@scottfurry This is my Controller for the above form  i sent. 
And this is my entity class
![Screenshot (29)](https://user-images.githubusercontent.com/61332272/124993008-09198f00-e044-11eb-84eb-7cb74f1b8792.png)

**Comment by scottfurry** [comment]
I'm out of my depth in using Java/JDBC/Spring Boot. However, a quick google search got me to [this](https://fullstackdeveloper.guru/2020/05/01/how-to-integrate-sqlite-database-with-spring-boot/) page.

If I'm reading this right, the magic sauce is in step 4 line 3:
```
spring.jpa.hibernate.ddl-auto=update
```
Line tells Java that SQL Data Definition Language (i.e. SQL table syntax) is to update the table.
I suspect this is the step you are missing.

If this doesn't work, I would recommend hunting up a dedicated Spring Boot forum (this [page](https://www.javaspringhibernate.com/spring-framework-training/forum) seems active and applicable to needs).

**Comment by HoodLegend** [comment]
@scottfurry  Thanks a lot i already included that property in my project but still no avail. However, thanks for the info i ll check out the resources.

**Comment by scottfurry** [comment]
@HoodLegend - My impression is that there is some missing piece of nuance in hibernate causing you grief. Beyond the above and a suggestion to check file paths(i.e. you are opening the correct DB that the web application is writing to), I got nothin' else.

That's one of the difficulties of software - which library is the roadblock and where to ask for help. Sorry I can't be of more help. Hopefully, someone in the java world can point you to a better solution. Good Luck.

**Comment by chrisjlocke** [comment]
> I dont know what that is i m new at spring boot for web development. Kindly share how that is done. Thanks

Just a note that your initial issue simply said "whenever i enter data in a form it is not saved in the mysqlite database" and didn't mention Java, Springboot or anything else.  When asking for help, it's helpful to provide as much information as possible.  It's also helpful to ask the right people.  Primarily, this is an issue forum for the software DB4S (Database Browser for SQLite) which has nothing to do with Java or Springboot...
We're happy to help where we can, but your initial query is like going into a butchers, holding up a piece of cabbage and asking, "How does my lawnmower work?"

Have you looked on Youtube for example tutorials?  I've found that a great resource for explanation videos where people have gone into great depth on all topics.

**Comment by chrisjlocke** [comment]
I'll close this due to lack of further details.  Sorry we couldn't help further.
