### ISSUE TITLE
Insert row middle of the table and change row row position

### ISSUE THREAD

**Issue by akash55** [sqlitebrowser/sqlitebrowser#2769]
Describe the new feature
--------------------------
Adding row at the middle of the table, and moving up and down the row of the table
are essential features to insert row in any database, this will make it more user friendly.

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
I was going to offer help, but based on #2768 I feel my todger is being pulled.
Is this a genuine question?

**Comment by akash55** [comment]
Issue resolved, thanks

**Comment by justinclift** [comment]
@chrisjlocke Yeah, something seems weird.
