### ISSUE TITLE
Missing MSVCR120.dll

### ISSUE THREAD

**Issue by mgarcia01752** [sqlitebrowser/sqlitebrowser#277]
I downloaded the latest 3.6.0 and is reporting this missing .dll

**Comment by justinclift** [comment]
Yeah, you need to install the (free) Microsoft Visual C++ Redistributable Packages for Visual Studio 2013, available here:

&nbsp; &nbsp; https://www.microsoft.com/en-us/download/details.aspx?id=40784

It's pretty easy.

And yeah, if we can figure out how to bundle this dependency with future releases, that'd be better. :wink:

**Comment by JobaDiniz** [comment]
I have Microsoft Visual C++ Redistributable Packages for Visual Studio 2017, shouldn't it work with this?

**Comment by justinclift** [comment]
Hmmm, I'm not 100% sure.  I **think** the 2017 ones should work for the recent Win64 3.11.x releases, and also our recent Win64 nightly builds.

If you're using one of our Win32 releases, up until recently they were still created with MSVC 2013.  They've recently moved to MSVC 2015 though.

Which version of DB4S (and Win32/64?) are you hitting the problem with? :smile:

**Comment by JobaDiniz** [comment]
I’ve just downloaded 64bit version and it throws that error 
My server has 2017 installed. Once I installed 2013, the app worked

**Comment by justinclift** [comment]
> I’ve just downloaded 64bit version 

Just to be super clear... which 64 bit version? :smile:

**Comment by JobaDiniz** [comment]
The latest one from website

**Comment by justinclift** [comment]
Heh Heh Heh.  You can check the version number in Help -> About. :smile:

I'm persistently asking about this because (in theory) that shouldn't be happening for our 3.11.x versions.  So, wanting to find out, just in case to be aware of a potential problem.

**Comment by karim** [comment]
@JobaDiniz Ping?

**Comment by cikal** [comment]
DB4S win32 (latest  3.11.2), report same thing, and solved with this. [#277](https://github.com/sqlitebrowser/sqlitebrowser/issues/277#issuecomment-97437939)
thanks @justinclift

**Comment by justinclift** [comment]
You're welcome. :smile:
