### ISSUE TITLE
cli `--import-csv` option ignores the `--table` value

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2772]
Compiled the very latest DB4S `master` branch code just now (23a597bcd1a34395f1a6e1603c6401993f7eae97), then tried to import some csv files ([Backblaze HDD data](https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/data_2013.zip)):

```
~/git_repos/sqlitebrowser/build/sqlitebrowser --import-csv 2013/2013-04-12.csv --table somedata backblaze.sqlite
```

DB4S starts up, and pops up the CSV import dialog with the options filled out as per whatever they were last time (useful!).  Unfortunately, it's ignoring the table name passed in on the command line and using the default of "use the csv filename".

![2021-07-18-import_csv_cli_table_name-v1](https://user-images.githubusercontent.com/406299/126062073-42e15b71-1c10-4c69-b3f3-b886914bf87a.png)

**Comment by justinclift** [comment]
Note that I'm just leaving this bug report here in case someone has time to look at it.  While I **could** dig into the C code and try to figure this out, it'd likely take me all day and my focus is instead on getting some DBHub.io stuff done.

**Comment by justinclift** [comment]
As a data point, I was able to import the csv data for all the Backblaze 2013 csv files using the sqlite3 cli and this small bash snippet:

```
export dirname=2013
for i in `ls -1 ${dirname}`; do echo "Importing ${i}"; sqlite3 backblaze.sqlite << EOF
.mode csv
.import ${dirname}/${i} somedata
EOF
done
```

**Comment by mgrojo** [comment]
The `--table` option is for selecting a table to display in the table browser, we are not using it to name the table where the CSV data should be imported, although we could give it that double meaning and use that one in this context. Another option would be a specific option, like `--to-table`.

**Comment by justinclift** [comment]
Yeah, I figured it might be something like that. :smile:

I'm thinking we should probably just reuse the same `--table` option, as that'll probably make things easier and be less clutter in the `--help` text too.  eg less options

**Comment by mgrojo** [comment]
Ok, I've made that change and now `--table` can be used to specify the destination table of the import.

**Comment by justinclift** [comment]
Oh, that's pretty awesome!  I should have a chance to try it out over the next few days, or next weekend.  Thanks heaps @mgrojo. :smile:

**Comment by justinclift** [comment]
Just tested this, and it's working fine.  Thanks heaps @mgrojo. :smile:
