### ISSUE TITLE
Website Security issue

### ISSUE THREAD

**Issue by RebeccaOlson** [sqlitebrowser/sqlitebrowser#2776]
Details for the issue
--------------------

#### What did you do?
Tried to go to the website. 

#### What did you expect to see?
the website

#### What did you see instead?
A security warning from both Chrome and Firefox that:
 
Your connection is not private
Attackers might be trying to steal your information from sqlitebrowser.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_10 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [x ] 3.11.x
- [ ] Other: ___

#### Did you also

- [x ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by Sairenity** [comment]
Looks like the SSL Certificate expired!

**Comment by justinclift** [comment]
That's weird, could have sworn I renewed that.  Thanks for the report, looking into it now. :smile:

**Comment by justinclift** [comment]
Yep, looks like I renewed _some_ of our certs, but somehow missed a bunch of others. :facepalm:  No idea why.

Updating them now.

**Comment by justinclift** [comment]
The log file isn't real useful either:
```
2021-07-20 15:57:26,180:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: nightlies.sqlitebrowser.org
Type:   unauthorized
Detail: Incorrect TXT record "O5MglJngNZh4DCIj0EhiE8hjk448dANTw7lbGFryM8k" found at _acme-challenge.nightlies.sqlitebrowser.org

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
```

No idea how the heck it's getting the wrong (prob old?) value, when I manually logged into the server before that and queried the exact same value with dig, and got the right value:

```
# dig -t txt _acme-challenge.nightlies.sqlitebrowser.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.5 <<>> -t txt _acme-challenge.nightlies.sqlitebrowser.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45902
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_acme-challenge.nightlies.sqlitebrowser.org. IN        TXT

;; ANSWER SECTION:
_acme-challenge.nightlies.sqlitebrowser.org. 900 IN TXT "3b8C_M-dcaFQitlHhdy37iS-9jnEWFzj1cC0f0cNoZc"

;; Query time: 303 msec
;; SERVER: 67.207.67.3#53(67.207.67.3)
;; WHEN: Tue Jul 20 15:57:19 UTC 2021
;; MSG SIZE  rcvd: 128
```

**Comment by justinclift** [comment]
4th time lucky, this time around it worked.  Wonder if they're having capacity issues on the Lets Encrypt side or something?

**Comment by RebeccaOlson** [comment]
Thanks!!! it's working now! I appreciate your quick response!

**Comment by justinclift** [comment]
You're welcome, thanks for letting us know. :smile:
