### ISSUE TITLE
Certificate Expired - Security Issue

### ISSUE THREAD

**Issue by veldy71** [sqlitebrowser/sqlitebrowser#2777]
Go to the https://sqlitebrowser.org/ site and there are security warnings about an expired certificate.  Running the software application on windows complains about the same with:

![image](https://user-images.githubusercontent.com/6292518/126355185-1b19030d-a3a5-4dfa-b84e-358424538799.png)

**Comment by veldy71** [comment]
It looks like this is a duplicate of #2776

**Comment by justinclift** [comment]
Yeah, sorry about that.  I renewed a bunch of certs a while ago, but somehow missed these ones. :frowning:
