### ISSUE TITLE
BLOB with text (json) is empty at 3.6.0 (32 or 64)

### ISSUE THREAD

**Issue by igozhenko** [sqlitebrowser/sqlitebrowser#278]
See bellow results of query.
`SELECT docs.doc_id, docs.docid, revs.revid, revs.json result FROM docs, revs WHERE docs.doc_id = revs.doc_id AND json IS NOT NULL AND docs.docid LIKE '%Attachment%'`
3.5.1
![3 5 1](https://cloud.githubusercontent.com/assets/2979445/7394422/1ec6bb02-ee9c-11e4-80d2-f41fa526e4df.png)
3.6.0
![3 6 0](https://cloud.githubusercontent.com/assets/2979445/7394424/1ff31368-ee9c-11e4-8561-a6c365ea6e98.png)

BLOB fields are empty during simple view of table.
![image](https://cloud.githubusercontent.com/assets/2979445/7394468/71b1c1e0-ee9c-11e4-9eb5-5c8b11b3d064.png)
Click on BLOB field show nothing
![image](https://cloud.githubusercontent.com/assets/2979445/7394474/802c3b4c-ee9c-11e4-9d03-367743e65129.png)

**Comment by justinclift** [comment]
Oh, that doesn't sound good.  @samir-aguiar this sounds like your kind of thing to look at?

**Comment by schdub** [comment]
It's definitely after #256.

Игорь, спасибо за баг-репорт.

> Click on BLOB field show nothing

Пожалуйста проверьте, действительно ли значение поля json для строки doc_id=1, revid=1-39757369ecc4... не равно NULL? Так же попробуйте открыть для редактирования значение поля json для строки doc_id=103, revid=1-4991b88e971f... (первая строка на первом скриншоте), так же в "Edit database cell" будет пусто? Если пусто, то пожалуйста сообщите как вставляются данные в эту таблицу (чтобы воспроизвести проблему). У меня, при редактировании BLOB-значения окно "Edit database cell" остаётся пустым только если значение данного поля равно NULL, о чем свидетельствует надпись "Typе of data currently in cell: Null".

По поводу того, что в 3.6.0 отображается надпись BLOB вместо текста самого BLOB-значения - это ожидаемое поведение после приведённого выше фикса, если бы тип колонки был TEXT, то все бы отображалось верно.

**Comment by igozhenko** [comment]
@schdub проверил, действительно значение было NULL

![image](https://cloud.githubusercontent.com/assets/2979445/7424885/fb4a1c0e-efaf-11e4-8e03-3b75414abcfe.png)


>По поводу того, что в 3.6.0 отображается надпись BLOB вместо текста самого BLOB-значения - это ожидаемое поведение после приведённого выше фикса, если бы тип колонки был TEXT, то все бы отображалось верно.

Очень жалко, так как искал специльно программу которая позволит быстро просматривать и копировать поля с типом BLOB.

**Comment by schdub** [comment]
Somebody trying to fix this issue?
If not, #285 returns display blob text fields as in version 3.5.1

**Comment by schdub** [comment]
@igozhenko, we've added the code that was supposed to solve the problem with displaying of text BLOB. Could you test?

**Comment by igozhenko** [comment]
@schdub where could I download it to test?

**Comment by schdub** [comment]
@igozhenko, changes will apply in tomorrow build.
Nightly builds (uncompress them with 7-Zip) are available at:
http://rp.oldsch00l.com/sqlitebrowser/

**Comment by igozhenko** [comment]
@schdub  works for me, thanks
![image](https://cloud.githubusercontent.com/assets/2979445/7493027/0a0e15ba-f406-11e4-88f0-fb08f3cd0a2d.png)

**Comment by justinclift** [comment]
Awesome. :grinning:

Thanks for testing this and letting us know @igozhenko. :smile:
