### ISSUE TITLE
Add file extension associations for Windows (and maybe OSX)

### ISSUE THREAD

**Issue by rheinheimer** [sqlitebrowser/sqlitebrowser#279]
On the 32-bit version of sqlitebrowser for Windows (W7P x64), I can set sqlite files to automatically open with sqlitebrowser. However, I was unable to do this for the 64-bit version. Just letting you know. Thanks!

**Comment by justinclift** [comment]
Oh interesting.  I'll setup a Win7 vm after work tomorrow and see if I can figure out what's wrong.

Which method(s) did you try for doing the file association?

**Comment by rhenish** [comment]
I right click, "open with...", "Browse...", then select the sqlitebrowser executable "C:\Program Files\SqliteBrowser3\bin\sqlitebrowser3.exe". Normally, the application would then appear back in the application selection screen. In this case, however, it doesn't appear, so I can't select it. It would be useful to get confirmation.

p.s. I also just tried using the "Default Programs" route, but same issue.

**Comment by hko-gh** [comment]
Had the same issue for the 64 bit version. I figured that the registry entry is still pointing to the wrong directory. So in HKEY_CLASSES_ROOT\Applications\sqlitebrowser3.exe\shell\open\command the value needs to be changed from "C:\Program Files (x86)\..." to  "C:\Program Files\..."

**Comment by justinclift** [comment]
Thanks @hko-gh. I hadn't gotten around to look at this yet after all. :wink:

With that registry key... it doesn't seem to be in CMakeLists.txt, so I'm wondering where in our source it comes from so we can update it.  Can't see it though. :frowning:

**Comment by maxslimmer** [comment]
If I remove HKCR\Applications\sqlitebrowser.exe and then associate with "c:\Program Files\sqlitebrowser3\bin\sqlitebroswer.exe" windows keeps the association. But if there is an exisiting shell\open\command (with an incorrect path) for the application it does not.
Maybe the installer made by cmake nsis generator works in a similar way. Without an explicit removal of that key it just leaves the exisiting?

**Comment by ts-web** [comment]
I had the same issue (Couldn't register the 64-bit as the default program after having the 32-bit).
The [solution](https://github.com/sqlitebrowser/sqlitebrowser/issues/279#issuecomment-98643971) by @hko-gh worked for me.

**Comment by justinclift** [comment]
Sounds like a wiki page with instructions would be useful.  Is anyone up for knocking up together (even very basic)?

**Comment by maxslimmer** [comment]
Well its *very* basic but here's a start. I didn't know how to do a pull request on a wiki so https://github.com/maxslimmer/sqlitebrowser/wiki/Windows-File-Associations

**Comment by justinclift** [comment]
Cool, that looks like a good start. :smile:

Would you be ok to create it in the main wiki, and add a link to it from the main wiki page so people can see it?

**Comment by glawrence** [comment]
Having first edited @maxslimmer copy of the Wiki I have now coped this to the sqlitebrowser wiki and added the link.

@justinclift let me know if we need anything else doing but I think we can close this issue now like #296

**Comment by justinclift** [comment]
Yeah... I'm just wondering if we can put some kind of info somewhere for people to easily find about this.

Maybe we should update the Release Note info to mention something like "If you're upgrading from the 32-bit to 64-bit release on Windows, you may need to change a registry entry so file association works.  Details [here]." with [here] being a link to the wiki page.

That's the best approach that I'm thinking of atm... anything better spring to mind for you?

**Comment by glawrence** [comment]
I have seen other software do one of two things:

- put a check box in the installer, so users can opt in to file association if they want
- options in the preferences for file association

Pretty sure this is possible either way, another option is both. However I think we need to support multiple and possibly custom file extensions given sqlite files don't have a standard extension

**Comment by justinclift** [comment]
Good thinking.  They're definitely both suitable for a future version.  I'm wondering more about what to do with the current one though, so people know. :smile:

**Comment by glawrence** [comment]
I guess we need a good wiki page and a Tweet? Or something like that anyway. Maybe http://sqlitebrowser.org/ should link direct to the wiki, as well as GitHub, some people might not know there is documentation in the form of the wiki on the GitHub site.

**Comment by justinclift** [comment]
Good idea.  Let's do that. :smile:

**Comment by justinclift** [comment]
Yeah, we should add an option for setting file associations for the next release.

Especially considering the 3.9.0 release changed the install path again.

/me completely forgot about potential impact of that on file associations

**Comment by justinclift** [comment]
Looking into this a bit, it seems like we could add an option to our installer for people to choose whether to "Associate file extensions?" or not.

There's no direct support for doing so in CMake's "CPack" (which controls the NSIS packaging process), but it should be feasible using some of the "extra install" commands.

* https://cmake.org/pipermail/cmake/2009-January/026252.html
* https://cmake.org/cmake/help/latest/module/CPackNSIS.html?highlight=cpack_nsis_extra_install_commands#variable:CPACK_NSIS_EXTRA_INSTALL_COMMANDS
* https://cmake.org/Wiki/CMake:CPackNSISAdvancedTips

Adding "options" to the generated installer might be done through components:

* https://cmake.org/Wiki/CMake:Component_Install_With_CPack

This may turn out to be useful as well:

* https://github.com/toeb/cmakepp#feature-overview

**Comment by AdamPS** [comment]
Thanks, an option in the installer sounds excellent.  This would also help the users who had created associations by hand that subsequently got broken with renaming.

You will need to decide what extensions to use.  As a starting point for that, according to http://stackoverflow.com/questions/808499/what-is-the-best-extension-name-sqlite-database-files 

> Emacs expects one of db, sqlite, sqlite2 or sqlite3 in the default configuration for sql-sqlite mode

**Comment by justinclift** [comment]
Good thinking @AdamPS. That does look like a useful source of info on commonly used file extensions. :smile:

**Comment by chrisjlocke** [comment]
Just tried this on my Windows 10 machine, and some useful 'quick' command line tools. 
So, from an administrative command prompt (not just a command prompt when logged in as a user with admin rights, but right click the 'cmd' shortcut and 'run as admin') type these commands:
`assoc .db=sqlite3Database`
`ftype sqlite3Database="C:\Program Files\DB Browser for SQLite\bin\DB Browser for SQLite.exe"`

Obviously, change your paths / file extensions as required.

![image](https://cloud.githubusercontent.com/assets/7872218/17974778/4e497e76-6adf-11e6-8e30-7195e288e8bd.png)

Obviously, the right click 'Open With...' dialog is also good, but it has its quirks....

![image](https://cloud.githubusercontent.com/assets/7872218/17974912/d45e30a6-6adf-11e6-851c-9666f8495efd.png)

**Comment by justinclift** [comment]
@chrisjlocke Cool, those `assoc` and `ftype` commands look useful. :smile:

With the `3.9.0` release, it installs into ... `\DB Browser for SQLite\3.9.0\` with the `bin` directory + files inside that.  So, the paths will be slightly different than shown.

**Comment by chrisjlocke** [comment]
Yes, I removed the '3.9.0' from my install, and added the 'change your paths / file extensions as required' to the above instructions!  Just my personal preference, but on my main machine, I don't install into separate directories.

I've used Inno Setup in the past to create Windows installs.  That does optional (ie, via checkboxes) file associations, but a user preference in the program is always welcome.

**Comment by AdamPS** [comment]
A user preference in the program would be convenient.  However it needs to be done carefully because changing file associated settings needs temporary escalation to Administrator access.

I feel that the developers should choose either install time or a subsequent preference depending on implementation factors.  As a user, I would welcome and can adapt to either.

**Comment by justinclift** [comment]
Makes sense.  I'll look into doing it via the installer.  But, probably won't investigate today.

Feeling a bit burnt out from the hectic last few days getting the release ready.  Ironically... I need a holiday. 😁

**Comment by justinclift** [comment]
Realised something important.  We don't really **need** to use CMake for creating the installer.  The way things are configured now, CMake drives the NSIS packaging program, but doesn't make easy the wide variety of things that NSIS allows.

If we just use NSIS directly, it shouldn't be too hard to make an installer which does what we want, including optional creation of file associations.

Note - This wouldn't be my first time around with NSIS either.  I've used it occasionally on an off over the years (eg creating the first OpenOffice.org .exe installer, the [Libvirt installer for Windows](https://github.com/justinclift/nsis_libvirt_installer), and others).

So... I'll give this a go shortly and see if the result is decent. :smile:

**Comment by justinclift** [comment]
Other Open Source projects have their NSIS scripts online too, and some of the pieces in them we can probably copy/adapt.  eg from VLC:

* https://github.com/videolan/vlc/blob/master/extras/package/win32/NSIS/vlc.win32.nsi.in#L224-L230
* https://trac.videolan.org/vlc/ticket/4323

This will probably fix #742 on the way through too.

**Comment by justinclift** [comment]
Aha, this looks like the thing we want:

* https://github.com/videolan/vlc/blob/master/extras/package/win32/NSIS/helpers/extensions.nsh

**Comment by AdamPS** [comment]
Excellent.  One other thought - if possible please can the installer allow a reconfigure option to change the setting of any config options without forcing a reinstall.  Often when I am evaluating software, I don't want to take over existing extensions.  But then when I decide to use it to replace my existing software, I want to go back and enable the extensions.

**Comment by justinclift** [comment]
@AdamPS That makes good sense.  While looking into "how to set up file associations with NSIS?", several other posts on the topic (for other applications) have mentioned that exact same thing. :smile:

It's probably going to be faster (for now) to add the file extension support into our "Preferences" dialog somewhere.  It would mean they're not set during installation (yet), but instead you can enable them when you want in the running program.

That's the theory anyway. :wink:  More detail than that is probably a bit hard to do right now.  We'll need to write some code to get a better practical understanding of things first. 😁

**Comment by glawrence** [comment]
Nice info for Windows 10 with assoc and fstype @chrisjlocke any chance you could add this to https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations please?

**Comment by justinclift** [comment]
@chrisjlocke (and others): What would the "optimal" directory layout be?

* Maybe having everything (except plugins/platform) in "C:\Program Files\DB Browser for SQLite"? eg:
 * "C:\Program Files\DB Browser for SQLite\DB Browser for SQLite.exe" 
 * "C:\Program Files\DB Browser for SQLite\*.dll"
 * "C:\Program Files\DB Browser for SQLite\uninstall.exe"

Asking because I've just now managed to get the installer doing that properly, instead of using a "bin" subdirectory.

(no progress with the shortcuts yet though)

**Comment by justinclift** [comment]
Note - When implementing this in the Preferences window, it would make sense to have it work well with #659 too.

**Comment by chrisjlocke** [comment]
For Windows, there is no 'benefit' of having a 'bin' directory - its soley a cosmetic thing.  Does the plugins directory sit in the root, or under the 'bin' directory? (I don't have a 'plugins' on my install...)
If in the 'bin' directory, then there is no benefit of a 'bin' directory.

**Comment by justinclift** [comment]
Yeah.  I **suspect** the "bin" directory is just a historical accident. (I didn't write the initial CMake stuff)

With CMake, it's `INSTALL` command has a **required** parameter called `DESTINATION`.  That parameter gives a subdirectory name (under "C:\Program Files\DB Browser for SQLite") to install into.  eg: `bin`, `docs` or whatever (it's free form text)

* Leaving out that parameter doesn't work - CMake errors out
* Giving a blank string (eg "") doesn't work - CMake errors out

* The [docs](https://cmake.org/cmake/help/v3.6/command/install.html) seem to very wrong about some important stuff. 😦   For example, the docs say full paths are used directly (eg "C:\foo") but after experimenting a lot yesterday, that's not the case.

One (probably dodgy) workaround is to use "/" as the destination parameter.  If the docs were correct, it would mean the files were installed in the root directory of the OS.  But the docs aren't correct, so they just get installed into "C:\Program Files\DB Browser for SQLite" instead.  Which is what we want.

Thus the commit yesterday with several changes of "bin" to "/": https://github.com/sqlitebrowser/sqlitebrowser/commit/8a9130883b9e89d57d33b6c3a0ee8ee59ce9957b#diff-af3b638bc2a3e6c650974192a53c7291L337

The plugins directory will be straight under "DB Browser for SQLite" too.  No "bin" needed any more.

The plugins directory is a Qt5 only thing, and will need to have stuff in there giving support for various image file formats. (eg .jpg, etc).  I haven't attacked that particular problem just yet, but will get around to it. :smile:

**Comment by glawrence** [comment]
@justinclift I just realised that @chrisjlocke makes a good point. By default Windows searches for DLLs in the same directory as the .exe so putting *.exe and *.dll in the same directory is a good thing.

**Comment by justinclift** [comment]
Good point, it might work out totally fine.  I just haven't investigated the plugins stuff yet, so am not sure. :smile:

**Comment by MKleusberg** [comment]
Closing this because it's really old and I am pretty sure our installer adds file associations without problems :smile: Please just re-open this issue if I'm wrong :wink:
