### ISSUE TITLE
[Projects] SQBPRO file contents deleted without user approval!

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#2790]
Details for the issue
--------------------

#### What did you do?
Open an existing sqbpro file containing many stored queries.
I only see this occasionally and it may be the project looking for a db to load that no longer exists.
I will confirm with the latest nightly and some trial and error to reproduce.
Opening the ticket before I forget, since the bug always happens when I have no time.

#### What did you expect to see?
The stored queries in the Execute SQL panel.

#### What did you see instead?
Blank Execute SQL contents!

Useful extra information
-------------------------
#### What operating system are you using?

- [x] Windows: ( _version:_10 Pro v20H2___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?
- [ ] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___Nightly v3.12.99-210127

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by sky5walk** [comment]
Ok,
Downloaded latest nightly and did a portable install.
When attempting to open a project file that points to a missing db file, DB4S crashes!

**Comment by sky5walk** [comment]
I think there is some incompatibility between sqbpro  formats.
If I create a project from the latest nightly, it can load without crash.

**Comment by MKleusberg** [comment]
Hmm, so there are several issues here:
1) Sporadically the Execute SQL tabs are not loaded correctly
2) Crash when loading a project file when the database is missing
3) Crash when loading a project file with an older file format
Correct?

As for the third issue, can you try to reproduce the crash using WinDbg as described [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Debugging-a-crash-on-Windows)?

**Comment by sky5walk** [comment]
Yes, I will try this soon.
I would prefer to solve issue #2791 1st. 
Then I could jump to the latest nightly and avoid stale code.
If I cannot export and load DB4S settings, there is something very basic wrong.
Solving that will pave way for project loads.

**Comment by sky5walk** [comment]
Ok,
I stumbled on the trigger for data loss within a sqbpro file.
1. Any standard sqbpro file with at least 1 Execute SQL tab populated.
2. Point to an existing sqlite db file and save the project.
3. Move or rename or delete the sqlite db file referenced in the sqbpro file.
4. Attempt to open the sqbpro file.
5. DB4S fails to find the referenced db and subsequently CLEARS and DELETES all contents of the sqbpro file. OUCH! 
DB4S should instead prompt the user to load another db without altering the sqbpro contents.

**Comment by mgrojo** [comment]
@sky5walk I hope this issue is fixed with fb43e0677a4e39d09b5288a6902b34d8c400f5d9. Could you confirm with the new nightly build?

**Comment by sky5walk** [comment]
Great job mgrojo 💯
