### ISSUE TITLE
Cortex XDR on macOS thinks it is malware

### ISSUE THREAD

**Issue by MayGo** [sqlitebrowser/sqlitebrowser#2794]
Details for the issue
--------------------
Installed DB.Browser.for.SQLite-3.12.2.dmg

Cortex XDR thinks it is malware
<img width="557" alt="Screenshot 2021-08-05 at 09 22 44" src="https://user-images.githubusercontent.com/1929299/128302055-4d8693ae-0f9a-43d3-8ef0-cd07004ffe42.png">

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

**Comment by justinclift** [comment]
Well, whatever Cortex XDR is, it's clearly not all that accurate. :shrug:

**Comment by justinclift** [comment]
Looking at the [Cortex XDR](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-pro-admin/endpoint-security/endpoint-security-profiles/add-malware-security-profile/wildfire-analysis-concepts) docs, they define "Grayware" as:

```
The sample does not pose a direct security threat, but might display otherwise obtrusive behavior.
Grayware typically includes adware, spyware, and Browser Helper Objects (BHOs).
```

No idea why in heck they'd think that.  Really, it's not going to help their reputation. :frowning:

**Comment by MayGo** [comment]
Actually, I think you are right. I heard it blocked 'node' also.
