### ISSUE TITLE
error loading the extension library on windows 10

### ISSUE THREAD

**Issue by vorchunpaul** [sqlitebrowser/sqlitebrowser#2795]
Hi, I ran into a problem loading the extension library. The strangest thing is that in the cli mode, the library loads and even performs its functions, and everything works correctly when compiling and loading the extension in linux.

    $ sqlite3
    SQLite version 3.36.0 2021-06-18 18:36:39
    Enter ".help" for usage hints.
    Connected to a transient in-memory database.
    Use ".open FILENAME" to reopen on a persistent database.
    sqlite> .load util.dll
    sqlite> SELECT bin(5);
    00000101
    sqlite>

I tried to compile both msys2 and MSVC the result is the same

     gcc -g -shared lib.c -o util.dll

![изображение](https://user-images.githubusercontent.com/69152326/128329856-17b2390b-288e-4179-b020-5aa62e49a789.png)

translation: the specified module could not be found

<details>
<summary> library code </summary>

```C
#include "sqlite3ext.h"
SQLITE_EXTENSION_INIT1
#include <assert.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

int bit(int byte, int bit) {
    return (byte >> bit) & 1;
}

void bin(int byte, char* byffer) {
    for (unsigned i = 0, j = 7; i < 8; i++, j--)
    {
        byffer[j] = bit(byte, i) + '0';
    }
}

static void bit_call(
  sqlite3_context *context,
  int argc,
  sqlite3_value **argv
){
    int byte = sqlite3_value_int(argv[0]);
    int bit_val =  sqlite3_value_int(argv[1]);

    int rez = bit(byte, bit_val);
    
    sqlite3_result_int(context, rez);
}

static void bin_call(
  sqlite3_context *context,
  int argc,
  sqlite3_value **argv
){
    int byte = sqlite3_value_int(argv[0]);    
    
    char* byffer = (char*)sqlite3_malloc(8);
    bin(byte, byffer);
    
    sqlite3_result_text(context, byffer, 8, SQLITE_TRANSIENT);
    sqlite3_free(byffer);
}

#ifdef _WIN32
__declspec(dllexport)
#endif
int sqlite3_extension_init(
  sqlite3 *db, 
  char **pzErrMsg, 
  const sqlite3_api_routines *pApi
){
  SQLITE_EXTENSION_INIT2(pApi);
  sqlite3_create_function(db, "bit", 2, SQLITE_DETERMINISTIC, 0, bit_call, 0, 0);
  sqlite3_create_function(db, "bin", 1, SQLITE_DETERMINISTIC, 0, bin_call, 0, 0);
  return SQLITE_OK;
}

#ifdef __cplusplus
}
#endif
```

</details>

Windows version: Windows 10 Pro (20H2, 19042.631)
DB Browser for SQLite:

![изображение](https://user-images.githubusercontent.com/69152326/128328859-fcef339d-3a7e-479a-9510-8e61fc1d20f8.png)

**Comment by chrisjlocke** [comment]
What other .dll or files does the extension need?  It might be missing a related file?

**Comment by vorchunpaul** [comment]
my library is built without external dependencies. and it works fine on linux
![image](https://user-images.githubusercontent.com/69152326/128414185-db407e32-1ffa-4710-9756-8365b6340e6f.png)

**Comment by chrisjlocke** [comment]
If you can email me the util.dll I can use processExplorer to see if its missing a dependency.  Unfortunately, because it works on one OS has no bearing on whether it works on another - it's like saying rocket fuel is great for a Boeing 747 but doesn't do much in my Ford Mondeo 🚗.

**Comment by vorchunpaul** [comment]
Hey, of course I understand that a lot depends on the OS, but util.dll it works on all the systems I tested in the Sqlite CLI ))

**Comment by little-brother** [comment]
Oh, sorry. I downloaded a wrong (32bit) version. Therefore 32bit version raises "Error loading extension"-message with 64bit library.
I think that the author of the issue does the same mistake.

**Comment by vorchunpaul** [comment]
I tried to compile test 64 on a windows 10 computer via Mingw-w64 and got the same error. Can anyone try to do the same?

**Comment by little-brother** [comment]
Try to load your extension in DB4S 32bit. Maybe you have 32bit mingw64.

**Comment by vorchunpaul** [comment]
Sorry, I've been sick with COVID-19 all this time and couldn't answer.

I was able to load my extension after I realized that I was not using the MinGW compiler, but the usual GCC. I use Msys2 and it doesn't use MinGW by default even after installation, so the path to the compiler. Here is my compilation instruction:

```bash
# install mingw64 compiler
pacman -S mingw-w64-x86_64-gcc

# compile shared lib
/mingw64/bin/gcc.exe -g -shared lib.c -o lib.dll
```
