### ISSUE TITLE
PRAGMA integrity_check yields disk I/O error

### ISSUE THREAD

**Issue by mpaolo** [sqlitebrowser/sqlitebrowser#2799]
Details for the issue
--------------------

#### What did you do?
checked a Mozilla bookmarks DB `places.sqlite` which was renamed on restart after crash as `places.sqlite.corrupt` 

#### What did you expect to see?
`ok`
or some actionable infos if any error was found

#### What did you see instead?
```
Result: disk I/O error
At row 1:
PRAGMA integrity_check;
```

Useful extra information
-------------------------
tried also setting to `off` the pragma journal mode.
there are no real disk/hw/fs issues
DB looks fully browseable
the same operation on that DB yields `ok `on a Linux Debian install with:
`SQLite 3.16.2 2017-01-06` 
```
sqlite> .tables
moz_anno_attributes    moz_historyvisits      moz_keywords
moz_annos              moz_hosts              moz_meta
moz_bookmarks          moz_inputhistory       moz_origins
moz_bookmarks_deleted  moz_items_annos        moz_places
sqlite> pragma integrity_check;
ok
```
check yields `ok` also in DB4S on the clean new `places.sqlite` that FFox created

#### What operating system are you using?
- [x] Windows: ( _version:_ 10)

#### What is your DB4S version?
- [x] 3.12.2

#### Did you also
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Is the database on your local disk?  Is it still in c:\program files (or wherever) - try moving the file (or copying) to your desktop.  Windows is fussy as to what can access files in c:\program files, etc.

**Comment by mpaolo** [comment]
yep, file location was a missing info indeed - but nope, all DB checked are in a subdir in `Documents`, BTW note also that the command succeeds on new-from-scratch DB (copied) in same place/dir

**Comment by mpaolo** [comment]
... and of course none was in use by any other process

**Comment by mpaolo** [comment]
grabbed sqlite3 dll+tools `SQLite 3.36.0 2021-06-18` from sqlite.org, in the sqlshell from command prompt I get:
```
sqlite> pragma integrity_check;
Error: disk I/O error
```
then following hunchs from similar bug in sqliteforum, tried:
```
sqlite> vacuum;
sqlite> pragma integrity_check;
*** in database main ***
Page 35: unable to get the page. error code=266
Page 34: unable to get the page. error code=266
Page 1275 is never used
Page 1276 is never used
(many times more) ...
Error: disk I/O error
```
then again
```
sqlite> vacuum;
Error: disk I/O error
```
retrying full check
```
sqlite> pragma integrity_check;
Error: disk I/O error
```
retrying by single table
```
sqlite> .tables
moz_anno_attributes    moz_historyvisits      moz_keywords
moz_annos              moz_hosts              moz_meta
moz_bookmarks          moz_inputhistory       moz_origins
moz_bookmarks_deleted  moz_items_annos        moz_places
sqlite> pragma integrity_check(moz_bookmarks);
ok
sqlite> pragma integrity_check(moz_places);
ok
sqlite> pragma integrity_check(moz_annos);
ok
sqlite> pragma integrity_check(moz_anno_attributes);
ok
sqlite> pragma integrity_check(moz_bookmarks_deleted);
ok
sqlite> pragma integrity_check(moz_historyvisits);
ok
sqlite> pragma integrity_check(moz_hosts);
ok
sqlite> pragma integrity_check(moz_items_annos);
ok
sqlite> pragma integrity_check(moz_origins);
ok
```
but all again fails
```
sqlite> pragma integrity_check;
Error: disk I/O error
```

so it seems the culprit is in the sqlite3 lib on windows, guess we can close the issue for DB4S then.
thx
