### ISSUE TITLE
Set Foreign Key OnDelete SetNull

### ISSUE THREAD

**Issue by AnthonyUccello** [sqlitebrowser/sqlitebrowser#280]
https://www.sqlite.org/foreignkeys.html#fk_actions

It seems you cannot alter columns after they have already been made. Yet I don't see an option to set OnDelete actions for the Foreign Key.

Do you know how I can set this up so if a foreign key is deleted in a parent table then all columns with that key will have those values set to null?

**Comment by MKleusberg** [comment]
I'm not entirely sure if I understand you correctly but you can set a foreign key, including a On Delete action, in the Edit Table dialog like this:
![foreignkey](https://cloud.githubusercontent.com/assets/3153504/8273293/70984122-1867-11e5-93f7-a671dd7eefff.png)

The foreign key column in the dialog is on the very right of the grid view so you probably have to use the scroll bar to see it (I've resized the other columns for the screenshot). Just type in the foreign key as you need it :smiley: Let me know if I misunderstood you or if there are any other issues.

**Comment by VrasidasP** [comment]
I'm trying to use ON DELETE CASCADE but it's not working.
![untitled](https://cloud.githubusercontent.com/assets/6231277/9027507/905a1502-3960-11e5-8531-e283c5dc8021.jpg)

eg. I have an order in Orders with order_id=3 and some rows in relationOrderProduct  with that order_id.
When I delete the order with id 3 in Orders shouldn't it delete the corresponding rows of relationOrderProduct? For some reason it doesn't. 
Have I made a mistake somewhere?
Thanks!

**Comment by MKleusberg** [comment]
Can you give us the layout of the other two tables (Orders and Products)? There doesn't seem to be anything wrong with your foreign keys as far as I can see. I assume your Orders and Products table have a column called order_id or product_id? And you have foreign keys enabled (click the View -> Preferences menu item, then open the Database tab, and check the Foreign Keys checkbox)?

**Comment by VrasidasP** [comment]
Yes, foreign keys are enabled and the layout is as you say.
You can see the whole file here (it's just a demo version for now so it's ok):
https://www.dropbox.com/s/fmmwhz3hqonei3r/thedb.sqlite?dl=0

I'm doing something wrong but I don't know what. :p

**Comment by MKleusberg** [comment]
This is super-weird because on my system it's just working fine :question: 

Can you maybe post all the version numbers shown in the About dialog (menu: Help -> About)? Especially the SQLite version could be interesting.

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
