### ISSUE TITLE
Allow to select tabs versus spaces in Execute SQL Tabs

### ISSUE THREAD

**Issue by stagg54** [sqlitebrowser/sqlitebrowser#2800]
I looked briefly for a similar issue and didn't see one. My work flow is I build queries in the Execute SQL tab and then copy them into my code. They come with all kinds of embedded tabs. However I much prefer spaces. Reformatting a big query is a pain. Not looking to start any kind flame war or debate over tabs versus spaces. It would just be nice to have a little check box in the preferences SQL tab.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
not that I know of. I'm new here. I did a quick search and didn't see anything.

#### Does this feature exist in another product or project? Please provide a link.
I'm sure it does, but I don't have a reference.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![image](https://user-images.githubusercontent.com/20363351/129209243-8d427693-9b67-48f2-9966-7f6c1a8d4659.png)
This is the current preferences screen. I imagine just adding anther drop down like the font drop down or a checkbox at the bottom that says use spaces instead of tabs. Dropdown probably makes more sense, but either one works for me.

**Comment by justinclift** [comment]
Probably doable.  Not sure how much effort it'd take though. :wink:

**Comment by mgrojo** [comment]
Done. It only required allowing the configuration of a property in the editor library (QScintilla). @stagg54, could you give the [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) a try and report any inconsistency?

**Comment by stagg54** [comment]
Works very well. Thank you.

**Comment by mgrojo** [comment]
Thanks for the report.
