### ISSUE TITLE
Huge fonts and widget in current AppImage

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2804]
Details for the issue
--------------------

#### What did you do?
I downloaded the AppImage after 6508974c5424f591f7c752914fdb130444ec05d1 through the Releases page.

#### What did you expect to see?
Normal execution of the program.

#### What did you see instead?
A Main Window with horrible layout, bigger than screen, with extra huge fonts and widgets. General sluggishness of the desktop.
![Bildschirmfoto_2021-08-14_18-37-29](https://user-images.githubusercontent.com/13812910/129453184-cfd5f731-5659-40dd-bb3f-2b7ae1bff022.png)

Useful extra information
-------------------------
- The problem goes away if I set QT_AUTO_SCREEN_SCALE_FACTOR=0.

#### What operating system are you using?

- Linux: ( _distro:_ Ubuntu 20.04 )

#### What is your DB4S version?

- Continuous build since 6508974c5424f591f7c752914fdb130444ec05d1

**Comment by mgrojo** [comment]
As a curious piece of information, I have a screen capture of the full window, but my viewer `eog` refuses to display it. It says it has a size of 16450x16476 pixels.

**Comment by justinclift** [comment]
Out of curiosity, what's the file size of that full screen capture? :smile:

**Comment by mgrojo** [comment]
Oh, it's only 2.7MB. Since it's a GUI image, PNG is compressing it very efficiently, I guess. I was able to display it using Firefox, and it looks nice after all. I mean, the layout is good, despite the disproportionate elements. I attach it here and let's see what happens, it might be scaled-down by GitHub, or it might break something somewhere, who knows :smile:

 ![Bildschirmfoto vom 2021-08-14 18-28-16](https://user-images.githubusercontent.com/13812910/129482442-b277d5ab-2fd3-44e4-8d55-b8e13fb721b7.png)

**Comment by sandman7920** [comment]
On Arch, current AappImage couldn't load OpenSSL and crash when remote DB is selected.

@mgrojo could you test my build [DB_Browser_for_SQLite-master-3634-9ba1a2e-x86_64.AppImage](https://luz-terin.net/db4s/appimage/DB_Browser_for_SQLite-master-3634-9ba1a2e-x86_64.AppImage)

**Comment by mgrojo** [comment]
> On Arch, current AappImage couldn't load OpenSSL and crash when remote DB is selected.
> 
> @mgrojo could you test my build [DB_Browser_for_SQLite-master-3634-9ba1a2e-x86_64.AppImage](https://luz-terin.net/db4s/appimage/DB_Browser_for_SQLite-master-3634-9ba1a2e-x86_64.AppImage)

That one works perfectly. How have you built it?

**Comment by sandman7920** [comment]
>That one works perfectly. How have you built it?

I have made a docker container for this purpose.
There's a developer team thread.
Maybe we should start this container for build test and continuous build.

**Comment by mgrojo** [comment]
Why not use directly GitHub actions? It seems the easiest option.

**Comment by jeanmatthieud** [comment]
Same issue here

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/1443167/59a7e4d5-988e-45c0-86c4-7b5dde0fdec2)

**Comment by justinclift** [comment]
@jeanmatthieud What OS (and version) is that happening on?

Is the problem resolved if you set the environment variable `QT_AUTO_SCREEN_SCALE_FACTOR=0`?

:smile:

**Comment by jeanmatthieud** [comment]
I'm using Windows 11 with two external screens on a laptop, with different resolutions between the laptop screen and the external screens.
The `QT_AUTO_SCREEN_SCALE_FACTOR` env var doesn't seems to have an impact on the issue.

**Comment by justinclift** [comment]
Interesting.  Thanks for the bug report.  I personally have absolutely no idea where to even start with fixing an .AppImage issue when it's running on Windows.

(Heh, "Year of the Linux Desktop" finally! :grin:)

Alternatively, if you install the Windows version of our software... does it have access to your Linux files if you launch it from the Linux command line?  (if that's even possible?)

**Comment by chrisjlocke** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/a3d6d5f1-b7b0-4a0b-8ee5-437d518ad632)

If you click 'Edit' and 'Preferences', what value have you got in the 'font size' box?
If it has a value already, set it to one up or down (so the value changes).  it might be using a default.  A 'sensible' value should be about 10 or 11 .. depending on the actual system font.

**Comment by mgrojo** [comment]
By the way, I cannot reproduce this bug any longer. It could be something we've done in our build process, or that I updated my Ubuntu. `QT_AUTO_SCREEN_SCALE_FACTOR` is not defined.

> DB4S v3.12.99 (Aug  6 2023) [built for x86_64-little_endian-lp64] on Ubuntu 22.04.2 LTS (linux/5.19.0-50-generic) [x86_64]
> using SQLite Version 3.42.0
> and Qt 5.12.8

**Comment by mgrojo** [comment]
Fixed in our latest release.

https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.13.0/DB.Browser.for.SQLite-v3.13.0-x86.64.AppImage
