### ISSUE TITLE
Open Database action doesn't remeber last opened folder

### ISSUE THREAD

**Issue by AlbertIslamov** [sqlitebrowser/sqlitebrowser#281]
Click Open Database, then choose database file. Next click on Open Database - you'll see the User sesttings folder again, not previously selected folder. Actual for version 3.6.0

**Comment by justinclift** [comment]
This sounds like a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/281 to me.

@AlbertIslamov Do they sound the same to you?

**Comment by justinclift** [comment]
@AlbertIslamov Would you be ok to test the latest nightly build (tomorrow)?  We've changed the behaviour a bit for this, so feedback would be useful. :smile:

**Comment by justinclift** [comment]
Going to close this, as we only really need one issue for this to be open (until we figure out a full solution and get it done). :smile:

**Comment by MKleusberg** [comment]
This should be fixed in the 3.7.0 release where we've introduced a new option to the Preferences dialog to change this behaviour. This way everybody should be happy :smiley:
![lastlocation](https://cloud.githubusercontent.com/assets/3153504/8273318/9c697f04-1868-11e5-9791-7dce9ff25cfe.png)
