### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by PxDVAU** [sqlitebrowser/sqlitebrowser#2813]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.5.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by justinclift** [comment]
It's kind of hard to tell what's going wrong without more detail.

Was an error message or similar displayed? :smile:

**Comment by chrisjlocke** [comment]
Closing due to lack of detail.
@PxDVAU - please provide more information and this can be reopened and investigated.
