### ISSUE TITLE
Feature suggestion : Show database as MLD

### ISSUE THREAD

**Issue by SebastienSCochet** [sqlitebrowser/sqlitebrowser#2816]
Describe the new feature
--------------------------
Show database as MLD 

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

**Comment by chrisjlocke** [comment]
MLD?  What is MLD?

**Comment by mgrojo** [comment]
@SebastienSCochet is this the same as #913 and #1260?

**Comment by mgrojo** [comment]
No problem. I'll close this, but you can subscribe to the others, so you can get any update.
