### ISSUE TITLE
SQL Editor area displays non-ascii symbols incorrectly - wtih '?' symbol

### ISSUE THREAD

**Issue by AlbertIslamov** [sqlitebrowser/sqlitebrowser#282]
Copyin text from sql-results with non-ascii (cyrillic symbols) it displays wtih ????

**Comment by justinclift** [comment]
Oh interesting.  That does sound like a bug.

Do you have some example text which we can verify with?

**Comment by schdub** [comment]
Enable UTF-8 in Scintilla Document ctor by default:
libs/qscintilla/src/Document.cpp, line 94
    -       dbcsCodePage = 0;
    +       dbcsCodePage = SC_CP_UTF8;
works for me.

**Comment by justinclift** [comment]
Ahhh, good thinking.  Want to submit a Pull Request with that?  If not, I can do it. :smile:

**Comment by schdub** [comment]
@justinclift, I don't have much experience with Scintilla, so I think is better to wait answer from @MKleusberg or @rp-.

**Comment by justinclift** [comment]
Yeah, good point. :grin:

**Comment by MKleusberg** [comment]
Thanks for reporting this :smile: I've just pushed a fix for this issue, so in the next nightly build your problem should be solved.

**Comment by justinclift** [comment]
@AlbertIslamov Would you have time to try the new nightly build, tomorrow? (if so, download locations are on the front page of our repo)

**Comment by AlbertIslamov** [comment]
The problem resolved. Thanks a lot.


Пятница,  1 мая 2015, 10:49 -07:00 от Justin Clift <notifications@github.com>:
>@AlbertIslamov Would you have time to try the new nightly build, tomorrow? (if so, download locations are on the front page of our repo)
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Альберт Исламов
albertislamov@mail.ru

**Comment by justinclift** [comment]
Excellent.  Thanks for letting us know @AlbertIslamov. :smile:
