### ISSUE TITLE
Space at the end of the table name

### ISSUE THREAD

**Issue by aevseg** [sqlitebrowser/sqlitebrowser#2821]
Details for the issue
--------------------

#### What did you do?
CREATE TABLE "table1 " ("id"	INTEGER);
SELECT * FROM table1;

#### What did you expect to see?
Execution finished without errors
Result: 0

#### What did you see instead?
Execution finished with errors.
Result: no such table: table1

Because there is a space at the end of the table name!
 
Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by mgrojo** [comment]
That's expected, this is how SQL works. The space is part of the name if you include it inside the quotes (which are precisely aimed to include any character in an identifier. Any future reference to this table will have to be quoted too, like this:

```
CREATE TABLE "table1 " ("id" INTEGER);
SELECT * FROM "table1 ";
```

Hope this helps.
