### ISSUE TITLE
Qt_Device

### ISSUE THREAD

**Issue by ahmedyoko** [sqlitebrowser/sqlitebrowser#2822]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I'll close this due to lack of detail.
@ahmedyoko - please provide more information and it can be reopened.
