### ISSUE TITLE
Multiple Window View

### ISSUE THREAD

**Issue by Karl-Franz** [sqlitebrowser/sqlitebrowser#2827]
Describe the new feature
--------------------------
1: Ability to view two tables of the same database at once (top & bottom or side by side view).
2: Ability to view two tables from different databases at once.
3: Ability to Copy/Paste between both table views in items 1 and 2 above.
4: Ability to view the Browse Data and Execute SQL tabs simultaneously so I can see changes to tables dynamically update as commands are executed. This would be a great learning tool.

Thanx for your hard work.

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Don't know

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No

**Comment by chrisjlocke** [comment]
You haven't specified what OS you're using, but the 'multiple windows' is possible using the nightly, in the 'browse data' tab, so you can have multiple tables open.

The nightlies are currently broken, but you can download one from 20 Aug from here:
https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2021-08-20-win32.zip

This allows a wide variety of customisable views - great if you have a large monitor.

![image](https://user-images.githubusercontent.com/7872218/132171594-3171d84b-9267-484e-a8d3-31c99eca7ec0.png)

Note this still only opens tables in the current database.  For your #2, you'd have to attach the other database, or you could open another instance of DB4S and resize the windows.

![image](https://user-images.githubusercontent.com/7872218/132171841-ef185bcc-b105-4920-9f20-572a7a11ed25.png)

Obviously, this solves #3 as data can be copied and pasted via the clipboard.

This doesn't solve #4, but 'sort of' does if you open more than one instance, as shown above.

**Comment by chrisjlocke** [comment]
I'll close this as it's been a month without any interaction.
The multiple windows idea is still in development, so hopefully will mature as time marches forward.
