### ISSUE TITLE
Interface (Database Structure, DB Schema) are wonky with large CREATE TABLE statements

### ISSUE THREAD

**Issue by mgrandi** [sqlitebrowser/sqlitebrowser#283]
```
Version 3.6.0
Qt Version 4.8.6
SQLite Version 3.8.9
Mac OS X 10.10.3
```

With large CREATE TABLE statements, the interface kinda messes up in those two interfaces (Database Structure tab, and the right side window, DB Schema), as it tries to show the full CREATE TABLE statement with all the newlines, tabs and spaces included. These CREATE TABLE statements are created by SQLAlchemy, so thats why they are formatted that way, but it theoretically could happen with manual written statements too if people like them to look pretty in the code.

Easier to show a screenshot: http://i.imgur.com/8bCmexZ.png

I would suggest making it so that the Database Structure tab, all the 'tables' are not so far apart (as it shows the large Create Table statement by default, and maybe have that as a drop down arrow as a child of the table, so it doesn't mess up the formatting/spacing of the table by default? 

And also for the DB Schema side window on the right, i dont think there is a need to show the full CREATE TABLE statement anyway, as you are already parsing out the individual columns anyway and showing the relevant part (per the column) right next to the column anyway. Maybe add entries for Foreign Keys and you won't need the whole CREATE TABLE statement?

**Comment by MKleusberg** [comment]
Fortunately there already is a solution to your problem :smile: You can tick the 'Remove line breaks in schema view' checkbox in the 'Database' tab of the Preferences Dialog. Let us know if this works for you :)

**Comment by schdub** [comment]
@MKleusberg, btw, why this option removes only \n? I think best way to reduce length of Schema column also remove extra spaces and tabs by using QString::simplified()

**Comment by justinclift** [comment]
@schdub From memory, the "\n" thing is because someone asked us to add it.  Your suggestion might be an improvement on top of it too. :smile:

**Comment by mgrandi** [comment]
That option does exist! thanks.

I guess i just don't understand why we even have the 'text' schema there at all, what does 'column_name VARCHAR(200)' tell us that already parsed columns with the name and 'type' information in the respective columns doesn't? I would support just getting rid of the text schema (except for maybe one place), and just have everything be available in the graphical tree view, including foreign keys, NOT NULL constraints, etc

**Comment by mgrandi** [comment]
Another picture, this of MySQLWorkbench, a program that is basically like sqlitebrowser only for mysql, and it sorta has what i'm envisioning for the schema views, where everything is available in a tree like fashion and we don't really need the giant CREATE TABLE string...

http://i.imgur.com/KGfYq4m.png

**Comment by justinclift** [comment]
Hmmmm, that might be a better way of doing things.  Someone would need to code up the new approach, and then we could do some before/after type screenshots and make a decision.

**Comment by MKleusberg** [comment]
I think the main reason why we still have the CREATE TABLE statement in there is that some people use it for copy & paste. I can't find the issue right now but somebody was explicitly asking for that feature... So I think we should leave it in there but this doesn't mean we can't improve the information in the tree structure :smiley: The Schema column is the last one anyways, so it probably isn't too much in anybody's way.

**Comment by justinclift** [comment]
Good point.  If the need for the CREATE TABLE statement is an edge case though, we could probably make it a right click context menu item.  eg. Right click → "Show CREATE TABLE statement", which might free up that widget for being redone... :grinning:

**Comment by mgrojo** [comment]
@mgrandi I hope we have helped you. There is an option (which now it's the default) to turn that multiline display off. We have also removed superfluous whitespace when the create statement is collapsed. We don't plan to make other adjustments unless some comes with a better idea, so I'll close this issue now.
