### ISSUE TITLE
When creating table column, the program does not offer to make it an timestamp.

### ISSUE THREAD

**Issue by AraHaan** [sqlitebrowser/sqlitebrowser#2831]
Details for the issue
--------------------

I could have sworn sqlite3 supported timestamps. What I wanted to do was create a table based on specific types of data.

#### What did you do?
I tried to add an table column that should contain a specific timestamp the user can insert manually.

#### What did you expect to see?
To successfully make the column a timestamp.

#### What did you see instead?
All of the types but ``timestamp``.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ 12 Beta )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other: 3.12.99

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Unfortunately not - just text, integer, real and blobs. There are date/time functions to work with values, but there is no type specifically for dates.

**Comment by chrisjlocke** [comment]
I'll close this as there has been no further response.
