### ISSUE TITLE
appimage 3.12.2 not run on Debian 10.10 x64

### ISSUE THREAD

**Issue by camtofu** [sqlitebrowser/sqlitebrowser#2833]
Details for the issue
--------------------
DB42 3.12.2 appimage build cannot run on Debian 10.10 x64.

#### What did you do?
Download appimage from this repo (2021-09-10).
Add exec permission to appimage file.
Try to run appimage file.

#### What did you see instead?
Fail to start DB4S.

Useful extra information
-------------------------
Try to run in console, find error prompt.

> $ ./DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: wayland-egl, wayland, xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-xcomposite-egl, wayland-xcomposite-glx.
> 
> Aborted

My QT env is 5.11.3, installed from official Debian 10 repo.

> $ qtchooser -l
> 4
> 5
> default
> qt4-x86_64-linux-gnu
> qt4
> qt5-x86_64-linux-gnu
> qt5

"xcb" lib in my file system.

> $ locate libxcb.so
> /usr/lib/x86_64-linux-gnu/libxcb.so
> /usr/lib/x86_64-linux-gnu/libxcb.so.1
> /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0

My OS info

> $ cat /etc/*release
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> 

#### What operating system are you using?
Debian 10.10 x64

#### What is your DB4S version?
DB4S 3.12.2 (2021-09-10 download)

**Comment by camtofu** [comment]
I just tried the latest nighly appimage version (20210912 build).
file name: DB_Browser_for_SQLite-master-62-655a8be-x86_64.AppImage
This time, it worked normally, all testted features work well.
The only question is that, in console, it keeps prompt error message.

> $ ./DB_Browser_for_SQLite-master-62-655a8be-x86_64.AppImage
> qt.svg: link b hasn't been detected!
> qt.svg: link b hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link b hasn't been detected!
> qt.svg: link b hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link d hasn't been detected!
> qt.svg: link b hasn't been detected!
> qt.svg: link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> link d hasn't been detected!
> link d hasn't been detected!
> link b hasn't been detected!
> link b hasn't been detected!
> 

Platform:
Debian 10.10 x64. (same as OP)

**Comment by MKleusberg** [comment]
Awesome! Glad it's working with the newer version.

You can safely ignore that warning. It's produced by Qt's SVG renderer. The worst that could happen is a missing icon. @sandman7920 @mgrojo Any idea which icons might be causing this and if there's anything we can do to silence this warning? I've just noticed that the find_edit.svg icon fails [validation](https://validator.w3.org/).

**Comment by camtofu** [comment]
I just tried latest appimage download.
The error prompt disapper now, "qt.svg: link b hasn't been detected!".
New prompt is,
"(sqlitebrowser:7761): Gtk-WARNING **: 17:02:49.337: Unable to locate theme engine in module_path: "murrine","
This can be solved by:
$ sudo apt install gtk2-engines-murrine
So, for now, no more error message prompt in console.
Though some other issues are still found, but seems not related to do with the appimage build..
So I decide to close this thread. Other issues found will be posted on new threads.
Thanks for @MKleusberg @mgrojo. You are great!

**Comment by chrisjlocke** [comment]
Thanks @camtofu for the detailed investigation - thanks for putting time into this.

**Comment by evbo** [comment]
Thanks for the nightly fix! I would recommend bumping the release version from your Downloads page. I almost gave up entirely since I was in a hurry to run something on Ubuntu. Glad I found this issue though, the latest nightly works great!
