### ISSUE TITLE
Project forgets location of included SQL file

### ISSUE THREAD

**Issue by bernard01** [sqlitebrowser/sqlitebrowser#2834]
Details for the issue
--------------------

#### What did you do?
I created a project because my database has another attached database. This works well, as the project when re-opened remembers the attached database and attaches it.
I also include a SQL file in the project so that it is available when I open the project. Again, this works as expected as the project remembers the SQL file and opens it when I re-open the project. Now I make changes to the SQL file and I want to save the SQL file.

#### What did you expect to see?
I expect that the save button just saves the SQL file.

#### What did you see instead?
I am asked to enter the location of the SQL file, with the file dialog primed with the sqlitebrowser program directory.

Useful extra information
-------------------------
The SQL file is NOT in the same directory as the database, and it is not in the same directory as the project file.
There is a related interesting issue  "Open SQL file default path #1014 "

#### What operating system are you using?

- Windows: 7

#### What is your DB4S version?

- [ ] 3.12.1

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
No.

**Comment by justinclift** [comment]
Interesting.  That really shouldn't happen, but it clearly is.

Hmmm, would you be ok to try out the latest nightly build, and see if it still happens with that?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If it happens with the nightly version too, then we know it's a bug in our current code base that still needs fixing.  And probably won't be tooooooo hard to fix. :smile:

**Comment by bernard01** [comment]
Same behavior in the nightly build. I see what is really happening. For a new project, I opened a SQL file that existed before the project was created. Then I thought I would be editing that file in sqlitebrowser. Instead, the sqlitebrowser copies the content from the file and saves it in its .sqbpro file. That seems to be the way it works. sqlitebrowser does not seem to have that concept of managing external files. It does not remember which SQL file the user loaded the SQL from because the content is now in the project file.  The save button is perhaps an export button or "save as" button. I don't know whether that is a bug or not.

**Comment by justinclift** [comment]
Ahhh, interesting.  Yeah, that approach probably has good and bad aspects to it.

Wonder if we should perhaps allow for external management of the SQL files somehow?  Maybe store a checksum of them in the .sqbpro file, and reload them (or offer to?) if the external file's checksum changes.

**Comment by mgrojo** [comment]
@bernard01: I've changed the behaviour. Now, the original state of each of the SQL "tabs" is restored. If the tab was
opened without a file, the content is saved in the project file itself (this hasn't changed); when the tab was opened from a file, the reference to the file is stored in the project file and the contents are restored from that disk file when loading the project. Could you give it a try using tomorrow's [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) to confirm it's working fine for you?
