### ISSUE TITLE
language

### ISSUE THREAD

**Issue by myzas** [sqlitebrowser/sqlitebrowser#2837]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by justinclift** [comment]
Closing this, as it seems to have been created by mistake.

@myzas If this was actually created on purpose, you're welcome to re-open it... but please provide enough details about the problem so we can investigate.

If you're needing help with SQLite things in general, then the SQLite Forum is probably a better place: :smile:

&nbsp; &nbsp; https://sqlite.org/forum/forum
