### ISSUE TITLE
disk image malformed

### ISSUE THREAD

**Issue by jakeruthven** [sqlitebrowser/sqlitebrowser#2841]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on macOS Mojave (10.14) (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.15.1

**Comment by justinclift** [comment]
Hi @jakeruthven.  Warnings about `disk image malformed` (and similar) generally mean the SQLite database file itself is damaged or incomplete.

The most common reason for that (so far) seems to be people copying their SQLite database from an Android device, as there's something a big dodgy about how `adb` does stuff when transferring files. :frowning:

Don't suppose that's the situation you're in?  You've transferred a database from an Android device and things aren't going well?

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@jakeruthven - comment back when convenient and we can look into this for you.
