### ISSUE TITLE
Bulk import

### ISSUE THREAD

**Issue by fishberries** [sqlitebrowser/sqlitebrowser#2842]
Details for the issue
--------------------

#### What did you do?
Tried importing a large file using a pipe delimiter (82,000 rows)

#### What did you expect to see?
The file properly parsed based on the delimiter and the data stored in the appropriate columns

#### What did you see instead?
Some records worked (roughly half) while others were skipped in the parsing and wound up in a single cell with the delimiters in tact.  I don't know what caused it but it is replicable.  It looked like it happened about half a dozen times.  Some of the skipped records contained only a few hundred or a few thousand records while other rows contained tens of thousands (>30k) - those records all appeared in a single cell because they were not parsed correctly.  I know it is a bug because I wrote some code to import the file directly into SQLite using the same delimiter "|" and it worked.  Additionally, I tried it with multiple different delimiters using the built in import tool and it had similar issues parsing the file.  Finally, if it is helpful, the data was words, definitions, and numbers using the open source Wordnet data as a starting point - but I cleaned it up pre-import and added the delimiters.  Again, worked fine when I bypassed this tool's import feature and used my own code with the same delimiter calling the .import function of SQLite.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by fishberries** [comment]
[words_defs_sigs.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/7190106/words_defs_sigs.csv)

file used that create above issue attached

**Comment by chrisjlocke** [comment]
What delimiter did you use?
Some lines have quotation marks in them.
```
attribution|assigning some quality or character to a person or thing; "the attribution of language to birds"; "the ascription to me of honors I had not earned"  |11000000200001100103100000
```
The default (on Windows, anyway) is for quotation marks.  This would upset the import.

It would be handy if you could indicate what settings you used, and at what point things go out of sync.  I looked to about 10,000 records and it was in sync, but it only imported 38.4k records, and not 82.1k.

**Comment by chrisjlocke** [comment]
I just imported using the pound character (£, not #) and that imported fine.

![image](https://user-images.githubusercontent.com/7872218/133894820-66061d75-59e2-4392-a09a-3518309f200f.png)

All 82.1k rows.

**Comment by mgrojo** [comment]
You can leave the "Quote character" empty if the file does not use any. It's the third value in the combo-box.

![image](https://user-images.githubusercontent.com/13812910/133895216-09b949f2-dec6-4265-b0cd-86031e206fe5.png)

I got 82115 entries with those settings.

**Comment by fishberries** [comment]
Ah, okay that is helpful.  So if the file contains quotes, sub with a quote character, else leave it blank, correct?

**Comment by mgrojo** [comment]
> Ah, okay that is helpful. So if the file contains quotes, sub with a quote character, else leave it blank, correct?

Yes, the quotes in CSV are for delimiting multiline strings and escaping texts containing the field separator. In your case, the quotes are part of the second field.

**Comment by fishberries** [comment]
Thanks

**Comment by chrisjlocke** [comment]
> You can leave the "Quote character" empty

Aah, I thought that was a space .... 😂😂

**Comment by mgrojo** [comment]
> > You can leave the "Quote character" empty
> 
> Aah, I thought that was a space .... joyjoy

:smile: I had doubts, I had to look at the code to be sure, and it's an empty string.
