### ISSUE TITLE
Hidden columns reappear on sort.

### ISSUE THREAD

**Issue by ricturley** [sqlitebrowser/sqlitebrowser#2843]
Details for the issue
--------------------

#### What did you do?
While browsing a table, I hid a number of columns by right-clicking the column header and choosing "Hide Column(s)" on each. I then clicked on a column header to sort the table by that column.

#### What did you expect to see?
The unhidden columns resorted.

#### What did you see instead?
Resorted with all columns showing again.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.5.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

I found another bug report for this issue on Windows, I'm running MacOS Big Sur 1.4.

**Comment by chrisjlocke** [comment]
Interesting - it doesn't do this on Windows - at least, not in the nightly.
I'm not a Mac user, but can you confirm if this issue is in the .dmg in the nightly build - is that possible?
https://nightlies.sqlitebrowser.org/latest/

**Comment by ricturley** [comment]
I found the problem in release version 3.12.2. It does NOT happen with the nightly build 3.12.99.

Thanks for fixing it!

Ric Turley

**Comment by mgrojo** [comment]
Thanks for reporting back.
