### ISSUE TITLE
Integer Division by Zero

### ISSUE THREAD

**Issue by mqudsi** [sqlitebrowser/sqlitebrowser#2866]
Details for the issue
--------------------

#### What did you do?

Upgrade to 3.12.2 and run

#### What did you expect to see?

A new session

#### What did you see instead?

Nothing; the application crashes before it initializes any windows or dialogs.

Running it in a debugger reveals an integer division by zero exception during startup:

> Unhandled exception at 0x00007FF7EDB43583 (DB Browser for SQLite.exe) in DB Browser for SQLite.exe.82400.dmp: 0xC0000094: Integer division by zero.
```
>	DB Browser for SQLite.exe!00007ff7edb43583()	Unknown
 	DB Browser for SQLite.exe!00007ff7edb431dc()	Unknown
 	DB Browser for SQLite.exe!00007ff7ed9fbcdb()	Unknown
 	DB Browser for SQLite.exe!00007ff7eda405c7()	Unknown
 	DB Browser for SQLite.exe!00007ff7edacde6d()	Unknown
 	DB Browser for SQLite.exe!00007ff7edacb855()	Unknown
 	DB Browser for SQLite.exe!00007ff7edc2b85c()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

Do you save the symbols (.pdb files, in the case of Windows builds) for released versions? Can I get them somewhere? Otherwise I'm going to have to build from scratch to get the symbols and I don't like building Qt applications on Windows.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: ( _version: Windows 10 18363 (1909)_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds (no Windows builds available)
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mqudsi** [comment]
I'll check what you suggested but note that the Windows nightly builds are not working (they're empty zip files). You might want to check your CI.

**Comment by mqudsi** [comment]
Thanks for all the help, guys. While neither the registry changes nor the newer build helped, I felt something was just _off_ about my Windows session - lo and behold, a reboot did the trick.

Maybe there was some Win32 resource that the framework was trying to obtain during startup without validating that it was acquired successfully or perhaps it was using the result of a Win32 call in a division operation and that result was coming back as an error or an invalid value. :shrug:

I appreciate the help and sorry for wasting your time!

**Comment by chrisjlocke** [comment]
> and sorry for wasting your time

No time was wasted at all - glad you got it fixed.  👍
If anything, it'll help someone else who encounters this issue.
