### ISSUE TITLE
Why does this query takes so long and freeze the app?

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#2883]
I don't think this is a DB Browser bug because it happens to crash my server as well. Seems like SQLite engine issue?

What is your question
-----------------------

[Related StackOverflow question](https://stackoverflow.com/questions/69763542/why-is-this-query-too-slow-getting-list-of-a-with-one-associated-foreign-keyed)

When I run the query in DB Browser, it froze the app for a few seconds, showed up this UI and then froze for a longer while before finally showing up the result:

![image](https://user-images.githubusercontent.com/6388546/139394589-c0ec74e5-a741-40da-85ab-0c9c80809efc.png)

The schema is quite simple: I have `Website(Id)` table, each record may have multiple `CheckLog(FK WebsiteId)` entries associated. `CheckLog` also has a compound index of `[WebsiteId, CreatedTime]`. `Website` has only around 20 records but overtime `CheckLog` would grow, 3 millions entries at the time I have this problem. (See schema using EF Core at the end of the question).

```
    public class Website
    {

        public int Id { get; set; }

        // Other properties

        public ICollection<CheckLog> CheckLogs { get; set; }

    }

    [Index(nameof(CreatedTime))]
    [Index(nameof(WebsiteId), nameof(CreatedTime))]
    public class CheckLog
    {
        public int Id { get; set; }
        public DateTime CreatedTime { get; set; }

        public int WebsiteId { get; set; }
        public Website Website { get; set; }

        // Other properties

    }
```

A frequent query I have is to query the list of all `Website`s, along with **zero/one** latest `CheckLog` record:

```
      SELECT "w"."Id", "t0"."Id", "t0"."CreatedTime", "t0"."WebsiteId"
      FROM "Websites" AS "w"
      LEFT JOIN (
          SELECT "t"."Id", "t"."CreatedTime", "t"."WebsiteId"
          FROM (
              SELECT "c"."Id", "c"."CreatedTime", "c"."WebsiteId", ROW_NUMBER() OVER(PARTITION BY "c"."WebsiteId" ORDER BY "c"."CreatedTime" DESC) AS "row"
              FROM "CheckLogs" AS "c"
          ) AS "t"
          WHERE "t"."row" <= 1
      ) AS "t0" ON "w"."Id" = "t0"."WebsiteId"
```

The above query is simplified from this code:

```
return await this.ctx.Websites.AsNoTracking()
    .Select(q => new  WebsiteListItem()
    {
        Website = q,
        LatestCheckLog = q.CheckLogs
            .OrderByDescending(q => q.CreatedTime)
            .FirstOrDefault(),
    })
    .ToListAsync();
```

~To be honest I am a bit desperate now and posting here, beside asking for why the problem is happening to DB Browser, I also want to ask how to optimize that query so it runs faster.~ I found the solution, this query runs much better and faster:

```
SELECT L.*
FROM CheckLogs L
INNER JOIN
(SELECT WebsiteId, Max(CreatedTime) AS CreatedTime
FROM CheckLogs
GROUP BY WebsiteId) L2
ON L.WebsiteId = L2.WebsiteId AND L.CreatedTime = L2.CreatedTime
```

**Comment by chrisjlocke** [comment]
> I found the solution

I'll close this issue then.
