### ISSUE TITLE
Difference between .zip (no-installer) and portable

### ISSUE THREAD

**Issue by gaiking-uk** [sqlitebrowser/sqlitebrowser#2884]
Which one should I use?
---------------------------

I use several portable apps which are synced across multiple machines and part of a roaming profile (i.e. are available on a fresh install with the intent that they can be run directly without any setup actions)...

- Previously, I copied the contents of the [Win x64 "no installer" (.zip)](https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.12.2-win64.zip)
- However, browsing the site today, I noticed the [Portable App (.exe)](https://download.sqlitebrowser.org/SQLiteDatabaseBrowserPortable_3.12.2_English.paf.exe) and wondered if I should be using this instead?

Please could you confirm...

1. Which is the best package to use for a portable scenario (in the situation(s) I described above)
2. The difference between the recommended option (i.e. the answer to [1]) and the other file -- i.e. if I should use the .zip file, what this gives (or doesn't give) me vs. the portable.exe

Thanks in advance!

**Comment by chrisjlocke** [comment]
Both packages are the same, but DB4S does write configuration/preferences to the registry, so it's not truly 'portable'.  It's portable in that it doesn't need installing and be run 'as is'.

The official portable app version includes an extra program that stores the registry settings in an .INI file, and writes this file back out to the registry again, so any changes are 'permanent', eg, if you run this from a USB stick in multiple machines.

When you say 'synced' and 'roaming profile', are you in a Windows domain?  If you're running DB4S in this location and the .INI file also gets synced, then the official Portable Apps version is the one you want.  However, the nightly does have more up-to-date code (eg, multiple 'browse data' tabs) and bug fixes from the latest release, so you might want to merge the contents of the nightly into the portable apps directory to get best of both worlds.

**Comment by gaiking-uk** [comment]
Hi Chris, thank for getting back to me so quickly! (and for clarifying the difference)

I'm not using a true domain roaming profile, however I have tried to essentially replicate this as I sync the majority of my files through OneDrive, including:
- `OneDrive > RoamingApps` -- Where I unzipped the DB4S files to previously)
- `OneDrive > RoamingAppData` -- I've redirected `%AppData%` `[C:\users\<username>\AppData\Roaming]` to point here instead (technically is more selective than this, but for simplicity let's just treat it like the whole folder)

My idea is whenever I re-build my machine or use a secondary device, I can run sync my OneDrive down and am ready to go (i.e. and run programs direct from the `OneDrive > RoamingApps` folder - so in that sense, your recommendation to use the Portable App version (that writes `INI` <--> `REG`) makes sense, thanks for that! (Will also look at integrating the night build).

Thanks again for your help and time, appreciate you clarifying this! 👍🏼

***

✅ Answered

**Comment by gaiking-uk** [comment]
Hi Chris, thank for getting back to me so quickly! (and for clarifying the difference)

I'm not using a true domain roaming profile, however I have tried to essentially replicate this as I sync the majority of my files through OneDrive, including:
- `OneDrive > RoamingApps` -- Where I unzipped the DB4S files to previously)
- `OneDrive > RoamingAppData` -- I've redirected `%AppData%` `[C:\users\<username>\AppData\Roaming]` to point here instead (technically is more selective than this, but for simplicity let's just treat it like the whole folder)

My idea is whenever I re-build my machine or use a secondary device, I can run sync my OneDrive down and am ready to go (i.e. and run programs direct from the `OneDrive > RoamingApps` folder - so in that sense, your recommendation to use the Portable App version (that writes `INI` <--> `REG`) makes sense, thanks for that! (Will also look at integrating the night build).

Thanks again for your help and time, appreciate you clarifying this! 👍🏼

***

✅ Answered

**Comment by chrisjlocke** [comment]
No problem.  DB4S stores very little information in preferences - mainly font choice and sizes, so once that's set, you're good to go.  Depends on how many different machines you use! ;)
For database related settings, DB4S uses project files, which are user stored files - these are stored with the database, for example, or your normal 'documents' folder.
