### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by eloranta** [sqlitebrowser/sqlitebrowser#2888]
In DB Browser for SQLite I have to press Refresh button in order to refresh Browse Data view.
Is there any means of periodical auto refresh?

**Comment by chrisjlocke** [comment]
Not currently.  There is already a request for this, eg https://github.com/sqlitebrowser/sqlitebrowser/issues/2508
Depending on your requirements, it's easy to knock up a third-party program to view data every x seconds.  If you can give more information on what you need, maybe something can be created.

I'll close this as it's a duplicate, so please subscribe to the other issue if you want to be notified of any updates.
