### ISSUE TITLE
Text on Browse data Tab is very strangely formatted. 

### ISSUE THREAD

**Issue by AlexanderProd** [sqlitebrowser/sqlitebrowser#2890]
I want to browse the data of my slqlite db but its very hard to read and strangely formatted, I'm using an M1 Pro MacBook and the latest version of MacOS as well as the latest version of DB Browser, translated with Rosetta 2. 

Here is a screenshot of how it looks. 

<img width="1401" alt="Bildschirmfoto 2021-11-05 um 19 49 22" src="https://user-images.githubusercontent.com/3080903/140563416-cf302b80-d404-48fe-8b1b-204945d52a39.png">

Details for the issue
--------------------

#### What did you do?
Browse data

#### What did you expect to see?
Browse my data and be able to read the content.

#### What did you see instead?
Very strange formatted text which is extremely hard to read 

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] macOS: ( _version:12.0.1 ) on M1 
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I would suspect this is a font issue.
If you click 'Edit' and 'Preferences', you'll see a series of tabs.
If you click on 'Data Browser', what font is in the 'Font' box?

![image](https://user-images.githubusercontent.com/7872218/140567947-93cfce27-1ad8-45d2-8b4b-8cb87cd12ba6.png)

If you change this to another font, does it improve things?
I don't use macOS so can't suggest a font to use, but on Windows, there are mono spaced and proportional spaced fonts.  'Normally' a mono spaced font is used, but try others.
I'd be interested to know what the default font is, and what alternative you used instead - it could help someone else.

**Comment by AlexanderProd** [comment]
> I'd be interested to know what the default font is, and what alternative you used instead - it could help someone else.

Oh wow there was no font selected just an empty field and font size 10. 

Selecting a font did fix it. Thanks!

**Comment by chrisjlocke** [comment]
That's weird.  Guess it picked a random font, which was just not a good one.
Glad you got it sorted.  Thanks for reporting back.
