### ISSUE TITLE
db sqlite browser import table from csv file

### ISSUE THREAD

**Issue by AliElkomy** [sqlitebrowser/sqlitebrowser#2891]
db sqlite browser import table from csv file

Describe the new feature
--------------------------
db sqlite browser import table from csv file

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
Unsure what this issue is for - are you having problems, or requesting a feature?  Or was it opened by accident?
If you can provide more details, we'd be more than happy to help.

**Comment by chrisjlocke** [comment]
I'll close this as it doesn't contain any information.
@AliElkomy - please provide more details and we can reopen this to look into it further.
