### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by imacodes** [sqlitebrowser/sqlitebrowser#2895]
Details for the issue
--------------------

#### What did you do?
The font size was too little so I increased it on preferences to 40 and it became too big, now I cannot reduce it back

#### What did you expect to see?
I expected the sql queries to increase in font size which did not

#### What did you see instead?
I have uninstalled and re installed back but it is still showing the font size of 40

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19041) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Even at size 40, the dialog is visible.

![image](https://user-images.githubusercontent.com/7872218/140700629-afbe691e-cd46-4b31-a6e4-181068d3d748.png)

Change this value to something smaller (eg, 16) and press [Enter].  The font size should immediately change.

Does this occur for you?

**Comment by imacodes** [comment]
I uninstall and installed the sqlite browser app instead.

Sent from Yahoo Mail on Android 
 
  On Mon, 8 Nov 2021 at 7:28 am, Chris ***@***.***> wrote:   


Even at size 40, the dialog is visible.



Change this value to something smaller (eg, 16) and press [Enter]. The font size should immediately change.

Does this occur for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisjlocke** [comment]
> I expected the sql queries to increase in font size which did not

This is set in the 'sql' tab of the preferences

![image](https://user-images.githubusercontent.com/7872218/140741541-25ff33a4-056b-4df4-b9d8-a25f8ebea5c9.png)

There are two font values.  The value for the SQL window, and the value for the results.

**Comment by chrisjlocke** [comment]
@imacodes - Are we all OK now, or are you still seeing large text?

**Comment by imacodes** [comment]
Hi,
I'm okay now.Ima

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Nov 2021 at 7:23 am, Chris ***@***.***> wrote:   


@imacodes - Are we all OK now, or are you still seeing large text?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisjlocke** [comment]
Excellent.  Thanks for reporting back, and glad all is good.
