### ISSUE TITLE
make install does nothing

### ISSUE THREAD

**Issue by Jonrysh** [sqlitebrowser/sqlitebrowser#29]
make install (invoked in the top level directory, containing BUILDING, ...) doesn't seem to do anything except produce output; no files are installed anywhere.  The program has already been build using make, and seems to work fine.

**Comment by justinclift** [comment]
Closing this now, as "make install" is generally known to work ok.

If for some reason it doesn't, please feel welcome to re-open this issue or create a new one (either is good). :smile:
