### ISSUE TITLE
colored column when is a key (Tab data or tab query )

### ISSUE THREAD

**Issue by llist** [sqlitebrowser/sqlitebrowser#2902]
Describe the new feature
--------------------------

Colored title column when it is a key 

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

It's an improvment 

#### Does this feature exist in another product or project? Please provide a link.

I think no.

#### Do you have a screenshot? Please add screenshots to help explain your idea
![keycolumncolored](https://user-images.githubusercontent.com/19572548/141839190-030cd31d-7ccf-4b5e-9b7f-eba492036cc2.png)
.

**Comment by sky5walk** [comment]
Great suggestion!

**Comment by mgrojo** [comment]
What about including the key icon? I think it would be more recognizable.

**Comment by mgrojo** [comment]
I've implemented it with the icon. Please, comment after trying the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds).

**Comment by sky5walk** [comment]
Was gonna try it but only MAC nightlies available.
Is Windows compilation usually delayed?

**Comment by chrisjlocke** [comment]
Nah, probably Justin has unplugged the build server to plug in his Christmas lights.... ;)
Poking @justinclift to have a gander ..... or two goose and a duck.

**Comment by justinclift** [comment]
Looking at the current schedule for the builds... the Win64 is scheduled for 10am.  So, it'd normally start in about 1hr 45mins from now.

I've just kicked it off now though, so should be available in about 1/2 an hour. :smile:

**Comment by justinclift** [comment]
Just checked, and the Win64 nightly builds were built fine and are online as expected. :smile:

**Comment by sky5walk** [comment]
Ok, Win64 came in after my sleep too!
Just tried DB Browser for SQLite Version 3.12.99 (Jan  2 2022) and the icon appears beside PK columns but no color.
I always use Dark Mode, but the same with Light and Follow Desktop Modes.

**Comment by mgrojo** [comment]
> Ok, Win64 came in after my sleep too! Just tried DB Browser for SQLite Version 3.12.99 (Jan 2 2022) and the icon appears beside PK columns but no color. I always use Dark Mode, but the same with Light and Follow Desktop Modes.

Indeed, I did not implement a color modification. Is that expectation based on other products? Colors are more difficult to combine well with different application styles and less intuitive than the icon.

**Comment by sky5walk** [comment]
Ah, I see that now. Colors are preferred since no increase in column width due to icon spacing.

**Comment by llist** [comment]
Hello

 I am the requester and I am very happy that the subject interests many people.
I checked the solution with the icon ..good job ..and thank for this approach.
However I confirm that the color is the original request. More visual. 
Probably little bit complex to program 
especially if you add a dedicate menu to choose different colors. 
Before to do this can you just add a pastel green color for example it would be great.
And we will see the users feedback.

Thant for your involvement
BR,
Patrice

**Comment by mgrojo** [comment]
I don't like the idea of using the background colour because it would interfere with the theme colours. I'll try using a font style, like underlined or cursive (bold is already used for the current column).

**Comment by mgrojo** [comment]
Done.
- Primary keys are underlined
- Foreign keys are italic

Please, give it a try using the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds).

**Comment by sky5walk** [comment]
[DB.Browser.for.SQLite-win64.zip](https://nightlies.sqlitebrowser.org/latest/) is empty?

**Comment by mgrojo** [comment]
It seems we have a problem with the win64 build (the github action is building right for Linux). @justinclift, is there a log we can review?

**Comment by chrisjlocke** [comment]
This seems like its OK now.

![image](https://user-images.githubusercontent.com/7872218/155274904-daa965cf-08b5-452a-9ac2-b69370744c00.png)

**Comment by mgrojo** [comment]
Ok, I can reproduce it when using the Dark Style. I'll get some time to test with the latest [QDarkStyleSheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet) version, and will report it if it still has that issue.

**Comment by mgrojo** [comment]
Issue reported to QDarkStyleSheet: https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/315
