### ISSUE TITLE
Error when adding datas on columns with foreign keys

### ISSUE THREAD

**Issue by MrRaggamuffin** [sqlitebrowser/sqlitebrowser#2904]
#### What did you do?
I cannot add datas via the "Browse Data" tab on DB Browser on both columns affected by a foreign key.
I tried again with a new blank database, only creating 2 tables (A & B) with 2 columns (A1, A2, B1, B2).
A1 & B1 are primary keys and autoincremented. B2 is configurated with the foreign key "A"("A2").

#### What did you expect to see?
I was expecting to fill the A2 column then the B2 according to A2.

#### What did you see instead?
When I try to add data on A2 I get this error :
"Error changing data:
foreign key mismatch "B" referencing "A""

When I try to add data on B2 I get this one :
"Error adding record. Message from database engine:
foreign key mismatch "B" referencing "A"(INSERT INTO "main"."B"("B2")
VALUES (5);)"   # I tried to add a 5.

I also tried on the nightly build and the portable versions, with the same result.
This is driving me crazy so thanks a lot in advance to anyone willing to help.

Useful extra information
-------------------------
- Windows 10 Familly 21H1
- DB4S version 3.12.2

**Comment by chrisjlocke** [comment]
Sorry to hear you're having issues.

This should work in both the 3.12.2 release and nightlies.  I don't use foreign keys much, but have used it to test other support issues.

So I've just created two tables.  Both just have one field, and one has a primary key.

![image](https://user-images.githubusercontent.com/7872218/142720742-e753e874-14fb-4ebb-be88-5989b61a1452.png)

In tableB, I can set that field to point to tableA

![image](https://user-images.githubusercontent.com/7872218/142720766-6cabb742-5305-438d-a127-7383e78c53b5.png)

This generates the following table schema.
```
CREATE TABLE "tableB" (
	"Field1"	INTEGER,
	FOREIGN KEY("Field1") REFERENCES "tableA"("Field1")
);
```

So when I add records into tableA, these are auto populated

![image](https://user-images.githubusercontent.com/7872218/142720845-bbe4b52a-1fbf-4603-8e33-5fe134b34db2.png)

For tableB, when I add a record, it's initially null

![image](https://user-images.githubusercontent.com/7872218/142720860-f31be64e-217f-445c-9f61-aebf736f0739.png)

But DB4S shows a dropdown that only allows me to select the numbers from tableA

![image](https://user-images.githubusercontent.com/7872218/142720874-c6185895-275c-40b7-b4d6-31c742fdfc60.png)

So so far, this is all working as it should.  Using your DB4S, do you want to try this example and ensure we get to this point?
Can you copy and paste your 'create table' statements into here so I can have an exact copy of your test database that isn't working?  I can only assume the foreign key statements aren't quite right between the tables.  Or it might be related to multiple columns - in my example, I'm just using one column to ensure we at least get stage 1 working...

**Comment by MrRaggamuffin** [comment]
Your example is working on my side.

Here is the code I have an issue with :
CREATE TABLE "A" (
	"A1"	INTEGER,
	"A2"	TEXT,
	PRIMARY KEY("A1" AUTOINCREMENT)
);
CREATE TABLE "B" (
	"B1"	INTEGER,
	"B2"	TEXT,
	PRIMARY KEY("B1" AUTOINCREMENT),
	FOREIGN KEY("B2") REFERENCES "A"("A2")
);


I just tried to change the foreign key's reference to A(A1) and it is working fine.
It's also working with "A1" changed to TEXT.
So that would mean the foreign key must refer to a primary key ?

**Comment by chrisjlocke** [comment]
Yes, a foreign key points to a primary key in another table.
A table can only have one primary key, but more than one foreign key.

"A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. ... It refers to the field in a table which is the primary key of another table."

**Comment by MrRaggamuffin** [comment]
Ok, that make sense, thanks a lot.
But then is there a trick to achieve what I want to do ? To constrain B2 to be filled only with A2 datas ? Without having A2 and B2 as primary keys.

**Comment by chrisjlocke** [comment]
Creating another table of valid inputs and using this as a primary key is the only recommended way.
You can also do check constraints or even triggers.

https://stackoverflow.com/questions/6367063/how-to-restrict-a-column-value-in-sqlite-mysql

**Comment by MrRaggamuffin** [comment]
Ok I will check that. Thanks a lot captain Locke ! 😃

**Comment by chrisjlocke** [comment]
I'll be interested to know how you get on.
In my development, I tend to use DB4S to build databases, but use vb.net as the development environment for my application, so all the logic and validation occurs at the application level.  This is fundamentally flawed (each application built on the database has to follow the same rules) but an equal argument is that each application uses a framework to talk to that database, so that's OK.  The flaw in THAT argument is that frameworks can get out of date ... I develop an application based on a framework and it might not be the right one, or it gets superceded by another version, etc.  For every argument there is a counter argument.
In my world, fighting with DB4S this way is quite lengthy, and doing it in VB which can have proper input screens, etc, is a bit more 'productive'.  But then I'm odd.  ;)

**Comment by MrRaggamuffin** [comment]
Finally I just changed the foreign key to an Id column with a primary key.
I'm working with python on Pycharm here and I'm quite a beginner, trying to do quite a complex project as a first shot.
And I want my database to be well-made before playing with it. That included some foreign keys.

**Comment by chrisjlocke** [comment]
> And I want my database to be well-made before playing with it

That's to be commended.  Well done.  Nothing worse than trying to refactor an application after the event to make it better - always better to get the foundation right.
Conversely, don't get every detail right, as the database schema can change.  If you spend ages getting the foreign keys, etc, right, but then find it's better to go a different route, you don't want to have wasted days of development...
A difficult balancing act.  This is why most software applications are shit.  ;)
