### ISSUE TITLE
i need to create a er diagram

### ISSUE THREAD

**Issue by saravanan-sathiyamoorthi** [sqlitebrowser/sqlitebrowser#2907]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
I'll close this as there are several other open issues requesting this feature.
Unfortunately, while a stab was made to develop this in DB4S, it hasn't progressed much, and is in mid development.

Hopefully this will get implemented at some point, but obviously there is no timescale on this.  :(
