### ISSUE TITLE
Won't run on Windows XP

### ISSUE THREAD

**Issue by Nisto** [sqlitebrowser/sqlitebrowser#291]
Just installed for the first time. When attempting to run it, I get "sqlitebrowser.exe is not a valid Win32 application". No warnings about DLLs or other dependencies missing. I downloaded the correct binary for my CPU/OS architecture (both 32-bit) and I have MSVC redistributable 2013 installed. Is Windows XP not supported anymore?

**Comment by glawrence** [comment]
Well, as I am sure you know, Microsoft don't support Windows XP any more. I don't believe there was a conscious decision to drop it though. Can you confirm you have SP2 applied? Oh and could you try the nightly download for Windows from the repository home page?

**Comment by justinclift** [comment]
@Nisto This may be a side effect of our new build process.  Does v3.5.1 work?

We can probably still create a WinXP compatible build using the old cross-compiler process if that's the case. :smile:

**Comment by Nisto** [comment]
Even though I am on XP I stay as I up to date as I can on things, so I have the latest service pack and all other updates available of course. I will try the nightly build and report back.

**Comment by justinclift** [comment]
Good idea.  That's probably using the old build process... I didn't think of that... but yeah, give that a shot. :smile:

**Comment by garfield69** [comment]
I also run XP SP3 with VC++2013.
just wanted to confirm that the nightly build 3.6.99 works fine, but sqlitebrowser-3.6.0v2-win32.exe fails with same error that Nisto previously reported.
Will there be a nightly build of 3.7.7 for us to try?

**Comment by justinclift** [comment]
Well, the "nightly builds" at the moment are using the very latest source code... so it's already "what will become version 3.7.0".  It sounds like we should create a 3.6.0 release for WinXP using the old process (to keep people on XP happy), and also look into updating our nightly builds to generate things with the new build process as well.  I have no idea when any of that will happen though.

Are you both ok to just use that nightly build for the moment?

**Comment by garfield69** [comment]
Yes indeed, am perfectly happy to keep using the nightly version for now, thank you.

**Comment by rp-** [comment]
VS2013 has as default the toolset > winxp set and I didn't check that or even think about it.
I may rebuilt the whole thing with the winxp toolset, or have it at least changed for the next release.

**Comment by justinclift** [comment]
@rp- Cool.  Btw, from email with John Haller (Portable Apps), we can probably bundle the MS dependency legally-ok, then have NSIS check if it's needed and auto-install it.  We'll need to look over the license text for the dependency first, just in case though.

**Comment by justinclift** [comment]
Initial response from @richardfontana indicates bundling doesn't seem to be allowed by the MSVC2014 runtime license text.  Going to dig a bit deeper though, to see what can be done. :smile:

**Comment by justinclift** [comment]
@nickdesaulniers has helpfully pointed this out:

&nbsp; &nbsp; https://msdn.microsoft.com/en-us/library/ms235299.aspx

I'm too sleepy atm to grok it, but I'm betting the info is there for us to find. :smile:

**Comment by rp-** [comment]
I uploaded new builds (v3) which should work on win xp again

**Comment by garfield69** [comment]
I can confirm that sqlitebrowser-3.6.0v3-win32.exe works on my win XP sp3. Thanks :+1:

**Comment by LeonTheOriginal** [comment]
Testing a bit around with the portable version, I just noticed, that version 3.9.0 (or to be precise the prtable launcher) on Windows XP shows an error message, that it requires at least Vista.
Is this a bug or has support of Win XP officially been dropped? I couldn't find an info about that in the release notes.

**Comment by chrisjlocke** [comment]
Have you tried the nightlies?  These use a slightly different build process, and searching through this group, appears to be more XP friendly....

http://nightlies.sqlitebrowser.org/win32/

**Comment by justinclift** [comment]
Ahhh yeah.  We dropped support for Windows XP with our version 3.9.0 release.

Version 3.8.0 will still work though. :smile:
