### ISSUE TITLE
Column sort in data browser is actually reversed

### ISSUE THREAD

**Issue by mqudsi** [sqlitebrowser/sqlitebrowser#2912]
Details for the issue
--------------------

The sort order for a column in the data browser is actually the inverse of what the UI says it should be. The UI convention is that a filled or empty equilateral triangle (or similar) shape with a narrow base and a wide crown or the opposite indicates the sort order. The top of the shape represents the top of the view and the bottom of the shape represents the bottom of the view. The wider of the two ends represents where the "largest" values will be seen and the narrower of the two represents where the "smallest" of the values will be located. 

All that is to say ▲ means ASC (narrow at start, wide at end) and ▼ means DESC (wide at start, narrow at end). In the GUI, the observed behavior is the opposite.

#### What did you do?
Browse some data and click on a column header to get it to explicitly sort in a particular direction.

#### What did you expect to see?
![image](https://user-images.githubusercontent.com/606923/143779524-f48adaeb-f324-4591-93db-c6461d4b1bfd.png)

#### What did you see instead?

![image](https://user-images.githubusercontent.com/606923/143779499-66a78eb6-9709-4f35-aa42-7bb28e01c9ba.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows 10 1909
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
lol. I mentioned this a loooooong time ago, and it appears it's an operating system thing. On Windows, it goes one way, but in Linux and (I think macOS ... can't remember) it goes the other, so the developer who implemented it, followed the way his OS used.
Maybe it should be an option in 'advanced' ... ;)

**Comment by MKleusberg** [comment]
Thanks, @mqudsi! This should be fixed in tomorrow's nightly build. Can you give that a try? :smile:

**Comment by mqudsi** [comment]
It works great!
