### ISSUE TITLE
rowid sorts with the wrong icon

### ISSUE THREAD

**Issue by mqudsi** [sqlitebrowser/sqlitebrowser#2913]
I described the UX for sort order in #2912, but an additional issue is that for some odd reason when the rowid column is enabled and the user sorts by rowid, the incorrect glyph is shown (which probably means that internally the Qt sort behavior is being incorrectly set to a multi-column sort).

▲¹ should only be displayed if there is a sort applied to multiple columns and indicates "first sort by this column ASC then sort by the column showing ▲² or ▼² (and so on and so forth)"

Details for the issue
--------------------

#### What did you do?
Browse data, right-click to enable rowid, then click on the rowid header to sort by row id.

#### What did you expect to see?
The same sort order glyph I would see if sorting by any other column, e.g.

![image](https://user-images.githubusercontent.com/606923/143779962-f66a0132-b16f-42b9-a11f-f301b429d5c8.png)

#### What did you see instead?
![image](https://user-images.githubusercontent.com/606923/143779499-66a78eb6-9709-4f35-aa42-7bb28e01c9ba.png)

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows 10 1909
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.12.2
- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [X] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
lol.  I mentioned this a loooooong time ago, and it appears it's an operating system thing.  On Windows, it goes one way, but in Linux and (I think macOS ... can't remember) it goes the other, so the developer who implemented it, followed the way his OS used.
Maybe it should be an option in 'advanced' ... ;)

**Comment by MKleusberg** [comment]
Same here. This should also be fixed in tomorrow's nightly build. Can you give that a try too, @mqudsi? :smile:

**Comment by mqudsi** [comment]
Both the ordinalization and the direction of the indicator are now correct. Thank you!
