### ISSUE TITLE
Unexpected results when joining tables in the database

### ISSUE THREAD

**Issue by BSMS87** [sqlitebrowser/sqlitebrowser#2916]
Details for the issue
Joining many tables will result in an unexcited value. 

#### What did you do?
NA

#### What did you expect to see?
The only corresponding values/data in the table

#### What did you see instead?
sku will have some values like e001, e002, e003, etc, as return result set, which are not existed at all. 

Useful extra information
Steps to reproduce: 
1.  Download and Open the SQLite Datebase --> https://drive.google.com/file/d/13el133mdWeOi5SmOcjvPGHPXEVF1pakX/view?usp=sharing
2. Execute below statement

{code}
-- Join CategoryTree, ProductCategories, Products, OrderItems with filters:  (export file turnover.csv)
SELECT CT.category_id, CT.name, P.product_id, P.sku, SUM(( OI.qty_ordered - OI.qty_refunded - OI.qty_canceled) * OI.price) as turnover
FROM CategoryTree CT
INNER JOIN ProductCategories PC
	ON CT.category_id = PC.category_id
LEFT JOIN Products P
	ON PC.product_id = P.product_id
LEFT JOIN OrderItems OI
	ON PC.product_id = OI.product_id
WHERE OI.price != 0
GROUP BY PC.category_id
ORDER BY CT.category_id ASC

-- Products lists with price ( export fileProductsWithPrice.csv) :
SELECT PC.category_id, CT.name, PC.product_id, P.sku, p.price
FROM CategoryTree CT
JOIN ProductCategories PC
	ON PC.category_id = CT.category_id
JOIN  Products P 
	ON PC.product_id = P.product_id	
--WHERE p.price != 0
ORDER BY CT.category_id ASC;
{code}

3. Result set exported as csv: 
[turnover.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/7629590/turnover.csv)
[ProductsWithPrice.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/7629591/ProductsWithPrice.csv)

Best regards,
Bilal 

-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
> result in an unexcited value

No offense, but I'm not sure what an excited value is.  I assume you mean unexpected.  What rows/values do you expect?  Looking at an SQL statement, I'm not sure what values are right and what are wrong.
Can you limit the table to for example, 5 rows, showing 3 rows that are right, and 2 rows that are unexpected?  This would give us an example of 'this row shouldn't be there' and work out why SQLite has obtained it.

For the avoidance of doubt, the issue is in SQLite and how you're obtaining the records, not in DB4S itself.

**Comment by BSMS87** [comment]
Hi Chris,

Thanks for you quick response. I mean unexciting values. For example, if you have owned the attached database and explored or select the column 'sku' from the table Products, you will not find any values has 'e001' or 'e002' maintained etc. Just compare the outout attached (*.csv) or execute the join query with the main table, you'd see the issue. 

Thanks
Bilal
