### ISSUE TITLE
Combined characters in browser not displayed correctly

### ISSUE THREAD

**Issue by voidray** [sqlitebrowser/sqlitebrowser#2917]
I saw that there were already questions like this, for example https://github.com/sqlitebrowser/sqlitebrowser/issues/956, but in my case I'm not sure if it is the same issue. I want to store IPA characters in a table. The values themselves are stored correctly, but in the browser they are sometimes displayed incorrectly. If I copy the value in the browser to Notepad++ it is the correct value.

**Example:**
Browser
Character ![browser](https://user-images.githubusercontent.com/1024256/144367635-500f25c7-f417-401d-af12-7bef1eddfdb6.jpg) in 
![sample](https://user-images.githubusercontent.com/1024256/144367149-2aef2937-59f6-430a-b3c7-d004bea7670e.jpg)

Notepad++ displays it correctly:
![notepad](https://user-images.githubusercontent.com/1024256/144367295-b384d9a4-c653-4453-94d9-40fd6a40f3dc.jpg)

The complete IPA string is ɛɐ̯ˈkʊndɪçtn̩ - there is also an issue with the last character.
Both are combined characters. ɐ̯ for example consists of the following unicode characters:
U+0250
U+032F

OS: Win 10 64x
Version: 3.12.2

**Comment by voidray** [comment]
I found the source of the issue. It's just an issue with the font I configured. I changed it from Carlito to another font and the text is displayed as expected now. With the the default font MS Shell Dlg 2 it also works.

**Comment by chrisjlocke** [comment]
Thanks for reporting back - handy for someone else who encounters this.  👍
