### ISSUE TITLE
Expression based indexes are still broken in 3.12.2

### ISSUE THREAD

**Issue by VasiliPupkin256** [sqlitebrowser/sqlitebrowser#2918]
Details for the issue
--------------------

I see many closed issues here, but the bug is still present in the most recent release.

To reproduce make a simplest temporary database. 
Create a table with two INTEGER fields A and B, 
then press Create index button, press the gear button in a middle of the dialog type A - B and press OK.

Useful extra information
-------------------------

#### What operating system are you using?

- [X] Linux: ( distro: Ubuntu )

#### What is your DB4S version?

- [X] 3.12.2

**Comment by chrisjlocke** [comment]
Yup, followed your instructions and it worked.

![image](https://user-images.githubusercontent.com/7872218/144738127-3ea71f01-a10e-4a75-975d-437073d33ce8.png)

What am I missing?
Such detailed instructions, but I don't know what occurred for you after pressing OK.  It's like losing the last page in a thriller, when the detective says, "And I found this letter which proves the killer is..... " /no more pages

**Comment by VasiliPupkin256** [comment]
> What am I missing?

You've missed an error

    Creating the index failed:
    near "-": syntax error (CREATE INDEX "index2" ON "table2" (
    	a - b
    );)

And it is not a "modify structure" issue either. The same error appear when you open any db already containing an expression based index.

**Comment by chrisjlocke** [comment]
That's my point ... I've not got an error.  The index is there.

![image](https://user-images.githubusercontent.com/7872218/144741529-5a1c1d61-b489-4adf-a275-30444cb14fe9.png)

The issue may be fixed in the nightly (which I'm using).  I'll try again with the release.
As you're on Linux, can you build from the source at all, or use the PPA version? (which I believe is more recent)

**Comment by VasiliPupkin256** [comment]
I've visited https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing and only found builds from 2021-05-24 there. May be it is fixed in the master branch but the release downloaded from the release page is lacking support of expression based indexes. Hence the issue report. May be authors think it is a minor issue and there is no need to update the release but for me this regression is a complete game changer I just can't use it on my database.

**Comment by chrisjlocke** [comment]
The release isn't just dependant on this issue, unfortunately, but theoretically, the next release should contain this fix.  I haven't checked to see when this fix was added to the nightly branch.  I'm guessing (purely guessing) but it might be related to the version of SQLite in 3.12.2, etc ... has expression-based indexes been a thing in SQLite for a while?
Thanks for reporting it though - it'll ensure it gets picked up.  👍
Sorry the launchpad location didn't help.

**Comment by chrisjlocke** [comment]
Yes, if you can click 'Help' and 'About' and confirm your sqlite version.  I've tried in my 3.12.2, and that uses sqlite 3.35.5, and that worked OK.  I suspect your version may be lower than that?
Again, I don't know Linux that well (can't even pronounce it right) but you may be able to tell DB4S to use a different version.  I know you can't do that in Windows*, thus the nightlies...
(* easily)

**Comment by VasiliPupkin256** [comment]
I've used DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage downloaded from the website. DB Browser for SQLite Version 3.12.2 Built for x86_64-little_endian-lp64, running on x86_64 Qt Version 5.15.2 SQLCipher Version 3.2.0 (based on SQLite 3.8.6). The sqlite version installed on the host is 3.31.1. 
The previous release 3.11.2 works fine... it doesn't show the index content correctly but opens db and let me create a new expression based index.

**Comment by justinclift** [comment]
Interesting.  @deepsidhu1313 it sounds from the above that we might need to get a more recent SQLite version into the DB4S nightly build PPA.  Any idea how easy, hard, etc that might be to do?

On the other hand, we should start getting around to making initial 3.13.0 release alpha or beta builds in the near-ish future (weeks), so maybe that'll be the right time to investigate and fix this?

**Comment by deepsidhu1313** [comment]
I am still looking into fixing our builds, some of the builds are broken from last few days. I have fixed sqlite3 package and switched it to use 3.36 branch.

Thanks for the heads up @justinclift , i will try my best to fix builds before release

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by chrisjlocke** [comment]
@VasiliPupkin256 - Want to try the PPA link again and see if a more recent build helps the indexing issue?

**Comment by VasiliPupkin256** [comment]
I've downloaded a newer build 3.12.99 and it works fine. The only thing I don't like in this build is a redundant small dock caption on browse data tab but it is not the subject of this issue.

**Comment by justinclift** [comment]
> is a redundant small dock caption on browse data tab

Would you be ok to screenshot that?  It sounds like an accidental change... :smile:

**Comment by VasiliPupkin256** [comment]
I need a video to show this. In the new interface there are docking panels. You can drag them and dock. By default on the right all the tabs can be dragged and docked "Edit Database Cell" etc. On the left the only docking panel is in the browse data tab, you can't dock it anywhere else, only to the Browse Data tab client area and its caption duplicates the name of the selected table.

**Comment by chrisjlocke** [comment]
The docking panels in the nightly for the Browse Data tabs are 'work in progress' and was an experiment to see if we could have multiple 'browse data' panels, which is a great benefit, compared to the current release.  It's hoped this UI could be replicated throughout DB4S.

**Comment by mgrojo** [comment]
See this discussion:  #2283. It makes sense when you know what to do with the new Browse Data docks, but we could still make changes if they improve the usability. Otherwise, this is probably going to be released in 3.13 in the short term.

**Comment by VasiliPupkin256** [comment]
Ah you can open multiple browse data panels and arrange them in tabs and even rename them, I see now. Not very intuitive though, you have to right click on this tiny panel caption to open a new browser. If you don't rename them this caption just eats the screen vertical space. If you open multiple tabs then the same table name is repeated three times, on a tab name then in a dock panel caption and finally in the combobox. Not sure how to get rid of them preserving the functionality though.

**Comment by mgrojo** [comment]
@VasiliPupkin256, your comment has been an inspiration to implement this: c40fb07b879182b460b553f80152f14932c158c6, which I hope improves the current UI.

**Comment by justinclift** [comment]
Cool.  This sounds like another useful addition! :smile:
