### ISSUE TITLE
Understanding Mac Identity Services DB

### ISSUE THREAD

**Issue by macuser321123** [sqlitebrowser/sqlitebrowser#2921]
I'm trying to understand the information included in the Identity Services folder on my Mac.

Is there a way to differentiate between sent and received within idstatuscache.plist and ids-pub-id.db? What is the significance of the date/timestamp for each?

What's the difference between the following:
com.apple.private.alloy.nearby
com.apple.private.alloy.status.keysharing
com.apple.ess
com.apple.private.ac
com.apple.private.alloy.facetime.multi

**Comment by FriedrichFroebel** [comment]
You opened this issue in the issue tracker for DB4S, a SQLite database GUI. For this reason, doing arbitrary file analysis - like the content of a directory on an Apple device in your case - is out of scope here.

**Comment by chrisjlocke** [comment]
Closing this, as this issue isn't related to DB4S.  If you want to open this as a discussion (https://github.com/sqlitebrowser/sqlitebrowser/discussions) you're more than welcome to, in case anyone that uses DB4S might know what you're after...

**Comment by macuser321123** [comment]
Thanks for the notice! Where would be the most appropriate place to ask this question to get a suitable answer?

Is there a way to differentiate between sent and received within idstatuscache.plist and ids-pub-id.db? What is the significance of the date/timestamp for each?

What's the difference between the following:
com.apple.private.alloy.nearby
com.apple.private.alloy.status.keysharing
com.apple.ess
com.apple.private.ac

com.apple.private.alloy.facetime.multi


    On Tuesday, December 7, 2021, 10:25:46 AM EST, Chris Locke ***@***.***> wrote:  
 
 


Closing this, as this issue isn't related to DB4S. If you want to open this as a discussion (https://github.com/sqlitebrowser/sqlitebrowser/discussions) you're more than welcome to, in case anyone that uses DB4S might know what you're after...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisjlocke** [comment]
> Where would be the most appropriate place to ask this question to get a suitable answer?

Well, I note you've already posted on the apple stackExchange website, so that seems as good a place as any, as thats more apple OS related than this corner of Github.
