### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by HarisKordic** [sqlitebrowser/sqlitebrowser#2925]
Describe the new feature
--------------------------

Please implement dark mode :D 
Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.

Yes its just a simple dark mode of the same app
#### Do you have a screenshot? Please add screenshots to help explain your idea.

**Comment by chrisjlocke** [comment]
Unsure what this issue is for - are you requesting a dark mode, or do you have an issue with the existing dark mode of the application?
What operating system are you using?  What version of DB4S are you using?

**Comment by skyhirider** [comment]
@HarisKordic You mean like this setting?

![image](https://user-images.githubusercontent.com/1695005/146176689-ce221909-3c60-4de7-9c9e-8a7fe3dc09bd.png)

I wonder if dark mode should be set as default, as most software tools started setting dark as default to not burn our eyeballs out as much.

**Comment by HarisKordic** [comment]
Awesome, thanks!
*Haris Kordić*
*contact:*
Facebook <https://www.facebook.com/haris.kordic.7?ref=bookmarks>
Instagram <https://www.instagram.com/kordic_haris/>
LinkedIn <https://www.linkedin.com/in/haris-kordic-638566196/>
Email ***@***.***>
Phone: +387 63 709 440
Skype : kordicharis18
