### ISSUE TITLE
Support for the new STRICT keyword?

### ISSUE THREAD

**Issue by abceleung** [sqlitebrowser/sqlitebrowser#2926]
What is your question
-----------------------
SQLite 3.37 added the STRICT keyword for better type checking.

Does SQLite Browser plan to add support for this (very) nice feature? Is there a ETA?

Thanks!

**Comment by chrisjlocke** [comment]
The nightlies will most likely get the newest version of SQLite first, and I believe (although I may be mistaken) the process is automatic.  Actually, just checked, and the nightlies are using 3.36 and 3.37 was released end of Nov, so no, it's not automatic.  But hopefully, it'll be upgraded soon.  We're due a release of DB4S in the coming months, and that'll have the newest version in it too.

**Comment by little-brother** [comment]
Don't forget about `create table`-wizzard. It should have `strict`-option in `Advanced`-section.

**Comment by chrisjlocke** [comment]
Wizard? You mean the Edit Table dialog?

**Comment by little-brother** [comment]
![изображение](https://user-images.githubusercontent.com/20204037/146649286-8362d732-f49a-4027-8e94-7e433868f6f2.png)

**Comment by MKleusberg** [comment]
A list of todos here:

- [ ] Use the latest SQLite library version for builds.
- [ ] Add the ```STRICT``` keyword to the SQL parser. Without this working with strict tables will be very restricted.
- [ ] Add strict tables to the Edit Table dialog as suggested above.
- [ ] Add the strict keyword to the syntax highlighting and the auto completion in the SQL editors.

Add nice to have but not something I see coming any time soon:

- [ ] Respect the data types when editing or inserting data.

As for the ETA, I think I can implement most of this over the next couple of days. If @justinclift has the time to update the library version on the nightly build server you might be able to test it this year. It's also a good feature to include in our next release to make sure we're supporting the latest SQLite databases more or less completely.

**Comment by justinclift** [comment]
> If @justinclift has the time to update the library version on the nightly build server ...

Just did so for the Windows build VM.  It just uses whichever sqlite amalgamation .zip file it finds in a specific directory, so I've dropped the new 3.37 .zip there.  In theory, that should be all that's needed for it to start being used.

With macOS, things are more complicated.  We need to manually create updated macOS Homebrew package for the new version.  It takes a few hours, and is a bit of a pita.  So, won't be happening this week. :wink:

**Comment by justinclift** [comment]
Reading over the `STRICT` documentation that @chrisjlocke linked to, it does sound really useful.  Seems like the kind of thing that will help with places that use SQLite for unit testing their changes locally, prior to deploying to production.  Super common. :smile:

**Comment by MKleusberg** [comment]
I've implemented support for strict tables. @abceleung and @little-brother Are you using Windows or some other OS? If it's Windows you can download the latest nightly build [here](https://nightlies.sqlitebrowser.org/latest/) (but choose the win32 version for now as the win64 version didn't seem to build correctly) and give it a try.

@justinclift Any idea why there are no nightlies for Win64?

**Comment by justinclift** [comment]
> @justinclift Any idea why there are no nightlies for Win64?

Looking into it now.  There's also a newer SQLCipher release, so I've just updated the Win32 and Win64 nightly builds to use that too.

**Comment by justinclift** [comment]
This is the build log for the win64 run: [win64error.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/7783540/win64error.txt)

The error seems to be around line 729 onwards:

```
5>PlotDock.cpp
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\bitset(256): error C26
66: 'operator /': 11 overloads have similar conversions
5>C:\git_repos\sqlitebrowser\libs\qcustomplot-source\qcustomplot.h(901): note: could be 'const QCPRange operator /(const
 QCPRange &,double)'
5>C:\git_repos\sqlitebrowser\libs\qcustomplot-source\qcustomplot.h(459): note: or       'const QCPVector2D operator /(co
nst QCPVector2D &,double)'
5>c:\dev\qt\5.12.8\5.12.8\msvc2017_64\include\qtgui\qmatrix4x4.h(126): note: or       'QMatrix4x4 operator /(const QMatr
ix4x4 &,float)'
5>C:\dev\Qt\5.12.8\5.12.8\msvc2017_64\include\QtGui/qquaternion.h(318): note: or       'const QQuaternion operator /(con
st QQuaternion &,float)'
5>C:\dev\Qt\5.12.8\5.12.8\msvc2017_64\include\QtGui/qvector4d.h(281): note: or       'const QVector4D operator /(const Q
Vector4D &,const QVector4D &)'
[more stuff snipped]
```

**Comment by justinclift** [comment]
Running the win32build now as well, just to see if the new SQLCipher 4.5.0 release works ok.

**Comment by justinclift** [comment]
Yep, win32 compiles fine with SQLCipher 4.5.0 too.  So, that's a win. :smile:

**Comment by MKleusberg** [comment]
It's [a compiler bug](https://bugreports.qt.io/browse/QTBUG-72073). With VS 2017 you cannot use ```bitset``` in your Qt 5.12 application. Apparently there's a workaround in newer version of Qt which I've tried to activate in 2a99d20cdfff2bdc9d76b834339c06f1e2d5d1c6. Let's see if that works.

**Comment by justinclift** [comment]
Cool, just kicked off the win64 build again.  Lets see how it goes.

Looking at our Win build box, it's currently using Qt 5.12.8.  There's a Qt 5.12.12 available for download too, which we could also try.

**Comment by justinclift** [comment]
@MKleusberg Good stuff, that fix worked.  Win64 nightly build is now on the nightlies server.  Yay! :smile:

**Comment by chrisjlocke** [comment]
Just a nod that SQLite 3.37 has been patched due to a corruption bug.

    Patch release 3.37.2 fixes a potential database corruption bug.
    Upgrading is recommended for all users.

    The database corruption bug is obscure and you are unlikely to hit it.
    But you should probably still upgrade.  For more information about
    the bug see:
    
      *  https://sqlite.org/forum/forumpost/ac381d64d8

**Comment by justinclift** [comment]
Thank @chrisjlocke.  Saw that and updated the Windows build VM with that this morning. :smile:

**Comment by chrisjlocke** [comment]
This would only be in the nightlies - there hasn't been an updated main release yet.
The nightly version doesn't need 'installing' as such - its just a .zip that needs downloading and extracting.  If you've got the olde version, there shouldn't be an issue bribing your IT dept to allow you the nightly! ;)

**Comment by MKleusberg** [comment]
Closing this issue as it's been fixed some time ago. The changes are available in the nightly builds [here](https://nightlies.sqlitebrowser.org/latest/).
