### ISSUE TITLE
How to create new database with pwd ?

### ISSUE THREAD

**Issue by liufsd** [sqlitebrowser/sqlitebrowser#293]
HI. I want to create a sqlcipher database. Is it support or not ???
Thanks

**Comment by justinclift** [comment]
It is in MacOS, and if you compile it yourself on Linux, FreeBSD, etc.

It's not yet supported on Windows, though it likely will be in a future release (unsure when).

Which OS are you using?

**Comment by 79144876** [comment]
on  my MacBook pro.

**Comment by 79144876** [comment]
![screen shot 2015-05-04 at 9 34 39 pm](https://cloud.githubusercontent.com/assets/1910405/7454354/78b3a4c4-f2a5-11e4-9993-587634a6a1b2.png)

It's only create a simple database,not create a sqlcipher database (encryption).

**Comment by justinclift** [comment]
Ahhhh, no worries. :smile:

There are two possible downloads for MacOS X.  One with SQLCipher support, and one without it.

Here is the direct link for the one with SQLCipher support, if that helps:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.6.0/sqlitebrowser-with_sqlcipher_support-3.6.0.dmg

You can tell which version you have, by going to the menu bar → About DB Browser for SQLite.
![issue293-1](https://cloud.githubusercontent.com/assets/406299/7455557/521d066e-f275-11e4-92fe-66438b12de87.png)
Does that help?

**Comment by 79144876** [comment]
ok. i will download the sqlcipher version. and try it latter.
Thanks.

**Comment by 79144876** [comment]
ok. i have download SQLCipher Version 3.8.6 .
But when i create a database it also tips a simple database and then create a table .
how to create a SQLCipher database with my custom key ????
Thanks

**Comment by 79144876** [comment]
like this https://github.com/sqlcipher/sqlcipher

**Comment by MKleusberg** [comment]
@79144876 Encrypting databases is done in two steps: first creating an unencrypted database and then encrypting it.  After you've created a new database file (or opened an existing one), you can click the File -> Set Encryption menu option (only available in the sqlitebrowser version built with SQLCipher support) to set a password for your database. The old, unencrypted file then gets replaced by an encrypted version. I hope this helps a bit :smiley: Let me know if you have any further questions or problems.

**Comment by glawrence** [comment]
I have now started a Wiki page on this, happy for others to improve it

**Comment by justinclift** [comment]
Awesome Geoff.  Just added an entry for the wiki tracking issue about this too. :grinning:

**Comment by justinclift** [comment]
@liufsd Did you ever manage to get this working for you? :smile:

**Comment by liufsd** [comment]
yeah.great job~ thanks.
