### ISSUE TITLE
import data from csv

### ISSUE THREAD

**Issue by FRGrewenig** [sqlitebrowser/sqlitebrowser#2934]
Describe the new feature
--------------------------

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by Mohsyn** [comment]
????

**Comment by Mohsyn** [comment]
> ## Describe the new feature
> ## Additional info
> Please answer these questions before submitting your feature request.
> 
> #### Is your feature request related to an issue? Please include the issue number.
> #### Does this feature exist in another product or project? Please provide a link.
> #### Do you have a screenshot? Please add screenshots to help explain your idea.

Hi,
Since this is your first issue you opened up on github ever, allow me to inform you that you posted the issue without mentioning anything in description. Kindly delete and put a new one, answering the questions shared in template. 
:)

**Comment by mgrojo** [comment]
This made the 500th issue :smile:
Might be that people without experience in GitHub think they are searching for issues instead of opening a new one? @FRGrewenig, was that your case?
I'll try to use a new feature for issue forms, so this is less difficult to understand.
