### ISSUE TITLE
[Bug]: Test of the new bug form template

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2935]
### What did you do?

I opened a bug report

### What did you expect to see?

I expected that... a bug report was opened.

### What did you see instead?

What happened instead was that the issue was opened, so no problem. This is a test.

### Version

3.12.2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
This was a test for the new issue form template. It worked, so I'll close this, but feel free to comment any improvement or bug with the bug template :smile:

**Comment by chrisjlocke** [comment]
> Version
> 3.12.2

Although it's probably obvious, I'm wondering if 'DB4S Version' (or 'DB Browser Version') would be better, just to remove any ambiguity for OS Version.  May not ever happen, but just in case...

**Comment by mgrojo** [comment]
That makes sense. I just carried it over from the example. I'm also wondering if we should add more values to the dropdown for the OS to add more versions and/or Linux distributions. Another question is whether the text-area should be prepopulated or empty (they have a placeholder if they're empty, so this might be better).

**Comment by justinclift** [comment]
Good points.  Might as well try things out, and see how it goes? :smile:

**Comment by mgrojo** [comment]
I finally removed the prepopulated values, added a new optional separate input field for the OS version, and some hints for better reports, like suggesting screenshots or video recordings, or copying output from console or the "SQL Log" pane. Let's hope, this improves the quality of new bug reports.

**Comment by chrisjlocke** [comment]
> Another question is whether the text area should be prepopulated or empty

You've removed it anyway, but anything pre-populated is an admin nightmare - something else to maintain...
