### ISSUE TITLE
Unable to create new record when Not Null fields are present

### ISSUE THREAD

**Issue by Taresin** [sqlitebrowser/sqlitebrowser#294]
Hi guys,
I've got tables with fields marked as NotNull. Tried to add a new record which returns "Error adding record: NOT NULL constraint failed".
I'm guessing the logic defaults everything to NULL for the user to change.

Current workaround: uncheck not null fields, add new record, populate with requisite data, recheck not null fields

**Comment by MKleusberg** [comment]
This should be fixed by now :smiley: Any recent release should definitely work. Sorry for the late reply :frowning: I'm going to close this issue but if any issues with this happen to come up feel free to reopen it or open a new one any time :smiley:
