### ISSUE TITLE
Dialog is bigger than screen when editing views with long code

### ISSUE THREAD

**Issue by mocsa** [sqlitebrowser/sqlitebrowser#2941]
Details for the issue
--------------------

#### What did you do?
Right-clicked on a view and selected Modify View.

#### What did you expect to see?
A dialog box where I can see the OK and Cancel buttons and click on it.

#### What did you see instead?
Because the view had a very long SQL source code, and the dialog contained all of this code, the bottom of the dialog was past the bottom of the screen, and therefore it was not possible to click the OK or Cancel buttons. A workaround was to press Enter which selected the OK button.

The dialog window is not resizeable so it is not possible to increase its width to fit it on the screen.

I suggest to remove the SQL source code from the dialog entirely. In my opinion, it has no added value to display (potentially long) code in a dialog. The dialog's purpose is to let the user decide whether he wants to edit the code or not. Showing the code does not help in this decision. Also, if after pressing OK he decides it was not the View he wanted to edit, he can simply close the SQL tab.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Thanks for reporting this.
This is actually solved in the nightly, where the SQL is truncated, so has even less value than before .... 😉😁

![image](https://user-images.githubusercontent.com/7872218/148689494-ff355db1-4a16-4ed1-b619-ea26f71ec7a0.png)

I'll close this as it's resolved, but thanks for reporting it anyway.  👍

**Comment by chrisjlocke** [comment]
As a data point, the nightlies can be downloaded from here.
https://nightlies.sqlitebrowser.org/latest/

I'd suggest downloading the .zip and simply extracting it.  The .exe can be run 'as is' and doesn't need to be installed.  This means you can run the nightly and the installed version (if you've installed it ... again, you could just run from the zip) at the same time.
