### ISSUE TITLE
excel vba connection

### ISSUE THREAD

**Issue by john-peter-github** [sqlitebrowser/sqlitebrowser#2945]
Details for the issue
--------------------
When I bring data from .db file to excel sheet , there is a problem with some records that return  twice to the sheet and deleting the next record. The issue appears in record 256 and
adding 256 to it:  512,768 ..etc .
#### What did you do?
When I change the parameters of  `rst.Open strSQL, conn, 1, 1` to  `rst.Open strSQL, conn`
It returns only the missing records.

```
Private Sub CommandButton1_Click()
query_Data "SELECT * FROM Test_Table;"
End Sub
Private Sub query_Data(strSQL As Variant)
Cells.ClearContents
Dim conn As Object
Dim rst As Object
    Set conn = CreateObject("ADODB.Connection")
    Set rst = CreateObject("ADODB.Recordset")
        conn.Open "DRIVER=SQLite3 ODBC Driver;Database=E:\A disk\Lit\Data.db;"
        rst.Open strSQL, conn, 1, 1
                Range("A1").CopyFromRecordset rst
                rst.Close
        Set rst = Nothing: Set conn = Nothing
        Range("a1").Select
End Sub

```
 ##

#### What did you expect to see?
Data in sheet  the same as in db

#### What did you see instead?
issue in some records being duplicated removing the next record

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
> john-peter-github closed this 12 minutes ago

Did you find a solution?
