### ISSUE TITLE
[Bug]: Icon request

### ISSUE THREAD

**Issue by raffaem** [sqlitebrowser/sqlitebrowser#2946]
### What did you do?

1. Save [https://sqlitebrowser.org/images/sqlitebrowser.svg](https://sqlitebrowser.org/images/sqlitebrowser.svg) into a file
2. Open it with GNOME Image Viewer 41.1

### What did you expect to see?

The DB Browser for SQLite icon

### What did you see instead?

![image](https://user-images.githubusercontent.com/54762742/149914779-2b6fd99c-3cb6-435c-9735-176c77be14e0.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Fedora Workstation 35

### Workaround

Changing the last line of the SVG file from `</svg:svg>` to `</svg>` fixes the problem

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
If you download that file, do you see the tag then?
If I use Curl (which simply downloads the file) I see the correct tag.

![image](https://user-images.githubusercontent.com/7872218/149929224-07919cf0-0067-4b1e-a8ff-137f6681bbbd.png)

**Comment by raffaem** [comment]
> If you download that file, do you see the tag then? If I use Curl (which simply downloads the file) I see the correct tag.
> 
> ![image](https://user-images.githubusercontent.com/7872218/149929224-07919cf0-0067-4b1e-a8ff-137f6681bbbd.png)

Yes it looks like Firefox is adding that tag.

Thanks.
