### ISSUE TITLE
ER Model

### ISSUE THREAD

**Issue by DeWolFix** [sqlitebrowser/sqlitebrowser#2947]

**Comment by chrisjlocke** [comment]
I'll close this as it has no detail to it.
@DeWolFix - feel free to add some more information, and it can be reopened if we can assist.

**Comment by scottfurry** [comment]
Note: There is also [#1260](https://github.com/sqlitebrowser/sqlitebrowser/issues/1260)

**Comment by chrisjlocke** [comment]
Maybe they were just looking for glamour shots of the Queen? ;)
