### ISSUE TITLE
Export to SQL issue with phpmyadmin

### ISSUE THREAD

**Issue by opeth771** [sqlitebrowser/sqlitebrowser#295]
Hi.

I am not sure why, but I have tried exporting my database to SQL using dbviewer. Then, I go to my website and use phpmyadmin to import the SQL file, and I keep having errors. It does not seem to understand the begin transaction statement. I have tried removing it, but it keeps saying that "integer" is not a valid SQL statement either.

What can I do to import my database on my website?

Thank you very much!

**Comment by schdub** [comment]
@opeth771, SQLite data types not compatible with MySQL data types. You need to rewrite create statements (such as create table) with column types supported by MySQL.

More about comparison DB data types:
http://stackoverflow.com/questions/1942586/comparison-of-database-column-types-in-mysql-postgresql-and-sqlite-cross-map

**Comment by schdub** [comment]
@opeth771, ping? Your problem is solved?

**Comment by justinclift** [comment]
Closing due to lack of response and this is ancient. 😦
