### ISSUE TITLE
"variables" for SQL development

### ISSUE THREAD

**Issue by Schachigel** [sqlitebrowser/sqlitebrowser#2951]
When I develop a complex SQL statement in DB Browser to use it in my c++ code later, I wish there was the possibility to use variables in the statement, so that I can use the same value in the sql statement multiple times (e.g. a certain date or other value). 

Example: 
My SQL has multiple sub queries. All have a WHERE clause to restrict data to a certain time range. While testing and developing I need to change multiple locations, to get all sub queries using the correct time range.
In the final SQL statement used in C++ this would be done by value binding or text replacement. 

UX:
- if a variable is not set, db browser would prompt for a value
- if a variable is set, the value would be used (text replacement)
- there is a simple UI to change the values of variables

PS: maybe there is a way to accomplish something like this and I am just not experienced enough.

**Comment by mgrojo** [comment]
Is this the same feature as the one requested in #2683?

**Comment by Schachigel** [comment]
> Is this the same feature as the one requested in #2683?

Yes, I think this is pretty close to what I asked for. The statement developed in DB Browser would be easily used in C / C++ code with this feature implemented.

**Comment by chrisjlocke** [comment]
I'll close this to prevent duplicates and slight variations on existing open issues - with 500+ issues, we have to keep the number down! Hopefully when #2683 gets addressed, with three references to this issue in it now, this'll get flagged too.
