### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by TimKarsten** [sqlitebrowser/sqlitebrowser#2953]
Hi,

love your software!
Can we get a darkmode setting? My eyes hurt at night.

Thanks!

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?
What operating system are you using?

If you click 'Edit' and 'Preferences' do you see an 'Application Style' option?

![image](https://user-images.githubusercontent.com/7872218/151073029-65bd9c9c-578d-45f2-bf73-3e104468efd4.png)

If you do, and you select 'Dark', then you might get your wish.

**Comment by TimKarsten** [comment]
You are my favorite person of this week. Scrap that, this month!

Yes it is there and I overlooked it.

**Comment by chrisjlocke** [comment]
Glad you found it, but more importantly glad it worked.

Out of interest, what could we do to make this more obvious?  A newsletter about 'things you didn't know about DB Browser for SQLite'?  Twitter notifications?  I use an application at work that fires up 'tips of the day' but after a while, everyone turns that off.
When we release new releases, we do issue a 'here's what's new' but it's easy to miss this, especially if you install straight to version 3.12.2 ...
I could do YouTube videos on using DB4S, but unless you specifically trawl through YouTube videos, you'll not just stumble on it.
