### ISSUE TITLE
[Bug]: Tables referenced by a view can't be modified.

### ISSUE THREAD

**Issue by JC3** [sqlitebrowser/sqlitebrowser#2956]
### Description

If a view exists that references a table, and I then try to modify that table using SQLiteBrowser's Modify Table UI (e.g. with the "Modify Table" button), the following error appears when the modifications are accepted, and the modification fails:

![image](https://user-images.githubusercontent.com/5651184/151202727-b7e777e5-672d-4355-b956-ca744092461b.png)

SQL Log:

```
PRAGMA foreign_keys;
PRAGMA foreign_keys = '0';
PRAGMA collation_list;
SAVEPOINT "db4s_edittable_16432140271434280";
SAVEPOINT "db4s_renamecolumn_16432140305115914";
SAVEPOINT "RESTOREPOINT";
ALTER TABLE "main"."test" ADD COLUMN 	"x"	INTEGER
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("theview");
SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
CREATE TABLE "sqlb_temp_table_4" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT,
	"x"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "main"."sqlb_temp_table_4" ("id","name") SELECT "id","name" FROM "main"."test"
PRAGMA defer_foreign_keys;
PRAGMA defer_foreign_keys = '1';
DROP TABLE "main"."test"
ALTER TABLE "main"."sqlb_temp_table_4" RENAME TO "test"
ROLLBACK TO SAVEPOINT "db4s_renamecolumn_16432140305115914";
RELEASE "db4s_renamecolumn_16432140305115914";
ROLLBACK TO SAVEPOINT "db4s_edittable_16432140271434280";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("theview");
SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
RELEASE "db4s_edittable_16432140271434280";
PRAGMA "main".foreign_key_check
PRAGMA foreign_keys = '1';
```

Error:

```
(1) statement aborts at 26: [ALTER TABLE "main"."sqlb_temp_table_4" RENAME TO "test"] error in view theview: no such table: main.test
(1) executeSQL:  "error in view theview: no such table: main.test (ALTER TABLE \"main\".\"sqlb_temp_table_4\" RENAME TO \"test\")" (, :0)
(1) "Error renaming table 'sqlb_temp_table_4' to 'test'.\nMessage from database engine:\nerror in view theview: no such table: main.test (ALTER TABLE \"main\".\"sqlb_temp_table_4\" RENAME TO \"test\")" (, :0)
```

### Steps To Reproduce

The issue can be produced by first setting up a new database as:

```
CREATE TABLE "test" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE VIEW "theview" AS SELECT * FROM "test";
```

And then selecting the "test" table, clicking "Modify Table", making some changes and pressing OK.

Note that "Modify Table" will work just fine if you do it before creating the view, or after deleting the view.

### DB4S Version

3.12.2 (SQLite 3.35.5)

### What OS are you seeing the problem on?

Windows 10, 64-bit

**Comment by JC3** [comment]
I found one possible solution at https://sqlite.org/forum/info/db1ff37c1b9e5b2b, which is to enable [`legacy_alter_table`](https://www.sqlite.org/pragma.html#pragma_legacy_alter_table) prior to the rename, e.g. from the above example:

```
PRAGMA legacy_alter_table=ON;
ALTER TABLE "main"."sqlb_temp_table_4" RENAME TO "test"
```

I can confirm that this works, but I don't know what the other implications of that pragma are. 

---

Slightly edited version of forum thread for posterity:

OP: Mark, on 2020-04-30 18:21:27
> **Renaming TABLE *into* existing VIEW definition?**
> 
> Don't know how to describe my issue better than this:
> ```
> CREATE VIEW v1 AS
>     SELECT * FROM x;
> 
> CREATE TABLE y(id INTEGER);
> 
> ALTER TABLE y RENAME TO x;
> ```
> -- Error: near line 6: error in view v1: no such table: main.x
> I don't know why the rename concerns itself with table 'x'. It feels to me like that error is raised a little too early.
> 
> https://sqlite.org/lang_altertable.html says:
> 
> > If the table being renamed has triggers or indices,
> > then these remain attached to the table after it has been renamed. 
> > That doesn't seem to cover this situation. If this is not a bug per se then perhaps the documentation could at explain the background actions (and constraints) in more detail.

Response: Dan, on 2020-05-04 07:35:05:
> Use:
> ```
>       PRAGMA legacy_alter_table=ON 
> ```
> before the ALTER TABLE command.

**Comment by chrisjlocke** [comment]
Yes, since that modification to SQLite, it's a feature.  Setting that pragma is the correct workaround.
Frustratingly, even the example they give in the instructions to 'get around' the problem don't work and produce the same error as above.

I'll close this as this is a duplicate, but the pragma workaround is the official workaround.
The error is by design. /sighs heavily.  I keep forgetting it myself whenever I edit a database I'm working on which uses views (which I don't normally use, personally).

**Comment by JC3** [comment]
@chrisjlocke Maybe it makes sense to add a toggle to the Modify Dialog to allow the user to more conveniently enable that pragma if necessary? Possibly with an explanatory tooltip saying something like "if you have views, and this fails, try checking this box" or something.

**Comment by chrisjlocke** [comment]
> Maybe it makes sense to add a toggle to the Modify Dialog 

No, the pragma just needs implementing.  Let DB4S run with that pragma enabled by default.  Why have an option that just fails anyway?  The pragma doesn't break anything - it just allows the table modification to run.  Tables cannot be edited without it.  Even the 'official' way to edit tables without that pragma doesn't work, so it just needs turning on.  /rant rant rant 😁

**Comment by GitSparTV** [comment]
Please add to "Edit Pragmas" tab. For every change in table with referenced view I have to find this issue to copy `PRAGMA legacy_alter_table=ON;`. It would be perfect if it switches this for me
