### ISSUE TITLE
String & datetime manipulation

### ISSUE THREAD

**Issue by Buyankhuu** [sqlitebrowser/sqlitebrowser#2957]
1) How to valid datetime value from string, Example: '2022-01-32 12:00:00',  '2022-01-30 12:10:00 PM'
Is there check valid datetime string?

2) How to separate hour, minute, and other value from datetime value?

**Comment by chrisjlocke** [comment]
You can use CHECK constraints to validate dates.

https://www.sqlite.org/lang_datefunc.html#overview

So when building the table, the dateField can be

    `dateField` text not null CHECK(dateField IS date(dateField))

I tend to store dates and times as yyyy-MM-dd HH:mm (plus :ss if you need the precision)) which makes usual string slicing possible - the hour is always two characters from the 12th position in the string, etc.

**Comment by scottfurry** [comment]
strftime function shown on the [SQLite datetime functions](https://www.sqlite.org/lang_datefunc.html) page would fit. You would use the string specifiers '%H', '%M' and '%S' to extract.

[SQLite Tutorial page for strftime](https://www.sqlitetutorial.net/sqlite-date-functions/sqlite-strftime-function/) may be of some help.

**Comment by Buyankhuu** [comment]
> You can use CHECK constraints to validate dates.
> 
> https://www.sqlite.org/lang_datefunc.html#overview
> 
> So when building the table, the dateField can be
> 
> ```
> `dateField` text not null CHECK(dateField IS date(dateField))
> ```
> 
> I tend to store dates and times as yyyy-MM-dd HH:mm (plus :ss if you need the precision)) which makes usual string slicing possible - the hour is always two characters from the 12th position in the string, etc.

Thank you.
