### ISSUE TITLE
Cannot register .db extension in Windows 7 x64

### ISSUE THREAD

**Issue by Anthirian** [sqlitebrowser/sqlitebrowser#296]
As the title says I'm having trouble registering the ``*.db`` file extension. When I double click such a file I'm asked to select the program to open it with. When I navigate to ``C:\Program Files\sqlitebrowser3\bin`` and choose ``sqlitebrowser.exe`` it is not added to the "Open with" window and thus I can't select it as the default option.

**Comment by justinclift** [comment]
This sounds like a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/279.

Does the solution at the bottom of that work for you?

**Comment by Anthirian** [comment]
It seems like the same issue, but I didn't find it using the search. I'll attempt the solution later this week and let you know.

**Comment by Anthirian** [comment]
Yes that solution has worked for me. I changed the value of ``HKEY_CLASSES_ROOT\Applications\sqlitebrowser.exe\shell\open\command`` from ``"C:\Program Files (x86)\SqliteBrowser3\bin\sqlitebrowser.exe" "%1"`` to ``"C:\Program Files\SqliteBrowser3\bin\sqlitebrowser.exe" "%1"`` and the extension can once again be registered. Thanks for the help.

**Comment by justinclift** [comment]
Cool. :smile:
