### ISSUE TITLE
Execute SQL tab is missing DB browser for sqlite

### ISSUE THREAD

**Issue by gsk9999** [sqlitebrowser/sqlitebrowser#2962]
Details for the issue
--------------------

#### What did you do?
Installed the latest version DB.Browser.for.SQLIte-13.2.1-win64-v2.msi from website 

#### What did you expect to see?
After installing in the machine it should display the Execute SQL tab along with other tabs like Database structure, Browse Data & Edit program tab.

#### What did you see instead?
Execute SQL tab is missing after opening the applicaion

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19042) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
If you click 'View', 'Window Layout' and 'Reset Window Layout' then that should ... well, reset your window layout.

![image](https://user-images.githubusercontent.com/7872218/151928892-78e03095-4d21-4fd1-957c-da5b1e0ce90f.png)

Alternatively, click 'View', and toggle the panes back on.

![image](https://user-images.githubusercontent.com/7872218/151928955-1ebdd93f-aa0f-4362-9f55-0f7d267a655b.png)

If you then close DB4S it'll write these values properly to the registry.
I suspect somewhere along the line it's written duff information, so corrupted itself.

**Comment by chrisjlocke** [comment]
Out of interest where did you get that link from?
The current windows releases are here:
https://sqlitebrowser.org/dl/#windows

And they should point to 3.12.2 ... (excusing the obvious 13. instead of 1.), you point to 3.12.1 with a _v2 suffix - looking in the download directory, that file doesn't exist anymore.

But ensure you're running 3.12.2.

**Comment by gsk9999** [comment]
Got it.. Thanks for your quick support.

**Comment by chrisjlocke** [comment]
Always a pleasure.  Glad you're back up and running.  👍
