### ISSUE TITLE
all directories not showing in list 

### ISSUE THREAD

**Issue by richllittle** [sqlitebrowser/sqlitebrowser#2969]
_Details_ for the issue
--------------------

#### What did you do?
Attempted to open a Database file

#### What did you expect to see?
the directory where the file is

#### What did you see instead?

two directories are missing from the list - /4tb and /SS360 - these refer to additional drives in my machine
Useful extra information
These directories show in terminal and in files, and I can access them with no problem from either place.
They also show up in lists in other software.
-------------------------
> DB4S v3.12.99 (May 24 2021) [built for x86_64-little_endian-lp64] on Ubuntu Core 16 (linux/5.13.0-28-generic) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.5.1

**Comment by richllittle** [comment]
Upon doing some more testing, I discovered this only happens with the snap install, also the program says a good database is invalid.
I installed it form the repositories using synaptic manager and it works fine - all directories, reads database fine.
Seems like the snap is not correct.

**Comment by chrisjlocke** [comment]
Apologies - looks like this issue got overlooked.
A snap from May 2021 would be quite old, so assume this is now resolved, as the snap would have been replaced?
I'll close this, but if you see its still an error, please let us know.
