### ISSUE TITLE
Typo in DB Browser French version

### ISSUE THREAD

**Issue by kanter** [sqlitebrowser/sqlitebrowser#2973]
Details for the issue
--------------------

#### What did you do?
the messagebox to warn the user that a file has been modified by another program contains a type "Vioulez-vous recharger..." instead of "Voulez-vous..."

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Thanks, I'll have a quick search to find that dialog.  Thanks for reporting it.

**Comment by MKleusberg** [comment]
Thank you very much! I've just fixed it :smile:
