### ISSUE TITLE
Error changing order of columns in database containing views

### ISSUE THREAD

**Issue by krisvanneste** [sqlitebrowser/sqlitebrowser#2976]
Details for the issue
--------------------

#### What did you do?
I have a database containing several tables and views. I added a new table "fluvial_terraces", which went fine.
However, when I try to modify the table, either by changing the order of the columns or adding more than 1 column at once, I obtain an unexpected error.

#### What did you expect to see?
I expected the table to be modified without any problems, similar to other tables I have modified in the past.

#### What did you see instead?
I received the following error:

Error renaming table 'sqlb_temp_table_3' to 'fluvial_terraces'.
Message from database engine:
error in view geomagnetic_reversals 1st ORDER BY term does not match any column
in the result set (ALTER TABLE "main"."sqlb_temp_table_3" RENAME TO "fluvial_terraces")

Additional comments:
- the view "geomagnetic_reversals" does not depend in any way on the table "fluvial_terraces"
- I can see the contents of the view "geomagnetic_reversals" perfectly fine with "Browse Data".
There is no problem with the ORDER BY clause.
- I can reorder the columns manually with python/sqlite without errors, using the following commands:
ALTER TABLE fluvial_terraces RENAME TO temp_fluvial_terraces
CREATE TABLE fluvial_terraces(name TEXT, alt_name TEXT, river TEXT, terrace_group TEXT, period TEXT, correlation TEXT, age_top REAL, age_top_method TEXT, age_top_source TEXT, age_top_unc TEXT, age_base REAL, age_base_method TEXT, age_base_source TEXT, age_base_unc TEXT)
INSERT INTO fluvial_terraces(name, alt_name, river, terrace_group, period, correlation, age_top, age_top_method, age_top_source, age_top_unc, age_base, age_base_method, age_base_source, age_base_unc) SELECT name, alt_name, river, terrace_group, period, correlation, age_top, age_top_method, age_top_source, age_top_unc, age_base, age_base_method, age_base_source, age_base_unc FROM temp_fluvial_terraces
DROP TABLE temp_fluvial_terraces

So I have the impression it is a bug in DB Browser, not in sqlite.

Thanks for looking into this issue,
Kris Vanneste

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
If you click in the 'Execute  SQL' tab and type

    pragma legacy_alter_table=on;

and run that, the table edit should work.
There was a 'fix' to SQLite which means you can't edit tables if there are any views which link to that table.  You can delete the view first and try again, but the above pragma fix is easier.

**Comment by krisvanneste** [comment]
Dear Chris,

Thanks, the pragma fix works indeed!

Kris

**Comment by chrisjlocke** [comment]
It's a bit of a nasty gotcha, and DB4S isn't helpful with the error.  In an ideal world, it should say something like 'blah blah didn't work - apply the pragma for you?', but in a more meaningful way, of course.
We have menu options for integrity checks, etc, so maybe one more to apply this pragma.

I'll close this as its resolved, but thanks for raising it.
