### ISSUE TITLE
Please do static build

### ISSUE THREAD

**Issue by mvrhov** [sqlitebrowser/sqlitebrowser#298]
Previous versions were all build statically. So I could have exe file in one directory.. The 3.6.0 is build dynamically with a bunch of files which is not very nice. You should also link to the msvcrt statically.

**Comment by justinclift** [comment]
Yeah, it's one of the tradeoff's that have come with using a new build process so we get 64-bit capable binaries on Windows.

If it helps, our nightly builds are still created using the old process.  So if you grab a nightly build it will have the latest source code and still be just one .exe. :smile:

**Comment by justinclift** [comment]
@mvrhov This is probably not going to happen.

We're moving towards using Qt5 only, and at least for Windows it seems statically build with Qt5 is a pain, and may not even work properly. (eg lack of image plugins) 😦

**Comment by chrisjlocke** [comment]
Does this mean the nightlies won't be one .exe?

**Comment by justinclift** [comment]
Yep. :wink:

**Comment by chrisjlocke** [comment]
Guess thats good in one way .... without all the Qt DLLs, the .exe is 2 MB rather than 32 MB...  The .exe should get updated but the DLLs won't change as often, so should just be a matter of downloading a smaller .exe and overwriting it.

**Comment by chrisjlocke** [comment]
I'll close this, as our build process is pretty much settled now, and our 'portable' ZIP allows a non-installed install.  There is also two portable versions - the official portableApps version, and my version.
