### ISSUE TITLE
Cannot get to home page to add or delete recoreds

### ISSUE THREAD

**Issue by DavidSwiss** [sqlitebrowser/sqlitebrowser#2981]
Details for the issue
--------------------
I installed DB Browser and created one database with 2 fields.

I am trying to get to the home page to add / delete records

![image](https://user-images.githubusercontent.com/29735787/154245268-93e2aa26-7a08-4dc9-bf90-94896b4f64e3.png)

![DB Browser home screen](https://user-images.githubusercontent.com/29735787/154245155-48ed3e06-bc29-45c0-8fd2-06fa22494a39.JPG)

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
I'm very confused.  You state you're using Windows 10, but that's  not a Windows 10 screenshot.  You state you're using 3.12.2 but that's not a screenshot of 3.12.2.  You state you've added two records, but the screenshot shows 12.

**Comment by DavidSwiss** [comment]
Thanks  for the mail.  Those screen shots were from a course I'm taking.  Am using DB Browser 3.12.2.  Doesn't look the same but I have been able to figure it out and make it work.

**Comment by justinclift** [comment]
No worries at all.  Hope your course goes well. :smile:

**Comment by chrisjlocke** [comment]
Just being nosey, but a course on SQLite, SQL, or databases in general?  It's always interesting to see what courses are 'advertising' DB4S.  
While this is primarily an issue portal for DB4S, we're (well, mainly me) are keen to take beginners questions on SQLite and SQL, so if you need any help in your journey, let me know.
As Justin says, hope the course goes well.  Good luck!
