### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by resuwa** [sqlitebrowser/sqlitebrowser#2982]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS Mojave (10.14) (darwin/18.7.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by chrisjlocke** [comment]
I'll close this as there isn't enough detail to assist.
@resuwa - if you can provide more information, then we can reopen and investigate this for you.
