### ISSUE TITLE
[Bug]: Lost the Plot

### ISSUE THREAD

**Issue by dsunanda** [sqlitebrowser/sqlitebrowser#2990]
### What did you do?

Downloaded and started using yesterday.

Today, ability to use Plot suddenly vanished,

I tried .... 

--exiting and restarting.
--Uninstalling and reinstalling
--Uninstalling; and then installing the latest Nightly (DB Browser for SQLite Version 3.12.99 (Feb 23 2022)  ... Built for x86_64-little_endian-llp64, running on x86_64 ...Qt Version 5.12.8 ...SQLite Version 3.37.2.)
--Rebooting
--Seeing if overly official malware detection had quantantined a vital file (It hadn't)

Nothing helped.

(I am on SQLite SQLite version 3.38.0 2022-02-22 18:58:40 - which is more recent than the version mentioned in the Build info for your product above .... But it worked fine for 24 hours).

### What did you expect to see?

Either Plot keeps working - or a message tells me I now have to pay to keep going. (I don't mind if Plot is a demo that needs activation......But, if so, Please make that obvious).

### What did you see instead?

See here. The X Y axis dialog has vanished. I can resize what I see. I can even add/remove the Legend box (it's a tiny white square). But can't plot any tuples.

https://i.imgur.com/bToAEZv.png

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Relevant log output

```shell
If I fresh-start the application, connect to a DB and do a SELECT, then attempt to plot:

--The User logs and Error logs are empty.

--SQL log has nothing unexpected,
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Looks like the column selection pane has been closed up.

If you move the mouse to just under 'Plot', the mouse should change to the 'move pane' cursor.

![image](https://user-images.githubusercontent.com/7872218/158245896-bcc41a8b-ce16-40d1-9e41-28cc5de219c0.png)

Click and drag it down.

![image](https://user-images.githubusercontent.com/7872218/158245943-7ce5b7de-07a7-4121-9d66-ad8fa9c3008b.png)

The pane looks like its become undocked.  You might want this.  if you want it as it was, simply double-click the 'Plot' caption bar 

![image](https://user-images.githubusercontent.com/7872218/158246390-6c837fc8-28fb-4832-affd-5729e0af565a.png)

Once you can see the column selection area, tick the columns you want to add them to the plot.

Yell back if this helps.

**Comment by chrisjlocke** [comment]
> which is more recent than the version mentioned in the Build info for your product above 

Do you mean the official 3.12.2 build?  The nightly would be newer than the release version, and contains a more up to date version of SQLite.  This is as expected. 👍

**Comment by dsunanda** [comment]
Brilliant - thank you!

The column selection panel is now visible again, and it is all looking good.

Just an additional note for anyone who has a similar problem:

> If you move the mouse to just under 'Plot', the mouse should change to the 'move pane' cursor.

That does not work if there is no Select statement active - a freshly opened instance of the application will not show the 'move pane' option when the mouse is under 'Plot' (I spent a couple of minutes micro-adjusting the cursor and getting nowhere ;) ..... I guess the pane is effectly grayed out if there is nothing Plot-able.

One Select later, and all is well.

Thanks again!

**Comment by chrisjlocke** [comment]
> That does not work if there is no Select statement active 

Aah, good point!  Thanks!
I'll close this as it's been resolved.  Glad you got it sorted. :)
