### ISSUE TITLE
[Bug]: Error msg related to the current release number [Certificate issue]

### ISSUE THREAD

**Issue by DCourtel** [sqlitebrowser/sqlitebrowser#2992]
### What did you do?

Each time I open Db browser for SQLite I see this error message:
![image](https://user-images.githubusercontent.com/13787283/159116049-4fa9ae06-dd44-4d0c-8929-ed12a99d8cbc.png)
However, I can successfully open the remote file and the certificate is trusted.

### What did you expect to see?

No error message and the check for a new release should run smoothly.

### What did you see instead?

An error message.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows Server 2019

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
You mention the nightly, but what version of the nightly?
I've run the nightly from 20 Feb, and I don't get this error.  Would your firewall be blocking DB4S getting the certificate details at all?
It's moaning about a local certificate ... which is why I was wondering what version of the nightly it was.

**Comment by DCourtel** [comment]
I use Version 3.12.99 (Feb 23 2022).
In the firewall I can see outgoing trafic to apps.identrust.com and download.sqlitebrowser.org, both are allowed. Even if I disable the firewall I get this warning message.

**Comment by chrisjlocke** [comment]
Not that it was related, as you posted this in March and the certificate expired in April, but it's now May.  Are you still getting this error, even though the certificate has been renewed?

We've not had any other reports of this, so seems suspicious it is something local to your environment.
Does turning off the check for updates help at all?
