### ISSUE TITLE
64-bit Windows nightlies not updating

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2994]
The 32-bit Windows nightlies were updated last night following a recent commit, but doesn't appear the 64-bit versions (zip or MSI) were updated.

![image](https://user-images.githubusercontent.com/7872218/159673758-f5ca6cf7-986a-46f3-b777-e629ccfdb817.png)

**Comment by justinclift** [comment]
Checked now, and they're in place.  Looks like they just took a bit longer to complete. :smile:

**Comment by chrisjlocke** [comment]
Whoopsie.  Thanks for checking! 😁
