### ISSUE TITLE
Scrolling behavior

### ISSUE THREAD

**Issue by acet3chnician** [sqlitebrowser/sqlitebrowser#300]
Scrolling in one direction at a time is not possible. Very difficult to stay in same column when scrolling down because it scrolls left or right at the same time. Locking first scroll direction would be a big improvement.

**Comment by justinclift** [comment]
Interesting.  Which OS and version are you using?

**Comment by acet3chnician** [comment]
Sorry, my laptop fan just died so can't retrieve version. But just update to latest release a few weeks ago on OS X Yosemite.

**Comment by justinclift** [comment]
Ok.  We released a new version a few days ago, so try that and see if it's better?  (it may or may not be, but it's worth a shot :smile:)

Btw, I'm trying our new 3.6.0 release here now on OSX 10.9.  In the Browse Data tab I have a field in a column selected.  When I scroll down using the scroll wheel, the PgUp/PgDn keys, or using the mouse on the scrollbar, the field that is selected isn't lost.

Just so I understand better... what are you using to scroll?

Also, my sample table is only a few columns wide.  Is the database table that's doing this for you very wide?

**Comment by acet3chnician** [comment]
Trackpad for scrolling. I'll have to wait about a week for my new fan, then I can try latest release.

**Comment by acet3chnician** [comment]
Yes, wide and tall databases

**Comment by justinclift** [comment]
Cool.  Please let us know how it goes. :smile:

**Comment by acet3chnician** [comment]
Will do, thanks. Get some rest :grin

**Comment by acet3chnician** [comment]
OK, just received my new fan and MBPro is working again. Found that my installed sqlitebrowser version was 3.6.0. So already had the newest (other than nightlies which I haven't tried yet)

**Comment by acet3chnician** [comment]
Just wanted to comment that i'm still seeing this scrolling behavior in v3.7.0

**Comment by justinclift** [comment]
No worries at all. :smiley:
