### ISSUE TITLE
Max and Min function in SQLite is bugged

### ISSUE THREAD

**Issue by Beeruitamsterdam** [sqlitebrowser/sqlitebrowser#3004]
Details for the issue
--------------------

#### What did you do?
I used SQL line <select brin_naam, brin_gemnr, min("telling_vototaal.2019") from leerlingen where brin_gemeente like 'amsterdam'>
and for max:
I used SQL line <select brin_naam, brin_gemnr, max("telling_vototaal.2019") from leerlingen where brin_gemeente like 'amsterdam'>

#### What did you expect to see?
brin_naam	                                                                                  brin_gemnr	         min("telling_vototaal.2019")
Stichting Joodse Kindergemeenschap Cheider MAVO HAVO VWO	363	                        37,00
brin_naam	                                                           brin_gemnr	         max("telling_vototaal.2019")
Esprit Scholen voor Lyceum Havo Mavo Vbo Lwoo	363	                      4821,00

#### What did you see instead?
brin_naam	                                        brin_gemnr	         min("telling_vototaal.2019")
Fons Vitae Lyceum voor havo en vwo	      363	                         1057,00
brin_naam	                                                                                                brin_gemnr	         max("telling_vototaal.2019")
Scholengemeenschap voor Athenum en Havo Het Hervormd Lyceum Zuid	      363	                            933,00

Useful extra information
When i use ORDER BY "telling_vototaal.2019" -> I see it is ordered as TEXT instead of NUMERIC
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
SQLite is a bit like the stroppy four-year old child you asked to go to the shop, with instructions to buy a carton of milk, "and, if they have avocados, get six.".  When you ask them why they returned with six cartons of milk, they will reply, "They had avocados".

I doubt there is a bug in SQLite, but more to do with the data you're putting in.  A field in SQLite can be many things, but two of the main things is either a numeric value or text.  SQLite tries to guess what you're putting in and the column itself can be set up to guide it, but again, like the stroppy four-year old, it will happily shove a red circle in a box designed for blue triangles.

What would be useful if you right click on the table (leerlingen) select 'Copy create statement' (or whatever it translates as) and paste it here.
It would also be useful to copy the insert statement used to put the data in that record and paste that here too, to see if the field is a red circle or a blue triangle.  If you try and sort on red circles but the data is blue triangles, then the output won't be what you think it will be.  
I'm guessing (but I'm usually wrong, especially on red circles with blue triangles) the commas in the numbers is confusing it, and its treating the numbers as text.  This is why 933 is coming out last - 9 is higher in the textual sorting order than 1.  
You get bonus points for adding in the DB4S version and operating system information in your post.  Thanks for that.  Any reason why you're using the SQLCipher version and not the normal SQLite version?  If its an encrypted database then that's a cracking answer, but the normal version has a slightly newer version of SQLite. Not that 3.34 is a buggy piece of teabags, but just there is a newer version.

**Comment by Beeruitamsterdam** [comment]
You are right, it is the source which is the problem. I converted a *.xls to *.csv with utf-8 comma seperation instead of *.csv with listseperationmark. Now the numbers in the *.csv file are INTEGER as "123", while with comma seperation the numbers became REAL like "123,00". Now i have imported the files again in the DB and the sql works.
**Lesson learned, always check the source for irregularities!**

**Comment by chrisjlocke** [comment]
You lose precision converting from real to integer - +/- 1, eg, 9.5 is going to be 9 or 10, and not 9.5 - is that going to be an issue?  SQLite obviously handles real (float) numbers, eg, 4.56, but depending on the number format/system locale, they just need to be input right for SQLite to know they're numbers and not text.
If you have text in a field, SQLite can cast them to a number.  

![image](https://user-images.githubusercontent.com/7872218/161431699-d1f1a5e1-5a3d-4622-909d-f2f52e4493ae.png)

My system doesn't know what '123 45,67' is, so can replace spaces with nothing, and commas with full-stops (or periods) to get a flat number of 12345.67.  This can then be converted to an actual number.

**Comment by Beeruitamsterdam** [comment]
The issue is importing the right convertion. While my first problem is solved. i now have a problem with the real numbers which are converted to text instead of real. So maybe your advise may be helpfull again. 

This works:
<SELECT brin_naam, max(CAST(replace("prognoses_vototaal.2022", ",", ".") as REAL)) from leerlingen3 WHERE brin_gemeente LIKE "Amsterdam">
Result:
Esprit Scholen voor Lyceum Havo Mavo Vbo Lwoo	5417.25

But can i change country settings in SQLite so he reconize the  comma as devider?
[leerlingen2.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/8404718/leerlingen2.csv)

**Comment by mgrojo** [comment]
You can configure DB4S to interpret ',' as decimal separator (see #2140), but you need a [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) for that.

**Comment by chrisjlocke** [comment]
I think if you import into a text field, then cast that into another field, it would work.
Edit: mgrojo's idea is better and 'cleaner'.

**Comment by Beeruitamsterdam** [comment]
I started the nightly build and made a new DB and imported the  file "Leerlingen 2.csv' and now i could check "Use local number conventions". Now The real numbers are converted to real in the DB. The function Min and Max work great now.
Question, is this only with the nightly build or did i had an old version of SQLite?

**Comment by chrisjlocke** [comment]
3.12.2 is the main release, so you were using the right version.  The nightly is just more up to date and has this particular 'fix' in it.

**Comment by mgrojo** [comment]
I hope this is now clarified and working, so I'll close the issue, since the feature will be included in the future (long delayed) release. Just open it again if something has been left pending.
