### ISSUE TITLE
[Bug-SQBPRO]: DB4S crash on attempt to open SQBPRO and deletes SQL on exit.

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#3007]
### What did you do?

Attempt to open a sqbpro with populated SQL tabs and/or a last known database file that is missing. If database exists, the clearing of SQL tabs still happens.

### What did you expect to see?

DB4S prompts user to browse for a database.

### What did you see instead?

Upon cancelling file open dialog, DB4S crashes.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 Pro

### Relevant log output

```shell
Crash does not allow log viewing.
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by sky5walk** [comment]
I am still crashing on project loads with nightly v220326.
I am forced to cut and paste precious SQL queries stored within sqbpro files.
Is there any way to import sqbpro files without crashing?

**Comment by chrisjlocke** [comment]
> and a last known database file that is missing

Put the database back? 😁😂

**Comment by sky5walk** [comment]
Tried with latest nightly and verified the db exists.
On opening a sqbpro file directly, DB4S appears and then crashes with no dialogs. :(
SQBPRO is super inefficient now since I have to cut and paste stored sql's into new versions of themselves. Aaaaarrrrrrggggg.

**Comment by sky5walk** [comment]
Is there a document describing the format of sqbpro files?
Why is the xml content storing sql inequalities as url or html ready?
`WHERE (Gd &gt;= -1.6 AND Gd &lt;= 0.5));`
Instead of:
`WHERE (Gd >= -1.6 AND Gd <= 0.5));`

**Comment by FriedrichFroebel** [comment]
> Why is the xml content storing sql inequalities as url or html ready?

Because this is what the XML standard requires ([section 2.4](https://www.w3.org/TR/xml/#syntax)):

> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings `" &amp; "` and `" &lt; "` respectively. The right angle bracket (>) may be represented using the string `" &gt; "`, and MUST, for compatibility, be escaped using either `" &gt; "` or a character reference when it appears in the string `" ]]> "` in content, when that string is not marking the end of a CDATA section.

**Comment by sky5walk** [comment]
Double arrrggggg! That is why I suggested using json for the sqbpro files.
Or just use a sqlite db. 💭 
xml is garbage in this application.
I am a bit testy, since even cut and pasting is now a fail given the additional step of backing out the xml alterations of sql queries.

Can you also answer what/where the format of sqbpro format is defined?
I will write a utility to convert my queries to whatever will work.
But given I cannot get older versions of DB4S to read newer versions of sqbpro files, I'd like to know what is wrong.

**Comment by FriedrichFroebel** [comment]
Project loading and saving happens in https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L2504-L3182. There is no corresponding schema definition as far as I know.

**Comment by sky5walk** [comment]
[Don't you mean here?](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L2850)

[Where is openSqlTab() located?](https://github.com/sqlitebrowser/sqlitebrowser/blob/a14e6eb607f96d71c6aeb12e94f109ca7073d4c3/src/MainWindow.cpp#L2861)

**Comment by FriedrichFroebel** [comment]
The line you marked is just the initial condition to start loading the SQL tab data. As far as I understand the code, you do not have to use `openSqlTab()` at all - this is just some GUI stuff; nevertheless, you can find the corresponding implementation in https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L2095-L2121 (<kbd>Ctrl + F</kbd> is your friend).

If I am not mistaken, the corresponding XML will look like this, although you should be able to see this by having a simple look at your project file without your favourite plaintext editor as well:

```xml
<tab_sql> <!-- SQL tab container -->
    <sql name="Tab name">  <!-- Direct SQL tab -->
        SELECT * FROM my_table;
    </sql>
    <sql name="Another tab name" filename="queries.sql">  <!-- File-based SQL tab -->
        -- Reference to file &quot;queries.sql&quot; (not supported by this version) --
    </sql>
    <current_tab id="1" /> <!-- Index of currently selected tab -->
</tab_sql>
```

**Comment by sky5walk** [comment]
Yes yes, of course I have looked at sqbpro files in ascii text, which is why I asked for its design?
You are only showing the SQL tab portion in your paste.
I am trying to compare a working sqbpro file with a crasher.

**Comment by FriedrichFroebel** [comment]
It seems like there has been some misunderstanding here. I assumed that you were only interested in extracting the SQL tab stuff for your own needs, as the project files have been crashing without a solution in sight. While I am a DB4S contributor, I am not familiar with the project file code and have never actually used this feature - I just did a quick look into the code as it appeared like you were having trouble with it.

**Comment by sky5walk** [comment]
I was already reading xml files in a text editor to pull out my SQL contents, but still needing to edit the xml special character swaps. This is not ideal.

I asked for the sqbpro format so I could modify my supposedly broken files and use them straight away in DB4S.

**Comment by justinclift** [comment]
Sounds like we need someone to attach a debugger and work out where the crash is happening.

@MKleusberg Any interest? :smile:

**Comment by sky5walk** [comment]
Ok, my simple minded workaround is to make a new sqbpro file with the latest nightly and copy its header(up to <tab_sql>) to the older sqbpro files that crash.
I cannot make sense of the header diff's without a sqbpro schema. So, full copy pasta strikes again!

**Comment by sky5walk** [comment]
Ok, I found a glaring diff with a crashing sqbpro file:
schema="main" appears 3 times in the file. 😱 
There are still many other small diff's I cannot resolve.
Continuing to paste a fresh sqbpro header in front of corrupted sections before my <sql> stuff.

**Comment by chrisjlocke** [comment]
Do you have a project file that is OK vs a project file that crashes?  I can use winDiff to look at the differences.
From your initial post, this only occurs if the database is missing, yes?

**Comment by sky5walk** [comment]
Yes, I was using WinMerge to see the differences.
That's how I noticed the schema="main"...

**Comment by chrisjlocke** [comment]
Is the schema='main' part of the XML, or part of your queries?
It's not in my XML, but I've only created a database then saved the project, so it's as minimalistic as you can get.

![image](https://user-images.githubusercontent.com/7872218/177012126-9abb5a64-f223-4af7-a9d7-64193fef5a3c.png)

**Comment by chrisjlocke** [comment]
Aah, its OK.  I had to fiddle with it.

![image](https://user-images.githubusercontent.com/7872218/177012275-4d751ba3-9cf0-46f6-8f48-9baf83c41fd9.png)

Why is having a schema bad for you?

**Comment by sky5walk** [comment]
No, the sqbpro files have individual xml sections including:
<tab_sql>...
<table schema="main" ...

**Comment by sky5walk** [comment]
It is not bad for me, I am just guessing what might create the corrupt sqbpro file?

**Comment by chrisjlocke** [comment]
The tab sql don't have a schema do they .... they don't on mine.  Just a 'name' and 'text' entries.

![image](https://user-images.githubusercontent.com/7872218/177012508-8a10a5fa-3e10-406a-898a-0cf710cb7e1d.png)

**Comment by chrisjlocke** [comment]
Ergh.

When you say 'DB4S crashes' does it crash to the desktop, or just spin in a 'not responding' way?

![image](https://user-images.githubusercontent.com/7872218/177012564-a6da177d-f058-4a46-9877-628256b4ca56.png)

**Comment by sky5walk** [comment]
Trying to make an sqbpro now...
The crash is just DB4S thinking, then quit. The DB4S window is open but empty contents.

**Comment by sky5walk** [comment]
Ok, I stumbled onto some heinous errors trying to make smallish example sqbpro and db's.

**Comment by sky5walk** [comment]
Rename the files and place in a folder: 
  BAD-sqbpro-db.csv --> BAD-sqbpro.db
  OPENS-BUT-DELETES-SQL-ON-EXIT-PROMPT-sqbpro.csv --> OPENS-BUT-DELETES-SQL-ON-EXIT-PROMPT.sqbpro
DOES-NOT-OPEN-sqbpro.csv --> DOES-NOT-OPEN.sqbpro

Confirm the sqbpro files do not work.
1. Double click on each sqbpro file.
2. Goto EXECUTE SQL tab.
3. Try to exit DB4S.
4. Notice all SQL tabs are cleared.
5. Hit discard changes to preserve SQL content.
6. Or Save Project.

[BAD-sqbpro-db.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/9033653/BAD-sqbpro-db.csv)
[OPENS-BUT-DELETES-SQL-ON-EXIT-PROMPT-sqbpro.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/9033656/OPENS-BUT-DELETES-SQL-ON-EXIT-PROMPT-sqbpro.csv)
[DOES-NOT-OPEN-sqbpro.csv](https://github.com/sqlitebrowser/sqlitebrowser/files/9033659/DOES-NOT-OPEN-sqbpro.csv)

**Comment by sky5walk** [comment]
Just downloaded latest nightly and same errors even on a working sqbpro file.
1. Run a query.
2. Hit exit
3. Prompt to save project but all SQL tabs are CLEARED!
4. Must discard changes to avoid losing stored SQL queries.

**Comment by chrisjlocke** [comment]
Think I had similar when I played with project files testing out your main issue above - just loading a normal project file died.
I haven't seen if it's related to newer nightlies - previous versions might work better.

**Comment by sky5walk** [comment]
This behavior has followed me through many months of nightlies.
I must reconsider the utility of sqbpro files. Whenever I upgrade a nightly, the sqbpro files become faulty and trigger crashes or lost SQL tab content.

**Comment by mgrojo** [comment]
@sky5walk I think I've fixed the crash and the SQL loss. Unfortunately, I could not reproduce exactly your steps with the attached files, because both DB files give an error and I think at least one of them shouldn't:
```
Could not open database file.
Reason: malformed database schema (T1) - near "STRICT": syntax error
```
Could you confirm the solution with tomorrow's nightly build?

**Comment by chrisjlocke** [comment]
Well, it won't be _tomorrow's_ nightly, as they're currently broken, but when they're live again... ;)
Just keep an eye out at https://nightlies.sqlitebrowser.org/latest/

**Comment by sky5walk** [comment]
Yahooo!
I will keep a lookout.
Thanks

**Comment by sky5walk** [comment]
No new nightlies 😢

**Comment by chrisjlocke** [comment]
That's due to a build error.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3105

Once that issue gets resolved, the nightlies will appear.

**Comment by sky5walk** [comment]
Thanks mgrojo!
The errors in the test sqbpro do not cause abort of DB4S now.
I will close this issue but since I am not sure what caused the erroneous sqbpro files, it may be reopened.
