### ISSUE TITLE
3.6 Win-64

### ISSUE THREAD

**Issue by Teeeeemo** [sqlitebrowser/sqlitebrowser#301]
Hello, I had just fresh install sqlite 3.6 64 bit edition and I got 0xc00007b problem. indicates that a 32-bit application is trying to load a 64-bit dll. maybe it's my windows? i'm not thinking so...

oh, sqlite browser is built by Qt!

**Comment by justinclift** [comment]
Hmmm, that doesn't sound good.

Which OS are you using?

**Comment by Teeeeemo** [comment]
windows 7 home premium 64 bit (updated

----- Reply message -----

**Comment by justinclift** [comment]
Cool, that's known to work.  As a first thought, when you grabbed the [Microsoft Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784), did you grab both 32 and 64 bit or just one?

I'm kind of thinking if you don't have both installed, it's probably worth installing whichever one is missing, just to see if that solves it.

Is that workable?

**Comment by Teeeeemo** [comment]
Good to know that it is known to work.
thank you for replying, @justinclift . I had just known that SQLite 3.6 requires Microsoft Visual C++ Redistributable Packages for Visual Studio 2013. I actually have the 2005, 2008, 2010, 2012, and 2013 for both x86 and x64 architecture.

Oh, okay, my bad that I did not notice the note.

**Comment by justinclift** [comment]
Hmmm, so you already have it installed, and it's still not working?

Ok, lets try a different approach.  Would you be ok to try our latest nightly build (location on the front page), and see if that works?

It uses a different (older) build process that I'm thinking will probably work for you right away.  It's worth a shot. :smile:

**Comment by Teeeeemo** [comment]
No, Installing Visual C++ 2013 Redist (x86 / x64) does not fix the problem.
but,
installing Visual C++ 2013 Redist (in my case is x64 (I take 64-bit version)) [b]FOR VISUAL STUDIO 2013[/b] fixes the problem

**Comment by justinclift** [comment]
Ahhh, all good then. :smile:

**Comment by Teeeeemo** [comment]
@justinclift Hello again..

weird, why do I need to reinstall (repair) my Visual C++ 2013 Redist for Visual Studio 2013 every time I reinstalled (in my case, I updated) SQLite Browser.. does the installer replace any file?

**Comment by justinclift** [comment]
Oh, that's strange.  In theory that shouldn't be needed... but theory obviously isn't working as expected here.  Personally, I have no idea how to diagnose this in more depth... @schdub, any ideas?
