### ISSUE TITLE
[Bug]: Import csv which may contain sql reports an error

### ISSUE THREAD

**Issue by AndiLeni** [sqlitebrowser/sqlitebrowser#3017]
### What did you do?

I tried to import a csv file which contains sql queries (probably from malicious web-request).

### What did you expect to see?

The csv content should be imported without issues.

### What did you see instead?

The import failed with this message:
![grafik](https://user-images.githubusercontent.com/13385771/163672037-9ecb2f90-17ed-4421-ab44-9347559e832c.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
The error is 'error importing data from row number 227584'.
It probably breaks the CSV rules, eg, too many or not enough columns of data.  A CSV file has to be consistent - the data has to be cleansed before you can import it.  Otherwise, if you're trying to import five fields, and DB4S only sees four, what is it to do - assume its field five that is empty?  It might now be putting a null value in a column thats not meant to be null.

Obviously you've not provided any information whatsoever, so I have no idea what you're doing - how many fields with what options, into what table.  But ensure the CSV is valid before importing.

**Comment by AndiLeni** [comment]
I am importing five columns which are separated by `|` in my csv file.

The problematic line is this one: 
````
2022-04-02|00:18|45.155.205.244|/handball-mannschaften/m%C3%A4nnl-d-jugend/138-turnen/angebote/index.php?option=com_content&view=article&id=198%3Aansprechpartner-bereiche&catid=181%3Aabteilungsleitung&Itemid=577|Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.517 Safari/537.36%';SELECT COUNT(*) FROM GENERATE_SERIES(1,32000000)--
````

The IP has attacked my server with many sql injection queries, as seen in my example in the user agent.
Nonehtless, if I separate the string by `|` there are again five columns which is correct.

The tabel I import into is not existent. So it should be created when I start the import.

**Comment by chrisjlocke** [comment]
I assume your quote character was a double quote, and field seperator was a pipe?

![image](https://user-images.githubusercontent.com/7872218/163677400-f06f9b1a-8113-4bc8-b7b5-677ee79479ba.png)

Admittedly, while DB4S is moaning about line 227584, the error that caused this might be earlier - you might have to check around that.  Has DB4S imported anything, or did it abort the import?  If you can split the file up, you can find the line that's causing the problem.
And this would be a PSV, not CSV... a CSV is a comma seperated file, while this is a pipe seperated file... ;) 

The issue could be if the URL/SQL he submitted contains a pipe symbol.  If so, you'd need to ensure this is quoted.

**Comment by AndiLeni** [comment]
Thanks for the answer. There are indeed lines which contain more columns because of the attempted sql injection.
Unfortunately, the 'ignore row' option does nothing in this case, the import gets aborted no matter which option I try.
Is there another option I could try, or should I go with sanitizing before importing to get rid of the columns?

**Comment by chrisjlocke** [comment]
If you don't sanitize, DB4S can't 'assume' the data is all one field.
If you have A|B|C|D and you read that into three columns, it can't assume C|D should be squeezed into column C - at worst, it will read C, dicarding |D.  This will give inaccurate data.  You have to sanitize it to A|B|"C|D" so it knows C|D is one field.

If you want, I can write a CSV (well, PSV) cleaner that can take x columns, and assume column Y and Z should be merged.
eg, in the above example, if it finds four columns, merge columns three and four.  If it finds five columns, three, four and five should be merged, etc.

**Comment by AndiLeni** [comment]
Thanks for your offer, but I can do this myself :-)

Maybe an import option like 'drop data if line does not fit in columns' might be included in sqlitebrowser?

**Comment by chrisjlocke** [comment]
I'd suggest looking at the nightly builds of DB4S.
https://nightlies.sqlitebrowser.org/latest/

Download the .zip, extract it, and run the .exe directly - it doesn't need installing and it won't affect the currently installed version installed.

I've a sneaky feeling the CSV import was slightly tweaked or improved.  Can't say for definite - I've lost track of when issues were raised, the nightlies tweaked to assist, and when the release version was released.  I could look through commit histories and stuff  but ... well.... forgive me but I won't.  ;)
