### ISSUE TITLE
[Bug]: Error parsing table schema "unexpected NULL, expecting DEFERRABLE"

### ISSUE THREAD

**Issue by alcroito** [sqlitebrowser/sqlitebrowser#3018]
### What did you do?

Tried opening a database file, with the following table schemas:

```
CREATE TABLE domains (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE domain_ip_fetches (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    domain_id INTEGER REFERENCES domains(id) NOT NULL
);
```

But sqlitebrowser can't parse the NOT NULL after the foreign key clause.

Looking at 

https://www.sqlite.org/syntax/column-def.html
https://www.sqlite.org/syntax/column-constraint.html

it should be possibly to specify multiple constraints, both a `NOT NULL` and `REFERENCES` foreign key clause.

Also if you check https://www.sqlite.org/foreignkeys.html there is this:

> Tip: If the application requires a stricter relationship between artist and track, where NULL values are not permitted in the trackartist column, simply add the appropriate "NOT NULL" constraint to the schema.

which seems to suggest it should be possible.

In an older version of sqlitebrowser, my table schemas were parsed successfully.

### What did you expect to see?

Ability to view / edit the table schema.

### What did you see instead?

Error parsing the table.
```
3.50-53: syntax error, unexpected NULL, expecting DEFERRABLE
Sqlite parse error: CREATE TABLE domain_ip_fetches (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    domain_id INTEGER REFERENCES domains(id) NOT NULL
)
```

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by alcroito** [comment]
Flipping the order of `NOT NULL` and `REFERENCES` seems to help.
Although i'd expect both orders to work.

**Comment by chrisjlocke** [comment]
> although I'd expect both orders to work

It's important to know the options aren't like flags on a DIR command, where it doesn't matter if you say DIR /s /p or DIR /p /s.  When you specify the ID field, you type 'Integer primary key' and this order is important - it doesn't like 'primary key integer'.  
I know we parse SQL statements, but on this occassion it looks like the error is coming from SQLite itself, so we're just throwing it the SQL statement, and it itself if moaning about the parameters, not DB4S.

As this isn't an error in DB4S and you have a workaround, I'll close this issue.

**Comment by alcroito** [comment]
> on this occassion it looks like the error is coming from SQLite itself and it itself if moaning about the parameters

I'm not sure why you say that, because it's not the case.

Running the two create tables statements directly via the Execute SQL pane works just fine, and returns no error, so it's valid syntax.

>  it doesn't like 'primary key integer'.

Yes, that's correct, because `PRIMARY KEY INTEGER` does not fit the grammar requirement of having the field type name before any constraints, as per https://www.sqlite.org/syntax/column-def.html.

Whereas `domain_id INTEGER REFERENCES domains(id) NOT NULL` is valid syntax according to the grammar.

`INTEGER` is a `type-name` token 

and 

`REFERENCES domains(id)`
 `NOT NULL` 

are 2 separate `column-constraint`s as per https://www.sqlite.org/syntax/column-def.html and https://www.sqlite.org/syntax/column-constraint.html

So, as i've said before, I think the syntax should be parsed as valid, because the order of `column-constraint`s should not matter.

**Comment by chrisjlocke** [comment]
>  I think the syntax should be parsed as valid

And you indeed are correct!  Looks like it has been corrected.

If you want to check the nightly version (https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite.dmg) it may be corrected.
Just checked 3.12.2 and it couldn't parse the table, as you highlighted.

![image](https://user-images.githubusercontent.com/7872218/163723571-5ee37437-bdeb-4ec4-bdea-7316a8b9fd3c.png)

I don't get an error, but I don't get a schema either.

However, in the nightly, it works OK.

![image](https://user-images.githubusercontent.com/7872218/163723590-9b4b23b5-f3f2-424a-9685-99a8612b8a5a.png)

Let us know if it improves things for you. :)

**Comment by alcroito** [comment]
Ah, such unfortunate timing to create the report. I can confirm that the nightly successfully parses the schema.
Thanks for spending time on this report and have a great day!

**Comment by chrisjlocke** [comment]
No problem!  Thanks for raising it in the first place!  Glad it's sorted for you. :)
