### ISSUE TITLE
Windows x64: SQL Execute squiggly red line

### ISSUE THREAD

**Issue by FASposito** [sqlitebrowser/sqlitebrowser#302]
Is it possible to add a feature to turn off the squiggly red line that indicates bad SQL in the SQL executer? It's very distracting and quite annoying. Thanks!

**Comment by justinclift** [comment]
Hmmm, just to ask... which version are you getting the squiggly line on?

It might be possible to add a preference for syntax checking or something, depending on the version. :smile:

**Comment by FASposito** [comment]
Justin, Thanks for the quick reply. I'm using the new version 3.6. It seems
like it's part of the syntax color scheme, but unlike the other colors
there's no way to change it or turn it off. Even a lighter gray might work
if it weren't squiggly.

Thanks again. It's really a great app!

**Comment by justinclift** [comment]
Yeah, the "Execute SQL" tab is using a new widget thing in this release, so it'll likely need a bit of fine tuning based upon people's suggestion (like you're doing), to get it suiting everyone well.

Thanks. :smile:

**Comment by FASposito** [comment]
Since I've got you on the line, may I put in another request? I use sqlite
browser every day and have a pretty good sense for my workflow with it. Its
design principals are better than any other similar app out there. I
especially love the simplicity of the filtering system in the browse data
tab. One issue I've had though is that whenever you move off the browse tab
you loose your filters. This becomes a serious problem when you're testing
sql on very large tables and have to go back and forth between execute and
browse tabs to see the results. Every time you toggle, you have to reenter
your filters, which can be a pain when you're filtering on multiple fields,
which is pretty much always the case for me. This flipping back and forth
is core to my work flow. The workaround I use is opening several instances
of sqlite browser at once. The filters don't vanish when you toggle off the
application as a whole, only when you move from one tab to another. So for
me one instance of sqlite browser is always on the browse tab, the other on
the execute tab. This works, but sometimes it's hard to keep track of
what's where. It would be great if filters were preserved so I could work
out of the same instance. And it would be even greater if there were
multiple browse tabs like there are multiple sql execute tabs. It's not
uncommon for me to have five or six instances of sqlite browser open at
once so that I can see the results of complex sql tests (like triggers) on
each of the tables affected. This is real work flow for me, how I actually
use the app.

Anyone, just one fan's opinion. I feel like an art critic who's telling a
highly successful artist what he should paint and which colors to use...
Anyway, thanks for your help and keep up the great work!

**Comment by justinclift** [comment]
Ahhh, that suggestion makes a lot of sense and is probably pretty easy to implement.

Would you be ok to make a new Issue out of it, so we can track it separately to this?

**Comment by FASposito** [comment]
No problem, just added it to the issues queue. Thanks!

**Comment by MKleusberg** [comment]
@FASposito I've just added a new option to the Preferences Dialog which allows you to disable the red line altogether :smiley: If you want to try it out, you'll have to wait for the next nightly build tomorrow and download it here: https://github.com/sqlitebrowser/sqlitebrowser#windows Then you should get this new option at the bottom:
![errorindicators](https://cloud.githubusercontent.com/assets/3153504/8280281/2d9352c0-18dc-11e5-898a-802a4a90ffd8.png)

**Comment by justinclift** [comment]
Cool. :grinning:

**Comment by MKleusberg** [comment]
Can we close this issue? The new option in the settings dialog should do the trick, and the bit about the filters not remembering their state is fixed too :smile:

**Comment by justinclift** [comment]
Sure. :smile:
