### ISSUE TITLE
[Bug]: .env file not working on macOS

### ISSUE THREAD

**Issue by NoirChad** [sqlitebrowser/sqlitebrowser#3023]
### What did you do?

Hi,

To start, I just want to say thanks so much for your awesome works! 

I'm trying to bypass password prompt for a sqlcipher3 encrypted .db file. 

My current .env file looks like this:

msg0.db = 0x5e9232a51d0c4c24998358d255739e98e5d7fa650b3d463083f968d5dae931ba
msg0.db_KeyFormat = 1  
msg0.db_pageSize = 1024  
msg0.db_kdfIter = 64000  
msg0.db_hmacAlgorithm = SHA1  
msg0.db_kdfAlgorithm = SHA1  
msg0.db_plaintextHeaderSize = 0  

I also downloaded the nightly version.
[DB.Browser.for.SQLite-sqlcipher.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg)

### What did you expect to see?

I expect that, when I open msg0.db, it should bypass the password prompt.

### What did you see instead?

The password prompt still popped, and when I choose "RAW KEY", "SQLCipher3 defaults", and enter the raw key, I can open the file.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

MacOS

### OS version

MacOS 12.0.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
I don't know, but just check _KeyFormat - in the pull request, it's set as _keyFormat (lowercase k).  I don't know if it's case sensitive.

**Comment by NoirChad** [comment]
Thanks so much!

I should be more cautious when writing it.
It works.

**Comment by chrisjlocke** [comment]
So it was case sensitive?  That's interesting to know.  Thanks for confirming and reporting back. 👍
