### ISSUE TITLE
QT_DEVICE_PIXEL_RATIO is deprecated

### ISSUE THREAD

**Issue by Nik8bit** [sqlitebrowser/sqlitebrowser#3025]
Details for the issue
--------------------
Showing a warning "QT_DEVICE_PIXEL_RATIO is deprecated" on each startup.
Seen this Warning in previous Releases also.
<a href="https://ibb.co/84tFFZJ"><img src="https://i.ibb.co/84tFFZJ/Screenshot-2022-04-24-165353.png" alt="Screenshot-2022-04-24-165353" border="0"></a>

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22000) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Interesting.  I use 3.12.2 on Windows 10 and have never seen that popup.  Is this running DB4S from our builds, or one that you've built yourself from our source?  Assuming the former, is that simply double-clicking the .exe from Explorer?
Not that it matters as both are the same files, but did you run the installer, or extract from the zip?  

Can you try the nightly?
https://nightlies.sqlitebrowser.org/latest/

Simply download the .zip, extract, and run the .exe - you don't need to install it and it can co-exist with the currently installed 3.12.2 version.
I've not seen that popup before, and in the past when DB4S writes to a debug window, I've not managed to get it to display it.

**Comment by chrisjlocke** [comment]
Ooh, I didn't search.  This issue is interesting.
https://github.com/sqlitebrowser/sqlitebrowser/issues/2643

In a CMD window, can you type 'set' and press Enter.  Do you have an environment variable set for QT_DEVICE_PIXEL_RATIO?

**Comment by chrisjlocke** [comment]
@Nik8bit - Have you managed to have a look to see if 
* you have the environment variable
* removing the environment variable helps

**Comment by MKleusberg** [comment]
Closing this since @chrisjlocke suggested a fix and we didn't hear anything for a while. Feel free to reopen this any time if there's still a problem with this.
