### ISSUE TITLE
[Bug]: DB Browser is ignoring the sqlite_sequence

### ISSUE THREAD

**Issue by bwminick** [sqlitebrowser/sqlitebrowser#3026]
It appears that DB Browser is ignoring the sqlite_sequence for a table when creating new records.

Here's how to replicate it:

- Create a new database.
- Create a new **Employees** table with the following fields:

     * id (primary key, autoincrement, unique not null)
     * firstName (text)
     * lastName (text)

<img width="652" alt="createTable" src="https://user-images.githubusercontent.com/77753152/164993342-972c4526-ac6a-4b7c-8075-627f74560809.png">

- Go to the new sqlite_sequence table.
- Add a new row with the values: **Employees** (for the name field) and **1000** (for the seq field).
- Write Changes
- Go to the Employees table
- Add a new row (via the "**Insert a new record in the current table**" toolbar button with values of your choosing.
- Notice that the ID value is **1**, instead of **1001**.
- Now, add a second row (this time via sql commands) instead.

<img width="1512" alt="sql_command" src="https://user-images.githubusercontent.com/77753152/164993502-0499d797-a769-4e23-837d-24649a97e8db.png">
 
You'll notice that the executed sql is following the sqlite_sequence table.

<img width="1575" alt="result" src="https://user-images.githubusercontent.com/77753152/164993549-5154f894-3a21-4592-bc0d-47fb4b9f8910.png">

Expected Results:
The first record's ID should be 1001.  The second record's ID should be 1002.  However, the "Insert a new record in the current table" toolbar button is ignoring the sqlite_sequence table.

**Comment by chrisjlocke** [comment]
Its the 'NN' option which is causing DB4S to choose a number for you.
In the application log it shows

```
SELECT "_rowid_",* FROM "main"."a" LIMIT 0, 49999;
SELECT MAX(CAST("Field1" AS INTEGER)) FROM "main"."a"
INSERT INTO "main"."a"("Field1","Field2","Field3") VALUES (10001,NULL,NULL);
```

If you remove the NN option, it'll work as you expect.

**Comment by MKleusberg** [comment]
@bwminick Did the nightly build work for you?

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
