### ISSUE TITLE
[Bug]: The character `\` is not encapsulated when exporting to SQL

### ISSUE THREAD

**Issue by Ponywka** [sqlitebrowser/sqlitebrowser#3027]
### What did you do?

`File` > `Export` > `Database to SQL file...`

### What did you expect to see?

In the exported file:
```sql
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "test" (
	"test"	TEXT
);
INSERT INTO "test" VALUES ('\\');
COMMIT;
```
After this I have inserted line with "\\" field

### What did you see instead?

In the exported file:
```sql
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "test" (
	"test"	TEXT
);
INSERT INTO "test" VALUES ('\');
COMMIT;
```
After this I have syntax error while importing this file.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 21H2 (19044.1645)

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
I've not known the \ character to be escaped before.  Doesn't occur for me.

![image](https://user-images.githubusercontent.com/7872218/165151419-a28c67ed-1195-42fb-b0a1-317da5e47f93.png)

![image](https://user-images.githubusercontent.com/7872218/165151462-f34808f5-7033-4493-8089-6c8b02e359ae.png)

And if I insert two \ characters, they are inserted without issue.

![image](https://user-images.githubusercontent.com/7872218/165151573-ebb484a2-01da-4b46-bb59-5f9477944077.png)

![image](https://user-images.githubusercontent.com/7872218/165151606-6824e1a8-3420-4aa0-8e5e-fd12182db8ac.png)

**Comment by Ponywka** [comment]
But... Other SQL servers (for example MySQL) fall into an error when importing such files.
I didn't think export (from import SQLite) could work exclusively on SQLite.

![image](https://user-images.githubusercontent.com/26777464/165158023-47536a29-14bf-434d-afbe-e665780f0cae.png)

**Comment by Ponywka** [comment]
Okay, this is not a bug, but a difference in syntax. Sorry to disturb you.

**Comment by chrisjlocke** [comment]
> I didn't think export (from import SQLite) could work exclusively on SQLite.

DB4S only really likes SQLite syntax of SQL.  It can't import MySQL exported SQL files, nor export to files compatible with MySQL.  You can tweak the separators when exporting to CSV, but datatypes between MySQL and SQLite are completely different and no effort is made to take this into account when importing or exporting.
