### ISSUE TITLE
Loading... in each table column instead of values

### ISSUE THREAD

**Issue by Setitch** [sqlitebrowser/sqlitebrowser#3029]
Details for the issue
--------------------

#### What did you do?

I created table with Foreign Key
Then i created two rows -using Browse Data tab- (one in main table, and another connected in the other table)

#### What did you expect to see?

In the table with foreign key i see all fields with ping/magenta background and string 'loading...' instead of values.

#### What did you see instead?

The values i inserted into the table

#### Some debug information
When i selected the rows from the table using direct SQL - it worked. The problem occurs only in Browser Data tab 

Then i checked SQL log, and this is what i found there: SELECT COUNT(*) FROM "main"."relation--users--events";
Correct one (returning data) is:  SELECT COUNT(*) FROM 'main'.'relation--users--events';

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
The double-quotes and single-quotes should have no impact - SQLite likes both, but technically, single-quotes is for string literals.  Did you copy that verbatim from the SQL log?
Just tried and created a table called "a a".  SQLite does know that "a a" is a table if I use 'a a' instead.

```
insert into 'a a' (field1)
values (3)
-- Result: query executed successfully. Took 0ms, 1 rows affected
-- EXECUTING SELECTION IN 'SQL 1'
--
-- At line 7:
insert into "a a" (field1)
values (3)
-- Result: query executed successfully. Took 0ms, 1 rows affected
```

It might be worth trying the nightly.  
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

I've a faint feeling this area was looked at after 3.12.2 was released.

You can download that zip, extract it and simply run the .exe - you dn't have to install anything, so it won't break your currently installed 3.12.2 version.

**Comment by Setitch** [comment]
I concur - nighty version works!

**Comment by chrisjlocke** [comment]
Excellent, thanks for reporting back.  Hopefully this will feed down into the next release. We may need to call you back to confirm! :)

**Comment by Setitch** [comment]
I now encountered similar problem but with table name containing -- (two consecutive dashes) 

```
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
SELECT "_rowid_",* FROM "main"."relation LIMIT 0, 49999;
SELECT COUNT(*) FROM "main"."relation--users--events"
```
