### ISSUE TITLE
bug: select returning wrong row

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#303]
Hello.

I've found one instance sqlitebroser returns one wrong row on 3.5.1 and 3.6.0. SqliteAdmin-0.8.3.2 works fine and so does every other software I tested. Unfortunately I'm working under NDA so I can't publish the query or the database but I can send them privately on request.

**Comment by justinclift** [comment]
Sure.  Please email the details to justin@postgresql.org.  I'll forward them to the main developers, and we'll keep the query + database details in confidence (but fix the bug). :smile:

**Comment by palmiche** [comment]
I suppose I shouldn't be surpised by your response speed any more. :grin: 
Thanks @justinclift

**Comment by justinclift** [comment]
You're welcome, just forwarded it on. (and going to bed, so response speed won't be great now :wink:)

**Comment by schdub** [comment]
@palmiche, you press 'Yes' in the 'Collation needed! Proceed?' message box while loading database?
Please try to click 'No' and test again, your query working for me in this case.

It seems that we only have collation implementation (sqlitedb.cpp, collCompare()) for char strings (8-bit) and if used our collation function for compare wide strings (16 bit) it compares only one character.

**Comment by palmiche** [comment]
It works. Never crossed mi mind to choose 'No' when asked 'Proceed?'. :grin: That dialog is kind of misleading. Maybe handle it as a separate issue?

Anyways, thanks @schdub.

**Comment by justinclift** [comment]
@palmiche Yep, are you ok to create another issue for it?

It sounds like we should change the description for this issue to something like "NOCASE collation does not handle multi-byte characters".  @schdub Is that a more accurate title?

**Comment by palmiche** [comment]
Issue #308 

I think that's about it for this issue. Multibyte nocase collation will come in due time so creating another issue for it won't help. Right?

**Comment by justinclift** [comment]
Ahhh, gotcha, closing then then. :smile:
