### ISSUE TITLE
convert language from arabic to english  in DB  browser

### ISSUE THREAD

**Issue by rdrd464** [sqlitebrowser/sqlitebrowser#3033]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Do you mean DB4S is currently showing Arabic, and you need to revert it back to English?

**Comment by justinclift** [comment]
@rdrd464 Ping?

**Comment by rdrd464** [comment]
thank you

**Comment by rdrd464** [comment]
@chrisjlocke thanks

**Comment by justinclift** [comment]
Cool.  Does that means it's all working ok for you now @rdrd464, and we're ok to close this? :smile:
