### ISSUE TITLE
Contact email for project owners for enterprise usage

### ISSUE THREAD

**Issue by ColinCohan** [sqlitebrowser/sqlitebrowser#3036]
Is there a contact email that I can use to reach out about Enterprise usage of this project? My company specifically needs an email address to proceed with the process.

Thank you!

**Comment by justinclift** [comment]
@ColinCohan I guess it really depends on what's needed for your enterprise. :smile:

You're welcome to email me directly (justin@postgresql.org), and we can figure it out from there.

**Comment by MKleusberg** [comment]
Could you two sort this out? :smile: Asking because if so we can close the issue.

**Comment by ColinCohan** [comment]
You can close the issue, thanks. 

- Colin

**Comment by justinclift** [comment]
@ColinCohan Should I expect to hear from yourselves, as I've not received any kind of contact yet?

**Comment by ColinCohan** [comment]
Hi Justin, I haven't needed to apply for enterprise use yet after all, I
just needed a contact email to list in the documentation/paperwork if we
decide we do want to use sqlitebrowser. Thank you!
