### ISSUE TITLE
Translations are not being installed via make install

### ISSUE THREAD

**Issue by gasinvein** [sqlitebrowser/sqlitebrowser#304]
No .qm files are installed anywhere with make install command.
Also, seems like the program searches for "translations" directory only in directory with the executable, e.g. in /usr/bin.
Sorry for my english.

**Comment by justinclift** [comment]
Ahhh. Which operating system is this happening on?

**Comment by gasinvein** [comment]
Ubuntu linux.

**Comment by justinclift** [comment]
Thanks @gasinvein. :smile:

@deepsidhu1313 Are you to look into this?

**Comment by deepsidhu1313** [comment]
@justinclift  I am preoccupied with other projects and helping my Juniors with their thesis, no promises but i can "try" to look into this by creating a window in my very tight schedule (my apologies).

:smiley:

**Comment by justinclift** [comment]
Its ok, whenever you have time. :smile:

**Comment by justinclift** [comment]
@gasinvein schdub has added a fix for this.  Would you be ok to try out our latest code and report back if it works for you as needed? :smile:

**Comment by gasinvein** [comment]
Yep, now language is selectable and works fine. Many thanks.

**Comment by justinclift** [comment]
Awesome @gasinvein, thanks for letting us know. :smile:

**Comment by deepsidhu1313** [comment]
Thanks  @schdub  @justinclift , I will package the changes on testing ppa asap. :smile:  :smiley:
