### ISSUE TITLE
[Bug]: How to execute in windows command line? I can only find exe, no bat file, etc. steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [sqlitebrowser/sqlitebrowser#3040]
### What did you do?

[Bug]: How to execute in windows command line? I can only find exe, no bat file, etc. steve8000818@gmail.com

### What did you expect to see?

execute a command in cmd window to export to json

### What did you see instead?

no such command

### DB4S Version

3.12.0

### What OS are you seeing the problem on?

Windows

### OS version

win10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by longnguyen2004** [comment]
Please use the `sqlite3` command line tool instead, this is not for automation.

**Comment by justinclift** [comment]
@nissansz You'll need to grab the "Precompiled Binaries for Windows" from here:

&nbsp; &nbsp; https://sqlite.org/download.html

It should be the third one under that heading on the page (with a name like `sqlite-tools-win32-x86-<something>.zip`.  That includes the command line tool.

Does that help? :smile:

**Comment by justinclift** [comment]
> this is not for automation.

Just to point out, which you're 95% correct... there is *some* support for command line usage in our application.  But only for specific things, at least at this point. :smile:

**Comment by nissansz** [comment]
Ok. I found another python code to extract content. thank you.
