### ISSUE TITLE
[Bug]:  Font Problem (Browsing Table Data) on macos (Mac Studio, M1 Chip)

### ISSUE THREAD

**Issue by unixneo** [sqlitebrowser/sqlitebrowser#3043]
### What did you do?

Everything worked great until I was in the Preferences tab for the app and tried to increase the font size from 13 to 14.   After that, everything when bad, as if the app cannot find the right font.  Now it nearly unreadable:

![Screen Shot 2022-05-26 at 12 15 07 PM](https://user-images.githubusercontent.com/12891828/170420816-3db54f97-9b2f-4aed-9eaf-1b15df49e6a9.png)

I tried uninstalling:

```bash
brew uninstall --cask db-browser-for-sqlite
```

and reinstalling

```bash
 brew install --cask db-browser-for-sqlite
```

but nothing works and I cannot get this great app back to the default state with a nice font.

Please advise on how to fix this bug.

Thanks!

### What did you expect to see?

See above.  Normal fonts when browsing data in tables.

### What did you see instead?

See above:  Strong, unreadable fonts when browsing data in tables.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

Monterey 12.3.1 (Chip M1 Max, Mac Studio 2022)

### Prevention against duplicate issues

- [X] I have searched for similar issues\

I searched the net extensively, uninstalled and reinstalled many times as well.  Nothing brings the fonts back (when browsing data in tables) to anything "readable".

**Comment by unixneo** [comment]
Never mind... found a "font" selection in the browser and changed table fonts.

![Screen Shot 2022-05-26 at 1 05 18 PM](https://user-images.githubusercontent.com/12891828/170427269-f01a5e1b-79b9-4a74-b898-dec89591ce87.png)

```self.closed```

**Comment by justinclift** [comment]
All good, glad you got it figured out. :smile:
