### ISSUE TITLE
Cannot use table editor with 'WITHOUT ROWID' tables

### ISSUE THREAD

**Issue by npiegdon** [sqlitebrowser/sqlitebrowser#3047]
Details for the issue
--------------------

#### Steps to Reproduce
1. Execute the following SQL for a new, blank database:
CREATE TABLE 'settings' ('key' TEXT NOT NULL UNIQUE, 'value' TEXT NOT NULL, PRIMARY KEY('key')) WITHOUT ROWID
INSERT INTO settings(key, value) VALUES('key1', 'value1');
INSERT INTO settings(key, value) VALUES('key2', 'value2');
(Feel free to insert as many rows in this fashion as you like; but two is enough to demonstrate the problem.)

2. From the Database Structure tab, right-click the 'settings' table and choose Browse Table.
3. Click on any table cell in the value column.
4. Click it again after a brief pause to enter editing mode.
5. Change the value to something different (say, "someNewValue") and press enter.
6. Click refresh button.

#### What did you expect to see?
Only that row's value should have changed to "someNewValue".

#### What did you see instead?
The value field of **ALL** rows change to "someNewValue"!

Useful extra information
-------------------------
This reproduces on nightly and the latest version.

This is very similar (identical?) to #2582, which is marked fixed (a year ago), but the behavior appears to still be happening.  Maybe this is a regression?

> DB4S v3.12.99 (May 10 2022) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLite Version 3.38.3
> and Qt 5.12.8

**Comment by MKleusberg** [comment]
That's not good! Thank you for reporting this issue.

This is caused by the single quotes used for the column name here. With double quotes it works fine:
```sql
CREATE TABLE 'settings' ("key" TEXT NOT NULL UNIQUE, 'value' TEXT NOT NULL, PRIMARY KEY("key")) WITHOUT ROWID;
INSERT INTO settings(key, value) VALUES('key1', 'value1');
INSERT INTO settings(key, value) VALUES('key2', 'value2');
```

I have just added a fix for the single quote case however. Can you try tomorrow's nightly build  and see if that fixes the issue for you?

**Comment by npiegdon** [comment]
I can confirm that the problem appears to be fixed in the latest nightly build.  Thanks!

**Comment by MKleusberg** [comment]
Awesome! Thanks for double checking :smile:
