### ISSUE TITLE
Preserve "Browse Data" field filters when switching tabs

### ISSUE THREAD

**Issue by FASposito** [sqlitebrowser/sqlitebrowser#305]
Moving off the Browse Data tab inadvertently clears all field filters. This creates a problem when frequent switching between application tabs is required. For example, when SQL statements are executed and then results are browses. Ideally, field filters would remain in place until actively cleared by the user. A "clear all filters now" button would be also be a great enhancement. Thanks!

**Comment by justinclift** [comment]
@schdub Any interest in taking care of this? :smile@

**Comment by schdub** [comment]
@justinclift, ok. Any idea where to put the button? I think it can be next to the 'Refresh the data...' tool button.

**Comment by justinclift** [comment]
Can we put an icon or something to the left of the filters?  Screenshot below, showing where I mean. :smile:

![2015-05-11-db4s-clear_filters_icon_question](https://cloud.githubusercontent.com/assets/406299/7563327/fec12a72-f7d3-11e4-9140-c9f9befcad3c.png)

**Comment by schdub** [comment]
@justinclift, I think not, because click in this place reserved for selecting all table contents.
What about this:
![screenshot from 2015-05-11 14 23 36](https://cloud.githubusercontent.com/assets/1304776/7564078/ee73d86e-f7eb-11e4-874a-331a2acee060.png)

**Comment by justinclift** [comment]
Good thinking. That seems like a good spot for it. :grinning:

@FASposito What's your opinion?

**Comment by FASposito** [comment]
I think that looks perfect, thanks. I'm really looking forward to this
change, even though it seems like a small one.

**Comment by justinclift** [comment]
@FASposito Just merged this.  The nightly build won't be created for about 20 hours or so, but would you be ok to test this out after that?

**Comment by FASposito** [comment]
Thanks! It would be an understatement to say that I would be happy to test
the new build...

**Comment by justinclift** [comment]
@schdub Any ideas on how we could have several "Browse Data" tabs?  Maybe we could make them be torn off, so they can be placed around the screen as separate windows?

This is so people can have "Browse Data" tab be open for several different windows at the same time.  I'm not sure how to make it happen though. :wink:

**Comment by justinclift** [comment]
@FASposito Reminder ping. :smile:

**Comment by FASposito** [comment]
Justin, Thanks for the reminder. It works perfectly. It really does make my
life an increment easier. When will the next official release come out?

**Comment by justinclift** [comment]
@FASposito Awesome! Rough aim for the next release is around June 8th. :smile:
