### ISSUE TITLE
[Bug]: Diagram panel: divider gone, diagram view cannot be restored after restart

### ISSUE THREAD

**Issue by derntl** [sqlitebrowser/sqlitebrowser#3055]
### What did you do?

1. In the diagram panel, reduce the diagram view to zero height by dragging the divider down

2. Close the program

3. When reopening the program, the attached error message box appears and the divider is not there any more. The diagram view cannot be restored, not by resetting window layout and also not by completely removing and reinstalling the program.

![dbbrowsererror](https://user-images.githubusercontent.com/4243679/171598033-0e21af85-846f-49a8-a4b0-fbde471f7cae.png)

### What did you expect to see?

I expect the divider in the diagram panel to allow me to expand the diagram view after being dragged to zero height and program being closed and reopened.

### What did you see instead?

After restart the divider is not there any more.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by scottfurry** [comment]
I'm confused about "diagram panel". I'm assuming you mean the plot dock?

However, as a workaround, you can find the configuration file for DB4S (look for a file called `sqlitebrowser.conf` - @justinclift - pls chime in with correct location). This a text file you can delete. Window and panel settings will be reset to startup defaults. You should get your window sash back to resize windows.

**Comment by derntl** [comment]
Thanks for the workaround. Yes I meant the plot dock.

**Comment by chrisjlocke** [comment]
While this error does appear at startup, it's benign.  

![image](https://user-images.githubusercontent.com/7872218/179388307-c39b96ea-e343-45c4-9b7d-c2e1f5e87323.png)

If you open a database (or create a new in-memory one) you can increase the size of the split area to remove the error.  The splitter bar _is_ there, but only if a database is open (so not immediately after program start).

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
