### ISSUE TITLE
Unexpected GUI looks?

### ISSUE THREAD

**Issue by lwandokasuba** [sqlitebrowser/sqlitebrowser#3058]
![Screenshot from 2022-06-05 08-34-23](https://user-images.githubusercontent.com/88346369/172038718-957dff45-2727-4096-9857-96f81187863d.png)
Unexpected GUI looks?
--------------------
Can anybody help me fix this?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on Manjaro Linux (linux/5.10.117-1-MANJARO) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.15.2

**Comment by justinclift** [comment]
Ouch... yeah that doesn't look right.

Is this the first time you've used the application, or is it a case that it used to work ok but now it's broken (like the above screenshot)? :smile:

**Comment by lwandokasuba** [comment]
I've used it before, and then it just broke when I wanted to use it.

**Comment by justinclift** [comment]
k.  So it's not that way "normally" on your system then.  Was just checking. :smile:

Two possibilities are springing to mind:

* Have there been any potentially relevant package changes on your system recently?  eg a change in Qt library of some sort, of perhaps some changes in the available fonts

* Alternatively, I wonder if there's something gone wrong with the DB4S preferences file.  eg what our font settings are stored in.  I'm not sure what it's likely called on Manjaro Linux though.  Probably "sqlitebrowser.<something>" in your user `.config` directory.  Rough guess though.  If you can locate that, I'd probably try renaming that file to something else (with DB4S not running), and see if that makes a difference. :smile:

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
