### ISSUE TITLE
SIGN function not working in SQLite

### ISSUE THREAD

**Issue by VigneswaraReddy** [sqlitebrowser/sqlitebrowser#3062]
Details for the issue
--------------------

#### What did you do?

SELECT SIGN(-145), SIGN(0), SIGN(145) FROM dual; --not working

select country
,LISTAGG(cname,',') WITHIN GROUP (order by cname )
from customer group by city;

#### What did you expect to see?
We need to supoort for SIGN function & LISTAGG function in SQLite3

#### What did you see instead?
these functions not defined on SQLIte3 so we are getting error 

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by VigneswaraReddy** [comment]
SELECT SIGN(-145), SIGN(0), SIGN(145) FROM dual; --not working 

LIASTAGG function also not working -- 
select country
,LISTAGG(cname,',') WITHIN GROUP (order by cname )
from customer group by city;

**Comment by MKleusberg** [comment]
As Justin already said this statement only works on Oracle databases
```sql
SELECT SIGN(-145), SIGN(0), SIGN(145) FROM dual;
```

However, in SQLite you can just remove the ```FROM``` part as long as you don't actually query any data from the file. So this works fine:
```sql
SELECT SIGN(-145), SIGN(0), SIGN(145);
```

**Comment by VigneswaraReddy** [comment]
Thanks for helping on Sign function 

My requirement is to fetch sum of all positive numbers & sum of all negative numbers from table.
SO i have created some test table & inserted some data in SQLite3 browser and its failing while running select statement 
Could you please try from your side to create below table & run select statement

create table fetch_pos_neg_sum (x integer);
insert into fetch_pos_neg_sum values(2);
insert into fetch_pos_neg_sum values(-2);
insert into fetch_pos_neg_sum values(4);
insert into fetch_pos_neg_sum values(-4);
insert into fetch_pos_neg_sum values(-3);
insert into fetch_pos_neg_sum values(0);
insert into fetch_pos_neg_sum values(2);

--running below statement and its failing, Please help me to correct query
select sum((sign(age)+1)/2 * age) as positive_sum ,
sum((-(sign(age)-1)/2) * age) as negative_sum 
from fetch_pos_neg_sum;

**Comment by VigneswaraReddy** [comment]
We have requirement like need to fetch all customer names with comma separated based on city , So i have created below table & inserted data and its failing while using LISTAGG function.
Can you help is there any function available instead of LISTAGG in SQLite3 

create table customer(cid integer,cname varachar2(40),city varchar2(20));
insert into customer values(1,'Jaga','Bangalore');
insert into customer values(2,'VIGNESH','Bangalore');
insert into customer values(3,'Sidd','Hyderabad');
insert into customer values(4,'Adarsh','Pune');

-- Below select statement is failing 
select country
,LISTAGG(cname,',') WITHIN GROUP (order by cname )
from customer group by city;


Excepted Output: 
Bangalore Jaga,VIGNESH 
Hyderabad Sidd 
Pune      Pune

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
