### ISSUE TITLE
[Feature]: Nightly Linux AppImage

### ISSUE THREAD

**Issue by longnguyen2004** [sqlitebrowser/sqlitebrowser#3064]
### Describe the new feature

My database is using strict mode, which requires SQLite 3.37.0 or newer, but the current testing PPA doesn't contain a new enough version, and my computer is too slow for a build. Can we have a nightly AppImage, like what Windows and macOS have?

**Comment by MKleusberg** [comment]
Good news is that we actually already have AppImages built for each new version. You can find the latest one [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous). Bad news is that they're only including SQLite 3.22. So it seems like we'd have to build SQLite from source. Unfortunately I don't have the time right now but maybe one of the other developers has. If you don't hear back from us any time soon-ish feel free to message me again :smile:

**Comment by longnguyen2004** [comment]
Should be pretty easy to set up, since you already got CI running. I'll wait for your response :)

**Comment by MKleusberg** [comment]
Ok, this was easier than expected :wink: Can you give the latest AppImage from [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous) a try? It should ship with SQLite 3.38.5.

**Comment by longnguyen2004** [comment]
Hmm...does it grab the correct version? The about dialog said 3.38.5, but `sqlite_version()` returns 3.22.0
![image](https://user-images.githubusercontent.com/15729831/173108522-4ae30410-d297-486a-a296-94eca50d0df2.png)
![image](https://user-images.githubusercontent.com/15729831/173108592-515f9ddc-f64c-4080-98f2-a5e5516eb9e1.png)

**Comment by longnguyen2004** [comment]
Extracting the AppImage, then running `strings ./libsqlite3.so.0 | grep -E '[0-9]+\.[0-9]+\.[0-9]+'` returns
```
COMPILER=gcc-7.5.0
3.22.0
GLIBC_2.2.5
GLIBC_2.3.4
```
So CMake did pick up the correct file, but the packaging step uses the wrong file.

**Comment by justinclift** [comment]
> So CMake did pick up the correct file, but the packaging step uses the wrong file.

Sounds like the packaging step still needs work then. :wink:

**Comment by MKleusberg** [comment]
Hmm, it looks like for compiling it uses the correct library but then bundles the wrong one in the AppImage. What's confusing here is that the [tool we use for AppImage creates](https://github.com/probonopd/linuxdeployqt) says it relies on ```ldd``` for determining which library to include:
> Open in Qt Creator and build your application. Run it from the command line and inspect it with ```ldd``` to make sure the correct libraries from the correct locations are getting loaded, as ```linuxdeployqt``` will use ```ldd``` internally to determine from where to copy libraries into the bundle.

```ldd``` however points at the correct library:
> libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x00007f63bda39000)
> libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f63bd7ca000)

So this will need some extra investigation :thinking: 

> I've also looked through the CMakeLists, and found hardcoded paths to various libraries, which is a big no-no in modern CMake.

Yes, you're absolutely right. If I remember correctly, the hard coded paths are mainly for building release versions and nightly builds for macOS and Windows and really should be part of a build script or similar (if required at all). @justinclift Do you know how much the macOS and Windows builds rely on these fixed paths in CMakeLists.txt?

**Comment by longnguyen2004** [comment]
> `ldd` however points at the correct library:

Probably because I tested the build before  https://github.com/sqlitebrowser/sqlitebrowser/commit/738ecd6feb5e2fec1735a26441c3e78df3e3e92e exists, so that can explain it.

Anyway, I have a local branch where I removed all `*_directories` function calls, and replaced it with proper targets. One disadvantage is that it requires CMake 3.14, since `FindSQLite3.cmake` is only available from 3.14 onwards. Is that good?

**Comment by MKleusberg** [comment]
> Probably because I tested the build before https://github.com/sqlitebrowser/sqlitebrowser/commit/738ecd6feb5e2fec1735a26441c3e78df3e3e92e exists, so that can explain it.

Unfortunately that commit didn't help either. It's still bundling version 3.22.0 in the AppImage. My best guess is that this could be because the Qt libraries also depend on SQLite and they were built using SQLite 3.22.0. But instead of going down that rabbit hole it might be the easiest option to just link SQLite statically and be done with it. Since you seem to know a fair amount about cmake, is there any preferred way to link a library statically? It seems like most people just directly point to the .a file using the full path but I don't really want to do that.

**Comment by justinclift** [comment]
> Do you know how much the macOS and Windows builds rely on these fixed paths in CMakeLists.txt?

We can probably make them environment variables (or something along those lines), instead if that'd be better?

**Comment by longnguyen2004** [comment]
So there are 2 ways that we can go about this
1. Build SQLite statically (easy - just pass an extra option to `configure`)
2. Set `LD_LIBRARY_PATH` to `/usr/local` before packaging (would resolve everything to the local SQLite build)

What way should we go with?

**Comment by longnguyen2004** [comment]
> We can probably make them environment variables (or something along those lines), instead if that'd be better?

Or keep them as CMake variables, but requires the user to set them from the command line.

**Comment by MKleusberg** [comment]
Well, it's working now. You can download the AppImage that this time actually ships with SQLite 3.38.5 [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous).

> So there are 2 ways that we can go about this
>
>     1. Build SQLite statically (easy - just pass an extra option to `configure`)
>     2. Set `LD_LIBRARY_PATH` to `/usr/local` before packaging (would resolve everything to the local SQLite build)
> 
> What way should we go with?

Number one is easy and I've done that but that doesn't seem like it's enough. I've also tried two but that didn't change anything. The current solution is super hacky and just replaces the ```.so``` in the library path by ```.a```. After trying basically everything, this is the only thing that actually worked :unamused:

**Comment by longnguyen2004** [comment]
> Number one is easy and I've done that but that doesn't seem like it's enough.

You also need to specify `--enable-shared=no`

> I've also tried two but that didn't change anything.

My bad...it needs to be `/usr/local/lib` 😅

Anyway, this is long enough as it is. I'll probably go back and refactor the CMakeLists, to bring it up to modern CMake standards (see my PR #3068 for more info), and also to remove the various hacks that has accumulated from this. For now, this issue can be closed.

**Comment by justinclift** [comment]
Sounds like we're making progress. :smile:

**Comment by longnguyen2004** [comment]
Merged! Now we have proper static SQLite in the nightlies
