### ISSUE TITLE
[Feature]: missing "clear" button in SQL tab

### ISSUE THREAD

**Issue by anvalanz** [sqlitebrowser/sqlitebrowser#3065]
### Describe the new feature

If you write a very long SELECT statement, 
it could be useful to have a "clear" button in the SQL tab the same as in the Log tab.

I haven't find any fast solution to select all the SQL code in order to delete it and to type other code.

**Comment by justinclift** [comment]
> I haven't find any fast solution to select all the SQL code

For me, pressing Control-a (eg the "standard" key combination for "select all") works.  That's on Linux, though I'd expect the same to work on Windows too.  On macOS, it's probably Command-a or something instead.

Any luck with that? :smile:

**Comment by anvalanz** [comment]
Thanks for the answer, 
it  works also on Windows.
