### ISSUE TITLE
[Bug]: App crashing and closing on Linux when selecting "Modify Table"

### ISSUE THREAD

**Issue by Baquara** [sqlitebrowser/sqlitebrowser#3069]
### What did you do?

I opened the sqlitebrowser app, selected a database, right clicked a table, then selected "Modify Table". The app instantly crashes and closes. I tried both versions from Arch Linux's package manager and Flatpak and had the same results.

I run the application through a terminal, please check the log for more details.

### What did you expect to see?

The table modification window to open.

### What did you see instead?

The app instantly closed.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Arch Linux with kernel 5.18.2-arch1-1

### Relevant log output

```shell
/usr/include/c++/12.1.0/bits/basic_string.h:1292: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&]: Assertion '!empty()' failed.
Aborted (core dumped)
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
> '!empty()' failed.

Whatever is empty, I guess isn't there.  That must be more than empty.  Whoopsie.
I'm guessing (as there aren't many reports of this) that this may be solved in the latest codebase.  I'm not sure what versions you've tried or what version the 'flatpak' is, but can you build from the latest source at all?

**Comment by Baquara** [comment]
> > '!empty()' failed.
> 
> Whatever is empty, I guess isn't there. That must be more than empty. Whoopsie. I'm guessing (as there aren't many reports of this) that this may be solved in the latest codebase. I'm not sure what versions you've tried or what version the 'flatpak' is, but can you build from the latest source at all?

I just built from the scratch from the latest git and it now works.

So there is a problem with the latest stable release, sqlitebrowser version **3.12.2-2**

I suggest making a new stable release ASAP so this problem can be fixed for more people looking for the binaries.

Thank you

**Comment by Weav3r** [comment]
Also had the same issue running archlinux with kernel 5.8.2 (same), resolved it by building from source. However, I'm still having other problems. I'll have dig deeper and open a new issue if the need arises.

**Comment by chrisjlocke** [comment]
> I suggest making a new stable release ASAP

A release was planned, but was delayed as a couple of people have been away doing 'life' things.
As a build is (for Linux, anyway) easy to create, it's not a hooooge issue.  For Windows and Mac users, a nightly build is built automatically.

**Comment by eduarddejong** [comment]
Yep pretty serious issue - being able to edit table definitions is quite a fundamental task :P, at the moment I was not planning to install Qt on my system, just using the previous version now. I am on Arch Linux as well by the way.

**Comment by lemerchand** [comment]
This is also occurring for me on Manjaro. There seems to be a Git version in the AUR but I am not sure if that's worth trying out. Love the program, but I'm new to designing DBs and I really would prefer to modify a table rather than delete and build from scratch!

**Comment by justinclift** [comment]
@mgrojo @MKleusberg Any ideas? :smile:

**Comment by justinclift** [comment]
@lemerchand If the git version isn't too hard to try out, please give that a shot.  This weird crash seems like some interaction between our code, and whatever version of libraries are on your systems.

The git version of our code is substantially tweaked and adjusted since the last release (we need to make a new one), so there's a decent chance whatever the bad interaction is... it'll either not be present... or will behave differently (!). :wink:

**Comment by coding4me2** [comment]
On Manjaro also. I swapped to the snap version and it works so just another option until the new release comes out.

**Comment by chrisjlocke** [comment]
As this seems fixed, I'll close this issue - there are workarounds if anyone needs them until the official release.

**Comment by Cr4tes** [comment]
Any idea when this fix will make it to the Flatpak version?

**Comment by justinclift** [comment]
Not really.  If you're ok with an AppImage though, that's available right now:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
