### ISSUE TITLE
[Feature]: Change the default chinese language font to "Microsoft YaHei UI".

### ISSUE THREAD

**Issue by suyangzuo** [sqlitebrowser/sqlitebrowser#3070]
### Describe the new feature

Current default chinese font is "宋体" or "SimSun", it looks very ugly, especially in high dpi screen.
I suggest use "Microsoft YaHei UI" for the chinese language UI font.

**Comment by chrisjlocke** [comment]
This is due to a bug in Qt which goes back to 2011.
https://github.com/sqlitebrowser/sqlitebrowser/issues/2744

We could fix this, but have decided to wait until the bug which won't get fixed (well, its been 11 years so far...) gets fixed.
