### ISSUE TITLE
misleading dialog: 'Collation needed! Proceed?' when opening db with NOCASE collation

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#308]
Please change dialog title and message to reflect the actual choices.

@justinclift suggested "NOCASE collation does not handle multi-byte characters"

**Comment by justinclift** [comment]
Oops, somehow missed this. 😦 

If this is still happening with our latest nightly builds, then changing the dialog text is very easy to do.

Um... if you're still interested in this, would you be ok to check if this still happens with our latest nightly build?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

If it still happens, I'll update the dialog text. :smile:

**Comment by palmiche** [comment]
The text didn't change from 3.9.1 to 3.9.99.  :confused:

**Comment by justinclift** [comment]
Ahhh yeah.  Looking at it here, it's still there: https://github.com/sqlitebrowser/sqlitebrowser/blob/7ad80352616df1b185ab87f989cb7c2fd6c784c5/src/sqlitedb.cpp#L48

Just to confirm, "NOCASE collation does not handle multi-byte characters.  Proceed?" would be better yeah?

If so, I'll change it immediately.  Better wording suggestions are welcome too of course. :smile:

**Comment by palmiche** [comment]
I'm not sure about that. What will happen if you choose "No"? From a purely UI pov a warning with just one button has the same effect: you execute the query anyway. So what the user (me) needs to know is what effect will the choices have. 

Something like:

Title: "NOCASE collation does not handle multi-byte characters. Proceed? "
Message: 
"A table in this database requires a special collation function '%1' "
"that this application can't provide without further knowledge.\n"
"If you don't proceed, NNN.\n"
"If you do proceed, YYY.\n"
"Be aware bad things can happen to your database. Create a backup!"

Replace the YYY and NNN with the effects.
I'd also like to know what those "bad things" are. 😄 

3.10 version name 👍 😆

**Comment by justinclift** [comment]
Ahhh, yeah.  I'm not sure what those effects are either.  We'll have to ask someone who knows this part of things better. 😕

**Comment by palmiche** [comment]
>  I'm not sure what those effects are either. 

My point exactly. 😉

**Comment by justinclift** [comment]
Reading through this again.  We updated DB4S just under a month ago (#1172) to not complain about NOCASE collation.

I have no idea if we're correctly handling multi-byte characters though, and have no real understanding how to test.

Hmmm... @mtissington is this something you'd know about off hand?  eg are you using multi-byte characters with your DB4S databases already and seen if we're collating then correctly?

**Comment by mtissington** [comment]
Well the the latin languages collate correctly. We are working with other languages too, and they seem to collate correctly but have not yet done much testing. I was under the impression that you were now passing the collation onto sqlite and not getting involved?

**Comment by justinclift** [comment]
Yeah, that's my understanding as well... but I'm only (personally) assuming that works ok and haven't really tested it.  Haven't yet had a need for any non-default collations (again, personally) so it's not yet something I know much about.

**Comment by mtissington** [comment]
The only thing I can say with certainty is that it's working for latin languages.

**Comment by justinclift** [comment]
No worries. :smile:

@palmiche Would you have the time and interest to try the collation again with a multi-byte language?  I'm thinking this is now fixed, but we need someone to verify. :smile:

**Comment by mtissington** [comment]
We have done a little testing with Thai - and very basic testing shows it's OK - we are not yet in a position to have someone else do a solid validation with Thai (in this example). The problem for us at the moment is asking a native speaker do the validation for us!

**Comment by MKleusberg** [comment]
If it helps: for the ```BINARY```, ```RTRIM```, and ```NOCASE``` collations we're not doing anything now. We used to overwrite SQLite's own implementation of them but now just leave that as-is. That's why the dialog doesn't pop up anymore, too. So if there is no dialog, we're using the SQLite implementation.

For the ```UTF16``` and the ```UTF16CI``` collations we always register our own implementation, since they are not build into SQLite.

For all other collations, we're still showing that dialog. If you click Yes in there, a default collation is installed which performs exact comparisons of the memory representations of the strings.

(We might want to put this in a Wiki page, now that I'm thinking about it :wink:)

**Comment by palmiche** [comment]
> @palmiche Would you have the time and interest to try the collation again with a multi-byte language?

@justinclift I'm always interested and time can -and will- be found. 😁

**Comment by palmiche** [comment]
The nightly seems to be working fine.

In case you need to do some testing I'm using SQL Server databases with a mix of SQL_Latin1_General_CP850_CI_AS, SQL_Latin1_General_CP1_CI_AS and Modern_Spanish_CI_AS exported with [SqlConverter v1.20](https://github.com/jschultz/sqlconverter). The app uses Xamarin's Mono.Data.Sqlite.

**Comment by justinclift** [comment]
@palmiche Excellent, thanks.  Sounds like this issue can be closed then. :smile:

**Comment by palmiche** [comment]
Thank you. I'm already using the nightly full time. 😀
