### ISSUE TITLE
[Bug]: Replicable crash - CTD on returning results after not returning results

### ISSUE THREAD

**Issue by wjagodfrey** [sqlitebrowser/sqlitebrowser#3082]
### What did you do?

Ran a query that returned no results, and then ran a query that returned several thousand results.

E.g. First:
```
SELECT
  *
FROM entries
WHERE
  remove IS 'no a valid value'
```

Second:
```
SELECT
  *
FROM entries
WHERE
  remove IS false
```

### What did you expect to see?

DB Browser didn't crash to desktop.

### What did you see instead?

DB Browser immediately CTDs.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

12.3 (Monterey)

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Interesting.  Does the crash happen with the latest nightly build for macOS?

eg: https://nightlies.sqlitebrowser.org/latest/

**Comment by wjagodfrey** [comment]
That seems to have fixed it! Looks like it was triggered by using `REGEXP` at least once, though I can't confirm that. Anyway, looks like nightly is fixed. I'll reopen if it comes back.

Thanks!

**Comment by MKleusberg** [comment]
Awesome, I'll close this issue then :smile:
