### ISSUE TITLE
[Feature]: "copy CREATE command" does not appear in the most common database scheme area

### ISSUE THREAD

**Issue by duritia** [sqlitebrowser/sqlitebrowser#3086]
### Describe the new feature

Wanting to copy a CREATE command  for a table currently selected in an open database, I tried several things. It is shown, but there is no way to copy it:

![image](https://user-images.githubusercontent.com/69221194/177199556-62a0047f-0ecb-462c-88a8-2183a1b4ec5f.png)

![image](https://user-images.githubusercontent.com/69221194/177199855-6721ad43-41ae-481e-8cea-061954883862.png)

The menu shown in the second photo is the menu opened by right clicking over the table scheme shown in the first. There is no option to copy the SQLite command to create the command, like there is when we click in the same information on the left part of the window shown in the first photo:

![image](https://user-images.githubusercontent.com/69221194/177200559-64ea6c75-2d3b-4711-a29c-e938b7184380.png)

### Do you have a screenshot? Please add screenshots to help explain your idea.

Enough screenshots were added along the request explanation.

**Comment by chrisjlocke** [comment]
Not sure I follow or understand the issue.

![image](https://user-images.githubusercontent.com/7872218/177222659-18b23371-04c8-4854-8eb3-644a9a28a97b.png)

In the main 'Database structure' tab, you can right-click any table and select 'Copy create command'.
You can't copy the schema from the 'DB Schema' window, but you can find the table in the main 'Database structure' tab.

**Comment by chrisjlocke** [comment]
Closing as no response.
