### ISSUE TITLE
[Bug]: Main window is too big, and maximizing it does not change anything

### ISSUE THREAD

**Issue by duritia** [sqlitebrowser/sqlitebrowser#3087]
### What did you do?

In my screen, which is not too small, the sqlitebrowser is only partially visible. This seems to be something easy to fix because there are parts of the window that can have a lower height, without compromising anything - at most, it could mean having a vertical scrollbar more often for them, naturally. My screen is 1366 x 768.

I use Debian and Mate Desktop. The maximized window looks like this:

![image](https://user-images.githubusercontent.com/69221194/177210402-b45181e7-0983-47f1-82aa-7ce85163fc82.png)

If I undo maximizing the window, I can change its width to less than 50% of the screen width. But the window height does not seem to accept a single pixel reduction.

Even if I hid the top and bottom bars I use in Mate Desktop, the window height is not completely shown. So, I think it really needs some change.

### What did you expect to see?

All the boards and things present in sqlitebrowser window.

### What did you see instead?

A cropped window.

### DB4S Version

3.12.1

### What OS are you seeing the problem on?

Linux

### OS version

Debian  11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
If I remember correctly, this is due to one of the docker windows, eg, remote.  I think there was a fix or tweak possibly done after the 3.12.2 release?  Note that 3.12.1  is at least one revision out.

![image](https://user-images.githubusercontent.com/7872218/177267462-2729d82b-831f-41b6-a4e7-b4e2350cb2bf.png)

Click 'View' and remote the top four entries - SQL Log, Plot, DB Schema and Remote.  See if that improves, then turn on each entry again until it breaks - I suspect it might be Remote.

**Comment by justinclift** [comment]
@chrisjlocke `docker` -> `docked` :wink:

**Comment by MKleusberg** [comment]
Just did some testing (with the latest build and on my system, so the exact number may vary slightly). There is a minimum window height and you're not allowed to make the window any smaller. This height mostly depends on the docked windows as Chris said. With the Edit and the Schema docks placed next to each other like on your screenshot it is 774 pixels (so slightly higher than your screen and not including the title bar of the window). If you move the Edit dock on the Schema dock or vice versa they are tabbed. This reduces the minimum window height to 584 pixels which would be way more workable on your system. Would that be workable for you?

I'll also check if we can reduce the minimum window height for both cases (stacked or tabbed docks). But this will only give you a couple of pixels either way...

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
