### ISSUE TITLE
[Feature]: Search Box

### ISSUE THREAD

**Issue by barragh** [sqlitebrowser/sqlitebrowser#3089]
### Describe the new feature

Not sure if I can't find it or it's just not there but I'd like if there was a search box in the 'browse data' tab. It's fiddly having to widen the columns, sort by name and scroll through the data to try and find what you're looking for. It would be really good if there was some sort of search box/function in the browse tab to make it easier to find things.
It's just a suggestion and if it IS there already could you please tell me where to find it?
Thanks:)

**Comment by chrisjlocke** [comment]
Depends on what version you have, and what exactly you want to do.

![image](https://user-images.githubusercontent.com/7872218/177593342-6f84f89b-3069-4bd6-af0b-47b0b7651140.png)

If you press Ctrl+F or press the icon in the toolbar, a search block should appear at the bottom of the screen.

![image](https://user-images.githubusercontent.com/7872218/177593401-0af7d612-bd11-48f5-ab3b-08551c0bdd08.png)

This supports regular expressions, etc.


![image](https://user-images.githubusercontent.com/7872218/177593493-563f4517-7ea1-42a7-8e51-9a68a7fe62eb.png)

At the top of each column you also have a filter box.  I think this is more powerful as the filters can be combined - so field1 that contains 'banana' and field2 that contains 'jack', etc.

**Comment by mgrojo** [comment]
Did it work for you, @barragh ? When not, just reopen this issue and tell us the problem.

**Comment by barragh** [comment]
Sorry @chrisjlocke @mgrojo for the very slow reply. I had a look at my version of Sqlitebrowser (Version 3.11.2) and did what you told me but found no button on the toolbar and pressing Ctrl+F doesn't seem to do anything. I am using Linux Mint. Just wondering if this is the latest version or am I using an old version and that's why it is missing the button?

**Comment by chrisjlocke** [comment]
3.12.2 is the latest version, but even that is old compared to the local source.
You could try building from the latest source, as you're on Linux.

**Comment by barragh** [comment]
Okay, I will try that and see if it fixes it:)

**Comment by barragh** [comment]
Okay, I will try that and see if it fixes it:)

**Comment by barragh** [comment]
Thank you @chrisjlocke !! This solved my problem:) I built it from source like you told me but also had to maximise the window to see the search button. Problem solved! Thanks everyone:)

**Comment by chrisjlocke** [comment]
Glad you got it resolved.  Thanks for reporting back. 👍
