### ISSUE TITLE
[Bug]: Removing encryption of DB causes syntax error

### ISSUE THREAD

**Issue by JHarzenetter** [sqlitebrowser/sqlitebrowser#3097]
### What did you do?

I opened a encrypted Database with the SQLCipher.exe and tried to remove the encryption via Tools > Set Encryption.
As Password i didn't pass anything (worked in Version 3.11.2). 
SQL Encryption: SQL Cipher 4

### What did you expect to see?

The Command runs correctly

### What did you see instead?

An Error Dialog wich says 
"near "s": syntax error (ATTACH DATABSE 'D:/PATH/TO/DATABASE' AS sqlitebrowser_edit_encryption KEY";)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Win 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by scottfurry** [comment]
> An Error Dialog wich says "near "s": syntax error (ATTACH DATABSE 'D:/PATH/TO/DATABASE' AS sqlitebrowser_edit_encryption KEY";)

This may seem pedantic, but could you check that output, please? I would like to confirm that `DATABSE` is an error in transcribing dialog message.

**Comment by chrisjlocke** [comment]
Think this was just a typo.

![image](https://user-images.githubusercontent.com/7872218/180098213-738508b4-567d-46cf-a9af-9f43fb249270.png)

@JHarzenetter - does your file and/or the path contain an apostrophe?
I didn't have problems encrypting/decrypting for files with spaces in them, but did if I added an apostrophe.

Workaround: Remove the apostrophe in the path/file temporarily.  Decrypt, then rename the file/path back as needed.

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
