### ISSUE TITLE
Does DB4S support any of the giving statements?

### ISSUE THREAD

**Issue by HimeshAsite512** [sqlitebrowser/sqlitebrowser#3098]
### Describe the new feature

Does it support any of the following statements mentioned below ?

**IF Condition,
delimiter,
PROCEDURE,
CASE condition.**

### Do you have a screenshot? Please add screenshots to help explain your idea.

![image](https://user-images.githubusercontent.com/89390810/179975258-fbdade78-d0f2-497d-9894-f1de50546a05.png)

**Comment by scottfurry** [comment]
This is more of an SQLite question than DB4S.

This desktop program is dependent on and limited by the underlying SQLite implementation. So, questions of "... does it support ...?" can mostly be answered by looking at SQLite documentation.

I suspect that the short answer to your questions is "No". Although `PROCEDURE` is apart of the SQL standard, SQLite does not really implement that functionality to a large degree. This [StackOverflow Q&A](https://stackoverflow.com/questions/3402841/does-sqlite-support-stored-procedures) should point you in good direction towards a fulsome answer.

**Comment by chrisjlocke** [comment]
SQLite doesn't support IF, but you can use CASE

    select case when length(a) > 4 then a else '' end as b
    from foo

http://sqlite.org/lang_expr.html


Delimiter?  Don't know what this means.
Procedure?  No.
Case?  Yes.

**Comment by chrisjlocke** [comment]
Closing as no response.
