### ISSUE TITLE
[Bug]: Crashing on 'Modify Table'

### ISSUE THREAD

**Issue by Isaacson33** [sqlitebrowser/sqlitebrowser#3102]
### What did you do?

Open an sqlite database (I've tried several)
Click on 'Modify Table' (right click on the table name in the database structure tab)

### What did you expect to see?

Open the modify table dialogue

### What did you see instead?

DB browser crashes

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Manjaro 5.15

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
This has been raised recently, and building from source should hopefully fix this.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3069

I'll close this as a duplicate, but if you have any issues, please yell in the above issue which can be re-opened.

**Comment by Isaacson33** [comment]
@chrisjlocke 

Thanks. Sorry for missing the existing report, I must have somehow skimmed over it in my checks. I'll build from source until the next release is officially out.

**Comment by chrisjlocke** [comment]
Not a problem at all - with so many open issues and variations how people enter them, it's not easy finding an existing issue.
Rebuilding from source should be simple enough though and give a more stable experience than the current release.
