### ISSUE TITLE
[Bug]: Frequent crashes when executing SQL on Mac 11.6 with 3.12.2

### ISSUE THREAD

**Issue by mikechambers** [sqlitebrowser/sqlitebrowser#3104]
### What did you do?

Running SQL Queries.

Crash is random, and restarting and running the exact same query usually works fine, but eventually it will crash again. Not one specific query.

Next time it crashes, Ill add the DB and actual query if I have a copy of it before it crashes (the query)

### What did you expect to see?

The query execute

### What did you see instead?

Crash

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

11.6

### Relevant log output

Crash log is here : https://pastebin.com/8yLSyXGv

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ouch.  Please try the latest nightly build, and let us know if it's still happening for you:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
Is this related to a query not having data/rows and then having data/rows (or vice versa).  I seem to recall something (which has been fixed) where a query run after another query was problematic.  I can't remember the sequence of events, but its tucked here somewhere.... ;)

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
