### ISSUE TITLE
Windows Nightly Download stuck at 22 bytes since 2022-07-25...

### ISSUE THREAD

**Issue by mlawren** [sqlitebrowser/sqlitebrowser#3105]
### What did you do?

I visited https://nightlies.sqlitebrowser.org/latest/

### What did you expect to see?

I expected to see full-size distribution/release files

### What did you see instead?

What I saw instead was this:

    Index of /latest/

    ../
    * README.txt                                       16-Jan-2019 19:58                1635
    DB.Browser.for.SQLite-sqlcipher.dmg                27-Jul-2022 03:58            18184847
    DB.Browser.for.SQLite-win32.zip                    25-Jul-2022 04:03                  22
    DB.Browser.for.SQLite-win64.zip                    25-Jul-2022 09:03                  22
    DB.Browser.for.SQLite.dmg                          27-Jul-2022 03:58             1867895

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Thanks for reporting.  Our chief Windows build investigator will be on the case... ;)

**Comment by MKleusberg** [comment]
@justinclift Could you send us the build log of the Windows nightlies? :smile:

**Comment by justinclift** [comment]
Been trying to get this working for a few hours now (very slow build server). :frowning:

It's something to do with the recently merged [PR #3068](https://github.com/sqlitebrowser/sqlitebrowser/pull/3068#issuecomment-1199641236).  It's no longer finding the SQLCipher install.

This is the full build log (manually cut-n-pasted) for the Win64 build, if it's useful.

[2022.07.30-win64_build_error1.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/9221846/2022.07.30-win64_build_error1.txt)

**Comment by justinclift** [comment]
Note that I'm also mucking around with the (x86) macOS builds atm too, so ignore any potential weirdness there for a few hours as well. :wink:

**Comment by sky5walk** [comment]
How far away are the nightly builds?

**Comment by chrisjlocke** [comment]
> This is the full build log

Thoughts from someone who doesn't know what they're on about...

> : The system cannot find the file 'C:\bui
> lds\release-sqlcipher-win64\Release\DB Browser for SQLCipher.exe'.

This line makes sense - the build failed.

> Could Not Find C:\git_repos\sqlitebrowser\installer\windows\DB.Browser.for.SQLite-win64.wixpdb

This looks suspicious

> WARNING: The system cannot find the path specified.
> C:\builds\zip\DB Browser for SQLite

This looks suspicious too

> cp: cannot stat ΓÇÿ/nightlies/win64/DB*SQLite-2022-07-29-win64.msiΓÇÖ: No such file or directory

Weird characters here - is this OK?

Has a chkdsk been performed on the box at all?  Wondering if the file system is slightly borked, so it's giving false errors?

**Comment by justinclift** [comment]
> Weird characters here

Yeah, that's just the output being displayed when it hit unicode characters there.  It's not a path corruption thing. :wink:

It should be up and running again next week.

**Comment by sky5walk** [comment]
At this point, would it be ok to deploy the non-cipher exe's?

**Comment by justinclift** [comment]
What do you mean?

**Comment by sky5walk** [comment]
I read that the build errors were limited to sql-cipher?

**Comment by justinclift** [comment]
With the macOS builds, the SQLCipher ones were actually still building ok.  But the same script runs both, so disabling the script disables both.

For Windows though, neither seems to be working properly. :frowning:

I had to put time into other stuff earlier this week, but have started building a new Win dev VM on my local workstation so I can figure out how to solve the problem.  The setup of that isn't complete though.  I went with installing Visual Studio 2022 (Community edition) instead of Visual Studio 2017, and it seems like Qt 5.x doesn't support VS 2022.  So, I need to find an install for VS 2017 instead and use that I reckon.

**Comment by chrisjlocke** [comment]
Web installer
https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15

ISO
https://developerinsider.co/download-visual-studio-2017-web-installer-iso-community-professional-enterprise/#downloadvisualstudio2017iso

Found from here:
https://developerinsider.co/download-visual-studio-2017-web-installer-iso-community-professional-enterprise/

**Comment by justinclift** [comment]
Awesome, thanks. :smile:

**Comment by justinclift** [comment]
Cool, that worked.  Thanks @chrisjlocke. :smile:

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/188018930-59aae487-6f25-4844-8506-451453a02094.png)

**Comment by sky5walk** [comment]
Ha, that is a distant goal given my time constraints.

**Comment by justinclift** [comment]
As a data point, the macOS SQLCipher nightly builds are working again now.  The standard (non-SQLCipher) ones still a work-in-progress though.

**Comment by justinclift** [comment]
As a data point, I've gotten the standard SQLite nightly builds to compile ok now.  I next need to update the macOS version in the VM, update the Apple dev certificate used for signing builds, and some other related points.

I've tried an initial update to macOS Monterey (most recent release), but it doesn't function properly on the ancient cpu the box runs.  So next I'm trying updating to macOS Catalina instead, the oldest macOS release that Apple still considers "supported".

Fingers crossed... :smile:

**Comment by sky5walk** [comment]
Way to go! 🤤

**Comment by justinclift** [comment]
k.  I've tried 4 times to install macOS Catalina on this thing, and it never finishes.  I think it's time to just retire this ancient Mac Mini, and figure out a different approach.

Thanks to our Patreon supporters, we have funds for getting a replacement (modern) Mac Mini.  Maybe a refurbished [2018 Mac Mini](https://www.apple.com/au/shop/refurbished/mac/mac-mini) or similar.  That might be the way to go.

Either way, I've spent enough time on this today so am calling it a night.  Will pick this up again either tomorrow or Sat and figure out both short and long term solution. :smile:

**Comment by sky5walk** [comment]
Is it possible to upload a _manually_ compiled Windows x64 non-ciphered nightly?
I see a truncated entry today.

**Comment by chrisjlocke** [comment]
Er.... https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip maybe?
Its 19.9 MB and opens successfully.

**Comment by sky5walk** [comment]
Nice, that was 22bytes when I checked. I'll check it out.

**Comment by justinclift** [comment]
A fix for the Windows builds has been figured out by @mgrojo today, and merged. :smile:

So, new Windows nightly builds are going again now.  I've updated the SQLite version to 3.39.3 (latest current release), and updated the Qt version to 5.12.12 (from 5.12.8).

We *could* move to the newer Qt 5.15.2, but I don't recall it adding anything important we need.  So, just keeping with the 5.12.x series on this old VM for now.

**Comment by sky5walk** [comment]
Great job 💯 
And, the sqbpro error seems to be fixed. Will close ticket.

**Comment by mlawren** [comment]
I'll save you the trouble @sky5walk , since I opened this in the first place :-)

Thanks team for the efforts, here and elsewhere!
