### ISSUE TITLE
[Feature]: option to save all tabs to sql file

### ISSUE THREAD

**Issue by KrischnaGabriel** [sqlitebrowser/sqlitebrowser#3107]
### Describe the new feature

An option to save all query tabs to a file, plus an option to open them all.

### Does this feature exist in another product or project? Please provide a link

Yes, this is the default behavior in the MySQL Workbench.

### Do you have a screenshot? Please add screenshots to help explain your idea.

N.A.

**Comment by chrisjlocke** [comment]
This is sort of there in project files (file -> Save project)
But don't use the nightly ... use the 3.12.2 release (or an old nightly).

**Comment by chrisjlocke** [comment]
Closing due to no response.
