### ISSUE TITLE
Frequent Crashes using Manjaro Linux

### ISSUE THREAD

**Issue by TommmieM** [sqlitebrowser/sqlitebrowser#3112]
Details for the issue
--------------------

#### What did you do?
Updating SQLite DB, after some writes to tables, browser will crash on next query. On restart, the previous write was not executed.

#### What did you expect to see?
Ummm, It not crashing and losing db writes.

#### What did you see instead?
My Wallpaper, and lost data

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on Manjaro Linux (linux/5.15.57-2-MANJARO) [x86_64]
> using SQLCipher Version 4.5.1 community (based on SQLite 3.37.2)
> and Qt 5.15.4

**Comment by chrisjlocke** [comment]
Have you tried building from the latest source at all?  There have been a few reports of 'crashes' which has been resolved in the latest source.

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
