### ISSUE TITLE
proxy error at startup

### ISSUE THREAD

**Issue by mhechthz** [sqlitebrowser/sqlitebrowser#3118]
### What did you do?

I started the program

### What did you expect to see?

the GUI

### What did you see instead?

an error message, stating that proxy authentication error occurred during proxy access. I don't want DB browser for SQLite to access the internet.

![image](https://user-images.githubusercontent.com/37075144/182413103-21410839-bc38-47be-a202-389e19f8b8ca.png)

After clicking ok, I can work as expected.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
If you click 'OK' to continue past that error, then click 'Edit' (or 'Bearbieten?) and 'Preferences' (or 'Einstellungen'?) then turn off the 'Automatic updates' near the bottom of the list.  Click OK, and that error shouldn't appear again.

**Comment by mhechthz** [comment]
Ok, the entry for "Automatic updates" was at the bottom of the config page and I missed it. Now there is no annoying message. Thank you.

**Comment by chrisjlocke** [comment]
Glad it worked. 😃
