### ISSUE TITLE
Win64  version 3.6.0v3 build fails to run

### ISSUE THREAD

**Issue by mgrandi** [sqlitebrowser/sqlitebrowser#312]
I run the installer for the 64 bit build, and every time I try and run it, it fails to run and shows the following dialog:

![http://i.imgur.com/ZTo3FeK.png](http://i.imgur.com/ZTo3FeK.png)

I am running windows 8.1 64 bit, and the 32 bit installer version works fine

**Comment by ajefferiss** [comment]
Was about to raise this issue myself, the 64bit does the same thing on Windows 7. Likewise, the 32bit version works fine.

**Comment by justinclift** [comment]
Oh, that's not good.  Do you have the (64-bit) version of Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 installed? ([download here](https://www.microsoft.com/en-us/download/details.aspx?id=40784))

**Comment by ajefferiss** [comment]
That was my problem, I had the 2012 64-bit version installed, but not the 2013 version. Works fine after that's been installed on Windows 7.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by mgrandi** [comment]
@justinclift then the installer should definietly be updated to download / include the installer for vcrdst2013, because i'm on the latest 'production' operating system and I didn't have those run time components.

You should be able to include the installer that is on that microsoft website you linked in the windows installer builds, as the license is meant for exactly that.

**Comment by justinclift** [comment]
@mgrandi Yep.  This is a bug on our side from switching to a new build process, and not having things completely worked out yet.  We should have this automatic installed from the next release onwards.

**Comment by rp-** [comment]
next release will fix this.
d99d83f269e4f942e9e3dddba5b417005e4191b7
