### ISSUE TITLE
[Bug]: error changing data no such table: main.

### ISSUE THREAD

**Issue by zoseph-green** [sqlitebrowser/sqlitebrowser#3122]
### What did you do?

-> opened a database with a fts5 table
-> select * from TABLE_NAME where link match 'SOMETHING' limit 25;
-> selected a row
-> couldn't edit
-> clicked 'open in external application' button
-> edited text using external text editor
-> saved in external text editor
-> clicked 'apply' button

### What did you expect to see?

changed data saved...

### What did you see instead?

-> gets: error changing data no such table: main.
![image](https://user-images.githubusercontent.com/103234725/183270419-468cb0ce-68d9-4223-847b-f8e4d4cdac4d.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

11 HOME

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by zoseph-green** [comment]
should i just change table name to main????

**Comment by chrisjlocke** [comment]
We've not had other reports relating to this.
Can you post your schema so we can duplicate your database (sans data) and a copy of your application log so we can see what SQL commands get posted?  

Is this a local database, or something quirky like working across a WSL link?

**Comment by chrisjlocke** [comment]
> couldn't edit

Did you get an error, or just no option to edit?

**Comment by MKleusberg** [comment]
@zoseph-green Can you maybe also provide us the ```CREATE TABLE``` statement of the table you're trying to edit? Feel free to change the table name and all column names, it's the general structure I'm interested in :smile:

**Comment by zoseph-green** [comment]
> > couldn't edit
> Did you get an error, or just no option to edit?

I didn't get ANY error messages. 

> What was the editor?

notepad++

> If you try this again, do you get the same error? Does it occur in another table? On another record?
How big is the database? Is it local or on a network? If you close the database and open it again is it OK? (no such table would mean to me the table has been removed by another process). Have you run an integrity check on the database?

I tried again but nothing lets me edit the rows. I created another fts5 table but alas doesn't let me edit the rows.
Database is very large. about 37 gb. Local database. Closing and opening is fine. The query statements work properly. I have not done an integrity check on the db.

**Comment by zoseph-green** [comment]
> @zoseph-green Can you maybe also provide us the `CREATE TABLE` statement of the table you're trying to edit? Feel free to change the table name and all column names, it's the general structure I'm interested in 😄

db structure is super simple. here is the create table statement:
CREATE VIRTUAL TABLE "store_table" using fts5(link,file)

**Comment by zoseph-green** [comment]
> We've not had other reports relating to this. Can you post your schema so we can duplicate your database (sans data) and a copy of your application log so we can see what SQL commands get posted?

CREATE VIRTUAL TABLE "store_table" using fts5(link,file)
CREATE TABLE "store_table_config"(k PRIMARY KEY, v) WITHOUT ROWID
CREATE TABLE "store_table_content"(id INTEGER PRIMARY KEY, c0, c1)
CREATE TABLE "store_table_data"(id INTEGER PRIMARY KEY, block BLOB)
CREATE TABLE "store_table_docsize"(id INTEGER PRIMARY KEY, sz BLOB)
CREATE TABLE "store_table_idx"(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID

i don't know what you mean by application log

**Comment by chrisjlocke** [comment]
The application log is just the SQL log showing the commands DB4S has issued.

![image](https://user-images.githubusercontent.com/7872218/183612568-600a67fc-a401-4031-b32c-44e7d930332a.png)

If you click 'View' and 'SQL Log' to show the window.

![image](https://user-images.githubusercontent.com/7872218/183612717-f80f40c3-519a-4a14-8caf-5b4215bdccf4.png)

This then has a history of commands.  Sometimes can be useful to show, 'aah, you issued this statement, then that one which put the application in a weird state', etc. Obviously not mega useful without the actual data in the database to simulate what you did, but still helpful.

**Comment by chrisjlocke** [comment]
> select * from TABLE_NAME where link match 'SOMETHING' limit 25;

Was table_name one of the fts5 tables, or another table (not a store_table__something_ table)

**Comment by zoseph-green** [comment]
PRAGMA foreign_keys = '1';
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("store_table");
PRAGMA encoding;
SAVEPOINT "RESTOREPOINT";
select * from store_table where rowid = 74593 LIMIT 253 OFFSET 0;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("store_table");
RELEASE "RESTOREPOINT";

**Comment by zoseph-green** [comment]
> Was table_name one of the fts5 tables, or another table (not a store_table_ _something_ table)

every table name i mentioned here are names of fts5 tables.

**Comment by chrisjlocke** [comment]
Yes - I was just checking if you were trying to edit another table - in your original post, it wasn't explicit which table you were trying to edit.

I can't seem to immediately replicate this.

    UPDATE "main"."store_table" SET "link"=? WHERE "_rowid_"='1'
    UPDATE "main"."store_table" SET "file"=? WHERE "_rowid_"='1'
    RELEASE "RESTOREPOINT";

If you repeated your steps, does it occur again?  Just trying to identify if it was a one-off cough, or consistent.

    UPDATE "main"."store_table" SET "link"=? WHERE "_rowid_"='1'

When you say you couldn't edit the store_table, you said it didn't come up with an error.  So in the 'browse data' tab, if you click on a row and type in a cell, does that edit work?  If you then press [Enter] does the contents 'stick'? (ie, the contents don't revert back to the original value)

![image](https://user-images.githubusercontent.com/7872218/183839819-c7b99aa1-dba9-41bc-81f4-e178160a5935.png)

So here you can see the text caret is in cell 1 and allows me to type freely.

![image](https://user-images.githubusercontent.com/7872218/183840006-c46a396b-e6ed-4095-92c5-bfc6e5aef6ae.png)

In the main application window, I assume it hasn't opened the database read-only?

**Comment by zoseph-green** [comment]
The only table I used is called the store_table and nothing else.

I literally created a new database with a fts5 table (called store_table). 
Inserted a row using the browse data tab (it works this way). The browse data tab allows me to update any row.
BUT, when I try editing ANY CELL WITHIN that row in the execute SQL tab DIRECTLY without DML commands, i can't update the cell within that row i want to update.

This issue has to be a consistent issue and not something that occurs seldomly.

![image](https://user-images.githubusercontent.com/103234725/184069407-719716fc-f954-4de9-a3ba-3a04e6aa0268.png)

SQL LOG:
CREATE TABLE "Temp1" (
	"Field1"	INTEGER
);
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("store_table");
SELECT "_rowid_",* FROM "main"."Temp1" LIMIT 253 OFFSET 0;
SELECT "_rowid_",* FROM "main"."store_table" LIMIT 253 OFFSET 0;
INSERT INTO "main"."store_table"("link","file") VALUES (NULL,NULL);
UPDATE "main"."store_table" SET "link"=? WHERE "_rowid_"='1'
UPDATE "main"."store_table" SET "file"=? WHERE "_rowid_"='1'
select * from store_table LIMIT 253 OFFSET 0;

**Comment by zoseph-green** [comment]
strangely when I try editing with notepad++ and clicked on the apply button within the db browser I get this:

PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
PRAGMA "main".TABLE_INFO("store_table");
SELECT "rowid",* FROM "main"."store_table" LIMIT 253 OFFSET 0;
SELECT "rowid",* FROM "main"."store_table" LIMIT 253 OFFSET 0;
UPDATE "main"."" SET "file"=? WHERE "_rowid_"='1'

the update statement doesn't have "main"."store_table"
this has got to be a bug

**Comment by chrisjlocke** [comment]
Screenshots are a wonderful thing.  Helpful. Thanks for your patience on this.  I know dealing with support can be frustrating - 'why can't they just solve my problem?'

OK.  The 'Execute SQL' tab just does queries, and that pane doesn't let you edit data.  The 'Edit database cell' window isn't valid in this pane.  
What you need is the 'Browse data' tab.  This lets you select a single table and then you can edit data - the 'edit database cell' window will now operate correctly.

Apologies for this confusion, and I can see why it would be confusing.  Guess we really need a 'getting started' guide?

Alternatively, if you use the 'Execute SQL' tab, you should have been able to edit a cell manually - 
    
    update table_store set link='ddd' where link='dd'

etc.

**Comment by zoseph-green** [comment]
hmmm okay thank you for all the help. im closing this thread.

**Comment by chrisjlocke** [comment]
No problem. :)
