### ISSUE TITLE
How can I remove the 'host download.sqlitebrowser.org not found' dialog at startup?

### ISSUE THREAD

**Issue by Hamza1244** [sqlitebrowser/sqlitebrowser#3124]
### What did you do?

How can I remove this advice that shows help me
![IMG_20220723_221228](https://user-images.githubusercontent.com/102913314/183287727-fe60fda3-454c-4d95-be41-f4e25421ef37.jpg)

### What did you expect to see?

How can I remove this advice that shows help me

![Uploading IMG_20220723_221228.jpg…]()

### What did you see instead?

How can I remove this advice that shows help me

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/183289936-05d572be-4aa2-40f1-a91f-06f960c979e7.png)

If you click (1) 'Edit' then (2) 'Preferences', you can turn off the automatic check (3) (which is where this error is coming from)

![image](https://user-images.githubusercontent.com/7872218/183290048-3a682ac5-d39f-428d-8e4c-d03e577277bc.png)

**Comment by Hamza1244** [comment]
@chrisjlocke  thank you
