### ISSUE TITLE
[Feature]: Stable Sort on multiple columns?

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#3126]
### Describe the new feature

I see a discussion of allowing a stable sort for multiple columns in #1407.

Ctl-clicking doesn't seem to be working in version 3.12.2 on macOS 10.15.7. (Ctl-click on the Mac is set up as a right-click: it gives the dropdown menu for the column headings.)

Any thoughts for making this work? Or am I missing something? Many thanks.

### Does this feature exist in another product or project? Please provide a link

See #1407

**Comment by chrisjlocke** [comment]
I believe this is in the nightly.
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

If you want to install that, and give it a go?

**Comment by richb-hanover** [comment]
I did grab 3.12.99  from the nightly builds, but I'm not sure what I'm seeing.

I had hoped that there would be some way to sort the "least significant" column, then the next least, etc. to produce a sorted table

But I have tried combinations of Cmd (on a Mac) and Ctl without seeing what I would like. Thoughts? Thanks.

**Comment by chrisjlocke** [comment]
I can only give you the Windows keys - I don't have a Mac to test it on.
I just tried it in 3.12.2 and it works in there, so apologies - you may not need the nightly after all.  However, the nightly has multiple browse windows, so it's actually a bonus anyway...

![image](https://user-images.githubusercontent.com/7872218/183488527-3a52f02d-682c-4307-b979-07473ad5faf4.png)

In the 'Browse data' tab, if you click 'Ctrl'* while clicking the column heading, then you get little indices after the column name.

(* Unsure what the equivalent is in Mac ... command?)

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@richb-hanover - yell back if you're still having issues.

**Comment by richb-hanover** [comment]
Now that I know how to do it, I can confirm this works with the production version. I made a video to show how it works... See: https://youtu.be/KMowPpzZ2Vc THANKS!

> DB Browser for SQLite Version 3.12.2
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.15.2
> SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).

**Comment by chrisjlocke** [comment]
Glad you got it working, and thanks for posting the video. :)

**Comment by richb-hanover** [comment]
And I blog about this stuff, so I can find my post when I forget how to do it... https://randomneuronsfiring.com/stable-sorting-for-db-browser-for-sqlite/
