### ISSUE TITLE
[Bug]: Assertion [cpMax <= pdoc->Length()] seldomly fails 

### ISSUE THREAD

**Issue by Hook25** [sqlitebrowser/sqlitebrowser#3127]
### What did you do?

When running select queries similar to the following: 
```sql
SELECT * from ... join ...
on ... = ...
where ... = 80
order by ...
```
there is a chance that the application crashes with 
`Assertion [cpMax <= pdoc->Length()] failed at ../scintilla/src/Editor.cpp 6096`

This may be related to old 2021 issues like the following, they seem to point to a different path, but the filename is the same so I suppose this is due to refactoring: 
- https://github.com/sqlitebrowser/sqlitebrowser/issues/2655
- https://github.com/sqlitebrowser/sqlitebrowser/issues/2611
- https://github.com/sqlitebrowser/sqlitebrowser/issues/2591

### What did you expect to see?

The result of the query, an error message or a popup signalling the error

### What did you see instead?

Nothing, the application crashes and prints the assertion error in the console (that I suppose is the default behaviour)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Arch Linux x86_64

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Does this occur in the latest source?  3.12.2 is (relatively) old now and the latest source does contain a number of fixes.
Might be worth having a bash (no pun intended...)

**Comment by chrisjlocke** [comment]
I'll close this as it's been three months without any comment.

**Comment by Hook25** [comment]
If the bug is fixed in the new version this can indeed be closed. Just note: the pacman version of the package is still the old one, I do not know which steps should be taken to update it officially, but we should probably do so. In `3.12.2` this happens pretty often and it makes the software unusable!

**Comment by hujuice** [comment]
The bug is closed but the buggy version (3.12.2) is still the last "stable" version.
What distros should do?
Gentoo Linux here, 3.12.2 is the last version in portage, correctly IMO, even if buggy.

**Comment by chrisjlocke** [comment]
The nightlies are pretty stable, so you can build from source if on Linux.

**Comment by hujuice** [comment]
> The nightlies are pretty stable, so you can build from source if on Linux.

Yes, I can do it, but I will not. I have a package manager and I prefer to follow it.

**Comment by Hook25** [comment]
What exacly is blocking the next stable release? Is there something I can do to take the current nightly version to stable?

**Comment by chrisjlocke** [comment]
Nothing is 'blocking' per se. The build process is in progress.

**Comment by justinclift** [comment]
> What exacly is blocking the next stable release?

We're waiting on some Windows certificate signing stuff from an external crowd.

**Comment by justinclift** [comment]
> I have a package manager and I prefer to follow it.

Understood.  *If* using .AppImages (rather than building from source) is workable, then those are available:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

**Comment by hujuice** [comment]
> > I have a package manager and I prefer to follow it.
> 
> Understood. _If_ using .AppImages (rather than building from source) is workable, then those are available:
> 
> https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

I think it's unclear.
I was digging in an application db. I've found sqlitebrowser useful, but it crashed very often. So i did it with cli. Done.
I didn't say "I don't know how to install a newer version" or "I'm lost without this tool".

sqlitebrowser is a very nice tool, but not the tool of my life.
I hope to find a new version in my package manager soon.
