### ISSUE TITLE
Foreign Key Constrained failed

### ISSUE THREAD

**Issue by frankstrobel** [sqlitebrowser/sqlitebrowser#3132]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.15 (darwin/19.6.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by chrisjlocke** [comment]
The subject looks good, but this issue is lacking in detail.  What did you do, expect and see instead?

**Comment by chrisjlocke** [comment]
Closing due to lack of detail.
@frankstrobel - fee free to comment back with more details and this can be reopened.
