### ISSUE TITLE
[Feature]: Publish to Windows Package Managar (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [sqlitebrowser/sqlitebrowser#3138]
### Describe the new feature

With every new release of sqlitebrowser, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

### Does this feature exist in another product or project? Please provide a link

https://github.com/search?q=vedantmgoyal2009%2Fwinget-releaser+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&s=indexed&o=desc

**Comment by chrisjlocke** [comment]
You're more than welcome to raise a PR.  I believe there is also releases on Chocolatey (a better package manager and been around for longer) albeit not the nightlies.
