### ISSUE TITLE
[Feature]: include row count beside table name in dropdown in Table Browser

### ISSUE THREAD

**Issue by neomafo88** [sqlitebrowser/sqlitebrowser#3144]
### Describe the new feature

It would be super handy to be able to know the number of rows in a particular table, instead of e.g. switching over to the SQL tab after executing "Show Row Counts", so that empty tables can be skipped over quickly

I've tried to understand the Qt codebase in order to implement this functionality for myself without success

tried the following variants, but kind of stuck due to unfamiliarity, so if anyone is able to help, would be great

DbStructureModel.cpp:

```
if(index.column() == ColumnName && item->parent() == browsablesRootItem)
{
  QString N = QString::number(123);

  QString sql = QString("SELECT COUNT(1) FROM %1").arg(
    sqlb::escapeIdentifier( item->text(ColumnName) )
  );

  QString N = QString::number(m_model->rowCount());

  QString N = QString::number(rowCount(index.parent()));
  return item->text(ColumnName) + " " + "(" + N + ")";

  // return QString::fromStdString(sqlb::ObjectIdentifier(item->text(ColumnSchema).toStdString(), item->text(ColumnName).toStdString()).toDisplayString());
}
```

### Does this feature exist in another product or project? Please provide a link

I believe Magnet AXIOM and/or Cellebrite PA

### Do you have a screenshot? Please add screenshots to help explain your idea.

![](https://user-images.githubusercontent.com/97744946/185493320-15e15d0f-bb90-4d27-b9f2-280ce23dbef9.png)

**Comment by neomafo88** [comment]
✅ nvm, implemented it myself already

![screenshot](https://user-images.githubusercontent.com/97744946/185752653-4bdd536d-9037-45de-b43b-752153cc7303.png)

**Comment by chrisjlocke** [comment]
If you're OK with it, you're more than welcome to submit a PR to have this code included in the application.  Get your name in lights (well, a credit) and have that warm fuzzy glow.

**Comment by neomafo88** [comment]
not receiving any near-immediate response/pointers over the weekend, I thought this code repository was pretty much dead/inactive now … apparently not?

sure, I'll be happy to oblige, though it might take 1-2 more weekends to cleanup/minify (as in reduce my changes to the minimum required to implement said feature)

in the meantime, before that happens:

- I would like to highlight that my feature implementation probably does not work for SQLCipher-encrypted SQLite databases
- I initially tried doing `size_t numRecordsTotal = db->querySingleValueFromDb("SELECT COUNT(1) FROM <TableName>;").toUInt();` within `TableBrowser::setStructure()`, but it wasn't "as nice" - it would result in `numRecordsTotal` being equal to 0 at first, then populate with the correct row count afterwards
- So, I decided to `sqlite3_open`/`sqlite3_prepare_v2`/`sqlite3_step`/`sqlite3_column_int`/`sqlite3_finalize` within `DbStructureModel::buildTree()` instead
- I'm guessing this is probably not the "canonical" way of implementing the feature, so the admins in charge of managing this code repository will likely have to take over the code to refactor it so that it is consistent with the original design principles etc.
- The _only_ documentation meant for developers interested in extending this that I could find was [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Source-code-highlights), which is kind of disappointing, and pretty much useless in attempting to code a feature that aligns with the "theme". The comments embedded in the source code helps slightly, though

While working on this, I also fixed another "bug" I discovered, at least something I found jarring, usability-wise. Will create another issue shortly and link to it here, so as to maintain the laser focus of this issue

**Comment by chrisjlocke** [comment]
> not receiving any near-immediate response/pointers over the weekend, I thought this code repository was pretty much dead/inactive now 

There is only a small number of developers who care to maintain DB4S (while I'm good at VB .NET, I know little about C++) and as is usual, 'real life' gets in the way of development.  DB4S isn't dead, but just put on the 'back burner'. ;)
