### ISSUE TITLE
Database which makes use of the STRICT keyword can not be opened 

### ISSUE THREAD

**Issue by GrumpyLittleTed** [sqlitebrowser/sqlitebrowser#3145]
### What did you do?

A database which makes use of the STRICT keyword can not be opened at all in the current nightly build: the message says that the database is corrupt. This did not happen in the older releases e.g. 3.11 complains but continues.

create table t (
  x integer not null
) strict;

### What did you expect to see?

The database would open even if it doesn't like the strict keyword

### What did you see instead?

A message saying that the database is corrupt

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 21.04

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Have you created a normal database and that opens OK?
I just downloaded the latest Windows binary (9 Jul 2022), created a new database, entered your SQL you put above, saved it, closed it and it opened fine.
I wouldn't have thought a recent commit would have broken this functionality.
Is there any chance you can revert to an earlier build just to rule that out? (ie, build from a different commit?)

**Comment by GrumpyLittleTed** [comment]
I reran my test using version 3.12.2 from the Debian PPA.
Without STRICT it works fine, with STRICT (code above) I get the message:

_Could not open database file.
Reason: malformed database schema (t) - near "strict": syntax error_

**Comment by chrisjlocke** [comment]
For the avoidance of doubt, can you do a `select sqlite_version()` in the execute SQL tab?
We're looking for a version of SQLite > 3.37.0
At least that'll rule that out.  
On my system, 3.12.2 gives SQLite version 3.35.5 ... so looks like SQLite is ignoring it.  
Just tried using that version, and while it doesn't report an error, it can't parse the schema properly - the column is blank.

![image](https://user-images.githubusercontent.com/7872218/187063728-a4dc7067-0824-4f80-b072-94a6e59aeb22.png)

So, you might be using the latest version of DB4S, but it's finding an older version of SQLite?

**Comment by GrumpyLittleTed** [comment]
Sqlite_version() is 3.39.2

**Comment by c9845** [comment]
I have been dealing with this as well.

I replaced the 3.35.5 sqlite3.dll (that came with DB Browser v3.12.2) on my system (Windows 10) with the 3.39.4 .dll from SQLite source.  I can get my database to open in DB Browser.  

However, table columns do not display in "Database Structure" under each table, "Modify Table" does not list any columns, and "Modify Table" shows "Warning: There is something wrong with this table definition that our parser doesn't fully understand...".  Columns and data are listed, though, in "Browse Data" and can be queried in "Execute SQL".  So, at least from what I can tell, a database with `STRICT` tables can be open and main issue is GUI handling of `STRICT` tables in the "Database Structure" tab.

**Comment by chrisjlocke** [comment]
@c9845 - As per my comment above - you have to change DB4S and the sqlite3.dll - the newer code has newer code in it which understands the data from the newer sqlite3.dll.
Have you tried the nightly at all?
Can you email me the database you're using?  db4s.issue3145 [at] chrisjlocke [dot] co.uk (you can delete the data ... its just the schema I'm after).

**Comment by c9845** [comment]
@chrisjlocke I did not try nightly.  I totally blanked on that!  Let me give it a try a bit later.

**Comment by MKleusberg** [comment]
Closing this issue as it's been fixed some time ago. The changes are available in the nightly builds [here](https://nightlies.sqlitebrowser.org/latest/). Feel free to reopen this issue if any problems remain :smile:

**Comment by justinclift** [comment]
We've begun internally discussing doing our next release.  Likely to be *at least* a few weeks away though.

**Comment by audunms** [comment]
Is this still an issue? I face the same problem with Version 2.0b1 and SQLIte version 3.6.18

**Comment by FriedrichFroebel** [comment]
Where did you get version 2.0b1 from? The latest nightlies of DB4S should fix this issue.

**Comment by justinclift** [comment]
> I face the same problem with Version 2.0b1 and SQLIte version 3.6.18

That's a *super* outdated version of the application.  By more than a decade I think (without checking).

What operating system are you using, and which version of it? :smile:

**Comment by audunms** [comment]
Hi, thanks for the prompte feedback. I had an old version in the backup folder on my computer, and after installing the new version, my Windows 11 did only find this old version when I searched for sqlite to find an open the program. 

Understanding what the problem was, thanks to your replies, I actually had to manually navigate to the folder where DB Browser for SQLite was installed and run the application. Thanks and sorry for noticing I was running on an old version!

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by audunms** [comment]
Anyways, when is a newer version coming? I am only able to install the latest regular version to due company policies, and this version (3.12.2) seems not to support STRICT.

**Comment by justinclift** [comment]
Ahhh.  The next version is pretty much ready to go.  We even have preliminary builds available for it (https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.x-rc1).

The builds there are fine for macOS and Linux users.  But for Windows the builds still need to be signed using a proper "certificate", otherwise Windows gives warnings about things coming from an unknown developer.

We're in the process of getting that signing bit done, but we're waiting on an external crowd and it's probably going to be weeks rather than days. :facepalm:
