### ISSUE TITLE
How can you change the language DB Browser for SQLite uses?

### ISSUE THREAD

**Issue by yusefAlmouhamad** [sqlitebrowser/sqlitebrowser#3146]
how to change sqlite browser language

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/185663434-e2437449-acef-471c-bf54-2dd9f9bc2434.png)

Click 'Edit' and 'Preferences'


![image](https://user-images.githubusercontent.com/7872218/185663532-58eaeb59-4be1-44ef-a92c-6547b87dc93f.png)

The language option is the second option on the General (first) tab.

**Comment by chrisjlocke** [comment]
Closing as no response.
@yusefAlmouhamad - reply back if this doesn't help or you require more information.
