### ISSUE TITLE
V 3.6.0 does not remember last-used folder

### ISSUE THREAD

**Issue by rickshory** [sqlitebrowser/sqlitebrowser#315]
I believe I tested this well enough to be sure. Started browser, opened a DB, closed browser. On next start, browser went back to looking for DBs in generic user folder. Since I mostly use the browser to do quick checks on previously-opened DBs, this is a usability drop.  I uninstalled the latest version and re-installed the previous, so I do not have version 3.6.0 to test further.

**Comment by glawrence** [comment]
This has come up a few times with 3.6.0 and also earlier than that. The nightly builds have some updates in. So I would suggest either using them or go to 3.6.0 and use the "Most Recently Used" database on the file menu. Which sounds like it might work better for you.

**Comment by justinclift** [comment]
@rickshory The directory which is opened can be set in the Preferences.  But yeah, it's a popular request, and one we're considering how best to do. :smile:

For further reference, please see: https://github.com/sqlitebrowser/sqlitebrowser/issues/281, https://github.com/sqlitebrowser/sqlitebrowser/issues/276, https://github.com/sqlitebrowser/sqlitebrowser/issues/224.

**Comment by MKleusberg** [comment]
This should be fixed in the 3.7.0 release where we've introduced a new option to the Preferences dialog to change this behaviour. This way everybody should be happy :smiley:
![lastlocation](https://cloud.githubusercontent.com/assets/3153504/8273318/9c697f04-1868-11e5-9791-7dce9ff25cfe.png)
If there are no objections I think we can close these issue soon.

**Comment by justinclift** [comment]
Good thinking @MKleusberg. :smile:

@rickshory Have you had a chance to try out the new behaviours in our recent 3.7.0 release? :smile:

**Comment by MKleusberg** [comment]
Closing this as it's been reported to work in issue #276. If there still should be any problems with this feel free to re-open the issue or open a new one.
