### ISSUE TITLE
[Bug]: Fonts got tiny due to remote Windows server update? 

### ISSUE THREAD

**Issue by MilindGandhi** [sqlitebrowser/sqlitebrowser#3153]
### What did you do?

In AWS there was windows server 2016 update, I allowed it to happened. The AWS was restarted. Note that in remote AWS instance, we can't change the display size.

### What did you expect to see?

The font size should be regular as it was before the remote server update.

### What did you see instead?

After that DB browser's font size became too small as here:
![image](https://user-images.githubusercontent.com/9047592/186325764-d46a0300-8a3d-48c6-9e18-3bd365f78d38.png)

Have described this problem in detail here: [How to fix the font sizes of DB browser for sqlite, which got tiny due to remote Windows server update?](https://superuser.com/questions/1738530/how-to-fix-the-font-sizes-of-db-browser-for-sqlite-which-got-tiny-due-to-remote)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows server 16

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
"By trial and error method, I was able to solve the issue by clicking "Restore Defaults" at the bottom left!!"

I'll close this as completed then.
Bit weird how that solved the issue, but glad it did.
