### ISSUE TITLE
Outil/Extension

### ISSUE THREAD

**Issue by J-Lacerte** [sqlitebrowser/sqlitebrowser#3158]
Est-il possible d'avoir un exemple pour créer une extenstion (créer des COLLATION)?

**Comment by chrisjlocke** [comment]
"‎Is it possible to have an example to create an extenstion (create COLLAs)?‎"

I've never created an extension, but assume you're doing this in C or C++?
Might be worth asking on the SQLite forum as they're a bunch of nerds over there who love doing that stuff.
https://sqlite.org/forum/forum

**Comment by J-Lacerte** [comment]
Merci, J'ai trouvé mon erreur. N'était pas compilé en x64!
(je dois utiliser x64 Native Tool Command Prompt for VS et non pas x64_x86 Cros Tools...)

**Comment by chrisjlocke** [comment]
> reopened this [4 hours ago](https://github.com/sqlitebrowser/sqlitebrowser/issues/3158#event-7307523050)

I'm not sure there is much we can offer in the way of support?

**Comment by J-Lacerte** [comment]
/*
** 2022-09-01
** Par Jacques Lacerte
** doit être compilé en x64
** J'ai utlisé VS2022 --> la commande "x64 Native Tools Command Prompt for VS 2022"
** et compiler comme suit:
** cl myCollations.c -link -dll -out:myCollations.dll
**
**

*/
#include "sqlite3ext.h"
SQLITE_EXTENSION_INIT1
#include <assert.h>
#include <string.h>


#ifdef _WIN32
__declspec(dllexport)
#endif
int sqlite3_extension_init(
  sqlite3 *db, 
  char **pzErrMsg, 
  const sqlite3_api_routines *pApi
){
  int rc = SQLITE_OK;
  SQLITE_EXTENSION_INIT2(pApi);

  (void)pzErrMsg;  /* Unused parameter */
  rc = sqlite3_create_collation(db, "LOCALE_NOCASE", SQLITE_UTF8, 0, myCompare);

  return rc;
}
