### ISSUE TITLE
[Bug]: Latest nightly doesn't work on macOS

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#3159]
### What did you do?

I wanted to download the latest macOS nightly. The README directed me to https://nightlies.sqlitebrowser.org/latest/

I downloaded that file, but saw a "slashed circle" on the DB Browser for SQLite icon when I opened the .dmg file.

So I rummaged around for a different file and ultimately got to https://nightlies.sqlitebrowser.org/osx/2022-07/ where I saw a discontinuity in file size between 21 & 22 July 2022. (see below)

I was able to download the version from 21 July and it works fine.

```
...
DB Browser for SQLite_20220721.dmg                21-Jul-2022 00:08            16599269
DB Browser for SQLite_20220722.dmg                22-Jul-2022 00:05             1867899
...
```

### What did you expect to see?

I expected that the latest nightly would work on macOS

### What did you see instead?

see above

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

MacOS

### OS version

10.15.7

### Relevant log output

```shell
none
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Thanks for reporting.
This would tie up (I think) with the Windows nightlies being broken too.  We're in the midst of fixing this, so theoretically once that has been resolved, it might similarly fix this (assuming it's a rogue commit that's farted somewhere).

**Comment by chrisjlocke** [comment]
Aah, just saw the sqlCipher version has a healthier file size.
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

Could you try that one?  It's the same codebase, but just has sqlCipher support in it.  It doesn't mean your databases will be encrypted, etc - it just adds that support if needed.

**Comment by richb-hanover** [comment]
Yes, I found and tried the sqlcipher branch to see if stable sort worked (IT DOES!) before testing the production branch.

Also: I note that there doesn't seem to be a 2022-08 directory for any of the builds in win64 or osx. Is that intended? 

In any event, thanks for a terrific tool!

**Comment by chrisjlocke** [comment]
Yes, the directories are created manually, and I haven't gotten around to moving the files (that aren't broken, at least) into their 'archive' directories. :)

![image](https://user-images.githubusercontent.com/7872218/187693345-500fe395-d037-4513-a228-1b41c4a82a54.png)

**Comment by richb-hanover** [comment]
Actually, I submitted that last note (about the 2022-08 directory) in the spirit of my company's unofficial motto:

> We promise not to fix it if we don't know it's broke.

**Comment by justinclift** [comment]
As a data point, today I've been setting up a new macOS (intel) VM on newer (temporary) hardware.  Just to figure out why our macOS builds are busted after that CMake change a while back.

What *seems* to be happening, is CMake is now finding and using the SQLite library that's part of macOS the "Command Line Utilities" package.  Rather than the SQLite library we compile and install ourselves.

The right approach will probably be to somehow point CMake to the right SQLite install.  After which the builds should work again.

I'll pick this up again in the morning, as it's early am now and I'm supposed to be recovering from getting sick. :frowning:

**Comment by justinclift** [comment]
Oh, there's a new SQLite point release (3.39.3) yesterday too, so I'll update things with that once the builds are working again.

**Comment by justinclift** [comment]
Got the standard SQLite nightly build compiling again for macOS.  Looks like the Apple developer certificate that's used to sign it has expired, so I'm updating the macOS version on the VM then will generate new macOS Dev certificate.

With *those* done, we should have working nightly builds again. :smile:

**Comment by justinclift** [comment]
No worries at all.  The macOS VM is running on an ancient Intel based Mac Mini, so is very slow.  It's finally finished upgrading macOS from Mojave to Monterey (3 hours, heh!), and Xcode is presently downloading.  Hopefully it'll all work ok. :smile:

**Comment by richb-hanover** [comment]
A (barely-related) thought re: standard vs sqlcipher builds...  The sqlcipher build seems to be only slightly bigger: 18mbytes vs 16mbytes. Is that size savings worth the additional hassle of maintaining two builds? (Is there anyone who'd complain if you only shipped the sqlcipher version?) Thanks.

**Comment by richb-hanover** [comment]
And another random neuron fires: Instead of a Mac mini, perhaps you could use a Docker instance. A quick Google search nets this: https://github.com/sickcodes/Docker-OSX

([I have recently learned about Docker,](https://randomneuronsfiring.com/more-fun-with-docker-tooling/) so everything looks like an application. And when I hold a hammer, everything looks like a nail... :-)

**Comment by justinclift** [comment]
It's a reasonable thought, but Apple licensing requires macOS to be running on Apple hardware.  For just general mucking around, I wouldn't be too bothered... but for a semi "production" system that we're building our releases on, it's probably best to keep things licensed ok. :wink:

If you're meaning "Run it in a Docker container on the Mac Mini"... then nope.  Docker on macOS actually runs Linux in a VM behind the scenes, then runs the Docker containers inside that.  Performance isn't very good at all.  Used to do that as part of previous $dayjob, so know first hand. :smile:

**Comment by justinclift** [comment]
> Is there anyone who'd complain if you only shipped the sqlcipher version?

Yep.  We do get asked to include the very newest SQLite releases, as people want to use the latest and greatest features not long after they come out. :smile:

**Comment by richb-hanover** [comment]
Good responses to both questions. (I suggest 'em, not knowing the implications of what I'm asking.) Thanks for listening.

**Comment by justinclift** [comment]
No worries at all, it's all good. :smile:

**Comment by justinclift** [comment]
k, this is an initial go at getting the macOS (Intel only, not M1/M2) nightly builds working again.  Is anyone up for testing these to check if they work from their point of view?

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite.dmg
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

**Comment by chrisjlocke** [comment]
@richb-hanover - Did you want to test the latest nightly at all?

**Comment by richb-hanover** [comment]
Both the DB.Browser.for.SQLite and DB.Browser.for.SQLite-sqlcipher downloads give a `.dmg` that opens to a window like this. 

Is it intentional that this version requires macOS 12? (I'm using 10.15.7 - Catalina). Thanks

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1094930/194120907-0e87a322-a343-4b62-9073-d138c3afe122.png">

**Comment by justinclift** [comment]
Ahhh, that's really useful.  The current nightly build process runs on a system that was upgraded to Monterey.  Looks like that was a mistake, and we should have left it running on Catalina or Big Sur.

If I put some time into changing it over to build on Big Sur, would you be ok to test if that works on your Catalina system?  Bear in mind that (according to [Wikipedia](https://en.wikipedia.org/wiki/MacOS_Catalina)), Catalina is no longer supported by Apple.

**Comment by justinclift** [comment]
Hmmm, I've give Catalina a go first and lets see if enough things still work for nightly builds to be functional.

**Comment by justinclift** [comment]
> One of my rules as a developer is not breaking backward compatibility.

Yeah, I fully agree personally.  Just wish Apple gave a shit about what we think too. :wink:

I've rebuilt the system using Catalina today, and it's building new macOS nightlies now.  Updated the SQLite one to use the new SQLite 3.39.4 release too.

In theory, they should be available for download in the usual spot in about 20 mins.

Btw, I'm aware the icon for the application is busted.  Someone reported it's due to a missing plist entry to point at the icon file.  I'll take a look at this later (eg not now). :smile:

**Comment by richb-hanover** [comment]
(Partial) Good News! 
The latest nightly build for macOS (07-Oct-2022 17:03) works just fine, except for the icon. Thank you!

```
DB Browser for SQLite Version 3.12.99 (Oct  8 2022)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.2
SQLite Version 3.39.4.
```

**Comment by richb-hanover** [comment]
> Yeah, I fully agree personally. Just wish Apple gave a shit about what we think too. 😉

It has been a couple decades since I built an OSX-native app so I'm no longer up to speed on the macOS ecosystem. I wonder if the Monterey (macOS 12) xcode version has a flag/option that says something to the effect of, "only build for current OS versions..."

**Comment by justinclift** [comment]
Just updated the macOS nightly build script, so the icon files are correct in the nightly builds.  I'll update the M1 mac builds in a few hours too.

**Comment by richb-hanover** [comment]
I checked the nightly build just now, and can confirm that the icon looked good and that the program operated as expected on macOS 10.15.7. Thanks!

**Comment by richb-hanover** [comment]
From: https://nightlies.sqlitebrowser.org/latest/ I can confirm that both:

* DB.Browser.for.SQLite-intel.dmg
* DB.Browser.for.SQLite-sqlcipher-intel.dmg

create a good DMG file, the icon looks good, and that the app's seem to function (open an existing SQLite file)

**Comment by justinclift** [comment]
Thanks @richb-hanover, that's good confirmation. :smile:
