### ISSUE TITLE
Delete the line of the plot.

### ISSUE THREAD

**Issue by kropochev** [sqlitebrowser/sqlitebrowser#316]
Add the ability to build a plot of the points only.

**Comment by justinclift** [comment]
@kropochev That's kind of unclear.  Do you have time to make that clearer?  Maybe a picture/graphic to show what you mean? (it does not have to be a high quality picture.  Even Microsoft Paint would be ok. :smile:)

**Comment by schdub** [comment]
@kropochev, something like this?
![plot only points](https://cloud.githubusercontent.com/assets/1304776/7705684/5dfb0b40-fe4e-11e4-88db-6b837fff5b1b.png)
Same plot with lines between points:
![plot std](https://cloud.githubusercontent.com/assets/1304776/7705700/7b82a344-fe4e-11e4-84c8-ef5a8f07fada.png)

**Comment by kropochev** [comment]
Yes exactly

**Comment by schdub** [comment]
@justinclift, we can add two ComboBoxes with 'Line type' and 'Point shape', when first item is 'None', for example. What do you think?
![screenshot from 2015-05-19 18 08 40](https://cloud.githubusercontent.com/assets/1304776/7706475/51037b16-fe53-11e4-836c-463c8aab6d62.png)

**Comment by justinclift** [comment]
@schdub That sounds like a really, really good idea.  Are you ok to commit it? :smile:

**Comment by schdub** [comment]
@justinclift, done.
Please somebody review #317.

**Comment by justinclift** [comment]
@kropochev The code to make this happen has been review and added to the project.  Would you be ok to try the latest code to verify it works how you want?

If you're using Windows or MacOS X, there will be a new "nightly" build you can try tomorrow.  Download locations are shown on our front page. :smile:

**Comment by kropochev** [comment]
Checked version of mac and win. In the version for the win chart with points at the vertices displayed incorrectly.
![win_dot](https://cloud.githubusercontent.com/assets/8565494/7750631/c417298a-ffee-11e4-8109-993f245ba8cd.PNG)
A mac version correctly.
![mac_dot](https://cloud.githubusercontent.com/assets/8565494/7750671/ef708d9c-ffee-11e4-8943-5910d1e906f4.png)
Implemented great, thank you very much.
Bus stops in my town.
![mac_disc](https://cloud.githubusercontent.com/assets/8565494/7750723/404b6606-ffef-11e4-8818-cedbd6f3e2eb.png)

**Comment by schdub** [comment]
@kropochev, are you sure data set on windows and mac is equal (it appears on the image there are gray dots)?
What happens if you choose point shape Disk on windows build?
Could you please send me the database to test?

**Comment by kropochev** [comment]
@schdub, yes, data is equivalent. [DB](https://dl.dropboxusercontent.com/u/2957764/Gortrans.db)
If choose point shape Disk on windows build, plot displays similar mac build.

**Comment by schdub** [comment]
It looks like troubles with drawing dots in qcustomplot library on Linux and Windows platforms.
Wrote to the author with proposal how to fix this.

**Comment by justinclift** [comment]
@schdub Is there a PR for it which we can watch? (if the qcustomplot stuff is on GitHub)

**Comment by rp-** [comment]
maybe its already fixed? we don't use the latest version

**Comment by schdub** [comment]
@rp-, I've already check, but not. Btw, can I add new version (1.3.1) this library into our repo?
@justinclift, no, only support email.

**Comment by rp-** [comment]
sure, but maybe wait a few days, if the guy from qcustomplot can fix it quick, he might release a new version.

**Comment by schdub** [comment]
@rp-, he told me that this isn't a problem in his library, but the problem in some versions Qt.

Problem code, I think is:

    case ssDot:
    {
        painter->drawLine(QPointF(x, y), QPointF(x+0.0001, y));
        break;
    }

If replace it with something like:

    case ssDot:
    {
        painter->drawPoint(QPointF(x, y));
        break;
    }
everything is fine.

I think the easiest way to deal with this problem is to delete ssDot from list of supported point shape.

**Comment by rp-** [comment]
sounds good enough for me

**Comment by justinclift** [comment]
Yep, sounds like a good plan @schdub. :smile:

**Comment by schdub** [comment]
ssDot displaying problems have been solved in #324.
I think we can close this issue.
@justinclift, can we?

**Comment by justinclift** [comment]
Sure. :smile:
