### ISSUE TITLE
Message stuck on screen

### ISSUE THREAD

**Issue by CodeByLine** [sqlitebrowser/sqlitebrowser#3167]
Can't dismiss the popup window with this message: "DB Browser for SQLite" would like to access files in your Document folder.

Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/21.6.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by justinclift** [comment]
Ouch, that's weird.  That sounds like a dialog that macOS is giving, so it can load your database files.

When you say "can't dismiss", is that even with trying every option?  It's not totally clear if you're trying to get past the option by skipping it, agreeing to it, or whatever.

Am thinking that it *should* (in theory) go away if you agree to it.  But if you're trying to skip it then macOS is probably going to complain or something. :shrug:

**Comment by scottfurry** [comment]
@CodeByLine - This is a Mac OS dialog ensuring that you the user are allowing another program to access your files. This is a security function of Mac OS. It should not be "dismissable" as the user is expected to explicitly give this permission.

See here for more info:
https://support.apple.com/en-ca/guide/mac-help/mchld5a35146/mac
https://developer.apple.com/forums/thread/127789

**Comment by chrisjlocke** [comment]
I'll close this as it doesn't seem like a fault directly in DB4S.  You can continue to comment though, and should we need to do anything, it can be reopened.
