### ISSUE TITLE
[Bug]: Crash opening table

### ISSUE THREAD

**Issue by Samega7Cattac** [sqlitebrowser/sqlitebrowser#3170]
### What did you do?

Opened a sqlite database and tried to modify a table

### What did you expect to see?

Window to modify the table

### What did you see instead?

crashes

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Arch Linux

### Relevant log output

```shell
/usr/include/c++/12.1.0/bits/basic_string.h:1292: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&]: Assertion '!empty()' failed.
Aborted (core dumped)
```
```


### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by Samega7Cattac** [comment]
Found issue https://github.com/sqlitebrowser/sqlitebrowser/issues/2779 but was for fedora
This happened since last update

**Comment by Samega7Cattac** [comment]
Downgrading from version 3.12.2-2 to version  3.12.2-1 makes it work again
Issues with the AUR package?

**Comment by Samega7Cattac** [comment]
Created a package bug report: https://bugs.archlinux.org/task/75921

**Comment by chrisjlocke** [comment]
This seems the same as this error.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3069

Building from the latest source seems to work.

**Comment by chrisjlocke** [comment]
Have you tried building from the latest source at all?

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.

**Comment by Ombrelin** [comment]
Juste encountered the same error. Crash on trying to modify table structure.  
  
Logs : 

```
/usr/include/c++/13.2.0/bits/basic_string.h:1317: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&]: Assertion '!empty()' failed.
```

OS : Ubuntu 22.04 LTS.  
Version of the software 3.12.2

**Comment by chrisjlocke** [comment]
3.12.2 is quite old now.  Have you tried using the latest source from the appImage?
"we do provide an AppImage for Linux in our continuous builds, so the next time you need a nightly build, you can run it directly through the AppImage instead of building from source: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous"

**Comment by Ombrelin** [comment]
I installed from flatpak, and by looking quickly in the release page I though 3.12.2 was the latest.
Thanks I will give it a try :+1:

**Comment by chrisjlocke** [comment]
3.12.2 is the latest 'official' release, but we also do 'nightly' versions which are generally 'work in progress' versions.  However, the nightly is currently relatively stable and contains a years' worth of fixes and updates.
