### ISSUE TITLE
[Bug]: App Crashes on Endeavour OS (Arch Linux) when typing SQL Queries

### ISSUE THREAD

**Issue by LordSicarious** [sqlitebrowser/sqlitebrowser#3172]
### What did you do?

Open database, open the "execute SQL" tab, begin typing a query. The issue appears to be independent of any particular query and can be triggered by simply holding down a single letter key for a few seconds.

### What did you expect to see?

The query continues to appear in the text window.

### What did you see instead?

The app crashes after a seemingly random number of characters are typed in. Launching through the terminal indicates a potential memory allocation error.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Endeavour OS Linux 22.9

### Relevant log output

```shell
[sic@sic-pc ~]$ sqlitebrowser
free(): invalid pointer
Aborted (core dumped)
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
There are a number of open issues about crashing on Linux, which are resolved by building from the current source, for example, https://github.com/sqlitebrowser/sqlitebrowser/issues/3069.

**Comment by chrisjlocke** [comment]
Have you tried building from the latest source at all?

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
