### ISSUE TITLE
How to setup Command line interface and use it to export a database to SQL script?

### ISSUE THREAD

**Issue by jacattrongnlh** [sqlitebrowser/sqlitebrowser#3174]
I'm using Mac Monterey. I see this section in the doc https://github.com/sqlitebrowser/sqlitebrowser/wiki/Command-Line-Interface but I don't see how to setup to be able to use the command line.

I want to automate the process of exporting database to SQL script. Is there a way to use CLI to export a database to SQL script?

**Comment by chrisjlocke** [comment]
There are no command-line options that export the database to SQL.
The only thing would be a program that simulated keystrokes, for example, on Windows is a program called AutoIT.  I assume a similar program exists on Mac.

**Comment by jacattrongnlh** [comment]
Thanks for the reply.
I will look into how to export database to SQL some other way.
There's still the problem with setting up command-line interface for Mac. It would be helpful for future visitor if you can provide information on how to get DB Browser's CI running on Mac.

**Comment by chrisjlocke** [comment]
From a terminal, can you not run ./"db browser for sqlite.dmg" /option /option 
(in the directory that program exists)

I'm not a Mac user, but that's the general principle?

**Comment by jacattrongnlh** [comment]
> From a terminal, can you not run ./"db browser for sqlite.dmg" /option /option
/option? Isn't it -option? Like -h for help and -t for table. I just want to make sure we are on the same page.

Running the command doesn't work
DB.Browser.for.SQLite-3.12.2.dmg -h
zsh: command not found: DB.Browser.for.SQLite-3.12.2.dmg

**Comment by scottfurry** [comment]
`.dmg` is the extension of an install disk on MacOS. You want to execute file with the extension `.app`.

For basic command line execution on an sqlite db there is also its command line interface `sqlite3`. This is the underlying database library for all sqlite. It should already exist on system but may not be at the same revision as DB4S nor include SQLCipher. If you open the terminal app execute `sqlite3 --version` you should get back current installed version.

If you want latest/bleeding edge, explore [Homebrew installs](https://wpbeaches.com/installing-homebrew-on-macos-big-sur-11-2-package-manager-for-linux-apps/).

From the sqlite command line interface you can create/alter/delete/add tables and data to an sqlite3 database. See [here](https://www.sqlite.org/cli.html) for more details.

**Comment by chrisjlocke** [comment]
I'll close this as its 'sort of' resolved - as best we can.
