### ISSUE TITLE
[Bug]: App crashes on Manjaro Linux when click to modify a table

### ISSUE THREAD

**Issue by rafidalhaque** [sqlitebrowser/sqlitebrowser#3175]
### What did you do?

1. Create table with some columns.
2. Click **write changes**.
3. Select the table I wrote.
4. Click **modify table**
5. App crashed.

### What did you expect to see?

I expect to see a dialogue box to modify the table.

### What did you see instead?

I saw the app crashed.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Manjaro 22.0.0

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Not certain, but building from the latest source may fix this issue. See https://github.com/sqlitebrowser/sqlitebrowser/issues/3069

**Comment by agomez225** [comment]
> Not certain, but building from the latest source may fix this issue. See #3069

Yup, this fixed it for me. Thanks!

**Comment by chrisjlocke** [comment]
Thanks for reporting back. 👍
