### ISSUE TITLE
[Bug]: Reported row counts are off-by-one

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#3176]
### What did you do?

Using 3.12.2 on macOS 10.15.7:

> DB Browser for SQLite Version 3.12.2
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.15.2
> SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).

The reported row numbers are off-by-one from what is shown in the window. See the image below:

_(note - everything seems to be working fine - it's just a display/reporting bug.)_

![image](https://user-images.githubusercontent.com/1094930/191342277-2a9764fb-558b-46ed-9043-dac0f51fa7f4.png)

### What did you expect to see?

I expected that the legend in the lower left would say:

* 1-19 of 388
* 370-388 of 388

### What did you see instead?

See the image

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

10.15.7

### Relevant log output

```shell
n/a
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
I believe the 'how many rows is visible?' is done by calculating the height of the window divided by the height of a row.  Unfortunately, just like 0.1 can't be represented properly, there is some wacky rounding error where the result is 18.9999 rather than 19.1, so its calculated as 18.  Is the application full-screen, or can you resize the window?

Have you tried the latest nightly at all?
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-sqlcipher.dmg

**Comment by scottfurry** [comment]
@chrisjlocke - not forcing/casting the math to use integer values?

**Comment by chrisjlocke** [comment]
I'm only guessing.  I haven't looked at the code.  I seem to remember this issue from a while back, but thought it got fixed.

**Comment by richb-hanover** [comment]
> I believe the 'how many rows is visible?' is done by calculating the height of the window divided by the height of a row.

Yes - I'm quite familiar with the problem, having implemented  different solutions in previous lives. Perhaps my favorite was to force the window size to be an integer number of lines tall(!) After it's resized, we just re-drew the window with a height that fit N rows exactly. No one was the wiser.

Then, with an integer number of rows showing, it'll be straightforward to display the proper information about the lines that are visible. Thanks!

**Comment by mgrojo** [comment]
@richb-hanover, I've fixed this problem, at least for my platform and Qt version. Could you try the next [nightly version](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) and confirm it also works for you?

**Comment by richb-hanover** [comment]
In a one-of-one test, the row count error appears to be fixed (macOS Ventura 13.5) Thanks!

I'll note that the nightly builds are available at this link: https://nightlies.sqlitebrowser.org/latest

@justinclift @chrisjlocke I'll also note that the nightly builds do not work on macOS 12.6. (They require Monterey...) Is this intended? I asked about this in #3159 for an earlier version of DB4S and macOS...

**Comment by lucydodo** [comment]
> I'll also note that the nightly builds do not work on macOS 12.6.

Hi @richb-hanover Thanks for reporting this.
I believe this was caused by an update to the macOS version that runs the nightly builds, I've confirmed it can run on Monterey with some build configuration and added the relevant commits, a build is currently underway. Please be patient.

**Comment by justinclift** [comment]
> I've confirmed it can run on Monterey with some build configuration and added the relevant commits

Looking at the commits shows this:

```
export MACOSX_DEPLOYMENT_TARGET=10.12
```

Awesome, really well done @lucydodo.  I didn't know that was possible. :smile:

**Comment by justinclift** [comment]
That reminds me, the macOS VM (on the M1 mac mini) that has the GitHub Runner is set to "Security Updates Only" for the OS, and it's saying there's an update available.  I'll apply that shortly.

**Comment by richb-hanover** [comment]
> Update: [continuous](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous) build has just finished, so you can test it.
> I also just ran it in my test environment and it worked fine. (macOS Monterey 12.6 (21G115) with Apple Virtual Machine 1)

I can confirm the continuous build ran fine on my Intel MacBook Pro - macOS Monterey 12.6.8. Thanks!

**Comment by mgrojo** [comment]
Thanks for confirming!
