### ISSUE TITLE
Increase font size of text in sql query panel

### ISSUE THREAD

**Issue by HajiMohamedRufai** [sqlitebrowser/sqlitebrowser#3178]
![Errorsqlite feauture](https://user-images.githubusercontent.com/60290402/191909358-2c76462e-d291-4535-ae9b-a7d245659f37.PNG)
I pressed ctr and minus(-) . The font decreased and i just continued till it became very small only the text font inside sql query panel. I try to restore default but only other features are being changed such as the text size of ribbon etc

**Comment by chrisjlocke** [comment]
So can you press [Ctrl]+[Numeric +] (on the keypad) - this should increase the font size again.

Alternatively, you can hold down [Ctrl] and use the scroll-wheel of the mouse - scrolling up makes the font larger and scrolling down makes it smaller.

**Comment by HajiMohamedRufai** [comment]
Thank you. It works.

**Comment by chrisjlocke** [comment]
Thanks for confirming. :)
