### ISSUE TITLE
Feature requests: be able to open each table in its own window, and allow multiple SQL execute windows

### ISSUE THREAD

**Issue by GeneGeneGitHub** [sqlitebrowser/sqlitebrowser#3181]
If you've tried SQLiteStudio, they do it that way.  With your system, you can only look at one table at a time.  That won't be sufficient for me.

Nice little tool otherwise.  Thanks

**Comment by chrisjlocke** [comment]
If you try the nightly (depending on your OS - you haven't said what OS you're using) you can have that functionality.

**Comment by chrisjlocke** [comment]
> and allow multiple SQL execute windows

Just a nod too, that DB4S currently supports tabs in the Execute SQL window, so technically, this part already exists.

![image](https://user-images.githubusercontent.com/7872218/194107920-8f7b1d68-2e0d-4f29-8bfc-4ba15fcdd52c.png)

**Comment by GeneGeneGitHub** [comment]
Nice.  Saw your note about separate table windows being available in the Windows version, and tried it out.  Good job!

Take a look at SQLite Studio (it's GPLed) and you might get some ideas from there.

I'll give your app a thorough test and get back to you with notes (and more feature requests).

Thanks for the replies.

________________________________

**Comment by chrisjlocke** [comment]
> and more feature requests

While this is appreciated, please note that as the issue count here is reaching 600, and we're only a small band of developers, the feature requests will take a low priority, with us focusing on bugs and critical issues first. :)

**Comment by GeneGeneGitHub** [comment]
I gotcha.   I'll still give you some feedback and testing.    Thanks Chris.
________________________________
