### ISSUE TITLE
Keyboard lock

### ISSUE THREAD

**Issue by Pegase92** [sqlitebrowser/sqlitebrowser#3182]
Good morning,

Details for the issue
--------------------

#### What did you do?
Writing sql requests work for 2/3 minutes then keyboard hang. I am able to navigate on the application only with the mouse

#### What did you expect to see?
Use the sql editor without any hang

#### What did you see instead?
Keyboard hang

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on Ubuntu 22.04.1 LTS (linux/5.15.0-48-generic) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.15.1

Only the tab "SQL" is impacted by this keyboard hang. When shutting the tab an open another SQL tab, I am able to write requests again ..

**Comment by chrisjlocke** [comment]
This hasn't been reported before.  Seems an odd issue.
Did it happen the once, or after restarting the application, it occurred again?

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
