### ISSUE TITLE
Basic question: bulk export images?

### ISSUE THREAD

**Issue by Thermospore** [sqlitebrowser/sqlitebrowser#3183]
Hello, I have a database consisting of ~7k images (a mixture of PNG and JPGs). Is there an easy way to export all of the files in bulk?

f_name - file name
f_type - file extension (1=jpg, 2=png)
f_main - image data

I figured out how to export the whole db as a csv though. So worst case scenario I could write some code to read in the csv and spit out the files

Thanks for taking a look, sorry if this is really obvious, I'm not very familiar with sqlite

![image](https://user-images.githubusercontent.com/35350819/193995303-1cc25a77-668f-4137-a18c-ad4e84b2088c.png)

**Comment by chrisjlocke** [comment]
Not easily from within DB4S, but if you can give me an example database of maybe 10 records, I can write a vb.net app to do this.  I see you're on Windows, so would be simple to do (theoretically!)
The only other 'easy' way is to use AutoIT which performs keystrokes automatically, but the vb.net route is easier and more reliable.
If you want to drop the database to db4s-issue3183 [at] chrisjlocke [dot] co.uk

**Comment by Thermospore** [comment]
Thanks, that is very kind of you, I will shoot an email!

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/194175086-97e5ff1c-4eba-41c9-bc3b-c54a1d3c7d46.png)

![image](https://user-images.githubusercontent.com/7872218/194175384-bd37b07b-4b79-4f98-aa31-bdc3e57ee4c7.png)

Here's a setup file.  We don't support .exes here, so remove the .txt extension.
[image exporter setup.exe.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/9719364/image.exporter.setup.exe.txt)

![image](https://user-images.githubusercontent.com/7872218/194175993-4e83f003-f847-46aa-bcd9-99d948a1d771.png)

This just opens a 7zip extractor.  Dump it anywhere.


![image](https://user-images.githubusercontent.com/7872218/194176107-16b325b9-813d-4154-b8ba-f3eeb6aa2ece.png)

In the directory you put it, place your database.  Call it **data.db** - it won't recognise any other name.  Case isn't important.
Run the 'image exporter.exe'.  It will require .net 5 runtimes.  It should moan if it doesn't find them and download them for you.  Yell if this is an issue...
Then click 'Export'.
When its done, you'll find a 'media' directory with all the images there.

Yell back if you've any problems. :)

**Comment by chrisjlocke** [comment]
> place your database

This is the vlpljblM.db file that is ~278 MB - **not** the .sql file

**Comment by Thermospore** [comment]
@chrisjlocke It ran beautifully, thank you so much!

**Comment by chrisjlocke** [comment]
Yay, glad it helped.  DB4S is a great tool, but obviously it can't do everything, otherwise it would be a fat bloated mess (hey, like me!)
Thankfully SQLite is easy to talk to via programming tools.
