### ISSUE TITLE
tables deleted

### ISSUE THREAD

**Issue by Maximme84** [sqlitebrowser/sqlitebrowser#3184]
Details for the issue
--------------------

#### What did you do?
adding tables

#### What did you expect to see?
all the tables were deleted

#### What did you see instead?
the first and only table

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
