### ISSUE TITLE
Sqlite cannot view tables with check constraints

### ISSUE THREAD

**Issue by AntonioRitucci** [sqlitebrowser/sqlitebrowser#3185]
**Cannot see table with check constraint**

I tried to open an existing sqlite db created with this statement, I also tried to create the table executing the sql code directly in the UI
The table is present but I can't see columns.

```
CREATE TABLE USERS (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
EMAIL TEXT UNIQUE NOT NULL,
CHECK (
    EMAIL LIKE '%_@_%._%' AND
    LENGTH(EMAIL) - LENGTH(REPLACE(EMAIL, '@', '')) = 1 AND
    SUBSTR(LOWER(EMAIL), 1, INSTR(EMAIL, '.') - 1) NOT GLOB '*[^@0-9a-z]*' AND
    SUBSTR(LOWER(EMAIL), INSTR(EMAIL, '.') + 1) NOT GLOB '*[^a-z]*'
)
);
```
I expected to see table columns, but I coludn't do that.
The table is present but there's no dropdown to see columns.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19043) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Yes, we use our own parser to pull apart schemas and get the fields, etc.  It probably looked at that check statement and had a stroke.

So there is good news and bad news.  And the bad news is quite bad news.
So the nightly appears to read the schema a bit better.

![image](https://user-images.githubusercontent.com/7872218/195136002-e09aa954-3cc6-4a8e-9ef7-54907bec9ed6.png)

However, the relative size of 'better' isn't great.

![image](https://user-images.githubusercontent.com/7872218/195135928-d4599c29-55fc-41b9-b66c-a999b1faaa6b.png)

So while it can read it, it can't fully understand it or allow modification without possibly losing that check.

**Comment by chrisjlocke** [comment]
For the avoidance of doubt, the nightlies are here.
https://nightlies.sqlitebrowser.org/latest/

If you download this .zip, you can just extract it and run the .exe - you don't need to install it and it won't affect your current installation.
https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
