### ISSUE TITLE
Plot x-axis and value tooltips

### ISSUE THREAD

**Issue by Spastika** [sqlitebrowser/sqlitebrowser#3186]
When consuming a plot, it would be useful to inspect the actual values of a data point. I propose that this be done with a tooltip shown when a data point is selected. The tooltip can then show the x-axis value along with the y-value of the selected data point.

**Comment by chrisjlocke** [comment]
Not sure if the graph control used supports this functionality, but have marked the issue as an enhancement anyway.  Hopefully it can be looked into.

**Comment by Spastika** [comment]
Thanks Chris. If it can't be on the chart, maybe just a label somewhere
showing the x and y value of the selected data point.

**Comment by Spastika** [comment]
They do, but just a label for the "major" marks on the scale.

I'm talking about the exact numbers but that's not a bad idea. A leader
line between the selected point and x axis also showing the exact x-value.
And a leader line between the selected point and the Y1 or Y2 axis,
whichever is relevant, showing the exact y-value. It feels like a mockup or
sketch would have helped, sorry.

**Comment by mgrojo** [comment]
Currently, you can click on a point to select the source row in the data browser.

**Comment by mgrojo** [comment]
Ok, I get your point.

**Comment by chrisjlocke** [comment]
(No pun intended). 😉

**Comment by Spastika** [comment]
😂

**Comment by mgrojo** [comment]
The x and y values of the current mouse position is now shown on a tooltip. @Spastika, you can give it a try if you install the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds).
