### ISSUE TITLE
[Bug]: Failed to create trigger containing 'ON CONFLICT' statement

### ISSUE THREAD

**Issue by WLimin** [sqlitebrowser/sqlitebrowser#3187]
### What did you do?

I compiled the application according to the instructions of README.MD, then created an empty In-Memory database and created two tables using the SQL:
`CREATE TABLE IF NOT EXISTS "cminkjetHardinfo" (
	"FactoryLineId"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("FactoryLineId")
);
CREATE TABLE IF NOT EXISTS "cminkjetLineInfo" (
	"MsgTopicFactoryLine"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("MsgTopicFactoryLine")
);
CREATE TRIGGER cminkjetHardinfo_trigger_ai AFTER INSERT ON cminkjetHardinfo
BEGIN
INSERT INTO cminkjetLineInfo("MsgTopicFactoryLine") VALUES (new.FactoryLineId) ON CONFLICT (MsgTopicFactoryLine) DO NOTHING;
END;
`
but It failed.

### What did you expect to see?

In the version 3.12.1 issued with Debian 11, that SQL statements work fine.

### What did you see instead?

Execution finished with errors.
Result: near "ON": syntax error
At line 9:
CREATE TRIGGER cminkjetHardinfo_trigger_ai AFTER INSERT ON cminkjetHardinfo
BEGIN
INSERT INTO cminkjetLineInfo("MsgTopicFactoryLine") VALUES (new.FactoryLineId) ON
![截屏-20221014102503-1396x733](https://user-images.githubusercontent.com/30562969/195759442-caff8e41-4973-418f-b99a-24158a25d445.png)
![截屏-20221014102222-1513x828](https://user-images.githubusercontent.com/30562969/195759461-72f641d1-d276-4a9b-8c4c-da8196bbb64c.png)

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Debian 11.5

### Relevant log output

```shell
Execution finished with errors.
Result: near "ON": syntax error
At line 9:
CREATE TRIGGER cminkjetHardinfo_trigger_ai AFTER INSERT ON cminkjetHardinfo
BEGIN
INSERT INTO cminkjetLineInfo("MsgTopicFactoryLine") VALUES (new.FactoryLineId) ON
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
For some reason, the SQL Cipher version is picking up an older version of SQLite (3.15.2).  

![image](https://user-images.githubusercontent.com/7872218/195776348-0ab36bd2-7002-424c-867c-a23caccad318.png)

From the nightlies, I'm getting SQLCipher version 4.51 with SQLite 3.37.2

Do you need encryption?  Do you see a 'non SQLCipher' application?

![image](https://user-images.githubusercontent.com/7872218/195776479-18ef1153-9ea5-48bd-bcf1-100246655e7d.png)

The current nightlies are using SQLite 3.39.3

Find what other sqlcipher.dll (or Linux equivalent it uses?) you've on your system.

**Comment by WLimin** [comment]
I just used the 'cmake  -Wno-dev ..' parameter and recompiled it. It works normally. 
![截屏-20221014162519-576x542](https://user-images.githubusercontent.com/30562969/195800490-42ea5c5a-b4b5-4f69-98b5-f5f8a060ff5c.png)

**Comment by chrisjlocke** [comment]
Thats a newer version of SQLite, so looks like that's working.
Glad you got it working. :)
