### ISSUE TITLE
Import form Excle ("Table from *.xls or *.xlsx")

### ISSUE THREAD

**Issue by palkoarnold** [sqlitebrowser/sqlitebrowser#3188]
Hi,

Often you use Excel charts (*.xls, *.xlsx). "Table from *.xls or *.xlsx" would be a good feature.

**Comment by chrisjlocke** [comment]
If the Excel data is saved as CSV (which Excel supports), you can import that CSV data.  So this is sort of there - just not 'directly' in one pass.  Excel is a proprietary format - and includes different flavours (.xls and .xlsx).  .csv is a specific standard.

**Comment by palkoarnold** [comment]
Hi, 
I see.
 I tried it but i have an error message. There ere 124412 records in the Excel that was exported into *.csv format. I do not understand why does not import into the table? Do you have an idea? 
Thanks,
![csv import problem](https://user-images.githubusercontent.com/60701366/195842192-199c4d89-0150-4bb3-a27a-507ba1b5c92d.JPG)

**Comment by chrisjlocke** [comment]
Are the quote characters correct?  I assume you've blanked the table name - ".  ,B text" doesn't look valid.
Have you checked row 15739? Maybe it contains weird characters?
If you email me the CSV (db4s-issue-3188 [at] chrisjlocke.co.uk) then I can have a look for you and confirm. :)
If you ZIP it (or 7zip) that would help as I assume its large?

**Comment by palkoarnold** [comment]
Thank, I am sending the file via email.

**Comment by chrisjlocke** [comment]
Thanks.
Looks like the file uses apostrophes for quotes (God said, 'Let there be light') etc.  So if you set the quote character to be a quotation mark, it imports 31,103 rows.

![image](https://user-images.githubusercontent.com/7872218/195903291-fefa12cc-cac0-4484-8645-e0fdc26208b0.png)

![image](https://user-images.githubusercontent.com/7872218/195903324-09b35d85-7e74-410a-b8bc-45a5167e7814.png)

Note, I did this on the nightly and in 3.12.2 - worked OK in both. :)

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.

**Comment by palkoarnold** [comment]
Dear Chris,

Sorry, that very night I become ill. Yes, you can close it, you resolved the problem.
