### ISSUE TITLE
App shows dialog "New version is available" even after click on "Don't show it again"

### ISSUE THREAD

**Issue by igozhenko** [sqlitebrowser/sqlitebrowser#319]
Dialog
![image](https://cloud.githubusercontent.com/assets/2979445/7716882/4c4c87b8-fea1-11e4-9d12-ff5f4c670543.png)

Details from About.

![image](https://cloud.githubusercontent.com/assets/2979445/7716878/4122e33c-fea1-11e4-81a4-c24bcd12cc9c.png)

**Comment by schdub** [comment]
@igozhenko, thanks for reporting, but this issue already fixed and discussed in #313.

**Comment by justinclift** [comment]
@igozhenko Ironically, the bug which causes this is fixed in 3.6.0.  Are you ok to upgrade to that?

**Comment by igozhenko** [comment]
@justinclift  I'm waiting new version ;), because I need quick view of blobs. I already reported about it and looks it will be reverted back in it.
