### ISSUE TITLE
Database cannot be opened ,SQLCipher aes-256-cbc

### ISSUE THREAD

**Issue by monkeycc** [sqlitebrowser/sqlitebrowser#3196]
Other database tools can be opened

![微信截图_20221022162458](https://user-images.githubusercontent.com/6490927/197329000-98467868-2ddf-434c-9fb6-6465fc4125d7.png)

sqlitebrowser Cannot open

**Comment by justinclift** [comment]
Interesting.  Do you know which software created the database, and do you know what encryption software was used?

We support a type of encryption called [SQLCipher](https://github.com/sqlcipher/sqlcipher).  If the database was created using that encryption, then it should be possible to work out how to open it.

If it was created using a different encryption package (maybe [SEE](https://www.sqlite.org/see/doc/release/www/readme.wiki)?), then we won't be able to open it.

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
