### ISSUE TITLE
[Feature]: Enums

### ISSUE THREAD

**Issue by duarm** [sqlitebrowser/sqlitebrowser#3197]
### Describe the new feature

Hello, would an enum feature be welcome? I have a database with a lot of enums, that would be, a 'race' column with 6 possible values, which I represent with an integer from 0 to 5. It would help a lot to read/update the data if there was an enum meta-type of some sorts, which would basically be displayed as, from the previous example, 'Elf', but the underlying value is actually 2. The column would be a dropdown.

### Does this feature exist in another product or project? Please provide a link

Other dbms with their own sql versions usually support a native Enum type.

**Comment by chrisjlocke** [comment]
In database lingo, this is called 'foreign keys' and is already supported.  Well, slightly.  It's not _exactly_ how you envisage.  DB4S will supply the allowed values, but it doesn't give their lookup values, so while it displays 1,2,3,4,5 for example, you don't know what 3 is, or 5.  

However, what is cool and exciting, is that you can have multiple browse windows open.  However (there is always a but) this is only in the nightly version.  Depending on your OS, this is either a good thing or a bad thing.  

If you want an example of the foreign key thingy, yell and I can post an example.

**Comment by duarm** [comment]
thanks, I'm awayre and I'm on nightly, what I wanted was precisely a better way to visualize the data without needing lookup anywhere. We already have a conditional formats in place, maybe extend that to format a "2" to "elf"?

**Comment by chrisjlocke** [comment]
Yes, it has been requested many times.  Hopefully it'll get implemented at some point. :)
As it is an existing issue, I'll close this, as it's a duplicate.
