### ISSUE TITLE
[Bug]: Crash when alter table with foreign key

### ISSUE THREAD

**Issue by Offerel** [sqlitebrowser/sqlitebrowser#3201]
### What did you do?

I try to alter a table, where foreign key is set. The application closes/crashes.

Table is created with:
```
CREATE TABLE "data" (
	`dataid`	TEXT NOT NULL,
	`parentid`	TEXT NOT NULL,
	`userID`	INTEGER NOT NULL,
	FOREIGN KEY(`userID`) REFERENCES `users`(`userID`) ON DELETE CASCADE
)
```

### What did you expect to see?

A form, where i can alter the table

### What did you see instead?

The application crashes/closes.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Manjaro rolling release

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
There have been a couple of reports of crashing when editing a table (not with foreign keys though) and each time, success has been fabulous with building from the current latest source.
Is that something you can try?

**Comment by scottfurry** [comment]
It's almost as if we should push the master branch out as a release... _nudge-nudge, wink-wink_

**Comment by Offerel** [comment]
I can try that tomorrow. I have switched temporary to a windows container with the same application version. There it works without any issue. The Linux version as from the standard repository.

**Comment by chrisjlocke** [comment]
> with the same application version

The difference may be between the version of Qt and/or SQLite.  You can see what version of SQLite is used in the 'about' box.

![image](https://user-images.githubusercontent.com/7872218/197893797-745d6006-3879-4eda-940b-4d9080ed7c99.png)

On Windows, its Qt 5.12 and SQLite 3.35

**Comment by Offerel** [comment]
I have tried no different variants. The default from official repository's failed:
![Bildschirmfoto vom 2022-10-26 16-26-04](https://user-images.githubusercontent.com/14041522/198056215-c1f526d6-b877-4c78-a1a1-6395b1ccedc0.png)

Then i have tried the variant from AUR with the same result:
![Bildschirmfoto vom 2022-10-26 16-32-34](https://user-images.githubusercontent.com/14041522/198056365-b91f6f85-bb3b-45de-99fa-5bfe3b1d358a.png)

Additionally there seems to be a continuous build (whatever this means in this case), also from AUR:
![Bildschirmfoto vom 2022-10-26 16-40-29](https://user-images.githubusercontent.com/14041522/198056741-f9ec73da-2d96-4f78-be54-e1f9d956ae05.png)

This last one works without crash. It works also on Windows 10 (Downloaded from https://download.sqlitebrowser.org/DB.Browser.for.SQLite-3.12.2-win64.msi). 

BTW: I have tried also DBVisualizer 14.0.1. Different app... i know... But this has also problems to alter some of the tables. There i get the error: 
```
An error occurred while performing the operation:
Range [-1, 9) out of bounds for length 10 
```

But thats not your issue. I have no idea, why i get the error. The db and table seems to be ok.

**Comment by Offerel** [comment]
The problem seems to be solved in testing branch of Manjaro Linux. If some is interested and find this issue, if you are on the stable branch, you can install it manually by using:
`sudo pacman -U https://osmirror.org/manjaro/testing/community/x86_64/sqlitebrowser-3.12.2-3-x86_64.pkg.tar.zst`

This specially for this exact version. Be careful, this can damage your system, if wrong packages are installed on your machine. In my case, it solved the issue.

I will close the issue because of this, feel free to re-open if needed.

**Comment by justinclift** [comment]
> It's almost as if we should push the master branch out as a release...

Yeah, it's very overdue.  Personally, I want to solve #2829 first, just in case it needs any DB4S changes rather than being a purely server side fix.  Started working on that a few days ago, but haven't solved it yet.  Should have it figured out sometime this week though. :smile:
