### ISSUE TITLE
delete not working with Order by / Limit

### ISSUE THREAD

**Issue by kitty7c6** [sqlitebrowser/sqlitebrowser#3204]
Hello,
I try two constructions:
```DELETE FROM table_name WHERE subtopic='some' ORDER BY id ASC LIMIT=1;```

and 

```DELETE FROM table_name WHERE subtopic='some' IN (SELECT (*) FROM table_mainflux WHERE subtopic='some' ORDER BY id ASC LIMIT 1);```

what I do wrong? or it just doesn't working yet?

**Comment by kitty7c6** [comment]
Hello,
I try two constructions:
```DELETE FROM table_mainflux WHERE subtopic='some' ORDER BY id ASC LIMIT=1;```

and 

```DELETE FROM table_name WHERE subtopic='some' IN (SELECT (*) FROM table_mainflux WHERE subtopic='some' ORDER BY id ASC LIMIT 1);```

what I do wrong? or it just doesn't working yet?

**Comment by justinclift** [comment]
I guess it depends on what you're expecting. :smile:

Looking at the SQLite documentation for the DELETE clause [here](https://www.sqlite.org/lang_delete.html#optional_limit_and_order_by_clauses), it says:

```
If SQLite is compiled with the SQLITE_ENABLE_UPDATE_DELETE_LIMIT compile-time option, then the syntax
of the DELETE statement is extended by the addition of optional ORDER BY and LIMIT clauses ...
```

My first guess, is that the SQLite library we've included doesn't (yet) have that compile option set.

Reading that page further, it also says:

```
The ORDER BY clause on a DELETE statement is used only to determine which rows fall within the LIMIT.
The order in which rows are deleted is arbitrary and is not influenced by the ORDER BY clause.
```

So it kinds of sounds like the option would be of limited use, even if we do enable it.  Which is do-able btw. :wink:

**Comment by chrisjlocke** [comment]
You can use a select first to find the record and delete it.

delete 
from table_name
where id=
(select id
from table_name
WHERE subtopic='some' ORDER BY id ASC LIMIT 1);

![image](https://user-images.githubusercontent.com/7872218/198016206-be10f682-d7b7-4d58-8cf2-1142dd50f0c5.png)

Note that its `limit 1` and not `limit=1`

**Comment by justinclift** [comment]
@kitty7c6 Did either of those help? :smile:

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by chrisjlocke** [comment]
Glad it worked.
We're happy to help with SQL woes as well as program queries.
So long as they're easy SQL woes... ;)
