### ISSUE TITLE
[Bug]: Database with STRICT table(s) does not display columns in Database Structure Tab

### ISSUE THREAD

**Issue by c9845** [sqlitebrowser/sqlitebrowser#3207]
### What did you do?

1. Opened a database file that contains `STRICT` defined tables. https://www.sqlite.org/stricttables.html
2. Viewed the Database Structure tab.
3. Tables cannot be expanded to see columns.
4. Right click a table and choose "Modify Table".
5. List of columns is not displayed to be modified nor are columns listed in the `CREATE TABLE` query.

### What did you expect to see?

Columns to be displayed.

### What did you see instead?

Columns are missing and a warning is displayed (Warning: There is something wrong with this table definition that our parser doesn't fully understand...).

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by c9845** [comment]
This is also tied into issue #3145.

**Comment by c9845** [comment]
Note, you will need to replace the sqlite3.dll file that comes with DB4S v3.12.2 with a newer version from SQLite.  The sqlite3.dll version that comes with DB4S v3.12.12 is 3.35.5.  However, SQLite 3.37+ is needed to support `STRICT` tables.

**Comment by chrisjlocke** [comment]
you have to change DB4S and the sqlite3.dll - the newer code has newer code in it which understands the data from the newer sqlite3.dll.
Have you tried the nightly at all?
Can you email me the database you're using? db4s.issue3145 [at] chrisjlocke [dot] co.uk (you can delete the data ... its just the schema I'm after).

**Comment by mgrojo** [comment]
This is implemented in #2926, so I'll close this one as duplicate.
