### ISSUE TITLE
SQL Lite Browser 3.6 

### ISSUE THREAD

**Issue by dmitrymozheyko** [sqlitebrowser/sqlitebrowser#321]
OS Windows Prof 7 x 64. Both versions x86 & x64 not prints russian symbols in SQL Window

**Comment by MKleusberg** [comment]
Hi! You're lucky we've already fixed this issue some days ago. You can download the latest build from here http://rp.oldsch00l.com/sqlitebrowser/sqlitebrowser.exe.xz (use 7-zip to unpack) and use that. With this file the Russian symbols will work again :smiley:

**Comment by justinclift** [comment]
Closing this, as it's definitely the known Unicode issue we've fixed in our latest nightly builds. :smile:
