### ISSUE TITLE
locked

### ISSUE THREAD

**Issue by yrkoon57** [sqlitebrowser/sqlitebrowser#3210]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22000) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by lucydodo** [comment]
Closed because no content has been entered. You can add content and reopen it at any time.
