### ISSUE TITLE
[Feature]: MySQL database support

### ISSUE THREAD

**Issue by fbongcam** [sqlitebrowser/sqlitebrowser#3212]
### Describe the new feature

Using sqlitebrowser for testing mysql statements before applying to actual database in mysql. But I stumble on to many errors as it's plain sql. So I would gladly see support for mysql database in the future. 👍

**Comment by chrisjlocke** [comment]
While a great idea, DB Browser **for SQLite** is for SQLite.  Adding in a bunch of gooey for MySQL, we'd then have to do SQL Server.  Then we'll get calls from the PostgreSQL guys.  Then MariaDB will be wanting a bit of action.  Where do we draw the line?  Unfortunately with only a couple of developers bashing away, there is only so much we can do.  We've added little bits (like quotes) but we have to keep to the core purpose of this program.

If you want a playground for MySQL, there are online playgrounds for MySQL.

I'll close this, as unfortunately there just isn't enough development time available to warrant completing this before the Earth blows up. :(
