### ISSUE TITLE
Regular text interpreted as Bitmap

### ISSUE THREAD

**Issue by mikaere66** [sqlitebrowser/sqlitebrowser#3217]
I was entering a user's initials as TEXT into a database, and the letters BMD are interpreted as a bitmap image, with a message appearing in the text editor window saying "Image data can't be viewed with the text editor"

**Comment by scottfurry** [comment]
If I'm reading this correctly, this is in the "Edit Database Cell" panel?
IIRC, there's a "quirk" with cell contents that you have to change. The "Mode" dropdown list has to be set to "Text". Screenshot attached.

Does this sound about right for the situation?

![DB4S_CELL_EDIT](https://user-images.githubusercontent.com/6686571/200151777-2ae33402-4b13-49bc-a1cb-e8b45e013e2d.jpg)

**Comment by justinclift** [comment]
> BMD are interpreted as a bitmap image

That actually sounds familiar.  From memory, it's something along the lines of the first few bytes that we use for automatic image detection.

I *thought* we fixed that a while ago though.  Which version of our application are you using? :smile:

**Comment by mikaere66** [comment]
That's correct: all my databases are simply text based, so drop-down is always Text anyway.
BTW: this hasn't caused me any problems yet, unless of course I wanted to edit that record.
Here's a screenshot of the "offending" cell:
![SQLite Browser v3 10 1](https://user-images.githubusercontent.com/3999272/200187149-0d65abac-1cb8-4010-845e-cbb8f868b296.png)

**Comment by mikaere66** [comment]
> > BMD are interpreted as a bitmap image
> 
> That actually sounds familiar. From memory, it's something along the lines of the first few bytes that we use for automatic image detection.
> 
> I _thought_ we fixed that a while ago though. Which version of our application are you using? smile

Version is 3.10.1 on Peppermint 10 Linux distro.

**Comment by FriedrichFroebel** [comment]
Version 3.10.1 actually is quite old, as it has been released over five years ago (see https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1). You might want to try building a recent release yourself: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

**Comment by mikaere66** [comment]
> Version 3.10.1 actually is quite old, as it has been released over five years ago (see https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.10.1). You might want to try building a recent release yourself: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

As I mentioned, it doesn't cause me any issues ATM ... I was just hoping to offer some feedback.
Feel free to close this issue, and if I need to upgrade in future, I could always find a PPA with a more recent version.

Thanks everyone for your prompt replies =)

**Comment by chrisjlocke** [comment]
Also of note is that the text editor panel is just a handy point to edit text.  You can still edit text directly in the cell itself, so DB4S showing 'image data' and not allowing editing isn't a 'show stopper'. :)

Thanks for the report though. :)

**Comment by chrisjlocke** [comment]
I'll close this, as this isn't an issue in the current version of DB4S.

![image](https://user-images.githubusercontent.com/7872218/200304061-33fa63c4-469f-4926-a5f5-af6a4be9ede3.png)
