### ISSUE TITLE
option

### ISSUE THREAD

**Issue by ulision** [sqlitebrowser/sqlitebrowser#3220]
bonjour ce qui serais bien pour bd browser c'est le mode sombre et colorisation des données par paquets de 10.
merci

**Comment by chrisjlocke** [comment]
Dark mode is in the nightly version.
https://nightlies.sqlitebrowser.org/latest/

What operating system are you using?

**Comment by ulision** [comment]
merci

**Comment by chrisjlocke** [comment]
What version of DB4S are you currently using? (click 'Help' then 'About')

![image](https://user-images.githubusercontent.com/7872218/200685138-7f431905-eecf-48c6-90a9-22012b422da7.png)

Just checked 3.12.2, and if you click 'Edit' and 'Preferences', you should have an option.

**Comment by ulision** [comment]
Merci beaucoup
C'est en mode sombre

Le mar. 8 nov. 2022 à 23:01, Chris Locke ***@***.***> a
écrit :

**Comment by chrisjlocke** [comment]
Glad it worked. :)
