### ISSUE TITLE
SQLite, convert date format

### ISSUE THREAD

**Issue by Wigbers** [sqlitebrowser/sqlitebrowser#3229]
Hi, how can I convert a 13 digit date&time format in SQLite to a date format something like [dd.mm.yyyy] ?

**Comment by scottfurry** [comment]
See here: https://www.sqlitetutorial.net/sqlite-date/

**Comment by chrisjlocke** [comment]
This is why I always store dates as yyyy-MM-dd - so much easier to view, sort, etc.

**Comment by Wigbers** [comment]
I agree, but my android phone stores it as a 13 digit integer 😊

**Comment by Wigbers** [comment]
thnx

**Comment by lucydodo** [comment]
Close the issue because it seems to have resolved.
