### ISSUE TITLE
[Bug]: GUI isn't shown straight away, until auto-update is completed

### ISSUE THREAD

**Issue by davi1td** [sqlitebrowser/sqlitebrowser#3230]
### What did you do?

No GUI on startup. Nothing but clicking on app start icon. Can see it running in Task Manager but no GUI.

### What did you expect to see?

GUI on startup.

### What did you see instead?

Turns out the GUI does eventually come up, but way in the future, like 10 minutes or more.
Once this occurs, starting the app again runs perfect there after. 
I suspect this has to do with auto update logic, and for whatever reason seems to take a long time.
The problem is, that update code is not allowing the GUI to show on startup, thus made me believe the app
was not working right. 
I could also post the following as a feature request, but because of the current behavior see it as a bug as well.
The feature request would be:
1) Show and indication that a check for updates is running, maybe with a cancel option
2) Run that update check in a separate thread and allow the GUI to load?
or both ...
Great App BTW
Thanks
-TD

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 Pro

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by scottfurry** [comment]
This sounds more like intensive, cpu-hogging, local processes than application problem. _Normally_, application just appears without delay. If it's taking 10+ minutes for you, I would suggest there are bigger problems (such as spyware, crypto-miners, et al) stealing cpu cycles.

A careful study of Task Manager output should be revealing.

**Comment by davi1td** [comment]
> Do you have an agressive anti-virus or firewall? There is an update check, but it just downloads from a normal HTTP link. Can't remember it at the moment, but I can find it, and you can test it.
> 
> ![image](https://user-images.githubusercontent.com/7872218/203624306-2c66d163-39ad-4be3-846a-df4fd6dc5373.png)
> 
> If you click 'Edit' and 'Preferences', you can turn off the check. If you close DB4S and restart it, hopefully it won't take 10 mins... That seems an aggressive timeout though. I've tried on my laptop with the wireless turned off, and don't get that sort of delay.

I'm only using windows standard firewall/antivirus.
I doubt it any of that. 

Your idea about the URL is probably is spot on, I'd appreciate that, also do you know when it checks, once a day, week, every-time?
Regards
-Tom

**Comment by scottfurry** [comment]
But is it running _efficiently_? If a GUI takes 10 minutes to come up, I have my doubts.

If Task Manager is showing idle on a Windows-based system, there are other items to consider - disk encryption (including QT libraries), DDOS lag, etc. Basic OS/networking problems.

As @chrisjlocke points out, auto update can be disabled. My personal preference is to disable automatic updating just about everywhere - updates happen usually at the worst times. YMMV

I would encourage you to look at your setup with some skepticism.

**Comment by chrisjlocke** [comment]
DB4S checks this URl
https://raw.githubusercontent.com/sqlitebrowser/sqlitebrowser/master/currentrelease

It checks each time you start the application.

**Comment by davi1td** [comment]
Chris, I'll just close this for now, I rebooted, with update enabled and worked fine. It could be some intermittent thing on my end with DNS.

**Comment by chrisjlocke** [comment]
No problem.  At least its working now, which is the main thing.
Thanks for reporting back. :)
