### ISSUE TITLE
[Bug]: Can't open db file at hidden folder

### ISSUE THREAD

**Issue by atx49559** [sqlitebrowser/sqlitebrowser#3231]
### What did you do?

I want open a db file at hidden folder.

OS: Ubuntu 20.04

### What did you expect to see?

Fix that.

### What did you see instead?

nothing at picker window explorer

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 20.04

### Relevant log output

```shell
NaN
```

### Prevention against duplicate issues

- [x] I have searched for similar issues

**Comment by scottfurry** [comment]
The problem of hidden files/folders exists in multiple Qt-based applications. Qt has a standard File Open Dialog that these applications, including DB4S, utilizes. Nothing we can do in our code.

Workaround is to right-click the dialog and select "Show Hidden Files".
![DB4S_Hidden_File](https://user-images.githubusercontent.com/6686571/203677353-f880895e-dd03-4bb7-9fcb-694de34becb2.jpg)

**Comment by chrisjlocke** [comment]
Closing this as it's a duplicate.
Hidden files are also a problem on macOs where you have to hold down twenty keys to show hidden folders.

**Comment by atx49559** [comment]
Hi chrisjlocke,

Thank you for response, but this issue is the second hidden folder not be show

![圖片](https://user-images.githubusercontent.com/47237586/205210864-7d0c1a10-1e35-4c87-9a82-ef67bb2b97dc.png)

**Comment by chrisjlocke** [comment]
Copy the database to a non-hidden folder, then move it?

**Comment by chrisjlocke** [comment]
Also, Scott appears to be right-clicking on the folder, not an empty file pane ... can you replicate his example?

**Comment by atx49559** [comment]
Hi chrisjlocke,

This picture show the folder path `/home/$USER/.config`,  please see terminal window that folder is not empty,

but in DB Browser looks like empty.

**Comment by scottfurry** [comment]
@chrisjlocke
Actually, I'm right clicking the folder pane. After I saw the comment I had an "_oh, yeah...differences_" moment. I'm using XFCE and I was highlighting a feature of the Thunar file manager.

For other Linux distros, YMMV. @atx49559, this [article](https://devconnected.com/how-to-show-hidden-files-on-linux/) should get you moving along. Gist is to click a drop down box in the top right corner and select "Show Hidden" from there. Article gives more details (half-way down).

**Comment by chrisjlocke** [comment]
Linux is for those people who like tinkering though.  Not showing hidden files is a 'feature' and you have to re-code half the OS, patch the kernel and download additional libraries if you want to do weird stuff like that.  Open config files using vi and patch in SSH ports from offline containers using lxc ringmain shuffle wombats.  If you want 'normality', then you use Windows, where everything is beige.  Well, grey.

**Comment by atx49559** [comment]
ok, I got it!

I'm going to download AppImage version that it's work, but download from snapcraft.io it's not work.

Strange, install from snap , DB Browser version is  `3.12.99`

![圖片](https://user-images.githubusercontent.com/47237586/205529709-18ff0b2f-8e2f-424c-a27a-d4968c7baa67.png)

**Comment by atx49559** [comment]
Strange, install from snap , DB Browser version is  `3.12.99`

![圖片](https://user-images.githubusercontent.com/47237586/205529709-18ff0b2f-8e2f-424c-a27a-d4968c7baa67.png)
