### ISSUE TITLE
[Bug]: Freeze when modifying primary key

### ISSUE THREAD

**Issue by goelzma** [sqlitebrowser/sqlitebrowser#3245]
### What did you do?

1. Create a new in-memory database
2. In the create table wizard that opens, tick the primary key (PK) checkbox for any column
3. Untick the PK checkbox

This only happens if the PK checkbox to be unticked is the last one active, such that there is no longer a primary key afterward.

### What did you expect to see?

The checkbox is cleared and the primary key clause is removed from the table definition.

### What did you see instead?

DB4S freezes and has to be forcibly closed using `kill`.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Arch

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
I reproduced the issue. Thanks for the report.

**Comment by MKleusberg** [comment]
Thanks for reporting this! The issue should be fixed with the last commit. Can you try again using the latest build?

**Comment by goelzma** [comment]
I just tried the latest (a5a3d7f) build and can confirm it is fixed, thanks!

**Comment by MKleusberg** [comment]
Awesome! Thanks for testing :+1:
