### ISSUE TITLE
Concerns regarding my sqlite project

### ISSUE THREAD

**Issue by LianaLaxamana** [sqlitebrowser/sqlitebrowser#3249]
Details for the issue
--------------------

#### What did you do?
I connected the SQLite file on my java project but why can it not find it? It said "No suitable driver found on jdvc.slite". 

#### What did you expect to see? 
I expect it to connect easily.

#### What did you see instead?
error 

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22621) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by scottfurry** [comment]
Project does not use java. Connecting to an sqlite database via the JDBC driver is a bit out of scope for us.

However, if you checkout ["SQLite Java: Connect To SQLite Database Using SQLite JDBC Driver"](https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/), this should get you going in a good direction.

Good Luck.

**Comment by chrisjlocke** [comment]
Where is your database stored?  Can you copy it to a Windows folder?  Is it 'contained' within a Java container?

**Comment by MKleusberg** [comment]
Closing this as it's not directly related to DB4S :innocent:
