### ISSUE TITLE
Request read-only Open of DB

### ISSUE THREAD

**Issue by JoeErsatz** [sqlitebrowser/sqlitebrowser#325]
Self-explanatory: I'm using sqlitebrowser to examine data but only the affiliated software must be permitted to modify the DB in any way! Lest a slip of the mouse occur, I respectfully request that you folks implement an Open Read-Only capability down the road or ASAP. Hey, THANKS!

Y'know, it's actually not a crucial thing. You'd have to be a dumbo to click on "Write changes". So let the reader be the judge of the value of this request.

**Comment by justinclift** [comment]
Hmmmm, I'm not sure if this would be easy/hard/etc. :wink:

Some databases technically change files even just to "open the database" - even if there is no real change in the data contained.

I'm personally unsure about SQLite3 for that, but if it has to change the database file just to open it, it could be difficult.  The other guys here would probably know for sure. :grinning:

**Comment by glawrence** [comment]
I have just tried opening a database, issuing some queries and then doing a binary diff, nothing changes, which is good. I then marked the database file read-only and when I tried to add a row I got an error message. So, DB Browser for SQLite does seem to do the write thing. As a workaround I would mark the file read-only to avoid problems. However it would still be good for us to add an enhancement displaying "read only mode" and also handling the UI better.

I tested on Windows by the way.

**Comment by justinclift** [comment]
Ahhh, good thinking. :smile:

**Comment by JoeErsatz** [comment]
'Glad to see you're pursuing this. You said as a workaround you could "mark the file read-only". I'll just go ahead and assume you mean by that to enter the appropriate direct command under the program's "Execute SQL" tab. I confess to and apologize for my utter ignorance of SQL command lingo but no matter. You say you may integrate the read-only ability into the GUI and I am thankful!

**Comment by glawrence** [comment]
@JoeErsatz sorry, I meant use your operating system to mark the file read-only. So, before you load the database file in DB Browser for SQLite, find the file with your operating system utilities and mark the file read-only

**Comment by justinclift** [comment]
@JoeErsatz Just to check... which operating system are you using? :smile:

**Comment by JoeErsatz** [comment]
Windows. Hey no, I get you now -- I actually had considered momentarily that was your meaning but concluded otherwise. No I cannot mark the file read-only because it's over a LAN but more importantly the software controlling the DB is constantly running (at that other LAN node).

**Comment by justinclift** [comment]
No worries.  As a thought, maybe it needs to be marked Read Only on the server which is storing it?

That being said, something in our UI and codebase to do things in a Read Only option fashion isn't a bad idea. :smile:

**Comment by glawrence** [comment]
@justinclift for the scenario @JoeErsatz has outlined the only option is "Open Read Only" within DB4S. Given this is labelled as an enhancement and we have clearly outlined why then we just need to wait for a pull request or similar

**Comment by MKleusberg** [comment]
Sorry, this took a while :wink:

With the next nightly build there will be a menu item to open a database in read only mode. With this all editing options in the GUI will be disabled and no SQL statements that make changes to the database will be allowed. Are you're still interested in this, @JoeErsatz? If so you can try out tomorrow's nightly build :smiley:

**Comment by JoeErsatz** [comment]
Yes, it is still of interest to me. Many earnest thanks for your efforts in regard to my request! But I won't be testing it via the nightly build. Instead, I harbor every confidence that you guys know precisely what you're doing, and if the feature appears in the next release then it will be employed. I presume the implementation of read-only open in sqlitebrowser is a proverbial "walk in the park". Thanks!

**Comment by justinclift** [comment]
@JoeErsatz Ahhh... there's a minor drawback to that concept.  We do our very best to make things work properly, but it's an 80/20 thing.  80% of the time everything works out well, and there aren't any hidden surprises.  20% of the time though... things turn out to need a bit of kicking into shape. 😀 

Thus our general request for feedback, to help catch those 20%-ers. :wink:

**Comment by MKleusberg** [comment]
No worries :smiley: I'll close this issue for now because I'm pretty sure it should be working with the next release. If it doesn't work as you expected, feel free to re-open it anytime, @JoeErsatz. Should we update this issue as soon as the new release is out to remind you of this issue/fix?
