### ISSUE TITLE
Very small Icons

### ISSUE THREAD

**Issue by Raphides** [sqlitebrowser/sqlitebrowser#3250]
Details for the issue
--------------------

#### What did you do?
Installed SqliteBrowser from Linux Mint Cinammon's Software Manager.

#### What did you expect to see?
Normal sized icons.

#### What did you see instead?
From the very beginning, all icons are really small when I use the application. I can't see them at all, they like in the size of a dot (.).

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on Linux Mint 21 (linux/5.15.0-56-generic) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.15.1

**Comment by chrisjlocke** [comment]
This seems similar to https://github.com/sqlitebrowser/sqlitebrowser/issues/3101
3.12.1 is at least one revision behind the latest release, and a long way behind the current build (as we haven't released an official version lately).  If you build from source, do you get the same issue?

**Comment by chrisjlocke** [comment]
If you build from source, do you get the same issue?

**Comment by Raphides** [comment]
>  If you build from source, do you get the same issue?

Oh, I am so sorry! I have not seen this message before, I was not excepting to be answered so early.

I checked the issue you mentioned, it is a bit different. All of the icons are there, but extremely smaller.

I am going to test if the same happens when I build it from source this afternoon.

**Comment by Raphides** [comment]
Thank you @chrisjlocke , it worked. I built it from source and icons are normal sized now. Also the recent app design theme is so beautiful. Thank you for your support :)

**Comment by chrisjlocke** [comment]
Glad you got it working.  Your confirmation will help others.  Thanks for taking the time to report back. :)
