### ISSUE TITLE
Is there a way to copy data from multipla tables into one table for once? 

### ISSUE THREAD

**Issue by alvarotinali** [sqlitebrowser/sqlitebrowser#3251]
### Describe the new feature

Hello, 
I have a SQLite db with multiple tables and each one of them has his own function to insert data into it. I want to create a new table which get all those table into one table to export it all as Excel file. Is there any way to sample all columns from tables into one big table? 
I have tried to use INSERT OR REPLACE, but it did not work for me. 
thanks

**Comment by chrisjlocke** [comment]
You can do a 'insert into ... select from ...' to copy from table A into table B, however the columns must match (at least in number) - so specify three columns from table A to copy into three columns in table B.

So if table A has field1, field2, field3 and field4, and table B has field2, you could
<code>
insert into tableB (field2)
select field2
from tableA
</code>

That copies all records - you can filter that by adding a where, etc.

**Comment by chrisjlocke** [comment]
Was this of any use at alll?

**Comment by MKleusberg** [comment]
Another option might be creating a view similar to this:
```sql
CREATE VIEW view_for_export AS SELECT * FROM tableA UNION SELECT * FROM tableB;
```
You can then export the data of this view.

Closing this issue though as it's been inactive for a while and seems answered. But if there's any remaining questions here you are absolutely welcome to reopen it again, @alvarotinali :smiley:
