### ISSUE TITLE
[Bug]: (copy as sql) NULL value fields gets changed to an empty string 

### ISSUE THREAD

**Issue by IIHERO4** [sqlitebrowser/sqlitebrowser#3257]
### What did you do?

Using the "copy as SQL", fields with NULL as their value gets converted to `''`

### What did you expect to see?

I believe `NULL` values should have been NULL in the sql statement not an empty string

### What did you see instead?

Before
![image](https://user-images.githubusercontent.com/46909116/211171300-16f77e25-e787-45b9-bc03-c77af7e99dbc.png)

If i remove the record and use the sql that was generated I get this
![image](https://user-images.githubusercontent.com/46909116/211171333-5c2dbfdb-a1f9-4408-9cfc-0e5e7aaa70b0.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
If you download the nightly, you should see this has been fixed.
If you download the .zip, extract the contents and just run the .exe, you don't need to install it, and it can co-exist with v3.12.2 you've installed.

**Comment by IIHERO4** [comment]
tested it, it works! ty

**Comment by chrisjlocke** [comment]
Thanks for taking the time to report back.  Appreciated. :)
