### ISSUE TITLE
Support for browsing Android SQLite databases

### ISSUE THREAD

**Issue by Brunobrlk** [sqlitebrowser/sqlitebrowser#3258]
Is it possible to use databases in real time on android phones / emulators? Like Android Studio Inspector.. I know that there's a security barrier that was added last years and we need root access to navigate through files..

Can it be possible to query and modify databases when root enabled?

**Comment by justinclift** [comment]
Probably not, at least with DB Browser for SQLite in the near future.

For it to work, it seems like the kind of thing that would need code running live on the Android phone.  Which means we'd need to develop it, and we'd need to deploy it to the phone.

The review processes for mobile apps (Google, Apple) have such a poor reputation, I'd personally not want to waste time even attempting this.  However, if someone else is feeling super motivated they could give it a go.

**Comment by scottfurry** [comment]
On 2023-01-24 15:37, Justin Clift wrote:
>
> Probably not, at least with DB Browser for SQLite in the near future.
>
> For it to work, it seems like the kind of thing that would need code 
> running live on the Android phone. Which means we'd need to develop 
> it, and we'd need to deploy it to the phone.
>
> The review processes for mobile apps (Google, Apple) have such a poor 
> reputation, I'd personally not want to waste time even attempting 
> this. However, if someone else is feeling super motivated they could 
> give it a go.
>
... with the added pain of development licensing fees and percentage of 
commissions...

https://www.theverge.com/21445923/platform-fees-apps-games-business-marketplace-apple-google

**Comment by justinclift** [comment]
Good point. :smile:
