### ISSUE TITLE
Open Databases per Drag and Drop

### ISSUE THREAD

**Issue by aciokv** [sqlitebrowser/sqlitebrowser#326]
If no database is loaded it would be really helpfull if you could drag one on the main app window.

**Comment by justinclift** [comment]
In theory (!), that should work already. :smile:  Which operating system are you using, and which version of our application?

**Comment by aciokv** [comment]
Strange, now it works, sorry 
But for completeness: 
Win 7 Pro
DB Browser Version 3.6.0
Qt Version 5.4.1
SQLite Version 3.8.9

**Comment by justinclift** [comment]
Yeah, that's a combination that is "known to be good".  I'll close this issue for now, but if you see the behaviour happening again, please re-open it so we can figure out how to investigate. :smile:
