### ISSUE TITLE
Update Views with INSTEAD OF trigger

### ISSUE THREAD

**Issue by iandall** [sqlitebrowser/sqlitebrowser#3260]
It would be nice to be able to modify fields from the Browse Data tab when there is a INSTEAD OF UPDATE trigger in place. Likewise to inset or delete rows where there is an INSTEAD OF INSERT or INSTEAD OF DELETE trigger.

**Comment by mgrojo** [comment]
It's possible, but you have to "Unlock view editing". See https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views

I wonder if we could implement detection of the triggers and automatically enable it.

**Comment by iandall** [comment]
Ah, thanks. I wasn't aware of that feature.

On 27 January 2023 10:21:28 am ACDT, Manuel ***@***.***> wrote:
>It's possible, but you have to "Unlock view editing". See https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views
>
>I wonder if we could implement detection of the triggers and automatically enable it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sqlitebrowser/sqlitebrowser/issues/3260#issuecomment-1405825276
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MKleusberg** [comment]
Closing this issue as it has been solved :smiley:
