### ISSUE TITLE
PRAGMA_TABLE_INFO

### ISSUE THREAD

**Issue by kMaticic** [sqlitebrowser/sqlitebrowser#3263]
Details for the issue

the system dont accept main before PRAGMA_TABLE_INFO correctly. If I write it wrong work aniway. If I want to go thrue attached bases it tooks only first one. The result is always the same.

select distinct *
from 
  select name, type from db1.PRAGMA_TABLE_INFO("DefinedTypes")
  union
  select name, type from db2.PRAGMA_TABLE_INFO("DefinedTypes")
  union
  select name, type from db2.PRAGMA_TABLE_INFO("DefinedTypes")
where name like ('DTC%')

#### What did you do?
I wanted to query all different column names in different attached databases. DBs are some automated data from controlling machine for different products groupe. Every DTC code is written as column and only if heppens.

#### What did you expect to see?
DISTINCT DTCs (columns) in all batabases

#### What did you see instead?
Only result from first.

Useful extra information
-------------------------
DB Browser for SQLite Version 3.12.2

Built for i386-little_endian-ilp32, running on i386
Qt Version 5.12.8
SQLite Version 3.35.5.

**Comment by MKleusberg** [comment]
The SQLite documentation says this [here](https://www.sqlite.org/pragma.html#pragfunc):
> PRAGMAs that return results and that have no side-effects can be accessed from ordinary [SELECT](https://www.sqlite.org/lang_select.html) statements as [table-valued functions](https://www.sqlite.org/vtab.html#tabfunc2). [...] The PRAGMA argument and schema, if any, are passed as arguments to the table-valued function, with the schema as an optional, last argument.

So the schema name should be added as the last parameter to the ```pragma_table_info``` function call. More or less like so:
```sql
select distinct *
from
select name, type from PRAGMA_TABLE_INFO("DefinedTypes", 'db1')
union
select name, type from PRAGMA_TABLE_INFO("DefinedTypes", 'db2')
union
select name, type from PRAGMA_TABLE_INFO("DefinedTypes", 'db2')
where name like ('DTC%')
```

I hope this helps :smile: Closing this issue though as it's not really directly related to DB4S.
