### ISSUE TITLE
[Bug]: Cannot use closure.c extension

### ISSUE THREAD

**Issue by kayng26** [sqlitebrowser/sqlitebrowser#3265]
### What did you do?

I generated closure.dll using `gcc -shared closure.c -o closure.dll` and successfully loaded it in DB Browser. 
Then I tried to use the extension running the following : 
`CREATE TABLE category (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(255),
  parent_id INTEGER,
  FOREIGN KEY (parent_id) REFERENCES category (id));

CREATE VIRTUAL TABLE category_closure USING transitive_closure (
  tablename="category",
  idcolumn="id",
  parentcolumn="parent_id");`

### What did you expect to see?

I expected to see my created tables.

### What did you see instead?

But right after I execute my sql query DB Browser closes without creating the tables.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by kayng26** [comment]
I tried using the nightly version as suggested. I now have an error message when I load the extension saying "Error loading the extension : the specified module could not be found". 
I saw there was a similar closed issue on the matter (#2795). I followed his solution of compiling the dll using mingw64 gcc. I can generate the dll but the extension is still not loading with the same error message.

**Comment by kayng26** [comment]
I was able to load my extension after I realized that I was not using the 64bit version but the 32bit version of DB Browser. Now I can load and use the extension using this version : https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.2/DB.Browser.for.SQLite-3.12.2-win64.zip
Thank you for your time.

**Comment by chrisjlocke** [comment]
You'll need to debug with something like the Process Monitor to see what module couldn't be found - usually its a dependant file.
https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

You can't just run it as it'll monitor everything and you probably don't want that.  Filter it down to just DB4S and exclude other noise.

**Comment by chrisjlocke** [comment]
Glad you got it running, and thanks for reporting back,
