### ISSUE TITLE
[Bug]: Buttons missing

### ISSUE THREAD

**Issue by qrockz** [sqlitebrowser/sqlitebrowser#3269]
### What did you do?

On Version DB Browser Version 3.11.2 on my Laptop there are Buttons "new record" and "delete record" in the "Browse Data" Menu.

But on my PC which runs Version 3.12.1 these Buttons are missing.....

### What did you expect to see?

 Buttons "new record" and "delete record" in the "Browse Data" Menu.
![Untitled](https://user-images.githubusercontent.com/56853194/215670744-b3c2cf58-f5fe-4f13-abeb-303040e3882e.png)

### What did you see instead?

![db](https://user-images.githubusercontent.com/56853194/215669656-a6efaf1c-50a1-4e56-8939-547b516698fc.png)

### DB4S Version

3.12.1

### What OS are you seeing the problem on?

Linux

### OS version

Linux Mint 21, cinnamon 5.4.12

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ahhh.  With the newer version, those are probably among the icons next to the `Table: family` drop down in the Browse Data tab.  At least, they are on mine.

It's a bit of a pain having to mouse over the icons and wait for the tooltip to show up (to say what the icon does).  But once you've figured out which icon is which, I *think* you'll be ok.

Does that help? :smile:

**Comment by chrisjlocke** [comment]
If you click 'Edit' and 'Preferences', there is a toolbar style option.

![image](https://user-images.githubusercontent.com/7872218/215795691-cfc898ca-cdf8-4820-b0cb-912fb1690098.png)

Is it on 'Only display the icon' ?  You can change this to 'The text appears beside the icon' or another style of your preference.
