### ISSUE TITLE
Include sqlitebrower and Translation

### ISSUE THREAD

**Issue by magicvinni** [sqlitebrowser/sqlitebrowser#327]
Hello, 

   Congratulations for your software. I'm the lead developper of the project : EduPython (http://edupython.tuxfamily.org/) which is a portable python distribution for French Teachers (this may excuse my bad english ;) ). Edupython is under free licence CeCILL-B.
    1 - Can I include your sqlitebrower in my next EduPython distribution ? 
    2 - Can I help you by translating sqlitebrowser in french ? 

Thanks for your answer, 
Vincent - vincent.maille@ac-amiens.fr

**Comment by glawrence** [comment]
Any help translating is always welcome. Just submit a pull request.

I will leave @justinclift to answer your other query.

**Comment by magicvinni** [comment]
Le 29/05/2015 19:26, Geoff Lawrence a écrit :
>
> Any help translating is always welcome. Just submit a pull request.
>
> I will leave @justinclift <https://github.com/justinclift> to answer 
> your other query.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/327#issuecomment-106878903>.
>
OK, thanks for your answer, it's the first time I use GitHub. I going 
to  submit a pull request.

Vincent

**Comment by justinclift** [comment]
@magicvinni You're welcome to do anything with this, that respects the licenses. So, yes. :wink:

This isn't a Python program though... are you sure you want to include it?

**Comment by magicvinni** [comment]
Hi,

    Thanks a lot for this very good new ! Yes I can include it in my 
python distrib, because it contains, Python engine, IDE (pyscripter), 
and tools (see the screen shot). I already do this with a very old 
version of SQlite Databas Browser.

Best regards,
Vincent

**Comment by glawrence** [comment]
@magicvinni if you need help with doing a pull request you can just ask, however the GitHub help, StackExchange and Google should also be useful. My suggestion to you is that you do it all in one commit, so just take your time and do the one commit. If you don't it's fine, we have commit merging instructions on the wiki

**Comment by justinclift** [comment]
Going to close this for now, as it's a fairly old issue and @mvt91 has been contributing the French translation bits.

@magicvinni You are absolutely welcome to help with keeping them updated if you have the time & desire. :grin:

**Comment by mvt91** [comment]
Hi,

Thanks. I saw, with the usage, I need to improve it a little...
