### ISSUE TITLE
[Bug]: FULL OUTER JOINs are not currently supported

### ISSUE THREAD

**Issue by EkriirkE** [sqlitebrowser/sqlitebrowser#3277]
### What did you do?

Tested a working `FULL JOIN` query in the `Execute SQL` tab.  e.g.

SELECT * FROM A FULL JOIN B ON B.key=A.key

### What did you expect to see?

A resultset, empty or otherwise

### What did you see instead?

Execution finished with errors.
Result: RIGHT and FULL OUTER JOINs are not currently supported

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

6.1.10-200.fc37.x86_64

### Relevant log output

```shell
From system sqlite3 cli
SELECT sqlite_version();
    3.40.0

From Browser:
SELECT sqlite_version()
    3.34.1
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ahhhh, you'll probably need a version of this that has been compiled using that newer SQLite version (3.40.x).

Along those lines:

a. With the nightly version that you installed, where did you get it from?

b. *If* you're ok with compiling stuff, then the fastest and easiest way to get things working might be to just compile our application yourself, so it links against your system SQLite3 library:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#centos--fedora-linux

Does that help? :smile:

**Comment by justinclift** [comment]
As a potential third option, if you're ok with trying out an AppImage build, then there's a brand new one here (few minutes old) using SQLite 3.40.1:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Hopefully that plays nice with Fedora. :smile:

**Comment by EkriirkE** [comment]
> a. With the nightly version that you installed, where did you get it from?

It came as part of Fedora's normal packaging this way, so maybe I should bring this issue over to them

> b. _If_ you're ok with compiling stuff, then the fastest and easiest way to get things working might be to just compile our application yourself

No problem, and yes that worked!  Thanks!

**Comment by justinclift** [comment]
Awesome, I'll close this issue then. :smile:
