### ISSUE TITLE
[Bug]: missing MOD function

### ISSUE THREAD

**Issue by anvalanz** [sqlitebrowser/sqlitebrowser#3280]
### What did you do?

SELECT MOD(12, 3);
-- Result: no such function: MOD

### What did you expect to see?

no error about this function

### What did you see instead?

I saw the error message above.

Please note:
------------
This function (that, as you know, is equivalent to %)  was introduced in SQLite 3.35  and 
Requires the -DSQLITE_ENABLE_MATH_FUNCTIONS compile-time option

see: https://sqlite.org/forum/info/938474793fb29ef5

I am using 
DB Browser for SQLite Version 3.12.2
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8
SQLite Version 3.35.5.

Is there a  specific reason for not compiling with the required option ?

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Grab the nightly build from here, as it should work in that. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Oh, also not that the SQLite function is lower case `mod()`.  Hmmm, and now I don't remember if SQLite function names are case sensitive or not... :wink:

**Comment by anvalanz** [comment]
SELECT mod(12, 2);
-- Result: no such function: mod

SELECT MOD(12, 2);
-- Result: no such function: MOD

I have downloaded the latest version

DB Browser for SQLite Version 3.12.99 (Feb 19 2023)


Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.12.12

SQLite Version 3.40.1.


it is still not working


Antonio



Il giorno lun 20 feb 2023 alle ore 17:36 Justin Clift <
***@***.***> ha scritto:

**Comment by justinclift** [comment]
Ugh.  I was sure we build the Windows nightlies with the maths functions included, but double checking now... and you're right.  It wasn't included:

https://github.com/sqlitebrowser/sqlitebrowser/blob/494196a1619aa291e451161ce05b6e358040b61a/installer/windows/nightly_build_scripts/win64build.bat#L70

The build server use a copy of that script above, so I've just manually added the `-DSQLITE_ENABLE_MATH_FUNCTIONS` build option to it and launched the Windows 64-bit build process.  If nothing goes wrong with the build from having that option enabled, then an updated nightly build should be automatically online in about 1/2 an hour from now.

**Comment by justinclift** [comment]
And if it works, I'll add it to the Win32 build as well, plus update the build script copies in our repository.

**Comment by justinclift** [comment]
k, please try the newly built Win64 nightly from the same location.  In theory, it should work now. :smile:

**Comment by anvalanz** [comment]
SELECT mod(12, 2);
-- Result: 1 rows returned in 21ms

SELECT MOD(12, 2);
-- Result: 1 rows returned in 12ms


------------------------------------------------------------------------------
With the following version

DB Browser for SQLite Version 3.12.99 (Feb 20 2023)


Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.12.12

SQLite Version 3.40.1.


it works !


Thanks


Antonio



Il giorno lun 20 feb 2023 alle ore 19:53 Justin Clift <
***@***.***> ha scritto:

**Comment by justinclift** [comment]
Awesome.  Thanks for confirming. :smile:

I'll add that option to the bits in our repo.

**Comment by ChadSimmons** [comment]
It worked for me too.  Thanks for the update!
