### ISSUE TITLE
MacOS design 

### ISSUE THREAD

**Issue by mr-far** [sqlitebrowser/sqlitebrowser#3283]
Add modern MacOS design to SQLiteStudio, like in transmission

**Comment by justinclift** [comment]
> to SQLiteStudio

Heh Heh Heh :grin:

This GitHub repository you've created the issue in, is for a project "DB Browser for SQLite" that competes with SQLite Studio.

Maybe you want to create your issue here instead?:

&nbsp; &nbsp; https://github.com/pawelsalawa/sqlitestudio

**Comment by mr-far** [comment]
Ops
