### ISSUE TITLE
[Bug]: Cannot load extensions from SQLean

### ISSUE THREAD

**Issue by bradharms** [sqlitebrowser/sqlitebrowser#3289]
### What did you do?

I tried to load .dll extensions from [SQLean](https://github.com/nalgeon/sqlean), including `text.dll`, `crypto.dll`, and others

### What did you expect to see?

The extension should load and I should be able to use new functions from the associated .dll files in my SQL queries

### What did you see instead?

A popup error message saying "sqlite error loading extension the specified module could not be found"
![image](https://user-images.githubusercontent.com/1239044/222355642-ac855e1b-9114-4594-84a5-1c1f636b9603.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by bradharms** [comment]
Related: https://github.com/sqlitebrowser/sqlitebrowser/issues/267

**Comment by bradharms** [comment]
Figured it out. I installed the 32-bit version of SQLite Browser but I was trying to load 64-bit DLLs. I solved it by installing the 64-bit version of SQLite Browser instead, and it loads the extensions just fine.

**Comment by justinclift** [comment]
Awesome, glad you got it figured out. :smile:
