### ISSUE TITLE
Plot not showing graph 

### ISSUE THREAD

**Issue by mimills09** [sqlitebrowser/sqlitebrowser#3290]
Details for the issue
--------------------

Someone was using my computer to use DB browser and now the plot window shows only the filters to select and no graph. 

#### What did you expect to see?
See a graph. 

#### What did you see instead?
Only the axis to select, no chart. 

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19044) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by mgrojo** [comment]
You should be able to restore it in "View > Plot" or pressing Ctrl+D

**Comment by mimills09** [comment]
I'll try control d, but the other option hasn't worked.

**Comment by mgrojo** [comment]
Add a screenshot if it's still not working.

**Comment by mimills09** [comment]
Did not work, this is what I see:
[image: image.png]
I expect a graph to be in the plot window. I have tried uninstalling and
reinstalling the program and that did not work. Someone x out of it when
using my laptop (the pop out) and it hasn't reappeared.

The pop out is not behind another tab or window either.

**Comment by chrisjlocke** [comment]
> this is what I see

Email attachments don't appear in this thread.  If you can paste directly here, that'll be helpful.

**Comment by chrisjlocke** [comment]
Email attachments don't appear in this thread.  This is what I meant by 'Email attachments don't appear in this thread.'
You can't attach email attachments in an email as Email attachments don't appear in this thread. 

If you can paste directly here, that'll be helpful.  That means visiting this page:
https://github.com/sqlitebrowser/sqlitebrowser/issues/3290
in a browser, and pasting the image into the textbox area at the bottom of the window.

Unfortunately Email attachments don't appear in this thread, so any email attachments in an email don't appear in this thread.

**Comment by mimills09** [comment]
<img width="1123" alt="DbBrowser Plot Issue" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/126927254/13b67f28-6c77-4bbb-aac5-b2bf79fed9a0">
Thank you, it is now attached.

**Comment by mgrojo** [comment]
It's probably collapsed. If you hover your mouse between the frame with the combo-boxes and buttons and the list of fields (in your case below the scroll bar), your mouse pointer should change to a two-headed arrow. Drag that border and you should get your graph back. Otherwise, I don't know what's happening.

**Comment by mimills09** [comment]
Yes that was it! Thank you!

**Comment by mgrojo** [comment]
You're welcome! As always, an image is better than a thousand words.
