### ISSUE TITLE
[Bug]: DB Browser for SQLite New database not responding

### ISSUE THREAD

**Issue by nhc112** [sqlitebrowser/sqlitebrowser#3292]
### What did you do?

Open DB Browser and create a new database.

### What did you expect to see?

I can create a database

### What did you see instead?

DB browser not responding

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by nhc112** [comment]
I have downloaded many versions of DB Browser, but very unfortunately they don't work, after clicking Create Database.

**Comment by justinclift** [comment]
Ouch.  Having the application hang when you click the button to create a new database... is clearly not supposed to happen. :frowning:

That being said, that kind of sounds like your OS (Windows) is having trouble opening the default folder or something

A couple of questions, as it will probably help us figure out what is going wrong:

1. Are you downloading and running the .msi versions of our application, or are you using the .zip file downloads?
   * This might make a difference
2. Have you tried the latest nightly download?
   * https://nightlies.sqlitebrowser.org/latest/
3. If the latest nightly download doesn't work, then try one from last week or so.  A day or two ago I changed the version of SQLite we in our nightly builds, which might have broken something accidentally.
   * https://nightlies.sqlitebrowser.org/win64/

**Comment by chrisjlocke** [comment]
Have you run DB4S successfully in the past?  What it usually does is try and open the last location you saved the database to.  If so was this on a network location?  

We could try removing the registry information stored.  A setting might be screwy.  It does involve editing the registry but its a painless exercise.

![image](https://user-images.githubusercontent.com/7872218/222919835-cb8ee1f7-04ad-446e-a5c6-798ea1f9cda6.png)

With DB4S **not** running, open Registry Editor, navigate to Computer\HKEY_CURRENT_USER\Software\ and rename the **sqlitebrowser** entry to something else, eg, sqlitebrowser1

Restart DB4S and see if the issue is resolved.

**Comment by chrisjlocke** [comment]
I'll close this as it's been two weeks without a response.
@nhc112 - feel free to comment and it can be reopened.

**Comment by CathyPPPP** [comment]
I think I have met similar issue. I can create an empty database, but once I try to add the name of the table or any columns info. it just shows not responding. I have tried the nightly version, doesn't work. My OS version is win10.

**Comment by chrisjlocke** [comment]
Is the database local, or are you storing it on a server or something?
We've not had many issues of this, so I don't believe its an application issue.
There is a program called whatishang which may help diagnose where its getting stuck.
Does it do it every time - even after a reboot?

**Comment by chrisjlocke** [comment]
Thanks for using whatIsHang.  Unfortunately it didn't really give a clear indication.  Well, not that I can see, anyway.
We do have a large number of nightlies on the server.  
https://nightlies.sqlitebrowser.org/win32/

I'd try going back a couple of years and seeing if an older version worked, and either going forward or back depending on success or failure.  At 'some point' I'm hoping its either a Qt version or some weird file which is causing the issue.
The alternative, which isn't great, is if you're using Windows 11, can you use the 'sandbox' feature?  This is a virtual Windows which is pretty much stock .. but you need the pro version.  Or if you have VMWare or VirtualBox?

**Comment by CathyPPPP** [comment]
> Thanks for using whatIsHang. Unfortunately it didn't really give a clear indication. Well, not that I can see, anyway. We do have a large number of nightlies on the server. https://nightlies.sqlitebrowser.org/win32/
> 
> I'd try going back a couple of years and seeing if an older version worked, and either going forward or back depending on success or failure. At 'some point' I'm hoping its either a Qt version or some weird file which is causing the issue. The alternative, which isn't great, is if you're using Windows 11, can you use the 'sandbox' feature? This is a virtual Windows which is pretty much stock .. but you need the pro version. Or if you have VMWare or VirtualBox?

Well...I tried to restart my computer, the browser works fine... It seems just because I haven't restarted my computer for a while which causes some conflicts at the backend? Thanks for your help and quick response anyway!

**Comment by chrisjlocke** [comment]
Glad you got it resolved. 👍

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/07f85528-d618-46a4-8918-34d5d433c72d)
