### ISSUE TITLE
ExucuteSQL tab

### ISSUE THREAD

**Issue by felagund18** [sqlitebrowser/sqlitebrowser#330]
When writing unicode characters in executeSqlTab, it instantly becomes a question mark "?"...

текст -> ?????

**Comment by schdub** [comment]
@felagund18, thanks for reporting but this issue already fixed.

You should use our nightly build (http://rp.oldsch00l.com/sqlitebrowser/) or wait until version 3.7.0 is finally will be released.

See: #282.
