### ISSUE TITLE
[Bug]: $ brew install sqlitebrowser - not available

### ISSUE THREAD

**Issue by mikeg-asi** [sqlitebrowser/sqlitebrowser#3305]
### What did you do?

Hi. According to BUILDING.md it is possible to install sqltebrowser as a single application instead of bundle on MacOS. However this does not appear to be available in homebrew.  Is a single application still an option?  Thanks!

### What did you expect to see?

Was hoping that it could be a single executable instead of bundle.

### What did you see instead?

brew reports
`Warning: No available formula with the name "sqlitebrowser".`

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

MacOS 12.5.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
The BUILDING.md file appears to be outdated. Single executable binary cannot be installed via Homebrew at this time.
However, if you want a single executable binary you can build it yourself.

Delete `MACOSX_BUNDLE` on line 26 of the CMakeLists.txt file.
https://github.com/sqlitebrowser/sqlitebrowser/blob/b2e2a52f78a241196ee5b90ac2f753d9b34b7077/CMakeLists.txt#L25-L26
to be
```cmake
if(APPLE)
    add_executable(${PROJECT_NAME})
```

Delete lines 602 through 608 in the CMakeLists.txt file.
https://github.com/sqlitebrowser/sqlitebrowser/blob/b2e2a52f78a241196ee5b90ac2f753d9b34b7077/CMakeLists.txt#L602-L608
and then, when you build it, it will create a single executable binary called `sqlitebrowser.`
If you need any additional help,. feel free to leave a comment. Thanks!

**Comment by lucydodo** [comment]
Close the issue because there has been no response for a long time.
Anyone can reopen the issue at any time if needed.

**Comment by martin-braun** [comment]
@lucydodo Just found this project and tried to install it via `brew install --cask sqlitebrowser` as well as `brew install sqlitebrowser`. It would be nice to have this on Homebrew.

**Comment by scottfurry** [comment]
For the next person...

**Comment by martin-braun** [comment]
@scottfurry Sure thing, this is what I did, but it wasn't clear to me that I have to search for a "formal" name. I just tried to install this and was surprised to actually get what I initially wanted.

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/232398564-f9631b25-70b8-4652-ba73-46d0bd97f95d.png)

Did you not see the macOS section on the github readme.md page?

We strive to make the documentation clear and easy to follow, so if you expected it to be in another place, or looked somewhere else and the details weren't there, let me know.

**Comment by martin-braun** [comment]
@chrisjlocke My bad. I missed this in hesitation, it's on me.

**Comment by chrisjlocke** [comment]
No problem - was just making sure.  We have the sqlitebrowser.org website which is laid out more differently than the github repo, so its hard to maintain the balance of giving info in the right place without duplicating everything everywhere.
Its the same when you lose your car keys.  Where you start looking for them is where you should be putting them in future ... ;)

**Comment by scottfurry** [comment]
> Its the same when you lose your car keys. Where you start looking for them is where you should be putting them in future ... ;)

"Located in a convenient location that I have completely forgotten about..." - me some days.

**Comment by chrisjlocke** [comment]
Have you ever looked for something that you know you have but don't use often, eg, a funnel, or upholstery vacuum attachment.  Can't find it anywhere.  End up buying another.  Think, 'right, I'm going to store this here so I don't have to buy an...... damn.  Found it.'.  Now you have two funnels.

**Comment by martin-braun** [comment]
@chrisjlocke Okay then, I will be so free to share what I was looked for, so you can decide if the keys should be re-organized. I was looking for a big header "Installation". But, I could've just do a text search for "brew" honestly. If I don't want to read the docs, I should deal with the consequences. Easy that is. ;)
