### ISSUE TITLE
Close button & other enhancement

### ISSUE THREAD

**Issue by tbayart** [sqlitebrowser/sqlitebrowser#331]
Hi, I would like to suggest a "Close database" button beside the "new" and "open" buttons.

A better enhancement would be a tab in settings to select active buttons in a list of possibilities allowing users a bit of customization.

**Comment by justinclift** [comment]
Hmmm, I have no strong objection to adding a Close database" button.  It would be useful for people.

The idea of having a list (in Preferences area?) to allow customisation of buttons does sound really good though. :smile:

Out of curiosity, do you have skill with C++ and/or Qt? :smile:

**Comment by tbayart** [comment]
I don't know about Qt
I'm a bit skilled with C++ but I'm not up to date since I didn't used it for 5 years
I could contribute with code, I have to free up time

**Comment by justinclift** [comment]
That would be great. :grinning:

**Comment by mgrojo** [comment]
I think we have space in the DB toolbar for adding more buttons, like close, attach, etc. Regarding customization, it is not simple to do, except if we leave the setting at the toolbar level. I think we could add one or more toolbars and let the user configure which one he/she wants to view. The only contra is that he/she will only free up space when all the toolbars are disabled (I personally hide the DB toolbar).

We could add an Extra DB Toolbar (Close, Attach) and a Project Toolbar (Open, Save), or do whatever reorganization of the current tool buttons, for example:
- DB Toolbar: New, Open, Attach, Close
- Data?, Change?, Transaction? Toolbar: Write Changes, Revert Changes
- Project Toolbar: Open, Save

If this is welcome I could contribute the implementation.

**Comment by justinclift** [comment]
Yeah, I'd welcome us having some extra buttons on the toolbar too.

Bearing in mind the UI still needs to "look approachable" for new users who are unskilled with SQLite (or even SQL in general).  That shouldn't be too hard to manage though. :smile:

**Comment by mgrojo** [comment]
@tbayart Are you still using DB browser for SQLite? We've finally added the Close Database button among other improvements like two new toolbars and toolbar style configuration. If you'd like to take a look at the new version, you can try with the nightly build: https://nightlies.sqlitebrowser.org/latest/

**Comment by tbayart** [comment]
Hi, I'm not using sqlitebrowser actually.
I downloaded latest version from nightly build link for a quick test and it worked fine.
Good job @mgrojo :1st_place_medal:

**Comment by mgrojo** [comment]
Thanks for testing it, @tbayart. We can close this issue now.

**Comment by justinclift** [comment]
Just tried this out quickly, and it looks great.  Still looks friendly for new users too (my opinion). :smile:

![screen shot 2017-12-06 at 16 13 08](https://user-images.githubusercontent.com/406299/33671882-b4d0c168-daa0-11e7-8b67-d302137a9425.png)

Awesome stuff @mgrojo. :smile:

**Comment by justinclift** [comment]
Not sure if "DB Toolbar", "Extra DB Toolbar", and "Project Toolbar" are the wording choices... but I'm not thinking of any better ones either at the moment.  They're good enough to start with. :smile:

**Comment by mgrojo** [comment]
Thanks, @justinclift :+1: 

The wording and grouping of buttons in toolbars could be changed easily. I wrote another idea for the grouping above, but finally didn't want to touch the current DB toolbar, just in case people is accustomed to it. But then the Extra DB has a somewhat arbitrary division and naming :smile:

**Comment by chrisjlocke** [comment]
Just a slight 'worry' is that now the 'Open Project' and 'Save Project' have been removed from the 'File' menu, it reduces the accessibility of the product for non-mouse users.  I can't see many non-mouse users using the product, but I've always been taught (although the design spec is shifting) that the menu options should house all  available options, regardless of whether there are menu buttons for them (which can't be easily accessed via the keyboard alone).
Its also slightly inconsistent as 'Attach' and 'Close Database' remain in the File menu even though they have toolbar buttons.
Just another slight 'inconsistency' in that hovering over 'Open Project' and 'Save Project' display a message in the status bar, while the 'Attach Database' and 'Close Database' don't.  Not even sure they should if we also provide tooltips?  Seems overkill...
Also ('oh shut up Chris!') when you click 'Open Project', the dialog shows 'Choose a file to open' which should really just say, "Open Project"

**Comment by mgrojo** [comment]
@chrisjlocke Thanks for pointing this out. Specially the one about Open Project and Save Project. You can consider them bugs. My intention was to copy them to the toolbar. You have to press control while you drag and drop them in qtcreator, otherwise they are moved. They are the same object, so all the properties in the menu are also set in the toolbar. I'll rectify that and take a look to the other mentioned issues.

**Comment by mgrojo** [comment]
The inconsistencies should  be fixed now with a4728ff5f6f3376b2e2a71e6d1920602e0cf7756. (I forgot to reference this issue)

I haven't changed the  'Choose a file to open' message. Not sure about it. We have also this:
```
EditDialog.cpp:300:                tr("Choose a file")
EditDialog.cpp:337:                tr("Choose a filename to export data"),
ExportDataDialog.cpp:278:                tr("Choose a filename to export data"),
ExportDataDialog.cpp:304:                    tr("Choose a filename to export data"),
ExportSqlDialog.cpp:87:                tr("Choose a filename to export"),
MainWindow.cpp:383:                                                   tr("Choose a filename to save under"),
MainWindow.cpp:1347:                tr("Choose a file to import"),
MainWindow.cpp:1364:                    tr("Choose a filename to save under"),
MainWindow.cpp:2054:                                                tr("Choose a file to open"),
MainWindow.cpp:2202:                                                    tr("Choose a filename to save under"),
PlotDock.cpp:420:                                                    tr("Choose a filename to save under"),
```

Maybe: 'Choose a project file to open' ?

**Comment by justinclift** [comment]
"Choose a project file to open" sounds good to me. :smile:

**Comment by mgrojo** [comment]
Let's close this since all the commented issues are addressed. If anyone has good ideas on how to distribute or name the toolbars can feel free to open a new issue or reopen this one.
