### ISSUE TITLE
foreign key

### ISSUE THREAD

**Issue by aymmm48** [sqlitebrowser/sqlitebrowser#3313]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.22621) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by justinclift** [comment]
Hi,

Did you need assistance with something, or was creating an issue here accidental? :smile:

**Comment by chrisjlocke** [comment]
Closing due to lack of details.
@aymmm48 - please give more information and we can reopen this to assist.
