### ISSUE TITLE
[Feature]: sqlean (SQLite Libaries)

### ISSUE THREAD

**Issue by cbitterfield** [sqlitebrowser/sqlitebrowser#3316]
### Describe the new feature

These are additional libraries like expanded regex and stats.

### Does this feature exist in another product or project? Please provide a link

https://github.com/nalgeon/sqlean

### Do you have a screenshot? Please add screenshots to help explain your idea.

These libraries work in the MacPorts version of your application. They can't be used as a plugin because you compiled it as a "Hardened Runtime". It would be good if you could have a version that includes these libraries.

**Comment by justinclift** [comment]
That sounds like a decent idea.  I'll try and get that added to our nightly builds sometime soon-ish, and we can see how well it works.

If you don't hear from me in about a week, please feel free to bump this issue to remind me.  That's a good thing to do, rather than unwelcome. :smile:

**Comment by lucydodo** [comment]
Now we have the `sqlean` library built-in. This release is available via the latest continuous build or nightly build.
- Continuous: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
- Nightly: https://nightlies.sqlitebrowser.org/latest/

Related issue: #3357, I'm closing the issue for now, but if you have any other comments or issues, feel free to reopen it. :)
