### ISSUE TITLE
MATH FUNCTION IS NOT WORKING FOR CEIL OR CEILING ON SQLite Version 3.35.5.

### ISSUE THREAD

**Issue by momoLyu** [sqlitebrowser/sqlitebrowser#3319]
Details for the issue
--------------------

#### What did you do?
UPDATE  SQL SYNTAX
MATH FUNCTION IS NOT WORKING FOR CEIL OR CEILING ON SQLite Version 3.35.5.

Execution finished with errors.
Result: no such function: CEIL
At line 1:

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19045) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
"but are only active if the amalgamation is compiled using the [-DSQLITE_ENABLE_MATH_FUNCTIONS](https://www.sqlite.org/compile.html#enable_math_functions) compile-time option"

I don't think this was enabled in the release version.
However, I believe it was enabled recently, so the nightlies might have it enabled.

As you're on Windows, you can download the .zip, extract it, and run it - it doesn't need installing.

**Comment by chrisjlocke** [comment]
Just tried the nightly and does seem to work OK.

![image](https://user-images.githubusercontent.com/7872218/230785595-10e422f2-c52b-4d62-873b-6514631ed049.png)

**Comment by momoLyu** [comment]
I tried the new version 3.12.99.
Here are a few things I found.
1. the ceil maths function now works. [Positive].
2. the UI cannot be updated automatically. This means that the sql has been executed, but the UI in the database structure tab and the browse data tab does not change unless you refresh the data. [Negative].

----- 原始邮件 -----
发件人：Chris Locke ***@***.***>
收件人：sqlitebrowser/sqlitebrowser ***@***.***>
抄送人：momoLyu ***@***.***>,  Author ***@***.***>
主题：Re: [sqlitebrowser/sqlitebrowser] MATH FUNCTION IS NOT WORKING FOR CEIL OR CEILING ON SQLite Version 3.35.5. (Issue #3319)
日期：2023年04月10日 00点50分


Just tried the nightly and does seem to work OK.

**Comment by chrisjlocke** [comment]
> the UI cannot be updated automatically

This doesn't seem relevant to the issue raised.  Is this a new issue?  Ideally separate issues that are not related need to be in separate issues.  If you can raise a new issue showing screenshots of this, it can be looked into.

I believe that if DB4S knows of a database change - eg, you add a field within DB4S - then the UI is refreshed.  It doesn't continually poll the database determining if the schema has changed - this would be highly inefficient.

**Comment by chrisjlocke** [comment]
> the ceil maths function now works.

Closing as completed.
