### ISSUE TITLE
Note on updating to 64-bit version

### ISSUE THREAD

**Issue by ronCYA** [sqlitebrowser/sqlitebrowser#332]
The new 64-bit version is obviously not an update but a completely separate program to any existing 32-bit installation. Certainly not a bug by any means, but perhaps a note could be included somewhere for unaware users.

I was unaware of sqlitebrowser's 32-bit-only history and just assumed it had always come in 64-bit offerings when I saw the 64-bit download. As a result, my head got scratched a few times when it kept asking me to install 3.60 even after updating. It only dawned on me when I uninstalled 3.60 and still saw 3.40 sitting in my x86 folder :)

**Comment by justinclift** [comment]
Ahhhh, interesting thought.  I guess we could put something in the Release Notes page.  Does that sound like a decent spot to you which people would generally see?

**Comment by ronCYA** [comment]
Well, I can think of at least two ideas.

The most useful spot would be in the 'There is a new version, please download' pop-up alert that appears, since it's what triggers most users to download the new version in the first place. Having such a note would clutter up the alert window though, and wouldn't be relevant to someone updating to a 32-bit version or (eventually) from a 64-bit version.

The neater solution is to have the installer detect existing 32-bit installations as well and uninstall them before continuing. This turns into a much bigger implementation though, with the need to migrate user configs/etc to the new directory in addition to the 32-bit detection.

Not a critical issue now but maybe something to think of down the line? I'm sure this happens in countless other projects too- maybe others have addressed the issue elegantly before.

**Comment by ronCYA** [comment]
Can do! Need to work on some projects at the moment but will be sure to
find some time this weekend for you. Great to hear about your progress :)

**Comment by justinclift** [comment]
Thanks @ronCYA. :smile:

**Comment by justinclift** [comment]
@ronCYA ping? :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
