### ISSUE TITLE
inserer des données dans une table existante

### ISSUE THREAD

**Issue by Delgres1** [sqlitebrowser/sqlitebrowser#3326]

**Comment by lucydodo** [comment]
Do you want to insert data into an existing table? Can you elaborate a bit more? (e.g. import from a csv file)

**Comment by justinclift** [comment]
Closing this, as it seems like an accidentally created issue or something.

**Comment by lucydodo** [comment]
so I remove response requested label.

**Comment by Delgres1** [comment]
> 

Hi Lucydodo 
Sorry for late response 
i wanted to add data from csv file  or feed my database with new data for *.csv

**Comment by justinclift** [comment]
No worries.  The application has a dialog just for that.

Just open your existing database (make a backup first!), then launch the CSV importer:

![image](https://user-images.githubusercontent.com/406299/233786215-14a95c81-c5e7-438e-af02-e6404c70d855.png)

The options are *reasonably* straight forward.  Try things out, and if you have any problems then let us know. :smile:

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
@Delgres1 - Hopefully the above screenshot has helped, but yell back if it hasn't.
