### ISSUE TITLE
Commenting / uncommenting problem with fields containing diacritic signs

### ISSUE THREAD

**Issue by DainiusPythonPTU11** [sqlitebrowser/sqlitebrowser#3328]
### What did you do?

![Screenshot 2023-04-20 063434](https://user-images.githubusercontent.com/128691143/233256401-57e628e1-077b-4d3f-b352-13950b130fb0.jpg)
.
.
.
![Screenshot 2023-04-20 064004](https://user-images.githubusercontent.com/128691143/233261468-3ec7922a-4a49-4441-8825-f497feccf2ff.jpg)
.
.
.
![Screenshot 2023-04-20 064123](https://user-images.githubusercontent.com/128691143/233254455-e65f79a1-e045-4f5a-b7e3-ec5afdd98f32.jpg)

After changing letter 'Ė' to 'E' everything was fine.

By the way, for testing you can try any diacritic sign.

### What did you expect to see?

FROM

### What did you see instead?

\- ROM

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 Pro 22H2 64-bit

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Oh, that's interesting.  In theory, we shouldn't be having any kind of unicode support problems.  However, clearly that theory isn't working out properly.  :facepalm:

Out of curiosity, if you try the latest nightly build is it still broken?  We've improved a *lot* of stuff since the last release, so there's a fair chance the behaviour around this has changed too:

https://nightlies.sqlitebrowser.org/latest/

**Comment by DainiusPythonPTU11** [comment]
Unfortunately, the same with DB Browser for SQLite Version 3.12.99 (Mar 26 2023)...
By the way, this is an old problem. It existed in previous versions too.

**Comment by justinclift** [comment]
No worries, thanks for confirming it's still a problem with our latest code too.  Sounds like something we'll want to look into. :smile:

**Comment by chrisjlocke** [comment]
Sounds like a trip up with length .. assuming its the number of bytes not characters.  Or the other way around.

![image](https://user-images.githubusercontent.com/7872218/233342688-70ba35f8-9ee8-4997-99e3-9cbf75bbd89d.png)

So I bet if you add two Unicode characters, you'd lose another character.

**Comment by mgrojo** [comment]
We were counting bytes, not characters, and then we used that number for something that expected bytes. Typical problem with UTF.

@DainiusPythonPTU11, If you could test it in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds), we will be able to close the issue with confidence it's now working fine.
