### ISSUE TITLE
Unrecognized token: "@" when query a column that use @ symbol

### ISSUE THREAD

**Issue by icol2006** [sqlitebrowser/sqlitebrowser#333]
Unrecognized token: "@" when query a column that use @ symbol

**Comment by schdub** [comment]
@icol2006, please provide example of your table and query.
Maybe your query should be something like:

   SELECT `D@ta` FROM `foo`;

**Comment by icol2006** [comment]
CREATE TABLE `Testing` (
	`id_@`	text,
	`name`	text,
	`adress`	text)

select id_@ from testing

**Comment by schdub** [comment]
@icol2006, escape field name with "" or [] or ``: 

    CREATE TABLE Testing ([id_@] text, name text, adress text);
    INSERT INTO Testing ([id_@], name, adress) VALUES(1, "test", "test");
    SELECT [id_@] FROM Testing;

http://stackoverflow.com/questions/2901453/sql-standard-to-escape-column-names

**Comment by justinclift** [comment]
Awesome @schdub.  I just learned something new too. :smile:
