### ISSUE TITLE
Add a different default view to transpose rows/columns

### ISSUE THREAD

**Issue by fmendels** [sqlitebrowser/sqlitebrowser#3330]
Hi,

I have had some requests about getting a different view of the table content, to be able to edit all fields in a row at once.
It could also be handful to have a transposed rows/columns view by default in Edit/Preferences, and through a UI button.
Do you think it is possible to get these features in the coming version?
Thanks & BR,
FM

**Comment by justinclift** [comment]
Hiya,

For the first one (all fields be editable at once), I'm trying to imagine what that would look like in practise.

So far, what I'm thinking of is something like "click a row, and it turns into one long text field, separated by commas (or whatever delimiter".  Thinking about it, that could actually be pretty useful.

The second one though (transposed rows/columns) I'm really struggling with.  Can you explain more of that concept, as to me it's (so far) just sounding like "I'd like a table a million rows wide" (as an example), so it's not making sense to me yet. :smile:

**Comment by fmendels** [comment]
Hi,
Thanks for your answer. Being able to modify a row  at once is truly an improvement on our side, as our users need to be able to edit all fields of a row at once. 
For this purpose, I was thinking of a classic "window-like" approach containing all fields where you can go from one field to the other with Tabs, not loosing the overall picture of the all data on a row.

As I said, the users I am working with are really into looking at all columns at once and scrolling on the side to look at more rows if they are present. I know it's a bit specific, and our tables do not have a million rows obviously. That's why I thought of reversing the way the tables are displayed (transposing rows and columns as in a matrix environment). This way, the users can also go through rows and keep the overall view of the row at once.

I hope my explanations are bringing a bit of clarity to my original request.

Thanks again,
BR,
FM

**Comment by justinclift** [comment]
Ahhh.   In the Browse Data tab, you already can move between fields when in edit mode by using tab. eg Click on a field to switch into Edit mode, and from there on you just need to click Tab for that field to be committed with its new value + your cursor to be moved to the next field (still in edit mode).

It's reasonably quick for entering a bunch of values into the fields of a row.

eg: Typing `1` <kbd>TAB</kbd> `foo` <kbd>TAB</kbd> `bar` <kbd>TAB</kbd> etc ... to fill out fields.

**Comment by justinclift** [comment]
Thinking through the transposing thought, I think that would actually be pretty complicated to implement (for us).

At least if we were to do it properly. :thinking:

As a different approach, have you considered using some kind of form design tool (maybe [LibreOffice Base](https://www.libreoffice.org), or perhaps even something like [Database Designer](https://github.com/emily-elizabeth/Database-Designer))?

That would let you design & customise the user interface fairly easily, and also have the data be kept in a backend database you'd be able to use the more standard tools on as well.

**Comment by fmendels** [comment]
Hi,
Yes, I know about the Browse data tab. It is very helpful and useful. However, when you have several columns (more than can be displayed), the users I am talking too cannot have the complete view of the record, and this is what is missing for them.
That's why I came up with the transposing button solution. I understand that a clean implementation of it is not straightforward.

I have not tried other tools, because yours is really complete and practical, but I will, and see if it can fit this need or not.
Thanks for the tip and answers !
BR,
FM

**Comment by justinclift** [comment]
You're welcome @fmendels. :smile:

**Comment by chrisjlocke** [comment]
> However, when you have several columns (more than can be displayed), the users I am talking too cannot have the complete view of the record

Don't forget you can create a view and edit the view.  This isn't automatic and does require some triggers, but could be a solution.

The other obvious solution is to use a third party utility.

The beauty of SQLite is that pretty much any language can plug into it.  

![image](https://user-images.githubusercontent.com/7872218/234252988-65560274-b1ca-414b-9ea5-dc7b76a901d4.png)

I thought there was a 'freeze column' option (which would be useful) but there is 'hide column' option.  This means you can at least hide the columns you don't want, which can save some screen real estate.

**Comment by fmendels** [comment]
Hi,
Yes the freeze option would be good as well for the display, as while scrolling, you would keep the columns you always want to see.
The View option is not obvious as you cannot edit the values directly.
Thanks for the tip,
BR,
FM

**Comment by chrisjlocke** [comment]
> The View option is not obvious as you cannot edit the values directly

The view is a mix between the 'hide columns' and show columns in a specific order.

![image](https://user-images.githubusercontent.com/7872218/234266610-5b38c0b2-5d4c-4c44-be3b-2b8891105644.png)

There is a wiki page on editing views, but essentially you right-click on the header and select 'unlock view editing'

**Comment by fmendels** [comment]
Ok, thanks, I will have a look at this too.
BR
F

**Comment by justinclift** [comment]
> There is a wiki page on editing views

This seems like the one:

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views#editing-data-in-a-view
