### ISSUE TITLE
[Feature]: Add a CHANGELOG.md file

### ISSUE THREAD

**Issue by richb-hanover** [sqlitebrowser/sqlitebrowser#3334]
### Describe the new feature

I am a long-time fan of SQLite Browser. I see that the 3.12.2 version has been out for quite a while, but also that there are continuing developments, new versions of SQLite, bug fixes, etc. Since I don't check back very often, it's hard for me to know whether it's worth upgrading. 

The folks at [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) have created sensible, low-effort guidelines for maintaining a CHANGELOG.md file that keeps us dabblers informed of interesting changes.

You wouldn't have to spend a lot of time to create a CHANGELOG.md file. Just start by noting 3.12.2's major features, the date it shipped, and mark it as [Released]. Then add entries for the big things that have gone into the nightlies, along with their rough dates. That'll catch everyone up to the current state. 

And as you make continued improvements, you can add a short description to the CHANGELOG.md. (This also has the benefit that when you formally release a new version, the release note have (mostly) already been written...)

Thanks for listening!

### Does this feature exist in another product or project? Please provide a link

Yes - [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) 

### Do you have a screenshot? Please add screenshots to help explain your idea.

See the link above

**Comment by lucydodo** [comment]
This seems like a very reasonable suggesntion for me.
Although I could write the 'CHANGELOG' and open a PR for you to review, but-
As an open source project, We're open to contributions too. Which do you prefer? 😄

**Comment by richb-hanover** [comment]
I made a PR (above) for a first cut at a CHANGELOG file. I spent (only) three minutes going through recent commits to make the list of changes for the **Unreleased - nightly** section. It's probably good enough to start, and someone who knows the project can pick out a few more important enhancements that should be mentioned. Thanks!

**Comment by justinclift** [comment]
Sure, lets try it out and see how it goes. :smile:

**Comment by lucydodo** [comment]
I just reviewed the PR and merged it. I'm closing the issue accordingly. Thank you!

**Comment by richb-hanover** [comment]
You're quite welcome!

**Comment by richb-hanover** [comment]
@mgrojo @lucydodo @justinclift  - I'm just being a bit of a noodge here... (hope it's not unhelpful).

Part of the "beauty" of a CHANGELOG is that, if you update the CHANGELOG file every time you commit changes, it makes the Grand Release Day much easier. You just update the **[Unreleased - nightly]** heading with the version and date, and Presto! it's ready to roll... 

I'm hoping the remainder of work on the release is going smoothly. Thanks as always!

**Comment by lucydodo** [comment]
I've been thinking about this lately, and I think it often gets missed because we're not in the habit of revising the changelog every time, so I've been thinking about automating it on a weekly basis.
@mgrojo, @justinclift Do you have any other thoughts? 🤔

**Comment by justinclift** [comment]
A manual process for doing it every time probably isn't going to work for us, as it's too prone to failure if someone forgets even once.

Something automatic would definitely be way more preferable, if it's accurate. :smile:

**Comment by richb-hanover** [comment]
My two cents, having maintained a changelog for a commercial product a dozen years ago...

1. I recognize this is a change to the ethos/practice of the project. I don't want to impose any harsh obligations on a project that's being done for love.
2. It's useful to write the Changelog message when doing the commit because it's fresh in your mind. You have at your fingertips all the Issues and Discussions that went into the commit.
3. It's not a big deal if someone misses a commit. Either someone notices (hey, we implemented XYZ last week, so I added a changelog entry for it today) or it'll get picked up in the final review before release. But most of the changes will have been entered already so the final check is not a huge task.
4. There are automated tools that scrape git commit messages to create a changelog (I don't remember any names) but they run the risk of simply dumping in the commit message. That text might be too specific, or too general. 
5. Toward that end, I'm partial to changelogs that give a little context to the fix. Having a human write a couple sentences like, "fixed a bug where all 'e's were converted to 'X'" or "Added a new foo option to the charting. See [link to new option docs]" leads to a good changelog.

That said, this isn't my project, and I don't want you to change anything that would decrease the fun of participation. Thanks for listening.

**Comment by lucydodo** [comment]
Yes, I undertsand and sympathize with what you're saying.
But I was mentioned automation because we ourselves often forget to update the changelog. Of course, we could make PR reviews mandatory, or use hooks to make sure we don't miss them, but I don't want to introduce that kind of enforcement.

However, based on what you said, I would suggest the following:
1. Automatically dump and update the commit history every week
2. Include a link to a wiki about this at the top of the changelog
3. Write a changes in a user-friendly way, not just a simple dump, as you said in that wiki.
That way, if we miss a changelog, we can always add it (without cluttering up the commit history),
and we can count on community members to help.

@richb-hanover What do you think about my suggestion? :)

As an aside, the new improvements to changelog will be applied after the next release* is complete.
(too may changes to apply now)

> *: The next release was originally planned for Monday of this week,
> but due to soem critical issues being reported, it was delyaed until those issues were resolved.

**Comment by mgrojo** [comment]
In my opinion, automation doesn't make sense here, since the changelog has to be useful for the users, and a dump of the commit log is not only unreadable and too detailed for users, it's also redundant if the same information is in another place.

For me, what we are doing in https://github.com/sqlitebrowser/sqlitebrowser/releases is the correct content, something informative and useful for our users. The main differences of this proposal and GitHub's Releases section is whether the information is in the repository itself, and whether the information is written little by little or at release time. Doing it at the end might seem more work, but it also gives us the opportunity to correctly summarize all what we have done for the users, so I don't dislike that approach. Other advantages are that we don't need to "educate" occasional contributors, and we don't have to fix conflicts due to editing always a central file.

In any case, if we go for the CHANGELOG.md, what I wouldn't do is to include any kind of automation there, we should aim to have a similar content to what we have in Releases, but keeping it up to date as we implement new features or fix bugs. Important is also not to mention bugs that were not present in the previous release, but introduced in our development process between releases; for those cases, it's enough to have them detailed in the commit log and the issue tracker; only involved users are interested.

**Comment by lucydodo** [comment]
@mgrojo Thank you for your thoughtful comments. So what about below?
Put a link to our wiki in `CHANGELOG.MD`, and continue to track changes in that wiki page (I'll take over update). If we do this, I think we can also implement some automation to write new release notes based on the changleog you mentioned.

**Comment by richb-hanover** [comment]
@lucydodo @justinclift I had already prepared a longer response, but @mgrojo has said what I want to emphasize: the changelog is to tell users what to expect.

Using git commits as a base tends to include a lot of fussy details. For example, when I look at https://github.com/sqlitebrowser/sqlitebrowser/commit/ca257ffcfaaa704cf24cdffc9e2265a992417c67, I can see that @lucydodo spent a lot of time creating it. But it's hard to see the "real changes" from that list.

I _do_ think it's important to have a human writing the changelog entries. Maybe having a weekly process to remind about the recent commits could work. We could then review the commits and update the CHANGELOG to summarize what happened. User-facing changes additions are important; breakage/deprecations are critical; back-end/CI changes not-so much, and maybe don't warrant an entry. 

As always, thanks for listening.

**Comment by lucydodo** [comment]
> Sorry, I forgot to comment on this, I remembered when I saw you commented on the other issue.

Yes, I agree with both of you. After next release, I'll try to write a changelog user-friendly myself. :)

**Comment by richb-hanover** [comment]
And since I've kicked over this hornet's nest :-) I'll take a stab at distilling the existing CHANGELOG to something manageable. (Yikes - you folks have done a LOT of work on this!) Look for something in 24 hours in this issue

**Comment by justinclift** [comment]
Heh Heh Heh.

@richb-hanover You keep on putting time into doing useful stuff, so I've just sent you a team invite.  Just in case. :wink:

**Comment by richb-hanover** [comment]
_As promised, here is a draft/proposed CHANGELOG.md file. Here are the important points:_

- _I made a stab at categorizing all the entries in the current CHANGELOG.md file. I am only guessing..., so please feel free to recategorize these as needed._
- _The top five headings (Added, Changed, Fixed, Removed, Translations) summarize the important changes that people will notice/want to know about._
- _The level of detail in each of the General/Appearance/SQL/Files/Configuration sections is uneven. Again, feel free to coalesce these entries into the important ones that people will care about._
- _I couldn't tell about many of the items - whether they were important or not. I retained them if I couldn't decide._
- _I removed all commit numbers. I don't believe they are useful in a summary of this much work._
- _I moved all the "less important" items (in my judgement) to the bottom, and would propose that they be deleted entirely from the CHANGELOG file. I don't believe they add information to the presentation. Feel free to rescue items I mis-categorized._
- _Thanks!_

PS I realize that this is most easily handled as a PR. I'll submit one today/tomorrow. 
PPS @justinclift  - I'm content being a drive-by contributor. I'll decline again, but thanks!

---

### Added
- **General**
	- Update to SQLite version 3.46.0
	- Integration with [dbhub.io](https://dbhub.io)
	- macOS ARM version 

- **Appearance and GUI Enhancements**
	- Add .NET DateTime.Ticks to date display format 
	- Add a refresh button to the Database Structure tab 
	- Add an extra tab for editing check constraints to the Edit Table dialog 
	- Add an extra tab for editing foreign keys to the Edit Table dialog 
	- Add auto completion for math functions  
	- Add Ctrl+Enter as shortcut for executing query 
	- Add new menu item to import from CSV data in the system clipboard 
	- Add new menu item to show the row counts of all tables 
	- Allow users to export or import user-settings file in a GUI environment  
	- Add file, line number and function to Error Log 
	- Add GUID display format 
	- Add iif SQL function to the list of known functions in Execute SQL tab 
	- Add new option to freeze columns in the Browse Data tab 
	- Allow multiple TableBrowser tabs in the Browse Data tab 
	- Bar charts now display labels in x axis when NULL values present 
	- Scale large images in ImageViewer to fit the viewport by default 
	- Enable HiDPI on all platforms by default 
	- Change tabbed table browisng to use docks instead 
	- Change mouse cursor to the pointing hand when Ctrl+Shift are pressed 
	- Change to 'Preference' expression for consistent 
	- Data Browser: avoid showing BLOBs containing unprintable characters as text 
	- Data Browser: export query results as JSON 
	- Edit Database Cell: fixed potential for data loss and better feedback 
	- Edit Table: alternating row colors in tables for better readability 
	- Edit Table: Change the key icons from header to tooltips 
	- Fix indentation - always use 4 spaces
	- Plot Dock: use more precision for small numbers and less for big numbers 
	- Plot: fix selecting points to select corresponding line in table 
	- Plot: show x and y values on a tooltip when hovering over the plot 
	- Table Browser: "Clear Filters" button to clear the global filter 
	- Table Browser: give hint of table sorted or filtered state in the toolbar 
	- Table Browser: Support extended selections 
	- Add copy column name to table viewer 
	- Allow multiple -t/--table parameters on the command line 
	- Open recent files in read-only mode using a different shortcut
	- Allow selecting fixed format for big integer numbers 
	- Allow the user to change MaxRecentFiles  
	- Always load settings for Browse Data tabs 
	- Always raise new Data Browser tabs to the foreground 

- **SQL Processing**
	- parser: Add support for IS (NOT) DISTINCT FROM expressions 
	- Execute SQL: add Ctrl+Shift+T for "Open SQL file(s)" 
	- Fall back to asking SQLite when parsing a table schema has failed 
	- Update schema after attaching/detaching a database in an Execute SQL tab 
	- Also update schema when clicking the Refresh button in Browse Data tab 
	- Improvements for working in the SQL Execution area using keyboard 
	- When modifying a view use DROP VIEW IF EXISTS instead of just DROP VIEW 
	- Add basic support for new RETURNING keyword 
	- Change WHERE clauses of queries to use column names instead of indexes 
	- DB Schema: drag & drop SELECT queries 
	- Export query results as JSON 
	- Export SQL: fix quoting of BLOB values and non-printable strings 
	- Export SQL: option to keep original CREATE statements 
	- Improve support for BLOB columns as primary key 
	- Use LIMIT + OFFSET when generating SELECT statements instead 


- **Files**
	- Import: Add import-csv option to command line to import CSV files 
	- Move recent files items to new submenu and add clear recent file function  
	- CLI: Reuse `--table` as table name for a CSV Import 
	- CSV Export: binary BLOB to base64 
	- CSV Import: fix importing into existing table 
	- CSV Import: give option to use system locale conventions 
	- Import: allow CSV separator and quote to be passed from command line 
	- Import: announce support for CSV files in Desktop file 
	- Import: do not remove characters from CSV header fields 
	- Import: don't assume an empty file is a text file 
	- Import: support importing the single file argument as a CSV file 

- **Configuration**
	- New setting for configuring brace matching background 
	- New setting for having close button on tabs (default) or not 
	- New settings for changing the selection appearance in editors 
	- Add the ability to support custom config files  

### Changed

There have been too many changes since the last full release to list separately.
Important changes are listed in the **Added** section above.
 
### Fixed

There have been too many bug fixes since the last full release to list separately.
Please check out 3.13.0 and let us know if your issue still exists

### Removed

- _none_

### Translation
- Add Dutch, Indonesian, Swedish translation 
- Update Arabic, Brazilian Portuguese, Chinese, French, German, Italian, Japanese, Korean, Polish, Spanish translation 

---

**_Proposal: Delete these from "Added" list above_**

- Enable HiDPI on Windows  
- Add "Save Database As..." action 
- Add status message when opening a file from the recent file list 
- Rename 'Open tab' to 'New tab' in the Execute SQL area 
- Add new action to close project file and return to initial state 
- dbhub: Add some line breaks to the input dialog text for cloning 
- dbhub: Add text to upload button 
- dbhub: Add "Upload Database" action to context menu of local file list 
- dbhub: Add button for cloning databases from a link 
- dbhub: Add context menu action for saving a revision to another file 
- dbhub: Add context menu action to delete local databases 
- dbhub: Add context menu actions to all tree views 
- dbhub: Add link to webUI page of currently opened database 
- dbhub: Add refresh button to both tool bars 
- dbhub: Add some line breaks to the input dialog text for cloning 
- dbhub: Add text to upload button 
- dbhub: Add toolbar action for fetching the latest commit 
- dbhub: Add view of all checked out databases 
- dbhub: Allow pushing to other user accounts to which you have access 
- dbhub: Log in by only selecting an identity, no need to press a button 
- Add more options for setting font sizes 
- Add zooming to image viewer in the Edit Dialog 
- Add 'Don't ask again' button to collation message box 
- ImageViewer: Add mouse wheel zoom 


**_Proposal: Delete these from "Fixed" list above_**

- [Fix  Can't parse db name in .env file 
- Fix 'Set Encryption': don't reuse current file after closing 
- Fix #2583: quote identifiers, not expressions 
- Fix a harmless warning when searching for an empty font name 
- Fix altering tables with generated as columns 
- Fix browsing tables without rowid and multiple primary key columns 
- Fix bug which made tables from other schemas inaccessible in Browse Data 
- Fix changes to constraints in Edit Table dialog not always being applied 
- Fix colour assigned to plot being always black 
- Fix crash when a format is applied and one or more columns are selected 
- Fix crash when removing the only index constraint from a table 
- Fix crash when trying to open non-existing table via command line 
- Fix editing of tables without rowid 
- Fix empty filters in project files 
- Fix error messages in Execute SQL tab 
- Fix executing selected SQL text when there are multi-byte characters 
- Fix filter row losing focus when changing filter values 
- Fix filters for tables with display formats 
- Fix formatting and syntax of the help message in Spanish 
- Fix issues with executing SQL statements 
- Fix possible crash when browsing a table with multiple PK columns 
- Fix possible crash when loading project files 
- Fix possible crash when opening a project without SQL tabs 
- Fix possible crash when removing constraints from table definition 
- Fix possible crash when trying to modify a table 
- Fix possible crashes when loading outdated project file 
- Fix possible memory leak when trying to open an encrypted database 
- Fix problems when showing help message in rich text format 
- Fix remaining issue with optimised SELECT statements 
- Fix repositioning of filter widgets after the second click on the header 
- Fix running ALTER TABLE statements in Execute SQL tab 
- Fix saving the list of extensions in the Preferences dialog 
- Fix SQL import of files with BOM 
- Fix title, which must be non-empty 
- Fix to 'Window Layout' options work properly 
- Fix type on TableBrowser.ui 
- Fix warning in SQL error log when creating an in-memory database 
- Fixed incorrect display of SQL calltips containing non-US-ASCII characters 
- Fixes for hiding the title bar of the single Table Browser 
- parser: Fix string literals used as column ids in indexed columns 
- parser: Fix unquoting when using square brackets 
- dbhub: Fix creating new branches 
- dbhub: Fix port number mismatch when using port 443 
- dbhub: Fix reply handler for push actions 
- dbhub: Fix saving latest commit to file 
- dbhub: Fix sporadic crashes when selecting an identity 
- dbhub: Fix updating branch list when database name is changed 


**_Proposal: Delete these from "Changed" list above_**

- Comment out additional gotReply signal connection 
- Complete menu accelerators in File and Tools entries 
- Correct to tab instead of space 
- Cut to clipboard operation in data browsers 
- Data Browser: use font style to indicate keys 
- Destroy the Temporary Fiel object so it is not kept open 
- detach additional database connection 
- Do not add SQL keywords multiple times to auto completion 
- Do not always refresh the table browser dock when opening a database 
- Do not show the titlebar for the Table Browser dock when there is only one 
- Enable buttons for editing/deleting tables and similar on first click 
- Evaluation mode in the Edit Database Cell editor 
- Execute SQL editor: Use tabs for indentation 
- Export: fix no error check for export errors 
- Export: more error checks 
- Export: use QSaveFile to get better error check on full partition 
- Font change in Browse Data table not applied to RTL Text editor 
- For sorted column remember column name instead of column index 
- Give alternate shorcuts to the ones using F keys 
- GUI improvements in Edit Table Dialog 
- Hide filters when table is empty 
- Icon in data browser for primary key fields 
- Import: "Yes to All" to skip all further prompts 
- No longer force Light theme on macOS when "Follow the desktop style" is chosen 
- Only show numbered sort indicators when more than one column is sorted 
- Open in external application: apply saved data directly to the cell 
- Open SQL files are now linked when saving project file 
- Open SQL tabs for modifying views and triggers 
- Optimise executing large SQL files in the Execute SQL tab 
- parser: Refactor parsing and handling of constraints 
- Permit dollar signs ($) after the first char in unquoted IDs 
- Project files: fix crash when tables does not match DB file 
- Project files: prevent SQL tabs loss while closing the application 
- Refactor the constraints tab in the Edit Table dialog 
- Refresh table views when using --table command line option 
- Remove filter widgets when the table is empty 
- Remove the Default property of the fetching dialog 
- Resize rows to contents only for visible rows 
- Respect the sqlite_sequence table when generating PK value for new rows 
- Restore original default for having condition format in filter line 
- Return the configured font for data browser in the model 
- Save as view: allow any state in the table 
- Save custom tab title flag in project files 
- Save some screen space and reduce number of unnecessary borders 
- Select column in table results when column header is pressed 
- Settings: fix file check in "-S" option for Windows 
- Show a useful icon in SQL tabs  
- Show preformatted text for output from command line arguments in Windows 
- Show tables in foreign key editor in alphabetical order 
- Speed up execution of many SQL statements by delaying the log output 
- SQL Execution Editor: appropriate helping message in reload dialog 
- sqlite3 API: Prevent that busy DB are left open 
- src: rename sqlb::Query::setColumNames 
- Store a relative filename if the path to project and to DB is the same 
- Store table constraints in a vector instead of a set 
- Swap sort order indicators 
- Tweak the output wording for command line options 
- Unify message in About dialog and version argument 
- Update appdata to pass validation 
- update plotwindow's selection in tablebrowser 
- Update remote database information when an upload is completed 
- Use a separate enum for table constraint types in the Edit Table dialog 
- Use Ctrl+PgUp to set focus to editor inside the SQL Execution Area. 
- Use native path separators in Preferences dialog 
- Use table name as tab text in Browse Data tabs 
- User can disable 'Save Project' dialog  
- Warn user to apply or discard unsaved changes in cell editor 
- appimage: Update to SQLite 3.41.1 
- AboutDialog: Change layout to fit large font better 
- Adjust the bottom buttons layout 
- Associate copy table column menu entry to action. 
- Avoid attaching the plot when the signal is notifying the row count since the data wouldn't be available yet. 
- Avoid error messages when checking for updates 
- Avoid multiple error messages when deleting cell values 
- Avoid possible database busy message when using the Browse Table action 
- Avoid running SELECT statements twice in Execute SQL tab 
- Avoid type conversion warnings in Plot Dock 
- Better error messages when CSV import fails due to an unexpected EOF 
- Binary detection: end-of-line characters where not treated as text 
- CipherDialog: Improve password fields validation 
- CipherSettings: fix crash with empty RawKey 
- Clear currently opened database file name when closing database 
- CSV Import: use file before it is removed by destructor 
- CSV Import: fixes of the local convention option 
- dbhub: Allow checking out different commits and different branches 
- dbhub: Automatically switch to the correct identity when opening file 
- dbhub: Better explanations for the Clone button 
- dbhub: Clear branches combo box when closing database 
- dbhub: Do no show error message when download was cancelled 
- dbhub: Do not allow pushing in-memory databases 
- dbhub: Highlight current commit in commit list 
- dbhub: Improve default settings table views in Remote dock a bit 
- dbhub: Improve support for different branches 
- dbhub: In Push dialog preselect the current branch 
- dbhub: Make HTML text of commit message field non-translateable 
- dbhub: Only show warning about losing unsaved changes when downloading 
- dbhub: Redownload database when checking out current commit 
- dbhub: Refresh commit list after pushing a new commit 
- dbhub: Show a warning when trying to push unsaved changes 
- dbhub: Show list of commits in Remote dock 
- dbhub: Show more information in tree views 
- dbhub: Show some information on the currently opened database file 
- dbhub: Some UI improvements 
- dbhub: Use current locale for formatting all timestamps 
- dbhub: When deleting last local database of a user, remove user too

**Comment by justinclift** [comment]
>  I'm content being a drive-by contributor. I'll decline again, but thanks!

No worries. :wink:
