### ISSUE TITLE
[Feature]: We should probably have our macOS nightly builds be named a bit differently from the stable release

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#3339]
### Describe the new feature

As our nightly builds currently use exactly the same icon and .app name as our stable releases, this makes it difficult for people who want to have both installed at the same time.

eg: https://github.com/Homebrew/homebrew-cask-versions/pull/9684

> Some upstream developers name their nightlies and betas clearly, others do not. We’re not privy to every upstream’s reasoning so we replicate whatever their decision is, we don’t want to impose our naming conventions on users.

Asking @lucydodo about it, it does seem to be something we'll want to change around.

> Right, I think it would be a good idea to have some sort of label and icon for nightly build so that uses can easily distinguish between.
> THis would also allow us to design stable and nightly versions to coexist on Homebrew Casks without conflicts. :thinking:

So, lets add this to the list of things to do. :smile:

**Comment by justinclift** [comment]
Anyone feel like making some variant of our icon, such that people can immediately tell which is our "standard release" icon vs our "nightly build release" icon?

**Comment by chrisjlocke** [comment]
I'm familiar with Windows icons (32x32 and 16x16) but for Mac isn't there about 900 different sizes in .svg format?

**Comment by lucydodo** [comment]
Well, I think it comes down to how we express it. 😄 
For example, VSCode uses a green-tinted variation of the existing icon to distinguish it. or we could label it with a label like 'Nightly'. Neither of tese seem very intuitive to me, so I think it would be nice to add some sort of symbol. Any ideas?

> https://code.visualstudio.com/brand (See the 'The wrong icons' section)

**Comment by justinclift** [comment]
Muaaa Haaaa Haaaa

I'm thinking "Radioactive" icon for the nightly build, possibly superimposed on our standard logo → ☢️

Might be a bit too daring though?

**Comment by justinclift** [comment]
@chrisjlocke From rough memory, we have a script or something hanging around **somewhere** that does icon conversion for macOS.  No idea where the heck it might be though. :smile:

**Comment by scottfurry** [comment]
> I'm familiar with Windows icons (32x32 and 16x16) but for Mac isn't there about 900 different sizes in .svg format?

Seven - see [here](https://eshop.macsales.com/blog/28492-create-your-own-custom-icons-in-10-7-5-or-later). It's not hard and can be incorporated into the CMake as a function to generate the icons from a base image.

**Comment by justinclift** [comment]
Oh, there's a whole bunch of "bug" related emoji's too:

https://emojipedia.org/search/?q=bug

Some of those might be a more obvious choice instead of the radioactive icon. :smile:

**Comment by lucydodo** [comment]
Just a matter of personally opinion, I think bug emoji are gross.. 😞 
Since it's a "night" version, how about a moon-like emoji?
But now that I think about it, go back on my words.. it would be fine to just make the icon a black color?
More projects than I might think have color variations for their dev version's icon. There's probably a reason for that. 🤔

**Comment by lucydodo** [comment]
For example, I tried inverting the existing logo once in the Affinity. 😄 
![Screenshot 2023-05-08 at 11 04 40](https://user-images.githubusercontent.com/64626662/236718143-43b48553-0180-44eb-be6c-e1c8aeaab82b.png)

**Comment by justinclift** [comment]
Hmmm, I'm not sure.  While that darker icon looks ok to me, I'm thinking it'll probably be confusing as to which is which.

For example, when we see both of those icons together it's easy to tell which is the "nightly" version.  Because one is clearly darker -> nightly.

However if a person sees just one icon by itself, without anything to compare to, the easy ability to know "this is the dark one" isn't there.

---

Doing a search for "moon" on Open Clipart turns up a bunch of results:

https://openclipart.org/search/?query=moon

One of those is likely suitable for our purposes.

**Comment by justinclift** [comment]
On a different note, these OSS illustrations look interesting:

https://undraw.co/illustrations

Not useful for our nightly-icon, but could be useful for other stuff.  eg writing documentation, blog posts, etc.

**Comment by lucydodo** [comment]
Emojis have lots of moons too: https://emojipedia.org/search/?q=moon 😄

**Comment by justinclift** [comment]
Cool, yep I somehow missed that. :smile:

**Comment by lucydodo** [comment]
How about place an emoji in the bottom right corner of logo? Just like this:
![logo](https://user-images.githubusercontent.com/64626662/236730197-c2917182-ea7f-49b8-b10b-9fdfb96f5cea.png)

**Comment by justinclift** [comment]
Yeah, bottom right is what I was thinking too.  That particular image doesn't seem to work well, but I'm not super bothered by it.

It's "good enough" for our purposes if you're happy with it. :smile:

**Comment by lucydodo** [comment]
The sample image uses the Google Noto Color Emoji. According to Google, there do not appear to be any licensing issue.
> You can use them in your products & projects – print or digital, commercial or otherwise.
> https://fonts.google.com/noto/specimen/Noto+Color+Emoji/about

**Comment by scottfurry** [comment]
There is also the apple logo from the wikimedia commons.
A quick mock up...
![experimental_logo](https://user-images.githubusercontent.com/6686571/236730484-d3d8f770-2f9f-484d-b7fb-6a3ab3d3c8f2.jpg)

**Comment by justinclift** [comment]
@lucydodo Yeah, that license (SIL Open Font License) seems fine. :smile:

@scottfurry Interesting idea, but "apple logo" doesn't really convey anything to do with "nightly" builds. :wink:

**Comment by scottfurry** [comment]
"shading" - superimpose the texture from the night/day emoji? Again, a mock-up/experiment, since we're throwing ideas around. Not the final product.

**Comment by justinclift** [comment]
Yeah, that could work. :smile:

**Comment by lucydodo** [comment]
Night,, It's like a satellite just popped into my head. https://emojipedia.org/satellite/

**Comment by justinclift** [comment]
Maybe try it out and see how it goes? :smile:

**Comment by lucydodo** [comment]
Hmmmm It looks like the satellite is less visible than I thought. :(
![logo](https://user-images.githubusercontent.com/64626662/236731458-98e77aff-94c6-47d2-ba1d-1c96b1226231.png)

**Comment by lucydodo** [comment]
Once upon a time, a building called DB4S was under construction.. 😉 
![logo](https://user-images.githubusercontent.com/64626662/236731823-b972df98-b3dc-4108-aa81-a62e6ed387d0.png)

**Comment by justinclift** [comment]
Heh, I reckon that works well.

That one has my vote. :smile:

**Comment by scottfurry** [comment]
Variations on a theme....
![experimental_logo2](https://user-images.githubusercontent.com/6686571/236733152-c852ab78-0887-4915-93de-23c795585d4d.jpg)

**Comment by justinclift** [comment]
Heh, nah.  I personally like the construction icon thing better. :smile:

**Comment by lucydodo** [comment]
![sqlitebrowser-nightly](https://user-images.githubusercontent.com/64626662/236733481-6ba54652-deac-499f-962a-230073b0ab0a.png)
Since OpenMoji also supports emoji in SVG format, I drafted this using OpenMoji. Is this okay?
The license also seems to me to be legal for our use: https://openmoji.org/faq/

**Comment by justinclift** [comment]
Doesn't seem to be loading for me at all.  It's just a big empty space.

**Comment by lucydodo** [comment]
Oh, I used the online editor, but there seems to be a problem with the editor. Hold on a second.

**Comment by scottfurry** [comment]
> Oh, I used the online editor, but there seems to be a problem with the editor. Hold on a second.

Inkscape is your friend...

**Comment by lucydodo** [comment]
![sqlitebrowser-nightly](https://user-images.githubusercontent.com/64626662/236737316-f4c6cf78-47df-4907-9715-5c1bb53286a3.png)

**Comment by lucydodo** [comment]
@scottfurry I hadn't thought of Inkscape, Thanks 😄

**Comment by scottfurry** [comment]
Since this is the macOS nightly, throw in the apple logo?
- bottom layer would be are usual logo
- next layer Apple logo
- top layer construction barricade

Thoughts?

**Comment by lucydodo** [comment]
Interesting suggestion, but I think this icon would be helpful for user on all OS :)
Also, the Apple logo is a registered trademark of Apple, so I think we might run into legal problems 😢

**Comment by justinclift** [comment]
> Since this is the macOS nightly, throw in the apple logo?

Nah.  Doesn't seem necessary.

If we want to extend the concept to other nightly builds too, it'll get in the way. :smile:

**Comment by justinclift** [comment]
@lucydodo Cool, yep I reckon that updated construction one is good.  Lets go with that. :smile:

**Comment by lucydodo** [comment]
I created a branch called 'dev-3339', and added new icons, and modified the build script.
However, I'm not sure at what point in the script I should change the name of the final app. Can I get some advice? 😄

**Comment by justinclift** [comment]
Probably the right spot to rename it, is inside the .dmg creation section.  Something like line 248 here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/ca257ffcfaaa704cf24cdffc9e2265a992417c67/installer/macos/build_sqlitebrowser_nightly-arm64.sh#L248

That's just a guess though, I haven't actually tried it. :smile:

**Comment by scottfurry** [comment]
In theory, IIRC, icon bundle should be available when the application bundle is assembled during macOS build.

**Comment by lucydodo** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/commit/84238233febe13bf1c43d05dfcc31ec8fc31fcf4
Thanks for advice, I modified the script just now. Do you think ready to merge to the `master` branch? 🤔

**Comment by lucydodo** [comment]
@scottfurry I agree, it's probably possible by changing the CMake configuration, but I'm not sure for now.

**Comment by justinclift** [comment]
> Do you think ready to merge to the master branch?

Looks fine to me.  We might want to figure out the icon piece first though, so it can be merged at the same time. :smile:

**Comment by lucydodo** [comment]
> figure out the icon piece first though, so it can be merged at the same time. 
Sorry, I don't understand this part. Could you please explain more? 😢

**Comment by justinclift** [comment]
Sure.  It looks like 84238233febe13bf1c43d05dfcc31ec8fc31fcf4 is just for the .app renaming.

My thought there, was that we should probably merge it at the same time as the new "construction mode" nightly build icon piece.

**Comment by lucydodo** [comment]
Sorry, I don't know if understood that correctly.
If you mean apply the new icon to the app, the script was modified the previous commit. 😄 
https://github.com/sqlitebrowser/sqlitebrowser/blob/37e2d39e39c137a486ee980516f45340f76b0011/installer/macos/build_sqlitebrowser_nightly-arm64.sh#L237-L239

**Comment by lucydodo** [comment]
and I think it would be better if the script could take an additional envionment variable like `NIGHTLY=1` and only use the new icon/app name when the value of the `NIGHTLY` variable is `1` or `TRUE`. This should be a very simple enhancement.

**Comment by justinclift** [comment]
Ahhhhhh.  Yeah, my mistake.  I just clicked on the one commit and saw only the rename. :wink:

Looking at the actual branch now, it seems fine.

But, I like your idea for the `NIGHTLY` variable as well.  Might as well add that too.

When you're happy with it all, squash it all into one commit and push it to `master`. :smile:

**Comment by lucydodo** [comment]
The branch is ready to merge, and I've added the license notation associated with the emoji that we use.
I added it based on the existing license notation, but can you check this just in case? I'm cautious about licensing.
https://github.com/sqlitebrowser/sqlitebrowser/commit/c77fae176bb1d0b699fd628cd37a0fe3bd49a06d

**Comment by lucydodo** [comment]
Additionally, the NIGHTLY=1 command is required when running the script on the build server. 😄 
Example: `NIGHTLY=1 ./build_sqlitebrowser_nightly-arm64.sh`

**Comment by justinclift** [comment]
Cool, that all looks good to me.  They're better off as a single commit though.

So, I'd next turn them into a single commit then push it to master.

After you've done that, I'll update the macOS build servers to use them (eg adjust cron jobs, etc). :smile:

**Comment by scottfurry** [comment]
@lucydodo - Basic method to generate icon from a PNG file that I've used in personal code. Code works on, and makes use of, macOS specific tools to programmatically generate the mac icon for the application bundle.

```cmake
...
    ## NOTE - cmd - touch [path to icns given in APP_ICON above] and this action works
    ## NOTE: reference: https://stackoverflow.com/a/20703594
    SET( SRC_PNG_PATH "${ICNSPATH}/logo_PX1024.png" )
    SET( DEST_ICS "${ICNSPATH}/${PROJECT_NAME}.iconset" )
    ADD_CUSTOM_COMMAND( TARGET ${PROJECT_NAME} PRE_BUILD
                        COMMAND mkdir "${DEST_ICS}"
                        COMMAND sips -z   16   16 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_16x16.png"
                        COMMAND sips -z   32   32 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_16x16@2x.png"
                        COMMAND sips -z   32   32 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_32x32.png"
                        COMMAND sips -z   64   64 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_32x32@2x.png"
                        COMMAND sips -z  128  128 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_128x128.png"
                        COMMAND sips -z  256  256 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_128x128@2x.png"
                        COMMAND sips -z  256  256 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_256x256.png"
                        COMMAND sips -z  512  512 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_256x256@2x.png"
                        COMMAND sips -z  512  512 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_512x512.png"
                        COMMAND sips -z 1024 1024 "${SRC_PNG_PATH}" --out "${DEST_ICS}/icon_512x512@2x.png"
                        COMMAND iconutil -c icns "${DEST_ICS}"
                        COMMAND rm -R "${DEST_ICS}"
    )
...
```
This could probably be a stand-along function within CMake script.

**Comment by justinclift** [comment]
@scottfurry Cool, that looks really useful. :smile:

**Comment by scottfurry** [comment]
It is... helps. Idea is to start with a 1024px^2 png image and let the mac toolset do the heavy lifting. Everything gets shoved into a folder, `DEST_ICNS` variable, that gets turned into the final icon for the bundle. When the mac `iconutil` finishes, the folder goes away leaving the icon file.

**Comment by lucydodo** [comment]
Merged. We have about 18 hours until the next build. I'll check to see if the build script is working as we intended, and if so, I'll modify the Homebrew Cask and send a PR to the Homebrew Team. For now, I'm going to bed. Really 'nightly' time for me. 😄

**Comment by scottfurry** [comment]
*...only 18 hours...* - no pressure.

**Comment by lucydodo** [comment]
@scottfurry Thank you so much, It helps me a lot. but I think I need to get some sleep now. :( If we need to, we can delay applying this build script for a day or so, fix the changes by @scottfurry's idea, and then apply the build script to the server.
What do you think? Any method is fine with me. 😄

**Comment by justinclift** [comment]
Awesome, good stuff @lucydodo. :smile:

I've just started the updated arm64 version of the script, with `NIGHTLY=1`.

Go get some sleep, it's all good.  If it breaks, it's likely something simple that we can do meanwhile. :smile:

**Comment by justinclift** [comment]
k, that worked.  There are new arm64 nightly builds on the nightlies server now.  I'll update the intel script with the same adjustments, and then run that one manually too.

@scottfurry Is your mac an Intel or Apple Silicon one?

**Comment by scottfurry** [comment]
@justinclift - intel mac. Was able to get a *steal* on an older Mac Mini, see [MacSales(OWC)](https://eshop.macsales.com/) for used Macs. Running Monterey. I can limp through on that until resources are available and forced to upgrade.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by justinclift** [comment]
k, updated nightly Intel builds just finished too.

@scottfurry Would you be ok to take a look at them from your point of view?

**Comment by justinclift** [comment]
Ugh.  I've just tested the standard SQLite intel build, and it's broken in some way.  Damn. :frowning:

**Comment by justinclift** [comment]
Hmmm, what the heck.  It's exhibiting behaviour I've not seen before.

Double clicking on the .dmg file opens it, but the .app has the "broken icon" look:

![image](https://user-images.githubusercontent.com/406299/236788366-0fc8ffff-56f4-4c61-b292-2f1bffca4b79.png)

Double clicking on that, gives a warning about a damaged .app:

![image](https://user-images.githubusercontent.com/406299/236788636-308fd112-05b7-4f3e-9ef1-f4ac7cf5689a.png)

However, running it directly from the command line works fine:

![image](https://user-images.githubusercontent.com/406299/236789516-c92f149e-f62d-49b6-be6d-2b2557f2d57a.png)

I have no idea why one part of macOS thinks its broken, when it's clearly not. :frowning:

**Comment by justinclift** [comment]
I can't test the Apple Silicon mac version without some extraordinary messing around, so I'm going to hope someone else (@lucydodo maybe?) has one handy and can test it instead. :smile:

**Comment by justinclift** [comment]
Same behaviour with the SQLCipher one too.

**Comment by justinclift** [comment]
Ahhh.  It might be unhappy with the new "nightly" icon file.  It might need to use the conversion process from @scottfurry above first.

Saying that because when I try the nightly build from yesterday, it looks fine and opens fine.  So, the updated icon is about the only significant change.

At this point, I'll commit the updated build scripts to our repo, and @lucydodo can look into the icon thing when he's around. :smile:

**Comment by justinclift** [comment]
k, I've pushed the updated build scripts to master.  That's enough from me on this for tonight. :smile:

**Comment by justinclift** [comment]
> I'd be happy to test it

@lucydodo Oh, is your mac an Apple Silicon one?

If so, would you be ok to try out the new arm64 macOS build on the nightlies server?  I've just created them with the old icon, and want to know if they're ok vs busted. :smile:

**Comment by justinclift** [comment]
Got it working.  Updating the name of the .app to produce in the CMakeLists.txt seems to be the right approach.  I just need to update the script to use the new nightly icon as well, and we should be good.

**Comment by scottfurry** [comment]
@justinclift - sorry, my homebrew/qt5 setup is a bit messy. I'm still trying to sort out the linking, et al. Not happy I have Qt5/Qt6 all over the place.

And as I just found out, Homebrew has no mechanism to distinguish between Qt Versions. Qt latest is whatever is available. Limiting builds to a single chain (i.e. Qt5 or Qt6) is not possible.

MacPorts is looking very tempting...

**Comment by lucydodo** [comment]
@scottfurry You can install Qt5 via `brew install qt@5` command. :smile:

**Comment by lucydodo** [comment]
@justinclift I'm back. What do I need to do? 😄

**Comment by justinclift** [comment]
@lucydodo At this exact moment, nothing. :wink:

I've just finished getting the DB4S Intel builds (for macOS) working properly, then took a bit of extra time to change the name of the SQLCipher .app build to "DB Browser for SQLCipher" in things.  That's been on the ToDo list for (literally) years. :wink:

I'll copy the changes from the Intel build script to the arm64 one, and once that's finally building ok it'd be great if you could test things (eg arm64 builds) to verify they're working from your point of view.  It's probably going to take me 1/2 hour to an hour from now though.

**Comment by lucydodo** [comment]
Nice, I have an M2 machine, so I can test the arm64 build, and I'll wait until it's ready 😄

**Comment by justinclift** [comment]
k, new builds are in the nightlies `latest` directory.  Please try them out and check if they're ok:

https://nightlies.sqlitebrowser.org/latest/

:smile:

**Comment by lucydodo** [comment]
![Screenshot 2023-05-09 at 10 19 45](https://user-images.githubusercontent.com/64626662/236969992-e361794b-5e4d-44b9-b14f-4c588aaa0815.png)
Well, it still looks like it's broken. 😢 
>0789d3f2633bb3a20f8c686952a00208ef19201fcf8acfbdd8adb1c0fa7807ca  DB.Browser.for.SQLCipher-arm64.dmg

**Comment by justinclift** [comment]
Gah.  Ok, going to double check the bits.

**Comment by lucydodo** [comment]
Yes, it works with `.appContents/MacOS/DB\ Browser\ for\ SQLCipher\ Nightly`

**Comment by lucydodo** [comment]
btw, are you getting GitHub notifications normally? mine suddenly stopped notifying. 😢

**Comment by justinclift** [comment]
Hmmm, I'm not sure about the notifications.  I'm just obsessively checking the bottom of this issue every few minutes after I change stuff and launch a new build. :smile:

**Comment by justinclift** [comment]
Btw, found what *probably* caused the breakage.  Fixing it now.

**Comment by lucydodo** [comment]
Good. I'll be waiting :)

**Comment by justinclift** [comment]
k, new builds online.  Changed the standard SQLite one a bit too, so that'll need re-testing as well. :wink:

**Comment by lucydodo** [comment]
![Screenshot 2023-05-09 at 11 03 18](https://user-images.githubusercontent.com/64626662/236975401-6d407d25-c724-48d5-8b8a-f0cafa03dac5.png)
I downloaded the new build, and it's up and running 😄

**Comment by justinclift** [comment]
AWESOME!  k, I'll commit the changes to `master` and call it a day (finally). :smile:

**Comment by justinclift** [comment]
k, updated scripts are in `master` now.

Good work @lucydodo and @scottfurry. :smile:

**Comment by lucydodo** [comment]
Awesome, I've just modified Homebrew Cask file and notified the Homebrew Team. 😄

**Comment by lucydodo** [comment]
Also, the app name is split between 'SQLite' and 'SQLCipher', so we probably need to submit another Casks to Homebrew.
Like following:
- Stable (homebrew/homebrew-cask)
	- db-browser-for-sqlite
	- db-browser-for-sqlcipher
- Nightly (homebrew/homebrew-cask-versions)
	- db-browser-for-sqlite-nightly
	- db-browser-for-sqlcipher-nightly

**Comment by lucydodo** [comment]
![Screenshot 2023-05-09 at 11 40 31](https://user-images.githubusercontent.com/64626662/236980288-d8ddc477-8803-41bc-a479-e4f03847b8f1.png)
As you can see, both versions can be installed via Homebrew. 😄

**Comment by justinclift** [comment]
@chrisjlocke This issue is likely something we'd want to have in a blog post. :smile:

The quick summary (all for macOS):

* Our nightly builds now have a slightly different name: `DB Browser for SQLite Nightly`, and the icon/logo for the nightly builds has one of those "under construction" image things on top of it.  As per: https://github.com/sqlitebrowser/sqlitebrowser/issues/3339#issuecomment-1537715587
* The SQLCipher ones have their own name now: `DB Browser for SQLite Nightly`, with the same "under construction" icon

The naming change means the stable release and a nightly build can safely be installed on the same system.  Previously, only one could be installed at any one time.

The icon change should mean it's easier for people to know if the app is a stable release or a nightly build.  In theory. :smile:

**Comment by scottfurry** [comment]
> @scottfurry You can install Qt5 via `brew install qt@5` command. smile

@lucydodo - well aware. However, there's more to the problem. As I've commented elsewhere, Homebrew doesn't distinguish between qt@6 and qt@5 in formulae. Software is built against the latest `qt` package - in this case 6.4.3. Homebrew does not disambiguate qt version unless the formula explicitly calls out a revision. It just makes revisioning of software a touch more complicated. There is no way to limit what gets installed. And at the next update, things could change again...

The *just use homebrew* answer is a gun loaded with assumptions in my books.

**Comment by chrisjlocke** [comment]
> This issue is likely something we'd want to have in a blog post

Will bash one out tonight (er, blog post, that is)
