### ISSUE TITLE
 problem in execute SQL tab when query includes Unicode 

### ISSUE THREAD

**Issue by vaidasB** [sqlitebrowser/sqlitebrowser#334]
There is problem in execute SQL tab when query includes Unicode characters for example Japanese or Chinese kanji. All characters turns to question marks.

**Comment by schdub** [comment]
@vaidasB, thanks for reporting but this issue is already fixed.

You should use our nightly build (http://rp.oldsch00l.com/sqlitebrowser/) or wait until version 3.7.0 is finally will be aired.

See: #282.

**Comment by justinclift** [comment]
Closing this as it's definitely the Unicode issue we've fixed in our nightly builds. :smile:
