### ISSUE TITLE
DNS moved on nightlies.sqlitebrowser.org

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#3340]
@lucydodo; Note we've just moved the DNS from the old server to the new Hetzner server (65.21.70.43).  Beware when viewing Nginx logs, etc.  You'll need to backup the old ones and move them to the new server 'somewhere safe' as needed.

We've copied your ssh key across, but if you have any problems accessing the new box, yell and we can assist. :)

**Comment by lucydodo** [comment]
Well, it looks like I can't connect new server. It's possible that I'm doing something wrong.
But just in case, it would be better to contact us via email or something insead off here:)
If that's okay for you, here's my email: seongtaejg at gmail.com :D

**Comment by chrisjlocke** [comment]
Contact me on chris at chrisjlocke dot co dot uk if you need assistance 'jumping via the other server'.  Apologies I didn't mention that in the above post.

**Comment by lucydodo** [comment]
No worries at all, I just sent you an email. 😄 
and also, going to close the issue as I think we can communicate via email from now.
