### ISSUE TITLE
[Bug]: Nightly builds for Mac are not notarized

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#3342]
### What did you do?

In `https://nightlies.sqlitebrowser.org/latest/`, download and run the following four files:
- [DB.Browser.for.SQLCipher-arm64.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLCipher-arm64.dmg)
- [DB.Browser.for.SQLCipher-intel.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLCipher-intel.dmg)
- [DB.Browser.for.SQLite-arm64.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-arm64.dmg)
- [DB.Browser.for.SQLite-intel.dmg](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-intel.dmg)

### What did you expect to see?

Runs normally (Warned by Apple GateKepper, but can be run)

### What did you see instead?

- ARM64 app occur the following warning and fail to run:
`APP` can’t be opened because Apple cannot check it for malicious software.
- Intel app occur the following error and fail to run (Also, icon is unavailable):
You can’t open the application `APP` because it may be damaged or incomplete.

Maybe because my Mac is ARM-based,
it thinks that Intel app that aren't notarized are corrupted because 'Rosetta' can't even intervene. 🤔 

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

MacOS

### OS version

macOS Ventura 13.3.1 (a) (22E772610a)

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
For reference, these are sha256 hash values that I downloaded file.
>3ab6230c922cd9e0edd625eb5f14ef8473f1fac08a8bdcb6ba48f7754ebfe0d3  DB.Browser.for.SQLCipher-arm64.dmg
>ca8ad5f5f5236ad315536049233bdc92c600928bd920304ff1fc8cd2c30ed003  DB.Browser.for.SQLCipher-intel.dmg
>848e12a749cc900f43aa3e36abbd2f945066aaa7c82a5390acade1f45cce7634  DB.Browser.for.SQLite-arm64.dmg
>058e76a8d831765556c7d10e522e1322b38409c7a0874fa4c8211815e2c219e4  DB.Browser.for.SQLite-intel.dmg

**Comment by justinclift** [comment]
Damn.  This stuff was working just a few days ago too.

k, I'll take a look into it.

Oh, would you be ok to try the nightly builds from a few days ago, when we got this stuff working?  I'm wondering if they'll show up as ok vs broken as well...

**Comment by lucydodo** [comment]
'DB Browser for SQLite-arm64_20230509.dmg' is working fine. There seems to be a problem the build from day 10. One interesting thing is that the 'SQLCipher' version doesn't have any builds from day 10 with the problem. 🤔 
However, the 'latest' path has a SQLCipher build the day 12th.

**Comment by justinclift** [comment]
Thanks, that narrow it down.

Wonder if it's something I changed while doing the cleanup from getting it working, that instead broke things.  Will find out in a bit. :smile:

**Comment by justinclift** [comment]
Looking at the M1 build's .log file for the 13's, this log message seems relevant:

```
Error: The db4s.keychain-db is locked. Use Keychain Access or the `security unlock-keychain /Users/jc/Library/Keychains/db4s.keychain-db` command line tool to unlock the db4s.keychain-db keychain.
```

I'll add in the appropriate `unlock` command a bit above that, and see how it goes.

**Comment by justinclift** [comment]
@lucydodo Just generated new arm64 macOS nightly builds.  Would you be ok to check them and see if they're better now?

https://nightlies.sqlitebrowser.org/latest/

**Comment by lucydodo** [comment]
Cool, I have confirmed that the arm64 version fo the app is notarized.
However, the Intel Intel version still say they are damaged.

**Comment by justinclift** [comment]
Yeah, the Intel ones there haven't changed.  The arm64 builds are fairly quick... less than 15 minutes from memory.

Whereas the Intel ones take about 75 minutes (!).

That's because it's running an older macOS version, so Homebrew doesn't provide bottles for the required dependencies (cmake, etc).  Thus they all get compiled from source, on every build.

We *could* make our own bottle for them, but the time taken to compile everything only really affects us when we need to do stuff interactively.  For overnight builds, the time taken is kind of not important.  Thus not bothering to make our own bottles (etc). :shrug:

**Comment by justinclift** [comment]
There's an intel build currently running btw, but it'll probably be another hour before the results are uploaded. :smile:

**Comment by lucydodo** [comment]
Aha, I understand. Let's wait and test the Intel version as well.
Actually, I found out about it while I was working on adding `db-browser-for-sqlcipher-nightly` to the Homebrew Cask.
so once that's done, I'll be able to add a new Cask as well. 😄

**Comment by justinclift** [comment]
k, the Intel ones should be good now.  The problem with those was that I'd tried to make it use a bottle of `cmake` (to speed things up) instead of compiling it each time.

I *thought* it was working, but clearly it wasn't.  Reverting that change in the local directory (where I keep these script for cronjobs) seems to have fixed the problem.

**Comment by lucydodo** [comment]
Cool, I've confirmed that the new Intel build works fine too :) so I close this issue, Thanks for your time 😄

**Comment by justinclift** [comment]
For the arm64 builds, I'm thinking the problem may be something to do with macOS locking the system keychain when no-one is logged in.  So I added some code that *I hope* (!) might fix the problem, and generated those newer arm64 builds an hour ago.

That code change *might not* be the actual fix.  It could instead have worked due to my ssh session being logged in at the time (yeah, weird I know).

So, instead I'm going to:

1. Temporarily change the nightly build cronjob on the m1 mac mini to run about an hour from now
2. Reboot the mac mini (before the cron job fires)

The reboot is so when the cron job runs, there's no possible way the mac mini can think anyone is logged into it.  That's my best guess as seeing whether the code change was the fix, or whether it was just having someone logged in when the script ran.

So, I'll re-open this issue until we know for sure it's solved. :smile:

**Comment by lucydodo** [comment]
Cool, I did some searching and it looks like we can disable the auto-lock for keychain with the following command:
`security set-keychain-settings`
>Source: https://ss64.com/osx/security-keychain-settings.html

By the way, I've make a request to Homebrew about adding new Cask. (https://github.com/Homebrew/homebrew-cask-versions/pull/16667)
It was mentioned in the PR, but it's a variant of sorts, so it might be rejected. I'll wait for the review. :confused:

**Comment by lucydodo** [comment]
@justinclift It's weird. Intel build appear to be broken again. Maybe it's a issue with the keychain test? 😄

**Comment by justinclift** [comment]
Well that's weird.  Looking now...

**Comment by justinclift** [comment]
k, I've just freshly downloaded the two intel based latest nightlies.  When
opening the volumes, they're not showing the broken icon:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/406299/4596697a-65da-4892-ace1-e1118775dd05)

The SQLite version of the application is doing the standard "you downloaded this..." warning:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/406299/c1baef7d-d117-4497-a418-29e52c5e13e9)

It starts up fine after confirming through that dialog:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/406299/aff076ce-72a9-40a3-8ea7-1468009ff94b)

The SQLCipher one though is giving a different warning when opening:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/406299/4fb227b8-7e5f-49ca-967b-21cbca3af580)

So it looks like something is still unhappy there.  I'll take another look at that bit again...

**Comment by lucydodo** [comment]
Let me know if there's anything I can do to help. 🤔

**Comment by justinclift** [comment]
Looking at [the log file for the build](https://nightlies.sqlitebrowser.org/macos-intel/nightly-20230513.log), it's saying notarisation worked, as did stapling:

```
{
  "tool-version": "4.029.1194",
  "tool-path": "/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework",
  "success-message": "No errors getting notarization info.",
  "notarization-info": {
    "Status": "success",
    "Status Message": "Package Approved",
    "Date": "2023-05-13T16:14:14.000Z",
    "Status Code": 0,
    "Hash": "cefd9ad2be478ed15a1abb305d3f401894216a4c355551aeac97656ff92c6cc2"
  },
  "os-version": "10.15.7"
}
Notarisation succeeded!
Processing: /Users/jc/appdmg/DB Browser for SQLCipher-intel_20230513.dmg
Processing: /Users/jc/appdmg/DB Browser for SQLCipher-intel_20230513.dmg
The staple and validate action worked!
Processing: /Users/jc/appdmg/DB Browser for SQLCipher-intel_20230513.dmg
The validate action worked!
```

The `validate` action at the end there means the verification step passed as well.

This is very "WTF?!?!?!" at the moment. :frowning:

**Comment by justinclift** [comment]
Everything *looks ok* for both of them:

```
$ codesign -vvv --check-notarization -d DB.Browser.for.SQLite-intel.dmg 
Executable=/Users/jc/Downloads/DB.Browser.for.SQLite-intel.dmg
Identifier=DB Browser for SQLite-intel_20230513
Format=disk image
CodeDirectory v=20200 size=324 flags=0x10000(runtime) hashes=1+6 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=4162b4a399ccd60fa92ac6db14fbf3d7ba3b2051
CandidateCDHashFull sha256=4162b4a399ccd60fa92ac6db14fbf3d7ba3b2051e4b3d66a9f9616e1626700eb
Hash choices=sha256
CMSDigest=4162b4a399ccd60fa92ac6db14fbf3d7ba3b2051e4b3d66a9f9616e1626700eb
CMSDigestType=2
CDHash=4162b4a399ccd60fa92ac6db14fbf3d7ba3b2051
Signature size=8975
Authority=Developer ID Application: Justin Clift (C34AV33YLK)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=13 May 2023 at 3:29:03 pm
Info.plist=not bound
TeamIdentifier=C34AV33YLK
Sealed Resources=none
Internal requirements count=1 size=196
```

```
$ codesign -vvv --check-notarization -d DB.Browser.for.SQLCipher-intel.dmg 
Executable=/Users/jc/Downloads/DB.Browser.for.SQLCipher-intel.dmg
Identifier=DB Browser for SQLCipher-intel_20230513
Format=disk image
CodeDirectory v=20200 size=327 flags=0x10000(runtime) hashes=1+6 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=4efb483c0152f456aa147627b3cc245a1887c77a
CandidateCDHashFull sha256=4efb483c0152f456aa147627b3cc245a1887c77a96bcbd36c0f343323310654d
Hash choices=sha256
CMSDigest=4efb483c0152f456aa147627b3cc245a1887c77a96bcbd36c0f343323310654d
CMSDigestType=2
CDHash=4efb483c0152f456aa147627b3cc245a1887c77a
Signature size=8974
Authority=Developer ID Application: Justin Clift (C34AV33YLK)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=13 May 2023 at 4:13:29 pm
Info.plist=not bound
TeamIdentifier=C34AV33YLK
Sealed Resources=none
Internal requirements count=1 size=200
```

**Comment by lucydodo** [comment]
>"Hash": "cefd9ad2be478ed15a1abb305d3f401894216a4c355551aeac97656ff92c6cc2"
What file is this hash value from? I can't find the that hash value in the file that I downloaded.

**Comment by justinclift** [comment]
The SQLCipher .app looks fine to me:

```
$ codesign -vvv --deep --check-notarization DB\ Browser\ for\ SQLCipher\ Nightly.app
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/libcrypto.3.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/libcrypto.3.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/libsqlcipher.0.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/libsqlcipher.0.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtConcurrent.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtConcurrent.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtCore.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtCore.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtDBus.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtDBus.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtGui.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtGui.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtMacExtras.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtMacExtras.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtNetwork.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtNetwork.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtSvg.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtSvg.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtTest.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtTest.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtWidgets.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtWidgets.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtXml.framework/Versions/Current/.
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/Frameworks/QtXml.framework/Versions/Current/.
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/bearer/libqgenericbearer.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/bearer/libqgenericbearer.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqgif.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqgif.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqicns.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqicns.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqico.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqico.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqjpeg.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqjpeg.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqmacheif.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqmacheif.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqtga.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqtga.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqtiff.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqtiff.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqwbmp.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqwbmp.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqwebp.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/imageformats/libqwebp.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/platforms/libqcocoa.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/platforms/libqcocoa.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib
--prepared:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/styles/libqmacstyle.dylib
--validated:/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/PlugIns/styles/libqmacstyle.dylib
DB Browser for SQLCipher Nightly.app: valid on disk
DB Browser for SQLCipher Nightly.app: satisfies its Designated Requirement
```

```
$ codesign -vvv --deep --check-notarization -d DB\ Browser\ for\ SQLCipher\ Nightly.app
Executable=/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app/Contents/MacOS/DB Browser for SQLCipher Nightly
Identifier=net.sourceforge.sqlitebrowser
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=59529 flags=0x10000(runtime) hashes=1853+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=238b7eb9ed2cbc3b58599103c812b4e471b004ff
CandidateCDHashFull sha256=238b7eb9ed2cbc3b58599103c812b4e471b004ff455f0299d21dd169f9ddb5c1
Hash choices=sha256
CMSDigest=238b7eb9ed2cbc3b58599103c812b4e471b004ff455f0299d21dd169f9ddb5c1
CMSDigestType=2
CDHash=238b7eb9ed2cbc3b58599103c812b4e471b004ff
Signature size=8974
Authority=Developer ID Application: Justin Clift (C34AV33YLK)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=13 May 2023 at 4:13:24 pm
Info.plist entries=15
TeamIdentifier=C34AV33YLK
Runtime Version=11.1.0
Sealed Resources version=2 rules=13 files=97
Nested=PlugIns/imageformats/libqicns.dylib
Nested=Frameworks/libcrypto.3.dylib
Nested=Frameworks/QtGui.framework
Nested=PlugIns/imageformats/libqwbmp.dylib
Nested=Frameworks/libsqlcipher.0.dylib
Nested=PlugIns/imageformats/libqtiff.dylib
Nested=Frameworks/QtCore.framework
Nested=PlugIns/imageformats/libqgif.dylib
Nested=Frameworks/QtConcurrent.framework
Nested=Frameworks/QtDBus.framework
Nested=PlugIns/platforms/libqcocoa.dylib
Nested=PlugIns/iconengines/libqsvgicon.dylib
Nested=Frameworks/QtNetwork.framework
Nested=Frameworks/QtPrintSupport.framework
Nested=Frameworks/QtTest.framework
Nested=PlugIns/printsupport/libcocoaprintersupport.dylib
Nested=PlugIns/imageformats/libqmacheif.dylib
Nested=Frameworks/QtWidgets.framework
Nested=PlugIns/imageformats/libqico.dylib
Nested=PlugIns/imageformats/libqtga.dylib
Nested=Frameworks/QtMacExtras.framework
Nested=PlugIns/imageformats/libqwebp.dylib
Nested=PlugIns/styles/libqmacstyle.dylib
Nested=PlugIns/bearer/libqgenericbearer.dylib
Nested=Frameworks/QtXml.framework
Nested=PlugIns/imageformats/libqmacjp2.dylib
Nested=PlugIns/imageformats/libqjpeg.dylib
Nested=Frameworks/QtSvg.framework
Internal requirements count=1 size=192
```

**Comment by lucydodo** [comment]
Interesting point is arm64 build is fine, only Intel build are problematic. 🤔

**Comment by justinclift** [comment]
Yeah, they use fairly different signing approaches.

**Comment by justinclift** [comment]
> What file is this hash value from?

Not real sure.  It might not be a hash of a file, but instead a hash of something else.

That's the info returned from Apple, when checking notarization status here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/master/installer/macos/build_sqlitebrowser_nightly-intel.sh#LL286C21-L286C21

**Comment by lucydodo** [comment]
I ran the `spctl` command to see what seemed to be causing the problem.
```
/Volumes/Install DB4S Nightly build/DB Browser for SQLCipher Nightly.app: rejected (invalid destination for symbolic link in bundle)
origin=Developer ID Application: Justin Clift (C34AV33YLK)
```

**Comment by justinclift** [comment]
Cool, that might point us in the right direction. :smile:

**Comment by justinclift** [comment]
Ahhh.  I bet it's the fileio.dylib link.

**Comment by lucydodo** [comment]
I'm trying to find a solution, but I'm not seeing anything. I'll let you know as soon as I find a solution that might help. 😄

**Comment by justinclift** [comment]
The fileio extension compiling step seems to break occasionally, as it grabs the very latest version of the extension source code each time the script runs.

And sometimes the fileio extension uses SQLite library calls that are only in the upcoming, unreleased version of SQLite.

Using a stable version of the fileio source code, rather than the latest source code, is probably the wrong direction to take.  That would mean having to manually update the version used every now and again.

Instead, what we could try is not creating that fileio.dylib soft link, when the fileio compile failed.

I'll give that a go now, and let see what happens... :smile:

**Comment by justinclift** [comment]
k, this is the approach I'm trying first: https://github.com/sqlitebrowser/sqlitebrowser/commit/7e7f356ab62ea59f8cdf95643564ec020b015f6c

Note - that commit is in a temporary branch, so it'll probably disappear in a few hours.

**Comment by lucydodo** [comment]
Nice, Let's see what happens 😄

**Comment by justinclift** [comment]
Interestingly, it looks like the fileio extension is compiling ok with the standard SQLite part of the build.

```
build/DB Browser for SQLite Nightly.app/Contents/Extensions/fileio.dylib: signed Mach-O thin (x86_64) [fileio]
build/DB Browser for SQLite Nightly.app/Contents/Extensions/formats.dylib: signed Mach-O thin (x86_64) [formats]
build/DB Browser for SQLite Nightly.app/Contents/Extensions/math.dylib: signed Mach-O thin (x86_64) [math]
```

That'd make sense for why we're only seeing the macOS warning message on the SQLCipher builds.  Well, that's *if* this turns out to be the cause.

**Comment by justinclift** [comment]
The compile just finished, but it didn't create *any* of the soft links.  So, something still needs adjusting:

```
$ ls -al DB\ Browser\ for\ SQLCipher\ Nightly.app/Contents/Extensions/
total 320
drwxr-xr-x   4 jc  staff    136 13 May 19:16 .
drwxr-xr-x  10 jc  staff    340 13 May 19:16 ..
-rwxr-xr-x   1 jc  staff  70272 13 May 19:16 formats.dylib
-rwxr-xr-x   1 jc  staff  88944 13 May 19:16 math.dylib
```

That being said, it does look like the fileio.dylib soft link not pointing to a file was the cause of the warning message.  This new build SQLCipher build opens fine.  I quit the compile script before it did the upload though. :wink:

Next step is trying to make sure the soft links do actually get created when the file is present...

**Comment by justinclift** [comment]
Ahhh.  It was a bad cut-n-paste on my part.  This next run should work. :smile:

**Comment by lucydodo** [comment]
Nice, the Intel build should work fine now. 😄

**Comment by lucydodo** [comment]
I have some bad news: The notarization of arm64 build is now broken.. 😢

**Comment by justinclift** [comment]
Heh, when it rains it pours. :wink:

**Comment by lucydodo** [comment]
I forgot to close this issue. As we know, this issue has been resolved.
