### ISSUE TITLE
[Bug]: DB Schema panel reset on each query execution

### ISSUE THREAD

**Issue by c-boeckler** [sqlitebrowser/sqlitebrowser#3350]
### What did you do?

I opened a database with one table T and navigated to the tab "Execute SQL".
Then I opened the panel "DB Schema" on the right hand side.
In the DB Schema I expanded the table T (+ sign) and made the Name column wider to show all of the long field names.
Then I executed a trivial SELCT * FROM T query.

### What did you expect to see?

I expected to see the DB Schema panel look the same after the execution as before.

### What did you see instead?

The width of the Name column  was reset to the default width.
The columns of the table T became hidden (as in the default view) and the expand sign (+) was shown again.
This is annoying if you rely on DB Schema to drag column names with spaces over to your query that incrementally evolves.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows, Linux

### OS version

Windows 10, Debian 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
This looks like its been corrected in the nightly.
On Windows, you can download the .zip, extract, and just run the .exe.
On Debian, you probably have to sacrifice a goat or something.  If you can build from the latest source, you should be golden.

**Comment by c-boeckler** [comment]
I can confirm, that my issue is indeed fixed in the nightly (at least for the Windows version).
