### ISSUE TITLE
"Execute SQL" tab cleared on close

### ISSUE THREAD

**Issue by tbayart** [sqlitebrowser/sqlitebrowser#336]
When you close a database, "Execute SQL" tab get cleared.
There is no warning about that.
Logs got cleared too (user & application).

**Comment by justinclift** [comment]
Would you be ok to check if this happens with our latest nightly build?  We've been doing some stuff with not clearing various things at specific times, and there's a chance this one is already taken care of.

If it's still happening with our latest nightly build, then yeah, we can add this to the list of stuff to do.  It sounds both simple, and fairly easy to make configurable.  :smile:

**Comment by tbayart** [comment]
I tested 3.6.99 nightly build.
It happens too.

**Comment by justinclift** [comment]
Thanks.  It doesn't sound like a hard thing to change.  @schdub Is this something you have time to fix? :smile:

**Comment by tbayart** [comment]
Added to the list :wink:

**Comment by MKleusberg** [comment]
@tbayart Sorry for the loooooong delay ☹️ I've finally come around to fix this. If you're still interested, this feature should be in the next nightly build. Are you still around to double check if this is working for you now? If not, no worries, I think we can just close the issue then :smile:

**Comment by tbayart** [comment]
Hi, thank you for the fix :smile: 
I'm not currently working with sqlite but I'm still watching updates. 
I will give it a try as soon as I can.

**Comment by tbayart** [comment]
Tested on latest nighly, it's working fine
Thanks again @MKleusberg

**Comment by MKleusberg** [comment]
Cool, thanks for testing 😃
