### ISSUE TITLE
[Feature]: Display Format for human-readable byte sizes

### ISSUE THREAD

**Issue by VolatileCable** [sqlitebrowser/sqlitebrowser#3363]
### Describe the new feature

The display format would show column with sizes in plain Bytes as MiB/GiB/etc depending on the unit required. Ideally you would have two functions for either IEC-style base2 units (eg, 1 GiB = 1 073 741 824 Bytes) or SI-style base10 units (eg, 1 GB = 1 000 000 000 Bytes)

**Comment by chrisjlocke** [comment]
You can add custom display formats.  They're not permanent (so not selectable in the list) but easy to enter.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/fa72d5e5-2f38-4466-9c9d-d4cb83e0c569)

Just select 'Custom' from the available entries and amend as needed.

**Comment by chrisjlocke** [comment]
> Add a conversion from bytes to GB

Unfortunately there are way too many permutations.  Bytes to MB, Bytes to GB, then bytes to GiB, bytes to KiB, KiB to GiB, etc, etc.  The list would be stupidly long.

**Comment by VolatileCable** [comment]
Maybe I didn't explain it clear enough, but there would only be one function for Byte to closest/best "human-readable" unit, plus a copy of it for the other base notation.

**Comment by chrisjlocke** [comment]
By why just add bytes to GB?  We would need to add grams to KG, litres to pints, elephants to giraffes, etc.  The conversion list is endless.  The custom format, while not ideal, at least gives people an easy ability to change the display format.  This can also be achieved in views.  I use many views at work where we add extra columns to the display for cosmetic purposes.

**Comment by VolatileCable** [comment]
The use case for human-readable byte units is more unique in that you often have wildly varying sizes, while this is often not the case or useful for anything else. But more conversions would definitely be nice and the developers somewhat dug their own grave here by only having a fixed list of conversions and, as far as I can tell, no scripting language powerful enough to just handle all of this without changing code.

**Comment by scottfurry** [comment]
The conversation seems to be spinning in weird directions. I would need to dig into standard libraries to see if there is a *best practices* functions for file size reporting using human-readable and/or si units before asserting this can be done.

However, reporting in non-byte values already exists in the wild - at least for Posix-based systems. See description and `-h` flag for the [`du` command](https://ss64.com/bash/du.html).

**Comment by chrisjlocke** [comment]
Closing as we have custom display formats.  It can be re-opened if a new specific display format is warranted.
