### ISSUE TITLE
[Bug]: sqlcipher nightly build is broken

### ISSUE THREAD

**Issue by eygraber** [sqlitebrowser/sqlitebrowser#3364]
### What did you do?

Installed `sqlitebrowser` from https://ppa.launchpadcontent.net/linuxgndu/sqlitebrowser-testing

### What did you expect to see?

That it uses sqlcipher 4.3.0

### What did you see instead?

It is using sqlcipher 3.4.1

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 22.04

### Relevant log output

```shell
You can see the broken build here https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Thanks for reporting.  I'm not overly familiar with the Linux build process but hopefully someone else who does can have a look to see the issue.

**Comment by scottfurry** [comment]
"Ubuntu Testing" is a term relative to Ubuntu release schedule.
Please clarify: Jammy Jellyfish, Kinetic Kudu, Lunar Lobster

Current view of PPA maintainer's [page](https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing/+packages) is a bit confusing. From what I can discern is that they have not migrated sqlcipher from 4.3.0 to 4.3.1, although the update is available [upstream](https://packages.ubuntu.com/source/mantic/sqlcipher).

Can you pull in SQLCipher from Ubuntu directly?

**Comment by eygraber** [comment]
Jammy. The Ubuntu version of sqlcipher is 3.something (I think 3.4.1)

**Comment by scottfurry** [comment]
@eygraber - please see links provided. If PPA maintainer is not providing an updated SQLCipher, the alternative is to build locally with [upstream version - source info page: SQLCipher](https://packages.ubuntu.com/source/mantic/sqlcipher).

@chrisjlocke - Having a look at our own [build instructions](https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-2), we're referencing someone else's shared repository(or PPA). This may not be prudent if the individual is not keeping up to date (think "bus factor=1" situation). If Ubuntu upstream is staying up to date, we should encourage that path for users.

Overall, this needs a bit of clean up.

**Comment by deepsidhu1313** [comment]
Thanks for reporting the issue. Build was failing because debug symbols were changed for the package in recent update. I have made some changes to fix the issue. That ppa is mainly for sqlitebrowser, we are building other packages to solve the dependencies for sqlitebrowser. Please be advised to not rely on nightly ppa.

Closing the issue. Enjoy sqlcipher 4.5.5.
