### ISSUE TITLE
[Bug]: opening an encrypted database passkey not working on nightly

### ISSUE THREAD

**Issue by eygraber** [sqlitebrowser/sqlitebrowser#3365]
### What did you do?

I opened a database and was prompted for the passkey. I entered the correct passkey.

### What did you expect to see?

That the db would open.

### What did you see instead?

After a second I was prompted to enter the passkey again.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 22.04

### Relevant log output

```shell
I also put the key in a .env file and that doesn't help. If I install stable then the .env works and the database opens.
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
I assume this is related to #3364 where the nightly is using an older version of sqlCipher.  There were definitely differences between v3 and v4.
Thanks for reporting this.  We've not had other reports, but hopefully we can test, confirm and fix this.

**Comment by chrisjlocke** [comment]
Closing as a duplicate (possibly) of 3364.
