### ISSUE TITLE
database saved but when open it is empty

### ISSUE THREAD

**Issue by haiyan-MS** [sqlitebrowser/sqlitebrowser#3366]
Details for the issue
--------------------

#### What did you see instead?
My database showed as large size file, but when I open, everything is 0, 0 tables, although I have large tables in there. 

All my databases are like that now

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19045) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Obviously we don't have a log of actions to determine what steps you took against what steps you performed.  All I can do is run through a 'this workflow works' scenario, and compare it against your actions.  Are your actions repeatable?  ie, if you redo what you did, do you get a large file with no tables again?

I won't include screenshots, but yell back if you need them.  Happy to redo the instructions.

So starting from opening DB4S.  It appears you're opening the SQLCipher version.  Unless you really need encrypted databases, I would stick with the normal DB4S version.

When you start DB4S, there is no database open, so you either have to create one or open one.  Lets create one.
Click 'File' and 'New database'.  Windows will bring up a file dialog to save the database.  This can be anywhere, but a local device is recommended - not a Linux share, NAS drive or on a Raspberry Pi you've got connected.  Store it on your desktop or 'My documents' folder.  Give a simple name, eg, 'database test,db'
After saving the file, DB4S asks for a 'table definition'.  Every database needs one or more tables.  Every table has one or more fields.  So create a table called 'test' with one field 'field1'.
Click the 'Execute sql' tab.  Enter the command
```
insert into test (field1) values (45)
```
Every time you press [F5] you'll add another row in the database.
However, at no point have you 'saved' the database yet.  This is like creating a huge Word document, but you haven't saved it yet.  If Word crashes, you've lost your document.  SQLite is the same.  (Well, DB4S).  So click the 'Write Changes' button in the toolbar, or click 'File' and 'Write changes'.

> My database showed as large size file

When you save a Word document, the whole document is rewritten, so when you look at the file size, this is relative to the file contents.  A document with two characters is going to be a smaller file than a 60-page file full of long paragraphs.
However, in a database, this isn't true.  If you add 50 rows to a database and delete 49 of them, the space those records took up is still in the file.  So you can look at a 49 GB database, and it only holds one record of one field holding one character.

**Comment by haiyan-MS** [comment]
Thank you for the detailed reply. Yes, I was working on a NAS drive. Alternatively, I have to work on ONE drive, which is a cloud drive. I have never had any success saving my SQLite in either place. Is that because the file did not get chance to be correctly uploaded? sometimes I ask the One drive to always keep the file available on hard drive. That works most of time but sometimes the SQLite will crush in the middle, and I lose everything as I described here although I have saved it before.  But now I think of it, the file must have not gotten chance to be saved in the cloud?

**Comment by chrisjlocke** [comment]
I would recommend using the database locally, and syncing to the cloud periodically if you want a backup .. not using the cloud 'direct'.

**Comment by chrisjlocke** [comment]
I'll close this as this isn't a failure with DB4S.  These 'don't use on a network' warnings are mentioned on the SQLite page.  SQLite is for 'local' storage.  If you need a network-related database, then there are free alternatives like PostgreSQL or MySQL.
