### ISSUE TITLE
[Enhancement] Only zoom x-axis in Plot window

### ISSUE THREAD

**Issue by amdkam** [sqlitebrowser/sqlitebrowser#3369]
I have found the Plot window to be very helpful to get a quick insight into my data. 
Especially the scrollable zoom, and data point selection is close to perfect. 
One thing that would make it better, in my case for time series data, is to be able to only zoom the x-axis. At this point scrolling to zoom zooms both the x and y axis. 
Something along the lines of CTRL+scroll only zooms the x-axis. 
Again, thanks for the efforts!

System: 
DB Browser for SQLite Version 3.12.2
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8
SQLite Version 3.35.5.

**Comment by mgrojo** [comment]
If I haven't understood wrong, this is already implemented. You only have to select the axes or axes labels to drag and zoom only in that orientation.

See the wiki for other tips and tricks:
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Plot-Dock
(I made the explanations with images, which are not very helpful, ideally there should be videos...)

**Comment by amdkam** [comment]
You're right, I overlooked that part, my bad. 
In my opinion, selecting the axis in the plot isn't too intuitive, something like ctrl+scroll seems a bit more common, but it feels borderline pedantic to mention this. 
thanks!
