### ISSUE TITLE
DB Browser for SQLite crashes when trying to import CSV file

### ISSUE THREAD

**Issue by Rchop49** [sqlitebrowser/sqlitebrowser#3370]
Details for the issue
--------------------

#### What did you do?
imported csv file from excel into new database

#### What did you expect to see?
data from table imported 

#### What did you see instead?

SQLite crashes and I get this error message: "DB Browser for SQLite quit unexpectedly." 
Have tried multiple times with different CSV files and getting same result. 

Useful extra information
-------------------------
> DB4S v3.12.2 [built for arm64-little_endian-lp64] on macOS 13.2 (darwin/22.3.0) [arm64]
> using SQLCipher Version 4.5.1 community (based on SQLite 3.37.2)
> and Qt 5.15.6

**Comment by chrisjlocke** [comment]
> Have tried multiple times with different CSV files

Have you tried just a one line CSV with 'field1,field2,field3' in it?  Lets start at the bottom and ramp it up.

You're on MacOS, so you could try the nightly to see if that fixes the issue.  
I note you're using the sqlCipher version .. is that an essential?

**Comment by Rchop49** [comment]
Same thing happened with just one line :/ I'm very new to SQL and coding in general, so not familiar with the nightly builds or what the sqlcipher version is

**Comment by chrisjlocke** [comment]
Yes, I would use the nightly.  Its pretty stable, and as you found, seems to fix a couple of issues!
Glad you got it fixed, and thanks for reporting back.
We've not had other reports of this, so seems unfortunate it bit you.
