### ISSUE TITLE
[Bug]: Project closes before warning

### ISSUE THREAD

**Issue by bernard01** [sqlitebrowser/sqlitebrowser#3373]
### What did you do?

On Windows, I accidentally press [Ctrl+4].

Without knowing, I am requesting the opening of another project on the previously opened projects list.

I get a dialog:
"Do you want to save the changes made to project 'myproject.sqbpro'?"

I press "Cancel" because I want to cancel my mistake.

Then I get an error:

"Could not open database file.
Reason: file is not a database"

Then I have lost the changes and the project file and the database are closed.

### What did you expect to see?

I would expect that nothing is closed after my initial "Cancel" response to a dialog.

### What did you see instead?

See above.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 7

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
Good news, @bernard01. This should be fixed in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds). Could you confirm it?

**Comment by justinclift** [comment]
@bernard01 Any interest in testing this out to see if it's working ok for you now? :smile:

**Comment by bernard01** [comment]
> @bernard01 Any interest in testing this out to see if it's working ok for you now? 😄

Thanks. I will test it. I was busy.

**Comment by bernard01** [comment]
I tested my scenario with the new nightly build. Looks like it works as expected.

Pressing the key [Ctrl+4] as described 

1) If I do have pending changes then it gives me the cancel/discard options es expected.
2) If I do not have pending changes then it opens the previous database without prompt, so no harm. 

Thanks very much.

**Comment by justinclift** [comment]
Awesome, thanks heaps for verifying it @bernard01. :smile:

@mgrojo Excellent stuff, you're kicking goals. :grin:
