### ISSUE TITLE
[Feature]: STRICT tables support

### ISSUE THREAD

**Issue by pchemguy** [sqlitebrowser/sqlitebrowser#3374]
### Describe the new feature

Please add support for STRICT tables.

### Does this feature exist in another product or project? Please provide a link

[SQLiteStudio](https://sqlitestudio.pl)

### Do you have a screenshot? Please add screenshots to help explain your idea.
![Clipboard-1](https://github.com/sqlitebrowser/sqlitebrowser/assets/39730837/52d1a990-633c-458d-9d9f-55a7700dc945)

**Comment by chrisjlocke** [comment]
While the GUI has no option, you can issue raw SQL statements to achieve this.
So technically DB4S does support strict tables (as the underlying SQLite used supports it .. and you just issue SQL statements).

**Comment by pchemguy** [comment]
No, it does not:

```sql
CREATE TABLE dummy(dummy TEXT) STRICT;
```

![Clipboard-2](https://github.com/sqlitebrowser/sqlitebrowser/assets/39730837/9a39714e-5502-4ef3-8438-7e70da77aa41)

**Comment by chrisjlocke** [comment]
> And no, "DB Browser for SQLite" does not support the STRICT feature

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/27ab78e3-9f7a-4dba-bad0-71650570fee3)

The 3.12.2 release doesn't, but the nightly does, which uses a more up-to-date version of sqlite.  The internal parser also understands it, as it would need to recognise the keyword.

**Comment by pchemguy** [comment]
For me, it only the matter of the DBS code. I normally update the SQLite library used by DBS to the recent version. I will wait till the next release.

**Comment by chrisjlocke** [comment]
I'll close this as completed then.  :)
