### ISSUE TITLE
New Export of SQL Results to Online M365 Chrome History (sqlite3) in Windows 11 

### ISSUE THREAD

**Issue by AchieveGoals** [sqlitebrowser/sqlitebrowser#3377]
With shift to Windows 11, anyone with Windows 10 loses their active Chrome History (.sqlite3) prior to the online enrollment required by Microsoft 365.  Prior to the upgrade, the Chrome History is Chrome/User Data/Default, but afterwards it is now under Chrome/User Data/Profile 1 but the active user is tied to Chrome/User Data/Profile 2.  In both cases, there is a History (.sqlite3) and a History.journal.

My workaround was to copy the 2 History files from Profile 1 over Profile 2's History files.

As I use sqlitebrowser on both Windows and Linux, it would be preferable to be able to read in the HIstory (.sqlite) in Windows Profile 1 and Profile 2 and then export Profile 2/History properly. 

I would be willing to provide testing of this solution.

**Comment by AchieveGoals** [comment]
Requirement:   Able to have effective "Never expire" of history. 
Note:  I have reviewed about a dozen solutions to export History to CSV but nothing to write them,
 - python3 (browserhistory module) ( code is 4 lines including import)
 - DB browser - exports query (from Safari, Chrome, etc) to CSV 
 - command line sqlite3 to export to csv

I will be posting those sample read History to CSV solutions to AchieveGoals some time this month if any interest.

**Comment by chrisjlocke** [comment]
So this isn't an issue per se with DB4S, but you've a use case for the usage of DB4S, is that correct?

**Comment by chrisjlocke** [comment]
Closing as doesn't appear to be a DB4S issue.
