### ISSUE TITLE
the issuer certificate of a locally looked up certificate could not be found

### ISSUE THREAD

**Issue by DiegoMeza3090** [sqlitebrowser/sqlitebrowser#3378]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17763) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Is this when starting the application?  DB4S does a current version check.
We recently renewed some certificates on the servers, so this might be a 'crossed in the post' situation.
Do you still get the error if you close DB4S and restart it?

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
