### ISSUE TITLE
[Bug]: Filtering a column value can make the columns header disappear

### ISSUE THREAD

**Issue by davidmartos96** [sqlitebrowser/sqlitebrowser#3379]
### What did you do?

When filtering a column value in the "Browse data" tab, it appears to be an edge case where the headers get hidden, even when there are some results.

From my tests these appear to be the conditions for that to happen:

* Filter by something that fits into the viewport
* Type an extra character that satisfies the current filter and doesn't change the number of filtered results

What ends up happening is that the headers are hidden. Below I provide some screenshots.

Resizing the right panel will make the header display again, so I'd say it has to do with the viewport calculations when filtering.

### What did you expect to see?

The header should remain visible

### What did you see instead?

# First filter
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/22084723/c96398c6-492c-4a18-acbf-90eefcd48e7f)

# Type an extra character
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/22084723/77b53951-0c7c-4927-a490-7633aba71522)

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Fedora 37

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
@davidmartos96, thanks for the detail report. I was able to reproduce it and fix it. Could you confirm it's working for you with the next [nightly build.](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)

**Comment by justinclift** [comment]
@davidmartos96 Would you have the time and interest to verify this is working ok for you now? :smile:

**Comment by davidmartos96** [comment]
@mgrojo @justinclift It's working great now. Thank you! :smile:

**Comment by justinclift** [comment]
Awesome.  Good stuff @mgrojo. :smile:
