### ISSUE TITLE
Windows installer runs program as wrong user

### ISSUE THREAD

**Issue by ccw808** [sqlitebrowser/sqlitebrowser#338]
At the end of installation, you are given an option to run the program. However the program is run as an administrator user, rather than the user that initially launched the installer.

**Comment by justinclift** [comment]
Oh, that doesn't sound good.  Which OS are you using, and which version of DB4S?

**Comment by ccw808** [comment]
Windows 7 64 bit and version 3.6.0

**Comment by schdub** [comment]
@ccw808, do you mean "Run DB Browser for SQLite" checkbox on "Complete DB Browser for SQLite Setup" page?
I think it is normal behaviour when you run the application from the installer NSIS.
New process inherits permissions from the parent process - in this case the process installer, which was elevated with UAC.

**Comment by ccw808** [comment]
The UAC plug-in for NSIS has a UAC_AsUser_ExecShell macro which can be used instead of ExecShell

**Comment by justinclift** [comment]
Ahhh, that sounds like it might do the trick.  @rp- Sounds like an easy fix?

**Comment by rp-** [comment]
It would probably an easy fix if we had a standalon NSIS script, but our script is generated by CMAKE/CPACK and there are some settings and variables that can be tuned, but I didn't have time to look at them.

**Comment by chrisjlocke** [comment]
Posted this in #974, so a bit of cross-posting.... ;)

This might help.

http://stackoverflow.com/questions/16555625/how-to-launch-an-executable-on-the-end-of-installation-correctly

> Use `Exec '"$WINDIR\explorer.exe" "$TEMP\MyUnElevatedProcess.exe"'`

**Comment by justinclift** [comment]
In theory :wink:, that last commit should mean the installer launches DB4S in user mode, not admin mode.

In testing here in a local VM it seems to work ok, but it'd be useful to have other people test and confirm it before I'm confident about it.

@ccw808 @chrisjlocke Would either of you have the time/interest in trying tomorrow's nightly build (3rd May or later) to check?

**Comment by chrisjlocke** [comment]
Will do.  😸

**Comment by chrisjlocke** [comment]
Now works fine. \o/  🥇

**Comment by justinclift** [comment]
Thanks @chrisjlocke, really appreciate you taking the time for this. :smile:
