### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by habixiong** [sqlitebrowser/sqlitebrowser#3381]
error message: malformed database schema (Ability) - urrecognized token:
file:
https://pan.baidu.com/s/1UuilZYhz0njmEsqAkHRGig 
code: pqe3
can someone help me ,thx

**Comment by habixiong** [comment]
I uploaded this file to DBHub, but it prompted me with: "malformed database schema (Ability) - unrecognized token: '#' (PRAGMA integrity_check) (database disk image is malformed)." 
So, I uploaded it to another server instead. 
Here's the link: http://qipao.57g.net/file/EFTable_Ability.db.
I hope you can help me take a look at it. Thank you very much.

**Comment by chrisjlocke** [comment]
Well, thats useful.

> unrecognized token: '#' (PRAGMA integrity_check)

Thats a SQL statement, not a database.  I'll write up a wiki page, but there are two files.  The database is a binary file containing your records, tables, indexes, etc.  A .sql file is a text file containing instructions to perform on the database file, eg, 'insert into table (field1, field2) values (value1,value2)', etc.  
When you open a database file or upload to DBHub.io, it expects the binary file.  It looks like you're trying to open or upload the text instructions.

So lets try this.

Start DB4S from scratch.  Close any database if you have one open.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/ea03cf9c-8ca2-4669-b54c-77d67dab776e)

Click 'File' and 'Import' and 'Database from SQL file'.
Open the file you uploaded to qipao.57g.net

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/15d3895f-b83b-4cb4-a7a4-aaae8231e875)

You'll then get prompted to save the file.  This is now saving the text SQL file as a binary database (of records and tables).  Save this somewhere, eg, your desktop.

Ideally, rename that eftable_ability.db to eftable_ability.sql.  Its not a .db (I suspect) but a .sql file.

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
