### ISSUE TITLE
[Bug]: Unable to add accented letters

### ISSUE THREAD

**Issue by rik1301** [sqlitebrowser/sqlitebrowser#3382]
### What did you do?

In Browse Date view, trying to add accented letters use the ALT +numbers short keys don't add the letters but instead opens up a bunch of unwanted menus.  ALT 0241 for ñ, being one such example.

### What did you expect to see?

Accented letter.

### What did you see instead?

A bunch of unwanted menus opening.

### DB4S Version

3.12.0

### What OS are you seeing the problem on?

Windows

### OS version

8.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Yes, [Alt]+[0] is to reset the window layout, so I suspect that is interpreted before it is passed to the text widget.  Moving that key combination might resolve that.  I suspect [Alt]+[0] has no effect in Linux, so the [Alt]+[0241] combination wouldn't do anything... so its never thought to be a problem.

There are two workarounds, neither of which are particularly nice.  You can either use the charmap program to copy the character to the clipboard, or use another text editor, eg, Notepad, to use [Alt]+[0241] into and then copy/paste that into DB4S.  Not great by any stretch of the imagination.

Thanks for reporting it.  
I'm wondering if that key combination could be moved in a nightly, and then put back, giving you at least one development edition to play with.  I would suggest 'build it yourself' but compiling on Windows is a huge task.  I've never succeeded.  So tweaking the nightly may be doable.

**Comment by mgrojo** [comment]
I would have thought that Windows would capture the keyboard shortcut and do its thing. In any case, does it happen with both the keypad numbers and the numbers in the first keyboard row?

**Comment by chrisjlocke** [comment]
Only ALT+keypad numbers allows the entering of extended characters.  You can't use the normal row of numbers along the top of the keyboard.

**Comment by mgrojo** [comment]
That's what I thought, but then Qt should understand "Alt+0" as only Alt+(0 not in keypad only), so the standard shortcut still works.

**Comment by rik1301** [comment]
> Yes, [Alt]+[0] is to reset the window layout, so I suspect that is interpreted before it is passed to the text widget. Moving that key combination might resolve that. I suspect [Alt]+[0] has no effect in Linux, so the [Alt]+[0241] combination wouldn't do anything... so its never thought to be a problem.
> 
> There are two workarounds, neither of which are particularly nice. You can either use the charmap program to copy the character to the clipboard, or use another text editor, eg, Notepad, to use [Alt]+[0241] into and then copy/paste that into DB4S. Not great by any stretch of the imagination.
> 
> Thanks for reporting it. I'm wondering if that key combination could be moved in a nightly, and then put back, giving you at least one development edition to play with. I would suggest 'build it yourself' but compiling on Windows is a huge task. I've never succeeded. So tweaking the nightly may be doable.

Thanks Chris.  My database is in English so the very occasional record with a foreign company name with accents is not a big issue.  I can manage with creating them externally and pasting them in.

**Comment by mgrojo** [comment]
I was investigating this, and I didn't find a way to discriminate between numbers in keypad and numbers in the first keyboard row. So, if we want to not eclipse this function, the only alternative is to move these shortcuts. I think there will be more people used to this Windows function than to our shortcuts for "Reset Window Layout" or "Switch to tab 1" and so on.

I suggest:
* "Reset Window Layout" -> Ctrl+Alt+0 (an arcane shortcut for an arcane function)
* "Switch to tab X" -> Ctrl+FX (it seems to be free in desktops and [in use by many applications](https://defkey.com/what-means/ctrl-f1))

**Comment by mgrojo** [comment]
Oh, we have "Ctrl+F4" for "Close the current database file". Too many functions for so few fingers and keys :smile:

**Comment by mgrojo** [comment]
@rik1301, I found a comment of mine in some similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/153#issuecomment-520225615

> In Linux, this method works both for Qt input fields and Scintilla:
> 
> > Type Ctrl+⇧ Shift+U, then type up to eight hexadecimal digits corresponding to the character to be inserted, and then type ↵ Enter.
> 
> I have tested under wine and it also works, but I guess it was some wine feature, and in Windows might not work. Someone can confirm?

Could you confirm?

**Comment by mgrojo** [comment]
@rik1301, the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) will replace the Alt+Number shortcuts with the following new accelerators:

- Alt+D Database Structure
- Alt+B Browse Data
- Alt+R Edit Pragmas
- Alt+X Execute SQL

Could you confirm that the insertion of special characters is working now on Windows? I've only tested under Linux, where that functionality isn't available.

**Comment by chrisjlocke** [comment]
> Could you confirm that the insertion of special characters is working now on Windows? 

@rik1301 - Can you confirm if this is now working please?

**Comment by rik1301** [comment]
Thanks Chris.,  I'm not in a position to be downloading new versions right now.  If it's working fine for you in your latest version then I guess the change is functioning correctly.
Rgds.

**Comment by rik1301** [comment]
Or you can check with other Windows users here if you only have Linux installed.
