### ISSUE TITLE
[Bug]: On windows - couldn't download, virus detected

### ISSUE THREAD

**Issue by pcsee** [sqlitebrowser/sqlitebrowser#3383]
### What did you do?

Download sqlitebrowser installer

### What did you expect to see?

Uninterrupted download on Windows

### What did you see instead?

An error at the end of download stating "possible virus detected"

Is there a plan to resolve this issue? We cannot use it in the company if downloads are not possible because of "potential viruses".

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
There are a number of solutions.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/6f14cb23-bc70-401c-96fa-8eddf68a0f77)

On the Github page, the downloads have the SHA256 hash.  If you download a file, you can compare the hash with this list.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/1e112cb3-f7bd-47fb-aaab-a85321a3429c)

You can upload the file you just downloaded to virustotal.com - this would confirm or deny if the file contains anything malicious.

This checks a number of virus detection engines, not just one.

> Is there a plan to resolve this issue? 

We've had no similar reports of our files becoming infected.
All files on the server match the hashes of the originally uploaded files.
I've not personally downloaded each file again and submitted to VirusTotal, but they were checked before uploading.  While the hashes are the same, this doesn't assume the file is still clean, as the detection engines change.

Let me know what file you were downloading, and I can submit to VirusTotal for checking.  The 32-bit MSI provided the above screenshot.

> possible virus

This does not indicate an actual virus was found.  

Don't forget you can download the source and build from source if you want a 100% known-to-be-safe binary.

**Comment by lucydodo** [comment]
Additionally, can you tell us which web browser was used for the download?

**Comment by pcsee** [comment]
Thanks for the reply!
I downloaded [DB.Browser.for.SQLite-3.12.2-win64.zip](https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.2/DB.Browser.for.SQLite-3.12.2-win64.zip) on Microsoft Edge Version 114.0.1823.51 (Official build) (64-bit)

**Comment by pcsee** [comment]
This version https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.2/DB.Browser.for.SQLite-3.12.2-win32.zip can be downloaded without problem.

**Comment by justinclift** [comment]
That's really weird.  The download server there has been online and maintained for years, and the downloads there are known to be good.

I have no idea why your browser is claiming dodgy stuff.  If you find out more info at some point, please let us know. :smile:

**Comment by chrisjlocke** [comment]
The link you've posted is a GitHub link, so did you download it from the GitHub page or the SQLitebrowser website?
If the former, then I would very highly doubt Microsoft would allow software to have viruses in it, and their files would regularly get checked.

Again, I would download the file and submit to virustotal.com.  Don't forget there is a possibility your machine could be infected and could be injecting malicious content into downloads.  This is why we supply SHA256 checksums.  Check the file you've downloaded to ensure it has the same hash as ours.  If it does, the file is the same.

**Comment by pcsee** [comment]
Ok, I will try. Thanks

**Comment by chrisjlocke** [comment]
Closing due to lack of response and no other reports of a virus.
