### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by sanjay7895** [sqlitebrowser/sqlitebrowser#3385]
[WARNING] there has been a problem while writing to the session file ('OperationalError: attempt to write a readonly database'

**Comment by chrisjlocke** [comment]
Is this on a local database/filesystem, or across a network, etc?
Was there an error prior to this?
This usually occurs if there is an existing journal file (https://github.com/sqlitebrowser/sqlitebrowser/wiki/Running-an-Integrity-Check) and that usually occurs if DB4S crashes in the ,middle of a process.

**Comment by chrisjlocke** [comment]
This sounds like another application that is using a sqlite database as the original error isn't from DB4S.
I'll close this as no further information has been provided.
Once we have more information, we can assist further.
