### ISSUE TITLE
how do a cte in dbrowser sqlite

### ISSUE THREAD

**Issue by etiel-camilla** [sqlitebrowser/sqlitebrowser#3387]

**Comment by justinclift** [comment]
Guessing you're meaning in the Execute SQL tab?

If that's the case, then standard SQLite CTE's should work fine.

eg:

https://blog.expensify.com/2015/09/25/the-simplest-sqlite-common-table-expression-tutorial/
(random search result looking for a SQLite CTE page) :smile:
