### ISSUE TITLE
Incorrect results from query

### ISSUE THREAD

**Issue by Eliyahu354** [sqlitebrowser/sqlitebrowser#3389]
Details for the issue
--------------------

#### What did you do?

select InvoiceDate,BillingAddress, BillingCity,total
from Invoice
WHERE  date(InvoiceDate)  >  ' 2010-05-22 00:00:00 ' 
order by InvoiceDate

#### What did you expect to see?
All invoices later than  ' 2010-05-22 00:00:00 ' 

#### What did you see instead?
invoices from 2009

Useful extra information
<img width="700" alt="Screenshot 2023-06-28 at 12 17 51" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/137999886/658c1662-660e-4883-b17f-2a7f269f3c48">

-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/22.5.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by chrisjlocke** [comment]
Is invoiceDate a text field, or is it numeric and you've set a display format?

**Comment by chrisjlocke** [comment]
What is the output if you type
```
select date('2010-05-06')
```

**Comment by Eliyahu354** [comment]
<img width="410" alt="Screenshot 2023-06-28 at 13 02 27" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/137999886/42cf8cf7-09af-47dd-b219-7193478f4b50">

**Comment by justinclift** [comment]
If you do this, is the output any different?

```
select InvoiceDate,BillingAddress, BillingCity,total
from Invoice
WHERE date(InvoiceDate) > '2010-05-22'
order by InvoiceDate
```

**Comment by chrisjlocke** [comment]
Well spotted.  Mr Hawk Eyes is in the room!

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by Eliyahu354** [comment]
Thanks guys!!
