### ISSUE TITLE
Windows 8

### ISSUE THREAD

**Issue by pbaker1977** [sqlitebrowser/sqlitebrowser#339]
Every time i open a database the sqlitebrowser automatically stops working. why? do I need to install something to enable it work properly?

**Comment by justinclift** [comment]
Which version of DB4S are you using, and is it 32 or 64 bit?

**Comment by pbaker1977** [comment]
Version 3.6.0

Kind Regards,


Paul




Paul Baker


Possibler


DDI: 01299 254787


E: Paul.Baker@drpgroup.com<mailto:Paul.Baker@drpgroup.com>





________________________________

London
+44(0)20 7937 8057

56 Shorts Gardens,
Covent Garden,
London WC2H9AN


________________________________

Midlands
+44(0)1299 250 531

212 Ikon Estate,
Droitwich Road,
Hartlebury DY10 4EU


________________________________

North
+44(0)113 3970 890

4100 Park Approach,
Thorpe Park,
Leeds LS15 8GB






[cid:imagea59f06.PNG@af3b00b9.4a85889d]





Winner: C&IT Awards Agency of the Year 2014





Follow @drpgroup<http://www.twitter.com/drpgroup> on Twitter or check here <http://www.drpgroup.com/#/news> for our latest news or visit our youtube<http://www.youtube.com/drpgroup> channel.





[cid:image36ea20.JPG@f7e96804.4395a00c]




Privileged /Confidential information and/or copyright material may be contained in this email.  The information and material is confidential and intended for the use of the addressee(s) only. If you are not the addressee or the person responsible for delivering it to the intended addressee(s), you may not copy or deliver it to anyone else or use it in any unauthorized manner.  To do so is strictly prohibited and may be unlawful.  Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system.  Any views or opinions presented are solely those of the author and do not necessarily represent those of drpgroup.Employees of the company are expressly required not to make defamatory statements and not to infringe or authorize any infringement of copyright or any other legal right by email communications. Any such communication is contrary to company policy and outside the scope of the employment of the individual concerned. The company will not accept any liability in respect of such communication, and the employee responsible will be personally liable for any damages or other liability arising. Although this email and attachments are believed to be free of any virus or other defects which might affect any computer or IT systems into which they are received, no responsibility is accepted by drgroup for any loss or damage arising in any way from the receipt or use thereof. No employee or agent is authorized to conclude any binding agreement on behalf of drpgroup with another party by email without express written confirmation by a board director of drpgroup. drpgroup accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.


drpgroup refers to DRP UK Limited, registered number 03653794, DRP Holdings Limited, registered number 04519180, DRP Technical Services Limited, registered number 04224047, and Corporate Media Displays Limited, registered number 03959886, all of which are limited company’s registered in England and Wales, with their Registered Office being: Unit 212 Ikon Industrial Estate, Droitwich Road, Hartlebury, Worcestershire, DY10 4EU

**Comment by justinclift** [comment]
Hmmm, it sounds like a dependency is missing or something.  @glawrence Do you have a Win8 VM handy you can try it out on?

**Comment by pbaker1977** [comment]
No really, I use at work on a windows 7 PC which works fine but at home I have a windows 8 PC which appears to work fine up until i try and open a database.




Paul Baker


Possibler


DDI: 01299 254787


E: Paul.Baker@drpgroup.com<mailto:Paul.Baker@drpgroup.com>





________________________________

London
+44(0)20 7937 8057

56 Shorts Gardens,
Covent Garden,
London WC2H9AN


________________________________

Midlands
+44(0)1299 250 531

212 Ikon Estate,
Droitwich Road,
Hartlebury DY10 4EU


________________________________

North
+44(0)113 3970 890

4100 Park Approach,
Thorpe Park,
Leeds LS15 8GB






[cid:image1a821d.PNG@aca71131.4bac020c]





Winner: C&IT Awards Agency of the Year 2014





Follow @drpgroup<http://www.twitter.com/drpgroup> on Twitter or check here <http://www.drpgroup.com/#/news> for our latest news or visit our youtube<http://www.youtube.com/drpgroup> channel.





[cid:image6b1a61.JPG@4556bf0b.42aac06b]




Privileged /Confidential information and/or copyright material may be contained in this email.  The information and material is confidential and intended for the use of the addressee(s) only. If you are not the addressee or the person responsible for delivering it to the intended addressee(s), you may not copy or deliver it to anyone else or use it in any unauthorized manner.  To do so is strictly prohibited and may be unlawful.  Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system.  Any views or opinions presented are solely those of the author and do not necessarily represent those of drpgroup.Employees of the company are expressly required not to make defamatory statements and not to infringe or authorize any infringement of copyright or any other legal right by email communications. Any such communication is contrary to company policy and outside the scope of the employment of the individual concerned. The company will not accept any liability in respect of such communication, and the employee responsible will be personally liable for any damages or other liability arising. Although this email and attachments are believed to be free of any virus or other defects which might affect any computer or IT systems into which they are received, no responsibility is accepted by drgroup for any loss or damage arising in any way from the receipt or use thereof. No employee or agent is authorized to conclude any binding agreement on behalf of drpgroup with another party by email without express written confirmation by a board director of drpgroup. drpgroup accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.


drpgroup refers to DRP UK Limited, registered number 03653794, DRP Holdings Limited, registered number 04519180, DRP Technical Services Limited, registered number 04224047, and Corporate Media Displays Limited, registered number 03959886, all of which are limited company’s registered in England and Wales, with their Registered Office being: Unit 212 Ikon Industrial Estate, Droitwich Road, Hartlebury, Worcestershire, DY10 4EU



________________________________

**Comment by justinclift** [comment]
When it stops working, does an error message get shown or something, or does the program just exit or ?

**Comment by pbaker1977** [comment]
the following message gets displayed.





Paul Baker


Possibler


DDI: 01299 254787


E: Paul.Baker@drpgroup.com<mailto:Paul.Baker@drpgroup.com>





________________________________

London
+44(0)20 7937 8057

56 Shorts Gardens,
Covent Garden,
London WC2H9AN


________________________________

Midlands
+44(0)1299 250 531

212 Ikon Estate,
Droitwich Road,
Hartlebury DY10 4EU


________________________________

North
+44(0)113 3970 890

4100 Park Approach,
Thorpe Park,
Leeds LS15 8GB






[cid:imagee6a099.PNG@68240a3a.4e8ef736]





Winner: C&IT Awards Agency of the Year 2014





Follow @drpgroup<http://www.twitter.com/drpgroup> on Twitter or check here <http://www.drpgroup.com/#/news> for our latest news or visit our youtube<http://www.youtube.com/drpgroup> channel.





[cid:image62a3e3.JPG@2b0e9fb5.42b26ffe]




Privileged /Confidential information and/or copyright material may be contained in this email.  The information and material is confidential and intended for the use of the addressee(s) only. If you are not the addressee or the person responsible for delivering it to the intended addressee(s), you may not copy or deliver it to anyone else or use it in any unauthorized manner.  To do so is strictly prohibited and may be unlawful.  Please notify the sender immediately by email if you have received this email by mistake and delete this email from your system.  Any views or opinions presented are solely those of the author and do not necessarily represent those of drpgroup.Employees of the company are expressly required not to make defamatory statements and not to infringe or authorize any infringement of copyright or any other legal right by email communications. Any such communication is contrary to company policy and outside the scope of the employment of the individual concerned. The company will not accept any liability in respect of such communication, and the employee responsible will be personally liable for any damages or other liability arising. Although this email and attachments are believed to be free of any virus or other defects which might affect any computer or IT systems into which they are received, no responsibility is accepted by drgroup for any loss or damage arising in any way from the receipt or use thereof. No employee or agent is authorized to conclude any binding agreement on behalf of drpgroup with another party by email without express written confirmation by a board director of drpgroup. drpgroup accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.


drpgroup refers to DRP UK Limited, registered number 03653794, DRP Holdings Limited, registered number 04519180, DRP Technical Services Limited, registered number 04224047, and Corporate Media Displays Limited, registered number 03959886, all of which are limited company’s registered in England and Wales, with their Registered Office being: Unit 212 Ikon Industrial Estate, Droitwich Road, Hartlebury, Worcestershire, DY10 4EU



________________________________

**Comment by justinclift** [comment]
Hmmm, there's not picture attached. (GitHub drops attachments from email responses)

If you drag-and-drop the picture into a comment here in the GitHub issue though, that should work. (eg that should add the image into the comment)

**Comment by pbaker1977** [comment]
![pic1](https://cloud.githubusercontent.com/assets/10552942/7993296/2233041c-0afd-11e5-9d13-00ff45f34f47.jpg)

**Comment by pbaker1977** [comment]
there is the message i'm getting

**Comment by justinclift** [comment]
Thanks, that's helpful.  If you click Debug, what gets shown?

**Comment by pbaker1977** [comment]
It opens visual studio...
![pic1](https://cloud.githubusercontent.com/assets/10552942/7993406/e66bdcf0-0afd-11e5-9f4a-c1954f1c7db9.jpg)

**Comment by pbaker1977** [comment]
After clicking yes - i get this screen in visual studio...

**Comment by pbaker1977** [comment]
![pic1](https://cloud.githubusercontent.com/assets/10552942/7993473/3c3c3d46-0afe-11e5-8890-3d1ba042959e.jpg)

**Comment by schdub** [comment]
@pbaker1977, do you open same database file on Win8 and Win7?

DB4S is 64 bit?

"0xC0000374: A heap has been corrupted" - it's really bad.

**Comment by justinclift** [comment]
@pbaker1977 Yeah, as @schdub mentions... are you using the 32-bit or 64-bit version of DB4S?

With our recent 3.6.0 release, it's the first time we've had both 32-bit and 64-bit versions for Windows available.  Thinking maybe you might have the wrong one. :wink:  (and kind of hoping it's that easy! :wink:)

**Comment by pbaker1977** [comment]
So i should try the 32-bit version?

**Comment by pbaker1977** [comment]
Yep the 32-bit versions seems to be ok.  thanks for the help

**Comment by justinclift** [comment]
Interesting.  It sounds like one of the 64-bit libraries installed on your system isn't happy.

If the 32-bit version works well for you, keep on using that. :smile:  If you need to use large databases though (eg 1GB+), you'll probably need the 64-bit version and we'll need to figure out what's wrong.

**Comment by pbaker1977** [comment]
Ok thanks any how.  I'm happy with the 32-bit so far as the databases I'm using aren't that big...yet!
