### ISSUE TITLE
Permission to publish "Sqlitebrowser" app in Umbrel App store

### ISSUE THREAD

**Issue by IMPranshu** [sqlitebrowser/sqlitebrowser#3391]
### Describe the new feature

Hi team,

I need your team's permission to try and host this app on the Umbrel App Store. I have given appropriate credits and mentions to your team as you are the sole Developer of the App I am just publishing it to the Umbrel App Store for free as I have done with a lot of other OSS applications.

It would be great to have a go-ahead from your team as I have already created a PR https://github.com/getumbrel/umbrel-apps/pull/267 for this but it has been closed as I was not the developer of this application

Thanks,
Pranshu

**Comment by FriedrichFroebel** [comment]
You probably should not assume that everyone is familiar what the *Umbrel App Store* is, so adding some basic explanation here about what it is and why it would be beneficial to have DB4S there might help (personally I am no big fan of third-party publishing as new releases might be delayed to some extent, but everyone can have its own opinion on this and for FOSS nobody can really restrict you).

> it has been closed as I was not the developer of this application

Where is this reasoning given? The above PR has been closed without any public comment, so there must have been some additional private communication?

**Comment by justinclift** [comment]
Yeah, I've not personally heard of it either.

Looking at the front page readme of that repo, it has this:

```
If you can code in any language, you already know how to develop an app for Umbrel. There is no restriction on the kind of programming languages, frameworks or databases that you can use. Apps run inside isolated Docker containers, and the only requirement (for now) is that they should have a web-based UI.
```

If the `the only requirement (for now) is that they should have a web-based UI` piece is still correct, then that's not going to work for DB Browser for SQLite, as it doesn't have a web-based UI.  There is the dbhub.io part of things, but that's a pain to set up manually.  Like, it *could* be done, but it would take some effort.

**Comment by FriedrichFroebel** [comment]
Given https://github.com/getumbrel/umbrel-apps/pull/267/files#diff-c4953aeeea6ca06a59d7c06dad3f9db1ebea54639ec3aabf19c0e61b38fbddc0R10, this uses the Docker image from https://hub.docker.com/r/linuxserver/sqlitebrowser / https://github.com/linuxserver/docker-sqlitebrowser

**Comment by justinclift** [comment]
@FriedrichFroebel Heh, that's kind of cool.  Didn't even know those existed either. :smile:

**Comment by IMPranshu** [comment]
> @FriedrichFroebel Heh, that's kind of cool. Didn't even know those existed either. 😄

Me neither but I was amazed after using it and then thought of publishing it to the Umbrel App Store because at that time I was extensively tinkering around Umbrel codebase. You can check https://fleet.linuxserver.io/ to checkout a bunch of cool apps that can be run using just docker and browser.

**Comment by justinclift** [comment]
I've just added a comment on the original issue.  Hopefully that's all it takes.

**Comment by IMPranshu** [comment]
Absolutely. Thanks.

**Comment by chrisjlocke** [comment]
Closing as completed.
