### ISSUE TITLE
SQL window closes with no changes saved. URGENT FIX !!!

### ISSUE THREAD

**Issue by AbrahamOsco** [sqlitebrowser/sqlitebrowser#3392]
On ubuntu 22.04 when you load the **northwin** toy database AND type :
```
SELECT * FROM Products
WHERE ProductID = 100
```
Then you press Control + R about 10 times.
And then you change:
`WHERE ProductID = 20 (or other number)
`the SQL window closes.
Please fix the BUG

**Comment by chrisjlocke** [comment]
This seems odd.  Did this happen once, or does it happen every time and you can replicate it?
While you're on Linux, you don't mention what version of DB4S you're using.  If you click 'Help' and 'About', it will provide this information.

**Comment by justinclift** [comment]
@AbrahamOsco Also, do you know if the version you installed is from a snap, or did you manually install from a PPA, (etc).

**Comment by AbrahamOsco** [comment]
Hello good evening,
It happens and I can replicate it perfectly.
when I write:
```
SELECT * FROM Products
WHERE ProductID = 100
```
Press control + R many times:
and then change the value:
```
SELECT * FROM Products
WHERE ProductID = 20 (or other number)
```
And we press control + r again -> The window is closed, the changes are lost.
That happens in ubuntu, I format my PC. Now today I switched to linux mint exactly the same thing happens. I leave the database for you to repeat the error: https://en.wikiversity.org/wiki/Database_Examples/Northwind/SQLite

The way to install sqlLite and SQLBroswer is through the terminal.
```
sudo apt install sqlite3
sudo apt update
sudo apt install sqlitebrowser
```
This installation was like this in both ubuntu and linux mint. (Linux Mint 21.1 "Vera").

The error keeps happening, I don't understand what causes that error?
Haven't tried it yet with other databases.
<img src = "https://i.ibb.co/NWhcD6c/FIX-BUG.png" >

**Comment by justinclift** [comment]
That version is a bit unexpected, as it's not our last official release (which was 3.12.2).

That aside, I'd recommend un-installing that one as it's clearly not stable.  Instead, try the .AppImage build from here:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

That "continuous" release is freshly rebuilt every time we make a change in our source code, and should be pretty stable at the moment.  Just download it, `chmod +x` on it to make it executable, and it should work.

If you run into any weirdness with that one, please let us know. :smile:

**Comment by chrisjlocke** [comment]
> Press control + R many times

Why are you pressing [Ctrl]+[R] many times?  Is this because another process or program has access to the database?  Is the database local or on a network?

**Comment by AbrahamOsco** [comment]
problem solved
using as sqlbrowser: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous.

@chrisjlocke  I press many times [ctrl] + [r] simply for habit.

<img src= "https://ibb.co/kmDXWZ1" > 

Thank you very much for the help

**Comment by justinclift** [comment]
Awesome. I'll close this issue then. :smile:

**Comment by chrisjlocke** [comment]
Glad you got it solved, and thanks for reporting back.
