### ISSUE TITLE
[Feature]: Add pull down menu for foreign keys in insert window

### ISSUE THREAD

**Issue by ceving** [sqlitebrowser/sqlitebrowser#3401]
### Describe the new feature

When you insert a row into a table using foreign keys, you have to manually enter the integer ID. This is in particular difficult, because Sqlitebrowser does not allow you to show more than one table. So you can not show the parent table while entering data in the table with the foreign key constraint. It would be nice, if the insert shows the contents of the parent table in an select box.

**Comment by chrisjlocke** [comment]
This is a common requirement.  
The nightly build of DB4S does allow multiple windows to be opened at the same time.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/5e69fc84-1f20-4183-a637-e84a76408aa9)

So you can have multiple tables, and dock windows with multiple tabs.

**Comment by mgrojo** [comment]
Do you mean a combo box in the Insert Record window as done in the Data Browser?

**Comment by chrisjlocke** [comment]
Closing as duplicate, and no response.
