### ISSUE TITLE
Wrong display in cells DB Browser for SQLite

### ISSUE THREAD

**Issue by AugustinHourquet** [sqlitebrowser/sqlitebrowser#3403]
Details for the issue
--------------------

#### What did you do?
I got a database file from someone using Windows and open it using Mac OS. This database contains Lots having IDs. The ID is well displayed on Windows but in Mac OS some really annoying 'extra spaces' came in. Maybe encoding issue ?

#### What did you expect to see?
My 'normal' Lot ID like so : 'Lot_YYYY-MM-DD-hh:mm:ss'

#### What did you see instead?
check this link to see what it looks like on my computer
https://docsend.com/view/87eq9hthc2uqtwdh

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on macOS 10.16 (darwin/20.6.0) [x86_64]
> using SQLCipher Version 4.4.3 community (based on SQLite 3.34.1)
> and Qt 5.15.2

**Comment by scottfurry** [comment]
Top of head guess is that problem is rooted in text encoding. Windows default encoding is `Windows-1252`, setting to UTF-8 requires some effort, IIRC. Default encoding in MacOS is UTF-16LE. There may be some text conversion problem happening where the extra spaces are actually `NULL` characters as text is not being converted/processed.

A workaround is to make use of [SQLite date/time functions](https://www.sqlite.org/lang_datefunc.html) to clean up(uses same flags as strftime).

**Comment by chrisjlocke** [comment]
Click 'Edit' and 'Preferences'.  Click the 'Database' tab.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/cb1343cd-12f9-471d-906f-4806f67563ba)

What font have you got?  Try changing it to a different one, and seeing if the effect changes.

**Comment by AugustinHourquet** [comment]
> 

Works perfectly with an other font! 
I use 'Apple SD Gothic Neo' and my problem is solved :))
Thank you

**Comment by chrisjlocke** [comment]
Thanks for reporting back.
Just for the avoidance of doubt, and to help someone else, I assume this was the 'default' font.  Do you happen to know what font it was showing?
Maybe the default needs to be amended for macOS.

**Comment by AugustinHourquet** [comment]
Unfortunately when I ask to restore default settings, the font field is blank... And my problem does not even reappear.
I don't know what happened.
But now it seems to work with various fonts, I tried 'Arial' that works great. Maybe amend the default font to Arial would solve the problem for macOS users.

**Comment by scottfurry** [comment]
In DB4S settings, the `General` section does not set a default font. For all other displays(data browser and SQL controls), Monospace font is used. The fallback *should be* font Qt sets for Application as a whole.

On MacOS, font can be reviewed/set via `Font Book` application. And I discovered that MacOS does not have a font named "Monospace".

So...two work items:
- reasonable default font (or warning to user if missing)
- identify/establish in settings default fixed-width font for MacOS
(scope creep for #3317)

**Comment by scottfurry** [comment]
And to put the cherry on top of this matter...
Building in MacOS with `ALL_WARNINGS` set to `ON`.
Output:
```
"/Users/[me]/DB4S-src/build/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite"
qt.qpa.fonts: Populating font family aliases took 263 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 

```
Adding to discussion #3317 as a TODO

**Comment by justinclift** [comment]
Excellent, sounds like a plan. :smile:
