### ISSUE TITLE
[Feature]: Style option for columns affected by a Display Format

### ISSUE THREAD

**Issue by Ailothaen** [sqlitebrowser/sqlitebrowser#3404]
### Describe the new feature

Hello,

Apologies if this feature should be part of another feature request (especially #2283)

Display Formats in DB Browser for SQLite are really useful, and I personally use them a lot to display date and time instead of an Unix timestamp. However, if I read the documentation [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats), it states that:
> There is no indication in the UI for which columns a format has been set.

This can be confusing if we are opening a database with a lot of different columns, and we do not know which ones are affected by a display format.

My suggestion would be to add an option in `Preferences > Data Browser > Field display`, so that formatted columns could have the opportunity to appear under a different appearance. (See below for screenshots)

### Do you have a screenshot? Please add screenshots to help explain your idea.

Here is how it could look in the configuration panel (the 4th line was added by me)

![formatted](https://github.com/sqlitebrowser/sqlitebrowser/assets/11133116/13e71729-78c0-446b-a140-2d2748bb2a1b)

And then, the formatted text (here the datetime, which was formatted from an UNIX timestamp) would turn green, according to the setting:

![Formatted2](https://github.com/sqlitebrowser/sqlitebrowser/assets/11133116/6dd1592c-f131-431f-8b17-5147aea4bf5c)

**Comment by justinclift** [comment]
That sounds like a decent concept. :smile:

@mgrojo @scottfurry @lucydodo What do you think?

**Comment by scottfurry** [comment]
This reminds me of something I did for another project where a _style preview_ was desirable.

:+1: Yeah, we should have this.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by mgrojo** [comment]
@Ailothaen, I liked your suggestion and I've implemented it. If you could test it in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds), we will be able to close the feature with confidence it's working fine.

**Comment by justinclift** [comment]
Nicely done @mgrojo! :smile:

**Comment by Ailothaen** [comment]
I could test the latest nighly build on a database I had, and it looks to work well indeed (even if I still had to define another color in the settings, I do not know if defining something else than the standard color by default would be a good thing?)

![20230802-191152-002826](https://github.com/sqlitebrowser/sqlitebrowser/assets/11133116/40b482bd-c2a4-47a2-a319-20d762289c9e)

Awesome work. I see the issue was mentioned on [the documentation](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats), the point about "no UI indication" can be removed after a stable version with this feature will be released 🙂

**Comment by mgrojo** [comment]
> I could test the latest nighly build on a database I had, and it looks to work well indeed (even if I still had to define another color in the settings, I do not know if defining something else than the standard color by default would be a good thing?)

I wanted to have a different background, but I didn't want to hardcode a color in the "Follow the desktop style" setting, because it could not match the colors set at the OS level. These are my colors under Ubuntu Linux:

![imagen](https://github.com/sqlitebrowser/sqlitebrowser/assets/13812910/a234aafc-fe98-4ad5-a532-ebfe4aac451f)

It seems [`QPalette::AlternateBase`](https://doc.qt.io/qt-6/qpalette.html#ColorRole-enum) is not working for Windows or for your particular setup. Then the user will have to discover the feature in the preferences. Otherwise, as I said, we could hardcode colors which are ugly to look at along the desktop colors.

**Comment by Ailothaen** [comment]
> It seems [QPalette::AlternateBase](https://doc.qt.io/qt-6/qpalette.html#ColorRole-enum) is not working for Windows or for your particular setup

If you are talking about the slighly darker background: it is actually me who changed it back to white, just to test 😄 It was actually working before I changed everything.

**Comment by mgrojo** [comment]
Perfect, then it's working as expected and ready for the next release.
