### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ClodoaldoPinto** [sqlitebrowser/sqlitebrowser#3409]
Opening the database I get a ```malformed database schema...: syntax error```.
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/1433209/260c1de5-c250-4d47-ae52-0e3390a34828)

I'm using the portable 3.12.2.
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/1433209/55466522-7e62-4515-bb69-4441f992cc4c)

I checked the database integrity in the shell interface:
```
> sqlite3 email.db
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for usage hints.
sqlite> pragma integrity_check;
ok
```
The database works from Python and from Dbeaver

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows 10

**Comment by FriedrichFroebel** [comment]
There have been multiple reports about the new *STRICT* keyword already, see #2926 for the oldest report. This has been fixed, but is only available within the nightly builds for the moment.

**Comment by ClodoaldoPinto** [comment]
The nightly build work https://nightlies.sqlitebrowser.org/latest/
