### ISSUE TITLE
Browse encrypted data

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#341]
From a recently created ticket on the old SourceForge project page:

&nbsp; &nbsp; https://sourceforge.net/p/sqlitebrowser/feature-requests/41/

```
Hello 
please add a feature to show as well ciphertext in .dbs as plaintext.
e.g. the app web browser dooble.sf.net has all data stored encrypted, e.g. the file
shared.db (path in settings), which is filled with an url in case you press the first
button of the url bar. Also the app Spot-on.sf.net creates an url.db which can be filled
with an import from that share.db. It would be great, if the crypto credentials of this
crypto used in the browser and url search tool is implemented over a path to
dooble.ini or spot-on.ini so that the DBs can be shown in plaintext in your browser.
Thanks.
```

**Comment by Z4us** [comment]
Probably it's me being a non-native speaker of English, but what you mean? 

The text before decrypted visible? There is the command 'od`, right?

**Comment by justinclift** [comment]
Yeah, I'm not totally sure.  I was hoping the reporter would jump in here.  Looks like not though... :frowning: 

I'm going to close this, as there's not a lot we can do with it as-is.
