### ISSUE TITLE
[Bug]: Impossible to open TypeORM database using better-sqlite3-multiple-ciphers

### ISSUE THREAD

**Issue by maximelafarie** [sqlitebrowser/sqlitebrowser#3417]
### What did you do?

I'm running an API with TypeORM using better-sqlite3 with encryption (`better-sqlite3-multiple-ciphers`). All works properly while using the API. It can r/w data perfectly into the DB. My current implementation is the following:

```ts
export const AppDataSource = new DataSource({
    type: 'better-sqlite3',
    key: 'the-2048-chars-long-passphrase',
    database: 'database',
    driver: require('better-sqlite3-multiple-ciphers'),
    //...
    prepareDatabase: db => {
        db.pragma(`cipher='sqlcipher'`)
    }
});
```

The passphrase I'm using is 2048 chars long.
As far as I know `sqlcipher` is using `SHA256` for encryption.

So I'm entering the passphrase in the `Password` field with the following params:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/5319267/44956d91-42c2-4ddf-8243-058c482701d8)

I'm afraid it can be an issue with `better-sqlite3-multiple-ciphers`, but I may have misconfigured something..

### What did you expect to see?

I expect the database to be read by the browser.

### What did you see instead?

The browser's encryption params window.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

Ventura 13.4

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Cool.  Thanks for putting that info there too.  It'll be helpful for any future people that hit the same problem. :smile:
