### ISSUE TITLE
Can't not open db file(sqlcipher v2.1) with new sql browser.

### ISSUE THREAD

**Issue by Pkkkkkkkk** [sqlitebrowser/sqlitebrowser#3421]
I got a db file from Android sys,and found it is encrypted with sqlcipher.

It's available by using ”SQLite Database Browser“ to visit it,but i can't open it with new version broswer(DB Browser for SQLCipher.exe).
password is right but new browser show  (pic2)

How to fix this poblem?

![a331a9123d91a9817399ba0c47d8d04](https://github.com/sqlitebrowser/sqlitebrowser/assets/56815236/3b4a5168-5c5d-4b21-9760-6ebb68790325)
![332d3b46a2f10fbf09a0f3d0c922b19](https://github.com/sqlitebrowser/sqlitebrowser/assets/56815236/eb727676-5d92-4900-9582-7de6df9f2896)

**Comment by scottfurry** [comment]
URL is barely visible in email I received advising of bug. However, I'm not seeing the URL in the web version of the report. Please post the URL again, please.

The error `Invalid file format` suggests that the downloaded file is corrupted. I would suggest re-verify the download. If the error persists, we can go from there.

**Comment by chrisjlocke** [comment]
I'm assuming you haven't downloaded DB4S v2.1 ?  
The second screenshot doesn't look like SQLCipher version of DB4S?  Although I may be mistaken.
Just because a database is encrypted, doesn't mean SQLCipher can open it.  The encryption format has to be compatible.  And the password has to be right.  SQLCipher doesn't know what the right password is - it just decrypts using the key you've given it.  Invalid database format means that it isn't the right key.

**Comment by justinclift** [comment]
There is another possibility.  It could be that the database file is indeed using "SQLCipher version 2.1".

Our current versions of DB4S are using SQLCipher 4.x, which has backwards compatibility with SQLCipher 3.x.

For SQLCipher 2.1 compatibility, *maybe* using a much older version of DB4S to open it would work.  That's a guess though. :smile:

**Comment by Pkkkkkkkk** [comment]
> I'm assuming you haven't downloaded DB4S v2.1 ? The second screenshot doesn't look like SQLCipher version of DB4S? Although I may be mistaken. Just because a database is encrypted, doesn't mean SQLCipher can open it. The encryption format has to be compatible. And the password has to be right. SQLCipher doesn't know what the right password is - it just decrypts using the key you've given it. Invalid database format means that it isn't the right key.


There is only DB4S v3.0 or higher version i can find,the pic1‘s DB4S is downloaded from others and it only show sqlcipher version(v2.1).
It's SQLCipher version of DB4S and maybe it's a bug why showing "... for  SQLite".
The password,im sure it' correct,bc i can pass this db with pic1'software.
As to "the encryption format",i think it's the key.
So i wonder could i open a sqlcipher v2.1 file by the latest version DB4S.

**Comment by Pkkkkkkkk** [comment]
> compatible



> There is another possibility. It could be that the database file is indeed using "SQLCipher version 2.1".
> 
> Our current versions of DB4S are using SQLCipher 4.x, which has backwards compatibility with SQLCipher 3.x.
> 
> For SQLCipher 2.1 compatibility, _maybe_ using a much older version of DB4S to open it would work. That's a guess though. 😄

YES i can open it with a much older version of DB4S as shown in pic1,but its ui is difficult to use.
I'm looking for a way to open it with the lastest versison DB4S.

**Comment by Pkkkkkkkk** [comment]
> 

URL?I don't seem to see url sending.
Would it be possible to "Invalid file format" means “compatible proble”.bc db file can be visited in sqlcipherv2.1 DB4S but recent version counld't.

**Comment by scottfurry** [comment]
> > 
> 
> URL?I don't seem to see url sending. Would it be possible to "Invalid file format" means “compatible proble”.bc db file can be visited in sqlcipherv2.1 DB4S but recent version counld't.
![3421_incoming_screenshot](https://github.com/sqlitebrowser/sqlitebrowser/assets/6686571/df559248-1bb3-47a3-a585-fe33444c0129)

@Pkkkkkkkk - Attaching a screen shot of the email I received from Github notification about bug report. I see a screen shot of what you posted originally, but only the image in the email from Github shows the URL text (looks like a download link starting with text "Here's the link..."). The image you posted above doesn't have this information. I suspect there is cropping done by Github.

**Comment by Pkkkkkkkk** [comment]
> > > 
> > 
> > 
> > URL？我好像没有看到url发送。“无效的文件格式”是否可能意味着“兼容问题”。bc db 文件可以在 sqlcipherv2.1 DB4S 中访问，但最近的版本不能访问。
> > ![3421_incoming_screenshot](https://user-images.githubusercontent.com/6686571/257752834-df559248-1bb3-47a3-a585-fe33444c0129.jpg)
> 
> @Pkkkkkkkk- 附上我从 Github 收到的有关错误报告通知的电子邮件的屏幕截图。我看到了您最初发布的内容的屏幕截图，但只有来自 Github 的电子邮件中的图像显示了 URL 文本（看起来像以文本“这是链接...”开头的下载链接）。您上面发布的图片没有此信息。我怀疑 Github 做了裁剪。

oh i see.
maybe is background software's edge,never mind.
The file is complete and pssword is correct i'm sure.
It's just a compatibility issue i guess,sqlcipher 4&3 can't work on version 2?  i guess

thk for replying

**Comment by Pkkkkkkkk** [comment]
> > > 
> > 
> > 
> > URL?I don't seem to see url sending. Would it be possible to "Invalid file format" means “compatible proble”.bc db file can be visited in sqlcipherv2.1 DB4S but recent version counld't.
> > ![3421_incoming_screenshot](https://user-images.githubusercontent.com/6686571/257752834-df559248-1bb3-47a3-a585-fe33444c0129.jpg)
> 
> @Pkkkkkkkk - Attaching a screen shot of the email I received from Github notification about bug report. I see a screen shot of what you posted originally, but only the image in the email from Github shows the URL text (looks like a download link starting with text "Here's the link..."). The image you posted above doesn't have this information. I suspect there is cropping done by Github.

oh i see.
maybe is background software's border,never mind.
The file is complete and pssword is correct i'm sure.
It's just a compatibility issue i guess,sqlcipher 4&3 can't work on version 2? i guess

thk for replying

**Comment by Pkkkkkkkk** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/56815236/1da6a383-f8c3-47bc-9945-34d7fb549f96)
The available but older DB4S for this file,can't find the software version except sqlcipher version.

**Comment by justinclift** [comment]
If you need the encrypted database to still be in "SQLCipher 2.1" format, then you are going to have to keep using the very old DB4S version. :frowning:

For example, if you use the database with some other software that only understands SQLCipher 2.1.

---

Alternatively, if you don't need to use the database with other software, then you could update the SQLCipher version.

1. Decrypt the SQLCipher 2.1 database, so that it becomes a standard SQLite database.  No longer encrypted.
2. Using modern DB4S, you can encrypt a SQLite database to SQLCipher 4.x.

That might not work with other, older applications though.

**Comment by Pkkkkkkkk** [comment]
> 

GOT IT.👌
