### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by getify** [sqlitebrowser/sqlitebrowser#3426]
Seems like this project hasn't officially released a new version since v3.12.2 in May 2021 (over 2 years ago). Yet, a lot has happened on the repo and with SQLite3 in that time.

I was surprised to find out that even math functions (added to SQLite3 back in March 2021, 17 months ago) haven't landed in a release yet.

I know there are nightlies, but as I generally use this software for more "production" purposes, I don't want to switch to that channel.

I'm curious if there's a roadmap tracking issue for the next release? 3.12.3? 3.13? 4? What is the estimate on when the next official release might be ready?

**Comment by chrisjlocke** [comment]
Currently, the nightly is as 'good as' the next release.  Apart from an open issue with projects, there isn't any 'in testing' code that's there just for testing purposes.  We're in the middle of testing some settings refactoring, but that code hasn't been pushed to the nightly code yet.
We were due to release a new version a month or so ago, but 'things happened' which meant that wasn't possible.  We're just waiting for another suitable slot.

**Comment by scottfurry** [comment]
So punt out `triskaidekaphobia` verision, aka 3.13, and then aim for the π version for next pi day. Or just say to hell with it and go straight to 4.0.

**Comment by justinclift** [comment]
If someone wants to make it happen, then go for it (please!). :smile:

I'm personally just very short on spare time at the moment, so I'll only be able to help out in minimal ways.  But there's nothing that I'm the critical component for... hopefully? :smile:

**Comment by scottfurry** [comment]
> ... But there's nothing that I'm the critical component for... hopefully?

Famous last words...

[Action Item Man](https://professionalsuperhero.com/)
Remember, kids, don't be the bottle neck.

**Comment by mgrojo** [comment]
I'd also like to do a new release, but I generally lack personal time to do it. Maybe in September, but I cannot promise anything...

**Comment by chrisjlocke** [comment]
Closing as the next release is in progress.  Hey @chrisjlocke .. maybe someone should mention that on Twitter, hey?
