### ISSUE TITLE
3.6.0 - Problem with browse data

### ISSUE THREAD

**Issue by eva5618** [sqlitebrowser/sqlitebrowser#343]
Hi,

I just downloaded and opened version 3.6.0, and there seems to be an issue with the Browse Data feature. When I open my database and browse data, sqlitebrowser shows all of my BLOB columns as being occupied with BLOB, when in fact only a subset of them are (as revealed by browsing with version 3.5.1, and my work with this database). I'm running Mac OSX Yosemite (10.10.3). Please let me know if you need any more information.

eva5618

**Comment by justinclift** [comment]
Thanks Eva.  Would you be ok to try our latest nightly build?  We've done some stuff with BLOB handing in the last few weeks, and there's a chance this has changed.  Would be good to know if it's something we still need to investigate or not. :smile:

(the download locations for our latest nightly builds are on the front page of this repo, if that helps)

**Comment by eva5618** [comment]
Just checked today's build (*20150607.dmg), and the problem is fixed! Thanks, and keep up the good work.

**Comment by justinclift** [comment]
Awesome. :grin:
