### ISSUE TITLE
[Bug]: Hidden Columns

### ISSUE THREAD

**Issue by pete165** [sqlitebrowser/sqlitebrowser#3438]
### What did you do?

Hidden columns do not stay hidden. 

### What did you expect to see?

Hidden columns should stay hidden until user makes visible again.

### What did you see instead?

Hidden columns return to visible if, for example, you then change the sort order of another column.    I had an old build (from several years ago) in which the columns did remain hidden, but I don't know what version that was and I've wiped that hard drive.   I found two other reports of this issue but didn't see a final resolution: 
https://github.com/sqlitebrowser/sqlitebrowser/issues/2718
https://github.com/sqlitebrowser/sqlitebrowser/issues/1026

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Interesting.  If you try the latest nightly build instead, is it still happening for you in that?

https://nightlies.sqlitebrowser.org/latest/

**Comment by kit-finknottle** [comment]
I downloaded and installed today and this is happening for me (MacOS, Intel chip):

- DB Browser for SQLite Version 3.12.2
- Built for x86_64-little_endian-lp64, running on x86_64
- Qt Version 5.15.2
- SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).

As soon as I changed the sort order, my hidden columns get unhidden.

**Comment by justinclift** [comment]
@kit-finknottle Try the nightly build for Intel MacOS instead.  We've recently been doing stuff with hidden columns, so there's a decent chance it'll work. :smile:

https://nightlies.sqlitebrowser.org/latest/

**Comment by mgrojo** [comment]
As #2718  says, the fix is not in the released version, only in the master branch (nightly builds). This is duplicated with it and can be closed.

**Comment by kit-finknottle** [comment]
Cool, thanks for the tip.  It is working properly in the latest nightly build:

```
DB Browser for SQLite Version 3.12.99 (Sep  8 2023)
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.2
SQLite Version 3.42.0.
```
