### ISSUE TITLE
MSVCR120.dll Depenedency

### ISSUE THREAD

**Issue by jcsayre** [sqlitebrowser/sqlitebrowser#344]
On Windows 7 Home Premium SP1 (6.1.7601), the dialog message box, "sqlitebrowser.exe - System Error" is displayed with the following message: "The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem."

![image](https://cloud.githubusercontent.com/assets/11142503/8035400/592462ea-0dbe-11e5-88c9-195007246cf3.png)

I uninstalled and resinstalled sqlitebrowser.exe, but that did not work.

I then installed the Visual C++Redistributable Packages for Visual Studio 2013 from: http://www.microsoft.com/en-us/download/confirmation.aspx?id=40784 and installed for 64bit OS. The application then launched successfully.

I'm not a developer, but I suspect that this DLL from MSFT should either be included with your installation or a prerequisite. Hope this helps.

**Comment by justinclift** [comment]
Thanks for the bug report. :smile:

We switched to a new build process for the Windows executables with the 3.6.x release, and we're still working out the kinks. :innocent:

The next release (3.7.0, soon) should automatically install that dependency.  Hopefully that works out in practise for everyone, but we'll see... :smile:
