### ISSUE TITLE
[Bug]: Execute SQL: bad highlighting and completion for table/field names containing accented characters

### ISSUE THREAD

**Issue by onurb-taktile** [sqlitebrowser/sqlitebrowser#3440]
### What did you do?

I use accented letters a lot in my database.

Here is a sample database schema to use for testing
`CREATE TABLE IF NOT EXISTS "Activité" (
	"id"	INTEGER,
	"début"	TEXT,
	"fin"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Éléphant" (
	"id"	INTEGER,
	"taille"	INTEGER
);
`

_I'm using home built nightly without sqlcipher, but I had the same issue with the stable version_

### What did you expect to see?

When typing a statement in Execute SQL, if I type `Élé`, I expect to see `Éléphant` as a completion choice proposed.

When I type the full table or field name, I expect to see it fully highlighted as a table/field name

### What did you see instead?

- The completion box doesn't pop if there is an accented character in the first 3 typed. If the first accented is located further within the name, the name is proposed properly.

- The highlighting is weird, excluding the accented chars which are displayed as default text (if I double quote the name, the highlighting is correct) - looks like a non unicode regex to me :D
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/11510335/1bc8bb0f-0548-401c-9bf9-17255f76432a)

https://github.com/sqlitebrowser/sqlitebrowser/assets/11510335/ba6f70f6-aa83-4294-9b94-95fa4aea18d9

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Linux Mint 20.3

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by onurb-taktile** [comment]
I've just noticed an issue within sqlite regarding accents in table names : whereas table names are case insensitive, when an accented character is present, it must use the same case as in the definition : if a table is created as Profile, it can be addressed as Profile, profile, pRoFiLe and so on. If a table is created as Activités, it can be addressed as Activités, activités, aCtIvItéS but not ACTIVIT**É**S. Something to do with uppercasing of unicode chars which is kindof tricky I suppose :)
Maybe a relation with the bugs I noticed in completion and highlighting?

**Comment by chrisjlocke** [comment]
This is a feature with SQLite, not DB4S.

SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE.

**Comment by chrisjlocke** [comment]
Closing as I don't believe this is fully an issue with DB4S.
Have added it as an enhancement, but due to the large number of outstanding issues, I don't believe this would get resolved in the short term.
