### ISSUE TITLE
[Bug]: Default Column Option inappropriately wrapped in quotes

### ISSUE THREAD

**Issue by hugeblank** [sqlitebrowser/sqlitebrowser#3446]
### What did you do?

I was in the process of creating a table which had a column whose default value was meant to be the unix epoch time (an integer). Into the default value, I input `(unixepoch('subsec'))`.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/16393543/02f221ba-b323-4758-86ee-b763b1de2fc7)

### What did you expect to see?

I would expect to see that this would be accepted into the input without any automatic replacements of quotes. See [this](https://www.sqlite.org/syntaxdiagrams.html#column-constraint).

### What did you see instead?

My input gets awkwardly wrapped, and when attempting to insert a row into this table, the literal text is put into the cell:
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/16393543/42a2764c-e4fc-4c79-9c2a-990d48214d05)
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/16393543/2d75403e-adc2-4967-a541-4e4ed752462c)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Archlinux 6.4.10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by scottfurry** [comment]
The `unixepoch()` function, described in sqlite docs [here](https://www.sqlite.org/lang_datefunc.html), is external code. This function was added to sqlite in late 2021 (see [commit](https://www.sqlite.org/src/info/559fdc0aa76f4c20).

From context, it appears that the table definition being established is meant to trigger execution of the sqlite call to populate.

Reporting appears to suggest that DB4S lexer is not taking a function call into account for table definition. Parentheses are being treated as quoted characters.

Confirmation that such a table definition, population with function call, is possible from the command-line. My previous SQL experience is that such actions are usually in the scope of triggers or procedures.

**Comment by hugeblank** [comment]
> My previous SQL experience is that such actions are usually in the scope of triggers or procedures.

My previous SQL experience is *slightly* better than nothing, which is why I presume nobody else has ran into this issue. I'll look into this in the mean time. Thanks! :D

**Comment by scottfurry** [comment]
For my own benefit and knowledge, I attempted to create a similar table with the `unixepoch()` call. SQLite reported an error.
```
sqlite> CREATE TABLE "VIDEOS" (
(x1...> "ID" INTEGER NOT NULL UNIQUE,
(x1...> "VKEY" TEXT NOT NULL UNIQUE,
(x1...> "EPOCH" INTEGER NOT NULL DEFAULT (unixepoch(subsec))
(x1...> PRIMARY KEY("ID" AUTOINCREMENT)
(x1...> );
Parse error: default value of column [EPOCH] is not constant
```

**Comment by chrisjlocke** [comment]
Use strftime:
```
sqlite> select strftime('%s', 'now');
1342685993
```
Use it in CREATE TABLE like this:
```
sqlite> create table t1 (
   ...> id integer primary key,
   ...> time timestamp default (strftime('%s', 'now')),
   ...> txt text);
sqlite> insert into t1 (txt) values ('foo');
sqlite> insert into t1 (txt) values ('bar');
sqlite> insert into t1 (txt) values ('baz');
sqlite> select * from t1;
1|1342686319|foo
2|1342686321|bar
3|1342686323|baz
```
See https://www.sqlite.org/lang_createtable.html#tablecoldef

    If the default value of a column is an expression in parentheses, then the expression is evaluated once for each row inserted 
    and the results used in the new row.


If DB4S adds quotes, you can select the create statement, paste it in a SQL tab, and edit it as needed.

**Comment by hugeblank** [comment]
> For my own benefit and knowledge, I attempted to create a similar table with the `unixepoch()` call. SQLite reported an error.

In the end I found and settled on using `DEFAULT_TIMESTAMP`, but it's interesting that my original idea wouldn't have worked.

> Use strftime

Before reporting I did test it with strftime, and it still wrapped in quotes. 

> If DB4S adds quotes, you can select the create statement, paste it in a SQL tab, and edit it as needed.

This works, but it's always nice to have the UI properly reflect what's capable!

**Comment by chrisjlocke** [comment]
Its a bug, and hopefully a quick one that could be addressed.  Rather than add tons of logic into the program deciding if its a function or not or whether to add quotes, just make it literal, so if quotes are needed, the user adds them.

**Comment by mgrojo** [comment]
Our code has always interpreted values starting by `=` as literal. This is how this has to be done for 3.12.2.

For the next release, I've added the same logic to user input as was done in the dialog population from SQLite; if it is surrounded by parentheses, the `=` is added to the GUI cell and no quotes are added. Otherwise, quotes are added as before. So users only have to add quotes themselves if their strings start by `=` or look like an `(expression) `. I don't dare to change the logic, as it would break the work flow of people used to the current logic.

@hugeblank you can try this in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds).

**Comment by chrisjlocke** [comment]
Closing as resolved.
Thanks @mgrojo for implementing the fix.
