### ISSUE TITLE
[Feature]: Add more keyboard "Alt" hints

### ISSUE THREAD

**Issue by brainwo** [sqlitebrowser/sqlitebrowser#3450]
### Describe the new feature

More keyboard hints when holding Alt key.
Currently there are only hints for toolbar. It would be nicer if buttons like "New Database" "Open Database" and tabs like "Database Structure" "Browse Data" have a quick keyboard hint.
So holding "Alt" and pressing "O" for <ins>O</ins>pen Database will open the open database dialog.

### Does this feature exist in another product or project? Please provide a link

Yes, in [FileZilla](https://filezilla-project.org/sourcecode.php)

### Do you have a screenshot? Please add screenshots to help explain your idea.

From Sqlitebrowser:
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/45139213/68f258f7-79d5-4877-94c7-33b80baee3ff)

From FileZilla:
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/45139213/8407dde6-26e2-4976-95fc-b78b6dd02745)

**Comment by scottfurry** [comment]
I can see where you're coming from as a fellow keyboard-warrior.

I should note that filezilla is probably not the best example. It is based on wxWidgets, which is an entirely different GUI widget library. DB4S is based on Qt.

I suspect that there is some tweak to the UI we have to make to coerce Qt to present the available options with the [Alt] key. I think it's possible. I've seen it done in other places. This may be a back-burner issue for us for the moment.

**Comment by brainwo** [comment]
You are right. Here's another example: (Kdenlive)

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/45139213/adb915be-c48f-4756-bbbb-71b47014716e)

**Comment by brainwo** [comment]
LGTM

---

Also I just found <ins>T</ins>able in "Browse Data" is highlighted although T is already assigned for <ins>T</ins>ools making it doesn't do anything but open the Tools menu instead. Normally, this shortcut should move the focus to the dropdown so you can use Up/Down keys to move between tables.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/45139213/51d58781-dad1-4b1c-8247-8433dee177bd)

**Comment by mgrojo** [comment]
Yes, I noticed that too. That is good example of the problem with this kind of accelerators that I mentioned. In any case, this works for me. If the Browse Data tab is focused, Alt+T focuses the Table combo; a second Alt+T opens the Tools menu. If the Browse Data is not visible, Alt+T opens directly the menu.

Nevertheless, maybe it's better to change one of the two. What do you think?

**Comment by brainwo** [comment]
I agreed to make it so the letters are not repeating

**Comment by mgrojo** [comment]
The accelerator for the Table combo was explicitly added for #908. Later I added the accelerator for Tools without realizing the repetition. I'll change the letter for this latter addition to O.
