### ISSUE TITLE
Future release 3.13 is ready for translation!

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#3452]
We are in the process of releasing our next stable version (3.13.0) with many [corrections and enhancements](https://github.com/sqlitebrowser/sqlitebrowser/milestone/18?closed=1).

This is your opportunity to make DB4S better by translating it to your language or updating the translation for this release (when available).

# Available nightly builds

You can install one of the [nightly builds](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) for your platform to see strings in context.

# Instructions

The `*.ts` files are already updated on the [`master`](https://github.com/sqlitebrowser/sqlitebrowser/tree/master) branch, and we don't plan to modify the strings unless needed to include some correction.

You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) about how to do it. Team members will assist you in the process, in case you had any doubt.

# Notifications 
I'll ping here all the translators who have helped us in the past, so they get a notification. Please, report back if you want to help again. When there are more than one volunteer, they can share out the work and/or review each other translations. Try to coordinate each other, otherwise you could do redundant work.

lang | complete | untranslated texts | translators
-- | -- | -- | --
ar_SA | | 191 |@safaalfulaij
cs | | 790 |@MrMarmelade  
de | | 249 |@FriedrichFroebel
en_GB | | 1123 |@glawrence 
es_ES | | 191 |@lulol, @mgrojo
fa | | | @khashayarxy
fr | | 192 | @mvt91
id | | 138 |@atriwidada 
it | | 264 | @Feyn-Man, @GortiZ6 
ja | | 208 |@hrwatahiki 
ko_KR | | 22 |@lucydodo, @neozest, @progh2
nl | | 138 |@Codifier 
pl | | 140 |@bartlomiej-przymus, @wojnilowicz 
pt_BR | | 257 | @bernardosulzbach
ru | | 507 |@schdub, @zvova7890, @VanDerSam 
sv | | 1076 |Jan-Erik (via @TeLLie)
tr | | 265 |@firateski 
uk_UA | | 857 |@keedhost 
zh | | 145 |@bssthu, @mercury233, @yfdyh000
zh_TW | | 138 |@PeterDaveHello 
other | | | Your name here!

Thanks and happy translation!

# Source string changes after translation started

* Two typos in the original English, not yet merged to avoid conflicts: #3454 #3456. Don't worry about them, this can be fixed later for all translation files.

# Due date
We don't have a planned date yet, but most probably by the end of September.

**Comment by lucydodo** [comment]
Cool, I'll try to have it done by next week at the latest. :)

**Comment by atriwidada** [comment]
will try to do this weekend

**Comment by GortiZ6** [comment]
Done, I added a pull request #3453

**Comment by lulol** [comment]
@mgrojo If you didn't start the Spanish translation, would you prefer that I translate all pending lines so that you can later review them and make any needed changes or we can split them in half and review each other's work?

**Comment by mgrojo** [comment]
> @mgrojo If you didn't start the Spanish translation, would you prefer that I translate all pending lines so that you can later review them and make any needed changes or we can split them in half and review each other's work?

I haven't started, and I'm happy with any of those options. If you don't really have a preference, let's split the file and then we review each other's work. Around line 4000 is the half, but I don't know if the share of pending translations is fair, but more or less so.

**Comment by lulol** [comment]
@mgrojo Ok. There are 197 unfinished lines and the half point is at:
https://github.com/sqlitebrowser/sqlitebrowser/blob/4948e160d33243bee87fd98a0f7dbcb74b0a0742/src/translations/sqlb_es_ES.ts#L3151-L3152

I can start from that line down.

**Comment by mgrojo** [comment]
Hint for translation: try to not repeat the global key accelerators, that is, underscored letters in main menubar, main toolbar and main tabs, otherwise they cannot be used or require a second key press. If there are no more available letters, you might choose to sacrifice the actions that already have keyboard shortcuts with Ctrl like Open Database or New Database. The change comes from #3450.

**Comment by mvt91** [comment]
Hi Manuel

Is there someone who works on the French translation ?

Thanks
Michel

----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Fri, 08 Sep 2023 18:08:45 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

Hint for translation: try to not repeat the global key accelerators, that is, underscored letters in main menubar, main toolbar and main tabs, otherwise they cannot be used or require a second key press. If there are no more available letters, you might choose to sacrifice the actions that already have keyboard shortcuts with Ctrl like Open Database or New Database. The change comes from #3450.

**Comment by hrwatahiki** [comment]
I've started translate this to ja.

**Comment by mgrojo** [comment]
> Is there someone who works on the French translation ?

Hi Michel,

No, nobody is working on the French translation yet, as far as I know.

**Comment by wojnilowicz** [comment]
In the future please ping once. Now I get a lot of spam unless I unsubscribe from this thread, which I haven't subscribed in the first place.

**Comment by mgrojo** [comment]
> In the future please ping once. Now I get a lot of spam unless I unsubscribe from this thread, which I haven't subscribed in the first place.

Sorry about that. Yes, you can always unsubscribe, that's the way to opt out. For the future, we will think how to do it in another way. Maybe an announcement in Discussions and then an issue for the actual work only for the contributing people.

**Comment by mvt91** [comment]
Thanks Manuel

What's the dead line ?

----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Fri, 08 Sep 2023 20:56:25 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

> Is there someone who works on the French translation ?

Hi Michel,

No, nobody is working on the French translation yet, as far as I know.

**Comment by mgrojo** [comment]
> What's the dead line ?

Let's say end of September. We are not in a hurry, although the pull requests are coming quicker than I expected.

**Comment by mvt91** [comment]
Ok. I'll try to do something, 'cause I did the previous ones !
----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Sat, 09 Sep 2023 00:44:24 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

> What's the dead line ?

Let's say end of September. We are not in a hurry, although the pull requests are coming quicker than I expected.

**Comment by bernardosulzbach** [comment]
I'm no longer interested in helping with localization. Nowadays, I have too little free time that I have to allocate across too many different projects, and I'm afraid I don't enjoy translating enough to justify doing it.

I hope you and other DB Browser for SQLite contributors and users will understand. A huge number of people speak both Portuguese and English, so hopefully someone will be able to carry on from where I stopped.

**Comment by FriedrichFroebel** [comment]
Some general stuff I stumbled upon which could be improved:

* Split the main HTML of the About Dialog with multiple strings to simplify translation. This might apply to the other HTML stuff as well where the string itself is not formatted as well.
* https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L143 misses a whitespace before the brace.
* https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L4404 is reported as missing the placeholder `%n/%Ln` in the translation.
* https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L6912 misses the first character of the last sentence.

**Comment by mgrojo** [comment]
@bernardosulzbach, that is understandable. Let's hope someone else volunteers to continue the Portuguese translation.

@FriedrichFroebel 
> Some general stuff I stumbled upon which could be improved:
> 
>     * Split the main HTML of the About Dialog with multiple strings to simplify translation. This might apply to the other HTML stuff as well where the string itself is not formatted as well.

Yes, you're right. I suppose it's late now. We should take into account for future versions.

> 
>     * https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L143
>        misses a whitespace before the brace.

Yes, I can fix the source and the translations later. It's better if the translations already come with appropriate punctuation.

> 
>     * https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L4404
>        is reported as missing the placeholder `%n/%Ln` in the translation.

I'll take a look. I don't know if it can be done without referencing the `%n/%Ln`, which wasn't foreseen in this case. Otherwise, it is too late too.

@lulol and me are also discussing another very special case, which is:

```xml
        <location filename="../EditDialog.cpp" line="1091"/>
        <source>Type: %1 Image; Size: %2x%3 pixel(s)</source>
```
Given that in this case the 1 case is very unusual, and in fact, n would be the result of a multiplication. Do you think it makes sense to transform it into a plural-supported way? `n` should be %2 * %3, and will not appear in the string (I don't know if that's even possible with Qt).
> 
>     * https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L6912
>        misses the first character of the last sentence.

Ok, it has already been reported.

There are two typos in the original English, not yet merged to avoid conflicts: #3454 and #3456. Don't worry about them, this can be fixed later for all translation files.

**Comment by mgrojo** [comment]
> https://github.com/sqlitebrowser/sqlitebrowser/blob/5f494ea65370aab3a239c125410fb66a08f41879/src/translations/sqlb_de.ts#L4404
>  is reported as missing the placeholder `%n/%Ln` in the translation.

I've checked that it is working with the Spanish translation. In that case, what I did was, not only changed the plural form for "file" but also remove the note.

So the placeholder `%n/%Ln` is not actually needed, and the report can be ignored. It's true that I could have written "Select the action to apply to the %n dropped file(s).", it would give information that it might be useful for the user in some cases. But in any case, the numerusform for 1 would not have %n, and that shouldn't be a problem either.

In any case, should I add the %n even at risk of breaking the current translations? Or we can leave it as is?

**Comment by FriedrichFroebel** [comment]
> In any case, should I add the %n even at risk of breaking the current translations? Or we can leave it as is?

We might want to at least add a general translator notice there like we already use for some strings.

> Given that in this case the 1 case is very unusual, and in fact, n would be the result of a multiplication. Do you think it makes sense to transform it into a plural-supported way? n should be %2 * %3, and will not appear in the string (I don't know if that's even possible with Qt).

This actually does not matter for German, as both singular and plural are the same word in this case, so I do not have any clear opinion on this. But leaving it with the braces should at least not hurt from my point of view.

**Comment by mgrojo** [comment]
> > In any case, should I add the %n even at risk of breaking the current translations? Or we can leave it as is?
> 
> We might want to at least add a general translator notice there like we already use for some strings.

Ok. Added notice in the branch where I'm fixing things affecting translations to avoid conflicts (#3456). Example:

```diff
+    <message numerus="yes">
+        <location filename="../MainWindow.cpp" line="1849"/>
+        <source>Select the action to apply to the dropped file(s). &lt;br/&gt;Note: only &apos;Import&apos; will process more than one file.</source>
+        <comment>Note for translation: Although there is no %n in the original, you can use the numerus-form to adjust &apos;files(s)&apos; and remove the note when n = 1. Including %n in the translation will also work.</comment>
+        <translation>
+            <numerusform>Seleccione la acción a aplicar al archivo.</numerusform>
+            <numerusform>Seleccione la acción a aplicar a los %n archivos soltados.&lt;br/&gt;Nota: sólo «Importar» procesará más de un archivo.</numerusform>
+        </translation>
+    </message>
```

> 
> > Given that in this case the 1 case is very unusual, and in fact, n would be the result of a multiplication. Do you think it makes sense to transform it into a plural-supported way? n should be %2 * %3, and will not appear in the string (I don't know if that's even possible with Qt).
> 
> This actually does not matter for German, as both singular and plural are the same word in this case, so I do not have any clear opinion on this. But leaving it with the braces should at least not hurt from my point of view.

Ok. Nothing changed for the moment.

**Comment by mgrojo** [comment]
Anyone working on a translation who wants to include it in v3.13? @mvt91?

**Comment by mvt91** [comment]
Hi Manuel,

I'm sorry, I didn't have time to do it.
As you know, when you're retired, your planning is growing up !
Have you an idea of the work to do ?
If I remember, the dead line was the end of September ?

Best regards

----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Wed, 11 Oct 2023 20:44:49 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

Anyone working on a translation who wants to include it in v3.13? @mvt91?

**Comment by mgrojo** [comment]
> Hi Manuel, I'm sorry, I didn't have time to do it. As you know, when you're retired, your planning is growing up ! Have you an idea of the work to do ? If I remember, the dead line was the end of September ? Best regards

There are 192 messages to be translated.  The original deadline was end of September, but it was tentative, we can wait if you plan to do it. If you need help, let's ping people who have contributed typo corrections for French in the past, maybe they want to share with you the effort: @vlakoff, @hydrargyrum, @vuod.

**Comment by mvt91** [comment]
Thanks
What's the new deadline ?

I'll have a look during this week-end to evaluate the work to do.
I've to retrieve my tools :)

----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Wed, 11 Oct 2023 21:33:14 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

> Hi Manuel, I'm sorry, I didn't have time to do it. As you know, when you're retired, your planning is growing up ! Have you an idea of the work to do ? If I remember, the dead line was the end of September ? Best regards

There are 192 messages to be translated.  The original deadline was end of September, but it was tentative, we can wait if you plan to do it. If you need help, let's ping people who have contributed typo corrections for French in the past, maybe they want to share with you the effort: @vlakoff, @hydrargyrum, @vuod.

**Comment by mvt91** [comment]
Hi Manuel,

Here is the file translated.
I've some errors : Translation does not contain the necessary %n/%Ln place marker.
I don't undertand what was the problem.

As usual, I don't know how to post the file on Github.
I hope it's the right file...
Friendly


----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Wed, 11 Oct 2023 21:33:14 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

> Hi Manuel, I'm sorry, I didn't have time to do it. As you know, when you're retired, your planning is growing up ! Have you an idea of the work to do ? If I remember, the dead line was the end of September ? Best regards

There are 192 messages to be translated.  The original deadline was end of September, but it was tentative, we can wait if you plan to do it. If you need help, let's ping people who have contributed typo corrections for French in the past, maybe they want to share with you the effort: @vlakoff, @hydrargyrum, @vuod.

**Comment by justinclift** [comment]
@mvt91 GitHub doesn't attach files from email, so you'll probably need to attach it via the GitHub web interface. :wink:

**Comment by mvt91** [comment]
Hi Justin,

I'll try it.
I'm always a dumb :)
----- Mail d'origine -----
De: Justin Clift ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Sat, 14 Oct 2023 04:11:29 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

@mvt91 GitHub doesn't attach files from email, so you'll probably need to attach it via the GitHub web interface. :wink:

**Comment by mvt91** [comment]
The file (need to rename it and remove the .txt suffix)
[sqlb_fr 3.12.3.MVT.ts.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/12901742/sqlb_fr.3.12.3.MVT.ts.txt)

Done :)

**Comment by lucydodo** [comment]
Hi @mvt91 Thanks for contribution. :)
> I've some errors : Translation does not contain the necessary %n/%Ln place marker.

I've checked these warning in some translations of MainWindow context, and I'm guessing it's a bug on Qt Linguist's end. Other similar translations are showing the same warning. Probably because we're uisng `<br>` for newline instead of `\n`.

When I make a commit, would you mind giving me your email address so I can commit as a co-author? If you don't feel comfortable giving out your email in a public place, you can contact me at my email: `seongtaejg at gmail dot com`
Of course, this is optional, and if you don't want to leave commit as a co-author, just let me know :)

**Comment by mgrojo** [comment]
> Hi Manuel, Here is the file translated. I've some errors : Translation does not contain the necessary %n/%Ln place marker. I don't undertand what was the problem. 

The warnings are because the [plural forms](https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals) have not been used. These plural forms are not mandatory (in fact, the original English texts don't have this possibility), but they are nice to have.

Using Linguist, it can be fixed in this way (supposing that the French grammar is correct):
![imagen](https://github.com/sqlitebrowser/sqlitebrowser/assets/13812910/cb531d55-73f9-4d20-bdbf-7ca0e5dfefef)

In the raw TS file:
```xml
    <message numerus="yes">
        <location filename="../EditDialog.cpp" line="927"/>
        <location filename="../EditDialog.cpp" line="1117"/>
        <source>Type: Text / Numeric; Size: %n character(s)</source>
        <translation>
            <numerusform>Type : Texte / Numérique ; Taille : %n caractère</numerusform>
            <numerusform>Type : Texte / Numérique ; Taille : %n caractères</numerusform>
        </translation>
    </message>
```

It's similar to what was mentioned here: https://github.com/sqlitebrowser/sqlitebrowser/issues/3452#issuecomment-1712535828

**Comment by lucydodo** [comment]
Hi @mgrojo Thanks for the great information. :)
Here's the translation with the warning I mentioned above, I wonder if this is a bug on Qt's side?
Or is there something else I'm not aware of?

![Screenshot 2023-10-14 at 21 58 47](https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/d7e42474-1e6f-4d61-818f-01dcc8ecf764)

**Comment by mvt91** [comment]
Hi Manuel,

Thanks for this explanation.
I'll check it next time :)

----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Sat, 14 Oct 2023 13:53:47 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Future release 3.13 is ready for translation! (Issue #3452)

> Hi Manuel, Here is the file translated. I've some errors : Translation does not contain the necessary %n/%Ln place marker. I don't undertand what was the problem. 

The warnings are because the [plural forms](https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals) have not been used. These plural forms are not mandatory (in fact, the original English texts don't have this possibility), but they are nice to have.

Using Linguist, it can be fixed in this way (supposing that the French grammar is correct):
![imagen](https://github.com/sqlitebrowser/sqlitebrowser/assets/13812910/cb531d55-73f9-4d20-bdbf-7ca0e5dfefef)

In the raw TS file:
```xml
    <message numerus="yes">
        <location filename="../EditDialog.cpp" line="927"/>
        <location filename="../EditDialog.cpp" line="1117"/>
        <source>Type: Text / Numeric; Size: %n character(s)</source>
        <translation>
            <numerusform>Type : Texte / Numérique ; Taille : %n caractère</numerusform>
            <numerusform>Type : Texte / Numérique ; Taille : %n caractères</numerusform>
        </translation>
    </message>
```

It's similar to what was mentioned here: https://github.com/sqlitebrowser/sqlitebrowser/issues/3452#issuecomment-1712535828

**Comment by mgrojo** [comment]
Hi @lucydodo. OK, that's a particular case and it's the trickiest. The question is that, in the source code, we have a message that includes the `n` parameter in the call, which is used to control the plural form to be used. Usually, this original message includes the `%n` in the message itself, so the involved number is present. In this case, we don't have the `%n` text, so Qt should complain when extracting the message, or never, but not when the translations are done, because they're following the path set by the original.

If you really want to silence that warning, you have this option (using English to English, so we all understand):
![imagen](https://github.com/sqlitebrowser/sqlitebrowser/assets/13812910/e4b6990d-c248-4878-9134-f6bb59699875)

After the release, we might think in adding `%n` in the source message.

See also this: https://github.com/sqlitebrowser/sqlitebrowser/pull/3456/commits/ff9981f068879ee3b995e693a7fb9734dc486170

**Comment by mvt91** [comment]
Hi Manuel,

I've corrected the 2 or 3 sentences in which the plural can be invoked.
There are still 2 "warning" errors about an end-of-sentence character that he doesn't like; I've looked in the file, but the format seems to comply. I don't think it's too important (main window).
The new file (sqlb_en 3.12.3.MVT-2.ts.txt) is attached.
Thanks
[sqlb_fr 3.12.3.MVT-2.ts.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/12906845/sqlb_fr.3.12.3.MVT-2.ts.txt)

**Comment by lucydodo** [comment]
@mgrojo Thank you very much. It was a great help to me. :)

**Comment by mgrojo** [comment]
@mvt91 Thanks! I've just committed it.

@lucydodo, by the way, you can always do this to attribute something to a GitHub user, even if you only know their user-id.

    git commit --author="mvt91 <mvt91@users.noreply.github.com>" -m "French translation by mvt91 #3452"

That e-mail is the one used by GitHub when a user configures the e-mail as private. GitHub recognizes it and attribute the work to the user.

Note: Later, when pushing this, I reused a command in my history for another repo, and I inadvertently run `git push --all`. Now I'm cleaning the mess; I pushed all the local branches that I've accumulated over the years in my local repository. :smile:

**Comment by lucydodo** [comment]
I didn't know that. Thanks for letting me know. 😄

**Comment by lucydodo** [comment]
As this release was delayed due to Windows code-signing issues, there were two additional new features incldued,
so there's a bit of a bump in untranslated items. (7db4db4, cf44288)

We apologize for making your work twice, and we look forward to your contributions if you have the time. 🙏🏻 
If all goes well, we'll lock the `v3.13.x` branch and release a new stable version next week. 🚀 

Thank you.

**Comment by GortiZ6** [comment]
This was a big one... anyway I submitted a pull request: #3656

**Comment by FriedrichFroebel** [comment]
It seems like there were additional changes on how the translation files were generated. Considering the relevant changes to be about auto-loading extensions and the last database only, 339 strings to check appears quite much. Are we sure that we want to start translating the *qscintilla* strings as well?

**Comment by mgrojo** [comment]
Yes, it seems we have added the QScintilla strings, but we are not displaying those strings, so it doesn't make sense to do it. I'll do it now as it was when we started this translation cycle, so only the two new strings appear as pending. We had a discussion about this time ago: https://github.com/sqlitebrowser/sqlitebrowser/discussions/3451

**Comment by mgrojo** [comment]
There are in fact 7 new or modified strings to translate. Not so many as with the included QScintilla, but some more than only two, as I thought. In any case, I encourage everyone to update their translations, so the next release can be complete. It's just a bit of an effort.

**Comment by lucydodo** [comment]
@FriedrichFroebel Yes, while updating the translation files, I realized that it was possible to translate for QScintilla as well, so I thought it might be helpful for uses, so I included it for now.

>but we are not displaying those strings

However, based on @mgrojo's comment, it looks like this is a string that is not output in the app,
Am I understanding this correctly?

**Comment by lucydodo** [comment]
We're about to finalize this translation work. Are any of you still working on it or need more time? 🤔

**Comment by lucydodo** [comment]
The final binaries for the new 3.13.0 version have been generated.
We appreciate your contributions, and the final release is scheduled for the 23rd UTC.

**Comment by justinclift** [comment]
Awesome!  We'll need to add them to the download server, update the downloader code to serve them, and probably update the download stats database to know about the new release.

**Comment by lucydodo** [comment]
As mentioned above, I've created a new wiki page to reference when making requests to these contributors. If you'd like to continue contributing translations to our project, please see the following discussion and add your GitHub username to the list: https://github.com/sqlitebrowser/sqlitebrowser/discussions/3736 Thank you. :)
