### ISSUE TITLE
Feature Request/Enhancement: Execute from Command Line With Multiple Parameters

### ISSUE THREAD

**Issue by DaltonST** [sqlitebrowser/sqlitebrowser#346]
Since sqlitebrowser is oriented towards end-users, it would be optimal if it could be executed from the command line to open a specific database, switch to a specific tab (e.g. Browse Data), open a specific table, and (if feasible) do so either "read-only" or "editing enabled".  

Example: 

"C:\Program Files (x86)\SqliteBrowser3\bin\sqlitebrowser.exe  --path=x:\mydb.db   --tab=browse   --table=mytable   --action=edit  "

This capability would enable sqlitebrowser to be executed from other applications within a specific context for a specific purpose while ensuring that the end-user gets exactly where they need to be.

Thank you for a great tool.

**Comment by justinclift** [comment]
Interesting thought.  It might also be useful to automate testing of GUI components in future too (though I suspect there are already Qt tools for that).

**Comment by Z4us** [comment]
Don't know about Windows, but with OSX you can do it yet.

**Comment by justinclift** [comment]
@Z4us That's a bit unclear to me... what do you mean? :smile:

**Comment by mgrojo** [comment]
@DaltonST This was implemented with some other issues. If you want to try, install one of our [nightly builds](https://nightlies.sqlitebrowser.org/latest/) or wait for our upcoming 3.11 release.

```
Usage: ./sqlitebrowser [options] [db]

Possible command line arguments:
  -h, --help		Show command line options
  -q, --quit		Exit application after running scripts
  -s, --sql [file]	Execute this SQL file after opening the DB
  -t, --table [table]	Browse this table after opening the DB
  -R, --read-only	Open database in read-only mode
  -v, --version		Display the current version
  [file]		Open this SQLite database

```

Following your example:
`sqlitebrowser --table my_table  /path/to/my_database.db`
