### ISSUE TITLE
[Feature]: merge driver

### ISSUE THREAD

**Issue by AndersBillLinden** [sqlitebrowser/sqlitebrowser#3466]
### Describe the new feature

When a database file has been changed in two branches in a version control system, the user should be able to select which of the changes that is interesting in in each of the files. That should involve specifying which columns that are implicite forgein keys so that joined-to ids are managed appropriately.

**Comment by justinclift** [comment]
Is this a feature request for DBHub.io, or a feature request for DB Browser for SQLite?

It's unclear from the description. :smile:

**Comment by AndersBillLinden** [comment]
Feature request for DB Browser for SQLite. Sorry.

**Comment by justinclift** [comment]
No worries.  What you're asking for could be a capability added to a version control system, but it doesn't really make sense to implement it independently in our application.

**Comment by AndersBillLinden** [comment]
I would say that every application should take responsibility of being able to compare its output files with each other. Ms Word for instance lets you compare two documents and select which parts that you want in the final result.

**Comment by chrisjlocke** [comment]
There is a sqldiff program which will happily compare two databases.  Have you seen or tried that program?

**Comment by chrisjlocke** [comment]
Closing as sqldiff or dbhub.io ccould be used.
