### ISSUE TITLE
[Bug]: the download server at https://sqlitebrowser.org/dl/#windows times out witho9ut downloading a file

### ISSUE THREAD

**Issue by johnwarh** [sqlitebrowser/sqlitebrowser#3467]
### What did you do?

tried to download file by clicking on link

### What did you expect to see?

expected a file download

### What did you see instead?

error page with connection times out

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

win 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Thanks, it should be working again now. :smile:
