### ISSUE TITLE
[Bug]: Starts with an empty window. No Interaction possible

### ISSUE THREAD

**Issue by Sumidu** [sqlitebrowser/sqlitebrowser#3475]
### What did you do?

I started SQLiteBrowser as regularly.

### What did you expect to see?

I expected it to open as normally.

### What did you see instead?

The window was completely empty. No interaction possible. 

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

MacOS 13.5.1

### Relevant log output

```shell
When starting from Terminal, I get the following log:

qt.qpa.fonts: Populating font family aliases took 51 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
Failed to create NSOpenGLContext
Failed to create NSOpenGLContext
composeAndFlush: QOpenGLContext creation failed
Failed to create NSOpenGLContext
composeAndFlush: makeCurrent() failed
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by Sumidu** [comment]
A simple reboot did the trick...

**Comment by chrisjlocke** [comment]
Thanks for reporting back what the solution was. :)
