### ISSUE TITLE
no utf-8 char support

### ISSUE THREAD

**Issue by abshuhuhuhu** [sqlitebrowser/sqlitebrowser#348]
DB Browser for SQlite for SQLITE
version: 3.6.0
while execute sql, 
no uft-8 char is support
the sentence : 
select * from refer where namecn like '%术语%'
will be looks like this:
select * from refer where namecn like '%??%'

**Comment by justinclift** [comment]
Yeah.  There was a bug in our Unicode handling with 3.6.0.  If you grab the latest nightly build though, it's fixed. :smile:

(download locations are shown on the front page of this repo, if that helps)

**Comment by justinclift** [comment]
@abshuhuhuhu Have you had a chance to grab the latest nightly build, and use that instead?

**Comment by justinclift** [comment]
Closing this, as we don't seem to be getting a response + the issue is already fixed in our codebase. :smile:
