### ISSUE TITLE
[Feature]: RETURNING is not working?

### ISSUE THREAD

**Issue by Mucip** [sqlitebrowser/sqlitebrowser#3480]
### Describe the new feature

I can not see the result of

INSERT INTO table(valu_a) VALUES (12) RETURNING row_key;

Normally row_key should be seen in reslt section?

Regards,
Mucip:)

**Comment by FriedrichFroebel** [comment]
This seems to be a duplicate of #2720. Please try with one of the nightly builds.

**Comment by justinclift** [comment]
Info about our nightly builds, as there are a bunch of options depending upon your Operating System: :smile:

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds

**Comment by chrisjlocke** [comment]
I see you've reported this on the main SQLite support forum too.  Technically, it isn't an SQLite issue, but more the 'wrapper' you're using.

I can help here, as I use vb.net extensively with SQLite.
You don't need the nuget packages or anything else.

Is this a critically urgent request?  I can help with some tutorials to get you up and running.

**Comment by chrisjlocke** [comment]
Closing as duplicate, and no response.
