### ISSUE TITLE
[Bug]: Function keys not working on Mac

### ISSUE THREAD

**Issue by bintoro** [sqlitebrowser/sqlitebrowser#3482]
### What did you do?

I entered a statement in the Execute SQL tab and pressed F5.

### What did you expect to see?

I expected the query to run.

### What did you see instead?

The query did not run. It did run when I hit Cmd+Return.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

MacOS

### OS version

14.0

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Interesting.  What kind of keyboard are you using?

Not sure if it'll make a difference, but it's probably a useful data point for our macOS friendly developers who'll be interested in this.

@lucydodo @scottfurry Sounds like this'll be of interest. :smile:

**Comment by scottfurry** [comment]
Weird key action under Ventura. Unfortunately, I'm stuck at Monterey due to hardware. I'll look for something obvious a little later.

**Comment by bintoro** [comment]
> Interesting. What kind of keyboard are you using?

Apple's wireless keyboard. But the same thing happens on the MBP built-in keyboard.

Disclaimer: I have Karabiner (a keyboard customizer) installed. However, the issue persists even if I quit Karabiner, and also the function keys work normally in other apps.

This is not a priority by any means, but it does make "Execute current line" unavailable via keyboard.

**Comment by chrisjlocke** [comment]
> but it does make "Execute current line" unavailable via keyboard

You can highlight a block of text and press [F5].  This will only execute the selection.  To me, and bit more intuitive than pressing Shift+F5

**Comment by lucydodo** [comment]
Interesting. For me, the query runs fine when I press F5. (To be precise, the Fn + F5)
Is the function key set to use the standard function key? If not, try pressing it along with the Fn key.
You might also be interested in [Apple - How to use the function keys on your Mac](https://support.apple.com/en-us/HT204436)
> Test environemtn: Logitech MX Mechanical Mini and macOS Sonoma

**Comment by bintoro** [comment]
> For me, the query runs fine when I press F5.

Thanks for testing! I investigated some more and found the problem. My customized keyboard layout file was missing entries for the F keys, whereas the system keyboard layout maps all F keys to the character code point `0x10`. After copying those lines over, the problem went away.

So, it seems that defining an output character for a virtual keycode is necessary for it to be detected, even if the output doesn't really identify the key in question. Maybe it's a Qt thing. 🤷‍♂️

Sorry about the invalid bug report.

**Comment by justinclift** [comment]
> Sorry about the invalid bug report.

No worries, glad you got it figured out. :smile:
