### ISSUE TITLE
[Feature]: "Execute current line" improvements

### ISSUE THREAD

**Issue by bintoro** [sqlitebrowser/sqlitebrowser#3483]
### Describe the new feature

A few ideas to make the "Execute current line" operation more intuitive and accessible:

* Add counterparts to the other *Execute* shortcuts besides F5, i.e., Shift-Ctrl-R and Shift-Ctrl-Return.
* Rename the operation to "Execute current statement", which I suppose is the intended meaning and what currently happens as long as the cursor is on the first line of a multiline statement.
* Have the feature execute the entire statement even if the cursor is not on the first line.

**Comment by lucydodo** [comment]
It sounds resonable and shouldn't be too difficult to resolve the issue. However, We'll almost done with the translation for the next release, so we might want to consider solve it after the next release. @justinclift What do you think about this? 😄

**Comment by justinclift** [comment]
Probably do it for the next release.  We've already had a lot of the translations done for this one. :wink:

**Comment by lucydodo** [comment]
Hi @bintoro, I've added a commit to a new branch that applies the improvements you suggested,
but as comments above, it will most likely not be in this release.

> Have the feature execute the entire statement even if the cursor is not on the first line.

By the way, can you elaborate a bit more on the above?
because when I tested it, it seems to be work as you said. Thanks for your patience.

**Comment by bintoro** [comment]
> > Have the feature execute the entire statement even if the cursor is not on the first line.
> 
> By the way, can you elaborate a bit more on the above? because when I tested it, it seems to be work as you said. Thanks for your patience.

I’m sorry, I had totally missed this question.

So yeah, upon further investigation, the command isn’t completely broken. But it seems that when searching backwards from the cursor to locate the first line of the current statement, only explicit semicolons are recognized; the beginning of the text area is not.

To illustrate:

![screenshot](https://github.com/sqlitebrowser/sqlitebrowser/assets/7081785/cac15070-900c-440d-8dd1-71e06d8289a4)

Cursor on line | Shift+F5 executes
---|---
1 | 1st statement  ✅
2 | 2nd line (error)  ❌
3 | 3rd line (error)  ❌
4 | 4th line (error)  ❌
5 | nothing  ✅
6..10 | 2nd statement  ✅

But if I prepend a semicolon to the first `SELECT`, everything works as expected.

**Comment by justinclift** [comment]
Oh, that sounds like a good catch.  @mgrojo I *think* this will be of interest to you. :smile:

**Comment by chrisjlocke** [comment]
Easy workaround... just highlight the statement you want to execute.  Works every time. ;)

**Comment by mgrojo** [comment]
Should be fixed, in anything case. But the last time I looked at this was not straightforward; this part of the code is complex.

**Comment by mgrojo** [comment]
Uhmm, I remembered something more cumbersome. I believe it's easy after all. Looking at it.

**Comment by mgrojo** [comment]
> So yeah, upon further investigation, the command isn’t completely broken. But it seems that when searching backwards from the cursor to locate the first line of the current statement, only explicit semicolons are recognized; the beginning of the text area is not.
>  [...]
> But if I prepend a semicolon to the first `SELECT`, everything works as expected.

This bug should be fixed now in the next nightly build and will enter the next release (v3.13.0).

**Comment by lucydodo** [comment]
@mgrojo Would it make sense to merge changes to 1 and 2 into the master branch after the next release? 🤔

**Comment by mgrojo** [comment]
@lucydodo , yes, of course, it makes sense. As soon as we have the release branch, you are free to merge it.

**Comment by lucydodo** [comment]
@mgrojo Thanks, I'll merge it after the when we create next release branch.
@bintoro As mentioned above, this will be reflected in the near future, and I'll elt you know when that happens. Thanks.

**Comment by justinclift** [comment]
@lucydodo The new `v3.13.x` release branch was created by @mgrojo yesterday, so merging stuff into `master` that's been waiting should now be ok. :smile:

**Comment by mgrojo** [comment]
@lucydodo but check first with @deepsidhu1313 , I understood that he still needs some time for master to be frozen.

**Comment by deepsidhu1313** [comment]
Hey, sorry for the master branch thing, I can switch all the builds to 3.13.x branch temporarily if we are not planning 3.13.x release soon, or if you need this change on master urgently.

**Comment by lucydodo** [comment]
@justinclift @mgrojo Thanks for letting me know.
@deepsidhu1313 Don't worry, Take your time. :)
