### ISSUE TITLE
incorrect CREATE TABLE ending in sql export

### ISSUE THREAD

**Issue by ant-on-io** [sqlitebrowser/sqlitebrowser#349]
Using File > Export > Database to SQL File:
Tables containing some data, are written correctly. But for empty tables, an extra ); is added on a new line, after the table.

Example:
correct:
CREATE TABLE "Table_with_data" (
  "object_id" INTEGER NOT NULL,
  "value" REAL NULL);
INSERT INTO `Table_with_data` VALUES (1,40.0);
INSERT INTO `Table_with_data` VALUES (2,90.0);

incorrect:
CREATE TABLE "Empty_table" (
  "object_id" INTEGER NOT NULL,
  "value" REAL NULL);
); <<<<<<<<<< redundant closing bracket

AFAICS, this occurs since v3.6.0 (export was correct in 3.5.1)

**Comment by schdub** [comment]
@ant-on-io thank you for reporting. This is definitely bug.

**Comment by justinclift** [comment]
@ant-on-io Would you be ok to try the latest nightly build (tomorrow), and verify back to us if it works or not? (just in case) :wink:

**Comment by ant-on-io** [comment]
OK, I will. I'll let you know if it works. Thanks for fixing!

**Comment by ant-on-io** [comment]
Hi Justin,

Just tested with the nightly build and confirm fixed. Export is correct. 
Thanks,

Best regards
Anton

**Comment by justinclift** [comment]
Awesome!  Thanks for testing and letting us know Anton. :smile:
