### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ATcDTc** [sqlitebrowser/sqlitebrowser#3491]
### What did you do?

DB Browser for SQLite version 3.12.2, it not working: power(), ceil(), floor(), sqrt();

for example:
--power, es potencial para potencias
SELECT multiplicador, power( multiplicador, 4)
from empleados;

--ceil, redondeo a la derecha, sin importar si esta cerca de 5
select salario, ceil(salario)
from empleados;

--floor, redondea a la izquierda, quita los decimales
Select salario, ceil(salario), floor(salario)
from empleados;

--sqrt(), raiz cuadrada
select sqrt(salario), salario
from empleados
where salario is not null and salario>0;

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/147943110/9a0cf1d1-acf7-4e63-99ae-6b1c3ecbddcf)

### What did you expect to see?

I hope it works again

### What did you see instead?

error

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

windows 11

### Relevant log output

```shell
These provide the functions in another program and if they work, only in this one that is better it does not work
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Thanks for letting us know.  As a work around for now, please grab one of our Nightly Builds instead:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds

These functions should work in that. :smile:
