### ISSUE TITLE
Unable to set the reference table for a foreign key

### ISSUE THREAD

**Issue by jojje888** [sqlitebrowser/sqlitebrowser#3493]
### What did you do?

1. I right-clicked on a table and selected `Modify Table`
2. I clicked on the tab `Constraints` in the dialog.
3. I clicked the `Add constraint` button, Foreign key.
4. I get a new row in the table where I can select the column of the referencing table, set the name of the foreign key, but there is no way to edit the referenced table name and column name.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/39448795/6aeff0f2-24f4-486a-bd60-bdcbed952e0a)

### What did you expect to see?

I expected to be able to set the referenced table and column name for a foreign key.

### What did you see instead?

I couldn't find a way to do it.

I ended up executing an SQL statement that I manually edited,

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
This does work, but the GUI is a bit 'glitchy' to actually process it.

If you see my answer in this issue (https://github.com/sqlitebrowser/sqlitebrowser/issues/3420) that might help.

Yell back if this does or doesn't work for you, or if you need more info.

**Comment by tohagan** [comment]
I hit the same area of confusion but your explanation in #3420 worked. Thanks.

**Comment by chrisjlocke** [comment]
Glad you got it working.

**Comment by jojje888** [comment]
@chrisjlocke Thanks for the explanation, I got it working now.
I totally missed the `Foreign Key` column on the Fields tab, because I didn't expand the dialog box.
I also assumed that the only place to edit the FK was on the Constraints tab.
