### ISSUE TITLE
[Bug]: Build errors : use of undeclared identifier 'sqlite3_enable_load_extension', 'sqlite3_load_extension'

### ISSUE THREAD

**Issue by mikeg-asi** [sqlitebrowser/sqlitebrowser#3496]
### What did you do?

Following build instructions: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#macos

### What did you expect to see?

Build to complete successfully

### What did you see instead?

sqlitedb.cpp has error compiling:

$ brew tap sqlitebrowser/tap
$ brew install db4sqt@5
$ git clone https://github.com/sqlitebrowser/sqlitebrowser.git
$ cd sqlitebrowser/
$ mkdir build && cd build

$ cmake -DcustomTap=1 -DFORCE_INTERNAL_QSCINTILLA=ON ..
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode_14_1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_14_1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SQLite3: /Applications/Xcode_14_1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include (found version "3.39.4")
-- Configuring done
-- Generating done

$ cmake --build .
[  0%] Automatic MOC for target qcustomplot
[  1%] Automatic MOC for target qhexedit
[  1%] Built target qcustomplot_autogen
[  1%] Built target qhexedit_autogen
[  4%] Built target qcustomplot
[  4%] Built target qhexedit
[ 48%] Built target qscintilla2
[ 49%] Automatic MOC for target sqlitebrowser
[ 49%] Built target sqlitebrowser_autogen
Consolidate compiler generated dependencies of target sqlitebrowser
[ 49%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sqlitedb.cpp.o
[ 49%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/ExtendedScintilla.cpp.o
[ 50%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/CondFormatManager.cpp.o
[ 50%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/FileExtensionManager.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/DotenvFormat.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/Data.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/FindReplaceDialog.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/CipherSettings.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/Palette.cpp.o
[ 52%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/CondFormat.cpp.o
[ 53%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/RunSql.cpp.o
[ 53%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/ProxyDialog.cpp.o
[ 54%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/IconCache.cpp.o
[ 54%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/SelectItemsPopup.cpp.o
[ 55%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/TableBrowser.cpp.o
[ 55%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sql/parser/ParserDriver.cpp.o
[ 55%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sql/parser/sqlite3_lexer.cpp.o
[ 56%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/sql/parser/sqlite3_parser.cpp.o
**.../local/github/sqlitebrowser/src/sqlitedb.cpp:2138:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(_db, 1);**
    ^
**.../local/github/sqlitebrowser/src/sqlitedb.cpp:2142:18: error: use of undeclared identifier 'sqlite3_load_extension'
    int result = sqlite3_load_extension(_db, filePath.toUtf8(), nullptr, &error);**
                 ^
**.../local/github/sqlitebrowser/src/sqlitedb.cpp:2147:9: error: use of undeclared identifier 'sqlite3_enable_load_extension'
        sqlite3_enable_load_extension(_db, 0);**
        ^
**.../local/github/sqlitebrowser/src/sqlitedb.cpp:2165:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
    sqlite3_enable_load_extension(_db, Settings::getValue("extensions", "enable_load_extension").toBool());**
    ^
[ 56%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/ImageViewer.cpp.o
4 errors generated.
make[2]: *** [CMakeFiles/sqlitebrowser.dir/src/sqlitedb.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
make: *** [all] Error 2
#

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

MacOS

### OS version

Monterey 12.5.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
Hi @mikeg-asi 
There are some SQLite compile options that our project needs, so we also provide a Homebrew Formula with these compile options. You can install it by running the following command.
```
brew install db4ssqlitefts@5; brew link db4ssqlitefts@5
```
After installation, and then before building, be sure to delete any generated CMake files.
This is because the existing configuration is set to point to Xcode's built-in SQLite.

Give it a try and let us know if you have any other problems. :)

**Comment by justinclift** [comment]
@lucydodo Does a tap need to be set up in Homebrew first, before it will find our formulas? :smile:

**Comment by lucydodo** [comment]
@justinclift Yes, right.
But based on the command log @mikeg-asi posted, tap was already cloned, so I didn't mention it. 😄

**Comment by lucydodo** [comment]
Yes, that's right, I dropped Homebrew Bottle support for macOS Monterey a while ago.
I forgot to disable that option. I just turned it off, so try it again after the `brew update' command.

**Comment by mikeg-asi** [comment]
Fundamentally the problem was that cmake find_package(SQLite3) would always pickup an old SQLite3 version in Xcode_14_1 that did not have sqlite3 extensions:

-- Found SQLite3: /Applications/Xcode_14_1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include (found version "3.39.4")

Could not figure out how to override that cmake behavior thru various tweaks to the find_package call and command line overrides.

Eventually changed the CMakeLists.txt file to completely remove the find_package(SQLite3) and force the issue like so:

set(MG_SQLITE_HOME /usr/local/Cellar/sqlite/3.43.2)
set(MG_SQLITE_INCLUDE ${MG_SQLITE_HOME}/include)
set(MG_SQLITE_LIBRARY ${MG_SQLITE_HOME}/lib/libsqlite3.a)
target_link_libraries(${PROJECT_NAME} "${MG_SQLITE_LIBRARY}")
target_include_directories(${PROJECT_NAME} PRIVATE src "${MG_SQLITE_INCLUDE}")

Maybe there is a cleaner solution but the browser is building and running successfully now.

Thanks again for being responsive on this issue!

**Comment by lucydodo** [comment]
I'm glad to hear you got it working, but I have a quick question. If you install the 'db4ssqlitefts@5' package and then give cmake the `customTap=1` option, doesn't that set cmake to point to that package? 🤔 

Because our macOS build machine and I am use the same method above to build on my local machine.

**Comment by mikeg-asi** [comment]
Yes, tried that.  Seemed like a good option, but no matter what cmake would always lock on to sqlite3 in Xcode like so:

-- Found SQLite3: /Applications/Xcode_14_1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include (found version "3.39.4")

Then the generated CMakeCache.txt had this:

    SQLite3_INCLUDE_DIR:PATH=/Applications/Xcode_14_1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include

resulting in the undeclared identifier 'sqlite3_enable_load_extension', 'sqlite3_load_extension' compile errors.

**Comment by lucydodo** [comment]
```
brew link db4ssqlitefts@5
```
Sorry for the hassle, can you confirm if the same thing happens after running the above commands?

**Comment by mikeg-asi** [comment]
Wasn't able to brew install that due to being on the Monterey

Error: db4ssqlitefts@5: Failed to download resource "db4ssqlitefts@5"
Download failed: https://nightlies.sqlitebrowser.org/homebrew_bottles/db4ssqlitefts%405-3.44.0.monterey.bottle.1.tar.gz

**Comment by lucydodo** [comment]
Oh, no, I figured out the cause. You are correct that the 'customTap' option does not work if you have an Intel-based Mac or an installation of Formula that does not support the universal binary build. I'll fix this this weekend and let you know. 😄

**Comment by lucydodo** [comment]
@mikeg-asi I created a new branch(https://github.com/sqlitebrowser/sqlitebrowser/tree/fix-3496) and resolved this issue. Can you confirm this is work? 😄 
```
git checkout https://github.com/sqlitebrowser/sqlitebrowser; cd sqlitebrowser
git checkout fix-3496
mkdir build; cd build
cmake -DcustomTap=1 ..
```
> At least it worked in my VM env (macOS Monterey 12.6 21G115)

**Comment by justinclift** [comment]
> git checkout https://github.com/sqlitebrowser/sqlitebrowser

Should that be `git clone` instead?

**Comment by lucydodo** [comment]
Good catch, that's a typo.
And I didn't realize I can only clone a specific branch when cloning, Thanks, I learned something today. 😄

**Comment by justinclift** [comment]
Still needs the `cd sqlitebrowser` after doing the clone. :wink:

**Comment by lucydodo** [comment]
Thanks, I modified it again. :D

**Comment by mikeg-asi** [comment]
It probably is fine.  However I get the error below on my machine.  Unfortunately I cannot update Xcode at this time.  For my specific case, I am able to build sqlitebrowser by forcing a different location for sqlite source in CMakeLists.txt other than the Xcode 14.1 bundled version.  So I am happy.

```
$ brew install db4ssqlitefts@5
==> Fetching sqlitebrowser/tap/db4ssqlitefts@5
==> Downloading https://sqlite.org/2023/sqlite-autoconf-3440000.tar.gz
Already downloaded: /Users/graz/Library/Caches/Homebrew/downloads/8be221c1025d32b8c8c06f74710a9681fa814226841a2c3b1731391583c6a376--sqlite-autoconf-3440000.tar.gz
==> Installing db4ssqlitefts@5 from sqlitebrowser/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.2.

```

**Comment by lucydodo** [comment]
I didn't realize the version of the CLI tool was an issue, thanks for the test.

**Comment by justinclift** [comment]
Yeah, Homebrew's treatment of older versions of utilities isn't really doing its users any favours: :frowning:

```
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences.
```
