### ISSUE TITLE
[Bug]: Unusual behavior when scrolling horizontally with Shift + Scroll

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#3498]
### What did you do?

Try scrolling with the Shift key

### What did you expect to see?

Horizontal scrolling

### What did you see instead?

It works for me, but there have been some reports of it not working.
You can also see that the amount of horizontal scrolling is different when using 'Alt' instead of 'Shift'.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Windows, MacOS

### OS version

Windows 11 (Version 22H2), macOS 14.0 (23A344), 

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
@malordin, Pinged since you are the author of the original discussion.
I've looked into this, but it's Qt's side that binds the 'Alt' key for horizontal scrolling,
and there doesn't seem to be any way for framework users to change it.

So, I've closed this as it seems to be an issue that needs to be addressed on the Qt side.

**Comment by justinclift** [comment]
Oh.  I didn't know that shift + scrolling was supposed to do anything.  Will try it out in other applications at some point... :smile:
