### ISSUE TITLE
[Bug]: Icon missing on snap install

### ISSUE THREAD

**Issue by kevinhikaruevans** [sqlitebrowser/sqlitebrowser#3500]
### What did you do?

I have a fresh install from the snap store. I noticed the icon was missing and using the default application icon (the cogs).

### What did you expect to see?

The sqlitebrowser icon. I'm not sure if the icon isn't being copied over to the system's paths or if there's something else that's supposed to be handling it.

My workaround is changing the .desktop file and manually entering in the icon path:
```
Icon=sqlitebrowser
```
to
```
Icon=/snap/sqlitebrowser/current/meta/gui/icon.svg
```

### What did you see instead?

The default application icon: ![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/4730591/f8184e66-4ac2-4d87-a1fe-c9ed52d02e88)

This is also the icon that appears when the application is opened and in the taskbar.

### DB4S Version

3.12.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 23.10

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/4730591/9f5862a6-592f-4d70-ab40-2b8a293b8fcc)

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
Apparently it's defined here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/4e8623b47ec0e26e10990b41913a349e935eb1a2/snap/snapcraft.yaml#L22

Maybe @deepsidhu1313 can analyze the issue.

**Comment by deepsidhu1313** [comment]
i will take a look.

**Comment by deepsidhu1313** [comment]
i am not able to replicate the issue. I am able to see the icon clearly. 
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7684338/3cee9358-1aea-414f-b880-b977abee777c)
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7684338/e20d1881-be40-4948-9893-739a64fe4285)

Installed package from edge channel on live Ubuntu 23.10 image using app store.

This line doesn't feel right.

```
Icon=sqlitebrowser
```
did you create that desktop file manually ? bcz the one in snap package points to

```
Icon=${SNAP}/meta/gui/icon.svg
```

**Comment by deepsidhu1313** [comment]
is it possible to share the output of `sudo snap info sqlitebrowser`

**Comment by justinclift** [comment]
Just to point out, the screenshot in the issue report shows a snap built (from the `master` development branch) on 24th May 2021.

That was quite a long time ago, so more recent versions of our Snap might have improved things.

As @deepsidhu1313 says, the info from the `snap info` command should help us work out what's going wrong. :smile:

**Comment by kevinhikaruevans** [comment]
Here's the output of snap info:

```
name:      sqlitebrowser
summary:   DB browser for Sqlite
publisher: Gajj GNDU (gajjgndu)
store-url: https://snapcraft.io/sqlitebrowser
contact:   linuxgndu@gmail.com
license:   unset
description: |
  SQLite Database Browser is a visual tool used to create, design and edit
  database files compatible with SQLite. Its interface is based on QT, and is
  meant to be used for users and developers that want to create databases,
  edit and search data using a familiar spreadsheet-like interface, without
  the need to learn complicated SQL commands. Controls and wizards are
  available for users to:
  * Create and compact database files
  * Create, define, modify and delete tables
  * Create, define and delete indexes
  * Browse, edit, add and delete records
  * Search records
  * Import and export records as text
  * Import and export tables from/to CSV files
  * Import and export databases from/to SQL dump files
  * Issue SQL queries and inspect the results
  * Examine a log of all SQL commands issued by the application
  SQLite Database Browser is not a visual shell for the sqlite command line
  tool. It does not require familiarity with SQL commands.
commands:
  - sqlitebrowser
snap-id:      r0gLdj09nlalUEzAy6kQf7s5f5bgcOzT
tracking:     latest/stable
refresh-date: 5 days ago, at 08:32 PST
channels:
  latest/stable:    3.12.2-3569-6cde3f5  2021-05-24 (3233)  91MB -
  latest/candidate: 3.12.2-3569-6cde3f5  2021-05-24 (3233)  91MB -
  latest/beta:      3.12.2-3809-9426509a 2023-03-18 (3834) 113MB -
  latest/edge:      3.12.2-3953-a4c7ca2b 2023-11-12 (4168) 113MB -
installed:          3.12.2-3569-6cde3f5             (3233)  91MB -
```

I didn't even see how out of date the snap version was! I did a `snap refresh --beta` and that updated it to the March 15 2023 version and the icon is working correctly here:

`Icon=/snap/sqlitebrowser/3834/meta/gui/icon.svg`

**Comment by justinclift** [comment]
Awesome.  It's good when the problems turn out to be easy to fix, or are already solved. :grin:
