### ISSUE TITLE
[Bug]: BD browser closes without any sign of error

### ISSUE THREAD

**Issue by neox94** [sqlitebrowser/sqlitebrowser#3501]
### What did you do?

I executed a database, a very small one, then I opened a new tab in order to insert info into this database, after a few minutes it closes. Every time a try to do the same it closes even faster than before.I have reinstall this software like 5 times today, this issue dosn't go away.

### What did you expect to see?

There is nothing to see

### What did you see instead?

I expect that this software to worked

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Mint

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ahhh.  As you're on Linux, try using the AppImage instead:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

The AppImage(s) are created automatically every time there's an update to our development source code, and should be very solid at the moment as we're preparing for our next major release. :smile:

**Comment by chrisjlocke** [comment]
@neox94 - Any joy with the appimage?

**Comment by chrisjlocke** [comment]
Excellent. 👍
