### ISSUE TITLE
[Feature]: Add ability to view & edit binary property lists

### ISSUE THREAD

**Issue by latenitefilms** [sqlitebrowser/sqlitebrowser#3503]
### Describe the new feature

I'm using **DB Browser for SQLite** to read SQLite databases created using Core Data.

In some of the fields in this Core Data database, you can binary property lists stored as binary data.

In **DB Browser for SQLite**, I can view the data in binary & hex editor form:

<img width="1638" alt="image" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/22286696/549b24d7-bbfb-403a-8c12-1552a9db8d78">

However, I'd love the ability for **DB Browser for SQLite** to be able to translate this binary property data into plain text XML - for example, using BBEdit it looks like this:

<img width="766" alt="image" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/22286696/f2ea7742-5f66-4d09-831e-6b0f820e3d8c">

This would allow me to make easy tweaks directly in **DB Browser for SQLite**, without having to have to export a the binary `plist` file, modify it, then bring it back in.

Given binary property lists are very common in the macOS world, and is used extensively by Core Data (with a SQLite backend) - I think this could be a very useful feature that could be used by lots of different users.

Any questions let me know. Thanks team!

**Comment by chrisjlocke** [comment]
Seems odd having that as binary data in a database... why not just have a separate table ... seems like embedding an excel chart inside a word document and storing that in an excel chart again... ;)

**Comment by latenitefilms** [comment]
I believe that’s just how [Core Data](https://developer.apple.com/documentation/coredata/) works?

**Comment by mgrojo** [comment]
We already have support for decoding binary plist through an extension, but not editing it. See #1716.

**Comment by latenitefilms** [comment]
@mgrojo - Dumb question... how do I actually download and install this extension?

**Comment by mgrojo** [comment]
The source code is here: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/extensions/extension-formats.c

I think it's included in our macOS builds in "$TARGET/Contents/Extensions/formats.dylib", see https://github.com/sqlitebrowser/sqlitebrowser/blob/c73afe3c6ba10cbf139e138b12aa899e62cf1e84/.github/actions/notarize-macos/action.yml#L47

Maybe @lucydodo can confirm.

**Comment by lucydodo** [comment]
Yes, that's right. In fact, it's not a "dumb question" at all because it's a little complicate to install.
I made a video a while back demonstrating how to load the `sqlean` extension when we decide built-in that: https://www.youtube.com/watch?v=FM5TSX9JRA8
In the last step of the video, `sqlean.dylib` is selected, but instead of that, you can select `formats.dylib`

**Comment by justinclift** [comment]
@latenitefilms As a data point, @lucydodo has been improving the way SQLite extensions work with the application.

Those improvements are mostly available in the recent builds, so probably best to use one of those when doing stuff:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Those builds should be pretty stable, as we've been preparing for a next release for ages. :grin:

**Comment by lucydodo** [comment]
Hi, @malicious 
I realized this issue today and was writing a report on it when I saw this comment. I apologize for the delay in responding.
This was not intentional and was purely an oversight on my part. It will be fixed in an upcoming patch.
Until then, you can take note of this issue and work around the issue: #3647

**Comment by lucydodo** [comment]
As an aside, this issue itself appears to be resolved, so I'm closing the issue.
If you need, you can reopen the issue and leave a comment.
