### ISSUE TITLE
[Feature]: a shortcut (probably insert key) for inserting new records on browse data window 

### ISSUE THREAD

**Issue by aydinunal** [sqlitebrowser/sqlitebrowser#3515]
### Describe the new feature

a keyboard shortcut to insert new records while brosing the table view...it is just not feasible to use mouse for repeated data entry

### Does this feature exist in another product or project? Please provide a link

yes nearly all data managers have this feature.

**Comment by justinclift** [comment]
Sounds like you found the tab key? :smile:

**Comment by aydinunal** [comment]
yes finally, but for some reason database was locked and tab key was working as a normal tab key.  So instead of warning me that the database was locked, tab key was moving to next gui interface instead of inserting a new row.  So it is not entirely my fault
