### ISSUE TITLE
[Feature]: SQLite function timediff not working

### ISSUE THREAD

**Issue by lucasarrudadev** [sqlitebrowser/sqlitebrowser#3516]
### Describe the new feature

When running:
SELECT timediff('2023-02-15','2023-03-15');

We get the error:
no such function: timediff

The timediff() SQL function was added to SQLite with release 3.43.0 on 2023-08-24

Could we use some SQLite version that allows for timediff function?

**Comment by chrisjlocke** [comment]
What version of DB Browser for SQLite are you using?

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/f478c26a-9f1b-4ed0-abed-55301be94cea)

If you click 'Help' and 'About' you get a dialog that not only gives you the version of DB4S, but also SQLite.
The last official version of 3.12.2 was with SQLite 3.35.5.

Depending on your operating system, you may be able to use a more up to date nightly build.  This'll use the latest version of SQLite.
https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
@lucasarrudadev - any joy?

**Comment by nesergen** [comment]
I have the same problem. 

DB Browser for SQLite Version 3.13.99 (Jan 15 2024)
Last commit hash when built: Unknown

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.8
SQLCipher Version 4.5.5 community (based on SQLite 3.42.0).

**Comment by justinclift** [comment]
@nesergen Would you be ok to screenshot the problem and the error message it's giving? :smile:

**Comment by lucydodo** [comment]
Hi, @nesergen 

> https://www.sqlite.org/releaselog/3_43_0.html

The `timediff` function is supported in SQLite versions 3.43.0 and later.

> SQLCipher Version 4.5.5 community (based on SQLite 3.42.0).
But looking at your version information, you're using SQLCipher 4.5.5, which is based on SQLite 4.42.0

I'm not sure, but my guess is that using a [nightly build](https://nightlies.sqlitebrowser.org/latest/) that supports the latest SQLCipher* will fix the problem.

>*: SQLCipher just released version 4.5.6 last week, which is based on SQLite 3.44.2

**Comment by nesergen** [comment]
@lucydodo 
you right. The confusion is that I already installed the latest test version, but only from the repository. As it turned out, it does not support the desired function. I had to compile the program from source code myself using these instructions: [https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#debian--ubuntu-linux](url)
Now everything works !

**Comment by lucydodo** [comment]
@nesergen, I'm glad to hear that it worked out for you.
As a side note, we do provide an AppImage for Linux in our continuous builds, so the next time you need a nightly build, you can run it directly through the AppImage instead of building from source: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

```bash
curl -LO https://github.com/sqlitebrowser/sqlitebrowser/releases/download/continuous/DB.Browser.for.SQLite-dev-7a31ef9-x86.64.AppImage
chmod +x DB.Browser.for.SQLite-dev-7a31ef9-x86.64.AppImage
./DB.Browser.for.SQLite-dev-7a31ef9-x86.64.AppImage
```

> Nightly builds are built based on the last commit at 00 UTC,
> while continious builds are built by the CI system on every commit. (So in theory, both builds are similar)

**Comment by lucydodo** [comment]
Additionally, this issue has not received a response from the creator in over a month, and similar cases have been resolved,
so we are closing this issue as it appears to be provisionally resolved. Feel free to comment and reopen if necessary. Thanks.
