### ISSUE TITLE
No nightlies for macOS arm64

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#3520]
Unsure if this is known about, but macOS arm64 nightlies have stopped since 13 Sep.
"You have not agreed to the Xcode license agreements".

Some build errors:
ERROR: Cannot resolve rpath "@rpath/libwebp.7.dylib"
ERROR:  using QSet("/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/lib")
ERROR: Cannot resolve rpath "@rpath/libsharpyuv.0.dylib"
ERROR:  using QSet("/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/lib")
Log: "codesign, enable hardened runtime, include secure timestamp" "/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/Frameworks/libwebpmux.3.dylib"
ERROR: Cannot resolve rpath "@rpath/libwebp.7.dylib"
ERROR:  using QSet("/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/lib")
ERROR: Cannot resolve rpath "@rpath/libsharpyuv.0.dylib"
ERROR:  using QSet("/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/lib")
Log: "codesign, enable hardened runtime, include secure timestamp" "/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/Frameworks/libwebpdemux.2.dylib"
ERROR: Cannot resolve rpath "@rpath/libsharpyuv.0.dylib"
ERROR:  using QSet("/Users/jc/git_repos/sqlitebrowser/build/DB Browser for SQLite Nightly.app/Contents/lib")

Then
build/DB Browser for SQLCipher Nightly.app: signed app bundle with Mach-O thin (arm64) [net.sourceforge.sqlitebrowser]
/Users/jc/bin/build_sqlitebrowser_nightly-arm64.sh: line 260: appdmg: command not found
DB Browser for SQLCipher-arm64_20230930.dmg: No such file or directory
Error: The value 'DB Browser for SQLCipher-arm64_20230930.dmg' is invalid for '<file-path>': The file couldn’t be opened because it doesn’t exist.
Help:  <file-path>  Path to the archive
Usage: notarytool submit [<options>] <file-path>
  See 'notarytool submit --help' for more information.
File /Users/jc/appdmg/DB Browser for SQLCipher-arm64_20230930.dmg does not exist. Error Domain=NSCocoaErrorDomain Code=260 "The file “DB Browser for SQLCipher-arm64_20230930.dmg” couldn’t be opened because there is no such file." UserInfo={NSURL=DB%20Browser%20for%20SQLCipher-arm64_20230930.dmg -- file:///Users/jc/appdmg/, NSFilePath=/Users/jc/appdmg/DB Browser for SQLCipher-arm64_20230930.dmg, NSUnderlyingError=0x600001dec090 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
mv: rename DB Browser for SQLCipher-arm64_20230930.dmg to /Users/jc/db4s_nightlies/DB Browser for SQLCipher-arm64_20230930.dmg: No such file or directory

DB Browser for SQLCipher-arm64_20231118.dmg: No such file or directory
You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.
mv: rename DB Browser for SQLCipher-arm64_20231118.dmg to /Users/jc/db4s_nightlies/DB Browser for SQLCipher-arm64_20231118.dmg: No such file or directory
Upload nightly builds

**Comment by justinclift** [comment]
Oh, that's weird.  Looking now.

**Comment by justinclift** [comment]
Ahhh.  I think those ones are from a cron job that was accidentally left running on the M1 Mac Mini.

We're using a nightly GitHub Actions based build now, which makes a "Universal Binary" containing both Intel and Apple Silicon in the same download.

I've turned off that old cron job now. :smile:

**Comment by lucydodo** [comment]
Yes, as @justinclift said, we no longer provide build for macOS arm64.
```
build/DB Browser for SQLCipher Nightly.app: signed app bundle with Mach-O thin (arm64) [net.sourceforge.sqlitebrowser]
```
btw, apart from this issue, I think we changed the application id before, but it didn't. should we change it?

**Comment by lucydodo** [comment]
Can we close this issue? :)

**Comment by justinclift** [comment]
Oops, good catch.  Closed now. :smile:
