### ISSUE TITLE
Regexp cannot handle NULL text

### ISSUE THREAD

**Issue by MikimotoH** [sqlitebrowser/sqlitebrowser#353]
http://stackoverflow.com/questions/30643061/sqlite-db-browser-invalid-operand-for-regexp 

I use DB Browser for SQLite version 3.6.0; SQLite Version 3.8.9. If I use regexp on a nullable column `revision` then `invalid operand` error is happened.

```sql
    SELECT brand,revision FROM TDevice WHERE TDevice.revision regexp '^ASUS$';
```

Below is the schema:

```sql
    CREATE TABLE `TDevice` (
    `id`    INTEGER NOT NULL,
    `brand` varchar(128) NOT NULL,
    `model` varchar(128) NOT NULL,
    `revision`  TEXT,
    PRIMARY KEY(id)
    );
```

After I replaced the NULL `revision` with empty string, then this issue fixed.

```sql
    UPDATE TDevice SET revision='' WHERE revision IS NULL
```

I assume `regexp` should behave as `LIKE` operator, because `LIKE` operator can accept NULL text.

**Comment by justinclift** [comment]
Interesting find. :wink:

@MKleusberg, any ideas?  As a thought, the StackOverflow link above helps frame it a bit better too.

**Comment by MKleusberg** [comment]
This commit should fix your problem, effectively a NULL value is now treated as an empty string. Not sure, which operating system you're running but if it's MacOS or Windows you can wait for tomorrow's nightly build and see if the new code works better for you. The download links are on the main page of our repository.

**Comment by MKleusberg** [comment]
Are we ok to close this issue? It's been some time since we fixed it and I'm pretty confident it's working as it should be now.

**Comment by justinclift** [comment]
No worries.  Closing it. :smile:
