### ISSUE TITLE
write changes doesn't work

### ISSUE THREAD

**Issue by Catalina-Asena** [sqlitebrowser/sqlitebrowser#3536]
### What did you do?

I'm trying to add something with "write changes", but there is no button available for it.
It is blend, it can't be clicked on!

### What did you expect to see?

to write changes

### What did you see instead?

I'm trying to add something with "write changes", but there is no button available for it.
It is blend, it can't be clicked on!

### DB4S Version

3.13.0-rc1

### What OS are you seeing the problem on?

Windows

### OS version

windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Can you give steps on what you've done, with possibly some screenshots?
If you add records, then the 'Write Changes' button should spring into life.
Is this with all databases or just one?
While the 'write changes' button isn't lit, can you add records at all?  Can you make database changes, eg, add a temporary table?  Add a new field?

**Comment by Catalina-Asena** [comment]
![17030683357282079212998243724255](https://github.com/sqlitebrowser/sqlitebrowser/assets/154071816/e9a91b66-df04-406a-99e8-2d781e1a5dd4)
![17030683736651113819339511841146](https://github.com/sqlitebrowser/sqlitebrowser/assets/154071816/31ae625e-da63-4eae-9d63-e9a836c7e5a2)
As u see  the button doesn't even load.

Similar issue with others

**Comment by chrisjlocke** [comment]
Aah, we've had this issue before.  I guess we need more of an introduction to DB Browser for SQLite.

You're entering in data into the **filter** row, not into a new record.  The data you're entering in the first row is used to filter subsequent rows, so you only see specific records.  This is why they have [x] symbols after them.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/034c60e7-a7f4-4985-8ac4-35e7d551f8ad)

Click the button which has a green row and a plus sign on it.  You may need to close the panels on the right to see the full toolbar, or you can click on the overflow icon.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/d4730c16-d016-4a9d-b56d-678cf975454c)

Click the ioverflow icon (1), then the 'New record' icon (2)

This should then create a new row where you can enter data. :)

**Comment by Catalina-Asena** [comment]
thank u so much! it works!

very grateful for the QUICK response!

**Comment by justinclift** [comment]
Awesome, sounds like this is resolved. :smile:

Is this issue ok to be closed?

**Comment by justinclift** [comment]
@Catalina-Asena Btw, do you remember where you downloaded that version of our application from?

In theory the 3.13.0-rc1 builds shouldn't be publicly available yet (we're still working on them), so it sounds like there's something unexpected happening in our build processes.

There's nothing "wrong" with the builds btw, they're just not "ready" for release yet. :smile:

**Comment by chrisjlocke** [comment]
It may just be the default on the issue template.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/2222eaeb-c849-4844-b070-1a0937f66771)

**Comment by justinclift** [comment]
Ahhh.  That probably shouldn't be on the template yet.
