### ISSUE TITLE
[Bug]: Font color of the copied result data on the Execute SQL pane need to be other than White, as they become invisible on pasting into excel. Noticed on MACOS Apple Silicon 3.12.2

### ISSUE THREAD

**Issue by linuxguist** [sqlitebrowser/sqlitebrowser#3539]
### What did you do?

Hope the above subject is clear and self-explanatory.

### What did you expect to see?

Hope the above subject is clear and self-explanatory.

### What did you see instead?

Hope the above subject is clear and self-explanatory.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

macOS Ventura

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by linuxguist** [comment]
Thanks for the lightning response ! Yes, I just checked the DB.Browser.for.SQLite-dev-3f7ee2f.dmg as well and the issue is still present, unfortunately. BTW, DB Browser for SQLite is an excellent software and i like it very much.

**Comment by justinclift** [comment]
Thanks.  Both for testing the latest build, and for the compliment.  We do try to get things right. :grin:

**Comment by linuxguist** [comment]
While i wait to see this issue closed, here is some news ( with some background ) , that might cheer your team : After a recent Google Bard query, that got me introduced to sqlitebrowser, especially its CSV file importing capabilities, i got inspired to write about it, in a post on dev.to, to help the youngsters & juniors come to know about it. Please circulate this news as you see fit. Post Location : https://dev.to/linuxguist/learn-sql-quickly-join-data-easily-with-this-simple-method-get-into-11-new-professions--223g

**Comment by linuxguist** [comment]
I just queried Google Bard, to see what helpful solution it offers to this issue and here are its responses : https://g.co/bard/share/9893c67f73dd

Feel free to take your call on this. BTW, i like & appreciate the Dark Theme of the software, as it causes least eye strain and helps in extended work time with it.

**Comment by justinclift** [comment]
Thanks for trying. :smile:

The graphical layer of our application uses the [Qt toolkit](https://www.qt.io), so it'll probably need to be something specific to that instead.

**Comment by linuxguist** [comment]
Thanks for the hint ! Here is the revised bard query and its response : https://g.co/bard/share/addb0160cab6

**Comment by justinclift** [comment]
Cool.  Hopefully someone's interested in getting this fixed and trying that out before it expires. :smile:

**Comment by mgrojo** [comment]
Strange, that shouldn't happen. What we do from our side is to make a copy of the table in two MIME types, one is in plain text (rich format, including colors) and the other in HTML. In the HTML version, we include the colors as displayed in DB4S. For Data Browser, that could involve a lot of conditional formatting specified by the user. In Execute SQL, it will depend on the current theme. Preserving that conditional formatting when pasting is an important feature.

Applications should either take the plain text version, or the HTML version. In the latter, they may choose to respect all the formatting, or strip all or coherent parts of it, like all colors. It seems that Excel for macOS is removing the background color (dark) and keeping the foreground (light). There seems to be the bug, in Excel side. I can't test now on Excel, but on OpenOffice spreadsheet, all the colors are stripped, so it is preserving its color combination. The word processor keeps all the formatting.

 In any case, you as Excel user can choose to paste without any formatting. I think the correct key sequence is <key>Control+V</key> <key>Control</key> <key>A</key>(but you can also do it from the floating tip that appears after Control+V).

**Comment by mgrojo** [comment]
> While i wait to see this issue closed, here is some news ( with some background ) , that might cheer your team : After a recent Google Bard query, that got me introduced to sqlitebrowser, especially its CSV file importing capabilities, i got inspired to write about it, in a post on dev.to, to help the youngsters & juniors come to know about it. Please circulate this news as you see fit. Post Location : https://dev.to/linuxguist/learn-sql-quickly-join-data-easily-with-this-simple-method-get-into-11-new-professions--223g

Added to https://github.com/sqlitebrowser/sqlitebrowser/wiki/Video-tutorials

**Comment by linuxguist** [comment]
Spot on @mgrojo ! Yes, the Excel on MAC is disregarding the Background Color. While, Word & Powerpoint is respecting all of it, on MAC. LibreOffice Calc is pasting the data as Plain Text, so no issues with that.

Paste Special of Excel had three options, with HTML being the default, which is having its problems. Other options like Paste as Unicode Text and Paste as Text are working fine.

I will close this issue as resolved now. Thanks to you & @justinclift for the investigation & help !

BTW, enclosing the Paste Special options of Excel as screenshot here, for the benefit of viewers reading this  : 

[Paste Special](https://i.imgur.com/9xHdYk8.png)
