### ISSUE TITLE
Unable to name fields

### ISSUE THREAD

**Issue by Sanpasqual123** [sqlitebrowser/sqlitebrowser#354]
Version 3.6.99, Qt Version 4.8.5, SQLite Version 3.7.17 OS  Centos 7.2

There is no provision for naming or changing fields.  The database is limited to default field names e.g. field1, field2, etc.

**Comment by justinclift** [comment]
Interesting.  Changing field names works on other OS's, so it sounds like a bug affecting just the build you're using atm.

Did you compile DB4S yourself, or is there a repo you grabbed a prebuilt version from or ?

**Comment by Sanpasqual123** [comment]
Yes, it Is peculiar.  I am able to make entries on a contemporary build under OsX, but not under Centos Linux.  

Yes, I ran the build scripts locally; no error flags during the process.  My local build seemingly supports everything except revision of field names v.v. Importing a database created on a Mac, entering new data, changing old data, outputting to CSV, exporting, all work uneventfully.  

K. Newman

**Comment by glawrence** [comment]
@justinclift I grabbed the very latest from GitHub and built this on my CentOS 7 VM so I could try this out. I did the following:

- create a new database
- create a new table
- click Add Field button
![stage_1](https://cloud.githubusercontent.com/assets/1067355/8144735/c86925d6-11e3-11e5-9947-0bd689e16576.png)
- double-click the field name to edit [note cursor at end]
![stage_2](https://cloud.githubusercontent.com/assets/1067355/8144739/e2850b38-11e3-11e5-8566-a63066255f60.png)
- type "XX" [see it overwrites in black]
![stage_3](https://cloud.githubusercontent.com/assets/1067355/8144743/f944b27e-11e3-11e5-85ca-1f203ace3bf7.png)
- press "Enter" and everything is fine
![stage_4](https://cloud.githubusercontent.com/assets/1067355/8144744/034175b4-11e4-11e5-8be4-2828aac8bbec.png)

So this would seem to be a draw/paint type bug that needs fixing, functionally DB4S works we just need to fix the UI so it is more obvious it is working.

Hope you like my screenshots, I think they help!

**Comment by Sanpasqual123** [comment]
Spot on ... prominent with the Centos build.  Thanks.

**Comment by glawrence** [comment]
Indeed @Sanpasqual123 it is either a CentOS thing or possibly a GNOME/KDE issue. I have just tried on an openSUSE VM and don't see the same issue. With CentOS I have GNOME and with openSUSE I have KDE, so I wonder if the issue is in GNOME compatibility somewhere

**Comment by Sanpasqual123** [comment]
I’m using a Cinnamon shell over GNOME (v.v. GTK3+ based), so yes there could be a source of divergence.

**Comment by justinclift** [comment]
@glawrence Well done.  It seems like bug in maybe the Qt toolkit build on CentOS 7.x then.

Do you have the rpm versions handy?  We can ping the CentOS guys (on IRC and/or mailing list) to see if anyone is already aware of it.  If not, we can file a bug so it can be looked into. :smile:

**Comment by glawrence** [comment]
I have the following installed
```
Name        : qt
Arch        : x86_64
Epoch       : 1
Version     : 4.8.5
Release     : 8.el7
Size        : 17 M
Summary     : Qt toolkit
URL         : http://qt-project.org/

Name        : qt-devel
Arch        : x86_64
Epoch       : 1
Version     : 4.8.5
Release     : 8.el7
Size        : 34 M
Summary     : Development files for the Qt toolkit
URL         : http://qt-project.org/

Name        : qt-settings
Arch        : noarch
Version     : 19
Release     : 23.5.el7
Size        : 1.8 k
Summary     : Configuration files for Qt
URL         : http://fedorahosted.org/kde-settings

Name        : qt-x11
Arch        : x86_64
Epoch       : 1
Version     : 4.8.5
Release     : 8.el7
Size        : 34 M
Summary     : Qt GUI-related libraries
URL         : http://qt-project.org/
```
Does that help? Not sure it is quite what you asked for but "feels" right.

**Comment by justinclift** [comment]
Yep, that's what I asked for.  I'll ping the CentOS guys in a bit, to see if it's a known issue. :smile:

**Comment by glawrence** [comment]
Great, thanks

**Comment by justinclift** [comment]
Oops.  The first email I sent them, I did from the wrong email address and it never got through.  I've just emailed them from the correct email address, and it's on the centos-devel mailing list now:

&nbsp; &nbsp; http://lists.centos.org/pipermail/centos-devel/2015-June/013551.html

Lets see if someone there has ideas...

**Comment by justinclift** [comment]
@Sanpasqual123 @glawrence Looking back over some of our older issues which we've not followed up on... do either of you have a machine or VM handy you could test this on again with the later code?  Both us and Qt have had new releases since this was reported last year, so it's worth checking. :smile:

**Comment by MKleusberg** [comment]
Any updates on this? From what I can tell this was tested using Qt4 and as it might be a Qt thing, it might be worth checking this out with Qt5.

**Comment by justinclift** [comment]
Closing this due to lack of response.  It's pretty likely (but not guaranteed) to not be a problem with our upcoming release due to Qt5.

If it does still happen, this issue is welcome to be reopened. :smile:
