### ISSUE TITLE
[Bug]: Foreign key issue

### ISSUE THREAD

**Issue by midoragh** [sqlitebrowser/sqlitebrowser#3552]
### What did you do?

I'm using EAN (13 digits) as key in one table and reference it in an other table. This works in general. But there are EANs starting with 00. Trying to add them as reference fails with "FOREIGN KEY constraint fails". Even selecting the value starting with 00 from the popup fails with the same error. But entering the reference without 00 works.

### What did you expect to see?

Keys should allow 00 at the the start.

### What did you see instead?

Error

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by midoragh** [comment]
I had to use TEXT because not all products provide EANs. I will check the latest build and report the results.

CREATE TABLE "Products" (
	"Id"	TEXT UNIQUE,
	"Manufacturer"	TEXT,
	"Name"	TEXT,
	"Category"	TEXT,
	"Description"	TEXT,
	"Color"	TEXT,
	"Width"	REAL,
	"Depth"	REAL,
	"Height"	REAL,
	"PriceCurrency"	TEXT DEFAULT 'CHF',
	"PriceValue"	REAL,
	"PriceDate"	TEXT,
	"Photo"	BLOB,
	"Remark"	TEXT
)
CREATE TABLE "Purchases" (
	"Added"	TEXT,
	"Removed"	TEXT,
	"Dealer"	TEXT,
	"DealerLocation"	TEXT,
	"Product"	INTEGER,
	"Currency"	TEXT,
	"Price"	REAL,
	"Location"	TEXT,
	"Remarks"	TEXT,
	FOREIGN KEY("Product") REFERENCES "Products"("Id")
)

**Comment by midoragh** [comment]
Same issue with 3.13.99 (Jan 14 2024)

**Comment by justinclift** [comment]
Hmmm, nothing is springing to mind as obviously wrong there.  It'll probably turn out to be something super simple though.

As a next step, probably best to ask the same question on the SQLite Forum directly: https://sqlite.org/forum/forum

While we have some knowledgable people amongst our members here, the SQLite Forum are the literal people who wrote SQLite.  They'll know the answer. :grin:

**Comment by justinclift** [comment]
Oh actually... maybe try making the `Purchases.Product` field into TEXT as well.  That way both fields are the same data type.  That might all you need to change. :smile:

**Comment by midoragh** [comment]
You are right, qualify this as user bug. I guess I started with integer in both tables and changed it later to text in Products because of products without EAN. And because I could enter these text references in the integer field in the Purchases table, I forgot to change the type in Purchases.
I'm not sure where it is done (sqlite or dbbrowser) but maybe entries starting with zeros should be interpreted as of type text and not as integer which seems to remove the zeros.

**Comment by midoragh** [comment]
Thanks for support.

**Comment by justinclift** [comment]
You're welcome. :smile:
