### ISSUE TITLE
[Bug]: no such function: unixepoch

### ISSUE THREAD

**Issue by mriveras** [sqlitebrowser/sqlitebrowser#3553]
### What did you do?

Running a query.
SELECT UNIXEPOCH()

### What did you expect to see?

current UNIXTIMESTAMP

### What did you see instead?

An error. 
Execution finished with errors.
Result: no such function: UNIXEPOCH
At line 13:
SELECT UNIXEPOCH()

### DB4S Version

3.13.0-rc1

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Pro

### Relevant log output

```shell
SELECT UNIXEPOCH()

Execution finished with errors.
Result: no such function: UNIXEPOCH
At line 13:
SELECT UNIXEPOCH()
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ahhh.  That'll probably mean the version of SQLite included with your version of the GUI is prior to version 3.38.0.

If you grab our latest development build, it'll work.  We're near to a new major release too, so the development builds are presently pretty solid. :smile:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

**Comment by justinclift** [comment]
@mriveras How'd you go with this? :smile:

**Comment by mriveras** [comment]
Hi @justinclift 
Thanks for your quick reply....

All good now. Thanks a lot. :-)

**Comment by justinclift** [comment]
Awesome. :smile:
