### ISSUE TITLE
[Bug]: Copy as SQL feature will copy NULL string value as empty string

### ISSUE THREAD

**Issue by yccheok** [sqlitebrowser/sqlitebrowser#3557]
### What did you do?

I have 2 rows.

The column is defined as "searched_string" TEXT

one is with row is with empty value

another row is with NULL value

When I right click the to selected row, and select "Copy as SQL", the NULL value is copied as empty string value. Please refer to the screenhots.

![Screenshot 2024-01-24 at 11 46 57 AM](https://github.com/sqlitebrowser/sqlitebrowser/assets/308276/0f81c4df-5d65-4bc7-a2d1-4483584d4d23)

![Screenshot 2024-01-24 at 11 47 28 AM](https://github.com/sqlitebrowser/sqlitebrowser/assets/308276/339d65bf-d6bc-4eb6-9e93-3ba63592ccb6)

![Screenshot 2024-01-24 at 11 48 00 AM](https://github.com/sqlitebrowser/sqlitebrowser/assets/308276/05432e1b-aac7-490c-9eeb-3020b944812e)

### What did you expect to see?

Copy as SQL will copy the NULL value as `NULL` instead of `''`

### What did you see instead?

Copy as SQL is copying the NULL value as `''`

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

Sonoma 14.0

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Hmmm, I *think* we did some work in that area a while back, but I don't remember the details.

Um, would you be ok to try with our most recent development build and see if that does it better?

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Note - We've been preparing for a new major release for quite a while, so those development builds are generally pretty good. :smile:

**Comment by mgrojo** [comment]
I confirm this is fixed in the development build.
