### ISSUE TITLE
View Big 

### ISSUE THREAD

**Issue by VasKing** [sqlitebrowser/sqlitebrowser#3559]
### What did you do?

Disconnect my laptop from my big desktop monitor and then reconnect it.

### What did you expect to see?

Normal view size.

### What did you see instead?

Very big view size.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
And if you restart DB4S, does it appear normal again?
This is common in Windows, as multi-monitor and differing resolutions causes it to cough and splutter sometimes.

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
