### ISSUE TITLE
[Bug]:  On open version check error display

### ISSUE THREAD

**Issue by tghoward** [sqlitebrowser/sqlitebrowser#3560]
### What did you do?

After upgrading to 3.12.2, the error display for institutionally blocked access to download.sqlitebrowser.org/currentrelease now has lots of excess html. 
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/6129193/fbcea31d-17a2-422b-84d3-0da9d803cfd9)

### What did you expect to see?

Historically there was typically a much smaller, compact error message about not being able to contact the site. 

### What did you see instead?

Top of image pasted above. I can't seem to select the text, nor find a log file. I'll paste a screen cap of the full window here. 
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/6129193/40e2a659-2712-43ae-b365-7e25b2bc6396)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Its kinda helpful though.
The HTML returned is from you, not us.  You're (your organisation, firewall, et al) is blocking access to that URL.  DB4S is accessing it and getting an error.  The reply from the server contains the HTML.  

If you want to prevent these messages, you can turn off the 'Automatic check' in the preferences.

**Comment by tghoward** [comment]
Ah, thanks. I had looked for that setting but hadn't found it. I've turned it off. (Preferences--General--Automatic Updates) 

I knew it was from me, but DB Browser handled it a bit more cleanly in earlier iterations. Thanks for the reply. All set here.

**Comment by chrisjlocke** [comment]
Glad you got it resolved.  Thanks for confirming.
