### ISSUE TITLE
[Feature]: Add foreign key constraint

### ISSUE THREAD

**Issue by fverneau** [sqlitebrowser/sqlitebrowser#3561]
### Describe the new feature

Add a foreign key constraint.
Currently, it is possible to indicate one or more fields as a foreign key, but it is impossible to indicate the table and the primary key field(s).

For example :
CREATE TABLE album(
  albumartist TEXT,
  albumname TEXT,
  albumcover BINARY,
  PRIMARY KEY(albumartist, albumname)
);

CREATE TABLE song(
  songid     INTEGER,
  songartist TEXT,
  songalbum TEXT,
  songname   TEXT,
  FOREIGN KEY(songartist, songalbum) REFERENCES **album(albumartist, albumname)**
);

For now, the SQL stops at REFERENCES

### Do you have a screenshot? Please add screenshots to help explain your idea.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/6473514/1755d9cb-632d-4836-ad8e-27e0f65b4194)

**Comment by chrisjlocke** [comment]
This is a quirk with the GUI.  Unfortunately it isn't intuitive what exactly to do.
Check out the comment to the same issue in this topic.
https://github.com/sqlitebrowser/sqlitebrowser/issues/3420

Let me know if it works.

**Comment by fverneau** [comment]
Yes, it works.
I wouldn't have found it on my own. It isn't intuitive.
Thank you very much.

**Comment by chrisjlocke** [comment]
Thanks for confirming.
I'll add a wiki article but hopefully the GUI will be updated at some point.
