### ISSUE TITLE
[Bug]: Nightly and AppImage both show sqlite version 3.15.2

### ISSUE THREAD

**Issue by rasa** [sqlitebrowser/sqlitebrowser#3565]
### What did you do?

On Ubuntu 23.10 (Mantic), I installed the latest nightly from https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing
```bash
$ dpkg -l | grep sqlitebrowser
ii  sqlitebrowser 3.13.0-0~3392~202401150232~ubuntu23.10.1 amd64 GUI editor for SQLite databases
$ sqlitebrowser --version
DB Browser for SQLite Version 3.13.99 (Jan 15 2024)
Last commit hash when built: Unknown
Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.15.10
SQLCipher Version 3.4.1 (based on SQLite 3.42.0).
```
but the version is 3.15.2, even though the about screen shows 3.42.0:
![Screenshot_20240206_172254](https://github.com/sqlitebrowser/sqlitebrowser/assets/220772/630de2b1-7d56-4214-8c6a-087aae39014c)

I then 'apt purged' that version, and installed the latest AppImage ([DB.Browser.for.SQLite-dev-7a31ef9-x86.64.AppImage](https://github.com/sqlitebrowser/sqlitebrowser/releases/download/continuous/DB.Browser.for.SQLite-dev-7a31ef9-x86.64.AppImage)), but now *both* versions are 3.15.2:
![Screenshot_20240206_172036](https://github.com/sqlitebrowser/sqlitebrowser/assets/220772/7d94048d-2715-4c2b-886e-ec5dc5690759)

The only sqlite related packages installed are:
```bash
$ dpkg -l | grep sqlite
ii  libqt5sql5-sqlite:amd64                                  5.15.10+dfsg-3                                         amd64        Qt 5 SQLite 3 database driver
ii  libsqlite3-0:amd64                                       3.44.0-0-20359~202311021114~202311041424~ubuntu23.10.1 amd64        SQLite 3 shared library
ii  libsqlite3-dev:amd64                                     3.44.0-0-20359~202311021114~202311041424~ubuntu23.10.1 amd64        SQLite 3 development files
ii  sqlite3                                                  3.44.0-0-20359~202311021114~202311041424~ubuntu23.10.1 amd64        Command line interface for SQLite 3
ii  sqlitebrowser                                            3.13.0-0~3392~202401150232~ubuntu23.10.1               amd64        GUI editor for SQLite databases
```
I've read other related bug reports, but they were solved by running the latest version. In my case, that's not the key.

What am I doing wrong?

### What did you expect to see?

3.42+

### What did you see instead?

3.15.2

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 23.10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
Thanks for the report, I checked and there was a bug that was reversing the name during the upload process.
I've fixed it now and are waiting for CI work done: https://github.com/sqlitebrowser/sqlitebrowser/actions/runs/7809010348

**Comment by rasa** [comment]
The AppImage in [7809010348 ](https://github.com/sqlitebrowser/sqlitebrowser/actions/runs/7809010348) works!
![Screenshot_20240206_182932](https://github.com/sqlitebrowser/sqlitebrowser/assets/220772/8a66f54a-08ed-476c-8f8a-db0dd8517288)
Thanks so much for the quick fix!
Will the PPA builds fix themselves once they are rebuilt?

**Comment by lucydodo** [comment]
The truth is, I don't really know how PPA repositories work. But I know that @deepsidhu1313 is manaing the PPA repository. :)

**Comment by chrisjlocke** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/ae3d0643-e552-4157-9bdf-5eb1f70674ee)

Looks like the process we use to build the images deleted the tag.  Maybe it expired.

The last appImage is from 29 Dec.  Any good?
https://github.com/sqlitebrowser/sqlitebrowser/releases/download/83649a3-3357/DB.Browser.for.SQLite-dev-83649a3-x86.64.AppImage

Once another commit occurs or the build process kicks in, the above links you've posted will spring back into life.  Then get deleted again.  Etc.

**Comment by lucydodo** [comment]
For note: I think there was one step at the end of the build that failed, so it assumed the action failed and deleted the release. I've fixed that issue, so it should probably work in theory. I'm currently waiting for the CI job to finish.

**Comment by lucydodo** [comment]
Well, this issue seems to have been resolved, so I'll close it again. Anyone can reopen it at any time if needed.
