### ISSUE TITLE
Can't open a file by double clicking

### ISSUE THREAD

**Issue by LLambertRGi** [sqlitebrowser/sqlitebrowser#357]
Prior to version 3.6.0 windows allowed me to assign the ".gpkg" (GeoSpatial format built on a SQLite file) extension to be opened with sqlitebrowser.  With versions 3.6.0 and 3.7.0, Windows won't allow me to associate the file extension with sqlitebrowser.exe

**Comment by justinclift** [comment]
Ahhh, this sounds like the problem that happens when going from a 32-bit to 64-bit install.

Does the fix here work for you?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

**Comment by LLambertRGi** [comment]
That was it exactly. I don't know how that didn't come up in my search for a fix. I greatly appreciate your prompt and precise reply :)

**Comment by glawrence** [comment]
@LLambertRGi we're always happy to help! Thanks for using DB4S.
