### ISSUE TITLE
[Bug]: Some links in About window have http protocol rather than https

### ISSUE THREAD

**Issue by rafrafek** [sqlitebrowser/sqlitebrowser#3571]
### What did you do?

I opened the About window.

### What did you expect to see?

All the links use https 😊

### What did you see instead?

Some of the links use http:

<img width="765" alt="image" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/23004737/27be1de1-1c2f-4cad-81fe-f75b9ec73e7f">

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Good point.  We should update that for the links that do have https ones available.

Hmmm, want to make a PR with that change? :smile:

**Comment by rafrafek** [comment]
Yep, let me try.

**Comment by rafrafek** [comment]
http://www.gnu.org/licenses/gpl.html redirects to https://www.gnu.org/licenses/gpl-3.0.html

Should I just change `http` to `https` or should I replace the link?

**Comment by rafrafek** [comment]
Why do the translation files have TypeScript file extension (.ts) rather than the actual type (xml)? It makes my editor crazy.

**Comment by justinclift** [comment]
> Why do the translation files have TypeScript file extension (.ts)

Pretty sure that extension has been .ts for many years before TypeScript was invented. :wink:

**Comment by justinclift** [comment]
> Should I just change http to https or should I replace the link?

I'd just change http to https where that works.  ie where the new link is valid

If there's a situation where the new link *isn't* valid, then changing the complete url is probably the next step. :smile:

**Comment by rafrafek** [comment]
I'm getting 404 for:

http://qt-project.org/doc/qt-5/licensing.html

and

http://www.famfamfam.com/lab/icons/silk/

**Comment by lucydodo** [comment]
Good point. Thank you for checking it out.

Qt License can be replaced with the following link: https://doc.qt.io/qt-5/licensing.html
Also, Silk Icon Set can be replaced with the following link: https://github.com/markjames/famfamfam-silk-icons

**Comment by rafrafek** [comment]
http://qt-project.org/doc/qt-5/licensing.html was already changed on master. But it was changed to

https://qt-project.org/doc/qt-5/licensing.html

which also gives me 404, so I've updated it to https://doc.qt.io/qt-5/licensing.html

**Comment by rafrafek** [comment]
http://www.famfamfam.com/lab/icons/silk/ is not present in all translation files:

<img width="254" alt="image" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/23004737/af9a679f-2710-4804-a32d-349e6628d634">

**Comment by justinclift** [comment]
Ahhh.  Hadn't thought of that.  I guess we'll figure it out more the next time our translators look at it. :smile:
