### ISSUE TITLE
[Feature]: Option to change # of recently-used files list

### ISSUE THREAD

**Issue by PJOttCanHome** [sqlitebrowser/sqlitebrowser#3576]
### Describe the new feature

I have more than 5 projects that use SQLite databases. The Preferences page General tab should have an option to change the max # of recently-used files (5 - 15).

OR, just increase the max internally to 15 or 25 or 732 (yes, that was just me being silly).

Very cool and useful product, though.

**Comment by lucydodo** [comment]
Hi, @PJOttCanHome What version are you using now?
The feature you mentioned have already been implemented.
However, it's not yet in the stable version, so you'll need to use the latest continuous or nightly build.

You can download them from the following links:
- Continuous: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
- Nightly: https://nightlies.sqlitebrowser.org/latest

and then, you can adjust it in the 'Preferences' as shown in the screenshot below.
<img width="868" alt="Screenshot 2024-03-04 at 10 05 47" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/60d4f0de-f9b0-4040-aae9-eb4ba2d7c9ce">

**Comment by chrisjlocke** [comment]
An alternative is to have a folder full of just shortcuts to databases you use.  Easier to manage, and transportable.  I tend to work on several databases per project, so this sometimes makes more sense.

**Comment by PJOttCanHome** [comment]
Thanks for the responses. Chrisjlocke, that's a decent work-around

**Comment by lucydodo** [comment]
Cool, does the solve the issue? Can we close the issue now?
