### ISSUE TITLE
I can't seem to open an encrypted database on my mac

### ISSUE THREAD

**Issue by MaxPower9** [sqlitebrowser/sqlitebrowser#358]
I've used the SQLCipher instructions to allow my iOS app to create an encrypted database.  When I try to open it in sqlitebrowser I just continuously get prompted to enter the password.  I'm not sure what I'm doing wrong.  Any ideas?

**Comment by justinclift** [comment]
Interesting.  Do you know if the iOS app uses SQLCipher to do the encryption?

If it definitely does, then it's probably something to do with needing to figure out the matching page size.  If the page size doesn't match when opening the database, DB4S doesn't get a valid database to use so keeps prompting. (or it could be a bug in our SQLCipher handing or similar, which we'll need to investigate)

**Comment by MaxPower9** [comment]
It does use SQLCipher to do the encryption, what i don't know is what the page size is.  I wrote the app using the instructions on the SQLCipher website, but it doesn't say anything about what page size it's using.  What can I do to start investigating?

**Comment by justinclift** [comment]
Ahhh, this shouldn't be too hard to figure out then. :smile:

What you should probably do is jump on the SQLCipher forum here, and ask what the default page size would be when using their instructions:

&nbsp; &nbsp; https://discuss.zetetic.net/c/sqlcipher

The SQLCipher people are pretty responsive + helpful (we've asked questions there too :wink:), so it's very likely they'll get you up and running. :smile:

**Comment by justinclift** [comment]
Hmmm, I've just noticed there's a newer version of SQLCipher out than what we included with our OSX builds.  I'm not sure if that's the cause of the problem, but it's worth keeping in mind.

In the meantime, I'll look into getting the newer SQLCipher release into OSX Homebrew, so we can use it in our nightly builds and future releases.

**Comment by justinclift** [comment]
For reference, this is the PR for updating SQLCipher to v3.3.0 in Homebrew: https://github.com/Homebrew/homebrew/pull/40841

**Comment by justinclift** [comment]
@MaxPower9 Looking through this, the default page size seems to be 1024:

&nbsp; &nbsp; https://discuss.zetetic.net/t/sqlcipher-support-added-to-db-browser-for-sqlite/243/11

If you're trying that and it isn't working... then lets see what happens with a version of DB4S using the latest SQLCipher (building one now).

**Comment by justinclift** [comment]
This might help:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/onceoffs/sqlitebrowser-sqlcipher_201506172157.dmg

It's a build using our very latest code base, plus with SQLCipher 3.3.0.

**Comment by MaxPower9** [comment]
Thanks for your help, I found the problem.  You mentioned building sqlitebrowser with a newer version of SQLCipher, well that's what I needed to do.  My iOS app was using an old version of SQLCipher.  Once I updated SQLCipher to the latest from github, I could read my databases in sqlitebrowser.  I even tested with sqlitebrowser 3.7.0 and it worked great.  Thanks for your help!

**Comment by justinclift** [comment]
You're welcome.  Glad it was a fairly easy fix (not everything is). :wink:
