### ISSUE TITLE
[Bug]: sqlcipher.dll is broken in nightly installer

### ISSUE THREAD

**Issue by darklie** [sqlitebrowser/sqlitebrowser#3582]
### What did you do?

To encrypt plain sqlite file, I clicked [Tools] on menu bar and [Set Encryption] on Tools menu. Then enter passphrase on the popup and click OK button.

### What did you expect to see?

I expected to encypt the plain sqlite file.

### What did you see instead?

This dialog appears.
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/12250058/beb0b32d-d5a7-40e7-9d83-21ec521b0d02)

To replace sqlcipher.dll with my own builds, it moves fine.

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Oh, that's interesting.  Thanks for letting us know @darklie. :smile:

@lucydodo Sounds like this will be of interest to you. :smile:

**Comment by lucydodo** [comment]
Thank you for reporting the issue. Upon checking the logs, it appears that the SQLCipher library build is not functioning correctly. As I am currently unavailable due to personal schedule, I will investigate the matter further tomorrow.

> https://github.com/sqlitebrowser/sqlitebrowser/actions/runs/8180582970/job/22368898623#step:7:813

**Comment by lucydodo** [comment]
@justinclift Additionally, we're currently relying on GitHub Actions to build for our next release,
so I add the 'release blocker' label for the same reason.

**Comment by justinclift** [comment]
Cool, thanks for taking a look @lucydodo. :smile:

**Comment by lucydodo** [comment]
I've identified the cause and fixed it (at least on my local VM). However, this workaround has been problematic when used in GitHub Actions in the past, so I'll be testing it internally before pushing it upstream.

@justinclift The thing is, I need access to our runner for internal testing and it doesn't seem to be working, 
Can you check it out if you have a moment? :)

**Comment by justinclift** [comment]
> I need access to our runner for internal testing and it doesn't seem to be working,

@lucydodo Looking into it now.

**Comment by justinclift** [comment]
@lucydodo Both the M1 macOS VM and the Windows VM should be accessible now.  The macOS one looked ok when I checked, however the Windows one had a problem with autossh.

Looks like autossh hit a problem at some point while it was running (router reboot maybe?), and after it couldn't re-connect 5 times it just stopped re-trying.

To hopefully fix that for the future, I've just added `Restart=always` to the autossh systemd unit file.  In theory that should mean it never gives up trying to re-connect.

**Comment by lucydodo** [comment]
Thank you for your confirmation, I can connect runner now.
Let's run some test and try to resolve the issue.

**Comment by lucydodo** [comment]
I have pushed the patch to the upstream.
I have confirmed that is works in my environment*.  [The CI is now live](https://github.com/sqlitebrowser/sqlitebrowser/actions/runs/8211101171), allowing you to test it yourself once finish the CI process,
If you have the time,we could appreciate it if you could test it. Here's the link for download continuous build:
https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Thank you again for bringing this important issue to our attention for our next release. :)

>*: Windows 11 Pro Version 23H2 (OS Build: 22631.3155)

**Comment by darklie** [comment]
Thank you for @lucydodo and @justinclift !
I tested it this ( https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous ) build and it moves fine.
I appreciate your help.

**Comment by justinclift** [comment]
Awesome. :smile:
