### ISSUE TITLE
how to export to db extension?

### ISSUE THREAD

**Issue by idomintz12** [sqlitebrowser/sqlitebrowser#359]
I have a file with a ".db" extension in android and I need to edit some data in that file and then export it back to ".db" extension but the only extension options are HTML, PDF, JSON, SQL or XML

How do I export the file back to its original extension and format in ".db"?

**Comment by justinclift** [comment]
When you say the only extension options are "HTML, PDF, JSON, SQL or XML", where are you seeing that?

In theory, you should be able to open the .db file directly in DB4S, then save back to it directly.  (does that help? :smile:)

**Comment by idomintz12** [comment]
Hi Justin thanks a lot for the insight!

I see the export options when I click "Export the database" - here's a screenshot

http://i.imgur.com/6t6brlp.png

How do I save the changes directly to the file?? (without exporting to a new file) That would be best!

I apologize for the dumb question but, what is DB4S?? Is it a ".db" file editor? I've googled it and pulled nothing (I'm new to databases btw!)

**Comment by justinclift** [comment]
Ahhhh, the screenshot you're showing is for SQLiteStudio, which is not us.  These are the people you want to ask questions about it: :smile:

&nbsp; &nbsp; http://sqlitestudio.pl/

"DB4S" is the acronym we use for our software - DB Browser for SQLite - as it's a pita to type out the full name each time. :wink:

**Comment by idomintz12** [comment]
Ooopsie!! Sorry xD
Well I just downloaded the zip and trying to make this DB4S work but there's no exe to launch the program!! How do get this thing to work? I can't wait to try it!

**Comment by glawrence** [comment]
Hi @idomintz12 if you want to try DB4S then I suggest you go to http://sqlitebrowser.org/ and download the installer. There is a nightly build but I would recommend starting with the 3.7.0 release which was done a few days ago. Alternatively go to https://github.com/sqlitebrowser/sqlitebrowser/releases and download from there, same files just a different view.

**Comment by justinclift** [comment]
Yeah.  Try this installer, as it's very likely to work for you:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.7.0/sqlitebrowser-3.7.0-win32.exe

**Comment by idomintz12** [comment]
Thanks so much guys it worked!

**Comment by glawrence** [comment]
Great news @idomintz12 we hope you enjoy DB4S
