### ISSUE TITLE
[Bug]: Timezone / UTC

### ISSUE THREAD

**Issue by alexanderavans** [sqlitebrowser/sqlitebrowser#3591]
### What did you do?

I tried inserting a row where one of the columns is assigned DEFAULT CURRENT_DATE.
After inserting the inserted row shows yesterday's date. I'm in UTC +1 myself and it is just a little over twelve midnight. 

### What did you expect to see?

I expected to see 23-3-2024 for the inserted date

### What did you see instead?

I got 22-3-2024 for the inserted date

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Relevant log output

```shell
-- In regel 1:
insert into `order` (userID,addressID) values (2,4)
-- Resultaat: Opdracht succesvol uitgevoerd. Duurde 0ms, 1 records getroffen


CREATE TABLE `Order` (
  orderID INTEGER PRIMARY KEY,
  orderDate DATE DEFAULT CURRENT_DATE,
  userID INTEGER,
  addressID INTEGER,
  orderStatus VARCHAR (20) NOT NULL DEFAULT 'awaiting payment',
  FOREIGN KEY (userID) REFERENCES `User`(userID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (addressID) REFERENCES `Address`(addressID) ON DELETE CASCADE ON UPDATE CASCADE
  )
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/95c3a5a1-2a13-42d7-9a81-2dee69d83f31)

If you type ```select CURRENT_TIME``` what result do you get?
sqlite would use the OS time .. what timezone is the OS in?
I've tried this on Linux and Windows, and get the same result on both.

**Comment by chrisjlocke** [comment]
Aah, scrap that.  Reading the docs, it says 'then the value used in the new row is a text representation of the current UTC date and/or time'.  So if you're UTC+1, then an hour back is right.

**Comment by alexanderavans** [comment]
Thanks. Didn't find that. It's a bit hidden away.
