### ISSUE TITLE
[Bug] Filtering by UTF8 characters not working

### ISSUE THREAD

**Issue by alirezaaa** [sqlitebrowser/sqlitebrowser#360]
I cannot filter rows by Persian (UTF8) characters.

**Comment by justinclift** [comment]
Which version of DB4S is this happening with, and what operating system is this on? :smile:

**Comment by MKleusberg** [comment]
Just testes it and It seems to work for me... The default filter behaviour is to only search for exact matches, so you probably need to put '%' characters around your search term but then it should work even for characters in a different form when they are connected:
![persian](https://cloud.githubusercontent.com/assets/3153504/8241425/88bc1ad6-1609-11e5-8ac7-45742a82dae9.png)

**Comment by alirezaaa** [comment]
Thanks @MKleusberg . I didn't know that is exact filtering. Yes filtering with `%` character works for me too.

**Comment by MKleusberg** [comment]
Cool! Glad this works :smiley: By the way, if you want to read about the fancier filter operations, we have prepared a wiki page explaining them: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters
