### ISSUE TITLE
[Bug]: Assertion [cpMax <= pdoc->Length()] failed at ../scintilla/src/Editor.cpp 6096

### ISSUE THREAD

**Issue by archqt** [sqlitebrowser/sqlitebrowser#3609]
### What did you do?

Open a db file, then do simply this
select * from yourTable
Where yourTable.id>5
Execute the sentence, then remove the >5
select * from yourTable
Where yourTable.id

Then execute and it crashes

### What did you expect to see?

It crashes

### What did you see instead?

It crashes

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### Relevant log output

```shell
Assertion [cpMax <= pdoc->Length()] failed at ../scintilla/src/Editor.cpp 6096

It is written as closed in the previous report
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
What version of Linux? 
Can you build from the latest source at all? Or there is an appimage you can try. There has been some updates to 3.12.2 which may have fixed this.

**Comment by archqt** [comment]
I tried it on several linux version. And on my computer archlinux which is updated, SqliteBrowser 3.12.2 it still crashes (Qt 5.15.6)
