### ISSUE TITLE
Installation under Windows 7

### ISSUE THREAD

**Issue by wschaefer11** [sqlitebrowser/sqlitebrowser#361]
Hi,
I have a problem running sqlitebrowser on a Windows 7 (Home Premium SP1 32-bit) machine. Installation runs fine, but DB Browser (Version 3.7.0) does not start. C++ redist (x86, version 10 and version 12) and .NET 4.5.2 are installed. The error message specifies Qt5Core.dll, Version 5.4.1.0 as the problem.
Would appreciate Help.

Thanks, Walter

**Comment by justinclift** [comment]
Interesting.  Just to check (to be safe)... you're using the 32-bit download, not the 64-bit one yeah? :wink:

If so, would you be ok to screenshot the error message and paste it into this issue?  It would be useful to know what the full error message is regarding Qt5Core.dll. :smile:

**Comment by wschaefer11** [comment]
yes, I use the 32-bit download. Will paste screenshots.

Thanks, Walter

Am 19.06.2015 um 12:16 schrieb Justin Clift:

**Comment by wschaefer11** [comment]
Here are screenshots from the error message

![db-broeser-1](https://cloud.githubusercontent.com/assets/12964920/8251627/75a3c79e-167e-11e5-99bf-9c8ec226b5ee.jpg)
![db-broeser-2](https://cloud.githubusercontent.com/assets/12964920/8251638/8a0102a6-167e-11e5-9418-6202b583d98a.jpg)

**Comment by justinclift** [comment]
Interesting.  Have you tried older versions of our application?  (I'm wondering if the problem started with release 3.7.0, or if it's existed for older versions too).

If you just need "something to work", then try the latest nightly build here (uncompress it with [7-zip](http://www.7-zip.org)):

&nbsp; &nbsp; http://rp.oldsch00l.com/sqlitebrowser/

That uses our old Windows build process, which is likely to avoid the problem you're hitting.

**Comment by wschaefer11** [comment]
I have tried 3.6.0v3 with the same result. Will go back to older versions to test and also use the latest build.
Thx, Walter

**Comment by wschaefer11** [comment]
Just tried version 3.5.1  -  works without problems.

**Comment by justinclift** [comment]
Cool. :smile:

Both 3.5.1 and our nightly Windows builds use a "static build" process.  The nightly build one should be better for you, since it's like 3.5.1 + lots of bug fixes. :grinning:

**Comment by wschaefer11** [comment]
Great, thanks for your help!
Regards, Walter

**Comment by glawrence** [comment]
@justinclift do you think this means we still have Windows deploy/install issues?

**Comment by justinclift** [comment]
@glawrence It's possible.  It could be a once-off too, but it's hard to tell.  The error message in the screenshot above didn't really show any smoking gun. :frowning: 

I guess we'll just need to wait and see... :wink:

**Comment by rp-** [comment]
if this is the only case of such a problem, I would guess there is a problem with the users machine, but its not really possible to tell from the screenshots, maybe some wrong .dll gets loaded.
