### ISSUE TITLE
[Bug]:  creation of new db file upon attach of non-existing file fails.

### ISSUE THREAD

**Issue by Moaneschien** [sqlitebrowser/sqlitebrowser#3612]
### What did you do?

`ATTACH "cpy.db3" AS new;`
attach a database, where the to be attached database-file does not exist jet, fails. 

### What did you expect to see?

I expected the file to be created as it happens from `SQLite.exe`.

### What did you see instead?

```
14) os_win.c:51526: (2) winOpen(C:\Users\...\Documents\db\DataExchangeFormat\cpy.db3) - The system cannot find the file specified.
(14) cannot open file at line 51527 of [d8cd6d49b4]
(14) statement aborts at 4: [ATTACH "cpy.db3" AS new;] unable to open database: cpy.db3
```

Win 11
DB Browser for SQLite Version 3.13.99 (Mar 26 2024)
Last commit hash when built: 3e7dd41

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

11

### Relevant log output

```shell
14) os_win.c:51526: (2) winOpen(C:\Users\...\Documents\db\DataExchangeFormat\cpy.db3) - The system cannot find the file specified.
(14) cannot open file at line 51527 of [d8cd6d49b4]
(14) statement aborts at 4: [ATTACH "cpy.db3" AS new;] unable to open database: cpy.db3
```
```


### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
I don't think its a bug if it was never designed to do that.  
The proper method of attaching databases is via the 'File' and 'Attach' menu option.
Using that menu option requires an existing file.
DB4S isn't a 'like for like' replacement for sqlite3.exe.
