### ISSUE TITLE
[Feature]: "Filter in any column" should only filter in '__rowid__' is visible

### ISSUE THREAD

**Issue by midoragh** [sqlitebrowser/sqlitebrowser#3613]
### Describe the new feature

"Filter in any column" should only filter in '__rowid__' is visible.
In the moment a '__rowid__' filter is always included to the list of filters in the SELECT command.
This may provide unexpected results if the '__rowid__' matches the selected filter.

**Comment by midoragh** [comment]
Maybe a "Filter only visible columns" checkbox would be an other solution.

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/684b8904-b4bb-4626-8b9f-580947c4c3a1)

This doesn't occur for me.
row_id 6 isn't showing.

**Comment by chrisjlocke** [comment]
_rowid_ is an alias for the primary key, so is the (well, usually...) the first field in the table.  So this is by design.  'any column' would include the primary key, which is normally visible.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/ddbc2a5c-addd-4f35-8ae5-bcc9e693d4ce)

So my first field here is 'key' which is an integer primary key.  Its also _rowid_ .. same field.  If I change key to 9, the _rowid_ will be 9.  If I change _rowid_ to 65, key will be 65.  They're the same field.

**Comment by midoragh** [comment]
Tested DB Browser for SQLite Version 3.13.99 (Mar 6 2024)

Last commit hash when built: 80e6f28


Built for x86_64-little_endian-llp64, running on x86_64

Qt Version 5.15.2

SQLite Version 3.45.1.


The log shows

SELECT "_rowid_",* FROM "main"."Products" WHERE ("_rowid_" LIKE '%123%' ESCAPE '\' OR "Key" LIKE '%123%' ESCAPE '\' OR "Manufacturer" LIKE '%123%' ESCAPE '\' OR "ProductId" LIKE '%123%' ESCAPE '\' OR "ProductName" LIKE '%123%' ESCAPE '\' OR "Category" LIKE '%123%' ESCAPE '\' OR "Description" LIKE '%123%' ESCAPE '\' OR "Color" LIKE '%123%' ESCAPE '\' OR "Width" LIKE '%123%' ESCAPE '\' OR "Depth" LIKE '%123%' ESCAPE '\' OR "Height" LIKE '%123%' ESCAPE '\' OR "PriceCurrency" LIKE '%123%' ESCAPE '\' OR "PriceValue" LIKE '%123%' ESCAPE '\' OR "PriceDate" LIKE '%123%' ESCAPE '\' OR "Photo" LIKE '%123%' ESCAPE '\' OR "Remark" LIKE '%123%' ESCAPE '\') ORDER BY "_rowid_" DESC LIMIT 49999 OFFSET 0;

CREATE TABLE "Products" (
    "Key"    TEXT UNIQUE,
    "Manufacturer"    TEXT,
    "ProductId"    TEXT,
    "ProductName"    TEXT,
    "Category"    TEXT,
    "Description"    TEXT,
    "Color"    TEXT,
    "Width"    REAL,
    "Depth"    REAL,
    "Height"    REAL,
    "PriceCurrency"    TEXT DEFAULT 'CHF',
    "PriceValue"    REAL,
    "PriceDate"    TEXT,
    "Photo"    BLOB,
    "Remark"    TEXT
)


The log is the same whether __rowid__ is shown or not.
