### ISSUE TITLE
[Feature]:  auto reopen last database

### ISSUE THREAD

**Issue by marez-janati** [sqlitebrowser/sqlitebrowser#3623]
### Describe the new feature

im having to reopen the database every time i run the program .. i want it to remember it please.

**Comment by chrisjlocke** [comment]
If you click 'File' and 'Recent files' you'll see a list of last used files.  These also have a numeric prefix.
If you press Ctrl+this number (at least on Windows .. you didn't say what OS you use, but it should work in other OS's), that database will open.
So if you want the last used database, simply press Ctrl+1.

**Comment by lucydodo** [comment]
@chrisjlocke has kindly already suggessted an alternative, but I think this would be a good idea to implement as a feature.
However, there is one thing I'd like to think about before implementing it.
What should DB4S do if the last opened DB file is inaccessible? `(permission issue or removed file etc)`
Should it print a warning message and automatically disable that option?

**Comment by justinclift** [comment]
Maybes some kind of warning like this?

```
Automatically loading the last opened database didn't work.

Database FOOO.sqlite not found at /home/foo/bar/FOOO.sqlite
```

**Comment by lucydodo** [comment]
Yes, that would be great. and would it be a more user-friendly design to disable the option with warning, and then if user open any DB files in that esssion, to re-enable it?

**Comment by justinclift** [comment]
Interesting idea.

As it'll probably need to be a user preference of some sort anyway (`Automatically load last-used database?`), I wonder if it's possible to include a toggle option in the warning dialog when it fails to load?

If so, that'd probably make for the least amount of surprise:

```
Automatically loading the last opened database didn't work.

Database FOOO.sqlite not found at /home/foo/bar/FOOO.sqlite

[x] Keep trying to automatically load the last used database?
```

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by lucydodo** [comment]
Sorry for the delay, I actually forgot about it. By the way, I thought it would be better to add the option to the recent file lists instead of in the preferences, so I added it there, what do you think? does it look okay?

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/64626662/cc2e952d-7e9b-4d76-b656-421f85ce59cd)

**Comment by lucydodo** [comment]
Well, I didn't hear back for about two weeks, so I pushed it to the `master` branch as implemented.
If anyone has any feedback on this feature, please leave a comment.
