### ISSUE TITLE
[Bug]: Execute SQL Console overlaps text

### ISSUE THREAD

**Issue by spacedog12** [sqlitebrowser/sqlitebrowser#3627]
### What did you do?

When writing in the Console, inside the Execute SQL tab, the text overlaps and it's difficult to see where you are.
It happens with the curser and characters. It get's extreme, when you use multiple conditions and connect them for example with OR

### What did you expect to see?

I expected, that the curser is always at the end of the line, not overlapping with the characters written

### What did you see instead?

The curser overlaps with the character, what reading and writing makes difficult.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

Sonoma 14.4.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
This is more than likely a font issue.
If you click 'Edit' and 'Preferences' and change the font, this should get resolved.

It would be interesting to know before you amend it what it currently thinks the font is.
I think its on the first tab, or the 'browse data' tab.

**Comment by spacedog12** [comment]
At the moment the font is set to Apple Braille. I changed it to Arial and now it works.
@chrisjlocke Thank's for the hint.
