### ISSUE TITLE
[Bug]: When you start the program, an error message appears.

### ISSUE THREAD

**Issue by pulmuone** [sqlitebrowser/sqlitebrowser#3635]
### What did you do?

QString::arg: Argument missing: "L1 - 0의 0" , 0

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/42885949/909026a7-fb17-4671-8575-0b86ac043230)

### What did you expect to see?

no error

### What did you see instead?

QString::arg: Argument missing: "L1 - 0의 0" , 0

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/42885949/909026a7-fb17-4671-8575-0b86ac043230)

### DB4S Version

3.13.0-rc1

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Relevant log output

```shell
QString::arg: Argument missing: "L1 - 0의 0" , 0
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
Hi @pulmuone, Thank you for reporting this. However, I was unable to reproduce the same issue in my enviornment.
Have you installed and run DB4S? or did you download a zip file and run it portably?

**Comment by pulmuone** [comment]
> Hi @pulmuone, Thank you for reporting this. However, I was unable to reproduce the same issue in my enviornment. Have you installed and run DB4S? or did you download a zip file and run it portably?

This is the install file I used.
https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.13.x-rc1/DB.Browser.for.SQLite-3.13.0-rc1-win64.msi

**Comment by lucydodo** [comment]
That's weird because I installed and tested with the same file. Did you try running DB4S from the command line?

**Comment by justinclift** [comment]
As an extra thought, does that dialog pop up right after starting the application, or does it happen in response to something else? (clicking a button or something?)

Am trying to figure out what part of the application might be triggering the start of the problem. :smile:

**Comment by pulmuone** [comment]
> As an extra thought, does that dialog pop up right after starting the application, or does it happen in response to something else? (clicking a button or something?)
> 
> Am trying to figure out what part of the application might be triggering the start of the problem. 😄

When you start the program, an error message appears immediately.

**Comment by justinclift** [comment]
Interesting.  I wonder if it's something to do with the check for new updates then?

There's a setting to disable that check somewhere in the application Preferences.  If you turn that off, does the error still appear?

**Comment by lucydodo** [comment]
Closing this issue due to no response from the author. You can check back later and reopen this issue.

**Comment by DongyunKang** [comment]
This issue seems to occur only when the language is set to Korean in the preferences.

**Comment by pulmuone** [comment]
> This issue seems to occur only when the language is set to Korean in the preferences.

한국어 버전에서만 발생하나요? 
이 에러가 데이터 처리에 문제 있을듯 해서 이전 버전으로 다시 설치 했습니다.

**Comment by DongyunKang** [comment]
정식 버전에서 언어 설정을 영어로 설정하고 다시 실행해 보면 발생하지 않는것 같습니다.

**Comment by pulmuone** [comment]
> 정식 버전에서 언어 설정을 영어로 설정하고 다시 실행해 보면 발생하지 않는것 같습니다.

영어 버전에서는 이 에러가 없는거 확인했습니다. 감사합니다.

**Comment by lucydodo** [comment]
@DongyunKang @pulmuone 저도 v3.13.0 버전에서 언어 설정을 한국어로 변경했을 때 이 문제를 재현할 수 있었습니다.
알려주셔서 감사합니다. 빠른 시일 내 수정하겠습니다. :)

**Comment by lucydodo** [comment]
안녕하세요 @DongyunKang, @pulmuone 
이 이슈는 @mgrojo에 의해서 수정되었습니다. 연속성 빌드를 통해 확인해보시고 해결이 되었는지를 알려주실 수 있으시면 감사하겠습니다. :)
> https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

> Hi @DongyunKang, @pulmuone 
> This issue has been fixed by @mgrojo,
> I'd appreciate if you could check it out with a continuous build and let us know if it's fixed: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

**Comment by DongyunKang** [comment]
Windows 11 Pro 23H2
OS 빌드	22631.4037
상기 OS 에서 64비트 버전 설치 후 실행하였을 때 증상 재현되지 않았습니다. :)

**Comment by lucydodo** [comment]
확인해주셔서 감사합니다. 이 변경에 대한 새 안정 버전 릴리즈는 약 1달 이내에 이루어질 예정입니다.

> Thank you for your confirmation. A new stable release with this change is expected in approximately one month.

**Comment by howtokim** [comment]
> 확인해주셔서 감사합니다. 이 변경에 대한 새 안정 버전 릴리즈는 약 1달 이내에 이루어질 예정입니다.
> 
> > Thank you for your confirmation. A new stable release with this change is expected in approximately one month.

Thank you, I also saw the same phenomenon at the Win10 Korean installation.
