### ISSUE TITLE
PRAGMA user_version is not displayed correctly if it is higher than 10000

### ISSUE THREAD

**Issue by karim** [sqlitebrowser/sqlitebrowser#366]
Sometimes I use YYYYMMDD format as the user_version in a database to know when it was last modified. It is stored and displayed correctly when using the SQLite3 command line:

    sqlite> PRAGMA user_version = 20150623;
    sqlite> PRAGMA user_version;
    20150623

However, when viewing the database from DB4S, the User_Version will not be displayed correctly (it will be 10000) if the value is higher than 10000.

According to SQLite3 (https://www.sqlite.org/pragma.html#pragma_schema_version) the user_version is a 32-bit signed integer (maximum value is 2,147,483,647).

    sqlite> PRAGMA user_version = 2147483647;
    sqlite> PRAGMA user_version;
    2147483647

**Comment by justinclift** [comment]
That all makes sense. :smile:

@schdub has added a fix for this bug to our code.  Would you have time to try our nightly build (tomorrow), to verify that works?  (if so, the download locations are on the front page of our repo)

**Comment by karim** [comment]
Thanks for the quick reply and fix. I will test it tomorrow and get back to you.

**Comment by karim** [comment]
Yes, it is working. The User_Version is displayed correctly now. Thanks a lot.

**Comment by glawrence** [comment]
Thanks for letting us know, good news and nice work
