### ISSUE TITLE
[Bug]: DB4S crashes and the project file contents lost

### ISSUE THREAD

**Issue by i-s-o** [sqlitebrowser/sqlitebrowser#3662]
### What did you do?

1. I created a new database, added a table.
2. Saved the project.
3. Attached another DB, reviewed the contents of a table in *Browse Data* tab.
4. Added a new tab under *Execute SQL*, and ran a query.
5. Detached the other DB which was attached in step 3.
6. Saved the project again.

Test DBs and the project file:
[bug-project-contents-lost.zip](https://github.com/user-attachments/files/15828010/bug-project-contents-lost.zip)

Screen recording:
https://github.com/sqlitebrowser/sqlitebrowser/assets/1661549/3609c476-fe51-4fb3-8819-dc6089554dda

### What did you expect to see?

Project file saved properly, including all *Execute SQL* tabs.

### What did you see instead?

* DB4S crashed.
* The project file is now 0-length.

Observations:
1. This bug seems to be the result of the Browse Data tab last showing a table from the now detached database.
2. A related (I think) bug is when the project was last saved when there was an attached DB, but it can't be found when you open the project.
3. Yet another related bug, this time *without an attached DB*, is when you delete a table from the main DB: if that table was open in the Browse Data tab, trying to save the project will crash DB4S, and unsaved work will be lost.

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Heh Heh Heh.  Sounds like bugs we'd need to fix before the next release. :wink:

**Comment by mgrojo** [comment]
@i-s-o thanks for the detailed report. This has saved the new release to be published with a crash. If you could confirm that it is working for you and there are no related crashes, the fix will be available in the next continuous or nightly release.

**Comment by justinclift** [comment]
@lucydodo We'll probably need to merge @mgrojo's fix into the 3.13 release branch. :smile:

**Comment by lucydodo** [comment]
Oh, I'm actually waiting for the reporter's response. :)

**Comment by i-s-o** [comment]
I can't replicate the third method I mentioned in my original post, so that seems to have been fixed by the latest commit. Unfortunately, I can still replicate the other two methods (with attached DBs) using the nightly version:
> DB Browser for SQLite Version 3.13.99 (Jun 16 2024)
> Last commit hash when built: d54933c

[bug-project-contents-lost.zip](https://github.com/user-attachments/files/15858648/bug-project-contents-lost.zip)

## Method 1
1. unzip the zip file to C:\Temp\db4s\bug
2. open the project file in DB4S
3. detach the attached DB
4. click on Save Project. 

### Workaround
Before saving the project, go to Browse Data tab, and make sure a table from the main DB is selected before saving the project.

## Method 2
0. delete C:\Temp\db4s\bug you might have created above
1. unzip the zip file to C:\Temp\test
2. open the project file in DB4S
3. click OK on the error dialog box

### Workaround
Open the .sqbpro file in a text editor and change the path to the attached DB. This manual editing becomes a more difficult task if the zip file didn't include the attached file.

**Comment by justinclift** [comment]
@lucydodo Sounds like there might still be something needing to be looked at ^^^?

**Comment by mgrojo** [comment]
@i-s-o it seems I didn't pay attention to all the details. Now I think the three cases are fixed. Besides, if some other crash would happen while saving the project file, the data won't be lost; the file is not replaced until the file hasn't been completely written. Please, confirm again, just in case I've again missed something, or you find some related crash.

**Comment by lucydodo** [comment]
@justinclift Thanks for the reminder. Thankfully, @mgrojo seems to have solved this issue. :)

**Comment by justinclift** [comment]
Awesome.  Well done @mgrojo. :smile:

**Comment by i-s-o** [comment]
@mgrojo thank you: all three cases are fixed. Unfortunately, in testing these cases, I discovered another path to a destructive bug:

1. Open the file from the the previous comment (also here: [bug-project-contents-lost.zip](https://github.com/user-attachments/files/15880652/bug-project-contents-lost.zip)).
2. Detach the attached DB.
3. Click on the application close button [x]: it should display a dialog box asking to save the project.
4. Cancel that dialog (e.g. maybe you want to check something else before saving).
5. Click on the application close button [x] again.
6. This time click on the save button: the content of the SQL tabs are lost (they are not in the saved project file).

**Comment by justinclift** [comment]
Cool.  This'll be another thing that's been caught early before more people are affected by it. :smile:

**Comment by mgrojo** [comment]
@i-s-o great! We are really purifying the imminent release. It seems I've fixed the destructive bug. I haven't been able to reproduce the minor glitch, though. In any case, it's very minor. It's possible that something is being modified even without user notice. If you save a copy of the project file and compare them afterward, what is it that has changed?

**Comment by mgrojo** [comment]
@i-s-o, I think I've fixed the glitch, although in my platform the behaviour was different. Please, could you try again to see if there's still something broken?

**Comment by i-s-o** [comment]
All good now.
