### ISSUE TITLE
[Bug]: Recent Win32 nightly zips are corrupted

### ISSUE THREAD

**Issue by rasa** [sqlitebrowser/sqlitebrowser#3667]
### What did you do?

On https://nightlies.sqlitebrowser.org/win64/ 
https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-06-16-win64.zip is a 403 (see below) and
https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-06-15-win64.zip is all nulls.

```sh
$curl -o x.zip -v https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-06-16-win64.zip
* Host nightlies.sqlitebrowser.org:443 was resolved.
* IPv6: 2404:f780:4:872::8a
* IPv4: 103.216.220.138
*   Trying [2404:f780:4:872::8a]:443...
*   Trying 103.216.220.138:443...
* Connected to nightlies.sqlitebrowser.org (2404:f780:4:872::8a) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> GET /win64/DB.Browser.for.SQLite-2024-06-16-win64.zip HTTP/1.1
> Host: nightlies.sqlitebrowser.org
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 403 Forbidden
< Server: nginx/1.22.1
< Date: Sat, 22 Jun 2024 21:52:14 GMT
< Content-Type: text/html
< Content-Length: 153
< Connection: keep-alive
<
{ [153 bytes data]
```

```
$curl -O https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-06-15-win64.zip

head -c 1024 DB.Browser.for.SQLite-2024-06-15-win64.zip | od -ax
0000000 nul nul nul nul nul nul nul nul nul nul nul nul nul nul nul nul
           0000    0000    0000    0000    0000    0000    0000    0000
```

### What did you expect to see?

200s

### What did you see instead?

403s and null files.

### DB4S Version

Other

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
Hi @rasa,Thank you for the report.
Unfortunately, I'm out of the office right now and can't check it out.

> https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/nightly
Could you please check if it's broken with the nightly builds uploaded to GitHub too? 🤔

**Comment by justinclift** [comment]
Logging into the nightlies server at the moment, yeah, the most recent Windows nightly zip seems to be broken:

```
nightlies:/nightlies/win64$ ls -al
total 580276
[...]
-rw-r--r--  1 nightlies nightlies 19767296 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-14-win64.msi
-rw-r--r--  1 nightlies nightlies 21599788 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-14-win64.zip
-rw-r--r--  1 nightlies nightlies 19763200 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-15-win64.msi
-rw-r--r--  1 nightlies nightlies 21599776 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-15-win64.zip
-rw-r--r--  1 nightlies nightlies 19750912 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-16-win64.msi
-rw-------  1 nightlies nightlies        0 Jun 16 16:17 DB.Browser.for.SQLite-2024-06-16-win64.zip
```

It'll probably have to wait until @lucydodo is back in the week to take a look at it.

**Comment by justinclift** [comment]
The nightlies that are uploaded to GitHub seem ok.  Well, they're bigger than 0 bytes anyway. :smile:

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/406299/e60dde7a-b818-4b29-a6ec-3e5112c62a51)

**Comment by lucydodo** [comment]
I've just resolved this issue, so I'm closing it. Please check it out and reopen it if you have any issues. Thank you. :)
