### ISSUE TITLE
A collation warning is displayed and sorting is wrong for fields that are defined with COLLATE NOCASE

### ISSUE THREAD

**Issue by yaronbank** [sqlitebrowser/sqlitebrowser#367]
Hi,
When opening a table that includes fields that are defined with COLLATE NOCASE a scary message box is displayed (see "Collation warning.jpg").
Trying to sort the table according to such a field gives wrong results both when trying to run a query (see "Wrong sorting using query.jpg") and when clicking the field header (see "Wrong sorting.jpg").
For comparison, the commercial SQLite Maestro application gives no warning and has no problem with the sorting (but of course it's not free).
Is there a solution for that?
Thanks,
Yaron Bank
email: ybank@adt-co.com
![collation warning](https://cloud.githubusercontent.com/assets/13019151/8309351/e741c2b8-197e-11e5-8ac0-5e25db1cd3e8.jpg)
![wrong sorting using query](https://cloud.githubusercontent.com/assets/13019151/8309353/e7448d0e-197e-11e5-8dce-45f1e9f9c04b.jpg)
![wrong sorting](https://cloud.githubusercontent.com/assets/13019151/8309352/e7423fb8-197e-11e5-800d-f039d02f163a.jpg)

**Comment by schdub** [comment]
@yaronbank do you click 'yes'? Try to click 'no' while loading database.
When you click 'yes' every collation works as BINARY collation and only for 8-bit encoding.

**Comment by yaronbank** [comment]
Hi,
Thanks for your answer.
I really chose 'Yes'.
When I choose 'No' the sorting is really OK.
But the message is still scary...
If I always chose 'No' will I be safe from harming my database?
Is there a way to set the application to always work with 'No', so I don't have to click 'No' the 1st time I open a table with COLLATE NOCASE fields?
Thanks,
Yaron Bank

**Comment by justinclift** [comment]
This sounded a bit familiar, so I went looking back through the old issues.  I think the warning message you're seeing was added for https://github.com/sqlitebrowser/sqlitebrowser/issues/54.

We might be able to change the warning message to be less scary, and more informative.  @rp- Thoughts?

**Comment by schdub** [comment]
I agree that the text of the warning needs to be changed, but I also think that the mechanism of substituting COLLATION can be improved by:
1) no need to register our collation function for standard collations like BINARY, NOCASE, RTRIM;
2) 16-bit encoding version of sqlitedb.cpp,collCompare.

**Comment by yaronbank** [comment]
Hi,
I thank you all for your answers.
Still, I want to be sure if I got it right that if I always chose 'No' for the message box I'd be on the safe side. If so, that would be good enough for me.
Thanks for your help,
Yaron Bank

**Comment by schdub** [comment]
@yaronbank, in your case safely select 'No'.

**Comment by yaronbank** [comment]
Thanks a lot for all the commenters.
This has been very helpful.
Regards,
Yaron Bank

**Comment by MKleusberg** [comment]
Sorry, just rediscovered this issue now. [This comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/367#issuecomment-114563172) by @schdub is the exact right analysis. Would have saved me some time if I saw this earlier :wink:

Anyway, both points are fixed now. Does somebody want to test using the latest nightly build? :smile: Sorry by the way for taking so long...

**Comment by justinclift** [comment]
@yaronbank Would you have the time & interest to try our latest nightly build, to verify if this is fixed now from your point of view? :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Closing this due to lack of response.

@yaronbank This should be fixed now in our recent nightly builds.  We're now handing `COLLATE NOCASE`, so no dialog should pop up at all + the results should automatically be ok.  If for some reason that doesn't work, please either reopen this or create a new issue so we can investigate it. :smile:
