### ISSUE TITLE
[Feature]: Time Detection / Converter Plugin for SQLite db files. 

### ISSUE THREAD

**Issue by BeanMachinez** [sqlitebrowser/sqlitebrowser#3670]
### Describe the new feature

Browser history times and durations seem to be in a epoch format, usually you have to run a SQL command to convert the time into a separate table. When you run the command you lose the ability to use the "Find in Table" feature. 

### Do you have a screenshot? Please add screenshots to help explain your idea.

![Example1](https://github.com/sqlitebrowser/sqlitebrowser/assets/119829273/52fe06f4-d731-472b-9ac7-d0f4af2999e8)

**Comment by mgrojo** [comment]
I don't know what browser is this, but assuming it is WebKit/Chromium, you can try with these [display formats](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats).

* WebKit / Chromium epoch to date
* WebKit / Chromium epoch to local time

If these aren't the format functions you need, you can customize it to your needs. 

If this solves your needs, please close the issue.

**Comment by BeanMachinez** [comment]
I found a other tool that formats this automatically. I'll close and just use that, thanks.

**Comment by neo7BF** [comment]
@mgrojo Thanks for "display formats".  👍
