### ISSUE TITLE
[Feature]: Chrome History - Page Transition Types

### ISSUE THREAD

**Issue by BeanMachinez** [sqlitebrowser/sqlitebrowser#3672]
### Describe the new feature

The plugin should specifically focus on:
Webkit Times: Ability to parse and interpret timestamps stored in Webkit format within the SQLite database.
Transition Types: Recognition of different transition types potentially stored within the History database.

**Benefits:**
1. Improved developer experience: Easier analysis and comprehension of Webkit-related data stored in SQLite databases.
2. Streamlined workflow: Efficient identification of transition types without the need for manual parsing.
3. Broader data insights: Enables developers to leverage Webkit times and transition data for more comprehensive analysis.

**Implementation Details:**
- The plugin should integrate seamlessly with the existing SQLite DB explorer interface.
- Upon encountering a Webkit time format, the plugin should automatically parse and display the time in a user-friendly format (e.g., UTC, local time).
- The plugin should identify and categorize different transition types found within the History database. 

**Additional Considerations:**
- Explore the feasibility of offering configuration options for the plugin, allowing users to customize parsing behavior or specify expected transition type formats.
- Provide clear documentation for the plugin, outlining its functionalities, usage instructions, and any relevant configuration options.

### Does this feature exist in another product or project? Please provide a link

https://kb.digital-detective.net/display/BF/Page+Transitions

### Do you have a screenshot? Please add screenshots to help explain your idea.

![Example2](https://github.com/sqlitebrowser/sqlitebrowser/assets/119829273/91f6b337-85e4-4438-a01d-8769eb3e8dea)

**Comment by chrisjlocke** [comment]
It seems you have knowledge in this area already.  We don't.
This plugin would better be coming from you, and would have a far more likely chance of getting developed.

**Comment by mgrojo** [comment]
Can't this be done using [display formats](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats) or [views](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Views)? These can be saved in a project file (with an attached DB for views, if needed) and distributed for others to use. Then, users only have to put the project file in the folder where the WebKit database is stored to open it correctly (another option is to open the project and then, after the message saying the database file is not found, finding and opening the real DB file).

**Comment by BeanMachinez** [comment]
Thanks all, I will try what @mgrojo mentioned as well as a workaround.
