### ISSUE TITLE
macOS 15 Sequoia Compatibility Check

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#3674]
Apple recently announced macOS 15 Sequoia at WWDC.
I installed the DB4S v3.13.0-rc3 on macOS 15 Sequoia Preview(24A5264n) to test our app and didn't see any issues.

However, I'm opening this issue to track and resolve any issues that arise in other situations.
If you see any issues, please let us know in this issue. Thank you.

> Notes: This issue will be closed after the general release of macOS 15.
> Unresolved issues that until then will be managed as separate issues.

**Comment by richb-hanover** [comment]
> I installed the DB4S v3.13.0-rc3 on macOS 15 Sequoia Preview(24A5264n) to test our app and didn't see any issues.

Whew! Congratulations!

**Comment by lucydodo** [comment]
The full version was released today, and both the v3.13.0 and v3.13.1 RC1 versions don't appear to have any major issues.
Therefore, we are closing this issue, but please open a new ticket if you encounter any further issues.

**Comment by richb-hanover** [comment]
@lucydodo @justinclift @mgrojo  CONGRATULATIONS on releasing 3.13.1!

**Comment by justinclift** [comment]
Oh, should it be showing up on the Releases page already?

https://github.com/sqlitebrowser/sqlitebrowser/releases

**Comment by lucydodo** [comment]
Ah, I see my explanation has caused some misunderstanding. I meant to say that the full version for macOS 15 has been released, and I've confirmed that there were no compatibility issues with our v3.13.0 and v3.13.1-rc1 versions.

**Comment by richb-hanover** [comment]
My apologies for misunderstanding... But congratulations on macOS compatibility, anyway
