### ISSUE TITLE
[Feature]: Open zipped databases OR add support for creating a zipped db

### ISSUE THREAD

**Issue by skyhirider** [sqlitebrowser/sqlitebrowser#3678]
### Describe the new feature

I have an 80MB csv file that I imported into sqlite. I then zipped the database file with 7zip and ended up with 3MB.

I would like to open said 3MB file directly via db browser and it would do the unzipping in the background and handle it transparently for me. 

Compress the actual database and shrinking it so that I would not zip it separately would also solve my use case.

### Does this feature exist in another product or project? Please provide a link

Unknown, thou assume there are database tools out there that can zip and then unzip database files.

**Comment by justinclift** [comment]
It's unlikely we'll do this.  While it's technically possible to make happen, we'd need to figure out a way for it to work on each of the platforms we support, and that would likely pull in further dependencies.

Doesn't seem like it'd be a good use of our time.

If someone knows of a much easier way to make it work than the approach approach though, then it could be an option.
