### ISSUE TITLE
improving Bidi 

### ISSUE THREAD

**Issue by amitmalina** [sqlitebrowser/sqlitebrowser#3681]
### Describe the new feature

when editing  and using multi language like Arabic, Hebrew etc..  with English the text  become unreadable . 
I have to edit the text in other editor like notepad++. 

when writing by mistake rtl language  the text doesn't appear or visually hardly can be seen. 

![Screenshot 2024-07-12 102050](https://github.com/user-attachments/assets/f7841b55-b888-48ca-a35e-415f78392289)

 

### Does this feature exist in another product or project? Please provide a link

notepad++

**Comment by mgrojo** [comment]
I'll close this because it is duplicated with #884. The situation haven't evolved, unfortunately. Please, subscribe to the other issue if you want to get updates about it.
