### ISSUE TITLE
Can't add new field to table

### ISSUE THREAD

**Issue by faacsousa** [sqlitebrowser/sqlitebrowser#369]
I've created a table called 'android_metadata' with a field called 'locale'.

Then I go to browse data and press "New Record" and get the following error:

"Error adding record:
 near ")": syntax error (INSERT INTO 'android_metadata' VALUES ();)"

I guess its because I didn't enter any value to inserto to the DB, but there's no field to do it.

If i run the command from the "Execute SQL tab" it works fine.

I'm using Win8.1 x64

Thank you

**Comment by justinclift** [comment]
Interesting, that doesn't sound good at all.  Which version of DB4S is this happening with?

Also, is there any way you could screenshot it?  It might be helpful. :smile:

**Comment by faacsousa** [comment]
I'm sorry for the long delay to reply.
I've just downloaded version 3.7.0 yesterday.

Those where my first steps into DBBrowser. Afterwards I added a few more tables and they worked fine, but this one still didn't.

I created a new db following "i think" the same steps and the table worked fine, but when I open my first file the error still happens.

![version](https://cloud.githubusercontent.com/assets/6272760/8380432/14e88024-1bfc-11e5-95ab-9656a2b9d392.PNG)

![error](https://cloud.githubusercontent.com/assets/6272760/8380433/14eab1a0-1bfc-11e5-929d-b61a5c082a00.PNG)

**Comment by schdub** [comment]
@faacsousa, please send me (jsbot@ya.ru) the file database, which reproduces this problem.

**Comment by faacsousa** [comment]
I've sent you the file.

And yes default value is set.

**Comment by justinclift** [comment]
@faacsousa Would you be ok to download our latest nightly build, and confirm that the fix for this added by @schdub works well for you? :smile:

(download locations are listed on the front page of this project, if that helps)

**Comment by faacsousa** [comment]
The issue is gone,
:D

**Comment by justinclift** [comment]
Awesome!  Good work @schdub. :smile:
