### ISSUE TITLE
[Bug]: Missing icons in the menu.

### ISSUE THREAD

**Issue by mykauf** [sqlitebrowser/sqlitebrowser#3693]
### What did you do?

Menu bar expanded.
![Screenshot](https://github.com/user-attachments/assets/1610ddb6-9bfb-41eb-b339-1dc785c90f3a)

### What did you expect to see?

The matching icons, as in the previous version.

### What did you see instead?

You can see the undefined icons.
![Screenshot](https://github.com/user-attachments/assets/db249af9-9ef3-4091-b388-5c97437bc8eb)

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
That is expected, those are the icons for links in the current icon-set. The related change is https://github.com/sqlitebrowser/sqlitebrowser/pull/2485

**Comment by mgrojo** [comment]
If we want to go back to the world metaphor, we could use these other icons from our set:

![page-world](https://github.com/user-attachments/assets/1b180644-17fa-4183-9f3b-e6df728ac261)
![page-white-world](https://github.com/user-attachments/assets/929fdeae-52b3-4321-a70c-5ad6331590a4)
![world-link](https://github.com/user-attachments/assets/52d92d9a-3275-4d37-8ee3-77d24705b3e3)

Opinions?

**Comment by justinclift** [comment]
Meh, either way is probably fine. :smile:

**Comment by mgrojo** [comment]
Changed by the "world with link" icon.
