### ISSUE TITLE
[Feature]: no clipping db

### ISSUE THREAD

**Issue by Ranko-Saotome** [sqlitebrowser/sqlitebrowser#3698]
### Describe the new feature

Is there any way to stop it from clipping the database and load everything like it did with the old stable I would rather the whole table be loaded and not be restricted to only 500,000 rows just a preference of mine

### Do you have a screenshot? Please add screenshots to help explain your idea.
new stable 
![image](https://github.com/user-attachments/assets/b99457be-1d59-45ec-8f35-b32552b7d0c3)
old stable
![image](https://github.com/user-attachments/assets/c9e28e91-4c75-417c-81e7-515a43409c1b)

**Comment by mgrojo** [comment]
This is due to #2801. I haven't looked at why it is 499,999 for you, instead of 10,000,000 as was configured in that pull request.

Could you go to the About dialog and paste the information about your version/build?

**Comment by Ranko-Saotome** [comment]
DB Browser for SQLite Version 3.13.0
Last commit hash when built: 777fe12

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.8
SQLCipher Version 3.4.1 (based on SQLite 3.15.2).

**Comment by Ranko-Saotome** [comment]
So I'm guessing there's no easy way to get the old functionality back where it loads the entire database Rows now that 10 million is hard coded

**Comment by Ranko-Saotome** [comment]
```sh
sqlitebrowser-v3.13.0 -o databrowser/rows_limit=20000000
``` 
this command fixed it for my use case

**Comment by Ranko-Saotome** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/issues/2592#issuecomment-897582848

**Comment by chrisjlocke** [comment]
Are you really going to browse through 10 million rows at once?
You can filter the rows easily, so if its only showing the first 10 million, you can add a filter of 'id > 1000000' to see the next 'batch' of rows.
I can't imagine any scenario where you'd go, 'I need to scroll through every row possible in my table'.

**Comment by Ranko-Saotome** [comment]
I have to say I agree after trying it out for a a while I've come to determine it's better this way but I like the option that command to give me in getting the old functionality back if I need it for large queries that I plan on exporting to a CSV
