### ISSUE TITLE
New records aren't saved

### ISSUE THREAD

**Issue by Maypeur** [sqlitebrowser/sqlitebrowser#37]
It seems i'm encoutered a new bug :
I open my database and in a table i click many times on "New Record", many blank rows appears.

I complete theses blank rows then i click "Write Changes" but only the first new record is saved to the disk, all others are cleared !

It appears the same thing if a delete a new record which hasn't be saved or if a i complete the filter, only the first new record appears at the end of the list.

Thanks.

**Comment by MKleusberg** [comment]
Closing this as it's been almost a year now without any response. It this error still occurs everybody's welcome to reopen this issue.
