### ISSUE TITLE
[Bug]: Font looks pixelated

### ISSUE THREAD

**Issue by Side514** [sqlitebrowser/sqlitebrowser#3700]
### What did you do?

Adjust preferences as follows:
- General -> Font size: `14`
- Database -> Database structure font size: `14`
- Data Browser -> Font: `Microsoft YaHei`
- Data Browser -> Font size: `14`
- SQL -> SQL editor font: `Consolas`
- SQL -> SQL editor font size: `14`
- SQL -> SQL results font size: `14`

Microsoft ClearType is enabled.

### What did you expect to see?

Maybe just similar to the previous version (3.12.2)?

1. UI and "Database Structure"
- When `Font size` <= 10, texts are sharp.
![image when font size is 10](https://github.com/user-attachments/assets/42e686fa-2bdf-4d09-bbea-891c960ca383)
- When `Font size` > 10, antialiasing is enabled to get smoother edge.
![image when font size is 14](https://github.com/user-attachments/assets/4e66ce15-8cf5-48e0-9e86-42a6bb7a6ff1)
2. "Data Browser", "SQL Editor"
Antialiasing seems always enabled.

### What did you see instead?

- When `Font size` <= 38, texts are always with ragged edges, especially for Chinese characters.
![image when font size is 14](https://github.com/user-attachments/assets/e5eebcf8-774b-4378-90bc-7f3793299f36)
- When `Font size` > 38, antialiasing seems enabled.
![image when font size is 40](https://github.com/user-attachments/assets/12637788-095d-4df2-996c-2854970568ac)

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by Side514** [comment]
I tried to change the display scale in Windows Settings.
- When scaling is **100%** and font size is 18, there's no difference between 3.12.2 and 3.13.0.
![image](https://github.com/user-attachments/assets/b8e4bb4b-ef9c-41d4-8230-658fe3a3ebdd)
- When scaling is **125%** and font size is 14, 3.12.2 is ok, but 3.13.0 looks not so good (both icons and fonts).
![image](https://github.com/user-attachments/assets/07eabeba-99f8-4abb-b6ce-ad9dbffb178d)

I also tried different fonts. For `Arial` (Windows UI font) and `Consolas`, the difference is not obvious but still exists.

**Comment by Side514** [comment]
I tried to change the display scale in Windows Settings.
- When scaling is **100%** and font size is 18, there's no difference between 3.12.2 and 3.13.0.
![image](https://github.com/user-attachments/assets/b8e4bb4b-ef9c-41d4-8230-658fe3a3ebdd)
- When scaling is **125%** and font size is 14, 3.12.2 is ok, but 3.13.0 looks not so good (both icons and fonts).
![image](https://github.com/user-attachments/assets/07eabeba-99f8-4abb-b6ce-ad9dbffb178d)

I also tried different fonts. For `Arial` (Windows UI font) and `Consolas`, the difference is not obvious but still exists.

**Comment by justinclift** [comment]
Hmmm, wonder if it's a QT setting of some variety?

**Comment by sandman7920** [comment]
Can you try to unzip the link bellow into DB4S root folder
[iconengines.zip](https://github.com/user-attachments/files/16612305/iconengines.zip)

**Comment by justinclift** [comment]
> Can you try to unzip the link bellow into DB4S root folder ...

Oh, that's a smart way of testing a fix.  Good stuff. :smile:

**Comment by lucydodo** [comment]
@sandman7920 Awesome, Can you give me some advice on how to make that change in our codebase? :)

**Comment by lucydodo** [comment]
This issue appears to have resolved, so I'm closing it for now.
