### ISSUE TITLE
SQL Log of changing a cell value

### ISSUE THREAD

**Issue by midoragh** [sqlitebrowser/sqlitebrowser#3702]
### What did you do?

I selected a cell and changed the cell value to "abc".

### What did you expect to see?

I expected that the SQL Log shows
  UPDATE "main"."table" SET "Col1"="abc" WHERE "_rowid_"='123'

### What did you see instead?

The SQL Log shows a question mark for the value
  UPDATE "main"."table" SET "Col1"=? WHERE "_rowid_"='123'

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Technically its right, as thats the SQL - with ? being a placeholder for parameters, which aren't displayed.

**Comment by midoragh** [comment]
I know but somehow the log is incomplete without the parameters.
Best would be to replace the ? so that you can just copy the command from the log, but maybe an additional log line with the parameters would help.

**Comment by chrisjlocke** [comment]
> I expected that the SQL Log shows

Why is the SQL log important?
If you need audit abilities, you could achieve that via triggers, et al.
DB4S knows the selected SQL so could just log that, not the parsed version, but I guess that could be problematic.  
I don't think this issue with the log has been raised before, so thanks for raising it.

**Comment by mgrojo** [comment]
If the statement preparation works, it's easy to change the log for the expanded prepared statement. If it doesn't work (unusual, because it's always the same thing), we shouldn't log it as it had been executed, as we are currently doing. I don't have a clear opinion on what to do in that case. Maybe it's enough with the error message we are printing in the "Error log".

Consequently, I'm going to change this log for the [expanded statement](https://www.sqlite.org/c3ref/expanded_sql.html).

**Comment by mgrojo** [comment]
Implemented. @midoragh, could you confirm it's working fine with the next nightly or continuous build?

**Comment by midoragh** [comment]
I will, but I'm not sure that I can do it tomorrow.

**Comment by midoragh** [comment]
Yes, this patch shows the parameter values instead of the question mark.
Maybe the view of blob values are not optimal. I.e. 
UPDATE "main"."Table" SET "Image"='�PNG

' WHERE "_rowid_"='2133'
Hex representation or a special blob symbol.

**Comment by mgrojo** [comment]
That's indeed a bug, or let's say a glitch, but not related with the logging but with the way of treating binary data in some cases. It's been inserted as a string instead of as a blob. This logging will help to isolate the abnormal cases.

**Comment by midoragh** [comment]
The UPDATE above was part of a 'Duplicate record' action.
It happens always for all  'Duplicate record' actions.
Just pasting an image to the blob shows an UPDATE using the x'...' value representation.
