### ISSUE TITLE
[Bug]: Crash when removing a newly added CHECK constraint

### ISSUE THREAD

**Issue by joulethief97** [sqlitebrowser/sqlitebrowser#3705]
### What did you do?

I was about to start learning SQL and created a very basic db file with nothing but a table "table" in it, the table itself containing a Field "Field1".

When I attempted to rename the table, I stumbled across the "CHECK constraints" tab, mistakenly added an entry and immediately tried to remove it.

### What did you expect to see?

The CHECK constrained being removed and the program working on as intended.

### What did you see instead?

The program crashed without providing any error message.

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Pro 22H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ouch, that definitely sounds like a bug. :grimacing:

**Comment by joulethief97** [comment]
Whoops, forgot to fill in the title. Sorry.

**Comment by chrisjlocke** [comment]
Confirmed - can replicate.  Add a constraint, click 'remove' and application just closes (albeit after a short 'program is dying' phase)

**Comment by justinclift** [comment]
@mgrojo I forgot to point this one out before the 3.13.1 release. 😦

Any interest in taking a look?

**Comment by mgrojo** [comment]
I couldn't reproduce on Linux, but I think I've fixed it. Could both of you, @erickpaquin or @joulethief97, confirm it is now fixed on your platform?

**Comment by erickpaquin** [comment]
@mgrojo I can confirm it did fix the issue for me on my mac M2. Thanks for the good work.

**Comment by mgrojo** [comment]
@erickpaquin thanks for confirming and for the crash report.

**Comment by justinclift** [comment]
@lucydodo We might want to do a 3.13.2 release in a few weeks.  There's still some bugs being fixed that'd be good to have in a stable release. :smile:

**Comment by lucydodo** [comment]
Yes, I'll leave a post in the private discussion about preparing for the next release.

**Comment by joulethief97** [comment]
It still crashes for me, unfortunately... Any further info I can provide?

**Comment by lucydodo** [comment]
Hi @joulethief97, What version are you using?

**Comment by joulethief97** [comment]
I double-checked to confirm that I updated to _3.13.1_.

**Comment by justinclift** [comment]
@joulethief97 Ahhh.  I think the fix is in the latest development builds rather than in the last point release.

Would you be ok to try the build from the `continuous` release? https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

That should (in theory) work ok. :smile:

**Comment by joulethief97** [comment]
Yes, that fixed it. Thank you for your effort!

**Comment by justinclift** [comment]
Awesome, thanks for checking and confirming @joulethief97. :smile:

**Comment by lucydodo** [comment]
The issue appears to be resolved, so we're closing this issue
