### ISSUE TITLE
ARM/Apple Silicon version for v3.13.0

### ISSUE THREAD

**Issue by R2206** [sqlitebrowser/sqlitebrowser#3707]
### What did you do?

I noticed that before version 3.12.2 there was a seperate ARM version, but when looking at the release notes I do not see that "DB.Browser.for.SQLite-v3.13.0.dmg" is a universal app now.

### What did you expect to see?

Can you upload an ARM/Apple Silicon version like you did in the past before v3.12.2 or can you confirm that the app is universal now?

### What did you see instead?

.

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

MacOS

### OS version

14.6.1

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by richb-hanover** [comment]
I am running DB4S 3.13.0 successfully on my M2 Mac mini. The about box says this:
```
DB Browser for SQLite Version 3.13.0
Last commit hash when built: 777fe12

Built for arm64-little_endian-lp64, running on arm64
Qt Version 5.15.13
SQLCipher Version 4.6.0 community (based on SQLite 3.45.3).
```
I don't always understand the definition of "universal". Does the above answer your question? Thanks.

**Comment by justinclift** [comment]
The 3.13.0 macOS application is definitely a "universal" one.  @lucydodo put a bunch of time and effort into getting that figured out. :smile:

@richb-hanover The universal macOS applications include both Intel x86_64 ***and*** ARM64 libraries/executables/etc in the one .dmg download.  macOS knows how to launch the right architecture pieces from such applications, so it (generally) all just works nicely out of the box.

**Comment by lucydodo** [comment]
The two people above have already provided sufficient and clear answers, so I'm closing the issue.
If you have any other comments or questions, you can always reopen the issue.
