### ISSUE TITLE
Suggestion: display numbers in hex format 

### ISSUE THREAD

**Issue by jflucc** [sqlitebrowser/sqlitebrowser#373]
Problem:
Current software can display numbers only in decimal format.For my current use sqlite as a database,  many items are created in hex format. Not comfortable read them in decimal format.
Suggestion:
Every display of data has two options, decimal or hex. Let user to choose.

**Comment by justinclift** [comment]
This sounds like it could be useful for people.  To clarify your suggestion, where are you wanting hex numbers to be displayed?  In the Browse Data tab, or in the Execute SQL tab, or somewhere else?

Also are you thinking it would be best as an option that can be turned on in the Preferences dialog, or something else? :smile:

**Comment by jflucc** [comment]
For me, I prefer to display it in Browse Data tab.  For example, in the attached picture, I prefer the item "diag_msg_def_id" to be displayed in hex format because the item are defined in hex format in my software application.  

Thank you for your efforts! 

Date: Tue, 30 Jun 2015 18:37:48 -0700

**Comment by justinclift** [comment]
Interesting.  So, it would be better to have this be changeable per column, instead of a default for everything?  I'm thinking that when you open a database for the first time + go to the Browse Data tab, you might need to do something like right click and choose a "Display in Hexadecimal" or something.  And we should store that column preference in the project file for a database too.

Does that sound like the best approach?

**Comment by jflucc** [comment]
Yes, your proposal is exactly what I want.😊

Date: Tue, 30 Jun 2015 21:44:02 -0700

**Comment by MKleusberg** [comment]
If I may make this even more complex: I'd suggest making this a fully flexible thing. For a previous project some years ago I had to use Qt's Julian day date format (which works similar to Unix epoch), this made the date values as they are stored in the database really difficult to read and even more so to edit. So maybe we should add some option to specify short SQL fragments (or some other code) which convert between stored data format and display format - ideally in both directions.

**Comment by justinclift** [comment]
@MKleusberg Interesting thought.  Maybe we should have a right click thing that lets people choose from various display options (binary, octal, decimal, hex?), but also allows defining custom ones too using (say) [QString string formatting](http://doc.qt.io/qt-4.8/qstring.html#arg).  eg:

Name | String
---- | ------
Binary | [unsure]
Octal | "%o"
Decimal | "%d"
Hex | "%#x"
My Custom String | "Hi there %s"

That being said, it would be useful to have time/date elements available too (eg %Y for Year, %m for month, etc as per the CLI date command), and I'm not sure how to do that without over engineering things. :wink:

**Comment by MKleusberg** [comment]
I've just made an initial effort in implementing this kind of thing. Here's how it's supposed to be used:
1. Right click the header of a column in the Browse Data tab and click the menu action
![df1](https://cloud.githubusercontent.com/assets/3153504/8528001/68968948-2410-11e5-89ba-ed307acc141e.png)
2. Select an alternative display format from the list of available formats, e.g. all upper case
![df2](https://cloud.githubusercontent.com/assets/3153504/8528016/852f5ec2-2410-11e5-8b8d-306a0dcb1e97.png)
3. Now the values of the column are shown in the new format (while still being saved in the old one)
![df3](https://cloud.githubusercontent.com/assets/3153504/8528029/9d265cce-2410-11e5-910d-4c80402ad8bd.png)

This is far from being finished but should demonstrate how this feature may look like eventually. Hex numbers aren't supported yet by the way, because there's no SQLite function for converting between decimal and hex format. That means we'll have to implement a user function for conversion of this kind and the ones that Justin suggested.

**Comment by MKleusberg** [comment]
Duh, I'm stupid. There *is* a built-in way in SQLite to convert numbers to a hex representation. It's even a fairly obvious one... Just added an option for setting the display format to hex :smiley:

**Comment by justinclift** [comment]
Awesome. :smile:

Have you added the code for saving/loading the custom format to/from the project file?

**Comment by MKleusberg** [comment]
Yes, I have :smiley:
There are still a few problems though, most notably filters and editing isn't working as expected.

**Comment by justinclift** [comment]
Well, we have a few weeks until the next release.  (I don't get my hands on our OSX build box for 6 weeks anyway). :wink:

**Comment by justinclift** [comment]
@jflucc Do you have time to try the nightly build and let us know if this is working well enough for you now? (if it helps, download locations are listed on the front page for this project)

**Comment by jflucc** [comment]
Wonderful, I have tried and like it. Thanks!

**Comment by jflucc** [comment]
A little suggestion for hexadecimal display. Instead of  "printf('%x', `an item id`) ", "printf('0x%x', `an item id`)" may be better.

**Comment by jflucc** [comment]
After I select an display type for an item, then exit the database. Next time, I enter this database, I still have to re-select the display type for this item. I know the reason is that the database does not remember my selection. Could this problem be solved?

**Comment by justinclift** [comment]
Ahhh.  That sounds like meta information that should be saved into a project file.  @MKleusberg, are you ok to add that? :smile:

**Comment by MKleusberg** [comment]
Already did that :wink:

**Comment by MKleusberg** [comment]
But I've just added the '0x...' part like @jflucc suggested :smile:

**Comment by justinclift** [comment]
Excellent! @jflucc Would you have a few minutes to try the next nightly build (tomorrow), and let us know if that change is working ok? :smile:

**Comment by Sharpeee** [comment]
I have a lot of BLOBs that I need to display in a hex format, so I made a small patch.
[hexblob.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/220650/hexblob.txt)

**Comment by justinclift** [comment]
Thanks @Sharpeee, testing it out now.

Do you have a name + email address we can use for the commit data? :smile:

**Comment by Sharpeee** [comment]
@justinclift I have updated my profile with my name. I would prefer not to give out my email address.

**Comment by justinclift** [comment]
No worries, I'll use a placeholder example.org address or something for that field. :wink:

**Comment by justinclift** [comment]
Added here: https://github.com/sqlitebrowser/sqlitebrowser/commit/21c708ab95b64d736764193cba399dbf9afb2262

Thanks for this @Sharpeee. :smile:

**Comment by Sharpeee** [comment]
You're welcome :)

**Comment by jungle-boogie** [comment]
Happy to see this new feature. I updated to master and tested it out--thanks for the work to do this.

I'm not seeing a way to display values in a decimal format. Am I missing something? 

If I change from default to hex, I get the proper conversion in the text box: `printf('0x%x', `Value`)`, I press ok and see the values. I then right click on the cell and choose `edit display format` and see the drop down now shows custom. I'm not able to actually type in the box, though. Is this expected?

**Comment by justinclift** [comment]
@jungle-boogie Ouch, you're completely correct.  That should be editable. 😦

And yeah... there's no "decimal" format option in the list (yet).  Hmmm, want to attempt adding one? :smile: (I would, but my headspace is in something else completely different at the moment. 😇 )
