### ISSUE TITLE
Chinese and Japanese comment text affects the execution of SQL statements

### ISSUE THREAD

**Issue by os9sur** [sqlitebrowser/sqlitebrowser#3731]
### What did you do?

i created a sample SQL statement, and add some comment: 
```
CREATE TABLE "FileDetails" (
	"id"	INTEGER UNIQUE,
	"Field1"	TEXT,
	"Field3"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
)
```
```
--Test SQL: 有列FileName, Field1, Field2. 冩一條sql語句根據FileName 模糊查詢: 首先根據 Fields1, 然後根據每個分組的Fields2值倒序, 然後合並所有
select * from FileDetails
```

### What did you expect to see?

Get the results

### What did you see instead?

https://github.com/user-attachments/assets/25bd4754-db80-4349-a8be-5f857c7f9629

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows10

### Prevention against duplicate issues

- [x] I have searched for similar issues

**Comment by justinclift** [comment]
Thanks.  Yeah that sounds like a bug we'll need to look into.

@lucydodo This might be something to look at for 3.13.1, though I suspect it could turn out to be tricky.  The parsing aspect of Execute SQL text has (from rough memory) been a pain before.

Oh, I think @mgrojo might be into this stuff?

**Comment by mgrojo** [comment]
It should be fixed now. @os9sur could you confirm it and close the issue with a nightly or continuous build?

**Comment by justinclift** [comment]
@mgrojo That fix looks like a good approach.  Much less complicated than I was fearing this might turn out to be. :grin:

**Comment by mgrojo** [comment]
> @mgrojo That fix looks like a good approach. Much less complicated than I was fearing this might turn out to be. 😁

I thought the same at first, because this part of the code is complex and Unicode difficult. But at the end, part of the problem was fixed, although only for one end of the string, so I applied a similar approach for the other end.
