### ISSUE TITLE
[Bug]: Data copied from table cell contains extra end of line character

### ISSUE THREAD

**Issue by hartmanph** [sqlitebrowser/sqlitebrowser#3735]
### What did you do?

1. File --> Open a database
2. Select Browse Data tab
3. Left click first cell in table
4. Right click --> Copy
5. Type Ctrl-F
6. Put cursor in Find In Table text box
7. Right click --> Paste
8. Match not found because data has end of line appended (highlighted in red)
9. Move cursor to end of data and backspace twice
10. Match found (red highlight gone)

Same thing happens when data is copied from table results in SQL Execute tab.

Note: Problem did not exist in v3.12.2

### What did you expect to see?

I expected to see a match in the find window.

### What did you see instead?

I saw a "not found" state in the find window.

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 Enterprise 10.0.19045

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
@mgrojo Any interest in looking at this one? :smile:

**Comment by mgrojo** [comment]
@hartmanph, it should be solved in the next nightly or continuous build.
