### ISSUE TITLE
dark theme cell text color unreadable

### ISSUE THREAD

**Issue by voidplayer** [sqlitebrowser/sqlitebrowser#374]
Im having a similar to issue #89 but with the cells  content color
I tried changing all the colors in preferences and none seemed to work
![screenshoot](https://cloud.githubusercontent.com/assets/4019910/8452545/10dbcf7e-1fec-11e5-8da6-88b33de9ae1f.png)

the color scheme is ghost from kde apps color repos

**Comment by justinclift** [comment]
Oh, interesting.  Looks like we need to add a few more preference options for font colour.

**Comment by schdub** [comment]
@voidplayer, we've added extra color setting for displaying data in 'Browse Data'.
If it isn't to hard for you, please, test this feature.

**Comment by voidplayer** [comment]
im terry busy at the moment... give me a month or so and i will try it :)

**Comment by voidplayer** [comment]
well, preferences are working... although the disabled buttons text is not very very visible yet... it also shows like this by default

![selection_142](https://cloud.githubusercontent.com/assets/4019910/8594011/5f8311a8-263d-11e5-90cd-381350bdde0e.png)


while i would expect it to show something like this

![selection_143](https://cloud.githubusercontent.com/assets/4019910/8594013/6338130c-263d-11e5-89b2-99f46810ac33.png)

I dont have much idea how themes work tho, so no idea whose fault it is :)

**Comment by justinclift** [comment]
@schdub Sounds like we have more work to do for this. :wink:

**Comment by akhilman** [comment]
After upgrading to 3.5.1 which in Debian built with qt5 I have this problem again.
![sqlite](https://cloud.githubusercontent.com/assets/180812/9005670/e28b77dc-37a1-11e5-9cf2-d6e9e1fc0b73.png)

**Comment by mgrojo** [comment]
@voidplayer This is probably solved now.

**Comment by justinclift** [comment]
Good point.  @akhilman Would you have the time/interest to check if this is working now?  We've made a few major releases since this was reported, and Debian has picked some of them up since. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by akhilman** [comment]
sqlitebrowser 3.10.1-1.1 woks fine on debian sid
![screenshot from 2018-02-28 11-05-44](https://user-images.githubusercontent.com/180812/36769683-779af092-1c78-11e8-890f-205f1bd2f1c3.png)

**Comment by justinclift** [comment]
@akhilman If you're ok with trying the latest nightly build, then the white area in the middle will be dark themed as well. :smile:

**Comment by akhilman** [comment]
Here is current master HEAD 3277174cb1ac734842ebdac0e49e3f2ff903d653
![screenshot from 2018-03-01 08-04-19](https://user-images.githubusercontent.com/180812/36821801-5d89c05c-1d27-11e8-8e8d-dbd76da0d39c.png)

**Comment by justinclift** [comment]
Excellent, looks good there too. :smile:
