### ISSUE TITLE
[Feature]: ERD (entity Relationship) Diagrams

### ISSUE THREAD

**Issue by riazahmedsg** [sqlitebrowser/sqlitebrowser#3745]
### Describe the new feature

I want to 

1. Create ERD for the database structure.
2. Create ERD for a new database 

### Does this feature exist in another product or project? Please provide a link

Yes, this feature is implemented by an app "Valentina Studio" for mac os. It is available on Apple App Store.

### Do you have a screenshot? Please add screenshots to help explain your idea.

Screenshots:<img width="911" alt="image" src="https://github.com/user-attachments/assets/82712976-4973-4825-94cc-c773b07de5eb">

**Comment by FriedrichFroebel** [comment]
Thanks for opening this feature request. We already have a ticket for this, thus I am closing your issue in favor of #2034. I recommend you to have a look at existing issues before opening a possible duplicate.

**Comment by riazahmedsg** [comment]
Hi FriedrichFroebel ,

Thanks for the update.

What is the* time frame for implementation* of the requested feature?
It is very much a necessary feature.
Please expedite its implementation.

Hoping to hear from you soon

Regards, Riaz
