### ISSUE TITLE
Future release v3.13.1 is ready for translation!

### ISSUE THREAD

**Issue by lucydodo** [sqlitebrowser/sqlitebrowser#3747]
We are working on the release process for the next stable version, v3.13.1. :rocket:
Before of the release, we'd like to ask for translation contributions to ensure usability for other users.

## Available Release Candidate Versions
You can download v3.13.1-rc2 from the following page: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.1-rc2

## How to Translate
You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) about how to do it.
If necessary, you can get support from our team by leaving a comment on this issue. Feel free to make a request. :)

## Notifications and Translation Status (5/21)
I've ping the list of volunteers for the translation request.
If you'd like to add your name to the list, please see the following wiki page: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translation-Contributor-List
Of course, you're welcome to contribute even if you're not on the list.

| **Locale** |  **Status** | **Untranslated Strings** |  **Translators**  |
|:----------:|:-----------:|:------------------------:|:-----------------:|
|    ar_SA   |   Pending   |            231           |         -         |
|     cs     |   Pending   |           1163           |         -         |
|     de     |  **DONE**  |            32            | @FriedrichFroebel |
|    en_GB   |   Pending   |           1164           |         -         |
|    es_ES   |   **DONE**   |             6            |         -         |
|     fa     |   Pending   |           1451           |         -         |
|     fr     |   Pending   |             7            |         -         |
|     id     |   **DONE**   |            41            |         -         |
|     it     |  Requested  |            34            |      @GortiZ6     |
|     ja     |  **DONE**  |            32            |    @hrwatahiki    |
|    ko_KR   | **DONE** |            32            |     @lucydodo     |
|     nl     |   Pending   |            180           |         -         |
|     pl     |   Pending   |            41            |         -         |
|    pt_BR   |   Pending   |            317           |         -         |
|     ro     |   Pending   |            37            |         -         |
|     ru     |   Pending   |            670           |         -         |
|     sv     |   Pending   |           1211           |         -         |
|     tr     |   Pending   |            327           |         -         |
|     uk     |   Pending   |            991           |         -         |
|     zh     |   **DONE**   |            67            |         -         |
|    zh_TW   |   Pending   |            42            |         -         |

## Changed source string after translation started
None at the moment, but we'll let you know if there are any more.

## Due date and expected release schedule thereafter
As of October 14, 2024 UTC, we're wrapping up translation contributions.

If no one requests additional time by that date and there are no critical issues,
we will make a final release within one week of the translation contribution end date.

Thanks for the community.

**Comment by FriedrichFroebel** [comment]
While translating, I stumbled upon https://www.sqlite.org/pragma.html#pragma_case_sensitive_like which is marked as deprecated. How do we handle these cases?

**Comment by lucydodo** [comment]
Hi @FriedrichFroebel,
Since we don't use the `SQLITE_OMIT_DEPRECATED` option when building SQLite, it seems like a good idea to translate it. However, there is a way to avoid translation in advance, in case we add this option in the next release.
I think it's a matter of translator choice. 🤔

**Comment by lucydodo** [comment]
v3.13.1 has been released, thanks to our translation contributors.
