### ISSUE TITLE
[Bug]: Adjust rows to contents not affecting first row

### ISSUE THREAD

**Issue by dt192** [sqlitebrowser/sqlitebrowser#3767]
### What did you do?

Turn on 'Adjust rows to contents'

### What did you expect to see?

All rows height adjusted

### What did you see instead?

All rows other than first row height adjusted.

https://github.com/user-attachments/assets/e1579512-f312-4599-adfc-d6366fc5eea8

Great feature btw way, was about to feature request it then found it at the last second.

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Win 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by mgrojo** [comment]
Thanks for reporting this. It was a silly off-by-one error.

If you'd like to confirm the fix, install a nightly or continuous build.

**Comment by dt192** [comment]
Yes, all good in the nightly, thanks.

**Comment by justinclift** [comment]
Awesome!  Good stuff @mgrojo, and thanks for verifying the fix @dt192. :smile:
