### ISSUE TITLE
[Bug]: Could not get the INetworkConnection instance for the adapter GUID.

### ISSUE THREAD

**Issue by julianebeli** [sqlitebrowser/sqlitebrowser#3774]
### What did you do?

I installed DB.Browser.for.SQLite-v3.13.0-win64.msi

### What did you expect to see?

No message

### What did you see instead?

A message saying Could not get the INetworkConnection instance for the adapter GUID.
The app launched in the background. The font is monospaced

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 22H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by julianebeli** [comment]
![browser_for_sqlite 3_font](https://github.com/user-attachments/assets/5190c54b-9da2-4c73-b51a-6ed75c46f6c5)
![browser_for_sqlite 2](https://github.com/user-attachments/assets/7f829622-d34b-4396-9c46-55b63177f0d9)
![browser_for_sqlite](https://github.com/user-attachments/assets/5e938c52-c3ac-4e40-a532-b96520ee6858)

**Comment by justinclift** [comment]
Oh, now that's different.  That sounds like an error message from the Qt networking layer.

@julianebeli If you go into the application Preferences and turn off the option to check for updates at start up, does the message still pop up when you restart?

**Comment by julianebeli** [comment]
The message does not appear when the "check for updates at start up" is deselected.

**Comment by julianebeli** [comment]
No problem. Thanks.

**Comment by justinclift** [comment]
Thanks @pulsarice, that's good info. :smile:

**Comment by gordug** [comment]
I have the same error, can't disable proxy though since it's company policy.
