### ISSUE TITLE
[Feature]: Enable Stable Sorting for Table Column Headers

### ISSUE THREAD

**Issue by nkunihiko** [sqlitebrowser/sqlitebrowser#3779]
### Describe the new feature

When clicking on a table header to sort the column, I would like the sort to preserve the original order for rows with the same values. In other words, I am requesting the use of a stable sort algorithm, such as merge sort, instead of quicksort.
This would allow for reproducing orderings like `ORDER BY group_id, age, name` by clicking on columns sequentially.

**Comment by justinclift** [comment]
I *think* we have something like that already by using the <kbd>Ctrl</kbd> / <kbd>cmd</kbd>key?

It's written about here, if that helps? https://github.com/sqlitebrowser/sqlitebrowser/wiki/Browse-Data#sorting-columns

**Comment by nkunihiko** [comment]
Thank you very much! I hadn't noticed that feature.

**Comment by justinclift** [comment]
No worries, hopefully it all works out well. :smile:
