### ISSUE TITLE
no portable version of version 3.7.0?

### ISSUE THREAD

**Issue by divinity76** [sqlitebrowser/sqlitebrowser#378]
22 days in, still no portable 3.7.0 as far as i can see

possible to get a portable version released?

**Comment by justinclift** [comment]
Aaaarrrghh.  I forgot to email John, to let him know about the new release.

**Comment by justinclift** [comment]
It's available now: 

https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.7.0/SQLiteDatabaseBrowserPortable_3.7.0_English.paf.exe

**Comment by divinity76** [comment]
great, thanks :)
