### ISSUE TITLE
[Bug]: updated to new version 3.13.1 and have an issue with the Edit Database Cell window

### ISSUE THREAD

**Issue by tie-a-fly** [sqlitebrowser/sqlitebrowser#3785]
### What did you do?

before, I would be in a table with a DATETIME type.  I would just double click the date of a row I wanted to modify, and the Edit Database Cell window would pop open with that data highlighted blue and ready to change/edit.   Now, when I click on a date, same window shows, but date is no longer, it is just a highlighted zero (0)??  dont know if it's me or the new updated version?

### What did you expect to see?

before, I would be in a table with a DATETIME type.  I would just double click the date of a row I wanted to modify, and the Edit Database Cell window would pop open with that data highlighted blue and ready to change/edit.   Now, when I click on a date, same window shows, but date is no longer, it is just a highlighted zero (0)??  dont know if it's me or the new updated version?

### What did you see instead?

before, I would be in a table with a DATETIME type.  I would just double click the date of a row I wanted to modify, and the Edit Database Cell window would pop open with that data highlighted blue and ready to change/edit.   Now, when I click on a date, same window shows, but date is no longer, it is just a highlighted zero (0)??  dont know if it's me or the new updated version?

### DB4S Version

3.13.1

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Pro version 23H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
This is the second issue like this.
The 'quick fix' is to change the data type of the cell, as 'datetime' isn't a valid sqlite data type.
Look at the recent similar issue where I showed changing to a 'text' data type works.
I'm guessing its a quirk in the logic identifying how to edit an unknown cell type, so technically is a bug...

**Comment by tie-a-fly** [comment]
thank you, that worked, much appreciated.

**Comment by mgrojo** [comment]
Uff, that's ugly. The commit to blame is 1ebe7bf2505d91876da6f0bb29d597edc3834015. I don't know why Qt can say that it can be converted to a number and then convert to 0. Don't know how to fix this, maybe I should revert it?

**Comment by mgrojo** [comment]
SQLite is also a bit crazy. `select typeof(CURRENT_TIMESTAMP);` returns `text` but DATETIME has type affinity as NUMERIC...

**Comment by justinclift** [comment]
Maybe we'll need to add in our own overrides for specific types, to work around the issue?

**Comment by chrisjlocke** [comment]
> SQLite is also a bit crazy. `select typeof(CURRENT_TIMESTAMP);` returns `text` but DATETIME has type affinity as NUMERIC...

current_timestamp is a function, so you're getting the result of a text reply.
datetime returns numeric, as that's the rules.
https://www.sqlite.org/datatype3.html
(see determination of affinity... default is numeric)

**Comment by mgrojo** [comment]
What I mean is, if SQLite developers think DATETIME has to be stored as a number, why they don't make CURRENT_TIMESTAMP to return a number?

**Comment by mgrojo** [comment]
I was able to fix it in the end, after understanding the Qt API. @tie-a-fly could you confirm it works for you with the [next nightly or continuous build](https://github.com/sqlitebrowser/sqlitebrowser/releases)?

**Comment by jadeade** [comment]
Same thing is happening to me. I was advise long ago to use customized field types so my database library would infer type and convert automatically. I am using Delphi and what worked best up to today is to set type as DATETIME (I can vaguely remember that using a different thing would imply manual conversions)

**Comment by mgrojo** [comment]
> Same thing is happening to me. I was advise long ago to use customized field types so my database library would infer type and convert automatically. I am using Delphi and what worked best up to today is to set type as DATETIME (I can vaguely remember that using a different thing would imply manual conversions)

Can you confirm is solved in the latest [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/releases)?

**Comment by jadeade** [comment]
@mgrojo working here as expected in the nightly build, thanks for the efforts!

**Comment by lucydodo** [comment]
The issue appears to be resolved, so close the issue.

**Comment by broidontgnow** [comment]
Do we know when this fix will make it into a prod release?  It's been nearly a year.

**Comment by lucydodo** [comment]
Hi @broidontgnow, Before migrating to Qt 6, a final release that using Qt 5.x is planned.
However, considering the inclusion of several improvements and allowing time for translation contributors,
I anticipate it will be at least two months from now. :(
