### ISSUE TITLE
[Bug]: After opening a database I need to click refresh otherwise nothing showed

### ISSUE THREAD

**Issue by gppoletti2** [sqlitebrowser/sqlitebrowser#3786]
### What did you do?

I open any database and what I see is showed in the attached image.
Every time I must click refresh
![After open](https://github.com/user-attachments/assets/4c73ccf9-29f0-4500-8b40-53f0abfd1037)
![After refresh](https://github.com/user-attachments/assets/98d37e07-1a9e-4396-8e04-4b145eb9b228)

### What did you expect to see?

I expected that after open I see what is inside the database without the need to always click on Refresh

### What did you see instead?

![After open](https://github.com/user-attachments/assets/ac7b152c-9b7b-4a35-99a5-d2fbccf0a7eb)
![After refresh](https://github.com/user-attachments/assets/dda9d1a0-dcec-4b80-bd4c-e10aa7b2f0bb)

### DB4S Version

3.13.1

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
@gppoletti2 Thanks for reporting this. :smile:

We've actually had a few people mention this bug to us already, so we're already investigating it (in #3714, which seems related).

**Comment by justinclift** [comment]
I'll close this issue, as it's a duplicate.  That doesn't mean it won't be solved though. :wink:
