### ISSUE TITLE
[Feature]: Add ability to "Check for updates..." to update the SQLite Browser app

### ISSUE THREAD

**Issue by JoeFerrucci** [sqlitebrowser/sqlitebrowser#3788]
### Describe the new feature

- Add a "Check for updates..." option in the menu bar

When I opened the app, it asked me to update but I was in a hurry and didn't want to update so I dismissed it. 
I went to find the check for updates option in menu bar and settings but didn't find it. 
I opened and closed the app a couple times; still didn't trigger it again. 

### Does this feature exist in another product or project? Please provide a link

Yes, they exist in most products

### Do you have a screenshot? Please add screenshots to help explain your idea.

![Screenshot 2024-10-30 at 10 45 41 AM](https://github.com/user-attachments/assets/f08c76ac-87e3-4c75-b18e-9c316c6c740d)

**Comment by chrisjlocke** [comment]
If you go to the preferences, there is an option, 'check for updates' checkbox.  Ensure this is checked (or ticked), close the application and reopen it.  :)

**Comment by JoeFerrucci** [comment]
> If you go to the preferences, there is an option, 'check for updates' checkbox. Ensure this is checked (or ticked), close the application and reopen it. :)

Yes, I stated that in the description but I can't get it to trigger anymore. An action to "Check for updates..." would be preferred.

Again, to restate, the check for updates "IS" enabled, but its not triggering the update anymore. I temporarily dismissed it and now it won't come back.

CTA to "Check for updates..." preferred.

Thanks, feel free to close if you don't want it

**Comment by JoeFerrucci** [comment]
Here's an example, I've also updated the description to include it:
![Screenshot 2024-10-30 at 10 45 41 AM](https://github.com/user-attachments/assets/f08c76ac-87e3-4c75-b18e-9c316c6c740d)

**Comment by chrisjlocke** [comment]
What version of DB4S are you using?
(Click 'Help' then 'About')

**Comment by JoeFerrucci** [comment]
> What version of DB4S are you using? (Click 'Help' then 'About')

3.12.2

**Comment by JoeFerrucci** [comment]
I'll reiterate just in case it got lost in the back-and-forth:

`DB4S 3.12.2` asked me to update _to_ `3.13.1` but I chose **not to** update at that time.

Since then, I've opened and closed the app a few times but it did not give me the update prompt again. 

However, I just opened it again and it finally asked me to update. Now I'm on 3.13.1.

**Comment by justinclift** [comment]
Yeah, it's weird that it wasn't asking you every time you launched 3.12.2, as it should have prompted you each time.

Glad it finally got there in the end though. :wink:

**Comment by chrisjlocke** [comment]
Just for the avoidance of doubt, you can always go to https://sqlitebrowser.org/dl/ and just download .. you don't have to download through the application.
Also, I would suggest running the nightly versions, as these tend to fix issues before the official release .. and no offence to the DB4S team, but official releases can take a while to be released.  The update check doesn't look at the nightlies so manually downloading tends to be a given thing to do anyway.

**Comment by JoeFerrucci** [comment]
I'd like to resurface the initial request: add a "Check for updates..." CTA in the menu bar.

**Comment by justinclift** [comment]
Well, it's probably pretty simple to add.  The code for doing the actual check is already in the code base, so this would be mostly a matter of adding matching gui pieces.

**Comment by lucydodo** [comment]
Thanks for this suggestion. A PR has been prepared to address this issue: #3791

**Comment by justinclift** [comment]
@JoeFerrucci A new manual update check has been added to the application menu in the very latest development code.

Would you be ok to try out a new "continuous" build and let us know if it works for you decently well? :smile:

Build is here: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous
