### ISSUE TITLE
[Bug]: SQLCipher prompt when launching SQLite Browser

### ISSUE THREAD

**Issue by jhuus** [sqlitebrowser/sqlitebrowser#3795]
### What did you do?

Whenever I launch the app, I get a message box saying "Please enter the key used to encrypt the database". I don't have any encrypted databases, so I click Cancel.  Then I get a message saying "Could not open database file. Reason: invalid format". Then I select and open my database file, and it works fine.

### What did you expect to see?

I expect the app to open with no prompts or error messages.

### What did you see instead?

As described above.

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 24.04

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Ahhh.  That's the message that the application displays when it tries to open a database file, but the underlying SQLite library rejects the file.

When that happens we assume that the file is an encrypted database, so not readable without the details for the encryption used.  And yeah, that's a bit confusing for someone trying to open a file which *isn't* an encrypted database.

I guess the first question is, are you *sure* the file you're trying to open is a SQLite database file?

Sometimes people try opening files with extensions like `.sql` or `.db` which are commonly SQLite files, but can turn out to be something else.  If it's a `.sql` file, it'll probably be text meant for importing into a new (empty) database.

**Comment by jhuus** [comment]
I'm just opening the application, and haven't selected a database file at all. Then I select a file, open it, close it and close the application. When I open the application again, I get the same message, even though I haven't selected a file.

**Comment by jhuus** [comment]
Agreed! Is there a log that might give more info?

**Comment by justinclift** [comment]
Good question.  There are logs for the SQL queries that get run, but I don't *think* there's really anything useful log wise until the database is open.  :thinking:

First things first, I'd try launching the application from the command line (eg `sqlitebrowser` or whatever`) as startup/failure messages *do* often get printed to stdout/stderr when it's running.  It's not a specific log, but might give enough info as to what's happening.

If that doesn't do anything useful, there's a 2nd approach to try that I sometimes use for other things when I'm trying to figure out wtf is going on. :smile:

The 2nd approach is to use a shell script like this to record the arguments a program is being started with:

```
#!/bin/bash

echo "Launching SQLite Browser" > /tmp/stuff.txt
echo $0 $@ >> /tmp/stuff.txt
```

I'd move the real `sqlitebrowser` program out of the way temporarily (ie `mv sqlitebrowser sqlitebrowser-orig`) and put the shell script in its place.  Then try launching the program as you normally would (via Gnome/KDE/etc).

That will instead run the shell script, which should (in theory) create a text file called `/tmp/stuff.txt` detailing the arguments that it was called with.

Does that make sense? :smile:

**Comment by jhuus** [comment]
Thanks! When I type sqlitebrowser at the command line I get the same symptoms as usual. Here's the console output:

t: Session management error: Could not open network socket
Could not create AF_NETLINK socket (Operation not permitted)
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.145\" (uid=1000 pid=5714 comm=\"/snap/sqlitebrowser/4598/usr/local/bin/sqlitebrows\" label=\"snap.sqlitebrowser.sqlitebrowser (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1303 comm=\"/usr/sbin/NetworkManager --no-daemon\" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.145\" (uid=1000 pid=5714 comm=\"/snap/sqlitebrowser/4598/usr/local/bin/sqlitebrows\" label=\"snap.sqlitebrowser.sqlitebrowser (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1303 comm=\"/usr/sbin/NetworkManager --no-daemon\" label=\"unconfined\")"
"Object path cannot be empty"
Could not create AF_NETLINK socket (Operation not permitted)

The "Object path cannot be empty" looks suspicious. Does it tell you anything?

**Comment by justinclift** [comment]
Ahhh.  It's the Snap version of the application.  It'll probably be something caused by Snap, but that's just a guess based upon seeing it cause so many other issues for people with other applications too. :wink:

The network mentions are a bit unexpected on Linux.  For Windows and macOS the application automatically checks at startup if there's a new version (by calling over the network to find out), but that shouldn't be happening on Linux.  Maybe there's some different network thing happening as well?

---

Hmmm, there's no real smoking gun in the above.  My suspicion is it's probably Snap related though.

Instead of running the Snap, you're probably better off using the AppImage version of the application instead.  ie: grab it from [here](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.1).  It should work fine. :smile:

**Comment by jhuus** [comment]
That worked! Thanks again.

**Comment by justinclift** [comment]
Awesome.  Yeah, Snap has a bad reputation for a reason. :frowning:
