### ISSUE TITLE
[Feature]: Plist Data Viewer / Editor

### ISSUE THREAD

**Issue by JamesHabben** [sqlitebrowser/sqlitebrowser#3796]
### Describe the new feature

Lots of sqlite database files pulled from iphones and mac computers have blob cells that store plist data. It would be great to view in an interpreted or parsed view similar to how there are currently XML and JSON viewers for cell data.

### Does this feature exist in another product or project? Please provide a link

Not in an open source tool.

Here is an example of the process to view the blob data when encountered: https://www.hexordia.com/blog/mobile-forensics-data-structures

Here is a commercial tool that provides plist viewer and protobuf viewer: https://docs.magnetforensics.com/docs/axiom-cyber/html/Content/en-us/axiom/reviewing-evidence/explorers/viewing-database-tables.htm#ViewBLOBdata

Another commercial tool that provides the viewer: https://sqliteforensictoolkit.com/sqlite-forensic-toolkit/forensic-browser-for-sqlite/

### Do you have a screenshot? Please add screenshots to help explain your idea.

<img width="430" alt="image" src="https://github.com/user-attachments/assets/a18f5e6d-28bd-4619-b72e-36034386c86b">

**Comment by FriedrichFroebel** [comment]
I am not completely sure if this really makes sense: JSON and XML are human-readable formats commonly used by lots of applications. Plist files are in some binary format which requires further conversion to make use of it inside DB4S and has more or less rather specific use cases.

**Comment by justinclift** [comment]
> Plist files are in some binary format

Oh, .plist files don't *have* to be in binary format.  They have a text representation too, and there are macOS utilities to convert between them.

I kind of wonder if we should have some kind of file detection logic (similar to `file` on *nix) that could detect a file type and potentially run the OS associated action for that file type.  Maybe like mine types?

**Comment by mgrojo** [comment]
Our [formats extension](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/extensions/extension-formats.c) is able to decode binary Plist. You can use it as a [display format](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Display-Formats). See  #1716. As with any display format, editing is not supported, though.

**Comment by JamesHabben** [comment]
@mgrojo Thanks for sharing that. I did some searching around and hadn't found that functionality.

It seems that there is an issue with that extension though. on 3.13.1 it seems that the extensions were compiled for Arm in the Intel package.
<img width="532" alt="image" src="https://github.com/user-attachments/assets/8495a60d-e750-4aca-a508-00d79b688af2">

I got a sneak at the functionality in 3.12.2 before I realized I didn't have the latest. Now it gives this error when I try to load the extension manually or have it loaded automatically in settings.

**Comment by mgrojo** [comment]
@lucydodo maybe this is something you can sort out?

**Comment by JamesHabben** [comment]
It looks like a relatively easy fix in the build script if I am understanding correctly - still kinda new to github actions. The extension build looks to be only building for the architecture the github runner is (guessing its arm). I was gonna fork and test this, but the workflows are intertwined and I can't get them to run in my fork as a test on the builds.

So this section:
https://github.com/sqlitebrowser/sqlitebrowser/blob/a7e35c2a3967d315ac6caa9e7b9a1e00634b1ad5/.github/workflows/build-macos.yml#L69-L70

might get fixed like this:
```
name: Build Extension
run: clang -I /opt/homebrew/opt/sqlb-sqlite/include -L /opt/homebrew/opt/sqlb-sqlite/lib -fno-common -dynamiclib src/extensions/extension-formats.c -arch arm64 -arch x86_64 -o extension-formats.dylib
```

**Comment by justinclift** [comment]
Cool.  Yeah @lucydodo will definitely be interested in investigating, and that'll likely help heaps. :smile:

**Comment by JamesHabben** [comment]
now that I know this capability and structure, I am working on a couple things to submit in, such as a plist-to-json function. 

plist data raw:
<img width="437" alt="image" src="https://github.com/user-attachments/assets/270c740b-2ed2-4af4-ab3e-e2ceb811bc5b">

existing plist to xml:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/4dbcf534-ea6f-43af-b3f4-f10a00ea2b90">

new plist to json (auto-detected):
<img width="382" alt="image" src="https://github.com/user-attachments/assets/70132af6-c5d9-4a28-88a7-74f4c34bc91c">

this plist is an example of further 'encoding' needing to be deserialized, so i am working on another function to see about doing that.

**Comment by JamesHabben** [comment]
I am also trying to add in some functionality where these extensions can share a list of display formats that can be added to the format drop down rather than having to manipulate these manually into place. since its in the core, i have to build to test the changes.

I am having trouble with doing a build though, so I am wondering if it is because of me trying to build on an intel mac rather than arm. i tried following the `building.md` doc but it seems to not be fully aligned with the CI builds in `build_macos.yml` so I am using that as a template instead. I cannot install the packages from the sqlitebrowser tap because they all require arm platform. this is why I wonder if I need those specific packages to build as the standard packages I have installed from homebrew give me these errors:

```sqlitebrowser/src/sqlitedb.cpp:2146:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
 2146 |     sqlite3_enable_load_extension(_db, 1);
      |     ^
/sqlitebrowser/src/sqlitedb.cpp:2150:18: error: use of undeclared identifier 'sqlite3_load_extension'
 2150 |     int result = sqlite3_load_extension(_db, filePath.toUtf8(), nullptr, &error);
      |                  ^
/sqlitebrowser/src/sqlitedb.cpp:2155:9: error: use of undeclared identifier 'sqlite3_enable_load_extension'
 2155 |         sqlite3_enable_load_extension(_db, 0);
      |         ^
/sqlitebrowser/src/sqlitedb.cpp:2173:5: error: use of undeclared identifier 'sqlite3_enable_load_extension'
 2173 |     sqlite3_enable_load_extension(_db, Settings::getValue("extensions", "enable_load_extension").toBool());
      |     ^
4 errors generated.
```

here is the command I am using to build
```
mkdir build
cd build
cmake -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_STANDARD=14 \
  -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) \
  -DENABLE_TESTING=ON \
  -DENABLE_LOAD_EXTENSION=ON \
  -Dsqlcipher=0 \
  .. && ninja
```

not fully related to the initial issue submission, but any thoughts here? should i open a new issue?

**Comment by lucydodo** [comment]
Oops, I forgot about this extension when transitioning to the universal binary. I'm sorry about that.
I'll have some free time this evening, so I'll add support for this extension then. :)

**Comment by lucydodo** [comment]
Hi @JamesHabben,
When building DB4S for macOS, the SQLite used is provided by the [homebrew-tap](https://github.com/sqlitebrowser/homebrew-tap), and it can be built through it.
However, as you mentioned, our current `homebrew-tap` does not support x86_64 machines.

If necessary, you can build SQLite yourself using the following set of commands:
```bash
curl -O https://www.sqlite.org/2024/sqlite-autoconf-3460100.tar.gz
tar -xvf sqlite-autoconf-3460100.tar.gz && cd sqlite-autoconf-3460100
export CPPFLAGS="-DSQLITE_ENABLE_API_ARMOR=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_SNAPSHOT=1 -DSQLITE_ENABLE_SOUNDEX=1 -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_MAX_ATTACHED=125 -DSQLITE_MAX_VARIABLE_NUMBER=250000 -DSQLITE_USE_URI=1"
./configure --prefix=[PREFIX_TO_INSTALL]  --disable-dependency-tracking --enable-dynamic-extensions --disable-readline --disable-editline
make && make install
```
And when executing the cmake command, provide the prefix path specified above in the `CMAKE_PREFIX_PATH`.
Free free to let me know anytime if you need more detailed assistance.

**Comment by lucydodo** [comment]
Hi @JamesHabben,
<img width="1841" alt="Screenshot 2024-11-12 at 10 19 22" src="https://github.com/user-attachments/assets/d2624e78-2dba-4368-8423-abaa962a4b81">
Support for the x86_64 architecture has been added. You can check it in continuous builds or nightly builds.

**Comment by JamesHabben** [comment]
Just got the continuous build. Confirmed the error is gone and the `plist()` function is working.

**Comment by justinclift** [comment]
Awesome!  Ok, lets close this issue an we can follow up the plist PR stuff in the PR itself.

Good work both everyone! :grin:

**Comment by JamesHabben** [comment]
sounds good and thanks for the quick response and help.
