### ISSUE TITLE
[Bug]: CSV import limited to 20 lines including columns headers

### ISSUE THREAD

**Issue by Jacques-in-Brussels** [sqlitebrowser/sqlitebrowser#3798]
### What did you do?

I opened an existing and working database (sqlite).
Then I tried to import a .csv file that was made with Exell.

### What did you expect to see?

1. I expected to see the "import CSV file" dialog with a view of the imported datas with their headers on top of the colums, and
2. that there are no columns/headers missing or irrelevant (checked = its OK) and
3. the number of lines displayed is the same as in the CSV file (wrong, lots are missing)

### What did you see instead?

After several tries with other databases, old or new (empty), and importing several different CSV files, the behaviour is always the same : only the 20 first line are imported (1 header, 19 data).
I tried with CSV from Exell, or from LibreOffice, same result.
I restarted Windoze, , same result.

My last successful work on database was november the 9th. I imported a new table (from a 240 lines csv file) into an old sqlite DB, and it works like a charm. 

### DB4S Version

3.13.1

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 64bits version 22H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Interesting.  As a diagnostic step, please try with the 3.12.2 release (the prior major release) and see if it works or fails in the same way: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.12.2

In theory, that one should definitely work.  Theory though... well, lets just see. :grin:

**Comment by Jacques-in-Brussels** [comment]
Thanks Justinclift.
I will try this asap, like in the next hour, and let you know.
In the mean time I ran some tests with SQLite studio (much tedious) with the same databases and sources CSV as before (which I've manipulated successfully until the 9th of november) and all those tests with SQLite were OK, and running correctly within KiCad. I don't know if this is of some use, but well, SQLite doesn't forget all the lines after the 20th in my CSV's.

**Comment by Jacques-in-Brussels** [comment]
Justinclift,
Actually the 3.12.2 version gave the same results, BUT...
(and now I feel a bit stupid) ... when I've chosen to import a CSV table a windows pop-up, named "Importing a CSV file" where I can choose some settings (Name of the colums in 1st line, field delimiter, encoding, etc...) and this window (dunno why) only shows the 20 first lines. What made me think that the import was not complete is the scroll bar at the right of the window, pulling it doesn't show you more than those 20 lines.
This time I went further and if you press OK, the table is created, and browsing the new table shows the full expected number of lines and its complete data.
I'm pretty sure that previously I could see the full set, scrolling down to the last line, in the first "Importing CSV file" window... but being "pretty sure" does not guarantee I am right.
Anyhow problem solved, sorry for any inconvenience, and thanks a lot for such a nice and simple tool.
Jacques

**Comment by mgrojo** [comment]
We are showing only a preview of the first 20 rows so you can see the effect of the different parameters, without parsing all the file, which might take a lot of time.

**Comment by justinclift** [comment]
> Anyhow problem solved, sorry for any inconvenience, and thanks a lot for such a nice and simple tool.

No worries at all, glad you got it figured out. :smile:
