### ISSUE TITLE
Split "Execute SQL" tab vertically in query & result/feedback

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#380]
Since most screens are more wide then high and query texts rarely occupy the screen's entire width,  the space in the "Execute SQL" tab could be used more efficiently if the query field could take up the entire left part of screen and the result/feedback fields were stacked on the right side.

Of course, the possibility to resize the left/right panes would be a bonus.

**Comment by justinclift** [comment]
Seems like an interesting idea.  I'm not sure how feasible it is though... one of the others - who knows Qt - will have to chime in. :smile:

**Comment by MKleusberg** [comment]
I've added a new option to the Preferences dialog which, when activated, puts the result table view to the right side of the code editor. The success/error messages are still shown at the bottom, though, which looks a bit more aesthetic in my point of view. I've also (re-)introduced the possibility to resize the two panes.

If you want to check out the new feature, you'll have to wait for tomorrow's nightly build, download & install it and then click View -> Preferences, select the "SQL" tab and check the "Horizontal tiling" option at the bottom. Hope this helps :smile:

**Comment by pamtbaau** [comment]
Wow, this is truly swift!

I'll have a look tomorrow...

**Comment by justinclift** [comment]
@MKleusberg You're a legend dude. :grin:

**Comment by pamtbaau** [comment]
The views are not expanding vertically...

Having considered the aesthetics, I still prefer the success/error pane to be stacked underneath the results pane. The editing of the query is the main task in this window hence its view should be most comfortable/efficient.

**Comment by justinclift** [comment]
@pamtbaau Are you ok to try the nightly build (tomorrow), to see if the latest commits from @MKleusberg makes it better?

**Comment by pamtbaau** [comment]
@justinclift Sure I will with this amount of speed and effort put in by MKleusberg... :-)

**Comment by pamtbaau** [comment]
@MKleusberg @justinclift  Just tested the nightly build of July 10th. It works like a charm! 

* I've got a 50% increase in vertical  space, which gives me much more oversight when editing and testing my queries.
* I also like I don't need to scroll down the entire success/error pane any more to see the performance figure of the query.

Thank you! I compliment you on your responsiveness....

Just out of curiosity, why is the query repeated in the success/error pane? I don't see an added value over the same text in the query pane. Wouldn't messages like "no such column: l.locationId" or "5 rows returned in 52ms" be enough on their own?

**Comment by MKleusberg** [comment]
Cool! I'm glad I could help :smiley: And thanks a lot for the feedback!

The query gets repeated since the first version I've ever used, long before I've started helping out in development. So to be honest I've no idea why it was added to the message string. However, with the more recent version (3.0+) it kind of makes sense to repeat it because these versions allow you to execute multiple queries at once. Now, assuming you get an error or some query results, it might be unclear from which query they originate. This is at least why *I* think it serves some purpose to have them in there.

**Comment by justinclift** [comment]
Hmmm, this issue seems like it's fully done now.  Are we ok to close it from your point of view @pamtbaau? :smile:

**Comment by pamtbaau** [comment]
@justinclift Yes from my point of view this issue can be closed. Thanks for your support.

**Comment by pamtbaau** [comment]
After upgrading to 3.10.1 it seems the 'Execute SQL' windows has been redesigned. I would very much like the changes to be reversed. Most important parts are query panel and result panel. The query feedback panel is least interesting and should not occupy 1/3 of the screen width.

It would suggest the following (as it was before):
Left side: 1/2 of screen for query panel
Right side: vertically stacked query result panel and query feedback panel

**Comment by justinclift** [comment]
@pamtbaau We moved the "Save" button on the right side of the bottom most pane to the top panel, after a report by a new user that it was confusing as-is (#1122).  Is that what you're meaning? :smile:

**Comment by pamtbaau** [comment]
I mean the layout as in this screenshot below. This is how it was in 3.9.0

![screenshot](https://user-images.githubusercontent.com/5120011/31355879-3faee248-ad3c-11e7-95e4-18e2e4a3b6ae.png)

Moving the 'save as' button from the lower right corner into the buttonbar (#1122) is a good suggestion by the way.

**Comment by justinclift** [comment]
@pamtbaau Ahhh. You're probably wanting the "Horizontal tiling" option under **Preferences** -> **SQL**:

![preferences-horizontal_tiling_option](https://user-images.githubusercontent.com/406299/31493172-f9266d9e-af45-11e7-87c2-f06deba6bbac.png)

With it disabled:

![execute_sql-horizontal_tiling_disabled](https://user-images.githubusercontent.com/406299/31493191-05304510-af46-11e7-890a-d0154b8ff0f6.png)

With it enabled:

![execute_sql-horizontal_tiling_enabled](https://user-images.githubusercontent.com/406299/31493199-0f2a82e2-af46-11e7-86cd-de4288da2bb9.png)

Does that help? :smile:

**Comment by pamtbaau** [comment]
I do have "horizontal tiling" enabled but don't get your layout. On my Windows 10, I get three vertical columns + the 'save as' button on the side.
Db Browser version: 3.10.1

![sqlbrowser](https://user-images.githubusercontent.com/5120011/31493965-aba98db0-af51-11e7-82f1-a4804040094c.png)

**Comment by chrisjlocke** [comment]
Was just going to post the same ... on my DB4S, the SQL Log isn't along the bottom.

![image](https://user-images.githubusercontent.com/7872218/31494062-a11036a4-af49-11e7-8c33-1f33b576e27b.png)

**Comment by justinclift** [comment]
Ahhh.  That's probably what the commit last night did then: ce18198bbfca05a33dccadee55e13e8afb54769c

I'd just updated and rebuilt from our latest source before taking that screenshot, without knowing that's what it did.  Sorry.

On a related note, it seems like our Windows nightly builds are broken at the moment due to a different recent code change (#1169).  It might take a few days for us to get this new windows breakage fixed though. 😦

**Comment by MKleusberg** [comment]
Yep, I've fixed this issue yesterday but then got distracted for some reason and didn't update this issue :smile:

@pamtbaau We'll let you know as soon as our nightlies our running again, so you can update without problems :wink:

**Comment by justinclift** [comment]
@pamtbaau The Windows nightly builds are running again now, so (in theory) any nightly build from tomorrow onwards will have the fixed layout bits in it. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by pamtbaau** [comment]
Thanks @justinclift.  
The nightly does indeed have the new layout...  Much better!

(I still slightly prefer the 3.9 layout in which the error feedback panel is stacked vertically  underneath the sql result panel and consumes half its current space...)

**Comment by MKleusberg** [comment]
Thanks for the feedback, @pamtbaau. You're right, it makes more sense the way it was in 3.9. So I've just fixed it to more resemble the 'old' layout. Can you check again using tomorrow's nightly build and see if that's good for you? :smile:

**Comment by pamtbaau** [comment]
@MKleusberg Yes, the layout is almost back as it was in version 3.9 :-)
Except.... that the columns are squeezed into the width of the column names.

**Comment by MKleusberg** [comment]
Ah, that's a side-effect of the multi-threading thing I've been trying to implement over the last couple of days. Thanks for pointing this out! I'll try to fix it soon-ish :smile:

**Comment by MKleusberg** [comment]
Ok, sooner than expected :wink: I've just prepared a fix for that, too. You can check again using tomorrow's nightly build. If you notice any further oddities in the nightly build, feel free to report them. I'm currently making some larger changes and it's good to know when things break :smile:

**Comment by pamtbaau** [comment]
@MKleusberg Width of columns in query results are fine now. 

Ok, if you really want me to, I will keep nagging if things break... :-)

**Comment by MKleusberg** [comment]
Yes, please do! 😄 With all the different options and features in DB4S now, it's gotten to the point where I can't really test a change in all scenarios anymore. So if you use horizontal tiling or pay attention to the default column widths, that's awesome and definitely helps a lot :wink:
