### ISSUE TITLE
Execute SQL window: Move query executiontime to top of success/error pane

### ISSUE THREAD

**Issue by pamtbaau** [sqlitebrowser/sqlitebrowser#381]
Together with amount of rows returned, the amount of time the query took is the most important info if the query is successful. This info is at the bottom of the success/error pane. Could that info be on the first line together with the amount of rows? E.g. "5 Rows returned  in 115ms from:\n"

**Comment by MKleusberg** [comment]
Sorry, I'm a bit in a hurry right now but I've just pushed a commit for each of your issues. I'm quite confident this one will be fixed in the next nightly build :smiley: The code for #380 has been changed as well, but we'll have to see how it works for you.

**Comment by justinclift** [comment]
@pamtbaau Is this one working well for you now too? :smile:

**Comment by pamtbaau** [comment]
@justinclift Yes, this issue may be closed as well

**Comment by justinclift** [comment]
Thanks. :smile:
