### ISSUE TITLE
Version info (Mac)

### ISSUE THREAD

**Issue by jmatx** [sqlitebrowser/sqlitebrowser#382]
When I launch version 3.7.0 on a Mac (10.10.2), the About DB Browser for SQLite page shows version 3.7.0.  But in the Finder, is shows version 3.4.99.

![screen shot 2015-07-13 at 1 32 29 am](https://cloud.githubusercontent.com/assets/11401821/8643897/17425434-28ff-11e5-993a-90deb9a8bd26.jpg)

**Comment by jmatx** [comment]
My mistake -- close it.

**Comment by justinclift** [comment]
No worries. :smile:
