### ISSUE TITLE
Add ability to choose font size for Browse Data tab

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#383]
Received a personal email from someone requesting a way to change the font size in the Browse Data tab.

On their system, the current font size isn't quite big enough. :smile:

**Comment by justinclift** [comment]
In follow up email, it was queried if we could add a way to change the height of rows too (eg # pixels tall they are), in addition to the font size.

**Comment by MKleusberg** [comment]
I've just added the requested option. I hope the new default values are working fine on all systems but the actual font size changing should definitely work. The default row height is changed automatically according to the font size to fit a line of text.

**Comment by justinclift** [comment]
I'll try this out on OSX (not tonight, brain dead tired).  But soon. :smile:

**Comment by MKleusberg** [comment]
Hi Justin,
have to had the time to look at this? :smile:

**Comment by justinclift** [comment]
Just tried it, and seems good to me personally.  I'll see if I can find the email that pinged me about this, and let them know to grab the latest nightly for confirmation too.

**Comment by justinclift** [comment]
Didn't find the original email, so this will have to do for the moment. :wink:
