### ISSUE TITLE
Unable to handle tables with '`' in the names

### ISSUE THREAD

**Issue by z-rui** [sqlitebrowser/sqlitebrowser#387]
If I create a table with the following SQL:
```sql
create table "table`1" (column1);
```
Then it cannot be editted with the graphical interface.

**Comment by justinclift** [comment]
Oh, that's interesting.  Sounds like our code for correctly escaping names isn't quite as good as it should be. :frowning:

**Comment by justinclift** [comment]
@z-rui Martin has added an initial fix for this.  Would you be ok to test out our latest code, and let us know if it's working for you?

If you're using Windows, our latest nightly build has the code in it.  Download locations for the nightly builds are on our front page. :smile:

**Comment by MKleusberg** [comment]
I've just pushed an additional commit which fixes some remaining issues with this (especially when quotes are used inside column names). The next nightly build hopefully works fine for you :smile:

**Comment by MKleusberg** [comment]
Are we ok to close this issue? I'm pretty sure it's working now in the latest builds :smile:

**Comment by justinclift** [comment]
Sure. :smile:
