### ISSUE TITLE
Need a keyboard shortcut for "Refresh the data in the selected table".

### ISSUE THREAD

**Issue by kinghelix** [sqlitebrowser/sqlitebrowser#388]
I'm used to pressing "Command-R" (on a mac) to refresh the current table. It would be great if this was added. Thanks!

**Comment by justinclift** [comment]
Should be do-able. :smile:

**Comment by MKleusberg** [comment]
You already can press F5 for refreshing the view but I've just added Ctrl+R (or I guess Command-R on MacOS) as an extra shortcut. You can download tomorrow's nightly build to test it if you like :smiley:

**Comment by justinclift** [comment]
The nightly builds are happening on OSX for now (waiting on the build box to be posted to me), so @kinghelix would have to compile it himself.

@kinghelix Compiling DB4S on OSX is really easy if you have Homebrew installed.  Is that your kind of thing? :smile:

**Comment by kinghelix** [comment]
Awesome, thanks! :)

**Comment by MKleusberg** [comment]
@kinghelix Our nightly build for MacOS X are back up and running. So if you haven't had the chance to compile by yourself you should be able to test the change now :smile: Either way I'd be happy to hear about the results :smile:

**Comment by justinclift** [comment]
@kinghelix Did you ever get around to trying this out?

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦

**Comment by kinghelix** [comment]
argh! sorry for the lack of response, i'm not usually on the actual github site, so i've just seen this notification.

just downloaded and tested the latest version, this works great!! thanks very much for it justin! the little things like this make all the difference

cheers

**Comment by justinclift** [comment]
The fix was by @MKleusberg, not myself, but no worries.  Glad it's working better now. :smile:
