### ISSUE TITLE
Win7 not used button

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#389]
In window "about program" button "?" not used
![default](https://cloud.githubusercontent.com/assets/6053197/8918362/30cf4980-34c0-11e5-96b9-172b6dd33d4e.png)

**Comment by justinclift** [comment]
Oh, good catch.  Sounds like a bug. :smile:

**Comment by justinclift** [comment]
Just tested this with version 3.8.0 in a Win 8.1 VM.  It's still occurring. :frowning:

**Comment by justinclift** [comment]
Good news @PKEv, this has been fixed today by @schdub.

The fix will be in our new 3.9.1 release, which will come our later on today. :smile:
