### ISSUE TITLE
crash then correct table

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#390]
to repeat:
1) create table,with some column
2) click "correct table"
3) add some column
4) move any column
![default](https://cloud.githubusercontent.com/assets/6053197/8919032/0692af40-34c5-11e5-9e98-d73f89c58713.png)
(update)

**Comment by justinclift** [comment]
Sounds like a bug, though I don't understand Russian personally so someone else will have to figure it out. :wink:

**Comment by GeorgijK** [comment]
Following information provided in russian: "Column rename: error releasing (freeing?) savepoint. DB says: [..] "

**Comment by justinclift** [comment]
Thanks @GeorgijK.

@MKleusberg Any ideas?

**Comment by MKleusberg** [comment]
I've looked into this and with any luck it should be fixed in the next nightly build :smiley: Let us know how if the fix works for you, @GeorgijK :smile:

**Comment by MKleusberg** [comment]
Oops, I ment @PKEv of course. Let us know if the next nightly build fixes your problem, @PKEv :smiley:

**Comment by justinclift** [comment]
@PKEv Do you have time to check the latest nightly build? :smile:

**Comment by PKEv** [comment]
test ver. from 12-Aug-2015
error persists

**Comment by justinclift** [comment]
@PKEv Thanks for testing. :smile:

@MKleusberg Looks like we still have work to do. :frowning:

**Comment by MKleusberg** [comment]
@PKEv Are you ok to test if the bug still occurs in the latest nightly build? To me it looks like it should be fixed by now :smile:

**Comment by PKEv** [comment]
corrected!!!

**Comment by justinclift** [comment]
Awesome. :smile:
