### ISSUE TITLE
Question: What are plugins for...

### ISSUE THREAD

**Issue by Bluscream** [sqlitebrowser/sqlitebrowser#392]
... and how to use them?

**Comment by justinclift** [comment]
Good question. :smile:

SQLite can be compiled with plugins/extensions.  The plugin tab in the gui is a way to have them loaded, so you can use these extensions in your SQL queries.

Personally, I've not used them ever, but some of the other guys know more about it.

**Comment by MKleusberg** [comment]
The best way to understand extensions is to not think of them extending our application (sqlitebrowser) but extending SQLite itself. SQLite extensions are just dynamic libraries (*.dll or *.so etc.) of a certain format which can be loaded by SQLite. After loading they provide additional functionality like extra SQL function (e.g. for doing maths or text operations) or collations (e.g. for special sort orders).

So, for example there is an extension for adding some functions for handling geo information. If you want to use these features for your database or if you want to open a database which was created using this extension, you have to load it too before proceeding.
But as long as you don't have a database which requires an extension to open (you usually get an error message when trying to open it) you probably won't need to load any extensions :smiley: 

For some more technical background you can also have a look at this page: https://www.sqlite.org/loadext.html

**Comment by justinclift** [comment]
@Bluscream Does that help enough? :smile:

**Comment by Bluscream** [comment]
Of course ^^ Thanks for your help @justinclift @MKleusberg :+1:
