### ISSUE TITLE
"Edit database cell" window moves down each time it is opened 

### ISSUE THREAD

**Issue by DelphiGit** [sqlitebrowser/sqlitebrowser#394]
Hi!

I'm using the Window's version of your great browser. One thing I've noticed is that each time I doubleclick on a cell and the window "Edit database cell" opens it moves further down the screen. After opening it a couple of times I need to move it back up before it disappears off screen. As you probably understand, it can be a bit irritating when doing lots of editing.
I would prefer if the edit-window always opened at the same position. Or even better if it opens in the position where it was last closed, to give the user control.
Hope this can be accomplished. :-) 

Have a nice day wherever you are!

**Comment by justinclift** [comment]
Interesting thought.  I've noticed similar before too. :smile:

Personally I'm not sure what controls (by default) where new windows are positions, but at a guess we're probably not specifying any positioning options, and maybe we should be. :wink:

**Comment by MKleusberg** [comment]
Personally, I don't experience this problem because on my (Linux) system the dialog is always centered above the main window. I've tried to implement the same behaviour for Windows now but can only assume it's working (because it looks the same as before to me). So with any luck this issue should be fixed for you in the next nightly build :smile: And please let me know if it doesn't work for you.

**Comment by DelphiGit** [comment]
Thank you very much MKleusberg, your fix makes it work a lot better. :smile: 
The first time after application start the Edit-window opens screen centered, but after that each subsequent opening is centered over the main window.

**Comment by DelphiGit** [comment]
This is broken in the nightly build (at least since August 29th). Now the Edit-window appears screen centered every second time, and halfway outside the top left corner of the screen every second time. I know nightly builds may contain oddities but I just thought I'd mention it so it doesn't remain like this when you make a final build. :-)
I'm back to using the build from August 19th.

**Comment by justinclift** [comment]
Yep it's good you mentioned it. :smile:

**Comment by DelphiGit** [comment]
I can add that where the Edit-window appears depends on the position of the main form, but it seems to alternate between two places. Maybe some kind of offset?
The position of the main form is stored when the application is closed, so wouldn't it be nice if you could add a setting in Preferences to also store the position of the Edit-window? I think that would be the most general solution.

I just had another thought. Since this thread is labeled "Fix applied" perhaps I should start a separate thread with this "new bug-report"?

May the force of SQL be with you. =D

**Comment by justinclift** [comment]
Yeah, start a new bug report :smile:

**Comment by justinclift** [comment]
@DelphiGit Should this one be closed now that your fix for #633 is merged?

**Comment by justinclift** [comment]
Closing this now, as @DelphiGit has fixed it in #633. :smile:
