### ISSUE TITLE
Program crashes on launch (Windows 7, 64 bit)

### ISSUE THREAD

**Issue by luckytoilet** [sqlitebrowser/sqlitebrowser#395]
Launching main exe (64 bit version) crashes immediately with the following error. Reproduced with version 3.7.0. Uninstalled and tried 32 bit version, runs fine.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	sqlitebrowser.exe
  Application Version:	0.0.0.0
  Application Timestamp:	557d5375
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f83ff
  Exception Code:	c000001d
  Exception Offset:	0000000000095c01
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	35c2
  Additional Information 2:	35c2dd30f908156967b892bc3a1f609a
  Additional Information 3:	763b
  Additional Information 4:	763b2cf89c4c307efcf840f78a41f957

**Comment by justinclift** [comment]
Hmmm, that doesn't sound good.  Do you have the (free) Microsoft Visual C++ Redistributable Packages for Visual Studio 2013 installed, available [here](https://www.microsoft.com/en-us/download/details.aspx?id=40784)?

**Comment by justinclift** [comment]
Closing this due to lack of response.  We've also released a new version (3.8.0) about a week ago, which shouldn't have this crashing problem.

If this problem still keeps happening for you for some reason, you're welcome to re-open this issue so we can investigate. :smile:

**Comment by ashok011154** [comment]
Launching main exe (64 bit version) crashes immediately with the following error. Reproduced with version 3.8.0. Uninstalled and tried 64 bit version, runs fine.
Problem Event Name: APPCRASH
Fault Module Name: MSVCR120.dll
Microsoft Visual C++ Redistributable Packages again reinstalled
but still the same issue
windows7 64 bit

**Comment by justinclift** [comment]
Yeah, it's not good this is happening for some people.  It's also really hard to track down. 😦 

Have you tried a recent nightly build instead?  They're generally more stable. :smile:

**Comment by mextedol** [comment]
I have the same problem event name, but the fault module name is atiumd64.dll and the exception offset is different.

**Comment by justinclift** [comment]
@mextedol If it helps, we have some steps shown here on ways to potentially track down the problem:

* https://github.com/sqlitebrowser/sqlitebrowser/issues/847#issuecomment-256713334
* https://github.com/sqlitebrowser/sqlitebrowser/issues/847#issuecomment-256763348

Are you ok to investigate using them?

**Comment by mextedol** [comment]
Ok.

**Comment by mextedol** [comment]
By the way the Exception code is the same.
