### ISSUE TITLE
cmake doesn't work on Centos/Fedora

### ISSUE THREAD

**Issue by syslogic** [sqlitebrowser/sqlitebrowser#396]
in order to meet the requirements: `sudo yum install qt-devel ant-antlr antlr-C++`
(not exactly sure about the C++ bindings). while it builds with `cmake . && make && sudo make install`.
please check and add to the build instructions - tested on CentOS 7.1.

**Comment by justinclift** [comment]
Sorry for the delay, I was away for a few days. :wink:

Does this seem ok?  If so, we can add it to BUILDING.md. :smile:

### CentOS / Fedora Linux

**1**. Make sure the `qt-devel`, `ant-antlr`, and `antlr-C++` packages are installed.<br />
```
$ sudo yum install qt-devel ant-antlr antlr-C++
```
**2**. Download the DB Browser for SQLite source code.<br />
**3**. Open a terminal in the source code directory.<br />
**4**. Run these commands:<br />
```bash
$ cmake . && make && sudo make install
```
**5**. This should complete without errors, and `sqlitebrowser` should now be launch-able from the command line.

Done. :)

**Comment by syslogic** [comment]
looks good. one probably would just need to validate the dependencies on a fresh install once,
because I'm not exactly sure if not others were already installed (they'll gonna complain, if not).

**Comment by justinclift** [comment]
Thanks Martin, just added them: https://github.com/sqlitebrowser/sqlitebrowser/commit/8bfd2852ae4c39af7c095b39679da5d3dc7c1237 :smile:

**Comment by subdriven** [comment]
Just FYI: you also need gcc-c++ or the build fails with a CXX error on Fedora 22/23.

**Comment by justinclift** [comment]
Any interest in submitting a PR with the info update? :smile:

**Comment by subdriven** [comment]
Sure, I can do that. I actually didn't end up installing from source since I ran into other issues with the build (it didn't find MAC or WIN but did find X11 and it wouldn't build).
So I did what I should have done from the start & looked in repo. Fedora actually packages it out so it's as easy as dnf install sqlitebrowser. I'll do a PR & update for Fedora 22/23.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by joekendal** [comment]
@justinclift still doesn't work

``sudo yum install qt-devel ant-antlr antlr-C++``

``cmake . ``

<code>
-- Found Antlr2: /usr/lib64/libantlr.a  
CMake Error at libs/qscintilla/Qt4Qt5/CMakeLists.txt:5 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/<username>/Downloads/sqlitebrowser-3.10.1/CMakeFiles/CMakeOutput.log".
</code>
