### ISSUE TITLE
question about compiling in win7

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#399]
Is it possible to assemble the project in windows ???

**Comment by justinclift** [comment]
When you say "assemble the project", are you meaning compile the project from source code?

If so, then yes.  There aren't good instructions written up for that yet though. :frowning:

**Comment by PKEv** [comment]
You may suggest where to start and what libraries are needed?

**Comment by justinclift** [comment]
I have some initial instructions which @schdub emailed us.  I can forward them on to you if you want to try them out.  Would that help? :smile: (my email address is justin@postgresql.org)

**Comment by justinclift** [comment]
Did the emailed instructions help?

**Comment by PKEv** [comment]
i try compile in qtcreator ... 
but why that was an error: "'::strcpy_s' has not been declared"

Try to go exactly according to instructions...

**Comment by justinclift** [comment]
Yeah, I don't know either.  Maybe @MKleusberg could guess what might cause that?

**Comment by MKleusberg** [comment]
Can't say without further information...
@PKEv There should be a filename and line number along with the error message. Can you provide that as well? Maybe the whole build output might contain some other valuable information, too.
@justinclift Can you mail me these build instructions, too? I don't think I have them here.

Still, it's going to be guesswork for me, too, cause I don't have a Windows machine here...

**Comment by justinclift** [comment]
Sorry @PKEv, I completely forgot about this open issue. 😦 

We've added very complete instructions for building on Windows, to the wiki:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

Lots of screenshots, and plenty of details.  If you're still wanting to get this working, those instructions are known to be good. :smile:
