### ISSUE TITLE
Invalid File Format on .db files

### ISSUE THREAD

**Issue by aleqria** [sqlitebrowser/sqlitebrowser#402]
On the Open Database dialog program asks me for the file and it reads the supported file types are ".db .db3 .sqlite .sqlite3".
But for some reason when I try to open "key.db" file from profile settings of Mozilla Firefox it prompts the plain message saying : "Invalid File Format". I was unable to find any working solution on the forums (i didnt try any solution talking about downgrading btw)
I'd be glad if you take a look

**Comment by rp-** [comment]
From what I read in a short google search key3.db is no sqlite database and there are other tools to recover or read the database.

http://kb.mozillazine.org/Password_Manager

**Comment by hurzl** [comment]
The same error I get with the android calendar db file /data/data/com.android.providers.calendar/databases/calendar.db

**Comment by justinclift** [comment]
Yeah, I think you need write access because SQLite itself makes some temporary files when it opens a database.

**Comment by hurzl** [comment]
Maybe the error message should say this then

**Comment by justinclift** [comment]
Not a bad suggestion.  It wouldn't hurt for us to detect this kind of error (if it's possible), and give a message about it.

**Comment by MKleusberg** [comment]
The next nightly build will try to detect a read only database file as well as a read only parent directory. I don't show any message box in this case but only add a subtle note to the status bar of the main window. All the buttons for editing the database are disabled in this case, too. So unless you're typing in an SQL statement yourself you won't be able to trigger any errors :smiley:

**Comment by hurzl** [comment]
That's the best behaviour imaginable :+1:

**Comment by justinclift** [comment]
Good thinking @MKleusberg. :smile:

@hurzl Have you had a chance to try the latest nightly build (or compile it yourself), to make 100% sure this is working well now from your point of view?

**Comment by hurzl** [comment]
No I'm just using the FreeBSD port

**Comment by justinclift** [comment]
No worries.  Was just wondering if this had been tested/verified so we can close it.  Looks like I'll need to try it out later, and see how it goes. :smile:

**Comment by SharonD214** [comment]
I'm getting this error message on a ssqlite db file...

**Comment by justinclift** [comment]
@SharonD214 Hmmm, that's not good.  If you try with the latest nightly build (if you're on Windows), does it give a more informative error message or act like it's in read-only mode?

**Comment by justinclift** [comment]
Closing this, as it was fixed ages ago. :smile:

@hurzl If for some reason this turns out to not work for you after all with our recent 3.8.0 release, please feel welcome to reopen this issue. :grin:
