### ISSUE TITLE
add ability to save graph

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#403]
There is no possibility to save graph on data, and it is not clear on how the data is plotted (selected table in another part of the window, and on the other tab)

**Comment by justinclift** [comment]
Good catch. :smile:

**Comment by MKleusberg** [comment]
You actually can save the graph (if that's what you mean); just press the little button on the bottom right of the plot pane:
![5](https://cloud.githubusercontent.com/assets/3153504/9479441/bd85c150-4b7d-11e5-8f82-e5b45a0f1c44.png)

**Comment by justinclift** [comment]
Oh cool.  I didn't realise that. :wink:

@PKEv Does that help?

**Comment by PKEv** [comment]
yes
