### ISSUE TITLE
json field not being shown

### ISSUE THREAD

**Issue by miltgrin** [sqlitebrowser/sqlitebrowser#407]
I have a table that contains a json field.  If I do a query of the table with no where clause the json field shows text.  However if I put in a where clause to pick a  particular set of records (1 or more), the json field only shows the word BLOB (in italic and light font) where the same same records without the where clause shows the text in the json field.  

Why does this happen?

**Comment by miltgrin** [comment]
Sorry.  This looks like it was already fixed in version 3.7.   I was running version 3.6.

**Comment by justinclift** [comment]
Cool. :smile:
