### ISSUE TITLE
DML not able to save

### ISSUE THREAD

**Issue by ashunigam** [sqlitebrowser/sqlitebrowser#412]
In an existing table with data, if you change the datatype it rollsback on saving. For example you import an csv file, and it uses id fields as text. Now you want to make it integer, you can not.

**Comment by justinclift** [comment]
That doesn't sound good.  Which OS are you using, and which version of DB4S?

**Comment by ashunigam** [comment]
Dear Justin,

I am using it on windows8.1.

Regards
Ashutosh

**Comment by justinclift** [comment]
Sorry for not looking into this properly yet. :frowning:

As a thought, we released a new version (3.8.0) just over a week ago, and it has a whole bunch of bug fixes in it.  I'm not sure if there's anything in there for transaction handling though, so I'm not sure if the behaviour you're reporting here is fixed or not.

Would you have a few minutes to try it out, and let us know? :smile:

**Comment by MKleusberg** [comment]
Closing this due to lack of response. If you're still having issues with this, please re-open this issue, @ashunigam. We always try to improve our application if we can :smile:
