### ISSUE TITLE
Positioning of "Edit database cell" window

### ISSUE THREAD

**Issue by DelphiGit** [sqlitebrowser/sqlitebrowser#413]
There was a previous problem (https://github.com/sqlitebrowser/sqlitebrowser/issues/394) in the Window's version that was fixed on August 19th 2015. Later it got broken, which I mentioned in that thread, but here's a new report with up-to-date information. :smiley: 
Now, the Edit-window is alternating between two places depending on the position of the main form. First it appears in one place, then the other next time it's opened. If the main window is moved, it's two different places. Sometimes half way outside the screen border.

The position of the main form is stored when the application is closed, so wouldn't it be a good idea if you added a setting in Preferences to also store the position of the Edit-window? Those who don't have any problems can leave that setting unchecked and will have the applications default behaviour. :smile:

**Comment by DelphiGit** [comment]
Just curious if I'm the only one seeing this strange behaviour? Perhaps most users on Windows stick to the release builds and therefore haven't experienced this yet? :)
I tried the nightly build from November 10th and, for me, it behaves the same erratic way as described in the post above.

**Comment by rp-** [comment]
This might be a qt bug than, as the nightly builds use the old qt 4.8 and the release version are build on a windows machine using qt 5.4 or newer

**Comment by revolter** [comment]
I have this problem too on Mac OS X El Capitan.

**Comment by justinclift** [comment]
Interesting.  @revolter Is this using version 3.8.0, and if so, is it one of the downloadable releases or was it compiled manually? :smile:

Asking because the downloadable releases for OSX (for 3.8.0) use Qt 5 instead of Qt4. (am actually considering going back to Qt4 for them :wink:)

**Comment by revolter** [comment]
Yes, 3.8.0, downloadable release with SQLCipher support. Is Qt 5 a beta release or something like that? I'm that kind of guy that likes to have the latest version to every thing and I find this possible downgrade to Qt 4 sad :( Or would it be temporarily until their bugs are fixed?

**Comment by justinclift** [comment]
It was the first time I've built the release with Qt5. :wink:

We've had a few reports of bugs, that may or may not have anything to do with that bit (I'm not sure).  So I'm thinking of making a new release with Qt4 or something to see if that fixes the problem.

Actually, I should make the nightlies for OSX build with Qt4 again, and see if the problem disappears for people.  That would help figure things out. :smile:

**Comment by justinclift** [comment]
Just tweaked the nightly build script for OSX.  It'll use Qt4 again from now on, until/if we change it back.  That should give us some more things to test, in order to figure out some of the reported OSX weirdness.

**Comment by xingped** [comment]
I'm seeing this on the 3.8.0 build of Windows x64 as well.

**Comment by justinclift** [comment]
@xingped If you try our nightly build for Windows, does the problem go away? :smile:

**Comment by DelphiGit** [comment]
I just tried it, and the Windows build still has the problem.

**Comment by justinclift** [comment]
Thanks for testing it @DelphiGit, that's useful info. :smile:

**Comment by justinclift** [comment]
@DelphiGit Same thought with this.  Should it be closed now too?

**Comment by DelphiGit** [comment]
Yes @justinclift I was going to suggest that myself, both this and #394, plus also #342.

**Comment by justinclift** [comment]
Awesome, thanks. :smile:
