### ISSUE TITLE
Improvement - Multi-line fields displayed on single line

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#416]
When a field contains line feeds, in the Browse Data tab, the contents are displayed on the same line but without any space between the lines.  I propose you replace line feeds with a space so as to look better as single line.  For example:

If fields contains:
Hello<CRLF>
World

It now displays as:
HelloWorld

(no space between Hello and World)

After my suggestion:
Hello World

**Comment by glawrence** [comment]
The other option would be to use another character like many text editors do when you "show hidden characters", that way we could show tabs and spaces as well

**Comment by tonypdmtr** [comment]
That would work also (even better, actually).  However, still a space should surround the special character or else again it will look as one word when printed as a single word.

**Comment by justinclift** [comment]
Yeah, "show hidden characters" sounds like a good idea. :smile:

**Comment by justinclift** [comment]
As a data point, although not the same bug as #731, they're both semi-related.

**Comment by mgrojo** [comment]
This was a Qt glitch and it seems fixed now.

> 
> DB Browser for SQLite Version 3.13.99 (Aug  4 2024)
> Last commit hash when built: 73ebe93e
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.15.3
> SQLite Version 3.37.2.

Feel free to reopen it if there is still something working in a current Qt and DB4S version.
