### ISSUE TITLE
Bug: deletion on attached database fails

### ISSUE THREAD

**Issue by AndreasMartin72** [sqlitebrowser/sqlitebrowser#417]
I tried to delete the content of a table "myTable" in an attached database "myDB":

DELETE FROM myDB.myTable;

And got the following error:
no such table: myDB.Tablename: DELETE FROM myDB.myTable
(Where "Tablename" is the name of a table in the main database)

The table itself exists, so a query on that table works:
SELECT \* FROM myDB.myTable;

Deletion on the main database works fine also:
DELETE FROM main.myTable;

Kindly regards,
Andreas Martin

**Comment by justinclift** [comment]
Oh, that's not good.  Which version are you running, and what OS is it on?

**Comment by justinclift** [comment]
Hmmm, is there a typo in your original post there?  It's saying **myDB**.myTable in the first bit, then **main**.myTable for the delete statement.

**Comment by justinclift** [comment]
Closing this as really ancient and no response.

**Comment by chrisjlocke** [comment]
This will be related to @MKleusberg's recent changes, so could be relevant now! ;)  Admittedly 2 years 'too soon', but hey, every improvement is a winner!
