### ISSUE TITLE
HD screen Scrolled list display 

### ISSUE THREAD

**Issue by raananb** [sqlitebrowser/sqlitebrowser#420]
Under Wndows, on a HD screen, the scrolled list of tables in the 'Browse data' tab is streched horizontally across the screen and becomes uncomfortably wide. It would be nice if its size could be adjusted to the size of the largest table name.
Vertically, the list shows only 10 entries whereas there is plenty of place to display a much longer list. My 23 tables could easily fit in one list (they do in the Database structure tab).

**Comment by justinclift** [comment]
Hmmm, trying to visualise that.  Would you be ok to add a screenshot in here? :smile:

**Comment by raananb** [comment]
Sure, no problem :

Thanks



Le 29/09/2015 13:27, Justin Clift a écrit :
>
> Hmmm, trying to visualise that. Would you be ok to add a screenshot in 
> here? :smile:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/420#issuecomment-144031418>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by raananb** [comment]
In my previous mail I sent a screenshot of about half the screen. The 
full screen is below, and you can see the problem of navigating the 
scrolled list...



Le 29/09/2015 13:27, Justin Clift a écrit :
>
> Hmmm, trying to visualise that. Would you be ok to add a screenshot in 
> here? :smile:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/420#issuecomment-144031418>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by justinclift** [comment]
Ahhh.  GitHub doesn't attach images sent via email.  You need to add them using the web based user interface. :frowning:

Sorry for the extra hassle. :innocent:

**Comment by raananb** [comment]
Please see the enclosed screenshot.
![db browser](https://cloud.githubusercontent.com/assets/8898267/10179264/25c9faa4-6705-11e5-81f2-4854f3a93577.jpg)

**Comment by raananb** [comment]
Done.

Le 29/09/2015 22:58, Justin Clift a écrit :
>
> Ahhh. GitHub doesn't attach images sent via email. You need to add 
> them using the web based user interface. :frowning:
>
> Sorry for the extra hassle. :innocent:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/420#issuecomment-144189444>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by justinclift** [comment]
Thanks, that makes it clear.  @MKleusberg Is this your kind of thing to fix? :smile:

**Comment by raananb** [comment]
Hi Justin,

DB Browser does not display records containing accented charaters. Is 
this the normal behavior? What needs to be done to display such records?

I switched the browser la nguage to French, but this does not modify the 
operation of DB Browser.

Regards,
Raanan


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by justinclift** [comment]
@raananb Hmmm, that's not good.  It's supposed to display all of the records.

As a thought, what happens if you try the latest nightly build?  Does it work there? :smile:

**Comment by raananb** [comment]
Same problem.

**Comment by justinclift** [comment]
@raananb With the problem displaying accented characters, do you have time to try our latest released version (3.8.0)?  It would be useful for us to know if that problem is still happening. :smile:

**Comment by raananb** [comment]
Hi Justin,

The accented words problem went away with 3.8.0.

The width of the 'Browse data' menu is still too large.

A request: include an option to 'Open the last opened base automatically'.

Regards,

Raanan

Le 05/01/2016 21:53, Justin Clift a écrit :
>
> @raananb <https://github.com/raananb> With the problem displaying 
> accented characters, do you have time to try our latest released 
> version (3.8.0)? It would be useful for us to know if that problem is 
> still happening. :smile:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/420#issuecomment-169130431>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by justinclift** [comment]
Thanks Raanan. :smile:

Yeah, we haven't done't anything with the width of that drop down in the Browse Data tab yet.  But we did fix a bug related to character display, which is why I asked. :wink:

Your idea for adding an option to automatically open the last opened database sounds good.  Made a new Issue for it [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/479), so we can keep track of it.  (We like to keep each problem/enhancement/etc in it's own issue, for better tracking.) :grin:

**Comment by raananb** [comment]
Hi Justin,

Thanks for accepting my suggestion, and a happy new year!

Raanan

Le 06/01/2016 12:01, Justin Clift a écrit :
>
> Thanks Raanan. :smile:
>
> Yeah, we haven't done't anything with the width of that drop down in 
> the Browse Data tab yet. But we did fix a bug related to character 
> display, which is why I asked. :wink:
>
> Your idea for adding an option to automatically open the last opened 
> database sounds good. Made a new Issue for it here 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/479>, so we can 
> keep track of it. (We like to keep each problem/enhancement/etc in 
> it's own issue, for better tracking.) :grin:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/420#issuecomment-169297779>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by justinclift** [comment]
You're welcome. Happy New Year to you too. :grin:

**Comment by mgrojo** [comment]
@raananb, we finally managed to add a sensible maximum for the browsed table combobox. Could you try with [tomorrow's nightly](https://nightlies.sqlitebrowser.org/latest/) and confirm that it's working as expected for you?

**Comment by MKleusberg** [comment]
Closing this because it looks like this issue is resolved and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time, @raananb :smile:
