### ISSUE TITLE
Wildcard escape

### ISSUE THREAD

**Issue by Aermec** [sqlitebrowser/sqlitebrowser#421]
I have many records with underscore char in the text.
But this char is also a wildcard so I'm not able to exclude unwanted items.
How can I escape wildcard in the filter textboxes?

**Comment by justinclift** [comment]
Hmmmm, that's a situation I haven't hit before.  Looking at this page, it **kind of** says that doubling up the character might work:

&nbsp; &nbsp; https://www.sqlite.org/lang_expr.html#like

Maybe try using two underscore characters in a row to mean one literal one?  Note, I haven't tried this as I'm focused on some non DB4S stuff at the moment.

**Comment by Aermec** [comment]
Already tried with no luck. Doubling the char doesn't work.
Thanks

**Comment by MKleusberg** [comment]
Sorry for the delay, I'm a bit short on time currently :frowning: 
If it's exact matches you want (i.e. not use the LIKE operator with its escaping problems at all) you can start your query with a '=' character: '=exact_hit' only matches records which are equal to 'exact_hit' (case-sensitive and no wildcards).
If you need the features of the LIKE operator you'll have to wait for tomorrow's nightly build which includes escpaing of the wildcard characters in the filter queries. The default escape character will be the backslash, so 'exact\_hit' will do the trick. If you prefer another character you'll be able to change it in the settings dialog.

Hope this helps :smiley:

**Comment by justinclift** [comment]
Thanks Martin. :smile:

And yeah, I'm short on time for DB4S at the moment too. :frowning:

**Comment by MKleusberg** [comment]
@Aermec Did you have time to try the nightly build? Wildcard escaping is added in there :smile:

**Comment by justinclift** [comment]
@Aermec Ping. :smile:

We released a new version (3.8.0) about a week ago, which includes the fix for this by @MKleusberg.  In theory it should be all good now.  Do you have a few moments to try it out and verify it from your point of view?

**Comment by justinclift** [comment]
@Aermec Ping 2?

**Comment by justinclift** [comment]
Closing this, as it "should be good".
