### ISSUE TITLE
Sqlite Browser Crashes on Start

### ISSUE THREAD

**Issue by naitik1995** [sqlitebrowser/sqlitebrowser#423]
I have downloaded the 64 bit version of sqlite browser. It appears to start normally and properly. As i do any activity on the browser for e.g. click on any button,an exception shows and the browser crashes. It goes off automatically. Please look into it and suggest some solution.

**Comment by justinclift** [comment]
Hmmm, that's unexpected.  If you're on windows, do you have "Microsoft Visual C++ Redistributable Packages for Visual Studio 2013" installed, available [here](https://www.microsoft.com/en-us/download/details.aspx?id=40784)?

**Comment by justinclift** [comment]
Closing this, due to lack of information.

**Comment by rithvikmundra** [comment]
Hi Justin... I have a similar issue....
I just installed the latest version of sqllite browser on my 64 bit windows 10 PC.
The sqllite browser opens and when i click on new databases, the application crashes.
Microsoft Visual C++ Redistributable 2013 is also installed on my PC.
Can you please provide me a solution for this problem?
