### ISSUE TITLE
Browser does not display all records

### ISSUE THREAD

**Issue by raananb** [sqlitebrowser/sqlitebrowser#424]
My base has 134 records in table 'Projets', as displayed by my application, but sqlitebrowser displays only 106 records.

I thought this was due to accented characters in the records, but that is not the cause.

Unfortunately, this panel does not allow to attach a base or an .xls file...

The base (Lightcomm.db, 150k) and the excel file (Projets.XLS, 8k) are available with
www.pixname.com/DBBrowser/Lightcomm.db
www.pixname.com/DBBrowser/Projets.XLS

**Comment by raananb** [comment]
I did not specify that this happens on Windows 8.1, with 

sqlitebrowser 
Version 3.7.0
Qt Version 5.4.1
SQLite Version 3.8.10.2

**Comment by MKleusberg** [comment]
I've just tried to reproduce this with the database you've linked but I get to see all 134 records. This makes debugging way more difficult, so I'll need your support for this :smiley: 
The first step would be to try the latest nightly build which you can download from here: https://github.com/sqlitebrowser/sqlitebrowser#windows

If it still won't work with this version we'll need to further investigate. In this case I'd need you to provide some more information. Is the total number of rows shown correctly (arrow 2 in the screenshot)? Or is that one correct and the actual number of rows shown is wrong (arrow 1 in the screenshort)?
![4](https://cloud.githubusercontent.com/assets/3153504/10289790/95b2c7a2-6ba0-11e5-8cb1-0b131f12b3c0.png)

**Comment by raananb** [comment]
Interesting: I uninstalled and reinstalled 3.7.0 64bits on Windows 8.1. 
and - surprise - all 134 records are there.

Thanks for your interest, and sorry for disturbing you.

Raanan Barzel

Le 05/10/2015 20:36, Martin Kleusberg a écrit :
>
> I've just tried to reproduce this with the database you've linked but 
> I get to see all 134 records. This makes debugging way more difficult, 
> so I'll need your support for this :smiley:
> The first step would be to try the latest nightly build which you can 
> download from here: https://github.com/sqlitebrowser/sqlitebrowser#windows
>
> If it still won't work with this version we'll need to further 
> investigate. In this case I'd need you to provide some more 
> information. Is the total number of rows shown correctly (arrow 2 in 
> the screenshot)? Or is that one correct and the actual number of rows 
> shown is wrong (arrow 1 in the screenshort)?
> 4 
> <https://cloud.githubusercontent.com/assets/3153504/10289790/95b2c7a2-6ba0-11e5-8cb1-0b131f12b3c0.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/424#issuecomment-145625535>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
http://www.avast.com

**Comment by justinclift** [comment]
No worries at all.  If it happens again, feel free to reopen this ticket. :smile:
