### ISSUE TITLE
Please add a reference to qhexedit homepage

### ISSUE THREAD

**Issue by Simsys** [sqlitebrowser/sqlitebrowser#427]
I'm happy to see the usage of qhexedit in the wild. I would be more happy, if you add a reference to

**Comment by Simsys** [comment]
https://github.com/Simsys/qhexedit2

**Comment by justinclift** [comment]
If you're up for it, would you be ok to submit a Pull Request adding a link to it where you feel is appropriate?  (eg adding a Thanks To + link to the README.md or something)

Just going for maximum laziness for myself personally atm (I'm focused elsewhere recently, not so much on DB4S). :smile:

**Comment by justinclift** [comment]
Hmmm, do we use qhexedit anywhere in our code?  If so, we're happy to add appropriate links/thanks/etc... :smile:

Asking this, because I don't '''think''' we do.  But I don't do coding in this project, so not familiar with the source so much... :wink:

**Comment by rp-** [comment]
yes we use qhexedit, it was introduced while @MKleusberg reworked the value editor dialog a long time ago.

https://github.com/sqlitebrowser/sqlitebrowser/tree/master/libs/qhexedit

**Comment by justinclift** [comment]
k, we can add some "Links to friends and related projects" or similar.  Maybe in both README.md, and the About dialog?
