### ISSUE TITLE
Monospace font not rendering properly

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#429]
With monospace fonts query editor rendering seems to be ignoring the proper space width. Screenshots below are both of the exact same text using 10pt Courier New with the red line 1px after the select keyword.

How it should look: Notepad++ 6.7.9
![notepad _6 7 9](https://cloud.githubusercontent.com/assets/12277525/10455659/f57223a2-7192-11e5-80ed-f36572dcbca8.png)

How it looks: DBBrowser 3.7.0
![dbbrowser_3 7 0](https://cloud.githubusercontent.com/assets/12277525/10455658/f5519a1a-7192-11e5-9b12-7a376d017c46.png)

Please note that spaces might not be the only characters involved and **_formatting_** might also affect the result.

Here is the text:
```
select sum(ValorNeto) as Neto, sum(ValorIVA + ValorNeto) as Total
  from NV
 inner join Entidad
    on NV.IdEntidad = Entidad.IdEntidad
 inner join NVEstado
    on NV.IdNVEstado = NVEstado.IdNVEstado
 where NV.IdNVEstado = {0}
       {1};
```

**Comment by justinclift** [comment]
Looking back over this... we did some font handling improvements for our recent 3.8.0 release a week or so ago.  Is there any chance you could give that a shot and see if that's better? :smile:

**Comment by palmiche** [comment]
Perfect! :+1: :+1: :+1: (I'm no longer suprised :grin:)

**Comment by justinclift** [comment]
Awesome!  Thanks @palmiche. :grin:
