### ISSUE TITLE
SQLite browser text filter does not work

### ISSUE THREAD

**Issue by ITS225EN** [sqlitebrowser/sqlitebrowser#430]
Hi GitHub,

I try your DB Brower for SQLite Version 3.8.10.2. The Browse Data text filter does not work at all. I will try it your next release again and see if your software is desirable. 

Best regards,

En Ych

**Comment by justinclift** [comment]
We have never released a version 3.8.10.2.  That's probably the SQLite version, not us. :wink:

You can check our version number in the About or Preferences dialog.  You should be using version 3.7.0, or a later nightly build.

Does that help? :smile:

**Comment by ITS225EN** [comment]
Hi Justin,

Please look below. When click the bug report of the program, it will go to your website.
[cid:image001.png@01D10693.56217F10]

Best regards,

En Yach

**Comment by glawrence** [comment]
I think @ITS225EN you will need to attach the image directory in GitHub, e-mailed images don't work, as far as I know, we certainly can't see your picture, sorry.

**Comment by ITS225EN** [comment]
Hi Geoff,

Later I download sqlitebrowser-3.7.0-win64.exe to try. This one works.

Thanks,

En Yach

**Comment by glawrence** [comment]
That's great news. Do you know what you had before exactly? Just in case there is an issue.

**Comment by justinclift** [comment]
Seems resolved, so closing this. :smile:
