### ISSUE TITLE
Cannot user Cyrillic characters in requests

### ISSUE THREAD

**Issue by eklipse2009** [sqlitebrowser/sqlitebrowser#431]
On "Execute SQL" tab I write:
SELECT default_image, russian FROM cards WHERE russian_lower LIKE "%тихо%"
I get:
SELECT default_image, russian FROM cards WHERE russian_lower LIKE "%????%"

**Comment by justinclift** [comment]
Ouch, that's not good.  Which version are you using, and on which OS?

If you're on Windows, please try the latest nightly build.  There are a bunch of fixes it in. :smile:
(download locations are on the front page of this project repo, if that helps)

**Comment by eklipse2009** [comment]
Windows 7, build 7601, 64 bit, I never do updates, because can't remember even once that they helped me with anything.

**Comment by justinclift** [comment]
Thanks. :)  That's the SQLite version number, not the version number for this software though. :wink:

Would you be ok to screenshot your Help → About dialog?  For example, this is mine:

![db4s about dialog 1](https://cloud.githubusercontent.com/assets/406299/10558843/9099d8fc-74d6-11e5-9e61-74b5767f1230.png)

**Comment by eklipse2009** [comment]
It's 3.6.0, I'll try the newer one and report.

**Comment by eklipse2009** [comment]
It's OK in 3.7.0, sorry for inconvenience.

**Comment by justinclift** [comment]
No problem.  Glad you got it working. :smile:
