### ISSUE TITLE
hot buttons for open last used  files

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#432]
It would be convenient to open recent files with combination: CTRL + 1 (2,3,4)

**Comment by justinclift** [comment]
Sounds like a good idea. :smile:

**Comment by MKleusberg** [comment]
Thanks for the suggestion. Just implemented it, so it should be the next nightly build :wink:

**Comment by justinclift** [comment]
@PKEv Do you have time to try out the next nightly build, and confirm back if it is/isn't working for you? :smile:

**Comment by PKEv** [comment]
Strange behavior.

actions:
open base
amend data
press the key combination (cntr + 1)
press (ESC) (2 times why?)
when you try to make a change in the base will be informed that it is locked

**Comment by justinclift** [comment]
Oh, that's not good.  @MKleusberg ?

**Comment by MKleusberg** [comment]
That's actually an old bug. So, nice catch, @PKEv :+1: Should be fixed by the latest commit.

**Comment by justinclift** [comment]
Awesome.  @PKEv Do you have time to verify the fix is good from your point of view? :smile:

**Comment by justinclift** [comment]
@PKEv Ping? :smile:

**Comment by PKEv** [comment]
all right

**Comment by justinclift** [comment]
Thank you @PKEv. :smile:
