### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChristophNiehoff** [sqlitebrowser/sqlitebrowser#433]
I have a question regarding the built-in plotting function. I observed that for larger databases (~ 2M entries) the plots look quite different compared to plots made with e.g. python. I also observed that the plots very much depend on the ordering of the entries in the database. 
Since the plots are extremely fast, I assume that you perform some kind of "thinning" before doing the plot? I am right about this? Could you elaborate about the details of how the plots are done?

Thanks,
Christoph Niehoff

**Comment by rp-** [comment]
I don't understand what you mean with look different?
The plots depend on what x and y axis(columns) you select,
and of course how your current select statement looks like.

And no there shouldn't be any data left out for plotting, all data that is returned from the select should be used to plot

**Comment by ChristophNiehoff** [comment]
Dear Rene,

thank you for you reply!

Let me give you an example.
When I perform the two following select's:
1) select dataA, dataB from DataBase order by dataA
2) select dataA, dataB from DataBase order by dataB
I assume that in both cases I have the same datapoints (or am I wrong here? I am quite new to SQL... ).
But when I make plots with dataA on the x-axis and dataB on the y-axis, I get totally different outcomes  for both cases (different distributions of datapoints and different plot ranges).

Also, I can make a plot with all points. Then I can perform a select that only returns entries, which are in a region, where the plot with all points didn't have any points. This select then shows that there are entries in the database, that the plot did not show...

I assume that this very much depends on the structure of my data. My database contains ~2M entries generated by ~500 different Markov Chains, so the data is pretty much "clustered"...

Thanks very much,
Christoph

**Comment by rp-** [comment]
I had a look at the code(some time has past since I wrote it) and I think I have not really accounted such order by statements and the plotting is still more or less some kind of prototype. So this is more or less a bug or missing functionality.

But I can say that we pass all the data returned from the statement to the plotting widget (qcustomplot), but as you noticed it may happen that some data is not shown, thats because it's not possible to draw every datapoint if the x-axis is too large and the plotting widget has to skip data.

**Comment by ChristophNiehoff** [comment]
Dear Rene,

thank you very much for taking the time to look into the code.  I think, this pretty much explains it. Thanks, that helped a lot.

All the best,
Christoph

**Comment by justinclift** [comment]
Is this issue something that can be closed, or is there more we need to do? :smile:
