### ISSUE TITLE
Clicking new DB on fresh install causes crash

### ISSUE THREAD

**Issue by staz1000** [sqlitebrowser/sqlitebrowser#436]
I've just installed 3.7 for the first time, I clicked New Database and this caused the application to crash. I also tried 3.6 and the same happens.

Clicking Open Database has the same effect.

I presume there's some conflict with my machine but I have no idea what that might be, everything else is running fine and it's only a 2 week old installation of W7.

**Comment by justinclift** [comment]
Hmmm, that's not good.  I'm not sure how to diagnose this though.

@rp- @MKleusberg Any ideas?  Maybe we need to add some logging/checkpoint code so we can figure out where the problem lies?

**Comment by michalfita** [comment]
Same for me on Windows 8.1 x64 on x64 version.
What a day, first Django migrations f*d up and now I can use that tool to review the database.

**Comment by rp-** [comment]
I don't know what exactly it is, but it might be something like this described qt bugs:
https://bugreports.qt.io/browse/QTBUG-33119
https://bugreports.qt.io/browse/QTBUG-41416

sounds like there is some conflict with shell extensions

**Comment by justinclift** [comment]
@staz1000 @michalfita As a thought, we've made a new release since this was reported.  That **might** fix the problem.  If not, then trying the latest nightly build may work instead, as that uses a different (static) build process.

Would either of you have time to try, and let us know if one of those approaches works for you? :smile:

**Comment by justinclift** [comment]
@staz1000 @michalfita Ping?  There's a decent chance this is fixed now in our latest release. :smile:

**Comment by michalfita** [comment]
Now it looks good. 64-bit version runs fine and the open dialog doesn't
cause crash. I'm able to browse my test database from Django application.

Thank you very much.

Regards / Pozdrawiam,
Michał Fita

2016-01-06 21:10 GMT+00:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment]
Awesome!  Thanks for testing it and letting us know Michał. :grinning:
