### ISSUE TITLE
SQLite Browser rejects SQLite 3 Affinity Data Types

### ISSUE THREAD

**Issue by quantum-x** [sqlitebrowser/sqlitebrowser#438]
Picking up on #184 
- SQLite 3 seems to use affinity types - ( https://www.sqlite.org/datatype3.html#affinity ) - and has baked in support for column types such as 'DATETIME' etc.

In SQLite Browser, if I execute the SQL that creates a columntype of DATETIME, SQLite supports it, and DATETIME is shown for the column type.

However, when trying to add / edit a column type, these types are not supported, even if I type them in manually.

Perhaps the default column types could be listed, but the add / edit dropdown will accept custom types as well.

I feel this qualifies as a bug - as I can't use your tool to access a built-in function of SQLite.

Thanks kindly

**Comment by justinclift** [comment]
@quantum-x Apologies, someone I missed this issue completely. :frowning: 

Reading over this, this bit confuses me:

```
... when trying to add / edit a column type, these types are not supported, even if I
type them in manually.
```

When you manually put in a data type, what happens?  I'm trying to understand the behaviour you're experiencing, that's lets you know it's unsupported.

(screenshots are really helpful, if that's workable :grin:)

**Comment by mgrojo** [comment]
Either the problem is already solved or I don't understand the issue. @quantum-x Are you still there?

**Comment by chrisjlocke** [comment]
It used to be a bug where entering a custom type was ignored unless [Enter] was pressed.  This was 'recently' (probably a while ago, actually) fixed.
@quantum-x might be experiencing this phenomenenenenum.
@quantum-x - are you using the latest build?

**Comment by karim** [comment]
Closed due to lack of response.

@quantum-x If you are still having issues, please reopen this again.
