### ISSUE TITLE
Invalid file format for Chrome History file

### ISSUE THREAD

**Issue by textractor** [sqlitebrowser/sqlitebrowser#439]
Chrome (latest, Mac OSX 10.10) has a History file that is in SQLite format. But opening it with sqlitebrowser 3.7.0 gives the "Invalid file format" error.

**Comment by justinclift** [comment]
In theory :smile: the two main things which can cause that error are either a file not really being in SQLite format, or not having write access to the file. That being said, theory isn't always perfect. ;)

Are you absolutely sure it's a SQLite format file?  Can you open the file with the SQLite cli?

**Comment by textractor** [comment]
So I was told it was in SQLite format. And I can open it in sqlite3:

```
$ sqlite3 
SQLite version 3.8.4.1 2014-03-11 15:27:36
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open History
sqlite> .tables
downloads             meta                  urls                
downloads_url_chains  segment_usage         visit_source        
keyword_search_terms  segments              visits           
```

**Comment by justinclift** [comment]
Yep, that's a SQLite file then. :wink:

Ok, it looks like something unexpected is happening.  Out of curiosity, do you use Homebrew on your OSX box?  If so, would you be ok to try compiling our latest source code and see if that's work better?  We've fixed a large amount of bugs since the last release (and are very overdue for the next release).

It's very very easy to compile, if you're already using Homebrew.  You can literally cut-n-paste the instructions. :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

**Comment by textractor** [comment]
At the `qmake` step, I'm getting `QMAKESPEC has not been set, so configuration cannot be deduced.
Error processing project file: /Users/igallevy/source/sqlitebrowser/sqlitebrowser.pro`.

Looking at Note 2 in the build section (referenced by your link), I see that I should run one of the `qmake -spec` commands, but there is no context given for which. So I ran `qmake -spec macx-llvm`, which seemed to work. However, after I copied the .app to Applications and attempted to start, I got the following dialog:

**sqlitebrowser cannot be opened because of a problem.**

So perhaps it should have been compiled with the other `qmake -spec`, but I'm far from knowing. I did retrace steps and tried it (same result), but some cleaning up may have been needed before trying that.

If I get the time I'll try starting from scratch if all that entails is blowing away the sqlitebrowser source I checked out. Or maybe you'll have a new build done sooner :pray:

**Comment by justinclift** [comment]
Yeah, I'm not sure which of those two options to try, as I've never hit the problem myself and don't really know what causes it.  So yeah, blow things away then try the other one I guess. :wink:

**Comment by justinclift** [comment]
@textractor Do you get this working in the end? :smile:

**Comment by jacobweber** [comment]
I had this problem, but I think it was because Chrome had the file open while sqlitebrowser was trying to read it. I made a copy of the file, and sqlitebrowser was able to open it.

**Comment by justinclift** [comment]
Thanks Jacob, that's good info. :smile:

**Comment by justinclift** [comment]
Hmmm, I'm going to close this issue. It sounds like it probably something transient, and not really to do with DB4S (sqlitebrowser) itself.
