### ISSUE TITLE
Expanded grid cell view to allow complete (or as much as possible) cell data to be displayed

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#440]
When moving in the browser grid from cell to cell, it'd be nice to have the full contents of that cell display in some full-width textbox (e.g., at the bottom of the screen -- like with a status line).

This is much faster than entering/exiting the editor for each cell when quickly browsing the data.

(If this is also a multi-line textbox, it could also take care of issue #416 I created earlier.)

**Comment by MKleusberg** [comment]
@tonypdmtr Can you try tomorrow's nightly build? I've added a new option to the View menu called "Edit cell" which basically takes the Edit dialog which used to be opened when double clicking a cell and turns it into a dock widget which is attached to the bottom of the main window. I hope this takes care of your issues :smile:

**Comment by tonypdmtr** [comment]
@MKleusberg Thanks for this.  I tried it and it looks very good.  However, double clicking (IMHO) still slows it down more than it's necessary.  How about the edit box being refreshed as soon as move the cursor from cell to cell, without any extra action, e.g., when navigating with the arrow keys.  (I personally tend to use the keyboard more than the mouse.)  Thanks again.

**Comment by MKleusberg** [comment]
Yup, I somehow forgot the keyboard use case :wink: With the next nightly build you'll be able to navigate with the arrow keys and move the foucs down to the editor by pressing the Return key. It's still not perfect (for getting back to the table view you probably need the mouse) but I hope I'll be able to put some more time into this soon :smile:

**Comment by mgrojo** [comment]
I'll close this, since it is currently working as requested. There is also  #481 for the specific case of the Cell Editor update from the Execute SQL results.
