### ISSUE TITLE
Image viewer or preview for blob fields that contain images

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#441]
Also, dragging a picture to a blob field could insert that picture.  Now, it crashes.

**Comment by MKleusberg** [comment]
There already should be an image viewer which gets opened when you double click the cell. We don't show the images in place because of performance reasons: checking if a cell value is an image we can open, then getting the dimensions, scaling it and rendering it in place is probably too costly for larger tables.

As for the crash: I think the application tries to open the image as a new database file. I fully agree her: This should be fixed as this behaviour makes no sense here at all.

**Comment by MKleusberg** [comment]
Quick update regarding your main point, the image viewer. I've just pushed a new commit which you can try if you download tomorrow's nightly build. It adds a new option to the View menu called "Edit cell". If you enable this option the Edit dlalog which used to be opened by double clicking a cell is permanently opened and attached to the bottom of the main window (though it can be moved around). This way you can see a preview of at least the image stored in the current cell without extra clicks.

**Comment by justinclift** [comment]
@tonypdmtr Do you have a few minutes to try this new code out, and let us know if the behaviour now is good from your point of view? :smile:

**Comment by tonypdmtr** [comment]
@justinclift I just did with the current nightly build.  It works much better now.  However, (again) being a keyboard person myself, I would like the focus to stay in the cell I was, rather than move to the editor.  That way, I can move over the grid using arrow keys (rather than mouse cliks), without losing focus all the time.  Try using it with the keyboard arrow key, and you'll see what I mean.  With the mouse it works great.

Suggestion: How about you keep the focus the way it is now when someone uses the mouse to click, but keep the original cell focus if the keyboard is used.  That should make both use cases work the best.

(BTW, the drag-n-drop still does not work.  I think it tries to open dragged file as SQLite3 instead of a blob to be inserted in the dropped at cell.  Not a big deal, though.)

**Comment by justinclift** [comment]
Makes sense. :smile:

@MKleusberg Thoughts? :wink:

**Comment by MKleusberg** [comment]
Yep, makes sense. I've changed it to work better with the keyboard use case now. The focus stays on the table view where you can move the cursor using the arrow keys but the editor below is updated accordingly. And you can press Return or double click to move the focus down to the editor.

I haven't had the time yet to implement the drag and drop but it's definitely on my list :smile:

**Comment by MKleusberg** [comment]
@tonypdmtr Just implemented the drag & drop functionality as well. So with the next nightly build you'll be able to drop image files onto a cell, too :smile:

**Comment by justinclift** [comment]
Awesome Martin. :grinning: 

@tonypdmtr Would you be ok to try the nightly build (tomorrow), and let us know what you reckon now? :smile:

**Comment by tonypdmtr** [comment]
Works great! Thanks!

I only noticed one more issue (a bit unrelated to this) with the edit box.  I can make a different ticket for it, if you like.  But, while we're on the subject, I'll mention it here:

When ESC is pressed from within the edit box, it minimizes to the left lower corner. If you try to double-click on it (or the min/max icon) to make it big again, it completely vanishes (it becomes floating -- instead of docked -- but nowhere to be found).  Even trying to re-enable it from the 'View/Edit Cell' does not bring it back.  Only way I found to bring it back is to close the app and re-open it.  So, something is not quite right there.

So, maybe when restoring the edit box, center it on the screen and bring to front for easy locating.

Thanks to all for your great work!

**Comment by justinclift** [comment]
Yep, that definitely sounds like a bug.  @MKleusberg ? :wink:

**Comment by MKleusberg** [comment]
Noticed that yesterday, too, but didnt have the time to fix it :wink: But it should be fixed now (in the next nightly build).

**Comment by justinclift** [comment]
Awesome. :grin:

@tonypdmtr You ok to test that too (tomorrow) and confirm back?

**Comment by tonypdmtr** [comment]
Perfect!  Many thanks.

**Comment by tonypdmtr** [comment]
If I'm browsing a view (instead of a table) the cell data isn't shown in the editor.  Of course I cannot possibly edit a view, but how about having the data display there in read-only mode so it takes care of the original issue of seeing the whole field?
Is read-only edit box possible?

**Comment by MKleusberg** [comment]
Yes, that's possible :smile: I've changed the code to update the editor even when being in a view. For everybody still using the old windowed mode without the dock it's now possible to open the editor window for views, too. Might be interesting when havin BLOBs or multi-line text in a cell. So (again :wink: ), the next nightly build should fix this issue.

You're quite a thorough tester by the way, @tonypdmtr :smile: Thank you for the time you're puttin into this! I'd be happy to hear about any other issues you stumble upon.

**Comment by justinclift** [comment]
Awesome. :smile:  @tonypdmtr If you have time, please let us know if the new view display code bit Martin just added works well for you (tomorrow). :wink:

**Comment by tonypdmtr** [comment]
Great!

My final (I hope) observation is a really minor remaining issue:
You enter the edit box and type something, and instead of accepting it (with OK or CTRL-ENTER), you press ESC and go back out to the grid cell.  The value in the edit box does not revert back to the original (unless you move away from the cell and back on it).  It stays modified so the cell and the edit box no longer match either other.

Thank you all again for all your work (and immediate responsiveness).

**Comment by MKleusberg** [comment]
Fixed it :wink: Sorry for the all the delays but, again, it'll be in the next nightly build.

As for your P.S.
1. I think Ctrl+Z is difficult because I'd expect it to be an undo of the last action and not a revert of all my work. So, for reverting I'd prefer another shortcut, maybe more complicated to not press it accidentally.
2. This makes sense. And yet it looks strange for me when I change the fonts. Maybe it's just me because I got used to the fonts as they are, though... What do you think, @justinclift and others reading here? Make both fonts the same or both configurable? Currently the table grid font is configurable but the editor font is always set to Monospace.

**Comment by justinclift** [comment]
Hmmmm, if it's not hard to do, make then both configurable? :smile:

**Comment by tonypdmtr** [comment]
One more similar to the previous one:
If you edit directly on the grid cell, and press enter you go to the Edit Box but with the previous contents of the cell -- even though the cell has been edited already.

**Comment by MKleusberg** [comment]
@tonypdmtr Fixed that, too :wink: Thanks again for all your testing efforts!

**Comment by justinclift** [comment]
Awesome. :grin:

**Comment by justinclift** [comment]
Hmmm, we should probably close this issue, as it makes tracking things untidy having several bundled into one. :wink:

**Comment by tonypdmtr** [comment]
Sure.
