### ISSUE TITLE
Crashes on exporting as SQL

### ISSUE THREAD

**Issue by MrScorp** [sqlitebrowser/sqlitebrowser#442]
SQLite Browser Version : 3.7.0
OS : Windows 10 64 bit
Steps : 
1. File->Export->Database to SQL file
2. Select New INSERT INTO syntax..
File selection window opens, and the the program crashes 

![issue](https://cloud.githubusercontent.com/assets/12444895/11015554/326a49e2-8589-11e5-81ef-4e01a6faa5be.jpg)

**Comment by MKleusberg** [comment]
Hmm, I can't seem to reproduce this behaviour. So I think we have two options:
1) You could try the latest nightly build from here (https://github.com/sqlitebrowser/sqlitebrowser#windows). Maybe the new version already solves your problem.
2) If this doesn't work and there's no sensitive data inside your file you could mail us the file for further debugging. Also, if the issue remains after deleting some tables etc. (i.e. eliminating possible error sources) you can send us the smaller file.

**Comment by justinclift** [comment]
@MrScorp Sorry for the delay.  Are you still needing assistance with this? :smile:

**Comment by justinclift** [comment]
@MrScorp We released a new version (3.8.0) about a week ago.  Would you be ok to try that and let us know if the crash still happens for you?

**Comment by justinclift** [comment]
Closing this due to lack of feedback.

@MrScorp There's a pretty good chance this was fixed in our recent 3.8.0 release.  If you get a chance to try that and it still crashes for you, please feel welcome to either re-open this issue or create a new one (either is good). :smile:
