### ISSUE TITLE
Add a key combination for setting fields to NULL

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#443]
In the Browse Data tab, it would be useful to have a "Set as NULL" button next to the New Record and Delete Record button.

This new "Set as NULL" button would simply set whichever fields (including multiple) are presently selected to NULL.

At present it's possible to go into each individual field, double click on it to open the edit dialog, and set the field to NULL that way.  However, that's a real PITA when needing to set quite a lot of individual fields in a table (which aren't easily selectable via straight SQL).

Guessing this would be pretty easy to implement too. :smile:

**Comment by MKleusberg** [comment]
I've added a keyboard shortcut for now (or actually two because the normal delete didn't work either). You can press delete now to set all selected cells to empty string and press Alt+Delete to set them to Null. No button yet because I wanted to hear whether people prefer a button here or a context menu. I feel like a button might be inconsistent when not adding a button for setting to empty string as well; and that's two buttons already for a feature I personally would be looking for in a context menu ;)

**Comment by MKleusberg** [comment]
With the latest commit there's a new menu item "View->Edit Cell" which adds the Edit dialog to the main window area and keeps it opened. So that's a way to have the Clear Data button in the main window now :smile:

**Comment by justinclift** [comment]
Cool.  Back home now, so I might get time to play with this later today.

With the keyboard shortcut approach, yeah that's probably good enough.  Hadn't thought of it when writing this Issue up, only thinking of "lets add a button". :wink:

**Comment by justinclift** [comment]
Just tried this out with 3.8.0 (on OSX), and something doesn't seem right with the Alt-Delete for setting NULL.  When I do that with multiple fields selected the value is cleared from the cell visually... but no "NULL" keyword text appears in place.  If I do it manually for an individual cell through the "Edit data cell" dialog instead (eg binary mode → Clear → OK), then the cell value displayed as NULL.

**Comment by tonypdmtr** [comment]
This keyboard shortcut to set a field to NULL still does not work correctly, I suppose.  It behaves the same a plain DELETE, the field is emptied but not NULLed.
(BTW, Ctrl-Delete feels like a more intuitive choice to Alt-Delete.)

**Comment by justinclift** [comment]
Closing this, as <kbd>Alt</kbd>+<kbd>Delete</kbd> to set NULL definitely now works in recent nightly builds.  <kbd>Alt</kbd>+<kbd>Backspace</kbd> (for the same effect) was added today too. :smile:
