### ISSUE TITLE
Program doesn't work on Windows 7 OS

### ISSUE THREAD

**Issue by Bailey26** [sqlitebrowser/sqlitebrowser#446]
Neither of the Windows 64-bit releases work on my computer. I am on a 64-bit Windows 7 OS. I open the application and click "New Database." Then an error message shows saying "sqlitebrowser.exe" has stopped working. My machine then automatically closes the program. This program does not work.

**Comment by justinclift** [comment]
Hmmm, that's unexpected.  Is there an error in the Windows system log or application log with more info?

It sounds like there's a bad .dll or something on your computer, making it crash.  That's a pure guess though, so we need to look for more accurate error info.

**Comment by Bailey26** [comment]
This is the log I found for the error. Do you know how to fix it? 
Faulting application name: sqlitebrowser.exe, version: 0.0.0.0, time stamp: 0x5548f5ba
Faulting module name: ntdll.dll, version: 6.1.7601.19045, time stamp: 0x56259295
Exception code: 0xc0000005
Fault offset: 
Faulting process id: 
Faulting application start time: 0x01d12575726a93e9
Faulting application path: C:\Program Files\SqliteBrowser3\bin\sqlitebrowser.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll

**Comment by glawrence** [comment]
I suggest you try searching the internet for "Exception code: 0xc0000005" which returns all sorts of possible causes from bad memory to corrupt video drivers, if you add in "ntdll.dll" then you might find something more specific or helpful. However I am sorry to say this suggests the problem is with your computer and not DB Browser for SQLite. If you have access to another computer with Windows 7 you could try running DB Browser for SQLite on there.

**Comment by Bailey26** [comment]
But how come its never been an issue before? I think that file is a link library that is used by a lot of programs. How come it only fails with your application?

**Comment by justinclift** [comment]
Well, we know for sure it works on other Windows 7 computers.  However, that doesn't help you. :wink:

As a thought, would you be ok to download and install this?  It **might** help.  At the very least, it shouldn't make things worse:

&nbsp; &nbsp; https://www.microsoft.com/en-us/download/details.aspx?id=40784

The only other thing I'm wondering is if your system has all of the latest Microsoft updates applied?  Do you keep it patched up to date?

**Comment by TrustyWolf** [comment]
It works well on my Windows 7 64-bit computer ^_^

**Comment by justinclift** [comment]
Thanks @TrustyWolf . :)

@Bailey26 Have you had a chance to investigate this more?

**Comment by gauravkolekar** [comment]
I'm having the same problem on a windows 10 machine

**Comment by justinclift** [comment]
Interesting.  There's a reasonable chance the Windows nightly build will work since it uses a different (static) build process.

@gauravkolekar Would you be ok to try it?  Download locations are on our front page, if that helps. :smile:

**Comment by gauravkolekar** [comment]
Yup, that worked ! thanks !

**Comment by justinclift** [comment]
Awesome, definitely something unhappy with the .dll's then. :wink:

@Bailey26 Do you still need a solution for this?  If so, the nightly builds seem to work ok. :smile:
