### ISSUE TITLE
How did you guys deploy with less Qt frameworks?

### ISSUE THREAD

**Issue by volomike** [sqlitebrowser/sqlitebrowser#449]
This isn't an issue with sqlitebrowser -- I didn't know the appropriate way to reach you.

When I look at the OSX .app Frameworks folder of sqlitebrowser, I noticed that your project is much smaller than my Qt app -- you utilize less Qt framework bundles. How did you get your application to support that? For instance, I'm not using QtQuick or QML in my Qt/C++ application. However, when I run my project through macdeployqt, it includes these frameworks in my app bundle. When I try to remove them, my application won't load.

**Comment by justinclift** [comment]
Heya. :smile:

I do the packaging for the OSX binaries.  I don't really know it in depth... it's more something that I figured out after a bit of reading and has worked from that point forwards.

If it helps, this is the exact script used to build the nightly OSX binaries:

&nbsp; &nbsp; https://gist.github.com/justinclift/38887c1cfe480adfb11b

They used to be built on an OSX 10.7 machine.  That's machine was recently (2015-11-20) updated to running OSX 10.10.  The binaries generated are now a lot larger.  Not really thinking the upgrade was a win, personally. :frowning:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/nightly/

I haven't looked into why.  If you want to though, the info might be interesting to a lot of people. :smile:

**Comment by volomike** [comment]
I found what's going on in my Qt/C++ app. Once I included QtWebKit, it
increased the size by several MB and forced the adding of QtQML and
QtQuick, even though I'm not using those. If I don't add that, the other
frameworks don't get deployed by macdeployqt.


On Sun, Nov 29, 2015 at 8:21 PM, Justin Clift <notifications@github.com>
wrote:

> Heya. [image: :smile:]
>
> I do the packaging for the OSX binaries. I don't really know it in
> depth... it's more something that I figured out after a bit of reading and
> has worked from that point forwards.
>
> If it helps, this is the exact script used to build the nightly OSX
> binaries:
>
>     https://gist.github.com/justinclift/38887c1cfe480adfb11b
>
> They used to be built on an OSX 10.7 machine. That's machine was recently
> (2015-11-20) updated to running OSX 10.10. The binaries generated are now a
> lot larger. Not really thinking the upgrade was a win, personally. [image:
> :frowning:]
>
>     http://mirror.salasaga.org/sqlitebrowser/nightly/
>
> I haven't looked into why. If you want to though, the info might be
> interesting to a lot of people. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/449#issuecomment-160492658>
> .
>



-- 

Mike McKee

CEO

Volo International

Myrtle Beach, SC

Skype: volomike

Phone: 843-933-5544

http://volointernational.io

**Comment by justinclift** [comment]
Sounds like there's some dependencies between them or something then.

Um, do we still need to leave this issue open for you? :wink:

**Comment by volomike** [comment]
Nope, close it. Just didn't now to reach someone really experienced in this
field. Sorry to place a ticket like this.  Thanks so much for your
assistance! :)

On Sun, Nov 29, 2015 at 10:21 PM, Justin Clift <notifications@github.com>
wrote:

> Sounds like there's some dependencies between them or something then.
>
> Um, do we still need to leave this issue open for you? [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sqlitebrowser/sqlitebrowser/issues/449#issuecomment-160506735>
> .
>



-- 

Mike McKee

CEO

Volo International

Myrtle Beach, SC

Skype: volomike

Phone: 843-933-5544

http://volointernational.io

**Comment by justinclift** [comment]
No worries at all.  Glad you got it figured out-ish. :smile:
