### ISSUE TITLE
Filter with operators greater/less not working

### ISSUE THREAD

**Issue by Talon01** [sqlitebrowser/sqlitebrowser#450]
In table view I added a filter for a column. The column contains a text representation of a date as yyyy-mm-dd (e. g. 2013-04-27).

**Example 1** 
Filter `>2010`
SQL-Log: `SELECT rowid,* FROM msgs_view WHERE 1=1 AND date > 2010 ORDER BY date DESC LIMIT 0, 50000;`
Problem: It's a text field but filtering is done numeric. 

**Example 2**
Filter `>2010-10-01`
SQL-Log: `SELECT rowid,* FROM msgs_view WHERE 1=1 AND date LIKE '>2010-10-01' ORDER BY date DESC LIMIT 0, 50000;`
Problem: It's executed as LIKE filter and not as GREATER THAN

**Remark**
There is always an additional sql execution to detect the number of rows
`SELECT COUNT(*) FROM (SELECT rowid,* FROM msgs_view WHERE 1=1 AND date LIKE '>2010-10-01' ORDER BY date DESC);`
Shouldnt ORDERY BY be omitted for performance reasons?

**Comment by justinclift** [comment]
@MKleusberg - Yours? :smile:

**Comment by mgrojo** [comment]
@Talon01 You're issue should be solved after PR  #1473. Could you confirm it using one [nightly build](https://nightlies.sqlitebrowser.org/latest/) so we can close this issue?

**Comment by chrisjlocke** [comment]
I'll close this, as it seems resolved, although @Talon01 hasn't confirmed.  I've tested it, and a filter of '>2018-06-01' produces the following SQL:

    SELECT "_rowid_",* FROM "main"."transactions" WHERE "date" > '2018-06-01' LIMIT 0, 49999;

So that seems correct.  Thanks @mgrojo for the fix.
