### ISSUE TITLE
Set Pragmas that should always used

### ISSUE THREAD

**Issue by DevynCJohnson** [sqlitebrowser/sqlitebrowser#451]
I have some Pragmas that I set in ~/.sqliterc . However, the SQLiteBrowser does not seem to use this file. How can I force SQLiteBrowser to always use Pragmas with a preset value? In other words, how can I make "secure delete" always false (unchecked) without having to change it in "Edit Pragmas"? I would also like to make "Temp Store" and "Journal Mode" always set to "Memory".

**Comment by justinclift** [comment]
That's a good question.  Not something I know about personally, but it shouldn't be super hard to figure out a way to make it work.

**Comment by justinclift** [comment]
By the way, which OS are you using it on? :smile:

**Comment by DevynCJohnson** [comment]
Ubuntu

**Comment by MKleusberg** [comment]
I'll have to think about this issue a little more. But as a first question: would it be ok for you to have to configure the PRAGMAs using the GUI editor? Like having a default pragmas page somewhere? But this would mean that we ignore the sqliterc file. The reason for this is that the sqliterc doesn't contain standard SQL but only the commands starting with a dot which are specifically for the command line tool; and I want to avoid writing a parser for that since I'm not expecting that many users will even notice the feature :wink:

**Comment by DevynCJohnson** [comment]
The GUI-editor would be fine if I only ever had to set the PRAGMAs once and then always use the same settings.

**Comment by MKleusberg** [comment]
Ok, this might be a silly approach to your issue but I've just added a way which should work for you. If you rebuild the latest code this should do the trick:
* Click View -> Preferences
* Click on the Database tab, then click on Advanced
* You'll now see a SQL editor where you type in arbitrary SQL statements
* Type in your PRAGMAs in there, one per line, terminated by semicolons - just like you'd be executing them in the Execute SQL area of the program

Now these PRAGMAs will be executed whenever you open an existing database or create a new one. I hope this helps :smile:

**Comment by justinclift** [comment]
@DevynCJohnson We released a new version (3.8.0) about a week ago, with some bits added for this as @MKleusberg describes above.  Do you have a few moments to try it out and let us know if this now works decently for you? :smile:

**Comment by justinclift** [comment]
@DevynCJohnson Did you ever get around to trying this out?

Note - I'm just looking to close out old issues which have probably been taken care of.  If the fix for this isn't working as intended, and it's something you care about, definitely let us know. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.
