### ISSUE TITLE
Allow to configure shortcuts.

### ISSUE THREAD

**Issue by ypid** [sqlitebrowser/sqlitebrowser#454]
This would require to change it in the code as well as in the i18n files.

**Comment by justinclift** [comment]
When you say "shortcuts", what are you meaning? :smile:

**Comment by ypid** [comment]
I mean the key combinations to for example run a query.

That sort of thing :wink: https://github.com/sqlitebrowser/sqlitebrowser/blob/9582786237792f9db010fb6b18f6e43dd558e589/src/EditDialog.cpp#L17

**Comment by justinclift** [comment]
Ahhh, understood.  Yeah, that makes sense.

@MKleusberg How much effort do you reckon this would take? :smile:

**Comment by justinclift** [comment]
Going to close this, because we have another issue open for the same thing at #682.

But yeah... you did suggest it first. :wink:
