### ISSUE TITLE
Windows 64 bit - inflexibilty

### ISSUE THREAD

**Issue by Esenby** [sqlitebrowser/sqlitebrowser#456]
My version of sqlitebrowser (Windows64) seems less flexible than required for a course I am following (Python using databases with Charles Severin).

How does one change the field names ("field1", "field2" entries to ) to, say,  "name", "email" and my options are "text",  not VARCHAR as seen in the course material. 

Thanks for any help.

**Comment by justinclift** [comment]
Hmmm, changing field names should work.  In the dialog for either creating a new table, or modifying an existing one, just double click on the name of the field you want to change.  eg Double click on "Field1".

In theory, that should let you then change it's name to whatever you want.  If that's not working, let us know as something's wrong. :wink:

For the field types, we list SQLite's in built types.

&nbsp; &nbsp; https://www.sqlite.org/datatype3.html

(Please read that page, as it should help a lot :wink:)

The course material you're using might benefit from getting a note added about the various data types available across different databases, depending on which software they expect people to be using.

Is it practical for you to have a chat with your course instructor, or the creator of the course material, or ask about this? :smile:

**Comment by Esenby** [comment]
Thanks! Of course. ;) My "clicks" weren't determined enough.

Best seasons wishes and thanks again,
Sandra Britz

**Comment by justinclift** [comment]
Thanks Sandra.  Are we ok to close this issue now? :smile:

**Comment by Esenby** [comment]
Definetly, thanks to you, Justin.

Again Good Season Wishes and happy SQL-ing in 2016,

Sandra

**Comment by justinclift** [comment]
:smile:
