### ISSUE TITLE
Update to latest sqlite3 / Some "complex" queries do work in latest command line version, but not in the sqlitebrowser

### ISSUE THREAD

**Issue by magicgoose** [sqlitebrowser/sqlitebrowser#457]
[Some "complex" queries do work in latest command line version, but not in the sqlitebrowser](https://stackoverflow.com/questions/34391632/how-can-i-add-row-position-to-a-query-with-a-sum-column-from-subquery?noredirect=1#comment56524568_34391632)

    $ sqlite3 -version
    3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4

**Comment by justinclift** [comment]
Which version of DB4S are you trying with, and which Operating System is it on? :smile:

**Comment by magicgoose** [comment]
```
Version 3.7.0
Qt Version 4.8.7
SQLCipher Version 3.8.6
```
on OS X 10.11.2

![screen shot 2015-12-23 at 5 15 48 pm](https://cloud.githubusercontent.com/assets/1442206/11977996/e85461ce-a998-11e5-8c9e-6796ddadb95f.png)

**Comment by justinclift** [comment]
Ahhhh yeah, that makes sense.

We're looking to complete a new release done tomorrow, which on OSX should include SQLite 3.9.2.  I'm thinking this should fix the problem for you.

In the meantime, if you need things to work right away you can compile DB4S yourself.  On OSX is very, very easy, if you already have Homebrew installed.  You can literally cut-n-paste the commands from the instructions here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

Sound ok to you? :smile:

**Comment by magicgoose** [comment]
Thanks for the information, that's good to know!
> In the meantime, if you need things to work right away

Fortunately, not really (I usually only use DB4S just for quick "prototyping"/testing harder queries), so I'll just wait. :laughing: 

And, by the way, I want to say, DB4S is an awesome thing

**Comment by justinclift** [comment]
Thanks. :grin:

Btw, the new release (3.8.0) has been out for a few days now, so you should be good. :smile:
