### ISSUE TITLE
update to latest SQLite (3.9.x) / Indexes on Expressions use new file format

### ISSUE THREAD

**Issue by springy76** [sqlitebrowser/sqlitebrowser#458]
When you try to open a Sqlite database which uses indexes on expressions then DB4S only shows a message box "invalid file format".

Quote from [https://www.sqlite.org/expridx.html]

> The ability to index expressions was added to SQLite with version 3.9.0 in October of 2015. A database that uses an index on expressions will not be usable by earlier versions of SQLite.

**Comment by justinclift** [comment]
Oh, that's interesting.  Which version of DB4S is this happening on, and which OS are you using? :smile:

**Comment by springy76** [comment]
I don't think it's a bug since the SQLite team clearly states that using that new 3.9.x feature makes the database incompatible with previous versions. That's why I'm asking for an updated version.

I'm using the newest available setup for Windows (8.1), 3.7.0 which includes SQLite 3.8.10.2.

The "problem" (=incompatibility) starts after creating an index (by using another tool) which includes an expression: `create index PixelCount on Images (Width * Height)` and the database again becomes compatible after dropping such index.

**Comment by justinclift** [comment]
Ahhh, makes sense.  It's more of a packaging issue on our end, needing a new release with the newer SQLite.

We're intending on getting a new release out reasonable shortly (likely days, not months).  Hopefully that's not too long a delay for you. :smile:

**Comment by justinclift** [comment]
@springy76 The new release uses SQLite 3.9.2 for the Windows packages.  Have you had a chance to try it out yet and confirm it's now working? :smile:

**Comment by justinclift** [comment]
Closing this now, as the new release bundles SQLite 3.9.2.  If it doesn't turn out to work for you after all, please feel welcome to reopen this issue and we'll investigate further. :smile:
