### ISSUE TITLE
Suggestion: Browse Data tab order

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#459]
May I suggest (hopefully for the upcoming release, as it is a tiny change) the 'Browse Data' tab moves first in the order of tabs so it is immediately available when opening the app.

I'm quite confident the majority of users, most of the time they enter the app, they want to go straight to viewing/editing data, instead of the database structure.

Hopefully you agree, and Merry Christmas to all.

**Comment by justinclift** [comment]
Makes sense to me. :smile:

 Unsure if it'll get done for this release (likely tomorrow) though. :frowning:

**Comment by mgrojo** [comment]
@tonypdmtr The Save Project functionality allows you to save the initial tab.

It would make sense to make this configurable in the settings or even change our default when opening a database.

**Comment by justinclift** [comment]
Yeah, we can probably have it configurable from Preferences. :smile:

**Comment by mgrojo** [comment]
@tonypdmtr Merry Christmas three years and two days later! If you're still around, you can check tomorrow [under the christmas tree](https://nightlies.sqlitebrowser.org/latest/), because you could have this enhancement as present :smile: Now you can reorder and close the main tabs and the state is automatically saved for the next session. Hope you like it! :gift:

**Comment by tonypdmtr** [comment]
Thanks for the update.  However, there seems to be some glitch.

Upon opening a database I end up in the browser view with a given table (I assume the first one alphabetically) but there is no data displayed.  If I select the (same) table from the drop-down list, then the data is displayed.

(Irrelevant but, apparently, CTRL-O stopped working at some point.)

Thanks and late Merry Christmas.

**Comment by sky5walk** [comment]
Nice! 
Will the 181227 nightly have the correct linewrap Qt lib?
Lost track of that experiment. 😕

**Comment by mgrojo** [comment]
> Will the 181227 nightly have the correct linewrap Qt lib?
Lost track of that experiment. :confused:

Yes, it's using Qt 5.11.3 now, which doesn't have that problem. See #1658.

**Comment by justinclift** [comment]
> Will the 181227 nightly have the correct linewrap Qt lib?

Yeah, all of our Win and OSX nightlies have dropped back to Qt 5.11.3. :smile:
