### ISSUE TITLE
repetition of the name of the column

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#460]
When editing the table, and adding any column does not check that the name is already in use, resulting in the loss column added when saving table and fall program attempting to move a column with duplicate names

to repeat
1. Create a table with columns (Field2, Field3, Field4)
2. open it for editing
3. add a new column, it name will duplicate (Field4)
4.1 when saving last column will be lost without warning
4.2 when trying to move the last column will happen fall program

add:
if you use non-standard column names, the name of the column will be repeating the standard

**Comment by justinclift** [comment]
Thanks @PKEv. :smile:

**Comment by MKleusberg** [comment]
Fixed it :smile:

**Comment by PKEv** [comment]
That will not be enough
you need to add a check of repeatability column names in edit mode when you change the order of columns and save.
Not only standard column  names

**Comment by MKleusberg** [comment]
Not sure if I understand what you mean :frowning: Can you give me an example maybe on how to reproduce this?

**Comment by PKEv** [comment]
to repeat
1. Create a table with columns (a1, a2, a3)
2. open it for editing
3. add a new column, it name will duplicate (a3)
4.1 when saving last collum will be saved as 'Field4'

**Comment by PKEv** [comment]
to repeat
1. Create a table with columns (Field1, Field2, Field3)
2. open it for editing
3. add a new column, it name will duplicate (Field3)
4 when saving last collum will be lost (second 'Field3')

**Comment by MKleusberg** [comment]
Ah, that's fixed too, I think. Step 3 is made impossible by this commit: b04d52b99c6ed9a93e5a0be250f00fb1b117dc14

**Comment by PKEv** [comment]
to repeat
1. Create a table with columns (Field1, Field2, Field3)
2. open it for editing
3. add a new column, it name will duplicate (Field3)
4 trying to move last collum (second Field3) upper  -> program will crash

**Comment by PKEv** [comment]
These examples are not just for the standard column names.
No checks the correctness of the table in the editing mode structure

**Comment by MKleusberg** [comment]
But there won't be a duplicate Field3 :confused: I understand that it *would* crash if there were two fields with the same name. But I don't see how you can make two fields with the same name after the latest commits?

**Comment by PKEv** [comment]
as I understand:
commit only affects moment to add a new column but there is no verification of column names before executing a user-entered changes

**Comment by MKleusberg** [comment]
Ok, I think I understand you :smile: 
I've made two different commits. One (5af384f0a21c5dd2882ef51dcce5884b916225c7) is for the case when a new field is added. This is the one you mean. But there is a second commit (b04d52b99c6ed9a93e5a0be250f00fb1b117dc14) which verifies the field names after the user has changed them. This second commit should solve the bug you've mentioned. Correct?

**Comment by PKEv** [comment]
look good, ok!
i close issues after test

**Comment by justinclift** [comment]
@PKEv Ping? :smile:

**Comment by PKEv** [comment]
all right

**Comment by justinclift** [comment]
Thanks @PKEv. :smile:
