### ISSUE TITLE
Updated to v3.8.0 - Clicking "Browse Data" tab crashes every time.

### ISSUE THREAD

**Issue by eikcam** [sqlitebrowser/sqlitebrowser#462]
I updated from v3.7.0 to v3.8.0 (Windows) this morning and now whenever I click the "Browse Data" tab the application crashes.

I have attached the db that I am trying to view.

[eikcam.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/72295/eikcam.zip)

**Comment by chinhodado** [comment]
Just updated and same problem here. 

    Problem signature:
    Problem Event Name:   APPCRASH
    Application Name: sqlitebrowser.exe
    Application Version:  0.0.0.0
    Application Timestamp:    567da857
    Fault Module Name:    Qt5Core.dll
    Fault Module Version: 5.5.1.0
    Fault Module Timestamp:   561c0647
    Exception Code:   c0000005
    Exception Offset: 0000000000001120
    OS Version:   6.3.9600.2.0.0.256.4
    Locale ID:    1033
    Additional Information 1: 60d6
    Additional Information 2: 60d646ea0e4fa529d5414ce8cb1f4f1c
    Additional Information 3: 2dd1
    Additional Information 4: 2dd15331c975a3699413280dec2a3d42

**Comment by justinclift** [comment]
Ouch, that's not good.  Guess we might be making a 3.8.1 release in the very near future. :wink:

**Comment by javamap** [comment]
Hey guys. I just wanted to confirm I'm having the same problem with the latest version on my Windows 64 Bit Desktop computer.

Landon

**Comment by justinclift** [comment]
Sorry for this hiccup.  Use the 3.7.0 release instead for now, and we'll try to figure out what's going wrong. :frowning:

**Comment by justinclift** [comment]
@eikcam @chinhodado @javamap As a thought, it would be interesting to know if the nightly build has the same problem.  Anyone have time/interest to check? :smile:

If so, it's here for Windows (uncompress it with [7-Zip](http://www.7-zip.org)):

  &nbsp; &nbsp; http://rp.oldsch00l.com/sqlitebrowser/sqlitebrowser.exe.xz

**Comment by chinhodado** [comment]
That version works fine.

**Comment by chinhodado** [comment]
Also, I noticed that the Qt version in the above build is 4.8.5, while the version when it crashed before is 5.5.1.0 in the windows error detail.

**Comment by eikcam** [comment]
That nightly appears to be working fine. Adding to what @chinhodado reported regarding versions;

3.8.0 - Qt version 4.8.5, SQLite Version 3.8.4.3
3.8.99 - Qt version 5.5.1, SQLite Version 3.9.2

**Comment by chinhodado** [comment]
@eikcam Shouldn't 3.8.99 be Qt version 4.8.5, and 3.8.0 be Qt 5.5.1?

![image](https://cloud.githubusercontent.com/assets/1388219/12004960/332cefee-ab52-11e5-8a42-ea9b1a311993.png)

**Comment by eikcam** [comment]
@chinhodado You are 100% correct. My bad. I have corrected my previous post.

**Comment by justinclift** [comment]
Thanks guys, that's very helpfu! :smile: The automated nightly build system for Windows runs on a different system than the one used to create the Windows release builds.  It sounds like something's not quite right with the packaging/building done for this release on Windows, rather than a problem in the actual code itself.

It'll take some more investigation, but that gives us a bunch to go on.  I've emailed the main dev's to let them know, so hopefully @rp- has time to look into this in the near-ish future and figure out a solution. :smile:

**Comment by eikcam** [comment]
Thanks for the quick action @justinclift. I'll roll with the nightly you provided for now and wait until the experts do their thing.

Cheers.

**Comment by justinclift** [comment]
No worries. :grin:

**Comment by rp-** [comment]
Fixed in 1c233de3b5166ecd9225d52f6985976f29a80729.

Rerelease should be published soon.

**Comment by justinclift** [comment]
Just published the new release: https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.8.0

Binaries on all platforms were rebuilt.  Used Qt5 on OSX this time too, just for the heck of it.  Hopefully that doesn't cause issues... :smiling_imp:

**Comment by justinclift** [comment]
@rp- Would it be possible for you to update the SQLite library being used for the static builds?

**Comment by justinclift** [comment]
Closing this now, as we haven't had any further reports of this bug since releasing the new packages. :smile:
