### ISSUE TITLE
invalid win32 application (3.8.0-win32v2)

### ISSUE THREAD

**Issue by MvGulik** [sqlitebrowser/sqlitebrowser#464]
"sqlitebrowser.exe" from the 3.8.0-win32v2 install is triggering a "invalid win32 app" error message on this side of the curtain.

OS: Win ... XP

**Comment by justinclift** [comment]
Hmmm, that's interesting.  I wonder if the new 3.8.0 package for Win32 was built without XP compatibility?  We'd better ask. :wink:

@rp- ?

**Comment by justinclift** [comment]
As a thought, does the nightly build work for you? (download locations is listed on our front project page)

**Comment by MvGulik** [comment]
Yes, the nightly (28-Dec-2015 02:20) starts up ok on this side. :)

**Comment by justinclift** [comment]
Cool, that fixes the immediate problem.  It'll be useful to figure out the actual cause and get that looked at tool. :wink:

**Comment by rp-** [comment]
I'll have a look as soon as I got some time

**Comment by MKleusberg** [comment]
We might need to explicitly set the v110_xp target when compiling with MSVC?

**Comment by rp-** [comment]
yeah it was that, but I don't know exactly why, because I added an overwrite for that property.

I uploaded a new installer

**Comment by MvGulik** [comment]
Thanks for continued XP support. :smiley:
