### ISSUE TITLE
Crash on El Capitán version 10.11.1

### ISSUE THREAD

**Issue by chrisdziewa** [sqlitebrowser/sqlitebrowser#468]
I'm not sure if you are supporting this version yet, but when I try to import or save a new database, the program crashes immediately.

**Comment by justinclift** [comment]
Interesting, similar reports on OSX 10.10.5 (that specific version) too.  It seems to be a bug in the packaging I did. :frowning:  As a workaround for now, do you have Homebrew installed?

If you do, compiling it DB4S yourself is super easy and the program won't crash.  You can literally cut-n-paste the instructions here, and it takes ~5 minutes in total (including reading the instructions). :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

**Comment by chrisdziewa** [comment]
@justinclift compiling the package manually worked! Thanks!

**Comment by justinclift** [comment]
You're welcome. :smile:
