### ISSUE TITLE
Closing DB does not clear Edit Box - Minor bug

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#469]
If you have the edit boxed docked, and close the DB, whatever was last displayed in the Edit Box remains visible.

**Comment by justinclift** [comment]
Ahhh, good catch.  Should be an easy fix too. :smile:

**Comment by MKleusberg** [comment]
Should be fixed in the next nightly build :smile: The same problem applied for the edit dialog, too, by the way and is fixed there as well.

**Comment by justinclift** [comment]
Excellent stuff Martin. :smile:

**Comment by MKleusberg** [comment]
Ha ha, this was broken again in the meantime ^^ Just pushed a new fix. Can somebody test this and confirm it's working now?

**Comment by MKleusberg** [comment]
Closing this because it's an old issue without many updates and I'm pretty sure it's fixed :smiley: If you feel like I've closed this issue too hastily please reopen it :smiley:

**Comment by justinclift** [comment]
@tonypdmtr If you've the time/energy, would you be ok to check a recent nightly from your point of view? :smile:

**Comment by tonypdmtr** [comment]
Seems OK. Thanks.

**Comment by justinclift** [comment]
Awesome @tonypdmtr, thanks for taking the time. :smile:
