### ISSUE TITLE
InvalidFileFormat

### ISSUE THREAD

**Issue by muhammad-naderi** [sqlitebrowser/sqlitebrowser#476]
Some times, for a db pulled out of an Android app, it shows this error, while the file can be opened using other sqlite editors on the device (eg. SQLite Editor (https://play.google.com/store/apps/details?id=air.SQLEditor&hl=en) ) 

[com.shygunsys.mu.cyberMobile.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/76168/com.shygunsys.mu.cyberMobile.zip)

**Comment by justinclift** [comment]
Oh, that's interesting.  Thanks for the bug report @muhammad-naderi. :smile:

**Comment by MKleusberg** [comment]
I cannot open your database file using the SQLite command line tool either. So I think it's the file which causes the problems, not the SQLite editor.

I've done a bit of searching and it looks like this is a common problem for Android users: copying the database file to your computer may give you an incomplete file which then can't be opened: https://stackoverflow.com/questions/9058169/sqlite-database-disk-image-is-malformed-on-windows-but-fine-on-android
This would explain why the file can be opened with an editor in the device - you don't need to copy it then.

If you want to do some more research, you can try searching for e.g. 'android "Error: database disk image is malformed"'.

**Comment by muhammad-naderi** [comment]
thanks, so it't not this apps bug then 
again thanks for quick response

**Comment by MKleusberg** [comment]
Yes, sorry I can't help you any further. But if you have any other issues or questions later on feel free to open issues for them, too :smile:
