### ISSUE TITLE
Edit database cell window appears when entering data

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#480]
Using 3.8.0, and the nightly build from 6 Jan.
When you add data via the 'browse data' table, when you press Enter to confirm data in a cell (or add new data) the 'edit database cell' window appears.  This didn't occur in 3.7.0.
If you add new data into a cell (eg, 'test') and press Enter to confirm this data, the 'edit database cell' window appears, but it is also blank.  Pressing Cancel closes the window, and the original data entered is correctly stored in the cell.
Additionally, updating the contents of a cell and pressing Enter displays the 'edit database cell' window, but this window has the original data in it.  Clicking OK on this erronous data is actually ignored - the edited data is saved.

**Comment by justinclift** [comment]
Yeah, the new "Edit database cell" window was an addition for 3.8.0.  Does the menu item for turning it off under the View menu do what you want? :smile:

**Comment by justinclift** [comment]
Hmmm, reading that back again, it sounds like there's a bug, in that new entered data (eg 'test') should be displayed in the 'edit database cell', and it's not happening.

Is that correct? :smile:

**Comment by justinclift** [comment]
Just tried this out here on OSX, and you're right.  That looks like a bug in our older "Edit database cell" code.  Seems to only happen (for me), when the new "Edit cell" window is turned off. :frowning:

**Comment by chrisjlocke** [comment]
No, 'View' -> 'Edit Cell' makes matters worse.
Now if a cell contains 'test' and I overwrite it with 'test2', and press Enter, 'test2' is saved to the cell, but 'test' appears in the window underneath.  The dialog doesn't appear though.

**Comment by justinclift** [comment]
Hmmm, yeah there definitely seems to be some interaction between the older "Edit database cell" window, and the new "Edit cell".  @MKleusberg wrote the code for this, so this Issue has been assigned to him. :grin:

No idea how long it will take to get resolved though... we're volunteer based an all.  It might take a few weeks. :angel:

**Comment by justinclift** [comment]
It does sound like it will be an easy fix though. :grin:

**Comment by chrisjlocke** [comment]
Additionally, the 'Edit Cell' pane at the bottom is labelled 'Edit &cell'...
Excellent - thanks for assigning it - much appreciated.

**Comment by MKleusberg** [comment]
Thanks, @chrisjlocke, for reporting this :smile: I've done most of my testing using the pane at the bottom instead of the dialog and didn't notice this annoying behaviour...
This bug should be fixed in the next nightly build (so no need to wait for a few weeks :wink:). Please let me know if the new version works for you.

As for the "Edit &cell" thing: this seems to work correctly on my system (i.e. underlining the 'c' and creating a Alt+C shortcut). Might be a Qt version thing or dependant on the OS. I'll have a closer look at this later.

**Comment by justinclift** [comment]
Excellent stuff @MKleusberg. :smile:

**Comment by justinclift** [comment]
@MKleusberg I've just been using DB4S for manually adding a few hundred fields of data in a database, which I need to do every few months.

Not at all a fan of the new Edit Cell window, as it's breaking my work flow pretty badly.  Previously, I could hit enter on a cell, edit the value in place there, hit tab to progress to the next cell (which would automatically be in editable mode), add the value there, hit tab, etc.

This no longer works, instead bringing up the Edit Cell window, where the TAB key makes a tab character instead.

To get around this I've reverted my version of DB4S back to commit e74645bb1f74395016bfda110dd4d996bb1d5cb1, which is prior to this Edit cell change.  That has let me continue being efficient.

We should probably either make the TAB key in the Edit cell move to the next cell value, or possibly rethink our Edit cell approach.  Thoughts? :wink:

**Comment by FreudGit** [comment]
Hi.  Yes, annoying bug.  Ship please! :)

**Comment by justinclift** [comment]
@FreudGit Which OS are you on?  If it's OSX, I can whip up a one-off build for you which is reverted back to that commit, same as I'm using.

**Comment by FreudGit** [comment]
thanks @justinclift, I prefer to wait for the next official release.  I think it was the only\last open thing for the 3.9 milestone. :)

**Comment by justinclift** [comment]
Sure, no worries at all. :smile:

**Comment by FreudGit** [comment]
@justinclift  Finally, i'll accept your offer to provide the version with this commit. :)

**Comment by chrisjlocke** [comment]
lol... caved in at last.... ;)

**Comment by justinclift** [comment]
Sure, no worries.  Just for OSX, or should I make a Win64 build as well?

Btw - I fully intend to debug this and get it fixed for the next release.  Putting time into other stuff at the moment though, but can't imagine it taking for than a fortnight (roughly).

**Comment by justinclift** [comment]
@FreudGit Just whipped up an OSX build using the commit mentioned above:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-onceoffs/sqlitebrowser-201606081616-commit_e74645b.dmg

Give that a shot for now.

In theory, a proper fix for this should be in the next release too.  \*fingers crossed* :wink:

**Comment by justinclift** [comment]
@chrisjlocke @FreudGit I've been putting some time over the last few days, to understand the code around this part of things.

Just made some changes to the source code, which I **think** will have improved this a lot.

It might not be perfect yet, but I think it's on the way.

Would either of you have time to try out tomorrow's nightly build to see how well that works for you?

**Comment by justinclift** [comment]
In theory, this should now be fully fixed.  Nightly builds (from tomorrow) will include the fix, so if someone can verify things are now good that would be fantastic. :smile:

**Comment by chrisjlocke** [comment]
I'll try it now.  :smile:

**Comment by chrisjlocke** [comment]
The only issue I immediately see is that when updating a cell via the table, the 'edit cell' pane below is not updated.  However, editing the lower pane updates the grid.
I can do a 'movie' if that shows things better.

**Comment by justinclift** [comment]
Ahhh, I think I understand already.

After a new value is put into a cell, the new value doesn't get propagated to the Edit Cell window automatically.  Is that what you're meaning?

**Comment by chrisjlocke** [comment]
Indeed.  Its 'out of sync'.  Flipping cells (left and right) obviously fixes it, so ... well..... so its not as bad as it was! :wink:

**Comment by justinclift** [comment]
Thanks Chris. :smile:

The fix is probably just figuring out the name of the event that fires when data is changed, and connecting that to the Edit Dock.  It'll likely be something straightforward such as... dataChanged().  Will investigate.

**Comment by justinclift** [comment]
@chrisjlocke Fixed the problem with in-place edits not propagating to the Edit Database Cell: https://github.com/sqlitebrowser/sqlitebrowser/commit/9fe42b1399658149cb02943e71b59902de3f8d1f

It'll be in the next nightly build. :smile:

**Comment by chrisjlocke** [comment]
\o/

**Comment by justinclift** [comment]
Closing this now, as it's definitely fixed by the just merged code in #679. :smile:

@FreudGit @chrisjlocke If either of you have time/inclination to test this (eg from the nightly builds after tomorrow), that would be great. :smile:
