### ISSUE TITLE
Autocomplete table name on export

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#484]
This is related and similar to #376.

It would be a great addition if the `filename` field would be auto completed by default with the table's name on export.

**Comment by justinclift** [comment]
This is a good idea, and should be pretty easy to make happen. :smile:

**Comment by revolter** [comment]
If I have time, I'll try [these steps](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle) and see if I can solve it myself :D or at least set it up for possible future PR

**Comment by justinclift** [comment]
If you have Homebrew installed, following those steps should only take about 5 mins (including cut-n-pasting the steps).  It's super easy. :smile:

**Comment by revolter** [comment]
And try to implement this enhancement too :smile:

**Comment by justinclift** [comment]
Yeah, good point. :grin:

**Comment by MKleusberg** [comment]
Just implemented it myself :smile: So it should be in the next nightly build. I've added default filenames in multiple places now, e.g. when saving project files or exporting as SQL, too.
If you're still interested in helping us out just let me know. I'm kind of busy atm but will try my best to introduce you into the codebase :smile:

**Comment by revolter** [comment]
I am, but can't find time for it. But, to start, what IDE should I use on a mac?

**Comment by MKleusberg** [comment]
I'd use Qt Creator for all platforms. It's probably the easiest for C++/Qt development even on Mac OS X :smile:

**Comment by revolter** [comment]
Awesome, thanks!

**Comment by revolter** [comment]
@MKleusberg, could you provide some steps to create a Qt project and run this project? I can't figure it out. I get errors like `qt creator has no cmake tools`, `Selected kit has no valid CMake executable specified.` and `No targets specified and no makefile found.`.

**Comment by justinclift** [comment]
Sounds like something's not right with your Qt Creator setup itself.  Are you able to generate and compile other Cmake programs?

Just thinking that if you can get that sorted, it might take care of the problem. :smile:

**Comment by revolter** [comment]
Well, I don't know what Cmake is. I didn't ever used Qt (though I know a little bit of C#), that's why I'd want some help to get started. I just want to know how to build and run the project, in order to contribute and test.

**Comment by justinclift** [comment]
Heh Heh Heh, I'm the wrong guy to ask.  Not a C++ coder myself. :grin:

Looking around online for info about using CMake (a compilation system) with Qt Creator, does turn up some useful looking info:

* http://doc.qt.io/qtcreator/creator-project-cmake.html
* http://stackoverflow.com/questions/9415761/using-cmake-with-qt-creator

Sounds like you'll just need to download CMake and put it somewhere, then update the paths mentioned above so Qt Creator can find it automatically.  It's worth giving a shot. :smile:

**Comment by MKleusberg** [comment]
Yes, we use cmake as a build system. But you can just use qmake instead (like I do most of the time). This way you shouldn't need to care about cmake at all. Your setup looks fine, too. So you probably have qmake installed :smile: 
So let's have a look what we can do... What's happening when you delete the sqlitebrowser.pro.user file (if there is one) and you open the sqlitebrowser.pro file afterwards? In theory, it should work to just keep all the settings as they are and just use qmake there...

**Comment by MKleusberg** [comment]
Also, if you have any other updates, just let me know :smile: I hope I'll be able to help you!
