### ISSUE TITLE
Crashes on edit display format

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#485]
In the `Browse Data` tab, if you right click next to the last column (in the empty space on the bar), and choose `Edit display format`, it crashes.

I think that that menu item shouldn't even appear when not right clicking a column.

**Comment by justinclift** [comment]
Thanks @revolter, that's a good catch. :smile:

**Comment by revolter** [comment]
I was lucky that I miss clicked the column :laughing: and that I'm curious.

**Comment by justinclift** [comment]
:wink:

**Comment by MKleusberg** [comment]
Nice catch :wink: Should be fixed in the next nightly build. Let us know if it works for you :smile:

**Comment by justinclift** [comment]
Thanks for verifying this @revolter. :smile:

**Comment by revolter** [comment]
My pleasure! :smile:
