### ISSUE TITLE
Automatically enter crypted database's password

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#486]
I work with an SQLite database encrypted with a password with different versions of it in different locations.
It gets annoying having to enter the same password over and over again (even with `ClipMenu`).

Is there any possibility to set a password, maybe in `Preferences > Database > Advanced` next to the new `SQL to execute after opening database`, and first try to use that password, and if it doesn't work (trying to open another database), show the enter password alert?

**Comment by justinclift** [comment]
Hmmm, I can see arguments both for and against doing that.  However, PostgreSQL (another database product) has the ability to set default passwords, and the arguments for it doing so are valid here too.

So... without thinking about it too deeply, this sounds like a decent idea. :smile:

**Comment by revolter** [comment]
Though, it may feel odd to try the same password for lets say 10 different databases, but only one  being the correct one.
Maybe specify a regex format for the databases with that password? Something along the lines of:

    Apply this password: <password>
    for files with this format: <format>

**Comment by justinclift** [comment]
There's no lockout of a database from failed attempts, so that kind of feels (to me) like overcomplicating things.

That being said, whoever end up implementing this... if they choose to do so, then great. :wink:

**Comment by revolter** [comment]
@justinclift It looks like I ended up implementing this 😄 Could you take a look at it? I was so hard for me to implement this fairly simple feature. But I'm understanding Qt and the project structure more and more ❤️.

**Comment by MKleusberg** [comment]
I guess we can close this issue now that #1404 is merged? What do you think, @revolter? :smile:

**Comment by revolter** [comment]
Wooow, I completely forgot about this issue 😮
