### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by fajprieto** [sqlitebrowser/sqlitebrowser#491]
I'm use version 3.8.0 and if I want put a filter (for example C) it doesnt work.
I read https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters but not work.

**Comment by justinclift** [comment]
Interesting.   Would you be ok to add a screenshot showing the filter, and it not working? :smile:

**Comment by fajprieto** [comment]
Yes
![filterz](https://cloud.githubusercontent.com/assets/5431180/12264103/1b1067dc-b913-11e5-9b56-9891bf44d742.png)

**Comment by justinclift** [comment]
Thanks.  Yeah, that doesn't seem to be working like it should. :frowning: 

If you press the refresh button (just above the "Apellido" heading in your screenshot), does it apply then?

**Comment by fajprieto** [comment]
I exit and then I enter to the application and now work.
I remember that I create the table, insert some records, write changes an then test filter and its not work. Maybe this was the problem.

**Comment by justinclift** [comment]
Hmmm yeah.  It sounds like there is a trigger for the filter which wasn't created. :frowning:

Thanks for taking the time to get in touch with us. :smile:
