### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by a1exus** [sqlitebrowser/sqlitebrowser#493]
I'm following [sqlitebrowser/BUILDING.md at master · sqlitebrowser/sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md) and getting following:

```
[root@wcmisdlin02 sqlitebrowser]# cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Antlr2: /usr/lib64/libantlr.a  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /bin/qmake-qt4 (found version "4.8.5") 
-- Found Qt4: /bin/qmake-qt4 (found version "4.8.5") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSQLITE
    linked by target "sqlitebrowser" in directory /usr/local/src/sqlitebrowser

-- Configuring incomplete, errors occurred!
[root@wcmisdlin02 sqlitebrowser]#
```

please advise.

**Comment by justinclift** [comment]
Hmmm, it looks like it hasn't found the SQLite development pieces.  Which platform are you compiling on? :smile:

**Comment by a1exus** [comment]
... after I installed `sqlite-devel`, `cmake` was able to complete without any errors.

thank you!

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by cappetta** [comment]
thanks for the sqlite-devel tip -- @justinclift would it be possible to add this to the building.md for centos?

**Comment by justinclift** [comment]
Heh Heh Heh

Just went to add it... and er... it's already there.  3rd package on the "yum install" line.

Oops? :wink:

**Comment by cappetta** [comment]
Ah your right it is.  My apologies -- I was looking at the building.md from tar.gz that I grabbed from the main site: https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.8.0.tar.gz

**Comment by justinclift** [comment]
Ahhh yeah, that makes sense.  We added the missing dependency a few days ago from memory. :smile:
