### ISSUE TITLE
"DB Sche&ma" window

### ISSUE THREAD

**Issue by wolfgang42** [sqlitebrowser/sqlitebrowser#494]
!["DB Sche&ma" pane](https://cloud.githubusercontent.com/assets/2261204/12335520/9c8602e8-bacd-11e5-9035-4267ea4477a6.png)

Presumably this is supposed to be "DB Sche<ins>m</ins>a" to indicate that <kbd>Alt</kbd>+<kbd>m</kbd> will focus the pane. This works fine in the tabs, but the title of the pane picks up on the `&` instead of ignoring it.

* Version 3.8.0
* Qt Version 5.5.1
* SQLite Version 3.9.2
* Windows 10

**Comment by justinclift** [comment]
Interesting, thanks for letting us know.  Someone mentioned something similar for one of the other windows too.  Looks like it wasn't a one off. :wink:

**Comment by glawrence** [comment]
@justinclift I am seeing the same on Windows 7, it looks to me like the text in the first 4 menu items of the "View" menu is used for the menu item entry and the corresponding "dockable window title", however the latter does not handle & like a menu does, hence the problem.

**Comment by justinclift** [comment]
k.  Hopefully Martin has time to look into it.

Good follow up Geoff. :)

**Comment by wolfgang42** [comment]
Interestingly this doesn't seem to be a problem on Linux (Qt 5.2.1, Kubuntu Trusty):

![image](https://cloud.githubusercontent.com/assets/2261204/12379170/a7dcee2a-bd22-11e5-8f57-4e8c913e633c.png)

**Comment by justinclift** [comment]
Interesting.  Maybe it's a bug in the Qt 5.5.1 released that was used on Windows then. :wink:

**Comment by MKleusberg** [comment]
I'm using Qt 5.5.1 on Linux and don't experience this problem. So it's not just the Qt version but either Qt on Windows or Windows in general. I've tried fixing the problem in the latest commit but don't have a Windows system to test my (somewhat naive) approach. So let me know if it works for you, ideally by first checking today's nightly build, then checking tomorrow's nightly build.

**Comment by MKleusberg** [comment]
As today's nightly build will be gone soon I've made a backup, just let me know if you need it.

**Comment by justinclift** [comment]
@wolfgang42 Do you have time to test the nightly build, and let us know if it's working better for you now? :smile:

**Comment by wolfgang42** [comment]
@justinclift Github [had an outage last night](https://status.github.com/messages/2016-01-28) and the nightly build seems to have failed:

    error: The requested URL returned error: 403 while accessing https://github.com/sqlitebrowser/sqlitebrowser.git/info/refs

**Comment by justinclift** [comment]
Aargh.  Ok, new plan.  Would you be ok to try the nightly build tomorrow then? :grinning:

**Comment by wolfgang42** [comment]
@justinclift The nightly build seems to have fixed the problem. :tada: 

![db-schema](https://cloud.githubusercontent.com/assets/2261204/12683075/1635b3a0-c685-11e5-984e-930ae4073b68.png)

**Comment by justinclift** [comment]
Awesome, thanks for letting us know. :smile:

I'll close this for now.  Our next release will have this in it. :grin:
