### ISSUE TITLE
Crash when opening database

### ISSUE THREAD

**Issue by skifans** [sqlitebrowser/sqlitebrowser#495]
Upon selecting the open database button the program crashes after 3-4 seconds. It dosn't seem to matter weather or not I select a file/folder or not. The same thing happens when using file -> open or control + o. Im using windows 10 for home (64 bit). I have tried using the portable and 64 bit version but both experience this crash.

**Comment by justinclift** [comment]
Interesting, thanks for reporting it.

Would you be ok to try our nightly build (download location is listed on our front page), and yet us know if that works for you?  It used a different (static) build process, and seems to work in many crash situations like this. :smile:

**Comment by skifans** [comment]
Thank you, that has fixed it.

**Comment by glawrence** [comment]
I am running Windows 7 with the standard 64-bit build from the installer and cannot reproduce this. I need to clear some space to test this on Windows 10 as I need to spin up a VM.

**Comment by justinclift** [comment]
@skifans No worries. :smile:

@glawrence That would be useful.  It kind of sounds like there's an issue with the dynamic linking part of things, as the static build version worked.  Not sure if that's pointing to a problem with some dll's on just @skifans' system, or if it's something more widespread, or something else... :anguished: If it happens for you too on a <strike>MS spyware</strike>Win10 system, that would help figure out if it's a once off vs possibly something just on Alex's computer.

**Comment by skifans** [comment]
Ok, if you need me to send any logs or anything then please let me know.

**Comment by justinclift** [comment]
Nah, should be ok for now.  Neither @glawrence nor I are C++ developers for this project, we just help out with other bits.  We're volunteer based, and the main developers are taking a bit of time off it seems after the holidays... so there's no debugging to be done urgently right now. :angel:

**Comment by glawrence** [comment]
I have created a vanilla Win 10 Pro (x64) Virtual Machine, downloaded sqlitebrowser-3.8.0-win64v2.exe from http://sqlitebrowser.org and installed SQLitebrowser, with no issues. I created a new database, added a table with some fields, a couple of rows of data and all was well. No matter what I did I cannot make it just crash after 3-4 seconds. All is well.

@skifans did you have a previous version installed?

**Comment by MKleusberg** [comment]
@skifans You mean it crashed while the open file dialog is opened? Might be difficult to debug then. Do you get any other information in an error message?

**Comment by skifans** [comment]
Yes that is what I mean - no other information appears. Only the standard sqlitebrowser.exe has stopped working.

**Comment by justinclift** [comment]
@skifans If you have a few minutes, would you be ok to try the "3.9.0 beta1" release we did last weekend?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1

We've fixed a weird crash bug a few weeks ago which kept showing up in strange places.  There's a decent chance that's the one which was affecting you. :smile:

**Comment by skifans** [comment]
Thanks, I'm afraid I'm currently away but will definitely try asap when I get back on the 26th August. Nice work guys!

**Comment by justinclift** [comment]
Thanks @skifans. :smile:

**Comment by justinclift** [comment]
@skifans Just an update, we released version 3.9.0 yesterday.  When you're back, please test with that one instead. :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0

**Comment by skifans** [comment]
One above has fixed the issue for me and works perfectly - nice one :smile:

**Comment by justinclift** [comment]
Thanks for checking and letting us know @skifans. :smile:
