### ISSUE TITLE
Columns their self not updating on refresh

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#496]
If I have a database with a table with columns `a` and `b`, and, programatically from an external script I alter the table and add a `c` column between the previous columns for example, and I hit refresh on the `Browse Data` tab, without changing it, there will still be showing columns `a` and `b`, but on the `b` column there will be the `c`'s values, so the data itself refreshed correctly, but the columns header not. When changing tabs, it correctly refreshes both sections.

**Comment by justinclift** [comment]
Interesting.  Good catch. :smile:

**Comment by MKleusberg** [comment]
Good catch indeed :smile: It was an easy fix, though. Should work as expected in the next nightly build :smile:

**Comment by justinclift** [comment]
@revolter Do you have time to test the next nightly build (tomorrow), and let us know if this is fixed for you now? :smile:

**Comment by revolter** [comment]
Sure :smile:

**Comment by revolter** [comment]
Can I test it along with the production release? Or should I replace it with the nightly version?

**Comment by justinclift** [comment]
Hmm, I think they use the same directory paths, so you'd need to uninstall/remove the production release first.  You can put the production release back afterwards if you want, or just keep using the nightly one (if it's better). :grinning:

**Comment by revolter** [comment]
Ok, thanks! :smile:

**Comment by MKleusberg** [comment]
Well, as far as I remember the nightly build is a static build, i.e. it's a single EXE which doesn't depend on any other files. So you can just put it anywhere, double click, and it should run. Using both version should be no problem. They do share their preferences, however. So if you change any settings in the nightly build, the new settings will apply for the release version, too. Hope this helps :smile:

**Comment by revolter** [comment]
Does this apply for Mac too?

**Comment by justinclift** [comment]
Hmmm, on OSX, all of the dependent libraries should be self contained inside the .app directory structure.  So if you rename it to something different (eg "sqlitebrowser-nightly.app") then I think you'll be fine.

Err... In theory. :wink:

**Comment by revolter** [comment]
Is there a nightly build with SQLCipher?

**Comment by justinclift** [comment]
On OSX, yep.  They're all here:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx/

You might need to scroll down a bit to get the latest one. :grinning:

**Comment by revolter** [comment]
Oh, the SQLCipher ones were in the top part actually, and I was looking at the bottom part of the list. I'll try to test this and #485 today, and close them it they're solved :smile:

**Comment by justinclift** [comment]
Awesome, thanks for testing. :smile:
