### ISSUE TITLE
Plot misses columns with NULL as first value

### ISSUE THREAD

**Issue by zwrmueller** [sqlitebrowser/sqlitebrowser#499]
Hi,

if the very first entry/value in a data column is NULL --> this column is no presented as a choice in the plot register.

I.e.: I got a table with 3 columns as
## A   B   C

1   10  NULL
2   12  21
3    8   123

then in the plot register frame only column A and B could be choosen for graphic representation - but not column C, column C is totally omitted and not listed for choosing it.

Could this be fixed please?!?

Small other issue with plotting:
in the graph section only data lines up to the SQL line limit are drawn. Took me a while to understand that. First I ever thought this behaviour would be a limit within the plot engine itself, but now I understood that it is correlated to the data lines shown within the data browser - and the data browser limits the data to 50000 at first view.

Suggestion: maybe a button "Show all data" right hand at the status line of the plot area would prevent others to stumble over that glitch.

Regards
 Ralf

**Comment by zwrmueller** [comment]
just learn a bit of Markdown formatting, so here again is my example table:

 A | B | C 
---|---|---
1|10|NULL
2|12|21
3|8|123

how does it look :-)

**Comment by MKleusberg** [comment]
Hi Ralf, I've just fixed the second issue you've mentioned. The next nightly build should load all data automatically. As for the first and main issue I'm not really sure how to address this yet. Our plot code can't seem to omit those rows which are set to NULL, so they would always be treated as 0. But that's just wrong in my opinion because NULL means no data whereas 0 is an actual data value. But we'll see as soon as I have a chance for a closer look on the code.

**Comment by justinclift** [comment]
Would having all of the data loaded automatically be a problem for people using very large (GB+) data sets?

**Comment by zwrmueller** [comment]
me too I would prefer the suggested button to quickly get a grip on the actually loaded data - and visibly offer an option (button) to load them all for viewing the whole thing if desired

Regards
Ralf

Von: Justin Clift [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. Januar 2016 12:35
An: sqlitebrowser/sqlitebrowser
Cc: Müller, Ralf
Betreff: Re: [sqlitebrowser] Plot misses columns with NULL as first value (#499)


Would having all of the data loaded automatically be a problem for people using very large (GB+) data sets?

—
Reply to this email directly or view it on GitHub<https://github.com/sqlitebrowser/sqlitebrowser/issues/499#issuecomment-176136051>.

Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by zwrmueller** [comment]
me too I would prefer the suggested button to quickly get a grip on the actually loaded data - and visibly offer an option (button) to load them all for viewing the whole thing if desired

Regards
Ralf

Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by zwrmueller** [comment]
me too I would prefer the suggested button to quickly get a grip on the actually loaded data - and visibly offer an option (button) to load them all for viewing the whole thing if desired

Regards
Ralf

**Comment by MKleusberg** [comment]
Sorry for keeping you waiting so long! But if you're still interested in this: could you try the next nightly build? I've added a small button for fetching all the data instead of doing it automatically. It's the small button with the cog icon in the plot panel :smiley:

**Comment by zwrmueller** [comment]
Hi no Problem, I feel happy that finally there is progress. Well the fetch all button seems to work. 2 Points here: 1) maybe the fetch all button could be "highlighted" - or make visible - only in case, that it is of use, as to say, when the actually plotted data are actually limited? 2) when the fetch all data button is activated surely it tooks a while til all data are loaded and plotted - but I miss the "hour glass" here, to get informed that something really miraculouse is happening under the hood.

Ah, and unfortunately the original issue "Plot misses columns with NULL as first value" is still not affected by this patch.

But thanx for this first step
 Ralf

**Comment by MKleusberg** [comment]
Hi Ralf,
sorry again for the late response!
Today I haved pushed two commits which address this issue. One adds a progress dialog to fetch all data process. This way you can tell how long it's going to take and you can cancel it anytime.
The other commit actually addresses the NULL value issue and fixes that. For NULL data there will be a gap in the graph now. If it's just your first row that has a NULL value, the graph will simply start a little later.
If you're still interested, can you test tomorrow's nightly builds and report back if it's working for you? :smiley:

**Comment by MKleusberg** [comment]
@zwrmueller Did you have any time to test this yet? :smiley:

**Comment by MKleusberg** [comment]
Closing this because it's an old issue without any updates recently. If this isn't working for you as expected, please reopen this issue. :smiley:
