### ISSUE TITLE
Is it possible to install the Windows binary in an unattended/silent fashion?

### ISSUE THREAD

**Issue by swinster** [sqlitebrowser/sqlitebrowser#500]
Hi Guys,

Tried a basic "sqlitebrowser-3.8.0-win64v2.exe /S", and "sqlitebrowser-3.8.0-win64v2.exe /?" to see if there where any options, but the installer just launched.

Cheers

**Comment by justinclift** [comment]
That's not a bad idea.  The installer is created using NSIS.  So, if NSIS adds a built in switch for silent install, that would likely work. :smile:

**Comment by rp-** [comment]
should work, see:
http://nsis.sourceforge.net/Docs/Chapter4.html#silent

**Comment by justinclift** [comment]
@rp- Excellent, that's good info.  @swinster Would you be ok to read that info, then try the /S, /D, options (etc) as appropriate?

**Comment by swinster** [comment]
Hey @justinclift . I meant to post back before @rp did with the same info, and indeed I though I had tried this very option (see first post), as when I first check I though I still saw all the dialog relating to folder etc. However, running this again worked slightly differently second time round. 

Because I already had sqlitebrowser installed, I still saw prompts, firstly to ask if I want to uninstall the "old" (but same) version, then the uninstall wizard. However, the actual install did progress fine.

Not sure if it is possible to override the uninstall/upgrade dialogues as well?

**Comment by justinclift** [comment]
It sounds like it should be, but it might take some digging to figure out what the correct command line switches should be.  Might need to locate the NSIS source code (should be online), and take a look at the file in there which does the command line option parsing.  That would be pretty definitive. :smile:

**Comment by justinclift** [comment]
As a very overdue follow up data point, we're moving to MSI based installers for Windows (#1400).

They have a bunch of available options, including `--quiet` and `--passive` for unattended use.

Running `/?` on one of them now gives this:

```
Install Options
	</package | /i> <Product.msi>
		Installs or configures a product
	/a <Product.msi>
		Administrative install - Installs a product on the network
	/j<u|m> <Product.msi> [/t <Transform List>] [/g <Language ID>]
		Advertises a product - m to all users, u to current user
	</uninstall | /x> <Product.msi | ProductCode>
		Uninstalls the product
Display Options
	/quiet
		Quiet mode, no user interaction
	/passive
		Unattended mode - progress bar only
	/q[n|b|r|f]
		Sets user interface level
		n - No UI
		b - Basic UI
		r - Reduced UI
		f - Full UI (default)
	/help
		Help information
Restart Options
	/norestart
		Do not restart after the installation is complete
	/promptrestart
		Prompts the user for restart if necessary
	/forcerestart
		Always restart the computer after installation
Logging Options
	/l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
		i - Status messages
		w - Nonfatal warnings
		e - All error messages
		a - Start up of actions
		r - Action-specific records
		u - User requests
		c - Initial UI parameters
		m - Out-of-memory or fatal exit information
		o - Out-of-disk-space messages
		p - Terminal properties
		v - Verbose output
		x - Extra debugging information
		+ - Append to existing log file
		! - Flush each line to the log
		* - Log all information, except for v and x options
	/log <LogFile>
		Equivalent of /l* <LogFile>
Update Options
	/update <Update1.msp>[;Update2.msp]
		Applies update(s)
	/uninstall <PatchCodeGuid>[;Update2.msp] /package <Product.msi | ProductCode>
		Remove update(s) for a product
Repair Options
	/f[p|e|c|m|s|o|d|a|u|v] <Product.msi | ProductCode>
		Repairs a product
		p - only if file is missing
		o - if file is missing or an older version is installed (default)
		e - if file is missing or an equal or older version is installed
		d - if file is missing or a different version is installed
		c - if file is missing or checksum does not match the calculated value
		a - forces all files to be reinstalled
		u - all required user-specific registry entries (default)
		m - all required computer-specific registry entries (default)
		s - all existing shortcuts (default)
		v - runs from source and recaches local package
Setting Public Properties
	[PROPERTY=PropertyValue]
```

Looks like pretty comprehensive coverage. :smile:
