### ISSUE TITLE
Selections in SQL Output Window Not Working

### ISSUE THREAD

**Issue by chipbeaulieu** [sqlitebrowser/sqlitebrowser#502]
Mac version 3.8.0. If I have a SQL Output with say 1,000 rows, clicking the top left corner of the window should select all records in the output window. In reality, it only selects the visible records (10 or so). 

A related bug is the scroll bar in the output window. I can't grab it and scroll to the bottom and thus shift-click the last row to easily work around this bug. I have to resort to shift + page down. This used to work in previous versions though.

Thanks for a great tool though.

**Comment by justinclift** [comment]
Thanks for the bug report.  Do you happen to remember which version the shift-click approach used to work?  That might help nail down the code which introduced the change. :smile:

**Comment by chipbeaulieu** [comment]
I would usually do one of two things which both worked. 

I would click the top left hand corner to select everything then command c to copy. 

If I didn't need everything I would click whichever columns I needed to select everything in that column(s). Then again command c to copy. Both approaches worked prior to the current version. 

All the best,
Chip.

**Comment by MKleusberg** [comment]
Just tested this on my Linux machine and I don't experience this issue here at all. I can't remember any code changes related to this view either, so I assume it might be a Qt version thing maybe? I'm building againg Qt 5.5.1 but I'm not sure which version we're using for the Mac OS X bundle.

**Comment by chipbeaulieu** [comment]
Hmmm….

I thought I would try the ole quit and restart. That fixed the issue. I usually keep sqlitebrowser open for a long time, sometimes even for days. But I checked and after a restart of the app, it’s fixed. Sorry for all the trouble.

Regards,

Chip.

**Comment by MKleusberg** [comment]
Ok, no worries :smile: That's a fine solution, too :wink: In case the issue happes again for you, feel free to reopen this bug any time.
