### ISSUE TITLE
Open selected table on enter key press

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#507]
On the `Browse Data` tab, if I click on the `Table:`'s dropdown list and type on the keyboard the desired table's name, that table gets selected, but if I press <kbd>enter</kbd>, the table doesn't open (on OS X 10.10.5). So I still have to use my mouse to select it.

**Comment by justinclift** [comment]
Makes sense. :smile:

**Comment by revolter** [comment]
@justinclift I just noticed that it works. Does the nighlty build updates itself automatically? But I culd bet that it didn't work before. I don't understand.

**Comment by justinclift** [comment]
Nope, the nightly builds only check for the latest version at start up (unless disabled in preferences).  We've not added code for automatic updating yet.  In some ways it would be nice to have... but we're not there yet. :smile:

**Comment by revolter** [comment]
Start up of the application? Because if that's the case, it means I do have the lastest nightly build version, because I often restart the app. And in that case, did this got solved after I opened this issue or it was implemented but not working because of a bug?

**Comment by justinclift** [comment]
Hmmm, I'm confused now.  I'll try explaining that in a bit more details, in case it helps:

When DB4S starts up, it does a HTTP request to the GitHub repo, reading the version in this file:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/currentrelease

If the version number in that file is newer than the running application version, we pop up a dialog letting the user know about the new release, so they can download and install it. (manually, themselves)

We don't (yet) do any kind of automatic downloading updates.  Hopefully at some point we do (and it would have to work well).

**Comment by revolter** [comment]
Oh, I understand now, sorry for my confusion. Selecting a table by pressing the <kbd>enter</kbd> works, so I'll close this.
