### ISSUE TITLE
Edit box stopped working

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#508]
In latest (last night's) build, whatever changes I make in the edit box are not accepted, either by CTRL-ENTER or pressing the OK button.  (The problem could have been introduced earlier because I haven't been updating on a daily basis for some time now.)

**Comment by MKleusberg** [comment]
It seems like this was introduced by #286. That PR changed the code for the edit dialog but not for the edit dock. I've just pushed a quick fix for that but haven't had a closer look at the changes made by that PR yet (not much time atm) but it seems to work now. Maybe if you have the time, you can help me out here testing the inline editing, the editing in dock mode and in window mode in the next nightly build? :smile:

**Comment by tonypdmtr** [comment]
The fix worked but it still has one minor issue.
When typing directly on the cell and pressing ENTER, the edit box does not update with the new value.

**Comment by justinclift** [comment]
Ahhh, forgot about this issue.

@tonypdmtr Going to close this, as it's fixed in the 3.9.0 release which came out yesterday. :smile:
