### ISSUE TITLE
Add full support for tables without rowid

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#51]
Commit 3761acfd024d4126ac67d55ce877d493986f4aa5 has added support for 'without rowid' tables to our Table class and commit a002e6768f65fc68a228abe7bd356acd730b641a improved the SqliteTableModel class to allow browsing these tables.

However, a lot of UI features still don't work when a without rowid table is being worked on. These include adding and deleting rows as well as editing cells. It would also be nice to have a checkbox in the create table dialog which adds the 'without rowid' option to the table definition.

**Comment by MKleusberg** [comment]
Finally implemented the missing 10% :smiley:

**Comment by justinclift** [comment]
Yay! :smile:
