### ISSUE TITLE
Show rowid column not correctly refreshing the table view

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#510]
If I select `Show rowid column`, the column headers correctly refreshes to show the new `rowid` column, but the columns data retains the old columns count.

So, after selecting the option, it looks like this:

![screen shot 2016-02-01 at 12 39 22](https://cloud.githubusercontent.com/assets/5748627/12715280/1eebccb4-c8e2-11e5-8511-cb3262410e59.png)

After __just right click-ing__, it correctly refreshed the columns data:

![screen shot 2016-02-01 at 12 39 30](https://cloud.githubusercontent.com/assets/5748627/12715296/3747f85a-c8e2-11e5-98f1-94c97ec41ccb.png)

After clicking the option again to disable the option, it looks like this:

![screen shot 2016-02-01 at 12 39 38](https://cloud.githubusercontent.com/assets/5748627/12715308/4b8d487e-c8e2-11e5-8128-2a78d4a54ff3.png)

And after right click-ing again, it goes back to the correct initial form:

![screen shot 2016-02-01 at 12 39 43](https://cloud.githubusercontent.com/assets/5748627/12715319/5ec1fbe2-c8e2-11e5-9eca-5e5061c86317.png)

**Comment by zwrmueller** [comment]
can confirm this with Win 7 SP1 and nightly build 3.8.99

Ralf

**Comment by justinclift** [comment]
Turns out this isn't quite as fixed as we'd thought. 😦 

@karim pointed out in https://github.com/sqlitebrowser/sqlitebrowser/issues/639#issuecomment-232600998 that the nightly build, which included this fix... still has the issue.

Looking at the [build log](http://sqlitebrowser.oldsch00l.com/build.log), that shows it using the correct git commit for building from.  Which means the code wasn't somehow missed out:

```
From https://github.com/sqlitebrowser/sqlitebrowser
   3b2c192..e7b3011  master     -> origin/master
Updating 3b2c192..e7b3011
Fast-forward
 src/EditDialog.cpp       |    2 +-
 src/EditDialog.ui        |   10 +++++-----
 src/MainWindow.cpp       |    2 ++
 src/sqlitetablemodel.cpp |    7 ++++++-
 4 files changed, 14 insertions(+), 7 deletions(-)
```

Now... to figure out WTF is going wrong.  Initial thought it maybe it's a Qt4/Qt5 thing?  I'll try compiling it here on OSX using Qt4 (instead of Qt5, which I used yesterday), and see if it's broken or not.

**Comment by revolter** [comment]
I think I'm using Qt4 home, where I solved this. I have no idea why wouldn't it work. And, how comes it worked with another nightly build?

**Comment by justinclift** [comment]
Yeah, I just tried it here on OSX with Qt4.  The bug is definitely not a Qt4/Qt5 problem.

Our official nightly builds are a static build, cross compiled on a Linux host using MXE.

The one off Windows build I created for testing the fix was made using MSVC on Win 8.1, and uses shared libraries.

So... yeah... I'm not sure either.  ... and I'm not sure what to check next. 😦

**Comment by revolter** [comment]
Wouldn't it be simpler for @karim to test again the latest nightly build today, which is guaranteed (I guess) to include the fix?

**Comment by karim** [comment]
The fix is working with this build http://nightlies.sqlitebrowser.org/win64/sqlitebrowser-win64-issue639v2-201607131125.exe but not with this one http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip

**Comment by justinclift** [comment]
Hmmm, I suppose it won't hurt.  I was under the impression that the build log for http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip was showing the fix already included. :wink:

**Comment by justinclift** [comment]
Ahhh, as a data point, the domain name for the nightlies might be giving the wrong impression with this one:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/win64/sqlitebrowser-win64-issue639v2-201607131125.exe

That one's not **really** a nightly build.  It's just a once off I chucked on the server for people to test.

Maybe I should rename that `win64` directory to `win64-onceoffs` or something?

**Comment by revolter** [comment]
Yes, I think it's a good idea not to mix nightlies and manual builds.

**Comment by justinclift** [comment]
k, moved those two into a hopefully-better-named subdirectory instead:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/win64-onceoffs/

**Comment by karim** [comment]
I tried the latest nightly build just now, and still the same problem.

**Comment by revolter** [comment]
On what OS?

**Comment by karim** [comment]
Windows 7 SP1 (64-bit).

**Comment by karim** [comment]
I don't think it is DB4S fault though. It could be a library problem. Cause after I reverted back to official version (3.8.0), show rowid is now working correctly.

To make it more clear, I was using the official version (3.8.0) and I had both problems (crashing, and not refreshing rowid). Then I uninstalled it, and installed the one @justinclift made in the the "win64-onceoffs" folder, and it fixed both. He told me to test the nightly build, and this build fixed the crash bug only. Then I uninstalled this "onceoff" version, and went back to the official one (3.8.0) and it is showing rowid correctly now.

Link | Crash | Show rowid | Qt
------------ | -------------|-------|-----
[sqlitebrowser-3.8.0-win64v2.exe][1] | Yes | Working | 5.5.1
[sqlitebrowser-win64-issue639v2-201607131125.exe][2] | No | Working | 5.6.0
[sqlitebrowser.exe.zip][3] | No | NOT Working | 4.8.7

[1]: https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.8.0/sqlitebrowser-3.8.0-win64v2.exe
[2]: http://nightlies.sqlitebrowser.org/win64/sqlitebrowser-win64-issue639v2-201607131125.exe
[3]: http://sqlitebrowser.oldsch00l.com/sqlitebrowser.exe.zip

**Comment by justinclift** [comment]
Hmmm, well that's just weird. :wink:

**Comment by karim** [comment]
True. But to be honest, it could be also something on my PC. Anyway, I'm using the version you made and it is working fine. I will just wait for the next release (3.9.0) and see how it goes. Thanks @justinclift and @revolter for your help. :+1:

**Comment by justinclift** [comment]
No worries at all, sounds like a decent plan. :smile:

**Comment by revolter** [comment]
@zwrmueller, As a safety check, can you test this too with the latest nightly?

**Comment by zwrmueller** [comment]
I can confirm Karim:
sqlitebrowser-win64-issue639v2-201607131125.exe  Working  Qt 5.6.0 
sqlitebrowser.exe.zip (06.08.2016)                       NOT Working  Qt 4.8.7

**Comment by justinclift** [comment]
Thanks @zwrmueller. :smile:

It sounds like the Windows builds will definitely need to be build using Qt5.
