### ISSUE TITLE
Plot when values are NULL

### ISSUE THREAD

**Issue by wolfc01** [sqlitebrowser/sqlitebrowser#512]
Hello,

in attached database, i perform the attached query. 

[test_db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/121597/test_db.zip)

**Comment by justinclift** [comment]
This is a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/513 isn't it?  If so, is it ok to close this one? :smile:

**Comment by MKleusberg** [comment]
Closing this as duplicate.
