### ISSUE TITLE
Plot when values are NULL

### ISSUE THREAD

**Issue by wolfc01** [sqlitebrowser/sqlitebrowser#513]
Hello,

in attached database, i perform the following query:

select \* from M1 left join M2 on M1.timestamp = M2.timestamp
This delivers the below result (in CSV format):

timestamp,M1,timestamp,M2
2015-07-15 23:59:51,0.0,2015-07-15 23:59:51,10.0
2015-07-15 23:59:52,1.0,2015-07-15 23:59:52,12.0
2015-07-15 23:59:53,2.0,,
2015-07-15 23:59:54,3.0,,
2015-07-15 23:59:55,4.0,,
2015-07-15 23:59:56,5.0,2015-07-15 23:59:56,13.0
2015-07-15 23:59:57,6.0,2015-07-15 23:59:57,14.0
2015-07-15 23:59:58,7.0,2015-07-15 23:59:58,15.0
2015-07-15 23:59:59,8.0,,

But in the plot I can only select 'timestamp' and 'M1'.  'M2' is not available presumably because there are NULL values present in that column.

Is it possible to add a feature to have this column available also in the plot, and draw previous value or Nothing (plot with holes) when NULL values are present in the query result?

Best regards
Carl.

[test_db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/121597/test_db.zip)

**Comment by zwrmueller** [comment]
could be also related to:
*Plot misses columns with NULL as first value* #499

Regards Ralf

**Comment by MKleusberg** [comment]
This is related to issue #822. Good news is that this is finally fixed now.
@wolfc01 If you are still interested in this, can you try tomorrow's nightly build and report back if it's working for you now? :smiley:

**Comment by MKleusberg** [comment]
Any update on this, @wolfc01? :smiley:

**Comment by MKleusberg** [comment]
Closing this because it's an old issue without any updates recently. If this isn't working for you as expected, please reopen this issue. :smiley:

**Comment by justinclift** [comment]
@wolfc01 Carl, out of curiosity did you ever get time to check if this is fixed from your point of view?

**Comment by zwrmueller** [comment]
Hi Justin, how can I make use of and test the nightly builds for Windows64 if I sit on a sqlitebrowser **portable app** version and have no administer priviledges?

Regards
 Ralf

**Comment by justinclift** [comment]
@zwrmueller Hmmm... I don't think we have a useful ongoing way to do that (yet).

If you need a something "once off", I can grab our latest nightly, install it in a VM here, then make a .zip file of the installed files.  If think if you unzip them into a place of your choosing, then that might work.

No guarantees 😁 , but worth a shot if you need a nightly to try. :smile:

**Comment by chrisjlocke** [comment]
You don't need to install in a VM and .ZIP it back up again - simply download the latest nightly and unzip that using 7zip - it'll create some 'wacky' directories, but the core files will be in one directory, then the 'platforms' directory.

**Comment by justinclift** [comment]
@chrisjlocke Cool, didn't know that.  Sounds practical then. :smile:

**Comment by chrisjlocke** [comment]
So, ignore the $PLUGINS directory, as thats the setup file's 'noise'.

![image](https://cloud.githubusercontent.com/assets/7872218/25914358/eb1c55c4-35b5-11e7-82d5-d16b3a073f7b.png)

...and the 'redist' directory, as that'll be installed anyway.  So just replace the files in the 'APP' directory of the portable installation.

I'll write this into the Wiki, as I'm sure someone else out there has the portable version! ;)  🍫

**Comment by zwrmueller** [comment]
Great! I checked this before but was'nt successful. But you encouraged me to hang on. And in addition to your hints, for me I needed to replace (update) the platforms directory in addition to the files mentioned by you.

Thanx Ralf
