### ISSUE TITLE
SQLCipher?

### ISSUE THREAD

**Issue by fmeneuhe** [sqlitebrowser/sqlitebrowser#515]
Does the Windows version support SQLCipher?

**Comment by justinclift** [comment]
The official release(s) for Windows don't yet have SQLCipher support added.

However, @huy-cong was able to compile things himself and include it.  More information [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/12#issuecomment-175526863), if that's an option for you. :smile:

**Comment by justinclift** [comment]
@fmeneuhe Did that help at all?

**Comment by MKleusberg** [comment]
@fmeneuhe There's now. @justinclift made a Windows executable with SQLCipher support which you can find here http://nightlies.sqlitebrowser.org/win64/sqlitebrowser-win64-with_sqlcipher-201605041823.exe

**Comment by justinclift** [comment]
Yeah, that's an early test build.  Everything should pretty much "just work" in it ok, as it uses the SQLCipher support that's been in our code base for a few versions now (on OSX, Linux, etc).

Am working through the process to make Windows support easier, and kind of hoping we can get SQLCipher support built into our next Windows releases from here on.  (that may or may not happen right away though, will need to do some more investigation/testing/etc)

**Comment by revolter** [comment]
@justinclift Should we close this?

**Comment by justinclift** [comment]
Hmmmm, I'm on the fence about it.  Maybe lets wait for 3.9.0 to be released and people are using it?

**Comment by justinclift** [comment]
Added 3.10.0 milestone, so we remember to look back at this to check. :smile:

**Comment by justinclift** [comment]
Closing this now, as the SQLCipher support included with 3.9.0 seems to work ok. :smile:
