### ISSUE TITLE
request icon pixel low quality

### ISSUE THREAD

**Issue by mvkrdndm** [sqlitebrowser/sqlitebrowser#517]
hello , just installed look so quality but unfortunately on windows 10 desktop icon low on pixel can you please modify the icon ,i am ok with the image itself but looks ugly when pixels are low

**Comment by justinclift** [comment]
That makes sense.  We can probably fix that without too much effort. :smile:

**Comment by glawrence** [comment]
Possibly but still struggling with getting myself a good development setup and finding time

**Comment by justinclift** [comment]
No worries.  Properly documented Windows build instructions are more important. :smile:

**Comment by mgrojo** [comment]
@scottfurry Might this be solved by #2275  and #2270?

**Comment by scottfurry** [comment]
#2275 should have addressed this. In hindsight, maybe add a 48 px. However, this should should be "resolved".

**Comment by mgrojo** [comment]
@mvkrdndm If you're still around, this issue should be solved in our last release 3.12.0. I'll close this, but you are free to reopen it if you consider there is still something pending.
