### ISSUE TITLE
Automatic update installer?

### ISSUE THREAD

**Issue by sman591** [sqlitebrowser/sqlitebrowser#518]
Has there been any thought to using an update installer? This way users can just press "Install & Restart" instead of having to go to the GitHub & re-download.

One that comes to mind for Mac OS X is this: https://sparkle-project.org/

**Comment by justinclift** [comment]
Yeah, that would be good.  We've had some previous discussion about it here: https://github.com/sqlitebrowser/sqlitebrowser/issues/162

@samir-aguiar has been super busy with his work though, so doesn't have time for this in the short/medium-term.

@sman591 Is it something you'd be interested in getting to work, even if for (say) just OSX for now?

**Comment by sman591** [comment]
My apologies - my issue search somehow didn't turn that issue up!

I'm afraid I don't have enough time or experience with OS X (only Swift for iOS) to get it working at the moment.

**Comment by justinclift** [comment]
No worries at all, thanks for taking the time to make the suggestion. :smile:
