### ISSUE TITLE
make mac release .app have better name

### ISSUE THREAD

**Issue by mgrandi** [sqlitebrowser/sqlitebrowser#520]
I don't like how the name is just 'sqlitebrowser.app', so i always rename it to be SQLite Browser, is there a way to modify the build scripts so it has a prettier name by default? =)

**Comment by justinclift** [comment]
Yeah, it should be pretty trivial to do.  "SQLite Browser.app" sounds like a decent start.

I'll update the nightly build script, and see if any problems show up from that.  If they don't it's probably that simple. :smile:

**Comment by justinclift** [comment]
Well, that didn't work.  The "macdeployqt" command fails.  Seems like it can't handle the space in the filename, which is weird. :frowning:

**Comment by mgrandi** [comment]
maybe it needs to be escaped? "SQLite\ Browser.app" ?

**Comment by justinclift** [comment]
Yeah, trying variations now.

**Comment by justinclift** [comment]
Renaming it definitely isn't a go-er.  What does seem to work though, is changing the TARGET line in src/src.pro prior to compiling:

    TARGET = 'SQLite Browser'

That creates a 'src\SQLite Browser.app', which macdeployqt works with.

Updating the nightly build script with that now.  Should be good for the next release too (in theory). :smile:

**Comment by glawrence** [comment]
@justinclift will you be committing that change then or do you have a fork on your build server? Just asking in case you forgot

**Comment by glawrence** [comment]
I don't know, maybe it is, the name on the Windows Start Menu doesn't look great to be honest. I just assumed that as https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/src.pro contains the TARGET line you would change it. No problem though.

**Comment by justinclift** [comment]
k, we should probably consider it then.  We'll probably need to make it conditional, so the command line version on BSD/Linux will still be one word.

It could be as simple as putting the TARGET keyword definition inside the "mac" and "win32" sections of src.pro.  I don't have the time/inclination to try it right now, but should get time to over the next few days.  Ping me if you don't hear from me. :smile:

**Comment by justinclift** [comment]
Finally got around to looking into this.  Putting an updated TARGET keyword into the mac definition works.  Didn't seem to make any difference for the win32 one, though I left it in there so others can check closer. :smile:
