### ISSUE TITLE
Enter key while editing a field causes problems

### ISSUE THREAD

**Issue by troyhen** [sqlitebrowser/sqlitebrowser#521]
I'm using 3.8 on Windows 10. When I am entering text in a cell I press the Enter key to save the cell/row. In 3.7 that simply did what I expected. It saved the changes. But in 3.8 it saves the changes then pops up the cell editor window, but the contents of the editor are the old value of the cell BEFORE my last entry change. I have to remember hit Esc or Cancel the dialog each time. This is unexpected and confusing behavior, and causes extra steps and potential data loss. I don't mind that the Enter key pops up the cell editor window, but only when I was NOT editing a field. Popping up the editor dialog should be the behavior only when I am navigating cells. And if/when it does pop up it must contain the latest version of the cell, not some previous version.

**Comment by justinclift** [comment]
Yeah, this new behaviour isn't great.  Hoping Martins gets time to fix it in the near future. :smile:

**Comment by pmcoz** [comment]
I'm getting this too, on Windows 7. I notice it when attempting in-place editing.

**Comment by MKleusberg** [comment]
I thought this was already fixed some time ago? @troyhen and @pmcoz, can you maybe test the latest nightly build (see main page of the repository for download links) and check if the error is fixed in there?

**Comment by pmcoz** [comment]
@MKleusberg: that seems to be fine! Thanks for the suggestion (which I should have thought of myself).

Might I suggest that rolling this change into a production release be given some priority, because the status quo gives the appearance of data loss, and could conceivably result in same if the user doesn't work around the problem correctly.

I'm glad I created a github account for this issue. :)

**Comment by troyhen** [comment]
I have verified that this is fixed in the nightly builds. I look forward to the 3.9 release.

**Comment by justinclift** [comment]
@troyhen Thanks.  And yeah, hopefully it's not too far off.  We may put it off for a few days though, to get some more changes in. :smile:

**Comment by revolter** [comment]
@justinclift, Shouldn't this be closed now?

**Comment by justinclift** [comment]
Yep, well spotted. :smile:
