### ISSUE TITLE
Import from CSV not naming columns correctly

### ISSUE THREAD

**Issue by 2ndCharter** [sqlitebrowser/sqlitebrowser#522]
v. 3.8.0 for Windows (64 bit)

1. Create new sqlite database.
2. When prompted to create table, hit cancel.
3. Go to File > Import > Table from CSV file...
4. Select a CSV file where the column names are in the first row.
5. Check option for "Column names in first line".
6. Click "OK".

Table will be created but the column names will still be in the first row. Columns will be named "field[n]...". 

Perhaps this is intentional but most other db GUIs I've worked with would take that first row and name the columns based on the text in that column's cell. That's the expectation I have when I select that option. If I don't select that option, I still get the column names in one of the rows but I now get a blank line above that row at row #1.

**Comment by justinclift** [comment]
Yeah, that sounds like a bug. :frowning:

**Comment by wierzba3** [comment]
I've followed those same exact steps and could not re-create this bug. The columns are named as expected. Is there anything else you did not mention in your test case? (Using windows 7 x64)

**Comment by 2ndCharter** [comment]
I forgot to post back a follow-up. The problem wasn't with the sqlitebrowser, it is with the CSV. If the tool that generates the file has white space before your first row, probably a line break, then you get the effect mentioned.

**Comment by justinclift** [comment]
Ahhh cool, thanks for taking the time to update this. :smile:
