### ISSUE TITLE
Edit Cell dialog window position problem

### ISSUE THREAD

**Issue by woody1955** [sqlitebrowser/sqlitebrowser#526]
Bij modify a cell, the title of the screen is "Edit database cell".
This screen fly van center to the left top corner.

**Example:**
"5684 GM" --> "5684GM" --> no space inside string (screen center), next
"5684 WX" -->"5684WX" --> no space inside (screen left top), screen center, screen left to
en so on.

**Comment by justinclift** [comment]
That's very difficult to understand. :frowning:

Guessing you are using Google Translate or something? :smile:

As a thought, are you able to do some screenshots to show the problem?  That might help overcome the language barrier. :smile:

**Comment by woody1955** [comment]
-Open a Database.
-Browse Data (filled database).
-Double click on a cell (filled).
    A screen with the name "Edit database cell" is shown, position left top corner.
-Press now the button cancel.
Double press again on the same cell.
   The screen what is shown has now a different postion (centre)
Repeat this several times.

**Comment by glawrence** [comment]
@woody1955 did you close this because you are happy or by mistake?

**Comment by woody1955** [comment]
Closing was a mistake

**Comment by MKleusberg** [comment]
I *think* this should be fixed in the latest nightly build. Do you have the time to confirm this, @woody1955 ? Just download tomorrow's nightly build (or any later one) from the main page of our repository and try the new version :smiley:

**Comment by justinclift** [comment]
This seems to be the same as #633, which is definitely fixed. :smile:

**Comment by justinclift** [comment]
I'm going to close this for now, as I'm **really** sure it's the same as #633.

@woody1955 The fix for this is in our "3.9.0 beta1" release, if you want to try it out:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1

If for some reason it doesn't work for you, you are definitely welcome to reopen this issue so we can investigate. :smile:

**Comment by chrisjlocke** [comment]
This isn't applicable anymore, and the 'dialog' window doesn't exist, does it?  Pressing Enter on a cell now displays the dockable / floating 'edit cell' panel.  If I click 'View' and 'Edit Database Cell' the docked window disappears, but double clicking a field cell just pings it back again.
I noticed (by accident) pressing Ctrl+Enter clicks the 'Apply' button, which is handy, but it would be handier if focus returned back to the grid.  Minor grip-ette though... :wink:

**Comment by justinclift** [comment]
Ahhh, yeah.  Good thinking @chrisjlocke.  It should be fairly trivial to make the Apply button change focus back to the main window.

Do you have time/interest to open a new issue for that, so it's not forgotten?  If you don't, I can do it. :smile:

**Comment by chrisjlocke** [comment]
I'll keep an eye on the issue counter.... I think there are 178 other more deserving issues to resolve first! :wink:  When we get to below 100 and people are bored, scratching around for something to do, I'll add this one! :stuck_out_tongue_winking_eye:

**Comment by justinclift** [comment]
You know... that would actually be really welcome. :smile:

If you're serious, this might help:

* [An Introduction to Design Patterns in C++ with Qt 4](http://www.informit.com/store/introduction-to-design-patterns-in-c-plus-plus-with-9780131879058)

Unlike what the potentially scary title sounds like... it's targeted at people with no experience or understanding of C++ or Qt, so introduces both on the way through.

Also, if you click on the "Download" tab there (middle of the page), you can download the whole thing as PDF.  No cost involved. 😁

**Comment by chrisjlocke** [comment]
Thanks for that.  Will defo download that and have a play. :smile:
