### ISSUE TITLE
v3.8 portable doesn't run under WinXP 64bit SP2

### ISSUE THREAD

**Issue by AAA111BBB** [sqlitebrowser/sqlitebrowser#527]
I'm still using WinXP 64bit SP2.
There were no problems with SQLiteBrowser 3.7 Portable.
For ver.3.8 Portable, the
SQLiteDatabaseBrowserPortable\App\SQLiteDatabaseBrowser32\sqlitebrowser.exe
runs ok
while
SQLiteDatabaseBrowserPortable\App\SQLiteDatabaseBrowser64\sqlitebrowser.exe
windows doesn't recognize as a compatible application and doesn't start it.
Why are builders not using a compatible compiler???

**Comment by justinclift** [comment]
Not sure.   We probably didn't really think about XP having a 64-bit version available.  Shouldn't be hard to fix from now on though... guessing it's just a matter of changing a setting in Visual Studio for the win builds. :smile:

**Comment by MKleusberg** [comment]
Closing this issue as it's really old and the build process has changed too much in the meantime. Can you open a new issue for this if there's still a problem like this with the latest release? We're trying to make DB4S for as many users as possible but only have time to do so for our latest releases :smile:
