### ISSUE TITLE
Check constraint on table prevents new record being added

### ISSUE THREAD

**Issue by mh00h** [sqlitebrowser/sqlitebrowser#530]
I'm having difficulty adding a record when a check constraint is defined. I can provide a db example offline if anyone can help me?

**Comment by justinclift** [comment]
In theory, we'd like to.  Most of our dev's seem to be taking a break recently now though, so we're kind of short on people with knowledge & free time. :frowning:

**Comment by Jeff-G** [comment]
I just came across a concrete example for this:

    CREATE TABLE "AAA" (
        "FIELD" TEXT,
        CONSTRAINT "AAA-FIELD-EVEN_LENGTH_CHECK"
            CHECK(LENGTH("FIELD") % 2 = 0)
    )

The fix for issue #505 seemed to fix some of these, but the constraint parser clearly has some unresolved issues.  The above table prevents inserting new records (or browsing the data within it) in the April 3, 2016 nightly build.

**Comment by MKleusberg** [comment]
Sorry for taking so long with this but we have finally merged a change by @mgrojo which should fix this problem :smile: If you're still around, can you give [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) a try and see if it's working now, @mh00h and @Jeff-G?

**Comment by mh00h** [comment]
Thanks guys. I'm not working on the previous project right now and don't have a good way to test it anymore. Nevertheless thank you to the individual who merged this.
