### ISSUE TITLE
Importing CSV from Excel Reverses Row Order

### ISSUE THREAD

**Issue by bryantm1123** [sqlitebrowser/sqlitebrowser#534]
Hi, 
Really great product! The only issue I've come across so far is that when I import a csv that I exported from Excel, my data rows get reversed: 
![table_reversed](https://cloud.githubusercontent.com/assets/16559983/13459914/0b01b2b6-e045-11e5-8ec7-bf616931372c.jpg)

As you can see, I've added a column called "ID" and designated it as Primary Key. It matches the order of the data in the csv. Does the built-in rowid order matter? Am I in good shape as long as the PK order is correct?

Thanks again,
Matt

**Comment by rp-** [comment]
Please be aware that SQL (don't matter which database implementation) does not define a default order.
Order is only guaranteed if an ORDER BY is specified by a query.
You can sort your data by clicking a column header
