### ISSUE TITLE
Open Remote Database

### ISSUE THREAD

**Issue by TFMV** [sqlitebrowser/sqlitebrowser#535]
Would it be possible to open a sqlite3 database hosted on a remote server (Azure to be specific), provided the connected using has the proper authorization?

**Comment by justinclift** [comment]
It depends on the protocol used to access the remote database.  Generally it's not a good idea though, as (from memory) even many file based protocols don't get file locking correct... and if something goes wrong with the connection without the files being committed/flushed correctly, the database could be corrupted.

**Comment by jungle-boogie** [comment]
These are options I thought of:

a) connect to the remote location and run the sqlite3 command on the server.

b) I believe azure is windows hosting (although can be linux, I think) so that means you can install sqlitebrowser on that thing and open the db locally, right?

c) download the database and use sqlitebrowser to browse it locally.

**Comment by TFMV** [comment]
I use option a today, but I just found the sqlitebrowser yesterday and
thought it would be nice if I could connect directly from the client to the
remote DB file.  I did find an ODBC for sqlite that has promise.

*Thomas F. McGeehan V*

**Comment by mgrojo** [comment]
@TFMV  I hope we have helped you. I'll close this now, but you can still comment on it if you'd like.

**Comment by bam80** [comment]
We could use [Qt for WebAssembly](https://www.qt.io/qt-examples-for-webassembly) for this - just look at the [Demo](https://www.qt.io/cs/c/?cta_guid=3dc35563-7a40-4061-b98b-b66f42959c8d&placement_guid=3bba596e-b49d-42b2-8846-5afc7f2d8da8&portal_id=149513&canon=https%3A%2F%2Fwww.qt.io%2Fqt-examples-for-webassembly&redirect_url=APefjpGZyQ5neZCyXkum2fCns8qxdluAOzwRI3DrE6QJ6NcJ-1OOEvhwjM4EyfzTVoohishZKBf8ncYVu1d-mdEP1hIo1L7v66BVZ9eknSSwOv11fKIn1z4AIVOoFE5713v-f3JjaUrc&click=31caae23-071f-41b6-bd13-3aacfc734071&hsutk=c7a0000016421f091585017003774abd&signature=AAH58kFZ1KM_ZB9mRYh2sUjz4CM80EXpHg&pageId=9712425852)! No need to re-write the app.

**Comment by justinclift** [comment]
Yeah, that's a possibility people have raised before.

Not sure how well it would **really** work out though, but if someone wants to put the effort into experimenting and finding out, then sure... the results from that would be interesting to see. :smile:
