### ISSUE TITLE
Feature request: Option to turn off "intellisense"-like suggestions

### ISSUE THREAD

**Issue by cjdavies** [sqlitebrowser/sqlitebrowser#537]
When writing SQL in the "Execute SQL" pane, the browser tries to suggest table names in a similar manner to IntelliSense in some IDEs. It interferes with my typing. I really hate this feature. How can I disable it?

**Comment by justinclift** [comment]
Ahhh, that's not a bad thought.  From memory, it's not possible to do via an option at the moment, but it's probably something we should add. :smile:

**Comment by MKleusberg** [comment]
Hi Colin!
Can you test the tomorrow's nightly buld (for download locations see the main page of our repository)? In this new version there is an option in the Preferences dialog for disabling the auto completion: View -> Preferences; SQL -> remove the tick next to 'Code completion'. Please let me know if this improves your user experience :smiley:

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by justinclift** [comment]
@cjdavies Ping? :smile:

**Comment by MKleusberg** [comment]
Closing this as we have had a fix for this for some time now. If there are any issues remaining please just reopen the issue.
