### ISSUE TITLE
Preferences Not Used 

### ISSUE THREAD

**Issue by iainrs** [sqlitebrowser/sqlitebrowser#539]
I'm running Version 2.0b1 on Linux Mint 17.3 XFCE.
If I try to set an alternative location it shows it in the text box and I click OK. The config file (SQLite Database Browser 2.conf) is saved in ~/.config/sqlitebrowser.sf.net. But when I try to open a database it goes straight to my home folder. 

When I go back to Preferences it now has my home folder shown

[db]
defaultencoding=UTF8
defaultnewdata=NULL
defaultlocation=/home/xxxx/Data/xxx/Desktop/gps/
defaulttext=Plain

Is the preference file saved somewhere else ?

**Comment by justinclift** [comment]
The 2.x version is about 10 years old, and uses a previous code base.  It's not something we can really comment on... :frowning:

Are you able to get a more recent version running?  Compiling yourself is generally not hard, if there aren't any packages available for you:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

**Comment by iainrs** [comment]
Hi
Thanks for quick response.
With a little trepidation I decided to compile as suggested.
Loaded dependencies, then ran as per website.
All worked OK.
Now have working version 3.8.0
Thanks a lot

Iain

**Comment by justinclift** [comment]
You're welcome. :smile:
