### ISSUE TITLE
Unique constraint deleted after table edit

### ISSUE THREAD

**Issue by tchaloupka** [sqlitebrowser/sqlitebrowser#540]
Lets have table like this:
CREATE TABLE "Foo" (
	`Id`	INTEGER,
	`Name`	TEXT NOT NULL,
	`Bar`	INTEGER NOT NULL,
	`Baz`	TEXT,
	PRIMARY KEY(Id),
	UNIQUE (`Bar`, `Baz`)
);

If you edit it within the app, unique constraint is not read from the DB and after edit it is gone completely.

**Comment by justinclift** [comment]
As a thought, which version is this happening in, and which OS? :smile:

**Comment by chalucha** [comment]
Ah sry :)
Its with 3.8.0 on Fedora 23 x86_64

**Comment by justinclift** [comment]
Yeah, it looks like we have some constraint handling problems that need addressing.  You're not the only person to point this out recently. :innocent:

The person who'll likely fix this is @MKleusberg, and he's doing holiday stuff for the next month.  But (in theory) he should be back and able to look at this after that.  Sorry it won't be looked at in the short term. :frowning:

**Comment by MKleusberg** [comment]
Took a bit longer but this should be fixed in the next nightly build :smiley: Editing of such UNIQUE constraints isn't supported yet (that would be issue #538) but at least such constraints are understood now by DB4S and aren't lost during editing.
@tchaloupka Are you still around and have the time to test the next build? :smiley:

**Comment by tchaloupka** [comment]
Hi, I've tested it with the current master and it seems to work. Thanks!

**Comment by justinclift** [comment]
@tchaloupka Thanks for testing this, and letting us know.  It definitely helps. :smile:

**Comment by justinclift** [comment]
@MKleusberg Should we add the fix for this to the v3.9 branch, or leave it for 3.10?

**Comment by MKleusberg** [comment]
@tchaloupka Thanks a lot for your fast reply :+1: That's good news :smiley: 

@justinclift Hard to say. If we have a second beta version then definitely yes. If not, my intuition would still be to include it but I wouldn't guarantee it to be bug-free (but then again, it wasn't bug free to begin with either) :smiley:

**Comment by justinclift** [comment]
Thanks @MKleusberg. Moving this to 3.10 then. :wink:

We could put out a the first of the 3.10 releases without huge delay, if things look decent.  There's no major reason we need to have 6+ months between each release. 😁
