### ISSUE TITLE
SQL Lite Browser crashes on starting 

### ISSUE THREAD

**Issue by rithvikmundra** [sqlitebrowser/sqlitebrowser#543]
Hi 
I just installed the latest version of sqllite browser on my 64 bit windows 10 PC.
The sqllite browser opens and when i click on new databases, the application crashes.
Microsoft Visual C++ Redistributable 2013 is also installed on my PC.
Can any of you please provide me with a solution for this problem?

**Comment by justinclift** [comment]
Wish I could help.  I don't have Windows 10 (and won't ever be running it), so this isn't something I can personally try and find a solution to.

Other people here may be able to help you though. :smile:

**Comment by DolbyCpp** [comment]
Try execute in compatibility mode.

**Comment by rithvikmundra** [comment]
Hi,
I have selected the compatibility mode and tried in both win 8 and win 7 mode .... but still its not working.

**Comment by glawrence** [comment]
I have a Windows 10 VM and have no issues. You issue seems similar to https://github.com/sqlitebrowser/sqlitebrowser/issues/495 which is also a puzzle. Have you tried latest the nightly build?

**Comment by rithvikmundra** [comment]
Installing the nightly build version worked for me.
Thanks lawrence

**Comment by glawrence** [comment]
Glad it worked but that is far from ideal from a project point of view. Thanks for updating us though.

**Comment by chrisjlocke** [comment]
Just as a 'fix' (which isn't a fix...) but as 'new database' always opens in a 'random' directory* (or at least not where I want the database) I open an Explorer window and create a new file where I want it, call it 'xyz.sdb' and then double click this file.  

*OK, not random, but not always the directory the last database was opened either.

**Comment by justinclift** [comment]
@rithvikmundra If you have a few minutes, would you be ok to try the "3.9.0 beta1" release we did last weekend?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1

The Windows files there were built using an updated process, that (in theory) should be ok for everyone now. :smile:
