### ISSUE TITLE
Execute SQL pane - 'Execute current line' executes remaining SQL 

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#547]
When in the 'Execute SQL' tab and entering SQL into the window, when I press the 'Execute current line', the SQL from the cursor downwards is executed, which isn't 'the current line'.  (am using Windows 3.7.0 ... also same behaviour in 3.8.0)
Unsure if this is 'by design' (kind of makes sense if you split SQL over several lines and want all those lines executed, eg half-way in the window...) but isn't quite 'what the button says will happen'.

**Comment by justinclift** [comment]
Hmmm, good point.  Should be a simple fix. :smile:

**Comment by chrisjlocke** [comment]
Thanks.  I noticed that highlighting SQL and pressing F5 only executes the highlighted commands.  This seems an 'undocumented feature' ... unless its standard in other sql systems.  It gets around the above issue though... albeit a bit long-winded sometimes...

**Comment by MKleusberg** [comment]
This should be fixed by now :smiley: Can you double check using the latest version?

And yes, the highlighting something and pressing F5 is an intentional, but undocumented feature. Maybe it makes sense having a Wiki page for each of the main tabs (and maybe the dialogs) mentioning the shortcuts and hidden features.

**Comment by chrisjlocke** [comment]
> mentioning the shortcuts and hidden features.

But then they would no longer be hidden.... 😉

**Comment by chrisjlocke** [comment]
I'll look at adding some Wiki pages.
This does indeed work in the latest nightly.

Just one slight query.  Executing the current line / SQL enables and then disables the 'Write Changes' and 'Revert Changes' buttons.  Is this correct?  Seems unnecessary and slightly confusing...

**Comment by MKleusberg** [comment]
@chrisjlocke You're right :confused: Just tried two workarounds and neither of them helped. What wonders me most is that everything's so slow that you can actually easily see it.
