### ISSUE TITLE
New Database = Crash

### ISSUE THREAD

**Issue by whieronymus** [sqlitebrowser/sqlitebrowser#552]
I just started using DB Browser for SQLite and each time I attempt to Create a new Database the program crashes with the error "sqlitebrowser.exe has stopped working..."

I'm using Windows 7 Profressional 64 bit, and I tried using both the 3.8 and 3.7 builds with no luck. I also tried opening as administrator, still no luck.

Is there something I'm doing wrong? Is there a setup step I'm missing?

Thanks!

**Comment by whieronymus** [comment]
Looks similar to [Issue #543](https://github.com/sqlitebrowser/sqlitebrowser/issues/543)

**Comment by justinclift** [comment]
Yeah, there's definitely some weird edge case that causes crashes (with the standard release) for a few people.  Personally, I have no idea where to even start for debugging it.

Keep using the Nightly's I guess. 😧

**Comment by justinclift** [comment]
@whieronymus If you have a few minutes, would you be ok to try the "3.9.0 beta1" release we did last weekend?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1

The Windows files there were built using an updated process, that (in theory) should be ok for everyone.

Theory however... well... I'd rather someone test it and confirm. 😁

**Comment by whieronymus** [comment]
Sure @justinclift, it will probably be tomorrow before I have a chance, but I'll give you a shout once I do.

**Comment by justinclift** [comment]
Thanks @whieronymus. :smile:

**Comment by justinclift** [comment]
@whieronymus Reminder ping?

Note, we [released 3.9.0 yesterday](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0), so that would be the one to test with instead. :smile:

**Comment by justinclift** [comment]
Last reminder ping... :wink:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
