### ISSUE TITLE
Error:sqllitebrowser.exe has stopped working

### ISSUE THREAD

**Issue by sheethalkumarsm** [sqlitebrowser/sqlitebrowser#554]
Hi

we are getting error when we open the DB. Error as follows

"sqllitebrowser.exe has stopped working"

please advise us how to work on this exe

**Comment by whieronymus** [comment]
Hi Kumar,

I posted a similar issue yesterday, and it's been posted a few times before. I'm assuming you're using Windows 7-10?

Here are the previous threads: 
[Issue #552](https://github.com/sqlitebrowser/sqlitebrowser/issues/552)
[Issue #543](https://github.com/sqlitebrowser/sqlitebrowser/issues/543)
[Issue #495](https://github.com/sqlitebrowser/sqlitebrowser/issues/495)

It appears this is a somewhat uncommon issue with no current fix. However, there is one current workaround using the Nightly Builds [Located here](http://rp.oldsch00l.com/sqlitebrowser/). Using the nightly build worked just fine for me and others. I hope this helps you move forward, and hopefully they are able to track to the cause of this crash soon!

**Comment by justinclift** [comment]
@whieronymus Thanks for helping out. 😀

**Comment by justinclift** [comment]
@sheethalkumarsm If you have a few minutes, would you be ok to try the "3.9.0 beta1" release we did last weekend?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0-beta1

The Windows files there were built using an updated process, that (in theory) should be ok for everyone now. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.

Note - In theory, this should be fixed in [our new 3.9.0 release](https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0) anyway. :smile:
