### ISSUE TITLE
No support for multiple windows/databases open simultaneously?

### ISSUE THREAD

**Issue by fmp777** [sqlitebrowser/sqlitebrowser#557]
I found it so odd that I couldn't open simultaneous sqlite database, that I figured I better ask here before assuming thats true and continuing my search

**Comment by justinclift** [comment]
Yeah, it's a "one database per running instance" kind of application for now.  If your OS allows you to run multiple instances though, each should let you open a different database (that's the theory anyway). :smile:

**Comment by Mochnant** [comment]
I would love to see multiple window support in this fine program.  Is there a feature request area somewhere?

**Comment by justinclift** [comment]
@Mochnant This "Issues" section kind of feature request + bug report + general "Help, it's busted!"  area.

It seems like you're also interest in multiple window support too.  It's a sensible suggestion, I just don't know when we'll get around to doing it.  We have **so much** other stuff needing to get done before even thinking that one through. 🙁

**Comment by Mochnant** [comment]
Thank you for the speedy reply and I can certainly understand there is a never-ending list of things to do (and that are more important).  Unfortunately I'm running on OSX which is not as friendly about multiple copies of a program running as Windows is.

I'll put my +1 on this feature and hope for the best!  Thanks for the consideration, too.

**Comment by justinclift** [comment]
Yeah, makes sense. :smile:

If it's any help, there's a sleazy workaround :smile: for that problem on OSX.  For some applications (including ours), you can multiple instances of it if you do it manually from the command line.

For example, with DB4S installed in the standard `/Applications` folder:

```
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite &
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite &
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite &
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite &
```

Now I have four separate instances of DB4S running, each not-interfering with the other.

Btw, I'm not sure it's a good idea to try and open the same database with several instances.  I have a suspicion that could end badly.  Probably best to only open different databases, when doing this, to be on the safe side. :smile:

**Comment by chrisjlocke** [comment]
> I'm not sure it's a good idea to try and open the same database with several instances

sqlite is multi-user (the database is locked until you click **Write Changes** so yes, it'll be fine. 😄

**Comment by justinclift** [comment]
Yeah, I just get nervous when I read section 2 of this:

&nbsp; &nbsp; https://www.sqlite.org/howtocorrupt.html

In theory we should be fine.  But I don't know how well tested that is in practise (with DB4S). :wink:

**Comment by Mochnant** [comment]
I appreciate the extra info on an OSX work around.  I'll give it a try.

**Comment by MKleusberg** [comment]
Quick update here: besides opening multiple windows at once, with the latest nightly builds you can now attach another database to the main one and browse and edit both of them using the same window. Just click File -> Attach database, select a second database file, then give it a short name, and it shows up in the UI under that name. If you're still interested in this, @fmp777 and @Mochnant, you can download the nightly build and give it a try. If not, that's no problem either. We can just close the issue then I think :smile:

**Comment by Mochnant** [comment]
Thanks, @MKleusberg!  I just took a look at nightly 3.10.99 and it appears to work well for my needs.  Thank you!

**Comment by mgrojo** [comment]
I'm reviewing enhancement requests. This seems to be addressed well with the attach functionality. Should we close it now?

**Comment by MKleusberg** [comment]
Thanks for testing, @Mochnant, after having to wait for such a long time 👍 😄 Glad it's working now!

@mgrojo Yes, I think we can close this issue then. If some problems with this change should pop up in the future, we can always reopen the issue or open a new one.

**Comment by Mochnant** [comment]
Thanks for getting the functionality added, @MKleusberg !

**Comment by MKleusberg** [comment]
You're very welcome, @Mochnant 😄

**Comment by tacomanator** [comment]
Attaching a database allows for it to be used in queries, but a shortcoming is that tables from the attached databases don't show in the database structure or browse data tabs.

**Comment by chrisjlocke** [comment]
@tacomanator - to which version are you referring?  To which operating system are you using?
We have nightlies / an alpha (or beta) release which resolves the issue you are commenting on.

**Comment by tacomanator** [comment]
@chrisjlocke I was using 3.10.1 on Mac OS 10.14.1m but based upon your comment I downloaded the beta 3.11 and see that attached tables are show in this version. Thanks!
