### ISSUE TITLE
SSE2 needed for versions >= 3.6?

### ISSUE THREAD

**Issue by lulol** [sqlitebrowser/sqlitebrowser#559]
The last version that works with non SSE2 enabled CPU AthlonXP on Windows XP SP3 is v3.5.1, which I suspect is due to newer versions compiled with the now default flags using SSE2 instructions.

Could you apply the GO386=387 flag and so that no SSE2 instructions are used and enable sqlitebrowser run on old CPUs?

**Comment by justinclift** [comment]
Interesting question.  Technically it should be possible.  But it sounds like it might negatively impact lots of people by (maybe) being much slower for some operations (unsure).

Lets ask Rene, who creates the Windows builds.

Also note, if/when we get Windows compiling instructions fully worked out - so anyone can compile it themselves - that could also add more possibilities for people on unusual hardware. Hopefully I'll get time to look into that next week. :smile:

@rp- Thoughts?

**Comment by justinclift** [comment]
Oh, as another thouht, do the nightly builds work for you at all?  They're compiled using a different approach, though I'm unsure if the compiler flags for cpu instruction set features are any different. Worth trying if you haven't yet. :smile:

**Comment by lulol** [comment]
As you suggested have tried the windows nightly sqlitebrowser Version 3.8.99 and it works fine in a non SSE2 enabled AthlonXP.

**Comment by justinclift** [comment]
Cool.  That's a good workaround for now then. :smile:

**Comment by lulol** [comment]
Since there is no warning at all that could give a clue to people with old CPUs potentially affected (AthlonXP, P3) that this issue is SSE2 related when running the program because it won't start or just crash inmediately, then in the mean time may worth adding a note to the README.md directing them to the nightly builds or to older releases. :wink:

**Comment by justinclift** [comment]
Good thinking. 😀 

Done: https://github.com/sqlitebrowser/sqlitebrowser/commit/fd0eae9c14f7f7e1213b4c4153e0c01910206e5c

**Comment by MKleusberg** [comment]
Closing this because it's really old and seems to be fixed :smile:
