### ISSUE TITLE
Auto open in windows.

### ISSUE THREAD

**Issue by idan-shimoni** [sqlitebrowser/sqlitebrowser#561]
Before last update I was able to set the application as a default application to open .sql files, and after I could not.

**Comment by justinclift** [comment]
Does this help?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

:smile:

**Comment by idan-shimoni** [comment]
I am sorry but no.

**Comment by justinclift** [comment]
No worries, it was a thought. :smile:

From here, we'll need some more info so we can try to figure things out.

* Which version of Windows are you using?
* Which version of DB4S are you using?
* Also, do you remember what the previous version number of DB4S was?
* Are you comfortable using regedit?

**Comment by mgrojo** [comment]
@idan-shimoni I hope you managed to associate the SQL files to the application.  I'll close this now due to lack of response, but feel free to reopen it if you want to add something.
