### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by adamzerner** [sqlitebrowser/sqlitebrowser#562]
<img width="830" alt="screen shot 2016-04-12 at 8 35 58 am" src="https://cloud.githubusercontent.com/assets/3144254/14465932/a55b4e30-0089-11e6-8168-a2dbe5cb2eb4.png">

When I look at this picture, I don't know what to click, what will happen, and what I should do next. I assume others are in the same boat as me. I think it'd be a good idea to give some instructions that address these questions.

**Comment by justinclift** [comment]
Hmmm, have you looked at our website? :smile:

&nbsp; &nbsp; http://sqlitebrowser.org

**Comment by adamzerner** [comment]
Oh, whoops, I didn't see it on the right side. Thanks!

**Comment by justinclift** [comment]
No worries at all. :wink:
