### ISSUE TITLE
Will not open database if on mapped drive

### ISSUE THREAD

**Issue by hrvoje-grabusic** [sqlitebrowser/sqlitebrowser#563]
![image](https://cloud.githubusercontent.com/assets/1836077/14490835/81b75284-0175-11e6-8a1e-484bf18dc264.png)

**Comment by justinclift** [comment]
Oh, that's not good.  Which version of DB4S are you using, and which version of Windows? :smile:

**Comment by hrvoje-grabusic** [comment]
Windows 8.1 Pro build 9600

DB4S
Version 3.8.0
Qt Version 5.5.1
SQLite Version 3.9.2

**Comment by hrvoje-grabusic** [comment]
windows is 64 bit

**Comment by justinclift** [comment]
Thanks.  Hopefully one of the guys will have time to look at this in the nearish future.  It's very unlikely to be this week though. 😦

**Comment by chrisjlocke** [comment]
Not helpful, but I don't get this issue, and happily open files on mapped drives.
I've had this before in other applications, depending on how the drive is mapped.  Or permissions.
Can you access the server in DB Browser via the UNC, eg, \\server\share ?

**Comment by hrvoje-grabusic** [comment]
The problem went away somehow and i am not sure what did it.

I have set DB4S to open SQLite files by default and when i double click on the database it opens and now that i try even with file > open it works.

It is as if making it the default program it got more permissions.

Yes i can/could open the share when it was not working.

We were setting up new computers recently and they would get this same error window just by trying to open that share before we added them to the proper group.

**Comment by justinclift** [comment]
Weird, sounds like something strange in the windows layer more than a DB4S specific problem.  Are we ok to close this issue, unless it crops up again?

**Comment by hrvoje-grabusic** [comment]
It works for me now so if no one else has this problem must be my windows acting up.
Sure close the issue.

**Comment by justinclift** [comment]
Thanks @hrvoje-grabusic. :smile:
