### ISSUE TITLE
crash when trying to browse DB tables ("last >= first")

### ISSUE THREAD

**Issue by zetok** [sqlitebrowser/sqlitebrowser#565]
When I'm trying to look at particular table in DB, sqlitebrowser crashes.

OS: Gentoo Linux x86_64
sqlitebrowser: 3.8.0
Qt: 5.5.1

Reproducible: Always

Steps to reproduce:
1. Open `rm.db`
2. Switch to `Browse data` tab
3. Try to browse `faux_offline_pending` table
4. crash

Additional info:
backtrace: https://gist.github.com/zetok/3220f559f4af03525098e61200d8a15c
DB: [rm.db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/218244/rm.zip)

```
galaxor sqlitebrowser[428]: ASSERT: "last >= first" in file itemmodels/qabstractitemmodel.cpp, line 2599
galaxor slim[2173]: /bin/bash: line 1:   542 Aborted                 (core dumped) sqlitebrowser
```
```
CFLAGS="-O2 -march=native -ggdb -pipe -fstack-protector-strong"
CXXFLAGS="${CFLAGS}"
```

**Comment by justinclift** [comment]
Awesome, thanks for the high quality hug report. :smile:

**Comment by chrisjlocke** [comment]
Everyone loves hugs! ;)

**Comment by justinclift** [comment]
Oops.  Thanks Chris, fixed it. 😀

**Comment by MKleusberg** [comment]
Hmm, this is very strange. I've tried reproducing this using the file you've attached but wasn't able to. I have even checked out the code used for building version 3.8 and I'm using Qt 5.5.1, too. So I'm groping about in the dark here.
But your backtrace might be pointing to what could be the problem. Though obviously I need your help here, @zetok. Can you checkout the latest code from master, built it and try again opening that table? With any luck it should work now :smiley:

**Comment by zetok** [comment]
After applying 730a272454cdca4846629642e500f383487e54fd on top of 3.8.0 crash is fixed, thanks :)

As for reproducibility - when one has whole system compiled with `-fstack-protector-strong` it helps find things like that :P

**Comment by MKleusberg** [comment]
Cool :smiley: Thanks a lot for the quick reply and the detailed bug report :+1: Some day I'll probably install Gentoo, at least on my notebook :grinning:
