### ISSUE TITLE
Updating 32-bit installation with 64-bit doesn't update HKEY path

### ISSUE THREAD

**Issue by BenjaminKrebs** [sqlitebrowser/sqlitebrowser#576]
Updating from version 3.7.0 32-bit to 3.8.0 64-bit does not update the file handler registry in: 
HKEY_CURRENT_USER/Software/Classes/Applications/sqlitebrowser.exe/shell/open/command

The path after update was still 'C:/Program Files (x86)/..' and should be 'C:/Program Files/..'

This breaks the "Open with" dialog such that it ignores your choice.

**Comment by justinclift** [comment]
Thanks for pointing this out. :smile:

We have a wiki page with a fix for a windows file associations problem.  It's the same one isn't it?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

**Comment by BenjaminKrebs** [comment]
It's exactly the same issue :)

**Comment by justinclift** [comment]
@MKleusberg Is this something we should take care of automatically at startup time?

**Comment by NickDaly** [comment]
It should be taken care of during install-time.

This is essentially a limited scope version of #332, asking to always open the most recently installed version of SQLite.

**Comment by justinclift** [comment]
Yeah, it's a known problem and we have some ideas how to solve it. :smile:

But, it won't be done before the next release (3.10.0). 😦

**Comment by MKleusberg** [comment]
Closing this because I believe it was solved in one of the last releases. Please just re-open this issue if I'm wrong :smile:
