### ISSUE TITLE
Single-exe distributable?

### ISSUE THREAD

**Issue by TWiStErRob** [sqlitebrowser/sqlitebrowser#578]
I'm just updating from 3.4.0 to 3.8.0 and notice that the current version has a lot of dll files and a `platforms` folder, would it be possible to build a single big exe file like before?

**Comment by justinclift** [comment]
Kind of. :wink:

The more recent release build process for Windows uses Microsoft Visual C++, and can produce both 32-bit and 64-bit output.  (useful for some stuff)

The older method uses a cross-compile approach (MXE on a Linux build host), producing a static build.

Our nightly builds for windows still use the older method, so if you grab any of those, they'll be the single-big-exe file.

Does that help? :smile:

**Comment by TWiStErRob** [comment]
Hmm, that's good to know, but it's not a full solution. It only works as long as you don't change your nightly toolchain, also it could be unstable at any time (have to be lucky to get the right nightly).

I personally would be willing to compromise x64 for a single file downloadable from the Releases page (without installer).

Note: I was really surprised when the portable app showed up as an installer...

**Comment by justinclift** [comment]
Yeah, our Windows releases situation isn't optimal.  @rp- who does the packaging for Windows hasn't really been active for anything (other than packaging) for some time.

It's fairly normal for longer running Open Source projects to have people move on over time, so it's not something too unusual. :wink:

Co-incidentally to you asking, I've been putting time into figuring out the build process on Windows today, and (after a **lot** of hair pulling frustration), managed to get it building finally [not long ago](https://github.com/sqlitebrowser/sqlitebrowser/issues/482#issuecomment-215229614).

So, if I can gain more of a clue :smile: with the Windows packaging side of things, we might be able to expand out our download options there.  No promises yet though, lets see how much of a clue I gain first. :wink:

**Comment by TWiStErRob** [comment]
Brrr, reading those errors gives me the chills... well done! I'm so used to just executing `gradlew jar` and it does everything (dependencies, compilation, packaging); all I need pre-build is a JDK on PATH :wink:. I would've thought that the situation in the OSS world have changed over the last 10 years, but it's just more different compilers to accommodate and more make-like builders. :disappointed:

You can prioritize this low (if you have prios), it's just a nice to have. I like to have my arsenal of dev tools in one folder (less dirs to add to PATH).

**Comment by chrisjlocke** [comment]
I'll close this as we do provide a 'portable' DB4S, and I can also provide a 'just-one-exe' version if needed.

**Comment by TWiStErRob** [comment]
@chrisjlocke I'm a bit confused about the "portable" version still. How is something portable if it starts with an installation wizard?

**Comment by chrisjlocke** [comment]
The portable version (https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.12.1/SQLiteDatabaseBrowserPortable_3.12.1_English.paf.exe) is just an 'extractor' of sorts.  So yes, it installs, but it's a self-containing directory - just install it / move it onto a USB stick.  It's not 'installed' per se - it won't be in the 'add/remove' programs, etc.  
Technically the .zips in the releases are the same, although DB4S does write preferences into the registry, so again, not 100% portable.  The portable version gets around this by exporting the registry entries to a file and importing them again the next time it's run.
I've used Enigma Virtual Box to wrap all that into a virtual app (a bit like Cameyo)
