### ISSUE TITLE
Cannot view binary data on BLOB columns containing image

### ISSUE THREAD

**Issue by TWiStErRob** [sqlitebrowser/sqlitebrowser#580]
Notice that the dropdown is missing when the image is recognized.

Screenshots are from today's nightly (having the JPEG plugin, see #579):
![image](https://cloud.githubusercontent.com/assets/2906988/14936787/704b756a-0ef5-11e6-8114-43b319ef97ca.png)
and latest 3.8.0 release:
![image](https://cloud.githubusercontent.com/assets/2906988/14936790/76cc3780-0ef5-11e6-85bd-dcc6201107b5.png)

Regardless of version or image format, sometimes it would be nice to check the binary data even if it's a known image. For example adding Image to that dropdown would be a nice solution.

**Comment by TWiStErRob** [comment]
This would make it easier to check header bytes without needing to export and open the file in an external editor.

**Comment by justinclift** [comment]
Ahhh, that's a really good point.  Yeah, lets do that. :smile:

**Comment by justinclift** [comment]
@TWiStErRob I'd completely forgotten about this one.  Good news though... we fixed the behaviour you're mentioning.

In the new behaviour for the Edit Cell, the drop down is always visible.  So, it's definitely always possible to view the binary data for images.

If you want to try it out, the 3.9.0-beta 1 release (last weekend) has that code in it.  The full 3.9.0 release should be this weekend too, if that's useful. :smile:

**Comment by TWiStErRob** [comment]
Cool, thanks for the updates, I'll check it out.
