### ISSUE TITLE
Filter by NULL

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#588]
Not sure if there is already a method to do this but if not, then a feature request, to be able to filter records in the browser by NULL so one can see all records that have null in the respective column(s).  Currently, I haven't figured out how to filter records that have no value, other than using a direct SQL statement.

Thanks

**Comment by justinclift** [comment]
Good point, that would be useful. :smile:

**Comment by MKleusberg** [comment]
I agree, good idea :smiley: That's why I've finally implemented it :wink: If you're still around, @tonypdmtr, are you interested in testing tomorrow's nightly build to see if it's working for you?

**Comment by tonypdmtr** [comment]
I sure am.

**Comment by MKleusberg** [comment]
Awesome :D By the way, I totally forgot to mention: you have to search for ```=NULL``` (all capital letters) for this.

**Comment by chrisjlocke** [comment]
Is this in the current nightly?  Doesn't seem to work for me...

![image](https://cloud.githubusercontent.com/assets/7872218/22584235/35ab4186-e9e9-11e6-8d74-f4b450cd6f40.png)

**Comment by MKleusberg** [comment]
It definitely should be in there. I've also just tried this again and for me it's working. Very weird. Are you sure you're using the latest nightly build?

**Comment by chrisjlocke** [comment]
Sorry, I apologise. Downloaded the last nightly, but the last nightly was yesterday's... there doesn't seem to be a nightly for this morning. Didn't look that closely at the date...

**Comment by tonypdmtr** [comment]
I tried just now with latest available download, and it does not work.

**Comment by chrisjlocke** [comment]
Unfortunately, as per my message above, the nighties are temporarily unavailable. They be broke. Hopefully normal service will be resumed shortly.

**Comment by justinclift** [comment]
Sorry for the problem with the nightlies over the last 2 days.  They get built on a box here at my house... and the internet gateway died.  Seems like a hardware problem.

Things should be ok again from tomorrow, as the gateway is getting replaced presently. (typing this message through it, but needs more testing)

**Comment by MKleusberg** [comment]
Thanks for testing! :smiley: Closing this issue then. If you should stumble upon any problem with this, feel free to re-open it anytime.

**Comment by renschler** [comment]
how about <>NULL? It doesn't seem to be working for me.
