### ISSUE TITLE
Allow to change the font in the "edit cell" editor or use an external text editor

### ISSUE THREAD

**Issue by pier4r** [sqlitebrowser/sqlitebrowser#589]
Hi everyone, just a feature request, not urgent at all: if could be possible to allow to change the font of the cell editor or to use directly an external editor (like notepad++ or notepad2-mod)

Great project and product, i keep my todo list ordered by the priority thanks to your efforts (portable version).

**Comment by justinclift** [comment]
Hmmm, which version are you using?  Isn't the font adjustable via the Preferences menu? :smile:

**Comment by pier4r** [comment]
Sorry for the delay. Version 3.8.0 . I checked the preferences and there is the font is adjustable for the sql editor or the cells in the table overview, but not in the cell editor itself.

**Comment by justinclift** [comment]
Cool, no worries at all.  We've added a few new things that can be changed in our latest source code (and available in nightly builds).  But there doesn't seem to be anything for the cell editor font.

So, that would probably be useful to add. :smile:

**Comment by mjbe** [comment]
ditto.

The 'browse data' tab displays rows in a large font. No way that I can see to reduce it, though that would be desirable.

**Comment by justinclift** [comment]
No worries.  It's probably not that hard to get this fixed too. :smile:

**Comment by justinclift** [comment]
@pier4r @mjbe Just added some code which sets the cell editor font (both text and binary modes) according to the setting in Preferences → Data Browser → Font.

Would either of you have time to check the latest nightly build (tomorrow), to verify it works from your point of view?  Download locations are on the front page of our project, if that helps. :smile:

**Comment by mjbe** [comment]
I ended up taking a different route to my unreachable goal, old chap. I'm
currently stuck in a crevice. But I shall have a look when I get a chance.;)

**Comment by justinclift** [comment]
Cool!  Good luck with the crevice. 😀

**Comment by justinclift** [comment]
Closing this, as it's almost definitely fixed.  Been using it here for a few days (on OSX) and no issues so far.

If it does turn out to not work properly for either of you for some reason after all, feel welcome to reopen this so we can investigate. :)
