### ISSUE TITLE
export csv as ascii and not CRLF

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#591]
Hi,

I really like the feature where you can export various tables in a database to a csv file as it's a quick way to get data out; however, exporting on a linux machine, the file is actually ASCII text, with CRLF line terminators.

That means the export inserts ^M at the end of the line:

```
trip_id,date,dayOfWeek,pickup_time,duration,distance,total,beginning_zip,ending_zip^M$
3b5a4966-f6ce-45e5-a659-448715344dbf,2016-04-18,monday,18:42,1036.8,3.17,6.7,89119,89109^M$
0915dd1f-86cc-440a-ae72-0f12ae0aaef1,2016-04-18,monday,19:05,816.0,3.35,6.31,89109,89109^M$
```

On anything other than windows, these ^M are annoying and difficult to deal with. Fortunately they're easily removed with a sed string. 

Can sqlitebrowser be updated to export to a strictly ASCII file?

You can observe the new line characters (^M) on linux with `cat -e file.csv`

**Comment by justinclift** [comment]
Yep, good idea. :smile:

**Comment by justinclift** [comment]
In theory, this should be fixed now.  Only tested it on OSX and Windows though. 😇 

@jungle-boogie Would you be ok to compile the latest master code, and verify the fix on Linux?

**Comment by jungle-boogie** [comment]
> @jungle-boogie Would you be ok to compile the latest master code, and verify the fix on Linux?

Wow, that was a super fast commit!

I built it successfully on my linux machine and I'll test it when I'm at home.

**Comment by justinclift** [comment]
The fix was really simple: https://github.com/sqlitebrowser/sqlitebrowser/commit/f05e3a211c393bb21686aaf41b680176e608a8ea :smile:

**Comment by jungle-boogie** [comment]
Great job, @justinclift:

```
trip_id,date,dayOfWeek,pickup_time,duration,distance,total,beginning_zip,ending_zip$
3b5a4966-f6ce-45e5-a659-448715344dbf,2016-04-18,monday,18:42,1036.8,3.17,6.7,89119,89109$
0915dd1f-86cc-440a-ae72-0f12ae0aaef1,2016-04-18,monday,19:05,816.0,3.35,6.31,89109,89109$
```

I'm happy with the results!

**Comment by justinclift** [comment]
Excellent. Thanks for verifying it and letting us know. :smile:

**Comment by justinclift** [comment]
@jungle-boogie Would you have time to try compiling and using the latest code again?

Made some changes a few days ago to the CSV export pieces, adding a newline option to the dialog, and some other minor cleanups there too.  Would be useful to have someone else cast their eye over the end result. 😀

**Comment by jungle-boogie** [comment]
Hi @justinclift,

I was watching the other thread and have recently tested the new changes. They look good and it's pretty nice you made a the other option so someone cane make it whatever separator they want.

**Comment by justinclift** [comment]
Awesome, thanks for keeping an eye on it @jungle-boogie. :smile:
