### ISSUE TITLE
Insert record fails with foreign key constraint

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#601]
I have the following schema .. when I click the add record button, I get an error that it failed with foreign key constraint - 

Why does the add record need to do a real INSERT before I have had a chance to edit the row?
(that's what the sql log is showing) ... this will never work.

``` swift
BEGIN TRANSACTION;
CREATE TABLE "words" (
    `groupid`   INTEGER NOT NULL DEFAULT 1,
    `word`  TEXT NOT NULL,
    `action`    TEXT NOT NULL,
    PRIMARY KEY(groupid,word),
    FOREIGN KEY(`groupid`) REFERENCES `groups`(`groupid`) ON DELETE CASCADE
);
CREATE TABLE "groups" (
    `groupid`   INTEGER NOT NULL,
    `name`  TEXT NOT NULL,
    `description`   TEXT,
    `enabled`   INTEGER NOT NULL DEFAULT 1,
    `canedit`   INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY(groupid)
);
COMMIT;`
```

**Comment by justinclift** [comment]
Yeah, our constraint handling definitely needs work at the moment.

It's fairly common to find busted things in it with the present release. 😦 

As a thought, we have made *some* bug fixes for this part of things, though not nearly enough (yet).

Which platform are you using?  If it helps, there's a chance the nightly builds might at least address the bug you're hitting at the moment.  Worth a try if you have the time. :smile:

**Comment by justinclift** [comment]
@innermous If you're ok with investigating some of the harder pieces, do you want to look into this?

**Comment by innermous** [comment]
@justinclift sure.

**Comment by justinclift** [comment]
Thanks.  That's one of the two main things I think we should improve for the next release.  The other one is to fix the data entry side of things, so that people can quickly enter many values into cells, by just pressing enter (or tab) to get to the next one.  It used to work, but the "Edit Cell" window thing now seems to break it.  I've been meaning to investigate it properly, but haven't yet done so. :wink:

**Comment by innermous** [comment]
@MKleusberg did you work on this issue? I barely can do anything about it, my only thoughts are to use proxy model and submit new row data to sql database as soon as new row is edited.
This issue is really nuts, it makes the work with complex constraints impossible. Maybe we can come together to solution.
And btw @justinclift there are 2 or 3 similar issues in tracker, we should probably close them, since we have this thread.

**Comment by Novo55** [comment]
I had the same problem when I clicked on new record I got the error message.

I am not an experienced coder but I thought that if the data entered into the fields were held in a buffer and the record would be written after all the fields have been entered into the buffer.  
 
any idea if a fix is imminent?

regards
Steve W
![sql_bug](https://cloud.githubusercontent.com/assets/9299894/17021986/da4e3360-4f8e-11e6-9da1-3fa7406532fd.png)

**Comment by justinclift** [comment]
@Novo55 Unfortunately... this is unlikely to be fixed for the upcoming 3.9.0 release (maybe next week).  It's very likely to be fixed for the one after that though, as it annoys us all and we're sick of this problem hanging around. :wink:

**Comment by justinclift** [comment]
@Novo55 As a possible workaround for now (after making a backup of your database, just to be safe), trying turning on the "Ignore Check Constraints" Pragma.

It's the 6th one down the list, in the "Edit Pragmas" tab of the main interface.  With that turned on, you can probably add the records you want.  After you're done, turn if off again.

Does that help? :smile:

**Comment by Novo55** [comment]
Justin,

That didn’t work but no worries Im just learning at the moment and work around it.  Keep up the good work.

regards


Steve W
steve_w@exemail.com.au

**Comment by justinclift** [comment]
Awww rats.  Well, hopefully the release after our next one has this fixed properly. :smile:

**Comment by Jeff-G** [comment]
Related to #553, and part of the fixes requested in #628.

**Comment by justinclift** [comment]
@Jeff-G As a thought, would you be ok to try **today's** nightly build?  @MKleusberg was fixing some of the constraint stuff last week, and it should be in better shape now.

Note the "**today's** build" wording though.  We added some experimental code this afternoon, which could break tonight's automatic nightly build (we're testing some things out).  There may not be a good nightly build from tomorrow onwards for a few days... :wink:

**Comment by Novo55** [comment]
No worries will give it a run later today.

thanks


Steve W
steve_w@exemail.com.au

**Comment by Novo55** [comment]
Hi Justin,

I just tried the database again and got the same error.

keep on trying :-),  I’ll give it a try in a few days.

regards


Steve W
steve_w@exemail.com.au

**Comment by justinclift** [comment]
Thanks Steve. :smile:

**Comment by RomainTT** [comment]
Has this issue been fixed ? I have the same problem.
OS : Ubuntu 14.014 x64
DBB : 3.9.99

**Comment by justinclift** [comment]
@RomainTT Which PPA did you grab that from? :smile:

Asking because the "nightly build" PPA (as per our front page instructions) should have our latest development code in it.  If you're using the other PPA ("stable release"), you'll probably need to change it over.

Does that help? :smile:

**Comment by Novo55** [comment]
Don’t think so but I haven’t tried in a while.

**Comment by z3ugma** [comment]
It looks like this isn't fixed in nightly 3.10.99, for MacOS

Version 3.10.99 (Nov 25 2017)
Qt Version 5.9.2
SQLCipher Version 3.15.2

I'm commenting to say how much I'd love a fix for this, I hate having to write an insert statement from scratch just to add a row to the table.

**Comment by justinclift** [comment]
@MKleusberg @mgrojo Do either of you have time to look at this?  It sounds like there's an edge case here being hit somehow, which is affecting DB4S's main purpose for being used. :wink:

**Comment by MKleusberg** [comment]
Sorry for taking so long with this but we have finally merged a change by @mgrojo which should fix this problem :smile: If you're still around, can you give [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) a try and see if it's working now, @mtissington, @Novo55, @RomainTT and @z3ugma?

**Comment by mtissington** [comment]
Sorry guys, It's still very much broken ... 

When I click New Record, this is attempted and fails ... 
INSERT INTO `main`.`words`(`uuid`,`word`) VALUES (11327,'');
with a CONSTRAINT error.

It seems like you are trying to guess what certain values should be and this will hardly ever work.
In the above example, first off it is trying to insert a number into uuid which is a TEXT field.
Why can't you let the default be used?

This is the DDL for the words table in the example

CREATE TABLE words (
	uuid TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-'||hex(randomblob(2))||'-'||hex(randomblob(2))||'-'||hex(randomblob(6)))),
	word TEXT NOT NULL CHECK(word <> '') COLLATE NOCASE,
	length INTEGER NOT NULL DEFAULT 0,
	trigger_uuid TEXT NOT NULL DEFAULT 'd2d37a7c-0001-44f5-8904-69d12502b86f',
	created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(uuid)
)

**Comment by mgrojo** [comment]
@mtissington Didn't the new Add Record dialog open? It should open so the user can insert manually values (or leave the defaults) when our automatic guess of values for inserting a new record fails (usually due to a constraint). If it didn't open, could you paste the version information from the About window? Just for checking if there have been some problem in the generation of the nightly.

**Comment by mgrojo** [comment]
@mtissington This is the dialog that I talked about. Giving a value to the only field that doesn't get an appropiated default value, the new record is inserted after pressing Save.

![imagen](https://user-images.githubusercontent.com/13812910/44741278-e7aaa180-aafc-11e8-8ebb-2b1671ba9655.png)

**Comment by mtissington** [comment]
I didn't get the Add New Record Dialog - and after checking the install did not upgrade or overwrite the previous install I had from May (I don't have it any more). So after checking, I found I had 2 versions installed but the latest had not really been correctly installed. I uninstalled both, ran the latest install and now I see the Add New Record dialog .... do I need to raise this as an issue with the installer?

**Comment by mgrojo** [comment]
Thanks for reporting, @mtissington. Maybe @karim, the author of the new installer, wants to know and answers your last question.

**Comment by karim** [comment]
@mtissington The new MSI installer cannot update the old NSIS (.exe) installer. Sorry about that. You have to uninstall the old one first. We will try to find a way to detect the presence of older (non-msi) version of the application.

Is it working fine now after uninstalling both and reinstalling the latest version?

**Comment by mgrojo** [comment]
Should we close this and open other issue for the installer or doesn't need one?

**Comment by mtissington** [comment]
New issue.

**Comment by wenbo23** [comment]
> @mtissington This is the dialog that I talked about. Giving a value to the only field that doesn't get an appropiated default value, the new record is inserted after pressing Save.
> 
> ![imagen](https://user-images.githubusercontent.com/13812910/44741278-e7aaa180-aafc-11e8-8ebb-2b1671ba9655.png)
i add a trigger for a table,  add to listen insert event, so i also need to pop up the dialog to input column values, then save to insert, instead of creating a new record then input and update. However, i try to the nigh build and latest build, but i can not find the button of add a new record. thank you in advance.

**Comment by mgrojo** [comment]
The button is where the pointer is located in the screenshot:
![imagen](https://github.com/user-attachments/assets/99d2ae1e-e3fe-4425-8c33-4a4b23d53716)
