### ISSUE TITLE
Add development instructions for Qt Creator

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#602]
The [`BUILDING.md`](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md) file mentions how to build this from the command line, but I would like to be able to do this from `Qt Creator`.

When using `make`, it correctly builds the app, and it looks like this on a MacBook Pro with Retina support:

<img width="1149" alt="screen shot 2016-05-22 at 13 26 44" src="https://cloud.githubusercontent.com/assets/5748627/15453498/f0860024-2020-11e6-93b2-74daadf4c06d.png">

but when I build from `Qt Creator`, it looks like this:

![screen shot 2016-05-22 at 13 27 16](https://cloud.githubusercontent.com/assets/5748627/15453506/108af35c-2021-11e6-9990-769fd9317b4c.png)

the text and icons are blurry, and also I noticed that the drag handle to the left of the `New Database` button looks different too.

I'm also not able to `Run` it, just `Build` and then manually open the `.app`, because I get this error:

```
Starting /Users/revolt/Development/GitHub/revolter/build-sqlitebrowser-Desktop_Qt_5_6_0_clang_64bit-Debug/src/sqlitebrowser.app/Contents/MacOS/sqlitebrowser...
dyld: Symbol not found: _sqlite3_intarray_bind
  Referenced from: /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
  Expected in: /usr/local/opt/sqlite/lib/libsqlite3.0.dylib
 in /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
The program has unexpectedly finished.
/Users/revolt/Development/GitHub/revolter/build-sqlitebrowser-Desktop_Qt_5_6_0_clang_64bit-Debug/src/sqlitebrowser.app/Contents/MacOS/sqlitebrowser crashed
```

Another problem is that I can't manage to build with SQLCipher support. The `.md` file says to replace `any calls to cmake and qmake`, but doesn't specify in which files. Could this be done by creating a new `Build and Run Kit`?

**Comment by justinclift** [comment]
Ahhh, that's interesting stuff.

With the SQLCipher support, I wrote up initial instructions on my fork of the wiki, but haven't transferred them to the main one as they're not finished yet.  That being said, there's enough info in them that you'll probably be able to work it out.  Look at step 7:

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/wiki/Win64-setup-—-Compiling-SQLCipher#7-compile-sqlcipher-into-db4s

With the Retina support for OSX, it sounds like it might be related to this:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/commit/f0d692547031c43b29243fd162e0e973ad55adbd

Not sure why it's not in effect for you though.  Maybe there's and #ifdef or something around that's stopping that being applied to your system? 😦

**Comment by justinclift** [comment]
@revolter Was the above helpful at all?

The error text in your comment above is indicating it's finding the SQlite3 libraries, not the SQLCipher one.  On my OSX development box I generally find I need to remove sqlite (`brew remote sqlite`) and ensure only sqlcipher (`brew install sqlcipher`) is installed.  That's the case even with `CONFIG+=sqlcipher` added to the qmake line, as per screenshot above.

In theory, it should be possible to make SQLite3 + SQLCipher co-exist on the same development machine ok.  In practise... I haven't quite figured that out yet. :wink:

Btw, I'm looking back at this stuff now that I've got my home lab setup mostly working.  Your feedback is definitely useful. :smile:

**Comment by revolter** [comment]
Sorry, I didn't have time to look into your wiki. I did manage to get it somewhat working after posting this issue.

1. One of the problems was that the `Qt Creator` project was not configured properly. Having absolute zero knowledge about it, I just "next, next, next"ed in the wizard popups. And, by default, it used a "project configuration kit" (if I recall correctly the name) using Qt 5.6. So I deleted it and somehow imported a kit from the project, which had the correct Qt 4.8.7.
I currently don't have access to `Qt Creator`, but when I do and have time, I can provide detailed steps, exact labels and buttons names or screenshots for this.
I now understood it a little better.
This also fixed the retina problem.

2. I also managed to enable SQLCipher by adding that flag in the same "project configuration kit". Same remarks as above.

3. I'm not able to directly run the project though.

I installed `Qt Creator` using `.dm`, not `brew`, if it helps. I did install `sqlcipher` using `brew` though.

> I need to remove sqlite (brew remote sqlite)

Did you mean `remove` instead of `remote`?
Also, wouldn't that break OS X stuff?

**Comment by justinclift** [comment]
Yeah, I'm using Qt Creator 4.0.0, manually downloaded from the Qt website, with SQLite/SQLCipher installed through Homebrew too.

Not 100% sure, but I don't think Homebrew has a formula for Qt Creator.  It's completely possible I'm wrong though. :wink:

With the Qt version, I far I've been finding that if I have qt installed through Homebrew, it seems to confuse Qt Creator (gets the wrong one) and generally fails.  So I've been using the version of Qt5 that comes with Qt Creator instead.  Pretty sure that would be fixable too, with some adjustment of paths and stuff.

Btw, yeah, the `remote` vs `remove` was a typo.  Fixed now, thanks. :smile:

For breaking OSX stuff... it depends.  It won't break OSX itself, but if you have other Homebrew formulas installed using it, they'll barf until it's put back.

For me that's workable, as I don't really need anything else installed while doing dev stuff.  That may not be typical though.

**Comment by revolter** [comment]
> Not 100% sure, but I don't think Homebrew has a formula for Qt Creator.

Oh, I think I said something stupid, I don't think `Qt Creator` is available on `brew`.
I think I meant `qt` alone. Is it only available on `brew`? I can't recall this, sorry for the confusion.

> For me that's workable
I think it's the same case for me too, but it would be nice if it worked without this removal... if it's possible, of course. But for now, I think we can make sure to mention these in the docs:

> For SQLCipher support, you need to remove sqlite (`brew remove sqlite`) and ensure only sqlcipher (`brew install sqlcipher`) is installed.
> Remember that, by removing sqlite, if you have other Homebrew formulas installed using it, they'll barf until it's put back. You can put it back using `brew ...` (here, I don't know the undo-ing command)

Or something like this.

**Comment by revolter** [comment]
I am now receiving this error after removing sqlite:

```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
The program has unexpectedly finished.
```

Does [this](https://github.com/Homebrew/legacy-homebrew/issues/34302) help you to help me solve the problem :D I don't understand much.

**Comment by justinclift** [comment]
Heh Heh Heh, unfortunately nope. :wink:

The error you're getting there is shown by the third line in that:

```
  Expected in: /usr/local/lib/libJPEG.dylib
```
Notice the path for that is /usr/local/lib/ [stuff]  ?

It looks like something is trying to run, and depends on a Homebrew installed version of libJPEG.

Guessing you removed more than just SQLite? :smile:

**Comment by revolter** [comment]
Well, I didn't remove anything else on purpose. But it seems I do have that file:

    lrwxr-xr-x    1 revolt  admin    35B Mar 26 17:26 libjpeg.dylib@ -> ../Cellar/jpeg/8d/lib/libjpeg.dylib

**Comment by revolter** [comment]
I found this possible solution:

> `sudo ln -sf /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib /opt/local/lib/libjpeg.dylib`
> 
> Why does this work? Because for whatever reason, when Apple requests libJPEG.dyld, whatever system searches for it finds /opt/local/lib/libjpeg.dyld because the search is case insensitive. For a Unix operating system. Go figure. The lines above will force any program looking for libjpeg.dyld to be redirected to Apple's libJPEG.dyld.
> 
> But wait, what if you WANT Macport's libjpeg.dyld? Sorry, not possible unless you statically link your program to libjpeg.a. And since I've never done that before, I can't help you if you want to do that :(

Do you think it's ok?

**Comment by justinclift** [comment]
Interesting. What does your `brew list` output show?

Btw, I'm kind of wondering if just recompiling jpeg ('brew remove jpeg --force; brew install jpeg`) would do the trick to fix that error. :smile:

**Comment by justinclift** [comment]
Btw, what's the program you're trying to run that's failing?  It's not henplus is it?

**Comment by revolter** [comment]
I managed to get it (finally) working by actually running all the command from [here](https://lists.macosforge.org/pipermail/macports-users/2010-November/022663.html), not only the jpeg one, but replaced `/opt/local/lib/lib*.dylib` with `/usr/local/lib/lib*.dylib`

This is my `brew list`:

```
/opt/local/lib ❯ brew list
autoconf	chisel		fontconfig	gmp		libpng		libusb		mackup		openssl		recode		unar
automake	cmake		freetype	highlight	libtasn1	libusb-compat	makedepend	pkg-config	rename		unrar
boost		colordiff	gd		jasper		libtiff		lua		neovim		qt		sqlcipher	xz
cask		emacs		gettext		jpeg		libtool		lynx		nettle		readline	tree		youtube-dl
```

And, what do you mean by what program?! It's sqlitebrowser, of course 😆

**Comment by justinclift** [comment]
Ahhhhh.  Wasn't sure from the context. :smile:

**Comment by justinclift** [comment]
I have a tendency to wipe my brew's out prior to getting into dev stuff, then just installing the one's I need for that.  After doing dev stuff, I run the brew install line to install them all again.

My list is a bunch shorter than yours though, so that may not be feasible for you. 😇

**Comment by revolter** [comment]
`brew remove jpeg --force; brew install jpeg` didn't work :(

**Comment by justinclift** [comment]
😦 

The `otool` command looks like it would be interesting, and help if you hit problems like this again:

```
$ otool -L src/sqlitebrowser.app/Contents/MacOS/sqlitebrowser 
src/sqlitebrowser.app/Contents/MacOS/sqlitebrowser:
	/tmp/sqlcipher/lib/libsqlcipher.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	@rpath/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtMacExtras.framework/Versions/5/QtMacExtras (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.6.0, current version 5.6.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

In theory that should show every library which the target executable needs (the sqlitebrowser executable in the above line.)  If something missing, it should explicitly show it.

**Comment by revolter** [comment]
I don't think it was a problem of missing library. A symlink for `libJPEG.dylib` existed, but it pointed to a different file, which probably didn't have the `__cg_jpeg_resync_to_restart` symbol.

Here is my `otool -L` output:

```
sqlitebrowser.app/Contents/MacOS/sqlitebrowser:
	/usr/local/opt/sqlcipher/lib/libsqlcipher.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/opt/qt/lib/QtNetwork.framework/Versions/4/QtNetwork (compatibility version 4.8.0, current version 4.8.7)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 915.0.0)
```

Why doesn't it show the `libJPEG.dylib`?! I don't understand.

**Comment by justinclift** [comment]
Yeah, I'm not sure.  I'm not clueful enough with otool yet to know.

It *might* be one of the libraries in the list from otool was relying on it (Qt?), and a version mismatch happened for some reason.  Wild shot-in-the-dark guess though. 😦

**Comment by revolter** [comment]
Yeah, that makes sense though.

So, to make it clearer, I currently have the Apples `dylib`s symlinked in `usr/local/lib` and it's working (and I'm working to on a PR 😄). I can directly run sqlitebrowser from `Qt Creator` with the debugger attached. So it's all good now. I'll continue like this and see if this overwrite is causing problem somewhere else.

**Comment by justinclift** [comment]
Hmmm, this is interesting in a non-good way:

```
otool -L src/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite 
src/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite:
	/usr/local/opt/sqlcipher/lib/libsqlcipher.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	@rpath/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtMacExtras.framework/Versions/5/QtMacExtras (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.6.0, current version 5.6.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

That's from a brand new compile of DB4S, with updated source (note the new executable name).

This is the same thing, but with sqlcipher uninstalled (`brew remove sqlcipher`) after compiling:

```
otool -L src/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite 
src/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite:
	/usr/local/opt/sqlcipher/lib/libsqlcipher.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	@rpath/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtMacExtras.framework/Versions/5/QtMacExtras (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.6.0, current version 5.6.0)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.6.0, current version 5.6.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

It's not showing up big warning for missing libraries after all.  Definitely need to investigate this more.

**Comment by revolter** [comment]
From the `master` branch? I forked and cloned the project a couple of days ago, should I have the new executable name too? I have `sqlitebrowser.app` and `sqlitebrowser` inside of it.

**Comment by justinclift** [comment]
There have been a few changes on the master branch in the last few days.

Um... maybe take a note of the latest commit you have for you master, so you can reset back to it if the latest code upsets your now-its-finally-working setup? :smile:

**Comment by revolter** [comment]
Nice name for the setup 😂.

It doesn't upset me. But I remember stumbling upon `DB Browser for SQLite.app` myself while in the trial and error period. And I'm wondering why isn't the project building with this new name too. I do want to have the latest commits.

Oh, I am 45 commits behind 😐. Need to search again on SO how to sync a fork 😂.

**Comment by justinclift** [comment]
I normally do:

    $ git checkout master
    $ git pull

**Comment by revolter** [comment]
Ooooh, I know what happened, I forked the project from the browser, but I already had a fork, so it just redirected to it, and I happily cloned it locally.

I don't think that works for a fork. I usually go over and over to [this answer](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by justinclift** [comment]
Ahhh yeah, that looks good too. :smile:

**Comment by revolter** [comment]
Stumbled upon this again 😂

I had to run:

```
brew unlink libjpeg libpng libtiff
ln -s /System/Library/Frameworks/ApplicationServices.framework/Versions/Current/Frameworks/ImageIO.framework/Versions/Current/Resources/libJPEG.dylib libjpeg.dylib
ln -s /System/Library/Frameworks/ApplicationServices.framework/Versions/Current/Frameworks/ImageIO.framework/Versions/Current/Resources/libPng.dylib libpng.dylib
ln -s /System/Library/Frameworks/ApplicationServices.framework/Versions/Current/Frameworks/ImageIO.framework/Versions/Current/Resources/libTIFF.dylib libtiff.dylib
```

but I still feel that this is not the correct approach.

It might work with an env var or something.

**Comment by revolter** [comment]
Found the answer. You have to uncheck the `Add build library search path to DYLD_LIBRARY_PATH and DYLD_FRAMEWORK_PATH` in the `Run` heading of the `Projects` tab:

![qtcreator](https://user-images.githubusercontent.com/5748627/40748162-2a8f4e50-6468-11e8-8de9-17a005557fe6.jpg)

**Comment by justinclift** [comment]
Excellent.  Thanks for updating the wiki with the info too @revolter. :smile:

**Comment by revolter** [comment]
How did you find out I updated the wiki?

**Comment by chrisjlocke** [comment]
He knows all...

**Comment by justinclift** [comment]
Heh Heh Heh.  The front page of the wiki has a "Wiki History" link at the bottom of the page:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/_history

It's useful for seeing what's changed recently. :smile:
