### ISSUE TITLE
Use C++11 / Drop Qt4

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#603]
I'm opening this issue to discuss two ideas regarding the technologies we want to use and/or support. The two ideas are totally independent, so let's try not to confuse them :wink: 

## 1) Start using C++11 (or C++14 or C++17)
There are some nice to have features in the newer versions of C++. Most of them we will probably never use, especially since we're relying very much on Qt, but still there are plenty of helpful additions to the language. This could make our code cleaner and more efficient.
The downside is the compiler support. While pretty much every compiler should support C++11 to a large extend *by now* there are still many old compiler versions out there which will have trouble with certain C++11 features. Furthermore, most compilers require the user to explicitly activate C++11 support. This makes the project files and the build processes slightly more complicated.
Questions:
* How about the nightly builds for Windows? What compiler version does mxe use? Let's not break the nightlies and let's not put too much work on Rene here.
* How about building on WIndows? I have no idea how well C++11 is supported on MSVC nor how to activate it.
* What documentation would we have to update?
* Any other processes relying on the current way it's building? If so, can we break them?

## 2) Drop Qt4 support
Qt4 is no longer maintained and it doesn't make sense to support it forever. At the moment we're limiting ourselves to the features supported by both, Qt4 and Qt5. Again, there's nothing major we're unable to do because of this but it would make the code a bit cleaner to be able to assume there's only Qt5 to support. I also see a chance of making the documentation and debugging a bit easiert by dropping Qt4 support because we can just make clear that we don't support it (and thus don't need to document it) and assume that each issue reported comes from a version compiled with Qt5 (since it won't compile with Qt4 anymore).
Problem: As far as I know, the Windows nightlies are using Qt4. If we dropped Qt4 support Rene would have to update the build process.
Also, I remember some issue or two where people would have problems with the Qt5 builds but got better results with the Qt4 builds. Does anybody remember these issues? Some font/display thing probably?
Questions:
* Does anybody else use Qt4?
* Which version of Qt5 do we want to be the minimum requirement? Qt 5.0 doesn't make a lot of sense I think, but the latest version doesn't make much sense either.

So what do you all think? :smile: 
I'm pro C++11 and pro dropping Qt4 but definitely don't want to rush this.

**Comment by justinclift** [comment]
For 1), I have no opinion as I don't grok the difference yet. :wink:

As a way to see what breaks, we might want to add a stub C++11 feature to master for one night to see if MXE still creates the build or not.  If it does, then great.  If not, well we have our answer for that bit :smile: and can just revert it.

For the nightly windows builds, it's probably a decent idea for us to set up a new nightly builder using MXE.  I set up an initial CentOS 6 VM in Rackspace about a week ago for testing other stuff on, though I haven't yet looked to see whether MXE works there.  Rackspace supports a bunch of different OS's though, including Arch 2015.7 (just checked), so if someone wants to get it building there via cronjob that's completely workable.  I'm not familiar with Arch though, and don't really feel like getting back into Linux if I can help it right atm. :wink:

**Comment by justinclift** [comment]
For 2), things broke when creating the OSX packages using Qt5 for um.. the 3.8.0 release I think.

By "broke" I mean that they seemed to work fine for me, but the .app created was just crashing for some people.  No idea why, as there didn't seem to be anything clearly in common with the reports (apart from OSX, multiple versions).

I don't have enough clue with debugging OSX crashes yet to chase down why.  If this problem can be resolved, it would help. :)

Note - I kind of suspect it might be something to do with OpenSSL.  Maybe the builds were relying on system OpenSSL instead of Homebrew one?  I'm unsure, and don't remember.

As an additional point, at least OS/2 doesn't have Qt5 available.  Or didn't when support for that was added a few releases ago.  It's a pretty minor platform in usage though, so I'm not sure we should keep with Qt4 just for that. 😇

**Comment by justinclift** [comment]
@innermous @glawrence What are your thoughts on this? :smile:

**Comment by glawrence** [comment]
My personal view is we should move to the latest Qt as soon as possible and that this should be the priority as this can deliver real benefit to end users. Then I see no reason why we shouldn't move the latest C++ standard, providing Qt is compatible as well as all our build processes. Although in many ways I would rather see the builds fixed but we need to consider how best to use people's time and skills.

**Comment by rp-** [comment]
mxe uses gcc 4.9.3, which should support most if not all c++11 features, so shouldn't be a problem here.

but qt5 is a different story, last time I updated mxe i tried to use qt5, but I just couldn't do a static build, either they removed support for it or I made something wrong. but I'm afraid that a switch to qt5 whould require more work for nightlies.

**Comment by innermous** [comment]
> I have no idea how well C++11 is supported on MSVC nor how to activate it.
It's even simpler on MSVC, it comes out-of-box.
There's really no need to rush this, but lots of boilerplate code could be optimized. What about Qt4 - it  just stinks as 11 year old stuff. It's just outdated, lots of stuff had been fixed and added/removed over this time. Upstream developers do it for a reason.

**Comment by justinclift** [comment]
To drop Qt4, we need to figure out a solution for the static build problem (MXE), and the OSX problem.

Those two seem to be the only things really stopping us for Qt5.

For doing Qt5 things in a separate branch... ugh.  That sounds like a not-great idea to me.  It would be too easy to only implement features in Qt5 branch, ignoring the Qt4 one.

We would be better off doing stuff with Qt4, and then update to Qt5 once the migration problem are solved.  That one there is only one active development branch. :smile:

**Comment by glawrence** [comment]
I've just been reading https://wiki.qt.io/New_Features_in_Qt_5.7 as Qt 5.7 is coming soon, the point to note is the first item "C++11 Support Required from the compiler". So even if we don't switch to Qt5 on all platforms straight away, C++11 is the right path to be going down.

**Comment by innermous** [comment]
@glawrence I already mentioned it :smile:

**Comment by glawrence** [comment]
Sorry @innermous you did, I forgot that

**Comment by justinclift** [comment]
One new hiccup with Qt5.  Unlike Qt4, the Qt5 version of `macdeployqt` (a utility it ships with) doesn't work properly. 😦 

Using `macdeployqt [name of .app]` is **supposed** to correctly determine the shared libraries needed by the .app, then bundle them into the .app package for deployment.

With Qt4, it "just works".  With Qt5, it fails to work correctly, even when claiming success.  Leading to things like this when users try to run it:
![screen shot 2016-08-14 at 17 13 37](https://cloud.githubusercontent.com/assets/406299/17650348/32cd0306-6243-11e6-9fe6-e9887f659d38.png)

I'll try to solve this for the main 3.9.0 release next weekend.

**Comment by justinclift** [comment]
As an interesting data point... In quick testing on my desktop when I build DB4S using the "official download" version of Qt 5.7.0 - the one through their online installer - rather than using the latest Homebrew one (5.6.0), then `macdeployqt` didn't screw up the dependencies.

I'll try this on the build server proper shortly.  Hopefully the fix really is that simple. :smile:

**Comment by justinclift** [comment]
Yay, that worked. :smile:

Going to add the Qt5 build to our 3.9.0-beta1 release page... and see if people start reporting crashes.  Hopefully not. :smile:

**Comment by MKleusberg** [comment]
Not really up to date here... but if this build turns out to work, are there any reasons left to *not* drop Qt4 support?

**Comment by justinclift** [comment]
As far as I know... this was the last really concrete thing holding us back. :smile:

We could be ok to say "right, we're Qt5 only from now on!" in just a few weeks. 👯

**Comment by justinclift** [comment]
Ahhh... the Windows nightly builds may need investigation too.

**Comment by justinclift** [comment]
We'll need to figure out Travis CI too.  It's using Qt4 at present.

It may be as simple as changing the `libqt4-dev` here to `libqt5-dev`:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/.travis.yml#L9

Travis automatically builds on any branch in the repo, so we can experiment in a temporary "qt5test" branch to figure this out.  When we know exactly what's needed, we can commit that specific change to master. :smile:

@revolter Any interest in getting this done?

**Comment by MKleusberg** [comment]
When building with cmake Qt4 is still the default, you have to enable Qt5 for building using the ```-DUSE_QT5=1``` option. The only exception is building on Windows using MSVC where Qt5 is the default. So this would need to be adjusted for Travis, too (besides the libqt4-dev).

I could change the build files to use Qt5 as default. But this would break the nightlies.

**Comment by justinclift** [comment]
Oops.  Obviously hadn't read the rest of the Travis config properly. :wink:

**Comment by revolter** [comment]
@justinclift, I guess I can't understand this properly to fix it.

**Comment by justinclift** [comment]
No worries.  I can guide you through it on the Gitter channel if you're interested?

**Comment by justinclift** [comment]
@MKleusberg Qt5's new approach to image handling - using plugins - seems like it will stop static builds from being very useful:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/issues/579

We'll definitely need to look at automating MSVC to create the nightly builds instead.

**Comment by justinclift** [comment]
These might be useful.  They're the MSVC2013 reference pages about its C++11 support:

* https://msdn.microsoft.com/en-us/library/hh409293(v=vs.120).aspx
* https://msdn.microsoft.com/en-us/library/hh567368(v=vs.120).aspx
* https://blogs.msdn.microsoft.com/vcblog/2013/06/28/c1114-stl-features-fixes-and-breaking-changes-in-vs-2013/

These are for MSVC2015, which I've not tried building DB4S with yet:

* https://msdn.microsoft.com/en-us/library/hh409293.aspx
* https://msdn.microsoft.com/en-us/library/bb531344.aspx

**Comment by justinclift** [comment]
Updated our OSX nightly build script today.  It's now building with Qt5 (and signing the .app's), so that's one less thing to take care of. :smile:

**Comment by justinclift** [comment]
There's a problem with Qt5 not showing all data records, on at least OSX: https://github.com/sqlitebrowser/sqlitebrowser/issues/737#issuecomment-241616641

It happens for both SQLCipher and non-SQLCipher builds.  When dropping back to Qt4, the issue goes away.

Haven't tried on Window yet, to see if it's just an OSX-only thing.

**Comment by MKleusberg** [comment]
I think I'll do a quick test and push a commit which introduces some C++11 code just to see if and where it's failing :smiley:

**Comment by justinclift** [comment]
Just noticed something interesting while looking into #786.

CentOS doesn't include Qt5 in any of it's repositories.  It *can* be manually compiled though.

This will need to be thought through... 😦

**Comment by justinclift** [comment]
@revolter pointed out a [this page for deploying Qt5 applications on Windows](http://doc.qt.io/qt-5/windows-deployment.html).  Specifically, it seems to cover Qt5 plugins in some depth.

**Comment by MKleusberg** [comment]
Just got rid of all the Qt4 stuff in our codebase :D I guess Vlad can start celebrating now :champagne: :tada: 

@justinclift One more thing to do :wink: Can you maybe have a look at that Wiki page (https://github.com/sqlitebrowser/sqlitebrowser/wiki/Notes-for-setting-up-your-build-environment-on-OSX)? It looks outdated to me, especially now, but I'm unsure if it still contains some useful information.

**Comment by justinclift** [comment]
Thanks, good thinking.  Just updated that page with we're-Qt5-only-now info. :smile:
