### ISSUE TITLE
Third option in Quote character field of ExportCSV dialog isn't restored properly

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#610]
Noticed another weird bug in the Export CSV dialog, while investigating a different one (#605).

The new weird bug is that the 3rd option for the Quote separator character is never selected correctly in the widget.  It may be something to do with string matching on the character, due to the way the compare in the function is run.

Need to look into it properly after a decent amount of sleep though. :smile:

**Comment by jungle-boogie** [comment]
Nice work with your c++! You're on the pathway to make sqlitebrowser is more superior.

**Comment by justinclift** [comment]
Thanks.  Yeah, I didn't know there were so many bugs in some of these areas.  Fixing now... :smile:

**Comment by justinclift** [comment]
As a data point, I'm finding I need to adjust the code in this file just so it's easier to trace/debug through.

eg: https://github.com/justinclift/sqlitebrowser/commit/203c51759f809215ce66387eb1c475777b88a62d

Not sure if there's a better way.
