### ISSUE TITLE
Primary keys are not quoted when creating/modifying table

### ISSUE THREAD

**Issue by bontibon** [sqlitebrowser/sqlitebrowser#613]
sqlitebrowser: 3.8.0

1. Create new database
2. Create table with name "test"
3. Add a field named "index"
4. Check "PK" (Primary key)
5. Click OK.

Error message:

```
Error creating table. Message from database engine:
near "index": syntax error (CREATE TABLE `test` (
	`index`	INTEGER,
	PRIMARY KEY(index)
);)
```

**Comment by justinclift** [comment]
Ugh, I knew our constraint handling is buggy and needs improvement, but this seems pretty bad.

Just tested it here on the very latest source code, and it's busted there too. 😦 

Thanks for pointing it out @bontibon. :smile:

**Comment by MKleusberg** [comment]
Thanks for reporting this! It should be fixed in tomorrow's nightly build. Can you test that (see the main page of our repo for download links) and report back if it's working for you now? :smiley:

**Comment by bontibon** [comment]
It's fixed! Thanks!
