### ISSUE TITLE
Feature request: foreign key combobox

### ISSUE THREAD

**Issue by vtronko** [sqlitebrowser/sqlitebrowser#614]
We could use  dropdown combobox for foreign key cells to make edition even more comfortable.
Example here:
![combobox](https://cloud.githubusercontent.com/assets/8950786/15634933/f85d2b5c-25d8-11e6-8a8e-3cc3cf74dc60.png) 
Cell editor should provide suggestions based on available set of values.

**Comment by justinclift** [comment]
This looks like a good idea.  From my point of view it would be welcome. :smile:

**Comment by innermous** [comment]
Problem is, I don't have idea how to get rid of ambiguity. How do we know, which text to display? In heidi it works so natural and implicitly.

**Comment by justinclift** [comment]
heidi ?

**Comment by justinclift** [comment]
The source for Heidi is available, so maybe take a look through that to get an idea of one useful approach? It may be you think of a better way, after seeing the way they do it. :smile:

**Comment by mgrojo** [comment]
@vtronko Are you still around? We've finally manage to implement this feature after so much time. Would you like to try it and comment any issue you might encounter? It will be available in tomorrow's [nightly build](https://nightlies.sqlitebrowser.org/latest/).

**Comment by silviulaurentiu** [comment]
So, the drop down list is ok:
![image](https://user-images.githubusercontent.com/14875058/50026139-7ed62f00-fff0-11e8-9252-1d83440a7131.png)
But when I selected a value, an error occurs:
![image](https://user-images.githubusercontent.com/14875058/50026197-afb66400-fff0-11e8-8f18-25c01d9545c3.png)

**Comment by mgrojo** [comment]
@silviulaurentiu Thanks for reporting!
