### ISSUE TITLE
Default button on 'Delete field' is 'Yes'

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#616]
When deleting a field from a table, the default button in the popup dialog is 'Yes' rather than 'No', which is the usual convention for dialog boxes that have consequences.

![image](https://cloud.githubusercontent.com/assets/7872218/15848978/ebb8ce0a-2c87-11e6-9b29-5dd433784113.png)

**Comment by justinclift** [comment]
@chrisjlocke The fix for this, made by @innermous, has just been added.

Would you have time tomorrow to try the (new) latest nightly build, to confirm it from your point of view? :smile:

**Comment by chrisjlocke** [comment]
Thanks for the prompt fix.  Was only a cosmetic issue mainly, but nice that
it now follows convention! ;)
Will test tomorrow and report back.  Thanks again.

**Comment by jungle-boogie** [comment]
On the sqlitebrowser from the 9th of June, I'm not prompted _at all_ when I delete a record. I'll download the latest (even though the code may be the same) and see if there's any change.

**Comment by chrisjlocke** [comment]
If you delete a row you're not prompted, as I presume if you think 'Oops', you can click 'Revert Changes'.

I can confirm though that deleting a field now displays a dialog box with 'No' as default.
