### ISSUE TITLE
Unhanded exception: Access Violation 

### ISSUE THREAD

**Issue by trueb87** [sqlitebrowser/sqlitebrowser#619]
When opening a .db file and clicking browse the form populates with data but quickly throws the following exception:

> Unhanded exception at 0x0000000064E61120 (Qt5Core.dll) in sqlitebrowser.exe: 0xC0000005: Access violation reading location 0x000000000045BD10.

Not a whole lot of information to go on as of now as I am unable to provide the offending file (Confidential Material).

![2016-06-08 08_11_57-sqlitebrowser debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/13841039/15895424/d8994c86-2d50-11e6-8221-143ef20cef23.png)

**Comment by justinclift** [comment]
If you have some time to investigate on your end, make a copy of the database for yourself, then try emptying it of all the data (just leaving the tables).  If that no longer causes the crash, then it means there's something in the data triggering it.

If that's the case, then you'd be able to figure out the data-causing-the-problem by selectively removing stuff until only that is left. (again, using a copy of the original one)

Does that make sense? :smile:

**Comment by jungle-boogie** [comment]
This doesn't happen to me in the sqlitebrowser from this morning (9 june, 2016).
Try making a database, write it, close browser and open it up and see what happens.

**Comment by trueb87** [comment]
I did not get back to this issue until today, I have been unable to reproduce this failure even with the original file. Perhaps Mars has to be in the right place in the sky? I will continue to use this application and try to get it to reproduce.

**Comment by justinclift** [comment]
No worries at all.  We'll close this issue for the moment, but if you do get it to reproduce please open it up again. :smile:
