### ISSUE TITLE
Too many margin

### ISSUE THREAD

**Issue by dridk** [sqlitebrowser/sqlitebrowser#620]
I suggest to remove some margin arround the treeview. It's not clear actually and it looks like 90's app. 
I did it for my Qt apps, and it looks better : http://dridk.github.io/cuterest/

**Comment by justinclift** [comment]
Hmmm, looking at your screenshot... not seeing what you mean?

**Comment by dridk** [comment]
I mean layout margin as you can see here : 
![gc1](https://cloud.githubusercontent.com/assets/1911063/15984490/788f6440-2fcd-11e6-8ade-35fde4750bab.png)

**Comment by dridk** [comment]
![gc1](https://cloud.githubusercontent.com/assets/1911063/15984507/fd0ec99a-2fcd-11e6-889e-c980cbd2409f.png)
In Red, margin to remove. Tree view should fill all the content

**Comment by justinclift** [comment]
Adding this 3.10.0 milestone, as it wouldn't hurt for us to at least investigate the possibility. :smile:

**Comment by MKleusberg** [comment]
Just pushed a commit that reduces the margin in there. There's more we could do to make this look better but I'm not sure we should. One reason is that this would mean the Database Structure tab would start looking different from the rest of the application. Another reason is that Qt does all sorts of things to make applications appear in different ways on different platforms and I'm not sure how much we want to interfere with that.

That being said, what does everyone think of the reduced margin? :smiley:

**Comment by justinclift** [comment]
Well, the reduced margin looks weird to me because it's not how other applications look.

But, to me it's super minor and I'll get used to it. :smile:

**Comment by justinclift** [comment]
@dridk Do you have a few minutes to try out a recent nightly build, and let us know if the reduced margin is now how you were meaning? :smile:

**Comment by chrisjlocke** [comment]
> this would mean the Database Structure tab would start looking different from the rest of the application.

The other areas are now looking 'different' to the database structure tab.  So the docked SQL Log, DB Schema, etc, now have the extra margin.  

Personally, I prefer 'some' margin.

So this is how it is currently (latest nightly)

![image](https://cloud.githubusercontent.com/assets/7872218/24762914/bb4fa64a-1ae7-11e7-9199-03ca0c1fd808.png)

In my opinion, this would look odd:

![image](https://cloud.githubusercontent.com/assets/7872218/24763026/0cb12cac-1ae8-11e7-83c1-2298254f938d.png)

(with no right margin)
But it looks better with no left margin...  although now you've got a big gap in the middle between the two tab controls.

**Comment by justinclift** [comment]
Hmmm, yeah not sure.  On OSX with the latest source, the margins still seem to be there:
![screen shot 2017-04-06 at 17 28 03](https://cloud.githubusercontent.com/assets/406299/24765093/6dd68d32-1aee-11e7-943c-05b90f134e68.png)

**Comment by justinclift** [comment]
Do we still need to do something for this issue?  I'm kind of thinking "no". :smile:

**Comment by chrisjlocke** [comment]
As above in my comment, some areas look slightly better if you remove one side of the margin, but weird on others.  Its something we can look at later... when we do a full UI revamp maybe!
I vote to close for now, but at least place on the back burner (or at least near a small candle.....)

**Comment by justinclift** [comment]
Meh, let's close it.  We have enough other things to get done anyway. :smile:
