### ISSUE TITLE
Security issue - Unquoted command during Windows install

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#621]
A minor security issue has been reported via Twitter:

&nbsp; &nbsp; https://twitter.com/Ug_0Security/status/740569774548213760

![ckcisjgwkaa3ici](https://cloud.githubusercontent.com/assets/406299/15933265/fcf4f326-2e56-11e6-927f-4573202958a4.jpg)

**Comment by justinclift** [comment]
Just created a new "security" label. :wink:

@innermous Is this something you'd be ok looking into?

**Comment by innermous** [comment]
@justinclift not a windows user, unfortunately. I don't know about proper windows packaging, sorry.

**Comment by justinclift** [comment]
Not a problem, wasn't sure. :wink:

I'll try to look into it this weekend. :smile:

**Comment by justinclift** [comment]
As a data point, the reporter has asked if we can give public credit for this somehow when it's fixed.

We don't have a blog, so unless we start one, that could be difficult.

As an alternative thought, we're due to release version 3.9.0 in the near future, which this bug should be fixed in.  Maybe that's the correct place to give public credit in this case?

**Comment by glawrence** [comment]
This should be a simple case or adding " around the path used to launch the vc_redist executables and any other executables the installer launches.

**Comment by justinclift** [comment]
@glawrence Cool.  Want to give it a shot? :smile:

**Comment by DelphiGit** [comment]
@justinclift I have made a commit with a fix to this issue in my master fork. Before I turn it into a pull request I have a question: I previously made a test commit with my ignore-file, but I assume you will be able to pick just the last commit I made, or will everything always be pulled?

**Comment by justinclift** [comment]
@DelphiGit The most optimal solution is to chuck your changes into a separate branch.

eg from the command line:

```
$ git checkout -b some_new_branch_for_issue621
$ git add foo bar baz
$ git commit
```

"Branches" are used to keep groups of related commits together, so things are neat.  Then, when someone clones your repo they can switch to a given branch with one command and only have the commits in it.

So... make a new branch for it. :smile:

**Comment by DelphiGit** [comment]
Thanks for your advice @justinclift. I think I succeeded. Otherwise, please let me know. :smile:

**Comment by justinclift** [comment]
Yep, you succeeded, that looks good. :smile:

**Comment by justinclift** [comment]
So, for this issue to be fully fixed, we need the NSIS guys to update their codebase such that the generated uninstallers don't have the problem.  Once that's done, new/future packages should be created with that, and we should be good. :smile:

**Comment by justinclift** [comment]
As part of a discussion with the original reporter via email, and Amir Szekely (@kichik) from NSIS, Amir pointed out it seems like CMake is the one at fault in this instance.  CPack (part of CMake) generates the script with NSIS uses.  The template for that script isn't properly quoting things.  eg:

* https://github.com/Kitware/CMake/blob/master/Modules/NSIS.template.in#L916
* https://github.com/Kitware/CMake/blob/master/Modules/NSIS.template.in#L655

There may be other occurrences too.

The original reporter is in process of contacting Kitware, the main sponsors for CMake.

Will add further relevant info here as comes to light. :smile:

**Comment by justinclift** [comment]
After experimenting with a few things, adding quotes to the first part of the ExecWait line pointed out by Amir fixed the issue:

&nbsp; &nbsp; https://github.com/justinclift/CMake/commit/af65a04f690e1d6e6e2d3aa3467116689ab12b4f

Hopefully Kitware gets a new release out soon.  If not, we can just used a manually patched version of the template file in CMake when making our next release.

**Comment by justinclift** [comment]
This is being addressed on the CMake developers mailing list:

&nbsp; &nbsp; http://public.kitware.com/pipermail/cmake-developers/2016-July/029039.html

**Comment by justinclift** [comment]
@DelphiGit You up for doing more stuff? :smile:

**Comment by justinclift** [comment]
CMake 3.6.1 has been released, which includes the fix for the unquoted path problem for the 2nd half of the problem (during uninstall):

&nbsp; &nbsp; https://blog.kitware.com/cmake-3-6-1-available-for-download/

This issue can probably be closed now. :smile:

**Comment by glawrence** [comment]
That's great news, assuming the place where we do builds for releasing has CMake 3.6.1.....

**Comment by justinclift** [comment]
@glawrence Good point.  I'm going to attempt doing the builds for 3.9.0, just to make sure we have the capability whenever needed. :smile:
