### ISSUE TITLE
Data 'validation' for field entry

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#622]
This isn't a bug per-se, but more of a 'what do you think?' question . suggestion.

If I create a table with a field set as an integer, DB Browser (or sqlitebrowser) doesn't moan if I try and create a new record and put 'test' in that new field - ie, a string (or text) in an integer field.

This isn't a fault with DB Browser, as you can do it in the raw SQL, so my thought was whether it would be useful if DB Browser had some 'validity' checks...  guess it would only need to be for the interger and real data types (oh, and numeric) so can't see it bloating the program too much...

Just some random thoughts...

**Comment by justinclift** [comment]
It's a reasonable suggestion, but it's not something we'll implement.

SQLite itself considers the flexibility of the datatypes to be a feature, and we'd be opening a weird can of worms if we didn't follow with the official position with it. :smile:

&nbsp; &nbsp; https://www.sqlite.org/datatype3.html

**Comment by chrisjlocke** [comment]
No problem.  Thanks for replying.
