### ISSUE TITLE
Browser column resizing does not work correctly when a new record is pending

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#627]
If you try to resize any column after having pressed 'Add Record' but before completion the addition, then no matter which column you try to resize, all columns are resized in the exact same way losing the original widths for all columns.

**Comment by justinclift** [comment]
Thanks @tonypdmtr, that's an interesting catch. :smile:

**Comment by schdub** [comment]
@justinclift this behavior works as expected in accordance with #241.

**Comment by justinclift** [comment]
@schdub They seem like different things.  #241 seems to be about selecting several columns, then resizing all of the selected ones.

This issue seems to be about trying to resize a single column, but all columns are resized instead.

Am I reading it wrong? :smile:

**Comment by schdub** [comment]
@justinclift after adding new record new row is selecting MainWindow::addRecord(), 568 (I don't know why, since 2013-04-07)
if we continue to change width of single column, it will actually change the width of all columns, because new row is selected (every column in row is selected).

**Comment by justinclift** [comment]
Ahhhh.  Yeah, I'm not sure of the best behaviour here.  @tonypdmtr ?

**Comment by tonypdmtr** [comment]
I see the problem now.  I guess it's a non-issue then other than it's not obvious to the user why this is happening.

So, if the whole row is automatically selected when pressing 'New Record', it could also appear as selected (all highlighted -- instead of just the row number) just as if one selected the row manually by clicking on the row number.  This would at least make it obvious that the whole row is selected at that moment, and it would have a consistent look between manual and automatic row selection.

**Comment by MKleusberg** [comment]
Isn't that the case already? When I click Add Record the entire row is selected and highlighted just like when clicking the row number manually.
Another idea would be to only select the first column of the newly added row. This way the auto resizing won't happen. It would also make more sense for putting data into the row: when all columns are selected I can't just start typing and Tab-bing through the columns. The only downside of only selecting the first column that I can think of is that the new row is slightly less visible then. What do you think?

**Comment by tonypdmtr** [comment]
In latest build I just tried, only the row number is highlighted when pressing "Add Record".  The entire row is highlighted only after starting the column resizing, which is too late as you have already messed up all other rows from their previous size.

**Comment by tonypdmtr** [comment]
Seems to be working OK in latest download.  It seems to cancel the edit in order to do the resize.  Maybe, it should be closed?

**Comment by justinclift** [comment]
Thanks heaps @tonypdmtr, we're a bit overloaded with open issues so this definitely helps. :smile:
