### ISSUE TITLE
How to force export function use backtick (`) in create table syntax?

### ISSUE THREAD

**Issue by lvbeck** [sqlitebrowser/sqlitebrowser#629]
Hi,

I need export my SQLite database to sql file with MySQL compatibility, hence I want to use always backtick (`) for CREATE TABLE syntax. For example:

```
CREATE TABLE `Table1` (`ID` INTEGER,`Name` TEXT);
```

however, in the exported sql, the create statement contains backtick (`) as well as double quote (") and single quote (') , which seems to be a random behavior.

for example I have a table with schema:

```
CREATE TABLE `Source` (`Source_ID` INTEGER, `Name_Source` TEXT);
```

if I export this table, it become to: 

```
CREATE TABLE "Source" (`Source_ID`  INTEGER, `Name_Source` TEXT)
```

or

```
CREATE TABLE 'Source' ('Source_ID' INTEGER, 'Name_Source' TEXT);
```

And it's also unpredictable in the CREATE INDEX statements:
in this case I want no quote around the columns like:

```
CREATE INDEX Source_Source_ID ON Source (Source_ID);
```

but the exported sql is:  

```
CREATE INDEX 'Source_Source_ID' ON 'Source' ('Source_ID' );
```

So when I import the sql to MYSQL database, I got syntax errors

**Comment by justinclift** [comment]
Interesting.  This shouldn't be too hard to implement. :smile:

**Comment by lvbeck** [comment]
@justinclift it would be great to have user defined quote character for export

**Comment by MKleusberg** [comment]
This should really be fixed I think :smiley: @lvbeck Can you test the latest version (3.9.1 or the nightly builds, whatever you prefer)? I'm pretty sure we quote all names using the ``` ` ``` quotes.

**Comment by MKleusberg** [comment]
Oh no I'm sorry, I was wrong. For the SQL dump we take the CREATE statement as is. This means it's quoted in the SQL export just like it's quoted in the original database. But I can fix that :smiley:

**Comment by MKleusberg** [comment]
@lvbeck Sorry for the confusion :smiley: If you're still interested in this, can you test tomorrow's nightly build and see if it's improving the situation for you? For triggers and views we don't have a chance to do this (yet) but tables and indices should be much better now.

**Comment by lvbeck** [comment]
@MKleusberg it would be great if you can implement this feature(tables and indices are enough for me), however I am not able to test the nightly build this week, I will check later ASAP, thank you.

**Comment by MKleusberg** [comment]
No worries :smiley: Just test it whenever you have the time for it. Thank you for your effort! :smiley:

**Comment by justinclift** [comment]
@lvbeck ping?

**Comment by lvbeck** [comment]
@justinclift @MKleusberg thanks, it's now working! I will close the issue

**Comment by justinclift** [comment]
@lvbeck Excellent, thanks for checking and letting us know. :smile:

**Comment by lvbeck** [comment]
@MKleusberg just another tiny feature request, could you please add:
DROP TABLE IF EXISTS `Tablename`;
before CREATE TABLE syntax? 
This would be very helpful if the table existed in database. Thank you!

**Comment by MKleusberg** [comment]
@lvbeck Sure, no problem :smiley: I've added an additional option to the Export SQL dialog to enable this feature. So you'll need to set it up like this:
![spectacle lh5631](https://cloud.githubusercontent.com/assets/3153504/26000659/1275dc4c-372a-11e7-83a8-9c47cfb35cef.png)
Can you download the next nightly build (tomorrow) and check if it's working for you as expected?

**Comment by lvbeck** [comment]
@MKleusberg I tested nightly build "DB Browser for SQLite-2017-05-15-win64.exe", it work exactly as expected, thank you for the amazing work!

**Comment by justinclift** [comment]
Awesome. :smile:
