### ISSUE TITLE
'Undo' in SQL window doesn't always work as expected

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#630]
I suspect this is more to do with the qt controls than DB4S, but thought I'd mention it anyway.  I'm using the nightly, so the qt is 4.8.7 - this is lower than than 'release' (5.4.1).  However, the bug is apparent in both.

OK, so in the SQL window, type your phrase:
![image](https://cloud.githubusercontent.com/assets/7872218/16301030/f3227438-393a-11e6-80de-22aa527ad6d9.png)

Ooops.  No, not tables.  Change that to 'blobby'
![image](https://cloud.githubusercontent.com/assets/7872218/16301056/21ae3292-393b-11e6-9b06-7b4b0d7a60fd.png)

And now press Enter to slap things on a new line
![image](https://cloud.githubusercontent.com/assets/7872218/16301069/3893cf8a-393b-11e6-85ca-d6518045023d.png)

If you press CTRL Z to undo, 'lobby' disappears.
![image](https://cloud.githubusercontent.com/assets/7872218/16301089/500d3426-393b-11e6-892d-fff0f7595a04.png)

This is an example to replicate this, but variants of this occur if you press CTRL Z legitimately when performing SQL statements - especially when pressing Enter or changing words. 

This is on Win 10 (64bit).  Havenn't tried other OS's.

**Comment by jungle-boogie** [comment]
I would say this is not a bug based on the same behavior in notepad++ version 6.5.3 on windows 8.1.

**Comment by chrisjlocke** [comment]
Seems 'unexpected' though.  Aah well - can live with it.
