### ISSUE TITLE
Filters raw isn't mirrored in RTL layout

### ISSUE THREAD

**Issue by SafaAlfulaij** [sqlitebrowser/sqlitebrowser#631]
The filters raw where you can search in the coloumn for a specifc string isn't mirrored in RTL layouts.
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16335207/1a6d97ec-3a0e-11e6-83bd-9c198be7ac54.png)

**Comment by justinclift** [comment]
Ahhh, interesting.  Thanks for reporting it. :smile:

**Comment by innermous** [comment]
I am not familiar with RTL in Qt apps. Could you tell, please, how can I toggle it? Maybe then I could provide some solution to this issue.

**Comment by SafaAlfulaij** [comment]
@innermous In Qt5, pass "--reverse" to the app, so it's "sqlitebrowser --reverse"

**Comment by innermous** [comment]
Well, the issue is caused [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/FilterTableHeader.cpp#L73)
My suggestion is to check the app is opened in RTL mode via
```cpp
bool reverse = isRightToLeft();
```
And do some changes in adjusting algorithm for that case. I tried to do some, but they have some glitches on resizing.

**Comment by justinclift** [comment]
@SafaAlfulaij Ahhh, that's useful info.

@chrisjlocke That `--reverse` switch might be useful for you in testing the Arabic translation as you go through getting it fixed. :smile:

**Comment by justinclift** [comment]
@innermous Any idea if there's a difference between Qt4 and Qt5 for the resizing glitches?

If they don't happen when we build with Qt5, that would be another reason to move towards it. :smile:

**Comment by innermous** [comment]
@justinclift don't know what are you talking about, honestly.
The problem causing this issue is that drawing method is hardcoded, and the code inside it is strictly left-to-right.
I tried to make workaround, it worked well, but when you try to resize it becomes a little messy.

**Comment by justinclift** [comment]
@innermous Sorry.  Was typing on a tablet before without really understanding. :smile:

Was thinking the "glitches on resizing" thing might have been Qt4/Qt5 related.  Guess not. :smile:

Looking at the code you point out, I see what you mean about the hard coded order and needing to do a workaround.  Would you be ok to throw that code into a branch so we can take a look and maybe figure out how to keep it ok when resizing?
