### ISSUE TITLE
Not able to restore window after minimize on Mac OS-X El Capitan

### ISSUE THREAD

**Issue by rvaneerd** [sqlitebrowser/sqlitebrowser#632]
Hi,

When I'm working with SQLiteBrowser and I need some additional screen resources, I occasionally minimize the SQLiteBrowser window.
However, when I then need to access SQLiteBrowser, I cannot get the window restored.
I need to Quit the application and then re-open it.

I'm running OS-X El Capitan and I retrieved the following information from SQLiteBrowser:
Version 3.8.0
Qt Version 4.8.7
SQLite Version 3.9.2

Is there something I'm doing wrong?
Is there anything I can do to change this behavior?

Please help as this is a little annoying.

Regards,
Rob.

**Comment by justinclift** [comment]
That's weird, I just tried it here (using latest nightly build), and it's working for me.  To minimise the application, what are you doing?  Clicking the orange icon in the top left of the window bar? (that's what I just tried)

For me, that minimises the running application down into the Dock.  To restore it, I click it in the Dock... which returns it to it's previous position.

Guessing you've tried that, but asking just in case. :smile:

**Comment by rvaneerd** [comment]
Just tried it myself as well.
Minimizing using the orange button on top left indeed.
Clicking on the icon in the Dock doesn't do anything.
When I do "RightClick / Show all Windows" it pops up. Although this works, this is not the default on my system.
When I minimize the Safari window I'm now using to write this answer, I just need to click it once from the Dock to have it restored.

**Comment by justinclift** [comment]
k.  Marking it as a bug, but I'm not sure when someone will get to it.  Personally, I have no idea what could be causing that (yet). :wink:

If you have the time to try it, grab the latest nightly build (download locations are listed on our front page), and give that a shot.  It has lots of bug fixes for various things, and there's a (small) chance this is fixed in it.

**Comment by chrisjlocke** [comment]
When I write programs for Windows using VB, if a program is minimised and restored, you not only have to make the window 'normal' again (from minimised) but also have to change the Z order - it might be why the window is restored but behind other windows?  I've never programmed for a Mac so unsure what I'm on about....  in VB you have to 'activate' the required application to bring it back to the front.

**Comment by ghellquist** [comment]
No problems on Sierra (10.12.2) using build 3.9.1v2.
I suggest this issue can be closed.

**Comment by justinclift** [comment]
@rvaneerd Would you have time to try out the new v3.9.1v2 binary for OSX, to see if this is fixed for you?

* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.1/DB.Browser.for.SQLite-3.9.1v2.dmg

**Comment by rvaneerd** [comment]
@justinclift Thanks for the update!
Just downloaded / installed this version and it is properly behaving like other apps!
You seem to have fixed the issue!

Thanks!!!!!!

Regards,
Rob.

**Comment by justinclift** [comment]
Awesome. :smile:

Thanks too @ghellquist!
