### ISSUE TITLE
Edit Database Cell Window position bug

### ISSUE THREAD

**Issue by GHProjects** [sqlitebrowser/sqlitebrowser#633]
Hi,

In windows 10, every time I double click a database cell the window opens in the left upper corner of the screen. If I press Esc and try again it opens in a "normal position", at the middle of the screen.

The position of the window alternates between these two. 
Its pretty inconvenient each time it appears on the left upper corner since the upper and left side of it are off the screen, not allowing dragging nor resizing or closing the window (with the pointer).

I'm running SQLite Browser 3.8.0.

Thanks!

**Comment by justinclift** [comment]
As a thought, it might be worth trying the latest nightly build.  There are a tonne of bug fixes in that, and there's a chance this is already fixed.

On the other hand... I don't remember any window positioning bugs being worked on yet... so... the chance might not be huge. :wink:

**Comment by jungle-boogie** [comment]
Hi @GHProjects and @justinclift,

This isn't specific to windows 10. I'm on Windows 8.1 and have the same behavior. This is also present on the latest nightly build.

I don't know the behavior on Linux, but I'll bring it up and see what happens.

**Comment by Mihail87** [comment]
The same issue on Windows 7 :(

**Comment by DelphiGit** [comment]
I'm glad this is brought up. I've mentioned it in a previous report (#413).

Since the position of the main form is stored when the application is closed, my suggestion is a new setting in Preferences to also store the position of the Edit-window.

Because of this bug I'm still using a build from August 19th 2015 but I'd like to update, cause I like to be up to date. :)

**Comment by jungle-boogie** [comment]
This happens on linux. Can someone please confirm? Then will @GHProjects please change the subject to be more accurate if someone else confirms the same behavior on linux?

**Comment by jungle-boogie** [comment]
> Because of this bug I'm still using a build from August 19th 2015

That's pretty silly. There's been many other bugs fixed since and sqlite has moved on as well.

**Comment by GHProjects** [comment]
@jungle-boogie I created the topic but I don't have the permission to do that. Ask @justinclift ;)

**Comment by jungle-boogie** [comment]
@GHProjects, why would you not have the permission to rename a thread you started?

**Comment by DelphiGit** [comment]
I don't know Qt or c++ very well (I'm a Delphi Pascal guy) but I took a quick look around the source code and I imagine something like this would work:

On show (or initialization) of edit dialog
restoreGeometry(PreferencesDialog::getSettingsValue("EditDialog", "geometry").toByteArray());
restoreState(PreferencesDialog::getSettingsValue("EditDialog", "windowState").toByteArray());

On close of edit dialog
PreferencesDialog::setSettingsValue("EditDialog", "geometry", saveGeometry());
PreferencesDialog::setSettingsValue("EditDialog", "windowState", saveState());

This is taken from "MainWindow.cpp" and I just altered a part of the lines to say "EditDialog" instead. I'm not sure the setting for "windowState" is necessary to save and restore though. Can someone more knowledgable please say that it might work or that I'm totally wrong. :-)
I'm willing to try a nightly build with this (or correction of this) code to help testing.

**Comment by justinclift** [comment]
Just tweaked the topic title, to remove the "Windows 10" bit on the end.  Hope that's right.

Note - I'm focused on a personal project (last few weeks, and probably a few more) so not keeping all that close an eye on things here.  I will get back to this stuff though. :wink:

**Comment by justinclift** [comment]
Gah, wrong button. 😇

**Comment by justinclift** [comment]
@DelphiGit Hmmm, any interest in building it yourself?  We have a detailed [Windows build guide](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S) (best done in a VM) if you're interested.

**Comment by DelphiGit** [comment]
Thanks @justinclift I'll take a look at the guide and see if I can set up a working build environment during the weekend.

**Comment by DelphiGit** [comment]
I've been experimenting a little.
Altering the event below works for me on Windows to keep the dialog opening centered over the main window. But I have no idea about other platforms, multiple monitor setups and other possible special cases.
```cpp
void EditDialog::showEvent(QShowEvent*)
{
    // Whenever the dialog is shown, position it at the center of the parent dialog
    QMainWindow* parentDialog = qobject_cast<QMainWindow*>(parent());
    if(parentDialog)
    {
        move(parentDialog->x() + parentDialog->width() / 2 - width() / 2,
            parentDialog->y() + parentDialog->height() / 2 - height() / 2);
    }
}
```

**Comment by justinclift** [comment]
Interesting.  If you commit that code into a branch in your own fork, that would let others compile it pretty easily.  @jungle-boogie may be ok to try it on Linux, and I can also generate a once off OSX build for people to test, if that sounds useful. :smile:

**Comment by jungle-boogie** [comment]
I will try this out soon!

**Comment by justinclift** [comment]
@DelphiGit Sorry for the delay, didn't notice your fork & commit.

Here's a build of it for OSX:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-201607111858-issue633.dmg

Built that on my desktop though, instead of our official buildbox, so it **might** segfault for people using older OSX than 10.9.5 though (unsure).  Can rebuild on it our official buildbox later, if it does turn out to be a problem. :smile:

**Comment by jungle-boogie** [comment]
This works great for me on Linux. the edit cell box stays centered each time on all cells.

**Comment by DelphiGit** [comment]
I've had the opportunity to try my Windows build on a computer with two monitors, and I'm happy to say it works great there too. :smile: 

For information, the current official build has problems there which can cause the dialog to appear on wrong monitor,

**Comment by justinclift** [comment]
Sounds like a win all around then. 😄 

@DelphiGit Want to make this into a Pull Request, so we can merge it?

**Comment by DelphiGit** [comment]
A pull request has been made. :smile:

**Comment by justinclift** [comment]
Thanks @DelphiGit, that's awesome. 😀 

Any interest in tackling other things too?

**Comment by DelphiGit** [comment]
You're welcome @justinclift.
Tackling other things.... sure, do you have more dialogs that needs to be centered? :wink: But seriously, do you have anything particular in mind? I'm still new to Visual Studio, C++, Qt, yeah basically everything in your brilliant Windows Build Guide. :smile:

**Comment by justinclift** [comment]
@DelphiGit Actually thinking this one: https://github.com/sqlitebrowser/sqlitebrowser/issues/621

Unless you want a C++/Qt one, to gain experience with that side of things?

**Comment by DelphiGit** [comment]
@justinclift  If I can find the piece of code that performs the launch I should be able to fix the security issue. Right now I don't know where to start looking, so any hints are welcome. :smile:

**Comment by justinclift** [comment]
Sure. :smile:

The NSIS packaging part, kicked off by the `PACKAGE` solution in MSVC has its bits scripted [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt#L354-L386).

Looking at the screenshot from #621, the unquoted line is probably this one [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt#L378).

Hopefully it's as simple a fix as it sounds, but sometimes in practise the simple ones turn out to be hairier than thought. :wink:

One way to find out... 😁

**Comment by jungle-boogie** [comment]
Confirmed this works great on windows 8.1. The edit database cell displays in the same spot all the time.
Thanks a lot for the patch, @DelphiGit!
