### ISSUE TITLE
Does not open password protected SQLite db created with Navicat!!!

### ISSUE THREAD

**Issue by venetasoft** [sqlitebrowser/sqlitebrowser#634]
Does not open password protected SQLite db created with Navicat!!!

**Comment by justinclift** [comment]
Interesting.  We use SQLCipher for the encryption.  Is that what Navicat uses? (there are a few different SQL encryption options around)

**Comment by justinclift** [comment]
@venetasoft ping?

**Comment by justinclift** [comment]
Closing this due to lack of response from @venetasoft. 😦
