### ISSUE TITLE
Arch Linux Version Crash

### ISSUE THREAD

**Issue by uguraba** [sqlitebrowser/sqlitebrowser#636]
Hi, I'm using sqlitebrowser for arch linux. I installed from yaourt. While i try to use, the application is crashing and without any error message, it will close.

**Comment by justinclift** [comment]
Ahhh.  One useful way to see error messages is if you start it from the command line.

When it crashes, there should be output there.  Hopefully something useful.

Ok to try that and let us know what it says? :smile:

**Comment by justinclift** [comment]
@uguraba ping?

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
