### ISSUE TITLE
Foreign Keys not accepted, version 3.5.1 on Slackware-14.1

### ISSUE THREAD

**Issue by rs-aesi** [sqlitebrowser/sqlitebrowser#638]
Tried creating a relational database with 3 tables; one parent and 2 children. Went to the Edit pragmas tab and clicked on the Foreign key checkbox. As soon as I return to the Database structure tab that pragma was turned off. Cannot create the db within the application.

Same problem occurs trying to import the db schema from a .sql file; the foreign keys are not recognized or accepted.

Wish there was documentation for this application.

Rich

**Comment by justinclift** [comment]
Hey Rich,

Sorry for the troubles.  Our foreign key handing (and constraints in general) needs a lot of work.  So, it's completely possible that you're doing things fine... and the application is just not where it needs to be.

As a thought though, we have made a few bug fixes and general tweaks to things over the last few versions.  There's a reasonable chance (but no guarantee 😦  sorry) that the bug you're hitting has been fixed by our more recent versions.

As you're on Linux, it should be pretty simple to compile things from our latest source code, if that's something you're ok trying.  We have a build guide with general instructions for Linux, if that helps:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

Is that something you're ok to try out? :smile:

**Comment by rs-aesi** [comment]
On Fri, 8 Jul 2016, Justin Clift wrote:

> Sorry for the troubles. Our foreign key handing (and constraints in
> general) needs a lot of work. So, it's completely possible that you're
> doing things fine... and the application is just not where it needs to be.

Justin,

   That's certainly understandable. I know that docs are often a much lower
priority than coding, but something on the wiki about what works and what
doesn't work would be helpful to folks like me.

> As a thought though, we have made a few bug fixes and general tweaks to
> things over the last few versions. There's a reasonable chance (but no
> guarantee 😦 sorry) that the bug you're hitting has been fixed by our more
> recent versions.

   Yesterday I tried building -3.8.0 (I use the SlackBuilds.org scripts for
most of my additional software), but it apparently requires a newer version
of QScintilla than that distributed with Slackware-14.1. However, -14.2 was
released a week ago and may have a QScintilla version that works. When my
DVD arrives I'll upgrade all the hosts and try again.

   Unfortunately, foreign key support is a critical need for all my
applications; that's why I use a RDBMS.

Thanks for your reply and explanation,

Rich

**Comment by justinclift** [comment]
No worries.  When you go to compile it again, try grabbing our latest source code ("master branch") from GitHub.

We're way overdue for a new release, and there have been a good number of bug fixes since 3.8.0. :wink:

**Comment by rs-aesi** [comment]
On Fri, 8 Jul 2016, Justin Clift wrote:

> When you go to compile it again, try grabbing our latest source code
> ("master branch") from GitHub.

Justin,

   Slackware's going to start mailing out the DVDs with 14.2 by the end of
the month (I guess they're all in production now). So it'll be August when I
upgrade and will try the latest build of sqlitebrowser then.

Rich

**Comment by justinclift** [comment]
Sure, no rush here. :smile:

**Comment by mgrojo** [comment]
@rs-aesi I think this issue is already solved. We have made also various improvements with table with foreign keys. Do you mind getting a [nightly build](https://nightlies.sqlitebrowser.org/latest/) or compiling from the master branch for confirming it?

**Comment by rs-aesi** [comment]
On Sat, 1 Sep 2018, Manuel wrote:

> @rs-aesi I think this issue is already solved. We have made also various
> improvements with table with foreign keys. Do you mind getting a [nightly
> build](https://nightlies.sqlitebrowser.org/latest/) or compiling from the
> master branch for confirming it?

Manuel,

   This issue is long out of date. Please close it.

Regards,

Rich

**Comment by justinclift** [comment]
No worries.  Thanks for getting back to us @rs-aesi. :smile:
