### ISSUE TITLE
Toggling Show rowid column clears only the filter input

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#640]
If you filter any column then toggle the Show rowid column, all the filter text fields are cleared but the data stays the same.

It should reload the table, or better yer, not clear (or reapply, depending on the implementation) the text fields.

**Comment by innermous** [comment]
I don't get it. 
```showRowidColumn(bool show)```
function seems not good in means of good interfaces. It overdoes what's stated in it's title, it not only toggles rowid column, but also regenerates all other filters aswell. Which, well, causes lots of mess, when one tries to make changes to it!
I'll try to make things to make their own job (i.e. showRowidColumn just toggles column, that's all!) and make a PR for discussion. But believe me, current code is **not** cool.

**Comment by justinclift** [comment]
@innermous Is this related to #645 ?

**Comment by SafaAlfulaij** [comment]
That's because of: https://github.com/sqlitebrowser/sqlitebrowser/blob/b773e77a0c17317c9096728876e2b3c0f29be559/src/MainWindow.cpp#L2487
which leads to deleting all the current fillter inputs: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/FilterTableHeader.cpp#L30

**Comment by justinclift** [comment]
Ahh.  PR 2 coming up? 😁

**Comment by revolter** [comment]
@justinclift, Not quite. As I understood, the refresh problem was just an UI issue. When minimizing and restoring the window, the column showed correctly.

**Comment by sky5walk** [comment]
🐛 bump...
I just ran into this tonight on the latest. Debugging a query and wanted to see my rowid's but my filter was cleared visually but not actually.

**Comment by chrisjlocke** [comment]
Showing the rowId column now does not clear any filters or amend the data already filtered.
Seems to work OK for me...

**Comment by MKleusberg** [comment]
Awesome. Thanks for testing this, @chrisjlocke :smile:
