### ISSUE TITLE
Some strings in the main UI are not showing their translation

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#643]
Some strings in the main UI aren't showing their translation.  eg:
![screen shot 2016-07-11 at 19 36 49](https://cloud.githubusercontent.com/assets/406299/16742251/d5da519e-479e-11e6-84fe-c7e10b28b334.png)
Apparently this happens for languages other than Arabic (eg [French](https://github.com/sqlitebrowser/sqlitebrowser/pull/642#issuecomment-231838973)), which makes it sound like a problem in our code.  Hopefully it's just a setting or something needing to be applied to the strings in the .ui file or similar.

**Comment by innermous** [comment]
Translation files are one huge mess, lines specified in .ts files are outdated and do not match lines in .ui files.
Even those translation strings that are displayed correctly atm - have wrong line numbers in .ts files. This requires a thorough work :)

**Comment by chrisjlocke** [comment]
I only know .NET programming, which is why I haven't gotten involved with programming/helping out before, but editing translation files sounds work I could be doing... matching up the lines and ensuring they're still valid?  I'm good at the laborious stuff, leaving others time to do the exciting bits!

**Comment by justinclift** [comment]
@chrisjlocke Any help with this would definitely be useful. 😀

**Comment by justinclift** [comment]
With this particular issue, I kind of wondered if maybe the punctuation symbols in some strings were doing weird things for the translations.

After a bit of investigation, it does seem like this is at least part of the problem.

For the French language example, here is what the UI looks like before investigating the punctuation symbols:
![screen shot 2016-07-12 at 13 43 01](https://cloud.githubusercontent.com/assets/406299/16767703/a5ff30bc-4838-11e6-9a2f-32948c28d570.png)
Picking one of the strings that hasn't translated - "Revert Changes" - doing a grep for it through the src/ subdirectory shows it in [MainWindow.ui](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.ui#L1371):

```
<string>&amp;Revert Changes</string>
```

In the [French translation file](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/translations/sqlb_fr.ts#L1071) though, it's missing the `&amp;` at the start:

```
<source>Revert Changes</source>
```

After adding the `&amp;` string to the translation file here, then rebuilding the project, that string now translates correctly in the main interface:
![screen shot 2016-07-12 at 13 53 56](https://cloud.githubusercontent.com/assets/406299/16767725/ac18b338-4838-11e6-98a3-54863e008b03.png)
So, it looks like string matching problems between the .ui files and the translation files for at least some of this.

@chrisjlocke Is going through the translations files and getting these adjusted to string match correctly something you'd be up for in the next few days? :smile:

**Comment by justinclift** [comment]
As a data point, this doesn't look to be too complicated.  Just went through the French UI and fixed the main strings for the initial UI.  I'll commit the change to our repo in a minute too:
![screen shot 2016-07-12 at 14 08 20](https://cloud.githubusercontent.com/assets/406299/16768033/564465b8-483a-11e6-9ef3-3aa5af62970d.png)

**Comment by chrisjlocke** [comment]
I'll set up a VM following your examples / instructions to create a Windows development area and have a go... going through the files sounds doable, but 'rebuilding the project' is something I've not done before... but I like a challenge!*

*If supplied with enough beer and sweets.

**Comment by justinclift** [comment]
Heh Heh Heh

The setup for the Win dev environment is kind of tedious.  Lots of downloading at the start to collect things, then lots of launching installers, picking the options (as given :smile:), then waiting for installers to finish.  The only challenge for that bit is patience. :wink:

Once you have that though, you're all set.  The instructions take you through building the project, so you'll find "rebuilding" the project itself super simple.

If you hit stumbling things, reach out. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Had a chance to look at this?

We'll probably do our next release next week, so this needs to be completed (+ verified) by then. :smile:

**Comment by chrisjlocke** [comment]
I'll set up a virtual machine this morning and follow your instructions. :)

**Comment by justinclift** [comment]
Excellent, that will really help. :smile:

**Comment by chrisjlocke** [comment]
Yes, in the "Requirements" section, you need to add "4 days put aside to
install all this gumph"...  ;)

**Comment by justinclift** [comment]
Yeah, that's the tedious bit. 😬

**Comment by chrisjlocke** [comment]
Quick 'confirmation'.  I can't find details of 'DB Schema' in the translation files for the tabs along the bottom - DB Schema, Plot, SQL Log

![image](https://cloud.githubusercontent.com/assets/7872218/17021134/be7ada68-4f3d-11e6-95ac-164c2115b2cd.png)

Found 'Plot' and 'SQL Log'.
![image](https://cloud.githubusercontent.com/assets/7872218/17021539/882bce6a-4f40-11e6-8751-ec3ea27bcd67.png)

I assume there isn't a translation for every label?  Or should there be?
There's a 'schema' (<source>Schema</source>) but thats pointing to a different file...

**Comment by chrisjlocke** [comment]
Confirmation No.2 ... noticed a window caption was translated, but not the main one.

![image](https://cloud.githubusercontent.com/assets/7872218/17021677/77f29dfc-4f41-11e6-8206-5f194532fa72.png)

Should the main caption be translated too?  I presume so.... ?

**Comment by justinclift** [comment]
Ahhh, co-incidentally I was looking at the dock labels earlier on as part of another change. :smile:

DB Schema is probably not showing up for you in a search because it has an &amp; embedded in its string. eg:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.ui#L1277

**Comment by justinclift** [comment]
Hmmm, the main caption probably should be translated.  I'm not 100% sure though. 😀 

See if you can figure it out.  We can always circle back to it later when the bulk of the other UI elements are done. :smile:

**Comment by chrisjlocke** [comment]
Thanks for the prompt reply. :smile: 
Did search for 'schem' and >db but no matches.  No matches in the sqlb_ar.ts for 'DB Sche&amp;ma'.  Will skip that one.... :wink: 

Will note down what I can't find so there is a list somewhere.  I'm sure there will be more ....

**Comment by justinclift** [comment]
Maybe chuck them in a comment here, using a "list style"? eg:

## Arabic
* foo
* bar
* baz

## French
* foo
* bar
* baz

etc

People can edit their own comments, so you can update/edit the comment as you go.

?

**Comment by chrisjlocke** [comment]
OK... *scratches head*.  Last question.  Honest.  The *.ts files have <location> tags, with line=xxx parameters.  Are these critical?  
eg:
<message>
        <location filename="../MainWindow.ui" line="1274"/>
        <source>&amp;Modify Table...</source>
        <translation>تعديل الجدول...</translation>
    </message>
    <message>
        <location filename="../MainWindow.ui" line="1277"/>
        <source>Open the Modify Table wizard, where it is possible to rename an existing table. It is also possible to add or delete fields form a table, as well as modify field names and types.</source>
        <translation>فتح الساحر لتعديل الجدول, حيث يمكن تعديل جدول حالي. و يمكن أيضا إضافة أو حذف خانات جديدة من الجدول, كما يمكننا تعديل إسم و نوع الخانة.</translation>
    </message>

but the mainwindow.ui at those lines:
![image](https://cloud.githubusercontent.com/assets/7872218/17022039/b0c0f3f2-4f43-11e6-8d9c-1e93aa419ccd.png)

I assume (in the above example) the bottom 'message' relates to a tooltip, and the line numbers should match.  Slightly confused, as tooltips (translated) seem to be appearing, so didn't want to blindly change line numbers if that didn't matter...

**Comment by justinclift** [comment]
Definitely ignore the line numbers. :smile:

There's a tool called "lupdate" which actually updates them automatically.  It seems to do that by looking at the source files, then updating the .ts files to correct the line numbers for each string.

You can launch it if you want from Qt Creator by (from the top menu) Tools → External → Linquist → Update translations (lupdate).

**Comment by chrisjlocke** [comment]
While I'm dabblin', in the 'About Dialog', it says 'SQLite Database Browser is..."
Should this be changed to 'DB Browser for SQLite' ?

**Comment by justinclift** [comment]
Ahhh yeah.  Definitely. :smile:

**Comment by chrisjlocke** [comment]
Having gone through the Arabic and Chinese, and seeing the languages still to go, I'm going to attack this in two 'sweeps'.  First off I'll correct the obvious issues, so its at least presentable, ie, the \&amp; mismatches stopping the translations appearing.  This will get the files ready for the planned release.  I'll then go back and thoroughly tidy up.  I've written a quick VB prog to check the .ui and .ts files for mismatches and help locate 'bugs', so they shouldn't be is such a mess as @innermous pointed out.

**Comment by justinclift** [comment]
... the "DB Schema" tab title just changed in our source.

I removed the &amp; in it, as it was misplaced anyway.

Sorry for the extra work. 😇

**Comment by chrisjlocke** [comment]
Misplaced?

**Comment by justinclift** [comment]
Yeah, the &amp; is supposed to represent a shortcut key.  It wasn't on the correct key for DB Schema anyway, so I just removed it.

**Comment by chrisjlocke** [comment]
I love these executive decisions! :wink:

Thanks,
Chris

**Comment by chrisjlocke** [comment]
OK, so after editing the .ts files and going back to Qt Creator, and doiing the lupdate and lrelease, its gone back and flagged a lot of the translations as 'unfinished'
`<translation type="unfinished">Version</translation>`
This stops the translations appearing.  Is there another step somewhere?  Manually editing the .ts files obviously isn't the right thing to do... :disappointed:

**Comment by justinclift** [comment]
Here's where I wish I knew more about translation files. 😢 

Which of lupdate and lrelease is adding the "unfinished" type to them?

**Comment by justinclift** [comment]
Guessing you've already looked over this?

&nbsp; &nbsp; https://doc.qt.io/qt-4.8/linguist-translators.html

**Comment by justinclift** [comment]
This one is overview stuff, but doesn't seem to help with "how to mark things as finished":

&nbsp; &nbsp; https://doc.qt.io/qt-4.8/linguist-manager.html

**Comment by chrisjlocke** [comment]
Oops.  I've been editing the raw .ts files.  There is a big button in Qt Linguist (which I hadn't previously installed)

![image](https://cloud.githubusercontent.com/assets/7872218/17077698/99896ef0-50d1-11e6-9fe0-3f71bbdc7464.png)

This should make things easier! :wink:

**Comment by chrisjlocke** [comment]
Green ticks.  Thats a good thing.

![image](https://cloud.githubusercontent.com/assets/7872218/17083260/af2f4228-5191-11e6-9081-b1b98f376c9a.png)

Progress being made!

**Comment by justinclift** [comment]
Heh Heh Heh

Keep going @chrisjlocke, looks like you're nearly there! 🎉

**Comment by chrisjlocke** [comment]
Hmm.  Some weird things keep occurring.  Going throuhg the German file for instance, and the captions for the dialogs are appearing in Arabic.

![image](https://cloud.githubusercontent.com/assets/7872218/17083828/ebd1a416-51a3-11e6-938a-3e99666080b6.png)

I'm not used to Qt Linguist or Qt Creator, so not sure where (or if?) I should be looking... maybe its Linguist just getting confused, or the .de.ts file was copied from the .ar.ts file?

**Comment by chrisjlocke** [comment]
Its OK.  Sorted it.  For some reason, it takes the current selected language from the *real* program, and so because Arabic was the last language I tested, it was showing that in the preview.  Bit mad...

**Comment by justinclift** [comment]
Oh wow, yeah that's unexpected.

Guess it's part of the learning process. :wink:

**Comment by SafaAlfulaij** [comment]
So, A quick "scan" throught the Arabic file showed me that there is a huge number of logical mistakes, I'm referring to This: `<translation>تصدير(&amp;)</translation>` especially.
I'd say to give the file for someone who really knew what translation (and the technical part of it) is.

Not to mention the grammatical errors and translation mistakes.

**Comment by chrisjlocke** [comment]
A lot of the translations have been corrected, due for 'release' soon.  Admittedly they're probably still not perfect, but the errors (like above) will have been addressed.  The main issue is that the program expects a shortcut key (so `&ampy` for ALT+Y, `&ampu for ALT+U, etc) so one has to be supplied, which doesn't always fit into the translation.  
I'm more than happy for you to assist me in this challenge if you would like! :wink:

**Comment by justinclift** [comment]
@SafaAlfulaij Yeah, would be optimal. 😃 

With this project, one important factor is that it's volunteer based effort.  All of the stuff you see (both good and bad) is the result of people willing to put their time into something, and they skill they have at it.

Importantly, people's skill level improves as they gain experience through practise and new challenges.

For example I'm personally a newbie with C++/Qt.  In no way am I good enough at it (yet) to make deep changes for this project. :wink:

However, [I can improve user visible dialogs](https://github.com/sqlitebrowser/sqlitebrowser/issues/673) decently (in my opinion 😈 ).  Hopefully soon, my understanding of things will have improved enough that I can assist with the more fundamental changes we need. :bowtie:

You're right about the &amp; sign's in strings.  They're breaking a bunch of translated items throughout the user interface, and it seems to be across all languages.  @chrisjlocke is putting time into fixing that, using our current understanding of the problem.  Hopefully, this gets us most of the way to our translations being "usable", even if not 100% fantastic (yet). 😁 

Would you be ok to look over our Arabic translation once @chrisjlocke has the &amp; sign problem fixed?  It should be within the coming week.

**Comment by SafaAlfulaij** [comment]
The programmer is NOT responsible for fixing the translation files. You
should contact the translator to fix that, or you simply don't get it
released.

"which doesn't always fit into the translation."
This isn't accepted in Arabic, it is not Japanese/Chinese.

I can work on the translation but my way of my translation is different,
I'm not sure if you accept that, as if will change almost all of the
current translations.

**Comment by justinclift** [comment]
When you say your way of translation is different... are you meaning a different dialect of Arabic?

**Comment by SafaAlfulaij** [comment]
> When you say your way of translation is different... are you meaning a different dialect of Arabic?

No, it's just another way of translating buttons (To action not noun), and some other Arabic specific rules.

**Comment by justinclift** [comment]
Ahhh.  Not sure then.  Would you be ok to discuss it with @0xbsec, [who recently made our Arabic translation](https://github.com/sqlitebrowser/sqlitebrowser/pull/642)?

**Comment by chrisjlocke** [comment]
Just a nod that I'm not just correcting the `&amp; but also the missing translations.  
![image](https://cloud.githubusercontent.com/assets/7872218/17251920/80408dae-55a2-11e6-8ce5-817dcdcfe0af.png)

This shows a large number of missing translations.  Some are just warnings of ellipses not correct, or full stops.  Its not just the dialogs, but messages displayed by the application.

Admittedly, its not going to be 100% - but I hope its not going to be as bad as this.... :wink:
http://static.boredpanda.com/blog/wp-content/uuuploads/funny-chinese-sign-translation-fails/funny-chinese-sign-translation-fails-10.jpg

**Comment by justinclift** [comment]
Ahhh, ok. :smile:

**Comment by justinclift** [comment]
@chrisjlocke How's this progressing?  We're closing out the last few issues now... :smile:

**Comment by justinclift** [comment]
Going to try and fix the obvious UI elements somewhat quickly. :smile:

These are the translations we have at present:

* sqlb_ar.ts - Arabic
* sqlb_de.ts - German
* sqlb_en_GB.ts - British English
* sqlb_es_ES.ts - Spanish
* sqlb_fr.ts - French
* sqlb_ko_KR.ts - Korean
* sqlb_pt_BR.ts - Brazilian Portuguese
* sqlb_ru.ts - Russian
* sqlb_tr.ts - Turkish
* sqlb_zh.ts - Chinese (Simplified?)
* sqlb_zh_TW.ts - Traditional Chinese

These are the UI's we have at present:

* AboutDialog.ui
* CipherDialog.ui
* ColumnDisplayFormatDialog.ui
* CreateIndexDialog.ui
* EditDialog.ui
* EditTableDialog.ui
* ExportCsvDialog.ui
* ExportSqlDialog.ui
* ImportCsvDialog.ui
* MainWindow.ui
* PreferencesDialog.ui
* SqlExecutionArea.ui
* VacuumDialog.ui

So, each of the UI's need to be checked for each language:

## Arabic

- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Chinese (Simplified?)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Chinese (Traditional)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## English (British)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## French
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## German
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Korean
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Portuguese (Brazilian)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Russian
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Spanish
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

## Turkish
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

Now to get it done.  I'll update the checkboxes here (probably in batches) as I progress.

**Comment by justinclift** [comment]
## Arabic

- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Chinese (Simplified?)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Chinese (Traditional)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## English (British)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## French
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## German
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Korean
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Portuguese (Brazilian)
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Russian
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Spanish
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
## Turkish
- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] ColumnDisplayFormatDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [ ] ImportCsvDialog.ui
- [ ] MainWindow.ui
- [ ] PreferencesDialog.ui
- [ ] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by chrisjlocke** [comment]
I'll commit later what I've got - I've gone through about 6 languages completely, not just fixing the dialogs.  Green ticks all round in Qt Linguist.

**Comment by justinclift** [comment]
Thanks @chrisjlocke that should help a bunch. :smile:

Make a PR for it though, don't just directly commit it.

**Comment by justinclift** [comment]
@chrisjlocke By the way, which ones are those 6?  I'll continue on with the others. :smile:

**Comment by justinclift** [comment]
Note, the Arabic translation has been redone completely today in #706.  Looks like 100% coverage too, which is pretty awesome. 😁

**Comment by chrisjlocke** [comment]
Write.  Sorry, right.  I can spend tomorrow doing some more languages.  I've seen most languages seem to have been completed, but unsure whether thats just the dialog or the full translations (I'm going through Qt Linguist, so doing the whole translation...) and I presume my 'bits' can't be merged with whats already been committed?  (Guess I could ignore the UI translations where they've been posted).  Sorry.  Rambling now...
If there is a specific language you want me to do next, let me know...

**Comment by justinclift** [comment]
Thanks Chris.  Yeah, drop this for now.  Several of the original translation authors responded positively to being contacted, and have either given us complete translations back or said they would.

There are a few who haven't, but it's probably something we can look at closer to the weekend.  We might just leave those ones as-is for now.  Thinking we'll call it at the time.

**Comment by justinclift** [comment]
Meh, we've done what we can for the 3.9.0 release.  It's "good enough for now".

:wink:
