### ISSUE TITLE
Fix tab order of widgets in all windows

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#647]
One thing that keeps bugging me, is that the tab order of the widgets in our windows/dialogs seems very random.

We should probably fix that, to make using the keyboard more practical - or even easy :wink:.

**Comment by chrisjlocke** [comment]
What files is this set in?  In VB, there is a 'tab index'.  How does it work for Qt?  I don't mind changing dialog files to fix the order.

**Comment by revolter** [comment]
@chrisjlocke, Wow, just found out [this tutorial][1] and it looks so easy. But you need [Qt Creator][2] for this.

  [1]: http://doc.qt.io/qt-4.8/designer-tab-order.html
  [2]: https://www.qt.io/ide

**Comment by chrisjlocke** [comment]
Aah, similar to how VB does it, but its just a GUI to change the 'tab
index' for the property in the code behind the form.  I was toying with
editing the file manually, but will have a look at installing the Qt
Creator.
Thanks for the links! :thumbs:

**Comment by justinclift** [comment]
@chrisjlocke DB4S definitely compiles ok when driven through Qt, if you want to do that instead of driving it through MSVC.

Added some notes here on doing that a while ago, though they're not fleshed out in any way:

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/wiki/Notes-for-compiling-on-Windows

Under the "Notes for Qt Creator" heading. :smile:

**Comment by chrisjlocke** [comment]
OK, have gone through all the dialogs, and have rejiggled the tab orders.
Am correcting the translation files related to these dialogs, so this will be in that commit.

**Comment by innermous** [comment]
@chrisjlocke I think, tab orders and translations should be in different commits.

**Comment by justinclift** [comment]
@innermous Yep, good point. :smile:

**Comment by chrisjlocke** [comment]
No problem. :smile:

**Comment by chrisjlocke** [comment]
OK, have commited the files into a pull request. #676 
Wasn't sure whether to add the ui.xxx.h files too (gitHub seems to think I have 271 files to commit...) so added them anyway...

**Comment by justinclift** [comment]
Thanks @chrisjlocke, that looks awesome.

Will check it out in depth fairly soon. 😁

**Comment by justinclift** [comment]
We should probably make a ToDo list for this. :smile:

- [ ] AboutDialog.ui
- [ ] CipherDialog.ui
- [ ] CreateIndexDialog.ui
- [ ] EditDialog.ui
- [ ] EditTableDialog.ui
- [ ] ExportCsvDialog.ui
- [ ] ExportSqlDialog.ui
- [x] ImportCsvDialog.ui
- [x] MainWindow.ui
- [x] PreferencesDialog.ui
- [x] SqlExecutionArea.ui
- [ ] VacuumDialog.ui

**Comment by chrisjlocke** [comment]
I checked the others, but their tab order was fine.  Qt listed the controls
in the right order.

**Comment by justinclift** [comment]
Cool, thanks Chris. :smile:
