### ISSUE TITLE
Weird vertical scrollbar resizing problem in Browse Data tab

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#648]
Noticed a weird problem with the vertical scroll bar in the Browse Data tab.

For this small example database, there are 33 rows of data.

The problem is that the vertical scroll bar on the right isn't scrolling to the bottom of the data set correctly.  No idea why.
![screen shot 2016-07-13 at 15 37 53](https://cloud.githubusercontent.com/assets/406299/16807611/0551670a-4911-11e6-99c7-f65e61458814.png)
![screen shot 2016-07-13 at 15 37 57](https://cloud.githubusercontent.com/assets/406299/16807622/0ef33d4c-4911-11e6-8185-d7cc1fe3fdda.png)

As an extra data point (may not be helpful) the scrollbar itself correctly disappears if the window is resized to show all the data, and reappears if the window is resized small enough to need it.  Still doesn't fix the scrolling problem though.

![screen shot 2016-07-13 at 15 35 57](https://cloud.githubusercontent.com/assets/406299/16807710/6550e70c-4911-11e6-9b5f-db6b0c12fe0c.png)

**Comment by justinclift** [comment]
The data set showing the problem is available online here:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/example_datasets/Belfast%20Bikes%20Docking%20Stations/

**Comment by justinclift** [comment]
This problem still happens even when rolling back the code to last year (eg https://github.com/sqlitebrowser/sqlitebrowser/commit/71b7806f036b262742dd29d3f36b3f98c0b7ef5e), so it doesn't seem to be a new thing.

**Comment by revolter** [comment]
No problem here with the 3b2c192b version. Can you test the scrollbars in other apps, better yet, Qt apps? And, it may sound dumb, but "did you try turning it off and on again?" I often encounter OS X bugs that disappear after a restart.

**Comment by justinclift** [comment]
Yeah, I'm thinking giving a restart then compile everything might do the trick. 😦 

(and really, *nix based OS's should have that problem.  They're **supposed** to be better engineered. :smile:)

**Comment by justinclift** [comment]
So, this is only happening when SQLCipher support is enabled.  Only tested it on OSX so far, I'll see if the same is happening on Win64 in a bit.

**Comment by justinclift** [comment]
k, it doesn't happen for Win64 with SQLCipher.  Weird.

**Comment by revolter** [comment]
Well, I only use SQLCipher enabled builds and I had no problem with the scrollbars. And even if it was, from what I learned until now, there are small chances this would be a DB4S bug, and more chances of a Qt bug. Correct me if I'm wrong.

**Comment by justinclift** [comment]
Interesting.  When you tried, was it OSX?

**Comment by justinclift** [comment]
I've tried it with both Qt 4.8.7 from Homebrew, and Qt 5.7.0 installed through the Qt online installer.

Hmmm, I still have my old Qt OSX installation in a renamed dir.  I'll give that  shot in a minute and see what happens.

I really want to focus on #480 today though, so I'll probably ignore this for a bit. :smile:

**Comment by revolter** [comment]
Yes, I only work/develop/test on OS X.

**Comment by justinclift** [comment]
Yeah, I think you're right, this isn't a DB4S code problem.  After nuking Qt Creator 4.0.3, and moving Qt Creator 4.0.0 back into place... things are working again.

Truly weird.
