### ISSUE TITLE
"Don't show again" button doesn't seem to work

### ISSUE THREAD

**Issue by perfect1077** [sqlitebrowser/sqlitebrowser#651]
Every time I open up the program it asks me if i want to update, i click "Don't show again" and carry on. When i reopen the program later, the message still pops up asking me if i want to update.

**Comment by justinclift** [comment]
Oh, that's not good.  From memory, we did have a bug in an older version where it wasn't recognising that "Don't show again" had been ticked.

Which version is this happening to you on?

**Comment by justinclift** [comment]
@perfect1077 ping?

**Comment by justinclift** [comment]
@perfect1077 Errr... is this still happening for you?

**Comment by chrisjlocke** [comment]
It won't happen in the newer versions as there are no newer versions for it to check against! :wink: 
You won't know until the next newer version and this newer version (now the older version) finds the newer version......! :wink:
:confounded:

**Comment by justinclift** [comment]
Closing this due to lack of response from @perfect1077. 😦
