### ISSUE TITLE
Ignore transaction control statements when executing SQL

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#653]
When executing SQL that contains the transaction control statements `BEGIN TRANSACTION;` and `COMMIT;`, it fails with the error `cannot start a transaction within a transaction: BEGIN TRANSACTION;`.

Extracted from #556.

**Comment by justinclift** [comment]
Is this related to #568 as well?

**Comment by revolter** [comment]
It looks like it is, indeed.
