### ISSUE TITLE
Cancel button in export database to SQL doesn't work

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#654]
Going to `File > Export > Database to SQL file...` and pressing the `Cancel` button in the popup that appears, it doesn't close.

**Comment by innermous** [comment]
Anybody else can reproduce this?

**Comment by revolter** [comment]
I reproduced it consistently a couple of times, then added that modification and it worked. But now I can't reproduce it again. Most probably a Qt or OS X bug...

**Comment by justinclift** [comment]
Sounds we're all having occasional gotchas with the current code recently.

... it's probably caused by some of the code I wrote. 😈

**Comment by revolter** [comment]
No, it's the abnormal heat. Sorry!
