### ISSUE TITLE
Export table(s) as CSV file causes assertion failure

### ISSUE THREAD

**Issue by innermous** [sqlitebrowser/sqlitebrowser#657]
Just open database thru File menu and choosing the most recent db. Clicking File->Export->Table(s) as CSV file.
This appears to be random behavior, it doesn't work every time I try to export it.
```
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 537
```

**Comment by justinclift** [comment]
Hmmm, if it can be triggered by launching DB4S from the command line, I wonder if that would be useful?  eg run the launch in a loop (eg 99 times), and see if there's debugging/instrumentation type code you could add to further diagnose the issue?

**Comment by revolter** [comment]
I successfully reproduced this too. The crash occurs [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/ExportCsvDialog.cpp#L57).

**Comment by revolter** [comment]
From some reason, `items` is empty.

**Comment by revolter** [comment]
Steps to reproduce:

- open database from recents (don't know if necessary)
- select `File > Export > Database to SQL file...`
- close it
- select `File > Export > Table(s) as CSV file...`

and on [this line](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L1064), the `current_table` is set to something like `Tables (5)`, which I think is searched in the tables list, but  of course there is no table named `Tables (5)`

**Comment by innermous** [comment]
@revolter you don't always need to export->close->export, sometimes it crashes on the very first export.
I'll investigate this myself and send a patch soon.

**Comment by innermous** [comment]
Actually, I suggested *not* to use code like this back in the days 
```
current_table = ui->comboBrowseTable->currentText();
```
It might be tricky sometimes. I really should do some changes on this later :smile: 

@revolter 
Tables(5) is just root item of the tree holding all those tables you have. Someone who had written this code
```
current_table = ui->dbTreeWidget->model()->data(ui->dbTreeWidget->currentIndex().sibling(ui->dbTreeWidget->currentIndex().row(), 0)).toString();
```
was very risky :smiling_imp:

**Comment by innermous** [comment]
There's actually no safe way to determine, if selected item in dbtree is actually table, so all should depend on extra check in ExportCsvDialog constructor. If match is found - appropriate item is selected. As simple as it gets.

**Comment by innermous** [comment]
Fixed by [2c1ab5](https://github.com/sqlitebrowser/sqlitebrowser/commit/2c1ab5ba7b143c592f5f40a3e2c6f1d676d2bd1f)

**Comment by revolter** [comment]
I saw that line too and was pretty terrified. 😲 
And I knew that the "Tables (5)" is the text of some UI element that's NOT a table, but didn't have time to search for it.

Aren't tables defined by some models? As you said, we should work with models, not with UI texts.

**Comment by innermous** [comment]
In 
```
current_table = ui->dbTreeWidget->model()->data(ui->dbTreeWidget->currentIndex().sibling(ui->dbTreeWidget->currentIndex().row(), 0)).toString();
```
we are exactly working with models. Problem is, that there are plenty of nested items, such as indices and so on. You can't precisely determine if the parent's parent item is QModelIndex(), that parent item is actually "Tables" and so on. As for me, I don't see a reason to heap all those constructions if we are searching thru list with exact match anyway. Code is absolutely safe now in this point.
If you have a solution how to check whether selected item is a table item - that would be neat. But again - it won't do any better, since everything is filtered at last. 
Btw, that check that was added - I think it's a bit naive to take first item of list after  operation like findItems. Who knows, what's passed to it? :smile:

**Comment by revolter** [comment]
Are you sure that that line is working with models? I have no idea what models look like in Qt, but having `ui` and `sibling` there, it definitely looks to me that it's going through the UI widgets, and not some backing variables.

And, the code is safe, meaning it doesn't crash the app, but it's not completely correct. It shouldn't get in that method with the string `Tables (5)` as a `selected table name`.

I'm not criticising you, just the existing code base. Personally, I prefer to put checks like that, so if anything goes wrong, it doesn't crash, but I also like to ensure that it doesn't enter the function with weird values.

**Comment by justinclift** [comment]
Anyone wanting to clean up / improve the code base is definitely welcome to. 😀

**Comment by innermous** [comment]
@revolter no, it's work with models. 
Yep, i know it's not precise and perfect. But the result will be the same, you know. It is checked on dialog constructor's side anyway. Further checks on mainwindow side will just cause more instructions, that doesn't sound like an improvement for me.
That's just my imo, I am sure me and @justinclift will be glad to review possible improvements (just don't remove a check :smile: )

**Comment by innermous** [comment]
@revolter done [here](https://github.com/sqlitebrowser/sqlitebrowser/commit/0f88fac26f19ec0b80353b8657ac0e794e0a2ffd)
Now issue is completely resolved :smile:

**Comment by revolter** [comment]
Great 👍
