### ISSUE TITLE
Add the Ubuntu specific instructions to sqlitebrowser.org front page

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#671]
@deepsidhu1313 pointed out that the Ubuntu instructions [here](https://github.com/sqlitebrowser/sqlitebrowser#ubuntu-and-derivatives), are not on the front page of our sqlitebrowser.org website.

That needs to be fixed. :smile:

**Comment by justinclift** [comment]
@deepsidhu1313 In theory, this should be complete now.  Would you be ok to take a look here, and let us know if something needs adjusting?

* http://sqlitebrowser.org/#ubuntu
* http://sqlitebrowser.org/#ubuntu-stable
* http://sqlitebrowser.org/#ubuntu-nightly

**Comment by justinclift** [comment]
Haven't heard back from @deepsidhu1313, but I'm pretty sure this is fixed decently now.  Closing this issue.

If it turns out there's more needing to be done for this issue, feel free to re-open this. :smile:

**Comment by deepsidhu1313** [comment]
@justinclift, apologies for not replying back. Thanks for fixing the issue. :)

**Comment by justinclift** [comment]
Cool.  You're welcome @deepsidhu1313, thanks for pointing it out. :smile:
