### ISSUE TITLE
New layout for Edit Database Cell view

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#673]
Thinking about the Edit Database Cell, it's layout could do with some minor tweaks.

### Existing layout
![current layout - 2016-07-25](https://cloud.githubusercontent.com/assets/406299/17102161/3c4f2d60-5270-11e6-8b28-113d71697fe5.png)

* The purpose of the drop down selector (text/binary) isn't really clear until using the program for a bit.  It's purpose is to choose the view mode, so we can made that clearer by labelling it as such.
* The `Clear` button could use better labelling, to indicate it sets NULL when in binary mode
* The `OK`/`Cancel` buttons would probably be simpler if replaced by a single `Update` button
* Adding an `Image` option to the drop down menu is probably useful too, so people have a choice how to view their data.  The image view is already in our code base, and has been for some time.  There's just no manual selector for it yet.

### Proposed new layout - text
![new layout - text](https://cloud.githubusercontent.com/assets/406299/17102290/d6ac6986-5270-11e6-85ff-8d1e7ae28be5.png)

### Proposed new layout - hexadecimal
![new layout - hexadecimal](https://cloud.githubusercontent.com/assets/406299/17102301/e1ea13f2-5270-11e6-8db5-35dbf7cca339.png)

### Proposed new layout - image
![new layout - image](https://cloud.githubusercontent.com/assets/406299/17102311/e997dce2-5270-11e6-86b3-38250a58f850.png)

Note - unsure if "hexadecimal" or "binary" is the better string for the second view name.  Kind of thinking "binary" might be better, even though it's not technically accurate.

Thoughts? :smile:

**Comment by justinclift** [comment]
Hmmm, would `Apply` be a better word than `Update`?

Kind of thinking that `Update` could be unclear.  The user may think it means to retrieve newer data from the database, instead of pushing it to the database.

**Comment by justinclift** [comment]
Working on this in a branch here for now: https://github.com/justinclift/sqlitebrowser/tree/edit_cell_layout1

Instead of `View mode:` I've gone with just `Mode:`, and using `Apply` instead of `Update` too:
![screen shot 2016-07-25 at 17 22 16](https://cloud.githubusercontent.com/assets/406299/17108672/7358d11e-528c-11e6-917d-f4955c89b42b.png)
![screen shot 2016-07-25 at 17 22 21](https://cloud.githubusercontent.com/assets/406299/17108680/7836d60e-528c-11e6-9871-163d20718bc9.png)
![screen shot 2016-07-25 at 17 22 40](https://cloud.githubusercontent.com/assets/406299/17108686/7c60cd66-528c-11e6-8058-55f97931e022.png)

Now adjusting things so the various signals are sent at the right time, to keep things updated correctly.

**Comment by revolter** [comment]
About your second points, isn't `Clear` setting `NULL` even if *not* in the binary mode?

**Comment by justinclift** [comment]
Not so far.  In text mode it's been setting an empty string.

**Comment by revolter** [comment]
Hmm. Does it open with the `binary` mode selected by default? Because I used it a couple of time to set a cell to `NULL` but never used the mode combo box.

**Comment by justinclift** [comment]
Yeah, I think it used to start in binary mode by default.

That can be turned on again if you reckon it'd be useful?

**Comment by revolter** [comment]
I don't know what's the best solution.

**Comment by justinclift** [comment]
Similar here.  I'm completely guessing, but assuming that most people will have text data (at least for now) in their fields.  So a default to text mode makes sense for that.

We could have the button for "Set NULL" in all of the modes.  Clearing a field to an empty string instead (in text mode) is pretty simple regardless.  Cntl-A (or Cmd-A on OSX) to select everything then hitting delete/backspace does that.

**Comment by revolter** [comment]
I personally only used the (now gone) edit popup to set fields to `NULL`. I also think that selecting a cell and hiting backspace sets it to empty string too, doesn't it? So having it set to text mode by default and a `Set to NULL` button sounds very very good!

Also, what do you think about placing the docked editing widget in the right sidebar above the SQL log on fresh install?

![Screenshot](https://i.imgur.com/OA4Hs4S.png)

So the bottom part instead of the top one. I'm saying this because, probably, most of the users don't have very long values and it looms better as a square instead of a wide rectangle, and so you have more space for your tables or table data.

**Comment by justinclift** [comment]
Cool. :smile:

Just updated the new layout code to have a `Set as NULL` button instead of the old `Clear` button, regardless of Edit Cell mode setting.

For the defaults... no objection here.  We should probably include the `DB Schema` and `Plot` docks in the default layout too.  Any ideas for them?

**Comment by revolter** [comment]
I personally never used them, and I don't see where could we add them without being crowded. It would be a good idea, so the users know, at least, about the capabilities of DB4S, but, again, can't imagine where should they show up.

**Comment by justinclift** [comment]
k, well we'll need to figure out where to put them.

In theory, we should be able to tack them onto the right of your suggested layout, but have them off by default.  I think (without trying it yet), that would give the result you're meaning.

**Comment by chrisjlocke** [comment]
If the Cancel button has gone, is clicking '[X]' the only way to cancel?  This seems an usual 'desktop' UI convention.  I'm just old and used to the traditional 'OK' 'Cancel' buttons - clear and explicit to what happens.  Also, useful for keyboard users - sometimes, clicking 'Esc' doesn't always work to cancel, as there is no cancel button linked to the Escape key.

**Comment by justinclift** [comment]
Nah, it's now a toggle-able window - using Ctrl-E (Cmd-E on OSX).

The other docks already work like that too (eg are toggle-able), so this bring it into line with them.

**Comment by justinclift** [comment]
On that note, we need to think of a new keyboard shortcut for "Execute SQL", which the Edit Cell dock has usurped. 😈

**Comment by chrisjlocke** [comment]
Sorry - confused by your 'toggle-able' answer.  In your new 'edit database cell' window, you've an apply button.  If I've entered data but this is wrong, how would I cancel this edit?

**Comment by justinclift** [comment]
Definitely don't hit apply. :smile:

Also, change to a different cell in the main window, so the contents of the Edit Cell get refreshed from that.

... hmmm...

So maybe `Revert` and `Apply` buttons instead of just the single `Apply`?

**Comment by revolter** [comment]
We should take into consideration the docked version of this edit cell widget, right? So the "don't hit apply / select another cell" makes more sense here.

**Comment by chrisjlocke** [comment]
Aah, s'okay - I follow now - must have had a brain fart earlier.  Was thinking the Edit Database Cell was a dialog, so popped up over the window, rather than docked state...

**Comment by revolter** [comment]
Sorry, I left out a "too" there. You can drag to undock it now, so it changes to a window popup as you said. What I was trying to say is that we need to think of the docked and windowed version too.

**Comment by justinclift** [comment]
Cool.  Let's leave out the `Revert` button for now.  It'd probably just add visual clutter, and is more code to maintain. :smile:

**Comment by justinclift** [comment]
I ***think** #679 is ok, but someone looking over it first wouldn't hurt. 😁

**Comment by justinclift** [comment]
Just merged it. :smile:

**Comment by justinclift** [comment]
@revolter Oops, forgot to reorganise the layout.

I'll open a new issue for that, and get onto it in a bit (maybe tomorrow though).

**Comment by revolter** [comment]
@justinclift Great :thumbsup:
