### ISSUE TITLE
Potential data loss gotcha - in-place editor isn't binary safe :(

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#674]
Found a nasty gotcha.  The in-place editor for table cells isn't binary safe. 😨 

For example, lets say someone has binary data in a cell (eg Line 12-Name below):
![screen shot 2016-07-25 at 15 23 39](https://cloud.githubusercontent.com/assets/406299/17104879/bff096fc-527c-11e6-8b71-d901f7ece632.png)
If they trigger the in-place cell editor, hitting Enter to close it corrupts the binary data:
![screen shot 2016-07-25 at 15 23 44](https://cloud.githubusercontent.com/assets/406299/17104888/c957a9ba-527c-11e6-9cc3-6a0f78ec0dd4.png)
![screen shot 2016-07-25 at 15 23 52](https://cloud.githubusercontent.com/assets/406299/17104900/d1823e0c-527c-11e6-9e85-4908a41c8fda.png)
The PNG data in that cell is no longer correct.  There is no recovery apart from 'Revert Changes', which loses all changes since the last save.

If the user has pressed Ctrl-S (Cmd-S on OSX) to commit the data since, they'd need to restore the data manually (from backup, etc). 🙀 😱 🙀

**Comment by justinclift** [comment]
Note - this bug has probably been present for a long time, rather than being in recent code.

**Comment by justinclift** [comment]
@innermous Would you have time to look into this?

**Comment by revolter** [comment]
Is editing binary data a solution? If not, shouldn't we disable the in-place editor all together for binary cells? Just a thought.

**Comment by justinclift** [comment]
Yeah, that would work too. :smile:

**Comment by justinclift** [comment]
Looking into this now.  [QItemDeletegate](https://doc.qt.io/qt-4.8/qitemdelegate.html) seems to be the area of things to learn about for this.

**Comment by justinclift** [comment]
As pointed out by @SafaAlfulaij, the problem code may be something to do with this:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/sqlitetablemodel.cpp#L271-L276

On his Qt5 based system, `BOOL` fields can't be edited in-place with DB4S.  So the above code may not be functioning as intended only with Qt4.

**Comment by justinclift** [comment]
Tested with Qt5 here (on OSX), the problem still happens.  So, it's not a Qt4-only bug.  Oh well. :wink:

**Comment by justinclift** [comment]
Note - this bug was fixed with #708.
