### ISSUE TITLE
Enable JSON1 extension by default

### ISSUE THREAD

**Issue by bhj** [sqlitebrowser/sqlitebrowser#677]
It would be great to be able to run SQL that uses functions from the [JSON extension](https://www.sqlite.org/json1.html).

**Comment by justinclift** [comment]
That extension looks useful. :smile:

What happens when you try to add it using Preferences → Extensions?

**Comment by bhj** [comment]
Ahh, had not noticed that pref pane. I imagine that would work but haven't compiled one of them before (on macOS 10.11 and will accept hints!)

Edited title to clarify as FR; thanks!

**Comment by justinclift** [comment]
Cool, no worries at all. :smile:

**Comment by justinclift** [comment]
Personally, I haven't ever used a SQLite extension either.  The code was added before my time, and I'm not (yet) a power user.

... but I'm improving. 😁

**Comment by bhj** [comment]
I noticed in another issue that you're on a Mac as well? Some Mac dev docs would be great. Maybe I should open another issue? 😃

**Comment by justinclift** [comment]
Yep, open another issue. :smile:

**Comment by justinclift** [comment]
Done. 😄

**Comment by revolter** [comment]
@justinclift Does the JSON extension need to be compiled or something?

If not, @bhj, can you manually add it in `Preferences` and let us know if it's working?

**Comment by justinclift** [comment]
@bhj Stumbled across info about this while investigating a different issue.  Including the JSON1 extension by default (on OSX) could be extremely easy.

If I create a test build with it, would you be ok to check that it works reasonably well from your point of view?

**Comment by bhj** [comment]
Absolutely! Their (sqlite) extension docs seemed pretty sparse and I wasn't sure where to start. Thanks @justinclift @revolter

**Comment by justinclift** [comment]
@bhj Please give this one a go:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-201608021830-issue677v1.dmg

For OSX, we kind of cheat when building SQLite.  We just build it using Homebrew.  For this experimental .dmg file, I just rebuilt it and included `--with-json1` on the Homebrew command line.

There's a fairly decent chance that worked.  Not guaranteed, but definitely worth a shot. 😁 

If it does happen to have worked, we can probably update our build & release process to include that from here on.

**Comment by thiagosantos** [comment]
The JSON1 functions (https://www.sqlite.org/json1.html) will be available in this nightly build?

**Comment by bhj** [comment]
@justinclift Looks good so far:
```
SELECT json_object('ex','[52,3.14159]'),
  json_array(1,2,'3',4),
  json_array_length('[1,2,3,4]'),
  json_extract('{"a":2,"c":[4,5,{"f":7}]}', '$'),
  json_insert('{"a":2,"c":4}', '$.a', 99),
  json_replace('{"a":2,"c":4}', '$.a', 99),
  json_object('a',2,'c',json_object('e',5)),
  json_remove('[0,1,2,3,4]','$[2]'),
  json_type('{"a":[2,3.5,true,false,null,"x"]}'),
  json_valid('{"x":35}')`
```

outputs

`{"ex":"[52,3.14159]"},[1,2,"3",4],4,{"a":2,"c":[4,5,{"f":7}]},{"a":2,"c":4},{"a":99,"c":4},{"a":2,"c":{"e":5}},[0,1,3,4],object,1`

Thanks, hopefully flipping on support for other platforms isn't too hard!

**Comment by justinclift** [comment]
@thiagosantos I'll go and add it to the script for the nightly builds on OSX now. :smile:

**Comment by justinclift** [comment]
Just added it to our main OSX build instructions too.

For OSX at least, this should be included in our releases from here on.

**Comment by revolter** [comment]
Would it work on Windows too?

**Comment by justinclift** [comment]
The extension code itself should, as far as I know, as it's a "core" extension.  Though it would take a separate piece of time to look into it.

**Comment by justinclift** [comment]
Oops.  Just realised that the "3.9.0 beta1" build released today for OSX didn't include the JSON1 extension.

I'll need to investigate whether SQLCipher + the JSON1 extension go together ok.  If they do, it should be feasible to have them both in 3.9.0.

**Comment by justinclift** [comment]
@bhj The new release out today - 3.9.0 - doesn't have JSON1 included in it.  It's purely because we included SQLCipher by default in all builds, and I haven't yet had time to investigate how to build them both together.

It may turn out to be super easy... I just don't know (yet). :wink:

In the meantime, grabbing any of our nightly builds *without* SQLCipher should work.  They have the JSON1 extension included as part of their automatic building. :smile:

**Comment by bhj** [comment]
Appreciate it @justinclift - people will probably want a JSON browser too, heh... One step at a time :wink:

**Comment by justinclift** [comment]
Heh Heh Heh

We definitely accept Pull Requests if you're up for it. 😁

**Comment by slidertom** [comment]
Is any plans to release with the JSON1 enabled by default?
(json1 is a core extension - sqlite should be recompiled with the json1 extension enabled.)

**Comment by DjPasco** [comment]
It's very easy to to add JSON1 support to sqlitebrowser. Only "-DSQLITE_ENABLE_JSON1=1" is required when building sqlite.

**Comment by justinclift** [comment]
@bhj @thiagosantos @slidertom @DjPasco Good news.  The nightly builds on Windows - both with and without encryption -now include the FTS3, FTS4, FTS5, and JSON1 extensions.

They'll be in the next major Windows releases too. :smile:

**Comment by wmertens** [comment]
@justinclift it seems that 3.10 for mac does not include JSON1 support?

**Comment by justinclift** [comment]
@wmertens Oh.  It's supposed to.  Looking at the SQLCipher build I used... you're right.  No JSON1 option enabled:

&nbsp; &nbsp; https://github.com/Homebrew/homebrew-core/blob/dfe6b1582283312cb899244626ec3f95bc5416a1/Formula/sqlcipher.rb#L28-L40

I'll fix that later today, so it's enabled in our nightly builds, and so that our upcoming 3.10.1 release has it too.

Sorry for the hassle.  I remember checking the SQLite only build, but didn't think to check the SQLCipher one.

As a thought, if you don't need SQLCipher at the moment then all of our OSX SQLite-only nightly builds should have it:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/osx/

(Looking at that directory, the SQLite-only nightlies from 20th August onwards seem to have doubled in size.  Not sure if that indicates a problem.  I'll need to look at that later too just to be sure).

**Comment by justinclift** [comment]
@wmertens This is in process now: https://github.com/Homebrew/homebrew-core/pull/17613

If for some reason that doesn't get accepted then the nightly build script can be updated to use a local build of it instead of using the Homebrew one.  The above PR shouldn't be a stress though, as the JSON1 extension doesn't have any downsides (that I know of!) to being enabled by default. :smile:

**Comment by justinclift** [comment]
@wmertens Just took a look at the SQLite-only build from last night... and it seems busted.

I'll take a closer look into it tomorrow and try to figure out what's wrong.

**Comment by justinclift** [comment]
After this OSX build problem is fixed, we should probably create a .sql script that can be used to do basic testing of the json/fts3/fts4/fts5, then add running that to the end of each build process.

That should make sure we catch future regressions like this.

**Comment by justinclift** [comment]
Found the problem with the OSX SQLite only build.  While updating things for the 3.10.0 release I added the `icu4c` library.

This is normally no problem, and DB4S runs fine after it's added.  However the `macdeployqt` tool (part of Qt) which is **supposed** to copy dependant libraries into an application in preparation for it's release... busts it.  It doesn't seem to notice there was a critical symbolic links that needed copying too, so the whole thing falls in a heaps when DB4S is then run.

Just added a workaround to the build script (manual creation of the symbolic link), which will work for now, but will break when the version numbers in the `icu4c` path change.  We'll probably need to figure out an approach which won't break so easily.

**Comment by wmertens** [comment]
@justinclift wonderful! I can confirm that it works in the nightlies :)

**Comment by justinclift** [comment]
Awesome.  Thanks @wmertens. :smile:

**Comment by justinclift** [comment]
As a follow up data point, the `JSON1` extension is now always built as part of Homebrew's `sqlcipher` formula.  So it should always be in our SQLCipher enabled OSX builds (nightly and release) from here onwards.

**Comment by MartinHaeusler** [comment]
The JSON1 extension is still not included by default in SQLite Browser on Linux (Mint 19.1 here; installed from the official repos).

**Comment by justinclift** [comment]
As far as I know, we don't do the packaging for the official Mint repos.

If you ping the people who do though, it's not a hard thing to add. :smile:

**Comment by MartinHaeusler** [comment]
@justinclift I also tried installing it from the PPA, as described on the sqlitebrowser website - unfortunately with the same result, no Json1 functions available...

**Comment by justinclift** [comment]
@deepsidhu1313 Any ideas? :smile:

**Comment by deepsidhu1313** [comment]
Enabled for deb packages. Can please someone test latest nightly builds ?? I will update snap package shortly.
