### ISSUE TITLE
Our qHexEdit widget is outdated

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#680]
The qHexEdit widget we're using comes from here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/tree/master/libs/qhexedit

Our version of the code seems to be really out of date, so someone should probably investigate if it's feasible/useful for us to update to a newer version. :smile:

**Comment by revolter** [comment]
So [this one][1], right?

  [1]: https://github.com/Simsys/qhexedit2

**Comment by justinclift** [comment]
Oops.  Yeah, I cut-n-pasted the wrong link. :wink:

**Comment by justinclift** [comment]
Closing this, as @revolter completed this in https://github.com/sqlitebrowser/sqlitebrowser/commit/ff302c4b6b48fbf7f5dc17f59169790685c85ea5.

**Comment by justinclift** [comment]
@revolter Ironically, 0.7.8 just came out after your prompting. 😈 

&nbsp; &nbsp; https://github.com/Simsys/qhexedit2/releases/tag/v0.7.8

We might as well update to that.

**Comment by justinclift** [comment]
Actually, reading the commits there since the 0.7.7 release, the variable initialisation piece seems like it might be the only useful thing for us.  Any idea?

**Comment by revolter** [comment]
Well, it's not a problem to update it again, so I'll do it.
