### ISSUE TITLE
can not create a table, because the tab is gray

### ISSUE THREAD

**Issue by huangjennifer947** [sqlitebrowser/sqlitebrowser#687]

**Comment by revolter** [comment]
Could you please attach a screenshot? It would help us understand the problem easier and faster :smile:

**Comment by justinclift** [comment]
@huangjennifer947 Have you solved this problem yet? :smile:

If not, can you add a screenshot here to show the problem?

**Comment by justinclift** [comment]
Closing this due to lack of response.
