### ISSUE TITLE
Json export support

### ISSUE THREAD

**Issue by thiagosantos** [sqlitebrowser/sqlitebrowser#688]
Hello,

I've been using DB Browser since May and I'm loving it. 
It's too easy to create, import data and manipulate data directly.

I use the CSV export a lot and it works very well for me. But sometimes I need sqlite records to be available in a JSON, as they are as CSV. So, I have to export to CSV than convert manually to JSON.

Certainly I can create a script to access database and export do JSON, but why not have this as a system feature.

Suggestion:
Implement by default a JSON export as CSV and SQL

Extras
Offer a dialog box for choose where to save and a checkbox to be the export pretty print or not.

 Best regards,

**Comment by justinclift** [comment]
This sounds like a useful enhancement, especially for people using JSON friendly languages.

If we add a command line option to drive this as well, people could use this headless in their toolchain. :wink:

**Comment by justinclift** [comment]
@thiagosantos As a side question... would you have time to try out our latest nightly build?

We've made a bunch of usability tweaks to it, and could really use some feedback. 😁 
(there is a crash bug when closing a database that I'm chasing down, but it's just annoying, not a data loss thing :wink:)

**Comment by thiagosantos** [comment]
@justinclift Why not? For sure. I'll take a look this afternoon. The crash bug happens in a specific OS?

**Comment by justinclift** [comment]
Thanks.  With the crash, @revolter [has just provided a fix](https://github.com/sqlitebrowser/sqlitebrowser/pull/690), so the nightly builds from tomorrow onwards should be very stable.

For yourself, just try out the application itself and see if there are any really obvious silly bits. :grin:

Also, we've redesigned the "Edit Database Cell" window, to hopefully make it more useful.  If you could try that out, it would be great.

Just to be careful though, don't use it with live data if you keep binary info in the cells.  There's [a bug we need to fix](https://github.com/sqlitebrowser/sqlitebrowser/issues/674) in that situation before our next release.

**Comment by justinclift** [comment]
As a data point, this issue probably ties in with #677.

**Comment by FreudGit** [comment]
I'll love to have this feature!

**Comment by justinclift** [comment]
@revolter have a chat to @schdub about this, as he's indicated via email that he's going to put time into this as well. :smile:

**Comment by MKleusberg** [comment]
We should implement this using Qt's JSON support, I think: http://doc.qt.io/qt-5/json.html
For export this makes things easier because it allows pretty printing or compact printing (http://doc.qt.io/qt-5/qjsondocument.html#JsonFormat-enum). Plus it would allow us relatively simple import of JSON, too.
Only caveat: it requires Qt 5.0+. But I see no reason to not drop Qt4 support for 3.10.0 :)

**Comment by MKleusberg** [comment]
I've just pushed a commit which adds basic JSON export support. There are a few things missing here and there (more menu entries for easier access throughout the program, an option to change from CSV to JSON format and back while being in the dialog, a way to export SQL query results as JSON, and exporting multiple tables into one JSON file). Other than that JSON export is there :smiley: 
However, unlike other changes this one won't be in the next nightly build as our nightly builds are still based on Qt4 which doesn't support JSON... If you use Windows, @thiagosantos, then @justinclift might be able to build a once-off for testing purposes. If you are a Mac user, I think you actually can use the normal nightlies :smiley:

**Comment by justinclift** [comment]
Unfortunately, the OSX nightlies are back to using Qt4 again.

There's a problem with Qt5 on OSX, where it doesn't show all of the data in the tables. 😦 

Until we get that figured out... Qt4.

***sigh***

**Comment by justinclift** [comment]
Created a new issue about the Qt5 problem on OSX, so we can investigate it properly: #750

**Comment by innermous** [comment]
@MKleusberg JSon is not working correctly, it generates 11MiB files for 3 record table and file is just corrupted.
Tried with 3 different tables, actually.

**Comment by justinclift** [comment]
@innermous Any idea if this is working correctly, and/or if we can close this issue? :smile:

**Comment by mgrojo** [comment]
I think this can be closed, doesn't it?

**Comment by justinclift** [comment]
Yep. :smile:

**Comment by nissansz** [comment]
Hi, how to run export to json underwindows? Below not work

"DB Browser for SQLite.exe" L:\update.db --export L:\test.json

**Comment by Primes63** [comment]
https://lnkr.fun/c8c0516 consider this reply
