### ISSUE TITLE
Browse Data UI looks weird when creating a new database

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#691]
Following these steps:
- open app
- open existing non-empty database
- select `Browse Data` tab
- select `File` > `New Database...`
- click `Save`

and the data table widget transforms to:

<img width="1277" alt="screen shot 2016-08-01 at 17 32 54" src="https://cloud.githubusercontent.com/assets/5748627/17297338/0392ea22-580e-11e6-8d0b-f267216871f6.png">

After clicking `Cancel` on the `Add table` window popup, selecting the `Database Structure` tab and then the `Browse Data` tab again, it correctly shows up like this:

<img width="1305" alt="screen shot 2016-08-01 at 17 33 54" src="https://cloud.githubusercontent.com/assets/5748627/17297410/47ea710e-580e-11e6-83d4-73acb89668fc.png">

**Comment by justinclift** [comment]
Hmmm, are those images the wrong way around?

**Comment by revolter** [comment]
No. The database doesn't contain any table.

**Comment by justinclift** [comment]
It looks like something that would be kind of obvious in testing, so maybe one of the recent commits added it.  Shouldn't be too hard for you to figure out which one. 😈

**Comment by revolter** [comment]
Nope, it still happens in 3.8.0. It was probably not noticed because the user (probably) mostly created a new database from the `Database Structure` tab.

**Comment by justinclift** [comment]
Makes sense.  Lets target this for 3.10.0, as it's non-critical. :smile:

**Comment by MKleusberg** [comment]
@revolter Is this still happening for you? Just tried to reproduce it on my system without any luck.

**Comment by revolter** [comment]
@MKleusberg, nope :( I'll close this for now and reopen if I see it again.
