### ISSUE TITLE
Create a prettier installer .dmg for the OSX 3.9.0 release

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#693]
As @revolter pointed out, we should be able to create a prettier looking .dmg than what `macdeployqt` creates by default.

This project looks like a good approach, fairly simple to use:

&nbsp; &nbsp; https://github.com/andreyvit/create-dmg

**Comment by justinclift** [comment]
Using create-dmg looks fairly simple so far.

After compiling DB4S, in the git root directory use `macdeployqt` to include the DB4S dependencies into the .app bundle:

    $ macdeployqt src/DB\ Browser\ for\ SQLite.app -verbose=2

Then clone the create-dmg git repo (in a different directory), and move the DB4S .app bundle into it:

```
$ cd ~/git_repos
$ git clone https://github.com/andreyvit/create-dmg.git
$ cd create-dmg
$ mv ~/git_repos/sqlitebrowser/src/DB\ Browser\ for\ SQLite.app .
```

Then run create-dmg to create the prettifier .dmg:

```
$ ./create-dmg --window-size 500 300 --icon-size 96 \
    --volname "DB Browser for SQLite 3.9.0 Installer" --app-drop-link 380 205 \
    'DB Browser for SQLite 3.9.0.dmg' 'DB Browser for SQLite.app'
```

The result is better than what we presently have:

![screen shot 2016-08-01 at 22 17 42](https://cloud.githubusercontent.com/assets/406299/17309275/fd913214-5835-11e6-83a3-5a10c486142f.png)
It can be customised further (eg a pretty background), and some kind of volume icon too.  We'd need to look for appropriately licensed artwork for that, or create some ourselves.

As a side note, because this is command line driven we can use this for building the OSX nightlies too. :smile:

**Comment by justinclift** [comment]
As an idea or a background, maybe something with text on it saying "Drag and drop the .app icon to 'Applications'"?

**Comment by justinclift** [comment]
This might be clearer:

    Drag and drop this [DB4S icon] to here [Applications icon] to install the program

With an arrow showing the path from DB4S icon to the Applications icon.

**Comment by justinclift** [comment]
Translations... hmmm... that could be tricky. :wink:

**Comment by revolter** [comment]
Maybe just an arrow to avoid translations. Also, do you have enabled the show hidden files option?

**Comment by justinclift** [comment]
Yeah, the arrow is probably the right way to do it.

Also, which show hidden files option are you meaning?

**Comment by revolter** [comment]
The `defaults write com.apple.finder AppleShowAllFiles YES` command.

In which case, `.DS_STORE` and/or other hidden files would show up and make it look ugly.

> By default hidden files will show for users with com.apple.finder AppleShowAllFiles set to TRUE. This can be worked around by moving all hidden files outside the initial window size, this has the side-effect of enabling a scrollbar.

> Files to usually move:
- .background
- .DS_Store
- .Trashes
- .VolumeIcon.icns


Another useful info:

> Retina background
> Finder can display retina backgrounds if packaged correctly into a .tiff file. appdmg will do this for you automatically if it can find a file with the same name as the background appended with @2x.

> E.g. if the json contains "background": "TestBkg.png" then add a file with the name TestBkg@2x.png into the same folder.

I can test this if you want.

This info was taken from [node-appdmg][1]

  [1]: https://github.com/LinusU/node-appdmg

**Comment by justinclift** [comment]
Thanks.  Will investigate.  Trying to avoid a node dependency, but it doesn't hurt to look at their approach. :smile:

**Comment by revolter** [comment]
Didn't say to use it, as I understand a shell script is easier to use. It's just the useful info in the readme, and maybe `create-dmg` allows to move the files for example in a similar way.

**Comment by justinclift** [comment]
Cool, thanks. :smile:

**Comment by justinclift** [comment]
The Applescript created then executed internally by `create-dmg` seems to have an error in it.  Investigating.

**Comment by justinclift** [comment]
@revolter [node-appdmg](https://github.com/LinusU/node-appdmg) might be the better way to go after all.

Although both `create-dmg` and `node-appdmg` just call out to the hdiutil for the initial image creation, the subsequent adjustment of things inside the image (icon positions, etc) seems better done in the node one.  It doesn't rely on Applescript for starters. :smile:

**Comment by revolter** [comment]
The [SO answer][1] said that `node-appdmg` is

> a more modern and active effort based on Node.js

so that explains why is better written. It would be awesome if you would get it working!

  [1]: http://stackoverflow.com/a/628874/865175

**Comment by justinclift** [comment]
Yeah, it's working here without much issue.  It does seem to have a problem with volume names over 27 chars, but that can be worked around.

**Comment by justinclift** [comment]
Reckon this is ok?
![screen shot 2016-08-03 at 16 50 40](https://cloud.githubusercontent.com/assets/406299/17372159/83bbc510-599a-11e6-9668-2cfca7df328b.png)

**Comment by revolter** [comment]
Not trying to be rude, but, is that a mockup? If not, that red is too hard on the eyes.

**Comment by revolter** [comment]
I was imagining something like:

![Firefox installer](http://i.stack.imgur.com/M8P9e.png)

**Comment by justinclift** [comment]
Heh Heh Heh, that's why I ask. :grin:

Ok, I'll try to copy the Firefox one's approach.

**Comment by revolter** [comment]
Make sure you create the photo big enough to have the @2x version too.

**Comment by justinclift** [comment]
Good point. :smile:

**Comment by justinclift** [comment]
Any of these good enough?
![screen shot 2016-08-03 at 19 33 02](https://cloud.githubusercontent.com/assets/406299/17377428/836cd1a0-59b1-11e6-945e-52b9901502ca.png)
![screen shot 2016-08-03 at 19 33 14](https://cloud.githubusercontent.com/assets/406299/17377434/8893e1fa-59b1-11e6-889a-924d96860b2f.png)
![screen shot 2016-08-03 at 19 33 25](https://cloud.githubusercontent.com/assets/406299/17377440/9063c9ae-59b1-11e6-8a55-bfcfadb6f04a.png)
![screen shot 2016-08-03 at 19 33 37](https://cloud.githubusercontent.com/assets/406299/17377448/9402a1c0-59b1-11e6-8316-ddc9fee359ba.png)
![screen shot 2016-08-03 at 19 35 21](https://cloud.githubusercontent.com/assets/406299/17377451/994411fa-59b1-11e6-890b-76db383cf079.png)
I should probably look for a better arrow icon.  My hand drawn one is definitely not very good. :wink:

**Comment by justinclift** [comment]
This looks useful:

&nbsp; &nbsp; https://openclipart.org/search/?query=right+arrow

**Comment by revolter** [comment]
What size is it?

**Comment by justinclift** [comment]
The screenshot above should be able the same size.

Using a decent arrow seems to improve the look somewhat:
![screen shot 2016-08-03 at 19 43 42](https://cloud.githubusercontent.com/assets/406299/17377700/c4635bba-59b2-11e6-8c6e-1504cc147ddd.png)

**Comment by justinclift** [comment]
Hmmm, the icons could probably go a touch larger too.

**Comment by revolter** [comment]
Where is that "Install DB4S 3.9.0" coming from? Do you think we could/should change it to "Install DB Browser for SQLite"?

**Comment by justinclift** [comment]
Apparently it needs to be 27 characters or less.

Which is weird, as create-dmg doesn't have that limit.  I'll see if I can figure out a workaround, as we only need 29 chars. :smile:

**Comment by justinclift** [comment]
Ahhh, that's why create-dmg was breaking.

We'll need to keep with 27 characters or less then.

**Comment by revolter** [comment]
Ok, we'll leave it that way

**Comment by justinclift** [comment]
Is this workable?
![screen shot 2016-08-03 at 20 02 29](https://cloud.githubusercontent.com/assets/406299/17378293/416e18b4-59b5-11e6-949b-ebafb43d3a43.png)

**Comment by justinclift** [comment]
If so, I'll attempt to create the 2X background next.

**Comment by justinclift** [comment]
@revolter Would you be ok to see if this installer seems retina friendly?

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite%203.9.0-installer_test2-2X.dmg

**Comment by revolter** [comment]
It looks like it is. But, firstly, I personally don't quite like the design. And secondly, the hidden folder is showing up:

![screen shot 2016-08-03 at 22 14 55](https://cloud.githubusercontent.com/assets/5748627/17378728/c982da02-59c7-11e6-8fca-4b6bd3ea397c.png)

**Comment by justinclift** [comment]
For you, does the hidden folder show up with the firefox installer?

**Comment by justinclift** [comment]
For the design itself, no worries.  Happy to use whatever background image, I'm not fussed.

Can you get a hold of a suitably licensed one for us to use? smile:

**Comment by revolter** [comment]
> For you, does the hidden folder show up with the firefox installer?

No. It moved them outside the window, and the scrollbars do appear as the `node-appdmg` said.

![screen shot 2016-08-03 at 22 22 34](https://cloud.githubusercontent.com/assets/5748627/17378972/e5813ad6-59c8-11e6-9f4b-8842e1767c37.png)

> Can you get a hold of a suitably licensed one for us to use? :smile:

I'm working on one now.

**Comment by justinclift** [comment]
k, position them below too then

**Comment by justinclift** [comment]
If you're trying with `node-appdmg`, this is the json file so far, including hidden icons moved down a bit:

```
{
  "title": "Install DB4S 3.9.0",
  "icon": "macapp.icns",
  "icon-size": 128,
  "background": "background-blue_arrow8.png",
  "background-color": "#8E8E8E",
  "contents": [
    { "x": 90, "y": 130, "type": "file", "path": "DB Browser for SQLite.app" },
    { "x": 395, "y": 125, "type": "link", "path": "/Applications" },
    { "x": 90, "y": 350, "type": "position", "path": ".background" },
    { "x": 240, "y": 350, "type": "position", "path": ".DS_Store" },
    { "x": 400, "y": 350, "type": "position", "path": ".VolumeIcon.icns" },
    { "x": 250, "y": 500, "type": "position", "path": ".Trashes" }
  ]
}
```

**Comment by revolter** [comment]
Shouldn't the hidden files have the same `y` and increasing `x`?

**Comment by justinclift** [comment]
This is how that json looks, with hidden files enabled:
![screen shot 2016-08-03 at 20 44 14](https://cloud.githubusercontent.com/assets/406299/17379611/218beb06-59bb-11e6-8d1a-4e76c2a8af3d.png)

**Comment by justinclift** [comment]
Guess this isn't any better?
![screen shot 2016-08-03 at 20 56 25](https://cloud.githubusercontent.com/assets/406299/17380008/cdbafb96-59bc-11e6-9d28-9fd406847986.png)

**Comment by revolter** [comment]
Are the hidden files moved?

**Comment by justinclift** [comment]
Yep.

**Comment by justinclift** [comment]
Updating the OSX nightly build script with @revolter's .json and [background image](https://github.com/sqlitebrowser/art-assets/tree/master/osx_install_backgrounds).

Manually version created for today:

* SQLite with JSON1 extension: http://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite_20160804.dmg
* SQLCipher: [in progress]

All the nightlies from here should automatically look the same way now. :smile:
