### ISSUE TITLE
Allow tab key to switch panes in the Hexedit view

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#694]
In the binary (qhexedit) view inside the Edit Database Cell, there doesn't seem to be any way to switch panes from the left to right sides.

It would be useful to capture the tab key (or something similar), to let the user switch which side they're editing in.

![screen shot 2016-08-01 at 18 17 41](https://cloud.githubusercontent.com/assets/406299/17302610/e74dbf16-5814-11e6-9ce1-ddcd6e2c928d.png)

**Comment by revolter** [comment]
I think that this would need a QHexEdit PR. Or a search for their API

**Comment by justinclift** [comment]
I'm not sure.  Kind of suspecting that the only reason it doesn't work at the moment, is that we capture the tab key for the window ourself.  It would surprise me if QHexEdit doesn't have this capability already.

Saying that because I've used command line hex editors before, and they (all?) support doing this.  So, I'm kind of expecting that QHexEdit does too. :smile:

**Comment by revolter** [comment]
Oh, ok. It makes sense.

**Comment by mgrojo** [comment]
It's working for me currently. It cycles outside, so for returning to hex view, Shift-Tab hast to be used. Maybe this can be closed now.

**Comment by justinclift** [comment]
Thanks @mgrojo.  This does work now.  From memory, @MKleusberg added this capability a while back.  I just didn't realise there was a matching issue that needed closing too. :wink:
