### ISSUE TITLE
Weird grey bar showing up underneath the filters line

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#696]
There's a weird grey line showing up here:

![screen-shot-2016-08-01-at-12 08 45](https://cloud.githubusercontent.com/assets/406299/17336758/80f49ed8-58d7-11e6-9265-964cb5bbc36c.png)

Hopefully not too hard to resolve.

**Comment by justinclift** [comment]
As something to look into for this, maybe QFontMetrics would help us calculate an optimal size, based on the header and filter fonts in use:

&nbsp; &nbsp; https://doc.qt.io/qt-4.8/qfontmetrics.html

**Comment by mgrojo** [comment]
Does this still happens? In Linux I've never seen it.

**Comment by justinclift** [comment]
Ahhhh no.  I've not noticed it for ages either, on any platform.

Good find @mgrojo.  Looking through old issues for things that can be closed is kind of like spelunking. :grin:
