### ISSUE TITLE
Prefetch block size direct input prevented.

### ISSUE THREAD

**Issue by bakercp** [sqlitebrowser/sqlitebrowser#700]
On version 3.8.0, OSX 10.11.6

In preferences -> database, manually entering a value into the "Prefetch block size" input does not work.  The only way to get a value to stay is to hold down the arrow key, which takes a very long time.

![preferences](https://cloud.githubusercontent.com/assets/300484/17383962/7d5ee77a-599e-11e6-9ad2-745fa877afba.png)

It is also possible to manipulate it with the keyboard via page up, page down, etc, but it is still slower than manually entering the desired value.

Thanks for a great project!

**Comment by revolter** [comment]
It's working for me :-?

**Comment by revolter** [comment]
@bakercp, Can you please test it in the [latest nightly][1]?

  [1]: http://nightlies.sqlitebrowser.org/osx/

**Comment by bakercp** [comment]
Hi @revolter thanks for the tip!  It seems to be working in the latest nightly.  In the last release I was finally able to get it working after checking and unchecking foreign keys.  I suspect it was just gui-related. Thanks!

**Comment by revolter** [comment]
@bakercp 👍
