### ISSUE TITLE
Change cell empty shortcut to use backspace beside delete

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#703]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem: ___

The keyboard shortcut for emptying a cell should be <kbd>alt</kbd> + <kbd>backspace</kbd> instead of <kbd>alt</kbd> + <kbd>delete</kbd>, as some (newer) Macbook models don't have the <kbd>delete</kbd> key.

### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___

### I'm using DB4S version:

- [ ] 3.7.0
- [ ] 3.8.0
- [x] Other: 3.9.0

### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Makes sense.  I should be able to get this done for 3.9.0.

**Comment by justinclift** [comment]
Fixed in #705.
