### ISSUE TITLE
Feature request: We should sign our official releases

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#711]
We should probably sign our official releases for OSX and Windows, to minimise potential weirdness that can arise from OS warnings about unknown software".

This kind of warning [popped up on Windows a while back](https://github.com/sqlitebrowser/sqlitebrowser/issues/284) (3.6.0v2 release), and at least one person has mentioned they have problems on OSX due to us not signing our application.

Useful relevant information here for OSX:

&nbsp; &nbsp; https://successfulsoftware.net/2014/10/17/signing-qt-applications-for-mac-os-x-10-9-5-and-10-10/

**Comment by glawrence** [comment]
You link to issue #284 is broken by the way

**Comment by justinclift** [comment]
Oops, thanks @glawrence. :smile:

**Comment by glawrence** [comment]
When I looked into this before I did find some free code signing certificates for open source projects, so [GlobalSign](https://www.globalsign.com/en/ssl/ssl-open-source/) for example. They have been doing so since June 2013. They also provide one certificate that work across platforms.

The other task is to but the code signing step into the build process and consider if the nightly builds need this.

**Comment by justinclift** [comment]
Cool, that's good info. :smile:

**Comment by justinclift** [comment]
Relevant reference info for Windows:

* https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx
* https://msdn.microsoft.com/en-us/library/ms537364(v=vs.85).aspx

GlobalSign page where MS Authenticode compatible certificates can be bought:

* https://www.globalsign.com/en/code-signing-certificate/

Although places are giving free SSL certificates to Open Source projects, there doesn't seem to be a similar offering in place for MS Authenticate cert's.

The screenshots here show than even signed files gets warning messages on them, it's only "EV" signed ones (~$US500/yr) which don't:

* https://stackoverflow.com/questions/21124634/ev-code-signing-certificate-or-code-signing-certificates-for-microsoft-authentic#24446908

That seems fairly scammy. 😦

**Comment by justinclift** [comment]
It seems like some "code signing certificates" can be used for both Windows & OSX signing.

&nbsp; &nbsp; https://www.sslshopper.com/cheap-code-signing-certificates.html

Choosing one of those might be useful.

**Comment by justinclift** [comment]
Cheapest option for signing on Windows so far seems to be US$84, through kSoftware:

&nbsp; &nbsp; http://codesigning.ksoftware.net

It's a US business, with a link to the US "Better Business Bureau" on their website, with no complaints.  So... might be workable.

**Comment by justinclift** [comment]
Certum has an "OpenSource Code Signing" thing:

&nbsp; &nbsp; http://www.certum.eu/certum/cert,offer_code_signing.xml

At first look, it seems cheap at 14 euro's.  It doesn't actually seem to do anything useful though, as their certificates aren't something which MS Authenticode can use.

Certum **does** offer Authenticode certificates... but they're ~200 euro.  Eg, it sounds like a scam for getting traffic 😦

**Comment by justinclift** [comment]
Useful info: http://www.tech-pro.net/code-signing-for-developers.html

**Comment by justinclift** [comment]
Certificates through [StartCom](https://startssl.com) seem to be the cheapest yet, at US$59.90.

Additionally, it seems the whole process can be done online.  Getting one through kSoftware would require finding a notary, getting my ID documents signed by them, etc.  eg a total pain in the butt (I live in remote UK). :wink:

**Comment by justinclift** [comment]
Just submitted documentation and paid through StartCom.  They still need to manually check things, so it might be a Monday thing as well.

**Comment by justinclift** [comment]
And now I find the link to [Outercurve](http://outercurve.org/whatwedo), who might have been able to sign our releases with their certificate.  Oh well. :wink:

**Comment by justinclift** [comment]
This post at the bottom of this seems to have a good step by step walk through for getting it done through StartCom.  Which is good, as StartCom's own docs... are almost non-existent:

&nbsp; &nbsp; https://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects

**Comment by justinclift** [comment]
Good news.  The Apple Developer staff work on weekends, and have fixed my account.

I've just renewed my OSX Developer membership, so in theory can sign our OSX releases now.

I'll try it out later on today, after investigating some more of our translation bits.

**Comment by justinclift** [comment]
It's taken some doing, but I **think** signing on OSX is working ok.

If anyone on OSX has a few minutes to try it, please grab this latest build (3.9.x series) and test if OSX throws up a warning when trying to run it:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.9.0-beta2.dmg

If it does... looks like I still have more stuff to figure out. :wink:

**Comment by justinclift** [comment]
The nightly build script for OSX has been updated with the signing pieces too, so (in theory) all of our OSX nightly builds should now "just work" without any "unsigned application" type of warning.

**Comment by revolter** [comment]
Following these steps:

- download and open beta 2 `.dmg`
- drag the `.app` to the `Downloads` folder
- open the `.app`

shows this alert:

![screen shot 2016-08-22 at 18 25 24](https://cloud.githubusercontent.com/assets/5748627/17860329/cae80426-6895-11e6-9bd3-8c2bc038b79e.png)

This is the alert that should have been gone, right? Could it be because I didn't move it to the `Applications` folder (though unlikely)?

**Comment by justinclift** [comment]
Nah, that's a different warning.  Not sure if that one's even possible to get rid of.

The warning being discussed here is the "Gatekeeper" one, whose settings are controlled through *OSX System Preferences → Security*.

Most people seem to change it to "Mac App Store and identified developers", which should make the warning go away for signed applications:
![screen shot 2016-08-22 at 16 32 37](https://cloud.githubusercontent.com/assets/406299/17860674/1fbfa02c-6886-11e6-863b-39216047e816.png)
When an unsigned application runs, it gets blocked and this warning pops up:
![screen shot 2016-08-22 at 16 34 45](https://cloud.githubusercontent.com/assets/406299/17860827/b04f3e9a-6886-11e6-8a05-6e148b308662.png)
(that's from an older nightly, before they were automatically signed)

**Comment by justinclift** [comment]
Ugh.  I just tried out last night's nightly build.  There does seem to be something wrong with it anyway.  The .app icon is wrong for starters, and the security certificate doesn't seem ok.

It's probably a good thing that the logs for the nightlies are keep.  Will investigate soon. :smile:

**Comment by justinclift** [comment]
So, StartCom are not that good.  The person doing the "verification" step has a script to follow, and that script **requires** me to submit a utility bill showing my phone number.

Problem is... none of mine do.  I don't like phones, and the area I live in has no mobile service.

Bit of an impasse.  I've asked them to reach out to their CEO, Eddy Nigg, to intervene.  He's been active on the Mozilla mailing lists previously, so he may be able to help (there are people in common we both know, who may be able to vouch for me).

Unlikely to have a result before tomorrow though.

**Comment by justinclift** [comment]
Ok, I think the nightly OSX builds are fixed now.  It turns out Debug mode builds don't include the icon.  Couldn't find a way to adjust that, so the nightlies are back to using Release mode.

The signing problem seems due to a problem with the way I'd constructed the keychain (where certificates are stored).  Moved the certificate to the system keychain... which (in theory) should work.  We can check tomorrow to verify that theory == reality in this case. :smile:

**Comment by revolter** [comment]
It looks like I already had that setting selected instead of `Anywhere`. Tested it with `3.8.0` and it blocked it, and with beta 2 and it opened it correctly.

**Comment by justinclift** [comment]
StartCom have ok'd my validation, so going through the code signing learning experience for Windows now. :wink:

**Comment by justinclift** [comment]
With some assistance from the StartCom online chat staff, it's done. :smile:

Closing this now as both Windows (Win64+Win32) and OSX releases will be signed from here on.

**Comment by justinclift** [comment]
StartCom is in hot water: https://news.ycombinator.com/item?id=12582534

Our already issued certificate(s) will still work, if/when we need stuff from them in future there could be problems.
