### ISSUE TITLE
Feature request: hex editor width should update automatically

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#714]
A useful enhancement we should consider, is to have the hex editor resize its width automatically whenever the user resizes the Edit Cell window.

At present, the hex editor view uses a fixed size which looks weird and leaves a lot of it's space unused:

![screen shot 2016-08-07 at 20 30 00](https://cloud.githubusercontent.com/assets/406299/17464726/fa052aae-5cdd-11e6-8583-feb416a8da50.png)

**Comment by revolter** [comment]
Don't hex editors alhave a fixed number of columns? Not accustomed with them, so I'm just asking. Is it ok to, for example, display all the bytes(?) on one line?

**Comment by justinclift** [comment]
Good point.  Hadn't thought of that. :smile:
