### ISSUE TITLE
DB4S changes writedate of a file - even if nothing is saved

### ISSUE THREAD

**Issue by zwrmueller** [sqlitebrowser/sqlitebrowser#717]
### Details for the issue

as topic says. My procedure:
* opening the database
* fireing an sql-statement updating the table
* browsing the table
* leaving the database without saving

Unfortunately DB4S is changing the writedate of the db file, despite saying "don't save".

I could understand if it is changing the accessdate, and leaving creationdate and writedate untouched.

Regards
 Ralf

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.7.0
- [x] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, that's an interesting observation. :smile:

It's **probably** because opening the database (using the SQLite library) does several setup and housekeeping type operations on the database, including creating temporary journaling files (and more).

From the database's point of view, it doesn't know ahead of time that no data will be changed.  So, it just does all the setup needed as if it will be.

If keeping the database completely unchanged is important to you, setting the "Read Only" property on the database file (eg using Windows Explorer) should work.  We added some code ages ago to work with "Read Only" databases (as set by the file system).

Does any of the above help? :smile:

**Comment by zwrmueller** [comment]
> Does any of the above help? 

Yes and No. You know, just peeking into the file, doing some SQL and leaving without saving is expected to leave the database timestamp unchanged - but is does not. Thus the timestamp of the file couldn't be used as an original information anymore. That's sad. I can remember that EXCEL has some issues here too. 

If you exactly know of the programs behaviour you can workaround as you wrote. But I'm human and I won't take into account each and every programs oddities to do workarounds - I just wanne go ahead with reasonable thinking.

Well, if I cannot argue the developers to alter the behaviour I have to live with it or ... using the workaround.

So, thanks for the workaround ;-)
 Ralf

**Comment by justinclift** [comment]
No worries. :smile:

Are we ok to close this issue?

**Comment by zwrmueller** [comment]
if there is no chance of a quick fix of the program - as of saving timestamps and reset them at closing the database without being saved - well, than we can close this issue.

Surely it is not the biggest point out here.

**Comment by justinclift** [comment]
Well... we *could* reset the timestamp of the file after access, but (sorry) it's probably a bad idea.

The SQLite library may have done other housekeeping tasks on the file meanwhile, and if we reset the timestamp then the file will appear as if it's been untouched (from a timestamp point of view).  Even though that's not really the case.

Personally, I can imagine some people being pretty annoyed with us :rage: if we reset the timestamp back to the original one, even when the file has been modified internally.

So... it's better if we skip that, at least for now. :smile:

**Comment by zwrmueller** [comment]
I thought it could be bad for other reasons.

So I'm fine with the workaround, at least for now ;-)
