### ISSUE TITLE
SqliteTableModel::getForeignKeyClause don't work properly if FK column has 0 index

### ISSUE THREAD

**Issue by schdub** [sqlitebrowser/sqlitebrowser#718]
Hello.

In "Browse Data" tab, for FK's with 0 index not work:
- tooltip with text "References %1 (%2)...";
- Ctrl + Shift + Left Mouse Click.

Possible solution sqlitetablemodel.cpp, 261

    if (column >= 0 && column < obj.table.fields().count())

instead

    if (column > 0 && column < obj.table.fields().count())

**Comment by justinclift** [comment]
Thanks @schdub, I'll look into it now. :smile:

**Comment by justinclift** [comment]
With:

```
for FK's with 0 index
```

I'm having a bit of trouble understanding that. :wink:

The concept of a foreign key with "0 index" is confusing me.

Would you be ok to take a screenshot of the database structure or similar, so I can see what you mean?  Maybe if the database file itself has no sensitive data, email it to me and I'll try it that way? :smile:

**Comment by schdub** [comment]
1) import tables from .sql file:
[kuban.db.sql.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/411587/kuban.db.sql.zip)
2) open Browse Data tab and select level table;
3) column place_id - it's Foreing Key to place(id) key;
4) try to jump to place table using Ctrl + shift+Click or try to wait tooltip with "References %1(%2).." text - none of this happens.

**Comment by justinclift** [comment]
Thanks @schdub, I can see the problem now. :smile:

**Comment by justinclift** [comment]
Sorry for the delay with this.  Today I've been learning about Qt's Model/View, which I want to understand properly before debugging through the `sqlitetablemodel.cpp` code. :wink:

**Comment by MKleusberg** [comment]
Thanks for reporting this, @schdub I've just pushed the fix you've proposed. Can you test the next nightly build and report back if you find any remaining problems with this?

**Comment by justinclift** [comment]
@schdub ping? :smile:

**Comment by schdub** [comment]
@MKleusberg, @justinclift seems to be working as expected. Sorry for late reply.

**Comment by justinclift** [comment]
Thanks @schdub, that really helps. :smile:

I'll pull this into the v3.9.x branch now too.

**Comment by justinclift** [comment]
Done. :smile:
