### ISSUE TITLE
The "Import CSV" dialog doesn't always display the preview

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#720]
### Details for the issue

With DB4S git master (b7be134 as of 10th 2016), the "Import CSV" dialog isn't always displaying the preview image correctly.

This happens with at least when DB4S is using the Russian language, though it may also happen for other languages too (not yet tested).
![d2d3dd00-5f16-11e6-88b2-f091fd9e6ee7](https://cloud.githubusercontent.com/assets/406299/17561165/b0a747ac-5f1c-11e6-90f2-1769c5a9eda9.png)

**Comment by justinclift** [comment]
As a data point, the [CSV RFC](https://tools.ietf.org/html/rfc4180) doesn't define a way to encode binary data.

Wonder what it would take to create a follow up RFC, filling in some of these edge cases we've noticed are missing:

* encoding of binary data (eg probably base64 encode it)
* clearly establish NULL vs "no value provided for this field" (so use the default value): https://github.com/sqlitebrowser/sqlitebrowser/issues/195#issuecomment-78546221

**Comment by MKleusberg** [comment]
Hmm, any update on this? I can't reproduce it with just any CSV file and setting DB4S to Russian.

Not sure about the PNG file either. We probably can't do much about it...

**Comment by justinclift** [comment]
Good news.  The blank preview no longer happens. :smile:

The preview does show a few fields... but has a heart attack (multi-second UI lockup, recurring every few seconds) with the CSV which triggers this.  It's an export of a table with a few PNG's in it, so they have binary data in them.

Not sure if we should be expecting to handle that ok, or if we should detect binary data and abort with a warning.

How feasible do you reckon it would be to detect the problem and do the abort?  Can email the .csv to you if that's useful. (?)

**Comment by MKleusberg** [comment]
Cool, good to hear that the missing preview issue is gone :smile:

As for the other issue: I've just pushed a commit that fixes the sluggish UI by limiting the length of the cell contents in the preview table. Importing binary data also seems to work way better than expected, so I would leave it as is. Exporting binary data to CSV seems to be pretty broken but we'll have to see if it's worth fixing.

**Comment by justinclift** [comment]
Awesome, this is definitely all fixed.  Tested the problem CSV file, and the preview works fast/well even with fields containing images.  Fantastic @MKleusberg. :smile:
