### ISSUE TITLE
Non-OSX key combination are displayed in tooltips on OSX

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#721]
It turns out that some key combinations are displayed via our tooltips.

However, they're not displaying the correct key combination on OSX, instead showing the Windows/Linux key combo.  For example, in [sqlitetablemodel.cpp](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/sqlitetablemodel.cpp#L249):

```
return tr("References %1(%2)\nHold Ctrl+Shift and click to jump there")
  .arg(fk.table()).arg(fk.columns().join(","));
```

This should be reasonably simple to fix using something like `#ifdef Q_OS_MAC` or `#ifndef Q_OS_MAC`, such that the correct key combination is shown for each OS.

**Comment by justinclift** [comment]
Code which seems to have this problem:

* [tr("References %1(%2)\nHold Ctrl+Shift and click to jump there")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/sqlitetablemodel.cpp#L249)
* [tr("Ctrl+Return")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L113)
* [tr("Ctrl+L")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L157)
* [tr("Ctrl+P")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L164)
* [tr("Ctrl+D")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L164)
* [tr("Ctrl+I")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L170)
* [tr("Ctrl+E")](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L178)

Additionally, these seem to both have the problem, and be missing `tr()` around them:

* ["Ctrl+R"](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L116)
* ["Ctrl+\""](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.cpp#L152)

There are two occurrences in `MainWindow.ui` as well.  They may need to be set through code, instead of directly in the .ui file:

* [<string>Execute SQL [F5, Ctrl+Return]</string>](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.ui#L1637)
* [<string>Execute current line [Ctrl+E]</string>](https://github.com/sqlitebrowser/sqlitebrowser/blob/538116c97b9dab60908199b82d4e58a3f8f757ac/src/MainWindow.ui#L1682)

**Comment by chrisjlocke** [comment]
Wasn't it mentioned in some other thread/topic/issue/branch/sub thing about customising shortcut keys, etc?  If so, shouldn't the message be more 'generic' on its 'push the blah blah key' rather than specific?  Surely its bloating the code by adding in superfluous code 'if its this OS, do this, otherwise do that', etc...

Just my 2p's worth....

**Comment by justinclift** [comment]
Yeah, I know the Issue you mean, but can't find the number for it at the moment.  It's the issue raising the idea of moving all of the shortcut assignment keys out of the .ui files, and into a common piece of code.  Then we could add a tab to the preferences dialog box, so users can customise the key mapping to what they want.

And yeah, this would probably tie in with that.  Or get superceded by it. :smile:

**Comment by chrisjlocke** [comment]
Aah, #682 be the jobbie...

**Comment by justinclift** [comment]
Thanks @chrisjlocke. :smile:

**Comment by mgrojo** [comment]
The first case was already solved in #1539, which is now closed. The cases in ui files are pending as already explained there.

**Comment by mgrojo** [comment]
@justinclift This should be fixed now. Could you take a look, when you have a chance, to how is it working under OSX?

**Comment by mgrojo** [comment]
@ThinkDigitalRepair You might also be interested. This correction will be in [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/).

**Comment by justinclift** [comment]
Just tried it out with the nightly build from a few hours ago.  Looks well done to me. :smile:

![db4s-issue_721-screenshot1](https://user-images.githubusercontent.com/406299/49694023-1fce7f80-fbd6-11e8-9a55-8e04e8546bb4.png)
![db4s-issue_721-screenshot2](https://user-images.githubusercontent.com/406299/49694024-20671600-fbd6-11e8-8bb4-4e0424629d6c.png)
![db4s-issue_721-screenshot3](https://user-images.githubusercontent.com/406299/49694025-20671600-fbd6-11e8-86ef-d118157735bf.png)
![db4s-issue_721-screenshot4](https://user-images.githubusercontent.com/406299/49694026-20ffac80-fbd6-11e8-91a1-cbb632906808.png)
![db4s-issue_721-screenshot5](https://user-images.githubusercontent.com/406299/49694027-20ffac80-fbd6-11e8-8df6-d7fac5d085b6.png)
![db4s-issue_721-screenshot6](https://user-images.githubusercontent.com/406299/49694029-21984300-fbd6-11e8-9fdf-9bd8e533247d.png)
![db4s-issue_721-screenshot7](https://user-images.githubusercontent.com/406299/49694030-21984300-fbd6-11e8-998e-0f34a11f0655.png)

Really good stuff @mgrojo!
