### ISSUE TITLE
Grid view not refreshing when schema changed

### ISSUE THREAD

**Issue by kimbar** [sqlitebrowser/sqlitebrowser#725]
### Details for the issue

Reproduction (it should be reproducible w/o Python, but that's what I exactly did):

1. In Python (2.7, 32-bit):
```
import sqlite3 as db
dbcon = db.connect("base.db")
dbcur = dbcon.cursor()
dbcur.execute("DROP TABLE IF EXISTS people")
dbcur.execute("""
    CREATE TABLE `people` (
        `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        `name` TEXT NOT NULL,
        `member` INTEGER DEFAULT 0
    )""")
dbcur.execute("""
    INSERT INTO people VALUES (NULL, 'John Appleseed', 0)
""")
dbcon.commit()
```
\2. Open ``base.db`` in SQLiteBrowser
\3. Switch to "Browse Data" tab
\4. In Python:
```
...
dbcur.execute("""
    CREATE TABLE `people` (
        `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        `name` TEXT NOT NULL,
        `rank` INTEGER,
        `member` INTEGER DEFAULT 0
    )""")
dbcur.execute("""
    INSERT INTO people VALUES (NULL, 'John Appleseed', 100, 0)
""")
...
```
\5. Hit refresh button in "Browse Data"

Result: Table "people" has 3 attributes, and John's membership flag is "100"
Expected: Table "people" has 4 attributes, and John's rank is "100"

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.7.0
- [x] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, interesting.

Would you be ok to try the latest nightly build?  It has a __bunch__ of bug fixes in it, some of which affect things like this.  There's a good chance this is already fixed in that. :smile:

As a side thought... are you using the 32-bit or 64-bit build on Windows?  Asking because I'm creating the Windows packages for our "3.9.0 beta1" release today.  If you have time to test for the bug in that, it would be nifty. 😁

**Comment by kimbar** [comment]
I'm using 64-bit build in Windows 10. BTW, the thing gets refreshed if I switch to the "Database Structure" tab and back (so it seems that data are queried but schema is not). I'm on to check the nightly build.

**Comment by justinclift** [comment]
Interesting about the schema.  Not sure we've done any fixes in that area of code, so it might still be present. 😦

**Comment by justinclift** [comment]
Btw, with `4.` above, what drops the table before it gets re-created?

**Comment by justinclift** [comment]
Oh, I guess that's what you're meaning with `...`.  Didn't realise. :wink:

**Comment by revolter** [comment]
It's possible that `Refresh Data` only refreshes the ... data 😄

**Comment by kimbar** [comment]
Behaviour as expected in 3.9.99. :) Over and out, waiting for the release (Thanks, for this tool a lot!).

**Comment by justinclift** [comment]
@kimbar With "Behaviour as expected"... is that "bug still present" or "bug is fixed"? :wink:

**Comment by kimbar** [comment]
I've tried to be as military as I could (y'know witch their "positive" and "affirmative"), haha. It's not present, the table has 4 columns.

**Comment by revolter** [comment]
Clearly the bug is fixed. Remembered I had the same problem: #496

**Comment by justinclift** [comment]
Awesome, thanks guys. :smile:
