### ISSUE TITLE
"Set as NULL" button doesn't work in text editor

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#726]
@innermous pointed out on Gitter that at the "Set as NULL" button isn't working in text mode.

It seems to just be clearing the value to an empty text string.

**Comment by innermous** [comment]
As I already said, it's not bug at all. Text can't be NULL. Only thing you can do - sync data between hex and text and update cell from hex when *Apply* is pressed. Because hex mode respects nulls. Not sure if empty strings will be available in that case.

**Comment by justinclift** [comment]
Heh Heh Heh

From a user's perspective, this is definitely a bug.  It is because - for a user - "Set as NULL" should not care which view mode we are in.  It should set the _cell data_ to NULL.

I have a different idea for how to "fix" this (from user perspective).  You probably won't like my code for it though. 😁

**Comment by innermous** [comment]
@justinclift but still. Editor widget doesn't make changes until we press  Apply and changes are based on editor. Which can't hold null(in case it's text editor)

**Comment by justinclift** [comment]
47b1224 fixes the problem using a class variable to track the NULL state for the text editor.  Seems to work ok. :smile:
