### ISSUE TITLE
Arabic flag icon missing from Language drop down on Windows

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#728]
With the new 3.9.0 beta 1 release, the Arabic flag icon is missing from the Language drop down in the Preferences dialog:
![missingarabicflag](https://cloud.githubusercontent.com/assets/406299/17647683/a7cc0ddc-61f3-11e6-8fdd-f7e404baa523.png)

**Comment by justinclift** [comment]
It may be this [line](https://github.com/sqlitebrowser/sqlitebrowser/blob/b1fb9391114244cee004c2da4602f5b80dea303e/src/translations/flags/flags.qrc#L3) needs updating.

I'll build with it on windows again shortly, and find out.

**Comment by innermous** [comment]
I have deja vu. I already fixed this issue before and sent patch to arabic translator.

**Comment by justinclift** [comment]
Ahhh, that's why it sounded familiar. :smile:

**Comment by justinclift** [comment]
Do you have the fix around still?

I just tried setting the language in flags.qrc to "ar" instead of "ar_SA", but that didn't work.

**Comment by justinclift** [comment]
As a test, I renamed `sqlb_ar.ts` to `sqlb_ar_SA.ts`, then changed all of the references in our source to use that.

The flag loads properly on windows with that change.

However, I suspect "ar_SA" may not be correct.

@SafaAlfulaij Any ideas?

**Comment by justinclift** [comment]
As a temporary fix for now, the language file has been renamed from `sqlb_ar.ts` to `sqlb_ar_SA.ts` in https://github.com/sqlitebrowser/sqlitebrowser/commit/c6121c8d6439853ebef2b1281adb52ef427ada84.
