### ISSUE TITLE
Windows dev setup pages need updating with new pathnames

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#729]
At present, our Windows developer setup guide uses path names which aren't great for making both Win32/Win64 builds from the same desktop. eg:
- SQLite being installed into `C:\dev\SQLite` rather than `C:\dev\SQLite-Win64`

I've been making changes in the DB4S source (`v3.9.x` branch only) enabling both Win32 and Win64 building, and needed to change some of the paths.

The wiki pages which refer to them will need updating to match.

**Comment by justinclift** [comment]
Moving this to the next release target, as it wasn't done in time for 3.9.0.

**Comment by justinclift** [comment]
@chrisjlocke This is done now isn't it? :smile:

**Comment by chrisjlocke** [comment]
Surely is.  🚯 😋 
Documentation and screenshots updated.  The DOS screenshots look a bit pants* as they've been more doctored than redone, but I can redo them again.  
*No-one will notice.... much! ;)

**Comment by justinclift** [comment]
Awesome, thanks @chrisjlocke. 😁
