### ISSUE TITLE
Ctrl+E doesn't work in 'Execute SQL' window in Beta

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#732]
### Details for the issue

Just using the Beta testing it with CRLFs, so using it to build a new database.  Noticed in the 'Execute SQL' dialog, pressing Ctrl+E didn't execute the current line.  Pressing the 'Execute current line' button did work.
The nightlies don't have this 'feature'.

Edit: I apologise - I lied.  The latest nightly DOES have this issue.  Certainly the one from 15 Jul didn't have it.  I've newer versions at home, so can't pinpoint now an exact 'it happened then' date.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0 beta1
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh yeah, good point.  We need to figure out a new key combination for that, as Ctrl-E is now used for toggling on/off the Edit Cell dock.

Open to suggestions, as I'm not sure there are any good solutions here.  All the obviously associated letters are already mapped to other things.

Maybe one of the F<something> keys if it's free. (unsure, I haven't checked)

**Comment by chrisjlocke** [comment]
If F5 is run the whole thing, couldn't it be Ctrl+F5?  Shift+F5?

**Comment by justinclift** [comment]
Ahhh yeah, that's a good idea. :smile:

**Comment by justinclift** [comment]
Btw, the commit that grabbed control of Ctrl-E for the Edit Cell is this one: https://github.com/sqlitebrowser/sqlitebrowser/commit/21ad12cba89e841e0b839bba2c039dae23c784cd

**Comment by justinclift** [comment]
@chrisjlocke In theory, this should be fixed in the master branch by https://github.com/sqlitebrowser/sqlitebrowser/commit/e9063235f954b0f4328d2549e6087e50a4915cc2, and also in 3.9.0 by a corresponding commit there.

Just to be on the safe side, would you be ok to try the nightly build tomorrow, and verify it from your point of view? :smile:

**Comment by justinclift** [comment]
@chrisjlocke This worked for you yeah?

**Comment by chrisjlocke** [comment]
Works perfectly, and a Shift+F5 seems more logical than Ctrl+E, so win win all round!
Thanks for the prompt fix.

**Comment by justinclift** [comment]
Completely welcome @chrisjlocke. It turned out to be a super easy fix. :smile:
