### ISSUE TITLE
Inconsistent backslashes in Windows files

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#735]
### Details for the issue

When opening files on the C drive, backslashes are changed to forward slashes, but on the D drive, backslashes are maintained.

After using DB4S for a while now, I've kinda gotten used to files having forward slashes - guessed it was part of the 'cross OS' style-ness of the program.  However, tonight I realised it was only doing it for certain files?

![image](https://cloud.githubusercontent.com/assets/7872218/17791684/6619e93c-6594-11e6-960a-f8a5187f4ef8.png)

![image](https://cloud.githubusercontent.com/assets/7872218/17791697/782bda18-6594-11e6-9d5b-1f5df69297f4.png)

![image](https://cloud.githubusercontent.com/assets/7872218/17791710/8cd067d6-6594-11e6-9b40-7d6e47d35283.png)

Just wondered if this 'inconsistency' was a bug more than a quirk....
It is only a cosmetic thing, and has no impact on the program.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.0 beta1
- [x] 3.8.0
- [x] Other: 3.8.99 (nightlies)___
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Actually, just thought and realised the ones on the C drive have been created and opened, while the ones on the D drive have been created previously, so just opened.  Its still a bug/issue ... albeit a very very minor cosmetic one! :wink:

**Comment by justinclift** [comment]
With the back and forward slashes, is that just in the "Recent Files" list thing?

**Comment by chrisjlocke** [comment]
And in the main caption of the window (as per the 2nd and 3rd screenshots...) 
It has no performance/program knock-on affects, but is just 'odd' when you look at it.  I guess its just some parsing done in one part thats squiffy.  (Thats a technical term just below 'bug', but I don't think you have a label for that!)

**Comment by justinclift** [comment]
Heh Heh Heh

Ahhh yeah, I use "wonky".  Same kind of thing. 😁 

With the first screenshot, it should be fairly trivial to fix.  If we throw in a regex or similar to replace slashes in the filename string with the correct one for the platform, I *think* that would do the trick:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L1240-L1241

Updating the window title will probably use the same regex, applying it to the filename here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L1257-L1262

**Comment by chrisjlocke** [comment]
Interesting snippet of code there.

// Add shortcut for opening the file using the keyboard. However, if the
application is configured to store
// more than nine recently opened files don't set shortcuts for the later
ones which wouldn't be single digit anymore.
if(i < 9)
recentFileActs[i]->setShortcut(QKeySequence(Qt::CTRL + (Qt::Key_1+i)));


... surely that should be if(i<10)....   or if(i<=9).......     as the
ninth entry isn't being shortcutted.

I can't test it, as my proggy only goes up to 5.

[image: Inline image 1]


Unsure how to set that higher....

**Comment by justinclift** [comment]
That's a good first though.

Looking at the initialisation for `i` though, it's [starting out at 0](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L1240).  So`<=9` would be 10 values, which would be too many.

**Comment by chrisjlocke** [comment]
Doh.  Didn't look at that.  Oops.

**Comment by justinclift** [comment]
You're trying, that's the important thing. :smile:

**Comment by chrisjlocke** [comment]
Thats what my wife says.  I'm very trying...  I'm not too sure its a compliment when she says it... :wink:

**Comment by justinclift** [comment]
@MKleusberg Do you have a few moments to knock together a quick patch to use the correct platform specific slashes?

Pretty sure this'll be super easy. :smile:

**Comment by MKleusberg** [comment]
@justinclift I can try :smiley:

@chrisjlocke Can you try the new commit I have just pushed? It's completely untested because I don't have a Windows system, so I'm wondering if it does the job :wink:

**Comment by justinclift** [comment]
@chrisjlocke Ping? 😁

**Comment by chrisjlocke** [comment]
The file list history now has the correct backslashes (didn't before), but the window caption doesn't.

![image](https://cloud.githubusercontent.com/assets/7872218/25742568/eff1e3de-3187-11e7-8241-9518ad5ea836.png)

**Comment by MKleusberg** [comment]
Thanks! Should be fixed with the last commit :smiley:

**Comment by MKleusberg** [comment]
@chrisjlocke Is it working for you? :smiley:

**Comment by chrisjlocke** [comment]
Working brilliantly now, thank you!  🍨
