### ISSUE TITLE
Preferences not being stored on macOS Sierra

### ISSUE THREAD

**Issue by MarqueIV** [sqlitebrowser/sqlitebrowser#737]
### Details for the issue

When running SQLiteBrowser (now renamed to DB Browser for SQLite) on macOS Sierra beta, because the app is unsigned, it can not find its preferences file and as such, the colors in the data browser tab are all black, meaning black text on black background.  Even if you change them, while they will work for that session, closing and reopening the app resets all of your settings.

My suspicion is this has to do with the new way macOS Sierra handles unsigned applications.  It stores them in a 'random, secure' portion on disk, not simply the application folder even though it _looks_ like that's where it is.  This is part of their new security.  My guess is this is the cause of the app not being able to find the preferences.

That said, even if the preference file isn't found, the defaults should not be black on black.  At least set them to black on white, possibly making nulls gray on white.

All of the above is also pure speculation and I could be completely wrong, but I am not seeing this behavior on earlier versions of OS X, including El Capitan, only macOS Sierra.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.0 beta1
- [x] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @MarqueIV, that's a very timely report. :smile:

We have an open ToDo list item for signing our [releases](https://github.com/sqlitebrowser/sqlitebrowser/issues/711), but weren't thinking to get it done just yet.

Sounds like it should be a higher priority then.  I'll spend some time looking into it today/tomorrow, and see if it's possible to get tomorrow's release signed in time.

For macOS Sierra itself... might be time to get my Apple Dev Membership renewed, and start looking through the beta too.  Not sure when though. :wink:

**Comment by MarqueIV** [comment]
The good news is macOS Beta is now open to everyone, even without the developer network.  Even so, your product has greatly improved my development environment so I would be more than happy to help you with testing, signed or unsigned. Let me know. I don't mind installing out for test builds.

Feel free to reach out to me directly too.  234-248-6275 or Mark@MarkDonohoe.com

Hope I can help!

Mark

[Sent from my... wait... does anyone really read this part?!?]

**Comment by justinclift** [comment]
Thanks Mark. :smile:

It looks like the Apple Developer staff work on weekends, and they just sorted out the paperwork for that side of things.  Now.. reading time. :smile:

**Comment by justinclift** [comment]
It's taken some doing, but I **think** signing on OSX is working ok now.

@MarqueIV If you have a few minutes to try it, please grab this latest build (3.9.x series) and test if OSX throws up a warning when trying to run it:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.9.0-beta2.dmg

In theory the signature is all good, OSX is happy, etc.  But... would prefer some people (other than me) test it first, just to be on the safe side. :smile:

**Comment by justinclift** [comment]
@MarqueIV Tested the latest nightly build on macOS Sierra (newly installed "Version 10.12 Beta (16A239m)") just now:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite-sqlcipher_20160822.dmg

Two fairly concerning problems show up immediately, though both seem more like bugs with Sierra.

When trying to mount the .dmg on Sierra through Finder, it claims the .dmg is damaged and should be moved to the trash.  The .dmg is actually fine, as mounting it from the command line poses no issue:

```
$ hdiutil attach DB\ Browser\ for\ SQLite-sqlcipher_20160822.dmg 
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $252B40D3
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $61E08442
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $303E3D74
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
..................................................................................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $22F28C10
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $303E3D74
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $61F46220
verified   CRC32 $96EB1D9F
/dev/disk1          	GUID_partition_scheme          	
/dev/disk1s1        	Apple_HFS                      	/Volumes/Install DB4S Nightly build
```

After dragging and dropping the DB4S icon to Applications... DB4S refuses to start, claiming it's damaged.  Again, this is just plain wrong, as launching it directly from the command line works fine:

```
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite
[the application starts fine, seems to work ok, and preferences are stored between runs]
```

It's signature seems ok too:

```
$ codesign --verify --verbose /Applications/DB\ Browser\ for\ SQLite.app
/Applications/DB Browser for SQLite.app: valid on disk
/Applications/DB Browser for SQLite.app: satisfies its Designated Requirement
```

Judging by Sierra's flat out inaccuracy above... it might be best to wait for a few more betas... :wink:

Note - I haven't tried with any of the older, unsigned builds.  It's completely possible they'll have different behaviour.

**Comment by justinclift** [comment]
Hmmm, Sierra is saying there is a new update available (Beta 7).  I'll give that a try too, just in case it fixes the bugs seen above.

**Comment by MarqueIV** [comment]
Yeah, just came out today I think.  I'm installing it on my machine too if you want another tester.

[Sent from my iPad Pro]

**Comment by MarqueIV** [comment]
The DMG worked fine for me. As for the app, it worked after I disabled the security prompt.

Even so, there was another issue... if you say 'run it this time' from sys prefs security, it doesn't actually open but instead prompts you again. You have to completely disable the security, run the app, then reenable.

My guess is you're using a boot strap mech which would cause that as the boot strapped part runs, but then the main app gets blocked.  But that's purely a guess.

Again, disabling it temporarily solves the issue.

One thing though, signing, sierra and the rest aside, you should still change the defaults to black on white instead of black on black when prefs aren't found.  At least it's a temporary work-around rather than making a user have to change it every start as I do now.  Of course this goes away with signing, but still... it's a good practice regardless.

[Sent from my iPad Pro]

**Comment by MarqueIV** [comment]
Crap! Missed this.  I'll test when I'm back on my machine in about an hour.

[Sent from my iPad Pro]

**Comment by MarqueIV** [comment]
Just a quick update... both the beta 2 and nightly open fine here on my desktop running El Capitan.  No security prompts anymore so it's recognized as being signed.

I'm currently installing the latest beta (Sierra 7) on my notebook and will let you know what happens there.

**Comment by MarqueIV** [comment]
FYI... 3.9.99, the nightly doesn't properly browse data.  It's not returning all records.  I'm seeing paging controls but they don't seem to work either.  Note, this is still on El Cap.

**Comment by justinclift** [comment]
Thanks, @MarqueIV. :smile:

It's interesting about the 3.9.99 nightly build not properly browsing data.

Something like that happened on my system a while back.  eg In a database with 140,000+ records... The Browse Data tab would only show (say) up to the ~18,000th one using the slider and/or the controls.  Literally no way to see all of the data. 😦 

That wasn't happening for anyone else though, so I thought it was just something on my system.

From memory, when building using um... Qt4 I think... that problem went away.

I'll look into it again.  It might be another Qt4/Qt5 difference we need to solve before switching to Qt5-only.

**Comment by MarqueIV** [comment]
If it matters, this is a relatively small dataset.  It’s the NJ Transit train times.  Definitely not 100K+ records.  The largest table is 44K but most are < 5K

BTW, even in 3.9.00 and even 3.8 the paging controls seem to be doing odd things.  For instance, right now on my browse data tab, it says 1-11 of 229.  If I hit the ‘next page’ button (the right arrow without the line) it now says 91-101 of 229 (it jumped by 90) but if I press it a third time, it now says 191-201 (it jumped by 100).  I would think one would expect it to jump by 11 in all cases since that’s what’s shown, but if the intent was to always make it jump by 100, as stated, it’s not doing that either.  At least not for the first one.

No biggie as I just scroll anyway, but still...

HTH,

M

**Comment by justinclift** [comment]
Interesting.  Sounds like the code around this needs a bit of love and attention.

Will take a look in a few days. :smile:

**Comment by justinclift** [comment]
Found the reason for the weird error with Sierra claiming the .dmg and .app were damaged.  It's because Sophos anti-virus was installed prior to the upgrade.  Seems like it doesn't work with Sierra (or at least doesn't survive the upgrade process), but leave enough of it's remnants behind to break application launching.

After redoing the upgrade without Sophos, that problem has gone away.  The signed version of DB4S seems happy too.

Haven't investigated the default preferences yet, not tried out the newer "beta 7".  Will probably do so later on today.

**Comment by justinclift** [comment]
Not sure what the root cause is yet, but the problem of all data not being shown does go away when building with Qt4.

We'll probably build this release with Qt4 then, and figure out the cause/fix afterwards.

**Comment by justinclift** [comment]
As a data point, this bug with all of the data not being shown isn't happening on Win64.

Seems like it might really be an OSX-only bug. 😦

**Comment by justinclift** [comment]
@MarqueIV Would you have time to test this?

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.9.0-beta3.dmg

That one should allow you to see all of the data.  The only real change is that it's using Qt4 instead of Qt5.

But, Qt4 is "good enough" for the moment.  We'll do the switch to Qt5 when all of the potential issues are resolved.

**Comment by MarqueIV** [comment]
Just tried it.  While I can now browse all the data in the table, it still has that wonky paging behavior I spoke about earlier.

Oh... and the preferences issue is still there.  Here's what I see when I close, then reopen, then go right to browsing data...

![image](https://cloud.githubusercontent.com/assets/897883/17920618/a07dcc70-69a3-11e6-95eb-6ef112923287.png)

**Comment by justinclift** [comment]
@MarqueIV Ouch.  Yeah, that doesn't look great.

I'll look through our preferences code now, to see if something obvious jumps out.  Otherwise, this will have to be figured out at a later time.  It sounds like a Sierra-only bug, and may not be affecting everyone.

With your Sierra setup, is it a VM, or physical hardware, or ?

Just wondering on the details, in case something springs to mind from them. :smile:

**Comment by revolter** [comment]
@justinclift, All the background colors (`*_bg_colour`) are [defaulting to white][1], so it looks like maybe it's a Qt bug?

  [1]: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/PreferencesDialog.cpp#L296-L305

**Comment by justinclift** [comment]
@revolter Yep, that's possible.  It's going to be hard to figure out the problem unless we can replicate it.

As an alternative thought @MarqueIV, would you be interested in building DB4S to investigate?

Your CV shows in-depth programming skills, including C++.  So, it's probably right in your skill set. 😀 

Setting up a DB4S development environment on OSX is fairly easy, if that helps.

**Comment by MKleusberg** [comment]
No idea why it's black on black. The default, in the case that there is no config file, is black on white (https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/PreferencesDialog.cpp#L282). How are settings stored on MacOS anyway? Do they have config files or something like a Windows registry? In the latter case Sierra could at least in theory send Null values which we wouldn't notice because 0 is not no value.

**Comment by MKleusberg** [comment]
Ah @revolter was faster ^^

**Comment by justinclift** [comment]
@MKleusberg That Null thought is interesting.  Maybe we should adjust our code to detect that, and if it's Null then return the default value instead?

**Comment by MarqueIV** [comment]
re: the nulls... yes... definitely check for that and return the defaults as necessary.  I'm one to always code for any possible value that's compilable (that a word?) 

To answer your question, this isn't a VM, it's the Mac version running right on the hardware.  However, I'm also running Win10 via Parallels 11.  I can check the Win version of the same build if you want to send it over. I also have an El Cap machine here too.  Lemme know if you want me to test on all of them, and if so, what version of the app.

As for setting up the dev environment myself, I'm stronger in C# and Swift and even Objective-C/C++ but am by no means an expert.  I've also never done QT development, although I have liked what I've seen with it. (I actually met the original owner of TrollTech way back before even Nokia bought it.) . Still, perhaps making a debug build where you log stuff to files, then I can send those over to you.  I'm also fine setting up a TeamViewer session where you can take control of my machine and experiment yourself.  Lemme know.

**Comment by MarqueIV** [comment]
Also, just ran your 3.9.99 beta 3 (which appears to be signed) on Sierra beta 7 and still got the black cells.  I'm wondering if perhaps there's some bad preferences being held around.  Can you give me a list of all the locations you've written files and I'll nuke them all? (Do you have an uninstaller or script? That would be even better!)

**Comment by justinclift** [comment]
@MarqueIV Wiping the preference files is an interesting thought.

For my OSX 10.9.5 desktop, this is where they are for my user:

```
$ ls -la Library/Preferences/*sqlitebrowser*
-rw-------  1 jc  staff  8286 25 Aug 11:25 Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
-rw-------  1 jc  staff   203 23 Aug 15:54 Library/Preferences/net.sourceforge.sqlitebrowser.plist
-rw-------  1 jc  staff   101  7 May 15:39 Library/Preferences/sqlitebrowser.plist
```

And yeah... spread out.  Trying to maintain compatibility with historical releases, so people (in theory) don't have to setup their preferences again just because they upgraded. :wink:

Checking Sierra, they're in the same place too.  Deleting those files should just mean they're recreated on the next run.  But yeah, one way to find out. :smile:

For Windows and El Cap, it doesn't hurt to check.  Personally, I'm not expecting those to have the issue, but heck since you're offering to try them out "why not?". 😃 

If you're still up for that, try with the installers from yesterday's 3.9.0 official release:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.9.0

**Comment by MarqueIV** [comment]
Ha! Found the cause of the issue!

Using your above references to the prefs, I nuked them, and as I had hoped, the colors appeared as normal even after closing, then reopening the app.

However, as soon as I went and changed from the default colors to match my liking (for reference, I set nulls to 'Moss' and binary to 'Lavender', both under 'Crayons'), while they displayed correctly for that session, closing and opening the app went back to the black-on-black colors I was seeing.  Deleting the prefs again got things back to normal.  Setting the colors broke it again, etc.

Trying to determine if it was a 'color prefs' thing or a 'prefs in general' thing, this time I nuked the prefs file, confirmed the colors were at their defaults, then opened up 'Preferences' and toggled 'Remove Line Breaks in Schema View' (i.e. a pref *not* related to color). I closed and restarted and sure enough, the colors went wonky again back to black-on-black.  Ironically, the 'Remove breaks' setting *did* stick.

So... that's how to get to see what I was seeing.  Apparently the prefs for the colors are either being written, or read incorrectly even though the other prefs seem to be persisting and being read just fine.

Hope this helps!  More importantly, I hope it's a quick fix so I can finally use my custom preferences with your app. :)

**Comment by revolter** [comment]
@justinclift, Did / Can you test this on El Capitan?

**Comment by justinclift** [comment]
I can, but not right now. :wink:

**Comment by MarqueIV** [comment]
Just chiming in.  Does this mean someone worked on a fix for the prefs here?  If so, lemme know and I can test it right now on El Cap 10.11.6. (I'm not set up to build tho so if someone can make a binary, that would be great.)

**Comment by justinclift** [comment]
Nope, not yet.  @revolter was just meaning I should test it on El Capitan to see if it's a Sierra only thing. :wink:

**Comment by justinclift** [comment]
As an initial workaround (emailed to me directly, thanks Roger! :smile:), this seems to effectively force DB4S to use the defaults for each session:

```
$ rm ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
$ ln -s /dev/null ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
$ ls -l ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
lrwxr-xr-x  1 roger  staff  9 22 Nov 18:36 /Users/roger/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist -> /dev/null
```

Hopefully I have to look into this properly in a few weeks to get it fixed "the right way". :smile:

**Comment by ghellquist** [comment]
My guess is that it is a QT bug, preferences are now saved and retrieved correctly as far as I can see.

I have recompiled on my mac 
 - OS: Sierra (10.12.2)
 - Qt Version 5.7.1
 - SQLite Version 3.15.2

Recompilation from inside of QT Creator as I´m still stumbling around learning what to do. 

/Gunnar Hellquist

**Comment by justinclift** [comment]
Interesting.  If I update the OSX utils on the build box, are you ok to try out the tomorrow's nightly build?

**Comment by ghellquist** [comment]
Absolutely.  I can test. /Gunnar



Den 16 dec. 2016 1:55 em skrev "Justin Clift" <notifications@github.com>:

**Comment by justinclift** [comment]
k, just updated everything on the build server, and kicked off a new build manually instead.

When you have a minute, please try out these two and let me know if they're ok:

* https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite_3.9.1v2.dmg
* https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-sqlcipher_3.9.1v2.dmg

If they are, we can add them to the 3.9.1 release page and point the Sierra users towards those. :smile:

**Comment by ghellquist** [comment]
Hi!
In my testing and loading and saving of preferences is correct - the dreaded black data fields are gone. 
I have done a few checks here and there of other functions and they work (not in any way any exhaustive test).
Default size for SQL is still 9, but I guess that is by design (change in next release).
Glad to be of some help.

/Gunnar

**Comment by justinclift** [comment]
Excellent Gunnar, that's good news.  I'll add the new build to the 3.9.1 release tomorrow (need sleep atm).

The build itself was done from the 3.9.x branch, which is pretty much the same as 3.9.1 but (from memory) with a few translation updates as well.  It should be fairly similar to the existing 3.9.1, with no real possibility of extra bugs introduced.

**Comment by justinclift** [comment]
The 3.9.1 Releases page is now updated with the new OSX binary, and the website points to it now too.

@MarqueIV, @highPlainsSailor, @compengi, @brozikcz - That might be of interest to you as well. :smile:

**Comment by ghellquist** [comment]
I can confirm that on my machine (Sierra 10.12.2) the black-on-black issue is solved in the new build (3.9.1v2). Preferences are handled correctly, application downloads, installs and work as expected as far as OS and preferences are concerned. This issue can as far as I see be closed.

**Comment by justinclift** [comment]
Cool, closing this now then.  If it turns out to still be a problem after all, I'm sure someone will make an Issue for it. 😁

**Comment by justinclift** [comment]
Thanks for the effort you've put in to chasing this problem Gunnar, it's definitely helped. :smile:

**Comment by revolter** [comment]
@ghellquist A big thanks from me too!

**Comment by jtlowe** [comment]
I downloaded 3.9.1v2 and had to remove my preferences file, found above, before the black background was resolved. I did't try changing the background preferences within the application to but that may have done it as well. The black background issue hasn't returned for me yet!

**Comment by justinclift** [comment]
@jtlowe Excellent, that's good info. :smile:

**Comment by nkahnfr** [comment]
Hi,

Sorry but the problem is still there for me whenever I try to modify preferences.
I am using Sierra (10.12.2) and DB4S from cask (3.9.1v2).

If I don't modify preferences I can restart DB4S and background colors remain correct.
Whenever I change a preference and restart DB4S the black-on-black issue is present.

Please find attached a working and bugged version of sqlitebrowser settings.
[sqlitebrowser.plist.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/701448/sqlitebrowser.plist.zip)

Am I missing anything?
Thanks for your help.

-Nicolas

**Comment by revolter** [comment]
As @jtlowe said, I think you need to delete the preferences file (while DB4S is closed), as they might be corrupted or something. You can do so from terminal by running this command in terminal:

    rm ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist

or by simply going to that location and manually removing that file.

@jtlowe, Correct me if I'm wrong.

**Comment by nkahnfr** [comment]
@revolter Sorry, I forgot to mention that I did all my tests from a fresh setting file after having deleted the previous one. So deleting the setting file does not help in my case.

**Comment by justinclift** [comment]
Interesting.  It sounds like the Qt fix might not be as complete as we were thinking.

@nkahnfr Would you be ok to try one of our recent nightly builds and see if that makes a difference? (download location is listed on the front page of this project, if that helps)

**Comment by nkahnfr** [comment]
@justinclift Ok, just found the bug, it's me! :-)
After uninstalling the cask version of DB4S to test a nightly build I realized that another old version (3.9.1) was still installed...
I uninstalled it and reinstall latest version using cask and everything works perfectly!

Sorry guys for the wrong alert, my bad.
And thanks again for the fix.

**Comment by jtlowe** [comment]
I've been doing some testing using settings from nkahnfr's attached .plist but haven't been able to reproduce the issue. I did notice this part below that diffs from my preferences.

`<key>databrowser.reg_bg_colour</key>
<data><string>@Variant(</string>`

**Comment by jtlowe** [comment]
Disregard my last comment, just saw @nkahnfr message

**Comment by revolter** [comment]
But maybe there is a bug that caused `@Variant(` to be saved instead of an actual color.

**Comment by justinclift** [comment]
Thanks all. :smile:

@revolter Yep, that does sound like a new bug.  Seems like a serialisation problem.  Do you have time to create an Issue for it? (if not, I can do it) :smile:

**Comment by revolter** [comment]
@justinclift, Done.

**Comment by justinclift** [comment]
Excellent, thanks @revolter. :smile:

**Comment by rmariuzzo** [comment]
I was fighting against this issue, had to delete my config files:

```shell
find ~/Library/Preferences -name '*sqlitebrowser*' -delete
```

Now, everything back to normal.

**Comment by justinclift** [comment]
@rmariuzzo  Interesting.  Any idea if using the 1st or 2nd version of our 3.9.1 release for OSX?

The original version we released (October last year) had a Qt bug causing this.  So we made a 2nd version a few weeks later (with "v2" on the end of the filename) which should have fixed it for everyone.  In theory. :wink:

If you're using the 2nd version, that's definitely something we'll need to keep an eye on!

**Comment by rmariuzzo** [comment]
I had the issue from 2-3 months ago, and I deleted the version I had and I downloaded today the `DB.Browser.for.SQLite-3.9.1v2.dmg` file and the error was there. Probably, because I already had the issue. I will try to customize my preferences and see if it happens again.

Thanks for the quick reply :)

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by justinclift** [comment]
@donmontalvo From memory on OSX they're stored in a flat file in the ~/Library/Preferences directory.

I'm not on my OSX desktop atm though, but guessing you'll have one handy so would be able to check pretty quickly. :smile:

**Comment by donmontalvo** [comment]
@justinclift, yep, first place I checked (...didn't see a key written for disabling updates when I did so through the app's GUI. Checked in ~/Library/Container/ and ~/Library/Group\ Containers/ even though the app isn't signed/sandboxed, just to be sure.

**Comment by justinclift** [comment]
When you say, disabling updates, are you meaning to stop the automatic version check?

It should definitely be there.  We had a bug in the first version of it, where it wasn't being read back correctly (ugh), but that was ages ago.  I really hope we haven't busted that again with the recent refactoring for getting the remote stuff working.

I'll jump on my OSX desktop shortly and take a look.

**Comment by justinclift** [comment]
k, took a while to refresh my memory and hunt around, but found it.

On my local OSX desktop, the setting for that is stored in:

    ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist

Mine was in binary plist format, so needed converting to the ascii format before being able to grok it:

```
cp ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist ~/foo.plist
plutil -convert xml1 foo.plist
```

The value itself is called `checkversion` so grepping the above converted foo.plist for that string should find it.  It does on mine.

Does that help? :smile:

**Comment by justinclift** [comment]
Looking into it even more, this is the code 3.10.0 which kicks off the version check:

https://github.com/sqlitebrowser/sqlitebrowser/blob/e30d19dbb4bf45d08b45ee347f8ebc12066a43ec/src/MainWindow.cpp#L258-L265

As well as first checking if the user has disabled the remote check, the code for doing the check itself can be not even included when DB4S is compiled.

That flag is enabled for Windows and OSX by default in the Qt project file.  The OSX line is here:

https://github.com/sqlitebrowser/sqlitebrowser/blob/e30d19dbb4bf45d08b45ee347f8ebc12066a43ec/src/src.pro#L196

So, if you want to be 100% sure... it's pretty easy to compile DB4S (the instructions are in BUILDING.md). You'd want to remove that option from the src.pro file, and compile it.

For super overkill :smile:, this is a copy of the script that builds our OSX nightly releases:

&nbsp; &nbsp; https://gist.github.com/justinclift/59e2c975100c5cd647d773bc797312f0

Might be useful bits in there if you want to see how our packaging gets put together. :smile:

**Comment by donmontalvo** [comment]
Ok sorted it out...clif note for disabling version when deploying this awesome app:

```
bash-3.2# defaults read /Users/username/Library/Preferences/com.sqlitebrowser.sqlitebrowser checkversion.enabled
1
bash-3.2# defaults write /Users/username/Library/Preferences/com.sqlitebrowser.sqlitebrowser checkversion.enabled -bool false
bash-3.2# defaults read /Users/username/Library/Preferences/com.sqlitebrowser.sqlitebrowser checkversion.enabled
0
bash-3.2# 
```

Our deployment method loops through existing users, so an easy *.plist key to set.

**Comment by donmontalvo** [comment]
BTW, on macOS, using defaults commands there's no reason to convert the file.

What we do is:

1. Download the DMG
2. Wrap it using any tool (Whitebox Packages, Apple pkgbuild, Jamf Composer, etc.).
3. Add postinstall.sh script to the package to set the setting (since it is per user), using a loop.

`#!/bin/sh

over500=$( dscl . list /Users UniqueID | awk '$2 > 500 { print $1 }' )

APPLICATION="/Applications/DB Browser for SQLite.app"

#-------------------------------------------------------
# Remove Quarantine flag if not owned by root:wheel
#-------------------------------------------------------

/usr/bin/xattr -r -d com.apple.quarantine /Applications/"$APPLICATION"

#-------------------------------------------------------
# Set pref User Template for future users
#-------------------------------------------------------

/usr/bin/defaults write /System/Library/Preferences/com.sqlitebrowser.sqlitebrowser "checkversion.enabled" -bool false
/bin/chmod -R 700 /System/Library/User\ Template/English.lproj/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
/usr/sbin/chown root:wheel /System/Library/User\ Template/English.lproj/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist

#-------------------------------------------------------
# Set prefs for existing users
#-------------------------------------------------------

for u in $over500 ;
do
	/usr/bin/defaults write /Users/"$u"/Library/Preferences/com.sqlitebrowser.sqlitebrowser "checkversion.enabled" -bool false
	/bin/chmod -R 700 /Users/"$u"/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
	/usr/sbin/chown "$u" /Users/"$u"/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
done

exit 0`

**Comment by justinclift** [comment]
Cool.  Thanks @donmontalvo. :smile:

That certainly looks like it'll be useful reference material for people. 😀
