### ISSUE TITLE
SQLitebrowser and System.Data.SQLite

### ISSUE THREAD

**Issue by Disactive** [sqlitebrowser/sqlitebrowser#739]
### Details for the issue

Yeah.. why not?
You can add the ability to open databases that are protected with RS of System.Data.SQLite (.Net Framework)
Then will be the best SQLite Browser in the world!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.0 beta1
- [X] 3.8.0
- [ ] Other: ___

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, it's unlikely.  Out of curiosity, do you know if that part of .Net is one which MS have Open Sourced?

**Comment by Disactive** [comment]
But System.Data.SQLite is not a part of Microsoft.. that come from SQLite DLLs

**Comment by justinclift** [comment]
Ahhhh, my bad.  Are you meaning this?

&nbsp; &nbsp; https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki

**Comment by Disactive** [comment]
Yeah, that is what i mean :)

**Comment by justinclift** [comment]
@Disactive Looking at the website, it seems like an alternative approach to opening SQLite files.

What does the "protected with RS" bit mean in your request? :smile:

**Comment by Disactive** [comment]
I mean.. whit this dll you can set a password to database, but you can only open it again whit the same dll.. not but other SQLite browser.. and.. in internet exists only 1 browser that can open encrypted database with this dlls, but is a very only software (2009), now is pretty bugged.
If i try to open a encrypted database with your browser, i get an error. Becase this dll encrypt files using RSA (not RS, like i write in the first post, was a keyboard error)
Hope you understand what i mean :)

**Comment by justinclift** [comment]
Ahhhh.  I understand part of it.

The System.Data.SQLite software can add RSA encryption to files.

Do you know if it uses [the official "SEE" encryption](https://www.sqlite.org/see/doc/trunk/www/index.wiki), or if it uses something else?

**Comment by Disactive** [comment]
No, the enrcryption use a personal security system, that is writed in the System.Data.SQLite.
For set a password you can simply add this dll to a project and use a command:
Connection.SetPassword("MyPass");

I have read womthing online, and im sure that use not SEE (external plugin) but RSA (internal function).

**Comment by justinclift** [comment]
Thanks @Disactive, it's making sense now. :smile:

We've taken a quick look at the System.Data.SQLite bits... and it doesn't really seem like there's much benefit to implementing that in DB4S.

It might be possible to adjust our SQLite layer to use that, but it's probably a fair amount of work.  It would only give us version basic encryption too, unlike the strong encryption in SQLCipher.

If you have C++/Qt skill though, and are willing to do the work, we're happy to accept good patches. :smile:

What do you think?

**Comment by Disactive** [comment]
That will be awesome, but i dont know C++ language, so... i can't give you a big help.
Anyway.. i think (and is just my opinion).. i think that you will have good benefit if you add the ability to open database that are encrypted with System.Data.SQLite. Because there are many users that use this dll with .Net Framework, by programming in VB.Net; C#, F, etc.. and many of them will use this internal protection to encrypt thier database. I mean.. why use an external dll or plugin if you can protect your database with the same dll that you use for read/write it?

Example:
I made a "Database.db" with System.Data.SQLite.dll and i use it in my app, then i use also your browser for open my databse and watch what contains. But is i set a password to this database, i cannot open it anymore (with your browser).
I (and other users like me) must CREATE a new app that will use only for watch the content of the encrypted database.

Remember that just one browser can open database encrypted with System.Data.SQLite.dll (SQLite2009 Pro) but is not good as your browser :)

With this more function you will have more users.

**Comment by justinclift** [comment]
Hmmm. It sounds like a lot of work needed on our part. 😦 

Sorry, but this is very unlikely to happen unless someone willing to do the work themselves gets involved.  I'm going to close this issue, but if someone **is** willing to do the needed work to implement this, they're welcome to reopen it and get it done. :smile:

**Comment by chrisjlocke** [comment]
Just a nod that this (or similar) came up recently on the system.data.sqlite mailing list.  Dr Richard Hipp mentioned System.data.sqlite can be recompiled to use SEE, rather than its own encryption library.


> I am working on a project using the System.Data.SQLite .net Classes. I
> use the encryption available with this classes.
> Is the encryption used by System.Data.SQLite when setting a password
> compatible with the encryption used in the SEE version of SQLite?

No.  Databases encrypted by the legacy encryption mechanism in SDS are
not readable or writable with SEE, and vice versa.
SDS can be recompiled to use SEE.

**Comment by justinclift** [comment]
Hmmm, if System.Data.SQLite could be recompiled to use SQLCipher, that might make things easier.

It's not something I'm personally interested in, but @Disactive may want to ask about it on [the SQLCipher forums](https://discuss.zetetic.net/c/sqlcipher).

**Comment by Disactive** [comment]
My idea was to use the integrated protection, not another external dll. :)
Anyway.. i dont know what i must ask on this forum, so.. i think i will pass :)
