### ISSUE TITLE
Unable to uninstall program from "Programs and Features" in Win7

### ISSUE THREAD

**Issue by goozak** [sqlitebrowser/sqlitebrowser#742]
Could be considered an installation bug, especially for 'regular' user.
Windows 7 Ultimate SP 1
DB Browser for SQLite 3.9.0, 64-bit

There is no "uninstall" entry in Windows 7 "Programs and Features" Control Panel item. (There was one for v. 3.8.0.)

Workaround is to directly use the "Uninstall.exe" program in the installation folder (the one above the "bin" folder where the program's executable file is located).

![screenshot - 24-08-16 14_47_19](https://cloud.githubusercontent.com/assets/454810/17943541/d693f0d0-6a09-11e6-9cfe-8c1aea86270c.png)

**Comment by justinclift** [comment]
@goozak Thanks for pointing this out.

I remember seeing this as well when testing the NSIS package, but completely forgot about it.

We'll investigate this in time for the next release.  In the meantime... damn. 😦

**Comment by justinclift** [comment]
In theory, it's probably just something simple in our NSIS package generation variables:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/e21dc402562d448a37b76ee7fe253501d96e6752/CMakeLists.txt#L354-L386

It'll just take some experimentation to find out exactly what's wrong, and fix it.

**Comment by justinclift** [comment]
@goozak Would you have a few minutes to try out this build?

* http://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-201608291559-win64.exe

With that build - for me - the correct entry is now appearing again in Add/Remove programs.

It'd be really helpful if you have time to verify it from your point of view. :smile:

**Comment by goozak** [comment]
Yep!  The program now shows up in the Uninstall list as expected.

Minor glitch when _uninstalling_ the program : It doesn't check if program is currently in use.  The uninstall goes through without any errors, but leaves the program executable and DLLs in place.

**Comment by justinclift** [comment]
Thanks @goozak that's one bit solved at least. :smile:

With the uninstaller not checking for files in use... ouch. 👿 

Not sure if it's something we can control, but I'll take a look and find out. :smile:

**Comment by justinclift** [comment]
@goozak There doesn't seem to be any good way to have the uninstaller abort if the files are in use, or even mark them for removal with the next system restart. 😦 

The NSIS (3.0) uninstaller itself has exactly the same problem.

It *might* be fixable by using a different Windows packaging mechanism (eg [WiX](http://wixtoolset.org) or [Inno Setup](http://jrsoftware.org/isinfo.php)), but we're unlikely to change over in the near/medium future.

Going to close this now, as there's probably not much more we can do at this stage. :smile:

**Comment by goozak** [comment]
That's totally fine.  :-)

I found this, which seems to do both the checking and the aborting : http://nsis.sourceforge.net/Check_whether_your_application_is_running

Not sure if it's any help in your case though, I have no idea how NSIS works.

**Comment by justinclift** [comment]
Ahhh, that's interesting.  Hadn't seen that. :smile:

I'll bear them in mind later, when I next need to dig into the installer again. (unfortunately, it's not standard NSIS, we use a combination of CMake/CPack to drive NSIS.  Turns out that's painful for adding things onto 😦 )
