### ISSUE TITLE
Exporting CSV table from 3.9.0 causes corruption when imported back in

### ISSUE THREAD

**Issue by rudolf323** [sqlitebrowser/sqlitebrowser#743]
### Details for the issue

So I'm using Chrome's SessionBuddy extension and once in a while I export SavedSessions table out of the extension's DB to edit out some URL's (from The Great Suspender). And after that I import back the saved .CSV (it's edited on N++) into SQLite browser. It all worked great on 3.8.0. But now on the 3.9.0 version when I tried to export the table as .CSV, edited it, imported back and it is somehow corrupted or incorrectly saved, there are over 140 columns in the screenshot. But there should be 14.
As you can see in the 2nd screenshot which was taken now after I tried to do the same on 3.8.0 luckily I did backups of that DB.

This happened after I exported DB table out of the newest SQLite Browser version (3.9.0) and imported it back in.
![capture1](https://cloud.githubusercontent.com/assets/4366810/17951123/67e3e85c-6a68-11e6-8a20-a12169b57aed.PNG)

This is how it looks when .CSV is exported and imported on version 3.8.0
![capture2](https://cloud.githubusercontent.com/assets/4366810/17951242/505ffb52-6a69-11e6-815e-7ece8eab4046.PNG)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: **because of this bug I'using the old version now**.

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
!
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch, that doesn't sound good at all.

Is the database you're dong this on private or sensitive?  Asking because I'm wondering if you could maybe email it to me (justin@postgresql.org)?  That way tomorrow I'll try and get the problem to happen for me, so we can fix it. :smile:

If not, no stress, I can still try tomorrow using a made up database here. :smile:

**Comment by rudolf323** [comment]
It's private, but you can easily try this by yourself if you're using Chrome: 

- [link to the extension](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko?hl=en)

- It automatically creates a DB in this location when you save a session.
- `C:\Users\[username]\AppData\Local\Google\Chrome\User Data\Default\databases\chrome-extension_edacconmaakjimmfgnblocblbcdcpbko_0`

- Open it with SQLite browser and try to export SavedSessions table (as .csv) and then import it back, it looks kind of messed up.

**Comment by justinclift** [comment]
Thanks @rudolf323.

I'll install Chrome in a VM tomorrow and see what's going on. :smile:

We might be releasing a v3.9.1 in near future after all. :wink:

**Comment by justinclift** [comment]
Just in case it turns out to make a difference, which version of Windows are you running?

**Comment by rudolf323** [comment]
@justinclift Windows 10 Anniversary Update

**Comment by justinclift** [comment]
Thanks @rudolf323. :smile:

**Comment by justinclift** [comment]
@rudolf323 With this, I haven't yet tried out the Chrome extension.  Something popped into mind though, which might explain the problem.

In the export dialog (*File* → *Export* → *Export data as CSV*), the drop down option at the bottom is "New line characters":
![screen shot 2016-08-25 at 15 02 08](https://cloud.githubusercontent.com/assets/406299/17972022/380802ea-6ad5-11e6-9fc5-89aa25f863e7.png)

For that, does the corruption go away if that's set to the Windows option?

The corruption you describe, is (I think) what would happen if the newline characters are completely missing.  When them missing, the Import dialog just sees everything as one big line and doesn't know where they each end.

Do you have time to give that a try, and let us know if it helps? :smile:

**Comment by rudolf323** [comment]
@justinclift I just tried it and it works !!! Thanks.

**Comment by justinclift** [comment]
Awesome, that's good news. :smile:
