### ISSUE TITLE
DB Schema view resets on tab change

### ISSUE THREAD

**Issue by Swabek** [sqlitebrowser/sqlitebrowser#744]
**Steps To Reproduce:** 	
1) Open any database with one or more tables
2) Expand any table in the "DB Schema" view on the right
3) Change the main tab (e.g. from "Database Structure" to "Browse Data"

**Actual Results:**
All your expanded tables get collapsed.

**Expected Results:**
All your expanded tables stays expanded.

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for reporting this @Swabek, this is definitely a bug.

It's happening here OSX too, so this isn't just a Windows thing either.

**Comment by innermous** [comment]
@justinclift it's not even close a bug, it's intended behavior by someone who've written that code.
Every time on changing current tab it wipes whole dbstructuremodel and fills it from scratch.

**Comment by justinclift** [comment]
Heh Heh Heh

It sounds like they may have tried to "keep it safe", and got it wrong. :wink:

**Comment by MKleusberg** [comment]
Should be more or less fixed by 684958b29ce3d26684d9142d73df773b11189d54 which I committed yesterday. The DB schema view will still reset as soon as the DB schema actually changes but at least it doesn't happen on each and every tab change anymore :wink:
@Swabek Currently our nightly builds are broken but I hope they'll be up and running this or the next night. As soon as that's done you'll be able to test the changes and report back if it's working for you :smiley:

**Comment by Swabek** [comment]
Just compiled it myself under Linux. 
The described bug (DB Schema view resets on tab change) is fixed.
But there is now a new bug:
Now the reset happend when I clicked on "Cancel" in the "Modify Table" dialog. 
This takes not only in the DB Schema view on the right place. Also in the main window.

I also think it is not the best practice to reset the hole schema. Why not just refresh the changed columne? And not collapsing the hole schema.
I think this would increase the user experience and the performance a lot.

**Comment by revolter** [comment]
As the initial issue was solved, can we close this? And maybe @Swabek opens a separate issue for the last problem (if one wasn't already created).

**Comment by Swabek** [comment]
@revolter Ok.
Verified fixed in [684958b](https://github.com/sqlitebrowser/sqlitebrowser/commit/684958b29ce3d26684d9142d73df773b11189d54).

**Comment by justinclift** [comment]
Moved this to 3.10.0 instead of 3.9.1, as the commit makes a *lot* of changes.  It doesn't apply cleanly to current 3.9.x source, and doing it manually isn't really appealing. :wink:
