### ISSUE TITLE
"sqlitebrowser" command doesn't work

### ISSUE THREAD

**Issue by srknkrn** [sqlitebrowser/sqlitebrowser#746]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

I cant start  the browser using this command "sqlitebrowser" in terminal, but I could start it with that command before update ?

**Comment by justinclift** [comment]
Ahhh, that's interesting.  We changed the name of the command from "sqlitebrowser" to "DB Browser for SQLite".

But, that might not have been a great idea for people used to launching it from the command line. 😦 

Depending on which shell you have configured, it **might** be possible to launch it by typing `DB` then hitting tab for autocompletion.

If that doesn't work, it's probably possible to create a `sqlitebrowser` soft link to the new "DB Browser for SQLite" executable.  eg using something like:

```
$ cd bin
$ ln -s "/path/to/new/DB Browser for SQLite" "sqlitebrowser"
```

As long as the "sqlitebrowser" soft link is in your PATH, it should work.

Does that help?

Btw, out of curiosity, did you update using the .dmg from the release page?

**Comment by srknkrn** [comment]
It work when I type DB then hitting TAB and I did update using .tar file ,also I used the same file for installation before the update...
This command does not work 
`ln -s "/path/to/new/DB Browser for SQLite" "sqlitebrowser"
`
and by the way I saw some error message after "cmake ." command, should I share?

**Comment by justinclift** [comment]
Yep, please share it.  It's better to see the error, just in case it is important. :smile:

**Comment by srknkrn** [comment]
CMake Warning (dev) at CMakeLists.txt:270 (add_executable):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "DB Browser for SQLite" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/someuser/sqlitebrowser-3.9.0

**Comment by justinclift** [comment]
Thanks.  That warning isn't a problem, you can ignore it. :smile:

**Comment by srknkrn** [comment]
Okay but still "sqlitebrowser" command does not work :( and this errors message from after "make" command
`Scanning dependencies of target qscintilla2
[  5%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qsciscintilla.cpp.o
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:267:9: warning: 
      add explicit braces to avoid dangling else [-Wdangling-else]
        else
        ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:274:9: warning: 
      add explicit braces to avoid dangling else [-Wdangling-else]
        else if (acThresh >= 1 && isWordCharacter(ch))
        ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:856:9: warning: 
      add explicit braces to avoid dangling else [-Wdangling-else]
        else
        ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:1244:13: warning: 
      enumeration value 'WrapFlagNone' not handled in switch [-Wswitch]
    switch (endFlag)
            ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:1260:13: warning: 
      enumeration value 'WrapFlagNone' not handled in switch [-Wswitch]
    switch (startFlag)
            ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciscintilla.cpp:1304:13: warning: 
      enumeration value 'NoFoldStyle' not handled in switch [-Wswitch]
    switch (folding)
            ^
6 warnings generated.
[  5%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qsciscintillabase.cpp.o
[  5%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qsciabstractapis.cpp.o
[  6%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qsciapis.cpp.o
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciapis.cpp:228:13: warning: 
      158 enumeration values not handled in switch: 'None', 'Timer',
      'MouseButtonPress'... [-Wswitch]
    switch (e->type())
            ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/qsciapis.cpp:641:17: warning: 
      add explicit braces to avoid dangling else [-Wdangling-else]
                else if (unambiguous_context != org)
                ^
2 warnings generated.
[  6%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscicommand.cpp.o
[  7%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscicommandset.cpp.o
[  7%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscidocument.cpp.o
[  8%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscilexer.cpp.o
[  8%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscilexersql.cpp.o
[  9%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscimacro.cpp.o
[  9%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qsciprinter.cpp.o
[ 10%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscistyle.cpp.o
[ 10%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/qscistyledtext.cpp.o
[ 10%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/MacPasteboardMime.cpp.o
[ 11%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/InputMethod.cpp.o
[ 11%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/SciClasses.cpp.o
[ 12%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/ListBoxQt.cpp.o
[ 12%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/PlatQt.cpp.o
[ 13%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/ScintillaQt.cpp.o
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/ScintillaQt.cpp:193:9: warning: 
      add explicit braces to avoid dangling else [-Wdangling-else]
        else
        ^
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/ScintillaQt.cpp:371:51: warning: 
      & has lower precedence than !=; != will be evaluated first [-Wparentheses]
  ...&& (scn.modificationType & (SC_MOD_INSERTTEXT|SC_MOD_DELETETEXT) != 0))
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/ScintillaQt.cpp:371:51: note: 
      place parentheses around the '!=' expression to silence this warning
  ...&& (scn.modificationType & (SC_MOD_INSERTTEXT|SC_MOD_DELETETEXT) != 0))
                              ^
                                (                                         )
/Users/someuser/sqlitebrowser-3.9.0/libs/qscintilla/Qt4Qt5/ScintillaQt.cpp:371:51: note: 
      place parentheses around the & expression to evaluate it first
  ...&& (scn.modificationType & (SC_MOD_INSERTTEXT|SC_MOD_DELETETEXT) != 0))
                              ^
         (                                                           )
2 warnings generated.
[ 13%] Building CXX object libs/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/lexers/LexSQL.cpp.o
`

**Comment by justinclift** [comment]
Ahhhh.  Try using `qmake` instead of `cmake`, using the steps here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

In theory (!), that should work.  It will generate an .app bundle though, which I'm not sure you want. 😦

**Comment by srknkrn** [comment]
I think I have to get used to "DB" with TAB. :) You can close this issue if there is nothing to work with "sqlitebrowser" command. Thank you

**Comment by justinclift** [comment]
Cool. :smile:

Yeah, the new DB<tab> approach is probably the way to go. :wink:
