### ISSUE TITLE
Selected table in Browse Data tab resets to first table on tab change

### ISSUE THREAD

**Issue by geoffblack** [sqlitebrowser/sqlitebrowser#748]
Steps To Reproduce:

1) Open any database with one or more tables
2) Expend any table in the "Browse Data" view on the right
3) Change the tab from "Browse Data" to "Execute SQL " and back to "Browse Data"

Actual Results:
The selected table is reset to the first table in the DB.

Expected Results:
The selected table stays the same as before you changed tabs.

#### I'm opening this issue because:
- [X ] DB4S has a bug

#### I'm using DB4S on:
- [X ] Windows 64-bit

#### I'm using DB4S version:
- [X ] 3.9.0

Related to #744

**Comment by justinclift** [comment]
Thanks for pointing this out @geoffblack, that does look like a bug related to #744.

@innermous Will your fix for #744 solve this one too?

**Comment by innermous** [comment]
1. Not related to #744, it was about schema tree structure.
2. It is already fixed a week ago, use nightly build.

**Comment by justinclift** [comment]
@geoffblack Interestingly, this does seem to be already fixed in our latest development code. :smile:

Would you be ok to try out [the latest nightly build for Windows](https://github.com/sqlitebrowser/sqlitebrowser#windows), and let us know if it's fixed for you?

The download locations are on our front page, if that helps.

**Comment by geoffblack** [comment]
It is indeed fixed in the latest nightly, thanks.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by justinclift** [comment]
I'll close this now then, as the code is available in our nightlies, and will be in the next major release too. :smile:
