### ISSUE TITLE
Custom Page Size max too low.

### ISSUE THREAD

**Issue by TheOriginalWinCat** [sqlitebrowser/sqlitebrowser#752]
### Details for the issue

When loading a db with a custom page size, the dialog only allows a max value of 8092 (seams like a typo for 8192), yet a page size up to 65536 is valid.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch.  Yep, that does sound like a bug.

@MKleusberg One for you?

**Comment by MKleusberg** [comment]
This seems to be a bug in the SQLCipher encryption dialog. I've increased the max page size to 65536 (and the min page size from 1 to 512). Should be all good now :smiley: We don't have nightly builds for Windows with SQLCipher support yet, but if you want to test the changes, @TheOriginalWinCat, you can ask @justinclift to build you a once-off. He'll only need to know if you're running a 32bit or 64bit Windows installation :smile:

**Comment by TheOriginalWinCat** [comment]
I'm running 64bit Windows, but I'm in no rush. :)

**Comment by justinclift** [comment]
Awesome @MKleusberg, thank you. :smile:

**Comment by justinclift** [comment]
@TheOriginalWinCat Would you have a few minutes to try out this build?

* http://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-201608291559-win64.exe

That has @MKleusberg's fix in it.  In testing here, it accept encryption key page sizes up to 65536 now, and the same works when unlocking a database too.

Verifying it from your point of view would be nifty. :smile:

@MKleusberg As a side note... noticed something strange when testing with the old maximum (typo) value of "8092".  On Win64, encrypting a database with a page size of "8092" (not 8192) seems like it goes ok.  However, when re-opening the encrypted database (using 8092 page size), DB4S crashes.

Maybe the page size needs to be a proper power of two or something?  We can ask the SQLCipher people if that would be useful too. :smile:

**Comment by TheOriginalWinCat** [comment]
I tried the build provided but I'm still not able to open the DB.

I suspect it's a different issue tho as the db I'm trying to open it's created using the c# wrapper System.Data.SQLite.dll from what I can see there is no password and the db contents don't look encrypted when opened in a hex editor. But I do know they exec "PRAGMA page_size = 32768;" which Is how I came to report this.

I can verify that it lets me set 32768 in the dialog tho.

**Comment by justinclift** [comment]
@TheOriginalWinCat Ahhh, yeah.  We don't support System.Data.SQLite databases at this stage.

We **probably** won't either, unless someone submits patches to add the support (which we'll happily accept).

Don't suppose you're a C++ developer? :smile:

**Comment by TheOriginalWinCat** [comment]
Yes I'm a c++ developer, but I personally use the native sqlite code so the browser works just fine for my needs :smile: 

I just decided to have a browse of a db created by a 3rd party tool that happens to use the c# wrapper, so unfortunately I don't feel like implementing support :disappointed:

**Comment by justinclift** [comment]
Heh Heh Heh, no worries at all. :wink:

Btw, this is a related issue also about System.Data.SQLite from just a few days ago: #739 

It mentions a GUI called [SQLite2009 Pro](http://sqlite2009pro.azurewebsites.net), which seems like it would work.  That page mentions it's been updated in 2014 as well, so it's not *completely* ancient. :smile:

**Comment by chrisjlocke** [comment]
SQLite Studio is open source (and cross platform).  Haven't tried it with SDS created databases.  
http://sqlitestudio.pl/

**Comment by justinclift** [comment]
Closing this now, as the reported issue is fixed (in testing here), and we're unlikely to add support for System.Data.SQLite any time soon.
