### ISSUE TITLE
Add *.sql to the OpenDialog filter

### ISSUE THREAD

**Issue by bobatwhidbey** [sqlitebrowser/sqlitebrowser#753]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, that's interesting. :smile:

In theory, that's **supposed** to be happening already in a few places:

* File → "Import database from SQL" dialog. (code [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/684958b29ce3d26684d9142d73df773b11189d54/src/MainWindow.cpp#L1132))
* "Open SQL File" button in the Execute SQL tab. (code [here](https://github.com/sqlitebrowser/sqlitebrowser/blob/684958b29ce3d26684d9142d73df773b11189d54/src/MainWindow.cpp#L1517))

Sounds like it's not working for you though, or it needs to be added in other places too?

**Comment by bobatwhidbey** [comment]
Here's what I see. I'm hoping you can add *.sql to the four file 
extensions you already have.

**Comment by justinclift** [comment]
Would you be ok to attach the screenshot using the web interface?

GitHub doesn't recognise images in attachments, so they just get dropped. 😦

**Comment by bobatwhidbey** [comment]
Hope this comes through
![image](https://cloud.githubusercontent.com/assets/13080152/18072084/1efaaeae-6e10-11e6-886e-977d28bf0973.png)

**Comment by bobatwhidbey** [comment]
They are sqlite3 files. I don't like such a long file extension and have 
been using just .sql for a few years. Thousands of file from all the 
users of my app have been created.

http://www.bridgecaptain.com/downloadDD.html

**Comment by chrisjlocke** [comment]
> They are sqlite3 files. I don't like such a long file extension

SQL is a language, and as such its 'common' for .sql files to contain SQL commands, thus the reason they're used in database import/export dialogs, etc.
A database isn't a collection of SQL commands, but instead, a collection of data.  It makes more 'sense' to use a .db extension to denote a database, rather than a collection of SQL commands.

As Justin says though, you can do whatever you want, but was just pointing out the 'reasons' why .sql isn't in that dialog by default.  As you like short extensions, changing to '.db' solves two problems - its in the dialog, and its a shorter file extension! :wink:

**Comment by justinclift** [comment]
Yeah, this is a hard call.  If someone came along and suggested an extension that's not commonly used for a different purpose, there's a good chance we'd add it.  After all, it's would be unlikely to have a negative impact on anyone.

... but ".sql" isn't like that.  It's commonly used (including by us) for a specific purpose as **not** a database file. :wink:

This is **sort** of like if someone asked us to add ".doc" in the extension list for our opening/saving dialogs.  There's nothing technically stopping it working... but ".doc" is widely used for something else.

All is not lost though. :smile:

There are two potential solutions coming to mind, depending on how much effort you're ok with:

1. Adding new file extensions yourself is fairly simple.  There's only one line to you'd need to change:

 * https://github.com/sqlitebrowser/sqlitebrowser/blob/684958b29ce3d26684d9142d73df773b11189d54/src/FileDialog.h#L20

 You will need to compile DB4S yourself (with that line changed).  There are full, end to end instructions [here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S) for installing the needed software (including the needed settings), and it walks through the entire process.

  It's not complicated at all, it's just time consuming the first time around to download the bits, run their installers, etc.  We're happy to answer questions, if you're up for this and need assistance at points. :smile:

2. Wait for issue #659 to be completed.  With that done, you'll be able to add/remove the file extensions yourself through the Preferences dialog.

Workable? :smile:

**Comment by bobatwhidbey** [comment]
I understand your reasons for not adding .sql to the list. Makes perfect 
sense.

At the moment I just have one extra step - changing to the All Files (*) 
view in the open dialog. I can live with that until #659 is up and 
running.  I'll also consider use of the .db extension instead.

**Comment by justinclift** [comment]
Cool, no worries at all @bobatwhidbey. :smile:
