### ISSUE TITLE
DBBrowser 3.9.0 does not show up as default program, nor can be selected as default program

### ISSUE THREAD

**Issue by rvalk** [sqlitebrowser/sqlitebrowser#754]
### Details for the issue

After de-installing the former DBBowser, which did work well, I installed DBBrowser 3.9.0 and found that my database does not recognize DBBrowser anymore as it's default program to start with. I tried to associate *.db (extention I use for a long time) with DBBrowser, but 3.9.0 does not appear, even after browse and select, in the program list to open the files with. 
Is there something wrong with the registry settings or so?

Now I have everytime to start DBBrowser, open a database, select my database and then I can work, while with the old version I only had to click the database file and it opened with DBBrowser.

This situation happened on 2 different PC's I work on: one with Windows-7 and the other with Windows-10. Same behavior.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Sorry @rvalk, that's my fault.  I changed the default installation directory to include the version number (eg `3.9.0`) in the path name.  It turns out that was a bad idea. 😦 

You can fix the problem manually though.  If you're ok with using regedit, you can adjust things yourself using @chrisjlocke's instructions here:

* https://github.com/sqlitebrowser/sqlitebrowser/issues/279#issuecomment-242426297

There is some older info here, but Chris's instructions are probably better: :smile:

* https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

**Comment by justinclift** [comment]
Note - We're also working out a proper "more permanent" fix for this in #279.  We'll probably add something in the Preferences dialog so people can set file associations there.

It hasn't been added yet, but research is happening. :smile:

**Comment by chrisjlocke** [comment]
In Windows, you can also right click the file, select 'Open with...', tick the ticky box, and click 'More apps' (if on Windows 10) then find where you installed DB4S.  

http://chrisjlocke.co.uk/associations/

**Comment by rvalk** [comment]
Hi Justin,
I could assign the db ti DBBrowser 3.9.0 now, all my db's do have the new icon now.
Thanks for your help.
Rob Valk
     Wednesday, 31 August 2016, 05:35PM +02:00 from Justin Clift  notifications@github.com :

**Comment by justinclift** [comment]
Cool.  Hopefully we'll have a proper solution working for the next major version. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Just tried watching the video on your /associations/ page.  For me, it's not working through the Jplayer thing on the website.  [Downloading it directly](http://chrisjlocke.co.uk/wp-content/uploads/2016/08/31_0750.mp4) and watching with VLC works fine though. :smile:

**Comment by chrisjlocke** [comment]
Hmm, that's interesting. Must be a poor player. Worked ok on my Chrome. :disappointed:
