### ISSUE TITLE
windows build failure on nightly

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#755]
If not already known, the nightly windows build is broken:
http://sqlitebrowser.oldsch00l.com/build.log

```
Building CXX object CMakeFiles/DB Browser for SQLite.dir/src/AboutDialog.cpp.obj
i686-w64-mingw32.static-g++: error: @CMakeFiles/DB: No such file or directory
i686-w64-mingw32.static-g++: error: Browser: No such file or directory
i686-w64-mingw32.static-g++: error: for: No such file or directory
i686-w64-mingw32.static-g++: error: SQLite.dir/includes_CXX.rsp: No such file or directory
make[2]: *** [CMakeFiles/DB Browser for SQLite.dir/src/AboutDialog.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
i686-w64-mingw32.static-g++: error: @CMakeFiles/DB: No such file or directory
i686-w64-mingw32.static-g++: error: Browser: No such file or directory
i686-w64-mingw32.static-g++: error: for: No such file or directory
i686-w64-mingw32.static-g++: error: SQLite.dir/includes_CXX.rsp: No such file or directory
make[2]: *** [CMakeFiles/DB Browser for SQLite.dir/src/CreateIndexDialog.cpp.obj] Error 1
make[1]: *** [CMakeFiles/DB Browser for SQLite.dir/all] Error 2
make: *** [all] Error 2
```

see also: https://github.com/sqlitebrowser/sqlitebrowser/issues/758

**Comment by justinclift** [comment]
Thank @jungle-boogie.  It's likely the result from changing CMake config in `master` branch yesterday.

Emailing @rp- now, to see if it's fixable. :smile:

**Comment by justinclift** [comment]
Haven't heard back from @rp-, so took a different approach instead as pointed out by @MKleusberg: https://github.com/sqlitebrowser/sqlitebrowser/commit/2957974974bb874b0219e52d63c198658c02f686

I **think** the nightly build will be ok again now.  At least until we switch to Qt5, by which time we'll need to have a Qt5 compatible version of it running. :smile:

**Comment by justinclift** [comment]
The logs from the nightly build seems to say it succeeded.

Haven't personally tried the resulting package though. :wink:

**Comment by chrisjlocke** [comment]
Just tested the nightly, and it works.  Compared the 'about' box with 3.9, and noticed 3.9 doesn't show a SQLite version?

3.9
![image](https://cloud.githubusercontent.com/assets/7872218/18156266/ee5e7754-700c-11e6-9726-b38b1977cab0.png)


3.9.99
![image](https://cloud.githubusercontent.com/assets/7872218/18156272/fe1d2e60-700c-11e6-8096-b78c6d12bc21.png)


Also, the icons for both are different - 3.9.99 is a lighter grey... Wasn't sure if these 'differences' should be there...

**Comment by jungle-boogie** [comment]
The nightly I downloaded is identical to the second picture above.

**Comment by justinclift** [comment]
@chrisjlocke Yeah, the version info shown for our SQLCipher builds is a bit wonky.  We query the SQLCipher library for it's version number... but instead of telling us the correct info, it just returns the version of SQLCipher it's based on.  That info is probably helpful for some people (maybe feature detection?), but doesn't really match up with how we're doing things.

We do have an open DB4S issue about fixing the version number displayed for SQLCipher, but I'm not finding it right at the moment. 😦

**Comment by chrisjlocke** [comment]
Aah, pull 585...   
https://github.com/sqlitebrowser/sqlitebrowser/pull/585

**Comment by justinclift** [comment]
Thanks.  That's why I missed it... only looked in the Issues. :wink:

**Comment by revolter** [comment]
But the icon didn't change, right?

**Comment by jungle-boogie** [comment]
The builds for windows have been working for some time. Closing now. :)

**Comment by revolter** [comment]
@justinclift, Why does this Windows issue have the `linux` label? 😆

**Comment by justinclift** [comment]
The Windows nightly builds (at the moment) are cross compiled on an Arch Linux box. :wink:
