### ISSUE TITLE
Whenever I click the Browse Data tab, the selected table reverts to the first table in the database.

### ISSUE THREAD

**Issue by appjeanne** [sqlitebrowser/sqlitebrowser#757]
### Details for the issue

First I click on Browse data and choose a table, then I select another tab like Execute SQL.  When I then click the Browse Data tab, the selected table reverts to the first table in the database.
This is very annoying.  

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
This is linked to #744 which has recently been fixed.  However, we usually have 'nightly builds' which have the latest fixes and tweaks in them, but unfortunately, due to one of the latest fixes and tweaks, the program isn't compiling properly, so the nightlies aren't available.  However, check back in a couple of days, and theoretically, this issue might have been fixed.  Give @justinclift a hug (in a virtual sense, of course.....) :smile:

**Comment by appjeanne** [comment]
Thanks for your prompt reply!  I'll check back later!

**Comment by justinclift** [comment]
Sorru @appjeanne, I accidentally broke our automatic nightly builds while adjusting some settings.

In theory (!) it's fixed now, so the new nightly build tomorrow should be fine to use.  Though, we'll need to double check again anyway, just in case something else is still making it unhappy. 👼

**Comment by revolter** [comment]
@appjeanne, Can you test the [latest nightly build][1] and confirm that this is fixed?

  [1]: http://sqlitebrowser.oldsch00l.com

**Comment by appjeanne** [comment]
Yes it is fixed!! Thank you!

**Comment by justinclift** [comment]
Awesome.  Thanks for letting us know @appjeanne. :smile:
