### ISSUE TITLE
Make "reload" behaviour optimal per-tab

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#759]
[This is @revolter's idea, from: https://github.com/sqlitebrowser/sqlitebrowser/commit/684958b29ce3d26684d9142d73df773b11189d54#commitcomment-18843683]

@sqlitebrowser/developers, What do you say if we would have a reload button in the `Database Structure` as we have in the `Browse Data` tab?

If adding a button is not wanted, a problem I forgot to report is that if you hit <kbd>ctrl</kbd> + <kbd>r</kbd> in any tab you are, it reloads the currently selected table from the `Browse Data`, which doesn't make sense.

I propose it would do different things depending on the selected tab:
- `Database Structure`: reload tables count (and the actual tables) and/or the structure
- `Browse Data`: reload the currently selected table (as it does now)
- `Edit Pragmas`: do nothing
- `Execute SQL`: run the current SQL ([Sequel Pro](http://www.sequelpro.com) does this and I personally find it very intuitive and useful)

**Comment by chrisjlocke** [comment]
Just a nod (vote?) that we should (could?) use F5 for refresh/reload, etc ... seems more of a natural 'refresh button', especially if you've ever used a web browser! :wink:  Easier to do one handed, too....
But this is linked to the 'remap keys to what you want' featurette thats 'in the next version', so ... hmm...

**Comment by revolter** [comment]
On a mac, <kbd>cmd</kbd> + <kbd>r</kbd> reloads a page in the browser, and on Windows, IIRC, works with this and <kbd>F5</kbd> too. And I find it easier than going for the <kbd>F5</kbd> key, and I it would need the <kbd>fn</kbd> key to be pressed on some laptops with media features for the F keys.

Anyways, this was more about the idea rather than the shortcut, which, as you said, will be able to be configured.

**Comment by chrisjlocke** [comment]
Your suggestion is still a great idea. One key to rule them all! :wink:

**Comment by MKleusberg** [comment]
Should be done :smiley:

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by revolter** [comment]
I can't believe this! I can't wait to test it!

**Comment by MKleusberg** [comment]
Did you have a chance to test this yet, @revolter ? :smiley:

**Comment by revolter** [comment]
Sorry for the delay! I tested it now and it works like a charm. Being able to re-run a SQL with <kbd>cmd</kbd> + <kbd>r</kbd> too is a life saver.

One thing, I noticed that selecting the `Edit Pragmas` tab runs some `PRAGMA` queries to update the different checkboxes/inputs states/values. Could it also do this on refresh too?

**Comment by MKleusberg** [comment]
@revolter Done :smiley:

**Comment by revolter** [comment]
I was just thinking about this the other day :)) I'm gonna' test it tomorrow if I don't forget

**Comment by revolter** [comment]
Working like a charm, thanks!

**Comment by MKleusberg** [comment]
Awesome :D Thanks for testing!
