### ISSUE TITLE
FTS4 Support?

### ISSUE THREAD

**Issue by pbtura** [sqlitebrowser/sqlitebrowser#762]
I'm using the latest version of sqlitebroswer (3.9.0) on OSX 10.11. I need to run a query that uses FTS to do a full text search on one of my tables. However, when I actually run the query I get the error: "no such module: fts4". Does the version of sqlite that comes with sqlite browser  #not include fts3/4 support? If not, is there some way to add it, or to at least point the program to the sqlite version I have installed on my machine?

**Comment by justinclift** [comment]
Ahhh, interesting thought.  The OSX version includes SQLCipher, compiled using OSX Homebrew.  I didn't add the "--with-fts" option for the SQLCipher command line though. 😦 

If you have Homebrew installed, it's very simple to build a version with FTS support included (5-10 mins max):

```
$ brew install sqlcipher --with-fts
$ brew install qt
$ git clone https://github.com/sqlitebrowser/sqlitebrowser.git -b v3.9.x
$ cd sqlitebrowser
$ qmake CONFIG+=sqlcipher
$ make
```

The "DB Browser for SQLite" .app should now be in the src/ subdirectory.  You can drag it to /Applications or run it in place, etc. :smile:

Note in case it's useful, the above is a mash up of these two:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#macos-x
* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#build-with-sqlcipher-support

**Comment by pbtura** [comment]
I'll give that a try. Thanks so much.

**Comment by pbtura** [comment]
Hmmm... No luck. I opened the newly built app file, pasted in my query, and tried again and I got the exact same error message.

**Comment by justinclift** [comment]
Ahhh, just found something relevant.  Looking at the SQLCipher formula in Homebrew, the "--with-fts" option includes FTS5 not FTS4:

* https://github.com/Homebrew/homebrew-core/blob/47d7f56c299bf965cda82ae342763c683d183086/Formula/sqlcipher.rb#L30

Is it feasible to update your query for FTS5?

**Comment by pbtura** [comment]
I'll try it and see.

**Comment by pbtura** [comment]
I suspect that solution is not going to work now that I think about it. The virtual tables are being created by an iOS app and I'm pretty sure the version of sqlite that xcode uses does not support fts5 yet. Is there a way to build sqlcipher with fts4 instead of fts5?

**Comment by justinclift** [comment]
Yep.  In theory, changing the line in sqlcipher.rb file to say `-DSQLITE_ENABLE_FTS4` instead of `-DSQLITE_ENABLE_FTS5` should work.

eg: `brew remove sqlcipher`, then change the file, then `brew install sqlcipher --with-fts`.

The sqlcipher.rb file is probably in this location:

* /usr/local/Library/Taps/homebrew/homebrew-core/Formula/sqlcipher.rb

Make a backup of it first, and replace it when done (to be safe). :smile:

**Comment by justinclift** [comment]
Just tested that change here and it seems ok:

```
$ brew install sqlcipher --with-fts
==> Using the sandbox
==> Downloading https://github.com/sqlcipher/sqlcipher/archive/v3.4.0.tar.gz
Already downloaded: /Users/jc/Library/Caches/Homebrew/sqlcipher-3.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/sqlcipher/3.4.0 --enable-tempstore=yes --with-crypto-lib=/usr/local/opt/openssl --enable-load-extension --disable-tcl CFLAGS=-DSQLITE_HAS_CODEC -DSQLITE_ENABLE_FTS4
==> make
==> make install
🍺  /usr/local/Cellar/sqlcipher/3.4.0: 11 files, 2.2M, built in 39 seconds
```

The `FTS4` bit on the end of the `./configure` line looks like it's in effect.

Didn't try the rest of the build steps though.  Will leave that to you. 😀

**Comment by pbtura** [comment]
It does indeed work. Thanks again for all your help.

**Comment by justinclift** [comment]
You're welcome @pbtura. :smile:

**Comment by justinclift** [comment]
Oh, it's probably a good idea to run `macdeployqt` on the .app after you're built it too.  That will copy the OpenSSL, SQLCipher, and Qt shared library files out of the Homebrew directory, into your new "DB Browser for SQLite" app.

```
$ cd /Applications
$ macdeployqt DB\ Browser\ for\ SQLite.app -verbose=2
```

That way, if you uninstall OpenSSL, SQLCipher, or Qt from Homebrew, the .app won't suddenly stop working. :smile:
