### ISSUE TITLE
NET / Windows DateTime type

### ISSUE THREAD

**Issue by Plutonix** [sqlitebrowser/sqlitebrowser#763]
### Details for the issue

This is more a feature request/suggestion and is specific to .NET

If you define a column as 'DATETIME', the ("official") .NET DB provider objects can be configured to return actual .NET DateTime Types via SQLiteDataAdapter and SQLiteDataReader.

The "issue" is that DB Browser tends to ignore/discard "DateTime" and use INTEGER (or sometimes the last legal base type selected).  The only way is to use a CREATE TABLE statement in a SQL window.  Once the table is created, 'DateTime' shows in the column type list but **only** for those columns already defined that way.

This would likely be confusing for other platforms, so it might be useful to display 'NetDate` or similar to the user but use 'DateTime' in the CREATE statement.  Another option would be to enable it via a Preference.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [ ] 3.9.0
- [x] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Is this a DB4S issue, and not a SQLite issue?

> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values

>Each column in an SQLite 3 database is assigned one of the following type affinities:
* TEXT
* NUMERIC
* INTEGER
* REAL
* BLOB

So if you stored your date as text or numeric, its up to your program to convert the data?  In my .Net apps, I normally use `dateVariableImUsing=cdate(sqlreader("dateFieldInDatabase").value.tostring)`

**Comment by Plutonix** [comment]
The NET Provider is fully capable of creating/returning NET DateTime variables/DataTable columns.  **In spite of** DATETIME not being listed, it can be used in the table definition and the official NET provider will use it to do so.

It is a DB Browser issue because it wont allow/use DATETIME when creating a table.

**Comment by justinclift** [comment]
Interesting.  Trying to visualise how it's not working, but I'm kind of failing. 😦 

Is it feasible to show a screenshot or record a screencast or something of the bit that's not working?

**Comment by justinclift** [comment]
Looking at the table in section 3.2 [here](https://www.sqlite.org/datatype3.html), it seems like "DATETIME" is automatically treated by SQLite as the "NUMERIC" type.

If you define a field as "NUMERIC", instead of using SQL to create it as "DATETIME", does that allow the .NET DB provider objects to work with it properly?

**Comment by Plutonix** [comment]
![sqlitedates](https://cloud.githubusercontent.com/assets/12514284/18286901/70ac8a1c-743a-11e6-82ea-7f7e20d4d538.gif)

It relates to when defining a table.  The first part shows how even when I type in `DATETIME` it uses whatever - something from the dropdown list.  The second part shows how it acts with a table which was created in a SQL window. 

I _believe_ "DATETIME" acts like meta-data for the NET Provider.  The actual data format for dates is defined by connection string options.  The default stores an ISO8601 string.  The NET Provider sees "DATETIME" and returns DateTime objects - **only if that column is defined as DATETIME**.  

The NET provider knows to store date data  to an appropriate string which it will be able to parse **back** into a DATETIME type.  

The official DB Provider only does this for columns defined as DateTime **and** data which matches the DateTimeFormat setting in the connection string. Add this '...;DateTimeFormat=Ticks;...' to the connection string and the Provider will automatically save the ticks value for DateTime vars (thus saving the data integer/Int64).  Ticks also convert back to DateTime types (variables, datatable columns etc) provided the column is defined as DATETIME (ticks is less useful because it cannot distinguish UTC from local).

About Type Affinity

From that page: "_the recommended type for data stored in that column_" and "_Any column can still store any type of data._".  Without check constraints anything goes.  In the case of DATETIME, as I said, I think the Provider is doing all the magic based on the column info and the connection string option.  

As I said in the original posting, this is probably something that only .NET devs would want/need (no one seems to know that it works). Other platforms may well choke on it, so it might be something that is enabled as an option.

I have a working demo and decent explanation, but I cannot find a recent, applicable StackOverflow post to attach it to.

Hope this helps

**Comment by justinclift** [comment]
Thanks @Plutonix, that definitely helps show the problem. :smile:

From my perspective, I'd call this a bug in our handling of the field definition values.  We're not detecting when a person has typed their own value (eg `DATETIME`) into the Type field.  Instead, we just blindingly use the string value before it was overwritten.  eg `INTEGER`, `TEXT`, `BLOB`, etc.

If we change the code so it uses the manually entered string value, would that solve the problem from your perspective? (assuming the .Net provider then does it's bit correctly :wink:)

**Comment by Plutonix** [comment]
I think using something from the list is generally a good idea, since the list is complete except for this one (?) case.   There might be other types allowed - who knows,  I cant find this latent ability documented anywhere.  

Since other platforms might choke on it, is the reason I suggested an option.  When *Enable NET DateTime* is on, add DateTime and Date to the list (I am not sure it actually treats Date differently).

Here is a reason this could be very valuable:  if you execute a CREATE TABLE statement from your NET app, Type Affinity apparently kicks in and also changes* DATETIME* to *TEXT*.  That means for NET devs they **need some sort of tool** like this to create tables that support DATETIME types.  The Execute SQL tab works perfectly.

**Comment by justinclift** [comment]
Cool, this is probably doable. :smile:

**Comment by justinclift** [comment]
Cool, this is probably doable. :smile:

**Comment by justinclift** [comment]
Cool, this is probably doable. :smile:

**Comment by chrisjlocke** [comment]
Just a query, but when you type 'datetime' in the text field, are you pressing Enter?  If I do that, 'DateTime' is set for the field...

**Comment by revolter** [comment]
We need to update the create statement with the current `Type`'s value on blur too, not only when pressing <kbd>Enter</kbd>.

**Comment by justinclift** [comment]
When you say "on blur", what do you mean? :smile:

**Comment by glawrence** [comment]
Well, blur is the opposite of focus, so it is when a control loses focus, irrespective of where it goes to

**Comment by justinclift** [comment]
Thanks, makes sense. :smile:

**Comment by chrisjlocke** [comment]
Never knew that either...

**Comment by alewis-github** [comment]
Sorry to add a comment to this a year later, but I have the same problem trying to display dates imported from SQLServer into a SQLLite db. I'm not really sure whether this should be a new question or not, as I am just wondering whether, when you right-click on the header of a data column in the DBBrowser a real "custom" format could be entered?

The dates are being returned as .Net "ticks", which are the number of 100 nanosecond units since 01/01/0001. My program converts them with no problem, but it would be really useful to see them as real dates in the browser, rather than 18-digit integers.

**Comment by justinclift** [comment]
@alewis-github It's no worries.  Adding a custom format would definitely be welcome.  From previous quick discussion though, it's likely a pain to implement so not sure if/when it'll get done.

That being said, if anyone with the time and inclination to get it done submits a PR, we'd definitely accept it (assuming code quality is decent of course). :smile:

**Comment by MKleusberg** [comment]
Fully custom display formats have been implemented for some time now. So closing this issue. Feel free to reopen it if any issues remain here :smiley:
