### ISSUE TITLE
FireDAC (Delphi) encryption

### ISSUE THREAD

**Issue by Mikanoshi** [sqlitebrowser/sqlitebrowser#764]
### Details for the issue

Add support for Delphi FireDAC's SQLite encryption, if it's not too complicated :)
It uses aes-256 by default (and it alone will be enough), but supported ciphers are:
_aes-128, aes-192, aes-256, aes-ctr-128, aes-ctr-192, aes-ctr-256, aes-ecb-128, aes-ecb-192, aes-ecb-256_

> The encrypted database format is not compatible with other similar SQLite encryption extensions. This means that you cannot use an encrypted database, encrypted with non-FireDAC libraries. If you need to do this, then you have to decrypt a database with an original tool and encrypt it with FireDAC.

> The encryption is provided through the officially supported SQLite approach - custom codec code and compilation with SQLITE_HAS_CODEC defined. All encryption routines are implemented on Delphi and embedded into the sqlite3 code.

> http://docwiki.embarcadero.com/RADStudio/Seattle/en/Using_SQLite_with_FireDAC#SQLite_Encrypted_Database

Actually, encryption is based on SQLCipher as stated in [sources](https://gist.github.com/Mikanoshi/a7b92e807967b3af602ee527dfccee0e):
> // FireDAC SQLite driver encryption feature is derived from the following work:
> (*
> ** SQLCipher
> ** crypto.c developed by Stephen Lombardo (Zetetic LLC)
> ** sjlombardo at zetetic dot net
> ** http://zetetic.net
> **
> ** Copyright (c) 2009, ZETETIC LLC
> ** All rights reserved.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux
- [ ] Mac OS
- [ ] Other

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
If FireDAC provides a drop-in-replacement for the sqlite3.dll which we could use, this might be an option.  Any idea? :smile:

**Comment by Mikanoshi** [comment]
I use static linking, because encryption is only available there)

**Comment by justinclift** [comment]
Ahhh.  I was asking a different thing. :wink:

With SQLCipher, they provide a drop in replacement .dll for the SQLite one.  With that, it meant our code didn't need much changing to add a few specific SQLCipher calls to get the encryption working.

I'm wondering if FireDAC can do the same thing, as it's hard to see from that link what kind of suitable download they provide. 😦

**Comment by Mikanoshi** [comment]
> Static linking -- the following client libraries are statically linked into the application:
>     Win32 - x86 sqlite3_x86.obj
>     Win64 - x64 sqlite3_x64.obj 
>    Note: SQLite database encryption is supported only for static linking. 
>
>    Dynamic linking -- the following client libraries must be available in order to open a SQLite database:
>        Win32 - x86 SQLITE3.DLL
>        Win64 - x64 SQLITE3.DLL 

http://docwiki.embarcadero.com/RADStudio/Berlin/en/Connect_to_SQLite_database_(FireDAC)

**Comment by justinclift** [comment]
Thanks, that's easier to grok. :smile:

We'll probably not add support for FireDAC (Delphi) encryption then.

If at some point they add support for encryption with shared library (non-static) builds, we're completely ok with re-opening this issue to look at it again. :smile:

**Comment by Mikanoshi** [comment]
Look at that source file I uploaded, there are sqlite3_* functions with cdecl calling convention that are defined in obj file, inside the file there are mentions of sqlite3.c and CodeGear C++ 7.20 compiler.
Maybe it's possible to just convert it to dll?)

**Comment by Mikanoshi** [comment]
This is an obj file in COFF64 format, maybe it can be linked directly with 64-bit version of DB4S:
[sqlite3_x64.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/455907/sqlite3_x64.zip)
or make a DLL out of it, somehow :)

**Comment by justinclift** [comment]
Yeah, it might be feasible to do, with some digging.

Would you have the time/inclination to look into it? :smile:

**Comment by Mikanoshi** [comment]
You mean in C++?) No, I can only provide libs, and maybe create a DLL, but it wouldn't be any different, if the above obj can be linked already.

**Comment by ch4rl3s** [comment]
Hi, You have a demo how to decrypt using Delphi, I tried but dont work.
 FDSQLiteSecurity1.Database := 'demo.db';
  FDSQLiteSecurity1.Password := '123';
  FDSQLiteSecurity1.RemovePassword;

thanks.

**Comment by justinclift** [comment]
> You have a demo how to decrypt using Delphi

Are you sure that's us?

**Comment by ch4rl3s** [comment]
yes, I only want any idea why not work decrypt using Delphi.

**Comment by justinclift** [comment]
Ok.  What's the URL for the Delphi demo?  My memory is being fuzzy, so I'm not remembering it. :smile:

**Comment by Mikanoshi** [comment]
> Hi, You have a demo how to decrypt using Delphi, I tried but dont work.
> FDSQLiteSecurity1.Database := 'demo.db';
> FDSQLiteSecurity1.Password := '123';
> FDSQLiteSecurity1.RemovePassword;

No idea how it's relevant to this issue :) but the code is correct, that's how you remove password.
It's not complete though, DriverLink is required, see my code here:
https://code.highspec.ru/Mikanoshi/RnQ/src/branch/master/RnQ/SQLiteDB.pas#L262
