### ISSUE TITLE
mouse unable to be seen in debian

### ISSUE THREAD

**Issue by pchtsp** [sqlitebrowser/sqlitebrowser#765]
### Details for the issue

When I open the application my mouse is frozen outside (in the margin) of the program. The mouse works correctly with every other application.
The mouse actually is working because buttons become selected and I can click on things but I do not see where it is aiming.

It's like the window doesn't get along with the pointer.

The rest appears to work correctly.

### Useful extra information
I'm using it on Maru OS (runs debian on ARM). Tried restarting but nothing.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [X] Linux: ( _distro:debian)
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.0
- [X] 3.8.0
- [ ] Other:3.8.5

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Version 3.8.0 is a bit old now, and we've made a **lot** of changes for the recent 3.9.0 release.

Are you comfortable with compiling things yourself?  If so, the instructions for Ubuntu **might** "just work":

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

As an alternative idea, @deepsidhu1313 may have suggestions.  He creates our official Debian/Ubuntu packages, and may find [Maru OS](https://github.com/maruos/maruos) interesting. :smile:

**Comment by justinclift** [comment]
@pchtsp ping?

**Comment by deepsidhu1313** [comment]
Hi @justinclift & @pchtsp. Do you guys need my help ?? Sorry it took me sometime to respond. I can look into the bug if still exist in 3.9 on debian. may be i will be able to figure it out if it is related to packaging or anything else. Thanks.

**Comment by justinclift** [comment]
@deepsidhu1313 Any idea about building 3.9.0 for Maru? (eg Debian on ARM) :smile:

**Comment by deepsidhu1313** [comment]
I already deployed packages for that (arm) on my ppa. But dont worry i will
create another ppa for just for testing this bug.

**Comment by justinclift** [comment]
Thanks @deepsidhu1313. :smile:

**Comment by pchtsp** [comment]
Hey! Thanks both for the quick answer and the help. I do feel comfortable
building from source. As soon as I plug my phone to an HDMI screen, I will
test building it.

I'll keep you informed. And thanks again!

F.

**Comment by pchtsp** [comment]
@justinclift @deepsidhu1313 .

Just tried compiling with ubuntu instructions. Worked. I have only checked that I can indeed see the mouse over the GUI and load a database I had.

The previous version was 3.8.5 so I guess it could be a good idea to update the repository.

thanks again!
F.

**Comment by justinclift** [comment]
Awesome @pchtsp, that's good news. :smile:

Out of curiosity, which repository had 3.8.5 in it, so we can investigate?
