### ISSUE TITLE
Two or more commented lines causes a query to fail

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#766]
### Details for the issue

Having a query like:

```
SELECT * FROM table
-- comment 1
-- comment 2
```

causes it to fail with the error:

```
Error executing query: SELECT * FROM table
-- comment 1
-- comment 2
```

Removing either one makes the query succeed. Even running:

```
SELECT * FROM table

-- comment 2
```

completes successfully.

### Useful extra information

This was added in `3.9.0`, as it was working well in `3.8.0`.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Do you reckon the regex for stripping comments might be the cause?

**Comment by revolter** [comment]
Can you point me to it?

**Comment by revolter** [comment]
If the comments are removed by us, then the `Show SQL submitted by Application` shows the wrong content, as the comments are present there.

**Comment by justinclift** [comment]
Well spotted. :smile:

This is the regex springing to mind: https://github.com/sqlitebrowser/sqlitebrowser/commit/f37c162c183595179c50f7aada14fe6acdb85f79

**Comment by revolter** [comment]
Oh, yes, sorry :( I'll fix it in a couple of hours.

**Comment by revolter** [comment]
We didn't change to Qt5 only, right? :( Because Qt5 allows me to solve it very easy.

**Comment by justinclift** [comment]
Correct.  We're still supporting Qt4 for now. 😦
