### ISSUE TITLE
SQL log incorrectly shows statements not executed

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#768]
### Details for the issue

If you enter various SQL statements in the 'Execute SQL' tab but only execute specific lines, while these are correctly executed, the log shows the executed statement, plus those that followed.  The statements that followed are however, not actually executed.  The log window is therefore being naughty and lying.

A screencast of what I'm mumbling about.
http://screencast-o-matic.com/watch/cDQjFdjQiF 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good catch. :smile:

**Comment by chrisjlocke** [comment]
hehe- that just reminded me of this GIF...
http://i.imgur.com/ph4TKDK.gif

"Did you just catch that?"

**Comment by justinclift** [comment]
😏

**Comment by revolter** [comment]
[This][1] is another problem related to this one.

  [1]: https://github.com/sqlitebrowser/sqlitebrowser/issues/766#issuecomment-245578686

**Comment by revolter** [comment]
Wait, it looks like only in the `Show SQL submitted by User` the comments appear, but I'm pretty sure that at work, those appeared in `... Application` too.

**Comment by revolter** [comment]
@chrisjlocke, Can you test this with 55d8905 applied?

**Comment by chrisjlocke** [comment]
I can confirm this is resolved in the latest nightly.  Whatever we're paying you, should be doubled. :wink:
