### ISSUE TITLE
[Enhancement] Focus the newly created field after clicking 'Add field'

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#769]
### Details for the issue

Bit of a pet peeve, but don't know what the 'ease of implementation' is.  
When you click 'Add field' in the 'Edit Table Definition' dialog, a new field is created, but depending on the number of fields already in the table, this field is below the horizontal scrollbar, so you have to scroll down first to find it, then click it twice to edit it (there is a 0.0003% chance 'Field10' would ever be the desired name for your field, so when clicking 'Add Field', the first thing you want to do is rename it) then rename it, etc.  It would be nice if the focus could flip to the new field, that it was viewable, and even cooler if the fieldname was already in edit mode.  The last bit is probably a step too far though and asking for the colour of the moon to be changed... 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Changing the view to show the new field could probably be done with a handler which catches the "Add Field" button click.  The edit mode bit needs a bit of thinking about though.  Not sure if it's always desirable behaviour or not?  (thinking maybe it's fine, but not yet sure)

**Comment by chrisjlocke** [comment]
If you click 'Add field' and it switches focus, if you didn't want it to, (as your mouse pointer would still be on it) you'd just push the 'Add field' button again, if thats what you wanted to do.  I can agree it wouldn't always be desirable, but equally, it has no drawback or causes problems.  maybe.  Heck, I don't know... maybe it should make me a coffee too while its at it! :wink:

**Comment by revolter** [comment]
Even though I don't know what @chrisjlocke's 0.0003% statistic is based on (joke), I completely agree with this.

**Comment by revolter** [comment]
@chrisjlocke Done! Can you test and see if it works ok (and that I understood it ok)?

**Comment by chrisjlocke** [comment]
Excellent - thanks!   Will check it and let you know.  If you get a knock at your door and some bald guy gives you a big sloppy kiss......no, that won't be me..... ;)

**Comment by revolter** [comment]
😆 I personally felt the need of this too, but didn't take time to solve it :D

**Comment by chrisjlocke** [comment]
This is fantastically perfect.  Not just perfect, but better than perfect!  Seriously - this is such a great improvement in terms of usability.  What with this one and the 'now-defaulting-to-the-field-type-you-want', I've finished coding my databases before I've even started!  

Thanks @revolter for resolving this so quickly.  Appreciated.  :smile_cat:
