### ISSUE TITLE
Create Windows nightly builds for Qt5

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#775]
We need to update our nightly builds on Windows to use Qt5 + SQLCipher.

This can be done from the Windows command line using `msbuild` + MSVC 2013.

It's probably a decent idea to learn Powershell for this too, instead of using cmd.exe.

**Comment by justinclift** [comment]
Initial scripting is done, and runs ~4:30am each morning (UK time), with the uploads going to the nightly build server:

* http://nightlies.sqlitebrowser.org/win32/
* http://nightlies.sqlitebrowser.org/win64/

There's no monitoring in place yet for failed builds, which will be [the next step to set up](https://github.com/sqlitebrowser/sqlitebrowser/issues/800) (not hard).

**Comment by innermous** [comment]
>It's probably a decent idea to learn Powershell for this too, instead of using cmd.exe

See, we done it with native tools :)

**Comment by justinclift** [comment]
:wink:
