### ISSUE TITLE
"Execute SQL" output does not escape HTML entities

### ISSUE THREAD

**Issue by wodim** [sqlitebrowser/sqlitebrowser#777]
![2016-09-16_16-05-14](https://cloud.githubusercontent.com/assets/1001553/18588595/6abafd24-7c27-11e6-8243-b27b781578e0.png)

**Comment by justinclift** [comment]
Ahhh, well spotted.  Yeah, that should be fixed. :smile:

**Comment by justinclift** [comment]
@wodim This should be fixed now. :smile:
![screen shot 2016-09-27 at 15 24 23](https://cloud.githubusercontent.com/assets/406299/18878023/0d370fbe-84c7-11e6-8e73-b132242da2db.png)

Would you be ok to try the nightly build (tomorrow), to verify it from your point of view? :smile:

**Comment by wodim** [comment]
Yes, it's fine now.

**Comment by justinclift** [comment]
Excellent.  Thanks for verifying and getting back to us @wodim. :smile:
