### ISSUE TITLE
Typo in About dialog

### ISSUE THREAD

**Issue by TorbenJ** [sqlitebrowser/sqlitebrowser#778]
### Details for the issue

There is a typo in the About dialog of DB4S.
The label "SQLCipher-Version 3.11.0" actually says "SQLCiper-Version 3.11.0" so there is a missing "h" in "Cipher".

Just a very minor issue but I noticed it so I report it :)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
(This label is not available in the nightly version)
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment]
Fixed in 1257134. It was the German translation who had this typo.
