### ISSUE TITLE
Pass crypted database password from command line

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#779]
### Details for the issue

It would be great if one could open an SQLCipher crypted database from the command line by setting a `password` argument to the command, so the password promt dialog would be skipped.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
This would be useful, as least for our main target audience (eg people using their own desktops).

One thing to be aware of though, passwords passed on the command line can be a security problem in a multi-user environment. (eg several people logged into the same computer)

When someone does a `ps` (or anything similar) from the command line to show the process list, it shows the running commands... and their command line options.  If there's only one person on a computer, that's not a huge worry.  But on a multi-user system... this would show other users which encrypted file you're opening, and the password for it.  Oops. 😉

**Comment by justinclift** [comment]
Just to be clear, I still think this would be useful. :smile:

**Comment by revolter** [comment]
Well, I'm pretty sure I saw other well-known commands (which I can't remember now) that ask for your password. I think it's the user's problem, not ours, we really can't do anything regarding this.

**Comment by justinclift** [comment]
It could.

**Comment by revolter** [comment]
So, should we vote or something? 😄

**Comment by justinclift** [comment]
If you want. :smile:

Personally, I'm ok with you adding this... as long as we clearly spell out where it's useful, and where it's a bad idea.  That way, people at least have the option to use it when it's suitable.

**Comment by revolter** [comment]
Well, my reason was to speed opening crypted databases faster. Like creating an alias that quickly/directly opens a database without the need to manually enter a password. But from what I read [in this serverfault question][1], it's completely forbidden.

  [1]: http://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument

Thinking that the `.db4s` file in `$HOME` sounds a pretty good solution, what do you think?

**Comment by innermous** [comment]
I don't think about it, I'm not considering introducing such a vulnerable thing. Password typing is zero cost operation, stop inventing the wheel.

**Comment by revolter** [comment]
When you enter is tens of times every day, is not zero cost operation. But I understand your point.

**Comment by innermous** [comment]
Why closed? That was just my opinion.

**Comment by revolter** [comment]
You told me to stop inventing the wheel. And indeed, for multiple users on the same computer or other configurations, this isn't safe. It only applies to my specific use case, so I'll just implement it in my fork.

**Comment by justinclift** [comment]
A weird thought occurs... if we had a plugin system, this could be done as an optional plugin. :smile:

**Comment by innermous** [comment]
Well, this might be useful in special use cases. We might implement this and add an appropriate checkbox in settings window, with advising users use this carefully, since it can be total disaster in security means.
