### ISSUE TITLE
Error creating/dropping FTS5 table

### ISSUE THREAD

**Issue by aludee** [sqlitebrowser/sqlitebrowser#781]
Creating fts5 prompts an error.

no such module: fts5: CREATE VIRTUAL TABLE article_fts5_001 USING fts5(content="article", platform, title, segment_text)
### Useful extra information

The virtual table article_fts5_001 is created, but the fts support tables are not.
Also the virtual table cannot be dropped.

<img width="430" alt="screen shot 2016-09-20 at 4 58 57 pm" src="https://cloud.githubusercontent.com/assets/9464400/18664050/ad270e62-7f53-11e6-8691-ec7f4eee7687.png">
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
We had something similar with FTS support and OSX.  (See #762).  Wanna change your OS? :wink:
@justinclift started mentioning homebrews and stuff - think he might have got confused with his whiskey collection.  None of that really helps you, but can only assume DB4S for Windows can be 'tweaked' to include FTS support....  @justinclift will bounce along soon and either confirm or ... something else.

**Comment by justinclift** [comment]
Yeah.  Sorry about this @aludee 

On Windows the version of SQLCipher (a encryption enhanced replacement for SQLite) we used was compiled without any of the SQLite extensions.

It's only due to a lack of time for researching if/how to compile them in.  It's completely possible the FTS5 module is easy to add, it's just no-one's yet looked into it.

If someone with a working DB4S build system has time to investigate, then provide steps to SQLCipher with FTS5, that would make things easy for the next release. :smile:

**Comment by aludee** [comment]
Thanks @justinclift and @chrisjlocke for the prompt response =)

@justinclift i found an old thread during the release of 3.8 (https://discuss.zetetic.net/t/db-browser-3-8-0-for-sqlite-sqlcipher-released/969). Could it would be possible to get the developers at zetetic to compile the updated SQLCipher with the new SQLite extension for FTS5?

**Comment by justinclift** [comment]
You're on the right track. :smile:

With our Windows release, I compiled SQLCipher myself using the instructions here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-—-Compiling-SQLCipher

The exact code I used is here:

&nbsp; &nbsp; https://github.com/justinclift/sqlcipher

It's a fork of the original SQLCipher branch, with the changes made to it as written in that doc.  That repository has a branch each for 32-bit and 64-bit Windows, as there were slightly different path changes needed.

For FTS5 support on Windows, we just need someone to spend some time doing that compile again, then figuring out how to add FTS5 to it.  It might not be difficult, it's just that none of us have looked into it yet.

If you have the time/inclination to get that done, we're *absolutely* open to including FTS5 in our next releases. :smile:

Does that help?

**Comment by aludee** [comment]
Thanks for sharing the instructions!
I will try to see what I can come up with.

Once again, thanks for sharing :smile:

**Comment by justinclift** [comment]
You're welcome.  We all help out where we can. :smile:

**Comment by pmoorelegistek** [comment]
Has there been any progress on this? Can I help in any way? Would really like to be able to try out FTS5 using DB Browser. Thanks.

**Comment by justinclift** [comment]
Updated the windows build scripts just now.

The nightly builds on Windows - both with and without encryption -now include the FTS3, FTS4, FTS5, and JSON1 extensions.
