### ISSUE TITLE
Can't open from commandline - OS X

### ISSUE THREAD

**Issue by loeschg** [sqlitebrowser/sqlitebrowser#782]
```
Version 3.9.0
Qt Version 4.8.7
SQLCipher Version 3.11.0
```

Trying to open from the command line (and pass a db as a command line parameter), and it's not working. I'm not able to open from the command line at all and was wondering if somebody might have some insight.

```
> open ./DB\ Browser\ for\ SQLite.app
The application cannot be opened because its executable is missing.
```

When directly trying to execute
```
> ./DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite
Sep 20 16:23:31  DB Browser for SQLite[16536] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Sep 20 16:23:31  DB Browser for SQLite[16536] <Error>: On-demand launch of the Window Server is allowed for root user only.
Sep 20 16:23:31  DB Browser for SQLite[16536] <Warning>: CGSLookupServerRootPort: Failed to look up the port for "com.apple.windowserver.active" (268435459)
Sep 20 16:23:31  DB Browser for SQLite[16536] <Error>: On-demand launch of the Window Server is allowed for root user only.
Sep 20 16:23:31  DB Browser for SQLite[16536] <Warning>: CGSLookupServerRootPort: Failed to look up the port for "com.apple.windowserver.active" (268435459)
Sep 20 16:23:31  DB Browser for SQLite[16536] <Error>: This user is not allowed access to the window system right now.
_RegisterApplication(), unable to get application ASN from launchservicesd, and this application requires an ASN, so aborting.  error=#-1.
[1]    16536 abort      ./DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite
```

**Comment by justinclift** [comment]
Hmmm, that doesn't seem happy at all. 😦 

Which version of OSX is this happening on?

**Comment by justinclift** [comment]
As an experiment, would be ok to try compiling it yourself?

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#building-an-app-bundle

If you have OSX Homebrew already installed, it's very easy. (5-10 mins max)

Asking because that's something I do fairly often, then use `open` (as you show above) to start it up.  This has generally worked for me... but it could be my system is configured strangely. 😇

**Comment by loeschg** [comment]
Running OS X - 10.11.6

Will give that a go and report back.

**Comment by loeschg** [comment]
What the heck. I followed those steps, and now opening works fine from command line, even without using the newly built `.app`. ¯\_(ツ)_/¯

**Comment by loeschg** [comment]
Yeah, some configuration must have changed. In my older iterm session, I still get the same error as I initially posted. If I open a new session/tab in iterm, it works correctly.

**Comment by justinclift** [comment]
Yeah, that sounds like a weird one. :wink:
