### ISSUE TITLE
Lots of QGradient::setColorAt messages to stdout

### ISSUE THREAD

**Issue by mafagafogigante** [sqlitebrowser/sqlitebrowser#783]
### Details for the issue

After playing with DB4S on Linux I got back to the terminal to see about 100 occurrences of 

```
QGradient::setColorAt: Color position must be specified in the range 0 to 1
```
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [X] DB4S has another problem
#### I'm using DB4S on:
- [X] Linux: (Fedora with 4.6.6-200.fc23.x86_64)
#### I'm using DB4S version:

Current master branch.
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

---

I have no experience with Qt. If this is known or expected, just close this issue. If I am the only one to see this, it may be an installation-specific bug. There seem to be no references to `QGradient` in the tree, so I am somewhat clueless as to what is this.

I don't consider this a bug, but is certainly an odd thing.

**Comment by justinclift** [comment]
Yeah, we do see a number of unusual messages like this on the output.  Some seem to be generated by DB4S, and others generated by Qt itself.

We've not yet put time into tracking down and fixing the one which don't sound critical though.

**Comment by mafagafogigante** [comment]
Just to let the little debugging I did in this time recorded somewhere:

If you let the cursor blinking in a state such as the following

![bug-cropping-sqlitebrowser](https://cloud.githubusercontent.com/assets/8271090/18711170/0664d492-7fdf-11e6-974d-87f84d0dc5da.png)

> "Field 1" is focused for editing.

You get a few of the reported messages per second to standard output.

**Comment by justinclift** [comment]
That does seem odd.

**Comment by MKleusberg** [comment]
I cannot reproduce it either. But it looks indeed like a theme thing, so maybe it depends on the desktop environment you're using or something similar.

The only thing I get in the Edit Table dialog are occasional warning which look like this:
```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 3467, resource id: 44167828, major code: 40 (TranslateCoords), minor code: 0
```
But that seems totally unrelated.

**Comment by mafagafogigante** [comment]
I will rebuild and see if this still happens. Maybe a newer Qt version has fixed it. If it is still reproducible, I will share some version numbers.

**Comment by mafagafogigante** [comment]
I could not reproduce this using feda408161ae98fee69bfd46a91c607bbc40921d under an up-to-date Fedora with 4.13.9-200.fc26.x86_64.

You can close this issue, as the problem (whatever it was) seems to have been fixed.

**Comment by mgrojo** [comment]
Thanks for reporting and testing!
