### ISSUE TITLE
Browse Data tab does not remember the selected table

### ISSUE THREAD

**Issue by davidhedley** [sqlitebrowser/sqlitebrowser#784]
### Details for the issue

Switching to the "Browse Data" tab resets the Table dropdown to the first item. It should remember the previously selected table (if any). I would say this is a bug - it seems to remember the row position when switching to the tab but not the table!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment]
This issue was already reported here: #757.

It was fixed and will be available in the next 3.9.1 release. 😄

**Comment by chrisjlocke** [comment]
...or the next nightly, assuming that gets resolved before 3.9.1 is released... :wink:

**Comment by davidhedley** [comment]
Many thanks. I didn't spot the duplicate issue in the list. Sorry to waste your time and keep up the great work!

**Comment by revolter** [comment]
Not a problem. And as @chrisjlocke mentioned, you can try the nightly version until the release, which, AFAIK, contains the fix.
