### ISSUE TITLE
Name "DB Browser for SQLite" has spaces which cause "missing separator"

### ISSUE THREAD

**Issue by RH-Euronext** [sqlitebrowser/sqlitebrowser#786]
### Details for the issue
There are two related issues:
1) the name was changed to “DB Browser for SQLite” (in 2014, I think) but the spaces (with cmake version 3.6.1) cause a “missing separator” problem when make is run.
2) After a local correction to 1), later. 
sudo make install 
failed because src/icons/DB_Browser_for_SQLite.png, distri/DB_Browser_for_SQLite.desktop and distri/DB_Browser_for_SQLite. .appdata.xml don't exist.

### Useful extra information

For me, the solution for 1) was to simply vi into CMakeLists.txt and 
1,$s/DB Browser for QLite/DB_Browser_for_SQLite/g

For 2) there is a sqlitebrowser.* for each of them – so I replaced them, after which the make install worked.

#### I'm opening this issue because:

- [X] DB4S won't build per its instructions.

#### I'm using DB4S on:

- [X] Linux: ( _distro: Red Hat Enterprise Linux Server release 7.2 (Maipo) )

#### I'm using DB4S version:

- [X] 3.9.0

#### I have also:

- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks Richard.  We'll be making a 3.9.1 release in the near future, which is probably a good time for getting this fixed. :smile:

**Comment by RH-Euronext** [comment]
Well I should say thanks to you guys for the product.
Seems to work very well so far as I’ve used it.

It will participate in a significant demo next Friday!

**Comment by justinclift** [comment]
Awesome. 😀

**Comment by justinclift** [comment]
@RH-Euronext Just tried this here on a CentOS 7-1511 install.  Both `cmake` and `make` compiled fine (no errors), though I did have to install both `cmake` and `gcc-g++` which our docs were missing (now fixed).

I only tried with our latest development source code though, not our previous 3.9.0 release tarball.

Is it feasible for you to compile from git source?

**Comment by RH-Euronext** [comment]
Sure I can compile from source.

Maybe our cmake is old?  3.6.1…

**Comment by justinclift** [comment]
CMake 3.6.1 is fine.  :smile:

With the bug in this issue, I *think* it's a duplicate of https://github.com/sqlitebrowser/sqlitebrowser/issues/758.  That was fixed ~1 month ago in our master branch in git, with https://github.com/sqlitebrowser/sqlitebrowser/commit/2957974974bb874b0219e52d63c198658c02f686.

If you want to try compiling with our git head, it should "just work". :smile:

We're also putting out a minor bug fix release (3.9.1) soon (maybe tonight), if that's useful.

---

On a side note, CMake 3.6.0 and earlier can generate windows binaries with a (low risk) [security problem in them](https://cmake.org/pipermail/cmake-developers/2016-July/029039.html).

Your version (3.6.1) has the main fix for that problem in it, so no worries there.

**Comment by justinclift** [comment]
Closing this, as I'm really sure it's a duplicate.  @RH-Euronext If if your testing it turns out not to be, you're definitely welcome to reopen this so it can be investigated. :smile:
