### ISSUE TITLE
Interesting way to show contributors

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#787]
The Serverless project has an interesting way to show contributors:

&nbsp; &nbsp; https://github.com/serverless/serverless#contributors

We might want to do similar.  Even for release notes. 😀 

Thoughts?

**Comment by mafagafogigante** [comment]
Seems good. Do you know what they use to generate the HTML?

**Comment by justinclift** [comment]
Looking at the source for their README.md, they seem to be embedding HTML directly.

eg, this is their first entry:

    | [<img src="https://avatars.githubusercontent.com/u/2752551?v=3" width="75px;"/><br /><sub>Austen </sub>](http://www.serverless.com)<br /> |

So, one of those per person, with the various bits tweaked to match (eg avatar, name, URL).

**Comment by innermous** [comment]
What's the point in that, after all?

**Comment by justinclift** [comment]
Some people like having their picture on things they do.  It's a different form of giving recognition.

**Comment by innermous** [comment]
@justinclift what's wrong with "Contributors" tab? It's just for that.

**Comment by justinclift** [comment]
Nothing in particular wrong with it, it's just having stuff on the README.md will appeal to some. :smile:

**Comment by revolter** [comment]
Yeah, the `Contributors` tab seems nicer, with graphs and stuff.

Having them in the `README` seems a duplication of info, bloating the file, and requiring often syncs.
As probably some people don't know about the tab's existence, we could add a `Contributors` section in the `README` like this:

## Contributors

You can see the list by going to the [__Contributors__ tab](https://github.com/sqlitebrowser/sqlitebrowser/graphs/contributors).

**Comment by mafagafogigante** [comment]
@revolter makes a good point regarding the added maintenance burden.

**Comment by justinclift** [comment]
No worries at all.  Let's close this. :smile:
