### ISSUE TITLE
Implement switching tabs using Alt modifier + number

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#788]
Being able to switch tabs in the Main Window interface using keyboard shortcuts (eg Alt+1, Alt+2, etc) would be useful.

@innermous has implemented it in https://github.com/sqlitebrowser/sqlitebrowser/commit/11558a86b45a65e01d49a46b6cf4ec0231f36aff & https://github.com/sqlitebrowser/sqlitebrowser/commit/45e17c9b497eafa8000c73eb60fcfce5c419d151.

Just to be careful, before merging that into 3.9.1 we should test the result under both Windows and OSX to ensure we're not conflicting with existing key bindings.

**Comment by justinclift** [comment]
Testing here on OSX, Alt+[number key] isn't working.  I'll dig into it a bit later on.

**Comment by innermous** [comment]
@justinclift :open_mouth: 
Why wouldn't it work on OSX?

**Comment by justinclift** [comment]
Yeah, I have no idea.  Looking at it visually, nothing seems wrong.

I'll dig into this properly fairly soon.

**Comment by innermous** [comment]
I'll stay tuned, this is important issue.

**Comment by justinclift** [comment]
Looking into this at the moment.  It *seems* like `QKeySequence` might be better than `QKeyEvent` for this.  Not sure yet, still reading.

As a first investigation thing, I changed the current code to this:

    int keyPressed = event->key();

    switch (keyPressed)
    {
    case Qt::Key_1:
        tab = Tabs::StructureTab;
        break;
    case Qt::Key_2:
        tab = Tabs::BrowseTab;
        break;
    case Qt::Key_3:
        tab = Tabs::PragmaTab;
        break;
    case Qt::Key_4:
        tab = Tabs::ExecuteTab;
        break;
    default:
        break;
    }

With a breakpoint on the `keyPressed` variable to see what it shows.  It keeps coming back with a value of `0x01000023`.  So, it's catching the initial press of the Alt key.

**Comment by justinclift** [comment]
Reading the `QKeySequence` and `QShortcut` class docs, they seem better suited to multiple-key combinations.

Something like (say) `QKeySequence(Qt::ALT + Qt::Key_1)` might work, added to a `QShortcut`.

**Comment by justinclift** [comment]
@innermous Do you want to investigate this, or should I keep at it? :smile:

**Comment by justinclift** [comment]
One approach (only tested on OSX) is this: https://github.com/justinclift/sqlitebrowser/commit/3aec905180f840186337f41f23c8c19789d0fd41

That still needs work though:

* The key combo doesn't always work straight away.  Sometimes tabs need to be manually changed first, and **then** all of the key combo's work.  This is weird, and obviously not going to be workable as-is. 😦 
* The switchToBrowseTab() method can also be called from the right click "Browse Data" context menu option in the Database Structure tab.  When that happens, it's supposed to switch to the currently selected table, but doesn't.  It's always just switching to the first table.  This needs fixing too.

**Comment by innermous** [comment]
It's nonsense, you are doing something wrong.
Switch block captures value only **once**.

**Comment by innermous** [comment]
@justinclift 
>The key combo doesn't always work straight away. Sometimes tabs need to be manually changed first, and then all of the key combo's work. This is weird, and obviously not going to be workable as-is.

This happens if something else is focused, this is normal.

**Comment by justinclift** [comment]
It's definitely possible I'm doing something wrong. :smile:

The keyPressEvent() though is definitely firing as soon as the alt key is pressed, and not waiting for the full key sequence.

**Comment by innermous** [comment]
@justinclift and the next keyPressEvent is fired as soon as you press another key holding alt.

**Comment by justinclift** [comment]
Ahhh, I see what you're meaning.  Ok, a better way for me to debug this might be to println() the keys to stdout or something.

**Comment by innermous** [comment]
@justinclift if you will introduce any changes to this code, don't forget to add `return;` statement after `setCurrentIndex`. This will be safer.

**Comment by justinclift** [comment]
Like this?

```
    ...

    if (event->modifiers() & Qt::AltModifier && tab != -1) {
        ui->mainTab->setCurrentIndex(tab);
        return;
    }

    QMainWindow::keyPressEvent(event);
}
```

**Comment by innermous** [comment]
Yeah. There's no need to capture event by default QMainWindow event processor if event we are interested in was already processed.

**Comment by justinclift** [comment]
Interestingly, adding the return there stops Cmd-Q from working on OSX.

**Comment by justinclift** [comment]
This is the adjusted function to printf() keyboard output:

```
void MainWindow::keyPressEvent(QKeyEvent* event)
{
    int tab = -1;

    int keyPressed = event->key();
    printf("0x%x\n", keyPressed);

    switch (keyPressed)
    {
    case Qt::Key_1:
        tab = Tabs::StructureTab;
        break;
    case Qt::Key_2:
        tab = Tabs::BrowseTab;
        break;
    case Qt::Key_3:
        tab = Tabs::PragmaTab;
        break;
    case Qt::Key_4:
        tab = Tabs::ExecuteTab;
        break;
    default:
        break;
    }

    if (event->modifiers() & Qt::AltModifier && tab != -1) {
        ui->mainTab->setCurrentIndex(tab);
        return;
    }

    QMainWindow::keyPressEvent(event);
}
```

This is the output from it, when pressing Alt+1, Alt+2, Alt+3, Alt+4, then Cmd-Q to quit:
```
0x1000023
0x1ffffff
0x1000023
0x1ffffff
0x1000023
0x1ffffff
0x1000023
0x1ffffff
0x1000021
```

The number keys aren't being detected properly.  Any ideas?

**Comment by innermous** [comment]
I don't understand this, tbh. I mean, AFAIK, mac's don't even have Alt keys, right?

**Comment by justinclift** [comment]
???

Why wouldn't they have Alt keys?

**Comment by justinclift** [comment]
That being said, I use a Mac Mini.  They don't have an inbuilt keyboard, instead relying on people to use their own.  I'm using a standard everyday 101-key keyboard with it, using US layout.

**Comment by innermous** [comment]
@justinclift I don't know, I never seen Mac keyboard. I just heard they have **this stuff** with CMD button.

**Comment by justinclift** [comment]
Ahhh.  The Cmd key is (on mine) mapped to the Windows key.

**Comment by innermous** [comment]
@justinclift hm.
Did @revolter  try this commit?

**Comment by justinclift** [comment]
Ahhh, not yet.  He wanted me to build him a .dmg for testing with.  I'll do it now.

**Comment by innermous** [comment]
@justinclift alright alright...
I am gonna investigate how QtCreator handles tabulation.

**Comment by revolter** [comment]
@innermous, Yes, I'm using a MacBook and I can test a built binary if provided. And yes, Apple keyboards have the <kbd>alt</key> key too.

**Comment by justinclift** [comment]
@revolter .dmg here: http://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-201609281947-issue788v1.dmg

Didn't use the pretty .dmg creator though. :wink:

Noticed a weird behaviour.  The Alt+[number key] works before a database is loaded.  After loading a database though... they don't work any more.

**Comment by justinclift** [comment]
@innermous Hmmm, is there any way that the load of a database could remove the capture of keystrokes?

**Comment by revolter** [comment]
@justinclift Thanks! Yes, it works ok up until opening a database.

**Comment by justinclift** [comment]
Cool.  It sounds like we're at least on the path to finding a solution. :smile:

**Comment by revolter** [comment]
Yes, it's losing focus after opening the database.

**Comment by revolter** [comment]
If I:

- open DB4S
- hit <kbd>alt</kbd>+<kbd>2</kbd>
- hit <kbd>alt</kbd>+<kbd>1</kbd>

it works ok. Then if I:

- open a database
- switch to another window like `Finder`
- switch to DB4S
- hit <kbd>alt</kbd>+<kbd>2</kbd>
- hit <kbd>alt</kbd>+<kbd>1</kbd>

it works again.

**Comment by justinclift** [comment]
Interesting yeah.  That does kind of work.

On the "Execute SQL" tab though, the number keys go into the SQL window. :wink:

**Comment by justinclift** [comment]
Moving this to 3.10.0 for now, just in case. :smile:

**Comment by innermous** [comment]
What's the status of this?

**Comment by mgrojo** [comment]
As already talked in https://github.com/sqlitebrowser/sqlitebrowser/commit/73f7cc824f043ba3c56a9ae8717a2e863639f2ba#commitcomment-31782545 I also had problems with these shortcuts. I've tried with QShortcut with success and it's now working for me in any case, even inside QScintilla widgets.

@justinclift Can you try in MacOS, too?

**Comment by mgrojo** [comment]
Oh, I've just seen this is more or less what you did in https://github.com/justinclift/sqlitebrowser/commit/5a0ac4685e2d37ce39fd54b462ff0662e94cde21 but now using a simpler version thanks to C++11. If that wasn't working well, there is a chance that it isn't still working in MacOS but it might have been a Qt bug, then. Let's see now.

**Comment by justinclift** [comment]
Wow, that was a long time ago.  I barely remember C++ any more. :angel: 

Do you still need me to test stuff on macOS?

**Comment by MKleusberg** [comment]
Let's just assume it's working and reduce the issue number a bit :innocent:  If it turns out to not work on macOS we should open a new issue since other shortcuts might have problems too then.

**Comment by revolter** [comment]
> Yes, it's losing focus after opening the database.

Not anymore. Meaning, immediately after opening a database, alt + number continue to work like after opening the app.

> On the "Execute SQL" tab though, the number keys go into the SQL window. 😉

Not anymore. So you can use alt + 4 and then alt + 1 to switch to and from the "Execute SQL" tab without any problem.
