### ISSUE TITLE
Copying cell contents in 3.9.0 inserts quotes around the value copied to the clipboard

### ISSUE THREAD

**Issue by swinster** [sqlitebrowser/sqlitebrowser#789]
### Details for the issue

Pretty much as the title says. I do not believe this occurred in the previous version. May not seem like a big thing, but when you copy value to paste them into a filter, or into another application you then have to edit the value to remove the quotes. Just really annoying, and so I think I would have remembered this if the previous version had the same functionality. 
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, that's interesting.  We did make some changes to the cut-n-paste code, so this is definitely useful feedback.

**Comment by justinclift** [comment]
By the way, does this happen for every value, or just certain things?

**Comment by swinster** [comment]
So far, all the values I have needed to try :(

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 29, 2016 at 1:58 PM +0100, "Justin Clift" <notifications@github.com<mailto:notifications@github.com>> wrote:


By the way, does this happen for every value, or just certain things?

**Comment by justinclift** [comment]
😦

**Comment by chrisjlocke** [comment]
As a workaround, click the cell once to set the focus, and click it again to go into 'edit mode'.  The cell contents will be highlighted.  Right click this selection, and select 'Copy' (or press Ctrl+C).
Alternatively, double click the cell contents, and the contents will be displayed in the 'Edit Cell' pane.  Again, the contents will be highlighted.  Copying this text as in the above manner will not be quoted.

**Comment by swinster** [comment]
Yeah, I have done that too, although TBH, I'm not sure which is the most irritating. Either way, it is something silly.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 29, 2016 at 11:38 PM +0100, "Chris Locke" <notifications@github.com<mailto:notifications@github.com>> wrote:


As a workaround, click the cell once to set the focus, and click it again to go into 'edit mode'. The cell contents will be highlighted. Right click this selection, and select 'Copy' (or press Ctrl+C).
Alternatively, double click the cell contents, and the contents will be displayed in the 'Edit Cell' pane. Again, the contents will be highlighted. Copying this text as in the above manner will not be quoted.

**Comment by chrisjlocke** [comment]
Until you mentioned it, I'd never tried pressing Ctrl+C in a cell.  I normally go by menu options, so as there is no 'Edit' | 'Copy', I assumed there was none.
Highlighting two cells gives quoted values, separated by a tab character.  Wonder how long before we have another option to change that to a comma, or some other user-defined character.... ;)

**Comment by revolter** [comment]
@swinster, I added a commit that should fix this. Thought copying multiple cells still quotes the contents, so only copying single cells will leave the contents unquoted. Are you able to build the project yourself? @justinclift could point you out to the instructions. If not, a nightly build containing this fix will be available tomorrow.

**Comment by justinclift** [comment]
@swinster If you're feeling adventurous, it's definitely workable to compile things yourself instead of waiting for the auto-generated nightly builds: :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

**Comment by justinclift** [comment]
@swinster Do you have time to try out our latest nightly release? (download locations are on the front page, if that helps)

This should be fixed in both our recent 3.9.1 release, and a further things fixed in our latest nightly builds.  Verification from your point of view would be cool. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦

**Comment by swinster** [comment]
@justinclift apologies for being tardy on this. Yes, this issue was fixed.- current version 3.9.1

**Comment by justinclift** [comment]
Thanks @swinster. :smile:
