### ISSUE TITLE
Some usability improvement requests

### ISSUE THREAD

**Issue by jschultz** [sqlitebrowser/sqlitebrowser#79]
Hello folks,

After the excellent service on my last request, I have a couple more:
1. On the 'Database Structure' tab, could the schema be made to collapse along with the field list? As it is, the benefit of collapsing is rather lost when the schema is long and you can only see a few (or only one) tables on your window anyway.
2. On the results from running an SQL query, long fields (varchar and friends) should only be displayed up to some maximum length. Otherwise you have to do massive horizontal scrolling to see all your fields.
3. On SQL query results and table browsing, how about a right-click option to copy the value of the field into the copy buffer. At the moment you can accomplish this with browse data by double-clicking and copying from the 'Edit database cell' window, but you can't do it at all with query results.

Many thanks for your help. And let me know if it makes sense that I work on the code myself - I could do it, but would ultimately prefer to avoid one more learning curve!

Cheers, Jonathan

**Comment by mgrojo** [comment]
I'm reviewing enhancement requests and this seem to be already addressed, isn't it? The request 1. is even configurable for everyone to be happy. Can it be closed?

**Comment by jschultz** [comment]
I'd still like a context menu - `^C` is OK but you have to know it is available. However it's rather less important than the other requests.

**Comment by mgrojo** [comment]
Have you tried a recent nightly build? We have now a context menu in Data Browser and Execute SQL tables, with "Copy" and "Copy with Headers" entries on it. I think this is what you want.

**Comment by jschultz** [comment]
Ah OK. That sounds perfect. Thank you once again.

**Comment by mgrojo** [comment]
Ok, it seems this can be closed. If anybody disagree, please reopen it without hesitation.
