### ISSUE TITLE
Pragmas don't keep saved on reopened db

### ISSUE THREAD

**Issue by gjijon** [sqlitebrowser/sqlitebrowser#790]
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [ ] 3.9.0
- [X] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, interesting.  It *sounds* like a bug, but we'll probably need to investigate more before we're sure. :smile:

**Comment by MKleusberg** [comment]
@gjijon Which pragmas do you mean? All of them, including e.g. the ```user version``` pragma? Or just some of them, e.g. the ```foreign keys``` pragma?

The reason I'm asking is that some pragmas aren't stored in the database file at all by SQLite, they are only saved for the current connection. So closing and opening the database again will reset them. Foreign keys are one example. In this case that's just the way SQLite works. Others are stored permanently in the database file, for example the user version. If these aren't saved either, then it's definitely a bug in our code :smiley:

**Comment by justinclift** [comment]
Closing due to lack of response. ☹️
