### ISSUE TITLE
Incorrect OPTION syntax in cmake?

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#791]
### Details for the issue

[It looks like][1] [these lines][2] should be

    OPTION(USE_QT5 "Build with qt5" OFF)
    OPTION(ENABLE_TESTING "Enable the unit tests" OFF)

instead. I don't know cmake almost at all, so not sure if it's a problem or that help page is about another `option` command/function/...

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

  [1]: https://cmake.org/cmake/help/v3.0/command/option.html
  [2]: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt#L6-L7

**Comment by MKleusberg** [comment]
Seems to be true for cmake 2.8.7, too: https://cmake.org/cmake/help/v2.8.7/cmake.html#command:option
Saying this because that's the minimum version we're relying on.

**Comment by MKleusberg** [comment]
It's still building as before :smiley: Changed in 2563d678681fa6972674b47617015cb2515bd414 as Iulian suggested. If Travis doesn't complain either I'm going to close this issue.

**Comment by MKleusberg** [comment]
Looks good :smiley:

**Comment by revolter** [comment]
Great, thanks!
