### ISSUE TITLE
ModifyTable: every field has FK constraint

### ISSUE THREAD

**Issue by schdub** [sqlitebrowser/sqlitebrowser#799]
![screenshot from 2016-10-02 11 08 51](https://cloud.githubusercontent.com/assets/1304776/19019649/439cc78c-8897-11e6-9092-bd39ac1082dd.png)
### Details for the issue

1) import tables from .sql file: https://github.com/sqlitebrowser/sqlitebrowser/files/411587/kuban.db.sql.zip
2) "Modify Table" level;
3) every row in "Foreign Key" column will be `place`(`id`) instead only for `place_id` field.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows
- [x] Linux: ( Ubuntu 14.04 x64 )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [ ] 3.9.0
- [ ] 3.8.0
- [x] Other: development trunk
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @schdub. :smile:

@MKleusberg is this of interest to you?

**Comment by MKleusberg** [comment]
@schdub Are you sure you have built the latest source from master? If so, are you using Qt4 or Qt5?
At least I cannot reproduce this at the moment, but the latest changes to foreign key handling are making use of some Qt5-only features. I tried to make it work for Qt4, too, but couldn't test it. So that would be my current guess.

**Comment by schdub** [comment]
@MKleusberg, after building on Qt5 (Qt 5.7.0) not reproduce anymore. Thank you.

**Comment by MKleusberg** [comment]
Awesome, thanks for testing :) Now that we've 'officially' dropped Qt4 support there should at last be no confusion as to what works with which version.
