### ISSUE TITLE
Broken build on v3.9.x branch

### ISSUE THREAD

**Issue by bernardosulzbach** [sqlitebrowser/sqlitebrowser#803]
### Details for the issue

```
CMakeFiles/DB Browser for SQLite.dir/build.make:1652: *** missing separator.  Stop.
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/DB Browser for SQLite.dir/all' failed
make[1]: *** [CMakeFiles/DB Browser for SQLite.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
#### I'm opening this issue because:

The build is broken.

Current master works fine.
#### I'm using DB4S on:

```
Fedora Linux 4.7.4-100.fc23.x86_64
```

```
clang version 4.0.0 (trunk 282332)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

```
cmake version 3.4.3
```
#### I'm using DB4S version:

https://github.com/sqlitebrowser/sqlitebrowser/commit/f68e2939b888c6e6e5a8ced334c9d0e1e799dac0

**Comment by justinclift** [comment]
Thanks.  I'll try it out in a VM later to see what's wrong. :smile:

**Comment by justinclift** [comment]
As a thought, what happens if you try qmake instead of cmake? eg:

```bash
$ qmake
$ make
```

**Comment by mafagafogigante** [comment]
Will try, I am bisecting it now.

**Comment by mafagafogigante** [comment]
f68e293 builds fine with qmake-qt4 here.

@justinclift is this the standard way to do it? BUILDING.md is outdated then.

**Comment by justinclift** [comment]
In theory, they both should work... however, that's not always the case. 😦 

* The config file for CMake is [CMakelists.txt](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/CMakeLists.txt).
* The config file for qmake is [src/src.pro](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/src.pro).

It's totally possible for one config file to be changed, breaking one system, but leaving the other completely fine.

For us, CMake seems mostly useful on Windows, with qmake more useful everywhere else.  And I have a bad habit of introducing Windows-isms to the CMake config. 😦 

It would probably be better if we update the Fedora/CentOS build instructions then, to use qmake. :smile:

**Comment by mafagafogigante** [comment]
My bisection blames 54dbd62508791da4bbcbc8c5bac4c770a1cc9cd7 for it. However, that commit itself breaks the build because of something completely different (see below).

```
[ 46%] Building CXX object CMakeFiles/sqlitebrowser.dir/src/MainWindow.cpp.o
In file included from /home/mg/code/sqlitebrowser/src/MainWindow.cpp:1:
/home/mg/code/sqlitebrowser/src/MainWindow.h:182:33: error: unknown type name 'QPersistentModelIndex'
    void updateRecordText(const QPersistentModelIndex& idx, const QByteArray& text, bool isBlob);
                                ^
/home/mg/code/sqlitebrowser/src/MainWindow.cpp:802:18: error: out-of-line definition of 'updateRecordText' does not match any declaration in 'MainWindow'
void MainWindow::updateRecordText(const QPersistentModelIndex& idx, const QByteArray& text, bool isBlob)
                 ^~~~~~~~~~~~~~~~
2 errors generated.
CMakeFiles/sqlitebrowser.dir/build.make:549: recipe for target 'CMakeFiles/sqlitebrowser.dir/src/MainWindow.cpp.o' failed
make[2]: *** [CMakeFiles/sqlitebrowser.dir/src/MainWindow.cpp.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/sqlitebrowser.dir/all' failed
make[1]: *** [CMakeFiles/sqlitebrowser.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
```

---

Anyway, I will use `qmake` for now. I hope master stays well-behaved, though.

**Comment by justinclift** [comment]
Yeah, master should keep good. :smile:

**Comment by justinclift** [comment]
Just updated the building instructions slightly for CentOS/Fedora:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/06398be8840d7b9f7f36334446caa8e6c20d771e/BUILDING.md#centos--fedora-linux

Tested here on Fedora 25 x64.  I still haven't looked into how to override paths yet, for example when providing a custom compiled newer version of SQLite... but I should get that figured out over the next few days. :smile:

**Comment by MKleusberg** [comment]
Closing this since it seems like there is a workaround and we probably don't have the time to look into the 3.9.x branch at the moment :wink:
