### ISSUE TITLE
Ensure silent install mode works for windows, & document it

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#804]
We've been [asked on Twitter](https://twitter.com/danj2k/status/784000550874546176) if our Windows installer supports silent mode installation, for deploying to classrooms of PC's.

```
@sqlitebrowser is there a way to silent install DB Browser for SQLite? For deployment
to a classroom of computers in the Computing Dept.
```
This is a good idea, and NSIS in theory automatically adds this capability.  Running our installer from the command line with '/S' switch (case sensitive) is supposed to do a silent install.

Lets test it, fix it if it's not working, and document it so others can use the silent mode capabilities too.

**Comment by justinclift** [comment]
Good news.  It's working here on Win 8.1 x64, using our 64-bit installer.

Weirdly the uninstall script doesn't seem to remove vcredist_64.exe, so it looks like theres a bug with this line: https://github.com/sqlitebrowser/sqlitebrowser/blob/5dddffd7a0eb8698885c324bd4f2080b9fb9fb21/CMakeLists.txt#L409

**Comment by justinclift** [comment]
Just added the information to the wiki:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Silent-Mode-installation-on-Windows

**Comment by revolter** [comment]
What about the uninstall problem?

**Comment by justinclift** [comment]
Good point.  Just created #805 to track that.
