### ISSUE TITLE
Install on windows doesn't seem to remove the MSVC redistributable

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#806]
While testing out silent mode install on Windows for #804, something interesting showed up.

After installation, the "vcredist_64.exe" file was still left in place.  It looks like theres a bug with this line:

https://github.com/sqlitebrowser/sqlitebrowser/blob/5dddffd7a0eb8698885c324bd4f2080b9fb9fb21/CMakeLists.txt#L409

**Comment by innermous** [comment]
I doubt any other software package does it after uninstall.
What if another application uses redistributable too?

**Comment by justinclift** [comment]
Nah, it works a bit differently from that.  The thing which needs to be removed - and isn't being - is the vc_redist*.exe uninstaller itself.

During the DB4S installation process we run that installer silently in the background, which installs the redistributables.  Once that's done, the vc_redist*.exe package isn't needed, and (in theory) should be getting removed automatically anyway (by us).

**Comment by justinclift** [comment]
As a data point, I tried the batch file approach yesterday.  eg we run a batch file at the end of the installation process, and it does a `del /F vs_redist??.exe` (with the correct file name), then rmdir's the redistributable's subdirectory.

The deletion command always fails with a "permission denied" error, so it seems like vc_redist*.exe is being installed using Admin priviledges, but the batch file is being run with user level priviledges.

Didn't investigate any further.  The next step will probably be to use a batch file to run the vs_redist*.exe installer, because the batch file would need Admin already to install thing.  The same batch file - already running as Admin - should (in theory) be ok to delete to the redistributable and it's sub-directory afterwards.

**Comment by karim** [comment]
@justinclift This should be closed now?

**Comment by justinclift** [comment]
Good point.  We might as well close this, now that we have working .msi's. :smile:
