### ISSUE TITLE
The dmg has wrong field color and can not be changed.

### ISSUE THREAD

**Issue by kokoar** [sqlitebrowser/sqlitebrowser#807]
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [x] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment]
Could you explain it better or better yet, post some screenshots with the problem you're having? It would help us understand it better.

**Comment by justinclift** [comment]
Are you meaning this?

![image](https://cloud.githubusercontent.com/assets/897883/17920618/a07dcc70-69a3-11e6-95eb-6ef112923287.png)
(Copied from: https://github.com/sqlitebrowser/sqlitebrowser/issues/737#issuecomment-241970969)

**Comment by justinclift** [comment]
@revolter It's possible this is another report of what was happening for @MarqueIV on macOS Sierra.

**Comment by revolter** [comment]
Could be, but the title doesn't say 100% what the problem is, so we need a reply from @kokoar to know for sure.

**Comment by justinclift** [comment]
Agreed. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.
