### ISSUE TITLE
Editing schema would remove foreign keys, constraints, and cascades

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#81]
From @TWiStErRob:

> I see all the schemas listed, however I can't edit (don't even want to, see my comment on #78) nearly any of them because it would remove all the foreign keys and constraints and cascades. See Category_Descendant in http://temp.twisterrob.net/share/MagicHomeInventory.sqlite

This is following on from https://github.com/sqlitebrowser/sqlitebrowser/issues/77.

**Comment by MKleusberg** [comment]
All table statements in the sample database are now parsed correctly. This means no foreign keys, constraints, and cascades should be removed when editing those tables. Furthermore, if there *is* a table which isn't fully supported yet you'll see a warning when editing that table.

There are more missing details in the grammar parser but I think we should collect those in issue #741. So I'd suggest closing this issue as all problems mentioned in here should be fixed and for further issues we have a separate issue already. Can somebody, @justinclift maybe :smiley:, double check it's working with the MagicHomeInventory.sqlite database before closing this issue?

**Comment by justinclift** [comment]
Just tried to download the database, but the link is 404-ing.

@TWiStErRob Do you still have a copy of it handy?

**Comment by MKleusberg** [comment]
@justinclift Luckily I had still a copy on my disk. Just emailed it to you :smiley:

**Comment by justinclift** [comment]
Thanks, added a ToDo item to try this out tomorrow. :smile:

**Comment by justinclift** [comment]
@MKleusberg Is this warning on the virtual table 'Search' expected?

![screen shot 2017-01-06 at 22 52 36](https://cloud.githubusercontent.com/assets/406299/21735580/d8ad16b2-d462-11e6-8223-667e62f4b508.png)
"USING USING" seems like an error (causing the warning?), though I'm not sure where it's originating from.  Haven't attached a debugger. :smile:

On a side note, choosing that virtual table (no defined fields) in the Browse Data tab display strangely.  No filters row, probably because no fields.  But the background colouring for the filter row is there.  Not real high urgency to fix though I reckon... :wink:

![screen shot 2017-01-06 at 22 59 31](https://cloud.githubusercontent.com/assets/406299/21735711/d4a11f36-d463-11e6-8cd3-ed69e6192593.png)

**Comment by TWiStErRob** [comment]
Original code that created that is
```sql
CREATE VIRTUAL TABLE Search USING FTS3 (
	_id,
	name,
	location
);
```
you can probably find the same in the .sqlite file if you open it with a text editor/grep it.

**Comment by justinclift** [comment]
Thanks @TWiStErRob.  I was definitely taking the lazy approach. :wink:

**Comment by MKleusberg** [comment]
@justinclift Just fixed the double 'USING' bit. Thanks for pointing this out :smiley:
The warning is still showing up but that's expected. You'll see it for all tables that aren't fully parsed by our grammar parser yet. This is true for all virtual tables. Because of this the Browse Data tab stays empty, too. See issue #917 as well. Virtual tables are a going to be a whole new problem for us :smiley:

@TWiStErRob Thanks for commenting back :smiley: I'm going to close this issue since we have #741 for further parsing problems and #917 for all the virtual table stuff. If you find any other parsing issues in your databases feel free to comment in one of these issues or open a new one :smiley:
