### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mrexodia** [sqlitebrowser/sqlitebrowser#812]
Just a message to say thank you for developing this tool. I use it a lot and it helps me out tremendously every single time! ❤️

**Comment by justinclift** [comment]
Awesome!  You're welcome @mrexodia. 😀

**Comment by justinclift** [comment]
We do accept PR's too btw (hint hint). :wink:

**Comment by chrisjlocke** [comment]
And beer.

**Comment by MKleusberg** [comment]
@mrexodia Thank you so much for letting us know :heart: I'm really happy when we can help people by providing our little tool :smiley:
