### ISSUE TITLE
keep database-specific view column widths

### ISSUE THREAD

**Issue by martrs** [sqlitebrowser/sqlitebrowser#813]
### Details for the issue

Make table view's column widths persistent for each database so that when the database is closed and re-opened, the browser view displays table columns in the same width as they were before closing, instead of the default column widths.

### Useful extra information

Maybe the widths can be stored in ~/sqlitebrowser.conf as part of recentFileList or additional entries for each recent file, containing the file name, table name, and a series of column widths. Only those with the column widths that have increased or decreased from default should be saved. There is no need to keep track of all databases, just the ones in the recent list.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows
- [x] Linux: ( _distro:_ Fedora )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [x] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by martrs** [comment]
DIdn't realize there is a menu entry to open and save project that does exactly what the issue was asking. Closing as non-issue.

**Comment by justinclift** [comment]
No worries at all.  I'm starting to think a manual - or at least an intro page pointing out stuff like this - might be useful for people.

Thoughts? :smile:
