### ISSUE TITLE
Alt + Backspace should delete a word in Execute SQL on macOS

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#815]
### Details for the issue

Pressing <kbd>alt</kbd> + <kbd>backspace</kbd> while in the _Execute SQL_'s editor, it starts to undo modifications instead of deleting words.
Pressing <kbd>alt</kbd> + <kbd>left arrow</kbd> correctly jumps through words.

Is is the same on Linux and Windows too?
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.11.6 )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Alt+Backspace deletes everything in Windows.  
Alt+Left arrow does nothing.

In Windows, Ctrl+Left arrow jumps backwards to the beginning of the previous word.

**Comment by revolter** [comment]
<kbd>alt</kbd> + <kbd>backspace</kbd> on macOS is <kbd>ctrl</kbd> + <kbd>backspace</kbd> on Windows. Sorry I forgot to mention this.

**Comment by justinclift** [comment]
@revolter When you say "instead of deleting words" where is that expectation coming from?

Asking because <key>alt</key> + <key>backspace</key> behaviour isn't one I'm familiar with.  Kind of wondering if maybe it's zsh specific or something? :smile:

**Comment by revolter** [comment]
@justinclift, Really? It's a standard keyboard, default system one, works in almost any editor. I was using it since having a Windows machine.

And I just read your disclaimer 😆 Yes, it's well known. Only that is <kbd>ctrl</kbd> on Windows but <kbd>alt</kbd> on macOS.

**Comment by justinclift** [comment]
No worries.  It's not the first one I'm somehow never known about. :wink:

**Comment by justinclift** [comment]
As an initial thought, I'm kind of suspecting it might be related to QScintilla.  Other key binding stuff seems weird when on the Execute SQL tab, so this might be related.

**Comment by revolter** [comment]
I thought so too. I'll look into QScintilla's documentation some time soon, but this annoyed me tens of times since I started using DB4S but delayed creating an issue.

**Comment by ghellquist** [comment]
Not sure if I understand how this should work to correctly follow Mac-OS conventions.. I get the following behaviour from 3.9.1v2 on my Macbook Pro.

 cmd backspace = deletes a word (i.e. anithing surrounded by whitespace)
 alt backspace = deletes the whole line

 but here is a bit of special behaviour:
if you first do cmd backspace (i.e. deleting words), the alt backspace changes behaviour to undoing the cmd backspace until all changes have been undone - then it deletes the full line.

I believe all of this is built in to the QT framework. My suggestion is to close this issue.
/gunnar

**Comment by revolter** [comment]
I think it's built into QScintilla :-?

**Comment by MKleusberg** [comment]
The problem seems to be in this line and the next one:
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/libs/qscintilla/src/KeyMap.cpp#L131

So it's not a Qt problem but not exactly a QScintilla problem either because this file is part of the underlying Scintilla library, not part of the Qt wrapper around it. Might be worth it to check if they changed these lines in their latest version and, if not, open an issue upstream.

**Comment by bsmith89** [comment]
Bump?

I'd really like to see this behavior, since Alt-Backspace is very much a part of my text editing muscle memory.  I don't even realize how much I use it until I'm editing SQL queries in SQLite Browser and it doesn't work.

**Comment by mgrojo** [comment]
It's still the same in https://sourceforge.net/p/scintilla/code/ci/default/tree/src/KeyMap.cxx

@bsmith89 @revolter Maybe you should open an issue in https://sourceforge.net/p/scintilla/bugs/

**Comment by mgrojo** [comment]
I'm reviewing shortcuts and returned to this issue. We can easily change in our code the default shortcuts configured by Scintilla so we could make this ourselves. But taking a look to [standard Mac shortcuts](https://support.apple.com/en-us/HT201236) it says:
> Option-Delete: Delete the word to the left of the insertion point.
So the standard for deleting a word on the left in Mac is Alt+Del.

On the other hand, many [applications use Alt+Backspace for undoing](https://defkey.com/what-means/alt-backspace). Most of them might be Windows applications, but the QScintilla choice is not totally unjustified.

Should the shortcut be changed for Mac, nevertheless? Is "delete word left" what regular Mac users expect from Alt+Backspace?

**Comment by justinclift** [comment]
The different names for keys on macOS vs others could be adding a layer of confusion. :frowning: 

For example, with @revolter's comment above near the start:

> <kbd>alt</kbd> + <kbd>backspace</kbd> on macOS is <kbd>ctrl</kbd> + <kbd>backspace</kbd> on Windows.

That's not the case (for me) when I use macOS though.  I generally use Mac Mini's though, with a "standard" :wink: [cheapo US 101-key keyboard](https://support.logitech.com/en_us/product/classic-keyboard-200-usb) plugged in.

The [standard Mac shortcuts](https://support.apple.com/en-us/HT201236) document @mgrojo points to above says the same:

* Command (or Cmd) ⌘
* Option (or Alt) ⌥
* Control (or Ctrl) ⌃
* On keyboards made for Windows PCs, use the Alt key instead of Option, and the Windows logo key instead of Command.

The same thing visually:

![logitech_classic_keyboard_200](https://user-images.githubusercontent.com/406299/50530003-ac24f000-0b4d-11e9-99a3-ac1eef8a8fd9.png)

Going by the above, the [note in the QScintilla source](https://github.com/sqlitebrowser/sqlitebrowser/blob/1925ccfd37bea327683a6704de625e47dc260cf4/libs/qscintilla/src/KeyMap.cpp#L56) seems wrong:

> Most uses of Ctrl map to Cmd on OS X ...

The Apple doc says the Windows key maps to "Cmd" though, which is what I experience using US 101-ley keyboards.

---

Semi-remembering a conversation with someone years ago (@revolter maybe?) about something like this.  Perhaps for the keyboard on Apple laptops, things are different?

**Comment by mgrojo** [comment]
I understood:
> <kbd>alt</kbd> + <kbd>backspace</kbd> on macOS is <kbd>ctrl</kbd> + <kbd>backspace</kbd> on Windows.

as: <kbd>alt</kbd> + <kbd>backspace</kbd> on macOS is used for the same thing as <kbd>ctrl</kbd> + <kbd>backspace</kbd> on Windows.

But then read that document that I linked and got confused.

**Comment by revolter** [comment]
Yes, that's what I meant. Even though cmd = ctrl and alt = option in most cases, the "standard" shortcut for deleting an entire word is ctrl + backspace on Windows but alt + backspace instead of cmd + backspace on macOS. But I may be wrong, I have to actually test this when I get back to my mac.

**Comment by justinclift** [comment]
Testing quickly just now on the build mac, connecting to it via VNC from a Linux desktop.

1. Opening TextEdit (the inbuilt GUI macOS text editor)
2. Adding three lines of text:
```
foo bar 1
foo bar 2
foo bar 3
```
3. Placing the cursor just **before** (eg left of) the "2" in the above lines
4. Pressing <kbd>alt</kbd> + <kbd>backspace</kbd> once deletes all the text to the left of the cursor, leaving the "2" in place:
```
foo bar 1
2
foo bar 3
```
The cursor is still to the left of the "2".

That being said, it's entirely possible VNC is remapping keys on the way through too.  **\*sigh\***

**Comment by justinclift** [comment]
I guess I'd better unplug the build mac later on today (after the nightlies finish), bring it over to the Linux desktop and try things out with it directly plugged into a mouse and keyboard.  That would help clarify if VNC is mucking with things too.

It won't shed any light on whether the key mappings for macOS are different on Apple supplied keyboards (eg laptops) vs user-added US 101-key ones.

**Comment by mgrojo** [comment]
More info on the issue:

https://lifehacker.com/5803041/the-mac-os-x-delete-key-it-goes-both-ways

**Comment by mgrojo** [comment]
According to: 
http://doc.qt.io/qt-5/qkeysequence.html
Section Standard Shortcuts:
DeleteStartOfWord	is Alt+Backspace in macOS column.

So this was enough evidence for me and I added that keysequence as alternate for deleting to the left. Ctrl+Backspace (that is, Cmd+Backspace) still does the same.

In other OS, Alt+Backspace still does the default set by Scintilla (undoing).

@revolter or @justinclift Please, close this when you have confirmed it is working OK in macOS.

**Comment by MKleusberg** [comment]
Can we close this issue then? :smile:

**Comment by revolter** [comment]
Yes, it's working perfectly, thank you @mgrojo!
