### ISSUE TITLE
SQLite Browser slow when opening big tables

### ISSUE THREAD

**Issue by afbpinheiro** [sqlitebrowser/sqlitebrowser#817]
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Hi,

I don't want to be picky, collaborators of this repo do a great job and I'm very thankful to you.

I just realized that sqlite browser is slower than it should when opening big tables. like 150k rows vs 45 columns (cells with small/medium text size). It seems that the program tries to load the entire table before visualization. Wouldn't be better, if possible, to load just the rows that are contained in the current view?

Anyway, just a suggestion :) if I can help with anything just ask.
Thanks!

**Comment by revolter** [comment]
You can lower the `prefetch` setting that specifies how many rows to load in advance. You can find it in `Preferences > Database > Prefetch block size`. The minimum value is `255`. Let me know if it improves the load speed or not.

**Comment by chrisjlocke** [comment]
Is this linked to #761 where a large amount of text (eg, BLOBs) is in the table?
@afbpinheiro- irregardless of the number of rows, have you fields containing a large amount of text? (> 30,000 characters)

**Comment by afbpinheiro** [comment]
@revolter no, unfortunately it doesn't help.
@chrisjlocke In some tables I might have, but in others I don't have for sure and it still take a bit to open the table. 

By the way, my cpu is the i5-6300HQ 2.3GHz.

**Comment by afbpinheiro** [comment]
@revolter no, unfortunately it doesn't help.
@chrisjlocke In some tables I might have, but in others I don't have for sure and it still take ~1 or 2 min to open the table.

By the way, my cpu is the i5-6300HQ 2.3GHz.

**Comment by justinclift** [comment]
@afbpinheiro Just to check... does it speed up if you choose a smaller number in `Preferences` → `Data Browser` → `Content` → `Symbol limit in cell`?

  ![screen shot 2016-10-01 at 17 27 46](https://cloud.githubusercontent.com/assets/406299/19015944/0b954b48-8806-11e6-8710-644bdbbab6ab.png)

If you make it something really low, like `1` just to experiment with, it would be interesting to know if that makes a difference. :smile:

**Comment by afbpinheiro** [comment]
@justinclift No, even with 1 it takes a lot of time to load :(

**Comment by justinclift** [comment]
Thanks, that's useful to know. :smile:

It's definitely not the text rendering then. :wink:

**Comment by revolter** [comment]
Are you able to send us the database you are using? Or remove sensitive information and send it? Or only the schema and the number of rows in it?

**Comment by mafagafogigante** [comment]
Off-topic: @justinclift was that image generated by software or did you manually write the text and draw the boxes? Just curious.

**Comment by justinclift** [comment]
@mafagafogigante Manually did it, using a really old version of [Snag It](https://www.techsmith.com/snagit.html). :smile:

**Comment by mafagafogigante** [comment]
Thanks, @justinclift.

**Comment by afbpinheiro** [comment]
@revolter I can't send the database since it has confidential data. As soon as I have some minutes I'll create and post a similar dummy database so you can see the problem. Thanks!

**Comment by chrisjlocke** [comment]
As another test, whats your prefetch size?  Go to 'View', 'Preferences' and the 'Database' tab.

![image](https://cloud.githubusercontent.com/assets/7872218/19506054/f0f10e40-95bf-11e6-90c6-0fa44675e073.png)

Change this to 50, and see if its quicker...  This is how many records it loads in one chunk.

**Comment by chrisjlocke** [comment]
How big is the physical database (MB) ?  To solve another issue (fields with >300,000 characters) that database has thousands of rows (about 20,000), and while my laptop initially struggles to open it (compared to 'normal' databases) its only about 20 seconds.  This database is about 800 MB.
I assume during the two minutes it takes to open the database, the disk IO is going through the roof?  The details from the task manaager would be handy - memory usage of DB4S and disk IO rate.

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦

**Comment by ravenAtSafe** [comment]
I see this (or a variant) with a pretty small DB - attaching the EPSG database associated with PROJ6.  I tried the two tweaks suggested above with no impact; still takes forever between each click (changing the selected table in the Database Structure tab).

If I leave the Database Structure tab things are much snappier.

v3.10.1
Mint 19 / Ubuntu 18.04
[proj.db.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3942538/proj.db.zip)

**Comment by megahypercat** [comment]
Same problem.  Opening big table is slow, even filtering for queries that only have a couple of matches takes forever.
Performance is good with normal SQlite.
Performance is good with small tables in the same file.
The suggestions did not affect performance.

DB size: 155MB
rows (in the big table): 524000

I can send a sample, I think.
