### ISSUE TITLE
Default font size on OSX is too small

### ISSUE THREAD

**Issue by OneMHz** [sqlitebrowser/sqlitebrowser#818]
### Details for the issue

In the latest version (3.9.1) for Mac, the font on the SQL Editor is very small and I can't see a way to change it.

I have a very large monitor, but it isn't a HiDPI display. On the built-in retina display, the font is more readable, but still tiny.
### Useful extra information

![screen shot 2016-10-12 at 8 49 36 am](https://cloud.githubusercontent.com/assets/593260/19317227/321045a6-9059-11e6-819a-86415d858e28.png)
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ 10.12 Sierra )
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
As a thought, have you tried adjusting things in `Preferences` → `SQL`?
![screen shot 2016-10-12 at 16 57 38](https://cloud.githubusercontent.com/assets/406299/19317481/0e86600e-909d-11e6-9a4a-ef43f76cd244.png)
In theory, the "SQL editor font" and the font size field below it should control that.

If that's not working for you, let us know so we can investigate. :smile:

**Comment by OneMHz** [comment]
Well, I'm an idiot. I thought I went through all of the tabs. Shows me for reporting yesterday's issue today before trying again.

**Comment by justinclift** [comment]
No worries at all.  We all do things like that occasionally. :wink:

**Comment by revolter** [comment]
I remember I had the same problem when I first installed DB4S. Could we bump up the default size?

**Comment by OneMHz** [comment]
I think part of it was that I saw font settings on the data browser tab and tried them and then had my attention pulled away. Might be useful to group the font settings into one area/tab?

Unrelated, has anyone else had an issue with the data browser font and background color resetting to black on black when the app starts up?

**Comment by revolter** [comment]
For sure! Here it is: #737. I also noticed it too while working on another issue. Needs to be solved.

**Comment by justinclift** [comment]
Ahhh, so the black on black thing wasn't just a one-off something.  Seems like there's something about Sierra which is triggering it.

We'll probably need to raise the priority of it then, as Sierra is now in use by people.

**Comment by justinclift** [comment]
@revolter If you want to increase the default font size, go for it. :smile:

**Comment by revolter** [comment]
As a curiosity, @OneMHz, what font size did you use?

**Comment by OneMHz** [comment]
It was on 9. I bumped it to 12. Part of me thinks it could do with 13 or 14 even, but the rest of me thinks I'm getting to old for my own good if I need that big a font.

**Comment by revolter** [comment]
I was thinking to bump it up to 12 too. I'll wait for more opinions then I'll do it, thanks!

**Comment by MKleusberg** [comment]
I have it on 8 and it is still quite large?! Using the Bitstream Vera Sans Mono font. Writing text on a computer screen is so weirdly complicated.. ^^

**Comment by revolter** [comment]
Hmm, I use 12 on a MacBook Pro Retina and an older iMac and it's not too small and not too large :-?

**Comment by justinclift** [comment]
Heh Heh Heh, it might be practical to #ifdef the default to be OS specific.

**Comment by MKleusberg** [comment]
Might be necessary. But I'm not entirely sure if it depends on the OS or if it's even more random.

**Comment by justinclift** [comment]
This is Courier New on OSX at size 15 for me.  It's not a HiDPI screen:

![screen shot 2016-10-12 at 22 48 22](https://cloud.githubusercontent.com/assets/406299/19328936/17bf8e76-90ce-11e6-94c0-fe20bd7459ed.png)

**Comment by justinclift** [comment]
We should probably try it out on a few different OS's with the exact same font, and see what the results are.

**Comment by justinclift** [comment]
Bitstream Vera Sans Mono seems to be available here:

&nbsp; &nbsp; http://www.dafont.com/bitstream-vera-mono.font

It uses the Open Font License, so we're ok to test with it. :smile:

**Comment by justinclift** [comment]
This is with Bitstream Vera Sans Mono, at size 15 (on OSX, using a [Cintiq 27QHDT](http://www.wacom.com/en-gb/products/pen-displays/cintiq-27-qhd-touch#Specifications) monitor - 2560 x 1440px resolution, not HiDPI):
![screen shot 2016-10-12 at 22 53 53](https://cloud.githubusercontent.com/assets/406299/19329083/e1d80f4e-90ce-11e6-9bd1-1139edbae6dc.png)

**Comment by OneMHz** [comment]
I tried it on a retina panel and a Dell Ultra-Wide (non-HiDPI) and both were small at 9px (same approximate physical size, actually). It may be @MKleusberg has the zoom setting on 125% (seems like that's the default on Windows 7 and above) or 150%? That would low 8px up to 12-15-ish.

**Comment by MKleusberg** [comment]
Here is Bitstream Vera Sans Mono on 8pt:
![8](https://cloud.githubusercontent.com/assets/3153504/19329713/8e1d57fe-90da-11e6-9d28-dd3a8d973c8c.png)
And here on 15pt:
![15](https://cloud.githubusercontent.com/assets/3153504/19329723/94adf146-90da-11e6-8226-f97a6fd2d1a7.png)

I'm running on Debian Linux using KDE and a 1680x1050 monitor, no zoom or anything.

**Comment by justinclift** [comment]
Interesting.  That 8pt text would be "too small" for me.  The 15pt probably "too big". :wink:

**Comment by revolter** [comment]
`Lucida Grande @12px` on MacBook Pro Retina:

<img width="1185" alt="screen shot 2016-10-13 at 01 41 00" src="https://cloud.githubusercontent.com/assets/5748627/19330281/271ed5ee-90e6-11e6-812a-ad2cf1563ab6.png">

**Comment by justinclift** [comment]
@revolter Try with [Bitstream Vera Sans Mono](http://www.dafont.com/bitstream-vera-mono.font)?

**Comment by revolter** [comment]
I can't install it :(

**Comment by revolter** [comment]
Nothing, `Font Book` opens, but the font isn't in the list nor in the DB4S's fonts dropdown after restarting it.

**Comment by revolter** [comment]
Guess what, it works now. I added it from the `Font Book`'s `File` menu

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by revolter** [comment]
Font size 15:

<img width="1185" alt="screen shot 2016-10-13 at 02 15 59" src="https://cloud.githubusercontent.com/assets/5748627/19331077/0c6e3cd0-90eb-11e6-8f4a-0ca78fde622f.png">

Font size 12:

<img width="1185" alt="screen shot 2016-10-13 at 02 16 11" src="https://cloud.githubusercontent.com/assets/5748627/19331083/16de315c-90eb-11e6-9eb1-b4b3ebfe67a7.png">

I personally find 15 to be too big with either font.

**Comment by justinclift** [comment]
k, for OSX lets make the default 12?

The others can probably remain whatever they are for now. :smile:

**Comment by justinclift** [comment]
Just added a commit to make 12pt the default on OSX: https://github.com/sqlitebrowser/sqlitebrowser/commit/980429debd4cfb358333b8f86967349dac08b7a6.

**Comment by MKleusberg** [comment]
Sounds like a good first step :smiley: It's only affecting new users though. Might be a good idea to try to do some poll via Twitter or so to ask long time users what settings they use there. Not sure if that's a good idea or just producing more confusing data.

**Comment by chrisjlocke** [comment]
Just joining the sharing party with a Windows inclusion... (also so there is a comparison)

15pt:
![image](https://cloud.githubusercontent.com/assets/7872218/19349994/e1f03676-914d-11e6-8bf0-58f9bd9d822a.png)

12pt
![image](https://cloud.githubusercontent.com/assets/7872218/19350036/0cc25050-914e-11e6-8c51-2700f56b0752.png)

8pt:
![image](https://cloud.githubusercontent.com/assets/7872218/19350025/fe566182-914d-11e6-8291-175b00955404.png)

So for me, 10 or 11pt would be my chosen size.

**Comment by justinclift** [comment]
Heh Heh Heh.  @chrisjlocke Pick one? :wink:

**Comment by whamsy** [comment]
Hi, am not sure if this is the correct thread (if not, I am sorry please let me know where to post this) but "Command" + "-" decreased the font size and I was looking for a way to increase it when I stumbled across this issue.

Wanted to ask if there is a similar command to increase the font size as well?

**Comment by justinclift** [comment]
@whamsy That's a little bit unclear.  Are you meaning for DB Browser for SQLite (DB4S), or for a different application? :smile:

If you're meaning for DB4S, the font size can be changed in `Preferences`.  We don't have any key combinations to change them live though... but now that you mention it, that's not a bad idea for us to think about. 😁

**Comment by justinclift** [comment]
@whamsy As an extra thought, for the applications which use <kbd>Command</kbd>+<kbd>-</kbd> to shrink the font size, some of them use <kbd>Command</kbd>+<kbd>+</kbd> to increase it.  Guessing you've already tried that?

**Comment by whamsy** [comment]
@justinclift Yes, I meant for DB Browser for SQLite. I have just started using it for a project and was playing around when i accidently pressed this combo.

And yes, I have tried  ⌘ + + to increase font size, but it doesn't work.

**Comment by justinclift** [comment]
No worries. :smile:

With DB4S there are two settings for font size in `Preferences`, each affecting different things.

To change the font size in the Browse Data tab, go to `Preferences` → `Data Browser` → `Font` → `Font size`:
![screen shot 2016-10-14 at 01 44 31](https://cloud.githubusercontent.com/assets/406299/19372005/ef71fb6a-91af-11e6-8fc7-eda403db38e4.png)
To change the font size in the `Execute SQL` tab, go to `Preferences` → `SQL` → `SQL editor font size`:
![screen shot 2016-10-14 at 01 45 19](https://cloud.githubusercontent.com/assets/406299/19372004/ef7114d4-91af-11e6-8e26-c3cb30acd14a.png)
Does that help?

**Comment by whamsy** [comment]
@justinclift I did go through the thread and figured that out from an earlier comment of yours. Thanks a lot for posting it again though :)

I was just wondering since there appeared to be a shortcut to decrease font size (in the Execute SQL tab), was there anything similar to increase font size as well.

**Comment by justinclift** [comment]
Ironically... I didn't know about the <kbd>⌘</kbd>+<kbd>-</kbd> key combination. :wink:

Testing it here now though... and yep it works.  At a guess, it *might* be something we inherit from one of the widgets we embed (QScintilla).  But not sure.

Trying out <kbd>⌘</kbd>+<kbd>+</kbd>, it works for me if I use the <kbd>+</kbd> key on the number pad.  But it doesn't work for me using the <kbd>+</kbd> key on the main keyboard. :frowning:

**Comment by chrisjlocke** [comment]
> it works for me if I use the + key on the number pad but it doesn't work for me using the + key on the main keyboard

There's a similar quirk in Windows.  With date picker controls (eg:
![image](https://cloud.githubusercontent.com/assets/7872218/19376755/980fd4d6-91d8-11e6-94ec-da773c35b5df.png)
You can click on the day and use the + and - to go forward/back a day.... unless you use the +/- on the main keyboard, when it does nothing.  Annoyingly it doesn't work on my laptop either.  👎

**Comment by justinclift** [comment]
@chrisjlocke I'd like to close this issue, as the default font size on OSX has been adjusted.

If you pick new font size for Windows, we can change it as well. :smile:

**Comment by ghellquist** [comment]
Hmm.
The code has been changed, but default value is still 9 when I run the program, version 3.9.1. 
Could there be some error in build system, not setting Q_OS_MAC correctly? (Or is this simply not yet in version 3.9.1)

(Code is in Settings.cpp, line 200 and forward).

    // editor/fontsize or log/fontsize?
    if((group == "editor" || group == "log") && name == "fontsize")
#ifdef Q_OS_MAC
	// Use 12 pt size as the default on OSX
        return 12;
#else
        return 9;
#endif

**Comment by justinclift** [comment]
@ghellquist Yeah, this was added after the 3.9.1 release, so (in theory) it should be in the nightly builds from a few weeks after that release.

**Comment by ghellquist** [comment]
Hi Justin.
New user, new to github (history 20 years ago as programmer). Learning how to do things.
/Gunnar

**Comment by justinclift** [comment]
No worries at all.  Sorry if I was a bit abrupt, it's been one of those days... 😦

**Comment by ghellquist** [comment]
No hard feelings.
And not to abrupt. 
I should have done a better search.
Hoping I can contribute a bit in the future, right now only checking how to do things.

Best wishes
/Gunnar

**Comment by justinclift** [comment]
Closing this now, as it seems to be fixed. :smile:

(if that's not the case, this is welcome to be reopened)
