### ISSUE TITLE
Plot: Respect the "Order by" clause when plotting

### ISSUE THREAD

**Issue by struck89** [sqlitebrowser/sqlitebrowser#821]
### Details for the issue

The plot is done in such a way, that the variable selected as "X", is the one that forces the order of the connecting points, So take a look at this nice loop:
![good](https://cloud.githubusercontent.com/assets/18152095/19331980/16dbe378-90b6-11e6-9226-1913d242d070.PNG)

I can't turn on the lines, because it does not respect the order I asked (order by t):
![bad](https://cloud.githubusercontent.com/assets/18152095/19331999/2e3f7f5c-90b6-11e6-8fa4-0b1a70a60f00.PNG)

### Useful extra information

The first color it appeared when making this mock example was YELLOW!! 

#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Heh Heh Heh, that's interesting plotting. :smile:

This request makes sense.  Personally I have no idea how to implement it, but hopefully someone else in the team does. 😀

**Comment by revolter** [comment]
I don't even understand why is this happening :/

**Comment by struck89** [comment]
@revolter It kind of makes sense that somewhere in the code there is a line that says, order the rows by X.
Because if not, given the definition of a relational query, the order doesn't matter, so it could be that the results would appear like this:
![wrong](https://cloud.githubusercontent.com/assets/18152095/19350645/9a3e31b0-9126-11e6-923d-78c6308c47ec.png)
Instead of like this:
![right](https://cloud.githubusercontent.com/assets/18152095/19350673/b1283998-9126-11e6-974d-42d0aa17e94e.png)

It's the exact same plot, but the order of the rows is switched.

**Comment by MKleusberg** [comment]
I'll just drop this link here as a reminder for myself:
http://www.qcustomplot.com/documentation/classQCPCurve.html

**Comment by mgrojo** [comment]
@struck89 I've implemented a change for using the QCPCurve when the table/query is not sorted by the X field. That looses some options for the line style, but only for that case. When the table is already sorted by X, everything stays the same. Could you test with the next nightly build how does it work with your data?

Indirectly, this solves too the problem that you reported in #838 about the incorrect row being selected.

**Comment by struck89** [comment]
@mgrojo 
The result is awesome. Thank you a lot
There are now some bits here and there which need some tweaking. The fetch-all button is not working properly now:
https://we.tl/YpPuaVtxwR

So, now that we have reached this amazing point, now I will throw you another challenge to think about:
Two or more parametric curves:
![image](https://user-images.githubusercontent.com/18152095/34664414-0ce7712e-f45c-11e7-8b9e-2e3fab3dd723.png)

You would need for curve 1, x1 and y1, for curve 2, x2 and y2.
🕺 

(btw, in my case, I don't see any loss in plotting functionality)

**Comment by mgrojo** [comment]
@struck89 Good catch about the fetch-all button. This is due to the oddness that the QCustomPlot API has for  the curves. It is clearly an afterthought. That should be fixed now. 

Your new idea deserves some thought :thinking: Could you open a new issue for that and develop a bit the user story :smile: It will probably not materialise soon, since we want now to get ready for the
 3.11.0 release.

**Comment by mgrojo** [comment]
By the way, the bit lost for the plot when there are curves is that only None and Line can be selected as line type. The other styles are only allowed by QCustomPlot for graphs.

**Comment by justinclift** [comment]
Sounds like the capabilities of the Plot pane are really expanding.  Should we create a "How to use the Plot pane" page on the wiki (with screenshots)?

**Comment by mgrojo** [comment]
Wiki suggestion copied in #226. It seems this can be closed now.
