### ISSUE TITLE
Another strange HTML escaping related bug

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#823]
### Details for the issue

Noticed a small bug in the "Execute SQL" tab.  The panel at the bottom incorrectly turns quote characters into "&quot;":
![screen shot 2016-10-13 at 10 26 52](https://cloud.githubusercontent.com/assets/406299/19343900/104b0ea6-9130-11e6-9c69-c441ea96e983.png)

Tested with both 3.9.1 and git master.  The bug is present in both.

As a thought, it might be related to https://github.com/sqlitebrowser/sqlitebrowser/commit/b9dd11df538bcd084b7b18b9fe142574c3a4f2f1.

#### I'm opening this issue because:

- [x] DB4S has a bug

#### I'm using DB4S on:

- [x] Mac OS: ( _version:_ 10.11.6 )

#### I'm using DB4S version:

- [x] 3.9.1
- [x] Other: git master https://github.com/sqlitebrowser/sqlitebrowser/commit/e76e5b3241af5e79474ae32fda393da921696d96

**Comment by MKleusberg** [comment]
Should be fixed :smiley:

**Comment by justinclift** [comment]
Thanks @MKleusberg, yep, verified here. :smile:
![screen shot 2016-10-13 at 11 50 51](https://cloud.githubusercontent.com/assets/406299/19346467/5ffece64-913b-11e6-8b02-ccfedf2726e6.png)

**Comment by justinclift** [comment]
Travis seems to have barfed on the commit, but it seems like a Travis infrastructure problem and not really a problem in our code.

**Comment by MKleusberg** [comment]
Yeah, at least it compiled on gcc. Let's just see what Travis does for the next commit...
