### ISSUE TITLE
Updated version of the Xcode 8 patch

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#824]
Updated patch here, developed by [Alan Garny](https://www.riverbankcomputing.com/pipermail/qscintilla/2016-October/001167.html):

&nbsp; &nbsp; https://github.com/Homebrew/homebrew-core/pull/5877

Haven't tried it yet as I'm focused on other bits.  If no-one gets to it before me, I'll try it out in the next few days. :smile:

**Comment by MKleusberg** [comment]
@justinclift Any update on this? :smiley:

**Comment by justinclift** [comment]
I'm kind of thinking this probably isn't an issue now, since (I think) the [update for qscintilla you pushed yesterday](https://github.com/sqlitebrowser/sqlitebrowser/commit/bddae31bf12b3ad050104352851d7a0b25886613) takes care of things.

@agarny Thoughts?  Does the latest qscintilla release solve the problem properly? :smile:

**Comment by justinclift** [comment]
@MKleusberg Ugh... it seems like QScintilla have switched their codebase to be GPLv3 *only* with no prior warning (?):

&nbsp; &nbsp; https://github.com/opencor/opencor/issues/1301

I'm kind of thinking we'll either needs to drop back to the version prior to that change, or pick a different library. 😦

**Comment by justinclift** [comment]
Further reference:

* https://www.riverbankcomputing.com/pipermail/qscintilla/2016-March/001105.html
* https://www.riverbankcomputing.com/pipermail/qscintilla/2017-May/001203.html

**Comment by agarny** [comment]
@justinclift: I can see that you just found the two links I was going to send you. So, as you may have seen, the latest version of QScintilla that contains the GPL exception is version 2.8.4, which was released in September 2014 (!!). The author of QScintilla has been considering switching to LGPL+commercial for more than a year now, but still hasn't made up his mind.

For my project, we can't afford going back to 2.8.4, so we discussed it internally and we have decided to switch to GPLv3 (see issue opencor/opencor#1301).

**Comment by agarny** [comment]
> @agarny Thoughts? Does the latest qscintilla release solve the problem properly? 😄

FWIW, QScintilla 2.8.10 does indeed solve the problem.

**Comment by MKleusberg** [comment]
Same problem here. We have some (minor) problems with QScintilla and I hope that the new version (or some future version) might fix them. And since I don't know about any good alternative we'll probably have to stick with QScintilla...

Same for qcustomplot by the way. That seems to be licensed under GPL v3, too, and that not just for the latest version.

**Comment by justinclift** [comment]
@agarny Thanks. :smile:

@MKleusberg I might have jumped the gun with worrying about the QScintilla license change.  The MPLv2 part of our licensing looks like it's compatible so we shouldn't have a problem.

&nbsp; &nbsp; https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-and-lgpl

**Comment by justinclift** [comment]
Closing this, as it seems like a solved problem. 😁

**Comment by MKleusberg** [comment]
Cool :smiley:

This license chaos always reminds me of [this article](http://250bpm.com/blog:82) :wink:

**Comment by justinclift** [comment]
Oh wow, that's a fairly awesome article.  Hadn't come across it before and it raises a concept I'd not yet seen. :smile:
