### ISSUE TITLE
Importing a .sql file take an extended period of time

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#827]
### Details for the issue

I had a database with a 'database image is malformed' as my application crashed during importing.  DB4S was able to create an export of the database.  Back in DB4S and I clicked **New Database** and **Import Database from SQL**.  So far, for a 80 MB SQL file (approx 501,000 lines) its taken an hour and its on 2%.  CPU for DB4S is approx 26%, but the disk is chuggin' away.  

Edit: Cancelled it.  It had done 20,000 rows in that hour.

Edit 2: Just pasted the 80 MB SQL file in the 'Execute SQL' tab, and now regret that decision.  Thats worse than the import (wondered if the Execute SQL would obey the 'BEGIN' and 'COMMIT' transaction but don't think it will...) as its now got no progress.

If anyone wants to experiment, the 80 MB .SQL file is here:
https://we.tl/sTRssetyAB
(link will expire in one week... will upload it somewhere else by then)

This links to issue #568 and was first 'identified' in that, but todays 'experience' has reminded me to open another issue about it...
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows: ( _version:_8 and 10 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [ ] 3.9.1
- [x] 3.9.0
- [ ] Other: ___
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
This might be a good way for us to experiment with profiling stuff for DB4S.

If it turns out the problem bits are in our code, instead of in SQLite/SQLCipher, then it's something we could probably affect.

With PostgreSQL, performance for things like this can be hugely changed by adjusting buffers and some PostgreSQL settings prior to an initial import.  There might be similar things we can do for SQLite/SQLCipher, as this performance problem has been mentioned multiple times before.  It's probably a good thing for us to get fixed. :smile:

**Comment by chrisjlocke** [comment]
I'll knock up my own VB app pumping this stuff into a database, comparing one transaction to a series of transactions.  Its mentioned that a series of inserts without a transaction is effectively a series of individual transactions, which is extremely costly, performance-wise.

**Comment by chrisjlocke** [comment]
OK, so while adding records into my 'bloat' database to help tinker with another issue, I tweaked it to add 'test' into a database.  My program can import about 10 records a second.  Disk IO is also quite high, as its committing each insert to disk each time.  It'll take 8 to 10 minutes (and a new hard drive...) to import 5000 records.
After wrapping the routine in a BEGIN and COMMIT, the initial insert of 5000 records takes 4 seconds and approx 3 seconds of a disk splurge at the end to commit the data.  

From this experiment, I can conclude the import from DB4S is not using transactions.

**Comment by justinclift** [comment]
Cool.  That's definitely something we can control then. :smile:

The question is now "why is it doing that?", as we've previously put effort into making sure imports happen in a transaction.

**Comment by justinclift** [comment]
@chrisjlocke If you have a few minutes to try, would you be ok to try importing with DB4S again, but try manually setting the synchronous PRAGMA to OFF (via execute SQL tab) first?

&nbsp; &nbsp; https://www.sqlite.org/pragma.html#pragma_synchronous

Kind of thinking that might be a useful workaround for now.

**Comment by MKleusberg** [comment]
@chrisjlocke Can you try again using one of the last nightlies? I have optimised the SQL import a bit in commits d783d36dbde97e04827009b6a84d18a984266117 and 13a8a1f282b334bbaff15505b38d07122cef574e. As far as I remember this was a pretty noticeable performance gain, so it's definitely worth checking if we can close this issue :smile:

**Comment by MKleusberg** [comment]
@chrisjlocke Ping :innocent:

**Comment by MKleusberg** [comment]
Closing this because I believe the performance is already a lot better than it was when this issue was opened and I haven't heard of any contrary news :wink:
