### ISSUE TITLE
Exporting a table in csv in windows doesn't add new line

### ISSUE THREAD

**Issue by flavio20002** [sqlitebrowser/sqlitebrowser#828]
In windows 10, when exporting a single table, all the characters are on the same line, making it impossible to reuse the data for importing.

**Comment by chrisjlocke** [comment]
The carriage return isn't set automatically for us Windows users... I presume you've found that option now! :Smile:

**Comment by justinclift** [comment]
@chrisjlocke Should we change this default for Windows users?

**Comment by chrisjlocke** [comment]
I think it's just making the option more prominent. If have to check on a fresh install, but I think the option is blank, which doesn't help, so it's easy to miss.

**Comment by justinclift** [comment]
No worries.  It should be pretty trivial to change the default for Windows. :smile:

If it does turn out to be needed, file an issue and someone can probably get it done pretty quickly.
