### ISSUE TITLE
dragonflyBSD: libicui18n.so.55 not found

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#837]
Hi All,

I've been able to build qlitebrowser from source on my dragonfly system in the very
recent past, but it breaks now and it's probably because something to do with dropping
qt4 support or something. I'm not very familiar with qt5 at this point.

Any clues on how I get this building?

```
Generating moc source moc_sqltextedit.cpp
Generating moc compilation sqlitebrowser_automoc.cpp
[ 62%] Built target sqlitebrowser_automoc
[ 63%] Generating ui_AboutDialog.h
Shared object "libicui18n.so.55" not found, required by "libQt5Core.so.5"
*** Error code 1

Stop.
make[2]: stopped in /home/user/bin/sqlitebrowser
*** Error code 1

Stop.
make[1]: stopped in /home/user/bin/sqlitebrowser
*** Error code 1

Stop.
make: stopped in /home/user/bin/sqlitebrowser
```

I don't have `libicui18n.so.55` but I have libicui18n.so.57.

```
> ls -l /usr/local/lib/libicui18*
-rw-r--r--  1 root  wheel  5550074 Oct  3 11:23 /usr/local/lib/libicui18n.a
lrwxr-xr-x  1 root  wheel       18 Oct  3 11:23 /usr/local/lib/libicui18n.so -> libicui18n.so.57.1
lrwxr-xr-x  1 root  wheel       18 Oct  3 11:23 /usr/local/lib/libicui18n.so.57 -> libicui18n.so.57.1
-r-xr-xr-x  1 root  wheel  2531432 Oct  3 11:23 /usr/local/lib/libicui18n.so.57.1
```

Thanks!

**Comment by justinclift** [comment]
Ahhh, that's interesting.  It looks like the libicu libraries your Qt5 was compiled with have changed underneath it.

If Qt5 was installed from DPorts, is there an update/upgrade for it?  I'm kind of thinking there should be a newer build of it out, that (correctly) references the newer .57 version.

**Comment by jungle-boogie** [comment]
Hi @justinclift,

There likely could be something newer, but dragonfly doesn't build all the ports at once into packages so the packages I have are the most recent. The next update there is, I'll see if sqlitebrowser will build.

Thanks,
sean

**Comment by jungle-boogie** [comment]
This is the last and latest revision of qt5 for freebsd (almost the same as dragonfly):
https://svnweb.freebsd.org/ports?view=revision&revision=422306

dragonfly ports:
http://mirror-master.dragonflybsd.org/dports/

**Comment by jungle-boogie** [comment]
Turns out I didn't have devel/qt5-core. Installing that resolved the build issues!

**Comment by justinclift** [comment]
Awesome. :smile:
