### ISSUE TITLE
"Edit Database Cell" area not cleaned after closing database

### ISSUE THREAD

**Issue by firstrose** [sqlitebrowser/sqlitebrowser#839]
### Details for the issue

Just as title.
![dbb-sqlite-bug](https://cloud.githubusercontent.com/assets/1551595/19507447/94ee7de4-9605-11e6-8b80-99666d0c36d8.png)

The bug exists in DB Browser for SQLite-2016-10-21 , both x86 & x64 version.

Step to reproduce:

1.Open database
2.Click "Browse Data" Page, click a data cell , and "Edit Database Cell" shows the content.
3.Close database.

![dbs-bug](https://cloud.githubusercontent.com/assets/1551595/19589019/3b0bc410-979c-11e6-950a-79771e3a6d96.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: windows7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [x] 3.9.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
The 'Write Changes' and 'Revert Changes' button don't have the proper translations ... is this v3.9?  Thought (sorry ... assumed) all translations for the UI had been completed...

**Comment by innermous** [comment]
Can't reproduce it in HEAD revision.
Try nightly version. In such situations you should always try nightly versions.

**Comment by justinclift** [comment]
@chrisjlocke We didn't receive updated translations for either of the Chinese locales in time for 3.9.x. 😦

**Comment by justinclift** [comment]
The "simplified Chinese" locale is being updated for the master branch in #840, so the nightlies should see some improvement there soon. :smile:

**Comment by chrisjlocke** [comment]
Can you see chrisjlocke.co.uk?  I can duplicate them there for you.  Alternatively, I can email them over - they are approx 14 MB... so some email systems might baulk at that size.  Or I can lob some up at wetransfer.com...

**Comment by firstrose** [comment]
@chrisjlocke

Yes! I can access chrisjlocke.co.uk, your blog.
It seems that nightlies.sqlitebrowser.org is blocked by GFW.

Could you upload the latest nightly build to your blog? I'll test it.

Thank you for your kind help.

**Comment by firstrose** [comment]
@chrisjlocke

Yes! I can access chrisjlocke.co.uk, your blog.
It seems that nightlies.sqlitebrowser.org is blocked by GFW.

Could you upload the latest nightly build to your blog? I'll test it.

Thank you for your kind help.

**Comment by chrisjlocke** [comment]
Excellent.  I've copied the 32 and 64bit versions (of both types ... normal SQLite and SQLCipher) to my site.  
http://chrisjlocke.co.uk/db4s/

Hope it works! 😄

**Comment by justinclift** [comment]
Awesome, thanks Chris. :smile:

It's interesting that our nightlies server is probably being blocked by the GFW.  It's running from my old personal VM in Linode, as I hadn't moved it to Rackspace.

I'll create a new VM in Rackspace, and lets see if that gets blocked or something too.

**Comment by chrisjlocke** [comment]
/off-topic
GFW?  *blank look*  Global Force Wrestling?  Great Furry Wombles?  Grey Ferocious Weasels?

**Comment by justinclift** [comment]
:wink:

**Comment by justinclift** [comment]
GFW == Great Firewall. The name commonly given to China's national-level firewall implementation.

**Comment by justinclift** [comment]
@firstrose I have just moved the "nightlies.sqlitebrowser.org" web server to a new data centre, and it's also now using HTTPS.

Does this link work for you?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org

**Comment by firstrose** [comment]
@justinclift

Great! It works! THANK YOU!

:)

**Comment by firstrose** [comment]
The bug exists in DB Browser for SQLite-2016-10-21 , both x86 & x64 version.

Step to reproduce:

1.Open database
2.Click "Browse Data" Page, click a data cell , and "Edit Database Cell" show the content.
3.Close database.


![dbs-bug](https://cloud.githubusercontent.com/assets/1551595/19589019/3b0bc410-979c-11e6-950a-79771e3a6d96.png)

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by chrisjlocke** [comment]
![image](https://cloud.githubusercontent.com/assets/7872218/19605119/4b5215fe-97b0-11e6-903e-e5c780af4ee4.png)
