### ISSUE TITLE
windows builds duplicated?

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#841]
Hi All,

I have no problems with this but I noticed http://nightlies.sqlitebrowser.org/win64/ contains builds from the 17th, 18th and 19th but all three builds (17,18,19) have the 19th datestamp. Do you want to keep a number of older builds around? Are they actually older builds or today's build with the wrong file name?

```
DB Browser for SQLite-2016-10-17-win64.exe
DB Browser for SQLite-2016-10-18-win64.exe
DB Browser for SQLite-2016-10-19-win64.exe
```

**Comment by justinclift** [comment]
Ahhh, well spotted.  At the moment the nightly build script also leaves them on the build server, just in case there's a transient upload failure, and uploads DB*.exe.

I hadn't thought that through though, and it looks like it's uploading all the files each morning, even the ones which already exist.  Oops.

I'll see if it's feasible to switch to rsync for the upload, which doesn't have that problem. :smile:

**Comment by justinclift** [comment]
@jungle-boogie Just updated the Windows nightly build script.

I **think** this is fixed now, though we should keep an eye on it for a few more days to be safe. :smile:

**Comment by chrisjlocke** [comment]
I download them regularly, so will have a look!

**Comment by justinclift** [comment]
Awesome, thanks @jungle-boogie. :smile:

**Comment by chrisjlocke** [comment]
?! ;)

**Comment by jungle-boogie** [comment]
haha @chrisjlocke

**Comment by justinclift** [comment]
Ahhhh, yeah, not watching close enough... 👼

**Comment by chrisjlocke** [comment]
s'okay - I answer to anything.... on weekends I'm @susan....  ;)

**Comment by justinclift** [comment]
:wink:

**Comment by jungle-boogie** [comment]
builds look better!

```
DB Browser for SQLite-2016-10-17-win64.exe         17-Oct-2016 03:46
DB Browser for SQLite-2016-10-18-win64.exe         18-Oct-2016 03:44
DB Browser for SQLite-2016-10-19-win64.exe         19-Oct-2016 03:44
DB Browser for SQLite-2016-10-20-win64.exe         20-Oct-2016 03:44
````

**Comment by jungle-boogie** [comment]
hi @justinclift,

Windows builds are not duplicated, but it seems the list will grow forever.

There's been a build for each sqlitebrowser since the 17th. I don't know how many you wanted to leave available, so I'm re-opening just to bring to your attention.

You have 20 builds total since the 17th of October and this stray:
sqlitebrowser-win64-with_sqlcipher-201605041823

**Comment by justinclift** [comment]
Thanks @jungle-boogie.

The server has 75GB set aside for this.  It's not going to be a problem any time soon. :smile:

**Comment by jungle-boogie** [comment]
awesome, @justinclift. I'll close and keep it closed. :)

**Comment by chrisjlocke** [comment]
I personally like a 'history' of nightlies, so if a problem is found, we can either find a 'working' copy or find out when it broke...  just my 2p worth... ;)
