### ISSUE TITLE
Change default CSV export options to include newlines on Windows

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#842]
There have been a few bug reports of DB4S mangling CSV output on Windows.

These have turned out to (technically) be "user error" from not having any newline character set in the Export CSV dialog options.

What this probably really means though, is that we should set the newline character as the default line ending on Windows. :smile:

**Comment by chrisjlocke** [comment]
I would also suggest the quote character is also defaulted to a quote ( " ).  At the moment, with nothing set, a NULL character is used, confusing people in thinking its garbled text.

**Comment by justinclift** [comment]
@innermous This one might be worth looking at, at the same time: #845

Seems related. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Would you have time/interest to try the nightly build tomorrow?  @innermous just committed a fix for this. :smile:

**Comment by chrisjlocke** [comment]
Surely can....

**Comment by chrisjlocke** [comment]
Deleted the registry settings and yes, DB4S resorted to comma, quote and newline characters as a default.  Issue #845 remains though.  Interestingly, setting manual quote characters gives different results to selecting 'hard wired' characters.  Not sure whats that about.... 😖 Guess its to do with the logic on what needs to be quoted and what doesn't.  This can be closed though, as the above issue is to do with #845.

**Comment by justinclift** [comment]
Awesome, thanks guys! :smile:

**Comment by innermous** [comment]
@chrisjlocke 
>#845 remains

Yeah, I haven't done anything to it yet. Don't understand the problem either, I'll investigate it soon.
