### ISSUE TITLE
SqliteBrowser support for extensions: "intrinsic (JSON1)" and "externals", and compiler-toolchain options: "windows/clang"

### ISSUE THREAD

**Issue by dsimcg** [sqlitebrowser/sqlitebrowser#844]
### SqliteBrowser support for **_extensions:_** "intrinsic (JSON1)" and "externals", and _compiler-toolchain options_: "Windows/`clang`"

_The following is a effectively a direct re-post of the e-mail I sent yesterday to Justin Clift, which I am posting here at his most kind e-mail suggestion._

Hi Justin,

Apologies for directly pinging you, I can't find any other means to inquire on a "posting-board" of some kind.

**SqliteBrowser** is a great project and a valuable community asset.

**QUESTION-1**: I was looking to see whether the _intrinsic_ **JSON1** _extension_ could be turned on _by-default_ in the nightly builds _(at least the **Windows** version)_ of **SqliteBrowser**?

_Side-note on non-intrinsic **Sqlite** extensions_: Given that **SqliteBrowser** is a great and openly available tool specifically for **Sqlite**, it makes sense to me that it also would be a hosting location for obtaining **Sqlite _extension libraries_** that are binary-compatible with its various platform versions. _Which, leads me to the more detailed second question..._

_First, some contextual background_: I do development work on **afm-scm** (afm-scm.org) _[which is a compatible variant of **fossil-scm**]_ and its integrated **TSL** language-engine and its hosting **AOS** object-system-engine. The **T**ext-**S**cripting-**L**anguage (ts-lang.org) is, for the most part, a superset of TCL blended with JavaScript, Smalltalk, Lisp/Scheme and intrinsically supports and integrates **Sqlite**.

**QUESTION-2**: Would it make sense to enable seamless `make` of **SqliteBrowser** _(on any platform, but especially **Windows**)_ using `clang` as a supported _(possibly-default)_ choice for a fully cross-platform compiler build tool for **SqliteBrowser**?

If one wants cross-platform source build compatibility at the C/C++ language and toolchain level there are few natively compatible options; and only one _(_`clang`_)_ that is also _gnu-compatible_.  As it stand now, building **SqliteBrowser** for **_Windows_** is a _non-trivial distraction_ since it requires variations of the _gnu-based_ toolchain to build quasi-compatible **_Windows_** binaries _(or an apparently complex setup of components to build via **VisualStudio** or_ `cmake` _or_ `nmake` _etc)_.

Not having some solution to these questions, in practice, _cripples_ **SqliteBrowser** use with "optional" Sqlite features and extensions. 

The **SqliteBrowser** _default_ releases do not link to a **Sqlite** _(coff)_ library so one has to **_recompile_** the whole **SqliteBrowser** app. I.e., it doesn't reference **Sqlite** via a `shared-library` and its binary depends on the _gnu-toolchain_. Thus, things like the **_intrinsic JSON1 extension_** are "apparently-hard" to build as a **Sqlite** _discrete extension_. This is **quite** "problematic".

_Point in case_: I have various databases with **TRIGGERS** that use and depend on **JSON1** _(an invaluable extension to **Sqlite**)_. The **SqliteBrowser** is _unusable_ with those database tables that have such triggers.

I don't have any _obvious solution_ other than to take the time and effort to create an _alternative_ to **SqliteBrowser** built-on the **_afm/fossil_** toolset. 

But, my real hope and desire is that the **SqliteBrowser** team might be open to a path to enable _intrinsic_ **Sqlite** _extensions_ such as **JSON1** to become accessible via **SqliteBrowser** either by it being built to reference **Sqlite** via a `shared-library`, or making various _intrinsic extensions_, such as **JSON1**, enabled _by-default_ in the **SqliteBrowser** app builds. 

This would be further aided in its simplicity and flexibility with cross-platform support for `clang` as a standardly supported build-chain tool. I assert this would eliminate _(most, if not all)_ special case platform issues for **Windows**.

A bit of other _background_ on `clang` availability: The current **Windows** `clang-tools` are available _freely_, and _natively_ integrated and supported within **Visual Studio** from **Microsoft**; as well as being _freely_  available from the `primary clang team` for use as `standalone` **Windows** based _gnu-compatible_ compiler tools. 

It might _(and probably would)_ be easier to configure the **Window's** builds to use either the _free_ `native` **Window's** **Visual Studio** `clang` tools or the _freely_ downloaded **Windows** `standalone` command-line `clang-tools` from the _official_ `clang` website. 

**SqliteBrowser** supporting a standard model of `clang` based build configuration would allow building on almost every platform with the same _gnu-compatible_ compiler. _This is what I use for building my code on all processors (Arm, Intel, ...) and platforms (BSD, Linux, Windows, OSX, ...); and worthy of mention, is that this also enables the **option** to build **for-all** platforms simultaneously on  single machine - although that is a bit more work :-) to set up._

Thanks for listening,

David Simmons
#### I'm opening this issue because:
- [X] DB4S needs a feature
- [X] DB4S has another problem

**Comment by justinclift** [comment]
Some initial thoughts from my point of view: :smile:

1. I was looking to see whether the *intrinsic JSON1 extension* could be turned on by **default** in the nightly builds _(at least the **Windows** version)_ of **SqliteBrowser**?

  Yep, this would be welcome.  The current build process we use for Windows (via MSVC) is - as you said - overly complicated.  Having any kind of reliance on MSVC isn't something I personally like either. ;)

  The only thing which has stopped us from adding in the JSON1 support on Windows by default... is lack of time to try it compiling it in.

  If you have the time & desire to work out what we need to do - eg extra commands/steps to run - in our build process, we'll definitely try it out and likely adopt them wholesale. :smile:

2. Would it make sense to enable seamless `make` of **SqliteBrowser** _(on any platform, but especially **Windows**)_ using `clang` as a supported _(possibly-default)_ choice for a fully cross-platform compiler build tool for **SqliteBrowser**?

  Any (good quality) alternative to MSVC would be warmly welcomed. Our OSX builds already use clang, as that's what Apple's Xcode comes with.

  On Windows, we use CMake to generate MSVC "solution / project" files.  These can then be either used interactively via MSVC, or compiled in batch fashion using `devenv`.

  CMake can be told to generate Makefiles and similar, so it might be quite possible to get things working with a native Clang install.

  If you have the time & desired to figure that out, we can definitely try building that way.

Personally, I'd be only too happy to completely remove MSVC from our requirements list, and completely remove it from our documentation. :smile:

Note - In both instances above the "If you have the time & desired to..." bit. That's because we're volunteer based, so the things that get done are whatever people put time into.  You're absolutely welcome to join in and attack things of interest. 😁 

Same for the side note - hosting related extensions could be done - it needs someone with the interest & desire to make it happen though.  If that's you, then great.  If not, then maybe someone else will.

**Comment by dsimcg** [comment]
I spent some 4 hours on this and the CMAKE file is difficult in terms of 
the dependency list and what needs to be configured. I am pretty sure 
that doing this right is many days of work to revise the build process, 
easier to start from scratch.

During the 4 hours or so I spent, it required polluting a dev-box with 
superfluous tools and libraries and language runtimes.

I.e., The build steps are fragile. QT is a beast. I ran out of time with 
ANTLR and QT issues and configuring CMAKE_PREFIX_PATH, ...

It has hard-coded paths, version information ...

The CMake file assumed explicit versions of many of its dependencies on 
binaries and particular libraries. QT is onerous for many reasons 
including the managerial aspects introduced by their marketing approach 
to make money.

It assumes various tools and libraries are installed that are not called 
out in the material listed on:
   
https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S

I found the CMake code process complicated with dependencies.

I understand it is portable-UI (around the scintilla-core editor) over 
the portable and easy to build SqLite engine.

For the windows components there is no-need for the redist files, just 
link them into the binary. The libs could be linked in or provided as 
so/dll's and on windows use delay-loaded dlls.

Could it not be built as: (cmd line for 32/6 bit build)
====
a) SqLite lib reference (binary download - or discrete C-compiler build)
b) Translation tool for localization of code (perhaps directly invoking 
Linguist tool if that is best option)
c) OpenSSL lib reference (binary download - or discrete C/C++ build) 
[why is SSL required?]
------
d) Qt lib reference (binary download - or discrete build)
e) Drag-install with self-installation/uninstallation in Main to avoid 
need for NSIS

The ANTLR reference does not make clear if it is using Java, Python, C#, 
etc; or how it is expecting to access ANTLR.

If ANTLR2 is not available, it is unclear what the code will need or 
will try to do...

I assume it is just a build:
================
1. Compile SqLite or use a existing LIB or SO/DLL
2. Compile OpenSSL or use a existing LIB or SO/DLL [which of the 
components needs this, is unclear]
3. Provide a portable UI using some framework, support locales for 
globalization
    3.1 QT Chosen, locale support provided by Linguist
    3.1.2 QT compilation (if not using pre-built binaries) requires 
Scintilla compilation
4. Package the resulting binary/resources into an installer (better if 
bundled straight into coff-binary)
    4.1 Let app be it's own installer [it does not need to register 
anything complicated with any of its host-platforms]

I think it might be easier to build and enrich as a Chromium/Electron 
app, or just see if the Linux cross-platform build steps are somehow 
simpler.

-- David

Justin Clift wrote:

**Comment by justinclift** [comment]
Cool!

Personally, I'm travelling at the moment, with only a Linux laptop.  No access to my normal development stuff.  I'll be back Friday evening/night, so should be able to get to this properly on the weekend or Monday. :smile:

**Comment by justinclift** [comment]
@dsimcg Good news.  The nightly builds on Windows - both with and without encryption - now include the FTS3, FTS4, FTS5, and JSON1 extensions.

They'll be in the next major Windows releases too. :smile:

**Comment by dsimcg** [comment]
Awesome!

**Comment by MKleusberg** [comment]
Looks like this is solved? I'll close this issue then - if I'm missing anything, please just re-open it :smile:
