### ISSUE TITLE
Export of database table does not honour quote setting

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#845]
### Details for the issue

Testing the export of a database table issue on Windows, and noticed I can't get quotes around field contents with spaces in.  Have tried both quote options, and the 'Other'.  Nothing.

http://screencast-o-matic.com/watch/cD6T6ijEHX

Tried 3.9.1 and the latest nightly.  In my experiments with options, it did do quotes once, even putting quotes round fields that didn't need it.  I couldn't reproduce that though, so unsure if something is screwy somewhere.

Edit: Just filling in the info below, and noted I'm using the 64bit version.  Unsure if it'll make a difference, but will try on the 32bit version too.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows: ( _version:_ 10 (64 bit)___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1 (64bit)
- [ ] 3.9.0
- [x] Other: _3.9.99__
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oh, interesting.  Something doesn't seem correct there.

It'd be really useful for us to add some kind of automatic testing for this.  Not sure how to achieve it though.

**Comment by chrisjlocke** [comment]
32bit was the same, and on a different computer, so its not just me... ;)
Haven't tried older versions to pick out where it went wrong.  I'm sure it used to work...
Looked (briefly) through the code, but without debug info, its hard to find out whats going on .... it *should* work.  Guess I'll add some...

**Comment by prutz1311** [comment]
It seems like it has to do with these lines https://github.com/sqlitebrowser/sqlitebrowser/blob/60e4cb758ed58db3a8d01cb13e82d79cf2d3ef33/src/ExportDataDialog.cpp#L92 and https://github.com/sqlitebrowser/sqlitebrowser/blob/60e4cb758ed58db3a8d01cb13e82d79cf2d3ef33/src/ExportDataDialog.cpp#L113-L116, that is, it quotes the contents of a field only if there are characters to be escaped. For example, if you have the following data:
![image](https://cloud.githubusercontent.com/assets/6525383/19951659/a2dced20-a170-11e6-83f8-acd018e4c9e3.png)
you can export like this:
```csv
id,flag
a,"E""E"
b,D D
c,C C
d,B B
e,A A
```

 So maybe we should introduce something like `chars_to_quote` alongside with `special_chars`?

**Comment by justinclift** [comment]
Interesting thought. :smile:

Thinking about this more, it sounds like Chris wants an option to "quote all fields", even if the quotes are not strictly needed.

Hmmm... trying to think of a use for that though... not sure what it would be useful for? :smile:

**Comment by chrisjlocke** [comment]
Aah, might just be me then.  I was under the mis-conception that fields with spaces in would need quoting, not just characters.  Thats why 'A' would not need quoting, but 'A A' would.  I must just be having a brain fart then.  I'll close this then, and revisit it if its an issue.  😄

**Comment by justinclift** [comment]
Cool. :smile:
