### ISSUE TITLE
Crashing when clicking "New Database" or "Open Database"

### ISSUE THREAD

**Issue by softdev2016** [sqlitebrowser/sqlitebrowser#847]
### Details for the issue

Hi,

I'm currently running DB Browser for SQLite v3.9.1 (64 bit) on a 64 bit version of Windows 10. Whenever I click on "New Database" or "Open Database", the program crashes. I've tried both the 32 and 64 bit versions. I get the following message box whenever the program crashes:

![image](https://cloud.githubusercontent.com/assets/23085957/19744318/a16cffa4-9b92-11e6-906f-161b5f18b1fa.png)

The event viewer contains two entries in the Windows Application Log. The first entry is below:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-10-26T20:40:38.758010900Z" /> 
  <EventRecordID>40893</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>DB Browser for SQLite.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>57f1942d</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.10586.306</Data> 
  <Data>571af2eb</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000ee6fc</Data> 
  <Data>19e4</Data> 
  <Data>01d22fc862246bd9</Data> 
  <Data>C:\Program Files\DB Browser for SQLite\DB Browser for SQLite.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>d9b8ac39-39f9-45cc-8484-5450e87ffdf8</Data> 
  <Data /> 
  <Data /> 
  </EventData>
</Event>
```

The second entry is below:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-10-26T20:41:20.649659100Z" /> 
  <EventRecordID>40894</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>120575474363</Data> 
  <Data>4</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>DB Browser for SQLite.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>57f1942d</Data> 
  <Data>StackHash_8518</Data> 
  <Data>10.0.10586.306</Data> 
  <Data>571af2eb</Data> 
  <Data>c0000374</Data> 
  <Data>PCH_9D_FROM_ntdll+0x00000000000A5C34</Data> 
  <Data /> 
  <Data /> 
  <Data>C:\Users\[USER]\AppData\Local\Temp\WERBA73.tmp.WERInternalMetadata.xml</Data> 
  <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DB Browser for S_e8b7f586f814b689dd3ef0c1d028c841c9959c0_82b7819f_09645c9f</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>d9b8ac39-39f9-45cc-8484-5450e87ffdf8</Data> 
  <Data>0</Data> 
  <Data>5ba2e3596f3412535b741ca1330b9809</Data> 
  </EventData>
</Event>
```

Can I please get some assistance in figuring out what is causing the crash?

Thanks.

#### I'm opening this issue because:
- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [x] Windows: ( _version:10 x64)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for reporting this. :smile:

Not sure we'll be be able to look into this properly in the near future though. `ntdll.dll` seems to be Windows "catch all" kind of error thing, not really giving any useful detail.

As a thought, would you be ok to try these two nightly builds and see if either doesn't crash?

* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2016-10-26-win64.exe
* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-sqlcipher-2016-10-26-win64.exe

The first one is a build with only SQLite support, not SQLCipher.  If that one doesn't crash, but the 2nd one does, at least that narrows things down. :smile:

**Comment by chrisjlocke** [comment]
It would be worth seeing if it does it in safe mode.  Aditionally, you could also test for the problem when logged on as another user (which you may need to create for testing purposes).

I run DB4S on a Win 10 64bit machine at work and have never had this issue.  :(

**Comment by softdev2016** [comment]
Thanks justin and chris. I'll try the suggestions and report back

**Comment by softdev2016** [comment]
I tried the two nightly builds but they didn't work either. I also tried running the program as an administrator, running windows in safe mode and also trying it in a different windows account (with admin privileges) and it still crashes.

I checked the entries in the Event Viewer, and it still contains the same information. It doesn't display anything different. Is there anything else that we can try?

**Comment by justinclift** [comment]
Hmmm, ok the next thing to try would be grabbing dependency walker and running that on the installed exe you're launching:

&nbsp; &nbsp; http://dependencywalker.com/

Note - The website for Dependency Walker looks like it was written in the 1980's... the tool itself though is fine, so don't get stressed by the website. :smile:

The tool itself is helpful for showing .dll problems.  Here's a screenshot from when I was looking into a problem a while ago:

![dependency_walker01](https://cloud.githubusercontent.com/assets/406299/19777975/92d06c16-9c72-11e6-8f68-60891f6a713d.png)
(that one was a mix-up of 32 and 64 bit dlls)

In your case the crash kind of sounds like a .dll problem, so I'm thinking it might be the right tool to investigate with. :smile:

**Comment by softdev2016** [comment]
I opened the executable in it. When I did so, I got the following pop up, but it still let me continue.

![image](https://cloud.githubusercontent.com/assets/23085957/19779600/6301d7ca-9c47-11e6-9cee-8f7edf37faa4.png)

Here's what it looked like after I clicked on "OK" in the popup. I get several errors, but I'm not sure where to start.

![image](https://cloud.githubusercontent.com/assets/23085957/19779607/6c7b8d46-9c47-11e6-91a2-2d9fd0c8a222.png)

I've saved and attached the .dwi file.

[DB Browser for SQLite.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/556666/DB.Browser.for.SQLite.zip)

**Comment by softdev2016** [comment]
So, if I filter out everything that begins with API-MS-WIN and EXT-MS, I'm left with the following:

```
DEVICELOCKHELPERS.DLL
EMCLIENT.DLL
IESHIMS.DLL
```

**Comment by justinclift** [comment]
Interesting, sounds like we're making progress. :smile:

It seems like there's something missing on your system then.  If you have time, try to find out which Microsoft (or Qt) package includes them, and get that installed on your system.

It's really weird this is happening though, as the dependencies are supposed to be automatically installed already. 😦 

Hmmm... what happens if you manually run the vc_redist*.exe file?  It should be in a subdirectory of the DB4S installation.  If that gives an error, it might help explain what's going wrong. :smile:

**Comment by justinclift** [comment]
@chrisjlocke Any idea about the API-MS-WIN-CORE-SYNCH thing shown in the screenshot.  Searching online shows an informational MS page about Windows "API Sets", but not sure how (if) it's relevant here.

**Comment by softdev2016** [comment]
It looks like the C++ redistributables were already installed on my computer. When I ran "vcredist_x64.exe", it brought up a window with "Repair" and "Uninstall" options. I tried "Repair" first, but it's still doing the same thing. Next I tried uninstalling and reinstalling it, but still nothing.

**Comment by justinclift** [comment]
Ok, well that's one possibility ruled out. :smile:

**Comment by chrisjlocke** [comment]
Microsoft (was SysInternals) do a process monitor tool.
https://download.sysinternals.com/files/ProcessMonitor.zip

Its comprehensive, but a bit confusing.  I'll have to do a screencast tomorrow, if you want to go down that route.  The beauty of that program is that it shows all the files Windows has tried to run but failed.

I'll try and run DB4S on as 'basic' Win 10 machine I've got to try and replicate the issue.

**Comment by softdev2016** [comment]
justin,

I tried googling, but I couldn't find any leads on which installers are supposed to distribute the dll's.

chris,

That sounds promising. I'll get Process Monitor on my computer. Just let me know where to go from there.

**Comment by justinclift** [comment]
Awesome @chrisjlocke, that Sysinternals tool does sound useful.

If this works for finding a solution, we can probably use these tools for investigating future windows crash problems too. :smile:

**Comment by chrisjlocke** [comment]
OK, so heres a quick screencast of the MS Process Monitor.  As shown, its 'noisy' and monitors everything, but I think at this stage, you only need to monitor file activity, so I've shown how to toggle the other buttons off.  At the bottom of the screencast is a CC button to turn on captions.  They don't work too well, and are distracting (by the time you've read them, the screen has moved on) so you might need to watch it more than once!

http://screencast-o-matic.com/watch/cD6uQyjHkL

Alternatively, if you're brave, you could install Teamviewer and I could remotely control your machine and have a look, but I can understadn the fear of some unknown having access to yuur machine...

**Comment by justinclift** [comment]
Excellent, that looks really useful for debugging this kind of thing. :smile:

**Comment by chrisjlocke** [comment]
Not sure why (will have to test on another machine) but when I click the 'New Database', a squillion read requests are made.

![image](https://cloud.githubusercontent.com/assets/7872218/19857866/3dd5bea2-9f77-11e6-9642-4a7ce81ca539.png)

Haven't found a machine at work that DB4S crashes on yet...
As part of our 'install' for every machine, we put on .NET Framework.  Just as a test (or confirmation) do you have any .Net frameworks installed?

**Comment by justinclift** [comment]
@softdev2016 Any luck with this? :smile:

**Comment by softdev2016** [comment]
Hi Justin, sorry I've been busy working on a few other things. I should be able to try it out tomorrow. Sorry for the delay.

**Comment by justinclift** [comment]
No worries, we definitely all get too-busy sometimes. :wink:

**Comment by MKleusberg** [comment]
@chrisjlocke Those read requests are probably for the 'Save file as' dialog, maybe some recently opened files or places. So that should be all fine. But other than that I'm afraid I can't say anything on this issue :/

**Comment by ibinshoid** [comment]
Hi,
i have the same problem as softdev, but on Linux (OpenSuSE 13.1 64bit).
I've tested version 3.6.0 and 3.8.0 from SuSE buildservice and compiled version 3.9.1 myself.
When i start sqlitebrowser as root everything works fine. But when i start it as normal user it crashes with a "segmentation fault" when i click on "Open Database".

libqt version is 4.8.5

**Comment by ibinshoid** [comment]
It seems to be a bug in qt4.
I've started qtconfig and set "GUI Style" to "Motiv", everything works fine.
This could be a solution for windows too.

**Comment by MKleusberg** [comment]
That's an interesting observation, @ibinshoid! :smiley: We've recently moved to Qt5-only, so it's worth trying again with the latest code and using Qt5.

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
