### ISSUE TITLE
Foreign Key Pragma doesn't persists between connections

### ISSUE THREAD

**Issue by navdeepmahajan** [sqlitebrowser/sqlitebrowser#848]
### Details for the issue

We are using sqllitedb browser to maintain a local db on the device. The issue is everytime we close and reopen the device the foreign key constraint/pragma is unchecked and as a part user is able to insert corrupt content in the DB. Please resolve.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch, that doesn't sound good. 😦 

Does it happen even when you save using a project file?

1. Open database
2. Change Pragma setting
3. **File** → **Save Project** (then pick a filename to save as)
  
  ![screen shot 2016-10-27 at 12 21 06](https://cloud.githubusercontent.com/assets/406299/19765373/e8e53d30-9c3f-11e6-8b1c-3fdcfb6f13ba.png)

4. Close the database
5. **File** → **Open Project**
  
  ![screen shot 2016-10-27 at 12 22 01](https://cloud.githubusercontent.com/assets/406299/19765385/0348c728-9c40-11e6-9399-c23a4d7bf31d.png)

In theory, settings are supposed to be saved ok when using project files.  They're a way to wrap "meta" information about a database in a safe way.

But, it's definitely possible that's not working properly for this. 😦

**Comment by tomcumming** [comment]
Same issue on windows portable build. Also seems to ignore the pragma after I turn it on (i can still insert invalid rows)

**Comment by MKleusberg** [comment]
As a first thought: is the check box in View -> Preferences, Database, Foreign keys checked or unchecked?

**Comment by tomcumming** [comment]
Yes, it is checked

**Comment by MKleusberg** [comment]
That's odd. You said it's also ignoring the pragma after manually turning it on. I assume you did click the Save button at the bottom of the window? Sounds like a stupid question but I sometimes forget that button :wink: If you're sure you saved the modified pragma settings. it seems like we have a general problem with foreign keys in your case. Not sure yet what to do then :smiley:

**Comment by tomcumming** [comment]
yes I am :) i also tried `PRAGMA foreign_keys = on;` in the sql box and write changes after running that. Still no luck

**Comment by MKleusberg** [comment]
I did some further research: you can't edit the foreign keys pragma inside a transaction (https://www.sqlite.org/pragma.html#pragma_foreign_keys). That makes it impossible to set that pragma from inside the SQL editor. Also, unlike other pragmas, it is not stored in the database file but must be set again each time a new connection is built (https://stackoverflow.com/a/15303742). This makes it impossible to set the foreign keys pragma in the Pragma editor and expect it to stay with that value. That's pretty stupid but we can't do much about that :frowning: 

The only question is why the the check box in the Preferences dialog doesn't work for you. However, I've just changed the settings handling a bit, so tomorrow's nightly build might be worth checking out. Can you give that a try? :smiley:

**Comment by justinclift** [comment]
If it's really needed to kept, we could store that pragma setting in the (per database) project file.

**Comment by MKleusberg** [comment]
Just added the foreign keys settings to the project file :smiley: I think that's all we can do at the moment.

**Comment by justinclift** [comment]
Awesome. :smile:

@tomcumming Would you have time to try out the nightly build (tomorrow), and check that the pragma setting works for you when the database is saved & loaded via project file?

**Comment by tomcumming** [comment]
Sorry @justinclift , I won't have access to a windows PC for a while !

**Comment by justinclift** [comment]
No worries, was a thought. :smile:

**Comment by justinclift** [comment]
Oops.  Sorry, wrong button. :wink:

@tomcumming Our automatic nightlies get built for OSX too if that helps?

**Comment by MKleusberg** [comment]
Any update here? :smile:

**Comment by chrisjlocke** [comment]
I've created two project files - one with the 'Foreign Keys' checked and one unchecked.  When loading both projects, the 'Foreign Keys' option is checked, so this is still unresolved.
