### ISSUE TITLE
Export CSV broken in 3.9.1 vs 3.8.0

### ISSUE THREAD

**Issue by esilverberg** [sqlitebrowser/sqlitebrowser#850]
Hi guys,

I have tables with newlines in them (it is an event log). Old SQLiteBrowser (3.8.0) used to export these tables like a champ.

Now, 3.9.1 breaks the export and Excel/Google Drive is no longer able to parse the file you all are creating. It seems to be coming out as garbage, lines munged together, almost like the memory is corrupted somehow.

**Comment by justinclift** [comment]
@esilverberg Ahhh, it's probably the default newline setting it set to blank in the Export dialog.

Would you be ok to try the export again, and double check the newline is set to "Windows" ?

**Comment by justinclift** [comment]
For reference: #842 :wink:

**Comment by esilverberg** [comment]
That was it, thanks!

**Comment by justinclift** [comment]
You're welcome. :smile:
