### ISSUE TITLE
macOS build lacks fts4 support

### ISSUE THREAD

**Issue by compengi** [sqlitebrowser/sqlitebrowser#853]
### Details for the issue

I find it interesting to find out that mac's build of the latest app lacks fts4 support. I use the same app on windows and it has fts4.

So I'm opening this ticket as a feature request.

I also want to refer to already closed ticket https://github.com/sqlitebrowser/sqlitebrowser/issues/762 which is not clear if the feature is already added or not.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 10.12.1 )
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
OSX is unlikely to ever get FTS4 support, as we already include FTS5 support and they seem to be mutually exclusive. 😦 

It's not super hard to build it with FTS4 instead of FTS5, if you really need it. (as per the issue you pointed out)

On a side note, I didn't realise our Windows builds include FTS4.  I'm specifically doing anything there to include it... maybe it's getting pulled in as a side effect from something else (SQLCipher?).

**Comment by compengi** [comment]
I don't mind supporting FTS5 as it seems to be a more mature version of previous efforts. It seems though like FTS3/4 and FTS5 can coexist.

xerial's JDBC driver at least have both.

Here's the make file https://github.com/xerial/sqlite-jdbc/blob/master/Makefile

Hope it helps.

**Comment by justinclift** [comment]
Hmmm, I'm not seeing FTS4 in there.  FTS3 and FTS5 yep, not 4:

&nbsp; &nbsp; https://github.com/xerial/sqlite-jdbc/blob/master/Makefile#L67-L69

Am I being blind? :smile:

**Comment by compengi** [comment]
-DSQLITE_ENABLE_FTS3
-DSQLITE_ENABLE_FTS3_PARENTHESIS

Enables both FTS3 and FTS4

see https://www.sqlite.org/fts3.html section "2. Compiling and Enabling FTS3 and FTS4"

**Comment by justinclift** [comment]
Cool, that looks pretty simple then. :smile:

Any interest in sending a Pull Request to the Homebrew team, adding those two options to the line here?

&nbsp; &nbsp; https://github.com/Homebrew/homebrew-core/blob/master/Formula/sqlcipher.rb#L31

When DB4S gets built, we pull in SQLCipher via the Homebrew package.  Getting it added there means automatic support. 😀

**Comment by compengi** [comment]
I'd be glad to.

**Comment by justinclift** [comment]
Awesome @compengi, please "make it so". 😁 :

**Comment by compengi** [comment]
Done.

**Comment by justinclift** [comment]
Excellent. Once that's merged, our nightly builds should automatically pick it up too, if that helps. :smile:

**Comment by compengi** [comment]
Is there anything at this point to do?

**Comment by justinclift** [comment]
In theory, it should be automatically included in our nightly builds at this point.

Do you have a few minutes to try one of the recently ones out to verify? :smile:

**Comment by compengi** [comment]
Just tested on the latest nightly build: DB Browser for SQLite-sqlcipher_20161127.dmg
On fts4 and fts5 databases, both worked fine.

**Comment by justinclift** [comment]
Awesome @compengi, thanks for putting the effort in for this, and keeping on top of it through to completion. :smile:

**Comment by compengi** [comment]
I'm glad we got this quickly sorted out.

Now we need fts5 support on win32 as well..

**Comment by justinclift** [comment]
> Now we need fts5 support on win32 as well..

One that note :smile: the new 3.10.0 release (presently being built) has FTS5 support, and I've just added `SQLITE_ENABLE_FTS3_PARENTHESIS` to the build options so (I'm thinking) that should mean the enhanced query syntax is in there too.  Hopefully. :smile:

Any interest in taking a look and making sure?
