### ISSUE TITLE
dragonflyBSD: cmake works and qmake fails

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#855]
So cmake works on dragonfly but qmake is failing...

`/usr/local/lib/qt5/bin/qmake`

```
ase/moc_ImportCsvDialog.o  release/moc_sqltextedit.o  release/moc_ExtendedTableWidget.o  release/moc_sqlitetablemodel.o  release/moc_FilterTableHeader.o  release/moc_SqlExecutionArea.o  release/moc_VacuumDialog.o  release/moc_DbStructureModel.o  release/moc_Application.o  release/moc_CipherDialog.o  release/moc_ExportSqlDialog.o  release/moc_SqlUiLexer.o  release/moc_ColumnDisplayFormatDialog.o  release/moc_FilterLineEdit.o   -L= -L/usr/local/lib -lsqlite3 -ldl -L/home/sean/bin/sqlitebrowser/src/../libs/qhexedit -L/home/sean/bin/sqlitebrowser/src/../libs/antlr-2.7.7 -L/home/sean/bin/sqlitebrowser/src/../libs/qcustomplot-source -L/home/sean/bin/sqlitebrowser/src/../libs/qscintilla/Qt4Qt5 -lantlr -lqhexedit -lqcustomplot -lqscintilla2 -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL
/usr/local/lib/libQt5Widgets.so: error: undefined reference to 'QDateTimeParser::sectionFormat(int) const'
/usr/local/lib/libQt5Widgets.so: error: undefined reference to 'QAbstractTransitionPrivate::get(QAbstractTransition*)'
release/MainWindow.o:MainWindow.cpp:function MainWindow::on_actionOpen_Remote_triggered(): error: undefined reference to 'RemoteDatabase::fetchDatabase(QString const&)'
release/MainWindow.o:MainWindow.cpp:function MainWindow::~MainWindow(): error: undefined reference to 'RemoteDatabase::~RemoteDatabase()'
release/MainWindow.o:MainWindow.cpp:function MainWindow::reloadSettings(): error: undefined reference to 'RemoteDatabase::reloadSettings()'
release/MainWindow.o:MainWindow.cpp:function MainWindow::MainWindow(QWidget*): error: undefined reference to 'RemoteDatabase::RemoteDatabase()'
release/MainWindow.o:MainWindow.cpp:function MainWindow::MainWindow(QWidget*): error: undefined reference to 'RemoteDatabase::~RemoteDatabase()'
collect2: error: ld returned 1 exit status
*** Error code 1

Stop.
make[2]: stopped in /home/sean/bin/sqlitebrowser/src
*** Error code 1

Stop.
make[1]: stopped in /home/sean/bin/sqlitebrowser/src
*** Error code 1

Stop.
make: stopped in /home/sean/bin/sqlitebrowser
```

Any hints?

**Comment by justinclift** [comment]
Interesting.  It was building ok a few weeks ago wasn't it?

Sounds like something we've added in the meantime.  If you're up for spending a few minutes figuring out which commit broke things, try resetting back a few days and see if that helps.

eg:

```bash
$ git log     ← shows the commit history
$ git clean -dffx       ← removes cruft created by qmake/cmake run
$ git reset --hard [a commit ID here]     ← from the git log command
```

Then try the qmake/cmake dance and (and repeat) to figure out the last commit which worked. :smile:

**Comment by jungle-boogie** [comment]
Hi @justinclift,

hmmm. You may be right. Last time I needed to install devel/qt5-core, which means I may have been using `qmake` and not `cmake` to do the building.

I'll see about rolling back a few revisions and seeing if it will build with qmake.

thanks!

**Comment by MKleusberg** [comment]
The error message looks like it should go away when you delete all makefiles generated by qmake. The problem here is that I've added a new file recently (RemoteDatabase.cpp). Now, qmake doesn't always regenerate the makefiles properly, so it compiles fine but ignores any new files as they aren't mentioned in the old makefiles. And that causes a linker error as seen in your issue.

On my system there it generates a Makefile, a Makefile.Debug, and a Makefile.Release in the src/ subdirectory. You should find something similar in your build directory, too. Deleting these files should help, as qmake will regenerate them properly then, including the new RemoteDatabase.cpp.

Let me know if you need any more assistance with that :)

**Comment by jungle-boogie** [comment]
Hi @MKleusberg,

Makefile, a Makefile.Debug, and a Makefile.Release in the src/ are generated after I attempt to make like this:
`/usr/local/lib/qt5/bin/qmake`
`make`

removing the files after the failure and attempting to build again in the same way results in the failture.

```
_FilterLineEdit.o  release/moc_RemoteDatabase.o   -L= -L/usr/local/lib -lsqlite3 -ldl -L/home/sean/bin/sqlitebrowser/src/../libs/qhexedit -L/home/sean/bin/sqlitebrowser/src/../libs/antlr-2.7.7 -L/home/sean/bin/sqlitebrowser/src/../libs/qcustomplot-source -L/home/sean/bin/sqlitebrowser/src/../libs/qscintilla/Qt4Qt5 -lantlr -lqhexedit -lqcustomplot -lqscintilla2 -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL
/usr/local/lib/libQt5Widgets.so: error: undefined reference to 'QDateTimeParser::sectionFormat(int) const'
/usr/local/lib/libQt5Widgets.so: error: undefined reference to 'QAbstractTransitionPrivate::get(QAbstractTransition*)'
collect2: error: ld returned 1 exit status  
```

I rolled back to this commit the other day; 2957974974bb874b0219e52d63c198658c02f686 and qmake still failed. 

Since cmake happily works, I'm fine with that. Is there a compelling reason I need to use qmake?
