### ISSUE TITLE
Add undo/redo for Browse Data tab

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#858]
### Details for the issue

It would be great if you could undo a delete or insert. And redo if you changed your mind.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
You'd literally need a copy of the database ... and some databases are huge!  if I deleted 10,000 rows, while that statement is instant, I wouldn't want DB4S to then 'import' those records in some temporary database on the off-chance I would want to undelete... surely thats the purpose of the 'Commit Changes' button - its a 'yup, I'm happy with that' button.  If I deleted 10,000 rows and only meant 1, then I'd press the 'Revert Changes'...
Maybe I'm just paranoid, but if I'm going to be doing dabbling on a database, I make sure I have a backup first.
Also, if you delete a record and the database has gubbins to delete child records (linked tables), how would you put these records back if you pressed 'Undo' - as DB4S technically doesn't know anything about them - it just knows the record(s) you deleted.

**Comment by justinclift** [comment]
Yeah, thinking about this particular case I'm not sure how it could be implemented in a thorough way.

Any query which modifies data in non-trivial ways would probably be very challenging to automatically reverse. :smile:

**Comment by MKleusberg** [comment]
Well, Qt offer some undo stack classes which we could use. So having a undo/redo feature for the Browse Data tab would be do-able, even without copying the entire database. However, when the user modifies the same table using the Execute SQL tab, another instance of DB4S, or another program we'd end up in a complete mess.

Maybe a compromise would be to add a way to add savepoints manually and offer a way to revert to one of them.

**Comment by revolter** [comment]
I briefly thought about this (without taking into consideration all the implications) while mistakenly entering data in the wrong cell and had to close the database without saving and open it again, instead of a quick <kbd>cmd</kbd>+<kbd>z</kbd>. We could wait until more people ask for this if we want to support it partially as @MKleusberg said.

**Comment by rik130** [comment]
As I've just discovered myself. the lack of an UNDO button/function can basically result in your work being ruined if you suffer a fat finger problem when copying & pasting other cells/rows.  You either have a choice of 

1. losing hours of work.
2. losing hours of work.

because your only options are to exit out of the database without saving or to somehow figure out what all the data was you've just overwritten and retype it all.
