### ISSUE TITLE
Drag&drop db file for opening db file isn't working

### ISSUE THREAD

**Issue by t3chno** [sqlitebrowser/sqlitebrowser#862]
Hi, I was working with version 3.7.0 but now it's not working on MacOs.. Just FYI.

**Comment by justinclift** [comment]
Interesting.  Thanks for mentioning it.  Will investigate later on and see whats causing the problem. :smile:

**Comment by SourceTrigger** [comment]
That's the same problem as here: #1175
Fixed with #1236

**Comment by justinclift** [comment]
@t3chno Thanks to @SourceTrigger this should be fixed now. :smile:

Would you have the time and interest to download the automatic nightly build tomorrow, and confirm that this is now working for you?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Closing this due to lack of response, and it really should be fixed now.

@t3chno If you get a chance to try this out, and it's not working for some reason, you're definitely welcome to reopen this so we can investigate. :smile:
