### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by AureliaKain** [sqlitebrowser/sqlitebrowser#864]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment]
Please provide more info. Is this an error message? Does it appear inside DB4S?

I usually get lock errors in my iOS app when I update some rows in DB4S but don't hit save.

**Comment by chrisjlocke** [comment]
Closing as the issue was too vague to diagnose, and no response received.
