### ISSUE TITLE
Hang up in case of cancel while choosing a file 

### ISSUE THREAD

**Issue by pirelaurent** [sqlitebrowser/sqlitebrowser#865]
### Details for the issue

problem  with sqlitebrowser 64 :  in any option to get a file ( db or sql for example ) : once the file explorator of system is open, if you click Cancel, control never come back to sqlitebrowser which stay hanged up . 
problem only on 64 bits version. 32 bits works fine. 

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10_family __ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Oops, that shouldn't happen! 😦 

Which version is this happening with?

**Comment by pirelaurent** [comment]
i download through the main page . Url is  https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.1/DB.Browser.for.SQLite-3.9.1-win64.exe 
https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.1/DB.Browser.for.SQLite-3.9.1-win32.exe works fine

**Comment by pirelaurent** [comment]
New (bad) news : sometimes 32 version also hang up (no return from external file search ) or even crash at startup.
Here are two Windows reports of crashes  this morning . Report.wer are renamed in txt for upload in github.
First is an appCrash report, second is a Critical hang .

[Report.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/575000/Report.txt)
[Report1.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/575003/Report1.txt)

HTH

**Comment by chrisjlocke** [comment]
Cannot replicate this on several Win 10 x64 machines I have at work.  Thats 3.9.1 and the latest nightly.

**Comment by justinclift** [comment]
@pirelaurent Would you have time to try out latest nightly 32 + 64 bit builds, and let us know if they still have this crash problem?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
This seems another 'isolated' x64 issue, similar to a couple of other issues.  Unfortunately, without further help and debugging, these cases can't be replicated and resolved.
I'll close this issue for now, until someone has the time to offer further debugging.
