### ISSUE TITLE
Please give the "Table" drop down more lines

### ISSUE THREAD

**Issue by UweKeim** [sqlitebrowser/sqlitebrowser#867]
Having a lot of tables, it feels very annoying to only have 10 rows in the "Table" drop down list:

![image](https://cloud.githubusercontent.com/assets/415439/20138489/ec89b452-a680-11e6-8711-de8d42d1c206.png)

**My question:**

Could you please make it more lines, like e.g. 20, or even a configuration value so that I can change it by myself?

**Comment by justinclift** [comment]
That makes sense. :smile:

**Comment by MKleusberg** [comment]
The max number of lines is now set to 30. This should improve the usability quite a bit, I hope :) Can you test one of the next nightly builds to check if it's working for you, @UweKeim ? :smiley:

**Comment by justinclift** [comment]
@MKleusberg Should we make it configurable?

**Comment by MKleusberg** [comment]
Nah, it's probably not worth it. I don't think many people would edit that option anyway if we had one. If somebody does complain we can still add it easily :smiley:

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by justinclift** [comment]
@MKleusberg, do you have time to look at #918?

@innermous is blocked on it. 👼

**Comment by UweKeim** [comment]
@MKleusberg I've downloaded [this one](https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-sqlcipher-2017-01-04-win64.exe) from [this page](https://nightlies.sqlitebrowser.org/win64/).

Seems to work as expected. Thank you very much! 😄 

![image](https://cloud.githubusercontent.com/assets/415439/21634637/ec1ca3ea-d258-11e6-846e-8048e91d04fc.png)

**Comment by revolter** [comment]
I downloaded the 04/01/2017 nightly and for me, the dropdown goes fullscreen, even bigger than the window (which I like). Does that 30 limit have effect only on Windows?

**Comment by MKleusberg** [comment]
@revolter No, that should work on all platforms. I've tested this on Linux and it worked, too. :smiley:

@UweKeim Thanks for the quick reply! I'm glad I could help :smiley: Closing this issue then.

**Comment by MKleusberg** [comment]
@revolter Sorry, you're right! That value applies for Windows and some Linux configurations but not for OS X. On OS X it seems to be impossible to manually set the number of max visible items in an easy way. See [here](https://doc.qt.io/qt-5/qcombobox.html#maxVisibleItems-prop):
```
maxVisibleItems : int

This property holds the maximum allowed size on screen of the combo box, measured in items.

By default, this property has a value of 10.

Note: This property is ignored for non-editable comboboxes in styles that returns true for QStyle::SH_ComboBox_Popup such as the Mac style or the Gtk+ Style.
```

**Comment by revolter** [comment]
Good to know. There's no problem for me. As I said, I like that it's showing full height 😄
