### ISSUE TITLE
Error executing query containing comments

### ISSUE THREAD

**Issue by chateb** [sqlitebrowser/sqlitebrowser#868]
### Details for the issue

Some multi-line queries having comments at the end of a line do not work.
For example, this one:

    SELECT
        ID,
        label -- fails
    FROM example;

I get the following message in the lower part of the window:
```
Error executing query: SELECT
	ID,
	shortName -- fails
FROM example;
```
However, this one is OK:

    SELECT
        ID,
        label -- doesn't fail
    FROM example;

Could it be related to the apostrophe?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _7_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
@revolter This sounds like it would be of interest to you, if you have the time? :smile:

**Comment by revolter** [comment]
I remember fixing this (again) after 3.9.1. @chateb, Could you please try out the nightly version?

**Comment by revolter** [comment]
Indeed, the apostrophe "fixes" this, though I have no idea why 😆  I tested it myself on the latest nightly on macOS and the failing query works.

**Comment by chateb** [comment]
Yes, indeed, the nightly version works. Thank you! 👍

**Comment by justinclift** [comment]
Awesome @chateb, thanks for letting us know. 😄
