### ISSUE TITLE
CTRL-S does not save sql files

### ISSUE THREAD

**Issue by RobHowardCoursera** [sqlitebrowser/sqlitebrowser#871]
### Details for the issue

STEPS TO REPRODUCE:

On the tab "Execute SQL", create a new SQL file and save it to your local drive.
Make a change to the document.
Click CTRL-S.
GET: File is not saved.
EXPECT: File to save.

Click "Save" button on toolbar.
GET EXPECTED: File is saved.

REASON: Every windows user in the world expects CTRL-S to save the current file regardless of the application (e.g. Notepad++, etc.). It is built into our fingers. Thank Microsoft for that. CTRL-SHIFT-S often saves all documents.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm, I'm kind of thinking the Ctrl-S behaviour might be getting caught by the overall "Save database" (Write Changes) thing.

But, I'm on a break at the moment (back next week), so won't be looking at this properly until then.

**Comment by chrisjlocke** [comment]
Ctrl+{something} is normally linked to a menu option, so is therefore application-wide.  Alt+{something} is normally linked to a visible button/option, so is screen/dialog-wide.  Mind you, we recently did something similar for Ctrl+R (#759) so could be replicated here.  While on the 'Browse Data' tab, Ctrl+S saves changes, but on the 'Execute SQL' tab, it saves the file...

**Comment by revolter** [comment]
And <kbd>alt</kbd> + <kbd>s</kbd> in `Browse Data` could open up the export table dialog ;)

**Comment by justinclift** [comment]
As a thought, it seems like it'd be pretty strange to have Ctrl+s do things differently on the Execute SQL window.  It's not unusual to run SQL which changes the database (eg update statements), so wanting to "Write changes to disk" (Ctrl+s) after that is fairly normal.

As @revolter points out, it's definitely possible to add further key combinations to open up the various save dialogs though.

**Comment by mgrojo** [comment]
Well, a compromise solution could be to make Ctrl+Shift+S to save everything: database, open SQL files and project.

**Comment by justinclift** [comment]
Good point, something like that would probably work.  Control+Shift+S might be better as a "Save As..." short cut though (it's a fairly standard key sequence for "Save As...").

Hmmm, as an alternative thought... maybe Control+S should save all open .sql files as well as save the main database to disk?

**Comment by mgrojo** [comment]
> Good point, something like that would probably work. Control+Shift+S might be better as a "Save As..." short cut though (it's a fairly standard key sequence for "Save As...").

I don't know too much keyboard shortcuts besides the basic ones, but a Google search seems to point to F12 instead. At least for MS Office. LibreOffice does use Ctrl+Shift+S.

> Hmmm, as an alternative thought... maybe Ctrl+S should save everything instead, regardless of what tab is open?

That would make sense, but it might break current user customs. The current behaviour is a bit peculiar nevertheless. There are SQL buffers not attached to files and it is clear that those are volatile. But tabs opened from files shouldn't be volatile and we should ask about saving them on program exit ( #938). Saving the session as project, doesn't help about it (#1386). Additionally, we change tabs linked to files to not being linked when we save the session as a project. Maybe we should still consider them linked files and still save them on their files on project saving or load them from their files on project loading, just as we do with the database file.

Maybe we should have a think about saving behaviour in general after the 3.11 release.

**Comment by justinclift** [comment]
> Maybe we should have a think about saving behaviour in general after the 3.11 release.

Good point.  There's no reason this issue has to be done urgently. :smile:

**Comment by mgrojo** [comment]
Interesting site for deciding about what shortcuts to use for what action:
https://defkey.com/what-means/ctrl-shift-s
https://defkey.com/what-means/f12
https://defkey.com/search?irq=save+all
https://defkey.com/search?irq=save+as

**Comment by justinclift** [comment]
Useful website.  That's a good find @mgrojo. :smile:

**Comment by embassy** [comment]
CTRL + s caused me to lose a lot of SQL statements I had written

**Comment by justinclift** [comment]
@embassy That's a bit confusing.  Can you provide more information? :smile:

**Comment by embassy** [comment]
I'm used to Ctrl + S save, but your program doesn't support it @justinclift

**Comment by justinclift** [comment]
Ahhh.  Yeah, we still haven't figured out which direction to take for this, shortcut wise.

The different keyboard layouts across OS's doesn't help either. :frowning:

**Comment by mgrojo** [comment]
Can this be closed? In [version 3.12.0](https://sqlitebrowser.org/blog/version-3-12-0-released/), Ctrl+S saves the current database and Ctrl+shift+S saves all: the project (if open, the SQL files otherwise) and the database.

**Comment by justinclift** [comment]
Yeah, lets close this. :smile:
