### ISSUE TITLE
Browse Data should remember the last Table/View

### ISSUE THREAD

**Issue by aneroid** [sqlitebrowser/sqlitebrowser#873]
### Details for the issue

Clicking on the 'Browse Data' tab always loads the first table or view alphabetically. After selecting the correct table, going to another tab and then coming back to 'Browse Data', it's the first table again. And if it's a big one, it takes time loading data you _weren't_ trying to browse.

So Feature request: 'Browse Data' should remember the last table/view you were on before having switched to another tab. (For that session.)

I'd consider this a bug - not remembering the last table/view in the Data Browser - but if it was never planned/intended, then it's a feature request.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _7_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Yes, this is a known issue (see #849)
From memory this was fixed shortly after the 3.9.1 release.
Would you be ok to try out one of the nightly builds?

https://nightlies.sqlitebrowser.org

**Comment by revolter** [comment]
The last nightly works correctly for me.

**Comment by aneroid** [comment]
Re-tried and works, with the last nightly (2016-11-18, win64, v3.9.99).
Thanks.
