### ISSUE TITLE
Unable to Import From Access .txt Export

### ISSUE THREAD

**Issue by JamesJoey** [sqlitebrowser/sqlitebrowser#874]
sqlitebrowser version 3.9.1

When I try to import a .txt that I exported using Access 2010 I get the following error:
**Error importing data: Error in statement #1: near "33". Syntax error. Aborted execution.**

James

**Comment by chrisjlocke** [comment]
What's line 1 in the file, or could you email it to me?

**Comment by JamesJoey** [comment]
Line 1 is the first row and "33" is the record ID.

**Comment by chrisjlocke** [comment]
Just to confirm, did you import this using the 'File | Import | Table from SQL File' ?
If so, did you then get a screen showing a sample of your data?  eg:

![image](https://cloud.githubusercontent.com/assets/7872218/20458091/9b568d52-ae92-11e6-8bb4-5da743b65cf0.png)

**Comment by JamesJoey** [comment]
That was it.
I needed to create a new db with the fields to import to.

Thanks much,
James

**Comment by chrisjlocke** [comment]
\o/

No problem.  Guess its not that intuitive if you're used to other systems.  Something else to add to the wiki... ;)  Glad you got it in the end.  :)
