### ISSUE TITLE
Unable to edit results in Execute SQL tab

### ISSUE THREAD

**Issue by Sojourneyman** [sqlitebrowser/sqlitebrowser#876]
### Details for the issue

When in the Execute SQL tab, I am unable to edit any of the results returned from a SQL query.

Steps to duplicate:
1) Go to Execute SQL tab
2) Run a query ( e.g. **SELECT * FROM _[TableName]_** )
3) Try to edit any cell from results

Double-clicking on a cell takes the keyboard cursor to the "Edit Database Cell" view, but I am not able to make any changes.  The "Apply" button is greyed out and not clickable.

Is this by design? Or is there there an option I need to enable to make cells editable in the Execute SQL tab?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version: 7 (64-bit)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
This isn't a bug per se ... It's by design. There are no in-built record editing features, but you can edit records using more SQL statements... Or using the 'browse data' tab...

**Comment by justinclift** [comment]
@Sojourneyman As Chris mentioned, yeah the output results from a SQL command aren't really editable.  If you're wanting to select specific rows to then edit (in a simple way), try out the filters in the Browse Data tab.  That lets you pick a subset of a table, and then edit specific rows.

**Comment by RedShift1** [comment]
This should be re-opened. The apply button is grayed out "Browse Data" tab.

**Comment by chrisjlocke** [comment]
The apply button is greyed out until the cell contents have changed.  Then the apply button is enabled.

**Comment by RedShift1** [comment]
![sqlite_bug](https://user-images.githubusercontent.com/3098010/29208249-9807bde8-7e89-11e7-92ad-2417564e4a6d.gif)

Have this happening multiple times. When I play around in the window doing various things, suddenly the "Apply" button will not be grayed out anymore.

Version: 3.9.1 64 bit
OS: Windows 10 build 15063.540

**Comment by justinclift** [comment]
Ahhhh.  Would you be ok to try the recent 3.10.0-beta?  We've made a lot of tweaks and changes since the 3.9.1 release last year, and there's a pretty good chance was fixed over the course of time. :smile:

**Comment by RedShift1** [comment]
See my updated reply

**Comment by justinclift** [comment]
Ahhh, no worries.

For the backporting, it would make sense if we intended to release a 3.9.2 or similar.  3.10.0-beta1 has turned out to be pretty good (no major bugs reported), so we're just mainly waiting on an external project (SQLCipher) to do a release before we release 3.10.0 properly.

That'll be what our 3.10.0-beta1 currently is, plus updated translations, and some changes to the way communication is done to the remote (optional) dbhub.io server.
