### ISSUE TITLE
Create table generate table that cannot be modified

### ISSUE THREAD

**Issue by FreudGit** [sqlitebrowser/sqlitebrowser#877]
### Details for the issue

Using this sql:
CREATE TABLE CONTACT (ID integer PRIMARY KEY AUTOINCREMENT,NAME varchar NOT NULL,PHONE varchar,ADDRESS varchar,NOTE text,EMERGENCY boolean NOT NULL DEFAULT NO,USERID integer NOT NULL DEFAULT 0, EMAIL varchar)  create the table, but cannot modify on edit the table!

<img width="958" alt="screen shot 2016-11-21 at 8 23 18 pm" src="https://cloud.githubusercontent.com/assets/1793380/20507391/69f65804-b028-11e6-989e-3f7a3906a0ab.png">
:

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Its the default values which has thrown it out.  I created the SQL, but when I went to modify the table, DB4S thought it was empty.  Remove the 'default' option, and it works OK.
Referencing #741 as its an issue with the parser...

**Comment by FreudGit** [comment]
Thanks.

Also, if I go to the editor, I cannot add a new row.

**Comment by chrisjlocke** [comment]
Can you give steps you're doing so I can try to replicate this...

**Comment by MKleusberg** [comment]
Thanks for reporting this, @FreudGit! You've stumbled upon a nice corner case there. This happens when using an unquoted default value that's a keyword at the same time. In your case that's the ```DEFAULT NO``` part of the ```EMERGENCY``` column. I think this should be fixed by the latest commit. Can you try tomorrow's nightly build to check if it's working for you as well? :smiley:

**Comment by MKleusberg** [comment]
Did you have a chance to test this yet, @FreudGit? :smiley:

**Comment by justinclift** [comment]
@FreudGit Would you be ok to try out latest nightly build, and let us know if it's fixed for you?  In theory, it should have been fixed a while back. :smile:

**Comment by FreudGit** [comment]
Can you please remind me how to get the last nightly? ?

**Comment by justinclift** [comment]
Oops, sorry I should have mentioned it.  The latest nightly builds are here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Closing due to lack of response. 😦

**Comment by justinclift** [comment]
@FreudGit If/when you see this, we just release a new major version (3.10.0) which has the fix for this in it. :smile:
