### ISSUE TITLE
Background Colors

### ISSUE THREAD

**Issue by highPlainsSailor** [sqlitebrowser/sqlitebrowser#880]
### Details for the issue

The preferences do not seem to update in the data browser section, text colors.  They revert to black on black after closing the app - thanks in advance.

Thanks for coming here to report an issue. :)

Please describe it in this section, fill out the correct check boxes
below with an "x", then click the "Submit new issue" button at the bottom

-->

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:10.12.1 )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Heya, this has been reported a few times already (though not yet fixed).

Probably best to keep an eye on #737 for now. :smile:

**Comment by highPlainsSailor** [comment]
Great - thanks!
