### ISSUE TITLE
Updating on windows still opens old version

### ISSUE THREAD

**Issue by XplittR** [sqlitebrowser/sqlitebrowser#882]
### Details for the issue

When updating from 3.9.0 to 3.9.1 (x64 version), using the binaries, opening "DB Browser for SQLite" from the start menu opens the newly installed 3.9.1 version, but double-clicking a ".sqlite" file still opens the old 3.9.0 version.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( 10 version: Pro, 64 bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [x] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  In theory, the installer for 3.9.1 is supposed to remove the previous version.  Sounds like that didn't happen.

Aside from that, the ".sqlite" file association isn't something the installer changes (yet).  It's a known issue for Windows, and ideally we'll have that fixed with the next release.

For now you'll need to change it manually (sorry).  Hopefully the info here helps: https://github.com/sqlitebrowser/sqlitebrowser/issues/279#issuecomment-242426297

**Comment by justinclift** [comment]
@chrisjlocke Also make a screencast showing the process, if that's useful too. :smile:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

**Comment by XplittR** [comment]
When running the binary for installing 3.9.1 I was prompted that a previous version was installed, and had to be uninstalled first, and so it did. After install, this is now my folder in program files, if that may be helpful (note the folder of 3.9.0):

![image](https://cloud.githubusercontent.com/assets/1478147/20620520/68ba0b96-b2fa-11e6-8bb6-7d3338e98630.png)

**Comment by justinclift** [comment]
Ahhh yeah, that's definitely a left over 3.9.0 folder. 😦 

Are there files inside the "3.9.0" folder, or is that folder empty?

**Comment by XplittR** [comment]
```
Folder PATH listing
Volume serial number is 0000008A 688F:D639
C:.
|   DB Browser for SQLite.exe
|   libeay32.dll
|   Qt5Core.dll
|   Qt5Gui.dll
|   Qt5Network.dll
|   Qt5PrintSupport.dll
|   Qt5Widgets.dll
|   sqlcipher.dll
|   ssleay32.dll
|   tree.txt
|   Uninstall.exe
|   
+---3.9.0
|   |   Uninstall.exe
|   |   
|   +---bin
|   |   |   DB Browser for SQLite.exe
|   |   |   libeay32.dll
|   |   |   Qt5Core.dll
|   |   |   Qt5Gui.dll
|   |   |   Qt5Network.dll
|   |   |   Qt5PrintSupport.dll
|   |   |   Qt5Widgets.dll
|   |   |   sqlcipher.dll
|   |   |   ssleay32.dll
|   |   |   
|   |   \---platforms
|   |           qwindows.dll
|   |           
|   \---tmp
|           vcredist_x64.exe
|           
+---platforms
|       qwindows.dll
|       
\---redist
        vcredist_x64.exe
```

**Comment by justinclift** [comment]
Ouch.  That 3.9.0 uninstaller **really** didn't work. 😦 

If you manually run the `Uninstall.exe` in the "3.9.0" folder, does that remove the older version?

**Comment by XplittR** [comment]
Yes. it deleted the files and folders related to 3.9.0, and the shortcuts from the Start Menu (according to the log)

**Comment by XplittR** [comment]
By the way, the Windows File Association-wiki you linked seems to be outdated for Windows 10 / the current version of DbBrowser.

The Reg-key is located at `HKEY_CLASSES_ROOT\Applications\sqlite_auto_file\shell\open\command` and there exists a key (REG_SZ) with name `(Default)` with the value of `"C:\Program Files\DB Browser for SQLite\3.9.0\bin\DB Browser for SQLite.exe" "%1"` (which i will now update)

**Comment by justinclift** [comment]
Ahhh cool. :smile:

Err... any interest in updating that wiki entry with the correct info for Win10?

(I don't have Win10 personally, so it's not something I can easily do)

**Comment by justinclift** [comment]
@XplittR Thanks for updating the wiki page, that kind of thing really does help. :smile:

**Comment by justinclift** [comment]
@XplittR We're ok to close this issue aren't we?

**Comment by justinclift** [comment]
Closing this, as there's nothing to really do at the moment. :smile:
