### ISSUE TITLE
Style Error of Apply Button in Mac

### ISSUE THREAD

**Issue by mayaa6** [sqlitebrowser/sqlitebrowser#883]
### Details for the issue

The apply button's style goes wrong.

![snip20161126_1](https://cloud.githubusercontent.com/assets/3221154/20641182/478525da-b42d-11e6-922e-95e5249e1dbb.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hmmm... looking at the screenshot, I can't tell what's wrong.

Give us a hint? :smile:

**Comment by mayaa6** [comment]
@justinclift 

Should the font color of apply button be white, like the second image

![snip20161129_4](https://cloud.githubusercontent.com/assets/3221154/20711820/846fc986-b67c-11e6-825d-64e387395549.png)

![snip20161129_3](https://cloud.githubusercontent.com/assets/3221154/20711759/402984ce-b67c-11e6-9c1e-f2591319b191.png)

**Comment by MKleusberg** [comment]
Is this still an issue? Maybe it has changed with some Qt update :smile:

**Comment by MKleusberg** [comment]
Closing this because it looks like an issue in Qt and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
