### ISSUE TITLE
cannot open database when using Wayland

### ISSUE THREAD

**Issue by fedelibre** [sqlitebrowser/sqlitebrowser#885]
When I try to open a database, sqlitebrowser gets a segfault:

```
(sqlitebrowser:10884): Gdk-WARNING **: gdkwindow-x11.c:5554 drawable is not a native X11 window
Segmentation fault (core dump creato)
```

This happens on Fedora 25 with Wayland.
sqlitebrowser version 3.9.1.

**Comment by fedelibre** [comment]
I've just closed the session, restarted with xorg and everything works fine.
Can you please fix this problem with Wayland?
I guess that this might help:
https://bugzilla.gnome.org/show_bug.cgi?id=758026

Thanks

**Comment by justinclift** [comment]
Interesting.  We're using Qt, so I don't *think* we have any X11 specific code.

Do other Qt apps work for you under Wayland?

**Comment by fedelibre** [comment]
Yes, other Qt apps work fine  under Wayland, e.g. Frescobaldi (lilypond editor, hosted here in github).
Let me know if I can do other tests.

**Comment by fedelibre** [comment]
Sorry, actually I wrote without double-checking: Frescobaldi used to work fine, but now I cannot open a file when using Wayland. I get the same error.
I recently upgraded the system from Fedora 24 to Fedora 25.

**Comment by justinclift** [comment]
Ahhh, that's making more sense to me now then.

This sounds like a problem with the Fedora (25) Wayland package, or perhaps the Fedora 25 Qt package (not being build correctly for Wayland).

Are you ok to open a bug about this on https://bugzilla.redhat.com?

**Comment by fedelibre** [comment]
I've found the solution [here](https://bugzilla.redhat.com/show_bug.cgi?id=1377616#c11); I installed qgnomeplatform and it's not crashing anymore.

**Comment by justinclift** [comment]
Awesome. :smile:
