### ISSUE TITLE
Cannot Open Encrypted Database

### ISSUE THREAD

**Issue by dragonstar0828** [sqlitebrowser/sqlitebrowser#886]
### Details for the issue

I'm trying to open an encrypted SqLite db and when I enter the key and click ok the dialog just blinks and provides no feedback as to what the issue is.
 
The db is encrypted using leCast128 as the algorithm if that helps.
 
I know the key is correct as the app I'me developing open the db without any issues.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  When you say the database is encrypted using "leCast128", that sounds like it's wasn't done using SQLCipher.

We only support SQLCipher encryption at present.  Adding support for other things can be done, but it would need someone with the time & interest in it to update the code & make a Pull Request with the changes.

**Comment by dragonstar0828** [comment]
I'm using the UniDac product from DevArt, they have an enumerated type of the encryption algorithms they support...
 
TCREncryptionAlgorithm = (eaTripleDES, eaBlowfish, eaAES128, eaAES192, eaAES256, eaCast128, eaRC4);
 
... this has been in my app long enough I don't recall why I selected Cast128, and I don't know what technology they're using under the hood to implement encrypting and decrypting.
 
So the quest for an SqLite db tool continues.  sigh...
 
 
drc  :)

**Comment by justinclift** [comment]
No worries at all, good luck with it. :smile:

**Comment by chrisjlocke** [comment]
Looking in your list, you have eaAES256. If you could unencrypt your database and encrypt using this method, it might be compatible with SQL cipher. 256bit AES is quite secure and fast, so is worth using.

**Comment by dragonstar0828** [comment]
I found an unencrypted copy I can use with your product to make a few minor changes.
 
As for changing the encryption method, I have an installed customer base and don't want to have to deal with some db's in the field are encrypted one way and and some a different way.
