### ISSUE TITLE
Deferred foreign keys not working

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#887]
### Details for the issue

As pointed out in #770, [deferred foreign keys](https://www.sqlite.org/foreignkeys.html#fk_deferred) are not working. Having this database:

```
CREATE TABLE one ( pk INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT );
INSERT INTO "one" VALUES(1,'test');
CREATE TABLE two( pk INTEGER PRIMARY KEY AUTOINCREMENT, fk INTEGER NOT NULL, FOREIGN KEY( fk ) REFERENCES one(pk) DEFERRABLE INITIALLY DEFERRED );
```

and entering a row in table `two` that violates the FK, it now throws an error instead of handling it correctly.

If this is not actually possible, please mark it as won't fix and close this.

cc @justinclift, @MKleusberg

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Have you tried it with the latest version from master, too? I have changed something in there to handle deferred foreign keys at least a little better. With the latest version I can enter anything in table ```two```, even when it violates the foreign key. No error messages or anything are shown. Only when clicking the Write Changes button, an error message is thrown at you:
![screenshot_20161228_141208](https://cloud.githubusercontent.com/assets/3153504/21522653/de545132-cd07-11e6-88bf-c1f66aa9f9ee.png)

**Comment by justinclift** [comment]
@revolter Do you have time to try this out on latest master build?

**Comment by mgrojo** [comment]
Closing this, as seems to work correctly and it's pretty old.
