### ISSUE TITLE
use sqlite 3.15.2 in nightly

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#888]
Hi All,

A release was made on the 4th of November for 3.15.1:
https://www.sqlite.org/releaselog/3_15_1.html

Can the nightly updates include 3.15.1 now?

Thanks!

**Comment by jungle-boogie** [comment]
3.15.2 was just released:
https://www.sqlite.org/releaselog/3_15_2.html

**Comment by glawrence** [comment]
I think you have just made your own case for waiting at least a month before taking a new release of SQLite! Hence I would suggest waiting at least a month before using 3.15.2. Just my personal view though.

**Comment by jungle-boogie** [comment]
> Hence I would suggest waiting at least a month before using 3.15.2. Just my personal view though.

Good point! I'll close this now and see what happens over the next 4-5 weeks with sqlite.

**Comment by glawrence** [comment]
Just set yourself a reminder to check in a month's time, maybe 3rd of Jan actually! Then you can reopen this if necessary. Was looking good until 3.15.2 came along to be honest!!
