### ISSUE TITLE
Execute SQL and dark KDE theme

### ISSUE THREAD

**Issue by akhilman** [sqlitebrowser/sqlitebrowser#89]
The input field in a Execute SQL tab with white on dark KDE theme becomes unusable because of it shows white text on white background.
Can you make this field follow system theme?
Screenshot: http://h01.akhil.ru/drop/u6wq

**Comment by voidplayer** [comment]
Im having a similar issue but with the cells  content color
I tried changing all the colors in preferences and none seemed to work

![Uploading Selection_138.png…](screenshot)
