### ISSUE TITLE
Database changes silently discarded if database open in another program

### ISSUE THREAD

**Issue by Kudalufi** [sqlitebrowser/sqlitebrowser#891]
### Details for the issue

If you open a database in DB4S that is also open in another process, then if you make changes to the database and click "Write Changes", the changes are not written to the database.  The journal file goes away and the changes remain in DB4S in memory, but as soon as the database is closed and reopened, the changes are gone.  There is no warning or error displayed.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ 7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for reporting it.  Yeah, we should at least detect that the changes aren't written, and warn the user when it happens.

**Comment by mgrojo** [comment]
@Kudalufi This seems solved long time ago. I always get "database is locked" errors. Would mind confirming it with our [current alpha version](https://github.com/sqlitebrowser/sqlitebrowser/releases) for the next release?

**Comment by chrisjlocke** [comment]
I'll close this, as this appears resolved in our latest builds.

![image](https://user-images.githubusercontent.com/7872218/50824579-e3a25200-132e-11e9-9c14-5f97d3971e32.png)

@Kudalufi - I appreciate its been a while since you opened this issue, but if you still use DB4S, I'd recommend you using the latest nightly/beta and trying again.
