### ISSUE TITLE
CSV-Export without trailing separator

### ISSUE THREAD

**Issue by steda112** [sqlitebrowser/sqlitebrowser#892]
### Details for the issue

When SQL is executed in sqlitebrowser, the resulting table can be exportet to csv.
Generated csv-files are difficult to import into e.g. MS Excel, because for each datarow, the trailing separator is missing. When importing, the last column value of the first datarow is not ending with the desired separating character. The next datarow does not start with a separator, so at this point things get messed up.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ 7__ )
- [ ] Linux: ( _distro:_ __Ubuntu_ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Yeah, that makes sense.

I wonder how everyone else is importing into Excel then, as no-one seems to have mentioned this before.

**Comment by steda112** [comment]
Should have digged deeper before opening this issue, found the corresponding issue-threads too late,sorry. Strange things happen in the Microsoft World: If you open the generated csv by double-clicking and excel opens, everything works well except encoding of german "Umlaute", which is not really a problem. If you try to import the same file from within excel via "import as text", the described problems arise :-)

**Comment by justinclift** [comment]
No worries at all.  It shouldn't be too hard for us to implement this. :smile:

**Comment by MKleusberg** [comment]
I'm not entirely sure I understand you correctly :)

Currently we would be exporting something like this:
```
aaa;bbb;ccc;ddd
eee;fff;ggg;hhh
iii;jjj;kkk;lll
```
And from what I understand you'd expect it to be like this:
```
aaa;bbb;ccc;ddd;
eee;fff;ggg;hhh;
iii;jjj;kkk;lll;
```
Correct?

But that would be a different table from a CSV perspective. It would add an empty column to the right side of the table. Excel should definitely be able to import it without the trailing separator. Maybe it is an issue with line endings? Newer versions of DB4S support setting the line separator and for Excel it needs to be CR+LF. These settings *should* work for Excel with default settings:
![screenshot_20161228_140821](https://cloud.githubusercontent.com/assets/3153504/21522586/2743c3d8-cd07-11e6-8011-a7724d81753b.png)

**Comment by justinclift** [comment]
@steda112 Ping... :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦

**Comment by steda112** [comment]
Dear Justin,

sorry for not responding - to little time, I´m sorry. Thank you very
much for your help and support.

Regards,

Stefan


Am 28.01.2017 um 03:53 schrieb Justin Clift:

**Comment by justinclift** [comment]
You're welcome. :smile:
