### ISSUE TITLE
Link on "edit pragmas" -> User Version is incorrect

### ISSUE THREAD

**Issue by mgrandi** [sqlitebrowser/sqlitebrowser#897]
### Details for the issue

The link on the "edit pragmas' tab for the "User Version" pragma is wrong

Clicking it takes you to `http://www.sqlite.org/pragma.html#pragma_schema_version` when it should take you to `http://www.sqlite.org/pragma.html#pragma_user_version` instead

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ 10.12.1 )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @mgrandi, good catch. :smile:

**Comment by revolter** [comment]
I noticed this too a couple of weeks ago but looks like I forgot to open an issue. I thought I fixed it too :-?

**Comment by MKleusberg** [comment]
I've just pushed a commit which fixes this issue :) Iulian is right by the way: the link is also included in the translation files as well (even though it originally comes from the form file), which I didn't see at first. So there's a second commit now which updates all the translation files to hopefully include the fixed link, too.

@mgrandi Can you test tomorrow's nightly build (or any later one) to check if the bug is fixed in there? :)

**Comment by mgrandi** [comment]
sure , i'll do it tomorrow

**Comment by revolter** [comment]
And I didn't know it's in the `.ui` file too. Then, why is it in the translations files? If it's the same. Shouldn't we remove it from those altogether?

**Comment by mgrandi** [comment]
i downloaded https://nightlies.sqlitebrowser.org/osx/DB%20Browser%20for%20SQLite_20161220.dmg and it seems that all of the links in the edit pragmas tab are not actually clickable anymore...

**Comment by MKleusberg** [comment]
Thanks for reporting back, @mgrandi ! :smiley:
I'm going to close this issue then. If anybody is bothered too much by the way the disabled links look, I think this should be a separate issue and unfortunately a little more thinking :smiley:
