### ISSUE TITLE
Emoji does not render

### ISSUE THREAD

**Issue by dreneral** [sqlitebrowser/sqlitebrowser#898]
### Details for the issue

Emoji (emoticons) do not render, appear as a blank space. Super not crucial, but would be nice.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_10.11.6)
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting thought.  Yeah, can't see why it wouldn't be a nice thing to have. :smile:

**Comment by dreneral** [comment]
👍

**Comment by MKleusberg** [comment]
I think this depends on the font you use. At least it works for me:
![screenshot_20161219_192721](https://cloud.githubusercontent.com/assets/3153504/21324277/59c4cbaa-c621-11e6-925a-b0c0788f9016.png)

Can you check which font you have selected in View -> Preferences, Data Browser -> Font?

**Comment by mgrojo** [comment]
@dreneral this depends probably on the fonts, libraries and the operating system. Have you tried with recent versions?

**Comment by justinclift** [comment]
Closing this due to lack of response.

@dreneral As mentioned above, it's probably a font thing.  If you still can't manage to get it working though (and you're interested in a solution), you're welcome to reopen this so we can continue. :smile:
