### ISSUE TITLE
keep same table open on the "Browse Data" when changing tabs

### ISSUE THREAD

**Issue by animismus** [sqlitebrowser/sqlitebrowser#899]
As the title says. 
I have to keep re selecting the table I'm interested in on the **browse data** tab whenever I change the tab to something else, e.g., **Exectute SQL**

Is there a way to make the program remember?

**Comment by justinclift** [comment]
From memory, this was fixed not long after the 3.9.1 release.

So... if you grab one of the nightly builds from (say) a week after that it should work.  In theory. 😁

**Comment by animismus** [comment]
Indeed that was the case! Thank you for the swift reply!

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by revolter** [comment]
Duplicate of #748.
