### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mvt91** [sqlitebrowser/sqlitebrowser#90]
Hi all,

I did a french translation. Where I can share the file ?
Thanks.

**Comment by justinclift** [comment]
@mvt91 Would you be interested in updating the translation for our next release (in a few weeks)? :smile:

**Comment by mvt91** [comment]
I Justin,

No problem. Please, send me the file.

**Comment by justinclift** [comment]
Cool.  I think I'll need to generate it first, which I don't remember how to do off the top of my head.  I'll look at it tonight. (I really should write down instructions for myself eh? :wink:)

**Comment by mvt91** [comment]
Hi Justin,

You will find the translated file with this mail.
I made a review of the file : sqlb_fr.ts (XML file)

Please, take care... The file is coded with UTF-8. All entities are coded with
this option.
I mean, for example :
l&apos;ouverture
will be, in the file
l'ouverture
The html source data (line 28) has his entites encoded*
style=&quot; font-size:small; text-decoration: underline;
color:#0000ff;&quot;&gt;
will be :
style=" font-size:small; text-decoration: underline; color:#0000ff;">

I got the file from github (sqlitebrowser-master/src/translation

have a good day overseas ;)

Michel

Selon Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment]
Awesome.  Would you be ok to email it to me (justin@postgresql.org)? :smile:

GitHub just drops email attachments. :frowning:
