### ISSUE TITLE
MacOS Field Colors corrupted in preferences file

### ISSUE THREAD

**Issue by ghellquist** [sqlitebrowser/sqlitebrowser#900]
### Details for the issue

All data fields in Browse Data show as black text on black background. The colouring schema is fetched from preferences. The error is repeatable.

When I do this:
1 - change "SQL editor font size" in pane SQL in Preferences
2 - exit program
3 - start program again

I get this error:
- data fields in pane "Browse data" are all shown in black text on black background

It is possible to change colours in Preferences (possible workaround). Once I leave the program and starts again the text is again shown in black on black (i.e. unreadable).

### Useful extra information
Workaround: delete the preferences file com.sqlitebrowser.sqlitebrowser.plist at my local Library/Preferences.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X ] Mac OS: ( _version:_ Sierra___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yeah, this is a known on Sierra.  There is a temporary workaround for now: https://github.com/sqlitebrowser/sqlitebrowser/issues/737#issuecomment-262403564

**Comment by revolter** [comment]
Quick update, this was actually a Qt bug and was fixed be a recent release. The latest nightlies should work ok.
