### ISSUE TITLE
WHERE wildcards working?

### ISSUE THREAD

**Issue by instrumentally** [sqlitebrowser/sqlitebrowser#902]
Does the SQLiteBrowser support [a-z] and _  wildcards? I have been unsuccessful in getting any results from the following queries, despite the face that my table (Keywords) has the word 'hello' in the Keyword field:

SELECT * FROM Keywords WHERE (Keyword LIKE '[h]%' )

SELECT * FROM Keywords WHERE (Keyword LIKE '_ello' )

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
What happens if you leave off the '(' and ')' characters?  eg:

    SELECT * FROM Keywords WHERE Keyword LIKE '[h]%'

**Comment by justinclift** [comment]
I'm unsure about the '[]' characters, but simple '_' and '%' are supposed to work.

Looking quickly on the SQLite site, I'm not seeing the reference documentation for wildcards though, thus my uncertainty about '[]'.

**Comment by justinclift** [comment]
Note - Weirdly, searching the SQLite website for the terms "wildcard" and/or "wildcards" turns up no useful information.  Oops.  Hole in the documentation maybe? 😦

**Comment by instrumentally** [comment]
> but simple '_' and '%' are supposed to work.

The % works fine. I simply can't get the underscore to work. Have you tried creaing a query with _  ?

**Comment by justinclift** [comment]
Yeah, I just tried it out now using this query, which worked:

    SELECT * FROM download_counts WHERE release LIKE '3._';

The database I ran it against is here, if that helps:

&nbsp; &nbsp; https://dev1.dbhub.io/justinclift/DB4S%20download%20stats.sqlite

**Comment by instrumentally** [comment]
When I run the following....

SELECT * FROM download_counts WHERE release LIKE '[3].3';

SELECT * FROM download_counts WHERE release LIKE '%[3].3%';

SELECT * FROM download_counts WHERE release LIKE '[3].%';

SELECT * FROM download_counts WHERE release LIKE '[3]._';

...I get no results.

**Comment by justinclift** [comment]
Just tried those here too, and yeah, it's treating the '[' and ']' as literal characters.  You'll probably need to leave them out.

Out of curiosity, which SQL variant are you used to which includes them? :smile:

**Comment by justinclift** [comment]
Looked into this a bit more.  It turns out [we include a regexp() operator with DB4S](https://github.com/sqlitebrowser/sqlitebrowser/commit/6d1a874f8077b859bee2dd9d4031f242cfa1e807) (I'd forgotten), which should help.

&nbsp; &nbsp; https://sqlite.org/lang_expr.html#regexp

Working examples:

    SELECT * FROM download_counts WHERE release REGEXP '^[3].[1-2]$'
    SELECT * FROM download_counts WHERE release REGEXP '[3]\.[2]$'
    SELECT * FROM download_counts WHERE release REGEXP '[3]\.[2]'

It doesn't execute fast - takes ~1.5+ seconds on my desktop, but it works.

Does that help? :smile:

**Comment by instrumentally** [comment]
The SQLite library I am using does not support RegExp.  See www.devart.com/litedac

**Comment by justinclift** [comment]
Oh well, it was a thought. :smile:

**Comment by MKleusberg** [comment]
But you should still be able to open the same file using DB4S and its SQLite library, I guess. Or am I missing something there? This way you can develop using litedac (having no regexp) and check your data using DB4S and its regexp function.

Other than that I don't see any way of supporting ```[ ]``` wildcards either. We are completely dependent on what SQLite offers us, and for the LIKE operator that's just the ```%``` and ```_``` wildcards but no ```[ ]```.

**Comment by justinclift** [comment]
Closing this, as it doesn't seem like we can do much/anything to add support for [] characters.

@instrumentally You're welcome to reopen this if it turns out I closed it prematurely. 😀
