### ISSUE TITLE
Feature request: refresh button

### ISSUE THREAD

**Issue by yesman85** [sqlitebrowser/sqlitebrowser#905]
I often open een WebSQL database from Chrome to test out a framework or app, which means that it often changes the structure of the database.

But the only way to see those changes is to close the database and to re-open it. It would be great if there was a menu option to reload the complete database.

**Comment by justinclift** [comment]
Hmmm, that sounds familiar... I **think** this might have been done not long ago, as part of #759.

Would you be ok to try a recent nightly build and see if the refresh key (F5, or Ctrl/Cmd+R) works for you?

**Comment by yesman85** [comment]
Yes that seems to do the trick, exactly what I needed!

**Comment by justinclift** [comment]
Awesome. :smile:
