### ISSUE TITLE
Execute SQL error output window should be resizeable

### ISSUE THREAD

**Issue by innermous** [sqlitebrowser/sqlitebrowser#906]
![Execute SQL output](https://cloud.githubusercontent.com/assets/8950786/21297372/0f9ef48c-c587-11e6-867f-cc4f0847b8eb.png)

Output widget can't be resized. This is stupid, because it can be annoying for user if output is large.

**Comment by justinclift** [comment]
Completely agree, it can be pretty annoying sometimes.

**Comment by MKleusberg** [comment]
Should be fixed now :)
