### ISSUE TITLE
Unable to create table with constraint using gui

### ISSUE THREAD

**Issue by polaris197** [sqlitebrowser/sqlitebrowser#911]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
I you have a few minutes, would you be ok to try this with any of our recent nightly builds?

We've added a few bits and pieces for better constraint support since the v3.9.1 release, though they're not yet extremely well tested.  Feedback would be useful. :smile:

(download locations for the nightly builds are listed on the front page of this repo, if that helps)

**Comment by MKleusberg** [comment]
What sort of constraint do you need? In the Create Table dialog we have fields for NOT NULL, unique, check, and foreign key. But if any of this isn't working as expected or if there is anything missing that you need just give us a quick example of what you'd like to be able to create :)

**Comment by innermous** [comment]
Foreign key requires more user friendly widget, I think.
Maybe I'll get around that soon.

**Comment by justinclift** [comment]
@polaris197 ping?

**Comment by MKleusberg** [comment]
@innermous I fully agree :)

**Comment by chrisjlocke** [comment]
Wondering if this was linked to #872, where the primary key can't be set... ?  Wondering if the parser was broken... ?  (just thinking out loud...)

**Comment by innermous** [comment]
Parser is alright.
Martin added some refactoring that caused broken primary keys.

**Comment by justinclift** [comment]
Closing this due to lack of response. ☹️
