### ISSUE TITLE
Bugged pagination

### ISSUE THREAD

**Issue by innermous** [sqlitebrowser/sqlitebrowser#912]
![2](https://cloud.githubusercontent.com/assets/8950786/21457487/4ed2d9e8-c938-11e6-86c8-308432fca305.png)

**Comment by justinclift** [comment]
Cool, I think @MarqueIV mentioned this bug annoying him a few times too.  Good that it's finally fixed. :smile:

**Comment by MarqueIV** [comment]
Woot!  :)
