### ISSUE TITLE
No drop down menu for linux

### ISSUE THREAD

**Issue by JonathanJohann** [sqlitebrowser/sqlitebrowser#914]
For linux there is no drop down menu? A bit confused, this means I can't import csv files to the database. Am I missing something?

**Comment by justinclift** [comment]
Hmm, there's supposed to be.

Which Linux version are you using, and which version of DB4S?

**Comment by JonathanJohann** [comment]
![dbbrowser](https://cloud.githubusercontent.com/assets/17105146/21472528/3f4248f8-caad-11e6-929a-c5bb0ac75c73.png)

I'm using Ubuntu 16.04 and I believe I downloaded the most recent version.

**Comment by justinclift** [comment]
Ouch, something isn't right then. 😦 

@deepsidhu1313, any ideas?  You're familiar with the package on Linux, so hoping something obvious springs to mind. :smile:

**Comment by deepsidhu1313** [comment]
I will check, and let u guys know.

Thanks for notifying.

**Comment by innermous** [comment]
Maybe [this](http://askubuntu.com/questions/762137/applications-menu-missing-from-menu-bar) would help.

**Comment by justinclift** [comment]
@JonathanJohann How did you go with this? :smile:

**Comment by JonathanJohann** [comment]
![no_change](https://cloud.githubusercontent.com/assets/17105146/21533102/3584cafa-cd25-11e6-9720-45857c9d6db2.png)

I didn't really see any change

**Comment by justinclift** [comment]
Yep, that's definitely not showing the menu bar.

Do any of the menu's show if you try triggering them via the keyboard?  eg Alt+f for the file menu?

**Comment by JonathanJohann** [comment]
Ohhh okay, I see what's going on. For some reason, I have to drag my clicker over the top bar (with the power button, etc) to see the drop down options. So I'm not missing the drop down but for some reason I can't read in csv's as tables now.

**Comment by justinclift** [comment]
Cool. :smile:

Just to confirm, you're able to get the CSV import dialog happening now yeah?

**Comment by deepsidhu1313** [comment]
@JonathanJohann  Check this link http://arstechnica.com/information-technology/2014/02/ubuntu-desktop-moving-application-menus-back-into-application-windows/. May be this will help.

**Comment by justinclift** [comment]
Closing this now as it **seems** like it's fixed.

If it turns out not to be, you're welcome to reopen this @JonathanJohann. :smile:
