### ISSUE TITLE
Graphics Card Problem

### ISSUE THREAD

**Issue by mextedol** [sqlitebrowser/sqlitebrowser#916]
Everytime I try to launch something that uses/shows something about my graphics card, it crashes. 
Problem Event Name: APPCRASH. 
![img_4375](https://cloud.githubusercontent.com/assets/24782593/21487261/b23241c8-cb8a-11e6-9649-14d699e02c43.JPG)
Fault Module Name: atiumd64.dll. Exception Code: c000001d. Exception Offset: 000000000013db71.

- My computer is screwed
- My graphics card is broken
- Atiumd64.dll is failing

Reply with your answer.

**Comment by justinclift** [comment]
Does this help?  https://github.com/sqlitebrowser/sqlitebrowser/issues/395#issuecomment-269245184

**Comment by justinclift** [comment]
Guessing you've also tried the basic things like looking for different (eg newer or older) ATI graphics drivers?

**Comment by mextedol** [comment]
Not exactly. The fault module name is different and so as the Exception offset. And it also crashes most java programs including Minecraft, Java Settings, etc.

**Comment by mextedol** [comment]
Sorry I was replying to the earlier comment. Anyways the thing is my graphics card settings is even crashing.

**Comment by mextedol** [comment]
I upgraded my graphics card drivers and now I guess it's failing at something.

**Comment by mextedol** [comment]
I got steam on there fine. I tried running a game and it loaded perfectly.

**Comment by justinclift** [comment]
k, I'd be suspecting something is weird with the graphics card drivers themselves, so that'd be the first thing I'd try changing around if you haven't already.

If that's difficult to do, try and just outright remove them from Add/Remove programs.  In theory (!) Windows should then use either a basic non-accelerated driver (but still work).  That should then be stable enough to try installing graphics drivers again.

**Comment by justinclift** [comment]
k.  It sounds like the 3D component of your graphics card drivers is fine, but something is messed up with some other component of them. Maybe 2d acceleration related or something.  They don't just do 3d. :wink:

**Comment by justinclift** [comment]
Out of curiosity, which graphics card are you using?

**Comment by mextedol** [comment]
The problem is java and graphics card things are crashing. Steam is running fine. I tried running 3D and 2d steam games. Whatever my graphics card is doing, it's something nobody has heard about because I've been searching everywhere and nothing was related to my problem.
My graphics card is a Radeon RX 480 GamingX. I have an AMD processor.

**Comment by mextedol** [comment]
My AMD processor is a 6-core.

**Comment by justinclift** [comment]
Hmmm, is a specific brand of Radeon?  eg MSI (etc)

**Comment by mextedol** [comment]
Yes it's an msi.

**Comment by justinclift** [comment]
k.  Some of the graphics card manufacturers release utilities just for their brand of graphics card.  eg for overclocking, doing updates, monitoring temperature, (etc)

Do you have the MSI one of that installed?

**Comment by mextedol** [comment]
My computer is a custom built gaming pc. Windows works like a charm.

**Comment by mextedol** [comment]
Yes, I went to msi.com and downloaded the same graphics card drivers I had. (Updated drivers for the same card I have)

**Comment by mextedol** [comment]
Now I can't run java or some programs.

**Comment by justinclift** [comment]
That's nice, but not what I asked. 😁 

I'm asking because people often load the manufacturer add-on utilities (not graphics drivers) without knowing better.  Those utilities are very often a complete pile of steaming dog turd.  eg source of problems.

I'm trying trying to think of potential things that could be the cause.

**Comment by mextedol** [comment]
so what's with the atiumd64.dll?

**Comment by justinclift** [comment]
Well, atiumd64.dll is one of the files provided by the ATI graphics card drivers.  It sounds like it's having weird issues interacting with something.

If you're not able to narrow down the problem more using the utilities pointed out in https://github.com/sqlitebrowser/sqlitebrowser/issues/395#issuecomment-269245184 then you'll problem just need to try different ATI drivers out in the hope one of them works.

**Comment by mextedol** [comment]
Thanks, I'll try that, if it works I'll let you know.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by mextedol** [comment]
But there's one thing I gotta say: there are 3 atiumd64 on my pc.

**Comment by justinclift** [comment]
Yeah, I'm not sure if that's good or bad. :wink:

**Comment by mextedol** [comment]
Ummm

**Comment by mextedol** [comment]
My computer was on a black screen for a second. It's not now

**Comment by justinclift** [comment]
Hmmm, you might need to get someone (eg a competent IT shop) to take a look at it.  It's pretty hard to diagnose this stuff over an internet comment style conversation. :wink:

**Comment by mextedol** [comment]
Never mind it works

**Comment by justinclift** [comment]
So, all fixed then?

**Comment by mextedol** [comment]
No I'm talking about the black screen

**Comment by justinclift** [comment]
Oh well.  Um, good luck with it? :smile:

**Comment by mextedol** [comment]
Ugh these drivers take forever to download x.x

**Comment by mextedol** [comment]
Imma just go screw around in mcpe

**Comment by mextedol** [comment]
It's stuck at 66%

**Comment by mextedol** [comment]
Maybe it wants to say three sixes (devil number) but can't replace the %

**Comment by mextedol** [comment]
**still at 66%**

**Comment by innermous** [comment]
Nice wall of text in notifications btw.

**Comment by mextedol** [comment]
Who are you

**Comment by mextedol** [comment]
Anyways it's not fixed

**Comment by mextedol** [comment]
Imma ingnore innermous if he's not gonna help.

**Comment by justinclift** [comment]
Just locked this.  We've put enough time into this, and it's not really related to DB4S at all.
