### ISSUE TITLE
Crashing on opening password protected DB

### ISSUE THREAD

**Issue by CarlCDHPIX** [sqlitebrowser/sqlitebrowser#919]
### Details for the issue

If I changepassword via vb.net and open it in code, works fine.
If I try and open the password protected DB in sqlitebrowser, it asks for the password and other setting (pagesize) I set that, put in the password (a 30 hex-character password) - it crashes.
I tried the nightly build (3rd Jan 2017 version) and now it says "invalid file format" and does not ask for a password or pagesize value.

If I then changepassword(string.empty) - i can then open up the unprotected sqlite db in sqlitebrowser without an issue. Just cannot open a password protect version.

#### I'm opening this issue because:

- [X ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X ] Windows: ( _version:_10 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [X ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by CarlCDHPIX** [comment]
If I changepassword via vb.net and open it in code, works fine.
If I try and open the password protected DB in sqlitebrowser, it asks for the password and other setting (pagesize) I set that, put in the password (a 30 hex-character password) - it crashes.
I tried the nightly build (3rd Jan 2017 version) and now it says "invalid file format" and does not ask for a password or pagesize value.

If I then changepassword(string.empty) - i can then open up the unprotected sqlite db in sqlitebrowser without an issue. Just cannot open a password protect version.

**Comment by justinclift** [comment]
Interesting.  Two thoughts spring to mind right away:

* I'm not sure that the VB.net encryption layer you're trying to use is based on SQLCipher.  We use SQLCipher to provide the SQLite encryption, which is *probably* different and not compatible.  Note, I'm not sure about this. :smile:
* For the crashing, it's definitely not supposed to crash when it can't open the file.  Ouch.

Kind of wondering if the vb.net encryped database is somehow "close enough" to a SQLite file to get past the initial "open the database" check, but is then barfing when our SQLCipher layer hits it.  Not sure.  I suspect this is going to take some debugging effort with some dummy encrypted data to trace throught the opening and see what's happening.

Is there any chance you can whip up a small dummy database which also crashes, so we can see if it crashes for us too?

**Comment by CarlCDHPIX** [comment]
So, I am using 3.9.99 nightly build ( which says invalid file form) because the 3.9.1 would just crash (closing down the app).

The help about menu in sqlite browser is saying:
Version 3.9.99
Qt version 5.7.0
SQLite version 3.15.0

I am not using any encryption on the database at all - just using the standard password protection built into sqlite, in the case of vb.net, i am issuing a changepassword command to perform this.

attached zip file has two databases, one is an empty (no tables) database and the other has a password of "a password" set against it.  I can confirm that if I open it up with sqlite browser it comes back with "invalid file format" and if i reset the password to string.empty, it removes password protection and the database is fine, so I know the database is not getting corrupt.

Thanks! A Quick question about licensing with SQLCipher - am I able to use its encryption abilities in my application as I want to release it as a commercial product (shareware) and would really like to have the data encrypted - Im not too good at reading licenses, its like reading a contract and it completes loses me :S

[dbs.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/682145/dbs.zip)

**Comment by justinclift** [comment]
Hmmm, when you say "standard password protection built into SQLite", that confuses me. :smile:

Er... SQLite doesn't have any password protection built into it.  (Thus our use of SQLCipher)

Maybe it's a new thing, just recently added?

**Comment by chrisjlocke** [comment]
> Hmmm, when you say "standard password protection built into SQLite", that confuses me. 

The wrapper of sqlite for .net (commonly refered to as system.data.sqlite.dll) has encryption, but its a weird legacy implimentation.  Certainly not compatible with sqlCipher.

sqlCipher do do a .net flavour which is (obviously) compatible, but you have to pay $$$ for that.
https://www.zetetic.net/sqlcipher/sqlcipher-ado/

**Comment by CarlCDHPIX** [comment]
Ah right. Ok. Here's some info I used to do the password - it looks like the .NET components use RSA to encrypt it with a password:

You can password protect SQLite3 DB. For the first time before doing any operations, set password as follows.

SQLiteConnection conn = new SQLiteConnection("Data Source=MyDatabase.sqlite;Version=3;");
conn.SetPassword("password");
conn.open();
then next time you can access it like

conn = new SQLiteConnection("Data Source=MyDatabase.sqlite;Version=3;Password=password;");
conn.Open();
**This wont allow any GUI editor to view your data. Some editors can decrypt the DB if you provide the password. The algorithm used is RSA.**

Later if you wish to change the password, use

conn.ChangePassword("new_password");
To reset or remove password, use

conn.ChangePassword(String.Empty);

I guess I will probably have to either
(1) use unprotected DB until I do a release (as it works fine through VS2015)
or
(2) wait for a possible update as this will affect all .NET users who use sqlite browser.

I'll stick with number 1 and occasionally check it with (2) on builds in case its something that is in the pipework (or has been broken). Im assuming at one point it did work, Sqlite is a great desktop database (much better than access mdb's).

Thanks for your help anyway - at least i have learned something more about Sqlite today :)

**Comment by justinclift** [comment]
Thanks @chrisjlocke. :smile:

@CarlCDHPIX No worries at all.  I'll close this for now, as I don't think there's much use in leaving it open at the moment.  We're kind of overwhelmed with the number of issues at the moment right now anyway. :wink:

**Comment by chrisjlocke** [comment]
Appreciate this is closed, but @CarlCDHPIX , which .NET component were you using?

**Comment by justinclift** [comment]
@chrisjlocke Are you still interested in that info?

**Comment by chrisjlocke** [comment]
Could be handy to know.  If there is a 'demo' to download, I could then test it. :)

**Comment by justinclift** [comment]
Ahhh, that definitely makes sense.

@CarlCDHPIX ?

**Comment by CarlCDHPIX** [comment]
I use VS Community Edition 2015.

The .net SQLite component is the general one (I assume), downloaded via github, using the NuGet package manager for solution, I type in SQLite and the search term, System.Data.SQLite by SQLite Development Team 1.12M downloads "The Official SQLite database engine for both x86 and x64 along with the ADO.NET providers" is in the description.

From what I have discovered, is the switching on a password protected database, encrypts it with RSA as per this link: [http://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection]

**Comment by justinclift** [comment]
Thanks @CarlCDHPIX, that should help @chrisjlocke familiarise. :smile:

**Comment by chrisjlocke** [comment]
Interesting - thats the exact same .net component I use for my sqlite databases.  Never used the encryption side of it though.

What I would suggest is therefore in the application a routine which creates a database backup (always useful...) and then (optionally) removes the encryption from this database.  This would allow you to view the contents of the database if needed.  If any modifications were required, you'd need the application/another application to re-encrypt this database so it could be replaced in place with the original again.

Either way, DB4S isn't going to be able to open the encrypted database (unless someone wrote an RSA plugin).  DB4S can't use the .net sqlite component, so can't 'talk' to it to unencrypt the database, and certainly can't use it to talk directly with it...

**Comment by justinclift** [comment]
@CarlCDHPIX @chrisjlocke Just stumbled on this: https://github.com/praeclarum/sqlite-net/commit/4858d1fba57f6a4a26157a4daa72a4da1a9f4004

I'm not at all a .NET person, so not 100% sure here... but it sounds like SQLite-net (close to it's next release) will soon support encrypting with SQLCipher.  Which might mean we can then open databases created with it.

Well, hoping that's the case. :smile:

**Comment by chrisjlocke** [comment]
I don't think this is the 'official' system.data.sqlite.dll but a separate
project, but if it 'solves an issue', could be worth investigating.
I'll have a play with it.  Not a huge issue (as fields should be unique
anyway) but a major issue with the 'official' release is that while you can
specify table names in sql queries, the fields returned back aren't table
prefixed. I'm waffling, but sometimes its a pain.
I'll have a look at this implimentation though, as I'm looking at images in
SQL databases at the moment, and it appears the only way to do this is via
parameters, which I've not played with lately.  Now im definately waffling.

**Comment by justinclift** [comment]
Cool. :smile:
