### ISSUE TITLE
Various Compiling Errors

### ISSUE THREAD

**Issue by hdchan** [sqlitebrowser/sqlitebrowser#927]
### Details for the issue

Hi I'm trying to compile the project on my Mac but getting this error. I've followed the steps in the BUILDING.md file for **MacOS X > Building an .app bundle**

I got up to the **qmake** action, but the next step **make** fails with the following. I've attemped the two **qmake** commands in the latter part of the secion:

> $ make
> cd libs/antlr-2.7.7/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.antlr 
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.antlr.Release
> make[2]: Nothing to be done for `first'.
> cd libs/qhexedit/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.Release
> make[2]: Nothing to be done for `first'.
> cd libs/qcustomplot-source/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.qcustomplot 
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.qcustomplot.Release
> make[2]: Nothing to be done for `first'.
> cd libs/qscintilla/Qt4Qt5/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.qscintilla 
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.qscintilla.Release
> make[2]: Nothing to be done for `first'.
> cd src/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
> /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.Release
> clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -std=c++11 -DCHECKNEWVERSION -O2 -arch x86_64 -Wall -W -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.7_2/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7_2/include -I/usr/local/Cellar/sqlite/3.16.2/include -I/usr/local/include -I../libs/antlr-2.7.7 -I../libs/qhexedit -I../libs/qcustomplot-source -I../libs/qscintilla/Qt4Qt5 -I../../sqlitebrowser -Irelease -I.ui -F/usr/local/Cellar/qt/4.8.7_2/lib -o release/MainWindow.o MainWindow.cpp
> In file included from MainWindow.cpp:13:
> ./SqlExecutionArea.h:25:67: error: use of undeclared identifier 'Q_NULLPTR'
>     explicit SqlExecutionArea(DBBrowserDB& _db, QWidget* parent = Q_NULLPTR);
>                                                                   ^
> MainWindow.cpp:160:46: error: 'activated' is a protected member of 'QShortcut'
>     connect(dittoRecordShortcut, &QShortcut::activated, [this]() {
>                                              ^
> /usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers/qshortcut.h:94:10: note: 
>       declared protected here
>     void activated();
>          ^
> MainWindow.cpp:160:5: error: no matching member function for call to 'connect'
>     connect(dittoRecordShortcut, &QShortcut::activated, [this]() {
>     ^~~~~~~
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:337:22: note: candidate
>       function not viable: no known conversion from 'void (QShortcut::*)()' to
>       'const char *' for 2nd argument
> inline bool QObject::connect(const QObject *asender, const char *asignal,
>                      ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:204:17: note: candidate
>       function not viable: requires at least 4 arguments, but 3 were provided
>     static bool connect(const QObject *sender, const char *signal,
>                 ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:217:17: note: candidate
>       function not viable: requires at least 4 arguments, but 3 were provided
>     static bool connect(const QObject *sender, const QMetaMethod &signal,
>                 ^
> MainWindow.cpp:1917:52: error: 'itemChanged' is a protected member of
>       'QTreeWidget'
>         connect(ui->treePlotColumns, &QTreeWidget::itemChanged, this, &M...
>                                                    ^
> /usr/local/Cellar/qt/4.8.7_2/lib/QtGui.framework/Versions/4/Headers/qtreewidget.h:348:10: note: 
>       declared protected here
>     void itemChanged(QTreeWidgetItem *item, int column);
>          ^
> MainWindow.cpp:1917:9: error: no matching member function for call to 'connect'
>         connect(ui->treePlotColumns, &QTreeWidget::itemChanged, this, &M...
>         ^~~~~~~
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:204:17: note: candidate
>       function not viable: no known conversion from 'void
>       (QTreeWidget::*)(QTreeWidgetItem *, int)' to 'const char *' for 2nd
>       argument
>     static bool connect(const QObject *sender, const char *signal,
>                 ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:217:17: note: candidate
>       function not viable: no known conversion from 'void
>       (QTreeWidget::*)(QTreeWidgetItem *, int)' to 'const QMetaMethod' for 2nd
>       argument
>     static bool connect(const QObject *sender, const QMetaMethod &signal,
>                 ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:337:22: note: candidate
>       function not viable: no known conversion from 'void
>       (QTreeWidget::*)(QTreeWidgetItem *, int)' to 'const char *' for 2nd
>       argument
> inline bool QObject::connect(const QObject *asender, const char *asignal,
>                      ^
> MainWindow.cpp:2693:31: error: 'triggered' is a protected member of 'QAction'
>     connect(action, &QAction::triggered, [&]() {
>                               ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtGui/qaction.h:228:10: note: declared
>       protected here
>     void triggered(bool checked = false);
>          ^
> MainWindow.cpp:2693:5: error: no matching member function for call to 'connect'
>     connect(action, &QAction::triggered, [&]() {
>     ^~~~~~~
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:337:22: note: candidate
>       function not viable: no known conversion from 'void (QAction::*)(bool)' to
>       'const char *' for 2nd argument
> inline bool QObject::connect(const QObject *asender, const char *asignal,
>                      ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:204:17: note: candidate
>       function not viable: requires at least 4 arguments, but 3 were provided
>     static bool connect(const QObject *sender, const char *signal,
>                 ^
> /usr/local/Cellar/qt/4.8.7_2/include/QtCore/qobject.h:217:17: note: candidate
>       function not viable: requires at least 4 arguments, but 3 were provided
>     static bool connect(const QObject *sender, const QMetaMethod &signal,
>                 ^
> 7 errors generated.
> make[2]: *** [release/MainWindow.o] Error 1
> make[1]: *** [release] Error 2
> make: *** [sub-src-make_default] Error 2

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [x] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  We've moved to require Qt5 for compiling, as it makes things better for development and pretty much every platform supports it now.

If you reinstall your Homebrew provided qt, in theory (!) that should get updated to Qt5.  After that, compiling our source code should work.

Are you ok to give that a go? :smile:

**Comment by MKleusberg** [comment]
Yeah, these definitely happen because you're trying to compile using Qt4. You either need to stick with version 3.9.1 (or some of the slightly later commits) or need to install Qt5 when you want to compile the latest version from master.

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
