### ISSUE TITLE
Table fields sometimes not handled properly

### ISSUE THREAD

**Issue by iseldonz** [sqlitebrowser/sqlitebrowser#929]
### Details for the issue

Trying to view and modify an existing database. The viewing and modifying work fine with SQLite Database Browser 2.0 b1 (which I believe is an "ancestor" of DB Browser for SQLite), but with DB Browser for SQLite, things do not work as expected.

The database opens, but using "Browse Data", if certain tables are selected (but not all), the list of fields of that table is not anything like what is shown with DB Browser for SQLite. Selecting some tables produces the expected result, but then if certain other tables are selected, the field descriptions from the previous table are retained instead of being updated to the new table.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:10.8.2)
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
This hasn't been mentioned before, which would imply something specific with your database ... it has an interesting schema...
Is there any chance of a copy of the database causing issues? If it is just the schema, then the data can be removed from the database.

**Comment by MKleusberg** [comment]
@iseldonz This sounds very much like a problem with our SQL parser. As @chrisjlocke said, it'd be best to have a look at your table schema. It's sufficient to just have the schema, no data is required. What you can do is to open the database file in DB4S, click the text in the schema column for a not working table, hit Ctrl+C and paste it here in Github. Should be easy for us to fix it then :smiley:

You can also try the latest nightly build. I've recently fixed some grammar parsing issues in there, so you might be lucky :smiley:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
