### ISSUE TITLE
Cannot switch workspace on gnome when SQLiteBrowser is open

### ISSUE THREAD

**Issue by vanitasvitae** [sqlitebrowser/sqlitebrowser#934]
### Details for the issue
Hi!
Im using sqlitebrowser from the Debian testing repository on my machine running Gnome Shell (3.22.2).
When I have sqlitebrowser opened, it seems like it is constantly requesting focus. I cannot switch workspaces, since it constantly switches back to the sqlitebrowser window.
Also I cannot minimize it, since it instantly gets de-minimized again.

### Useful extra information
Gnome-Shell version 3.22.2

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: (Debian Testing)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for reporting this.  I'm pretty sure someone else has mentioned this happening to them a few months ago too, but I'm not finding the bug report about it just yet.

@revolter Do you remember the previous bug report about this?  From memory, you commented on it.

**Comment by innermous** [comment]
In any case it's upstream bug, not SQLiteBrowser.

**Comment by justinclift** [comment]
Why an upstream bug?

**Comment by kehugter** [comment]
From #948 

The problem starts in one of the following commits

1ced89779353346548d2e71d8eb58dc4d278f1ca
b9e4433318efb869af494dd2c7631e0787248143
aa965ff7256bbf0dcb279ad90697c3ed9f56c203

1ced897 and aa965ff fail to compile in my machine, so I couldn't bisect the exact bad commit.

**Comment by justinclift** [comment]
@kehugter Excellent, that's good info. :smile:

**Comment by MKleusberg** [comment]
Just quickly mentioning issue #635 here which seems to describe a similar problem (see the last couple of comments). However, that issue is older than the commits mentioned by @kehugter. No idea how to explain this but maybe this is some valuable input for somebody :smiley:

**Comment by akhilman** [comment]
Bug appears only when `View→Edit Database Cell`  is enabled.

**Comment by MKleusberg** [comment]
That's some interesting information, @akhilman! Can you double check one extra case for me? When disabling the ```View -> Edit Database Cell``` option do you have the ```View -> Plot``` option enabled? And if not, does setting it change anything?

If we can really narrow this down to the Edit dialog I could prepare a patch that adds tons of debug output to that dialog and, with any luck, this helps us tracking down the source of the problem.

**Comment by kehugter** [comment]
It's only `Edit Database Cell`. Tried all permutations and `Plot` doesn't trigger the issue.

**Comment by prcutler** [comment]
I can confirm this bug on GNOME 3.22 on Fedora 25.  Looking at the above comments, I'm just running SQLIteBrowser as it comes installed by default - I haven't disabled or enabled the Views as mentioned two comments above.  If there is anything you want me to try to confirm, please let me know.

**Comment by justinclift** [comment]
@vanitasvitae @prcutler @akhilman @kehugter Would any of you have time to try something out which might (if lucky) solve this problem? :smile:

If you try, please compiling this branch here and see if the problem seems any different: https://github.com/justinclift/sqlitebrowser/tree/issue_934_v1
(specifically, the "issue_934_v1" branch)

It's our latest source for what will become version 3.10.0, but with all of the calls to `qApp->processEvents()` either removed or commented out.

While debugging a different problem today I gained a sneaking suspicion that these calls might be causing the problem here.  Removing them hasn't seemed to cause any change in user visible behaviour for me just now.  So, it'd be useful to find out if there's any change for yourselves. :smile:

**Comment by kehugter** [comment]
@justinclift sorry for taking so long to answer. I'm using Arch now but can still reproduce the issue compiling 6029e25bcc994c7e448f0296da387635171175f3. Issue is also present in https://github.com/justinclift/sqlitebrowser/commit/e7933fac6dd9b881a0a7247c65c23ee0d66b75c1 even after a `make clean`.

**Comment by justinclift** [comment]
@kehugter Thanks for testing.  Someone else mentioned a few weeks ago that the experimental thing above didn't fix it for them either, so I guess your report really confirms it.

Will probably have time to investigate it further over the next few weeks. :smile:

**Comment by rastersoft** [comment]
Hi:
I found exactly this bug five minutes ago. Anyway... it seems to be more a bug in gnome shell, not in sqlitebrowser, isn't it? (and the same in Cinnamon: both are based on mutter). Has someone reported this to gnome programmers?

**Comment by kehugter** [comment]
> a bug in gnome shell

I don't think so. sqlitebrowser seems to be requesting focus. Some new findings in the `dconf`s:

`org.cinnamon prevent-focus-stealing false`
`org.cinnamon bring-windows-to-current-workspace false`
Switching workspaces is impossible

`org.cinnamon prevent-focus-stealing true`
`org.cinnamon bring-windows-to-current-workspace false`
No issues

`org.cinnamon prevent-focus-stealing false`
`org.cinnamon bring-windows-to-current-workspace true`
sqlitebrowser follows to every workspace

`org.cinnamon prevent-focus-stealing true`
`org.cinnamon bring-windows-to-current-workspace true`
sqlitebrowser follows to every workspace only if focused

**Comment by justinclift** [comment]
@vanitasvitae @akhilman @prcutler @rastersoft A fix (written by @kehugter) for this problem has just been added to our source code.

Would any of you have the time/interest to try compiling, and confirm back from your point of view? :smile:

**Comment by rastersoft** [comment]
Compiling...

**Comment by rastersoft** [comment]
Ok, this patch seems to have fixed the problem. Thanks!!!!

**Comment by justinclift** [comment]
Fantastic!  Thanks for confirming @rastersoft. :smile:

Good work @kehugter, this bug has been annoying people for ages. 😀

**Comment by qwabra** [comment]
+1

```
[qwabra@n5110 ~]$ sqlitebrowser -v
This is DB Browser for SQLite version 3.10.1.
[qwabra@n5110 ~]$  cat /etc/fedora-release
Fedora release 27 (Twenty Seven)
[qwabra@n5110 ~]$ gnome-shell --version
GNOME Shell 3.26.2
```

**Comment by hutou** [comment]
Workspace switching still blocked (version 3.10.1 on Archlinux / Gnome 3.30)

**Comment by justinclift** [comment]
@hutou That's not good.  Are you comfortable compiling stuff from source?

If you are, the build instructions we use are here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#generic-linux-and-freebsd

We don't have any Arch specific steps yet, but it's generally a matter of installing dependencies, then running `cmake` on the directory to generate a Makefile, then running `make` to do the compiling.

In theory (!), it shouldn't be toooooooooo hard to figure out. :smile:

**Comment by hutou** [comment]
Ok, sqlbrowser works fine after compiling from source (git clone).
I noticed the last release is 3.10.1 from Sept. 2017 and the Archlinux package is built upon it. So, I suppose this version still suffers from this bug.
Thanks

**Comment by justinclift** [comment]
Cool. :smile:

And yeah, the next release should be pretty soon (#1656 for progress, if you're interested), so it's probably not worth filing a bug for 3.10.1. :smile:
