### ISSUE TITLE
An acutal code problem with lua

### ISSUE THREAD

**Issue by mextedol** [sqlitebrowser/sqlitebrowser#936]
I was coding with lua got this error
chunk_2:(11,29-12,12): attempt to call a nil value

Pls help

**Comment by justinclift** [comment]
Is this related to DB Browser for SQLite?

**Comment by justinclift** [comment]
If you're needing help with Lua coding, it's probably best to ask on the Lua mailing list:

&nbsp; &nbsp; http://www.lua.org/lua-l.html

:smile:

**Comment by innermous** [comment]
I wonder every time when I see such issues...
