### ISSUE TITLE
Import Table from CSV bug

### ISSUE THREAD

**Issue by nielscup** [sqlitebrowser/sqlitebrowser#94]
Import table from a CSV file does not handle linebreaks in a field: If a field in the csv file contains a linebreak, the import function handles it as the start of a new record. A solution might be to take the number of fields per record into account as well.

I noticed this while importing a csv file from a third party.

ps. I find the "Import table from a CSV file" function brilliant anyways!

**Comment by wl1508702360** [comment]
When importing csv file, why the field value in the table is changed to filed1, filed2 ... (the latest windows version)
![image](https://user-images.githubusercontent.com/20127531/34369695-0a420ef0-eaf9-11e7-9b8f-5a8975032a37.png)

**Comment by justinclift** [comment]
@wl1508702360 Oh, that doesn't look good.

Can you make a screenshot of the setting you are using for the import dialog?  Hopefully it's just a setting that needs changing. :smile:

**Comment by wl1508702360** [comment]
Sorry,you can see the picture below, I hope you do not mind if I use Chinese
![image](https://user-images.githubusercontent.com/20127531/34377520-5e46044c-eb2c-11e7-9594-5d596a3d38c1.png)
After importing the results as shown below
![image](https://user-images.githubusercontent.com/20127531/34377657-edd87db0-eb2c-11e7-9b4c-078cd5554386.png)

**Comment by justinclift** [comment]
No worries.  Does the table it's being imported into already exist?  I'm guessing "yes", but am asking just to make 100% sure I understand. :smile:

**Comment by MKleusberg** [comment]
Hmm as far as I understand, it probably does not yet exist because otherwise the column names wouldn't be field1, field2, etc. So the question would then be why we are showing '1', '2', ... in the preview but use 'field1', 'field2', ... in the actual table.

I have actually changed that while working on the CSV import. So in theory it should say 'field1', 'field2', ... in the preview now as well.

@wl1508702360 Are you using the latest release (3.10) or the latest nightly build? If you're not sure you can double check in the Help menu. If you aren't using the nightly build, can you download it [here](https://nightlies.sqlitebrowser.org/latest/) and try again? 😄

**Comment by justinclift** [comment]
@wl1508702360 ping?

**Comment by wl1508702360** [comment]
@MKleusberg 
Hmmm, I tried the version you gave me, but it still does not work. You can see through the figure below
![image](https://user-images.githubusercontent.com/20127531/34472353-67b7c2d6-ef9b-11e7-9fcf-a06504cb6eca.png)
After importing the results as shown below
![image](https://user-images.githubusercontent.com/20127531/34472371-c3c5bce0-ef9b-11e7-86a3-aa4ab3282efb.png)
I have used the 3.10.1 version, is successful, the recent re-use of such problems

**Comment by wl1508702360** [comment]
Hi, @justinclift 
Sorry! I don't understand what you mean by ping

**Comment by justinclift** [comment]
@wl1508702360 It's just me sending a reminder, in case you'd forgotten about this. :smile:

**Comment by justinclift** [comment]
@wl1508702360 Out of curiosity, are you able to give us the CSV file for testing with?

It doesn't have to be the whole thing, it just needs to be enough to trigger the problem.  That would probably help us investigate. :smile:

**Comment by wl1508702360** [comment]
@justinclift Yes, I am going to send you

**Comment by wl1508702360** [comment]
@justinclift Hi, Did you get it? I also tested the use of the next version of Linux and found that the same windows version

**Comment by justinclift** [comment]
Thanks @wl1508702360.  Got it.  I've just forwarded it to @MKleusberg via email, for when he has time to look into it. :smile:

**Comment by wl1508702360** [comment]
@justinclift Okay.

**Comment by wl1508702360** [comment]
You can know the difference between them by the following two pictures
first(3.10.1):
![image](https://user-images.githubusercontent.com/20127531/34506016-1ffb310c-f064-11e7-88e4-82adcfa166bf.png)
second(the newest version):
![image](https://user-images.githubusercontent.com/20127531/34506033-4a2a10c4-f064-11e7-8cee-9b857f502d23.png)
The result is the same as below：
![image](https://user-images.githubusercontent.com/20127531/34506049-6dd6ecea-f064-11e7-8123-893472ad2572.png)

**Comment by wl1508702360** [comment]
@MKleusberg 
You can know the difference between them by the following two pictures
first(3.10.1):
![image](https://user-images.githubusercontent.com/20127531/34506077-a8ff63ba-f064-11e7-9ffe-01defc0f00ce.png)
second(the newest version):
![image](https://user-images.githubusercontent.com/20127531/34506083-b4d118fa-f064-11e7-9834-9c40a2ea8795.png)
The result is the same as below：
![image](https://user-images.githubusercontent.com/20127531/34506090-beea480c-f064-11e7-9a9e-ff02746e61cf.png)

**Comment by MKleusberg** [comment]
So it's about the header in the table, that is the column names? We've added the 'field' bits in there:
![34506083-b4d118fa-f064-11e7-9834-9c40a2ea8795](https://user-images.githubusercontent.com/3153504/34539326-528acc92-f0d0-11e7-84a8-a775d153c91f.png)

That was actually done on purpose, so the preview is the same as the result after the import. Was it that? :smiley:

**Comment by wl1508702360** [comment]
Hi,@MKleusberg 
But apart from this, I didn't find any other difference
