### ISSUE TITLE
Database will not open from a Virtualbox shared folder

### ISSUE THREAD

**Issue by jlmcgraw** [sqlitebrowser/sqlitebrowser#940]
### Details for the issue

I'm attempting to open an sqlite database (called "Recordings.db") associated with Voice Memos copied from an iPhone.

When attempting to open this file from a VirtualBox Shared Folder db4s fails with "invalid file format"

If I copy that same file locally to the virtual machine then it opens successfully.

This is most likely a VirtualBox Shared Folders issue but I thought I'd start here

VirtualBox Host is Ubuntu 16.04
VirtualBox Guest is Ubuntu Mate 16.10

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [X] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [X] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [X] Other: Locally compiled v3.9.99___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  No idea where to even begin with this, so hoping some of the others have ideas. :smile:

**Comment by jlmcgraw** [comment]
Are you able to recreate this issue? (if you still have your Mate VM from the last issue I filed) :)

**Comment by justinclift** [comment]
Heh Heh Heh

I haven't tried, and probably won't for (at least) a few days personally.  My headspace is entirely in a different area at the moment and I **really** don't want to break that. :wink:

**Comment by jlmcgraw** [comment]
Fair enough.  Like I said, it's probably a bug in VirtualBox but figured
you might have some good insight into it

**Comment by MKleusberg** [comment]
Seems like a common issue with SQLite + Virtualbox:
https://forums.virtualbox.org/viewtopic.php?f=3&t=42404
https://forums.plex.tv/discussion/165867/ubuntu-on-virtualbox-w-shared-folders-sqlite-mmap-error
https://dba.stackexchange.com/questions/44156/disk-i-o-error-in-sqlite/80594
http://fossil-users.fossil-scm.narkive.com/muAXYMCp/problem-accessing-shared-folder-in-virtualbox

From the last link
```
SQLite is quite strict with the filesystem, and it needs it to work as
advertised, for example with syncing and file locking. VirtualBox is
just not there yet. Go bug them. Give them a tiny test case, a
sequence of commands to create a repository and try to open it.
```

**Comment by justinclift** [comment]
@MKleusberg Ahhh, that definitely makes sense.

I guess we should close this now, as it's not a DB4S problem (and we're trying to get the issue count down :wink).

@jlmcgraw Are you ok to file a bug with the VirtualBox project?

&nbsp; &nbsp; https://www.virtualbox.org/wiki/Bugtracker

**Comment by justinclift** [comment]
This seems potentially relevant:

&nbsp; &nbsp; https://www.virtualbox.org/ticket/10059

Not seeing any other tickets in their system about SQLite with shared folders.  Search page:

&nbsp; &nbsp; https://www.virtualbox.org/search?ticket=on&q=sqlite
