### ISSUE TITLE
Cannot change name of a newly created field when creating a table

### ISSUE THREAD

**Issue by prutz1311** [sqlitebrowser/sqlitebrowser#945]
### Details for the issue

When creating a new table and trying to set a new name to a field, sqlitebrowser responds with an error `There already is a field with that name. Please rename it first or choose a different name for this field.`
![image](https://cloud.githubusercontent.com/assets/6525383/22317453/c8d7fd48-e384-11e6-8e29-672359c6cd9e.png)
Expected: changing name both in the table widget and in SQL area of Create Table window

### Useful extra information

This stops working after f728ff7. Btw at f728ff7 itself after editing table name all windows of sqlitebrowser freeze.
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Xubuntu 14.04.5 LTS)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: 8d82070

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Fixed by @schdub in #947. Thanks @schdub! :smile:
