### ISSUE TITLE
Some issues with the plot feature

### ISSUE THREAD

**Issue by MKleusberg** [sqlitebrowser/sqlitebrowser#950]
Here are some issues @chrisjlocke found in the plotting feature testing the latest version from master. See PR #925 for details.

```
Initial thoughts:

*   Widget is not disabled when a database is not open
*   When 'Browse Data' tab is clicked on, X axis gets unticked (ie, when user flips from execute SQL to Browse Data) Two 'rowid' rows momentarily exist in the grid, but this is just a quirk of the grid re-populating I think.
*   When an item in the X axis is ticked, ticking another item unticks the original item, but the item you clicked on is not ticked, so you have to click the item you want again.
*   When selecting 'row #' as the X axis, '65536' is displayed as a label, rather than 'row #'.
```

**Comment by MKleusberg** [comment]
All done :smiley: The first one is a little tricky because the widget is disabled, it just doesn't look like it. But that's something we can't do much about...

@chrisjlocke Can you double check that the other three are fixed in the next nightly build? :smiley:

**Comment by chrisjlocke** [comment]
Will do.  😼

**Comment by justinclift** [comment]
@chrisjlocke Ping. 😉

**Comment by MKleusberg** [comment]
Ping? :wink:

**Comment by chrisjlocke** [comment]
6 months ago?! Whoops. Sorry!

**Comment by chrisjlocke** [comment]
Apologies for the delay.  Yes, the issues I raised have been resolved.  Many thanks!
The only quirk I have now is that if you untick a Y axis field, the axis label is removed.  This doesn't happen if the X axis is unticked.  

![image](https://user-images.githubusercontent.com/7872218/32254087-851c783e-be96-11e7-8521-ee430edd9e2b.png)

So here, the label is showing ap_date, but its unticked.  Just a minor thing...

**Comment by justinclift** [comment]
This sounds like it might have been fixed a few days ago by 16263452c83f8a5c0deccc0ec17b5cbdb6d7a6db, which cleans up the plot y axis check handling.

@chrisjlocke Do you have time to check it quickly? :smile:

**Comment by chrisjlocke** [comment]
🏃 Am on it...

**Comment by chrisjlocke** [comment]
Nope.  ☹️

**Comment by justinclift** [comment]
Doh!

k, this sounds like a fairly easy fix though, as @MKleusberg was updating this same section of code the other day. :smile:

**Comment by MKleusberg** [comment]
Should be fixed in the next nightly build 😄

**Comment by chrisjlocke** [comment]
You should make that your signature.  😆

**Comment by justinclift** [comment]
I've just manually started the Windows nightly build script again, so in ~1/2 hour we can test this instead of waiting until tomorrow. :wink:

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/33723073-8bff7fc2-db63-11e7-937f-9d71856bfe3b.png)

**Comment by justinclift** [comment]
k, they're built and uploaded. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by chrisjlocke** [comment]
Ticking Y axis column labels doesn't show anything if the X axis is unticked, but I assume thats not a bug per-se as the operation hasn't completed yet... so I'll shut up otherwise this'll never get closed! ;)

Thanks @MKleusberg for the prompt fix!

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by MKleusberg** [comment]
Cool :smile: Thanks again for reporting all these issues, @chrisjlocke 👍
