### ISSUE TITLE
views crashes sqlitebrowser by changing tabs

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#953]
### Details for the issue

Installed latest Windows build:
DB Browser for SQLite-2017-01-30-win64.exe

Reproducible steps:

 0. Opened up a database I created a few months ago
 1. click browse data
 2. Change to views table
 3. Change to database structure tab back to browse data
 4. Crashing as soon as browse data is selected.

### Useful extra information

My simple create sql:
```
CREATE VIEW `surgeview` AS select date, dayOfWeek, distance, surge, surge_amount from rides where surge="yes"
```

#### I'm opening this issue because:

- [ x] DB4S is crashing

#### I'm using DB4S on:

- [x ] Windows: ( _version:Windows 8.1)

untested:
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] Other: SQLite-2017-01-30

**Comment by jungle-boogie** [comment]
Okay, crash can happen without the refresh procedure and steps above have been modified to reflect this.

**Comment by MKleusberg** [comment]
Thanks for reporting this, @jungle-boogie! This was caused by some refactoring I did recently and which needs some thorough testing. So I'm quite happy you've reported this issue :smiley: I've just pushed a commit, so it should be fixed in the next nightly build. Can you test that for me and confirm it's working even in your database? Also, if you should find any other problems like this one, please keep opening issues for them :smiley:

**Comment by jungle-boogie** [comment]
Hi @MKleusberg, happy to help. Out of curiosity, when did you make the changes? Just curious how many nightly builds escaped before I caught this.

I'll keep this issue opened until tomorrow and update with the results.

thanks!

**Comment by MKleusberg** [comment]
Thanks a lot :smiley:

I've worked on the refactoring from 20/01/2017 till 23/01/2017. This bug was probably introduced by commit d236f6df9f09c9969e8c75f6f4728048b6da7eff, so it's in there since 23/01/2017 :wink:

**Comment by jungle-boogie** [comment]
This is fixed! Thanks for the quick fix.

**Comment by MKleusberg** [comment]
Awesome :D Thanks again for reporting this!
