### ISSUE TITLE
Useful to have a way to enter a full path rather than have to navigate

### ISSUE THREAD

**Issue by Logistes** [sqlitebrowser/sqlitebrowser#958]
Since I am using sqlitebrowser to help me develop iOS applications in Xcode using Core Data, the pathnames to the sqlite files are demoralisingly long and hard to remember. I can easily print the full pathname in the console and then copy it into the paste buffer. I would like sqlitebrowser to have a place for me to copy and paste that path and open the database directly.

At present the only way to select the path is to navigate through the finder-like dialog, which is painstaking and error-prone.

**Comment by chrisjlocke** [comment]
I was thinking you could 'cheat' by using the 'history' of the last 4 opened files.... In Windows this is stored (I believe) in the registry.  Not sure where its stored on Apple devices...
My kludge would be to edit the history, then simply click the file in DB4S...

**Comment by MKleusberg** [comment]
At least on Linux you can just click File -> Open Database and copy the whole path including file name into the file name box at the bottom, then click OK and it opens it no matter what directory you are in. Have you tried that already?

**Comment by Logistes** [comment]
Thanks for the suggestion. I'm on a Mac. The trouble is that in the app I
will be developing, the paths are going to change frequently and each
simulator has a different path.

**Comment by Logistes** [comment]
I'm on a Mac, and there is unfortunately no such text box.

**Comment by gboudreau** [comment]
@Logistes On Mac, in the Open Database dialog, hit <kbd>cmd</kbd>-<kbd>shift</kbd>-<kbd>g</kbd>, and paste the full path to your SQLite database file (you might need to use a right-click in the textbox to be able to paste in there for some reason).

**Comment by Logistes** [comment]
I have finally got back to this problem, found your reply, and it was perfect, thanks. 
It is hard to remember, but it is the open dialog homolog for the Finder | Go | "Go to folder ..." action, which has its key stroke combination shown in the menu item. So I can recall it from that.

**Comment by mgrojo** [comment]
Another solution would be opening the database from a command line or dragging and dropping the file from a file manager. This seems already solved with the help provided, so I'll close this issue now.

**Comment by justinclift** [comment]
@mgrojo Was that help wanted tag accidental? :smile:

**Comment by mgrojo** [comment]
No, it wasn't 😁I have probably misused it. I wanted to tag it as: a user wanted a way to do something and the solution didn't require an enhancement... But maybe that is for the project owners to request help from their users? 🤔

**Comment by justinclift** [comment]
Ahhhh.  Yeah, that "user wanted a way to do something and the solution didn't require an enhancement" concept is pretty much right. :smile:

As a data point, when people look at the sqlitebrowser organisation page on GitHub:

https://github.com/sqlitebrowser

With our "sqlitebrowser" repo it shows "13 issues need help" under the tag list.  I **think** this `help wanted` tag is what that line goes by, but it only includes the Open items in the counted number.

**Comment by mgrojo** [comment]
Yeah, closed issues need also good labelling for archiving purposes.

But looking at how the 'help wanted' tag is highlighted in the organisation page has lead me to think that the conventional use for this label was more or less the second one that I said. In fact after a bit of searching, this is what GitHub says about these labels: 
https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by justinclift** [comment]
Cool, no worries. :smile:
