### ISSUE TITLE
Exclude HTML tags and some UNICODE Characters while searching in SQLite using REGEXP

### ISSUE THREAD

**Issue by waqas-ansari** [sqlitebrowser/sqlitebrowser#960]
I am working with Arabic Language saved in UNICODE Format in SQLite. I want to implement a search. But there's a problem.

Let's say the text is

```
<html>
  <head>
    <style>
      @font-face {
        font-family: "Al_Mushaf";
        src: url('fonts/al_mushaf.ttf');
      }
      @font-face {
        font-family: "Jameel Noori Nastaleeq";
        src: url('fonts/jameel_noori.ttf');
      }
    </style>
  </head>
  <body>
    <h3 style='font-family:"Al_Mushaf"'>
            وَاۡمُرْ 
    </h3>
  </body>
</html>
```

And it is stored in SQLite Database. Now I want to search `html`, it will return the result and if I search  `وامر` it won't return a result because in actual text, it is `وَاْمُرْ` (with these extra UNICODE).

I want to ignore all HTML tags and these extra UNICODE Characters while searching so that `html` shouldn't return a result while `وامر` should return a result.

What I found so far;

1. Make extra column and put stripped text into it and then search (I can't do it because there are thousands of books and they will take a lot of memory)
2. UDF Like SQL (I couldn't find any suitable example/tutorial to implement it)
3. Using REGEXP (I couldn't figure it out yet how to do this, I just know that I've to implement it myself)
4. SQL query using LIKE and GLOB operators and wildcard characters.

I'm stuck for two days and couldn't find a working solution. Option#4 is desirable but any working solution will do the charm.

Meanwhile, I've to keep application memory efficient and optimized searching.

Any help is highly appreciated.

What I've done so far
1. I've made regex to ignore html tags and text between style tag and used it in query with REGEXP.
Now there are two problems,
    - I want to ignore these extra characters too. I know their UNICODEs, just need to know how to append it in the regex. This is my regex;
`(?![^<]*>)(?!<style[^>]*?>)(TEXT)(?![^<]*?<\/style>)`
    - I've used it in query like
`SELECT text FROM dummy WHERE text REGEXP <myregex>`
It's not giving an error but not returning the desired result too.

2. I've compiled `sqlite3` library in my project. I am now looking for anyone to help me with writing a function for my regex, attach it to database and call it from query.

**Comment by justinclift** [comment]
As a general thought, this seems like a general SQL question rather than something specific to DB4S.

What you ***probably*** should do is ask on the sqlite users mailing list:

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

There are many knowledgable & helpful people there, and it's very likely you'll receive good suggestions/advice. :smile:

**Comment by waqas-ansari** [comment]
Thank you for guiding me. I will definitely do so.

**Comment by justinclift** [comment]
You're welcome. :smile:
