### ISSUE TITLE
Rightclick open table doesn't open the right table

### ISSUE THREAD

**Issue by AndreasSummer** [sqlitebrowser/sqlitebrowser#963]
When you try to open a database table in "Database Structure" and click right and choose  "Browse Table" in the context menu, it opens the first table instead of the selected one.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
If you download and try the latest nightly (nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows) then this should be fixed.

**Comment by justinclift** [comment]
Yeah, this was mentioned to us shortly after the 3.9.1 release, so has been in the nightly builds now for some time.

@AndreasSummer Are you ok to try out the latest nightly build? :smile:

**Comment by justinclift** [comment]
Closing due to lack of response. ☹️

**Comment by AndreasSummer** [comment]
Worked :)

**Comment by justinclift** [comment]
Awesome. :smile:
