### ISSUE TITLE
Critical WIFI interference for macOS 

### ISSUE THREAD

**Issue by zhanghedr** [sqlitebrowser/sqlitebrowser#964]
### Details for the issue
When running DB Browser for SQLite on my 2016 15-inch Macbook Pro, the WIFI connection becomes very unstable and the ping is moving up and down dramatically. Sometimes it even causes connection dropping. I tested that It happens for both 2.4GHz and 5GHz WIFI. Thanks.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 10.12.3)
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just to confirm, you believe a program is affecting your physical WiFi connection?  As soon as DB4S is closed down, the WiFi status is returned to normal?
DB4S is an application, so its hard to see how it can affect the 'outside world' as such.  It would only use the WiFi....in fact, it doesn't, it goes through your OS.... to access files on a network share.  

I'm not familiar with Macs, but does it show (when DB4S is running) the state of the network, eg, what application is using what?  In Windows,  its easy to see what application is using the CPU, memory, disk and network.

![image](https://cloud.githubusercontent.com/assets/7872218/23292461/e3f04dbc-fa57-11e6-99e7-0aa59f30c2c7.png)

**Comment by justinclift** [comment]
@zhanghedr Interesting.  That's the first time a problem like this has been mentioned.

Do any other applications cause the same problem?

I'm kind of thinking there might be a problem with your WiFi hardware, which is being triggered by DB4S.  At the moment, that's the only thing I can think of.

If you try our latest nightly build (download locations are on the front page), does it still happen?  That's definitely worth trying.

**Comment by zhanghedr** [comment]
@chrisjlocke @justinclift Thanks for reply. This is the only application I found caused the problem. I haven't  faced this issue on Windows before with any application. It sounds weird but it happens on macOS for me. 

It shouldn't be hardware issue since I went to apple store yesterday and they checked hardware and the system and it doesn't have any issue. Then I tested WIFI by pinging google and I closed all applications. First the request time is stable. But after I open DB4S the request time becomes very unstable. And it turned to normal immediately after I closed it.  I can upload screenshot when I back home. This happened in both 2.4GHz and 5GHz WIFI. Today I closed DB4S and network works well without any problem.

I will try the latest nightly build to see if it still happens. Thanks.

**Comment by chrisjlocke** [comment]
The only other suggestion I can offer at this stage is to confirm whether or not the ping request time improves after a short time.  I can imagine (as a possibility) DB4S doing some 'am I up to date?' checks, but apart from that (which should be minimal) DB4S doesn't use the network (unless you're opening a database over the network, of course...)
If left open, does the ping request time improve, or does the network only improve once DB4S is closed?

There are applications to monitor the network traffic down to the packet level, so you could confirm if DB4S was (for example) splatting garbage over the network (and thus the WiFi) but you'd need to know what you were doing and be comfortable dibbling and dabbling about.....

**Comment by zhanghedr** [comment]
@chrisjlocke Yes the network improve quickly when DB4S is closed. It seems tab doesn't matter. 

Actually I found that I have same issue with another SQLite client. I doubt that maybe my mac has something conflict with sqlite3. That's so weird. I think you may close the issue if you want. I can reopen it if I found the solution later or if someone else has same issue with me.

**Comment by MKleusberg** [comment]
Just one more idea: does it help when when you go to the Settings dialog and disable the Automatic update check? That's the only network activity in the application.

**Comment by chrisjlocke** [comment]
> That's the only network activity in the application.
Unless you're opening a (big?) database over a network connection.

**Comment by justinclift** [comment]
@zhanghedr Just to check... did you download DB4S from our official locations? (eg sqlitebrowser.org, or from github.com/sqlitebrowser)

Just wondering if maybe the download came from somewhere else, and someone has put something dodgy in it. 😖

**Comment by zhanghedr** [comment]
@justinclift @MKleusberg @chrisjlocke  I downloaded from sqlitebrowser.org. And it's a small database. It seems my mac network has conflict with sqlite3 database, not with specific client software. Hope I am the only one facing this, sad. For now I have to stand with it while developing with sqlite. Thanks guys.

**Comment by justinclift** [comment]
@zhanghedr No worries, it was just a thought.  And yeah, that is a weird problem. 😦

**Comment by justinclift** [comment]
Looking back through this... it turns out @zhanghedr was correct.

It's was a Qt problem, caused by [an insane default Qt behaviour](https://bugreports.qt.io/browse/QTBUG-40332) - which no-one in their right mind would expect Qt to do.

Fixed by @MKleusberg a few months ago in https://github.com/sqlitebrowser/sqlitebrowser/commit/73946400c32d1f7cfcd4672ab0ab3f563eb84f4e.  It's in our nightly builds, if that's useful for people. :smile:
