### ISSUE TITLE
Open file from console doens't display the good path in recent menu

### ISSUE THREAD

**Issue by dridk** [sqlitebrowser/sqlitebrowser#965]
### Details for the issue
Open file from console doesn't display the good path in recent menu

### Useful extra information
From console : 

     sqlitebrowser database.sqlite 

From gui , fileMenu : The file cannot be load because it's just the filename and not the full path.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: 3.7.0

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, that's interesting.  Does it still happen with modern DB4S though?  Version 3.7.0 is really old, and we've changed the code that does this stuff a fair amount in the meantime.

**Comment by dridk** [comment]
Same issue for the last version. I made you a pull request to fix that.

**Comment by justinclift** [comment]
Thanks @dridk. :smile:
