### ISSUE TITLE
Create AppImage

### ISSUE THREAD

**Issue by dridk** [sqlitebrowser/sqlitebrowser#968]
I would suggest to create an AppImage for Linux. 
Several Qt application does it by using https://github.com/probonopd/linuxdeployqt/ 
Personnaly I prefere compile myself or getting application from the PPA. But for some people appImage would be greate. See http://appimage.org/

**Comment by probonopd** [comment]
Started working on it [here](https://github.com/probonopd/sqlitebrowser/blob/patch-1/.travis.yml).

**Comment by probonopd** [comment]
Sent Pull Request https://github.com/sqlitebrowser/sqlitebrowser/pull/969.

**Comment by justinclift** [comment]
AppImage looks interesting.

**Comment by justinclift** [comment]
Thanks @dridk and @probonopd, just merged it.  Going to watch this over the next few days to gain a better understanding of how it works in practise.

We'll likely need to document "how get get the transfer.sh URL out of the log" in our wiki, but that shouldn't be hard once it's understood. :smile:

**Comment by probonopd** [comment]
Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the [Releases](https://github.com/sqlitebrowser/sqlitebrowser/releases) page of your project. This is what I recommend. See https://docs.travis-ci.com/user/deployment/releases/. If you want to do this for continuous builds, also see https://github.com/probonopd/uploadtool.

**Comment by justinclift** [comment]
Keeping the binaries (for every commit) in GitHub releases sounds fairly terrible for our project.

We have a server for nightly releases, which could hold those kind of development centred builds.  We'd need to figure out how to get the Travis CI builds uploaded to that securely though, without embedding username/password in the .travis.yml.

Something to investigate at a later date. :smile:

**Comment by probonopd** [comment]
> We have a server for nightly releases, which could hold those kind of development centred builds.

Excellent.

By the way, uploadtool deletes the prior continuous build and then uploads the latest one, so that there is always only one "continuous" tag on GitHub Releases.

**Comment by justinclift** [comment]
Interesting, thanks. :smile:
