### ISSUE TITLE
Is there an easy way to browser tables?

### ISSUE THREAD

**Issue by rodrigozanatta** [sqlitebrowser/sqlitebrowser#973]
Just want to know if I can go to next table with some shortcut. When I am browsing the tables, I need to click in their name in drop-down menu. Then, to go to next, need to do the same thing. 

Why not a simple shortcut or icon to go to next table. This will make my life really easier.

**Comment by chrisjlocke** [comment]
Click in the 'Table' combo box (which on Windows you can get to by pressing Alt+T) then simply press the down arrow key.  You can press the down arrow key again and again to get the next table.
Depending on your operating system, you can get an application to 'wrap' these two keystrokes in one, so pressing something else (eg, F8) runs the macro of pressing Alt+T, then down arrow......

**Comment by rodrigozanatta** [comment]
@chrisjlocke I am using the Mac OS X. I tried what you say. Here is ⌘+T. But doing the same thing, when I press down, it just go down one cell. Even if I focus the drop-down menu, the down button don't work. 
Maybe this is a specific bug from Mac Os X. Is there a dirt solution to this?

**Comment by chrisjlocke** [comment]
Install Windows?  ;)

Does pressing Tab change the focus?  I've not got a Mac to test this on.

**Comment by justinclift** [comment]
It's probably not a bad idea to include some shortcuts for switching between tables via keystroke. :smile:

**Comment by rodrigozanatta** [comment]
@justinclift great idea. How difficult is to make this? I am right now looking a lot of tables and need to do two mouse click to get the next table. I will love have this fix now. 👍 

@chrisjlocke the tab don't change the focus. This is not common in osx, but I thing is about the interface technology they used in sqlitebrowser.

**Comment by justinclift** [comment]
@rodrigozanatta It's unlikely to happen in the next fortnight.  Our main developer for DB4S is on holiday for a few weeks, and I'm working on server side stuff in a different language completely. :wink:

**Comment by rodrigozanatta** [comment]
@justinclift thanks for answer. I will wait..

**Comment by MKleusberg** [comment]
Still on holiday, so just a quick note from my side: I think we already have exactly what you're asking for, @rodrigozanatta :smiley: When you're using a recent nightly build you should be able to switch tables using the ```Ctrl + PageDown``` and ```Ctrl + PageUp``` shortcuts.

**Comment by rodrigozanatta** [comment]
@MKleusberg , I tested and it worked really good! In mac you need to use ⌘ + PageDown or ⌘ + PageUp. Thanks, this makes a lot of difference!

**Comment by justinclift** [comment]
Awesome.  Thanks @MKleusberg. :smile:
