### ISSUE TITLE
Cannot modify table structure ... fields get duplicated

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#975]
### Details for the issue

When a field is moved up or down, DB4S seems to duplicate all the fields.  If one of these fields is then moved, DB4S complains or crashes.

http://screencast-o-matic.com/watch/cbe1bF6UnC

This is on the last available nightly, 22 Jan 2017.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 x64___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: __Last available nightly (22 Jan 2017)_

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks Chris, should be fairly simple for @MKleusberg to fix. :smile:

**Comment by MKleusberg** [comment]
Oops, sorry! My bad! :smiley: Should be fixed now. Can you test if it's working for you?

If you notice any other problems with the table editing please open more issues, Chris. This really helps fixing all the fallout of my refactoring :+1:

**Comment by chrisjlocke** [comment]
Will check out tomorrows nightly.  :)

**Comment by justinclift** [comment]
Hmmm, the nightlies don't seem to be running, yet again.

Which is weird as I can literally see the box they run on from where I'm sitting, and it's in hibernation mode.  As it should be this time of the day.

Hmmm, I'll kick it again and see what's up.  I don't think it's the box itself though, but something is weird with the network switch such that it's not seeing it upon wakeup.  I've been getting the same thing with my desktop recently when coming out of sleep mode, needing to have the network cable pulled out + plugged in before network connection happens.  Not a good sign. 👼

**Comment by justinclift** [comment]
New nightlies are building now...

**Comment by chrisjlocke** [comment]
> Should be fixed now. Can you test if it's working for you?

Yes, works perfectly now thanks. 👍 🥇

**Comment by MKleusberg** [comment]
Thanks for testing :D
