### ISSUE TITLE
Nightly builds needs a 'latest' link on the server

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#977]
### Details for the issue

Issue is more for reminder purposes.
It would be handy if the nightly build repository had a 'latest' link (one per OS) pointing to the latest build.  This would make pointing to the latest build easier, and also help towards creating a pretty index of builds, as the list could be pre-built once a month.  Or something.  Anyway.  This is phase 1.

The final part of the current build scripts upload the new binaries to the server.
We can add a line to them, so that after uploading the new binary(s) it then creates/updates a soft link from "LATEST" → [newly uploaded file].

I can't do the above, so this is a 'prod' to Justin when he has a couple of mins free.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Prodding @justinclift ..... ;)   🖖

**Comment by justinclift** [comment]
Ahhh yeah, I'll need to muck with the OSX and Windows nightly upload script bits.  Adding this to the ToDo list so I don't forget. (may push it to next week though)

**Comment by chrisjlocke** [comment]
Thats fine - you have my permission.  🤺

**Comment by justinclift** [comment]
The nightly build scripts for OSX and Windows now add links for "LATEST" and "LATEST-SQLCipher" after uploading new builds each night:

* https://nightlies.sqlitebrowser.org/osx/
* https://nightlies.sqlitebrowser.org/win32/
* https://nightlies.sqlitebrowser.org/win64/

I'd personally prefer if they somehow just bounced to the correct one (eg an obvious link indicator, but still gives the correct daily download name), but it doesn't seem possible with Nginx.  Not even if we added in the [fancyindex module](https://www.nginx.com/resources/wiki/modules/fancy_index/).

@chrisjlocke Do you reckon the current approach is good enough?

**Comment by chrisjlocke** [comment]
I was going to build a flashy index myself, in a more 'calendar' view way,
linking to the various flavours, but with x32, x64, SQL-Cipher versions,
etc, it was a struggle not making it a link nightmare!

When you say 'bounced', do you mean when you click 'latest', it downloads 'DB
Browser for SQLite-2017-05-16-win64.exe
<https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-05-16-win64.exe>'
instead (because if I click 'latest' now, I get a 'latest' as a filename
(and thus broken as WIndows doesn'ty know what to do with it))

Is the server PHP-able?  Maybe I could create latest.php?

**Comment by justinclift** [comment]
Yep, that's exactly the thing.  The way Nginx seems to display soft links is as a direct file name, instead of redirecting people to the correct "LATEST" download. 😦 

For PHP (specifically)... I'd rather not have PHP anywhere in our infrastructure.  It's had too many bad security problems over the years - even in core code - for me to place it in a position of trust. eg public facing servers

Errr... feel like learning Go? 😁

**Comment by justinclift** [comment]
Hmmm, there might be an Nginx IRC channel or mailing list we can ask.  There's probably some way we can get this done without having to change the server from static pages to dynamic content.

**Comment by justinclift** [comment]
Oh.  I just realised something... we can indeed get this done, and in a simple way.

The current index page is an "autogenerated" one.  If however we supply our own "index.html", that'll be displayed instead.

So, we just need something which generates an appropriate static index.html page (once per night, after the uploads), and which has a decent "LATEST" link pointing to the correct latest binary.

**Comment by karim** [comment]
True. I tried to download it and i got a file with the name "LATEST" and no extension.

![latest](https://cloud.githubusercontent.com/assets/8761081/26111166/ad1043e6-3a54-11e7-91b3-8f852152f60d.jpg)

Maybe it can be done with a simple HTTP redirect? I didn't use Nginx in a long time, but maybe something like..

`/win64/lastest/ -> /win64/DB%20Browser%20for%20SQLite-(YYY-MM-DD)-win64.exe`

**Comment by chrisjlocke** [comment]
> Errr... feel like learning Go?

Is this something Go can do?  Never used it, so don't know what it can do.

**Comment by chrisjlocke** [comment]
> So, we just need something which generates an appropriate static
index.html page

That kinda defeats the purpose of what I was after... but looking at it,
its not going to work.
I was kinda hoping to redirect to DB Browser for SQLite-Nightly-win64.exe
<https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-05-16-win64.exe>
which
would be the 'latest'.  I can't see the benefit of putting a link to that
on the index page, as they'll have a view of all the downloads anyway.  I
was after a 'bookmark' link which would always download the latest. (useful
to put in support posts, rather than a long download link)....

Maybe 'latest' could be renamed as above?

**Comment by justinclift** [comment]
@karim @chrisjlocke Yep, I think this is doable.  Gimme an hour or two, and I might have a barebones approach we can look at to see if it's actually going to work.

**Comment by karim** [comment]
Okay, I misunderstood what @chrisjlocke meant. I got it now and I think it is easier and straightforward. Instead of a dynamic page or redirecting, we can use a simple **copy** to `latest` folder.

`https://nightlies.sqlitebrowser.org/latest/`

Right after building the installer, copy it to **latest** folder and remove the date from it, so it will be like..

`https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.exe`

This file will be overwritten (with the latest version) when the nightlies are built.

**Comment by justinclift** [comment]
Ahhhh.  I should have checked this issue before starting coding.

Yep, I misunderstood too.  The way you're describing sounds super simple and easy to implement.

I'll give it a shot now.

**Comment by justinclift** [comment]
So, something like this, and always with the most current entry (for each OS/architecture) in it?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/LATEST/

**Comment by karim** [comment]
Yes. Lowercase is fine too. 😄 

This might replace..

Nightly builds (for Mac/Win/Win64/etc) are available at:

- https://nightlies.sqlitebrowser.org/osx/
- https://nightlies.sqlitebrowser.org/win32/
- https://nightlies.sqlitebrowser.org/win64/

..with this in the README.md too

Nightly builds are available at:

- https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
No worries.  I'll make the name lowercase, and updating the scripting to copy the right bits in place.

We can look at the README after that too. :smile:

**Comment by chrisjlocke** [comment]
Thanks for your help you two.  Much appreciated.  🍶

**Comment by justinclift** [comment]
k, the scripting updates for both OSX and Windows are done, and appear to be working ok.  I've run the complete build scripts for both through once afterwards, and the builds are correctly being placed into the `/latest/` directory.

Lets keep this issue open until tomorrow, once we've seen a proper overnight run succeed on it's own.

Do either of you guys feel like doing a PR with the updates to README.md, and [index.html in gh-pages branch](https://github.com/sqlitebrowser/sqlitebrowser/blob/gh-pages/index.html) for the main website?

**Comment by karim** [comment]
I think @chrisjlocke wanted the filename to be *static*. The date in the filename is.. ahm.. pointless, as it's implied to be today's date. Also, more importantly, if someone linked to a file in `latest` folder, the link will be broken after 24 hours. 😄 

However, a link like this https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.exe will always refer to the latest windows 64-bit version, which can be bookmarked, or used in forums, IRC, issues here, and so on.

The general link https://nightlies.sqlitebrowser.org/latest is used to refer to *all* nightly build the same way this link https://github.com/sqlitebrowser/sqlitebrowser/releases refers to all releases.

*Example:*

Binaries can be downloaded from:

- https://github.com/sqlitebrowser/sqlitebrowser/releases

Nighty builds can be downloaded from:

- https://nightlies.sqlitebrowser.org/latest

**Comment by justinclift** [comment]
That totally makes sense.  The build script for both OSX and Windows have been updated to match.

I **think** we're ok now.  Let's take a look at the result of the scripts overnight though, just to make sure. :smile:

**Comment by justinclift** [comment]
Actually... should we use spaces or dots in between the words of "DB Browser for SQLite"?  The script can do either way.  It's set to spaces at the moment ("DB Browser for SQLite"), but it's trivial to change to dots ("DB.Browser.for.SQLite") if that'd be more useful.

**Comment by karim** [comment]
Both are fine, but I vote for dot. 😄 Spaces are not url-friendly.

**Comment by justinclift** [comment]
No worries. :smile:

We're now using dots for the `latest` directory then.

The `osx`, `win32`, and `win64` directories are still using spaces though, just because they have been so far. :wink:

**Comment by karim** [comment]
That's very good. 😄 👍

**Comment by justinclift** [comment]
The overnight builds went flawlessly for both OSX and Windows, with everything showing up as expected in the new [latest](https://nightlies.sqlitebrowser.org/latest/) nightlies directory.  So, closing this now. :smile:

Thanks for your persistence guys. 😀

**Comment by chrisjlocke** [comment]
Ditto, thanks Justin.

**Comment by justinclift** [comment]
Just remembered the README.md and main website need updating with the new location.  I'll get that done later today.

**Comment by justinclift** [comment]
k, now it's all complete. :smile:
