### ISSUE TITLE
file is encrypted or is not a database sqlite c#

### ISSUE THREAD

**Issue by govindrawat55** [sqlitebrowser/sqlitebrowser#978]
Once I encrypt the .db file from DB Browser, i am unable to read .db file from uwp application.

I am getting error like "**file is encrypted or is not a database**". Please help me.

Note : I am using "Sqlite.net-plc" for connect SQLite DB to UWP application.

**Comment by chrisjlocke** [comment]
DB Browser uses SQLCipher encryption.  Does Sqlite.net-plc support 256-bit AES?

**Comment by justinclift** [comment]
@govindrawat55 Sorry, somehow I missed this.

For encrypting SQLite databases, we use an Open Source project called SQLCipher.  It's made by Zetetic:

&nbsp; &nbsp; https://www.zetetic.net/sqlcipher/

I'm not sure if it's compatible with "SQLite.net-plc".  Are you ok to contact them to ask?

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by govindrawat55** [comment]
Thanks for your reply. Sorry for the late response. Today I have contacted the SQLCipher support to get it resolve.
[See link](https://discuss.zetetic.net/t/file-is-encrypted-or-is-not-a-database-sqlite-c/2814)
