### ISSUE TITLE
Add proxy support for DBHub.io connectivity

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#979]
We'll need to add support for common proxies (eg HTTPS, SOCKS 4/5 ?, etc) for our connectivity with DBHub.io.

Proxies are used in ***many*** business and government places, so missing this would be a major growth limiter. :wink:

**Comment by MKleusberg** [comment]
This is finally implemented now :smile: Are you ok to give it a quick test, just to confirm it's working on systems other than mine :wink:

**Comment by justinclift** [comment]
Yep, will try this out in the morning (getting sleep soon here).

For testing, my initial thought it to spin up a Squid server and use that.  What approach did you use for testing against when developing? :smile:

**Comment by MKleusberg** [comment]
I used the Tor client which I have installed anyway for testing. It provides a standard SOCKS 5 interface. And I used Wireshark to make sure the communication actually goes through the loopback interface when using the local tor client (plus that downloads become pretty slow when using Tor). So I was just using the tools I had installed anyway :smile: The HTTP proxy support is also completely untested.

By the way, Qt doesn't offer any SOCKS 4 support. So we probably won't be able to add that as well :frowning_man:

**Comment by justinclift** [comment]
Cool.  Yeah, SOCKS 4 was just from my remembering it being in the various other UI's for proxy stuff I've seen.  No idea if it's even used much in the real world. :smile:

**Comment by justinclift** [comment]
Tested with HTTP mode (using Squid 3.x on CentOS 7), which works fine.  Didn't set it up to need authentication, so not sure if that bit works.

I'll have a go through Tor later on too, just to check. :smile:

**Comment by justinclift** [comment]
@MKleusberg Any interest in writing an entry about the new proxy support for our blog?

**Comment by MKleusberg** [comment]
@justinclift Sorry, I completely missed that :frowning: I'll just point this out in the highlights section of the release notes instead. But I'll try to keep the blog thing in mind and write a blog post about the next dbhub.io features or similar stuff :smile:
