### ISSUE TITLE
Don't show selected table

### ISSUE THREAD

**Issue by voltento** [sqlitebrowser/sqlitebrowser#981]
### Details for the issue

"Data Structure -> table right click -> Browse table"  show first table but no seleted

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 10 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
What version of DB Browser for SQLite are you using?
Try one of the nightlies here:
https://nightlies.sqlitebrowser.org/win64/

I think this was an issue in v3.9.1 which was fixed.

**Comment by voltento** [comment]
You right, thank you.

**Comment by chrisjlocke** [comment]
\o/  Glad it worked. 👍
