### ISSUE TITLE
Cannot change case of a column name

### ISSUE THREAD

**Issue by prutz1311** [sqlitebrowser/sqlitebrowser#985]
### Details for the issue

When I have this table
![image](https://cloud.githubusercontent.com/assets/6525383/24325376/981b49ec-11a8-11e7-9c6d-4ad431612f50.png)
and try to change name `A` to `a`, it says `There already is a field with that name. Please rename it first or choose a different name for this field.`:
![image](https://cloud.githubusercontent.com/assets/6525383/24325393/f70f5114-11a8-11e7-9723-df96a3c9f50d.png)
However if I enter `A` it proceeds fine.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Xubuntu 14.04.5 LTS trusty)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [x] Other: 43a5175

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  @MKleusberg This'll be one for you. :smile:

**Comment by MKleusberg** [comment]
Should be fixed with the latest commit :smiley: Good catch by the way, @prutz1311 :+1:

**Comment by prutz1311** [comment]
Now it works properly.

**Comment by MKleusberg** [comment]
Thanks for testing, Oleg! :smiley:
