### ISSUE TITLE
Text color cannot be fixed in "Browse Data"

### ISSUE THREAD

**Issue by Chaolun-Chen** [sqlitebrowser/sqlitebrowser#990]
### Details for the issue
Hi,
DB Browser is useful and easy to use. I have one question about the text color.
The default text color in "Browse Data" is black. I always modify the default color to my favorite color, but these changes cannot be fixed. When I restart the application, these colors that I modified before are all set to default color(black).
Please help to solve this problem.
Thank you very much. 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: v14.12.4 )
- [ ] Other: ___

#### I'm using DB4S version:

- [V] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting. :smile:

If you try the latest nightly build, does it works properly for you?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/osx/

**Comment by Chaolun-Chen** [comment]
Hi justinclift
Thanks for your help. This problem is solved.
 I downloaded **DB Browser for SQLite_20170330.dmg**, and it works fine.

**Comment by justinclift** [comment]
Awesome. :smile:
