### ISSUE TITLE
Open new database

### ISSUE THREAD

**Issue by ofelius** [sqlitebrowser/sqlitebrowser#991]
When I open a new database I'm always asked to enter the key used to encrypt the data base file. but as I've never encrypt the file In don't know what to type?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
'Open a new database' - do you mean open an existing database, or create a new database?

If open an existing database, are you sure its a valid SQLite v3 database?  Its not a .sql file is it?  (ie, human readable SQL commands, rather than a database of records)

**Comment by chrisjlocke** [comment]
@ofelius Ping?

**Comment by chrisjlocke** [comment]
@ofelius ping?

**Comment by justinclift** [comment]
Meh, just going to close this.  9 days without response is generally a good sign the problem is fixed or no longer of interest to the reporter.

@ofelius If that's not the case, you're welcome to reopen this. :smile:
