### ISSUE TITLE
FTP issue (?) - can't open DB4S to transfer

### ISSUE THREAD

**Issue by bjm4054** [sqlitebrowser/sqlitebrowser#993]
### Details for the issue

I created a simple db with 5 tables.  I can view and update it locally (through command-line or DB4S), but when I try to place the .db file on my school server, I hit the following:

Error:	local: unable to open C:\RIT\ISTE_646\rogue6_project1\RIT-esports\db\sqlite\sqlite-tools-win32-x86-3180000\ESports.db
Error:	Critical file transfer error

None of the other files in the project are having this problem, and I transferred an earlier version of the same db a few days ago with no apparent issue.  When I deleted the entire project from the server and started over, every other folder and file transferred successfully.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [X] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( 7 version: Professional / Service Pack 1, ca 2009 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
This is a bit unclear. :wink:

DB4S doesn't natively support FTP itself... so I'm not sure what you're meaning.

Are you ok to explain in a bit more depth? :smile:

**Comment by bjm4054** [comment]
Sorry, should have been more clear.  I originally created my SQLite db from the command-line, and was able to upload it to RIT using FileZilla no problem.  I decided to revamp the schema, so I deleted the file from the server.  In the meantime, I installed DB4S, and recreated the db through the UI.  I have no idea whether that's a factor, but now when I try to upload the file, I get the above error.

**Comment by justinclift** [comment]
k, still needing a bit more information. :smile:

First, what's "RIT"?

Next, what's the exact error message you're getting?  Maybe screenshot it if there's no confidential info in it?

**Comment by justinclift** [comment]
Ahhh, just noticed that you do have the info in the original bug report, it's just inside the javascript hiding brackets.  I'll remove those and it should show up...

**Comment by justinclift** [comment]
Ahhh, the "unable to open" bit might be helpful.  It kind of sounds like the file permissions (or maybe ownership) of the file itself are causing an issue:

"unable to open C:\RIT\ISTE_646\rogue6_project1\RIT-esports\db\sqlite\sqlite-tools-win32-x86-3180000\ESports.db"

Maybe double check that?  If there's nothing obvious there, I'd ping one of the school admins and ask if there's a likely reason.  This is almost definitely not something related to DB4S itself.

Oh... unless DB4S is still running and has the database open when you're trying the transfer?  If that's the case, there could be a file lock problem.  eg close DB4S and try again maybe? :smile:

**Comment by bjm4054** [comment]
You, sir, are one of the good things in this life.  I closed out of DB4S and still had the problem.  When I exited sqlite3 from the shell, I was able to upload successfully.  Thanks very much.

**Comment by justinclift** [comment]
Awesome, glad it worked. :smile:
