### ISSUE TITLE
Formatting date columns

### ISSUE THREAD

**Issue by treddy73** [sqlitebrowser/sqlitebrowser#996]
I'm looking at a sqlite database generated from iOS Core Data.  I would like some help trying to format the date columns into a human readable format.  Currently, I just see a 9 digit numeric value.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [X] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( Sierra )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
No worries.  Two thought come to mind right away... :smile:

* Not sure if you've tried this yet, but you can right click on the heading for a column and choose **Edit display format**.

There are several pre-made formats listed, one of them might work.  It's probably a good idea to try [a recent nightly build](https://nightlies.sqlitebrowser.org/osx/) too, as (from memory) there were some more formats added after the 3.9.1 release.

* If that doesn't work, are you able to cut-n-paste some of the 9 digit values here as an example for us to think on? :smile:

**Comment by chrisjlocke** [comment]
Try `select *, format(fieldName,'YYYY-MM-DD') from tableName`

https://www.w3schools.com/sql/sql_func_format.asp

**Comment by treddy73** [comment]
Thanks for the quick feedback.  It seems that clicking the column header only works in the "Browse Data" tab and not from the "Execute SQL" tab.  After changing the formatting from the Browse Data tab, it doesn't seem to apply to the columns in Execute SQL.

At any rate, I have a couple of options as a workaround.

Thanks!

**Comment by chrisjlocke** [comment]
You also use SQL.

`select date(2457864)` or
`select date(fieldName)`

`select date(2457864)` would return todays date.  The `date()` function returns YYYY-MM-DD format, but you can change this.

https://sqlite.org/lang_datefunc.html

**Comment by justinclift** [comment]
Awesome @chrisjlocke. :smile:

@treddy73 When you've got it worked out, are you ok to close this issue?  (am just trying to keep the open issue count not completely out-of-control :wink:)
