### ISSUE TITLE
Records flipped after viewing the table's record.

### ISSUE THREAD

**Issue by kyliostricor** [sqlitebrowser/sqlitebrowser#997]
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Hi @kyliostricor, when you say "flipped" that's a bit unclear.  Are you ok to take a screenshot?

**Comment by justinclift** [comment]
As a thought, is there any chance you've clicked on a column header in the Browse Data tab?

If so, that causes the rows to be sorted by that column.  An arrow shows up showing the direction, and you can click the same column heading again to sort in the opposite direction.

Not sure if that's what's happening here, but the concept seems kind of like what you're mentioning. :smile:

**Comment by kyliostricor** [comment]
Well... fuck... I am soo dumb!

Thank you, that really helped.

**Comment by justinclift** [comment]
No worries at all @kyliostricor, we all start at the beginning. :smile:
