### ISSUE TITLE
After updating a row changes not reflected in browser.

### ISSUE THREAD

**Issue by nextdimension** [sqlitebrowser/sqlitebrowser#998]
After updating the row in my database with my own script, and despite my database actually is updated with the correct data, when I view the database in sqlite browser the changes are not reflected. I deleted the original database from everywhere and restarted and I get the same results.

If I uninstall sqlite browser and reinstall, then the changes appear, tried to uninstall again and this time it didnt even work the changes do not appear.

**Comment by justinclift** [comment]
Interesting.  A couple of questions, just to get a better idea of things... :smile:

* Which version of DB4S (our abbreviation for SQLite Browser) are you using?
* After making the change with your own script, are you closing the reopening the database in DB4S?
* After making the change with your own script, are you quitting out of DB4S, starting it up again, and reloading your database?
* Is your database on an external device?  For example an Android phone or tablet or something?

The answers to those should help us figure out what's going on. :smile:

**Comment by nextdimension** [comment]
-  Version of DB4S is 3.9.1.
- Yes
- Yes
- Yes

1. Pull the database directly from my Android device using ADB. 
2. Close DB4S and delete the local database, before reopening to view the new database.
3. Verified in my application on the device that the data is updated.
4. Use an app browser on the device to verify the data is indeed updated.
5. Copy the database from the device, and compress to an archive, copy archive to local storage
6. and repeat from the #1 of the this list. 

Result is always the same: DB4S is not showing the updated data.

**Comment by justinclift** [comment]
In theory (!) it should work.  But for some unknown reason, Android devices are occasionally reported to not copy database files correctly.  (not just for us, but in general)

It's been going on for a few years now, so there's a decent chance someone has worked out a solution or fix to the problem.  I don't use Android, so it's not something I've ever really come across myself. (sorry)

**Comment by chrisjlocke** [comment]
> Pull the database directly from my Android device using ADB

What's ADB?  
On what platform are you using DB4S? (not that that makes a huge difference, but just in case...)
If you amend the database, does the file have an updated modified date?

**Comment by justinclift** [comment]
ADB → https://developer.android.com/studio/command-line/adb.html

**Comment by justinclift** [comment]
This may be the problem:

https://stackoverflow.com/questions/9058169/sqlite-database-disk-image-is-malformed-on-windows-but-fine-on-android

As pointed out by @MKleusberg [last year](https://github.com/sqlitebrowser/sqlitebrowser/issues/476#issuecomment-168403277).

**Comment by nextdimension** [comment]
Ahh thank you, I did wonder if it was because of wall mode. I think that's
the culprit, will check.

**Comment by nextdimension** [comment]
Yep it because of WAL mode. When disabling WAL mode everything works great, all updates are reflected just fine when exporting the database from my device. Thanks for the help.

**Comment by justinclift** [comment]
DB4S itself definitely uses WAL.

That being said, it's sounding like there's a bad interaction with DB4S + WAL + ADB.  We might be the culprit, or we might not (no idea).  At least there's a workaround for now though. 😁

**Comment by chrisjlocke** [comment]
@quantuminformation - how did you update the data - via another process?  An external program?
Do you mean data updates or schema updates?
If another program has updated the data, sometimes changing tabs can help.  Or changing table to a different table and back again.

**Comment by quantuminformation** [comment]
I have a node process that updated the db

data only updates if i reconnect to the db:

https://youtu.be/HN1zJzhr7wY?t=83

**Comment by chrisjlocke** [comment]
Well, that kind of makes sense - sqlite isn't a multi-user system, so it caches bits in memory.  If you go to the 'execute sql' tab and issue a statement, that would be up to date when you press F5 (or re-execute) the statement as that physically pulls the data back from the database.  The 'browse data' tab caches data in the grid so probably isn't what you're after.

**Comment by quantuminformation** [comment]
ok thx
