### ISSUE TITLE
Sqlitebrowser is using SQLite 3.15.2 instead of installed 3.18.0

### ISSUE THREAD

**Issue by mburger81** [sqlitebrowser/sqlitebrowser#999]
### Details for the issue
I'm using a Kubuntu 17.04 system where I manually installed sqlite3.18 and manually libsqlite3.18, for example our JDBC driver now loads the installed system lib which is 3.18.
On opening SqliteBrowser 3.9.1 under the about window I get the information the loaded SQliteVersion is 3.15.2

Where is the browser loading the sqlite implementation? The system one, and if yes where is it loading from the system, because it is not the default one, or is the 3.15.2 included in sqlitebrowser? If yes, can you please upgrade version?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( (K)Ubuntu: 17.04 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
You could download /build the latest sqlite precompiled binary from this page:
https://sqlite.org/download.html

You can then replace the sqlite3.dll (well, for my Windows installation... I guess the Linux files may differ...) in the application directory.

This worked for me, but DB Browser for SQLite still showed the old version of SQLite in the about box...
![image](https://cloud.githubusercontent.com/assets/7872218/25335062/41b76c4a-28e9-11e7-9008-586a5d38cf85.png)

**Comment by justinclift** [comment]
@mburger81 Ahhhh, you'll probably need to compile DB4S (our abbreviation for our software) yourself, and use some environment variables to point the build process towards the SQLite version you installed.

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

From memory though, those instructions might be a bit out of date.  I think (without trying it recently), the command to run is "qmake" not "cmake".  You might need to experiment a bit... :wink:

**Comment by jungle-boogie** [comment]
I have this same problem, too. I don't know qmake/cmake well enough to know what kind of configuration option to pass in to point it to the correct sqlite3 files.

I have sqlite3 installed and compiled from src: `SQLite version 3.19.0 2017-04-29 19:29:49`

**Comment by justinclift** [comment]
I've added an item related to this for my ToDo list for this week.  For that I'll update our Linux compile instructions, and also figure out the environment variables (or whatever else) is needed for using a custom installation of SQLite or SQLCipher: https://github.com/sqlitebrowser/dbhub.io/issues/32

**Comment by mburger81** [comment]
@justinclift That would be really great!! thx a lot!

**Comment by justinclift** [comment]
No worries. 😄

This may be pushed to next week (after looking at fairly immediate/urgent tasks), but it's of high importance so it won't be passed over.

**Comment by jungle-boogie** [comment]
Hi @justinclift,

Have you had a chance to update the docs?

**Comment by justinclift** [comment]
I've made a decent start on going through the docs from a Qt Creator perspective here:

* https://github.com/sqlitebrowser/sqlitebrowser/wiki/Compiling-on-Ubuntu-16.04-with-Qt-Creator

... but haven't yet gotten up to the point of determining how to override the system provided SQLite.

While doing that, I found that - unlike our CMake configuration - using `qmake` didn't install all of the required files.  It's since been adjusted to also include the "desktop" related files so it will show up in the menu.  But as @MKleusberg pointed out we still needs to add the translation files to `make install` as they're not installed yet either.

If someone has the time and inclination to muck around with changing the [likely relevant lines](https://github.com/sqlitebrowser/sqlitebrowser/blob/7ad80352616df1b185ab87f989cb7c2fd6c784c5/src/src.pro#L139-L140) in src.pro, it would probably work to find a user-installed version of SQLite.

Note that the link there I gave is inside a `mac` clause.  So, a similar definition would need to be added for linux ("unix" maybe?) for that to be picked up on.  I'm not 100% sure of the bits needed yet, but some trial and error would get it worked out.

Timeline wise, my headspace is deeply into DBHub.io stuff at the moment.  We need to get that in a useful/usable state for people in time for DB4S 3.10, and there are still major bits of it needing doing.  I'm almost certainly going to be working on my focus task for that (a new backend data model) through to the end of next week.  After that I may be able to pick this up again, or I may need to continue getting other DBHub.io bits done first.  Not yet sure. 😉 

Does that help?

**Comment by MKleusberg** [comment]
As fas as I understand you have (at least) two versions of the SQLite, @mburger81, the system version that was installed using the package manager and the manually installed version. During compilation we just statically link to the first library version we can find. In your case that should be the system one.

So what you'll need to do is recompile DB4S and configure the build to search for the manually installed SQLite version. How exactly this works depends on how you've built SQLite but the general idea is like this.

Edit the src/src.pro file. Around line 196 you should find these lines:
```
INCLUDEPATH += $$PWD/../libs/antlr-2.7.7 $$PWD/../libs/qhexedit $$PWD/../libs/qcustomplot-source $$PWD/../libs/qscintilla/Qt4Qt5 $$PWD/..
LIBS += -L$$LIBPATH_QHEXEDIT -L$$LIBPATH_ANTLR -L$$LIBPATH_QCUSTOMPLOT -L$$LIBPATH_QSCINTILLA -lantlr -lqhexedit -lqcustomplot -lqscintilla2
```
Change them to
```
INCLUDEPATH += /path/to/your/sqlite/lib/header/files $$PWD/../libs/antlr-2.7.7 $$PWD/../libs/qhexedit $$PWD/../libs/qcustomplot-source $$PWD/../libs/qscintilla/Qt4Qt5 $$PWD/..
LIBS += -L/path/to/your/sqlite/lib/a/file -L$$LIBPATH_QHEXEDIT -L$$LIBPATH_ANTLR -L$$LIBPATH_QCUSTOMPLOT -L$$LIBPATH_QSCINTILLA -lantlr -lqhexedit -lqcustomplot -lqscintilla2
```
Where the first path points to the directory that contains the ```sqlite3.h``` file and the second path points to the directory that contains the ```libsqlite3.a``` file.

Then just run this from the root dir of the repository to build the application:
```
qmake
make
```

If you want to use cmake, you'll have to edit the ```CMakeLists.txt``` file and change line 252
```
find_library(LIBSQLITE ${LIBSQLITE_NAME})
```
to this
```
find_library(LIBSQLITE ${LIBSQLITE_NAME} HINTS /path/to/your/sqlite/lib/a/file)
set(ADDITIONAL_INCLUDE_PATHS /path/to/your/sqlite/lib/header/files)
```
And then run this from the root dir of the repository:
```
mkdir build
cd build
cmake ..
make
```

**Comment by jungle-boogie** [comment]
The steps provided by @MKleusberg worked great! Now my sqlitebrowser from git master is in sync with my sqlite version.

Thanks!

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by MKleusberg** [comment]
Cool :smile: Glad I could help :wink:

@justinclift Shall we add a Wiki page for this?

**Comment by justinclift** [comment]
@MKleusberg Definitely.  I'm buried in [other stuff atm](https://github.com/justinclift/dio/commits/master), but maybe @chrisjlocke or @karim or someone has some time to make the appropriate cut-n-pastes? :smile:

**Comment by chrisjlocke** [comment]
[Done](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Compiling-DB4S-on-Ubuntu-To-Use-A-Pre-Installed-Version-of-SQLite), and added to the front page.

**Comment by justinclift** [comment]
Perfect @chrisjlocke.  Just looked over it and it's really good. :smile:

**Comment by chrisjlocke** [comment]
> and it's really good.

Lol... copy and pasted, so thank @MKleusberg ! ;)  Oh, we already have done.  We'd better not give him too
 much praise..... ;) 🐕

**Comment by MKleusberg** [comment]
Why not? :P

**Comment by chrisjlocke** [comment]
To cure 'Big Head Syndrome' required the use of a big needle.  Taken rectally.

![image](https://user-images.githubusercontent.com/7872218/27230016-b94cb400-52a5-11e7-836d-38dec403b819.png)

**Comment by justinclift** [comment]
Eeeeewwwww!

**Comment by MKleusberg** [comment]
Haha, I see :wink:
